### ISSUE TITLE
Flutter engine randomly crashes on Android after upgrading to latest stable (2.2.3)

### ISSUE THREAD

**Issue by yrom** [flutter/flutter#86692] opened 2021-07-20 03:34 UTC
After upgrading to Flutter 2.2.3 from 1.22.5, some Android customers using my app reported this crash. 

Logs: 
Fatal signal 11 (SIGSEGV), code 0, fault addr 0x283c0000655a in tid 26077 (1.ui)

<details> <summary> Crash dump:</summary>
<pre>
#00 0x0000000000068b5c /system/lib64/libc.so (pthread_mutex_lock+0) [arm64-v8a::cd3d46e93276d051074b8ef45bcf9d3b]
#01 0x00000000004ed458 /data/app/com.bilibili.comic-DUR2Rl25i_IO3xwpT_ch4A==/lib/arm64/libflutter.so 
dart::Monitor::Enter()
    src/out/android_release_arm64/../../third_party/dart/runtime/vm/os_thread_android.cc:420:16
dart::MonitorLocker::MonitorLocker(dart::Monitor*, bool)
    src/out/android_release_arm64/../../third_party/dart/runtime/vm/lockers.h:143:15
dart::MessageHandler::HandleNextMessage()
    src/out/android_release_arm64/../../third_party/dart/runtime/vm/message_handler.cc:288:17
Dart_HandleMessage
    src/out/android_release_arm64/../../third_party/dart/runtime/vm/dart_api_impl.cc:2037:29
tonic::DartMessageHandler::OnHandleMessage(tonic::DartState*)
    src/out/android_release_arm64/../../flutter/third_party/tonic/dart_message_handler.cc:113:14
tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0::operator()() const
    src/out/android_release_arm64/../../flutter/third_party/tonic/dart_message_handler.cc:42:37
decltype(std::__1::forward<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&>(fp)()) std::__1::__invoke<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&>(tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&)
    src/out/android_release_arm64/../../third_party/libcxx/include/type_traits:3530:1
void std::__1::__invoke_void_return_wrapper<void>::__call<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&>(tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&)
    src/out/android_release_arm64/../../third_party/libcxx/include/__functional_base:348:9
std::__1::__function::__alloc_func<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0, std::__1::allocator<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0>, void ()>::operator()()
    src/out/android_release_arm64/../../third_party/libcxx/include/functional:1533:16
std::__1::__function::__func<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0, std::__1::allocator<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0>, void ()>::operator()()
    src/out/android_release_arm64/../../third_party/libcxx/include/functional:1707:12
#02 0x00000000002d796c /data/app/com.bilibili.comic-DUR2Rl25i_IO3xwpT_ch4A==/lib/arm64/libflutter.so 
std::__1::function<void ()>::operator()() const
    src/out/android_release_arm64/../../third_party/libcxx/include/functional:2419:12
fml::MessageLoopImpl::FlushTasks(fml::FlushType)
    src/out/android_release_arm64/../../flutter/fml/message_loop_impl.cc:130:5
fml::MessageLoopImpl::RunExpiredTasksNow()
    src/out/android_release_arm64/../../flutter/fml/message_loop_impl.cc:143:3
#03 0x00000000002d9da8 /data/app/com.bilibili.comic-DUR2Rl25i_IO3xwpT_ch4A==/lib/arm64/libflutter.so 
fml::MessageLoopAndroid::OnEventFired()
    src/out/android_release_arm64/../../flutter/fml/platform/android/message_loop_android.cc:92:5
fml::MessageLoopAndroid::MessageLoopAndroid()::$_0::operator()(int, int, void*) const
    src/out/android_release_arm64/../../flutter/fml/platform/android/message_loop_android.cc:42:52
fml::MessageLoopAndroid::MessageLoopAndroid()::$_0::__invoke(int, int, void*)
    src/out/android_release_arm64/../../flutter/fml/platform/android/message_loop_android.cc:40:40
#04 0x0000000000016054 /system/lib64/libutils.so (android::Looper::pollInner(int)+856) [arm64-v8a::c3cbd04f94cdd09f36ab242a7f5863ff]
#05 0x0000000000015c74 /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+108) [arm64-v8a::c3cbd04f94cdd09f36ab242a7f5863ff]
#06 0x000000000000e7d4 /system/lib64/libandroid.so (ALooper_pollOnce+96) [arm64-v8a::ea8be8e37a4dd0e2224c8af467a24262]
#07 0x00000000002d9eb8 /data/app/com.bilibili.comic-DUR2Rl25i_IO3xwpT_ch4A==/lib/arm64/libflutter.so 
fml::MessageLoopAndroid::Run()
    src/out/android_release_arm64/../../flutter/fml/platform/android/message_loop_android.cc:68:18
#08 0x00000000002d6bf8 /data/app/com.bilibili.comic-DUR2Rl25i_IO3xwpT_ch4A==/lib/arm64/libflutter.so 
fml::MessageLoopImpl::DoRun()
    src/out/android_release_arm64/../../flutter/fml/message_loop_impl.cc:0:3
fml::MessageLoop::Run()
    src/out/android_release_arm64/../../flutter/fml/message_loop.cc:49:10
#09 0x00000000002d8924 /data/app/com.bilibili.comic-DUR2Rl25i_IO3xwpT_ch4A==/lib/arm64/libflutter.so 
fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const
    src/out/android_release_arm64/../../flutter/fml/thread.cc:35:10
decltype(std::__1::forward<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fp)()) std::__1::__invoke<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0&&)
    src/out/android_release_arm64/../../third_party/libcxx/include/type_traits:3530:1
void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>&, std::__1::__tuple_indices<>)
    src/out/android_release_arm64/../../third_party/libcxx/include/thread:341:5
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*)
    src/out/android_release_arm64/../../third_party/libcxx/include/thread:351:5
#10 0x0000000000068178 /system/lib64/libc.so (__pthread_start(void*)+36) [arm64-v8a::cd3d46e93276d051074b8ef45bcf9d3b]
#11 0x000000000001f280 /system/lib64/libc.so (__start_thread+68) [arm64-v8a::cd3d46e93276d051074b8ef45bcf9d3b]
</pre>
</details>

Crashes devices:
![image](https://user-images.githubusercontent.com/2888674/126256649-4c13f72c-e818-4ff3-92d4-e92c59f31e07.png)

Unfortunately, I don’t know how to reproduce this crash. 
I guess it might be related to the `FlutterEngineGroup`.
In my app, FlutterEngineGroup may create more than 2 Flutter engine instances for multiple FlutterActivitys.

Flutter version:
```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (3 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

**Comment by TahaTesser** [comment] 2021-07-20 07:56
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/86692#issue-948215885 flutter#v2.2.3 force ios release arm64

**Comment by TahaTesser** [comment] 2021-07-20 07:57
@flutter-symbolizer-bot #86692 (comment) flutter#v2.2.3 force android release arm64

**Comment by TahaTesser** [comment] 2021-07-20 07:58
@flutter-symbolizer-bot  https://github.com/flutter/flutter/issues/86692#issue-948215885

**Comment by TahaTesser** [comment] 2021-07-20 08:01
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/86692#issue-948215885

**Comment by TahaTesser** [comment] 2021-07-20 08:02
Hi @yrom 
Can you please provide your `flutter doctor -v` and your complete `crash logs`
Thank you

**Comment by yrom** [comment] 2021-07-20 09:28
Hi @TahaTesser, the complete crash log has been submitted and re-symbolized. The log was collected from crash reporting tools like Firebase Crashlytics. 

I think it has nothing to do with the Flutter environment on my computer.
<details> <summary>flutter doctor -v</summary>
<pre>
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1217 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/wangyongrong/Library/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/wangyongrong/Documents/Android-SDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/wangyongrong/Documents/Android-SDK
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H1217 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114
</pre>
</details>

**Comment by chinmaygarde** [comment] 2021-07-26 17:54
cc @a-siva. The stack trace seems to indicate this is an issue in Dart. But I am not sure how the engine got into this situation. If you are not able to reason about the issue from the trace, we might need a reproducible test case.

**Comment by a-siva** [comment] 2021-07-26 20:33
The backtrace seems to be indicate that the monitor_ field in the message handler class is corrupted. That is odd, it could be in an uninitialized state if the isolate was just being initialized or was shutting down. The crash log seems to have the backtrace of only the current thread, is it possible to get a backtrace of all the threads to see if either of these conditions is possible ?

**Comment by chinmaygarde** [comment] 2021-07-27 19:22
@yrom Would it be possible to get the backtraces of all threads? BTW, does this happen on iOS as well? I've seen crash dumps on that platform contain traces of all threads. So correlating with the iOS version of this crash would be super useful.

**Comment by yrom** [comment] 2021-07-28 04:47
@chinmaygarde So sorry, there is no more useful stacktrace of the other threads. And it happen only on Android.

The activity stack when crash occurs:
```
FlutterActivity1 onCreated
FlutterActivity1 onResumed
FlutterActivity1 onPaused
FlutterActivity2 onCreated
FlutterActivity2 onResumed
FlutterActivity2 onPaused
FlutterActivity2 onResumed
FlutterActivity2 onPaused
FlutterActivity2 onDestoryed
```
The FlutterActivity in my app uses FlutterEngine created by FlutterEngineGroup, just like the sample code https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters/multiple_flutters_android 
And the FlutterEngine will not be destroyed on FlutterActivity destroyed.

I'm trying to find the way to reproduce.

**Comment by linroid** [comment] 2022-06-08 11:52
@yrom Are you still having this issue? I solved by adding the following code into `DartMessageHandler::OnHandleMessage`, it happens on exiting flutter engine with using `FlutterEngineGroup`

<img width="670" alt="image" src="https://user-images.githubusercontent.com/3192142/172609437-d9dbda75-508a-41fc-9817-353b32d79cae.png">

cc @chinmaygarde @a-siva

**Comment by jonahwilliams** [comment] 2024-08-08 08:55
Closing as obsolete

**Closed by jonahwilliams** 2024-08-08 08:55 UTC
Labels: platform-android, engine, dependency: dart, a: production, P2, c: fatal crash, team-android, triaged-android
