### ISSUE TITLE
devicelab tests should run on presubmit for release branches

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#91926] opened 2021-10-15 20:21 UTC
Usually release branches require multiple patches to infrastructure to work and if those patches are required to make devicelab tests run we won't know until they fail on post-submit which is already too late.

This usually forces us to trigger 50+ tests manually.

**Comment by CaseyHillers** [comment] 2021-11-19 19:58
We could add `bin/` to the run if for the devicelab presubmit tests

**Comment by CaseyHillers** [comment] 2021-12-01 17:49
@godofredoc is this a duplicate of https://github.com/flutter/flutter/issues/92306?

**Comment by CaseyHillers** [comment] 2021-12-10 00:56
Closing as next stable will include a ci.yaml that runs the hot reload tests on Linux_android and Mac_ios

**Closed by CaseyHillers** 2021-12-10 00:56 UTC
Labels: passed first triage, team: infra, passed secondary triage
