### ISSUE TITLE
image_picker -  requiring to choose only gallery or camera

### ISSUE THREAD

**Issue by acidjazz** [flutter/flutter#18416] opened 2018-06-12 20:09 UTC
While I see the benefits of wanting to get images from only the camera or gallery, I really liked having the option prior to this of letting the user use both, and this restriction now has to force people that use to it to prompt the user in the app.

**Comment by zoechi** [comment] 2018-06-13 10:02
@Hixie

**Comment by roughike** [comment] 2018-06-18 11:39
There was no "both" option before - it was just a prompt on iOS asking the user to choose either camera or photo library. On Android, it was a custom UI coming from a third party library. This was removed in flutter/plugins#423 by me, in favor of using the native Android system gallery for picking images.

I would say this is "not a bug, but a feature" - it's up to you to come up with an UI letting the user choose the image source. The simplest option for this would be an AlertDialog. I think it's not the responsibility of the `image_picker` plugin to handle displaying the "Select an image source" prompts.

cc: @Hixie, @goderbauer, @jonahwilliams, @mit-mit who all were involved in the discussion of the original PR.

See also: https://groups.google.com/forum/#!topic/flutter-dev/YE5tM2Y0BP8

**Comment by goderbauer** [comment] 2018-06-18 17:13
I agree with what @roughike said. It should be fairly simple to implement the appropriate UI to switch between the two sources in your app.

**Comment by acidjazz** [comment] 2018-06-18 20:06
When I use other apps or browsers on iOS, I get a bottom-aligned native modal asking either to take a photo, or go tot he library.  

When I do the same on Android I get an image/photo browser with a CTA being "take a picture".

Are these not native and global solutions we can tap into? While I agree it is fairly simple to write our own, I still don't see requiring the option to re-invent the wheel again.

**Comment by lukaspili** [comment] 2018-06-19 14:31
Also this is exactly how it works on both natives SDK. It's up to the developer to choose a UI component such as a dialog or a bottom action sheet to ask for the image source.

**Comment by acidjazz** [comment] 2018-06-19 20:43
If there is no native solution for both iOS and Android on allowing the user to choose between the camera and/or gallery natively then I'll happily close this issue since that would make it invalid.

**Comment by cyanglaz** [comment] 2019-04-25 23:38
@acidjazz There is no native solution for either iOS or Android for this. I am going to close this issue. If you find a way to do it, please open an issue with your suggestion in details and we will be happy to review it!

**Closed by cyanglaz** 2019-04-25 23:38 UTC
Labels: p: first party, p: image_picker, plugin, severe: new feature

**Comment by d-silveira** [comment] 2019-10-01 09:46
for those of us frustrated with this issue, try this plugin: https://pub.dev/packages/media_picker
