### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process., errno = 32

### ISSUE THREAD

**Issue by CrezyProgrammer** [flutter/flutter#69537] opened 2020-11-01 19:58 UTC
## Command
```
flutter build web --release
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: The process cannot access the file because it is being used by another process.
, errno = 32
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:201:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:455:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:389:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:486:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:388:12)
#6      buildWeb (package:flutter_tools/src/web/compile.dart:41:21)
<asynchronous suspension>
#7      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:91:11)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1005:18)
#9      _rootRunUnary (dart:async/zone.dart:1198:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#15     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#16     _rootRun (dart:async/zone.dart:1190:13)
#17     _CustomZone.run (dart:async/zone.dart:1093:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.17763.864], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\src\flutter
    • Framework revision 198df796aa (2 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\masum2\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\masum2\Desktop\android-studio-ide-181.5056338-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\masum2\Desktop\android-studio-ide-181.5056338-windows\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 198df796aa80073ef22bdf249e614e2ff33c6895

**Comment by pedromassangocode** [comment] 2020-11-02 08:33
Hi @CrezyProgrammer 
This is a duplicate of https://github.com/flutter/flutter/issues/69109 and a recent fix (PR https://github.com/flutter/flutter/pull/69115) has landed on master channel.

Can you please try on master?

**Comment by pedromassangocode** [comment] 2020-11-24 10:03
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-24 10:03 UTC
Labels: in triage, waiting for customer response
