### ISSUE TITLE
'@' and all Special character reverses the string inside text widget in RTL text direction 

### ISSUE THREAD

**Issue by dev-devarsh4** [flutter/flutter#133317] opened 2023-08-25 09:00 UTC
When i use textDirection: TextDirection.rtl in TextField and type any special character the is automatically set to last position
![Screenshot 2023-08-25 at 2 28 25 PM](https://github.com/flutter/flutter/assets/126959872/66bf967b-b642-4277-aaaf-6ad65a61e767)

https://github.com/flutter/flutter/assets/126959872/5bf3887e-9eee-4886-bc07-62a18718aa88

**Comment by dam-ease** [comment] 2023-08-25 10:21
Hi @dev-devarsh4. Thanks for filing this issue. Per this https://github.com/flutter/flutter/issues/74302#issuecomment-807972898, this seems to be the expected behaviour.
Closing this since this isn't a bug, if you disagree, kindly comment and I'll reopen this.
Thank you!

**Closed by dam-ease** 2023-08-25 10:21 UTC
Labels: in triage

**Comment by dev-devarsh4** [comment] 2023-08-27 06:59
Hello @dam-ease Thanks for your response I can understand this behavior is natural.
And there is no need to reopen this issue
