### ISSUE TITLE
ChoiceChip does not expand correctly for multiline Texts  

### ISSUE THREAD

**Issue by ansolantz** [flutter/flutter#73494] opened 2021-01-07 17:57 UTC
## Issue

When using a multiline Text widget inside a `ChoiceChip`, there are cases where the Chip does not expand correctly.
Please find a minimal example below. 

The first screenshot ending with the letters abc does not create the fifth line in the ChoiceChip. 

<img width="399" alt="not_ok" src="https://user-images.githubusercontent.com/48385990/103925165-66756780-5117-11eb-8793-6bd64c4e19f3.png">

However adding an extra letter, in this case “d” correctly shows the fifth line as per the second screenshot.

<img width="392" alt="ok" src="https://user-images.githubusercontent.com/48385990/103925142-61181d00-5117-11eb-8205-66b57ce29372.png">

This code reproduces the issue on 1.22.5. The only thing you have to do is add and remove a letter to the text string.

## Steps to Reproduce

```
 @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: Container(
          width: 300,
          child: ChoiceChip(
            label: Text(
                "The earliest known appearance of the phrase is from The Boston Journal. In an article titled Current Notes in the February 9, 1885, edition, the phrase is mentioned as a good practice sentence for writing students: A favorite copy set abcdefghijklmnopqrst abcde",
                overflow: TextOverflow.visible,
                maxLines: 10,
                softWrap: true),
            selected: false,
            onSelected: (_) {},
            clipBehavior: Clip.none,
          )),
    ));
  }
```

**Expected results:** 
As in the second screenshot.

**Actual results:** 
See first screenshot.

Suggestions for a workaround would also be appreciated.

<details>
  <summary>Logs</summary>

```
```

```
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E266 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/yc00025/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/yc00025/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/yc00025/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • 841D3C4B-4403-4EDC-92ED-5CEA611616F2 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2
      (simulator)

</details>

**Comment by pedromassangocode** [comment] 2021-01-08 08:59
Hi @ansolantz 
Looks like you are using an old Flutter version.
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the issue persists, please provide your `flutter doctor -v`.
Thank you

**Comment by ansolantz** [comment] 2021-01-08 10:07
Hi @pedromassango 

Thanks for the fast reply. I have updated to 1.22.5 and the issue persists. I have also added a fixed width to the Container in the example code above. I am testing on an iPhone 11 simulator but now with the fixed width, I assume it is reproducible on other devices as well.

**Comment by pedromassangocode** [comment] 2021-01-08 14:08
I was able to reproduce the issue on latest master and stable channel.

![Screen Shot 2021-01-08 at 15 00 46](https://user-images.githubusercontent.com/67424416/104024337-43a08d00-51c3-11eb-9219-d92abf09ea54.png)

<details><summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

<details><summary>flutter doctor (master)</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.251, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.251 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 5bc725bea8 (7 hours ago), 2021-01-08 08:12:36 +0100
    • Engine revision 2e5833b7c5
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11
      (API 30) (emulator)
    • macOS (desktop)            • macos         • darwin-x64     • Mac OS X
      10.15.7 19H2 darwin-x64
    • Chrome (web)               • chrome        • web-javascript • Google
      Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```
</details>

**Comment by ansolantz** [comment] 2021-03-01 11:32
Hi @pedromassangocode,
Do you have any update about this?

**Comment by pedromassangocode** [comment] 2021-03-01 12:21
Hi @ansolantz 
Unfortunately no!

Cc @HansMuller

**Comment by danagbemava-nc** [comment] 2021-11-17 12:37
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-11-17 12:37 UTC
Labels: waiting for customer response, framework, f: material design, has reproducible steps, found in release: 1.22, found in release: 1.26
