### ISSUE TITLE
Rectangular icons are clipped

### ISSUE THREAD

**Issue by maxnemoy** [flutter/flutter#28131] opened 2019-02-19 07:56 UTC
I use custom icons

after flutter update, icons are cropped
```
Icon(icon)
```
![image](https://user-images.githubusercontent.com/39363044/52998523-75d56400-345e-11e9-9f11-e44e35299ad6.png)

but if wrap the widget Icon in a container with a fixed height and width, the icon is displayed correctly
```
 Container(width: 30, height: 30 ,child: Icon(icon)),
```

![image](https://user-images.githubusercontent.com/39363044/52998493-5fc7a380-345e-11e9-9591-b3f98103b8e6.png)

### flutter doctor -v

```
[√] Flutter (Channel master, v1.2.2-pre.21, on Microsoft Windows [Version 10.0.17763.253], locale ru-RU)
    • Flutter version 1.2.2-pre.21 at C:\flutter
    • Framework revision 035e0765cc (3 days ago), 2019-02-16 01:48:28 -0500
    • Engine revision f37b09a11b
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\maxnemoy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[√] Connected device (1 available)
    • SM G532F • 42006871065015d9 • android-arm • Android 6.0.1 (API 23)

• No issues found!

```

**Comment by zoechi** [comment] 2019-02-19 08:10
Tentatively adding `today`

**Comment by goderbauer** [comment] 2019-02-20 00:51
Removing todo since this only affects non-square icons, which are not really supported by the `Icon` class. 

I'll update the documentation to be explicit about this. Additionally, we'll also turn off clipping for icons since that's never necessary. That will restore the old behavior you were seeing with your non-square icons.

**Comment by maxnemoy** [comment] 2019-02-20 03:00
Yes, only icons with different heights and widths are cropped.
Excuse me, my English is very bad...

**Comment by goderbauer** [comment] 2019-02-20 17:43
Let's leave this open until https://github.com/flutter/flutter/pull/28182 is committed to restore the previous behavior.

**Comment by goderbauer** [comment] 2019-02-20 23:41
@maxnemoy Can you upgrade to the latest master and check if the problem is resolved for you?

**Closed** 2019-02-20 23:40 UTC
Labels: engine, framework, severe: regression

**Comment by maxnemoy** [comment] 2019-02-22 06:09
@goderbauer 
> @maxnemoy Can you upgrade to the latest master and check if the problem is resolved for you?

after updating the master branch
**The application crashes.**

![image](https://user-images.githubusercontent.com/39363044/53222630-65fd9000-36a9-11e9-838f-88c01816a275.png)
(text: application app_name stopped)

log

flutter run
```
Launching lib\main.dart on SM G532F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device SM G532F...
```

after press **ok button** on screen

```
I/Process (24279): Sending signal. PID: 24279 SIG: 9
Lost connection to device.
```

**[flutter run -v](https://gist.github.com/maxnemoy/f82d5d4759a06f547a29857817b90e2a)**


**flutter doctor -v**
```
[√] Flutter (Channel master, v1.2.2-pre.54, on Microsoft Windows [Version 10.0.17763.253],
    locale ru-RU)
    • Flutter version 1.2.2-pre.54 at C:\flutter
    • Framework revision d39a72516a (37 minutes ago), 2019-02-21 21:21:43 -0800
    • Engine revision f1f19bba8f
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\maxnemoy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2
    • Flutter plugin version 33.0.6
    • Dart plugin version 183.5901

[√] Connected device (1 available)
    • SM G532F • 42006871065015d9 • android-arm • Android 6.0.1 (API 23)

• No issues found!

```

PS in a stable branch everything works correctly, icons are non clipped
PPS for a new clean project, the behavior does not change, everything works in the stable branch, the same problems exist in the master branch

I'm sorry. I don't know English well

**Comment by maxnemoy** [comment] 2019-02-22 08:29
I updated the flutter again
up to version 1.2.3-pre.5
the application crashes after starting

```
[√] Flutter (Channel master, v1.2.3-pre.5, on Microsoft Windows [Version 10.0.17763.253], locale ru-RU)
    • Flutter version 1.2.3-pre.5 at C:\flutter
    • Framework revision b7711d0f9b (69 minutes ago), 2019-02-21 23:18:22 -0800
    • Engine revision cb0f7ece1f
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\maxnemoy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2
    • Flutter plugin version 33.0.6
    • Dart plugin version 183.5901

[√] Connected device (1 available)
    • SM G532F • 42006871065015d9 • android-arm • Android 6.0.1 (API 23)

• No issues found!

```

**Comment by maxnemoy** [comment] 2019-02-22 15:01
I'm sorry
The problem was in the device. On the emulator, everything works. Icons are displayed correctly.
