### ISSUE TITLE
Failed to load test harness error when running tests with flutter test

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#35893] opened 2019-07-10 18:03 UTC
## Steps to Reproduce

1. When running tests on a dart package, if I run the tests using the IDE, it runs `flutter test` ... and I get the below error. This is not a flutter plugin, as in, there is only dart code and no dependencies on flutter code.

## Logs

```
Testing started at 10:45 ...
/Users/thinkdigital/development/flutter/bin/flutter --no-color test --machine --plain-name "test prefix" test/html_parsing_client_test.dart

Compiler message:


Failed to load test harness. Are you missing a dependency on flutter_test?

Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aflutter_test%2Fflutter_test.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:601:37)
<asynchronous suspension>
#2      FrontendCompiler._outputDependenciesDelta (package:vm/frontend_server.dart:401:39)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:vm/frontend_server.dart:375:13)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:31:22)
<asynchronous suspension>
#5      listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:736:26)
<asynchronous suspension>
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#10     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#11     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#12     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#13     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#14     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#15     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#20     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#21     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#22     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#23     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#24     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#25     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#30     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#31     _StreamController._add (dart:async/stream_controller.dart:640:7)
#32     _StreamController.add (dart:async/stream_controller.dart:586:5)
#33     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#34     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#36     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#37     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#38     _StreamController._add (dart:async/stream_controller.dart:640:7)
#39     _StreamController.add (dart:async/stream_controller.dart:586:5)
#40     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#41     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
dart:async/stream_controller.dart 595:43                     _StreamController.addError
dart:async/stream_controller.dart 862:13                     _StreamSinkWrapper.addError
package:stream_channel/src/guarantee_channel.dart 144:14     _GuaranteeSink._addError
package:stream_channel/src/guarantee_channel.dart 135:5      _GuaranteeSink.addError
package:flutter_tools/src/test/flutter_platform.dart 448:27  FlutterPlatform._startTest
===== asynchronous gap ===========================
dart:async/zone.dart 1053:19                                 _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 77:23                      _asyncThenWrapperHelper
package:flutter_tools/src/test/flutter_platform.dart         FlutterPlatform._startTest
package:flutter_tools/src/test/flutter_platform.dart 362:36  FlutterPlatform.loadChannel
package:flutter_tools/src/test/flutter_platform.dart 315:46  FlutterPlatform.load
===== asynchronous gap ===========================
dart:async/zone.dart 1053:19                                 _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 77:23                      _asyncThenWrapperHelper
package:test_core/src/runner/loader.dart                     Loader.loadFile.<fn>
package:test_core/src/runner/load_suite.dart 98:31           new LoadSuite.<fn>.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1045:19                                 _CustomZone.registerCallback
dart:async/zone.dart 962:22                                  _CustomZone.bindCallbackGuarded
dart:async/timer.dart 52:45                                  new Timer
dart:async/timer.dart 87:9                                   Timer.run
dart:async/future.dart 174:11                                new Future
package:test_api/src/backend/invoker.dart 399:21             Invoker._onRun.<fn>.<fn>.<fn>

Failed to load "/Users/thinkdigital/IdeaProjects/pub_client/test/html_parsing_client_test.dart":
Compilation failed
Test: /Users/thinkdigital/IdeaProjects/pub_client/test/html_parsing_client_test.dart
Shell: /Users/thinkdigital/development/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester


```

I think the issue lies in the fact that I have a Flutter project open in Intellij and then I added a local package as a source so I can edit it as well and so it tries to run the tests as flutter tests. When I open the project directly, it runs `pub run test` and there are no issues.

**Comment by jonahwilliams** [comment] 2019-07-10 18:05
You need to include steps to reproduce the issue, such as an example of the test file where this occurs.

**Comment by ThinkDigitalSoftware** [comment] 2019-07-10 18:13
@jonahwilliams, the problem is that it's an incorrect command being run, not an issue with the file. It boils down to the IDE incorrectly assuming that it's a flutter test file instead of a dart test file. For example, I created a new dart package using stagehand and then ran `flutter test random_name_test.dart` and it fails with the same error. Running `pub run test random_name_test.dart` runs fine. We could say, "well run the right command", but it's something decided on by the IDE.
Is there any more clarification I can provide? I'm happy to help

**Comment by Mike278** [comment] 2019-09-14 01:05
@ThinkDigitalSoftware did you find a workaround for this? I'm in the same situation with the same error. Makes it frustrating to develop and test a dart package and a flutter app at the same time in one IDE. Perhaps this could be directed to an IDE-focused flutter issue tracker?

**Comment by ThinkDigitalSoftware** [comment] 2019-09-14 01:16
@mike278 I don't believe I did.

**Comment by janmoppel** [comment] 2019-09-30 07:56
Hello @ThinkDigitalSoftware !

Can you please also attach the `flutter doctor -v` output?

Thank you.

**Comment by iapicca** [comment] 2019-11-11 13:48
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by frank06** [comment] 2020-02-11 22:33
Why was this closed? I'm running into the same error. I want to be able to run pure Dart tests from the IDE

**Comment by iapicca** [comment] 2020-02-12 10:43
Hi @frank06 
can you please provide your `flutter doctor -v`
and the logs of your test
Thank you

**Comment by frank06** [comment] 2020-02-13 00:00
@iapicca sure!

```
➜ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /usr/local/Caskroom/flutter/1.2.1/flutter
    • Framework revision 27321ebbad (9 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

Running the test via `flutter pub run test test/adapter_test.dart` works fine.

When I use VS Code "Run" or "Debug" (because I'd like to debug tests) then I get a failure with the following message:

```
loading /Users/admin/projects/zzz_lib/test/adapter_test.dart:

ERROR: Failed to load "/Users/admin/projects/zzz_lib/test/adapter_test.dart":
Compilation failed
Test: /Users/admin/projects/zzz_lib/test/adapter_test.dart
Shell: /usr/local/Caskroom/flutter/1.2.1/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester


dart:async/stream_controller.dart 597:43                      _StreamController.addError
dart:async/stream_controller.dart 864:13                      _StreamSinkWrapper.addError
package:stream_channel/src/guarantee_channel.dart 144:14      _GuaranteeSink._addError
package:stream_channel/src/guarantee_channel.dart 135:5       _GuaranteeSink.addError
package:flutter_tools/src/test/flutter_platform.dart 463:27   FlutterPlatform._startTest
===== asynchronous gap ===========================
dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 73:23                       _asyncThenWrapperHelper
package:flutter_tools/src/test/flutter_platform.dart          FlutterPlatform._startTest
package:flutter_tools/src/test/flutter_platform.dart 368:36   FlutterPlatform.loadChannel
package:flutter_tools/src/test/flutter_platform.dart 321:46   FlutterPlatform.load
package:test_core/src/runner/loader.dart 224:36               Loader.loadFile.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 73:23                       _asyncThenWrapperHelper
package:test_core/src/runner/loader.dart                      Loader.loadFile.<fn>
package:test_core/src/runner/load_suite.dart 98:31            new LoadSuite.<fn>.<fn>
package:test_api/src/utils.dart 241:5                         invoke
package:test_core/src/runner/load_suite.dart 97:7             new LoadSuite.<fn>
package:test_api/src/backend/invoker.dart 392:25              Invoker._onRun.<fn>.<fn>.<fn>.<fn>
dart:async/future.dart 176:37                                 new Future.<fn>
package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1122:38                                  _rootRun
dart:async/zone.dart 1023:19                                  _CustomZone.run
dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1126:13                                  _rootRun
dart:async/zone.dart 1023:19                                  _CustomZone.run
dart:async/zone.dart 949:23                                   _CustomZone.bindCallback.<fn>
dart:async-patch/timer_patch.dart 23:15                       Timer._createTimer.<fn>
dart:isolate-patch/timer_impl.dart 384:19                     _Timer._runTimers
dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
dart:async/timer.dart 54:45                                   new Timer
dart:async/timer.dart 91:9                                    Timer.run
dart:async/future.dart 174:11                                 new Future
package:test_api/src/backend/invoker.dart 391:21              Invoker._onRun.<fn>.<fn>.<fn>
dart:async/zone.dart 1126:13                                  _rootRun
dart:async/zone.dart 1023:19                                  _CustomZone.run
dart:async/zone.dart 1518:10                                  _runZoned
dart:async/zone.dart 1465:12                                  runZoned
package:test_api/src/backend/invoker.dart 378:9               Invoker._onRun.<fn>.<fn>
dart:async/zone.dart 1126:13                                  _rootRun
dart:async/zone.dart 1023:19                                  _CustomZone.run
dart:async/zone.dart 1518:10                                  _runZoned
dart:async/zone.dart 1465:12                                  runZoned
package:test_api/src/backend/invoker.dart 144:7               Invoker.guard
package:test_api/src/backend/invoker.dart 428:15              Invoker._guardIfGuarded
package:test_api/src/backend/invoker.dart 377:7               Invoker._onRun.<fn>
package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
dart:async/zone.dart 1126:13                                  _rootRun
dart:async/zone.dart 1023:19                                  _CustomZone.run
dart:async/zone.dart 1518:10                                  _runZoned
dart:async/zone.dart 1465:12                                  runZoned
package:stack_trace/src/chain.dart 99:12                      Chain.capture
package:test_api/src/backend/invoker.dart 376:11              Invoker._onRun
package:test_api/src/backend/live_test_controller.dart 185:5  LiveTestController._run
package:test_api/src/backend/live_test_controller.dart 40:37  _LiveTest.run
dart:async/future.dart 202:37                                 new Future.microtask.<fn>
dart:async/zone.dart 1122:38                                  _rootRun
dart:async/zone.dart 1023:19                                  _CustomZone.run
dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
dart:async/zone.dart 1126:13                                  _rootRun
dart:async/zone.dart 1023:19                                  _CustomZone.run
dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 118:13                  _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 175:5                   _RawReceivePortImpl._handleMessage
```

**Comment by iapicca** [comment] 2020-02-13 08:33
thank you @frank06

**Comment by frank06** [comment] 2020-02-13 18:49
@iapicca Update: I had forgotten `flutter_test` as a dependency on the library, it works now!

I have another issue which probably doesn't belong here: the library is pure Dart, and the `example` is a Flutter app.  If I remove the Flutter dependency from the library, the example app is unable to find the Flutter SDK. That is why (for now at least) I have to depend on Flutter in the library, too.

**Comment by iapicca** [comment] 2020-02-14 12:07
Hi @frank06 
first of all I'm glad that you fixed the issue
and thank you for  letting me know

I suggest you to open a specific issue for the case you are describing,
I (personally) see it more like a proposal,

closing this issue for now,
if you disagree please comment below and I'll reopen the issue
Thanks again

**Closed by iapicca** 2020-02-14 12:07 UTC
Labels: a: tests, customer: crowd, framework, severe: crash
