### ISSUE TITLE
Support for borderless windows

### ISSUE THREAD

**Issue by mengrayan** [flutter/flutter#71042] opened 2020-11-22 14:46 UTC
Would it be possible to add support for borderless window mode on desktop? Thanks!

**Comment by darshankawar** [comment] 2020-11-23 11:32
Leaving [this](https://stackoverflow.com/a/63399864) here for reference.

**Comment by stuartmorgan** [comment] 2020-11-25 21:38
Duplicate of https://github.com/flutter/flutter/issues/31373

**Closed by stuartmorgan** 2020-11-25 21:38 UTC
Labels: a: desktop, passed first triage, proposal

**Comment by Rayan749** [comment] 2020-11-29 03:10
Thanks! #31373 is helpful.
