### ISSUE TITLE
I have a problem installing Flutter (the doctor check crashed)     X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know       about this issue at https://github.com/flutter/flutter/issues.     X FileSystemException: Cannot resolve symbolic links, path = 'D:\¦ں­ êêëيم ںé§¦يé\ ©ê¤ى\flutter\bin\flutter' (OS       Error: The system cannot find the path specified.

### ISSUE THREAD

**Issue by pokfa** [flutter/flutter#133145] opened 2023-08-23 13:11 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Cannot resolve symbolic links, path = 'D:\¦ں­ êêëيم ںé§¦يé\ ©ê¤ى\flutter\bin\flutter' (OS
      Error: The system cannot find the path specified.

### Actual results

Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FileSystemException: Cannot resolve symbolic links, path = 'D:\¦ں­ êêëيم ںé§¦يé\ ©ê¤ى\flutter\bin\flutter' (OS
      Error: The system cannot find the path specified.

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

<!-- Paste your output here -->

```

</details>

**Comment by danagbemava-nc** [comment] 2023-08-23 14:09
Closing this as a duplicate of https://github.com/flutter/flutter/issues/59770. 

As an aside, I think you should try moving flutter out of the directory it is in currently. i.e the directory with the Arabic(?) text

**Closed by danagbemava-nc** 2023-08-23 14:09 UTC
Labels: in triage
