### ISSUE TITLE
Error with ScrollController and multiple ListView

### ISSUE THREAD

**Issue by ferraridamiano** [flutter/flutter#85456] opened 2021-06-28 15:37 UTC
If you try to execute the code below on flutter web and you try to drag the scrollbar nothing happens and you get this error in the console:
`Another exception was thrown: The provided ScrollController is currently attached to more than one ScrollPosition.`

It is a very simple example with two listview in the same page.

<details>
  <summary>Code</summary>

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {

    return Scaffold(
      body: SafeArea(
          child: Row(
        children: [
          Expanded(
            child: ListView.builder(
              itemCount: 50,
              itemBuilder: (context, index) {
                return Text(index.toString(), style: const TextStyle(fontSize: 30.0),);
              },
            ),
          ),
          Expanded(
            child: ListView.builder(
              itemCount: 50,
              itemBuilder: (context, index) {
                return Text(index.toString(), style: const TextStyle(fontSize: 30.0),);
              },
            ),
          ),
        ],
      )),
    );
  }
}

```

</details>

<details>
  <summary>flutter --version</summary>

```

Flutter 2.3.0-17.0.pre.538 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1fd2f7c400 (13 hours ago) • 2021-06-27 22:51:02 -0400
Engine • revision 5d287a2061
Tools • Dart 2.14.0 (build 2.14.0-250.0.dev)

```

</details>

**Comment by iapicca** [comment] 2021-06-28 19:22
@ferraridamiano 
this solves the issue

```diff
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
          child: Row(
        children: [
          Expanded(
            child: ListView.builder(
+              controller: ScrollController(),
              itemCount: 50,
              itemBuilder: (context, index) {
                return Text(
                  index.toString(),
                  style: const TextStyle(fontSize: 30.0),
                );
              },
            ),
          ),
          Expanded(
            child: ListView.builder(
+              controller: ScrollController(),
              itemCount: 50,
              itemBuilder: (context, index) {
                return Text(
                  index.toString(),
                  style: const TextStyle(fontSize: 30.0),
                );
              },
            ),
          ),
        ],
      )),
    );
  }
}

```

**Comment by ferraridamiano** [comment] 2021-06-28 19:31
Thank you! But is this behaviour intentional? It seems that they are initialized with the same controller by default

**Comment by TahaTesser** [comment] 2021-06-29 11:28
@ferraridamiano 
To me, it looks like an expected behavior, since Scrollbar is always shown when running on desktop, ScrollController is [provided](https://api.flutter.dev/flutter/material/Scrollbar-class.html#material.Scrollbar.2) 

`The provided ScrollController is currently attached to more Yhan one ScrollPosition`

Since you have multiple listviews,  ScrollController is attaching being attached to multiple listviews hence the error. If you run the code sample without this on mobile, you can scroll without any error, since the scrollbar is not always visible by default on mobile

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-29 11:28 UTC
Labels: in triage
