### ISSUE TITLE
Design distortion on first time install - iOS

### ISSUE THREAD

**Issue by metizror** [flutter/flutter#31197] opened 2019-04-17 13:44 UTC
![Skype_Picture_2019_04_17T13_40_51_632Z](https://user-images.githubusercontent.com/8925045/56292291-88a9a380-6144-11e9-83e5-f439f4f3d2fc.jpeg)

When install app on my device and i use below code to jump to another screen and I see design destroyed but it start working when i open app again.  

**Navigator.pushNamed(context, "ROUTE_NAME");**

**Comment by goderbauer** [comment] 2019-04-17 21:59
You'll have to provide more information. What does your Flutter code look like? Do you have a minimal sample that shows the failure?

**Comment by metizror** [comment] 2019-04-18 05:00
I'm running on **iPhone 6** and **iPhone 8** devices in both I am having this problem. It works fine in all iPhone simulators. 

These is my code I have written to jump to login or register screen. 
`TweenButtons(
                 startText: S.of(context).log_in,
                 endIcon: DanceAppIcons.lock,
                 startOnTap: () {
                    Navigator.pushNamed(context, AppRoutes.loginPage);
                  },
                endText: S.of(context).register,
                startIcon: DanceAppIcons.compose,
                endOnTap: () {
                  Navigator.pushNamed(context, AppRoutes.registerWithPhoneNumberPage);
                },
              ),
`
And this code behind this two buttons i have a viewpager control where i am sliding three images. Below is the code for that one:

`class _WelcomeViewPager extends StatelessWidget {
  const _WelcomeViewPager();

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints) {
        return Container(
          height: constraints.maxHeight,
          child: TabBarView(
            children: <Widget>[
              Container(
                decoration: const BoxDecoration(
                  image: DecorationImage(
                    image: AssetImage('res/images/welcome_page_1.jpg'),
                    fit: BoxFit.cover,
                  ),
                ),
              ),
              Container(
                decoration: const BoxDecoration(
                  image: DecorationImage(
                    image: AssetImage('res/images/welcome_page_2.jpg'),
                    fit: BoxFit.cover,
                  ),
                ),
              ),
              Container(
                decoration: const BoxDecoration(
                  image: DecorationImage(
                    image: AssetImage('res/images/welcome_page_3.jpg'),
                    fit: BoxFit.cover,
                  ),
                ),
              ),
            ],
          ),
        );
      },
    );
  }
`

**Comment by daniilguit** [comment] 2019-04-18 18:00
Looks like a duplicate of a https://github.com/flutter/flutter/issues/30972
Try upgrading to dev channel and use v 1.4.19 (this fixed this issue for me)
```
flutter channel dev
flutter version 1.4.19
```

**Closed** 2019-10-12 14:55 UTC
