### ISSUE TITLE
Unable to build Counter App Flutter Counter app in ios

### ISSUE THREAD

**Issue by jindalAnuj** [flutter/flutter#76922] opened 2021-02-27 10:50 UTC
## Steps to Reproduce

1. I have a application which runs fine in ios emulator but i was not able to archive it in ios.
2. I continously get the error
 ```
↳
    building file list ... done
    App.framework/
    App.framework/App
    App.framework/Info.plist
    App.framework/flutter_assets/
    App.framework/flutter_assets/AssetManifest.json
    App.framework/flutter_assets/FontManifest.json
    App.framework/flutter_assets/NOTICES
    App.framework/flutter_assets/fonts/
    App.framework/flutter_assets/fonts/MaterialIcons-Regular.otf
    App.framework/flutter_assets/packages/
    App.framework/flutter_assets/packages/cupertino_icons/
    App.framework/flutter_assets/packages/cupertino_icons/assets/
    App.framework/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf

    sent 8735093 bytes  received 210 bytes  17470606.00 bytes/sec
    total size is 8733270  speedup is 1.00
    building file list ... done
    Flutter.framework/
    Flutter.framework/Flutter
    Flutter.framework/Info.plist
    Flutter.framework/icudtl.dat
    Flutter.framework/_CodeSignature/
    Flutter.framework/_CodeSignature/CodeResources

    sent 441345196 bytes  received 120 bytes  51922978.35 bytes/sec
    total size is 441290905  speedup is 1.00
    Warning: unable to build chain to self-signed root for signer "Apple Development: Name (TEAM_ID)"
    /Users/rahuljindal/AppDevelopment/Flutter_projects/sampleapp/build/ios/Release-iphoneos/Runner.app/Frameworks/App.framework/App:
    errSecInternalComponent
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning build
    note: Constructing build description
```
4. Then i created a app using command `flutter create --org com.skjcorp  sampleapp`
5. Without changing anything i run `flutter build ios` then i again got the same error.

3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel beta, 1.26.0-17.8.pre, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-IN)
    • Flutter version 1.26.0-17.8.pre at /Users/rahuljindal/Library/flutter
    • Framework revision 044f2cf560 (3 days ago), 2021-02-24 13:02:05 -0800
    • Engine revision 042c82b02c
    • Dart version 2.12.0 (build 2.12.0-259.16.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/rahuljindal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ! Xcode 11.3.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-03-01 07:47
Hi @jindalAnuj 
I tried to reproduce with new project `sampleapp`, app builds fine. 
Your looks like from Xcode, check out https://developer.apple.com/forums/thread/86161

```bash
tahatesser@Tahas-MacBook-Pro AndroidStudioProjects % cd sampleapp 
tahatesser@Tahas-MacBook-Pro sampleapp % flutterb build ios
Building com.skjcorp.sampleapp for device (ios-release)...
Signing iOS app for device deployment using developer identity: "Apple
Development: Taha Baig (45T44J23Y9)"
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        23.5s
Xcode build done.                                           72.8s
Built
/Users/tahatesser/AndroidStudioProjects/sampleapp/build/ios/iphoneos/Runner.app.
tahatesser@Tahas-MacBook-Pro sampleapp % 
```


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.26.0-17.8.pre, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-17.8.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 044f2cf560 (4 days ago), 2021-02-24 13:02:05 -0800
    • Engine revision 042c82b02c
    • Dart version 2.12.0 (build 2.12.0-259.16.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 14.4
    • iPhone 12 (mobile)   • 948EC106-78EE-4A69-8D31-83C00E6419DE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome
      88.0.4324.192

• No issues found!

```

</details>


Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-01 07:47 UTC
Labels: in triage
