### ISSUE TITLE
`platform_views_scroll_perf__timeline_summary`:`99th_percentile_frame_build_time_millis` 250% regression

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#144255] opened 2024-02-27 20:55 UTC
introduction https://github.com/flutter/flutter/pull/144208

[skia-perf](https://flutter-flutter-perf.skia.org/e/?keys=Xd2656b08b4961c84affb7d07f7eb4c29&selected=commit%3D39546%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_build_time_millis%252Ctest%253Dplatform_views_scroll_perf__timeline_summary%252C&xbaroffset=39546)

**Comment by gaaclarke** [comment] 2024-02-27 20:56
This is probably a result of https://github.com/flutter/engine/pull/50976

**Comment by jonahwilliams** [comment] 2024-03-04 18:53
We looked into this more and the cause was the multiview PR that landed and was reverted changed how the work was scheduled in a way that reduce the measured workload of the framework.

**Closed by jonahwilliams** 2024-03-04 18:53 UTC
Labels: c: regression, team-engine
