### ISSUE TITLE
Limit exception stack trace depth

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#6424] opened 2016-10-20 17:05 UTC
A sample exception thrown from Leafy app is below.

This is a feature request to filter out everything other than the package the app belongs to (modulo N context frames).

```
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
I/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
I/flutter : #2      Redacted.[] (package:LEAFY/redacted.dart:11)
I/flutter : #3      _RedactedState.build (package:LEAFY/redacted.dart:241)
I/flutter : #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2666)
I/flutter : #5      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2652)
I/flutter : #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:2768)
I/flutter : #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:2647)
I/flutter : #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #10     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #12     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2652)
I/flutter : #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2647)
I/flutter : #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #16     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #18     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2652)
I/flutter : #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2647)
I/flutter : #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #22     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3436)
I/flutter : #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #25     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3436)
I/flutter : #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #28     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #30     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2652)
I/flutter : #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:2768)
I/flutter : #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2647)
I/flutter : #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #35     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #37     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2652)
I/flutter : #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:2768)
I/flutter : #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2647)
I/flutter : #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #42     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3436)
I/flutter : #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #45     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3436)
I/flutter : #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #48     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #50     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2652)
I/flutter : #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2647)
I/flutter : #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #54     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:3436)
I/flutter : #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #57     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #59     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2652)
I/flutter : #61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:2768)
I/flutter : #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2647)
I/flutter : #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #64     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #66     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2652)
I/flutter : #68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:2768)
I/flutter : #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2647)
I/flutter : #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #71     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #73     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:2652)
I/flutter : #75     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:2768)
I/flutter : #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:2647)
I/flutter : #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2139)
I/flutter : #78     Element.updateChild (package:flutter/src/widgets/framework.dart:1970)
I/flutter : #79     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:3227)
I/flutter : #80     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3542)
I/flutter : #81     Element.updateChild (package:flutter/src/widgets/framework.dart:1963)
I/flutter : #82     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:487)
I/flutter : #83     Element.updateChild (package:flutter/src/widgets/framework.dart:1963)
I/flutter : #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #85     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #86     StatefulElement.update (package:flutter/src/widgets/framework.dart:2787)
I/flutter : #87     Element.updateChild (package:flutter/src/widgets/framework.dart:1963)
I/flutter : #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #89     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #90     ProxyElement.update (package:flutter/src/widgets/framework.dart:2905)
I/flutter : #91     Element.updateChild (package:flutter/src/widgets/framework.dart:1963)
I/flutter : #92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3443)
I/flutter : #93     Element.updateChild (package:flutter/src/widgets/framework.dart:1963)
I/flutter : #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #95     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #96     StatefulElement.update (package:flutter/src/widgets/framework.dart:2787)
I/flutter : #97     Element.updateChild (package:flutter/src/widgets/framework.dart:1963)
I/flutter : #98     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3443)
I/flutter : #99     Element.updateChild (package:flutter/src/widgets/framework.dart:1963)
I/flutter : #100    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:3443)
I/flutter : #101    Element.updateChild (package:flutter/src/widgets/framework.dart:1963)
I/flutter : #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:2678)
I/flutter : #103    BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:2567)
I/flutter : #104    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:1668)
I/flutter : #105    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:297)
I/flutter : #106    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:162)
I/flutter : #107    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:648)
I/flutter : #108    BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:583)
I/flutter : #109    _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:59)
```

**Comment by Hixie** [comment] 2016-10-20 17:39
That stack is super helpful in figuring out what was going on. For example, from this example I can tell that this was the build phase (frames 105 and 104), that the app had an Overlay (frame 82), and that this was shortly after a relatively serious transition (frame 75). If we could get hold of the actual objects in the stack we could turn the stack into something more useful (listing the actual widgets being built at each frame, for example), but I don't know how to do that today.

Closing, dupe of https://github.com/flutter/flutter/issues/4174.
See also https://github.com/flutter/flutter/issues/4021.

**Closed by Hixie** 2016-10-20 17:39 UTC
Labels: affects: dev experience, affects: framework, customer: leafy
