### ISSUE TITLE
I need GoogleService_Info.plist file from existing Firebase project

### ISSUE THREAD

**Issue by nathan-kane** [flutter/flutter#73603] opened 2021-01-08 21:56 UTC
I have an android flutter app that I created using Android Studio on a Windows machine. However, now I need to move everything to a Mac iOS machine. This has been a true test of my patients.

I need to get the GoogleServices-Info.plist file for a Firebase project that already exists. I have followed the directions on Firebase but I don't see any download button.

_**Firebase Instructions:**
1. Go to your. Project settings in the Firebase console.
2. In the Your apps card, select the bundle ID of the app for which you need a config file._

This Firebase project already existed so I don't know how to get the file.

**Comment by nt4f04uNd** [comment] 2021-01-09 05:25
this is not related to flutter
you can do this from firebase projects settings
url https://console.firebase.google.com/u/0/project/YOUR_PROJECT/settings/general/

**Comment by iapicca** [comment] 2021-01-09 10:32
@nathan-kane 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicate [github](https://github.com/FirebaseExtended/flutterfire/issues)
I recommend you to close this issue

**Comment by TahaTesser** [comment] 2021-01-11 07:52
Hi @nathan-kane 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-11 07:52 UTC
