### ISSUE TITLE
Cropping YUV images I'm a quick way.

### ISSUE THREAD

**Issue by eduardkieser** [flutter/flutter#34743] opened 2019-06-19 21:35 UTC
Hello, I would like to crop the images that are returned from the camera image stream without first converting to rgb image so that I can send the cropped frame to Tflite.

Something like this would be great
```
cameraController.startImageStream((CameraImage availableYUV)async{
      if (!_isDoneReadingImage) return;
      CameraImage croppedYUV = cropCameraImage(availableYUV, x0, x1, y0, y1)
      // send cropped image to Tflite
}
```
Does anyone know how to do this?

**Comment by palinda** [comment] 2019-09-24 11:37
+1

**Comment by mhilalsh** [comment] 2022-02-23 11:42
Hello, did anyone find a solution yet? I still don't understand how to crop a cameraImage, the problem isn't with the format of the camera Image, I tried to change the format to JPEG but then what? how can I crop it?

**Comment by stuartmorgan** [comment] 2023-03-26 19:17
Closing, as post-processing images is out of scope for the `camera` plugin. This is something that would be best built as a separate package by the community.

**Closed by stuartmorgan** 2023-03-26 19:17 UTC
Labels: new feature, plugin, d: stackoverflow, customer: crowd, p: camera, P5
