### ISSUE TITLE
X Unable to locate Android SDK.

### ISSUE THREAD

**Issue by sjx19900424** [flutter/flutter#13078] opened 2017-11-18 02:07 UTC
X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.

I have installed Android SDK ,and set $ANDROID_HOME. But 'flutter doctor' show the error again.

**Comment by bledfort** [comment] 2018-02-24 01:49
Same issue, why there is no responses? weird

**Comment by sam43** [comment] 2018-02-27 11:48
same issue... stucked. Help!

**Comment by PillowDeveloper** [comment] 2018-02-27 18:20
try to Install Android studio again, with default installation folder... don't use custom path

**Comment by sam43** [comment] 2018-02-28 05:50
Wow, this worked perfectly, thank you. but I can't able start any device to run the sample project. Can you help me with this last thing please? here is the attachment.
![issue_flutter](https://user-images.githubusercontent.com/4275505/36771966-8470cdb4-1c7d-11e8-8792-be8364daedb4.PNG)
 @PillowDeveloper

**Comment by sam43** [comment] 2018-02-28 07:00
Update... working fine. But have to start the project from PowerShell and run it. Note: Close your AS 3.0 if it is running. steps: create app -> cd <your_app_dir> -> flutter run. Boom! :)

**Comment by sumiaggarwal** [comment] 2018-05-27 17:17
thanks worked like a charm :)

**Comment by zoechi** [comment] 2018-08-03 15:59
@sjx19900424 is this still an issue or can this be closed?

**Comment by mahbobyosf** [comment] 2018-08-28 07:28
This worked perfectly, thank you.

**Comment by arsalan0312** [comment] 2018-09-05 13:56
I have the same issue after following step.
/ Open system properties
*/ Environment variables
*/ create new system variable
*/ name : ANDROID_HOME
*/ value : copy your SDK path
*/ close your current cmd, and restart it
*/ run flutter doctor

**Comment by zoechi** [comment] 2018-09-05 14:19
check the SDK config in `android/local.properties`
You can use `flutter config` to update it.
Can you still reproduce when the setting is updated to the new path?

**Comment by zoechi** [comment] 2018-10-08 09:19
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2018-10-08 09:19 UTC
Labels: waiting for customer response

**Comment by JosephDunivan** [comment] 2018-12-05 07:03
> check the SDK config in `android/local.properties`
> You can use `flutter config` to update it.
> Can you still reproduce when the setting is updated to the new path?

@zoechi When you say "You can use flutter config to update it." can you elaborate? The issue is flutter expects the path to point to /usr/local/share/android-sdk, however android studio installs everything in users/<username>/library/android/sdk and has for quite some time. The issue seems to be that redirecting this expected path to the actual path in .bash_profile does not solve the issue.

**Comment by JosephDunivan** [comment] 2018-12-05 07:14
Using the command flutter config --android-sdk $HOME/Library/Android/sdk on Mac OS seems to have immediately solved my issues if anyone is looking for a more specific directive.

**Comment by QuietLakeStone** [comment] 2018-12-15 17:01
I finally solved the problem!!!!.>>Ubuntu 18<<, Need to make paths the same，
like:/home/name/flutter   and /home/name/Android-SDK
Check ndk-bundle/toolchains Is it complete?,You can download> android-ndk-r16b-linux-x86_64.zip 
Then modify the environment and AS configure,restart AS,no devices ->Android Device
I hope I can help you all.

**Comment by denzsbs** [comment] 2018-12-20 08:12
> Using the command `flutter config --android-sdk $HOME/Library/Android/sdk` on Mac OS seems to have immediately solved my issues if anyone is looking for a more specific directive.

thanks bro !!!

**Comment by DevLuuk** [comment] 2019-01-08 18:44
I solved it by adding this line: ```flutter config --android-sdk /path/to/android/sdk``` in the terminal in Android Studio.

**Comment by Qinxianshen** [comment] 2019-01-30 10:55
> I had the same problem,
> I did the following steps :
> 
> */ Open system properties
> */ Environment variables
> */ create new system variable
> */ name : ANDROID_HOME
> */ value : copy your SDK path
> */ close your current cmd, and restart it
> */ run flutter doctor
> 
> this should work on windows

awesome ! It‘s work for me!Thank you

**Comment by ValmirJuniorr** [comment] 2019-03-20 01:19
> I solved it on Ubuntu by adding this line: `flutter config --android-sdk /path/to/android/sdk` in the terminal in Android Studio.

it works perfect to me, thanks buddy.

**Comment by codingcity4747** [comment] 2019-03-20 06:20
> I had the same problem,
> I did the following steps :
> 
> */ Open system properties
> */ Environment variables
> */ create new system variable
> */ name : ANDROID_HOME
> */ value : copy your SDK path
> */ close your current cmd, and restart it
> */ run flutter doctor
> 
> this should work on windows

this worked for me, but I mention that  after adding ANDROID_HOME path to your env variables you should restart your computer before checking flutter doctor report 
good luck

**Comment by DaywisonSilva** [comment] 2019-09-05 18:55
[X] Android toolchain - develop for Android devices
    X ANDROID_HOME = C:\Users\Daywi\AppData\Local\Android\Sdk
      but Android SDK not found at this location.

**Comment by milanpatel18** [comment] 2019-10-12 17:49
Already solved at https://github.com/flutter/flutter/issues/15114#issuecomment-541346856

**Comment by avavirus3** [comment] 2020-03-18 17:06
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
[!] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    X No valid Android SDK platforms found in D:\oprathing
      system\Compressed\flutter_windows_v1.12.13+hotfix.8-stable\android-sdk\platforms. Directory was empty.
[!] Android Studio (not installed)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.41.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 4 categorie

**Comment by avavirus3** [comment] 2020-03-18 17:07
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
[!] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    X No valid Android SDK platforms found in D:\oprathing
      system\Compressed\flutter_windows_v1.12.13+hotfix.8-stable\android-sdk\platforms. Directory was empty.
[!] Android Studio (not installed)
[!] IntelliJ IDEA Community Edition (version 2018.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.41.1)

**Comment by sameermuslim** [comment] 2020-03-26 14:47
> I can't able start any device to run the sample project.

me too :(
