### ISSUE TITLE
Uri.base.queryparameters is empty for Flutter Web but Uri.base.toString() is fine

### ISSUE THREAD

**Issue by hermantai** [flutter/flutter#116484] opened 2022-12-04 16:12 UTC
In the following, you can try that if you enter a URL like: http://localhost:1234/#/?flavor=chocolate, the commented out line would be an empty string because the whole Uri.base.queryParameters is empty. The workaround is to parse the Uri.base.toString() again withou Uri.dataFromString:

```
void main() {
  // Parse from Uri.base does not work, we have to parse from Uri.base.toString() again.
  // String flavor = Uri.base.queryParameters['flavor'] ?? "";
  String flavor = Uri.dataFromString(Uri.base.toString()).queryParameters.toString();
  runApp(MyApp(flavor: flavor));
}
```

Output of "flutter doctor -v":

```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6.1 21G217 darwin-x64, locale en)
    • Flutter version 3.3.9 on channel stable at /Users/htaihm/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (12 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/htaihm/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio with Blaze Beta.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio with Blaze Beta.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

**Comment by LuisMiguelSS** [comment] 2022-12-04 16:55
This is shown when the uri has a [fragment](https://en.wikipedia.org/wiki/URI_fragment), so if you test the same uri but without the "#", it'll display properly:
```dart
final uri = Uri.parse("https://www.website.com/#/path1/path2?myAttribute=1");
  
  print(uri.queryParameters);
  print(uri.fragment);
  print(uri.pathSegments);
```
Will output:
```
{}
/path1/path2?myAttribute=1
[]
```

But if you do the same without the "#" in the uri:
```dart
final uri = Uri.parse("https://www.website.com/path1/path2?myAttribute=1");

print(uri.queryParameters);
print(uri.fragment);
print(uri.pathSegments);
```

You'll get:
```
{myAttribute: 1}

[path1, path2]
```

Normally the fragment defines an anchor in the same website, reason why everything that goes after it is not parsed.
A temporal solution to this would be removing the "#" from the Uri and then reparse it:
```dart
Uri uri = Uri.parse("https://www.website.com/#/path1/path2?myAttribute=1");

uri = Uri.parse(
  uri.toString().replaceFirst("#/","")
);

print(uri.queryParameters);
print(uri.fragment);
print(uri.pathSegments);
```
Result:
```
{myAttribute: 1}

[path1, path2]
```

Alternatively you could also parse the `uri.fragment` into a new Uri and access the same properties:
```dart
uri = Uri.parse(uri.fragment);

print(uri.queryParameters);
print(uri.fragment);
print(uri.pathSegments);
```
Output:
```
{myAttribute: 1}

[path1, path2]
```

**Comment by hermantai** [comment] 2022-12-04 18:49
I see, so Uri.dataFromString works because it parses the uri as a "data", not a URL, which doesn't respect the semantic of "fragment"?

Code:
```
void main() {
  String url = "http://localhost:1234/#/?flavor=chocolate";
  print(Uri.dataFromString(url).toString());
  print(Uri.dataFromString(url).queryParameters.toString());

  print(Uri.parse(url).toString());
  print(Uri.parse(url).queryParameters.toString());
}
```

Output:
```
data:,http://localhost:1234/%23/?flavor=chocolate
{flavor: chocolate}
http://localhost:1234/#/?flavor=chocolate
{}
```

Is this issue then work-as-intended or something should be fixed?

**Comment by exaby73** [comment] 2022-12-05 10:37
Hello @hermantai. This is working as intended for reasons mentioned by @LuisMiguelSS here (https://github.com/flutter/flutter/issues/116484#issuecomment-1336466214). As a workaround, you can try parsing the fragment then access the query params like so:

```dart
void main() {
  final uri = Uri.parse(Uri.parse('http://localhost:1234/#/?flavor=chocolate').fragment);
  print(uri.queryParameters);
}
```

But since this is not an issue with Flutter, I am closing this issue. Thank you

**Closed by exaby73** 2022-12-05 10:37 UTC
Labels: in triage
