### ISSUE TITLE
Missing material icons `more_up` and `more_down`

### ISSUE THREAD

**Issue by GniLudio** [flutter/flutter#152338] opened 2024-07-25 20:22 UTC
### Use case

Maybe I am misunderstanding something, but I thought the `icons.dart` includes all material icons, but I found some that are missing.

### Proposal

The [more_down](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:more_down:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%235f6368&icon.query=more_down) and [more_up](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:more_up:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%235f6368&icon.query=more_up) icons are absent from the [material icons](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/icons.dart).

**Comment by danagbemava-nc** [comment] 2024-07-26 08:02
What you are looking at is a material symbol which is slightly different from material icons. Support for this is being tracked in https://github.com/flutter/flutter/issues/102560. In the interim, you can use https://pub.dev/packages/material_symbols_icons

Closing this as a duplicate of the issue linked above.

**Closed by danagbemava-nc** 2024-07-26 08:02 UTC
Labels: in triage
