### ISSUE TITLE
Remove the firebase test lab tests

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#63419] opened 2020-08-10 19:35 UTC
I think the results of the experiment with the firebase test lab is that they are too flaky.

I propose that we declare the experiment a failure and remove all the code supporting firebase test lab tests.

**Comment by Hixie** [comment] 2020-08-10 19:38
cc @goderbauer @dnfield @bparrishMines @jonahwilliams @jmagman @xster @HansMuller

**Comment by dnfield** [comment] 2020-08-10 20:05
We currently get to test on lower API versions than the devicelab supports, as well as devices we don't have access to in the devicelab via Firebase. From what I understand, @digiter has mentioned that we have had issues with availability/reliability of devicelab devices (/cc @godofredoc as well).

Do we have data on how flaky Firebase has been for us, and what the causes are? 

If we have data showing how often Firebase tests are failing in ways that are beyond our control to fix (e.g. we can't just add a retry or a network failure), that would certainly help make this decision clearer.

/cc @csells as well FYI

**Comment by godofredoc** [comment] 2020-08-10 20:21
@blasten is adding support for android emulators, is it possible to run some of those tests in emulators?

Flakiness data will be available as soon as we move them to luci.

**Comment by dnfield** [comment] 2020-08-10 20:24
We'd lose the ability to do release/profile builds on emulators, right?

**Comment by jonahwilliams** [comment] 2020-08-10 20:30
you can do release/profile builds on android emulators, provided it is one of the ABIs we support

**Comment by blasten** [comment] 2020-08-10 20:34
What is the reason of the flakiness? Has this been investigated?  ARM/ARM64 emulation is very slow. I don't think it's feasible to use either.  Maybe x64 release or profile.

**Comment by jonahwilliams** [comment] 2020-08-10 20:43
Are these actually less flaky than the devicelab?

**Comment by christopherfujino** [comment] 2020-08-10 20:46
> What is the reason of the flakiness? Has this been investigated? ARM/ARM64 emulation is very slow. I don't think it's feasible to use either. Maybe x64 release or profile.

Probably the main problem is that no one owns this integration, and no one has investigated it. I think for us to get value from these tests, we would need someone to drive the integration, and actually follow-up with the FTL team.

**Comment by Hixie** [comment] 2020-08-10 20:47
I've seen two failure modes, one was definitely infrastructure failure (https://github.com/flutter/flutter/issues/63103), the other was a timeout and I've no idea what the cause was and no real way that I know of to debug it.

More importantly, though, I've never heard of these tests catching a real failure. Have they? Certainly if there's value to them that outweighs the cost then we should keep them. But it's not clear to me what the value really is, and the cost seems high (it's a whole bunch of additional infrastructure to go wrong).

**Comment by christopherfujino** [comment] 2020-08-10 20:52
There are three things we can do about this:

1. Invest the resources in making these high value tests.
2. Delete them, and figure out a way to test within our existing infrastructure.
3. Status quo.

Number 1 would be ideal, but I think the second option is an improvement over the third.

**Comment by blasten** [comment] 2020-08-10 20:56
> More importantly, though, I've never heard of these tests catching a real failure. Have they? 

Yup. I've seen that it prevented bad engine rolls from being merged.  For instance, SIGSEGVs, R8/Reflection/Java method lookups issues.  Another thing to consider is that we don't have the infrastructure to install APKs from App Bundles the same way Firebase test lab does it.

**Comment by dnfield** [comment] 2020-08-10 21:08
These have definitely caught real failures in the past. That's why I added the ones I did. We're also exploring adding more to relieve some of the devicelab pressure (@caref is working on that).

Anything we can do to make them higher quality is good.  I've reached out to the Firebase team to see if they can help too.

**Comment by CareF** [comment] 2020-08-10 21:21
I'm removing related codes in https://github.com/flutter/flutter/pull/62064 but those has already been commented out in device lab manifest long ago. After that lands I'll take a look at other firebase test (if there's any).

**Comment by Hixie** [comment] 2020-08-11 17:48
Good to hear that they are at least catching some bugs. That swings the scales a bit.

**Comment by dnfield** [comment] 2020-08-27 16:11
Some updates:

Some firebase team members took a look for us, and apparently some of the devices we were using have higher than normal wait times. I've updated that for flutter/flutter and flutter/plugins, hopefully that improves things. They say they're working on a feature that would allow users to detect that.

According to them, the tests have a 1% infra failure rate, although that includes tests that we cancel (e.g. when a new commit is pushed and the cirrus or LUCI job goes away). According to them, in the last couple weeks the only such failures have been from our cancelling.

**Comment by goderbauer** [comment] 2020-09-09 21:58
Has this gotten better after Dan switched to other devices?

**Comment by godofredoc** [comment] 2020-09-28 04:22
These tests have been passing consistently:

prod: https://ci.chromium.org/p/flutter/g/firebaselab/console
try: https://ci.chromium.org/p/flutter/g/firebaselab-try/builders

**Closed by godofredoc** 2020-09-28 04:22 UTC
Labels: P4, a: tests, framework, passed first triage, team, team: flakes
