### ISSUE TITLE
[image_picker] Crash when Xiaomi Android 10 return n

### ISSUE THREAD

**Issue by tcf150** [flutter/flutter#131234] opened 2023-07-25 02:15 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

No idea how to reproduce yet, but this is the root cause according to Crashlytics log~
Using image_picker: 0.8.5+2 now, but i notice this issue are not handle in latest version too.

1. Xiaomi Android 10 will return null for intent.data although the resultCode is **-1** - **ResultInfo{who=null, request=2346, result=-1, data=Intent {  }}**
2. so **ImagePickerDelegate.handleChooseMultiImageResult** will still continue proceed due to it check **intent != null** only
3. **fileUtils.getPathFromUri** will throw error when **context.getContentResolver().openInputStream(uri);** due to the uri is **null** and this method only handle **IOException**

### Expected results

Prefer no crash happen and return failed or empty uri path.

### Actual results

It causing crash in Xiaomi Android 10

### Logs

<details><summary>Logs</summary>

```console
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2346, result=-1, data=Intent {  }} to activity {com.xxxxx/com.xxxxx}: java.lang.NullPointerException: uri
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4977)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5018)
Caused by java.lang.NullPointerException: uri
       at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:133)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:1183)
       at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:45)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseMultiImageResult(ImagePickerDelegate.java:504)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:467)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:772)
       at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:685)
```

</details>

**Comment by danagbemava-nc** [comment] 2023-07-25 06:57
Closing this as a duplicate of https://github.com/flutter/flutter/issues/104168. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-07-25 06:57 UTC
Labels: in triage
