### ISSUE TITLE
Tab names don't fit on ios in material gallery

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#1806] opened 2016-02-12 18:19 UTC
Steps to reproduce:

1) Launch material gallery in ios
2) Navigate to Components > Buttons > Floating
3) Tap the floating action button

Expected behavior

The names in the "FAB per tab" screen should fit without the text wrapping.

Actual behavior.
![tab-labels-wrapping](https://cloud.githubusercontent.com/assets/15253456/13016146/e8115bbc-d171-11e5-8f83-05840b9d8ad2.jpg)

@HansMuller

**Comment by eseidelGoogle** [comment] 2016-02-12 18:22
I suspect this will be resolved by https://github.com/flutter/flutter/issues/116 which jason is hard at work on.

**Comment by eseidelGoogle** [comment] 2016-02-12 18:23
I suspect there are several bugs here actually.

- [ ] Tabs have the wrong text-overflow behavior?
- [ ] Material Gallery doesn't use the same font on iOS and Android
- [ ] It's not currently possible to use the same font #116

**Comment by eseidelGoogle** [comment] 2016-02-12 18:24
Tabs will need to handle overflow behavior due to different sized screens anyway.  Seems we could use this bug to resolve that?

**Comment by Hixie** [comment] 2016-02-12 18:35
We should probably make tabs automatically enable the overflow behaviour if they can't fit.

**Comment by eseidelGoogle** [comment] 2016-02-25 14:08
@jason-simmons solved #116 so now we just need to bundle Roboto with the Gallery per MD:
https://www.google.com/design/spec/style/typography.html#typography-typeface

**Comment by HansMuller** [comment] 2016-02-25 15:53
As you can see from the super-short tab labels, I had to work pretty hard to get this to fit. There's no guarantee that portrait format on any phone will be as wide or wider than my Nexus 5. I should probably make the demo's tabs scrollable. 

AFAIK there's no "text-overflow" defined for tabs in the MD spec. My impression is that you're supposed to keep the labels short enough to fit or make the tab bar scrollable.

**Closed** 2016-03-21 18:04 UTC
Labels: affects: material design, device-specific, ⌺‬ platform-ios, ⚠ bug

**Comment by sethladd** [comment] 2016-03-21 20:38
Dupe of https://github.com/flutter/flutter/issues/2677 ?
