### ISSUE TITLE
A Hero widget cannot be the descendant of another Hero widget

### ISSUE THREAD

**Issue by codigo47** [flutter/flutter#29565] opened 2019-03-18 19:53 UTC
## Steps to Reproduce

1. Filling a ListView with Hero animations throw an error (was working before the last Flutter SDK upgrade)
* You can replace `user.searches` inside _getSearches() with something else for testing purposes

```dart
import 'package:flutter/material.dart';

import '../models/user.dart';
import '../models/search.dart';
import '../helpers/app_settings.dart';

class SearchesView extends StatefulWidget {
  @override
  _SearchesScreenState createState() => _SearchesScreenState();
}

class _SearchesScreenState extends State<SearchesView> {
  @override
  Widget build(BuildContext context) {
    return Center(      
      child: ListView(
        padding: const EdgeInsets.all(5.0),
        children: _getSearches(context)
      ),
    );
  } 

  List<Widget> _getSearches(BuildContext context) {
    var user = User.currentUser;

    List<Widget> tiles = List<Widget>();
    for (var s in user.searches) {

      String mandatoryTags = '';
      for (var m in s.mandatoryTags) {
        if (m.length > 0)
          mandatoryTags = "$mandatoryTags ${m[0]}";
      }
 
      tiles.add(
        Hero( // <---- PROBLEM HERE, IF I REMOVE THE HERO CLASS, APP WORKS FINE
          tag: "hero_card_search_${s.name}",
          child: Card(
            elevation: AppSettings.cardElevation, 
            color: AppSettings.cardBackgroundColor,
            child: ListTile(
              leading: Icon(Icons.search),              
              title: Text(s.name),
              subtitle: Text(mandatoryTags.trim()),
              onTap: () {
                Search.currentSearch = s;
                Navigator.of(context).pushNamed('/search');
              },
            ),
          ),
        )
      );
    }

    return tiles;
  }

}
```

![image](https://user-images.githubusercontent.com/1730379/54558724-363a6300-499d-11e9-8470-71d72b4b6b54.png)

## Logs
```
[   +3 ms] I/flutter (13547): searches: 5 - jobs: 60
[ +235 ms] I/flutter (13547): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
[   +4 ms] I/flutter (13547): The following assertion was thrown building Hero(tag:
hero_card_search_PHP remoto, dirty, state:
[   +1 ms] I/flutter (13547): _HeroState#87d03):
[   +3 ms] I/flutter (13547): A Hero widget cannot be the descendant of another Herowidget.
[   +2 ms] I/flutter (13547): 'package:flutter/src/widgets/heroes.dart': Failed
assertion: line 300 pos 7:
[        ] I/flutter (13547): 'context.ancestorWidgetOfExactType(Hero) == null'
[   +1 ms] I/flutter (13547): 
[        ] I/flutter (13547): Either the assertion indicates an error in the
framework itself, or we should provide substantially
[        ] I/flutter (13547): more information in this error message to help you
determine and fix the underlying cause.
[        ] I/flutter (13547): In either case, please report this assertion by filinga bug on GitHub:
[        ] I/flutter (13547):
https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (13547): 
[        ] I/flutter (13547): When the exception was thrown, this was the stack:
[   +6 ms] I/flutter (13547): #2      _HeroState.build
(package:flutter/src/widgets/heroes.dart:300:7)
[   +1 ms] I/flutter (13547): #3      StatefulElement.build
(package:flutter/src/widgets/framework.dart:3824:27)
[        ] I/flutter (13547): #4      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3735:15)
[        ] I/flutter (13547): #5      Element.rebuild
(package:flutter/src/widgets/framework.dart:3558:5)
[        ] I/flutter (13547): #6      ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3715:5)
[        ] I/flutter (13547): #7      StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:3863:11)
[        ] I/flutter (13547): #8      ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3710:5)
[        ] I/flutter (13547): #9      Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2954:14)
[        ] I/flutter (13547): #10     Element.updateChild
(package:flutter/src/widgets/framework.dart:2757:12)
[        ] I/flutter (13547): #11     SingleChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:4875:14)
[        ] I/flutter (13547): #12     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2954:14)
[        ] I/flutter (13547): #13     Element.updateChild
(package:flutter/src/widgets/framework.dart:2757:12)
[        ] I/flutter (13547): #14     SingleChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:4875:14)
[        ] I/flutter (13547): #15     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2954:14)
[        ] I/flutter (13547): #16     Element.updateChild
(package:flutter/src/widgets/framework.dart:2757:12)
[        ] I/flutter (13547): #17     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3746:16)
[        ] I/flutter (13547): #18     Element.rebuild
(package:flutter/src/widgets/framework.dart:3558:5)
[   +2 ms] I/flutter (13547): #19     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3715:5)
[        ] I/flutter (13547): #20     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3710:5)
[        ] I/flutter (13547): #21     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2954:14)
[        ] I/flutter (13547): #22     Element.updateChild
(package:flutter/src/widgets/framework.dart:2757:12)
[        ] I/flutter (13547): #23     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3746:16)
[   +1 ms] I/flutter (13547): #24     Element.rebuild
(package:flutter/src/widgets/framework.dart:3558:5)
[        ] I/flutter (13547): #25     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3715:5)
[        ] I/flutter (13547): #26     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3710:5)
[        ] I/flutter (13547): #27     ParentDataElement.mount
(package:flutter/src/widgets/framework.dart:4062:11)
[        ] I/flutter (13547): #28     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2954:14)
[        ] I/flutter (13547): #29     Element.updateChild
(package:flutter/src/widgets/framework.dart:2757:12)
[        ] I/flutter (13547): #30     ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:3746:16)
[        ] I/flutter (13547): #31     Element.rebuild
(package:flutter/src/widgets/framework.dart:3558:5)
[        ] I/flutter (13547): #32     ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:3715:5)
[        ] I/flutter (13547): #33     StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:3863:11)
[        ] I/flutter (13547): #34     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:3710:5)
[        ] I/flutter (13547): #35     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:2954:14)
[        ] I/flutter (13547): #36     Element.updateChild
(package:flutter/src/widgets/framework.dart:2757:12)
[        ] I/flutter (13547): #37     SliverMultiBoxAdaptorElement.updateChild
(package:flutter/src/widgets/sliver.dart:1030:36)
[        ] I/flutter (13547): #38
SliverMultiBoxAdaptorElement.createChild.<anonymous closure>
(package:flutter/src/widgets/sliver.dart:1015:20)
[        ] I/flutter (13547): #39     BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2251:19)
[        ] I/flutter (13547): #40     SliverMultiBoxAdaptorElement.createChild
(package:flutter/src/widgets/sliver.dart:1008:11)
[        ] I/flutter (13547): #41
RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:275:23)
[        ] I/flutter (13547): #42     RenderObject.invokeLayoutCallback.<anonymous
closure> (package:flutter/src/rendering/object.dart:1740:58)
[        ] I/flutter (13547): #43     PipelineOwner._enableMutationsToDirtySubtrees
(package:flutter/src/rendering/object.dart:797:15)
[        ] I/flutter (13547): #44     RenderObject.invokeLayoutCallback
(package:flutter/src/rendering/object.dart:1740:13)
[        ] I/flutter (13547): #45
RenderSliverMultiBoxAdaptor._createOrObtainChild
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:264:5)
[        ] I/flutter (13547): #46     RenderSliverMultiBoxAdaptor.addInitialChild
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:348:5)
[        ] I/flutter (13547): #47     RenderSliverList.performLayout
(package:flutter/src/rendering/sliver_list.dart:78:12)
[        ] I/flutter (13547): #48     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #49     RenderSliverPadding.performLayout
(package:flutter/src/rendering/sliver_padding.dart:182:11)
[        ] I/flutter (13547): #50     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[   +6 ms] I/flutter (13547): #51     RenderViewportBase.layoutChildSequence
(package:flutter/src/rendering/viewport.dart:407:13)
[        ] I/flutter (13547): #52     RenderViewport._attemptLayout
(package:flutter/src/rendering/viewport.dart:1322:12)
[        ] I/flutter (13547): #53     RenderViewport.performLayout
(package:flutter/src/rendering/viewport.dart:1240:20)
[        ] I/flutter (13547): #54     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #55
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (13547): #56     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #57
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (13547): #58     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #59
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (13547): #60     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #61
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (13547): #62     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #63
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (13547): #64     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #65
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (13547): #66     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #67
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (13547): #68     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #69
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (13547): #70     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #71
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[   +2 ms] I/flutter (13547): #72     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #73     RenderPositionedBox.performLayout
(package:flutter/src/rendering/shifted_box.dart:385:13)
[  +10 ms] I/flutter (13547): #74     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[  +22 ms] I/flutter (13547): #75     RenderStack.performLayout
(package:flutter/src/rendering/stack.dart:510:15)
[   +1 ms] I/flutter (13547): #76     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[   +9 ms] I/flutter (13547): #77     RenderPositionedBox.performLayout
(package:flutter/src/rendering/shifted_box.dart:385:13)
[   +3 ms] I/flutter (13547): #78     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[   +7 ms] I/flutter (13547): #79     MultiChildLayoutDelegate.layoutChild
(package:flutter/src/rendering/custom_layout.dart:142:11)
[   +1 ms] I/flutter (13547): #80     _ScaffoldLayout.performLayout
(package:flutter/src/material/scaffold.dart:431:7)
[   +1 ms] I/flutter (13547): #81     MultiChildLayoutDelegate._callPerformLayout
(package:flutter/src/rendering/custom_layout.dart:212:7)
[   +3 ms] I/flutter (13547): #82     RenderCustomMultiChildLayoutBox.performLayout
(package:flutter/src/rendering/custom_layout.dart:356:14)
[   +1 ms] I/flutter (13547): #83     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[   +6 ms] I/flutter (13547): #84
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[  +10 ms] I/flutter (13547): #85     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[  +27 ms] I/flutter (13547): #86
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[  +11 ms] I/flutter (13547): #87     _RenderCustomClip.performLayout
(package:flutter/src/rendering/proxy_box.dart:1215:11)
[  +36 ms] I/flutter (13547): #88     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[  +16 ms] I/flutter (13547): #89
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[   +1 ms] I/flutter (13547): #90     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[   +1 ms] I/flutter (13547): #91
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[   +3 ms] I/flutter (13547): #92     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[   +2 ms] I/flutter (13547): #93
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[   +1 ms] I/flutter (13547): #94     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[   +1 ms] I/flutter (13547): #95
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[   +1 ms] I/flutter (13547): #96     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[   +2 ms] I/flutter (13547): #97
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[   +2 ms] I/flutter (13547): #98     RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[   +1 ms] I/flutter (13547): #99
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[   +2 ms] I/flutter (13547): #100    RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #101
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (13547): #102    RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[        ] I/flutter (13547): #103
_RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (13547): #104    RenderOffstage.performLayout
(package:flutter/src/rendering/proxy_box.dart:3061:13)
[        ] I/flutter (13547): #105    RenderObject.layout
(package:flutter/src/rendering/object.dart:1644:7)
[   +7 ms] I/flutter (13547): #106    RenderStack.performLayout
(package:flutter/src/rendering/stack.dart:510:15)
[   +2 ms] I/flutter (13547): #107    RenderObject._layoutWithoutResize
(package:flutter/src/rendering/object.dart:1519:7)
[   +2 ms] I/flutter (13547): #108    PipelineOwner.flushLayout
(package:flutter/src/rendering/object.dart:766:18)
[   +1 ms] I/flutter (13547): #109
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame
(package:flutter/src/rendering/binding.dart:336:19)
[   +1 ms] I/flutter (13547): #110
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:701:13)
[   +2 ms] I/flutter (13547): #111
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:275:5)
[        ] I/flutter (13547): #112
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1008:15)
[        ] I/flutter (13547): #113
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:948:9)
[   +1 ms] I/flutter (13547): #114
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:860:5)
[ +738 ms] I/flutter (13547): #118    _invoke (dart:ui/hooks.dart:219:10)
[   +1 ms] I/flutter (13547): #119    _drawFrame (dart:ui/hooks.dart:178:3)
[  +11 ms] I/flutter (13547): (elided 5 frames from class _AssertionError and
package dart:async)
[   +1 ms] I/flutter (13547):
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
C:\sistemas\flutter\flutter1>flutter analyze
Analyzing flutter1...

   info - The method '_loginMock' isn't used - lib\main.dart:132:16 - unused_element
   info - The method '_logOut' isn't used - lib\main.dart:193:16 - unused_element

2 issues found. (ran in 11.0s)
```

```
C:\sistemas\flutter\flutter1>flutter doctor -v
[√] Flutter (Channel master, v1.3.11-pre.40, on Microsoft Windows [Version 10.0.17134.648],    locale es-AR)
    • Flutter version 1.3.11-pre.40 at C:\flutter
    • Framework revision a1bee54fda (11 hours ago), 2019-03-18 05:02:34 -0400
    • Engine revision e75f6de01f
    • Dart version 2.2.1 (build 2.2.1-dev.1.1 None)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\codig\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[!] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\codig\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] VS Code, 64-bit edition (version 1.32.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24)
      (emulator)

! Doctor found issues in 1 category.

C:\sistemas\flutter\flutter1>
```

Thanks!

**Comment by esarbanis** [comment] 2019-03-21 12:06
@codigo47 do you have any `Hero` widgets in `SearchesView` parent hierarchy?

**Comment by codigo47** [comment] 2019-03-21 12:17
Yes:

![image](https://user-images.githubusercontent.com/1730379/54751521-fef4cd80-4bb9-11e9-999c-b3be34e3ea9e.png)

```dart
    return Hero(
      tag: "hero_card_search_${s.name}",
      child:
      Card(                        
        elevation: AppSettings.cardElevation, 
        color: AppSettings.cardBackgroundColor,
        child: Container(
          padding: EdgeInsets.only(bottom: 10),              
          child: ListTile(                            
            //leading: Icon(Icons.search),              
            title: Padding(
              padding: EdgeInsets.only(top: 10),
              child: Text(s.name)
            ),
            subtitle: Column(
              children: subtitles,
            ),
            onTap: () {
              Search.currentSearch = s;
              Navigator.of(context).pushNamed('/search');
            },
          ),
        ),
      ),
    );   
```

**Comment by esarbanis** [comment] 2019-03-21 12:27
Since v1.3.10 a `Hero` cannot contain another `Hero` widget in its children hierarchy ([API doc](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/heroes.dart#L129)).

**Comment by 5hanth** [comment] 2020-01-14 17:20
@esarbanis I'm using `1.12.13+hotfix.5` and still couldn't nest `Hero` inside another `Hero` 🙈

**Comment by DennisKragekjaer** [comment] 2020-01-15 10:08
Now facing same problem (v1.12.13+hotfix.5). I think this must be a NEW bug, Im almost certain that I did nest Hero widgets a year ago. It should be possible to nest them, as long as they dont have the same tag.

Lets say you have a Holder Container(HC), holding a child container(CC). When you press the CC, you want a modal push/transition with CC as Hero.
You have a Button, when pressed, you navigates/pushes to another page with HC as Hero.

**Comment by 5hanth** [comment] 2020-01-15 10:12
@DennisKragekjaer I have commented the assert statement in core's hero class and able to nest hero without any issues. Not sure if this was asserted presuming any performance issues.

**Comment by 9thwall** [comment] 2020-03-14 18:52
I too started having this error after upgrading an old but solid working app. I couldn't figure out why this would be happening so I did what @5hanth did and everything is working like before. Not sure why this assertion is set because there doesn't seem to be any issues. Is this is a bug? Please enlighten us why this assertion needs to be set.

**Comment by DjangoOverloard** [comment] 2020-03-24 04:57
Can someone please explain how do you comment out the assertion? Do you have to go deep into the class of Hero or something?

**Comment by 9thwall** [comment] 2020-04-04 15:29
@DjangoOverloard 
in the newest build, it's line 373-376 in heroes.dart. 
You are looking for this..
```
assert(
      context.findAncestorWidgetOfExactType<Hero>() == null,
      'A Hero widget cannot be the descendant of another Hero widget.'
);
```

**Comment by tapizquent** [comment] 2020-04-29 22:59
Should this be 

> @DjangoOverloard
> in v1.12.13+hotfix.9, it's line 373-376 in heroes.dart.
> You are looking for this..
> 
> ```
> assert(
>       context.findAncestorWidgetOfExactType<Hero>() == null,
>       'A Hero widget cannot be the descendant of another Hero widget.'
> );
> ```

Is this safe to do? Why is this assert in place?

**Comment by azad47808** [comment] 2020-07-05 13:37
I hade the same problem in ListView,  I solved it after adding the index inside of Hero tag. because the Hero tag should be unique.

```
Hero(
                tag: "item" + this.index.toString(),
                child:
                    Image.asset("assets/images/design.jpg", fit: BoxFit.cover),
              ),
```

**Comment by tapizquent** [comment] 2020-07-05 13:39
> I hade the same problem in ListView,  I solved it after adding the index inside of Hero tag. because the Hero tag should be unique.
> 
> 
> 
> ```
> 
> Hero(
> 
>          tag: "item" + this.index.toString(),
> 
>          child: Image.asset("assets/images/design.jpg", fit: BoxFit.cover),
> 
> ),
> 
> ```

That is a different issue. The id should be unique. The problem is when you have a Hero inside another Hero. Even if they both have unique ids, it will throw the assertion

**Comment by markusaksli-nc** [comment] 2020-07-16 12:13
Closing this issue as a duplicate of #38684. Please follow up on the mentioned issue.

**Closed by markusaksli-nc** 2020-07-16 12:13 UTC
Labels: a: animation, customer: crowd, f: material design, framework
