### ISSUE TITLE
App crashing on production with Flutter 1.13.10-pre.65

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#49037] opened 2020-01-17 11:25 UTC
Latest version of our app was released using version `1.13.10-pre.65` on `master` channel. Since then, on Play Store Console, we're seeing a huge number of users are experiencing of crashes. On that version, the only meaningful change was migrating the app to Android V2 Embedding. Not sure if this may be related to https://github.com/flutter/flutter/issues/49008.

![image](https://user-images.githubusercontent.com/2807712/72608800-d5184e80-3923-11ea-9c04-6dee488e3f18.png)
![image](https://user-images.githubusercontent.com/2807712/72608916-0f81eb80-3924-11ea-87b7-1a11ebaaaf8e.png)

This is the stacktrace on the report of the error:
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:3746)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:235)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1784)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6986)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.embedding.engine.loader.FlutterLoader.a (FlutterLoader.java:233)
  at io.flutter.view.FlutterMain.a (FlutterMain.java:9)
  at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate (FlutterFirebaseMessagingService.java:12)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:3734)
  at android.app.ActivityThread.access$1400 (ActivityThread.java:235)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1784)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6986)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
```

And the most affected Android versions + devices, just in case it's useful information.

![image](https://user-images.githubusercontent.com/2807712/72608870-fa0cc180-3923-11ea-994e-9c0f33eb86d8.png)

I wasn't able to reproduce the crash on any of my devices, so not really sure what is causing it.

```
Flutter 1.13.10-pre.65 • channel master • https://github.com/flutter/flutter.git
Framework • revision 5d37de2685 (6 hours ago) • 2020-01-15 01:23:02 -0500
Engine • revision bc41ab5139
Tools • Dart 2.8.0 (build 2.8.0-dev.1.0 fe666ce592)
```

</details>

**Comment by iapicca** [comment] 2020-01-17 11:40
Hi @Zazo032 
The problem is being addressed in the issue you linked,
please follow up there.
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-01-17 11:40 UTC

**Comment by Zazo032** [comment] 2020-01-17 11:42
cc/ @dkwingsmt is this related to your issue? just for confirmation
