### ISSUE TITLE
Performance Issue/Yank with video_player in PageView

### ISSUE THREAD

**Issue by flying-wizzy** [flutter/flutter#90320] opened 2021-09-18 09:26 UTC
I've been struggling with severe yanks with the "official" flutter *video_player* library in combination with the PageView widget.

### My Goal ###

Scroll *smoothly* and *quickly* through several pages of a PageView widget, that contain a Video widget each.

### Actual Result ###

When I try to scroll through those pages quickly, I get terrible yanks/performance issues. When I swipe through the pages slowly, and wait for the scrolling animation to finish, everything is smooth. See my video recorded on a **Xiaomi Redmi Note 8 Pro** in **profile** mode as proof.

[GIF: video proof of the yanks in the app][2]

## Performance Analysis ##

I tried finding help by consulting flutter performance tool. The tool shows massive spikes in raster time. In one example 51.7 ms raster time, 43.0 ms of that time needed for shader compilation. I'm not experienced enough to understand what that means or how that information helps me, though. Screenshot follows:

[screenshot: flutter performance tool screenshot showing slow frame][1]

## What I tried so far ##

 1. Removing the line `controller.dispose();` resolves the issue, but that leeds to memory leaks and the widgets crashing eventually.
2. I tried wrapping the `controller.dispose();` into a `WidgetsBinding.instance!.addPostFrameCallback((_) async {}`, but that didn't help

## My Code ##

```
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

class ExamplePageView extends StatelessWidget {
  ExamplePageView({Key? key}) : super(key: key);

  final PageController pageController = PageController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        height: MediaQuery.of(context).size.height,
        child: PageView(
          controller: pageController,
          onPageChanged: (value) {},
          children: [
            ExampleVideo(),
            ExampleVideo(),
            ExampleVideo(),
            ExampleVideo(),
            ExampleVideo(),
            ExampleVideo(),
          ],
        ),
      ),
    );
  }
}

class ExampleVideo extends StatefulWidget {
  const ExampleVideo({Key? key}) : super(key: key);

  @override
  State<ExampleVideo> createState() => _ExampleVideoState();
}

class _ExampleVideoState extends State<ExampleVideo> {
  late VideoPlayerController controller;

  @override
  void initState() {
    super.initState();
    controller = VideoPlayerController.network(
        "https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4");
    controller
      ..initialize()
      ..addListener(() {
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: Alignment.center,
      child: Container(
        constraints: BoxConstraints(
          maxHeight: MediaQuery.of(context).size.height,
        ),
        child: AspectRatio(
          aspectRatio: 16 / 9,
          child: controller.value.isInitialized
              ? VideoPlayer(controller)
              : Container(
                  color: Colors.black,
                ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
}

```

Flutter Doctor shows no issues, video_player and flutter are in their respective latest version. Thank you for helping! :)

Also posted on [stackoverflow](https://stackoverflow.com/questions/69223542/flutter-performance-issue-yank-with-video-player-in-pageview).

  [1]: https://i.stack.imgur.com/XQAXz.png
  [2]: https://i.stack.imgur.com/c74OH.gif

**Comment by rawquesh** [comment] 2021-09-18 14:04
`preload_page_view` and `cache_video_player` might help you.

**Comment by flying-wizzy** [comment] 2021-09-18 15:38
Thanks for your comment @rawquesh! Those packages do help, and performance is smooth while scrolling! 

_However_, I don't really like this solution, since it only seems to move the yank/performance issue to another point in time, namely when the PreloadPageView is being disposed of. 
I have about 30 pages in my PageView in my real app, and preloading them all would be wasteful. If I set the `preloadPagesCount` attribute in `preload_page_view` to a reasonable number, like `4`, I have a smooth scrolling experience until I reach page number 4. From then on it's yanky all over again. Also, as mentioned, when the `PreloadPageView` is disposed, the app needs some time to dispose of all the `VideoController`s  --> on my phone, it takes about a second until the app is responsive again.

**Comment by rawquesh** [comment] 2021-09-18 15:46
@flying-wizzy I understand, you can avoid the lag by just not load the video while you are scrolling you can use `visibility_detector ` for that I have done that same thing in listview with cache_video_playar, you can see here [app link ](https://play.google.com/store/apps/details?id=com.memebaaz.MemeBaaz)

**Comment by flying-wizzy** [comment] 2021-09-22 23:32
Thanks for your input @TahaTesser ! I agree, disposal of the `VideoController` seems to be the issue here. I haven't tried WebView or google maps, but you're probably right.

I have tried diminishing the problem by using `PageView.builder`, if that's what you mean by lazy loading, but to no avail. 
I'm not sure how to lazily dispose or what that means, though. Doesn't flutter automatically build/ dispose of the Video widget and the `VideoController` right away, when it's coming into view/ is moving out of the viewport? To my (limited) knowledge, that is what lazy loading/ disposal resembles.

Anyhow, even if I delay the disposal of the controller even further, doesn't that just move the jank to another point in time? Can you explain to me how this approach could solve the problem altogether?

**Comment by flying-wizzy** [comment] 2021-09-22 23:38
> @flying-wizzy I understand, you can avoid the lag by just not load the video while you are scrolling you can use `visibility_detector ` for that I have done that same thing in listview with cache_video_playar, you can see here [app link ](https://play.google.com/store/apps/details?id=com.memebaaz.MemeBaaz)

I'm pretty sure disposal of the controller is rather the issue than loading the video. Reason being, if you simply remove the `controller.dispose()` part from the code, everything is buttery smooth. `visibility_detector` is an interesting approach, though, thank you for your input, I'll give that a shot as well.

**Comment by TahaTesser** [comment] 2021-09-23 07:03
Hi @flying-wizzy 
There is an open issue with same problem, closing as duplicate of https://github.com/flutter/flutter/issues/34553

**Closed by TahaTesser** 2021-09-23 07:03 UTC
Labels: in triage
