### ISSUE TITLE
Trying to scrap some data from an internal website

### ISSUE THREAD

**Issue by elamir611** [flutter/flutter#42313] opened 2019-10-09 08:29 UTC
Hello Everyone
I have an internal website that uses login page then summary page

when i put the login page in the http.get it return 200 authentication succeeded but it doesn't retrieve any information

when i put the link for the summary page (that have the information i need) in the http.get authentication fail and return 401

i use basic Authentication

do you have any advice ?

**Comment by iapicca** [comment] 2019-10-09 11:38
Hi @elamir611 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by stuartmorgan** [comment] 2019-10-09 16:40
It sounds like your issue with authentication in the `http` package, which isn't part of Flutter itself. If you believe there's a bug in its authentication handling, you'll want to file a bug in [its issue tracker](https://github.com/dart-lang/http). If you're just looking for help on using the APIs, a general support forum like StackOverflow would be the best place to ask.

Closing since this isn't a bug or a feature request for Flutter itself.

**Closed by stuartmorgan** 2019-10-09 16:40 UTC
Labels: created via support template, waiting for customer response

**Comment by elamir611** [comment] 2019-10-10 06:19
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17134.885], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!
