### ISSUE TITLE
switching from beta to stable breaks iOS build, magic line fixes for release only

### ISSUE THREAD

**Issue by maks** [flutter/flutter#80561] opened 2021-04-16 04:51 UTC
I recently switched from using beta on local machine building android to stable, the local mac I was using for iOS builds was always on stable.
This seemed to break the iOS build.
Following the suggestion from [this comment](https://github.com/flutter/flutter/issues/70895#issuecomment-792755327) fixed the error:
```
error: 'Flutter/Flutter.h' file not found
```
for release builds using `flutter build ipa` but did not fix the error for `flutter run`.

I have no idea why this magic line was missing  from my podfile, I have no idea why adding it in fixes the release build but not the debug builds.

Any explanation or further information on the above error or any of the above unanswered questions would be most appreciated.

**Comment by TahaTesser** [comment] 2021-04-16 07:58
Hi @maks 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/79920
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-16 07:58 UTC
Labels: in triage
