### ISSUE TITLE
Label TextStyle in SnackBarAction

### ISSUE THREAD

**Issue by KunjKanani** [flutter/flutter#144769] opened 2024-03-07 12:04 UTC
### Use case

I am using SnackBarAction. I want to change the label text style. Currently, It has only support for textcolor. I purpose to introduce TextStyle for labels.

### Proposal

```
SnackBarAction(
  label: 'Go To Cart',
  // labelStyle: Style Support
  onPressed: () {
  },
),
```

**Comment by darshankawar** [comment] 2024-03-07 12:39
Closing as duplicate of https://github.com/flutter/flutter/issues/46599

**Closed by darshankawar** 2024-03-07 12:39 UTC
Labels: in triage
