### ISSUE TITLE
Flutter 1.22, FlutterFire, and Xcode 14 complains about IPHONEOS_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter#66103] opened 2020-09-18 09:25 UTC
I'm in the process of building out a codelab for FlutterFire https://github.com/flutter/codelabs/pull/20

With Xcode 14, I'm seeing a new error:

```bash
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target
    'Firebase' from project 'Pods')
```

We have set the minimum iOS version to 9.0 in a variety of places, but the generated `./ios/Pods/Pods.xcodeproj/project.pbxproj` has a bunch of lines that match `IPHONEOS_DEPLOYMENT_TARGET = 8.0;`

Any chance of updating the template `ios/Podfile` that we generate to set iOS 9? The following line is at the top of file, but it is currently commented out.

```ruby
platform :ios, '9.0'
```

**Comment by jmagman** [comment] 2020-09-18 16:58
This is actually a pretty old problem (that's why the comment you uncommented was originally added https://github.com/flutter/flutter/pull/4893/files#diff-3484408d815583a1721faee188827c45R5), and is a duplicate of https://github.com/flutter/flutter/issues/40109 and I guess I shouldn't have closed that one.  I'll reopen it and duplicate this over there since it already has history.

CocoaPods discussion: https://github.com/CocoaPods/CocoaPods/issues/7314

Please see previous attempts to do this and discussion around it:
https://github.com/flutter/flutter/pull/36117
https://github.com/flutter/flutter/issues/40109#issuecomment-529691520

**Comment by jmagman** [comment] 2020-09-18 16:58
Duplicate of #40109

**Closed by jmagman** 2020-09-18 16:58 UTC
Labels: a: error message, passed first triage, t: xcode, tool

**Comment by PatrickRic** [comment] 2020-09-28 18:29
I had the same problem, but a simple `flutter clean` fixed it for me. In my case, I think it occurred because I updated XCode and Flutter.

**Comment by mnorhamizan** [comment] 2020-10-10 15:44
@jmagman, so what was being done really?

**Comment by jmagman** [comment] 2020-10-12 17:15
The fix explanation is in https://github.com/flutter/flutter/pull/66590.  It is available in the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels).
