### ISSUE TITLE
[tool_crash] String: <44 characters>

### ISSUE THREAD

**Issue by araqelyankaren99** [flutter/flutter#132652] opened 2023-08-16 12:08 UTC
## Command
```
flutter run --profile
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <44 characters>
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:133:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DartDevelopmentService.startDartDevelopmentService (package:flutter_tools/src/base/dds.dart:54:22)
<asynchronous suspension>
#3      FlutterDevice.connect.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:266:11)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.2.1 22D68 darwin-x64, locale en-US)
    • Flutter version 3.3.9 on channel stable at /Users/karenkhzmalyan/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (9 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/karenkhzmalyan/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:

**Comment by dam-ease** [comment] 2023-08-16 12:12
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108812.

Kindly subscribe to the original issue for updates.

Thank you

**Closed by dam-ease** 2023-08-16 12:12 UTC
Labels: in triage
