### ISSUE TITLE
RawKeyboard error: Attempted to send a key down event when no keys are in keysPressed

### ISSUE THREAD

**Issue by kebyzak** [flutter/flutter#151940] opened 2024-07-18 06:55 UTC
### Steps to reproduce

1. Use the flutter_barcode_listener package in a Flutter project.
2. Run the application on a Windows device.
3. Connect a hardware scanner.
4. Scan a 1D barcode consisting only of numbers - it works fine.
5. Scan a 2D barcode containing symbols and letters.
6. Observe the error message.

### Expected results

The 2D barcode should be scanned and processed without any errors.

### Actual results

======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#72ac3(logicalKey: LogicalKeyboardKey#df100(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#ed430(usbHidUsage: "0x000700e1", debugName: "Shift Left"), repeat: false) and its data: RawKeyEventDataWindows#b33a7(keyCode: 160, scanCode: 42, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 862 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

### Code sample

<details open><summary>Code sample</summary>

```dart
return Stack(
              children: [
                if (state.barcodeListening)
                  BarcodeKeyboardListener(
                    key: const Key('home'),
                    bufferDuration: const Duration(milliseconds: 200),
                    onBarcodeScanned: (barcode) {
                      context.read<HomeBloc>().add(BarcodeScanned(barcode));
                    },
                    child: Container(),
                  ),
                Focus(
                  onKeyEvent: (FocusNode node, KeyEvent event) {
                    if (AppVariables.ignoringKeyDownKeys.contains(event.logicalKey)) {
                      return KeyEventResult.handled;
                    } else {
                      return KeyEventResult.ignored;
                    }
                  },
                  child: Column(
                    mainAxisSize: MainAxisSize.max,
                    children: [
                      AppRepository.buildSearchBar(
                          context: context, searchFieldController: searchFieldController, isListView: state.isListView),
                      Expanded(
                        child: Padding(
                          padding: const EdgeInsets.fromLTRB(5, 5, 10, 5),
                          child: _buildItems(
                            context: context,
                            state: state,
                            searchFieldController: searchFieldController,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            );
            
              Future<void> _barcodeScanned(Emitter<HomeState> emit, String barcode) async {
    print("Barcode scanned: $barcode");

    Map<String, String> result = {'excise_stamp': '', 'productCode': ''};
    // Use the extractBarcode function to handle barcodes with English letters
    barcode = extractBarcode(barcode, result);
    final prefix = CurrentSession.instance.currentCompanySettings?.pluPrefix;
    final match = RegExp(r'(\d+)(.*)').firstMatch(barcode);

    String barcode1D = "";
    String? exciseStamp = result['excise_stamp'];

    if (match != null) {
      barcode1D = match.group(1) ?? "";
      exciseStamp = result['excise_stamp'];
    }

    if (prefix != null &&
        barcode1D.startsWith(prefix.toString()) &&
        barcode1D.length >= 12) {
      String tempBarcode =
          barcode1D.substring(1, 14); // Adjusted to capture the correct part

      final pluString = tempBarcode.substring(0, 5);
      final weightString = tempBarcode.substring(5);
      final plu = int.tryParse(pluString);
      if (plu != null) {
        final weightInGrams = int.tryParse(weightString);
        if (weightInGrams != null) {
          final variations = homeRepo.variationsByPluCode(plu);
          if (variations.isEmpty) {
            throw ProductNotFound();
          } else {
            final variation = variations.first;
            Decimal weight = Decimal.fromInt(weightInGrams);
            if (variation.measurement_unit == 'unit_kg') {
              weight = Decimal.parse((weight / Decimal.fromInt(1000))
                  .toDouble()
                  .toStringAsFixed(3));
            }
            addVariation(emit, variation, quantity: weight);
          }
        } 
      } 
    } else {
      List<Variation>? variations = homeRepo.variationsByBarcode(barcode);

      if (variations.isEmpty) {
        throw VariationByBarcodeNotFound(barcode1D);
      } else if (variations.length == 1) {
        add(VariationSelected(variations.first));
      } else {
        emit(state.copyWith(appStatus: VariationSelection(variations)));
      }
    }
  }

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Unable to parse JSON message:
The document is empty.
Unable to parse JSON message:
The document is empty.

======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
Attempted to send a key down event when no keys are in keysPressed. This state can occur if the key event being sent doesn't properly set its modifier flags. This was the event: RawKeyDownEvent#72ac3(logicalKey: LogicalKeyboardKey#df100(keyId: "0x200000102", keyLabel: "Shift Left", debugName: "Shift Left"), physicalKey: PhysicalKeyboardKey#ed430(usbHidUsage: "0x000700e1", debugName: "Shift Left"), repeat: false) and its data: RawKeyEventDataWindows#b33a7(keyCode: 160, scanCode: 42, characterCodePoint: 0, modifiers: 0)
'package:flutter/src/services/raw_keyboard.dart':
Failed assertion: line 862 pos 7: 'event is! RawKeyDownEvent || _keysPressed.isNotEmpty'

When the exception was thrown, this was the stack:
#2      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:862:7)
#3      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1161:30)
#4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
#5      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581:35)
#6      _invoke2 (dart:ui/hooks.dart:344:13)
#7      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#8      _Channel.push (dart:ui/channel_buffers.dart:135:31)
#9      ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#10     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#11     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
(elided 2 frames from class _AssertionError)
====================================================================================================

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3880], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.5)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.91.0)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by kebyzak** [comment] 2024-07-18 07:24
label:platform-windows

**Comment by kebyzak** [comment] 2024-07-18 07:34
Also, my barcode is: 0104603679007354215<rSSBVs%W:>T↔91EE09↔92cs76JaUWVRtu1W3YLSBaJjZMY+bVgYEdBrTdSRygJA0=
but flutter gives me: 
flutter: Barcode scanned: 0104603679007354215 ¼R SSB VS5Wº¾ T91 E E0992CS76 JAUWV RTU1 W3YLS BA JJ ZMY »B VGY ED BR TDS RYGJ A0»

**Comment by danagbemava-nc** [comment] 2024-07-18 09:16
Closing this as a duplicate of https://github.com/flutter/flutter/issues/143155

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-07-18 09:16 UTC
Labels: in triage
