### ISSUE TITLE
Crash when overriding viewDidLoad() of extension of FlutterViewController

### ISSUE THREAD

**Issue by FineTillYouCameAlong** [flutter/flutter#57905] opened 2020-05-24 19:29 UTC
Crash on iOS emulators (all devices, all versions) as well as physical device. This used to work before I upgraded to Xcode whatever.the.latest.version.is and Catalina.

Steps to reproduce:

1. create a demo Flutter project
2. open its AppDelegate.swift
3. add the following:

```
extension FlutterViewController {
    open override func viewDidLoad() {

    }
}
```

4. run

Produces a crash:
```
> Flutter`flutter::Rasterizer::Setup:
    0x10f46bf96 <+0>:   pushq  %rbp
    0x10f46bf97 <+1>:   movq   %rsp, %rbp
    0x10f46bf9a <+4>:   pushq  %r15
    0x10f46bf9c <+6>:   pushq  %r14
    0x10f46bf9e <+8>:   pushq  %r12
    0x10f46bfa0 <+10>:  pushq  %rbx
    0x10f46bfa1 <+11>:  subq   $0x10, %rsp
    0x10f46bfa5 <+15>:  movq   %rdi, %rbx
    0x10f46bfa8 <+18>:  movq   (%rsi), %rax
    0x10f46bfab <+21>:  movq   $0x0, (%rsi)
    0x10f46bfb2 <+28>:  movq   0x48(%rdi), %rdi
    0x10f46bfb6 <+32>:  movq   %rax, 0x48(%rbx)
    0x10f46bfba <+36>:  testq  %rdi, %rdi
    0x10f46bfbd <+39>:  je     0x10f46bfc5               ; <+47>
    0x10f46bfbf <+41>:  movq   (%rdi), %rax
    0x10f46bfc2 <+44>:  callq  *0x8(%rax)
    0x10f46bfc5 <+47>:  cmpb   $0x0, 0xb0(%rbx)
    0x10f46bfcc <+54>:  je     0x10f46bfe4               ; <+78>
    0x10f46bfce <+56>:  movq   0xa8(%rbx), %rsi
    0x10f46bfd5 <+63>:  movzbl 0xa0(%rbx), %edx
    0x10f46bfdc <+70>:  movq   %rbx, %rdi
    0x10f46bfdf <+73>:  callq  0x10f46c0b8               ; flutter::Rasterizer::SetResourceCacheMaxBytes(unsigned long, bool)
    0x10f46bfe4 <+78>:  movq   0x50(%rbx), %rdi
    0x10f46bfe8 <+82>:  callq  0x10f41756a               ; flutter::CompositorContext::OnGrContextCreated()
    0x10f46bfed <+87>:  movq   0x48(%rbx), %rdi
->  0x10f46bff1 <+91>:  movq   (%rdi), %rax
    0x10f46bff4 <+94>:  callq  *0x30(%rax)
    0x10f46bff7 <+97>:  testq  %rax, %rax
    0x10f46bffa <+100>: je     0x10f46c0ab               ; <+277>
    0x10f46c000 <+106>: leaq   0x10(%rbx), %r15
    0x10f46c004 <+110>: leaq   -0x28(%rbp), %r12
    0x10f46c008 <+114>: movq   %r12, %rdi
    0x10f46c00b <+117>: movq   %r15, %rsi
    0x10f46c00e <+120>: callq  0x10f41705c               ; flutter::TaskRunners::GetPlatformTaskRunner() const
    0x10f46c013 <+125>: movq   (%r12), %rdi
    0x10f46c017 <+129>: movq   (%rdi), %rax
    0x10f46c01a <+132>: callq  *0x30(%rax)
    0x10f46c01d <+135>: movq   %rax, %r14
    0x10f46c020 <+138>: movq   (%r12), %rdi
    0x10f46c024 <+142>: testq  %rdi, %rdi
    0x10f46c027 <+145>: je     0x10f46c03e               ; <+168>
    0x10f46c029 <+147>: lock   
    0x10f46c02a <+148>: decl   0x8(%rdi)
    0x10f46c02d <+151>: jne    0x10f46c03e               ; <+168>
    0x10f46c02f <+153>: addq   $0x8, %rdi
    0x10f46c033 <+157>: movq   -0x8(%rdi), %rax
    0x10f46c037 <+161>: addq   $-0x8, %rdi
    0x10f46c03b <+165>: callq  *0x8(%rax)
    0x10f46c03e <+168>: leaq   -0x28(%rbp), %r12
    0x10f46c042 <+172>: movq   %r12, %rdi
    0x10f46c045 <+175>: movq   %r15, %rsi
    0x10f46c048 <+178>: callq  0x10f4170aa               ; flutter::TaskRunners::GetRasterTaskRunner() const
    0x10f46c04d <+183>: movq   (%r12), %rdi
    0x10f46c051 <+187>: movq   (%rdi), %rax
    0x10f46c054 <+190>: callq  *0x30(%rax)
    0x10f46c057 <+193>: movq   %rax, %r15
    0x10f46c05a <+196>: movq   (%r12), %rdi
    0x10f46c05e <+200>: testq  %rdi, %rdi
    0x10f46c061 <+203>: je     0x10f46c078               ; <+226>
    0x10f46c063 <+205>: lock   
    0x10f46c064 <+206>: decl   0x8(%rdi)
    0x10f46c067 <+209>: jne    0x10f46c078               ; <+226>
    0x10f46c069 <+211>: addq   $0x8, %rdi
    0x10f46c06d <+215>: movq   -0x8(%rdi), %rax
    0x10f46c071 <+219>: addq   $-0x8, %rdi
    0x10f46c075 <+223>: callq  *0x8(%rax)
    0x10f46c078 <+226>: movl   $0x28, %edi
    0x10f46c07d <+231>: callq  0x10fc2f256               ; symbol stub for: operator new(unsigned long)
    0x10f46c082 <+236>: movq   %rax, %r12
    0x10f46c085 <+239>: movq   %rax, %rdi
    0x10f46c088 <+242>: movq   %r14, %rsi
    0x10f46c08b <+245>: movq   %r15, %rdx
    0x10f46c08e <+248>: callq  0x10f4297ca               ; fml::RasterThreadMerger::RasterThreadMerger(fml::TaskQueueId, fml::TaskQueueId)
    0x10f46c093 <+253>: movq   0xd0(%rbx), %rdi
    0x10f46c09a <+260>: movq   %r12, 0xd0(%rbx)
    0x10f46c0a1 <+267>: testq  %rdi, %rdi
    0x10f46c0a4 <+270>: je     0x10f46c0ab               ; <+277>
    0x10f46c0a6 <+272>: callq  0x10f414a28               ; fml::RefCountedThreadSafe<fml::RasterThreadMerger>::Release() const
    0x10f46c0ab <+277>: addq   $0x10, %rsp
    0x10f46c0af <+281>: popq   %rbx
    0x10f46c0b0 <+282>: popq   %r12
    0x10f46c0b2 <+284>: popq   %r14
    0x10f46c0b4 <+286>: popq   %r15
    0x10f46c0b6 <+288>: popq   %rbp
    0x10f46c0b7 <+289>: retq   
```
My flutter doctor -v:
```
> [✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-RS)
    • Flutter version 1.17.1 at /Users/redacted/Library/flutter
    • Framework revision f7a6a7906b (12 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2
>
> 
>[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/redacted/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio
      3.5.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
>
>[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.2

>[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 3.5.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
>
>[✓] Connected device (1 available)
    • iPhone 11 • 4A912B17-A850-4977-B1F6-80A06AA66B18 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
>
>• No issues found!
```

**Comment by TahaTesser** [comment] 2020-05-25 12:20
duplicate of https://github.com/flutter/flutter/issues/56622

**Closed by TahaTesser** 2020-05-25 12:20 UTC
