### ISSUE TITLE
localeResolutionCallback is not passed the device locale

### ISSUE THREAD

**Issue by guidezpl** [flutter/flutter#45343] opened 2019-11-21 14:11 UTC
MaterialApp's localeResolutionCallback should be passed the device locale (as in Web/Android/iOS). However, it is being passed null, meaning there is no way to determine the system locale on macOS (Linux and Windows have this issue as well).

**Target Platform:** macOS
**Target OS version/browser:** Version 10.14.6
**Devices:** Macbook

## Logs

```
 flutter doctor -v
[✓] Flutter (Channel master, v1.12.6-pre.15, on Mac
    OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.12.6-pre.15 at
      /Users/plg/development/flutter
    • Framework revision 43a8a1902e (3 hours ago),
      2019-11-21 12:09:43 +0100
    • Engine revision 7a77e3625d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices    (Android SDK version 29.0.2)
    • Android SDK at /Users/plg/Library/Android/sdk
    • Android NDK location not configured
      (optional; useful for native profiling
      support)
    • Platform android-stable, build-tools 29.0.2
    • ANDROID_SDK_ROOT =
      /Users/plg/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin
      /java
    • Java version OpenJDK Runtime Environment
      (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode
    11.2.1)
    • Xcode at
      /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android
      Studio with Blaze.app/Contents
    ✗ Flutter plugin not installed; this adds
      Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart
      specific functionality.
    • Java version OpenJDK Runtime Environment
      (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment
      (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (4 available)
    • iPhone 11 Pro •
      E2CD6618-F1C3-4AA9-BA3D-CD0972AC86EE • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-2
      (simulator)
    • macOS         • macOS
      • darwin-x64     • Mac OS X 10.14.6 18G103
    • Chrome        • chrome
      • web-javascript • Google Chrome 78.0.3904.97
    • Web Server    • web-server
      • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by csells** [comment] 2020-03-12 16:00
@stuartmorgan @gspencergoog for their input

**Comment by gspencergoog** [comment] 2020-03-12 16:03
Yes, this should be on our list to implement.

**Comment by stuartmorgan** [comment] 2020-03-12 17:18
Duplicate of #45152

**Closed by stuartmorgan** 2020-03-12 17:18 UTC
Labels: a: desktop, a: internationalization, f: material design, framework, ⌘‬ platform-mac, ❖ platform-windows, 🐧 platform-linux
