### ISSUE TITLE
[tool_crash] OSError: OS Error: Can't assign requested address, errno = 49

### ISSUE THREAD

**Issue by JiangYelinGit** [flutter/flutter#100513] opened 2022-03-22 01:03 UTC
## Command
```
flutter --no-color attach --machine --device-id=58C89F5F-4793-45DD-873E-F1C745A8C764 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OSError: OS Error: Can't assign requested address, errno = 49
```
#0      _NativeSocket.nativeSetRawOption (dart:io-patch/socket_patch.dart:1558:35)
#1      _NativeSocket.setRawOption (dart:io-patch/socket_patch.dart:1480:5)
#2      _RawDatagramSocket.setRawOption (dart:io-patch/socket_patch.dart:2373:56)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:138:16)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/mdns_discovery.dart:66:7)
<asynchronous suspension>
#5      MDnsObservatoryDiscovery.getObservatoryUri (package:flutter_tools/src/mdns_discovery.dart:153:51)
<asynchronous suspension>
#6      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:278:11)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:214:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.6.1 20G224 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/ext.jiangyelin1/jd/flutter_sdk/flutter_2.2.6
    • Framework revision f4abaa0735 (9 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/ext.jiangyelin1/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 Pro Max (mobile) • 58C89F5F-4793-45DD-873E-F1C745A8C764 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 99.0.4844.83

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.jd.focus_flutter
**iOS bundle identifier**: com.jd.focusFlutter
**Creation channel**: null
**Creation framework version**: null
### Plugins
ro_f_split
connectivity-0.4.9+5
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
device_info-0.4.2+10
disk_space-0.0.3
flutter_bugly-0.2.8
flutter_downloader
flutter_native_image
flutter_plugin_record
package_info-0.4.3+4
path_provider-1.6.7
path_provider_macos-0.0.4+8
sentry_flutter-4.0.6
shared_preferences-0.5.7
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
sqflite_sqlcipher-1.1.0+1
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
video_player-2.2.3
video_player_web-2.0.6
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.0.13
wechat_kit

**Comment by danagbemava-nc** [comment] 2022-03-22 06:54
Duplicate of #97489

**Closed by danagbemava-nc** 2022-03-22 06:54 UTC
Labels: in triage
