### ISSUE TITLE
I/Adreno  (10180): DequeueBuffer: dequeueBuffer failed

### ISSUE THREAD

**Issue by eyalkutz** [flutter/flutter#35900] opened 2019-07-10 19:56 UTC
this app is still a work in progress
## Steps to Reproduce

[main.dart.txt](https://github.com/flutter/flutter/files/3379072/main.dart.txt)
I had to send main.dart as a .txt file because github doesnt allow to attach a .dart file
1. tap something (anything) in the homescreen
2. tap something (anything) in the "Breed" screen
3. play with the "Toggle Button" and with navigating back and forth from "favorites view"
4. at a random point while playing with it, it will randomly freeze and constantly throw the following error: `I/Adreno  (10180): DequeueBuffer: dequeueBuffer failed`

## Logs

[output.txt](https://github.com/flutter/flutter/files/3379193/output.txt)
(too much output, github complained)

```
Analyzing google_play_recreation...

   info - Unused import: 'package:transparent_image/transparent_image.dart' - lib\main.dart:7:8 - unused_import
   info - Unused import: 'dart:math' - lib\main.dart:9:8 - unused_import
   info - Unused import: 'package:shared_preferences/shared_preferences.dart' - lib\main.dart:10:8 - unused_import
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its
          instance fields are not final: Home.breeds, Home.breed - lib\main.dart:129:7 - must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its
          instance fields are not final: Thambnail.image, Thambnail.name, Thambnail.onPressed - lib\main.dart:205:7 -
          must_be_immutable
   info - This function has a return type of 'Widget', but doesn't end with a return statement - lib\main.dart:235:38 -
          missing_return
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its
          instance fields are not final: Category.images - lib\main.dart:301:7 - must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its
          instance fields are not final: Breed.breed, Breed.subBreed, Breed.images - lib\main.dart:433:7 -
          must_be_immutable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its
          instance fields are not final: Zoom.image, Zoom.key - lib\main.dart:556:7 - must_be_immutable
   info - The for, if and spread elements were not supported until version 2.2.2, but this code is required to be able
          to run on earlier versions - lib\main.dart:642:11 - sdk_version_ui_as_code

10 issues found. (ran in 12.2s)
```

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17134.829], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\developement\flutter
    • Framework revision b712a172f9 (24 hours ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\developement\AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\developement\AndroidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.0)
    • VS Code at C:\Users\אייל קוץ\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • ONEPLUS A6003 • 29484b14 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by eyalkutz** [comment] 2019-07-11 09:03
I need a quick fix because this completely prevents me from debugging my app

**Comment by esskar** [comment] 2020-08-14 18:38
How is the status on this?

**Comment by eyalkutz** [comment] 2020-08-15 15:04
@esskar this does not seem to happen anymore so I guess the issue can be closed

**Comment by ogustavopimentel** [comment] 2020-08-17 12:32
My app has a similar error that causes crash whenever the app is minimized:

_W/MALI    (28014): winsysp_window_buffer_get:2379: [MALI] window->dequeueBuffer Failed, return -19 ... ..._

**Comment by esskar** [comment] 2020-08-17 20:02
@eyalkutz please see #63725 ; i can reproduce it on an Android 7.1.2 device; I cannot upgrade to an higher version as this is part of a larger company; they will upgrade to Android 8 end of next year.

**Comment by b055man** [comment] 2020-08-18 13:13
Observing the same on 7.1.1 device, in any app. Flutter 1.20.2

Is there any workaround for this issue?

**Comment by Majamato** [comment] 2020-08-18 23:18
Same problem, same android version: 7.1.1, flutter 1.20

**Comment by cschellhas** [comment] 2020-08-19 11:47
Same problem, Android 7.1.1 on Flutter 1.20.2.

**Comment by limocute** [comment] 2020-08-20 07:18
Same problem, Android 7.0 on Flutter 1.20.2.

_W/MALI    (11396): winsysp_window_buffer_get:2383: [MALI] window->dequeueBuffer Failed, return -19_

**Comment by matejkramny** [comment] 2020-08-21 03:11
Here's a gif showing what happens if that helps.

![flutter](https://user-images.githubusercontent.com/797608/90848087-8ee60a80-e39e-11ea-95a3-3b4b7f9a9794.gif)

After returning from the app switcher the console reports this repeatedly

```
I/Adreno  ( 9122): DequeueBuffer: dequeueBuffer failed
I/Adreno  ( 9122): flush reason set to EsxFlushModeReasonInvalidBinLayout
I/Adreno  ( 9122): flush reason set to EsxFlushModeReasonInvalidBinLayout
```

`flutter doctor -v`
```
[✓] Flutter (Channel stable, 1.20.2, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.20.2 at /home/matej/flutter
    • Framework revision bbfbf1770c (8 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/matej/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/matej/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at /home/matej/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```

**Comment by matejkramny** [comment] 2020-08-21 03:59
Tried creating a new project, can reproduce it without any modification to the code.

Tried flutter beta channel, same issue.

Some additional output from logcat.

```
2020-08-21 11:56:17.367 425-1880/? E/BufferQueueProducer: [SurfaceView - com.example.bug/com.example.bug.MainActivity] dequeueBuffer: BufferQueue has no connected producer
2020-08-21 11:56:17.367 13046-13073/com.example.bug I/Adreno: DequeueBuffer: dequeueBuffer failed
2020-08-21 11:56:17.367 13046-13073/com.example.bug I/Adreno: flush reason set to EsxFlushModeReasonInvalidBinLayout
2020-08-21 11:56:17.367 13046-13073/com.example.bug I/Adreno: flush reason set to EsxFlushModeReasonInvalidBinLayout
```

**Comment by matejkramny** [comment] 2020-08-24 03:26
Downgrade flutter

**Comment by llearn** [comment] 2020-08-24 09:37
> Downgrade flutter

which version?

**Comment by matejkramny** [comment] 2020-08-24 09:39
Stable 1.20. Think it's 1.15

**Comment by cschellhas** [comment] 2020-08-24 10:54
> Anything stable before 1.20. Think it's 1.15

Last stable before was 1.17.5.

See: [https://flutter.dev/docs/development/tools/sdk/releases](https://flutter.dev/docs/development/tools/sdk/releases)

**Comment by tryadelion** [comment] 2020-08-25 08:39
Can reproduce on android 7.1.1 and Flutter 1.20.2

**Comment by tryadelion** [comment] 2020-08-25 08:51
In android 7.1.1, Flutter 1.17.5, and pointing to android api-29, it works flawlessly.

**Comment by bwerere** [comment] 2020-08-26 08:03
I having exactly the same issue with android 7.0, flutter 1.20.2. Occassionally it will throw setState called after dispose() as I have indicated in this stackflow error. https://stackoverflow.com/questions/63592887/fluttererror-setstate-called-after-dispose-lifecycle-state-defunct-not. Downgrading to 1.7.5 will require a lot of changes I made after upgrading especially on Firestore (NOTE: https://firebase.flutter.dev/docs/migration which was recently updated).

**Comment by denonzhu** [comment] 2020-08-26 08:17
my app had same error,how to fix it

**Comment by GAURAV13803** [comment] 2020-08-31 07:42
how do i downgrade to specific version?

**Comment by matejkramny** [comment] 2020-08-31 07:48
> how do i downgrade to specific version?

https://lmgtfy.com/?q=downgrade+flutter+version

**Comment by bwerere** [comment] 2020-08-31 07:54
1. Download stable 1.7.5 from https://storage.googleapis.com/flutter_infra/releases/stable/windows/flutter_windows_1.17.5-stable.zip. 
2. Extract the file to your current Flutter folder - MAKE SURE to rename the current flutter folder to something else like flutter_1_20_2. 
3. Open your flutter editor of choice - I did this in VS Code. 
4. Issue the following command on your commad terminal on the project you are working on: 

```
flutter downgrade 
flutter version v1.17.5 
```
This should work and the issue will be resolved - worked on mine like Charm, note that you will update some of the deprecated methods (not many of them).

**Comment by xiaoliang943** [comment] 2020-08-31 09:30
Same problem, Android 7.1.1 on Nexus 6, Flutter 1.20.2.

**Comment by lgGuo** [comment] 2020-09-02 02:34
Same problem, Android 7.1.1 on  Flutter 1.20.2.

**Comment by lgGuo** [comment] 2020-09-02 02:45
> @esskar this does not seem to happen anymore so I guess the issue can be closed

it still happens on flutter 1.20.2 stable channel  on android 7.1.1

**Comment by bwerere** [comment] 2020-09-02 05:34
This issue still exists. As has been noted, it is happening on stable
1.20.2 and android 7.0 or android 7.1.1. It should not be closed. Rye
workaround is to use stable 1.17.5. But that is not a permanent solution.

**Comment by ali-1989** [comment] 2020-09-02 06:19
I have this issue with Android 7 (real device). When will it be fixed?
I back to flutter 1.17.1

**Comment by tryadelion** [comment] 2020-09-02 06:38
@jmagman  any updates?

**Comment by HiIamAlanOu** [comment] 2020-09-02 07:37
It is happening on dev 1.21.0-9.0.pre and android 7.0 version.

**Comment by b055man** [comment] 2020-09-02 18:25
It looks like the fix is on its way - seen this https://github.com/flutter/flutter/issues/64414 ?

**Comment by wanchaijit** [comment] 2020-09-03 07:29
Change flutter to master branch

**Comment by b055man** [comment] 2020-09-04 18:40
It seems to be resolved in 1.20.3! 👍

**Comment by lgGuo** [comment] 2020-09-09 01:34
> It seems to be resolved in 1.20.3! 👍

nice,it did

**Comment by jmagman** [comment] 2020-09-10 20:51
Thanks for confirming, closing.

**Closed by jmagman** 2020-09-10 20:51 UTC
Labels: P4, a: debugging, customer: crowd, platform-android, severe: crash, tool

**Comment by juandozuna** [comment] 2021-03-16 12:49
I had a similar issue working in an app that had to handle a lot of backoground and when I brought it back to foreground all of the buttons stopped working, but in iOS only. 

```dart
class _VideoCallScreenState extends State<VideoCallScreen> with WidgetsBindingObserver
```
I fixed it by adding the `WidgetsBindingObserver` to the state class and then 

```dart
 @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      setState(() {});
			Provider.of<VideoCallStateProvider>(context, listen: false).updateDraggableBottomMargin();
    }
  }
```
I just called `setState` when ever the app was being resumed.
