### ISSUE TITLE
[Camera] Camera freezes on the last frame instead of taking photos from 0.9.0 onwards

### ISSUE THREAD

**Issue by HosseinYousefi** [flutter/flutter#89155] opened 2021-08-30 09:13 UTC
Camera freezes on the last frame instead of taking photos from 0.9.0 onwards. This doesn't happen in 0.8.1+7 and lower versions.

## Steps to Reproduce

1. Run the [official camera example](https://github.com/flutter/plugins/tree/master/packages/camera/camera/example) from flutter on an android device.
2. Take a photo!

**Expected results:** 

The photo to be taken!

**Actual results:** 

The preview screen freezes on the last frame.

<details>
  <summary>Logs</summary>

```
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on RMX1931 is available at: http://127.0.0.1:49208/4ewBM2cUis8=/
[  +81 ms] Activating Dart DevTools...
[ +969 ms] I/app.identi.app(22918): ProcessProfilingInfo new_methods=1805 is saved saved_to_disk=1 resolve_classes_delay=5000
[+1993 ms] D/ViewRootImpl(22918): enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=104.0, y[0]=2211.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=51243491, downTime=51243491, deviceId=2, source=0x1002, displayId=0 }
[        ] D/ViewRootImpl[MainActivity](22918): processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=104.0, y[0]=2211.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=51243491, downTime=51243491, deviceId=2, source=0x1002, displayId=0 }
[  +10 ms] D/ViewRootImpl[MainActivity](22918): dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=104.0, y[0]=2211.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=51243491, downTime=51243491, deviceId=2, source=0x1002, displayId=0 }
[  +68 ms] D/ViewRootImpl[MainActivity](22918): processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=104.0, y[0]=2211.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=51243568, downTime=51243491, deviceId=2, source=0x1002, displayId=0 }
[   +4 ms] D/ViewRootImpl[MainActivity](22918): dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=104.0, y[0]=2211.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=51243568, downTime=51243491, deviceId=2, source=0x1002, displayId=0 }
[  +40 ms] I/OplusCameraManagerGlobal(22918): setClientInfo, packageName: app.identi.app, uid: 10577, pid: 22918
[  +27 ms] I/chatty  (22918): uid=10577(app.identi.app) identical 4 lines
[   +1 ms] I/OplusCameraManagerGlobal(22918): setClientInfo, packageName: app.identi.app, uid: 10577, pid: 22918
[        ] E/libc    (22918): Access denied finding property "persist.vendor.camera.privapp.list"
[        ] I/OplusCameraManagerGlobal(22918): setClientInfo, packageName: app.identi.app, uid: 10577, pid: 22918
[        ] I/OplusCameraManagerGlobal(22918): setClientInfo, packageName: app.identi.app, uid: 10577, pid: 22918
[   +5 ms] W/app.identi.app(22918): type=1400 audit(0.0:117699): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=15408 scontext=u:r:untrusted_app:s0:c65,c258,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=app.identi.app
[ +192 ms] E/libc    (22918): Access denied finding property "vendor.camera.aux.packagelist"
[   +2 ms] E/libc    (22918): Access denied finding property "vendor.camera.aux.packagelist"
[  +13 ms] E/libc    (22918): Access denied finding property "vendor.camera.aux.packagelist"
[   +3 ms] W/CameraManagerGlobal(22918): ignore the torch status update of camera: 2
[        ] E/libc    (22918): Access denied finding property "vendor.camera.aux.packagelist"
[   +4 ms] W/CameraManagerGlobal(22918): ignore the torch status update of camera: 3
[  +20 ms] E/libc    (22918): Access denied finding property "vendor.camera.aux.packagelist"
[        ] W/CameraManagerGlobal(22918): ignore the torch status update of camera: 5
[  +20 ms] E/libc    (22918): Access denied finding property "vendor.camera.aux.packagelist"
[  +16 ms] W/CameraManagerGlobal(22918): ignore the torch status update of camera: 6
[  +17 ms] E/libc    (22918): Access denied finding property "vendor.camera.aux.packagelist"
[   +5 ms] W/CameraManagerGlobal(22918): ignore the torch status update of camera: 7
[   +6 ms] E/libc    (22918): Access denied finding property "vendor.camera.aux.packagelist"
[        ] W/CameraManagerGlobal(22918): ignore the torch status update of camera: 8
[        ] E/libc    (22918): Access denied finding property "vendor.camera.aux.packagelist"
[   +4 ms] W/CameraManagerGlobal(22918): ignore the torch status update of camera: 9
[  +97 ms] I/Camera  (22918): startPreview
[  +23 ms] I/Camera  (22918): Updating builder settings
[        ] D/Camera  (22918): Updating builder with feature: ExposureLockFeature
[        ] D/Camera  (22918): Updating builder with feature: ExposurePointFeature
[        ] D/Camera  (22918): Updating builder with feature: ZoomLevelFeature
[        ] D/Camera  (22918): Updating builder with feature: AutoFocusFeature
[   +3 ms] D/Camera  (22918): Updating builder with feature: NoiseReductionFeature
[   +3 ms] I/Camera  (22918): updateNoiseReduction | currentSetting: fast
[   +3 ms] D/Camera  (22918): Updating builder with feature: FocusPointFeature
[        ] D/Camera  (22918): Updating builder with feature: ResolutionFeature
[        ] D/Camera  (22918): Updating builder with feature: SensorOrientationFeature
[        ] D/Camera  (22918): Updating builder with feature: FlashFeature
[   +3 ms] D/OplusCamera2StatisticsManager(22918): addInfo, eventMap: {halLevel=3, cameraId=0, pkgName=app.identi.app, connentTime=1630314422746, apLevel=2}
[   +3 ms] D/Camera  (22918): Updating builder with feature: ExposureOffsetFeature
[   +2 ms] D/Camera  (22918): Updating builder with feature: FpsRangeFeature
[   +8 ms] W/OplusStatistics--(22918): startDcsService Exception: java.lang.SecurityException: Not allowed to start service Intent { cmp=com.nearme.statistics.rom/.service.ReceiverService (has extras) } without permission oppo.permission.OPPO_COMPONENT_SAFE
[ +167 ms] E/libEGL  (22918): Invalid file path for libcolorx-loader.so
[ +902 ms] Activating Dart DevTools... (completed in 4.6s)
[ +545 ms] The Flutter DevTools debugger and profiler on RMX1931 is available at: http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A49208%2F4ewBM2cUis8%3D%2F
[+1006 ms] D/ViewRootImpl(22918): enqueueInputEventMotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=148.0, y[0]=1946.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=51246731, downTime=51246731, deviceId=2, source=0x1002, displayId=0 }
[   +7 ms] D/ViewRootImpl[MainActivity](22918): processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=148.0, y[0]=1946.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=51246731, downTime=51246731, deviceId=2, source=0x1002, displayId=0 }
[   +7 ms] D/ViewRootImpl[MainActivity](22918): dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=148.0, y[0]=1946.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=51246731, downTime=51246731, deviceId=2, source=0x1002, displayId=0 }
[  +62 ms] D/ViewRootImpl[MainActivity](22918): processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=148.0, y[0]=1946.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=51246809, downTime=51246731, deviceId=2, source=0x1002, displayId=0 }
[   +5 ms] D/ViewRootImpl[MainActivity](22918): dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=148.0, y[0]=1946.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=51246809, downTime=51246731, deviceId=2, source=0x1002, displayId=0 }
[   +9 ms] I/Camera  (22918): runPictureAutoFocus
[   +4 ms] I/Camera  (22918): lockAutoFocus
[        ] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[  +22 ms] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[  +20 ms] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[  +19 ms] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[  +13 ms] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[  +12 ms] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[  +34 ms] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 2 | aeState: 2
[   +5 ms] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_WAITING_FOCUS | afState: 4 | aeState: 2
[   +4 ms] I/Camera  (22918): captureStillPicture
[   +3 ms] D/Camera  (22918): Updating builder with feature: ExposureLockFeature
[   +4 ms] D/Camera  (22918): Updating builder with feature: ExposurePointFeature
[   +5 ms] D/Camera  (22918): Updating builder with feature: ZoomLevelFeature
[   +6 ms] D/Camera  (22918): Updating builder with feature: AutoFocusFeature
[        ] D/Camera  (22918): Updating builder with feature: NoiseReductionFeature
[        ] I/Camera  (22918): updateNoiseReduction | currentSetting: fast
[        ] D/Camera  (22918): Updating builder with feature: FocusPointFeature
[        ] D/Camera  (22918): Updating builder with feature: ResolutionFeature
[        ] D/Camera  (22918): Updating builder with feature: SensorOrientationFeature
[        ] D/Camera  (22918): Updating builder with feature: FlashFeature
[        ] D/Camera  (22918): Updating builder with feature: ExposureOffsetFeature
[        ] D/Camera  (22918): Updating builder with feature: FpsRangeFeature
[  +31 ms] I/Camera  (22918): sending capture request
[  +38 ms] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_CAPTURING | afState: 2 | aeState: 2
[   +2 ms] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_CAPTURING | afState: 4 | aeState: 2
[   +3 ms] D/CameraCaptureCallback(22918): CameraCaptureCallback | state: STATE_CAPTURING | afState: null | aeState: null
[+7207 ms] Application finished.
[   +2 ms] executing: /Users/hossein/Library/Android/sdk/platform-tools/adb -s cdc8fcab forward --list
[   +7 ms] Exit code 0 from: /Users/hossein/Library/Android/sdk/platform-tools/adb -s cdc8fcab forward --list
[        ] cdc8fcab tcp:49203 tcp:42665
[   +1 ms] executing: /Users/hossein/Library/Android/sdk/platform-tools/adb -s cdc8fcab forward --remove tcp:49203
```

```
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.15.7 19H1030 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/hossein/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/hossein/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0
```

</details>

**Comment by michaelsof47** [comment] 2021-08-31 04:31
is there camera 0.9.2+1 is resolved about front camera problem in android 11? because i got a problem with freeze in android 11 front camera

**Comment by danagbemava-nc** [comment] 2021-08-31 11:33
@HosseinYousefi @michaelsof47, I am unable to reproduce the issue using `camera: ^0.9.2+1` and `stable 2.2.3`. 
Can you please provide more information with regards to the issue that you are facing? 

See attached video
[video.mp4.zip](https://github.com/flutter/flutter/files/7083520/video.mp4.zip)


Thank you.

**Comment by michaelsof47** [comment] 2021-09-03 19:38
i was try in android nougat. it was work well in front camera. but, i was decided if it doesn't work only android 11 samsung galaxy A21s

**Comment by danagbemava-nc** [comment] 2021-09-08 06:22
@michaelsof47, can you show the behaviour that you experience when you use the front camera?

**Comment by TahaTesser** [comment] 2021-09-29 11:49
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-29 11:49 UTC
