### ISSUE TITLE
[google_maps_flutter] iOS BUILD FAILED  "userData not found on object of type GMSPolyline "

### ISSUE THREAD

**Issue by niypoo** [flutter/flutter#65102] opened 2020-09-02 15:59 UTC
I have an app working with  "google_maps_flutter" and I have  update it to last version "^0.5.31" then I run my app as usual then I'm facing this issue.

```

    2020-09-02 17:48:39.657 xcodebuild[92555:333603] warning:  The file reference for "GoogleMaps.debug.xcconfig" is a member of multiple groups ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    2020-09-02 17:48:39.657 xcodebuild[92555:333603] warning:  The file reference for "GoogleMaps.release.xcconfig" is a member of multiple groups ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    ** BUILD FAILED **
Xcode's output:
↳
    Command MergeSwiftModule failed with a nonzero exit code
    /Users/mahmoudnabhan/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.31/ios/Classes/GoogleMapPolylineController.m:20:15: error: property 'userData' not found on object of type 'GMSPolyline *'
        _polyline.userData = @[ polylineId ];
                  ^
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
Could not build the precompiled application for the device.

```

I'm trying every thing I know `flutter clean & upgrade pub & pod deintegrate and remove podfiles` no one worked.
I have tried on stable and master channel and build on VSCode and Xcode same issue.

imported it in AppDelegate.swift

```
import UIKit
import Flutter
import GoogleMaps
import Firebase
import FBSDKCoreKit
import TwitterKit
```

what can I do.

**Comment by hamdikahloun** [comment] 2020-09-02 16:41
Hi @niypoo 

Have you added this to AppDelegate.swift :

```
import UIKit
import Flutter
import GoogleMaps

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GMSServices.provideAPIKey("YOUR KEY HERE")
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist file with the key io.flutter.embedded_views_preview and the value YES.

You can found more details here: https://pub.dev/packages/google_maps_flutter

**Comment by niypoo** [comment] 2020-09-02 16:53
> Hi @niypoo
> 
> Have you added this to AppDelegate.swift :
> 
> ```
> import UIKit
> import Flutter
> import GoogleMaps
> 
> @UIApplicationMain
> @objc class AppDelegate: FlutterAppDelegate {
>   override func application(
>     _ application: UIApplication,
>     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
>   ) -> Bool {
>     GMSServices.provideAPIKey("YOUR KEY HERE")
>     GeneratedPluginRegistrant.register(with: self)
>     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
>   }
> }
> ```
> 
> Opt-in to the embedded views preview by adding a boolean property to the app's Info.plist file with the key io.flutter.embedded_views_preview and the value YES.
> 
> You can found more details here:
> 
> https://pub.dev/packages/google_maps_flutter
> 
> https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter/example

Yes I did 
` Info.plis`
```
<key>io.flutter.embedded_views_preview</key>
<true/>
```

AppDelegate.swift

```

import UIKit
import Flutter
import GoogleMaps
import Firebase
import FBSDKCoreKit
import TwitterKit

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GMSServices.provideAPIKey("xxxxx-xxxxxx")
    FirebaseApp.configure()
    GeneratedPluginRegistrant.register(with: self)
   
    //FCM configration
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }

    return super.application(application, didFinishLaunchingWithOptions: launchOptions) // YES;
  }

```

**Comment by hamdikahloun** [comment] 2020-09-02 17:02
Can you provide please:

- `flutter doctor -v`

- `flutter run -v`

**Comment by niypoo** [comment] 2020-09-02 18:33
> Try please with the example from Github : https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter/example and provide :
> 
> * `flutter doctor -v`
> * `flutter run -v`
> 
> Thank you

I appreciate you!
I have created new project and copy the iOS to the app that has this issue and replace info and it's work but I don't know what is missing , but the important thing my app is working again

**Comment by shubh-151411** [comment] 2020-09-09 05:40
i am still getting error after doing all things

**Comment by dospringer** [comment] 2020-09-16 14:24
Same here, I get the error last week.

**Comment by dospringer** [comment] 2020-09-16 14:26
flutter doctor -v 
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-DE)
    • Flutter version 1.20.4 at /Users/username/Code/DevTools/flutter/flutter
    • Framework revision fba99f6cf9 (2 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 25141AC3-AAC6-40F7-9948-925115A3E44E • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!

**Comment by niypoo** [comment] 2020-09-29 13:45
unfortunately I'm facing this issue again !!,
and replace IOS Folder not enough to solved this issue !

<img width="1404" alt="Screen Shot 2020-09-29 at 3 33 58 PM" src="https://user-images.githubusercontent.com/13227239/94565528-9e902300-0269-11eb-96d9-96ff6c2be15d.png">

this log after run `flutter run -v`


```


Volumes/SSD/Library/Developer/Xcode/DerivedData/Runner-hbwgtmuucrblfxcosrrvkozijoez/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/google_maps_flutter.build/Obj
                   ects-normal/arm64/GoogleMapPolygonController.o
               While building module 'GoogleMaps' imported from
               /Users/mahmoudnabhan/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.33/ios/Classes/GoogleMapPolygonController.h:6:
               In file included from <module-includes>:1:
               In file included from /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GoogleMaps.h:56:
               In file included from /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacePicker.h:11:
               In file included from /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacePickerConfig.h:12:
               In file included from /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesClient.h:15:
               /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:28:14: warning: expected quoted string after
equals sign
               [-Wdocumentation]
                  * <a href=https://developers.google.com/places/support">community and support page</a>.
                           ~^
               /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:28:19: warning: HTML start tag prematurely
ended,
               expected attribute name or '>' [-Wdocumentation]
                  * <a href=https://developers.google.com/places/support">community and support page</a>.
                                 ^
               /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:35:14: warning: expected quoted string after
equals sign
               [-Wdocumentation]
                  * <a href=https://developers.google.com/places/support">community and support page</a>.
                           ~^
               /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:35:19: warning: HTML start tag prematurely
ended,
               expected attribute name or '>' [-Wdocumentation]
                  * <a href=https://developers.google.com/places/support">community and support page</a>.
                                 ^
               /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:64:4: warning: HTML start tag prematurely
ended,
               expected attribute name or '>' [-Wdocumentation]
                  * href="https://developers.google.com/places/ios-api/usage">usage limits guide</a> for more
                  ^
               /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:63:63: note: HTML tag started here
                  * the API that far exceeds normal request levels. See the <a
                                                                             ^
               /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:73:4: warning: HTML start tag prematurely
ended,
               expected attribute name or '>' [-Wdocumentation]
                  * href="https://developers.google.com/places/ios-api/usage">usage limits guide</a> for more
                  ^
               /Volumes/SSD/Projects/flutter/owlist3/ios/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GMSPlacesErrors.h:72:63: note: HTML tag started here
                  * the API that far exceeds normal request levels. See the <a
                                                                             ^
               6 warnings generated.
               /Users/mahmoudnabhan/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.33/ios/Classes/GoogleMapPolygonController.m:20:14: error: property 'userData' not
found on
               object of type 'GMSPolygon *'
                   _polygon.userData = @[ polygonId ];
                            ^
               6 warnings and 1 error generated.
           
           
[ +133 ms] Could not build the precompiled application for the device.
[  +17 ms] Error launching application on Mahmoud’s iPhone.
[   +9 ms] "flutter run" took 87,423ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +264 ms] ensureAnalyticsSent: 254ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[        ] exiting with code 1


```

**Comment by niypoo** [comment] 2020-09-29 13:46
I have tried everything I know
```
flutter clean
pod deintegrate
pod install
remove /pod/ & pod.file & pod.log
```

**Comment by niypoo** [comment] 2020-09-29 13:46
```

Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (2 weeks ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2

```

**Comment by niypoo** [comment] 2020-09-29 13:56
After I removed the ` google_maps_flutter` package from pubspec.yaml and a project it's return work again !!

**Comment by dospringer** [comment] 2020-09-29 17:30
Remove google_maps_flutter didn't work for me

**Comment by niypoo** [comment] 2020-09-29 17:53
> Remove google_maps_flutter didn't work for me

what is error that show !?

**Comment by dospringer** [comment] 2020-09-29 18:27
Same as you 
error: property 'userData' not found on object of type 'GMSCircle *' _circle.userData = @[ circleId ];

**Comment by darshankawar** [comment] 2020-09-30 06:37
@niypoo 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.
Also, the latest plugin version is ^0.5.33, so if you aren't using the latest version, please upgrade to latest and see if you still get the issue.
Thanks.

**Comment by dospringer** [comment] 2020-10-08 20:18
Thanks for your answer! Yes I think that have fix the issue, but I don't know what was the exactly problem, after I have recreated the iOS folder, it finally works, but I have do this step 10 or more this.

**Comment by niypoo** [comment] 2020-10-08 20:40
> Thanks for your answer! Yes I think that have fix the issue, but I don't know what was the exactly problem, after I have recreated the iOS folder, it finally works, but I have do this step 10 or more this.

Yes , I have noticed it's appearing when I do pod update/install , I don't catch the reason but I have backed-up the iOS folder in case this issue appeared again.

and it's not related with` google_maps_flutter ` I guessed that.

**Comment by darshankawar** [comment] 2020-10-09 06:41
@niypoo 
Does that mean your issue is resolved ? If it's not related to the plugin and you still seeing the issue consistently, please provide detailed steps to replicate the issue along with `flutter doctor -v`.
Thanks.

**Comment by niypoo** [comment] 2020-10-09 07:29
yes I guess it's not related , but only plugin that name was mentioned in debug console `google_maps_flutter` and I can't know the reason , but I have fixed also by replace whole IOS folder.. no clear resolve

**Comment by darshankawar** [comment] 2020-10-09 07:57
@niypoo Thanks for getting back.
I'd suggest to keep an eye on the error again if you see it consistently along with a pattern to it if any.
I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-10-09 07:57 UTC
Labels: in triage

**Comment by niypoo** [comment] 2020-10-11 21:53
it's appear when I did `pod update`

**Comment by hamdikahloun** [comment] 2020-10-11 21:59
Hi @niypoo 
Can you create a GitHub repository with the iOS folder and minimal complete reproducible code sample.
Thank you

**Comment by niypoo** [comment] 2020-10-11 22:20
okay I will

**Comment by TranPhuHung98** [comment] 2020-11-30 03:17
I'm facing this issue and I need to use google maps. Did anyone solve this?

**Comment by yuva-dev** [comment] 2021-01-02 12:29
Still facing this issue 🤯🤯🤯

**Comment by yuva-dev** [comment] 2021-01-02 13:01
@niypoo I have finally solved this issue. I believe this does not have direct correlation with `google_maps_flutter` package

## steps to reproduce
Running `pod update` after a flutter SDK upgrade.

## Potential fix (In my case)
1. Ran `pod repo update` as per the instruction on the screen, 
2. after which I again faced a build error only this time asking me to run `pod update Firebase/Messaging`

That's it. Problem was fixed.

**Comment by pinkizpunk** [comment] 2021-01-03 08:25
Cool.

**Comment by niypoo** [comment] 2021-01-05 23:49
> @niypoo I have finally solved this issue. I believe this does not have direct correlation with `google_maps_flutter` package
> 
> 
> 
> ## steps to reproduce
> 
> Running `pod update` after a flutter SDK upgrade.
> 
> 
> 
> ## Potential fix (In my case)
> 
> 1. Ran `pod repo update` as per the instruction on the screen, 
> 
> 2. after which I again faced a build error only this time asking me to run `pod update Firebase/Messaging`
> 
> 
> 
> That's it. Problem was fixed.
> 
> 

Do you using any package google-place-picker ?

**Comment by yuva-dev** [comment] 2021-01-06 01:40
Yes

**Comment by niypoo** [comment] 2021-01-06 01:46
> Yes

Yes i guss that , this package is that is casing this issue appear. If you face this issue again display this package and try.

**Comment by sperochon** [comment] 2021-03-24 19:31
I had the same problem (using the package google_places_picker too).

It appears that the Google Maps pod installed is the 1.13.2 (no userData on GMSPolyline into this version -> so the compilation error).

Here is my solution:
1) edit the file Podfile to force to use the version 3.9.0 of GoogleMaps lib:
```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  pod 'GoogleMaps', '3.9.0'
end
```

2) delete Podfile.lock
3) launch the app :-)

**Comment by tomadimitrie** [comment] 2021-04-13 10:54
Any fix for this? Still getting this in the latest version

**Comment by yuva-dev** [comment] 2021-05-05 10:48
I was facing this issue again today after I ran `pod update`. I was also using [google_places_picker](https://pub.dev/packages/google_places_picker)

## Possible Workaround
So I did the following steps and the problem seems to be fixed.

1. Remove `google_places_picker` from the `pubspec.yaml` file. 
_(I m planning to reimplement the features provided by that library by myself directly using `Google API`s. Anyways the plugin does not even work in web.)_
2. Remove all the dart libraries in `<Flutter installation folder>/flutter/.pub-cache/hosted/pub.dartlang.org/`
3. Remove `Pods` file
4. Remove `Podfile.lock`
5. Now compile it for iOS.

I have also filed an issue with the plugin developers regarding the same.
