### ISSUE TITLE
Keep scroll position when appending new items to list view

### ISSUE THREAD

**Issue by dere-app** [flutter/flutter#63946] opened 2020-08-17 11:29 UTC
Hi,

I'm creating a list view that loads new items as the user scrolls. If new items are added while you're holding the scroll position up past the last item, all new items are added above the current position instead of below. It looks like the scroll position is being maintained relative to the bottom and not the top when using **BouncingScrollPhysics()**.

Thanks

**Expected results:**
<img src="https://user-images.githubusercontent.com/65984124/90389934-600c2380-e082-11ea-9189-6d6d73897935.jpg" width="300px" height="auto"> <img src="https://user-images.githubusercontent.com/65984124/90390233-e9235a80-e082-11ea-841c-7647056766f3.jpg" width="300px" height="auto">

**Actual results:**
<img src="https://user-images.githubusercontent.com/65984124/90389934-600c2380-e082-11ea-9189-6d6d73897935.jpg" width="300px" height="auto"> <img src="https://user-images.githubusercontent.com/65984124/90390000-803be280-e082-11ea-8624-190ad98dc444.jpg" width="300px" height="auto">

## Source Code

```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'List View Issue',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyListView(),
    );
  }
}

class MyListView extends StatefulWidget {
  MyListView({Key key}) : super(key: key);
  @override
  _MyListViewState createState() => _MyListViewState();
}

class _MyListViewState extends State<MyListView> {

  bool _loading;
  List<int> _items = [];
  final int _batchSize = 20;
  ScrollController _scrollController;

  @override
  void initState() {
    super.initState();
    _loading = false;
    _items = List.generate(_batchSize, (index) => index);
    _scrollController = ScrollController()..addListener(_onScroll);
  }

  void _onScroll() {
    if(!_loading) {
      final double threshold = 1.0;
      final ScrollPosition position = _scrollController.position;
      if(position.userScrollDirection == ScrollDirection.reverse) {
        if(position.extentAfter < threshold) {
          _load();
        }
      }
    }
  }

  void _load() {
    setState(() {
      _loading = true;
    });
    Future.delayed(
      Duration(seconds: 3),
      () {
        final items = List.generate(_batchSize, (index) => _items.length + index);
        _items.addAll(items);
        setState(() => _loading = false);
      }
    );
  }

  Widget _itemBuilder(BuildContext context, int index) {
    if(index == _items.length) {
      if(!_loading) {
        return SizedBox.shrink();
      }
      return Center(
        child: Container(
          width: 50.0,
          height: 50.0,
          padding: const EdgeInsets.all(10.0),
          child: CircularProgressIndicator(),
        ),
      );
    }
    return Container(
      color: index < _batchSize
        ? Colors.white
        : Color(0xFFF4F4F4),
      child: ListTile(
        title: Text('Item $index'),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        controller: _scrollController,
        physics: AlwaysScrollableScrollPhysics(
          parent: BouncingScrollPhysics(),
        ),
        itemCount: _items.length + (_loading ? 1 : 0),
        itemBuilder: _itemBuilder,
      ),
    );
  }
}

```

<details>
  <summary>Logs</summary>

```
```

```
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0 at /Users/taha/flutter
    • Framework revision 840c9205b3 (12 days ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2020-08-18 09:34
Hi  @dere-app 
Tried on latest `stable`, working as expected results, items are below 

![untitled](https://user-images.githubusercontent.com/48603081/90496898-0a0fac80-e164-11ea-9aeb-a4c33a665990.gif)


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.2 at C:\Code\flutter_stable
    • Framework revision bbfbf1770c (5 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

**Comment by venisei** [comment] 2020-08-18 23:37
Hi Taha,

Thanks for your comment.

The issue arrises when you scroll up from the bottom and continue to hold the screen in place without lifting your finger. In the first image I've shared you'll see that there's extra space below the loading indicator, that's because I am holding the scroll position up past the last element until the new items are loaded.

**Comment by dere-app** [comment] 2020-08-18 23:38
Hi Taha,

Thanks for your comment.

The issue arrises when you scroll up from the bottom and continue to hold the screen in place without lifting your finger. In the first image I've shared you'll see that there's extra space below the loading indicator, that's because I am holding the scroll position up past the last element until the new items are loaded.

**Comment by TahaTesser** [comment] 2020-08-19 08:17
Thanks @dere-app 
I can reproduce on `dev` channel too, updated https://github.com/flutter/flutter/issues/63946#issuecomment-675373080

**Comment by cadinz** [comment] 2020-09-22 11:04
Do you have any updates?
I have same issue..

**Comment by cadinz** [comment] 2021-01-14 02:27
class CustomBouncingScrollPhysics extends ScrollPhysics {
  
  const CustomBouncingScrollPhysics({ScrollPhysics parent}) : super(parent: parent);

  @override
  CustomBouncingScrollPhysics applyTo(ScrollPhysics ancestor) {
    return CustomBouncingScrollPhysics(parent: buildParent(ancestor));
  }

  double frictionFactor(double overscrollFraction) => 0.52 * pow(1 - overscrollFraction, 2);

  @override
  double applyPhysicsToUserOffset(ScrollMetrics position, double offset) {
    assert(offset != 0.0);
    assert(position.minScrollExtent <= position.maxScrollExtent);

    if (!position.outOfRange) return offset;

    final double overscrollPastStart = max(position.minScrollExtent - position.pixels, 0.0);
    final double overscrollPastEnd = max(position.pixels - position.maxScrollExtent, 0.0);
    final double overscrollPast = max(overscrollPastStart, overscrollPastEnd);
    final bool easing = (overscrollPastStart > 0.0 && offset < 0.0) || (overscrollPastEnd > 0.0 && offset > 0.0);

    final double friction = easing
        ? frictionFactor((overscrollPast - offset.abs()) / position.viewportDimension)
        : frictionFactor(overscrollPast / position.viewportDimension);
    final double direction = offset.sign;

    return direction * _applyFriction(overscrollPast, offset.abs(), friction);
  }

  static double _applyFriction(double extentOutside, double absDelta, double gamma) {
    assert(absDelta > 0);
    double total = 0.0;
    if (extentOutside > 0) {
      final double deltaToLimit = extentOutside / gamma;
      if (absDelta < deltaToLimit) return absDelta * gamma;
      total += extentOutside;
      absDelta -= deltaToLimit;
    }
    return total + absDelta;
  }

  @override
  double applyBoundaryConditions(ScrollMetrics position, double value) {
    return 0.0;
  }

  @override
  Simulation createBallisticSimulation(ScrollMetrics position, double velocity) {
    final Tolerance tolerance = this.tolerance;

    if (velocity.abs() >= tolerance.velocity || position.outOfRange) {
      return BouncingScrollSimulation(
        spring: spring,
        position: position.pixels,
        velocity: velocity,
        leadingExtent: position.minScrollExtent,
        trailingExtent: position.maxScrollExtent,
        tolerance: tolerance,
      );
    }

    return null;
  }

  @override
  double get minFlingVelocity => kMinFlingVelocity * 2.0;

  @override
  double carriedMomentum(double existingVelocity) {
    return existingVelocity.sign * min(0.000816 * pow(existingVelocity.abs(), 1.967).toDouble(), 40000.0);
  }

  @override
  bool recommendDeferredLoading(double velocity, ScrollMetrics metrics, BuildContext context) {
    return super.recommendDeferredLoading(velocity, metrics, context);
  }

  @override
  double adjustPositionForNewDimensions(
      {@required ScrollMetrics oldPosition,
      @required ScrollMetrics newPosition,
      @required bool isScrolling,
      @required double velocity}) {
    if (oldPosition.extentAfter == 0 && newPosition.extentAfter != 0) {
      if (oldPosition.extentInside != newPosition.extentInside) {
        return super.adjustPositionForNewDimensions(
            oldPosition: oldPosition,
            newPosition: FixedScrollMetrics(
              viewportDimension: oldPosition.viewportDimension,
              pixels: newPosition.extentBefore,
              minScrollExtent: oldPosition.minScrollExtent,
              maxScrollExtent: oldPosition.maxScrollExtent,
              axisDirection: oldPosition.axisDirection,
            ),
            isScrolling: isScrolling,
            velocity: velocity);
      }
    }
    return super.adjustPositionForNewDimensions(
        oldPosition: oldPosition, newPosition: newPosition, isScrolling: isScrolling, velocity: velocity);
  }

  @override
  double get dragStartDistanceMotionThreshold => 3.5;
}

Try this customPhysics!

**Comment by red282** [comment] 2021-07-23 06:23
It's likely the same as #62890.

**Comment by VNAPNIC** [comment] 2021-11-11 06:54
try it
https://pub.dev/packages/scroll_two

**Comment by nt4f04uNd** [comment] 2021-11-11 14:08
@TahaTesser I feel like this is a duplicate of https://github.com/flutter/flutter/issues/62890

**Comment by nt4f04uNd** [comment] 2021-12-16 22:06
Closing per my previous comment.

**Closed by nt4f04uNd** 2021-12-16 22:06 UTC
Labels: framework, f: scrolling, a: quality, has reproducible steps, found in release: 1.20, found in release: 1.21

**Comment by PaulBout1** [comment] 2021-12-23 17:36
Add `physics: const AllwaysScrollableFixedPositionScrollPhysics(),` to your `CustomScrollView`

if the user is at the edge of the list, new items be scrolled to automatically


    import 'package:flutter/material.dart';
    
    class AllwaysScrollableFixedPositionScrollPhysics extends ScrollPhysics {
      /// Creates scroll physics that always lets the user scroll.
      const AllwaysScrollableFixedPositionScrollPhysics({ScrollPhysics? parent})
          : super(parent: parent);
    
      @override
      AllwaysScrollableFixedPositionScrollPhysics applyTo(ScrollPhysics? ancestor) {
        return AllwaysScrollableFixedPositionScrollPhysics(parent: buildParent(ancestor));
      }
    
      @override
      double adjustPositionForNewDimensions({
        required ScrollMetrics oldPosition,
        required ScrollMetrics newPosition,
        required bool isScrolling,
        required double velocity,
      }) {
        if (newPosition.extentBefore == 0) {
          return super.adjustPositionForNewDimensions(
            oldPosition: oldPosition,
            newPosition: newPosition,
            isScrolling: isScrolling,
            velocity: velocity,
          );
        }
        return newPosition.maxScrollExtent - oldPosition.extentAfter;
      }
    
      @override
      bool shouldAcceptUserOffset(ScrollMetrics position) => true;
    }
