### ISSUE TITLE
dispose methods are not being executed when exiting app on Desktop (Windows)

### ISSUE THREAD

**Issue by busslina** [flutter/flutter#140760] opened 2023-12-31 11:47 UTC
I close the app using `exit(0)`.

Also, is this the correct way to close the app?

**Comment by stuartmorgan** [comment] 2023-12-31 13:48
This is [the documented behavior](https://github.com/flutter/flutter/blob/3df4e735d5d0bd2db7930098eba1b3e620d77aa0/packages/flutter/lib/src/widgets/framework.dart#L1306-L1326)

Closing as a duplicate of https://github.com/flutter/flutter/issues/40940

**Closed by stuartmorgan** 2023-12-31 13:48 UTC
