### ISSUE TITLE
Large portion of unicode blocks do not display with canvas kit web-renderer

### ISSUE THREAD

**Issue by mrcsh** [flutter/flutter#87765] opened 2021-08-06 00:35 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: lib/main.dart
3. flutter build web --web-renderer html (renders all characters correctly as far as I can tell)
4. flutter build web --web-renderer canvaskit (renders a few characters correctly)

**Expected results: see attached image

**Actual results:**  see attached image 
<details>
  <summary>Logs</summary>

[unicode-render.zip](https://github.com/flutter/flutter/files/6942288/unicode-render.zip)

```
> flutter analyze 
Analyzing unicode_tester...                                             
No issues found! (ran in 1.2s)
```

```
 flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /server/home/csh/lib/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/csh/Android/Sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /usr/lib/jvm/java-1.8.0/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_292-fastdebug-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 12.0.0 (Fedora 12.0.0-2.fc34)
    • cmake version 3.20.5
    • ninja version 1.8.2
    • pkg-config version 1.7.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).

[✓] VS Code (version 1.58.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (7 available)
    • G5 (mobile)                           • 7080018019007106 • android-arm64  • Android 9 (API 28)
    • moto x4 (mobile)                      • ZY224KQLWQ       • android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 (mobile)    • emulator-5554    • android-x86    • Android 10 (API 29)
      (emulator)
    • Android SDK built for x86 64 (mobile) • emulator-5556    • android-x64    • Android 9 (API 28)
      (emulator)
    • sdk gphone64 x86 64 (mobile)          • emulator-5558    • android-x64    • Android 11 (API 30)
      (emulator)
    • Linux (desktop)                       • linux            • linux-x64      • Linux
    • Chrome (web)                          • chrome           • web-javascript • Google Chrome
      91.0.4472.164

! Doctor found issues in 1 category.

```

</details>

**Comment by mrcsh** [comment] 2021-08-06 00:50
Oh and I am using chrome.

```
Google Chrome | 91.0.4472.164 (Official Build) (64-bit)
-- | --
Revision | 541163496c9982c98f61819bab7cf2183ea8180f-refs/branch-heads/4472@{#1569}
OS | Linux
JavaScript | V8 9.1.269.39
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=SecurePaymentConfirmation
Executable Path | /opt/google/chrome/google-chrome
```

**Comment by TahaTesser** [comment] 2021-08-06 12:25
Hi @mrcsh 
Thanks for filing the issue
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/77465
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-06 12:25 UTC
Labels: in triage
