### ISSUE TITLE
3d touch of Chinese keyboard behave oddly

### ISSUE THREAD

**Issue by zzzs123** [flutter/flutter#54413] opened 2020-04-10 02:28 UTC
it works fine if you use an English keyboard. But if you use a Chinese keyboard, it's hard to use 3d touch to move the cursor. And after move the cursor using 3d touch, touch the textfield relocate the cursor, then type in some words, there will be two cursors in the textfield.

**Comment by VladyslavBondarenko** [comment] 2020-04-13 09:54
Hi @zzzs123 
could you please provide your `flutter doctor -v` and screen recording of reproducing?

**Comment by kongo2002** [comment] 2020-04-22 15:52
Hi @VladyslavBondarenko 

I have basically the same problem as described by @zzzs123 but just with a normal english keyboard. That's why I thought I just pitch in some of my findings.

For me the issue always happens if I use the 3D touch longpress *without actually moving the cursor*. As soon as I release the press, the cursor will get stuck on the current position and I basically end up with two cursors being visible. I hope the screen recording ([recording.tar.gz](https://github.com/flutter/flutter/files/4517226/recording.tar.gz)) makes that visible enough.

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-DE)
    • Flutter version 1.12.13+hotfix.9 at /Users/.../programs/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/.../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 4DC3B729-9167-4998-80F5-B1BD12762B68 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

If you think this is not related to this specific issue, I can open a dedicated one instead.

Cheers,
Gregor

**Comment by zzzs123** [comment] 2020-04-23 03:09
> Hi @zzzs123
> could you please provide your `flutter doctor -v` and screen recording of reproducing?

➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E287,
    locale en-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/qxu0668/development/flutter
    • Framework revision 0b8abb4724 (2 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/qxu0668/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/qxu0668/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.


[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Users/qxu0668/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

**Comment by VladyslavBondarenko** [comment] 2020-04-23 07:43
Yes, it seems to be not specific to the language,
@kongo2002 , @zzzs123 
Please follow up on https://github.com/flutter/flutter/issues/47610,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-04-23 07:43 UTC
