### ISSUE TITLE
Sometimes the ColorScheme generated by ColorScheme.fromSeed has the same color for different color role

### ISSUE THREAD

**Issue by brandon3343** [flutter/flutter#149954] opened 2024-06-08 10:12 UTC
### Steps to reproduce

1.download sample project.
2.unzip and run ```flutter pub get```.
3.run app.

### Expected results

ColorScheme generated by ColorScheme.fromSeed should has the difference color for different color role.

### Actual results

Sometimes the ColorScheme generated by ColorScheme.fromSeed has the same color for different color role.

There are actually a few other color that can cause this, but I've only recorded two.

### Code sample

[flutter_theme_issue.zip](https://github.com/user-attachments/files/15747500/flutter_theme_issue.zip)

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![11111111](https://github.com/flutter/flutter/assets/17621099/adec03d9-fd58-4d92-9240-ed7475355a9d)
![222222222222](https://github.com/flutter/flutter/assets/17621099/ef746bea-160e-471e-b9a4-d33c638d2b70)

</details>

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.22.2, on Microsoft Windows [版本 10.0.22631.3672], locale zh-CN)
    • Flutter version 3.22.2 on channel stable at D:\scoop\apps\flutter\current
    ! Warning: `flutter` on your path resolves to D:\scoop\apps\flutter\3.22.2\bin\flutter, which is not inside your
      current Flutter SDK checkout at D:\scoop\apps\flutter\current. Consider adding D:\scoop\apps\flutter\current\bin
      to the front of your path.
    ! Warning: `dart` on your path resolves to D:\scoop\apps\flutter\3.22.2\bin\dart, which is not inside your current
      Flutter SDK checkout at D:\scoop\apps\flutter\current. Consider adding D:\scoop\apps\flutter\current\bin to the
      front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 days ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.0)
    • Visual Studio at D:\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34916.146
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.3)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2023.3.2
    • Flutter plugin version 80.0.2
    • Dart plugin version 241.17502

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.3672]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.142
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.85

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by huycozy** [comment] 2024-06-10 10:05
Thanks for your report. I can see `primaryContainer` and `secondaryContainer` roles are the same in the sample code. I copied the main sample code here so others can easily take a look at it for reproduction. 

<details>
<summary>Sample code (from the given compressed project)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'color scheme issue',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'color scheme issue'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  // 0xE3195243    surface == surfaceBright
  // 0xE35E310D    surface == surfaceBright and primaryContainer == secondaryContainer
  final Color _seedColor1 = const Color(0xE3195243);
  final Color _seedColor2 = const Color(0xE35E310D);
  late Color _currentSeedColor;
  late ColorScheme _colorScheme;

  @override
  void initState() {
    super.initState();
    _genColorScheme(_seedColor1);
  }

  void _genColorScheme(Color color) {
    setState(() {
      _currentSeedColor = color;
      _colorScheme = ColorScheme.fromSeed(seedColor: _currentSeedColor);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.purple,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: [
            ColorBox(
              color: _colorScheme.surface,
              colorRole: "surface",
            ),
            ColorBox(
              color: _colorScheme.surfaceBright,
              colorRole: "surfaceBright",
            ),
            ColorBox(
              color: _colorScheme.primaryContainer,
              colorRole: "primaryContainer",
            ),
            ColorBox(
              color: _colorScheme.secondaryContainer,
              colorRole: "secondaryContainer",
            ),
            Text(
              "current seedColor: $_currentSeedColor",
              style: TextStyle(
                color: _currentSeedColor,
                fontSize: 18.0,
                fontWeight: FontWeight.bold,
              ),
            ),
            FilledButton(
              onPressed: () => _genColorScheme(_seedColor1),
              child: Text("seedColor: $_seedColor1"),
            ),
            const SizedBox(height: 8.0),
            FilledButton(
              onPressed: () => _genColorScheme(_seedColor2),
              child: Text("seedColor: $_seedColor2"),
            ),
          ],
        ),
      ),
    );
  }
}

class ColorBox extends StatelessWidget {
  const ColorBox({
    super.key,
    required this.color,
    required this.colorRole,
  });

  final Color color;
  final String colorRole;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 300,
      height: 50,
      color: color,
      child: Text("$color -> $colorRole"),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (31 hours ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.23.0-13.0.pre.168, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-13.0.pre.168 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 32081aab69 (34 hours ago), 2024-06-08 10:35:21 -0700
    • Engine revision 1cdbebee19
    • Dart version 3.5.0 (build 3.5.0-236.0.dev)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 2B171FDH20084L                           • android-arm64  • Android 14 (API 34)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by Piinks** [comment] 2024-06-12 17:54
The color scheme is generated by the algorithm in https://pub.dev/packages/material_color_utilities, which is maintained by the material team and matches the specification. Unique colors per role is not always expected as the algorithm often has to take into account ensuring contrast guidelines are met etc. Since we do not control this, I am going to close this issue.

**Closed by Piinks** 2024-06-12 17:54 UTC
Labels: framework, f: material design, has reproducible steps, team-design, found in release: 3.22, found in release: 3.23
