### ISSUE TITLE
Cursor can't go within "ff" ligature in the GoogleFonts.anton font

### ISSUE THREAD

**Issue by felix-mittermeier** [flutter/flutter#110767] opened 2022-09-01 08:24 UTC
(**edit:** See updates starting at https://github.com/flutter/flutter/issues/110767#issuecomment-1249647582 .)

See https://github.com/flutter/flutter/issues/110767#issuecomment-1239265848 for samples and recordings

**Comment by danagbemava-nc** [comment] 2022-09-01 11:33
Hi @felix-mittermeier, it would appear that this has been fixed on the `master` channel as I can reproduce this on stable but not on `master`. See the recordings below. 

Can you confirm whether or not this reproduces for you on the `master` channel?

<details>
<summary>recordings</summary>

| stable | master | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/187903912-834988ab-cfca-4df4-b60a-5945ad98c452.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/187903845-125babf7-dcd4-49aa-881d-e0efe9d7dfb3.mov" /> | 

</details>

**Comment by danagbemava-nc** [comment] 2022-09-02 08:33
Hi @felix-mittermeier, I seem to be able to position the cursor between the two "f" in `aaaffaaa`. 
See the recording below

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/188098709-3be3af8b-55b1-4b0b-a270-fcae940a7f3d.mp4
</details>

**Comment by felix-mittermeier** [comment] 2022-09-06 15:51
Hi @danagbemava-nc ,
I'm sorry for the delayed response. I now just did a minimal reproducible example so it's easier for you to understand, uploaded the project here: https://github.com/felix-mittermeier/cursor_demo

Recording: 


https://user-images.githubusercontent.com/100692288/188680001-e7486c08-7f4b-4871-a48f-d7e3cbc9c15b.MP4

**Comment by danagbemava-nc** [comment] 2022-09-07 07:45
Hi @felix-mittermeier, thanks for the repro. I see what you mean now. 

Given that it doesn't throw the exception on master, I feel we should update the title to a more generic one that accurately describes the main issue at hand. Can you suggest a new title that will accurately capture the issue?

**Comment by felix-mittermeier** [comment] 2022-09-07 07:59
@danagbemava-nc Yeah that's actually a good point, I will change the title to match the issue more precisely 👍🏻

**Comment by danagbemava-nc** [comment] 2022-09-07 11:27
Thanks for updating the title. 

Labeling for further investigation. 

<details>
<summary>recordings</summary>

| flutter 2.10.5 | current stable & master | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/188867092-f7585221-b501-4872-ae27-c0a9845d6fa4.mp4" /> | <video src="https://user-images.githubusercontent.com/88313112/188867124-0e51f900-7fb9-4f38-b0bb-d4fb48aef1b8.mp4" /> |

</details>


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Demo to showcase cursor bug (ff)'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(50.0),
          child: TextField(
            style: GoogleFonts.anton(),
          ),
        ),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel unknown, 2.10.5, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter_rc/flutter
    • Upstream repository unknown
    • Framework revision 5464c5bac7 (5 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-arm, locale en-GB)
    • Flutter version 3.3.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (8 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.104, on macOS 12.5 21G72 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-19.0.pre.104 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 29eb478743 (5 hours ago), 2022-09-07 01:55:18 -0400
    • Engine revision 2eba5a7485
    • Dart version 2.19.0 (build 2.19.0-171.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 6E074BA5-191C-47D4-892F-FD96AFC34148 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.5 21G72 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by jmagman** [comment] 2022-09-07 17:30
Duplicate of https://github.com/flutter/flutter/issues/109632

**Comment by felix-mittermeier** [comment] 2022-09-07 20:57
> Duplicate of #109632

I don't understand why this has been closed and why this would be the fix for it? If this would solve it, it should work on the master branch but as written and explained in detail by me and @danagbemava-nc it doesn't.

**Comment by jmagman** [comment] 2022-09-07 23:19
I see this now:
> Given that it doesn't throw the exception on master, I feel we should update the title to a more generic one that accurately describes the main issue at hand. Can you suggest a new title that will accurately capture the issue?

This is really confusing, the title was changed but the description is the exception that was fixed in https://github.com/flutter/flutter/issues/109632, and I had to read 6+ comments to get to the actual bug this is now tracking.
Can you file a new issue with all the information tracking the cursor positioning issue, the minimal repro case, doctor output, etc to make it easier to see what engineers should actually be tracking down?  You can copy what's already in all those comments.

**Comment by felix-mittermeier** [comment] 2022-09-08 07:54
> I see this now:
> 
> > Given that it doesn't throw the exception on master, I feel we should update the title to a more generic one that accurately describes the main issue at hand. Can you suggest a new title that will accurately capture the issue?
> 
> This is really confusing, the title was changed but the description is the exception that was fixed in #109632, and I had to read 6+ comments to get to the actual bug this is now tracking. Can you file a new issue with all the information tracking the cursor positioning issue, the minimal repro case, doctor output, etc to make it easier to see what engineers should actually be tracking down? You can copy what's already in all those comments.

I get your point but I think there is no need to create everything new. I edit the description to directly link the comment which contains all relevant information.

**Comment by chinmaygarde** [comment] 2022-09-12 17:44
cc @jason-simmons

**Comment by justinmc** [comment] 2022-09-16 17:56
This doesn't seem to be related to the floating cursor.  Even the arrow keys on desktop will skip over two adjacent f's!

<img width="250" src="https://user-images.githubusercontent.com/389558/190702050-03938f7a-8ac9-4809-bf22-bd1d6e27e057.gif" />

Could this be something wrong with this specific font?  I only see this happen for the letter "f".  I tried a few other narrow characters and didn't see the problem (`t`, `l`, `i`, `|`, etc.).

Can anyone reproduce this bug with a character other than f or a different font?

**Comment by chinmaygarde** [comment] 2022-09-16 19:00
I believe the font treats the double "f" as a ligature ([reference](https://en.wikipedia.org/wiki/Ligature_(writing))). At least when using the SkParagraph backend (I can't tell if the old backend did the same), we seem to be iterating over ligatures instead of graphemes. If we can confirm the regressions and behavior, we should bring this up with the Skia folks working on typography.

**Comment by jason-simmons** [comment] 2022-09-16 21:23
Confirmed that positioning within ligatures is not working as expected in SkParagraph's `TextLine::getGlyphPositionAtCoordinate`

This was working previously (see https://bugs.chromium.org/p/skia/issues/detail?id=9850) but has regressed.

I will reopen the bug in Skia and work with the SkParagraph team on a fix.

**Comment by gnprice** [comment] 2023-03-12 04:04
Retitled and relabeled based on https://github.com/flutter/flutter/issues/110767#issuecomment-1249647582 . I also added a link to that comment in the issue description.

**Comment by jason-simmons** [comment] 2023-03-12 16:40
Skia has landed a fix that has rolled into the master branch (https://skia.googlesource.com/skia/+/9a98174e5c50e5e50cabb335b00fa9f9bb886775)

**Comment by justinmc** [comment] 2023-03-22 17:54
Confirmed that this works on master now!  Closing.

https://user-images.githubusercontent.com/389558/226994762-3cfaa26e-39d9-4901-aca3-63b6d8999854.mov

**Closed by justinmc** 2023-03-22 17:54 UTC
Labels: a: text input, severe: regression, engine, a: typography, has reproducible steps, P4, found in release: 3.3, found in release: 3.4
