### ISSUE TITLE
Automatic configuration and unnecessarily early start of Firebase plugins

### ISSUE THREAD

**Issue by cohortor** [flutter/flutter#39207] opened 2019-08-25 10:18 UTC
ISSUE: Flutter does not support manual/delayed configuration of the default `FirebaseApp`.

COROLLARY: Firebase plugins (and dependent google services) get started way before the first frame is displayed on screen, unnecessarily increasing the time it takes to show the first flutter frame/widget.

DISCUSSION: Firebase on Android supports disabling the auto-configure and auto-start "feature" (IMHO a bug, not convenience) by disabling the `com.google.firebase.provider.FirebaseInitProvider` from `AndroidManifest.xml`. At any point later in the app, `FirebaseApp.initializeApp()` can be used with a dynamically populated list of options using `FirebaseOptions.Builder()` to set up the default FirebaseApp instance.

While Flutter's firebase_core's `FirebaseApp` also seems to have a static `configure()` method, its `name` field (required) can't be equal to `FirebaseApp.defaultAppName`. The API docs for `configure()` do say this is not supported, but fail to indicate why. At the same time, most of the Firebase plugins (as of today) work only with the default FirebaseApp configuration, and do not support other named configurations.

WORKAROUND: Disable Firebase auto-initialization in AndroidManifest, add platform-specific (Android) code to the app's Activity that calls `FirebaseApp.initializeApp()`, then call this java code using a `MethodChannel` from flutter _after_ e.g. a splash screen has already been displayed on the device.

PROPOSED SOLUTION:
1. Provide support for initialization of the default firebase_core/FirebaseApp,
2. Document how one can disable the whole auto-starting shebang of google services.

**Comment by Levi-Lesches** [comment] 2019-08-25 19:39
Just curious, what would be an example of wanting to delay Firebase? From my use cases, my apps need Firebase data (usually authentication) to draw the first frame.

**Comment by VladyslavBondarenko** [comment] 2020-01-14 13:46
Hi @cohortor 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Comment by Levi-Lesches** [comment] 2020-01-14 15:01
If a nice-looking first frame is all you want, then maybe look into a native splash screen?

**Comment by cohortor** [comment] 2020-01-14 15:43
@VladyslavBondarenko thank you for considering this as a firebase proposal.

@Levi-Lesches no, a "nice-looking first frame" is not "all I want". First and foremost I would like to avoid the automatic initialization of google services, of which I (and my users) have no use of whatsoever (e.g. analytics), or no use until much later than startup during an app's lifecycle (e.g. firestore connection in my case). Just the same, as you should want too, if you cared about your users' privacy and convenience at all.

**Comment by stuartmorgan** [comment] 2021-06-15 15:28
As this is specific to the firebase plugins, which have moved to https://github.com/FirebaseExtended/flutterfire/issues, this will need to be filed there.

**Closed by stuartmorgan** 2021-06-15 15:28 UTC
Labels: p: firebase, plugin, proposal
