### ISSUE TITLE
[Canvaskit][Web] Large images do not appear with `WebGL: INVALID_VALUE: texImage2D: width or height out of range`

### ISSUE THREAD

**Issue by guidotheelen** [flutter/flutter#114679] opened 2022-11-04 10:02 UTC
## Steps to Reproduce

1. Try to display the following large image in an `Image` widget:

(This file is large enough to crash on my machine. Depending on your hardware this could crash with smaller files)

![large](https://user-images.githubusercontent.com/9211107/199940976-571cee4e-7281-45d9-a557-d10691013707.jpg)

**Expected results:** Display the image correctly, or throw an error.

**Actual results:** The picture is displayed with white pixels only. Browser displays the following alert:
```
WebGL: INVALID_VALUE: texImage2D: width or height out of range
```

**Browser details**: MacOS - Chrome Version 106.0.5249.119 (Official Build) (x86_64)

<details>
<summary>Code sample</summary>

```dart
   Widget _image() => Image(
       fit: BoxFit.fill,
       image: widget.image,
       frameBuilder: (_, child, __, ___) {
         return Container(
           child: child,
         );
       },
       errorBuilder: (_, error, __) {
         return const SizedBox();
       },
     );
```

</details>

<details>
  <summary>Logs</summary>

flutter analyze:

```
No issues found!
```

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.5.1 21G83 darwin-x64,
    locale en-NL)
    • Flutter version 3.3.7 on channel stable at
      /Users/guidotheelen/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (2 days ago), 2022-11-01 16:59:00
      -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.8+10-b944.6916264)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome
      107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

Displayed image: 

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/9211107/199944930-095ac1d4-cbc1-41e1-b2d6-b0b21435fc33.png">

**Comment by guidotheelen** [comment] 2022-11-04 10:24
This image is scaled down by GitHub. You can find the full image here: https://drive.google.com/file/d/1ELvklxsPGDkyJGH-chAFwB3Oyo3SErFr/view?usp=sharing

**Comment by exaby73** [comment] 2022-11-04 12:05
Hello @guidotheelen. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by guidotheelen** [comment] 2022-11-07 07:06
<details><summary>flutter run -v</summary>
<p>

#### Does not show anything special

```
[        ] 💪 Running with sound null safety 💪
[   +4 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at:
           http://127.0.0.1:54080/htU7H0VypCM=
[  +26 ms] Flutter Web Bootstrap: Programmatic
[ +883 ms] The Flutter DevTools debugger and profiler on Chrome is available at:
                    http://127.0.0.1:9103?uri=http://127.0.0.1:54080/htU7H0VypCM=
```

</p>
</details>

**Comment by guidotheelen** [comment] 2022-11-07 07:06
<details><summary>main.dart</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Image.asset('large.jpg'),
      ),
    );
  }
}
```

</p>
</details>

**Comment by guidotheelen** [comment] 2022-11-07 07:08
The only visible warning in the browser is: `⚠️  WebGL: INVALID_VALUE: texImage2D: width or height out of range`

**Comment by guidotheelen** [comment] 2022-11-07 07:13
I suspect the app is reaching the browser limit, but there is no error thrown by Flutter. This makes it difficult to deal with this problem. Throwing an error would be a nice first step, but ideally I would like to display these large images.

**Comment by exaby73** [comment] 2022-11-07 08:43
## Triage report

I can reproduce this issue on the latest `Master (3.5.0-12.0.pre.142)`. The following is the warning I got from the Chrome devtools' console:

<details>
<summary>Console logs</summary>

```console
WebGL: INVALID_VALUE: texImage2D: width or height out of range
makeTexture	@	canvaskit.js:22
(anonymous)	@	canvaskit.js:230
$	@	canvaskit.js:229
$func9559	@	canvaskit.wasm:0x47d622
$func5140	@	canvaskit.wasm:0x2d24c5
$func10373	@	canvaskit.wasm:0x4a7fc3
$func904	@	canvaskit.wasm:0x47f93
$func3074	@	canvaskit.wasm:0x174c02
$func3073	@	canvaskit.wasm:0x174b7c
$func9140	@	canvaskit.wasm:0x46b408
$func7808	@	canvaskit.wasm:0x3f8560
$func1073	@	canvaskit.wasm:0x5a692
$func2402	@	canvaskit.wasm:0x10ca0b
$func3192	@	canvaskit.wasm:0x18d570
$func10093	@	canvaskit.wasm:0x49bb1b
$func7624	@	canvaskit.wasm:0x3ee0df
$func1280	@	canvaskit.wasm:0x72a48
$func11141	@	canvaskit.wasm:0x4d47ec
$func962	@	canvaskit.wasm:0x4d05a
(anonymous)	@	canvaskit.js:181
a.Canvas.drawPicture	@	canvaskit.js:51
_callMethodUnchecked1	@	js_util_patch.dart:106
SkCanvasExtension$124drawPicture	@	canvaskit_api.dart:1799
drawPicture	@	canvas.dart:214
paint	@	layer.dart:467
paintChildren	@	layer.dart:141
paint	@	layer.dart:368
paintChildren	@	layer.dart:141
paint	@	layer.dart:368
paintChildren	@	layer.dart:141
paint	@	layer.dart:368
paintChildren	@	layer.dart:141
paint	@	layer.dart:154
paint	@	layer_tree.dart:54
(anonymous)	@	layer_tree.dart:97
timeAction	@	profiler.dart:34
raster	@	layer_tree.dart:96
draw	@	rasterizer.dart:33
renderScene	@	renderer.dart:349
render	@	platform_dispatcher.dart:645
render	@	window.dart:107
compositeFrame	@	view.dart:235
drawFrame	@	binding.dart:520
drawFrame	@	binding.dart:869
[_handlePersistentFrameCallback]	@	binding.dart:381
[_invokeFrameCallback]	@	binding.dart:1289
handleDrawFrame	@	binding.dart:1218
[_handleDrawFrame]	@	binding.dart:1076
invoke	@	platform_dispatcher.dart:1153
invokeOnDrawFrame	@	platform_dispatcher.dart:218
(anonymous)	@	initialization.dart:190
_checkAndCall	@	operations.dart:352
dcall	@	operations.dart:357
ret	@	js_patch.dart:414
requestAnimationFrame (async)
callMethod$	@	js_util_patch.dart:81
DomWindowExtension$124requestAnimationFrame	@	dom.dart:53
(anonymous)	@	initialization.dart:160
scheduleFrame	@	platform_dispatcher.dart:616
scheduleFrame	@	binding.dart:871
ensureVisualUpdate	@	binding.dart:824
[_handleBuildScheduled]	@	binding.dart:756
scheduleBuildFor	@	framework.dart:2566
markNeedsBuild	@	framework.dart:4651
setState	@	framework.dart:1153
[_handleImageFrame]	@	image.dart:1156
setImage	@	image_stream.dart:655
[_emitFrame]	@	image_stream.dart:998
_decodeNextFrameAndSchedule	@	image_stream.dart:977
(anonymous)	@	async_patch.dart:45
runUnary	@	zone.dart:1660
handleValue	@	future_impl.dart:147
handleValueCallback	@	future_impl.dart:767
_propagateToListeners	@	future_impl.dart:796
[_completeWithValue]	@	future_impl.dart:567
(anonymous)	@	future_impl.dart:640
_microtaskLoop	@	schedule_microtask.dart:40
_startMicrotaskLoop	@	schedule_microtask.dart:49
(anonymous)	@	async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise	@	async_patch.dart:164
_scheduleImmediate	@	async_patch.dart:136
_scheduleAsyncCallback	@	schedule_microtask.dart:69
_rootScheduleMicrotask	@	zone.dart:1465
scheduleMicrotask	@	zone.dart:1680
[_asyncCompleteWithValue]	@	future_impl.dart:639
[_asyncComplete]	@	future_impl.dart:599
complete	@	future_impl.dart:36
(anonymous)	@	js_util_patch.dart:352
Promise.then (async)
promiseToFuture	@	js_util_patch.dart:364
promiseToFuture$	@	safe_browser_api.dart:64
getNextFrame	@	image_web_codecs.dart:215
(anonymous)	@	async_patch.dart:45
runUnary	@	zone.dart:1660
handleValue	@	future_impl.dart:147
handleValueCallback	@	future_impl.dart:767
_propagateToListeners	@	future_impl.dart:796
[_completeWithValue]	@	future_impl.dart:567
(anonymous)	@	future_impl.dart:640
_microtaskLoop	@	schedule_microtask.dart:40
_startMicrotaskLoop	@	schedule_microtask.dart:49
(anonymous)	@	async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise	@	async_patch.dart:164
_scheduleImmediate	@	async_patch.dart:136
_scheduleAsyncCallback	@	schedule_microtask.dart:69
_rootScheduleMicrotask	@	zone.dart:1465
scheduleMicrotask	@	zone.dart:1680
[_asyncCompleteWithValue]	@	future_impl.dart:639
[_asyncComplete]	@	future_impl.dart:599
complete	@	future_impl.dart:36
(anonymous)	@	js_util_patch.dart:352
Promise.then (async)
promiseToFuture	@	js_util_patch.dart:364
promiseToFuture$	@	safe_browser_api.dart:64
_getOrCreateWebDecoder	@	image_web_codecs.dart:171
(anonymous)	@	async_patch.dart:45
runUnary	@	zone.dart:1660
handleValue	@	future_impl.dart:147
handleValueCallback	@	future_impl.dart:767
_propagateToListeners	@	future_impl.dart:796
[_completeWithValue]	@	future_impl.dart:567
(anonymous)	@	future_impl.dart:640
_microtaskLoop	@	schedule_microtask.dart:40
_startMicrotaskLoop	@	schedule_microtask.dart:49
(anonymous)	@	async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise	@	async_patch.dart:164
_scheduleImmediate	@	async_patch.dart:136
_scheduleAsyncCallback	@	schedule_microtask.dart:69
_rootScheduleMicrotask	@	zone.dart:1465
scheduleMicrotask	@	zone.dart:1680
[_asyncCompleteWithValue]	@	future_impl.dart:639
[_asyncComplete]	@	future_impl.dart:599
complete	@	future_impl.dart:36
(anonymous)	@	js_util_patch.dart:352
Promise.then (async)
promiseToFuture	@	js_util_patch.dart:364
promiseToFuture$	@	safe_browser_api.dart:64
_getOrCreateWebDecoder	@	image_web_codecs.dart:165
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
[_getOrCreateWebDecoder]	@	image_web_codecs.dart:134
create	@	image_web_codecs.dart:76
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
create	@	image_web_codecs.dart:43
skiaInstantiateImageCodec	@	image.dart:15
instantiateImageCodec	@	renderer.dart:181
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
instantiateImageCodec	@	renderer.dart:176
instantiateImageCodecFromBuffer	@	painting.dart:488
instantiateImageCodecFromBuffer	@	binding.dart:153
_loadAsync	@	image_provider.dart:740
(anonymous)	@	async_patch.dart:45
runUnary	@	zone.dart:1660
handleValue	@	future_impl.dart:147
handleValueCallback	@	future_impl.dart:767
_propagateToListeners	@	future_impl.dart:796
[_completeWithValue]	@	future_impl.dart:567
(anonymous)	@	future_impl.dart:640
_microtaskLoop	@	schedule_microtask.dart:40
_startMicrotaskLoop	@	schedule_microtask.dart:49
(anonymous)	@	async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise	@	async_patch.dart:164
_scheduleImmediate	@	async_patch.dart:136
_scheduleAsyncCallback	@	schedule_microtask.dart:69
_rootScheduleMicrotask	@	zone.dart:1465
scheduleMicrotask	@	zone.dart:1680
[_asyncCompleteWithValue]	@	future_impl.dart:639
[_asyncComplete]	@	future_impl.dart:599
complete	@	future_impl.dart:36
(anonymous)	@	binding.dart:372
runUnaryGuarded	@	zone.dart:1593
(anonymous)	@	platform_dispatcher.dart:395
(anonymous)	@	platform_dispatcher.dart:1123
runUnary	@	zone.dart:1660
handleValue	@	future_impl.dart:147
handleValueCallback	@	future_impl.dart:767
_propagateToListeners	@	future_impl.dart:796
[_complete]	@	future_impl.dart:558
(anonymous)	@	future.dart:421
internalCallback	@	isolate_helper.dart:48
setTimeout (async)
_isolate_helper.TimerImpl.new	@	isolate_helper.dart:55
_createTimer	@	async_patch.dart:186
createTimer	@	zone.dart:1684
new	@	timer.dart:51
delayed	@	future.dart:419
replyToPlatformMessage	@	platform_dispatcher.dart:1121
(anonymous)	@	platform_dispatcher.dart:449
runUnary	@	zone.dart:1660
handleValue	@	future_impl.dart:147
handleValueCallback	@	future_impl.dart:767
_propagateToListeners	@	future_impl.dart:796
[_completeWithValue]	@	future_impl.dart:567
(anonymous)	@	future_impl.dart:640
_microtaskLoop	@	schedule_microtask.dart:40
_startMicrotaskLoop	@	schedule_microtask.dart:49
(anonymous)	@	async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise	@	async_patch.dart:164
_scheduleImmediate	@	async_patch.dart:136
_scheduleAsyncCallback	@	schedule_microtask.dart:69
_rootScheduleMicrotask	@	zone.dart:1465
scheduleMicrotask	@	zone.dart:1680
[_asyncCompleteWithValue]	@	future_impl.dart:639
[_asyncComplete]	@	future_impl.dart:599
complete	@	future_impl.dart:36
(anonymous)	@	dom.dart:773
_checkAndCall	@	operations.dart:352
dcall	@	operations.dart:357
ret	@	js_patch.dart:414
load (async)
callMethod$	@	js_util_patch.dart:81
DomEventTargetExtension$124addEventListener	@	dom.dart:151
domHttpRequest	@	dom.dart:766
load	@	assets.dart:68
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
load	@	assets.dart:64
[_sendPlatformMessage]	@	platform_dispatcher.dart:448
sendPlatformMessage	@	platform_dispatcher.dart:324
send	@	binding.dart:370
load	@	asset_bundle.dart:253
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
load	@	asset_bundle.dart:250
loadBuffer	@	asset_bundle.dart:266
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
loadBuffer	@	asset_bundle.dart:264
_loadAsync	@	image_provider.dart:731
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
[_loadAsync]	@	image_provider.dart:725
loadBuffer	@	image_provider.dart:695
(anonymous)	@	image_provider.dart:513
putIfAbsent	@	image_cache.dart:384
resolveStreamForKey	@	image_provider.dart:511
resolveStreamForKey	@	scroll_aware_image_provider.dart:106
(anonymous)	@	image_provider.dart:358
(anonymous)	@	image_provider.dart:473
runUnary	@	zone.dart:1660
handleValue	@	future_impl.dart:147
handleValueCallback	@	future_impl.dart:767
_propagateToListeners	@	future_impl.dart:796
[_completeWithValue]	@	future_impl.dart:567
(anonymous)	@	future_impl.dart:640
_microtaskLoop	@	schedule_microtask.dart:40
_startMicrotaskLoop	@	schedule_microtask.dart:49
(anonymous)	@	async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise	@	async_patch.dart:164
_scheduleImmediate	@	async_patch.dart:136
_scheduleAsyncCallback	@	schedule_microtask.dart:69
_rootScheduleMicrotask	@	zone.dart:1465
scheduleMicrotask	@	zone.dart:1680
[_asyncCompleteWithValue]	@	future_impl.dart:639
[_asyncComplete]	@	future_impl.dart:599
complete	@	future_impl.dart:36
(anonymous)	@	binding.dart:372
runUnaryGuarded	@	zone.dart:1593
(anonymous)	@	platform_dispatcher.dart:395
(anonymous)	@	platform_dispatcher.dart:1123
runUnary	@	zone.dart:1660
handleValue	@	future_impl.dart:147
handleValueCallback	@	future_impl.dart:767
_propagateToListeners	@	future_impl.dart:796
[_complete]	@	future_impl.dart:558
(anonymous)	@	future.dart:421
internalCallback	@	isolate_helper.dart:48
setTimeout (async)
_isolate_helper.TimerImpl.new	@	isolate_helper.dart:55
_createTimer	@	async_patch.dart:186
createTimer	@	zone.dart:1684
new	@	timer.dart:51
delayed	@	future.dart:419
replyToPlatformMessage	@	platform_dispatcher.dart:1121
(anonymous)	@	platform_dispatcher.dart:449
runUnary	@	zone.dart:1660
handleValue	@	future_impl.dart:147
handleValueCallback	@	future_impl.dart:767
_propagateToListeners	@	future_impl.dart:796
[_completeWithValue]	@	future_impl.dart:567
(anonymous)	@	future_impl.dart:640
_microtaskLoop	@	schedule_microtask.dart:40
_startMicrotaskLoop	@	schedule_microtask.dart:49
(anonymous)	@	async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise	@	async_patch.dart:164
_scheduleImmediate	@	async_patch.dart:136
_scheduleAsyncCallback	@	schedule_microtask.dart:69
_rootScheduleMicrotask	@	zone.dart:1465
scheduleMicrotask	@	zone.dart:1680
[_asyncCompleteWithValue]	@	future_impl.dart:639
[_asyncComplete]	@	future_impl.dart:599
complete	@	future_impl.dart:36
(anonymous)	@	dom.dart:773
_checkAndCall	@	operations.dart:352
dcall	@	operations.dart:357
ret	@	js_patch.dart:414
load (async)
callMethod$	@	js_util_patch.dart:81
DomEventTargetExtension$124addEventListener	@	dom.dart:151
domHttpRequest	@	dom.dart:766
load	@	assets.dart:68
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
load	@	assets.dart:64
[_sendPlatformMessage]	@	platform_dispatcher.dart:448
sendPlatformMessage	@	platform_dispatcher.dart:324
send	@	binding.dart:370
load	@	asset_bundle.dart:253
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
load	@	asset_bundle.dart:250
loadString	@	asset_bundle.dart:83
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
loadString	@	asset_bundle.dart:82
loadString	@	asset_bundle.dart:184
loadStructuredData	@	asset_bundle.dart:206
obtainKey	@	image_resolution.dart:287
obtainKey	@	scroll_aware_image_provider.dart:116
[_createErrorHandlerAndKey]	@	image_provider.dart:465
resolve	@	image_provider.dart:355
[_resolveImage]	@	image.dart:1119
didChangeDependencies	@	image.dart:1069
[_firstBuild]	@	framework.dart:5119
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
mount	@	framework.dart:6377
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
inflateWidget	@	framework.dart:6512
mount	@	framework.dart:6524
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
performRebuild	@	framework.dart:5133
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
[_firstBuild]	@	framework.dart:5124
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
performRebuild	@	framework.dart:5133
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
[_firstBuild]	@	framework.dart:5124
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
performRebuild	@	framework.dart:5133
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
[_firstBuild]	@	framework.dart:5124
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
mount	@	framework.dart:6377
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
mount	@	framework.dart:6377
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
performRebuild	@	framework.dart:5133
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
[_firstBuild]	@	framework.dart:5124
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
performRebuild	@	framework.dart:5133
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
[_firstBuild]	@	framework.dart:5124
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
performRebuild	@	framework.dart:5133
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
[_firstBuild]	@	framework.dart:5124
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
performRebuild	@	framework.dart:5133
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
[_firstBuild]	@	framework.dart:5124
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
mount	@	framework.dart:6377
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
mount	@	framework.dart:6377
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
mount	@	framework.dart:6377
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
performRebuild	@	framework.dart:5133
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
[_firstBuild]	@	framework.dart:5124
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
mount	@	framework.dart:6377
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
performRebuild	@	framework.dart:4993
performRebuild	@	framework.dart:5133
rebuild	@	framework.dart:4690
[_firstBuild]	@	framework.dart:4950
[_firstBuild]	@	framework.dart:5124
mount	@	framework.dart:4944
inflateWidget	@	framework.dart:3953
updateChild	@	framework.dart:3682
mount	@	framework.dart:6377
inflateWidget	@	framework.dart:3953
setTimeout (async)
_isolate_helper.TimerImpl.new	@	isolate_helper.dart:55
_createTimer	@	async_patch.dart:186
createTimer	@	zone.dart:1684
new	@	timer.dart:51
run	@	timer.dart:110
scheduleAttachRootWidget	@	binding.dart:909
(anonymous)	@	binding.dart:1022
runApp	@	binding.dart:1023
main$	@	main.dart:4
(anonymous)	@	web_entrypoint.dart:24
_checkAndCall	@	operations.dart:352
dcall	@	operations.dart:357
(anonymous)	@	initialization.dart:77
(anonymous)	@	async_patch.dart:45
runUnary	@	zone.dart:1660
handleValue	@	future_impl.dart:147
handleValueCallback	@	future_impl.dart:767
_propagateToListeners	@	future_impl.dart:796
[_completeWithValue]	@	future_impl.dart:567
(anonymous)	@	future_impl.dart:640
_microtaskLoop	@	schedule_microtask.dart:40
_startMicrotaskLoop	@	schedule_microtask.dart:49
(anonymous)	@	async_patch.dart:166
Promise.then (async)
_scheduleImmediateWithPromise	@	async_patch.dart:164
_scheduleImmediate	@	async_patch.dart:136
_scheduleAsyncCallback	@	schedule_microtask.dart:69
_rootScheduleMicrotask	@	zone.dart:1465
scheduleMicrotask	@	zone.dart:1680
[_asyncCompleteWithValue]	@	future_impl.dart:639
[_asyncComplete]	@	future_impl.dart:599
runBody	@	async_patch.dart:108
_async	@	async_patch.dart:123
initializeEngineUi	@	initialization.dart:212
(anonymous)	@	initialization.dart:75
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
(anonymous)	@	initialization.dart:71
_checkAndCall	@	operations.dart:352
callMethod	@	operations.dart:416
dsend	@	operations.dart:420
(anonymous)	@	app_bootstrap.dart:75
runBody	@	async_patch.dart:84
_async	@	async_patch.dart:123
(anonymous)	@	app_bootstrap.dart:73
_checkAndCall	@	operations.dart:352
dcall	@	operations.dart:357
ret	@	js_patch.dart:414
(anonymous)	@	app_bootstrap.dart:71
_checkAndCall	@	operations.dart:352
dcall	@	operations.dart:357
ret	@	js_patch.dart:414
(anonymous)	@	(index):53
Promise.then (async)
(anonymous)	@	(index):52
load (async)
(anonymous)	@	(index):44
```

</details>

**Comment by eyebrowsoffire** [comment] 2022-11-10 19:26
This is a duplicate of https://github.com/flutter/flutter/issues/105985

**Closed by eyebrowsoffire** 2022-11-10 19:26 UTC
Labels: severe: crash, engine, platform-web, a: images, e: web_canvaskit, has reproducible steps, assigned for triage, found in release: 3.3, found in release: 3.4
