### ISSUE TITLE
[regression on beta] double tapping to select text doesn't show toolbar and long hold in the textfield sometimes causes ghosting effect from toolbar 

### ISSUE THREAD

**Issue by Jethro87** [flutter/flutter#66149] opened 2020-09-18 22:38 UTC
## The issue
![Screen Recording 2020-09-18 at 3 29 10 PM](https://user-images.githubusercontent.com/6467808/93650641-f4d8a880-f9c3-11ea-8cb3-f8551a649c40.gif)

The clipboard control for Cut / Copy doesn't show up at all anymore. I am able to Select all, but I'm not able to Copy or Cut the selection in order to paste it. **Very rarely, it looks like the Cut/Copy clipboard tries to appear, as there is a black flash above the selected text.**

I've tested this on various iPhones running iOS 14 as well as in the Simulator (as shown in the gif), and with both CupertinoTextField and TextField. On all channels it is broken except for master - evidently, a fix has happened.

I managed to locate https://github.com/flutter/flutter/pull/63994 and https://github.com/flutter/flutter/issues/62658, and it appeared that the pull request fixed this issue. But, looking in the beta channel (where I normally work), I can confirm that the fix is in the code, yet the problem is still occurring. 

I've heard from numerous users that this feels broken and isn't at all what they expect on iOS. 

@justinmc  Can you point me to the direction of the fix in master, if possible, or escalate this somehow?

cc @GaryQian 

Much appreciated.

## Flutter doctor
```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-CA)
    • Flutter version 1.22.0-12.1.pre at /Users/jeffreybunn/flutter
    • Framework revision 8b3760638a (3 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jeffreybunn/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/jeffreybunn/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • iPhone 11 (mobile)                  • CE07B25B-6B99-43C6-9229-3BD43670BB7F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • iPhone SE (2nd generation) (mobile) • AC831EC5-14C0-4911-885F-AC428667B33D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)                    • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 85.0.4183.102
```

**Comment by TahaTesser** [comment] 2020-09-21 08:31
Hi @Jethro87 
I can reproduce the issue on the `stable`,`beta`, `dev` channels, the latest `master` channel has no issues


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Cupertino App',
      home: CupertinoPageScaffold(
        navigationBar: CupertinoNavigationBar(
          middle: Text('Cupertino App Bar'),
        ),
        child: Center(
          child: CupertinoTextField(),
        ),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.269, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.269 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 51fa704642 (2 days ago), 2020-09-19 11:27:04 -0700
    • Engine revision 4b8477d115
    • Dart version 2.10.0 (build 2.10.0-142.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[✓] Connected device (4 available)            
    • iPhone 11 (mobile) • 9A8EFBFE-A806-4FF9-ACA5-F3F98D94979D • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.102

• No issues found!
```

</details> 

We close issues that are fixed and closed issues are also taken for cherry-pick release. https://github.com/flutter/flutter/issues/64228#issuecomment-679337044

 I am editing the title for better visibility.

 I feel safe to close the issue. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Jethro87** [comment] 2020-09-22 06:06
Thanks, @TahaTesser, I appreciate your response. If there's any way to expedite this cherry-pick, I'd really appreciate it!

In any case, thanks again 👍

**Comment by pcsosinski** [comment] 2020-09-28 20:23
@TahaTesser i'm confused a bit by the issue - it looks it was fixed on master at some point, but if https://github.com/flutter/flutter/issues/64228#issuecomment-679337044 is the fix it would be fixed on beta/stable as well

**Comment by TahaTesser** [comment] 2020-09-29 13:25
Hi @pcsosinski 
I tried all the channels again, this issue now only exists on the `beta` channel, **I hope this issue doesn't land into the next `stable`, which would b really bad IMO.**,  `dev` channel is fixed now from last time I commented on the issue

I only mentioned https://github.com/flutter/flutter/issues/64228#issuecomment-679337044 to explain @Jethro87  that we cherry-pick closed issues if qualified, even tho this is fixed in later versions, we can close it 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Mac OS X 10.15.7 19H2, locale
    en-GB)
    • Flutter version 1.22.0-12.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 2bafdc8226 (4 days ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • 7E0D24D0-76BD-45A7-B84A-3E70FFAF4171 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.121

• No issues found!

```

</details>

**Comment by pcsosinski** [comment] 2020-09-29 14:11
@xster as fyi

I don't expect it to fix itself on the beta branch, so reopening this bug

**Comment by jmagman** [comment] 2020-09-29 18:03
Bisected, this was fixed with 0d945a1a56.

**Comment by jmagman** [comment] 2020-09-29 18:26
That commit has already been cherry-picked to the next beta candidate https://github.com/flutter/flutter/pull/66849 because of https://github.com/flutter/flutter/issues/66036.

**Comment by pcsosinski** [comment] 2020-09-29 18:41
thanks @jmagman!

**Closed by pcsosinski** 2020-09-29 18:41 UTC
Labels: a: text input, engine, found in release: 1.22, framework, has reproducible steps, severe: regression

**Comment by jmagman** [comment] 2020-09-29 20:09
Thanks @TahaTesser for the videos and such clear repro instructions, it made bisecting really easy!

**Comment by Jethro87** [comment] 2020-09-29 20:35
Thanks to everyone! Works great on the latest beta release.
