### ISSUE TITLE
`InkRipple` seems to overflow `IconButton` boundaries more than expected

### ISSUE THREAD

**Issue by Hawmex** [flutter/flutter#96100] opened 2022-01-04 08:10 UTC
## SDK Information
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (3 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

## So what's the issue?

As you can see in the following screenshots, `splash` unexpectedly overflows the `IconButton` if it's created by `InkRipple.splashFactory`.

#### Run the code below

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light().copyWith(
        splashFactory: InkRipple.splashFactory,
      ),
      home: Scaffold(
        body: Center(
          child: IconButton(onPressed: () {}, icon: const Icon(Icons.add)),
        ),
      ),
    );
  }
}
```

#### Result:

![Screenshot 2022-01-04 112314](https://user-images.githubusercontent.com/54506231/148028443-a5f8120d-3b57-4f8d-bba9-3e7d64a8f4cb.png)

#### Run the code below

```dart
import 'package:flutter/material.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light(),
      home: Scaffold(
        body: Center(
          child: IconButton(onPressed: () {}, icon: const Icon(Icons.add)),
        ),
      ),
    );
  }
}
```

#### Result
![Screenshot 2022-01-04 113128](https://user-images.githubusercontent.com/54506231/148028382-90a91dd5-b54f-487e-a3a3-47cdbd7dc8c6.png)

**Comment by xu-baolin** [comment] 2022-01-04 09:55
This is work as design,
https://github.com/flutter/flutter/blob/5257f0290cb7e11ab4946da6ee15104ceaa815f9/packages/flutter/lib/src/material/ink_ripple.dart#L84-L85

**Comment by Hawmex** [comment] 2022-01-04 10:04
@xu-baolin
But doesn't it look buggy when it expands more than its highlight? Shouldn't the highlight be the same size of the splash? I've never seen this behavior in production material apps.
**Note that this buggy behavior doesn't exist on `TextButton`, etc (Try the first reproduction code with `TextButton` instead of `IconButton`).**

**Comment by maheshmnj** [comment] 2022-01-04 11:08
I am able to reproduce the same behavior but this seems to be intended as mentioned in the [above comment.](https://github.com/flutter/flutter/issues/96100#issuecomment-1004667140). 

 Closing as working as intended.

**Closed by maheshmnj** 2022-01-04 11:08 UTC
Labels: in triage

**Comment by xu-baolin** [comment] 2022-01-04 11:35
> @xu-baolin But doesn't it look buggy when it expands more than its highlight? Shouldn't the highlight be the same size of the splash? I've never seen this behavior in production material apps. **Note that this buggy behavior doesn't exist on `TextButton`, etc (Try the first reproduction code with `TextButton` instead of `IconButton`).**

This is work as design, the `IconButton` has a default padding of `EdgeInsets.all(8.0)`, so it could not overflow the boundaries.

Also, you can custom the `IconButton.splashRadius` to change this behavior.

**Comment by xu-baolin** [comment] 2022-01-04 11:37
See also:
https://github.com/flutter/flutter/blob/5257f0290cb7e11ab4946da6ee15104ceaa815f9/packages/flutter/lib/src/material/icon_button.dart#L366-L370

**Comment by Hawmex** [comment] 2022-01-05 17:47
Ok seems to be not a bug. But it seems to be a strange decision in terms of design IMO.
