### ISSUE TITLE
formKey.currentState.reset() dont work after formKey.currentState.save()

### ISSUE THREAD

**Issue by amandeeptherockstar** [flutter/flutter#26621] opened 2019-01-16 05:01 UTC
All  want to do is clear the Inputs after form submission. Even if i get an error Inputs must reset to the default (empty). I am binding that inputs to variables using initialValue property of `TextFormField`.
Here is my code
```dart
  String email = '';
  String password = '';
  bool acceptTerms = false;

  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final GlobalKey<FormFieldState> _passwordKey = GlobalKey<FormFieldState>();

Widget _buildEmailField() {
    return TextFormField(
      keyboardType: TextInputType.emailAddress,
      initialValue: email,
      decoration: InputDecoration(
        labelText: 'Enter Email',
        filled: true,
        fillColor: Colors.white,
      ),
      validator: (String value) {
        if (value.isEmpty) {
          return 'Email is required';
        } else if (!RegExp(
                r'^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$')
            .hasMatch(value)) {
          return 'Invalid Email';
        }
      },
      onSaved: (String value) {
        setState(() {
          //_formData['email'] = value;
          email = value;
        });
      },
    );
  }

showDialog(
          context: context,
          builder: (BuildContext context) {
            return AlertDialog(
              title: Text('An Error Occurred'),
              content: Text(response['message']),
              actions: <Widget>[
                FlatButton(
                  child: Text('Okay!'),
                  onPressed: () {
                    Navigator.of(context).pop();
                    _passwordKey.currentState.reset();
                    _formKey.currentState.reset();
                    print('Callsss');
                  },
                ),
              ],
            );
          },
        );
```

**Comment by zoechi** [comment] 2019-01-16 07:35
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2019-01-16 07:36
Thanks for reporting. Can you please make the reproduction code self-containing and runnable so that copy-past to `lib/main.dart` is enough to run and reproduce.

**Comment by zoechi** [comment] 2019-02-12 07:53
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-02-12 07:53 UTC
Labels: a: text input, framework, waiting for customer response

**Comment by Alishgiri** [comment] 2020-04-26 15:38
For me setting initial value on the TextField was causing the issues, after I took care of initial value, reset started working.

**Comment by bismarabia** [comment] 2020-08-14 17:58
Is there a way to make the formKey.currentstate.reset() work with setting textEditingController.text? @zoechi 
Because it works perfect if we don't set textEditingController.text value.
