### ISSUE TITLE
"reply_outlined" material icon is solid instead of being outlined.

### ISSUE THREAD

**Issue by Pavel401** [flutter/flutter#113452] opened 2022-10-14 17:44 UTC
I am using Material icons in my app. All the outlined material icons are working fine except the "reply_outlined".It should display as an outlined icon instead of a solid icon.

**Reply Outlined Icon**
<img width="537" alt="Screenshot 2022-10-14 at 11 11 07 PM" src="https://user-images.githubusercontent.com/47685150/195908465-50c13d3a-bb6f-488c-8b16-51c527cd4b5b.png">

**thumbs up outlined icon**
<img width="611" alt="Screenshot 2022-10-14 at 11 12 32 PM" src="https://user-images.githubusercontent.com/47685150/195908652-bbbedb2e-4e55-4e3a-b175-c52bf0c8b43a.png">

If this is a bug then please assign me the issue.

**Comment by nitin-787** [comment] 2022-10-15 13:06
can you give me your repo link @Pavel401 ?

**Comment by nitin-787** [comment] 2022-10-15 13:22
> can you give me your repo link @Pavel401 ?

hey after my research I found that, this bug is coming from "material icon design" not from "flutter" @Pavel401

**Comment by danagbemava-nc** [comment] 2022-10-17 06:33
Hi @Pavel401, this is working according to the material icon design spec. See the recording below. 

https://user-images.githubusercontent.com/88313112/196104650-7607fa12-e0a1-46ed-9ee3-17fbca9fbcc5.mov

Closing this as it is working as intended. 

Thank you

**Closed by danagbemava-nc** 2022-10-17 06:33 UTC
Labels: in triage
