### ISSUE TITLE
ArrowCircleLeft/ArrowCircleRight Material icons not implemented in Flutter

### ISSUE THREAD

**Issue by simlf** [flutter/flutter#93383] opened 2021-11-10 09:58 UTC
Hello,

I want to display an IconButton with an Arrow Circle Left on my app.
I copied the Flutter ID from this [website](https://fonts.google.com/icons?selected=Material+Icons+Outlined:assignment_returned&icon.query=arrow+circle+left).

Here is my code :  
```
IconButton(
    color: COOKE_GREEN,
    onPressed: () {},
    icon: Icon(Icons.arrow_circle_left_outlined))
```

And the error message I get : `Error: Getter not found: 'arrow_circle_left_outlined'.`.

I have the exact same code for the Arrow Circle Up and Down and it works fine : 
```
IconButton(
    color: COOKE_GREEN,
    onPressed: () {},
    icon: Icon(Icons.arrow_circle_up_outlined))
```

It works with the up and  down Arrow Circle but not with the left and right.
Could you please help me figure out if this is a normal issue or is it a bug ?

**Comment by danagbemava-nc** [comment] 2021-11-10 11:19
Duplicate of #88852.

@simlf an umbrella issue has been created for all the missing materials icons in #88852. 

Kindly follow up there for more information

**Closed by danagbemava-nc** 2021-11-10 11:19 UTC
Labels: in triage
