### ISSUE TITLE
WebView for Flutter - support listen and reacting to URL changes

### ISSUE THREAD

**Issue by alsocalledchris** [flutter/flutter#27729] opened 2019-02-09 16:54 UTC
This looks possible but I can't work out the code to get it to work if it is - I want to listen to URL changes as the user interacts with the site - useful for OAuth login flows and reacting to redirects to custom URLs (e.g. at the end of the OAuth dance).

Is this possible via the current webViewController and currentUrl - I can't get it listen to the initialUrl but no subsequent url change.

**Comment by vanelizarov** [comment] 2019-02-10 04:55
@alsocalledchris as a temporary solution you can call `currentUrl()` every second and check if it contains needed query-params

**Comment by alsocalledchris** [comment] 2019-02-10 15:26
Thanks - I tried the work-around, would probably work in other scenarios but the URL needed is from a redirect which the widget does not call (presumable as it does not recognise the URL as it's a custom one)

**Comment by vanelizarov** [comment] 2019-02-10 20:56
I’ve faced the same issue while implementing oauth in my app. This plugin doesn’t allow me to redirect to URLs like `http://my-app`.
Solved by adding `blank.html` file to the root of my website and redirecting to it.

**Comment by SachaHerszkorn** [comment] 2019-05-17 15:18
Hi,

In my case, i want to display a floating action button depending on url.
I can't figure out a reactive way to check .currentUrl().
I tried to use flutter_webview_plugin because it has onUrlChange() but you can't overlay anything because the webview created with this package is in foreground.
Is there any way to achieve my goal other than just call .currentUrl() in a timeout method ?

**Comment by Sarthaktydy** [comment] 2019-05-21 07:35
There is a way if you know on what URL you need to put action button on, Through NavigationDelegate you can put a condition that when the user navigates to certain URL you change your view accordingly. Hope it helps and also take a look at onPageFinished method.

**Comment by SachaHerszkorn** [comment] 2019-05-21 08:32
@Sarthaktydy I'll try that thanks !

**Comment by tvarwig** [comment] 2019-08-20 16:23
I tried the above solution. I have an PWA/VueJS app that I am using that is not detecting the currentUrl change in NavigationDelegate. Only works if I have a real link change which reloads the entire page. I don't see any issues opened for url changes not working on PWA sites.

**Comment by Sarthaktydy** [comment] 2019-10-10 11:28
> I tried the above solution. I have an PWA/VueJS app that I am using that is not detecting the currentUrl change in NavigationDelegate. Only works if I have a real link change which reloads the entire page. I don't see any issues opened for url changes not working on PWA sites.

Webview has an issue reading URL that contains "#" inside it. Check if you have a similar test case.

**Comment by IonelLupu** [comment] 2019-11-19 11:21
Any update on this?

**Comment by wal33d006** [comment] 2019-12-23 14:52
Any update on this? It is really required

**Comment by rafazafar** [comment] 2020-02-06 17:50
This is super needed for flutter web to be flexible.

**Comment by deandreamatias** [comment] 2020-02-07 07:52
Please stop commenting on problems things like at:

> any update on this

The best option is to add this emoji :+1: in the initial comment.
To see a priority of each issue, we can see in which Milestone the issue is added. This issue belongs
to milestone Goals, with this description:

> P2: These are tasks we think are worth fixing in the coming years. It includes issues we've identified that might block fully shipping broad consumer-facing apps, correctness issues, and bugs relating to polish and quality. The date on this milestone is utterly arbitrary and just intended to sort the milestone appropriately.

Thank

**Comment by IonelLupu** [comment] 2020-02-07 12:12
@deandreamatias of course people should not comment on issues with messages like `any update on this` and only use emojis. But using emojis won't trigger a notification for the participants and thus the issue won't be seen.

Commenting is the only way to make the issue stand out. This is not a user issue. This is a platform issue. Users a just abusing it.

**Comment by KaiP-598** [comment] 2020-02-16 03:06
lol, 2020 and still no change

**Comment by GoldenFinger** [comment] 2020-02-18 21:24
does anyone has a solution for this?

**Comment by MihaMarkic** [comment] 2020-02-19 09:26
IMO having a functional WebView is a big thing. By functional I mean stuff like this issue and more. Otherwise it is really handicapped and not very useful besides loading URLs and showing their content.  i.e. I've done plenty of hybrid (Xamarin) apps that rely on WebView and, event though I'd really wish, I can't switch to flutter or start new apps with flutter until WebView is first class citizen. I assume I'm not alone.

**Comment by woutervanwijk** [comment] 2020-03-09 09:25
Aren't onPageStarted and onPageFinished useful in this?

**Comment by d3fkon** [comment] 2020-05-01 20:09
> 
> 
> Aren't onPageStarted and onPageFinished useful in this?

Nope doesn't work.
This feature is really need imo. Working with PWA's is impossible with this WebView :(

**Comment by TMSantos** [comment] 2020-09-08 12:56
This is easily fixed with navigationDelegate, the widget gives everything you need:

`    navigationDelegate: (action) {
                    launch(action.url);
                    return NavigationDecision.prevent;
                  },`

You can prevent any navigation, and use https://pub.dev/packages/url_launcher to launch it

**Comment by PauloZung** [comment] 2021-07-21 20:30
> This is easily fixed with navigationDelegate, the widget gives everything you need:
> 
> ` navigationDelegate: (action) { launch(action.url); return NavigationDecision.prevent; },`
> 
> You can prevent any navigation, to avoid 'url_scheme' error, and use https://pub.dev/packages/url_launcher to launch it
> 
> ![Screenshot 2020-09-08 at 13 59 00](https://user-images.githubusercontent.com/5798822/92479480-80d81c80-f1db-11ea-8290-2aeeb9c85d16.png)

It does not work when accessing a PWA that changes url without reloading the whole page.

**Comment by stefanmusat** [comment] 2021-09-22 04:51
I've tried the navigationDelegate, onPageStarted/Finished with webViewController.currentUrl but they are only catching the redirects to outer urls. I have like www.mydomain.com/news and inside I have an article www.mydomain.com/news?articleId=1 and none of the mentioned methods catches the url change. Any updates or suggestions?

**Comment by AndriiHavrylyak** [comment] 2022-09-15 06:18
hi, has anyone been able to solve this problem??

**Comment by AndriiHavrylyak** [comment] 2022-09-15 06:22
> Я пробовал navigationDelegate, onPageStarted/Finished с webViewController.currentUrl, но они перехватывают только перенаправления на внешние URL-адреса. Мне нравится [www.mydomain.com/news](http://www.mydomain.com/news) , а внутри у меня есть статья [www.mydomain.com/news?articleId=1](http://www.mydomain.com/news?articleId=1) , и ни один из упомянутых методов не улавливает изменение URL-адреса. Любые обновления или предложения?



> I've tried the navigationDelegate, onPageStarted/Finished with webViewController.currentUrl but they are only catching the redirects to outer urls. I have like [www.mydomain.com/news](http://www.mydomain.com/news) and inside I have an article [www.mydomain.com/news?articleId=1](http://www.mydomain.com/news?articleId=1) and none of the mentioned methods catches the url change. Any updates or suggestions?

I have the same problem, did you manage to get around it somehow? thank you)

**Comment by Juanr1m** [comment] 2022-10-12 11:07
really need this

**Comment by NTA-trongpq** [comment] 2022-11-01 09:45
Any update?

**Comment by krishaajtak** [comment] 2023-04-14 11:47
Is this possible now? @bparrishMines @stefanmusat ?

**Closed** 2023-04-18 19:18 UTC
Labels: new feature, plugin, p: webview, P4
