### ISSUE TITLE
[Plugin] Does the google_sign_in plugin implement url_launcher? If so, how?

### ISSUE THREAD

**Issue by Gene-Dana** [flutter/flutter#79671] opened 2021-04-02 21:19 UTC
Hi there ! 

I've been touring through the source code of the [google_sign_in plugin](https://github.com/flutter/plugins/tree/master/packages/google_sign_in), and for the life of me, I cannot figure out how they get the browser to launch and then close in Flutter Web.

![2021-04-01 15 41 46](https://user-images.githubusercontent.com/45580241/113454811-1edd3f80-93d7-11eb-81a5-bf54c9825e47.gif)

My end goal is to add web support to the existing [ github_sign_in plugin](https://github.com/dotronglong/dart-github-sign-in) and I would like to model the implementation around google_sign_in. 

Any help would be appreciated ! Thanks again

**Comment by bdlukaa** [comment] 2021-04-02 21:59
- You can use firebase auth with this: 

```dart
GoogleAuthProvider googleProvider = GoogleAuthProvider();

googleProvider.addScope('https://www.googleapis.com/auth/contacts.readonly');
googleProvider.setCustomParameters({
  'login_hint': 'user@example.com'
});

await FirebaseAuth.instance.signInWithPopup(googleProvider);
```

The code above will open a window and log in the user

- If you don't use firebase_auth, you can take a look at `google_sign_in` web source code: 
https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in_web

**Comment by stuartmorgan** [comment] 2021-04-02 23:22
The Flutter issue tracker is for bug reports and feature requests; for help with your own code please use a community resource like StackOverflow or Discord.

Closing, as this is not a bug or feature request.

**Closed by stuartmorgan** 2021-04-02 23:22 UTC
