### ISSUE TITLE
[Flutter Inspector] I know it's good to see the flutter inspector in VSCode, but I just want to see it in Chrome, how can I do it ?

### ISSUE THREAD

**Issue by jerryzhoujw** [flutter/flutter#67886] opened 2020-10-12 01:58 UTC
## Use case

1. I know it's good to see the flutter inspector in VSCode.
2. But my computer screen is not so bigger on laptop, It would be good open inspector in separate window.

see bellow image, it's 2/3 of my screen with now, and it's hard to see code & inspector efficiently.

<img width="1101" alt="Screen Shot 2020-10-12 at 9 56 06 AM" src="https://user-images.githubusercontent.com/6405390/95697404-33831b00-0c71-11eb-800c-3fb7223f38cc.png">

## Proposal

1. So  I would like to open flutter inspector in chrome as before.  how can I do it ?

**Comment by RoyARG02** [comment] 2020-10-12 09:13
Hi @jerryzhoujw 
You can open flutter inspector in chrome by either of the follwing two ways:
1. In **VSCode** show all commands by pressing Ctrl + Shift + P, then selecting **Dart: Open Devtools**...
![dart_open_devtools](https://user-images.githubusercontent.com/44899587/95728090-b4a1d880-0c98-11eb-9793-4a3c26b94908.png)
...then selecting **Open Devtools in Web Browser**.
![open_devtools_in_web_browser](https://user-images.githubusercontent.com/44899587/95728100-b79cc900-0c98-11eb-8eb5-c522a74c8fa8.png)

2. Running `flutter run` directly in the root of the project at the terminal and then pressing **`v`** after the app launches.

**Comment by TahaTesser** [comment] 2020-10-12 14:07
Hi @jerryzhoujw 
You can uncheck this setting 
![image](https://user-images.githubusercontent.com/48603081/95755679-538efa80-0cc2-11eb-9b5c-a44e172c9acf.png)

Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-12 14:07 UTC

**Comment by jerryzhoujw** [comment] 2020-10-13 03:10
Thank you @TahaTesser,

   Just because when I check the content on [https://flutter.dev/docs/development/tools/devtools/inspector](https://flutter.dev/docs/development/tools/devtools/inspector), and didn't found this message above.  Wonder the `devtools/inspector` content update should belong to [https://github.com/Dart-Code/Dart-Code/](https://github.com/Dart-Code/Dart-Code/) or [https://github.com/flutter/flutter](https://github.com/flutter/flutter) ?

**Comment by TahaTesser** [comment] 2020-10-13 07:24
Hi @jerryzhoujw 
It's embedding dev tools in VS Code  plugin's job as far as I know so it would be https://github.com/Dart-Code/Dart-Code/

**Comment by jerryzhoujw** [comment] 2020-10-13 07:54
Thank you very much @TahaTesser .
