### ISSUE TITLE
Firebase PhoneAuth  0.8.3 - signInWithCredential returns null reference 

### ISSUE THREAD

**Issue by marscj** [flutter/flutter#27763] opened 2019-02-11 11:00 UTC
E/MethodChannel#plugins.flutter.io/firebase_auth(21209): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(21209): java.lang.NullPointerException: null reference
E/MethodChannel#plugins.flutter.io/firebase_auth(21209): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:2)
E/MethodChannel#plugins.flutter.io/firebase_auth(21209): 	at com.google.firebase.auth.FirebaseAuth.signInWithCredential(Unknown Source:137)
E/MethodChannel#plugins.flutter.io/firebase_auth(21209): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInWithCredential(FirebaseAuthPlugin.java:398)

**Comment by zoechi** [comment] 2019-02-11 11:49
Duplicate of #27132

**Closed by zoechi** 2019-02-11 11:49 UTC
