### ISSUE TITLE
Flutter for Web large build size

### ISSUE THREAD

**Issue by arnabchat90** [flutter/flutter#74561] opened 2021-01-23 13:04 UTC
## Details

1. Flutter web production build generated using flutter build web --release is generating >1 MB main bundle file. This is manifolds higher than general web builds.

![image](https://user-images.githubusercontent.com/15185453/105578902-66c56200-5da9-11eb-88e3-d6fc98888534.png)

2. --release tag actually does nothing same sized builds are getting generated.

As flutter web is in beta, wanted to know if this is actively worked on, as we are evaluating flutter for web for our org. Or if there are other build optimization techniques we can use

**Target Platform:** Web
**Target OS version/browser:** chrome
**Devices:** Web

## Logs

<details>
<summary>Logs</summary>

Flutter analyze
```
Analyzing buildsize...
No issues found! (ran in 1.4s)
```
Flutter Doctor Output - 
```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.25.0-8.3.pre at D:\Arnab\flutter-git\flutter
    • Framework revision 5d36f2e7f5 (9 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\arnab\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\arnab\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\arnab\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\arnab\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.75

```

</details>

**Comment by fodil-a** [comment] 2021-01-23 17:17
For point 2. it is because `--release` is the default.

**Comment by msoham123** [comment] 2021-01-23 18:48
![image](https://user-images.githubusercontent.com/51520568/105611148-796b7700-5d68-11eb-8470-98eeb355f08c.png)

Same issue here. My build is over 2MB! And this is minified already, right?

**Comment by iapicca** [comment] 2021-01-24 17:07
possible duplicate of https://github.com/flutter/flutter/issues/46589

**Comment by pedromassangocode** [comment] 2021-01-25 14:40
Seems to be a duplicate of https://github.com/flutter/flutter/issues/46589 to me. Closing this one.
For anyone interested in this issue please follow on that one for updates.
Thank you

**Closed by pedromassangocode** 2021-01-25 14:40 UTC
Labels: created via performance template
