### ISSUE TITLE
[google_maps] Support Cloud-based Maps Styling 

### ISSUE THREAD

**Issue by Cjoshua2** [flutter/flutter#78513] opened 2021-03-18 06:57 UTC
Would really appreciate the support for new google's cloud styling feature.

**Comment by pedromassangocode** [comment] 2021-03-18 08:12
Hi @Cjoshua2 
Can you please elaborate? It is not clear what you are proposing.
Thank you

**Comment by Cjoshua2** [comment] 2021-03-18 08:17
This one - https://console.cloud.google.com/google/maps-apis/client-styles
I also saw someone asking in stackoverflow - https://stackoverflow.com/questions/65613810/flutter-google-maps-how-to-use-cloud-styling
Sorry for my english i am not native speaker.

**Comment by pedromassangocode** [comment] 2021-03-18 11:29
Feature references for Android
https://developers.google.com/maps/documentation/android-sdk/cloud-based-map-styling.

**Comment by cedvdb** [comment] 2021-11-10 16:03
This would solve the flickering issue when calling setStyles

**Comment by incnuvem** [comment] 2021-12-27 21:56
this issue duplicates https://github.com/flutter/flutter/issues/67631 . We would track this request on #67631

**Comment by darshankawar** [comment] 2022-05-30 06:13
Closing this as duplicate of https://github.com/flutter/flutter/issues/67631

**Closed by darshankawar** 2022-05-30 06:13 UTC
Labels: new feature, plugin, p: first party, p: maps, proposal, passed first triage, P5
