### ISSUE TITLE
native pop FlutterViewController shake

### ISSUE THREAD

**Issue by FirstDKS521** [flutter/flutter#46212] opened 2019-12-06 03:40 UTC
I have four native tabbar, one of load FlutterViewController, when I click a flutter button push to native page, then pop to FlutterViewController, flutterview shake, my FlutterViewController navigetion is hiden, please help me

**Comment by iapicca** [comment] 2019-12-06 09:49
Hi @FirstDKS521 
can you please provide your updated  `flutter doctor -v`
and a minimal code sample or the steps to reproduce the problem?
Thank you

**Comment by FirstDKS521** [comment] 2019-12-07 06:04
Hi @iapicca

**Comment by FirstDKS521** [comment] 2019-12-07 06:13
Hi @iapicca 
my tabbar manager oneVC,twoVC,threeVC,fourVC, in the threeVC,code:
`
FlutterViewController *flutterVC = [[FlutterViewController alloc] init];
[self addChildViewController:flutterVC];
[self.view addSubview:flutterVC.view];
flutterVC.view.frame = self.view.bounds;
`
in the flutter project, click a flutter button push to native page,pop to threeVC will shake

**Comment by FirstDKS521** [comment] 2019-12-07 06:38
if have like my iOS project demo, tabbar manager four native VC,one of is load flutterViewController,please give me a project link,i`ll check it out

**Comment by iapicca** [comment] 2019-12-09 08:04
Hi ... 
could you please run 
`
 flutter channel stable
`
`
 flutter upgrade
`
If the issue persist please provide your updated `flutter doctor -v`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by VladyslavBondarenko** [comment] 2020-01-10 08:56
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by FirstDKS521** [comment] 2020-01-20 08:51
![12](https://user-images.githubusercontent.com/15830054/72711948-0fdce980-3ba5-11ea-9027-91c77086560d.jpg)
this is my message run 'flutter doctor'

**Comment by iapicca** [comment] 2020-01-20 09:54
Hi @FirstDKS521  
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a minimal code sample to reproduce the problem

Please refrain from posting pictures if not necessary.
thank you

**Comment by VladyslavBondarenko** [comment] 2020-02-14 13:20
The issue is already long time not active and without answer. I hope it's solved.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code, logs and the output of `flutter doctor -v` please

**Closed by VladyslavBondarenko** 2020-02-14 13:20 UTC
Labels: waiting for customer response
