### ISSUE TITLE
 spacebar not working in TextFormField flutter web

### ISSUE THREAD

**Issue by miraklecode** [flutter/flutter#78652] opened 2021-03-19 21:20 UTC
In flutter web, in TextFormField / Form field I have to press shift+spacebar in order to have a space in between words.

**Comment by Umerfarooq55** [comment] 2021-03-20 09:14
Can you Send the screen show of your TextFormField  Widget Please!

**Comment by darshankawar** [comment] 2021-03-22 09:25
@miraklecode 
Tried a sample code on latest master and was able to use spacebar alone to add spaces between words without any issues.

<img width="485" alt="Screenshot 2021-03-22 at 2 51 43 PM" src="https://user-images.githubusercontent.com/67046386/111967516-27539180-8b1e-11eb-8729-e16c80a1227a.png">

```

body: Center(
        child: TextFormField(
          decoration: InputDecoration(
            hintText: 'enter here'
          ),
        ),
      )
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.194, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.194 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision e58ee0fbc7 (2 hours ago), 2021-03-22 13:06:06 +0800
    • Engine revision e6db3a275e
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

If above sample code doesn't represent your issue, please provide a reproducible code sample along with `flutter doctor -v` that shows the issue you are facing.
Thanks.

**Comment by slav140** [comment] 2021-03-22 12:43
I have the same problem in latest master, flutter web. Flutter version 2.1.0-13.0.pre.194
this works
```
body: Center(
    child: TextFormField(
      decoration: InputDecoration(
        hintText: 'enter here'
      ),
    ),
) 
```


but when parent is ListView does not work
 ```
body: ListView(
  children: [
    Center(
      child: TextFormField(
        decoration: InputDecoration(hintText: 'enter here'),
      ),
    )
  ],
) 
```

**Comment by miraklecode** [comment] 2021-03-22 17:05
to be specific:
the problem occurs in flutter web on mobile, on desktop it is working
I understood that probably is related to the capitalization, in fact if I do SHIFT+spacebar it is working

'''
body: Center(
    child:TextFormField(
                              controller: _lastName,
                              autocorrect: false,
                              keyboardType: TextInputType.text,
                              textCapitalization: TextCapitalization.words,
                              decoration: textInputDecoration.copyWith(labelText: 'Last Name'),
                              validator: (val) => val.isEmpty ? 'please enter your last name' : null,
                            ),
    ),
), 
'''

**Comment by miraklecode** [comment] 2021-03-22 17:10
> Can you Send the screen show of your TextFormField Widget Please!

sorry for the late, see above
thx

**Comment by darshankawar** [comment] 2021-03-23 06:28
@miraklecode 
Tried your sample code using latest master on iPhone simulator mobile browser (safari) and saw no issues, unless I missed any part to replicate properly:


https://user-images.githubusercontent.com/67046386/112102928-0434ea80-8bcf-11eb-8bdf-955c16b234da.mov


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.206, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.206 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 720dac5438 (2 hours ago), 2021-03-22 20:56:02 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.


```

</details>

**Comment by miraklecode** [comment] 2021-03-23 17:31
@darshankawar 
thanks yes it is working on simulator,
but is not actually working when you deploy it and use it on an actual phone.

https://user-images.githubusercontent.com/65094884/112190754-8965d280-8bc2-11eb-8762-5024b6033ba0.MP4

**Comment by darshankawar** [comment] 2021-03-24 06:35
@miraklecode 
I ran `flutter build web` on latest master and opened it on physical device's browser (safari), on which the spacebar worked properly.


https://user-images.githubusercontent.com/67046386/112265743-fba8e680-8c98-11eb-98a8-544ec9796396.MP4

If this doesn't represent the issue you are facing, please provide step by step to replicate it on mobile browser.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.230, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.230 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 975fb0f06c (2 hours ago), 2021-03-23 21:33:05 -0700
    • Engine revision d59a01d2d3
    • Dart version 2.13.0 (build 2.13.0-150.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.


```

</details>

**Comment by tiloc** [comment] 2021-04-08 23:02
I have the same issue. If you take the code at https://github.com/tiloc/faiadashu . I am having the issue on macOS, but not in the browser.
It is TextFormFields inside a ListView. Shift + Spacebar works for me as well.

To see the issue, launch the app, choose "SDC Demo Scroller" from the main menu and then select the first field "Enter your first name". Start typing letters and hit space. You should see an ink splash, but no space being entered.
![Screen Recording 2021-04-09 at 00 58 12](https://user-images.githubusercontent.com/16414047/114106393-f2419000-98ce-11eb-9ca5-d18831ec82aa.gif)

```
 flutter doctor -v
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on macOS 11.2.3 20D91 darwin-arm, locale en-DE)
    • Flutter version 2.1.0-12.1.pre at /Users/tilo/development/flutter
    • Framework revision 8264cb3e8a (4 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tilo/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_SDK_ROOT = /Users/tilo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 08081FDD4002T6 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by pedromassangocode** [comment] 2021-05-07 10:53
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 10:53 UTC
Labels: in triage, waiting for customer response

**Comment by talski** [comment] 2021-06-16 20:00
Anyone that had this problem, how did you solve it?
