### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, OS Error: Permission denied, errno = 13

### ISSUE THREAD

**Issue by BorisDmv** [flutter/flutter#141946] opened 2024-01-21 17:22 UTC
## Command
```
flutter --version
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create file, OS Error: Permission denied, errno = 13
```
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.createSync (dart:io/file_impl.dart:306:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:26:16)
#3      Initializer.createSessionFile (package:unified_analytics/src/initializer.dart:84:17)
#4      Initializer.run (package:unified_analytics/src/initializer.dart:126:7)
#5      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:390:17)
#6      new Analytics (package:unified_analytics/src/analytics.dart:83:12)
#7      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:45:10)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#10     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#13     analytics (package:flutter_tools/src/globals.dart:93:36)
#14     exitWithHooks (package:flutter_tools/src/base/process.dart:583:15)
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:117:24)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
```
[33m[!][39m Flutter (Channel stable, 3.16.8, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-BG)
    [32m•[39m Flutter version 3.16.8 on channel stable at
      /Users/boris-laptop/Documents/flutter
    [33m![39m Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.2.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/boris-laptop/Documents/flutter.
      Consider adding /Users/boris-laptop/Documents/flutter/bin to the front of
      your path.
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 67457e669f (5 days ago), 2024-01-16 16:22:29 -0800
    [32m•[39m Engine revision 6e2ea58a5c
    [32m•[39m Dart version 3.2.5
    [32m•[39m DevTools version 2.28.5
    [32m•[39m If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    [32m•[39m Android SDK at /Users/boris-laptop/Library/Android/sdk
    [32m•[39m Platform android-33, build-tools 31.0.0
    [32m•[39m Java binary at: /usr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.3+7-LTS)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.2)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15C500b
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[32m[✓][39m VS Code (version 1.85.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.80.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m macOS (desktop) • macos  • darwin-arm64   • macOS 14.2.1 23C71
      darwin-arm64
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.234

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by dam-ease** [comment] 2024-01-22 10:15
Closing this as a duplicate of https://github.com/flutter/flutter/issues/141857.
Please check https://github.com/flutter/flutter/issues/141857#issuecomment-1900544415 if it works in your case?

**Comment by christopherfujino** [comment] 2024-01-23 21:58
@eliasyishak can you investigate?

**Comment by eliasyishak** [comment] 2024-01-23 22:07
@BorisDmv thank you for filing this issue! Can you help provide a little more clarity into this permissions error?

Does this error happen every time you run it and if possible, can you check if the directory `~/.dart-tool` was created on your workstation?

If it was created, were there any files also created inside there? Maybe one called `dart-flutter-telemetry.config`?

**Comment by BorisDmv** [comment] 2024-01-23 22:10
> @BorisDmv thank you for filing this issue! Can you help provide a little more clarity into this permissions error?
> 
> Does this error happen every time you run it and if possible, can you check if the directory `~/.dart-tool` was created on your workstation?
> 
> If it was created, were there any files also created inside there? Maybe one called `dart-flutter-telemetry.config`?

Turn out I removed all cache files related to flutter and installed it because I did something flutter was warning me but I did it and it was upgrading the version using sudo so prettt much is messed up something after that

**Comment by eliasyishak** [comment] 2024-01-23 23:11
@BorisDmv ah I see, thank you for following up. I'll go ahead and close this issue then, but please feel free to reopen if you run into this again! 🙂

**Closed** 2024-01-23 23:11 UTC
Labels: c: crash, tool, team-tool
