### ISSUE TITLE
[Windows Web] A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed.

### ISSUE THREAD

**Issue by minhduc1827** [flutter/flutter#95460] opened 2021-12-17 09:57 UTC
Hello all, now i updated the flutter sdk 2.8.1.
When i run it on flutter and press the key, i see the exceptions on it:

```console
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, 
please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's 
event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#bb535(physicalKey:
PhysicalKeyboardKey#8ed21(usbHidUsage: \"0x1700000000\", debugName: \"Key with ID 0x1700000000\"), 
logicalKey: LogicalKeyboardKey#000e2(keyId: \"0x000000e2\", keyLabel: \"Â\", debugName: \"Key Â\"), 
character: null, timeStamp: 0:00:57.416299, synthesized)"
```
Please check it and update it thank you very much

**Comment by maheshmnj** [comment] 2021-12-17 10:12
Hi @minhduc1827, Thanks for reporting the issue. Please share the output of `flutter doctor -v`, And Are there any known steps to reproduce this issue or any specific key press which reproduces this? 
This is likely a duplicate of https://github.com/flutter/flutter/issues/94688

Thanks

**Comment by minhduc1827** [comment] 2021-12-17 10:14
Now i switch to master and it throws errors when run:
![image](https://user-images.githubusercontent.com/4393681/146528659-71d60cf7-fa8b-4c28-845e-9d49c37269a9.png)

**Comment by minhduc1827** [comment] 2021-12-17 10:28
Hi @maheshmnj , i upload the video to reproduce it
https://user-images.githubusercontent.com/4393681/146530508-aa15db92-751d-481b-9b36-cc73cce902b9.mp4

**Comment by minhduc1827** [comment] 2021-12-17 10:30
Here is the flutter doctor
![image](https://user-images.githubusercontent.com/4393681/146530789-a62cab3c-23e4-49a5-ad83-cf163b8f53bf.png)

**Comment by minhduc1827** [comment] 2021-12-20 03:07
Hi @maheshmnj , do you see the videos that i send. Please help me, this issue happened from dart sdk 2.5
Now i downgraded to the version 2.3

**Comment by maheshmnj** [comment] 2021-12-20 06:05
thanks for the info @minhduc1827, 
> Hi @maheshmnj , do you see the videos that I send.

Yes, I saw it but the video doesn't seem to help to find the reproducible steps. Are there any known steps to reproduce the issue?

> Now i switch to master and it throws errors when run:

This error seems to be irrelevant to this issue and seems to be coming from a third party package `platform`. Please file a issue for the same with the maintainer of the package.


ps: In the future please prefer sending the textual output of code snippets or console logs instead of image.

**Comment by maheshmnj** [comment] 2021-12-20 07:01
Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/94688.

**Closed** 2021-12-20 07:01 UTC
