### ISSUE TITLE
[proposal] Ability to set TextOverflow on TextField or TextFormField

### ISSUE THREAD

**Issue by ancileddu** [flutter/flutter#62963] opened 2020-08-05 09:39 UTC
## Overflow on TextField or TextFormField

When a text field is not enabled, I would like to have the option to manage the text overflow, just as you can do it in the Text Widget.

## Proposal
Manage text overflow on the textfield or textformfield

**Comment by pedromassangocode** [comment] 2020-08-05 10:15
Hi @ancileddu 
Can you elaborate more about this proposal? please explain how the current version of Flutter prevents you to not manage the text overflow while it is disabled. Would be great if you provide a sample code that demonstrate this.
Thank you.

**Comment by ancileddu** [comment] 2020-08-05 10:18
it is not an error.
i can't define a TextOverflow property on TextField or on TextFormField. in my opinion, it is very important for disabled TextField.

in example:
in text widget i can do this:

Text("longtextttttttttttttttttt", overflow: TextOverflow.ellipsis,)

in TextFormField, i can't do something like that.

**Comment by aneeshjose** [comment] 2020-08-05 10:36
Try to use the `hintText` property of the `InputDecoration` to render your text on the `TextField`. It works the same way as the `TextOverflow.ellipsis`.  This may not be the perfect solution. But it works.

**Comment by ancileddu** [comment] 2020-08-05 12:51
sorry but it is not a solution for me.  when labelText is set, hintText is shown only when focused, and i never focus a disabled field.

**Comment by lordvins226** [comment] 2020-08-06 00:20
Hello @ancileddu  You can create your custom textField widget if you want.

**Comment by JonLevin25** [comment] 2021-01-15 23:47
+1
Using `TextFormField` and as soon as the user inputs more than can be shown it goes blank.
I'd go as far as saying this is a bug rather than a new feature - since it looks as though the text has disappeared completely

**Comment by pedromassangocode** [comment] 2021-01-21 13:20
Closing this as a duplicate of https://github.com/flutter/flutter/issues/62963. Please follow up/subscribe on that issue for updates.

**Closed by pedromassangocode** 2021-01-21 13:20 UTC
Labels: a: text input, framework, passed first triage, proposal, severe: new feature
