### ISSUE TITLE
[tool_crash] _TypeError: (#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:198:24))

### ISSUE THREAD

**Issue by souzaavi** [flutter/flutter#158382] opened 2024-11-08 17:06 UTC
## Command
```sh
flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:198:24))
```console
#0      PlistParser.getValueFromFile (package:flutter_tools/src/ios/plist_parser.dart:198:24)
#1      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:470:29)
<asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#10     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.0, on macOS 15.0.1 24A348 darwin-x64, locale en-IN)
    [32m•[39m Flutter version 3.24.0 on channel stable at /Users/kelvin/Development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 80c2e84975 (3 months ago), 2024-07-30 23:06:49 +0700
    [32m•[39m Engine revision b8800d88be
    [32m•[39m Dart version 3.5.0
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/kelvin/Library/Android/sdk
    [32m•[39m Platform android-34-ext8, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/kelvin/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16B40
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m Connected device (3 available)
    [32m•[39m Kelvin’s iPhone (mobile) • 032ddaa0ed0148146c5d9ce838734d1c3bb2d14c • ios            • iOS 15.8.3 19H386
    [32m•[39m macOS (desktop)          • macos                                    • darwin-x64     • macOS 15.0.1 24A348 darwin-x64
    [32m•[39m Chrome (web)             • chrome                                   • web-javascript • Google Chrome 130.0.6723.117

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.1.2+12
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
add_2_calendar-3.0.1
awesome_notifications-0.10.0
awesome_notifications_core-0.9.3
awesome_notifications_fcm-0.10.0
credential_manager-2.0.2
firebase_core-3.6.0
firebase_core_web-2.18.1
firebase_crashlytics-4.1.3
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
mobile_device_identifier-0.0.2
objectbox_flutter_libs-4.0.2
package_info_plus-8.0.3
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
uni_links2-0.6.0+2
uni_links_web2-0.1.0+2
url_launcher-6.3.1
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
webview_cookie_manager-2.0.6
webview_flutter-4.10.0
webview_flutter_android-4.0.0
webview_flutter_wkwebview-3.15.0

**Comment by huycozy** [comment] 2024-11-11 07:28
Duplicate of https://github.com/flutter/flutter/issues/138465.

**Closed by huycozy** 2024-11-11 07:28 UTC
Labels: in triage
