### ISSUE TITLE
Flutter doesn't support downloading Dart SDK over proxy on Windows

### ISSUE THREAD

**Issue by mengchengxxx** [flutter/flutter#13557] opened 2017-12-14 09:10 UTC
when i run flutter doctor:

PS E:\git_project\flutter\bin> flutter doctor
Checking Dart SDK version...
Downloading Dart SDK 1.25.0-dev.11.0...
Start-BitsTransfer : HTTP 状态 407: 需要代理身份验证。
所在位置 E:\git_project\flutter\bin\internal\update_dart_sdk.ps1:55 字符: 19
+ Start-BitsTransfer <<<<  -Source $dartSdkUrl -Destination $dartSdkZip
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBits
   TransferCommand

Error: Unable to update Dart SDK. Retrying...

How to solve this problem？

**Comment by sethladd** [comment] 2017-12-14 19:40
cc @jakobr-google @mit-mit does this look familiar?

Does this mean that a proxy or intermediary is in the way?

**Comment by mit-mit** [comment] 2017-12-14 21:40
I think this is the windows proxy issue @goderbau

**Comment by Hixie** [comment] 2018-03-03 00:48
Dupe of https://github.com/flutter/flutter/issues/10903.

**Closed by Hixie** 2018-03-03 00:48 UTC
Labels: dev: first hour, dev: tool, new feature, ❖ platform-windows
