### ISSUE TITLE
Many columns on the framework tree stuck since yesterday morning

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#122209] opened 2023-03-08 17:06 UTC
It looks like many machines are idle, but no work is starting:
<img width="966" alt="Screenshot 2023-03-08 at 9 05 36 AM" src="https://user-images.githubusercontent.com/6343103/223780831-006981cb-9408-4e83-b90f-587838fd0813.png">

@yusuf-goog on call

**Comment by keyonghan** [comment] 2023-03-08 17:24
The root cause is https://github.com/flutter/flutter/issues/122117.
The hanging yellow boxes prevents back filling.
Working to vacuum those stale statues.

**Comment by keyonghan** [comment] 2023-03-08 17:30
Backfilling started.

<img width="1532" alt="Screenshot 2023-03-08 at 9 30 20 AM" src="https://user-images.githubusercontent.com/54558023/223786633-7eda00a2-292a-4a9f-9a3a-c1f34e4f3343.png">

**Comment by godofredoc** [comment] 2023-03-10 02:01
@keyonghan can we close this one?

**Comment by keyonghan** [comment] 2023-03-10 17:21
Yes. Root cause is still being investigated/worked on.

**Closed by keyonghan** 2023-03-10 17:21 UTC
Labels: team: infra, passed secondary triage, P0
