### ISSUE TITLE
[WebViewWidget] webView is not working inside the overlay window

### ISSUE THREAD

**Issue by Arvind0005** [flutter/flutter#133038] opened 2023-08-22 10:42 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

create a flutter project with:
install [flutter_overlay_window](https://pub.dev/packages/flutter_overlay_window) package.
clone it from https://github.com/Arvind0005/overlay_window
or
with main.dart:

```
import 'dart:async';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_3d0/widget/Myapp.dart';
import 'package:flutter_3d0/widget/home_page.dart';
import 'package:flutter_3d0/widget/overlayContent.dart';
import 'package:flutter_background_service/flutter_background_service.dart';
import 'package:flutter_background_service_android/flutter_background_service_android.dart';
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

@pragma("vm:entry-point")
void overlayMain() {
  runApp(const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyOverlayContent()
  ));
}
```

myapp.dart:

```
import 'package:flutter/material.dart';
import 'home_page.dart';
import 'overlayContent.dart';
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        // home: Home(),
      home: Home()
    );
  }
}
```

home_page.dart:
```
import 'package:flutter/material.dart';
import 'package:flutter_background_service/flutter_background_service.dart';
import 'package:flutter_overlay_apps/flutter_overlay_apps.dart';
import 'package:flutter_overlay_window/flutter_overlay_window.dart';
import 'package:model_viewer_plus/model_viewer_plus.dart';
import 'package:system_alert_window/system_alert_window.dart';
import 'package:webview_flutter/webview_flutter.dart';

class Home extends StatefulWidget {
  const Home({super.key});

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  late final WebViewController controller;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    controller = WebViewController()
      ..loadRequest(
        Uri.parse('https://flutter.dev'),
      );
  }
  @override
  Widget build(BuildContext context) {
    String text="stop running";
    bool? status;
    return Scaffold(
      appBar: AppBar(title: const Text("3d model"),),
      body: Column(
        children: [
          ElevatedButton(onPressed: () async {
            await FlutterOverlayWindow.showOverlay(height: 600,width: 600,enableDrag: true);
          }, child: Text("start overlay")),
          ElevatedButton(onPressed: () async {
            status = await FlutterOverlayWindow.requestPermission();
            if(!status!)
              await FlutterOverlayWindow.requestPermission();
          }, child: Text("request permission")),
        ],
      ),
    );
  }
}

```
obverlayContent.dart:

```
import 'package:flutter/material.dart';
import 'package:flutter_overlay_apps/flutter_overlay_apps.dart';
import 'package:flutter_overlay_window/flutter_overlay_window.dart';
import 'package:model_viewer_plus/model_viewer_plus.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:webview_flutter_platform_interface/webview_flutter_platform_interface.dart';

class MyOverlayContent extends StatefulWidget {
  const MyOverlayContent({super.key});

  @override
  State<MyOverlayContent> createState() => _MyOverlayContentState();
}

class _MyOverlayContentState extends State<MyOverlayContent> {
  late final WebViewController controller;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
      controller = WebViewController()
      ..loadRequest(
        Uri.parse('https://flutter.dev'),
      );
  }
  @override
  Widget build(BuildContext context) {
    return WebViewWidget(controller: controller);
  }
}

```

### Expected results

The expected result is to view the webpage inside the overlay window, and this overlay can be viewed upon any apps running background without stopping them.

### Actual results

The same webview code is running on a normal screen but not inside a overlay window,when i click on show overlay button the overlay is not displayed,but if i try to display only overlay without webview inside it it works properly.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Invalid file path for libcolorx-loader.so
I/chatty  (23598): uid=10557(com.example.flutter_3d0) 3.raster identical 58 lines
E/libEGL  (23598): Invalid file path for libcolorx-loader.so
E/flutter (23598): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)
E/flutter (23598): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (23598): <asynchronous suspension>
E/flutter (23598): #1      SurfaceAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:976:30)
E/flutter (23598): <asynchronous suspension>
E/flutter (23598): #2      AndroidViewController.create (package:flutter/src/services/platform_views.dart:763:5)
E/flutter (23598): <asynchronous suspension>
E/flutter (23598): 
I/OplusFeedbackInfo(23598): [sendFPSInfo:L326] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(23598): [sendFPSInfo:L326] mInputBufCnt = 3 fps, mOutputBufCnt = 1 fps, mRenderFrameCnt = 1 fps
I/OplusFeedbackInfo(23598): [sendFPSInfo:L326] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(23598): [sendFPSInfo:L326] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(23598): [sendFPSInfo:L326] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
I/OplusFeedbackInfo(23598): [sendFPSInfo:L326] mInputBufCnt = 0 fps, mOutputBufCnt = 0 fps, mRenderFrameCnt = 0 fps
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3324], locale en-IN)
    • Flutter version 3.10.6 on channel stable at C:\src\flutter\flutter
    ! Warning: `dart` on your path resolves to C:\tools\dart-sdk\bin\dart.exe, which is not inside your current Flutter SDK checkout at
      C:\src\flutter\flutter. Consider adding C:\src\flutter\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (6 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and     
      upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc3)
    • Android SDK at C:\Users\Arvind\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.37)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.28307.1585
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\Arvind\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.70.0

[√] Connected device (4 available)
    • RMX2117 (mobile)  • 69TOEQ49QCYDD6BU • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.3324]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 115.0.5790.173
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 115.0.1901.188

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.

```

</details>

**Comment by Arvind0005** [comment] 2023-08-22 10:59
how to overcome this issue, thanks in advance

**Comment by dam-ease** [comment] 2023-08-22 11:41
Hi @Arvind0005. Thanks for filing this. I'm able to reproduce this on my end but from the behaviour and error logs, there seems to be a currently open issue describing the case https://github.com/flutter/flutter/issues/59951. Kindly comment, upvote and follow up on this issue for updates.
Closing this as a duplicate, if you disagree kindly let me know and I'd reopen this.
Thank you!

**Comment by dam-ease** [comment] 2023-08-25 10:01
Hello @Arvind0005. Thanks for checking that out. Running the code sample provided and clicking on `start overlay` button, I get the logs below which seem similar to the open issue I tagged. Can you confirm if your observed behaviour differs from this?

<details><summary>Log</summary>
<p>

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method showOverlay on channel x-slayer/overlay_channel)
#0      MethodChannel._invokeMethod
platform_channel.dart:308
<asynchronous suspension>
#1      FlutterOverlayWindow.showOverlay
overlay_window.dart:41
<asynchronous suspension>
#2      _HomeState.build.<anonymous closure>
home_page.dart:36
<asynchronous suspension>

``` 

</p>
</details>

**Closed** 2023-09-15 10:08 UTC
Labels: waiting for customer response, in triage
