### ISSUE TITLE
.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found

### ISSUE THREAD

**Issue by zhumj** [flutter/flutter#70006] opened 2020-11-07 03:26 UTC
This problem has bothered me for a long time.

Xcode v12.1
Flutter SDK v1.22.3

## Steps to Reproduce

1. flutter create --template module flutter_my_module
2. 
```
some/path/
├── flutter_my_module/
│   └── .ios/
│       └── Flutter/
│         └── podhelper.rb
└── MyApp/
    └── Podfile
```
3. Add the following lines to my Podfile:
```
flutter_application_path = '../flutter_my_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
```
4. For each Podfile target that needs to embed Flutter, call install_all_flutter_pods(flutter_application_path).
```
target 'MyApp' do
  install_all_flutter_pods(flutter_application_path)
end
```
5. Run pod install.
6. Xcode build.

## Logs

```
../flutter_my_module/.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found

Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by zhumj** [comment] 2020-11-07 09:15
After my investigation, the reason for the error was that I used the "flutter intl" plug-in. It is not clear that this plug-in will do this, or it will be the same after internationalization.

**Comment by darshankawar** [comment] 2020-11-09 07:22
@zhumj 
Since you said the issue was due to [intl](https://pub.dev/packages/intl) package which belongs to dart-lang and not Flutter, I'd suggest you to open the issue here : https://github.com/dart-lang/intl/issues
Closing from here since this isn't an issue with Flutter framework. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-11-09 07:22 UTC

**Comment by zhumj** [comment] 2020-11-09 07:39
I think the Flutter framework should also pay attention to and avoid this problem.

**Comment by Kiruel** [comment] 2020-12-18 12:42
I have the same problem, but I don't use inlt. Anyone have a solution ?

**Comment by lkpHub** [comment] 2020-12-30 09:12
I have the same problem, but I don't use inlt. Anyone have a solution ?
error msg:
```
export YACC=yacc
    export arch=i386
    export variant=normal
    /bin/sh -c /Users/lkp_mac/Library/Developer/Xcode/DerivedData/Yonline-dseboznqvnxvyoezrmzdgtvhsqke/Build/Intermediates.noindex/Yonline.build/Debug-iphonesimulator/Yonline.build/Script-B3D5927362BB91FAB37F2DB6.sh

/Users/lkp_mac/Desktop/Carzone/Yonline/../flutter_yonline/.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found

Command /bin/sh failed with exit code 
```

please help me

**Comment by aaluyi** [comment] 2021-01-25 02:23
> I have the same problem, but I don't use inlt. Anyone have a solution ?
> error msg:
> 
> ```
> export YACC=yacc
>     export arch=i386
>     export variant=normal
>     /bin/sh -c /Users/lkp_mac/Library/Developer/Xcode/DerivedData/Yonline-dseboznqvnxvyoezrmzdgtvhsqke/Build/Intermediates.noindex/Yonline.build/Debug-iphonesimulator/Yonline.build/Script-B3D5927362BB91FAB37F2DB6.sh
> 
> /Users/lkp_mac/Desktop/Carzone/Yonline/../flutter_yonline/.ios/Flutter/flutter_export_environment.sh: line 8: inherited: command not found
> 
> Command /bin/sh failed with exit code 
> ```
> 
> please help me

If you use the xcode simulator to run, just change the run mode to "debug". If you run on a real machine, change it to "release", and I can run after the modification.

**Comment by entonio** [comment] 2021-05-04 23:11
This issue is caused by `.ios/Flutter/flutter_export_environment.sh` not correctly handling Xcode vars, so I do think the issue is with whoever generates the file.
Specifically, the common Xcode var `$(inherited)` is placed in a shell script, where `$(...)` has the special 'run in a subshell' meaning. In my project, so
- what in `Generated.xcconfig` is a harmless `OTHER_LDFLAGS=$(inherited) -framework Flutter` line,
- in `flutter_export_environment.sh` becomes the broken `export "OTHER_LDFLAGS=$(inherited) -framework Flutter"`.

My workaround is replacing "" by '' using sed, but that's a very specific solution. It would be best to have the expoerts correctly generated, escaping the $.

**Comment by Wbqqqq** [comment] 2021-07-06 12:58
@entonio  I think your are right ， but I don't quite understand what you mean. Could you be more specific?
