### ISSUE TITLE
Keyboard show/hide on TextField triggers widget rebuild

### ISSUE THREAD

**Issue by klaszlo8207** [flutter/flutter#52342] opened 2020-03-10 18:47 UTC
When I have a TextField and my keyboard show/hide on that, then the widget is rebuild.

How to do a workaround on this? I don't want to rebuild every time when the keyboard changes. Thanks

**Comment by windows7lake** [comment] 2020-03-16 02:21
Have any idea to aviod it?

**Comment by IkhwanSI13** [comment] 2020-03-16 10:23
It happened to me too. I have another Flutter Project in 2019, and it works well with many forms of features. Before I started the new project, I updated the flutter SDK, and this problem occurred.

New updates to the Flutter SDK have an impact on other libraries such as flutter_keyboard_visibility.

btw, there are also some strange logs after I update them. The logs appear when I click on TextFormField widget

> W/IInputConnectionWrapper(  545): getSelectedText on inactive InputConnection
> W/IInputConnectionWrapper(  545): getTextAfterCursor on inactive InputConnection
> W/IInputConnectionWrapper(  545): beginBatchEdit on inactive InputConnection
> W/IInputConnectionWrapper(  545): endBatchEdit on inactive InputConnection

**Comment by klaszlo8207** [comment] 2020-03-16 13:45
> It happened to me too. I have another Flutter Project in 2019, and it works well with many forms of features. Before I started the new project, I updated the flutter SDK, and this problem occurred.
> 
> New updates to the Flutter SDK have an impact on other libraries such as flutter_keyboard_visibility.
> 
> btw, there are also some strange logs after I update them. The logs appear when I click on TextFormField widget
> 
> > W/IInputConnectionWrapper(  545): getSelectedText on inactive InputConnection
> > W/IInputConnectionWrapper(  545): getTextAfterCursor on inactive InputConnection
> > W/IInputConnectionWrapper(  545): beginBatchEdit on inactive InputConnection
> > W/IInputConnectionWrapper(  545): endBatchEdit on inactive InputConnection

What is the different between TextField and TextFormfield by the way?

**Comment by klaszlo8207** [comment] 2020-05-26 08:21
Any news on this? Or any workaround? Thanks

**Comment by clocksmith** [comment] 2020-06-18 15:51
Hi could you please add a small demo that reproduces this issue?

**Comment by guidezpl** [comment] 2020-07-22 12:29
I believe the keyboard resizing the viewport causes builds (as it should). I have a feeling this issue is indicative of doing things in `build` methods that would be better suited in initState or other StatefulWidget lifecycle methods. 

Code to repro would be helpful

**Comment by TahaTesser** [comment] 2020-08-05 14:28
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-08-05 14:28 UTC
Labels: P4, a: text input, f: material design, framework

**Comment by nicolasmq** [comment] 2020-08-28 04:04
I had the same issue with Form, it was fixed by declaring the GlobalKey<FormState>(); in the StatefulWidget and not in the State <Class>, I'm learning Flutter and I don't have more information about it. But if it works for someone, I observed that in a StatelessWidget this issue did not occur, but if I declared a GlobalKey in the State <class> class of a StatefullWidget the issue appears again.

**Comment by Soham-Rakhunde** [comment] 2021-01-05 17:20
I have the same issue
when the keyboard is in focus and we use Navigator.push the keyboard unfocus(closing) causes rebuild of the pushed page.
Normally it should only rebuild the ancestors where it was used
I also tried using FocusScope.of(context).unfocus() but this too causes rebuild since both things happen on the same button

**Comment by TahaTesser** [comment] 2021-01-06 12:09
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by HoseinHaqiqian** [comment] 2021-02-08 08:42
I had this with a dialog. so If you have a bottom sheet or dialog, just make it stateful, and save the variables in it. then by opening/closing the keyboard values will be hold.

**Comment by FeiWhang** [comment] 2021-04-15 07:58
just move from doing things inside build() to a stateful initState()

**Comment by davidgaspardev** [comment] 2021-05-31 22:11
@FeiWhang It doesn't matter if it's Stateless or Stateful, everything is rebuilt. As if starting the application again and with that the controllers go back to their default values.

 I was in the migration process and the old code didn't have this problem, I'm stuck.

**Comment by ahmed-salah-ask** [comment] 2021-06-29 23:18
if your screen **depends** on **MediaQuery** or **at least** having **one** widget depenig on MediaQuery, the keyboard popup changes the size of your screen, which triggers mediaQuery and causing rebuilds...in this case avoid using mediaQuery, Instead get your dimensions using (sizer package) https://pub.dev/packages/sizer
