### ISSUE TITLE
Getting this error Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.dev/google_maps_android_46)

### ISSUE THREAD

**Issue by ashokv1337** [flutter/flutter#134002] opened 2023-09-04 21:05 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Steps to reproduce
1. Create 3 screens =>  A > B > C
2. C is the Map screen where map is getting loaded.
`return GoogleMap(
              myLocationEnabled: true,
              mapType: MapType.hybrid,
              indoorViewEnabled: false,
              onMapCreated: (GoogleMapController controller) {
                if (!_controller!.isCompleted) {
                  _controller!.complete(controller);
                }

                if (_kInitialPosition != null) {
                  _navigateToInitialLocation(_kInitialPosition!);
                }
              },
              initialCameraPosition: CameraPosition(
                  target: _kInitialPosition ??
                      const LatLng(23.3453635, 78.343453)));

 Future<void> _navigateToInitialLocation(LatLng initial) async {
    final GoogleMapController controller = await _controller!.future;

    await controller.animateCamera(CameraUpdate.newCameraPosition(
        CameraPosition(target: initial, zoom: 18)));
  }
`
Now if o go from C > B, then again B > C, 
Getting this error always Unhandled Exception: MissingPluginException(No implementation found for method camera#animate on channel plugins.flutter.dev/google_maps_android_46)
But if i go from C > B > A then A > B > C, it doesn't through the exception and runs properly.

### Expected results

It should navigate to specific location as per the scenario, without giving the exception.

### Actual results

Mentioned in steps to reproduce.

### Code sample

<details><summary>Code sample</summary>

```dart
return GoogleMap(
              myLocationEnabled: true,
              mapType: MapType.hybrid,
              indoorViewEnabled: false,
              onMapCreated: (GoogleMapController controller) {
                if (!_controller!.isCompleted) {
                  _controller!.complete(controller);
                }

                if (_kInitialPosition != null) {
                  _navigateToInitialLocation(_kInitialPosition!);
                }
              },
              initialCameraPosition: CameraPosition(
                  target: _kInitialPosition ??
                      const LatLng(23.3453635, 78.343453)));

 Future<void> _navigateToInitialLocation(LatLng initial) async {
    final GoogleMapController controller = await _controller!.future;

    await controller.animateCamera(CameraUpdate.newCameraPosition(
        CameraPosition(target: initial, zoom: 18)));
  }
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4.1 22F82 darwin-arm64, locale
    en-IN)
    • Flutter version 3.13.2 on channel stable at /Users/ashokverma/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (11 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ashokverma/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14
      (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS
      13.4.1 22F82 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by stuartmorgan** [comment] 2023-09-04 23:38
Closing as a duplicate of https://github.com/flutter/flutter/issues/43785

**Closed by stuartmorgan** 2023-09-04 23:38 UTC
