### ISSUE TITLE
Apple app name changes do not work

### ISSUE THREAD

**Issue by dingzuhua** [flutter/flutter#43877] opened 2019-10-31 04:15 UTC
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.4 18E226, locale
    zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] Connected device (1 available)

• No issues found!

No matter how I change the name of the app in xcode, it doesn't work, and the name of the app on the phone is always the 'name' in ‘pubspec.yaml’, but if I change the name in ‘pubspec.yaml’, I have to change all the 'import'.

**Comment by dingzuhua** [comment] 2019-10-31 04:21
It's ok to run in xcode, but I don't want to open xcode to run

**Comment by tanutapi** [comment] 2019-10-31 05:25
This may duplicate of #41793
I ended up with regenerate iOS and Android project.

**Comment by dingzuhua** [comment] 2019-10-31 05:26
> This may duplicate of #41793
> I ended up with regenerate iOS and Android project.

It's regenerated an infinite number of times. It doesn't work

**Comment by dingzuhua** [comment] 2019-10-31 05:28
> This may duplicate of #41793
> I ended up with regenerate iOS and Android project.

Can only be called Runner???

**Comment by tanutapi** [comment] 2019-10-31 05:32
My project was created with older version of flutter which use objc and android configuration. A few week ago I updated flutter to newer version, everything work fine until I renamed my app name in the Xcode. I can not run my iOS via ether command line "flutter run ios" or from Android Studio.

I found that the generated .app has a different name rather than Runner.app. After read that #41793, I deleted ios and android folder and regenerate it with swift and kotlin configuration.

**Comment by dingzuhua** [comment] 2019-10-31 05:37
> My project was created with older version of flutter which use objc and android configuration. A few week ago I updated flutter to newer version, everything work fine until I renamed my app name in the Xcode. I can not run my iOS via ether command line "flutter run ios" or from Android Studio.
> 
> I found that the generated .app has a different name rather than Runner.app. After read that #41793, I deleted ios and android folder and regenerate it with swift and kotlin configuration.

How do I change the Display Name of my app?

**Comment by tanutapi** [comment] 2019-10-31 05:51
After I regenerated my ios folder, I simply change the Display Name in Xcode as described in official document https://flutter.dev/docs/deployment/ios#review-xcode-project-settings. Running from Android Studio / Visual Studio Code / command line is not a problem anymore.

**Comment by dingzuhua** [comment] 2019-10-31 06:31
> After I regenerated my ios folder, I simply change the Display Name in Xcode as described in official document https://flutter.dev/docs/deployment/ios#review-xcode-project-settings. Running from Android Studio / Visual Studio Code / command line is not a problem anymore.

I deleted the original ios, and I implemented the flutter create - I objc. Changing the name doesn't work

**Comment by jmagman** [comment] 2019-11-02 01:39
> I deleted the original ios, and I implemented the flutter create - I objc. Changing the name doesn't work

Can we get reproduction steps?  See my explanation and further questions you can answer in https://github.com/flutter/flutter/issues/41793#issuecomment-537681233.

**Comment by nguyenhuutinh** [comment] 2019-11-03 16:48
<img width="866" alt="Screenshot 2019-11-04 at 12 46 11 AM" src="https://user-images.githubusercontent.com/4114159/68088700-8a4a7700-fe9c-11e9-99dc-488d24a3b476.png">

@jmagman : I have to change back to Runner to make the flutter run work.
Otherwise, it will throw this error
<img width="604" alt="Screenshot 2019-11-04 at 12 47 42 AM" src="https://user-images.githubusercontent.com/4114159/68088720-bb2aac00-fe9c-11e9-8731-55dda8bae615.png">

**Comment by dingzuhua** [comment] 2019-11-04 02:54
> > 我删除了原始的ios，并实现了flutter create-I objc。更改名称无效
> 
> 我们可以得到繁殖的步骤吗？请参阅我的解释以及您可以在[＃41793（注释）中](https://github.com/flutter/flutter/issues/41793#issuecomment-537681233)回答的其他问题。

1.I deleted the original ios
2.I ran the flutter create-i objc. (I will only object - c)Regenerate ios
3.There is no problem with running directly
4.I changed Display Name in xcode to "i照护"
5.If I run it again, the application name doesn't change

**Comment by jmagman** [comment] 2019-11-06 19:21
I reproduced this.  Maybe this is a Xcode 11 change?

**Comment by bro-jo** [comment] 2019-11-08 01:27
In my case, When changing display name in xcode `Runner > General > Display Name`, the error is produced such as `ios/iphonesimulator/Runner.app`. So I put back `Display Name` and change `CFBundleName` from `Info.plist`, then it works.

**Comment by dingzuhua** [comment] 2019-11-08 07:40
> In my case, When changing display name in xcode `Runner > General > Display Name`, the error is produced such as `ios/iphonesimulator/Runner.app`. So I put back `Display Name` and change `CFBundleName` from `Info.plist`, then it works.

Thank you. That's fine

**Comment by JHBitencourt** [comment] 2019-11-08 17:03
The problem seems to be when changing the Display Name name directly on Xcode.

> XCode version: 11.2
> OS Catalina: 10.15.1 (19B88)

It works fine renaming the app when changing it on `Info.plist`

```
<key>CFBundleDisplayName</key>
<string>My App Name</string>
```

But if you change with XCode:
![xcode1](https://i.imgur.com/c8d7dgI.png)

It will change `Info.plist`:

```
<string>Espaço Estudante</string>
<string>$(PRODUCT_NAME)</string>
```
And make same changes on `project.pbxproj`, setting the value to `PRODUCT_NAME`:

![xcode2](https://i.imgur.com/sL4Zxl4.png)

And when trying to `flutter run`, it will end up changing `Runner.xcsheme`:

![xcode2](https://i.imgur.com/Gwn0HyY.png)

Which results in build failure:

> Could not find the built application bundle at build/ios/iphoneos/Runner.app.
> Error launching application on iPhone

**Comment by zigang93** [comment] 2019-11-09 12:58
so where do I change the display name?? in Xcode or project folder?

**Comment by tanutapi** [comment] 2019-11-11 05:09
> so where do I change the display name?? in Xcode or project folder?

Make a change into "Info.plist" and don't touch "Display Name".

**Comment by jmagman** [comment] 2019-12-11 23:51
I'm about to put out a pull request with to change the default iOS project template:
- Build setting PRODUCT_NAME will default to the pubspec.yaml name. The instructions at https://flutter.dev/docs/deployment/ios#review-xcode-project-settings Xcode 11 General > Display Name change this build setting.  
- Info.plist CFBundleName will be `$(PRODUCT_NAME)`.  This is the default in a new Xcode project, and the Flutter macOS Info.plist template.  Previously, the iOS Info.plist CFBundleName defaulted to the pubspec name.
- Your built .app bundle will be named whatever Xcode reports to be the `FULL_PRODUCT_NAME`
```
cd ios
/usr/bin/xcodebuild -project Runner.xcodeproj -scheme Runner -showBuildSettings 
...
    FULL_PRODUCT_NAME = My App.app
...
```
- `flutter run` will install `build/ios/iphoneos/<FULL_PRODUCT_NAME>.app.`

**Comment by jmagman** [comment] 2019-12-12 02:06
Actually, this is a duplicate of https://github.com/flutter/flutter/issues/41793.

**Closed by jmagman** 2019-12-12 02:06 UTC
Labels: severe: regression, t: xcode, tool

**Comment by NickalasB** [comment] 2020-03-22 21:29
Also had this problem where the iOS version of my app would show up on a device like: `my_app_name` 

@tanutapi's  [solution](https://github.com/flutter/flutter/issues/43877#issuecomment-552295336) worked for me:

Inside `ios/Runner/Info.plist` change this
```
	<key>CFBundleName</key>
	<string>my_app_display_name</string>
```

```
	<key>CFBundleName</key>
	<string>My App Display Name</string>
```
