### ISSUE TITLE
TextField selection start does not move

### ISSUE THREAD

**Issue by louisdeveseleer** [flutter/flutter#112488] opened 2022-09-27 17:22 UTC
## Steps to Reproduce

- Create a TextField with multiline enabled (`maxLines: null`).
- Run on the Web.
- Try to select the text, then reselect another portion of the text.
- Only the end cursor of the selection moves, the start cursor of the selection stays static (unless double-clicking a word).
- Sometimes it works fine, sometimes it does not - seems to be a bit random. Running the screen video capture tool on MacOS while selecting the text seems to make it not work most of the time, for some reason.

**Expected results:**
Same behavior as with a single line TextField.

https://user-images.githubusercontent.com/59314108/192592913-2bf95045-e777-4765-8c90-1844d58f3f7a.mov

**Actual results:**
Selection is sometimes buggy: the starting point of the selection is not updating correctly.

https://user-images.githubusercontent.com/59314108/192593195-2d7f8254-ea31-4a30-a172-e275be39e6e6.mov

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          alignment: Alignment.center,
          padding: const EdgeInsets.all(16),
          child: const TextField(
               maxLines: null,
              ),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-US)
    • Flutter version 3.3.2 on channel stable at /Users/louisdeveseleer/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (13 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/louisdeveseleer/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • A96E2EDD-0CD6-404E-95E9-C2C624608DC7 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2022-09-28 07:49
Hi @louisdeveseleer, thanks for filing the issue. But I can not reproduce the issue on the latest `stable` and `master` channels even after trying several times.

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/192717804-21cedd48-ecf9-4390-a667-278093197477.mov


</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.2 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.4.0-33.0.pre.32, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.4.0-33.0.pre.32 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7ce121fed9 (89 minutes ago), 2022-09-27 21:40:12 -0400
    • Engine revision 46009cbe3d
    • Dart version 2.19.0 (build 2.19.0-247.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

Did you select the text by trackpad or mouse? Could retry on another website that contains a multiline TextField (maybe in this Github's comment editor)? This is to check if the peripheral device is working properly (sorry if that's incorrect).

Also, could you please retry with `HTML` renderer? It will be great if you can try on `master` channel too. Thanks!

**Comment by louisdeveseleer** [comment] 2022-09-28 13:36
Hey thanks for your answer.
- Selection was done using a mouse. I get the same result with the trackpad. The issue was noted also by our users, which was the initial trigger for us to look into this.
- No issue at all with the Github's comment editor.
- I am getting exactly the same buggy behavior with `flutter run -d chrome --web-renderer html` as with `flutter run -d chrome --web-renderer canvaskit`
- Same result again with the `master` channel as with the `stable`

Have you tried doing the text selection while having the MacOS native screen video capture recording? It's the best way to make it not work for me, although it also happens sometimes without it.

**Comment by huycozy** [comment] 2022-09-29 09:28
@louisdeveseleer 
>Have you tried doing the text selection while having the MacOS native screen video capture recording?

Yes, I did it with the [above demo video](https://github.com/flutter/flutter/issues/112488#issuecomment-1260520378) (use QuickTime Player)

My colleagues tried to reproduce this issue and had the same behavior as you described on his Mac M1 (while I'm using a Mac Intel chip). And there is no special log from the console.

<details>
<summary>Demo (Mac M1)</summary>

https://user-images.githubusercontent.com/104349824/192994051-5810d9ab-554e-4359-9142-25cceed51428.mov

</details>


Labeling this issue for further investigation from the team! Thank you!

**Comment by louisdeveseleer** [comment] 2022-09-29 12:50
Yes I also have a Mac M1! Thanks for your help.

**Comment by mdebbar** [comment] 2022-09-30 15:08
I wasn't able to reproduce this issue on my M1 Macbook Pro. Unfortunately, there isn't much I can do without a repro.

From the videos in this issue, it looks like the text field is behaving as if the `Shift` is key is pressed. I'm not sure why that would be the case.

For those who were able to reproduce it, could you try running the app as a macOS native app instead of web? Do you see the same issue?

**Comment by louisdeveseleer** [comment] 2022-10-01 13:36
@mdebbar I am away with no access to my computer until Tuesday, I'll test what you suggested then and let you know.

**Comment by louisdeveseleer** [comment] 2022-10-05 13:04
@mdebbar  The issue does not appear on macOS for me, only on Web.

It is indeed similar to what happens when the Shift key is pressed.

Have you tried running the mac screen recording (Shift-Command-5) while selecting the text?

**Comment by bleroux** [comment] 2022-10-06 14:06
While investigating further, I found that this issue is also reproducible on desktop (Mac and Linux on my side).

## Steps to reproduce
- Run the provided code sample.
- Enter some text and select a portion of it.
- Press and hold down the right shift key.
- While holding the shift key, click on another window (the Flutter window will lose the focus).
- Release the shift key (while being outside the Flutter window).
- Click somewhere on the text: the selection will be updated as if the shift key is still pressed.

(FYI, I have updated title and main description to expose those findings).

**Comment by dkwingsmt** [comment] 2022-10-06 19:56
@bleroux Thank you. I think option 2 is the best. In fact, I noted it in https://github.com/flutter/flutter/issues/99330 (which apparently hasn't been done yet.) The biggest part of this change would be to figure out how to listen to window focusing/unfocusing, which isn't a mechanism of the current flutter engine. In fact, IIRC focusing/unfocusing callback is part of the "desktop lifecycle" project. We'd very happy if you can help us with it. (cc @cbracken Do we have a issue for it?)

Option 1 is also what we eventually would like to do, but I don't think it solves this problem in a pretty way. It will require fetching that information for every pointer down.

**Comment by bleroux** [comment] 2022-10-07 13:39
@dkwingsmt Many thanks for your insights and especially for pointing out https://github.com/flutter/flutter/issues/99330 :+1: 

While analyzing this deeper, I would like to have your opinion on solution 3 because:
- Modifier keys states are directly available for mouse events on the 4 targeted platforms where this issue is reproducible (Linux, Mac, Windows, Web, see 'reference 1' links below).
- There are use cases where keyboard modifier keys states are interesting without the window gaining focus. For instance, with any Chrome windows (using the mouse wheel on an unfocused Chrome window scrolls the content. If the shift key is pressed, using the mouse wheel on an unfocused window will zoom in/zoom out).
- With multi-window support in work, there are probably new use cases where passing the modifier keys states with mouse events will be interesting.
- Flutter `PointerEvent` was designed when mobile platforms were the only supported platforms. Now that desktop and web are supported it makes sense to align Flutter mouse events to what is done in many desktop and web UI toolkits (see 'reference 2' below).
- Adding one (or more) optional parameter to `PointerEvent` won’t be a breaking change (as I feared in my previous comment).
- Solution 2 (listening to window focusing/unfocusing) will be an interesting addition to the framework. But, it will probably rely on the native mouse event to get the modifiers keys state (so on the engine side, it will be solution 3 + more work to try to get it right on each platform + probably less accuracy than solution 3).


_Reference 1_: supported platforms mouse events field to get modifiers state:

- **MacOS**: https://developer.apple.com/documentation/appkit/nsevent/modifierflags - https://developer.apple.com/documentation/appkit/nsevent/1532495-mouseevent
- **GTK**: https://api.gtkd.org/gdk.c.types.GdkEventButton.state.html
- **Win32**: https://learn.microsoft.com/fr-fr/windows/win32/inputdev/wm-lbuttondown?redirectedfrom=MSDN (MK_SHIFT, MK_CONTROL, etc).
- **Web**: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/shiftKey

_Reference 2_: mouse event modifiers state field for some UI Toolkits:

- **Swing/AWT**: https://docs.oracle.com/javase/7/docs/api/java/awt/event/InputEvent.html#SHIFT_DOWN_MASK
- **SWT**: https://download.eclipse.org/rt/rap/doc/2.0/guide/reference/api/org/eclipse/swt/events/MouseEvent.html#stateMask
- **Qt**: https://doc.qt.io/qt-6/qmouseevent.html#QMouseEvent-4 - https://doc.qt.io/qt-6/qt.html#KeyboardModifier-enum

**Comment by mdebbar** [comment] 2022-10-07 13:41
@bleroux thanks for helping with this issue!

@dkwingsmt On the web, listening to window focus/unfocus is easy. But getting keyboard state at a random point in time isn't possible. So options 1 and 2 are out for web.

Option 3 is actually how the web works. `MouseEvent` (and `TouchEvent`) contain properties (and methods) to determine the current state of modifier keys (e.g. [`getModifierState`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/getModifierState), [`ctrlKey`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/ctrlKey)).

@bleroux 
> but that sounds like a huge breaking change and it mixes different concerns

**Breaking change**: We can make the keyboard state information optional in pointer events. 
**Mixes different concerns**: I don't think so. Both keyboard and mouse are input devices, they are the same concern. And they are used in combination to perform certain actions (e.g. cmd+click). So at some point, Flutter will have to support such shortcuts too.

**Comment by mdebbar** [comment] 2022-10-07 14:12
@bleroux great analysis! Thanks for putting it together. I agree with everything you said.

**Comment by dkwingsmt** [comment] 2022-10-07 18:07
@bleroux Thanks so much for you research, analysis and writeup, and @mdebbar for your insight! I think it's a good idea.

Although first, I'm very hesitant on adding keyboard states to `PointerEvent` because:
1. The extent that key states are available vary from platform to platform (e.g. Win32 only supports Ctrl and Shift).
1. It's confusing to have keyboard states on pointer event.
1. `PointerEvent` already have way too many properties.

That being said, I suggest synchronizing key states from pointer events on the engine side.
* When the engine receives a pointer event, extract its keyboard state, and send it to the keyboard manager.
* The keyboard manager synchronizes with the states, dispatch synthesized events as needed.
* If this procedure is done synchronously, the synthesized key events will arrive at the framework before the pointer events, thus correctly affecting the next pointer event.

Notes:
* This works the best for the hardware keyboard system.
* If we really want to support the (to be deprecated) raw keyboard system, the raw keyboard manager can add the key state to the raw key data JSON payload, and process synchronization on the framework side.

**Comment by bleroux** [comment] 2022-10-10 14:58
@dkwingsmt Great! I will start to work on this. I will first target only one platform (Web) with a WIP PR, this way we have a foundation for further discussions. I need to dig into the code to understand the full implications (especially "The keyboard manager synchronizes with the states").

I would be happy to work on #87391 too. If it’s ok for you, I will work on it after making progress here.

**Comment by dkwingsmt** [comment] 2022-10-10 17:08
Sure! Thank you so much for volunteering. Feel free to find me on discord for questions.

**Closed** 2022-10-21 06:02 UTC
Labels: a: text input, framework, engine, platform-web, a: desktop, has reproducible steps, P4, found in release: 3.3, found in release: 3.4
