### ISSUE TITLE
Can't limit Material Dropdown Overlay height!

### ISSUE THREAD

**Issue by Ali-fadaei** [flutter/flutter#75117] opened 2021-02-01 07:00 UTC
I'm using flutter dev channel for develop windows app.
material's built-in **dropdownButton** widget doesn't have height argument or anything helpful for control overlay height when item count increase.
it's necessary for developing app's for desktop or web platforms. 
![Screenshot (6)](https://user-images.githubusercontent.com/46972583/106425031-7105f100-6478-11eb-8534-f961d566e52c.png)

**Comment by iapicca** [comment] 2021-02-01 07:50
duplicate of https://github.com/flutter/flutter/issues/23865

**Comment by darshankawar** [comment] 2021-02-01 12:09
Closing this as duplicate of https://github.com/flutter/flutter/issues/23865. Please follow-up in original issue for updates and any questions.

**Closed by darshankawar** 2021-02-01 12:09 UTC
