### ISSUE TITLE
Post-submit Cirrus `tool_tests-integration-macos` timeout failure

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#43793] opened 2019-10-30 03:40 UTC
## Description
Cirrus post-submit test failed on timeout for `tool_tests-integration-macos`. This is probably a flake.

https://cirrus-ci.com/task/4602004957036544?command=main#L1137

## Logs 
```
17:49 +22 -1: test/integration.shard/hot_reload_test.dart: breakpoints are hit after hot reload [E]                                                                                                    
  TimeoutException after 0:15:00.000000: Test timed out after 15 minutes.
  package:test_api  Invoker._onRun.<fn>.<fn>.<fn>
17:51 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
17:52 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
17:53 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
17:54 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
17:55 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
17:56 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
17:57 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
17:58 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
17:59 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:00 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:01 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:02 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:03 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:04 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:05 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:06 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:07 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:08 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:09 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:10 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:11 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:12 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:13 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:14 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:15 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:16 +22 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:16 +23 -1: test/integration.shard/hot_reload_test.dart: hot reload doesn't reassemble if paused                                                                                                     
18:16 +23 -1: Some tests failed.                                                                                                                                                                       
▌19:05:04▐ ELAPSED TIME: 22min 36.212s for ../../bin/cache/dart-sdk/bin/pub run build_runner test --build-filter=test/integration.shard/*.dill --build-filter=test/integration.shard/**/*.dill -- -rcompact -j2 --no-color test/integration.shard in packages/flutter_tools
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ERROR: Last command exited with 1 (expected: zero).
Command: ../../bin/cache/dart-sdk/bin/pub run build_runner test --build-filter=test/integration.shard/*.dill --build-filter=test/integration.shard/**/*.dill -- -rcompact -j2 --no-color test/integration.shard
Relative working directory: packages/flutter_tools
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by jonahwilliams** [comment] 2019-10-30 04:41
Duplicate of https://github.com/flutter/flutter/issues/43464

**Closed by jonahwilliams** 2019-10-30 04:41 UTC
Labels: team: flakes
