### ISSUE TITLE
Accessing hidden method Landroid/util/MathUtils;->dist

### ISSUE THREAD

**Issue by Herryjoeson** [flutter/flutter#28637] opened 2019-02-28 09:38 UTC
1. When I initialize the project, I use listview and scroll through the error log that keeps appearing under the log.

## Logs
```
      Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex).
```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
    • Flutter version 1.2.1 at /Project/flutter
    • Framework revision 8661d8aecd (13 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/joeson/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0
```

**Comment by Hixie** [comment] 2019-03-06 00:29
@Herryjoeson Please, if possible, provide a reduced test case so that we can reproduce it. There isn't sufficient information in this report for us to be able to determine the cause of the issue you are reporting. Thanks!

**Comment by sosospicy** [comment] 2019-03-14 03:49
@Hixie  It's not difficult to reproduce this problem on flutter version `Channel master, v1.3.9-pre.17`. In terminal , just run `flutter create demo` then `cd demo` and then `flutter run`, scroll on screen,  you'll get flush error log in the terminal:
```
W/om.example.dem(19063): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
E/ContentCatcher(19063): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
```
I tested the demo on version `Channel master, v1.3.10-pre.37`  just now, nothing changed.

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.3.10-pre.37, on Mac OS X 10.14.3 18D109, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.1)
[✓] Connected device (2 available)
```

**Comment by pinyin** [comment] 2019-03-16 09:28
Same error on my Mi MAX3 phone. After updating `targetSdkVersion`  in './android/app/build.gradle' from `28` to `27`, the error seems to go away.
This issue seems to be mainly reported by Chinese developers, so this may be a system bug or compatibility issue with some Chinese manufacturer's distribution of Android. Sadly I don't have enough experience to prove that.
Have you tried reproducing this issue in a customized Android distribution, such as MIUI 10?

**Comment by dhaval0122** [comment] 2019-07-25 13:00
Hello I have Same Issue in MI Device which actually does't have any GMS Services like Google Play etc. 

Model: RedMI 7A
Android Version: 9
Android Security Patch level: 2019-05-01

**Flutter Application**
```
compileSdkVersion 28
defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        //applicationId "hkflutter.vc.com.flutterapp"
        multiDexEnabled true
        applicationId "com.ecu.b"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters 'x86','armeabi-v7a'
        }
    }
```

**Flutter Doctor:**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.13.6 17G7024,
    locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)


**Step to reproduce:**

I have used TextFormField, when i type some character than try to delete one of them at that time app got crash. 

---------------------------------
**Logs**


[LOGCAT]=07-25 20:34:42.645 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:42.645 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:42.656 E/checkPermission(28359): checkPermission
07-25 20:34:42.658 I/flutter (28359): ===checkPermission=====true
07-25 20:34:42.917 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:42.917 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.053 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.053 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.062 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.062 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.070 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.071 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.080 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.080 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.089 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.089 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.098 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.098 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.107 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.107 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.116 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.116 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.129 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.129 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.138 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.139 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.245 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.245 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.253 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.253 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.263 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.264 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.270 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.271 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.282 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.282 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.289 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.290 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.299 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.300 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.311 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.311 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.320 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.320 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:43.614 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:43.615 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:44.239 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:44.239 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:44.248 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:44.248 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:44.257 W/com.ecu.bas(28359): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
07-25 20:34:44.257 E/ContentCatcher(28359): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
07-25 20:34:48.256 D/AndroidRuntime(28359): Shutting down VM
--------- beginning of crash
07-25 20:34:48.257 E/AndroidRuntime(28359): FATAL EXCEPTION: main
07-25 20:34:48.257 E/AndroidRuntime(28359): Process: com.ecu.basf, PID: 28359
07-25 20:34:48.257 E/AndroidRuntime(28359): java.lang.IndexOutOfBoundsException: getChars (0 ... 8) ends beyond length 7
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1321)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:1202)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.text.SpannableStringBuilder.getTextRunCursor(SpannableStringBuilder.java:1574)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.graphics.Paint.getTextRunCursor(Paint.java:2503)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.text.TextLine.getOffsetBeforeAfter(TextLine.java:788)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.text.TextLine.getOffsetToLeftRightOf(TextLine.java:631)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.text.Layout.getOffsetToLeftRightOf(Layout.java:1733)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.text.Layout.getOffsetToLeftOf(Layout.java:1679)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.text.Selection.extendLeft(Selection.java:392)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at io.flutter.plugin.editing.InputConnectionAdaptor.sendKeyEvent(InputConnectionAdaptor.java:152)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:436)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.os.Looper.loop(Looper.java:201)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at android.app.ActivityThread.main(ActivityThread.java:6864)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at java.lang.reflect.Method.invoke(Native Method)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
07-25 20:34:48.257 E/AndroidRuntime(28359): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
07-25 20:34:48.261 E/ACRA    (28359): ACRA caught a IndexOutOfBoundsException for com.ecu.basf
07-25 20:34:48.261 E/ACRA    (28359): java.lang.IndexOutOfBoundsException: getChars (0 ... 8) ends beyond length 7
07-25 20:34:48.261 E/ACRA    (28359): 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1321)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:1202)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.text.SpannableStringBuilder.getTextRunCursor(SpannableStringBuilder.java:1574)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.graphics.Paint.getTextRunCursor(Paint.java:2503)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.text.TextLine.getOffsetBeforeAfter(TextLine.java:788)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.text.TextLine.getOffsetToLeftRightOf(TextLine.java:631)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.text.Layout.getOffsetToLeftRightOf(Layout.java:1733)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.text.Layout.getOffsetToLeftOf(Layout.java:1679)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.text.Selection.extendLeft(Selection.java:392)
07-25 20:34:48.261 E/ACRA    (28359): 	at io.flutter.plugin.editing.InputConnectionAdaptor.sendKeyEvent(InputConnectionAdaptor.java:152)
07-25 20:34:48.261 E/ACRA    (28359): 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:436)
07-25 20:34:48.261 E/ACRA    (28359): 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.os.Looper.loop(Looper.java:201)
07-25 20:34:48.261 E/ACRA    (28359): 	at android.app.ActivityThread.main(ActivityThread.java:6864)
07-25 20:34:48.261 E/ACRA    (28359): 	at java.lang.reflect.Method.invoke(Native Method)
07-25 20:34:48.261 E/ACRA    (28359): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
07-25 20:34:48.261 E/ACRA    (28359): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)``


Hope it help to regenerate issue. I am glad to hear from you.

**Comment by iapicca** [comment] 2019-11-06 16:08
Hi @Herryjoeson 
I'm closing this issue as it refer to an older version of Flutter.
If you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Closed by iapicca** 2019-11-06 16:08 UTC
Labels: f: scrolling, waiting for customer response, ▣ platform-android

**Comment by lhcdims** [comment] 2020-03-29 13:51
same problem in Flutter v1.15.17 beta channel:

Although the app can keep running, unstoppable error messages in the log is annoying.  

Connect Device: Xiao Mi 9
Android Version: 9.0


Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.15.17, on Linux, locale zh_CN.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!
```


Repeated Error Message:

```
W/bot.v2rayuser0(12052): Accessing hidden method Landroid/util/MathUtils;->dist(FFFF)F (dark greylist, linking)
E/ContentCatcher(12052): Interceptor : dispatchTouchEvent-Error: java.lang.NoSuchMethodError: No static method dist(FFFF)F in class Landroid/util/MathUtils; or its super classes (declaration of 'android.util.MathUtils' appears in /system/framework/framework.jar!classes2.dex)
```


If possible, please re-open this issue.

**Comment by iapicca** [comment] 2020-04-03 09:19
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
