### ISSUE TITLE
Text selection tooltip overflow in case of scroll outside of screen.

### ISSUE THREAD

**Issue by RomanKapshuk** [flutter/flutter#138341] opened 2023-11-13 11:36 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run code snippet
2. Fill any textField with text
3. scroll until the tooltip is out of the screen

### Expected results

The tooltip was dismissed at least on the edge of the status bar. 

### Actual results

The tooltip is still intact while scrolling.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class AppWidget extends StatelessWidget {
  const AppWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My Smart App',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: HomeWidget(),
    );
  }
}

class HomeWidget extends StatelessWidget {
  HomeWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            children: [
              ...List<Widget>.generate(
                20,
                (index) => Container(
                  color: Colors.red,
                  margin: const EdgeInsets.only(top: 150),
                  child: const TextField(),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/16819254/02722a92-b67d-4de6-ade7-224b2537b971

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.6 22G120 darwin-arm64, locale en-UA)
    • Flutter version 3.13.6 on channel stable at /Users/user/fvm/versions/3.13.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (7 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Users/user/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (2 available)
    • iPhone 15 Pro Max (mobile) • 059BEAA6-1C70-49FF-84B4-3506B9F6DFBC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-11-14 08:26
Hi @RomanKapshuk, this is a duplicate of https://github.com/flutter/flutter/issues/89570 which was closed in favour of https://github.com/flutter/flutter/issues/13182. 

Kindly follow up in the original issue for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2023-11-14 08:26 UTC
Labels: in triage
