### ISSUE TITLE
firebase_auth

### ISSUE THREAD

**Issue by DiegoEros** [flutter/flutter#73639] opened 2021-01-09 12:50 UTC
Hi everyone, please could you please help me with the next error (Thanks a lot):

------------------------------------------------------------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:profileRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: E:\ANDROID\PROYECTOS\rodapp\build\app\intermediates\flutter\profile\libs.jar.
         > Transform's input file does not exist: E:\ANDROID\PROYECTOS\rodapp\build\app\intermediates\flutter\profile\libs.jar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 54s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      55,7s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin firebase_auth...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    2,2s

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\ANDROID\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.18.4+1\android\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating root project 'firebase_auth'.
> Could not find the firebase_core FlutterFire plugin, have you added it as a dependency in your pubspec?

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin firebase_auth could not be built due to the issue above.
--------------------------------------------------------------------------------------------------------

line 26 code in file build.gradle:

def firebaseCoreProject = findProject(':firebase_core')
if (firebaseCoreProject == null) {
    **throw new GradleException('Could not find the firebase_core FlutterFire plugin, have you added it as a dependency in your pubspec?')**
} else if (!firebaseCoreProject.properties['FirebaseSDKVersion']) {
    throw new GradleException('A newer version of the firebase_core FlutterFire plugin is required, please update your firebase_core pubspec dependency.')
}

def getRootProjectExtOrCoreProperty(name, firebaseCoreProject) {
    if (!rootProject.ext.has('FlutterFire')) return firebaseCoreProject.properties[name]
    if (!rootProject.ext.get('FlutterFire')[name]) return firebaseCoreProject.properties[name]
    return rootProject.ext.get('FlutterFire').get(name)
}

**Comment by iapicca** [comment] 2021-01-09 18:34
@DiegoEros
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by TahaTesser** [comment] 2021-01-11 08:18
Hi @DiegoEros 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-11 08:18 UTC

**Comment by DiegoEros** [comment] 2021-01-11 11:48
while building the app after the latest update, but then I disabled the lint task in android/app/build.gradle

lintOptions {
    disable 'InvalidPackage'
    checkReleaseBuilds false
}
and this worked for me.
Thanks a lot!!

**Comment by DiegoEros** [comment] 2021-01-11 11:49
> Hi @DiegoEros
> From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
> Closing, as this isn't an issue with Flutter itself.
> If you disagree, please write in the comments,
> providing your `flutter doctor -v`, your `flutter run -v`, your `pubspec.yaml`
> a minimal reproducible code sample that does not use 3rd party plugins,
> and I will reopen it.
> Thank you

Yes, thanks
