### ISSUE TITLE
shared preference displays the old value in release mode 

### ISSUE THREAD

**Issue by Shakhboz95** [flutter/flutter#74790] opened 2021-01-27 07:30 UTC
P.S: its not duplicate, no solution is found in community

Shared pref value in release mode shows the old value sometimes,
during the my testing it stores the value and can get the new value that I stored just to make sure but after closing application and opening it again, sometimes it shows the the old value, which I stored befoe new one.

here is example of my code:
to store and get value:
```dart
void setToken(String userToken) async {
    var sharedPreferences = await shared;
    sharedPreferences.setString("$_token", userToken);
    print("token is: " +sharedPreferences.getString("$_token").toString());
  }     
  
  Future<String> getToken() async {
    var sharedPreferences = await shared;
    sharedPreferences.reload();
    String value = sharedPreferences.getString("$_token");
    print("your token: $value");
    return value;
  }
  ```
  The result message:
  1. in first store ( getting first token):
                  token is: eyJhbG.....Ai-A
  2. Second token storing:
                  token is: eyJhbG....oKk
                  
  And after reopening app, I get the 1st token
                  your token:  eyJhbG.....Ai-A

**Comment by TahaTesser** [comment] 2021-01-27 08:42
Hi @Shakhboz95 
Can you please provide your `flutter doctor -v`, is the issue on Android or iOS device? 
Thank you

**Comment by Shakhboz95** [comment] 2021-01-27 09:02
✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale ru-UZ)
    • Flutter version 1.22.5 at /Users/sitora/src/flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/sitora/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • User’s iPhone (mobile) • a7cf54c4f69a83f07907bc6bfe4c490dd54a4099 • ios • iOS 12.4.9
    • iPhone 11 Pro (mobile) • C0D753D8-B108-4FA2-A21B-A7CA0AE03A19     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

**Comment by GaspardMerten** [comment] 2021-01-27 09:06
Shouldn't you await the setString method? (I don't think it is the cause of your issue but I always find it dangerous to not await a future, if you want to mark it as "on purpose ", there is the unawaited method from the pedantic package (unawaited(myFuture())!

**Comment by Shakhboz95** [comment] 2021-01-27 09:15
Actually it sets the string to shared, because on print method I am getting the same value that I stored, but interesting thing is after reopening it shows the old value

**Comment by TahaTesser** [comment] 2021-01-28 08:12
Hi @Shakhboz95 
Here I created a minimal runnable code sample to reproduce the in a release mode, tried on Android and iOS with the latest `shared_preferences: ^0.5.12+4`


<details>
<summary>code sample</summary>

```dart
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SharedPreferences Demo',
      home: SharedPreferencesDemo(),
    );
  }
}

class SharedPreferencesDemo extends StatefulWidget {
  SharedPreferencesDemo({Key key}) : super(key: key);

  @override
  SharedPreferencesDemoState createState() => SharedPreferencesDemoState();
}

class SharedPreferencesDemoState extends State<SharedPreferencesDemo> {
  Future<SharedPreferences> shared = SharedPreferences.getInstance();

  String _token = "my_token";

  void setToken(String userToken) async {
    var sharedPreferences = await shared;
    await sharedPreferences.setString("$_token", userToken);
    print("token is: " + sharedPreferences.getString("$_token").toString());
    setState(() {});
  }

  Future<String> getToken() async {
    var sharedPreferences = await shared;
    sharedPreferences.reload();
    String value = sharedPreferences.getString("$_token");
    print("your token: $value");
    return value;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("SharedPreferences Demo"),
      ),
      body: Center(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          FutureBuilder<String>(
              future: getToken(),
              builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
                switch (snapshot.connectionState) {
                  case ConnectionState.waiting:
                    return const CircularProgressIndicator();
                  default:
                    if (snapshot.hasError) {
                      return Text('Error: ${snapshot.error}');
                    } else {
                      return Text("your token: ${snapshot.data ?? ""}");
                    }
                }
              }),
          ElevatedButton(
            onPressed: () => setToken("token2021"),
            child: Text("Set Token: token2021"),
          ),
          ElevatedButton(
            onPressed: () => setToken("token2077"),
            child: Text("Set Token: token2077"),
          ),
        ],
      )),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (5 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.3

! Doctor found issues in 1 category.
```

</details>



Thank you

**Comment by Shakhboz95** [comment] 2021-01-28 10:48
Hello @TahaTesser 

so you mean, it works well, right?

Actually it happens sometimes, shows the data stored, but sometimes during fetching the value, shows the old value

**Comment by TahaTesser** [comment] 2021-01-28 13:16
Hi @Shakhboz95 
Is it only reproducing on `iOS 12.4.9` device you've? Can you reproduce it on the simulator? 
It is working for me?

**Comment by Shakhboz95** [comment] 2021-01-29 05:10
Hello @TahaTesser 
no, for simulators working fine.
Only in real devices are having this issue, especially on IoS platform(tested 3 devices with different ios version), I can find only in release mode, for debugging it is ok

**Comment by TahaTesser** [comment] 2021-01-29 09:29
Hi @Shakhboz95 
I tried the physical device again today, wasn't able to reproduce the issue. 
Can you please reproduce the using the minimal code sample I created and provide a screen recording how you're reproducing it? 


<details>
<summary>code sample</summary>

```dart
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SharedPreferences Demo',
      home: SharedPreferencesDemo(),
    );
  }
}

class SharedPreferencesDemo extends StatefulWidget {
  SharedPreferencesDemo({Key key}) : super(key: key);

  @override
  SharedPreferencesDemoState createState() => SharedPreferencesDemoState();
}

class SharedPreferencesDemoState extends State<SharedPreferencesDemo> {
  Future<SharedPreferences> shared = SharedPreferences.getInstance();

  String _token = "my_token";

  void setToken(String userToken) async {
    var sharedPreferences = await shared;
    await sharedPreferences.setString("$_token", userToken);
    print("token is: " + sharedPreferences.getString("$_token").toString());
    setState(() {});
  }

  Future<String> getToken() async {
    var sharedPreferences = await shared;
    sharedPreferences.reload();
    String value = sharedPreferences.getString("$_token");
    print("your token: $value");
    return value;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("SharedPreferences Demo"),
      ),
      body: Center(
          child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          FutureBuilder<String>(
              future: getToken(),
              builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
                switch (snapshot.connectionState) {
                  case ConnectionState.waiting:
                    return const CircularProgressIndicator();
                  default:
                    if (snapshot.hasError) {
                      return Text('Error: ${snapshot.error}');
                    } else {
                      return Text("your token: ${snapshot.data ?? ""}");
                    }
                }
              }),
          ElevatedButton(
            onPressed: () => setToken("token2021"),
            child: Text("Set Token: token2021"),
          ),
          ElevatedButton(
            onPressed: () => setToken("token2077"),
            child: Text("Set Token: token2077"),
          ),
        ],
      )),
    );
  }
}
```
</details>



<details>
<summary>flutter doctor -v</summary>

```bash

  ╔════════════════════════════════════════════════════════════════════════════╗
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.                                                   ║
  ║                                                                            ║
  ║ Flutter tool analytics are not sent on the very first run. To disable      ║
  ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
  ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
  ║ event will be sent, and then no further information will be sent by the    ║
  ║ Flutter tool.                                                              ║
  ║                                                                            ║
  ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
  ║ Note: The Google Privacy Policy describes how data is handled in this      ║
  ║ service.                                                                   ║
  ║                                                                            ║
  ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
  ║ crash reports to Google.                                                   ║
  ║                                                                            ║
  ║ Read about data we send with crash reports:                                ║
  ║ https://flutter.dev/docs/reference/crash-reporting                         ║
  ║                                                                            ║
  ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
  ╚════════════════════════════════════════════════════════════════════════════╝

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (6 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>


Thank you

**Comment by Shakhboz95** [comment] 2021-02-01 08:59
Hello @TahaTesser 

your demo is also working for me too. Don't know, why my code is not working sometimes.

Can you please check my pubspec.yaml, maybe there is some conflict is available. Thanks beforehand!
   
   environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  
  flutter_masked_text: ^0.8.0
  firebase_analytics: ^6.0.0

  shared_preferences: ^0.5.12+4
  # sms: ^0.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # sms_autofill: ^1.2.7
  flutter_platform_widgets: ^0.32.5
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^3.2.0
  # core_card_io: ^0.0.2
  sqflite: ^1.3.2+2
  card_scanner: 
    git:
      url: https://github.com/DeadBryam/card-scanner-flutter
      ref: fix-static-framework
  # flutter_screenutil: ^3.1.1
  local_auth: ^0.6.3
  carousel_slider: ^2.3.1
  json_annotation: ^3.0.1
  http: ^0.12.0+4
  flare_flutter: ^2.0.1
  json_serializable: ^3.5.0
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.0
  shimmer: ^1.1.0
  share: ^0.6.4+3
  contacts_service: ^0.3.10
  permission_handler: ^5.0.1+1
  scoped_model: ^1.0.1
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.0
  equatable: 
  flutter_bloc:
  flutter_launcher_icons: ^0.8.0
  flutter_date_pickers: ^0.0.6
  cached_network_image: ^2.0.0
  path_provider: ^1.6.11
  connectivity: ^0.4.9+3
  data_connection_checker: ^0.3.4
  url_launcher: ^5.7.10
  firebase_remote_config: ^0.3.1+1
  package_info: ^0.4.1
  launch_review: ^2.0.0
  printing: ^3.6.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3

**Comment by TahaTesser** [comment] 2021-02-02 07:04
Hi @Shakhboz95 
You seem to be using a lot of third-party packages, unfortunately, I cannot know which one is affecting this. Please isolate a third-party that is causing this and file an issue on their dedicated GitHub. 

Since `shared_preferencees` is working as intended, given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-02-02 07:04 UTC
Labels: in triage

**Comment by itmediacreations** [comment] 2021-02-05 10:53
I had same issue. My solution was to manually clear cache of app and then reinstall it. As if after uinstalling application the prefs values werent deleted, weird. Hope it will help you.
