### ISSUE TITLE
The appearance of items in a dropdown menu vary between the Desktop and web platform

### ISSUE THREAD

**Issue by abineshPalanisamy** [flutter/flutter#119817] opened 2023-02-02 12:48 UTC
**Appearance of items in a dropdown menu may vary between the Desktop and web platform**
 Appearance of items in a dropdown menu get vary between the Desktop and web platform, when the items font size get increasing.

**Expected results**
Both the Windows and web platform give same appearance.

**Simple Sample**
```dart
class _MyHomePageState extends State<MyHomePage> {
  String dropdownValue = 'Dog';
  TextStyle? textStyle =
      const TextStyle(fontSize: 50, fontStyle: FontStyle.italic);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            SizedBox(
              height: 100,
            ),
            DropdownButton<String>(
              value: dropdownValue,
              items: <String>['Dog', 'Cat', 'Tiger', 'Lion']
                  .map<DropdownMenuItem<String>>((String value) {
                return DropdownMenuItem<String>(
                  value: value,
                  child: Text(
                    value,
                    style: textStyle ,
                  ),
                );
              }).toList(),
              onChanged: (String? newValue) {
                setState(() {
                  dropdownValue = newValue!;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
**Actual results**
Appearance of items in a dropdown menu may vary between the Desktop and web platform, when the items font size get increasing.

![image](https://user-images.githubusercontent.com/120440951/216327854-5511b023-495e-48e2-a30e-9d48b8fccb26.png)

**Used Flutter Version**
Channel stable, 3.3.10,

[!] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.4.3)
[√] Android Studio (version 2021.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by exaby73** [comment] 2023-02-02 15:06
Hello @abineshPalanisamy. Looks like you're using a previous release of Flutter. Please upgrade to the latest stable (3.7.1) and confirm if this issue is still reproducible. If so, please provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so that I can verify the issue. Thank you

**Comment by abineshPalanisamy** [comment] 2023-02-03 05:05
Hello @exaby73 . After upgrading the flutter, I am facing the same issue in both web and desktop platform. So kindly provide  solution for this issue.

**Simple Sample**

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String dropdownValue = 'Dog';
  TextStyle? textStyle =
      const TextStyle(fontSize: 50, fontStyle: FontStyle.italic);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            SizedBox(
              height: 100,
            ),
            DropdownButton<String>(
              value: dropdownValue,
              items: <String>['Dog', 'Cat', 'Tiger', 'Lion']
                  .map<DropdownMenuItem<String>>((String value) {
                return DropdownMenuItem<String>(
                  value: value,
                  child: Text(
                    value,
                    style: textStyle ,
                  ),
                );
              }).toList(),
              onChanged: (String? newValue) {
                setState(() {
                  dropdownValue = newValue!;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}

````

**Actual results**
Appearance of items in a dropdown menu may vary between the Desktop and web platform, when the items font size get increasing.

![image](https://user-images.githubusercontent.com/120440951/216327854-5511b023-495e-48e2-a30e-9d48b8fccb26.png)


**Used Flutter Version**
```
[!] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
    • Flutter version 3.7.1 on channel stable at D:\Flutter\flutter
    ! Warning: `dart` on your path resolves to C:\Dart\dart-sdk\bin\dart.exe, which is not inside your current Flutter SDK checkout at
      D:\Flutter\flutter. Consider adding D:\Flutter\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7048ed95a5 (2 days ago), 2023-02-01 09:07:31 -0800
    • Engine revision 800594f1f4
    • Dart version 2.19.1
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update   
      checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0) 
    • Android SDK at C:\Users\AbineshPalanisamy\AppData\Local\Android\sdk        
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.4.3) 
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.4.33205.214
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2486]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by exaby73** [comment] 2023-02-03 07:39
## Triage report

I can reproduce this issue on all desktop and mobile. https://github.com/flutter/flutter/issues/106359 might be related, or might be a regression though I am not sure

<details><summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String dropdownValue = 'Dog';
  TextStyle? textStyle =
      const TextStyle(fontSize: 50, fontStyle: FontStyle.italic);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            const SizedBox(
              height: 100,
            ),
            DropdownButton<String>(
              value: dropdownValue,
              items: <String>['Dog', 'Cat', 'Tiger', 'Lion']
                  .map<DropdownMenuItem<String>>((String value) {
                return DropdownMenuItem<String>(
                  value: value,
                  child: Text(
                    value,
                    style: textStyle ,
                  ),
                );
              }).toList(),
              onChanged: (String? newValue) {
                setState(() {
                  dropdownValue = newValue!;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[!] Flutter (Channel master, 3.8.0-3.0.pre.21, on macOS 13.1 22C65 darwin-arm64, locale en-US)
    • Flutter version 3.8.0-3.0.pre.21 on channel master at /Users/nabeelparkar/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nabeelparkar/fvm/versions/master. Consider adding /Users/nabeelparkar/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f3effce630 (2 hours ago), 2023-02-03 00:07:10 -0500
    • Engine revision e3fe6dade9
    • Dart version 3.0.0 (build 3.0.0-198.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio (version 2022.1)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 109.1.47.186

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by HansMuller** [comment] 2023-02-06 23:52
The DropdownMenu class should replace most DropdownButton use cases. @exaby73 - could you check to see if it has the same problem?

CC @QuncCccccc

**Comment by exaby73** [comment] 2023-02-07 08:01
The dropdown menu still does clip the text when the text is large

<details>
<summary>Code Sample</summary>

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String dropdownValue = 'Dog';
  TextStyle? textStyle =
      const TextStyle(fontSize: 50, fontStyle: FontStyle.italic);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            const SizedBox(
              height: 100,
            ),
            DropdownMenu<String>(
              initialSelection: dropdownValue,
              textStyle: textStyle,
              dropdownMenuEntries: <String>[
                'Dog',
                'Cat',
                'Tiger',
                'Lion',
              ].map<DropdownMenuEntry<String>>((String value) {
                return DropdownMenuEntry<String>(value: value, label: value);
              }).toList(),
              onSelected: (String? newValue) {
                setState(() {
                  dropdownValue = newValue!;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<img width="300" src="https://user-images.githubusercontent.com/50555895/217186085-61c5ab38-b316-47b3-8f20-bf3c287149f2.jpg">

**Comment by QuncCccccc** [comment] 2023-02-07 21:39
> The dropdown menu still does clip the text when the text is large

If we pass the same `textStyle` to the `DropdownMenuEntry.style`, the content will not be clipped. This is mainly because the width of the `TextField` in `Dropdownmenu` is calculated by the content of the menu list.
Also the `width` property can be used to customize the width of `DropdownMenu` if we don't want the default calculation:) 

<details>
<summary>Code Sample</summary>

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String dropdownValue = 'Dog';
  TextStyle? textStyle =
  const TextStyle(fontSize: 50, fontStyle: FontStyle.italic);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            const SizedBox(
              height: 100,
            ),
            DropdownMenu<String>(
              width: 300,
              initialSelection: dropdownValue,
              textStyle: textStyle,
              dropdownMenuEntries: <String>[
                'Dog',
                'Cat',
                'Tiger',
                'Lion',
              ].map<DropdownMenuEntry<String>>((String value) {
                return DropdownMenuEntry<String>(value: value, label: value, style: MenuItemButton.styleFrom(textStyle: textStyle));
              }).toList(),
              onSelected: (String? newValue) {
                setState(() {
                  dropdownValue = newValue!;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<img width="389" alt="Screenshot 2023-02-07 at 1 39 10 PM" src="https://user-images.githubusercontent.com/36861262/217372035-93775da5-b493-4ed4-9e67-563ade672962.png">

**Comment by exaby73** [comment] 2023-02-08 07:45
@QuncCccccc Thanks for that insight :) Since `DropdownMenu` is the suitable replacement for `DropdownButton` and this issue does not reproduce with `DropdownMenu`, I see this issue as invalid. I'll close this issue. If you disagree, please comment and I can reopen it. Thank you

**Closed by exaby73** 2023-02-08 07:45 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.7, found in release: 3.8
