### ISSUE TITLE
Running flutter create with a reserved keyword in org is not escaped

### ISSUE THREAD

**Issue by idragon81** [flutter/flutter#15631] opened 2018-03-16 21:52 UTC
Running the following command 
`flutter create -akotlin --org="in.company.domain" flutter_app`
is problematic.

MainActivity.kt is created with the following package 
package in.company.domain
instead of 
package \`in\`.company.domain

Which results in failed compilation

**Comment by Hixie** [comment] 2018-06-12 21:22
@jonahwilliams I unassigned this from you since it looks like the assignment was stale.

**Comment by zoechi** [comment] 2019-01-22 15:16
Duplicate of #16521
which has more activity

**Closed by zoechi** 2019-01-22 15:16 UTC
Labels: tool
