### ISSUE TITLE
Flutter pub upgrade is not workin

### ISSUE THREAD

**Issue by Mohit020888** [flutter/flutter#66720] opened 2020-09-26 10:58 UTC
I am trying to run flutter doctor and getting the below error 

C:\Src\flutter>flutter doctor
Building flutter tool...
Running pub upgrade...
packages/flutter_tools/lib/executable.dart:35:8: Error: Error when reading 'packages/flutter_tools/lib/src/commands/generate_localizations.dart': The system cannot find the file specified.

import 'src/commands/generate_localizations.dart';
       ^
packages/flutter_tools/lib/src/commands/packages.dart:10:8: Error: Error when reading 'packages/flutter_tools/lib/src/dart/generate_synthetic_packages.dart': The system cannot find the file specified.

import '../dart/generate_synthetic_packages.dart';
       ^
packages/flutter_tools/lib/src/commands/test.dart:14:8: Error: Error when reading 'packages/flutter_tools/lib/src/dart/generate_synthetic_packages.dart': The system cannot find the file specified.

import '../dart/generate_synthetic_packages.dart';
       ^
packages/flutter_tools/lib/src/runner/flutter_command.dart:23:8: Error: Error when reading 'packages/flutter_tools/lib/src/dart/generate_synthetic_packages.dart': The system cannot find the file specified.

import '../dart/generate_synthetic_packages.dart';
       ^
packages/flutter_tools/lib/src/globals.dart:13:8: Error: Error when reading 'packages/flutter_tools/lib/src/base/error_handling_io.dart': The system cannot find the file specified.

import 'base/error_handling_io.dart';
       ^
packages/flutter_tools/lib/src/context_runner.dart:18:8: Error: Error when reading 'packages/flutter_tools/lib/src/base/error_handling_io.dart': The system cannot find the file specified.

import 'base/error_handling_io.dart';
       ^
packages/flutter_tools/lib/src/context_runner.dart:39:8: Error: Error when reading 'packages/flutter_tools/lib/src/ios/iproxy.dart': The system cannot find the file specified.

import 'ios/iproxy.dart';
       ^
packages/flutter_tools/lib/src/ios/devices.dart:32:8: Error: Error when reading 'packages/flutter_tools/lib/src/ios/iproxy.dart': The system cannot find the file specified.

import 'iproxy.dart';
       ^
packages/flutter_tools/lib/src/macos/xcode.dart:24:8: Error: Error when reading 'packages/flutter_tools/lib/src/ios/iproxy.dart': The system cannot find the file specified.

import '../ios/iproxy.dart';
       ^
packages/flutter_tools/lib/src/device.dart:20:8: Error: Error when reading 'packages/flutter_tools/lib/src/base/dds.dart': The system cannot find the file specified.

import 'base/dds.dart';
       ^
Error: Unable to create dart snapshot for flutter tool.

**Comment by amanv8060** [comment] 2020-09-27 09:40
@Mohit020888 try  `flutter clean` after that run the command

**Comment by Mohit020888** [comment] 2020-09-27 11:09
@amanv8060 : thanks for your response but I deleted and downloaded the latest stable version of flutter to fix the issue but now when I am run pub upgrade then I am getting android embedding error as below.
![Android_Embedding_Error](https://user-images.githubusercontent.com/63721227/94363453-d66b5f00-00df-11eb-8e07-196da263e742.PNG)

Does that mean I can no longer build my flutter application without migrating to newer version of Android Embedding ?

**Comment by amanv8060** [comment] 2020-09-27 18:32
@Mohit020888   As i see that you were successfully able to run the `flutter pub get` . So the issue is solved . For the other thing that you asked , it is basically a warning . Your code should work fine i guess. But you should migrate your code , by following the instructions available on the link

**Comment by darshankawar** [comment] 2020-09-28 08:44
@Mohit020888 
Above screenshot shows that your original issue related to `pub upgrade` has been resolved. You may follow the link as suggested per your requirement.
I am going ahead and closing this. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-28 08:44 UTC
