### ISSUE TITLE
Why can I not run on iOS? “The sandbox is not in sync with the Podfile.lock”

### ISSUE THREAD

**Issue by briefness** [flutter/flutter#19257] opened 2018-07-11 10:10 UTC
Problem
I have tried to run on iOS but it threw error but at Android it can work.
```
Logs
Launching lib/main.dart on iPhone X in debug mode...
Starting Xcode build...
Xcode build done.
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    diff: /Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
Could not build the application for the simulator.
Error launching application on iPhone X.
``

Flutter Doctor
[✓] Flutter (Channel dev, v0.3.2, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.3.2 at /Users/Wisit/flutter
    • Framework revision 44b7e7d3f4 (12 days ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/Wisit/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] VS Code (version 1.22.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.11.2

[✓] Connected devices (1 available)
    • iPhone X • 92E4AD04-D69D-4353-BDA3-299CE124A10F • ios • iOS 11.3 (simulator)

• No issues found!

**Comment by zoechi** [comment] 2018-07-11 10:59
Did you try running `pod install` or `pod update` in `ios/`?

**Comment by zoechi** [comment] 2018-07-11 11:00
Your Flutter version `Channel dev, v0.3.2` is quite outdated. 
Please update to the newest `beta` or probably currently better `dev` channel version.

**Comment by briefness** [comment] 2018-07-12 01:51
I have tried to run pod install or pod update  on iOS but it threw error.


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.3 17D47, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] Connected devices
    ! No devices available

**Comment by briefness** [comment] 2018-07-12 01:57
I've tried a lot of things but there's still no solution.

**Comment by zoechi** [comment] 2018-07-12 05:13
What dos `pod --version` print?

**Comment by briefness** [comment] 2018-07-12 09:53
1.5.3

**Comment by zoechi** [comment] 2018-07-12 10:35
One of these might help

- https://stackoverflow.com/questions/17072396/cocoapods-errors-on-project-build
- https://support.layer.com/hc/en-us/articles/204301594-I-m-getting-a-The-sandbox-is-not-in-sync-with-the-Podfile-lock-error-How-do-I-fix-it-
- https://stackoverflow.com/questions/21366549/errorthe-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-res
- https://stackoverflow.com/questions/31738339/the-sandbox-is-not-in-sync-with-the-podfile-lock-ios/35446801

**Comment by briefness** [comment] 2018-07-13 07:32
I don't know why？
I tried everything but there's still no solution.
Do I need to reinstall it？

**Comment by yuminoung** [comment] 2018-07-15 16:35
im having the same problem after adding path provider, now im getting this error on every flutter project even a new created project.

**Comment by briefness** [comment] 2018-07-16 01:50
So do i,but why? Version of the problem？I reinstall flutter but there's still no solution.

**Comment by briefness** [comment] 2018-07-16 03:15
I was also having this problem. I ran flutter channel and saw I was in beta channel. I then ran flutter channel master to switch over. This fixed the problem for me.

**Comment by zoechi** [comment] 2018-07-16 06:32
@briefness thanks for the feedback. 
I'm going to close the issue. If this isn't fixed for others on `dev` or `master` channel, please create a new issue.

**Closed by zoechi** 2018-07-16 06:32 UTC
Labels: severe: crash, tool, ⌺‬ platform-ios

**Comment by GuoZhiQiang** [comment] 2019-04-16 05:38
When I run :`flutter run` or `flutter build ios`. I got this error:
```
Building com.ximalaya.qunfeng.qunfengFlutter for device (ios-release)...
Found saved certificate choice "iPhone Developer: xxxxxx@xx.com (U785VQF42P)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "iPhone Developer: xxxxxx@xx.com (U785VQF42P)"
Starting Xcode build...                                                 
Xcode build done.                                            2.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    diff: /Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Encountered error while building for device.
```
I solved it by  adding the following settings to User-Defined Setting : 

```
PODS_ROOT = ${SRCROOT}/Pods
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
```

But there are some more things you should notice : 
1. Assume that you have run `flutter run`(or `flutter build ios`) successed after doing suggestion above.
2. Then you want to run `flutter build ios`. First, you should remove the Settings `PODS_ROOT = ${SRCROOT}/Pods` and `PODS_PODFILE_DIR_PATH = ${SRCROOT}/.`. Second, run 
  ```
   rm Podfile.lock
   rm -rf Pods/
   pod install
   flutter build ios
  ```
 You will get the error again . Third, adding `PODS_ROOT = ${SRCROOT}/Pods` and  `PODS_PODFILE_DIR_PATH = ${SRCROOT}/.` back again to User-Defined Setting.
3. Run `flutter build ios`.

**Comment by epicquestgames** [comment] 2019-07-05 08:54
This is issue every time I want to run my project on different machine...so annoying.
Only thing which works for me is to create "new" flutter project and import all files inside

**Comment by Stef-GMS** [comment] 2019-07-05 20:46
This helped me, thank you!

**Comment by jamie1192** [comment] 2019-11-12 10:02
I'm still getting this exact problem when I switch between work and home Mac's. Did anyone manage to work out the cause of this?

**Comment by Varun7691** [comment] 2019-11-20 11:15
I just followed the below steps and that worked for me.
1. Podfile already existed in my ios folder.
2. `cd ios`
3. `pod install`
4. `pod update`

Hope this helps someone.

**Comment by sksinghdev** [comment] 2020-07-11 18:33
I just followed the below steps and that worked for me.


cd ios
pod install
pod update

then clean your project and build.

**Comment by webkhushboo** [comment] 2021-02-20 13:09
Its not working for me. I tried all the options but its keep giving the same error 
```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

**Comment by sksinghdev** [comment] 2021-02-22 04:27
@webkhushboo You Just need to Run command 1) Flutter clean  4) update CocoaPods then Flutter run
