### ISSUE TITLE
Flutter web application fails

### ISSUE THREAD

**Issue by billy-rainbow** [flutter/flutter#65674] opened 2020-09-12 03:03 UTC
Using the "default sample" flutter application, the one that just displays a counter that can be incremented by user selection, i have been unable to get it to work using the web interface.

From my system:

```
% flutter run -d chrome

Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                       
10,649ms (!)                                       
Unable to connect to Chrome debug port: 46817
 SocketException: OS Error: Connection refused, errno = 111, address = localhost, port = 43630

% flutter run -d web

Launching lib/main.dart on Web Server in debug mode...
Syncing files to device Web Server...                                   
10,892ms (!)                                       
lib/main.dart is being served at http://localhost:43169
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r" or "R".
^C
```
OS:  Ubuntu 18.04 (bionic)
```
Flutter version: 
Flutter 1.21.0-9.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 81a45ec2e5 (2 weeks ago) • 2020-08-27 14:14:33 -0700
Engine • revision 20a9531835
Tools • Dart 2.10.0 (build 2.10.0-7.3.beta)
```
Firefox: 80.0.1 (64-bit)  Mozilla Firefox for Ubuntu canonical - 1.0

Chrome: Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by Abhishek01039** [comment] 2020-09-12 03:28
Hi @billy-rainbow 
are you calling an API?
Thanks.

**Comment by billy-rainbow** [comment] 2020-09-12 04:04
Abhishek,

i'm just trying to run the default project created when "New Flutter 
Project" is selected in Android Studio. You've surely see the code many 
times, but just to be sure, i've cut & pasted a copy, below.

Thanks for the quick response!  Have a great day,

*/billy rainbow, acs

/*
On 09/11/2020 08:28 PM, Abhishek Ghaskata wrote:
> Hi @billy-rainbow <https://github.com/billy-rainbow>
> are you calling an API?
> Thanks.

main.dart:
=======
import 'package:flutter/material.dart';

void main() {
   runApp(MyApp());
}

class MyApp extends StatelessWidget {

   @override
   Widget build(BuildContext context) {
     return MaterialApp(
       title: 'Flutter Demo',
       theme: ThemeData(
         primarySwatch: Colors.blue,
         visualDensity: VisualDensity.adaptivePlatformDensity,
       ),
       home: MyHomePage(title: 'Flutter Demo Home Page'),
     );
   }
}

class MyHomePage extends StatefulWidget {
   MyHomePage({Key key, this.title}) : super(key: key);

   final String title;

   @override
   _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
   int _counter = 0;

   void _incrementCounter() {
     setState(() {
       _counter++;
     });
   }

   @override
   Widget build(BuildContext context) {
     return Scaffold(
       appBar: AppBar(
         title: Text(widget.title),
       ),
       body: Center(
         child: Column(
           mainAxisAlignment: MainAxisAlignment.center,
           children: <Widget>[
             Text(
               'You have pushed the button this many times:',
             ),
             Text(
               '$_counter',
               style: Theme.of(context).textTheme.headline4,
             ),
           ],
         ),
       ),
       floatingActionButton: FloatingActionButton(
         onPressed: _incrementCounter,
         tooltip: 'Increment',
         child: Icon(Icons.add),
       ),
     );
   }
}

**Comment by iapicca** [comment] 2020-09-12 09:29
possibly related to
https://github.com/flutter/flutter/issues/51198
https://github.com/flutter/flutter/issues/56816

**Comment by billy-rainbow** [comment] 2020-09-13 16:18
Abhishek,

neither of the two incidences appear relevant.

Although i experimented with a few ideas that i got from looking over 
#51198 in detail, the incident involves substantially different usage 
and application than i'm working with.

The other incident, 56816, is pertinent only for Windows-based 
development.  My platform is Linux,  Windows is not involved, so neither 
is WSL.

My problem is only failure to get a very simple application to work with 
flutter's web-based (browser) support.  I.e., "flutter run -d [chrome | 
web]" both fail.  For chrome, the result is error messages and an 
abort.  For Firefox, the console output makes it seem like it's working, 
but nothing ever happens, no Firefox window starts if Firefox is not 
running at the time, and if Firefox is running, nothing changes about 
its state.  (E.g., no new tabs or windows open.)

Any other ideas?

Thanks!  Have a great day,

*/billy rainbow, acs

/*

**Comment by TahaTesser** [comment] 2020-09-14 09:06
Hi @billy-rainbow 
This seems to caused localhost not getting started by your `flutter_tool`, a duplicate of https://github.com/flutter/flutter/issues/53338, based on `SocketException: OS Error: Connection refused` and it fails when using `flutter run -d web` as you mentioned

You can try this workaround https://github.com/flutter/flutter/issues/53338#issuecomment-621348161

<details> 
<summary>logs</summary> 

```bash
Launching lib/main.dart on Web Server in debug mode...
Syncing files to device Web Server...                                   
 6,458ms (!)                                       
lib/main.dart is being served at http://localhost:35791
The web-server device requires the Dart Debug Chrome extension for debugging.
Consider using the Chrome or Edge devices for an improved development workflow.

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r" or "R".


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.2.pre at /home/taha/Code/flutter_beta
    • Framework revision 81a45ec2e5 (3 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.83

• No issues found!


```

</details> 


I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/53338
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-14 09:06 UTC
