### ISSUE TITLE
[video_player] Add onComplete callback

### ISSUE THREAD

**Issue by omartinma** [flutter/flutter#90030] opened 2021-09-14 07:10 UTC
## Use case

Currently we dont have a clear API to know whether the video playing has finished. We can workaround that by checking in the app the duration and current time/frame displayed, but it will not be as accurate as having a callback.

## Proposal
Current proposal is developed [here](https://github.com/flutter/plugins/pull/4318).

Basically whenever VideoEventType.completed the optional callback will be called making more straightforward handling this scenario.

**Comment by stuartmorgan** [comment] 2021-09-14 13:49
> ## Use case
> Currently we dont have a clear API to know whether the video playing has finished.

This is just the inverse phrasing of the solution you have in mind, not a use case. Can you explain the use case for having such an API? I.e., why do you need to know that a video has finished playing?

**Comment by omartinma** [comment] 2021-09-14 18:36
> > ## Use case
> > Currently we dont have a clear API to know whether the video playing has finished.
> 
> This is just the inverse phrasing of the solution you have in mind, not a use case. Can you explain the use case for having such an API? I.e., why do you need to know that a video has finished playing?

I have some videos that needs to be played in a row.
For instance if I have video1, video2. Whenever the video1 finishes it will automatically starts to play video2.

**Comment by stuartmorgan** [comment] 2021-09-15 02:20
> Currently we dont have a clear API to know whether the video playing has finished. We can workaround that by checking in the app the duration and current time/frame displayed, but it will not be as accurate as having a callback.

Can you elaborate on what you mean by not as accurate"? It's not clear to me why we need a second API for getting callbacks when there's already the state listener. If you can't accurately determine that a video is complete from that, it seems like that's a bug that should be fixed rather than worked around with a new API.

**Comment by omartinma** [comment] 2021-09-15 07:08
> > Currently we dont have a clear API to know whether the video playing has finished. We can workaround that by checking in the app the duration and current time/frame displayed, but it will not be as accurate as having a callback.
> 
> Can you elaborate on what you mean by not as accurate"? It's not clear to me why we need a second API for getting callbacks when there's already the state listener. If you can't accurately determine that a video is complete from that, it seems like that's a bug that should be fixed rather than worked around with a new API.

Ok, then could you provide some guidance to know whether a video has finished playing? So far I was testing this:

**Comment by stuartmorgan** [comment] 2021-09-15 14:01
> I just found another issue opened since [2018](https://github.com/flutter/flutter/issues/21929)

Thanks; closing as a duplicate of that issue to consolidate tracking.

> But didnt work as expected because is called more than once

Wouldn't a single boolean in your code be sufficient to address that?

**Closed by stuartmorgan** 2021-09-15 14:01 UTC
Labels: severe: new feature, plugin, waiting for PR to land (fixed), p: first party, p: video_player, proposal, passed first triage
