### ISSUE TITLE
Focus Node with key event not working on web

### ISSUE THREAD

**Issue by arualana** [flutter/flutter#80403] opened 2021-04-14 03:14 UTC
Following code does not work on dartpad

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatefulWidget {
  @override
  _MyWidgetState createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  late FocusNode _focusNode;
  @override
  void initState() {
    super.initState();
    _focusNode = FocusNode(onKey: (node, event) {
      _handleKeyEvents(node, event);
    });
  }

  bool _handleKeyEvents(node, event) {
    if (event.isKeyPressed(LogicalKeyboardKey.arrowDown)) {
      print("Arrow down pressed");
    } else if (event.isKeyPressed(LogicalKeyboardKey.arrowUp)) {
      print("Arrow up pressed");
    }
    return true;
  }

  @override
  Widget build(BuildContext context) {
    return TextField(focusNode: _focusNode);
  }
}
```
I am also having trouble with this locally on web.

The error on web is 

```
Assertion failed: file:///path/to/flutter/packages/flutter/lib/src/widgets/focus_manager.dart:1677:16
result is bool || result is KeyEventResult
"Value returned from onKey handler must be a non-null bool or KeyEventResult, not Null"
```

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

<details>
<summary>Logs</summary>

```
```

```
[✓] Flutter (Channel dev, 2.1.0-12.1.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

```

</details>

**Comment by pedromassangocode** [comment] 2021-04-14 07:20
As the error message says, you must return a non-null bool or KeyEventResult value. So your `onKey` callback must return  something.

```dart
  _focusNode = FocusNode(onKey: (node, event) {
    return _handleKeyEvents(node, event);
  });

```

Closing as working as intended.

**Closed by pedromassangocode** 2021-04-14 07:20 UTC
Labels: in triage
