### ISSUE TITLE
Will Flutter Desktop have Fluent style components in the future?

### ISSUE THREAD

**Issue by xiao-cao-x** [flutter/flutter#95229] opened 2021-12-14 01:54 UTC
Material style is not suitable for Windows, Fluent is more suitable. Has Flutter considered adding a set of Fluent-style Widgets in the future?

**Comment by stuartmorgan** [comment] 2021-12-14 03:06
Duplicate of https://github.com/flutter/flutter/issues/46481

**Closed by stuartmorgan** 2021-12-14 03:06 UTC
