### ISSUE TITLE
Flutter iOS app crashes instantly on install after upgrading from 1.12 to 1.20

### ISSUE THREAD

**Issue by odonc** [flutter/flutter#65078] opened 2020-09-02 07:10 UTC
I just upgraded from Flutter 1.12 to 1.20, my existing app works fine on android sim & device but wont run on iOS sim or device. 

When I click run, it builds, then tries to install on the phone but only gets a white screen flash for a second before closing down. 

Also i can run a newly created flutter app ok on iOS, there must be something wrong with my existing app. 

<details>

flutter run
```
Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...
Xcode build done.                                           43.9s
Configuring the default Firebase app...
Configured the default Firebase app __FIRAPP_DEFAULT.
Connecting to the VM Service is taking longer than expected...
Still attempting to connect to the VM Service...
If you do NOT see the Flutter application running, it might have crashed. The device logs (e.g. from adb or XCode) might have more details.
If you do see the Flutter application running on the device, try re-running with --host-vmservice-port to use a specific port known to be available.
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 62503
This was attempt #50. Will retry in 0:00:01.600000.
```

flutter doctor -v
```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.4 19E287, locale en-AU)
    • Flutter version 1.20.2 at /Users/chris/COD/AppActive/flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 45.1.3
    • Dart plugin version 201.7223.43

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • 6631007E-FEBC-4C6A-8D0E-285A4A1F9247 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by pedromassangocode** [comment] 2020-09-02 08:23
Hi @odonc 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by odonc** [comment] 2020-09-02 20:25
"Flutter doctor -v" will work on the others now

**Comment by pedromassangocode** [comment] 2020-09-03 07:12
Hi @odonc 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).

In the title of the issue please add "Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused"

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-03 07:12 UTC
Labels: in triage

**Comment by odonc** [comment] 2020-09-03 07:56
Can I transfer this to flutterfire or do I need to create a new issue there?
