### ISSUE TITLE
`flutter build appbundle` builds app that uses private API's

### ISSUE THREAD

**Issue by stijnster** [flutter/flutter#80715] opened 2021-04-19 11:59 UTC
We have recently updated our app (previously built on flutter 1.x, updated to 2.0.4).

**$ flutter doctor -v**
```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-BE)
    • Flutter version 2.0.4 at /Users/smath/Work/flutter
    • Framework revision b1395592de (12 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/smath/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
```

**Pubspec.yaml**
```
version: 1.1.0+29

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  http: ^0.13.1
  webview_flutter: ^2.0.4
  flutter_svg: ^0.21.0
  package_info: ^2.0.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  firebase_analytics: ^7.1.1
  firebase_crashlytics: ^2.0.0
  firebase_messaging: ^9.1.1
  devicelocale: ^0.4.1
  simple_connectivity: ^0.1.1
  share: '^2.0.1'
  uni_links: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

When we run an appbundle build (`flutter clean; flutter build appbundle`) and upload the bundle to the Google Play Store, the pre-launch report returns with 2 errors and 2 warnings, regarding the use of private API's;

```
Errors;
Non-SDK API Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V
Non-SDK API Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V

Warnings;
Non-SDK API Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B
Non-SDK API Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V
```

I've looked at the stack trace from the pre-launch report and at the bottom I see a reference to `com.google.firebase.crashlytics` (see stack trace below this email).

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V
at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
at java.lang.Class.getDeclaredMethodInternal(Native Method)
at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
at java.lang.Class.getMethod(Class.java:2066)
at java.lang.Class.getMethod(Class.java:1693)
at f.g0.j.e.a(Unknown Source:1)
at f.g0.j.e.a(Unknown Source:7)
at f.g0.j.e.b(Unknown Source:4)
at f.g0.j.e.c(Unknown Source:0)
at f.g0.j.a.a(Unknown Source:23)
at f.g0.f.c.a(Unknown Source:62)
at f.g0.f.c.a(Unknown Source:54)
at f.g0.f.c.a(Unknown Source:178)
at f.g0.f.g.a(Unknown Source:222)
at f.g0.f.g.a(Unknown Source:0)
at f.g0.f.g.a(Unknown Source:22)
at f.g0.f.a.a(Unknown Source:25)
at f.g0.g.g.a(Unknown Source:158)
at f.g0.g.g.a(Unknown Source:6)
at f.g0.e.a.a(Unknown Source:124)
at f.g0.g.g.a(Unknown Source:158)
at f.g0.g.g.a(Unknown Source:6)
at f.g0.g.a.a(Unknown Source:161)
at f.g0.g.g.a(Unknown Source:158)
at f.g0.g.j.a(Unknown Source:48)
at f.g0.g.g.a(Unknown Source:158)
at f.g0.g.g.a(Unknown Source:6)
at f.y.b(Unknown Source:115)
at f.y.j(Unknown Source:31)
at com.google.firebase.crashlytics.d.k.b.a(Unknown Source:10)
at com.google.firebase.crashlytics.d.p.j.d.a(Unknown Source:61)
at com.google.firebase.crashlytics.d.p.d$a.a(Unknown Source:13)
at com.google.firebase.crashlytics.d.p.d$a.a(Unknown Source:2)
at b.b.a.b.i.y.run(Unknown Source:12)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.firebase.crashlytics.d.h.w$a$a.a(Unknown Source:2)
at com.google.firebase.crashlytics.d.h.d.run(Unknown Source:5)
at java.lang.Thread.run(Thread.java:923)
```

**Comment by TahaTesser** [comment] 2021-04-19 12:56
Hi @stijnster 
`crashlytics` is part of `FirebaseExtended/flutterfire`
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-19 12:56 UTC
