### ISSUE TITLE
android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error

### ISSUE THREAD

**Issue by trueinnidhi** [flutter/flutter#94232] opened 2021-11-26 06:40 UTC
Currently app is using both controller.startImageStream() and controller.takePicture();

Camera Plugin version used is 0.8.1+5

There is no issue when there is light.  When I capture picture in low light, camera freezes with below error.

```bash
E/CameraCaptureSession( 2187): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession( 2187): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession( 2187): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2239)
E/CameraCaptureSession( 2187): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1249)
E/CameraCaptureSession( 2187): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:578)
E/CameraCaptureSession( 2187): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1171)
E/CameraCaptureSession( 2187): 	at io.flutter.plugins.camera.Camera.close(Camera.java:1177)
E/CameraCaptureSession( 2187): 	at io.flutter.plugins.camera.Camera$1.onError(Camera.java:252)
E/CameraCaptureSession( 2187): 	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1637)
E/CameraCaptureSession( 2187): 	at android.hardware.camera2.impl.CameraDeviceImpl.lambda$oDs27OTfKFfK18rUW2nQxxkPdV0(Unknown Source:0)
E/CameraCaptureSession( 2187): 	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$oDs27OTfKFfK18rUW2nQxxkPdV0.accept(Unknown Source:8)
E/CameraCaptureSession( 2187): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:278)
E/CameraCaptureSession( 2187): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
E/CameraCaptureSession( 2187): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
E/CameraCaptureSession( 2187): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession( 2187): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession( 2187): 	at android.os.Looper.loop(Looper.java:246)
E/CameraCaptureSession( 2187): 	at android.app.ActivityThread.main(ActivityThread.java:8538)
E/CameraCaptureSession( 2187): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession( 2187): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/CameraCaptureSession( 2187): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/CameraManagerGlobal( 2187): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.gotruein.kiosk API Level 2
```

Tried updating the plugin to 0.9.2+2. Here, it works for controller.takePicture(). 
 But, in controller.startImageStream(), I get a different error  as,

Unable to set property "debug.sf.dequeuebuffer" to "1": connection failed; errno=13 (Permission denied)
E/BufferQueueProducer(27498): [ImageReader-320x240f23m1-27498-7](id:6b6a0000000b,api:4,p:3686,c:27498) waitForFreeSlotThenRelock: timeout

**Comment by mamuseferha** [comment] 2021-11-26 08:55
Hi @trueinnidhi, thank you for filing this issue. 

To clarify, does this happen on a physical device or emulator? 
Can you please update your camera plugin version to the latest to see if the issue persists? `camera: ^0.9.4+5`

If issues persist, please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Related to https://github.com/flutter/flutter/issues/75208 and https://github.com/flutter/flutter/issues/92762

**Comment by alexandreJavaDeveloper** [comment] 2021-11-26 17:03
I have the same issue in emulator with API 31. I didn't try in device.
I am using the latest version `camera: ^0.9.4+5`

**Comment by trueinnidhi** [comment] 2021-11-26 17:52
This happened on Samsung Galaxy A 10 inch tab. 
Android version 11

**Comment by alexandreJavaDeveloper** [comment] 2021-11-26 17:56
My error has a strack trace a bit different. Maybe because of the version of camera library `0.9.4+5?`

`E/CameraCaptureSession(25720): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:507: Camera 0: Error clearing streaming request: Function not implemented (-38)
E/CameraCaptureSession(25720): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1179)
E/CameraCaptureSession(25720): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
E/CameraCaptureSession(25720): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1287)
E/CameraCaptureSession(25720): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
E/CameraCaptureSession(25720): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:790)
E/CameraCaptureSession(25720): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:259)
E/CameraCaptureSession(25720): 	at android.os.Handler.handleCallback(Handler.java:938)`

**Comment by trueinnidhi** [comment] 2021-11-26 18:00
Are you getting this error while using startImageStream or takePicture?

**Comment by alexandreJavaDeveloper** [comment] 2021-11-26 18:02
Using Take picture. I did something here that it changed the error =)
Instead of 
`_initializeControllerFuture = _controller.initialize();`
I did 
`    _initializeControllerFuture = _controller.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    });`

And in dispose method, instead of:
`_controller.dispose();`
I did
`_controller?.dispose();`

I checked in the documentation. Did you try this?

**Comment by mamuseferha** [comment] 2021-11-29 07:40
Hi @trueinnidhi 
There's an open issue addressing the case you described https://github.com/flutter/flutter/issues/92762.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-11-29 07:40 UTC
Labels: in triage
