### ISSUE TITLE
Device disconnected after app crash

### ISSUE THREAD

**Issue by MuhammamdArslanKhan** [flutter/flutter#54348] opened 2020-04-09 10:09 UTC
My device disconnected some times after crash and sometimes without crash, and it happend on all apps building 
```
W/IInputConnectionWrapper(27698): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(27698): endBatchEdit on inactive InputConnection
W/ample.mokoo_do(27698): 0xebadde09 skipped times: 0
F/libc    (27698): Fatal signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0 in tid 27717 (Thread-6), pid 27698 (ample.mokoo_dog)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/j6primeltedd/j6primelte:9/PPR1.180610.011/J610FXXU3BSJ1:user/release-keys'
Revision: '6'
ABI: 'arm'
pid: 27698, tid: 27717, name: Thread-6  >>> com.example.mokoo_dog <<<
signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 0x0
    r0  8f98143c  r1  8f981490  r2  1e3d4ef6  r3  00000008
    r4  8f981570  r5  8ecf3ffe  r6  91a55ac6  r7  1e3d4ef6
    r8  1e3d4ef6  r9  8ec90fae  r10 98326bf6  r11 983267ea
    ip  adf2e3cc  sp  91a55ac6  lr  8ef35871  pc  ade90c80
backtrace:
    #00 pc 00019c80  /system/lib/libc.so (sigsetjmp+128)
    #01 pc 0051e86f  <anonymous:8ea17000>
Lost connection to device.
Exited (sigterm)
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.42.1)
[√] Connected device (1 available)
• No issues found!

**Comment by mraleph** [comment] 2020-04-09 10:14
Duplicate of #27077

**Comment by mraleph** [comment] 2020-04-09 10:14
Should be fixed on the master channel now.

**Closed by mraleph** 2020-04-09 10:14 UTC
