### ISSUE TITLE
Picture.toImage() width and height limits in Flutter 1.2

### ISSUE THREAD

**Issue by john-k-lee** [flutter/flutter#28705] opened 2019-03-01 07:22 UTC
## Steps to Reproduce
I was using Picture.toImage(..) in Flutter 1.0 on Android as part of creating large PNG files - (a resolution of 10800X7200 was the largest size I used.)  This worked well.  Picture.toImage(..) (w/Flutter 1.2.1) now has a hard limit of 4096 for both the height and width parameters. Exceeding 4096 for either parameter results in  "Exception: operation failed".  I read that the Picture.toImage rasterization was recently moved to the GPU thread...so maybe this is a GPU related limitation.  

In my use-case of saving PNG files, screen performance is not an issue -- so the synchronous Flutter 1.0 implementation worked fine.  Is this 4K limit in Flutter 1.2 an issue that can be addressed?  Is there an alternate path I could pursue to get a larger image from a Picture in Flutter 1.2? 

To reproduce call  pic.toImage(4097, 100);   to generate an exception.
Changing 4097 to 4096 will run fine.  Using (4096, 4096) is the max width & height that will work.
https://gist.github.com/john-k-lee/9841d68b45fdff2f2981dcdd2c56739b

## Logs

```
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+9295 ms] E/flutter (20319): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: operation failed
[   +1 ms] E/flutter (20319): #0      _MyHomePageState.build.<anonymous closure> (package:testing/main.dart:43:26)
[        ] E/flutter (20319): <asynchronous suspension>
[        ] E/flutter (20319): #1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
[        ] E/flutter (20319): #2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
[   +1 ms] E/flutter (20319): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
[        ] E/flutter (20319): #4      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
[        ] E/flutter (20319): #5      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
[        ] E/flutter (20319): #6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
[        ] E/flutter (20319): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent
(package:flutter/src/gestures/binding.dart:218:20)
[   +1 ms] E/flutter (20319): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent
(package:flutter/src/gestures/binding.dart:192:22)
[   +1 ms] E/flutter (20319): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent
(package:flutter/src/gestures/binding.dart:149:7)
[   +1 ms] E/flutter (20319): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue
(package:flutter/src/gestures/binding.dart:101:7)
[   +1 ms] E/flutter (20319): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket
(package:flutter/src/gestures/binding.dart:85:7)
[   +1 ms] E/flutter (20319): #12     _rootRunUnary (dart:async/zone.dart:1136:13)
[        ] E/flutter (20319): #13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] E/flutter (20319): #14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
[        ] E/flutter (20319): #15     _invoke1 (dart:ui/hooks.dart:223:10)
[        ] E/flutter (20319): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
[        ] E/flutter (20319):

```

```
PS C:\Flutter\testing> flutter analyze
Analyzing testing...
No issues found! (ran in 3.4s)
```

```
flutter doctor -v
[v] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.14393], locale en-US)
    • Flutter version 1.2.1 at C:\Flutter\flutter
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[v] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\johnlee\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[v] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[v] Connected device (1 available)
    • Nexus 7 • 05ef1e44 • android-arm • Android 6.0.1 (API 23)

• No issues found!
```

**Comment by e-body** [comment] 2019-03-01 13:43
o~

**Comment by cbracken** [comment] 2019-04-29 18:20
@brianosman is this working as intended?

**Comment by brianosman** [comment] 2019-04-29 18:31
As far as Skia is concerned, this is working as intended, but we have talked about handling this differently. This probably isn't ideal, especially for Flutter.

In particular, the 4096 isn't even consistent, it's the maximum texture size supported by the GPU. (4k is a very common value for that limit, though). Creating an image greater than that on the GPU is basically impossible, but we could render something bigger in a tiled fashion. We'd still only be able to resolve those sub-tiles to RAM (and there are issues if the picture contains image filters that need intermediate results outside of the tile boundaries). We've also talked about being able to ingest images that are larger than the GPU supports, by using multiple textures and custom shader code to handle the sampling. That's all a ways off, though.

**Comment by cbracken** [comment] 2019-05-06 18:38
@john-k-lee closing this as working as intended for the moment. If we were to implement a workaround (e.g. switching to the software renderer once we get past the max size) users would see a performance cliff, and get inconsistent rendering depending on size. I also worry that this encourages practices that lead to memory issues etc. 

If you could provide a concrete example of your use-case and what other approaches you've investigated, there may be some other means of achieving it.

**Closed by cbracken** 2019-05-06 18:38 UTC
Labels: a: images, dependency: skia, engine, severe: new feature

**Comment by john-k-lee** [comment] 2019-05-06 22:03
@cbracken   Thanks for the review of this issue.  I fully support changes to improve animation performance and prevent potential memory issues.  A majority of my experimental project does involve animation and performance is key.  It took a bit of debugging to find the limits that I reported - so I would suggest adding known limits to the docs or exception text.

Regarding the issue, my use case is as simple as it sounds - using PictureRecorder, Canvas and related classes to compose an image in memory (not displayed) with the end result being a printable PNG file. Higher resolution equals better quality or larger prints.  I do recognize that this is a unconventional use of these tools.  I have not investigated other approaches - and as long as my code continues to compile w/Flutter 1.0, I have that as a fallback.  

As a newcomer to Flutter my understanding of the framework is still pretty weak -- but I wonder if this is a case where a package or plugin might be applicable.  Perhaps one which revives the rendering technique that was previously used and can take advantage of available device memory - with the known performance penalty.
