### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "git" in the search path. Command: git, OS error code: 0

### ISSUE THREAD

**Issue by dkjfa** [flutter/flutter#144515] opened 2024-03-03 11:42 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "git" in the search path. Command: git, OS error code: 0
```
#0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
#1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:711:24)
#2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:710:12)
#4      _runSync (package:flutter_tools/src/version.dart:856:56)
#5      _gitCommitDate (package:flutter_tools/src/version.dart:436:12)
#6      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:279:49)
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:322:40)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
```
[☠] Flutter (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ ProcessException: Failed to find "git" in the search path.
        Command: git 
    • #0      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:118:7)
      #1      ErrorHandlingProcessManager.runSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:711:24)
      #2      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
      #3      ErrorHandlingProcessManager.runSync (package:flutter_tools/src/base/error_handling_io.dart:710:12)
      #4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:423:51)
      #5      _runGit (package:flutter_tools/src/version.dart:877:23)
      #6      FlutterVersion.frameworkAge (package:flutter_tools/src/version.dart:220:30)
      #7      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:574:17)
      #8      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:272:72)
      #9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #10     _rootRun (dart:async/zone.dart:1399:13)
      #11     _CustomZone.run (dart:async/zone.dart:1301:19)
      #12     _runZoned (dart:async/zone.dart:1804:10)
      #13     runZonedGuarded (dart:async/zone.dart:1792:12)
      #14     runZoned (dart:async/zone.dart:1744:12)
      #15     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #16     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:264:9)
      #17     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart:792:60)
      #18     DoctorText._validatorTasks (package:flutter_tools/src/doctor.dart)
      #19     DoctorText._runDiagnosis (package:flutter_tools/src/doctor.dart:796:53)
      #20     DoctorText.text (package:flutter_tools/src/doctor.dart:788:36)
      #21     DoctorText.text (package:flutter_tools/src/doctor.dart)
      #22     _createLocalCrashReport (package:flutter_tools/runner.dart:262:51)
      #23     _handleToolError (package:flutter_tools/runner.dart:224:31)
      <asynchronous suspension>
      #24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
      <asynchronous suspension>
      #25     main (package:flutter_tools/executable.dart:90:3)
      <asynchronous suspension>


[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34622.214
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.2)
    • Android Studio at E:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3007]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.95
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.59

[!] Network resources
    ✗ A network error occurred while checking "https://maven.google.com/": 信号灯超时时间已到


! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment] 2024-03-04 08:50
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133585

**Closed by danagbemava-nc** 2024-03-04 08:50 UTC
Labels: in triage
