### ISSUE TITLE
TextFormField border disappeared after few second in Safari

### ISSUE THREAD

**Issue by jianzai9607** [flutter/flutter#103946] opened 2022-05-17 03:12 UTC
## Steps to Reproduce

I have created some TextFormFields with labelText. After focused, the border will disappear after few second in Safari browser. Removing the labelText will not caused the bug. 

<details>
<summary>Code sample</summary>

```
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final ScrollController _scrollController = ScrollController();

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: true,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SafeArea(
        child: Center(
          child: Container(
            width: 364,
            height: 350,
            decoration: BoxDecoration(
                color: Colors.white, border: Border.all(color: Colors.black)),
            padding: const EdgeInsets.all(20),
            child: Column(children: [
              const SizedBox(
                height: 20,
              ),
              ...['Username', 'Password', 'Referral Code']
                  .map(
                    (e) => Padding(
                      padding: const EdgeInsets.only(bottom: 20),
                      child: TextFormField(
                        decoration: InputDecoration(
                          labelText: e,
                          hintText: e,
                          filled: true,
                          isDense: true,
                          fillColor: Colors.white,
                          border: OutlineInputBorder(
                            borderSide: const BorderSide(color: Colors.black),
                            borderRadius: BorderRadius.circular(20),
                          ),
                          focusedBorder: OutlineInputBorder(
                            borderSide: const BorderSide(color: Colors.black),
                            borderRadius: BorderRadius.circular(20),
                          ),
                          enabledBorder: OutlineInputBorder(
                            borderSide: const BorderSide(color: Colors.black),
                            borderRadius: BorderRadius.circular(20),
                          ),
                          disabledBorder: OutlineInputBorder(
                            borderSide: const BorderSide(color: Colors.black),
                            borderRadius: BorderRadius.circular(20),
                          ),
                        ),
                      ),
                    ),
                  )
                  .toList()
            ]),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1706], locale en-MY)
    • Flutter version 2.10.5 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\HewZiJian\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.67.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

https://user-images.githubusercontent.com/65189320/168720075-05ae7093-c64a-403b-94ff-0a34296bf163.mp4

**Comment by huycozy** [comment] 2022-05-17 10:27
Hi @jianzai9607,
Thanks for filing the issue. But I can not reproduce this error on either MacOS's Safari or iPhone's Safari even though I waited a few minutes. 
As I see you are using Flutter SDK version 2.10.5.
Could you try to upgrade to the latest version (3.10 stable or 3.1 master) and try again to see whether the issue persists?
Also please provide the device information (device model, iOS version) to investigate this issue further.

**Comment by jianzai9607** [comment] 2022-05-19 07:11
It is happened in iPhone's Safari browser, IOS 15.4.1 , IPHONE XR. 

For further details, I build the flutter web with the command:
`flutter build web --release --no-sound-null-safety --web-renderer canvaskit`

I updated to Flutter 3, but the problem still there with same behavior.
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1706], locale en-MY)
    • Flutter version 3.0.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (9 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\HewZiJian\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.67.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by huycozy** [comment] 2022-05-20 10:56
@jianzai9607: I still can not reproduce the issue on my iPhone 7 (iOS 15.5), iPhone XR (iOS 15.5), and Emulator (iOS 15.4). 
Do you have any special render settings on your's Safari browser?

**Comment by jianzai9607** [comment] 2022-05-23 10:48
It didn't have any special setting in Safari browser, perhaps you may test my example in the url below?
https://fluttertest-22891.web.app/
I also updated flutter to 3.0.1 as below

[√] Flutter (Channel stable, 3.0.1, on Microsoft Windows [Version 10.0.19044.1706], locale en-MY)
    • Flutter version 3.0.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (4 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\HewZiJian\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.67.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by huycozy** [comment] 2022-05-23 11:12
> It didn't have any special setting in Safari browser, perhaps you may test my example in the url below? 
https://fluttertest-22891.web.app/

Hi, I tried your web before but the result still is the same. 

<details>
<summary>Demo</summary>

https://user-images.githubusercontent.com/104349824/169806378-4deb5154-a3c1-490b-b672-4583f4a7c0c1.MP4

</details>

I noticed that at 0:26 time in your demo video, the layout was pushed up too high than normal. I can't reproduce this on my device either. 

And one more the different thing is that the cursor still is there when closing the keyboard (the cursor will disappear when closing the keyboard on my side).

I think you should try to find the correct steps to investigate this issue further.

**Closed** 2022-06-13 12:11 UTC
Labels: in triage, r: timeout
