### ISSUE TITLE
Web view Download listener 

### ISSUE THREAD

**Issue by asarkar1990** [flutter/flutter#28257] opened 2019-02-21 13:12 UTC
is there any way to use download listener with web view ?

**Comment by MilloshFey** [comment] 2019-02-21 20:12
That would be very helpfull

**Comment by MilloshFey** [comment] 2019-02-22 20:13
I am really newbie but I kind of got it working (for me, at least).
open FlutterWebviewPlugin.java located at: <flutter directory>\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.0+2\android\src\main\java\com\flutter_webview_plugin.
Then add :
``` java
import android.webkit.DownloadListener;
```
you can add it at line 18.

and 
``` java
webView.setDownloadListener(new DownloadListener() {
            public void onDownloadStart(String url, String userAgent,
                                        String contentDisposition, String mimetype,
                                        long contentLength) {
                Intent i = new Intent(Intent.ACTION_VIEW);
                i.setData(Uri.parse(url));
                activity.startActivity(i);
            }
			});
```
right bellow  "webView.setWebViewClient(webViewClient);" or something.
That worked for me. Hope it work for you too.

**Comment by VladyslavBondarenko** [comment] 2020-03-17 14:02
Related to https://github.com/flutter/flutter/issues/39321

**Comment by stuartmorgan** [comment] 2023-04-30 17:00
Closing as a duplicate of https://github.com/flutter/flutter/issues/39321, since that's where most of the discussion and voting has happened.

**Closed by stuartmorgan** 2023-04-30 17:00 UTC
Labels: new feature, plugin, p: webview, P4
