### ISSUE TITLE
'This is not an official channel' message during switch to stable

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#25115] opened 2018-12-08 13:05 UTC
I've gotten this on two machines now while switching from beta to stable:

```
$ flutter channel stable
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Switching to flutter channel 'stable'...
This is not an official channel. For a list of available channels, try "flutter channel".
```

**Comment by ened** [comment] 2018-12-08 13:30
Perhaps because your previous flutter version did not have "stable" listed in the `officialChannels` constant in `packages/flutter_tools/lib/src/version.dart`?

See also:
https://github.com/flutter/flutter/commit/1b9cba4b42d177d9b0ca243e9072084b13f87b95

**Comment by biancashouse** [comment] 2018-12-20 21:59
I also got this message and stable is, indeed, the last entry in my version.dart.

**Comment by biancashouse** [comment] 2018-12-20 22:05
Although I did see this message, when I did a 'flutter channel' imm. after, the stable versions were downloaded, and there are now 4 channels lists.
(This leads me to assume that 'stable' was possibly not there before I started.)

**Comment by christopherfujino** [comment] 2020-01-24 21:10
I'm closing this as it looks to me like the cause was indeed starting from a version before [this change](https://github.com/flutter/flutter/pull/23745), as @ened suggests. If this happens again to anyone please re-open with details.

**Closed by christopherfujino** 2020-01-24 21:10 UTC
Labels: tool
