### ISSUE TITLE
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.

### ISSUE THREAD

**Issue by ChristBKK** [flutter/flutter#59319] opened 2020-06-12 10:48 UTC
Hi there,

Always when I change the Display Name of the App in the Runner File in Xcode from Runner to something meaningful I get this error when I run the app in the IOS Simulator.

**"Could not find the built application bundle at build/ios/iphonesimulator/Runner.app."**

Is there any way to fix this problem? I have this for several months now on different Flutter versions. 

<img width="646" alt="Screenshot 2020-06-12 17 48 21" src="https://user-images.githubusercontent.com/12375330/84495194-f44db900-acd4-11ea-8ff0-d70d2afbf14e.png">

**Comment by TahaTesser** [comment] 2020-06-12 11:56
Hi @ChristBKK 
You shouldn't modify display name, it's should be Runner 
Please check this [explanation](https://github.com/flutter/flutter/issues/41793#issuecomment-537609269rl)

Closing as duplicate of https://github.com/flutter/flutter/issues/41793

**Closed by TahaTesser** 2020-06-12 11:56 UTC
