### ISSUE TITLE
NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages

### ISSUE THREAD

**Issue by infinityp913** [flutter/flutter#60444] opened 2020-06-27 22:26 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. No file was changed. The project is exactly the project that is created on creating a flutter project in vscode
3. Execute flutter run -d chrome

**Expected results:** 
I expected to see the default web app.
**Actual results:** 
I saw a blank chrome page displaying nothing and in the terminal saw this in red:

> Oops; flutter has exited unexpectedly: "NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
> Receiver: Closure: (_SyncIterator<Package>) => bool
> Tried calling: MutablePackageTree.allPackages()
> Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool"

When the project is run with flutter run --release -d chrome it has no issues. Not sure why this happens.
<details>
  <summary>Logs</summary>

flutter run --verbose-

>  executing: [C:\Users\infin\OneDrive\Documents\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
> [  +64 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
> [   +1 ms] d3ed9ec945f8869f0e136c357d0c2a6be2b60c98
> [   +1 ms] executing: [C:\Users\infin\OneDrive\Documents\flutter/] git describe --match *.*.* --first-parent --long --tags
> [  +57 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
> [   +1 ms] 1.17.0-dev.3.1-0-gd3ed9ec94
> [  +10 ms] executing: [C:\Users\infin\OneDrive\Documents\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
> [  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
> [   +1 ms] origin/beta
> [   +1 ms] executing: [C:\Users\infin\OneDrive\Documents\flutter/] git ls-remote --get-url origin
> [  +36 ms] Exit code 0 from: git ls-remote --get-url origin
> [   +1 ms] https://github.com/flutter/flutter.git
> [  +87 ms] executing: [C:\Users\infin\OneDrive\Documents\flutter/] git rev-parse --abbrev-ref HEAD
> [  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
> [   +1 ms] beta
> [  +44 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
> [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [  +22 ms] executing: C:\Users\infin\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
> [  +38 ms] List of devices attached
> [   +8 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
> [   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
> [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
> [   +8 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
> [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
> [   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
> [  +15 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
> [  +12 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
> [ +160 ms] Generating C:\Users\infin\OneDrive\Documents\Flutter Web Projects\coldfiction\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
> [ +504 ms] Launching lib\main.dart on Chrome in debug mode...
> [  +41 ms] Updating assets
> [  +83 ms] Syncing files to device Chrome...
> [  +47 ms] Generating C:\Users\infin\OneDrive\Documents\Flutter Web Projects\coldfiction\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
> [  +56 ms] <- reset
> [   +8 ms] C:\Users\infin\OneDrive\Documents\flutter\bin\cache\dart-sdk\bin\dart.exe
> C:\Users\infin\OneDrive\Documents\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
> C:\Users\infin\OneDrive\Documents\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
> -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\infin\AppData\Local\Temp\flutter_tool.162078e0\app.dill --libraries-spec
> file:///C:/Users/infin/OneDrive/Documents/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\infin\OneDrive\Documents\Flutter Web
> Projects\coldfiction\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
> --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts 
> --track-widget-creation --filesystem-root C:\Users\infin\AppData\Local\Temp\flutter_tools.68ac9018 --filesystem-scheme org-dartlang-app --initialize-from-dill       
> build\cache.dill --platform file:///C:/Users/infin/OneDrive/Documents/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
> [  +11 ms] <- compile org-dartlang-app:///web_entrypoint.dart
> [+12562 ms] Syncing files to device Chrome... (completed in 12,677ms, longer than expected)
> [   +1 ms] Synced 22.7MB.
> [   +1 ms] <- accept
> [ +210 ms] [CHROME]:
> [   +4 ms] [CHROME]:DevTools listening on ws://127.0.0.1:49826/devtools/browser/9a4b04bd-8699-41c7-99a4-c9bb75ea42da
> [+4828 ms] Debug service listening on ws://127.0.0.1:49862/i7YueAKHzvs=
> 
> [ +239 ms] "flutter run" took 18,999ms.
> 
> Oops; flutter has exited unexpectedly: "NoSuchMethodError: Closure call with mismatched arguments: function 'MutablePackageTree.allPackages'
> Receiver: Closure: (_SyncIterator<Package>) => bool
> Tried calling: MutablePackageTree.allPackages()
> Found: MutablePackageTree.allPackages(_SyncIterator<Package>) => bool".
> [ +270 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
> [  +97 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
> [   +1 ms] openjdk version "1.8.0_212-release"
>            OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>            OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
> [  +16 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
> [  +95 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
> [   +1 ms] openjdk version "1.8.0_212-release"
>            OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>            OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
> [   +7 ms] executing: [C:\Users\infin\OneDrive\Documents\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
> [  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
> [   +1 ms] 3 months ago
> \[ +248 ms] executing: C:\Users\infin\AppData\Local\Android\sdk\tools\bin\sdkmanager --licenses
> 
> A crash report has been written to C:\Users\infin\OneDrive\Documents\Flutter Web Projects\coldfiction\flutter_04.log.
> This crash may already be reported. Check GitHub for similar crashes.
> https://git.io/JfCfg
> 
> To report your crash to the Flutter team, first read the guide to filing a bug.
> https://flutter.dev/docs/resources/bug-reports
> 
> Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
> https://git.io/JJeHP

```
```

flutter analyze:

> Analyzing coldfiction...
> No issues found! (ran in 1.9s)

```
```

flutter doctor -v:

> [√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
>     • Flutter version 1.17.0 at C:\Users\infin\OneDrive\Documents\flutter
>     • Framework revision d3ed9ec945 (3 months ago), 2020-04-06 14:07:34 -0700
>     • Engine revision 9a28c3bcf4
>     • Dart version 2.9.0 (build 2.9.0-14.1.beta)
> 
>  
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at C:\Users\infin\AppData\Local\Android\sdk
>     • Platform android-29, build-tools 29.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.46.1)
>     • VS Code at C:\Users\infin\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.12.0
> 
> [√] Connected device (2 available)
>     • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116
>     • Web Server • web-server • web-javascript • Flutter Tools
> 
> ! Doctor found issues in 1 category.

```
```

</details>

**Comment by jonahwilliams** [comment] 2020-06-27 22:42
Duplicate of https://github.com/flutter/flutter/issues/59245

**Closed by jonahwilliams** 2020-06-27 22:42 UTC
