### ISSUE TITLE
[tool_crash] FileSystemException: Cannot delete file, OS Error: Access is denied., errno = 5

### ISSUE THREAD

**Issue by TheNairaSign** [flutter/flutter#155237] opened 2024-09-16 07:42 UTC
## Command
```sh
flutter --quiet assemble --no-version-check --depfile C:\Project Files\vennloop\build\app\intermediates\flutter\debug/flutter_build.d --output C:\Project Files\vennloop\build\app\intermediates\flutter\debug -dTargetFile=C:\Project Files\vennloop\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true -dFlavor= -dAndroidArchs=android-arm64 -dMinSdkVersion=21 debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot delete file, OS Error: Access is denied.
, errno = 5
```console
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File._deleteSync (dart:io/file_impl.dart:329:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:407:7)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#4      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#5      ErrorHandlingFileSystem.deleteIfExists (package:flutter_tools/src/base/error_handling_io.dart:84:14)
#6      FlutterBuildSystem.trackSharedBuildDirectory (package:flutter_tools/src/build_system/build_system.dart:778:33)
#7      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:659:5)
<asynchronous suspension>
#8      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:328:32)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22631.4169], locale en-NG)
    • Flutter version 3.24.1 on channel stable at C:\Users\tonye\Downloads\.exe\flutter_windows_3.10.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (4 weeks ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\tonye\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.0 Preview 1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Preview
    • Visual Studio Community 2022 version 17.7.33711.374
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[✓] VS Code (version 1.93.1)
    • VS Code at C:\Users\tonye\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[✓] Connected device (4 available)
    • Redmi Note 9S (mobile) • 208131cd • android-arm64  • Android 12 (API 31)
    • Windows (desktop)      • windows  • windows-x64    • Microsoft Windows [Version 10.0.22631.4169]
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 128.0.2739.79

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b0850beeb25f6d5b10426284f506557f66181b36
### Plugins
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0

**Comment by darshankawar** [comment] 2024-09-16 11:18
Closing as duplicate of https://github.com/flutter/flutter/issues/88830

**Closed by darshankawar** 2024-09-16 11:18 UTC
Labels: in triage
