### ISSUE TITLE
Intl Invalid locale 'null' IOS

### ISSUE THREAD

**Issue by illiashvedov** [flutter/flutter#57204] opened 2020-05-14 11:54 UTC
### flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale ru)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.0)
[✓] Connected device (2 available)
```

ios (13.4.1) exception 

```
Non-fatal Exception: Invalid argument(s): Invalid locale 'null'
0  ???                            0x0 _throwLocaleError + 245 (intl.dart:245)
1  ???                            0x0 verifiedLocale + 239 (intl.dart:239)
2  ???                            0x0 new + 246 (date_format.dart:246)
3  ???                            0x0 _dateFormat + 16 (home_screen.dart:16)
4  ???                            0x0 build + 153 (home_screen.dart:153)
5  ???                            0x0 build + 4334 (framework.dart:4334)
6  ???                            0x0 performRebuild + 4223 (framework.dart:4223)
7  ???                            0x0 rebuild + 3947 (framework.dart:3947)
8  ???                            0x0 buildScope + 2432 (framework.dart:2432)
9  ???                            0x0 drawFrame + 773 (binding.dart:773)
10 ???                            0x0 _handlePersistentFrameCallback + 283 (binding.dart:283)
11 ???                            0x0 _invokeFrameCallback + 1102 (binding.dart:1102)
12 ???                            0x0 handleDrawFrame + 1041 (binding.dart:1041)
13 ???                            0x0 _handleDrawFrame + 957 (binding.dart:957)
```

**Comment by illiashvedov** [comment] 2020-05-14 12:52
I have already caught the second such error on iOS version 13.4.1 (17E262).

**Comment by VladyslavBondarenko** [comment] 2020-05-14 14:13
Hi @illiashvedov 
does it happen with current stable `1.17.1` or other channels?
could you provide a minimal complete code sample/project to reproduce the exception?

**Comment by illiashvedov** [comment] 2020-05-14 14:48
Hi, I am using the penultimate stable version. Unfortunately, I could not reproduce this error artificially. This is a mistake I caught using Crashlantic. I only know that the devices were English and the Ukrainian region

**Comment by VladyslavBondarenko** [comment] 2020-05-15 07:55
@illiashvedov 
consider to open the issue in the Intl repository https://github.com/dart-lang/intl/issues instead,
closing since this is not an issue with Flutter itself.
If you disagree please write in the comments and I will reopen it

**Closed** 2020-05-15 07:55 UTC
