### ISSUE TITLE
Application.java file is broken!

### ISSUE THREAD

**Issue by kari538** [flutter/flutter#74398] opened 2021-01-21 12:15 UTC
I followed your Read Me to the dot, but the Application.java file that you gave the code for does not work at all!

As I copy that code into a new file called Application.java in the same directory as MainActivity.java, pretty much everything comes up read-marked with the error msg "Cannot resolve symbol" and similar.

About the argument "registry", I'm told it is the wrong type, it should be a FlutterEngine type. But if I change the type to FlutterEngine, it goes back to "cannot resolve"...

All the import except one can't be read/don't exist... Even if I look for them in the proposed directory, there is nothing there...

I'm guessing this is some kind of compatibility issue!... So could you plz clarify what exactly is needed for that Application.java file to work?... Or otherwise how to solve this problem. As of now, the app doesn't even build.

**Comment by TahaTesser** [comment] 2021-01-21 12:49
Hi @kari538 
The issue is not clear, can you please explain the issue with some example and why you need `Application.java` in your project and also link README you followed.
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by kari538** [comment] 2021-01-21 14:41
Sorry, I came to this repository following a link from a specific flutter
package... Therefore, I naturally thought that the feedback I gave would be
linked to the specific package! I see now that it's instead a very general
repository... How will the developers of the package even know? 🙄

Anyway, this is the package that my qn relates to:
https://pub.dev/packages/firebase_messaging

Could I post the qn somewhere else, maybe...? If you can't answer...

**Comment by TahaTesser** [comment] 2021-01-22 07:11
Hi @kari538 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-22 07:11 UTC
Labels: in triage
