### ISSUE TITLE
[Official tutorial] Grid with image view scroll issue in android (IOS not test)

### ISSUE THREAD

**Issue by CircleCurve** [flutter/flutter#17152] opened 2018-05-01 13:30 UTC
## Steps to Reproduce
1. Following the official tutorial about building a grid view
[https://flutter.io/tutorials/layout/](url)
2. Copy the source code and paste to my project
[https://raw.githubusercontent.com/flutter/website/master/_includes/code/layout/grid/main.dart](url)
3. Compile and run it. It has a good look but when i scroll a period of time, it finally crashes. ![flutter_grid](https://user-images.githubusercontent.com/8490834/39474113-f74a44d6-4d84-11e8-9ab1-8d9ad147500f.gif)
4. I try this from flutter gallery but it's all ok. Do not have any issue even if faster or slower scroll. 
5. I also try to follow an lazing loading of grid builder 
[https://docs.flutter.io/flutter/widgets/GridView/GridView.builder.html](url)

I think the most related part should be an assertion
```dart
'childCount >= leadingGarbage + trailingGarbage': is not true.
```

And below is my source code, Do anyone know how to fix this problem? According to an error, seems like it is related to garbage collection? 

```dart
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
// Uncomment lines 7 and 10 to view the visual layout at runtime.
//import 'package:flutter/rendering.dart' show debugPaintSizeEnabled;



class OfficalGridViewLayout extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

// The images are saved with names pic1.jpg, pic2.jpg...pic30.jpg.
// The List.generate constructor allows an easy way to create
// a list when objects have a predictable naming pattern.
List<Container> _buildGridTileList(int count) {
  List<Container> containers = new List<Container>.generate(
      count,
      (int index) =>
          new Container(child: new Image.asset('images/grid/pic${index+1}.jpg')));
  return containers;
}

Widget buildGrid() {


  return new GridView.builder(
    itemCount: 10,
    padding: const EdgeInsets.all(4.0),
    gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
      crossAxisCount: 2,
      mainAxisSpacing: 4.0,
      crossAxisSpacing: 4.0
    ),
    itemBuilder: (context, i ){
      print(i) ; 
      return new Container(child: new Image.asset('images/grid/pic${i+1}.jpg')); 
    },
  );

  /* return new GridView.extent(
      maxCrossAxisExtent: 150.0,
      padding: const EdgeInsets.all(4.0),
      mainAxisSpacing: 4.0,
      crossAxisSpacing: 4.0,
      children: _buildGridTileList(30)); */
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: buildGrid(),
      ),
    );
  }
}
```

## Logs

Run your application with `flutter run` and attach all the log output.
```
05-01 21:12:51.419 3649-3663/com.example.myapp I/flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
05-01 21:12:51.439 495-508/? D/dalvikvm: GC_FOR_ALLOC freed 737K, 25% free 9113K/12064K, paused 16ms, total 16ms
05-01 21:12:51.439 495-508/? I/dalvikvm-heap: Grow heap (frag case) to 9.583MB for 635808-byte allocation
05-01 21:12:51.449 3649-3663/com.example.myapp I/flutter: The following assertion was thrown during performLayout():
    'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 433 pos 12:
    'childCount >= leadingGarbage + trailingGarbage': is not true.
    Either the assertion indicates an error in the framework itself, or we should provide substantially
    more information in this error message to help you determine and fix the underlying cause.
    In either case, please report this assertion by filing a bug on GitHub:
      https://github.com/flutter/flutter/issues/new
    When the exception was thrown, this was the stack:
05-01 21:12:51.469 495-502/? D/dalvikvm: GC_FOR_ALLOC freed 2K, 24% free 9731K/12688K, paused 23ms, total 23ms
05-01 21:12:51.469 495-508/? W/WindowManager: updateFocusedWindowLocked, focusedAppToken is null.
05-01 21:12:51.479 705-705/? D/FirebaseApp: Notifying background state change listeners.
05-01 21:12:51.509 3649-3663/com.example.myapp I/flutter: #2      RenderSliverMultiBoxAdaptor.collectGarbage (package:flutter/src/rendering/sliver_multi_box_adaptor.dart)
    #3      RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:533:7)
    #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #5      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
    #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
    #7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:285:13)
    #8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1008:12)
    #9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:932:20)
    #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
    #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
    #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
    #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:622:13)
    #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
    #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
    #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
    #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
    #18     _invoke (dart:ui/hooks.dart:120:13)
    #19     _drawFrame (dart:ui/hooks.dart:109:3)
    (elided 2 frames from class _AssertionError)
05-01 21:12:51.559 3649-3663/com.example.myapp I/flutter: The following RenderObject was being processed when the exception was fired:
      RenderSliverGrid#87a7a relayoutBoundary=up2
      creator: SliverGrid ← SliverPadding ← Viewport ← _ScrollableScope ←
      IgnorePointer-[GlobalKey#aaffe] ← Semantics ← Listener ← _GestureSemantics ←
      RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#d1583] ←
      _ExcludableScrollSemantics-[GlobalKey#7754b] ← RepaintBoundary ← CustomPaint ← ⋯
      parentData: paintOffset=Offset(4.0, 0.0) (can use size)
      constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward,
      ScrollDirection.reverse, scrollOffset: 271.3, remainingPaintExtent: 772.0, crossAxisExtent: 472.0,
      crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 772.0)
      geometry: SliverGeometry(scrollExtent: 1186.0, paintExtent: 768.5, maxPaintExtent: 1186.0,
      hasVisualOverflow: true)
      currently live children: 0 to 7
    This RenderObject had the following descendants (showing up to depth 5):
      RenderRepaintBoundary#876aa
        RenderImage#d6dfd
      RenderRepaintBoundary#d5ab5
        RenderImage#bf1c1
05-01 21:12:51.569 3649-3663/com.example.myapp I/flutter:   RenderRepaintBoundary#9c7a8
        RenderImage#59735
      RenderRepaintBoundary#9fba1
        RenderImage#67b9a
      RenderRepaintBoundary#faeef
        RenderImage#8bbc7
      RenderRepaintBoundary#4c986
        RenderImage#d572e
      RenderRepaintBoundary#49a3e
        RenderImage#0fc3d
      RenderRepaintBoundary#18c23
        RenderImage#a15a4
    ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Run `flutter analyze` and attach any output of that command also.
```
D:\Program Files\Code\source_code\flutterapps>flutter analyze
Analyzing D:\Program Files\Code\source_code\flutterapps...
  hint - Unused import: 'FlutterLayout.dart' at lib\main.dart:2:8 - unused_impor
t
  hint - Unused import: 'StartupNamer.dart' at lib\main.dart:3:8 - unused_import

  hint - Unused import: 'MenuLayout.dart' at lib\main.dart:4:8 - unused_import
  hint - Unused import: 'OfficalMenuLayout.dart' at lib\main.dart:5:8 - unused_i
mport
  hint - Unused import: 'NonMaterialApp.dart' at lib\main.dart:6:8 - unused_impo
rt
  hint - Unused import: 'ImageLayout.dart' at lib\main.dart:7:8 - unused_import
  hint - Unused import: 'CustomGridViewLayout.dart' at lib\main.dart:8:8 - unuse
d_import
  hint - Unused import: 'GridViewAdvanceLayout.dart' at lib\main.dart:9:8 - unus
ed_import
  hint - The function '_buildGridTileList' isn't used at lib\OfficalGridViewLayo
ut.dart:36:17 - unused_element
  hint - The function '_buildImage' isn't used at lib\OfficalMenuLayout.dart:146
:12 - unused_element
10 issues found.
(Ran in 19.1s)
```
## Flutter Doctor
```
D:\Program Files\Code\source_code\flutterapps>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[âˆš] Flutter (Channel beta, v0.2.8, on Microsoft Windows [Version 6.1.7601], lo
cale zh-TW)
[âˆš] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[âˆš] Android Studio (version 3.1)
[âˆš] Connected devices (1 available)

â€¢ No issues found!
```
> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by chunhtai** [comment] 2020-05-08 18:02
I cannot reproduce it. @CircleCurve Can you try again to see if you can still reproduce it?

**Comment by iapicca** [comment] 2020-06-05 12:19
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-06-05 12:19 UTC
Labels: f: scrolling, framework, severe: crash, waiting for customer response
