### ISSUE TITLE
Just upgrade flutter and all ImageView can not be shown on iOS 13.2 iPhoneX

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#45098] opened 2019-11-18 15:24 UTC
```
Flutter 1.12.3-pre.49 • channel master • https://github.com/flutter/flutter.git
Framework • revision 21e6fe1ddf (10 hours ago) • 2019-11-17 23:39:51 -0500
Engine • revision 3261324fab
Tools • Dart 2.7.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.3-pre.49, on Mac OS X 10.14.6 18G71a, locale en-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

Just upgraded to newest flutter, now all my app with Image relate (literally image pixel relate widget can not be shown anymore).

The Image, AssetImage, NetworkImage all can not be shown....

**Comment by jinfagang** [comment] 2019-11-18 15:24
Also, CupertinoTextField can not show paste promote message as before....

**Comment by tvolkert** [comment] 2019-11-18 19:48
@jinfagang any chance you could bisect to find out where this started happening?

**Comment by rdev-software** [comment] 2019-11-18 21:12
Half of my screen is not rendering correctly with new update

**Comment by tvolkert** [comment] 2019-11-18 21:28
I've reproduced on the Flutter gallery - running a bisect right now.

**Comment by tvolkert** [comment] 2019-11-18 21:57
I've bisected this to commit 6268a7f54025123fcdd951d78aef549f9587ae7f - an engine roll that contained the following commits:

* Roll src/third_party/dart dc35290111..dc808f3fcb (5 commits) (flutter/engine#13859)
* Roll fuchsia/sdk/core/mac-amd64 from 7XOyl... to VMTIz... (flutter/engine#13861)
* Roll src/third_party/skia d860a78fd60c..e57ca4931952 (44 commits) (flutter/engine#13862)
* RendererContextSwitch guard flutter's gl context rework. (flutter/engine#13812)
* Fix test to account for pixel ratio transformations being framework responsibility. (flutter/engine#13850)
* Guard against orphaned semantic objects from referencing dead accessibility bridge on iOS (flutter/engine#13857)
* [fuchsia] Package flutter_frontend_server snapshot for fuchsia (flutter/engine#13865)
* [flow][fuchsia] Add more tracing to layers and Fuchsia surface pool (flutter/engine#13864)
* Roll src/third_party/skia e57ca4931952..c1c4634dcb07 (15 commits) (flutter/engine#13866)
* Revert "Roll src/third_party/dart dc35290111..dc808f3fcb (5 commits) (#13859)" (flutter/engine#13867)

Will continue to bisect the engine commits therein.

**Comment by rdev-software** [comment] 2019-11-18 22:05
@tvolkert thx, so how I can pull just that flutter version, using commit ID you sent ? I use only flutter channel dev. How can I specify commit there ?

**Comment by rdev-software** [comment] 2019-11-18 22:41
`flutter version 1.12.2` Resolved issue for me

**Comment by tvolkert** [comment] 2019-11-18 23:57
Ok, further bisected this to the following commit:

* RendererContextSwitch guard flutter's gl context rework. (flutter/engine#13812)

/cc @cyanglaz

**Comment by beoandlun** [comment] 2019-11-19 02:38
I have same issue on 1.12.3-pre.49.

**Comment by tvolkert** [comment] 2019-11-19 02:47
The engine revert has landed in flutter/engine#13906 but not yet rolled into flutter/flutter

**Comment by jinfagang** [comment] 2019-11-19 03:15
@tvolkert  Thanks for your guys quickly investigation!

When will this solved in master? It's like a disaster for now.

**Comment by luismarquesfreire** [comment] 2019-11-19 03:39
@tvolkert Thanks for the quick support. This needs to be rolled out quickly. I'm also relying on master to fix some dependencies. Going the get some sleep now..

**Comment by tvolkert** [comment] 2019-11-19 05:35
The revert is on master now if you sync past https://github.com/flutter/flutter/commit/1b1365376b924b9664bc6093093a161428f65349

**Comment by tvolkert** [comment] 2019-11-19 18:05
Closing this issue since the fix is on master.  The dev channel should receive the fix in approximately the next day.

**Closed by tvolkert** 2019-11-19 18:05 UTC
Labels: a: images, customer: crowd, customer: fun (g3), severe: customer blocker, ⌺‬ platform-ios, ⚠ TODAY

**Comment by pilotviper134** [comment] 2019-11-20 15:54
Good to know, thanks!
