### ISSUE TITLE
[google_maps_flutter][ios]Incorrect zoom level in TileProvider getTile function.

### ISSUE THREAD

**Issue by manumohn** [flutter/flutter#92960] opened 2021-11-03 05:30 UTC
### Steps to Reproduce

- Implement `onCameraMove` call back in `TileOverlayPage` in google_maps_flutter's example.
- Run example project in google_maps_flutter. 
- Note map's current zoom level in `onCameraMove`.
- Note zoom parameter requested in `TileProvider.getTile(int x, int y, int? zoom)`.

### Expected results:
Zoom level in `onCameraMove` and zoom level in `getTile(int x, int y, int? zoom)` are the same.

### Actual results:
Zoom level in `getTile(int x, int y, int? zoom)` would always be 2 levels greater than the zoom in `onCameraMove`.

I tested this on android and works as expected.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale
    en-IN)
    • Flutter version 2.5.3 at /Users/manumohan/Develolper/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/manumohan/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • 68D4FE39-265B-491E-8DCA-3185D43A3F1C • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)            • chrome                               •
      web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

Ive modified the `TileOverlayPage` to print the camera zoom level in `onCameraMove` and added the zoom to the Tile being shown on the map. Modified code and screenshots below.
<details>
<summary>Modified code</summary>

```
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

import 'page.dart';

class TileOverlayPage extends GoogleMapExampleAppPage {
  TileOverlayPage() : super(const Icon(Icons.map), 'Tile overlay');

  @override
  Widget build(BuildContext context) {
    return const TileOverlayBody();
  }
}

class TileOverlayBody extends StatefulWidget {
  const TileOverlayBody();

  @override
  State<StatefulWidget> createState() => TileOverlayBodyState();
}

class TileOverlayBodyState extends State<TileOverlayBody> {
  TileOverlayBodyState();

  GoogleMapController? controller;
  TileOverlay? _tileOverlay;

  void _onMapCreated(GoogleMapController controller) {
    this.controller = controller;
  }

  @override
  void dispose() {
    super.dispose();
  }

  void _removeTileOverlay() {
    setState(() {
      _tileOverlay = null;
    });
  }

  void _addTileOverlay() {
    final TileOverlay tileOverlay = TileOverlay(
      tileOverlayId: TileOverlayId('tile_overlay_1'),
      tileProvider: _DebugTileProvider(),
    );
    setState(() {
      _tileOverlay = tileOverlay;
    });
  }

  void _clearTileCache() {
    if (_tileOverlay != null && controller != null) {
      controller!.clearTileCache(_tileOverlay!.tileOverlayId);
    }
  }

  @override
  Widget build(BuildContext context) {
    Set<TileOverlay> overlays = <TileOverlay>{
      if (_tileOverlay != null) _tileOverlay!,
    };
    return Column(
      mainAxisSize: MainAxisSize.min,
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        Center(
          child: SizedBox(
            width: 350.0,
            height: 300.0,
            child: GoogleMap(
                initialCameraPosition: const CameraPosition(
                  target: LatLng(59.935460, 30.325177),
                  zoom: 7.0,
                ),
                tileOverlays: overlays,
                onMapCreated: _onMapCreated,
                onCameraMove: (cam) {
                  print("camera zoom ${cam.zoom}");
                }),
          ),
        ),
        TextButton(
          child: const Text('Add tile overlay'),
          onPressed: _addTileOverlay,
        ),
        TextButton(
          child: const Text('Remove tile overlay'),
          onPressed: _removeTileOverlay,
        ),
        TextButton(
          child: const Text('Clear tile cache'),
          onPressed: _clearTileCache,
        ),
      ],
    );
  }
}

class _DebugTileProvider implements TileProvider {
  _DebugTileProvider() {
    boxPaint.isAntiAlias = true;
    boxPaint.color = Colors.blue;
    boxPaint.strokeWidth = 2.0;
    boxPaint.style = PaintingStyle.stroke;
  }

  static const int width = 100;
  static const int height = 100;
  static final Paint boxPaint = Paint();
  static final TextStyle textStyle = TextStyle(
    color: Colors.red,
    fontSize: 20,
  );

  @override
  Future<Tile> getTile(int x, int y, int? zoom) async {
    final ui.PictureRecorder recorder = ui.PictureRecorder();
    final Canvas canvas = Canvas(recorder);
    final TextSpan textSpan = TextSpan(
      text: '$x,$y\n$zoom',
      style: textStyle,
    );
    final TextPainter textPainter = TextPainter(
      text: textSpan,
      textDirection: TextDirection.ltr,
    );
    textPainter.layout(
      minWidth: 0.0,
      maxWidth: width.toDouble(),
    );
    final Offset offset = const Offset(0, 0);
    textPainter.paint(canvas, offset);
    canvas.drawRect(
        Rect.fromLTRB(0, 0, width.toDouble(), width.toDouble()), boxPaint);
    final ui.Picture picture = recorder.endRecording();
    final Uint8List byteData = await picture
        .toImage(width, height)
        .then((ui.Image image) =>
            image.toByteData(format: ui.ImageByteFormat.png))
        .then((ByteData? byteData) => byteData!.buffer.asUint8List());
    return Tile(width, height, byteData);
  }
}
```
</details>

<details>
<summary>Screenshots</summary>
<img width="865" alt="Screenshot 2021-11-03 at 10 49 48 AM" src="https://user-images.githubusercontent.com/22583762/140013596-61dbf6c6-0d25-4877-94aa-f474871562d7.png">
<img width="866" alt="Screenshot 2021-11-03 at 10 50 03 AM" src="https://user-images.githubusercontent.com/22583762/140013613-8ad6b040-2323-4573-9891-6443e598495c.png">

</details>

**Comment by danagbemava-nc** [comment] 2021-11-03 08:53
Issue is reproducible on `stable` and `master` with `google_maps_flutter: ^2.1.0`.

<details>
<summary>screenshots</summary>

`android`

<img width="1440" alt="Screenshot 2021-11-03 at 08 35 41" src="https://user-images.githubusercontent.com/88313112/140031121-d8fe65ee-28be-4751-98c2-f41bf71e65b7.png">

`iOS`
<img width="1440" alt="Screenshot 2021-11-03 at 08 32 32" src="https://user-images.githubusercontent.com/88313112/140031453-6de904dd-6dba-460e-a11a-ed50ba2410c1.png">

</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.566, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.566 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 607d7934c7 (4 hours ago), 2021-11-02 21:23:01 -0700
    • Engine revision 6095a13678
    • Dart version 2.15.0 (build 2.15.0-268.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • 5dd3be00 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)     • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

**Comment by krzychudz** [comment] 2022-06-09 12:18
Hi, is there any update on this issue? 

I'm having the same problem using iOS (everything works fine on Android). 
I've tested it using `iPhone XR (iOS 15.0.2) `and `iPhone 8 (iOS 14.8.1)`.

In my case the zoom level in `getTile()` method of TileProvider is always 1 level grater than the actual zoom level of the map - checked using `onCameraMove` callback.

I'm using `google_maps_flutter: ^2.1.7`

**Comment by Mathorga** [comment] 2022-11-23 09:30
Same exact issue here:
`iPhone 14 Pro (iOS 16.0.2)`
`google_maps_flutter: ^2.2.0`
any news?

**Comment by jmagman** [comment] 2022-11-28 22:02
This looks similar to https://issuetracker.google.com/issues/118016667 on the GoogleMaps iOS SDK side, and I wasn't able to track down any google_maps_flutter plugin code that would prompt this behavior.  In the given example code the `GMSMapView`'s `camera.zoom` was consistently 7, but `-[GMSTileLayer requestTileForX:y:zoom:receiver:` always passes in 9 for the zoom.

**Comment by jmagman** [comment] 2022-11-29 19:00
I've pinged the internal issue tracking this b/120832253, unfortunately there's nothing the Flutter plugin can do to work around this since it's all being processed on the GoogleMaps iOS SDK side.  Closing this.  
Follow along at https://issuetracker.google.com/issues/118016667  in the meantime to track the fix.

**Closed by jmagman** 2022-11-29 19:00 UTC
Labels: platform-ios, plugin, p: first party, p: maps, passed secondary triage, has reproducible steps, P4, found in release: 2.5, found in release: 2.6

**Comment by Mathorga** [comment] 2022-12-01 09:50
Alright, thank you for pointing us to the right direction!

**Comment by csnguyenskg** [comment] 2023-01-18 07:06
I got the same problem, is there any update?

**Comment by Mathorga** [comment] 2023-01-18 09:14
Not that I can see, looks like the official issue is still there https://issuetracker.google.com/issues/118016667 as @jmagman pointed out
