### ISSUE TITLE
[web]Can not show "Space" between chinese

### ISSUE THREAD

**Issue by sunjianan9900** [flutter/flutter#76038] opened 2021-02-15 03:31 UTC
on last channel dev , web default using SKIA , but there is a bug

<img width="201" alt="WX20210215-112232@2x" src="https://user-images.githubusercontent.com/10936316/107902048-50fa2580-6f80-11eb-90e9-5b8d3ebc3d31.png">

Cant not show "Space" between chinese
And how can I not use skia?
`flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=false` NOT WORK

[✓] Flutter (Channel dev, 1.27.0-1.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.27.0-1.0.pre at /Volumes/SDK/BETA/flutter-dev
    • Framework revision 68c96f100e (6 days ago), 2021-02-08 16:14:15 -0800
    • Engine revision b04955656c
    • Dart version 2.13.0 (build 2.13.0-0.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by pedromassangocode** [comment] 2021-02-15 08:46
Hi @sunjianan9900 
This is a duplicate of https://github.com/flutter/flutter/issues/76003. To switch to HTML renderer you have to pass: `--web-renderer html` instead of dart-define. Please follow up on that issue for more updates.
Thank you

**Comment by sunjianan9900** [comment] 2021-02-15 08:58
> Hi @sunjianan9900
> This is a duplicate of #76003. To switch to HTML renderer you have to pass: `--web-renderer html` instead of dart-define. Please follow up on that issue for more updates.
> Thank you

thanks for reply
but it's a little different
on #76003 it can not show any chinese character at all

but this issue is not about chinese character not showing up，it can load chinese character, 
but "Space" can not show up between chinese , like this:

你❌❌好！
hello   there！

when "Space" between chinese character , it comes up "x"
but  "Space" between english character , it works well

**Comment by pedromassangocode** [comment] 2021-02-15 13:24
> but this issue is not about chinese character not showing up，it can load chinese character,
> but "Space" can not show up between chinese

This makes sence, but I do believe that the root cause may be the same as https://github.com/flutter/flutter/issues/73628. @yjbanov can you please confirm?
Thank you

**Comment by yjbanov** [comment] 2021-02-16 19:18
This is being fixed in https://github.com/flutter/engine/pull/24249. We need to roll to a new version CanvasKit.

**Comment by yjbanov** [comment] 2021-02-16 19:19
Duplicate of https://github.com/flutter/flutter/issues/74742

**Closed by yjbanov** 2021-02-16 19:19 UTC
Labels: P2, a: internationalization, a: typography, e: web_canvaskit, found in release: 1.27, has reproducible steps, platform-web, severe: regression
