### ISSUE TITLE
[tool_crash] StateError: Bad state: No element

### ISSUE THREAD

**Issue by nullvoid0** [flutter/flutter#148511] opened 2024-05-16 20:33 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No element
```
#0      Stream.first.<anonymous closure> (dart:async/stream.dart:1583:9)
#1      _rootRun (dart:async/zone.dart:1391:47)
#2      _CustomZone.run (dart:async/zone.dart:1301:19)
#3      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#7      _SyncBroadcastStreamController._sendDone.<anonymous closure> (dart:async/broadcast_stream_controller.dart:399:22)
#8      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322:15)
#9      _SyncBroadcastStreamController._sendDone (dart:async/broadcast_stream_controller.dart:398:7)
#10     _BroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:268:5)
#11     _AsBroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:505:27)
#12     _rootRun (dart:async/zone.dart:1391:47)
#13     _CustomZone.run (dart:async/zone.dart:1301:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#15     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#16     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#17     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#18     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#19     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#20     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
#21     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
#22     _ErrorHandlingAsciiDecoderSink.close (dart:convert/ascii.dart:261:15)
#23     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
#24     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22621.3155], locale en-ZA)
    [32m•[39m Flutter version 3.19.5 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 300451adae (7 weeks ago), 2024-03-27 21:54:07 -0500
    [32m•[39m Engine revision e76c956498
    [32m•[39m Dart version 3.3.3
    [32m•[39m DevTools version 2.31.1

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\SGcan\AppData\Local\Android\sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[33m[!][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [31m✗[39m Unable to find bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[32m[✓][39m Android Studio (version 2023.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio1
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[32m[✓][39m VS Code (version 1.89.1)
    [32m•[39m VS Code at C:\Users\SGcan\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3155]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.208
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.67

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 300451adae589accbece3490f4396f10bdf15e6e

**Comment by danagbemava-nc** [comment] 2024-05-17 07:32
Closing this as a duplicate of https://github.com/flutter/flutter/issues/99788

**Closed by danagbemava-nc** 2024-05-17 07:32 UTC
Labels: in triage
