### ISSUE TITLE
HttpClient throw "InternalError: 'Filter error, bad data'"

### ISSUE THREAD

**Issue by sososdk** [flutter/flutter#32558] opened 2019-05-11 17:14 UTC
### My code:
```dart
  test("InternalError: 'Filter error, bad data'", () async {
    var http = HttpClient();
//    http.findProxy = (_) {
//      return 'PROXY 127.0.0.1:8888';
//    };
    var request = await http.getUrl(Uri.parse(
        'https://www.9dxs.com/modules/article/search.php?searchkey=%B2%CE%CC%EC'));
    request.followRedirects = true;
    request.maxRedirects = 10;
    request.headers
      ..add('content-type', 'application/x-www-form-urlencoded')
      ..set('user-agent',
          'Mozilla/5.0 (Windows NT 6.3; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0');
    var response = await request.close();
    await consolidateHttpClientResponseBytes(response);
  });
```

### Result:
```
Testing started at 01:04 ...
/Users/xxxx/Library/flutter/bin/flutter --no-color test --machine --plain-name "InternalError: 'Filter error, bad data'" test/widget_test.dart
dart:_http                   _HttpClient.getUrl
test/widget_test.dart 31:30  main.<fn>

InternalError: 'Filter error, bad data'
```

### flutter doctor -v
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/xxxx/Library/flutter
    • Framework revision 7a4c33425d (12 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/xxxx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/xxxx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Users/xxxx/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.1

[✓] Connected device (1 available)
    • iPhone Xʀ • CC06E74A-5414-40EF-9D0B-B59712EF14D5 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 3 categories.
```

**Comment by BondarenkoStas** [comment] 2019-10-12 12:27
@sososdk did you find a solution?

**Comment by sososdk** [comment] 2019-10-14 05:46
@BondarenkoStas I set `request.followRedirects = false;`, and handle 301 myself.

**Comment by iapicca** [comment] 2020-01-15 12:51
Hi @sososdk 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your `updated flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by sososdk** [comment] 2020-01-23 08:25
@iapicca Issue still exists.

Repo: https://github.com/sososdk/flutter_issue_32558.git

```
flutter doctor -v
[✓] Flutter (Channel master, v1.14.4-pre.28, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    • Flutter version 1.14.4-pre.28 at /Users/xxxx/Library/FlutterMaster
    • Framework revision a1fa1a3d26 (9 hours ago), 2020-01-22 14:58:46 -0800
    • Engine revision 83a64b7233
    • Dart version 2.8.0 (build 2.8.0-dev.3.0 ef0c7f16e6)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xxxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/xxxx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/xxxx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Users/xxxx/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/193.6107147/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Users/xxxx/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 82905D98-7C19-4340-9935-8D3658482601 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.
```

**Comment by VladyslavBondarenko** [comment] 2020-01-23 11:49
Hi @sososdk 
Do you need to use exactly this query `%B2%CE%CC%EC` in your url?
Interesting, I tried different combinations of these characters, but only this sequence leads to error

**Comment by sososdk** [comment] 2020-01-26 08:37
@VladyslavBondarenko 
I guess it throw the error when the search has one result.
Some Keywords: `%D4%AA%D7%F0`, `%B6%BC%CA%D0%D2%F5%D1%F4%CA%A6`

ps: Keywords are gbk encoded.

**Comment by sjsakib** [comment] 2020-06-28 00:59
I am seeing the same error on my Crashlytics dashboard. I can not recreate this on my on machine. I make an API call in the app without any query params. Seems like it's happening randomly for some users.

![Screenshot from 2020-06-28 06-48-12](https://user-images.githubusercontent.com/15678931/85934971-6a286600-b90c-11ea-856c-4892c004042c.png)

**Comment by zgramming** [comment] 2020-07-22 16:45
Same issue happen to me . 
I do http post request , inside this request i send  :

-  4 type data **String**
-  1 **integer**
-  1 **Datetime**
-  1 **File**

<img src="https://user-images.githubusercontent.com/38829404/88204193-2576bd00-cc75-11ea-91df-17b27cd90463.gif" height="400">

But i test on postman , it's working without problem :

<img width="960" alt="tanya flutter , internal error" src="https://user-images.githubusercontent.com/38829404/88204254-37f0f680-cc75-11ea-9209-7f041082d215.PNG">



### Flutter doctor -v

```
PS C:\Project Flutter\playstore_app\peduli_utang> flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18363.959], locale en-ID)
    • Flutter version 1.17.5 at C:\flutter\flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (1 available)
    • Redmi Note 4 • 1a96d23a9904 • android-arm64 • Android 7.0 (API 24)

• No issues found!
PS C:\Project Flutter\playstore_app\peduli_utang> 
```

**Comment by darshankawar** [comment] 2020-11-30 13:07
@sososdk 
I cloned your code sample repo and tested on latest stable version by tapping on FAB which incremented the counter without any issues and didn't see the aforementioned error, unless I missed to replicate it properly.

<img width="884" alt="Screenshot 2020-11-30 at 6 32 08 PM" src="https://user-images.githubusercontent.com/67046386/100613617-d899a600-333a-11eb-9ff3-21c635d774bc.png">

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

</details>

I am going ahead and closing this as resolved. If you disagree or think this should be kept open, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2020-11-30 13:07 UTC
Labels: dependency: dart, engine

**Comment by rohitsainik** [comment] 2021-07-24 08:46
you are getting this issue due to encoding try to run the request by adding 

> Accept-Encoding : * 

in Header and print response body to  find exact issue
