### ISSUE TITLE
After i did flutter upgrade. The dart extension in vscode is now not working anymore. Any one has solution to this?

### ISSUE THREAD

**Issue by Pushkar98** [flutter/flutter#16172] opened 2018-04-03 05:08 UTC
## Steps to Reproduce

Please tell us what you were doing and what went wrong. If you are running flutter tools from the command line, please try adding the `-v` or `--verbose` option to gather more information.

If the problem is with your application's rendering, please attach a screenshot and any relevant source code.
If you are getting an exception in the logs, and your code is implicated in the first few frames, then please include the source code for the functions involved.

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

Paste the output of running `flutter doctor -v` here.

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment] 2018-04-03 09:18
As the issue template states a bug report should contain the output of `flutter doctor -v`

**Comment by AxelMarquez** [comment] 2018-04-04 00:29
The same happened to me after I ran flutter upgrade, I tried re-installing dart code, re-installing VS Code and re- installing flutter with no success. I ended up installing IntelliJ Idea.

Note that the entire plugin seem to not work because the next error pops when I run >Flutter: New Project
![image](https://user-images.githubusercontent.com/8497432/38282182-62ec4d46-3774-11e8-883c-b7a8ba8f21bc.png)

But code highlighting works correctly (but other functions, like navigate to source (F12) don't work):
![image](https://user-images.githubusercontent.com/8497432/38282200-804fa856-3774-11e8-9481-597c8322a9a0.png)

My version of Dart Code is:
![image](https://user-images.githubusercontent.com/8497432/38282269-dfb34c6c-3774-11e8-8347-5be37995b463.png)

I'm using Ubuntu 17.10

Flutter doctor:
```
[✓] Flutter (Channel master, v0.2.7-pre.6, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.3)
[✓] VS Code (version 1.21.1)
[✓] Connected devices (1 available)
• No issues found!
```

**Comment by xster** [comment] 2018-04-04 00:41
cc @DanTup

**Comment by Pushkar98** [comment] 2018-04-04 06:16
[✓] Flutter (on Mac OS X 10.13.4 17E199, locale en-IN, channel dev)
    • Flutter version 0.1.4 at /Users/sahusoft/Sites/projects/flutter
    • Framework revision f914e701c5 (6 weeks ago), 2018-02-19 21:12:17 +0000
    • Engine revision 13cf22c284
    • Dart version 2.0.0-dev.27.0-flutter-0d5cf900b0

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/sahusoft/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Users/sahusoft/Downloads/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.4)
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[✓] Connected devices
    • iPhone 7 Plus • CAD5D61F-6553-427D-87E5-94D146D7935A • ios • iOS 11.2 (simulator)

**Comment by DanTup** [comment] 2018-04-04 06:38
@Pushkar98 Can you try opening VS Code, clicking `Help -> Toggle Developer Tools` and then try running `Flutter: New Project` again? If any errors or warnings appear in the dev console, please paste them here.

**Comment by zoechi** [comment] 2018-04-04 06:48
@Pushkar98 Your Flutter version is quite old. I think you should update to a more recent version.

**Comment by DanTup** [comment] 2018-04-04 07:05
Whoops, my comment was intended for @AxelMarquez! Can you please try the steps above? (it may be worth raising a separate case to avoid confusion with two different peoples problems in this one - ideally at https://github.com/Dart-Code/Dart-Code/issues).

@Pushkar98 If you just ran flutter upgrade and you're on `0.1.4` then I think something may have gone wrong; can you try running `flutter upgrade` and `flutter version` together and pasting all of the output?

**Comment by AxelMarquez** [comment] 2018-04-05 01:01
@DanTup The following error appeared in the Developer console
![image](https://user-images.githubusercontent.com/8497432/38342217-9f2f03c4-3842-11e8-83bc-62c6c969539a.png)


So I uninstalled Dart Code, manually deleted `Dart-Code.dart-code-2.11.1` folder and installed Dart Code again **and it worked!**

I’m so happy because I just couldn’t get used to IntelliJ, many thanks for the help 😊

**Comment by DanTup** [comment] 2018-04-05 07:02
Glad it's sorted - that error does suggest something was wrong. It would've been interesting to know what the contents of `/home/axel/.vscode/extensions` looked like when it was in this state. This seems like maybe a VS Code bug having a corrupt extension folder (possible related to the v2.11.2 release, maybe Code upgraded but left some reference to the old folder).

If you ever see it again, please grab a directory listing of the folder before fixing and we can open an issue with them.

Closing this as I believe both the issues in it are now resolved. If you have further issues with Dart Code, please open issues at https://github.com/Dart-Code/Dart-Code where I'll know about them sooner :-)

**Closed by DanTup** 2018-04-05 07:02 UTC
Labels: dev: ide - vscode
