### ISSUE TITLE
``Multiple widgets used the same GlobalKey.`` with nested navigator inside widget

### ISSUE THREAD

**Issue by JGeek00** [flutter/flutter#144360] opened 2024-02-29 01:41 UTC
### Steps to reproduce

Put a Navigator inside a widget and then push a route using it's key. Check code below.

### Expected results

New pushed route should only fill a part of the screen as it's a nested navigator, and the error should not appear. Check attached screenshots to see what I want to achieve.

### Actual results

I'm getting a ``Multiple widgets used the same GlobalKey.`` error all the time.

### Code sample

<details open><summary>Code sample</summary>

```dart
final webviewBookmarksKey = GlobalKey<NavigatorState>();

...

LayoutBuilder(
        builder: (context, constraints) {
          if (constraints.maxWidth > Sizes.tabletBreakpoint) {
            return Row(
              children: [
                const Expanded(flex: 2, child: _List(tabletMode: true)),
                Expanded(
                  flex: 3,
                  child: Navigator(
                    key: webviewBookmarksKey,
                    onGenerateRoute: (settings) => MaterialPageRoute(
                      builder: (context) => const SizedBox(),    // SizedBox to have empty screen at the beginning
                    ),
                  ),
                ),
              ],
            );
          } else {
            return const _List(tabletMode: false);
          }
        },
      ),

...

Navigator.of(webviewBookmarksKey.currentContext!).push(
        MaterialPageRoute(
          builder: (context) => WebViewScreen(bookmark: bookmark),
        ),
      );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_1709168990](https://github.com/flutter/flutter/assets/47545344/cd0307ac-b561-4089-ba27-ee091f4296f1)
![Screenshot_1709170703](https://github.com/flutter/flutter/assets/47545344/4299369b-df3a-4822-bb60-55b1310fee4f)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-arm64, locale es-ES)
    • Flutter version 3.19.1 on channel stable at /Users/juan/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (8 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/juan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/juan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.86.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 14 (API 34) (emulator)
    • sdk gphone64 arm64 (mobile) • emulator-5556 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.3.1 23D60 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 122.0.6261.69

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by davidhicks980** [comment] 2024-02-29 08:53
Can you provide a runnable code sample without dependencies? This can be caused by loads of issues (for example, we don't know what's in the _List widget, or whether the `webviewBookmarksKey` is scoped within a StatefulWidget or if it is declared outside of your widget).

**Comment by darshankawar** [comment] 2024-02-29 10:02
@JGeek00 
As requested above, please provide us complete runnable code sample to properly address the issue.

**Comment by JGeek00** [comment] 2024-02-29 11:43
I have found the issue. The problem was that on the widget that was being included on the nested navigator there was included a ScaffoldMessenger widget with it's global key. That global key was causing the issue.

**Comment by darshankawar** [comment] 2024-03-01 06:06
Closing as resolved based on above comment.

**Closed by darshankawar** 2024-03-01 06:06 UTC
Labels: in triage
