### ISSUE TITLE
Dead link in wiki : Process/Contributor access

### ISSUE THREAD

**Issue by battinleo** [flutter/flutter#133612] opened 2023-08-29 23:44 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Visit wiki page at https://github.com/flutter/flutter/wiki/Contributor-access#process
2. In this section, click on this link : `[the flutter-hackers team page](https://github.com/orgs/flutter/teams/flutter-hackers/members)`

### Expected results

Redirection to flutter team's member page

### Actual results

Redirection to flutter's website 404 page.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment] 2023-08-30 02:01
> Redirection to flutter team's member page

This is the result for members of the team; it's not accessible to everyone. That section is the instructions to be performed "by Flutter repo admins", who do have access to that page.

Closing as the link works as intended for anyone able to follow those steps in the first place.

**Closed by stuartmorgan** 2023-08-30 02:01 UTC
