### ISSUE TITLE
Special characters are not rendered correctly on Android

### ISSUE THREAD

**Issue by FelixMittermeier** [flutter/flutter#76792] opened 2021-02-25 17:22 UTC
Many characters which can be displayed in a native written Android app are not showing up in apps written with flutter on Android. On iOS this is working fine.

### **Steps to reproduce**
Create a simple app with a text widget and copy paste one of the following example texts into it.

### **First example text**
»zuckєrwαttєrσѕα«

### **Second example text**
• sʟᴏᴡ ᴜᴘᴅᴀᴛᴇs
• ʀᴏᴍᴀɴᴄᴇ & ᴅʏsᴛᴏᴘɪᴀ

### **Screenshots**

- iOS (rendered correctly):
![iOS-1](https://user-images.githubusercontent.com/33794642/109190230-2e90b500-7795-11eb-8e35-a31277d4eddf.jpg)
![iOS-2](https://user-images.githubusercontent.com/33794642/109190236-2f294b80-7795-11eb-8cee-66db31909cd5.jpg)
- Android (not rendered correctly):
![Android-1](https://user-images.githubusercontent.com/33794642/109190603-88917a80-7795-11eb-8596-ffdcb69bd53f.png)
![Android-2](https://user-images.githubusercontent.com/33794642/109190608-89c2a780-7795-11eb-91e1-306acd372c34.png)

### **Flutter doctor output**

```
[✓] Flutter (Channel beta, 1.26.0-17.7.pre, on macOS 11.1 20C69 darwin-x64, locale nb-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (3 available)
```

**Comment by darshankawar** [comment] 2021-02-26 07:57
@FelixMittermeier 
Tried the same on latest master and observed that special characters you provided are rendered properly on Android (Samsung S10).

1. Android:

<img width="547" alt="Screenshot 2021-02-26 at 1 22 47 PM" src="https://user-images.githubusercontent.com/67046386/109271810-07d68b00-7836-11eb-89bf-dd5e5e97ab76.png">


2. iOS:

<img width="367" alt="Screenshot 2021-02-26 at 1 20 11 PM" src="https://user-images.githubusercontent.com/67046386/109271831-102ec600-7836-11eb-8804-a7b11cb639f3.png">

<details>
<summary> code sample </summary>

```
return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('»zuckєrwαttєrσѕα«'),
              Text('sʟᴏᴡ ᴜᴘᴅᴀᴛᴇs'),
              Text('ʀᴏᴍᴀɴᴄᴇ & ᴅʏsᴛᴏᴘɪᴀ')
            ],
          )
        ),
      ),
    );

```

</details>

Can you provide which Android device and version has this issue ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.27.0-9.0.pre.106, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.27.0-9.0.pre.106 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1610a27476 (4 hours ago), 2021-02-25 20:26:02 -0800
    • Engine revision 1515b1d4a4
    • Dart version 2.13.0 (build 2.13.0-79.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM G975F (mobile)          • RZ8M802WY0X                          •
      android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.

```

</details>

**Comment by FelixMittermeier** [comment] 2021-02-26 08:09
@darshankawar It occurred on the Google Pixel 3 XL with the latest Android 11 software update.

**Comment by darshankawar** [comment] 2021-02-26 11:08
@FelixMittermeier 
Since I don't have the said physical device, but tried it on Pixel XL (api 30) emulator on which too, the text is rendered properly:

<img width="352" alt="Screenshot 2021-02-26 at 4 36 41 PM" src="https://user-images.githubusercontent.com/67046386/109292815-f353bc00-7850-11eb-8461-56796ffac146.png">

So I am not sure if it's specific to device model, make and OS. Can you try it on other device (not Pixel) and see if issue persists ?

**Comment by FelixMittermeier** [comment] 2021-02-27 09:32
@darshankawar I cannot test it on another physical device right now. But if it is working for you on the latest master on api 30 then it might already be fixed. I cannot upgrade to the lastest master version right now due to some build errors there.
I am going to close it for now and might reopen it later if the issue still exists in the new version. 👍🏻

**Comment by FelixMittermeier** [comment] 2021-03-03 23:14
@darshankawar So I just upgraded to the latest flutter 2 today but unfortunately it does not look like it is fixed.
As mentioned above it is not working on the Pixel 3 XL (mobile) with Android 11 (API 30) and also not on web with Google Chrome 88.0.4324.192.
Maybe the issue only appears when used in combination with a custom font because I am using https://fonts.google.com/specimen/Quicksand?preview.text_type=custom for every text style. But due to the fact it is working fine on iOS I really think there is something wrong.
Would be great if you could have a look at it again. Thank you.

**Comment by darshankawar** [comment] 2021-03-04 06:28
Thanks @FelixMittermeier for getting back.
When you mentioned not working on web, I tried the same sample code using latest dev (2.1.0) and noticed below after running `flutter run -d chrome` which defaults to canvaskit rendering:

<img width="773" alt="Screenshot 2021-03-04 at 11 53 39 AM" src="https://user-images.githubusercontent.com/67046386/109920601-8ae95c80-7ce0-11eb-8424-b9eebc3d15c2.png">

With html renderer though, the text renders properly:

<img width="749" alt="Screenshot 2021-03-04 at 11 54 36 AM" src="https://user-images.githubusercontent.com/67046386/109920691-aa808500-7ce0-11eb-9a2e-3facc126e1a7.png">

Note that I didn't use the custom font you mentioned above. Could you confirm if this is the correct interpretation of the issue ?
I wasn't able to verify this on Android since the latest OS device I've is 10 and don't have Pixel device too.

**Comment by FelixMittermeier** [comment] 2021-03-04 08:31
Yeah I can confirm that it is working with the html renderer. It only fails while using the canvaskit 👍🏻

**Comment by darshankawar** [comment] 2021-03-04 11:41
@FelixMittermeier 
Thanks for confirming. I believe this issue is duplicate of https://github.com/flutter/flutter/issues/77212 which seem to have regressed. Original issue https://github.com/flutter/flutter/issues/73628 which was fixed and merged but came back in form of 77212.  Since it is already triaged and assigned labels, I'll close this one in favor of 77212. Please follow-up there for updates.
If you disagree, write in comments and I'll reopen this.

**Closed by darshankawar** 2021-03-04 11:41 UTC
Labels: in triage
