### ISSUE TITLE
multicast_dns is giving socket exception and failing to provide interface listing on Android platform.

### ISSUE THREAD

**Issue by neerajyadv** [flutter/flutter#27346] opened 2019-01-31 09:57 UTC
### **Error:-**
```
D/libc-netbsd( 9156): [getaddrinfo]: hostname=0.0.0.0; servname=(null); netid=0; mark=0
D/libc-netbsd( 9156): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
E/flutter ( 9156): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed listing interfaces (OS Error: Listing interfaces is not supported on this platform)
E/flutter ( 9156): #0      _NativeSocket.listInterfaces.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:414:9)
E/flutter ( 9156): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 9156): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 9156): #3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter ( 9156): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter ( 9156): #5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter ( 9156): #6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter ( 9156): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter ( 9156): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 9156): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 9156): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 9156): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 9156): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 9156): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```
### **Flutter** Doctor Output :-
```
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.2.0, on Linux, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[!] VS Code (version 1.30.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
### **Steps** to reproduce:-
1. Import multicast_dns plugin
2. Use the multicast_resolve.dart code as provided in the example app (changing the .local domain to own)
3. run the app

**Comment by zoechi** [comment] 2019-01-31 10:12
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment] 2019-01-31 10:14
@dnfield

**Comment by neerajyadv** [comment] 2019-01-31 10:21
> To investigate we would need a minimal runnable reproduction
> as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

`
import 'package:multicast_dns/multicast_dns.dart';
import 'package:flutter/material.dart';

void main() => runApp(TestMDNS());

class TestMDNS extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'mDNS',
      home: CheckApp(),
    );
  }
}

class CheckApp extends StatefulWidget {
  @override
  CheckAppState createState() {
    return CheckAppState();
  }
}

class CheckAppState extends State<CheckApp> {
  @override
  void initState() {
    test(['esp.local']);
    super.initState();
  }

  test(List<String> args) async {
    if (args.length != 1) {
      print('''Please provide an address as argument.
      For example: dart mdns-resolve.dart dartino.local''');
      return;
    }

    final String name = args[0];

    final MDnsClient client = MDnsClient();
    await client.start();
    await for (IPAddressResourceRecord record
        in client.lookup<IPAddressResourceRecord>(
            ResourceRecordQuery.addressIPv4(name))) {
      print('Found address (${record.address}).');
    }

    await for (IPAddressResourceRecord record
        in client.lookup<IPAddressResourceRecord>(
            ResourceRecordQuery.addressIPv6(name))) {
      print('Found address (${record.address}).');
    }
    client.stop();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text("Testing mDNS"),
      ),
      body: Container(
        child: Center(
          child: Text("mDNS"),
        ),
      ),
    );
  }
}
`

This is the code which is resulting in a error.

**Comment by zoechi** [comment] 2019-01-31 10:50
I get
```
Launching lib/main.dart on Pixel XL in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/flutter0generi(21064): Late-enabling -Xcheck:jni
I/flutter0generi(21064): The ClassLoaderContext is a special shared library.
Syncing files to device Pixel XL...
E/Dart    (21064): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:110: `reusePort` not supported for Android.
E/flutter (21064): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed listing interfaces (OS Error: Listing interfaces is not supported on this platform)
E/flutter (21064): #0      _NativeSocket.listInterfaces.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:414:9)
E/flutter (21064): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (21064): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (21064): #3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (21064): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (21064): #5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (21064): #6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter (21064): #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter (21064): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (21064): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (21064): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (21064): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (21064): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (21064): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (21064): 
```
```
[✓] Flutter (Channel master, v1.1.10-pre.205, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by dnfield** [comment] 2019-01-31 12:41
I'll check.  This may be a problem in dart upstream.

**Comment by dnfield** [comment] 2019-01-31 13:03
Hmm.  I've only tested this lib ok the main machine, not on a device.  It looks like Android doesn't support listing interfaces or reuse port.

Reuse port might be ok, but it's also possible this approach won't work ok Android.

Right now the intent of this library is for use in the tooling to find the device.  If I can make it work on the device I'll try, otherwise you may need to use a plug-in that wraps NsdManager

**Comment by neerajyadv** [comment] 2019-01-31 16:57
So does this mean that this plugin is not use for any service on Android platform?

**Comment by dnfield** [comment] 2019-01-31 18:04
Not right now.  But that should be fixable.

**Comment by neerajyadv** [comment] 2019-02-01 04:54
Can that be done by me? Or the fix would be coming from your side?

**Comment by harshvardhan** [comment] 2019-02-27 15:17
Hey any resolution on this one?
I thought its an AndroidX issue. But even after successfully migrating to AndroidX, I still getting this:
[main.dart.zip](https://github.com/flutter/flutter/files/2910908/main.dart.zip)

```
Syncing files to device ONEPLUS A5000...
V/FA      (19647): Inactivity, disconnecting from the service
E/flutter (19647): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'List<String>' is not a subtype of type 'ReactiveFeedsRepository' of 'feedsRepository'
E/flutter (19647): #0      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:185:38)
E/flutter (19647): #1      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (19647): #2      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (19647): #3      _runZoned (dart:async/zone.dart:1516:10)
E/flutter (19647): #4      runZoned (dart:async/zone.dart:1500:12)
E/flutter (19647): #5      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
E/flutter (19647): #6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
E/flutter (19647): #7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter (19647): 
```

**Comment by dnfield** [comment] 2019-02-27 15:20
Dart doesn't support this plug-in yet on Android

**Comment by harshvardhan** [comment] 2019-02-27 15:25
> Dart doesn't support this plug-in yet on Android

Can you please explain which plug-in. Because I was running this fine till yesterday.

**Comment by dnfield** [comment] 2019-02-27 15:35
multicast_dns calls a method that always throws on Android right now.

**Comment by harshvardhan** [comment] 2019-02-27 15:45
> multicast_dns calls a method that always throws on Android right now.

Thanks for the reply.

Although I am not using `multicast_dns` but using many other things like `crashlytics`, `path_provider`, `firebase_auth`, `firebase_messaging`, `cloud_firestore`, `redux` etc. Is there a deterministic way to find out what is the root cause. Because i am not getting a breakpoint hit even at the first line of the main method.

For more details please see [this issue](https://github.com/flutter/flutter/issues/28564)

**Comment by lherman-cs** [comment] 2019-03-02 19:18
@dnfield is android implementation going to be fixed soon? I'm trying to decide which feature I should add next to my app. Thanks!

**Comment by dnfield** [comment] 2019-03-02 20:11
I don't have an estimate at this point in time.

**Comment by leapit** [comment] 2019-03-17 13:10
```
class Helper {
  static Future getNetworkIP() async {
    String _networkInterface;
    await NetworkInterface.list(
            includeLoopback: false, type: InternetAddressType.any)
        .then((List<NetworkInterface> interfaces) {
      _networkInterface = "";
      interfaces.forEach((interface) {
        int i = 0;
        interface.addresses.forEach((address) {
          _networkInterface += "${address.address}";
        });
      });
    });
    return _networkInterface;
  }
}
```

when call `await Helper.getNetworkIP();` on Android,failed,throw something like title issue

**Comment by MeMoSalem** [comment] 2019-04-02 02:12
if u added the internet permission in Manifest file then check the internet connection on the your pc in emulator case and check the internet connection on the device your using in case you are using physical device

**Comment by dnfield** [comment] 2019-04-25 06:39
Dart has landed a fix for this upstream.  I'm not sure if or when it will roll into the Flutter framework, but it should be avialable on master sometime before long now.

**Comment by nermolov** [comment] 2019-05-21 02:06
@dnfield any updates on when this will be rolled in?

**Comment by dnfield** [comment] 2019-05-21 02:10
I'm not sure if this made the latest stable but it may have.  It should be available on dev otherwise

**Closed** 2019-05-21 02:13 UTC
Labels: dependency: dart, p: first party, p: multicast_dns, plugin, severe: crash

**Comment by bobatsar** [comment] 2019-05-21 07:18
Unfortunately it seems it didn't make it in the last release. Will this work for all platforms? Would be really nice to have a simple solution to use service discovery.

**Comment by dnfield** [comment] 2019-05-21 13:19
Does this still crash on master?

**Comment by leapit** [comment] 2019-05-24 06:02
@dnfield seems still crash on Android

**Comment by bobatsar** [comment] 2019-06-21 13:08
@dnfield  just tested with current "beta" channel and it seems to work. So this should hopefully land soon in stable.

**Comment by artrmz** [comment] 2019-06-26 09:17
@bobatsar Are you sure you are on `beta` channel? I am on `dev` and I am still getting
```
`reusePort` not supported for Android.
```

**Comment by donic46** [comment] 2019-08-19 09:32
> @bobatsar Are you sure you are on `beta` channel? I am on `dev` and I am still getting
> 
> ```
> `reusePort` not supported for Android.
> ```
> 
> ```
> [✓] Flutter (Channel dev, v1.7.9, on Mac OS X 10.14.5 18F132, locale en-PL)
> ```

Same here.

**Comment by artrmz** [comment] 2019-08-19 09:39
@dnfield shall it be reopened?

**Comment by bobatsar** [comment] 2019-08-19 10:54
I just run my test app and it works on stable channel.

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale de_DE.utf8)

multicast_dns:  version: "0.1.1"

**Comment by bobatsar** [comment] 2019-08-19 11:15
When upgrading to multicast_dns 0.2.0 I get the same error.
`
Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:110: `reusePort` not supported for Android.
`

**Comment by ElArtista** [comment] 2019-10-22 09:51
Same here in 0.2.2...

**Comment by stefan01** [comment] 2019-11-30 15:10
Same issue for me :/

**Comment by mrbanana3000** [comment] 2019-12-02 23:42
Same

multicast_dns v0.2.2

Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:114: `reusePort` not supported for Android

**Comment by dnfield** [comment] 2019-12-02 23:48
You have to provide your own `RawDatagramSocketFactory` to the client that doesn't try to reusePort.

**Comment by ali80** [comment] 2019-12-13 15:54
same issue on v0.2.2 , it throws the exception then it finds the right IP!  so why this issue is closed, maybe mention in docs this does not currently support android

**Comment by githubforsank** [comment] 2020-03-01 14:24
This issue has been opened since 1 year, Any update on this ?

**Comment by Sandeep-GitAcc** [comment] 2020-03-02 18:19
Has anyone found any fix for this issue or workaround? I have tried using multiple other plugins. mdns2 was failing 
D/MDNSPlugin( 5393): onStartDiscoveryFailed:

Same for MDNSPlugin

using multicast_dns plugin 0.1.1 and 0.2.2 version giving error
(12148): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:114: `reusePort` not supported for Android.

**Comment by dnfield** [comment] 2020-03-02 18:26
The issue is closed because it's fixed.  I commented about the reuse port issue here: https://github.com/flutter/flutter/issues/27346#issuecomment-560931996

**Comment by ychawla29** [comment] 2020-03-03 05:45
can you example code of how to pass RawDatagramSocketFactory to the client @dnfield

**Comment by dnfield** [comment] 2020-03-03 15:52
```dart
var factory = (dynamic host, int port,
    {bool reuseAddress, bool reusePort, int ttl}) {
  return RawDatagramSocket.bind(host, port, reuseAddress: true, reusePort: false, ttl: tll);
};

var client = MDnsClient(rawDatagramSocketFactory: factory);
```

**Comment by lucafaggianelli** [comment] 2020-05-05 12:45
@dnfield It would be nice if you can reference the solution in the official examples for `multicast_dns`, that is, here: https://github.com/flutter/packages/tree/master/packages/multicast_dns/example
