### ISSUE TITLE
TextOverflow.ellipsis didn't work well when string contains multiple languages

### ISSUE THREAD

**Issue by dujianchi** [flutter/flutter#43332] opened 2019-10-23 11:02 UTC
## Steps to Reproduce
1. there is my code:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  final _list = [
    'This is very very very very very big mistake!!!!',
    'This?is?very?very?very?very?very?big?mistake!!!!',
    'This>is>very>very>very>very>very>big>mistake!!!!',
    'This,is,very,very,very,very,very,big,mistake!!!!',
    '这是一个 非常 非常 非常 非常 非常 非常 非常 非常 非常 非常 严重 的 错误',
    '这是一个>very,very,very,very,very,big,mistake!!!!',
    'これは very,very,very,very,very,big,mistake!!!!',
    'これはvery,very,very,very,very,big,mistake!!!!',
    '이것은 very,very,very,very,very,big,mistake!!!!',
    '이것은very,very,very,very,very,big,mistake!!!!',
    '这是一个very매우매우매우매우mistake',
    '这是一个very매우매우매우매우mistake',
    'これはvery매우매우매우매우mistake',
    'これは1111111111111111111111111111',
    '这是一个>1111111111111111111111111111',
    'This is 非常 非常 非常 非常 非常 非常 非常 非常 非常 非常 严重 的 错误',
    'This is 非常に非常に非常に大きな間違いです',
  ];
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('title'),
        ),
        body: ListView.builder(
          itemBuilder: (context, index) => Text(
            _list[index],
            style: TextStyle(fontSize: 26.0,color: Colors.blueAccent),
            overflow: TextOverflow.ellipsis,
          ),
          itemCount: _list.length,
        ),
      ),
    );
  }
}

```

2.run it, and it just like this:
![image](https://user-images.githubusercontent.com/7309424/67386043-d22cec80-f5c6-11e9-9e69-2b0fdefb4b70.png)

3. see the 6/7/8/9/10/14/15 line, I think they should like other lines.

**Target Platform: Android**
**Target OS version/browser: Android 4.4**
**Devices:Huawei G620S(I think every Android device is same)**

## Logs
and there is my flutter version

```
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15 19A602, locale zh-Hans-CN)
    • Flutter version 1.10.7 at /Users/do/Dev/flutter
    • Framework revision e70236e36c (3 周前), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/do/Dev/android-sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/do/Dev/android-sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.6817.14

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • G620S UL00 • 582af71dfac3 • android-arm • Android 4.4.4 (API 19)

! Doctor found issues in 1 category.
```

**Comment by GaryQian** [comment] 2020-04-30 10:26
We are aware of this problem. It is caused by our ellipsis system computes ellipsis per run but cannot consider more than one run at a time.

We expect this to be fixed once we switch text shaping backends to SkParagraph: https://github.com/flutter/flutter/issues/39420

**Comment by pedromassangocode** [comment] 2020-09-10 13:47
(triage)

Reproducible on latest stable channel.


<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.20.3 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 216dee60c0 (9 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5556 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by kf6gpe** [comment] 2020-12-10 20:34
@jason-simmons Another one that may be affected by the SkParagraph migration?

**Comment by 18633847058** [comment] 2021-02-26 08:14
Why hasn't this problem been solved for so long time？

**Comment by ybin0823** [comment] 2022-07-22 08:58
also `flutter 3.0.5`

**Comment by darshankawar** [comment] 2023-01-03 11:03
Verified this issue using latest versions and observed that the issue persists. The text which is combination of non-English + English doesn't ellipse properly like other text which is provided in the code sample.

<img width="350" alt="Screenshot 2023-01-03 at 4 31 11 PM" src="https://user-images.githubusercontent.com/67046386/210345084-53c1b49b-18f4-497c-89c1-e3b067f6683d.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.10 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (15 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.7.0-13.0.pre.138, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.7.0-13.0.pre.138 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b938dc13df (18 hours ago), 2023-01-02 05:47:23 -0500
    • Engine revision 472e34cbbc
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by AmirhosseinShk** [comment] 2023-05-03 16:30
this is our issue too, please fix this asap

**Comment by LongCatIsLooong** [comment] 2024-06-01 02:24
This doesn't seem to be reproducible on 3.22.1

**Closed by LongCatIsLooong** 2024-06-01 02:24 UTC
Labels: framework, engine, a: internationalization, a: typography, has reproducible steps, P2, found in release: 3.3, found in release: 3.7, team-engine, triaged-engine
