### ISSUE TITLE
Scaffold assumes that it is always the height of the device, breaking nested scaffolds

### ISSUE THREAD

**Issue by shrugs** [flutter/flutter#24768] opened 2018-11-27 07:26 UTC
## Description

A Scaffold assumes that it is always the height of the device, so when calculating the `contentBottom` in order to avoid the keyboard, it doesn't include its own offset from the bottom of the screen, resulting in blank space between the keyboard and the `body`.

This behavior occurred for me when attempting to nest scaffolds and create an ios-style BottomNavigationBar layout. The BottomNavigationBar is hosted via Scaffold, and within each tab, I'd like to use a scaffold for the appBar and keyboard avoidance logic.

## Example

<div>
<img width="48%" alt="screen shot 2018-11-27 at 4 06 36 pm" src="https://user-images.githubusercontent.com/1535001/49064602-c160e300-f25e-11e8-8136-e9f6485fe958.png">
<img width="48%" alt="screen shot 2018-11-27 at 4 07 55 pm" src="https://user-images.githubusercontent.com/1535001/49064604-c160e300-f25e-11e8-9693-076b1ca3ca65.png">
</div>

## Proposed Solution

On line [332 in scaffold.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scaffold.dart#L332), we calculate the `contentBottom` using the `viewInsets.bottom` of the screen, but without subtracting the widget's own offset from the bottom of the screen. In my screenshots, there's a BottomNavigationBar of height `57 + viewInsets.bottom` behind the keyboard, so the extra space is equal to `57 + viewInsets.bottom` points.

I'm not quite sure where we'd be able to grab the screen height, but if we could get the screen height, the correct minInsets.bottom calculation would be be `viewInsets.bottom - (screenHeight - widgetHeight)`.

## Work Around

My workaround at the moment is to make sure that all scaffolds are indeed full screen by putting them in a stack and giving them an empty `bottomNavigationBar` container.

(for context, `SwitchStack` is just a Stack with Offstage/TickerMode children, and `BetterNavigationBar` is a simple `Row` of `IconButton`s)

```dart
  Widget build(BuildContext context) {
    return Material(
      child: Stack(
        children: <Widget>[
          SwitchStack(
            children: paths
                .map((p) => FocusScope(node: nodes[p], child: routes[p]))
                .toList(),
            index: currentIndex,
          ),
          Align(
            alignment: Alignment.bottomCenter,
            child: BetterNavigationBar(
              currentIndex: currentIndex,
              onTap: _handleItemSelected,
              items: [
                _buildTabItem(Icons.crop_square, "Spaces"),
                _buildTabItem(Icons.donut_large, "Circles"),
                _buildTabItem(Icons.add, "Action"),
                _buildTabItem(Icons.format_align_justify, "Lines"),
                _buildTabItem(Icons.account_circle, "Dot"),
              ],
            ),
          ),
        ],
      ),
    );
  }
```

and each one of those routes renders something like

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: appBar,
      body: body,
      bottomNavigationBar: Container(
        height:
            kBottomNavigationBarHeight + MediaQuery.of(context).padding.bottom,
        color: Colors.transparent,
      ),
    );
  }
```

## `flutter doctor -v`

```
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.11.3 at /Users/matt/.flutter-sdk
    • Framework revision 72bf075e8d (2 weeks ago), 2018-11-09 20:36:17 -0800
    • Engine revision 5646e86a6f
    • Dart version 2.1.0 (build 2.1.0-dev.9.3 9c07fb64c4)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/matt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/matt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (1 available)
    • Rose iPhone • 1af0c70e23fe6c60e7f570442a106b3ea6e33db0 • ios • iOS 12.1

• No issues found!
```

**Comment by xqwzts** [comment] 2018-11-27 14:03
I feel like nested Scaffolds is not the most optimal way to go about this, rather have you considered using [CupertinoTabScaffold](https://docs.flutter.io/flutter/cupertino/CupertinoTabScaffold-class.html) which has that nested navigation model baked in?

**Comment by shrugs** [comment] 2018-11-28 02:32
@xqwzts doh! I definitely should have taken a look at that file before charging in head first here; thanks for the link.

It looks like CupertinoTabScaffold pulls a similar pattern as my workaround stack, including bumping each tab up using a MediaQuery with padding (instead of a face bottom nav bar). It works well with a `CupertinoPageScaffold` because the PageScaffold uses the normal `build` method instead of a multi child delegate to layout its children, which means I think it'll handle the viewInsets correctly. 

I think my next step will be implementing something very similar to the cupertino tab scaffold and page scaffold, but with either Material widgets or arbitrary `Widget`s.

---

Do you think it's worth keeping this issue? I understand that nested scaffolds were not the original use-case for Scaffold at all, but it does seem like a pattern that's worth supporting (although maybe it's best to put this in a package somewhere).

**Comment by zoechi** [comment] 2018-12-20 15:54
Duplicate of #23106

**Closed by zoechi** 2018-12-20 15:54 UTC
Labels: f: material design, framework, severe: new feature
