### ISSUE TITLE
Impeller: Strange issue with path fills

### ISSUE THREAD

**Issue by lyceel** [flutter/flutter#157885] opened 2024-10-30 21:51 UTC
Using the new Impeller interop toolkit, and I've run into a fairly elusive issue that causes path fills to not be drawn when they should.

The issue seems to involve interactions between transforms, clip regions, and the DisplayListBuilder save stack. After adding lots of logging, I've reduced the issue down to a fairly simple example:  https://gist.github.com/lyceel/de6d80caffb3c209d3dadbdfd10447de

With the code as it is, the path is not filled at all:

![incorrect](https://github.com/user-attachments/assets/90a2e688-480d-4a5f-8c2d-e2d4af6aa433)

If either the rounded rectangle's transform (Option 1 comment), or the unused clip (Option 2) are commented out, the path is filled properly with red:

![correct](https://github.com/user-attachments/assets/90824d2c-09cd-46dd-a492-fc67977aa893)

I recognize that the simple solution would be to remove the useless save/clip/restore block in the middle, but this is much more difficult to prevent in the real-world use case where this issue was discovered.

**Comment by jason-simmons** [comment] 2024-10-31 20:45
This issue started with the switch to the experimental canvas.

Possibly this is similar to the issue seen in https://github.com/flutter/flutter/issues/153504?

**Comment by chinmaygarde** [comment] 2024-10-31 20:52
Thanks for the breadcrumb. I'll compare different backends and attempt a fix if thats the case.

**Comment by jason-simmons** [comment] 2024-10-31 21:31
Converted the example to a `DisplayListBuilder` based test case:
https://gist.github.com/jason-simmons/f9e450e3f8379a14a1de7381299e16c8

Using this, the issue reproduces on the GLES back end but not Metal.

**Comment by chinmaygarde** [comment] 2024-10-31 22:11
The intersect clip prep call seems to be doing some funky stuff to the depth buffer on OpenGL. The Metal backend comparison is 
<img width="2449" alt="Screenshot 2024-10-31 at 3 10 11 PM" src="https://github.com/user-attachments/assets/07869fdd-51aa-41bd-bb77-4bb2748c9144">

**Comment by chinmaygarde** [comment] 2024-11-01 21:00
This will be fixed in https://github.com/flutter/engine/pull/56310

**Comment by jonahwilliams** [comment] 2024-11-01 21:21
Fixed in https://github.com/flutter/engine/pull/56310

**Closed by jonahwilliams** 2024-11-01 21:21 UTC
Labels: engine, customer: google, e: impeller, team-engine, e: libimpeller

**Comment by lyceel** [comment] 2024-11-01 22:04
Thanks for the quick turnaround!
