### ISSUE TITLE
Flutter 2.2.3 stable iOS DSYM is not found

### ISSUE THREAD

**Issue by WilliamMaybe** [flutter/flutter#86920] opened 2021-07-23 07:26 UTC
Flutter 2.2.3 engine is 241c87ad800beeab545ab867354d4683d5bfb6ce, but this link is error
https://storage.cloud.google.com/flutter_infra/flutter/241c87ad800beeab545ab867354d4683d5bfb6ce/ios-release/Flutter.dSYM.zip

**Comment by TahaTesser** [comment] 2021-07-23 12:36
duplicate of https://github.com/flutter/flutter/issues/86920

**Closed by TahaTesser** 2021-07-23 12:36 UTC
Labels: engine, passed first triage, team: infra

**Comment by jmagman** [comment] 2021-07-23 17:05
@WilliamMaybe the link is now https://storage.cloud.google.com/flutter_infra_release/flutter/241c87ad800beeab545ab867354d4683d5bfb6ce/ios-release/Flutter.dSYM.zip, apologies for any confusion.  Where did you find that `https://storage.cloud.google.com/flutter_infra/` link?  It looks like we missed updating it a few places in our documentation.

**Comment by WilliamMaybe** [comment] 2021-07-24 02:02
https://github.com/flutter/flutter/wiki/Crashes
It's updated now?

**Comment by jmagman** [comment] 2021-07-27 17:09
> https://github.com/flutter/flutter/wiki/Crashes
> It's updated now?

Yes, it's updated now.  Thanks!
