### ISSUE TITLE
NesteScrollView example bugs

### ISSUE THREAD

**Issue by christian-muertz** [flutter/flutter#53130] opened 2020-03-23 22:04 UTC
The [sample](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html) in the NestedScrollView documentation does not look right when over scroll and then directly scroll down. I recorded the screen on an iPhone XS:

![ST21-1](https://user-images.githubusercontent.com/14054224/77367342-390f2700-6d5a-11ea-81c5-5dd1c9ffdf5d.gif)

The tab bar moves up for like 2 or 3 frames and then goes back to its original position which then looks like a flicker.

## Doctor 
```
[✓] Flutter (Channel master, v1.16.2-pre.48, on Mac OS X 10.15.3 19D76, locale de-DE)
    • Flutter version 1.16.2-pre.48 at /Users/chris/Development/flutter
    • Framework revision 2a8e7b7bf1 (87 minutes ago), 2020-03-23 13:36:01 -0700
    • Engine revision 2d42c74a34
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 ba8baa46b4)
```

## Sample
The sample i used to record the vidoe:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

final _tabs = ['1', '2', '3'];

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: DefaultTabController(
          length: _tabs.length,
          child: NestedScrollView(
            headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
              return <Widget>[
                SliverOverlapAbsorber(
                  handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                  sliver: SliverAppBar(
                    title: const Text('Books'),
                    pinned: true,
                    expandedHeight: 350.0,
                    forceElevated: innerBoxIsScrolled,
                    bottom: TabBar(
                      tabs: _tabs.map((String name) => Tab(text: name)).toList(),
                    ),
                  ),
                ),
              ];
            },
            body: TabBarView(
              children: _tabs.map((String name) {
                return SafeArea(
                  top: false,
                  bottom: false,
                  child: Builder(
                    builder: (BuildContext context) {
                      return CustomScrollView(
                        key: PageStorageKey<String>(name),
                        slivers: <Widget>[
                          SliverOverlapInjector(
                            handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                          ),
                          SliverPadding(
                            padding: const EdgeInsets.all(8.0),
                            sliver: SliverFixedExtentList(
                              itemExtent: 48.0,
                              delegate: SliverChildBuilderDelegate(
                                    (BuildContext context, int index) {
                                  return ListTile(
                                    title: Text('Item $index'),
                                  );
                                },
                                childCount: 30,
                              ),
                            ),
                          ),
                        ],
                      );
                    },
                  ),
                );
              }).toList(),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by Piinks** [comment] 2020-03-25 22:28
Hi @christian-muertz, thanks for your contribution. This appears to be a duplicate of #29264. Please track that issue for updates. If you believe we've made an error, please reply here with more details that explain the difference and we'll re-open this issue. Thanks! :)

**Closed by Piinks** 2020-03-25 22:28 UTC
Labels: a: quality, f: scrolling, framework, has reproducible steps, ⌺‬ platform-ios
