### ISSUE TITLE
facing issue in google map

### ISSUE THREAD

**Issue by shreyakarad** [flutter/flutter#131124] opened 2023-07-22 13:16 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

google_maps_flutter: ^2.3.1

I have 3 bottom-bar in my application

1. Map 2. Route 3. User
2. when user come to this page first time map load successfully without error 
3. but when user normally change bottom-bar and goto map bottom bar then unfortunately app crash

and through this log in terminal

E/AndroidRuntime(25510): FATAL EXCEPTION: GLThread 219040
E/AndroidRuntime(25510): Process: com.tecell.android, PID: 25510
E/AndroidRuntime(25510): java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime(25510): 	at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.i(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):2)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.d(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):3)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.d.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):2)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):12)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.bx.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):29)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.bq.b(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):157)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.at.run(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):48)

### Actual results

normally working fine

### Logs

<details>
<summary>Logs</summary>

```console

E/AndroidRuntime(25510): FATAL EXCEPTION: GLThread 219040
E/AndroidRuntime(25510): Process: com.tecell.android, PID: 25510
E/AndroidRuntime(25510): java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime(25510): 	at java.nio.ByteBufferAsIntBuffer.put(ByteBufferAsIntBuffer.java:122)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.i(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):2)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.d(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):3)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.d.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):2)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):12)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.bx.s(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):29)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.bq.b(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):157)
E/AndroidRuntime(25510): 	at com.google.maps.api.android.lib6.gmm6.vector.at.run(:com.google.android.gms.dynamite_mapsdynamite@232414037@23.24.14 (150400-0):48)

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.10.6, on macOS 12.3.1 21E258 darwin-x64, locale en-IN)
    • Flutter version 3.10.6 on channel stable at /Users/user/Downloads/flutter 4
    ! Warning: `flutter` on your path resolves to /Users/user/Downloads/flutter3.0.2/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/user/Downloads/flutter 4. Consider adding /Users/user/Downloads/flutter 4/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/user/Downloads/flutter3.0.2/bin/cache/dart-sdk/bin/dart, which is not inside your current Flutter SDK checkout at /Users/user/Downloads/flutter 4. Consider adding /Users/user/Downloads/flutter 4/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (10 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

```

</details>

**Comment by danagbemava-nc** [comment] 2023-07-24 07:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/105965. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-07-24 07:42 UTC
Labels: in triage
