### ISSUE TITLE
TextField - can't delete space character when typing in RTL languages 

### ISSUE THREAD

**Issue by royibernthal** [flutter/flutter#57732] opened 2020-05-21 12:42 UTC
flutter doctor -v is perfect.

When typing inside of a TextField in Hebrew (a right to left language) on an IOS device, I can't delete the space character.

It doesn't reproduce on Android.

**Comment by VladyslavBondarenko** [comment] 2020-05-21 14:23
Reproduces with current stable, beta, dev and master.

Doesn't delete space. Deletes on very long press and throws exception at some point:

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/17024977/82568386-63793700-9b87-11ea-8e4b-f2954a0af70a.gif)

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following StateError was thrown during paint():
flutter: Bad state: No element
flutter:
flutter: The relevant error-causing widget was:
flutter:   TextField file:///Users/nevercode/dev/AndroidStudioProjects/testapp/lib/main.dart:16:18
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      List.first (dart:core-patch/array.dart:123:5)
flutter: #1      RenderEditable.getEndpointsForSelection (package:flutter/src/rendering/editable.dart:1461:41)
flutter: #2      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2140:33)
flutter: #3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
flutter: #4      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #5      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
flutter: #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #9      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:391:12)
flutter: #10     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4849:13)
flutter: #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
flutter: #12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #13     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
flutter: #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
flutter: #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
flutter: #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
flutter: #24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
flutter: #25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:131:15)
flutter: #26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2264:7)
flutter: #27     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
flutter: #28     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
flutter: #29     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:980:29)
flutter: #30     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
flutter: #31     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
flutter: #32     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #33     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #34     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
flutter: #35     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
flutter: #39     _invoke (dart:ui/hooks.dart:277:10)
flutter: #40     _drawFrame (dart:ui/hooks.dart:235:3)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderEditable#99ad3 relayoutBoundary=up14:
flutter:   creator: _Editable-[GlobalKey#e4f7c] ← Semantics ← CompositedTransformTarget ←
flutter:     IgnorePointer-[GlobalKey#dd822] ← Semantics ← _PointerListener ← Listener ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#93930] ← _PointerListener ← Listener
flutter:     ← _ScrollableScope ← Scrollable ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=414.0, 0.0<=h<=527.0)
flutter:   size: Size(414.0, 19.0)
flutter:   cursorColor: Color(0xff2196f3)
flutter:   showCursor: ValueNotifier<bool>#85eee(true)
flutter:   maxLines: 1
flutter:   minLines: null
flutter:   selectionColor: Color(0xff90caf9)
flutter:   textScaleFactor: 1.0
flutter:   locale: en_US
flutter:   selection: TextSelection(baseOffset: 36, extentOffset: 37, affinity: TextAffinity.downstream,
flutter:     isDirectional: false)
flutter:   offset: ScrollPositionWithSingleContext#64bb0(offset: -1.5, range: 0.0..0.0, viewport: 414.0,
flutter:     ScrollableState, BouncingScrollPhysics -> RangeMaintainingScrollPhysics,
flutter:     BallisticScrollActivity#c7929(AnimationController#a9f86(▶ -1.459; for BallisticScrollActivity)),
flutter:     ScrollDirection.idle)
flutter: This RenderObject had the following child:
flutter:     text: TextSpan
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Bad state: No element
```

Related to https://github.com/flutter/flutter/issues/47745.

Moving cursor issue persists as well:

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/17024977/82568533-a2a78800-9b87-11ea-8a0b-4189a81e338b.gif)

<details>
 <summary>fluter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.133, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.19.0-2.0.pre.133 at /Users/nevercode/dev/flutter
    • Framework revision e92afc16b6 (16 hours ago), 2020-05-21 05:29:01 +0900
    • Engine revision 2d4e83921d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (6 available)
    • Redmi Note 7              • 6345c469                                 •
      android-arm64  • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554                            •
      android-x86    • Android 10 (API 29) (emulator)
    • Nevercode’s iPhone        • b668e524315069f3db3661ac11ff1f66afafebdb • ios
      • iOS 13.5
    • macOS                     • macOS                                    •
      darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server                • web-server                               •
      web-javascript • Flutter Tools
    • Chrome                    • chrome                                   •
      web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by mohammadamir98** [comment] 2020-05-27 05:09
The same happens when setting the locale to an RTL language( Persian or Arabic). It happens in both English and Persian languages in that case.

**Comment by YusufAbdelaziz** [comment] 2020-06-08 12:07
It does reproduce on Android, check issue #58902

**Comment by VladyslavBondarenko** [comment] 2020-06-08 13:42
@YusufAbdelaziz 
indeed, thank you. Reproduced with dev 1.19.0-4.0.pre on Redmi Note 7 Android 9 (API 28)

**Comment by YusufAbdelaziz** [comment] 2020-06-16 13:24
Setting `maxLines` to null and `minLines` to 1, somehow fixes the issue.
Check [here](https://giphy.com/gifs/XfPxuUkQLv1syfkLqB).

**Comment by iscriptology** [comment] 2020-06-16 14:29
This is a really serious regression. We can’t release our app to users. Any ETA?

**Comment by awnigharbia** [comment] 2020-06-28 23:59
> Setting `maxLines` to null and `minLines` to 1, somehow fixes the issue but I still think it's a bug.
> Check [here](https://giphy.com/gifs/XfPxuUkQLv1syfkLqB).

I have this issue as well. please find a solution for this. this solution works for me (some hacky way).

**Comment by mmd44** [comment] 2020-07-30 09:55
> Setting `maxLines` to null and `minLines` to 1, somehow fixes the issue but I still think it's a bug.
> Check [here](https://giphy.com/gifs/XfPxuUkQLv1syfkLqB).

This does not solve the issue if the localization is set to RTL but the input in a LTR language.

**Comment by Legendree** [comment] 2020-07-30 13:53
Same here, hebrew spaces doesn't delete when use RTL languages (hebrew)

**Comment by Legendree** [comment] 2020-07-30 14:22
set maxLines to 2, minLines to 1 and it will be fixed, yet shoud be fixed. min

**Comment by mmd44** [comment] 2020-08-03 14:03
> set maxLines to 2, minLines to 1 and it will be fixed, yet shoud be fixedw without this hacks.

The thing is that for this temp fix to work you should not/cannot  provide the maxLength textfield param.

**Comment by EngAddow** [comment] 2020-08-05 14:24
any solutions for this problem in stable chanel:

I have these issues + password show/hide and then erase not working!

pls any solution ?

**Comment by EngAddow** [comment] 2020-08-05 14:33
> > Setting `maxLines` to null and `minLines` to 1, somehow fixes the issue but I still think it's a bug.
> > Check [here](https://giphy.com/gifs/XfPxuUkQLv1syfkLqB).
> 
> This does not solve the issue if the localization is set to RTL but the input is in a LTR language.

did u get solution? I have the same problem.

**Comment by areejmayadeh** [comment] 2020-10-08 14:06
Any solution still have this issue

**Comment by Legendree** [comment] 2020-10-08 15:14
> Any solution still have this issue

Yeah, switch to react

**Comment by xJon** [comment] 2020-10-18 23:24
Any idea if this is going to get resolved soon? It makes RTL text input in Flutter impossible.

**Comment by mhbdev** [comment] 2020-10-23 14:44
This should be marked as severe. There are 400+ textfield related issues out there.

**Comment by ahmed-foulad20** [comment] 2020-11-18 16:01
this work with me 
[https://medium.com/@ahmedalyousif/auto-change-ltr-direction-to-rtl-for-any-widget-b2fc229e0a0d](url)
auto direction package
[https://pub.dev/packages/auto_direction](url)

**Comment by xJon** [comment] 2020-11-18 18:05
> this worked with me
> [https://medium.com/@ahmedalyousif/auto-change-ltr-direction-to-rtl-for-any-widget-b2fc229e0a0d](url)
> auto direction package
> [https://pub.dev/packages/auto_direction](url)

This did not solve the problem for me, also sometimes you'd want to have a TextField with LTR alignment that can still accept RTL text properly.

**Comment by ahmed-foulad20** [comment] 2020-11-19 17:00
> > this worked with me
> > [https://medium.com/@ahmedalyousif/auto-change-ltr-direction-to-rtl-for-any-widget-b2fc229e0a0d](url)
> > auto direction package
> > [https://pub.dev/packages/auto_direction](url)
> 
> This did not solve the problem for me, also sometimes you'd want to have a TextField with LTR alignment that can still accept RTL text properly.

if you want to accept LTR in The two cases you can hardcoded 
` AutoDirection(
                    text:"en",
                    child: TextFormField( ),
                  )`

**Comment by xJon** [comment] 2020-11-21 22:35
> > > this worked with me
> > > [https://medium.com/@ahmedalyousif/auto-change-ltr-direction-to-rtl-for-any-widget-b2fc229e0a0d](url)
> > > auto direction package
> > > [https://pub.dev/packages/auto_direction](url)
> > 
> > 
> > This did not solve the problem for me, also sometimes you'd want to have a TextField with LTR alignment that can still accept RTL text properly.
> 
> if you want to accept LTR in The two cases you can hardcoded
> ` AutoDirection( text:"en", child: TextFormField( ), )`

Unfortunately this does not resolve the issue for me.
The only workaround that worked was giving `TextField` this parameter: `maxLines: null`.

**Comment by MeMoSalem** [comment] 2020-12-16 14:57
The reason this happens is because the cursor shifts so when language changes from English to Arabic or any rtl language.
I faced the issue when i changed keyboard to English and the language of the app is Arabic and vice versa so i came up with this solution and it worked

create a variable to hold default textDirection --> var textDirection = TextDirection.rtl;
and pass it to the textDirection property in your textfield.

Then in onChanged method type the following:
onChanged: (val){
        // here this regexp only for English chars so in your case find the suitable regex for the language you want
         RegExp exp = RegExp("[a-zA-Z]");
         // simply checking if the last char is an English char and not space make the textDirection left to right 
         if(exp.hasMatch(val.substring(val.length-1)) && val.substring(val.length-1) != " "){
               setState(() {
                   textDirection = TextDirection.ltr;
                });
         }else if(val.substring(val.length-1) != " " && !exp.hasMatch(val.substring(val.length-1))){
                setState(() {
                   textDirection = TextDirection.rtl;
                 });
         }
// this line is to indicate the change of the last char in the string will print true or false
  print(exp.hasMatch(val.substring(val.length-1)).toString());
             },

**Comment by Pourqavam** [comment] 2021-01-09 14:39
I have the same problem on Windows (desktop) platform.
I tested it on an Android device (API 23) and it looked perfect.
`Flutter 1.26.0-1.0.pre • channel dev •`

**Comment by darshankawar** [comment] 2021-02-03 12:23
@royibernthal 
I tried a code sample using latest stable and master on iOS simulator and was able to delete space characters while typing Hebrew. 


https://user-images.githubusercontent.com/67046386/106746083-086d6e80-6648-11eb-8c67-489799676414.mov


```
body: Center(
            child: TextFormField(
              textAlign: TextAlign.right,
              textDirection: TextDirection.rtl,
              decoration: InputDecoration(
                  hintText: 'Enter here'
              ),
            )
        )
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (11 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 1.26.0-18.0.pre.156, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-18.0.pre.156 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 45508985b1 (9 hours ago), 2021-02-02 22:46:04 -0500
    • Engine revision 2c144c3eeb
    • Dart version 2.12.0 (build 2.12.0-282.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM A260G (mobile)          • 5200763ebcfa861f                     •
      android-arm    • Android 8.1.0 (API 27)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 1 category.


```

</details>

Can you confirm if this is now an expected behavior ?

**Closed** 2021-03-25 00:54 UTC
Labels: a: internationalization, a: text input, f: cupertino, f: material design, found in release: 1.17, found in release: 1.18, found in release: 1.19, framework, has reproducible steps
