### ISSUE TITLE
Photo picker albums list is incomplete

### ISSUE THREAD

**Issue by rohansohonee1** [flutter/flutter#142104] opened 2024-01-24 06:48 UTC
### What package does this bug report belong to?

image_picker

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

No

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
image_picker:
    dependency: "direct main"
    description:
      name: image_picker
      sha256: "7d7f2768df2a8b0a3cefa5ef4f84636121987d403130e70b17ef7e2cf650ba84"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.4"
image_picker_android:
    dependency: transitive
    description:
      name: image_picker_android
      sha256: "1a27bf4cc0330389cebe465bab08fe6dec97e44015b4899637344bb7297759ec"
      url: "https://pub.dev"
    source: hosted
    version: "0.8.9+2"
image_picker_platform_interface:
    dependency: transitive
    description:
      name: image_picker_platform_interface
      sha256: "0e827c156e3a90edd3bbe7f6de048b39247b16e58173b08a835b7eb00aba239e"
      url: "https://pub.dev"
    source: hosted
    version: "2.9.2"    
```

</details>

### Steps to reproduce

1. Open the gallery using the pickImage.
2. Navigate to the Albums section on the photo picker.
3. Here the albums listed are incomplete.

### Expected results

The Photo picker should list all the albums present/available on the user's device.

### Actual results

- The Albums list is incomplete. Only the Camera, Screenshots & Downloads is listed based on the testing.

- Also after disabling the Photo picker using the following:
```
imagePickerImplementation.useAndroidPhotoPicker = false;
```
In the testing a Browse menu button is displayed in the Photo picker. Please clarify about this as it is not mentioned in the docs https://developer.android.com/training/data-storage/shared/photopicker

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'packages:image_picker/image_picker.dart';
import 'package:image_picker_android/image_picker_android.dart';
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  
  final ImagePickerPlatform imagePickerImplementation =
      ImagePickerPlatform.instance;
  // check if platform is Android
  if (imagePickerImplementation is ImagePickerAndroid) {
    // enable photo picker for Android 13
    imagePickerImplementation.useAndroidPhotoPicker = true;
  }
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    super.key,
    required this.title,
  }) : super();

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _openPicker() async {
    final result = await ImagePicker.pickImage(source: ImageSource.gallery);
    print(result);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              'Open picker',
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _openPicker,
        tooltip: 'Open picker',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

Incomplete albums list:
<img src="https://github.com/flutter/flutter/assets/120708465/d15f8880-1847-47ef-80fa-16a196fa317e" width="50%"/>

After setting the `useAndroidPhotoPicker` to false the Browse menu button is enabled:
<img src="https://github.com/flutter/flutter/assets/120708465/5fce0e59-bb50-4405-8131-17961737bd43" width="50%"/>

Tapping on Browse menu button opens the old interface:
<img src="https://github.com/flutter/flutter/assets/120708465/5d5b7f8a-1a4c-4896-b882-d940cd766a3c" width="50%"/>

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.6, on macOS 12.7.2 21G1974 darwin-x64, locale en-US)
    • Flutter version 3.16.6 on channel stable at /Users/appleapple/fvm/versions/3.16.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46787ee49c (2 weeks ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 12.7.2 21G1974 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 121.0.6167.85

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by rohansohonee1** [comment] 2024-01-24 06:49
Also mentioning the following issue https://issuetracker.google.com/issues/264952941

**Comment by huycozy** [comment] 2024-01-24 12:10
> Also mentioning the following issue https://issuetracker.google.com/issues/264952941

Hi @rohansohonee1, I see the response to this at https://issuetracker.google.com/issues/264952941#comment3: this is working as intended. Until the API changes, opening a feature request for this would be more appropriate.

>In the testing a Browse menu button is displayed in the Photo picker. Please clarify about this as it is not mentioned in the docs https://developer.android.com/training/data-storage/shared/photopicker

Please open a separate request for this. Thank you!

Closing the issue.

**Closed by huycozy** 2024-01-24 12:10 UTC
Labels: in triage
