### ISSUE TITLE
detect android sdk via ANDROID_SDK_ROOT in addition to deprecated ANDROID_HOME

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter#18627] opened 2018-06-20 06:24 UTC
As said in android's doc (https://developer.android.com/studio/command-line/variables), `ANDROID_HOME` is deprecated and should migrate to `ANDROID_SDK_ROOT`.

**Comment by zoechi** [comment] 2019-02-13 11:15
Duplicate of #15273

**Closed by zoechi** 2019-02-13 11:15 UTC
Labels: tool, ▣ platform-android

**Comment by zoechi** [comment] 2019-02-13 11:19
Duplicate of #15144
