### ISSUE TITLE
[in-app-purchase] [iOS] ask permision

### ISSUE THREAD

**Issue by ceokin** [flutter/flutter#68626] opened 2020-10-20 16:25 UTC
Hi, I am trying to implement in app purchases just for iOS.

In the process of buying a consumable product, a pop up is shown asking for parent permission. When I press on the ask button, it does nothing.

I do not know how to avoid this popup.

Any idea?

![WhatsApp Image 2020-10-20 at 17 07 51](https://user-images.githubusercontent.com/9987374/96615408-85771100-1301-11eb-9ca5-7321aaec9927.jpeg)

**Comment by darshankawar** [comment] 2020-10-21 08:10
@ceokin 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue. Also provide the iOS version and device you are using which shows the dialog. Are you getting this dialog for specific product or for all ?
Can you try to run the official plugin [example](https://pub.dev/packages/in_app_purchase/example) and see if you get dialog there too ?

**Comment by ceokin** [comment] 2020-10-21 15:35
Someone gave me the solution in a different post. 

He said: 

I think the error about paternal permission is related to the sandbox option in purchase param, this option doesn't set the sandbox environment, instead, it enables the parent permission sandbox testing, try to set it to false!

I tried it and the parent permission does not appear anymore.

**Comment by darshankawar** [comment] 2020-10-22 05:24
@ceokin Glad to know your issue is resolved.
I am going ahead and closing this as resolved.
Thanks.

**Closed by darshankawar** 2020-10-22 05:24 UTC
Labels: in triage

**Comment by alexlovar** [comment] 2020-10-26 01:05
@ceokin will be useful if you explain where you set the flag simulatesAskToBuyInSandbox to false, where do you find this key?
could you please explain more about this?

thanks

**Comment by ceokin** [comment] 2020-10-26 09:03
Hi @alexlovar 

when you buy a product you need to send purchaseParam. Here you can include an attribute called sandboxTesting. See below an example:

     PurchaseParam purchaseParam = PurchaseParam(
                        sandboxTesting: false,
                          productDetails: productDetails);

sanboxTesting should set if you are in a sandbox environment, but it does not. If it is true, the parent permission will show, if you set it false or not include it, parent permission no longer be shown

**Comment by alexlovar** [comment] 2020-10-26 17:11
@ceokin  thank you, i found the key:
change sandboxTesting: true, to false
https://github.com/flutter/plugins/blob/d82940f02fc306707cce66e4e7111c0bc6ca6fc6/packages/in_app_purchase/example/lib/main.dart#L256

**Comment by sanekyy** [comment] 2020-11-12 18:45
same issue

**Comment by naththeprince** [comment] 2020-12-03 17:50
We are noticing the same issue, for now we were changing sandboxTesting: true, to false as said by @alexlovar and @ceokin

**Comment by junaidlodhi22** [comment] 2020-12-14 13:21
the message of ask permission gets removed. Getting a message that you are successfully subscribed.
But on iOS, the below **_purchased_** code is still not running
and can not see the app in the subscriptions of App Store like I can see subscription in android testing?

```
 purchaseUpdates.listen((purchases) async {
      for (PurchaseDetails purchase in purchases) {
        if (purchase.status == PurchaseStatus.error) {
          print(purchase.error.code);
          in_app_purchase.completePurchase(purchase);
        } else if (purchase.status == PurchaseStatus.purchased) {
          await reUse.add_purchase_details_to_user_account(
            user_id,
            purchase.purchaseID,
            purchase.transactionDate,
          );
          in_app_purchase.completePurchase(purchase);
        } else {
          reUse.show_toast("payment problem else");
        }
      }
    });
``` 
how can I save the transaction id if the purchase code is not running?

**Comment by jbryanh** [comment] 2021-03-23 21:52
This would not be expected behavior. I think it's a bug.

**Comment by somavoyager** [comment] 2021-05-04 17:49
Why is this issue closed? I am experiencing the same issue.

**Comment by MichaelM97** [comment] 2021-05-09 21:29
It looks like this is expected behaviour, see the documentation 

```dart
/// @deprecated Use [simulatesAskToBuyInSandbox] instead.
///
/// Only available on iOS, set it to `true` to produce an "ask to buy" flow for this payment in the sandbox.
///
/// See also [SKPaymentWrapper.simulatesAskToBuyInSandbox].
@deprecated
final bool sandboxTesting;
```

So yes, setting `sandboxTesting` to `false` will prevent the "Ask To Buy"/"Ask Permission" prompt from showing.
