### ISSUE TITLE
Flutter console keep showing previous logs and prints

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#48959] opened 2020-01-16 12:33 UTC
After upgrade to Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 and everytime try to run my app I get previous log in console. Yesterday I work on my project and put some print function to see what is the data that I am getting. Than I comment the print line. Today I open my project and try to run and I am keep getting yesterday logos and prints that install the app to my emulator.

Any idea how to stop this?

After the line (Running Gradle task 'assembleDebug'...) shows my yesterday logs and print and than on the bottom shows building and installing.

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
I/flutter ( 6222): upgrader.ITunesResults.version: RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter ( 6222): upgrader.ITunesResults.trackViewUrl: RangeError (index): Invalid value: Valid value range is empty: 0
....
....
....
....
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk..

```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CY)
    • Flutter version 1.12.13+hotfix.5 at /Users/niyazitoros/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by jonahwilliams** [comment] 2020-01-16 13:28
Duplicate of https://github.com/flutter/flutter/issues/47329

**Closed by jonahwilliams** 2020-01-16 13:28 UTC
