### ISSUE TITLE
SSL Memory leaks

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#94808] opened 2021-12-07 16:20 UTC
Hi @dnfield :
We meet a similar issue like https://github.com/flutter/flutter/issues/20409.
**Stack is :**
OPENSSL_memdup (in Flutter) (mem.c:365)
CRYPTO_BUFFER_new (in Flutter) (pool.c:101)
bssl::ssl_parse_cert_chain(unsigned char*, std::__1::unique_ptr<stack_st_CRYPTO_BUFFER, bssl::internal::Deleter<stack_st_CRYPTO_BUFFER> >*, std::__1::unique_ptr<evp_pkey_st, bssl::internal::Deleter<evp_pkey_st> >*, unsigned char*, cbs_st*, crypto_buffer_pool_st*) (in Flutter) (ssl_cert.cc:396)
bssl::ssl_client_handshake(bssl::SSL_HANDSHAKE*) (in Flutter) (handshake_client.cc:1769)
bssl::ssl_run_handshake(bssl::SSL_HANDSHAKE*, bool*) (in Flutter) (handshake.cc:694)
SSL_do_handshake (in Flutter) (ssl_lib.cc:889)
dart::bin::SSLFilter::Handshake(long long) (in Flutter) (secure_socket_filter.cc:592)
dart::bin::Builtin_SecureSocket_Handshake(_Dart_NativeArguments*) (in Flutter) (secure_socket_filter.cc:152)
dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) (in Flutter) (native_entry.cc:217)

![企业微信截图_a6d311ce-7a58-41e1-ad3d-de361ac6463f](https://user-images.githubusercontent.com/6874049/145066029-2043c922-5a2e-4ba1-98e5-b9a1e86a67ac.png)

**flutter version:2.2.0**

Is this problem fixed in latest version? How to avoid this problem in this version.
Wish your reply . 
thanks!

**Comment by dnfield** [comment] 2021-12-07 18:46
Can you share a simple reproduction of this?

**Comment by cj3479** [comment] 2021-12-08 03:06
> Can you share a simple reproduction of this?

The entrance of our App is native, and Flutter is a functional entrance. 
When I enter flutter and then exit flutter, it reappears

**Comment by dnfield** [comment] 2021-12-08 03:08
Yes, but we need a sample flutter application that reproduces this.

**Comment by cj3479** [comment] 2021-12-08 11:41
https://github.com/zjrwdl/flutterDemoNews


![image](https://user-images.githubusercontent.com/9412601/145202596-2dc297d6-cd5d-45d1-8122-a073e5aad075.png)

**Comment by cj3479** [comment] 2021-12-08 11:55
> https://github.com/zjrwdl/flutterDemoNews
> 
> ![image](https://user-images.githubusercontent.com/9412601/145202596-2dc297d6-cd5d-45d1-8122-a073e5aad075.png)

https://user-images.githubusercontent.com/9412601/145204394-59f5805c-7a33-424d-94fe-f7bab1c704c2.mp4

**Comment by cj3479** [comment] 2021-12-08 11:58
> Yes, but we need a sample flutter application that reproduces this.

Flutter 2.2.0 
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

this is demo app 
https://github.com/zjrwdl/flutterDemoNews


![145202596-2dc297d6-cd5d-45d1-8122-a073e5aad075](https://user-images.githubusercontent.com/9412601/145204712-a9c314e6-532b-4352-a152-91092d62f7be.png)



https://user-images.githubusercontent.com/9412601/145204747-f1b3c511-f724-4626-b3f0-734e06bb70d0.mp4

**Comment by dnfield** [comment] 2021-12-08 17:33
I think this is still a duplicate of https://github.com/dart-lang/sdk/issues/36935. It seems like whatever your larger app is doing to leave Flutter and come back makes the leak worse though. I'm going to close this as a dupe up there - this is a Dart bug unfortunately.

**Closed by dnfield** 2021-12-08 17:33 UTC
Labels: waiting for customer response, engine, dependency: dart, perf: memory, P4
