### ISSUE TITLE
Add Proguard annotations to Flutter

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#33603] opened 2019-05-30 17:59 UTC
Mirror issue for https://b.corp.google.com/issues/113252715, belonging to customer dream, but is connected to add-to-app, too. As noted from the original issue:

If an app embedding Flutter is proguarded, class and method names are mangled, so JNI code cannot access them by their normal names. FlutterMain and other classes accessed by JNI should be annotated so that default Proguard config keeps them or a Proguard configuration fragment should be provided.

Dream-specific discussion should occur on the linked bug, but work pertaining to add-to-app and the general community can occur here.

**Comment by jmagman** [comment] 2020-02-05 01:37
Duplicate of https://github.com/flutter/flutter/issues/21130.

**Closed by jmagman** 2020-02-05 01:37 UTC
Labels: a: existing-apps, customer: dream (g3), tool, ▣ platform-android
