### ISSUE TITLE
Flutter application crashes after start (Android API 23)

### ISSUE THREAD

**Issue by maxnemoy** [flutter/flutter#28412] opened 2019-02-24 05:51 UTC
If I use master branch >= **v1.2.2-pre.54**
The application crashes.
This is **only** for the samsung SM-G532F device.
```
MediaTek MT6737T
Mali-t720
Android 6.0.1 API 23
```
Other devices and emulators work correctly.

On the problem device, I cleared the cache, then made a factory reset.
but the behavior remains the same.
when changing branches to stable, no problem.

flutter doctor -v
```
[√] Flutter (Channel master, v1.2.3-pre.27, on Microsoft Windows [Version 10.0.17763.253], locale ru-RU)
    • Flutter version 1.2.3-pre.27 at C:\flutter
    • Framework revision db0c655110 (4 hours ago), 2019-02-23 20:59:28 -0500
    • Engine revision b1779e7d95
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\maxnemoy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2
    • Flutter plugin version 33.2.2
    • Dart plugin version 183.5901

[√] Connected device (1 available)
    • SM G532F • 42006871065015d9 • android-arm • Android 6.0.1 (API 23)

• No issues found!
```

[flutter run -v](https://gist.github.com/maxnemoy/c21a4fb3e0fa53d024d43da84298da70)

how can i fix this?

UPD - Default project also crashes
UPD 2 - The problem is not in my device. Application **crash on devices and emulators API 23** (Android 6.x.x)

I am sorry for my bad english

**Comment by windrunner414** [comment] 2019-02-24 09:29
also crash on android 5.x

**Comment by Azazel** [comment] 2019-02-24 10:36
This is exception which I'm getting in LogCat for my API 21 device:
```
java.lang.NoSuchMethodError: No virtual method getLocales()Landroid/os/LocaleList; in class Landroid/content/res/Configuration; or its super classes (declaration of 'android.content.res.Configuration' appears in /system/framework/framework.jar)
        at io.flutter.view.FlutterView.sendLocalesToDart(FlutterView.java:323)
        at io.flutter.view.FlutterView.<init>(FlutterView.java:187)
        at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:161)
        at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:89)
        at au.com.azazelkon.dilutioncalculator.MainActivity.onCreate(MainActivity.kt:10)
        at android.app.Activity.performCreate(Activity.java:6288)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2642)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2754)
        at android.app.ActivityThread.access$900(ActivityThread.java:177)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5938)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by Azazel** [comment] 2019-02-24 11:04
Looks like this commit 2f4a38dbd33061e950cf83ddc31785803d58c126 for flutter/engine broke locales logic.
If you go to this diff `@@ -311,39 +319,21 @@ private void sendUserPlatformSettingsToDart()` you will find that before there was SDK version check and reflection, while now it simply tries to call `config.getLocales()` which was added in API 24. So earlier versions crash.

**Comment by pjcau** [comment] 2019-02-24 12:56
I verify this issue, crash on sdk 21, 22, 23. It's running from 24 to 28.

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.2.3-pre.29, on Mac OS X 10.14.3 18D109, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by miDeb** [comment] 2019-02-24 18:12
Introduced in https://github.com/flutter/engine/pull/7892

**Comment by jonahwilliams** [comment] 2019-02-24 20:45
duplicate of https://github.com/flutter/flutter/issues/28321

**Closed by jonahwilliams** 2019-02-24 20:45 UTC

**Comment by harshshredding** [comment] 2019-09-29 17:57
The reason it was crashing me was because of a third-party library on startup. *To check which library is causing the crash*, look at the logs using Logcat by going to `View > Tool Windows > Logcat` on Android Studio. Then, restart the app and inspect the output of Logcat on startup. For me, it was Firebase Auth library which was causing the crash. I just updated that library to love my problem. I hope this helps someone. If not, "Stay calm, and keep reading, you will find it eventually
:) ".
