### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by LipuBeingeniere** [flutter/flutter#160585] opened 2024-12-19 09:57 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008130-000A48E60A88001C --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:236:36)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:189:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:452:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:614:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-arm64, locale zh-Hans-FR)
    • Flutter version 3.27.1 on channel stable at /Users/lipu/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (3 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/lipu/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Users/lipu/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Users/lipu/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] Connected device (5 available)
    • V2206 (mobile)                  • 10AC8K0X89000JL           • android-arm64  • Android 14 (API 34)
    • Lipu 的 iPhone (mobile)          • 00008130-000A48E60A88001C • ios            • iOS 18.2 22C152
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.2 24C101 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.2 24C101 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.205

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.10.84+95
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 62bd79521d8d007524e351747471ba66696fc2d4
### Plugins
audioplayers-6.1.0
audioplayers_android-5.0.0
audioplayers_darwin-6.0.0
audioplayers_linux-4.0.0
audioplayers_web-5.0.1
audioplayers_windows-4.0.0
device_info_plus-11.2.0
file_picker-8.1.6
file_selector_linux-0.9.3+2
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
firebase_analytics-11.3.6
firebase_analytics_web-0.5.10+5
firebase_core-3.8.1
firebase_core_web-2.18.2
firebase_crashlytics-4.2.0
firebase_messaging-15.1.6
firebase_messaging_web-3.9.5
firebase_performance-0.10.0+11
firebase_performance_web-0.1.7+5
flutter_datawedge-3.0.0
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_local_notifications-18.0.1
flutter_local_notifications_linux-5.0.0
flutter_native_splash-2.4.3
flutter_plugin_android_lifecycle-2.0.23
google_mlkit_commons-0.9.0
google_mlkit_text_recognition-0.14.0
image_cropper-8.1.0
image_cropper_for_web-6.0.2
image_picker-1.1.2
image_picker_android-0.8.12+18
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
mobile_scanner-6.0.2
open_file-3.5.10
open_file_android-1.0.6
open_file_ios-1.0.3
open_file_linux-0.0.5
open_file_mac-1.0.3
open_file_web-0.0.4
open_file_windows-0.0.3
package_info_plus-8.1.2
path_provider-2.1.5
path_provider_android-2.2.15
path_provider_foundation-2.4.1
path_provider_linux-2.2.1
path_provider_windows-2.3.0
pointer_interceptor-0.10.1+2
pointer_interceptor_ios-0.10.1
pointer_interceptor_web-0.10.2+1
shared_preferences-2.3.3
shared_preferences_android-2.4.0
shared_preferences_foundation-2.5.4
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
speech_to_text-7.0.0
sqflite-2.4.1
sqflite_android-2.4.0
sqflite_darwin-2.4.1
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.2
url_launcher_linux-3.2.1
url_launcher_macos-3.2.2
url_launcher_web-2.3.3
url_launcher_windows-3.1.3
vibration-2.0.1
webview_flutter-4.10.0
webview_flutter_android-4.2.0
webview_flutter_wkwebview-3.16.3

**Comment by danagbemava-nc** [comment] 2024-12-19 10:11
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-12-19 10:11 UTC
Labels: in triage
