### ISSUE TITLE
I am getting this error while runnibg my first app

### ISSUE THREAD

**Issue by skollToWeird** [flutter/flutter#48675] opened 2020-01-12 12:59 UTC
What went wrong:
```bash
Could not resolve all files for configuration ':app:debugCompileClasspath'.
Could not resolve io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
  Required by:
      project :app
Could not resolve io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
Could not get resource 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
Could not GET 'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom'.
            Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 31s
Gradle task assembleDebug failed with exit code 1
```

Flutter doctor -v response : 
```console
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at C:\Program Files\flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\MAD\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\MAD\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • SM G935F • ce0716073bace21503 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.
exit code 0

```

**Comment by jonahwilliams** [comment] 2020-01-12 23:54
The error you've posted is a network error. Are you able to reach `http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.pom` in a web browser or from the command line?

**Comment by skollToWeird** [comment] 2020-01-13 07:48
in a web browser, yes
Also now i am using my office wifi, can that be a problem?

**Comment by skollToWeird** [comment] 2020-01-13 08:06
yes it did ran now, can you tell me why it does not work on my home network, i have no proxy or firewall issue,

**Comment by iapicca** [comment] 2020-01-13 08:29
possible duplicate of https://github.com/flutter/flutter/issues/41553

**Comment by jonahwilliams** [comment] 2020-01-13 15:20
> yes it did ran now, can you tell me why it does not work on my home network, i have no proxy or firewall issue

I can't really remotely debug a network issue. Since there isn't anything actionable here I'm closing the issue

**Closed by jonahwilliams** 2020-01-13 15:20 UTC
Labels: tool, ▣ platform-android
