### ISSUE TITLE
Could not find compiler set in environment variable CXX:                                                                                          clang++.     

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#61418] opened 2020-07-14 05:37 UTC
```
❯ echo $CXX                      
/usr/bin/clang++-6.0

/media/ on  master ● ●
❯ flutter run -d linux           
Launching lib/main.dart on Linux in debug mode...
CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.17/Modules/CMakeDetermineCXXCompiler.cmake:48 (message):
  Could not find compiler set in environment variable CXX:              
                                                                        
  clang++.                                                              
                                                                        
Call Stack (most recent call first):                                    
  CMakeLists.txt:2 (project)                                            
                                                                        
                                                                        
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage           
Building Linux application...   
```

I have clang++ install, how to use it?

I tried export CMAKE_CXX_COMPILER and CXX all not work

**Comment by TahaTesser** [comment] 2020-07-14 12:11
Hi @jinfagang 
Can you please provide your `flutter doctor -v` your `flutter run --verbose -d <linux device>` and a complete reproducible minimal code sample
Thank you

**Comment by jinfagang** [comment] 2020-07-15 03:58
@TahaTesser For sure:

```
❯ flutter doctor -v      
Downloading android-arm-profile/linux-x64 tools...                  5.2s
Downloading android-arm-release/linux-x64 tools...                  5.8s
Downloading android-arm64-profile/linux-x64 tools...               13.7s
Downloading android-arm64-release/linux-x64 tools...               10.3s
Downloading android-x64-profile/linux-x64 tools...                  9.6s
Downloading android-x64-release/linux-x64 tools...                 10.0s
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Linux, locale en_HK.UTF-8)
    • Flutter version 1.20.0-7.1.pre at /home/fagangjin/development/flutter
    • Framework revision 7736f3bc90 (4 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    • cmake version 3.17.1
    • ninja version 1.9.0.git.kitware.dyndep-1.jobserver-1
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.47.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 3 categories.

```

main outputs:

```
[   +3 ms] Launching lib/main.dart on Linux in debug mode...
[   +3 ms] /dart-sdk/bin/dart --disable-dart-dev /rtifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
che/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
/tmp/flutter_tools.JICZDK/flutter_tool.QFZRFT/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/cache.dill.track.dill
[  +14 ms] Building Linux application...
[  +11 ms] <- compile package:flutter_app/main.dart
[   +1 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /oduct/linux
[ +272 ms] CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.17/Modules/CMakeDetermineCXXCompiler.cmake:48 (message):
[   +1 ms]   Could not find compiler set in environment variable CXX:
[        ]   clang++.
[        ] Call Stack (most recent call first):
[        ]   CMakeLists.txt:2 (project)
[        ] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
[        ] -- Configuring incomplete, errors occurred!
[        ] See also "/media/xx/sams/build/linux/debug/CMakeFiles/CMakeOutput.log".
[  +11 ms] Building Linux application... (completed in 0.3s)
[+7872 ms] Exception: Unable to generate build files
[   +1 ms] "flutter run" took 8,572ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:591:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:860:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +253 ms] ensureAnalyticsSent: 252ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +20 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1


```

**Comment by TahaTesser** [comment] 2020-07-15 08:17
Hi @jinfagang 
Looks like you've incomplete linux setup 
```
 ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/`
```

Did you execute `sudo apt install clang`? also your says `/usr/bin/clang++-6.0`, maybe you need update to latest version 10.0.0

Please check my doctor -v 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-7.1.pre at /home/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (4 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    •
      Android 10 (API 29) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      •
      Linux
    • Web Server (web)                   • web-server    • web-javascript •
      Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript •
      Google Chrome 84.0.4147.89

• No issues found!

```

</details> 

Thank you

**Comment by jinfagang** [comment] 2020-07-15 08:52
@TahaTesser You simply saved my life ! It now runs!

However, may I ask is there sqflite plugin support for it?

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method openDatabase on channel com.tekartik.sqflite)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>                                               

```

I also notice that another project go-flutter-desktop can work well with all my dependencies in my app

**Comment by TahaTesser** [comment] 2020-07-15 12:43
Hi @jinfagang 
Glad you resolved `linux` issue 

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/tekartik/sqflite/issues).

Closing as `linux` issue issue is resolved
Thank you

**Closed by TahaTesser** 2020-07-15 12:43 UTC
Labels: in triage

**Comment by stuartmorgan** [comment] 2020-07-15 16:27
> I also notice that another project go-flutter-desktop can work well with all my dependencies in my app

That project has a completely separate, unrelated plugin ecosystem.
