### ISSUE TITLE
Drawers are not working on 3.1.0-0.0.pre.1560 master on web

### ISSUE THREAD

**Issue by stevendz** [flutter/flutter#107290] opened 2022-07-08 10:30 UTC
### Edit:
It seems that this is not a bug but it was changed intentionally. That the drawers were working on desktop was the bug :/
So eventually it would be possible to allow drawers again on desktop and make them toggle-able or something?

https://github.com/flutter/flutter/pull/100476

~~`drawer` and `enddrawer` are not working on web.~~

## Steps to Reproduce

1. Add `drawer` or `enddrawer` to Scaffold
2. Drag from left/right to the mid of the app

**Expected results:** Drawer opens

**Actual results:** Nothing happens

``` dart
Widget build(BuildContext context) {
    return Scaffold(
      endDrawer: Container(
        width: 200,
        color: Colors.red,
      ),
      body: SizedBox(),
    );
  }
```

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1560, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
• No issues found!

**Comment by exaby73** [comment] 2022-07-08 12:55
Hello @stevendz. Can you link the discussion which states this intentional change?

**Comment by karokojnr** [comment] 2022-07-08 13:52
Hi @stevendz 
Your `Container(...)` widget needs to be a child under a `Drawer()`:

`Drawer(
    child: Container(
        width: 200,
        color: Colors.red,
    ),
);`

**Comment by stevendz** [comment] 2022-07-11 12:16
The PR where this was 'fixed' https://github.com/flutter/flutter/pull/100476

**Comment by exaby73** [comment] 2022-07-12 09:51
cc: @TahaTesser for more information on this issue

**Comment by TahaTesser** [comment] 2022-07-12 12:00
@stevendz 
Please refer to the discussion in this [issue](https://github.com/flutter/flutter/issues/105835)
Closing as duplicate of https://github.com/flutter/flutter/issues/105835

**Closed by TahaTesser** 2022-07-12 12:00 UTC
Labels: in triage
