### ISSUE TITLE
Exception: The getter 'height' was called on null. - when running --release on a Pixel

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6847] opened 2016-11-14 21:12 UTC
Ran `flutter run --release` onto a Pixel, from the "starter app". Exception from the console:

```
~/tmp/testflutter2 $ flutter run --release
Building APK in release mode (android-arm-release)...      
Warning! Signing the APK using the debug keystore.
You will need a real keystore to distribute your application.
Installing build/app.apk...                         3523ms
Running lib/main.dart on Pixel...

To repeat this help message, press "h" or F1. To quit, press "q", F10, or Ctrl-C.
I/flutter ( 8521): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 8521): The following ArgumentError was thrown during performLayout():
I/flutter ( 8521): Invalid argument(s): 0.0
I/flutter ( 8521): 
I/flutter ( 8521): When the exception was thrown, this was the stack:
I/flutter ( 8521): #0      _Double.clamp (dart:core-patch/double.dart)
I/flutter ( 8521): #1      TextPainter.layout (package:flutter/src/painting/text_painter.dart)
I/flutter ( 8521): #2      RenderParagraph.performLayout (package:flutter/src/rendering/paragraph.dart)
I/flutter ( 8521): #3      RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #4      _ToolbarLayout.performLayout (package:flutter/src/material/app_bar.dart)
I/flutter ( 8521): #5      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart)
I/flutter ( 8521): #6      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart)
I/flutter ( 8521): #7      RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #8      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart)
I/flutter ( 8521): #9      RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #10     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #11     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #12     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart)
I/flutter ( 8521): #13     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #14     RenderConstrainedOverflowBox.performLayout (package:flutter/src/rendering/shifted_box.dart)
I/flutter ( 8521): #15     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #16     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #17     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #18     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart)
I/flutter ( 8521): #19     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #20     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #21     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #22     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #23     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #24     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #25     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #26     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart)
I/flutter ( 8521): #27     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #28     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #29     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #30     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart)
I/flutter ( 8521): #31     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart)
I/flutter ( 8521): #32     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart)
I/flutter ( 8521): #33     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #34     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #35     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #36     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #37     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #38     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #39     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #40     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #41     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #42     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #43     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #44     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #45     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #46     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #47     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #48     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #49     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #50     RenderStack.performLayout (package:flutter/src/rendering/stack.dart)
I/flutter ( 8521): #51     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #52     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #53     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #54     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #55     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #56     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #57     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #58     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart)
I/flutter ( 8521): #59     RenderObject.layout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #60     RenderView.performLayout (package:flutter/src/rendering/view.dart)
I/flutter ( 8521): #61     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #62     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart)
I/flutter ( 8521): #63     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart)
I/flutter ( 8521): #64     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart)
I/flutter ( 8521): #65     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart)
I/flutter ( 8521): #66     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart)
I/flutter ( 8521): #67     main (file:///Users/sethladd/tmp/testflutter2/lib/main.dart)
I/flutter ( 8521): #68     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart)
I/flutter ( 8521): #69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart)
I/flutter ( 8521): 
I/flutter ( 8521): The following RenderObject was being processed when the exception was fired:
I/flutter ( 8521):   RenderParagraph relayoutBoundary=up1 NEEDS-LAYOUT
I/flutter ( 8521): This RenderObject has no descendants.
I/flutter ( 8521): 
I/flutter ( 8521): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8521): Another exception was thrown: NoSuchMethodError: The getter 'height' was called on null.
```

Version:

```
~/tmp/testflutter2 $ flutter --version
Flutter • channel master • git@github.com:flutter/flutter.git
Framework • revision 34e466f1fd (2 hours ago) • 2016-11-14 14:21:30
Engine • revision 84a060820a
Tools • Dart 1.21.0-dev.3.0
```

**Comment by sethladd** [comment] 2016-11-14 21:13
cc @Hixie this might be a known issue?

**Comment by Hixie** [comment] 2016-11-14 21:26
Dupe of https://github.com/flutter/flutter/issues/5259 and https://github.com/flutter/flutter/issues/6537

**Closed by Hixie** 2016-11-14 21:26 UTC
Labels: affects: framework, ⚠ bug
