### ISSUE TITLE
Camera, initialize() failing with error Access denied finding property "persist.vendor.camera.privapp.list"

### ISSUE THREAD

**Issue by ajesh-pb-ai** [flutter/flutter#83980] opened 2021-06-04 08:20 UTC
```
List<CameraDescription> cameras = await availableCameras();
CameraController _controller =
        CameraController(
          cameras.first,
          ResolutionPreset.medium,
          imageFormatGroup: ImageFormatGroup.jpeg);
_controller.initialize();
```

is failing with below error.
**Devide** OnePlus 6
**Camera Package Version** camera 0.8.1+2

```console
> I/CameraManagerGlobal(29123): Connecting to camera service
> W/CameraManagerGlobal(29123): [soar.cts] ignore the status update of camera: 2
> W/CameraManagerGlobal(29123): [soar.cts] ignore the status update of camera: 3
> D/DecorView(29123): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@5589bb6[MainActivity]
> I/Camera  (29123): [FPS Range Available] is:[15, 15]
> I/Camera  (29123): [FPS Range Available] is:[7, 30]
> I/Camera  (29123): [FPS Range Available] is:[30, 30]
> I/Camera  (29123): [FPS Range] is:[7, 30]
> E/SensorManager(29123): registerListenerImpl sensorName:BMI160_ACCELEROMETER Accelerometer Non-wakeup,isWakeUpSensor:false,callingApp: com.sahi.candidatemobile,callingPid:29123,callingUid:10644
> W/Camera  (29123): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
> E/libc    (29123): Access denied finding property "persist.vendor.camera.privapp.list"
> W/candidatemobile(29123): type=1400 audit(0.0:33232): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=16652 scontext=u:r:untrusted_app:s0:c132,c258,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
> W/Gralloc3(29123): allocator 3.x is not supported
```

`flutter  doctor -v`

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.0.4 at /home/purpleboat13/installed/flutter
    • Framework revision b1395592de (9 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/purpleboat13/Android/Sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /home/purpleboat13/Android/Sdk
    • Java binary at: /home/purpleboat13/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/purpleboat13/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • ONEPLUS A6000 (mobile) • eea0f17c • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-06-04 12:55
Hi @ajesh-pb-ai 
I can't reproduce the issue on Oneplus 8 using official with latest `camera`

I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/46952
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-06-04 12:55 UTC
Labels: in triage
