### ISSUE TITLE
Failed assertion: line 3705 pos 12: 'element._lifecycleState == _ElementLifecycle.inactive': is not true.

### ISSUE THREAD

**Issue by TaiTair** [flutter/flutter#85058] opened 2021-06-22 18:50 UTC
## Steps to Reproduce

I have managed to narrow down the problem to my recursive widgets. Please take a look at the recursiveCategory class and the way it gets used in the navDawer.

If I remove the changeNotifier from the recursiveCategory class then the problem seems to go away.

Create flutter demo app.
Replace everything in main.dart with the code below:

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'dart:convert';
import 'dart:math' as math;

GlobalKey<viewState> viewKey = new GlobalKey<viewState>();
view dataView = new view(key: viewKey);
String data = "[{\"id\":\"1\",\"name\":\"test1\",\"subCategories\":[{\"id\":\"1A\",\"name\":\"test1-A\",\"subCategories\":null}]},{\"id\":\"2\",\"name\":\"test2\",\"subCategories\":[{\"id\":\"2A\",\"name\":\"test2-A\", \"subCategories\":null}]}]";
final idHandler = new IdHandler();

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  navDrawer _navDrawer = new navDrawer();


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          automaticallyImplyLeading: false,
          toolbarHeight: 100.0,
          flexibleSpace: Container(
              decoration: BoxDecoration(
                  gradient: LinearGradient(
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                      colors: <Color>[
                        Colors.grey,
                        Colors.red
                      ])
              )
          ),
          title:
          Container(
              alignment: Alignment.centerLeft,
              padding: EdgeInsets.all(0.0),
              child:
              Column(
                  children:[
                    Container(
                        padding: EdgeInsets.fromLTRB(0.0, 10.0, 0.0, 0.0),
                        child:
                        Row(
                            children: [
                              Builder(
                                  builder: (context) => IconButton(
                                    icon: Icon(Icons.menu_rounded),
                                    onPressed: () => Scaffold.of(context).openDrawer(),
                                  )
                              ),
                            ]
                        )
                    ),
                  ]
              )
          )
      ),
      drawer: _navDrawer,
      body: Center(
          child: dataView
        // Container(),
      ),
    );
  }
}

class navDrawer extends StatefulWidget {
  List _categories;
  var _categoryList;

  String indentCategory(String input, int amount){
    String output='';
    for(var i=0; i<amount; i++){
      output += '    ';
    }
    output+=input;
    return output;
  }

  void setCategories(){
    _categories = json.decode(data);
    int catCount = _categories.length;
    _categoryList = new ListView.builder(
      //shrinkWrap: true,
      physics: ClampingScrollPhysics(),
      padding:EdgeInsets.all(0.0),
      itemCount: catCount,
      itemBuilder: (BuildContext context, int index) => buildCategories(context, index),
    );
  }

  Widget buildCategories(BuildContext context, int index){
    recursiveCategory cat = new recursiveCategory(_categories[index]['id'], indentCategory(_categories[index]['name'], 2));
    if(_categories[index]['subCategories']!=null){
      cat.addAllSubCategories(buildSubCategories(_categories[index], 3));
      return cat;
    } else {
      return cat;
    }
  }

  List<recursiveCategory> buildSubCategories(var parent, int depth){
    List<recursiveCategory> subCats = [];
    List subCategoryList = parent['subCategories'];
    int subCategoryCount = subCategoryList.length;
    for(var i=0; i<subCategoryCount; i++){
      recursiveCategory subCat = new recursiveCategory(parent['subCategories'][i]['id'], indentCategory(parent['subCategories'][i]['name'], depth));
      if(parent['subCategories'][i]['subCategories']!=null){
        subCat.addAllSubCategories(buildSubCategories(parent['subCategories'][i], depth+1));
      }
      subCats.add(subCat);
    }
    return subCats;
  }

  @override
  _navDrawerState createState() => _navDrawerState();
}
// ignore: camel_case_types
class _navDrawerState extends State<navDrawer>{

  @override
  void initState(){
    super.initState();
    widget.setCategories();
  }

  @override
  Widget build(BuildContext Context){
    return Container(
        width: MediaQuery.of(context).size.width*0.76,
        child:
        Drawer(
            child:
            Container(
                padding:EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0),
                child:
                Column(
                    children:[
                      Container(
                          height:MediaQuery.of(context).size.height*0.15,
                          width:double.infinity,
                          child:
                          DrawerHeader(
                              child: Text('Menu'),
                              decoration: BoxDecoration(
                                  gradient: LinearGradient(
                                      begin: Alignment.topLeft,
                                      end: Alignment.bottomRight,
                                      colors: <Color>[
                                        Colors.grey,
                                        Colors.red
                                      ])
                              )
                          ),
                          margin:EdgeInsets.all(0.0),
                          padding:EdgeInsets.all(0.0)
                      ),
                      Expanded(
                        child:
                        ListView(
                            padding:EdgeInsets.zero,
                            children: <Widget>[
                              MediaQuery.removePadding(
                                  removeTop:true,
                                  context: context,
                                  child:
                                  SizedBox(
                                    height:MediaQuery.of(context).size.height*0.5,
                                    child: widget._categoryList,

                                  )
                              )
                            ]
                        ),
                      )
                    ]
                )
            )
        )
    );
  }
}

class recursiveCategory extends StatefulWidget{
  String _id = '';
  String _name = '';
  List<recursiveCategory> _subCategories = [];

  recursiveCategory(String id, String name){
    _id = id;
    _name = name;
  }

  void addAllSubCategories(List<recursiveCategory> subCats){
    _subCategories.addAll(subCats);
  }

  void addSubCategory(recursiveCategory cat){
    _subCategories.add(cat);
  }

  @override
  _recursiveCategoryState createState() => _recursiveCategoryState();

}
// ignore: camel_case_types
class _recursiveCategoryState extends State<recursiveCategory> with ChangeNotifier{
  @override
  Widget build(BuildContext context) {
    if(widget._subCategories.isNotEmpty){
      if(idHandler.isIdOpen(widget._id)){
        return Column(
          //mainAxisSize: MainAxisSize.max,
            children: [
              Container(
                  height: MediaQuery.of(context).size.height*0.035,
                  child:
                  Align(
                    alignment: Alignment.centerLeft,
                    child:
                    Wrap(
                        children: [
                          InkWell(
                              child: Row(
                                  children: [
                                    Text(widget._name),
                                    Transform.rotate(
                                        angle: -math.pi/2,
                                        child:
                                        Transform.scale(
                                            scale: 0.75,
                                            child:
                                            Icon(Icons.arrow_back)
                                        )
                                    )
                                  ]
                              ),
                              onTap: () {
                                setState((){
                                  idHandler.toggleId(widget._id);
                                });
                              }
                          ),
                        ]
                    ),
                  ),
                  padding: EdgeInsets.all(0.0),
                  margin: EdgeInsets.all(0.0)
              ),
              MediaQuery.removePadding(
                  removeTop: true,
                  removeBottom: true,
                  removeLeft: true,
                  removeRight: true,
                  context: context,
                  child: ListView.builder(
                      physics: NeverScrollableScrollPhysics(),
                      shrinkWrap: true,
                      padding: EdgeInsets.all(0.0),
                      itemCount: widget._subCategories.length,
                      itemBuilder: (BuildContext context, int index){
                        return widget._subCategories[index];
                      }
                  )
              )
            ]
        );
      } else {
        return Container(
            height: MediaQuery.of(context).size.height*0.035,
            child:
            Align(
              alignment: Alignment.centerLeft,
              child:
              Wrap(
                  children: [
                    InkWell(
                        child:
                        Row(
                            children: [
                              Text(widget._name),
                              Transform.scale(
                                  scale: 0.75,
                                  child:
                                  Icon(Icons.arrow_back)
                              )
                            ]
                        ),
                        onTap: () {
                          setState((){
                            idHandler.toggleId(widget._id);
                          });
                        }
                    ),
                  ]
              ),
            ),
            padding: EdgeInsets.all(0.0),
            margin: EdgeInsets.all(0.0)
        );
      }
    } else {
      return Container(
          height: MediaQuery.of(context).size.
          height*0.035,
          child:
          Align(
            alignment: Alignment.centerLeft,
            child:
            Wrap(
                children:[
                  InkWell(
                      child: Row(
                          children: [
                            Text(widget._name),
                            Opacity(
                                opacity:0.0,
                                child:
                                Transform.scale(
                                    scale: 0.0,
                                    child:
                                    Icon(Icons.arrow_back)
                                )
                            ),
                          ]
                      ),
                      onTap: () {
                        crashTheApp();
                      }
                  ),
                ]
            ),
          ),
          padding: EdgeInsets.all(0.0),
          margin: EdgeInsets.all(0.0)
      );
    }
  }

  void crashTheApp(){
    dataView.incrementCounter();
    viewKey.currentState.reDraw();
    Navigator.of(context).pop();
  }

  @override
  void dispose(){
    super.dispose();
  }

}

class IdHandler {
  final Set<String> _openIds = {};

  void openId(String id) => _openIds.add(id);
  void closeId(String id) => _openIds.remove(id);
  void closeAll() => _openIds.clear();
  bool isIdOpen(String id) => _openIds.contains(id);
  void toggleId(String id){
    if(isIdOpen(id)){
      closeId(id);
    } else {
      openId(id);
    }
  }
}

class view extends StatefulWidget{

  view({Key key,}) : super(key: key);

  int counter=0;

  void incrementCounter(){
    counter++;
  }

  @override
  viewState createState() => new viewState();

}
class viewState extends State<view>{

  @override
  Widget build(BuildContext context) {
    return Center(
        child:
        Text("Count: "+widget.counter.toString())
    );
  }

  void reDraw(){
    setState(() {
    });
  }
}
``` 

</details>

Make sure pubspec.yaml has null safety disabled:
```
environment:
  sdk: ">=2.7.0 <3.0.0"
```

Launch the app. Open the navDrawer, click Test1, click Test1A, watch drawer close and counter update. Try to re-open the drawer, app crashes.

**Expected results:** 

Should be able to open navDrawer as many times as I want.

**Actual results:** 

The app crashes with the following error messages:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building RawGestureDetector(state: RawGestureDetectorState#9cc98(gestures: [horizontal drag], excludeFromSemantics: true)):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3705 pos 12: 'element._lifecycleState == _ElementLifecycle.inactive': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Scaffold file:///home/ttr/AndroidStudioProjects/savona_equipment/lib/main.dart:91:12
When the exception was thrown, this was the stack: 
#2      Element._activateRecursively (package:flutter/src/widgets/framework.dart:3705:12)
#3      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6185:16)
#4      Element._activateRecursively (package:flutter/src/widgets/framework.dart:3708:13)
#5      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
#6      Element._activateRecursively (package:flutter/src/widgets/framework.dart:3708:13)
```

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.

The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The key was:
- [GlobalKey#8e982]
This was determined by noticing that after the widget with the above global key was moved out of its previous parent, that previous parent never updated during this frame, meaning that it either did not update at all or updated before the widget was moved, in either case implying that it still thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to GlobalKey reparenting is:
- RepaintBoundary(renderObject: RenderRepaintBoundary#bc55c relayoutBoundary=up3)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2900:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2925:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:877:19)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
...
====================================================================================================
```
<details>
  <summary>Logs</summary>

```
 #218    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                      #219    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4628:14)
                      #220    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                      #221    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                      #222    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                      #223    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                      #224    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                      #225    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                      #226    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                      #227    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                      #228    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                      #229    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                      #230    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                      #231    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6185:16)
                      #232    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                      #233    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1845:7)
                      #234    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6070:14)
                      #235    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1843:13)
                      #236    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
                      #237    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1856:25)
                      #238    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2840:27)
                      #239    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2473:15)
                      #240    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2839:7)
                      #241    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:877:19)
                      #242    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
                      #243    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
                      #244    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
                      #245    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
                      #249    _invoke (dart:ui/hooks.dart:163:10)
                      #250    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
                      #251    _drawFrame (dart:ui/hooks.dart:126:31)
                      (elided 3 frames from dart:async)
                      ════════════════════════════════════════════════════════════════════════════════════════════════════
[+4563 ms] 
                    Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3705 pos 12: 'element._lifecycleState == _ElementLifecycle.inactive': is not true.
[  +17 ms] 
           Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5593 pos 14: 'oldChild == null || oldChild._lifecycleState == _ElementLifecycle.active': is not true.
[  +62 ms] 
           Another exception was thrown: Each child must be laid out exactly once.
[   +3 ms] 
           Another exception was thrown: Duplicate GlobalKey detected in widget tree.
[  +24 ms] 
           Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 6075 pos 12: 'child == _child': is not true.
[  +42 ms] 
           Another exception was thrown: Each child must be laid out exactly once.
[   +1 ms] 
           Another exception was thrown: Duplicate GlobalKey detected in widget tree.
[  +17 ms] 
           Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 6075 pos 12: 'child == _child': is not true.
[  +46 ms] 
           Another exception was thrown: Each child must be laid out exactly once.
[        ] 
           Another exception was thrown: Duplicate GlobalKey detected in widget tree.
[  +22 ms] 
           Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 6075 pos 12: 'child == _child': is not true.
[  +40 ms] 
           Another exception was thrown: Each child must be laid out exactly once.
[        ] 
           Another exception was thrown: Duplicate GlobalKey detected in widget tree.
[   +8 ms] 
           Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 6075 pos 12: 'child == _child': is not true.
[  +49 ms] 
           Another exception was thrown: Each child must be laid out exactly once.
[        ] 
           Another exception was thrown: Duplicate GlobalKey detected in widget tree.

```

```
No errors with analyze.
```

```
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_CA.UTF-8)
    • Flutter version 2.2.1 at /home/ttr/snap/flutter/common/flutter
    • Framework revision 02c026b03c (4 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ttr/Android/Sdk
    • Platform android-29, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 57.0.1
    • Dart plugin version 201.9380
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.56.2)
    • VS Code at /usr/share/code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-06-25 09:28
Hi @TaiTair 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and expected results vs actual results
Thank you

**Comment by TaiTair** [comment] 2021-06-25 15:09
> Hi @TaiTair
> Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), and expected results vs actual results
> Thank you

Ok I'm on it.

**Comment by TaiTair** [comment] 2021-06-25 16:35
I have updated the issue to include reproducible code and more insight as to what could be the cause.

**Comment by TahaTesser** [comment] 2021-06-28 07:48
Hi @TaiTair 
I just tried the code sample, I can reproduce the issue, however, the code you provided is very bloaty, doesn't help narrow the cause of the issue, a minimal sample includes the code that is needed to reproduce and it must be as small as possible while still reproducing the issue. Please remove all decoration, class implementations and provide a minimal sample, please read https://stackoverflow.com/help/minimal-reproducible-example for instructions

**Comment by TaiTair** [comment] 2021-06-28 17:36
> Hi @TaiTair
> I just tried the code sample, I can reproduce the issue, however, the code you provided is very bloaty, doesn't help narrow the cause of the issue, a minimal sample includes the code that is needed to reproduce and it must be as small as possible while still reproducing the issue. Please remove all decoration, class implementations and provide a minimal sample, please read https://stackoverflow.com/help/minimal-reproducible-example for instructions

Very bloaty?
I literally removed everything that wasn't necessary to produce the crash. Even the data is hard-coded instead of using my API.
I understand that this looks "big" to you but it comes from a much bigger project and has already been minimized for you.

I don't have the time to do more for you. I'm not going to re-write you an app just to pin-point exactly what's happening. That is not my job. I've already been kind enough to provide you with a reproducible code sample.

Thanks.

**Comment by TahaTesser** [comment] 2021-06-29 08:15
Hi @TaiTair 
After debugging your code further, your code is calling has disposed errors and `'oldChild == null || oldChild._lifecycleState == _ElementLifecycle.active': is not true` is caused when you're calling setState in the widget tree widget is not mounted https://github.com/flutter/flutter/issues/21675#issuecomment-422229141 as result you get `Duplicate GlobalKey detected in the widget tree.` as well. 

Unfortunately, this seems an issue with your code, if you could narrow the test code to flutter specifically rather than your code, you will only need minimal, doesn't need dummy API or decorations.

**Comment by TahaTesser** [comment] 2021-07-21 12:15
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-07-21 12:15 UTC
