### ISSUE TITLE
fluttergpu has a lot of linter warnings

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#153181] opened 2024-08-09 17:24 UTC
These show up in my vscode as problems when just editing c++ code.

<img width="488" alt="Screenshot 2024-08-09 at 10 14 33 AM" src="https://github.com/user-attachments/assets/1dce140b-65bb-4529-ad3b-9b8dd50fbc51">

seen at: 206e86ee8a40ad28233338b7a99a2b083cdce85f

cc @bdero

**Comment by gaaclarke** [comment] 2024-08-09 17:28
These can be filtered out by selecting the "Show active files only" filter option in the problems view.

**Comment by matanlurey** [comment] 2024-08-09 19:14
Possibly related/dupe: https://github.com/flutter/flutter/issues/152002

**Comment by matanlurey** [comment] 2024-08-09 19:15
In the future this will be prevented by https://github.com/flutter/flutter/issues/152636.

**Comment by jonahwilliams** [comment] 2024-08-12 17:40
Closing as dupe of https://github.com/flutter/flutter/issues/152002

**Closed by jonahwilliams** 2024-08-12 17:40 UTC
Labels: team-engine
