### ISSUE TITLE
Android platform FD leak

### ISSUE THREAD

**Issue by Carpeiem007** [flutter/flutter#85692] opened 2021-07-01 11:05 UTC
Hi
    
When we used Flutter on Android platform, some crashes occurred. We checked and found that it was caused by FD leakage. Every time we opened a new page of Flutter, FD would increase.Android has limits on FD, which can cause a crash if exceeded.

We found that only Mail's GPU architecture caused this problem. [Mali (GPU)](https://zh.wikipedia.org/wiki/Mali_(GPU))

![image](https://user-images.githubusercontent.com/20220659/124114114-c2092800-da9e-11eb-98db-e44541b7ccab.png)

This is the log of fd growing all the time.

Can you help us fix this problem? thanks  (=^_^=)

flutter doctor 
<img width="1100" alt="QQ20210701-185435@2x" src="https://user-images.githubusercontent.com/20220659/124114327-05fc2d00-da9f-11eb-9b00-2ff645f918c5.png">

**Comment by PingShen** [comment] 2021-07-01 11:07
I also meet this crash
so serious
pls fix this asap!!!!

**Comment by TahaTesser** [comment] 2021-07-01 14:46
Hi @Carpeiem007 
Unfortunately, the version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.

I kindly advise you to update to the latest Fluter `stable`, if you encounter this issue, please comment below with the details from the latest stable, including steps to replicate the issue.

Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`


If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?

Thank you

**Comment by Carpeiem007** [comment] 2021-07-02 09:29
> Hi @Carpeiem007
> Unfortunately, the version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.
> 
> I kindly advise you to update to the latest Fluter `stable`, if you encounter this issue, please comment below with the details from the latest stable, including steps to replicate the issue.
> 
> Can you please upgrade to the latest `stable` and try again
> Execute the following commands to upgrade
> `flutter channel stable`
> `flutter upgrade --force`
> `flutter doctor -v`
> 
> If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
> 
> Thank you

I used 2.2.3-stable version without this problem, but I would like to ask, what caused it? Can you tell me? Can I fix it if I don't upgrade it? We cannot upgrade the version at this time.

**Comment by TahaTesser** [comment] 2021-07-02 10:18
@Carpeiem007 
We can investigate the cause if it reproduces on the stable.
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-07-02 10:18 UTC
Labels: in triage
