### ISSUE TITLE
Flutter outputs 'ASSERT != ' log while showing the hebrew character in Linux environment

### ISSUE THREAD

**Issue by GoYamazaki** [flutter/flutter#115126] opened 2022-11-11 00:29 UTC
Showing some of the Hebrew characters with `\u05bc` ([HEBREW POINT DAGESH OR MAPIQ](https://www.fileformat.info/info/unicode/char/05bc/index.htm)) makes Flutter output the ASSERT log with the following format.

`ASSERT: 16.439941 != 17.270508`

Why (Where in the Flutter code) this ASSERT log is output?   

## Steps to Reproduce

1. Tested on Ubuntu desktop.
1.1. Ubuntu 20.04.3 LTS
1.1. Both `linux` and `web` devices output the log.
2. MacOS envrionment (`macos`, `web`) did not output the log.

1. Execute `flutter run` on the code sample 

**Expected results:** ASSERT log should not be output.

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('\u{05E9}\u{05BC}'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text(
                '\u{05E4}\u{05BC}',
                style: Theme.of(context).textTheme.headline1,
              ),
            ],
          ),
        ), // This trailing comma makes auto-formatting nicer for build methods.
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
$ flutter run -d linux --verbose                                                   

[  +51 ms] executing: uname -m
[  +29 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +7 ms] executing: [/home/hoge/development/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +9 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] executing: [/home/hoge/development/flutter/] git tag --points-at
fb57da5f945d02ef4f98dfd9409a72b7cce74268
[  +21 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] 3.0.1
[  +10 ms] executing: [/home/hoge/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +61 ms] executing: [/home/hoge/development/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +53 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +53 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +67 ms] Skipping pub get: version match.
[ +115 ms] Generating
/home/hoge/work/WS/hebrew_test/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.
java
[  +82 ms] Initializing file store
[  +10 ms] Skipping target: gen_localizations
[   +9 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following
inputs have updated contents: /home/hoge/work/WS/hebrew_test/.dart_tool/package_config_subset}
[  +26 ms] gen_dart_plugin_registrant: Complete
[   +1 ms] Skipping target: _composite
[   +2 ms] complete
[   +5 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/hoge/development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/hoge/development/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot
--sdk-root /home/hoge/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.GLMZGW/flutter_tool.BWPEIR/app.dill
--packages /home/hoge/work/WS/hebrew_test/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --flutter-widget-cache
--enable-experiment=alternative-invalidation-strategy
[  +24 ms] Building Linux application...
[  +16 ms] <- compile package:hebrew_test/main.dart
[   +5 ms] executing: [build/linux/x64/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
-DFLUTTER_TARGET_PLATFORM=linux-x64 /home/hoge/work/WS/hebrew_test/linux
[  +62 ms] -- Configuring done
[   +4 ms] -- Generating done
[   +2 ms] -- Build files have been written to: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug
[   +7 ms] executing: ninja -C build/linux/x64/debug install
[  +13 ms] ninja: Entering directory `build/linux/x64/debug'
[+11904 ms] [1/5] Generating /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/libflutter_linux_gtk.so, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_method_response.h, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_value.h, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/fl_view.h, /home/hoge/work/WS/hebrew_test/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +2 ms] [  +58 ms] executing: uname -m
[        ] [  +32 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[        ] [   +5 ms] executing: [/home/hoge/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] [        ] executing: [/home/hoge/development/flutter/] git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] [  +16 ms] Exit code 0 from: git tag --points-at fb57da5f945d02ef4f98dfd9409a72b7cce74268
[        ] [        ] 3.0.1
[        ] [   +7 ms] executing: [/home/hoge/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +4 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] fatal: HEAD does not point to a branch
[        ] [  +59 ms] executing: [/home/hoge/development/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] HEAD
[        ] [  +41 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +84 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +20 ms] Initializing file store
[        ] [   +5 ms] Done initializing file store
[        ] [  +28 ms] Skipping target: gen_localizations
[        ] [   +9 ms] Skipping target: gen_dart_plugin_registrant
[        ] [ +459 ms] Skipping target: unpack_linux
[        ] [ +375 ms] kernel_snapshot: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/hoge/work/WS/hebrew_test/lib/main.dart}
[   +1 ms] [   +7 ms] /home/hoge/development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/hoge/development/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/hoge/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --packages
/home/hoge/work/WS/hebrew_test/.dart_tool/package_config.json --output-dill /home/hoge/work/WS/hebrew_test/.dart_tool/flutter_build/1122d8bf7cb7075a35d6c1c886911515/app.dill --depfile
/home/hoge/work/WS/hebrew_test/.dart_tool/flutter_build/1122d8bf7cb7075a35d6c1c886911515/kernel_snapshot.d package:hebrew_test/main.dart
[   +1 ms] [+9099 ms] kernel_snapshot: Complete
[        ] [ +638 ms] debug_bundle_linux-x64_assets: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/hoge/work/WS/hebrew_test/.dart_tool/flutter_build/1122d8bf7cb7075a35d6c1c886911515/app.dill}
[        ] [ +156 ms] debug_bundle_linux-x64_assets: Complete
[        ] [ +239 ms] Persisting file store
[        ] [   +5 ms] Done persisting file store
[        ] [   +4 ms] build succeeded.
[        ] [   +7 ms] "flutter assemble" took 11,163ms.
[        ] [   +5 ms] ensureAnalyticsSent: 1ms
[        ] [        ] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +615 ms] [2/5] Building CXX object CMakeFiles/hebrew_test.dir/flutter/generated_plugin_registrant.cc.o
[  +29 ms] [3/5] Building CXX object CMakeFiles/hebrew_test.dir/my_application.cc.o
[ +183 ms] [4/5] Linking CXX executable intermediates_do_not_run/hebrew_test
[        ] [4/5] Install the project...
[  +11 ms] -- Install configuration: "Debug"
[   +1 ms] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/hebrew_test
[   +1 ms] -- Set runtime path of "/home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/hebrew_test" to "$ORIGIN/lib"
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/icudtl.dat
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so
[  +58 ms] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/packages
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES
[   +2 ms] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/version.json
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/NOTICES.Z
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +62 ms] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing: /home/hoge/work/WS/hebrew_test/build/linux/x64/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.otf
[  +17 ms] Building Linux application... (completed in 13.0s)
[ +272 ms] Observatory URL on device: http://127.0.0.1:35141/aN8mfjnEcHE=/
[   +5 ms] Caching compiled dill
[  +29 ms] Connecting to service protocol: http://127.0.0.1:35141/aN8mfjnEcHE=/
[ +174 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:35141/aN8mfjnEcHE=/.
[  +92 ms] DDS is listening at http://127.0.0.1:46039/OT-6gbA3C3E=/.
[  +62 ms] Successfully connected to service protocol: http://127.0.0.1:35141/aN8mfjnEcHE=/
[  +45 ms] DevFS: Creating new filesystem on the device (null)
[  +19 ms] DevFS: Created new filesystem on the device (file:///tmp/hebrew_testYHJRTT/hebrew_test/)
[   +2 ms] Updating assets
[ +113 ms] Syncing files to device Linux...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[   +2 ms] <- recompile package:hebrew_test/main.dart b7324354-a5d7-4d8a-af47-a0b2c2417ce4
[        ] <- b7324354-a5d7-4d8a-af47-a0b2c2417ce4
[   +2 ms] Bundle processing done.
[ +103 ms] Updating files.
[        ] DevFS: Sync finished
[   +3 ms] Syncing files to device Linux... (completed in 114ms)
[        ] Synced 0.0MB.
[   +2 ms] <- accept
[   +2 ms] Connected to _flutterView/0x10d9790.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[   +1 ms] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[   +3 ms] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:46039/OT-6gbA3C3E=/
[ +200 ms] ASSERT: 63.218750 != 69.945312
[        ] ASSERT: 0.000000 != -6.726562
[  +88 ms] The Flutter DevTools debugger and profiler on Linux is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:46039/OT-6gbA3C3E=/

```

```
$ flutter analyze               
Analyzing hebrew_test...                                                
No issues found! (ran in 1.5s)
```

```
[✓] Flutter (Channel unknown, 3.0.1, on Ubuntu 20.04.3 LTS 5.15.0-52-generic, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /home/go-yamazaki/development/flutter
    • Upstream repository unknown
    • Framework revision fb57da5f94 (6 months ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    • Android SDK at /usr/lib/android-sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/go-yamazaki/android-studio
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.70.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.3 LTS 5.15.0-52-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by exaby73** [comment] 2022-11-11 10:46
Hello @GoYamazaki. I cannot reproduce this issue with the latest stable (3.3.7) or master. Can you please upgrade to stable and confirm?

**Comment by GoYamazaki** [comment] 2022-11-15 01:12
Hi @exaby73 . Thank you for your comment, and sorry for the late reply.

Thanks to you, I have solved this issue by upgrading my flutter version.
But my question still remains how could I find where in the flutter-engine code output that ASSERT log? 
Do you have any tips that I could use when I investigate the flutter-engine code?
Thank you.

**Comment by exaby73** [comment] 2022-11-15 07:10
You can use [Github's Code Search](https://github.com/search?q=repo%3Aflutter%2Fengine+ASSERT&type=code). Not sure if that could help you much though. But since this issue is fixed in the latest version, I am closing this issue. Thank you.

**Closed by exaby73** 2022-11-15 07:10 UTC
Labels: in triage
