### ISSUE TITLE
> After each picture is larger than 50kb, the redirect route will return and the picture will be reloaded. Is there a bug in flutter image Wdiget?

### ISSUE THREAD

**Issue by poison8** [flutter/flutter#94703] opened 2021-12-06 03:28 UTC
> After each picture is larger than 50kb, the redirect route will return and the picture will be reloaded. Is there a bug in flutter image Wdiget?
> 
>  QQ.20211204114629.mp4

Thanks for filing this issue. Can you show any reproducible code for regenerating this issue . 

I am not sure but may be it has something to do with asynchronous programming. Are you fetching those images from any API ?

_Originally posted by @Sahil-kachhap in https://github.com/flutter/flutter/issues/94648#issuecomment-986302921_

How to solve this problem???  

I've tested many methods, but they don't work

**Comment by darshankawar** [comment] 2021-12-06 07:37
Closing as self-duplicate of https://github.com/flutter/flutter/issues/94648
Please don't open multiple issues for same reason.

**Closed by darshankawar** 2021-12-06 07:37 UTC
Labels: in triage
