### ISSUE TITLE
Listview flashing when image comes into view

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#14141] opened 2018-01-17 17:51 UTC
I am seeing an issue where the screen is flashing when I scroll an image into view.   I am seeing this on an iPhone 5s running 11.2.2 and on a Nexus 5X running 7.1.2.  

It does seem to only affect certain images, though I can't say exactly what it is about them that causes it to happen.  I have attached an image to this issue that demonstrates the issue.

Here is a video of it happening: https://www.youtube.com/watch?v=Y3KUKsrq7os

A sample image to use that causes the issue: 
![image](https://user-images.githubusercontent.com/9346834/35057994-9b32024e-fb84-11e7-8d4a-d1c618a48e11.png)

The `main.dart` code to use to see the issue:
```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new ListView(
        children: <Widget>[
          _child(),
          new Container(
            height: 500.0,
            color: Colors.red,
          ),
          new Container(
            height: 500.0,
            color: Colors.green,
          ),
          new Container(
            height: 500.0,
            color: Colors.blue,
          ),
          new Container(
            height: 500.0,
            color: Colors.yellow,
          ),
        ],
      ),
    );
  }

  Widget _child() {
    return new Padding(
      padding: const EdgeInsets.only(
        left: 12.0,
        right: 12.0,
        top: 5.0,
        bottom: 10.0,
      ),
      child: new Image.asset(
        "assets/images/pngtest0.png",
      ),
    );
  }
}
```

## Steps to Reproduce

- Create a new flutter project, add the image above to your assets/pubspec.yaml
- Use the code above in main.dart
- Scroll to bottom of the list, then scroll back to the top.
- See flash

## Logs
There was nothing logged after the project began running

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.12.6 16G1114, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 0e903d9544 (2 days ago), 2018-01-15 09:43:01 -0500
    • Engine revision 05fe72d068
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.28757928b47b192efcec082c78258102beb03f78

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 3.0RC2.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.2.6)
    • Flutter plugin version 19.1
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Nexus 5X           • 0106bcc49c8ca3eb                         • android-arm • Android 7.1.2 (API 25)
    • iPhone             • a343cf06739643813928707a674dd1ae905fa75d • ios         • iOS 11.2.2

```

**Comment by mchome** [comment] 2018-01-17 18:01
Yeah, i have the same problem. I use a controller to track the `controller.position.maxScrollExtent`, when i scroll almost to the top, the value down to 0.0 and the screen flashing.

**Comment by jason-simmons** [comment] 2018-01-17 22:20
Looks like this was introduced in https://github.com/flutter/flutter/commit/5c4ffa13a6c4f00ea6f752866e9393ee6395d469

I was able to work around it for this test case by changing the check that applies the SliverPadding in BoxScrollView.buildSlivers to:
    ```if (effectivePadding != null && effectivePadding != EdgeInsets.zero)```

Not sure if this is a general solution though.

@xster @Hixie

**Comment by xster** [comment] 2018-01-17 23:35
I think the proposed line will reduce the frequency of the issue but there's still an underlaying issue.

I tested with the code below:

```dart
Widget build(BuildContext context) {
  SliverChildListDelegate sliverDelegate = new SliverChildListDelegate(
    <Widget>[
      new Container(
        height: 500.0,
        color: Colors.red,
      ),
      new Padding(
        padding: const EdgeInsets.symmetric(
          horizontal: 90.0
        ),
        child: new Image.asset('assets/test.png'),
      ),
      new Container(
        height: 500.0,
        color: Colors.green,
      ),
      new Container(
        height: 500.0,
        color: Colors.blue,
      ),
      new Container(
        height: 500.0,
        color: Colors.yellow,
      ),
    ]
  );

  return new Scaffold(
    appBar: new AppBar(
      title: const Text('Sliver flashing test'),
    ),
    body: new CustomScrollView(
      slivers: <Widget>[
        new SliverPadding(
          // padding: const EdgeInsets.symmetric(vertical: 20.0),
          padding: EdgeInsets.zero,
          sliver: new SliverList(
            delegate: sliverDelegate,
          ),
        )
      ],
    ),
  );
}
```

which is the underlaying components to the code above and doesn't include BoxScrollView. Playing with a few permutations, it seems like there is flashing when there's a SliverList and a Padding inside with an Asset where the Padding is the cross axis.

**Comment by xster** [comment] 2018-02-06 19:32
Adding to milestone since it's fairly easy to encounter on a common component

**Comment by Hixie** [comment] 2018-02-06 22:45
This kind of issue isn't in our current list of priorities, though it will likely be a higher priority in the medium term. Moving to m4.

**Comment by deremer** [comment] 2018-02-08 23:35
@Hixie @xster Well the problem is that we just spent a lot of time creating a new home screen experience for the Hamilton app and this flash frankly ruins it. It makes the app feel buggy and bad. It's a pretty common user behavior to scroll a little bit down a list then scroll back to the top...and this flash happens nearly every time. So if we launch this it's going to be visible to 100's of thousands of people. I'm borderline considering holding it back until this is fixed, but that would be very bad. 

Please advise.

**Comment by Hixie** [comment] 2018-02-09 07:57
I totally agree that it's important, it's just competing with a bunch of other critical work.
If you are able to pin down the cause of the bug, we can probably find the time to write a fix and a test for the fix. Just looking at the code above I can't imagine what could be causing it, so we have to track down the cause before we can fix it.

**Comment by eseidelGoogle** [comment] 2018-02-09 16:30
@deremer and I spoke this morning.  As he notes above, this has occurred on one of the main screens in the next update of HamApp and is blocking their release. :/  They're looking for a workaround or fix.

I attempted to reproduce just now on my iPhone 6s and was unable to, presumably it's screen-size specific.

**Comment by eseidelGoogle** [comment] 2018-02-09 16:37
I don't really understand what could make it paint white.  Could this be bad raster cache behavior?  Bad layout behavior?

I wonder if any of the debug.dart options would shed any light:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/debug.dart
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/debug.dart

**Comment by eseidelGoogle** [comment] 2018-02-09 16:57
I'm not able to repo this on
`Nexus 5X • 00d44fa710453aa9                     • android-arm64 • Android 8.0.0 (API 26)`

With 
```
Flutter 0.0.25-pre.22 • channel master • git@github.com:flutter/flutter.git
Framework • revision f5bbc5bb76 (7 hours ago) • 2018-02-09 11:16:58 +0100
Engine • revision 9bc2efdf47
Tools • Dart 2.0.0-dev.20.0
```

**Comment by eseidelGoogle** [comment] 2018-02-09 16:58
Nevermind, it repros now.

**Comment by eseidelGoogle** [comment] 2018-02-09 17:10
Nothing interesting shows up from `debugRepaintRainbowEnabled` or `showPerforamanceOverlay`.

I have to imagine this is an engine bug?

Do we have any way to save displaylists from every frame?

I'm able to repro by scrolling slowly.  I'm not able to get it to stay on the white frame however.

**Comment by eseidelGoogle** [comment] 2018-02-09 17:49
Ok, so here is a reproduction:
https://github.com/eseidelGoogle/scrolling_flash

`flutter drive --target=test_driver/flash.dart` to run it.

With that it's clear that it's only the list which is turning white, not the whole screen.  Now that I understand that, I can actually see it in the video too:

<img width="536" alt="screen shot 2018-02-09 at 9 48 35 am" src="https://user-images.githubusercontent.com/11857803/36041763-7acb52b0-0d7e-11e8-8d98-f3b6735a10ac.png">

**Comment by xster** [comment] 2018-02-10 09:55
Ummm strange, I could repro before but can't anymore (though I forgot to take note of the device I used). Will test more Monday when I got more devices to try.

**Comment by xster** [comment] 2018-02-13 10:09
The bug is somewhere inside the RenderSliverList. For one frame, it ends up returning a SliverGeometry with scrollExtent 0, maxPaintExtent 0 etc.

**Comment by xster** [comment] 2018-02-13 10:50
Seems like some sort of numerical rounding issue. The RenderImage correctly calculates a sane height and width based on the aspect ratio box contraints (coming from cross axis padding). But when checking for its `paintExtentOf` again in the RenderSliverList, somehow some of the RenderObjects wrapping the RenderImage reports approximations like 85.78500000000001 instead of 85.8 which puts the start offset of the image at 499.99999999999994 instead of 500. 

This eventually makes the list think it underflowed when going from second to first item in the list which now has a offset of something like -5.684341886080802e-14

**Comment by xster** [comment] 2018-02-13 11:07
Correction, the issue is in the way the BoxContraints' `constrainSizeAndAttemptToPreserveAspectRatio` is calculated.

Note to self:
```
I/flutter ( 1495): earliest useful child RenderRepaintBoundary#256a8 relayoutBoundary=up3 with offset 585.785 at offset 585.5344605399483
I/flutter ( 1495): inserting first child RenderRepaintBoundary#9e960 NEEDS-LAYOUT NEEDS-PAINT with constraints BoxConstraints(w=411.4, 0.0<=h<=Infinity)
I/flutter ( 1495): image size for constraint BoxConstraints(w=233.4, 0.0<=h<=Infinity)
I/flutter ( 1495): preserving aspect ratio to size Size(1200.0, 441.0) with height 441.0
I/flutter ( 1495): bigger than max width, based on aspect ratio 2.7210884353741496 and width 233.42857142857144, new height 85.78500000000001
I/flutter ( 1495): result size Size(233.4, 85.8) with constrain height 85.78500000000001 and height 85.78500000000001
I/flutter ( 1495): padding size Size(411.4, 85.8)
I/flutter ( 1495): paint extent of render box RenderRepaintBoundary#9e960 relayoutBoundary=up3 NEEDS-PAINT with size type _DebugSize with height 85.78500000000001
I/flutter ( 1495): paint extent of render box RenderRepaintBoundary#9e960 relayoutBoundary=up3 NEEDS-PAINT with size type _DebugSize with height 85.78500000000001
I/flutter ( 1495): first child RenderRepaintBoundary#9e960 relayoutBoundary=up3 NEEDS-PAINT with paint extent 85.78500000000001 making first scroll offset 499.99999999999994 with earliest offset 585.785
```

The newly aspect ratio conforming height of 85.78500000000001 causes problems.

**Comment by Hixie** [comment] 2018-02-13 18:39
RenderSliverList is supposed to be able to handle the first item having an offset of something like -5.684341886080802e-14, that's definitely something we expect to see (since we're scrolling with dead reckoning).

**Closed** 2018-02-21 22:51 UTC
Labels: customer: posse (eap), prod: framework, prod: scrolling

**Comment by abacaj** [comment] 2018-10-09 19:54
I am seeing this still in flutter `Flutter (Channel master, v0.9.7-pre.79`

Was this fixed? @Hixie

**Comment by xster** [comment] 2018-10-09 20:16
This should have been fixed earlier this year. If you're seeing this bug, please open a new with a description of the repro steps.
