### ISSUE TITLE
Better stacktrace and less polluted logs in Android Studio

### ISSUE THREAD

**Issue by pulstar** [flutter/flutter#59591] opened 2020-06-16 20:06 UTC
## Use case

This kind of error messages and stacktrace gives absolutely no clue where the problem really is...

```
════════ Exception caught by widgets library ══════════
The following assertion was thrown building Listener:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1960 pos 12: '_elements.contains(element)': is not true.

The relevant error-causing widget was: 
  SingleChildScrollView file:///C:/some_project/lib/src/some_file.dart:2393:12
When the exception was thrown, this was the stack: 
#2      _InactiveElements.remove (package:flutter/src/widgets/framework.dart:1960:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:3405:29)
...     Normal element mounting (7 frames)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
...
```

## Proposal

Everytime I see the file "framework.dart" in the logs I know I am in serious trouble... A better stacktrace should include the files and lines that the execution take place. The only file and line that is shown in the log belong to a parent widget that is not causing the error.

Also, the logs in the run tab are becoming a lot polluted... It is hard to find anything relevant among so many messages.

Why the logcat tab always show the message "Please configure Android SDK"? The SDK is already configured. The logcat sometimes work, but mostly of time it doesn't.

Sometimes, when the IDE marks some code with a red line, when I try to see what is by placing the mouse cursor above it, it display a message VERY FAST and I can't read what is there...  :-(

**Comment by iapicca** [comment] 2020-06-17 08:27
Hi @pulstar 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-17 08:27 UTC
