### ISSUE TITLE
allow us to mv targets into targets/ folder

### ISSUE THREAD

**Issue by amills-vibeirl** [flutter/flutter#141539] opened 2024-01-14 20:22 UTC
### Use case

this structure will clean-up people's codebases:
----------------------

<kbd>
<img width="387" alt="Screen Shot 2024-01-14 at 12 30 09 AM" src="https://github.com/flutter/flutter/assets/150489986/de0ebde7-7cae-4943-9521-2a672e96eb49">
</kbd>

---------------------------------

and collapsed it looks like:

<kbd>
<img width="397" alt="Screen Shot 2024-01-14 at 12 29 59 AM" src="https://github.com/flutter/flutter/assets/150489986/f6327c25-2597-4eb0-8a56-8a3126f6ca0d">
</kbd>

--------------------------

however, all info points to this being a difficult to accomplish change
can we make basic configuration changes like this easier. IMO this structure should be the default

### Proposal

flutter direct

**Comment by stuartmorgan** [comment] 2024-01-14 20:26
Duplicate of https://github.com/flutter/flutter/issues/71400

**Closed by stuartmorgan** 2024-01-14 20:26 UTC

**Comment by amills-vibeirl** [comment] 2024-01-14 22:53
why no plan? plan is good
