### ISSUE TITLE
Incorrect scroll behavior when scrolling nested ListViews using two finger scrolling on a touchpad  

### ISSUE THREAD

**Issue by jonaird** [flutter/flutter#70046] opened 2020-11-08 09:40 UTC
## Steps to Reproduce

1. Create nested ListViews, that is to say a ListView with vertical scroll axis that has other ListViews (with horizontal scroll axis) as children.
2. Try to scroll in the vertical direction and try scrolling in the horizontal direction using two finger scrolling on a touch pad. In the horizontal direction, the scroll axis is properly locked but it isn't in the vertical direction. Try scrolling vertically slowly with two fingers held down and scroll up and down without picking up your fingers rather than a quick flick. The quick flick seems to work properly.

Here's the code to reproduce the error. I've only tested this on a MacBook in Flutter Web:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          itemBuilder: (context, index) => Container(
            height: 210,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              itemBuilder: (context, index) => Box(),
            ),
          ),
        ),
      ),
    );
  }
}

class Box extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
        height: 200,
        width: 200,
        padding: EdgeInsets.all(10),
        child: Container(
          color: Colors.grey,
        ));
  }
}
```

**Expected results:** 

The desired result is that when you begin scrolling vertically, the scroll direction is "locked" and you will not accidentally scroll horizontally as is the case when you scroll by dragging the mouse (or via touch screen);

**Actual results:** 
Instead scrolling vertically is very buggy and it switches back and forth between horizontal and vertical scrolling. 
Here is a video of the behavior:
[bug video.zip](https://github.com/flutter/flutter/files/5506094/bug.video.zip)

<details>
  <summary>Logs</summary>

```
flutter run --verbose
[ +163 ms] executing: [/Users/jonathanaird/developer/flutter sdk/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +73 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 198df796aa80073ef22bdf249e614e2ff33c6895
[        ] executing: [/Users/jonathanaird/developer/flutter sdk/flutter/] git tag --points-at HEAD
[  +28 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.23.0-18.1.pre
[  +20 ms] executing: [/Users/jonathanaird/developer/flutter sdk/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/jonathanaird/developer/flutter sdk/flutter/] git ls-remote --get-url
origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +86 ms] executing: [/Users/jonathanaird/developer/flutter sdk/flutter/] git rev-parse --abbrev-ref
HEAD
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +9 ms] executing: sw_vers -productName
[  +48 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] Mac OS X
[   +1 ms] executing: sw_vers -productVersion
[  +28 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.7
[        ] executing: sw_vers -buildVersion
[  +27 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19H2
[        ] executing: uname -m
[   +7 ms] Exit code 0 from: uname -m
[        ] x86_64
[  +75 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +150 ms] executing: /Users/jonathanaird/Library/Android/sdk/platform-tools/adb devices -l
[  +13 ms] executing: /usr/bin/xcode-select --print-path
[  +13 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Library/Developer/CommandLineTools
[   +2 ms] executing: /usr/bin/xcodebuild -version
[   +5 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory
'/Library/Developer/CommandLineTools' is a command line tools instance
[        ] Xcode not found. Run 'flutter doctor' for more information.
[   +2 ms] executing: /usr/bin/xcodebuild -version
[   +7 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[   +1 ms] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory
'/Library/Developer/CommandLineTools' is a command line tools instance
[  +74 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] executing: /usr/bin/xcodebuild -version
[   +5 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[   +1 ms] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory
'/Library/Developer/CommandLineTools' is a command line tools instance
[  +70 ms] Multiple devices found:
[ +225 ms] Web Server (web) • web-server • web-javascript • Flutter Tools
[   +1 ms] Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.183
[   +2 ms] [0]: Web Server (web-server)
[        ] [1]: Chrome (chrome)
[   +2 ms] Please choose one (To quit, press "q/Q")
[        ] : 
```

```
No issues found! (ran in 3.1s)
```

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/jonathanaird/developer/flutter sdk/flutter
    • Framework revision 198df796aa (3 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jonathanaird/Library/Android/sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from
        the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.183
```

</details>

**Comment by TahaTesser** [comment] 2020-11-09 10:14
Hi @jonaird 
Thanks for the filing the issue, I can reproduce on web and desktop 

### Preview
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/98528496-62a5a000-22a2-11eb-954a-6a42ee53167e.gif)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          itemBuilder: (context, index) => Container(
            height: 210,
            child: ListView.builder(
              scrollDirection: Axis.horizontal,
              itemBuilder: (context, index) => Box(),
            ),
          ),
        ),
      ),
    );
  }
}

class Box extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
        height: 200,
        width: 200,
        padding: EdgeInsets.all(10),
        child: Container(
          color: Colors.grey,
        ));
  }
}

```

</details>

<details> 
<summary>multiple flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H15 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-18.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/SanDisk/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile)       • 00008020-000255113EE8402E            • ios
      • iOS 14.2
    • iPhone 12 Pro Max (mobile) • 0A159C14-BF48-4DD7-8D91-F45A387EE4B2 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 86.0.4240.183
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

• No issues found!
```

```bash
[✓] Flutter (Channel master, 1.24.0-8.0.pre.149, on Mac OS X 10.15.7 19H15
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-8.0.pre.149 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 8e7748e74c (5 hours ago), 2020-11-08 20:32:04 -0800
    • Engine revision 0f7cdca65f
    • Dart version 2.12.0 (build 2.12.0-27.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/SanDisk/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • Taha’s iPad (mobile)       • 00008020-000255113EE8402E            • ios
      • iOS 14.2
    • iPhone 12 Pro Max (mobile) • 0A159C14-BF48-4DD7-8D91-F45A387EE4B2 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.7 19H15 darwin-x64
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 86.0.4240.183
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

• No issues found!

```

</details>

**Comment by creativecreatorormaybenot** [comment] 2020-11-21 18:34
@jonaird @TahaTesser I can only reproduce this on a MacBook. What device / touchpad did you use to reproduce it?

I **cannot** reproduce it on a ThinkPad (even if I try) - the scroll seems to be correctly locked there.

**Comment by jonaird** [comment] 2020-11-21 18:53
Just tried on a MacBook. Could be that on the Thinkpad the locking happens at the driver/OS level?

**Comment by IchordeDionysos** [comment] 2020-11-21 18:54
Happens to me on both the built in and the external Apple trackpad :)

**Comment by creativecreatorormaybenot** [comment] 2020-11-21 18:54
@jonaird 👍 

Seems to be also happening on Magic Trackpad.

**Comment by Piinks** [comment] 2021-01-14 20:38
> /cc @Piinks Would you have time to take a look at this? (Desktop Triage)

Sure! I'll add it to my queue. :)

**Comment by Piinks** [comment] 2021-02-08 17:10
The right way to solve this is most likely by adding official support for trackpads. I've seen a few mentions of trackpad behaviors in a couple of issues recently.. I am not sure what it will take to complete currently, and I have a few other scrolling issues of higher priority that will probably precede work here.

Also, cc @goderbauer since the application above is an example of 2D scrolling. When 2D scrolling is also supported officially this may not be an issue anymore.

**Comment by Piinks** [comment] 2021-03-15 22:26
I am not actively working on implementing trackpad support, so I am going to remove my assignment for now. Per https://github.com/flutter/flutter/issues/70046#issuecomment-775298491 there is work underway on 2D scrolling that may also provide a solution.

**Comment by SardorbekR** [comment] 2022-03-12 09:30
Any news? This issue still persists @gspencergoog @TahaTesser I'm having this issue while scrolling on Flutter Web

**Comment by Piinks** [comment] 2022-09-20 19:21
I've tried this on the master branch today and found that the errant behavior described above is now fixed.

When using two finger scrolling on trackpad, the axis that is not scrolling is locked, eliminating the stutter behavior in the above videos.

Many thanks to @moffatman! 🎉

**Closed by Piinks** 2022-09-20 19:21 UTC
Labels: framework, platform-mac, f: scrolling, a: quality, a: desktop, has reproducible steps, P3, found in release: 1.23, found in release: 1.24
