### ISSUE TITLE
Add support for onMouseEnter / onMouseExit

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#22815] opened 2018-10-08 16:36 UTC
For when a Flutter app is running on a device with a connected mouse.

**Comment by zoechi** [comment] 2018-12-21 09:08
Related to #757

**Comment by goderbauer** [comment] 2019-01-03 22:06
Dupe of https://github.com/flutter/flutter/issues/5504.

**Closed by goderbauer** 2019-01-03 22:06 UTC
Labels: framework, ⎊ platform-chromebook
