### ISSUE TITLE
Flutter web requires internet to debug when running in Canvas mode

### ISSUE THREAD

**Issue by timsneath** [flutter/flutter#105421] opened 2022-06-06 03:23 UTC
Per 
https://twitter.com/lesnitsky_dev/status/1533585292023717889

On the surface, this looks similar to https://github.com/flutter/flutter/issues/60069, but flagging it since it looked like that was fixed for CanvasKit?

At the very least, we should document any necessary steps to prepare a machine for offline work. /cc @kevmoo

**Comment by maheshmnj** [comment] 2022-06-06 09:58
Hi @timsneath, Thanks for filing the issue. Running a flutter web app fully offline with canvaskit is currently not supported. Because canvaskit in offline mode still tries to fetch the fallback fonts from google fonts (fonts.google.com), However HTML renderer should work fine `flutter run -d chrome --web-renderer html`.

The fully offline support for canvaskit is being tracked here #60069. Closing as the duplicate of the linked issue. In case you disagree feel free to write in the comments and we will reopen it.


Thank you.


cc: @yjbanov

**Closed by maheshmnj** 2022-06-06 09:58 UTC
Labels: in triage

**Comment by bunopus** [comment] 2022-06-06 10:23
Steps to reproduce:
1. Run `flutter create test_web`
2. `cd test_web`
3. `flutter run`
4. Turn internet off (disable wifi for example)
5. Open _http://localhost:64731/#/_
6. See `GET https://unpkg.com/canvaskit-wasm@0.33.0/bin/canvaskit.js net::ERR_INTERNET_DISCONNECTED` error in console
So the main question is: why not to put _canvaskit.js_ right next to the other local files when debugging?
