### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: Read-only file system, errno = 30

### ISSUE THREAD

**Issue by ALI-tech-tech** [flutter/flutter#147237] opened 2024-04-23 13:48 UTC
## Command
```
flutter run --machine --start-paused -d linux --devtools-server-address http://127.0.0.1:9100/ --target /media/ali/New Volume/flutterlinux/desktop/testdesktop/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: Read-only file system, errno = 30
```
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
<asynchronous suspension>
#4      _File.writeAsBytes.<anonymous closure> (dart:io/file_impl.dart:634:34)
<asynchronous suspension>
#5      ForwardingFile.writeAsString (package:file/src/forwarding/forwarding_file.dart:136:12)
<asynchronous suspension>
#6      ErrorHandlingFile.writeAsString.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:246:24)
<asynchronous suspension>
#7      _run (package:flutter_tools/src/base/error_handling_io.dart:556:12)
<asynchronous suspension>
#8      _renderTemplateToFile (package:flutter_tools/src/flutter_plugins.dart:38:3)
<asynchronous suspension>
#9      _writeWebPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:985:3)
<asynchronous suspension>
#10     injectBuildTimePluginFiles (package:flutter_tools/src/flutter_plugins.dart:1157:5)
<asynchronous suspension>
#11     WebProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:919:5)
<asynchronous suspension>
#12     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:386:7)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1743:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.19.3, on Ubuntu 22.04.4 LTS 5.15.0-1061-realtime, locale en_US.UTF-8)
    • Flutter version 3.19.3 on channel stable at /home/ali/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (7 weeks ago), 2024-03-07 15:22:21 -

**Comment by danagbemava-nc** [comment] 2024-04-23 13:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/125775

**Closed by danagbemava-nc** 2024-04-23 13:59 UTC
Labels: in triage
