### ISSUE TITLE
[Impeller] When the stroke width is equal to the diameter of the circle, the result of the drawn arc is incorrect

### ISSUE THREAD

**Issue by ColdPaleLight** [flutter/flutter#133032] opened 2023-08-22 08:14 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

run the sample code on master channel

### Expected results

The center point of the arc is displayed correctly

### Actual results

The center point of the arc is displayed incorrectly

### Code sample

<details><summary>Code sample</summary>

```dart

import 'dart:math';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorSchemeSeed: Colors.deepPurple,
        useMaterial3: true,
      ),
      home: const MyWidget(),
    );
  }
}

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget>
    with SingleTickerProviderStateMixin {
  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    // controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomPaint(
        size: Size(MediaQuery.of(context).size.width,
            MediaQuery.of(context).size.width),
        painter: MyPaint(),
      ),
    );
  }
}

class MyPaint extends CustomPainter {

  @override
  void paint(Canvas canvas, Size size) {
    final center = Offset(size.width / 2, size.height / 2);

    var paint = Paint()
      ..color = Colors.orangeAccent
      ..style = PaintingStyle.stroke;
    paint.strokeWidth = 1;
    canvas.drawRect(Rect.fromCenter(center: center, width: 200, height: 200), paint);
    paint.strokeWidth = 200;
    paint.color = Colors.blue;
    canvas.drawArc(Rect.fromCenter(center: center, width: 200, height: 200), 0, 1.5,  false, paint);
  }

  @override
  bool shouldRepaint(MyPaint oldDelegate) => false;
}


```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

| expected | actual |
| -- | -- |
| <img src="https://github.com/flutter/flutter/assets/31977171/075eba51-d522-4eef-aa55-272f71de0f78" /> | <img src="https://github.com/flutter/flutter/assets/31977171/6f518365-2886-480c-bfb6-08b64f5b0288" /> |

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel main, 3.14.0-9.0.pre.26, on macOS 13.3.1 22E261 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.14.0-9.0.pre.26 on channel main at /Users/bytedance/Develop/upstream/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 5b20988483 (3 hours ago), 2023-08-22 01:26:25 -0400
    • Engine revision 454e0e35f8
    • Dart version 3.2.0 (build 3.2.0-94.0.dev)
    • DevTools version 2.26.1
    • Pub download mirror https://dart-pub.byted.org

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/bytedance/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/bytedance/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone SE (2nd generation) (mobile) • 00008030-0018042E2E46802E • ios            • iOS 15.0 19A346
    • macOS (desktop)                     • macos                     • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)                        • chrome                    • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-08-22 10:03
Reproducible using the code sample provided above. 

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
    • Flutter version 3.13.0 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (6 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.8660.129

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9225.16/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.8660.185/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 16.6 20G75
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.14.0-9.0.pre.26, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
    • Flutter version 3.14.0-9.0.pre.26 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5b20988483 (5 hours ago), 2023-08-22 01:26:25 -0400
    • Engine revision 454e0e35f8
    • Dart version 3.2.0 (build 3.2.0-94.0.dev)
    • DevTools version 2.26.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.4)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9225.16/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.8660.185/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 16.6 20G75
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 116.0.5845.96
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by chinmaygarde** [comment] 2023-08-22 20:51
@chunhtai Are you working on this? Just noticed this skipped prioritization.

**Comment by chunhtai** [comment] 2023-08-22 20:59
yes, I am working on this one

**Comment by chunhtai** [comment] 2023-08-24 16:58
some update. still reading through code. It looks like the arc added into the Impeller::Path has expected value. The cubic components have correct points and the stroke width. At least the canvas GetCurrentPass().AddEntity for the path is still correct, I think.

I am currently trying to find where these entities are actually converting to pixels.

**Comment by chinmaygarde** [comment] 2023-08-25 18:10
For that, it may be easiest to setup a GPU frame capture ([documented here](https://github.com/flutter/engine/tree/main/impeller#documentation-references-and-additional-reading)). In the frame capture, look for the render pipeline being used. That pipeline should give you all the information about shaders and fix function elements. If you are looking to see how the piplines are setup in code, check which `impeller::Contents` subclass uses that pipeline and break there.

Hope that helps.

**Comment by chunhtai** [comment] 2023-08-29 18:06
some more update, it seems like the nearly the end when it fill out the stroke path line by line, few lines will start slightly to the left, which create that small gap.

In theory all of the lines should start at center (200, 200) and draw a length of 200 to the other side of stroke, but the last few lines starts at (194.9, 200.5).

I will keep investigate where these small error come from

**Comment by chunhtai** [comment] 2023-08-29 20:53
I think I found the root cause
https://github.com/flutter/engine/blob/1feb9302050c5a6f7e822433915d7159365ad65c/impeller/entity/geometry/stroke_path_geometry.cc#L316C7-L316C7
This line eagerly draw ahead to the next point with previous point offset, which causes the next point to draw slightly outside of the stroke line. I think this is probably needed  to make sure we fill all the spaces in the case of sharp turn. Will try to put up a pr to fix it

**Comment by bdero** [comment] 2023-09-05 20:08
I haven't looked very closely at this, but it looks to me like we're not ending butt caps with the correct normal. I landed a patch some time ago to track cap normals as part of the contour, but something may still be going amiss.

Another possibility is that the polyline we're generating is far less precise than Skia, but eyeballing the screenshot it looks plenty detailed. So I'd put my money on a problem with the normals.

**Comment by chunhtai** [comment] 2023-09-27 21:58
revert https://github.com/flutter/engine/pull/46334

**Comment by chunhtai** [comment] 2023-10-24 21:01
fixed by https://github.com/flutter/engine/pull/46203

**Closed by chunhtai** 2023-10-24 21:01 UTC
Labels: engine, c: rendering, has reproducible steps, P1, e: impeller, team-engine, triaged-engine, found in release: 3.13, found in release: 3.14
