### ISSUE TITLE
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: '_playLocal'

### ISSUE THREAD

**Issue by wangwanchao** [flutter/flutter#29232] opened 2019-03-12 16:35 UTC
1. Internal compiler error message during Flutter run:
2. other sdks: 
```
  dio: 0.1.8
  flutter_swiper : 1.1.2
  image_picker: 0.5.0+3
  cupertino_icons: ^0.1.2

  path_provider: ^0.4.1
  video_player: ^0.7.2
  audioplayer: 0.5.2
  audio_recorder: 0.0.6
  chewie: ^0.9.6
  http: 0.12.0+1
```
3. dart --version shows: Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "windows_x64"

## Logs
error
```
Compiler message:
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: '_playLocal'.
_playLocal
^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter '_playLocal' isn't defined for the class 'StandardMethodCodec'.
 - 'StandardMethodCodec' is from 'package:flutter/src/services/message_codecs.dart' ('file:///D:/flutter/packages/flutter/lib/src/services/message_codecs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '_playLocal'.
_playLocal
^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'localFilePath'.
localFilePath
^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'localFilePath' isn't defined for the class 'StandardMethodCodec'.
 - 'StandardMethodCodec' is from 'package:flutter/src/services/message_codecs.dart' ('file:///D:/flutter/packages/flutter/lib/src/services/message_codecs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'localFilePath'.
localFilePath
^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'localFilePath'.
localFilePath
^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'localFilePath' isn't defined for the class 'StandardMethodCodec'.
 - 'StandardMethodCodec' is from 'package:flutter/src/services/message_codecs.dart' ('file:///D:/flutter/packages/flutter/lib/src/services/message_codecs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'localFilePath'.
localFilePath
^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Can't find ']' to match '['.
[
^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Can't find ']' to match '['.
[
^
org-dartlang-debug:synthetic_debug_expression:1:18: Error: Expected '(' after this.
const EdgeInsets.all
                 ^^^
org-dartlang-debug:synthetic_debug_expression:1:7: Error: Method not found: 'EdgeInsets.all'.
const EdgeInsets.all
      ^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Can't find ']' to match '['.
[
^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Can't find ']' to match '['.
[
^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: '_loadFile'.
_loadFile
^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter '_loadFile' isn't defined for the class 'StandardMethodCodec'.
 - 'StandardMethodCodec' is from 'package:flutter/src/services/message_codecs.dart' ('file:///D:/flutter/packages/flutter/lib/src/services/message_codecs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '_loadFile'.
_loadFile
^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: '_playLocal'.
_playLocal
^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter '_playLocal' isn't defined for the class 'StandardMethodCodec'.
 - 'StandardMethodCodec' is from 'package:flutter/src/services/message_codecs.dart' ('file:///D:/flutter/packages/flutter/lib/src/services/message_codecs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '_playLocal'.
_playLocal
^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'localFilePath'.
localFilePath
^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'localFilePath' isn't defined for the class 'StandardMethodCodec'.
 - 'StandardMethodCodec' is from 'package:flutter/src/services/message_codecs.dart' ('file:///D:/flutter/packages/flutter/lib/src/services/message_codecs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'localFilePath'.
localFilePath
^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'localFilePath'.
localFilePath
^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'localFilePath' isn't defined for the class 'StandardMethodCodec'.
 - 'StandardMethodCodec' is from 'package:flutter/src/services/message_codecs.dart' ('file:///D:/flutter/packages/flutter/lib/src/services/message_codecs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'localFilePath'.
localFilePath
^^^^^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Can't find ']' to match '['.
[
^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: 'isPlaying'.
isPlaying
^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter 'isPlaying' isn't defined for the class 'StandardMethodCodec'.
 - 'StandardMethodCodec' is from 'package:flutter/src/services/message_codecs.dart' ('file:///D:/flutter/packages/flutter/lib/src/services/message_codecs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isPlaying'.
isPlaying
^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Can't find ']' to match '['.
[
^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: Getter not found: '_loadFile'.
_loadFile
^^^^^^^^^
org-dartlang-debug:synthetic_debug_expression:1:1: Error: The getter '_loadFile' isn't defined for the class 'StandardMethodCodec'.
 - 'StandardMethodCodec' is from 'package:flutter/src/services/message_codecs.dart' ('file:///D:/flutter/packages/flutter/lib/src/services/message_codecs.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '_loadFile'.
_loadFile
^^^^^^^^^
Compiler failed on D:\AndroidProjects\soho\soho\lib\main.dart
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Finished with error: Gradle task assembleDebug failed with exit code 1
```

```
```
flutter doctor -v shows:
```
D:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale zh-CN)
    • Flutter version 1.2.1 at D:\flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:/Android/sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    X Android license status unknown.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at D:\JetBrains\IDEA2018
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
Process finished with exit code 0
```

**Comment by wangwanchao** [comment] 2019-03-13 18:14
when i excute Tools -> Flutter -> flutter clean, it works!

**Comment by jetaggart** [comment] 2019-03-14 00:27
Currently, I get this daily. I'm not sure what triggers it, but I'll be coding for a while, and eventually a restart with throw errors of this exact sort. If I clean, it will work for a while, but eventually it comes back. 

I don't know how to reproduce this, as it seems fairly random. I mostly use an iOS device, and have not experienced this on an android device (only thing I can think of that's non-standard in my workflow). If there's something I can do or information to provide to give to shed some light on this issue, let me know.

**Comment by wangwanchao** [comment] 2019-03-14 12:37
> Currently, I get this multiple times daily. It seems like it started after I moved to 1.2, and persists on stable or dev channel. I'm not sure what triggers it, but I'll be coding for a while, and eventually a restart with throw errors of this exact sort. If I clean, it will work for a while, but eventually it comes back.
> 
> I don't know how to reproduce this, as it seems fairly random. I mostly use an iOS device and have not experienced this on an android device yet (only thing I can think of that's non-standard in my workflow). If there's something I can do or information to provide to give to shed some light on this issue, let me know.
> 
> ```
> ± |master {6} ✓| → flutter doctor -v
> [✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
>     • Flutter version 1.2.1 at /Users/jetaggart/code/flutter
>     • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
>     • Engine revision 3757390fa4
>     • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/jetaggart/Library/Android/sdk/
>     • Android NDK at /Users/jetaggart/Library/Android/sdk/ndk-bundle
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /Users/jetaggart/Library/Android/sdk/
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
>     • All Android licenses accepted.
> 
> [✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 10.1, Build version 10B61
>     • ios-deploy 1.9.4
>     • CocoaPods version 1.5.0
> 
> [✓] Android Studio (version 3.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 24.2.1
>     • Dart plugin version 173.4700
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
>     • IntelliJ at /Applications/IntelliJ IDEA.app
>     • Flutter plugin version 33.3.2
>     • Dart plugin version 183.5912.23
> 
> [✓] Connected device (1 available)
>     • iPhone • b5ffaf39edec9d736e483dca117bb44c0c1ed6d8 • ios • iOS 12.1.4
> 
> • No issues found!
> ```

I have the same problem with you，but I dont know what caused it. if I have a better way, I will reply under this issue.

**Comment by brianegan** [comment] 2019-03-14 15:26
Same problem here, log in IntelliJ and app won't compile until I clean. Happens during hot reload, app crashes, and need to clean before I can redeploy.

```
16:23:49.374 7 info flutter.tools org-dartlang-debug:synthetic_debug_expression:1:7: Error: Expected '(' after this.
```

### Doctor

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/phillywiggins/lab/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/phillywiggins/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/phillywiggins/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5912.23

[✓] IntelliJ IDEA Community Edition (version 2018.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.4129.13

[!] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android P (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by jetaggart** [comment] 2019-03-15 17:49
Are any of you using `built_value`?

**Comment by wangwanchao** [comment] 2019-03-17 02:51
> Are any of you using `built_value`?

what do you mean?pubspec.yaml or build.gradle?

**Comment by mraleph** [comment] 2019-03-17 18:31
It seems that expression evaluation specific incremental compiler state is leaking into standalone compilations. This should not be possible. 

Are we by any chance allowing "evaluate expression" requests to be serialized into dill file that is later used to bootstrap the compiler state? 

Alex & Jens, can you take a look at this? Seems like sever developer experience regression. (Potentially connected to the work that Jens did to surface compilation errors from the dependencies). 

/cc @aam @jensjoha

**Comment by aam** [comment] 2019-03-18 02:54
@wangwanchao are you still able to reproduce this in flutter master channel?

Hopefully this is duplicate of https://github.com/dart-lang/sdk/issues/36091 and has been fixed https://github.com/flutter/flutter/commit/a29906d5f552f2984daf9bef569b7fe1295e1c70

**Comment by wangwanchao** [comment] 2019-03-20 03:00
> @wangwanchao are you still able to reproduce this in flutter master channel?
> 
> Hopefully this is duplicate of [dart-lang/sdk#36091](https://github.com/dart-lang/sdk/issues/36091) and has been fixed [a29906d](https://github.com/flutter/flutter/commit/a29906d5f552f2984daf9bef569b7fe1295e1c70)

I dont know what causes it. When the problem occurs, i execute flutter clean, the app works normally.

**Comment by mraleph** [comment] 2019-03-20 08:55
@wangwanchao to rephrase @aam's question: if you upgrade to the `master` channel - do you still see this occasionally happening or does it disappear?

**Comment by brianegan** [comment] 2019-03-20 20:08
I'd like to report that I think this is solved from my end. Worked with master for the most part today and I couldn't reproduce the issue, where it was happening quite frequently before.

In addition, Hot Reload is only taking like ~150ms now, instead of 450. It was good before, but this is amazing!

**Comment by jonahwilliams** [comment] 2019-03-20 20:12
> In addition, Hot Reload is only taking like ~150ms now, instead of 450. It was good before, but this is amazing!

Good to hear that this is working well outside of my own devices (https://github.com/flutter/flutter/pull/28152)

**Comment by wangwanchao** [comment] 2019-03-21 06:28
> @wangwanchao to rephrase @aam's question: if you upgrade to the `master` channel - do you still see this occasionally happening or does it disappear?

en, I have moved to a new project, and replaced some sdks version. now it works well. if i have the same problem, i will remark under this issue.

**Comment by mraleph** [comment] 2019-03-21 06:54
Then we treat this as fixed by @aam for now. Let us know if you see it again.

**Closed by mraleph** 2019-03-21 06:54 UTC
Labels: dependency: dart, severe: crash, tool

**Comment by jonahwilliams** [comment] 2019-04-12 00:27
I've still got some reports of users finding the org-dartlang-debug errors on newer builds, see https://github.com/flutter/flutter/issues/30802#issuecomment-482387277
