### ISSUE TITLE
image_picker plugin : why is taking a photo changing the app lifecycle to paused?

### ISSUE THREAD

**Issue by ecl66** [flutter/flutter#29408] opened 2019-03-15 04:57 UTC
## Steps to Reproduce

1. Add image_picker plugin and  do "await ImagePicker.pickImage(source: ImageSource.camera, maxHeight: 450, maxWidth: 650);3
2. App enters in lifecycle inactive/paused mode
3. Upon return from await, app comes back in active mode

This is a serious issue for me as this specific app performs a number of operations before entering in paused mode and while coming back to active mode. Therefore, just taking a photo results in a very long UX lag.

## Logs

```
```

```
```

```
```

**Comment by rostopira** [comment] 2019-03-15 19:24
You haven't mentioned exactly, what platform you are talking about, but I suppose it's android
That's actually the nature of android intents
To take picture with camera you have 2 ways: 
1. Ask another app to take it for you via `Intent` (exactly, what this plugin does here: https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java)
This approach doesn't require you to deal with camera api, permission and let's user to choose his favorite camera app.
But you app is paused until camera app returns you photo.
2. Ask user for permission to use camera, use `camera` plugin, make custom UI for camera etc.
In this case, you have much more work to do, but your app isn't paused

This is a completely intended behavior.

However, you I would recommend considering moving any intensive work in separate isolate or even native code (Java thread)

**Comment by ecl66** [comment] 2019-03-17 12:48
Hi Dima,

Thanks a lot for such a swift reply.
Indeed, I checked out the code and this plugin works using Intent, hence this behavior, that happens both in iOS and Android platforms (we are obviously using Flutter to develop a  rather complex multi-platforms app in this instance).

As a matter a fact, on Android (API27), the app will raise a security exception if I don’t set the relevant CAMERA permissions (contrarily to what is written in the instructions) - you may want to check that out for future releases.

I wish there could be a plugin using the second approach - in our case, pausing the app involves a lot of database activity and therefore significant delays for the app to become ready again on resuming.

Do you know any other plugin using that second approach by chance?

Cheers
Emmanuel

**Comment by emadd** [comment] 2019-12-15 07:12
I'm experiencing the same issue on iOS.  Very curious that the lifecycle would change to paused for this functionality. One would think the only reason an app would enter the paused state is if it has left the foreground, but it technically hasn't.

**Comment by TahaTesser** [comment] 2020-03-18 14:02
Hi @ecl66  @emadd 
Are you still experiencing this problem with latest stable?
If so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment] 2020-04-17 12:15
Hi @ecl66 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution

**Closed by TahaTesser** 2020-04-17 12:15 UTC
Labels: p: first party, p: image_picker, plugin, severe: performance, waiting for customer response
