### ISSUE TITLE
Bleeding Pixel Draw on iOS Safari

### ISSUE THREAD

**Issue by billyinferno** [flutter/flutter#113146] opened 2022-10-08 05:43 UTC
## Steps to Reproduce

1. Create flutter application
2. Create listview, with container, and row with color
3. Run the flutter on the web
4. Open the web on iOS safari
5. Scroll

**Expected results:**
1. No bleeding pixel on the render during scroll

**Actual results:**
1. There are 1px bleed (on top and bottom) when scroll the widget
2. It not happen it the widget is not being scrolled

**Code Sample:**
[expansion_list.zip](https://github.com/flutter/flutter/files/9738491/expansion_list.zip)

**Flutter Doctor:**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.4.0-17.2.pre, on Microsoft Windows [Version 10.0.22000.1042], locale en-SG)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.72.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Video:**

https://user-images.githubusercontent.com/20193342/194691043-4e5ef07f-90fb-45f3-8145-8e392a9d616b.mp4

Note: just realized it not being noticable on the video, below is the pixel bleed recorded from another phone:

https://user-images.githubusercontent.com/20193342/194714680-5efb33ce-624c-4002-9fb6-4902b1945a7c.mp4

**Comment by danagbemava-nc** [comment] 2022-10-10 08:27
Hi @billyinferno, I can't really see the issue you're referring to in your video. What renderer are you experiencing the issue with? Can you share a clearer video? 

Can you also upgrade to the latest version of beta to see if you're still experiencing the issue?

I run the code sample you provided but I cannot see anything strange. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 3.4.0-34.1.pre, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-34.1.pre on channel beta at /Users/nexus/dev/sdks/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71520442d4 (4 days ago), 2022-10-05 16:38:28 -0500
    • Engine revision db0cbb2145
    • Dart version 2.19.0 (build 2.19.0-255.2.beta)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Users/nexus/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Nexus (mobile)         • 00008020-001875E83A38002E            • ios            • iOS 16.0.2 20A380
    • iPhone 14 Pro (mobile) • 4302007A-B132-4B89-887A-C5993FCA3284 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

**Comment by billyinferno** [comment] 2022-10-11 00:43
Hi, I already in the latest beta version as per checking.

It's very faint in video, but easy to notice on the real world when scrolling:
![faint_line](https://user-images.githubusercontent.com/20193342/194972145-b8f76bf7-84c4-4a09-8d9a-1049f5c8c248.png)

You can see a faint line on the video that I marked, this is only happen during scroll, when you stop scroll the line is gone. It more noticeable if the background is dark, probably this is because the way I create the list due to I am unable to give height as size.infinity to Container in Row, so I am doing it by:
1. Creating a cointainer with color
2. Put Row as Child
3. Add SizedBox with width 10 (this to ensure the parent container with color showed0
4. Add Expanded with child Container with color same as background (in this case white, to override the container parent color)
5. Inside the Expanded + Container, then I can add any other widget (row, column)

Due to the parent container contain color that cover the whole screen width, and in the child there are also widget that contain color that cover the whole screen widht - SizedBox width, when scroll the parent container widget color seems like seep out 1px in top and bottom (depends on the scroll direction).

My suspect is either the way it render in the iPhone (but the way it not showed on the screen recording make me think that this is not it), but the way of iPhone screen refresh the pixel, but I might be wrong also.

**Comment by danagbemava-nc** [comment] 2022-10-11 06:32
Hi @billyinferno, thanks for the clarification. 
I believe what you're running into is an anti-aliasing issue which would make this a duplicate of https://github.com/flutter/flutter/issues/14288. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2022-10-11 06:32 UTC
Labels: in triage
