### ISSUE TITLE
[cloud_firestore] FirebaseAuth.instance.signOut() causes crash

### ISSUE THREAD

**Issue by jmnyv** [flutter/flutter#15837] opened 2018-03-22 19:21 UTC
## Steps to Reproduce

1) Switch to a new screen of type StatefulWidget using `pushReplacementNamed`.
2) In the new screen, Call `FirebaseAuth.instance.signOut()` from `initState()`
3) Result in logs below.

## Logs

```
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010e75412b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010dde8f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010e7940cc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010e668951 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x000000010e6687db +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   Runner                              0x000000010a0ef0db __51-[FLTCloudFirestorePlugin handleMethodCall:result:]_block_invoke.454 + 635
	6   Runner                              0x000000010a35cee5 __72-[FIRDocumentReference addSnapshotListenerInternalWithOptions:listener:]_bl<…>
Lost connection to device.
```

## Flutter Doctor
```
flutter doctor -v
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-SE)
    • Flutter version 0.1.5 at /Users/mikael/Library/flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/mikael/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4700

[✓] Connected devices (3 available)
    • iPhone 7 • F215FCBC-D6DE-4C2B-B1D9-E81C3CD4DC14     • ios           • iOS 11.2 (simulator)

• No issues found!
```

**Comment by blaneyneil** [comment] 2018-06-15 19:52
same here, though it only started happening recently and i can't figure out why.

Lost connection to device.
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001116f47f6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000110d66035 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011164005c _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000111763cf1 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x00000001116f031b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   Runner                              0x000000010d4e739b __51-[FLTCloudFirestorePlugin handleMethodCall:result:]_block_invoke.537 + 635
	6   Runner                              0x000000010d2556ff __72-[FIRDocumentReference addSnapshotListenerInternalWithOptions:listener:]_bl<…>


my method is this:

`  
static FirebaseAuth _auth = FirebaseAuth.instance;
Future<void> logoutUser() async{
    return _auth.signOut();
  }
`

and it's called on the page like this:

`void _logout() async {
    setState(() {_isLoading = true;});
    try {
      await _auth.logoutUser();
      setState(() {_isLoading = false;});
      Navigator.of(context).pushReplacementNamed('/splash');
    } catch(e) {
      print(e);
    }
  }`

**Comment by zoechi** [comment] 2018-06-18 09:55
@Hixie

**Comment by blaneyneil** [comment] 2018-06-26 19:57
i narrowed it down, at least in my use case, as being a result of using a streambuilder (anywhere in the app) with a DocumentSnapshot rather than a QuerySnapshot.

my sample logout call is this:

```
FirebaseAuth.instance.logoutUser().then((_){
      print('success logging out');
    }).catchError((e) {
      print('failure logging out');
      print(e);
    });
```

which executes successfully and then crashes:

```
flutter: success logging out
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011329a7f6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001123be035 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001131e605c _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000113309cf1 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x000000011329631b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   Runner                              0x000000010eb3e8bb __51-[FLTCloudFirestorePlugin handleMethodCall:result:]_block_invoke.537 + 635
Lost connection to device.
	6   Runner                              0x000000010e8acc1f __72-[FIRDocumentReference addSnapshotListenerInternalWithOptions:listener:]_bl<…>

```

i traced it back to a StatelessWidget i use that returns a StreamBuilder.  when i make the stream a QuerySnapshot then everything is fine:

```
stream: dbProfiles.where('lastname', isEqualTo: 'Blaney').snapshots(),
builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
```

but if i use a DocumentSnapshot (anywhere in the app):

```
stream: dbProfiles.document(profileID).snapshots(),
builder: (BuildContext context, AsyncSnapshot<DocumentSnapshot> snapshot) {

```
then it results in the crash above.

**Comment by zoechi** [comment] 2018-06-26 20:09
@blaneyneil did you check you have the latest version of all plugins you are using?

**Comment by zoechi** [comment] 2018-06-28 14:31
Voting for issues using "Add reaction" on the initial comment is a good idea to rise priority.

**Comment by felixlucien** [comment] 2018-07-10 05:58
Has this been resolved yet?

**Comment by mwesolek** [comment] 2018-08-11 20:09
Same issue here!

**Comment by ashtonthomas** [comment] 2018-09-05 14:03
This seems to be related to Firestore's `security-rules`. 

I can remove the issue with the following security rule to open up everything to reads, writes:

```
match /{document=**} {
  allow read, write: if true;
}
```

I have also narrowed my issue down to a `document()` call on `DocumentReference.document(path).snapshot()` stream/listener. 

I did not try a where query as this would probably violate my security-rule.

So it seems that a stream listener is not being canceled before the auth is terminated ( I cancel subscriptions in `dispose()`).  I am unsure how to cancel these subscriptions prior to the logout in any reasonable way (the log out can happen in a different part of the app)

**Comment by adamkoch** [comment] 2018-09-06 02:06
I've been running into the exact same crash on signOut() as well (I also have a Stream set up to monitor a snapshot), but I can also repro this now when simply accessing a non-existent path in the db (where `somedoc` does not exist):
```
DocumentReference docReference = Firestore.instance.document('somecollection/somedoc);
Stream<DocumentSnapshot> snapshots = docReference.snapshots();
// Causes entire app to exit with same crash as in original report
```

Playing around with the plugin source here:
https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/ios/Classes/CloudFirestorePlugin.m#L415

It seems that in certain cases `snapshot` is `nil` (eg. immediately after signOut, if the path does not exist, or if the security rules are not allowed).

I also noticed that the Objective-C samples in the Firebase docs always check if `snapshot` is `nil`:
https://firebase.google.com/docs/firestore/query-data/listen
```
[[[self.db collectionWithPath:@"cities"] documentWithPath:@"SF"]
    addSnapshotListener:^(FIRDocumentSnapshot *snapshot, NSError *error) {
      if (snapshot == nil) {
        NSLog(@"Error fetching document: %@", error);
        return;
      }
      NSLog(@"Current data: %@", snapshot.data);
    }];
```

Adding a check for for `snapshot` being `nil` here and returning out prevents the app from crashing.

I think the fix for this should be fairly trivial but I have zero Objective-C experience so am not sure how to return this error back through the Flutter plugin. If anyone else cc'd on this bug does know then please comment back and we can try and get this fixed.

**Comment by felixlucien** [comment] 2018-10-02 11:18
**Thought I would let everyone know that this issue is likely caused by a null in a document path** such as "users/$userUid". In this case, after a logout, the userUid will become null and Firestore will be listening to an invalid path, triggering a crash. I solved this issue by canceling stream subscriptions before logging out ie. `userStream.cancel();` Then calling `FirebaseAuth.instance.signOut();`. The team working on the Firestore flutter plugin should also add something to ensure an invalid path won't cause a crash. Maybe someone could submit a pull request?

**Comment by JSANL** [comment] 2018-10-15 15:04
Is there a way to raise awareness of this issue again?
Especially with a Bloc(-Provider) - a stateless widget - in the "top-level" of my application this is difficult and I guess time consuming to fix.

**Comment by collinjackson** [comment] 2019-02-21 18:59
Did flutter/plugins#1203 mitigate this issue? I can create a PR for mwesolek's suggestion as well.

**Comment by adamkoch** [comment] 2019-02-22 05:29
I haven't tested yet, but I think that should help, in my case I was seeing `snapshot` was set to `nil` yet the plugin was still trying to continue on (causing crashes when `snapshot` members were accessed -- even before it could return the empty snapshot).

Looking at the `CloudFirestorePlugin.m`, I think another PR might have actually fixed the crash I was seeing: https://github.com/flutter/plugins/pull/773

As a side note though (I mentioned this above), the Firebase [docs](https://firebase.google.com/docs/firestore/query-data/listen) always do a check for `snapshot == nil` (instead of checking `error`) which seems like it would have prevented these issues from the get go had the same been used. Worth switching over to it now?

**Comment by collinjackson** [comment] 2019-03-14 17:23
@adamkoch I don't see any downside to adding a nil check so I'll do that.

**Closed** 2019-03-14 21:09 UTC
Labels: p: firebase, p: firebase_auth, p: first party, plugin, severe: crash

**Comment by kroikie** [comment] 2019-10-13 19:16
@jmnyv

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/878. Any further collaboration will be done there.
