### ISSUE TITLE
Request install packages permission after uploading to playstore

### ISSUE THREAD

**Issue by ainetworkglobal** [flutter/flutter#113478] opened 2022-10-15 08:40 UTC
After uploading my app to play store the above error has raised.
Search results in Merging decision tree log shows the following log

ADDED from [:image_picker_android] /Users/......../build/image_picker_android/intermediates/merged_manifest/debug/AndroidManifest.xml:16:17-67
uses-permission#android.permission.REQUEST_INSTALL_PACKAGES

please help me to resolve the issue.

thanks in advance

**Comment by abinvs-2019** [comment] 2022-10-15 08:51
I think this issue is with the android permissions. [https://support.google.com/googleplay/android-developer/answer/12085295?hl=en](url), this might help.

**Comment by ainetworkglobal** [comment] 2022-10-15 09:03
> I think this issue is with the android permissions. [https://support.google.com/googleplay/android-developer/answer/12085295?hl=en](url), this might help.

i didn't add this permission request while building app..if image_picker works fine even with this permission removed then ill remove the permission. thankyou

**Comment by stuartmorgan** [comment] 2022-10-15 11:44
Duplicate of https://github.com/flutter/flutter/issues/111947

Please refer to my comment there about how to read the merge log you've excerpted from.

**Closed by stuartmorgan** 2022-10-15 11:44 UTC
