### ISSUE TITLE
Flutter web , remove # from URLs

### ISSUE THREAD

**Issue by gagsy** [flutter/flutter#49031] opened 2020-01-17 09:41 UTC
I an using flutter to create a website 
But I want to remove # from URLs

Also, # in URLs is not good for SEO

Kindly please anyone who can resolve this issue?

**Comment by iapicca** [comment] 2020-01-17 09:54
Closing of duplicate of your own [issue](https://github.com/flutter/flutter/issues/49026)

**Closed by iapicca** 2020-01-17 09:54 UTC
