### ISSUE TITLE
Scrolling in NestedScrollView sometimes gets stuck when using expandedHeigh 

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#128526] opened 2023-06-08 19:29 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. scroll down first
2. scroll up & down fast

Disclaimer: It's a little time-consuming to reproduce the bug since this is a very minimal code, thus very light on the performance. In my app, it was not heavy either but a little heavier with other stuff and the bug was very annoying happening every time I used the app (not every scroll either but a lot more often)

### Expected results

the scroll should be smooth without jumping to a weird position

### Actual results

Sometimes it jumps to a expandedHeight scrollOffset instead of continuing scrolling.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(TodayApp());
}

class TodayApp extends StatelessWidget {
  TodayApp({super.key});
  double expandedAppBarHeight = 360;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NestedScrollView(
          controller: ScrollController(initialScrollOffset: expandedAppBarHeight - kToolbarHeight),
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverOverlapAbsorber(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: SliverAppBar(
                  pinned: true,
                  expandedHeight: expandedAppBarHeight,
                  flexibleSpace: Container(
                    height: 100,
                    color: Colors.orange,
                  ),
                ),
              ),
            ];
          },
          body: ListView(
              children: List.generate(
                  500,
                  (index) => ListTile(
                        title: Text('Index: $index'),
                      ))),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/25743901/1ddb1e25-1079-4c8f-81ff-087757342d60

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-arm64, locale en-MX)
    • Flutter version 3.7.8 on channel stable at /Users/tomas/code/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 90c64ed42b (3 months ago), 2023-03-21 11:27:08 -0500
    • Engine revision 9aa7816315
    • Dart version 2.19.5
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (4 available)
    • iPhone (mobile)            • 00008020-000415840E50003A            • ios            • iOS 16.3.1 20D67
    • iPhone 14 Pro Max (mobile) • 5B588A40-8346-4AF6-8CD8-3A54F9EC8C0A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2
      (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 114.0.5735.106

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment] 2023-06-09 06:08
This is likely duplicate of the one you linked above, so let's follow-up in it for further updates.
Closing as such. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-06-09 06:08 UTC
Labels: in triage
