### ISSUE TITLE
video_player plugin: Unhandled Exception on windows desktop

### ISSUE THREAD

**Issue by tinywolf3** [flutter/flutter#75324] opened 2021-02-03 12:08 UTC
## Steps to Reproduce

1. android studio 4.1.2 + flutter channel dev + flutter config --enable-windows-desktop
2. video_player: ^1.0.1 OR video_player: 2.0.0-nullsafety.7
3. assets/coffee.mp4 OR assets/background.avi
4. run main.dart for windows(desktop)
4. VideoPlayerApi.create : Unhandled Exception: PlatformException channel-error

**Expected results:** 
How to play a video file on windows desktop?

**Actual results:** 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:178:7)
<asynchronous suspension>
#1      MethodChannelVideoPlayer.create (package:video_player_platform_interface/method_channel_video_player.dart:46:31)
<asynchronous suspension>
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:292:19)
<asynchronous suspension>
#3      _BackgroundVideoState.initState.<anonymous closure> (package:flutter_app/main.dart)
<asynchronous suspension>
```

**flutter analyze**
```
Analyzing flutter_app...
No issues found! (ran in 1.2s)
```

**flutter doctor -v**
```
[√] Flutter (Channel dev, 1.26.0-17.1.pre, on Microsoft Windows [Version 10.0.19042.746], locale ko-KR)
    • Flutter version 1.26.0-17.1.pre at D:\DevTool\flutter_windows_1.22.6-stable
    • Framework revision c40e5294dd (5 days ago), 2021-01-29 08:44:18 -0800
    • Engine revision 5d3477eab4
    • Dart version 2.12.0 (build 2.12.0-259.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\DevTool\Android\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = D:\DevTool\Android\SDK
    • Java binary at: D:\DevTool\Android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\DevTool\Android\Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.746]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.56

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-02-03 15:08
Hi @tinywolf3 
`video_player` doesn't windows support yet  https://github.com/flutter/flutter/issues/37673
Closing as duplicate of https://github.com/flutter/flutter/issues/37673
 If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-03 15:08 UTC
