### ISSUE TITLE
App Gets crashed when we open the map screen

### ISSUE THREAD

**Issue by ankitgadatc** [flutter/flutter#131665] opened 2023-08-01 13:15 UTC
### Is there an existing issue for this?

- [ ] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [ ] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Expected results

Open the Google Map

### Actual results

Gets Crashed

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class GoogleMapScreen extends StatefulWidget {
  const GoogleMapScreen({Key? key}) : super(key: key);

  @override
  State<GoogleMapScreen> createState() => _GoogleMapScreenState();
}

class _GoogleMapScreenState extends State<GoogleMapScreen> {

  final Completer<GoogleMapController> _controller =
  Completer<GoogleMapController>();

  static const CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  static const CameraPosition _kLake = CameraPosition(
    bearing: 192.8334901395799,
    target: LatLng(37.43296265331129, -122.08832357078792),
    tilt: 59.440717697143555,
    zoom: 19.151926040649414,);

  Future<void> _goToTheLake() async {
    final GoogleMapController controller = await _controller.future;
    await controller.animateCamera(CameraUpdate.newCameraPosition(_kLake));
  }

  @override
  void initState() {
    super.initState();
    init();
  }

  void init() async {
    //
  }

  @override
  void setState(fn) {
    if (mounted) super.setState(fn);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _goToTheLake,
        label: const Text('To the lake!'),
        icon: const Icon(Icons.directions_boat),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
D/MapsInitializer(21298): preferredRenderer: null
D/zzcb    (21298): preferredRenderer: null
I/zzcb    (21298): Making Creator dynamically
I/DynamiteModule(21298): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:203115000
I/DynamiteModule(21298): Selected remote version of com.google.android.gms.maps_dynamite, version >= 203115000
V/DynamiteModule(21298): Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/ziparchive(21298): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/0000023f/MapsDynamite.dm': No such file or directory
W/ziparchive(21298): Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/0000023f/MapsDynamite.dm': No such file or directory
I/Google Maps Android API(21298): Google Play services client version: 12451000
I/Google Maps Android API(21298): Google Play services package version: 232617044
I/Google Maps Android API(21298): Google Play services maps renderer version(legacy): 203115000
D/MapsInitializer(21298): loadedRenderer: LEGACY
D/zzcb    (21298): preferredRenderer: null
I/Google Maps Android API(21298): Google Play services package version: 232617044
I/Google Maps Android API(21298): Google Play services maps renderer version(legacy): 203115000
D/CompatibilityChangeReporter(21298): Compat change id reported: 210923482; UID 10467; state: ENABLED
D/CompatibilityChangeReporter(21298): Compat change id reported: 171228096; UID 10467; state: ENABLED
D/TrafficStats(21298): tagSocket(171) with statsTag=0x30001101, statsUid=-1
I/PlatformViewsController(21298): Using hybrid composition for platform view: 0
I/bb      (21298): Successfully registered with Phenotype.
I/SurfaceView@cb6741e(21298): onWindowVisibilityChanged(0) true com.google.maps.api.android.lib6.gmm6.api.as{cb6741e VFE...C.. ......ID 0,0-0,0} of ViewRootImpl@fc83b6c[MainActivity]
D/SurfaceView@cb6741e(21298): updateSurface: has no frame
D/SurfaceView@cb6741e(21298): updateSurface: has no frame
I/SurfaceView@cb6741e(21298): Changes: creating=true format=true size=true visible=true alpha=false hint=false mUseAlpha=false visible=true left=true top=true
I/BLASTBufferQueue(21298): update, w= 720 h= 1509 mName = null mNativeObject= 0xb40000708e8bf900 sc.mNativeObject= 0xb4000070670c69a0 format= 4 caller= android.view.SurfaceView.createBlastSurfaceControls:1383 android.view.SurfaceView.updateSurface:1079 android.view.SurfaceView.lambda$new$0$android-view-SurfaceView:200 android.view.SurfaceView$$ExternalSyntheticLambda5.onPreDraw:2 android.view.ViewTreeObserver.dispatchOnPreDraw:1121 android.view.ViewRootImpl.performTraversals:4442 
I/SurfaceView@cb6741e(21298): 213283870 Cur surface: Surface(name=null)/@0xe9185e2
I/SurfaceView@cb6741e(21298): pST: sr = Rect(0, 0 - 720, 1509) sw = 720 sh = 1509
I/SurfaceView@cb6741e(21298): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
D/SurfaceView@cb6741e(21298): performSurfaceTransaction UI Thread position = [0, 0, 720, 1509] surfaceSize = 720x1509
I/SurfaceView@cb6741e(21298): applyTransactionOnVriDraw: vri = ViewRootImpl@fc83b6c[MainActivity] fRS = false t = 0xb4000070a3b17700 android.view.SurfaceView.performSurfaceTransaction:959 android.view.SurfaceView.updateSurface:1105 android.view.SurfaceView.lambda$new$0$android-view-SurfaceView:200 
I/ViewRootImpl@fc83b6c[MainActivity](21298): applyTransactionOnDraw: mRemoved = false isHardwareEnabled = false t = 0xb4000070a3b17700android.view.SurfaceView.applyTransactionOnVriDraw:2048 android.view.SurfaceView.performSurfaceTransaction:959 android.view.SurfaceView.updateSurface:1105 android.view.SurfaceView.lambda$new$0$android-view-SurfaceView:200 android.view.SurfaceView$$ExternalSyntheticLambda5.onPreDraw:2 
I/SurfaceView@cb6741e(21298): updateSurface: mVisible = true mSurface.isValid() = true
I/SurfaceView@cb6741e(21298): updateSurface: mSurfaceCreated = false surfaceChanged = true visibleChanged = true
I/SurfaceView@cb6741e(21298): visibleChanged -- surfaceCreated
I/SurfaceView@cb6741e(21298): surfaceCreated 1 #8 com.google.maps.api.android.lib6.gmm6.api.as{cb6741e VFE...C.. ......ID 0,0-720,1509}
I/SurfaceView@cb6741e(21298): surfaceChanged -- format=4 w=720 h=1509
I/SurfaceView@cb6741e(21298): surfaceChanged (720,1509) 1 #8 com.google.maps.api.android.lib6.gmm6.api.as{cb6741e VFE...C.. ......ID 0,0-720,1509}
I/SurfaceView@cb6741e(21298): surfaceRedrawNeeded
V/SurfaceView@cb6741e(21298): Layout: x=0 y=0 w=720 h=1509, frame=Rect(0, 0 - 720, 1509)
V/ViewRootImpl@fc83b6c[MainActivity](21298): Surface Surface(name=null)/@0xb444c0 drawing to bitmap w=720, h=1600
I/ViewRootImpl@fc83b6c[MainActivity](21298): Drawing: package:com.lystout.customer.app, metrics=DisplayMetrics{density=1.875, width=720, height=1467, scaledDensity=1.6875, xdpi=268.941, ydpi=269.139}, compatibilityInfo={300dpi always-compat}
D/AndroidRuntime(21298): Shutting down VM
E/AndroidRuntime(21298): FATAL EXCEPTION: main
E/AndroidRuntime(21298): Process: com.lystout.customer.app, PID: 21298
E/AndroidRuntime(21298): java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
E/AndroidRuntime(21298): 	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:749)
E/AndroidRuntime(21298): 	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:94)
E/AndroidRuntime(21298): 	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:134)
E/AndroidRuntime(21298): 	at android.graphics.Canvas.drawBitmap(Canvas.java:1556)
E/AndroidRuntime(21298): 	at io.flutter.embedding.android.FlutterImageView.onDraw(FlutterImageView.java:241)
E/AndroidRuntime(21298): 	at android.view.View.draw(View.java:24406)
E/AndroidRuntime(21298): 	at android.view.View.draw(View.java:24278)
E/AndroidRuntime(21298): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
E/AndroidRuntime(21298): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
E/AndroidRuntime(21298): 	at android.view.View.draw(View.java:24276)
E/AndroidRuntime(21298): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
E/AndroidRuntime(21298): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
E/AndroidRuntime(21298): 	at android.view.View.draw(View.java:24276)
E/AndroidRuntime(21298): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
E/AndroidRuntime(21298): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
E/AndroidRuntime(21298): 	at android.view.View.draw(View.java:24276)
E/AndroidRuntime(21298): 	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
E/AndroidRuntime(21298): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
E/AndroidRuntime(21298): 	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1540)
E/AndroidRuntime(21298): 	at android.view.View.draw(View.java:24409)
E/AndroidRuntime(21298): 	at com.android.internal.policy.DecorView.draw(DecorView.java:1513)
E/AndroidRuntime(21298): 	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:5794)
E/AndroidRuntime(21298): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5695)
E/AndroidRuntime(21298): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5330)
E/AndroidRuntime(21298): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4486)
E/AndroidRuntime(21298): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
E/AndroidRuntime(21298): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
E/AndroidRuntime(21298): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
E/AndroidRuntime(21298): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
E/AndroidRuntime(21298): 	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
E/AndroidRuntime(21298): 	at android.view.Choreographer.doFrame(Choreographer.java:852)
E/AndroidRuntime(21298): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
E/AndroidRuntime(21298): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(21298): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21298): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(21298): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(21298): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(21298): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21298): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(21298): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/BLASTBufferQueue(21298): [SurfaceView[com.lystout.customer.app/com.lystout.customer.app.MainActivity]@0#2](f:0,a:0) onFrameAvailable the first frame is available
I/Process (21298): Sending signal. PID: 21298 SIG: 9
Lost connection to device.

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1992], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] Android Studio (version 2022.1)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.80.0)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
PS E:\TC\Live\grocery_app> 


```

</details>

**Comment by dam-ease** [comment] 2023-08-01 13:40
Hi @ankitgadatc. Thanks for filing this issue. I am unable to reproduce this issue on the latest `master` and `stable` channels. From the logs, are you setting `android:hardwareAccelerated` to false in your `AndroidMainfest.xml`?

**Comment by ankitgadatc** [comment] 2023-08-02 05:03
Yes, I am setting it to false.

**Comment by dam-ease** [comment] 2023-08-02 07:57
Thanks for your response. I am able to reproduce this on the latest `master` and `stable` channels with this set in `AndroidManifest.xml`. This seems to be similar to https://github.com/flutter/flutter/issues/105889. Closing this as a duplicate of the already open issue, kindly comment, upvote and follow up on that issue for updates.

**Closed by dam-ease** 2023-08-02 07:57 UTC
Labels: in triage
