### ISSUE TITLE
driver.screenshot() doesn't take any screenshots (Integration Test)

### ISSUE THREAD

**Issue by BassamxMednini** [flutter/flutter#50996] opened 2020-02-18 23:20 UTC
## Steps to Reproduce

Follow [this tutorial](https://flutter.dev/docs/cookbook/testing/integration/introduction) from the documentation and replace in *app_test.dart* this code

    test('starts at 0', () async {
      // Use the `driver.getText` method to verify the counter starts at 0.
      expect(await driver.getText(counterTextFinder), "0");
    });

with this

    test('starts at 0', () async {
      await driver.screenshot();
      expect(await driver.getText(counterTextFinder), "0");
    });

**Expected results:** 
A screenshot of my app in the root.

**Actual results:** 
Nothing happens. No message, no error, just nothing.
<details>
  <summary>Logs</summary>

```
No issues found! (ran in 4.0s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale de-DE)
    • Flutter version 1.12.13+hotfix.8 at /Users/name/Documents/flutter
    • Framework revision 0b8abb4724 (vor 7 Tagen), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/name/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 • 779D367E-A812-49DD-98CA-C48D84C12CD6 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-02-18 23:54
Hi @BassamxMednini 
The `driver.screenshot()` function is working as intended - it's returning `Future<List<int>>` - list of pixels. In your code sample you are receiving the data, but doing nothing with it.
If you want to save it as an image - you need to do it manually.
```
final List<int> pixels = await driver.screenshot();
final File file = File(path);
await file.writeAsBytes(pixels);
```
You can find example of using it in this article - https://medium.com/flutter-community/testing-flutter-ui-with-flutter-driver-c1583681e337

Closing, as this isn't an issue with Flutter,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-02-18 23:54 UTC

**Comment by fadhlimaulidri** [comment] 2021-07-28 07:57
anyone know how to implement in flutter_gherkin?
