### ISSUE TITLE
Code sample with keyboard focus prevents copy and paste only in Firefox

### ISSUE THREAD

**Issue by rekire** [flutter/flutter#137128] opened 2023-10-24 06:14 UTC
### Steps to reproduce

1. Open https://api.flutter.dev/flutter/widgets/TextFieldTapRegion-class.html
2. Make sure that the input field has still focus
3. Mark any text
4. Right click
5. The copy option is disabled

### Expected results

That I can copy the selected text

### Actual results

The copy option is grayed out as long the input field has the focus

### Code sample

Nothing

### Screenshots or Video
https://github.com/flutter/flutter/assets/4619618/7c476993-ca67-438a-bcb9-d8d0a84d57c6

**Comment by dam-ease** [comment] 2023-10-24 09:19
Hi @rekire. Thanks for filing this. I can see this behaviour in both the `stable` and `master` docs. I can only see this on Firefox.

| Chrome | Safari | Firefox | Egde | Opera |
|--------|--------|--------|--------|--------|
| ❌ | ❌ | ✅  | ❌ | ❌ | 

✅ - Reproduces issue
❌ - Doesn't Reproduce the issue

**Comment by yjbanov** [comment] 2023-11-02 18:18
This looks like a browser bug. When you select text outside the Dartpad iframe there's no Flutter at all, and the browser should let you select and copy text as usual. Something must be broken because of the nested iframes, but I'm not sure what we can do on the Flutter side to fix it.

**Comment by rekire** [comment] 2023-11-23 19:41
Their bug tracker was so buggy that I never got notifications. So I don't use it.

**Comment by yjbanov** [comment] 2024-02-22 19:24
Closing as there's nothing we can do in Flutter to fix Firefox.

**Closed by yjbanov** 2024-02-22 19:24 UTC
Labels: d: api docs, f: focus, browser: firefox, team-web
