### ISSUE TITLE
 Use the EventChannel, Throws a MissingPluginException in Flutter module

### ISSUE THREAD

**Issue by originlan** [flutter/flutter#58580] opened 2020-06-03 10:56 UTC
## Steps to Reproduce

I according to the official website (https://flutter.dev/docs/development/add-to-app/android/project-setup), the steps to generate a moduel, the use of flutter create -t module -- org com. Example my_flutter, let my native applications can interact with the flutter page, but I found not to be able to use the EventChannel, Throws a MissingPluginException

**native code:** 

```     
package com.example.livedemo;
    import android.os.Bundle;
    import android.util.Log;
    import android.view.View;
    import android.widget.Toast;
    import java.util.concurrent.TimeUnit;
    import io.flutter.embedding.android.FlutterActivity;
    import io.flutter.plugin.common.BinaryMessenger;
    import io.flutter.plugin.common.EventChannel;
    import io.flutter.plugin.common.MethodCall;
    import io.flutter.plugin.common.MethodChannel;

    public class MainActivity extends FlutterActivity {
        final String TAG = "MainActivity";
        public static final String STREAM = "liveDemo/event";

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            BinaryMessenger binaryMessenger =getFlutterEngine().getDartExecutor().getBinaryMessenger();
            getContext().startActivity(
                    FlutterActivity.createDefaultIntent(getApplicationContext())
            );

            new EventChannel(binaryMessenger, STREAM).setStreamHandler(
                    new EventChannel.StreamHandler() {

                        @Override
                        public void onListen(Object arguments, EventChannel.EventSink eventSink) {
                            eventSink.success("success ");
                        }
                        @Override
                        public void onCancel(Object arguments) {
                            Log.e("plateform_channel", "arguments: " + arguments.toString());
                        }
                    }
            );
        }
    }
```

**flutter code:**
```
 import 'package:flutter/material.dart';
        import 'package:flutter/services.dart';

        class LivePage extends StatefulWidget {
            LivePage({Key key}) : super(key: key);

            @override
            _LivePageState createState() => _LivePageState();
            }

            class _LivePageState extends State<LivePage> {
            static const EventChannel eventChannel = EventChannel("liveDemo/event");
            var timeData = "time ";

            @override
            void initState() {
                getEventChannel();
                eventChannel.receiveBroadcastStream().listen(_onEvent, onError: _onError);
                super.initState();
            }

            void _onEvent(Object event) {
                setState(() {
                timeData = '$event';
                });
            }

            void _onError(Object error) {
                setState(() {
                timeData = 'Receive  failed';
                });
            }

            @override
            Widget build(BuildContext context) {
                return Scaffold(
                appBar: AppBar(),
                body: Container();
            }
        }

```

**Actual results:** 
```
I/flutter (25032): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (25032): The following MissingPluginException was thrown while activating platform stream on channel
I/flutter (25032): liveDemo/event:
I/flutter (25032): MissingPluginException(No implementation found for method listen on channel liveDemo/event)
I/flutter (25032): 
I/flutter (25032): When the exception was thrown, this was the stack:
I/flutter (25032): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
I/flutter (25032): <asynchronous suspension>
I/flutter (25032): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
I/flutter (25032): #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:519:29)
I/flutter (25032): #3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:505:64)
I/flutter (25032): #8      _LivePageState.getEventChannel (package:liveDemoFlutter/livePage.dart:53:43)
I/flutter (25032): #9      _LivePageState.initState (package:liveDemoFlutter/livePage.dart:18:5)
I/flutter (25032): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
I/flutter (25032): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (25032): ...     Normal element mounting (115 frames)
I/flutter (25032): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (25032): #127    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
I/flutter (25032): ...     Normal element mounting (253 frames)
I/flutter (25032): #380    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (25032): #381    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (25032): #382    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
I/flutter (25032): #383    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
I/flutter (25032): #384    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
I/flutter (25032): #385    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter (25032): #386    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
I/flutter (25032): #387    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
I/flutter (25032): #388    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
I/flutter (25032): (elided 15 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

```
flutter --version
Flutter 1.17.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f21edf8b6 (6 days ago) • 2020-05-28 12:44:12 -0700
Engine • revision b851c71829
Tools • Dart 2.8.3

flutter doctor -v
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.2 at /Users/guoshun/Flutter/flutter
    • Framework revision 5f21edf8b6 (6 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/guoshun/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • IN2020 • d85a39ba • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by originlan** [comment] 2020-06-03 11:27
Does anyone else have this problem

**Comment by VladyslavBondarenko** [comment] 2020-06-03 14:03
Hi @originlan 
could you attach complete minimal reproducible project?

**Comment by originlan** [comment] 2020-06-04 06:35
So this is where I create a new project just coding channel

**Comment by jmagman** [comment] 2020-06-04 21:59
Very similar to https://github.com/flutter/flutter/issues/58160#issuecomment-639139990.

**Comment by ooooori** [comment] 2021-06-15 08:10
> Does anyone else have this problem

<img width="873" alt="企业微信截图_96afa186-c228-40f8-b53b-7f15a3407057" src="https://user-images.githubusercontent.com/84013377/122017011-2a47e080-cdf4-11eb-8aa3-1c2ea57c9e4a.png">

**Comment by stuartmorgan** [comment] 2022-08-31 18:22
Closing as a duplicate of the issue referenced above, as it looks like this is the same race.

**Closed by stuartmorgan** 2022-08-31 18:22 UTC
Labels: severe: crash, easy fix, platform-android, engine, a: existing-apps, documentation, passed first triage, P4
