### ISSUE TITLE
[tool_crash] DartDevelopmentServiceException

### ISSUE THREAD

**Issue by aidaapadilla** [flutter/flutter#116593] opened 2022-12-06 15:42 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
DartDevelopmentServiceException
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:133:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:154:12)
<asynchronous suspension>
#3      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:466:7)
<asynchronous suspension>
#4      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:241:21)
<asynchronous suspension>
#5      Dwds.debugConnection (package:dwds/dart_web_debug_service.dart:61:30)
<asynchronous suspension>
#6      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:713:15)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel beta, 3.4.0-34.1.pre, on Microsoft Windows [Versi¢n 10.0.22621.819], locale es-ES)
    [32m•[39m Flutter version 3.4.0-34.1.pre on channel beta at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 71520442d4 (9 weeks ago), 2022-10-05 16:38:28 -0500
    [32m•[39m Engine revision db0cbb2145
    [32m•[39m Dart version 2.19.0 (build 2.19.0-255.2.beta)
    [32m•[39m DevTools version 2.18.0

[31m[✗][39m Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    [32m•[39m Android SDK at C:\Users\aidap\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.

**Comment by darshankawar** [comment] 2022-12-07 05:57
Closing as duplicate of https://github.com/flutter/flutter/issues/97604

**Closed by darshankawar** 2022-12-07 05:57 UTC
Labels: in triage
