### ISSUE TITLE
abnormally  release sizes: flutter app.ipa 190MB, Runner - 427,3Mb, apk 7,2MB

### ISSUE THREAD

**Issue by R3ll36** [flutter/flutter#51579] opened 2020-02-27 17:45 UTC
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.5 18F132, locale en-IT)
    • Flutter version 1.12.13+hotfix.5 at /Users/cosminrus/Utils/flutter
    • Framework revision 27321ebbad (3 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cosminrus/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment] 2020-02-28 08:42
Hi @R3ll36 

[Measuring your app's size](https://flutter.dev/docs/perf/app-size#ios)
Please look at these comments [comment](https://github.com/flutter/flutter/issues/47101#issuecomment-567522077) [comment](https://github.com/flutter/flutter/issues/45519#issuecomment-568935022rl)

Duplicate of [#](https://github.com/flutter/flutter/issues/471017)
Closing as such 
Thank you

**Closed by TahaTesser** 2020-02-28 08:42 UTC
