### ISSUE TITLE
Auto rename of the path in Android Studio on moving a file

### ISSUE THREAD

**Issue by melwinlobo18** [flutter/flutter#69014] opened 2020-10-26 09:50 UTC
## Use case
In Android Studio when we **Move** or **Drag and Drop** a file to a different folder, the path of the referenced file changes to 
`C:\Users\user_name\Desktop\project\app\lib\main.dart`. As a result, 
- **Hot Reload** doesn't work for the code in that particular file.
- If the code is opened on a different PC it'll show an error as the path is relative to the system.

I have personally faced this issue and recently saw another user facing the same issue  #68945.

## Proposal
This used to work fine before. Not sure when it changed. So, it'd be great if the path be renamed as `package:app\lib\main.dart` instead of `C:\Users\user_name\Desktop\project\app\lib\main.dart`

**Comment by TahaTesser** [comment] 2020-10-26 10:08
Hi @melwinlobo18 
Looks like a duplicate of https://github.com/flutter/flutter-intellij/issues/4740
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-26 10:08 UTC
