### ISSUE TITLE
Cannot delete App data on MacOs

### ISSUE THREAD

**Issue by KevinCCucumber** [flutter/flutter#137566] opened 2023-10-30 19:21 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a flutter Project
2. Add SharedPreferences
3. Add some Data 
4. Delete the App from the Build Folder
5. relaunch the app
6. Data is still in the app

### Expected results

The Data should be deleted with the deletion of the build folder

### Actual results

The Apps Data is nowhere to be found. Neither in /Library/Application Support nor in /Library/Preferences

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stuartmorgan** [comment] 2023-10-30 23:26
> The Data should be deleted with the deletion of the build folder

This is not how `NSUserDefaults` works. This is not specific to Flutter, it's standard OS behavior.

Closing, as this works as intended. Feedback about how `NSUserDefaults` stores data would need to be filed with Apple.

**Closed by stuartmorgan** 2023-10-30 23:26 UTC
