### ISSUE TITLE
ExpansionPanelList example is not working with flutter 3.13, It needs correction.

### ISSUE THREAD

**Issue by atul-vashisht** [flutter/flutter#132948] opened 2023-08-21 11:29 UTC
Hello Flutter team, I am unable to expand the list item.

![image](https://github.com/flutter/flutter/assets/111724591/631ff9c1-0d26-4fb8-a216-e6f3d09c761c)

https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html
On line 67 
It should be like 
data[index].isExpanded = **isExpanded**;

instead of 
data[index].isExpanded = **!isExpanded**;

Please make changes or give me this opportunity as I found this.

**Comment by huycozy** [comment] 2023-08-21 11:54
Closing this as a duplicate of https://github.com/flutter/flutter/issues/132759. Please follow up on it for updates.

**Closed by huycozy** 2023-08-21 11:54 UTC
Labels: in triage
