### ISSUE TITLE
Flutter for Windows on ARM

### ISSUE THREAD

**Issue by justrach** [flutter/flutter#67403] opened 2020-10-06 10:03 UTC
Is there any working library for Flutter for Windows on ARM64?

Or is there any way to emulate it on the Surface Pro X, with the new 64 bit emulation that hits devices in November

**Comment by darshankawar** [comment] 2020-10-06 11:26
Closing as duplicate of [53120](https://github.com/flutter/flutter/issues/53120)

**Closed by darshankawar** 2020-10-06 11:26 UTC
