### ISSUE TITLE
[Http] ClientException. Failed to Parse HTTP. 67 does not match 13.

### ISSUE THREAD

**Issue by MuriloRS** [flutter/flutter#71555] opened 2020-12-02 11:55 UTC
## Steps to Reproduce

1. Create a new project.
2. Import the package http or dio.
3. Make a simple post http request to a rest api.

**Expected results:** 
1. I have executed the same rest api on postman and it worked.
2. I need execute a simple post http request, using the http package or dio.

**Actual results:** 
1. The error occurs ClientException. Failed to Parse HTTP. 67 does not match 13.
![Sem título](https://user-images.githubusercontent.com/18061819/100869630-0f2b0a00-347c-11eb-8d0f-7db237c7ac65.png)

The code.
![Sem título2](https://user-images.githubusercontent.com/18061819/100869687-236f0700-347c-11eb-8ee0-59b464c6b6d9.png)

Flutter doctor, I have tried resolve this issues below, but I'm managing to run the flutter except for this error

`[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [versÃ£o 10.0.19041.630], locale pt-BR)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 3.4)
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.   
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.51.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.`

**Comment by TahaTesser** [comment] 2020-12-02 12:03
Hi @MuriloRS 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/http/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-02 12:03 UTC

**Comment by MuriloRS** [comment] 2020-12-02 12:21
I have tried execute this code using the http package and the dio package, and I got the same problem.

**Comment by TahaTesser** [comment] 2020-12-02 14:20
Hi @MuriloRS 
Yes, please file an issue dart/http repository as mentioned earlier, this repository is for flutter
https://github.com/dart-lang/http/issues
Thank you
