### ISSUE TITLE
Crash in TFA when compiling application: NoSuchMethodError: The method 'getExpressionType' was called on null

### ISSUE THREAD

**Issue by damphat** [flutter/flutter#79268] opened 2021-03-29 13:32 UTC
## Steps to Reproduce

1. Run `flutter create bug`
2. Update the files as follows:

`lib/main.dart`
_Please don't change the order of declarations in the file_
```dart
// lib/main.dart
class Utils {
  static final foo = Foo(() {});
}

class Foo {
  Foo(func);
}

// No need to put `runApp()` here, but this flutter app should be compiled 
void main() {
  print(Utils.foo); // should print: Instance of 'Foo'
}

```
3. Build the app in **release** mode
```
flutter build apk --release
```

**Expected results:**
should generate a release APK file. 

**Actual results:** 
```
Unhandled exception:
NoSuchMethodError: The method 'getExpressionType' was called on null.
Receiver: null
Tried calling: getExpressionType(Instance of 'FunctionExpression')
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      Expression.getStaticType (package:kernel/ast.dart:3169:20)      
#2      _Transform.transformCall.<anonymous closure> (package:vm/transformations/type_flow/signature_shaking.dart:557:27)
#3      _Transform.forEachArgumentRev (package:vm/transformations/type_flow/signature_shaking.dart:508:10)
#4      _Transform.transformCall (package:vm/transformations/type_flow/signature_shaking.dart:553:9)
#5      _Transform.visitConstructorInvocation (package:vm/transformations/type_flow/signature_shaking.dart:650:5)
#6      ConstructorInvocation.accept (package:kernel/ast.dart:5247:44)  
```

```
$ flutter --version 

Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (11 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

$ flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (4 available)

• No issues found!
```

**Comment by iapicca** [comment] 2021-03-29 13:49
the issue occurs with the latest master
<details>
<summary>code sample</summary>

```diff
class Utils {
  static final foo = Foo(() {});
}

- class Foo {
-   Foo(func); /// <= ??????
- }

+ class Foo {
+   final void Function() func;
+   Foo(this.func);
+ }

void main() {
  print(Utils.foo);
+   runApp(MaterialApp(home: Material()));
}

```

</details>

<details>
<summary>logs</summary>

```bash
[  +77 ms] 💪 Building with sound null safety 💪
[  +24 ms] Running Gradle task 'assembleRelease'...
[   +6 ms] Using gradle from /home/francesco/projects/issue/android/gradlew.
[  +20 ms] executing: [/home/francesco/projects/issue/android/] /home/francesco/projects/issue/android/gradlew -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib/main.dart
-Pdart-obfuscation=false -Ptrack-widget-creation=true -Ptree-shake-icons=true assembleRelease
[+3212 ms] > Task :app:compileFlutterBuildRelease
[   +9 ms] [  +63 ms] executing: uname -m
[        ] [  +31 ms] Exit code 0 from: uname -m
[        ] [        ] x86_64
[   +1 ms] [   +5 ms] executing: [/home/francesco/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +6 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] a603714610f8c9c831e7d85071274460d70c18da
[        ] [   +1 ms] executing: [/home/francesco/snap/flutter/common/flutter/] git tag --points-at a603714610f8c9c831e7d85071274460d70c18da
[        ] [  +15 ms] Exit code 0 from: git tag --points-at a603714610f8c9c831e7d85071274460d70c18da
[        ] [   +1 ms] executing: [/home/francesco/snap/flutter/common/flutter/] git describe --match *.*.* --long --tags a603714610f8c9c831e7d85071274460d70c18da
[        ] [  +36 ms] Exit code 0 from: git describe --match *.*.* --long --tags a603714610f8c9c831e7d85071274460d70c18da
[        ] [        ] 2.1.0-12.0.pre-294-ga603714610
[        ] [   +6 ms] executing: [/home/francesco/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/francesco/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +62 ms] executing: [/home/francesco/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +62 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +94 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +7 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +29 ms] Initializing file store
[        ] [  +32 ms] Skipping target: gen_localizations
[        ] [   +8 ms] kernel_snapshot: Starting due to {}
[        ] [  +13 ms] /home/francesco/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/francesco/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/francesco/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false
-Ddart.vm.product=true --aot --tfa --packages /home/francesco/projects/issue/.dart_tool/package_config.json --output-dill
/home/francesco/projects/issue/.dart_tool/flutter_build/5d3e655da5182a6a0c2764c949d95cdd/app.dill --depfile
/home/francesco/projects/issue/.dart_tool/flutter_build/5d3e655da5182a6a0c2764c949d95cdd/kernel_snapshot.d package:issue/main.dart
[+11434 ms] [+12731 ms] Unhandled exception:
[   +2 ms]             NoSuchMethodError: The method 'getExpressionType' was called on null.
[        ]             Receiver: null
[        ]             Tried calling: getExpressionType(Instance of 'FunctionExpression')
[        ]             #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
[        ]             #1      Expression.getStaticType (package:kernel/ast.dart:3497:20)
[        ]             #2      _Transform.transformCall.<anonymous closure> (package:vm/transformations/type_flow/signature_shaking.dart:557:27)
[        ]             #3      _Transform.forEachArgumentRev (package:vm/transformations/type_flow/signature_shaking.dart:508:10)
[        ]             #4      _Transform.transformCall (package:vm/transformations/type_flow/signature_shaking.dart:553:9)
[        ]             #5      _Transform.visitConstructorInvocation (package:vm/transformations/type_flow/signature_shaking.dart:650:5)
[        ]             #6      ConstructorInvocation.accept (package:kernel/ast.dart:6209:44)
[        ]             #7      Field.visitChildren (package:kernel/ast.dart:1928:18)
[        ]             #8      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:981:10)
[        ]             #9      Visitor.defaultTreeNode (package:kernel/visitor.dart:774:39)
[        ]             #10     TreeVisitor.defaultMember (package:kernel/visitor.dart:287:35)
[        ]             #11     TreeVisitor.visitField (package:kernel/visitor.dart:290:31)
[        ]             #12     Field.accept (package:kernel/ast.dart:1914:40)
[        ]             #13     visitList (package:kernel/ast.dart:12998:14)
[        ]             #14     Class.visitChildren (package:kernel/ast.dart:1364:5)
[        ]             #15     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:981:10)
[        ]             #16     Visitor.defaultTreeNode (package:kernel/visitor.dart:774:39)
[        ]             #17     TreeVisitor.visitClass (package:kernel/visitor.dart:296:31)
[        ]             #18     Class.accept (package:kernel/ast.dart:1325:38)
[        ]             #19     visitList (package:kernel/ast.dart:12998:14)
[        ]             #20     Library.visitChildren (package:kernel/ast.dart:517:5)
[        ]             #21     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:981:10)
[        ]             #22     Visitor.defaultTreeNode (package:kernel/visitor.dart:774:39)
[        ]             #23     TreeVisitor.visitLibrary (package:kernel/visitor.dart:311:35)
[        ]             #24     Library.accept (package:kernel/ast.dart:506:38)
[        ]             #25     visitList (package:kernel/ast.dart:12998:14)
[        ]             #26     Component.visitChildren (package:kernel/ast.dart:12831:5)
[        ]             #27     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:981:10)
[        ]             #28     Visitor.defaultTreeNode (package:kernel/visitor.dart:774:39)
[        ]             #29     TreeVisitor.visitComponent (package:kernel/visitor.dart:323:39)
[        ]             #30     SignatureShaker.transformComponent (package:vm/transformations/type_flow/signature_shaking.dart:77:22)
[        ]             #31     transformComponent (package:vm/transformations/type_flow/transformer.dart:101:21)
[        ]             #32     runGlobalTransformations (package:vm/kernel_front_end.dart:442:5)
[        ]             #33     compileToKernel (package:vm/kernel_front_end.dart:359:11)
[        ]             <asynchronous suspension>
[        ]             #34     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:533:17)
[        ]             <asynchronous suspension>
[        ]             #35     starter (package:flutter_frontend_server/server.dart:180:12)
[        ]             <asynchronous suspension>
[        ]             #36     main (file:///b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
[        ]             <asynchronous suspension>
[ +187 ms] [ +112 ms] Persisting file store
[        ] [   +3 ms] Done persisting file store
[        ] [   +3 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:291:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:828:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:766:32)
[        ]            <asynchronous suspension>
[        ]            #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:595:16)
[        ]            <asynchronous suspension>
[        ]            #9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:306:32)
[        ]            <asynchronous suspension>
[        ]            #10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1044:27)
[        ]            <asynchronous suspension>
[        ]            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #12     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:287:9)
[        ]            <asynchronous suspension>
[        ]            #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:238:5)
[        ]            <asynchronous suspension>
[        ]            #16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #18     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [   +5 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:323:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1044:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:287:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:238:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [  +13 ms] "flutter assemble" took 13,063ms.
[  +79 ms] [ +151 ms] ensureAnalyticsSent: 148ms
[        ] [   +3 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [   +1 ms] exiting with code 1
[  +99 ms] > Task :app:compileFlutterBuildRelease FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 1 actionable task: 1 executed
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/home/francesco/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1029
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildRelease'.
[        ] > Process 'command '/home/francesco/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 14s
[ +355 ms] Running Gradle task 'assembleRelease'... (completed in 15.5s)
[   +3 ms] "flutter apk" took 15,856ms.
[   +5 ms] Gradle task assembleRelease failed with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:464:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:231:5)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1044:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:287:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:238:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +178 ms] ensureAnalyticsSent: 176ms
[   +3 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 2.1.0-13.0.pre.294, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-13.0.pre.294 at /home/francesco/snap/flutter/common/flutter
    • Framework revision a603714610 (27 hours ago), 2021-03-28 03:54:02 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.90 snap

! Doctor found issues in 1 category.

```

</details>

**Comment by alexmarkov** [comment] 2021-03-29 15:57
@johnniwinther It looks like this is related to getStaticType implementation.

**Comment by alexmarkov** [comment] 2021-03-29 19:53
Correction: it looks like the root cause is that `StaticTypeContext` instance which is passed to `getStaticType` was not correctly initialized in `_Transform` from pkg/vm/lib/transformations/type_flow/signature_shaking.dart.

That happens because `_Transform.typeContext` is not set for field initializers: it is set in `transformMemberSignature` which is called from `visitConstructor` and `visitProcedure`, but it is not set in `visitField`.

@askeksa-google

**Comment by askeksa-google** [comment] 2021-04-09 16:28
Fixed in https://github.com/dart-lang/sdk/commit/ea50eeb4beb07d8e0a672d6fb52d356b523a6392. Should be fixed when this rolls.

**Comment by askeksa-google** [comment] 2021-04-12 12:17
Flutter engine rolled in https://github.com/flutter/engine/commit/de84bdde1fe1f2ebe78e9b185e3dc2ecd7b50c9a

**Closed by askeksa-google** 2021-04-12 12:17 UTC
Labels: dependency: dart, severe: crash
