### ISSUE TITLE
[cloud_functions] - Internal Exception invisible to the user

### ISSUE THREAD

**Issue by rishab2113** [flutter/flutter#28578] opened 2019-02-27 12:59 UTC
## Error Details

The _region variable is returned as null and causes an internal exception invisible to the user, 
```
PlatformException(-1, The operation couldn’t be completed. (com.google.GTMSessionFetcher error -1.), null).
```

## How to Reproduce

1. Setup an application and a callable cloud function
2. Try calling the function. It fails with an internal error. On further inspection, shows that the region isn't set.

## Logs

Logs don't show anything, the only errors that pop up are

```
Beginning a fetch requires a request with a URL
[  +16 ms] flutter: throwing generic exception
[   +9 ms] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Exception: Unable to call function detectIntent
...

```

**Comment by zoechi** [comment] 2019-02-27 14:32
Possible duplicate of #17677

**Comment by Asoseil** [comment] 2019-02-28 21:35
same issue with 1.2.1 stable and cloud_function 0.1.0+

**Comment by aytunch** [comment] 2019-03-01 18:03
@zoechi Günter, this is not a duplicate.
After downgrading from the current version:
cloud_functions: ^0.1.1+1
to:
cloud_functions: 0.1.0+1

we can successfully call the callable cloud function

**Comment by rishab2113** [comment] 2019-03-01 21:46
@aytunch @zoechi This issue is most likely caused by [this commit](https://github.com/flutter/plugins/pull/1210), which tried to solve [flutter/flutter#24333](https://github.com/flutter/flutter/issues/24333). 

I did some of my own debugging and found out that the internal variable [_region](https://github.com/flutter/plugins/blob/f2b1e696eb1391fa734090faaac66b46057a0d38/packages/cloud_functions/lib/cloud_functions.dart#L25) doesn't return successfully, leading to the error. Since this was introduced by [PR 1210](https://github.com/flutter/plugins/pull/1210), I believe it was the culprit, as that commit correlated with the version roll to 0.1.1; also confirmed by a [git blame](https://github.com/flutter/plugins/blame/f2b1e696eb1391fa734090faaac66b46057a0d38/packages/cloud_functions/lib/cloud_functions.dart#L25).

It can probably be fixed by a null check on the variable, reverting it to the default ```us-central1```.

**Closed** 2019-03-06 19:49 UTC
Labels: p: framework, plugin, severe: crash, waiting for PR to land (fixed)
