### ISSUE TITLE
Textfield does not lose focus when clicked outside

### ISSUE THREAD

**Issue by Kunal-Deshpande** [flutter/flutter#83666] opened 2021-05-31 15:01 UTC
Textfield does not lose focus when clicked outside the input box.
Is this implemented intentionally?
Should it not lose focus automatically?

**Comment by SirusCodes** [comment] 2021-05-31 21:27
Duplicate of https://github.com/flutter/flutter/issues/32433

**Comment by TahaTesser** [comment] 2021-06-01 09:06
closing as a duplicate of https://github.com/flutter/flutter/issues/32433

**Closed by TahaTesser** 2021-06-01 09:06 UTC
Labels: in triage
