### ISSUE TITLE
After upgrading to latest beta (1.25.0-8.1.pre), web device disappeared

### ISSUE THREAD

**Issue by postacik** [flutter/flutter#73087] opened 2020-12-29 10:07 UTC
## Steps to Reproduce

I upgraded to the latest beta (1.25.0-8.1.pre) and the web device is gone. Here is the result from "flutter devices" command:

```
2 connected devices:

Chrome (web) • chrome • web-javascript • Google Chrome 80.0.3987.132
Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.57
```

I could not find any release note that this was done deliberately.

And it is strange that the latest version of the SDK zip file is 129 MB where the previous version was 628 MB.

## Logs

<details>
<summary>Logs</summary>

```
```

```
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Version 10.0.17763.1637], locale tr-TR)
    • Flutter version 1.25.0-8.1.pre at c:\Projects\flutter
    • Framework revision 8f89f6505b (13 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\au250073\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\xxxxx\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.51.1)
    • VS Code at C:\Users\xxxxx\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.1

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 80.0.3987.132
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.57

• No issues found!
```

</details>

**Comment by postacik** [comment] 2020-12-29 10:29
After searching again in the closed issues I found that this was done deliberately.

#https://github.com/flutter/flutter/pull/71491

However I could not understand the purpose. Why did you hide web server device by default?

**Comment by TahaTesser** [comment] 2020-12-29 10:30
Hi @postacik 
This is by design. Implemented in https://github.com/flutter/flutter/pull/71491
duplicate of https://github.com/flutter/flutter/issues/72645
Since this is by design and verified by PR,  no issues here, feel free to comment on the PR 
Thank you

**Closed by TahaTesser** 2020-12-29 10:30 UTC
