### ISSUE TITLE
RenderFlex Overflow with Hero Widget

### ISSUE THREAD

**Issue by esDotDev** [flutter/flutter#90470] opened 2021-09-21 18:30 UTC
## Problem
Flutter throws a RenderFlex overflowed exception when using Hero Widget, even when nothing is actually cut off.
```
eg: A RenderFlex overflowed by 0.000335 pixels on the bottom.
```

![J6M2V9LLGt](https://user-images.githubusercontent.com/736973/134227012-22a8ed3c-671f-4c50-ad34-9593955d70ec.gif)

## Steps to Reproduce

Run the following as your main app: 

<details> 
<summary>minimal code sample</summary> 

```dart
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: HeroSpikes(),
    );
  }
}

class HeroSpikes extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: _Page1(),
    );
  }
}

class NotificationData {
  final String title;
  final String desc;
  final String id;
  NotificationData({required this.title, required this.desc, required this.id});
}

List<NotificationData> notifications = List.generate(
    5, (index) => NotificationData(title: "Notification $index", desc: "Description goes here", id: "not$index"));

class _Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    timeDilation = 10;
    double width = 300;
    double spacing = 10;
    return Scaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            Placeholder(fallbackHeight: 300),
            Placeholder(fallbackHeight: 300),
            Placeholder(fallbackHeight: 300),
            SizedBox(
              height: 100 + (notifications.length - 1) * spacing + 10,
              width: 300 + (notifications.length - 1) * spacing,
              child: Stack(
                children: List.generate(notifications.length, (index) {
                  return Positioned(
                    left: spacing * index,
                    top: spacing * index,
                    child: Opacity(
                        opacity: 1,
                        child: Container(
                            child: _NotificationCard(data: notifications[index], onTap: () => _handleCardTap(context)),
                            width: width)),
                  );
                }),
              ),
            ),
            Placeholder(fallbackHeight: 300),
            Placeholder(fallbackHeight: 300),
            Placeholder(fallbackHeight: 300),
          ],
        ),
      ),
    );
  }

  void _handleCardTap(BuildContext context) {
    Navigator.of(context).push(MaterialPageRoute(builder: (_) => _Page2()));
  }
}

class _NotificationCard extends StatelessWidget {
  final VoidCallback onTap;
  final NotificationData data;

  const _NotificationCard({Key? key, required this.onTap, required this.data}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Hero(
        tag: data.id,
        child: Card(
          color: Colors.grey,
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(data.title, style: TextStyle(fontSize: 22)),
                Text(data.desc),
                SizedBox(height: 12),
                Text("Read More >"),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: List.generate(notifications.length, (index) {
            return _NotificationCard(data: notifications[index], onTap: () => _handleCardTap(context));
          }),
        ),
      ),
    );
  }

  void _handleCardTap(BuildContext context) => Navigator.pop(context);
}
``` 
	
</details>

```console
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 2.5.1 at C:\_dev\sdks\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (4 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2
```

**Comment by TahaTesser** [comment] 2021-09-22 08:19
Hi @esDotDev 
I can reproduce on multiple channels 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/78471
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-22 08:19 UTC
Labels: in triage
