### ISSUE TITLE
SafeArea around Scaffold with BottomNavigationBar -> How to remove Bar elevation?

### ISSUE THREAD

**Issue by AlexandreRoba** [flutter/flutter#21688] opened 2018-09-11 15:11 UTC
Hi All, I'm trying the SafeArea Widget. Unfortunately the BottomNavigationBar has an Elevation that I canno't find a way to remove... I end up with something like that. 

Is there a way to remove this Elevation?
<img width="406" alt="screen shot 2018-09-11 at 17 11 17" src="https://user-images.githubusercontent.com/60746/45369251-c14d3180-b5e5-11e8-9ea9-0cb3a24a20ec.png">

Flutter Version: 0.7.3-beta

**Comment by zoechi** [comment] 2018-09-12 06:33
Please add the output of `flutter doctor -v`.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by AlexandreRoba** [comment] 2018-09-12 08:16
Hi @zoechi,

Thanks for the fast answer. Here it goes:
```bash
> $ flutter doctor -v
[✓] Flutter (Channel beta, v0.7.3, on Mac OS X 10.13.6 17G65, locale en-BE)
    • Flutter version 0.7.3 at /Users/aroba/flutter
    • Framework revision 3b309bda07 (2 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/aroba/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/aroba/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.3)
    • IntelliJ at /Users/aroba/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 28.0.4
    • Dart plugin version 182.4323.44

[✓] VS Code (version 1.26.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.17.1

[✓] Connected devices (1 available)
    • iPhone X • 05732A5C-C0A3-4DBD-A21E-17C8814C3845 • ios • iOS 11.4 (simulator)

• No issues found!
```
regards

**Comment by zoechi** [comment] 2018-09-12 09:37
Have you checked if it looks different in Android?

**Comment by HansMuller** [comment] 2019-01-09 19:02
If the SafeArea specifes `bottom: false` then the BottomNavigationBar will extent to the bottom of the screen and its shadow will not appear. 

Here's an example: https://gist.github.com/HansMuller/936413db82428cecf260697e9a6a31f9

**Comment by daadu** [comment] 2019-02-18 12:37
There should be a field in BottomNavigationBar for elevation just like BottomAppBar.
I've developed it in my fork. Should I create a PR for it? I haven't contributed to any project before.

**Comment by daadu** [comment] 2019-02-18 12:37
AppBar also has elevation field.

**Comment by Ahmadre** [comment] 2019-05-01 19:39
Just add to your BottomNavigationBar:
```dart
BottomNavigationBar(
...
elevation: 0,
...
```

**Comment by robertying** [comment] 2019-05-17 20:22
There is a workaround for this problem using `Padding` with `SafeArea bottom padding` derived from `MediaQuery`.

You can do the same for `appBar` too.

Example:
```dart
  @override
  Widget build(BuildContext context) {
    // Scaffold is a layout for the major Material Components.
    return MaterialApp(
      title: '#THU',
      theme: ThemeData(
        brightness: Brightness.light,
        primaryColor: Colors.white,
        accentColor: Color.fromARGB(1, 102, 8, 116),
      ),
      home: Container(
        color: Colors.white,
        child: SafeArea(
          bottom: false,
          child: Scaffold(
            appBar: AppBar(
              backgroundColor: Colors.white,
              title: Text('#thu'),
              textTheme: Theme.of(context).textTheme.apply(
                    bodyColor: Colors.black,
                    displayColor: Colors.black,
                  ),
            ),
            body: Center(
              child: Text('Hello, world!'),
            ),
            bottomNavigationBar: Material(
              color: Colors.white,
              elevation: 16,
              child: Padding(
                padding: EdgeInsets.only(
                    bottom: MediaQuery.of(context).padding.bottom),
                child: TabBar(
                  tabs: <Tab>[
                    Tab(
                      icon: Icon(Icons.person),
                    ),
                    Tab(
                      icon: Icon(Icons.email),
                    ),
                  ],
                  controller: _tabController,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
```

**Comment by mbyervand** [comment] 2019-12-14 10:38
### Hello friends. I use SafeArea but it doesn't make a difference in appbar

![code](https://user-images.githubusercontent.com/56269494/70847532-bf25f280-1e7a-11ea-80b7-bacb6549aea8.JPG)

![ui](https://user-images.githubusercontent.com/56269494/70847563-0e6c2300-1e7b-11ea-94aa-0d7582516b36.JPG)

**Comment by Hixie** [comment] 2020-01-09 21:55
This is a bug database, not a support channel. Since there does not appear to be an actionable bug here for us to fix, I'm going to close this issue. If there's a specific bug you would like us to fix please file a new issue with a clear description of the steps to reproduce the problem including full code. Thanks!

**Closed by Hixie** 2020-01-09 21:55 UTC
Labels: a: fidelity, f: material design, framework

**Comment by Sandeep911** [comment] 2020-07-13 09:51
Instead of wrapping the body with SafeArea, wrap the Scaffold itself with SafeArea, it should help

**Comment by idkq** [comment] 2021-02-16 23:42
> This is a bug database 

No its not, not necessarily
