### ISSUE TITLE
Cannot select telephoto lens on Google Pixel 8 Pro

### ISSUE THREAD

**Issue by MS-Mabri** [flutter/flutter#153554] opened 2024-08-16 10:13 UTC
Hi there,

I am using the https://pub.dev/packages/camera camera package to access the camera of my Google Pixel Pro 8. I want to select the telephoto lens but at any rate, the lens is not shown in the available camera controllers. I only have 1 front and 1 back camera shown in the list.

Does anyone know why it is like that?

Best regards

**Comment by huycozy** [comment] 2024-08-16 11:07
Closing this as a duplicate of https://github.com/flutter/flutter/issues/38987.

**Closed by huycozy** 2024-08-16 11:07 UTC
Labels: in triage
