### ISSUE TITLE
PaginatedDataTable sort indicator toggles on rebuild.

### ISSUE THREAD

**Issue by puhgeh** [flutter/flutter#89927] opened 2021-09-12 01:44 UTC
The sort indicator toggles whenever a rebuild is called even when the value is constant.

`Doctor summary (to see all details, run flutter doctor -v):

```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.59.0)
[✓] Connected device (1 available)`
```

**Sample Widget:**

```dart
class TestWidget extends StatefulWidget {
  @override
  _TestWidgetState createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget> {
  DataTableSource _data = MyData();

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 500,
      child: Column(
        children: [
          SizedBox(
            height: 10,
          ),
          PaginatedDataTable(
            source: _data,
            header: Text('My Products'),
            actions: [
              IconButton(
                  onPressed: () {
                    setState(() {});
                  },
                  icon: Icon(Icons.refresh))
            ],
            columns: [
              DataColumn(label: Text('ID'), onSort: (index, ascending) {}),
              DataColumn(label: Text('Name'), onSort: (index, ascending) {}),
              DataColumn(label: Text('Price'), onSort: (index, ascending) {})
            ],
            columnSpacing: 100,
            horizontalMargin: 10,
            rowsPerPage: 5,
            showCheckboxColumn: false,
            sortAscending: false, // <-- explicitly set this or not, the indicator will toggle on rebuild.
            sortColumnIndex: 0,
          ),
        ],
      ),
    );
  }
}

class MyData extends DataTableSource {
  // Generate some made-up data
  final List<Map<String, dynamic>> _data = List.generate(
      200, (index) => {"id": index, "title": "Item $index", "price": Random().nextInt(10000)});

  bool get isRowCountApproximate => false;
  int get rowCount => _data.length;
  int get selectedRowCount => 0;
  DataRow getRow(int index) {
    return DataRow(cells: [
      DataCell(Text(_data[index]['id'].toString())),
      DataCell(Text(_data[index]["title"])),
      DataCell(Text(_data[index]["price"].toString())),
    ]);
  }
}
```

**The initial state**
![Screen Shot 2021-09-12 at 9 31 11 AM](https://user-images.githubusercontent.com/5802406/132967845-7aa09a17-8d48-404e-aec1-b94d55a6144f.png)

**Rebuild is called**
![Screen Shot 2021-09-12 at 9 32 57 AM](https://user-images.githubusercontent.com/5802406/132967857-50dba2bd-b5b8-4546-adc1-257b335538b2.png)

**Comment by puhgeh** [comment] 2021-09-13 14:46
Hi @maheshmnj Thank you for responding. Yes, calling a rebuild toggles the indicator; either you set it to descending and it toggles to ascending or vice-versa. I even tried it on a StatelessWidget using a provider to take hold of the value for the flag and the same behavior occurs. Found it to be an issue on DataTable too.

**Comment by sperochon** [comment] 2021-12-06 19:21
Hi, maybe this is a duplicate of [this one](https://github.com/flutter/flutter/issues/43724) (created in 2019!) ?
which hopefully got a PR submitted 5 days ago 😀

**Comment by maheshmnj** [comment] 2021-12-07 06:34
Closing as a duplicate of https://github.com/flutter/flutter/issues/43724.

**Closed by maheshmnj** 2021-12-07 06:34 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 2.5, found in release: 2.6
