### ISSUE TITLE
App stuck on 'Waiting for connection from debug service on Chrome...' on 3.24

### ISSUE THREAD

**Issue by GeorgePagounis** [flutter/flutter#153165] opened 2024-08-09 14:24 UTC
### Steps to reproduce

1. Upgrade flutter to v3.24 (from v3.22.3)
2. Create a new project via flutter create <name> command
3. Run the new flutter project via Visual Studio Code by having Chrome (web) selected.

### Expected results

App should load normally.

### Actual results

App hangs in _Flutter: Waiting for connection from debug service on Chrome_ step, while showing blue progress bar on a white browser page.

Sometimes when the browser opens, I get asked to choose my predefined search engine and get an other error as follows:

> Connecting to VM Service at ws://127.0.0.1:61179/hxx4nYPkBrU=/ws
Connected to the VM Service.
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown attaching to the render tree:
TypeError: Cannot read properties of undefined (reading 'objectRuntimeType')

This  object in `TypeError: Cannot read properties of undefined (reading '<object>')` changes from time to time to other package web plugins an app may use depending.

### Code sample

This seems a bit unrelated to code since it happens even in newly created projects such as `flutter create bug`

### Screenshots or Video

![running app hangs](https://github.com/user-attachments/assets/de9b132c-0949-4242-a27d-c9eef15d16b4)

### Logs

Whenever the search engine question comes up I get below logs

<details open><summary>Logs</summary>

```console
> Connecting to VM Service at ws://127.0.0.1:61179/hxx4nYPkBrU=/ws
Connected to the VM Service.
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown attaching to the render tree:
TypeError: Cannot read properties of undefined (reading 'objectRuntimeType')
When the exception was thrown, this was the stack:
packages/flutter/src/widgets/framework.dart 352:25                                toStringShort
framework.dart:352
packages/flutter/src/widgets/framework.dart 5082:38                               toStringShort
framework.dart:5082
packages/flutter/src/foundation/diagnostics.dart 2865:22                          <fn>
diagnostics.dart:2865
packages/flutter/src/foundation/diagnostics.dart 2866:14                          toDescription
diagnostics.dart:2866
packages/flutter/src/foundation/diagnostics.dart 1201:30                          [_debugRender]
diagnostics.dart:1201
packages/flutter/src/foundation/diagnostics.dart 1131:14                          render
diagnostics.dart:1131
packages/flutter/src/foundation/diagnostics.dart 1776:20                          <fn>
diagnostics.dart:1776
packages/flutter/src/foundation/diagnostics.dart 1783:14                          toStringDeep
diagnostics.dart:1783
packages/flutter/src/foundation/diagnostics.dart 1706:18                          <fn>
diagnostics.dart:1706
packages/flutter/src/foundation/diagnostics.dart 1717:14                          toString
diagnostics.dart:1717
packages/flutter/src/foundation/diagnostics.dart 3014:66                          <fn>
diagnostics.dart:3014
```
This  object in `TypeError: Cannot read properties of undefined (reading '<object>')` changes from time to time to other package web plugins an app may use depending.
</details>

If I close Visual Studio Code and reopen I get for example this
<details open><summary>Logs</summary>

```console
Connecting to VM Service at ws://127.0.0.1:63377/ti29rFTKMII=/ws
Connected to the VM Service.
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown building WidgetsApp-[GlobalObjectKey
_MaterialAppState#477cf](dirty, state: _WidgetsAppState#5ca9c):
TypeError: Cannot read properties of undefined (reading 'AxisDirection')

The relevant error-causing widget was:
  MaterialApp MaterialApp:file:///C:/Users/gogom/Applications/new_project/lib/main.dart:13:12

When the exception was thrown, this was the stack:
5
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1091:8  get
operations.dart:1091
packages/flutter/src/widgets/app.dart 1249:67                                     get _defaultWebShortcuts
app.dart:1249
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1091:8  get
operations.dart:1091
packages/flutter/src/widgets/app.dart 1310:14                                     get defaultShortcuts
app.dart:1310
packages/flutter/src/widgets/app.dart 1802:55                                     build
app.dart:1802
packages/flutter/src/widgets/framework.dart 5729:27                               build
framework.dart:5729
packages/flutter/src/widgets/framework.dart 5617:15                               performRebuild
framework.dart:5617
packages/flutter/src/widgets/framework.dart 5780:11                               performRebuild
framework.dart:5780
packages/flutter/src/widgets/framework.dart 5333:7                                rebuild
framework.dart:5333
packages/flutter/src/widgets/framework.dart 5599:5                                [_firstBuild]
framework.dart:5599
packages/flutter/src/widgets/framework.dart 5771:11                               [_firstBuild]
framework.dart:5771
packages/flutter/src/widgets/framework.dart 5593:5                                mount
framework.dart:5593
packages/flutter/src/widgets/framework.dart 4468:15                               inflateWidget
framework.dart:4468
packages/flutter/src/widgets/framework.dart 3963:18                               updateChild
framework.dart:3963
packages/flutter/src/widgets/framework.dart 6900:14                               mount
framework.dart:6900
packages/flutter/src/widgets/framework.dart 4468:15                               inflateWidget
framework.dart:4468
packages/flutter/src/widgets/framework.dart 3963:18                               updateChild
framework.dart:3963
packages/flutter/src/widgets/framework.dart 5642:16                               performRebuild
framework.dart:5642
packages/flutter/src/widgets/framework.dart 5333:7                                rebuild
framework.dart:5333
packages/flutter/src/widgets/framework.dart 5599:5                                [_firstBuild]
framework.dart:5599
packages/flutter/src/widgets/framework.dart 5593:5                                mount
framework.dart:5593
packages/flutter/src/widgets/framework.dart 4468:15                               inflateWidget
framework.dart:4468
packages/flutter/src/widgets/framework.dart 3963:18                               updateChild
framework.dart:3963
packages/flutter/src/widgets/framework.dart 5642:16                               performRebuild
framework.dart:5642
packages/flutter/src/widgets/framework.dart 5780:11                               performRebuild
framework.dart:5780
packages/flutter/src/widgets/framework.dart 5333:7                                rebuild
framework.dart:5333
packages/flutter/src/widgets/framework.dart 5599:5                                [_firstBuild]
framework.dart:5599
packages/flutter/src/widgets/framework.dart 5771:11                               [_firstBuild]
framework.dart:5771
packages/flutter/src/widgets/framework.dart 5593:5                                mount
framework.dart:5593
packages/flutter/src/widgets/framework.dart 4468:15                               inflateWidget
framework.dart:4468
packages/flutter/src/widgets/framework.dart 3963:18                               updateChild
framework.dart:3963
packages/flutter/src/widgets/framework.dart 5642:16                               performRebuild
framework.dart:5642
packages/flutter/src/widgets/framework.dart 5333:7                                rebuild
framework.dart:5333
packages/flutter/src/widgets/framework.dart 5599:5                                [_firstBuild]
framework.dart:5599
packages/flutter/src/widgets/framework.dart 5593:5                                mount
framework.dart:5593
packages/flutter/src/widgets/framework.dart 4468:15                               inflateWidget
framework.dart:4468
packages/flutter/src/widgets/framework.dart 3963:18                               updateChild
framework.dart:3963
packages/flutter/src/widgets/framework.dart 5642:16                               performRebuild
framework.dart:5642
packages/flutter/src/widgets/framework.dart 5333:7                                rebuild
framework.dart:5333
packages/flutter/src/widgets/framework.dart 5599:5                                [_firstBuild]
framework.dart:5599
packages/flutter/src/widgets/framework.dart 5593:5                                mount
framework.dart:5593
```
</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
    • Flutter version 3.24.0 on channel stable at C:\Users\gogom\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (10 days ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\gogom\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code (version 1.92.1)
    • VS Code at C:\Users\gogom\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3880]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.100
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.86

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

This does not happen to me on v3.22.3

**Comment by felipeduarte26** [comment] 2024-08-09 15:27
same problem here

**Comment by j-fbriere** [comment] 2024-08-09 16:01
Same here.

Upgraded our PWA project from Flutter stable 3.22.2 to stable 3.24.0.
Got the same issue when running our WEB app who got stuck on 'Waiting for connection from debug service on Chrome...'
The error message is:
TypeError: Cannot read properties of undefined (reading 'main')

So I had to rollback to 3.22.2.

**Comment by jthlim** [comment] 2024-08-09 20:04
I rolled forward to main branch, and it seems to be fixed there, but that's a little uncomfortable, and I'd much prefer to be on stable.

**Comment by sapar-io** [comment] 2024-08-09 23:20
I upgraded now, same problem here. But if I build and deploy web. It work correctly from hosting website.

**Comment by Trung15010802** [comment] 2024-08-10 02:29
I have a similar issue. But it doesn't show any error. It stuck at loading screen.
![image](https://github.com/user-attachments/assets/973f589c-6364-4e31-8611-767ba1128254)

**Comment by bharathwajv** [comment] 2024-08-10 05:06
Found a workaround:
-> Just refresh the page after launching, the debug service will attach again and start working.

but this is definitely has to be fixed from flutter end soon

**Comment by sapar-io** [comment] 2024-08-10 08:44
> Found a workaround: -> Just refresh the page after launching, the debug service will attach again and start working.
> 
> but this is definitely has to be fixed from flutter end soon

thank you! it work

**Comment by jocubeit** [comment] 2024-08-10 10:58
Interestingly FVM broke for me at the same time. I couldn't roll back using FVM. I couldn't even reinstall FVM (error: Failed to fetch installed FVM version).

Had to delete `3.24.0` and `stable` in the `fvm/versions` folder, then delete `default` symbolic link, copy `3.22.3` as `stable` (not sure if this should have been a symlink - I forgot to check), then link `default` to `3.22.3`. FVM works again. Just for good measure I then ran `fvm global 3.22.3`.

I made no changes to code, ran again with 3.22.3, no issues starting, problem's gone away.

**Comment by spydon** [comment] 2024-08-10 18:56
Should be fixed by https://github.com/flutter/flutter/issues/152953
I tried with main and the issue is indeed solved there!

**Comment by passsionforprogramming** [comment] 2024-08-11 18:19
I am also seeing this issue as well.

**Comment by huycozy** [comment] 2024-08-12 05:16
Thank everyone for the report! 

This is a known issue at https://github.com/flutter/flutter/issues/145410 and it's fixed on Flutter master channel. Please follow the CP request at https://github.com/flutter/flutter/issues/152953.

Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/145410.

**Closed by huycozy** 2024-08-12 05:16 UTC
Labels: in triage

**Comment by j-fbriere** [comment] 2024-08-12 17:30
Not using the master channel.
It should be resolved on the stable channel ASAP.

**Comment by ibereydereyes** [comment] 2024-08-16 17:35
Estoy con el mismo problema a hoy y ya no se que mas hacer y probar, alguna novedad sobre el arreglo en el maestro de flutter?
que debería hacer para arreglar el problema?
Gracias!

**Comment by bharathwajv** [comment] 2024-08-18 07:35
the master channel has many bugs, please Fix this in STABLE!

**Comment by geronimol** [comment] 2024-08-20 16:37
Same issue. Any updates?

**Comment by juanptoror** [comment] 2024-08-20 20:35
`   - const serviceWorkerVersion = "{{flutter_service_worker_version}}";
    + const serviceWorkerVersion = "{{flutter_service_worker_version}}";
`

`    -  _flutter.loader.load({
    +  _flutter.loader.loadEntrypoint({
`

I just changed this and it worked, it is a temporary solution.

**Comment by juanptoror** [comment] 2024-08-20 20:37
web/index.html

`   - const serviceWorkerVersion = "{{flutter_service_worker_version}}"; `
`   + const serviceWorkerVersion = null;`


`    -  _flutter.loader.load({ `
`    +  _flutter.loader.loadEntrypoint({ `


I just changed this and it worked, it is a temporary solution.
