### ISSUE TITLE
[Web][IOS] Unable to enter text into Textfield & TextFormField

### ISSUE THREAD

**Issue by VladislavYakonyuk** [flutter/flutter#121076] opened 2023-02-20 06:16 UTC
## Steps to Reproduce

1. For run using `flutter build web`
2. Open web application using Safari on IOS (IPhone Xr 16.1.1)
3. Attempt to type in any TextFormField 

**Expected results:** 
TextFormfield should gain focus and accept text upon keyboard button presses

**Actual results:** 
TextFormfield gains focus and does not accept text upon keyboard button presses

<details>
<summary>Code sample</summary>

```dart
TextFormField(
  hintText: "text",
  controller: _myControllerInput,
  keyboardType: TextInputType.number,
  decoration: InputDecoration(
    prefixIcon: Text("+"),
    counterText: "",
    border: InputBorder.none,
    focusedBorder: InputBorder.none,
    enabledBorder: InputBorder.none,
    errorBorder: InputBorder.none,
    disabledBorder: InputBorder.none,
    hintText: widget.hintText,
    prefixIconConstraints: const BoxConstraints(maxWidth: 48),
    )
  maxLength: 14,
  inputFormatters: <TextInputFormatter>[
    FilteringTextInputFormatter.allow(RegExp(r'^[0-9]+$')),
  ],
  onSubmitted: (val) => _submit(),
)
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.0 22A380 darwin-arm64, locale ru-RU)
    • Flutter version 3.7.3 on channel stable at /Users/vlados/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (11 дней назад), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to
        invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 222.4345.14

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
    • IntelliJ at /Users/vlados/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by exaby73** [comment] 2023-02-20 13:17
Hello @VladislavYakonyuk. I am able to enter numbers into the `TextFormField` as per your input formatter. Am I missing anything? Could you share a screen recording of the issue?

**Comment by VladislavYakonyuk** [comment] 2023-02-20 14:29
https://user-images.githubusercontent.com/58368922/220133819-f73eddf0-6f9f-4be2-87ee-53e4127e0db5.MP4

Here's an example of how it works on a real device

**Comment by exaby73** [comment] 2023-02-20 14:35
Using the following code, I cannot reproduce this issue.

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: Center(
        child: TextFormField(
          keyboardType: TextInputType.number,
          decoration: const InputDecoration(
            prefixIcon: Text("+"),
            counterText: "",
            border: InputBorder.none,
            focusedBorder: InputBorder.none,
            enabledBorder: InputBorder.none,
            errorBorder: InputBorder.none,
            disabledBorder: InputBorder.none,
            hintText: 'Hint Text',
            prefixIconConstraints: BoxConstraints(maxWidth: 48),
          ),
          maxLength: 14,
          inputFormatters: <TextInputFormatter>[
            FilteringTextInputFormatter.allow(RegExp(r'^[0-9]+$')),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by VladislavYakonyuk** [comment] 2023-02-21 13:49
the other day I will deploy this code on my hosting and check if anything goes wrong - I will write here

**Comment by VladislavYakonyuk** [comment] 2023-02-21 13:49
the other day I will deploy this code on my hosting and check if anything goes wrong - I will write here

**Comment by MrShafqatNadeem** [comment] 2023-02-28 15:08
Did you find any solution ?
I have same issue , unable to input OTP manually into a textfield while integration is running.

**Comment by VladislavYakonyuk** [comment] 2023-02-28 15:10
I was able to fix this issue by upgrading to flutter 3.3.0 stable.  a little later I will throw off an example of a docker for deployment

**Comment by VladislavYakonyuk** [comment] 2023-02-28 16:50
`curl -L https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.3.0-stable.tar.xz -o flutter.tar.xz`

I used this line in the dockerfile to install the right version of the flutter, because `flutter downgrade` did not meet the requirements and expectations. 

an example of what to do next:
``` Dockerfile
RUN tar -xf flutter.tar.xz
RUN git config --global --add safe.directory /flutter
ENV PATH "$PATH:/flutter/bin"
RUN flutter config --enable-web
```

**Comment by huycozy** [comment] 2023-03-01 10:10
Closing the issue as it's fixed after upgrading to the newer Flutter version (above [comment](https://github.com/flutter/flutter/issues/121076#issuecomment-1448355545)). If you still experience this issue, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2023-03-01 10:10 UTC
Labels: in triage
