### ISSUE TITLE
[macOS - Web] Hot restart resets URL.

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#82737] opened 2021-05-17 20:13 UTC
Code: https://github.com/flutter/uxr/blob/master/nav2-usability/scenario_code/lib/deeplink-pathparam/router.dart

Steps:
- run
- click to change the page
- press 'r' in terminal or the hot refresh button in the IDE

The page will change to '/'. This has been happening in macOS since always. I talked with some people and this works in Windows and Ubuntu. Only mac is affected.

FAIL - macOS (Channel beta, 2.2.0-10.3.pre, on macOS 11.3 20E232
    darwin-x64)

https://user-images.githubusercontent.com/351125/118549624-1eec9100-b732-11eb-84c4-7e2e1653dc53.mov

WORKS - ubuntu (Channel stable, 2.0.6)
![Peek_2021-05-17_19-47](https://user-images.githubusercontent.com/351125/118549647-26ac3580-b732-11eb-9f5d-5bc3cceaacb1.gif)

**Comment by darshankawar** [comment] 2021-05-18 08:52
Thanks for the detailed report. Verified this using latest master and see the same behavior on Mac.

<details>
<summary> flutter doctor -v </summary>

```
[✓] Flutter (Channel master, 2.3.0-2.0.pre.253, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-2.0.pre.253 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bac5a0db3b (5 hours ago), 2021-05-18 10:19:03 +0800
    • Engine revision 3cda7f5807
    • Dart version 2.14.0 (build 2.14.0-119.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.



```

</details>

**Comment by slovnicki** [comment] 2021-05-21 15:02
This is present on all OSs with either Router API or "Navigator 1.0" and it was not present in `stable 2.0.6`. I'm not sure when exactly did it break, but is still present on `master`.

I would say this is a duplicate of #79241

**Comment by yjbanov** [comment] 2021-06-10 22:22
Deduplicating with https://github.com/flutter/flutter/issues/79241

**Closed by yjbanov** 2021-06-10 22:22 UTC
Labels: found in release: 2.3, has reproducible steps, platform-mac, platform-web
