### ISSUE TITLE
Flutter view receives pointer events, when visually underneath a native iOS view spawned by a plugin

### ISSUE THREAD

**Issue by saibotma** [flutter/flutter#94293] opened 2021-11-27 16:54 UTC
## Steps to Reproduce
- Create a flutter plugin that spawns a native iOS modal, like in the example project.
- Add a text field and a button to the flutter screen.
- Spawn the native view on button press.
- Touch the modal at the same height as the text field beneath the modal.

**Expected results:** 
The text field should not get focus and the keyboard should not open.

**Actual results:**
The text field gets focus and the keyboard opens.
The same also happens with buttons instead of text fields.

Video:
https://user-images.githubusercontent.com/26022902/143690036-cf6a2ac3-8215-4efe-8091-4be2424e7f25.mov

I have created a second example app written in iOS natively that does the exact same thing as the flutter app, however the text field (correctly) does not get focus when tapping the modal above it.

<details>
<summary>Code sample</summary>
 Example projects in my [GitHub repository](https://github.com/saibotma/pointer_event_bug_example).
</details>

<details>
  <summary>Logs</summary>

Logs when tapping the text field (the same when modal opened or not).

```
[+23713 ms] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ]      Probably at least one of the constraints in the following list is one you don't want. 
[        ]      Try this: 
[        ]              (1) look at each constraint and try to figure out which you don't expect; 
[        ]              (2) find the code that added the unwanted constraint or constraints and fix it. 
[        ]      (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2811efed0 h=--& v=--& _UIButtonBarButton:0x106bd2bf0.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2811e94a0 _UIUCBKBSelectionBackground:0x106bd3510.bottom == _UIButtonBarButton:0x106bd2bf0.bottom - 6   (active)>",
[        ]     "<NSLayoutConstraint:0x2811e9400 V:|-(6)-[_UIUCBKBSelectionBackground:0x106bd3510]   (active, names: '|':_UIButtonBarButton:0x106bd2bf0 )>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2811e94a0 _UIUCBKBSelectionBackground:0x106bd3510.bottom == _UIButtonBarButton:0x106bd2bf0.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ]      Probably at least one of the constraints in the following list is one you don't want. 
[        ]      Try this: 
[        ]              (1) look at each constraint and try to figure out which you don't expect; 
[        ]              (2) find the code that added the unwanted constraint or constraints and fix it. 
[        ]      (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2811ef890 h=--& v=--& _UIButtonBarButton:0x106bd0ca0.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2811e8e60 V:|-(6)-[_UIUCBKBSelectionBackground:0x106bd1cb0]   (active, names: '|':_UIButtonBarButton:0x106bd0ca0 )>",
[        ]     "<NSLayoutConstraint:0x2811e8f00 _UIUCBKBSelectionBackground:0x106bd1cb0.bottom == _UIButtonBarButton:0x106bd0ca0.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2811e8f00 _UIUCBKBSelectionBackground:0x106bd1cb0.bottom == _UIButtonBarButton:0x106bd0ca0.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ]      Probably at least one of the constraints in the following list is one you don't want. 
[        ]      Try this: 
[        ]              (1) look at each constraint and try to figure out which you don't expect; 
[        ]              (2) find the code that added the unwanted constraint or constraints and fix it. 
[        ]      (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2811efbb0 h=--& v=--& _UIButtonBarButton:0x106bd2150.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2811e9130 V:|-(6)-[_UIUCBKBSelectionBackground:0x106bd2a70]   (active, names: '|':_UIButtonBarButton:0x106bd2150 )>",
[        ]     "<NSLayoutConstraint:0x2811e91d0 _UIUCBKBSelectionBackground:0x106bd2a70.bottom == _UIButtonBarButton:0x106bd2150.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2811e91d0 _UIUCBKBSelectionBackground:0x106bd2a70.bottom == _UIButtonBarButton:0x106bd2150.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ]      Probably at least one of the constraints in the following list is one you don't want. 
[        ]      Try this: 
[        ]              (1) look at each constraint and try to figure out which you don't expect; 
[        ]              (2) find the code that added the unwanted constraint or constraints and fix it. 
[        ]      (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2811ea3f0 h=--& v=--& _UIButtonBarButton:0x106ba49c0.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2811e9c70 _UIUCBKBSelectionBackground:0x106b880a0.bottom == _UIButtonBarButton:0x106ba49c0.bottom - 6   (active)>",
[        ]     "<NSLayoutConstraint:0x2811e9bd0 V:|-(6)-[_UIUCBKBSelectionBackground:0x106b880a0]   (active, names: '|':_UIButtonBarButton:0x106ba49c0 )>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2811e9c70 _UIUCBKBSelectionBackground:0x106b880a0.bottom == _UIButtonBarButton:0x106ba49c0.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ]      Probably at least one of the constraints in the following list is one you don't want. 
[        ]      Try this: 
[        ]              (1) look at each constraint and try to figure out which you don't expect; 
[        ]              (2) find the code that added the unwanted constraint or constraints and fix it. 
[        ]      (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2811ea0d0 h=--& v=--& _UIButtonBarButton:0x106939610.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2811e98b0 V:|-(6)-[_UIUCBKBSelectionBackground:0x106b9aca0]   (active, names: '|':_UIButtonBarButton:0x106939610 )>",
[        ]     "<NSLayoutConstraint:0x2811e9950 _UIUCBKBSelectionBackground:0x106b9aca0.bottom == _UIButtonBarButton:0x106939610.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2811e9950 _UIUCBKBSelectionBackground:0x106b9aca0.bottom == _UIButtonBarButton:0x106939610.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[        ] [LayoutConstraints] Unable to simultaneously satisfy constraints.
[        ]      Probably at least one of the constraints in the following list is one you don't want. 
[        ]      Try this: 
[        ]              (1) look at each constraint and try to figure out which you don't expect; 
[        ]              (2) find the code that added the unwanted constraint or constraints and fix it. 
[        ]      (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
[        ] (
[        ]     "<NSAutoresizingMaskLayoutConstraint:0x2811ea710 h=--& v=--& _UIButtonBarButton:0x106bd1e30.height == 0   (active)>",
[        ]     "<NSLayoutConstraint:0x2811e9ea0 V:|-(6)-[_UIUCBKBSelectionBackground:0x106b83910]   (active, names: '|':_UIButtonBarButton:0x106bd1e30 )>",
[        ]     "<NSLayoutConstraint:0x2811e9f40 _UIUCBKBSelectionBackground:0x106b83910.bottom == _UIButtonBarButton:0x106bd1e30.bottom - 6   (active)>"
[        ] )
[        ] Will attempt to recover by breaking constraint 
[        ] <NSLayoutConstraint:0x2811e9f40 _UIUCBKBSelectionBackground:0x106b83910.bottom == _UIButtonBarButton:0x106bd1e30.bottom - 6   (active)>
[        ] Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
[        ] The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

```

```
Analyzing example...                                                    
No issues found! (ran in 2.0s)
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-DE)
    • Flutter version 2.5.3 at /Users/tobias/Documents/Dev/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tobias/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/tobias/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tobias/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/tobias/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tobias/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Users/tobias/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/212.5457.46/IntelliJ IDEA.app
    • Flutter plugin version 62.0.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • KrasserDude (mobile) • 79aa79a8f05d850905d52818fde5eea8d1b898ff • ios            • iOS 14.8.1 18H107
    • macOS (desktop)      • macos                                    • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)         • chrome                                   • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2021-11-28 11:03
Duplicate of https://github.com/flutter/flutter/issues/14720

**Closed by stuartmorgan** 2021-11-28 11:03 UTC
