### ISSUE TITLE
RenderSliverFixedExtentBoxAdaptor.getMinChildIndexForScrollOffset - Unsupported operation: Infinity or NaN toInt.

### ISSUE THREAD

**Issue by Hossam-mustafa** [flutter/flutter#143716] opened 2024-02-19 20:10 UTC
### Actual results

We've encountered an unexpected crash in our Flutter app that's leaving us scratching our heads. Here's what we know:

Error Message:
io.flutter.plugins.firebase.crashlytics.FlutterError - Unsupported operation: Infinity or NaN toInt. Error thrown.

Location:
RenderSliverFixedExtentBoxAdaptor.getMinChildIndexForScrollOffset (sliver_fixed_extent_list.dart)
package:flutter/src/rendering/sliver_fixed_extent_list.dart

Description:
Unfortunately, Crashlytics hasn't provided us with much context beyond the error message and the location within the code where the error occurred. There are no indications of which specific screen or widget might be causing the issue, making it challenging to pinpoint the root cause.

Devices:
Xiaomi 32%
Transsion 15%
Samsung 12%
Oppo 12%
Lenovo 4%
Huawei 3%

Operating systems:
Android 11 76%
Android 10 24%

### Steps to reproduce

Unfortunately, at this time, we're unable to provide specific steps to reproduce the crash. The nature of the error message and the lack of contextual information from Crashlytics make it challenging for us to pinpoint the exact sequence of events leading to the crash.

### Expected results

Given the nature of the unexpected crash and the lack of specific details provided by Crashlytics, we are currently unable to define expected results for this issue. Typically, we would expect the application to perform as intended without encountering any errors or unexpected behavior.

### Logs

<details open><summary>Logs</summary>

```console
RenderSliverFixedExtentBoxAdaptor.getMinChildIndexForScrollOffset
io.flutter.plugins.firebase.crashlytics.FlutterError - Unsupported operation: Infinity or NaN toInt. Error thrown .

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
Unsupported operation: Infinity or NaN toInt. Error thrown .
RenderSliverFixedExtentBoxAdaptor.getMinChildIndexForScrollOffset (sliver_fixed_extent_list.dart)
RenderSliverFixedExtentBoxAdaptor.performLayout (sliver_fixed_extent_list.dart:261)
RenderObject.layout (object.dart:2546)
RenderSliverEdgeInsetsPadding.performLayout (sliver_padding.dart:139)
_RenderSliverFractionalPadding.performLayout (sliver_fill.dart:160)
RenderObject.layout (object.dart:2546)
RenderViewportBase.layoutChildSequence (viewport.dart:601)
RenderViewport._attemptLayout (viewport.dart:1554)
RenderViewport.performLayout (viewport.dart:1463)
RenderObject._layoutWithoutResize (object.dart:2385)
PipelineOwner.flushLayout (object.dart:1025)
PipelineOwner.flushLayout (object.dart:1038)
RendererBinding.drawFrame (binding.dart:591)
WidgetsBinding.drawFrame (binding.dart:986)
RendererBinding._handlePersistentFrameCallback (binding.dart:457)
SchedulerBinding._invokeFrameCallback (binding.dart:1325)
SchedulerBinding.handleDrawFrame (binding.dart:1255)
SchedulerBinding._handleDrawFrame (binding.dart:1113)

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22631.3155], locale en-US)
    • Flutter version 3.16.9 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (4 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\pc\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34330.188
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.86.2)
    • VS Code at C:\Users\pc\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.82.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3155]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.185
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.128

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.```

</details>

**Comment by moffatman** [comment] 2024-02-19 20:59
Please share your code where you use fixedextentlist

**Comment by Hossam-mustafa** [comment] 2024-02-19 21:03
> Please share your code where you use fixedextentlist

@moffatman I don't use this kind of list in my whole project.

**Comment by moffatman** [comment] 2024-02-19 21:24
Hmmm. Maybe `SliverFillViewport`?

**Comment by Hossam-mustafa** [comment] 2024-02-19 21:29
The only scrollable widgets I use are listview, gridview and tabbarview

**Comment by moffatman** [comment] 2024-02-19 21:40
No PageView?

**Comment by Hossam-mustafa** [comment] 2024-02-19 21:53
No

could you give me some guide line about what could cause this problem?

**Comment by moffatman** [comment] 2024-02-19 22:03
Idk, you can see in the callstack where the exception was thrown. Probably it's some issue with layout of a scrollable using one of those classes mentioned above. It could be in a third-party dependency?

**Comment by Hossam-mustafa** [comment] 2024-02-19 22:12
these are all the packages i use in the project:

  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  flutter_localization: ^0.2.0
  intl: any
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  pinch_zoom: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.3.9
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_storage: ^11.6.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  google_mobile_ads: ^4.0.0
  http: ^1.2.0
  
  i think non of them uses scrollable layouts

**Comment by danagbemava-nc** [comment] 2024-02-20 07:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/105630

**Closed by danagbemava-nc** 2024-02-20 07:14 UTC
Labels: in triage
