### ISSUE TITLE
URL LAUNCHER 4.0.1&& 4.0.2 THROWS  PLATFORM ERROR

### ISSUE THREAD

**Issue by rajeshjeshar** [flutter/flutter#24920] opened 2018-12-03 04:07 UTC
```
PlatformException (PlatformException(error, Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?, null))
```
after downgrading to 3.0.0 it Works well

**Comment by zoechi** [comment] 2018-12-03 06:36
Please try 4.0.2

**Comment by rajeshjeshar** [comment] 2018-12-03 06:39
@zoechi  tried both 4.0.1 and 4.0.2

**Comment by zoechi** [comment] 2018-12-03 07:20
Please add the output of `flutter doctor -v`.

**Comment by ViniciusSossela** [comment] 2018-12-03 19:09
The same is happing here...

**Comment by naumanahmed19** [comment] 2018-12-03 20:37
url_launcher: 4.0.0 works fine but new version have an issue with Android

**Comment by goderbauer** [comment] 2018-12-03 21:52
Looks like this is a duplicate of https://github.com/flutter/flutter/issues/24866.

**Closed by goderbauer** 2018-12-03 21:52 UTC
Labels: p: first party, plugin, severe: crash
