### ISSUE TITLE
[iOS] When navigating to a page with a TextField which has autofocus, voiceover bounding box disappears, and user can no longer swipe

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#54093] opened 2020-04-06 14:51 UTC
https://b.corp.google.com/issues/153320803.

**Comment by mehmetf** [comment] 2020-04-06 17:15
I believe this is a dupe of https://github.com/flutter/flutter/issues/53065

**Closed by mehmetf** 2020-04-06 17:15 UTC
Labels: a: accessibility, customer: money (g3), framework, platform-ios, severe: customer critical
