### ISSUE TITLE
[camera] When I start the startImageStream, after calling the stopImageStream method, an error will be reported. The error message is: A resource failed to call release.

### ISSUE THREAD

**Issue by Superyanggod** [flutter/flutter#125087] opened 2023-04-19 02:33 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/18109520/232951426-e354bdae-d554-4483-98d9-f824c8eba682.png)

I only perform the above steps, and an error will also be reported！

### Expected results

Don't report mistakes, release correctly！

### Actual results

An error will be reported. The error message is: A resource failed to call release.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2023-04-19 06:29
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108941. 

Kindly subscribe to the original issue for updates. Please upvote the original issue as well. 

Thank you

**Closed by danagbemava-nc** 2023-04-19 06:29 UTC
Labels: in triage
