### ISSUE TITLE
Use animation to display pictures abnormal on iOS platform 

### ISSUE THREAD

**Issue by AngusPei** [flutter/flutter#63222] opened 2020-08-07 19:27 UTC
## Steps to Reproduce

1. open [A issue Flutter project.](https://github.com/AngusPei/issue_project)

2. Flutter run ./

**Expected results:** 
![2020-08-08 032332](https://user-images.githubusercontent.com/4378435/89680963-96c99780-d926-11ea-91c1-86d3e5e0c405.gif)

**Actual results:** 
![2020-08-08 032528](https://user-images.githubusercontent.com/4378435/89681112-dbedc980-d926-11ea-9978-ff013e2028c2.gif)

<details>
  <summary>Logs</summary>

```
flutter doctor -v

[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on macOS 11.0 20A5323l, locale
    zh-Hans-CN)
    • Flutter version 1.21.0-1.0.pre at /Users/angus/flutter
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/angus/Library/Android/sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (5 available)            
    • iPhone 11 Pro (mobile)             • 468F375E-3F71-48C9-A6B3-DC0B41368118
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • iPad Air (3rd generation) (mobile) • 44B93FB8-7AA1-404F-AF32-04A2B65D9614
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)                    • macos
      • darwin-x64     • macOS 11.0 20A5323l
    • Web Server (web)                   • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome
      • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

## My Code
```dart

class _SidePageState extends State<SidePage>
    with SingleTickerProviderStateMixin {
  Animation<int> _animation;
  AnimationController _animationController;

  int _forward = 0;

  Future<void> _preCacheImage(context) async {
    for (var i = 0; i < 150 + 1; i++) {
      try {
        await precacheImage(
            ImageUtils.getAssetImage('side/side_$i', format: ImageFormat.jpg),
            context);
        debugPrint('assets/images/side/side_$i.jpg');
      } catch (e) {
        debugPrint(e.toString());
      }
    }

    await Provider.of<SideState>(context, listen: false).loadImages();
  }

  @override
  void initState() {
    super.initState();
    Future.delayed(Duration.zero, () {
      _preCacheImage(context).then((value) {
        setState(() {});
      });
    });

    _animationController = new AnimationController(
        duration: const Duration(milliseconds: 500), vsync: this);

    _animation = new IntTween(begin: 0, end: 10).animate(_animationController)
      ..addListener(() {
        setState(() {});
      })
      ..addStatusListener((state) {
        if (state == AnimationStatus.completed) {
          _animationController.reset();
        }
      });
  }

  @override
  void dispose() {
    _animationController?.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).primaryColor,
      appBar: AppBar(
        elevation: 0,
      ),
      body: buildBody(context),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      floatingActionButton: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          FloatingActionButton(
            onPressed: () {
              _forward = -2;
              _animationController.forward();
            },
            heroTag: "right_rotation",
            child: Container(
              child: Image.asset(
                'assets/images/right_rotation.png',
                width: 40,
                height: 40,
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(left: 16.0),
            child: FloatingActionButton(
              heroTag: "left_rotation",
              onPressed: () {
                _forward = 2;
                _animationController.forward();
              },
              child: Container(
                child: Image.asset(
                  'assets/images/left_rotation.png',
                  width: 40,
                  height: 40,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget buildBody(BuildContext context) {
    final size = MediaQuery.of(context).size;
    final width = size.height > size.width ? size.width : size.height;

    return Container(
      child: GestureDetector(
        behavior: HitTestBehavior.translucent,

        /// 此处需要细化
        onPanUpdate: (DragUpdateDetails details) {
          if (details.delta == Offset.zero) return;

          int forward = details.delta.dx ~/ 10;

          if (forward.abs() < 4) {
            forward = (details.delta.dx < 0 ? 4 : -4);
          } else if (forward.abs() < 15) {
            forward = (details.delta.dx < 0 ? 6 : -6);
          } else {
            forward = (details.delta.dx < 0 ? 8 : -8);
          }

          _forward = forward;
          _animationController.forward();
          setState(() {});
        },
        child: Container(
          width: double.infinity,
          height: double.infinity,
          child: Center(
            child: _buildPlayAnimation(width),
          ),
        ), //        child: Container(
      ),
    );
  }

  _buildPlayAnimation(double width) {
    return AnimatedBuilder(
      animation: _animation,
      builder: (BuildContext context, Widget child) {
        int frame =
            Provider.of<SideState>(context, listen: false).frame(_forward);
        if (SideState.images.length > frame) {
          debugPrint('assets/images/side/side_$frame.jpg');

          return Container(
            width: width,
            height: width,
            key: ValueKey('side_$frame'),
//            decoration: BoxDecoration(
//                color: Colors.purple,
//                image: DecorationImage(
//                    image: ImageUtils.getAssetImage('side/side_$frame',
//                        format: ImageFormat.jpg),
//                    fit: BoxFit.fill)),
            child: Image.memory(
              SideState.images[frame].buffer.asUint8List(),
              width: width,
              height: width,
              gaplessPlayback: true,
            ),
          );
        } else {
          debugPrint('err: assets/images/side/side_$frame.jpg');
          return Container(
            width: width,
            height: width,
          );
        }
      },
    );
  }
}

```

**Comment by AngusPei** [comment] 2020-08-08 05:19
image info : 1920x1440 JPEG(24-bit color) 200 kb

Is there any other way?

**Comment by itssidhere** [comment] 2020-08-09 07:33
It's happening in Android too translation animations using animated container in V1.20

**Comment by itssidhere** [comment] 2020-08-09 07:40
I think it's related #63218

**Comment by PrinzKenny1** [comment] 2020-08-09 07:54
> I think it's related to #63218

Yes it's actually the same issue. One way to bypass this problem is defining a variable in initstate with the memory image and that should fix the issue. My guess is that flutter needs to reload the image from the list again and again, because the array could be modified I guess?

Another bypass is to set the option gaplessPlayback in the Image widget to true, therefore the old image stays until the image is loaded again(but I wouldnt recommend this solution firstly because you dont always have an Image Widget where you need a MemoryImage Provider and secondly it could possibly affect the performance if its still needs to rebuild the image.

**Comment by itssidhere** [comment] 2020-08-09 08:00
Hope, it gets fixed soon . The performance difference is quiet noticable when you have 20-30 widgets which are animating. Downgrading to 1.17.5 works for now.

**Comment by Rudiksz** [comment] 2020-08-10 02:44
This code is very inefficient and it's no surprised you get jank.

A few useful tips:
1) Check out the 'child' parameter of the AnimatedBuilder
https://api.flutter.dev/flutter/widgets/AnimatedBuilder-class.html

> If your builder function contains a subtree that does not depend on the animation, it's more efficient to build that subtree once instead of rebuilding it on every animation tick.

Since you are using provider and you seem to paint a different image on every frame I'm not sure it will be useful, but it's the most important optimization you can do in this case.

2) You are needlessly rebuilding you whole screen on every animation tick. This will seriously slow down your app even for simple widgets, let alone large images. Splitting up your screen in smaller widgets and rebuilding only the part of the UI that actually changes is very important in Flutter.

3) I'm not sure if you tried release mode yet. In my experience debug mode can be many factors slower than profile/release mode and it's not indicative of the actual performance you will get.

**Comment by TahaTesser** [comment] 2020-08-10 12:16
Hi @AngusPei 
Please follow https://github.com/flutter/flutter/issues/63222#issuecomment-671140220 suggestions

If the problem still persist, Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample without using provider 
Thank you

**Comment by itssidhere** [comment] 2020-08-11 06:51
With multiple widgets there are some performance degradation please have a look into this @TahaTesser . I have experimented with translation animation and they are much more janky than 1.17.5

**Comment by itssidhere** [comment] 2020-08-11 07:00
> Hope, it gets fixed soon . The performance difference is quiet noticable when you have 20-30 widgets which are animating. Downgrading to 1.17.5 works for now.

@TahaTesser  you can try to animate 20-30 containers having decoration image with translation animation and you will notice the difference between 1.20.1 vs 1.17.5

**Comment by darshankawar** [comment] 2020-09-02 10:21
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-02 10:21 UTC
Labels: in triage, waiting for customer response
