### ISSUE TITLE
Why web-flutter run under `chrome-incognito` mode every time? It causes the SDK re-download every time, which is inefficient and dangerous for those people under National-Fire-Wall who can't visit google easily.

### ISSUE THREAD

**Issue by yingshaoxo** [flutter/flutter#121981] opened 2023-03-06 02:33 UTC
Why don't you guys let it run under normal chrome, so that web-flutter could use cached flutter-web-sdk.

**Comment by Neurs12** [comment] 2023-03-06 03:18
Please provide more information about your problem, run this command and post the output:
```
flutter doctor -v
```
For my experience: Flutter web on debug always runs in non-incognito mode, and Web SDK only re-download after an update or the SDK doesn't exist.

Maybe some of your configuration could cause that behaviour.

**Comment by dexprexxtion** [comment] 2023-03-06 06:50
I often use Flutter to develop for the web and on debug, it always runs as a new Chrome window, signed out from any google accounts and in non-incognito mode. As @Neurs12 said, there is a chance your configuration is causing this.

**Comment by yingshaoxo** [comment] 2023-03-06 07:43
I'm using MacOS M1

It's a stupid close-mind system, this problem may only happens in this type
of system.

Sorry for the disturbing.

**Comment by Neurs12** [comment] 2023-03-06 07:45
I don't think that macos caused this issue...

**Comment by dexprexxtion** [comment] 2023-03-06 08:36
@yingshaoxo 
Even if you think that macOS is causing this, are you sure this happens only on M1 or all across macOS? Perhaps you should try reinstalling flutter in case you're having flutter web errors

**Comment by exaby73** [comment] 2023-03-06 11:42
Hello @yingshaoxo. This is working as expected and is a duplicate of https://github.com/flutter/flutter/issues/43809. Therefore, I will close this issue. Thank you

**Closed by exaby73** 2023-03-06 11:42 UTC
Labels: in triage
