### ISSUE TITLE
[web] iOS Safari random crashes/white frame

### ISSUE THREAD

**Issue by peerwaya** [flutter/flutter#84832] opened 2021-06-18 04:58 UTC
I recently built an app on flutter web using the latest master and I am experiencing random white screens or crashes when tapping around, see the link here [App](https://dev.web.gotok.app)

https://user-images.githubusercontent.com/14053870/122508583-18378f00-cffa-11eb-8d39-8b6ba60930b5.MP4

Flutter Doctor
```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.390, on Mac OS X 10.15.7 19H105 darwin-x64, locale
    en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.0)
[✓] Connected device (2 available)
```

**Comment by darshankawar** [comment] 2021-06-18 09:41
@peerwaya 
Can you provide the crash log it generates ? Is the behavior replicable locally in debug mode or in release mode ?
Can you also provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example
) that we can use that shows the crashes ?

**Comment by peerwaya** [comment] 2021-06-18 10:11
This is currently running in release mode, no crash log. happens randomly.

**Comment by peerwaya** [comment] 2021-06-18 10:12
You can try the latest gallery app in release mode  on the latest master running on ios safari

**Comment by darshankawar** [comment] 2021-06-18 11:30
I tried the gallery [app](https://github.com/flutter/gallery) and ran it in release mode using latest master and opened it in safari browser. Clicked through the app features but don't seem to get any crash / white frames.

<img width="1202" alt="Screenshot 2021-06-18 at 4 58 34 PM" src="https://user-images.githubusercontent.com/67046386/122554419-9590ed00-d056-11eb-940b-448affebf1c8.png">

**Comment by peerwaya** [comment] 2021-06-18 12:35
Hi @darshankawar , please run it on iOS safari not desktop safari, I am working on a minimum sample

**Comment by peerwaya** [comment] 2021-06-23 06:52
Here is a minimum sample

```
import 'package:animations/animations.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/link.dart';

void main() {
  runApp(const MyApp());
}

const url = 'https://google.com';

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _selectedIndex = 0;
  final PageStorageBucket bucket = PageStorageBucket();

  final List<Widget> pages = const [
    Page1(),
    Page2(),
  ];

  Widget _bottomNavigationBar(int selectedIndex) => SafeArea(
        child: BottomNavigationBar(
          onTap: (int index) => setState(() => _selectedIndex = index),
          currentIndex: selectedIndex,
          items: const [
            BottomNavigationBarItem(
                icon: Icon(Icons.local_dining), label: 'Page1'),
            BottomNavigationBarItem(
                icon: Icon(Icons.assignment), label: 'Page2'),
          ],
        ),
        bottom: true,
      );

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.amber,
      body: PageTransitionSwitcher(
        transitionBuilder: (
          Widget child,
          Animation<double> animation,
          Animation<double> secondaryAnimation,
        ) {
          return FadeThroughTransition(
            animation: animation,
            secondaryAnimation: secondaryAnimation,
            child: child,
            fillColor: Colors.amber,
          );
        },
        child: KeyedSubtree(
          key: ValueKey(_selectedIndex),
          child: pages[_selectedIndex],
        ),
      ),
      bottomNavigationBar: _bottomNavigationBar(
          _selectedIndex), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class Page1 extends StatelessWidget {
  const Page1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Page 1'),
      ),
      backgroundColor: Colors.amber,
      body: const SizedBox.expand(
        child: Center(
          child: Text('Empty Page'),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  const Page2({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Page 2'),
      ),
      backgroundColor: Colors.amber,
      body: Center(
        child: Link(
          uri: Uri.parse(url),
          target: LinkTarget.blank,
          builder: (context, onPressed) {
            return ElevatedButton(
                onPressed: onPressed, child: const Text('Button 2'));
          },
        ),
      ),
    );
  }
}
```

**Comment by peerwaya** [comment] 2021-06-23 06:58
I noticed this happens with a Link Widget or something with a Platform view underneath on web especially iOS Safari. It's not so noticeable on chrome. It is fine on stable channel but It seems to have started after the slots refactor done by @ditman. @ditman what do you think?


https://user-images.githubusercontent.com/14053870/123050643-d2fbce80-d3f8-11eb-835a-78c47a3ae835.MP4

**Comment by peerwaya** [comment] 2021-06-23 09:45
To see the effect, try switching the tabs

**Comment by darshankawar** [comment] 2021-06-25 06:49
Thanks for putting effort to come up with minimal code sample and further details around it. Although I wasn't able to replicate it in debug and release mode using both renderers after running the code sample on iOS safari browser (version 14.4.1), may be it is replicable after deploying it on server.

Keeping it open for further insights from the team.

Cc: @yjbanov

**Comment by peerwaya** [comment] 2021-06-25 07:36
I am running 

![image](https://user-images.githubusercontent.com/14053870/123388168-661b3c80-d590-11eb-8cf3-23c55b4b38bb.png)

**Comment by peerwaya** [comment] 2021-06-26 11:41
@ditman is there a possibility this could be related to #80524 ? I started noticing this after migrating to the latest master with HTML slots. without the use of Link widget it works normally on iOS safari. The link widget uses a platform view for web. Also, how can I disable the HTML slots feature so I can test without slots?

**Comment by ditman** [comment] 2021-06-28 20:47
> how can I disable the HTML slots feature so I can test without slots?

You can switch to flutter `stable`, slots haven't landed there yet. (Maybe `beta` either)

I'll take a look at this asap!

**Comment by ditman** [comment] 2021-06-28 21:17
This also happens in MacOS Safari:

https://user-images.githubusercontent.com/1255594/123705151-6713ce80-d81b-11eb-9c9f-ec2d22990abc.mov

It seems to be related to the moment where the platform view is deleted from the DOM (maybe it gets cleared before its slot and safari doesn't like it?)

**Comment by peerwaya** [comment] 2021-06-30 08:08
is it possible to fallback to the implementation without slots for safari as a temporary workaround?

**Comment by ditman** [comment] 2021-06-30 20:14
@peerwaya use flutter channel `master` for that, until we land the workaround.

**Comment by ditman** [comment] 2021-06-30 22:29
I've reproduced the white page in development mode, locally, and with canvaskit rendering.

This is good news, because it probably means that this is a ShadowDOM Safari bug. I'm diving deeper.

**Comment by ditman** [comment] 2021-07-01 00:51
OK, I think I've minimally reproduced the issue (without flutter web). Here's the link:

https://jsfiddle.net/ditman/rmwqjLah

If you visit that fiddle in Safari, the end result will be a "red" screen, but if you use Chrome, the end result will be "green".

I hope the JS code is easy to understand; I'll create a bug for Safari ASAP, but first I'll try to implement a mitigation strategy into flutter. We have two options:

1. Delete the "slotted" content *before* the slot itself. This could be a permanent fix, but I need to dive deeper in the ordering of the flutter events regarding web views.
2. Never delete the root container of the "slotted" content (this will seem like a "DOM node leak" from the outside, but this would be a temporary fix until Safari gets fixed).
3.

**Comment by ditman** [comment] 2021-07-03 00:02
We have a workaround for this that doesn't leave DOM nodes hanging. Deleting the slotted content before the slot was not practical, due to how flutter rendering pipeline works.

**Comment by ditman** [comment] 2021-07-03 01:08
The underlying issue has been reported to Webkit, here:

* [Webkit:227652](https://bugs.webkit.org/show_bug.cgi?id=227652)

**Closed** 2021-07-07 19:06 UTC
Labels: P2, a: platform-views, browser: safari, engine, passed first triage, platform-web

**Comment by ditman** [comment] 2021-07-07 20:26
The fix is rolling into flutter/master here:

https://github.com/flutter/flutter/pull/86036

**Comment by ditman** [comment] 2021-07-07 23:17
The fix has rolled into flutter master successfully.
