### ISSUE TITLE
[video_player] update periodic timer duration to be public

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [flutter/flutter#160855] opened 2024-12-26 03:17 UTC
### Use case

Currently, the code snippet:

```dart
Timer.periodic(
        const Duration(milliseconds: 500),
```

found at [code](https://github.com/flutter/packages/blob/864e6be3ff505afb66e029b93f034e85cc568a49/packages/video_player/video_player/lib/video_player.dart#L590), is configured with a periodic duration of 500 milliseconds. This introduces a delay when using internal captions, as the `Timer` only updates every 500 milliseconds.

In scenarios where subtitles are displayed for a short duration, such as 1 second, this delay can cause captions to either appear late or for an inconsistent duration (e.g., 500 milliseconds or less). This significantly impacts user experience, as subtitles may not align properly with the video, making it difficult for users to follow along.

### Proposal

A potential solution is to expose a setter for the periodic duration. This setter would allow developers to adjust the timer's interval dynamically. When a new duration is provided, the setter would cancel the current timer and create a new one with the updated duration. This flexibility ensures that subtitle timing can be adjusted to match use cases requiring finer granularity, significantly improving the user experience by reducing delays and ensuring accurate subtitle display.

**Comment by stuartmorgan** [comment] 2024-12-26 15:44
This is essentially a duplicate of https://github.com/flutter/flutter/issues/90080; see the last comment there for a link to discussion in a previous PR proposing this.

**Closed by stuartmorgan** 2024-12-26 15:44 UTC
