### ISSUE TITLE
 When the exception was thrown, this was the stack:

### ISSUE THREAD

**Issue by kafeishaonian** [flutter/flutter#31110] opened 2019-04-16 06:10 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by Butzlabben** [comment] 2019-04-16 09:21
Please provide the error log and your code.

**Comment by timsneath** [comment] 2019-04-17 01:29
Closing due to lack of content. Please reopen if you have more information to add! Thanks.

**Closed by timsneath** 2019-04-17 01:29 UTC

**Comment by Ronakgadhia** [comment] 2019-07-11 06:53
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
2019-07-11 12:18:40.535 2945-3011/com.example.login_flutter I/flutter: The following assertion was thrown while handling a gesture:
2019-07-11 12:18:40.535 2945-3011/com.example.login_flutter I/flutter: Navigator operation requested with a context that does not include a Navigator.
2019-07-11 12:18:40.535 2945-3011/com.example.login_flutter I/flutter: The context used to push or pop routes from the Navigator must be that of a widget that is a
2019-07-11 12:18:40.535 2945-3011/com.example.login_flutter I/flutter: descendant of a Navigator widget.
2019-07-11 12:18:40.537 2945-3011/com.example.login_flutter I/flutter: **When the exception was thrown, this was the stack:**
2019-07-11 12:18:40.547 2945-3011/com.example.login_flutter I/flutter: #0      Navigator.of.<anonymous closure> (package:flutter/src/widgets/navigator.dart:1449:9)
2019-07-11 12:18:40.547 2945-3011/com.example.login_flutter I/flutter: #1      Navigator.of (package:flutter/src/widgets/navigator.dart:1456:6)
2019-07-11 12:18:40.547 2945-3011/com.example.login_flutter I/flutter: #2      Navigator.pushNamed (package:flutter/src/widgets/navigator.dart:877:22)
2019-07-11 12:18:40.548 2945-3011/com.example.login_flutter I/flutter: #3      TabLayoutDemo.build.<anonymous closure> (package:login_flutter/tabbarbottom.dart:109:49)
2019-07-11 12:18:40.548 2945-3011/com.example.login_flutter I/flutter: #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
2019-07-11 12:18:40.548 2945-3011/com.example.login_flutter I/flutter: #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
2019-07-11 12:18:40.548 2945-3011/com.example.login_flutter I/flutter: #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
2019-07-11 12:18:40.549 2945-3011/com.example.login_flutter I/flutter: #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
2019-07-11 12:18:40.549 2945-3011/com.example.login_flutter I/flutter: #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
2019-07-11 12:18:40.549 2945-3011/com.example.login_flutter I/flutter: #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
2019-07-11 12:18:40.549 2945-3011/com.example.login_flutter I/flutter: #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
2019-07-11 12:18:40.550 2945-3011/com.example.login_flutter I/flutter: #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
2019-07-11 12:18:40.550 2945-3011/com.example.login_flutter I/flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
2019-07-11 12:18:40.550 2945-3011/com.example.login_flutter I/flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
2019-07-11 12:18:40.550 2945-3011/com.example.login_flutter I/flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
2019-07-11 12:18:40.551 2945-3011/com.example.login_flutter I/flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
2019-07-11 12:18:40.551 2945-3011/com.example.login_flutter I/flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
2019-07-11 12:18:40.551 2945-3011/com.example.login_flutter I/flutter: #20     _invoke1 (dart:ui/hooks.dart:233:10)
2019-07-11 12:18:40.551 2945-3011/com.example.login_flutter I/flutter: #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
2019-07-11 12:18:40.552 2945-3011/com.example.login_flutter I/flutter: (elided 3 frames from package dart:async)
2019-07-11 12:18:40.556 2945-3011/com.example.login_flutter I/flutter: Handler: onTap
2019-07-11 12:18:40.556 2945-3011/com.example.login_flutter I/flutter: Recognizer:
2019-07-11 12:18:40.556 2945-3011/com.example.login_flutter I/flutter:   TapGestureRecognizer#88d7e(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
2019-07-11 12:18:40.556 2945-3011/com.example.login_flutter I/flutter:   Offset(110.3, 625.0), sent tap down)

**Comment by timsneath** [comment] 2019-07-11 16:11
Thanks. This is operating by design, however. As the earlier lines show, you need a `Navigator` object to send routing commands to. You might want to review: https://flutter.dev/docs/cookbook/navigation/navigation-basics
