### ISSUE TITLE
Failed assertion: line 334 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true

### ISSUE THREAD

**Issue by gauravyadav21** [flutter/flutter#89103] opened 2021-08-28 12:38 UTC
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
'package:flutter/src/rendering/binding.dart': Failed assertion: line 334 pos 12: '!_debugMouseTrackerUpdateScheduled': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

**Comment by TahaTesser** [comment] 2021-08-30 07:06
Hi @gauravyadav21 
This is a duplicate of https://github.com/flutter/flutter/issues/84241

**Closed by TahaTesser** 2021-08-30 07:06 UTC
Labels: in triage
