### ISSUE TITLE
Android Flutter Firebase auth crashing app when app is restarted

### ISSUE THREAD

**Issue by james9181** [flutter/flutter#57767] opened 2020-05-21 23:47 UTC
My app seems to work fine initially, where i can constantly log in and out of different accounts. But if I exit the app by using the back button and reopen the app, trying to sign in and out crashes the app (all other features of the app are fine e.g. firestore access). This gives the following info:

> java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(20520): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$3.onAuthStateChanged(FirebaseAuthPlugin.java:710)
E/AndroidRuntime(20520): 	at com.google.firebase.auth.zzp.run(com.google.firebase:firebase-auth@@19.2.0:3)
E/AndroidRuntime(20520): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(20520): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(20520): 	at com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage(com.google.firebase:firebase-auth@@19.2.0:6)
E/AndroidRuntime(20520): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(20520): 	at android.app.ActivityThread.main(ActivityThread.java:7857)
E/AndroidRuntime(20520): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20520): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(20520): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

If i choose to instead exit the app by viewing all apps running in the background and swiping it away, the app works perfectly fine again and I can log in and out without crashing. Any help would be appreciated as I'm still pretty new with flutter/firebase

**Comment by iapicca** [comment] 2020-05-22 06:23
Hi @james9181 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-05-22 06:23 UTC
