### ISSUE TITLE
xcode_backend.sh build failure

### ISSUE THREAD

**Issue by IronMan-I** [flutter/flutter#84968] opened 2021-06-21 09:07 UTC
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build

## command

/Users/xx/Documents/development_stable/flutter/bin/flutter --verbose assemble --output=/Users/xx/flutter/baidu/netdisk/note/flutter_plugins_host/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=release -dIosArchs=armv7 arm64 -dSdkRoot= -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=false -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= release_ios_bundle_flutter_assets

## exception

<details> 
<summary>logs</summary> 
	
```console
Target release_unpack_ios failed: Exception: No iOS frameworks found in
           /Users/xx/Documents/development_stable/flutter/bin/cache/artifacts/engine/ios-release/Flutter.xcframework
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _getIosEngineArtifactPath (package:flutter_tools/src/artifacts.dart:567:5)
           #2      CachedArtifacts._getIosArtifactPath (package:flutter_tools/src/artifacts.dart:324:16)
           #3      CachedArtifacts.getArtifactPath (package:flutter_tools/src/artifacts.dart:268:16)
           #4      UnpackIOS.build (package:flutter_tools/src/build_system/targets/ios.dart:280:51)
           #5      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:27)
           <asynchronous suspension>
           #6      Future.wait.<anonymous closure> (dart:async/future.dart)
           <asynchronous suspension>
           #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
           <asynchronous suspension>
           #8      Future.wait.<anonymous closure> (dart:async/future.dart)
           <asynchronous suspension>
           #9      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
           <asynchronous suspension>
           #10     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
           <asynchronous suspension>
           #11     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
           <asynchronous suspension>
           #12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #16     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #19     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #21     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #22     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #24     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #25     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #26     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +20 ms] "flutter assemble" took 41,834ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:237:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

</details>

## flutter doctor

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.6 at /Users/xxx/Documents/development_stable/flutter
    • Framework revision 1d9032c7e1 (7 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/xx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • IPhone (mobile) • 00008030-001D350C2E80802E • ios            • iOS 14.2
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>

**Comment by hamad22h** [comment] 2021-06-21 09:08
-

**Comment by TahaTesser** [comment] 2021-06-21 15:18
Hi @IronMan-I 
Can you please upgrade to the latest  `stable` and try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`


If the problem persists, can you please provide your `flutter doctor -v` with the upgrade, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by jmagman** [comment] 2021-06-23 01:11
Duplicate of https://github.com/flutter/flutter/issues/68475.

**Closed by jmagman** 2021-06-23 01:11 UTC
Labels: in triage, waiting for customer response
