### ISSUE TITLE
"webView Package"  post request not working on ios.

### ISSUE THREAD

**Issue by pc425** [flutter/flutter#135203] opened 2023-09-21 05:09 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

below i explained, please read it.

### Expected results

Expected logs should be this: (and i am getting this result in inAppWebView package.) 
```
flutter: 1 https://domain.com/OD_SessionBuilder.aspx // first it loads base_url
flutter: 3 30
flutter: 3 49
flutter: 3 85
flutter: 3 100
flutter: 2 https://domain.com/domain-route/CustomerPortal.aspx // then load expected pages
```

### Actual results

but in flutter webView it is giving me this:

```
flutter: 1 https://online.bosch-pharma.com/OD_SessionBuilder.aspx // as usual first it loads base_url
flutter: 2 null // here you can see next/expected url getting null.
```

### Code sample

<details><summary>Code sample</summary>

```
initWebView () async {
    // this is the body query for post request
    var myUrlQuery = "UserID=test&pass=test&location=11";
    
    webViewController
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(NavigationDelegate(
        onProgress: (int progress) {
          debugPrint("$progress");
        },
        onUrlChange: (UrlChange? val){
          debugPrint("changed URL ${val?.url.toString()}");
        },
        onNavigationRequest: (NavigationRequest request) {
          List<String> components = request.url.split("/");
          if (components.last == "Default.aspx") {
            // here i set logic for log_out, when ever if url change and the last end-point is "Default.aspx" it should logged out.
          }

          if(components.last == "CustomerPortal.aspx"){
            // this indicating that page has been loaded successfully when end-point is "CustomerPortal.aspx".
          }

          if(components.last == "OD_SessionBuilder.aspx"){
            // its means nothing happened, url not changed, because "OD_SessionBuilder.aspx" is already my base url end-point.
          }
          return NavigationDecision.navigate;
        },
        onPageFinished: (String url) {
          // here i am displaying my webView.
        },
      ..loadRequest(
          Uri.parse('https://domain.com/OD_SessionBuilder.aspx'), // see here end-point i was talking about.
          method: LoadRequestMethod.post,
          body: Uint8List.fromList(myUrlQuery.codeUnits)
      );
  }
```
Hope you got my point, this is my simple code when i run in android device it works properly and load all expected pages, but in ios it is not loading other pages just stuck after loading base_url, and also i tried same loginc on different package (inAppWebView) and it is working properly.

```
flutter: url changed: https://domain.com/OD_SessionBuilder.aspx // first time this url hit, because it is base url
// on below i am storing all coming url's end-points, and you can see here it give only base url which i already provided, it should get all urls, from base url to dashboard pages url's.
flutter: In NavigationRequest Method Components: [https:, , domaiin.com, OD_SessionBuilder.aspx]
// see below here second time when base-url done there no other urls of next pages...
flutter: url changed: null
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.0 22A380 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by danagbemava-nc** [comment] 2023-09-21 08:56
Please do file multiple issues for the same bug. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/135092

**Closed by danagbemava-nc** 2023-09-21 08:56 UTC
Labels: in triage
