### ISSUE TITLE
[go_router] add a way to insert a widget below the Navigator

### ISSUE THREAD

**Issue by leoshusar** [flutter/flutter#103009] opened 2022-05-04 01:26 UTC
## Use case
I would like to create a `DialogManager` widget that would exist just below the navigator. That manager would listen for calls from `DialogService`. This way I would be able to show dialogs from my business logic without needing a `BuildContext`.
(inspired [here](https://medium.com/flutter-community/manager-your-flutter-dialogs-with-a-dialog-manager-1e862529523a))

If I didn't miss anything, the only workaround I came up with is to create my own `Navigator` either inside the `navigatorBuilder` or the `MaterialApp.router::builder`, but this is not great solution *and* it breaks the back button - it doesn't pop the dialog, it pops the page under it.

## Proposal
Maybe add another `builder` as a `GoRouter` parameter that would be built somewhere under the `Navigator`. This way I could have something like this:
```dart
GoRouter(
  underNavigatorBuilder: (context, child) => DialogManager(child: child),
  ...
)
```

EDIT: I've just found a better workaround than using custom `Navigator`. I can pass `GoRouter::routerDelegate.navigatorKey` to my `DialogManager` and then use `navigatorKey.currentContext!` inside the manager to show the dialog.
Although this works for this particular use case, I still wonder if my initial builder idea would somehow be possible.

<details>
  <summary>Non working example using `DialogManager`</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final _dialogService = DialogService(); // in prod will be injected using DI

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  final router = GoRouter(
    // navigatorBuilder: (context, state, child) => DialogManager(child: child), // this doesn't work either, it's still above the `Navigator`
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) => const HomePage(),
      ),
    ],
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      builder: (context, child) => DialogManager(child: child ?? const SizedBox.shrink()),
      routeInformationParser: router.routeInformationParser,
      routerDelegate: router.routerDelegate,
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          child: const Text('Show dialog'),
          onPressed: () => _dialogService.showDialog(),
        ),
      ),
    );
  }
}

class DialogManager extends StatefulWidget {
  final Widget child;

  const DialogManager({Key? key, required this.child}) : super(key: key);

  @override
  State<DialogManager> createState() => _DialogManagerState();
}

class _DialogManagerState extends State<DialogManager> {
  @override
  void initState() {
    super.initState();
    _dialogService.registerDialogListener(_showDialog);
  }

  @override
  Widget build(BuildContext context) => widget.child;

  Future<void> _showDialog() {
    return showDialog(context: context, builder: (context) => const AlertDialog(title: Text('Dialog')));
  }
}

class DialogService {
  Function? _showDialogListener;

  void registerDialogListener(Function listener) {
    _showDialogListener = listener;
  }

  Future<void> showDialog() async {
    _showDialogListener?.call();
  }
}
```

</details>

<details>
  <summary>Working example using `router.routerDelegate.navigatorKey.currentContext!` workaround</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final _dialogService = DialogService(); // in prod will be injected using DI

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  final router = GoRouter(
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) => const HomePage(),
      ),
    ],
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      builder: (context, child) {
        _dialogService.initialize(router.routerDelegate.navigatorKey);

        return child ?? const SizedBox.shrink();
      },
      routeInformationParser: router.routeInformationParser,
      routerDelegate: router.routerDelegate,
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextButton(
          child: const Text('Show dialog'),
          onPressed: () => _dialogService.show(),
        ),
      ),
    );
  }
}

class DialogService {
  late GlobalKey<NavigatorState> _navigatorKey;

  void initialize(GlobalKey<NavigatorState> navigatorKey) {
    _navigatorKey = navigatorKey;
  }

  Future<void> show() async {
    showDialog(context: _navigatorKey.currentContext!, builder: (_) => const AlertDialog(title: Text('Dialog')));
  }
}
```

</details>

**Comment by maheshmnj** [comment] 2022-05-04 05:27
Hi @leoshusar, Thanks for filing the issue. Can you please share a minimal code sample that shows the problem with the current Go router apis?

**Comment by maheshmnj** [comment] 2022-05-05 06:47
Thanks for the code sample @leoshusar, I do get the exception when trying to show the dialog. I think this is by design How routing works with flutter, Every descendant Widget must have a Navigator parent. However, I do not have solid reasoning for this. I leave this open for secondary triage's input on this.

Code sample can be found in the [original post](https://github.com/flutter/flutter/issues/103009#issue-1224839612)

<details>
<summary>logs</summary>

```
Restarted application in 123ms.
Error: Navigator operation requested with a context that does not include a Navigator.
The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
    at Object.throw_ [as throw] (http://localhost:55549/dart_sdk.js:5067:11)
at http://localhost:55549/packages/flutter/src/widgets/widget_inspector.dart.lib.js:20074:21
at Function.of (http://localhost:55549/packages/flutter/src/widgets/widget_inspector.dart.lib.js:20077:26)
at Object.showDialog (http://localhost:55549/packages/flutter/src/material/dialog.dart.lib.js:1399:97)
at main._DialogManagerState.new.[_showDialog] (http://localhost:55549/packages/newapp/main.dart.lib.js:478:21)
    at Object._checkAndCall (http://localhost:55549/dart_sdk.js:5274:16)
    at Object.dcall (http://localhost:55549/dart_sdk.js:5279:17)
at main.DialogService.new.showDialog (http://localhost:55549/packages/newapp/main.dart.lib.js:505:34)
    at showDialog.next (<anonymous>)
    at runBody (http://localhost:55549/dart_sdk.js:40590:34)
    at Object._async [as async] (http://localhost:55549/dart_sdk.js:40621:7)
at main.DialogService.new.showDialog (http://localhost:55549/packages/newapp/main.dart.lib.js:502:20)
at http://localhost:55549/packages/newapp/main.dart.lib.js:389:177
at ink_well._InkResponseState.new.[_handleTap] (http://localhost:55549/packages/flutter/src/material/icon_button.dart.lib.js:40468:31)
at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:55549/packages/flutter/src/gestures/recognizer.dart.lib.js:190:18)
at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:55549/packages/flutter/src/gestures/tap.dart.lib.js:409:40)
at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:55549/packages/flutter/src/gestures/tap.dart.lib.js:217:12)
at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:55549/packages/flutter/src/gestures/tap.dart.lib.js:166:23)
at tap.TapGestureRecognizer.new.handleEvent (http://localhost:55549/packages/flutter/src/gestures/recognizer.dart.lib.js:426:16)
at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:55549/packages/flutter/src/gestures/pointer_router.dart.lib.js:86:9)
at http://localhost:55549/packages/flutter/src/gestures/pointer_router.dart.lib.js:112:26
    at LinkedMap.new.forEach (http://localhost:55549/dart_sdk.js:27679:11)
at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:55549/packages/flutter/src/gestures/pointer_router.dart.lib.js:110:29)
at pointer_router.PointerRouter.new.route (http://localhost:55549/packages/flutter/src/gestures/pointer_router.dart.lib.js:105:37)
at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:55549/packages/flutter/src/gestures/binding.dart.lib.js:364:26)
at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:55549/packages/flutter/src/gestures/binding.dart.lib.js:352:24)
at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:55549/packages/flutter/src/rendering/layer.dart.lib.js:5427:13)
at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:55549/packages/flutter/src/gestures/binding.dart.lib.js:328:14)
at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:55549/packages/flutter/src/gestures/binding.dart.lib.js:302:43)
at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:55549/packages/flutter/src/gestures/binding.dart.lib.js:292:14)
at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:55549/packages/flutter/src/gestures/binding.dart.lib.js:283:54)
    at Object.invoke1 (http://localhost:55549/dart_sdk.js:190405:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:55549/dart_sdk.js:171081:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:55549/dart_sdk.js:171963:49)
    at http://localhost:55549/dart_sdk.js:172401:28
    at http://localhost:55549/dart_sdk.js:172357:16
    at loggedHandler (http://localhost:55549/dart_sdk.js:172062:11)

```
</details> 

cc: @chunhtai

**Comment by leoshusar** [comment] 2022-05-05 21:04
Hi, thanks for your suggestion.
This is kinda similar to my current "workaround", however I still don't feel like this is the cleanest solution.
I mean - it's not a big deal, passing a context using a navigator key, but I still think "the clean way" would be having something under the navigator.

I'll keep this open and if you feel like it's not something you'd like to implement, feel free to close this and I'll keep using the workaround. It's after all just a single initialization line hidden in `main.dart`.

**Comment by chunhtai** [comment] 2022-05-05 21:17
I don't think the feature request you proposed is feasible. The navigator is a big wrapper over Overlay widget. What you really want is a widget below Overlay. However, the overlay is widget that contains multiple overlayEntries. So unless the inserted widget wraps every overlayEntry, there isn't a way to insert a widget between Overlay and its overlayentry.

If you do wraps all  overlay entry, you may as well create a custom page that builds the dialog manager at the top.

I am going to close this as invalid.

**Closed by chunhtai** 2022-05-05 21:17 UTC
Labels: p: first party, f: routes, package, proposal, p: go_router
