### ISSUE TITLE
D/FlutterActivityAndFragmentDelegate( 3465): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.

### ISSUE THREAD

**Issue by ramtinq** [flutter/flutter#54025] opened 2020-04-05 02:02 UTC
I'm recently seeing these new errors (are these errors?!) in my Android Studio's console when trying to run my app in Android emulator.

`Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
D/FlutterActivity( 3465): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 3465): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 3465): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate( 3465): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView( 3465): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@7585558
D/FlutterActivityAndFragmentDelegate( 3465): Executing Dart entrypoint: main, and sending initial route: /
Debug service listening on ws://127.0.0.1:58353/pd7W03EjaRM=/ws
Syncing files to device Android SDK built for x86...`

flutter doctor:
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!`

The strange thing is that I hadn't seen these errors before, and now they appear even when opening my project's backups!

**Comment by codermihirpaldhikar** [comment] 2020-04-05 08:32
Hello, @ramtinq try running flutter upgrade and flutter pub upgrade 

let me know if the error continues
Happy Coding!!

**Comment by developeralp** [comment] 2020-04-05 21:26
Hi, @codermihirpaldhikar I faced with same errors even if I tried your suggestions.. What should I do?

**Comment by codermihirpaldhikar** [comment] 2020-04-06 04:47
Hi, @developeralp have you tried reinstalling the Flutter SDK?

**Comment by VladyslavBondarenko** [comment] 2020-04-06 10:52
Hi @ramtinq 
It's not an error, even not a warning.
If you don't want to see it, you can consider to switch to another channel (I can't see it already in beta when running flutter run --verbose).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-04-06 10:52 UTC

**Comment by ramtinq** [comment] 2020-04-06 11:01
Well, magically it doesn't show up anymore like before! Maybe I've upgraded flutter again. Anyway, I'm sure I haven't done anything special, maybe just updating. Thanks to everyone.

**Comment by developeralp** [comment] 2020-04-06 12:04
okay than thanks :) @VladyslavBondarenko @codermihirpaldhikar

**Comment by sumitrvi** [comment] 2020-04-07 14:03
@VladyslavBondarenko Sorry to say but I'm newer in flutter.This issues crashing my app.how can I avoid this issue without affecting my functionality.
@developeralp Have you resolved this issue.if yes so can you suggest me to resolved this.

**Comment by VladyslavBondarenko** [comment] 2020-04-08 07:12
@sumitrvi are you sure your app is crashing because of this?
please search your case among opened issues or consider to file a new issue, providing your `flutter doctor -v` and logs of `flutter run --verbose`

**Comment by sumitrvi** [comment] 2020-04-08 07:32
@VladyslavBondarenko hey it's resolved you're right. it's not any warning or error.

**Comment by fayaz07** [comment] 2020-04-08 13:37
I faced the same issue after installing [flutter_facebook_login](https://pub.dev/packages/flutter_facebook_login) plugin, actually I missed the configuration in ```AndroidManifest.xml``` file and that was the cause for the issue.

**Comment by sumitrvi** [comment] 2020-04-08 14:55
@fayaz07 As same way I fixed this issue. But because of firebase_auth plugin Issue in ios.
**Error:**localhost Runner[36946]: (Flutter) [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception:
PlatformException(ERROR_INTERNAL_ERROR, An internal error has occurred, print and inspect the error details for more information., null)
If you have any suggestion for the same please give.

**Comment by fayaz07** [comment] 2020-04-08 18:36
Sorry @sumitrvi, I don't have a mac and no knowledge about that

**Comment by netodeolino** [comment] 2020-04-23 11:34
Probably this is proxy problems. Follow these instructions!

https://stackoverflow.com/questions/60466163/d-flutteractivityandfragmentdelegate29168-no-preferred-flutterengine-was-prov/61331375#61331375
