### ISSUE TITLE
Keyboard janky animation on iOS

### ISSUE THREAD

**Issue by delfme** [flutter/flutter#120555] opened 2023-02-12 10:48 UTC
Bottom inset animation is janky and out of sync when opening the keyboard.
cc: @cyanglaz - https://github.com/flutter/engine/pull/39172#issuecomment-1424629420

Tested on latest stable and master 3.8.0-5.0.pre.1, iphone 13 pro, ios 16.1.1

## Steps to Reproduce
Please run this example here:
https://github.com/delfme/flutter-native-text-input-repo

You can disable/enable flutter textfield and native textfield by commenting/uncommenting related lines. Issue occurs with both textfields.

**Expected results:**
When opening keyboard, UI should animate smoothly and stay ahead of the keyboard for the most part of the run.

**Actual results:**
Animation is janky and the first stop is already at the 80% of entire run.

https://user-images.githubusercontent.com/53510751/229340285-b87e84da-74f1-4712-8d09-91dd52a0b93c.MOV

**Debugging:**
Things have changed during these months and latest merges, please read comments below.

https://user-images.githubusercontent.com/53510751/218306966-73a5c60e-841d-4c80-a301-365362afd960.mov

**Flutter doctor:**
 [✓] Flutter (Channel master, 3.8.0-5.0.pre.1, on macOS 12.2 21D49 darwin-arm64, locale en-IT) [!] Android toolchain - develop for Android devices (Android SDK version 31.0.0) ✗ cmdline-tools component is missing Run path/to/sdkmanager --install "cmdline-tools;latest" See https://developer.android.com/studio/command-line for more details. ✗ Android license status unknown. Run flutter doctor --android-licenses to accept the SDK licenses. See https://flutter.dev/docs/get-started/install/macos#android-setup for more details. [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.2) [✓] Connected device (3 available) [✓] HTTP Host Availability

**Comment by delfme** [comment] 2023-02-12 13:22
@CoolDude53 @luckysmg Just noticed that jitters occur also when using flutter textfield. So this might not be due to platform view. Just wondering if it could be related to https://github.com/flutter/engine/pull/37604 

Can you please investigate this on your devices? To open and close keyboard multiple times in a row, just tap textfield and then Send icon.

To test with flutter textfield just enable lines 134-150.

https://user-images.githubusercontent.com/53510751/218312868-30c57029-5977-4731-82cb-5adf4039fbea.MP4

**Comment by CoolDude53** [comment] 2023-02-12 16:43
@delfme I did quite a bit of investigating. Will try to post what I found in more depth tomorrow.

I found that there are two potential problems with the engine:
- For some reason the GC decides it's a good time to do an idle collect right before the first frame of the animation - this almost always takes longer than dart estimates and causes missed frames
- The first 1-3 frames of the animation when the keyboard is showing almost always get dropped because the raster takes too long. This is particularly evident when you have a TextField that has text content in it (type in a letter and then open and close the keyboard and you'll notice it skips the first few frames more frequently and makes the animation look like it's happening too fast)

What I haven't been able to figure out is why the animation is drawn slowly sometimes and fast others. I found it shows too slow without text in the textfield and too fast when there is text in the textfield. I think we should be able to improve the interpolating to better handle skipped frames. I think the engine does something weird with them. At the end of the day, it's a rendering issue that I'm not sure how we'd be able to fix.

**Comment by delfme** [comment] 2023-02-12 17:28
@CoolDude53 I can see your discovery on my device as well 👍 I attach the video, a more severe jank can be seen after I type in “F”.


https://user-images.githubusercontent.com/53510751/218325891-8463b900-5ad0-4803-ae2f-f11175166da4.MOV


@cyanglaz should we move this conversation to https://github.com/flutter/engine/pull/37604 or keep it here? Do you have any idea what the cause of the issue is?

**Comment by jonahwilliams** [comment] 2023-02-12 19:44
> For some reason the GC decides it's a good time to do an idle collect right before the first frame of the animation - this almost always takes longer than dart estimates and causes missed frames

We could try opting into a performance tier using the RAIL API. We do this for page transitions already, curious if it would help here or if we need more settings. See https://github.com/flutter/flutter/blob/527977b6af24c1663fd5864ef0dfea46a8fd4df3/packages/flutter/lib/src/scheduler/binding.dart#L1158 . Maybe we call this at the start and switch into throughput mode?

> The first 1-3 frames of the animation when the keyboard is showing almost always get dropped because the raster takes too long. This is particularly evident when you have a TextField that has text content in it (type in a letter and then open and close the keyboard and you'll notice it skips the first few frames more frequently and makes the animation look like it's happening too fast)

The timeline won't tell you very much here, and in fact the overhead of timeline measurements can sometimes dwarf actual workloads. I would recommend running this in release mode and using Xcode profiling tools to see what the raster thread is doing during these slow frames w/o any interference from observatory

**Comment by exaby73** [comment] 2023-02-13 09:43
Is the jank visible when using `--enable-impeller`?

**Comment by delfme** [comment] 2023-02-13 11:25
@exaby73 yes it is.

**Comment by exaby73** [comment] 2023-02-13 14:14
## Triage report

I can reproduce this issue on an iPhone 12 Pro Max. I wasn't able to get a good recording as it is subtle in my opinion, though noticeable. I think the video OP shared in https://github.com/flutter/flutter/issues/120555#issue-1581209566 does show the jank better.

Code sample (OP provided): https://github.com/delfme/flutter-native-text-input-repo

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[!] Flutter (Channel master, 3.8.0-10.0.pre.34, on macOS 13.2 22D49 darwin-arm64, locale en-US)
    • Flutter version 3.8.0-10.0.pre.34 on channel master at /Users/nabeelparkar/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nabeelparkar/fvm/versions/master. Consider adding /Users/nabeelparkar/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 53fe8a3f94 (74 minutes ago), 2023-02-13 02:37:24 -0500
    • Engine revision 4107a7b71f
    • Dart version 3.0.0 (build 3.0.0-231.0.dev)
    • DevTools version 2.21.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.75.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 6BC61E88-4DE0-4BCB-8599-DA5294269146 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.2 22D49 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Brave Browser 110.1.48.158

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by cyanglaz** [comment] 2023-02-13 17:43
I don't think it is a rendering issue. It looks like the bottom inset is not animating with the same animation curve that the keyboard uses.

**Comment by delfme** [comment] 2023-02-13 19:06
@CoolDude53 do you think it is worth checking whether issue is reproducible with your very first fix? The one where you used hardcoded stops or this formula from CosynPa’s  https://github.com/CosynPa/RevealSpringAnimation/blob/master/RevealSpringAnimation/Math/SpringCurve.swift

As for license, hardcoded stops would be safe to use. But I guess also the spring formula should. I mean, there is Framer’s code and the project itself looks educational.

**Comment by CoolDude53** [comment] 2023-02-13 19:26
@jonahwilliams that's what I was thinking.

Here are the logs when running in profile mode with skia-trace and enable-propeller:
<details>
  <summary>Test 1 - no change to the performance mode</summary>

![Screenshot 2023-02-13 at 12 51 01 PM](https://user-images.githubusercontent.com/5343432/218548210-d0695961-8dc1-4206-8741-9e7c9cfc5eb8.png)
![Screenshot 2023-02-13 at 12 54 51 PM](https://user-images.githubusercontent.com/5343432/218548971-83ae98e4-5298-4efb-8181-dccd03db472b.png)
<img width="1240" alt="Screenshot 2023-02-13 at 1 03 25 PM" src="https://user-images.githubusercontent.com/5343432/218550389-a81000b1-23d8-4396-bb6e-5c87c0ee799a.png">

</details>

**My thoughts** There's no reported raster jank or SceneDisplayLag, but jank is visible - the bottom inset is updated behind schedule. I would think this comes from the GC taking 44ms or ~5 frames on a 120hz device.


Test 2 - using DartPerformanceMode.latency
<img width="885" alt="Screenshot 2023-02-13 at 1 14 30 PM" src="https://user-images.githubusercontent.com/5343432/218552774-296d5d30-e41f-4f9e-86c4-8b231dfae2cf.png">
<img width="112" alt="Screenshot 2023-02-13 at 1 17 35 PM" src="https://user-images.githubusercontent.com/5343432/218552937-a0862a8c-5971-4367-8484-99fe0b94b3d6.png">
<img width="1261" alt="Screenshot 2023-02-13 at 1 11 56 PM" src="https://user-images.githubusercontent.com/5343432/218552819-ef0cbe19-4ee2-4b0b-ae4e-9fcc84fe78f4.png">
<img width="562" alt="Screenshot 2023-02-13 at 1 12 17 PM" src="https://user-images.githubusercontent.com/5343432/218552847-efe3c531-0fec-444a-9754-49104e5000a1.png">

**Comment by CoolDude53** [comment] 2023-02-13 21:09
@jonahwilliams that's what I was thinking. I saw these issues and thought they might be related:
- https://github.com/flutter/flutter/issues/113796
- https://github.com/flutter/flutter/issues/9219

I ran these tests when running in profile mode with skia-trace and enable-propeller on a physical iPhone 14 Pro. I wasn't sure how to use the Xcode profiling tools, but would be happy to rerun these in there if you think it'd give more granularity. For reference, the iOS keyboard animation takes about 0.5 seconds.
<details>
  <summary>Test 1a - no change to the performance mode, no text in TextField</summary>

> The GC idle collect happens at the start of the animation and ~1-2 more times during the animation. No reported jank, but visible jank on app. The GC NotifyIdle is seen in the timeline view.

![Screenshot 2023-02-13 at 12 51 01 PM](https://user-images.githubusercontent.com/5343432/218548210-d0695961-8dc1-4206-8741-9e7c9cfc5eb8.png)
![Screenshot 2023-02-13 at 12 54 51 PM](https://user-images.githubusercontent.com/5343432/218548971-83ae98e4-5298-4efb-8181-dccd03db472b.png)
<img width="1240" alt="Screenshot 2023-02-13 at 1 03 25 PM" src="https://user-images.githubusercontent.com/5343432/218550389-a81000b1-23d8-4396-bb6e-5c87c0ee799a.png">
</details>

<details>
  <summary>Test 1b - no change to the performance mode, text in TextField</summary>

> The GC idle collect happens at the start of the animation and ~1-2 more times during the animation. Reported first frame raster jank and visible jank on app. The GC NotifyIdle is seen in the timeline view (the tiny blimp to the right of the first Vsync call on the second line).
<img width="733" alt="Screenshot 2023-02-13 at 2 36 27 PM" src="https://user-images.githubusercontent.com/5343432/218569740-2a526774-0622-413c-9723-c5b3a5dfc8fc.png">
<img width="103" alt="Screenshot 2023-02-13 at 2 39 19 PM" src="https://user-images.githubusercontent.com/5343432/218569751-87bf2cbe-c2e5-4b09-a9a9-57ac36ef92ca.png">
<img width="1273" alt="Screenshot 2023-02-13 at 2 39 37 PM" src="https://user-images.githubusercontent.com/5343432/218569794-e09ed1a1-fb9e-45a2-a9d4-143205ad2599.png">
<img width="544" alt="Screenshot 2023-02-13 at 2 39 54 PM" src="https://user-images.githubusercontent.com/5343432/218569809-7b55bdbf-53db-45af-af5b-bd17d016e0d3.png">



The top displaylag reports missing 2 vsync transitions, while the bottom reports missing 1.
</details>

<details>
  <summary>Test 2a - using DartPerformanceMode.latency, no text in TextField</summary>

> A new space GC collect happens during the animation with no other GC calls. No reported jank, but jank visible on app (the bottom inset is updated behind schedule).
<img width="846" alt="Screenshot 2023-02-13 at 2 15 21 PM" src="https://user-images.githubusercontent.com/5343432/218565571-162fd321-a059-4f3f-8720-8ffd7ccf4888.png">
<img width="109" alt="Screenshot 2023-02-13 at 2 16 34 PM" src="https://user-images.githubusercontent.com/5343432/218565587-3a2eb61c-dd61-4401-b6bd-7739ee848d4d.png">
<img width="1253" alt="Screenshot 2023-02-13 at 2 16 48 PM" src="https://user-images.githubusercontent.com/5343432/218565599-3610c879-0108-4daf-a686-5ac163fdfcfc.png">

</details> 

<details>
  <summary>Test 2b - using DartPerformanceMode.latency, text in TextField</summary>

> A new space GC collect at the start of the animation with no other GC calls during the animation. There is reported first frame raster jank and jank visible on app. The bottom inset is updated ahead of schedule (the animation goes faster than the native iOS keyboard).
<img width="885" alt="Screenshot 2023-02-13 at 1 14 30 PM" src="https://user-images.githubusercontent.com/5343432/218552774-296d5d30-e41f-4f9e-86c4-8b231dfae2cf.png">
<img width="112" alt="Screenshot 2023-02-13 at 1 17 35 PM" src="https://user-images.githubusercontent.com/5343432/218552937-a0862a8c-5971-4367-8484-99fe0b94b3d6.png">
<img width="1261" alt="Screenshot 2023-02-13 at 1 11 56 PM" src="https://user-images.githubusercontent.com/5343432/218552819-ef0cbe19-4ee2-4b0b-ae4e-9fcc84fe78f4.png">
<img width="562" alt="Screenshot 2023-02-13 at 1 12 17 PM" src="https://user-images.githubusercontent.com/5343432/218552847-efe3c531-0fec-444a-9754-49104e5000a1.png">

The top displaylag reports missing 2 vsync transitions, while the bottom reports missing 1.
</details> 

**Thoughts:** 

- Test 2 prevents the NotifyIdle GC collects by enabling latency mode, but it doesn't stop the GC from collecting during the animation. I'm not sure if there's a way to force the GC to not do it's regular New space scavenger collects. I tried another batch of tests using throughput mode, but those results mimicked Test 1.
- In both a test cases, when there is no text in the TextField, the animation happens behind schedule. With no reported jank, I would think the visual jank comes from the GC and that for some reason the performance monitor doesn't show that as increasing the frame time and reporting jank.
- In both b test cases, when there is text in the TextField, the animation happens ahead of schedule. With reported jank and reported GC collects. The frame analysis knows the raster got hung up on something, but doesn't really report any detail on what. By matching the GC time from the logs, I would think the GC is causing the raster hang and it's just not being reported in the performance view. Both show reported missed frames, but I don't know why the animation happens too quickly - my guess it has something to do with the Vsync transition misses and when the Vsync callbacks are called on a miss.

**Comment by jonahwilliams** [comment] 2023-02-13 21:12
waitForNextDrawable means that the engine is blocking on the GPU being ready, so whatever the cause of the jank it likely has to do with the workload we gave it on the previous frame.

**Comment by CoolDude53** [comment] 2023-02-13 21:19
That would make sense given the gc collect time, but not sure why it's only reported as jank when there's input in the textfield vs empty - the GC times are roughly the same in the a/b of both tests, but the jank is only reported in the b tests.

**Comment by jonahwilliams** [comment] 2023-02-13 21:23
That has to do with the workload of the GPU, not raster or UI threads.

**Comment by CoolDude53** [comment] 2023-02-14 02:13
So I did some more testing to try to isolate what's happening. I made a new build of the engine and stripped out all of the iOS keyboard animation handling and overhead from the FlutterViewController.

I found that the initial GCs don't happen anymore, but there's still some massive raster jank being reported at the beginning of the animation that causes the Vsync to skip frames.

![Screenshot 2023-02-13 at 8 07 19 PM](https://user-images.githubusercontent.com/5343432/218620385-09304c1e-0fc5-4217-bee4-57565d80a2a7.png)
![Screenshot 2023-02-13 at 8 02 21 PM](https://user-images.githubusercontent.com/5343432/218620282-5d17c2c3-a443-4ea9-beb0-091a5d65c6fe.png)

I tried to get some more clarity by using the Xcode debugging tools in release mode. I'm not the most familiar with how to really drill down, but I did find that there's a decent ~10-20ms that seems to be spent on the iOS keyboard PredictionViewController when the keyboard show is triggered. I would think that would be running asynchronously and wouldn't block the raster from drawing, but maybe the engine thinks it needs to wait for that? Grasping at straws ha

**Comment by luckysmg** [comment] 2023-02-14 02:16
Seems like https://github.com/flutter/flutter/issues/103847#issuecomment-1261796761 and seems because engine send data to engine? See https://github.com/flutter/flutter/issues/103847#issuecomment-1128397840
When you close devtools this should not happen^_^

**Comment by luckysmg** [comment] 2023-02-14 02:22
I think we need to triage something to comfirm that the junk is related to platform view or not? Because things get very different when there are platform views in scene.

**Comment by luckysmg** [comment] 2023-02-14 03:26
Did some local testing. The animation seems to be ok on flutter textfield.

But notice very very little laggy (or junk) on platfrom view scene. The laggy (or junk) behavior is not very transparent on my device.

**Comment by CoolDude53** [comment] 2023-02-14 06:48
Did some more testing in the xcode instruments (in release mode w/o any keyboard animation handling in my engine build).

Tried my best to narrow down the slow frames that happen immediately after tapping a TextField and triggering the native keyboard animation. I found that the frames aren't slow because they can't process fast enough, but they're slow because the thread's locked and the raster gets stuck waiting. Here's an example:

<img width="1726" alt="Screenshot 2023-02-14 at 12 39 46 AM" src="https://user-images.githubusercontent.com/5343432/218658875-82e23138-a3b1-4259-9a72-08258928aed3.png">
<img width="1718" alt="Screenshot 2023-02-14 at 12 40 03 AM" src="https://user-images.githubusercontent.com/5343432/218658918-67ad4c87-b9a3-462b-8fe3-9e208579446a.png">

It looks like when you tap a TextField, the MessageLoopDarwin gets triggered (presumably for the FlutterKeyboardManager). I'm not sure what the platform does to start accepting text input, but the below comment makes me believe this input loop gets started and some aspect of that starting creates the jank in the first few frames of the animation. Hoping this is our culprit 😬

https://github.com/flutter/engine/blob/1a8033ce8c7b307287d425f0df66bb8a1abbc2de/shell/platform/darwin/ios/framework/Source/FlutterKeyboardManager.mm#L110-L117

**Comment by delfme** [comment] 2023-02-14 14:52
😊🤞
I will better investigate #120435 so that a fix could land on android as well. This UI layout is pervasive and it is a must have on both platforms.

At first glance it looks like platform view is not the issue there as well. Point is whether it is wrong animation curve or a jittery caused by something else.

**Comment by CoolDude53** [comment] 2023-02-14 17:25
@delfme I imagine the platform implements a similar text listener for android. I agree, it's pervasive enough to warrant an effort to find and fix.

The point of my latest testing was to remove flutter's handling of the keyboard animation from question so as to highlight the underlying performance issue when a selected textfield gets ready to receive text input.

**Comment by delfme** [comment] 2023-03-05 18:38
@CoolDude53 can you please write here your discoveries so far? I mean the ones mentioned in our discord, maybe flutter team can chime in.

**Comment by delfme** [comment] 2023-03-05 18:45
To recap, basically the fix made late past year (merged and closed) addressed only a part of the issue. Animation curve was improved but GC and other issues at engine level prevent the UI to be smooth.

Since this layout is pervasive (messaging screen with a bottom textfield) we hope that can be addressed soon.

https://user-images.githubusercontent.com/53510751/222979457-21851b88-7b76-42cf-a1b0-96634fb9e559.MOV

**Comment by delfme** [comment] 2023-03-05 18:48
I mean this is too bad guys 🤦‍♂️😊 we cannot show this to users.

**Comment by delfme** [comment] 2023-03-05 19:30
Idea: is it doable to listen to a bool which tells the engine whether not to trigger GC? Just as a workaround until we’ll have a real fix. We would set enableGC to false when user lands to this specific screen. 

Because it seems that GC is triggered right when animation starts and that causes the jank and the animation curve to diverse.

**Comment by jonahwilliams** [comment] 2023-03-05 19:49
@delfme see https://github.com/flutter/flutter/issues/120555#issuecomment-1427116082

**Comment by delfme** [comment] 2023-03-05 20:04
> @delfme see [#120555 (comment)](https://github.com/flutter/flutter/issues/120555#issuecomment-1427116082)

@CoolDude53 did you try this as well or just that swift fix?

**Comment by delfme** [comment] 2023-03-05 21:40
@jonahwilliams  
@CoolDude53 seems to have gained a good understanding of the issue. Quick wrote me on discord but will report here too.

For clarity, is flutter team actively working on this? If you guys could prioritize this, that would be much appreciated. We have made a premium app but cannot ship it due to janks respectively in list/grid scrolling, screen animation and keyboard animation. 

Nowadays bar is so high that with this level of janks app would be uninstalled in minutes.

**Comment by jonahwilliams** [comment] 2023-03-05 22:09
Please see https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed

In short, no one is currently assigned to this and it hasn't been prioritized yet.

**Comment by delfme** [comment] 2023-03-06 07:39
Asked due to this:

“Typically, people fix bugs that are relevant to their customers. For example, Google engineers who contribute to Flutter are going to prioritize issues that affect Flutter apps written by Google teams.”


I was just wondering if someone were already assigned to this.

We will try to help here as much as we can. However, can you please discuss my point internally and see if one man can help as well? Apart the understandable desire of seeing a smooth app, janks cause apps to be uninstalled.

**Comment by delfme** [comment] 2023-03-14 21:25
@cyanglaz we just figured out that the 80fps is causing the keyboard animation jank in case of platform view. 

Basically, low fps doesnt allow the engine to catch up with the native animation and makes the two curve diverge.

You already envisioned a solution for this https://github.com/flutter/flutter/issues/119268

Is this going to be available anytime soon? Even a suboptimal alpha solution would be much appreciated!

**Comment by delfme** [comment] 2023-03-14 21:27
Forgot to mentions that the 80fps causes also a jank on screen animation (usually on the very initial frames) because platform view is used in the screen

**Comment by gnprice** [comment] 2023-03-15 03:02
The issue you linked says that 120fps is already the default refresh rate on devices that are capable of it. So if you're seeing a different behavior, that would be good to file as its own issue.

> Basically, low fps doesnt allow the engine to catch up with the native animation and makes the two curve diverge.

This isn't how animations are supposed to work — when running at a lower frame rate, they're supposed to simply advance farther each frame, so that the curve keeps the same shape when plotted in units of real time. So this would be a bug in the animation controller, or the infrastructure underneath it. This would also be good to file as its own issue, with a clear description of how you're observing this effect.

**Comment by delfme** [comment] 2023-03-15 07:57
It was @CoolDude53 seeing the demo working at 80fps on his device.

The code provided above should let testing that as well https://github.com/delfme/flutter-native-text-input-repo/blob/main/lib/demo_screen.dart

To recap the situation:
1) On Feb 7, PR 37604 landed to fix fidely issue with ios animation
https://github.com/flutter/engine/pull/37604
2) However, the fix is not working good and the reason of that seems to be slow frames preventing the engine’s formula at point 1 to advance animation in sync with iOS. Traces and details have been shared above. 
3) Idea from @jonahwilliams was tested but seems to be not effective https://github.com/flutter/flutter/issues/120555#issuecomment-1427116082
4) Idea from @cyanglaz seems correct but looks like it is engine’s janky frames causing the unsync (not the swift formula) https://github.com/flutter/flutter/issues/120555#issuecomment-1428387351
Although the janky frames are the root of the problem, it looks like working at 80fps makes the animation unsyn more evident.

The affected UI layout is pervasive. Any in-app chat screen / customer support screen works with a textfield placed at the bottom of the screen and moving up in sync with the keyboard. 

Any contribution to land a fix for this would be much appreciated.

**Comment by delfme** [comment] 2023-03-15 08:23
@CoolDude53 just to try all the chances of fix already in our hands, can you please try again engine with the formula using fixed stops? Im not sure about that, but not having to calculate stops dynamically might ease the burden of the engine and resolve janks.

**Comment by delfme** [comment] 2023-03-15 13:02
Quick note:

@luckysmg has been so kind to do the test with hardcoded stops, see pic below.

All of them are raster thread junk. So issue is not related with hardcoded stops or not.

![3A12530A-F946-4C01-8493-D24AB3AFC9AD](https://user-images.githubusercontent.com/53510751/225315832-dad4c353-4cea-4a52-92e1-036498467931.png)

@cyanglaz @jonahwilliams any idea on what this could be?

**Comment by luckysmg** [comment] 2023-03-15 13:02
Tested with hardcoded stops. Also see some junk in devtools. So I think it is related with some raster thread work instead of hardcoded stops.

<img src="https://user-images.githubusercontent.com/49340347/225316520-051d16f6-1796-4726-9e2c-e9861b9acd5a.jpg" width=700/>

**Comment by cyanglaz** [comment] 2023-03-15 16:58
> Is this going to be available anytime soon? Even a suboptimal alpha solution would be much appreciated!

I'm not currently actively working on the feature but I think such API could be added straightforwardly in the dart:ui, similar to this: https://github.com/flutter/engine/blob/main/lib/ui/platform_dispatcher.dart#L712

**Comment by delfme** [comment] 2023-03-15 17:12
@cyanglaz wondering if that might also fix the issue with listView/gridView scrolling.

https://github.com/flutter/flutter/issues/121547

If not taking much time, could you please make time to land `requestVariableRefreshRate` or have someone working on that?

**Comment by CoolDude53** [comment] 2023-03-15 17:21
Yes, condensing my debug results from the last month or so:
- spring calculations are fine, performance impact from calculating each frame is fine
- current implementation is as good as we can get using vsync. After investigating, the native iOS animation isn't consistent each run. It appears to be calculated at some time in between each frame and doesn't use the vsync's target time. You can observe this by screen recording a few keyboard animations and examining the difference in keyboard height at frame 1.
- the only solution to getting better fidelity than vsync is using a CFRunLoopObserver, which I've done some testing with but haven't had time to wrap up. I've posted below a ss of a frame during the keyboard present animation. Using a CFRunLoopObserver, we can get closer to the CoreAnimation call time. https://stackoverflow.com/a/15168471

<img width="1728" alt="Screenshot 2023-03-15 at 10 13 26 AM 1" src="https://user-images.githubusercontent.com/5343432/225389395-07d75480-e34a-483a-b81b-980f9626fee9.png">

**Comment by delfme** [comment] 2023-03-15 20:02
@CoolDude53 tested  requestDartPerformanceMode on my iphone 13 pro out of curiosity and in that case doesnt impact much for the good and the bad.

Your discovery would also explain why sometimes animation janks occur when there is no janky frames in the trace. Seems likes CFRunLoopObserver is our best hope.

Anyway, we must fix this. I cannot stress enough how people uninstall janky apps in the blink of an eye. Let alone ios users 🤦‍♂️😄 They first uninstall and then also give the 1 star.

**Comment by delfme** [comment] 2023-03-17 08:27
Quick notice on this.

CoolDude and I are active on the issue. We have come up with another idea we should try before CFRunLoopObserver. In fact, although CFRunLoopObserver might be an improvement, it would still be prone to cause UI tremors in case of a few ms delay.

Idea is to keep the two animations decoupled, this would allow us to have a smooth bottom inset animation.
If we get to keep animation just a few px always-ahead of the keyboard and get it run with a linearEasyOut curve and end its run at the correct coordinate, that would look smooth to eye and with good platform fidelity because it all happens in about 100ms. In a CP scenario, where we have no control over the native side, that would be the safest approach. We know the keyboardHeight (the run) and the duration. Whatever linear-sth curve that works as described above should let us avoid tremors/bumps even if bottom inset animation starts a bit out of sync.

**Comment by delfme** [comment] 2023-04-02 14:25
FYI 🎉https://github.com/flutter/engine/pull/40867

**Comment by delfme** [comment] 2023-04-12 13:18
Unfortunately it seems that Lucky’s latest attempt was not a fix
https://github.com/flutter/engine/pull/40867

Does flutter team have any idea that could be tested? We use to focus our conversation on textfield, but the jank reflects on entire UI and other things will bump and tremble, see vid below. For us, a messenger, this is P0. But many apps have screen layouts where this issue is also visible (comments, auth, profile/account edit, support, etc).

https://user-images.githubusercontent.com/53510751/231467013-04327706-1d1f-452c-95e1-db86965acaba.MOV

**Comment by delfme** [comment] 2023-04-12 15:19
One thought:
By looking at the video of Lucky PR, it seems that the animation is at least fixed there. https://github.com/flutter/engine/pull/40867

I mean that the inset moves up in sync with keyboard.

So, a final fix might be something like “40867 + additional fix to avoid janky frames during animation”.

**Comment by luckysmg** [comment] 2023-04-14 10:24
Linked: https://github.com/flutter/engine/pull/41201

**Comment by delfme** [comment] 2023-04-15 13:29
> Linked: [flutter/engine#41201](https://github.com/flutter/engine/pull/41201)

This is great! 👏
CoolDude is going to help with the fix on android.
It seems that https://github.com/flutter/engine/pull/39391 might not be a fix of all issues.
Also, after changes have been requested, the PR got stalled.

**Closed** 2023-06-20 02:55 UTC
Labels: platform-ios, severe: performance, has reproducible steps, found in release: 3.8

**Comment by cyanglaz** [comment] 2023-07-10 16:26
Fixed with https://github.com/flutter/engine/pull/43463
