### ISSUE TITLE
Unable to run flutter app for ios

### ISSUE THREAD

**Issue by AndreasB115** [flutter/flutter#66223] opened 2020-09-20 17:33 UTC
When I run "flutter clean && flutter run", I'm getting the following errors.

<details> 
<summary>logs</summary> 

```bash
$ _flutter clean && flutter run
Cleaning Xcode workspace...                                         3.2s
Deleting build...                                                   34ms
Deleting .dart_tool...                                               4ms
Deleting Generated.xcconfig...                                       1ms
Deleting flutter_export_environment.sh...                            0ms
Running "flutter pub get" in pm-match-mobile...                     0.6s
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
 
Running pod install...                                             10.8s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           89.3s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-09-20 19:28:35.948 xcodebuild[60279:3001907] warning:  The file reference for "Objective-C/TOCropViewController/Models/TOActivityCroppedImageProvider.h" is a
    member of multiple groups ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will
    be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the
    same path.
    2020-09-20 19:28:35.948 xcodebuild[60279:3001907] warning:  The file reference for "Objective-C/TOCropViewController/Views/TOCropOverlayView.h" is a member of
    multiple groups ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will be
    preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the
    same path.
    2020-09-20 19:28:35.948 xcodebuild[60279:3001907] warning:  The file reference for "Objective-C/TOCropViewController/Models/TOCroppedImageAttributes.h" is a
    member of multiple groups ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will
    be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the
    same path.
    2020-09-20 19:28:35.948 xcodebuild[60279:3001907] warning:  The file reference for "Objective-C/TOCropViewController/Views/TOCropScrollView.h" is a member of
    multiple groups ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will be
    preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the
    same path.
    2020-09-20 19:28:35.948 xcodebuild[60279:3001907] warning:  The file reference for "Objective-C/TOCropViewController/Views/TOCropToolbar.h" is a member of
    multiple groups ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will be
    preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the
    same path.
    2020-09-20 19:28:35.948 xcodebuild[60279:3001907] warning:  The file reference for "Objective-C/TOCropViewController/Views/TOCropView.h" is a member of multiple
    groups ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but
    membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    2020-09-20 19:28:35.948 xcodebuild[60279:3001907] warning:  The file reference for "Objective-C/TOCropViewController/TOCropViewController.h" is a member of
    multiple groups ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will be
    preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the
    same path.
    2020-09-20 19:28:35.948 xcodebuild[60279:3001907] warning:  The file reference for "Objective-C/TOCropViewController/Models/TOCropViewControllerTransitioning.h"
    is a member of multiple groups ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups
    will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference
    to the same path.
    ** BUILD FAILED **


Xcode's output:
↳
    /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-2.2.0/ios/Classes/FlutterInappPurchasePlugin.m:45:52:
    warning: assigning to 'id<IAPPromotionObserverDelegate>' from incompatible type 'FlutterInappPurchasePlugin *__strong'
        [IAPPromotionObserver sharedObserver].delegate = self;
                                                       ^ ~~~~
    /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-2.2.0/ios/Classes/FlutterInappPurchasePlugin.m:200:79:
    warning: implicit conversion loses integer precision: 'SKPaymentTransactionState' (aka 'enum SKPaymentTransactionState') to 'int' [-Wshorten-64-to-32]
                                                         [NSNumber numberWithInt: item.transactionState], @"transactionStateIOS",
                                                         ~                        ^~~~~~~~~~~~~~~~~~~~~
    /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-2.2.0/ios/Classes/FlutterInappPurchasePlugin.m:586:71:
    warning: implicit conversion loses integer precision: 'SKPaymentTransactionState' (aka 'enum SKPaymentTransactionState') to 'int' [-Wshorten-64-to-32]
                                                 [NSNumber numberWithInt: transaction.transactionState], @"transactionStateIOS",
                                                 ~                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 warnings generated.
    In file included from
    /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:9:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h:75:10: warning: "FirebaseAnalytics.framework is not included in your
    target. Please add `Firebase/Analytics` to your Podfile or add FirebaseAnalytics.framework to your project to ensure Firebase Messaging works as intended."
    [-W#warnings]
            #warning "FirebaseAnalytics.framework is not included in your target. Please add \
             ^
    /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:190:43:
    warning: 'FIRMessagingRemoteMessage' is deprecated: FCM direct channel is deprecated, please use APNs for downstream message handling. [-Wdeprecated-declarations]
    - (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage {
                                              ^
    In module 'FirebaseMessaging' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:219:1: note: 'FIRMessagingRemoteMessage'
    has been explicitly marked deprecated here
    __deprecated_msg(
    ^
    In module 'UIKit' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/UIKit.framework/Hea
    ders/UIKit.h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/Foundation.framewor
    k/Headers/Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/CoreFoundation.fram
    ework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/usr/include/sys/cdefs.h:191:48: note:
    expanded from macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:290:24:
    warning: 'FIRMessagingRemoteMessage' is deprecated: FCM direct channel is deprecated, please use APNs for downstream message handling. [-Wdeprecated-declarations]
        didReceiveMessage:(FIRMessagingRemoteMessage *)remoteMessage {
                           ^
    In module 'FirebaseMessaging' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:219:1: note: 'FIRMessagingRemoteMessage'
    has been explicitly marked deprecated here
    __deprecated_msg(
    ^
    In module 'UIKit' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/UIKit.framework/Hea
    ders/UIKit.h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/Foundation.framewor
    k/Headers/Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/CoreFoundation.fram
    ework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/usr/include/sys/cdefs.h:191:48: note:
    expanded from macro '__deprecated_msg'
            #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                          ^
    /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:136:30:
    warning: 'shouldEstablishDirectChannel' is deprecated: FCM direct channel is deprecated, please use APNs channel for downstream message delivery.
    [-Wdeprecated-declarations]
        [FIRMessaging messaging].shouldEstablishDirectChannel = true;
                                 ^
    In module 'FirebaseMessaging' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:283:56: note:
    'shouldEstablishDirectChannel' has been explicitly marked deprecated here
    @property(nonatomic) BOOL shouldEstablishDirectChannel DEPRECATED_MSG_ATTRIBUTE(
                                                           ^
    In module 'UIKit' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/UIKit.framework/Hea
    ders/UIKit.h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/Foundation.framewor
    k/Headers/Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/CoreFoundation.fram
    ework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/usr/include/AvailabilityMacros.h:182:64:
    note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
                #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                                   ^
    /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:191:52:
    warning: 'appData' is deprecated [-Wdeprecated-declarations]
      [self didReceiveRemoteNotification:remoteMessage.appData];
                                                       ^
    In module 'FirebaseMessaging' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:226:62: note: 'appData' has been
    explicitly marked deprecated here
    @property(nonatomic, readonly, strong) NSDictionary *appData DEPRECATED_ATTRIBUTE;
                                                                 ^
    In module 'UIKit' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/UIKit.framework/Hea
    ders/UIKit.h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/Foundation.framewor
    k/Headers/Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/CoreFoundation.fram
    ework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/usr/include/AvailabilityMacros.h:180:60:
    note: expanded from macro 'DEPRECATED_ATTRIBUTE'
            #define DEPRECATED_ATTRIBUTE        __attribute__((deprecated))
                                                               ^
    /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:289:1:
    warning: implementing deprecated method [-Wdeprecated-implementations]
    - (void)messaging:(FIRMessaging *)messaging
    ^
    In module 'FirebaseMessaging' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:253:1: note: method
    'messaging:didReceiveMessage:' declared here
    - (void)messaging:(FIRMessaging *)messaging
    ^
    /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.0/ios/Classes/FLTFirebaseMessagingPlugin.m:291:63:
    warning: 'appData' is deprecated [-Wdeprecated-declarations]
      [_channel invokeMethod:@"onMessage" arguments:remoteMessage.appData];
                                                                  ^
    In module 'FirebaseMessaging' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Headers/Public/Firebase/Firebase.h:72:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FIRMessaging.h:226:62: note: 'appData' has been
    explicitly marked deprecated here
    @property(nonatomic, readonly, strong) NSDictionary *appData DEPRECATED_ATTRIBUTE;
                                                                 ^
    In module 'UIKit' imported from /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/UIKit.framework/Hea
    ders/UIKit.h:8:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/Foundation.framewor
    k/Headers/Foundation.h:6:
    In module 'Darwin' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/System/Library/Frameworks/CoreFoundation.fram
    ework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk/usr/include/AvailabilityMacros.h:180:60:
    note: expanded from macro 'DEPRECATED_ATTRIBUTE'
            #define DEPRECATED_ATTRIBUTE        __attribute__((deprecated))
                                                               ^
    7 warnings generated.
    lib/pages/feed/create_feed.dart:2:8: Error: Not found: 'dart:js'
    import 'dart:js';
           ^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ajs; message=StandardFileSystem only supports file:* and data:* URIs)
    #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:659:37)
    #2      writeDepfile (package:vm/kernel_front_end.dart:853:21)
    <asynchronous suspension>
    #3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:574:15)
    <asynchronous suspension>
    #4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:43:22)
    #5      starter (package:flutter_frontend_server/server.dart:182:27)
    #6      main (file:///b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:9:30)
    #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
    #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/Models/TOActivityCroppedImageProvider.h (in target
    'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/Views/TOCropOverlayView.h (in target
    'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/Models/TOCroppedImageAttributes.h (in target
    'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/Views/TOCropScrollView.h (in target
    'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/Views/TOCropToolbar.h (in target
    'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/Views/TOCropView.h (in target 'TOCropViewController'
    from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/TOCropViewController.h (in target
    'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Volumes/Dev/dev/Dev/Flutter/pm-match-mobile/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/Models/TOCropViewControllerTransitioning.h (in target
    'TOCropViewController' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

```

</details> 

Following is the result when I call "flutter doctor -v"

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.4 at /Volumes/Dev/dev/Dev/Flutter/FlutterSDK/flutter
    • Framework revision fba99f6cf9 (6 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Volumes/Dev/dev/Dev/Android/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Volumes/Dev/dev/Dev/Android/SDK
    • ANDROID_SDK_ROOT = /Volumes/Dev/dev/Dev/Android/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.10.0.rc.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • B5AC98B9-BA6D-411F-89DB-2551EC37963A • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!

```

</details> 

<details> 
<summary>pubspec.yaml</summary> 

```yaml

Following is the part of pubspec.yaml.

version: 1.0.1+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_masked_text: ^0.8.0
  http: ^0.12.2
  sailor: ^0.7.1
  intl: ^0.16.1
  socket_io_client: ^0.9.11
  shared_preferences: ^0.5.10
  image_picker: ^0.6.7+9
  image_cropper: ^1.3.1
  cached_network_image: ^2.3.2+1
  flutter_keyboard_visibility: ^3.2.2
  url_launcher: ^5.6.0
  flutter_platform_widgets: ^0.60.2
  share: ^0.6.5+1
  location: ^3.0.2
  geocoder: ^0.2.1
  carousel_slider: ^2.2.1
  flutter_linkify: ^3.1.3
  flutter_tindercard: ^0.2.0
  flutter_inapp_purchase: ^2.2.0
  firebase_messaging: ^7.0.0
  badges: ^1.1.1

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

</details> 

Anybody can help me?

**Comment by SeasonLeee** [comment] 2020-09-21 06:40
Hi, there,  could you elaborate why you run the project the way you run it?(`flutter clean && flutter run`)

Normally, we just run the project, simply `flutter run`

Have you tried not using `flutter clean`?

**Comment by AndreasB115** [comment] 2020-09-21 09:21
Yes, I tried.

**Comment by AndreasB115** [comment] 2020-09-21 09:23
@SeasonLeee I don't have to use "flutter clean" anymore?

**Comment by TahaTesser** [comment] 2020-09-21 09:25
Hi @AndreasB115 

Can you please provide `flutter run --verbose` logs in a plain text file `.txt`, attach in the comment below, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by AndreasB115** [comment] 2020-09-21 09:44
[1.txt](https://github.com/flutter/flutter/files/5254555/1.txt)
Hi @TahaTesser It is the log file of "flutter run --verbose".

**Comment by TahaTesser** [comment] 2020-09-22 07:52
Hi @AndreasB115 
Can you please provide  a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using the third party packages
Thank you

**Comment by AndreasB115** [comment] 2020-09-22 09:22
Hi @TahaTesser 
I changed the pubspec.yaml with my team member is working.
It is working now.

**Comment by TahaTesser** [comment] 2020-09-22 09:34
Hi @AndreasB115 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-09-22 09:34 UTC
Labels: in triage

**Comment by ming-chu** [comment] 2020-09-24 05:49
@AndreasB115 Just FYR, I got the same issue because of imported dart html accidentally by android studio. You may want to check is there any `import 'dart:html';`

**Comment by AndreasB115** [comment] 2020-09-24 13:47
@ming-chu you don't need to remove it.
You need to check the configuration of flutter

**Comment by rdeleon13** [comment] 2020-09-25 01:41
@AndreasB115  what configuration of flutter? please provide more instruction, thank you!
