### ISSUE TITLE
[Mobile-web][Huawei Browser] Two cursors are visible in textfield

### ISSUE THREAD

**Issue by gabri1135** [flutter/flutter#118838] opened 2023-01-19 22:40 UTC
<img src="https://user-images.githubusercontent.com/70166963/213577795-1011a90c-7215-4660-88af-cae956765121.jpg" width="300" />

Using Flutter 3.3.10

Browser: HUAWEI Browser v. 12.1.3.304

Error Like #53244

**Comment by danagbemava-nc** [comment] 2023-01-20 10:59
Hi @gabri1135, please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example). 

- What device(s) have you tested on? 
- Is the Huawei browser the only browser you're seeing this issue on, or do you experience it with other browsers as well?


Thank you

**Comment by gabri1135** [comment] 2023-01-20 11:49
I have tested it o Huawei p40 lite
Only Huawei browser have this problem, show the browser cursor and is not aligned with The flutter one

```
final _formKey = GlobalKey<FormBuilderState>();
  final _node = FocusScopeNode();
  bool _showPassword = false;

@override
  Widget build(BuildContext context) {
    ref.listen(
        signInControllerProvider, (_, st) => st.showErrorDialog(context));
    final state = ref.watch(signInControllerProvider);

    return Container(
      padding: const EdgeInsets.all(20),
      child: FocusScope(
        node: _node,
        child: FormBuilder(
            key: _formKey,
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Text('PaninHub'),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: FormBuilderTextField(
                    name: 'username',
                    enabled: !state.isLoading,
                    decoration: const InputDecoration(
                      labelText: 'Username',
                      hintText: 'cognome.nome',
                    ),
                    validator: (value) => validUsername(value),
                    textInputAction: TextInputAction.next,
                    onEditingComplete: () => _node.nextFocus(),
                    autocorrect: false,
                    enableSuggestions: false,
                  ),
                ),
                Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: StatefulBuilder(
                        builder: (_, innerSetState) => FormBuilderTextField(
                            name: 'password',
                            autocorrect: false,
                            enableSuggestions: false,
                            obscureText: !_showPassword,
                            onChanged: (value) => innerSetState(() {}),
                            textInputAction: TextInputAction.next,
                            onEditingComplete: () => _submit(),
                            enabled: !state.isLoading,
                            decoration: InputDecoration(
                                labelText: 'Password',
                                suffixIcon: IconButton(
                                    icon: Visibility(
                                        visible: password.isNotEmpty,
                                        child: const Icon(
                                            Icons.remove_red_eye_sharp)),
                                    onPressed: () => innerSetState((() =>
                                        _showPassword = !_showPassword)))),
                            validator: (value) => validPassword(password)))),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: FormBuilderCheckbox(
                    name: 'rememberMe',
                    title: const Text('Ricordami'),
                    initialValue: false,
                    enabled: !state.isLoading,
                  ),
                ),
                Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: PrimaryButton(
                        text: 'Login',
                        icon: Icons.login,
                        isLoading: state.isLoading,
                        onPressed: () => _submit()))
              ],
            )),
      ),
    );
  }
}
```

**Comment by gabri1135** [comment] 2023-01-20 12:00
![Screenshot_20230120_130010](https://user-images.githubusercontent.com/70166963/213690238-a88e6d02-e0d7-49bd-a804-c8c50d880618.jpg)
![Screenshot_20230120_125820_com huawei browser_edit_76682593549756](https://user-images.githubusercontent.com/70166963/213690270-9b84bc27-c8d6-4463-ade0-5eacfa24f527.jpg)

**Comment by danagbemava-nc** [comment] 2023-01-23 07:06
Hi, @gabri1135, Thanks for the info. 

I want to confirm something. Did you run into a situation like below where the cursor and the handler are out of sync? 

Also, did you encounter the double cursor in any textfield at all or was it only the password textfield?


<img src="https://user-images.githubusercontent.com/88313112/213982865-bbd33ddd-8bca-406b-8b3a-94b1e1ff2f22.jpeg" width="300" />

**Comment by gabri1135** [comment] 2023-01-23 07:58
It run in all the textfields, but only in the password one is visible, in the other cases the two cursor are aligned
![Screenshot_20230123_084907](https://user-images.githubusercontent.com/70166963/213988994-52e16a62-8a90-42b6-af8e-065bcc7b4bfc.jpg)

Instead in the password field they are not aligned because you can obscure text and the text need more space when is obscused, compared to when is visible
![Collage_20230123_085443_edit_13517734987519](https://user-images.githubusercontent.com/70166963/213989984-94cccb89-f8bd-46fd-8cd0-29c1bb212792.jpg)
The one highlighted is the real one, where the character are inserted, and is the flutter one, the other is the browser cursor

**Comment by danagbemava-nc** [comment] 2023-01-24 06:26
Thanks for the info. 

Labeling for further investigation as I cannot reproduce this locally.

**Comment by mdebbar** [comment] 2023-01-26 18:37
Duplicate of https://github.com/flutter/flutter/issues/94130

**Closed by mdebbar** 2023-01-26 18:37 UTC
Labels: a: text input, platform-android, engine, platform-web, assigned for triage, web-host-platform-specific
