### ISSUE TITLE
Map doesn't work with GetX on iOS, Flutter SDK 3.10.0

### ISSUE THREAD

**Issue by alexlozdev** [flutter/flutter#128609] opened 2023-06-09 18:11 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter SDK 3.10.0
google_map_sdk: ^2.3.0
iOS : 11

sample code gives crash.

### Expected results

Flutter SDK 3.7.8
google_map_sdk: ^2.2.5
iOS : 11

sample code working properly

### Actual results

sample code gives crash

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
Goole Maps SDK for iOS version: 5.2.0.0
New version of Google Maps SDK for iOS available: 8.0.0.0
Lost connection to device
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
flutter channel stable, 3.10.0 on macOS 12.0.1 21559 darwin-x64
xcode 13.2.1
android studio 2022.1
```

</details>
flutter

**Comment by huycozy** [comment] 2023-06-12 06:13
Hi @alexlozdev 
I'm not quite clear on the `Steps to reproduce` this issue. The latest `[google_maps_flutter](https://pub.dev/packages/google_maps_flutter)` version is `2.3.0` and there is no `google_map_sdk` package on pub.dev. Can you please be more specific?

**Comment by alexlozdev** [comment] 2023-06-12 08:17
Sorry, I miswrite the version. I edited my question again.
The lastest google_maps_flutter version 2.3.0 is not working for iOS.

**Comment by alexlozdev** [comment] 2023-06-14 04:13
Sample works well.
I found that it is related with GetX.
I use GetX4.6.5 . 
Obx(() {
  return Column(
     children: [
        widget1,
        GoogleMap(
           mapType: MapType.hybrid,
           initialCameraPosition: _initialPosition,
        ),
     ],
  );
});

If I remove GetX, it works well.
Is there any solution?

**Comment by huycozy** [comment] 2023-06-14 04:18
Since it's related to GetX, you should open an issue on [its repository](https://github.com/jonataslaw/getx/issues) for better support there. 

Closing, as this isn't an issue with Flutter framework.

**Closed by huycozy** 2023-06-14 04:18 UTC
Labels: in triage
