### ISSUE TITLE
Flutter web + firebase hosting is too slow but not in local

### ISSUE THREAD

**Issue by eso0117** [flutter/flutter#150775] opened 2024-06-25 13:49 UTC
### Steps to reproduce

1. visit [my web application link](https://the-game-king.web.app/)
2. wait for fully rendering

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### What target platforms are you seeing this bug on?

Web

### OS/Browser name and version | Device information

Window | chrome  126.0.6478.115

### Does the problem occur on emulator/simulator as well as on physical devices?

No

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4529], locale ko-KR)
    • Flutter version 3.22.2 on channel stable at C:\Users\chuis'family\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\chuis'family\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.90.2)
    • VS Code at C:\Users\chuis'family\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4529]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.115
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.68

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by eso0117** [comment] 2024-06-25 13:53
I'm getting this error on dev console of browser,
```Exception while loading service worker: Error: prepareServiceWorker took more than 4000ms to resolve. Moving on.```
Maybe the error was the cause for this issue?

**Comment by feljohn07** [comment] 2024-06-25 14:02
Yeah kinda takes 3-4 seconds to load. But i always thought that this is the average loading time specially in Web. have you tried:

`flutter build web --web-renderer canvaskit --release`
? maybe this it will help.

**Comment by eso0117** [comment] 2024-06-25 14:17
Thanks I did the command what you mentioned, but It seems nothing improved.

then Is it normal that throwing
```Exception while loading service worker: Error: prepareServiceWorker took more than 4000ms to resolve. Moving on.```
this error?

**Comment by feljohn07** [comment] 2024-06-25 14:22
do you use wasm?

**Comment by eso0117** [comment] 2024-06-25 14:25
Currently not, does it make better? if i use it?

**Comment by eso0117** [comment] 2024-06-25 14:55
I updated `setTimeout` second argument to 1000 in `flutter_bootstrap.js`  and deployed

then it is much faster than before, 

But it seems not normal solution,

let r,t=new Promise((i,s)=>{r=setTimeout(()=>{s(new Error(`${n} took more than ${1000}ms to resolve. Moving on.`,{cause:b}))},1000)});

anybody help?

**Comment by LarryBauman** [comment] 2024-06-26 00:43
I'm having the same issue. 
This also causes files to not load and breaks most functionality of the app
![image](https://github.com/flutter/flutter/assets/19341411/ef3807bf-4d57-468e-bd88-ac98ec675930)

It appears to be related to the new 3.22 way of initializing the app
https://docs.flutter.dev/platform-integration/web/initialization

Following the upgrade instructions at the end of the page does not help.

**Comment by huycozy** [comment] 2024-06-26 05:43
@eso0117 Does the issue occur when running in `release` mode on your local machine? 

Also, since the issue only occurs in a deployed site, it's not easy for us to look into what could cause it. For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample.

**Comment by LarryBauman** [comment] 2024-06-26 06:44
@huycozy  apologies if it's inappropriate to intrude on this issue. 
I've tested locally in release mode and did not see the issue. 

Here's a public repo with the issue. https://github.com/LarryBauman/test_app

This was a newly created flutter app, that I simply ran flutter build web and then deployed to firebase. 

Here's by flutter doctor -v output
```[✓] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)
    • Flutter version 3.22.2 on channel stable at c:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Larry\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.29)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33927.289
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] VS Code (version 1.90.2)
    • VS Code at C:\Users\Larry\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[✓] VS Code (version 1.91.0-insider)
    • VS Code at C:\Users\Larry\AppData\Local\Programs\Microsoft VS Code Insiders
    • Flutter extension version 3.91.20240529

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.115
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.68

[✓] Network resources
    • All expected network resources are available.

• No issues found!```

**Comment by huycozy** [comment] 2024-06-27 04:54
Thank you both for the update. I also tried to deploy a new Flutter project to my Firebase hosting but couldn't see the issue:

![Screenshot 2024-06-27 at 11 45 13](https://github.com/flutter/flutter/assets/104349824/d2c00647-26ad-4731-91d6-71494b901ac8)

Did you build web with any optimization options (`--dart2js-optimization`)?  Can you share the command you used to build web?

**Comment by LarryBauman** [comment] 2024-06-27 04:58
@huycozy  I only ran `flutter build web` no optimizations

**Comment by eso0117** [comment] 2024-06-27 13:54
@huycozy 
@LarryBauman 

I've fixed my issue,

it was `firebase-tools` version issue for me,

I did run following command on my terminal
 ```npm install -g firebase-tools```
 
 and re-deploy then it is working well

**Comment by huycozy** [comment] 2024-06-28 03:48
Glad you found it. Closing the issue as solved.

**Closed by huycozy** 2024-06-28 03:48 UTC
Labels: in triage
