### ISSUE TITLE
Can't draw fullscreen on Android phone with notch

### ISSUE THREAD

**Issue by itsJoKr** [flutter/flutter#46486] opened 2019-12-08 11:40 UTC
## Steps to Reproduce
Flutter app doesn't draw fullscreen on Android phones with a notch. I tried all the combinations of window flags and Flutter setEnabledSystemUIOverlays.

- I can either use `SystemChrome.setEnabledSystemUIOverlays([]);` or `WindowManager.LayoutParams.FLAG_FULLSCREEN` which will result in app completely ignoring top area around notch:
<img width="522" alt="Screenshot 2019-12-07 at 15 32 27" src="https://user-images.githubusercontent.com/11093480/70376789-153fe680-190d-11ea-814d-70bfb3d2c654.png">

- Or I can use `WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS` which will make it draw around notch area but it doesn't hide the status bar
<img width="522" alt="Screenshot 2019-12-07 at 15 34 23" src="https://user-images.githubusercontent.com/11093480/70376815-533d0a80-190d-11ea-9339-ab0854854e33.png">

**Target Platform:** Android with a notch
**Devices:** tried with 2 physical devices and emulator

## Logs
[✓] Flutter (Channel master, v1.9.8-pre.3, on Mac OS X 10.14.6 18G1012, locale en-HR)
    • Flutter version 1.9.8-pre.3 at /Users/jokr/Downloads/flutter
    • Framework revision d67f47b21e (3 months ago), 2019-08-29 11:28:04 -0700
    • Engine revision f52c0b9270
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jokr/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/jokr/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

**Comment by iapicca** [comment] 2019-12-09 12:13
Hi @itsJoKr 
could you please run  `flutter upgrade`
If the issue persist please provide your updated `flutter doctor -v` 
thank you

**Comment by itsJoKr** [comment] 2019-12-09 15:37
Sure. I can report that after the upgrade issue is still present.

- Normal app with just blue background

![image](https://user-images.githubusercontent.com/11093480/70449106-b6f83c80-1aa1-11ea-90e5-f6d5ec25ddfb.png)

- With `WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS`

![image](https://user-images.githubusercontent.com/11093480/70449242-f9ba1480-1aa1-11ea-9de3-fe3e709f4efd.png)

- With `WindowManager.LayoutParams.FLAG_FULLSCREEN` or `SystemChrome.setEnabledSystemUIOverlays([]);`

![image](https://user-images.githubusercontent.com/11093480/70449353-1eae8780-1aa2-11ea-9e2a-5f63d7c34532.png)

## Logs
[✓] Flutter (Channel master, v1.13.1-pre.63, on Mac OS X 10.14.6 18G1012, locale en-HR)
    • Flutter version 1.13.1-pre.63 at /Users/jokr/Downloads/flutter
    • Framework revision 5e06984854 (6 hours ago), 2019-12-09 04:54:33 -0500
    • Engine revision 4beaa696fc
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a9c77229c2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jokr/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/jokr/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

**Comment by Piinks** [comment] 2020-03-05 18:30
This may be a regression already being tracked in #47683, which was bisected to #44369
cc/ @blasten

**Comment by divided7** [comment] 2020-03-22 17:25
@itsJoKr can you help me out? on #53056

**Comment by divided7** [comment] 2020-03-23 15:06
I am not using WindowManager.LayoutParams.FLAG_FULLSCREEN or SystemChrome.setEnabledSystemUIOverlays([]);, but still have the black area near the notch on my screen

**Comment by Aaron009** [comment] 2020-06-08 12:09
Has this problem been solved? I also encountered this problem.



```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Align(
          alignment: Alignment.topLeft,
          child: Image.network("https://shorturl.at/otCU9")),
    );
  }
}
```



[![2.jpg](https://i.postimg.cc/pT8XTyhR/2.jpg)](https://postimg.cc/8JpVXpm0)



I hope the picture will start to show from the red square. How to solve.

**Comment by kenle** [comment] 2020-06-08 13:48
> Has this problem been solved? I also encountered this problem.
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Align(
>           alignment: Alignment.topLeft,
>           child: Image.network("https://shorturl.at/otCU9")),
>     );
>   }
> }
> ```
> 
> [![2.jpg](https://camo.githubusercontent.com/df63ef395543b99ce88f3edb9f4ff5125f86a2b3/68747470733a2f2f692e706f7374696d672e63632f70543858547968522f322e6a7067)](https://postimg.cc/8JpVXpm0)
> 
> I hope the picture will start to show from the red square. How to solve.

Seems to have just happened to me also after upgrading to Android 10!

**Comment by Lapshin** [comment] 2020-07-07 11:39
Adding this to the styles.xml helped me

`<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>`

**Comment by zanderso** [comment] 2020-08-04 20:40
@xster I'm going to remove the milestone from this since it doesn't look like anyone is assigned.

**Comment by chandeshwarkumar** [comment] 2020-10-08 08:20
> Adding this to the styles.xml helped me
> 
> `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>`

how can i revert it to default on the next page ?
there is no option to alter style.XML programmatically

**Comment by huage2580** [comment] 2020-12-14 02:18
after use this code
```
<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
```
flutter can show as fullscreen，but the safeArea is doesn't work

**Comment by kashishkhullar** [comment] 2021-01-05 19:17
is there any solution to this through dart?

**Comment by xster** [comment] 2021-01-07 17:43
@GaryQian maybe you have some ideas

**Comment by mmmcorpsvit** [comment] 2021-01-14 10:50
i fix this problem, in styles.xml

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- Theme applied to the Android Window while the process is starting -->
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <!-- Theme applied to the Android Window as soon as the process has started.
         This theme determines the color of the Android Window while your
         Flutter UI initializes, as well as behind your Flutter UI while its
         running.
         
         This Theme is only used starting with V2 of Flutter's Android embedding. -->
    <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <item name="android:windowBackground">@android:color/white</item>
    </style>
</resources>
```

i think problem was in popular package: flutter_native_splash: ^0.2.5

**Comment by darshankawar** [comment] 2021-01-28 11:36
Verified this on latest stable and master and using below code changes, we can draw fullscreen on Android phone that has notch. (ex : tested on Pixel 3XL emulator).

1. Add `SystemChrome.setEnabledSystemUIOverlays([]);`
2. Add `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>` in `styles.xml` as mentioned in https://github.com/flutter/flutter/issues/46486#issuecomment-654796115.

With above, a sample image is rendered full screen as shown:

<img width="363" alt="Screenshot 2021-01-28 at 5 04 11 PM" src="https://user-images.githubusercontent.com/67046386/106133139-dca34200-618a-11eb-8ac4-b06b9791b8cd.png">

<details>
<summary> code sample </summary>

```
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([]);
    return MaterialApp(
      home: Scaffold(
      //  backgroundColor: Colors.blue,
        body: new Image.network(
          "https://picsum.photos/250?image=9",
          fit: BoxFit.cover,
          height: double.infinity,
          width: double.infinity,
          alignment: Alignment.center,
        ),
      ),
    );
  }
}

```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (6 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • SM A260G (mobile)            • 5200763ebcfa861f • android-arm • Android
      8.1.0 (API 27)
    • AOSP on IA Emulator (mobile) • emulator-5554    • android-x86 • Android 9
      (API 28) (emulator)

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 1.26.0-13.0.pre.229, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-13.0.pre.229 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 650b240634 (5 hours ago), 2021-01-27 21:39:06 -0800
    • Engine revision 68cd4c42b5
    • Dart version 2.12.0 (build 2.12.0-267.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM A260G (mobile)            • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • AOSP on IA Emulator (mobile) • emulator-5554    • android-x86    • Android
      9 (API 28) (emulator)
    • macOS (desktop)              • macos            • darwin-x64     • Mac OS
      X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                 • chrome           • web-javascript • Google
      Chrome 88.0.4324.96

! Doctor found issues in 1 category.


```

</details>
Closing this as fixed. If anyone disagrees, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-01-28 11:36 UTC
Labels: P4, a: layout, customer: crowd, dependency: android, engine, found in release: 1.19, framework, has reproducible steps, platform-android, severe: rendering

**Comment by lslv1243** [comment] 2021-03-15 22:14
@darshankawar I tried your solution and it does extend the screen to the edges, but it creates another problem, the widget SafeArea stops working.

<details>
<summary>flutter doctor -v</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.1 20C69 darwin-x64, locale pt)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.54.2)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
leonardosilva@MacBook-Pro-de-Leonardo versus % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.1 20C69 darwin-x64, locale pt)
    • Flutter version 2.0.1 at /Users/leonardosilva/development/flutter/flutter
    • Framework revision c5a4b4029c (11 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/leonardosilva/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • moto g 9 play (mobile)      • 0070472309                               • android-arm64  • Android 10 (API 29)
    • iPhone de Leonardo (mobile) • ac197a55a52fbad3d364054a4c99dbe29ed46b23 • ios            • iOS 14.3
    • macOS (desktop)             • macos                                    • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 89.0.4389.82
    ! Error: iPhone de Leonardo is busy: Copying cache files from device. Xcode will continue when iPhone de Leonardo is finished. (code -10)

! Doctor found issues in 1 category.
```
</details>
