### ISSUE TITLE
product_vm_isolate_snapshot does not exist?

### ISSUE THREAD

**Issue by LucasCLuk** [flutter/flutter#22553] opened 2018-10-02 12:29 UTC
I'm trying to use fastlane and I'm doing ``fastlane test`` and this is the result

## command
`
flutter build bundle --suppress-analytics --target lib/main.dart --depfile C:\Users\John\AndroidStudioProjects\projectX\build\app\intermediates\flutter\dynamicRelease/snapshot_blob.bin.d --asset-dir C:\Users\John\AndroidStudioProjects\projectX\build\app\intermediates\flutter\dynamicRelease/flutter_assets --release --dynamic
`
## exception

`FileSystemException: FileSystemException: Cannot open file, path = 'C:\flutter\bin\cache\artifacts\engine\windows-x64\product_vm_isolate_snapshot.bin' (OS Error: The system cannot find the file specified.
, errno = 2)`

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel unknown, v0.9.5, on Microsoft Windows [Version 10.0.17758.4], locale en-CA)
    • Flutter version 0.9.5 at C:\flutter
    • Framework revision 020fd590b0 (6 days ago), 2018-09-26 14:28:26 -0700
    • Engine revision 38a646e14c
    • Dart version 2.1.0-dev.5.0.flutter-4cf2d3990b

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at C:\Users\John\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Users\John\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\182.4505.22
    • Flutter plugin version 29.0.4
    • Dart plugin version 182.4323.44

[✓] Connected device (1 available)
    • SGH M919V • d5514710 • android-arm • Android 5.0.1 (API 21)

• No issues found!
```****

**Comment by mjaffa-figure** [comment] 2018-10-13 21:01
I am getting this as well trying to run on my Android phone.


## command

flutter build bundle --suppress-analytics --target lib/main.dart --depfile /Users/matthewjaffa/git/poodemic/build/app/intermediates/flutter/dynamicRelease/snapshot_blob.bin.d --asset-dir /Users/matthewjaffa/git/poodemic/build/app/intermediates/flutter/dynamicRelease/flutter_assets --release --dynamic

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/Users/matthewjaffa/flutter/bin/cache/artifacts/engine/darwin-x64/product_vm_isolate_snapshot.bin' (OS Error: No such file or directory, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.10.1-pre.40, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.10.1-pre.40 at /Users/matthewjaffa/flutter
    • Framework revision 8e2ca93f52 (17 hours ago), 2018-10-12 21:07:55 -0700
    • Engine revision 50c2e69daf
    • Dart version 2.1.0-dev.7.0.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/matthewjaffa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.28.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Pixel 2          • HT85J1A00654                             • android-arm64 • Android 9 (API 28)
    • Matthew’s iPhone • e5167fb6705be49ae5fe64392a7db61e6fc0e53e • ios           • iOS 12.0

! Doctor found issues in 1 category.
```

**Comment by jromero** [comment] 2018-10-23 17:45
For anyone looking for a current way around this...

Understand that the only variants broken are `DynamicProfile` and `DynamicRelease`. So any gradle task that tries to build those variants will fail due to the issue reported. In most cases you don't want to use those variants anyway.

Instead of using general tasks use the following:

`./gradlew build` → 
`./gradlew assembleDebug testDebug` OR `./gradlew assembleRelease testRelease`

`./gradlew test` → 
`./gradlew testDebug` OR `./gradlew testRelease`

**Comment by chaangliu** [comment] 2018-10-24 03:18
> For anyone looking for a current way around this...
> 
> Understand that the only variants broken are `DynamicProfile` and `DynamicRelease`. So any gradle task that tries to build those variants will fail due to the issue reported. In most cases you don't want to use those variants anyway.
> 
> Instead of using general tasks use the following:
> 
> `./gradlew build` →
> `./gradlew assembleDebug testDebug` OR `./gradlew assembleRelease testRelease`
> 
> `./gradlew test` →
> `./gradlew testDebug` OR `./gradlew testRelease`

Yes i also found this solution.  
I'm wondering what does `gradlew build`  do that causes the error. 
I also have the issue that if I define some other `BuildConfig`s in gradle other than `release` and `debug`, such as `dev`,  gradle also has trouble building the project(I am using flutter module in an existing app).

**Comment by jromero** [comment] 2018-10-24 04:45
`build` - `assembles` and `tests` *all* variants. Including the currently broken variants I've mentioned. As long as you specify exactly what variant tasks to execute you can work around this current issue.

**Comment by mjaffa-figure** [comment] 2018-10-24 13:46
That is great that you can compile command line. When I push the apk out to the device using adb, the app keeps constantly trying to launch and it won't launch. @zoechi This has been happening for almost 2 weeks. Have not been able to run my project on Android for awhile now.

**Comment by zoechi** [comment] 2018-10-24 14:53
@mjaffa-figure is this also with fastlane?
Can you reproduce with a new project as well?

**Comment by mjaffa-figure** [comment] 2018-10-24 15:31
@zoechi This is not with fast lane, it is with my project that has been working since the beginning on Android. I just tried with a new project and the new project is able to push out to Android just fine...

**Comment by mjaffa-figure** [comment] 2018-10-24 16:56
@zoechi I tracked it down to having these two dependencies included in my project. 

firebase_auth: ^0.6.2+1
firebase_admob: ^0.6.1+1

If I included those in a brand new project, the brand new project stops working. I will try to see if there are later versions that aren't breaking it.

**Comment by mjaffa-figure** [comment] 2018-10-24 17:03
@zoechi I tracked it down if I downgrade to firebase_admob: ^0.5.5 the app runs fine now on Android. So latest firebase_admob on android doesn't let the apk run, just crashes on load. iOS runs fine with the latest though.

**Comment by sbaranov** [comment] 2018-11-07 17:11
#23208 is fixed now. I'm having difficulty parsing the discussion here whether this issue is a duplicate of #23208, or something else is going on with firebase dependency. I'm closing this, but feel free to open a new issue if firebase dependency is giving you problem.

**Closed by sbaranov** 2018-11-07 17:11 UTC
Labels: p: firebase, p: first party, plugin, severe: crash, tool

**Comment by kroikie** [comment] 2019-10-13 18:47
@LucasCLuk

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/632. Any further collaboration will be done there.
