### ISSUE TITLE
flutter  getApplicationDocumentsDirectory() on IOS 

### ISSUE THREAD

**Issue by jfboisvieux** [flutter/flutter#50268] opened 2020-02-06 11:06 UTC
on my flutter app I use getApplicationDocumentsDirectory() to save data locally, **but** on IOS physical phone  getApplicationDocumentsDirectory() does not provide the same value when the app has been pushed from background apps and relaunch. Is there a workaround or do I have to use another local repository for local data ?

**Comment by alanassis** [comment] 2020-02-06 13:59
https://pub.dev/packages/path_provider

**Comment by VladyslavBondarenko** [comment] 2020-02-06 16:03
Thanks @alanassis ,
Yes, @jfboisvieux , try this plugin

Closing the issue
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by jfboisvieux** [comment] 2020-02-06 16:07
I tested both with getTemporaryDirectory() and getApplicationDocumentsDirectory() and in both cases on the iPhone (not on the emulator) the dir/file is different when the app is relaunched

**Comment by jfboisvieux** [comment] 2020-02-06 16:09
I mean using the path_provider plugin of course.

**Comment by gaaclarke** [comment] 2020-02-11 00:08
This isn't a bug.  The path that you get returned will be something like this `/var/mobile/Containers/Data/Application/D0497B41-0890-4C3F-B781-CEC94DB0248B/Documents`. That hash code represents the installation of the app.  When you update the app again iOS will get assigned a new hash but the documents will be transferred over.

You can verify that it works yourself with the following code:
```dart
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import 'package:path/path.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  _MyHomePageState() {
    _readState();
  }

  void _readState() async {
    Directory dir = await getApplicationDocumentsDirectory();
    String filePath = join(dir.path, "test.txt");
    File file = File(filePath);
    if (await file.exists()) {
      String oldText = file.readAsStringSync();
      setState(() {
        _counter = int.parse(oldText);
      });
    }
  }

  void _incrementCounter() async {
    setState(() {
      _counter += 1;
    });
    Directory dir = await getApplicationDocumentsDirectory();
    String filePath = join(dir.path, "test.txt");
    File file = File(filePath);
    file.writeAsStringSync('$_counter');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Closed by gaaclarke** 2020-02-11 00:08 UTC
Labels: p: path_provider, plugin, ⌺‬ platform-ios

**Comment by jfboisvieux** [comment] 2020-02-11 08:58
That’s a very clear answer

**Comment by jpgpuyo** [comment] 2021-02-23 17:21
Thank you so much for this answer, I had also this issue in an application. 
This is not a bug from Flutter, but this iOS behaviour is totally awful
