### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by kushvatsa** [flutter/flutter#21419] opened 2018-09-05 07:45 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --device-id=2f3acaca lib\main.dart

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /usr/bin/xcode-select.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84:7)
#2      Xcode.xcodeSelectPath (package:flutter_tools/src/ios/mac.dart:97:43)
#3      Xcode.isInstalled (package:flutter_tools/src/ios/mac.dart:106:9)
#4      Xcode.isInstalledAndMeetsVersionCheck (package:flutter_tools/src/ios/mac.dart:91:47)
#5      IOSWorkflow.canLaunchDevices (package:flutter_tools/src/ios/ios_workflow.dart:33:38)
#6      Doctor.canLaunchAnything.<anonymous closure> (package:flutter_tools/src/doctor.dart:285:58)
#7      _ListBase&Object&ListMixin.any (dart:collection/list.dart:130:15)
#8      Doctor.canLaunchAnything (package:flutter_tools/src/doctor.dart:285:22)
#9      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:385:17)
<asynchronous suspension>
#10     RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:237:21)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:350:11)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:109:11)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#40     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#41     run (package:flutter_tools/runner.dart:50:10)
#42     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#43     main (file:///F:/Flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.7.6-pre.45, on Microsoft Windows [Version 10.0.17134.228], locale en-IN)
    • Flutter version 0.7.6-pre.45 at F:\Flutter
    • Framework revision 58d98ce31e (5 hours ago), 2018-09-04 19:36:47 -0700
    • Engine revision de4c7a53f2
    • Dart version 2.1.0-dev.3.0.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\Kush\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\Program Files\Android\Android Studio Preview\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio Preview
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.26.1)
    • VS Code at C:\Users\Kush\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • SM A605G • 2f3acaca • android-arm • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by DanTup** [comment] 2018-09-05 08:35
Closing this as a dupe of #21418 which came in right before this one.

**Closed by DanTup** 2018-09-05 08:35 UTC
