### ISSUE TITLE
Image.network throws exceptions on HTTP errors

### ISSUE THREAD

**Issue by benPesso** [flutter/flutter#69125] opened 2020-10-27 17:26 UTC
As many developers have reported in the past, the `Image.network` constructor throws an exception whenever an HTTP error occurs (be it a 4xx error, 5xx error, or a SocketException). This is done in spite of the fact that there are many ways in which the developer can provide fallbacks when such an error occurs; using the built-in `errorBuilder` for example, or by attaching an `ImageStreamListener` and implementing its `onError` handler.

An HTTP error is not a failure of the code, and so should not throw an exception. Not when there are already hooks in place to allow the developer to handle the errors in a non-destructive manner. Throwing an exception is a major overkill and it completely breaks the app.

### Use case
To understand the severity of this, try this:
1. Build an app with a `ScrollView` that loads many `Image` widgets at the same time (ala Pinterest). (You can start with the sample app from the [errorBuilder docs](https://api.flutter.dev/flutter/widgets/Image/errorBuilder.html) - `create --sample=widgets.Image.errorBuilder.1 mysample` - and just modify it to insert multiple `Image.network` widgets into a `ScrollView`.)
2. Block network traffic if not using the sample app, to ensure HTTP errors will trigger.
3. Run the app.

What you'll end up having is an app that throws one exception after the other and a locked interface (E.g. no gesture responses on the scroll view).

### Expected Behavior
An HTTP request should never throw an exception on failure. It should instead fail gracefully, providing `onError` hooks, and allow the UI and logic to continue their execution.

### Proposed solution
1. Stop throwing exceptions on HTTP errors.
2. Add an `onError` handler to the `Image.network` constructor.
3. Modify the docs to encourage developers to either implement `errorBuilder` or an `ImageStreamListener` with an `onError` handler.

**Comment by TahaTesser** [comment] 2020-10-28 08:46
Hi @benPesso 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by benPesso** [comment] 2020-10-28 09:10
@TahaTesser `flutter doctor` didn't find any issues, which is why I did not include it.
As for the code, suffice that you run the sample code from the Flutter docs to see the issue. My example of having multiple images just goes to show how the effect is compounded when multiple images are failing to load. As opposed to just one.

**Comment by benPesso** [comment] 2020-10-28 10:00
While going through other issues, I found #33427, which seems to be talking about the same root problem - an exception from deep within the platform, even if the original call is made within a `try...catch`. However, that issues was last commented on a year ago, and with no solution.

Looking at all the referenced issues in #33427, this is clearly a major pain point for developers.

**Comment by TahaTesser** [comment] 2020-10-29 08:21
Hi @benPesso 
based on your steps , i tried to to reproduce HTTP and there no exception is thrown when using listview with 50 items with no network access
<details> 
<summary>code sample</summary> 

```dart
/// Flutter code sample for Image.errorBuilder
// @dart = 2.9

// The following sample uses [errorBuilder] to show a 'ð¢' in place of the
// image that fails to load, and prints the error to the console.

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

/// This is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: ListView.builder(
        itemCount: 50,
        itemBuilder: (BuildContext context, int index) {
          return MyStatelessWidget();
        },
      ),
    );
  }
}

/// This is the stateless widget that the main application instantiates.
class MyStatelessWidget extends StatelessWidget {
  MyStatelessWidget({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return DecoratedBox(
      decoration: BoxDecoration(
        color: Colors.white,
        border: Border.all(),
        borderRadius: BorderRadius.circular(20),
      ),
      child: Image.network(
        'https://i.imgur.com/kJFsPzd.jpg',
        errorBuilder:
            (BuildContext context, Object exception, StackTrace stackTrace) {
          // Appropriate logging or analytics, e.g.
          // myAnalytics.recordError(
          //   'An error occurred loading "https://example.does.not.exist/image.jpg"',
          //   exception,
          //   stackTrace,
          // );
          return Text('ð¢');
        },
      ),
    );
  }
}

```

</details> 

<details> 
<summary>code sample</summary> 

```dart
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 84f3d28555 (13 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details> 

Can you please provide your a complete reproducible minimal code sample and steps to reproduce 
Thank you

**Comment by benPesso** [comment] 2020-10-31 10:53
@TahaTesser It's easier if you use the sample from the docs, as it's using a non-existing URL.

Below is a working code sample. Just make sure to enable breakpoints on uncaught exceptions. 

_**Remember:** These errors are supposedly caught by the framework, and so shouldn't be treated as uncaught exceptions._

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ListView.builder(
        itemCount: 50,
        itemBuilder: (BuildContext context, int index) =>
            MyStatelessWidget(index),
      ),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  final int index;

  MyStatelessWidget(this.index, {Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Image.network(
        'https://example.does.not.exist/image.jpg?$index',
        errorBuilder: (
          BuildContext context,
          Object exception,
          StackTrace stackTrace,
        ) =>
            Text('Error $index'),
      ),
    );
  }
}
```
</details>

**Comment by TahaTesser** [comment] 2020-11-02 10:13
Hi @benPesso 
Thanks, I can reproduce the issue with the given code sample
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ListView.builder(
        itemCount: 50,
        itemBuilder: (BuildContext context, int index) =>
            MyStatelessWidget(index),
      ),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  final int index;

  MyStatelessWidget(this.index, {Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Image.network(
        'https://example.does.not.exist/image.jpg?$index',
        errorBuilder: (
          BuildContext context,
          Object exception,
          StackTrace stackTrace,
        ) =>
            Text('Error $index'),
      ),
    );
  }
}

```

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 8874f21e79 (4 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64 • Android
      10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios           • iOS
      14.1

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 1.24.0-7.0.pre.47, on Mac OS X 10.15.7 19H2
    darwin-x64, locale en-GB)
    • Flutter version 1.24.0-7.0.pre.47 at /Users/tahatesser/Code/flutter_master
    • Framework revision 2f18e0b23d (17 hours ago), 2020-11-01 20:58:04 +0530
    • Engine revision 3460519398
    • Dart version 2.12.0 (build 2.12.0-3.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.1
    • macOS (desktop)      • macos                     • darwin-x64     • Mac OS
      X 10.15.7 19H2 darwin-x64
    • Web Server (web)     • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 86.0.4240.111

• No issues found!
```

</details>

**Comment by fryette** [comment] 2021-06-11 06:07
@TahaTesser is it visible to fix it in near future?
If the application has a lot of images in the app it's impossible to develop with the enabled Uncaught exception option. This is a real pain for many developers.

**Comment by maheshmnj** [comment] 2022-07-12 07:00
This is no longer reproducible on the latest stable 3.0.4 or the master 3.1.0.

<img src="https://user-images.githubusercontent.com/31410839/178427918-375ea04a-fb20-4b91-99a0-4a9523a0f370.png" width ="300">


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: ListView.builder(
        itemCount: 50,
        itemBuilder: (BuildContext context, int index) =>
            MyStatelessWidget(index),
      ),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  final int index;

  MyStatelessWidget(this.index, {Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Image.network(
        'https://example.does.not.exist/image.jpg?$index',
        errorBuilder: (
          BuildContext context,
          Object? exception,
          StackTrace? stackTrace,
        ) =>
            Text('Error $index'),
      ),
    );
  }
}

```
</details> 
<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1594, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1594 on channel master at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 082ad11422 (21 hours ago), 2022-07-11 11:40:07 +0200
    • Engine revision 2b5d5c3b2d
    • Dart version 2.18.0 (build 2.18.0-271.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing as fixed.

**Closed by maheshmnj** 2022-07-12 07:00 UTC
Labels: framework, a: quality, a: debugging, a: images, has reproducible steps, P4, found in release: 1.22, found in release: 1.24

**Comment by Vadaski** [comment] 2022-07-14 03:43
Hi @maheshmnj , can you find out which pr fixes this? 
Many developers can't immediately upgrade to the latest version of flutter because the risk is high, so we want to refer to how to fix this problem. Thanks！

**Comment by suryavip** [comment] 2022-07-20 04:37
hi @maheshmnj . Are you sure you already check the "Uncaught exceptions" option in "breakpoints"? I can still reproduce the issue with your sample code.
![image](https://user-images.githubusercontent.com/28729285/179897125-2c7ebc88-817b-402e-9a32-b7737feffd91.png)
![image](https://user-images.githubusercontent.com/28729285/179897839-8649033e-3bf5-4ba8-8cdb-c425e2577dac.png)

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.739], locale en-ID)
    • Flutter version 3.0.5 at C:\projects\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Surya\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\Surya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.739]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 103.0.1264.49

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by maheshmnj** [comment] 2022-08-01 06:21
@benPesso Thanks for pointing out that it looks like the errroBuilder does show the errorWidget but does not catch the exception. I see a similar issue open for this case https://github.com/flutter/flutter/issues/107416. Please follow up there for further updates.

**Comment by benPesso** [comment] 2022-08-01 08:37
@maheshmnj Thanks for the heads up. Shouldn't this issue be reopened, then? I haven't tested this myself, but as you point out - the underlying issue still remains.

**Comment by maheshmnj** [comment] 2022-08-08 13:18
Please follow up on this issue https://github.com/flutter/flutter/issues/107416
