### ISSUE TITLE
 Interface androidx.lifecycle.b implemented by class io.flutter.plugins.localauth.AuthenticationHelper is inaccessible (declaration of 'io.flutter.plugins.localauth.AuthenticationHelper' _

### ISSUE THREAD

**Issue by JanobA99** [flutter/flutter#78791] opened 2021-03-22 16:05 UTC
## Steps to Reproduce

**Expected results:** Localauth is not working on release mode, but works on debug. I checked other similar issues on this repository, but downgrading gradle version's didn't help. Currently using gradle 4.1.1 and localauth 1.1.0

<details>
  <summary>Logs</summary>

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.alijonyulchiev.karmon_pay_new">
    <uses-permission android:name="android.permission.READ_CONTACTS"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.USE_BIOMETRIC"/>
   <application
        android:label="karmon_pay_new"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

```
E/AndroidRuntime(24031): FATAL EXCEPTION: main
E/AndroidRuntime(24031): Process: com.alijonyulchiev.karmon_pay_new, PID: 24031
E/AndroidRuntime(24031): java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class io.flutter.plugins.localauth.AuthenticationHelper is inaccessible (declaration of 'io.flutter.plugins.localauth.AuthenticationHelper' appears in /data/app/com
.alijonyulchiev.karmon_pay_new-FVY-bp94lywpX4uTBKMw8Q==/base.apk)
E/AndroidRuntime(24031):        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:16)
E/AndroidRuntime(24031):        at com.alijonyulchiev.karmon_pay_new.MainActivity.g(Unknown Source:5)
E/AndroidRuntime(24031):        at io.flutter.embedding.android.i.g(Unknown Source:10)
E/AndroidRuntime(24031):        at io.flutter.embedding.android.e.k(Unknown Source:58)
E/AndroidRuntime(24031):        at io.flutter.embedding.android.i.u0(Unknown Source:10)
E/AndroidRuntime(24031):        at androidx.fragment.app.Fragment.Z0(Unknown Source:21)
E/AndroidRuntime(24031):        at androidx.fragment.app.j.R0(Unknown Source:433)
E/AndroidRuntime(24031):        at androidx.fragment.app.o.b(Unknown Source:206)
E/AndroidRuntime(24031):        at androidx.fragment.app.o.c(Unknown Source:18)
E/AndroidRuntime(24031):        at androidx.fragment.app.o.C(Unknown Source:36)
E/AndroidRuntime(24031):        at androidx.fragment.app.j.n0(Unknown Source:110)
E/AndroidRuntime(24031):        at androidx.fragment.app.j.Z0(Unknown Source:88)
E/AndroidRuntime(24031):        at androidx.fragment.app.j.l0(Unknown Source:21)
E/AndroidRuntime(24031):        at androidx.fragment.app.j.e0(Unknown Source:9)
E/AndroidRuntime(24031):        at androidx.fragment.app.j.y(Unknown Source:6)
E/AndroidRuntime(24031):        at androidx.fragment.app.f.c(Unknown Source:4)
E/AndroidRuntime(24031):        at androidx.fragment.app.d.onStart(Unknown Source:15)
E/AndroidRuntime(24031):        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
E/AndroidRuntime(24031):        at android.app.Activity.performStart(Activity.java:7980)
E/AndroidRuntime(24031):        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3655)
E/AndroidRuntime(24031):        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/AndroidRuntime(24031):        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/AndroidRuntime(24031):        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/AndroidRuntime(24031):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(24031):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
E/AndroidRuntime(24031):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(24031):        at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(24031):        at android.app.ActivityThread.main(ActivityThread.java:8125)
E/AndroidRuntime(24031):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24031):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(24031):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

```
flutter doctor -v
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (11 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\alijo\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\alijo\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31105.61
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SC 02K (mobile)   • 231af64c670d7ece • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2021-03-23 08:28
@JanobA99 
Can you provide us a complete minimal reproducible code sample that shows this issue ?
Can you also try the local_auth plugin [example](https://pub.dev/packages/local_auth/example) and check if you see same behavior ?

**Comment by Nuruddinjr** [comment] 2021-03-23 08:47
Hi @darshankawar, I am working with @JanobA99 at the same project, we are trying to run example project you provided, it is giving the same error in two different PCs.

**Comment by Jamshid1901** [comment] 2021-03-23 08:50
@darshankawar , Yes we tried the local_auth plugin exiting the apk when using it after releasing the example

**Comment by darshankawar** [comment] 2021-03-23 10:36
@Nuruddinjr @Jamshid1901 @JanobA99 Looking at the error:

`java.lang.IllegalAccessError: Interface androidx.lifecycle.b implemented by class io.flutter.plugins.localauth.AuthenticationHelper is inaccessible (declaration of 'io.flutter.plugins.localauth.AuthenticationHelper' appears in /data/app/com`

It doesn't seem to be specific to `local_auth`, but has occurred while using other plugins as well, for example, `image_picker` and `google_maps_flutter` and seems to be related to the gradle version, ie >= 4.0.0

There's similar open issue describing your case, https://github.com/flutter/flutter/issues/58479.
Please follow-up there for updates and try the workarounds mentioned in underlying comments to see if they work for you.

I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-03-23 10:36 UTC
Labels: in triage, waiting for customer response
