### ISSUE TITLE
Flake: intrinsic dimension methods of the RenderPadding class returned values that violate the intrinsic protocol contract

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#26319] opened 2019-01-09 23:14 UTC
The following failure was [observed on Cirrus for Windows](https://cirrus-ci.com/task/6596762926055424) while running tests for an [unrelated (posix-only) PR](https://github.com/flutter/flutter/pull/26315):

```
01:03 +808 ~7: C:\Windows\Temp\flutter sdk\packages\flutter\test\material\date_picker_test.dart: showDatePicker tap-select a day                                                                       
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
The intrinsic dimension methods of the RenderPadding class returned values that violate the
intrinsic protocol contract.
The following failure was detected:
 * getMinIntrinsicWidth(Infinity) returned a larger value (40.0) than getMaxIntrinsicWidth(Infinity)
   (24.0)
If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
01:04 +809 ~7: C:\Windows\Temp\flutter sdk\packages\flutter\test\material\date_picker_test.dart: showDatePicker tap-select a day                                                                       
01:04 +809 ~7: C:\Windows\Temp\flutter sdk\packages\flutter\test\material\date_picker_test.dart: showDatePicker tap-select a day                                                                       
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1813:11)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1823:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1543:17)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1543:65)
#4      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:202:5)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#6      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#22     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:549:15)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#24     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#29     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1203:11)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#31     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:486:13)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#34     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#38     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#49     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#66     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2900:13)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#68     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#70     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#75     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
#82     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
#83     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
#84     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
#85     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:803:23)
#86     _TestWidgetsFlutterBinding&BindingBase&ServicesBinding&SchedulerBinding&GestureBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
#87     _TestWidgetsFlutterBinding&BindingBase&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#88     _TestWidgetsFlutterBinding&BindingBase&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#89     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:714:9)
#92     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#93     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:701:27)
#94     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:237:22)
#97     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#98     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:234:27)
#99     _tests.<anonymous closure> (file:///C:/Windows/Temp/flutter%20sdk/packages/flutter/test/material/date_picker_test.dart:43:18)
#101    _tests.<anonymous closure> (file:///C:/Windows/Temp/flutter%20sdk/packages/flutter/test/material/date_picker_test.dart:39:35)
#102    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:82:23)
#103    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:566:19)
#117    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:909:17)
#119    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:897:35)
(elided 34 frames from class _FakeAsync, package dart:async, and package stack_trace)
The following RenderObject was being processed when the exception was fired:
  RenderPadding#0ea7e relayoutBoundary=up9
  creator: Padding ← ConstrainedBox ← Semantics ← Semantics ← Listener ← RawGestureDetector ←
  GestureDetector ← Tooltip ← Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ←
  ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(48.0<=w<=Infinity, 48.0<=h<=Infinity)
  size: Size(48.0, 48.0)
  padding: EdgeInsets.all(8.0)
  textDirection: ltr
This RenderObject had the following descendants (showing up to depth 5):
  RenderConstrainedBox#1d437 relayoutBoundary=up10
    RenderPositionedBox#12af9
      RenderSemanticsAnnotations#d7c62 relayoutBoundary=up1
        RenderExcludeSemantics#87334 relayoutBoundary=up2
          RenderConstrainedBox#0fa75 relayoutBoundary=up3
════════════════════════════════════════════════════════════════════════════════════════════════════
01:04 +809 ~7 -1: C:\Windows\Temp\flutter sdk\packages\flutter\test\material\date_picker_test.dart: showDatePicker tap-select a day [E]                                                                
  Test failed. See exception logs above.
  The test description was: tap-select a day
```

**Comment by Hixie** [comment] 2019-05-17 18:03
Dupe of https://github.com/flutter/flutter/issues/19696

**Closed by Hixie** 2019-05-17 18:03 UTC
Labels: team, team: flakes
