### ISSUE TITLE
[Web] TextField error on web mode

### ISSUE THREAD

**Issue by liuzhengcai** [flutter/flutter#42397] opened 2019-10-10 04:10 UTC
[error message ](http://www.liuzhengcai.top/images/txtinput_err.png)

`Widget getRow(String name, String value) {
    TextEditingController txtController = TextEditingController();
    txtController.text = value;
    txtController.addListener(() {});

    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Row(
        children: <Widget>[
          Icon(
            Icons.settings,
            color: Colors.green,
          ),
          Text(
            name,
            style: TextStyle(fontSize: 21, color: Colors.white),
          ),
          Padding(
            padding: const EdgeInsets.only(left: 15),
            child: Container(
              width: 90,
              height: 50,
              child: TextField(
                controller: txtController,
                //cursorColor: Colors.purple,
                //cursorWidth: 10,
                //cursorRadius: Radius.elliptical(2, 8),
                onChanged: (value) {
                  setState(() {
                    value1 = value;
                  });
                },
                keyboardType: TextInputType.text,
                decoration: InputDecoration(
                  contentPadding: EdgeInsets.all(10.0),
                  //labelText: value.toString(),
                ),
                //autofocus: false,
              ),
            ),
          )
        ],
      ),
    );
  }`

**Comment by liuzhengcai** [comment] 2019-10-10 04:13
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.10.6, on Microsoft Windows [Version 10.0.17134.1069], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] Connected device (2 available)

**Comment by jonahwilliams** [comment] 2019-10-10 05:11
duplicate of https://github.com/flutter/flutter/issues/42201

**Closed by jonahwilliams** 2019-10-10 05:11 UTC
