### ISSUE TITLE
[Impeller] Enabling Impeller on iOS simulator causing massive memory usage and latency 

### ISSUE THREAD

**Issue by broderbluff** [flutter/flutter#127482] opened 2023-05-24 10:50 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Running any of my apps on the iOS Simulator with impeller enabled.

macOS ventura 13.2
MacBook 2018 Pro 8 GB ram

[https://stackoverflow.com/questions/76298094/impeller-rendering-engine-causing-massive-latency-and-memory-consumption](url) Problem is encountered here as well with a computer with 4 times the amount of ram that i have.

### Expected results

That the application is running as smooth on the simulator as without impeller enabled.

### Actual results

With impeller enabled causing massive latency problems when trying to use the computer and massive memory consumption.

Process: SimMetalHost used about 2.65 gb ram while running with impeller directly after the loading of the app is done. 

with the  --no-enable-impeller flag everything goes back to running as smooth as butter.

with impeller
![With Impeller](https://github.com/flutter/flutter/assets/8105390/5379eea8-668e-461c-b5d4-cd0ee77c34b4)

without impeller
![Without impeller](https://github.com/flutter/flutter/assets/8105390/41ce460e-8f7c-4149-a64f-47f6df8acbfc)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.2 22D49 darwin-x64, locale sv-SE)
    • Flutter version 3.10.1 on channel stable at /Users/patrikpersson/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (7 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/patrikpersson/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] VS Code (version 1.79.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • E3DDB83B-943F-4F57-9F0C-C058C57C6B58 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 13.2 22D49 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-05-25 07:00
Thanks for the report @broderbluff 
Can you provide us some memory consumption visuals (usually from Xcode) which shows the massive spike in memory usage with and without impeller ?

Also, please try the same on physical device and in `--profile` mode to capture the correct consumption.

**Comment by broderbluff** [comment] 2023-05-25 14:37
I hope this is the data you're asking for. =O =D

[run1impellerrun2without.trace.zip](https://github.com/flutter/flutter/files/11566071/run1impellerrun2without.trace.zip)


Running real device --profile 
[without-impeller-dart_devtools_2023-05-25_16_16_12.778.csv](https://github.com/flutter/flutter/files/11566078/without-impeller-dart_devtools_2023-05-25_16_16_12.778.csv)

[impeller-dart_devtools_2023-05-25_16_11_29.218.csv](https://github.com/flutter/flutter/files/11566080/impeller-dart_devtools_2023-05-25_16_11_29.218.csv)

**Comment by large** [comment] 2023-05-25 18:26
Same issue, using Flutter (Channel master, 3.11.0-14.0.pre.11, on macOS 13.4 22F66 darwin-arm64, locale nb-NO)
![image](https://github.com/flutter/flutter/assets/535446/2feba471-6915-4225-b629-a7e696b8f7b7)

Runned on Mac Mini M2 with 32 GB ram 1TB drive...

Trying the beta channel next...

**Comment by darshankawar** [comment] 2023-05-26 05:31
Thanks for the update. Seeing the same behavior as reported and labeling based on the report and details provided https://github.com/flutter/flutter/issues/127482#issuecomment-1563025209

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.10.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.10.1 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (35 hours ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.11.0-13.0.pre.21, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.11.0-13.0.pre.21 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e4104b094 (2 hours ago), 2023-05-24 23:09:20 -0400
    • Engine revision 62a83490ee
    • Dart version 3.1.0 (build 3.1.0-143.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by alexobviously** [comment] 2023-05-26 10:46
![Screenshot 2023-05-26 at 17 36 56](https://github.com/flutter/flutter/assets/2500696/3611ac28-129a-424a-bd7f-880bdd8141a4)
120GB, can I have the silver medal?

**Comment by electricbolt** [comment] 2023-05-27 07:23
Hi. Same issue for me with Impeller enabled. Very low frame rates of apps in the Simulator and ~3GB SimMetalHost memory usage in macOS activity monitor. Disable Impeller and everything is great again. I've tried a few flutter apps and they all exhibit the same behaviour.

(2019 MacBook Pro 2.6GHz Core i7, 16GB RAM, Intel UHD Graphics 630 1536 MB)

**Comment by mohammed710** [comment] 2023-05-30 10:46
i have sma issue HELP!!!

**Comment by chinmaygarde** [comment] 2023-05-30 20:06
From Triage: Reported memory usage on Intel macOS should be higher than Apple Silicon macs as well as devices because both the MSAA and stencil textures will get allocated as device private textures instead of memoryless textures. But those should get recycled immediately.

Looking at the comments however, @large s [setup is an Apple Silicon Mac](https://github.com/flutter/flutter/issues/127482#issuecomment-1563329320). So, unless we are discussing different issues, something is holding onto scratch textures (the only thing I can recall as being anything close to be large enough to explain this rise) for a long time.

The only thing I can recall as being related are the Metal profiling and debugging tools in Xcode that sometimes held onto resources for longer than expected. 

I am going to try to reproduce this on my setup as I have both an Intel and Apple Silicon mac handy. In the meantime, can anyone here comment on whether Metal frame profiling and debugging is enabled in your run configurations?

**Comment by electricbolt** [comment] 2023-05-30 22:29
Hi. I don't run the app using the Xcode profile option, nor do I ever use the Xcode Metal frame capture feature, shader debugger or anything similar.

**Comment by chinmaygarde** [comment] 2023-05-31 00:58
Sorry, I meant the Metal GPU Frame Capture and validations turned off from the run configuration. This is different from the Profile Xcode option. Are you able to reproduce the memory consumption with the capture disabled and the validation boxes checked off?

I am trying to reproduce the usage. So far, I haven't managed to do so on my M1 Macbook Pro and Intel iMac with AMD Firepro. Trying a few more things.

![Image](https://github.com/flutter/flutter/assets/44085/b075502a-6364-4771-a176-ac338653f678)
![Image](https://github.com/flutter/flutter/assets/44085/f3bc8ac6-76da-4f2c-8e33-9b0ef3eda60b)

**Comment by electricbolt** [comment] 2023-05-31 01:16
So I tried my own app and a 3rd party single file app 4 days ago when i logged the issue ... both were janky and horrible and 3GB memory usage. **Today ... working perfectly fine.** I've not changed any settings in Xcode. None of those settings are enabled.

Also how would these settings be enabled (which appear to be flags or similar passed into the environment when launched), still work when I kill the app off in the Simulator and restart the app from within the Simulator. Xcode, Intelli-J not running. I still had laggy performance.

Just wondering if anyone else has any messages appearing in the Console on app startup in Intelli-J. I'm sure i remember something appearing, but it's not there today, something mentioning "Metal".

I'll continue trying the app(s) and see if I can get it back to being laggy.

**Comment by chinmaygarde** [comment] 2023-05-31 01:34
> Also how would these settings be enabled...

I wasn't suggesting that these settings had to be enabled or disabled manually. The simulators should work without taking up copious amounts of memory no matter the settings. Just wanted to see if turning these off made the issue go away so I could validate the hunch. Since I'm having trouble reproducing the observations.

Will keep looking and post another update soon.

**Comment by lazarohcm** [comment] 2023-05-31 04:56
@chinmaygarde It looks okay when disabling those settings. It has just been a few minutes.
I'll update it later in case the memory consumption goes up again

**Comment by broderbluff** [comment] 2023-05-31 11:20
Same issue when both options are disabled.

**Comment by AlaaAbdelbaki** [comment] 2023-05-31 14:51
I was having this problem when using master channel, switching back to the stable channel fixed this issue for me.

**Comment by jason-simmons** [comment] 2023-05-31 19:09
I can reproduce this by running the old Flutter Gallery app with Impeller on an iOS simulator.  The `MEM` statistic in `top` will quickly grow while scrolling the image list in the "Pesto" demo.

Bisected this to https://github.com/flutter/engine/commit/fc6df951

**Comment by chinmaygarde** [comment] 2023-05-31 19:16
Is that patch is in 3.10 and 3.11? Could it be the autorelease pool thing that we ran into on macOS again?

**Comment by jason-simmons** [comment] 2023-05-31 19:41
That change has not been cherry picked into the 3.10 branch.

The memory leak disappears if I wrap the task queued by `CommandBufferMTL::SubmitCommandsAsync` in an `@autoreleasepool`.

**Comment by joconnell521** [comment] 2023-06-02 17:16
I am having the same issue. I ran flutter upgrade a couple days ago and it failed to find a .zip file but I just continued with what I was doing rather than trying to figure it out. Maybe its linked to that? Did anyone else have that happen?

**Comment by borjandev** [comment] 2023-06-02 20:05
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

Reproducible on the default flutter app on cd18c8c02f3f2bdee61c19ca440d8849e6b9f24b which is TOT on master channel at the moment of this comment

```
flutter create memoryhog
cd memoryhog
```

`open -a Simulator`

```
flutter run -d 'iPhone 13 mini' 
(since Impeller is enabled by default, press the button 474 times and monitor the huge memory usage)

flutter run -d 'iPhone 13 mini' --no-enable-impeller



(disable impeller, press the button 474 times, memory is OK)
```

https://github.com/flutter/flutter/assets/64651636/3c9a66ce-12a3-4f2d-8c37-d1f470fbf106

https://github.com/flutter/flutter/assets/64651636/8b334f40-542d-4f01-a4d3-fc398ef228cb

The system runs out of memory eventually and presents a dialog to force close apps, which severely impacts development.

I also suspect this may be related to some crashes on real devices that started happening recently.

**Comment by borjandev** [comment] 2023-06-02 22:53
Seems fixed by 6b69a74dc62b85ed325082a843e414cbf5a4a93b 

Can't reproduce anymore

**Comment by ravindranathakila** [comment] 2023-06-04 02:43
The resolution provide in the comments of this answer work.

https://stackoverflow.com/a/76349510/915022

**Comment by broderbluff** [comment] 2023-06-21 12:19
Still present in Flutter 3.10.5

**Comment by raulmabe-labhouse** [comment] 2023-06-29 15:13
I think this issue also happens on real devices, at least to me. We have severe perf issues (app taking up to 2 GB of memory on iOS) after updating to Flutter 3.10.

We have tried different versions of Flutter to check if the issue still persists:

- Memory taking as much as possible: `3.10.0`,`3.10.1`, `3.10.5`, `3.12.0`
- Memory taking more than before `3.7.8`, but less than `3.10`: `3.11.0-0.1.pre`

**Comment by chinmaygarde** [comment] 2023-06-29 20:45
A leak was introduced in https://github.com/flutter/engine/commit/fc6df951 and fixed in https://github.com/flutter/engine/commit/f3f6a020595dd7f9f809bca2ebb604a42aae1cfc. I am reliably able to reproduce the memory leak in the intermediate commits. After the second patch however, the leak goes away. See the attached screenshot of my attempt with @borjandev s "memoryhog" application. He also confirmed the fix in https://github.com/flutter/flutter/issues/127482#issuecomment-1574408325.

Looking at the tags however, the issue was introduced and fixed between `3.11` and `3.12`. The issue nor the fix was is `3.11` and both commits were in `3.12`. The affected tags had the `.pre` suffix. So while I think there was a leak, @broderbluff s issue is not the same and the issue I linked to was never in a stable release.

Our suspicion is that this is the same as https://github.com/flutter/flutter/issues/128391 but that affects performance of simulators running on macOS devices with Intel integrated GPUs from around 2018 or 2019 (Intel Iris 630/640/645 GPUs or similar).

@broderbluff (and anyone else who may be seeing this on their simulators), can you chime on the graphics card used on your macOS Host running the simulator? You can do this using "[Apple Logo] -> About This Mac" or "System Information.app -> Graphics/Displays.".

@raulmabe-labhouse We are only trying to figure out simulator issues here. Can you file a separate issue with reproductions etc. so we can give attention to it specifically. 

Also, since there *was* a leak found and fixed between 3.11 and 3.12, can folks saying this affects them also confirm that their observation was not in the problematic ranges (`main` branch should be fine) along with their macOS Hosts graphics configuration please? Thanks.

<img width="1523" alt="Screenshot 2023-06-29 at 1 05 18 PM" src="https://github.com/flutter/flutter/assets/44085/463317cd-aca6-445d-9583-21d8ca864519">

Example of About my Mac:
<img width="392" alt="Screenshot 2023-06-29 at 1 28 29 PM" src="https://github.com/flutter/flutter/assets/44085/cd84b644-6e54-4e20-8c40-3d80d97377f2">

**Comment by juandiago** [comment] 2023-06-30 16:17
Can confirm seeing this issue on MBP16 2019 with Intel UHD 630

**Comment by broderbluff** [comment] 2023-07-01 20:41
@chinmaygarde 

Intel Iris Plus Graphics 645 1536 MB

**Comment by stefannovak** [comment] 2023-07-03 10:42
I have just had this issue too. I have this exception at start 

```
The following _Exception was thrown resolving an image frame:
Exception: No Impeller context is available

When the exception was thrown, this was the stack
Image provider: AssetImage(bundle: null, name: "assets/graphics/logo.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#6234d(), name: "assets/graphics/logo.png", scale: 1.0)
```

And then shortly after the SimMetalHost process goes up to 4gb memory usage making my machine unusable.

**Comment by f-person** [comment] 2023-07-06 13:34
Folks, did anyone experience this issue in release builds, too, or only debug?

**Comment by broderbluff** [comment] 2023-07-06 14:23
> Folks, did anyone experience this issue in release builds, too, or only debug?

For me I only experience this on debug with the simulator. 
On release builds with real devices I do not experience any slowdowns.

**Comment by diegotori** [comment] 2023-07-13 20:31
@chinmaygarde I also saw this happen recently where a video we are using in our app's background caused the simulator to use 192GB of memory, which is beyond the 16GB of RAM my OG MacBook Pro M1 2020 can muster.

This was never an issue pre-Impeller, but as a result of upgrading to Flutter 3.10, this is causing me to max out my RAM very easily.

Also, this is still happening on `3.10.6`. This feels like a tier 1 issue that's affecting my ability to use the iOS Simulator when developing apps. Is there any chance that you guys can cherry-pick the hotfix that addresses this issue? That way, I don't have to disable Impeller while using it in debug mode.

Thank you in advance.

**Comment by stefannovak** [comment] 2023-07-15 15:16
Still happening on Flutter version 3.10.6, Dart 3.0.6. It happens every single time I open the simulator and debug a flutter app.

**Comment by AntonioVerdiglione1996** [comment] 2023-07-17 09:30
Flutter 3.10.4, this memory leak seems to be true. 
You need to disable impeller --no-enable-impeller for your flutter run.
Im using emulator: iPhone 14 Pro Max.
Developing a chat app.
SimMetalHost take 3.6 GB of Ram.

**Comment by broderbluff** [comment] 2023-09-18 21:20
Issue seems to be resolved on 3.13  and onwards

**Comment by juandiago** [comment] 2023-09-26 21:36
I'm still seeing degraded perf on `3.13.5` when impeller is enabled

**Comment by alexobviously** [comment] 2023-09-27 02:56
This is definitely not resolved, I tried to turn impeller back on and my simulator was taking 100GB of memory again, on `3.13.5`.

**Closed** 2023-11-01 12:21 UTC
Labels: platform-ios, engine, perf: memory, has reproducible steps, P1, r: fixed, e: impeller, found in release: 3.10, found in release: 3.11, team-engine, triaged-engine, multiteam-retriage-candidate
