### ISSUE TITLE
SingleChildScrollView with column produces gaps between Column's children

### ISSUE THREAD

**Issue by jaleelfingo** [flutter/flutter#40724] opened 2019-09-18 02:37 UTC
## Steps to Reproduce

Scroll the black bar up and down in the following application, you will see small gaps between the children of the column like this -- sometimes it goes away but sometimes it stays:

<img width="399" alt="Screen Shot 2019-09-17 at 7 31 54 PM" src="https://user-images.githubusercontent.com/47991632/65103255-88773380-d982-11e9-8662-a317c20d1b92.png">

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title});
  final String title;

  @override
  Widget build(BuildContext context) {
    return StateWidget();
  }
}

class StateWidget extends StatefulWidget {
  StateWidget({Key key}) : super(key: key);

  @override
  State<StatefulWidget> createState() {
    return StateWidgetState();
  }
}

class StateWidgetState extends State<StateWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(children: [
        Column(
        children: <Widget>[
          Expanded(child: Container(color: Colors.yellow),)
        ],
      ),
        SingleChildScrollView(
          child: Column(
            children: <Widget>[
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
              Container(height: 30, width: 40, color: Colors.black,),
            ],
          ),
        ),
      ],
      ),
    );
  }
}

```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/jaleel/jalibs/flutter
    • Framework revision 2d2a1ffec9 (11 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaleel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone 6 • 63B7E050-6B5F-47FA-9BF6-074197ED1788 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

```

**Comment by escamoteur** [comment] 2019-09-18 11:18
Besides the question why you doing this, I think this is not to avoid because of rounding errors. You can avoid this by creating your Layout differently.

**Comment by jaleelfingo** [comment] 2019-09-18 14:47
@escamoteur this is just an example to illustrate the problem. My app is not a black scrolling bar with a yellow background. There are use cases that require this hierarchy.

**Comment by escamoteur** [comment] 2019-09-18 15:06
@jaleelfingo Sure I was guessing that. Still the question do you need to place Widgets in a column so that they don't have any spaces like the ones you describe here?
Maybe another approach to your problem might be better.

**Comment by jaleelfingo** [comment] 2019-09-18 15:19
How do you recommend placing widgets that should be vertically adjacent?

**Comment by escamoteur** [comment] 2019-09-18 16:13
Depends on what you want to show. Also you always can put another layer of the same color behind the Widgets in your column.

**Comment by jaleelfingo** [comment] 2019-09-18 17:51
@escamoteur what if the children are different colors?

**Comment by escamoteur** [comment] 2019-09-18 19:43
Can you share the design that you want to make? You can also send me an email to github@burkharts.net

**Comment by goderbauer** [comment] 2019-09-18 22:03
Duplicate of https://github.com/flutter/flutter/issues/14288.

**Closed by goderbauer** 2019-09-18 22:03 UTC
Labels: framework, severe: rendering
