### ISSUE TITLE
microbenchmarks_ios timing out ~40% of the time, white screen

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#76163] opened 2021-02-17 00:01 UTC
https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/godofredoc_google.com/15e28fdf5416728310250fe80d868d178b795977279a5341418a44dcbd936cb4/+/annotations

The runner is not progressing from:

```
[microbenchmarks_ios] [STDOUT] [  +58 ms] Successfully connected to service protocol: http://127.0.0.1:53924/
[microbenchmarks_ios] [STDOUT] [  +14 ms] Application running.
[microbenchmarks_ios] [STDOUT] [   +5 ms] Connected to iPhone
[microbenchmarks_ios] [STDOUT] [   +2 ms] Flutter run key commands.
[microbenchmarks_ios] [STDOUT] [   +1 ms] h Repeat this help message.
[microbenchmarks_ios] [STDOUT] [        ] c Clear the screen
[microbenchmarks_ios] [STDOUT] [        ] q Quit (terminate the application on the device).
[microbenchmarks_ios] [STDOUT] [        ] An Observatory debugger and profiler on iPhone is available at: http://127.0.0.1:53927/7vUpRFk2E18=/
```

Split off from https://github.com/flutter/flutter/issues/75851, which will track the task never being killed.

**Comment by jmagman** [comment] 2021-02-17 00:02
I tried to reproduce this locally and couldn't.

**Comment by godofredoc** [comment] 2021-03-02 23:50
Seems to happenning very frequently ~40%. Are there any logs that we can collect to help triage?

https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20microbenchmarks_ios

**Comment by jmagman** [comment] 2021-03-03 00:09
A screenshot from the device while it is hanging would be helpful.
I wish we could automatically collect that before the task times out.

**Comment by godofredoc** [comment] 2021-03-03 18:51
Moving this one as P1 as it is the main contributor to Flutter tree closures.

**Comment by jmagman** [comment] 2021-03-04 01:56
I tried this again and I can't get it to fail locally.  Will probably need to ssh into a machine again.

**Comment by godofredoc** [comment] 2021-03-04 02:42
Replicated the issue using led. The application starts opening but it gets up to the white screen and then it hangs there.

**Comment by jmagman** [comment] 2021-03-04 03:00
@godofredoc Are there particular machines it always fails on?

**Comment by jmagman** [comment] 2021-03-04 03:02
> @godofredoc Are there particular machines it always fails on?

Never mind I just looked myself, it seems to reproduce all over the place.

**Comment by godofredoc** [comment] 2021-03-04 03:13
I'm trying to reproduce again while collecting idevicesyslog I hope it contains some some hints about the problem.

**Comment by jmagman** [comment] 2021-03-04 03:21
I reproduced it! The screen was white, but I touched the screen and that kicked something and it loaded the UI.  I actually have a trace of it while it's stuck

[dart_devtools_2021_3_3-1614827796628000.json.txt](https://github.com/flutter/flutter/files/6080657/dart_devtools_2021_3_3-1614827796628000.json.txt)

**Comment by jmagman** [comment] 2021-03-04 03:25
> I'm trying to reproduce again while collecting idevicesyslog I hope it contains some some hints about the problem.

@godofredoc Unfortunately `idevicesyslog` doesn't work on iOS 13 and above.  We would be getting logs from the debugger if the app was logging anything, since it's attached.
```
[microbenchmarks_ios] [STDOUT] [  +48 ms] (lldb)     run
[microbenchmarks_ios] [STDOUT] [ +170 ms] success
```

**Comment by godofredoc** [comment] 2021-03-04 05:41
I got some logs with the latest idevicesyslog version installed with brew. Could it be that we need to upgrade flutter idevicesyslog to the latest version?  

Attached the log
[microbenchmarks_log.txt](https://github.com/flutter/flutter/files/6081131/microbenchmarks_log.txt)

**Comment by jmagman** [comment] 2021-03-04 20:10
Oh nice! I don't even see the code change where they started supporting that lockdown service.

**Comment by chinmaygarde** [comment] 2021-03-08 18:37
@jmagman From the trace attached, No frames were scheduled. Could it be one one of those benchmarks that starts paused and then starts its workload after a service protocol request? Not sure why things got kicked off when you touched the screen however. Can you attach a trace when the UI starts rendering?

**Comment by jmagman** [comment] 2021-03-10 03:00
@godofredoc said in chat:
> The issue can be easily replicated by running the test several times, usually it replicate in less than 10 iterations.

I've been trying to reproduce this for an hour, my local setup doesn't seem to do it anymore.
@zanderso I recommend getting someone on the engine team to work with @godofredoc to figure out which host machine is the best candidate, SSH in, and just reproduce it there.  It won't be possible to touch the device, but at least you have a debugger attached and can poke at the app however is helpful.

**Comment by godofredoc** [comment] 2021-03-11 01:18
@jmagman can you please share the command you are using to collect the traces?

**Comment by jmagman** [comment] 2021-03-11 01:44
I went to the observatory service URL ("An Observatory debugger and profiler on <> is available at: http://127.0.0.1:60931/91n_cdDMTRI=/") , then timeline
![Screen Shot 2021-03-10 at 5 43 21 PM](https://user-images.githubusercontent.com/682784/110722951-1cb50600-81c8-11eb-94b3-2439bfa73961.png)
"Save" button to save the current results, or "Refresh" to get the results since the last run.

I'm not sure what "Recorded Streams" @chinmaygarde or @zanderso would find helpful.

**Comment by chinmaygarde** [comment] 2021-03-15 17:53
Per @jason-simmons, this is not occurring at 40%. The [trace in a previous comment](https://github.com/flutter/flutter/issues/76163#issuecomment-790257671) shows that the engine didn't get any request to render a frame. Since there isn't any actionable information to make progress on this issue, @zanderso is going to find an owner to track this down. Given the rate of occurrence, I am lowering the priority of this issue.

**Comment by mdebbar** [comment] 2021-03-15 21:12
I saw another recipe timeout but in Mac_android this time: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20home_scroll_perf__timeline_summary/529/overview (issue filed [here](https://github.com/flutter/flutter/issues/78243)). Not sure if it's the same cause or not. It passed after re-running.

**Closed** 2023-04-21 20:53 UTC
Labels: team, platform-ios, engine, passed first triage, team: benchmark, P3
