### ISSUE TITLE
CJK font appears upward shifted for ListTile with subtitle

### ISSUE THREAD

**Issue by tamcy** [flutter/flutter#19063] opened 2018-07-04 04:15 UTC
I am trying to replicate Android's setting screen in Flutter. 

![flutter_native_setting](https://user-images.githubusercontent.com/959433/42255724-c1e0f538-7f7f-11e8-9afe-f6769cfcbd66.png)

I reproduced the last 4 items. Here's how it looks like:

![listtile-2](https://user-images.githubusercontent.com/959433/42256018-52e17f48-7f81-11e8-8137-3b96447a0c06.png)

The problem is mainly on the Chinese part. It appears that CJK text appears shifted a little bit downward for single line items. But for items with title and subtitle, CJK text appears upward shifted.

![measure_chi](https://user-images.githubusercontent.com/959433/42256131-f0513962-7f81-11e8-839e-376f79cdf714.png)

This is also true for English text, albeit less apparent:
![measure_eng](https://user-images.githubusercontent.com/959433/42256130-ef016f8c-7f81-11e8-8fd3-6f3b3bf1f776.png)

Note that I'm not asking for a pixel-perfect alignment (different icon may produce a different visual center). But the Chinese texts in the ListTile does look far too upward to me. And texts in title-only list tiles shifted the opposite direction makes it more disturbing.

**Comment by zoechi** [comment] 2019-02-14 10:04
@tamcy It's a while since this issue was created and a lot of things have changed.
Are you still seeing this with `master` channel?

**Comment by tamcy** [comment] 2019-02-15 14:53
Thanks for the news! So I have switched to the master channel (framework rev. `67cf21577f`; engine rev. `3757390fa4`) and see how the latest ListTile looks like.

Left/top: MaterialApp locale set to English, with English elements:
Right/bottom: MaterialApp locale still in English, with Chinese elements:

<img src="https://user-images.githubusercontent.com/959433/52863287-6f02d480-3172-11e9-8fa3-617bf11b850e.png" width="300"> <img src="https://user-images.githubusercontent.com/959433/52863306-788c3c80-3172-11e9-8889-88659d1a7d34.png" width="300">

First of all, there seems to be a regression - the icon is no longer aligned to the middle of the container when subtitle isn't empty. The texts looks fine though - the spacing is now much closer to the native version.

(The only issue here is that when the `MaterialApp` locale is set to English, the Chinese font shown isn't acknowledging the device's fallback chain, nor the order of `supportedLocales` of the `MaterialApp`.  Here the Simplified Chinese variant is used, although the device is set to Traditional Chinese. And this behavior seems not overridable by the developer. Anyway this is another issue.)

Now the bad news. When `MaterialApp` locale is set to Chinese (Traditional), the Chinese text in the ListTile looks like this:
<img src="https://user-images.githubusercontent.com/959433/52863328-893cb280-3172-11e9-913d-11f88a3ea341.png" width="400">

The situation seems worse, and measurement supports my observation.
![4](https://user-images.githubusercontent.com/959433/52862881-48906980-3171-11e9-8df2-92ada6458b92.png)

Note that the problem isn't limited to ListTile:
![05](https://user-images.githubusercontent.com/959433/52863794-b5a4fe80-3173-11e9-917d-6b8fbc3f7244.png)

**Comment by GaryQian** [comment] 2019-03-11 23:37
I can take a look at this, do you think you can provide a minimal (or full) test app that has the implementation necessary to reproduce this?

**Comment by tamcy** [comment] 2019-03-14 02:36
@GaryQian Sure, the test app can be found [here](https://github.com/tamcy/flutter-issue-19063). Thank you!

**Comment by GaryQian** [comment] 2019-07-08 17:45
Should be fixed by https://github.com/flutter/flutter/pull/35493

**Closed by GaryQian** 2019-07-08 17:45 UTC
Labels: a: typography, engine
