### ISSUE TITLE
[IOS] App Crashes with error EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by Zeming404** [flutter/flutter#105575] opened 2022-06-08 07:37 UTC
## Steps to Reproduce
I haven't found a way to reproduce it. The crash got reported to Firebase console.

</details>

<details>
  <summary>Logs</summary>

```
Crashed: io.flutter.1.raster
0  Flutter                        0x44134 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
1  Flutter                        0x405cb0 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
2  Flutter                        0x403494 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
3  Flutter                        0x405c9c (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
4  Flutter                        0x403494 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
5  Flutter                        0x406e9c (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
6  Flutter                        0x403494 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
7  Flutter                        0x403214 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
8  Flutter                        0x3f9080 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
9  Flutter                        0x341c44 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
10 Flutter                        0x342aa4 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
11 Flutter                        0x342110 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
12 Flutter                        0x349f00 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
13 Flutter                        0x2ee068 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
14 Flutter                        0x2f1098 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
15 CoreFoundation                 0xaf168 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
16 CoreFoundation                 0x33144 __CFRunLoopDoTimer + 1064
17 CoreFoundation                 0x2d8f0 __CFRunLoopDoTimers + 320
18 CoreFoundation                 0xbfa0 __CFRunLoopRun + 1936
19 CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
20 Flutter                        0x2f0f74 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
21 Flutter                        0x2f0788 (缺少 UUID e01ae2d7b4293d2bad99555f1db36746)
22 libsystem_pthread.dylib        0x19ac _pthread_start + 148
23 libsystem_pthread.dylib        0xe68 thread_start + 8
```

```
```

```
[✓] Flutter (Channel master, 2.5.3, on macOS 12.2.1 21D62 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/ming/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 months ago), 2021-10-15 10:46:35
      -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/ming/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2.1, Build version 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.11+0-b60-7590822)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Ming’s iPhone 12 (mobile) • 00008101-000339082143003A            •
      ios            • iOS 15.3.1 19D52
    • iPhone Xs Max (mobile)    • 4568A6E1-3975-4F1E-B130-2F68D5F1034C •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4
      (simulator)
    • Chrome (web)              • chrome                               •
      web-javascript • Google Chrome 102.0.5005.61

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-06-08 08:23
Hello @Zeming404. Looks like you're on 2.5. This issue may be already fixed in 3.0.1. Please upgrade and confirm if that's the case.

**Comment by exaby73** [comment] 2022-06-08 10:18
> how can i judge the problem is solved

I'm not judging. It could be an issue in Flutter (I am assuming from the first line mentioned something about "raster"). But unfortunately, we only try to verify issues on stable. If it's reproducing on an older version, it could be already fixed though I'm not saying it is. Sorry for the misunderstanding

**Comment by Zeming404** [comment] 2022-06-08 11:28
> > how can i judge the problem is solved
> 
> I'm not judging. It could be an issue in Flutter (I am assuming from the first line mentioned something about "raster"). But unfortunately, we only try to verify issues on stable. If it's reproducing on an older version, it could be already fixed though I'm not saying it is. Sorry for the misunderstanding


I have got some feedback with the same stack trace log above. I can't reproduce it. 
Do you know what does 'Missing UUID e01ae2d7b4293d2bad99555f1db36746' mean? I want to get more info from stack.

**Comment by exaby73** [comment] 2022-06-08 15:28
@flutter-symbolizer-bot force ios flutter#v2.5.3 https://github.com/flutter/flutter/issues/105575#issue-1264327271

**Comment by exaby73** [comment] 2022-06-08 15:35
Hello @Zeming404. From the symbolized traces, I am not sure exactly what is going on. But doing a quick search on other issues, there were a few results that might be related:

#105315
#92550
#71405
#50097

This is a long shot but do any of these issues seem to reproduce your one?

**Comment by Zeming404** [comment] 2022-06-09 08:38
> Hello @Zeming404. From the symbolized traces, I am not sure exactly what is going on. But doing a quick search on other issues, there were a few results that might be related:
> 
> #105315 #92550 #71405 #50097
> 
> This is a long shot but do any of these issues seem to reproduce your one?

Thanks. Now I am trying to upgrade flutter at the same time.
There're several events on firebase with the same error 'EXC_BAD_ACCESS KERN_INVALID_ADDRESS'. Their stack traces look similar but the address offset are different. Hope it helps.

<details>
<summary>Logs</summary>

```
Crashed: io.flutter.1.ui
0  Flutter                        0x5f22a0 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
1  Flutter                        0x5f0e78 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
2  Flutter                        0x5e4e5c (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
3  Flutter                        0x5e67a8 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
4  Flutter                        0x4e8a38 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
5  Flutter                        0x345e34 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
6  Flutter                        0x33baa8 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
7  Flutter                        0x2ee068 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
8  Flutter                        0x2f1098 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
9  CoreFoundation                 0xaf168 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
10 CoreFoundation                 0x33144 __CFRunLoopDoTimer + 1064
11 CoreFoundation                 0x2d8f0 __CFRunLoopDoTimers + 320
12 CoreFoundation                 0xbfa0 __CFRunLoopRun + 1936
13 CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
14 Flutter                        0x2f0f74 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
15 Flutter                        0x2f0788 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
16 libsystem_pthread.dylib        0x19ac _pthread_start + 148
17 libsystem_pthread.dylib        0xe68 thread_start + 8
```
</details>

<details>
<summary>Logs</summary>

```
Crashed: io.flutter.1.raster
0  Flutter                        0x97f6c (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
1  Flutter                        0x405be0 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
2  Flutter                        0x33b1e4 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
3  Flutter                        0x4025b0 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
4  Flutter                        0x406d5c (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
5  Flutter                        0x33b1e4 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
6  Flutter                        0x4025b0 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
7  Flutter                        0x4031b4 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
8  Flutter                        0x33b1e4 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
9  Flutter                        0x341618 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
10 Flutter                        0x342af4 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
11 Flutter                        0x342110 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
12 Flutter                        0x349f00 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
13 Flutter                        0x2ee068 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
14 Flutter                        0x2f1098 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
15 CoreFoundation                 0xa48c0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
16 CoreFoundation                 0xa44bc __CFRunLoopDoTimer + 1076
17 CoreFoundation                 0xa390c __CFRunLoopDoTimers + 328
18 CoreFoundation                 0x9d6c0 __CFRunLoopRun + 1944
19 CoreFoundation                 0x9c9f4 CFRunLoopRunSpecific + 600
20 Flutter                        0x2f0f74 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
21 Flutter                        0x2f0788 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
22 libsystem_pthread.dylib        0x1bfc _pthread_start + 320
23 libsystem_pthread.dylib        0xa758 thread_start + 8
```
</details>

<details>
<summary>Logs</summary>

```
Crashed: io.flutter.1.raster
0  Flutter                        0x28d990 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
1  Flutter                        0x19b79c (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
2  Flutter                        0x1e3fb0 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
3  Flutter                        0x19d184 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
4  Flutter                        0x1920c4 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
5  Flutter                        0x1924b0 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
6  Flutter                        0x58c34 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
7  Flutter                        0x4f63f0 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
8  Flutter                        0x409fc4 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
9  Flutter                        0x341d3c (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
10 Flutter                        0x342aa4 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
11 Flutter                        0x342110 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
12 Flutter                        0x349f00 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
13 Flutter                        0x2ee068 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
14 Flutter                        0x2f1098 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
15 CoreFoundation                 0xae678 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
16 CoreFoundation                 0x32654 __CFRunLoopDoTimer + 1064
17 CoreFoundation                 0x2ce00 __CFRunLoopDoTimers + 320
18 CoreFoundation                 0xb4b0 __CFRunLoopRun + 1936
19 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
20 Flutter                        0x2f0f74 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
21 Flutter                        0x2f0788 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
22 libsystem_pthread.dylib        0x19ac _pthread_start + 148
23 libsystem_pthread.dylib        0xe68 thread_start + 8
```
</details>

**Comment by exaby73** [comment] 2022-06-09 13:10
@flutter-symbolizer-bot force ios arm64 flutter#v3.0.1 this

<details>
<summary>Logs</summary>

```
Crashed: io.flutter.1.ui
0  Flutter                        0x5f22a0 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
1  Flutter                        0x5f0e78 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
2  Flutter                        0x5e4e5c (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
3  Flutter                        0x5e67a8 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
4  Flutter                        0x4e8a38 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
5  Flutter                        0x345e34 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
6  Flutter                        0x33baa8 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
7  Flutter                        0x2ee068 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
8  Flutter                        0x2f1098 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
9  CoreFoundation                 0xaf168 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
10 CoreFoundation                 0x33144 __CFRunLoopDoTimer + 1064
11 CoreFoundation                 0x2d8f0 __CFRunLoopDoTimers + 320
12 CoreFoundation                 0xbfa0 __CFRunLoopRun + 1936
13 CoreFoundation                 0x1f6b8 CFRunLoopRunSpecific + 600
14 Flutter                        0x2f0f74 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
15 Flutter                        0x2f0788 (Missing UUID e01ae2d7b4293d2bad99555f1db36746)
16 libsystem_pthread.dylib        0x19ac _pthread_start + 148
17 libsystem_pthread.dylib        0xe68 thread_start + 8
```

</details>

**Comment by exaby73** [comment] 2022-06-09 13:32
The logs you shared, just to confirm were from Flutter 3.0.1?

**Comment by Zeming404** [comment] 2022-06-10 01:10
> The logs you shared, just to confirm were from Flutter 3.0.1?

Sorry for the misunderstanding. The logs are all from Flutter 2.5.3.

**Comment by exaby73** [comment] 2022-06-10 04:14
Please upgrade to 3.0.1. It doesn't make sense to continue testing on 2.5.3, which is 2 versions old at this point.

**Comment by jacopofranza** [comment] 2022-06-12 14:02
I'm encountering the same problem using flutter 3.0.1 stable, also tested in version 3.1.0 beta.

**Comment by exaby73** [comment] 2022-06-15 06:17
Could you send the crash logs from stable (3.0.1) and/or master (3.1.0) once again so that I can symbolize it?

**Closed** 2022-07-01 04:32 UTC
Labels: r: timeout
