### ISSUE TITLE
Fontsize is extremely small when using Text on Image within a Stack and Gridview

### ISSUE THREAD

**Issue by rossedwardsus** [flutter/flutter#99430] opened 2022-03-02 21:03 UTC
I have a gridview with Stack so as to create a text on top of image effect. So i have 3 objects within the Stack.  Each one works properly on its own.  The image and transparent block also work as well as the transparent block and text.  As soon as i add the image and text though the text disappears.  The only way to get it to show is to make the fontsize massive.  Maybe 200 or 300.  If its normal size it simply is too small to see.

Is this a bug or do i need another container around the text?  I have tried several but none worked.

This is the piece of code that causes the problem.

<details>
<summary> code </summary>

```

GridView.count(
              shrinkWrap: true,
              crossAxisCount: 2,
              children: [
                FittedBox(
                    /*child: Container(
                        decoration: BoxDecoration(
                            image: DecorationImage(
                                image: AssetImage(
                                    "images/Conflict_Mitigation.jpg"),
                                scale: 1.0,
                                fit: BoxFit.cover))),*/

                    child:
                        Stack(alignment: Alignment.center, fit: StackFit.expand,
                            //overflow: Overflow.visible,
                            children: [
                          //    scale: 1.0, fit: BoxFit.cover),
                          Flexible(
                              child: Image.asset(
                                  "images/Conflict_Mitigation.jpg")),
                          Positioned.fill(
                              child: Container(
                                  color: Colors.blue.withOpacity(.5))),
                          Flexible(
                              //fit: BoxFit.contain,
                              //height: 1000,
                              //width: 1000,
                              //fit: BoxFit.contain,
                              child: Text("here",
                                  style: TextStyle(
                                      color: Colors.yellow,
                                      fontWeight: FontWeight.bold,
                                      fontSize: 20))),

                          /*Positioned(
                              left: 200,
                              top: 20,
                              child: Container(
                                  alignment: Alignment.center,
                                  child: Text("hello",
                                      style: TextStyle(
                                          color: Colors.yellow,
                                          fontWeight: FontWeight.bold,
                                          fontSize: 12)))),*/
                        ]),
                    fit: BoxFit.fill),
                FittedBox(
                    child: Image.asset("images/Community_Based_Knowledge.jpg"),
                    fit: BoxFit.fill),
                Text("hello"),
                Text("hello")
              ],
            ),

```

</details>

**Comment by rossedwardsus** [comment] 2022-03-02 21:04
This was actually mentioned 2 years ago in this stackoverflow comment.

https://stackoverflow.com/questions/51674962/how-to-make-text-as-big-as-the-width-allows-in-flutter

The middle answer is exactly what i have had to do.

**Comment by darshankawar** [comment] 2022-03-03 07:27
@rossedwardsus 
Thanks for the report. I tried to run your code sample but its giving me compile errors most probably due to the way the code is implementation. For example: 

```
Incorrect use of ParentDataWidget.
The ParentDataWidget Flexible(flex: 1) wants to apply ParentData of type FlexParentData to a
RenderObject, which has been set up to accept ParentData of incompatible type StackParentData.
Usually, this means that the Flexible widget has the wrong ancestor RenderObjectWidget. Typically,
Flexible widgets are placed directly inside Flex widgets.
The offending Flexible is currently placed inside a Stack widget.

```

But anyways, since you mentioned that using `FittedBox`, the issue is resolved. The widget is used when we want to scale its child based on the `fit` value we pass, so in your case, `fit: BoxFit.fill` would scale the text to fit the available space making the fontsize proper.

I'll close this issue as resolved. If you disagree, write in comments and I'll reopen it.

**Comment by rossedwardsus** [comment] 2022-03-03 12:55
Hello.  How is this issue being closed exactly?  This was a code snippet and not the entire screen which is why it didnt work.  It didnt even include the widget definition.  I linked a stackoverlow question from two ears ago that mentioned the same problem.

Are there any solutions to this?

I tried FittedBox and it didnt work.  I have tried expanded, Flexible, literally everything and nothing works.

Thank you.

**Comment by darshankawar** [comment] 2022-03-03 13:20
Thanks for the feedback @rossedwardsus. Reopening.


> The middle answer is exactly what i have had to do.

This got me confused and assumed that `FittedBox` resolved your issue. 

> This was a code snippet and not the entire screen which is why it didnt work. It didnt even include the widget definition

Can you provide a complete minimal reproducible code sample again that shows the current behavior ?

**Comment by rossedwardsus** [comment] 2022-03-03 13:51
Heres the full code for the widget.  There is debug code included.  I duplicated the stack outside of the gridview as a test and it worked properly.  Which is why that code is there.


import 'package:flutter/material.dart';

class MainCategoriesPage extends StatefulWidget {
  //const MainCategoriesPage({Key? key, required this.title}) : super(key: key);
  const MainCategoriesPage({Key? key}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  //final String title;

  @override
  State<MainCategoriesPage> createState() => _MainCategoriesPageState();
}

class _MainCategoriesPageState extends State<MainCategoriesPage> {
  int _counter = 0;

  final List<Map> myCategories = [
    {"id": 1, "image": "", "text": "Conflict Mitigation"},
    {"id": 2, "image": "", "text": "Community-Based Knowledge"},
    {"id": 3, "image": "", "text": "Organizational Development"},
    {"id": 4, "image": "", "text": "Knowledge Sharing"}
  ];
  //List.generate(4, (index) => {"id": index, "category": "category $index", });

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text("widget.title"),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
            // Center is a layout widget. It takes a single child and positions it
            // in the middle of the parent.
            child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Image.asset("images/Login_Header.png"),
            Text("Welcome to Lion Guardians",
                style:
                    const TextStyle(fontWeight: FontWeight.bold, fontSize: 25)),
            Stack(alignment: Alignment.bottomCenter,
                //fit: StackFit.expand,
                //overflow: Overflow.visible,
                children: [
                  //    scale: 1.0, fit: BoxFit.cover),
                  //Positioned.fill(
                  //    child: Container(
                  //        color: Colors.blue.withOpacity(.5))),
                  Image(
                      fit: BoxFit.cover,
                      image: AssetImage("images/Conflict_Mitigation.jpg")),
                  Text("here",
                      style: TextStyle(
                          color: Colors.yellow,
                          fontWeight: FontWeight.bold,
                          fontSize: 22)),

                  /*Positioned(
                              left: 200,
                              top: 20,
                              child: Container(
                                  alignment: Alignment.center,
                                  child: Text("hello",
                                      style: TextStyle(
                                          color: Colors.yellow,
                                          fontWeight: FontWeight.bold,
                                          fontSize: 12)))),*/
                ]),
            Container(
                height: 200,
                child: Center(
                    //width: 1000,
                    //height: 100,
                    child: Text("Testing",
                        style: const TextStyle(
                            //height: 20,
                            fontWeight: FontWeight.bold,
                            fontSize: 25),
                        textAlign: TextAlign.center))),
            GridView.count(
              shrinkWrap: true,
              crossAxisCount: 2,
              children: [
                FittedBox(
                    /*child: Container(
                        decoration: BoxDecoration(
                            image: DecorationImage(
                                image: AssetImage(
                                    "images/Conflict_Mitigation.jpg"),
                                scale: 1.0,
                                fit: BoxFit.cover))),*/

                    child:
                        Stack(alignment: Alignment.center, fit: StackFit.expand,
                            //overflow: Overflow.visible,
                            children: [
                          //    scale: 1.0, fit: BoxFit.cover),
                          Flexible(
                              child: Image.asset(
                                  "images/Conflict_Mitigation.jpg")),
                          Positioned.fill(
                              child: Container(
                                  color: Colors.blue.withOpacity(.5))),
                          Flexible(
                              //fit: BoxFit.contain,
                              //height: 1000,
                              //width: 1000,
                              //fit: BoxFit.contain,
                              child: Text("here",
                                  style: TextStyle(
                                      color: Colors.yellow,
                                      fontWeight: FontWeight.bold,
                                      fontSize: 20))),

                          /*Positioned(
                              left: 200,
                              top: 20,
                              child: Container(
                                  alignment: Alignment.center,
                                  child: Text("hello",
                                      style: TextStyle(
                                          color: Colors.yellow,
                                          fontWeight: FontWeight.bold,
                                          fontSize: 12)))),*/
                        ]),
                    fit: BoxFit.fill),
                FittedBox(
                    child: Image.asset("images/Community_Based_Knowledge.jpg"),
                    fit: BoxFit.fill),
                Text("hello"),
                Text("hello")
              ],
            ),
            Container(
                margin: const EdgeInsets.only(left: 30, right: 30),
                child: TextField(
                  decoration: InputDecoration(
                    labelText: "Email",
                  ),
                )),
            Container(
                margin: const EdgeInsets.only(left: 30, right: 30),
                child: TextField(
                  decoration: InputDecoration(
                    labelText: "Password",
                  ),
                )),
            Container(
                margin: const EdgeInsets.only(top: 50),
                child: ElevatedButton(
                    child: Text("Login"),
                    onPressed: () {},
                    style: ElevatedButton.styleFrom(
                        primary: Color(0xff3c1803),
                        minimumSize: Size(250, 50))))
          ],
        )),
      ),
    );
  }
}

**Comment by darshankawar** [comment] 2022-03-04 05:48
@rossedwardsus 
Thanks for the code sample. Since I don't have the said images you used in the code sample, I used a sample png everywhere and got something like below:

<img width="754" alt="Screenshot 2022-03-04 at 11 16 27 AM" src="https://user-images.githubusercontent.com/67046386/156706956-e83eab71-f34d-408e-ad3a-8f6eb55ded0a.png">

I don't see the text you declared below:

```
final List<Map> myCategories = [
    {"id": 1, "image": "", "text": "Conflict Mitigation"},
    {"id": 2, "image": "", "text": "Community-Based Knowledge"},
    {"id": 3, "image": "", "text": "Organizational Development"},
    {"id": 4, "image": "", "text": "Knowledge Sharing"}
  ];
```
To properly replicate it, does it need to have specific images you used ? 

Also, can you provide your `flutter doctor -v` and platform on which you are running this ?

**Comment by rossedwardsus** [comment] 2022-03-04 14:39
The text call is within a Stack call towards the bottom of the code i included. It is not within the code you included. That stack is within a gridview.  When stack and gridview are combined, the text is tiny.

**Comment by darshankawar** [comment] 2022-03-07 05:45
@rossedwardsus 
I just used the code you shared as-is so I am not sure when you say `It is not within the code you included`.

Also 

> can you provide your `flutter doctor -v` and platform on which you are running this ?

**Closed** 2022-03-28 07:10 UTC
Labels: waiting for customer response, in triage
