### ISSUE TITLE
Plugins do not support AndroidX

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#23995] opened 2018-11-06 13:35 UTC
I have a flutter project. Inside of its `android` folder I have a lot of android code, including background processing classes and some native UI. I updated this code to use the new `androidX `packages.

Now, some of the plugins stopped working. A example is the `permission_handler `plugin.

```
permissionhandler\PermissionHandlerPlugin.kt: (10, 31): Unresolved reference: ActivityCompat
permissionhandler\PermissionHandlerPlugin.kt: (11, 27): Unresolved reference: content
permissionhandler\PermissionHandlerPlugin.kt: (152, 37): Unresolved reference: ContextCompat
permissionhandler\PermissionHandlerPlugin.kt: (191, 20): Unresolved reference: ActivityCompat
permissionhandler\PermissionHandlerPlugin.kt: (235, 13): Unresolved reference: ActivityCompat`
```

I believe this is because the native Android part of my app is using the AndroidX packages, since those plugins are still using the old support library. In the current state, it is impossible to me to roll back to the support library.

Also, when I add the `camera` plugin I get the following error:
```
error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
```

Is this a intended behavior? Can someone give me a light? 

```
[√] Flutter (Channel beta, v0.9.4, on Microsoft Windows [versÃ£o 10.0.17134.376], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2018.2)
[√] Connected devices (1 available)

• No issues found!`
```

**Comment by jiechic** [comment] 2018-12-18 07:10
I also have this problem ，when i use flutter module for my android project，use flutter packages get，then flutter android source would be replace by default and it is use support library ，not the androidx library

**Comment by dnfield** [comment] 2018-12-20 17:52
related to #23586.

We're working on making it easier to update this stuff for the engine, but we'll have to think of plugins as well...

**Comment by japborst** [comment] 2019-01-15 02:08
Any updates on supporting for AndroidX?

**Comment by dnfield** [comment] 2019-01-25 19:51
This is done now for all first party plugins, but keep in mind this may be an issue for various third party plugins out there.  If you find other issues with those, please open an issue in the appropriate repository for it.

**Comment by mklim** [comment] 2019-01-25 20:20
I am still waiting to publish a few of the updated packages to pub. I'll reopen this and close it once it's published everywhere. /cc @kroikie 

 - location_background
 - cloud_functions
 - firebase_dynamic_links
 - firebase_performance
 - firebase_remote_config

**Comment by dnfield** [comment] 2019-01-28 23:08
In case it's not clear to everyone here - we had a snafu on the versioning related to this.  Implementing this is a breaking change for existing clients, and produces really unhelpful gradle error messages.

We're rolling back the publications that fixed this, and are working to roll out properly versioned ones that fix it.  @mklim is leading that effort right now.

**Comment by mklim** [comment] 2019-01-28 23:58
The semantic versioning fixes have been published.

- url_launcher: `4.2.0+3` (or `^4.2.0`) for the original, `5.0.0` for the migration
- google_sign_in: `3.3.0+1` (or `^3.3.0`) for the original, `4.0.0` for the migration
- firebase_storage: `1.1.0+1` (or `^1.1.0`) for the original, `2.0.0` for the migration
- firebase_messaging: `2.2.0+1` (or `^2.2.0`) for the original, `3.0.0` for the migration
- firebase_database: `1.1.0+1` (or `^1.1.0` for the original), `2.0.0` for the migration
- firebase_analytics: `1.2.0+1` (or `^1.2.0` for the original), `2.0.0` for the migration

**Comment by mklim** [comment] 2019-01-29 00:42
The remaining plugins [here](https://github.com/flutter/flutter/issues/23995#issuecomment-457713599) have also been updated (/cc @Asoseil). Minus `location_background`, which hadn't been ever published in the first place.

**Comment by ramyku** [comment] 2019-01-30 10:37
> The semantic versioning fixes have been published.
> 
> * url_launcher: `4.2.0+3` (or `^4.2.0`) for the original, `5.0.0` for the migration
> * google_sign_in: `3.3.0+1` (or `^3.3.0`) for the original, `4.0.0` for the migration
> * firebase_storage: `1.1.0+1` (or `^1.1.0`) for the original, `2.0.0` for the migration
> * firebase_messaging: `2.2.0+1` (or `^2.2.0`) for the original, `3.0.0` for the migration
> * firebase_database: `1.1.0+1` (or `^1.1.0` for the original), `2.0.0` for the migration
> * firebase_analytics: `1.2.0+1` (or `^1.2.0` for the original), `2.0.0` for the migration



> The semantic versioning fixes have been published.
> 
> * url_launcher: `4.2.0+3` (or `^4.2.0`) for the original, `5.0.0` for the migration
> * google_sign_in: `3.3.0+1` (or `^3.3.0`) for the original, `4.0.0` for the migration
> * firebase_storage: `1.1.0+1` (or `^1.1.0`) for the original, `2.0.0` for the migration
> * firebase_messaging: `2.2.0+1` (or `^2.2.0`) for the original, `3.0.0` for the migration
> * firebase_database: `1.1.0+1` (or `^1.1.0` for the original), `2.0.0` for the migration
> * firebase_analytics: `1.2.0+1` (or `^1.2.0` for the original), `2.0.0` for the migration

Are the versioning fixes also applicable to firebase_ml_vision package?

**Comment by ramyku** [comment] 2019-01-30 10:39
I am getting the following error message when using the firebase_ml_vision package 

> BarcodeDetector.java:5: error: cannot find symbol

**Comment by hukid** [comment] 2019-02-04 20:55
Hi, we have a third party plugin and our customers start hitting this issue when they migrate to Androidx. We'd like to fix this issue ASAP, is there a guideline of how to update plugin to support AndroidX migration? Or can we suggest a workaround to the customer?

Another question is - how do we support those customers who haven't migrated?

**Comment by RussellZornes** [comment] 2019-02-05 07:54
Getting the following error when using cloud_functions 0.1.0 package.

```
cloud_functions-0.1.0\android\src\main\java\io\flutter\plugins\firebase\cloudfunctions\cloudfunctions\CloudFunctionsPlugin.java:7: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation

```

[√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.2.0 at C:\dev\libraries\flutter2\flutter
    • Framework revision 06b979c4d5 (11 days ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\dev\libraries\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\dev\libraries\android-sdk
    • Java binary at: C:\dev\tools\android-studio-ide-171.4402976-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\dev\tools\android-studio-ide-171.4402976-windows\android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

• No issues found!

**Comment by Telthem89** [comment] 2019-02-10 12:32
flutter run
Launching lib/main.dart on Telthem in debug mode...
Initializing gradle...                                          34.6s
Resolving dependencies...                                       369.1s
Gradle task 'assembleDebug'...
[Fatal Error] support-core-ui-26.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] support-compat-26.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] support-core-utils-26.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] support-compat-26.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] support-core-ui-26.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] support-core-utils-26.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] support-fragment-26.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] support-fragment-26.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] support-annotations-26.1.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] support-annotations-26.1.0.pom:2:1: Content is not allowed in prolog.
         *********************************************************
WARNING: This version of google_maps_flutter will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not resolve com.android.support:support-compat:26.1.0.
  Required by:
      project :app > project :google_maps_flutter > com.google.android.gms:play-services-maps:15.0.1 > com.google.android.gms:play-services-basement:15.0.1 > com.android.support:support-v4:26.1.0
      project :app > project :google_maps_flutter > com.google.android.gms:play-services-maps:15.0.1 > com.google.android.gms:play-services-basement:15.0.1 > com.android.support:support-v4:26.1.0 > com.android.support:support-media-compat:26.1.0
   > Could not resolve com.android.support:support-compat:26.1.0.
      > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/support/support-compat/26.1.0/support-compat-26.1.0.pom
         > Content is not allowed in prolog.
   > Could not resolve com.android.support:support-compat:26.1.0.
      > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/support/support-compat/26.1.0/support-compat-26.1.0.pom
         > Content is not allowed in prolog.
> Could not resolve com.android.support:support-core-utils:26.1.0.
  Required by:
      project :app > project :google_maps_flutter > com.google.android.gms:play-services-maps:15.0.1 > com.google.android.gms:play-services-basement:15.0.1 > com.android.support:support-v4:26.1.0
   > Could not resolve com.android.support:support-core-utils:26.1.0.
      > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/support/support-core-utils/26.1.0/support-core-utils-26.1.0.pom
         > Content is not allowed in prolog.
   > Could not resolve com.android.support:support-core-utils:26.1.0.
      > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/support/support-core-utils/26.1.0/support-core-utils-26.1.0.pom
         > Content is not allowed in prolog.
> Could not resolve com.android.support:support-core-ui:26.1.0.
  Required by:
      project :app > project :google_maps_flutter > com.google.android.gms:play-services-maps:15.0.1 > com.google.android.gms:play-services-basement:15.0.1 > com.android.support:support-v4:26.1.0
   > Could not resolve com.android.support:support-core-ui:26.1.0.
      > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/support/support-core-ui/26.1.0/support-core-ui-26.1.0.pom
         > Content is not allowed in prolog.
   > Could not resolve com.android.support:support-core-ui:26.1.0.
      > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/support/support-core-ui/26.1.0/support-core-ui-26.1.0.pom
         > Content is not allowed in prolog.
> Could not resolve com.android.support:support-fragment:26.1.0.
  Required by:
      project :app > project :google_maps_flutter > com.google.android.gms:play-services-maps:15.0.1 > com.google.android.gms:play-services-basement:15.0.1 > com.android.support:support-v4:26.1.0
   > Could not resolve com.android.support:support-fragment:26.1.0.
      > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/support/support-fragment/26.1.0/support-fragment-26.1.0.pom
         > Content is not allowed in prolog.
   > Could not resolve com.android.support:support-fragment:26.1.0.
      > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/support/support-fragment/26.1.0/support-fragment-26.1.0.pom
         > Content is not allowed in prolog.
> Could not resolve com.android.support:support-annotations:26.1.0.
  Required by:
      project :app > project :google_maps_flutter > com.google.android.gms:play-services-maps:15.0.1 > com.google.android.gms:play-services-basement:15.0.1 > com.android.support:support-v4:26.1.0 > com.android.support:support-media-compat:26.1.0
   > Could not resolve com.android.support:support-annotations:26.1.0.
      > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.pom
         > Content is not allowed in prolog.
   > Could not resolve com.android.support:support-annotations:26.1.0.
      > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.pom
         > Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
49.1s
Gradle task assembleDebug failed with exit code 1

**Comment by Telthem89** [comment] 2019-02-10 12:33
this error is killing me

**Comment by lhcdims** [comment] 2019-02-13 13:47
Following Error appears SUDDENLY with no code changes, after Flutter Packages Upgrade, I believe it's the new camera plugin bugs.


Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\2.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\3.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\4.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\5.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\6.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\7.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\8.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\9.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\10.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\11.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\12.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\13.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\14.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\15.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\16.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\17.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\18.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\19.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\20.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\21.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\22.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\23.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\24.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\25.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\26.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\27.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\28.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\29.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\30.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\31.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\32.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\33.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\34.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\35.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\36.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\37.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\38.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\39.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\40.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\41.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\42.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\43.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\44.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\45.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\46.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\47.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\48.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\49.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\50.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\51.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\52.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\53.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\54.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\55.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\56.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\57.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\58.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\59.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\60.jar, D:\flutter\mms01\build\app\intermediates\transforms\dexBuilder\debug\61.jar
         *********************************************************
WARNING: This version of camera will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by zoechi** [comment] 2019-02-13 16:25
You need either limit the version of the `camera` dependency in `pubspec.yaml` or follow the instructions to migrate to AndroidX.

`0.2.9+1` is the last version that does not depend on AndroidX (https://pub.dartlang.org/packages/camera#030) so

```yml
dependencies:
  camera: ^0.2.9
```
and running `flutter packages get` should fix it.
You might get similar errors for other plugins if you didn't apply such constraints.

**Comment by mklim** [comment] 2019-02-14 00:18
The plugins have all been updated to AndroidX, so I'm going to close this as fixed.

The official guide for migrating apps and plugins to work with AndroidX is [up on our website](https://flutter.io/docs/development/packages-and-plugins/androidx-compatibility). Please feel empowered to file new issues if you're still running into crashes after following the guide, or if the guide is unclear.

**Closed by mklim** 2019-02-14 00:18 UTC
Labels: customer: euclid, p: camera, p: first party, plugin, severe: crash, ▣ platform-android

**Comment by saravananmnm** [comment] 2019-03-05 13:04
geolocator:
after adding this dependency, am getting following error from androidx

Launching lib\main.dart on E6553 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
E:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-2.1.1\android\src\main\java\com\baseflow\flutter\plugin\geolocator\tasks\LastKnownLocationUsingLocationServicesTask.java:4: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
E:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-2.1.1\android\src\main\java\com\baseflow\flutter\plugin\geolocator\tasks\LocationUpdatesUsingLocationServicesTask.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
E:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-2.1.1\android\src\main\java\com\baseflow\flutter\plugin\geolocator\tasks\LastKnownLocationUsingLocationServicesTask.java:40: error: cannot find symbol
                    public void onFailure(@NonNull Exception e) {
                                           ^
  symbol: class NonNull
E:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator-2.1.1\android\src\main\java\com\baseflow\flutter\plugin\geolocator\tasks\LocationUpdatesUsingLocationServicesTask.java:62: error: cannot find symbol
                    public void onComplete(@NonNull Task<Void> task) {
                                            ^
  symbol: class NonNull
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by gitkarumuga** [comment] 2019-04-01 00:47
Faced the same issue. In my case, it's because of the "Firebase_auth" package used in a target Android SDK 28. As per the official documentation, the right version **0.7.0 and NOT THE LATEST VERSION**.

You can refer to the all packages which have conflict[here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#avoiding-androidx)

**Comment by Karlheinzniebuhr** [comment] 2019-05-27 15:19
Same issues here 

```
Launching lib\main.dart on SM G930F in debug mode...
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:14: error: package android.support.annotation does not exist
import android.support.annotation.MainThread;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:15: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:16: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:17: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:18: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:193: error: cannot find symbol
        int permissionState = ActivityCompat.checkSelfPermission(activity, Manifest.permission.ACCESS_FINE_LOCATION);
                              ^
  symbol:   variable ActivityCompat
  location: class LocationPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:198: error: cannot find symbol
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.ACCESS_FINE_LOCATION},
        ^
  symbol:   variable ActivityCompat
  location: class LocationPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:203: error: cannot find symbol
        return ActivityCompat.shouldShowRequestPermissionRationale(activity, Manifest.permission.ACCESS_FINE_LOCATION);
               ^
  symbol:   variable ActivityCompat
  location: class LocationPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:296: error: cannot find symbol
            public void onFailure(@NonNull Exception e) {

  symbol:   variable ActivityCompat
  location: class LocationPlugin
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:296: error: cannot find symbol
            public void onFailure(@NonNull Exception e) {
                                   ^
  symbol: class NonNull
9 errors
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':location:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by pkonx** [comment] 2019-07-10 19:00
how do i start projects with Android X support. the migrating instructions are not working

**Comment by SunLongbri** [comment] 2019-08-28 02:30
> I also have this problem ，when i use flutter module for my android project，use flutter packages get，then flutter android source would be replace by default and it is use support library ，not the androidx library

Did you solved this problem?

**Comment by robsondon** [comment] 2019-12-04 17:31
same issues here, someone fix it?

**Comment by pkonx** [comment] 2019-12-04 19:23
I found that starting projects in Android studio or migrating them to
Android x in Android studio was the way to go

**Comment by LuodiJackShen** [comment] 2020-04-15 06:14
same issues here,someone fix it ?

**Comment by erperejildo** [comment] 2021-03-04 21:14
almost 1 year after same error
