### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by JasonChiu-dev** [flutter/flutter#159193] opened 2024-11-20 10:14 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008101-0015783A1411001E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale zh-Hant-TW)
    • Flutter version 3.24.5 on channel stable at /Users/ecreat-jasonchiu/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (7 天前), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/ecreat-jasonchiu/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/ecreat-jasonchiu/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/ecreat-jasonchiu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • Jason的iPhone12Pro (mobile)      • 00008101-0015783A1411001E • ios            • iOS 18.1 22B83
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.4.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7048ed95a5ad3e43d697e0c397464193991fc230
### Plugins
app_links-6.3.2
app_links_linux-1.0.3
app_links_web-1.0.4
device_info_plus-11.1.1
file_selector_linux-0.9.3+1
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
flutter_email_sender-6.0.3
flutter_plugin_android_lifecycle-2.0.23
gtk-2.1.0
image_picker-1.1.2
image_picker_android-0.8.12+17
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
package_info_plus-8.1.1
path_provider-2.1.5
path_provider_android-2.2.12
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.3.3
shared_preferences_android-2.3.3
shared_preferences_foundation-2.5.3
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
speech_to_text-7.0.0
sqflite-2.4.1
sqflite_android-2.4.0
sqflite_darwin-2.4.1
url_launcher-6.3.1
url_launcher_android-6.3.14
url_launcher_ios-6.3.1
url_launcher_linux-3.2.1
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.3

**Comment by darshankawar** [comment] 2024-11-20 10:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by darshankawar** 2024-11-20 10:55 UTC
Labels: in triage
