### ISSUE TITLE
Adding a border to a container leaves a gap between the border and the content on Windows

### ISSUE THREAD

**Issue by roblframpton** [flutter/flutter#119019] opened 2023-01-23 21:18 UTC
## Steps to Reproduce

When creating a Container with a border, there is a small but noticable white gap between the border and the content on Windows.  This border does not appear on Android.

**Expected results:** 

This is how such a widget appears in Android, and is as expected:

![image](https://user-images.githubusercontent.com/43182639/214151557-f538852d-415f-42a3-9ae2-c729c4a8e82e.png)

**Actual results:** 

This is how it appears on Windows, with the gap visible:

![image](https://user-images.githubusercontent.com/43182639/214151429-b2e4c196-b7b0-422c-9e87-fc107e37c177.png)

<details>
<summary>Code sample</summary>

```dart
class MyWidget extends StatelessWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
        child: Container(
            decoration: BoxDecoration(
              border: Border.all(color: Colors.blue, width: 3.0),
            ),
            child: Container(
              color: Colors.blue,
            )));
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.9)
[√] Android Studio (version 2021.1)
[!] Android Studio (version 4.2)
    X Unable to determine bundled Java version.
[√] VS Code (version 1.74.3)
[√] Connected device (3 available)    
[√] HTTP Host Availability

! Doctor found issues in 2 categories.
```

</details>

**Comment by danagbemava-nc** [comment] 2023-01-24 07:45
Hi @roblframpton, this is a result of anti-aliasing because the border and the container have the same color. See https://github.com/flutter/flutter/issues/14288

Closing this as a duplicate of https://github.com/flutter/flutter/issues/14288. 

Kindly follow up in the issue linked above for updates and possible workarounds.

Thank you

**Closed by danagbemava-nc** 2023-01-24 07:45 UTC
Labels: in triage
