### ISSUE TITLE
[web][devtools] App get stuck `Compiling lib\main.dart for the Web...` and devtools doesn't work in profile mode

### ISSUE THREAD

**Issue by billyinferno** [flutter/flutter#90596] opened 2021-09-23 13:45 UTC
## Steps to Reproduce

1. Create flutter web project
2. Debug console showed as below
- Run flutter profile with Chrome as device
- `Running "flutter pub get" in test_keyboard...
- Launching lib\main.dart on Chrome in profile mode...
- lib\main.dart:1
- Compiling lib\main.dart for the Web...
3. Chrome opened, but DevTools not opened, the "Compiling" text never dismiss also

**Expected results:**
Flutter Dev Tools should be open

**Actual results:**
Flutter Dev Tools not open

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[√] Flutter (Channel beta, 2.6.0-5.2.pre, on Microsoft Windows [Version 10.0.19042.1110], locale en-SG)
    • Flutter version 2.6.0-5.2.pre at D:\Project\Flutter\sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (8 days ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\billy\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\billy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.54
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.52

! Doctor found issues in 1 category.
```
	
</details>

**Comment by TahaTesser** [comment] 2021-09-24 09:55
Hi @billyinferno 

> Chrome opened, but DevTools not opened, 

This is not expected behaviour, devtools don't open by itself

When running in debug mode, we can get a devtools links but for some reason, it is not printed in profile mode. I also running beta channel,  `Compiling` doesn't get stuck 


<details> 
<summary>logs</summary> 
	
```console
	[  +72 ms] Running "flutter pub get" in myapp... (completed in 1,237ms)
[ +145 ms] Generating
/Users/tahatesser/StudioProjects/myapp/android/app/src/main/java/io/flutter/plug
ins/GeneratedPluginRegistrant.java
[ +187 ms] Launching lib/main.dart on Chrome in profile mode...
[ +123 ms] Compiling lib/main.dart for the Web...
[   +7 ms] Initializing file store
[  +39 ms] web_entrypoint: Starting due to {InvalidatedReasonKind.inputChanged:
The following inputs have updated contents:
/Users/tahatesser/Code/flutter_master/packages/flutter_tools/lib/src/build_syste
m/targets/web.dart}
[   +1 ms] Skipping target: gen_localizations
[   +8 ms] web_entrypoint: Complete
[   +1 ms] dart2js: Starting due to {}
[+24963 ms] dart2js: Complete
[ +682 ms] web_release_bundle: Starting due to {}
[ +153 ms] web_release_bundle: Complete
[ +447 ms] web_service_worker: Starting due to {}
[  +89 ms] web_service_worker: Complete
[ +104 ms] Persisting file store
[   +7 ms] Done persisting file store
[  +10 ms] Compiling lib/main.dart for the Web... (completed in 26.5s)
[  +61 ms] Using Google Chrome 94.0.4606.61 

[  +92 ms] executing: sysctl hw.optional.arm64
[   +7 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[ +357 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on
ws://127.0.0.1:62341/devtools/browser/7ecb2aa9-be66-4023-82cc-5b05bef1b601
[+1076 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +3 ms] For a more detailed help message, press "h". To quit, press "q".
```
	
</details>


Can you please provide complete logs from `flutter run -d chrome --profile`
Thank you

**Comment by billyinferno** [comment] 2021-09-25 13:17
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS D:\Project\my_expense> flutter run -d chrome --profile
Launching lib\main.dart on Chrome in profile mode...
Compiling lib\main.dart for the Web...                             56.5s

  To hot restart changes while running, press "r" or "R".       
For a more detailed help message, press "h". To quit, press "q".
```

Chrome showed up, but DevTools not showed up, when I press the DevTools on VSCode it open the browser (http://127.0.0.1:9101/#/?), and showed this:

![devtools](https://user-images.githubusercontent.com/20193342/134772924-48cdc7ac-2c06-4ea6-a418-35b9707e1dce.JPG)

**Comment by TahaTesser** [comment] 2021-09-27 09:15
Hi @billyinferno 
I didn't know about this https://github.com/flutter/flutter/issues/77975 but it is supposed to open devtools when you run in profile mode and the Devtools link doesn't get printed in profile mode. 


Coming to this issue 
`Chrome opened, but DevTools not opened, the "Compiling" text never dismiss also`

I can reproduce when running from IDEs, (VS Code and Android), the chrome window is launched, but the tool process is stuck at compiling on all platforms (macOS, Windows, Linux) and when you attempt to open devtools. I can also reproduce this issue with multiple Flutter channels, including older stable.

From the command line, the app is launched, Compiling doesn't get stuck , however, there is devtools doesn't get launch either 


### Steps to reproduce 

- `flutter create myapp`
- Open my app in VS Code or Android Studio
- Run web in profile mode 

### Android Studio (performance tab says no app available)
https://user-images.githubusercontent.com/48603081/134879408-45075205-a11e-4ddf-b777-9baead3a9541.mov


### VS Code (devtools desn't launch)

https://user-images.githubusercontent.com/48603081/134879403-99552ceb-0ca7-43f7-83eb-1be443db63ed.mov

|  `stable`  | `master` |
| :---: |:---: |
|  ❗️  |   ❗️  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0 21A5522h darwin-x64, locale en-GB)
    • Flutter version 2.5.1 at /Users/tahatesser/Code/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (10 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.6.0-12.0.pre.98, on macOS 12.0 21A5522h darwin-x64, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.98 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 48e6758fb5 (8 hours ago), 2021-09-26 21:28:03 -0400
    • Engine revision 65ad5a4836
    • Dart version 2.15.0 (build 2.15.0-150.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61

• No issues found!

```
		
</details>

✅: No Issue ❗️: Issue reproduced

Thanks for filing the issue

**Comment by christopherfujino** [comment] 2021-11-16 22:52
Closing this as a duplicate of https://github.com/flutter/flutter/issues/80334.

**Closed by christopherfujino** 2021-11-16 22:52 UTC
Labels: tool, platform-web, d: devtools, has reproducible steps, found in release: 2.2, found in release: 2.5, found in release: 2.6
