### ISSUE TITLE
focusColor of DropdownButton inside ListView overflows

### ISSUE THREAD

**Issue by guidotheelen** [flutter/flutter#114804] opened 2022-11-07 11:39 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample

**Expected results:** The focusColor of the dropdown button ends where the ListView ends.

**Actual results:** The focusColor overflows other widgets.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            Container(
              height: 200,
            ),
            Expanded(
              child: ListView.builder(
                itemCount: 100,
                itemBuilder: (context, index) {
                  return DropdownButton(
                    value: 1,
                    items: const [
                      DropdownMenuItem(
                        value: 1,
                        child: Text('Item 1'),
                      ),
                    ],
                    onChanged: (int? value) {},
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[   +3 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:52618/J2WfKu-P8k0=/
[ +677 ms] The Flutter DevTools debugger and profiler on macOS is available at:
                    http://127.0.0.1:9102?uri=http://127.0.0.1:52618/J2WfKu-P8k0=/
```

```
No issues found!
```

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.5.1 21G83 darwin-x64, locale en-NL)
    • Flutter version 3.3.7 on channel stable at /Users/guidotheelen/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (6 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

![image](https://user-images.githubusercontent.com/9211107/200301255-4fbecfad-b4b7-47f3-9500-e4b7c7a7989d.png)

**Comment by guidotheelen** [comment] 2022-11-07 11:46
Workaround: Wrap your `ListView` inside a `Material` Widget.

**Comment by exaby73** [comment] 2022-11-07 14:11
Hello @guidotheelen. As explained [here](https://github.com/flutter/flutter/issues/114390#issuecomment-1298165585), this is working as intended. Therefore I am closing this issue. Thank you.

**Closed by exaby73** 2022-11-07 14:11 UTC
Labels: in triage

**Comment by guidotheelen** [comment] 2022-11-07 14:47
This is really confuses me. 🤔

**Comment by guidotheelen** [comment] 2022-11-07 15:11
Ok, sounds sensible! Would be neat to automatically check if it's needed.
Thanks for the explanation 👍
