### ISSUE TITLE
Assertion if tablet is rotated during startup

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4133] opened 2016-05-23 22:45 UTC
## Steps to Reproduce

I rotated my Nexus 9 while the app was starting up.

## Flutter Doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /media/jimbe/mojossd/sysui/src/third_party/flutter
    • Framework revision 5b8677d15d (3 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-121669373-121622544)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```
## Logs and Crash Reports

```
--------- beginning of system
I/flutter : ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown during performLayout():
I/flutter : 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 405: '_controller.isAnimating
I/flutter : || _simulation == null' is not true.
I/flutter : Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter : more information in this error message to help you determine and fix the underlying cause.
I/flutter : In either case, please report this assertion by filing a bug on GitHub:
I/flutter :   https://github.com/flutter/flutter/issues/new
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter : #1      ScrollableState.didUpdateScrollBehavior (package:flutter/src/widgets/scrollable.dart:405)
I/flutter : #2      _ScrollableViewportState._handlePaintOffsetUpdateNeeded (package:flutter/src/widgets/scrollable.dart:775)
I/flutter : #3      _ScrollableViewportState._buildViewport.<anonymous closure> (package:flutter/src/widgets/scrollable.dart:790)
I/flutter : #4      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:298)
I/flutter : #5      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1154)
I/flutter : #6      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:734)
I/flutter : #7      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:152)
I/flutter : #8      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:205)
I/flutter : #9      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:144)
I/flutter : #10     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:423)
I/flutter : #11     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:383)
I/flutter : #12     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/out/android_debug/gen/sky/bindings/hooks.dart:48)
I/flutter : The following RenderObject was being processed when the exception was fired:
I/flutter :   RenderViewport NEEDS-LAYOUT
I/flutter : This RenderObject had the following creator information:
I/flutter :   Viewport ← ClampOverscrolls ← Listener ← _GestureSemantics ← RawGestureDetector-[GlobalKey
I/flutter :   626728657] ← Scrollable-[GlobalKey 838444798] ← ClampOverscrolls ← CustomPaint ← AnimatedBuilder ←
I/flutter :   NotificationListener<ScrollNotification> ← ⋯
I/flutter : This RenderObject had the following descendants (showing up to depth 5):
I/flutter :   RenderPadding relayoutSubtreeRoot=up1
I/flutter :     RenderBlock relayoutSubtreeRoot=up2
I/flutter :       RenderFlex relayoutSubtreeRoot=up3
I/flutter :         RenderDecoratedBox relayoutSubtreeRoot=up4
I/flutter :           RenderPadding relayoutSubtreeRoot=up5
I/flutter :         RenderDecoratedBox relayoutSubtreeRoot=up4
I/flutter :           RenderPadding relayoutSubtreeRoot=up5
I/flutter :         RenderDecoratedBox relayoutSubtreeRoot=up4
I/flutter :           RenderPadding relayoutSubtreeRoot=up5
I/flutter :         RenderDecoratedBox relayoutSubtreeRoot=up4
I/flutter :           RenderPadding relayoutSubtreeRoot=up5
I/flutter :         RenderDecoratedBox relayoutSubtreeRoot=up4
I/flutter :           RenderPadding relayoutSubtreeRoot=up5
I/flutter :         RenderDecoratedBox relayoutSubtreeRoot=up4
I/flutter :           RenderPadding relayoutSubtreeRoot=up5
I/flutter :         RenderDecoratedBox relayoutSubtreeRoot=up4
I/flutter :           RenderPadding relayoutSubtreeRoot=up5
I/flutter :         RenderDecoratedBox relayoutSubtreeRoot=up4
I/flutter :           RenderPadding relayoutSubtreeRoot=up5
I/flutter :         RenderDecoratedBox relayoutSubtreeRoot=up4
I/flutter :           RenderPadding relayoutSubtreeRoot=up5
I/flutter :         RenderDecoratedBox relayoutSubtreeRoot=up4
I/flutter :           RenderPadding relayoutSubtreeRoot=up5
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by eseidelGoogle** [comment] 2016-05-23 23:34
This is likely either @Hixie or @HansMuller territory judging from the stacktrace.

**Comment by HansMuller** [comment] 2016-05-24 15:37
I haven't been able to reproduce this (yet) but the assert doesn't seem right:

```
  void didUpdateScrollBehavior(double newScrollOffset) {
    assert(_controller.isAnimating || _simulation == null);
    ...
```
I think that the assert's implication is that an interactive or a programmatic scroll is underway. In this case we're doing a layout because the screen's dimensions have changed.

**Comment by Hixie** [comment] 2016-05-24 18:26
Shouldn't that assert always be true? If we're not animating, then `_simulation` should equal `null`, no?

**Comment by HansMuller** [comment] 2016-05-24 19:35
If you scroll with scrollTo(), then only _controllerIsAnimating should be true.

**Comment by Hixie** [comment] 2016-05-24 20:14
then the assert will still be true, right?

**Comment by HansMuller** [comment] 2016-05-24 21:02
Right. But if we'rein this code because we're doing a layout - we're not scrolling due to a scrollTo() or a fling - then I assume that the assert is false.

**Comment by Hixie** [comment] 2016-05-24 21:50
Hans and I talked about this. The assert firing means that the system thinks we're not simulating, but we for some reason still have a simulation. I think that's a state we should never reach, but it's not clear why we're reaching it...

**Comment by Hixie** [comment] 2016-08-04 17:51
FIxed by https://github.com/flutter/flutter/pull/5209

**Closed by Hixie** 2016-08-04 17:51 UTC
Labels: affects: framework, ⚠ bug
