### ISSUE TITLE
Bad error message when calling`Image.file` on web

### ISSUE THREAD

**Issue by s2yed** [flutter/flutter#88772] opened 2021-08-24 08:46 UTC
```console
======== Exception caught by image resource service ================================================
The following UnsupportedError was thrown resolving an image codec:
Unsupported operation: _Namespace

When the exception was thrown, this was the stack: 
dart:sdk_internal 5041:11                                             throw_
dart:sdk_internal 52632:17                                            get _namespacePointer
dart:sdk_internal 50535:28                                            _namespacePointer
dart:sdk_internal 50538:31                                            _dispatchWithNamespace
dart:sdk_internal 50653:23                                            open
```

**Comment by TahaTesser** [comment] 2021-08-24 12:15
hI @s2yed 
Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by achinverma** [comment] 2021-08-25 07:12
I am also getting the same in web. I am simpley showing the image from file in the web.
```
XFile=blob:http://localhost:55375/9a7c7849-3b80-4066-9681-c7a39b861b9b
Unsupported operation: _Namespace
connectivityChanged to ConnectivityResult.wifi
```

**Comment by johanehinger** [comment] 2021-09-02 05:59
I'd like to try and fix this issue. I'm new to contributing to Flutter however I've used the framework a lot in my education as a computer scientist. Do you think it's a good first issue or should I try my luck with something else?

**Comment by Shashwat2708** [comment] 2021-09-29 13:52
I think that you should double-check the indentation in pubspec.yaml file where you have entered the location of the image. I have faced this issue mostly because of that.

**Comment by or-adar** [comment] 2021-11-05 23:22
> The browser doesn't have access to the file system, so `Image.file` is not supported. However, we should produce a better error message when the app attempts to use it.

Hello there!
I would love to help in this issue, but would also like to lay out possible fixes before starting, so I won't commit twice the work.
These are the fixes I came up with:

1. Using dart's assert statement with a proper error message to distrupt the execution on `FileImage` class or `Image.file` constructor (or both, let me know what you think):
```dart
    assert(!kIsWeb, """
Error: FileImage is not supported on Flutter Web.
       The current security model of browsers does not permit access 
       to file systems.
       Consider using supported image providers
       or obtaining access through a file picker.
""");
```
2. Catching an `UnsupportedError` on `FileImage._loadAsync(#, #)` and rethrowing it with a better message if the application runs on web (or rethrowing it anyway with a better message, no matter the platform, as long as we caught an `UnsupportedError`?)

**Comment by tugorez** [comment] 2021-11-29 19:35
@yjbanov I'll pick this bug. Would you mind assign it to me? Thanks :)!

**Comment by tugorez** [comment] 2021-11-29 19:49
Oh wait, I didn't read the previous comment, my bad. It seems that @or-adar is already working on it. 

@or-adar is this something you would still like to fix? If so it seems to me that **1)** is the way to go in this case.

**Closed** 2021-12-14 15:59 UTC
Labels: easy fix, engine, platform-web, a: images, has reproducible steps, P4, found in release: 2.2, found in release: 2.6
