### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by pratikbutani** [flutter/flutter#79360] opened 2021-03-30 11:27 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=16579747 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart
```

## Logs
SentinelException
```

```
```
[✓] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.17763.475], locale en-IN)
    • Flutter version 2.0.3 at E:\Android\flutter
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\Android\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: E:\Android\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at E:\Android\Android\AndroidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • SM J810G (mobile) • 16579747 • android-arm    • Android 10 (API 29)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 8874f21e79d7ec66d0457c7ab338348e31b17f1d
### Plugins
connectivity-2.0.2
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
device_info-1.0.0
firebase_analytics-7.0.1
firebase_analytics_web-0.1.1
firebase_auth-0.20.1
firebase_auth_web-0.3.3
firebase_core-0.7.0
firebase_core_web-0.2.1+3
firebase_messaging-8.0.0-dev.15
firebase_messaging_web-0.1.0-dev.6
firebase_remote_config-0.6.0
flutter_local_notifications-4.0.1+1
flutter_plugin_android_lifecycle-1.0.11
fluttertoast-7.1.8
image_picker-0.6.7+22
package_info-0.4.3+4
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
razorpay_flutter-1.2.5
share-0.6.5+4
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
upi_india-2.2.0+1
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
webview_flutter-1.0.7

**Comment by pedromassangocode** [comment] 2021-03-30 12:06
Hi @pratikbutani 
Does the crash logs generated any log file in the root directory where the run command ran? If yes, can you please provide it?
Thank you

**Comment by pratikbutani** [comment] 2021-04-05 06:34
@pedromassangocode Here is the log file.

Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=16579747 --start-paused --dart-define=flutter.inspector.structuredErrors=true --devtools-server-address=http://127.0.0.1:9100 lib\main.dart

## exception

SentinelException: [Sentinel type: Sentinel, kind: Collected, valueAsString: <collected>] from getIsolate()

```
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.17763.475], locale en-IN)
    • Flutter version 2.0.3 at E:\Android\flutter
    • Framework revision 4d7946a68d (11 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\Android\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: E:\Android\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at E:\Android\Android\AndroidStudio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • SM J810G (mobile) • 16579747 • android-arm    • Android 10 (API 29)
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 89.0.4389.90

• No issues found!
```

**Comment by arnaudelub** [comment] 2021-04-14 08:09
Hi, 
i just had the same crash, here is the log file:
<details>
<summary>Crash Log</summary>
Flutter crash report.
Please report a bug at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

SentinelException: [Sentinel type: Sentinel, kind: Collected, valueAsString: <collected>] from getIsolate()

```
```

## flutter doctor

```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /home/idelub/Development/flutter
    • Framework revision b1395592de (12 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/idelub/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 11.1.0
    • cmake version 3.19.7
    • ninja version 1.10.2
    • pkg-config version 1.7.3

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at /opt/idea-IU-202.6397.94
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.6397.47

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Linux
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```
</details>

**Comment by danagbemava-nc** [comment] 2022-10-06 12:46
Closing this as a duplicate of https://github.com/flutter/flutter/issues/78214

**Closed by danagbemava-nc** 2022-10-06 12:46 UTC
Labels: severe: crash, tool, passed first triage
