### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by hudawei996** [flutter/flutter#136867] opened 2023-10-19 06:11 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory.createSync (dart:io/directory_impl.dart:129:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:428:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:427:12)
#5      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:918:19)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:812:5)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:679:9)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1566:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN)
    [32m•[39m Flutter version 3.13.8 on channel stable at /Users/goals/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 6c4930c4ac (13 小时前), 2023-10-18 10:57:55 -0500
    [32m•[39m Engine revision 767d8c75e8
    [32m•[39m Dart version 3.1.4
    [32m•[39m DevTools version 2.25.0

[31m[☠][39m Android toolchain - develop for Android devices (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    [31m✗[39m Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:04:30.000000
    [32m•[39m 

[31m[☠][39m Xcode - develop for iOS and macOS (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    [31m✗[39m Exception: Xcode - develop for iOS and macOS exceeded maximum allowed duration of 0:04:30.000000
    [32m•[39m 



**Comment by darshankawar** [comment] 2023-10-19 07:16
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98066

**Closed by darshankawar** 2023-10-19 07:16 UTC
Labels: in triage
