### ISSUE TITLE
USB comunication error compiling in release mode but works properly compiling in debug mode on  PAX IM700 device

### ISSUE THREAD

**Issue by safeDev15** [flutter/flutter#69026] opened 2020-10-26 15:02 UTC
## Error Explanation 
I am using the PAX IM700 device which allows for banking transactions. This device comes with a Java SDK that I have successfully implemented through the guide to write specific code for the android platform. If I compile the application in debug mode I am able to correctly use the implemented functionalities and therefore perform banking transactions. When I compile the application in release mode it is not possible to establish the USB connection between the POS and the android device. In particular, when reading the logs generated by the POS terminal, the ConnectionLayer, object of the pos library that manages the connection, does not receive the response signal (Acknowledge) from the terminal through the USB channel. The Logs section shows the error messages just discussed. Does the release build mode apply restrictions on USB communication channels?

<details>
  <summary>Logs</summary>
[verbosecommandDEBUG.txt](https://github.com/flutter/flutter/files/5439251/verbosecommandDEBUG.txt)
[verbosecommandRELEASE.txt](https://github.com/flutter/flutter/files/5439252/verbosecommandRELEASE.txt)

```
The content of the flutter run --verbose command is inside these two files:
FlutterRunVerboseRelease.txt with --release
FlutterRunVerboseDebug.txt with --debug

Error messages about POS and Android device communication:
E/ConnectionLayer: MessageDispatcher: ack to authentication request not received: try to resend the message
E/ConnectionLayer: StreamServer: annotation com.paxitalia.mpos.connectionlayer.UsbDataReceived not found
E/ConnectionLayer: MessageDispatcher: ack to authentication request not received: try to resend the message
E/ConnectionLayer: MessageDispatcher: not ack to authentication request received after three attempts
```

flutter analyze
Analyzing ast_controllo...                                               
No issues found! (ran in 13.3s)

flutter doctor -v
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.4 19E287, locale it-IT)
    • Flutter version 1.22.2 at /Users/officinedelturismo/Documents/flutter
    • Framework revision 84f3d28555 (11 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/officinedelturismo/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/officinedelturismo/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

Flutter and Dart plugins are installed correctly in Android Studio. I don't know why I get these errors;
</details>

**Comment by TahaTesser** [comment] 2020-10-27 09:34
Hi @safeDev15 
Can you please provide` your `flutter run --release --verbose` with USB errors and a complete reproducible minimal code sample
Thank you

**Comment by safeDev15** [comment] 2020-10-28 10:23
The POS communication error occurs only if I launch the "flutter build apk --release" command and install the generated apk on the device to which I connect the PAX IM700 via usb. Instead, launching the application from Visual Studio Code or Android Studio the app works correctly. Even running the application with the command "flutter run --release" the app works correctly. It seems that the process of building the release apk through the command "flutter build apk --release" blocks or inhibits the operation of the USB communication channel.

Attached are the logs of the "flutter run --release --verbose" command and also the logs retrieved from the Android Studio logcat after installing the apk generated with the "flutter build apk --release" command where you can see the errors returned by the POS library MessageDispatcher.

P.S: In the logs you will read "Bluethoot connection ....", note that this is a typo by the POS library developers. You can conceptually replace the word bluethoot with USB, then "USB connection ...." etc ..

Thank you!!
[logcat_Android_Studio.txt](https://github.com/flutter/flutter/files/5451137/logcat_Android_Studio.txt)
[FlutterRunVerboseRelease.txt](https://github.com/flutter/flutter/files/5451139/FlutterRunVerboseRelease.txt)

**Comment by TahaTesser** [comment] 2020-10-29 08:27
Hi @safeDev15 

Can you please provide your `pubspec.yaml` and a complete reproducible minimal code sample
Thank you

**Comment by safeDev15** [comment] 2020-10-29 18:01
I created a new Flutter project and exclusively implemented the functionalities related to the POS. Attached is the pubspec.yaml file of the new project created. Code sharing can be done by signing an NDA on your part. Remember that even sharing the code without the PAX IM700 device it is not possible to test and notice the errors present in the logs already sent.
Thanks for your time.

[pubspec.txt](https://github.com/flutter/flutter/files/5460390/pubspec.txt)

**Comment by TahaTesser** [comment] 2020-10-30 07:13
I’m unable to reproduce the issue to pinpoint the cause. The issue needs further investigation.

**Comment by safeDev15** [comment] 2020-10-30 16:02
if I give you the code, could you try also without the PAX IM700 device?

**Comment by safeDev15** [comment] 2020-11-02 11:44
Do you have some news for me? thank you!

**Comment by safeDev15** [comment] 2020-11-03 12:10
[flutter_test_pos_for_Flutter_Team.zip](https://github.com/flutter/flutter/files/5481084/flutter_test_pos_for_Flutter_Team.zip)
I attached the project. Please, give me support. Thank you!

**Comment by safeDev15** [comment] 2020-11-04 13:47
[flutter_test_pos_for_Flutter_Team.zip](https://github.com/flutter/flutter/files/5488144/flutter_test_pos_for_Flutter_Team.zip)
I attached the project. Please, give me support. Thank you!

**Comment by safeDev15** [comment] 2020-11-09 08:21
> I’m unable to reproduce the issue to pinpoint the cause. The issue needs further investigation.

I attached the project. Please, give me support. Thank you!

**Comment by TahaTesser** [comment] 2020-11-09 12:33
Hi @safeDev15 
The issue is labeled, thanks for providing the project, this is device-specific too.
Please be patient, this issue needs additional triage

**Comment by safeDev15** [comment] 2020-11-09 13:34
> Hi @safeDev15
> The issue is labeled, thanks for providing the project, this is device-specific too.
> Please be patient, this issue needs additional triage

Ok, thank you!

**Comment by Hixie** [comment] 2020-11-10 23:57
Is it possible that you have different permissions set in the debug Android manifest and the release Android manifest?

**Comment by safeDev15** [comment] 2020-11-12 16:56
[AndroidManifestDEBUG.txt](https://github.com/flutter/flutter/files/5532030/AndroidManifestDEBUG.txt)
[AndroidManifestMAIN.txt](https://github.com/flutter/flutter/files/5532031/AndroidManifestMAIN.txt)

There are the two android manifest that I use in the project sent. Do you find something strange? Thank you!

**Comment by Hixie** [comment] 2020-11-18 00:07
Nothing obvious there...

Am I correct in understanding that this only happens with this Java library?
I would try to narrow down the problem as much as possible. Try reproducing it without Flutter, try reproducing it without the Java library, try taking the code from the Java library and narrowing down what could be causing it there... I really can't think of anything that could be causing this.

cc @jason-simmons who may have an idea

**Comment by safeDev15** [comment] 2020-11-18 09:10
It seems to have partially solved the problem. By creating the apk files directly from Android studio with the classic procedure and with the V1 (Jar Signature) and V2 (Full APK Signature) signatures, the communication problems of the USB channel seem to be solved and I am able to perform payment transactions. Therefore the problem seems to be in the process of compiling and creating the apk through the command "flutter build apk --release". The flutter team should analyze the compilation differences between the two processes and understand what causes the problem in the flutter command.

**Comment by Hixie** [comment] 2020-11-18 09:13
Does it work if you use `flutter build appbundle`?

**Comment by safeDev15** [comment] 2020-11-30 10:27
I don't know. however it seems in the process of compiling and creating the apk. This will be useful to other people. With Android Studio sign and build apk it works.

**Comment by Hixie** [comment] 2020-12-02 00:24
Can you try `flutter build appbundle` just to see if that breaks also?

**Comment by Hixie** [comment] 2020-12-02 00:24
It would be really useful to have absolutely clear steps to reproduce (like, starting from `flutter create`, listing all the steps and hardware and configuration needed), since trying to fix it without us being able to reproduce will be very difficult.

**Comment by pedromassangocode** [comment] 2020-12-23 09:21
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-23 09:21 UTC
Labels: a: release, e: device-specific, engine, passed first triage, tool, waiting for customer response
