### ISSUE TITLE
VScode auto import

### ISSUE THREAD

**Issue by lkhgvsuren** [flutter/flutter#27230] opened 2019-01-29 09:48 UTC
I am using vscode and I can't find a way to auto import packages and classes. For example, If I need to use http get request do I only have to type import 'package:http/http.dart' manually?

**Comment by zoechi** [comment] 2019-01-29 10:02
Duplicate of https://github.com/dart-lang/sdk/issues/25820

**Closed by zoechi** 2019-01-29 10:02 UTC

**Comment by lkhgvsuren** [comment] 2019-01-29 11:42
@zoechi but I can't find the answer.

**Comment by zoechi** [comment] 2019-01-29 12:32
The answer is that this currently does not work as you want and you can subscribe to the linked issue to get updates.
