### ISSUE TITLE
99%-ile build time regression in a couple of benchmarks

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#114436] opened 2022-11-01 17:06 UTC
On the Engine roll here https://github.com/flutter/flutter/pull/114258, SkiaPerf found regressions in 99%-ile build time in the `picture_cache_perf__e2e_summary` and `list_text_layout_perf__e2e_summary` benchmarks on Android.

https://flutter-flutter-perf.skia.org/e/?begin=1666796431&end=1667320150&keys=X71399d07b6f9fb75e61157d8a6f8f665&requestType=0&selected=commit%3D31809%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DMoto_G__4_%252Cdevice_version%253Dnone%252Chost_type%253Dlinux%252Csub_result%253D99th_percentile_frame_build_time_millis%252Ctest%253Dpicture_cache_perf__e2e_summary%252C&xbaroffset=31809

In chat @jason-simmons mentioned narrowing this down to the Skia change here https://skia.googlesource.com/skia/+/e474903a0236b77cacb04b81ac53855e99189f89.

**Comment by jason-simmons** [comment] 2022-11-01 20:23
This was caused by changes to the SkParagraph `ParagraphImpl` state machine in https://skia.googlesource.com/skia/+/e474903a0236b77cacb04b81ac53855e99189f89

`ParagraphImpl::layout` is now calling `computeCodeUnitProperties()` for all paragraphs, including paragraphs that are already in the `ParagraphCache`.

Previously `computeCodeUnitProperties()` was only called within `shapeTextIntoEndlessLine()` and would be skipped if the shaping results were found in the cache.

The affected benchmark returns to its old behavior if I move `computeCodeUnitProperties()` back into `shapeTextIntoEndlessLine()`.

@Rusino

**Comment by chinmaygarde** [comment] 2022-11-07 18:32
From Triage: [Skia has a fix for this that has just landed](https://skia-review.googlesource.com/c/skia/+/600096) and is waiting to be rolled in.

**Comment by jason-simmons** [comment] 2022-11-08 19:39
Confirmed that the fix is working as expected in the benchmark

**Closed by jason-simmons** 2022-11-08 19:39 UTC
Labels: engine, severe: performance, P2
