### ISSUE TITLE
Update flutter_driver dependencies

### ISSUE THREAD

**Issue by nknezevicpr** [flutter/flutter#44829] opened 2019-11-13 18:04 UTC
**Steps to reproduce**: 

1. Add flutter_driver and test dependency in pubspec.yaml
2. Add following dependencies  to pubspec (image: ^2.1.8, quiver: ^2.1.2+1, analyzer)
3. Run command "flutter pub get" or "flutter packages get"

**Actual result**: pub get command fails because flutter_driver from sdk depends on "image 2.1.4" but app uses "image: ^2.1.8"
**Expected result**: command is executed successfully
NOTE: Same case with quiver dependency

**LOGS**
In case of "quiver: ^2.1.2+1":
> Because every version of flutter_driver from sdk depends on fuchsia_remote_debug_protocol any from sdk which depends on quiver 2.0.5, every version of flutter_driver from sdk requires quiver 2.0.5.
So, because "some_app_name" depends on both quiver ^2.1.2+1 and flutter_driver any from sdk, version solving failed.

In case of "image: ^2.1.8":
> Because every version of flutter_driver from sdk depends on image 2.1.4 and "some_app_name" depends on image ^2.1.8, flutter_driver from sdk is forbidden.
So, because "some_app_name" depends on flutter_driver any from sdk, version solving failed.

In case of "analyzer":
> The current Dart SDK version is 2.7.0.                                                                                              
Because no versions of test match >1.9.4 <2.0.0 and test >=0.12.0-beta.3 <1.3.0 requires SDK version >=1.8.0 <2.0.0-∞, test >=0.12.0-beta.3 <1.3.0-∞ or >1.9.4 <2.0.0 is forbidden.
And because test >=1.3.0 <1.6.1 depends on stream_channel ^1.6.0, test >=0.12.0-beta.3 <1.6.1-∞ or >1.9.4 <2.0.0 requires stream_channel ^1.6.0.
And because test >=1.6.0 <1.6.5 depends on analyzer >=0.26.4 <0.37.0 and test >=1.6.4 <1.6.8 depends on test_api 0.2.6, test >=0.12.0-beta.3 <1.6.8-∞ or >1.9.4 <2.0.0 requires stream_channel ^1.6.0 or analyzer >=0.26.4 <0.37.0 or test_api 0.2.6.
And because test >=1.6.8 <1.6.11 depends on test_api 0.2.7 and test >=1.6.11 <1.9.2 depends on test_api 0.2.8, test >=0.12.0-beta.3 <1.9.2-∞ or >1.9.4 <2.0.0 requires stream_channel ^1.6.0 or analyzer >=0.26.4 <0.37.0 or test_api 0.2.6 or 0.2.7 or 0.2.8.
And because test >=1.9.2 <1.9.3 depends on test_api 0.2.9 and test >=1.9.3 <1.9.4 depends on test_api 0.2.10, test >=0.12.0-beta.3 <1.9.4-∞ or >1.9.4 <2.0.0 requires test_api 0.2.6 or 0.2.7 or 0.2.8 or 0.2.9 or 0.2.10 or stream_channel ^1.6.0 or analyzer >=0.26.4 <0.37.0.
Because no versions of chopper_generator match >3.0.2 <4.0.0 and chopper_generator 3.0.2 depends on analyzer ^0.38.2, chopper_generator ^3.0.2 requires analyzer ^0.38.2.
Thus, if chopper_generator ^3.0.2 and test >=0.12.0-beta.3 <1.9.4-∞ or >1.9.4 <2.0.0 then test_api 0.2.6 or 0.2.7 or 0.2.8 or 0.2.9 or 0.2.10 or stream_channel ^1.6.0.
And because every version of flutter_driver from sdk depends on stream_channel 2.0.0 and test <1.3.0 requires SDK version >=1.8.0 <2.0.0-∞, if chopper_generator ^3.0.2 and flutter_driver any from sdk and test <1.9.4-∞ or >1.9.4 <2.0.0 then test_api 0.2.6 or 0.2.7 or 0.2.8 or 0.2.9 or 0.2.10.
And because no versions of test match >=2.0.0 and test 1.9.4 depends on test_api 0.2.11, if chopper_generator ^3.0.2 and flutter_driver any from sdk and test any then test_api 0.2.6 or 0.2.7 or 0.2.8 or 0.2.9 or 0.2.10 or 0.2.11.
And because "some_app_name" depends on flutter_driver any from sdk which depends on test_api 0.2.5, chopper_generator ^3.0.2 is incompatible with test.
So, because "some_app_name" depends on both test any and chopper_generator ^3.0.2, version solving failed.

**Workaround:**
Override problematic dependencies with older versions that are compatible with flutter driver

It's not good that QA overrides app dependencies in order to run integration tests, so it would be good if flutter driver can be updated to work with latest dependencies. Compatibility with other dependencies should be checked also.

I am sorry if I missed to write some useful information, if you need additional info, feel free to ask and I will provide everything.

**Comment by nknezevicpr** [comment] 2019-11-20 09:41
Any update on this issue?

**Comment by DNomad93** [comment] 2019-11-26 12:40
Same thing witth the test_api dependency, waaay out of date with the version 1.6.3 intead of 1.9.4.

**Comment by Hixie** [comment] 2019-12-02 17:32
These will get updated automatically next time we run `flutter update-packages --force-upgrade`. Feel free to submit a PR that does that.

I'm closing this as a dupe of #37985 for now.

**Closed by Hixie** 2019-12-02 17:32 UTC
Labels: t: flutter driver
