### ISSUE TITLE
GestureDetector blocking when inside a Stack

### ISSUE THREAD

**Issue by shinayser** [flutter/flutter#32492] opened 2019-05-10 14:25 UTC
`GestureDestector `is blocking detection on any widget that are behind it on a `Stack`, **even when `behavior: HitTestBehavior.translucent` is set!**

This is really problematic, mostly when you want to use a GestreDetector to figure out when a user taps **outside** a specific widget.

Example:
```
class RandomTest extends StatelessWidget {
 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Stack(
          children: <Widget>[
            Positioned.fill(
              child: RaisedButton(
                child: Text("THIS CAN'T BE CLICKED"),
                onPressed: () {
                  print("The button got clicked");
                },
              ),
            ),
            Positioned.fill(
              child: GestureDetector(
                behavior: HitTestBehavior.translucent,
                onTap: () {
                  print("The GestureDetector got clicked");
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [versÃ£o 10.0.17763.437], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.30.1)
[√] Connected device (1 available)

• No issues found!

```

**Comment by TahaTesser** [comment] 2020-02-28 15:17
Duplicate of [#51635](https://github.com/flutter/flutter/issues/51635)

**Closed by TahaTesser** 2020-02-28 15:17 UTC
Labels: framework
