### ISSUE TITLE
setState might not update the widgets in showDrawer

### ISSUE THREAD

**Issue by afandria** [flutter/flutter#604] opened 2015-11-27 06:03 UTC
Sorry if this is sparse on details. I mainly want to determine if there is a bug with `showDrawer` or with the way I attempted to use it.

Yesterday, I attempted to use `showDrawer` with the 7be58b1 alpha branch of Flutter. The drawer appeared/dismissed correctly, and the widgets I put in the drawer were correct.

Unfortunately, I noticed that no matter how I attempted to change the state of what was drawn in the drawer, it would not re-render. In my case, I tried to put a `Switch` inside a `DrawerItem` to toggle debug mode for my app. I did confirm that the state did actually change, which led me to think that Flutter has a bug.

I was following the Stocks demo app quite closely, which uses a Drawer to toggle the user's market sentiment (`Optimistic` vs `Pessimistic`). However, I was assuming that the app's behavior would match the [Sky Demo](https://play.google.com/store/apps/details?id=org.domokit.sky.demo) app in the Google Play Store. I only just realized that this app is actually 3 months old (last update August 25), so it is very possible that in that time, the Stocks example does not function as it did before.

I am currently unable to try running these examples (though I have found the [instructions](https://github.com/flutter/flutter/tree/4b03a9eec899659e4770e5ec88e365afbac0916b/examples)), so if someone else can run the Stocks app and determine whether the Optimistic/Pessimistic radio buttons update the drawer menu or not, that would be very helpful.

Otherwise, I will look into this more after the break.

**Comment by abarth** [comment] 2015-11-27 06:13
This is a duplicate of #187.  I can fix it for you.

> Sky Demo app in the Google Play Store

Yeah, that demo is really old.  We've unpublished it because we're no longer maintaining it.

> someone else can run the Stocks app

The stocks app has the same bug.  The issue is with how the `showDrawer` function takes its arguments.  It needs to take a `WidgetBuilder` instead of a `widget`.

**Comment by abarth** [comment] 2015-11-27 06:41
Hum... The fix isn't as simple as I thought it would be.

**Comment by abarth** [comment] 2015-11-27 07:06
Fix in https://github.com/flutter/flutter/pull/605

**Closed** 2015-12-03 18:21 UTC
Labels: affects: framework, customer: croupier, ⚠ bug (regression)
