### ISSUE TITLE
Linux firebase_release_smoke_test timing out

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#144183] opened 2024-02-26 23:09 UTC
### Type of Request

bug

### Infrastructure Environment

LUCI

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20firebase_release_smoke_test/17675/overview

### What is happening?

The framework tree is red on an infra failure from the test_execution/gcloud firebase step.

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8754993950716731393/+/u/test_execution/gcloud_firebase/stdout

It looks like this has repeatedly timed out and cannot be rerun again.

### Steps to reproduce

N/A, see current state of https://flutter-dashboard.appspot.com/#/build

### Expected results

N/A

**Comment by keyonghan** [comment] 2024-02-26 23:15
Reaching out to firebase team.

**Comment by keyonghan** [comment] 2024-02-26 23:22
FTL is experiencing networking issue: http://omg/70161
We can mark the target as `bringup: true` to unblock. /cc @Piinks

**Comment by Piinks** [comment] 2024-02-26 23:28
Thanks @keyonghan!

**Comment by keyonghan** [comment] 2024-02-27 16:58
https://github.com/flutter/flutter/pull/144234 moves `firebase_abstract_method_smoke_test` and `firebase_android_embedding_v2_smoke_test` to staging, considering the issue is still not resolved.

**Comment by keyonghan** [comment] 2024-02-28 01:05
Issue seems mitigated, but I still see a failed build today. Need monitor a bit more.
<img width="111" alt="Screenshot 2024-02-27 at 5 04 09 PM" src="https://github.com/flutter/flutter/assets/54558023/6edaa86c-0453-482f-ac9b-af770b330ff4">

**Comment by keyonghan** [comment] 2024-02-29 19:07
The issue has been mitigated, but the omg is still open. Will monitor a bit more before closing (moving targets back to prod).

**Comment by keyonghan** [comment] 2024-03-06 18:39
Tests have been passing consistently for days. Though the omg is still open, proactively bringing these back to prod. https://github.com/flutter/flutter/pull/144703

**Comment by keyonghan** [comment] 2024-03-07 19:33
Targets have been moved to prod. Closing.

**Closed by keyonghan** 2024-03-07 19:33 UTC
Labels: team-infra, P0, triaged-infra
