### ISSUE TITLE
[video_player] black screen rendered for aspect ratio higher than device on edited videos (iOS, possibly Android) 

### ISSUE THREAD

**Issue by Tom3652** [flutter/flutter#96918] opened 2022-01-20 13:16 UTC
## Steps to Reproduce

1. Record a new video with the phone's camera app
2. Run the sample code below and see the correct video displayed
3. Open the ```Photos``` native app
4. Edit this video and crop it with an aspect ratio higher than your device
5. Go back to the sample code, restart the app 
6. Pick the edited video
7. See the black rect / screen

If you crop the video with an aspect ratio lower than the device, it is displayed correctly.  
I am in release mode and my users made me realize this, if you know how can i fix it quickly i would be really thankful.

I am using ```video_player: ^2.2.13```.

**Expected results:** 

The edited video should be displayed correctly

**Actual results:** 

The edited video renders as black screen.

<details>
<summary>Code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:video_player/video_player.dart';

void main() {
  runApp(const TestApp());
}

class TestApp extends StatefulWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  _TestAppState createState() => _TestAppState();
}

class _TestAppState extends State<TestApp> {

  String filePath = "";

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: filePath.isNotEmpty ? VideoTestWidget(file: filePath) : Center(
          child: GestureDetector(
            onTap: () async {
              XFile? file = await ImagePicker().pickVideo(source: ImageSource.gallery);
              if (file != null) {
                setState(() {
                  filePath = file.path;
                });
              }
            },
            child: Container(
              width: 200,
              height: 200,
              color: Colors.blue,
              child: Text("pick"),
            ),
          ),
        ),
      ),
    );
  }
}


class VideoTestWidget extends StatefulWidget {

  final String file;

  const VideoTestWidget({Key? key, required this.file}) : super(key: key);

  @override
  _VideoTestWidgetState createState() => _VideoTestWidgetState();
}

class _VideoTestWidgetState extends State<VideoTestWidget> {

  VideoPlayerController? controller;

  @override
  void initState() {
    super.initState();
    controller = VideoPlayerController.file(File(widget.file));
    controller!.initialize().then((value) {
      setState(() {
        controller!.play();
      });
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return controller != null && controller!.value.isInitialized ? Center(child: AspectRatio(aspectRatio: controller!.value.aspectRatio, child: VideoPlayer(controller!))) : const SizedBox();
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale fr-FR)
    • Flutter version 2.8.1 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Now You See Me (mobile) • 00008020-001204401E78002E • ios            • iOS 15.2.1 19C63
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

</details>

https://user-images.githubusercontent.com/32631467/150345127-baae1807-564f-40e9-9791-f5dccf8cd3ad.mov

**Comment by danagbemava-nc** [comment] 2022-01-20 13:37
Duplicate of #71299

**Closed by danagbemava-nc** 2022-01-20 13:37 UTC
Labels: in triage
