### ISSUE TITLE
Wrongly colored pixel on splash animation on Android

### ISSUE THREAD

**Issue by Neurs12** [flutter/flutter#125863] opened 2023-05-02 07:03 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Press/Click on any of the widgets that create splash effect on debug or release build for Android.

### Expected results

Clean splash effect animation like as it should be on other platform's build.

### Actual results

Random wrongly colored pixels while the splash is being animated.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: Cover()));
}

class Cover extends StatelessWidget {
  const Cover({super.key});

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(onPressed: () {}, child: Container());
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://user-images.githubusercontent.com/31346263/235599408-4778aa28-fc69-49aa-84a5-0d6c3a74fcb2.mp4

</details>

### Logs

<details><summary>Logs</summary>

```console
No log produced.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19045.2846], locale en-US)
    • Flutter version 3.7.12 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (2 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)
    • Android SDK at D:\SDK
    • Platform android-33, build-tools 34.0.0-rc3
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
    • Visual Studio at D:\Visual Studio\VS IDE
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\QUAN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2846]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.48

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

### Notes
I noticed this behavior since Flutter v3.0.4.

I don't have any Apple devices to test on.

Windows, web build do not produce this behavior.

Device used in video: Samsung S22

**Comment by danagbemava-nc** [comment] 2023-05-02 12:29
Hi @Neurs12, this is not a bug. What you're seeing is the `InkSparkle` effect that was introduced in android 12. See https://github.com/flutter/flutter/issues/82850 for the proposal to introduce this in flutter. 

You are only seeing it on android because it is an android specific feature. 

Closing this as working as intended. 

Thank you

**Closed by danagbemava-nc** 2023-05-02 12:29 UTC
Labels: in triage
