### ISSUE TITLE
[tool crash] StateError: Bad state: Failed to start Dart Development Service

### ISSUE THREAD

**Issue by Shreya09Singh** [flutter/flutter#158006] opened 2024-11-01 16:37 UTC
## Command
```sh
flutter run --machine --start-paused -d mf7tcmsg7d5ti7au --devtools-server-address http://127.0.0.1:9100/ --target D:\SQFLite_DB\notesapplication\lib\main.dart
```

## Steps to Reproduce
1. Update Android Studio to the latest version.
2. Switch Flutter to the master channel and run `flutter upgrade`.
3. Create a new Flutter project using `flutter create`.
4. Run the project on an Android Emulator with API level 33.

## Logs
StateError: Bad state: Failed to start Dart Development Service
```console
E/flutter (7132): [ERROR:flutter/impeller/renderer/backend/vulkan/android/ahb_texture_source_vk.cc(133)] Break on 'ImpellerValidationBreak' to inspect point of failure: Could not allocate device memory for external image : ErrorOutOfDeviceMemory
...


```
```console
[✓] Flutter (Channel beta, 3.27.0-0.1.pre, on Microsoft Windows [Version 10.0.22631.4391], locale en-IN)
    • Flutter version 3.27.0-0.1.pre on channel beta at D:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e2c358c9b (10 days ago), 2024-10-22 11:02:13 -0400
    • Engine revision af0f0d559c
    • Dart version 3.6.0 (build 3.6.0-334.3.beta)
    • DevTools version 2.40.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\abhi6\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio2\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio2
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] VS Code (version 1.95.0)
    • VS Code at C:\Users\abhi6\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.101.20241031

[✓] Connected device (4 available)
    • Redmi Note 8 Pro (mobile) • mf7tcmsg7d5ti7au • android-arm64  • Android 11 (API 30)
    • Windows (desktop)         • windows          • windows-x64    • Microsoft Windows [Version 10.0.22631.4391]
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 128.0.6613.121
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 130.0.2849.56

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 2e2c358c9b14765c90343af9df11e12c5dfc3e6c

**Comment by huycozy** [comment] 2024-11-04 07:34
Based on the output log and the black screen symptom, looks like you encountered https://github.com/flutter/flutter/issues/155973. Closing this as a duplicate of that one, please follow it for updates.

**Closed by huycozy** 2024-11-04 07:34 UTC
Labels: in triage
