### ISSUE TITLE
Firebase cloud messaging crash when on sending a message

### ISSUE THREAD

**Issue by RedTech64** [flutter/flutter#19017] opened 2018-07-02 22:41 UTC
My Flutter app is crashing on Android when I send a Firebase cloud message.

## Steps to Reproduce

1. Install firebase_messaging v1.0.3
2. Initialize FCM
3. Send message

## Error

```
[+17829 ms] E/AndroidRuntime( 2427): FATAL EXCEPTION: Firebase-FlutterFirebaseMessagingService
E/AndroidRuntime( 2427): Process: com.redtech.grade, PID: 2427
E/AndroidRuntime( 2427): java.lang.NoSuchMethodError: No static method zzc(Landroid/content/Context;)Lcom/google/firebase/iid/zzs; in class Lcom/google/firebase/iid/zzs; or its super classes (declaration of 'com.google.firebase.iid.zzs' appears in /data/app/com.redtech.grade-pNWCe4V8hZr-BNUnJaCn8A==/base.apk)
 E/AndroidRuntime( 2427):     at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:210)
E/AndroidRuntime( 2427):     at com.google.firebase.iid.zzg.run(Unknown Source:29)
E/AndroidRuntime( 2427):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime( 2427):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime( 2427):     at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
flutter  E/AndroidRuntime( 2427):     at java.lang.Thread.run(Thread.java:764)
```

## Code
```
final FirebaseMessaging _firebaseMessaging = new FirebaseMessaging();

Future initFCM() async{
  _firebaseMessaging.requestNotificationPermissions();
  _firebaseMessaging.configure(
    onMessage: (Map<String,dynamic> message) {},
    onLaunch: (Map<String,dynamic> message) {},
    onResume: (Map<String,dynamic> message) {},
  );
}
```

## Flutter doctor -v
```
[√] Flutter (Channel beta, v0.5.1, on Microsoft Windows [Version 10.0.17134.81], locale en-US)
    • Flutter version 0.5.1 at C:\flutter
    • Framework revision c7ea3ca377 (5 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 22.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[!] VS Code, 64-bit edition (version 1.24.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected devices (1 available)
    • SM G955U • 9888d33730415a4a32 • android-arm64 • Android 8.0.0 (API 26)
```

**Comment by zoechi** [comment] 2018-07-03 06:41
This looks like some version conflict. Can you please check all your dependencies (especially plugins) are of the latest version?

**Comment by felixng1028** [comment] 2018-07-03 16:37
same issue here.

build.gradle
`    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.2.1'
        classpath 'com.google.firebase:firebase-auth:16.0.2'
        classpath 'com.google.firebase:firebase-firestore:17.0.1'
        classpath 'com.google.firebase:firebase-functions:16.0.1'
        classpath 'com.google.firebase:firebase-core:16.0.1'
        classpath 'com.google.firebase:firebase-storage:16.0.1'
        classpath 'com.google.firebase:firebase-messaging:17.0.0'
    }`

pubspec.yaml:
`dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_webview_plugin: "0.1.6"
  shared_preferences: "0.4.2"
  cloud_firestore: "0.7.3"
  cloud_functions: "0.0.1"
  firebase_auth: "0.5.11"
  firebase_storage: "0.3.7"
  firebase_messaging: "1.0.3"`

**Comment by RedTech64** [comment] 2018-07-03 20:42
I'm still getting the crash with the lastest versions:
  cloud_firestore: "0.7.3"
  firebase_auth: "0.5.12"
  firebase_messaging: "1.0.3"
  cupertino_icons: "0.1.0"
  google_sign_in: "3.0.4"

classpath 'com.android.tools.build:gradle:3.1.2'
classpath 'com.google.gms:google-services:3.2.1'

**Comment by vortixhead** [comment] 2018-07-04 23:10
Same here

**Comment by RedTech64** [comment] 2018-07-05 12:38
On the [firebase-messaging example](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/example/android/build.gradle) it has google-services on 3.2.1, and other plugins break if they are on 4.0.1.

**Comment by sestegra** [comment] 2018-07-05 15:16
@RedTech64 If you read the [README.md](https://github.com/flutter/plugins/blob/master/packages/firebase_messaging/README.md)
```
... Next, modify the android/build.gradle file and the android/app/build.gradle file to add the Google services plugin as described by the Firebase assistant.
```

**Comment by RedTech64** [comment] 2018-07-06 02:40
Ok so I didn't update Google services because I ran in to this: #18579 However, I figured out that if you comment out or remove the `implementation 'com.google.firebase:firebase-core:16.0.1'` line in the app level build.gradle, the errors go away, and with the updated version FCM works properly.

**Comment by kroikie** [comment] 2018-07-19 16:48
@RedTech64 I was unable to reproduce this error. Could you show the message you are sending to the device?

**Comment by martinvarelaaaa** [comment] 2018-09-08 00:44
what is the status of this issue? when using firebase_analytics and firebase_messaging together it does not work

**Comment by zoechi** [comment] 2018-09-14 08:01
@RedTech64 is this still an issue?

**Comment by beardo01** [comment] 2018-10-08 12:45
Adding `implementation 'com.google.firebase:firebase-messaging:17.3.3'` to my app level build.gradle solved this for me.

**Comment by aidandavis** [comment] 2018-10-09 09:48
I have had the exact same problem. Adding 'implementation `'com.google.firebase:firebase-messaging:17.3.3'` also solved it for me.
I have tried many other things (thinking it was other gradle dependency issues) and this is the only fix I could find.

**Comment by beardo01** [comment] 2018-10-09 09:52
Hey @aidandavis, after some more work today I have been getting some other random crashes related to the Token Refresher. Not sure if this relates to this issue, but if `implementation 'com.google.firebase:firebase-messaging:17.3.3'` line is working for you, could you look out for any similar crashes?

**Comment by aidandavis** [comment] 2018-10-10 05:32
Hi @beardo01 I'm having that same crash too! 
It's often when I make a build through either vscode or in android studio and it auto-launches. I get an immediate crash on launch with an error saying Token Refresher. Force closing the app and re-launching sometimes fixes it but not always.

This happened prior to adding that new line, and is still happening now afterwards. I figured it was unrelated and hopefully won't happen in a prod build (haven't checked yet though).

**Comment by beardo01** [comment] 2018-10-10 05:39
Hey Aidan,

I've done a little bit more digging since yesterday. I believe that the crash is due to Google using outdated versions of their Android implementations in the Flutter plugins. I'm going to go through each and make a pull request to get it updated. In the mean time I have overridden the `implementation` versions for all of the Firebase plugins I'm using:

```
    implementation 'com.google.firebase:firebase-core:16.0.4'
    implementation 'com.google.firebase:firebase-analytics:16.0.4'
    implementation 'com.google.firebase:firebase-auth:16.0.4'
    implementation 'com.google.firebase:firebase-firestore:17.1.1'
    implementation 'com.google.firebase:firebase-functions:16.1.1'
    implementation 'com.google.firebase:firebase-messaging:17.3.3'
    implementation 'com.google.firebase:firebase-storage:16.0.3'
```
This seems to have stopped the crashing. Could you do the same and let me know if it works for you (only add the implementation for the plugins that you require - latest versions can be found [here](https://firebase.google.com/support/release-notes/android))?

**Comment by aidandavis** [comment] 2018-10-10 05:48
@beardo01 thanks for looking into it. I might not get a chance to try these out for few days now. I'm moving the builds through to our testing environment then I have training Thursday Friday. If this solves it for you and it's still broken on my end I'll try it out for the next build and give you a shout.

**Comment by rizkyandriawan** [comment] 2018-10-11 01:54
@beardo01 thanks a lot dude!

**Comment by aidandavis** [comment] 2018-10-15 05:17
Looks like they've updated many of the libraries now. https://github.com/flutter/plugins/blob/master/FlutterFire.md

**Comment by zoechi** [comment] 2018-12-18 15:35
Sounds like this was fixed.
Please add a comment if you disagree to get the issue reopened.

**Closed by zoechi** 2018-12-18 15:35 UTC
Labels: p: firebase, p: first party, plugin, severe: crash, waiting for customer response

**Comment by kroikie** [comment] 2019-10-13 19:03
@RedTech64

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/769. Any further collaboration will be done there.
