### ISSUE TITLE
App using flutter channel dev cannot be ran, using --dart-define

### ISSUE THREAD

**Issue by hoc081098** [flutter/flutter#76269] opened 2021-02-18 03:12 UTC
## Steps to Reproduce

Run flutter app with command:
```sh
flutter run --dart-define=ENV_STAFF_APP=0 --dart-define=ENV_APP_NAME=Member --dart-define=ENV_ID_SUFFIX= --dart-define=ENV_REDIRECT_URL=com.fiisoft.memberengagement
```

After upgrade flutter, cannot access anymore. Prev version works.

**Expected results:** 

Can access env variables in gradle.

**Actual results:** 

Cannot access

## Doctor -v
```sh
❯ flutter doctor -v
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on Mac OS X 10.15.6 19G73 darwin-x64,
    locale en-VN)
    • Flutter version 1.27.0-4.0.pre at
      /Users/petrushoc/development/flutter/flutter
    • Framework revision f8cd24de95 (32 hours ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/petrushoc/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone 11 (mobile)           • 6803EE6F-FD63-4704-9672-14DF684DDCA3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.
```

## Log
```sh
❯ flutter run --dart-define=ENV_STAFF_APP=0 --dart-define=ENV_APP_NAME=Member --dart-define=ENV_ID_SUFFIX= --dart-define=ENV_REDIRECT_URL=com.fiisoft.memberengagement
Changing current working directory to: /Users/petrushoc/Desktop/Company/member_engagement
Multiple devices found:
AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
iPhone 11 (mobile)           • 6803EE6F-FD63-4704-9672-14DF684DDCA3 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
[1]: AOSP on IA Emulator (emulator-5554)
[2]: iPhone 11 (6803EE6F-FD63-4704-9672-14DF684DDCA3)
Please choose one (To quit, press "q/Q"): 1
Using hardware rendering with device AOSP on IA Emulator. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
Plugin project :location_web not found. Please update settings.gradle.  
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugManifest'.                  
> Failed to calculate the value of task ':app:processDebugManifest' property 'manifestPlaceholders'.
   > java.lang.NullPointerException (no error message)                  
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 21s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        21.7s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by TahaTesser** [comment] 2021-02-18 09:02
Hi @hoc081098 
Unable to reproduce using latest `dev` channel
`flutterd run --dart-define=param1="flutter framework" --dart-define=param2="dart language" --dart-define=param3="VS Code" --dart-define=param4="Xcode"`


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  const param1 = String.fromEnvironment('param1');
  print('param1 = $param1');
  const param2 = String.fromEnvironment('param2');
  print('param2 = $param2');
  const param3 = String.fromEnvironment('param3');
  print('param3 = $param3');
  const param4 = String.fromEnvironment('param4');
  print('param4 = $param4');
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details>



<details>
<summary>logs</summary>

```bash
tahatesser@Tahas-MacBook-Pro dev_flutter % flutterd run --dart-define=param1="flutter framework" --dart-define=param2="dart language" --dart-define=param3="VS Code" --dart-define=param4="Xcode"
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling
software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        24.1s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              2,099ms
I/flutter (12172): param1 = flutter framework
I/flutter (12172): param2 = dart language
I/flutter (12172): param3 = VS Code
I/flutter (12172): param4 = Xcode
Syncing files to device Android SDK built for x86...               191ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:55067/YmXtLjRTXBw=/
D/EGL_emulation(12172): eglMakeCurrent: 0xed07f340: ver 3 0 (tinfo 0xd6893080)
D/eglCodecCommon(12172): setVertexArrayObject: set vao to 0 (0) 1 0
The Flutter DevTools debugger and profiler on Android SDK built for x86 is available at:
http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A55067%2FYmXtLjRTXBw%3D%2F

```

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-4.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f8cd24de95 (2 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182
! Doctor found issues in 2 categories.
```

</details>

 Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by illukinati** [comment] 2021-02-19 01:06
Same here!
after I upgrade "dev channel" I cannot run either to Android or iOS

**Comment by hoc081098** [comment] 2021-02-19 02:04
Cannot access env var in gradle anymore.
```groovy
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

Map<String, String> dartEnvironmentVariables = null
if (project.hasProperty('dart-defines')) {
    dartEnvironmentVariables = (project.property('dart-defines') as String)
            .split(',')
            .collectEntries { entry ->
                URLDecoder.decode(entry).split('=')
            }
}
project.logger.debug("dartEnvironmentVariables=$dartEnvironmentVariables")
def isStaff = (dartEnvironmentVariables?.('ENV_STAFF_APP') ?: '1') == '1'
def idSuffix = dartEnvironmentVariables?.('ENV_ID_SUFFIX') ?: (isStaff ? '.member_engagement' : '')
def appName = dartEnvironmentVariables?.('ENV_APP_NAME') ?: (isStaff ? "Staff" : "Member")
def redirectUrl = dartEnvironmentVariables?.('ENV_REDIRECT_URL')

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.fiisoft.member_engagement"
        applicationIdSuffix idSuffix
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        resValue "string", "app_name", appName

        manifestPlaceholders = [
                'appAuthRedirectScheme': redirectUrl
        ]
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            // signingConfig signingConfigs.debug

            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```

**Comment by TahaTesser** [comment] 2021-02-19 10:56
Hi @hoc081098 
Thanks for the details, I tried to reproduce on the `stable` and `dev`, 

Here I can see the value is being but logs don't show `dartEnvironmentVariables` or `param1_value` even on stable, how can you confirm the value is passed in previous channels in Gradle? As I can see value is being passed but can't confirm in Gradle even on stable

```bash
[  +52 ms] Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +41 ms] Starting incremental build...
[   +5 ms] Initializing file store
[  +19 ms] Skipping target: gen_localizations
[  +16 ms] complete
[   +9 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +13 ms] /Users/tahatesser/Code/flutter_stable/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/tahatesser/Code/flutter_stable/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/tahatesser/Code/flutter_stable/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental
--target=flutter --debugger-module-names --experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true
-Dparam1=flutter framework --output-dill
```







To verify the Gradle is appropriately per taking the value from dart-define, I use the [code sample](https://github.com/TatsuUkraine/flutter_define_example) from this [article](https://itnext.io/flutter-1-17-no-more-flavors-no-more-ios-schemas-command-argument-that-solves-everything-8b145ed4285d), value is correctly provided in the dev channel 

`flutter run --dart-define=DEFINEEXAMPLE_APP_NAME=FlutterIssueApp  --dart-define=DEFINEEXAMPLE_APP_SUFFIX=.dev -v`

![Screenshot_1613732045](https://user-images.githubusercontent.com/48603081/108495552-f12cb300-72ce-11eb-8d73-86ff951e8ded.png)


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel dev, 1.27.0-4.0.pre, on macOS 11.2.1 20D74 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-4.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f8cd24de95 (3 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.1 20D74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.182
! Doctor found issues in 2 categories.
```

</details>


Please try this code sample on the `dev` channel



Thank you

**Comment by hoc081098** [comment] 2021-02-22 05:54
@TahaTesser i confirmed it by look at `applicationIdSuffix idSuffix ` and `resValue "string", "app_name", appName`. I have switched to beta channel and it works again, but dev channel does not works

**Comment by TahaTesser** [comment] 2021-02-22 07:11
Hi @hoc081098 
Can you please this https://github.com/TatsuUkraine/flutter_define_example and run it on your channel with `flutter run --dart-define=DEFINEEXAMPLE_APP_NAME=FlutterIssueApp --dart-define=DEFINEEXAMPLE_APP_SUFFIX=.dev -v`
Thank ou

**Comment by hoc081098** [comment] 2021-02-26 10:10
> Hi @hoc081098
> Can you please this https://github.com/TatsuUkraine/flutter_define_example and run it on your channel with `flutter run --dart-define=DEFINEEXAMPLE_APP_NAME=FlutterIssueApp --dart-define=DEFINEEXAMPLE_APP_SUFFIX=.dev -v`
> Thank ou

beta channel works, but dev/master does not

**Comment by TahaTesser** [comment] 2021-02-26 11:35
Hi @hoc081098 
Modified app name here, it works fine on `master` channel
`flutterm run --dart-define=DEFINEEXAMPLE_APP_NAME=masterapp --dart-define=DEFINEEXAMPLE_APP_SUFFIX=.dev`

<img src="https://user-images.githubusercontent.com/48603081/109295335-965a0500-7854-11eb-84f6-476fef6d2504.png" width="300" />



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.27.0-9.0.pre.106, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 1.27.0-9.0.pre.106 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1610a27476 (7 hours ago), 2021-02-25 20:26:02 -0800
    • Engine revision 1515b1d4a4
    • Dart version 2.13.0 (build 2.13.0-79.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29)
      (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 11.2.2 20D80
      darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2021-03-19 12:46
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-19 12:46 UTC
Labels: in triage, waiting for customer response

**Comment by altermark** [comment] 2021-03-29 11:08
See: https://github.com/TatsuUkraine/flutter_define_example/issues/3 for possible cause/solution.

**Comment by altermark** [comment] 2021-03-31 08:46
@TahaTesser you triage many issues, so you will probably see it more often.

FYI `dart-defines` have different encoding when passed to gradle on Android, so in the application it works but when you try to use it in gradle it fails. See links my comment above.
