### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by AnnChangSal** [flutter/flutter#155193] opened 2024-09-14 01:02 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```console
#0      VmService._call (package:vm_service/src/vm_service.dart:1769:7)
#1      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#2      FlutterDevice.initLogReader (package:flutter_tools/src/resident_runner.dart:428:55)
#3      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408

**Comment by danagbemava-nc** [comment] 2024-09-16 06:44
Closing this as a duplicate of https://github.com/flutter/flutter/issues/154903, parent issue in https://github.com/flutter/flutter/issues/153471. 

If you have a reliable way to let us reproduce this, kindly leave a comment in the parent issue. 

Thank you

**Closed by danagbemava-nc** 2024-09-16 06:44 UTC
Labels: in triage
