### ISSUE TITLE
flutter analyze reports Target of URI doesn't exist:

### ISSUE THREAD

**Issue by bradyt** [flutter/flutter#36581] opened 2019-07-20 00:10 UTC
Copied from https://github.com/rrousselGit/provider/issues/164.

Running `flutter analyze` from terminal results in an error, as follows.

```
> git clean -dfx
> cd packages/provider
> flutter analyze
Analyzing provider...                                                   

  error • Target of URI doesn't exist: 'package:example/main.dart' • packages/provider/example/test/widget_test.dart:11:8 •
         uri_does_not_exist

1 issue found. (ran in 4.5s)
```

My version of flutter is as follows.

```
>  flutter --version
Flutter 1.7.8+hotfix.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b712a172f9 (10 days ago) • 2019-07-09 13:14:38 -0700
Engine • revision 54ad777fd2
Tools • Dart 2.4.0
```

**Comment by bradyt** [comment] 2019-07-30 00:33
I can do this with `flutter create --template=plugin`, then `git clean -dfx` and `flutter analyze`. But doing `flutter packages get` fixes it. Perhaps if `flutter analyze` or similar tools knew to do a `flutter packages get`, it would improve user experience?

```
$ flutter analyze
Running "flutter pub get" in uri_picker...                          2.1s
Analyzing uri_picker...                                                 

  error • Target of URI doesn't exist: 'package:uri_picker_example/main.dart' • example/test/widget_test.dart:11:8 • uri_does_not_exist
  error • The function 'MyApp' isn't defined • example/test/widget_test.dart:16:29 • undefined_function

2 issues found. (ran in 3.9s)
```

**Comment by jonahwilliams** [comment] 2020-01-24 19:00
Duplicate of https://github.com/flutter/flutter/issues/7275

**Closed by jonahwilliams** 2020-01-24 19:00 UTC
Labels: proposal, tool
