### ISSUE TITLE
App flashes when you bring it back to foreground on Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#7246] opened 2016-12-13 18:01 UTC
Open a Flutter app on Android.
Background it.
Bring it back to foreground.

Observed: flash of black before redraw of app.

Expected: no flash. (for comparison, when I foreground an Android SDK app, I don't see a flash)

**Comment by eseidelGoogle** [comment] 2017-08-02 17:00
Is this still happening? :)

**Comment by Hixie** [comment] 2017-12-13 00:44
Yes.

**Comment by Hixie** [comment] 2017-12-13 00:45
Actually the bug we see now is on (re)startup, not just coming back from background. Going to close this one.

**Closed by Hixie** 2017-12-13 00:45 UTC
Labels: prod: engine, ▣ platform-android

**Comment by therealjohnsummer** [comment] 2019-10-01 10:01
This problem has resurfaced on ALL iOS devices. This only happens on Flutter built apps on iOS. Other apps on iOS do not exhibit the issue. I have also upgraded to iOS 13.1.2. Tested on physical devices - iPhone 7 Plus, iPhone X, iPhone 11 Pro Max, iPhone SE, iPad Pro. 

To reproduce :

1) Deploy an app to a live device
2) Run the app
3) Put the app to the background
4) Swipe down on the device to show SIRI Suggestions/search.
5) Select your app that you backgrounded

Repeat steps 3,4,5 and you will see a horrible flash when the app is brought back to foreground.
Only seems to happen when app is brought back from SIRI/Search screen.


You will need to repeat steps 3,4,5 a few times to see this. On iPhone 11 pro max it is reproducible instantly. Have tested with Reflectly and we see this behaviour. Also the standard counter app.

Attached screencast shows the flash. Happens at 6, 8 and 10secs.


[flicker1.mp4.zip](https://github.com/flutter/flutter/files/3675570/flicker1.mp4.zip)

**Comment by eseidelGoogle** [comment] 2019-10-01 14:42
@therealjohnsummer thank you for the report!  This would be easier for us to handle if this was a new report.  That way we could route it correctly and not have the baggage of this 2 year old (possibly unrelated) issue.  Would you be willing to file a new/separate issue?  Thanks!  FYI @gaaclarke

**Comment by gaaclarke** [comment] 2019-10-01 17:24
> you will see a horrible flash when the app is brought back to foreground.

Hi, @therealjohnsummer I watched the video.  I've seen 3 things that could be considered a flash:
1) The sun jumps.
2) The bevel around the app changes.
3) The horizontal scroller draws its cells the wrong size for one frame.

The sun jumping is a programmer error.  It looks like that sun is set to rotate based off the system clock.  When the app is backgrounded a screenshot is taken, the animation timer should be frozen at that time as well.

The bevel changing I believe is part of the operating system.  Do you think that behavior is erroneous?

The 3rd item is what I suspect you were referring to when you mention a flash.  Is that true? 
 When you file your new issue can you add that information into your issue that it specifically has to do with the horizontal scroller rendering at the wrong size for one frame?  Thanks again for the report.

**Comment by bpaul7101** [comment] 2019-10-01 18:13
I have this also and it is not programmer induced as this can easily be repeated by simply creating a flutter project and deploying it on a device (Running the counter app).

A new issue has now been created here : https://github.com/flutter/flutter/issues/41679

@gaaclarke The issue is apparent in the video and also exactly from what I am experiencing. The bottom half of the app appears to be drawn in the middle of the app in an instant (flash).

**Comment by chiuhol** [comment] 2020-11-17 03:23
Hi,I have the same problems,did you solve it now?
