### ISSUE TITLE
Hot restart on web resets current URL route after upgrading to 2.2

### ISSUE THREAD

**Issue by andrewjallenuoft** [flutter/flutter#84231] opened 2021-06-08 23:36 UTC
Prior to Flutter 2.2, if the application was hot restarted, the current URL displayed world persist. For example, if the application was at _localhost:5555/some/route_, then after a hot restart the application would boot directly to the same route (_localhost:5555/some/route_).

After upgrading to 2.2 (and continuing in 2.2.1), the route is cleared and reset to the default. I.e. after hot restart, the application will start at _localhost:5555/_, regardless of what the previous route was .

This is not a major issue, but somewhat of a minor development annoyance. 

## Steps to Reproduce

1. Start a flutter web application in debug mode
2. Navigate to some named route
3. Hot restart the application. It will now be reset to the default route.

**Comment by bernaferrari** [comment] 2021-06-09 02:52
duplicate of https://github.com/flutter/flutter/issues/82737 and https://github.com/flutter/flutter/issues/79241

**Comment by darshankawar** [comment] 2021-06-09 09:56
Closing this as duplicate of above linked issues.

**Closed by darshankawar** 2021-06-09 09:56 UTC
Labels: in triage
