### ISSUE TITLE
Package the flutter as APK, release reports an error and there is no log, but debug runs normally

### ISSUE THREAD

**Issue by lqx359** [flutter/flutter#60509] opened 2020-06-29 08:49 UTC
Package the flutter as APK, release reports an error and there is no log, but debug runs normally

**Comment by lqx359** [comment] 2020-06-30 03:39
[app-release.zip](https://github.com/flutter/flutter/files/4849298/app-release.zip)

sry to get back to you so late


my flutter doctor -v :Flutter version 1.18.0-11.1.pre 
pubspec.yaml:
name: flutter_tencentplayer
description: Is a native plugin for playing Tencent Cloud on-demand videos, live streaming, offline downloads, etc.
version: 0.6.0
author: qq326646683<326646683@qq.com>,yxwandroid<yxw_flutter@163.com>
homepage: https://github.com/qq326646683/flutter_tencentplayer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.jinxian.flutter_tencentplayer
    pluginClass: FlutterTencentplayerPlugin



> Hi @lqx359
> Can you please provide your `flutter doctor -v`,
> your `flutter build apk -v`
> and your `pubspec.yaml`.
> Thank you

**Comment by TahaTesser** [comment] 2020-06-30 09:04
Hi @lqx359 
Can you please provide *complete** `flutter doctor -v`, your `flutter build apk -v`
File you have provided seems to be corrupted, it's not opening 


Looks like you trying to build [flutter_tencentplayer](https://github.com/qq326646683/flutter_tencentplayer), maybe you want to make apk from example of the plugin, you can go to example folder then build aok
Thank you

**Comment by lqx359** [comment] 2020-07-02 03:15
> Hi @lqx359
> Can you please provide _complete_* `flutter doctor -v`, your `flutter build apk -v`
> File you have provided seems to be corrupted, it's not opening
> 
> Looks like you trying to build [flutter_tencentplayer](https://github.com/qq326646683/flutter_tencentplayer), maybe you want to make apk from example of the plugin, you can go to example folder then build aok
> Thank you

i just go to example folder and build apk,it's no working

**Comment by TahaTesser** [comment] 2020-07-02 06:57
Hi @lqx359 
Can you please try a new flutter project without using any code sample/third party packages?
If problem persist, can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by TahaTesser** [comment] 2020-07-24 13:50
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-24 13:50 UTC
Labels: in triage
