### ISSUE TITLE
"ninja: error: failed recompaction: No such file or directory" building on linux

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#122735] opened 2023-03-15 18:18 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I ran `flutter run` and chose Linux as the target for an application I had created a few weeks ago and not touched for a while. It failed as described below. Then I tried running it again and it worked fine.

### Actual results

```
$ run
Waiting for another flutter command to release the startup lock...
Multiple devices found:
Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-56-generic
Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.121
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (or "q" to quit): 1
Resolving dependencies... 
  async 2.10.0 (2.11.0 available)
  material_color_utilities 0.2.0 (0.3.0 available)
Got dependencies!
Launching lib/main.dart on Linux in debug mode...
CMake Error:
  Running

   '/home/ianh/dev/depot_tools/ninja' '-C' '/home/ianh/dev/blankcanvas/example/build/linux/x64/debug' '-t' 'recompact'

  failed with:

   fatal: not a git repository (or any of the parent directories): .git

  ninja: warning: bad deps log signature or version; starting over

  ninja: error: failed recompaction: No such file or directory



CMake Generate step failed.  Build files cannot be regenerated correctly.
Building Linux application...                                           
Exception: Unable to generate build files
```

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console
$ flutter doctor -v
[✓] Flutter (Channel main, 3.9.0-7.0.pre.38, on Ubuntu 22.04.1 LTS 5.15.0-56-generic, locale C.UTF-8)
    • Flutter version 3.9.0-7.0.pre.38 on channel main at /home/ianh/dev/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision e08d250eeb (21 minutes ago), 2023-03-15 10:53:29 -0700
    • Engine revision b7297f0259
    • Dart version 3.0.0 (build 3.0.0-322.0.dev)
    • DevTools version 2.22.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /home/ianh/Android/Sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /home/ianh/bin/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/ianh/bin/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at /home/ianh/bin/idea-IC-221.5921.22
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-56-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.121

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-03-16 09:04
Thanks for the report, @Hixie 
Unfortunately, I also can not reproduce this issue on my end (even with a new project or old project created one month ago). 

However, when taking a look at the stack trace, it seems to be a `ninja` build issue (see a [ninja-build issue](https://github.com/ninja-build/ninja/issues/2048) on Window with the similar error log). As mentioned at https://github.com/ninja-build/ninja/issues/2048#issuecomment-1143400240, it looks like the issue's caused by `ninja` from 1.8 onwards. It would be appreciated if you could retry a lower ninja version on your system to see if it is the cause of this issue (once you see this issue again). 

Also, as you are unable to reproduce this, feel free to close it and write a comment when you have clear steps to reproduce. Thank you!

**Comment by jason-simmons** [comment] 2023-03-16 18:23
The version of ninja in depot_tools has been deprecated (see https://groups.google.com/a/chromium.org/g/chromium-dev/c/xFYvFYGQUGI)

If the deprecated ninja is at the head of your `PATH`, then `flutter doctor` should report that ninja is not correctly installed.

**Closed** 2023-04-06 09:09 UTC
Labels: waiting for customer response, in triage
