### ISSUE TITLE
User Reported Exception: The method 'dispose' was called on null. Maybe caused by Ink/InkWell.

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#15148] opened 2018-03-05 03:10 UTC
## Steps to Reproduce

We got some weird exceptions via sentry from the user. Maybe caused by Flutter Library.
Since we replaced Container/GestureDetector with Ink/InkWell, reported exceptions grow much more.

## StackTrace
```
NoSuchMethodError: NoSuchMethodError: The method 'dispose' was called on null.
Receiver: null
Tried calling: dispose()
  File "hooks.dart", line 109, in _drawFrame
  File "hooks.dart", line 122, in _invoke
  File "zone.dart", line 925, in _CustomZone.runGuarded
  File "zone.dart", line 1023, in _CustomZone.run
  File "zone.dart", line 1126, in _rootRun
  File "binding.dart", line 842, in BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
  File "binding.dart", line 930, in BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
  File "binding.dart", line 990, in BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 208, in BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback
  File "binding.dart", line 622, in BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame
  File "binding.dart", line 270, in BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame
  File "object.dart", line 709, in PipelineOwner.flushLayout
  File "object.dart", line 1445, in RenderObject._layoutWithoutResize
  File "custom_layout.dart", line 338, in RenderCustomMultiChildLayoutBox.performLayout
  File "custom_layout.dart", line 194, in MultiChildLayoutDelegate._callPerformLayout
  File "scaffold.dart", line 325, in _ScaffoldLayout.performLayout
  File "custom_layout.dart", line 124, in MultiChildLayoutDelegate.layoutChild
  File "object.dart", line 1570, in RenderObject.layout
  File "flex.dart", line 798, in RenderFlex.performLayout
  File "object.dart", line 1570, in RenderObject.layout
  File "stack.dart", line 509, in RenderStack.performLayout
  File "object.dart", line 1570, in RenderObject.layout
  File "proxy_box.dart", line 107, in RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
  File "object.dart", line 1570, in RenderObject.layout
  File "proxy_box.dart", line 107, in RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
  File "object.dart", line 1570, in RenderObject.layout
  File "proxy_box.dart", line 107, in RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
  File "object.dart", line 1570, in RenderObject.layout
  File "proxy_box.dart", line 107, in RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
  File "object.dart", line 1570, in RenderObject.layout
  File "proxy_box.dart", line 107, in RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
  File "object.dart", line 1570, in RenderObject.layout
  File "viewport.dart", line 932, in RenderViewport.performLayout
  File "viewport.dart", line 1008, in RenderViewport._attemptLayout
  File "viewport.dart", line 285, in RenderViewportBase.layoutChildSequence
  File "object.dart", line 1570, in RenderObject.layout
  File "sliver_padding.dart", line 182, in RenderSliverPadding.performLayout
  File "object.dart", line 1570, in RenderObject.layout
  File "sliver_list.dart", line 251, in RenderSliverList.performLayout
  File "sliver_multi_box_adaptor.dart", line 434, in RenderSliverMultiBoxAdaptor.collectGarbage
  File "object.dart", line 1666, in RenderObject.invokeLayoutCallback
  File "object.dart", line 740, in PipelineOwner._enableMutationsToDirtySubtrees
  File "object.dart", line 1666, in RenderObject.invokeLayoutCallback.<fn>
  File "sliver_multi_box_adaptor.dart", line 440, in RenderSliverMultiBoxAdaptor.collectGarbage.<fn>
  File "sliver_multi_box_adaptor.dart", line 270, in RenderSliverMultiBoxAdaptor._destroyOrCacheChild
  File "sliver.dart", line 754, in SliverMultiBoxAdaptorElement.removeChild
  File "framework.dart", line 2205, in BuildOwner.buildScope
  File "sliver.dart", line 758, in SliverMultiBoxAdaptorElement.removeChild.<fn>
  File "framework.dart", line 2670, in Element.updateChild
  File "framework.dart", line 2926, in Element.deactivateChild
  File "framework.dart", line 1709, in _InactiveElements.add
  File "framework.dart", line 1700, in _InactiveElements._deactivateRecursively
  File "framework.dart", line 3659, in ComponentElement.visitChildren
  File "framework.dart", line 1700, in _InactiveElements._deactivateRecursively
  File "framework.dart", line 3659, in ComponentElement.visitChildren
  File "framework.dart", line 1700, in _InactiveElements._deactivateRecursively
  File "framework.dart", line 3659, in ComponentElement.visitChildren
  File "framework.dart", line 1700, in _InactiveElements._deactivateRecursively
  File "framework.dart", line 4599, in SingleChildRenderObjectElement.visitChildren
  File "framework.dart", line 1700, in _InactiveElements._deactivateRecursively
  File "framework.dart", line 3659, in ComponentElement.visitChildren
  File "framework.dart", line 1700, in _InactiveElements._deactivateRecursively
  File "framework.dart", line 3659, in ComponentElement.visitChildren
  File "framework.dart", line 1700, in _InactiveElements._deactivateRecursively
  File "framework.dart", line 3659, in ComponentElement.visitChildren
  File "framework.dart", line 1700, in _InactiveElements._deactivateRecursively
  File "framework.dart", line 4599, in SingleChildRenderObjectElement.visitChildren
  File "framework.dart", line 1700, in _InactiveElements._deactivateRecursively
  File "framework.dart", line 4599, in SingleChildRenderObjectElement.visitChildren
  File "framework.dart", line 1698, in _InactiveElements._deactivateRecursively
  File "framework.dart", line 3775, in StatefulElement.deactivate
  File "ink_decoration.dart", line 236, in _InkState.deactivate
  File "object_patch.dart", line 46, in Object.noSuchMethod
```

**Comment by Hixie** [comment] 2018-03-16 17:16
Hard to say but I'm pretty sure this is a dupe of https://github.com/flutter/flutter/issues/14773.

**Closed by Hixie** 2018-03-16 17:16 UTC
