### ISSUE TITLE
[iOS] `Parse Issue (Xcode): Module 'camera_avfoundation' not found` error on a specific flavor (production only) 

### ISSUE THREAD

**Issue by jadenwatt** [flutter/flutter#144120] opened 2024-02-26 06:20 UTC
### Steps to reproduce

Running my production flavor gives this error, when I run my staging flavor the app runs and it works fine. I wonder if I set up my prod flavor wrong. This is a flutter/firebase app.

### Expected results

App should run just how it does on staging.

### Actual results

```
App doesnt build:
Could not build the precompiled application for the device.
Parse Issue (Xcode): Module 'camera_avfoundation' not found
/Users/.../GeneratedPluginRegistrant.m:11:8
``` 

### Code sample

N/A

### Screenshots or Video

<img width="1035" alt="Screenshot 2024-02-25 at 10 16 34 PM" src="https://github.com/flutter/flutter/assets/70243409/e537c233-fed7-4f1b-928b-9099419974c1">

### Flutter Doctor output

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.3, on macOS 14.1.1 23B81 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by jadenwatt** [comment] 2024-02-26 21:04
Upgrading to the latest Flutter version worked! Thank you! After doing this I just needed to `flutter clean && flutter pub get` and also `pod install` inside of the ios directory!

**Comment by dam-ease** [comment] 2024-02-27 06:34
Thanks for your response and the update!
Can you please share the full logs of the error you get on VScode?
Also, when you try running from your terminal, do you get similar errors?

**Comment by jadenwatt** [comment] 2024-02-27 08:00
`Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project:
Xcode build done.                                           25.4s
Failed to build iOS app
Could not build the precompiled application for the device.
Parse Issue (Xcode): Module 'camera_avfoundation' not found
/Users/.../ios/Runner/GeneratedPluginRegistrant.m:11:8
GeneratedPluginRegistrant.m:11
2

Error launching application on iPhone.

Exited (1).`

**Comment by dam-ease** [comment] 2024-02-28 07:23
Thanks for your response
Please can you try out the suggested solution here https://stackoverflow.com/a/77061114 to see if this helps?

**Comment by jadenwatt** [comment] 2024-02-29 02:13
This did not work

**Comment by dam-ease** [comment] 2024-02-29 06:58
Thanks for your response @jadenwatt
I see a similar issue to this https://github.com/flutter/flutter/issues/92577. Can you confirm your build configurations as in https://github.com/flutter/flutter/issues/92577#issuecomment-954107673?
If that's not the issue, please attach your ios/Runner.xcodeproj/project.pbxproj.

**Comment by jadenwatt** [comment] 2024-02-29 07:35
My build configurations seem correct:
<img width="642" alt="Screenshot 2024-02-28 at 11 31 37 PM" src="https://github.com/flutter/flutter/assets/70243409/fda0f030-fe00-4ce3-b8c6-77230d6a1928">

/Users/jadenwatt/development/projects/Geninnovation/ios/Runner.xcodeproj/project.pbxproj

**Comment by dam-ease** [comment] 2024-02-29 10:18
Thanks for sharing this @jadenwatt.
Kindly attach a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code that reproduces the issue so as to move this issue forward?

**Comment by jadenwatt** [comment] 2024-03-01 01:18
Not sure how I can do this as it seems that this is an issue with how I setup my production flavor, but I'm not sure how to find the issue.

**Comment by huycozy** [comment] 2024-03-01 05:21
It could be caused by the chosen configuration (please see https://github.com/flutter/flutter/issues/92577#issuecomment-957759041). Please provide a minimal sample code with the same flavor setup so that we can take a look and investigate. Thanks!

**Comment by jadenwatt** [comment] 2024-03-01 06:25
Here is a compressed file. I setup a prod flavor and dev/stg one as well. Same as my app and also added the dependencies that I use. 
[minimal_sample_code.zip](https://github.com/flutter/flutter/files/14457431/minimal_sample_code.zip)

**Comment by huycozy** [comment] 2024-03-04 06:24
Thanks for sharing a sample project. But I got another issue when checking the issue. When I open it on XCode, select `Production` scheme but can't select any devices:

| STEV | Production |
| --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/4043bcbb-70a4-47dc-a64d-8e833f1f7255"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/d39de219-17c8-43d9-947e-ed77fecb7f5e">

Did you also see this issue?

**Comment by jadenwatt** [comment] 2024-03-04 20:49
@huycozy I don't see this issue. It may be because the production scheme needs a real device to run locally.

**Comment by huycozy** [comment] 2024-03-05 05:59
I managed to make it run. Your `Production` scheme should choose the correct `Build Configuration`: It was `Debug`. After choosing `Debug-Production`, I can select the run destination (devices/emulators are listed up) and the app can run without issue (with both XCode and Flutter)

![Screenshot 2024-03-05 at 12 55 33](https://github.com/flutter/flutter/assets/104349824/2fda1130-e411-47f0-9e23-fc31e276433c)

![Screenshot 2024-03-05 at 12 53 38](https://github.com/flutter/flutter/assets/104349824/db136c61-b6fc-4332-8ca0-d8eb99cab4b2)

So, please check your `Production scheme` again and retry.

**Comment by jadenwatt** [comment] 2024-03-06 08:34
<img width="948" alt="Screenshot 2024-03-06 at 12 34 17 AM" src="https://github.com/flutter/flutter/assets/70243409/2c067300-dcbb-4532-b9ca-ba844a1f3c24">

This is what my production scheme looks like. still doesn't work.

**Comment by huycozy** [comment] 2024-03-07 04:27
I'm not sure if this could be related. But you can try removing all packages except `camera` (I did the same on my end because the project took a long time to build). This is the updated project with `camera` package only: [minimal_sample_code.zip](https://github.com/flutter/flutter/files/14518694/minimal_sample_code.zip)

**Comment by jadenwatt** [comment] 2024-03-08 08:35
No luck with anything

**Comment by huycozy** [comment] 2024-03-11 03:17
I'm unsure what can cause the issue on your side. Label this to get more input from others.

**Comment by jmagman** [comment] 2024-03-15 01:31
> Here is a compressed file. I setup a prod flavor and dev/stg one as well. Same as my app and also added the dependencies that I use.
> [minimal_sample_code.zip](https://github.com/flutter/flutter/files/14457431/minimal_sample_code.zip)

I tried this on the master channel and it built fine in the terminal, and `build ipa` worked. 
```
$ flutter build ipa --flavor production

Archiving com.example.minimalSampleCode.prod...
Automatically signing iOS for device deployment using specified development team in Xcode project: S8QB4VV633
Running Xcode build...
 └─Compiling, linking and signing...                      2,216ms
Xcode archive done.                                         17.4s
Built /Users/magder/Downloads/minimal_sample_code/build/ios/archive/Runner.xcarchive.

[!] App Settings Validation
    • Version Number: 1.0.0
    • Build Number: 1
    • Display Name: GenInnovation
    • Deployment Target: 12.0
    • Bundle Identifier: com.example.minimalSampleCode.prod
    ! Your application still contains the default "com.example" bundle identifier.

[!] App Icon and Launch Image Assets Validation
    ! App icon is set to the default placeholder icon. Replace with unique icons.
    ! Launch image is set to the default placeholder icon. Replace with unique launch image.

To update the settings, please refer to https://docs.flutter.dev/deployment/ios

Building App Store IPA...                                          22.1s
Built IPA to /Users/m/Downloads/minimal_sample_code/build/ios/ipa.
```

Can you run again with the `-v` verbose flag, and attach that output?  It will be large.

**Comment by jadenwatt** [comment] 2024-03-16 00:58
Everything is working now, not sure what changed. I tried `flutter build ipa --flavor production -v` and it built the ipa, then I went to see if the app would run through vscode and it now works. Not sure what happened, but seems things got better once updating my Flutter version.

**Comment by MitchellGoodwin** [comment] 2024-03-20 20:55
If you happen to see this issue again, please feel free to file a new issue with the requested logs. Closing this in the meantime.

**Closed by MitchellGoodwin** 2024-03-20 20:55 UTC
Labels: platform-ios, tool, p: camera, t: xcode, package, team-ios
