### ISSUE TITLE
ScaffoldState.openDrawer brings the keyboard up

### ISSUE THREAD

**Issue by agordeev** [flutter/flutter#54277] opened 2020-04-08 14:53 UTC
As soon as I press Drawer button, it shows me keyboard back.

Please see this gif that demonstrates the issue

![video](https://user-images.githubusercontent.com/2883524/78798279-7b26a280-79c1-11ea-8138-532a110f1967.gif)

My code is quite simple:

```dart

    return GestureDetector(
      onTap: () => FocusScope.of(context).unfocus(),
      child: ListView(
        padding: const EdgeInsets.all(16.0),
        children: <Widget>[
            //... my form widgets go here
        ],),);
```

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-RU)
    • Flutter version 1.17.0 at /Users/andrey/flutter_beta
    • Framework revision d3ed9ec945 (2 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/andrey/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (5 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 8.1.0 (API 27) (emulator)
    • iPad                      • 8807f3e1632ff643cc3f92f0f207ae5a7d831121 • ios            • iOS 13.3.1
    • iPhone 11 Pro             • 1A5C302F-1156-4A9E-A269-1B0B80B2BCBC     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 80.0.3987.163
    • Web Server                • web-server                               • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-04-08 15:11
Hi @agordeev 
could you please provide a complete minimal reproducible code sample? such that I can copy and run

**Comment by TahaTesser** [comment] 2020-04-30 10:35
Hi @agordeev 
Are you still experiencing this issue?
Thank you

**Comment by agordeev** [comment] 2020-04-30 14:00
Yes, it's still reproducible on 1.17.0-3.3.pre. It's not reproducible with the code snippet above though.

**Comment by agordeev** [comment] 2020-05-01 16:49
@VladyslavBondarenko this issue is not my priority at this moment, so I'm going to close it for now.

**Comment by xsahil03x** [comment] 2020-05-14 10:09
Facing similar issue.

**Comment by mohammadamir98** [comment] 2020-05-18 09:36
The same issue happened to me. 
It only happens when you close the keyboard shown for texfield with 
`FocusScope.of(context).unfocus();`

**Comment by VladyslavBondarenko** [comment] 2020-05-18 11:41
Reproduces with current stable `1.17.1` (`1.17.0` as well), beta `1.18.0-11.1.pre`, dev `1.19.0-1.0.pre`.
But not with previous stable `v1.12.13+hotfix.9`. 

Code sample from https://github.com/flutter/flutter/issues/54277#issuecomment-611016111

**Comment by gspencergoog** [comment] 2020-06-09 01:35
I bisected this and traced the cause to [this PR](https://github.com/flutter/flutter/pull/50831), which makes sense.

I'll try and track down the exact cause of the regression.

**Comment by gspencergoog** [comment] 2020-06-09 02:59
Actually, it looks like the example code has a bug in it, and the PR (which corrected some buggy behavior in focus handling) has tickled that bug:

The corrected code should look like this:
<details>
<pre>
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        final FocusScopeNode currentScope = FocusScope.of(context);
        if (!currentScope.hasPrimaryFocus && currentScope.hasFocus) {
          FocusManager.instance.primaryFocus.unfocus();
        }
      },
      child: Scaffold(
        appBar: AppBar(title: const Text('title')),
        body: const Center(child: TextField()),
        drawer: Drawer(
          child: ListView(
            padding: EdgeInsets.zero,
            children: <Widget>[
              const DrawerHeader(
                child: Text('Drawer Header'),
                decoration: BoxDecoration(
                  color: Colors.blue,
                ),
              ),
              ListTile(
                title: const Text('Item 1'),
                onTap: () {
                  Navigator.pop(context);
                },
              ),
              ListTile(
                title: const Text('Item 2'),
                onTap: () {
                  Navigator.pop(context);
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}
</pre>
</details>

Where instead of:
```dart
      onTap: () {
        FocusScopeNode currentFocus = FocusScope.of(context);
        if (!currentFocus.hasPrimaryFocus) {
          currentFocus.unfocus();
        }
      },
```

The code should be:
```dart
      onTap: () {
        final FocusScopeNode currentScope = FocusScope.of(context);
        if (!currentScope.hasPrimaryFocus && currentScope.hasFocus) {
          FocusManager.instance.primaryFocus.unfocus();
        }
      },
```

The original version gets the scope of the current context (which is the modal scope for the navigator's overlay), and then tells the scope to unfocus itself only if it _does not_ have primary focus.  Which, if the text field doesn't have focus, the scope does have focus, so it doesn't call unfocus at all then.

If the text field does have focus, then the code does call unfocus _on the scope_, which hands the focus to its parent scope, which is the navigator scope. Then, when the navigator pushes the drawer route, it tries to focus its own scope, but since we've just focused the navigator's scope, and the "first focus" of that scope is still the child scope, and its first focus is the editable text, the editable text gets focus again, raising the keyboard.

My recommendation above will instead only unfocus the primary focus if it is on a descendant of the current scope, but won't unfocus the scope itself, so it doesn't hand focus to the navigator's scope.

The bug in the example is that it calls `unfocus` on itself: it should call `unfocus` on the `primaryFocus`.

**Comment by HansMuller** [comment] 2020-08-07 20:02
I'm going to close this issue, since it appears that https://github.com/flutter/flutter/issues/54277#issuecomment-640998757 explains how to use correctly use the unfocus API and avoid the problem.

**Closed by HansMuller** 2020-08-07 20:02 UTC
Labels: a: text input, f: focus, f: material design, found in release: 1.17, found in release: 1.18, found in release: 1.19, framework, has reproducible steps, severe: regression

**Comment by basilmariano** [comment] 2021-06-14 08:36
This issue still happens

```
Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.6 19G2021 darwin-x64,
    locale en-PH)
```

I Tried adding the code from #54277 (comment)  before opening the Drawer but it doesnt work

@HansMuller any advice?

**Comment by tattivitorino** [comment] 2021-06-23 20:00
@basilmariano, as @gspencergoog explained,  this worked for me:
```
onTap: () {
        final FocusScopeNode currentScope = FocusScope.of(context);
        if (!currentScope.hasPrimaryFocus && currentScope.hasFocus) {
          FocusManager.instance.primaryFocus.unfocus();
        }
      },
```
