### ISSUE TITLE
X Unable to locate Android SDK.

### ISSUE THREAD

**Issue by z7b** [flutter/flutter#83331] opened 2021-05-25 10:07 UTC
```
C:\Users\Administrator>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.3.0-12.1.pre, on Microsoft Windows [Version 10.0.19043.985], locale ar-SA)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Android Studio (version 4.2.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

```

**Comment by TahaTesser** [comment] 2021-05-25 12:40
Hi @z7b 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/83232
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-25 12:40 UTC
Labels: in triage
