### ISSUE TITLE
Not all pinned dependencies upgrade with `flutter update-packages`

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#53350] opened 2020-03-26 14:32 UTC
Flutter currently pins several packages to outdated versions:
```
$ cd packages/flutter
$ flutter pub outdated
Package           Current   Upgradable  Resolvable  Latest
dependencies
collection        *1.14.11  *1.14.11    *1.14.11    1.14.12

dev_dependencies
archive           *2.0.11   *2.0.11     *2.0.11     2.0.13
args              *1.5.2    *1.5.2      *1.5.2      1.6.0
async             *2.4.0    *2.4.0      *2.4.0      2.4.1
boolean_selector  *1.0.5    *1.0.5      *1.0.5      2.0.0
charcode          *1.1.2    *1.1.2      *1.1.2      1.1.3
crypto            *2.1.3    *2.1.3      *2.1.3      2.1.4
image             *2.1.4    *2.1.4      *2.1.4      2.1.12
petitparser       *2.4.0    *2.4.0      *2.4.0      3.0.1
quiver            *2.0.5    *2.0.5      *2.0.5      2.1.3
source_span       *1.5.5    *1.5.5      *1.5.5      1.7.0
xml               *3.5.0    *3.5.0      *3.5.0      3.7.0

transitive dependencies: all up-to-date
```

I tried to updated these with `flutter update-packages --force-upgrade` in https://github.com/flutter/flutter/pull/53349, however that only moved one of them (`http_parser: 3.1.3` -> `3.1.4`). Is there a bug in `flutter update-packages --force-upgrade` ?

**Comment by devoncarew** [comment] 2020-03-27 13:12
It's likely that these are manually pinned in places. @zanderso and @jonahwilliams would know where in the codebase that's happening.

**Comment by zanderso** [comment] 2020-03-27 16:02
Possible duplicate of https://github.com/flutter/flutter/issues/36511 ?

**Comment by zanderso** [comment] 2020-03-27 16:05
Tangentially related: https://github.com/flutter/flutter/issues/50646

**Comment by jonahwilliams** [comment] 2020-03-27 17:33
I may need some assistance from the Dart/Pub teams. When pub is version solving, how does it resolve the dependencies of `sdk: flutter` deps? We may have an order of operations issue here, where pub is still seeing `sdk: flutter` dependencies from `t - 1` when solving at `t`

**Comment by jonahwilliams** [comment] 2020-03-27 18:42
NVM, it uses flutter root

**Comment by dnfield** [comment] 2020-03-27 20:28
Why does Flutter depend on args?  Or xml?  Or  several of the other ones in there?

**Comment by dnfield** [comment] 2020-03-27 20:29
Ah..  Those are all transitive dependencies of libraries we depend on.

**Closed** 2020-03-28 05:11 UTC
Labels: tool
