### ISSUE TITLE
git clone does not work with 3.0.1

### ISSUE THREAD

**Issue by vixez** [flutter/flutter#105122] opened 2022-06-01 13:39 UTC
Hello,

We use `git clone` to install Flutter during our code build on AWS. The following command used to work fine until 3.0.1

`git clone --depth 1 -b 3.0.1 https://github.com/flutter/flutter.git`

After doing this, `flutter doctor` returns the following

```
[Container] 2022/06/01 13:12:37 Running command flutter doctor
--
120 | Doctor summary (to see all details, run flutter doctor -v):
121 | [✓] Flutter (Channel 3.0.1, 0.0.0-unknown, on Ubuntu 20.04.4 LTS 4.14.246-187.474.amzn2.x86_64, locale en_US)
122 | [✗] Android toolchain - develop for Android devices
123 | ✗ Unable to locate Android SDK.
124 | Install Android Studio from: https://developer.android.com/studio/index.html
125 | On first launch it will assist you in installing the Android SDK components.
126 | (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
127 | If the Android SDK has been installed to a custom location, please use
128 | `flutter config --android-sdk` to update to that location.
129 |  
130 | [✓] Chrome - develop for the web
131 | [✗] Linux toolchain - develop for Linux desktop
132 | ✗ clang++ is required for Linux development.
133 | It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
134 | ✗ CMake is required for Linux development.
135 | It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
136 | ✗ ninja is required for Linux development.
137 | It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
138 | ✗ GTK 3.0 development libraries are required for Linux development.
139 | They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
140 | [!] Android Studio (not installed)
141 | [✓] Connected device (2 available)
142 | [✓] HTTP Host Availability
143 |  
144 | ! Doctor found issues in 3 categories.
```

Then `pub get` fails with the following error:

```
Running "flutter pub get" in -redacted-...
The current Flutter SDK version is 0.0.0-unknown.
```

Do we need to specify the specific build version we want to use in a different way, or did something break?

Thanks

**Comment by danagbemava-nc** [comment] 2022-06-01 13:44
Closing this as a duplicate of https://github.com/flutter/flutter/issues/104901.

Kindly follow up in the linked issue for updates. 

Thank you

**Closed by danagbemava-nc** 2022-06-01 13:44 UTC
Labels: in triage

**Comment by QQQ-RRR** [comment] 2022-06-02 06:42
i fixed this in Dockerfile: 
`ARG FLUTTER_CHANNEL="stable"
ARG FLUTTER_VERSION=""`
and git clone ` git clone -b ${FLUTTER_CHANNEL} --depth 1 "${FLUTTER_URL}.git" "${FLUTTER_ROOT}" ; \`
its worked for me
