### ISSUE TITLE
how to fix the problem ?

### ISSUE THREAD

**Issue by wade-liwei** [flutter/flutter#65687] opened 2020-09-12 13:21 UTC
(base) adeMacBook-Pro:mooncake a$ flutter run 
Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...                                  
                                                                
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':app:processDebugGoogleServices'.                                                       
> File google-services.json is missing. The Google Services Plugin cannot function without it.                     
   Searched Location:                                                                                              
  /Users/a/go/src/github.com/desmos-labs/mooncake/android/app/src/nullnull/google-services.json                    
  /Users/a/go/src/github.com/desmos-labs/mooncake/android/app/src/debug/google-services.json                       
  /Users/a/go/src/github.com/desmos-labs/mooncake/android/app/src/nullnullDebug/google-services.json               
  /Users/a/go/src/github.com/desmos-labs/mooncake/android/app/src/nullnull/debug/google-services.json              
  /Users/a/go/src/github.com/desmos-labs/mooncake/android/app/src/debug/nullnull/google-services.json              
  /Users/a/go/src/github.com/desmos-labs/mooncake/android/app/google-services.json                                 
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org                                                                         
                                                                                                                   
BUILD FAILED in 15m 3s                                                                                             
Running Gradle task 'assembleDebug'...                                                                             
Running Gradle task 'assembleDebug'... Done                       904.7s (!)
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Abhishek01039** [comment] 2020-09-12 15:39
Duplication of https://github.com/invertase/react-native-firebase/issues/398

**Comment by PixelToast** [comment] 2020-09-12 16:45
I suggest opening an issue in https://github.com/desmos-labs/mooncake or asking in their community how to set up a development environment for their app.

You may have to follow the steps at https://firebase.google.com/docs/flutter/setup?platform=android

Possible duplicate of #56796

**Comment by wade-liwei** [comment] 2020-09-12 16:48
@PixelToast 

thank you.

**Comment by markusaksli-nc** [comment] 2020-09-14 08:46
Closing this in favor of https://github.com/desmos-labs/mooncake/issues/152

**Closed by markusaksli-nc** 2020-09-14 08:46 UTC
