### ISSUE TITLE
[image_picker]: Support selecting images and videos at the same time, multiple videos at once

### ISSUE THREAD

**Issue by kailamjeter** [flutter/flutter#119235] opened 2023-01-26 13:44 UTC
Hi!

The current Image Picker plugin **([https://github.com/flutter/plugins/tree/main/packages/image_picker](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2Fflutter%2Fplugins%2Ftree%2Fmain%2Fpackages%2Fimage_picker))** implementation does not support

- selecting multiple videos at once 
- selecting videos and images simultaneously

I'm implementing a file library which supports both images and videos and would like to allow for the selection of both file types in the same picker window without a restriction on how many files can be selected at once.

I've seen one of these issues mentioned [here](https://github.com/flutter/flutter/issues/89159) where it looks like some progress on an implementation was made but not completed. 

Thanks!

**Comment by stuartmorgan** [comment] 2023-01-26 14:21
Closing as a duplicate of https://github.com/flutter/flutter/issues/102283 and https://github.com/flutter/flutter/issues/89159

**Closed by stuartmorgan** 2023-01-26 14:21 UTC
