### ISSUE TITLE
Allow use relative path in the plugin/package when we use git to dependence it

### ISSUE THREAD

**Issue by gsy13213009** [flutter/flutter#47324] opened 2019-12-18 10:05 UTC
## Use case
Hello. Thanks and I have a problem. Here is the use case
- Use git path to dependence a business module which is a flutter package
- It will show that when I use `flutter packages get`

```
Error on line 17, column 11: Invalid description in the "login" pubspec on the "base_lib" dependency: "../../base_lib" is a relative path, but this isn't a local pubspec.

   ╷

17 │     path: ../../base_lib

   │           ^^^^^^^^^^^^^^^

   ╵
pub get failed (65)
Process finished with exit code 6
```

## Proposal
- I hope we can allow it `rather than using git path at the pubspec.yaml in business module`(login)
- Because commit-lib is also need change. `A business module will use relative path to dependence some common-lib`. So in this case it will not convenient to integrate this business module to other repository.
- Thank you very much

**Comment by gsy13213009** [comment] 2020-01-08 03:35
- Hi @liyuqian Thanks for your attention. If we can support the relative path in a plugin/packages, We can reuse this plugin/packages in other project. And don't need create a new branch to replace all `relative path` to `git path`

**Comment by jonahwilliams** [comment] 2020-01-09 21:23
This would require a change in pub's dependency resolution, not in the flutter tool

**Comment by liyuqian** [comment] 2020-01-10 09:39
@sivachandra : shall we move this issue to the Dart repo, and how do you think about this proposal?

**Comment by a-siva** [comment] 2020-01-10 17:50
I think we should loop in the Dart pub team for their views on this.
/cc @mit-mit (could you loop in the correc folks here).

**Comment by proninyaroslav** [comment] 2021-03-07 14:53
This is a very useful option if you need to use a third party source, not pub.dev. Is there any progress on this issue?

**Comment by mit-mit** [comment] 2021-03-08 08:59
@gsy13213009 can you show the rest of the pubspec, not just the one path line? And what does the folder structure of the git repo look like?

**Comment by jonasfj** [comment] 2021-03-09 15:49
Seems similar to https://github.com/dart-lang/pub/issues/2447

**Comment by stuartmorgan** [comment] 2023-07-13 18:24
Closing as a duplicate of https://github.com/dart-lang/pub/issues/2447

**Closed by stuartmorgan** 2023-07-13 18:24 UTC
Labels: dependency: dart, c: proposal
