### ISSUE TITLE
I have installed " Desktop development with C++" installed in my visual studio but still flutter says that it is missing components

### ISSUE THREAD

**Issue by sarthak1singhal** [flutter/flutter#37844] opened 2019-08-08 05:40 UTC
Flutter (Channel master, v1.8.4-pre.127, on Microsoft Windows [Version 10.0.17134.829], locale en-US)
    • Flutter version 1.8.4-pre.127 at F:\flutter_windows_v1.5.4-hotfix.2-stable\flutter
    • Framework revision c08a3c7a0a (24 hours ago), 2019-08-06 22:38:09 -0700
    • Engine revision 4291770479
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 574c4a51c6)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.2.1)
    • Visual Studio at F:\Visual Studio
    • Visual Studio Community 2019 version 16.2.29201.188
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
      development with C++" workload, and include these components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)
        Windows 10 SDK (10.0.17763.0)

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code, 64-bit edition (version 1.19.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.17134.829]
 

![image](https://user-images.githubusercontent.com/22476073/62677782-21eb1700-b9cd-11e9-8d0e-eb55ad6e5f52.png)

**Comment by RayDexter** [comment] 2019-08-08 06:50
Same here...

**Comment by stuartmorgan** [comment] 2019-08-08 12:59
```
X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
development with C++" workload, and include these components:
MSBuild
MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)
Windows 10 SDK (10.0.17763.0)
```

The details for the workload in the sidebar are collapsed in your screenshot; are all of these components checked if you expand it?

**Comment by sarthak1singhal** [comment] 2019-08-08 13:13
> ```
> X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop
> development with C++" workload, and include these components:
> MSBuild
> MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.21)
> Windows 10 SDK (10.0.17763.0)
> ```
> 
> The details for the workload in the sidebar are collapsed in your screenshot; are all of these components checked if you expand it?

![image](https://user-images.githubusercontent.com/22476073/62706020-40243780-ba0c-11e9-972b-983806caf9ec.png)

MS Build seems to be missing. How to download it ?

**Comment by stuartmorgan** [comment] 2019-08-08 14:41
MSBuild is most likely part of the `core desktop features` entry. The problem is that you aren't installing the SDK version that the `flutter doctor` output indicates that you need to install.

Closing since this isn't a bug; the output is correct that you haven't installed all the necessary components.

**Closed by stuartmorgan** 2019-08-08 14:41 UTC
Labels: a: desktop, t: flutter doctor, tool, ❖ platform-windows

**Comment by sarthak1singhal** [comment] 2019-08-08 15:00
Can you please tell me what to install. Because I am not able to find any
solution

**Comment by stuartmorgan** [comment] 2019-08-08 15:52
As it says in the output:

> Windows 10 SDK (10.0.17763.0)

That's the exact name of the checkbox (unchecked in your screenshot) for the component, so I'm not sure how to clarify further.

**Comment by Jatin9098** [comment] 2019-09-04 11:56
As suggested by @stuartmorgan 
uncheck all the Windows 10 SDK (version). You have to keep **Windows 10 SDK (10.0.17763.0)**

This will resolve all three missing tools. 
Definitely, It works!

**Comment by AmbujaAK** [comment] 2020-09-23 20:18
Hi
I am not able to solve this issue as suggested by @stuartmorgan 
I am attaching the screenshot. Please let me know if anything required.

<img width="947" alt="vs" src="https://user-images.githubusercontent.com/22987600/94064906-f7922e00-fe07-11ea-9d61-157054481991.PNG">

**Comment by stuartmorgan** [comment] 2020-09-23 20:49
The discussion above about needing to install a specific version of the SDK is no longer relevant to current versions of Flutter.

There are many possible ways to get this `doctor` message; the specific case this issue was about is no longer one of them. Given that it's not relevant to current versions of Flutter, I'm going to lock it to prevent it from collecting unrelated issues. Anyone who believes that `flutter doctor` is behaving incorrectly in reporting that components are missing should file a new issue.
