### ISSUE TITLE
Execution failed for task ':image_gallery_saver:createFullJarDebug'

### ISSUE THREAD

**Issue by mrfoxie** [flutter/flutter#58581] opened 2020-06-03 11:22 UTC
I cant run my app and it's giving me error altho I tried to check whether the flutter is outdated or not but it's fine.
[![error][2]][2]
this is the last code I added in my app [link][3] 

    _save() async { if (Platform.isAndroid) { await _askPermission(); } var response = await Dio() .get(widget.imgUrl, options: Options(responseType: ResponseType.bytes)); final result = await ImageGallerySaver.saveImage(Uint8List.fromList(response.data)); print(result); Navigator.pop(context); } _askPermission() async { if (Platform.isIOS) { Map<PermissionGroup, PermissionStatus> permissions = await PermissionHandler() .requestPermissions([PermissionGroup.photos]); } else { PermissionStatus permission = await PermissionHandler() .checkPermissionStatus(PermissionGroup.storage); } }
for saving wallpaper in gallery in `Image_View.dart`.

  [2]: https://i.stack.imgur.com/I5Doz.png
  [3]: https://github.com/mrfoxie/wallpaper

**Comment by TahaTesser** [comment] 2020-06-03 12:09
Hi @mrfoxie 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/hui-z/image_gallery_saver/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-03 12:09 UTC
