### ISSUE TITLE
Platform view hasn't been initialized from the platform view channel.

### ISSUE THREAD

**Issue by orhan-lau** [flutter/flutter#108429] opened 2022-07-27 09:54 UTC
I have this problem too.

You need to test in the release build. It doesn't crash in the debug build.

I'm trying to rewrite the video player by replacing Texture with SurfaceView for Android.

Everything works, but when I start to quickly change the PlatformViewLink or switch to PIP, the application crashes:

**Log:** 
```
E/flutter (14136): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
E/flutter (14136): 	at h9.m.I(Unknown Source:100)
E/flutter (14136): 	at h9.m.Q(Unknown Source:3)
E/flutter (14136): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(Unknown Source:19)
E/flutter (14136): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (14136): 	at android.os.MessageQueue.next(MessageQueue.java:337)
E/flutter (14136): 	at android.os.Looper.loopOnce(Looper.java:168)
E/flutter (14136): 	at android.os.Looper.loop(Looper.java:299)
E/flutter (14136): 	at android.app.ActivityThread.main(ActivityThread.java:8103)
E/flutter (14136): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14136): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/flutter (14136): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Flutter doctor -v**
```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.2.1 21D62 darwin-x64)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Dart code**
```Dart
return PlatformViewLink(
          viewType: 'my_view_type',
          surfaceFactory: (BuildContext context, PlatformViewController controller) {
            return AndroidViewSurface(
              controller: controller as AndroidViewController,
              gestureRecognizers: const <Factory<OneSequenceGestureRecognizer>>{},
              hitTestBehavior: PlatformViewHitTestBehavior.transparent,
            );
          },
          onCreatePlatformView: (PlatformViewCreationParams params) {
            final ExpensiveAndroidViewController controller = PlatformViewsService.initExpensiveAndroidView(
              id: params.id,
              viewType: params.viewType,
              layoutDirection: TextDirection.ltr,
              creationParams: {'textureId': textureId},
              creationParamsCodec: const StandardMessageCodec(),
            );
            controller
              ..addOnPlatformViewCreatedListener(params.onPlatformViewCreated)
              ..create();

            return controller;
          },
        );
```

**Kotlin code**
```Kotlin
internal class PlayerViewFactory(private val videoPlayers: LongSparseArray<Player>) :
    PlatformViewFactory(StandardMessageCodec.INSTANCE) {
    override fun create(context: Context?, viewId: Int, args: Any?): PlatformView {
        val layout = LinearLayout(context)
        
        val creationParams = args as Map<String?, Any?>?
        val textureId = (creationParams!!["textureId"] as Int).toLong()
        val player = videoPlayers[textureId]

        val surfaceView = player.surfaceView()

        if (surfaceView.parent != null) {
            (surfaceView.parent as ViewGroup).removeView(surfaceView)
        }

        layout.addView(surfaceView)

        return NativeView(layout)
    }
}

internal class NativeView(private val view: View) :
    PlatformView {
    override fun getView(): View {
        return view
    }

    override fun dispose() {
    }
}
```

**You can test code**
```Kotlin
internal class PlayerViewFactory(private val videoPlayers: LongSparseArray<Player>) :
    PlatformViewFactory(StandardMessageCodec.INSTANCE) {
    override fun create(context: Context?, viewId: Int, args: Any?): PlatformView {
        val layout = LinearLayout(context)
        
        val view = View(context)
        view.setBackgroundColor(Color.GREEN)
        layout.addView(view)

        return NativeView(layout)
    }
}

internal class NativeView(private val view: View) :
    PlatformView {
    override fun getView(): View {
        return view
    }

    override fun dispose() {
    }
}
```

_Originally posted by @FlutterSu in https://github.com/flutter/flutter/issues/104797#issuecomment-1166486203_

**Comment by danagbemava-nc** [comment] 2022-07-27 13:17
Hi @orhan-lau, the code sample provided is not complete. 

Please provide a complete minimal reproducible code sample, preferably in a repo that we can clone so that we can further investigate this. 

Thank you

**Comment by orhan-lau** [comment] 2022-07-28 06:29
dart code
```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: TestPage(),
    );
  }
}

/// Test Page
class TestPage extends StatefulWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    final isLandscape =
        MediaQuery.of(context).orientation == Orientation.landscape;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Plugin example app'),
        actions: [
          // When i click this button about five times, i got a error：Platform view hasn't been initialized from the platform view channel.
          IconButton(
            tooltip: "full screen platform view",
            onPressed: () async {
              final isLandscape =
                  MediaQuery.of(context).orientation == Orientation.landscape;
              if (isLandscape) {
                await SystemChrome.setPreferredOrientations([
                  DeviceOrientation.portraitUp,
                  DeviceOrientation.portraitDown
                ]);
              } else {
                await SystemChrome.setPreferredOrientations([
                  DeviceOrientation.landscapeLeft,
                  DeviceOrientation.landscapeRight
                ]);
              }
            },
            icon: const Icon(Icons.fullscreen),
          )
        ],
      ),
      body: isLandscape
          ? androidHybridView()
          : Column(
              children: [
                AspectRatio(
                  aspectRatio: 16 / 9,
                  child: androidHybridView(),
                ),
                Expanded(
                  child: DefaultTabController(
                    length: 3,
                    child: Column(
                      children: [
                        TabBar(
                          labelColor: Colors.black,
                          tabs: List.generate(
                            3,
                            (index) => Tab(
                              text: 'tab${index + 1}',
                            ),
                          ),
                        ),
                        const Expanded(
                          child: TabBarView(
                            children: [
                              Center(child: Text('Page 1')),
                              Center(child: Text('Page 2')),
                              Center(child: Text('Page 3')),
                            ],
                          ),
                        )
                      ],
                    ),
                  ),
                )
              ],
            ),
    );
  }

  /// suck as a surface-video-player
  Widget androidHybridView() {
    return PlatformViewLink(
      viewType: 'Test/surface_view_platform',
      surfaceFactory:
          (BuildContext context, PlatformViewController controller) {
        return AndroidViewSurface(
          controller: controller as AndroidViewController,
          gestureRecognizers: const {},
          hitTestBehavior: PlatformViewHitTestBehavior.opaque,
        );
      },
      onCreatePlatformView: (PlatformViewCreationParams params) {
        return PlatformViewsService.initExpensiveAndroidView(
          id: params.id,
          viewType: params.viewType,
          layoutDirection: TextDirection.ltr,
          creationParamsCodec: const StandardMessageCodec(),
        )
          ..addOnPlatformViewCreatedListener(params.onPlatformViewCreated)
          ..create();
      },
    );
  }
}

```

**Comment by orhan-lau** [comment] 2022-07-28 06:30
java code
```java
package com.example.surface_view_platform;


import androidx.annotation.NonNull;


import io.flutter.embedding.engine.plugins.FlutterPlugin;

import io.flutter.plugin.platform.PlatformViewRegistry;

/**
 * SurfaceViewPlatformPlugin
 */
public class SurfaceViewPlatformPlugin implements FlutterPlugin {


    @Override
    public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
        final PlatformViewRegistry registry = flutterPluginBinding.getPlatformViewRegistry();
        registry.registerViewFactory("Test/surface_view_platform", new TestSurfaceViewFactory());
    }

    @Override
    public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
    }
}
```

**Comment by orhan-lau** [comment] 2022-07-28 06:30
```java
package com.example.surface_view_platform;

import android.content.Context;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.util.Map;

import io.flutter.plugin.common.StandardMessageCodec;
import io.flutter.plugin.platform.PlatformView;
import io.flutter.plugin.platform.PlatformViewFactory;

public class TestSurfaceViewFactory extends PlatformViewFactory {
    public TestSurfaceViewFactory() {
        super(StandardMessageCodec.INSTANCE);
    }

    @NonNull
    @Override
    public PlatformView create(@NonNull Context context, int id, @Nullable Object args) {
        final Map<String, Object> creationParams = (Map<String, Object>) args;
        return new TestSurfaceView(context, id, creationParams);
    }
}
```

**Comment by orhan-lau** [comment] 2022-07-28 06:30
```java
package com.example.surface_view_platform;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.PixelFormat;
import android.graphics.PorterDuff;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.View;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.util.Map;

import io.flutter.plugin.platform.PlatformView;

public class TestSurfaceView extends SurfaceView implements PlatformView {


    TestSurfaceView(Context context, int id, Map<String, Object> creationParams) {
        super(context);
        initView();
    }

    @Nullable
    @Override
    public View getView() {
        return this;
    }

    @Override
    public void dispose() {

    }

    private SurfaceHolder mSurfaceHolder;
    private Canvas mCanvas;
    private Paint paint;


    private void initView() {
        paint = new Paint();
        paint.setColor(Color.RED);
        paint.setStrokeWidth(10);
        paint.setStyle(Paint.Style.STROKE);
        this.mSurfaceHolder = getHolder();
        this.mSurfaceHolder.addCallback(new SurfaceHolder.Callback() {
            @Override
            public void surfaceCreated(@NonNull SurfaceHolder holder) {
                new Thread(() -> {
                    mCanvas = mSurfaceHolder.lockCanvas();
                    if (null != mCanvas) {
                        mCanvas.drawColor(Color.TRANSPARENT, PorterDuff.Mode.CLEAR);
                        mCanvas.drawCircle(200, 200, 200, paint);
                        mSurfaceHolder.unlockCanvasAndPost(mCanvas);
                    }
                }).start();
            }

            @Override
            public void surfaceChanged(@NonNull SurfaceHolder holder, int format, int width, int height) {

            }

            @Override
            public void surfaceDestroyed(@NonNull SurfaceHolder holder) {

            }
        });
        this.setZOrderOnTop(true);
        this.mSurfaceHolder.setFormat(PixelFormat.TRANSLUCENT);
    }


}

```

**Comment by orhan-lau** [comment] 2022-07-28 06:35
> Hi @orhan-lau, the code sample provided is not complete.
> 
> Please provide a complete minimal reproducible code sample, preferably in a repo that we can clone so that we can further investigate this.
> 
> Thank you

Hi! Everything works, but when I start to full-screen platform-view, the application crashes, (tips: I click the fullscreen-IconButton)
sorry for my shit code:)

**Comment by danagbemava-nc** [comment] 2022-07-28 07:34
Hi @orhan-lau, can you put the code together into repo that we can clone and run? 

That'll make it easier/faster for us to investigate the issue. 

Thank you

**Comment by orhan-lau** [comment] 2022-07-29 02:11
> crashes

Hi! @danagbemava-nc ,Of course! You can clone [https://github.com/orhan-lau/surface_view_platform_demo.git](https://github.com/orhan-lau/surface_view_platform_demo.git)

and my **flutter doctor -v** is：
```
[√] Flutter (Channel unknown, 3.0.5, on Microsoft Windows [版本 10.0.19044.1826], locale zh-CN)
    • Flutter version 3.0.5 at xxx
    • Upstream repository unknown
    • Framework revision f1875d570e (2 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at xxx
    • Platform android-33, build-tools 31.0.0
    • Java binary at: xxx
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at xxx

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at xxx
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at xxx
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (4 available)
    • M2012K10C (mobile) • aueqzpswnb7pvknn • android-arm64  • Android 12 (API 31)
    • Windows (desktop)  • windows          • windows-x64    • Microsoft Windows [版本 10.0.19044.1826]
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 103.0.5060.134
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 103.0.1264.49

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by orhan-lau** [comment] 2022-07-29 02:12
> Hi @orhan-lau, can you put the code together into repo that we can clone and run?
> 
> That'll make it easier/faster for us to investigate the issue.
> 
> Thank you

**Comment by danagbemava-nc** [comment] 2022-07-29 07:51
Hi @orhan-lau, can you check on the `master` channel if it is reproducible for you and what device it reproduces on? 
I was able to reproduce it on the `stable` channel after about 10 rotations, however, on the master channel, I cannot seem to reproduce it after about 30 rotations.

**Comment by orhan-lau** [comment] 2022-07-30 06:24
> Hi @orhan-lau, can you check on the `master` channel if it is reproducible for you and what device it reproduces on? I was able to reproduce it on the `stable` channel after about 10 rotations, however, on the master channel, I cannot seem to reproduce it after about 30 rotations.

Hi @danagbemava-nc  I just tryed ，Me too, On the **master** channel, I cannot seem to reproduce it, By the way, I hope build my app with **stable** channel , What should i do?
My **flutter doctor -v is：**
```
[√] Flutter version 3.1.0-0.0.pre.1994 on channel master at D:\fvm_home\current
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 713c4fa9b0 (2 hours ago), 2022-07-29 22:26:06 -0400
    • Engine revision 19ad02a9ea
    • Dart version 2.19.0 (build 2.19.0-46.0.dev)
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\my_android_sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: D:\my_as\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.
```

**Comment by danagbemava-nc** [comment] 2022-08-01 06:28
Hi @orhan-lau, if you cannot reproduce this on the master channel, it likely means that the issue has been fixed. 

> By the way, I want to build my app with the stable channel, What should I do?

You can test this out on the `beta` channel to see if the issue is reproducible or not and take it from there since the beta channel is what will eventually become the next stable version. 

The other thing is for you to wait till the changes on master become stable. 

Since this is not reproducible for either of us on the `master` channel, I'm going to have to close this issue per our triage policy. 

If you are able to reproduce it on the master branch or later, kindly leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2022-08-01 06:28 UTC
Labels: in triage

**Comment by 000panther** [comment] 2022-08-01 13:06
I had this issue too with a webview and changing to the beta channel solved it for me. Hope the changes will reach stable soon!
