### ISSUE TITLE
Flutter linux - TextField.onChanged not getting called

### ISSUE THREAD

**Issue by BobEvans** [flutter/flutter#63712] opened 2020-08-13 21:57 UTC
Running on Linux, create an app with a TextField providing the onChanged handler.

```
TextField(
      keyboardType: TextInputType.multiline,
      maxLength: 500,
      maxLines: null,
      onChanged: (text) {
        _event.responses[input.name] = text;
      },
    );
```

Run with Flutter run.

Notice that the textEdit does not show any text, the cursor does not move and the onChanged handler never gets called.

This is running debiand 5.6.14.1rodete2 with xfce.
```
$ flutter doctor -v
[✓] Flutter (Channel master, 1.20.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0 at /usr/local/google/home/bobevans/git/flutter
    • Framework revision eaf9ff738a (7 weeks ago), 2020-06-22 11:53:54 -0700
    • Engine revision 676cd566f7
    • Dart version 2.9.0 (build 2.9.0-17.0.dev 7e72c9ae7e)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/google/home/bobevans/Android/Sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at:
      /usr/local/google/home/bobevans/applications/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 9.0.1-12
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[!] Android Studio (version 3.1)
    • Android Studio at
      /usr/local/google/home/bobevans/applications/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at
      /usr/local/google/home/bobevans/applications/idea-IC-181.4445.78
    • Flutter plugin version 23.2.3
    • Dart plugin version 181.4445.29

[✓] Connected device (1 available)
    • Linux desktop • linux • linux-x64 • Linux

! Doctor found issues in 1 category.
```

**Comment by BobEvans** [comment] 2020-08-14 04:24
Also tested on Cinnamon window manager just in case. Same problem.

**Comment by TahaTesser** [comment] 2020-08-14 13:40
Hi @BobEvans 
Looks like you've 7 weeks old `master`, there is no issue with onChange on latest `master`


<details> 
<summary>main.dart</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: TextField(
            keyboardType: TextInputType.multiline,
            maxLength: 500,
            maxLines: null,
            onChanged: (value) {
              print(value);
            },
          ),
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.95, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-10.0.pre.95 at /home/taha/Code/flutter
    • Framework revision 48b9c3d39b (7 hours ago), 2020-08-14 00:04:33 -0700
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 1 category.
```

</details> 

I cannot reproduce this issue on latest master channel.
Can you upgrade to master and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by TahaTesser** [comment] 2020-09-04 13:28
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-09-04 13:28 UTC
Labels: in triage
