### ISSUE TITLE
rendering problems with web-renderer html on safari browser

### ISSUE THREAD

**Issue by cksoft0807** [flutter/flutter#94998] opened 2021-12-10 09:27 UTC
Because the display using canvaskit and the Safari browser is completely broken, i use the web-renderer html. Various problems arise here in Flutter version 2.8 as well. Example:

**Steps to Reproduce**
- Create Form
- Insert multiple form fields with icon decorations
- move cursor over form fields or scroll

**Result:**
The icons flicker and swap their representation. No error with other browser, no error if i remove the form tag. 

There are various other problems, such as a slow start or e.g. changing text styles on complete page when the cursor is over InkWell area.

Code:
```dart
Scaffold(
        body: Form(
      child: Column(
        children: [
          TextFormField(
            onSaved: (value) {},
            initialValue: '',
            keyboardType: TextInputType.number,
            decoration: const InputDecoration(
              labelText: "Test 1",
              icon: Icon(Icons.person),
            ),
          ),
          TextFormField(
            onSaved: (value) {},
            initialValue: '',
            keyboardType: TextInputType.number,
            decoration: const InputDecoration(
              labelText: "Test 2",
              icon: Icon(Icons.access_alarm),
            ),
          ),
```

**Comment by maheshmnj** [comment] 2021-12-10 10:58
Hi @cksoft0807, Thanks for filing the issue. I am able to reproduce a flicker issue when scrolling or tapping on textfields. Is this the same issue you are referring to?

_Reproducible using canvaskit not with html renderer_

https://user-images.githubusercontent.com/31410839/145562944-806c7c66-40b7-4f7f-ac38-792b70f3fd40.mov

 <details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.6:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
```
</details>

 <details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class CounterModel extends InheritedNotifier<ValueNotifier<int>> {
  const CounterModel(
      {Key? key, ValueNotifier<int>? notifier, required Widget child})
      : super(key: key, notifier: notifier, child: child);

  static int of(BuildContext context) {
    return context
        .dependOnInheritedWidgetOfExactType<CounterModel>()!
        .notifier!
        .value;
  }
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Form(
            child: ListView(children: [
      for (int i = 0; i < 20; i++)
        TextFormField(
          onSaved: (value) {},
          initialValue: '',
          keyboardType: TextInputType.number,
          decoration: const InputDecoration(
            labelText: "Test 1",
            icon: Icon(Icons.person),
          ),
        ),
    ])));
  }
}

```
</details>

**Comment by cksoft0807** [comment] 2021-12-10 11:30
With canvaskit i have similar errors and many more in connection with safari.

With html renderer only the icons flicker and if different icons are set, they change position.

see video. i just move the cursor or change the window size

https://user-images.githubusercontent.com/59683964/145566808-e0391cf1-2904-45cd-bc05-fc901fa5d4f7.mov

**Comment by maheshmnj** [comment] 2021-12-10 12:46
@cksoft0807 Can you please share your `flutter doctor -v` I believe this issue might be related to https://github.com/flutter/flutter/issues/92495

Thanks

**Comment by cksoft0807** [comment] 2021-12-12 21:24
#92495 is about web-renderer canvaskit and safari (i have the simmilar display errors here). My issue is about web-rederer html and safari. So in the end we always have problems with Safari (on M1?).

flutter doctor -v:
✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale de-DE)
    • Flutter version 2.8.0 at /Users/carstenkunsken/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/carstenkunsken/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.93

• No issues found!

**Comment by maheshmnj** [comment] 2021-12-13 04:50
@cksoft0807 I ran the below code sample (with different icons) with web renderer html in debug mode on stable 2.8.0 but could not reproduce the issue. 

https://user-images.githubusercontent.com/31410839/145753862-d6beb262-1228-4ebc-89d2-129249f02a53.mov



<details>
<summary>code sample</summary>


```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    List<IconData> _icons = [
      Icons.ac_unit_outlined,
      Icons.people_outlined,
      Icons.contacts,
      Icons.time_to_leave,
      Icons.maps_home_work,
      Icons.safety_divider,
      Icons.label,
      Icons.label_rounded,
      Icons.ac_unit,
      Icons.ac_unit_outlined
    ];
    return Scaffold(
        body: Form(
            child: ListView(children: [
      for (int i = 0; i < _icons.length; i++)
        TextFormField(
          onSaved: (value) {},
          initialValue: '',
          keyboardType: TextInputType.number,
          decoration: InputDecoration(
            labelText: "Test 1",
            icon: Icon(_icons[i]),
          ),
        ),
    ])));
  }
}

```
</details>


<details>
<summary>flutter doctor -v</summary>

```
✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      96.0.4664.93

• No issues found!
```
</details>

Can you please verify if the issue reproduces with my code sample, if it doesn't then I would advise you to please share your complete code sample? 

Thanks

**Comment by maheshmnj** [comment] 2021-12-13 04:51
@cksoft0807 I ran the below code sample (with different icons) with web renderer html in debug mode on stable 2.8.0 but could not reproduce the issue. 

https://user-images.githubusercontent.com/31410839/145753862-d6beb262-1228-4ebc-89d2-129249f02a53.mov



<details>
<summary>code sample</summary>


```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    List<IconData> _icons = [
      Icons.ac_unit_outlined,
      Icons.people_outlined,
      Icons.contacts,
      Icons.time_to_leave,
      Icons.maps_home_work,
      Icons.safety_divider,
      Icons.label,
      Icons.label_rounded,
      Icons.ac_unit,
      Icons.ac_unit_outlined
    ];
    return Scaffold(
        body: Form(
            child: ListView(children: [
      for (int i = 0; i < _icons.length; i++)
        TextFormField(
          onSaved: (value) {},
          initialValue: '',
          keyboardType: TextInputType.number,
          decoration: InputDecoration(
            labelText: "Test 1",
            icon: Icon(_icons[i]),
          ),
        ),
    ])));
  }
}

```
</details>


<details>
<summary>flutter doctor -v</summary>

```
✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      96.0.4664.93

• No issues found!
```
</details>

Can you please verify if the issue reproduces with my code sample, if it doesn't then I would advise you to please share your complete code sample.

Thanks

**Comment by cksoft0807** [comment] 2021-12-13 09:06
Your code runs fine. In my case i used column, not listview. Changed listview->column in your code i have my error back.

I found another small bug here. Place InkWell in column, bold text in other column. On hoover the InkWell any other text loose his bold style. Error is again only with column, not using listview and only with safari.

**Comment by maheshmnj** [comment] 2021-12-13 11:35
>  In my case i used column, not listview. Changed listview->column in your code i have my error back.

Thanks for the info @cksoft0807, changing Listview to Column I was able to reproduce the issue on `stable 2.8.0`. But on the latest master channel, the issue was not reproduced, So this seems to be fixed on the master channel.


https://user-images.githubusercontent.com/31410839/145804784-efe079be-48e0-4149-ae22-ad455117f525.mov


So until this lands to stable in the upcoming release you may switch to master channel by running 

```
flutter channel master
flutter upgrade
```  

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (5 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.1002, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.1002 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9de8849905 (10 hours ago), 2021-12-12 20:54:15 -0500
    • Engine revision f16c96c31f
    • Dart version 2.16.0 (build 2.16.0-85.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559
      darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome
      96.0.4664.93

• No issues found!
```
</details>


@yjbanov can this be cherry-picked to the stable channel?
cc: @stuartmorgan 

Closing as fixed on the master channel.

**Closed by maheshmnj** 2021-12-13 11:35 UTC
Labels: in triage
