### ISSUE TITLE
[linux] Flutter on linux has some graphical bug on certain device with GPU

### ISSUE THREAD

**Issue by ferraridamiano** [flutter/flutter#64464] opened 2020-08-24 15:10 UTC
I recently gived flutter for linux a try. I created the default flutter project and launched it. I noticed that it is pretty buggy on the right side of the window. With the following gif you can see what I mean.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34270884/91059519-214e0e80-e62a-11ea-89d0-ca1825d15700.gif)

I thought it was normal (it's alfa), but I saw some videos which all worked good. I tried to install flutter gallery from the snap store and it works as aspected. Flutter doctor tell me that everything is ok. What's wrong?
(I'm on kubuntu 20.04)

<details>
  <summary>Flutter doctor -v</summary>

```

[✓] Flutter (Channel dev, 1.22.0-1.0.pre, on Linux, locale it_IT.UTF-8)
    • Flutter version 1.22.0-1.0.pre at /home/damiano/flutter
    • Framework revision ce40de69b7 (4 giorni fa), 2020-08-20 07:31:50 -0700
    • Engine revision 81027ab0cc
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/damiano/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/damiano/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.6)
    • Android Studio at /home/damiano/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.0

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!

```

</details>

**UPDATE 25/08/2020**
If I launch the app in release mode the app is way less glitchy. The only graphical bug is during the in/out animation of the tooltip of the FAB.

**Comment by TahaTesser** [comment] 2020-08-25 09:17
Hi @ferraridamiano 
Just tried to reproduce it on the latest `master`  running on Popos 20.04, no graphical bugs

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.59, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.0-2.0.pre.59 at /home/taha/Code/flutter
    • Framework revision be7c7faee6 (7 hours ago), 2020-08-24 22:31:02 -0400
    • Engine revision 8107b36c7b
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at //home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = //home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

• No issues found!
```

</details> 

Can you upgrade to latest `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by ferraridamiano** [comment] 2020-08-25 09:48
<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.59, on Linux, locale it_IT.UTF-8)
    • Flutter version 1.22.0-2.0.pre.59 at /home/damiano/flutter
    • Framework revision be7c7faee6 (7 ore fa), 2020-08-24 22:31:02 -0400
    • Engine revision 8107b36c7b
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/damiano/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/damiano/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.6)
    • Android Studio at /home/damiano/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.0

[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!

```
</details>

<details>
  <summary>flutter run --verbose</summary>

```
[  +97 ms] executing: [/home/damiano/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +27 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] be7c7faee6cb8bcabd3fefbbe8107c5b772ef9c3
[        ] executing: [/home/damiano/flutter/] git tag --points-at HEAD
[  +11 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [/home/damiano/flutter/] git describe --match *.*.* --first-parent --long --tags
[  +22 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.22.0-1.0.pre-59-gbe7c7faee6
[   +7 ms] executing: [/home/damiano/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/damiano/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +33 ms] executing: [/home/damiano/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +34 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] executing: /home/damiano/Android/Sdk/platform-tools/adb devices -l
[  +31 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +51 ms] Multiple devices found:
[  +37 ms] Linux (desktop)  • linux      • linux-x64      • Linux
[        ] Web Server (web) • web-server • web-javascript • Flutter Tools
[        ] Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135
[   +1 ms] [0]: Linux (linux)
[        ] [1]: Web Server (web-server)
[        ] [2]: Chrome (chrome)
[   +1 ms] Please choose one:
[        ]  [0|1|2]
[        ] : 
[+3722 ms] 0
[ +117 ms] Generating
/home/damiano/Scrivania/prova/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.ja
va
[  +65 ms] Starting incremental build...
[   +1 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +5 ms] complete
[   +2 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/damiano/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/damiano/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/damiano/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental
--target=flutter --debugger-module-names --experimental-emit-debug-metadata
-Ddart.developer.causal_async_stacks=true --output-dill
/tmp/flutter_tools.ESGWLL/flutter_tool.GTPZZT/app.dill --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unre
achable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +10 ms] Building Linux application...
[  +11 ms] <- compile package:prova/main.dart
[   +2 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
/home/damiano/Scrivania/prova/linux
[  +35 ms] -- Configuring done
[   +3 ms] -- Generating done
[        ] -- Build files have been written to: /home/damiano/Scrivania/prova/build/linux/debug
[   +3 ms] executing: ninja -C build/linux/debug install
[   +6 ms] ninja: Entering directory `build/linux/debug'
[+4548 ms] [1/5] Generating
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/damiano/Scrivania/prova/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[   +3 ms] [ +103 ms] executing: [/home/damiano/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] be7c7faee6cb8bcabd3fefbbe8107c5b772ef9c3
[        ] [        ] executing: [/home/damiano/flutter/] git tag --points-at HEAD
[        ] [  +18 ms] Exit code 0 from: git tag --points-at HEAD
[        ] [   +1 ms] executing: [/home/damiano/flutter/] git describe --match *.*.* --first-parent
--long --tags
[        ] [  +22 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] [        ] 1.22.0-1.0.pre-59-gbe7c7faee6
[        ] [   +7 ms] executing: [/home/damiano/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/damiano/flutter/] git ls-remote --get-url origin
[        ] [   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +40 ms] executing: [/home/damiano/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] [   +5 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [  +77 ms] Initializing file store
[        ] [   +7 ms] Done initializing file store
[        ] [  +27 ms] Skipping target: gen_localizations
[        ] [+1402 ms] Skipping target: kernel_snapshot
[        ] [+1775 ms] Skipping target: unpack_linux
[        ] [ +348 ms] Skipping target: debug_bundle_linux_assets
[        ] [        ] Persisting file store
[        ] [   +8 ms] Done persisting file store
[        ] [   +5 ms] build succeeded.
[        ] [   +6 ms] "flutter assemble" took 3.679ms.
[        ] [ +189 ms] ensureAnalyticsSent: 186ms
[        ] [   +3 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 0
[ +474 ms] [2/5] Building CXX object CMakeFiles/prova.dir/flutter/generated_plugin_registrant.cc.o
[   +9 ms] [3/5] Building CXX object CMakeFiles/prova.dir/my_application.cc.o
[ +138 ms] [4/5] Linking CXX executable prova
[        ] [4/5] Install the project...
[   +7 ms] -- Install configuration: "Debug"
[  +15 ms] -- Installing: /home/damiano/Scrivania/prova/build/linux/debug/bundle/prova
[        ] -- Set runtime path of "/home/damiano/Scrivania/prova/build/linux/debug/bundle/prova" to
"$ORIGIN/lib"
[        ] -- Installing: /home/damiano/Scrivania/prova/build/linux/debug/bundle/data/icudtl.dat
[        ] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/lib/libflutter_linux_gtk.so
[ +113 ms] -- Installing: /home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets
[        ] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets/kernel_blob.bin
[  +29 ms] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets/NOTICES
[        ] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets/packages
[        ] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons
[        ] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/ass
ets
[        ] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets/packages/cupertino_icons/ass
ets/CupertinoIcons.ttf
[        ] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets/FontManifest.json
[        ] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets/AssetManifest.json
[        ] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets/fonts
[        ] -- Installing:
/home/damiano/Scrivania/prova/build/linux/debug/bundle/data/flutter_assets/fonts/MaterialIcons-Regular.
otf
[  +10 ms] Building Linux application... (completed in 5,4s)
[ +699 ms] Observatory URL on device: http://127.0.0.1:33733/ME9PdqcSWJU=/
[   +2 ms] Caching compiled dill
[  +55 ms] Connecting to service protocol: http://127.0.0.1:33733/ME9PdqcSWJU=/
[        ] DDS is currently disabled due to https://github.com/flutter/flutter/issues/62507
[  +94 ms] Successfully connected to service protocol: http://127.0.0.1:33733/ME9PdqcSWJU=/
[        ] Waiting for Linux to report its views...
[   +3 ms] Waiting for Linux to report its views... (completed in 2ms)
[   +6 ms] DevFS: Creating new filesystem on the device (null)
[  +10 ms] DevFS: Created new filesystem on the device (file:///tmp/provaCBCTPI/prova/)
[   +1 ms] Updating assets
[  +71 ms] Syncing files to device Linux...
[   +1 ms] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:prova/main.dart 1e3a50e8-521c-42d5-9a34-16d79005c952
[        ] <- 1e3a50e8-521c-42d5-9a34-16d79005c952
[  +90 ms] Updating files
[  +59 ms] DevFS: Sync finished
[        ] Syncing files to device Linux... (completed in 154ms)
[        ] Synced 1.7MB.
[        ] <- accept
[   +1 ms] Connected to _flutterView/0xc86a80.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Linux is available at:
http://127.0.0.1:33733/ME9PdqcSWJU=/
[+25943 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +4 ms] DevFS: Deleting filesystem on the device (file:///tmp/provaCBCTPI/prova/)
[ +256 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not
completed
[   +6 ms] "flutter run" took 36.847ms.
[ +204 ms] ensureAnalyticsSent: 193ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +8 ms] Shutdown hooks complete
[        ] exiting with code 0

```
</details>

I tried to reproduce this bug on my notebook with the same OS and all works good. My notebook has an integrated GPU and my dektop pc (where there is the bug) has a dedicated GPU. I don't know if this info can help.

**Comment by TahaTesser** [comment] 2020-08-25 11:23
I’m unable to reproduce the issue to pinpoint the cause. The issue needs further investigation.

**Comment by iskakaushik** [comment] 2020-09-11 16:13
This is a duplicate of https://github.com/flutter/flutter/issues/44136 if this happens only during resize.

**Closed by iskakaushik** 2020-09-11 16:13 UTC
Labels: P4, a: desktop, e: device-specific, engine, platform-linux, severe: rendering
