### ISSUE TITLE
[tool_crash] SocketException: The remote computer refused the network connection., OS Error: The remote computer refused the network connection., errno = 1225

### ISSUE THREAD

**Issue by Bindas69** [flutter/flutter#153590] opened 2024-08-16 19:58 UTC
## Command
```sh
flutter run --machine --start-paused -d edge --devtools-server-address http://127.0.0.1:9100/ --target C:\Users\laptop center\OneDrive\Desktop\development\practise\lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: The remote computer refused the network connection.
, OS Error: The remote computer refused the network connection.
, errno = 1225
```console
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1920:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2144:22)
#4      Socket.startConnect (dart:io/socket.dart:825:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2491:20)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2930:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2935:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2790:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2632:48)
#10     ChromeConnection.getUrl (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:108:33)
#11     ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:53:26)
#12     ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:90:31)
#13     Chromium.close (package:flutter_tools/src/web/chrome.dart:510:53)
#14     ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:164:20)
#15     ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:203:27)
<asynchronous suspension>
#16     ResidentWebRunner.cleanupAtFinish (package:flutter_tools/src/isolated/resident_web_runner.dart:191:5)
<asynchronous suspension>
#17     ResidentRunner.waitForAppToFinish (package:flutter_tools/src/resident_runner.dart:1482:5)
<asynchronous suspension>
#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:788:26)
<asynchronous suspension>
#19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4037], locale en-PK)
    • Flutter version 3.24.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\laptop center\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.11.35208.52
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at C:\Users\laptop center\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4037]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.98

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 80c2e84975bbd28ecf5f8d4bd4ca5a2490bfc819

**Comment by mqhamdam** [comment] 2024-08-19 01:50
This is known issue please follow here:
#152953

**Comment by huycozy** [comment] 2024-08-19 07:45
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153064. This has been fixed on Flutter master channel so you can try switching to master channel and retry.

**Closed by huycozy** 2024-08-19 07:45 UTC
Labels: in triage
