### ISSUE TITLE
[WebView]Trying to use platform views with API 19, required API level is: 20

### ISSUE THREAD

**Issue by puzhengwu** [flutter/flutter#85755] opened 2021-07-02 06:59 UTC
java.lang.IllegalStateException: Trying to use platform views with API 19, required API level is: 20
	at io.flutter.plugin.platform.PlatformViewsController$1.ensureValidAndroidVersion(PlatformViewsController.java:347)
	at io.flutter.plugin.platform.PlatformViewsController$1.onTouch(PlatformViewsController.java:301)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.touch(PlatformViewsChannel.java:173)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:68)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:140)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by stuartmorgan** [comment] 2021-07-02 10:13
Duplicate of https://github.com/flutter/flutter/issues/85215#issuecomment-872791541

**Closed by stuartmorgan** 2021-07-02 10:13 UTC

**Comment by puzhengwu** [comment] 2021-07-02 11:02
在android4.4（19）系统上，webview可以加载页面，但是无法响应任何手势操作，此手机原生应用的webview是可以正常使用的，也可以使用jsbridge

**Comment by puzhengwu** [comment] 2021-07-02 11:02
On Android 4.4 (19) system, WebView can load the page, but can not respond to any gesture operation, the mobile native WebView can be used normally, can also use JSBridge
