### ISSUE TITLE
[firebase_crashlytics]  The default Firebase app has not yet been configured.

### ISSUE THREAD

**Issue by miguelpruivo** [flutter/flutter#44615] opened 2019-11-11 21:47 UTC
## Steps to Reproduce

Follow the instructions from [firebase_crashlytics](https://pub.dev/packages/firebase_crashlytics#-readme-tab-) to set up Crashlytics in your app.

**Target Platform:** iOS
**Devices:** All

## Logs
As soon as the app starts, it gives the following:
```
 Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
```
along with
```
[Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize
```

Despite that, the plugin itself seems to be working, at least I can see the Crashlytics up and running on the Firebase console. However, I can't get rid of those errors and somehow it looks like it's expecting `firebase_core` to call `config` when the Crashlytics itself doesn't require it (unless I'm wrong and if so, the docs are missing it).

On Android it seems to be ok.

## Flutter doctor
```
 Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale
    pt-PT)
    • Flutter version 1.9.1+hotfix.6 at /Users/miguelruivo/devtools/flutter
    • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
```

**Comment by iapicca** [comment] 2019-11-12 12:03
Hi @miguelpruivo 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-12 12:03 UTC
