### ISSUE TITLE
Flutter tool does not support Android host

### ISSUE THREAD

**Issue by NatoBoram** [flutter/flutter#35933] opened 2019-07-10 22:35 UTC
## Steps to Reproduce

1. `git clone` Flutter
2. Add `flutter/bin` to `$PATH`
3. `flutter doctor`

## Logs

```
Building flutter tool...
/data/data/com.termux/files/home/Applications/flutter/bin/cache/dart-sdk/bin/pub: line 49: /data/data/com.termux/files/home/Applications/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error
/data/data/com.termux/files/home/Applications/flutter/bin/cache/dart-sdk/bin/pub: line 49: /data/data/com.termux/files/home/Applications/flutter/bin/cache/dart-sdk/bin/dart: Success
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

```
Building flutter tool...
/data/data/com.termux/files/home/Applications/flutter/bin/cache/dart-sdk/bin/pub: line 49: /data/data/com.termux/files/home/Applications/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error
/data/data/com.termux/files/home/Applications/flutter/bin/cache/dart-sdk/bin/pub: line 49: /data/data/com.termux/files/home/Applications/flutter/bin/cache/dart-sdk/bin/dart: Success
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

```yaml
OS: Android 10 aarch64
Host: google Pixel 3
Kernel: 4.9.165-g766ebbc83605-ab5543004
Uptime: secs
Packages: 56 (dpkg), 1 (pkg)
Shell: bash 5.0.7
CPU: Qualcomm SDM845 (8) @ 1.766GHz
Memory: 2561MiB / 3546MiB
```

**Comment by NatoBoram** [comment] 2019-07-21 02:18
I figured out it was maybe because Flutter didn't download the correct Dart build for my device, so I've tried to install Dart from the package manager then copying it to Flutter's `dart-sdk` directory. 

The result is now that the `flutter` command crashes my device when it's trying to build the flutter tool.

**Comment by bus710** [comment] 2019-08-16 17:04
Just wonder if this would be good with an android-x86 and termux combination.

**Comment by BondarenkoStas** [comment] 2019-09-29 19:59
@NatoBoram Can the issue be closed?

**Comment by NatoBoram** [comment] 2019-09-30 00:35
Nope, there's still the problem of Flutter not downloading the correct Dart SDK for ARM.

Then there's a bug where Dart crashes when building Flutter with not enough memory, but that can probably be raised somewhere else.

**Comment by jonahwilliams** [comment] 2019-09-30 00:45
We currently only support development on Windows, macOS, and Linux host machines. I'd imagine that beyond getting the correct distribution of the Dart SDK downloaded, there will be other issues with tool dependencies that aren't supported, such as the prebuilt host artifacts. That's not to say it would be impossible, but more investigation would be needed.

**Comment by allansrc** [comment] 2020-01-26 07:55
Currently I am working to research possible crashes on Android host. But nothing yet. 

Please share if you test something else to run. Thanks

**Comment by NatoBoram** [comment] 2020-01-26 11:55
I've updated and cleaned my Flutter installation on Termux, but the error is still the same : 

> cannot execute binary file: Exec format error

If I copy the package manager's `dart-sdk` to the cache : 

```bash
cp /data/data/com.termux/files/usr/lib/dart-sdk ~/Applications/flutter/bin/cache/
```

… It didn't crash!

**Comment by jonahwilliams** [comment] 2020-01-26 22:31
Not android specific, we do not currently provide host binaries for arm64 hosts.

Duplicate of https://github.com/flutter/flutter/issues/45216

**Closed by jonahwilliams** 2020-01-26 22:31 UTC
Labels: severe: new feature, tool

**Comment by NatoBoram** [comment] 2021-03-06 14:52
Ah, there's news about this issue.

```
~ $ flutter --version
Flutter 2.1.0-10.0.pre • channel dev •
https://github.com/flutter/flutter.git
Framework • revision cc9b78fc5c (9 days ago) •
2021-02-25 13:26:03 -0800
Engine • revision a252ec09b7
Tools • Dart 2.12.0
~ $ flutter doctor
Unsupported operating system: android
```

The Dart SDK was able to compile the Flutter tool, but the Flutter tool refuses to continue. I think there's a few binaries to download that aren't provided for Android hosts. It would be nice if it compiled them though.
