### ISSUE TITLE
[google_maps_flutter] marker InfoWindow title text is white when iOS is Dark Mode

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#50165] opened 2020-02-05 04:08 UTC
```
google_maps_flutter: ^0.5.21+17
```

```
flutter 1.14.6
```

```
Marker(
  infoWindow: InfoWindow(
    title: "Luke Pighetti",
  ),
  icon: ...,
  markerId: ...,
  position: ...,
)
```

![IMG_D7E29EAECF93-1](https://user-images.githubusercontent.com/666539/73809999-02c61a00-47a3-11ea-926d-d9dfd48540d3.jpeg)

This only happens when iPhone 8+ `iOS 13.3` is in DarkMode

**Comment by dwikyhardi** [comment] 2020-03-11 07:13
Duplicate of [#40982](https://github.com/flutter/flutter/issues/40982)

**Comment by TahaTesser** [comment] 2021-04-27 13:10
Hi @lukepighetti 
Thanks for filing the issue!

| Light mode | Dark mode |
| --------------- | --------------- |
![Image from iOS (1)](https://user-images.githubusercontent.com/48603081/116246321-8c7c5180-a772-11eb-8d4d-8f5d3ef0c3af.png) | ![Image from iOS](https://user-images.githubusercontent.com/48603081/116246329-8f774200-a772-11eb-84c4-72c18400969f.png) | 

<details> 
<summary>flutter doctor -v</summary> 

```console
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision adc687823a (11 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.93

• No issues found!

```

```console
[✓] Flutter (Channel master, 2.3.0-1.0.pre.101, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.101 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff2dde2c7f (8 hours ago), 2021-04-26 22:35:45 -0700
    • Engine revision afd9c397a5
    • Dart version 2.14.0 (build 2.14.0-43.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version unknown)
    ✗ Invalid IntelliJ version number.

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.2
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 90.0.4430.93

! Doctor found issues in 1 category.
```
		
</details>

**Comment by stuartmorgan** [comment] 2021-08-17 19:02
As noted above, this is a duplicate; closing.

With current versions of Flutter, I believe that just setting the min iOS version of your app to iOS 9 will be enough to get newer versions of the Maps SDK, so the workarounds discussed in the original should no longer be necessary.

**Closed by stuartmorgan** 2021-08-17 19:02 UTC
Labels: platform-ios, plugin, p: first party, p: maps, has reproducible steps, found in release: 2.0, found in release: 2.3
