### ISSUE TITLE
[image_picker plugin 0.6.7+]: pickvideo from gallery format .mp4 but return pickedfile change to .jpg

### ISSUE THREAD

**Issue by KhairulAkhtar** [flutter/flutter#73448] opened 2021-01-07 01:44 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by darshankawar** [comment] 2021-01-07 08:39
Closing this as duplicate of https://github.com/flutter/flutter/issues/52419

**Closed by darshankawar** 2021-01-07 08:39 UTC
