### ISSUE TITLE
Localizations optionalParameters don't override

### ISSUE THREAD

**Issue by aiatsuk** [flutter/flutter#151341] opened 2024-07-05 12:23 UTC
### Steps to reproduce

For example I have English key

```json
"price": "{price}",
  "@price": {
    "description": "price",
    "placeholders": {
      "price": {
        "type": "double",
        "format": "currency",
        "optionalParameters": {
          "decimalDigits": 2,
          "name": "USD",
          "symbol": "$",
          "customPattern": "¤#0.00"
        }
      }
    }
  }
```

And key for German language

```json
"price": "{price}",
  "@price": {
    "description": "price",
    "placeholders": {
      "price": {
        "type": "double",
        "format": "currency",
        "optionalParameters": {
          "decimalDigits": 0,
          "name": "EUR",
          "symbol": "€",
          "customPattern": "0.00 ¤"
        }
      }
    }
  }
```

### Expected results

```dart
// `en` locale
Text(context.loc.price(price: 100)), // $100.00
```

```dart
// `de` locale
Text(context.loc.price(price: 100)), // 100 €
```

### Actual results

```dart
// `en` locale
Text(context.loc.price(price: 100)), // $100.00
```

```dart
// `de` locale
Text(context.loc.price(price: 100)), // $100.00
```

### Code sample

<details open><summary>Code sample</summary>

In `app_en.arb` for 
```json
  "price": "{price}",
  "@price": {
    "description": "price",
    "placeholders": {
      "price": {
        "type": "double",
        "format": "currency",
        "optionalParameters": {
          "decimalDigits": 2,
          "name": "USD",
          "symbol": "$",
          "customPattern": "¤#0.00"
        }
      }
    }
  }
```

`app_localizations_en.dart`
```dart
  @override
  String price({required double price}) {
    final intl.NumberFormat priceNumberFormat = intl.NumberFormat.currency(
      locale: localeName,
      decimalDigits: 2,
      name: 'USD',
      symbol: '\$',
      customPattern: '¤#0.00'
    );
    final String priceString = priceNumberFormat.format(price);

    return '$priceString';
  }
```

In `app_de.arb` for 
```json
  "price": "{price}",
  "@price": {
    "description": "price",
    "placeholders": {
      "price": {
        "type": "double",
        "format": "currency",
        "optionalParameters": {
          "decimalDigits": 0,
          "name": "EUR",
          "symbol": "€",
          "customPattern": "0.00 ¤"
        }
      }
    }
  }
```

`app_localizations_de.dart
```dart
  @override
  String price({required double price}) {
    final intl.NumberFormat priceNumberFormat = intl.NumberFormat.currency(
      locale: localeName,
      decimalDigits: 2,
      name: 'USD',
      symbol: '\$',
      customPattern: '¤#0.00'
    );
    final String priceString = priceNumberFormat.format(price);

    return '$priceString';
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-05 12:59
I believe this is a duplicate of https://github.com/flutter/flutter/issues/114237. 

Kindly follow up in the issue linked above for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-07-05 12:59 UTC
Labels: in triage
