### ISSUE TITLE
TextEditingController.clear() makes keyboard unresponsive until tapped on field.

### ISSUE THREAD

**Issue by parasthekoder** [flutter/flutter#39182] opened 2019-08-24 12:40 UTC
## Steps to Reproduce

1. Create Text, TextField, Button inside a column.
2. Define a TextEditing controller and pass it to controller field of TextField.
3. In onPressed() method, assign variable passed to Text(), a value of controller.text in setState.
4. Clear the controller.
4. Try to type again when keyboard is still open, and TextField will show that it is focused.

## flutter run --verbose
```
DevFS: Sync finished
[   +3 ms] Syncing files to device Redmi Note 7 Pro... (completed in 2,400ms, longer than expected)
[   +1 ms] Synced 0.9MB.
[   +3 ms] Sending to VM service: _flutter.listViews({})
[   +5 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x72dafcd020, isolate: {type: @Isolate, fixedId: true, id:
isolates/4135458902686711, name: main.dart$main-4135458902686711, number: 4135458902686711}}]}
[   +2 ms] <- accept
[        ] Connected to _flutterView/0x72dafcd020.
[   +4 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +2 ms] An Observatory debugger and profiler on Redmi Note 7 Pro is available at: http://127.0.0.1:34601/vOpbxgAEQv8=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+4467 ms] I/teditingexampl(13468): ProcessProfilingInfo new_methods=389 is saved saved_to_disk=1 resolve_classes_delay=8000
[+2895 ms] W/IInputConnectionWrapper(13468): getTextBeforeCursor on inactive InputConnection
[   +2 ms] W/IInputConnectionWrapper(13468): getSelectedText on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper(13468): getTextAfterCursor on inactive InputConnection
[+10988 ms] W/IInputConnectionWrapper(13468): getTextBeforeCursor on inactive InputConnection
[  +18 ms] W/IInputConnectionWrapper(13468): getSelectedText on inactive InputConnection
[        ] W/IInputConnectionWrapper(13468): getTextAfterCursor on inactive InputConnection
[+2367 ms] W/IInputConnectionWrapper(13468): getTextBeforeCursor on inactive InputConnection
[  +12 ms] W/IInputConnectionWrapper(13468): getSelectedText on inactive InputConnection
[   +3 ms] W/IInputConnectionWrapper(13468): getTextAfterCursor on inactive InputConnection

```

## flutter analyze

```
Analyzing texteditingexample...                                         
No issues found! (ran in 2.9s)
```

## flutter doctor -v

```
[✓] Flutter (Channel master, v1.9.4-pre.42, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.4-pre.42 at /home/paras/programs/flutter
    • Framework revision 01a5d112d5 (27 hours ago), 2019-08-23 11:16:30 +0200
    • Engine revision 975a8aa575
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/paras/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /home/paras/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 6.0.0
    • GNU Make 4.1

[✓] Android Studio (version 3.5)
    • Android Studio at /home/paras/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /home/paras/programs/idea-IC-191.7479.19
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.37.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.3.0

[✓] Connected device (2 available)
    • Redmi Note 7 Pro • 21765936 • android-arm64 • Android 9 (API 28)
    • Linux            • Linux    • linux-x64     • Linux

! Doctor found issues in 1 category.
```
## Minimal Code for reproducing the issue.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final _controller = TextEditingController();
  String _text = "Empty";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Last typed text is : $_text',
            ),
            TextField(
              controller: _controller,
            ),
            FlatButton(
              onPressed: () {
                setState(() {
                  _text = _controller.text;
                });
                _controller.clear();
              },
              child: Text("Send"),
            )
          ],
        ),
      ),
    );
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    _controller.dispose();
    focusNode.dispose();
  }
}

```

Note : Clicking again on TextField makes it responsive. and fixed the issue. I'm forced to tap on the TextField in order to type another message.

**Comment by Levi-Lesches** [comment] 2019-08-25 19:58
Is the problem that the keyboard is still up after calling `focusNode.unfocus()`? You say it is unresponsive until clicked on again, but at the same time you are trying to remove the keyboard...

**Comment by parasthekoder** [comment] 2019-08-26 05:25
What I'm building is chat application. As soon as user tap on send button, I wan't to clear the text in TextField and show them this text as a message in ListView. I came up with the simple example to reproduce the issue. I think unfocus() method helps only in the case when there are multiple fields and you want to switch to the next field. But even unfocus didn't provide the solution to me.

**Comment by Levi-Lesches** [comment] 2019-08-26 06:19
What unfocus does in this case is retract the keyboard. I'm still not 100% clear on what behavior you're looking for. When the user hits send, what exactly happens and in what order? What happens if they want to send another message?

**Comment by parasthekoder** [comment] 2019-08-26 11:02
I'll tell you step by step.

Case 1: User encounters the problem first time
1. User taps on TextField.
2. Keyboard comes up.
3. User types a message.
4. User clicks on send button (provided in UI).
5. User types another message via keyboard.
6. Nothing is showing in TextField.

Case 2: User knows the problem and found the workaround.
1. User taps on TextField.
2. Keyboard comes up.
3. User types a message.
4. User clicks on send button (provided in UI).
5. User types another message via keyboard.
6. Nothing is showing in TextField.
7. User taps on TextField again.
8. User types another message via keyboard.
9. User hit the send button. Message is delievered.

These are the two case to define the problem I'm facing. Once the user send a message, user won't be able to type another message until user taps on TextField again.

If still you can not understand, I'll post the video or GIF.

**Comment by parasthekoder** [comment] 2019-08-27 05:49
Sorry for creating the confusion. I've used unfocus() method, because I've read in some issue that one should remove focus and then call the clear() function. I've updated the code in my first comment. Please refer to it again.

**Comment by parasthekoder** [comment] 2019-08-28 06:02
I've tried using requestFocus() function. But it doesn't seem to provide the solution I want. I maybe using it incorrectly. Can you test my code ? Try using the requestFocus() function, and tell me if it works or not and how to using it.

**Comment by Nicolr3** [comment] 2019-08-28 15:34
The exact same thing is happening to me, any solution or do I have to go back to an earlier version?

**Comment by matthew-carroll** [comment] 2019-08-30 06:47
This issue should be resolved with the following reverts. The engine will need to roll into the framework before the issue is fully resolved on master.

https://github.com/flutter/flutter/pull/39523

https://github.com/flutter/engine/pull/11720

**Closed by matthew-carroll** 2019-08-30 06:47 UTC
Labels: a: text input, framework, severe: regression
