### ISSUE TITLE
AAPT2 aapt2-3.5.0-5435860-windows Daemon #0: Daemon startup failed

### ISSUE THREAD

**Issue by neerajkanchan** [flutter/flutter#58088] opened 2020-05-27 10:26 UTC
Hi - I am trying to setup flutter app and not able to run it:

Windows 7:

```
F:\Flutter_Project\myapp>flutter doctor -v
[ΓêÜ] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 6.1.7601], locale en-US)
    ΓÇó Flutter version 1.17.1 at E:\Apps\flutter
    ΓÇó Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    ΓÇó Engine revision 6bc433c6b6
    ΓÇó Dart version 2.8.2

[ΓêÜ] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ΓÇó Android SDK at E:\Apps\Android_sdk
    ΓÇó Platform android-29, build-tools 29.0.3
    ΓÇó ANDROID_HOME = E:\Apps\flutter
    ΓÇó Java binary at: E:\Apps\Android Studio\jre\bin\java
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ΓÇó All Android licenses accepted.

[ΓêÜ] Android Studio (version 3.6)
    ΓÇó Android Studio at E:\Apps\Android Studio
    ΓÇó Flutter plugin version 45.1.1
    ΓÇó Dart plugin version 192.8052
    ΓÇó Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[ΓêÜ] Connected device (1 available)
    ΓÇó AOSP on IA Emulator ΓÇó emulator-5554 ΓÇó android-x86 ΓÇó Android 9 (API 28) (emulator)

ΓÇó No issues found!
```
## Logs

```
F:\Neeraj\Flutter_Project\myapp>flutter run
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...


FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:mergeDebugResources'.

> Multiple task action failures occurred:

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #3: Daemon startup failed

        This should not happen under normal circumstances, please file an issue if it does.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #0: Daemon startup failed

        This should not happen under normal circumstances, please file an issue if it does.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #2: Daemon startup failed

        This should not happen under normal circumstances, please file an issue if it does.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #1: Daemon startup failed

        This should not happen under normal circumstances, please file an issue if it does.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #4: Daemon startup failed

        This should not happen under normal circumstances, please file an issue if it does.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #5: Daemon startup failed

        This should not happen under normal circumstances, please file an issue if it does.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #6: Daemon startup failed

        This should not happen under normal circumstances, please file an issue if it does.

   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #7: Daemon startup failed

        This should not happen under normal circumstances, please file an issue if it does.



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full i
nsights.



* Get more help at https://help.gradle.org



BUILD FAILED in 1m 57s
Running Gradle task 'assembleDebug'...                            118.7s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by neerajkanchan** [comment] 2020-05-27 10:27
I have also tried https://github.com/flutter/flutter/issues/51690#issuecomment-603988891 to adjust credle version but no help.

**Comment by VladyslavBondarenko** [comment] 2020-05-27 15:19
@neerajkanchan 
what gradle versions have you tried?
could you check if you can run it with admin rights? https://github.com/flutter/flutter/issues/48443#issuecomment-587661780
(you don't need to do it generally, but it may show that some files are lacking of permissions)

**Comment by neerajkanchan** [comment] 2020-05-28 09:24
@VladyslavBondarenko  - I have 5.6.2
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

**Comment by VladyslavBondarenko** [comment] 2020-05-28 10:03
@neerajkanchan 
does the error persist when using `https\://services.gradle.org/distributions/gradle-5.6.3-all.zip` and running with admin rights?

**Comment by neerajkanchan** [comment] 2020-05-29 00:41
@VladyslavBondarenko I tried updating https\://services.gradle.org/distributions/gradle-5.6.3-all.zip and running with admin rights but its still the same.

If I run following, I get gradle version 6.4.1 though:
F:\Flutter_Project\myapp>gradle --version

------------------------------------------------------------
Gradle 6.4.1
------------------------------------------------------------

Build time:   2020-05-15 19:43:40 UTC
Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5

Kotlin:       1.3.71
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Windows 7 6.1 amd64

**Comment by neerajkanchan1** [comment] 2020-05-30 00:10
@VladyslavBondarenko Is there any potential issue that could be causing this or may be some step that I may be missing or incorrect?

**Comment by jonahwilliams** [comment] 2020-05-30 00:33
unfortunately there isn't really anything for us to go off of in this stack trace. I would consider trying to create an empty project to see if it reproduces the issue. If not, you could gradually make changes until this error is hit to help us track down the cause.

Of course, it could also be some issue with a gradle cache, that could be fixed by clearing it out https://stackoverflow.com/questions/23025433/how-to-clear-gradle-cache . I'm less certain about that though

**Comment by neerajkanchan1** [comment] 2020-06-01 09:48
@jonahwilliams  - Oh thanks. Its actually empty project only. I did "flutter create MyApp" to get a flutter project created. After that I was trying to launch the app but that could not get through the build. I will try different steps and see if I can find the root cause and hopefully fix too.

**Comment by TahaTesser** [comment] 2020-06-26 15:29
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-06-26 15:29 UTC
Labels: platform-android, severe: crash, t: gradle, tool, waiting for customer response

**Comment by neerajkanchan1** [comment] 2020-06-26 23:48
@TahaTesser There was no additional information asked actually :-)

**Comment by TahaTesser** [comment] 2020-06-29 14:15
@neerajkanchan 
There was no new information, hope it's not happening again 
Thanks

**Comment by neerajkanchan1** [comment] 2020-06-29 23:54
@TahaTesser I had to switch to different machine all together and redone all setup which worked. Same steps were run on previous machine but there is some unknown issue in Flutter.

**Comment by 2227056071** [comment] 2020-07-27 03:04
I met the same error.
i solved it by the answer https://stackoverflow.com/a/57804481/5159080,It is enough just to do 2

**Comment by prateekjangra1239** [comment] 2020-11-07 06:26
Ok
