### ISSUE TITLE
When I run build on ios simulator everything is good, but on real iphone i get error. and Flutter build ios - give same error

### ISSUE THREAD

**Issue by Hopheylalal** [flutter/flutter#66283] opened 2020-09-21 18:52 UTC
@MacBook-Air-Alexander ios % flutter build ios
Changing current working directory to: /Users/alexander/AndroidStudioProjects/order_system_olga
 
Building com.app.ordersystem.olga for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: 5C569G8MV4
Running pod install...                                             15,4s
Running Xcode build...                                                  
                                                   
Xcode build done.                                           18,9s
Failed to build iOS app
Error output from Xcode build:
↳
   <details>
<summary>error log</summary>

```
 2020-09-21 21:48:08.801 xcodebuild[22465:11663865] warning:  The file reference for
    "Objective-C/TOCropViewController/Models/TOActivityCroppedImageProvider.h" is a member of multiple groups
    ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of
    the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file
    in more than one group, please add another reference to the same path.
    2020-09-21 21:48:08.801 xcodebuild[22465:11663865] warning:  The file reference for
    "Objective-C/TOCropViewController/Views/TOCropOverlayView.h" is a member of multiple groups ("TOCropViewController" and
    "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will be preserved
    (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please
    add another reference to the same path.
    2020-09-21 21:48:08.801 xcodebuild[22465:11663865] warning:  The file reference for
    "Objective-C/TOCropViewController/Models/TOCroppedImageAttributes.h" is a member of multiple groups
    ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of
    the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file
    in more than one group, please add another reference to the same path.
    2020-09-21 21:48:08.801 xcodebuild[22465:11663865] warning:  The file reference for
    "Objective-C/TOCropViewController/Views/TOCropScrollView.h" is a member of multiple groups ("TOCropViewController" and
    "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will be preserved
    (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please
    add another reference to the same path.
    2020-09-21 21:48:08.801 xcodebuild[22465:11663865] warning:  The file reference for
    "Objective-C/TOCropViewController/Views/TOCropToolbar.h" is a member of multiple groups ("TOCropViewController" and
    "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will be preserved
    (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please
    add another reference to the same path.
    2020-09-21 21:48:08.801 xcodebuild[22465:11663865] warning:  The file reference for
    "Objective-C/TOCropViewController/Views/TOCropView.h" is a member of multiple groups ("TOCropViewController" and
    "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will be preserved
    (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please
    add another reference to the same path.
    2020-09-21 21:48:08.801 xcodebuild[22465:11663865] warning:  The file reference for
    "Objective-C/TOCropViewController/TOCropViewController.h" is a member of multiple groups ("TOCropViewController" and
    "TOCropViewController"); this indicates a malformed project.  Only the membership in one of the groups will be preserved
    (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please
    add another reference to the same path.
    2020-09-21 21:48:08.801 xcodebuild[22465:11663865] warning:  The file reference for
    "Objective-C/TOCropViewController/Models/TOCropViewControllerTransitioning.h" is a member of multiple groups
    ("TOCropViewController" and "TOCropViewController"); this indicates a malformed project.  Only the membership in one of
    the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file
    in more than one group, please add another reference to the same path.
    ** BUILD FAILED **


Xcode's output:
↳
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'leveldb-library' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'image_cropper' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'geolocator' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'FirebaseAnalytics' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'FirebaseCoreDiagnostics' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'GTMAppAuth' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'FirebaseFirestore' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'google_maps_flutter' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Users/alexander/AndroidStudioProjects/order_system_olga/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/
    Models/TOActivityCroppedImageProvider.h (in target 'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Users/alexander/AndroidStudioProjects/order_system_olga/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/
    Views/TOCropOverlayView.h (in target 'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Users/alexander/AndroidStudioProjects/order_system_olga/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/
    Models/TOCroppedImageAttributes.h (in target 'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Users/alexander/AndroidStudioProjects/order_system_olga/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/
    Views/TOCropScrollView.h (in target 'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Users/alexander/AndroidStudioProjects/order_system_olga/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/
    Views/TOCropToolbar.h (in target 'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Users/alexander/AndroidStudioProjects/order_system_olga/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/
    Views/TOCropView.h (in target 'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Users/alexander/AndroidStudioProjects/order_system_olga/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/
    TOCropViewController.h (in target 'TOCropViewController' from project 'Pods')
    warning: Skipping duplicate build file in Copy Headers build phase:
    /Users/alexander/AndroidStudioProjects/order_system_olga/ios/Pods/TOCropViewController/Objective-C/TOCropViewController/
    Models/TOCropViewControllerTransitioning.h (in target 'TOCropViewController' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'FMDB' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'FirebaseStorage' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'nanopb' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'GoogleSignIn' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'flutter_phone_direct_caller' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'image_picker' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'shared_preferences' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'url_launcher' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'FirebaseCore' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'GoogleAppMeasurement' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'FirebaseAuth' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'gRPC-C++' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'Firebase' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'GoogleDataTransport' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'gRPC-Core' from project 'Pods')
    error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't include signing certificate "Apple Development:
    Aleksandr Ivanov (987W8PM28H)". (in target 'Runner' from project 'Runner')
    error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the Push Notifications capability. (in
    target 'Runner' from project 'Runner')
    error: Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the aps-environment entitlement. (in
    target 'Runner' from project 'Runner')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'FirebaseMessaging' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'TOCropViewController-TOCropViewControllerBundle' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'Flutter' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'firebase_core' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'FirebaseInstanceID' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'firebase_messaging' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'GoogleUtilities' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'simple_connectivity' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'GTMSessionFetcher' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'FirebaseInstallations' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'PromisesObjC' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'Reachability' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'cloud_firestore' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'firebase_auth' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'google_sign_in' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'firebase_storage' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'Protobuf' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'path_provider' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'AppAuth' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'BoringSSL-GRPC' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'sqflite' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment
    target versions is 9.0 to 14.0.99. (in target 'abseil' from project 'Pods')

Encountered error while building for device.


```

</details>

**Comment by adumrewal** [comment] 2020-09-21 19:47
On a quick look: Looks like you either have multiple import to the same library inside a file or you are using 2 SDKs which use the TOCropViewController pod.

For the warnings you can go to "project.pbxproj" and set all three occurrences of "IPHONEOS_DEPLOYMENT_TARGET" to "9.0".

**Comment by Hopheylalal** [comment] 2020-09-21 20:11
> For the warnings you can go to "project.pbxproj" and set all three occurrences of "IPHONEOS_DEPLOYMENT_TARGET" to "9.0".

Thank you but this is do not work for me.

I am new in programming, what is mean, and what i should do?

On a quick look: Looks like you either have multiple import to the same library inside a file or you are using 2 SDKs which use the TOCropViewController pod.

**Comment by darshankawar** [comment] 2020-09-22 06:29
Hi @Hopheylalal 
Please provide `flutter doctor -v`, `flutter run --verbose` and a minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by Abhishek01039** [comment] 2020-09-22 18:45
Hi @Hopheylalal 
as @adumrewal said go to `project.pbxproj` file which is in the iOS directory and set the `IPHONEOS_DEPLOYMENT_TARGET` to 9 which is 8 by default.
Thanks

**Comment by TahaTesser** [comment] 2020-10-14 12:34
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 12:34 UTC
Labels: in triage
