### ISSUE TITLE
TabBar inside DecoratedBox doesn't have ripples/hit states

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#8533] opened 2017-03-02 17:27 UTC
If I put a `TabBar` inside a `DecoratedBox` with a `BoxDecoration` (background color only) then the ripples/hit states do not appear. Example:

```dart
new Positioned(
  top: 0.0, left: 0.0, right: 0.0, height: 80.0,
  child: new DecoratedBox(
    decoration: new BoxDecoration(
      backgroundColor: new Color(0xFFFFFFFF),
    ),
    child: this._categoriesTabBar(),
  )
)
```

If I remove the `DecoratedBox` and add the `TabBar` to the `Positioned` element directly then the problem goes away.

**Comment by eseidelGoogle** [comment] 2017-03-02 17:40
@HansMuller might know?

**Comment by lukef** [comment] 2017-03-02 17:43
For what it is worth, the reason it is inside the `DecoratedBox` was to apply a background color to the `TabBar`.

**Comment by Hixie** [comment] 2017-03-03 20:47
Oh! The ripples are happening, they're just behind the decorated box. The decorated box is painting over the material. This is basically a dupe of https://github.com/flutter/flutter/issues/3782.

**Closed by Hixie** 2017-03-03 20:47 UTC
Labels: customer: hoppy, prod: framework
