### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by gauravwani-coditas** [flutter/flutter#149834] opened 2024-06-06 17:30 UTC
## Command
```
flutter pub add firebase_analytics
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:188:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:407:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:479:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:478:12)
#6      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:967:22)
#7      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:903:5)
#8      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1013:5)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:367:5)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:383:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.1, on macOS 12.5 21G72
    darwin-x64, locale en-GB)
    [32m•[39m Flutter version 3.22.1 on channel stable at
      /Users/coditas/Documents/flutterDev/sdk/flutter
    [32m•[39m Upstream repository
      https://github.com/flutter/flutter.git
    [32m•[39m Framework revision a14f74ff3a (2 weeks ago), 2024-05-22
      11:08:21 -0500
    [32m•[39m Engine revision 55eae6864b
    [32m•[39m Dart version 3.4.1
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Android toolchain - develop for Android devices (Android
    SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/coditas/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    [32m•[39m All Android licenses accepted.

[31m[✗][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation
      is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch
        /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS
        platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or
        macOS.
        For more info, see
        https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html
      #installation for instructions.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /Applications/Android
      Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m VS Code (version 1.85.2)
    [32m•[39m VS Code at /Users/coditas/Downloads/Visual Studio
      Code.app/Contents
    [32m•[39m Flutter extension version 3.90.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m sdk gphone64 x86 64 (mobile) • emulator-5554 •
      android-x64    • Android 14 (API 34) (emulator)
    [32m•[39m macOS (desktop)              • macos         •
      darwin-x64     • macOS 12.5 21G72 darwin-x64
    [32m•[39m Chrome (web)                 • chrome        •
      web-javascript • Google Chrome 125.0.6422.142

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: abb292a07e20d696c4568099f918f6c5f330e6b0
### Plugins
cloud_firestore-4.17.5
cloud_firestore_web-3.12.5
firebase_analytics-10.10.7
firebase_analytics_web-0.5.7+7
firebase_auth-4.20.0
firebase_auth_web-5.12.0
firebase_core-2.32.0
firebase_core_web-2.17.0
firebase_messaging-14.9.4
firebase_messaging_web-3.8.7
path_provider-2.1.3
path_provider_android-2.2.5
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.3
shared_preferences_android-2.2.3
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2

**Comment by darshankawar** [comment] 2024-06-07 08:55
Duplicate of https://github.com/flutter/flutter/issues/106953

**Closed by darshankawar** 2024-06-07 08:55 UTC
Labels: in triage
