### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "C:\Development\SDKs\flutter_windows_3.19.3-stable\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the search path. Command: C:\Development\SDKs\flutter_windows_3.19.3-stable\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 0

### ISSUE THREAD

**Issue by QaniAhmed** [flutter/flutter#151324] opened 2024-07-05 00:37 UTC
## Command
```
flutter run --machine --start-paused -d emulator-5554 --devtools-server-address http://127.0.0.1:9100/ --target C:\Development\Projects\pro\flutter_application_1\lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "C:\Development\SDKs\flutter_windows_3.19.3-stable\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the search path. Command: C:\Development\SDKs\flutter_windows_3.19.3-stable\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:686:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:556:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:685:12)
#4      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:876:37)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:736:14)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:422:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:396:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:782:23)
#9      _rootRunUnary (dart:async/zone.dart:1407:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:541:14)
#14     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
#16     _rootRun (dart:async/zone.dart:1391:47)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _rootRun (dart:async/zone.dart:1399:13)
#21     _CustomZone.run (dart:async/zone.dart:1301:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22621.3737], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\Development\SDKs\flutter_windows_3.19.3-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\welcome\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33424.131
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] VS Code (version 1.91.0)
    • VS Code at C:\Users\welcome\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.3737]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 126.0.6478.127
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 126.0.2592.87

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49

**Comment by danagbemava-nc** [comment] 2024-07-05 07:19
Closing this as a duplicate of https://github.com/flutter/flutter/issues/143391

**Closed by danagbemava-nc** 2024-07-05 07:19 UTC
Labels: in triage
