### ISSUE TITLE
availableCameras() not finding external camera

### ISSUE THREAD

**Issue by kunaldigi** [flutter/flutter#158975] opened 2024-11-15 06:47 UTC
### Steps to reproduce

I want to getting my external camera in flutter app

### Expected results

Show external camera in flutter app

### Actual results

Not detecting external camera in availableCameras()

### Code sample

<details open><summary>Not Getting External Camera</summary>

```dart
  var temp = await availableCameras();
  for (var camera in temp) {
      print(camera.lensDirection);  // This should print CameraLensDirection.external for external cameras
      print(camera.name);  // Camera name to help you identify the camera
    }
    CameraDescription externalCamera = temp.firstWhere((camera){
      print(camera);
     return camera.lensDirection == CameraLensDirection.external;
    },
      orElse: () => temp.first, // Fallback if no external camera found
    );
I/flutter ( 6484): CameraLensDirection.back
I/flutter ( 6484): Camera 0
I/flutter ( 6484): CameraLensDirection.front
I/flutter ( 6484): Camera 1
I/flutter ( 6484): CameraLensDirection.back
I/flutter ( 6484): Camera 2
I/flutter ( 6484): CameraDescription(Camera 0, CameraLensDirection.back, 90)
I/flutter ( 6484): CameraDescription(Camera 1, CameraLensDirection.front, 270)
I/flutter ( 6484): CameraDescription(Camera 2, CameraLensDirection.back, 90)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
I/flutter ( 6484): CameraLensDirection.back
I/flutter ( 6484): Camera 0
I/flutter ( 6484): CameraLensDirection.front
I/flutter ( 6484): Camera 1
I/flutter ( 6484): CameraLensDirection.back
I/flutter ( 6484): Camera 2
I/flutter ( 6484): CameraDescription(Camera 0, CameraLensDirection.back, 90)
I/flutter ( 6484): CameraDescription(Camera 1, CameraLensDirection.front, 270)
I/flutter ( 6484): CameraDescription(Camera 2, CameraLensDirection.back, 90)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
```

</details>

**Comment by huycozy** [comment] 2024-11-15 11:36
Duplicate of https://github.com/flutter/flutter/issues/42413

**Closed by huycozy** 2024-11-15 11:36 UTC
Labels: in triage
