### ISSUE TITLE
Memory leak observed upon closing Flutter windows

### ISSUE THREAD

**Issue by yaminet1024** [flutter/flutter#138893] opened 2023-11-22 13:54 UTC
### Steps to reproduce

1. Navigate to the demo directory with cd demo_win
2. flutter pub get
3. flutter run -d windows --release
4. Navigate through the application: open the menu, select 'New Flutter Window', then close the Flutter Window.
5. Repeat step 4 ten times. You will notice a consistent increase in memory usage.

first:
<img width="582" alt="企业微信截图_1ed6067c-5d4e-4892-b6be-2be6ba31b6d6" src="https://github.com/flutter/flutter/assets/23304639/a8ffc525-d418-4b33-85ca-1a13911f584d">

ten times:
<img width="581" alt="企业微信截图_e56da68b-c91e-473b-b826-0350b7458e25" src="https://github.com/flutter/flutter/assets/23304639/51718230-9874-4f8b-acb9-ed93e92af011">

### Code sample

see the flutter example project
[demo_win.zip](https://github.com/flutter/flutter/files/13440306/demo_win.zip)

### What target platforms are you seeing this bug on?

Windows

### OS/Browser name and version | Device information

Windows 11 x64 13th Gen Intel(R) Core(TM) i7-13700KF   3.42 GHz

### Does the problem occur on emulator/simulator as well as on physical devices?

Unknown

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.0, on macOS 13.6.1 22G313 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by huycozy** [comment] 2023-11-23 08:19
Hi @yaminet1024 
The multi-window has not been supported yet so I'm unfortunately going to close this issue. Please follow https://github.com/flutter/flutter/issues/30701 for further updates. Thanks!

**Comment by yaminet1024** [comment] 2023-11-24 08:08
@huycozy hi, I think this is not a issue related to multi-windows. This problem will also occur when a single window is opened and closed. The purpose of repeating it 10 times is to reflect the increase in memory. This is a desktop engine memory leak I think.

**Comment by huycozy** [comment] 2023-11-27 05:22
Re-opening the issue for further investigation. 

I tried running the example on my Windows `Microsoft Windows [Version 10.0.19045.3693]` but the issue didn't appear there. I observed app memory from Task Manager and noticed it consumed ~50MB every time opening `New Flutter Window` (from 20MB to 70MB), and then it got back to 20MB after closing `New Flutter Window` (tried this more than 10 times). 

On your machine, does the memory continue to increase the more times you try?

**Comment by yaminet1024** [comment] 2023-11-27 05:31
> Re-opening the issue for further investigation.
> 
> I tried running the example on my Windows `Microsoft Windows [Version 10.0.19045.3693]` but the issue didn't appear there. I observed app memory from Task Manager and noticed it consumed ~50MB every time opening `New Flutter Window` (from 20MB to 70MB), and then it got back to 20MB after closing `New Flutter Window` (tried this more than 10 times).
> 
> On your machine, does the memory continue to increase the more times you try?

Yes, I am very sure that there is a memory leak problem. As you can see from my screenshots, from 37.2 to 44.1, there will be an average leak of about 1m at a time. In our actual complex project, there will be 3m at a time.

**Comment by huycozy** [comment] 2023-11-28 07:38
Looks like this is OS-specific issue on Windows 11 as I can see the memory increases the more times I try on my Windows 11 machine. Labeling the issue for further insights.

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[!] Flutter (Channel stable, 3.16.1, on Microsoft Windows [Version 10.0.22000.2416], locale en-US)
    • Flutter version 3.16.1 on channel stable at C:\WORKING\SDK\flutter
    ! Warning: `flutter` on your path resolves to C:\Aliases\flutter.bat, which is not inside your current Flutter SDK checkout at C:\WORKING\SDK\flutter. Consider adding
      C:\WORKING\SDK\flutter\bin to the front of your path.
    ! The dart binary is not on your path. Consider adding C:\WORKING\SDK\flutter\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (12 hours ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.84.1)
    • VS Code at C:\Users\huynq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2416]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.92

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```

```bash
[!] Flutter (Channel master, 3.17.0-16.0.pre.36, on Microsoft Windows [Version 10.0.22000.2416], locale en-US)
    • Flutter version 3.17.0-16.0.pre.36 on channel master at C:\WORKING\SDK\flutter_master
    ! Warning: `flutter` on your path resolves to C:\Aliases\flutter.bat, which is not inside your current Flutter SDK checkout at C:\WORKING\SDK\flutter_master. Consider
      adding C:\WORKING\SDK\flutter_master\bin to the front of your path.
    ! The dart binary is not on your path. Consider adding C:\WORKING\SDK\flutter_master\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ad62645fce (55 minutes ago), 2023-11-28 14:20:07 +0900
    • Engine revision 96137d05fa
    • Dart version 3.3.0 (build 3.3.0-169.0.dev)
    • DevTools version 2.30.0-dev.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33829.357
    • Windows 10 SDK version 10.0.22000.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.84.1)
    • VS Code at C:\Users\huynq\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2416]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.92

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
```
</details>

**Comment by loic-sharma** [comment] 2023-12-01 20:41
Thanks for reporting this! The leaks reproduce on my machine and primarily allocations by ANGLE. However, our shutdown logic appears to be correctly tearing down the EGL contexts and display. I wonder if we're somehow not cleaning up properly, or, if ANGLE itself is leaking.

**Comment by yaminet1024** [comment] 2023-12-02 14:44
> Thanks for reporting this! The leaks reproduce on my machine and primarily allocations by ANGLE. However, our shutdown logic appears to be correctly tearing down the EGL contexts and display. I wonder if we're somehow not cleaning up properly, or, if ANGLE itself is leaking.
I've been analyzing this issue and identified one problem: Flutter creates EGL contexts on the IO or raster thread but releases them on the platform thread. This does not correctly release the ANGLE thread; it needs to destroy the context on the thread where it was created. Even after fixing the ANGLE thread leak, there are still many leaks present. I am actively working to analyze these additional leaks

**Comment by loic-sharma** [comment] 2023-12-02 18:15
@yaminet1024 Interesting, I wasn't aware of this. Where can I learn more about this, are you aware of any docs on this topic?

**Comment by yaminet1024** [comment] 2023-12-12 14:08
> @yaminet1024 Hm, on Windows we create the render and resource contexts on the platform thread at start up, before the engine is started and before the IO & raster threads exist. I wasn't aware of this ANGLE requirement though, where can I learn more about this topic? Perhaps our threading strategies is causing these leaks.

Hi, Apologies for the delayed response. ,I found the problem just to debug angle code, I've pinpointed the issue to how eglMakeCurrent manages thread data. It appears that when eglMakeCurrent is called on the IO/Raster thread, the context gains a reference count, which is only decremented when eglMakeCurrent is invoked with EGL_NO_CONTEXT on the same thread. However, I couldn't find a call to makeCurrent(,,EGL_NO_CONTEXT) in the AngleManager.

Here are the relevant sections of the ANGLE codebase that I've been looking into:

Binding the context to a thread: 
[eglMakeCurrent Entry Point](https://github.com/google/angle/blob/32175d8a6dc185dd850e5c9988f208085c9c0d80/src/libGLESv2/entry_points_egl_autogen.cpp#L391C27-L391C43)
[eglMakeCurrent Stub](https://github.com/google/angle/blob/32175d8a6dc185dd850e5c9988f208085c9c0d80/src/libGLESv2/egl_stubs.cpp#L493C18-L493C33)
 [Display.cpp](https://github.com/google/angle/blob/32175d8a6dc185dd850e5c9988f208085c9c0d80/src/libANGLE/Display.cpp#L1632)
I also discovered that eglDestroyContext will not fully clear all data If the context is still current on at least 1 thread.
[eglDestroyContext](https://github.com/google/angle/blob/32175d8a6dc185dd850e5c9988f208085c9c0d80/src/libANGLE/Display.cpp#L1775C1-L1776C1)

Furthermore, eglTerminate does not clear all the data either.
[eglTerminate](https://github.com/google/angle/blob/32175d8a6dc185dd850e5c9988f208085c9c0d80/src/libANGLE/Display.cpp#L1204C1-L1204C9)

It seems that flutter threading strategy might not be accounting for this reference count behavior, which could be leading to the leaks we're experiencing. 

If I set EGL_NO_CONTEXT during the clear time on the raster/IO thread, I notice a 38MB reduction in memory usage when closing the Flutter window.

<img width="1135" alt="aab24aea-e976-4071-9e91-bb97c767c583" src="https://github.com/flutter/flutter/assets/23304639/01e872d1-ff8c-40ff-85ab-150fc1492954">

before:
<img width="714" alt="20231212214121" src="https://github.com/flutter/flutter/assets/23304639/1f851a9f-9a75-441e-aa40-34ce7ad8dd67">

after:
<img width="714" alt="20231212220124" src="https://github.com/flutter/flutter/assets/23304639/4cabc975-91e1-4bae-a79d-77b40392767c">


I'm curious as to why this approach wasn't implemented previously? Am I wrong to change it this way? If this change is indeed beneficial and doesn't introduce any issues, I would be glad to contribute a fix for this problem.

**Closed** 2024-07-18 17:03 UTC
Labels: platform-windows, a: desktop, e: OS-version specific, perf: memory, has reproducible steps, P2, found in release: 3.16, found in release: 3.17, team-windows, triaged-windows
