### ISSUE TITLE
flutter_gallery_ios32__transition_perf average_frame_rasterizer_time_millis regressed when turning on AA

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#30402] opened 2019-04-02 20:53 UTC
https://github.com/flutter/engine/pull/8157 apparently regressed `flutter_gallery_ios32__transition_perf average_frame_rasterizer_time_millis` about 10%.

cc @dnfield

**Comment by Hixie** [comment] 2019-04-02 20:56
Maybe also `flutter_gallery__transition_perf average_frame_rasterizer_time_millis`, which regressed at the same time.

**Comment by dnfield** [comment] 2019-04-02 21:28
That commit enabled anti aliasing where we were missing it.  I suppose we should anticipate that woudl cause some regression there.

Should I just rebaseline the benchmark?

/cc @liyuqian

**Comment by Hixie** [comment] 2019-04-02 22:13
It's a pretty big regression. Is the improvement noticeable? Would it be worth turning it off on lower-end devices, maybe?

**Comment by dnfield** [comment] 2019-04-02 23:23
We go from this:

![image](https://user-images.githubusercontent.com/8620741/55442307-e2b24280-5562-11e9-9de5-f69963a38b36.png)


To this:

![image](https://user-images.githubusercontent.com/8620741/55442320-f067c800-5562-11e9-9f79-0d6bb44bde60.png)

which is a significant improvement.

It would be possible to disable this for ios32 builds, but that introduces a loss of quality on that platform (and a loss of quality in only one area).

It may be worth investigating if we could make anti-aliasing in general optional - right now we have a lot of places in the engine that turn it on no matter what, but we could offer developers a toggle - or perhaps have some kind of toggle based on our current FPS.  That said, I suspect developers would have a difficult time deciding when to do this, and users would be upset about a sudden degredation in quality that they have no way to control if we made it FPS based.

**Comment by liyuqian** [comment] 2019-04-02 23:47
It's quite hard to say whether the improvement or the cost is noticeable:
1. Many shapes are already anti-aliased in flutter_gallery without this PR so maybe users won't see a big difference (compared to all AA vs. all non-AA).
2. 10% increase in average raster time is still below 16ms so in the case where every frame is using exactly the average raster time, users also won't see a performance decrease (other than maybe the battery usage).

I guess that we'll need a framework/mechanism to conduct user research to justify decisions like this. I've been thinking about it since last year, and Skia's recent AA change (CCPR) made me to think about it again, and I hope that I can finish my draft with Tao soon once I get my other overdued P0/P1 done.

**Comment by liyuqian** [comment] 2019-04-08 20:14
@dnfield : as you've rebaselined the becnhmark, can we close this issue?

BTW, flutter_gallery__transition_perf average_frame_rasterizer_time_millis also regressed a little after your manual engine roll. Please double check if it's expected and rebaseline the benchmark if so.

**Comment by dnfield** [comment] 2019-04-08 21:13
Both have been updated.  Closing.

**Closed by dnfield** 2019-04-08 21:13 UTC
Labels: a: quality, engine, severe: performance, severe: regression
