### ISSUE TITLE
Current AVD Device Emulator Error Solution Suggestion in Windows

### ISSUE THREAD

**Issue by ozcanbayram** [flutter/flutter#160744] opened 2024-12-22 23:01 UTC
Solution By BerkSartik: [https://github.com/flutter/flutter/issues/160161#issuecomment-2559130216](url)

- Open the C:\Users\user\.android folder.

- Create an advancedFeatures.ini file.

- Add the commands below to this file.

```
Vulkan=off
GLDirectMem=on
```

- Do flutter clean flutter run

This is what removed the computer freezing issue in API 34. Apart from this, the emulator was closing itself in API 33, and it was completely resolved.

OR TRY WHIS SOLUTION:

### **The reason for this error may be that your video card driver is not up to date. (e.g. NVIDIA, Intel)**

I offer this solution, taking reference from this problems: #160500 and #160161

I saw the social media posts of people experiencing this problem and wanted to benefit from my own solution.

_**I am using NVIDIA and I updated as follows:**_

- Go to NVIDIA Driver Download Page: [https://www.nvidia.com/en-us/drivers/](url)

- Choose your product type and model (For example):
Product Type: GeForce
Product Series: The series of your card (for example GeForce RTX 30 Series).
Product: Your card model (for example RTX 3060).
Operating System: The operating system you are using (Windows 10, 11, etc.).

- Download the resulting driver and run the file.

- Install Driver

- After the installation is complete, restart your computer.

### **! If you are using intel**

- Go to Intel's Driver Download Page

- Learn Your Processor Model:
(Click Start > Run > type dxdiag and press Enter.)
In the window that opens, go to the "System Information" tab and check the model of your processor 

- On the driver download page, select the "Graphics" category.

- Find the graphics driver for your processor model and select the version compatible with your operating system.

- Download the relevant driver and start the installation process by running the file.

- After the installation is complete, restart your computer.

**_! If this solution solves your error, I would be happy to give you feedback._**

**Comment by danagbemava-nc** [comment] 2024-12-30 09:34
The flutter issue tracker is for reporting bugs in flutter. 

While we appreciate what you're trying to do with this issue, there are better places to keep track of this. 

Given that this is not a bug in flutter, I'll be closing this. 

Thank you

**Closed by danagbemava-nc** 2024-12-30 09:34 UTC
Labels: in triage
