### ISSUE TITLE
[BUG] player state not same between native side and flutter dart side

### ISSUE THREAD

**Issue by shashikantshaale** [flutter/flutter#50686] opened 2020-02-13 02:49 UTC
## Steps to Reproduce

1. Run video, let it reach end. after end isPlaying=false.
2. Seek to middle through progress indicator.  isPlaying=false still.
3. Now VideoPlayerController does not notify of new values as isPlaying=false.
 But, the video player starts playing video as it was playing before it is completed.
In dart it does not notify because isPlaying is false.

<details>
  <summary>Logs</summary>

```
Analyzing flutter_dplayer...                                            
No issues found! (ran in 2.3s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!

```
</details>

**Comment by shashikantshaale** [comment] 2020-02-13 02:53
Temporary fix:
in the progress bar _seekToRelativePosition_ function:
```
    void seekToRelativePosition(Offset globalPosition) async {
     ...
      final isCompleted = controller.value.position == controller.value.duration;
      await controller.seekTo(position);
      if (isCompleted) {
        //This is bug fix
        await controller.play();
      }
    }
```

**Comment by markusaksli-nc** [comment] 2020-07-15 14:06
Reproducible in latest master `1.20.0-8.0.pre.102` with latest [video_player 0.10.11+2](https://pub.dev/packages/video_player/versions/0.10.11+2)
<details>
 <summary>Minimal reproducible code sample</summary>

 ```
import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:video_player/video_player.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Example',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Video example'),
        ),
        body: _BumbleBeeRemoteVideo(),
      ),
    );
  }
}

class _BumbleBeeRemoteVideo extends StatefulWidget {
  @override
  _BumbleBeeRemoteVideoState createState() => _BumbleBeeRemoteVideoState();
}

class _BumbleBeeRemoteVideoState extends State<_BumbleBeeRemoteVideo> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
    );

    _controller.addListener(() {
      setState(() {});
    });
    _controller.initialize();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  String text = "init";

  @override
  Widget build(BuildContext context) {
    Timer(Duration(milliseconds: 100), () {
      setState(() {
        text =
            "controller isPlaying = " + _controller.value.isPlaying.toString();
      });
    });
    return Column(
      children: <Widget>[
        Container(
          padding: const EdgeInsets.all(20),
          child: AspectRatio(
            aspectRatio: _controller.value.aspectRatio,
            child: Stack(
              alignment: Alignment.bottomCenter,
              children: <Widget>[
                VideoPlayer(_controller),
                ClosedCaption(text: _controller.value.caption.text),
                _PlayPauseOverlay(controller: _controller),
                VideoProgressIndicator(_controller, allowScrubbing: true),
              ],
            ),
          ),
        ),
        Container(
          child: Center(
            child: Text(text),
          ),
        ),
      ],
    );
  }
}

class _PlayPauseOverlay extends StatelessWidget {
  const _PlayPauseOverlay({Key key, this.controller}) : super(key: key);

  final VideoPlayerController controller;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        AnimatedSwitcher(
          duration: Duration(milliseconds: 50),
          reverseDuration: Duration(milliseconds: 200),
          child: controller.value.isPlaying
              ? SizedBox.shrink()
              : Container(
                  color: Colors.black26,
                  child: Center(
                    child: Icon(
                      Icons.play_arrow,
                      color: Colors.white,
                      size: 100.0,
                    ),
                  ),
                ),
        ),
        GestureDetector(
          onTap: () {
            controller.value.isPlaying ? controller.pause() : controller.play();
          },
        ),
      ],
    );
  }
}

```
</details>

<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.20.0-8.0.pre.102, on Microsoft Windows [Version 10.0.18362.900], locale et-EE)
    • Flutter version 1.20.0-8.0.pre.102 at C:\Development\flutter_master
    • Framework revision f95f46e910 (8 hours ago), 2020-07-15 01:46:01 -0400
    • Engine revision be7595bafb
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)        • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```
</details>

Steps as described by the author. Observed behavior affects VideoProgressIndicator as well.

**Comment by maheshmnj** [comment] 2021-07-07 08:04
I am able to reproduce the issue on the latest stable and the master channel with ```video_player: ^2.1.6```  after the video has ended when we seekto a position by tapping on the progress indicator the video starts playing but the progress bar doesn't update and ```_controller.value.isPlaying``` still remains false. And as soon as the video ends the progress bar moves to the end. The issue is replicable on both IOS and Android.

<details>
<summary>code sample </summary>

```
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';
import 'package:video_player_example/main.dart';

void main() {
  runApp(
    MaterialApp(home: VideoPlayerDocs()),
  );
}

class VideoPlayerDocs extends StatefulWidget {
  @override
  _VideoPlayerDocsState createState() => _VideoPlayerDocsState();
}

class _VideoPlayerDocsState extends State<VideoPlayerDocs> {
  late VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network('$chromeCastUrl')
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
        print('initialized');
        print('video duration =${_controller.value.duration}');
        _controller.addListener(() {
          print(' is playing =${_controller.value.isPlaying}');
          final isCompleted =
              _controller.value.position == _controller.value.duration;
          if (isCompleted) {
            print(_controller.value.isPlaying);
            print('video ended at ${_controller.value.position}');
            print(' is playing =${_controller.value.isPlaying}');
          }
        });
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        appBar: AppBar(
          automaticallyImplyLeading: true,
        ),
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: Stack(
                    alignment: Alignment.topCenter,
                    children: <Widget>[
                      VideoPlayer(_controller),
                      VideoProgressIndicator(_controller, allowScrubbing: true),
                    ],
                  ),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}

```
</details>

<details>
<summary>console output</summary>

```
Running "flutter pub get" in example...
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Xcode build done.                                           37.1s
Connecting to VM Service at ws://127.0.0.1:52323/XHVo1T_3mVQ=/ws
TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
flutter: initialized
flutter: video duration =0:01:00.070000
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =true
flutter:  is playing =false
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =true
flutter:  is playing =false
flutter: false
flutter: video ended at 0:01:00.070000
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter:  is playing =false
flutter: false
flutter: video ended at 0:01:00.070000
flutter:  is playing =false

```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (5 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.4.0-1.0.pre.78, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.4.0-1.0.pre.78 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761d568421 (2 days ago), 2021-07-05 05:21:03 -0400
    • Engine revision 37e3922ae8
    • Dart version 2.14.0 (build 2.14.0-276.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • 6A434744-B348-4FB3-AB10-131292174456 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```
</details>

**Comment by maheshmnj** [comment] 2021-07-08 13:31
This issue is a duplicate of #80811, Please follow there for more updates. if you disagree feel free to comment and I will reopen it.

Thank you for your contribution

**Closed by maheshmnj** 2021-07-08 13:31 UTC
Labels: found in release: 2.2, found in release: 2.4, has reproducible steps, p: first party, p: video_player, plugin
