### ISSUE TITLE
Upgrade gradle version ?

### ISSUE THREAD

**Issue by EArminjon** [flutter/flutter#98362] opened 2022-02-13 17:13 UTC
## Use case

When running flutter create, Android use the following version of gradle : 
```
com.android.tools.build:gradle:4.1.0'
```

Why Flutter didn't use a more recent version ?

## Proposal

Use a recent version.
https://developer.android.com/studio/releases/gradle-plugin

## Limitation

Is their any reasons to keep this old version ? Can we gain some performance and reduce production issue/crash with this ?

**Comment by ragokan** [comment] 2022-02-13 17:35
I think using old gradle version gives more bugs. 
As mentioned here [#googleads](https://github.com/googleads/googleads-mobile-flutter/issues/471)
Upgrading to later versions actually fixes the bugs on some devices.

**Comment by darshankawar** [comment] 2022-02-14 09:35
Closing this as a duplicate of https://github.com/flutter/flutter/issues/92073

**Closed by darshankawar** 2022-02-14 09:35 UTC
Labels: in triage
