### ISSUE TITLE
SharedPreferencesPlugin - access from native code is needed to read/set prefs as well

### ISSUE THREAD

**Issue by gregko** [flutter/flutter#17914] opened 2018-05-25 19:33 UTC
I have an enhancement request to shared_preferences plugin. On occasion the native side of a Flutter app (e.g. Java side on Android) needs to access shared preferences set in Flutter, or maybe set them for Flutter side as well. It is necessary for example when communicating with other native apps on a platform.

Currently what I have to do in Java to accomplish this is:

SharedPreferences prefs = getSharedPreferences("FlutterSharedPreferences", MODE_PRIVATE);

and later when I want to read e.g. "myValue" key, I have to add "flutter." prefix:

String value = prefs.getString("flutter."+key, null);

This does not feel right though, spying on package private values and using them elsewhere. A better way should be provided by the SharedPreferencesPlugin instead.

**Comment by Rockvole** [comment] 2018-06-11 00:51
You can try my preferences library :

https://github.com/Rockvole/flutter/tree/master/filename_preferences

**Comment by gregko** [comment] 2018-06-11 02:18
Thank you very much, I’ll give it a try!

**Comment by zoechi** [comment] 2018-08-26 16:05
Is this solved?

**Comment by zoechi** [comment] 2018-12-11 13:58
Duplicate of #21925 
I think this is covered by #21925

**Closed by zoechi** 2018-12-11 13:58 UTC
Labels: p: framework, plugin

**Comment by zoechi** [comment] 2019-02-07 16:15
Duplicate of #14337
