### ISSUE TITLE
Failed resolution of: Landroid/support/v4/util/LongSparseArray

### ISSUE THREAD

**Issue by haibowen** [flutter/flutter#46681] opened 2019-12-10 12:55 UTC
> 我想用flutter 调用原生Android的方法，（原生Android集成了LiquidCore，【    implementation 'com.github.LiquidPlayer:LiquidCore:0.6.2'
> 】即java调用了js方法）其实最终实现的是 flutter通过调用java 来调用了JS
> 但是app安装后，点击调用按钮 运行后报错了....日志如下

I want to call native Android methods with flutter, (Native Android integrates LiquidCore, [implementation 'com.github.LiquidPlayer: LiquidCore: 0.6.2'
] That is, java calls the js method) In fact, the final implementation is that flutter calls JS by calling java
But after the app is installed, click the call button and it reports an error after running ... The log is as follows

```bash
2019-12-10 20:44:12.911 5115-5115/com.example.flutter_app_channel E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/LongSparseArray;
        at org.liquidplayer.javascript.JNIJSValue.<clinit>(JNIJSValue.java:126)
        at org.liquidplayer.javascript.JNIJSObject.fromRef(JNIJSObject.java:80)
        at org.liquidplayer.javascript.JNIJSContext.getGlobalObject(JNIJSContext.java:34)
        at org.liquidplayer.javascript.JSContext.<init>(JSContext.java:102)
        at org.liquidplayer.javascript.JSContext.<init>(JSContext.java:89)
        at io.flutter.plugins.FlutterPluginJumpToAct.JSFuction(FlutterPluginJumpToAct.java:62)
        at io.flutter.plugins.FlutterPluginJumpToAct.onMethodCall(FlutterPluginJumpToAct.java:43)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.LongSparseArray" on path: DexPathList[[zip file "/data/app/com.example.flutter_app_channel-aWHaJMFP7VAW6PqqQLABFg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_app_channel-aWHaJMFP7VAW6PqqQLABFg==/lib/x86_64, /data/app/com.example.flutter_app_channel-aWHaJMFP7VAW6PqqQLABFg==/base.apk!/lib/x86_64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.liquidplayer.javascript.JNIJSValue.<clinit>(JNIJSValue.java:126) 
        at org.liquidplayer.javascript.JNIJSObject.fromRef(JNIJSObject.java:80) 
        at org.liquidplayer.javascript.JNIJSContext.getGlobalObject(JNIJSContext.java:34) 
        at org.liquidplayer.javascript.JSContext.<init>(JSContext.java:102) 
        at org.liquidplayer.javascript.JSContext.<init>(JSContext.java:89) 
        at io.flutter.plugins.FlutterPluginJumpToAct.JSFuction(FlutterPluginJumpToAct.java:62) 
        at io.flutter.plugins.FlutterPluginJumpToAct.onMethodCall(FlutterPluginJumpToAct.java:43) 
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231) 
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93) 
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:326) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-12-10 20:44:12.912 5115-5115/com.example.flutter_app_channel A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
2019-12-10 20:44:12.912 5115-5115/com.example.flutter_app_channel A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 5115 (ter_app_channel), pid 5115 (ter_app_channel)

```

**Comment by itsJoKr** [comment] 2019-12-10 13:28
I don't there's anything wrong with Flutter here. It seems like the problem is with the liquidplayer library. Everything needs to be updated to androidx. This is using support library instead androidx `android.support.v4.util.LongSparseArray`

You can find migration to AndroidX here, as I said it has nothing to do with flutter specifically: https://developer.android.com/jetpack/androidx/migrate

**Comment by haibowen** [comment] 2019-12-11 02:16
thanks bro

**Comment by haibowen** [comment] 2019-12-11 02:17
> 我没有Flutter出现任何问题。看来问题出在Liquidplayer库上。一切都需要更新到androidx。这是使用支持库而不是androidx`android.support.v4.util.LongSparseArray`
> 
> 您可以在此处找到向AndroidX的迁移，因为我说过它与Flutter无关：[https](https://developer.android.com/jetpack/androidx/migrate) : [//developer.android.com/jetpack/androidx/migrate](https://developer.android.com/jetpack/androidx/migrate)

thanks bro！

**Comment by iapicca** [comment] 2019-12-11 10:28
Hi @haibowen 
I'm Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by iapicca** 2019-12-11 10:28 UTC
