### ISSUE TITLE
LinearGradient stops/colors properties as named parameters fail

### ISSUE THREAD

**Issue by scullabyte** [flutter/flutter#63908] opened 2020-08-16 17:31 UTC
## Steps to Reproduce

1. call the `LinearGradient` function with a `color` property

```
	LinearGradient(
      begin: begin,
      end: end,
	  // These are broken now:
      stops: stops,
      colors: colors,
    );
```

The new code on `master` shows this:
```
const LinearGradient({
    this.begin = Alignment.centerLeft,
    this.end = Alignment.centerRight,
    required List<Color> colors,
    List<double>? stops,
    this.tileMode = TileMode.clamp,
    GradientTransform? transform,
  }) : assert(begin != null),
       assert(end != null),
       assert(tileMode != null),
       super(colors: colors, stops: stops, transform: transform);
```

I'm assuming this:
```
    required List<Color> colors,
    List<double>? stops,
```

should be this:
```
    required List<Color> this.colors,
    List<double>? this.stops,
```

Unless I'm missing something?

## Logs

Inside VSCode when adding `colors`:
```
The named parameter 'colors' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'colors'.
```

However, `colors` is required, so when taking the `colors` property out, compile errors are shown:
```
════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/painting/gradient.dart': Failed assertion: line 152 pos 15: 'colors != null': is not true.
The relevant error-causing widget was
```

`flutter doctor -v`:

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.114, on macOS 11.0 20A5343i, locale en)
    • Flutter version 1.21.0-10.0.pre.114 at /Users/admin/flutter
    • Framework revision b2c0970aa7 (7 hours ago), 2020-08-16 06:11:02 -0400
    • Engine revision b300be3df3
    • Dart version 2.10.0 (build 2.10.0-34.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2
```

**Comment by Abhishek01039** [comment] 2020-08-16 19:06
hi @scullabyte
```
LinearGradient(
      begin: begin,
      end: end,
	  // These are broken now:
      stops: stops,
      colors: colors,
    );
```
can you please provide these values of the variables ?
Thanks

**Comment by pedromassangocode** [comment] 2020-08-17 14:05
Hi @scullabyte 
The `LinearGradient` class is working as expected on the latest `master` channel. I assume you're having some Dart Analysis issue, I recommend you to restart your code editor.

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.114, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.21.0-10.0.pre.114 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision b2c0970aa7 (26 hours ago), 2020-08-16 06:11:02 -0400
    • Engine revision b300be3df3
    • Dart version 2.10.0 (build 2.10.0-34.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone SE (2nd generation) (mobile) • 1119074E-0493-4533-9212-6758A33EB40C
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 84.0.4147.125

! Doctor found issues in 3 categories.
```
</details>

Closing this as this is not an issue with Flutter itself. If you disagree please comment bellow and I will reopen it.
Thank you

**Comment by MOo207** [comment] 2020-08-17 14:06
it`s the same issue that i suddenly facing right now.
my snippets
<pre>
body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            colors: [
              style.backgroundColor1,
              style.backgroundColor2
            ], 
            stops: [0.0, 1.0],
            tileMode: TileMode.repeated,
            begin: Alignment.centerLeft,
            end:  Alignment(1.0, 0.0), 
          ),
        ),
      ),
</pre>
Then i checked the member of LinearGradient on documecnt and i found 
  * required List<Color> colors,
  *  List<double>? stops,
  *  this.tileMode = TileMode.clamp,

in quick vscode document shows me the instance and it`s constructor like this
<pre>
LinearGradient LinearGradient({AlignmentGeometry begin = Alignment.centerLeft, AlignmentGeometry end = Alignment.centerRight, dynamic List})
</pre>

**Closed by pedromassangocode** 2020-08-17 14:05 UTC

**Comment by scullabyte** [comment] 2020-08-17 17:09
> hi @scullabyte
> 
> ```
> LinearGradient(
>       begin: begin,
>       end: end,
> 	  // These are broken now:
>       stops: stops,
>       colors: colors,
>     );
> ```
> 
> can you please provide these values of the variables ?
> Thanks

They're all within the range of the parameters... Specifically, `colors` and `stops` are the same lengths as the array.

@pedromassangocode thanks for the `flutter doctor -v`, very helpful. The only difference that steps out between mine, @MOo207, and yours is that you don't have the Flutter extension for VSCode installed. I'm guessing that's where the problem lies. I will switch back to master soon and test this with that disabled to help nail this down.

**Comment by scullabyte** [comment] 2020-08-17 18:19
Ok, I can confirm that this does not show up in Android Studio's linter and builds fine inside Android studio. I uninstalled the flutter extension on VSCode and it made no difference. I'm guessing this is a VSCode thing. Maybe because of the null-checks that were added to the `stops` parameter? Does that still fall under the flutter purview, or where should I go to try to help fix this?

**Comment by chuckntaylor** [comment] 2020-08-17 18:20
Hi, I am just playing with some LinearGradient right now. I'm having the same issue noted above in VS Code (on branch master) in regards to there being issue with the `colors` parameter. I see the same constructor in the quickview documentation as @MOo207 mentions above. Seeing that this issue is very recent, I thought I would share my `flutter doctor -v` too in case it is relevant. It is worth noting, that despite the errors showing in VS Code, the project builds, and the gradient appears as expected.

### flutter doctor -v

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.90, on Mac OS X 10.15.6 19G73, locale en-CA)
    • Flutter version 1.21.0-10.0.pre.90 at /Users/chuckntaylor/Developer/flutter
    • Framework revision 88118bcbd1 (4 days ago), 2020-08-14 00:17:43 +0200
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/chuckntaylor/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/chuckntaylor/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (3 available)            
    • iPhone 11 Pro (mobile) • 1AC4255A-8CC8-428A-A3BD-E83D3187834E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 80.0.3987.87

• No issues found!
```

**Comment by chuckntaylor** [comment] 2020-08-17 18:25
Okay. I think I see the issue. In the constructor for LinearGradient in `gradient.dart`, it is written as:
### gradient.dart
```
class LinearGradient extends Gradient {
  /// Creates a linear gradient.
  ///
  /// The [colors] argument must not be null. If [stops] is non-null, it must
  /// have the same length as [colors].
  const LinearGradient({
    this.begin = Alignment.centerLeft,
    this.end = Alignment.centerRight,
    required List<Color> colors,
    List<double>? stops,
    this.tileMode = TileMode.clamp,
    GradientTransform? transform,
  })  : assert(begin != null),
        assert(end != null),
        assert(tileMode != null),
        super(colors: colors, stops: stops, transform: transform);
```

It is missing the **@** before `required` on line 358.

**Comment by craiglabenz** [comment] 2020-08-18 00:33
@chuckntaylor I looked right at that myself and didn't even notice the missing `@`.

Kind of wild though that such a typo snuck past all the guards 🤔

**Comment by chuckntaylor** [comment] 2020-08-18 00:38
@craiglabenz I've been told that this was not actually a problem.

I made the 'correction' and submitted a pull request. However, it was rejected, with the following message:
"required without the @ is the new syntax with dart's new nullsaftey feature: https://dart.dev/null-safety/understanding-null-safety#required-named-parameters

If you're using the latest Dart SDK shipped with Flutter in VS Code you shouldn't see any warnings about this."

So, I did run `$ flutter upgrade`, and it appears the problem went away. Not sure why the Flutter package was upgraded before the Dart SDK in the first place, but this did seem to resolve the issue.

**Comment by craiglabenz** [comment] 2020-08-18 00:45
Ah nice, I'm on master, but also had to `flutter clean` _and then_ restart VS Code, and now it has gone away for me, too.

**Comment by pedromassangocode** [comment] 2020-08-18 06:04
> @pedromassangocode thanks for the `flutter doctor -v`, very helpful. The only difference that steps out between mine, @MOo207, and yours is that you don't have the Flutter extension for VSCode installed. I'm guessing that's where the problem lies. I will switch back to master soon and test this with that disabled to help nail this down.

Hi @scullabyte and anyone facing this issue

Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).

**Comment by andrefauth** [comment] 2020-09-16 14:35
> Ah nice, I'm on master, but also had to `flutter clean` _and then_ restart VS Code, and now it has gone away for me, too.

That worked for me!

**Comment by holivieri** [comment] 2020-10-02 17:17
This issue is still there in Flutter 1.22 and Dart 2.10 (at least in the Mac version)

**Comment by ossama0808** [comment] 2020-10-02 19:17
> This issue is still there in Flutter 1.22 and Dart 2.10 (at least in the Mac version)

me too, any way to fix this?

**Comment by holivieri** [comment] 2020-10-02 19:48
I just run "flutter downgrade". flutter clean, close and open VS again. It works with the previous version

**Comment by Shakle** [comment] 2020-10-02 23:45
Bug exists on stable 1.22

**Comment by adesege** [comment] 2020-10-02 23:53
Experienced the same issue but restarting Android Studio solves it for me @holivieri @ossama0808 @Shakle

**Comment by Shakle** [comment] 2020-10-02 23:54
> Experienced the same issue but restarting Android Studio solves it for me @holivieri @ossama0808 @Shakle

Couple of restarts + flutter clean indeed helped

**Comment by Beautylivery** [comment] 2020-10-03 01:43
Same issue here , also some vsync stuff on top. 
Flutter Clean and Restart VS Code solved it.

**Comment by Deepankar1993** [comment] 2020-10-03 04:58
I had the same issue and their info is correct its something related to the new null safety 
for new the solution is 
```
$ flutter upgrade
$ flutter clean 
```
and then restart Android Studio or VS code whichever IDE you are using

**Comment by apple-creator** [comment] 2020-10-05 07:41
> Ah nice, I'm on master, but also had to `flutter clean` _and then_ restart VS Code, and now it has gone away for me, too.

Worked for me. Thanks

**Comment by gmarimo** [comment] 2020-10-15 05:45
I recently upgraded to `flutter 1.22.1` and that issue started to show on my existing project so I ran `flutter clean` and restarted VS Code and the error disappeared!

**Comment by dpkswn4** [comment] 2020-10-19 07:39
run `flutter clean` and restart IDE

**Comment by EdvaldoMartins** [comment] 2020-10-19 11:34
I was also having this problem after having upgraded to the new version of flutter my mistake was not having updated the plugins too and after doing so the situation was overtaken.

**Comment by Djamel96** [comment] 2020-10-20 11:22
I uninstalled the flutter plugin and installed it again from the vscode extension, reload the vscode and it works

**Comment by NaseerUllahAwan** [comment] 2020-10-23 06:28
> Ah nice, I'm on master, but also had to `flutter clean` _and then_ restart VS Code, and now it has gone away for me, too.

gOOD...wORKED FOR ME

**Comment by waikyaw9999** [comment] 2020-10-25 14:36
> Ah nice, I'm on master, but also had to `flutter clean` _and then_ restart VS Code, and now it has gone away for me, too.

this works for me. 👍

**Comment by waynermaia** [comment] 2020-11-01 03:58
This works for me. 🥇

**Comment by waynermaia** [comment] 2020-11-01 03:58
> I had the same issue and their info is correct its something related to the new null safety
> for me the solution is
> 
> ```
> $ flutter upgrade
> $ flutter clean 
> ```
> 
> and then restart Android Studio or VS code whichever IDE you are using

This works for me. 🥇

**Comment by rvsingh011** [comment] 2020-11-08 17:57
Restart worked for me.

**Comment by chaochaox1990** [comment] 2020-11-11 09:14
Restart worked for me.

**Comment by adgrover** [comment] 2020-11-18 08:54
Same here. Using Android Studio on MacOS and cleaning and restarting the IDE worked it out for me.

I think we can close this ticket for now.

**Comment by KhBrahim** [comment] 2020-11-20 11:59
in your pubspec.yml change this to :
environment:
  sdk: ">=2.8.0 <3.0.0"

and flutter pub get

**Comment by KhBrahim** [comment] 2020-11-20 12:00
in your pubspec.yml change this to :
environment:
  sdk: ">=2.8.0 <3.0.0"

and flutter pub get

**Comment by barak-innov** [comment] 2021-01-30 21:01
> Ah nice, I'm on master, but also had to `flutter clean` _and then_ restart VS Code, and now it has gone away for me, too.

Work for me
