### ISSUE TITLE
Flutter should warn, when a final field is modified that doesn't have an impact on hot-reload.

### ISSUE THREAD

**Issue by floitschG** [flutter/flutter#10486] opened 2017-06-03 15:06 UTC
## Steps to Reproduce

Create a static final:
``` dart
final sampleLocks = [
  new Lock("L1", 5.0, "flo"),
  new Lock("L2", 2.5, "flo"),
  new Lock("L3", 4.0, "chris"),
  new Lock("L4", 1.1, "flo"),
  new Lock("L5", 4.2, "chris"),
];
```

Modify it (changing the individual numbers).
Do a hot reload.

Due to limitations of the VM, the value is not updated in the program, and the hot reload "doesn't work".
There should be a warning somewhere, that a static final has been updated and that the hot-reload will not necessarily take these changes into account.

**Comment by eseidelGoogle** [comment] 2017-06-03 15:13
No immediately clear which subsystem would print the error. (@a-siva or @Hixie would have opinions I'm sure.) . But I suspect once we sort that out it should be straightforward to add things like this.

And yes, trying hard not to confuse the user is definitely the goal. :)

**Comment by Hixie** [comment] 2017-06-04 05:36
I'm not sure how we could detect this. Technically, for example, this static final changes its "initial value" every time you hot reload:

```dart
final foo = new Object();
```

...but I'm sure we shouldn't warn about it...

**Comment by eseidelGoogle** [comment] 2017-06-04 17:24
I believe the user cares about *code they changed* and whether it will be manifested in the hot reload.  Presumably we can know that?

**Comment by Hixie** [comment] 2017-06-04 17:56
```dart
  const foo = 1;
  final bar = foo;
```

Now change `foo` to `2`. Did `bar` change?

Constants do get reupdated (so e.g. `print(foo)` will print 2, while `print(bar)` will print 1). What should we do? Why?

**Comment by floitschG** [comment] 2017-06-06 11:28
There are certainly things that are hard to detect, but when I change the RHS of a `final` expression, it's reasonable that I wanted to change the value and that I expect the new changes to show up after a hot reload. In these cases, there could be a hint/information/warning that I might need to do a full reload to see them.

**Comment by DanTup** [comment] 2017-06-11 15:35
I raised this with some additional comments in #10620. When testing hot reload I was modifying the `main` method in the `hello_world` sample and it seemed like it wasn't working. Presumably this would be easy to detect and warn.

I'd like the debugger `Restart` button in Dart Code do a hot reload but fall back to a restart if it doesn't work, but currently it's not possible (which means the restart button just looks buggy).

**Comment by a-siva** [comment] 2017-09-28 18:07
Marking this as a duplicate of #12300 and closing.

**Closed by a-siva** 2017-09-28 18:07 UTC
Labels: dev: tool - reload
