### ISSUE TITLE
'flutter run' doesn't rebuild the app if it's changed

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#7014] opened 2016-11-24 22:36 UTC
cc @johnmccutchan

**Comment by abarth** [comment] 2016-11-30 17:57
Do we know what needs to change here?

**Comment by johnmccutchan** [comment] 2016-11-30 18:25
AFAIK this has never worked reliably. My work flow is often `rm -rf build && flutte run`

**Comment by johnmccutchan** [comment] 2016-11-30 18:30
@abarth To answer your question we need dependency tracking and a check before running to see if any of the source files / assets are newer than the APK/IPA.

**Comment by johnmccutchan** [comment] 2016-11-30 18:31
One possible solution I've considered is having flutter tools generate a BUILD.gn for the application and then rely on ninja for dependency tracking and building.

**Comment by chinmaygarde** [comment] 2016-11-30 20:00
I doubt we can rely on the user having GN or ninja on their systems.

**Comment by Hixie** [comment] 2016-11-30 20:50
This used to work fine. There is code that verifies if the snapshot needs to be rebuilt or if the assets are changed, etc. It just got disconnected at some point recently.

**Comment by Hixie** [comment] 2016-11-30 20:51
cc @devoncarew who might know more

**Comment by johnmccutchan** [comment] 2016-11-30 21:24
@chinmaygarde I was thinking that we would download them from cloud storage so that we can rely on them being present.

**Comment by Hixie** [comment] 2016-12-08 21:04
Maybe we always rebuilt unconditionally before?

In any case, the `flutter run`; edit; `flutter run` workflow absolutely must work or people are going to be pulling their hair out. This used to work, and doesn't work now. We should fix that ASAP. :-)

**Comment by johnmccutchan** [comment] 2016-12-08 23:35
I don't know how this ever worked. I traced it to `_needsRebuild` in `build_apk.dart`. This function is returning false all the time. 

It's not surprising because, `_needsRebuild` receives the list of assets, apk, and the AndroidManifest and checks if anything has been modified *after* the APK was built. There are no checks if any Dart sources have been modified. In fact there is even a really old and wrong comment explaining why:

```dart
  // Note: This list of dependencies is imperfect, but will do for now. We
  // purposely don't include the .dart files, because we can load those
  // over the network without needing to rebuild (at least on Android).
```

**Comment by devoncarew** [comment] 2016-12-09 00:10
If I recall correctly, we would check a few files to see if the native portion of the app had to be rebuilt - if we had to build a new APK. We would then always re-snapshot - and send that over to the device separately - but that was fast enough that we still had a quick turn-around time.

> Maybe we always rebuilt unconditionally before?

So, yeah, I think that was the case at least for the dart files.

**Comment by Hixie** [comment] 2016-12-09 00:22
It should be relatively easy to just crawl all the .dart files and see if any of them are newer than the last snapshot, right?

**Comment by apwilson** [comment] 2016-12-14 17:13
I hit this yesterday after a long hiatus from flutter on android.  As @Hixie says, this used to work.  And I think its super important that it works as otherwise it's just weird behaviour.

**Comment by abarth** [comment] 2017-01-03 18:19
@johnmccutchan Should we close this issue now that your patch has landed?

**Comment by Hixie** [comment] 2017-01-04 01:35
It doesn't seem fixed? I think I'm at tip of tree but I just saw this.

**Comment by Hixie** [comment] 2017-01-04 01:36
Specifically, my steps to reproduce were, run `flutter run`. Make some changes. Do a `R` reload to confirm they have taken effect. ^C, rerun `flutter run`, changes have gone away, app doesn't get rebuilt. Pressing `R` does show them again.

**Comment by johnmccutchan** [comment] 2017-01-04 16:41
@abarth @Hixie I haven't actually wired up the dependency checker. I'll be working on finishing this work this week.

**Comment by Hixie** [comment] 2017-01-04 20:49
Ah, awesome. Thanks for doing this!

**Closed** 2017-01-10 15:59 UTC
Labels: dev: tool, old: dev experience (tell Hixie today if you don't want this label deleted), regression

**Comment by AlBiNoS14** [comment] 2018-04-30 09:50
More than a year later, this problem still exist...
I was following the "Getting Started", doing the "startup_namer" app. I copy/paste the code from the example, Ctrl+S , reloaded but the code still the "Hello World" from the start.

I'm using Flutter with Visual Studio Code, does anyone have the solution for my problem ?

**Comment by Hixie** [comment] 2018-04-30 15:40
@AlBiNoS14 can you file a new bug that includes precise steps for reproducing this? Thanks

**Comment by Hixie** [comment] 2018-05-08 05:43
If you run into this please file a new bug with explicit steps that show how to reproduce it.

**Comment by javadbat** [comment] 2018-05-08 07:06
https://stackoverflow.com/questions/49695393/flutter-build-apk-create-old-version-app/49695394#49695394

**Comment by eturk1** [comment] 2018-05-09 05:32
on Windows, haven't found exactly when it stops rebuilding.

The symptom that indicates the failure is stopping at a breakpoint and secondary window with the file opens which is read only and does NOT show recent edits.

i.e. set a breakpoint in main.dart
execute to breakpoint, a copy of main.dart now open (it's failed, old code) with path \main.dart
writable code window labeled as lib\main.dart (shows current code)

seems deleting build\app\intermediates is enough to get a correct rebuild

**Comment by zoechi** [comment] 2018-06-12 05:15
@eturk1 please create a new issue with `flutter doctor` output and all other information you can provide to allow to reproduce.
Closed issues aren't monitored.

**Comment by lukepighetti** [comment] 2018-06-18 21:00
VSC debug auto hot reloads on file save no problems. But `flutter run` does not. Am I missing an argument of some kind?

**Comment by zoechi** [comment] 2018-06-19 02:56
@lukepighetti I'd assume auto hot reload is an IDE feature, not a `flutter` feature.

**Comment by lukepighetti** [comment] 2018-06-19 21:40
This issue seems to be related to `flutter run` having the same functionality. Did it, or does it, have the same functionality?

**Comment by zoechi** [comment] 2018-06-20 03:49
@lukepighetti I see what you mean. I'd assume that requires a command option because in the IDE Flutter plugin this can be enabled/disabled.

**Comment by lvillatoro** [comment] 2018-10-26 15:44
Hello. I got the same issue even when i create new flutter projects. Every time a want to see the changes i need to delete de build folder and then re-run the app.

**Comment by eturk1** [comment] 2018-10-26 18:57
I found you can just delete build\app\intermediates. 

Also found it's much worse when debugging. Just changing one line of code could cause failure, noted when debugging read-only window opens and codee is old.

(I'm on Windows. Is this happening on all platforms?)

**Comment by lvillatoro** [comment] 2018-10-26 19:06
Im on Windows too, using Android Studio and Visual Code, same problem in both  IDEs
