### ISSUE TITLE
Table builder with listview.builder features

### ISSUE THREAD

**Issue by nikesh03** [flutter/flutter#49767] opened 2020-01-30 06:41 UTC
Need a table builder with features of listview.builder . The cells should be created on demand rather them loading all together . This would improve the performance by lot . 

Some additional Features 
* Fixed first column and row for better readability
* Row and columns highlight 
* Search functionality to recreate table with the rows which has the search result data
* Bidirectional scrolling 
* Cell alignment when scrolling stops to adjust to the nearest cell .

**Comment by iapicca** [comment] 2020-01-30 08:46
Hi @nikesh03 
are you referring to [Table](https://api.flutter.dev/flutter/widgets/Table-class.html) or [DataTable](https://api.flutter.dev/flutter/material/DataTable-class.html)?

I'm quite sure some of the features you are describing are already available 
(example: row "highlight" could be `selected: true`) 
could you describe your proposed features more in details
and how would improve the Widget
(example: fixed first row/column)

Thank you

**Comment by SHRJamal** [comment] 2020-01-30 09:34
I think the current DataTable performance is not good when you have a table with hundreds of rows.
I used pagination but UI freeze when you go from page to page.
My case was showing a table that has more than 30k rows, used pagination of 10, 50, 100.
Also, there is this problem of the first Column not being fixed.

Thanks.

**Comment by n1k3sh** [comment] 2020-01-30 14:34
DataTable with many columns and rows , flutter loads them very slow . The main feature i am looking is for cells to be loaded when required just like listview.builder . This will definitely improve performance and user experience . 

Fixed Sticky Header
With the tables having more rows and columns , it becomes difficult to track which data is under what heading . with having fixed header and first column , more and more users will find it easy to read tables and thus increasing their usability . 

Search Function 
Using search function data can be sorted according to user needs . Let the table be recreated with the search query rows . 

Bidirectional scrolling . 
Current tables only allow scrolling in one direction . This in turn consumes lot of time . It would be easier and simpler to allow user to scroll in any direction . If we could also get the cells to adjust to the nearest cell in viewport . 

More can be added .

**Comment by nikesh03** [comment] 2020-01-30 21:25
DataTable with many columns and rows , flutter loads them very slow . The main feature i am looking is for cells to be loaded when required just like listview.builder . This will definitely improve performance and user experience .

Fixed Sticky Header
With the tables having more rows and columns , it becomes difficult to track which data is under what heading . with having fixed header and first column , more and more users will find it easy to read tables and thus increasing their usability .

Search Function
Using search function data can be sorted according to user needs . Let the table be recreated with the search query rows .

Bidirectional scrolling .
Current tables only allow scrolling in one direction . This in turn consumes lot of time . It would be easier and simpler to allow user to scroll in any direction . If we could also get the cells to adjust to the nearest cell in viewport .

More can be added .

**Comment by nikesh03** [comment] 2020-02-04 13:06
Is anyone planning for this ?

**Comment by n1k3sh** [comment] 2020-02-28 19:43
need this on priority basis

**Comment by nikesh03** [comment] 2020-03-16 19:27
i dont know if flutter community is planning this or not ?

**Comment by iapicca** [comment] 2020-05-13 10:57
https://github.com/flutter/flutter/issues/56079

**Comment by n1k3sh** [comment] 2020-05-21 06:17
atleast someone give this a push , waiting forever .

**Comment by n1k3sh** [comment] 2020-05-22 14:04
bump 2

**Comment by n1k3sh** [comment] 2020-05-24 01:31
Bump 3

**Comment by n1k3sh** [comment] 2020-05-25 00:30
bump 4

**Comment by n1k3sh** [comment] 2020-05-26 06:42
bump 5

**Comment by hillelcoren** [comment] 2020-05-26 06:44
@n1k3sh please try to be respectful to other people subscribed to this issue

**Comment by aguilaair** [comment] 2020-11-16 19:35
Would love to see this. Right now what would be the suggested workaround?

Thanks!

**Comment by Patrick386** [comment] 2021-11-26 05:45
Datatable in flutter web is very slow. Looking forward to the Datatable Builder quick addition.

**Comment by Piinks** [comment] 2022-11-29 00:22
I am going to close this as a duplicate of https://github.com/flutter/flutter/issues/87370, since that one has more up votes currently. I have been collecting these issues in the 2D Scrolling project for reference: https://github.com/orgs/flutter/projects/32/views/1 This work in currently underway.

**Closed by Piinks** 2022-11-29 00:22 UTC
Labels: new feature, framework, f: material design, customer: crowd, proposal, P3
