### ISSUE TITLE
tiles_scroll_perf throws exception during driver test

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26724] opened 2019-01-17 22:55 UTC
```
flutter drive test_driver/scroll_perf.dart 
Using device Pixel 2 XL.
Starting application: test_driver/scroll_perf.dart
Initializing gradle...                                              0.7s
Resolving dependencies...                                           6.8s
Installing build/app/outputs/apk/app.apk...                        15.1s
Running Gradle task 'assembleDebug'...                             16.7s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         4.2s
I/flutter ( 9926): Observatory listening on http://127.0.0.1:37554/
00:00 +0: scrolling performance test (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:44261/
[trace] FlutterDriver: Isolate found with number: 320410179
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:01 +0: scrolling performance test complex_layout_scroll_perf
00:14 +1: scrolling performance test tiles_scroll_perf
I/flutter ( 9926): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9926): The following assertion was thrown while finalizing the widget tree:
I/flutter ( 9926): setState() or markNeedsBuild() called when widget tree was locked.
I/flutter ( 9926): This _ModalScope<dynamic> widget cannot be marked as needing to build because the framework is
I/flutter ( 9926): locked.
I/flutter ( 9926): The widget on which setState() or markNeedsBuild() was called was:
I/flutter ( 9926):   _ModalScope<dynamic>-[LabeledGlobalKey<_ModalScopeState<dynamic>>#ec33d](state:
I/flutter ( 9926):   _ModalScopeState<dynamic>#2bc81)
I/flutter ( 9926):
I/flutter ( 9926): When the exception was thrown, this was the stack:
I/flutter ( 9926): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3502:9)
I/flutter ( 9926): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3511:6)
I/flutter ( 9926): #2      State.setState (package:flutter/src/widgets/framework.dart:1146:14)
I/flutter ( 9926): #3      _ModalScopeState._routeSetState (package:flutter/src/widgets/routes.dart:623:5)
I/flutter ( 9926): #4      ModalRoute.setState (package:flutter/src/widgets/routes.dart:722:30)
I/flutter ( 9926): #5      ModalRoute.changedInternalState (package:flutter/src/widgets/routes.dart:1193:5)
I/flutter ( 9926): #6      _ModalRoute&TransitionRoute&LocalHistoryRoute.removeLocalHistoryEntry (package:flutter/src/widgets/routes.dart:507:7)
I/flutter ( 9926): #7      LocalHistoryEntry.remove (package:flutter/src/widgets/routes.dart:338:12)
I/flutter ( 9926): #8      DrawerControllerState.dispose (package:flutter/src/material/drawer.dart:241:20)
I/flutter ( 9926): #9      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3900:12)
I/flutter ( 9926): #10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1709:13)
I/flutter ( 9926): #11     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 9926): #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 9926): #13     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 9926): #14     _InactiveElements._unmount.<anonymous closure>
...
I/flutter ( 9926): #51     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 9926): #52     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 9926): #53     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1707:7)
I/flutter ( 9926): #54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter ( 9926): #55     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1705:13)
I/flutter ( 9926): #56     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter ( 9926): #57     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1718:25)
I/flutter ( 9926): #58     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2372:27)
I/flutter ( 9926): #59     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2204:15)
I/flutter ( 9926): #60     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2371:7)
I/flutter ( 9926): #61     __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding&GestureBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:690:18)
I/flutter ( 9926): #62     __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding&GestureBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 9926): #63     __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 9926): #64     __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 9926): #65     __DriverBinding&BindingBase&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 9926): #66     _invoke (dart:ui/hooks.dart:173:13)
I/flutter ( 9926): #67     _drawFrame (dart:ui/hooks.dart:162:3)
I/flutter ( 9926): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 9926): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3473 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
00:26 +2: scrolling performance test (tearDownAll)
00:26 +2: All tests passed!
Stopping application instance.
```

See also https://github.com/flutter/flutter/issues/6256

**Comment by HansMuller** [comment] 2019-01-18 16:43
This appears to be the same swan song as was reported here: https://github.com/flutter/flutter/issues/25047

As with that bug, it looks like the demo needs to close its drawer or risk having the local history update occur after the drawer has been removed from the tree.

**Comment by HansMuller** [comment] 2019-01-18 17:44
The error is easy to reproduce by running the benchmark interactively: just tap the "Tile" below the Drawer's header.

Popping the navigator (dismissing the drawer), fixes the problem.

**Closed** 2019-01-18 20:44 UTC
Labels: a: tests, framework, severe: crash, team
