### ISSUE TITLE
Should not draw outside bounds

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#33855] opened 2019-06-04 17:26 UTC
We should never pass an elevation to Scenic that is greater than the max elevation it gave us.

**Comment by mklim** [comment] 2019-06-21 01:21
The above PR should be enough of a fix for this, but I was seeing what looks like Scenic clipping us based on our world space position instead of our position relative from the root ViewHolder with our bounding box. From preliminary offline discussions it sounds like that's unintended behavior on Scenic's part, but there may be followup work here if that turns out to not be a Scenic bug after all. Going to leave this open until that's confirmed.

**Comment by mklim** [comment] 2019-06-25 22:37
The remaining offset I was seeing isn't a problem within flutter itself. It's a minor bug from how the bounds are set in `tiles.cc` and should be resolved there once [296090](https://fuchsia-review.googlesource.com/c/fuchsia/+/296090) lands.

**Closed by mklim** 2019-06-25 22:37 UTC
Labels: customer: fuchsia, engine, severe: customer critical, ○ platform-fuchsia
