### ISSUE TITLE
Focus might not handle child order change

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#38644] opened 2019-08-15 20:27 UTC
I suspect based on discussions that if you have this kind of setup:

```
        Focusable widget
               |
              ...
               |
              Row
               |
           +---+---+
           |   |   |
         ...  ...  ...
           |   |   |
           A   B   C
```
...where A, B, and C are focusable, and then you focus B, and then you cause the tree to become:
```
        Focusable widget
               |
              ...
               |
              Row
               |
           +---+---+
           |   |   |
         ...  ...  ...
           |   |   |
           C   B   A
```

...by only rebuilding the Row, and then you hit Tab, the focus will go to C, not A.

cc @gspencergoog

**Comment by gspencergoog** [comment] 2019-08-15 20:31
This implies that `WidgetOrderTraversalPolicy` might need to be reimplemented to traverse the element tree instead of the focus node tree in order to find the next element to be focused.

And if that's the case, then it might be possible to flatten the focus node tree so that only `FocusScope`s have children.

**Comment by gspencergoog** [comment] 2019-08-15 20:32
Except that might not be possible (to reimplement using the element tree), since the element tree has no idea if a particular element is hosting a focus node (other than the `Focus` and `FocusScope` widgets themselves).

**Comment by Hixie** [comment] 2019-08-15 23:12
Can you have a `Set` that contains all the `BuildContext`s of `FocusNode`s?

**Comment by gspencergoog** [comment] 2019-08-16 17:57
Yes, we could, but one other thing occurred to me: we can't flatten the focus node tree because it uses that for distributing key events up the parent hierarchy, and it means that a widget that is a descendent of another being focused doesn't imply that the ancestor is also focused: right now the focused widget has `hasPrimaryFocus` set to true, but all of its ancestors have `hasFocus` set to true as well, and if the tree were flattened, that would only be true for scopes, not other nodes.

**Comment by Hixie** [comment] 2019-08-18 00:22
What's the use case for nested focus nodes both looking at the same key events?

**Comment by gspencergoog** [comment] 2019-08-18 00:46
For instance, the `Shortcuts` widget has a Focus node that that listens to keys pressed when its children have focus to see if it should handle the shortcut for them.

**Comment by Hixie** [comment] 2019-08-18 02:21
That's a solution, not a use case. :-)

**Comment by gspencergoog** [comment] 2019-08-19 15:53
Yes, OK.  But there are associated problems that it solves:

The reason we use the hierarchy of nodes to handle keys is so that it isn't necessary to redefine or at least refer to the key bindings at every widget (or in a global handler), so they can be defined (and re-defined) at the container level to do things specific to that UI arena.

A specific example would be a dialog that wants to define the ESC key as a way to get out of the dialog, even if a control within it is focused. As long as the control with focus is a child of the dialog, it will receive the event and handle it.

Another would be in order to define the LEFT ARROW key as the key to move to the next control to the left in a way that can be overridden. It can be defined at the app level so that it covers the entire app by default without having to redefine it for every single control in the app, or with a global key handler. Then, if a particular region of the UI wants to override that behavior, it can, just by redefining the key binding.

Without the hierarchy, the key bindings need to be defined, or at least referred to, at each control, or there has to be complex logic in a global handler to know where to apply it.

**Comment by gspencergoog** [comment] 2019-08-19 16:11
In any case, I think it's possible to re-implement the traversal code to use the element hierarchy instead, since we could (as you pointed out), have a set that contains all of the elements in the focus tree, and just look up each element as it's traversed to see if it's in the set.

**Comment by markusaksli-nc** [comment] 2020-08-13 13:23
I can't reproduce a case for this based on the description on the latest master `1.21.0-8.0.pre.176`.
<details>
 <summary>Used test case</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(FocusTest());

class FocusTest extends StatefulWidget {
  @override
  _FocusTestState createState() => _FocusTestState();
}

class _FocusTestState extends State<FocusTest> {
  @override
  Widget build(BuildContext context) {
    print('parent rebuild');
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Container(
          child: Center(
            child: SingleChildScrollView(
              child: FocusColumn(),
            ),
          ),
        ),
      ),
    );
  }
}

class FocusColumn extends StatefulWidget {
  static _FocusColumnState instance = _FocusColumnState();

  @override
  _FocusColumnState createState() => instance;
}

class _FocusColumnState extends State<FocusColumn> {
  final items = List<Container>.generate(
      5,
      (index) => Container(
            width: 100,
            decoration: BoxDecoration(
              border: Border.all(),
            ),
            child: TextFormField(
              initialValue: index.toString(),
              key: GlobalKey(),
              onChanged: (_) => FocusColumn.instance.shuffleStuff(),
            ),
          ));

  void shuffleStuff() {
    setState(() {
      items.shuffle();
    });
  }

  @override
  Widget build(BuildContext context) {
    print('Row rebuild');
    return Row(children: items);
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-8.0.pre.176, on Microsoft Windows [Version 10.0.19041.388], locale en-US)
    • Flutter version 1.21.0-8.0.pre.176 at C:\Development\flutter_master
    • Framework revision d9637ed784 (3 hours ago), 2020-08-11 23:51:03 -0400
    • Engine revision 6381b1511b
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.388]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```
</details>

Has this been fixed and can the issue be closed?

**Comment by darshankawar** [comment] 2022-11-09 12:48
Using the code sample provided above, I was unable to replicate the behavior mentioned in original issue, so I am going ahead and closing this issue as not replicable. If anybody disagrees, please write in comments and I'll reopen it.

**Closed by darshankawar** 2022-11-09 12:48 UTC
Labels: framework, f: focus, has reproducible steps, P4, found in release: 1.21
