### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by viztushar** [flutter/flutter#78342] opened 2021-03-16 17:26 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```

```
```
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale en-IN)
    • Flutter version 2.0.1 
    • Framework revision c5a4b4029c (12 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK 
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008030-0009490E01D2802E • ios            • iOS 14.4.1
    • macOS (desktop)          • macos                     • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 89.0.4389.82
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when  iPhone is finished. (code -10)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f
### Plugins
firebase_core-0.5.0
firebase_core_web-0.2.0
firebase_messaging-7.0.0
path_provider-1.6.8
path_provider_macos-0.0.4+2
sqflite-1.3.0+1
url_launcher-5.4.10
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.1+6
video_player-0.10.11+2
video_player_web-0.1.3+1
wakelock-0.1.4+1
whatsapp_stickers-0.0.4

**Comment by iapicca** [comment] 2021-03-16 18:57
possible duplicate of https://github.com/flutter/flutter/issues/78099

**Comment by pedromassangocode** [comment] 2021-03-16 20:44
Closing as duplicate of https://github.com/flutter/flutter/issues/78099.

**Closed by pedromassangocode** 2021-03-16 20:44 UTC
Labels: in triage
