### ISSUE TITLE
Add a wait for the device to be ready before allowing uninstall of app

### ISSUE THREAD

**Issue by ricardoamador** [flutter/flutter#121420] opened 2023-02-24 19:06 UTC
There are times when the device will crash because the device test packages are crashing the phone when force removing applications and not waiting for the device to become available.

See the following related flakes:
https://github.com/flutter/flutter/issues/120802
https://github.com/flutter/flutter/issues/120806

**Comment by godofredoc** [comment] 2023-09-13 16:21
@zanderso @christopherfujino this will require some hooks in the flutter tool as these failures happen within flutter tool calls.

**Comment by christopherfujino** [comment] 2023-09-13 17:07
Looks like the command in question is:

```
[flutter_gallery__start_up] [STDOUT] Executing "/opt/s/w/ir/x/w/recipe_cleanup/tmp46953xvl/flutter sdk/bin/flutter install --uninstall-only -d ZY223CXXGL" in "/opt/s/w/ir/x/w/recipe_cleanup/tmp46953xvl/flutter sdk/dev/integration_tests/flutter_gallery" with environment {BOT: true, LANG: en_US.UTF-8}
[flutter_gallery__start_up] [STDOUT] stdout: Uninstalling app-release.apk from Moto G 4...
```

**Comment by christopherfujino** [comment] 2023-09-13 17:09
@godofredoc what exactly does it mean for the device to "become available"? And how would we know that it is available. It looks like we're calling `flutter install` right after `flutter run` succeeded.

**Comment by christopherfujino** [comment] 2023-09-13 17:31
When I locally try to `adb uninstall non-existent-app-id` it blocks forever with the following to stderr: `- waiting for device -`. If the tool is exiting, I'm assuming it's because adb returned. However, the only error handling we have is a regex on stdout. I can update this command to trace the exitcode and stderr also.

**Comment by godofredoc** [comment] 2023-09-13 18:54
Sometimes when force uninstalling an application adb returns successfully but the device crashes after making all the subsequent adb commands fail.

In automation this is usually solved with a function adding a small delay after uninstalling the app, then pinging adb in a loop until the device becomes available or times out. Not sure how we could inject this functionality to the flutter tool for testing purposes only.

**Comment by christopherfujino** [comment] 2023-09-13 19:18
> Sometimes when force uninstalling an application adb returns successfully but the device crashes after making all the subsequent adb commands fail.
> 
> In automation this is usually solved with a function adding a small delay after uninstalling the app, then pinging adb in a loop until the device becomes available or times out. Not sure how we could inject this functionality to the flutter tool for testing purposes only.

Ahh, I see, the issue is not with uninstalling, but with the run AFTER the uninstall, do I have this right?

**Comment by christopherfujino** [comment] 2023-09-13 19:21
And we can do this delay in https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L961, right after the `flutter install --uninstall-only` call and before the `for` loop repeats.

**Comment by godofredoc** [comment] 2023-09-14 18:15
Right, if we can uninstall and install the app separately that will give us the ability to implement `await_availabilty` in the device lab class.

Here is a good example: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8769958206160447377/+/u/run_flutter_gallery__start_up/test_stdout

```
[2023-09-14 10:47:33.911482] [STDOUT] stdout: [  +16 ms] executing: /opt/s/w/ir/cache/android/sdk/platform-tools/adb version
[2023-09-14 10:47:33.918620] [STDOUT] stdout: [   +7 ms] Android Debug Bridge version 1.0.41
[2023-09-14 10:47:33.918674] [STDOUT] stdout:            Version 33.0.2-8557947
[2023-09-14 10:47:33.918693] [STDOUT] stdout:            Installed as /opt/s/w/ir/cache/android/sdk/platform-tools/adb
[2023-09-14 10:47:33.921184] [STDOUT] stdout: [   +2 ms] executing: /opt/s/w/ir/cache/android/sdk/platform-tools/adb start-server
[2023-09-14 10:47:33.929381] [STDOUT] stdout: [   +8 ms] Stopping app 'app-profile.apk' on Moto G 4.
[2023-09-14 10:47:33.930941] [STDOUT] stdout: [   +1 ms] executing: /opt/s/w/ir/cache/android/sdk/platform-tools/adb -s ZY223D6B7B shell am force-stop io.flutter.demo.gallery
```
Await_availability

```
[2023-09-14 10:47:34.837739] [STDOUT] stdout: [ +906 ms] executing: /opt/s/w/ir/cache/android/sdk/platform-tools/adb -s ZY223D6B7B shell pm list packages io.flutter.demo.gallery
[2023-09-14 10:47:35.769431] [STDOUT] stdout: [ +932 ms] Installing APK.
````

**Comment by christopherfujino** [comment] 2023-09-14 19:41
> Right, if we can uninstall and install the app separately that will give us the ability to implement `await_availabilty` in the device lab class.

Right, this is how it works today. We uninstall at line 961: https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L961

We loop back to the start of the for loop at line 913: https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L913

And then we do the install as part of hte run at line 923: https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L923

**Comment by godofredoc** [comment] 2023-09-14 19:50
Isn't https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L923 the one running `shell am force-stop io.flutter.demo.gallery`?

**Comment by christopherfujino** [comment] 2023-09-14 20:50
> Isn't https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart#L923 the one running `shell am force-stop io.flutter.demo.gallery`?

Right. So, as I see it, the flow of the StartupTest from https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/tasks/perf_tests.dart is roughly:

1. `flutter build ...` the app (lines 850-909)
2. start a for loop with iterations = 5 (line 913)
3. `flutter run ...` the app that was built in step 1, this will also install the app on the device (line 923)
4. check exit code of step 3
  a. if exit code is 0, decode the results json file that was generated and append it to the results list
  b. if exit code is not 0, decrement our iterator - 1 (essentially re-run this loop), increment failure count, fail task if we hit max failures
5. uninstall the app (line 961)
6. end of loop, return to step 2 (line 966)

If I'm understanding the issue correctly, it is that step 5 succeeds, however, when we loop back to around and hit step 3, it fails because the device is not yet ready? If so, we could add a delay and poll after step 5 to ensure the device is ready.

However, in looking at https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8769958206160447377/+/u/run_flutter_gallery__start_up/test_stdout, it looks like the actual failure cause was:

```
adb: failed to install /opt/s/w/ir/x/w/recipe_cleanup/tmpqq1xk4w0/flutter sdk/dev/integration_tests/flutter_gallery/build/app/outputs/flutter-apk/app-profile.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE: Package couldn't be installed in /data/app/io.flutter.demo.gallery-1: Creating application package io.flutter.demo.gallery failed]
```

**Comment by godofredoc** [comment] 2023-09-14 21:06
You're right https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8769958206160447377/+/u/run_flutter_gallery__start_up/test_stdout is probably a bad example as it is failing for something different. 

The issue that I've seen causing a lot of flakiness is when `shell am force-stop ...` crashes the phone and the additional adb commands of line 923 fail. In those cases just checking the healthiness rather than going through a whole iteration will be more effective.

For the issue in https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8769958206160447377/+/u/run_flutter_gallery__start_up/test_stdout, is there a way to enforce a single namespace for all the testing apps? my assumption is that new apps have been added with namespaces that are not being deleted by device_doctor.

**Comment by christopherfujino** [comment] 2023-09-14 22:34
> You're right https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8769958206160447377/+/u/run_flutter_gallery__start_up/test_stdout is probably a bad example as it is failing for something different.
> 
> The issue that I've seen causing a lot of flakiness is when `shell am force-stop ...` crashes the phone and the additional adb commands of line 923 fail. In those cases just checking the healthiness rather than going through a whole iteration will be more effective.

Ok, so after we call `force-stop`, we then call `adb shell pm list packages $appId`: https://github.com/christopherfujino/flutter/blob/build-web-no-o0/packages/flutter_tools/lib/src/android/android_device.dart#L382. I wonder what happens in this case if the device is not ready? The bug here could be that we're not handling that case properly.

> For the issue in https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8769958206160447377/+/u/run_flutter_gallery__start_up/test_stdout, is there a way to enforce a single namespace for all the testing apps? my assumption is that new apps have been added with namespaces that are not being deleted by device_doctor.

The only way I can think of to enforce this is to write a script that checks the app name of all the flutter projects in the repo. AFAIK the tool doesn't control this, but the actual generated android config files do: https://github.com/eliasyishak/flutter/blob/use-same-analytics-logic-as-pkg-usage/dev/integration_tests/flutter_gallery/android/app/build.gradle#L52

**Comment by godofredoc** [comment] 2023-09-14 23:08
Before I forget, this is the bug tracking cleaning up the devices  https://github.com/flutter/flutter/issues/134782

**Comment by zanderso** [comment] 2023-09-25 17:47
Should this be a P0? I see the installation failures causing many flakes across every Android test, frequently closing the tree. Is that aspect of this tracked elsewhere?

**Closed** 2023-09-30 01:58 UTC
Labels: team-infra, P1, triaged-infra
