### ISSUE TITLE
"flutter doctor" always downloads package from start no matter previous downloaded or not.

### ISSUE THREAD

**Issue by vestayin** [flutter/flutter#13693] opened 2017-12-20 07:32 UTC
I setup flutter environment on my MacBook via "flutter doctor" under slow and unstable network . It took hours to download all packages, darwin, android, and IOS. When I re-ran "flutter doctor" after network broke, all previous downloaded packages would be downloaded again and took another a few hours. and network broke again. I was stuck in this step many times. I'm wondering is that possible to check downloaded packages before trigger new download for flutter setup?

## Steps to Reproduce
1. Install flutter to new box.
2. Run ```flutter doctor``` to setup environment.
3. Wait for a few packages downloading and disconnect network before all packages download complete.
4. Run ```flutter doctor``` to setup environment again.
5. Existing packages were downloaded again. Wait for a few packages downloading and disconnect network before all packages download complete.
6. Repeat step 4 and 5. Flutter always downloads package from 1st one no matter it was downloaded previously or not.

I know the 3rd steps wasn't real but remember that I'm in **slow and unstable network** facility and my network broke frequently. Therefore, I used disconnect to simulate unstable network.

## Logs
No log since issue was on flutter setup.

## Flutter Doctor
$: flutter doctor
Downloading package sky_engine...                    22.7s
Downloading common tools...                          168.3s
Downloading darwin-x64 tools...                      730.0s
Downloading darwin-x64 tools...                      1113.7s
Downloading android-arm-profile/darwin-x64 tools...  97.8s
Downloading android-arm-release/darwin-x64 tools...  84.4s
Downloading android-x86 tools...                     474.9s
Downloading android-x64 tools...                     478.0s
Downloading android-arm tools...                     280.2s
Downloading android-arm-profile tools...             201.9s
Downloading android-arm-release tools...             169.0s
Downloading ios tools...                                  
Download failed -- attempting retry 1 in 1 second...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address = clients2.google.com, port = 55793
Crash report written to /Users/user/flutter/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by Hixie** [comment] 2017-12-21 20:57
We shouldn't be crashing, either.

**Comment by Hixie** [comment] 2017-12-21 20:58
Marking as current milestone since this is a first-hour issue that will affect many users.

**Comment by vestayin** [comment] 2017-12-22 14:25
Thanks for marking this in current milestone. More info that my network was very poor at that time. It will be better to add good retry for that. Even the worse case, network totally down and tool can't continue, I'm ok to receive friendly prompt for retry later and tool stop. But when I retry, those packages which had downloaded should be reused rather than download them again.

**Comment by jcollins-g** [comment] 2018-01-05 20:52
@vestayin I'm able to reproduce the problem of downloading multiple times, but not the crash.  Could you post the crash report?

**Comment by jcollins-g** [comment] 2018-01-05 21:41
Preliminary investigation and experiments suggest the crash is likely an unexpected exception from this try block; throwing something unexpected by hand there produces output like @vestayin experienced.  

https://github.com/flutter/flutter/blob/28366002d9a86ec1403764453df31580362c9097/packages/flutter_tools/lib/src/base/net.dart#L56

Without the crash report I have to guess, but given the error analytics emitted when trying to send, I'd say "SocketException" seems a good bet.  So we can trap that exception as well and continue with the retries.

For fixing the "fetch everything" problem, I think rearranging the cache so it doesn't delete the entire artifact directory whenever it fetches would be a good idea.  Alternatively, we can:

1. clear out everything except the zip
2. clear out and redownload the ZIP only if it is corrupt
3. extract the zip

I think this can be done with minimal intrusiveness to the code and should make the behavior a lot more manageable for bad connections.

**Comment by jcollins-g** [comment] 2018-01-09 19:23
Strangely, it looks like Windows bots work on the flutter-dashboard but Linux bots don't.  Will retry the fix once I learn how to launch flutter the same way cocoon does and fix the issue there.

**Comment by jcollins-g** [comment] 2018-01-10 18:14
With some help getting debug data from @yjbanov, #13693 failed because generated filenames are too long.  Ext4 encrypted filesystems have a lower ceiling (143 characters) and the collision-proof filenames we built in the cache were just over that length.   Reworking the cache's filename scheme should make this work fine.

**Closed** 2018-01-16 16:07 UTC
Labels: dev: first hour, dev: tool

**Comment by jcollins-g** [comment] 2018-01-16 18:08
Take two made it past the cocoon bots this time, so I think this is done.  Thanks for the bug report!

**Comment by lisiyizu** [comment] 2019-03-14 04:15
@vestayin  Have you solved this problem?  I had the same problem。
[https://github.com/flutter/flutter/issues/29333](https://github.com/flutter/flutter/issues/29333)

**Comment by AashiqinCode** [comment] 2020-06-26 06:19
> We shouldn't be crashing, either.

Even in >flutter run also,I first switched between channels often,it that's why?
