### ISSUE TITLE
setState() not working in list items under StatefulWidget

### ISSUE THREAD

**Issue by abdurahmanqb** [flutter/flutter#59058] opened 2020-06-09 09:03 UTC
Hi there,

There seems to be an issue with updating the StatefulWidget by clicking or tapping a list item. Based on what I've tried myself, and the similar questions that I've gone through here and on StackOverflow, `setState()` function doesn't have any effect on the widget state.

However, I tired to set the state in another widget under the same stateful, it worked just fine, and even applied the missing state update from the previous one set in the list item. This turned out for me that the issue is when updating the state in a list item specifically.

Hopefully, I can get any solution for that here.

**Comment by VladyslavBondarenko** [comment] 2020-06-09 14:54
Hi @abdurahmanqb 
could you provide your a minimal complete reproducible code sample and also your `flutter doctor -v`?

**Comment by VladyslavBondarenko** [comment] 2020-06-11 10:05
@abdurahmanqb 
This is intended behaviour, see https://github.com/flutter/flutter/issues/56998#issuecomment-628220674.
Avoid making your state depend on static variables of another widget. You can set `isActive` variable for ColumnItem or to some another way. Or you can use bloc pattern or provider or inherited widget.
May be useful https://medium.com/flutter-community/simple-ways-to-pass-to-and-share-data-with-widgets-pages-f8988534bd5b.
Closing since this is not an issue with flutter,
if you disagree please write in the comments and I will reopen it

**Closed by VladyslavBondarenko** 2020-06-11 10:05 UTC
Labels: in triage

**Comment by abdurahmanqb** [comment] 2020-06-11 10:18
@VladyslavBondarenko 
Thanks for the clarification, but indirect set of the state by calling it from another context solved the issue and got the correct value of the static variable. That means there's no issue with the static variable itself, but from where `setState()` was called!

Hopefully that makes sense.
