### ISSUE TITLE
After iOS is upgraded to 17, TextField cannot be entered on the keyboard.

### ISSUE THREAD

**Issue by wuwenwei5566** [flutter/flutter#133962] opened 2023-09-04 02:38 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Create a TextField and run it on iOS 17.0
![1693794127](https://github.com/flutter/flutter/assets/52393077/9138928e-0d8f-4466-8034-ed25b7b6ff40)

### Expected results

Normal input

### Actual results

Unable to enter normally

### Code sample

 TextField(
          autofocus: widget.autofocus,
          textAlign: widget.textAlign,
          controller: widget.controller,
          keyboardAppearance: widget.keyboardAppearance ?? _checkThemeDrak(),
          focusNode: widget.focusNode,
          scrollController: widget.scrollController,
          keyboardType: widget.keyboardType,
          textInputAction: widget.textInputAction,
          scrollPhysics: widget.scrollPhysics,
          selectionControls: widget.selectionControls,
          maxLines: widget.maxLines,
          maxLength: widget.maxLength,
          minLines: widget.minLines,
          cursorHeight: setCursorHeight(),
          cursorColor: widget.cursorColor ?? ThemeColor.themeColor(context),
          style: widget.style,
          enableInteractiveSelection: widget.enableInteractiveSelection,
          //onTap: widget.onTap,
          decoration: widget.decoration,
          onEditingComplete: widget.onEditingComplete,
          onAppPrivateCommand: widget.onAppPrivateCommand,
          onSubmitted: widget.onSubmitted,
          onChanged: widget.onChanged,
          inputFormatters: widget.inputFormatters,
          scrollPadding: widget.scrollPadding,
          textAlignVertical: widget.textAlignVertical,
          obscureText: widget.obscureText,
          obscuringCharacter: widget.obscuringCharacter,
          readOnly: widget.readOnly,
          clipBehavior: widget.clip,
        ),

### Screenshots or Video

https://github.com/flutter/flutter/assets/52393077/f3db6ca0-3694-4d1c-ad57-becf590c7f89

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

[!] Flutter (Channel [user-branch], 3.13.2, on macOS 13.5.1 22G90 darwin-arm64, locale zh-Hans-CN)
    ! Flutter version 3.13.2 on channel [user-branch] at /Users/wuwenwei/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision ff5b5b5fa6 (11 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/wuwenwei/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone (mobile) • 48c405558758d3db34d62094c63b20477e0f2a71 • ios            • iOS 16.6 20G75
    • macOS (desktop) • macos                                    • darwin-arm64   • macOS 13.5.1 22G90 darwin-arm64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

**Comment by stuartmorgan** [comment] 2023-09-04 03:17
Closing as a duplicate of https://github.com/flutter/flutter/issues/133908

Please stop filing duplicates of this issue.

**Closed by stuartmorgan** 2023-09-04 03:17 UTC

**Comment by zhangyanzhu88** [comment] 2023-09-04 17:12
I had the same problem，Is solved？

**Comment by wuwenwei5566** [comment] 2023-09-04 23:09
> I had the same problem，Is solved？

Yes, it’s .
