### ISSUE TITLE
[tool_crash] ProcessException: Too many open files in system Command: /Users/richarddanquah/Documents/Dev/flutter/bin/cache/dart-sdk/bin/dart, OS error code: 23

### ISSUE THREAD

**Issue by richarddanquah** [flutter/flutter#71345] opened 2020-11-28 17:38 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=LGH900a54e598a --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Too many open files in system Command: /Users/richarddanquah/Documents/Dev/flutter/bin/cache/dart-sdk/bin/dart, OS error code: 23
```

```
```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-GH)
    • Flutter version 1.22.4 at /Users/richarddanquah/Documents/Dev/flutter
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/richarddanquah/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • LG H900 (mobile) • LGH900a54e598a • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1aafb3a8b9b0c36241c5f5b34ee914770f015818
### Plugins
flutter_custom_dialog-1.0.20
flutter_pdfview-1.0.3+6
flutter_plugin_android_lifecycle-1.0.11
flutter_webview_plugin-0.3.11
geolocator-6.1.7
image_cropper-1.3.1
image_picker-0.6.6+5
path_provider-1.6.24
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+6
path_provider_windows-0.0.4+3
searchable_dropdown-1.1.3
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.1+3
sqflite-1.3.2+1

**Comment by iapicca** [comment] 2020-11-28 19:00
possibly related to https://github.com/flutter/flutter/issues/2976

**Comment by Abhishek01039** [comment] 2020-11-29 05:13
Maybe the duplication of https://github.com/flutter/flutter/issues/18225

**Comment by jmagman** [comment] 2020-12-01 01:14
@richarddanquah Can we get the full stack trace from the crash, or can you attach the generated `.log` file?

**Comment by christopherfujino** [comment] 2020-12-04 20:33
I'm closing this as a duplicate of https://github.com/flutter/flutter/issues/2976. The workaround is documented on the website https://flutter.dev/docs/testing/debugging#too-many-open-files-exception-macos, basically increasing your ulimit: `ulimit -S -n 2048`

**Closed by christopherfujino** 2020-12-04 20:33 UTC
Labels: passed first triage, severe: crash, tool, waiting for customer response
