### ISSUE TITLE
[video_player] Video disappears on pause in safari

### ISSUE THREAD

**Issue by camfrandsen** [flutter/flutter#146785] opened 2024-04-15 22:46 UTC
### What package does this bug report belong to?

video_player

### What target platforms are you seeing this bug on?

Web

### Have you already upgraded your packages?

Yes

### Dependency versions

Used dart pad

### Steps to reproduce

If you press the run button in safari, the video disappears.

### Expected results

The video would stay up (like in every other browser)

### Actual results

The video disappears.

### Code sample

<details open><summary>Code sample</summary>

```dart
import "package:flutter/material.dart";
import "package:video_player/video_player.dart";
void main() => runApp(const VideoApp());
/// Stateful widget to fetch and then display video content.
class VideoApp extends StatefulWidget {
  const VideoApp({super.key});
  @override
  _VideoAppState createState() => _VideoAppState();
}
class _VideoAppState extends State<VideoApp> {
  late VideoPlayerController _controller;
  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.networkUrl(Uri.parse(
        "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",),)
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Video Demo",
      home: Scaffold(
        body: Center(
          child: _controller.value.isInitialized
              ? AspectRatio(
                  aspectRatio: _controller.value.aspectRatio,
                  child: VideoPlayer(_controller),
                )
              : Container(),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }
  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}
```

</details>

### Screenshots or Videos

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/145144088/d74e4ee4-af83-4cdb-93fe-3ed0857d9941

</details>

### Flutter Doctor output

![image](https://github.com/flutter/flutter/assets/145144088/3366206f-8750-4d0b-9f0f-6a0e34a2bf2c)
![image](https://github.com/flutter/flutter/assets/145144088/5f9dd978-8caa-4452-8b35-43acf1998869)
You can see this on dart pad

**Comment by danagbemava-nc** [comment] 2024-04-16 07:34
Hi @camfrandsen, are you only seeing this issue when you run the code sample in dart-pad? If you run the code sample locally and open the site in safari, do you see the same issue? 

Do you get any errors in your console? 

What version of Safari are you using?

**Comment by camfrandsen** [comment] 2024-04-16 20:54
Yeah, I see it notepad as well as when running normal. There is nothing in the logs... I can pause and start several times without getting anything in the logs.

I do get a warning sometimes: "WebGL: non-portable extension enabled: WEBGL_polygon_mode", but no errors.

This is on safari 17.4.1. Chrome works great on the same machine

**Comment by danagbemava-nc** [comment] 2024-04-17 06:21
Hi @camfrandsen, does this happen everytime you pause the video? I ran the code sample you provided in safari but when I pause it, it doesn't disappear. See the recording below. What renderer are you using? And would you happen to be using open core legacy patcher? 

https://github.com/flutter/flutter/assets/88313112/283a4a34-652a-4781-9fec-7e5ccaf3b0ab

**Comment by camfrandsen** [comment] 2024-04-22 19:25
Sorry I have not responded yet. I have a second project that does not show the same issue in safari and am trying to find the different. I will let you know what I find.

**Comment by camfrandsen** [comment] 2024-05-09 00:08
Alright, sorry that took so long, but I found some more information.
Using the exact same code as in the description in the dart pad, it always reproduces the issue for me. This is on Version 17.4.1 (19618.1.15.11.14).
The only way that I know how to run the code in a dev build for safari is to run ```flutter run -d chrome``` then copying the url and pointing safari to it. (If there is a better way, I would love to learn it). I then open a few tabs more tabs in safari pointing to the same url. At least one of them will show the issue. It seems like I rarely see the bug on the first tab, but I do always see it.
The interesting thing to me about this is that dart pad, I see it every time, but with a dev build, it requires several tabs running at the same time to always see it. 

A couple of notes, that second project that I thought was working, it actually wasn't, but since it was the first tab that I opened, I didn't really see it fail.

Also, I am just using the default renderer, so CanvasKit (I haven't tried safari in a mobile browser, just in a desktop browser.
Note: This is on safari from a mac-mini. Are you running with Safari from a mobile device?

**Comment by danagbemava-nc** [comment] 2024-05-09 06:07
Hi @camfrandsen, I test on `Safari` on my m1-mac. Can you try running the app with `flutter run -d web-server`? It doesn't launch chrome and you can copy the url into any browser of your choice. 


Do you experience this issue in release mode as well?

**Comment by camfrandsen** [comment] 2024-05-09 22:13
@danagbemava-nc Great idea! I just tried using ```flutter run -d web-server```, and it still reproduced the issue. 

Something else that may be the difference, is I have disabled the cache in the dev tools. If you disable the cache and reload it, then do you see it?

And yeah, we see it very consistently in release, without the cache disabled. But disabling the cache in debug makes it easier to reproduce.

**Comment by huycozy** [comment] 2024-05-10 05:54
@camfrandsen I couldn't reproduce this issue on my Safari `Version 17.1 (19616.2.9.11.7)`; I disabled cache as well. 

When you see the issue, does the sound still play or not? Can you inspect web element to see if `video` still stays there? It's worth trying to test with a pure web that contains `video` element (without using package) to isolate the issue.

**Comment by camfrandsen** [comment] 2024-05-11 17:19
It is very interesting to me that some machines with safari see the issue, and some don't... We have only tried it on 4 computers at this point, and have seen it on each one. Having said, I believe this to be a safari issue. As I can reproduce the issue with the follow html code:
```
<!DOCTYPE html> 
<html> 
<body> 

<video width="400" controls>
  <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" type="video/mp4">
  
  Your browser does not support HTML video.
</video>

<p>
Video courtesy of 
<a href="https://www.bigbuckbunny.org/" target="_blank">Big Buck Bunny</a>.
</p>

</body> 
</html>
```
https://github.com/flutter/flutter/assets/145144088/28d9e866-2f81-4f7a-959c-db97ee94015b

Thank you for all of your help trying to track this down! I really appreciate it! I will let you close the issue so that way you can mark it however you would like.

Thank you again!

**Comment by danagbemava-nc** [comment] 2024-05-13 06:12
Great, glad we could you trace the root of the issue. 

Closing this as it appears to be a general Safari issue rather than an issue with flutter itself. 

Thank you

**Closed by danagbemava-nc** 2024-05-13 06:12 UTC
Labels: in triage
