### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: The system cannot find the path specified., errno = 3

### ISSUE THREAD

**Issue by KPoarch** [flutter/flutter#67196] opened 2020-10-03 05:04 UTC
## Command
```
flutter pub upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: The system cannot find the path specified.
, errno = 3
```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      _ensureExists (package:flutter_tools/src/cache.dart:1413:15)
#4      Cache.downloadFile (package:flutter_tools/src/cache.dart:491:5)
#5      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:640:23)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:636:55)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:670:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:636:12)
#9      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:657:12)
#10     EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:785:13)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:592:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:458:24)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     CachedArtifact.update (package:flutter_tools/src/cache.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```
```
[✓] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.20.2 at C:\flutter
    • Framework revision bbfbf1770c (7 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision <<<<<<< HE
    • Dart version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Keegan\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code, 64-bit edition (version 1.49.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: bbfbf1770cca2da7c82e887e4e4af910034800b6

**Comment by Abhishek01039** [comment] 2020-10-03 05:08
Hi @KPoarch 
a similar issue is opened here https://github.com/flutter/flutter/issues/60272
so please follow there rather than to create a duplicate issue.
Thanks

**Comment by iapicca** [comment] 2020-10-04 07:12
@KPoarch 
according to this [comment](https://github.com/flutter/flutter/issues/66415#issuecomment-701003004)
this issue might have been fixed in the master channel

**Comment by darshankawar** [comment] 2020-10-05 09:15
Closing this as duplicate of [60272](https://github.com/flutter/flutter/issues/60272)

**Closed by darshankawar** 2020-10-05 09:15 UTC
