### ISSUE TITLE
Linux web_tool_tests flakes on `Failed to create server socket`

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97332] opened 2022-01-26 23:02 UTC
part of [#97036](https://github.com/flutter/flutter/issues/97036))
These data is based on Q4 2021 flakes that happened from 10/01/2021 to 01/13/2022

4 flakes on `Linux web_tool_tests`: 
[4228](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/4228/overview) (happened on 11/24/2021)
[4048](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/4048/overview) (happened on 11/03/2021)
[3984](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/3984/overview) (happened on 10/28/2021)
[3980](https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20web_tool_tests/3980/overview) (happened on 10/27/2021)

```
01:18 +3 -1: test/web.shard/vm_service_web_test.dart: Clients of flutter run on web with DDS disabled can validate flutter version [E]                                                                 
  Exception: Received app.stop event while waiting for app.started event
  
  [ +120 ms] SocketException: Failed to create server socket (OS Error: The shared flag to bind() needs to be `true` if binding multiple times on the same (address, port) combination.), address = ::1, port = 42655
             #0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:988:7)
             <asynchronous suspension>
             #1      HttpMultiServer._loopback (package:http_multi_server/http_multi_server.dart:183:22)
             <asynchronous suspension>
             #2      ExtensionBackend.start (package:dwds/src/servers/extension_backend.dart:57:18)
             <asynchronous suspension>
             #3      Dwds.start (package:dwds/dwds.dart:138:26)
             <asynchronous suspension>
             #4      WebAssetServer.start (package:flutter_tools/src/isolated/devfs_web.dart:274:23)
             <asynchronous suspension>
             #5      WebDevFS.create (package:flutter_tools/src/isolated/devfs_web.dart:727:22)
             <asynchronous suspension>
             #6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:285:25)
             <asynchronous suspension>
             #7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
             <asynchronous suspension>
  
  Failed to establish connection with the application instance in Chrome.
  This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.
  
  #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
  #1      ResidentWebRunner.run (package:flutter_tools/src/isolated/resident_web_runner.dart:336:7)
  <asynchronous suspension>
  #2      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:599:9)
  <asynchronous suspension>
  #3      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:597:5)
  <asynchronous suspension>
  #4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:568:15)
  <asynchronous suspension>
  #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
  <asynchronous suspension>
  #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
  <asynchronous suspension>
  #7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
  <asynchronous suspension>
  #8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
  <asynchronous suspension>
  #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
  <asynchronous suspension>
  #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
  <asynchronous suspension>
  #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
  <asynchronous suspension>
  #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
  <asynchronous suspension>
  #13     main (package:flutter_tools/executable.dart:94:3)
  <asynchronous suspension>
```

**Comment by keyonghan** [comment] 2022-01-26 23:09
@zanderso Here is one for Linux web_tool_tests. Please help take a look and feel free to close if the issue has been addressed or is no longer feasible to fix. Thanks!

**Comment by zanderso** [comment] 2022-01-31 05:19
This is a duplicate of https://github.com/flutter/flutter/issues/93256

**Closed by zanderso** 2022-01-31 05:19 UTC
Labels: tool, team: flakes
