### ISSUE TITLE
[web] : Scrolling using touch is broken on the latest version 1.12.15

### ISSUE THREAD

**Issue by johnstef99** [flutter/flutter#45922] opened 2019-12-02 20:06 UTC
## Steps to Reproduce

1. Upgrade from dev v1.12.2 to v1.12.15
2. Use the same app without any changes
3. I **can't scroll anything (ListView, SingleChildScrollView) by using touch**

**Target Platform: web**
**Target OS version/browser: chrome**
**Devices: macbook and android**

## Logs

```
```

```
```

```
```

**Comment by johnstef99** [comment] 2019-12-02 22:08
I found out that scrolling is working in v1.12.5 but it's broken in v1.12.6.. hope that helps find the bug

**Comment by kf6gpe** [comment] 2019-12-03 19:54
Possible dupe of https://github.com/flutter/flutter/issues/45510?

**Comment by tvolkert** [comment] 2019-12-03 20:00
@johnstef99 can you see if this reproduces against the latest beta (v1.12.13+hotfix.1)?  Also, any way you can bisect to find out which commit introduced the bug?

@ferhatb @yjbanov to get this on your radar.

**Comment by jonahwilliams** [comment] 2019-12-03 20:09
I believe this fix for this is https://github.com/flutter/engine/pull/14082

so @chunhtai and @mdebbar will have the most context.

**Comment by tvolkert** [comment] 2019-12-03 20:15
> working in v1.12.5 but it's broken in v1.12.6

I initially misread this as `v1.12.15` and `v1.12.16`.  I agree this sounds like a dup of #45510.  Closing as such.  @johnstef99 please let me know if you disagree.

**Closed by tvolkert** 2019-12-03 20:15 UTC
Labels: RELEASE BLOCKER, f: scrolling, framework, severe: regression, ☸ platform-web

**Comment by johnstef99** [comment] 2019-12-04 11:34
So that's the solution for now? https://github.com/flutter/flutter/issues/45510#issuecomment-558313671

**Comment by tvolkert** [comment] 2019-12-04 15:41
The fix has landed on master.
