### ISSUE TITLE
SystemUiOverlayStyle is not working

### ISSUE THREAD

**Issue by ziqq** [flutter/flutter#77887] opened 2021-03-11 08:09 UTC
SystemUiOverlayStyle is not working for me. I upgrade flutter to v2.0 and i have this problem.

![image](https://user-images.githubusercontent.com/20646071/110755655-3c950a00-825a-11eb-9e87-c86d46d49e5b.png)

![image](https://user-images.githubusercontent.com/20646071/110755692-4880cc00-825a-11eb-8e68-9594de0b4a30.png)

**Comment by pedromassangocode** [comment] 2021-03-11 09:21
Hi @ziqq 
Can you please provide your `flutter doctor -v` a minimal complete reproducible code sample and the actual vs expected results?
Thank you

**Comment by ziqq** [comment] 2021-03-11 09:23
![image](https://user-images.githubusercontent.com/20646071/110764814-8da9fb80-8264-11eb-968c-dfdc332f07bf.png)

**Comment by hellobq** [comment] 2021-03-17 11:40
i also had this problem, so lowered the version.

try this:
``` dart
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
  statusBarColor: Colors.blue,
  statusBarIconBrightness: Brightness.dark, // not working
  systemNavigationBarColor: Colors.blue,
  systemNavigationBarIconBrightness: Brightness.dark, // works
))
```

**Comment by ziqq** [comment] 2021-03-17 12:55
> i also had this problem, so lowered the version.
> 
> try this?
> 
> ```dart
> SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
>   statusBarColor: Colors.blue,
>   statusBarIconBrightness: Brightness.dark,
>   systemNavigationBarColor: Colors.blue,
>   systemNavigationBarIconBrightness: Brightness.dark,
> ))
> ```

I need this line 

`statusBarIconBrightness: Brightness.dark`

but it dosnt work

**Comment by pedromassangocode** [comment] 2021-03-17 13:14
This seems to be a duplicate of https://github.com/flutter/flutter/issues/64001. Please follow up on that issue for updates.
Thank you

**Closed by pedromassangocode** 2021-03-17 13:14 UTC
Labels: in triage

**Comment by ziqq** [comment] 2021-03-17 13:26
it didn't help me
