### ISSUE TITLE
Navigation stack resetting when 'Don't Keep Activities' is enabled in developer options

### ISSUE THREAD

**Issue by viplavrawal** [flutter/flutter#51628] opened 2020-02-28 10:26 UTC
Navigation stack resets and the app starts from the first page on coming from background in case 'Don't Keep Activities' is enabled in the developer options menu of Android device.

## Steps to Reproduce

1. Enable 'Don't keep activities' in the Developer options of Android settings
2. Run the app and go to page two or further in the navigation stack.
3. Take the app in the background and open again

**Expected results:** The same page should load again

**Actual results:** The navigation stack reloads and the app starts from the first page

## Flutter doctor
`[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87,`
`    locale en-IN)`
`[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)`
`[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)`
`[✓] Android Studio (version 3.5)`
`[✓] VS Code (version 1.42.1)`
`[✓] Connected device (2 available)`

**Comment by Zazo032** [comment] 2020-02-28 14:27
Duplicate of https://github.com/flutter/flutter/issues/6827

**Comment by chunhtai** [comment] 2020-03-03 22:50
Lets keep track of the progress in https://github.com/flutter/flutter/issues/6827

**Closed by chunhtai** 2020-03-03 22:50 UTC
Labels: f: routes, framework, ▣ platform-android
