### ISSUE TITLE
Application crash when dragging mouse over Tooltip while selecting text in SelectionArea

### ISSUE THREAD

**Issue by damphat** [flutter/flutter#129969] opened 2023-07-04 21:39 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Write an app with `SelectionArea`, add some text and some widget that show tooltips
2. Keep drag the mouse cursor to select the text, try to move the mouse over a tooltip
3. Crash in desktop debug mode (macOS in my case)

### Expected results

Should be able to select the text

### Actual results

```
Exception has occurred.
_AssertionError ('package:flutter/src/rendering/object.dart': Failed assertion: line 3263 pos 14: 'renderer.parent != null': is not true.)
```

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: CrashTest(),
    );
  }
}

class CrashTest extends StatelessWidget {
  const CrashTest({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SelectionArea(
        child: Center(
          child: Column(
            children: [
              const Text("Select me"),
              const Text("Select me"),
              Tooltip(
                showDuration: const Duration(seconds: 30),
                message: 'Drag your mouse over me to crash your app',
                child: Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                ),
              ),
              const Text("Select me"),
              const Text("Select me"),
              const Text("Select me"),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![crash](https://github.com/flutter/flutter/assets/677382/ac44294c-4474-4c37-ba86-c532de866bab)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.12.0-12.0.pre.40, on macOS 13.2.1 22D68 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
[✓] VS Code (version 1.79.2)
[✓] VS Code (version 1.80.0-insider)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-07-05 08:39
Thanks for your report, @damphat. I can see this issue appears on master channel but it works on the latest stable 3.10.5. 

I bisected this to  https://github.com/flutter/flutter/pull/127728 (migrate Tooltip to use OverlayPortal)

<details>
<summary>Entire the exception</summary>

```console

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: file:///Users/huynq/Documents/GitHub/flutter_master/packages/flutter/lib/src/rendering/object.dart:3263:14
renderer.parent != null
is not true

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3         assertFailed
packages/flutter/src/rendering/object.dart 3263:22                                 getTransformTo
packages/flutter/src/rendering/paragraph.dart 1723:58                              <fn>
packages/flutter/src/rendering/paragraph.dart 1723:81                              getTransformTo
packages/flutter/src/widgets/selection_container.dart 279:17                       getTransformFrom
packages/flutter/src/widgets/selectable_region.dart 1830:35                        <fn>
dart-sdk/lib/internal/iterable.dart 415:31                                         elementAt
dart-sdk/lib/internal/iterable.dart 344:26                                         moveNext
dart-sdk/lib/internal/iterable.dart 440:22                                         moveNext
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1080:20  next
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 555:14                 of
dart-sdk/lib/core/iterable.dart 495:7                                              toList
packages/flutter/src/widgets/selectable_region.dart 1837:56                        getSelectionGeometry
packages/flutter/src/widgets/selectable_region.dart 1669:40                        [_updateSelectionGeometry]
packages/flutter/src/widgets/selectable_region.dart 1657:5                         didChangeSelectables
packages/flutter/src/widgets/selectable_region.dart 1487:11                        didChangeSelectables
packages/flutter/src/widgets/selectable_region.dart 1589:5                         [_updateSelectables]
packages/flutter/src/widgets/selectable_region.dart 1569:9                         runScheduledTask
packages/flutter/src/scheduler/binding.dart 1297:15                                [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1236:9                                 handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1085:5                                 [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1304:13                                invoke
lib/_engine/engine/platform_dispatcher.dart 278:5                                  invokeOnDrawFrame
lib/_engine/engine/initialization.dart 185:45                                      <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37   _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39   dcall
====================================================================================================

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.10.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D                         • android-arm64  • Android 11 (API 30)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.12.0-13.0.pre.42, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.12.0-13.0.pre.42 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5b12b7467f (10 hours ago), 2023-07-04 10:12:49 -0700
    • Engine revision 987b621eac
    • Dart version 3.1.0 (build 3.1.0-262.0.dev)
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by hangyujin** [comment] 2023-07-05 20:02
Assign to @LongCatIsLooong  since is caused by https://github.com/flutter/flutter/pull/127728

**Comment by LongCatIsLooong** [comment] 2023-07-05 20:13
@hangyujin @chunhtai is there a way to exclude `Tooltip` widgets in a selectable region?

**Comment by chunhtai** [comment] 2023-07-05 20:17
you can tell if the tooltip is in a selection container or not, but why?

**Comment by LongCatIsLooong** [comment] 2023-07-05 20:24
Most of the time the text in the tooltip isn't meant to be selectable (especially not along with the other contents on screen) right? It can be exposed as a flag in the `Tooltip` widget so people can toggle the behavior?

**Comment by chunhtai** [comment] 2023-07-05 20:28
oh you meant the tooltip pop up? yes you can do SelectionContainer.disabled()

**Comment by chunhtai** [comment] 2023-07-05 20:29
you can do something like
```dart
if (SelectionContainer.of(context) != null) {
  result = SelectionContainer.disabled(child: result);
}
```

**Closed** 2023-07-13 00:35 UTC
Labels: c: regression, c: crash, framework, f: material design, a: desktop, a: mouse, has reproducible steps, P1, f: selection, found in release: 3.12, team-desktop, triaged-desktop, multiteam-retriage-candidate
