### ISSUE TITLE
Appbar navigation button missplaced when switching to RTL language on IOS

### ISSUE THREAD

**Issue by Khaled-Eldeeb-BW** [flutter/flutter#153245] opened 2024-08-11 13:40 UTC
### Steps to reproduce

Use a scaffold 
check the back button icon
it wil be reversed in IOS, 

Same goes for widgets using the arrow icon 

Check 2nd image 

### Expected results

![image](https://github.com/user-attachments/assets/ff5116e6-e9ec-495e-ab13-fe793e64337f)
![image](https://github.com/user-attachments/assets/6491e3f4-8bf4-4cfb-a0c2-18e18ca8a9b9)

### Actual results

![image](https://github.com/user-attachments/assets/b9cb058b-55c2-46fc-93d8-d703626a44a2)
![image](https://github.com/user-attachments/assets/8945bd2c-8ff4-4c44-85d2-f004744a43c6)

### Code sample

<details open><summary>Code sample</summary>

```dart
const Icon(
                        Icons.arrow_forward_ios,
                        size: 14,
                        color: Color(0xFF156FEE),
                      ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached
      with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by Khaled-Eldeeb-BW** [comment] 2024-08-11 13:42
not missplaced, but mirrored incorrectly on IOS

**Comment by danagbemava-nc** [comment] 2024-08-12 09:05
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153036

**Closed by danagbemava-nc** 2024-08-12 09:05 UTC
Labels: in triage
