### ISSUE TITLE
SliverGeometry is not valid: The "layoutExtent" is negative.

### ISSUE THREAD

**Issue by ishizhen** [flutter/flutter#39963] opened 2019-09-06 07:50 UTC
```
════════ Exception Caught By rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
SliverGeometry is not valid: The "layoutExtent" is negative.

The RenderSliver that returned the offending geometry was: RenderSliverOverlapAbsorber#e405e relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 490.2) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
...  geometry: SliverGeometry(scrollExtent: 0.0, hidden, layoutExtent: -56.0, maxPaintExtent: 56.0, hasVisualOverflow: true, cacheExtent: -56.0)
...    scrollExtent: 0.0
...    hidden
...    layoutExtent: -56.0
...    maxPaintExtent: 56.0
...    hasVisualOverflow: true
...    cacheExtent: -56.0
...  handle: SliverOverlapAbsorberHandle(56.0null)
When the exception was thrown, this was the stack: 
#0      SliverGeometry.debugAssertIsValid.<anonymous closure>.verify (package:flutter/src/rendering/sliver.dart:711:9)
#1      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:720:13)
#2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:745:6)
#3      RenderSliver.debugAssertDoesMeetConstraints (package:flutter/src/rendering/sliver.dart:1198:21)
#4      RenderObject.layout.<anonymous closure> (package:flutter/src/rendering/object.dart:1621:19)
...
The following RenderObject was being processed when the exception was fired: RenderSliverOverlapAbsorber#e405e relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 490.2) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
...  geometry: SliverGeometry(scrollExtent: 0.0, hidden, layoutExtent: -56.0, maxPaintExtent: 56.0, hasVisualOverflow: true, cacheExtent: -56.0)
...    scrollExtent: 0.0
...    hidden
...    layoutExtent: -56.0
...    maxPaintExtent: 56.0
...    hasVisualOverflow: true
...    cacheExtent: -56.0
...  handle: SliverOverlapAbsorberHandle(56.0null)
RenderObject: RenderSliverOverlapAbsorber#e405e relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: paintOffset=Offset(0.0, 490.2) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
  geometry: SliverGeometry(scrollExtent: 0.0, hidden, layoutExtent: -56.0, maxPaintExtent: 56.0, hasVisualOverflow: true, cacheExtent: -56.0)
    scrollExtent: 0.0
    hidden
    layoutExtent: -56.0
    maxPaintExtent: 56.0
    hasVisualOverflow: true
    cacheExtent: -56.0
  handle: SliverOverlapAbsorberHandle(56.0null)
...  child: _RenderSliverPinnedPersistentHeaderForWidgets#be3c6 relayoutBoundary=up2 NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 56.0, hidden, maxPaintExtent: 56.0, hasVisualOverflow: true)
...      scrollExtent: 56.0
...      hidden
...      maxPaintExtent: 56.0
...      hasVisualOverflow: true
...    maxExtent: 56.0
...    child position: 0.0
...    child: RenderSemanticsAnnotations#9889a relayoutBoundary=up3
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=56.0)
...      semantics node: SemanticsNode#12
...        Rect.fromLTRB(0.0, 490.2, 414.0, 546.2)
...      semantic boundary
...      size: Size(414.0, 56.0)
...      child: RenderAnnotatedRegion<SystemUiOverlayStyle>#8e98d relayoutBoundary=up4
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=56.0)
...        size: Size(414.0, 56.0)
...        child: RenderPhysicalModel#72146 relayoutBoundary=up5
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, 0.0<=h<=56.0)
...          size: Size(414.0, 56.0)
...          elevation: 0.0
...          color: Color(0xfff5f5f5)
...          shadowColor: Color(0xfff5f5f5)
...          shape: BoxShape.rectangle
...          borderRadius: BorderRadius.zero
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception Caught By rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
SliverGeometry is not valid: The "layoutExtent" is negative.

When the exception was thrown, this was the stack: 
#0      SliverGeometry.debugAssertIsValid.<anonymous closure>.verify (package:flutter/src/rendering/sliver.dart:711:9)
#1      SliverGeometry.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/sliver.dart:720:13)
#2      SliverGeometry.debugAssertIsValid (package:flutter/src/rendering/sliver.dart:745:6)
#3      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:422:34)
#4      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
...
The following RenderObject was being processed when the exception was fired: RenderNestedScrollViewViewport#906a9 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=712.0)
...  layer: OffsetLayer#0d6db
...    offset: Offset(0.0, 0.0)
...  size: Size(414.0, 712.0)
...  axisDirection: down
...  crossAxisDirection: right
...  offset: _NestedScrollPosition#2efd0(outer, offset: 0.0, range: 0.0..490.2, viewport: 712.0)
...  anchor: 0.0
...  handle: SliverOverlapAbsorberHandle(56.0null)
RenderObject: RenderNestedScrollViewViewport#906a9 NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=712.0)
  layer: OffsetLayer#0d6db
    offset: Offset(0.0, 0.0)
  size: Size(414.0, 712.0)
  axisDirection: down
  crossAxisDirection: right
  offset: _NestedScrollPosition#2efd0(outer, offset: 0.0, range: 0.0..490.2, viewport: 712.0)
  anchor: 0.0
  handle: SliverOverlapAbsorberHandle(56.0null)
...  center child: RenderSliverToBoxAdapter#60f53 relayoutBoundary=up1 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 712.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 962.0 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 204.2, paintExtent: 204.2, maxPaintExtent: 204.2, cacheExtent: 204.2)
...      scrollExtent: 204.2
...      paintExtent: 204.2
...      maxPaintExtent: 204.2
...      cacheExtent: 204.2
...    child: RenderConstrainedBox#0b943 relayoutBoundary=up2 NEEDS-PAINT
...      needs compositing
...      parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...      size: Size(414.0, 204.2)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=204.2)
...      child: RenderStack#5f1a2 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, h=204.2)
...        size: Size(414.0, 204.2)
...        alignment: AlignmentDirectional.topStart
...        textDirection: ltr
...        fit: loose
...        overflow: clip
...        child 1: _RenderScrollSemantics#c5882 relayoutBoundary=up1
...          needs compositing
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=204.2)
...          semantics node: SemanticsNode#33
...            Rect.fromLTRB(0.0, 0.0, 414.0, 204.2)
...          semantic boundary
...          size: Size(414.0, 204.2)
...        child 2: RenderPositionedBox#9d129 relayoutBoundary=up1 NEEDS-PAINT
...          parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=204.2)
...          size: Size(414.0, 204.2)
...          alignment: bottomCenter
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
...  child 1: RenderSliverToBoxAdapter#c3d90 relayoutBoundary=up1
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 204.2) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 507.8, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 757.8 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 204.2, paintExtent: 204.2, maxPaintExtent: 204.2, cacheExtent: 204.2)
...      scrollExtent: 204.2
...      paintExtent: 204.2
...      maxPaintExtent: 204.2
...      cacheExtent: 204.2
...    child: RenderConstrainedBox#2c6c3 relayoutBoundary=up2
...      needs compositing
...      parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...      size: Size(414.0, 204.2)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=204.2)
...      child: _RenderScrollSemantics#66983
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, h=204.2)
...        semantics node: SemanticsNode#42
...          Rect.fromLTRB(0.0, 204.2, 414.0, 408.5)
...        semantic boundary
...        size: Size(414.0, 204.2)
...        child: RenderPointerListener#5c93c
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, h=204.2)
...          size: Size(414.0, 204.2)
...          behavior: deferToChild
...          listeners: signal
...  child 2: RenderSliverToBoxAdapter#8f0a6 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: paintOffset=Offset(0.0, 408.5) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 303.5, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 553.5 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 176.6, paintExtent: 176.6, maxPaintExtent: 176.6, cacheExtent: 176.6)
...      scrollExtent: 176.6
...      paintExtent: 176.6
...      maxPaintExtent: 176.6
...      cacheExtent: 176.6
...    child: RenderConstrainedBox#fbf38 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...      size: Size(414.0, 176.6)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=176.6)
...      child: RenderDecoratedBox#6fcb3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, h=176.6)
...        size: Size(414.0, 176.6)
...        decoration: BoxDecoration
...          color: Color(0xfff8f8f8)
...        configuration: ImageConfiguration(bundle: PlatformAssetBundle#bf5ca(), devicePixelRatio: 2.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
...        child: RenderFlex#8a473 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, h=176.6)
...          size: Size(414.0, 176.6)
...          direction: vertical
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          verticalDirection: down
...  child 3: RenderSliverToBoxAdapter#ed741 relayoutBoundary=up1 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 585.1) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 126.9, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 376.9 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 286.0, paintExtent: 126.9, maxPaintExtent: 286.0, hasVisualOverflow: true, cacheExtent: 286.0)
...      scrollExtent: 286.0
...      paintExtent: 126.9
...      maxPaintExtent: 286.0
...      hasVisualOverflow: true
...      cacheExtent: 286.0
...    child: RenderDecoratedBox#152d3 relayoutBoundary=up2
...      needs compositing
...      parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...      size: Size(414.0, 286.0)
...      decoration: BoxDecoration
...        color: Color(0xffffffff)
...      configuration: ImageConfiguration(bundle: PlatformAssetBundle#bf5ca(), devicePixelRatio: 2.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
...      child: RenderPadding#b6366 relayoutBoundary=up3
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...        size: Size(414.0, 286.0)
...        padding: EdgeInsets.zero
...        textDirection: ltr
...        child: RenderFlex#cd212 relayoutBoundary=up4
...          needs compositing
...          parentData: offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(w=414.0, 0.0<=h<=Infinity)
...          size: Size(414.0, 286.0)
...          direction: vertical
...          mainAxisAlignment: start
...          mainAxisSize: max
...          crossAxisAlignment: center
...          verticalDirection: down
...  child 4: RenderSliverOverlapAbsorber#e405e relayoutBoundary=up1 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 490.2) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 0.0, hidden, layoutExtent: -56.0, maxPaintExtent: 56.0, hasVisualOverflow: true, cacheExtent: -56.0)
...      scrollExtent: 0.0
...      hidden
...      layoutExtent: -56.0
...      maxPaintExtent: 56.0
...      hasVisualOverflow: true
...      cacheExtent: -56.0
...    handle: SliverOverlapAbsorberHandle(56.0null)
...    child: _RenderSliverPinnedPersistentHeaderForWidgets#be3c6 relayoutBoundary=up2 NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 0.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 90.9 cacheOrigin: 0.0 )
...      geometry: SliverGeometry(scrollExtent: 56.0, hidden, maxPaintExtent: 56.0, hasVisualOverflow: true)
...        scrollExtent: 56.0
...        hidden
...        maxPaintExtent: 56.0
...        hasVisualOverflow: true
...      maxExtent: 56.0
...      child position: 0.0
...      child: RenderSemanticsAnnotations#9889a relayoutBoundary=up3
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=56.0)
...        semantics node: SemanticsNode#12
...          Rect.fromLTRB(0.0, 490.2, 414.0, 546.2)
...        semantic boundary
...        size: Size(414.0, 56.0)
...        child: RenderAnnotatedRegion<SystemUiOverlayStyle>#8e98d relayoutBoundary=up4
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, 0.0<=h<=56.0)
...          size: Size(414.0, 56.0)
...  child 5: RenderSliverFillRemaining#0231d relayoutBoundary=up1
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 490.2) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 221.8, overlap: 56.0, crossAxisExtent: 414.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 712.0, remainingCacheExtent: 471.8 cacheOrigin: 0.0 )
...    geometry: SliverGeometry(scrollExtent: 712.0, paintExtent: 221.8, maxPaintExtent: 221.8, cacheExtent: 221.8)
...      scrollExtent: 712.0
...      paintExtent: 221.8
...      maxPaintExtent: 221.8
...      cacheExtent: 221.8
...    child: _RenderScrollSemantics#f5037
...      needs compositing
...      parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...      constraints: BoxConstraints(w=414.0, h=221.8)
...      semantics node: SemanticsNode#8
...        Rect.fromLTRB(0.0, 546.2, 414.0, 712.0)
...      semantic boundary
...      size: Size(414.0, 221.8)
...      child: RenderPointerListener#da0c0
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, h=221.8)
...        size: Size(414.0, 221.8)
...        behavior: deferToChild
...        listeners: signal
...        child: RenderSemanticsGestureHandler#3504c
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, h=221.8)
...          size: Size(414.0, 221.8)
...          gestures: horizontal scroll
```

**Comment by BondarenkoStas** [comment] 2019-09-06 10:52
@ishizhen Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Please provide your ```flutter doctor -v``` output.

This is a question better suited for StackOverflow, since probably there is no anything wrong with Flutter itself, but related to implementation. Please consider to post it there as well as help there may come faster.

**Comment by janmoppel** [comment] 2019-11-12 11:08
Hello @ishizhen !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Comment by Piinks** [comment] 2020-01-16 18:23
A PR has been opened to fix this issue, so I am re-opening this to discuss. Can you provide a reproduction of the crash @luckybilly?

**Comment by Piinks** [comment] 2020-01-16 18:26
Repro: https://dartpad.dev/2630a061cf2632a1ffd6fb6c13c94e4c

**Closed** 2020-01-24 18:23 UTC
Labels: f: scrolling, framework, severe: crash, waiting for PR to land (fixed)

**Comment by raveesh-me** [comment] 2020-10-30 13:50
@Piinks thank you so much for work on this. Now we dont have this issue in release, but have this issue in debug builds.

Output for my flutter doctor:
```
🙏  <ॐ> 
╰─~ flutter doctor -v                                                                                             [19:19:03]
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Linux, locale en_IN)
    • Flutter version 1.23.0-18.1.pre at /home/raveesh/Dev/Tools/flutter
    • Framework revision 198df796aa (2 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/raveesh/Android/Sdk
    • Platform android-29, build-tools 30.0.2
    • Java binary at: /home/raveesh/Dev/Tools/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/raveesh/Dev/Tools/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /home/raveesh/Dev/Tools/idea-IC-202.6948.69
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.50.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111

• No issues found!


```

**Comment by Piinks** [comment] 2020-10-30 16:09
Hi @raveesh-me can you please file a new issue with a runnable sample of code that reproduces this issue? Thanks!
