### ISSUE TITLE
Flutter Error initializing ADB:Android Debug Bridge not found !!(after android studio update)

### ISSUE THREAD

**Issue by eminyazann** [flutter/flutter#55557] opened 2020-04-24 13:57 UTC
Hello guys 
When ı workıng on databases (sqflite 1.3.0) ı created a db file in my project and when ı want to check it
when ı clicked to device file explorer ı took this Error initializing ADB:Android Debug Bridge not found.
Do u have any advice for solving this problem? 

everything is normal in  flutter doctor sdk updated platform tools updated adc.exe closed and opened deleted updated.

**Comment by oberkaytuncer** [comment] 2020-04-24 15:03
Same problem here..

**Comment by eminyazann** [comment] 2020-04-24 16:12
> 
> 
> Same problem here..

do u have same problem too

**Comment by iapicca** [comment] 2020-04-27 07:03
Hi @eminyazann 
the error doesn't seem to involve flutter itself;

for issues using flutter with `android studio`,
following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

also note that [sqflite](https://pub.dev/packages/sqflite) is a 3rd party plugin,
if you believe the issue is related with said plugin 
you may want to open an issue in the dedicated [github](https://github.com/tekartik/sqflite/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you for your understanding

**Closed by iapicca** 2020-04-27 07:03 UTC

**Comment by PiN73** [comment] 2020-06-12 21:21
This fixes the problem for me
https://github.com/flutter/flutter-intellij/issues/3273#issuecomment-521633766

**Comment by MarceloBalz** [comment] 2020-07-15 19:10
> This fixes the problem for me:
> Open File -> Project Structure;
> In Project, select valid Project SDK;
> In Modules -> myapp_android -> Dependencies, select a valid Module SDK.
> (thanks _walberla_ from [flutter/flutter-intellij#3273 (comment)](https://github.com/flutter/flutter-intellij/issues/3273#issuecomment-521633766))
> Then close AS, kill adb process in Task Manager, do `adb start-server` in command line and start AS

Thank you very mutch...

**Comment by aminovicnouri** [comment] 2021-01-28 10:02
> This fixes the problem for me:
> Open File -> Project Structure;
> In Project, select valid Project SDK;
> In Modules -> myapp_android -> Dependencies, select a valid Module SDK.
> (thanks _walberla_ from [flutter/flutter-intellij#3273 (comment)](https://github.com/flutter/flutter-intellij/issues/3273#issuecomment-521633766))
> Then close AS, kill adb process in Task Manager, do `adb start-server` in command line and start AS

thank you very much

**Comment by pabliuscf** [comment] 2021-02-12 13:17
Works!! Thank you.

**Comment by pabliuscf** [comment] 2021-02-12 13:18
> This fixes the problem for me:
> Open File -> Project Structure;
> In Project, select valid Project SDK;
> In Modules -> myapp_android -> Dependencies, select a valid Module SDK.
> (thanks _walberla_ from [flutter/flutter-intellij#3273 (comment)](https://github.com/flutter/flutter-intellij/issues/3273#issuecomment-521633766))
> Then close AS, kill adb process in Task Manager, do `adb start-server` in command line and start AS

Works!! Thank you.
