### ISSUE TITLE
[tool_crash] SessionNotCreatedException

### ISSUE THREAD

**Issue by kristoffer-zliide** [flutter/flutter#152367] opened 2024-07-26 11:47 UTC
## Command
```
flutter drive -d web-server --web-port=7357 --driver-port=9515 --browser-name=edge --web-renderer=html --driver test_driver/integration_test.dart --target integration_test/camera_web_test.dart
```

## Steps to Reproduce
1. run msedgedriver.exe
2. run the above command (in packages/camera/camera_web/example/, though that package is likely not the issue)

## Logs
SessionNotCreatedException: SessionNotCreatedException (500): session not created: No matching capabilities found
```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:81:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:157:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:324:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
```
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3880])
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.5)
[√] Android Studio (version 2023.2)
[√] VS Code (version 1.90.2)
[√] Connected device (2 available)
[√] Network resources

! Doctor found issues in 2 categories.
```
```
Starting Microsoft Edge WebDriver 127.0.2651.74 (dbf5b0aa014c4e70e3d5e2d73248e21264f82957) on port 9515
To submit feedback, report a bug, or suggest new features, please visit https://github.com/MicrosoftEdge/EdgeWebDriver

Only local connections are allowed.
Please see https://aka.ms/WebDriverSecurity for suggestions on keeping Microsoft Edge WebDriver safe.

Microsoft Edge WebDriver was started successfully.
[1721993466.926][INFO]: [0cd9bf797da19572f2181fa4357f9bad] COMMAND InitSession {
   "capabilities": {
      "alwaysMatch": {
         "acceptInsecureCerts": true,
         "browserName": "edge"
      }
   },
   "desiredCapabilities": {
      "acceptInsecureCerts": true,
      "browserName": "edge"
   }
}
[1721993466.935][INFO]: [0cd9bf797da19572f2181fa4357f9bad] RESPONSE InitSession ERROR session not created: No matching capabilities found
[1721993466.935][DEBUG]: Log type 'driver' lost 1 entries on destruction
```

## Flutter Application Metadata
**Type**: malformed
**Version**: null
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
camera_web
integration_test

**Comment by kristoffer-zliide** [comment] 2024-07-26 11:52
```
geckodriver.exe
```
and
```
flutter drive -d web-server --web-port=7357 --browser-name=firefox --web-renderer=html --driver test_driver/integration_test.dart --target integration_test/camera_web_test.dart
```
(Firefox) works fine.
```
$ ./geckodriver.exe
1721994507027   geckodriver     INFO    Listening on 127.0.0.1:4444
1721994569812   geckodriver::capabilities       DEBUG   Trying to read firefox version from ini files
1721994569813   geckodriver::capabilities       DEBUG   Found version 128.0.2
1721994569815   mozrunner::runner       INFO    Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-headless" "-no-remote" "-profile" "C:\\Users\\...\\AppData\\Local\\Temp\\rust_mozprofileg8od1I"
1721994569818   geckodriver::marionette DEBUG   Waiting 60s to connect to browser on 127.0.0.1
1721994569818   geckodriver::browser    TRACE   Failed to open C:\Users\...\AppData\Local\Temp\rust_mozprofileg8od1I\MarionetteActivePort
1721994569818   geckodriver::marionette TRACE   Retrying in 100ms
1721994569919   geckodriver::browser    TRACE   Failed to open C:\Users\...\AppData\Local\Temp\rust_mozprofileg8od1I\MarionetteActivePort
1721994569919   geckodriver::marionette TRACE   Retrying in 100ms
1721994570020   geckodriver::browser    TRACE   Failed to open C:\Users\...\AppData\Local\Temp\rust_mozprofileg8od1I\MarionetteActivePort
1721994570020   geckodriver::marionette TRACE   Retrying in 100ms
1721994570120   geckodriver::browser    TRACE   Failed to open C:\Users\...\AppData\Local\Temp\rust_mozprofileg8od1I\MarionetteActivePort
1721994570121   geckodriver::marionette TRACE   Retrying in 100ms
Read port: 60173
1721994570244   geckodriver::marionette DEBUG   Connection to Marionette established on 127.0.0.1:60173.
1721994570740   webdriver::server       DEBUG   <- 200 OK {"value":{"sessionId":"7d0d9792-8b22-48eb-8ca9-2294b280b712","capabilities":{"acceptInsecureCerts":true,"browserNam ... avior":"dismiss and notify","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"}}}
1721994570747   webdriver::server       DEBUG   -> GET /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/window
1721994570754   webdriver::server       DEBUG   <- 200 OK {"value":"348e2a22-534a-4978-9444-ba9cb99560a1"}
1721994570756   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/window/rect {"x":0,"y":0}
1721994571009   webdriver::server       DEBUG   <- 200 OK {"value":{"x":0,"y":0,"width":1229,"height":691}}
1721994571012   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/window/rect {"width":1600,"height":1024}
1721994571018   webdriver::server       DEBUG   <- 200 OK {"value":{"x":0,"y":0,"width":1600,"height":1024}}
1721994571875   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/url {"url":"http://localhost:7357"}
1721994573938   webdriver::server       DEBUG   <- 200 OK {"value":null}
1721994573953   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return typeof(window.$flutterDriver)","args":[]}
1721994573966   webdriver::server       DEBUG   <- 200 OK {"value":"undefined"}
1721994574480   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return typeof(window.$flutterDriver)","args":[]}
1721994574483   webdriver::server       DEBUG   <- 200 OK {"value":"undefined"}
1721994574997   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return typeof(window.$flutterDriver)","args":[]}
1721994575005   webdriver::server       DEBUG   <- 200 OK {"value":"undefined"}
1721994575515   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return typeof(window.$flutterDriver)","args":[]}
1721994575587   webdriver::server       DEBUG   <- 200 OK {"value":"undefined"}
1721994576092   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return typeof(window.$flutterDriver)","args":[]}
1721994576099   webdriver::server       DEBUG   <- 200 OK {"value":"function"}
1721994576115   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return $flutterDriverResult","args":[]}
1721994576117   webdriver::server       DEBUG   <- 200 OK {"value":null}
1721994576118   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"window.$flutterDriver('{\"command\":\"request_data\",\"timeout\":\"1200000\"}')","args":[]}
1721994576120   webdriver::server       DEBUG   <- 200 OK {"value":null}
1721994576121   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return $flutterDriverResult","args":[]}
1721994576123   webdriver::server       DEBUG   <- 200 OK {"value":null}
1721994576634   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return $flutterDriverResult","args":[]}
1721994576640   webdriver::server       DEBUG   <- 200 OK {"value":null}
1721994577145   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return $flutterDriverResult","args":[]}
1721994577150   webdriver::server       DEBUG   <- 200 OK {"value":null}
1721994577660   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return $flutterDriverResult","args":[]}
1721994577665   webdriver::server       DEBUG   <- 200 OK {"value":null}
1721994578175   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"return $flutterDriverResult","args":[]}
1721994578179   webdriver::server       DEBUG   <- 200 OK {"value":"{\"isError\":false,\"response\":{\"message\":\"{\\\"result\\\":\\\"true\\\",\\\"failureDetails\\\":[]}\"}}"}
1721994578181   webdriver::server       DEBUG   -> POST /session/7d0d9792-8b22-48eb-8ca9-2294b280b712/execute/sync {"script":"$flutterDriverResult = null","args":[]}
1721994578182   webdriver::server       DEBUG   <- 200 OK {"value":null}
1721994578211   webdriver::server       DEBUG   -> DELETE /session/7d0d9792-8b22-48eb-8ca9-2294b280b712
1721994578543   webdriver::server       DEBUG   Teardown session
1721994578744   geckodriver::browser    DEBUG   Browser process stopped: exit code: 0
1721994578783   webdriver::server       DEBUG   <- 200 OK {"value":null}
```

**Comment by darshankawar** [comment] 2024-07-26 13:13
Closing as duplicate of https://github.com/flutter/flutter/issues/141010

**Closed by darshankawar** 2024-07-26 13:13 UTC
Labels: in triage
