### ISSUE TITLE
Scrolling is janky with simple listview  with long list of strings

### ISSUE THREAD

**Issue by shadowdogg** [flutter/flutter#59404] opened 2020-06-13 19:51 UTC
1.  Please tell us exactly how to reproduce the problem you are running into.

I've been having issues with janking for a while, when you get more complicated widgets, this hanking effect gets expectedly worse. Took a video to show how even a simple scroll bar which was took from flutter's own cookbook becomes janky. Paying attention to the right where the scrollbar indicates the scroll. I attempted to scroll quickly in one movement. One is when the code is ran as a native android app and the other as a web app running in android chrome.

2.  Please attach a small application (ideally just one main.dart file) that
     reproduces the problem. You could use https://gist.github.com/ for this.

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<String>.generate(100, (i) => "Item $i"),
  ));
}

class MyApp extends StatelessWidget {
  final List<String> items;

  MyApp({Key key, @required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final title = 'Long List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Scrollbar(
          child: ListView.builder(
            itemCount: items.length,
            itemBuilder: (context, index) {
              return ListTile(
                title: Text('${items[index]}'),
              );
            },
          ),
        ),
      ),
    );
  }
}
```

3.  Switch flutter to master channel and run this app on a physical device
     using profile mode with Skia tracing enabled, as follows:
       flutter channel master
       flutter run --profile --trace-skia
     Then press ‘P’ to enable the performance overlay.

I am on master channel

4.  Record a video of the performance issue using another phone so we
     can have an intuitive understanding of what happened. Don’t use
     "adb screenrecord", as that affects the performance of the profile run.

Both running on a Pixel 3a running Android 10 (5th June 2020 security update)
Scroll test on native android app: https://youtu.be/A0KxjSvy9wU
Scroll test on chrome browser (android): https://youtu.be/OCWMrBHqNV0

5.  Open Observatory and save a timeline trace of the performance issue
     so we know which functions might be causing it. See "How to Collect
     and Read Timeline Traces" on this blog post:
       https://medium.com/flutter/profiling-flutter-applications-using-the-timeline-a1a434964af3#a499

Don't think I can with Android chrome?

**Comment by Auties00** [comment] 2020-06-13 23:25
I'm facing the same exact issue

**Comment by Auties00** [comment] 2020-06-13 23:46
I've kind of fixed it using a single child list view with a column and inside all of my objects, but there are still performance issues and when you try to scroll, only on certain devices, it just doesn't let you. You can test this: auties00.github.io
Chrome/Safari/Firefox desktop: Perfect
Chrome mobile: On some devices it works decently, on others it doesn't let you scroll, you have to manually hold to move the page. 
Firefox/Safari mobile: unusable

**Comment by TahaTesser** [comment] 2020-06-15 15:14
https://silly-clarke-ff3b2d.netlify.app/#/

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.20.0-1.0.pre.42, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.42 at /Users/tahatesser/Code/flutter_master
    • Framework revision 401690a64f (3 days ago), 2020-06-12 19:45:48 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome 83.0.4103.97

• No issues found!

``` 

</details>

**Comment by TahaTesser** [comment] 2020-06-16 08:50
This is also janky on mobile not just web

**Comment by Auties00** [comment] 2020-06-18 11:24
No, it doesn't lag on chrome mobile, just on firefox

**Comment by shadowdogg** [comment] 2020-06-18 11:41
> 
> 
> No, it doesn't lag on chrome mobile, just on firefox

I've done a video, it clearly does.

**Comment by Auties00** [comment] 2020-06-18 17:19
> > No, it doesn't lag on chrome mobile, just on firefox
> 
> I've done a video, it clearly does.

It doesn't on m device. Can you send it?

**Comment by shadowdogg** [comment] 2020-06-18 17:31
> 
> 
> > > No, it doesn't lag on chrome mobile, just on firefox
> > 
> > 
> > I've done a video, it clearly does.
> 
> It doesn't on m device. Can you send it?

Below is my quote from the first post
 
> 
> Both running on a Pixel 3a running Android 10 (5th June 2020 security update)
> Scroll test on native android app: https://youtu.be/A0KxjSvy9wU
> Scroll test on chrome browser (android): https://youtu.be/OCWMrBHqNV0

**Comment by CaliforniaMountainSnake** [comment] 2020-07-06 19:57
I also have scrolling janks even with very simple ListView with 100 of ListTtiles with strings.

**Comment by CaliforniaMountainSnake** [comment] 2020-07-09 08:04
Even this code produce junks on xiaomi redmi note 5 with Snapdragon 636 processor:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text("Test app"),
        ),
        body: Scrollbar(
          child: ListView.builder(
            itemCount: 200,
            physics: AlwaysScrollableScrollPhysics(),
            itemBuilder: (BuildContext context, int index) {
              return ListTile(
                title: Text("Title " + index.toString()),
                subtitle: Text("Subtitle " + index.toString()),
              );
            },
          ),
        ),
      ),
    );
  }
}

```

**Comment by shadowdogg** [comment] 2020-07-09 09:03
@CaliforniaMountainSnake That has 200, with text and subtitle. My code just had 100 with just title. So that would be expected

**Comment by azeemgujjar** [comment] 2020-07-10 06:51
This is the major bug in flutter, a very clear performance mirror as compared to react-native.
Flutter vertical scrolling specially with images have jerking issues.

here is an example app on playstore (Flutter demo: CINEMA) you can download and test, but that i am sure its flutter bug because all similar apps or with long list views this happens.

More examples in flutter official app: Flutter Gallery

Flutter Gallery -> (Crane A personalized travel app) -> vertical scroll listview in bottom (Jerk is clearly visible)

Flutter Gallery -> (Rally A personalized finance app) -> Login -> vertical scroll it (choppy scrolling Jerks)

Above examples are not debug all are on production playstore, on stackoverflow this is under discussion but everyone is doing just tricks which is not appropriate way to develop an production grade application.

**Comment by fadhlisulaimi** [comment] 2020-08-31 12:16
@azeemgujjar 

Use ScrollablepostionedList.builder instead of Listview.builder for listview from this package.
https://pub.dev/packages/scrollable_positioned_list

After changing to this library, scrolling is smooth and feel native on android.

**Comment by liyuqian** [comment] 2020-11-02 22:45
If https://pub.dev/packages/scrollable_positioned_list fixes the jank here, this issue might be a duplicate of https://github.com/flutter/flutter/issues/52207 where the costly computation of variable extent caused the jank.

**Comment by shadowdogg** [comment] 2020-11-30 23:38
@kf6gpe It certainly seems similar, my example seems a much simpler solution to show the issue though and is an example used by Flutter team too.

**Comment by GanongLS** [comment] 2021-02-06 08:56
I even do this janky lag performance with only 5 simple widget in SingleChildScrollView. If you flutter core developer just ignore it, just face the reality for the future, i code with RN to, i know when scrolling is janky. this is happening in android. and this is so bad feature bug.

**Comment by strohmann** [comment] 2021-02-06 09:53
Doing some profiling I found out that adjusting the browser DOM ('domRenderer.clearDom()' etc.) in flutters html engine while scrolling is the main cause of my performance problem in Android. I was not able to find a workaround as the problematic code is a few abstraction layers deeper than my own code. My own code resp. using Flutter widgets like CustomScrollView and RepaintBoundary seems fine and does not cause any performance overhead.
I think the problem could be easily mitigated by not clipping the resulting DIVs at each frame, but maybe providing a setting to not clip DIVs at all would help. It just does not make sense to spend tens of milliseconds on DOM cleaning when the list only contains ~20 items (with ~10 visible items). Mobile browers really don't like it when you change the DOM each frame.

Generally speaking, it was IMHO an unfortunate technical decision to re-implement scrolling in Dart and therefore not leveraging the browser's own native implementation. This is not just a performance problem on none-high-end smartphones, but also a problem when it comes to hiding the browser bar on scrolling.
I really hope that the flutter team can make huge leaps in scrolling performance in 2021, and can make it a lot easier for devs to implement 60hz scrolling.

**Comment by ChikkuChoco** [comment] 2022-05-28 15:41
**We can use `flutter run --release` to get the real performance of the app**

**Comment by matthewfx** [comment] 2022-06-06 09:59
Hey, I've experienced it in the flutter_markdown. Someone has raised it for it but it was marked as a duplicate of this issue. Any progress on it? That issue is 2 years old already....

**Comment by exaby73** [comment] 2022-07-11 11:53
This issue is still re-producible in Flutter 3.0.4

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.4 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (10 days ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.40.113

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1592, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1592 on channel master at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 19b3279497 (54 minutes ago), 2022-07-11 02:10:07 -0400
    • Engine revision 372d2f411b
    • Dart version 2.18.0 (build 2.18.0-271.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.40.113

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by Piinks** [comment] 2022-12-02 19:50
We're in the stages of planning to resolve this, so I am going to close this issue to refer to https://github.com/flutter/flutter/issues/52207 to focus all conversation and updates in one place. That one has the highest number of upvotes regarding this performance issue, and is why I chose it. Thank you all for providing test cases on this!

**Closed by Piinks** 2022-12-02 19:50 UTC
Labels: framework, severe: performance, f: scrolling, has reproducible steps, P3, found in release: 3.0, found in release: 3.1
