### ISSUE TITLE
FlutterActivity in the background of a Fullscreen transparent native Activity spills to the Notch area

### ISSUE THREAD

**Issue by LTPhantom** [flutter/flutter#146092] opened 2024-04-01 18:57 UTC
### Steps to reproduce

0. This happens on Android devices with a notch.
1. From a FlutterActivity (Android) start a new Fullscreen Activity with transparent background. The theme of the Fullscreen activity has the following configuration:
```
<item name="android:windowIsTranslucent">true</item>
<item name = "android:windowActionBar">false</item>
<item name = "android:windowNoTitle">true</item>
<item name="android:windowBackground">@android:color/transparent</item>
<item name="android:windowContentOverlay">@null</item>
<item name="android:backgroundDimEnabled">false</item>
```

### Expected results

After switching to fullscreen (hiding the status bar), the FlutterActivity should respect the Notch area and do not resize to occupy that area. Same as with Android native apps.

### Actual results

The fullscreen Android activity keeps out of the notch area, but the background FlutterActivity spills to that area making it visible.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

* Flutter Behavior

https://github.com/flutter/flutter/assets/1921175/16b6798f-145c-43aa-8c99-6a4461de8c4e

* Native Android Behavior

https://github.com/flutter/flutter/assets/1921175/b83b0738-e070-408a-8e28-b29412a58c0a

</details>

### Logs

<details open><summary>Logs</summary>

```console
N/A
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4 23E214 darwin-arm64, locale en)
    • Flutter version 3.19.3 on channel stable at ~/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (4 weeks ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at ~/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = ~/Library/Android/sdk
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 14.4 23E214 darwin-arm64
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 123.0.6312.87

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by huycozy** [comment] 2024-04-02 08:32
Hi @LTPhantom
Have you tried using `windowLayoutInDisplayCutoutMode` property? Could you share a minimal sample project so we can try reproducing this?

**Comment by LTPhantom** [comment] 2024-04-09 16:51
Hi @huycozy 
Sure, here is a sample code I used to make the Flutter video: https://github.com/LTPhantom/SampleCodeRepository/tree/main/FlutterActivityCodeSample

**Comment by huycozy** [comment] 2024-04-10 06:20
Thanks for the sample code. I ran it on my device Pixel 7 with enabled Tall cutout from Developer options but couldn't see the actual result as yours. Below is the demo on it:

<details>
<summary>Demo</summary>


https://github.com/flutter/flutter/assets/104349824/63fb7111-a5dc-4a43-9d80-7b4263f8e6b7


</details>

I wonder if this is a device-specific issue. What device are you seeing the issue? This looks similar to a case at https://github.com/flutter/flutter/issues/64274.

**Comment by LTPhantom** [comment] 2024-04-16 23:11
@huycozy Yeah so this is happening for devices running on Android API levels between 27 and 32. I am able to reproduce it by enabling the Cutout on the device Developer Options.

**Comment by huycozy** [comment] 2024-04-17 05:57
I think this is a device-specific issue as I see it occurs on my another device also on Android 14. Labeling this for other's input. 

| Pixel 7 (Android 14) ✅ | Galaxy Tab A7 Lite (Android 14) ❗ |
| --------------- | --------------- |
<video src="https://github.com/flutter/flutter/assets/104349824/603ce465-481b-4520-83a9-be1cccbe792b"/> | <video src="https://github.com/flutter/flutter/assets/104349824/d1152a04-7b9c-42c2-89f2-b1d6dbe970e4"/>


✅: No Issue ❗: Issue reproduced

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (8 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 123.0.6312.106

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.22.0-12.0.pre.32, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.22.0-12.0.pre.32 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 69c7fcb8aa (43 minutes ago), 2024-04-16 23:44:51 -0400
    • Engine revision 31b67985de
    • Dart version 3.5.0 (build 3.5.0-68.0.dev)
    • DevTools version 2.35.0-dev.8
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 123.0.6312.124

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by reidbaker** [comment] 2024-04-17 14:32
What happens if you enable kill background activities? My gut is that this is intended android behavior you are seeing and not a flutter bug.

**Comment by PMARZV** [comment] 2024-04-19 15:42
Im having the same problem that they are experiencing in the GAds sdk for android and im using compose, same top "padding" when launching an interstitial ad (fullscreen)

**Comment by reidbaker** [comment] 2024-04-19 15:46
@PMARZV thank you for your comment this further makes me think this a quirk of the android system when you have an activity with a transparent background that is not fullscreen laid over another activity .

**Comment by malandr2** [comment] 2024-04-30 14:29
@huycozy any input on how to resolve the issue on the Galaxy Tab A7 Lite? Is this considered working as intended or no?

**Comment by yaakovschectman** [comment] 2024-05-02 18:35
From triage: Closing as working as intended.

**Closed by yaakovschectman** 2024-05-02 18:35 UTC
Labels: e: device-specific, platform-android, waiting for customer response, engine, a: layout, has reproducible steps, team-android, found in release: 3.19, found in release: 3.22
