### ISSUE TITLE
Camera Video Recording Quality

### ISSUE THREAD

**Issue by markuspaschi** [flutter/flutter#20994] opened 2018-08-24 14:28 UTC
Hi, I'm using camera plugin to capture video. I changed multiple lines, but the problem exists in the sample as well. I'm using an **Oneplus 2** (real device) and the quality of the saved video is way to bad.
I get 1MB for 10 seconds of video recording. The resolution is fine (1080x1440) but i think the bitrate is not high enough.

Is there a way to change it?
In the CameraPlugin there is this line:

`mediaRecorder.setVideoEncodingBitRate(1024 * 1000);`

Or am i the only person facing this problem?

Question 2: The recorded video has an aspect ratio of 0.75 ( according to the resolution 1080x1440 ).
Is there a way to make a portrait video (full height  16 / 9)).

Greetings Markus
```
[√] Flutter (Channel dev, v0.7.0, on Microsoft Windows [Version 10.0.17134.228], locale de-DE)
    • Flutter version 0.7.0 at C:\src\flutter
    • Framework revision 09fe34708f (2 days ago), 2018-08-22 10:20:51 -0700
    • Engine revision 4b271b2e02
    • Dart version 2.1.0-dev.1.0.flutter-69fce633b7

[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.2
    • Java binary at: C:\src\android-studio3.3C6\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files (x86)\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Android Studio (version 3.3)
    • Android Studio at C:\src\android-studio3.3C6
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected devices (1 available)
    • ONE A2003 • 500fbec4 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by iozozturk** [comment] 2019-04-16 18:03
I just tried higher bit rate of `3048 * 1000` and video quality improved to much better state. Whereas as you might guess size of the file also tripled. So it might be better to give use some type of control over these values. For now you can change values in `CameraPlugin.java` file you can find in your project and experiment. Or fork the plugins project and use your fork and rebase time to time.

**Comment by jeffaknine** [comment] 2019-04-30 20:30
Hi, I was also wondering if there was a way to set the FPS while recording videos ? Like 240fps for slow motion etc.
Thanks

**Comment by liyuqian** [comment] 2019-11-17 23:01
@amirh @collinjackson : I have the same question --- does the camera plugin support slow motion (120fps or 240fps) video recording? If not, how much does it cost to add?

**Comment by TahaTesser** [comment] 2020-03-16 15:52
Duplicate of  [#26959](https://github.com/flutter/flutter/issues/26959)

**Closed by TahaTesser** 2020-03-16 15:52 UTC
Labels: p: camera, p: first party, plugin
