### ISSUE TITLE
Test coverage also for flutter drive

### ISSUE THREAD

**Issue by nicolalandro** [flutter/flutter#59239] opened 2020-06-11 06:50 UTC
## Use case
* the test piramid include the UI test
* some feature are tested oly with UI test
* but the code coverage can only tested with "flutter test --coverage" and thi option are not present with "flutter drive"

## Proposal
* add the param "--coverage" and the possibility to go into append to the test coverage in order to get the correct coverage.

**Comment by TahaTesser** [comment] 2020-06-11 12:02
hI @nicolalandro 
Please check this [comment](https://github.com/flutter/flutter/issues/7474#issuecomment-558882182) 

Closing as duplicate of https://github.com/flutter/flutter/issues/7474

**Closed by TahaTesser** 2020-06-11 12:02 UTC
