### ISSUE TITLE
throw PlatformException(code: errorCode, message: errorMessage, details: errorDetails);

### ISSUE THREAD

**Issue by SirMajed** [flutter/flutter#77109] opened 2021-03-03 00:08 UTC
Hello, I have a weird problem, I have an existed user in my firebase auth. so when I register a new user the code in try and catch
the code for the user registration:
```
AuthResult res;
    try {
      res = await _instance.createUserWithEmailAndPassword(
          email: account.getEmail(), password: account.getPassword());
      (account as User).id = res.user.uid;

      await Firestore.instance
          .collection('Users')
          .document((account as User).id)
          .setData((account as User).toJson());

      await signIn(account);
    } catch (e) {
      signOut();
      rethrow;
    }
```
and in the UI, I also have try and catch for firebase exception class that I already made that contains the error codes for firebase auth and firestore.
```
try {
  User user = new User(
    email: _email,
    password: _password,
    name: _name);
  await user.register();
  Navigator.of(context).pop();
}
on PlatformException
catch (exception) {
  String msg = FirebaseException
    .generateReadableMessage(exception);
  MyBar.customFlushBar(
    context: context,
    message: msg,
    icon: Icons.warning_amber_rounded);
}
}
```

But the problem is that the error is not even catched and the system stopped at this line in debug:
![Screenshot_8](https://user-images.githubusercontent.com/33690366/109732115-94ce6b00-7bcd-11eb-8656-bc272f048c3d.jpg)

I just want it to display the snackbar error instead of the system stop working,
I'm sorry for my English

**Comment by pedromassangocode** [comment] 2021-03-03 07:46
Hi @SirMajed 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-03 07:46 UTC
Labels: in triage
