### ISSUE TITLE
Shimmer package works for mobile but throws Unimplemented Error for web

### ISSUE THREAD

**Issue by tanya-555** [flutter/flutter#69391] opened 2020-10-30 11:52 UTC
dependency used : shimmer: ^1.1.2
![image](https://user-images.githubusercontent.com/52540265/97701911-27ea7d80-1ad4-11eb-98af-f6df857c6bac.png)

output of flutter doctor -v :

[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15 19A583 x86_64, locale en-IN)
    • Flutter version 1.23.0-18.1.pre at /Users/apple/development/flutter
    • Framework revision 198df796aa (2 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.111

! Doctor found issues in 2 categories.

**Comment by iapicca** [comment] 2020-10-30 12:12
@tanya-555 as [shimmer](https://pub.dev/packages/shimmer) is a 3rd party plugin
the right approach should be to open an issue on the dedicated [github](https://github.com/hnvn/flutter_shimmer/issues),
but in this case I see that such an [issue already exist](https://github.com/hnvn/flutter_shimmer/issues/25)
you may want to follow up there

**Comment by TahaTesser** [comment] 2020-10-30 14:57
Hi @tanya-555 
@iapicca is correct

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated repository 
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-30 14:57 UTC
