### ISSUE TITLE
[go_router] [bug] Deep linking misses query params

### ISSUE THREAD

**Issue by jagomf** [flutter/flutter#101816] opened 2022-04-13 12:26 UTC
## Steps to Reproduce

1. Create a `GoRoute` that reads at least 2 query parameters from `state`.
```dart
GoRoute(
  path: '/section',
  builder: (final context, final state) {
    final p1 = state.queryParams['p1'];
    final p2 = state.queryParams['p2'];
    return MyScreen(p1: p1, p2: p2);
  },
),
```
2. Open URL with those 2 query parameters filled (or use [ADB command as featured on docs](https://docs.flutter.dev/development/ui/navigation/deep-linking#test-on-android-emulator)).
```
https://yoursite.com/section?p1=val1&p2=val2
```

**Expected results:** You can read/retrieve both values.

**Actual results:** Second query parameter and ahead are not retrieved
```dart
GoRoute(
  path: '/section',
  builder: (final context, final state) {
    final p1 = state.queryParams['p1'];
    print(p1); // prints 'val1'
    final p2 = state.queryParams['p2'];
    print(p1); // prints null
    return MyScreen(p1: p1, p2: p2);
  },
),
```

## Flutter version

Using Flutter stable 2.10.4

**Comment by danagbemava-nc** [comment] 2022-04-13 13:12
Hi @jagomf, thanks for filing the issue. 

Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and specify the version of `go_router` you're using. 

Also, what platforms are you experiencing this issue on?

Thank you

**Comment by jagomf** [comment] 2022-04-14 07:27
Hello @danagbemava-nc ,

Any piece of code that I provide further than the already provided (creating a route that is next to "/" and reading all its query params) will be pointless because deep linking can only be tested if you do own a domain.

I have experienced this issue in Android, but just because I have not still been able to set up the Apple app site association, meaning it might be happening in iOS as well.

**Comment by danagbemava-nc** [comment] 2022-04-14 13:21
Hi @jagomf,

Can you try running the command this way to see if the URL is properly parsed? 

```
adb shell 'am start -a android.intent.action.VIEW \
    -c android.intent.category.BROWSABLE \
    -d "yourscheme://yoursite.com/section?p1=pink&p2=floyd"'
```

**Comment by jagomf** [comment] 2022-04-17 18:07
Hello @danagbemava-nc ,

Just tested your tip, same command with the single quotes surrounding the adb shell command, and it now seems to be working fine. Thank you.

I believe the docs should be updated accordingly.

**Comment by danagbemava-nc** [comment] 2022-04-18 06:10
Hi @jagomf, thanks for confirming. 

Yes, the docs should be updated to specify how to run the command to account for multiple query parameters. I'll create an issue on the flutter website github repo so that it can be properly addressed since this is a doc on the website. 

Closing as solved. 

Thank you

**Closed by danagbemava-nc** 2022-04-18 06:10 UTC
Labels: in triage
