### ISSUE TITLE
Sending a message before the FlutterEngine has been run when using FlutterStreamHandler

### ISSUE THREAD

**Issue by ggirotto** [flutter/flutter#135613] opened 2023-09-27 16:22 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

This issue is tricky to reproduce, so I'll explain the process to do it but I won't be able to provide a full reproducible example.

This issue happens when using [Live Activities](https://pub.dev/packages/live_activities) plugin, but the issue is not with the plugin itself, but with the workflow when handling live activities on iOS. The issue happens when using this iOS feature combined with server-side updates for live activities using push notifications. (Ref: https://developer.apple.com/documentation/activitykit/updating-live-activities-with-activitykit-push-notifications).

The steps that create this inconsistency are:

1. Create live activity in the main Flutter app
2. User sends the app to background
3. Server sends an update push notification to the app
4. When this push notification is received, the live activity plugin tries to notify the app - which is in background - of the new received date.
5. This error is thrown (I'm assuming that because the app is in background?)

The plugin tries to communicate with the main app using `FlutterStreamHandler` protocol, and you can see the exactly line that it crashes here:

https://github.com/istornz/flutter_live_activities/blob/581933050e1f3bb081ca5dadd44f5e960be9f363/ios/Classes/SwiftLiveActivitiesPlugin.swift#L354C1-L354C16

This line is inside `monitorLiveActivity` which receives updates from the server when a push notification is received. It tries to send this updated information to the main app, but it may be in background, which I think may be the origin of the error.

Finally, I'm not sure if this is a bug or a incorrect implementation in the plugin. If this is not a problem with Flutter, how the plugin should handle this scenario? Should it dispose the sink events when the app goes to background? Or it must check if the app is in background and make no communications with the main app directly?

### Expected results

The main app would receive the message sent by the plugin.

### Actual results

The app crashes with the exception:

```
NSInternalInconsistencyException
Sending a message before the FlutterEngine has been run.
```

### Code sample

Described above

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.6 22G120 darwin-arm64, locale en-BR)
    • Flutter version 3.13.5 on channel stable at /Users/guilhermegirotto/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (8 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/guilhermegirotto/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (6 available)
    • WSC6X (mobile)              • 1234567                   • android-arm64  • Android 10 (API 29)
    • SM T735 (mobile)            • RX2W6004E3B               • android-arm64  • Android 13 (API 33)
    • sdk gphone64 arm64 (mobile) • emulator-5554             • android-arm64  • Android 13 (API 33) (emulator)
    • Girotto iPhone (mobile)     • 00008120-000130EE21B8C01E • ios            • iOS 16.7 20H19
    • macOS (desktop)             • macos                     • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)                • chrome                    • web-javascript • Brave Browser 117.1.58.131
    ! Error: Guilherme’s Apple Watch needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-09-28 07:43
Hi @ggirotto 
It would be best if reproducible with a minimal sample code instead of through a 3rd party plugin. However, based on the given case and error message above, I see there is an issue that could be similar https://github.com/flutter/flutter/issues/117523. If you have the entire crash stack trace, you can compare and see if it's indeed a similar issue. Otherwise, please share it here so that we can verify the issue further.

**Comment by ggirotto** [comment] 2023-10-12 21:47
Hey @huycozy sorry for the delay. The issue seems to share the same reason: some action happening while the app is in background. I can't create a reproducible sample with the example I gave above because it's very difficult and it would require some server-side integration. 

I can't think now of any simple example that would reproduce the same issue of "waking" an app that's in background without involving push notification and background mode for iOS. Not sure how can I help more than just describing the issue.

**Comment by huycozy** [comment] 2023-10-13 04:40
Thanks for your response. Sometimes the crash stack trace is enough to continue investigating the issue and https://github.com/flutter/flutter/issues/117523 has shared a such stack trace (even though it's from production). 

Based on your case and error message, I will close this in favor of #117523 to centralize it since that issue provided a stack trace. Please follow up on it for updates. It would be appreciated if you could help verify the patch fix on your end if needed (when have a patch fix).

**Closed by huycozy** 2023-10-13 04:40 UTC
Labels: in triage
