### ISSUE TITLE
Is it normal for Flutter to render relatively high resolution images with extreme pixelation?

### ISSUE THREAD

**Issue by nmcain** [flutter/flutter#65120] opened 2020-09-02 20:38 UTC
## Steps to Reproduce

1. Use a high-resolution image as an asset image in a small widget size
2. Run the app

**Expected results:** 
I was expecting the image to antialias, like these (at exact resolution):
![image](https://user-images.githubusercontent.com/18690588/92032705-69062180-ed1f-11ea-90f3-c7fe355ef6f3.png)
![image](https://user-images.githubusercontent.com/18690588/92032742-76231080-ed1f-11ea-8b6c-6fd5c3aa108f.png)

**Actual results:** 
Highly aliased images, very pixelated
![image](https://user-images.githubusercontent.com/18690588/92032570-3eb46400-ed1f-11ea-9c7f-95257c5e3d8d.png)
![image](https://user-images.githubusercontent.com/18690588/92032604-4c69e980-ed1f-11ea-99e6-1df078d3b157.png)

<details>
  <summary>Logs</summary>

No errors are thrown aside from the app being too small at startup (not an issue)
```
[   +6 ms] ** BUILD SUCCEEDED **
[  +44 ms] Building macOS application... (completed in 20.8s)
[   +5 ms] executing: /usr/bin/plutil -convert json -o -
/Users/nmcain/Documents/gnome-desktop-flutter/build/macos/Build/Products/Debug/pangolin_desktop.app/Contents/Info.plist
[  +19 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Users/nmcain/Documents/gnome-desktop-flutter/build/macos/Build/Products/Debug/pangolin_desktop.app/Contents/Info.plist
[        ] {"CFBundleName":"pangolin_desktop","DTXcode":"1120","DTSDKName":"macosx10.15","NSHumanReadableCopyright":"Copyright © 2020 system. All rights
reserved.","DTSDKBuild":"19B89","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"18G5033","NSPrincipalClass":"NSApplication","CFBundl
eIconName":"AppIcon","CFBundlePackageType":"APPL","CFBundleIconFile":"AppIcon","CFBundleSupportedPlatforms":["MacOSX"],"CFBundleShortVersionString":"1.0.0","NSMai
nNibFile":"MainMenu","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"pangolin_desktop","DTCompiler":"com.apple.compilers.llvm.clang.1_0","CFBundleIden
tifier":"system.pangolinDesktop","DTPlatformVersion":"GM","DTXcodeBuild":"11B500","LSMinimumSystemVersion":"10.11","DTPlatformBuild":"11B500"}
[+1925 ms] Observatory URL on device: http://127.0.0.1:59119/E8V3HQEPYF8=/
[   +6 ms] Caching compiled dill
[ +196 ms] Connecting to service protocol: http://127.0.0.1:59119/E8V3HQEPYF8=/
[ +276 ms] Successfully connected to service protocol: http://127.0.0.1:59119/E8V3HQEPYF8=/
[        ] Waiting for macOS to report its views...
[   +6 ms] Waiting for macOS to report its views... (completed in 5ms)
[  +13 ms] DevFS: Creating new filesystem on the device (null)
[  +22 ms] DevFS: Created new filesystem on the device
(file:///var/folders/gx/ktkyx8b10sq9ky8gchz3kjq80000gn/T/system.pangolinDesktop/gnome-desktop-flutter16o5eW/gnome-desktop-flutter/)
[   +4 ms] Updating assets
[ +845 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[  +10 ms] Syncing files to device macOS...
[   +2 ms] Scanning asset files
[   +8 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:GeneratedApp/main.dart 1213edc1-81bf-4ee0-902d-4241b0b555f3
[        ] <- 1213edc1-81bf-4ee0-902d-4241b0b555f3
[ +106 ms] Updating files
[ +873 ms] flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[        ] flutter: The following assertion was thrown during layout:
[        ] flutter: A RenderFlex overflowed by 161 pixels on the right.
[        ] flutter: 
[        ] flutter: The relevant error-causing widget was:
[        ] flutter:   Row file:///Users/nmcain/Documents/gnome-desktop-flutter/lib/main.dart:345:30
[        ] flutter: 
[        ] flutter: The overflowing RenderFlex has an orientation of Axis.horizontal.
[        ] flutter: The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
[        ] flutter: black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
[        ] flutter: Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
[        ] flutter: RenderFlex to fit within the available space instead of being sized to their natural size.
[        ] flutter: This is considered an error condition because it indicates that there is content that cannot be
[        ] flutter: seen. If the content is legitimately bigger than the available space, consider clipping it with a
[        ] flutter: ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
[        ] flutter: like a ListView.
[  +24 ms] flutter: The specific RenderFlex in question is: RenderFlex#39716 OVERFLOWING:
[        ] flutter:   needs compositing
[        ] flutter:   creator: Row ← Padding ← DecoratedBox ← ConstrainedBox ← Container ← BackdropFilter ← ClipRRect ←
[        ] flutter:     _PointerListener ← Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector ← ⋯
[        ] flutter:   parentData: offset=Offset(8.0, 8.0) (can use size)
[        ] flutter:   constraints: BoxConstraints(w=384.0, h=34.0)
[        ] flutter:   size: Size(384.0, 34.0)
[        ] flutter:   direction: horizontal
[        ] flutter:   mainAxisAlignment: spaceBetween
[        ] flutter:   mainAxisSize: max
[        ] flutter:   crossAxisAlignment: center
[        ] flutter:   textDirection: ltr
[        ] flutter:   verticalDirection: down
[        ] flutter: ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[+2965 ms] DevFS: Sync finished
[        ] Syncing files to device macOS... (completed in 3,988ms, longer than expected)
[        ] Synced 83.0MB.
[   +1 ms] <- accept
[   +1 ms] Connected to _flutterView/0x7f95a3840820.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:59119/E8V3HQEPYF8=/

```

Analysis (no relevant issues here, just for the sake of transparency)
```
Analyzing gnome-desktop-flutter...                                      

   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          SearchWidget._context • lib/applications/browser/searchbar.dart:20:7 • must_be_immutable
   info • The value of the field '_context' isn't used • lib/applications/browser/searchbar.dart:23:16 • unused_field
   info • Unused import: 'dart:io' • lib/applications/containers.dart:20:8 • unused_import
   info • Unused import: 'dart:async' • lib/applications/containers.dart:21:8 • unused_import
   info • The declaration '_FilesBar' isn't referenced • lib/applications/files/main.dart:372:7 • unused_element
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          SearchWidget._context • lib/applications/files/searchbar.dart:19:7 • must_be_immutable
   info • The value of the field '_context' isn't used • lib/applications/files/searchbar.dart:21:16 • unused_field
   info • Unused import: 'calculator.dart' • lib/applications/imports.dart:17:8 • unused_import
   info • Unused import: 'package:GeneratedApp/widgets/cards.dart' • lib/applications/imports.dart:18:8 • unused_import
   info • Unused import: 'developer.dart' • lib/applications/imports.dart:19:8 • unused_import
   info • Unused import: 'editor.dart' • lib/applications/imports.dart:20:8 • unused_import
   info • Unused import: 'monitor.dart' • lib/applications/imports.dart:21:8 • unused_import
   info • Unused import: 'welcome.dart' • lib/applications/imports.dart:23:8 • unused_import
   info • Unused import: '../settings.dart' • lib/applications/imports.dart:24:8 • unused_import
   info • Unused import: '../themes/main.dart' • lib/applications/imports.dart:25:8 • unused_import
   info • The value of the local variable 'wordToStyle' isn't used • lib/applications/terminal/root/root-widget.dart:69:11 • unused_local_variable
   info • The value of the local variable 'style' isn't used • lib/applications/terminal/root/root-widget.dart:70:11 • unused_local_variable
   info • Don't explicitly initialize variables to null • lib/applications/terminal/root/root-widget.dart:133:11 • avoid_init_to_null
   info • Dead code • lib/applications/terminal/root/root-widget.dart:198:5 • dead_code
   info • The value of the local variable 'wordToStyle' isn't used • lib/applications/terminal/terminal-widget.dart:69:11 • unused_local_variable
   info • The value of the local variable 'style' isn't used • lib/applications/terminal/terminal-widget.dart:70:11 • unused_local_variable
   info • Don't explicitly initialize variables to null • lib/applications/terminal/terminal-widget.dart:133:11 • avoid_init_to_null
   info • Dead code • lib/applications/terminal/terminal-widget.dart:198:5 • dead_code
   info • Unused import: 'dart:io' • lib/applications/welcome.dart:17:8 • unused_import
   info • Dead code • lib/applications/welcome.dart:707:5 • dead_code
   info • 'inheritFromWidgetOfExactType' is deprecated and shouldn't be used. Use dependOnInheritedWidgetOfExactType instead. This feature was deprecated after
          v1.12.1. • lib/commons/constants.dart:27:15 • deprecated_member_use
   info • Unused import: 'dart:io' • lib/main.dart:17:8 • unused_import
   info • Unused import: 'package:GeneratedApp/applications/welcome.dart' • lib/main.dart:21:8 • unused_import
   info • Unused import: 'package:path_provider/path_provider.dart' • lib/main.dart:29:8 • unused_import
   info • Unused import: 'menu.dart' • lib/main.dart:36:8 • unused_import
   info • Unused import: 'app_toggle.dart' • lib/main.dart:44:8 • unused_import
   info • The declaration '_launcherToggleKey' isn't referenced • lib/main.dart:61:30 • unused_element
   info • The declaration '_statusToggleKey' isn't referenced • lib/main.dart:64:30 • unused_element
   info • The declaration '_overlayScaleTween' isn't referenced • lib/main.dart:67:21 • unused_element
   info • The declaration '_overlayOpacityTween' isn't referenced • lib/main.dart:68:21 • unused_element
   info • The declaration '_setOverlayVisibility' isn't referenced • lib/main.dart:82:6 • unused_element
   info • 'inheritFromWidgetOfExactType' is deprecated and shouldn't be used. Use dependOnInheritedWidgetOfExactType instead. This feature was deprecated after
          v1.12.1. • lib/model.dart:56:19 • deprecated_member_use
   info • 'ancestorWidgetOfExactType' is deprecated and shouldn't be used. Use findAncestorWidgetOfExactType instead. This feature was deprecated after v1.12.1. •
          lib/model.dart:57:19 • deprecated_member_use
   info • 'inheritFromWidgetOfExactType' is deprecated and shouldn't be used. Use dependOnInheritedWidgetOfExactType instead. This feature was deprecated after
          v1.12.1. • lib/model.dart:125:19 • deprecated_member_use
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final:
          SearchWidget._context • lib/searchbar.dart:20:7 • must_be_immutable
   info • The value of the field '_context' isn't used • lib/searchbar.dart:23:16 • unused_field
   info • Unused import: 'package:GeneratedApp/applications/containers.dart' • lib/settings.dart:14:8 • unused_import
   info • Set literals weren't supported until version 2.2, but this code is required to be able to run on earlier versions •
          lib/utils/palette_generator.dart:356:35 • sdk_version_set_literal
   info • Unused import: 'package:GeneratedApp/commons/key_ring.dart' • lib/widgets/cards.dart:32:8 • unused_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: Window.customBar •
          lib/window/window.dart:26:7 • must_be_immutable
   info • Unused import: 'themes/main.dart' • lib/window_space.dart:23:8 • unused_import
   info • Unused import: 'dart:io' • test/custombar_test.dart:8:8 • unused_import
   info • Unused import: 'package:GeneratedApp/commons/key_ring.dart' • test/custombar_test.dart:13:8 • unused_import
   info • Unused import: 'package:hive/hive.dart' • test/custombar_test.dart:23:8 • unused_import
   info • Unused import: 'package:hive_flutter/hive_flutter.dart' • test/custombar_test.dart:24:8 • unused_import
   info • Unused import: 'package:path_provider/path_provider.dart' • test/custombar_test.dart:25:8 • unused_import
   info • Unused import: 'package:hive/src/box/box_impl.dart' • test/mocks.dart:3:8 • unused_import
  error • Target of URI doesn't exist: 'package:pangolin_desktop/main.dart' • test/widget_test.dart:11:8 • uri_does_not_exist
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function

54 issues found. (ran in 5.7s)
```

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.14.6 18G5033, locale en-US)
    • Flutter version 1.21.0-1.0.pre at /Users/nmcain/flutter
    • Framework revision f25bd9c55c (7 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nmcain/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1)
    • IntelliJ at /Users/nmcain/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.14.6 18G5033
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2020-09-03 07:59
Hi @nmcain,
Please provide a minimal complete reproducible code sample along with the images used and `pubspec.yaml` that shows the issue.
Thanks.

**Comment by nmcain** [comment] 2020-09-03 15:36
Use the below image,
![System Preferences](https://user-images.githubusercontent.com/18690588/92136045-67406a80-edc0-11ea-9efe-196cf7b883fa.png)
with this code:
```
import 'package:flutter/material.dart';

void main() {
  runApp(new MyApp());
}
class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Generated App',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
        primaryColor: const Color(0xFF2196f3),
        accentColor: const Color(0xFF2196f3),
        canvasColor: const Color(0xFFfafafa),
      ),
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
    @override
    Widget build(BuildContext context) {
      return new Scaffold(
        appBar: new AppBar(
          title: new Text('broken image'),
          ),
        body:
          new Center(
            child:
              new Image.asset(
                'img/SystemPreferences.png',
                fit:BoxFit.fill,
                width: 64.0,
                height: 64.0,
                ),
    
          ),
    
      );
    }
}
```

**Comment by nmcain** [comment] 2020-09-03 15:45
![image](https://user-images.githubusercontent.com/18690588/92137258-cb176300-edc1-11ea-9465-09cf98ccbbc4.png)
Here is the result of the code

**Comment by erickzanardo** [comment] 2020-09-04 00:45
I can confirm this and I have a hunch that this is been causing by skia, as this effect is also noticeable on web, but only when using canvas kit, without skia, the image is fine.

Without canvas kit:
<img width="501" alt="no_skia" src="https://user-images.githubusercontent.com/835641/92186942-bc1aca00-ee2e-11ea-88cf-2b159e33ce46.png">

With canvas kit:
<img width="501" alt="skia" src="https://user-images.githubusercontent.com/835641/92186955-c50b9b80-ee2e-11ea-8c8a-040cf58ddce2.png">

**Comment by erickzanardo** [comment] 2020-09-04 00:56
I dug a little more and discovered that that happens because the default `filterQuality` of `Image.asset` is `FilterQuality.low` (you can confirm here: https://api.flutter.dev/flutter/widgets/Image/Image.asset.html)

Adding `filterQuality: FilterQuality.high` to the `Image.asset` solved the weird looking.

**Comment by darshankawar** [comment] 2020-09-04 05:31
@nmcain Can you try above solution and see if it works for you ?
Thanks.

**Comment by darshankawar** [comment] 2020-09-07 06:17
Hi @nmcain,
Please see [this](https://github.com/flutter/flutter/issues/63397) for performance related issue related to Flutter web canvaskit and image rendering.
Thanks.

**Comment by nmcain** [comment] 2020-09-08 04:28
Thank you!

**Comment by darshankawar** [comment] 2020-09-08 05:32
@nmcain I'd suggest you follow-up in above linked ticket on your performance related question on image rendering.
Since your original question on high resolution image rendering is [resolved](https://github.com/flutter/flutter/issues/65120#issuecomment-687259261), I am going ahead and closing this issue.
If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-08 05:32 UTC
Labels: in triage
