### ISSUE TITLE
Tests are not working properly after upgrading to null safety. Incompatibilty issues.

### ISSUE THREAD

**Issue by davidcz95** [flutter/flutter#78313] opened 2021-03-16 10:34 UTC
Hello,
After upgrading flutter to null safety I am having a lot of issues with test library and now when I upgraded from 1.15.2 to the newest 1.16.8 it can't get past pub get with a message:
`Because every version of flutter_test from sdk depends on test_api 0.2.19 and test >=1.16.7 depends on test_api 0.3.0, flutter_test from sdk is incompatible with test >=1.16.7. `

This is my flutter doctor:
```
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19041.867], locale pl-PL)
    • Flutter version 2.0.2 at C:\src\flutter
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Dawid Czuchnowski\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\Dawid Czuchnowski\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at D:\IntelliJ IDEA Community Edition 2020.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\Dawid Czuchnowski\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.54

• No issues found!
```

**Comment by pedromassangocode** [comment] 2021-03-16 10:38
Duplicate of https://github.com/flutter/flutter/issues/77681. Please post your feedback on that issue and subscribe for updates.
Thank you

**Closed by pedromassangocode** 2021-03-16 10:38 UTC
Labels: in triage
