### ISSUE TITLE
Error: Member not found: 'UnicodeChar'.

### ISSUE THREAD

**Issue by gbbest15** [flutter/flutter#103730] opened 2022-05-13 18:05 UTC
After Upgrading i keep getting this error

```
: Error: Member not found: 'UnicodeChar'.
  int get UnicodeChar => Char.UnicodeChar;
                              ^^^^^^^^^^^
: Error: Setter not found: 'UnicodeChar'.
  set UnicodeChar(int value) => Char.UnicodeChar = value;

                                     ^^^^^^^^^^^
: Error: Member not found: 'AsciiChar'.
  int get AsciiChar => Char.AsciiChar;
                            ^^^^^^^^^
: Error: Setter not found: 'AsciiChar'.
  set AsciiChar(int value) => Char.AsciiChar = value;

                                   ^^^^^^^^^
```

Flutter doctor
```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.1 21C52 darwin-arm, locale
    en-NG)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

error posted on stackoverflow
[https://stackoverflow.com/questions/72233476/flutter-error-member-not-found-unicodechar](url)

**Comment by stuartmorgan** [comment] 2022-05-13 18:41
Duplicate of https://github.com/flutter/flutter/issues/103674

**Closed by stuartmorgan** 2022-05-13 18:41 UTC
