### ISSUE TITLE
[web] Flutter web using WebAssembly (WASM)

### ISSUE THREAD

**Issue by iapicca** [flutter/flutter#41062] opened 2019-09-22 17:50 UTC
## Proposal

I spotted several articles about WASM being faster then JS [[1](https://medium.com/@torch2424/webassembly-is-fast-a-real-world-benchmark-of-webassembly-vs-es6-d85a23f8e193), [2](https://medium.com/@OPTASY.com/webassembly-vs-javascript-is-wasm-faster-than-js-when-does-javascript-perform-better-db86d2ecf2cc)]
I see the topic has been touched in this old (closed) issues [[3](https://github.com/flutter/flutter/issues/14868), [4](https://github.com/flutter/flutter/issues/25406)],
these open issues on with the dart team [[5](https://github.com/dart-lang/sdk/issues/32894), [6](https://github.com/dart-lang/sdk/issues/37355), [7](https://github.com/dart-lang/sdk/issues/37882)]
and this seemingly abandoned discussion on google groups [[8](https://groups.google.com/a/dartlang.org/forum/#!topic/misc/szGdXdLrZM8%5B1-25%5D)];

the question and the implicit proposal is:
**why flutter web doesn't use WASM instead of dart2js** ?

thank you for your time

(asked also on [stack](https://stackoverflow.com/questions/58051917/should-flutter-web-use-wasm-instead-of-dart2js))

**Comment by kaleidawave** [comment] 2019-09-22 19:21
Hmm there is some misconception that wasm is a replacement for javascript. As of the time of this comment Wasm does not have the ability to interact with the dom or any other web api's. So wasm is used to do heavy complex computation "on the side" and then return the results to js so it can draw to the canvas etc..

If this were to be implement, the flutter compiler would have split logic and browser api calls. Which for flutter applications there is likely to be more web api calls than complex knowledge. What I could possibly see happening is compiling the recent `dart:ffi` api to the wasm js api or something like that. But yeah I am unsure of it. It would be nice to see something like this to happen similar to C# Blazor... 

But I think wasm isn't really meant for building performant ui's. It's really made for doing heavy computation for canvas rendering and such. So for a flutter project I don't think the performance impacts would pay of...

**Comment by iapicca** [comment] 2019-09-22 21:30
> Hmm there is some misconception that wasm is a replacement for javascript. As of the time of this comment Wasm does not have the ability to interact with the dom or any other web api's. So wasm is used to do heavy complex computation "on the side" and then return the results to js so it can draw to the canvas etc..
> 
> If this were to be implement, the flutter compiler would have split logic and browser api calls. Which for flutter applications there is likely to be more web api calls than complex knowledge. What I could possibly see happening is compiling the recent `dart:ffi` api to the wasm js api or something like that. But yeah I am unsure of it. It would be nice to see something like this to happen similar to C# Blazor...
> 
> But I think wasm isn't really meant for building performant ui's. It's really made for doing heavy computation for canvas rendering and such. So for a flutter project I don't think the performance impacts would pay of...
@kaleidawave 
thank you for the explanation, if I can use your expertise for one more question:
what about running the flutter rendering with wasm, wouldn't be more preformant?
(the link [5] of the initial post seams to suggest that also running 
dart in wasm would give an advantage to sass/css, if I've understood correctly)

**Comment by kaleidawave** [comment] 2019-09-22 22:22
Hmm, I am not sure as I don't really use flutter. **I guess** flutter web basically compiles a flutter app to pwa. If the flutter `RenderBox` object transpiles to a `CanvasRenderingContext2D` from the canvas api then any dart logic code used to decide how things are rendered on the `RenderObject` could be converted to web assembly code for *potentially* more performance. **But** the bindings for the `RenderBox` would still have to be implemented in js. Would have to get ask a maintainer of the Flutter web compile step for clarification on that though. 

As for css/styling, wasm has nothing to do that and would not affect it in any way, so I am unsure what they are talking about. I don't know if Flutter web generates css or just implements styles through javascript but wasm wouldn't help as it cannot access web api's (yet?)

If there is considerable demand for Flutter's `RenderBox`  on the web then I could see a appeal for a wasm build step in the flutter web compiler/transpiler but as of now implementing it would be nonessential.

**Comment by JarrodCColburn** [comment] 2019-09-22 23:04
Relative to this... Emscipten's `emcc` can compile `c` to wasm. Emcc has a `file system api` that adapts many of c's `stdlib` calls to webassembly, please see https://emscripten.org/docs/api_reference/Filesystem-API.html for use in browser. Example, obscuring filesystem calls as IndexedDB. Is there any chance that a subset of dart-lang `c` code can be compiled to wasm? ...What I would like to produce is an `dart:io` library that can be used in the browser. Does anyone think this is possible? I tried looking at it the other day but I am unfamiliar with ninja and how to incorporate emcc. thank

**Comment by JarrodCColburn** [comment] 2019-09-22 23:32
Assuming dart-lang could be compiled to LLVM's bitcode (not AOT or JS) and exported as wasm ... and because SKIA has a wasm implementation (https://skia.org/user/modules/canvaskit) ...couldn't Flutter web exist with only a handful of web API calls?

**Comment by yjbanov** [comment] 2019-09-23 03:58
While we do not yet have a dart2wasm compiler, we have a super-experimental CanvasKit-based compositor (it uses WebGL and WebAssembly). If you like living dangerously, you can enable it by setting the `FLUTTER_WEB_USE_SKIA` environment variable to `true` and recompile the app ([more info](https://github.com/flutter/engine/blob/fad38e252f0748d49471bf2e09a2eb74ea04ce0b/lib/web_ui/lib/src/engine/compositor/initialization.dart#L8)).

@hterkelsen can tell us more about what it can and cannot do today.

**Comment by AppleEducate** [comment] 2019-10-29 13:06
This would also work well with [this project](https://github.com/flutter-rs/flutter-rs) too. WebAssembly can help in more areas too. With a dart2wa tool we could even use it on the server with [wasi](https://github.com/WebAssembly/WASI).

This would also help make the applications safer and faster.

**Comment by ThinkDigitalSoftware** [comment] 2019-12-03 14:50
I'm sure binaryen has been considered during this discussion, but just incase it hasn't and can prove useful for dart2wasm, here's a [link](https://github.com/WebAssembly/binaryen)

**Comment by catalsdevelop** [comment] 2019-12-09 21:51
I set the `FLUTTER_WEB_USE_SKIA` env to `true`, but nothing changed. @yjbanov 

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.13.0, on Mac OS X 10.14.6 18G95, locale en-NZ)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (3 available)

• No issues found!
```
compile command
```
$FLUTTER_WEB_USE_SKIA=true flutter build web --release
```

**Comment by jonahwilliams** [comment] 2019-12-09 22:01
FYI @yjbanov I would strongly recommend that FLUTTER_WEB_USE_SKIA is referred to as a dart-define and not referred to as an environment variable in documentation

**Comment by yjbanov** [comment] 2019-12-09 22:46
We don't have any documentation for this. I updated my comment above with the latest info.

**Comment by michaellee8** [comment] 2020-04-18 02:20
I have read that Flutter in iOS emit llvm ir which is then optimized by xcode's compiler. Is it possible to use the llvm ir functionality? Where should I look at if I want to see the llvm ir output component of Flutter SDK? Or is it still based on the dartino version here? https://github.com/dartino/sdk/tree/llvm

**Comment by secretshardul** [comment] 2020-06-01 12:12
Check out [Microsoft's .NET to WASM project, Blazor](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-now-available/). Will Flutter web move on similar lines one day?

**Comment by serefarikan** [comment] 2020-06-01 14:31
Please note that even though a WASM based rendererer can have performance benefits for various scenarios (such as implementing performant table/tree components etc), it'd also mean Flutter web cannot use any of the existing DOM based js libraries. 

At the moment, it is possible to create, modify and pass DOM nodes to existing js libraries from Flutter Web. D3 is one such library. There is a whole category of applications that would benefit enormously from the existing javascript ecosystem such as D3 or browser based code editors such as Ace or Monaco. 

Reimplementing these with a WASM based canvas is not realistic.  So as much as I'd like to see Flutter Web support a WASM/WebGL renderer, I think it would be good to keep in mind the cons of this option. Having WASM and DOM both would be great. Mixing these together in the same Flutter Web application would be awesome.

**Comment by lucaszanella** [comment] 2020-07-05 08:09
So there's no way of rendering textures in flutter web without WASM? I wanted to play videos from an RTSP camera

**Comment by Sunbreak** [comment] 2020-08-18 05:16
> @lucaszanella So there's no way of rendering textures in flutter web without WASM? I wanted to play videos from an RTSP camera

A little off topic.

I'm working on web sport for https://github.com/woodemi/quick-scan-flutter. It works on `HtmlElementView` with `<video>` tag.

These repos are quite inspiring as well:
- https://github.com/tekartik/app_camera.dart/tree/master/camera_web
- https://github.com/flutter/plugins/tree/master/packages/video_player/video_player_web

**Comment by Sunbreak** [comment] 2020-08-18 05:40
> @secretshardul  Check out [Microsoft's .NET to WASM project, Blazor](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-now-available/). Will Flutter web move on similar lines one day?

Do you mean `CanvasKit`? https://medium.com/flutter/flutter-web-support-updates-8b14bfe6a908

**Comment by iapicca** [comment] 2021-07-25 08:05
compiling dart to js [holds back dart-lang features](https://github.com/dart-lang/language/issues/1159)

**Comment by rafalsobota** [comment] 2021-07-28 12:26
Official blog post about Dart and WASM: https://medium.com/dartlang/experimenting-with-dart-and-wasm-ef7f1c065577

**Comment by cedvdb** [comment] 2021-08-01 13:36
That article is a good read. It still sounds like a long way to go (years).

**Comment by tsavo-vdb-knott** [comment] 2021-10-07 18:39
This Gentleman is doing something interesting https://dev.to/sunshine-chain/dart-meets-rust-a-match-made-in-heaven-9f5

**Comment by iapicca** [comment] 2022-01-11 18:04
> We also plan to expand Dart's compilation toolchain to support compiling to Wasm, contingent on the timely standardisation of WasmGC.

from [2022 roadmap](https://github.com/flutter/flutter/wiki/Roadmap#dart)

**Comment by caniko** [comment] 2022-03-22 10:26
Would this implementation make running [Python](https://pythondev.readthedocs.io/wasm.html) possible in a flutter web app?

**Comment by caniko** [comment] 2022-08-23 15:05
> @caniko I would assume that it's possible for wasm to interop with each other and for flutter to call wasm functions just like the js bindings toda

The issue is that flutter is compiled so the web-specific bindings have to be in Dart-lang, which is really annoying.

**Comment by michaellee8** [comment] 2023-01-26 00:38
Nice to hear that Flutter will be going the WASM route. Are there any technical deep dive articles indicating the Flutter team's intended approach on this? I meant how is WASM going to be implemented in Flutter web? Like having only the flutter dart code compiled to WebAssembly like JS or having the whole Dart VM compiled to WASM and then execute Flutter's code in an interpreter or JIT (not sure if it is possible to do JIT in WASM), and most importantly how will the transition to WebAssembly affect Flutter web's hot reload capability? It is well understood that it is extremely hard to achieve hot reload in dart compiled to JS since you cannot really get Dart VM's hot reload capability into the JS environment, and JS hot reload need to be done by injecting JS code incrementally transpiled by Dart VM into the browser, so it is hard to achieve, but how will the WebAssembly route affect this landscape? I mean I liked Flutter a lot but considering its rendering architecture and lack of hot reload in web I won't really consider Flutter web for developing gemeral websites currently, it is too far from both the developer experience and user experience of more general frameworks like React and Angular. Using Flutter web in some highly client-sided applications that already had an Flutter mobile application, like games, would be the only use cases I consider Flutter web currently, but the lack of hot reload is still making the development experience difficult. I think if Flutter managed to support hot reload in web then more usecases in web can be considered, for now Flutter web is merely just a way to export an existing mobile app to run in the web.

**Comment by iapicca** [comment] 2023-01-26 09:27
> [...] most importantly how will the transition to WebAssembly affect Flutter web's hot reload capability? It is well understood that it is extremely hard to achieve hot reload in dart compiled to JS since you cannot really get Dart VM's hot reload capability into the JS environment, and JS hot reload need to be done by injecting JS code incrementally transpiled by Dart VM into the browser, so it is hard to achieve, but how will the WebAssembly route affect this landscape? I mean I liked Flutter a lot but considering its rendering architecture and lack of hot reload in web I won't really consider Flutter web for developing gemeral websites currently [...]

I'd go into the `hot-reload` rabbit hole in this issue, maybe is better to address this in the issue linked below
- https://github.com/flutter/flutter/issues/53041

**Comment by eyebrowsoffire** [comment] 2023-05-25 20:16
We now have compilation to wasm via `flutter build web --wasm` in the flutter tool in the master branch. I'm going to go head and close this issue.

**Closed by eyebrowsoffire** 2023-05-25 20:16 UTC
Labels: new feature, engine, dependency: dart, customer: crowd, platform-web, passed first triage, P3, customer: chilli
