### ISSUE TITLE
[Impeller] Incorrect Arabic Text Rendering

### ISSUE THREAD

**Issue by michaelsoliman1** [flutter/flutter#119805] opened 2023-02-02 10:28 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Open the dialog to see that arabic text is not rendered properly 
3. Toggle commented style lines to see that arabic text is not rendered properly 

**Expected results:** 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/40867495/216297753-42b8edda-96a8-4287-9b7f-d682299df702.png">

**Actual results:** 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/40867495/216297885-534784a0-bd87-472a-b7ca-74c51c372746.png">

Also the font weight is not correctly applied for ar text

related issues: 
[#119489](https://github.com/flutter/flutter/issues/119489)
[#117428](https://github.com/flutter/flutter/issues/117428)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text(arStrings[0]),
        ),
        body: Builder(builder: (context) {
          return InkWell(
              onTap: () {
                showDialog(
                  context: context,
                  builder: (context) {
                    return AlertDialog(
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                      title: Center(child: Text(arStrings[1])),
                      actionsAlignment: MainAxisAlignment.center,
                      actionsPadding: const EdgeInsets.all(15),
                      titleTextStyle:
                          Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold),
                      content: Text(arStrings[2]),
                      contentTextStyle: Theme.of(context).textTheme.titleMedium,
                    );
                  },
                );
              },
              child: Container(
                padding: const EdgeInsets.all(20),
                child: Center(
                  child: Column(
                    children: [
                      Text(
                        "English Text",
                        // style: const TextStyle(fontWeight: FontWeight.w600),
                        style: Theme.of(context)
                            .textTheme //
                            .titleLarge //
                            ?.copyWith(fontWeight: FontWeight.w900),
                      ),
                      const SizedBox(height: 20),
                      Text(
                        arStrings[1],
                        // toggling this line breaks all text!
                        // style: const TextStyle(fontWeight: FontWeight.w600),
                        // toggling this line fixes it!
                        // but neglects the font weight
                        // style: Theme.of(context)
                        //     .textTheme //
                        //     .titleLarge //
                        //     ?.copyWith(fontWeight: FontWeight.w900),
                      ),
                      const SizedBox(height: 20),
                      Text(
                        arStrings[2],
                        // toggling this line breaks it!
                        // style: const TextStyle(fontWeight: FontWeight.w600),
                        // toggling this line fixes it!
                        // style: Theme.of(context).textTheme.titleMedium,
                      ),
                    ],
                  ),
                ),
              ));
        }),
      ),
    );
  }
}

final arStrings = [
  "الرئيسية",
  "تسجيل الخروج ",
  "هل أنت متأكد أنك تريد تسجيل الخروج",
];

```

</details>

<details>
  <summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel master, 3.8.0-1.0.pre.32, on macOS 12.6 21G115 darwin-arm64, locale en-EG)
    • Flutter version 3.8.0-1.0.pre.32 on channel master at /Users/michael/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9daa9aac4 (6 hours ago), 2023-02-01 22:59:24 -0500
    • Engine revision 679c4b42e2
    • Dart version 3.0.0 (build 3.0.0-192.0.dev)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/michael/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 14 Pro (mobile)      • DF465456-B470-4FBE-84DF-3B4653EC517F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2023-02-02 16:04
Hey. I don't see any difference other than the font being a bit more bold. Could you point out a glyph that doesn't look like it's supposed to?

#### Without impeller

![image](https://user-images.githubusercontent.com/50555895/216376191-0750c5e2-1504-4d8f-b7d2-15812823dbda.png)

#### With impeller

![image](https://user-images.githubusercontent.com/50555895/216376591-75c5028b-4cad-4b31-adf1-07dd071c8360.png)

**Comment by michaelsoliman1** [comment] 2023-02-02 18:00
without impeller (left), with impeller (right)
<img width="312" alt="image" src="https://user-images.githubusercontent.com/40867495/216398337-4ea47798-f6bb-4d7d-8649-2359811f4e6d.png"><img width="312" alt="image" src="https://user-images.githubusercontent.com/40867495/216397879-87f13368-dff5-498f-9275-4e9e639c0417.png">

in dialog- without impeller (left), with impeller (right)
<img width="312" alt="image" src="https://user-images.githubusercontent.com/40867495/216398410-543bbb0a-e65c-44d5-b5fb-29e313588ecd.png"><img width="312" alt="image" src="https://user-images.githubusercontent.com/40867495/216398729-3e4708d9-4fdb-4b92-8106-6c6ca1e77829.png">

Although it might not appear when you first load the app, but when you change the font weight you get unexpected results, not the weight but the glyphs become weird (see video below)

https://user-images.githubusercontent.com/40867495/216402315-d17ed2ea-931e-4bbe-a0da-b21533067b4a.mov

Notice how the font breaks in the second and third when you change the font weight in only the second one

**Comment by jason-simmons** [comment] 2023-02-02 22:24
The font weight issue may be happening because it looks like Impeller is not applying all of the flags in the `SkFont` attached to each text run in the `SkTextBlob`.

`SkFont` contains an `isEmbolden()` flag indicating that the typeface should be drawn with a wider stroke in order to simulate a bold font.  Impeller's `Font` is not transferring this flag.

Flutter text layout may also set `SkFont's` `skewX` property, which is used to simulate italics.

**Comment by exaby73** [comment] 2023-02-03 06:00
Thanks @michaelsoliman1 for the detailed explanation and @jason-simmons for the insights :) I can reproduce this issue. Adding relevant labels

**Comment by NikosTsesmelis** [comment] 2023-02-03 12:33
This issue is also present in greek.

![skia](https://user-images.githubusercontent.com/100851392/216604452-2954775c-049c-4ab3-b928-13ab741e0f2c.jpeg)
![impeller](https://user-images.githubusercontent.com/100851392/216604474-5c482a6f-21b2-43f7-adb0-223d8762c8b9.jpeg)

**Comment by NikosTsesmelis** [comment] 2023-02-03 12:36
Also the font weights seem to be bolder overall

**Comment by NikosTsesmelis** [comment] 2023-02-03 13:55
Ok my bad this also happens with english so it seems that texts in general are not rendered correctly

![english-impeller](https://user-images.githubusercontent.com/100851392/216620856-f8eac763-491b-4597-bfce-08672e058ad6.jpeg)

**Closed** 2023-02-04 06:34 UTC
Labels: engine, severe: rendering, has reproducible steps, P2, impeller, found in release: 3.7, found in release: 3.8

**Comment by michaelsoliman1** [comment] 2023-02-04 15:44
Hi again, 
I'm still having the same behavior on the master channel
```
Flutter (Channel master, 3.8.0-4.0.pre.21, on macOS 12.6 21G115 darwin-arm64, locale en-EG)
    • Flutter version 3.8.0-4.0.pre.21 on channel master at /Users/michael/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 61f6a0bcd4 (7 hours ago), 2023-02-04 03:08:35 -0500
    • Engine revision c7a4bbab0e
    • Dart version 3.0.0 (build 3.0.0-204.0.dev)
    • DevTools version 2.21.1
```
