### ISSUE TITLE
Listview overlapping animation

### ISSUE THREAD

**Issue by alirezava** [flutter/flutter#66820] opened 2020-09-28 13:00 UTC
There is very strange behavior from listview when it's not taking the full length of the screen and in a column.

When you scroll down, the animation at max extent persists and overlaps. I'm assuming this is a bug and not by design. 

Here's the simple code to reproduce. 

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<MessageItem>.generate(
      33,
      (i) => MessageItem("Sender $i", "Message body $i"),
    ),
  ));
}

class MyApp extends StatelessWidget {
  final List<MessageItem> items;

  MyApp({Key key, @required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final title = 'Mixed List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Column(
          children: [
            Expanded(
              child: Container(),
            ),
            Expanded(
              child: ListView.builder(
                itemCount: items.length,
                itemBuilder: (context, index) {
                  final item = items[index];

                  return ListTile(
                    title: item.buildTitle(context),
                    subtitle: item.buildSubtitle(context),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// A ListItem that contains data to display a message.
class MessageItem {
  final String sender;
  final String body;

  MessageItem(this.sender, this.body);

  Widget buildTitle(BuildContext context) => Text(sender);

  Widget buildSubtitle(BuildContext context) => Text(body);
}
```
![bug](https://user-images.githubusercontent.com/20642661/94435310-e132fc00-0192-11eb-93ed-9e3c4cad9f2f.gif)

**Comment by TahaTesser** [comment] 2020-09-28 14:47
Hi @alirezava 
Can you please provide your `flutter doctor -v` 
Thank you

**Comment by alirezava** [comment] 2020-09-28 14:59
[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\alire\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

Thanks in advance.

**Comment by Abhishek01039** [comment] 2020-09-28 18:13
Hi @alirezava 
this is because of `Expanded` widget.
```
 Expanded(
              child: Container(),
            ),
            Expanded(
              child: ListView.builder(
                itemCount: items.length,
                itemBuilder: (context, index) {
                  final item = items[index];

                  return ListTile(
                    title: item.buildTitle(context),
                    subtitle: item.buildSubtitle(context),
                  );
                },
              ),
```
By default `Expanded` has 1 flex so technically it divides your screen into two parts in your case because there is only 2 flex in which 1 for container and 1 for the listview.

you can change it by provides the flex to listview builder if you want the more size than a container.

Thanks.

**Comment by alirezava** [comment] 2020-09-28 19:29
> Hi @alirezava
> this is because of `Expanded` widget.
> 
> ```
>  Expanded(
>               child: Container(),
>             ),
>             Expanded(
>               child: ListView.builder(
>                 itemCount: items.length,
>                 itemBuilder: (context, index) {
>                   final item = items[index];
> 
>                   return ListTile(
>                     title: item.buildTitle(context),
>                     subtitle: item.buildSubtitle(context),
>                   );
>                 },
>               ),
> ```
> 
> By default `Expanded` has 1 flex so technically it divides your screen into two parts in your case because there is only 2 flex in which 1 for container and 1 for the listview.
> 
> you can change it by provides the flex to listview builder if you want the more size than a container.
> you can refer this for more information https://api.flutter.dev/flutter/widgets/Expanded-class.html
> 
> Thanks.

I appreciate your response. The desired result is a column with a fixed upper section and a listview at the bottom. Which is working as expected. However the issue as the gif highlights, is the animation that trails in the upper widget. 

The issue is the overlapping shouldn't happen. Not that the listview is taking half the screen. That part is intended. 

:)

**Comment by xu-baolin** [comment] 2020-09-29 03:28
@alirezava Hi, this issue was fixed at #64149, please track the latest version, thanks.

**Comment by TahaTesser** [comment] 2020-09-29 09:47
Hi @alirezava 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/94542769-d34eab00-0266-11eb-9156-a8fccce70402.gif)


<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp(
    items: List<MessageItem>.generate(
      33,
      (i) => MessageItem("Sender $i", "Message body $i"),
    ),
  ));
}

class MyApp extends StatelessWidget {
  final List<MessageItem> items;

  MyApp({Key key, @required this.items}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final title = 'Mixed List';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Column(
          children: [
            Expanded(
              child: Container(),
            ),
            Expanded(
              child: ListView.builder(
                itemCount: items.length,
                itemBuilder: (context, index) {
                  final item = items[index];

                  return ListTile(
                    title: item.buildTitle(context),
                    subtitle: item.buildSubtitle(context),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// A ListItem that contains data to display a message.
class MessageItem {
  final String sender;
  final String body;

  MessageItem(this.sender, this.body);

  Widget buildTitle(BuildContext context) => Text(sender);

  Widget buildSubtitle(BuildContext context) => Text(body);
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.405, on Mac OS X 10.15.7 19H2 x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.405 at /Users/tahatesser/Code/flutter_master
    • Framework revision 9d7bdb5903 (4 hours ago), 2020-09-28 22:46:21 -0700
    • Engine revision 438685dad0
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 x86_64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details> 

I cannot reproduce this issue on the latest `dev` channel.
Can you please upgrade to the latest  `dev` and try again
`flutter channel dev`
`flutter upgrade --force`
`flutter doctor -v`

Thank you @xu-baolin

**Comment by pedromassangocode** [comment] 2020-10-21 13:28
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-21 13:28 UTC
