### ISSUE TITLE
[webview_flutter] [flutter 3.22.1] iOS textfield cannot call up keyboard after exiting webview_flutter page in flutter 3.22.1, no problem in 3.19.6 

### ISSUE THREAD

**Issue by ebwood** [flutter/flutter#149338] opened 2024-05-30 18:35 UTC
### Steps to reproduce

1. HomePage with a TextField to call up keyboard , and a button to navigate to webview page
2. navigate to webview page and exit the page back to HomePage
3. click the TextField, the keyboard cannot call up, double click it can only see the paste options menu

Flutter 3.22.1 has the problem, but 3.19.6 has no problem. webview_flutter and flutter_inappwebview have the same problem.

### Expected results

TextField can call up keyboard after exiting webview page

### Actual results

Keyboard cannot call up after exiting webview page

### Code sample

<details open><summary>Code sample</summary>

[same project code to reproduce the problem](https://github.com/ebwood/webview_keyboard)

```dart
import 'package:flutter/material.dart';

import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: HomePage());
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          TextButton(
              onPressed: () {
                Navigator.push(context,
                    MaterialPageRoute(builder: (_) => const WebViewExample()));
              },
              child: const Text('webview')),
          const TextField()
        ],
      ),
    );
  }
}

class WebViewExample extends StatefulWidget {
  const WebViewExample({super.key});

  @override
  State<WebViewExample> createState() => _WebViewExampleState();
}

class _WebViewExampleState extends State<WebViewExample> {
  late final WebViewController controller;

  @override
  void initState() {
    super.initState();

    // #docregion webview_controller
    controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(const Color(0x00000000))
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            // Update loading bar.
          },
          onPageStarted: (String url) {},
          onPageFinished: (String url) {},
          onHttpError: (HttpResponseError error) {},
          onWebResourceError: (WebResourceError error) {},
          onNavigationRequest: (NavigationRequest request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
        ),
      )
      ..loadRequest(Uri.parse('https://flutter.dev'));
    // #enddocregion webview_controller
  }

  // #docregion webview_widget
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter Simple Example')),
      body: WebViewWidget(controller: controller),
    );
  }
  // #enddocregion webview_widget
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/60820399/9b071c8c-cf0d-4ca1-9bb2-d17374c24915

</details>

### Logs

<details open><summary>Logs</summary>

[webview_keyboard.txt](https://github.com/flutter/flutter/files/15504321/webview_keyboard.txt)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale en-CN)
    • Flutter version 3.22.1 on channel stable at /Users/faken/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (8 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/faken/Library/Android/sdk
    • Platform 0android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/faken/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • wombat (mobile)                 • 00008101-00096D923622001E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 125.0.6422.113

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by KropVOo** [comment] 2024-05-30 23:15
I would like to add a comment, I have the same problem with the fact that if the keyboard was hidden and focus was removed, it is not possible to put it back even through focusNode.requestFocus(), and the problem is not related to the webview

**Comment by ebwood** [comment] 2024-05-31 03:26
> I would like to add a comment, I have the same problem with the fact that if the keyboard was hidden and focus was removed, it is not possible to put it back even through focusNode.requestFocus(), and the problem is not related to the webview

Could you provide a simple example to reproduce your problem?

**Comment by darshankawar** [comment] 2024-05-31 06:54
@ebwood 
I tried the details as you provided using latest stable version but I was unable to replicate the reported behavior. 


https://github.com/flutter/flutter/assets/67046386/c8211cb1-29b6-4ac3-b339-8ed798bf9aa1

Are you swiping back to previous screen or tapping on back arrow ?

Can you also try the same on iOS device and see if you still get same behavior or not ? If it persists, please switch to latest master version and re-run your scenario to check if in master too it replicates or not.  See a related [issue](https://github.com/flutter/flutter/issues/148867) which works in master.

**Comment by darshankawar** [comment] 2024-05-31 06:55
> I would like to add a comment, I have the same problem with the fact that if the keyboard was hidden and focus was removed, it is not possible to put it back even through focusNode.requestFocus(), and the problem is not related to the webview

@BeesUser Please file a new issue using template and fill out requested details so that we can address it properly.

**Comment by wahkim** [comment] 2024-05-31 07:50
@

> @ebwood我尝试了您使用最新稳定版本提供的详细信息，但我无法复制报告的行为。
> 
>  149338.mov 
> 
> 您是向后滑动到上一个屏幕还是点击后退箭头？
> 
> 你也可以在iOS设备上尝试同样的尝试，看看你是否仍然有相同的行为吗？如果它仍然存在，请切换到最新的主版本并重新运行您的场景，以检查它是否也在主版本中复制。请参阅在master中有效的相关[问题](https://github.com/flutter/flutter/issues/148867)。



> > I would like to add a comment, I have the same problem with the fact that if the keyboard was hidden and focus was removed, it is not possible to put it back even through focusNode.requestFocus(), and the problem is not related to the webview
> 
> @BeesUser Could you provide a simple example to reproduce your problem?

After jumping to the next page in version 3.22.1, gesture side slide back, then click TextField will appear

https://github.com/flutter/flutter/assets/33590201/df66760c-b1a9-4cdc-b55f-925a06eddd4e

**Comment by ebwood** [comment] 2024-05-31 08:02
@darshankawar @wahkim

So this is nothing to to with webview. It's the swipe back gesture error in iOS with flutter 3.22.1.
The related issue #149393

**Comment by wahkim** [comment] 2024-05-31 08:05
> @darshankawar @wahkim
> 
> 因此，这与网络视图无关。这是iOS中使用flutter 3.22.1的向后滑动手势错误。相关问题#149393

Have you solved it now? Or wait for the sdk update?

**Comment by ebwood** [comment] 2024-05-31 08:08
> > @darshankawar @wahkim
> > 因此，这与网络视图无关。这是iOS中使用flutter 3.22.1的向后滑动手势错误。相关问题#149393
> 
> Have you solved it now? Or wait for the sdk update?

Not yet. I can only confirm the flutter 3.19.6 has no this problem. If sdk is not updated recently, maybe I only downgrade flutter version back to 3.19.6.

**Comment by wahkim** [comment] 2024-05-31 08:10
> > > @darshankawar @wahkim因此，与网络视图无关。这是iOS用中flutter 3.22.1的向后滑动手势错误。相关问题#149393
> > 
> > 
> > 你现在解决了吗？或者等待sdk更新？
> 
> 还没有。我只能确认flutter 3.19.6没有这个问题。如果sdk最近没有更新，也许我只能将flutter版本降级到3.19.6。

I was just upgraded from 3.19.6, 3.19.6 version has a background return card screen problem has not been solved, and there is no recurrence plan. It's hard.

**Comment by darshankawar** [comment] 2024-05-31 11:05
> So this is nothing to to with webview. It's the swipe back gesture error in iOS with flutter 3.22.1.
> The related issue #149393

@ebwood If you look at the linked issue and [this](https://github.com/flutter/flutter/issues/149393#issuecomment-2141648836) comment, it is already fixed in master, so you can switch to latest master and re-run your scenario to confirm it works properly.

Closing, as this is a duplicate issue and the original is already fixed in master.

**Closed by darshankawar** 2024-05-31 11:05 UTC
Labels: in triage
