### ISSUE TITLE
error when i hotreload

### ISSUE THREAD

**Issue by superpepe2003** [flutter/flutter#80615] opened 2021-04-17 00:48 UTC
## Command
```
flutter run --machine --target lib/main.dart -d emulator-5554 --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-allow-expose-url --devtools-server-address http://127.0.0.1:9100/
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ClientException
```
#0      IOClient.send.<anonymous closure> (package:http/src/io_client.dart:50:13)
#1      _invokeErrorHandler (dart:async/async_error.dart:45:24)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:272:9)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _HttpClientResponse.listen.<anonymous closure> (dart:_http/http_impl.dart:441:16)
#5      _rootRunBinary (dart:async/zone.dart:1378:47)
#6      _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#7      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#8      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#9      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#10     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#11     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#12     _addErrorWithReplacement (dart:async/stream_pipe.dart:176:8)
#13     _HandleErrorStream._handleError (dart:async/stream_pipe.dart:277:11)
#14     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#15     _rootRunBinary (dart:async/zone.dart:1378:47)
#16     _CustomZone.runBinary (dart:async/zone.dart:1272:19)
#17     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1178:7)
#18     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
#19     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:16)
#20     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#21     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:737:19)
#22     _StreamController._addError (dart:async/stream_controller.dart:615:7)
#23     _StreamController.addError (dart:async/stream_controller.dart:569:5)
#24     _HttpParser._reportBodyError (dart:_http/http_parser.dart:1163:22)
```
```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale es_AR.UTF-8)
    • Flutter version 2.0.4 at /home/pablo/development/flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/pablo/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 5.1.1 (API 22) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.114

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: fba99f6cf9a14512e461e3122c8ddfaa25394e89
### Plugins
flutter_plugin_android_lifecycle-1.0.11
image_picker-0.6.7+22
path_provider-1.6.27
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.4+3
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3

**Comment by iapicca** [comment] 2021-04-17 07:58
@superpepe2003 
	can you provide your  full `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by darshankawar** [comment] 2021-04-19 07:39
@superpepe2003 
Similar issue was fixed and merged into master, https://github.com/flutter/flutter/issues/73356.

Can you try to upgrade to latest master Channel master  and try again to see if you get same error or works now ?
If issue still persists, can you provide the crash log generated by the error, something like flutter_01.log ?
Thanks.

**Comment by darshankawar** [comment] 2021-04-19 07:39
Similar : https://github.com/flutter/flutter/issues/80365

**Comment by darshankawar** [comment] 2021-05-07 07:33
Closing this as duplicate of https://github.com/flutter/flutter/issues/80365

**Closed by darshankawar** 2021-05-07 07:33 UTC
Labels: in triage, waiting for customer response
