### ISSUE TITLE
[pigeon] copy documentation through to generated code.

### ISSUE THREAD

**Issue by bsutton** [flutter/flutter#67460] opened 2020-10-06 22:18 UTC
@gaaclarke 

Given that pigeon is generating apis for use across multiple platforms the ability to document those api's will be critical for a project's success.

Currently if you add documentation to the pigeon platform agnostic interface the pigeon generator ignores this documentation.

Pigeon should copy this documentation into the generated code for each platform.

**Comment by xster** [comment] 2020-10-12 17:55
this is a dupe of #53191

**Closed by xster** 2020-10-12 17:55 UTC
Labels: p: first party, passed first triage, pigeon, plugin, proposal
