### ISSUE TITLE
Error: The argument type 'HTMLStyleElement' can't be assigned to the parameter type 'JSAny'.

### ISSUE THREAD

**Issue by imeDevelopers** [flutter/flutter#140533] opened 2023-12-22 02:57 UTC
### Steps to reproduce

https://github.com/dart-lang/web/issues/128

### Expected results

https://github.com/dart-lang/web/issues/128

### Actual results

https://github.com/dart-lang/web/issues/128

### Code sample

https://github.com/dart-lang/web/issues/128

### Screenshots or Video

https://github.com/dart-lang/web/issues/128

### Logs

https://github.com/dart-lang/web/issues/128

### Flutter Doctor output

https://github.com/dart-lang/web/issues/128

**Comment by danagbemava-nc** [comment] 2023-12-22 09:44
Hi @imeDevelopers, please provide the output of `flutter doctor -v` along with steps to reproduce and a minimal complete reproducible code sample so that we can investigate this issue. 

Thank you

**Comment by imeDevelopers** [comment] 2023-12-22 18:19
@danagbemava-nc 
3.16.5 Flutter SDK
3.2.3 (Flutter) Dart SDK
Package: web
Version: 0.4.0

This was a flutter web application build, both debug and release.

**Comment by imeDevelopers** [comment] 2023-12-22 18:22
Windows 11

**Comment by dimiril** [comment] 2023-12-23 20:11
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../../../flutter/packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart:118:33: Error: The argument type 'HTMLStyleElement' can't be assigned to the parameter type 'JSAny'.
 - 'HTMLStyleElement' is from 'package:web/src/dom/html.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.4.0/lib/src/dom/html.dart').
 - 'JSAny' is from 'dart:_js_types'.
      web.document.head!.append(styleElement);
                                ^

**Comment by navaronbracke** [comment] 2023-12-23 21:05
Does this reproduce with `package:web` version 0.3.0? Per the changelog https://github.com/dart-lang/web/blob/main/CHANGELOG.md#040 this is intentional in version 0.4.0

**Comment by dimiril** [comment] 2023-12-24 12:20
> Does this reproduce with `package:web` version 0.3.0? Per the changelog https://github.com/dart-lang/web/blob/main/CHANGELOG.md#040 this is intentional in version 0.4.0

package:web version 0.4.0

**Comment by navaronbracke** [comment] 2023-12-24 16:15
To reiterate my previous answer: In package:web version `0.4.0` the `implements JSObject` was removed from DOM types.
This is mentioned in the changelog here: https://github.com/dart-lang/web/blob/main/CHANGELOG.md#040

```
Remove implements JSObject from all types. This is needed to move the JS types exposed in dart:js_interop to extension types. This subtyping will be added back in a future version when we move all package:web types to extension types.
```

So you'll have to go back to version 0.3.0 until the move to extension types is done.

**Comment by debojyoti452** [comment] 2023-12-24 16:20
can you please run 
`dart pub upgrade`

for me after running this command it started working again, I was also facing the same issue before. 

cc @dimiril

**Comment by dimiril** [comment] 2023-12-24 17:04
> @danagbemava-nc 3.16.5 Flutter SDK 3.2.3 (Flutter) Dart SDK Package: web Version: 0.4.0
> 
> This was a flutter web application build, both debug and release.

3.16.5 Flutter SDK
3.2.3 (Flutter) Dart SDK
Package: web
Version: 0.4.0

The problem appeared in the latest update flutter

**Comment by dimiril** [comment] 2023-12-24 17:09
> To reiterate my previous answer: In package:web version `0.4.0` the `implements JSObject` was removed from DOM types. This is mentioned in the changelog here: https://github.com/dart-lang/web/blob/main/CHANGELOG.md#040
> 
> ```
> Remove implements JSObject from all types. This is needed to move the JS types exposed in dart:js_interop to extension types. This subtyping will be added back in a future version when we move all package:web types to extension types.
> ```
> 
> So you'll have to go back to version 0.3.0 until the move to extension types is done.

flutter pub add web:^0.3.0
"web" is already in "dependencies". Will try to update the constraint.
Note: web is pinned to version 0.4.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_test from sdk depends on web 0.4.0 and syara depends on web 0.3.0, flutter_test from sdk is forbidden.
So, because syara depends on flutter_test from sdk, version solving failed.

**Comment by danagbemava-nc** [comment] 2023-12-27 06:58
Hi all, does this happen with the flutter counter app?

**Comment by Mahad61** [comment] 2023-12-31 23:21
Same Problem after upgrading to 3.16.5 .
Has anyone found a solution to this problem?

**Comment by dimiril** [comment] 2024-01-01 14:23
> Same Problem after upgrading to 3.16.5 . Has anyone found a solution to this problem?

So far there is no solution

**Comment by Mahad61** [comment] 2024-01-01 20:07
Additionally, I have tried overriding the dependency on web 0.3.0, but it hasn't helped.
Ultimately, I downgraded to 3.16.4, which resolved the issue.

**Comment by danagbemava-nc** [comment] 2024-01-02 06:03
Can anyone provide a complete minimal reproducible code sample so that we can investigate this issue? 

Thanks

**Comment by dimiril** [comment] 2024-01-02 20:04
> flutter pub add web:^0.3.0 "web" is already in "dependencies". Will try to update the constraint. Note: web is pinned to version 0.4.0 by flutter_test from the flutter SDK. See https://dart.dev/go/sdk-version-pinning for details.
> 
> Because every version of flutter_test from sdk depends on web 0.4.0 and syara depends on web 0.3.0, flutter_test from sdk is forbidden. So, because syara depends on flutter_test from sdk, version solving failed.

flutter pub add web:^0.3.0
"web" is already in "dependencies". Will try to update the constraint.
Note: web is pinned to version 0.4.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because every version of flutter_test from sdk depends on web 0.4.0 and syara depends on web 0.3.0, flutter_test from sdk is forbidden.
So, because syara depends on flutter_test from sdk, version solving failed.

**Comment by w0da** [comment] 2024-01-15 10:25
quick workaround in PlatformSelectableRegionContextMenu

  ```
import 'dart:js_util' as js_util;

static String _registerWebSelectionCallback(_WebSelectionCallBack callback) {
    _registerViewFactory(_viewType, (int viewId) {
      final web.HTMLElement htmlElement = web.document.createElement('div') as web.HTMLElement;
      htmlElement
        ..style.width = '100%'
        ..style.height = '100%'
        ..classList.add(_kClassName);

      // Create css style for _kClassName.
      final web.HTMLStyleElement styleElement = web.document.createElement('style') as web.HTMLStyleElement;

     // web.document.head!.append(styleElement);
      js_util.callMethod(web.document.head!, 'append', [styleElement]); // Use js_util here

      final web.CSSStyleSheet sheet = styleElement.sheet!;
      sheet.insertRule(_kClassRule, 0);
      sheet.insertRule(_kClassSelectionRule, 1);

      htmlElement.addEventListener('mousedown', (web.Event event) {
        final web.MouseEvent mouseEvent = event as web.MouseEvent;
        if (mouseEvent.button != _kRightClickButton) {
          return;
        }
        callback(htmlElement, mouseEvent);
      }.toJS);
      return htmlElement;
    }, isVisible: false);
    return _viewType;
  }
```

**Comment by mamaly12** [comment] 2024-01-28 17:56
I upgraded Flutter SDK to the latest version:

![image](https://github.com/flutter/flutter/assets/7683251/d65a00e1-0eb1-45d8-9485-7cb9d6dcd2ca)

When creating a new Flutter project, I select a web device and run main.dart to launch the app.
I get the following error:

```
Flutter/packages/flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart:118:33: Error: The argument type 'HTMLStyleElement' can't be assigned to the parameter type 'JSAny'.
 - 'HTMLStyleElement' is from 'package:web/src/dom/html.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.4.2/lib/src/dom/html.dart').
 - 'JSAny' is from 'dart:_js_types'.
      web.document.head!.append(styleElement);     
```

**Comment by navaronbracke** [comment] 2024-01-28 18:18
As the error points to the web implementation of the context menu at `flutter/lib/src/widgets/_platform_selectable_region_context_menu_web.dart`,
we'll probably have to cast the `HTMLStyleElement` to JSAny.

See my previous comment on why the `implements JSObject` was removed.

cc @justinmc

**Comment by Simouche** [comment] 2024-01-28 21:36
Simply i did:
```
dependency_overrides:
  web: ^0.3.0
```
and it worked :)

**Comment by justinmc** [comment] 2024-01-29 19:24
I'm out of my league with that web stuff... @kevmoo is the solution given by @navaronbracke above reasonable here?

Also CC @chunhtai who I believe wrote that file.

**Comment by kevmoo** [comment] 2024-01-29 19:31
@srujzs – thoughts here?

**Comment by srujzs** [comment] 2024-01-29 21:22
I don't think modifying that file/cherrypicking is the answer here as it may be one of several files that won't work. There's a version mismatch that needs to be addressed.

For clarity:

- Flutter pinned package:web `0.3.0`. This includes Flutter packages like `flutter_test`.
- Code that use package:web `0.3.0` might not work with `0.4.X` due to the change in the `implements` clause (hence the errors around type mismatch)

Both your package and *any dependencies you use* should support package:web `0.3.0` if you want to use Flutter `3.16.5` (or any other version that pins `0.3.0` for that matter). If not, you'll get a conflict. In a future Flutter release, this pin is removed, but for now, users have to support `0.3.0`: https://github.com/dart-lang/sdk/wiki/Flutter-Pinned-Packages

> Because every version of flutter_test from sdk depends on web 0.4.0 and syara depends on web 0.3.0, flutter_test from sdk is forbidden.

I don't understand how this error is possible, so I might be missing something. With Flutter `3.16.5`, `flutter_test` explicitly uses `web: 0.3.0`.

> When creating a new Flutter project, I select a web device and run main.dart to launch the app. I get the following error:
> `- 'HTMLStyleElement' is from 'package:web/src/dom/html.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dev/web-0.4.2/lib/src/dom/html.dart').`

This is interesting. `3.16.9` (the latest) also pins `0.3.0` so it's strange that it's trying to use `0.4.2`. https://github.com/dart-lang/web/issues/128#issuecomment-1913582637 indicates you have `^0.4.2` so I'd expect a pub version mismatch before you get to this error. Did you change the Flutter pin locally? Modifying the `pubspec.yaml` files in Flutter is how I can come across this error.

**Comment by ambr89** [comment] 2024-02-02 15:25
Any news? someone with flutter 3.16.9 can build right web ?

**Comment by srujzs** [comment] 2024-02-02 17:58
> Any news? someone with flutter 3.16.9 can build right web ?

If I understand your question correctly, you should be able to (like you could with `3.16.5`). You just have to make sure your package and any package you use support `0.3.0` of `package:web` as those version of Flutter pin the package version.

**Comment by jonkstro** [comment] 2024-02-12 22:44
> can you please run `dart pub upgrade` and `flutter update-packages --force-upgrade`
> 
> for me after running this command it started working again, I was also facing the same issue before.
> 
> cc @dimiril

I dit it and still is not working on 3.16.9

**Closed** 2024-02-23 09:08 UTC
Labels: waiting for customer response, in triage
