### ISSUE TITLE
Hit testing on default time app is returning wrong node.

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#59269] opened 2020-06-11 16:13 UTC
https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=53053

/cc @dnfield

**Comment by dnfield** [comment] 2020-06-23 21:39
Customer is indicating bug still exists. Moving milestone out while we continue to investigate root cause.

**Comment by dnfield** [comment] 2020-06-25 19:36
Requested a minimal reproduction from customer.

**Comment by chinmaygarde** [comment] 2020-06-29 17:46
Triage Update: There has been no progress on the reproducible test case.

**Comment by kf6gpe** [comment] 2020-06-30 17:29
I've pushed back on this issue to get a reproducible test case, as @dnfield and @iskakaushik indicated that they cannot reproduce this with the steps given due to target hardware/build instability. Leaving as a P1, as a11y is an important issue for the team right now, but there's nothing for the Flutter team to do with this at the moment.

**Comment by chinmaygarde** [comment] 2020-07-06 17:34
Triage: Nothing to do as there is no reproducible test case.

**Comment by kf6gpe** [comment] 2020-07-07 16:37
@iskakaushik, when you get a moment, could you try the use case detailed as comment 21 on https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=53053 if you have running hardware and comment on the upstream issue? Thanks!

**Comment by chinmaygarde** [comment] 2020-07-13 17:36
Triage: Still waiting for a reproducible test case. Reducing priority to match upstream prioritization.

**Comment by dnfield** [comment] 2020-07-14 22:43
Customer is reporting this is fixed upstream.

**Comment by dnfield** [comment] 2020-07-14 22:43
Suspicion is that the patch I landed that I thought fixed this did fix it, but that it had not rolled in yet last time there was testing.

**Closed by dnfield** 2020-07-14 22:43 UTC
Labels: P2, a: accessibility, customer: fuchsia, engine
