### ISSUE TITLE
google_maps_flutter the GoogleMap widget is not shown in specific devices

### ISSUE THREAD

**Issue by nashihu** [flutter/flutter#47195] opened 2019-12-17 06:23 UTC
hello,

i'm developing an app using Google Map in a page.

when i run the app in Sony & Redmi, the map is successfully shown like [like this](https://raw.githubusercontent.com/nashihu/mh_mcmc-double-elliptic-bivariate-gaussian/master/WhatsApp%20Image%202019-12-17%20at%2013.00.44.jpeg):

but when i run the app in Oppo and Vivo, the map just gone black blank [like this](https://raw.githubusercontent.com/nashihu/mh_mcmc-double-elliptic-bivariate-gaussian/master/Screenshot_2019-12-17-12-57-48-57%5B1%5D.png)

i tested it in just 4 devices above, 
but here some logs when the Google Map widget is shown using Oppo:
```
E/        ( 6096): [Mali]: gles_texture_bind_texture: Rendering feedback loop detected (texture=9), app behavior is wrong
D/libc-netbsd( 6096): [getaddrinfo]:  hostname=ems.air.id;  servname=(null);  app_pid=6096;  app_uid=10246;  ai_flags=1024;  ai_family=0; ai_socktype=1 from prox result 0
D/libc-netbsd( 6096): [getaddrinfo]:  hostname=ems.air.id;  servname=(null);  app_pid=6096;  app_uid=10246;  ai_flags=1024;  ai_family=0; ai_socktype=1 from prox result 0
I/flutter ( 6096): len data: 9
I/flutter ( 6096): Instance of 'Dil'
I/flutter ( 6096): ini dari Map ya : 9
I/BufferQueue( 6096): [unnamed-6096-3](this:0x739f3fc800,id:3,api:0,p:-1,c:-1) BufferQueue core=(6096:id.co.iconplus.ems)
I/BufferQueueConsumer( 6096): [unnamed-6096-3](this:0x739f3fc800,id:3,api:0,p:-1,c:6096) connect(C): consumer=(6096:id.co.iconplus.ems) controlledByApp=true
I/GLConsumer( 6096): [SurfaceTexture-0-6096-3] detachFromContext
I/BufferQueueProducer( 6096): [SurfaceTexture-0-6096-3](this:0x739f3fc800,id:3,api:1,p:379,c:6096) connect(P): api=1 producer=(379:???) producerControlledByApp=false
I/flutter ( 6096): len data: 9
I/flutter ( 6096): Instance of 'Dil'
I/Google Maps Android API( 6096): Google Play services package version: 19831021
D/SurfaceView( 6096): checkSurfaceViewlLogProperty get invalid command
I/System.out( 6096): Check isMmsSendPdu
I/System.out( 6096): PDU read len:466
I/System.out( 6096): MMS PDU Type:0:23
I/System.out( 6096): [OkHttp] sendRequest<<
I/System.out( 6096): Check isMmsSendPdu
I/System.out( 6096): PDU read len:357
I/System.out( 6096): MMS PDU Type:0:23
I/System.out( 6096): [OkHttp] sendRequest<<
I/Presentation( 6096): Presentation is being dismissed because the display metrics have changed since it was created.
V/ViewRootImpl( 6096): enableLogLight: enable = false
D/WindowClient( 6096): Add to mViews: DecorView@a08f9ef[], this = android.view.WindowManagerGlobal@9e2aba6
D/OpenGLRenderer( 6096): CanvasContext() 0x73859f8800
D/ViewRootImpl[MainActivity]( 6096): hardware acceleration is enabled, this = ViewRoot{cda5f94 id.co.iconplus.ems/id.co.iconplus.ems.MainActivity,ident = 5}
E/GoogleMapController( 6096): Cannot enable MyLocation layer as location permissions are not granted
I/System.out( 6096): Wrong owner. Perhaps a late disconnect
D/WindowClient( 6096): Remove from mViews: DecorView@a08f9ef[], this = android.view.WindowManagerGlobal@9e2aba6
I/System.out( 6096): Wrong owner. Perhaps a late disconnect
I/Choreographer( 6096): Skipped 5 frames!  The application may be doing too much work on its main thread.
D/OpenGLRenderer( 6096): ~CanvasContext() 0x73859f8800
D/OpenGLRenderer( 6096): ~CanvasContext() 0x73809f61c0
I/BufferQueue( 6096): [SurfaceTexture-0-6096-1](this:0x738097c000,id:1,api:1,p:-1,c:-1) ~BufferQueueCore
D/OpenGLRenderer( 6096): ~CanvasContext() 0x73a9ff5680
D/OpenGLRenderer( 6096): ~CanvasContext() 0x73a9bc2100
I/BufferQueue( 6096): [SurfaceTexture-0-6096-2](this:0x738f03e800,id:2,api:1,p:-1,c:-1) ~BufferQueueCore
I/flutter ( 6096): ini dari Map ya : 9
I/GLConsumer( 6096): [SurfaceTexture-0-6096-3] attachToContext

```
the first line in log above probably related to #28893 but i think it's not related to this issue

then here logs using Redmi, the successful one:
```
I/flutter (17528): len data: 9
I/flutter (17528): Instance of 'Dil'
I/flutter (17528): ini dari Map ya : 9
I/zzbz    (17528): Making Creator dynamically
W/co.iconplus.em(17528): Unsupported class loader
W/co.iconplus.em(17528): Skipping duplicate class check due to unsupported classloader
I/DynamiteModule(17528): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:222
I/DynamiteModule(17528): Selected remote version of com.google.android.gms.maps_dynamite, version >= 222
V/DynamiteModule(17528): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/DynamiteLoaderV2(17528): [71] Mapsdynamite
W/co.iconplus.em(17528): Unsupported class loader
I/Google Maps Android API(17528): Google Play services client version: 12451000
I/Google Maps Android API(17528): Google Play services package version: 19831029
W/co.iconplus.em(17528): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
D/NetworkSecurityConfig(17528): No Network Security Config specified, using platform default
I/DpmTcmClient(17528): RegisterTcmMonitor from: $Proxy0
W/co.iconplus.em(17528): Accessing hidden method Landroid/view/View;->getAccessibilityDelegate()Landroid/view/View$AccessibilityDelegate; (light greylist, linking)
E/GoogleMapController(17528): Cannot enable MyLocation layer as location permissions are not granted
W/DynamiteModule(17528): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(17528): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
I/DynamiteModule(17528): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
I/DynamiteLoaderV2(17528): [71] Googlecertificates
W/co.iconplus.em(17528): Unsupported class loader
```

is there any clue to from logs above to solve it?

thank you

**Comment by iapicca** [comment] 2019-12-18 09:41
Hi @nashihu 
can you please provide your updated  `flutter doctor -v`?
thank you

**Comment by nashihu** [comment] 2019-12-18 12:25
oh yes, i forget

here @iapicca 
```
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17134.765], locale en-ID)
    • Flutter version 1.9.1+hotfix.6 at C:\Users\username\flutter\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\username\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\as\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

```

**Comment by nashihu** [comment] 2020-01-08 22:09
umm, I expect after upgrading to v1.12.13+hotfix.5 the problem disappear, but still showing the same error on the specific device above

**Comment by TahaTesser** [comment] 2021-05-04 10:32
Hi @nashihu 
Do you have access to these devices ` Oppo and Vivo`, Please try following `google_maps_flutter: ^2.0.3`, since there are so many changes happen, the problem might be fixed

If the problem persists, Can you please provide your `flutter doctor -v, complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by nashihu** [comment] 2021-05-04 10:51
hello @TahaTesser , thanks for update, but i dont have access to the device anymore.

you can close this for now. if anyone reading this is still having the error please feel free to update here or create new one, thank you

**Comment by TahaTesser** [comment] 2021-05-06 10:35
Hi @nashihu 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-05-06 10:35 UTC
Labels: e: device-specific, p: first party, p: maps, platform-android, plugin
