### ISSUE TITLE
Unable to find bundled Java version

### ISSUE THREAD

**Issue by nguyendviet** [flutter/flutter#118502] opened 2023-01-14 17:55 UTC
## Steps to Reproduce

```
flutter doctor -v
[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
```

My specs:
```
Macbook Apple M1
MacOS 13.1 (22C65)
Android Studio Electric Eel | 2022.1.1
java 11.0.16.1 2022-08-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.16.1+1-LTS-1)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.16.1+1-LTS-1, mixed mode)
```

This is my `.zshrc`:
```
export PATH="$PATH:$HOME/flutter/bin"
export JAVA11_HOME=$(/usr/libexec/java_home -v11.0)
export JAVA_HOME=$JAVA11_HOME
```

I've tried:
- Creating a symlink.
- Copying folder as suggested here https://github.com/flutter/flutter/issues/76215#issuecomment-864407892

This is similar to these tickets but it's not resolved: 
- https://github.com/flutter/flutter/issues/81909
- https://github.com/flutter/flutter/issues/113161

**Comment by Lavish-Deba** [comment] 2023-01-15 00:42
hello there, im having same issue on my windows, were you able to resolve this issue ?

**Comment by nguyendviet** [comment] 2023-01-15 02:16
No, I haven't found a solution yet.

**Comment by mgenware** [comment] 2023-01-15 05:09
Same here on windows after upgrade Android Studio to Electric Eel.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22621.1105], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in
      your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.4.4)
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.74.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

**Comment by abood1996** [comment] 2023-01-15 11:21
+1 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19044.2486], locale en-US)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
**[!] Android Studio (version 2022.1)
    X Unable to find bundled Java version.**
[√] VS Code (version 1.74.3)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by 305371179** [comment] 2023-01-15 12:31
same question

**Comment by zeqinjie** [comment] 2023-01-15 13:18
+1

**Comment by zeqinjie** [comment] 2023-01-15 13:51
I solve this by download old version (4.2) [download url](https://developer.android.com/studio/archive)

**Comment by hootyjeremy** [comment] 2023-01-15 17:26
Uninstalling eel and then installing `Android Studio Dolphin | 2021.3.1 Canary 1` worked for me.

**Comment by roufy235** [comment] 2023-01-15 18:10
Go to finder and find Android studio:
1. right click and click show package contents
2. Create a new folder called jre
3. copy the contents of the jbr folder and paste them into jre folder

**Comment by prozenberg** [comment] 2023-01-15 18:21
@roufy235 I was going crazy with this on macOS, your solution fixed it. Thanks

**Comment by 1888ael** [comment] 2023-01-15 18:29
**WINDOWS SOLVED** 
GO TO 
C:\Program Files\Android\Android Studio 
then copy the content of jbr and paste the content into jre folder 
run doctor again and problem solved

**Comment by nguyendviet** [comment] 2023-01-15 19:17
Thanks a lot @roufy235 [That](https://github.com/flutter/flutter/issues/118502#issuecomment-1383215722) works

Just add a minor thing: both folders: **jbr** and **jre** are in `<PATH_TO_YOUR_ANDROID_STUDIO>/Android\ Studio/`

**Comment by Lavish-Deba** [comment] 2023-01-15 19:23
Thanks a lot @1888ael and @roufy235 
I have solved it

**Comment by halilbeytorun** [comment] 2023-01-15 19:44
@roufy235 thanks a lot it solved my problem in Ubuntu 22 also!
Can you explain why do we need to do that?

**Comment by junhan-z** [comment] 2023-01-15 22:51
The fix works, it's a weird fix though...

**Comment by Francesco-FL** [comment] 2023-01-16 01:38
I agree with @junhan-z, I understand the "ok doing this works", but why?
Don't we risk solving this problem and provoking others elsewhere? (after all, if the files were in that folder maybe there was a reason)

**Comment by robetus** [comment] 2023-01-16 02:40
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

Worked on latest macOS but I agree it is weird and I second the question, why?

**Comment by nguyendviet** [comment] 2023-01-16 03:34
Since there are people asking why. I think this is the cause: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart#L449-L451

The why 🤷

Perhaps a maintainer of the repo can answer that.

**Comment by Jago-ral** [comment] 2023-01-16 09:57
> **WINDOWS SOLVED** GO TO C:\Program Files\Android\Android Studio then copy the content of jbr and paste the content into jre folder run doctor again and problem solved

Tks

**Comment by DatabertDuck** [comment] 2023-01-16 11:22
Thanks @roufy235. 
But yeah, leaves an ominous feeling, not knowing if in the we will have to re-install everything completely again :D

**Comment by Sar10thak** [comment] 2023-01-16 11:59
> **WINDOWS SOLVED** GO TO C:\Program Files\Android\Android Studio then copy the content of jbr and paste the content into jre folder run doctor again and problem solved

Thank You So much worked for me.

**Comment by aliyazdi75** [comment] 2023-01-16 18:43
@nguyendviet I think you should keep this issue open, since the suggestion fix is not an actual fix. That's how an issue maintains. It needs to be triaged.

**Comment by ber2016** [comment] 2023-01-16 20:11
https://www.youtube.com/watch?v=CKpS9Jij6HQ
solution at least for me

**Comment by pnemonic78** [comment] 2023-01-17 07:42
workaround until official fix:

1. `cd /Applications/Android\ Studio.app/Contents`
2. `ln -s jbr jre`

**Comment by raveesh-me** [comment] 2023-01-17 08:03
Hello People!
It is the dev's responsibility to declare the right environment variables in their System.
I usually am explicit about these and these files are added to my .zshrc on mac. The same will work on any Linux machine that uses ZSH.

For windows, use environment variables.

```
The defaults for me are:
# Export Android Variables
export ANDROID_SDK_ROOT="/Users/raveesh/Library/Android/sdk"
export ANDROID_HOME="/Users/raveesh/Library/Android/sdk"
export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
```

In doing this, I just changed JAVA_HOME from:

`export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/Contents/Home"`

to 

`export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"`

**Comment by AntonyLeons** [comment] 2023-01-17 11:41
I think this issue should not be closed, an update changed the the java home/runtime without notification or a clear error message. users only avoided this error if they had another suitable java version already installed on their system. I had java 17 installed on my system giving me a irrelevant error: `java.lang.String java.io.File.path accessible: module java.base does not "opens java.io"`. its not a good experience.

**Comment by crow-dz** [comment] 2023-01-17 12:11
> 

thanks man

**Comment by kanyshaiosmonova** [comment] 2023-01-18 06:35
Thank you @roufy235 it works now. I am so thankful
![image](https://user-images.githubusercontent.com/85030155/213101222-d02b9961-bb1a-4770-9b4d-f70960b8825c.png)

**Comment by omidshojaee** [comment] 2023-01-18 12:40
This issue is related to this bug:

https://issuetracker.google.com/issues/247854802

**Comment by vladignatyev** [comment] 2023-01-18 22:06
I solved this issue on Ubuntu by creating a symlink: ```ln -s ~/android-studio/jbr ~/android-studio/jre```

The android-studio/jre now points to android-studio/jbr and Flutter can find the Java Runtime Environment.

Hope it helps. I agree that this is just a workaround.

**Comment by luismoron** [comment] 2023-01-18 23:23
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

This worked for me thanks Linux

**Comment by raynorcorgio** [comment] 2023-01-19 00:09
> **WINDOWS SOLVED** GO TO C:\Program Files\Android\Android Studio then copy the content of jbr and paste the content into jre folder run doctor again and problem solved

Thanks! This works for me too!

**Comment by 0xnlldev** [comment] 2023-01-19 22:30
> Bulucuya git ve **Android toplantınu** bulun :
> 
> 1. sağ tıklayın ve paket bilgilerini show'i tıklayın
> 2. **jre** adlı yeni bir klasör oluşturun****
> 3. **jbr** klasörlerinin gruplarını kopyalayın ve **jre** aygıtlarına ayırma
> 
> terminalinizi yeniden yükleyin ve yazın`flutter doctor`
thank you bro <3

**Comment by 0xnlldev** [comment] 2023-01-19 22:31
> Bulucuya git ve **Android toplantınu** bulun :
> 
> 1. sağ tıklayın ve paket bilgilerini show'i tıklayın
> 2. **jre** adlı yeni bir klasör oluşturun****
> 3. **jbr** klasörlerinin gruplarını kopyalayın ve **jre** aygıtlarına ayırma
> 
> terminalinizi yeniden yükleyin ve yazın`flutter doctor`

thank you bro <3

**Comment by MarkMuyobe** [comment] 2023-01-20 10:38
> 

Thanks A MIllion

**Comment by OverBrave** [comment] 2023-01-20 13:42
🚀

**Comment by omidshojaee** [comment] 2023-01-20 15:48
This is not an issue with Flutter, but Android Studio EE and Dolphin.

I had this and downgraded to Chipmunk for now.

**Comment by bcichowlas** [comment] 2023-01-20 18:38
Thanks. Just saw your comment. I think that is effectively what I ended up doing, though I ended with a Dophin version 2021.3.1 Patch 1. I had been on Electric Eel. I just went backwards until I found a version where the folder in document was named "jre" instead of "jbr". Though I understand why you say this isn't a Flutter issue, won't this be an issue for Flutter users that want to use the current Android Studio version? I also do other non-Flutter Android work and would want to use the current Android Studio version for that.

**Comment by omidshojaee** [comment] 2023-01-20 19:01
The problem is Google has serious issues in EE related to Java.

Just have a look at issuetracker.google.com.

On Windows, Android Studio itself won’t start after installation and it says cannot find Java because apparently VC++ Runtime is missing in the installation package.

So even if Flutter team solve this one most likely you won’t be able to run your app as it is reported by some users on Issue Tracker.

**Comment by CharlesLim0721** [comment] 2023-01-22 03:38
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

Thank you so much, I had been trying a lot solution is not working~ you help my day~

**Comment by amiralikh** [comment] 2023-01-22 08:44
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

This has solved my problem. Thank you.

**Comment by joelmoreiradev** [comment] 2023-01-23 00:23
> **WINDOWS SOLVED** GO TO C:\Program Files\Android\Android Studio then copy the content of jbr and paste the content into jre folder run doctor again and problem solved

I also had this problem. Copying the contents of jbr to jre worked, thanks you so much!

**Comment by iHTCboy** [comment] 2023-01-23 13:24
> workaround until official fix:
> 
> 1. `cd /Applications/Android\ Studio.app/Contents`
> 2. `ln -s jbr jre`

This has solved my problem. Thank you.

**Comment by maximegdn** [comment] 2023-01-23 14:33
thank you very much it worked for me

**Comment by khalidsaadat** [comment] 2023-01-24 19:51
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

Just a quick tip here. Make sure you create the `jre` folder inside `Contents` folder. Then copy `jbr`'s content into `jre`. This trick worked for me.

**Comment by sridip7** [comment] 2023-01-25 13:42
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

Thanks a lot

**Comment by Waruna-Kaushalya** [comment] 2023-01-26 04:18
@roufy235 thanks a lot and you saved us 💙💙💙

**Comment by LlMrc** [comment] 2023-01-26 15:51
thanks @1888ael

**Comment by corhythm** [comment] 2023-01-27 05:26
If you installed `Android Studio` using `Toolbox`, the folder is located `~/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio`

**Comment by rushidave01** [comment] 2023-01-27 14:16
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

Which IDE you are using?? In android studio it's not working

**Comment by rubenferreira97** [comment] 2023-01-27 23:30
> **WINDOWS SOLVED** GO TO C:\Program Files\Android\Android Studio then copy the content of jbr and paste the content into jre folder run doctor again and problem solved

I think a better workaround on **WINDOWS** would be to create a symbolic link with:
`mklink /D "C:\Program Files\Android\Android Studio\jre" "C:\Program Files\Android\Android Studio\jbr"`

This way we don't have duplicate files that also can get outdated when the folder jbr is updated/changed.

However, still waiting for a fix.

**Comment by Hamdan85** [comment] 2023-01-28 02:16
> I solved this issue on Ubuntu by creating a symlink: `ln -s ~/android-studio/jbr ~/android-studio/jre`
> 
> The android-studio/jre now points to android-studio/jbr and Flutter can find the Java Runtime Environment.
> 
> Hope it helps. I agree that this is just a workaround.

best solution.

**Comment by muhammadali224** [comment] 2023-01-28 10:03
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

thaaaaaaaanks a lot its work

**Comment by TheFinestArtist** [comment] 2023-01-31 13:20
I don't think the issue has been really resolved. We should keep this open until Flutter team actually fix this.

**Comment by alexandromillan** [comment] 2023-02-01 11:41
> Go to finder and find **Android studio**:
> 
>     1. right click and click show package contents
> 
>     2. Create a new folder called **jre**
> 
>     3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> 
> reload your terminal and type `flutter doctor`

it Works!!! thanks

**Comment by akaita** [comment] 2023-02-03 00:23
Just sharing this StackOverflow answer, as it's the most complete I've seen around: https://stackoverflow.com/questions/51281702/unable-to-find-bundled-java-version-on-flutter 

> For those having these issues with the latest Android Studio - Electric Eel version, and other canaries and preview releases, note that the bundled `jre `directory in the Android Studio installation folder is now renamed to `jbr`
> 
> To resolve this, just create a sym link `jre `-> `jbr `and Flutter won't complain.
> 
> On Linux
> 
> `cd ~/android-studio/ && ln -s jbr jre`
>
> Windows (check installation folder)
> 
>```
> cd C:\Program Files\Android\Android Studio
> mklink /D "jre" "jbr"
>```
>
> or
> 
>```
> New-Item -ItemType SymbolicLink -Path .\jre -Target .\jbr
>```
>
> Mac OS
> ```
> cd /Applications/Android\ Studio.app/Contents
> ln -s jbr jre
>```
>
> Note that if you are running a preview release, and depending on your OS, the default installation directory might be different, e.g. on Linux it would be
> ```
> ~/android-studio-preview/
>```
> In either case, you can check the installation directory by running
> ```
> flutter doctor -v
>```
> Also, in case if you run with permissions issues, you can try running the command with sudo or admin privileges, depending on your OS.

**Comment by arnaudambro** [comment] 2023-02-03 10:08
I have this error... nobody else ?

![image](https://user-images.githubusercontent.com/31724752/216572596-9e8e82d7-8ac4-4d8e-9ef4-1c94915af489.png)

**Comment by sarahec** [comment] 2023-02-03 18:57
A note about `ln -s` failures on MacOS. Under Ventura, that triggers a permissions error as the terminal is trying to modify a signed application. If you click on the notification, it'll offer you the chance to allow app modifications from the terminal. `ln -s` will work after that.

Also, @arnaudambro, try installing a fresh copy, running it once (to trigger the integrity check), *then* make the modifications. That should resolve the issue.

**Comment by Walnutty** [comment] 2023-02-03 22:26
> I have this error... nobody else ?
> 
> ![image](https://user-images.githubusercontent.com/31724752/216572596-9e8e82d7-8ac4-4d8e-9ef4-1c94915af489.png)

Mods as suggested above should be completed AFTER opening the Android Studio app at least once.

**Comment by ankurT96** [comment] 2023-02-04 11:46
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

Thanks it works for me

**Comment by FDiskas** [comment] 2023-02-05 14:35
For users who are using the `JetBrains toolbox` app instead - the path to Android studio is different

https://user-images.githubusercontent.com/468006/216825650-c4c69e1a-2cca-47fd-8273-eff39f846705.mov

**Comment by ayeshaghazi** [comment] 2023-02-05 22:43
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

Thank you so much!

**Comment by muhd7rosli** [comment] 2023-02-07 04:01
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

Thank you so much. Works for me.

**Comment by mahdiflutter** [comment] 2023-02-07 17:57
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

thank you . it is working for me

**Comment by mahdiflutter** [comment] 2023-02-08 13:32
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

thank you . solved my problem

**Comment by Muhammad-Shah** [comment] 2023-02-08 19:56
Thank You

**Comment by kaseebhotla85** [comment] 2023-02-10 01:55
> > Go to finder and find **Android studio**:
> > 
> > 1. right click and click show package contents
> > 2. Create a new folder called **jre**
> > 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> > 
> > reload your terminal and type `flutter doctor`
> 
> Worked on latest macOS but I agree it is weird and I second the question, why?

This worked on Macbook ARM / M1 as well.

**Comment by c-majer** [comment] 2023-02-12 19:56
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

This worked for me, thanks.

Also, I know I'm not adding much to the discussion but I had a doubt about "where to create the folder" while following the steps). So:

- The new jre folder must be created inside the Contents folder (hence having the jbr and the jre in the same directory).
- And the newly created jre folder must contain the folder Contents exactly as the jbr. 

[Basically you just need to copy-past the jbr folder in the same place and rename it as jre]

**Comment by AxisZql** [comment] 2023-02-13 03:55
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

awesome，thanks you！！！

**Comment by giaur500** [comment] 2023-02-13 09:33
That's still not explained - is this because Android Studio does not use `jre` direcotry anymore to store bundled java? If so, shouldn't flutter also respect that change? I my case (latest flutter stable) it still looks for java in `jre` folder, but it does not exist. BTW, that's not only flutter doctor issue, without proper java version you are not able to build any Android app.

**Comment by omidshojaee** [comment] 2023-02-13 09:52
That's correct. Someone in Flutter team messed up and as soon as users found some workarounds, they closed this.

**Comment by muhlba91** [comment] 2023-02-13 10:34
i agree - this issue should not be closed until flutter is updated to reflect this change. this will inherently lead to further issues and must be addressed by correctly.

@nguyendviet you closed this issue. what are your thoughts about reopening it until the flutter team fixes it without the need for any workaround?

**Comment by sky96111** [comment] 2023-02-13 13:40
@muhlba91 Actually the issue had been fixed in master but not in stable channel. https://github.com/flutter/flutter/pull/119244

**Comment by omidshojaee** [comment] 2023-02-13 13:45
This is a critical bug affecting millions not a fancy feature.  We are not supposed to wait until next quarter to see the fix in stable or otherwise deal with other broken things in master only because someone messed up.

**Comment by christopherfujino** [comment] 2023-02-13 17:50
> This was closed because: There are 5K+ issues in the repo. Another stale issue won't help.
> 
> This is reopened because:
> 
> * People still have this exact issue.
> * This merged PR was created to fix the issue [Fix unable to find bundled Java version #119244](https://github.com/flutter/flutter/pull/119244). However, it seems to have been reverted. I didn't have enough time to dig deep into it. cc: @christopherfujino If you have the time, please confirm this. Thank you.

I re-landed this in https://github.com/flutter/flutter/pull/120107. I think the people claiming they still have this are on stable (the fix has not yet reached stable). If someone is still experiencing this at the latest master feel free to comment here (with your full `flutter doctor -v` contents).

**Comment by gus-skywalker** [comment] 2023-02-13 18:16
I think the best way would be to link the "jbr" (phantom) to the a new missed yet required directory:

cmd_Line> ln -s jbr jre

**Comment by giaur500** [comment] 2023-02-13 18:19
You can also install java 11 on your system and don't use bundled one

**Comment by giaur500** [comment] 2023-02-13 18:40
> I think the best way would be to link the "jbr" (phantom) to the a new missed yet required directory:
> 
> cmd_Line> ln -s jbr jre

Not really. Android Studio updater will probably throw error message saying installation has been modified and unexpected directory found and it will be deleted.

**Comment by aniket-kale** [comment] 2023-02-14 07:05
Thanks @roufy235. [This](https://github.com/flutter/flutter/issues/118502#issuecomment-1383215722) works for me.

**Comment by mik3mast3rs** [comment] 2023-02-15 10:54
> Since there are people asking why. I think this is the cause: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_studio.dart#L449-L451 [Credit](https://github.com/flutter/flutter/issues/76215#issuecomment-864407892)
> 
> The why 🤷
> 
> Perhaps a maintainer of the repo can answer that.

This is actually the solution, not the issue. But it's only on the master branch of the Flutter repo, not the stable one that usually corresponds to the official SDK release.

As a wrap up, after 1-2 hours spent on this issue I can say this:

- Android Studio Electric Eel changed the folder where it holds the build in Java from jre to jbr
- The latest stable version of Flutter SDK (3.7.3) still looks for java.exe in the jre folder
- That's why copying contents from jbr folder into jre works
- The most elegat solution is to clone the Flutter repo after the branch master and then everything will work
- You also need to modify the Path in case you use the build in Android Studio Java on other applications

**Comment by giaur500** [comment] 2023-02-15 11:24
> The most elegat solution is to clone the Flutter repo after the branch master and then everything will work

Unless you don't want to use unstable Flutter version from master for your production apps.

**Comment by staciax** [comment] 2023-02-15 15:18
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

Thanks <3

**Comment by Wendell00** [comment] 2023-02-15 20:48
Thanks <3

**Comment by stevekohls** [comment] 2023-02-15 22:55
> A note about `ln -s` failures on MacOS. Under Ventura, that triggers a permissions error as the terminal is trying to modify a signed application. If you click on the notification, it'll offer you the chance to allow app modifications from the terminal. `ln -s` will work after that.
> 
> Also, @arnaudambro, try installing a fresh copy, running it once (to trigger the integrity check), _then_ make the modifications. That should resolve the issue.

Thank you @sarahec ! Just upgraded to Ventura before installing Flutter, Android Studio, and friends.

**Comment by hassnainabass** [comment] 2023-02-16 12:17
> **WINDOWS SOLVED** GO TO C:\Program Files\Android\Android Studio then copy the content of jbr and paste the content into jre folder run doctor again and problem solved

Thanks. This worked

**Comment by bunnyhu** [comment] 2023-02-16 20:15
mklink /J "f:\Program Files\Android\Android Studio\jre" "f:\Program Files\Android\Android Studio\jbr"

Of course use your path to Android studio.

**Comment by hugo-hdsolucoes** [comment] 2023-02-17 16:08
If you use Microsoft OpenJDK and selected it in the beginning of the installation, you should run this in elevated PowerShell inside Android Studio folder

```
New-Item -ItemType SymbolicLink -Path ".\jre" -Target "C:\Program Files\Microsoft\jdk-17.0.6.10-hotspot"
```

**Comment by samuelHenriquez92** [comment] 2023-02-21 01:18
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

Just ensure that the new `jre` folder will be at the same level as `jbr`

**Comment by cnksoft** [comment] 2023-02-21 14:23
Excellent solution @roufy235, works perfect.
Thanks a lot.

**Comment by this-is-allan** [comment] 2023-02-21 18:15
Excellent solution @roufy235, thanks.

**Comment by eluck** [comment] 2023-02-22 10:47
Worked for me as well! @roufy235, thanks.

**Comment by infinitepower18** [comment] 2023-02-23 13:04
Several updates were released for flutter and this problem is still a thing? Why? When will it be updated to reflect the changes made to Android Studio?

Also, I did the workaround but find whenever Android Studio updates it removes the jre folder.

**Comment by Dhanabhon** [comment] 2023-02-24 03:08
> Go to finder and find **Android studio**:
> 
> 1. right click and click show package contents
> 2. Create a new folder called **jre**
> 3. copy the contents of the **jbr** folder and paste them into **jre** folder
> 
> reload your terminal and type `flutter doctor`

It works in my case I rename the folder from jbr to jre.

**Comment by HsynBrnQuenjou** [comment] 2023-02-25 10:41
baranhuseyinkencu@BARAN-MacBook-Air ~ % flutter doctor    
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
baranhuseyinkencu@BARAN-MacBook-Air ~ % flutter doctor -v                                       
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale tr-TR)
    • Flutter version 3.7.5 on channel stable at /Users/baranhuseyinkencu/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (2 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/baranhuseyinkencu/Library/Android/sdk
    • Platform android-33-ext4, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!



baranhuseyinkencu@BARAN-MacBook-Air ~ % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found


why do i have "Intellij idea" inside the list.

**Comment by timsneath** [comment] 2023-02-25 20:55
@mariamhas, given the number of thumbs up for this issue, I wonder if it's something we need to patch in the next stable hot fix?

**Comment by sandwichstealer** [comment] 2023-02-25 21:08
Where is the jbr folder located?

**Comment by TonyHoyle** [comment] 2023-02-25 21:37
The delay fixing this means you've now got thousands of people with two copies of java, which may or may not stay in sync.. then you've got those that install a completely different java and override the path to work around the issue..

So a future installer is going to have to try to undo all that without breaking stuff.

**Comment by sandwichstealer** [comment] 2023-02-25 21:58
> workaround until official fix:
> 
> 1. `cd /Applications/Android\ Studio.app/Contents`
> 2. `ln -s jbr jre`

Where is the 'Applications' folder located on a Window machine?

**Comment by giaur500** [comment] 2023-02-26 07:34
> > workaround until official fix:
> > 
> > 1. `cd /Applications/Android\ Studio.app/Contents`
> > 2. `ln -s jbr jre`
> 
> Where is the 'Applications' folder located on a Windows machine?

On a Windows machinie look in your Android Studio installation directory

**Comment by diwacreation3** [comment] 2023-02-26 14:17
> **WINDOWS SOLVED** GO TO C:\Program Files\Android\Android Studio then copy the content of jbr and paste the content into jre folder run doctor again and problem solved

wow It works finally 🙂❤

**Comment by darshankawar** [comment] 2023-02-27 06:25
> @mariamhas @christopherfujino @itsjustkevin, given the number of thumbs up for this issue, I wonder if it's something we need to patch in the next stable hot fix? As more folk upgrade to Electric Eel, it's going to become considerably more prominent in the next couple of months until the next stable release.

There's already a hotfix request for this issue: https://github.com/flutter/flutter/issues/121505 that everyone in this thread can follow-up on for further updates. 

I'll keep this issue open for reference and tracking apart from the cp issue linked in this comment.

**Comment by andynvt** [comment] 2023-03-01 04:42
This will link `jbr` folder to `jre`

```
cd /Applications/Android Studio.app/Contents
ln -s jbr jre
```

**Comment by giaur500** [comment] 2023-03-01 07:55
Again and again. This is not actually solution, it's workaround only. Next Android Studio update will remove your symlink/folder. So, it can't be considered as solution.

**Comment by TonyHoyle** [comment] 2023-03-01 08:19
This non-fix (which people insist on reposting every day) now breaks the .1
update.. it won't install because the jre directory exists..  Google being
completely inconsistent about this.

So to upgrade
Delete jre directory
Create jre/bin/.marker (empty file which must exist)
Install update
Remove temporary jre directory
Copy jbr to jre again

This is very silly.  This should have been fixed in update 1 not made worse!

This is incredibly silly.

**Comment by timsneath** [comment] 2023-03-01 16:59
Thank you all for your comments, and please accept our apologies. This issue was caused by a change in Android Studio after Flutter 3.7 was released.

@giaur500 Correct, this is a workaround. That's why this issue is tagged with the **workaround available** tag. The details of the fix are here: https://github.com/flutter/flutter/issues/121505 and this will be merged in the next hotfix. 

@TonyHoyle I'm not sure why you think Google is "being completely inconsistent". As far as I can tell, we've made one comment on this bug, and it's to acknowledge it as a hotfix candidate. A quick reminder: let's be kind and courteous to each other in this professional space. 

Closing this issue and locking it since we have the information we need to resolve the bug and a workaround is clearly posted.

**Closed by timsneath** 2023-03-01 16:59 UTC
Labels: tool, t: flutter doctor, customer: crowd, workaround available
