### ISSUE TITLE
The password keyboard will flash in flutter 3.16.5  ios17.1.2

### ISSUE THREAD

**Issue by assemblyios** [flutter/flutter#140693] opened 2023-12-28 10:01 UTC
### Steps to reproduce

When you close TextField obscureText   The password keyboard will flash in flutter 3.16.5  ios17.1.2

### Expected results

not  falash

### Actual results

The password keyboard will flash

### Code sample

<details open><summary>Code sample</summary>

```dart
TextField(
          //文字默认小写
          textCapitalization: TextCapitalization.none,
          style: TextStyle(
            color: FColor.text33,
            fontSize: widget.fontSize ?? 18.fsp,
          ),
          //是否能够复制粘贴
          enableInteractiveSelection: true,
          focusNode: widget.focusNode,
          maxLength: 20,
          autofocus: false,
          controller: widget.controller,
          inputFormatters: [
            FilteringTextInputFormatter.deny(
                RegExp(r'[\u4e00-\u9fa5.·\u36c3\u4DAE]'))
          ],
          obscureText: false,
          textInputAction: TextInputAction.done,
          keyboardType: TextInputType.visiblePassword,
          decoration: InputDecoration(
            icon: widget.needIcon
                ? SvgPicture.asset(
                    ImageAssets.accountIcLockSvg,
                  )
                : null,
            focusedBorder: InputBorder.none,
            enabledBorder: InputBorder.none,
            isCollapsed: true,
            hintText: widget.hintText,
            hintStyle: TextStyle(
              color: FColor.textCC,
              fontSize: widget.fontSize ?? 18.fsp,
              fontWeight: FontWeightPlus.w400
            ),
            counterText: '',
          ),
        ),

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/12081932/1aec5b4a-d9ae-443d-afe8-da14ae758a16

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1.1 23B81 darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.0)
[✓] Connected device (6 available)
```

</details>

**Comment by danagbemava-nc** [comment] 2023-12-28 11:11
Closing this as a duplicate of https://github.com/flutter/flutter/issues/134723. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-12-28 11:11 UTC
Labels: in triage
