### ISSUE TITLE
[tool_crash] StateError: Bad state: No context with the running Dart application.

### ISSUE THREAD

**Issue by SweetSourPeter** [flutter/flutter#91193] opened 2021-10-03 15:00 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No context with the running Dart application.
```
#0      RemoteDebuggerExecutionContext.id (package:dwds/src/debugging/execution_context.dart:55:7)
<asynchronous suspension>
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:501:20)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:93:34)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:156:5)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:222:18)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.1237], locale en-US)
    • Flutter version 2.2.1 at C:\flutter
    • Framework revision 02c026b03c (4 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\p7319\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.60.2)
    • VS Code at C:\Users\p7319\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 94.0.992.31

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.7+14
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 5d36f2e7f5387b6c751449258ade8e4e6edf99be
### Plugins
cloud_firestore-2.5.2
cloud_firestore_web-2.4.2
emoji_picker_flutter-1.0.7
file_picker-4.0.2
firebase_auth-1.4.1
firebase_auth_web-1.3.1
firebase_core-1.6.0
firebase_core_web-1.1.0
firebase_messaging-10.0.7
firebase_messaging_web-2.0.5
firebase_storage-8.1.3
firebase_storage_web-1.1.2
flutter_email_sender-5.0.2
flutter_keyboard_visibility-5.0.3
flutter_keyboard_visibility_web-2.0.0
flutter_plugin_android_lifecycle-2.0.3
fluttertoast-8.0.8
google_sign_in-5.1.0
google_sign_in_web-0.10.0+2
image_cropper-1.4.1
image_gallery_saver-1.6.9
image_picker-0.7.5+4
image_picker_for_web-2.1.3
jitsi_meet-4.0.0
jitsi_meet_web_plugin-2.0.0
multi_image_picker-4.8.01
path_provider-2.0.3
path_provider_linux-2.0.2
path_provider_macos-2.0.2
path_provider_windows-2.0.3
permission_handler-8.1.6
share_plus-2.1.4
share_plus_macos-2.0.2
share_plus_web-2.0.4
shared_preferences-2.0.7
shared_preferences_linux-2.0.2
shared_preferences_macos-2.0.2
shared_preferences_web-2.0.2
shared_preferences_windows-2.0.2
sqflite-2.0.0+4
url_launcher-6.0.10
url_launcher_linux-2.0.2
url_launcher_macos-2.0.2
url_launcher_web-2.0.4
url_launcher_windows-2.0.2

**Comment by maheshmnj** [comment] 2021-10-04 10:00
Hi @SweetSourPeter, Thanks for filing the issue. Could you please try upgrading to the latest stable using 

```
flutter upgrade 
```
and see if that reproduces the issue for you.

Thank you.

**Comment by christopherfujino** [comment] 2021-10-06 00:32
closing as a duplicate of https://github.com/flutter/flutter/issues/60495

**Closed by christopherfujino** 2021-10-06 00:32 UTC
Labels: waiting for customer response, in triage
