### ISSUE TITLE
Support desktop in Webview

### ISSUE THREAD

**Issue by vargavince91** [flutter/flutter#46662] opened 2019-12-10 08:28 UTC
# Use case

I want to display a webview inside my Flutter desktop app.

# Question

Are there any workaround I could do for now? Am I doing it wrong and I shouldn't even be using the webview?

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following UnsupportedError was thrown building WebView(dirty, state: _WebViewState#a4635):
flutter: Unsupported operation: Trying to use the default webview implementation for TargetPlatform.macOS but
flutter: there isn't a default one
flutter:
flutter: The relevant error-causing widget was:
flutter:   WebView file:///Users/vince/dartsidedev/presentations/2019-12-11/presentation/lib/main.dart:82:14
flutter:
```

**Comment by stuartmorgan** [comment] 2019-12-10 09:10
Duplicate of #41725

> Are there any workaround I could do for now?

It depends on your use case. `url_launcher` might suffice for some cases in the meantime, for instance.

> Am I doing it wrong and I shouldn't even be using the webview?

I'm not sure what you're asking exactly. It's not currently supported for macOS, but it is something we intend to support.

**Closed by stuartmorgan** 2019-12-10 09:10 UTC

**Comment by vargavince91** [comment] 2019-12-10 09:24
Thank you for your help and the quick answer!

> I'm not sure what you're asking exactly.

I wanted to display a website within a desktop app. To do this on mobile, I would use the `WebView`. I wanted to know what we can do in desktop apps to display a website "inline".

**Comment by shrideh** [comment] 2020-03-31 17:43
url_launcher & WebView not work

flutter: Another exception was thrown: Unsupported operation: Trying to use the default webview implementation for TargetPlatform.fuchsia but there isn't a default one
