### ISSUE TITLE
Make Android 10 Activity Animation the default animation

### ISSUE THREAD

**Issue by shihaohong** [flutter/flutter#43277] opened 2019-10-22 17:11 UTC
After https://github.com/flutter/flutter/pull/41935 lands, we should default material page transitions to the newer animation.

**Comment by lazylazyllama** [comment] 2019-11-09 14:07
What about only making it the default on API 29 and above?

**Comment by shihaohong** [comment] 2019-11-11 06:57
We typically use the latest OEM behavior by default for Flutter https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#widget-libraries-follow-the-latest-oem-behavior

**Comment by lazylazyllama** [comment] 2019-11-11 09:29
Hmm I'm not sure if that's a good idea as most people don't have the latest OEM version which leads to an inconsistent user experience for them.

**Comment by AlexV525** [comment] 2021-08-20 01:48
Unfortunately we cannot land the change at the moment due to some performance regression with transitions.

**Comment by Hixie** [comment] 2022-01-09 07:31
What is the status here?

**Comment by AlexV525** [comment] 2022-01-09 08:00
> What is the status here?

@Hixie Thanks for the following up, a couple of reasons that this can't be pushed at present:
- #85737: The OpacityLayer needs to reduce/prevent saveLayer when children are able to do so. It mainly affects the memory footprint when drawing. Although the `DisplayList` improvement has been landed, I'm still not sure about the solid proof if it helps, will need to consult @flar.
- https://github.com/flutter/flutter/pull/88482#issue-974140300 from @HansMuller: Migration breaks an internal test but it's not resolved yet. This could be done once any googlers can take further investigations, or pass the test to me IMO.

**Comment by Hixie** [comment] 2022-01-09 08:07
If you need help with the Google-internal test please reach out to me on Discord on Monday. I'd be happy to help.

**Comment by AlexV525** [comment] 2022-01-09 08:08
> If you need help with the Google-internal test please reach out to me on Discord on Monday. I'd be happy to help.

I'll take a note of it, and try to land this again once tests can be resolved.

**Comment by flar** [comment] 2022-01-10 18:59
If you can describe the conditions under which you want the Opacity layer to reduce or prevent saveLayer operations, I can give a status on that work. One optimization that recently landed that might be related is https://github.com/flutter/engine/pull/29775 with examples of situations in which it improves operations demonstrated in the benchmarks in https://github.com/flutter/flutter/blob/master/dev/benchmarks/macrobenchmarks/lib/src/opacity_peephole.dart

**Closed** 2022-03-26 05:25 UTC
Labels: framework, f: material design, severe: performance, proposal, perf: memory, P4

**Comment by AlexV525** [comment] 2022-03-28 05:21
The new transition has been enabled as the default one on the master branch.
