### ISSUE TITLE
[web] VideoElement flickers on redraw in Safari

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#39980] opened 2019-09-06 15:46 UTC
![safary_flicker](https://user-images.githubusercontent.com/814785/64441279-da3fd400-d0cd-11e9-9445-2271b9a6f901.gif)

This does not happen in Chrome or Firefox. Setting `controls` to to `true` "fixes" it. Also removing the color of the container. This does not happen with an `ImageElement`.

```dart
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() {
  final String src1 =
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4';
  final String src2 =
      'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4';
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Container(
          color: Colors.white,
          child: Column(
            children: <Widget>[
              WebVideoElement(src: src1),
              WebVideoElement(src: src1),
              WebVideoElement(src: src2),
              WebVideoElement(src: src2),
            ],
          ),
        ),
      ),
    ),
  );
}

class WebVideoElement extends StatefulWidget {
  WebVideoElement({Key key, this.src}) : super(key: key);

  final String src;

  @override
  _WebVideoElementState createState() => _WebVideoElementState();
}

class _WebVideoElementState extends State<WebVideoElement> {
  @override
  void initState() {
    super.initState();
    ui.platformViewRegistry.registerViewFactory(
      widget.src,
      (int viewId) => VideoElement()
        ..src = widget.src
        ..width = 320
        ..height = 180
        ..controls = false
        ..style.border = 'none',
    );
  }

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: SizedBox(
        width: 320,
        height: 180,
        child: HtmlElementView(viewType: widget.src),
      ),
    );
  }
}
```
```
[✓] Flutter (Channel master, v1.9.8-pre.108, on Mac OS X 10.14.6 18G95, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)
```

**Comment by cbenhagen** [comment] 2019-09-09 14:47
@hterkelsen any ideas?

**Comment by yjbanov** [comment] 2019-09-11 14:51
I'm guessing the video tag is being reparented within the scene DOM tree and Safari doesn't like that.

**Comment by yjbanov** [comment] 2019-09-11 14:52
@hterkelsen since you self-assigned, could you please also pick a milestone for this issue?

**Comment by hterkelsen** [comment] 2019-09-30 20:41
Sorry, haven't had time to get to this this month: I have been working on landing web plugins into the first-party plugins repo. I will look into this in October.

**Comment by hterkelsen** [comment] 2019-10-30 20:41
Sorry, still need to investigate this. I am working on platform views in the near term, so I will make sure to prioritize this.

**Comment by cbenhagen** [comment] 2019-12-05 23:47
@hterkelsen do you think the CanvasKit backend might have the same issues once it supports [Platform Views](https://github.com/flutter/flutter/issues/43783)?

**Comment by yjbanov** [comment] 2020-01-06 19:10
@cbenhagen the CanvasKit backend does support platform view now. Can you please give it a shot?

**Comment by cbenhagen** [comment] 2020-01-06 19:36
Unfortunately the CanvasKit has the same issues.

**Comment by MateusAmin** [comment] 2020-02-10 01:35
Any workarounds?

I am embedding a Twitch stream with an iframe but it reloads whenever I affect the screen in any fashion. Like resizing or any hovering over buttons.

**Comment by zibizz1** [comment] 2020-03-06 22:57
Yes iFrame is reloaded when I move the cursor over some elements but if I resize the window and cause that some elements do not fit then it stops.
![1KHe8lY2yr](https://user-images.githubusercontent.com/9219799/76128907-fa613900-6005-11ea-8500-d33d570b3f37.gif)
![EfI0MoMYvi](https://user-images.githubusercontent.com/9219799/76128914-ff25ed00-6005-11ea-9909-385b44e0e841.gif)

**Comment by thachnb85** [comment] 2020-03-15 23:18
Got the same problem IFrameElement is flickering whenever I hover mouse pointer on any button, list, etc...

**Comment by muhleder** [comment] 2020-04-01 11:45
Partial fix for the initial reported issue over here https://github.com/flutter/flutter/issues/53253

Tested in Safari and it stops the bottom element from flickering, top element still flickers as the window edge hits the bottom element.

**Comment by Garciconx** [comment] 2020-04-23 05:29
I have the same issue here, any updates?

**Comment by jameswasher** [comment] 2020-06-26 12:25
I'm using the [video_player package](https://pub.dev/packages/video_player) and get flickering in Safari when I pause a video.  No flickering on iOS, Android and Chrome.

**Comment by maheshmnj** [comment] 2021-07-01 07:50
Hi @cbenhagen,
Thanks for filing the issue I am able to reproduce this issue on the latest stable and master channel of flutter using the latest plugin ```video_player: ^2.1.6```. The issue is reproducible only in Safari and works fine on Chrome. I had to use 
[universal_ui package](https://pub.dev/packages/universal_ui) instead of dart:ui because of this issue https://github.com/flutter/flutter/issues/41563.

<details>
<summary>code sample</summary>

```
import 'dart:html';
import 'package:universal_ui/universal_ui.dart';
import 'package:flutter/material.dart';

class VideoFlicker extends StatefulWidget {
  @override
  _VideoFlickerState createState() => _VideoFlickerState();
}

class _VideoFlickerState extends State<VideoFlicker> {
  final String src1 =
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4';
  final String src2 =
      'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          color: Colors.grey,
          child: Column(
            children: <Widget>[
              WebVideoElement(src: src1),
              WebVideoElement(src: src1),
              WebVideoElement(src: src2),
              WebVideoElement(src: src2),
            ],
          ),
        ),
      ),
    );
  }
}

class WebVideoElement extends StatefulWidget {
  final String src;

  WebVideoElement({Key key, this.src}) : super(key: key);

  @override
  _WebVideoElementState createState() => _WebVideoElementState();
}

class _WebVideoElementState extends State<WebVideoElement> {
  @override
  void initState() {
    super.initState();
    ui.platformViewRegistry.registerViewFactory(
      widget.src,
      (int viewId) => VideoElement()
        ..src = widget.src
        ..width = 320
        ..height = 180
        ..controls = false
        ..style.border = 'none',
    );
  }

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: SizedBox(
        width: 320,
        height: 180,
        child: HtmlElementView(viewType: widget.src),
      ),
    );
  }
}

```
</details>


<details>
<summary>output</summary>

### Chrome
https://user-images.githubusercontent.com/31410839/124085737-fc0e0600-da6d-11eb-9eba-7f84db7bf72c.mov

### Safari
https://user-images.githubusercontent.com/31410839/124085748-ff08f680-da6d-11eb-943a-5f8f4f557af7.mov

</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.2 at /Users/mahesh/Documents/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.608, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.3.0-17.0.pre.608 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18ccfe6386 (4 hours ago), 2021-07-01 05:26:03 +0200
    • Engine revision eab0cd490a
    • Dart version 2.14.0 (build 2.14.0-262.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>


Thank you for your contribution.

**Comment by maheshmnj** [comment] 2021-10-04 09:49
removed the video_player plugin specific labels

**Comment by aytunch** [comment] 2021-12-15 22:32
This issue effects CanvasKit we apps using VideoPlayer's
@maheshmnj why did we remove the video_player plugin? Is this bug related to something else?

**Comment by maheshmnj** [comment] 2021-12-16 05:12
> @maheshmnj why did we remove the video_player plugin? Is this bug related to something else?

Because this issue is related to the embedder's API and not with the video_player plugin. If you are seeing a similar issue with the Video_player plugin please file a separate issue for the same, I would love to take a look.

> Also does using this snippet shared by the author fixes the issue temporarily?

It doesn't as per my [response above](https://github.com/flutter/flutter/issues/39980#issuecomment-872011517)

**Comment by ditman** [comment] 2022-06-03 17:51
I tried to reproduce this issue, but couldn't. I think this got fixed by https://github.com/flutter/flutter/issues/80524.

The issue that I can reproduce now very easily in Canvaskit mode with the repro from this issue is:

<details>
<summary><tt>WebGL: INVALID_OPERATION delete: object does not belong to this context</tt></summary>

```
[Error] WebGL: INVALID_OPERATION: delete: object does not belong to this context
	deleteTexture
	oa (canvaskit.js:231:503)
	wasm-stub
	<?>.wasm-function[856]
	<?>.wasm-function[6476]
	<?>.wasm-function[1433]
	<?>.wasm-function[2875]
	<?>.wasm-function[8037]
	<?>.wasm-function[2357]
	wasm-stub
	(anonymous function)
	(anonymous function) (canvaskit.js:178)
	_callMethodUnchecked0 (dart_sdk.js:62324)
	createOrUpdateSurface (dart_sdk.js:151338:98)
	acquireFrame (dart_sdk.js:151304)
	submitFrame (dart_sdk.js:145202:85)
	draw (dart_sdk.js:150270)
	render (dart_sdk.js:172270)
	compositeFrame (view.dart.js:315)
	drawFrame (view.dart.js:753)
	drawFrame (title.dart.js:61112)
	(anonymous function) (view.dart.js:712)
	[_handlePersistentFrameCallback]
	(anonymous function) (binding.dart.js:782)
	handleDrawFrame (binding.dart.js:749)
	(anonymous function) (binding.dart.js:696)
	[_handleDrawFrame]
	invoke (dart_sdk.js:195230)
	invokeOnDrawFrame (dart_sdk.js:172004)
	(anonymous function) (dart_sdk.js:194953)
```

</details>

It complains about not being to do `deleteProgram`, `deleteSampler`, `deleteFramebuffer`, `deleteTexture`, `deleteBuffer`.

I'm going to deduplicate this one with https://github.com/flutter/flutter/issues/91881 so @hterkelsen can take a look, they seem somewhat related to what's being reported over there too!

**Closed by ditman** 2022-06-03 17:51 UTC
Labels: e: embedder, platform-web, has reproducible steps, browser: safari-macos, P4, found in release: 2.2, found in release: 2.3
