### ISSUE TITLE
Facing issue while calling api by using mobx

### ISSUE THREAD

**Issue by himanshuyadav146** [flutter/flutter#116053] opened 2022-11-26 15:50 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by iapicca** [comment] 2022-11-26 16:11
if the issue is with [mobx](https://pub.dev/packages/mobx) than should be probably addressed [here](https://github.com/mobxjs/mobx.dart/issues)

**Comment by huycozy** [comment] 2022-11-28 05:49
Hi @himanshuyadav146 
The goal of this GitHub repo is not to give assistance on personal code or the whole package/plugin project, but to improve Flutter reporting bugs or feature requests.

If you have an issue with mobx, please open the issue in the [mobx repository](https://github.com/mobxjs/mobx.dart/issues). Closing, as this isn't an issue with Flutter itself.

**Closed by huycozy** 2022-11-28 05:49 UTC
Labels: in triage
