### ISSUE TITLE
Error With Build APK 

### ISSUE THREAD

**Issue by HamzaAyada** [flutter/flutter#65252] opened 2020-09-04 16:31 UTC
Hi,
I try to build my Flutter application but avery time when i execute the commande ```flutter build apk``` i get this error 

```console
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...
Format incorrect du param�tre -



FAILURE: Build failed with an exception.



* What went wrong:

Execution failed for task ':app:lintVitalRelease'.

> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.

   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.

      > Execution failed for JetifyTransform: C:\Users\HAMZA TEK'NOLOGY IT\IdeaProjects\walk_win_tt\build\app\intermediates\flutter\debug\libs.jar.

         > Failed to transform 'C:\Users\HAMZA TEK'NOLOGY IT\IdeaProjects\walk_win_tt\build\app\intermediates\flutter\debug\libs.jar' using Jetifier. Reason: FileNotFoundException, message: C:\Users\HAMZA TEK'NOLOGY IT\IdeaProjects\walk_win_tt\build\app\intermediates\flutter\debug\libs.jar (Le chemin d�acc�s sp�cifi� est introuvable). (Run with --stacktrace for more details.)

           Please file a bug at http://issuetracker.google.com/issues/new?component=460323.



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 9s
Running Gradle task 'assembleRelease'...                           10,3s
Gradle task assembleRelease failed with exit code 1

``` 

- FLutter Doctor
```console
$ [√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [version 10.0.19041.450], locale fr-FR)
bash: syntax error near unexpected token `('
    • Dart version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\HAMZA TEK'NOLOGY IT\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\HAMZA TEK'NOLOGY IT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by Calamity210** [comment] 2020-09-04 17:30
Possible dupe of #58247

**Comment by hamdikahloun** [comment] 2020-09-04 20:06
@HamzaAyada can you check if this file exist after you running the build command 'C:\Users\HAMZA TEK'NOLOGY IT\IdeaProjects\walk_win_tt\build\app\intermediates\flutter\debug\libs.jar'

**Comment by HamzaAyada** [comment] 2020-09-04 20:29
@hamdikahloun yes the file existe

**Comment by hamdikahloun** [comment] 2020-09-04 20:35
Can you change your project folder to D: or C:\Users\ and try again , I think it's because the path have `'`  in TEK'NOLOGY .

**Comment by markusaksli-nc** [comment] 2020-09-07 05:45
Hi @HamzaAyada 
Are you using Android Gradle plugin 4.0.0?
Thank you

**Comment by HamzaAyada** [comment] 2020-09-07 06:05
@markusaksli-nc yes

**Comment by markusaksli-nc** [comment] 2020-09-07 06:08
In that case I'll close this as a duplicate of https://github.com/flutter/flutter/issues/58247.

Please follow up with your case there.

**Closed by markusaksli-nc** 2020-09-07 06:08 UTC
Labels: in triage
