### ISSUE TITLE
Flutter Web: image_picker plugin gets image from folder instead of webcam

### ISSUE THREAD

**Issue by CodingWithTashi** [flutter/flutter#86652] opened 2021-07-19 12:02 UTC
image_picker  seems to be working fine in mobile but in web even after passing source as camera. Image is picking from folder.   
I check this in stackoverflow [here ](https://stackoverflow.com/questions/67543270/flutter-web-image-picker-plugin-gets-image-from-folder-instead-of-webcam). seems no solution. Please let me know what is the issue.

```
final pickedFile = await _picker.pickImage(
        source: ImageSource.camera,
        imageQuality: 7,
      );
```   
Thanks

**Comment by TahaTesser** [comment] 2021-07-20 08:31
Hi @CodingWithTashi 
The camera from `image_picker` works fine on some mobile browsers,  on desktop, it is the browser limitation, please see https://pub.dev/packages/image_picker_for_web#input-file-capture
Closing, as duplicate of https://github.com/flutter/flutter/issues/85195
Thank you

**Closed by TahaTesser** 2021-07-20 08:31 UTC
Labels: in triage
