### ISSUE TITLE
Web & Android / IOS app using web platform view registry issues with update (analyzer issue?)

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#57370] opened 2020-05-16 09:01 UTC
### Some Background

The latest issue i'm having is probably something to do with the dart analyzer and not flutter itself, however, I'm not exactly familiar with how the platform registry works or what it is, but i'm using it for a web audio player in place of another player for mobile. In any case, maybe someone here can point me in the right place to report this.

For a while now I have been using a mixture of universal dart html (https://pub.dev/packages/universal_html) and a platformViewRegistry for web specifically. Found the solution from someone on github a while ago. It's simply

```dart
// in some file
import 'dummy_platform_registry.dart' if (dart.library.html) 'web_platform_registry.dart' as ui;
```

And two dummy registries i.e.

The real web registry
```dart
import 'dart:ui' as ui;

// ignore: camel_case_types
class platformViewRegistry {
  static registerViewFactory(String viewId, dynamic cb) {
    // ignore:undefined_prefixed_name
    ui.platformViewRegistry.registerViewFactory(viewId, cb);
  }
}
```

A dummy registry for mobile to avoid import issues
```dart
// ignore: camel_case_types
class platformViewRegistry {
  static registerViewFactory(String viewId, dynamic cb) {}
}
```

### The Problem

The problem is simply the dart analyzer complaining about `undefined_prefixed_name`. Building anyways (ignoring the errors) works perfectly fine on all platforms, but it started happening today. 

![image](https://user-images.githubusercontent.com/10619135/82115660-2ef21f00-9732-11ea-8ead-2025adaa9b66.png)

```
The name 'platformViewRegistry' is being referenced through the prefix 'ui', but it isn't defined in any of the libraries imported using that prefix.
Try correcting the prefix or importing the library that defines 'platformViewRegistry'.dart(undefined_prefixed_name)
```

Any help into how to get the analyzer to ignore this error as I have specified the line above would be nice. Thanks!

### Doctor
```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.18.0-11.1.pre at C:\Users\cyberpwn\Documents\development\flutter
    • Framework revision 2738a1148b (2 days ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\cyberpwn\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\cyberpwn\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\cyberpwn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (3 available)
    • Nokia 6 1  • PL2GARM863007117 • android-arm64  • Android 10 (API 29)
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 81.0.4044.138

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2020-05-18 11:27
duplicate of https://github.com/flutter/flutter/issues/50018

**Closed by TahaTesser** 2020-05-18 11:27 UTC
