### ISSUE TITLE
Runner.app Build says App Needs To Be Updated

### ISSUE THREAD

**Issue by postpasspost** [flutter/flutter#76853] opened 2021-02-26 10:40 UTC
## Steps to Reproduce

1. `flutter build ios` or `flutter build ios -t lib/main_release.dart`
2. Drag&Drop the Built project<ProjectName>/build/ios/iphoneos/Runner.app
3. Wait for install
4. Popup displays "app name" Needs To Be Updated
5. Failed to find matching arch for input file: /Users/user/Library/Developer/CoreSimulator/Devices/deviceId/data/Library/Caches/com.apple.mobile.installd.staging/temp.KT2iFt/extracted/Runner.app/Runner

I need to be able to install the build on iOS.

## Logs

<details>
<summary>Logs</summary>

![Needs to be updated error](https://user-images.githubusercontent.com/78803759/109290064-6b0cf100-7827-11eb-94bd-1a5344afcf03.png)

```
No logs because not installed
```

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-FR)
    • Flutter version 1.22.6 at /Users/user/development/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone 8 (mobile) • deviceId • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

! Doctor found issues in 1 category.


```

</details>

**Comment by TahaTesser** [comment] 2021-02-26 13:36
Hi @postpasspost 
Does it use to work before?  it doesn't work on the `stable` or `master`

**Comment by postpasspost** [comment] 2021-02-26 13:38
I don't know if it ever worked. Until now I only used` flutter run` for iOS devices.

**Comment by TahaTesser** [comment] 2021-02-26 13:38
@postpasspost 
I never tried this, I'm not sure if it supported or not, can you point to some reference where this works?

**Comment by postpasspost** [comment] 2021-02-26 14:19
I'm trying to launch the result of the build to test it in the iOS simulator.
https://flutter.dev/docs/deployment/ios#create-a-build-archive

How do I install a build on iOS? (on Android I only need to drag and drop the build to the emulator)

**Comment by TahaTesser** [comment] 2021-03-01 07:20
Hi @postpasspost 
You can IPA from Xcode on a physical device, release builds are not yet supported on simulator https://github.com/flutter/flutter/issues/11754
Closing as duplicate of https://github.com/flutter/flutter/issues/11754
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-01 07:20 UTC
Labels: in triage

**Comment by psuresh2501** [comment] 2021-05-15 11:35
any idea when is it going be available. ..??
