### ISSUE TITLE
[Web][html] Unexpected gray underline below Text Widget 

### ISSUE THREAD

**Issue by Limvunhoy** [flutter/flutter#95984] opened 2021-12-31 03:21 UTC
## Steps to Reproduce

1. Embedded on Android App as WebView

**Expected results:
A normal layout as running on Mobile app 

**Actual results:
Gray underline below Text Widget using this build command: 
flutter build web --web-renderer html --profile

![2021-12-31 09 55 36](https://user-images.githubusercontent.com/39089099/147801080-88a901f3-7bde-4c65-9a3f-8854ac098b6d.jpg)

**Additional Details: 
I have create flutter web app and embedded it as a WebView on iOS and Android Native App. It's working as expected on iOS but on Android App it shows gray underline below Text Widget.

Build Command: 
flutter build web --web-renderer html --release // show gray underline on Android 
OR
flutter build web --web-renderer canvaskit --release // iOS safari not working 

I new to Flutter Web, looking forward to hear from Github Contributors. Thanks.

**Comment by maheshmnj** [comment] 2021-12-31 07:11
duplicate of https://github.com/flutter/flutter/issues/86776

**Comment by danagbemava-nc** [comment] 2021-12-31 07:21
Closing as duplicate based on above comment.

**Closed by danagbemava-nc** 2021-12-31 07:21 UTC
Labels: in triage
