### ISSUE TITLE
Hot restart / hot reload fail when using AndroidAlarmManager

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26842] opened 2019-01-21 07:38 UTC
If you use AndroidAlarmManager (meaning, you call `AndroidAlarmManager.initialize()` in your main app), then hot reloads and hot restarts pretty often crash the tool with:

```
Performing hot restart...                                       Error 105 received from application: Isolate must be runnable
Unhandled exception:
JSON-RPC error 105: Isolate must be runnable
package:json_rpc_2/src/client.dart 110:64          Client.sendRequest
package:json_rpc_2/src/peer.dart 68:15             Peer.sendRequest
package:flutter_tools/src/vmservice.dart 310:13    VMService._sendRequest
package:flutter_tools/src/vmservice.dart 836:60    VM.invokeRpcRaw
===== asynchronous gap ===========================
package:flutter_tools/src/vmservice.dart 1104:15   Isolate.invokeRpcRaw
package:flutter_tools/src/vmservice.dart 1216:12   Isolate.resume
package:flutter_tools/src/run_hot.dart 509:37      HotRunner._restartFromSources.<fn>
dart:async/zone.dart 1132:38                       _rootRunUnary
dart:async/zone.dart 1029:19                       _CustomZone.runUnary
dart:async/future_impl.dart 126:18                 _FutureListener.handleValue
dart:async/future_impl.dart 639:45                 Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 668:32                 Future._propagateToListeners
dart:async/future_impl.dart 473:7                  Future._complete
dart:async/future_impl.dart 51:12                  _SyncCompleter.complete
dart:async/runtime/libasync_patch.dart 28:18       _AsyncAwaitCompleter.complete
dart:async/runtime/libasync_patch.dart 294:13      _completeOnAsyncReturn
package:flutter_tools/src/vmservice.dart           ServiceObject.reload
===== asynchronous gap ===========================
package:flutter_tools/src/run_hot.dart 505:26      HotRunner._restartFromSources
dart:async/runtime/libasync_patch.dart 77:64       _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1132:38                       _rootRunUnary
dart:async/zone.dart 1029:19                       _CustomZone.runUnary
dart:async/future_impl.dart 126:18                 _FutureListener.handleValue
dart:async/future_impl.dart 639:45                 Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 668:32                 Future._propagateToListeners
dart:async/future_impl.dart 473:7                  Future._complete
dart:async/future_impl.dart 51:12                  _SyncCompleter.complete
dart:async/runtime/libasync_patch.dart 28:18       _AsyncAwaitCompleter.complete
dart:async/runtime/libasync_patch.dart 294:13      _completeOnAsyncReturn
package:flutter_tools/src/run_hot.dart             HotRunner._updateDevFS
dart:async/runtime/libasync_patch.dart 77:64       _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1132:38                       _rootRunUnary
dart:async/zone.dart 1029:19                       _CustomZone.runUnary
dart:async/future_impl.dart 126:18                 _FutureListener.handleValue
dart:async/future_impl.dart 639:45                 Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 668:32                 Future._propagateToListeners
dart:async/future_impl.dart 473:7                  Future._complete
dart:async/future_impl.dart 51:12                  _SyncCompleter.complete
dart:async/runtime/libasync_patch.dart 28:18       _AsyncAwaitCompleter.complete
dart:async/runtime/libasync_patch.dart 294:13      _completeOnAsyncReturn
package:flutter_tools/src/resident_runner.dart     FlutterDevice.updateDevFS
dart:async/runtime/libasync_patch.dart 77:64       _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1132:38                       _rootRunUnary
dart:async/zone.dart 1029:19                       _CustomZone.runUnary
dart:async/future_impl.dart 126:18                 _FutureListener.handleValue
dart:async/future_impl.dart 639:45                 Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 668:32                 Future._propagateToListeners
dart:async/future_impl.dart 473:7                  Future._complete
dart:async/future_impl.dart 51:12                  _SyncCompleter.complete
dart:async/runtime/libasync_patch.dart 28:18       _AsyncAwaitCompleter.complete
dart:async/runtime/libasync_patch.dart 294:13      _completeOnAsyncReturn
package:flutter_tools/src/devfs.dart               DevFS.update
dart:async/runtime/libasync_patch.dart 77:64       _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1132:38                       _rootRunUnary
dart:async/zone.dart 1029:19                       _CustomZone.runUnary
dart:async/future_impl.dart 126:18                 _FutureListener.handleValue
dart:async/future_impl.dart 639:45                 Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 668:32                 Future._propagateToListeners
dart:async/future_impl.dart 473:7                  Future._complete
dart:async/future_impl.dart 51:12                  _SyncCompleter.complete
dart:async/runtime/libasync_patch.dart 28:18       _AsyncAwaitCompleter.complete
dart:async/runtime/libasync_patch.dart 294:13      _completeOnAsyncReturn
package:flutter_tools/src/devfs.dart               _DevFSHttpWriter.write
dart:async/runtime/libasync_patch.dart 77:64       _asyncThenWrapperHelper.<fn>
dart:async/zone.dart 1132:38                       _rootRunUnary
dart:async/zone.dart 1029:19                       _CustomZone.runUnary
dart:async/future_impl.dart 126:18                 _FutureListener.handleValue
dart:async/future_impl.dart 639:45                 Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 668:32                 Future._propagateToListeners
dart:async/future_impl.dart 483:5                  Future._completeWithValue
dart:async/future_impl.dart 513:7                  Future._asyncComplete.<fn>
dart:async/zone.dart 1124:13                       _rootRun
dart:async/zone.dart 1021:19                       _CustomZone.run
dart:async/zone.dart 947:23                        _CustomZone.bindCallback.<fn>
dart:async/schedule_microtask.dart 41:21           _microtaskLoop
dart:async/schedule_microtask.dart 50:5            _startMicrotaskLoop
dart:isolate/runtime/libisolate_patch.dart 115:13  _runPendingImmediateCallback
dart:isolate/runtime/libisolate_patch.dart 172:5   _RawReceivePortImpl._handleMessage
```

**Comment by Hixie** [comment] 2019-01-21 07:40
The problem with the tool itself crashing in this situation is https://github.com/flutter/flutter/issues/26568. This bug is specifically about the hot reload or hot restart not working.

**Comment by Hixie** [comment] 2019-01-22 17:44
cc @bkonyi

**Comment by Hixie** [comment] 2019-01-22 23:53
This is really bad but it's not the highest priority problem with this plugin so I'm removing the "critical" label.

**Comment by Hixie** [comment] 2019-01-26 08:41
Also, when it doesn't crash, hot restart is restarting the app double, maybe in both the main isolate and the alarm manager one? If I put a print in my `void main`, I see it once on startup and twice after I hit `R`.

**Comment by bkonyi** [comment] 2019-01-30 20:43
This isn't an issue specific to the alarm manager plugin, but is a bug in how the framework performs a hot restart with multiple isolates. When updating the DevFS on device during a restart, a `mainPath` parameter is passed which points to the main library of the application. I'm guessing it's using this path to perform the restart, which would be why we're seeing duplicate output from prints in `main()`. Haven't had a chance to dig into this deeper, but it's probably related to #20743, #18600, and #26953.

**Comment by jonahwilliams** [comment] 2019-03-24 17:37
We should only reload or restart isolates that match the name of the entrypoint we're compiling.

**Comment by jonahwilliams** [comment] 2019-03-25 16:58
@Hixie , do you have an example app on github somewhere I can use to test https://github.com/flutter/flutter/pull/29882 ?

**Comment by Hixie** [comment] 2019-03-26 06:28
The app I was writing was http://seamonkeysocial.cruises/cruisemonkey/.
You may have to re-enable the background logic (or just go back one commit).

**Comment by bkonyi** [comment] 2019-05-23 21:23
Closing as it's a duplicate of #20743, #18600, and #26953.

**Closed by bkonyi** 2019-05-23 21:23 UTC
Labels: dependency: dart, p: android_alarm_manager, plugin, severe: crash, t: hot reload, tool
