### ISSUE TITLE
Installing build\app\outputs\apk\app.apk... Error connecting to the service protocol: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:57204/BRlg7YmMVBc=/ws

### ISSUE THREAD

**Issue by vasubandhu** [flutter/flutter#36760] opened 2019-07-23 13:10 UTC

**Comment by DanTup** [comment] 2019-07-25 09:23
Are you using Android Q / API Level 29? If so, I think this is likely a dupe of https://github.com/flutter/flutter/issues/33050.

**Closed** 2019-08-15 10:14 UTC
Labels: waiting for customer response
