### ISSUE TITLE
Minimum version requirements for WebView

### ISSUE THREAD

**Issue by puzhengwu** [flutter/flutter#87781] opened 2021-08-06 07:14 UTC
The documentation shows that the minimum support for Android 19 is possible, but the actual support is at least 20, that is the documentation is not correct or the code is not correct, if we can not support 19, this will affect our overall technology selection for using the Flutter, because there are a large number of H5 implementations, it is not possible to fully port the Project to the Flutter

**Comment by stuartmorgan** [comment] 2021-08-06 10:09
Duplicate of https://github.com/flutter/flutter/issues/85215

The README is [fixed on master](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/README.md#android-platform-views), but hasn't been published yet.

**Closed by stuartmorgan** 2021-08-06 10:09 UTC

**Comment by puzhengwu** [comment] 2021-08-06 17:02
> 重复#85215
> 
> README 已[在 master](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/README.md#android-platform-views)上[修复](https://github.com/flutter/plugins/blob/master/packages/webview_flutter/webview_flutter/README.md#android-platform-views)，但尚未发布。

I am in hybrid mode, not virtual mode, android 19 phone web page can not be operated, any touch is invalid, in debugging, I found that the lowest error is android 20, because this phone can only be upgraded to 19, so I can not use the APP developed by Flutter. But apps developed in a native way will work fine with WebView, so this is a weird problem, so let's face it
