### ISSUE TITLE
[CP] Support for Android 13 (SDK 33) as targetSdkVersion

### ISSUE THREAD

**Issue by blok5025** [flutter/flutter#109964] opened 2022-08-21 22:47 UTC
### issue_link

https://github.com/flutter/flutter/issues/105764

### Commit Hash

unknown (refer to the issue)

### Target

stable

### pr_link

flutter-2.13-candidate.0

### Impacted Users

all Flutter devs, all end-customers

### Impact Description

Now that Android 13 is stable and that most of the packages have migrated to support SDK 33. It is important that the fix currently in master is pushed to Stable

### Workaround

No workaround for this compatibility issue

### Risk

low

### Test Coverage

yes

**Comment by itsjustkevin** [comment] 2022-08-22 15:57
@blok5025 have you identified the fix in master?  

Please provide more information on this request for it to be considered for a cherry-pick.

**Comment by blok5025** [comment] 2022-08-22 19:53
I don't think I will be much of help in terms of determining which fix on Master solved this issue @exaby73 Maybe you can help me here to identify which fix needs to be cherry picked. The fix might be older than June 10, unsure how to actually pin point it.

**Comment by exaby73** [comment] 2022-08-23 07:20
There is an open issue related https://github.com/flutter/flutter/issues/103356 as well as a related PR that was closed https://github.com/flutter/flutter/pull/104662

I couldn't find the exact PR that fixed this. For the exact bug I am referring to, see https://github.com/flutter/flutter/issues/109963#issuecomment-1222261829

**Comment by blok5025** [comment] 2022-08-23 16:19
@GaryQian is this https://github.com/flutter/flutter/pull/104662 the fix for the compatibility issue with SDK 33?

**Comment by GaryQian** [comment] 2022-08-23 18:32
@blok5025 No, that issue is no longer relevant since API 33 is now an official release. Only preview APIs get a string identifier. Once they are stable, they get assigned an integer.

**Comment by GaryQian** [comment] 2022-08-23 18:35
This PR (https://github.com/flutter/flutter/pull/109583) defaults to targeting android API 33 on master channel, and it should be straightforwards to manually change your apps to target API 33 by editing your `android/app/build.gradle`, although I would recommend changing it back to the dynamically set value once your experimentation is complete.

**Comment by stuartmorgan** [comment] 2022-08-23 19:47
> I don't think I will be much of help in terms of determining which fix on Master solved this issue @exaby73 Maybe you can help me here to identify which fix needs to be cherry picked.

Since we're not sure what changed the behavior here, it would need to be bisected. You'd need to try checking out various hashes of Flutter and seeing if the problem reproduces (e.g., starting from the current `master`, skip back a month at a time until you find a failure, then try something half-way between the last failure and first success, repeating that until you find a small range of commits.) Once we have a small range, we can inspect the changes.

**Comment by exaby73** [comment] 2022-08-24 13:48
I cannot reproduce the issue I mentioned in https://github.com/flutter/flutter/issues/109963#issuecomment-1222261829 with the current master version. @blok5025 is this still reproducible on your end?

**Comment by CaseyHillers** [comment] 2022-08-30 18:13
Closing as flutter-2.13-candidate.0 is no longer on the stable channel (see the latest Flutter 3.3.0 stable release)

**Closed by CaseyHillers** 2022-08-30 18:13 UTC
Labels: cp: review
