### ISSUE TITLE
Flutter web mobile browser render issues on 'Desktop site' version

### ISSUE THREAD

**Issue by omatt** [flutter/flutter#87798] opened 2021-08-06 11:26 UTC
## Steps to Reproduce

1. Create any flutter app
2. Build the web version of the app with `flutter build web`
3. Deploy the web build (in my case, I used Firebase Hosting)
4. Access deployed web page using mobile browser (Chrome)
5. Toggle 'Desktop site' to view the mobile page in its "desktop version"
6. Web page render is stretched

I don't think Firebase Hosting should be causing this issue. I have deployed a Flutter sample that you can try accessing on a mobile browser: https://webtest-68960.web.app

**Expected results:** 

'Desktop site' version on mobile browser should be rendered like it's opened on a desktop browser.

**Actual results:** 

<img alt="screenshot" src="https://user-images.githubusercontent.com/4143153/128502505-c897c9e3-1499-461e-b1b5-6e2e7f14770e.jpg" height="500">

Test device:
SM-N975F, Android 11
Chrome 92.0.4515.131

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-x64, locale en)
    • Flutter version 2.2.3
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • AOSP on IA Emulator (mobile) • emulator-5554                        • android-x86    • Android 9 (API 28) (emulator)
    • iPhone Xs (mobile)           • 82CF4677-9933-4698-AD5C-823D6E93F283 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    • Chrome (web)                 • chrome                               • web-javascript • Google Chrome 92.0.4515.131

! Doctor found issues in 1 category.
```

</details>

**Comment by TahaTesser** [comment] 2021-08-06 13:27
Hi @omatt 
I think this is the same underlying cause as https://github.com/flutter/flutter/issues/77084#
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/77084#
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-06 13:27 UTC
Labels: in triage
