### ISSUE TITLE
How to hot fix my app

### ISSUE THREAD

**Issue by lucywhite168** [flutter/flutter#25689] opened 2018-12-22 04:54 UTC
Now I have a app written using flutter,when it has a new version,I want distribute the new version to my customs,What should I do? The only way I have found is ask them delete the old version on their phone and download the new version. I want my customs update to the new version though hot fix,what should I do? Thanks very much.

**Comment by koudle** [comment] 2018-12-22 06:44
That's not yet supported.

**Comment by lucywhite168** [comment] 2018-12-22 06:48
So。。。what should i do？delete then download the new？

**Comment by koudle** [comment] 2018-12-22 06:52
Yes, it is the only way

**Comment by lucywhite168** [comment] 2018-12-22 06:58
中文测试~

**Comment by lucywhite168** [comment] 2018-12-22 07:01
Does anybody have other way？

**Comment by zoechi** [comment] 2018-12-22 14:30
Are Play Store and AppStore not doing that for you automatically if you publish a new version?

**Comment by zoechi** [comment] 2018-12-22 14:30
Duplicate of #14330

**Closed by zoechi** 2018-12-22 14:30 UTC

**Comment by ahong222** [comment] 2019-01-24 03:44
I also want to know

**Comment by zoechi** [comment] 2019-01-24 06:40
@ahong222 Follow #14330
