### ISSUE TITLE
Recent version of flutter is breaking

### ISSUE THREAD

**Issue by ArunYogi** [flutter/flutter#51355] opened 2020-02-24 19:50 UTC
## Steps to Reproduce

Issue happening in Windows system
1. ... Run >flutter upgrade
2. ... Run >flutter doctor

## Logs

Checking Dart SDK version...
Downloading Dart SDK from Flutter engine e1e6ced81d029258d449bdec2ba3cddca9c2ca0c...
Unzipping Dart SDK...
Exception calling "ExtractToFile" with "3" argument(s): "Access to the path
'F:\apps\flutter\bin\cache\dart-sdk\bin\dart.exe' is denied."
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:1056
char:25
+ ...             [System.IO.Compression.ZipFileExtensions]::ExtractToFile( ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException

Building flutter tool...
Running pub upgrade...
The system cannot find the path specified.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...

```
```

```
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine e1e6ced81d029258d449bdec2ba3cddca9c2ca0c...
Unzipping Dart SDK...
Exception calling "ExtractToFile" with "3" argument(s): "Access to the path
'F:\apps\flutter\bin\cache\dart-sdk\bin\dart.exe' is denied."
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:1056
char:25
+ ...             [System.IO.Compression.ZipFileExtensions]::ExtractToFile( ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException

Building flutter tool...
Running pub upgrade...
The system cannot find the path specified.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
```

**Comment by jonahwilliams** [comment] 2020-02-24 19:54
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-24 19:54 UTC
