### ISSUE TITLE
[web]: Fetch Data Example throws "Failed assertion: boolean expression must not be null" error

### ISSUE THREAD

**Issue by testphys** [flutter/flutter#36778] opened 2019-07-23 18:28 UTC
I am on firefox 68.0 and the error I get when I run `webdev serve` is "Failed assertion: boolean expression must not be null" which is caused by a `snapshot.hasData` being null and not boolean.

```
name: leadership_coach

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  http: ^0.12.0+2

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
```

**Comment by kevmoo** [comment] 2019-07-23 23:51
Where is `snapshot.hasData` coming from?

**Comment by testphys** [comment] 2019-07-24 07:01
It's part of a FutureBuilder. See the example code below in which I just replaced the flutter with flutter_web.
```
import 'dart:async';
import 'dart:convert';

import 'package:flutter_web/material.dart';
import 'package:http/http.dart' as http;

Future<Post> fetchPost() async {
  final response =
      await http.get('https://jsonplaceholder.typicode.com/posts/1');

  if (response.statusCode == 200) {
    // If the call to the server was successful, parse the JSON.
    return Post.fromJson(json.decode(response.body));
  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load post');
  }
}

class Post {
  final int userId;
  final int id;
  final String title;
  final String body;

  Post({this.userId, this.id, this.title, this.body});

  factory Post.fromJson(Map<String, dynamic> json) {
    return Post(
      userId: json['userId'],
      id: json['id'],
      title: json['title'],
      body: json['body'],
    );
  }
}

void main() => runApp(MyApp(post: fetchPost()));

class MyApp extends StatelessWidget {
  final Future<Post> post;

  MyApp({Key key, this.post}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Fetch Data Example'),
        ),
        body: Center(
          child: FutureBuilder<Post>(
            future: post,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                return Text(snapshot.data.title);
              } else if (snapshot.hasError) {
                return Text("${snapshot.error}");
              }

              // By default, show a loading spinner.
              return CircularProgressIndicator();
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by yjbanov** [comment] 2019-08-01 22:24
@testphys Have you tried running this code using `flutter run -d chrome`? I'm curious if the bug is only in the fork or in the upstream Flutter.

**Comment by Vanethos** [comment] 2019-09-05 22:46
This is not caused by the `FutureBuilder`, this issue is raised when from the `http` `Response` we are accessing the `body` property.

```
Failed assertion: boolean expression must not be null dart_sdk.js:19110:15
dart:sdk_internal 17552:33                                                                            matchAsPrefix
package:string_scanner/src/packages/string_scanner/src/string_scanner.dart 169:25                     matches
package:string_scanner/src/packages/string_scanner/src/string_scanner.dart 126:19                     scan
package:http_parser/packages/http_parser/src/media_type.dart 48:14                                    <fn>
package:http_parser/packages/http_parser/src/utils.dart 13:16                                         wrapFormatException
package:http_parser/packages/http_parser/src/media_type.dart 46:12                                    parse
package:http/src/packages/http/src/response.dart 84:39                                                _contentTypeForHeaders
package:http/src/packages/http/src/response.dart 77:66                                                _encodingForHeaders
package:http/src/packages/http/src/response.dart 27:51                                                get body
package:webcvportfolio/data/services/packages/webcvportfolio/data/services/medium_service.dart 13:32  <fn>
dart:sdk_internal 25433:9   
```

A workaround for anyone having this error in Firefox is to run the release version `webdev serve -r`, I didn't have more problems with it.

**Comment by kaede28** [comment] 2019-11-13 15:57
I had the same problem in Dart 2.6.0 and webdev 2.5.3, and Chrome 78. I started getting these errors after I upgraded Chrome and Dart.

Instead of accessing the body property from http Response I just accessed bodyBytes.

Instead of doing this: _json.decode(response.body)_
I did this: _json.decode(utf8.decode(response.bodyBytes))_

It seems like a temporary solution to this problem.

**Comment by yjbanov** [comment] 2019-11-13 21:09
The `dart:sdk_internal 17552:33` from the stack trace does not provide enough information. We recently fixed stack-traces in profile web builds. Could you please reproduce this again and provide the new stack trace?

**Comment by kaede28** [comment] 2019-11-13 21:40
Sure, it's a pleasure to help. Is this information enough or do you need the full stack trace?

`EXCEPTION: Failed assertion: boolean expression must not be null`

`STACKTRACE: 
dart:sdk_internal                                    decode
package:http/src/response.dart 27:42                 get body
package:element/controller/service/users.dart 31:41  fetch
package:stack_trace                                  <fn>
package:angular/src/core/zone/ng_zone.dart 144:18    <fn>
dart:sdk_internal                                    runUnary
package:angular/src/core/zone/ng_zone.dart 141:18    [_runUnary]
dart:sdk_internal                                    <fn>
package:angular/src/core/zone/ng_zone.dart 117:11    <fn>
package:stack_trace                                  <fn>
package:angular/src/core/zone/ng_zone.dart 132:18    <fn>
dart:sdk_internal                                    run
package:angular/src/core/zone/ng_zone.dart 129:18    [_run]`

**Comment by yjbanov** [comment] 2019-11-13 21:48
@kaede28 You seem to be using a different web framework. It says "angular" in the stack trace, but this is Flutter :)

**Comment by kaede28** [comment] 2019-11-13 23:17
Oh, sorry about that. As I came here by researching the same problem, I thought my input could help. I assumed Flutter shared some code base with Angular.

**Comment by vsmenon** [comment] 2020-02-04 15:30
Are folks still seeing this?  As @yjbanov said above, stack traces have been improved since the original bug was filed, so a new trace would be helpful.

**Comment by nateshmbhat** [comment] 2020-04-06 10:30
i'm also getting the same issue : 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.15.18-pre.1, on Mac OS X 10.15.2 19C57, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.43.2)

```

**Comment by nateshmbhat** [comment] 2020-04-06 11:48
The error reporting is really bad and the stacktrace shows error in some totally different line in a different file than the one where the error happens.

**Comment by nateshmbhat** [comment] 2020-04-06 11:48
For me , the issue was that I was assigning a null value to the **Visibility** widget's **visible** property . But it was showing the error in some whole another unrelated page.

**Comment by yjbanov** [comment] 2022-01-06 00:09
`webdev serve` is no longer supported. Use `flutter run -d chrome` for debugging instead. If there are issues related to stack traces that haven't been filed yet, please open a new issue. I'm going to close this one.

**Closed by yjbanov** 2022-01-06 00:09 UTC
Labels: framework, dependency: dart, platform-web, a: error message, passed first triage, P5
