### ISSUE TITLE
======== Exception caught by widgets library ======================================================= The following assertion was thrown building Builder: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3566 pos 18: '!keyReservation.contains(key)': is not true.

### ISSUE THREAD

**Issue by bperrenoud** [flutter/flutter#132059] opened 2023-08-07 15:37 UTC
I got the following exception, usually when the app opens after getting a firebase remote message, but I also got it randomly

The error is simply
```

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Builder:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3566 pos 18: '!keyReservation.contains(key)': is not true.
```

Below, there is this mention:

> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
>   https://github.com/flutter/flutter/issues/new?template=2_bug.md 
> 

So here it is. I cannot share any code / project since this is a professional private repo

**Comment by danagbemava-nc** [comment] 2023-08-08 07:03
Hi @bperrenoud, even though the error message states to file an issue without a minimal reproducible code sample, we cannot make any headway on solving the issue. 
Please provide a complete minimal reproducible code sample (it does not have to be your application code nor do we expect it to be) preferably without any third-party packages along with the output of flutter doctor -v so that we can investigate this issue. 

Thank you

**Comment by bperrenoud** [comment] 2023-08-08 16:25
Hi
I unfortunatley don't have a clean project sample and since it happens with push notifs, any sample need a firebase api key to test. But I actually think this is not an error in navigator (although the assert message is not quite clear).

So in conclusion I think that the assert is rightfully triggered and that the "readable" reason should be something like "The same navigation event might have been called twice at the same time". On my side, it is ok to close this issue, but I past below some more info in case there is an interest on your side to try and reproduce

The error triggers because the firebase_messaging library seems to have a bug. So to reproduce, setup the firebase_messaging to recieve push notifs. Here is what I have: On the init function of one of your Root widget, you have something like this:

```
  @override
  void initState() {
    FirebaseMessaging.instance.getInitialMessage().then((message) {
      _handleRemoteMessage(message);
    });

    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      _handleRemoteMessage(message);
    });

    super.initState();
  }
```

Accorind to firebase doc, these two callbacks are mutually excusive (one is triggered when app is in background, the other when the app was completely closed). In practice they are called together so if the _handleRemoteMessage function calls a Navigation event, the same event it triggered twice in the same frame, which seems to trigger the assert.

Here is the output from flutter doctor

[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0 22A380 darwin-arm64, locale en-CH)
    • Flutter version 3.10.5 on channel stable at /opt/homebrew/Caskroom/flutter/3.3.10/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (8 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/basileperrenoud/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/basileperrenoud/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 3D930FD8-3E5D-4BAA-9080-296CFF0F5AEC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 115.0.5790.170

[✓] Network resources
    • All expected network resources are available.

**Comment by danagbemava-nc** [comment] 2023-08-09 07:17
Thanks for the details. 

As for the error message, it may not always be the case that calling the same event twice may trigger that error so I think a generic message is ok. 

Closing this since you have figured out the source of the bug in your code.

Thank you

**Closed by danagbemava-nc** 2023-08-09 07:17 UTC
Labels: in triage
