### ISSUE TITLE
Bringup tests take a long time to get scheduled

### ISSUE THREAD

**Issue by vashworth** [flutter/flutter#136499] opened 2023-10-12 22:12 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing infra issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Ateam-infra)

### Type of Request

bug

### Infrastructure Environment

LUCI

### What is happening?

I added a bunch of tests to bringup at ~12 PM CDT (https://github.com/flutter/flutter/pull/136463). However, the tests are being scheduled very slowly. 

For example, this test was only scheduled to run 1 time within 5 hours, even though all of the bots are idle and there's been 9 commits since it was added.

https://ci.chromium.org/ui/p/flutter/builders/luci.flutter.staging/Mac_arm64%20run_release_test_macos

![Screenshot 2023-10-12 at 5 09 57 PM](https://github.com/flutter/flutter/assets/15619084/77f5f6e9-ee3a-42de-a749-79d818ce2262)

### Expected results

I expect the tests to be scheduled within a reasonable amount of time

**Comment by vashworth** [comment] 2023-10-12 22:14
Actually seems like it's maybe not just specific to bringup tests. I see the same issue in prod tests

**Comment by ricardoamador** [comment] 2023-10-19 18:24
Keyong has a PR that may address this.

**Comment by keyonghan** [comment] 2023-10-23 16:10
Is this issue for presubmit or post submit? Based on https://github.com/flutter/flutter/pull/136498#issuecomment-1761701806, seems with presubmit? But from this Bug description, a post-submit screenshot is posted.

If this is for post submit targets, it is expected to wait for backfiller to cover top rows. To avoid unexpected buildbucket/pubsub exception, we have throttled the number of tasks to be scheduled at each time (50 targets will be picked up in each backfill).

**Comment by keyonghan** [comment] 2023-10-23 17:05
Thanks for the context. Yeah, as mentioned above, this is an intended behavior and meets our SLOs.

The situation might be more obvious for bringup: true targets as we now have ~50 targets running in staging. I guess we should follow up on those `bringup: true` targets to see if applicable for prod.

I will check those from the flake bot.

With all being said, I am lowering the priority to P2 in case this affects our commit validation time (which I doubt though).

**Comment by keyonghan** [comment] 2024-03-18 23:19
All platform queue time has been well within SLO. Closing as obsolete.

**Closed by keyonghan** 2024-03-18 23:19 UTC
Labels: team-infra, P2, triaged-infra
