### ISSUE TITLE
[url_launcher] Add chrome custom tabs

### ISSUE THREAD

**Issue by lazylazyllama** [flutter/flutter#67639] opened 2020-10-08 14:46 UTC
The url_launcher should have the ability to open urls as a custom tab instead of a webview, when the url should be opened in-app.

**Comment by MrBirb** [comment] 2021-02-27 22:07
@pedromassangocode Duplicate of #18589

**Comment by pedromassangocode** [comment] 2021-03-01 10:44
Closing as a duplicate of https://github.com/flutter/flutter/issues/18589. For anyone interested in this feature, please follow up on https://github.com/flutter/flutter/issues/18589.

Thanks for the heads up!

**Closed by pedromassangocode** 2021-03-01 10:44 UTC
Labels: p: first party, p: url_launcher, passed first triage, plugin, severe: new feature
