### ISSUE TITLE
--dart-define doesn't work on current stable

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#82110] opened 2021-05-08 13:19 UTC
When switching back from master to stable I experienced an unpleasant surprise because my App stopped behaving as it should. After some digging it turned out that it used the wrong backend because the server address that I passed in via `--dart-define` seems to be ignored as you can see on this screenshot. the red circled debug output is a print of the `server` constant.

![image](https://user-images.githubusercontent.com/16635729/117540482-07195c80-b010-11eb-94e9-536cf0419dde.png)

```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.18363.1500], locale de-DE)
    • Flutter version 2.0.6 at C:\Entwicklung\flutter
    • Framework revision 1d9032c7e1 (9 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
```

**Comment by escamoteur** [comment] 2021-05-08 15:22
hmm, that's not what is shown here https://dartcode.org/docs/using-dart-define-in-flutter/
 And on master it works. it's also against the normal convention for parameters

**Comment by jonahwilliams** [comment] 2021-05-08 18:32
The format is fine. The problem is that dart defines are not supported correctly be the tooling on stable, you need to use a beta channel after https://github.com/flutter/flutter/pull/75027

If you're doing any non-trivial desktop development I highly recommend against using the stable channel.

**Comment by escamoteur** [comment] 2021-05-08 22:11
@jonahwilliams I switched to stable because of the keyboard problems on master. Thankfully I was shown there is a workaround for the right-shift issue, so I'm back on master

**Comment by jonahwilliams** [comment] 2021-05-10 02:23
OK, I'll close the issue then since we don't plan to hotfix it

**Closed by jonahwilliams** 2021-05-10 02:23 UTC
Labels: a: build, tool
