### ISSUE TITLE
"pub is deprecated" error message when building flutter tool

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#69980] opened 2020-11-06 20:49 UTC
```
jonahwilliams-macbookpro2:flutter jonahwilliams$ flutter pub
Downloading Dart SDK from Flutter engine cf376142ed5fb9c6433bb9cf7ee4d3540387965f...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  177M  100  177M    0     0  29.9M      0  0:00:05  0:00:05 --:--:-- 31.3M
Building flutter tool...
The `pub` command is deprecated. Run `dart pub` instead.
```

**Comment by Hixie** [comment] 2020-11-08 01:18
Marking P2 because this should be a stop-ship bug, but it's not critical until a few weeks before our next release.
cc @pcsosinski for visibility.

**Comment by jonahwilliams** [comment] 2020-11-08 17:58
I tried to switch to `dart pub` in the bash/batch bootstrap scripts, but that command does not accept a verbosity option, resulting in the following stdout when the tool gets built:

```
^Cjonahwilliams-macbookpro2:flutter_tools jonahwilliams$ flutter
Building flutter tool...
Resolving dependencies... (1.7s)
  _fe_analyzer_shared 7.0.0 (12.0.0 available)
  analyzer 0.39.17 (0.40.6 available)
  archive 2.0.13
  args 1.6.0
  async 2.5.0-nullsafety.3
  boolean_selector 2.1.0-nullsafety.3
  browser_launcher 0.1.7
  build_daemon 2.1.4
  built_collection 4.3.2
  built_value 7.1.0
  charcode 1.2.0-nullsafety.3
  checked_yaml 1.0.2
  cli_util 0.2.0
  clock 1.1.0-nullsafety.3
  collection 1.15.0-nullsafety.5
  completion 0.2.2
  convert 2.1.1
  coverage 0.14.1
  crypto 2.1.5
  csslib 0.16.2
  dds 1.4.1
  devtools 0.9.3+4 (0.9.4 available)
  devtools_server 0.9.3+4 (0.9.4 available)
  devtools_shared 0.9.3+4 (0.9.4 available)
  dwds 7.0.2
  fake_async 1.2.0-nullsafety.3
  file 6.0.0-nullsafety.4
  file_testing 2.1.0
  fixnum 0.10.11
  flutter_template_images 1.0.1
  glob 1.2.0
  html 0.14.0+4
  http 0.12.2
  http_multi_server 2.2.0
  http_parser 3.1.4
  intl 0.16.1
  io 0.3.4
  js 0.6.3-nullsafety.3
  json_annotation 3.1.0
  json_rpc_2 2.2.2
  logging 0.11.4
  matcher 0.12.10-nullsafety.3
  meta 1.3.0-nullsafety.6
  mime 0.9.7
  mockito 4.1.1 (4.1.3 available)
  multicast_dns 0.2.2
  mustache_template 1.0.0+1
  native_stack_traces 0.3.7
  node_interop 1.2.0
  node_io 1.1.1
  node_preamble 1.4.12
  package_config 1.9.3
  path 1.8.0-nullsafety.3
  pedantic 1.10.0-nullsafety.3
  petitparser 3.1.0
  platform 3.0.0-nullsafety.4
  pool 1.5.0-nullsafety.3
  process 4.0.0-nullsafety.4
  pub_semver 1.4.4
  pubspec_parse 0.1.5
  quiver 2.1.4+1 (2.1.5 available)
  shelf 0.7.5 (0.7.9 available)
  shelf_packages_handler 2.0.0
  shelf_proxy 0.1.0+7
  shelf_static 0.2.8
  shelf_web_socket 0.2.3
  source_map_stack_trace 2.1.0-nullsafety.4
  source_maps 0.10.10-nullsafety.3
  source_span 1.8.0-nullsafety.4
  sse 3.6.0
  stack_trace 1.10.0-nullsafety.6
  stream_channel 2.1.0-nullsafety.3
  stream_transform 1.2.0
  string_scanner 1.1.0-nullsafety.3
  sync_http 0.2.0
  term_glyph 1.2.0-nullsafety.3
  test 1.16.0-nullsafety.9
  test_api 0.2.19-nullsafety.6
  test_core 0.3.12-nullsafety.9
  typed_data 1.3.0-nullsafety.5
  usage 3.4.2
  uuid 2.2.2
  vm_service 5.2.0 (5.5.0 available)
  vm_snapshot_analysis 0.5.5
  watcher 0.9.7+15
  web_socket_channel 1.1.0
  webdriver 2.1.2
  webkit_inspection_protocol 0.7.4
  xml 4.5.1
  yaml 2.2.1
No dependencies changed.
```

**Comment by aissat** [comment] 2020-11-08 19:31
@Hixie same issues

**Comment by Hixie** [comment] 2020-11-08 21:31
cc @mit-mit for escalation

**Comment by mit-mit** [comment] 2020-11-09 07:18
Duplicate of https://github.com/dart-lang/sdk/issues/44105

Background in https://medium.com/dartlang/announcing-dart-2-8-7750918db0a

@pq verbosity seems to work for me:
```
$ dart pub get --verbosity=error
$ dart pub get
Resolving dependencies...
Got dependencies!
$ dart pub get --verbosity=error
$
```

Do you have a PR for those changes? Would be great to get that landed; I'm happy to take a look.

**Comment by tvolkert** [comment] 2020-11-09 18:56
FYI, I got this when running `flutter update-packages` (not `flutter pub`)

**Comment by Hixie** [comment] 2020-11-09 23:01
(I'm going to reopen this one just to make sure I see it during critical triage meetings so I don't forget about it.)

**Comment by Hixie** [comment] 2020-11-09 23:02
(assigned to myself to indicate that we're not expecting someone on the Flutter team to need to work on this currently.)

**Comment by jonahwilliams** [comment] 2020-11-10 22:46
AT ToT:

```
jonahwilliams-macbookpro2:flutter jonahwilliams$ flutter
Building flutter tool...
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with --help, shows hidden options.
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting when this command runs.

Available commands:
  analyze           Analyze the project's Dart code.
  assemble          Assemble and build Flutter resources.
  attach            Attach to a running app.
  bash-completion   Output command line shell completion setup scripts.
  build             Build an executable app or install bundle.
  channel           List or switch Flutter channels.
  clean             Delete the build/ and .dart_tool/ directories.
  config            Configure Flutter settings.
  create            Create a new Flutter project.
  devices           List all connected devices.
  doctor            Show information about the installed tooling.
  downgrade         Downgrade Flutter to the last active version for the current channel.
  drive             Run integration tests for the project on an attached device or emulator.
  emulators         List, launch and create emulators.
  format            Format one or more Dart files.
  gen-l10n          Generate localizations for the current project.
  install           Install a Flutter app on an attached device.
  logs              Show log output for running Flutter apps.
  precache          Populate the Flutter tool's cache of binary artifacts.
  pub               Commands for managing Flutter packages.
  run               Run your Flutter app on an attached device.
  screenshot        Take a screenshot from a connected device.
  symbolize         Symbolize a stack trace from an AOT-compiled Flutter app.
  test              Run Flutter unit tests for the current project.
  upgrade           Upgrade your copy of Flutter.

```

Seems to be better

**Comment by Hixie** [comment] 2020-11-10 23:55
Great!

**Closed by Hixie** 2020-11-10 23:55 UTC
Labels: P2, dependency: dart, passed first triage, tool
