### ISSUE TITLE
App is crashing when camera is initialized

### ISSUE THREAD

**Issue by AmolGangadhare** [flutter/flutter#28455] opened 2019-02-25 10:03 UTC
This issue is causing app to crash. This seems to be permissions issue at runtime (for very first time run). Sometimes when screens are switched, app crashes at       
```
CameraPlugin.java line 724 surfaces.add(pictureImageReader.getSurface());
```
(less frequently).

## Steps to Reproduce
1. Followed steps and example given at https://pub.dartlang.org/packages/camera#-example-tab- and then run the app.

## Logs
```
[  +31 ms] W/Activity(18792): Can reqeust only one set of permissions at a time
[   +4 ms] E/MethodChannel#plugins.flutter.io/camera(18792): Failed to handle method call
[        ] E/MethodChannel#plugins.flutter.io/camera(18792): java.lang.IllegalStateException: Reply already submitted
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:208)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at io.flutter.plugins.camera.CameraPlugin$Camera$1.run(CameraPlugin.java:331)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at
io.flutter.plugins.camera.CameraPlugin$CameraRequestPermissionsListener.onRequestPermissionsResult(CameraPlugin.java:263)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at android.app.Activity.requestPermissions(Activity.java:4397)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at io.flutter.plugins.camera.CameraPlugin$Camera.<init>(CameraPlugin.java:351)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:187)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at android.os.MessageQueue.next(MessageQueue.java:325)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at android.os.Looper.loop(Looper.java:142)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at android.app.ActivityThread.main(ActivityThread.java:6626)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[        ] E/MethodChannel#plugins.flutter.io/camera(18792):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
[        ] E/FlutterNativeView(18792): Uncaught exception in binary message listener
[        ] E/FlutterNativeView(18792): java.lang.IllegalStateException: Reply already submitted
[        ] E/FlutterNativeView(18792):  at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
[        ] E/FlutterNativeView(18792):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:218)
[        ] E/FlutterNativeView(18792):  at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
[        ] E/FlutterNativeView(18792):  at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/FlutterNativeView(18792):  at android.os.MessageQueue.next(MessageQueue.java:325)
[        ] E/FlutterNativeView(18792):  at android.os.Looper.loop(Looper.java:142)
[        ] E/FlutterNativeView(18792):  at android.app.ActivityThread.main(ActivityThread.java:6626)
[        ] E/FlutterNativeView(18792):  at java.lang.reflect.Method.invoke(Native Method)
[        ] E/FlutterNativeView(18792):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[        ] E/FlutterNativeView(18792):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
[   +7 ms] E/flutter (18792): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
[        ] E/flutter (18792): CameraException(cameraPermission, Camera permission request ongoing)
[        ] E/flutter (18792): #0      CameraController.initialize (package:camera/camera.dart:238:7)
[        ] E/flutter (18792): <asynchronous suspension>
[        ] E/flutter (18792): #1      _HomeScreen.initCameras (package:flutter_poc_app/ui/home_screen.dart:29:25)
[        ] E/flutter (18792): <asynchronous suspension>
[        ] E/flutter (18792): #2      new _HomeScreen (package:flutter_poc_app/ui/home_screen.dart:21:5)
[        ] E/flutter (18792): #3      HomeScreen.createState (package:flutter_poc_app/ui/home_screen.dart:16:20)
[        ] E/flutter (18792): #4      new StatefulElement (package:flutter/src/widgets/framework.dart:3789:23)
[        ] E/flutter (18792): #5      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:795:38)
[        ] E/flutter (18792): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2948:40)
[        ] E/flutter (18792): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
[        ] E/flutter (18792): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
[        ] E/flutter (18792): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
[        ] E/flutter (18792): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
[        ] E/flutter (18792): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
[        ] E/flutter (18792): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
[        ] E/flutter (18792): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
[        ] E/flutter (18792): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
[        ] E/flutter (18792): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
[        ] E/flutter (18792): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
[        ] E/flutter (18792): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
[        ] E/flutter (18792): #18     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
[        ] E/flutter (18792): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
[        ] E/flutter (18792): #20     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4965:32)
[        ] E/flutter (18792): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
[        ] E/flutter (18792): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
[        ] E/flutter (18792): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
[        ] E/flutter (18792): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
[        ] E/flutter (18792): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
[        ] E/flutter (18792): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
[        ] E/flutter (18792): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
[        ] E/flutter (18792): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
[        ] E/flutter (18792): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
[        ] E/flutter (18792): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
[        ] E/flutter (18792): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
[        ] E/flutter (18792): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
[        ] E/flutter (18792): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
[        ] E/flutter (18792): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
[        ] E/flutter (18792): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
[        ] E/flutter (18792): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
[        ] E/flutter (18792): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
[        ] E/flutter (18792): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
[        ] E/flutter (18792): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
[        ] E/flutter (18792): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
[        ] E/flutter (18792): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
[        ] E/flutter (18792): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
[        ] E/flutter (18792): #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
[        ] E/flutter (18792): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
[        ] E/flutter (18792): #45     Element.updateChild (package:flutter/src/widgets/framewor
[+1846 ms] D/AndroidRuntime(18792): Shutting down VM
[   +2 ms] E/AndroidRuntime(18792): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(18792): Process: com.amolg.flutterpocapp, PID: 18792
[        ] E/AndroidRuntime(18792): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=513469796, result=-1,
data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.amolg.flutterpocapp/com.amolg.flutterpocapp.MainActivity}:
java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
[   +1 ms] E/AndroidRuntime(18792):     at android.app.ActivityThread.deliverResults(ActivityThread.java:4382)
[        ] E/AndroidRuntime(18792):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4426)
[        ] E/AndroidRuntime(18792):     at android.app.ActivityThread.-wrap20(Unknown Source:0)
[        ] E/AndroidRuntime(18792):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
[        ] E/AndroidRuntime(18792):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime(18792):     at android.os.Looper.loop(Looper.java:164)
[        ] E/AndroidRuntime(18792):     at android.app.ActivityThread.main(ActivityThread.java:6626)
[        ] E/AndroidRuntime(18792):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(18792):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[        ] E/AndroidRuntime(18792):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
[        ] E/AndroidRuntime(18792): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object
reference
[        ] E/AndroidRuntime(18792):     at io.flutter.plugins.camera.CameraPlugin$CameraRequestPermissionsListener.onRequestPermissionsResult(CameraPlugin.java:263)
[        ] E/AndroidRuntime(18792):     at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:191)
[        ] E/AndroidRuntime(18792):     at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:125)
[        ] E/AndroidRuntime(18792):     at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:133)
[        ] E/AndroidRuntime(18792):     at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7458)
[        ] E/AndroidRuntime(18792):     at android.app.Activity.dispatchActivityResult(Activity.java:7309)
[        ] E/AndroidRuntime(18792):     at android.app.ActivityThread.deliverResults(ActivityThread.java:4378)
[        ] E/AndroidRuntime(18792):     ... 9 more
```

**Comment by JoseGeorges8** [comment] 2019-12-09 17:02
Any updates on this? My app keeps on crashing the first time the user gets asked for permissions and allows them

**Comment by timsneath** [comment] 2020-01-03 19:05
Dupe of https://github.com/flutter/flutter/issues/22427

**Closed by timsneath** 2020-01-03 19:05 UTC
Labels: p: camera, p: first party, plugin, severe: crash, ▣ platform-android
