### ISSUE TITLE
Trackpad pinch zooming not working in macOS platform

### ISSUE THREAD

**Issue by praveeng2565** [flutter/flutter#78190] opened 2021-03-15 05:42 UTC
Hi,

In macOS, when I have tried to pinch-zoom my application using the trackpad, it didn't get zoomed in. I have checked it using the interactive viewer widget. When zoomed in, the interactive viewer didn't get updated.

<details>
  <summary>Code sample</summary>

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: InteractiveViewer(
        minScale: 0.1,
        maxScale: 5.0,
        child: Stack(
          children: [
            Positioned.fill(
                  child: FlutterLogo(style: FlutterLogoStyle.horizontal)),
          ],
        ),
      ),
    );
  }
```

</details>

Is there any way to resolve this?

Thanks in advance.

**Comment by stuartmorgan** [comment] 2021-03-15 10:35
Duplicate of https://github.com/flutter/flutter/issues/23604

**Closed by stuartmorgan** 2021-03-15 10:35 UTC
