### ISSUE TITLE
Mising description in "Write Your First Flutter App"

### ISSUE THREAD

**Issue by tintelle** [flutter/flutter#48236] opened 2020-01-06 11:11 UTC
In part "4. Use an external package", the const identifiers in Title and Body magically vanish with no explanations. One cannot add "child: Text(wordPair.asPascalCase)" into the body without removing the const before Body, as this throws errors. There should be a comment in the code to tell the user to remove the const before Body.

**Comment by VladyslavBondarenko** [comment] 2020-01-06 12:19
Hi @tintelle 
If I understood correctly, you mentioned this paragraph.
![image](https://user-images.githubusercontent.com/17024977/71817672-49830000-308f-11ea-9bcc-c7701e5bd789.png)
It is clear from code which lines should be added, which should be removed.
I close the issue
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by tintelle** [comment] 2020-01-06 12:22
Sorry, I should have been clearer: I'm not talking about the code in the repo, but the Codelab description. Here, the app is created using const identifiers:
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#2
One step later, the const's vanished without a comment, causing problems when not removing them:
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3

**Comment by VladyslavBondarenko** [comment] 2020-01-06 16:02
Ah, ok, my screenshot was from [this documentation](https://flutter.dev/docs/get-started/codelab). 
I was looking there (and there examples were without `const` in mentioned places).
But now I see what do you mean
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-01-16 15:44
Closing as duplicate of https://github.com/flutter/flutter/issues/48404
The current one is older, but less descriptive

**Closed by VladyslavBondarenko** 2020-01-16 15:44 UTC
Labels: d: codelabs, documentation, passed first triage
