### ISSUE TITLE
Flaky benchmark results for a variety of benches

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#34439] opened 2019-06-13 20:54 UTC
We have recently started seeing a swath of benchmarks frequently becoming red, but still green a majority of the time. A few examples include `hot_mode_dev_cycle_linux__benchmark hotReloadMillisecondsToFrame` and `microbenchmarks_ios stock_animation_close_first_frame_average` Please look at the benchmark dashboard as it impacts quite a few. It is not apparent when it started happening, but rather a more gradual shift to becoming flaky. The results were also muddied by real regressions happening in parallel during the same period.

I am marking this as TODAY, but feel free to remove the label if you think this is not a blocker, as the issue is rather vague anyways.

**Comment by tvolkert** [comment] 2019-06-14 00:54
Removing TODAY label, as I don't think it blocks a dev release.

**Comment by markusaksli-nc** [comment] 2020-08-05 10:36
There are still benchmarks like this in the [dashboard](https://flutter-dashboard.appspot.com/benchmarks.html)

**Comment by exaby73** [comment] 2022-11-28 13:47
I am not sure if this issue is still valid or not. @GaryQian could you help me understand this issue, and whether it should remain open or can be closed?

I am removing the `has reproducible label` since the link in https://github.com/flutter/flutter/issues/34439#issuecomment-669118569 doesn't seem to be working anymore.

**Comment by goderbauer** [comment] 2023-02-01 23:13
I am going to close this since a lot of work has happened to make benchmarks less flaky.

**Closed by goderbauer** 2023-02-01 23:13 UTC
Labels: framework, severe: performance, passed first triage, team: benchmark, found in release: 1.21
