### ISSUE TITLE
Passing a completed future in FutureBuilder does not produce initial snapshot with data

### ISSUE THREAD

**Issue by divillysausages** [flutter/flutter#118032] opened 2023-01-05 10:33 UTC
## Steps to Reproduce

This was originally reported in https://github.com/flutter/flutter/issues/22687, though was closed because the code example provided didn't show the error in question

1. Execute `flutter run` on the code sample
2. In the console, you can see that we still go through the `ConnectionState.waiting` phase even though the `Future` has already been resolved.

The example given is a simple one, but in my app in question, I have a `PageView.builder` that loads data from an API on every page. In order to provide a more seamless experience, I preload the next page's data. However, even though the data is there, there's still a single frame where the `Future` is "unresolved", which causes a flash in my UI and jank in my `PageView` scrolling.

**Expected results:** 

As the `Future` is already completed, the builder should go straight to the "resolved" section of the code.

**Actual results:** 

Even though the `Future` is already completed, there'll still be a one frame delay while the `snapshot.connectionState == ConnectionState.waiting`, which, depending on your UI, can result in a flash

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final testFuture = Future.value("Hello, world!");
    return FutureBuilder(
      future: testFuture,
      builder: (context, snapshot) {
        print("BUILDING OUR FUTURE BUILDER - has data: ${snapshot.hasData}");

        /// if we're loading,then show a progress indicator
        if (snapshot.connectionState == ConnectionState.waiting) {
          print("WAITING FOR FUTURE");
          return const CircularProgressIndicator();
        }
        
        // future is completed - show our value
        print("SHOWING OUR VALUE");
        return Text('${snapshot.data}');
      },
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
BUILDING OUR FUTURE BUILDER - has data: false
WAITING FOR FUTURE
BUILDING OUR FUTURE BUILDER - has data: true
SHOWING OUR VALUE
```

```
flutter doctor -v
[√] Flutter (Channel stable, 3.3.8, on Microsoft Windows [Version 10.0.19045.2364], locale en-GB)
    • Flutter version 3.3.8 on channel stable at C:\Users\d.connolly\Documents\Dev\flutter_windows_3.0.1-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (8 weeks ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4       
    • DevTools version 2.15.0   

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\d.connolly\Documents\Dev\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\d.connolly\Documents\Dev\AndroidSDK
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.70.0)
    • VS Code at C:\Users\d.connolly\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (4 available)
    • CPH2009 (mobile)  • b1c697fc • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows  • windows-x64    • Microsoft Windows [Version 10.0.19045.2364]
    • Chrome (web)      • chrome   • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge     • web-javascript • Microsoft Edge 107.0.1418.35

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

**Comment by exaby73** [comment] 2023-01-05 13:50
Hello @divillysausages. I cannot reproduce this issue. I changed the code to make the future an instance of the `State` class like so:

```dart
import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  final testFuture = Future.value("Hello, world!");

  MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: testFuture,
      builder: (context, snapshot) {
        print("BUILDING OUR FUTURE BUILDER - has data: ${snapshot.hasData}");

        /// if we're loading,then show a progress indicator
        if (snapshot.connectionState == ConnectionState.waiting) {
          print("WAITING FOR FUTURE");
          return const CircularProgressIndicator();
        }

        // future is completed - show our value
        print("SHOWING OUR VALUE");
        return Text('${snapshot.data}');
      },
    );
  }
}
```

Can you provide some more information about how to reproduce this? Maybe a screen recording as well?

**Comment by divillysausages** [comment] 2023-01-05 14:33
Hi @exaby73,

Thanks for looking into this.

If I run your edit in dartpad.dev, it shows the error (see attached image)
![dartpad](https://user-images.githubusercontent.com/179882/210803183-e752d8ad-9600-4ef6-baac-aff5bb977628.png)

I can only really show an image with the console output here, as a screen recording wouldn't pick up much (the error only happens for ~1 frame).

Can you confirm that you only see 2 console messages when you run the code example? When the bug is present, you should see 4 console messages

Thanks

**Comment by divillysausages** [comment] 2023-01-05 14:35
To be clear, the bug is that the `FutureBuilder.builder` method is run twice, though it should only run once, as the `Future` has already been resolved

**Comment by exaby73** [comment] 2023-01-06 07:13
This is working as expected. The `Future` has to be awaited, whether is done or not. During awaiting, you'd get a waiting state, which in your code is using a `CircularProgressIndicator`. There's not really a better way to do this unfortunately and that's just a limitation of the way `Future`s work and there isn't anything Flutter can really do there. You could pass `initialData` to the `FutureBuilder` so that you don't get a `waiting` state, but rather a `data` state immediately with the `initialData` on the first frame before the data in the `Future` is ready and the UI updates with that.

If you want to avoid the `waiting` state altogether, I suggest refactoring your code to await the `Future` and pass the data with constructor arguments or using a state management solution like riverpod for example.

But since this is working as expected, I am closing this issue. If you disagree, please comment with your reasoning, and I can reopen the issue. Thank you

**Closed by exaby73** 2023-01-06 07:13 UTC
Labels: in triage
