### ISSUE TITLE
`flutter run` stops at "Waiting for observatory port to be available ..."

### ISSUE THREAD

**Issue by smolck** [flutter/flutter#55128] opened 2020-04-19 01:15 UTC
## Steps to Reproduce

1. Have an android device connected and recognized by Flutter, in this case with an id of `LGH871af9c16d7`
2. `$ flutter create foo`
3. `$ cd foo`
4. `$ flutter run -v -d LGH871af9c16d7`

## Logs

```
$ flutter run -v -d LGH871af9c16d7
[   +9 ms] executing: [/home/smolck/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +26 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f35b673f2b7ea7800c97d9ec096153fcca6091f2
[        ] executing: [/home/smolck/flutter/] git describe --match *.*.* --first-parent --long --tags
[  +12 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.18.0-dev.5.0-82-gf35b673f2
[   +8 ms] executing: [/home/smolck/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/smolck/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +50 ms] executing: [/home/smolck/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +54 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +22 ms] executing: /home/smolck/Android/Sdk/platform-tools/adb devices -l
[  +48 ms] List of devices attached
           LGH871af9c16d7         device usb:1-2.4.3 product:lucye_att_us model:LG_H871 device:lucye transport_id:1
[  +10 ms] /home/smolck/Android/Sdk/platform-tools/adb -s LGH871af9c16d7 shell getprop
[  +83 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +158 ms] Generating /home/smolck/dev/dart/flutter-projects/foo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +27 ms] ro.hardware = lucye
[        ] ro.build.characteristics = default
[  +51 ms] Launching lib/main.dart on LG H871 in debug mode...
[   +9 ms] /home/smolck/flutter/bin/cache/dart-sdk/bin/dart /home/smolck/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/smolck/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.XDPGSY/app.dill --packages /home/smolck/dev/dart/flutter-projects/foo/.packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill
[  +13 ms] executing: /home/smolck/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/smolck/dev/dart/flutter-projects/foo/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +8 ms] Exit code 0 from: /home/smolck/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/smolck/dev/dart/flutter-projects/foo/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.foo" (Raw: "com.example.foo")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="foo" (Raw: "foo")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.foo.MainActivity" (Raw: "com.example.foo.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[  +10 ms] executing: /home/smolck/Android/Sdk/platform-tools/adb -s LGH871af9c16d7 shell -x logcat -v time -t 1
[ +113 ms] Exit code 0 from: /home/smolck/Android/Sdk/platform-tools/adb -s LGH871af9c16d7 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           04-18 20:09:48.535 V/WifiServerServiceExt( 1617): checkPollTimer Cnt= 0 rssi =-54 threshold=-100
[  +13 ms] <- compile package:foo/main.dart
[  +10 ms] executing: /home/smolck/Android/Sdk/platform-tools/adb version
[   +6 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as /home/smolck/Android/Sdk/platform-tools/adb
[   +2 ms] executing: /home/smolck/Android/Sdk/platform-tools/adb start-server
[   +5 ms] Building APK
[  +23 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from /home/smolck/dev/dart/flutter-projects/foo/android/gradlew.
[   +1 ms] /home/smolck/dev/dart/flutter-projects/foo/android/gradlew mode: 33261 rwxr-xr-x.
[  +11 ms] executing: /opt/android-studio/jre/bin/java -version
[  +97 ms] Exit code 0 from: /opt/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +7 ms] executing: [/home/smolck/dev/dart/flutter-projects/foo/android/] /home/smolck/dev/dart/flutter-projects/foo/android/gradlew -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=/home/smolck/dev/dart/flutter-projects/foo/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+3469 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +12 ms] executing: [/home/smolck/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] f35b673f2b7ea7800c97d9ec096153fcca6091f2
[        ] [        ] executing: [/home/smolck/flutter/] git describe --match *.*.* --first-parent --long --tags
[        ] [  +12 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] [        ] 1.18.0-dev.5.0-82-gf35b673f2
[        ] [   +9 ms] executing: [/home/smolck/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/smolck/flutter/] git ls-remote --get-url origin
[        ] [   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +65 ms] executing: [/home/smolck/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +45 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +10 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +11 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +10 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [ +109 ms] Initializing file store
[        ] [  +22 ms] Done initializing file store
[ +731 ms] [+1886 ms] Skipping target: kernel_snapshot
[  +99 ms] [ +175 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +200 ms] [ +202 ms] debug_android_application: Complete
[        ] [  +15 ms] Persisting file store
[  +99 ms] [   +9 ms] Done persisting file store
[        ] [   +7 ms] build succeeded.
[        ] [  +12 ms] "flutter assemble" took 2,472ms.
[ +200 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[  +97 ms] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +198 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[ +100 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +1 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[  +95 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[  +98 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[ +100 ms] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:signingConfigWriterDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[ +100 ms] > Task :app:packageDebug UP-TO-DATE
[ +196 ms] > Task :app:assembleDebug
[        ] BUILD SUCCESSFUL in 5s
[        ] 31 actionable tasks: 5 executed, 26 up-to-date
[ +341 ms] Running Gradle task 'assembleDebug'... (completed in 6.3s)
[ +201 ms] calculateSha: LocalDirectory: '/home/smolck/dev/dart/flutter-projects/foo/build/app/outputs/flutter-apk'/app.apk
[  +81 ms] calculateSha: reading file took 80us
[ +771 ms] calculateSha: computing sha took 770us
[   +2 ms] ✓ Built build/app/outputs/flutter-apk/app-debug.apk.
[   +4 ms] executing: /home/smolck/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/smolck/dev/dart/flutter-projects/foo/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +7 ms] Exit code 0 from: /home/smolck/Android/Sdk/build-tools/29.0.3/aapt dump xmltree /home/smolck/dev/dart/flutter-projects/foo/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.foo" (Raw: "com.example.foo")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="foo" (Raw: "foo")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.foo.MainActivity" (Raw: "com.example.foo.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=52)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw: "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=56)
                     E: action (line=57)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=59)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=66)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +1 ms] Stopping app 'app.apk' on LG H871.
[        ] executing: /home/smolck/Android/Sdk/platform-tools/adb -s LGH871af9c16d7 shell am force-stop com.example.foo
[ +155 ms] executing: /home/smolck/Android/Sdk/platform-tools/adb -s LGH871af9c16d7 shell pm list packages com.example.foo
[ +619 ms] package:com.example.foo
[   +7 ms] executing: /home/smolck/Android/Sdk/platform-tools/adb -s LGH871af9c16d7 shell cat /data/local/tmp/sky.com.example.foo.sha1
[  +40 ms] f0830cbb623c95025cb1e6b9ba1dc1e04b6b7af3
[   +1 ms] Latest build already installed.
[        ] LG H871 startApp
[   +5 ms] executing: /home/smolck/Android/Sdk/platform-tools/adb -s LGH871af9c16d7 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.foo/com.example.foo.MainActivity
[  +93 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.foo/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.18.0-6.0.pre.82, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-6.0.pre.82 at /home/smolck/flutter
    • Framework revision f35b673f2b (4 hours ago), 2020-04-19 02:45:01 +0530
    • Engine revision a5e0b2f2f2
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 5b19445d9c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/smolck/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/smolck/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is not installed
    • GNU Make 4.3

[✓] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[✓] Connected device (3 available)
    • LG H871    • LGH871af9c16d7 • android-arm64  • Android 8.0.0 (API 26)
    • Linux      • Linux          • linux-x64      • Linux
    • Web Server • web-server     • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

See also https://github.com/flutter/flutter/issues/54608#issuecomment-614275832.

**Comment by imeDevelopers** [comment] 2020-04-19 04:45
simply manually open your app and it will work fine .. , i think its in the adb.exe ..

**Comment by smolck** [comment] 2020-04-19 13:44
@imeDevelopers What do you mean by “manually open your app”?

**Comment by imeDevelopers** [comment] 2020-04-19 14:40
This message means that your app are compiled and installed on your device .. , flutter tried to open the app but something wrong happened in this stop .. so the command line are wait the app to be opened and will normally work .. so just open the app manually by press the app icon in your device and you can now see everything is normal ..

**Comment by smolck** [comment] 2020-04-19 14:43
Hmm, that’s interesting. But **the app does open on my device, hot-reload just doesn’t work** since it never gets past the “Waiting for observatory” part.

**Comment by imeDevelopers** [comment] 2020-04-20 03:42
Just run app using this command `flutter run --verbose` , and then try hot reload by press `r` letter and it should work ..

**Comment by smolck** [comment] 2020-04-20 03:51
That’s what I did, but Flutter hangs at `Waiting for observatory port to be available ...`, so no matter how many times I press `r` nothing happens: hot reload doesn’t work.

**Comment by iapicca** [comment] 2020-04-20 06:13
possibly related to https://github.com/flutter/flutter/issues/54876

**Comment by szotp** [comment] 2020-04-22 06:40
Can you run native app from Android Studio and see if any crashes happen? It something went wrong on start, then dart had no chance to connect.

**Comment by smolck** [comment] 2020-04-22 19:11
@szotp Sure! No crashes happened, same thing happens as with `flutter run`, where it hangs on `Installing build/app/outputs/flutter-apk/app.apk...` in the console. Here's the output:

```
Launching lib/main.dart on LG H871 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
```
Doesn't change after leaving it running for a while; just stays on the installing part.

Note that the app *does* load on the android device, (I can use it and everything, works fine) hot reload just never starts.

**Comment by szotp** [comment] 2020-04-22 19:29
@szotp Sure! No crashes happened, same thing happens as with `flutter run`, where it hangs on `Installing build/app/outputs/flutter-apk/app.apk...` in the console. 

That's now what I meant, you need to run the native app from android directory, it will have different, Android centered logs.

**Comment by smolck** [comment] 2020-04-22 19:39
Oh, my bad. How do I set that up from within android-studio?

**Comment by szotp** [comment] 2020-04-22 20:04
Just open the android folder in Android Studio, wait for gradle setup, and run.

**Comment by smolck** [comment] 2020-04-22 20:08
Okay, thanks! Did that, and no crashes. Builds were successful, and the app appeared on my device fine. If you want any logs let me know.

**Comment by smolck** [comment] 2020-05-08 13:13
@szotp Is there anything else I can do to debug this issue? I would really like to get it fixed, as being unable to run my app with hot reload on a physical device will make testing on other devices difficult and laborious (same probably goes for profiling too).

**Comment by smolck** [comment] 2020-05-08 13:30
I also tried the instructions (just without the `*:I` at the end) from https://github.com/flutter/flutter/issues/25455#issuecomment-483344294 and I got no output from the logcat process.

**Comment by smolck** [comment] 2020-05-08 17:37
Another note, this could be related to or a duplicate of #52636, seems like a similar (or the same) issue.

**Comment by imeDevelopers** [comment] 2020-05-11 11:44
@smolck
@iapicca 
Now i have the same problem .. , lol 😁

**Comment by smolck** [comment] 2020-05-11 11:49
@imeDevelopers I’ve actually found a (admittedly annoying) workaround, see my comment here:  https://github.com/flutter/flutter/issues/52636#issuecomment-626031880 

(Please let me know if that comment isn’t clear.)

**Comment by auleaf** [comment] 2020-05-30 15:03
I got the same problem !

**Comment by matheusabr** [comment] 2020-07-15 19:20
Try to change android app applicationId: https://stackoverflow.com/a/62922020/2636782

**Comment by smolck** [comment] 2020-07-18 01:03
@matheusabr Hmm, not sure if that's what did it, but the problem seems to be fixed in master channel; hot reload works now after an upgrade! Should I close the issue, or wait until others can confirm the issue is fixed?

**Comment by matheusabr** [comment] 2020-07-22 10:35
> @matheusabr Hmm, not sure if that's what did it, but the problem seems to be fixed in master channel; hot reload works now after an upgrade, even with the applicationId being the same! Should I close the issue, or wait until others can confirm the issue is fixed?

IDK, cause I can't reproduce that problem anymore after applicationId has been changed. Thank you for asking but it's up to you to close or not.

**Comment by liugangnhm** [comment] 2020-12-27 11:52
- flutter clean
- reboot device

Done!

**Comment by iapicca** [comment] 2020-12-27 11:54
@smolck 
are you still experiencing the issue?

tagging @TahaTesser  for visibility

**Comment by smolck** [comment] 2020-12-28 03:05
@iapicca Not last I checked, no, at least on Flutter for Desktop (not that mobile should be any different). Should I close this issue?

**Comment by TahaTesser** [comment] 2021-01-05 14:37
Hi @smolck
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-01-05 14:37 UTC
Labels: P4, found in release: 1.18, has reproducible steps, platform-android, tool

**Comment by brad007** [comment] 2021-01-29 08:24
Still experiencing this issue

**Comment by jaggzh** [comment] 2021-02-19 08:53
I'm experiencing it using android studio's included qemu in linux, debian, stable.
Flutter  1.24.0-10.2.pre
I can't even see any output showing the port(s) being used. I've also tried --dds-port=8888 --host-vmservice-port=8888 
(Nothing else is on that port... I don't actually desire to pick a port; these are just my attempts at getting it to work.)

`
[✓] Flutter (Channel unknown, 1.24.0-10.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-10.2.pre at /home/jaggz/projects/flutter/flutter
    • Framework revision 022b333a08 (3 months ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/jaggz/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/jaggz/Android/Sdk
    • Java binary at: /mnt/bigfs/home/jaggz/projects/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
    • cmake version 3.16.3
    • ninja version 1.8.2
    • pkg-config version 0.29

[✓] Android Studio
    • Android Studio at /mnt/bigfs/home/jaggz/projects/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /mnt/bigfs/home/jaggz/projects/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Linux (desktop)                       • linux         • linux-x64      • Linux
    • Web Server (web)                      • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
`

**Comment by iapicca** [comment] 2021-02-19 08:59
@jaggzh 
`Flutter 1.24.0-10.2.pre` ?
can you run 
```console
flutter channel beta
flutter upgrade -f
```
if the issue persist please open a new issue 
providing your updated `flutter doctor -v`, your `flutter run -v`
