### ISSUE TITLE
closeCaptureSession  Session 1: Exception while stopping repeating:

### ISSUE THREAD

**Issue by oscar02r** [flutter/flutter#97485] opened 2022-01-29 19:24 UTC
**I got this error in my app while I'm used  startImageStream** 

/Camera  ( 6455): open | onError
I/Camera  ( 6455): close
I/Camera  ( 6455): closeCaptureSession
E/CameraCaptureSession( 6455): Session 1: Exception while stopping repeating:
E/CameraCaptureSession( 6455): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession( 6455): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2023)
E/CameraCaptureSession( 6455): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:952)
E/CameraCaptureSession( 6455): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:395)
E/CameraCaptureSession( 6455): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1114)
E/CameraCaptureSession( 6455): 	at io.flutter.plugins.camera.Camera.close(Camera.java:1121)
E/CameraCaptureSession( 6455): 	at io.flutter.plugins.camera.Camera$1.onError(Camera.java:302)
E/CameraCaptureSession( 6455): 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks$1.run(CameraDeviceImpl.java:1684)
E/CameraCaptureSession( 6455): 	at android.os.Handler.handleCallback(Handler.java:751)
E/CameraCaptureSession( 6455): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/CameraCaptureSession( 6455): 	at android.os.Looper.loop(Looper.java:179)
E/CameraCaptureSession( 6455): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by maheshmnj** [comment] 2022-01-31 08:03
Hi @oscar02r, Thanks for filing the issue. Please share a minimal and complete reproducible code sample along with the output of `flutter doctor -v` and `flutter run -v`.
This is a duplicate of https://github.com/flutter/flutter/issues/94232 (closed)

Thanks

**Closed** 2022-02-21 08:10 UTC
Labels: waiting for customer response, in triage
