### ISSUE TITLE
Invalid tab title in Flutter Web on iOS 

### ISSUE THREAD

**Issue by syfulin** [flutter/flutter#68423] opened 2020-10-18 04:26 UTC
There is a problem with the page title in Flutter Web.

after setting the title parameter:
```
...
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My Title',
      theme: ThemeData(
...
```

The custom title is displayed correctly in the desktop version of the site:
![ok_desktop](https://user-images.githubusercontent.com/20333151/96358717-932b6b80-1134-11eb-810e-27c20076c51e.png)

But in mobile browsers, instead of the title, a string with the value "flutter" is displayed.

I tried to find the 'flutter' string in the compiled js code and replace it with another value:
![replace](https://user-images.githubusercontent.com/20333151/96358722-9e7e9700-1134-11eb-93a8-7238de4c7437.png)

Problem solved, but I don't think it is a good solution:
![comp](https://user-images.githubusercontent.com/20333151/96358724-a807ff00-1134-11eb-90d6-588704390251.png)

Examples:

1. Correct mobile title:
http://hhhhtyu.000webhostapp.com/test_title_2/

2. Invalid mobile title:
http://hhhhtyu.000webhostapp.com/test_title/

I also noticed that in the second example, /#/ is inserted at the end of the url.

Help me to understand

**Comment by sidrao2006** [comment] 2020-10-18 08:00
Hello @syfulin ,
Could you please post the output of `flutter doctor -v`

In Navigator 1.0, flutter creates a single page application and uses # to navigate between different pages
Thank you!

**Comment by syfulin** [comment] 2020-10-18 08:03
@sidrao2006 
![Безымянный](https://user-images.githubusercontent.com/20333151/96361797-0e9c1580-1153-11eb-80c8-51b083d0f746.png)

**Comment by syfulin** [comment] 2020-10-18 08:17
@sidrao2006 
Let me summarize my problem:

This is a standard project - a counter.

When you try to open it using a link like this:
http://hhhhtyu.000webhostapp.com/test_title/#/
Title displays correctly in Chrome Desktop and Chrome Mobile

When you try to open it using a link like this:
http://hhhhtyu.000webhostapp.com/test_title
Title displays correctly only Chrome Desktop.
In Chrome Mobile instead of the title, the string 'flutter' is displayed:
![photo_2020-10-18_15-16-20](https://user-images.githubusercontent.com/20333151/96362078-f5946400-1154-11eb-9e37-d1efd9ac9f93.jpg)

**Comment by sidrao2006** [comment] 2020-10-18 08:56
Hey @syfulin , for me both the links show test_title

**Comment by sidrao2006** [comment] 2020-10-18 08:58
![Screenshot_20201018-142735_Chrome.jpg](https://user-images.githubusercontent.com/66567899/96362858-19a07700-114e-11eb-8576-9bba5a14aa55.jpg)![Screenshot_20201018-142729_Chrome.jpg](https://user-images.githubusercontent.com/66567899/96362863-202eee80-114e-11eb-8a17-feedc45f901d.jpg)

**Comment by TahaTesser** [comment] 2020-10-19 12:00
hI @syfulin 
Testing on iOS and Android, results are different from following
> Placed another application at the root of the site. The problem is the same:
> http://hhhhtyu.000webhostapp.com/ title="flutter"
> http://hhhhtyu.000webhostapp.com/#/ title="Flutter Demo"

### Android
Opening http://hhhhtyu.000webhostapp.com/ on Chrome on Android adds `#/` to this link
This opens as it is  http://hhhhtyu.000webhostapp.com/#/ 
![Screenshot_2020-10-19-17-20-59-84](https://user-images.githubusercontent.com/48603081/96447888-390fd080-1230-11eb-9931-faf3a7ab6aeb.jpg)


### iOS

Opening http://hhhhtyu.000webhostapp.com/ on Chrome on IOS, it doesn't add  `#/` 
This opens as it is  http://hhhhtyu.000webhostapp.com/#/ 
![Image from iOS](https://user-images.githubusercontent.com/48603081/96447855-2e553b80-1230-11eb-81dd-74bf5d4ec1cb.png)

Are you experiencing this same behavior? The problem seems to rely on iOS since the same behavior as Android is on Desktop as well

**Comment by syfulin** [comment] 2020-10-19 14:30
@TahaTesser 

Thanks for the tests. 
I only tested on ios and windows.

I consider this problem to be critical, as the string value "flutter" can be confusing to users. I will think about how I can fix this problem from Flutter side. And I will write about it here.

**Comment by ferhatb** [comment] 2020-10-23 00:15
Duplicate of https://github.com/flutter/flutter/issues/53568
/cc @goderbauer , same issue we discussed

**Closed by ferhatb** 2020-10-23 00:15 UTC
Labels: a: quality, assigned for triage, f: routes, found in release: 1.23, framework, has reproducible steps, platform-ios, platform-web
