### ISSUE TITLE
Android App Crash when multiple VideoController instances exists even after dispose.

### ISSUE THREAD

**Issue by unoravi** [flutter/flutter#88955] opened 2021-08-26 13:01 UTC
I am facing app crash when multiple video instances are generated (approx 8-10 VideoController instances). After video usage complete, I have executed dispose() VideoController (used pause() if video is playing).

But still I faces an app crash due to multiple video controllers and heap memory issue. Please provide solution or proper way to handle this. Awaiting your quick solution.

Thanks

**Comment by unoravi** [comment] 2021-09-07 12:36
@darshankawar 
Android app crash logs is attached here with [Crash Logs.txt](https://github.com/flutter/flutter/files/7121533/Crash.Logs.txt)

Please have a look and let me know if any.

Thanks

**Comment by darshankawar** [comment] 2021-09-07 13:10
> `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any 3rd party plugins, that we can use to verify this issue ?

@unoravi 
We would also need above details so as to properly address this issue.

**Comment by unoravi** [comment] 2021-09-07 13:29
@darshankawar 
I am getting crash while playing videos only. Crash reason is Out of Memory as you can see in crash logs. So please check logs and have a look if you found something.

I am trying to replicate crash on sample code with short example but still not face crash on sample code. Once, I am able to replicate crash on sample code, I will surely share that.

Thanks

**Comment by darshankawar** [comment] 2021-09-08 06:17
@unoravi 
Yes I looked at the crash, but in order to make this issue actionable, we would also need a reproducible code sample that we can use to clearly verify it.
Thanks.

**Comment by unoravi** [comment] 2021-09-08 06:49
@darshankawar 
I am trying to replicate that issue and will surely share sample code in short time.

I think this crash is because of dispose video issue as shown here with SAMPLE CODE : https://github.com/flutter/flutter/issues/79546

Please have a look and provide solution on it.

Thanks

**Comment by darshankawar** [comment] 2021-09-08 07:28
@unoravi 
From the crash log, it fails due to below errors:

<details>
<summary>console error log</summary>



```
java.lang.OutOfMemoryError: Failed to allocate a 3664 byte allocation with 1064 free bytes and 1064B until OOM, target footprint      
201326592, growth limit 201326592
[        ] E/AndroidRuntime(10351):     at java.util.Arrays.copyOf(Arrays.java:3257)
[        ] E/AndroidRuntime(10351):     at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
[        ] E/AndroidRuntime(10351):     at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:541)
[        ] E/AndroidRuntime(10351):     at java.lang.StringBuilder.append(StringBuilder.java:176)
[        ] E/AndroidRuntime(10351):     at java.lang.String.replace(String.java:2381)
[        ] E/AndroidRuntime(10351):     at com.google.android.exoplayer2.util.Log.appendThrowableString(Log.java:176)
[        ] E/AndroidRuntime(10351):     at com.google.android.exoplayer2.util.Log.e(Log.java:138)
[        ] E/AndroidRuntime(10351):     at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onCodecError(MediaCodecVideoRenderer.java:705)
[        ] E/AndroidRuntime(10351):     at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:858)
[  +10 ms] E/AndroidRuntime(10351):     at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
[        ] E/AndroidRuntime(10351):     at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
[   +1 ms] E/AndroidRuntime(10351):     at android.os.Handler.dispatchMessage(Handler.java:103)
[        ] E/AndroidRuntime(10351):     at android.os.Looper.loop(Looper.java:237)
[        ] E/AndroidRuntime(10351):     at android.os.HandlerThread.run(HandlerThread.java:67)
[        ] E/LoadTask(10351): OutOfMemory error loading stream
[        ] E/LoadTask(10351):   java.lang.OutOfMemoryError: Failed to allocate a 8016 byte allocation with 2528 free bytes and 2528B until OOM, target footprint
201326592, growth limit 201326592
[        ] E/LoadTask(10351):       at com.google.android.exoplayer2.source.SampleQueue.<init>(SampleQueue.java:159)
[        ] E/LoadTask(10351):       at com.google.android.exoplayer2.source.SampleQueue.createWithDrm(SampleQueue.java:144)
[        ] E/LoadTask(10351):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.prepareTrackOutput(ProgressiveMediaPeriod.java:719)
[        ] E/LoadTask(10351):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod.track(ProgressiveMediaPeriod.java:682)
[        ] E/LoadTask(10351):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:507)
[        ] E/LoadTask(10351):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:443)
[  +12 ms] E/LoadTask(10351):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:425)
[        ] E/LoadTask(10351):       at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:244)
[        ] E/LoadTask(10351):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
[        ] E/LoadTask(10351):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1049)
[        ] E/LoadTask(10351):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
[        ] E/LoadTask(10351):

```


</details>

Which could happen if trying to play multiple videos at once as in your case. There could also be a case if the device RAM is on lower side and hence it cannot allocate the buffer writing and will need to make changes in buffer to try to handle such cases.

The issue you linked earlier is more of a documentation issue.

**Comment by unoravi** [comment] 2021-09-13 12:32
@darshankawar 
I am running my application on Samsung M30 with Android 10, 6 GB RAM. As per me this is enough memory for this case. I think this is the issue of Memory Management. Can you please share a way to release VideoController memory which is related to exoplayer ? 

- Issue Case : One video play for 15 mins and then start another and do the same with 5-6 different videos. This can cause issue and shows OutofMemory error with exoplayer issue.

Thanks

**Comment by darshankawar** [comment] 2021-09-14 07:13
@unoravi 
A sample code would be helpful to know more about and how you are disposing the VideoController.

**Comment by unoravi** [comment] 2021-09-17 05:09
@darshankawar 
I am facing an issue in my working module and working on to replicate the same with sample code. Once I am ready with it, I will quickly share it as I want the solution very quickly.

Here is the code that how I dispose VideoPlayerController object(controller).

```
try {
      if (controller.value.isPlaying) {
        await controller.pause();
      }
      await controller.dispose();
    } catch (e) {
    } finally {
      controller = null;
    }
```

Suggest me if I need to dispose it any other way or any issue in this.

**Comment by darshankawar** [comment] 2021-09-17 06:19
@unoravi 
See if [this](https://stackoverflow.com/a/58959097) SO solution helps. 



> I want the solution very quickly

Please be aware that we may not be able to give you a quick solution unless this is a genuine bug or gets prioritized, so you need to be patient.

**Comment by danagbemava-nc** [comment] 2021-10-13 08:48
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-10-13 08:48 UTC
