### ISSUE TITLE
Dart -> Engine roll is failing on failure in const_finder_test

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#78328] opened 2021-03-16 15:13 UTC
Starting with the roll here: https://github.com/flutter/engine/pull/25008

But not occurring on the roll here: https://github.com/flutter/engine/pull/25003 which failed for other reasons

```
Running command "/b/s/w/ir/cache/builder/src/out/host_debug_unopt/dart-sdk/bin/dart /b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/const_finder_test.dart /b/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/frontend_server.dart.snapshot /b/s/w/ir/cache/builder/src/out/host_debug_unopt/flutter_patched_sdk"
Generating kernel fixtures...
/b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/fixtures/lib/consts.dart
Checking recursive calls.
Checking for expected constants.
Checking for non-constant instances.
Expected: {"constantInstances":[{"stringValue":"1","intValue":1,"targetValue":null},{"stringValue":"10","intValue":10,"targetValue":null},{"stringValue":"6","intValue":6,"targetValue":null},{"stringValue":"7","intValue":7,"targetValue":null},{"stringValue":"8","intValue":8,"targetValue":null},{"stringValue":"9","intValue":9}],"nonConstantLocations":[{"file":"file:///b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/fixtures/lib/consts_and_non.dart","line":14,"column":26},{"file":"file:///b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/fixtures/lib/consts_and_non.dart","line":17,"column":41},{"file":"file:///b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/fixtures/lib/consts_and_non.dart","line":17,"column":26},{"file":"file:///b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/fixtures/lib/consts_and_non.dart","line":19,"column":26},{"file":"file:///b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/fixtures/pkg/package.dart","line":14,"column":25}]}
Actual:   {"constantInstances":[{"stringValue":"1","intValue":1,"targetValue":null},{"stringValue":"10","intValue":10,"targetValue":null},{"stringValue":"6","intValue":6,"targetValue":null},{"stringValue":"7","intValue":7,"targetValue":null},{"stringValue":"8","intValue":8,"targetValue":null},{"stringValue":"9","intValue":9}],"nonConstantLocations":[{"file":"file:///b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/fixtures/lib/consts_and_non.dart","line":14,"column":26},{"file":"file:///b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/fixtures/lib/consts_and_non.dart","line":17,"column":26},{"file":"file:///b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/fixtures/lib/consts_and_non.dart","line":19,"column":26},{"file":"file:///b/s/w/ir/cache/builder/src/flutter/tools/const_finder/test/fixtures/pkg/package.dart","line":14,"column":25}]}
Tests failed - exit code: -1
```

/cc @dnfield @a-siva

**Comment by aam** [comment] 2021-03-16 16:06
@alexmarkov https://dart.googlesource.com/sdk/+/daae24b488023bbcf2f5a353fa29b084ba16b6c7 seems to be the culprit for failing const_finder_test.

**Comment by a-siva** [comment] 2021-03-16 16:16
Should we revert that CL or do you have a forward fix?

**Comment by aam** [comment] 2021-03-16 16:17
I don't think that cl can be reverted as it fixed different regression.

**Comment by aam** [comment] 2021-03-16 16:19
Original regression was https://github.com/dart-lang/sdk/commit/2d63f26ef5a4170ff1d6035d5388824788fd30d8, it could not have been cleanly reverted, so two follow-up fixes landed yesterday: https://dart.googlesource.com/sdk/+/daae24b488023bbcf2f5a353fa29b084ba16b6c7 and https://dart.googlesource.com/sdk/+/e8f57b66058287fb5243928341f1dde517dc249a. And the first follow-up fix caused new regression.

**Comment by mkustermann** [comment] 2021-03-16 16:27
@aam Maybe this just needs an update to the expectation file?

**Comment by aam** [comment] 2021-03-16 16:33
@mkustermann the expectations looks correct.
New actual results seems to be missing one non-const at {"file":"file:///usr/local/google/home/aam/p/f/flutter/engine/src/flutter/tools/const_finder/test/fixtures/lib/consts_and_non.dart","line":17,"column":41}

line 17: `  final Target target3 = Target('3', 3, Target('5', 5, null)); // should be tree shaken out.`

**Comment by alexmarkov** [comment] 2021-03-16 17:13
The line

```dart
  final Target target3 = Target('3', 3, Target('5', 5, null)); // should be tree shaken out.
```

has 2 constructor invocations.

When const_finder visits ConstructorInvocation nodes in kernel AST, it doesn't go deeper if class matches and non-constant instance is found:

https://github.com/flutter/engine/blob/2ab18532859ca9ba7f3fa13479dd1bb03f3d9435/tools/const_finder/lib/const_finder.dart#L66-L77

It means that the 2nd ConstructorInvocation at the same line will not be visited if it is not hosted out of the 1st ConstructorInvocation. Tree shaker might or might not do that hoisting depending on various factors. So, I think it is correct to update the expectations for this test.

@dnfield @zanderso Longer term I think we should fix const_finder to visit children nodes even if the matching ConstructorInvocation node is found, otherwise we cannot guarantee that it finds all constant and non-constant nodes.

**Comment by alexmarkov** [comment] 2021-03-16 21:26
@aam found that the issue is not fully fixed with https://github.com/flutter/engine/pull/25020: now all expectations appear in the test, but in a different order.

We still need to update expectations. Also, it would be useful to sort `nonConstantLocations` in the test to make it less fragile.

**Comment by aam** [comment] 2021-03-16 22:39
https://github.com/flutter/engine/pull/25022 manual roll landed with updated expectations.

**Closed by aam** 2021-03-16 22:39 UTC
Labels: P0, dependency: dart
