### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for null.

### ISSUE THREAD

**Issue by MinhCuongIT** [flutter/flutter#58742] opened 2020-06-05 01:49 UTC
## Command
```
flutter run --machine --target lib\main.dart -d emulator-5554 --track-widget-creation --start-paused
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for null.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:68:30)
#2      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:313:59)
#3      AndroidDevice._checkForSupportedAndroidVersion (package:flutter_tools/src/android/android_device.dart:303:26)
#4      AndroidDevice.uninstallApp (package:flutter_tools/src/android/android_device.dart:414:16)
<asynchronous suspension>
#5      AndroidDevice._installLatestApp (package:flutter_tools/src/android/android_device.dart:452:20)
#6      _rootRunUnary (dart:async/zone.dart:1192:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#14     AndroidDevice.installApp (package:flutter_tools/src/android/android_device.dart)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
```
```
[✓] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.17.2 at C:\flutter
    • Framework revision 5f21edf8b6 (7 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\CuongTran\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\CuongTran\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 0b8abb4724aa590dd0f429683339b1e045a1594d
### Plugins
cloud_firestore-0.13.5
cloud_firestore_web-0.1.1+2
firebase_auth-0.15.5+3
firebase_auth_web-0.1.3+1
firebase_core-0.4.4
firebase_core_web-0.1.1+2
firebase_messaging-6.0.15
flutter_image_compress-0.6.7
flutter_local_notifications-1.4.3
flutter_plugin_android_lifecycle-1.0.8
google_sign_in-4.4.0
google_sign_in_web-0.8.4
image_picker-0.6.3+4
path_provider-1.6.5
path_provider_macos-0.0.4+3
sqflite-1.3.0+2
url_launcher-5.4.2
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.1+6

**Comment by zanderso** [comment] 2020-06-09 21:19
Duplicate of https://github.com/flutter/flutter/issues/58534

**Closed by zanderso** 2020-06-09 21:19 UTC
Labels: P4, severe: crash, tool
