### ISSUE TITLE
[tool] APK's built with `flutter run --release` differ in size from `flutter build apk --release`

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#96650] opened 2022-01-14 08:49 UTC
## Steps to Reproduce

1. Create a new Flutter app: `flutter create myapp`
2. Connect an Android device (I used a physical device, not sure if it reproduces with an emulator)
3. Run `flutter run --release` with should build an APK and instal it as well
4. Terminate the app on the device
5. Run `flutter build apk --release`
6. Observe that for both APKs the size is different

**Expected results:** 
The APKs both have the same size.

**Actual results:** 
Both APK's have a different size.
`flutter run --release` has 5.9MB
`flutter build apk --release` has 15.5MB

I could install both APK's on my device.
I had reports of people not being able to install the APK that was generated by `flutter run --release`.
Does the size difference have anything to do with the Split Per ABI?
The application that I originally encountered the issue with,
had a size of around 86 MB for `flutter run --release` and around 116 MB for `flutter build apk --release`.
Does `flutter run --release` split the application per ABI before installing it on the connected device?
Or does it install a fat APK anyway, unless specified by the split per ABI flag?

So either it was my own fault, or there really is a bug somewhere.

**Logs**
```
navaronbracke@MacBook-Pro-van-Navaron Desktop % flutter create myapp
Signing iOS app for device deployment using developer identity: "XXXXX"
Creating project myapp...
  myapp/test/widget_test.dart (created)
  myapp/pubspec.yaml (created)
  myapp/README.md (created)
  myapp/lib/main.dart (created)
  myapp/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  myapp/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  myapp/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  myapp/ios/Runner/Info.plist (created)
  myapp/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  myapp/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  myapp/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  myapp/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  myapp/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  myapp/ios/Runner/Base.lproj/Main.storyboard (created)
  myapp/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  myapp/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  myapp/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  myapp/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  myapp/ios/Flutter/Debug.xcconfig (created)
  myapp/ios/Flutter/Release.xcconfig (created)
  myapp/ios/Flutter/AppFrameworkInfo.plist (created)
  myapp/ios/.gitignore (created)
  myapp/myapp.iml (created)
  myapp/.gitignore (created)
  myapp/web/favicon.png (created)
  myapp/web/index.html (created)
  myapp/web/manifest.json (created)
  myapp/web/icons/Icon-maskable-512.png (created)
  myapp/web/icons/Icon-192.png (created)
  myapp/web/icons/Icon-maskable-192.png (created)
  myapp/web/icons/Icon-512.png (created)
  myapp/.metadata (created)
  myapp/android/app/src/profile/AndroidManifest.xml (created)
  myapp/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  myapp/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  myapp/android/app/src/main/res/drawable/launch_background.xml (created)
  myapp/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  myapp/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  myapp/android/app/src/main/res/values-night/styles.xml (created)
  myapp/android/app/src/main/res/values/styles.xml (created)
  myapp/android/app/src/main/res/drawable-v21/launch_background.xml (created)
  myapp/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  myapp/android/app/src/main/AndroidManifest.xml (created)
  myapp/android/app/src/debug/AndroidManifest.xml (created)
  myapp/android/gradle/wrapper/gradle-wrapper.properties (created)
  myapp/android/gradle.properties (created)
  myapp/android/.gitignore (created)
  myapp/android/settings.gradle (created)
  myapp/android/app/build.gradle (created)
  myapp/android/app/src/main/kotlin/com/example/myapp/MainActivity.kt (created)
  myapp/android/build.gradle (created)
  myapp/android/myapp_android.iml (created)
  myapp/ios/Runner/Runner-Bridging-Header.h (created)
  myapp/ios/Runner/AppDelegate.swift (created)
  myapp/ios/Runner.xcodeproj/project.pbxproj (created)
  myapp/analysis_options.yaml (created)
  myapp/.idea/runConfigurations/main_dart.xml (created)
  myapp/.idea/libraries/Dart_SDK.xml (created)
  myapp/.idea/libraries/KotlinJavaRuntime.xml (created)
  myapp/.idea/modules.xml (created)
  myapp/.idea/workspace.xml (created)
Running "flutter pub get" in myapp...                            1,509ms
Wrote 81 files.

All done!
In order to run your application, type:

  $ cd myapp
  $ flutter run

Your application code is in myapp/lib/main.dart.

navaronbracke@MacBook-Pro-van-Navaron Desktop % cd myapp
navaronbracke@MacBook-Pro-van-Navaron myapp % flutter run --release
Launching lib/main.dart on motorola one in release mode...
Running Gradle task 'assembleRelease'...                           27.4s
✓  Built build/app/outputs/flutter-apk/app-release.apk (5.9MB).
Installing build/app/outputs/flutter-apk/app.apk...                 5.5s

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).

Application finished.
navaronbracke@MacBook-Pro-van-Navaron myapp % flutter build apk --release

💪 Building with sound null safety 💪

Running Gradle task 'assembleRelease'...                           25.5s
✓  Built build/app/outputs/flutter-apk/app-release.apk (15.5MB).
```

**Doctor output**
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale
    en-BE)
    • Flutter version 2.8.1 at /Users/navaronbracke/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/navaronbracke/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/navaronbracke/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • motorola one (mobile) • ZL5228NFL7 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome     • web-javascript • Google Chrome
      97.0.4692.71

• No issues found!
```

**Comment by maheshmnj** [comment] 2022-01-14 12:16
Hi @navaronbracke, Thanks for filing the issue. I would say this is working as intended.

`flutter run --release` compiles only for a target abi.  while,

 `flutter build apk --release` results in a fat APK (Universal apk) that contains your code compiled for all the target ABIs, as a result, you could install this apk on any device.Flutter app can be compiled for `armeabi-v7a (ARM 32-bit)`,`arm64-v8a (ARM 64-bit)`, and `x86-64 (x86 64-bit)`. 
 
 I would recommend taking a look at
 
 https://developer.android.com/ndk/guides/abis
 https://docs.flutter.dev/deployment/android#what-is-a-fat-apk
 
 Closing as this is working as intended. If you disagree feel free to write in the comments and I will reopen it.
 
 Thank you.

**Closed by maheshmnj** 2022-01-14 12:16 UTC
Labels: in triage

**Comment by adrianjagielak** [comment] 2022-01-14 12:24
@navaronbracke you could compile your app with `flutter build apk --split-per-abi` command if you know your target abi and want smaller apk. Ideally you would use `flutter build appbundle` if releasing to the Play Store if you want the smallest size possible for given device.
