### ISSUE TITLE
Getting error when adding Authorization header in http client

### ISSUE THREAD

**Issue by aubykhan** [flutter/flutter#12453] opened 2017-10-08 05:04 UTC
I'm getting this error when I try to add `Authorization` header (`Bearer` token).
![image](https://user-images.githubusercontent.com/1756496/31314022-be7f902e-ac0e-11e7-92ed-fca14fcc2487.png)

I'm adding headers like this (the call I'm using is `post`):
![image](https://user-images.githubusercontent.com/1756496/31314052-774c9fac-ac0f-11e7-9104-a9a3b1b4f011.png)

If don't add the `Authorization` key in `headers` collection, the exception goes away. 

Need urgent help on this.

**Comment by Hixie** [comment] 2017-10-08 05:20
HttpClient is part of the dart:io API, so I recommend approaching the Dart SDK folks (or posting on StackOverflow with a Dart question, or both). See https://github.com/dart-lang/sdk/issues

**Comment by Hixie** [comment] 2018-05-21 18:42
Closing as dupe of dart/sdk issue.

**Closed by Hixie** 2018-05-21 18:42 UTC

**Comment by NemOry** [comment] 2019-01-10 10:02
Im having the same issue

**Comment by zoechi** [comment] 2019-01-10 10:11
@NemOry as mentioned above it's not Flutter related. 
https://github.com/dart-lang/sdk/issues/31105
