### ISSUE TITLE
[webview_flutter] Very glitchy launch on iOS

### ISSUE THREAD

**Issue by lukepighetti** [flutter/flutter#27561] opened 2019-02-05 20:09 UTC
After adding `webview_flutter` I get these gnarly glitchy graphics on iOS. Not yet tested on Android.

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.2.0, on Mac OS X 10.13.6 17G4015, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)

• No issues found!
```

![glitchy](https://user-images.githubusercontent.com/666539/52301253-02a8f980-2958-11e9-86aa-5e607c12bf04.gif)

**Comment by mcplectrum** [comment] 2019-02-05 20:35
As the UI works fine after the glitch at the beginning, it looks like you block the UI thread for too long, probably doing some lengthy network request.
Please have a look at https://docs.flutter.io/flutter/foundation/compute.html, which you can use to perform the lengthy non-UI operation.
There is also an excellent article about that topic from Kartik Sharma https://blog.usejournal.com/flutter-async-beginner-friendly-guide-for-heavy-lifting-operations-cf8ec81833d7 , who was inspired by this issue https://github.com/flutter/flutter/issues/18999 to write the article.

**Comment by lukepighetti** [comment] 2019-02-05 20:49
This issue did not happen until after adding `webview_flutter` and the associated `info.plist` entry

**Comment by mcplectrum** [comment] 2019-02-05 21:55
Can you please provide an minimal example?

**Comment by lukepighetti** [comment] 2019-02-05 23:02
I can provide the private repo which is not minimal to a Google employee for review if it is requested. I know this is not ideal but it is what is available at the moment.

**Comment by lukepighetti** [comment] 2019-02-06 01:17
I have just confirmed that this occurs when you add this line to `info.plist`

```
	<key>io.flutter.embedded_views_preview</key>
	<string>YES</string>
```

This is not related to the `webview_flutter` package.

**Comment by zoechi** [comment] 2019-02-13 17:57
#21403 looks similar

**Comment by focux** [comment] 2019-02-17 18:56
> io.flutter.embedded_views_preview<

I have the same bug and I can confirm it's happening because of that. I removed that from my `info.plist` and now it's working fine. Anyways, in order to implement Google Maps, we need to add that key. Is there a workaround for this?

**Comment by amirh** [comment] 2019-03-03 03:45
@focux your saying you see this by just setting the embedded_views_preview (without including any platform view in the app) on dev but not on stable? did you also try master?

How easy is it to reproduce? does it happen every time you start the app?
Which device are you seeing this on?

**Comment by lukepighetti** [comment] 2019-03-03 13:46
If you create a new project (on v1.2.0 anyway) and add this line

```
	<key>io.flutter.embedded_views_preview</key>
	<string>YES</string>
```

And launch iOS you will get the glitch. Every time. That's all there is to it.

**Comment by amirh** [comment] 2019-03-04 19:11
@lukepighetti which device are you using? can you share the output of `flutter doctor -v`?
I cannot reproduce the glitch on an iPhone 6S at least...
I'm trying with the default app template `flutter create` generates (and the embedded views flag set to YES).
Do you get the glitch for the default `flutter create` app as well when setting the embedded views preview flag?

**Comment by amirh** [comment] 2019-03-04 19:31
Ok got a repro! (by running flutter gallery).
Good news is that the issue wasn't there at v1.0.0 so we should be able to bisect the range and find where the regression started.

**Comment by amirh** [comment] 2019-03-04 20:30
The regression started at https://github.com/flutter/flutter/pull/26596 (engine roll), I'm continuing to bisect engine commits.

**Comment by amirh** [comment] 2019-03-04 21:16
The regression started with https://github.com/flutter/engine/pull/7272
@dnfield can you take a look?

It reproduces consistently when running the flutter gallery with the embedded views preview flag on iOS with GL rendering.
The only effect the flag has in this case is running the engine with a single thread(as flutter gallery isn't using platform views).

**Comment by dnfield** [comment] 2019-03-04 21:21
I had this on my list to get to - will take a look.  I strongly suspected it would be related to that CL, sorry we didn't get to catch up before you bisected

**Comment by mattkj** [comment] 2019-03-04 21:24
I hope this can be fixed quickly as it is negatively affecting our app as well. App looks very broken to end users.

We've been able to reproduce it every time on several different physical iPhones. However it is not reproduce-able in the simulator.

`<key>io.flutter.embedded_views_preview</key>
	<string>YES</string>`

is the cause. As soon as I remove that, the issue goes away.

**Comment by lukepighetti** [comment] 2019-03-05 01:23
I am on an iPhone 8+ on iOS 12.

**Comment by dnfield** [comment] 2019-03-05 08:13
We're going to work as quickly as possible to identify and fix the cause of this.

With that said, the feature is experimental. If you do not absolutely need it to enable critical functionality for your app, it should not be turned on.

**Comment by mattkj** [comment] 2019-03-05 17:40
Thank you @dnfield. Much appreciated.

**Comment by dnfield** [comment] 2019-03-06 18:09
https://github.com/flutter/engine/pull/8045 should improve this.  There's still some underlying issue about why this doesn't work when the threads are merged that needs to be looked into.

**Comment by nelsonrosa3** [comment] 2019-03-14 18:41
Having the same issue here. When i remove <key>io.flutter.embedded_views_preview</key> <string>YES</string>, the issue is gone. But i also needed for google maps.

Any solutions yet?

**Comment by focux** [comment] 2019-03-15 00:05
@dnfield So the fix should be already in the dev channel?

**Comment by xiaojia21190** [comment] 2019-03-15 05:36
now fix this bug?

**Comment by faverolles** [comment] 2019-03-23 19:23
I am experiencing a graphical glitch when a device's orientation changes. I'm pretty sure this issue is what I am seeing. My app depends on ```webview_flutter```, so I'm using the master channel for its most recent improvements. I have a gif of the glitch, and have written a short test app that can reproduce the bug, both of which I would be more than happy to post.

**Comment by lukepighetti** [comment] 2019-03-23 21:18
Post away!

**Comment by faverolles** [comment] 2019-03-23 21:56
### **Rotating iOS Emulator and Physical Device**
![BugApp](https://user-images.githubusercontent.com/48035185/54871846-dbcc4880-4d88-11e9-9cab-44c38d45588c.gif)
### **Flutter Doctor -v**
This was taken on my Windows machine while testing the app in Android. My Mac has the exact same set up as posted below. The bug does not occur in Android.
```
[√] Flutter (Channel master, v1.3.14-pre.64, on Microsoft Windows [Version
    10.0.17134.648], locale en-US)
    • Flutter version 1.3.14-pre.64 at D:\Programs\Flutter\flutter
    • Framework revision 2e637d8303 (4 hours ago), 2019-03-23 13:20:41 -0400
    • Engine revision 9f878fcb3e
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Programs\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Programs\AndroidSDK
    • Java binary at: D:\Programs\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Programs\AndroidStudio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\Programs\JetBrains\IntelliJ\IntelliJ IDEA 2018.1.3
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

```
### **Test App**
```Dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: BasePage(),
    );
  }
}

class BasePage extends StatefulWidget {
  BasePage({Key key}) : super(key: key);

  @override
  _BasePageState createState() => _BasePageState();
}

class _BasePageState extends State<BasePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Bug App")),
      body: Flex(
        direction: Axis.vertical,
        children: <Widget>[
          Expanded(
            flex: 1,
            child: Center(
              child: Text("Demo Rotation Bug",
                textScaleFactor: 3.0,
                textAlign: TextAlign.center
              ),
            ),
          ),
          Expanded(
            flex: 1,
            child: Center(
              child: RaisedButton(
                textColor: Colors.blue,
                child: Text("Show Bug Page"),
                onPressed: () => Navigator.push(context,
                  MaterialPageRoute(builder: (context) => BugPage()),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class BugPage extends StatefulWidget {
  BugPage({Key key}) : super(key: key);

  @override
  _BugPageState createState() => _BugPageState();
}

class _BugPageState extends State<BugPage> {

  /*
  I commented this out, as it seemed to have no affect on the glitch.
  The web views always load fine without the keys, after the
    most recent updates to webview_flutter and the master channel.
  Swiping has been fixed and works in iOS just as it does in Android.
  */
  //static final _keys = List<GlobalKey>.generate(3, (_) => GlobalKey());

  List<WebTest> _tabPages = {
    0:"https://www.google.com/",
    1:"https://flutter.dev/",
    2:"https://github.com/flutter"
  }.entries.map((p) =>
    WebTest(path: p.value, /*webKey: _keys[p.key]*/)).toList();

  @override
  Widget build(BuildContext context) {
    return OrientationBuilder(
      builder: (ctx, orientation) {
        return DefaultTabController(
          length: 3,
          child: Scaffold(
            appBar: AppBar(
              title: Image.asset("assets/img/logo.jpg",
                fit: BoxFit.contain, gaplessPlayback: true,),
              centerTitle: true,
              titleSpacing: 0.0,
              bottom: PreferredSize(
                preferredSize: const Size.fromHeight(kToolbarHeight * 2.0),
                child: ConstrainedBox(
                  constraints: BoxConstraints(maxHeight: kToolbarHeight * 2.0),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: <Widget>[
                      Expanded(
                        child: Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: FittedBox(
                            fit: BoxFit.contain,
                            child: Text("Customer Wants Long Auto Size Text Here",
                              softWrap: false,
                              textAlign: TextAlign.center,
                              style: Theme.of(context).primaryTextTheme.title,
                            ),
                          ),
                        ),
                      ),
                      Expanded(
                        child: TabBar(
                          indicatorColor: Colors.black,
                          isScrollable: orientation == Orientation.portrait,
                          tabs: ["img1", "img2", "img3"].map((p) =>
                            Tab(icon: Image.asset("assets/img/" + p + ".jpg",
                               fit: BoxFit.contain, gaplessPlayback: true))).toList(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
            body: TabBarView(children: this._tabPages),
          ),
        );
      }
    );
  }
}

class WebTest extends StatefulWidget {
  WebTest({Key key, this.path, this.webKey}) : super(key: key);

  final GlobalKey webKey;
  final String path;

  final Set<Factory<OneSequenceGestureRecognizer>> _gSet = Set()..addAll([
    Factory<VerticalDragGestureRecognizer>(
        () => VerticalDragGestureRecognizer()),
    Factory<ScaleGestureRecognizer>(
        () => ScaleGestureRecognizer()),
    Factory<PanGestureRecognizer>(
        () => PanGestureRecognizer()),
  ]);

  @override
  _WebTestState createState() => _WebTestState();
}

class _WebTestState extends State<WebTest>
  with AutomaticKeepAliveClientMixin<WebTest> {

  @override
  bool get wantKeepAlive => true;

  @override
  Widget build(BuildContext context) {
    return WebView(
//      key: widget.webKey,
      gestureRecognizers: widget._gSet,
      javascriptMode: JavascriptMode.unrestricted,
      initialUrl: widget.path
    );
  }
}
```
I hope someone can point out a simple mistake that I have made, which upon correcting, would fix the issue.  Although, do to the fact that the same code does not produce the glitch in Android, I think what I am seeing might be related to this iOS bug.

**Comment by amirh** [comment] 2019-03-28 18:27
@faverolles this looks like a different issue from the one discussed in this thread, would you mind starting a new issue and moving the relevant comments there?

**Comment by liyuqian** [comment] 2019-04-08 18:32
FWIW, the glitch screenshot looks similar to those in https://github.com/flutter/flutter/issues/28227 and https://github.com/flutter/flutter/issues/28484

**Comment by suzhenghao** [comment] 2019-06-28 08:01
did this problem solved ?

**Comment by darkmarthur** [comment] 2019-07-02 07:06
Same here

**Comment by liyuqian** [comment] 2019-07-02 23:59
As both https://github.com/flutter/flutter/issues/28227 and https://github.com/flutter/flutter/issues/28484 have been fixed, can you please try if it's still broken using the master channel of Flutter?

**Comment by liyuqian** [comment] 2019-09-30 23:04
Is this fixed or not?

**Comment by iapicca** [comment] 2019-11-06 16:01
Hi @lukepighetti 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/21403)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2019-11-06 16:01 UTC
Labels: a: platform-views, engine, p: first party, p: webview, plugin, severe: performance, severe: rendering, waiting for customer response, ⌺‬ platform-ios
