### ISSUE TITLE
Populate dart_entrypoint_args on Linux?

### ISSUE THREAD

**Issue by mikemaksymowych** [flutter/flutter#51599] opened 2020-02-27 23:12 UTC
I'd like to pass command line args (linux desktop app) to Flutter's `main(List<String> args)`. It seems like it should be possible, but the args are dropped along the way.

It looks like the engine's `Settings` struct has a field for these, `dart_entrypoint_args`, but that field is ignored when creating the Settings in embedder.cc.

Relevant code snippet from embedder.cc:
```
  fml::CommandLine command_line;
  if (SAFE_ACCESS(args, command_line_argc, 0) != 0 &&
      SAFE_ACCESS(args, command_line_argv, nullptr) != nullptr) {
    command_line = fml::CommandLineFromArgcArgv(
        SAFE_ACCESS(args, command_line_argc, 0),
        SAFE_ACCESS(args, command_line_argv, nullptr));
  }

  flutter::Settings settings = flutter::SettingsFromCommandLine(command_line);
```

Is my interpretation correct?

**Comment by mikemaksymowych** [comment] 2020-02-27 23:36
Actually, I've now confirmed that this works/is possible, at least in theory, by populating the struct field.

**Comment by stuartmorgan** [comment] 2020-02-28 04:55
Duplicate of #32986

**Closed by stuartmorgan** 2020-02-28 04:55 UTC
