### ISSUE TITLE
[webview_flutter] Redirect URI on iOS

### ISSUE THREAD

**Issue by eserna86** [flutter/flutter#67073] opened 2020-10-01 18:30 UTC
I am using webview_flutter to do Azure AD authentication. It works fine on Android however when testing it on iOS the webview does not redirect and therefore cannot receive the token. If a bad password is entered it will tell you but when login is successful the loading dots show at the top of the device and just hangs there. Not sure if there is some special iOS setting or permissions I need to also implement to get this to work. Any help would be appreciated.

**Comment by darshankawar** [comment] 2020-10-02 08:40
@eserna86 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample including iOS version you are on.
Thanks.

**Comment by eserna86** [comment] 2020-10-02 17:26
iOS 14.0.1

[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.4 at /Users/administrator/Documents/flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/administrator/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • BE89EEE7-9F2C-4734-8A9A-9263877691C0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

**Comment by darshankawar** [comment] 2020-10-05 05:58
@eserna86 
Please upgrade to latest Stable (1.22.0) along with latest `webview_flutter`. There have been updates made to latest plugin for iOS 14. See if after upgrading and running, solves your issue.
Thanks.

**Comment by eserna86** [comment] 2020-10-06 15:47
I have upgraded to Stable 1.22.0 and webview_flutter 1.0.0 but same issue is happening.

**Comment by darshankawar** [comment] 2020-10-07 06:22
@eserna86 
Please provide complete code that we can readily copy paste and run in IDE. I am getting compile errors on code sample:

`final User data;`

**Comment by eserna86** [comment] 2020-10-07 15:06
`import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

//I cannot share this link for security purposes.
final _initialUrl = "This is my Azure AD authentication endpoint";


void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Webview Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Webview Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);


  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  static WebViewController _webViewController;

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      //Builder is wrapped around the webview to allow SnackBar to access the build context of the scaffold.
      // Without this the context would be from AuthLogin which does not contain a scaffold.
      body: Builder(builder: (context) =>
          WebView(
            onWebViewCreated: (WebViewController c) {
              _webViewController = c;
            },
            initialUrl: _initialUrl,
            onPageFinished: _getAuthCode,
            javascriptMode: JavascriptMode.unrestricted,
          ),
      ),
    );
  }

  Future<void> _getAuthCode(String value) async {

    // Wait for the web view to redirect after successful authentication then parse the code from the redirect url.
    // It then uses the code from the previous step to POST to the token endpoint.
    //Check that the web view has loaded the page before continuing
    if (_webViewController != null) {
      value = await _webViewController.currentUrl();
      Uri response = Uri.dataFromString(value);
      print(response.path);
      //Check that the user is past authentication and current URL is the redirect with the code.
      if(response.path == ',https://login.microsoftonline.com/common/oauth2/nativeclient' ) {
        //iOS does not get to this part. Only on android does the webview go to the redirect URI.
        //iOS shows the loading dots at the top of the screen and hangs there indefinitely.
        print("Webview has redirected");

      }
    }
  }

}
`

**Comment by darshankawar** [comment] 2020-10-08 06:40
@eserna86 
Since we don't have Azure authentication url to try and replicate this, can you try the same using [this](https://pub.dev/packages/flutter_inappwebview) plugin on iOS and see if it works ?
thanks.

**Comment by eserna86** [comment] 2020-10-13 15:08
The issue might be on the MS side, I will let you know the outcome when they get back to me.

**Comment by pedromassangocode** [comment] 2020-11-04 12:43
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-04 12:43 UTC

**Comment by eserna86** [comment] 2020-11-30 18:17
I have finished troubleshooting with MS support and ran packet captures which proved that MS is indeed seeing that the authentication was successful on iOS and sends the requested code back to the webview however the webview does not redirect the user to the redirect uri. I can setup an account for you to test with if you want to use the code I provided earlier.

Requesting code from token endpoint
![image](https://user-images.githubusercontent.com/72224310/100647873-1f24db80-330e-11eb-9c3e-fd53d9daaf61.png)
Response from MS
![image](https://user-images.githubusercontent.com/72224310/100647971-424f8b00-330e-11eb-992a-b64da723dab0.png)

**Comment by mdmota** [comment] 2020-12-21 18:36
How was it resolved?

**Comment by Revoltiks** [comment] 2021-02-28 00:38
> How was it resolved?

I solved my problem as follows 

```
              onPageStarted: (String url) {
                // for Android here 
                if (url == "${GlobalConfiguration().getValue('base_url')}payments/sberpay") {
                  Navigator.of(context).pushReplacementNamed('/Pages', arguments: 3);
                }
              },
              onPageFinished: (String url) {
                // for iOS here 
                if (url == "${GlobalConfiguration().getValue('base_url')}payments/sberpay") {
                  Navigator.of(context).pushReplacementNamed('/Pages', arguments: 3);
                }
              }),
```

**Comment by Revoltiks** [comment] 2021-02-28 00:41
> 
> 
> I have finished troubleshooting with MS support and ran packet captures which proved that MS is indeed seeing that the authentication was successful on iOS and sends the requested code back to the webview however the webview does not redirect the user to the redirect uri. I can setup an account for you to test with if you want to use the code I provided earlier.
> 
> Requesting code from token endpoint
> ![image](https://user-images.githubusercontent.com/72224310/100647873-1f24db80-330e-11eb-9c3e-fd53d9daaf61.png)
> Response from MS
> ![image](https://user-images.githubusercontent.com/72224310/100647971-424f8b00-330e-11eb-992a-b64da723dab0.png)
> 
> I also found something very interesting, when pasting the authorization url with headers into Chrome it redirects to
> ![image](https://user-images.githubusercontent.com/72224310/100658342-e4766f80-331c-11eb-8666-a896168371eb.png)
> 
> However, pasting the url into safari a popup shows in the foreground to download the file instead of loading the redirect uri. I believe this just isn't showing in the webview and it is waiting for a response hence the continuous loading dots at the top.
> ![image](https://user-images.githubusercontent.com/72224310/100658717-86965780-331d-11eb-873c-77523f6b2a42.png)



> 
> 
> I am using webview_flutter to do Azure AD authentication. It works fine on Android however when testing it on iOS the webview does not redirect and therefore cannot receive the token. If a bad password is entered it will tell you but when login is successful the loading dots show at the top of the device and just hangs there. Not sure if there is some special iOS setting or permissions I need to also implement to get this to work. Any help would be appreciated.
