### ISSUE TITLE
Google login in Flutter

### ISSUE THREAD

**Issue by UwaisWisitech** [flutter/flutter#26160] opened 2019-01-07 05:06 UTC
I am trying to integrate Google login in my flutter App.
Getting the below issue:

```
'package:firebase_auth/firebase_auth.dart': Failed assertion: line 327 pos 12: 'idToken != null': is not true.
```
Here is my code:
```dart
class UserOptionsState extends State<UserOptions> {
  final FirebaseAuth _fAuth = FirebaseAuth.instance;
  final GoogleSignIn _gSignIn = new GoogleSignIn();

  Future<FirebaseUser> _signIn(BuildContext context) async {
    Scaffold.of(context).showSnackBar(new SnackBar(
      content: new Text('Sign in button clicked'),
    ));

    GoogleSignInAccount googleSignInAccount = await _gSignIn.signIn();
    GoogleSignInAuthentication authentication =
    await googleSignInAccount.authentication;

    FirebaseUser user = await _fAuth.signInWithGoogle(
        idToken: authentication.idToken,
        accessToken: authentication.accessToken);

    UserInfoDetails userInfo = new UserInfoDetails(
        user.providerId, user.displayName, user.email, user.photoUrl, user.uid);

    List<UserInfoDetails> providerData = new List<UserInfoDetails>();
    providerData.add(userInfo);

    UserDetails details = new UserDetails(
        user.providerId,
        user.uid,
        user.displayName,
        user.photoUrl,
        user.email,
        user.isAnonymous,
        user.isEmailVerified,
        providerData);

    print("User Name : ${user.displayName}");

    return user;
  }
```

**Comment by zoechi** [comment] 2019-01-07 07:08
Duplicate of #24378

**Closed by zoechi** 2019-01-07 07:08 UTC
