### ISSUE TITLE
`flutter build` or `flutter doctor` changes files in the repo, invalidating caching

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter#39176] opened 2019-08-24 06:58 UTC
I am using Flutter at channel "beta". Looks like the `flutter` tool is too eager to change contents of the directory, which stays in the way of the idea of CI cache.

For instance, when running `flutter upgrade` I often get Git indexes changed, even though there are no actual updates to the "beta" channel. I work around this by verifying the output of

```shell
$ git ls-remote https://github.com/flutter/flutter beta
```

against the one that I have cached, before running "flutter upgrade".

But recently, even running "flutter build" or "flutter doctor" changes the files inside the "flutter" directory. Since Flutter does not support read-only directories, I can't lock that down or put the contents into a Docker container, and CI (e.g. AppVeyor, CirrusCI) detect changes. Re-uploading the cache adds about 1-2 minutes on top of a 4 minute build, so the increase in build time is up to 50%!

```
Cache flutter has changed!
List of changes for /root/flutter:
modified: bin/cache/flutter_version_check.stamp
modified: .git/index
modified: .git/logs/HEAD
flutter cache size is 352Mb.
Uploading cache flutter...
```

**Comment by dotdoom** [comment] 2019-08-30 14:16
@jmagman 

1. `flutter_version_check.stamp` doesn't always change, but `.git/index` changes all the time
1. I will add a command to diff this file and get back to you with results
1. is there any documentation that suggests which files should be cached and which not? It's rather inconvenient to capture those files one by one and there are more `.stamp` files in that directory. If there's no doc and you know which files should be excluded, I am happy to draft a page.

**Comment by dotdoom** [comment] 2019-08-30 16:36
Here are a few builds within less than 2hours from each other. You have to click on `Upload `flutter` cache` step to expand it and see the relevant log, and I also inserted it inline here.

## https://cirrus-ci.com/task/6019028591575040

<details>
<summary>Upload `flutter` cache</summary>
<pre>
SHA for /root/flutter is '55d4a393d6deded1e70bca4041ae9ff1427d9444323f5d3c7117ba9413dadb08'
Cache flutter has changed!
List of changes for /root/flutter:
created: .git/refs/remotes/origin/revert-38922-text-docs
modified: .git/logs/refs/remotes/origin/master
modified: bin/cache/flutter_version_check.stamp
created: .git/logs/refs/remotes/origin/revert-38922-text-docs
created: .git/refs/remotes/origin/keyonghan-deviceLabReadme
created: .git/objects/pack/pack-4f90bb97e820cd22d9248dce5e4734db78d56a7a.pack
modified: .git/logs/HEAD
created: .git/logs/refs/remotes/origin/keyonghan-deviceLabReadme
created: .git/logs/refs/remotes/origin/dev
created: .git/objects/pack/pack-4f90bb97e820cd22d9248dce5e4734db78d56a7a.idx
created: .git/refs/remotes/origin/dev
modified: .git/refs/remotes/origin/master
modified: .git/index
created: .git/refs/tags/v1.9.6
created: .git/refs/tags/v1.9.7
flutter cache size is 352Mb.
Uploading cache flutter...
</pre>
</details>

## https://cirrus-ci.com/task/6407238706528256

```diff
diff -u "/tmp/flutter_version_check.stamp" "${FLUTTER_SDK_ROOT}/bin/cache/flutter_version_check.stamp" || true
--- /tmp/flutter_version_check.stamp	2019-08-30 15:11:24.351182016 +0000
+++ /root/flutter/bin/cache/flutter_version_check.stamp	2019-08-30 15:11:33.821919896 +0000
@@ -1,4 +1,4 @@
 {
-  "lastTimeVersionWasChecked": "2019-08-30 14:49:03.289046",
+  "lastTimeVersionWasChecked": "2019-08-30 15:11:33.812091",
   "lastKnownRemoteVersion": "2019-07-27 18:48:24.000Z"
 }
\ No newline at end of file
```

<details>
<summary>Upload `flutter` cache</summary>
<pre>
SHA for /root/flutter is '6dd2d2c49d9898f00e8d71fd43d469f609e15c16e5c6b5d8314b6e9631734009'
Cache flutter has changed!
List of changes for /root/flutter:
modified: .git/index
modified: bin/cache/flutter_version_check.stamp
modified: .git/logs/HEAD
flutter cache size is 352Mb.
Uploading cache flutter...
</pre>
</details>

## https://cirrus-ci.com/task/6256536961155072

```diff
diff -u "/tmp/flutter_version_check.stamp" "${FLUTTER_SDK_ROOT}/bin/cache/flutter_version_check.stamp" || true
--- /tmp/flutter_version_check.stamp	2019-08-30 15:57:12.958746975 +0000
+++ /root/flutter/bin/cache/flutter_version_check.stamp	2019-08-30 15:57:23.634654935 +0000
@@ -1,4 +1,4 @@
 {
-  "lastTimeVersionWasChecked": "2019-08-30 15:12:00.955916",
+  "lastTimeVersionWasChecked": "2019-08-30 15:57:23.627225",
   "lastKnownRemoteVersion": "2019-07-27 18:48:24.000Z"
 }
\ No newline at end of file
```

<details>
<summary>Upload `flutter` cache</summary>
<pre>
SHA for /root/flutter is 'e88151b12fd8aab9f04eff0eec8f6121a81f42e03eb9b5372db828e6dcc477fc'
Cache flutter has changed!
List of changes for /root/flutter:
modified: .git/index
modified: bin/cache/flutter_version_check.stamp
modified: .git/logs/HEAD
flutter cache size is 352Mb.
Uploading cache flutter...
</pre>
</details>

## https://cirrus-ci.com/task/5201218533588992

```diff
diff -u "/tmp/flutter_version_check.stamp" "${FLUTTER_SDK_ROOT}/bin/cache/flutter_version_check.stamp" || true
--- /tmp/flutter_version_check.stamp	2019-08-30 16:25:55.665237789 +0000
+++ /root/flutter/bin/cache/flutter_version_check.stamp	2019-08-30 16:26:06.306143070 +0000
@@ -1,4 +1,4 @@
 {
-  "lastTimeVersionWasChecked": "2019-08-30 15:57:23.627225",
+  "lastTimeVersionWasChecked": "2019-08-30 16:26:06.298500",
   "lastKnownRemoteVersion": "2019-07-27 18:48:24.000Z"
 }
\ No newline at end of file
```

<details>
<summary>Upload `flutter` cache</summary>
<pre>
SHA for /root/flutter is 'fafcde86499807810bd10ef9e7ab506142bea2b424fdbdfb89ae5e0910df1ce3'
Cache flutter has changed!
List of changes for /root/flutter:
modified: .git/index
modified: bin/cache/flutter_version_check.stamp
modified: .git/logs/HEAD
flutter cache size is 352Mb.
Uploading cache flutter...
</pre>
</details>

**Comment by christopherfujino** [comment] 2020-01-22 23:20
Related to https://github.com/flutter/flutter/issues/44526

**Comment by christopherfujino** [comment] 2022-06-01 18:58
Actually, closing this as a duplicate of https://github.com/flutter/flutter/issues/44526

**Closed by christopherfujino** 2022-06-01 18:58 UTC
Labels: tool
