### ISSUE TITLE
Error: unable to locate asset entry in pubspec.yaml

### ISSUE THREAD

**Issue by Aruljebaraj** [flutter/flutter#154971] opened 2024-09-11 03:04 UTC
### Steps to reproduce

created and published a package called [aj_text_editor](https://pub.dev/packages/aj_text_editor), which includes fonts in the assets folder. The fonts work perfectly when I use the package within its own project. However, when I add the package to another project, the fonts don't appear unless I manually add the assets folder to the project's pubspec.yaml file.

I was advised to reference the fonts using:
packages/aj_text_editor/assets/fonts/Billabong.ttf
in the pubspec.yaml of the project using the package, but this approach didn’t work.

If I manually copy the assets folder and declare it in the pubspec.yaml of the new project, it works fine. Is there a way to make the font automatically usable from the package without this extra step?

### Expected results

Should be able to use the font from the package on project in which it Is added

### Actual results

Unable to use the font of the packages

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-09-11 10:23
Hi @Aruljebaraj, looks like you missed declaring `package` in TextStyle, please see https://github.com/flutter/flutter/issues/142494#issuecomment-2343218814. Closing this as a duplicate of https://github.com/flutter/flutter/issues/142494.

**Closed by huycozy** 2024-09-11 10:23 UTC
Labels: in triage

**Comment by Aruljebaraj** [comment] 2024-09-19 05:36
@huycozy  I'm already     return OptionButton(
      isActive: isSelected,
      size: const Size(90, 45),
      onPressed: () => onSelect(font),
      child: Center(child: Text(font, style: TextStyle(fontFamily: font))),
    ); doing that
