### ISSUE TITLE
[tool_crash] FileSystemException: readSync failed, OS Error: Data error (cyclic redundancy check)., errno = 23

### ISSUE THREAD

**Issue by lokhandeyogesh7** [flutter/flutter#80058] opened 2021-04-08 16:29 UTC
## Command
```
flutter --quiet assemble --depfile path r\build\app\intermediates\flutter\debug -dTargetFile=path\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=flutter.inspector.structuredErrors%3Dtrue debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: readSync failed, OS Error: Data error (cyclic redundancy check).
, errno = 23
```
#0      _RandomAccessFile.readSync (dart:io/file_impl.dart:760:7)
#1      _File.readAsBytesSync (dart:io/file_impl.dart:552:23)
#2      _File.readAsStringSync (dart:io/file_impl.dart:584:18)
#3      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#4      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:209:22)
#5      _runSync (package:flutter_tools/src/base/error_handling_io.dart:556:14)
#6      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:208:12)
#7      SourceVisitor.visitDepfile (package:flutter_tools/src/build_system/source.dart:55:37)
#8      List.forEach (dart:core-patch/growable_array.dart:403:8)
#9      Target._resolveConfiguration (package:flutter_tools/src/build_system/build_system.dart:246:14)
#10     Target.resolveInputs (package:flutter_tools/src/build_system/build_system.dart:194:12)
#11     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:147:39)
#12     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:154:58)
#13     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:552:30)
#14     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:58)
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:18)
<asynchronous suspension>
#16     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 2.0.2 at C:\flutter
    • Framework revision 8962f6dc68 (4 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Yogarsha\AppData\Local\Android\Sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Yogarsha\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\Yogarsha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Mi A2 (mobile) • 47f8d56b • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: null
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
apple_sign_in-0.1.0
connectivity-0.4.9+5
connectivity_for_web-0.3.1+4
connectivity_macos-0.1.0+7
firebase_auth-0.18.4+1
firebase_auth_web-0.3.2+3
firebase_core-0.5.3
firebase_core_web-0.2.1+1
firebase_messaging-7.0.3
flutter_facebook_login-3.0.0
flutter_local_notifications-3.0.3
flutter_native_admob-2.1.0+3
flutter_plugin_android_lifecycle-1.0.11
google_mobile_ads-0.12.1
google_sign_in-4.5.9
google_sign_in_web-0.9.2
hexcolor-1.0.6
image_picker-0.6.7+22
in_app_purchase-0.3.5+1
path_provider-1.6.28
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+8
path_provider_windows-0.0.5
shared_preferences-0.5.12+4
shared_preferences_linux-0.0.2+4
shared_preferences_macos-0.0.1+11
shared_preferences_web-0.1.2+7
shared_preferences_windows-0.0.2+3
sqflite-1.3.2+4
url_launcher-5.7.10
url_launcher_linux-0.0.1+4
url_launcher_macos-0.0.1+9
url_launcher_web-0.1.5+3
url_launcher_windows-0.0.1+3
webview_flutter-1.0.7

**Comment by TahaTesser** [comment] 2021-04-09 10:43
please check out this https://github.com/flutter/flutter/issues/61264#issuecomment-656898218


duplicate of https://github.com/flutter/flutter/issues/61264

**Closed by TahaTesser** 2021-04-09 10:43 UTC
Labels: in triage
