### ISSUE TITLE
[go_router] Extra value is null when Widget inspector is open 

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#99099] opened 2022-02-24 23:45 UTC
copied from https://github.com/csells/go_router/issues/385

The extra from GoRouterState is null when the Widget inspector is open with the toggle SELECT WIDGET MODE is enabled and the current page extract data from the GoRouterState (extra).

Video:
https://user-images.githubusercontent.com/4898256/155167172-4e6924bd-f71b-49e6-be25-2884ce39e593.mov

Code to reproduce this issue:

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(const MyApp());
}

GoRouter _router = GoRouter(
  initialLocation: '/splash',
  debugLogDiagnostics: true,
  observers: [],
  routes: [
    GoRoute(
      path: '/splash',
      pageBuilder: (context, state) => CustomTransitionPage<void>(
        key: state.pageKey,
        child: const SplashPage(),
        transitionsBuilder: (context, animation, animation2, child) {
          return FadeTransition(
            opacity: animation,
            child: child,
          );
        },
      ),
    ),
    GoRoute(
      name: 'login',
      path: '/login',
      builder: (context, state) => LoginPage(user: state.extra! as String),
    ),
  ],
);

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routeInformationParser: _router.routeInformationParser,
      routerDelegate: _router.routerDelegate,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
    );
  }
}

class SplashPage extends StatefulWidget {
  const SplashPage({Key? key}) : super(key: key);

  @override
  State<SplashPage> createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage> {
  Future<void> _checkSplash() async {
    await Future.delayed(const Duration(seconds: 2));
    context.go('/login', extra: "Diego");
  }

  @override
  void initState() {
    _checkSplash();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      backgroundColor: Colors.white,
      body: const Center(
        child: CircularProgressIndicator(),
      ),
    );
  }
}

class LoginPage extends StatefulWidget {
  const LoginPage({required this.user, Key? key}) : super(key: key);
  final String user;

  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('LOGIN'),
      ),
      body: Center(
        child: Text('user: ${widget.user}'),
      ),
    );
  }
}
```

**Comment by AsmaaMohamed81** [comment] 2022-03-01 08:02
this problem with me any answer?

**Comment by maheshmnj** [comment] 2022-03-25 12:59
I am able to reproduce this issue on stable and the master channel. Launching widget inspector throws the below null check error.

<details>
<summary>logs</summary>

```
Restarted application in 3,636ms.
[GoRouter] known full paths for routes:
[GoRouter]   => /splash
[GoRouter]   => /login
[GoRouter] known full paths for route names:
[GoRouter]   login => /login
[GoRouter] setting initial location /splash
[GoRouter] going to /login
[GoRouter] MaterialApp found
[GoRouter] deep linking to /login
I/flutter (24209): ══╡ EXCEPTION CAUGHT BY GOROUTER ╞══════════════════════════════════════════════════════════════════
I/flutter (24209): The following _Exception was thrown Exception during GoRouter navigation:
I/flutter (24209): Exception: Null check operator used on a null value
I/flutter (24209):
I/flutter (24209): When the exception was thrown, this was the stack:
I/flutter (24209): #0      _router.<anonymous closure>
I/flutter (24209): #1      GoRouterDelegate._pageBuilder
I/flutter (24209): #2      GoRouterDelegate.getPages
I/flutter (24209): #3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:180:26)
I/flutter (24209): #4      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:219:26)
I/flutter (24209): #5      new _GrowableList.of (dart:core-patch/growable_array.dart:155:26)
I/flutter (24209): #6      new List.of (dart:core-patch/array_patch.dart:51:28)
I/flutter (24209): #7      Iterable.toList (dart:core/iterable.dart:470:12)
I/flutter (24209): #8      GoRouterDelegate._builder
I/flutter (24209): #9      GoRouterDelegate.build
I/flutter (24209): #10     Builder.build
I/flutter (24209): #11     StatelessElement.build
I/flutter (24209): #12     ComponentElement.performRebuild
I/flutter (24209): #13     Element.rebuild
I/flutter (24209): #14     ComponentElement._firstBuild
I/flutter (24209): #15     ComponentElement.mount
I/flutter (24209): ...     Normal element mounting (111 frames)
I/flutter (24209): #126    Element.inflateWidget
I/flutter (24209): #127    MultiChildRenderObjectElement.inflateWidget
I/flutter (24209): #128    MultiChildRenderObjectElement.mount
I/flutter (24209): ...     Normal element mounting (9 frames)
I/flutter (24209): #137    Element.inflateWidget
I/flutter (24209): #138    Element.updateChild
I/flutter (24209): #139    SingleChildRenderObjectElement.update
I/flutter (24209): #140    Element.updateChild
I/flutter (24209): #141    ComponentElement.performRebuild
I/flutter (24209): #142    Element.rebuild
I/flutter (24209): #143    StatelessElement.update
I/flutter (24209): #144    Element.updateChild
I/flutter (24209): #145    ComponentElement.performRebuild
I/flutter (24209): #146    Element.rebuild
I/flutter (24209): #147    StatelessElement.update
I/flutter (24209): #148    Element.updateChild
I/flutter (24209): #149    ComponentElement.performRebuild
I/flutter (24209): #150    Element.rebuild
I/flutter (24209): #151    StatelessElement.update
I/flutter (24209): #152    Element.updateChild
I/flutter (24209): #153    ComponentElement.performRebuild
I/flutter (24209): #154    Element.rebuild
I/flutter (24209): #155    ProxyElement.update
I/flutter (24209): #156    Element.updateChild
I/flutter (24209): #157    ComponentElement.performRebuild
I/flutter (24209): #158    Element.rebuild
I/flutter (24209): #159    ProxyElement.update
I/flutter (24209): #160    Element.updateChild
I/flutter (24209): #161    SingleChildRenderObjectElement.update
I/flutter (24209): #162    Element.updateChild
I/flutter (24209): #163    ComponentElement.performRebuild
I/flutter (24209): #164    StatefulElement.performRebuild
I/flutter (24209): #165    Element.rebuild
I/flutter (24209): #166    StatefulElement.update
I/flutter (24209): #167    Element.updateChild
I/flutter (24209): #168    ComponentElement.performRebuild
I/flutter (24209): #169    Element.rebuild
I/flutter (24209): #170    ProxyElement.update
I/flutter (24209): #171    Element.updateChild
I/flutter (24209): #172    ComponentElement.performRebuild
I/flutter (24209): #173    StatefulElement.performRebuild
I/flutter (24209): #174    Element.rebuild
I/flutter (24209): #175    StatefulElement.update
I/flutter (24209): #176    Element.updateChild
I/flutter (24209): #177    ComponentElement.performRebuild
I/flutter (24209): #178    Element.rebuild
I/flutter (24209): #179    ProxyElement.update
I/flutter (24209): #180    _InheritedNotifierElement.update
I/flutter (24209): #181    Element.updateChild
I/flutter (24209): #182    ComponentElement.performRebuild
I/flutter (24209): #183    StatefulElement.performRebuild
I/flutter (24209): #184    Element.rebuild
I/flutter (24209): #185    StatefulElement.update
I/flutter (24209): #186    Element.updateChild
I/flutter (24209): #187    ComponentElement.performRebuild
I/flutter (24209): #188    Element.rebuild
I/flutter (24209): #189    ProxyElement.update
I/flutter (24209): #190    Element.updateChild
I/flutter (24209): #191    ComponentElement.performRebuild
I/flutter (24209): #192    StatefulElement.performRebuild
I/flutter (24209): #193    Element.rebuild
I/flutter (24209): #194    StatefulElement.update
I/flutter (24209): #195    Element.updateChild
I/flutter (24209): #196    ComponentElement.performRebuild
I/flutter (24209): #197    Element.rebuild
I/flutter (24209): #198    ProxyElement.update
I/flutter (24209): #199    Element.updateChild
I/flutter (24209): #200    ComponentElement.performRebuild
I/flutter (24209): #201    StatefulElement.performRebuild
I/flutter (24209): #202    Element.rebuild
I/flutter (24209): #203    StatefulElement.update
I/flutter (24209): #204    Element.updateChild
I/flutter (24209): #205    ComponentElement.performRebuild
I/flutter (24209): #206    Element.rebuild
I/flutter (24209): #207    ProxyElement.update
I/flutter (24209): #208    _InheritedNotifierElement.update
I/flutter (24209): #209    Element.updateChild
I/flutter (24209): #210    SingleChildRenderObjectElement.update
I/flutter (24209): #211    Element.updateChild
I/flutter (24209): #212    ComponentElement.performRebuild
I/flutter (24209): #213    Element.rebuild
I/flutter (24209): #214    ProxyElement.update
I/flutter (24209): #215    _InheritedNotifierElement.update
I/flutter (24209): #216    Element.updateChild
I/flutter (24209): #217    ComponentElement.performRebuild
I/flutter (24209): #218    StatefulElement.performRebuild
I/flutter (24209): #219    Element.rebuild
I/flutter (24209): #220    StatefulElement.update
I/flutter (24209): #221    Element.updateChild
I/flutter (24209): #222    ComponentElement.performRebuild
I/flutter (24209): #223    StatefulElement.performRebuild
I/flutter (24209): #224    Element.rebuild
I/flutter (24209): #225    StatefulElement.update
I/flutter (24209): #226    Element.updateChild
I/flutter (24209): #227    ComponentElement.performRebuild
I/flutter (24209): #228    Element.rebuild
I/flutter (24209): #229    ProxyElement.update
I/flutter (24209): #230    _InheritedNotifierElement.update
I/flutter (24209): #231    Element.updateChild
I/flutter (24209): #232    SingleChildRenderObjectElement.update
I/flutter (24209): #233    Element.updateChild
I/flutter (24209): #234    ComponentElement.performRebuild
I/flutter (24209): #235    Element.rebuild
I/flutter (24209): #236    ProxyElement.update
I/flutter (24209): #237    _InheritedNotifierElement.update
I/flutter (24209): #238    Element.updateChild
I/flutter (24209): #239    ComponentElement.performRebuild
I/flutter (24209): #240    StatefulElement.performRebuild
I/flutter (24209): #241    Element.rebuild
I/flutter (24209): #242    StatefulElement.update
I/flutter (24209): #243    Element.updateChild
I/flutter (24209): #244    ComponentElement.performRebuild
I/flutter (24209): #245    StatefulElement.performRebuild
I/flutter (24209): #246    Element.rebuild
I/flutter (24209): #247    StatefulElement.update
I/flutter (24209): #248    Element.updateChild
I/flutter (24209): #249    ComponentElement.performRebuild
I/flutter (24209): #250    Element.rebuild
I/flutter (24209): #251    ProxyElement.update
I/flutter (24209): #252    Element.updateChild
I/flutter (24209): #253    ComponentElement.performRebuild
I/flutter (24209): #254    StatefulElement.performRebuild
I/flutter (24209): #255    Element.rebuild
I/flutter (24209): #256    StatefulElement.update
I/flutter (24209): #257    Element.updateChild
I/flutter (24209): #258    ComponentElement.performRebuild
I/flutter (24209): #259    Element.rebuild
I/flutter (24209): #260    ProxyElement.update
I/flutter (24209): #261    Element.updateChild
I/flutter (24209): #262    ComponentElement.performRebuild
I/flutter (24209): #263    StatefulElement.performRebuild
I/flutter (24209): #264    Element.rebuild
I/flutter (24209): #265    StatefulElement.update
I/flutter (24209): #266    Element.updateChild
I/flutter (24209): #267    ComponentElement.performRebuild
I/flutter (24209): #268    Element.rebuild
I/flutter (24209): #269    ProxyElement.update
I/flutter (24209): #270    Element.updateChild
I/flutter (24209): #271    ComponentElement.performRebuild
I/flutter (24209): #272    StatefulElement.performRebuild
I/flutter (24209): #273    Element.rebuild
I/flutter (24209): #274    StatefulElement.update
I/flutter (24209): #275    Element.updateChild
I/flutter (24209): #276    ComponentElement.performRebuild
I/flutter (24209): #277    StatefulElement.performRebuild
I/flutter (24209): #278    Element.rebuild
I/flutter (24209): #279    StatefulElement.update
I/flutter (24209): #280    Element.updateChild
I/flutter (24209): #281    SingleChildRenderObjectElement.update
I/flutter (24209): #282    Element.updateChild
I/flutter (24209): #283    ComponentElement.performRebuild
I/flutter (24209): #284    Element.rebuild
I/flutter (24209): #285    ProxyElement.update
I/flutter (24209): #286    _InheritedNotifierElement.update
I/flutter (24209): #287    Element.updateChild
I/flutter (24209): #288    ComponentElement.performRebuild
I/flutter (24209): #289    StatefulElement.performRebuild
I/flutter (24209): #290    Element.rebuild
I/flutter (24209): #291    StatefulElement.update
I/flutter (24209): #292    Element.updateChild
I/flutter (24209): #293    ComponentElement.performRebuild
I/flutter (24209): #294    Element.rebuild
I/flutter (24209): #295    ProxyElement.update
I/flutter (24209): #296    Element.updateChild
I/flutter (24209): #297    ComponentElement.performRebuild
I/flutter (24209): #298    Element.rebuild
I/flutter (24209): #299    ProxyElement.update
I/flutter (24209): #300    Element.updateChild
I/flutter (24209): #301    ComponentElement.performRebuild
I/flutter (24209): #302    StatefulElement.performRebuild
I/flutter (24209): #303    Element.rebuild
I/flutter (24209): #304    StatefulElement.update
I/flutter (24209): #305    Element.updateChild
I/flutter (24209): #306    ComponentElement.performRebuild
I/flutter (24209): #307    Element.rebuild
I/flutter (24209): #308    BuildOwner.buildScope
I/flutter (24209): #309    WidgetsBinding.drawFrame
I/flutter (24209): #310    RendererBinding._handlePersistentFrameCallback
I/flutter (24209): #311    SchedulerBinding._invokeFrameCallback
I/flutter (24209): #312    SchedulerBinding.handleDrawFrame
I/flutter (24209): #313    SchedulerBinding._handleDrawFrame
I/flutter (24209): #317    _invoke (dart:ui/hooks.dart:151:10)
I/flutter (24209): #318    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
I/flutter (24209): #319    _drawFrame (dart:ui/hooks.dart:115:31)
I/flutter (24209): (elided 3 frames from dart:async)
I/flutter (24209): ════════════════════════════════════════════════════════════════════════════════════════════════════

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (20 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.5:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.191, on macOS 12.3 21E230 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.191 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 69b92f0452 (2 days ago), 2022-03-21 21:25:09 -0700
    • Engine revision e6233bd30b
    • Dart version 2.17.0 (build 2.17.0-223.0.dev)
    • DevTools version 2.11.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.37.20220301

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by lukepighetti** [comment] 2022-04-29 14:52
This is a pretty serious blocker for my development workflow. I typically navigate to a screen, then use this to find the source code for a widget to modify. Because of this issue, I am blocked from doing this, and I have to reload the app to proceed.

**Comment by KanybekMomukeyev** [comment] 2022-05-24 03:57
Absolutely same here, by this issue, can not use widget in inspector mode.

**Comment by lukepighetti** [comment] 2022-05-25 17:59
Has anyone found a temporary fix to this? It's pretty unbearable.

**Comment by maheshmnj** [comment] 2022-05-26 07:31
cc: @chunhtai

**Comment by tomassasovsky** [comment] 2022-07-06 13:53
same here. this breaks a lot of my development process :((

**Comment by tomassasovsky** [comment] 2022-07-20 17:17
@stuartmorgan any updates on this?

**Comment by camerow** [comment] 2023-01-09 19:09
I'm experiencing the same thing.

**Comment by GonzagaGIT** [comment] 2023-02-02 01:41
I can't use it either :(

**Comment by engine-bmkim-uxplus** [comment] 2023-04-03 04:36
This has not been resolved yet.

**Comment by Konomaster** [comment] 2023-04-27 16:14
Yep, still not resolved.

**Comment by maRci002** [comment] 2023-05-04 22:29
I'm using plain `Router` and it has similar behaviour, `RouterDelegate.setInitialRoutePath` is triggered when `Widget Inspector` is opened:

[`_RouterState.didChangeDependencies` triggers `RestorationMixin.didChangeDependencies`](https://github.com/flutter/flutter/blob/3.7.12/packages/flutter/lib/src/widgets/router.dart#L655) which calls [`_RouterState.restoreState` which calls `_processRouteInformation(widget.routeInformationProvider!.value, () => widget.routerDelegate.setInitialRoutePath);`](https://github.com/flutter/flutter/blob/3.7.12/packages/flutter/lib/src/widgets/router.dart#L584)

Meanwhile `setInitialRoutePath` doc:

> Called by the [Router](https://api.flutter.dev/flutter/widgets/Router-class.html) **at startup** with the structure that the [RouteInformationParser](https://api.flutter.dev/flutter/widgets/RouteInformationParser-class.html) obtained from parsing the initial route.
> 
> This should configure the [RouterDelegate](https://api.flutter.dev/flutter/widgets/RouterDelegate-class.html) so that when [build](https://api.flutter.dev/flutter/widgets/RouterDelegate/build.html) is invoked, it will create a widget tree that matches the initial route.
> 
> By default, this method forwards the configuration to [setNewRoutePath](https://api.flutter.dev/flutter/widgets/RouterDelegate/setNewRoutePath.html).
> 
> Consider using a [SynchronousFuture](https://api.flutter.dev/flutter/foundation/SynchronousFuture-class.html) if the result can be computed synchronously, so that the [Router](https://api.flutter.dev/flutter/widgets/Router-class.html) does not need to wait for the next microtask to schedule a build.

**Comment by chunhtai** [comment] 2023-06-12 22:11
A simpler repro

<details>

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  State<StatefulWidget> createState() => MyAppState();

}

class MyAppState extends State<MyApp> {
  bool toggle = false;
  @override
  Widget build(BuildContext context) {
    Widget app = MaterialApp.router(
      routerConfig: _router,
    );
    if (toggle) {
      app = Container(child: app);
    }
    return Directionality(
      textDirection: TextDirection.ltr,
      child: Stack(
        children: [
          app,
          SizedBox(
            width: 100,
            height: 100,
            child: ElevatedButton(onPressed: (){
              setState(() {
                toggle = !toggle;
              });
            }, child: Text('press')),
          )
        ],
      ),
    );
  }

  final GoRouter _router = GoRouter(
    initialLocation: '/homepage',
    debugLogDiagnostics: true,
    routes: [
      GoRoute(
        name: 'homepage',
        path: '/homepage',
        pageBuilder: (context, state) => const MaterialPage(
          child: HomePage(),
        ),
      ),
      GoRoute(
        name: 'page1',
        path: '/page1',
        pageBuilder: (context, state) => MaterialPage(
          child: Page1Widget(args: state.extra as Page1Args),
        ),
      ),
    ],
  );

}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: const Text('go to page 1'),
          onPressed: () => GoRouter.of(context).goNamed(
            'page1',
            extra: Page1Args('John Doe'),
          ),
        ),
      ),
    );
  }
}

class Page1Widget extends StatelessWidget {
  final Page1Args args;

  const Page1Widget({Key? key, required this.args}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(
          '${args.name}, go to page 2',
          style: const TextStyle(fontSize: 40),
        ),
      ),
    );
  }
}

class Page1Args {
  final String name;

  Page1Args(this.name);
}

</details>

The main issue is that the extra need to be json serializable. right now the original issue would work if extra is serializable type like Map or List, or String.

This would be a problem if extra is a complicated object.

I think there are three options we can do here:


1. Warn developers that the extra can be null and why, and in what case it would be null
2. GoRouter takes in a custom Codec for extra, in case developer don't want to rely on json codec.
3. extra class must implement a serialize/ deserialize method


I think both 2 and 3 may be over-solving the issue, and they each have their own draw back.

I intent to just do 1, but I would like to hear how people think about this. I will revisit this issue after one or two weeks and decide how to proceed.

**Comment by Maatteogekko** [comment] 2023-06-13 06:27
Having extra limited to be a serializable type means it would be always null for what I am using it for (passing typed parameters that are not url encodable to the route).
I am in favour of 3, but the implementation of the serialize/deserialize methods can be optional. Then extra will be null if it isn't a serializable type or doesn't implement serialization methods.

**Comment by letyletylety** [comment] 2023-06-28 14:01
> The main issue is that the extra need to be json serializable. right now the original issue would work if extra is serializable type like Map or List, or String.

I tried putting a List in extra, but ended up with the same error.

Could you show me a simple code example that works with serializable types?

**Comment by astubenbord** [comment] 2023-07-06 13:06
I think allowing to register custom converters for extra objects (e.g. to json format and back) would be a good compromise. If a converter for a specific type exists, use this converter, otherwise refer to the standard encode/decode functions from the dart:convert library.
I also wouldn't agree that allowing the extra to be null (if it is expected to be not null) just because the serialisation is a valid solution to this problem. 

A current workaround could be to specify from/toJson methods for all extra objects and always manually convert the extra toJson, then in the builders parse them back using the fromJson. However, this only works if the extra is always the same type or if different type's json representations are distinguishable or identifiable by certain fields/values. Even if this may work, It's much less convenient and makes code harder to read/write compared to passing around typed objects between routes (how it is intended).

**Comment by YaserH25** [comment] 2023-07-23 14:45
still have the same problem, extra is null whenever rebuild happens

**Comment by JohnF17** [comment] 2023-09-06 15:06
I believe this comment here might help y'all 👍 https://github.com/flutter/flutter/issues/130602#issuecomment-1708530820

**Comment by muhammadkamel** [comment] 2023-10-18 22:16
<img width="1435" alt="Screenshot 2023-10-19 at 1 12 52 AM" src="https://github.com/flutter/flutter/assets/17657941/a020e550-42b7-4626-8b0f-d5df58b1c890">

**Comment by muhammadkamel** [comment] 2023-10-18 22:17
I attempted to use the Go Router Builder, but I'm still facing an issue with the DevTool when I activate the "Toggle Select Widget mode."

**Comment by mikeroneer** [comment] 2023-10-23 11:22
This issue does not only happen in combination with the widget inspector but also when performing async redirection as suggested in the example https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/async_redirection.dart due to the dependency on the inherited widget.

@chunhtai You mentioned you'd prefer to "Warn developers that the extra can be null and why, and in what case it would be null". We already understand the code path resulting in the null value but not the conceptional reason behind it. Could you please elaborate this in detail so we can get a better understanding and maybe even be able to support resolving the issue?

**Comment by chunhtai** [comment] 2023-10-23 17:18
there are cases where all the state in the app need to go through serialization/deserialization. e.g. State restoration, browser backward and forward (states are saved in browser history), or widget inspector. All the state in GoRouter can be serialized except for the arbitrary type `extra` and push route future.

Right now, it will attempt to serialize `extra`. If it can't, it will leave it as null.

**Comment by mikeroneer** [comment] 2023-10-23 18:29
> there are cases where all the state in the app need to go through serialization/deserialization. e.g. State restoration, browser backward and forward (states are saved in browser history), or widget inspector. All the state in GoRouter can be serialized except for the arbitrary type `extra` and push route future.
> 
> Right now, it will attempt to serialize `extra`. If it can't, it will leave it as null.

I understand, and it matches the observations I've had so far. Another approach we could maybe take is to simply keep the `extra` parameter as `Object` in the encoded map and drop it before native serialization. This is of course far from perfect but it would probably help a lot to migrate from Navigator 1.0 especially in mobile apps. Otherwise, I feel like the `extra` is useless and one would probably end up using only primitive query parameters which conflicts with the idea of type-safe routes from go_router_builder. Do you think this would be reasonable or are there any cases preventing us from doing this?

Would there be any other option to use complex types for route parameter?

**Comment by chunhtai** [comment] 2023-10-23 18:46
> in the encoded map and drop it before native serialization

That is what we are doing now. because it is dropped during serialization, the extra is lost.

**Comment by mikeroneer** [comment] 2023-10-23 19:06
> > in the encoded map and drop it before native serialization
> 
> That is what we are doing now. because it is dropped during serialization, the extra is lost.

so the attempt mentioned would keep it at that point (`_RouteMatchListEncoder`) in the map as `Object` (decoding would simply extract the object again) while it is dropped only before calling the `SystemChannels.navigation` method channel. What do you think about it?

Still, the question is, would there be any other option to use complex types for route parameters?

**Comment by chunhtai** [comment] 2023-10-23 19:21
> so the attempt mentioned would keep it at that point (_RouteMatchListEncoder) in the map as Object (decoding would simply extract the object again) while it is dropped only before calling the SystemChannels.navigation method channel. What do you think about it?

This would only solve part of the problem, you will still have cases that the app is booted from scratch with just serialized state. for example, state restoration or browser backward and forward from a different domain. It wouldn't solve the use case of this github issue as well.

**Comment by mikeroneer** [comment] 2023-10-23 19:56
> > so the attempt mentioned would keep it at that point (_RouteMatchListEncoder) in the map as Object (decoding would simply extract the object again) while it is dropped only before calling the SystemChannels.navigation method channel. What do you think about it?
> 
> This would only solve part of the problem, you will still have cases that the app is booted from scratch with just serialized state. for example, state restoration or browser backward and forward from a different domain. It wouldn't solve the use case of this github issue as well.

This is true, but it would at least solve part of the problem compared to dropping the `extra` at all, especially for mobile apps where browser history is not required. Do you think this is more of a web problem or does it go hand-in-hand with Android and iOS apps? Since the proposed idea does not solve the use case of this issue either, we should definitely think about it again. Are there any other approaches you currently pursue? I feel like this is a rather crucial bug specifically when requiring async redirection and there is actually no way to work around it, is it?

**Comment by chunhtai** [comment] 2023-10-23 20:49
For mobile, the only case this can be a problem should be during state restoration. Your proposal can't solve state restoration case, neither. or am I missing other cases this can happen?

> Do you think this is more of a web problem or does it go hand-in-hand with Android and iOS apps?

I think there are different issue but with same root cause.

I am hesitating about implementing the your proposal is that if at some point we decided that developer has to write a toJson and fromJson method in their `extra`.  The proposal solution will be superseded. It may be hard to remove the code without a breaking change.

> I feel like this is a rather crucial bug specifically when requiring async redirection and there is actually no way to work around it, is it?

I am not aware of an async redirection issue cause by this, can you elaborate?

**Comment by mikeroneer** [comment] 2023-10-24 13:10
> For mobile, the only case this can be a problem should be during state restoration. Your proposal can't solve state restoration case, neither. or am I missing other cases this can happen?
> 
What are examples when the state would be restored? Picking an app from the background to foreground maybe?

> I am hesitating about implementing the your proposal is that if at some point we decided that developer has to write a toJson and fromJson method in their extra. The proposal solution will be superseded. It may be hard to remove the code without a breaking change.
>
I agree! Due to the lack of alternatives, I still appreciate we're discussing this option at least. Regarding the possible breaking change I think this should not be an issue but I'd have to think through it before making a clear statement.

> I am not aware of an async redirection issue cause by this, can you elaborate?
>
Sure! According to https://github.com/flutter/packages/blob/main/packages/go_router/example/lib/async_redirection.dart, one should use an inherited widget to perform async redirection. If the state changes, the router's `didChangeDependencies` is called since it's registered to the inherited widget. In case the `extra` is a non-serializable complex type, it is dropped during encoding in `restoreRouteInformation` (parser.dart) which would cause the following error.

```
"type 'Null' is not a subtype of type 'Foo' in type cast"
```
If it was serializable, we'd face the issue after deserialization with the difference that the decoded `Map` cannot be casted to the complex parameter type. I could provide you with a more specific simplified code example if you'd like to.

So from the current findings, due to the executed code path via `didChangeDependencies` originating from the inherited widget state change, the issue becomes visible. Without that, one would not notice that the `extra` has already been dropped. Can you elaborate why serialization is even needed at that point?

**Comment by chunhtai** [comment] 2023-10-24 16:21
> What are examples when the state would be restored? Picking an app from the background to foreground maybe?

https://api.flutter.dev/flutter/services/RestorationManager-class.html
There are some instructions in Testing State Restoration section.

@mikeroneer oh yes, that sounds like a bug where the RouteInformation.state is going through unnecessary serializing and deserializing. Can you help my file a bug and pin me on it. I should take a look and see if I can come up with a fix.

**Comment by mikeroneer** [comment] 2023-10-25 12:30
@chunhtai filed the issue #137248

**Closed** 2023-11-03 20:16 UTC
Labels: package, has reproducible steps, a: null-safety, P2, found in release: 2.10, p: go_router, found in release: 2.13, team-go_router, triaged-go_router

**Comment by chunhtai** [comment] 2023-11-03 20:21
An API is added to provide a custom codec to GoRouter for serializing and deserializing the data. If you are seeing this issue, providing a custom codec should solve the issue.
