### ISSUE TITLE
TextFormField losing its text when app focus changes

### ISSUE THREAD

**Issue by Haidar0096** [flutter/flutter#56111] opened 2020-05-01 08:50 UTC
I put a comment on [this](https://github.com/flutter/flutter/issues/16391#issuecomment-619450901) similar closed  issue, but got no response,

[here](https://github.com/rrousselGit/flutter_hooks/issues/131#issuecomment-619402961) is a video describing the problem,

The problem is that when I am typing inside the text field, and I press the recent apps button while I am still typing, this will cause the app to lose focus, so far so good, but then when I press on my app from recent apps list to get back to it, I see that the text field has:

- lost focus (so the soft keyboard is also dismissed)

- lost its text (which is the real problem!!)  

So how to solve this??

**Comment by pedromassango** [comment] 2020-05-14 20:46
Can you please provide a code that reproces the issue.

Cc: @TahaTesser

**Comment by Haidar0096** [comment] 2020-05-14 21:28
> Can you please provide a code that reproces the issue.
> 
> Cc: @TahaTesser

I provided code in the link in the question
just replace the default counter app code with this code and do the steps as I described in the link and you can reproduce the issue, here is the [link](https://github.com/rrousselGit/flutter_hooks/issues/131#issue-606778449)
And here is the code:

```
class Test extends HookWidget {
  @override
  Widget build(BuildContext context) {
    print('build');//build is not called again when app gains focus
    final focusNode = useFocusNode();
    final controller = useTextEditingController();
      return Scaffold(
      body: Center(
        child: Container(
          width: 200,
          height: 200,
          color: Colors.red,
          child: TextField(
            focusNode: focusNode,
            controller: controller,
          ),
        ),
      ),
    );
  }
}
```

**Comment by bradsb** [comment] 2020-05-26 12:43
I'm also experiencing this issue on v1.12.13+hotfix.9.

It can be recreated quickly with flutter create and the code from [the flutter cookbook](https://flutter.dev/docs/cookbook/forms/text-field-changes).

Enter text into the `TextField` or `TextFormField` but don't change focus to another field, change to the recent apps view, return to app and the text resets to the initial value of the `TextEditingController`.

This is accompanied with
```
I/flutter (17625): Second text field: nmevkj
I/flutter (17625): Second text field: nmevk
D/EGL_emulation(17625): eglMakeCurrent: 0xe93f4120: ver 3 0 (tinfo 0xddfa0e60)
D/FlutterView(17625): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@468c0ef
D/FlutterView(17625): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@468c0ef
D/eglCodecCommon(17625): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(17625): eglCreateContext: 0xf467f2e0: maj 3 min 0 rcv 3
D/EGL_emulation(17625): eglMakeCurrent: 0xf467f2e0: ver 3 0 (tinfo 0xddfa0990)
D/EGL_emulation(17625): eglMakeCurrent: 0xe93f4120: ver 3 0 (tinfo 0xddfa0e60)
I/flutter (17625): Second text field: nmevkjadm
D/EGL_emulation(17625): eglMakeCurrent: 0xf467f2e0: ver 3 0 (tinfo 0xddfa0990)
D/eglCodecCommon(17625): setVertexArrayObject: set vao to 0 (0) 22 0
```

The text isn't lost if you change or request focus away from the field before leaving the app, or on the occasion that the `Detaching from a FlutterEngine` doesn't appear.

Changing to v1.17.1, the problem doesn't seem to happen and there is no `Detaching from a FlutterEngine` in the debug console

**Comment by Haidar0096** [comment] 2020-05-26 12:48
> I'm also experiencing this issue on v1.12.13+hotfix.9.
> 
> It can be recreated quickly with flutter create and the code from [the flutter cookbook](https://flutter.dev/docs/cookbook/forms/text-field-changes).
> 
> Enter text into the `TextField` or `TextFormField` but don't change focus to another field, change to the recent apps view, return to app and the text resets to the initial value of the `TextEditingController`.
> 
> This is accompanied with
> 
> ```
> I/flutter (17625): Second text field: nmevkj
> I/flutter (17625): Second text field: nmevk
> D/EGL_emulation(17625): eglMakeCurrent: 0xe93f4120: ver 3 0 (tinfo 0xddfa0e60)
> D/FlutterView(17625): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@468c0ef
> D/FlutterView(17625): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@468c0ef
> D/eglCodecCommon(17625): setVertexArrayObject: set vao to 0 (0) 0 0
> D/EGL_emulation(17625): eglCreateContext: 0xf467f2e0: maj 3 min 0 rcv 3
> D/EGL_emulation(17625): eglMakeCurrent: 0xf467f2e0: ver 3 0 (tinfo 0xddfa0990)
> D/EGL_emulation(17625): eglMakeCurrent: 0xe93f4120: ver 3 0 (tinfo 0xddfa0e60)
> I/flutter (17625): Second text field: nmevkjadm
> D/EGL_emulation(17625): eglMakeCurrent: 0xf467f2e0: ver 3 0 (tinfo 0xddfa0990)
> D/eglCodecCommon(17625): setVertexArrayObject: set vao to 0 (0) 22 0
> ```
> 
> The text isn't lost if you change or request focus away from the field before leaving the app, or on the occasion that the `Detaching from a FlutterEngine` doesn't appear.
> 
> Changing to v1.17.1, the problem doesn't seem to happen and there is no `Detaching from a FlutterEngine` in the debug console

I recently noticed that on version 1.12
this problem does not happen on a real device (in debug mode)

**Comment by bradsb** [comment] 2020-05-26 13:04
For me, this occurs both on the emulator and a real device, in both debug and release mode. It also persists in the apk installed from the play store

**Comment by bradsb** [comment] 2020-05-28 13:51
It looks like this might be a dupe of #47137
And is described here: https://flutter.dev/docs/release/breaking-changes/text-input-client-current-value

**Comment by Haidar0096** [comment] 2020-05-28 14:52
> It looks like this might be a dupe of #47137
> And is described here: https://flutter.dev/docs/release/breaking-changes/text-input-client-current-value

Yes It looks like a duplicate but I don't think this issue here should be closed before the problem is solved

**Comment by VladyslavBondarenko** [comment] 2020-07-08 16:59
Hi @Haidar0096 ,
Does the issue about lost text value persist?
I can't reproduce it with https://github.com/flutter/flutter/issues/56111#issuecomment-628896125 on Redmi Note 7 Android 9 (API 28) and Android 10 (emulator) with current stable `1.17.5` and current master `1.20.0-3.0.pre.163`.

**Comment by dipeshmohanty** [comment] 2020-07-30 09:12
Hi @Haidar0096 

I think I had the same issue, where when it loses focus and once you come back to the app the text field is empty.

I fixed this issue after adding two lines to the activity tag in AndroidManifest.xml
android:alwaysRetaininTaskState="true"
android:autoRemoveFromRecents="false"

**Closed** 2020-07-30 09:39 UTC
Labels: a: text input, f: focus, f: material design, framework, waiting for customer response
