### ISSUE TITLE
[Android] I/flutter ( 8707): PathAccessException: Cannot copy file to '/storage/emulated/0/MyFolder/MYPDF.pdf', path = '/storage/emulated/0/Android/data/com.example.myproject/files/copyme.pdf' (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by TeachMeHacking** [flutter/flutter#146620] opened 2024-04-11 05:26 UTC
### Steps to reproduce

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION"/>
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"
       />
       
       
         <application
        ...
        android:requestLegacyExternalStorage="true" 

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.19045.4170], locale en-IN)
Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.17)
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.87.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by danagbemava-nc** [comment] 2024-04-11 08:33
Closing this as a duplicate of https://github.com/flutter/flutter/issues/40498

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2024-04-11 08:33 UTC
Labels: in triage

**Comment by TeachMeHacking** [comment] 2024-04-11 10:19
(OS Error: Operation not permitted, errno = 1) In my case there is no duplicate problem, I try to copy the file but my new file uses (**:**) in the name. So I was getting an error
