### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s):  must have scheme 'file:'.

### ISSUE THREAD

**Issue by AhmedLAith1** [flutter/flutter#109511] opened 2022-08-14 12:33 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Uri c:/src/opj/new_project_1/lib/fonts/Pacifico-Regular.ttf must have scheme 'file:'.
```
#0      WindowsStyle.pathFromUri (package:path/src/style/windows.dart:86:7)
#1      Context.fromUri (package:path/src/context.dart:1000:32)
#2      ManifestAssetBundle._resolveAsset (package:flutter_tools/src/asset.dart:820:47)
#3      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:714:34)
#4      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:245:54)
<asynchronous suspension>
#5      HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:459:26)
<asynchronous suspension>
#6      HotRunner.attach (package:flutter_tools/src/run_hot.dart:280:40)
<asynchronous suspension>
#7      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:638:9)
<asynchronous suspension>
#8      AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:636:5)
<asynchronous suspension>
#9      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:583:15)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.0.4 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (6 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\ahmed\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Users\ahmed\IntelliJ IDEA 2022.1.3
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.69.1)
    • VS Code at C:\Users\ahmed\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 104.0.1293.47

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 85684f9300908116a78138ea4c6036c35c9a1236

**Comment by danagbemava-nc** [comment] 2022-08-15 09:53
Closing this as a duplicate of https://github.com/flutter/flutter/issues/107592. 

Kindly upvote the original issue. 

Thank you

**Closed by danagbemava-nc** 2022-08-15 09:53 UTC
Labels: in triage
