### ISSUE TITLE
await tester.pumpWidget(MyApp()) throw Exception

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#57992] opened 2020-05-26 08:58 UTC
MyApp can run on device without error but throw Exception when testWidget
[log.txt](https://github.com/flutter/flutter/files/4681011/log.txt)

**Comment by TahaTesser** [comment] 2020-05-26 14:14
Hi @tbm98 
can you please provide your `flutter doctor -v`? 
Also, to better address the issue, would be helpful  if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by tbm98** [comment] 2020-05-26 14:16
doctor:
```
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-VN)
    • Flutter version 1.19.0-1.0.pre at /Users/tbm/dev/flutter_sdk/flutter
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tbm/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone 11 Pro • CDE77D0C-DF86-4F52-9E87-F3F4B92FB0B8 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

! Doctor found issues in 1 category.
```
 my code:
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'src/views/pages/home.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Wedding',
      theme: ThemeData(
          visualDensity: VisualDensity.adaptivePlatformDensity,
          primarySwatch: Colors.pink,
          appBarTheme: const AppBarTheme(
              color: Colors.transparent,
              elevation: 0,
              iconTheme: IconThemeData(color: Colors.black),
              textTheme: TextTheme(
                  headline6:
                      TextStyle(color: Colors.black, fontSize: 55 / 3)))),
      home: HomePage(),
    );
  }
}
```

**Comment by TahaTesser** [comment] 2020-05-26 15:26
Hi @tbm98 

<details> 
<summary>main.dart</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Wedding',
      theme: ThemeData(
          visualDensity: VisualDensity.adaptivePlatformDensity,
          primarySwatch: Colors.pink,
          appBarTheme: const AppBarTheme(
              color: Colors.transparent,
              elevation: 0,
              iconTheme: IconThemeData(color: Colors.black),
              textTheme: TextTheme(
                  headline6:
                      TextStyle(color: Colors.black, fontSize: 55 / 3)))),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}

``` 

</details> 

```
// This is a basic Flutter widget test.
//
// To perform an interaction with a widget in your test, use the WidgetTester
// utility that Flutter provides. For example, you can send tap and scroll
// gestures. You can also use WidgetTester to find child widgets in the widget
// tree, read text, and verify that the values of widget properties are correct.

import 'package:flutter_test/flutter_test.dart';

import 'package:dev_flutter/main.dart';

void main() {
  testWidgets('MyAppTest', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(MyApp());

    // Verify that our counter starts at 0.
  });
}

```
```
PS C:\Users\Taha\AndroidStudioProjects\dev_flutter> flutter test .\test\widget_test.dart
00:03 +1: All tests passed!
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[√] Flutter (Channel dev, 1.19.0-1.0.pre, on Microsoft Windows [Version 10.0.19041.264], locale en-US)
    • Flutter version 1.19.0-1.0.pre at C:\Code\flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Code\SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Code\SDK
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 83.0.4103.61

• No issues found!

``` 

</details> 

Test is passing 

Thank you

**Comment by tbm98** [comment] 2020-05-26 15:30
Yes. But my HomePage work fine with no bug 🤔

**Comment by TahaTesser** [comment] 2020-05-26 15:46
Hi  @tbm98 
It's an issue with `await tester.pumpWidget(MyApp())`
MyApp executing probably that leads to crash 
Since the issue is not reproducible using code sample i provided 

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-05-26 15:46 UTC
Labels: in triage

**Comment by tbm98** [comment] 2020-05-27 02:02
Hi @TahaTesser 
when I run again with my open source at [repo](https://github.com/tbm98/make_sleep_better)

still get error
```
Testing started at 08:58 ...
/Users/tbm/dev/flutter_sdk/flutter/bin/flutter --no-color test --machine --plain-name "Counter increments smoke test" test/widget_test.dart
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   logs (package:make_sleep_better/src/supports/logs.dart:8:13)
│ #1   MyApp.build.<anonymous closure> (package:make_sleep_better/main.dart:24:9)
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 🐛 rebuild material app
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Pending timers:
Timer (duration: 0:00:01.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:283:41)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:247:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:180:19)
#6      PrefsSupport.getDarkMode (package:make_sleep_better/src/supports/prefs.dart:22:18)
#7      MainProvider._initLoad (package:make_sleep_better/src/providers/main.dart:23:37)
#8      new MainProvider (package:make_sleep_better/src/providers/main.dart:13:5)
#9      main.<anonymous closure>.<anonymous closure> (file:///Users/tbm/dev/flutter_app/make_sleep_better/test/widget_test.dart:52:24)
#10     _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:576:35)
#11     _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:439:33)
#12     Provider.of (package:provider/src/provider.dart:216:29)
#13     new Selector.<anonymous closure> (package:provider/src/selector.dart:145:61)
#14     _Selector0State.buildWithChild (package:provider/src/selector.dart:74:37)
#15     SingleChildState.build (package:nested/nested.dart:318:41)
#16     StatefulElement.build (package:flutter/src/widgets/framework.dart:4623:28)
#17     SingleChildStatefulElement.build (package:nested/nested.dart:340:18)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4506:15)
#19     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
#21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
#22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4670:11)
#23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
#24     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
...     Normal element mounting (7 frames)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
#34     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:361:11)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
#36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
#37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
...     Normal element mounting (7 frames)
#44     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
...     Normal element mounting (7 frames)
#51     _NestedHookElement.mount (package:nested/nested.dart:188:11)
#52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
#55     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:361:11)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
#57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
#58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
...     Normal element mounting (7 frames)
#65     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
...     Normal element mounting (7 frames)
#72     _NestedHookElement.mount (package:nested/nested.dart:188:11)
...     Normal element mounting (7 frames)
#79     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
#80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3215:20)
#82     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1132:16)
#83     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1110:5)
#84     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1124:7)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
#86     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
#87     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1006:18)
#88     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#89     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1074:15)
#90     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1013:9)
#91     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:879:9)
#94     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#95     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:866:27)
#96     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:462:22)
#99     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#100    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:459:27)
#101    main.<anonymous closure> (file:///Users/tbm/dev/flutter_app/make_sleep_better/test/widget_test.dart:47:18)
#102    main.<anonymous closure> (file:///Users/tbm/dev/flutter_app/make_sleep_better/test/widget_test.dart:15:48)
#103    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
#114    FakeAsync.flushMicrotasks (package:fake_async/fake_async.dart:192:32)
#115    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1099:17)
#116    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1087:35)
(elided 32 frames from dart:async and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1119 pos 12: '() {
      if (   _currentFakeAsync.periodicTimerCount == 0
          && _currentFakeAsync.nonPeriodicTimerCount == 0) {
        return true;
      }

      debugPrint('Pending timers:');
      for (final FakeTimer timer in _currentFakeAsync.pendingTimers) {
        debugPrint(
          'Timer (duration: ${timer.duration}, '
          'periodic: ${timer.isPeriodic}), created:');
        debugPrintStack(stackTrace: timer.creationStackTrace);
        debugPrint('');
      }
      return false;
    }()'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1119:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:716:7)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:683:14)
#7      AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1083:24)
#8      FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:177:54)
#13     withClock (package:clock/src/default.dart:46:10)
#14     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:177:22)
#19     FakeAsync.run (package:fake_async/fake_async.dart:177:7)
#20     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1080:15)
#21     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:137:24)
#22     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#23     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#24     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#29     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#30     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#35     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#36     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:30)
(elided 36 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

The test description was:
  Counter increments smoke test
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: Counter increments smoke test

```

my app work fine with no error

**Comment by tbm98** [comment] 2020-05-27 02:04
my test code:
```
// This is a basic Flutter widget test.
//
// To perform an interaction with a widget in your test, use the WidgetTester
// utility that Flutter provides. For example, you can send tap and scroll
// gestures. You can also use WidgetTester to find child widgets in the widget
// tree, read text, and verify that the values of widget properties are correct.

import 'package:flutter_test/flutter_test.dart';
import 'package:make_sleep_better/main.dart';
import 'package:make_sleep_better/src/providers/main.dart';
import 'package:make_sleep_better/src/supports/prefs.dart';
import 'package:provider/provider.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {

    await tester.pumpWidget(MultiProvider(providers: [
      Provider<PrefsSupport>(
        create: (_) => PrefsSupport(),
      ),
      ChangeNotifierProvider(
        create: (_) => MainProvider(),
      )
    ], child: MyApp()));
  });
}
```

**Comment by TahaTesser** [comment] 2020-05-27 11:40
Hi @tbm98 
If you believe this is a Flutter, please create minimal without third party package and MyApp code 
Thank you
