### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by cjsmocjsmo** [flutter/flutter#115699] opened 2022-11-19 17:28 UTC
## Command
```
flutter clean && flutter run or
flutter clean && flutter run -d chrome or
flutter clean && flutter build web
```

## Steps to Reproduce
1. ...cd myProject
2. ...flutter run -d chrome
3. ...flutter crashes

## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:201:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:185:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:163:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:867:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tool

**Comment by cjsmocjsmo** [comment] 2022-11-19 17:51
flutter doctor -v
[✓] Flutter (Channel master, 3.6.0-6.0.pre.22, on Ubuntu 22.04.1 LTS
    5.15.0-1018-raspi, locale en_US.UTF-8)
    • Flutter version 3.6.0-6.0.pre.22 on channel master at
      /home/charliepi/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 633d7ef046 (9 hours ago), 2022-11-19 03:27:24 -0500
    • Engine revision 916fd798de
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] VS Code (version 1.73.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-arm64    • Ubuntu 22.04.1 LTS
      5.15.0-1018-raspi
    • Chrome (web)    • chrome • web-javascript • Chromium 107.0.5304.110 snap

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by darshankawar** [comment] 2022-11-21 06:31
Closing as duplicate of https://github.com/flutter/flutter/issues/115433

**Closed by darshankawar** 2022-11-21 06:31 UTC
Labels: in triage
