### ISSUE TITLE
Issue: App publishing. webview_flutter

### ISSUE THREAD

**Issue by scg94** [flutter/flutter#51796] opened 2020-03-02 20:48 UTC
Hi, everyone,

## Problem description:

In the application I am developing, it is necessary to play live videos from a YouTube playlist, this is why I must use webview, however, Google Play is rejecting the application because when pressing the android home button, the video continues with the reproduction. How can I stop it to eliminate this error?

```
child: WebView(
    initialUrl: "$PlaylistLink",
    javascriptMode: JavascriptMode.unrestricted,
),
```

Note: It is not when I press the Android back button, it is when I press the Android home button.

I hope you can help me, regards.

**Comment by TahaTesser** [comment] 2020-03-03 08:18
Duplicate of [#32363](https://github.com/flutter/flutter/issues/32363)

**Closed by TahaTesser** 2020-03-03 08:18 UTC
