### ISSUE TITLE
[iOS Module] - Generated Podfile incompatible with plugins that require versions of iOS > 11

### ISSUE THREAD

**Issue by ColinCammaranoAccolade** [flutter/flutter#139256] opened 2023-11-29 19:35 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Context: 
---
When creating a Flutter module, all iOS support files are automatically generated under the `.ios` directory, including a `Podfile.` This `Podfile` sets the default iOS platform to `11.0`, with no apparent way to configure this at the `flutter pub get` or `flutter build ios-framework` stages. Since these files are all generated, guidance suggests that they should not be committed.

Changing `platform :ios, '11.0'` to `platform :ios, '12.0'` in the Podfile resolves this issue on my local machine, but causes additional errors if this file is committed and then cloned onto another machine, such as:
1. If this file is committed, even if it is the only file in the `.ios` directory, `flutter pub get` fails to regenerate the rest of the files in the directory, which causes the subsequent `flutter build ios-framework` command to fail.
2. If all files in `.ios` are committed, other machines will fail to build the project because these generated files use absolute file paths based on the machine in which they were generated.

Environment:
---
```console
Flutter 3.16.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7f20e5d18c (2 days ago) • 2023-11-27 09:47:30 -0800
Engine • revision 22b600f240
Tools • Dart 3.2.1 • DevTools 2.28.3
```

Steps to Reproduce:
---
1. Create a Flutter module: `flutter create --template module my_flutter`
2. Add a plugin with a minimum iOS deployment target > 11. For example, `connectivity_plus: ^5.0.2`
3. Run `flutter pub get`
4. Run `flutter build ios-framework`

### Actual results

The build fails with the following message:

```console
Building frameworks for com.example.myFlutter in debug mode...
 ├─Copying Flutter.xcframework...                                  168ms
 ├─Building App.xcframework...                                      5.1s
Running pod install...                                             598ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `FlutterPluginRegistrant` from
    `Flutter/FlutterPluginRegistrant`
    -> Fetching podspec for `connectivity_plus` from
    `.symlinks/plugins/connectivity_plus/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because
      checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "connectivity_plus":
      In Podfile:
        connectivity_plus (from `.symlinks/plugins/connectivity_plus/ios`)

    Specs satisfying the `connectivity_plus (from
    `.symlinks/plugins/connectivity_plus/ios`)` dependency were found, but they
    required a higher minimum deployment target.

    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer.rb:422:in `analyze'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer.rb:162:in `install!'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/command/install.rb:52:in `run'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/claide-1.1.0/
    lib/claide/command.rb:334:in `run'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/command.rb:52:in `run'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/bin/pod:55:in `<top (required)>'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/bin/pod:25:in `load'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/bin/pod:25:in `<main>'
```

### Logs

<details>
<summary>Logs</summary>

```console

colin.cammarano@<hostname> my_flutter % flutter build ios-framework

Building frameworks for com.example.myFlutter in debug mode...
 ├─Copying Flutter.xcframework...                                  168ms
 ├─Building App.xcframework...                                      5.1s
Running pod install...                                             598ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `FlutterPluginRegistrant` from
    `Flutter/FlutterPluginRegistrant`
    -> Fetching podspec for `connectivity_plus` from
    `.symlinks/plugins/connectivity_plus/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because
      checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "connectivity_plus":
      In Podfile:
        connectivity_plus (from `.symlinks/plugins/connectivity_plus/ios`)

    Specs satisfying the `connectivity_plus (from
    `.symlinks/plugins/connectivity_plus/ios`)` dependency were found, but they
    required a higher minimum deployment target.

    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8
    .0/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer.rb:422:in `analyze'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/installer.rb:162:in `install!'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/command/install.rb:52:in `run'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/claide-1.1.0/
    lib/claide/command.rb:334:in `run'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/lib/cocoapods/command.rb:52:in `run'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.1
    4.3/bin/pod:55:in `<top (required)>'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/bin/pod:25:in `load'
    /Users/colin.cammarano/.rbenv/versions/3.2.2/bin/pod:25:in `<main>'

Error running pod install

```

</details>

### Flutter Doctor output

<details>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.16.1, on macOS 14.1.1 23B81 darwin-arm64, locale
    en-US)
    • Flutter version 3.16.1 on channel stable at
      /Users/colin.cammarano/.flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (2 days ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/colin.cammarano/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/colin.cammarano/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (5 available)
    • Colin’s iPhone (mobile)   • 00008120-001E046136E0C01E            • ios            • iOS 17.1.1 21B91
    • Colin’s iPad Pro (mobile) • 00008027-000125D23E85002E            • ios            • iOS 16.5 20F66
    • iPhone 15 Pro (mobile)    • 87EE74F9-A3E6-4C59-9309-B18814E2044C • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 119.0.6045.199
    ! Error: Browsing on the local area network for Colin’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
    ! Error: Browsing on the local area network for Colin’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2023-11-30 10:21
Thanks for the detailed report @ColinCammaranoAccolade 
I do see the same behavior as reported upon using the example plugin. But if we use a lesser version of that plugin (connectivity_plus: ^4.0.2) and rerun the steps, it seems to be building the ios-framework properly for the module.
Just that, the latest version of that plugin requires min. deployment target to be iOS 12 and hence you might be seeing the compatibility issue.
Does [this](https://github.com/fluttercommunity/plus_plugins/issues/2243) issue help further ?

**Comment by jmagman** [comment] 2023-12-04 20:21
I believe this is a duplicate of https://github.com/flutter/flutter/issues/78862.  See also the conversation in https://github.com/flutter/flutter/issues/98077.

**Closed by jmagman** 2023-12-04 20:21 UTC
Labels: platform-ios, tool, has reproducible steps, team-ios, found in release: 3.16, found in release: 3.17
