### ISSUE TITLE
[tool_crash] SentinelException

### ISSUE THREAD

**Issue by omar-khaium** [flutter/flutter#157256] opened 2024-10-21 07:13 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SentinelException
```console
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:261:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1778:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1790:8)
#3      VmService.reloadSources (package:vm_service/src/vm_service.dart:1410:7)
#4      _reloadDeviceSources (package:flutter_tools/src/run_hot.dart:1382:33)
<asynchronous suspension>
#5      defaultReloadSourcesHelper (package:flutter_tools/src/run_hot.dart:1307:65)
<asynchronous suspension>
#6      HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:1028:38)
<asynchronous suspension>
#7      HotRunner._hotReloadHelper (package:flutter_tools/src/run_hot.dart:922:16)
<asynchronous suspension>
#8      HotRunner.restart (package:flutter_tools/src/run_hot.dart:796:36)
<asynchronous suspension>
#9      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1783:40)
<asynchronous suspension>
#10     TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1836:7)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.1, on macOS 15.0.1 24A348 darwin-arm64, locale en-US)
    [32m•[39m Flutter version 3.24.1 on channel stable at /Users/omar/Development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 5874a72aa4 (9 weeks ago), 2024-08-20 16:46:00 -0500
    [32m•[39m Engine revision c9b9d5780d
    [32m•[39m Dart version 3.5.1
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/omar/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16A242d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[32m[✓][39m VS Code (version 1.94.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.98.0

[32m[✓][39m VS Code (version 1.92.2)
    [32m•[39m VS Code at /Users/omar/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.98.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m iPhone 16 Pro Max (mobile)      • 8E466717-05C8-4AAC-986C-D4643D46940B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-18-0 (simulator)
    [32m•[39m macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.0.1 24A348 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.0.1 24A348 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                               • web-javascript • Google Chrome 129.0.6668.101
    [33m![39m Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.3.8+38
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49
### Plugins
connectivity_plus-6.0.5
cronet_http-1.3.2
cupertino_http-1.5.1
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_core-3.6.0
firebase_core_web-2.18.1
firebase_remote_config-5.1.3
firebase_remote_config_web-1.7.2
flutter_exif_rotation-0.5.1
flutter_image_compress-2.3.0
flutter_image_compress_common-1.0.5
flutter_image_compress_macos-1.0.2
flutter_image_compress_ohos-0.0.3
flutter_image_compress_web-0.1.4+1
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_native_splash-2.4.1
flutter_plugin_android_lifecycle-2.0.21
geolocator-13.0.1
geolocator_android-4.6.1
geolocator_apple-2.3.7
geolocator_web-4.1.1
geolocator_windows-0.2.3
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
in_app_update-4.2.3
jni-0.10.1
maps_launcher-2.2.1
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
sentry_flutter-8.7.0
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
webview_flutter-4.9.0
webview_flutter_android-3.16.7
webview_flutter_wkwebview-3.15.0

**Comment by danagbemava-nc** [comment] 2024-10-21 07:56
Closing this as a duplicate of https://github.com/flutter/flutter/issues/78214

**Closed by danagbemava-nc** 2024-10-21 07:56 UTC
Labels: in triage
