### ISSUE TITLE
The app works well in debug mode but not in release mode.

### ISSUE THREAD

**Issue by richard457** [flutter/flutter#87122] opened 2021-07-27 17:43 UTC
## Steps to Reproduce

1. flutter build apk --debug  --no-tree-shake-icons
![a](https://user-images.githubusercontent.com/8529700/127200963-9b407cb9-a064-4ee5-b78c-d2bdd64511aa.PNG)
As you can see I am able to get all files in all generated abis but when I use
2. flutter build apk --release --no-tree-shake-icons
![b](https://user-images.githubusercontent.com/8529700/127201702-cd1390e0-34d0-4b0b-bc27-5f72991764ca.PNG)
You can see that the files generated are different especially in x86 folder some files are missing such as  libapp.so and flutter.so
This leads me to this:
the app works well in debug mode but when I publish to google play some users start getting errors of missing files I mentioned above, Note that I tested both apk and app bundle it gives the same result, also is very important to note that I am using stable channel of flutter, to reproduce this create an empty project then add these dependencies ```objectbox: ^1.1.1
  objectbox_flutter_libs: any``` then build app both in release and debug mode.

## Logs

<details>
<summary>Logs</summary>

```
```

```
```

</details>

**Comment by richard457** [comment] 2021-07-27 17:46
When I debug on my local machine, I use x86 emulator to be sure, this gave me enough confidence that the app works on x86 devices, but it turn out that in release mode it does not work. please advise me of the fix or workaround.

**Comment by hndrbrm** [comment] 2021-07-27 19:33
I thought flutter doesn't support 32bit [#9253](https://github.com/flutter/flutter/issues/9253)

**Comment by richard457** [comment] 2021-07-27 20:41
Then why does debugging mode works? this set tones that it should work in prod too! we need very clear clarification.

**Comment by richard457** [comment] 2021-07-27 20:42
and reading from the documentation it is obvious that it is supported https://flutter.dev/docs/whats-new#may-18-2021-google-io-edition

**Comment by hndrbrm** [comment] 2021-07-28 03:01
> Then why does debugging mode works? this set tones that it should work in prod too! we need very clear clarification.

In what i understand (CMIIW),
When in debugging mode, the dart would be in JIT, so it works.
But in release mode the dart would be in AOT, unfortunately there are no AOT on x86.

**Comment by richard457** [comment] 2021-07-28 05:59
Is there a way to disable AOT in release mode?

**Comment by TahaTesser** [comment] 2021-07-28 08:01
Hi @richard457 
You should be able to build an app without x86 and still run on x86 devices, see  https://github.com/flutter/flutter/issues/9253#issuecomment-665736044 for more details

This was reported in https://github.com/flutter/flutter/issues/85826 and solved by https://github.com/flutter/flutter/issues/85826#issuecomment-873966407
Closing as duplicate of https://github.com/flutter/flutter/issues/85826

**Closed by TahaTesser** 2021-07-28 08:01 UTC
Labels: in triage
