### ISSUE TITLE
Alert Dialoge Button

### ISSUE THREAD

**Issue by FunlabStudio** [flutter/flutter#83473] opened 2021-05-27 10:35 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

======== Exception caught by widgets library =======================================================
The following assertion was thrown building TestScrolling(dirty, dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#1de43]], state: _SearchMain#c004a):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 4517 pos 12: '!_debugLocked': is not true.

```
```

</details>

**Comment by darshankawar** [comment] 2021-05-27 12:49
@FunlabStudio 
There's not enough details to properly address this issue. Can you provide `flutter doctor -v` and a complete minimal reproducible code sample?

Looking at the exception you are getting `package:flutter/src/widgets/navigator.dart': Failed assertion: line 4517 pos 12: '!_debugLocked': is not true`, it seems to be a code implementation issue rather than bug in framework.

You may also search over internet similar issues and see if you get any leads there.

**Comment by darshankawar** [comment] 2021-06-18 12:54
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2021-06-18 12:54 UTC
Labels: in triage, waiting for customer response
