### ISSUE TITLE
flutter app bundle; ProcessException: ProcessException: Permission denied

### ISSUE THREAD

**Issue by anasnaguib** [flutter/flutter#51414] opened 2020-02-25 16:15 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color build appbundle

## exception

ProcessException: ProcessException: The requested operation requires elevation.

  Command: "C:\Program Files\Android\Android Studio\jre\bin\java.EXE" -version

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:368:50)
#5      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:299:45)
#6      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:40:5)
#7      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:97:14)
#8      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:243:54)
#9      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:174:40)
#10     AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:164:41)
#11     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:100:41)
#12     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#13     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:88:20)
#14     AppContext.get (package:flutter_tools/src/base/context.dart:117:32)
#15     AppContext.get (package:flutter_tools/src/base/context.dart:115:23)
#16     AppContext.get (package:flutter_tools/src/base/context.dart:115:23)
#17     androidStudio (package:flutter_tools/src/android/android_studio.dart:16:44)
#18     javaPath (package:flutter_tools/src/android/android_studio.dart:30:24)
#19     gradleEnvironment (package:flutter_tools/src/android/gradle_utils.dart:27:7)
#20     buildGradleApp (package:flutter_tools/src/android/gradle.dart:368:20)
#21     _AndroidBuilderImpl.buildAab (package:flutter_tools/src/android/android_builder.dart:117:13)
#22     BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:77:26)
#23     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
<asynchronous suspension>
#24     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1465:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#31     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#32     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#33     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _runZoned (dart:async/zone.dart:1518:10)
#38     runZoned (dart:async/zone.dart:1465:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#40     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#41     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#42     new Future.sync (dart:async/future.dart:224:31)
#43     CommandRunner.run (package:args/command_runner.dart:112:14)
#44     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#45     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#46     _rootRun (dart:async/zone.dart:1126:13)
#47     _CustomZone.run (dart:async/zone.dart:1023:19)
#48     _runZoned (dart:async/zone.dart:1518:10)
#49     runZoned (dart:async/zone.dart:1502:12)
#50     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#51     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#52     _rootRun (dart:async/zone.dart:1126:13)
#53     _CustomZone.run (dart:async/zone.dart:1023:19)
#54     _runZoned (dart:async/zone.dart:1518:10)
#55     runZoned (dart:async/zone.dart:1465:12)
#56     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#57     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#58     run (package:flutter_tools/runner.dart:50:10)
#59     main (package:flutter_tools/executable.dart:65:9)
#60     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#61     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
encountered exception: ProcessException: The requested operation requires elevation.

  Command: "C:\Program Files\Android\Android Studio\jre\bin\java.EXE" -version

#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:368:50)
#5      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:299:45)
#6      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:40:5)
#7      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:97:14)
#8      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:243:54)
#9      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:174:40)
#10     AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:20:55)
#11     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:67:33)
#12     Doctor.validators (package:flutter_tools/src/doctor.dart:145:46)
#13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:151:39)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
#15     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:205:26)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#22     _doctorText (package:flutter_tools/runner.dart:204:19)
#23     _createLocalCrashReport (package:flutter_tools/runner.dart:182:32)
#24     _handleToolError (package:flutter_tools/runner.dart:138:31)
<asynchronous suspension>
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:68:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1502:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1465:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#37     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
#40     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by jonahwilliams** [comment] 2020-02-25 16:52
duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-25 16:52 UTC
