### ISSUE TITLE
[flutter-tools] "Flutter Device Selection" not working properly on IntelliJ IDEA CE 2020.1.2

### ISSUE THREAD

**Issue by alsedev** [flutter/flutter#59288] opened 2020-06-11 22:43 UTC
In 2020.1.2 version of IntelliJ IDEA (Installed using Toolbox from JetBrains) the Flutter Plugin doesn't works as it should be in the "Flutter device selection" selector.  Some times it only shows a device icon, and only shows Simulator (no more), some times shows "Loading..." and shows Simulator and list Android Emulators options, and some times (less than the others) it works fine.  I have 2 real devices connected (iPhone 7 & Samsung Tablet) and Simulator opened and Emulator opened.  flutter devices command on terminal works fine, problems appears only on IntelliJ IDEA.

Note: I have Android Studio 4 (Installed using Toolbox from JetBrains).  It appears working.  But doesn't shows all options I need (web/simulator/ios devices) for Flutter work.

Reboot computer, uninstall & reinstall IntelliJ + Flutter Plugin is not working.
![Screen Shot 2020-06-11 at 10 28 00 AM](https://user-images.githubusercontent.com/53921739/84406083-a77fba80-abce-11ea-98b5-761db8e7d37d.png)
![Screen Shot 2020-06-11 at 10 42 51 AM](https://user-images.githubusercontent.com/53921739/84407379-6092c480-abd0-11ea-8748-37030c0616a7.png)

Note, I am on MacOS Catalina 10.15.5 on a MacBook Air, flutter master channel.

```
flutter --version
Flutter 1.20.0-1.0.pre.19 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 49dc9b1227 (71 minutes ago) • 2020-06-11 16:05:18 +0200
Engine • revision 965fbbed17
Tools • Dart 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)
```

```
IntelliJ IDEA 2020.1.2 (Community Edition)
Build #IC-201.7846.76, built on May 31, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Non-Bundled Plugins: org.jetbrains.kotlin, Dart, io.flutter
```

```
flutter devices
6 connected devices:

SM T113NU  • xxxxxxxxxxxxxxxxxxxxxxxxxxxx                         • android-arm    • Android
4.4.4 (API 19)
iPhone7       • xxxxxxxxxxxxxxxxxxxxxxxxxxxx • ios            • iOS
13.5
iPhone 11  • 76F86870-719D-4327-9307-8A3FAD7D15F2     • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
macOS      • macOS                                    • darwin-x64     • Mac OS
X 10.15.5 19F101
Web Server • web-server                               • web-javascript • Flutter
Tools
Chrome     • chrome                                   • web-javascript • Google
Chrome 83.0.4103.97

``` 

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-1.0.pre.19, on Mac OS X 10.15.5 19F101,
    locale en-CO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (6 available)

• No issues found!
```

**Comment by alsedev** [comment] 2020-06-11 22:45
Problem still appears... I found a workaround: **delete .idea folder before open the project** with IntelliJ IDEA CE 2020.1.2. Maybe someone has same behavior with "Flutter Device Selection".

**Comment by iapicca** [comment] 2020-06-12 11:18
Hi @alsedev 
Are you experiencing the issue only with Android Studio / IntelliJ or with VS Code as well?
Thank you

**Comment by cyberdemon8** [comment] 2020-06-12 12:52
Same for me on Android Studio 4 after flutter upgrade from 1.18 to 1.19 on channel beta...
"Loading..." on device selection and no web devices

`
Flutter 1.19.0-4.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision f994b76974 (3 giorni fa) • 2020-06-09 15:53:13 -0700
Engine • revision 9a28c3bcf4
Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Mac OS X 10.15.5 19F96, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

2 connected devices:
Web Server • web-server • web-javascript • Flutter Tools
Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: Dart, com.google.services.firebase, io.flutter, org.intellij.plugins.markdown
`

**Comment by leandrosantiag** [comment] 2020-06-12 15:32
I'm having the same problem after updating android studio
"Loading ...." devices

**Comment by iapicca** [comment] 2020-06-12 15:48
Hi @cyberdemon8 @leandrosantiag 
Are you experiencing the issue only with Android Studio / IntelliJ or with VS Code as well?
Thank you

**Comment by leandrosantiag** [comment] 2020-06-12 15:51
@iapicca Android Studio only

**Comment by pruebasabner** [comment] 2020-06-13 09:32
> Hi @alsedev
> Are you experiencing the issue only with Android Studio / IntelliJ or with VS Code as well?
> Thank you

@iapicca It **appears on both Android Studio and IntelliJ IDEA CE**. (I'm not using VS Code, so I don't know if this issue).  

- [ ] I have found a "new" **workaround** that "maybe" can help to check what/where the bug really is.

My history: 
I need to work with "project1".  Then I open "project2", then, immediately, open "project1".  Close "project2", cause I don't really need it, AND the _"Flutter Device Selection"_ **works as expected**.

Hope this can help!.

**Comment by alsedev** [comment] 2020-06-13 09:42
> Hi @alsedev
> Are you experiencing the issue only with Android Studio / IntelliJ or with VS Code as well?
> Thank you

Hi @iapicca as @pruebasabner said, on both Android/IntelliJ, but I do use mainly **IntelliJ IDEA CE (now version 2020.2 EAP)**.

**Comment by cyberdemon8** [comment] 2020-06-13 12:22
> > Hi @alsedev
> > Are you experiencing the issue only with Android Studio / IntelliJ or with VS Code as well?
> > Thank you
> 
> @iapicca It **appears on both Android Studio and IntelliJ IDEA CE**. (I'm not using VS Code, so I don't know if this issue).
> 
> * [ ]  I have found a "new" **workaround** that "maybe" can help to check what/where the bug really is.
> 
> My history:
> I need to work with "project1". Then I open "project2", then, immediately, open "project1". Close "project2", cause I don't really need it, AND the _"Flutter Device Selection"_ **works as expected**.
> 
> Hope this can help!.

flutter downgrade to 1.18 resolve the issue... switching projects doesn't work for me

**Comment by iapicca** [comment] 2020-06-15 06:57
Hi all
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-15 06:57 UTC
Labels: in triage
