### ISSUE TITLE
android platformview PlatformException

### ISSUE THREAD

**Issue by qylshy** [flutter/flutter#51326] opened 2020-02-24 10:42 UTC
## Steps to Reproduce

1. I use androidview to play lottie animation，I  got an exception
```
PlatformException(error, View=com.android.internal.policy.impl.PhoneWindow$DecorView{31f93b47 V.E..... R......D 0,0-1080,240} not attached to window manager, null) 
1
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569) 
2
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321) 
3
<asynchronous suspension> 
4
#2      AndroidViewController.dispose (package:flutter/src/services/platform_views.dart:539) 
5
#3      _AndroidViewState.dispose (package:flutter/src/widgets/platform_view.dart:490) 
6
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4435) 
7
#5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1748) 
8
#6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
9
#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
10
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
11
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
12
#10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
13
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
14
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
15
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
16
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
17
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
18
#16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
19
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
20
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
21
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
22
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
23
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
24
#22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
25
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
26
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
27
#25     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5534) 
28
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
29
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
30
#28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
31
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
32
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
33
#31     _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:56) 
34
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
35
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
36
#34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
37
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
38
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
39
#37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
40
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
41
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
42
#40     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5534) 
43
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
44
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
45
#43     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
46
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
47
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
48
#46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
49
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
50
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
51
#49     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
52
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
53
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
54
#52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
55
#53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
56
#54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
57
#55     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
58
#56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
59
#57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
60
#58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
61
#59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
62
#60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
63
#61     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
64
#62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
65
#63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
66
#64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
67
#65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
68
#66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
69
#67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
70
#68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
71
#69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
72
#70     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
73
#71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
74
#72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
75
#73     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
76
#74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
77
#75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
78
#76     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
79
#77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
80
#78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
81
#79     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
82
#80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
83
#81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
84
#82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
85
#83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
86
#84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
87
#85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
88
#86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
89
#87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
90
#88     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
91
#89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
92
#90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
93
#91     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
94
#92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
95
#93     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
96
#94     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
97
#95     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
98
#96     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
99
#97     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
100
#98     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
101
#99     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
102
#100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
103
#101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
104
#102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
105
#103    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
106
#104    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
107
#105    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
108
#106    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
109
#107    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
110
#108    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
111
#109    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
112
#110    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
113
#111    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
114
#112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
115
#113    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
116
#114    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
117
#115    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
118
#116    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
119
#117    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
120
#118    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
121
#119    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
122
#120    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
123
#121    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
124
#122    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
125
#123    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
126
#124    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5534) 
127
#125    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
128
#126    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
129
#127    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
130
#128    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
131
#129    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
132
#130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
133
#131    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
134
#132    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
135
#133    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
136
#134    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
137
#135    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
138
#136    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
139
#137    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
140
#138    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
141
#139    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
142
#140    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
143
#141    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
144
#142    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
145
#143    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
146
#144    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
147
#145    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
148
#146    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
149
#147    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
150
#148    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
151
#149    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
152
#150    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
153
#151    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
154
#152    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
155
#153    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
156
#154    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
157
#155    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
158
#156    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
159
#157    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
160
#158    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
161
#159    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
162
#160    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
163
#161    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
164
#162    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
165
#163    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
166
#164    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
167
#165    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
168
#166    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
169
#167    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
170
#168    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
171
#169    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
172
#170    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
173
#171    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
174
#172    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
175
#173    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
176
#174    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
177
#175    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
178
#176    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
179
#177    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
180
#178    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
181
#179    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
182
#180    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
183
#181    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
184
#182    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
185
#183    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
186
#184    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
187
#185    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
188
#186    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
189
#187    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
190
#188    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
191
#189    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
192
#190    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
193
#191    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
194
#192    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
195
#193    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5433) 
196
#194    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
197
#195    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
198
#196    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
199
#197    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
200
#198    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
201
#199    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
202
#200    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
203
#201    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1746) 
204
#202    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4272) 
205
#203    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1744) 
206
#204    ListIterable.forEach (dart:_internal/iterable.dart:41) 
207
#205    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1757) 
208
#206    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2519) 
209
#207    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2350) 
210
#208    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2518) 
211
#209    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:775) 
212
#210    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283) 
213
#211    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102) 
214
#212    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041) 
215
#213    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957) 
216
#214    _rootRun (dart:async/zone.dart:1126) 
217
#215    _CustomZone.run (dart:async/zone.dart:1023) 
218
#216    _CustomZone.runGuarded (dart:async/zone.dart:925) 
219
#217    _invoke (dart:ui/hooks.dart:259) 
220
#218    _drawFrame (dart:ui/hooks.dart:217) 

```

I found the cause in the platform_view.dart , the method "dispose"  caused platform excetion
/// Disposes the Android view.
  ///
  /// The [AndroidViewController] object is unusable after calling this.
  /// The identifier of the platform view cannot be reused after the view is
  /// disposed.
```
  Future<void> dispose() async {
    if (_state == _AndroidViewState.creating || _state == _AndroidViewState.created)
      await SystemChannels.platform_views.invokeMethod<void>('dispose', id);
    _platformViewCreatedCallbacks.clear();
    _state = _AndroidViewState.disposed;
  }
```
```
flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14 18A391, locale
    zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2018.3.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)
```
<details>
  <summary>Logs</summary>

</details>

**Comment by TahaTesser** [comment] 2020-02-24 13:10
Hi @qylshy 
This seems to work as intended. You can play lottie animation after disposing your platformview. 
If you believe this is a Flutter itself,  to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem or repository link
Thank you

**Comment by TahaTesser** [comment] 2020-03-20 08:30
Hi @qylshy 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by TahaTesser** 2020-03-20 08:30 UTC
Labels: waiting for customer response
