### ISSUE TITLE
`flutter pub upgrade/outdated` no longer work

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#96456] opened 2022-01-11 08:56 UTC
## Steps to Reproduce

1. Run `flutter pub upgrade` or `flutter pub outdated`

Yesterday it was working fine, no changes were made to IDE setup

## Logs

<details>
<summary>Logs</summary>

```
SLVR: Version solving took 0:00:13.740174 seconds.
    | Tried 1 solutions.
ERR : Git error. Command: `git fetch`
    | stdout: 
    | stderr: fatal: remote error: 
    |   The unauthenticated git protocol on port 9418 is no longer supported.
    | Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
    | exit code: 128
FINE: Exception type: GitException
FINE: package:pub/src/git.dart 62:7                                    run
    | ===== asynchronous gap ===========================
    | dart:async                                                       Future.catchError
    | package:pub/src/utils.dart 109:52                                captureErrors.wrappedCallback
    | package:stack_trace                                              Chain.capture
    | package:pub/src/utils.dart 122:11                                captureErrors
    | package:pub/src/command.dart 180:13                              PubCommand.run
    | package:args/command_runner.dart 209:27                          CommandRunner.runCommand
    | package:pub/src/command_runner.dart 173:24                       PubCommandRunner.runCommand
    | package:pub/src/command_runner.dart 158:20                       PubCommandRunner.run
    | package:dartdev/dartdev.dart 45:56                               runDartdev
    | /opt/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
IO  : Get versions from https://pub.dartlang.org/api/packages/charcode.
IO  : Get versions from https://pub.dartlang.org/api/packages/source_span.
IO  : Get versions from https://pub.dartlang.org/api/packages/string_scanner.
IO  : Get versions from https://pub.dartlang.org/api/packages/typed_data.
IO  : HTTP GET https://pub.dartlang.org/api/packages/charcode
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: outdated
    | X-Pub-Session-ID: 453E6F3F-39E2-45BA-AF11-789CF245DFF8
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.15.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/source_span
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: outdated
    | X-Pub-Session-ID: 453E6F3F-39E2-45BA-AF11-789CF245DFF8
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.15.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/string_scanner
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: outdated
    | X-Pub-Session-ID: 453E6F3F-39E2-45BA-AF11-789CF245DFF8
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.15.1
IO  : HTTP GET https://pub.dartlang.org/api/packages/typed_data
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: outdated
    | X-Pub-Session-ID: 453E6F3F-39E2-45BA-AF11-789CF245DFF8
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.15.1
IO  : Get versions from https://pub.dartlang.org/api/packages/term_glyph.
IO  : HTTP GET https://pub.dartlang.org/api/packages/term_glyph
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: macos
    | X-Pub-Command: outdated
    | X-Pub-Session-ID: 453E6F3F-39E2-45BA-AF11-789CF245DFF8
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.15.1
[+15166 ms] "flutter outdated" took 15,292ms.
[  +12 ms] pub finished with exit code 69
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:416:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:251:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[+1231 ms] ensureAnalyticsSent: 128ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 69
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale
    en-DE)
    • Flutter version 2.8.1 at /Users/cristianzazomillan/src/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/cristianzazomillan/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

</details>

**Comment by ezet** [comment] 2022-01-11 11:37
Caused by updates to github https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by maheshmnj** [comment] 2022-01-11 12:08
Hi @Zazo032, Thanks for filing the issue.

> The unauthenticated git protocol on port 9418 is no longer supported.
    | Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

This seems like an issue with git authentication. Caused by change on Github's end. So You will need to use the HTTPS URL. Not sure if flutter can do much about it.

Thanks for the link @ezet 

Closing as this is not a bug on the flutter's end.

cc: @jonasfj

**Closed by maheshmnj** 2022-01-11 12:08 UTC
Labels: in triage

**Comment by nmcain** [comment] 2022-01-11 16:33
I'm using the https:// URL format in my pubspec entirely, but this issue still applies to all of my projects that use git packages in any form.

**Comment by kNoAPP** [comment] 2022-01-11 19:31
I too have verified all my dependencies have been updated to the form:
```
example_package:
    git:
      url: https://github.com/exampleUser/exampleRepo.git
      ref: example/branch
```

Yet, I still have this error:
```
Git error. Command: `git fetch`
stdout:
stderr: fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
exit code: 128
```

I have also verified my pubspec.lock contains no references to the `git://` protocol.

What should my next steps look like? @Zazo032 did you manage to resolve your problem doing this alone?

**Comment by Zazo032** [comment] 2022-01-11 19:46
Just in case, try running `flutter clean` and `flutter pub cache clean`. Changing `git://` for `https://` and removing the `.git` at the end of the urls fixed the issue for me.

**Comment by kNoAPP** [comment] 2022-01-11 19:52
@Zazo032 While running `flutter clean` and `flutter pub cache clean` did not resolve the problem, it did reveal it. Looks like some dependencies I have are referencing their own dependencies with the `git://` protocol. I'm guessing this means I'll need to go to those authors and ask them to update their pubspec files.

Thank you.
