### ISSUE TITLE
Issue from website page 入门: 在Windows上搭建Flutter开发环境

### ISSUE THREAD

**Issue by ietwangwei** [flutter/flutter#52645] opened 2020-03-16 01:26 UTC
when i test flutter with version 1.14.6 • channel beta •
it happend to me with problem "[0x7FFB67156230] ANOMALY: meaningless REX prefix used"
and when i install packages with the command " flutter pub get", it show me the error "B A T C H   PROCESSING IS   A B O R T E D"
what can i do to resolve it?

**Comment by SeasonLeee** [comment] 2020-03-16 03:37
It's better for us to help you with the issue if you could provide more information about your environment, such as the output of 'flutter.

Besides, if you could provide more detail of what you are trying to achieve will also help, like, what you wanted to do, what have you tried and the outcome, etc.

**Comment by ietwangwei** [comment] 2020-03-17 07:33
thanks!
there is a list of my environment
![image](https://user-images.githubusercontent.com/12638284/76832097-9f301180-6863-11ea-880a-8de4c14fae40.png)
![image](https://user-images.githubusercontent.com/12638284/76832157-c1c22a80-6863-11ea-8b0c-2c6a9a5f758c.png)
![image](https://user-images.githubusercontent.com/12638284/76832179-cab2fc00-6863-11ea-934a-d2a7ba07e014.png)
and my flutter info
flutter 1.12.13+hotfix.8

and i tried to resolve it with subs methods:
1. remove older flutter and install the lastest version
2. killed process wich maybe effect
3. install the lastest android studio
but the problem is still exsist
 

...hope your help, thank you!

**Comment by ietwangwei** [comment] 2020-03-17 07:34
![image](https://user-images.githubusercontent.com/12638284/76832667-bd4a4180-6864-11ea-864c-8e767821e20b.png)
this is the problem

**Comment by SeasonLeee** [comment] 2020-03-17 08:24
So, thanks for the background information provided, but I want to clarify some more questions for someone with more experience to give you advice.

Does the error message occur during the process that you follow to set up the environment for Flutter?
If so, could you tell us which process or step lead you to this error? The screenshot with outline or the link with description of the process that you followed would be helpful.
Thanks!

**Comment by ietwangwei** [comment] 2020-03-18 01:30
when i run "flutter pub get" to install packages, the error happend to me.
And it's my "flutter doctor" result
![image](https://user-images.githubusercontent.com/12638284/76916315-09e05c00-68fb-11ea-91b0-19baf7dd0786.png)

**Comment by ietwangwei** [comment] 2020-03-18 01:30
![image](https://user-images.githubusercontent.com/12638284/76916328-11a00080-68fb-11ea-9a3f-367a06aba83b.png)

**Comment by TahaTesser** [comment] 2020-03-20 08:04
Hi @ietwangwei 
Could you please execute from the root of your project

1. `flutter pub cache repair`
2. `flutter clean`
then provide your `flutter pub get --verbose` in the comment here
Thank you

**Comment by ietwangwei** [comment] 2020-03-23 08:12
![image](https://user-images.githubusercontent.com/12638284/77295431-e8c7a300-6d20-11ea-9cbc-c6155aabb29d.png)
here is the result when i run width command "flutter pub get --verbose"

**Comment by iapicca** [comment] 2020-03-23 09:34
https://github.com/flutter/flutter/issues/46654

**Comment by jmagman** [comment] 2020-03-23 20:32
Please create an [issue against pub](https://github.com/dart-lang/pub/issues/new/choose) so they can take a look.
I bet this is a duplicate of https://github.com/dart-lang/pub/issues/2258.

**Closed by jmagman** 2020-03-23 20:32 UTC
Labels: severe: crash, tool

**Comment by kizoojun01** [comment] 2020-11-30 11:14
![image](https://user-images.githubusercontent.com/75110474/100603571-a2fbb980-3348-11eb-9c2c-e7e62db2c3b6.png)
