### ISSUE TITLE
Failed to extract manifest from APK: ProcessException: The command failed              Command: /opt/android-sdk/build-tools/31.0.0/aapt dump xmltree

### ISSUE THREAD

**Issue by KosmonautX** [flutter/flutter#115103] opened 2022-11-10 19:13 UTC
## Steps to Reproduce

Encountering issues with `flutter run` which crashes after build is successful even in the default new project with regards to the XML file

```
[ +355 ms] Running Gradle task 'assembleDebug'... (completed in 17.2s)
[ +134 ms] calculateSha: LocalDirectory:
'/home/ksatrayamaii/scratchbac/my_app/build/app/outputs/flutter-apk'/app.apk
[ +666 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +1 ms] executing: /opt/android-sdk/build-tools/31.0.0/aapt dump xmltree
/home/ksatrayamaii/scratchbac/my_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +1 ms] Exit code 127 from: /opt/android-sdk/build-tools/31.0.0/aapt dump xmltree
/home/ksatrayamaii/scratchbac/my_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] /opt/android-sdk/build-tools/31.0.0/aapt: error while loading shared libraries: /lib/libc++.so: file too
short
[   +1 ms] Failed to extract manifest from APK: ProcessException: The command failed
             Command: /opt/android-sdk/build-tools/31.0.0/aapt dump xmltree
             /home/ksatrayamaii/scratchbac/my_app/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml.
[   +1 ms] Exception: Problem building Android application: see above error(s).
[   +2 ms] "flutter run" took 19,006ms.

```

## Logs

<details>
<summary>Logs</summary>

```
JAVA_HOME=/usr/lib/jvm/java-11-temurin/ flutter run --verbose
[  +50 ms] executing: uname -m
[  +21 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +3 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 6928314d505d2bb4777be05e45d7808a5aa91d2a
[        ] executing: [/opt/flutter/] git tag --points-at 6928314d505d2bb4777be05e45d7808a5aa91d2a
[  +10 ms] Exit code 0 from: git tag --points-at 6928314d505d2bb4777be05e45d7808a5aa91d2a
[        ] 3.3.6
[  +35 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[   +1 ms] executing: [/opt/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +28 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +38 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +46 ms] executing: /opt/android-sdk/platform-tools/adb devices -l
[  +63 ms] List of devices attached
           R9YT6096SHA            device usb:1-3 product:a03nnxx model:SM_A035F device:a03 transport_id:4
[   +6 ms] /opt/android-sdk/platform-tools/adb -s R9YT6096SHA shell getprop
[  +50 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +108 ms] Skipping pub get: version match.
[  +73 ms] Generating
/home/ksatrayamaii/scratchbac/demo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +25 ms] ro.hardware = ums9230_25c10
[        ] ro.build.characteristics = phone
[  +23 ms] Initializing file store
[   +7 ms] Skipping target: gen_localizations
[   +4 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs
have updated contents: /home/ksatrayamaii/scratchbac/demo/.dart_tool/package_config_subset}
[  +16 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +3 ms] Launching lib/main.dart on SM A035F in debug mode...
[   +3 ms] /opt/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/opt/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/opt/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.HCPWHK/flutter_tool.DAFZZN/app.dill --packages
/home/ksatrayamaii/scratchbac/demo/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --verbosity=error
--enable-experiment=alternative-invalidation-strategy
[   +4 ms] executing: /opt/android-sdk/build-tools/31.0.0/aapt dump xmltree
/home/ksatrayamaii/scratchbac/demo/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +1 ms] Exit code 127 from: /opt/android-sdk/build-tools/31.0.0/aapt dump xmltree
/home/ksatrayamaii/scratchbac/demo/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] /opt/android-sdk/build-tools/31.0.0/aapt: error while loading shared libraries: /lib/libc++.so: file too
short
[   +2 ms] Failed to extract manifest from APK: ProcessException: The command failed
             Command: /opt/android-sdk/build-tools/31.0.0/aapt dump xmltree
             /home/ksatrayamaii/scratchbac/demo/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml.
[   +2 ms] No application found for TargetPlatform.android_arm64.
           Is your project missing an android/app/src/main/AndroidManifest.xml?
           Consider running "flutter create ." to create one.
[   +4 ms] <- compile package:demo/main.dart
[+6173 ms] "flutter run" took 6,644ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

```

```
[✓] Flutter (Channel stable, 3.3.6, on Arch Linux 6.0.7-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.3.6 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (2 weeks ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/lib/jvm/java-8-openjdk/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_352-b08)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.24.3
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • SM A035F (mobile) • R9YT6096SHA • android-arm64 • Android 12 (API 31)
    • Linux (desktop)   • linux       • linux-x64     • Arch Linux 6.0.7-arch1-1

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.
[ksatrayamaii@ksatrayamaii demo]$ JAVA_HOME=/usr/lib/jvm/java-11-temurin/ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.6, on Arch Linux 6.0.7-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.3.6 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (2 weeks ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/lib/jvm/java-11-temurin/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✗] Linux toolchain - develop for Linux desktop
    • clang version 14.0.6
    • cmake version 3.24.3
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from
      https://github.com/ninja-build/ninja/releases
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • SM A035F (mobile) • R9YT6096SHA • android-arm64 • Android 12 (API 31)
    • Linux (desktop)   • linux       • linux-x64     • Arch Linux 6.0.7-arch1-1

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by exaby73** [comment] 2022-11-11 10:17
Hello @KosmonautX. I think this is occurring because your Android SDK is not in your `/home` directory. Try installing/moving it to inside `$HOME` instead and try again. You can also use the SDK bundled with Android Studio that should be located at `$HOME/Android/Sdk` by running `flutter config --android-sdk $HOME/Android/Sdk`

**Comment by exaby73** [comment] 2022-11-15 06:42
Since I cannot reproduce this issue, I am labeling it for further investigation by the team.

**Comment by reidbaker** [comment] 2022-11-17 19:54
Our current theory is that there are permission issues with your files. Either with the permissions at install of flutter or in your project. Not sure there is something we can do on our side to fix this.

**Closed by reidbaker** 2022-11-17 19:54 UTC
Labels: severe: crash, platform-android, tool, r: invalid
