### ISSUE TITLE
Landscape videos are displayed upside down

### ISSUE THREAD

**Issue by smarteertech** [flutter/flutter#62400] opened 2020-07-28 11:05 UTC
Landscape videos which are recorded by tilting the phone horizontal right, are displayed upside down when played. Did anyone experience this?

## Steps to Reproduce

1. Record a video by tilting the phone horizontal right
2. Play the video using the Flutter video player

**Comment by pedromassangocode** [comment] 2020-07-28 12:28
Hi @smarteertech 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by shangyilim** [comment] 2020-07-28 15:57
I'm having the same problem too. checking exif of the video it appears the video is rotated 180 degrees and the video player isnt compensating for that rotation

**Comment by Elemenopeee** [comment] 2020-07-31 17:39
Hi guys, 
Even I was running into the same problem.
So I tried rotating the videos by 180 degrees using Transform.rotate widget if the aspect ratio was greater than 1.
Its not a through and through fix, as in it can fail.. but for the time being its a potential fix.

**Comment by smarteertech** [comment] 2020-08-01 10:17
Attaching reproducible code

`import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:video_player/video_player.dart';
void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
    VideoPlayerController _videoPlayerController;
    File _video;
    Future getVideo(type) async {
      switch (type) {
        case "camera":
          _video = await ImagePicker.pickVideo(source: ImageSource.camera);
          break;
        default:
      }
      _videoPlayerController = VideoPlayerController.file(_video)
        ..initialize().then((_) {
          _videoPlayerController.play();
          setState(() {});
        });
      setState(() {});
    }
  @override
  Widget build(BuildContext context) {
  
    return Scaffold(
      appBar: AppBar(
        title: Text("Video"),
      ),
      body: _video != null
          ? AspectRatio(
              aspectRatio: 12 / 9,
              child: VideoPlayer(_videoPlayerController),
            )
          : Center(
              child: Icon(
                Icons.picture_in_picture,
              ),
            ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          getVideo('camera');
        },
        child: Icon(Icons.camera),
      ),
    );
  }
}`

**Comment by shangyilim** [comment] 2020-08-02 13:36
> Hi guys,
> Even I was running into the same problem.
> So I tried rotating the videos by 180 degrees using Transform.rotate widget if the aspect ratio was greater than 1.
> Its not a through and through fix, as in it can fail.. but for the time being its a potential fix.

Good idea, I went along this route and exposed the rotation value of the video from Exoplayer:
```
    // video player seems to show video upside down if captured in 180 rotation
    // typically via turning the screen clockwise 90 degrees in landscape
    final shouldRotateVideo = Platform.isAndroid &&
        _videoPlayerController?.value?.rotation != null &&
        _videoPlayerController?.value?.rotation == 180;
```
This `rotation` is not exposed in the plugin so I forked it and added the rotation property, if you're desperate as I am, you can use it instead:
```
video_player:
    git:
      url: https://github.com/shangyilim/plugins.git
      path: packages/video_player/video_player
```
Note: I have not made changes to the iOS code so this works for Android for now

**Comment by pedromassangocode** [comment] 2020-08-03 07:24
This is how I recorded the video

![image](https://user-images.githubusercontent.com/67424416/89156359-7a161400-d562-11ea-85f0-c4c4bb025ca0.png)

And this is how the video is appearing

![image](https://user-images.githubusercontent.com/67424416/89156388-87330300-d562-11ea-8f2e-1fa521ee9cf9.png)

<details>
<summary> Complete sample code</summary>

```dart
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:video_player/video_player.dart';
void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  VideoPlayerController _videoPlayerController;
  File _video;
  Future getVideo(type) async {
    switch (type) {
      case "camera":
        _video = await ImagePicker.pickVideo(source: ImageSource.camera);
        break;
      default:
    }
    _videoPlayerController = VideoPlayerController.file(_video)
      ..initialize().then((_) {
        _videoPlayerController.play();
        setState(() {});
      });
    setState(() {});
  }
  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text("Video"),
      ),
      body: _video != null
          ? AspectRatio(
        aspectRatio: 12 / 9,
        child: VideoPlayer(_videoPlayerController),
      )
          : Center(
        child: Icon(
          Icons.picture_in_picture,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          getVideo('camera');
        },
        child: Icon(Icons.camera),
      ),
    );
  }
}
```
</details>

<details>
<summary> pubspec.yaml</summary>

```
dependencies:
  flutter:
    sdk: flutter
  video_player:
  image_picker:
```
</details>

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en)
    • Flutter version 1.17.5 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 3 categories.
Process finished with exit code 0
```
</details>

**Comment by rostopira** [comment] 2020-11-18 08:57
Looks like duplicate #60327

**Comment by pedromassangocode** [comment] 2020-11-19 07:56
Thanks @rostopira 
Closing this one as duplicate of https://github.com/flutter/flutter/issues/60327.

**Closed by pedromassangocode** 2020-11-19 07:56 UTC
Labels: found in release: 1.17, has reproducible steps, p: first party, p: video_player, platform-android, plugin

**Comment by jhonvegamas** [comment] 2021-02-24 16:23
> > Hi guys,
> > Even I was running into the same problem.
> > So I tried rotating the videos by 180 degrees using Transform.rotate widget if the aspect ratio was greater than 1.
> > Its not a through and through fix, as in it can fail.. but for the time being its a potential fix.
> 
> Good idea, I went along this route and exposed the rotation value of the video from Exoplayer:
> 
> ```
>     // video player seems to show video upside down if captured in 180 rotation
>     // typically via turning the screen clockwise 90 degrees in landscape
>     final shouldRotateVideo = Platform.isAndroid &&
>         _videoPlayerController?.value != null &&
>         _videoPlayerController.value.rotation == 180;
> ```
> 
> This `rotation` is not exposed in the plugin so I forked it and added the rotation property, if you're desperate as I am, you can use it instead:
> 
> ```
> video_player:
>     git:
>       url: https://github.com/shangyilim/plugins.git
>       path: packages/video_player/video_player
> ```
> 
> Note: I have not made changes to the iOS code so this works for Android for now

This solution currently does not work 👎
