### ISSUE TITLE
flutter_admob crashed app due to multiDex

### ISSUE THREAD

**Issue by ErosZy** [flutter/flutter#24091] opened 2018-11-08 05:07 UTC
i use the newest version of firebase_admob plugin, when i add multiDex
```xml
defaultConfig {
    multiDexEnabled true
    ......
}
```
and
```xml
implementation 'com.android.support:multidex:1.0.3'
```
it crashed, due to
```shell
1-08 05:06:54.923 6139-6139/com.vpngo.flutterapp E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAdsInitProvider" on path: /data/app/com.vpngo.flutterapp-2.apk
        at android.app.ActivityThread.installProvider(ActivityThread.java:4822)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4432)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
        at android.app.ActivityThread.access$1300(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAdsInitProvider" on path: /data/app/com.vpngo.flutterapp-2.apk
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4807)
```

**Comment by zoechi** [comment] 2018-11-09 06:57
Please add the output of `flutter doctor -v`.

**Comment by ErosZy** [comment] 2018-11-15 02:16
bogon% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.11.5-pre.29, on Mac OS X 10.13.6 17G65, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.29.0)
[!] Connected device
    ! No devices available

**Comment by rostopira** [comment] 2019-04-01 13:20
Try this answer from SO: https://stackoverflow.com/a/54680454/5593959
Copy code here just in case:
```java
package your.great.pakage.appname;

import io.flutter.app.FlutterApplication;
import android.content.Context;
import androidx.multidex.MultiDex;

public class App extends SomeOtherApplication {

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

}
```

**Comment by kroikie** [comment] 2019-10-13 18:42
@ErosZy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/583. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:54
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment] 2019-10-22 14:57
Hi @ErosZy
Did the proposed [solution ](https://github.com/flutter/flutter/issues/24091#issuecomment-478576034)worked for you?
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-15 12:19
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-15 12:19 UTC
Labels: p: firebase, p: firebase_admob, p: first party, plugin, severe: crash, waiting for customer response
