### ISSUE TITLE
Windows is stuck at 60fps

### ISSUE THREAD

**Issue by ollydixon** [flutter/flutter#102877] opened 2022-04-30 14:04 UTC
```
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (12 days ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

Creating a cross platform app. On Windows it's stuck at 60fps. Seems fine on everything else (not tested Linux).

On at 144hz monitor is looks really bad.

**Comment by stuartmorgan** [comment] 2022-04-30 14:47
Duplicate of https://github.com/flutter/flutter/issues/49757

**Closed by stuartmorgan** 2022-04-30 14:47 UTC
