### ISSUE TITLE
TextField stop erasing when detect white space in Arabic language 

### ISSUE THREAD

**Issue by Mohammad-AlZabibi** [flutter/flutter#59062] opened 2020-06-09 10:22 UTC
Since flutter 1.7.0 the problem has found like the following: 

1- Change your keyboard language
2- Type two words inside or more with white spaces between them 
3- Erase the word after white space -- >> it won't erase the word that before the white space 

This problem is found for Android and ios in the flutter version 1.7.0 - 1.7.1 - 1.7.2 - 1.7.3 and in all channels. 

Waiting for solution. 

Thank you.

**Comment by TahaTesser** [comment] 2020-06-09 15:09
Hi @Mohammad-AlZabibi 
Testing on `stable` channel, issue exist but when i tried same code sample latest `dev` channel, there is no issue

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(
          textDirection: TextDirection.rtl,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-4.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.19.0-4.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 2f7a59a8da (4 days ago), 2020-06-05 03:44:02 -0700
    • Engine revision d17c84e7af
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 02915ec5ce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome 83.0.4103.97

• No issues found!

``` 

</details> 

Could please try it on latest `dev` channel?
Execute the following 
`flutter channel dev`
`flutter upgrade`
`flutter doctor -v`

Clean your project your using `flutter clean` and try again on latest `dev` channel
Thank you

**Comment by TahaTesser** [comment] 2020-06-11 07:13
Hi @Mohammad-AlZabibi 
Testing the long  press to select, there is no crash on `stable` channel or `dev` channel
![flutter_01](https://user-images.githubusercontent.com/48603081/84355815-df8ff900-abe0-11ea-9d08-c53269af5381.png)

![flutter_02](https://user-images.githubusercontent.com/48603081/84355824-e159bc80-abe0-11ea-8df8-2b867ebe59dc.png)

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b041144f83 (7 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
``` 

</details> 

Can you please `flutter run --verbose` of this crash and code sample?
Thank you

**Comment by Mohammad-AlZabibi** [comment] 2020-06-12 09:40
Hi @TahaTesser  
The problem appears when nothing inside the textField only a white space,  on long press it cases the problem 

Now i'm working on (Channel stable, v1.12.13+hotfix.9), it all works fine, waiting for updates

**Comment by TahaTesser** [comment] 2020-06-12 10:07
Hi @Mohammad-AlZabibi 

Still no issue on latest stable

![flutter_01](https://user-images.githubusercontent.com/48603081/84491592-649f0f00-acc2-11ea-9684-ea6eebe2a395.png)


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: TextField(
          textDirection: TextDirection.rtl,
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b041144f83 (8 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
``` 

</details> 


Can you please provide your `flutter doctor -v` with latest `stable`, your `flutter run --verbose` with issue and a minimal complete reproducible code sample.
Thank you

**Comment by iapicca** [comment] 2020-07-08 14:06
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-07-08 14:06 UTC
Labels: a: internationalization, a: text input, f: material design, framework

**Comment by MohibBhojani** [comment] 2020-10-09 13:11
facing same issue on text field using latest flutter version 1.22.1, I request flutter team kindly fix this issue

**Comment by iapicca** [comment] 2020-10-09 13:29
@MohibBhojani 
I recommend you to open a new issue provide the info mentioned [above](https://github.com/flutter/flutter/issues/59062#issuecomment-643191020)

> Can you please provide your `flutter doctor -v` with latest `stable`, your `flutter run --verbose` with issue and a minimal complete reproducible code sample.
> Thank you

**Comment by MohibBhojani** [comment] 2020-10-09 13:54
there are two fields in my app in one field it was working fine on other field it was not working fine then I put same properties on both field now it was working these three properties which I added to text field then my issue was resolve.

    keyboardType: TextInputType.multiline,
                            maxLines: null,
                            expands: true,

I add theses three Thank god it was working fine now I was facing this since 2 months
