### ISSUE TITLE
[google_maps_flutter] iOS TileOverlay stops loading tiles after backgrounding app (3.13+)

### ISSUE THREAD

**Issue by elitree** [flutter/flutter#135252] opened 2023-09-21 19:57 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the google_maps_flutter example app on an iOS device (compile against a 3.13 or higher flutter; this does not occur in 3.10) 
2. Select the Tile Overlay example
3. Click Add Tile Overlay
4. Scroll the map, and observe how the custom tiles are loaded as expected
5. Background the app (can just trigger multitasking partially, for example)
6. Scroll the map again
7. Note that no new overlay tiles are downloaded, and the only tiles shown are the ones pulled down in steps 3-4

### Expected results

As the user scrolls the map, custom TileOverlay tiles should continue to download and show whether or not the user has backgrounded the app yet.

### Actual results

As soon as the user backgrounds the app, no more custom TileOverlay tiles will download.

This issue does not occur when compiling against Flutter 3.10. It does not seem to occur on Android.

### Code sample

Reproduced using the example app in the packages repo: https://github.com/flutter/packages/tree/main/packages/google_maps_flutter/google_maps_flutter/example

### Screenshots or Video

The following was captured from an iPhone 11 running iOS 17.0. I also reproduced it on an iPad Pro running iPadOS 16.7.
<details>
<summary>Video demonstration</summary>

https://github.com/flutter/flutter/assets/602697/81a6820d-0d18-4369-933e-00bf1bb0acd8

</details>

### Logs

<details><summary>Logs</summary>

```console
❯ fvm flutter run -d 00008030-000E10513A38802E
Launching lib/main.dart on Eli iPhone in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Automatically signing iOS for device deployment using specified development team in Xcode project: 6L6G8SY9C6
Running pod install...                                             541ms
Running Xcode build...                                          
Xcode build done.                                            6.1s
Installing and launching...                                     
You may be prompted to give access to control Xcode. Flutter uses Xcode to run your app. If access is not allowed, you can change this through your Settings > Privacy & Security > Automation.
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
Installing and launching...                                        29.2s
Syncing files to device Eli iPhone...                               28ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Eli iPhone is available at: http://127.0.0.1:51754/guQumPzfAk4=/
The Flutter DevTools debugger and profiler on Eli iPhone is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:51754/guQumPzfAk4=/
[VERBOSE-2:shell.cc(1004)] The 'plugins.flutter.dev/google_maps_ios_0' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
...
```

Those ((null)) console messages begin once you start scrolling the map after backgrounding/foregrounding the app, and they keep generating after that point whenever you scroll the map again.
</details>

### Flutter Doctor output

The output below is for 3.13.3, but I've reproduced it with 3.13.5 as well. The issue does not occur with 3.10.7.

<details><summary>Doctor output</summary>

```console
❯ fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.13.3, on macOS 14.0 23A339 darwin-arm64, locale en-US)
    • Flutter version 3.13.3 on channel stable at /Users/eligeller/fvm/versions/3.13.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (2 weeks ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/eligeller/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (5 available)
    • Eli’s ReportAll iPhone (mobile) • 00008110-000611A60CD8401E • ios            • iOS 17.0 21A329
    • Eli iPhone (mobile)             • 00008030-000E10513A38802E • ios            • iOS 17.0 21A329
    • Eli’s iPad Pro (mobile)         • 00008103-001A203E26C3001E • ios            • iOS 16.7 20H19
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.0 23A339 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by elitree** [comment] 2023-09-21 20:09
Just an impact note... my team is OK to use the 3.10.7 release of Flutter as a workaround for now, but I really hope there's some fix or other workaround so that we can use the 3.13 releases, and reap the iOS performance gains there.

**Comment by elitree** [comment] 2023-11-02 20:07
Hi, just checking in. Any more details on this one? Thanks!

**Comment by elitree** [comment] 2023-11-16 19:10
No surprise here, but this isn't fixed in the newly stable Flutter 3.16.0. Our app is still back on 3.10.7 due to this iOS only issue. 

Any idea what layer of the stack the issue is occurring in? Anything I can help test? 

We're eager to move to a new Flutter, so if there's anything I can do to assist, Please ket me know! Thanks.

**Comment by ki113rtofu** [comment] 2023-12-05 15:31
any news on the issue?

**Comment by neetable-chollarasan** [comment] 2023-12-26 09:57
Any fix for this?

**Comment by stuartmorgan** [comment] 2024-01-22 20:47
> Anything I can help test?

Anyone is certainly welcome to help investigate. Bisecting to a specific revision on `master` where this started occurring would be one thing that could help narrow it down.

**Comment by martyfuhry** [comment] 2024-01-23 21:23
Thank you @stuartmorgan for the assistance. I ran bisected the `master` branch of Flutter down to this commit:

[1f09a8662dad3bb1959b24e9124e05e2b9dbff1d](https://github.com/flutter/engine/commit/1f09a8662dad3bb1959b24e9124e05e2b9dbff1d) is the first bad commit.

I see some references to Impeller here, including something about "wide gamut".

**Comment by martyfuhry** [comment] 2024-01-24 00:32
Sorry, it looks like I referenced the wrong repository in that link

[Here is the correct link to the breaking commit](https://github.com/flutter/flutter/commit/1f09a8662dad3bb1959b24e9124e05e2b9dbff1d)

[And here is the commit comparison](https://github.com/flutter/engine/compare/400a26ad8343...47fd496c6f8d) where I noticed Impeller and wide gamut.

**Comment by elitree** [comment] 2024-02-05 14:01
Good news… @martyfuhry remembered that [a build flag was added in 3.13 relating to the wide gamut setting.](https://medium.com/flutter/whats-new-in-flutter-3-10-b21db2c38c73) He was able to find that by setting the `FLTEnableWideGamut` flag to `false` in the `Info.plist` file (or in the Custom Build settings in Xcode), the observed issue no longer occurred.

We verified that with the flag set to false, we are able to use the latest stable Flutter (3.16.9) without encountering this bug in iOS anymore. So this will hopefully serve as a good workaround for us, letting us use the latest and greatest Flutter releases, until the underlying bug is addressed.

Thanks,
Eli

**Comment by stuartmorgan** [comment] 2024-02-06 17:27
Redirecting to the impeller team based on the above; cc @gaaclarke since it's related to wide gamut.

**Comment by gaaclarke** [comment] 2024-02-06 19:25
1) This example app in the "Tile Overlay" page never renders a map correctly
2) When disabling wide gamut the tile overlay appears to render correctly
3) With wide gamut enabled it never renders the overlay, instead issuing the following error logs when the "Add tile overlay" is pressed.

## versions
flutter
```
commit 37fd173e03f33081ae75828272ca4d63c18aec75 (HEAD, origin/master, origin/main, origin/HEAD)
Author: David Martos <davidmartos96@gmail.com>
Date:   Tue Feb 6 20:01:49 2024 +0100
```
packages
```
commit ef765f105069489dc8db93b568a00a043575f39f (HEAD -> main, upstream/main)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Feb 6 16:33:32 2024 +0000
```

## log
```
[ERROR:flutter/shell/common/shell.cc(1038)] The 'plugins.flutter.dev/google_maps_ios_0' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
((null)) was false: Don't support little endian bitmaps
((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
2024-02-06 11:06:35.334 Runner[35261/0x16f353000] [lvl=3] -[GMSx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
2024-02-06 11:06:35.871 Runner[35261/0x16f69b000] [lvl=3] -[GMSx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
2024-02-06 11:06:35.882 Runner[35261/0x16f69b000] [lvl=3] -[GMSx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
2024-02-06 11:06:36.018 Runner[35261/0x16f60f000] [lvl=3] -[GMSx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable
[connection] nw_connection_add_timestamp_locked_on_nw_queue [C1] Hit maximum timestamp count, will start dropping events
```

Those log messages about `bad graphics data` are not coming from Flutter engine or the plugin.  I suspect we are serving textures to the google maps plugin and it is making assumptions about the pixel format of those textures, assuming r8g8b8a8 instead of 16bit float values for example.  It's likely the fix is that the plugin will have to support wide gamut textures, we don't want to make all of our plugins forced to render poorly.  Another solution could be to add an option for compatibility.  We'll see after I spend more time looking into it.

**Comment by gaaclarke** [comment] 2024-02-06 20:34
If you run the example with a debug engine it will crash on thread safety violations when "Add tile overlay" is pressed. So there is some shenanigans outside of wide gamut:
```
[FATAL:flutter/fml/memory/weak_ptr.h(109)] Check failed: (checker_.checker).IsCreationThreadCurrent().
Thread 7 Queue : com.google.Maps.TileStart-sdkLayer_0x280f57480 (concurrent)
#0	0x00000001e9b51578 in __pthread_kill ()
#1	0x000000020a9e4118 in pthread_kill ()
#2	0x00000001b20b0178 in abort ()
#3	0x000000010e8d0bc0 in fml::KillProcess() at /Users/aaclarke/dev/engine/src/flutter/fml/logging.cc:230
#4	0x000000010e8d0b18 in fml::LogMessage::~LogMessage() at /Users/aaclarke/dev/engine/src/flutter/fml/logging.cc:217
#5	0x000000010e8d0bdc in fml::LogMessage::~LogMessage() at /Users/aaclarke/dev/engine/src/flutter/fml/logging.cc:143
#6	0x000000010dc61a78 in fml::WeakPtr<flutter::PlatformView>::CheckThreadSafety() const at /Users/aaclarke/dev/engine/src/flutter/fml/memory/weak_ptr.h:109
#7	0x000000010dc547a8 in fml::WeakPtr<flutter::PlatformView>::operator->() const at /Users/aaclarke/dev/engine/src/flutter/fml/memory/weak_ptr.h:99
#8	0x000000010dc5b724 in -[FlutterEngine sendOnChannel:message:binaryReply:] at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:1255
#9	0x000000010f918ef4 in -[FlutterBinaryMessengerRelay sendOnChannel:message:binaryReply:] at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/common/framework/Source/FlutterBinaryMessengerRelay.mm:34
#10	0x000000010f91d218 in -[FlutterMethodChannel invokeMethod:arguments:result:] at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/common/framework/Source/FlutterChannels.mm:294
#11	0x000000010226298c in -[FLTTileProviderController requestTileForX:y:zoom:receiver:] at /Users/aaclarke/.pub-cache/hosted/pub.dev/google_maps_flutter_ios-2.4.1/ios/Classes/FLTGoogleMapTileOverlayController.m:125
#12	0x000000010227f078 in -[GMSCustomTileService sendRequest:] ()
#13	0x000000010227f55c in -[GMSCustomTileService internalRequestTile:target:selector:allowNetworkFetch:] ()
#14	0x0000000103804520 in _dispatch_call_block_and_release ()
#15	0x0000000103806038 in _dispatch_client_callout ()
#16	0x00000001038092f4 in _dispatch_continuation_pop ()
#17	0x0000000103808404 in _dispatch_async_redirect_invoke ()
#18	0x000000010381a43c in _dispatch_root_queue_drain ()
#19	0x000000010381ae34 in _dispatch_worker_thread2 ()
#20	0x000000020a9ddda0 in _pthread_wqthread ()
```

**Comment by gaaclarke** [comment] 2024-02-06 21:36
I've confirmed that the bug is that the google maps plugin doesn't support wide gamut images.  The following patch fixes the problem by transforming the images to non-wide gamut images before serving them to the google maps plugin:

```diff
--- a/packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FLTGoogleMapTileOverlayController.m
+++ b/packages/google_maps_flutter/google_maps_flutter_ios/ios/Classes/FLTGoogleMapTileOverlayController.m
@@ -123,39 +123,49 @@
                    zoom:(NSUInteger)zoom
                receiver:(id<GMSTileReceiver>)receiver {
   dispatch_async(dispatch_get_main_queue(), ^{
-    [self.methodChannel invokeMethod:@"tileOverlay#getTile"
-        arguments:@{
-          @"tileOverlayId" : self.tileOverlayIdentifier,
-          @"x" : @(x),
-          @"y" : @(y),
-          @"zoom" : @(zoom)
-        }
-        result:^(id _Nullable result) {
-          UIImage *tileImage;
-          if ([result isKindOfClass:[NSDictionary class]]) {
-            FlutterStandardTypedData *typedData = (FlutterStandardTypedData *)result[@"data"];
-            if (typedData == nil) {
-              tileImage = kGMSTileLayerNoTile;
-            } else {
-              tileImage = [UIImage imageWithData:typedData.data];
-            }
-          } else {
-            if ([result isKindOfClass:[FlutterError class]]) {
-              FlutterError *error = (FlutterError *)result;
-              NSLog(@"Can't get tile: errorCode = %@, errorMessage = %@, details = %@",
-                    [error code], [error message], [error details]);
-            }
-            if ([result isKindOfClass:[FlutterMethodNotImplemented class]]) {
-              NSLog(@"Can't get tile: notImplemented");
-            }
-            tileImage = kGMSTileLayerNoTile;
-          }
-
-          [receiver receiveTileWithX:x y:y zoom:zoom image:tileImage];
-        }];
+    [self.methodChannel
+        invokeMethod:@"tileOverlay#getTile"
+           arguments:@{
+             @"tileOverlayId" : self.tileOverlayIdentifier,
+             @"x" : @(x),
+             @"y" : @(y),
+             @"zoom" : @(zoom)
+           }
+              result:^(id _Nullable result) {
+                UIImage *tileImage;
+                if ([result isKindOfClass:[NSDictionary class]]) {
+                  FlutterStandardTypedData *typedData = (FlutterStandardTypedData *)result[@"data"];
+                  if (typedData == nil) {
+                    tileImage = kGMSTileLayerNoTile;
+                  } else {
+                    tileImage = [UIImage imageWithData:typedData.data];
+                    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
+                    CGContextRef context = CGBitmapContextCreate(nil, tileImage.size.width, tileImage.size.height, 8, 0, colorSpace, kCGImageAlphaPremultipliedLast);
+                    CGContextDrawImage(context, CGRectMake(0, 0, tileImage.size.width, tileImage.size.height), tileImage.CGImage);
+                    CGImageRef image = CGBitmapContextCreateImage(context);
+                    tileImage = [UIImage imageWithCGImage:image];
+                    CGImageRelease(image);
+                    CGContextRelease(context);
+                    CGColorSpaceRelease(colorSpace);
+                  }
+                } else {
+                  if ([result isKindOfClass:[FlutterError class]]) {
+                    FlutterError *error = (FlutterError *)result;
+                    NSLog(@"Can't get tile: errorCode = %@, errorMessage = %@, details = %@",
+                          [error code], [error message], [error details]);
+                  }
+                  if ([result isKindOfClass:[FlutterMethodNotImplemented class]]) {
+                    NSLog(@"Can't get tile: notImplemented");
+                  }
+                  tileImage = kGMSTileLayerNoTile;
+                }
+
+                [receiver receiveTileWithX:x y:y zoom:zoom image:tileImage];
+              }];
   });
 }
 
+
 @end
 
 @interface FLTTileOverlaysController ()
```

I'll let the ecosystem team decide if they want to incur that cost or if they want to work with the google maps team to support wide gamut images ( @stuartmorgan ).

**Comment by stuartmorgan** [comment] 2024-02-09 15:05
> I'll let the ecosystem team decide if they want to incur that cost or if they want to work with the google maps team to support wide gamut images ( @stuartmorgan ).

It's ultimately the iOS team's call, but I would vote for us doing the conversion—or if there's a way the plugin client could reasonably do the conversion in Dart, maybe just document that in the README—until the underlying SDK supports it.

We should make sure we test with each version of the Google Maps SDK that we support to see if it's already fixed. @gaaclarke Which `ios*` version of the example app were you ultimately testing this in, and what version of `GoogleMaps` do you have in your `Podspec.lock` for that example?

**Comment by gaaclarke** [comment] 2024-02-09 17:15
> Which ios* version of the example app were you ultimately testing this in

I was using `//packages/google_maps_flutter/google_maps_flutter/example`

> and what version of GoogleMaps do you have in your Podspec.lock for that example?

I was at ef765f105069489dc8db93b568a00a043575f39f, GoogleMaps says `6.2.1`.

**Comment by stuartmorgan** [comment] 2024-02-09 17:19
That's the oldest version of `GoogleMaps` we support, so we should re-test with `google_maps_flutter_ios/example/ios14/` and see if the newest version still has the problem. If so we can follow up with an issue against the Google Maps iOS SDK. If not we can bisect the other `ios*` examples to see when it wide gamut support was added.

**Comment by jonahwilliams** [comment] 2024-02-12 19:04
@gaaclarke is this something you are going to keep pushing on? Does it need another assignee? This seems like an issue we need to get fixed.

**Comment by gaaclarke** [comment] 2024-02-12 19:10
> @gaaclarke is this something you are going to keep pushing on? Does it need another assignee? This seems like an issue we need to get fixed.

I've communicated the problem and handed it off to the iOS team ( @hellohuanlin ).  The plan is that they will follow up with the Google Maps team and decide the best course of action after that.

**Comment by jmagman** [comment] 2024-02-12 20:43
I checked on latest GoogleMaps 8.4.0 (iOS 14) and I the TileOverlays still do not load, and I see 
```
2024-02-12 12:11:55.406149-0800 Runner[4058:2457053] ((null)) was false: Don't support little endian bitmaps
2024-02-12 12:11:55.406202-0800 Runner[4058:2457053] ((null)) was false: Unable to create GMSImageRenderTile due to bad graphics data
```
We should:
1. File an issue with GoogleMaps to support wide gamut in the future.
2. Land @gaaclarke's workaround or similar since we won't be able to support the latest GoogleMaps for awhile (due to the iOS 14 minimum), even if they fixed it tomorrow.
3. Write a test that would have caught this.
https://github.com/flutter/packages/blob/6828aaaf488b2882be3eec7f367eabdebfda4aea/packages/google_maps_flutter/google_maps_flutter_ios/example/ios12/integration_test/google_maps_test.dart#L898

@hellohuanlin can you work on 2 and 3?  I will try to repro with a non-Flutter app and file the issue.

**Comment by jmagman** [comment] 2024-02-13 18:42
> File an issue with GoogleMaps to support wide gamut in the future.

b/325076777

**Comment by Velek** [comment] 2024-03-18 08:16
Disabling Impeller on iOS for my app and my layers are showing up.

**Closed** 2024-03-27 06:54 UTC
Labels: c: regression, platform-ios, a: platform-views, p: maps, package, has reproducible steps, P1, e: impeller, team-ios, triaged-ios, found in release: 3.13, found in release: 3.15

**Comment by LouiseHsu** [comment] 2024-03-27 17:12
This issue should be fixed now. Please let me know if you run into any issues!
