### ISSUE TITLE
Suggestion for adding limit when using pickMultiImage()

### ISSUE THREAD

**Issue by Adesanya-David** [flutter/flutter#150675] opened 2024-06-24 00:11 UTC
```
Future<List<XFile>> pickMultiImage(
      {double? maxWidth,
      double? maxHeight,
      int? imageQuality,
      bool requestFullMetadata = true,
      int? limit}) {
    final ImageOptions imageOptions = ImageOptions.createAndValidate(
      maxWidth: maxWidth,
      maxHeight: maxHeight,
      imageQuality: imageQuality,
      requestFullMetadata: requestFullMetadata,
    );

    return platform.getMultiImageWithOptions(
      options:
          MultiImagePickerOptions(imageOptions: imageOptions, limit: limit),
    );
  }
```
  
  This allows the user pass limit into pickMultiImage(limit: 5)

**Comment by stuartmorgan** [comment] 2024-06-24 10:00
Closing as a duplicate of https://github.com/flutter/flutter/issues/85772, which was already implemented. The current version of the plugin has a `limit` parameter.

**Closed by stuartmorgan** 2024-06-24 10:00 UTC
