### ISSUE TITLE
Feature 'select all' in SelectableText.rich not working when using TextAlign.justify

### ISSUE THREAD

**Issue by nguyenhieu283** [flutter/flutter#63157] opened 2020-08-07 02:31 UTC
## Steps to Reproduce

1. Run `flutter doctor`
2. Result:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.0, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

3. I create simple example using SelectableText.rich with TextSpan which has multiple InlineSpan as children. Everything work fine when not align text justify.
`return SelectableText.rich(
      span,
      textScaleFactor: textScale,
      textAlign: TextAlign.justify,
    );`
This is result i got: 

![Capture](https://user-images.githubusercontent.com/36096637/89602172-5ddee380-d890-11ea-9e3a-3d2288df463f.PNG)
 I think that is serious error and need to fix

**Comment by darshankawar** [comment] 2020-08-07 10:28
Hi @nguyenhieu283,
I tried to replicate it on latest Stable (1.20.1) and although I was able to replicate it with a code sample, I'd first like to confirm if what I've observed is indeed true. 
If your text inside `TextSpan` starts from a space and has a style to it, then only the `select all` with `justify` text align is not covering the entire text. For example, I tried below code sample:

```
body: Center(
        child: SelectableText.rich(
          TextSpan(
            text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', // default text style
            children: <TextSpan>[
              TextSpan(text: ' Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.'),
              TextSpan(text: 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.'),
            ],
          ),
          textScaleFactor: 1,
          textAlign: TextAlign.justify,
        )
      ),


```
Here if you see, inside first `TextSpan`, if the text starts with a space and has style to it, then `select all` is not working properly, but if you remove the space but keep style, it's working properly.

**Comment by nguyenhieu283** [comment] 2020-08-08 02:17
So useful. Thank for your support. But i think it should be update to handle this case work properly

**Comment by darshankawar** [comment] 2020-08-10 05:43
@nguyenhieu283 yes.
The issue occurs, ie, the `textAlign: justify` doesn't cover all text ie when we select `select all` when the first inline span (TextSpan) starts with a space and has a style to it, But if there's no space and has style, then the entire text is covered / selected properly.

**Comment by exaby73** [comment] 2022-11-15 13:09
I cannot reproduce this issue on `Master (3.6.0-3.0.pre.26)`. Closing this issue as fixed. If you disagree with my decision, please comment with a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and I can reopen it. Thank you.

<img width="300" src="https://user-images.githubusercontent.com/50555895/201927362-e3c9e4d4-7e61-4d43-8387-058a6fe67a94.png">

**Closed** 2022-11-15 13:09 UTC
Labels: framework, f: material design, a: typography, has reproducible steps, found in release: 1.20
