### ISSUE TITLE
NestedScrollView does not support a floating app bar

### ISSUE THREAD

**Issue by Steelsmasher** [flutter/flutter#17518] opened 2018-05-11 18:56 UTC
b/136489010

I want to make a floating app bar that's shared across multiple TabBarViews, so I used a NestedScrollView. I would expect the app bar to appear whenever I scroll up at any point of the page but it does not seem to do so?

**main.dart**
```dart
    import 'package:flutter/material.dart';

    void main() {

        Widget getPage(){
            return new ListView.builder(
                itemBuilder: ((context, index){
                    return new ListTile(
                        title: new Text('Item $index')
                    );
                }),
            );
        }

        runApp(
            new MaterialApp(
                home: new DefaultTabController(
                    length: 2,
                    child: new Scaffold(
                        body: new NestedScrollView(
                            headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
                                return <Widget>[
                                    new SliverAppBar(
                                        floating: true,
                                        bottom: new TabBar(
                                            tabs: [
                                                new Tab(text: 'tab1'),
                                                new Tab(text: 'tab2'),
                                            ],
                                        ),
                                    ),
                                ];
                            },
                            body: new TabBarView(
                                children: [
                                    getPage(),
                                    getPage(),
                                ],
                            ),
                        ),
                    ),
                ),
            ),
        );
    }
```

Strangely enough if "snap: true" is set for the SliverAppBar the desired effect is achieved. But I don't want it to snap.

Similar issue here: #11222

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 10.0.16299.431], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK 26.0.3)
[X] Android Studio (not installed)
[√] VS Code, 64-bit edition (version 1.23.0)
[!] Connected devices
    ! No devices available
! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment] 2018-05-14 06:41
Please add the output of `flutter doctor`

**Comment by Steelsmasher** [comment] 2018-05-14 13:09
Done.

**Comment by diegoveloper** [comment] 2018-06-02 06:58
same issue here

**Comment by allanwolski** [comment] 2018-06-02 16:12
Same issue here too.

**Comment by lidroider** [comment] 2018-06-19 03:41
same issue too.

**Comment by zoechi** [comment] 2018-06-19 04:11
@HansMuller

**Comment by allanwolski** [comment] 2018-08-25 03:41
any update on this problem?

**Comment by GerlanStanley** [comment] 2018-10-03 19:44
Same issue

**Comment by iambudi** [comment] 2018-10-07 22:56
+1

**Comment by allanwolski** [comment] 2018-10-30 03:02
Any chance of this fixed?

**Comment by aletorrado** [comment] 2018-12-07 19:42
+1

**Comment by diegoveloper** [comment] 2018-12-07 20:13
Maybe this can help you guys: https://medium.com/@diegoveloper/flutter-collapsing-toolbar-sliver-app-bar-14b858e87abe

**Comment by allanwolski** [comment] 2018-12-14 11:12
This is different than I need @diegoveloper.
I am trying to reproduce the same behavior as WhatsApp.

**Comment by zoechi** [comment] 2018-12-14 12:09
"me too" and "+1" comments are pointless. 
Instead use ![image](https://user-images.githubusercontent.com/405837/49718793-716d1d80-fc5b-11e8-8a7a-7288f578a66d.png) on the initial comment to upvote and increase priority.
Comments cause spammy notification mails sent to all subscribers.
If you want to get notified, use ![image](https://user-images.githubusercontent.com/405837/49718838-95306380-fc5b-11e8-8900-0d9173289cc8.png)

**Comment by workerbee22** [comment] 2019-01-12 04:01
I'm assuming @Steelsmasher you mean '...expect the app bar to **disappear** whenever I scroll up at any point ...' ?

If so I have the same issue, but copying your exact code, I had to use all of these on **SliverAppBar**:

floating: **true**,
pinned: **true**,
snap: **true**,

Then scrolling up the list in TabBarView results in the AppBar bit of the SliverAppBar to scroll off screen at the top, but the TabBar bit of the SliverAppBar persists at the top of the screen and will not scroll off screen. 
Scroll down and the AppBar bit of SliverAppBar scrolls back into view.

**Comment by themindstorm** [comment] 2019-03-14 10:23
@workerbee22 
But if you set all 3 to true (floating, pinned, and snap), the desired behaviour is achieved, but OP stated

> I don't want it to snap.

I think it's because snapping makes the SliverAppBar appear less smoothly? On apps like WhatsApp, we can see that the top bar appears smoothly, rather than snapping. I think a good example of snapping will be the Google Docs Android app, where the top bar snaps when we scroll up (it appears "unsmoothly")

@allanwolski 
Did you find a solution?

**Comment by allanwolski** [comment] 2019-03-15 13:38
No, waiting for the Flutter team to fix this.

**Comment by themindstorm** [comment] 2019-03-18 16:08
@allanwolski 
> No, waiting for the Flutter team to fix this.

Are you saying that it is currently impossible to implement layouts like [this](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1cx_CQC_pYOeAxmJAoEIjGnZNAWQzz-O1%2Ftabs-scrolling-1.mp4) and [this](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1s7cWxE-2f_70t7xemGBk9G6Uav7Z7c9C%2Ftabs-scrolling-2.mp4)? 

Both these videos have been taken from [Tabs - Material.io](https://material.io/design/components/tabs.html#behavior)

**Comment by aletorrado** [comment] 2019-05-09 15:00
Is there any work being made on this issue?

**Comment by themindstorm** [comment] 2019-05-11 07:26
@aletorrado 
Unfortunately, no (not yet, at least). 

Here are similar issues/questions:
https://stackoverflow.com/questions/55187332/flutter-tabbar-and-sliverappbar-that-hides-when-you-scroll-down
#29561

**Comment by willlarche** [comment] 2019-08-01 15:25
Internal bug mirror b/136489010

**Comment by rolurq** [comment] 2019-08-02 17:49
Is there any updates about this? I'm having the same issue the SliverAppBar in a nested scroll view is ignoring the floating argument completely, and I want it to float but not snap.

**Comment by sleeyax** [comment] 2019-08-09 15:41
It's super annoying that this is still an issue. Any progress on this?

**Comment by martinsedoo1** [comment] 2019-08-15 12:55
+1

**Comment by shamnex** [comment] 2019-09-13 10:11
Any hope on this?

**Comment by a9udn9u** [comment] 2019-10-05 05:25
@willlarche mind sharing the status of the internal bug? Most of us here don't have access to Flutter's internal issue tracker but we are all waiting for the fix, please don't leave us in the dark.

**Comment by Piinks** [comment] 2019-11-04 18:00
I think the first steps in solving this involve the changes proposed in #41235, which will make it possible to account for the inner scroll offset.
Currently, it seems to me that the floating persistent header is only informed by the outer scroll controller, which is why it does not know to float back in when the inner controller is scrolled.

**Comment by JoanSchi** [comment] 2019-12-07 09:06
On Github (contribution: iRbouh) a clear example can be found to use the floating appbar with TabBarView by using SliverOverlapAbsorber and SliverOverlapInjector for the notification.

Example:
- Title: iRbouh/Flutter - Hide SliverAppBar with TabBar on Scroll.dart
- Link: https://gist.github.com/iRbouh/219a81b3f2e32c3ef725972b45627f2e

Summary in a nut shell:

DefaultTabController -> NestedScrollView:
  -  headerSliverBuilder: **SliverOverlapAbsorber** -> SliverAppBar -> TabBar
  -  body: TabBarView -> CustomScrollView -> **SliverOverlapInjector** (first sliver child)

**Comment by themindstorm** [comment] 2020-01-24 02:52
@JoanSchi I tried that solution, but I was getting an issue with white space which I also commented there. 

I've put a gif of the issue in my repo too: https://github.com/themindstorm/flutter-autohide-tabbar-problem/blob/master/README.md

**Comment by JoanSchi** [comment] 2020-01-24 19:26
@themindstorm 

**cut out of view**
Do you use for each tabbarview a CustomScrollView with a slivers. If you do not want to use a list,  you can add your widget in a SliverToBoxAdapter. Example:

body: TabBarView : 
   - tab 1:  CustomScrollView 
             -> SliverOverlapInjector (first sliver child)
            ->  other slivers
   - tab 2:  CustomScrollView 
            -> SliverOverlapInjector (first sliver child) 
            -> _SliverToBoxAdapter -> Text('This is the second screen... ')_
  -  and so on

**bar is not smoothly**
I noticed also that the bar was not smoothly, I filled in a issue and purposed a solution: https://github.com/flutter/flutter/issues/47039 (Maybe it solves your issue too)

I found the boring flutter show: Slivers Explained - Making Dynamic Layouts, very helpfull to understand the  sliverbar and slivers in general: 
https://www.youtube.com/watch?v=Mz3kHQxBjGg

**Comment by jinteoh** [comment] 2020-03-02 23:37
> It's super annoying that this is still an issue. Any progress on this?

Any progress on this issue?

**Comment by heshaShawky** [comment] 2020-03-13 22:17
Me too, Any progress on this issue?


> > It's super annoying that this is still an issue. Any progress on this?
> 
> Any progress on this issue?

**Comment by ArsalanSavand** [comment] 2020-03-18 16:29
Any progress?

This is a need with Tabs also. Using tabs with slivers will cause tabs to lose their scroll position when switching between them.

**Comment by ArsalanSavand** [comment] 2020-03-18 16:40
Following this offical tutorial https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html
for NestedScrollView that supports TabBarView, will result in following issues:

1. As the description of this issue states, floating AppBar won't work. Meaning when you scroll up, it doesn't show the AppBar unless you use `snap: true` which it will work if you stop scrolling up.

2. When switching between tabs, scroll index won't be saved and it will scroll to top.

Please fix these issues, it's a very major feature and we are all greatful that it exists currently in Flutter, but it still has issues and there are no workarounds for it.

**Comment by heshaShawky** [comment] 2020-03-29 17:46
Are there any updates for a workaround about this?

**Comment by feinstein** [comment] 2020-05-17 05:06
I just want to add that in my case the `SliverAppBar` will only update it's size when I lift my finger from the scroll. Whatsapp will snap the App Bar whenever I scroll, it doesn't wait for me to lift my finger and stop scrolling completely.

**Comment by sunyatax** [comment] 2020-05-19 19:28
Any word on this? Would be great if efforts were being made to resolve this

**Comment by feinstein** [comment] 2020-05-19 19:36
It appears to be on the May 2020 Milestone.

**Comment by Piinks** [comment] 2020-06-03 20:30
Update on the milestone here: There is a PR open to close this issue (#57707), it is still going back and forth in review, anticipated to land soon. I have moved the milestone to June to remove from the overdue heap.

**Comment by ArsalanSavand** [comment] 2020-06-03 20:33
@Piinks That's a great news, thank you!

**Comment by kira1752** [comment] 2020-06-04 11:10
@Piinks I appreciate the good news. Thanks for fixing this issue 🥳🥳

**Comment by gsusI** [comment] 2020-06-04 11:12
Please use reactions (emojis) on @Piinks comment, instead of adding new comments. Every time you comment an email is sent to all the subscribers (which I believe are a lot of them). Thanks

**Comment by heshaShawky** [comment] 2020-06-08 03:18
is flutter 1.17.3 has the fix? or still in progress? I have opened the release 1.17.3 and no notes for what differences occurred.

Thanks for your efforts.

**Comment by Piinks** [comment] 2020-06-09 23:19
I have an update for y'all!!

https://github.com/flutter/flutter/pull/57707 proposed a way to support __floating__ and __floating-snapping__ `SliverAppBar`s in the `headerSliverBuilder` of the `NestedScrollView`.

Floating has been pretty easy to solve by adding a flag to `NestedScrollView`, `floatHeaderSlivers`. This flag just tells `NestedScrollView`'s scrolling coordinator to pass the scroll offset to the outer header slivers before the inner when scrolling back up. It actually makes it possible to create whatever floating header you like, without specifically using a `SliverAppBar`. :)

Supporting floating __and__ snapping though has proved challenging. The only way I have managed to get this to work required adding a flag that implemented some specific logic to the snap animation of the `SliverAppBar`. This non-generic solution is unfavorable. Other solutions that were tried included passing the inner position to the `SliverAppBar`, but this approach was also non-generic and unsuccessful as the `NestedScrollView` can dispose of inner scroll positions when changing tabs and can also have more than one inner position attached at a time.
There is more discussion about the snapping animation on https://github.com/flutter/flutter/pull/57707 .

I think we are going to move ahead with supporting the __floating__ `SliverAppBar`, but not the __floating-snapping__ `SliverAppBar`, documenting the later as a limitation instead.

The `NestedScrollView` will still be able to support _only_ snapping, as it does now, and the `flaotHeaderSlivers` flag will allow for floating only.

I am going to close https://github.com/flutter/flutter/pull/57707 to preserve the implementation of the initial proposal. I'll open a new PR shortly and link it after removing the snap logic I tried in the other PR.

**Closed** 2020-06-12 16:15 UTC
Labels: P3, a: annoyance, a: quality, customer: crowd, customer: quill (g3), f: material design, f: scrolling, found in release: 1.12, found in release: 1.17, found in release: 1.18, framework, has reproducible steps, waiting for PR to land (fixed)

**Comment by heshaShawky** [comment] 2020-07-20 05:02
it's not fixed yet and what remains not just the "floating and snapping simultaneously"

Please open another issue, for it's also resetting the scroll point to the previous active tab on all tabs, for example, I have a news app and scrolled to whatever on tab 1 ( Home ), Then I go to tab 2 ( videos let's say ) and I scrolled to whatever when I get back to tab 1 ( home ) you will see it's been back to the same offset as tab 2 ( Videos ).

**Comment by heshaShawky** [comment] 2020-07-20 05:09
**This issue still exists on the latest version not fixed yet** 

<img style="max-width: 50%" src="https://i.stack.imgur.com/ySuU1.gif">

**Comment by nsendhavdq** [comment] 2020-12-22 08:04
If anyone wants to refer to working code sample here it is -> https://dartpad.dev/0955dcf876ba24619b86d49ec50788cc?

**Comment by kaxp** [comment] 2020-12-22 08:05
If anyone wants to refer a working code sample, here it is -> https://dartpad.dev/0955dcf876ba24619b86d49ec50788cc?
