### ISSUE TITLE
Still unable to use flutter day six now trying seriously demotivated

### ISSUE THREAD

**Issue by flutternooob** [flutter/flutter#72210] opened 2020-12-12 21:36 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by iapicca** [comment] 2020-12-12 22:16
@flutternooob 
I'm sorry for your feelings, I can suggest you the [free course](https://www.udacity.com/course/build-native-mobile-apps-with-flutter--ud905) I got started with Flutter...

but this is `definitely not a bug` or a `feature request`
I recommend to close this "issue"

**Comment by flutternooob** [comment] 2020-12-12 22:19
> @flutternooob 
> 
> I'm sorry for your feelings, I can suggest you the [free course](https://www.udacity.com/course/build-native-mobile-apps-with-flutter--ud905) I got started with Flutter,
> 
> but this is `definitely not a bug` or a `feature request`
> 
> I recommend to close this "issue"

Hi sorry I'm new here and still not sure how everything works on here. 
I don't think the course will help as I can't even get in to use flutter I've not been able to write a line of code. In six days and following all instructions to the letter. Ive joined here to get some help with fixing whatever is wrong so i can start using it. I'm not sure where to post to find that.

**Comment by iapicca** [comment] 2020-12-12 22:32
@flutternooob 
this repository is meant to improve flutter with `bug report` of `feature requests`,
**not to provide assistance**

If you need assistance please follow the link `I want help writing my application` in the [new issue page](https://github.com/flutter/flutter/issues/new/choose)
or [slack channel](https://fluttercommunity.dev/joinslack)  
or [discord server](https://discord.gg/N7Yshp4) 
or [sub reddit](https://www.reddit.com/r/FlutterDev/)

**Comment by flutternooob** [comment] 2020-12-12 22:33
Ok thanks.

**Comment by flutternooob** [comment] 2020-12-12 22:36
How do I delete this thread?

**Closed** 2020-12-12 23:06 UTC
