### ISSUE TITLE
Add a way for manipulating FPS in startImageStream in camera plugin

### ISSUE THREAD

**Issue by av153k** [flutter/flutter#77235] opened 2021-03-04 09:36 UTC
## Use case

     An option to manipulate FPS in startImageStream of camera plugin. 

## Proposal

   `  I'm using Camera plugin for one of my projects which is based on Real time face detection from an Image stream. Everything is working good except that face detection is catching even the blurred images. So I'm basically looking for a way to manipulate FPS of the image stream because I don't need images at that exact FPS. A lower FPS would help me to get clear picture of a face to run the model on. `
 
P.S - This is my first issue report/feature request ever so I apologize if I haven't been able to explain what I wanted to say. If anything else required please let me know.

**Comment by darshankawar** [comment] 2021-03-04 11:06
@av153k 
There's similar issue describing your case, https://github.com/flutter/flutter/issues/54339.
Do you think that issue resemble yours ?

**Comment by av153k** [comment] 2021-03-04 11:26
@darshankawar Yes it does. Thanks for pointing this out.

**Comment by darshankawar** [comment] 2021-03-04 11:45
Closing this as duplicate of https://github.com/flutter/flutter/issues/54339. Please follow-up there for updates.

**Closed by darshankawar** 2021-03-04 11:45 UTC
Labels: in triage
