### ISSUE TITLE
ColorFiltered conflicts with iOS WKWebview

### ISSUE THREAD

**Issue by AbeiOS** [flutter/flutter#116340] opened 2022-12-01 13:26 UTC
ColorFiltered conflicts with iOS WKWebView.
When I use ColorFiltered to change my app to full gray, everything is fine on Android, but all iOS WKWebView on iOS is no longer visible, leaving pure gray.
This problem can be reproduced very well on webview_flutter. 

The following is the code I tested on webview_flutter example

```dart
void main() => runApp(ColorFiltered(colorFilter: ColorFilter.mode(Colors.grey, BlendMode.color), child: MaterialApp(home: WKWebViewExample())));
```

Expected results:
I expect iOS to display an application with gray filters like Android

Actual results:
In fact, WKWebView has become invisible and has become a solid color

<details>
<summary>Doctor</summary>

```
[✓] Flutter (Channel master, 3.0.0, on macOS 12.4 21F79 darwin-arm (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.0.0 at /Users/luffy/zcy_flutter_sdk_3_0_0
    • Upstream repository https://git.cai-inc.com/mobile-framework/flutter_sdk_3_0_0.git
    • Framework revision 7d07027cb7 (3 weeks ago), 2022-11-09 14:33:48 +0800
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/luffy/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/luffy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    •  A (mobile)     • 00008110-222123123123 • ios            • iOS 15.6.1 19G82
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.4 21F79 darwin-arm (Rosetta)
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by exaby73** [comment] 2022-12-01 13:42
## Triage report

I can reproduce this issue with `Master (3.6.0-13.0.pre.26)`.

<details>
<summary>Code Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    return ColorFiltered(
      colorFilter: const ColorFilter.mode(Colors.grey, BlendMode.color),
      child: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: const WebView(
          initialUrl: 'https://flutter.dev',
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>Screenshot</summary>

<img width="300" src="https://user-images.githubusercontent.com/50555895/205067858-5143b046-d637-4d15-b793-e88b84e84787.png">

</details>

**Comment by jmagman** [comment] 2022-12-01 18:43
@cyanglaz is this a duplicate of https://github.com/flutter/flutter/issues/39270?

**Comment by cyanglaz** [comment] 2022-12-01 19:07
> @cyanglaz is this a duplicate of #39270?

Yes, closing this as dup with https://github.com/flutter/flutter/issues/39270

**Closed by cyanglaz** 2022-12-01 19:07 UTC
Labels: platform-ios, plugin, p: first party, p: webview, has reproducible steps, found in release: 3.3, found in release: 3.6

**Comment by AbeiOS** [comment] 2022-12-02 07:41
> ## Triage report

Thank you for your Triage report

**Comment by 86linksrain** [comment] 2022-12-02 07:49
+1....

**Comment by jmagman** [comment] 2022-12-02 19:19
This issue has been closed as a duplicate of another issue. Please follow https://github.com/flutter/flutter/issues/39270 for progress.
