### ISSUE TITLE
[Android][Bluetooth Keyboard] The software keyboard repeatedly opens and closes while typing with bluetooth keyboard.

### ISSUE THREAD

**Issue by tony-soft** [flutter/flutter#95697] opened 2021-12-22 22:23 UTC
The software keyboard is repeatedly open and close when I type characters with bluetooth keyboard.
I have Samsung Galaxy S20 and iPhone 11, and the problem is only appears in Galaxy S20.
I'm not sure other Android devices have the same issue.
This problem was produced after 2.2.1. (No problems in 2.2.1)

## Steps to Reproduce

1. Tap a TextField in your app.
2. Type some characters with your bluetooth keyboard.
3. The software keyboard will be open and closed repeatedly.

**Expected results:** 
The software keyboard must not be opened when I typing characters with bluetooth keyboard.

**Actual results:**
The software keyboard repeatedly open and close.

<details>
<summary>Code sample</summary>

```dart
Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: SingleChildScrollView(
        child: Center(
          child: Column(
            children: [
              TextField(
                decoration: InputDecoration(labelText: "TextField"),
              ),
            ],
          ),
        ),
      ),
    )
```

</details>

<details>
  <summary>Logs</summary>

```
I/ViewRootImpl@28cbda1[MainActivity](14072): setInTouchMode(false), android.view.ViewRootImpl.checkForLeavingTouchModeAndConsume:8700 android.view.ViewRootImpl.access$3100:256 android.view.ViewRootImpl$EarlyPostImeInputStage.processKeyEvent:7038 android.view.ViewRootImpl$EarlyPostImeInputStage.onProcess:7022 android.view.ViewRootImpl$InputStage.deliver:6595 android.view.ViewRootImpl$InputStage.onDeliverToNext:6652 android.view.ViewRootImpl$InputStage.forward:6618 android.view.ViewRootImpl$AsyncInputStage.forward:6819 android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent:7007 android.view.inputmethod.InputMethodManager$PendingEvent.run:3624 
I/ViewRootImpl@28cbda1[MainActivity](14072): ViewPostIme key 0
D/InputMethodManager(14072): SSI - flag : 0 Pid : 14072 view : com.example.example
D/InputMethodManager(14072): view is not EditText
D/InputMethodManager(14072): prepareNavigationBarInfo() DecorView@d8b0425[MainActivity]
D/InputMethodManager(14072): getNavigationBarColor() -855310
D/InputConnectionAdaptor(14072): The input method toggled cursor monitoring on
D/InsetsSourceConsumer(14072): setRequestedVisible: visible=true, type=13, host=com.example.example/com.example.example.MainActivity, from=android.view.InsetsSourceConsumer.show:229 android.view.InsetsController.showDirectly:1437 android.view.InsetsController.controlAnimationUnchecked:1110 android.view.InsetsController.applyAnimation:1417 android.view.InsetsController.show:962 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6146 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 android.app.ActivityThread.main:8633 java.lang.reflect.Method.invoke:-2 
I/ViewRootImpl@28cbda1[MainActivity](14072): ViewPostIme key 1
I/SurfaceControl(14072): nativeRelease nativeObject s[-5476376631332933760]
I/SurfaceControl(14072): nativeRelease nativeObject e[-5476376631332933760]
I/ViewRootImpl@28cbda1[MainActivity](14072): ViewPostIme key 0
D/InsetsSourceConsumer(14072): setRequestedVisible: visible=false, type=13, host=com.example.example/com.example.example.MainActivity, from=android.view.InsetsSourceConsumer.hide:236 android.view.ImeInsetsSourceConsumer.hide:101 android.view.InsetsController.hideDirectly:1430 android.view.InsetsController.controlAnimationUnchecked:1112 android.view.InsetsController.applyAnimation:1417 android.view.InsetsController.hide:984 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6150 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 android.app.ActivityThread.main:8633 
D/InputMethodManager(14072): SSI - flag : 0 Pid : 14072 view : com.example.example
D/InputMethodManager(14072): view is not EditText
D/InputMethodManager(14072): prepareNavigationBarInfo() DecorView@d8b0425[MainActivity]
D/InputMethodManager(14072): getNavigationBarColor() -855310
D/InputConnectionAdaptor(14072): The input method toggled cursor monitoring off
D/InputConnectionAdaptor(14072): The input method toggled cursor monitoring on
D/InsetsSourceConsumer(14072): setRequestedVisible: visible=true, type=13, host=com.example.example/com.example.example.MainActivity, from=android.view.InsetsSourceConsumer.show:229 android.view.InsetsController.showDirectly:1437 android.view.InsetsController.controlAnimationUnchecked:1110 android.view.InsetsController.applyAnimation:1417 android.view.InsetsController.show:962 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6146 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 android.app.ActivityThread.main:8633 java.lang.reflect.Method.invoke:-2 
I/SurfaceControl(14072): nativeRelease nativeObject s[-5476376631332875328]
I/SurfaceControl(14072): nativeRelease nativeObject e[-5476376631332875328]
I/ViewRootImpl@28cbda1[MainActivity](14072): ViewPostIme key 1
I/SurfaceControl(14072): nativeRelease nativeObject s[-5476376631332903136]
I/SurfaceControl(14072): nativeRelease nativeObject e[-5476376631332903136]

```

```
Analyzing ts_text_field...                                      

   info • Unused import: 'package:ts_text_field/ts_text_field.dart' • example/lib/main.dart:2:8 • unused_import
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:203:27 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:204:26 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:205:35 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:206:28 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:207:28 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:210:34 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:211:37 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:212:43 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:213:25 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:214:26 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:215:22 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:216:28 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:217:38 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:218:37 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:219:38 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:220:37 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:221:36 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:222:26 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:229:24 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:235:26 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:236:39 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:237:30 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:238:34 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:239:31 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:240:29 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:241:46 • unnecessary_null_comparison
   info • 'textEditingValue' is deprecated and shouldn't be used. Use the userUpdateTextEditingValue instead. This feature was deprecated after v1.26.0-17.2.pre. • lib/src/ts_editable_text.dart:1326:5 • deprecated_member_use
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:2381:28 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:2400:19 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:2688:30 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_editable_text.dart:2689:39 • unnecessary_null_comparison
   info • 'maxLengthEnforced' is deprecated and shouldn't be used. Use maxLengthEnforcement parameter which provides more specific behavior related to the maxLength limit. This feature was deprecated after v1.25.0-5.0.pre. • lib/src/ts_text_field.dart:250:11 • deprecated_member_use_from_same_package
   info • 'maxLengthEnforced' is deprecated and shouldn't be used. Use maxLengthEnforcement parameter which provides more specific behavior related to the maxLength limit. This feature was deprecated after v1.25.0-5.0.pre. • lib/src/ts_text_field.dart:263:8 • deprecated_member_use_from_same_package
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:331:26 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:332:25 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:333:26 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:334:35 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:335:28 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:336:28 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:339:34 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:340:43 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:341:34 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:346:30 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:347:34 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:348:37 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:349:36 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:356:24 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:368:29 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_field.dart:369:46 • unnecessary_null_comparison
   info • 'maxLengthEnforced' is deprecated and shouldn't be used. Use maxLengthEnforcement parameter which provides more specific behavior related to the maxLength limit. This feature was deprecated after v1.25.0-5.0.pre. • lib/src/ts_text_field.dart:544:11 • deprecated_member_use_from_same_package
   info • 'maxLengthEnforced' is deprecated and shouldn't be used. Use maxLengthEnforcement parameter which provides more specific behavior related to the maxLength limit. This feature was deprecated after v1.25.0-5.0.pre. • lib/src/ts_text_field.dart:794:61 • deprecated_member_use_from_same_package
   info • 'maxLengthEnforced' is deprecated and shouldn't be used. Use maxLengthEnforcement parameter which provides more specific behavior related to the maxLength limit. This feature was deprecated after v1.25.0-5.0.pre. • lib/src/ts_text_field.dart:1106:46 • deprecated_member_use_from_same_package
   info • 'maxLengthEnforced' is deprecated and shouldn't be used. Use maxLengthEnforcement parameter which provides more specific behavior related to the maxLength limit. This feature was deprecated after v1.25.0-5.0.pre. • lib/src/ts_text_field.dart:1272:16 • deprecated_member_use_from_same_package
   info • The import of 'package:flutter/widgets.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/material.dart' • lib/src/ts_text_form_field.dart:7:8 • unnecessary_import
   info • Using the 'new' keyword in a comment reference is deprecated • lib/src/ts_text_form_field.dart:93:12 • deprecated_new_in_comment_reference
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:153:26 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:154:26 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:155:25 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:156:35 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:157:28 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:158:28 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:159:34 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:160:34 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:165:30 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:172:24 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:179:43 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_form_field.dart:180:46 • unnecessary_null_comparison
   info • 'maxLengthEnforced' is deprecated and shouldn't be used. Use maxLengthEnforcement parameter which provides more specific behavior related to the maxLength limit. This feature was deprecated after v1.25.0-5.0.pre. • lib/src/ts_text_form_field.dart:224:17 • deprecated_member_use_from_same_package
   info • Unused import: 'dart:async' • lib/src/ts_text_selection.dart:5:8 • unused_import
   info • Unused import: 'dart:math' • lib/src/ts_text_selection.dart:6:8 • unused_import
   info • Unused import: 'package:characters/characters.dart' • lib/src/ts_text_selection.dart:8:8 • unused_import
   info • The import of 'package:flutter/foundation.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/widgets.dart' • lib/src/ts_text_selection.dart:9:8 • unnecessary_import
   info • Unused import: 'package:flutter/scheduler.dart' • lib/src/ts_text_selection.dart:12:8 • unused_import
   info • The import of 'package:flutter/services.dart' is unnecessary because all of the used elements are also provided by the import of 'package:flutter/widgets.dart' • lib/src/ts_text_selection.dart:13:8 • unnecessary_import
   info • Unused import: 'constant.dart' • lib/src/ts_text_selection.dart:16:8 • unused_import
   info • The operand can't be null, so the condition is always true • lib/src/ts_text_selection.dart:71:24 • unnecessary_null_comparison
   info • Unused import: 'package:flutter_test/flutter_test.dart' • test/ts_text_field_test.dart:1:8 • unused_import
   info • Unused import: 'package:ts_text_field/src/ts_text_field.dart' • test/ts_text_field_test.dart:3:8 • unused_import

79 issues found. (ran in 2.0s)

```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale ko-KR)
    • Flutter version 2.8.1 at /Users/dongsoo/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/dongsoo/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM G981N (mobile) • 192.168.219.101:5555 • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome               • web-javascript • Google Chrome 96.0.4664.110

! Doctor found issues in 1 category.
```

</details>

https://user-images.githubusercontent.com/70277412/147161506-97dd569c-0cc7-48a4-a2ea-ca714023490b.mp4

**Comment by darshankawar** [comment] 2021-12-23 07:42
Verified this using Samsung S10 device on master and stable and do see the same behavior. The soft keyboard opens and closes repeatedly while typing using bluetooth keyboard, as shown below:


The same behavior doesn't occur on Samsung Galaxy A2Core device (OS 8, api 19) wherein, the soft keyboard doesn't open while typing using bluetooth keyboard.

<details>
<summary> master and stable flutter doctor -v </summary>

```
[√] Flutter (Channel master, 2.9.0-1.0.pre.145, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
    • Flutter version 2.9.0-1.0.pre.145 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 209d316b4b (2 days ago), 2021-12-21 02:59:21 -0500
    • Engine revision 202e4a6d16
    • Dart version 2.16.0 (build 2.16.0-123.0.dev)
    • DevTools version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.62.3)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Windows (desktop)       • windows     • windows-x64     • Microsoft Windows [Version 10.0.19042.1415]
    • Windows (UWP) (desktop) • winuwp      • windows-uwp-x64 •
    • Chrome (web)            • chrome      • web-javascript  • Google Chrome 96.0.4664.110
    • Edge (web)              • edge        • web-javascript  • Microsoft Edge 96.0.1054.62

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
    • Flutter version 2.8.1 at D:\FlutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (8 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.1

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Win\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.0)
    • VS Code at C:\Users\Win\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.27.0

[√] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Windows (desktop)       • windows     • windows-x64     • Microsoft Windows [Version 10.0.19042.1415]
    • Windows (UWP) (desktop) • winuwp      • windows-uwp-x64 •
    • Chrome (web)            • chrome      • web-javascript  • Google Chrome 96.0.4664.110
    • Edge (web)              • edge        • web-javascript  • Microsoft Edge 96.0.1054.62

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-12-23 08:50
duplicate of https://github.com/flutter/flutter/issues/70546

**Closed by TahaTesser** 2021-12-23 08:50 UTC
Labels: a: text input, e: device-specific, platform-android, engine, has reproducible steps, found in release: 2.8, found in release: 2.9
