### ISSUE TITLE
Massive iOS App Size avoidable via non-bitcode debug framework. 

### ISSUE THREAD

**Issue by KritantaDev** [flutter/flutter#56325] opened 2020-05-04 20:22 UTC
## The Problem

I’m currently maintaining an old dead application *for iOS* and when upgrading from ancient frameworks, realized the output file size jumped from 12MB to about 500MB. 

After chatting with some developers who are familiar with this project, and after some static analysis due to confusion, it seems to me that the reason for the very large size is Flutter.framework being composed almost entirely of LLVM bitcode generated for the App Store. 

After thorough research on that topic it’s become clear to me that this size issue can be mitigated, **and should be,**for the following reasons:

- Poor routers, such as mine, mean debug builds can take upwards of 10 minutes to install, due to slow transfer.
- A portion of your community, including myself, has no intention of submitting created apps to the App Store. 

## I would like to propose the following non-destructive changes:
- Adding a phase to the Flutter.framework build process that allows creation of Flutter.framework for iOS without bitcode. 
 
- Bundling the generated, much smaller, library labeled as a “Debug” framework. 

- Linking the “debug” framework whenever a debug build is initiated, instead of the large one. 

- Potentially: allowing a method of using the debug framework when creating release builds.  

I apologize if this feature request is misinformed. It’s been very  difficult for me to find accurate information about Flutter on the topic. 

While this is a minor issue for most developers, the changes specified here would allow a performance increase for all users, and it would make it possible for me to rely on flutter without having to use several Mach-O tools by hand to manually remove a massive unneeded portion of the the framework.

**Comment by KritantaDev** [comment] 2020-05-04 20:24
I would like to add as a P.S. that although, I’m assuming given the determination, I could compile Flutter without bitcode, that solution does not work for developers targeting the App Store.

**Comment by timsneath** [comment] 2020-05-10 01:16
Related: https://github.com/flutter/flutter/issues/46707

**Comment by jmagman** [comment] 2020-06-29 18:46
This was probably a duplicate of https://github.com/flutter/flutter/issues/56750 considering the timing, though it's impossible to know since we didn't get the template `flutter doctor -v` output.  It was a pretty narrow few builds where this happened, if I recall.

Can you confirm your debug builds aren't that large on the current stable version?

**Comment by jmagman** [comment] 2020-06-29 18:47
Closing, let us know if it's still happening and we'll reopen and investigate.

**Closed by jmagman** 2020-06-29 18:47 UTC
Labels: a: build, a: size, engine, platform-ios, proposal, severe: new feature, tool, waiting for customer response
