### ISSUE TITLE
Flutter beta channel appears to cause problems with firebase_auth and cloud_firestore

### ISSUE THREAD

**Issue by wrpeck** [flutter/flutter#141812] opened 2024-01-18 23:07 UTC
### Steps to reproduce

1. `flutter create new_project && cd new_project`
2. `flutter channel beta && flutter upgrade`
3. `flutter pub add firebase_core`
4. `flutter pub add firebase_auth`
5. `flutter pub add cloud_firestore`
6. `flutter build apk --multidex` - error is thrown at this stage

### Expected results

Flutter should generate the APK. 

### Actual results

An error is thrown:

```
Note: /Users/{user}/.pub-cache/hosted/pub.dev/cloud_firestore-4.14.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/{user}/{project_path}/new_project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:24: error: package io.flutter.plugins.firebase.auth does not exist
      flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin());
                                                                         ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Running Gradle task 'assembleRelease'...                           21.5s
Gradle task assembleRelease failed with exit code 1
```

### Code sample

There are no changes to the boilerplate project here - only to `pubspec.yaml`. 

<details open><summary>Code sample</summary>

```yaml
name: new_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.0.dev <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

https://pastebin.com/2C62Gp2v

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel beta, 3.19.0-0.2.pre, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
    • Flutter version 3.19.0-0.2.pre on channel beta at /Users/wesleypeck/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c1df7d07ac (23 hours ago), 2024-01-17 15:42:07 -0800
    • Engine revision 4f18bb4dcb
    • Dart version 3.3.0 (build 3.3.0-279.0.dev)
    • DevTools version 2.31.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/wesleypeck/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34)
      (emulator)
    • iPhone 15 Pro Max (mobile)  • 4ACF8B00-D846-4559-8DE4-080E154E114F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.2.1 23C71
      darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome
      120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by brain0verfl0w** [comment] 2024-01-21 16:53
I recently ran into a similar issue after migrating an existing project from stable `3.16` to `3.19.0-0.2.pre`.
I installed the `image_picker` package and got a similar error:

```
...android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:29: error: package io.flutter.plugins.imagepicker does not exist
      flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
```

After some investigation, I tried to change the `distributionUrl` value in `gradle-wrapper.properties` from 
`https\://services.gradle.org/distributions/gradle-7.5-all.zip` to 
`https\://services.gradle.org/distributions/gradle-7.6.3-all.zip`.

At that point, all other installed plugins started to show the same error.

Strangely, reverting the `distributionUrl` back to `https\://services.gradle.org/distributions/gradle-7.5-all.zip` resulted in a successful build. Now the build process no longer shows any errors.

**Comment by danagbemava-nc** [comment] 2024-01-26 07:15
I could not reproduce this using any of the steps outlined above, but since this has been reproduced in https://github.com/flutter/flutter/issues/141940 I'll be closing this in favor of the original issue. 

Kindly subscribe to the issue for updates and if you have any additional information that may be useful, kindly share it over there as well. 

Thank you

**Closed by danagbemava-nc** 2024-01-26 07:15 UTC
Labels: waiting for customer response, in triage
