### ISSUE TITLE
Fluent UI Support

### ISSUE THREAD

**Issue by msyagami** [flutter/flutter#68938] opened 2020-10-24 04:56 UTC
## Use case

It would be nice if there was a widget catalog like [Cupertino](https://flutter.dev/docs/development/ui/widgets/cupertino) for Fluent UI. (since Flutter supports Windows development, and Fluent UI also supports [cross platform](https://www.microsoft.com/design/fluent/#/crossplatform).)
Microsoft has Fluent UI icons on [pub.dev](https://pub.dev/packages/fluentui_system_icons).

## Proposal

Implementing a Windows-like/Fluent UI-like widget(s) for Flutter.

**Comment by stuartmorgan** [comment] 2020-10-24 18:35
Duplicate of https://github.com/flutter/flutter/issues/46481

**Closed by stuartmorgan** 2020-10-24 18:35 UTC
