### ISSUE TITLE
iOS14 home screen widgets

### ISSUE THREAD

**Issue by edwin-alvarez** [flutter/flutter#60090] opened 2020-06-23 12:36 UTC
a fluter native way to implement this, will be a great new widget. Can you guys check it out:

https://9to5mac.com/2020/06/22/how-to-use-iphone-home-screen-widgets-ios-14/

**Comment by Zazo032** [comment] 2020-06-23 13:35
Duplicate of https://github.com/flutter/flutter/issues/60026

**Closed** 2020-06-23 14:44 UTC
