### ISSUE TITLE
TextEditingController.value fails on macOS

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#96372] opened 2022-01-09 22:29 UTC
I can update terminalController via `.text` but not via `value`, which I kind of need to be able to select the last character.

How to reproduce:
- Get the sample.
- Select the TextField
- Press key arrowUp in the keyboard. It should set 'Bernardo'. Nothing happens.

https://user-images.githubusercontent.com/351125/148703649-5ae9888b-df8e-4db2-85ff-57ac65c2b40a.mov

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      home: const KeyboardA(),
    );
  }
}

class KeyboardA extends StatefulWidget {
  const KeyboardA({Key? key}) : super(key: key);

  @override
  _KeyboardAState createState() => _KeyboardAState();
}

class _KeyboardAState extends State<KeyboardA> {
  late final terminalController = TextEditingController(text: 'default');
  late final terminalFocusNode = FocusNode();
  late final rawFocusNode = FocusNode();
  final inputs = ['a', 'b', 'c'];

  @override
  void dispose() {
    terminalController.dispose();
    terminalFocusNode.dispose();
    rawFocusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: RawKeyboardListener(
        onKey: (event) {
          // Only taking key down event into consideration
          if (event.runtimeType == RawKeyDownEvent) {
            if (event.logicalKey == LogicalKeyboardKey.arrowUp) {
              setState(() {
                terminalController.value = terminalController.value.copyWith(
                    text: 'bernardo',
                    selection:
                        TextSelection.collapsed(offset: 'bernardo'.length - 1));
                print("selection is ${terminalController.value}");
              });
            }
          }
        },
        focusNode: rawFocusNode,
        child: Center(
          child: TextFormField(
            controller: terminalController,
            textAlignVertical: TextAlignVertical.center,
            focusNode: terminalFocusNode,
            onFieldSubmitted: (value) {
              terminalController.clear();
              terminalFocusNode.requestFocus();
            },
          ),
        ),
      ),
    );
  }
}
```

```
➜ flutter doctor -v
[✓] Flutter (Channel beta, 2.9.0-0.1.pre, on macOS 11.4 20F71 darwin-x64, locale
    en-BR)
    • Flutter version 2.9.0-0.1.pre at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8f1f9c10f0 (4 weeks ago), 2021-12-14 13:41:48 -0800
    • Engine revision 234aca678a
    • Dart version 2.16.0 (build 2.16.0-80.1.beta)
    • DevTools version 2.9.1
```

**Comment by bernaferrari** [comment] 2022-01-09 22:32
cc @dkwingsmt. Could you please take a look here when you have some time? Not sure if it is exactly your area, but it might be.

**Comment by danagbemava-nc** [comment] 2022-01-11 06:56
Issue is reproducible using code sample provided above.

## Observations 
1.  This appears to be a regression as it works just fine on stable channel
2. This works just fine on the web
3. If I use a FAB to update the text, it works as expected. 
4. The value is updated in `TextEditingValue`, but somehow it doesn't make its way to the `TextField`.

<details>
<summary>videos</summary>

| master 2.9.0-1.0.pre.316 | web |  stable 2.8.1 |
| -- | -- | -- |
<video src="https://user-images.githubusercontent.com/88313112/148894641-4d721024-042f-494c-ac00-25f067cf503d.mov" /> |  <video src="https://user-images.githubusercontent.com/88313112/148894849-46f72163-df06-4c19-a3fb-e158dc71281f.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/148895080-75e3a765-71dd-4b0e-ab93-5d153155d163.mov" /> |


</details>

<details>
<summary>code sample</summary>

```dart
// ignore_for_file: avoid_print

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      home: const KeyboardA(),
    );
  }
}

class KeyboardA extends StatefulWidget {
  const KeyboardA({Key? key}) : super(key: key);

  @override
  _KeyboardAState createState() => _KeyboardAState();
}

class _KeyboardAState extends State<KeyboardA> {
  late final terminalController = TextEditingController(text: 'default');
  late final terminalFocusNode = FocusNode();
  late final rawFocusNode = FocusNode();
  final inputs = ['a', 'b', 'c'];

  @override
  void dispose() {
    terminalController.dispose();
    terminalFocusNode.dispose();
    rawFocusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: RawKeyboardListener(
        onKey: (event) {
          // Only taking key down event into consideration
          if (event.runtimeType == RawKeyDownEvent) {
            if (event.logicalKey == LogicalKeyboardKey.arrowUp) {
              setState(() {
                terminalController.value = terminalController.value.copyWith(
                  text: 'bernardo',
                  selection: const TextSelection.collapsed(
                      offset: 'bernardo'.length - 1),
                );
              });
              print(
                  "+=====================ARROWUP====================================+");
              print("selection is ${terminalController.value}");
              print(
                  "+=========================================================+");
            }
          }
        },
        focusNode: rawFocusNode,
        child: Center(
          child: TextFormField(
            controller: terminalController,
            focusNode: terminalFocusNode,
            onFieldSubmitted: (value) {
              terminalController.clear();
              terminalFocusNode.requestFocus();
            },
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            terminalController.value = terminalController.value.copyWith(
              text: 'bernardo',
              selection:
                  const TextSelection.collapsed(offset: 'bernardo'.length - 1),
            );
          });
          print(
              "+=====================FAB====================================+");
          print("selection is ${terminalController.value}");
          print("+=========================================================+");
        },
        child: const Icon(Icons.arrow_upward),
      ),
    );
  }
}

```
</details>

<details>
<summary> flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:318:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1428:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1863:10)
      #15     runZonedGuarded (dart:async/zone.dart:1851:12)
      #16     runZoned (dart:async/zone.dart:1782:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:197:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:301:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:53:47)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1290:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.9.0-1.0.pre.316, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.316 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 79025d4567 (2 hours ago), 2022-01-10 23:40:18 -0500
    • Engine revision b5a9cfd537
    • Dart version 2.16.0 (build 2.16.0-149.0.dev)
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.71

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by HansMuller** [comment] 2022-01-11 16:54
CC @justinmc

**Comment by justinmc** [comment] 2022-01-11 21:36
The up arrow is being handled by Flutter's keyboard Shortcut system at the same time that you are updating the controller's value, so there's a bit of a race condition, and the Shortcut essentially wins.  You can fix this by disabling that Shortcut (or even better, if it works for you, you can use Shortcuts instead of RawKeyboardListener).

<details>

<summary>Working example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      home: const KeyboardA(),
    );
  }
}

class KeyboardA extends StatefulWidget {
  const KeyboardA({Key? key}) : super(key: key);

  @override
  _KeyboardAState createState() => _KeyboardAState();
}

class _KeyboardAState extends State<KeyboardA> {
  late final terminalController = TextEditingController(text: 'default');
  late final terminalFocusNode = FocusNode();
  late final rawFocusNode = FocusNode();
  final inputs = ['a', 'b', 'c'];

  @override
  void dispose() {
    terminalController.dispose();
    terminalFocusNode.dispose();
    rawFocusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: RawKeyboardListener(
        onKey: (event) {
          // Only taking key down event into consideration
          if (event.runtimeType == RawKeyDownEvent) {
            if (event.logicalKey == LogicalKeyboardKey.arrowUp) {
              setState(() {
                terminalController.value = terminalController.value.copyWith(
                    text: 'bernardo',
                    selection:
                        TextSelection.collapsed(offset: 'bernardo'.length - 1));
              });
            }
          }
        },
        focusNode: rawFocusNode,
        child: Center(
          // HERE is the change you need to make to fix the original example!
          child: Shortcuts(
            shortcuts: <ShortcutActivator, Intent>{
              const SingleActivator(LogicalKeyboardKey.arrowUp): DoNothingIntent(),
            },
            child: TextFormField(
              controller: terminalController,
              textAlignVertical: TextAlignVertical.center,
              focusNode: terminalFocusNode,
              onFieldSubmitted: (value) {
                terminalController.clear();
                terminalFocusNode.requestFocus();
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

The root of the problem is that each frame only has the text metrics for the previous frame's text, so the handler for the up arrow can't figure out where to put the cursor in your new "bernardo" text unless it waits for the next frame.  Instead, it just uses last frame's text.  CC @LongCatIsLooong as we've run into this problem a lot.

The reason why this works on older versions of Flutter is that we recently implemented the Shortcuts system (before we were also using RawKeyboardListener)).

I'll go ahead and close this, but let me know if it still doesn't work or there's something we should fix.  Long term I would hope to have a better solution for this race condition.

**Closed by justinmc** 2022-01-11 21:36 UTC
Labels: a: text input, severe: regression, framework, f: material design, platform-mac, has reproducible steps, found in release: 2.9

**Comment by bernaferrari** [comment] 2022-01-11 23:47
That makes sense. I never thought about this, and happening on macOS only I thought it was a platform issue. Maybe a lint with `RawKeyboardListener` + `TextEditingController.value = ` could help people prevent this issue.

I just tried shortcuts (without raw listener) and it works perfectly. Thanks a lot. It took me a lot of time to get it working, but now it does! 🎉
