### ISSUE TITLE
[image_picker] (IOS 17) File path returned when taking a picture with camera do not exists

### ISSUE THREAD

**Issue by lmagniez-sd** [flutter/flutter#135493] opened 2023-09-26 09:12 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. On a IOS 17 device, and take a picture using the camera: `picker.pickImage(source: ImageSource.Camera)`
2. Get the picked file path and convert it to a File object: `File(pickedFile.path)`
3. The following exception is thrown: 
  `PathNotFoundException: Cannot open file, path ='/private/var/mobile/Containers...' (OS Error: No such file or directory, errno = 2)`

### Expected results

Returning the correct path when taking picture on a IOS 17 device

### Actual results

The following exception is thrown when trying to accessing to the file: 
`PathNotFoundException: Cannot open file, path ='/private/var/mobile/Containers...' (OS Error: No such file or directory, errno = 2)`

### Code sample

<details><summary>Code sample</summary>

```
final pickedFile = await picker.pickImage(
  source: ImageSource.camera,
);
if (pickedFile == null) return;
final file = File(pickedFile.path);
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
flutter: PathNotFoundException: Cannot open file, path = '/private/var/mobile/Containers/Data/Application/AAAAAA/tmp/image_picker_AAAAA.jpg' (OS Error: No such file or directory, errno = 2)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on macOS 13.6 22G120 darwin-arm64, locale en-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment] 2023-09-26 13:42
Hi @lmagniez-sd, I just tested the image_picker sample code and it worked as expected. From taking pictures to taking videos and selecting from gallery, all the features in the example app worked just fine. 

Could you provide a more complete reproducible code sample so that we can investigate this? Any other information you can provide would also be appreciated. 

Thank you

**Comment by lmagniez-sd** [comment] 2023-09-27 09:11
@danagbemava-nc 
Thank you for checking the matter on your side.
I also tried the image_picker example and found no problem on it.

After looking at the difference with our code we found that the fact we were deleting the tmp folder on the app start was the cause of the problem. 

Instead of deleting the entire folder, we opted to delete only the files contained in the folder instead. 
This way we were able to use the image_picker with no problem on IOS 17.

<details><summary>Tmp folder deletion sample code: </summary>

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  _cleanUpTemporaryDirectory();
  // ...
  runApp(const MyApp());
}

_cleanUpTemporaryDirectory() async {
  if (Platform.isIOS) {
    final documentsDirectory = await getApplicationDocumentsDirectory();
    documentsDirectory.parent.list().forEach((child) async {
      if (child is Directory && child.path.endsWith('/tmp')) {
        try {
          await child.delete(recursive: true);
        } on Exception catch (error) {
          debugPrint('Temp folder could not be deleted: $error');
        }
      }
    });
  }
   if (Platform.isAndroid) {
      // Delete tmp folder
   }
  }
```
</details>

**Comment by danagbemava-nc** [comment] 2023-09-28 06:31
Thanks for the update. 

I'll be closing this since the issue has been resolved on your end.

**Closed by danagbemava-nc** 2023-09-28 06:31 UTC
Labels: in triage
