### ISSUE TITLE
Questions about shader compilation

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#76100] opened 2021-02-16 09:13 UTC
Following the discussion in https://github.com/flutter/engine/pull/23914 I open this issue to have a better place to talk about how we can improve the performance of iOS Shaders.

Mainly I would like to understand 

* Why do we do the translation from SKSL to MSL in realtime for the shader. If we can't store them precompiled why can't we bundle the shaders in MSL?
* Why doesn't an optimisation run of the app that logs the used shaders not help for Metal? 

@dnfield @chinmaygarde @Hixie

**Comment by Hixie** [comment] 2021-02-18 04:43
@escamoteur Please please please follow good issue hygiene -- one topic per bug, bugs should have clear actionable steps to reproduce, and so on. GitHub issues aren't a good place for discussions or asking for help, etc.

So for example your first bullet point could be turned into an issue along the lines of "add documentation explaining how shaders work including why we do the translation from SKSL to MSL in realtime for the shader" and so forth (similar to https://github.com/flutter/flutter/issues/75311).

Just filing bugs like this will not get you the result you want because this is the wrong forum for discussions of this nature. If you just want to ask questions, we have a Discord for contributors such as yourself.

**Comment by escamoteur** [comment] 2021-02-18 10:20
@Hixie shure I can ask that on Discord. This is a topic that many people are interested in so I thought it might be easier to have this conversation where many can follow this thoughts. 
If there is an easy explanation to my questions then why not share them here so that people know that there are reasons why my maybe naive ideas won't work or won't bring much.

**Comment by escamoteur** [comment] 2021-02-18 10:25
I was hoping that discussing this topic with members of the community might help in finding solutions.

**Comment by aliakhtar** [comment] 2021-02-19 09:23
This seems like a discussion that should be held in the open, so everyone who might be able to contribute gets a chance to see it. Also so there's transparency.

If its held in a transient place like discord, there'll be no record of what was discussed, why certain decisions were made or not made.

**Comment by Hixie** [comment] 2021-02-20 04:13
Decisions will be recorded in design docs. We don't make decisions in discussions.

**Comment by Hixie** [comment] 2021-02-22 22:36
@escamoteur Would you mind filing separate bugs for the things you want documenting here? (e.g. the two bullet points in your original comment?)

**Comment by escamoteur** [comment] 2021-02-23 09:21
@Hixie does that makes sense? They are no real issues and it seems your team currently got into their think chambers if I read other issues correctly. If they have already thought about my questions before it doesn't seem to be of great value.

**Comment by Hixie** [comment] 2021-02-24 01:33
> * Why do we do the translation from SKSL to MSL in realtime for the shader. If we can't store them precompiled why can't we bundle the shaders in MSL?

I asked in Discord as suggested above. The answer is: SkSL->MSL isn't the expensive step of shader compilation, so this wouldn't meaningfully help.

> * Why doesn't an optimisation run of the app that logs the used shaders not help for Metal?

If I understand correctly, the answer is because the shaders are compiled by the driver, which is outside Flutter's control.

**Comment by escamoteur** [comment] 2021-02-24 08:14
Thanks @Hixie ok if the first one isn't expensive, that's fine, although it seems we could need every little bit performance.

>If I understand correctly, the answer is because the shaders are compiled by the driver, which is outside Flutter's control.
that doesn't really make sense to me why this speaks against an optimization run to determine which Shaders are used at all (that shouldn't be driver dependend) and then use that info to compile these shaders at the first startup of the iOS App. 
Also I didn't really understand what the problem with the caching of metal shaders is because they would be compiled on the installation device and you can load shader binaries.

**Comment by Hixie** [comment] 2021-02-25 06:32
Fundamentally, reducing the jank from 500ms to 250ms (or whatever) doesn't really help with the problem of there being jank. One you start skipping frames, it doesn't really matter that much how _many_ frames you're skipping.

That said, it does sound like there's some investigation going on around changing this to be a bit faster, just on general principles that as you say, faster is better.

What should the next step be for this bug?

**Comment by escamoteur** [comment] 2021-02-25 10:50
Still think the idea of precompiling the used shaders of an app may still make sense. Like on Android, but you can close this issue as it seems it won't bring much.
It might be worth to talk also to the Google folks working on web_gpu because they faced the same problem.

**Comment by Hixie** [comment] 2021-03-29 19:00
Shader warm-up is covered by https://github.com/flutter/flutter/issues/32170.

**Comment by nikitadol** [comment] 2021-04-30 17:16
In order to draw `BoxDecoration` in different versions, Flutter creates several shaders
Most developers use standard widgets (for example `BoxDecoration`), but with different configurations

What if we could create generic shaders for standard widgets that could compile on first run?
Or just the ability to write shaders for drawing widgets on the screen

**Comment by Hixie** [comment] 2021-05-03 22:40
@nikitadol If there are specific cases you're aware of, please file bugs for those cases. In general we're interested in reducing the number of shaders where that makes sense, but we need explicit test cases to [turn into SKPs](https://github.com/flutter/tests/tree/master/skp_generator) to make progress.

**Comment by Hixie** [comment] 2021-05-03 22:41
There doesn't seem to be anything actionable in this issue that isn't covered by existing bugs so I'm going to close it. Please don't hesitate to file a new issue if you have actionable feedback. Thanks!

**Closed by Hixie** 2021-05-03 22:41 UTC
Labels: engine, passed first triage, perf: speed, platform-ios, severe: performance, severe: rendering
