### ISSUE TITLE
firebase_auth linkWithCredential bug on Android only

### ISSUE THREAD

**Issue by nemoryoliver** [flutter/flutter#27578] opened 2019-02-06 04:50 UTC
Using latest firebase_auth: ^0.8.0+1

## Steps to Reproduce

1. Add and configure the firebase_auth package
2. Use the linkWithCredential function with any Social AuthProvider credential
3. Run on Android Device / Emulator

## Logs

You can see here that it tries to use the android function **handleLinkWithEmailAndPassword** instead of the corresponding social linking method. I believe this is a mistake use of the function.

```
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): java.lang.IllegalArgumentException: Given String is empty or null
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at com.google.firebase.auth.EmailAuthProvider.getCredential(Unknown Source)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleLinkWithEmailAndPassword(FirebaseAuthPlugin.java:272)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:122)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handlePlatformMessage(FlutterNativeView.java:188)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/MethodChannel#plugins.flutter.io/firebase_auth(11343): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
I/flutter (11343): error: PlatformException(error, Given String is empty or null, null)
V/FA      (11343): Inactivity, disconnecting from the service
```

## Flutter Doctor

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.1.8 at /Users/nemory/Development/flutter
    • Framework revision 985ccb6d14 (4 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nemory/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (4 available)
    • BBF100 2                  • 5000013362                               • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554                            • android-x86   • Android 7.1.1 (API 25) (emulator)
    • Oliver's iPhone           • b3d99ff4ed9f1a1a3aa41eb597b33b6ddc7d2752 • ios           • iOS 12.1.2
    • iPhone XS Max             • 39AC65C7-4F9F-454F-B1B5-3376EE04BCBF     • ios           • iOS 12.1 (simulator)

• No issues found!
```

**Comment by BerndWessels** [comment] 2019-02-06 21:14
Exactly same here :(

With every update Firebase is breaking my projects and feels is frustratingly unstable :(

**Comment by kangwang1988** [comment] 2019-02-07 12:41
cc @cyanglaz

**Comment by zoechi** [comment] 2019-02-08 11:16
Duplicate of #26477

**Closed by zoechi** 2019-02-08 11:16 UTC
Labels: p: firebase, p: firebase_auth, p: first party, plugin, severe: crash

**Comment by nemoryoliver** [comment] 2019-02-08 14:48
> Duplicate of #26477

Sorry for the dumb question. How do I specifically use the commit as my package dependency? From this commit https://github.com/flutter/plugins/pull/973/commits/79409ab2d61e8411a8c1be6582587afd60364ae6

**Comment by tolotrasamuel** [comment] 2019-02-26 19:56
@nemoryoliver  Which version of firebase_core does this require?

**Comment by nemoryoliver** [comment] 2019-02-26 23:26
> @nemoryoliver Which version of firebase_core does this require?

I use the very latest and it's working fine for me.

**Comment by myoganugraha** [comment] 2019-03-22 04:19
> > Duplicate of #26477
> 
> Sorry for the dumb question. How do I specifically use the commit as my package dependency? From this commit [flutter/plugins@79409ab](https://github.com/flutter/plugins/commit/79409ab2d61e8411a8c1be6582587afd60364ae6)
> 
> ## Update
> Sorry, I think I figured it out.
> 
> ```
> firebase_auth:
>     git:
>       url: git://github.com/flutter/plugins.git
>       path: packages/firebase_auth
>       ref: 79409ab2d61e8411a8c1be6582587afd60364ae6
> ```
> It requires an older version of firebase_core though

hello, i follow this commit
but after input phone number, still bypass the verificationCode screen on flutter

my code is below

```
Future<Null> _verifyPhoneNumber() async {

    
      final PhoneCodeAutoRetrievalTimeout autoRetrieve = (String verId) {
      setState(() {
        this._verificationId = verId;
        this._codeTimedOut = true;
      });
    };

    final PhoneCodeSent smsCodeSent = (String verId, [int forceCodeResend]) {
      
      _codeTimer = Timer(Duration(minutes: 1), (){
        setState(() {
          _codeTimedOut = true;
        });
      });

      setState(() {
        _isPhoneVerifScreenPassed = true;
        this._verificationId = verId;
        this._loginStatus = LoginStatus.SMS_LOGIN;
      });
      
    };

    final PhoneVerificationCompleted verifiedSuccess = (FirebaseUser user) async {
      if(await _onCodeVerified(user)) {
        await _finishSignIn(user);
      } else {
        setState(() {
          this._loginStatus =LoginStatus.SMS_LOGIN;
        });
        _clearPreviousSession();
        
      }
    };

    final PhoneVerificationFailed veriFailed = (AuthException exception) {
      print('${exception.message}');
      _showSnackbar('Verifikasi OTP Gagal. Code: ${exception.code}. Message: ${exception.message}');
      _isPhoneVerifScreenPassed = false;
    };

    final result = await _firebaseAuth.verifyPhoneNumber(
      phoneNumber: '+62' + _phoneController.text,
      timeout: Duration(minutes: 1),
      codeAutoRetrievalTimeout: autoRetrieve,
      codeSent: smsCodeSent,
      verificationCompleted: verifiedSuccess,
      verificationFailed: veriFailed
    );

    return result;
    
  }

  _signInWithPhoneNumber() async {
    final AuthCredential credential = PhoneAuthProvider.getCredential(
      verificationId: _verificationId,
      smsCode: _verifCodeController.text
    );

    print(_verifCodeController.text);


    
    await _firebaseAuth.linkWithCredential(credential)
    .then((user) async {
       await _onCodeVerified(user).then((codeVerified) async {
         this._codeVerified = codeVerified;
       });

       if(this._codeVerified){
         await _finishSignIn(user);
       }
    }).catchError((error) {
      _showSnackbar(error.toString());
    });
  }

  _finishSignIn(FirebaseUser user) async {
    await _onCodeVerified(user).then((result) {
      if(result){
        print('user $user');
        
        Navigator.of(context).pushReplacement(CupertinoPageRoute(
              builder: (context) => MainScreen(
                    firebaseUser: user,
                  ),
        ));
      }
      else {
        _showSnackbar("Silahkan Login Ulang");
        setState(() {
          _clearPreviousSession();
        });
      }
    });
  } 
```

so after i put phone number, it immediately call _finishSignIn method 
is something wrong in my code ?

thank you

**Comment by kroikie** [comment] 2019-10-13 18:27
@nemoryoliver

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/462. Any further collaboration will be done there.
