### ISSUE TITLE
Flutter crashing on startup iPad only (iOS 16.2) EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by cdennison** [flutter/flutter#120092] opened 2023-02-06 16:23 UTC
I'm happy to share my entire code base privately but don't want to put it here.

![image](https://user-images.githubusercontent.com/7264710/217025050-036f4110-bc79-4ed6-9a56-ef59bf023087.png)

Not sure why there are 2 crash logs - both appear to be for same iPad
[crashlog-4D1F731F-D7E0-48B1-B7DD-914C776B6064.txt](https://github.com/flutter/flutter/files/10665018/crashlog-4D1F731F-D7E0-48B1-B7DD-914C776B6064.txt)
[crashlog-4FE44B51-CA67-48C0-915F-021AD7F9C132 (2).txt](https://github.com/flutter/flutter/files/10665019/crashlog-4FE44B51-CA67-48C0-915F-021AD7F9C132.2.txt)

Pubspec
```
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_phone_direct_caller: ^2.1.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  geocode: ^1.0.2
  rounded_loading_button: ^2.1.0
  url_launcher: ^6.1.8
  google_fonts: ^4.0.1
  shared_preferences: ^2.0.17
  page_transition: ^2.0.9
  timeago: ^3.3.0
  json_path: ^0.4.2
  intl: ^0.17.0
  from_css_color: ^2.0.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.3.0
  go_router: ^6.0.1
  firebase_analytics: ^10.1.0
  flutter_linkify: ^5.0.2
```

main.dart
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(MyApp());
}
```

Runs fine inside Xcode - these are the logs using iPad simulator (10th gen)
```
2023-02-06 10:06:02.818143-0500 Runner[71969:269425] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-02-06 10:06:02.818232-0500 Runner[71969:269425] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-02-06 10:06:03.284374-0500 Runner[71969:269425] Metal API Validation Enabled
2023-02-06 10:07:28.193715-0500 Runner[71969:273074] flutter: The Dart VM service is listening on http://127.0.0.1:59699/Yne6xxmgzGE=/
2023-02-06 10:07:29.143200-0500 Runner[71969:269721] 10.3.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
2023-02-06 10:07:29.384353-0500 Runner[71969:269721] 10.3.0 - [FirebaseCore][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'com.charlemagne.callthestatepolice'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.
2023-02-06 10:07:29.589694-0500 Runner[71969:273106] 10.3.0 - [FirebaseAnalytics][I-ACS023007] Analytics v.10.3.0 started
2023-02-06 10:07:29.596681-0500 Runner[71969:273106] 10.3.0 - [FirebaseAnalytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2023-02-06 10:07:29.996978-0500 Runner[71969:269720] 10.3.0 - [FirebaseAnalytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2023-02-06 10:07:30.037060-0500 Runner[71969:269715] 10.3.0 - [FirebaseAnalytics][I-ACS013008] Parameter name uses reserved prefix. Ignoring parameter: firebase_screen
2023-02-06 10:07:30.038250-0500 Runner[71969:269715] 10.3.0 - [FirebaseAnalytics][I-ACS013008] Parameter name uses reserved prefix. Ignoring parameter: firebase_screen_class
2023-02-06 10:07:30.062977-0500 Runner[71969:269715] 10.3.0 - [FirebaseAnalytics][I-ACS023012] Analytics collection enabled
2023-02-06 10:07:30.065968-0500 Runner[71969:269715] 10.3.0 - [FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist

```

Here's the crash report

<details>
<summary>Crash</summary>

```console
{
  "exception": {
    "codes": "0x0000000000000001, 0x0000000000000000",
    "rawCodes": [
      1,
      0
    ],
    "type": "EXC_BAD_ACCESS",
    "signal": "SIGSEGV",
    "subtype": "KERN_INVALID_ADDRESS at 0x0000000000000000"
  },
  "termination": {
    "flags": 0,
    "code": 11,
    "namespace": "SIGNAL",
    "indicator": "Segmentation fault: 11",
    "byProc": "exc handler",
    "byPid": 4448
  }
}

[
  {
    "triggered": true,
    "id": 667545,
    "threadState": {
      "x": [
        {
          "value": 0
        },
        {
          "value": 144115192454974270,
          "symbolLocation": 144115188075855870,
          "symbol": "type metadata for PathProviderPlugin"
        },
        {
          "value": 4379118392,
          "symbolLocation": 0,
          "symbol": "type metadata for PathProviderPlugin"
        },
        {
          "value": 0
        },
        {
          "value": 4
        },
        {
          "value": 1072
        },
        {
          "value": 4379668968,
          "symbolLocation": 128,
          "symbol": "_OBJC_$_INSTANCE_METHODS_SurveysFlutterApi"
        },
        {
          "value": 4379668944,
          "symbolLocation": 104,
          "symbol": "_OBJC_$_INSTANCE_METHODS_SurveysFlutterApi"
        },
        {
          "value": 10780918832
        },
        {
          "value": 7100585594,
          "objc-selector": "init"
        },
        {
          "value": 10820969378
        },
        {
          "value": 71776123926817280
        },
        {
          "value": 214
        },
        {
          "value": 4865603408
        },
        {
          "value": 2043
        },
        {
          "value": 8619532248,
          "symbolLocation": 0,
          "symbol": "OBJC_CLASS_$_NSObject"
        },
        {
          "value": 7075835052,
          "symbolLocation": 0,
          "symbol": "swift_getObjectType"
        },
        {
          "value": 2
        },
        {
          "value": 0
        },
        {
          "value": 0
        },
        {
          "value": 4379118392,
          "symbolLocation": 0,
          "symbol": "type metadata for PathProviderPlugin"
        },
        {
          "value": 1
        },
        {
          "value": 1
        },
        {
          "value": 0
        },
        {
          "value": 1
        },
        {
          "value": 8574021632
        },
        {
          "value": 8574111744,
          "symbolLocation": 0,
          "symbol": "OBJC_IVAR_$__UIDatePickerMode._defaultTimeFont"
        },
        {
          "value": 730267748
        },
        {
          "value": 16
        }
      ],
      "flavor": "ARM_THREAD_STATE64",
      "lr": {
        "value": 5416656077687345000
      },
      "cpsr": {
        "value": 1610612736
      },
      "fp": {
        "value": 6094622928
      },
      "sp": {
        "value": 6094622912
      },
      "esr": {
        "value": 2449473542,
        "description": "(Data Abort) byte read Translation fault"
      },
      "pc": {
        "value": 7075835092,
        "matchesCrashFrame": 1
      },
      "far": {
        "value": 0
      }
    },
    "queue": "com.apple.main-thread",
    "frames": [
      {
        "imageOffset": 4316372,
        "symbol": "swift_getObjectType",
        "symbolLocation": 40,
        "imageIndex": 0
      },
      {
        "imageOffset": 36400,
        "symbol": "static PathProviderPlugin.register(with:)",
        "symbolLocation": 88,
        "imageIndex": 1
      },
      {
        "imageOffset": 36400,
        "symbol": "static PathProviderPlugin.register(with:)",
        "symbolLocation": 88,
        "imageIndex": 1
      },
      {
        "imageOffset": 36664,
        "symbol": "@objc static PathProviderPlugin.register(with:)",
        "symbolLocation": 56,
        "imageIndex": 1
      },
      {
        "imageOffset": 29032,
        "symbol": "+[GeneratedPluginRegistrant registerWithRegistry:]",
        "symbolLocation": 588,
        "imageIndex": 2
      },
      {
        "imageOffset": 29296,
        "symbol": "AppDelegate.application(_:didFinishLaunchingWithOptions:)",
        "symbolLocation": 96,
        "imageIndex": 2
      },
      {
        "imageOffset": 30008,
        "symbol": "@objc AppDelegate.application(_:didFinishLaunchingWithOptions:)",
        "symbolLocation": 188,
        "imageIndex": 2
      },
      {
        "imageOffset": 3513428,
        "symbol": "-[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]",
        "symbolLocation": 300,
        "imageIndex": 3
      },
      {
        "imageOffset": 3511160,
        "symbol": "-[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:]",
        "symbolLocation": 2848,
        "imageIndex": 3
      },
      {
        "imageOffset": 3507028,
        "symbol": "-[UIApplication _runWithMainScene:transitionContext:completion:]",
        "symbolLocation": 856,
        "imageIndex": 3
      },
      {
        "imageOffset": 3506080,
        "symbol": "-[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:]",
        "symbolLocation": 132,
        "imageIndex": 3
      },
      {
        "imageOffset": 647692,
        "symbol": "_UIScenePerformActionsWithLifecycleActionMask",
        "symbolLocation": 108,
        "imageIndex": 3
      },
      {
        "imageOffset": 4062872,
        "symbol": "__101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke",
        "symbolLocation": 216,
        "imageIndex": 3
      },
      {
        "imageOffset": 2690272,
        "symbol": "-[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:]",
        "symbolLocation": 220,
        "imageIndex": 3
      },
      {
        "imageOffset": 2689800,
        "symbol": "-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]",
        "symbolLocation": 620,
        "imageIndex": 3
      },
      {
        "imageOffset": 2688696,
        "symbol": "-[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:]",
        "symbolLocation": 252,
        "imageIndex": 3
      },
      {
        "imageOffset": 2688388,
        "symbol": "__186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke",
        "symbolLocation": 148,
        "imageIndex": 3
      },
      {
        "imageOffset": 9913016,
        "symbol": "+[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:]",
        "symbolLocation": 736,
        "imageIndex": 3
      },
      {
        "imageOffset": 10541708,
        "symbol": "_UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion",
        "symbolLocation": 224,
        "imageIndex": 3
      },
      {
        "imageOffset": 1295756,
        "symbol": "-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]",
        "symbolLocation": 316,
        "imageIndex": 3
      },
      {
        "imageOffset": 5960068,
        "symbol": "__64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.214",
        "symbolLocation": 556,
        "imageIndex": 3
      },
      {
        "imageOffset": 2157496,
        "symbol": "-[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:]",
        "symbolLocation": 216,
        "imageIndex": 3
      },
      {
        "imageOffset": 2157096,
        "symbol": "-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]",
        "symbolLocation": 244,
        "imageIndex": 3
      },
      {
        "imageOffset": 2154364,
        "symbol": "-[UIApplication workspace:didCreateScene:withTransitionContext:completion:]",
        "symbolLocation": 520,
        "imageIndex": 3
      },
      {
        "imageOffset": 2153736,
        "symbol": "-[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]",
        "symbolLocation": 288,
        "imageIndex": 3
      },
      {
        "imageOffset": 11920,
        "symbol": "-[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:]",
        "symbolLocation": 344,
        "imageIndex": 4
      },
      {
        "imageOffset": 272632,
        "symbol": "__92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke.78",
        "symbolLocation": 120,
        "imageIndex": 4
      },
      {
        "imageOffset": 27684,
        "symbol": "-[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]",
        "symbolLocation": 168,
        "imageIndex": 4
      },
      {
        "imageOffset": 271664,
        "symbol": "__92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke",
        "symbolLocation": 360,
        "imageIndex": 4
      },
      {
        "imageOffset": 16348,
        "symbol": "_dispatch_client_callout",
        "symbolLocation": 20,
        "imageIndex": 5
      },
      {
        "imageOffset": 31324,
        "symbol": "_dispatch_block_invoke_direct",
        "symbolLocation": 264,
        "imageIndex": 5
      },
      {
        "imageOffset": 68928,
        "symbol": "__FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__",
        "symbolLocation": 52,
        "imageIndex": 4
      },
      {
        "imageOffset": 67804,
        "symbol": "-[FBSSerialQueue _targetQueue_performNextIfPossible]",
        "symbolLocation": 220,
        "imageIndex": 4
      },
      {
        "imageOffset": 78212,
        "symbol": "-[FBSSerialQueue _performNextFromRunLoopSource]",
        "symbolLocation": 28,
        "imageIndex": 4
      },
      {
        "imageOffset": 876340,
        "symbol": "__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__",
        "symbolLocation": 28,
        "imageIndex": 6
      },
      {
        "imageOffset": 926476,
        "symbol": "__CFRunLoopDoSource0",
        "symbolLocation": 176,
        "imageIndex": 6
      },
      {
        "imageOffset": 418256,
        "symbol": "__CFRunLoopDoSources0",
        "symbolLocation": 244,
        "imageIndex": 6
      },
      {
        "imageOffset": 506764,
        "symbol": "__CFRunLoopRun",
        "symbolLocation": 836,
        "imageIndex": 6
      },
      {
        "imageOffset": 528064,
        "symbol": "CFRunLoopRunSpecific",
        "symbolLocation": 612,
        "imageIndex": 6
      },
      {
        "imageOffset": 4968,
        "symbol": "GSEventRunModal",
        "symbolLocation": 164,
        "imageIndex": 7
      },
      {
        "imageOffset": 3807340,
        "symbol": "-[UIApplication _run]",
        "symbolLocation": 888,
        "imageIndex": 3
      },
      {
        "imageOffset": 3806416,
        "symbol": "UIApplicationMain",
        "symbolLocation": 340,
        "imageIndex": 3
      },
      {
        "imageOffset": 30384,
        "symbol": "main",
        "symbolLocation": 64,
        "imageIndex": 2
      },
      {
        "imageOffset": 88416,
        "symbol": "start",
        "symbolLocation": 2528,
        "imageIndex": 8
      }
    ]
  },
  {
    "id": 667617,
    "queue": "com.apple.UIKit.KeyboardManagement",
    "frames": [
      {
        "imageOffset": 21984,
        "symbol": "__ulock_wait",
        "symbolLocation": 8,
        "imageIndex": 9
      },
      {
        "imageOffset": 18892,
        "symbol": "_dlock_wait",
        "symbolLocation": 56,
        "imageIndex": 5
      },
      {
        "imageOffset": 18304,
        "symbol": "_dispatch_thread_event_wait_slow",
        "symbolLocation": 56,
        "imageIndex": 5
      },
      {
        "imageOffset": 79968,
        "symbol": "__DISPATCH_WAIT_FOR_QUEUE__",
        "symbolLocation": 368,
        "imageIndex": 5
      },
      {
        "imageOffset": 78860,
        "symbol": "_dispatch_sync_f_slow",
        "symbolLocation": 144,
        "imageIndex": 5
      },
      {
        "imageOffset": 3808064,
        "symbol": "__37-[_UIRemoteKeyboards startConnection]_block_invoke_3",
        "symbolLocation": 156,
        "imageIndex": 3
      },
      {
        "imageOffset": 476868,
        "symbol": "__invoking___",
        "symbolLocation": 148,
        "imageIndex": 6
      },
      {
        "imageOffset": 133932,
        "symbol": "-[NSInvocation invoke]",
        "symbolLocation": 428,
        "imageIndex": 6
      },
      {
        "imageOffset": 661768,
        "symbol": "__NSXPCCONNECTION_IS_CALLING_OUT_TO_REPLY_BLOCK__",
        "symbolLocation": 16,
        "imageIndex": 10
      },
      {
        "imageOffset": 470160,
        "symbol": "-[NSXPCConnection _decodeAndInvokeReplyBlockWithEvent:sequence:replyInfo:]",
        "symbolLocation": 520,
        "imageIndex": 10
      },
      {
        "imageOffset": 6603332,
        "symbol": "__88-[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:]_block_invoke_5",
        "symbolLocation": 188,
        "imageIndex": 10
      },
      {
        "imageOffset": 122184,
        "symbol": "_xpc_connection_reply_callout",
        "symbolLocation": 124,
        "imageIndex": 11
      },
      {
        "imageOffset": 68496,
        "symbol": "_xpc_connection_call_reply_async",
        "symbolLocation": 88,
        "imageIndex": 11
      },
      {
        "imageOffset": 16476,
        "symbol": "_dispatch_client_callout3",
        "symbolLocation": 20,
        "imageIndex": 5
      },
      {
        "imageOffset": 139096,
        "symbol": "_dispatch_mach_msg_async_reply_invoke",
        "symbolLocation": 344,
        "imageIndex": 5
      },
      {
        "imageOffset": 46444,
        "symbol": "_dispatch_lane_serial_drain",
        "symbolLocation": 376,
        "imageIndex": 5
      },
      {
        "imageOffset": 49684,
        "symbol": "_dispatch_lane_invoke",
        "symbolLocation": 436,
        "imageIndex": 5
      },
      {
        "imageOffset": 93712,
        "symbol": "_dispatch_workloop_worker_thread",
        "symbolLocation": 652,
        "imageIndex": 5
      },
      {
        "imageOffset": 3576,
        "symbol": "_pthread_wqthread",
        "symbolLocation": 288,
        "imageIndex": 12
      },
      {
        "imageOffset": 2968,
        "symbol": "start_wqthread",
        "symbolLocation": 8,
        "imageIndex": 12
      }
    ]
  },
  {
    "id": 667618,
    "frames": [
      {
        "imageOffset": 2960,
        "symbol": "start_wqthread",
        "symbolLocation": 0,
        "imageIndex": 12
      }
    ]
  },
  {
    "id": 667619,
    "frames": [
      {
        "imageOffset": 2960,
        "symbol": "start_wqthread",
        "symbolLocation": 0,
        "imageIndex": 12
      }
    ]
  },
  {
    "id": 667620,
    "frames": [
      {
        "imageOffset": 2960,
        "symbol": "start_wqthread",
        "symbolLocation": 0,
        "imageIndex": 12
      }
    ]
  },
  {
    "id": 667621,
    "frames": [
      {
        "imageOffset": 2960,
        "symbol": "start_wqthread",
        "symbolLocation": 0,
        "imageIndex": 12
      }
    ]
  },
  {
    "id": 667622,
    "frames": [
      {
        "imageOffset": 2960,
        "symbol": "start_wqthread",
        "symbolLocation": 0,
        "imageIndex": 12
      }
    ]
  },
  {
    "id": 667623,
    "name": "com.apple.uikit.eventfetch-thread",
    "frames": [
      {
        "imageOffset": 19112,
        "symbol": "mach_msg2_trap",
        "symbolLocation": 8,
        "imageIndex": 9
      },
      {
        "imageOffset": 94148,
        "symbol": "mach_msg2_internal",
        "symbolLocation": 80,
        "imageIndex": 9
      },
      {
        "imageOffset": 94724,
        "symbol": "mach_msg_overwrite",
        "symbolLocation": 388,
        "imageIndex": 9
      },
      {
        "imageOffset": 20460,
        "symbol": "mach_msg",
        "symbolLocation": 24,
        "imageIndex": 9
      },
      {
        "imageOffset": 502484,
        "symbol": "__CFRunLoopServiceMachPort",
        "symbolLocation": 160,
        "imageIndex": 6
      },
      {
        "imageOffset": 507160,
        "symbol": "__CFRunLoopRun",
        "symbolLocation": 1232,
        "imageIndex": 6
      },
      {
        "imageOffset": 528064,
        "symbol": "CFRunLoopRunSpecific",
        "symbolLocation": 612,
        "imageIndex": 6
      },
      {
        "imageOffset": 270548,
        "symbol": "-[NSRunLoop(NSRunLoop) runMode:beforeDate:]",
        "symbolLocation": 212,
        "imageIndex": 10
      },
      {
        "imageOffset": 270268,
        "symbol": "-[NSRunLoop(NSRunLoop) runUntilDate:]",
        "symbolLocation": 64,
        "imageIndex": 10
      },
      {
        "imageOffset": 5072684,
        "symbol": "-[UIEventFetcher threadMain]",
        "symbolLocation": 436,
        "imageIndex": 3
      },
      {
        "imageOffset": 374184,
        "symbol": "__NSThread__start__",
        "symbolLocation": 716,
        "imageIndex": 10
      },
      {
        "imageOffset": 5836,
        "symbol": "_pthread_start",
        "symbolLocation": 148,
        "imageIndex": 12
      },
      {
        "imageOffset": 2980,
        "symbol": "thread_start",
        "symbolLocation": 8,
        "imageIndex": 12
      }
    ]
  }
]
```
</details>

**Comment by huycozy** [comment] 2023-02-07 07:53
@cdennison Thanks for the report. I updated the crash log into a collapse section for better readability. 

>2023-02-06 10:07:29.143200-0500 Runner[71969:269721] 10.3.0 - [FirebaseCore][I-COR000005] No app has been configured yet.
2023-02-06 10:07:29.384353-0500 Runner[71969:269721] 10.3.0 - [FirebaseCore][I-COR000008] The project's Bundle ID is inconsistent with either the Bundle ID in 'GoogleService-Info.plist', or the Bundle ID in the options if you are using a customized options. To ensure that everything can be configured correctly, you may need to make the Bundle IDs consistent. To continue with this plist file, you may change your app's bundle identifier to 'com.charlemagne.callthestatepolice'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.

Taking a look at XCode run output, it looks like your project's Bundle ID is not the same as Bundle ID in 'GoogleService-Info.plist' file. Please double check on this and retry. 

Once the issue still persists after updating Bundle ID, please provide the complete output of `flutter run -v` so that we may verify the issue. Thanks!

**Comment by cdennison** [comment] 2023-02-07 15:11
Thanks for your help. I don't think the Bundle ID is the issue but I will fix that.

I just submitted an older commit and it passed Apple's check so I'm trying to narrow down the issue based on the diff between my 2 commits. What makes this slow and tedious is that I can't reproduce the issue locally so I'm relying on Apple's build process to find this issue and the crash report makes no sense - but I'm new to Flutter/Dart so wasn't sure if I missed something obvious.

**Comment by huycozy** [comment] 2023-02-08 02:58
@cdennison It's not very informative in two crash files where I can find the cause of the issue. You should keep an eye on it if you are able to replicate it and see if it has any pattern (running in release mode would be a try, for eg: `flutter run -v --release`). 

If you are unable to see it again, feel free to close it and then you can write a comment when you have clear steps to reproduce so that we will reopen the issue. Thanks!

**Comment by cdennison** [comment] 2023-02-08 21:59
@huycozy got it. The latest update is I re-submitted the exact same build to Apple and now it's passing so I don't know what to make of that.

**Comment by huycozy** [comment] 2023-02-09 03:09
@cdennison 
Without more information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away! Thank you!

**Closed by huycozy** 2023-02-09 03:09 UTC
Labels: in triage
