### ISSUE TITLE
Validate the return type of the callback in compute() function

### ISSUE THREAD

**Issue by gavinhub** [flutter/flutter#108856] opened 2022-08-03 03:22 UTC
I'm suggesting a better error message for the issue with `compute()`.

I ran into the same issue as described in https://github.com/flutter/flutter/issues/63664 and I figured out my problem. 

In my case, I was passing in a function that returns a Future.

```
Future<List<String>> _loadData(String arg) async {
  final dataFromFile = await readFile(arg);
  // Heavy compute
  parseFile(dataFromFile);
}

@override
void initState() {
  super.initState();

  myData = compute(_loadData, 'arg');
}
```

This throws an exception. Then I changed the code to use `compute` inside `_loadData`;

```
Future<List<String>> _loadData(String arg) async {
  final dataFromFile = await readFile(arg);
  // Heavy compute
  return compute(parseFile, dataFromFile);
}
```

Then it worked.

So the problem was that we cannot use a async function as the callback in `compute`;

**Comment by exaby73** [comment] 2022-08-03 08:54
Hello @gavinhub. Using the code sample below, I was not able to reproduce this issue. The `compute` function takes a [`ComputeCallback`](https://api.flutter.dev/flutter/foundation/ComputeCallback.html), whose signature accepts a `FutureOr Function`. Therefore, futures are supported. If you are able to produce a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), please do post it here

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String? _data;

  Future<String> _initData(String message) async {
    await Future.delayed(const Duration(seconds: 2));
    return 'Data loaded: $message';
  }

  @override
  void initState() {
    super.initState();
    compute(_initData, 'from compute').then((String data) {
      setState(() {
        _data = data;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Text(_data ?? 'Loading...'),
      ),
    );
  }
}
```

</details> 

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.5 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.41.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2055, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.2055 on channel master at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b4673a2c1f (2 hours ago), 2022-08-03 00:51:16 -0400
    • Engine revision 6cd744bb97
    • Dart version 2.19.0 (build 2.19.0-58.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.41.100

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by gavinhub** [comment] 2022-08-14 06:19
Hi @exaby73. Thanks for replying. I tried your code example and it works. Then I changed the code closer to what I had when I see the problem. Basically, I ran compute while pushing in a new page. And I read from assets in the `compute` function. Here is how I reproduce. 

Please ensure you have the assets added in pubspec.yaml.

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) => const MyHomePage(),
        '/compute': (context) => const ComputePage(),
      },
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      body: Center(
        child: TextButton(
          onPressed: () {
            Navigator.pushNamed(context, '/compute');
          },
          child: const Text('Compute'),
        ),
      ));
}

class ComputePage extends StatefulWidget {
  const ComputePage({Key? key}) : super(key: key);

  @override
  State<ComputePage> createState() => _ComputePageState();
}

Future<String> loadAsset(String filename) async {
  return await rootBundle.loadString(filename);
}

Future<String> _initData(String filename) async {
  final content = await loadAsset(filename);
  return 'Data loaded: $content';
}

class _ComputePageState extends State<ComputePage> {
  String? _data;

  @override
  void initState() {
    super.initState();
    compute(_initData, 'assets/text_file.txt').then((String data) {
      setState(() {
        _data = data;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Compute'),
      ),
      body: Center(
        child: Text(_data ?? 'Loading...'),
      ),
    );
  }
}

```

**Comment by exaby73** [comment] 2022-08-15 07:38
I do not think you can read from assets in the compute function since it's running on a separate thread/isolate.

Basically Flutter needs `WidgetsFlutterBinding.ensureInitialized()` to be called in order for you to access assets. But it's only supported from the root isolate AKA the UI thread. So you need to read the data and pass it to the callback in the `compute` function. You shouldn't have problems with performance of your UI since it is an asynchronous call.

Since this is how it's expected to work, I am closing this issue. Feel free to comment if you disagree and we can reopen it. Thank you

**Closed** 2022-08-15 07:39 UTC
Labels: r: invalid, in triage
