### ISSUE TITLE
package_info is retrieving different  build number in apk from debugging Application ? any idea for this issue?

### ISSUE THREAD

**Issue by hemalivekariya** [flutter/flutter#90514] opened 2021-09-22 10:52 UTC
in pubspac.yml ---->version: 1.0.19+81
but when I print the build number in this mode debug apk or release like this 
debug--build number -->81
apk--build number ->1081
release--build number ->81

why apk print show the 1081 build number ??

**Comment by maheshmnj** [comment] 2021-09-22 11:53
Hi @hemalivekariya Thanks for filing the issue. Please share the output of `flutter doctor -v`. 

> apk--build number ->1081

Could you please explain how you got `apk-build number 1081` ? 

I verified on the latest `stable 2.5.1` using the `package_info: ^2.0.2` on Android and I could see the correct build number, verified in debug, profile, and release mode.

Also please share the plugin version you are having issues with


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:package_info/package_info.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  Future<void> _incrementCounter() async {
    PackageInfo packageInfo = await PackageInfo.fromPlatform();

    String appName = packageInfo.appName;
    String packageName = packageInfo.packageName;
    String version = packageInfo.version;
    String buildNumber = packageInfo.buildNumber;
    print('''
      appName: $appName,
      packageName: $packageName,
      version: $version,
      buildNumber: $buildNumber
    ''');
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (5 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • d9dac45d • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos    • darwin-arm64   • macOS 11.6 20G165 darwin-arm
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 94.0.4606.54

• No issues found!
```

</details>

<details>
<summary>logs</summary>

```console
mahesh@Maheshs-MacBook-Air-M1 pigeon_example % flutter run --release
Launching lib/main.dart on Redmi K20 Pro in release mode...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Running Gradle task 'assembleRelease'...                           53.2s
✓  Built build/app/outputs/flutter-apk/app-release.apk (6.0MB).
Installing build/app/outputs/flutter-apk/app.apk...              1,021ms

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
W/FlutterActivityAndFragmentDelegate(32575): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
I/flutter (32575):       appName: pigeon_example,
I/flutter (32575):       packageName: com.example.pigeon_example,
I/flutter (32575):       version: 1.0.19,
I/flutter (32575):       buildNumber: 81
I/flutter (32575):     
```
</details>


Thanks.

**Comment by hemalivekariya** [comment] 2021-09-22 12:22
Thanks for ans..i am using the package "package_info: ^2.0.0"
and 
Code:--
getPackageInfo(){
PackageInfo packageInfo = await PackageInfo.fromPlatform();
    int _appVersion = int.parse(packageInfo.buildNumber);
    log("appVersion---> ${_appVersion}
}
but when i am make apk from this command :flutter build apk --release --split-per-abi --no-shrink
after that i m install that apk in my mobile and check the Logcat which i have print 
and i get the buildNumber in logcat

Locat log:
apkMode--build number get like --->1081
![Screenshot 2021-09-22 at 5 50 02 PM](https://user-images.githubusercontent.com/54179309/134342424-8beb4c71-f19b-4442-ae38-447bba221a9f.png)

**Comment by maheshmnj** [comment] 2021-09-22 13:39
@hemalivekariya Thanks for the info, This is an intended behavior, Since you are using split apks by adding 
`--split-per-abi` to build command.

Please read this for more info on how [versioning works for split apks](https://developer.android.com/studio/build/configure-apk-splits?authuser=1#configure-APK-versions).  

On a side note: if you are building app for releasing to playstore

> prefer building app bundle when releasing the app on play store as From August 2021, the Google Play Console will require all new apps to publish with the Android App Bundle format.
https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html

Closing the issue since it is working as expected, If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-22 13:39 UTC
Labels: in triage
