### ISSUE TITLE
Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:04:30.000000

### ISSUE THREAD

**Issue by huayicheng2015** [flutter/flutter#156415] opened 2024-10-08 16:14 UTC
[#111576](https://github.com/flutter/flutter/issues/111576)
[#33649](https://github.com/flutter/flutter/issues/33649)
```bash
flutter doctor
```
```bash
[✓] Flutter (Channel stable, 3.19.6, on macOS 12.7.6 21H1320 darwin-x64, locale zh-Hans-CN)
all green.
```
```bash
flutter upgrade
```
```bash
[✓] Flutter (Channel stable, 3.24.3, on macOS 12.7.6 21H1320 darwin-x64, locale zh-Hans-CN)
[☠] Android toolchain - develop for Android devices (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Android toolchain - develop for Android devices exceeded maximum allowed duration of 0:04:30.000000
all green.
```
```bash
java -version
```
```bash
java version "1.8.0_421"
```
```bash
flutter doctor --android-licenses
```
```bash
/.../sdk/cmdline-tools/latest/bin/sdkmanager: line 173: test: : integer expression expected
[========= ] 28% Fetch remote repository...
```
The latest version of cmdline-tools above is ```16.0```.

**Comment by darshankawar** [comment] 2024-10-09 07:17
Closing as duplicate of https://github.com/flutter/flutter/issues/126755
For solution, check https://github.com/flutter/flutter/issues/126755#issuecomment-1546815731 and see if it helps to resolve your issue or not.

**Closed** 2024-10-09 07:18 UTC
Labels: r: duplicate
