### ISSUE TITLE
[tool_crash] SocketException: Der Remotecomputer hat die Netzwerkverbindung abgelehnt., OS Error: Der Remotecomputer hat die Netzwerkverbindung abgelehnt., errno = 1225

### ISSUE THREAD

**Issue by stingrayx** [flutter/flutter#153512] opened 2024-08-15 18:16 UTC
## Command
```sh
flutter run --machine --start-paused -d chrome --devtools-server-address http://127.0.0.1:9100/ --target main.dart
```

## Steps to Reproduce
I have this type of crashes on my Windows 11 since upgrading to Flutter 3.24. Before the latest upgrade, I never encountered this issue while developing my web application. Windows firewalls are deactivated and no other firewall etc. is installed. Internet connection is stable during the crash and I'm not behind a proxy or something. Thanks

## Logs
SocketException: Der Remotecomputer hat die Netzwerkverbindung abgelehnt.
, OS Error: Der Remotecomputer hat die Netzwerkverbindung abgelehnt.
, errno = 1225
```console
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1920:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2144:22)
#4      Socket.startConnect (dart:io/socket.dart:825:21)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2491:20)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2930:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2935:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2790:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2632:48)
#10     ChromeConnection.getUrl (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:108:33)
#11     ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:53:26)
#12     ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:90:31)
#13     Chromium.close (package:flutter_tools/src/web/chrome.dart:510:53)
#14     ChromiumDevice.stopApp (package:flutter_tools/src/web/web_device.dart:164:20)
#15     ResidentWebRunner._cleanup (package:flutter_tools/src/isolated/resident_web_runner.dart:203:27)
<asynchronous suspension>
#16     ResidentWebRunner.cleanupAtFinish (package:flutter_tools/src/isolated/resident_web_runner.dart:191:5)
<asynchronous suspension>
#17     ResidentRunner.waitForAppToFinish (package:flutter_tools/src/resident_runner.dart:1482:5)
<asynchronous suspension>
#18     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:788:26)
<asynchronous suspension>
#19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.4037], locale de-DE)
    • Flutter version 3.24.0 on channel stable at h:\software\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Software\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = D:\Software\Android\Sdk
    • Java binary at: D:\android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2022.2)
    • Android Studio at D:\android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[✓] VS Code (version 1.92.1)
    • VS Code at C:\Users\Thomas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4037]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.119
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.98

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ee4e09cce01d6f2d7f4baebd247fde02e5008851
### Plugins
file_picker-8.0.7
flutter_plugin_android_lifecycle-2.0.21
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0

**Comment by huycozy** [comment] 2024-08-16 05:33
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153064. This has been fixed on Flutter master channel so you can try switching to master channel and retry.

**Closed by huycozy** 2024-08-16 05:33 UTC
Labels: in triage

**Comment by andrewkolos** [comment] 2024-08-22 16:35
@stingrayx I have some questions which might help us troubleshoot this, as I'm still seeing this reported on 3.24.1.

Do you know when this crash specifically happens? Is it when quitting the app (e.g. by sending `q` to the CLI or clicking `Stop debugging` if running from VSCode)?

Is this crash preventing you from running/debugging Flutter apps, or is it just noise printed in the output?

**Comment by stingrayx** [comment] 2024-08-23 05:35
@andrewkolos Actually it happens out of the sudden!

I'm developing a flutter web app with a nest js backend.

The crash so far never occured when I was debugging my flutter code directly. But when I was in another window or debugging the nestjs backend within another instance of VSCode.

Maybe there is an interference somewhere between the different ports? 

My Windows local firewall is deactivated, because of performance reasons when doing such kind of dev.

Thanks
