### ISSUE TITLE
[Web] RawKeyboardListener does not respect keyboard setting

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#80682] opened 2021-04-18 21:50 UTC
On Flutter Web the RawKeyboardListener does not respect the keyboard setting.

## Steps to Reproduce

- Run the [LogicalKeyboardKey](https://api.flutter.dev/flutter/services/LogicalKeyboardKey-class.html) sample with an AZERTY keyboard layout on Flutter Web. 
- The detected keys are not correct

**Expected results:** 
Expected to see the correct key getting detected.
For example when pressing the `A` key on an AZERTY keyboard, I expect `A` to be detected.

**Actual results:** 
When pressing `A` the `Q` key is detected instead. 

I have tested this on a physical AZERTY keyboard.
I'm not sure what happens when using a physical QWERTY keyboard, with an AZERTY logical layout setting.
Keys are detected properly on an Android Emulator. (using the physical keyboard to send key events)

**flutter doctor -v**
```
[√] Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19041.928], locale nl-BE)
    • Flutter version 2.1.0-12.2.pre at E:\Flutter\flutter
    • Framework revision 5bedb7b1d5 (5 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at E:\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = E:\Android\Sdk
    • Java binary at: E:\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\Android\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!

```

**Comment by darshankawar** [comment] 2021-04-19 10:01
I see the same behavior after verifying this using AZERTY keyboard. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.5 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)    

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
	  • SM G975F (mobile) • RZ8M802WY0X • android-arm64 • Android 10 (API 29)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment] 2021-04-19 10:02
Similar / related to https://github.com/flutter/flutter/issues/44918

**Comment by darshankawar** [comment] 2021-04-19 10:02
Cc: @dkwingsmt

**Comment by mdebbar** [comment] 2021-04-22 22:38
Duplicate of https://github.com/flutter/flutter/issues/77048

**Closed by mdebbar** 2021-04-22 22:38 UTC
Labels: assigned for triage, engine, found in release: 2.0, has reproducible steps, platform-web
