### ISSUE TITLE
Cancelling Google Sign In on Android & iOS throws exception instead of returning null

### ISSUE THREAD

**Issue by benjaminhorner** [flutter/flutter#26705] opened 2019-01-17 15:01 UTC
## Steps to Reproduce

1. download the example app : https://github.com/flutter/plugins/blob/0909e96c366f2f06643dd8f3be779a84aec37750/packages/google_sign_in/example/lib/main.dart#L100

2. add google_sign_in 3.2.4 to pubspeck

3. Build the App on either Android or iOS emulator

4. tap the google sign in button.

5. On Android -> click the back button -> the app throws an exception that is not caught (even by manually adding it to code)
On iOS -> click the cancel button on the alert dialog -> the app throws an exception that is not caught (even by manually adding it to code)

~~5.1 On iOS, the app crashes when the email/phone text input is taped or on the screen prompting to enter email or phone when the cancel button is taped.~~ -> Fixed by upgrading to the latest version of the sdk on master channel.

## LOGS
For Cancel button:
`PlatformException(sign_in_canceled, com.google.GIDSignIn, The user canceled the sign-in flow.)
`
For the iOS crash:
~~The IDE doesn't output anything in the console. I ran it with XCode and got the following error:
`EXC_BAD_ACCESS (code=1, address=0x48) aka operation that should occur on the main Thread being run on a background thread.~~ -> Fixed by upgrading to the latest version of the sdk on master channel.
`
##Flutter analyze
```
Analyzing my_team...                                             

   info • The class 'Stream' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions • lib/blocs/messages.bloc.dart:11:3 •
          sdk_version_async_exported_from_core
   info • The method '_onWidgetDidBuild' isn't used • lib/views/login/login.form.dart:84:8 • unused_element
  error • The function 'MyApp' isn't defined • test/widget_test.dart:14:29 • undefined_function

3 issues found. (ran in 5.3s)
```

##Flutter doctor
```
[✓] Flutter (Channel master, v1.1.10-pre.83, on Mac OS X 10.14.2 18C54, locale fr-FR)
    • Flutter version 1.1.10-pre.83 at /Users/work/Projects/flutter
    • Framework revision b4e9d0a440 (22 hours ago), 2019-01-16 08:47:37 -0800
    • Engine revision 3c0aa918de
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 492df72739)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/work/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/work/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[!] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone XR • A7D80D85-30D8-4DAA-AB3D-F7FB0B07D57D • ios • iOS 12.1 (simulator)

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment] 2019-01-17 15:05
Might be a regression from #22113

**Comment by lohanidamodar** [comment] 2019-01-17 16:22
Yep having the same issue!

**Comment by zoechi** [comment] 2019-01-17 17:01
@lohanidamodar Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by DrRibosome** [comment] 2019-01-21 22:03
Is there a way to catch the PlatformException? I've tried inserting try/catch for PlatformException at several points, but my test app continues to error with an uncaught PlatformException when I simulate canceling the sign on process by clicking outside the signin dialog box.

**Comment by zoechi** [comment] 2019-02-08 10:02
@benjaminhorner Please check https://github.com/flutter/flutter/issues/27634#issuecomment-461746852

**Comment by nicolasduranl** [comment] 2019-02-14 16:33
I was able to catch the exception by wrapping the invokeMethod call in a try catch in `google_sign_in.dart` file in the package like this:

```dart
// file: package:google_sign_in/google_sign_in.dart
Future<GoogleSignInAccount> _callMethod(String method) async {
    await _ensureInitialized();

    // TODO(amirh): remove this on when the invokeMethod update makes it to stable Flutter.
    // https://github.com/flutter/flutter/issues/26431
    // ignore: strong_mode_implicit_dynamic_method
    try {
      final Map<dynamic, dynamic> response = await channel.invokeMethod(method);
      return _setCurrentUser(response != null && response.isNotEmpty
          ? GoogleSignInAccount._(this, response)
          : null);
    } catch (error) {
      print(error.toString());
      return null;
      // Another option could be rethrowing:
      rethrow;
    }
  }
```

I'm quite new at flutter development and this is probably not an optimal solution but I hope this can help someone else to further solve this problem, as this is a severe crash in a fundamental plugin.

**Comment by benjaminhorner** [comment] 2019-02-15 10:28
@zoechi as I mentioned previously the EXC_BAD_ACCESS error has been resolved by updating the flutter SDK. However, the exception not being caught upon canceling still remains, event after upgrading the google_sign_in package to 4.0.1.

**Comment by basketball-ico** [comment] 2019-03-06 23:01
@nicolasduranl Hi where I put this code :( ?
Thanks

**Comment by basketball-ico** [comment] 2019-03-13 00:23
@zoechi Hello, I am unable to catch this exception :(.
and also when use [sendPasswordResetEmail](https://pub.dartlang.org/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/sendPasswordResetEmail.html) 
Y try to catch `ERROR_INVALID_EMAIL` `ERROR_USER_NOT_FOUND` but i can't

**Comment by inceptusp** [comment] 2019-05-12 13:02
I am having this issue:
![Anotação 2019-05-12 095345](https://user-images.githubusercontent.com/17789155/57582540-50c02280-749c-11e9-9af2-16ea873da0c8.jpg)
I'm using flutter 1.5.4-hotfix2 (the latest on flutter.dev), google-sign-in 4.0.1+3 package and debugging on a Galaxy J6. I've tried every 'catch' combination and none worked, that one in the image was the last try...

**Comment by mikegazzaruso** [comment] 2019-05-12 20:20
@nicolasduranl 's solution is the working one for me (actually using Flutter 1.5.4-hotfix2. You should also handle correctly 
`GoogleSignInAuthentication googleAuth = await googleUser.authentication;`

due the fact the API call returns "null". (i.e.: if (googleUser == null) return null;)

@inceptusp try to rollback to 
`google_sign_in: 3.2.4`

**Comment by inceptusp** [comment] 2019-05-12 21:57
@mikegazzaruso i've tried rolling back and "patching" the `_callMethod` like the @nicolasduranl 's solution, just now, but still throws the exception... Both, 3.2.4 and the one I was using, 4.0.1+3, throws with or without "patching"...

Am I missing something here?

**Comment by mikegazzaruso** [comment] 2019-05-12 22:03
@inceptusp are you sure that Exception you get *after* the workaround is always PlatformException? Please double check it's not "NoSuchAsMethod" Exception (maybe "bad" dealing with subsequent calling methods on a 'null' object)

**Comment by inceptusp** [comment] 2019-05-18 12:28
@mikegazzaruso I'm sure, my function deals with "subsequent calling methods on a 'null' object"... But after break my head with it for a while, I've decided to delete the package, download it again and re-apply the 'patch' and it worked (even on the newest version that I was using, the 4.0.1+3)...

**Comment by sukhcha-in** [comment] 2019-05-27 23:41
@mikegazzaruso yes it is!
![Screenshot_3](https://user-images.githubusercontent.com/26461527/58442236-e1d30280-8106-11e9-93d1-7a5688d1d514.jpg)

**Comment by cyanglaz** [comment] 2019-05-30 18:41
@sukhcha-in @inceptusp  Were you not able to catch the exception? I wonder if what you saw was because you have exception break point enabled in your IDE so it automatically stopped at the exception.

@benjaminhorner Sorry, I am a little lost reading the comments. I would like to understand what your original issue is. The signIn method is designed to throw platform exception if the sign in is cancelled. So you are expected the catch that exception (if you care), and do something about it. You can also ignore this exception and the app should not crash.
Let me know if you have any other concerns.

**Comment by inceptusp** [comment] 2019-05-30 18:58
@cyanglaz no, I've tried many try-catch combinations and none catched the exception... And about the "exception breakpoint", I am using VSCode with default configuration, I've not changed anything besides the theme... This is activated by default? If is, so yes, I am using exception breakpoint without knowing, if isn't, so no, I am not using exception breakpoint...

The only thing that worked to "bypass" the exception was this "patch'' by @nicolasduranl after a "reinstall" of google_sign_in package... Like I said above...

**Comment by feinstein** [comment] 2019-05-30 18:59
@cyanglaz is "The signIn method is designed to throw platform exception if the sign in is cancelled" documented? Because I didn't find it. 

Also, I think it's kinda weird to get a platform exception if a user cancelled the signin. Platform Exceptions IMHO should be used to convey a message that something went wrong while trying to talk to the platform, and should only be sent back to the user if he's trying to communicate directly with the platform, otherwise you are just exposing the inner workings of your library, instead of abstracting away the signin process.

The only way a user of the library can understand that a Platform Exception is related to a Signin Cancellation is if he knows how the signin process actually occurs behind the curtains. So I think another mechanism could be used to convey this behavior, like retuning null, or remapping the exception to a SignInException.

Just my 2 cents.

**Comment by cyanglaz** [comment] 2019-05-30 20:10
@inceptusp I am not sure if the breakpoint is set up by default in VSCode but you can find it out more here:  https://code.visualstudio.com/docs/editor/debugging
@nicolasduranl 's patch (without the `rethrow`) essentially suppress the exception. It is ok to do so if you want to ignore all the exceptions but if you do want to catch the exception and do something in your app, you might want to catch it on your own, or use the `rethrow` in this patch. Hope this helps.

**Comment by cyanglaz** [comment] 2019-05-30 20:18
@feinstein I agree that it should be documented better. 
I checked the implementation and saw that it was intentional to throw exception if there is an error returned from the google sign in library. The way that the method channel was set up only allows us to return one object from the platform. In case an error happens, we return that error from the method channel, which then translated to a `PlatformException` by design. I do think we can make the return type better. 

I don't think directly returning null is a good idea. We want to provide the error information to the developer so they can do custom things. Simply ignore the error might not be in everyone's interest.

Although it will be a break change, another way is to have the signIn method return a response object and have the error as one property of the response. If you'd like to create a PR for a change of how the response is handled, please feel empowered to do so! :)

**Comment by inceptusp** [comment] 2019-05-30 20:48
@cyanglaz I know it suppress the exception, but it was the only try-catch that worked to catch the exception... I have tried, within my code, try { function } catch(e) { print(e); }, same behaviour, try { googleSignIn } catch(e) { print(e); }, same behaviour, googleSignIn().catcherror(), like in the screenshot I sent, same behaviour... Is there another way to do try-catch that I'm not getting?

**Comment by feinstein** [comment] 2019-05-30 20:54
I have had this same issue before, but I can't remember how I fixed it... I think it was related to how Dart process exceptions... I will try to find it here, if I do, I will post it

**Comment by cyanglaz** [comment] 2019-05-30 21:02
@inceptusp I am suspecting that the exception break point is on in your IDE so it stopped at where the exception is thrown. If you directly do a `flutter run` in the terminal, does the app crash or print out any exception back trace?

**Comment by feinstein** [comment] 2019-05-30 21:13
I found my code.

Try this:

```dart
try {
...
} on PlatformException catch (e) {
...
}
```

Instead of what you have right now, which is:


```dart
try {
...
} catch (e) {
...
}
```

Boa sorte ;)

**Comment by sukhcha-in** [comment] 2019-05-31 01:22
@cyanglaz @inceptusp I tried installing app on real device without debugging, it works fine without any exception! Error occurs only when debugging is on. And yes i don't set any break point, it automatically stops (sets break point too) and throws exception in VSCode.
@feinstein Thanks, but your code still throws exception in debug mode 🤓

**Comment by feinstein** [comment] 2019-05-31 04:24
@sukhcha-in the code is supposed to throw an Exception if the user cancelled the signin, it's up to you to understand what the Exception was all about.

Here's a simple version of the code I use for handling the Google Sign In with Firebase Auth:

```dart
Future<void> _signInWithGoogle() async {
    GoogleSignInAccount googleUser;
    try {
      googleUser = await _googleSignIn.signIn();
      if (googleUser == null) {
        // user canceled the sign-in, do your cancellation logic here.
        return;
      }
      GoogleSignInAuthentication googleAuth = await googleUser.authentication;
      AuthCredential credential = GoogleAuthProvider.getCredential(
          accessToken: googleAuth.accessToken,
          idToken: googleAuth.idToken);
      var user = await _auth.signInWithCredential(credential);
      print('Google Sign-In completed!');
      print(user);
    } on PlatformException catch (e) {
      switch (e.code) {
        case 'ERROR_USER_DISABLED':
          print('Google Sign-In error: User disabled');
          break;
        case 'ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL':
          print('Google Sign-In error: Account already exists with a different credential.');
          break;
        case 'ERROR_INVALID_CREDENTIAL':
          print('Google Sign-In error: Invalid credential.');
          break;
        case 'ERROR_OPERATION_NOT_ALLOWED':
          print('Google Sign-In error: Operation not allowed.');
          break;        
        default:
          print('Google Sign-In error');
          break;
      }
      print(e);
    } catch (e) {
      print('Google Sign-In error');
      print(e);
    }
  }
```

I am using this with `firebase_auth: ^0.8.1` and `google_sign_in: ^4.0.1` with no issues.

**Comment by komapeb** [comment] 2019-05-31 15:03
Here's what they're talking about, see the breakpoints tab at the very bottom:

![uncaught_exceptions](https://user-images.githubusercontent.com/3054873/58714503-86866600-83cd-11e9-985a-984233ff256e.PNG)

I think what the guys mean is that it still treats it as an **uncaught exception**, even though `signIn()` is surrounded with a `try...catch` block.

**Comment by feinstein** [comment] 2019-05-31 15:09
I would suggest that this is a bug within the Flutter Platform Channel and the Dart VM for Debugging, and those guys should be included in this discussion.

**Comment by komapeb** [comment] 2019-06-03 15:14
@feinstein I think you're right on this. I don't get it why the `PlatformException` is uncatchable. Maybe someone knows who the guys responsible for maintaining that code are and can tag them.

**Comment by feinstein** [comment] 2019-06-03 16:59
@zoechi, any comments on this?

**Comment by komapeb** [comment] 2019-06-10 17:20
Still no resolution. I guess this issue is related to the `google_sign_in` plugin not forwarding `PlatformException`s or something like it. I tried this simple code:

```dart
var gsi = GoogleSignIn(
  signInOption: SignInOption.standard,
  scopes: ['openid', 'email', 'profile'], // whatever options
);

try {
  print(await gsi.disconnect());
} catch (e, s) {
  print("$e, $s");
}
```

And also with a specified exception type :

```dart
try {
  print(await gsi.disconnect());
} on PlatformException catch (e, s) {
  print("$e, $s");
}
```

Both of these `try...catch` blocks don't catch the exception. Tested in VS Code and Android Studio, with enabled auto breakpoints on uncaught exception.

`flutter doctor -v` output:
```
flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Kristiyan\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.35.0)
    • VS Code at C:\Users\Kristiyan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

It would be great if someone can look into this and give more info on what's happening. I really want to use the 'Sign in with Google' feature.

**Comment by feinstein** [comment] 2019-06-11 04:21
As a curiosity, does your code behaves the same if compiled to Release instead?

**Comment by komapeb** [comment] 2019-06-11 10:42
### Well, oddly enough...

<details>
<summary>spoiler</summary>

*This turned out to be longer than I expected, but it's mostly code and stacktraces, here we go:*

</details>

```dart
// this is executed on a button press
var gsi = GoogleSignIn(
  signInOption: SignInOption.standard,
  scopes: ['openid', 'email', 'profile'], // whatever options here
);
try {
  print(await gsi.disconnect());
} catch (e, s) {
  print("exception handled???");
  print("--------------------");
  print("$e, $s");
}
```

`flutter doctor -v` is the same as above, except:

```
[√] Connected device (1 available)
    • LG H955 • LGH9557d41e271 • android-arm64 • Android 6.0.1 (API 23)
```

`flutter run --release` output:

```
I/flutter (16496): exception handled???
I/flutter (16496): --------------------
I/flutter (16496): PlatformException(status, Failed to disconnect., null), #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564)
I/flutter (16496): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302)
I/flutter (16496): <asynchronous suspension>
I/flutter (16496): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:330)
I/flutter (16496): <asynchronous suspension>
I/flutter (16496): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:218)
I/flutter (16496): <asynchronous suspension>
I/flutter (16496): #4      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:257)
I/flutter (16496): #5      GoogleSignIn.disconnect (package:google_sign_in/google_sign_in.dart:335)
I/flutter (16496): #6      _AppState._firebaseTests (package:[removed intentionally]/main.dart:94)
I/flutter (16496): <asynchronous suspension>
I/flutter (16496): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511)
I/flutter (16496): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566)
I/flutter (16496): #9      GestureRecognizer.invokeCallback (package:flutte
```

### 🎉  So, yes, the exceptions are handled in release mode.

Quite strange. One thing that also caught my attention is that the stack trace stops exactly to where it's copied above, not sure if that helps.

I also tried catching exceptions for `gsi.signIn()`, which works too in release mode.

Another thing to consider is that when running the project in `debug` mode, I get the following:

```
Launching lib\main.dart on LG H955 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.3\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.3\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.3+2\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
...
```

The project is (I think) properly migrated to androidx support libraries, here are the relevant parts of my `pubspec.yaml`:

```yaml
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # http client
  http: ^0.12.0+2

  # bloc (state management)
  bloc: ^0.14.1
  flutter_bloc: ^0.15.0
  equatable: ^0.2.5

  # *** FIREBASE AND  AUTH PROVIDERS
  # firebase
  firebase_core: ^0.4.0+3
  firebase_auth: ^0.11.1+5
  cloud_firestore: ^0.12.1
  google_sign_in: ^4.0.2
  
  # auth providers (add more)
  flutter_facebook_login: ^2.0.1

  # secure local storage for android and ios
  flutter_secure_storage: ^3.2.1+1

  # allows to discover network connectivity (none/wifi/mobile)
  connectivity: ^0.4.3+2
  # checks for data connection (internet)
  # data_connection_checker: any
  # get it from master branch on github (latest build)
  data_connection_checker:
    git:
        url: git://github.com/komapeb/data_connection_checker.git
        ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
```

Some more config files:

`android/gradle.properties`:

```
org.gradle.jvmargs=-Xmx1536M
android.enableJetifier=true
android.useAndroidX=true
```

`android/build.gradle`:

```gradle
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        // https://firebase.google.com/docs/flutter/setup#configure_an_android_app
        classpath 'com.google.gms:google-services:3.2.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

`android\app\build.gradle`

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "[removed intentionally]"
        // minSdkVersion 18 (as apposed to 16 - flutter's advertised minimum)
        // is required for package flutter_secure_storage to work
        minSdkVersion 18
        // adding the below line resolved https://github.com/flutter/flutter/issues/21009 for me.
        multiDexEnabled true
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}

apply plugin: 'com.google.gms.google-services'  // Google Play services Gradle plugin
```

Generally speaking, not using breakpoints on unhandled exceptions is a bad practice, but it seems to be the workaround for now (at least for testing google sign-in flow).

Another thing to consider is that, while canceling the login flow (pressing the back button, or taping outside of the box when the form is presented) in debug mode throws an exception, **in release it does not**. In release it just returns null as the result of the awaited future (i.e. `print(await gsi.signIn()); // prints null`).

It would be nice if things were consistent across debug/release.

As a final note: @feinstein , thank you very much for asking me this question ❤️❤️❤️, it didn't even cross my mind to try it in release mode. I just assumed it would still hang the app.

**Comment by feinstein** [comment] 2019-06-11 16:45
I am glad this worked out. To be honest I kinda remembered reading some time ago, somewhere, someone saying that in Release mode things worked out fine.

@zoechi @cyanglaz I still believe this should be investigated further by the Dart VM team, specially for the discrepancies in Debug and Release mode execution behavior.

**Comment by komapeb** [comment] 2019-06-14 17:40
@feinstein Yes, it's quite irritating to "debug" in release mode (no hot reload), and since this is a officially supported plugin by the Flutter team I'd expect a higher level of attention. But it's also free of charge 😑

**Comment by cyanglaz** [comment] 2019-06-14 22:43
I have raised https://github.com/dart-lang/sdk/issues/37268 with a minimum reproduce case for the `uncaught exception` issue. If you do care about the "uncaught exception" behavior, please follow the other issue.

I am closing this issue now because I don't see any action to take here in the google_sign_in plugin.

I agree that the "uncaught exception" breakpoint might cause some surprises in the development. However, you can still develop on debug mode with the check mark off. Or you can simply ignore the breakpoint.
There are several good work-around provided in this thread. I have tried them and they did suppress the "uncaught exception", so feel free to use them. 

The reason I haven't decided to upstream the workarounds is that: 
If you add it, the "uncaught exception" won't stop anymore if you don't catch it when calling the API.
Consider this:
```dart
await gst.disconnect();
```
When this code throws exception, we want the "uncaught exceptions" breakpoint to stop. However, with the workarounds, the breakpoint won't stop and the app crashes. It might cause difficulties for developers to debug who relies on the breakpoint. 

Please feel free to contribute a PR if you found a solution that can suppress the unwanted "uncaught exceptions" breakpoint but still works in the situation above. I will be very happy to review it.

**Closed by cyanglaz** 2019-06-14 22:43 UTC
Labels: p: firebase, p: first party, p: google_sign_in, plugin, severe: crash

**Comment by komapeb** [comment] 2019-06-14 22:55
So, just to clarify, this is in no way related to the implementation of `google_sign_in`?

**Comment by cyanglaz** [comment] 2019-06-14 23:08
@komapeb The worked arounds provided in this issue like:
```dart
Future<GoogleSignInAccount> _callMethod(String method) async {
    await _ensureInitialized();

    // TODO(amirh): remove this on when the invokeMethod update makes it to stable Flutter.
    // https://github.com/flutter/flutter/issues/26431
    // ignore: strong_mode_implicit_dynamic_method
    try {
      final Map<dynamic, dynamic> response = await channel.invokeMethod(method);
      return _setCurrentUser(response != null && response.isNotEmpty
          ? GoogleSignInAccount._(this, response)
          : null);
    } catch (error) {
      print(error.toString());
      // Another option could be rethrowing:
      rethrow;
    }
  }
```
can suppress the breakpoint but it also has other side effects as I mentioned. There is definitely a way to completely fix it but I have not found anything yet. But the OP is about the cancel method throwing exception which is intended at this point.

My suggestions:
1. For people who don't like the cancel method throwing exception:
If people want to introduce a break change to update the API to make the error to be a part of return value instead of throwing an exception. They can feel free to open an issue and explain the break change and the benefit of it. If we get a lot of thumb-ups we will start working on it or accepting PRs regarding this change. Even it is nice, since it is a break change, I do want to get a matrix to see how many people want the change before breaking everyone.

2. For people want to fix the "uncaught breakpoint" issue:
There are definitely to fix it. I couldn't come up with a quick fix. Please feel free to open another ticket and explain the issue. Depends on the thumb-ups we get, we will prioritize the work to fix it. 

Thank you for understanding!

**Comment by komapeb** [comment] 2019-06-14 23:31
Yes, you're right about ignoring the uncaught exception (in your previous comment). It does its job as a workaround for me.

A change to the API doesn't seem relevant, because (as you said) we can't know how many people will be affected by it, I am against it. It doesn't matter for me how the API is constructed (it's just a couple more lines of code for a `try...catch`).

That being said, I don't think canceling the login flow throws an exception. See this (just tested it):

```dart
print('Trying to sign in with Google.');
GoogleSignInAccount user;
try {
  user = await gsi.signIn();
  print("User is $user.");
} catch (e, s) {
  print('Exception handled.');
  print(e);
  print(s);
}
```

Output: 

```
I/flutter ( 8119): Trying to sign in with Google.
I/flutter ( 8119): User is null.
```

As for opening another issue, I think you already did that (https://github.com/dart-lang/sdk/issues/37268), so I'm tracking it. I suggest all others bothered by the uncatchable PlatformException follow/thumbs-up it too.

**Comment by feinstein** [comment] 2019-07-01 22:54
Apparently the solution is to use `async` `await` with `try` `catch`, instead of `future.then().catchError()`. Are there any Issues yet tracking this change for the Google Sign In and Fireabase Auth libraries?

**Comment by cyanglaz** [comment] 2019-07-01 22:57
@feinstein  I haven't tried but I think future.then().catchError() should also work.

**Comment by feinstein** [comment] 2019-07-01 23:08
@cyanglaz it does work, but it throws the `PlatformException`, they closed #33427 saying that `async` `await` with `try` `catch` won't let the Exceptions escape (which is what we are complaining here) as the VM can see the stack in this case and find a `catch` statement (I am over-simplifying the issue to make a brief point).

**Comment by adrianvintu** [comment] 2019-07-02 10:56
Hello, is there any resolution to this?

If yes, can we get a code sample?

**Comment by komapeb** [comment] 2019-07-02 12:13
@adrianvintu Just ignore the `PlatformException`s thrown from this package in debug. They're not present when compiling for release.

**Comment by adrianvintu** [comment] 2019-07-02 12:42
> @adrianvintu Just ignore the `PlatformException`s thrown from this package in debug. They're not present when compiling for release.

Thank you @komapeb . So I just check for googleUser null in the next instruction?

```
    GoogleSignInAccount googleUser = await googleSignIn.signIn();
    GoogleSignInAuthentication googleAuth = await googleUser.authentication;
```

I actually maybe would have wished to handle the user canceling the sign in.

**Comment by feinstein** [comment] 2019-07-02 14:02
If the user is null, then it canceled, you will get an exception in Debug, but in Release it will work as expected.

**Comment by DanTup** [comment] 2019-07-02 18:22
@cyanglaz 
> @feinstein I haven't tried but I think future.then().catchError() should also work.

@feinstein:
> @cyanglaz it does work, but it throws the PlatformException

Just to clarify, the issue here is that the VM debugger doesn't correctly detect that the exception is handled if it doesn't use `try`/`catch` (but instead uses `.catchError()`) so it pauses on the exception if you have the IDE set to break on "unhandled exceptions" even though the exception is handled.

*It doesn't change the runtime behaviour even in debug mode*. If you click the continue/resume button when it breaks on the exception, it will still behave exactly as it should, it's just a little confusing because the debugger pausing makes it seem like something unexpected is happening.

Using `try`/`catch` will avoid this quirk, as will unticking the option to break on unhandled exceptions (though that'll obviously mean real unhandled exceptions don't cause the debugger to break too - though in Flutter that functionality is of less use because the framework tends to catch the exceptions anyway).

**Comment by feinstein** [comment] 2019-07-02 18:39
@DanTup Perfect summary. 

I would like to suggest then, that in order to avoid future confusions, specially from inexperienced users, it would be nice to implement `try` `catch` instead, in all `.catchError()` occurrences for this library.

**Comment by feinstein** [comment] 2019-07-31 21:38
@cyanglaz I am willing to have a look at the code, could you point me out where in the flutter repository I can find the google signin code? Thanks

**Comment by cyanglaz** [comment] 2019-07-31 21:46
@feinstein it would be here: https://github.com/flutter/plugins/blob/master/packages/google_sign_in/lib/google_sign_in.dart

**Comment by feinstein** [comment] 2019-07-31 21:51
Thanks, I will probably need further help/review as I am new to the whole project, since I don't want to spam everyone here, is it there a better channel for this (slack, gitter, email, etc I don't know what do you prefer/use).

**Comment by cyanglaz** [comment] 2019-07-31 21:54
@feinstein The best way is to create a new issue explaining what you are going to do. And you can cc me in the issue.

**Comment by feinstein** [comment] 2019-07-31 21:56
Will do, thanks a lot.

**Comment by kroikie** [comment] 2019-10-13 18:32
@benjaminhorner

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/501. Any further collaboration will be done there.

**Comment by feinstein** [comment] 2019-10-13 18:39
@kroikie I believe this is actually solved.

PS: wouldn't it be easier to use a "move-bot" to move all those issues?

**Comment by kroikie** [comment] 2019-10-13 20:27
@feinstein Agreed that it is solved but would still like to have Firebase related issues in the FirebaseExtended/flutterfire repo.

"move-bot" may have been easier, but I was under the impression that it required the move to be within the same organization.

**Comment by feinstein** [comment] 2019-10-13 20:30
Hmm, I can't say, never used one.

**Comment by erperejildo** [comment] 2020-08-02 11:24
> @cyanglaz Yes, you're right about ignoring the uncaught exception (in your previous comment). It does its job as a workaround for me.
> 
> A change to the API doesn't seem relevant, because (as you said) we can't know how many people will be affected by it, I am against it. It doesn't matter for me how the API is constructed (it's just a couple more lines of code for a `try...catch`).
> 
> That being said, I don't think canceling the login flow throws an exception. See this (just tested it):
> 
> ```dart
> print('Trying to sign in with Google.');
> GoogleSignInAccount user;
> try {
>   user = await gsi.signIn();
>   print("User is $user.");
> } catch (e, s) {
>   print('Exception handled.');
>   print(e);
>   print(s);
> }
> ```
> 
> Output:
> 
> ```
> I/flutter ( 8119): Trying to sign in with Google.
> I/flutter ( 8119): User is null.
> ```
> 
> (edit: this is the documented behavior, so it's ok, maybe I just misunderstood you)
> 
> As for opening another issue, I think you already did that ([dart-lang/sdk#37268](https://github.com/dart-lang/sdk/issues/37268)), so I'm tracking it. I suggest all others bothered by the uncatchable PlatformException follow/thumbs-up it too.

Not working:

<img width="783" alt="Screenshot 2020-08-02 at 13 23 42" src="https://user-images.githubusercontent.com/5629919/89121905-6b2c5480-d4c3-11ea-92a7-5c7e15b34879.png">

**Comment by raselkhan9560** [comment] 2020-08-24 06:58
Don't worry. It's working fine on release apk. App not crash. On my side It's working fine. 
google_sign_in 4.5.3
