### ISSUE TITLE
engine: "Mac Host Engine" flaky crash on dartdev snapshot

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#81398] opened 2021-04-28 16:57 UTC
[Sample build](https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Host%20Engine/23014/steps?succeeded=true&debug=false)

```
[5718/5876] ACTION //third_party/dart/utils/dartdev:generate_dartdev_snapshot_dill(//build/toolchain/mac:clang_x64)
FAILED: gen/third_party/dart/utils/dartdev/generate_dartdev_snapshot.dart.dill 
python ../../third_party/dart/build/gn_run_binary.py compiled_action /opt/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/dart --depfile=/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/third_party/dart/utils/dartdev/generate_dartdev_snapshot.dart.dill.d --depfile_output_filename=gen/third_party/dart/utils/dartdev/generate_dartdev_snapshot.dart.dill -Dsdk_hash=0546ef6899 --dfe=/opt/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /opt/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/gen_kernel.dart --packages=/opt/s/w/ir/cache/builder/src/third_party/dart/.packages --platform=/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/third_party/dart/utils/dartdev/generate_dartdev_snapshot.dart.dill -Dsdk_hash=0546ef6899 /opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart
Command failed: /opt/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/dart --depfile=/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/third_party/dart/utils/dartdev/generate_dartdev_snapshot.dart.dill.d --depfile_output_filename=gen/third_party/dart/utils/dartdev/generate_dartdev_snapshot.dart.dill -Dsdk_hash=0546ef6899 --dfe=/opt/s/w/ir/cache/builder/src/third_party/dart/tools/sdks/dart-sdk/bin/snapshots/kernel-service.dart.snapshot /opt/s/w/ir/cache/builder/src/third_party/dart/pkg/vm/bin/gen_kernel.dart --packages=/opt/s/w/ir/cache/builder/src/third_party/dart/.packages --platform=/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/vm_platform_strong.dill --no-aot --no-embed-sources --no-link-platform --output=/opt/s/w/ir/cache/builder/src/out/host_debug_unopt/gen/third_party/dart/utils/dartdev/generate_dartdev_snapshot.dart.dill -Dsdk_hash=0546ef6899 /opt/s/w/ir/cache/builder/src/third_party/dart/pkg/dartdev/bin/dartdev.dart
output: 
===== CRASH =====
si_signo=Bus error: 10(10), si_code=2, si_addr=0x112288140
version=2.12.0 (stable) (Thu Feb 25 19:50:53 2021 +0100) on "macos_x64"
pid=21510, thread=3075, isolate_group=main(0x7f8ae3018400), isolate=(nil)(0x0)
isolate_instructions=10fd13880, vm_instructions=10fd13880
  pc 0x0000000110044c67 fp 0x000070000474dde0 dart::GCMarker::MarkObjects(dart::PageSpace*)+0x17d7
  pc 0x00000001100440ca fp 0x000070000474de80 dart::GCMarker::MarkObjects(dart::PageSpace*)+0xc3a
  pc 0x0000000110044818 fp 0x000070000474deb0 dart::GCMarker::MarkObjects(dart::PageSpace*)+0x1388
  pc 0x0000000110016aae fp 0x000070000474df30 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x14e
  pc 0x0000000110016fad fp 0x000070000474df60 dart::ThreadPool::Worker::Main(unsigned long)+0x5d
  pc 0x000000010ff80f98 fp 0x000070000474dfb0 dart::OSThread::GetMaxStackSize()+0xb8
  pc 0x00007fff6da19109 fp 0x000070000474dfd0 _pthread_start+0x94
  pc 0x00007fff6da14b8b fp 0x000070000474dff0 thread_start+0xf
-- End of DumpStackTrace
```

**Comment by zanderso** [comment] 2021-04-28 19:37
Likely a duplicate of https://github.com/flutter/flutter/issues/72047

**Closed by zanderso** 2021-04-28 19:37 UTC
Labels: dependency: dart, engine, team: flakes
