### ISSUE TITLE
Console shows previous run logs

### ISSUE THREAD

**Issue by RaviKavaiya** [flutter/flutter#47907] opened 2019-12-28 05:19 UTC
My flutter doctor -v output :
```
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.19041.1], locale en-IN)
    • Flutter version 1.12.13+hotfix.6 at C:\flutter
    • Framework revision 18cd7a3601 (2 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at D:\Work\Android_SDK\windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = D:\Work\Android_SDK\windows
    • Java binary at: C:\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\android-studio
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\RvK\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 79.0.3945.88
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
```

Whenever I run my application, it shows logs from PREVIOUS run logs even before app started. Same is the case with hot restart.

Note: I have NOT enabled 'verbose logging' option.

Thanks.

**Comment by jonahwilliams** [comment] 2019-12-28 05:25
Duplicate of https://github.com/flutter/flutter/issues/47629

**Closed by jonahwilliams** 2019-12-28 05:25 UTC
