### ISSUE TITLE
Webview_flutter Not working on iOS version 16.5.1

### ISSUE THREAD

**Issue by dhavalsoni2001** [flutter/flutter#130094] opened 2023-07-06 20:25 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Installwebview_flutter: ^4.2.2
2. 
Here is the code which I am trying to run on the device:
```
    late WebViewController controller = WebViewController()
    ..setJavaScriptMode(JavaScriptMode.unrestricted)
    ..setBackgroundColor(const Color(0x00000000))
    ..loadRequest(
      Uri.parse('https://thetechkart.co.in/termsofservice'),
    );

```

In build method

```
  return Scaffold(
      appBar: appBar,
      body: WebViewWidget(
        controller: controller,
      ),
    );
```

3. Use this URL for the reproduce the bug as it's working with google.com:  https://thetechkart.co.in/termsofservice

### Expected results

Page should be rendered.

### Actual results

Currently getting a blank screen.

### Code sample

<details><summary>Code sample</summary>

```dart
   import 'package:TechKart_User/Constants/apiConstant.dart';
import 'package:flutter/material.dart';
// import 'package:flutter_webview_plugin/flutter_webview_plugin.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:webview_flutter_wkwebview/webview_flutter_wkwebview.dart';

class TermAndConditions extends StatelessWidget {


  const TermAndConditions({super.key});

  @override
  Widget build(BuildContext context) {
    late WebViewController controller = WebViewController()
    ..setJavaScriptMode(JavaScriptMode.unrestricted)
    ..setBackgroundColor(const Color(0x00000000))
    ..loadRequest(
      Uri.parse('https://thetechkart.co.in/termsofservice'),
    );
    final appBar = AppBar(
      backgroundColor: Colors.black,
      centerTitle: true,
      leading: InkWell(
        onTap: () {
          Navigator.pop(context);
        },
        child: const Icon(
          Icons.arrow_back,
          color: Colors.white,
        ),
      ),
      title: RichText(
        text: TextSpan(
            style: const TextStyle(
              fontSize: 16,
              color: Colors.grey,
            ),
            children: <TextSpan>[
              TextSpan(
                text: 'Term & Conditions',
                style: TextStyle(
                    color: Colors.white,
                    fontSize:
                        Theme.of(context).textTheme.titleMedium?.fontSize),
              ),
            ]),
      ),
    );

    return Scaffold(
      appBar: appBar,
      body: WebViewWidget(
        controller: controller,
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.11.0-18.0.pre.3, on macOS 13.5 22G5059d darwin-arm64 (Rosetta), locale en-IN)
    • Flutter version 3.11.0-18.0.pre.3 on channel master at /Users/dhavalsoni/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 224667e90f (5 weeks ago), 2023-05-31 04:24:27 -0400
    • Engine revision 5294709d68
    • Dart version 3.1.0 (build 3.1.0-155.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/dhavalsoni/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/dhavalsoni/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/dhavalsoni/Library/Android/sdk
    • Java binary at: /Users/dhavalsoni/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/dhavalsoni/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)            
    • iPhone 14 (mobile) • 40040B4F-8680-44BD-9F46-00D359F79B17 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4
      (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 13.5 22G5059d darwin-arm64 (Rosetta)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dhavalsoni2001** [comment] 2023-07-07 08:26
Thanks for your response @darshankawar. 

Yes, other websites are working perfectly fine only the URL I mentioned is not opening,  though it's working fine on Safari.

**Comment by darshankawar** [comment] 2023-07-07 10:32
@dhavalsoni2001 
What package version are you using ? Is it latest ? Also, can you upgrade to latest master or stable and run scenario again to see if it still persists or not ?

**Comment by stuartmorgan** [comment] 2023-07-07 11:21
Does this website work in a trivial non-Flutter WKWebView application?

**Comment by dhavalsoni2001** [comment] 2023-07-07 12:19
@stuartmorgan  @darshankawar  It's not working with the Native WKWebView application as well.

**Comment by stuartmorgan** [comment] 2023-07-07 12:29
Then the issue is almost certainly with the site (likely browser detection).

Closing as there's nothing the plugin can do if the site doesn't load in WKWebView.

**Closed by stuartmorgan** 2023-07-07 12:29 UTC
Labels: in triage
