### ISSUE TITLE
When I try to use the tab key to convert a character in chrome on mac, it moves to the next focus

### ISSUE THREAD

**Issue by hatano0x06** [flutter/flutter#150253] opened 2024-06-14 10:42 UTC
### Steps to reproduce

1. run `flutter run -d chrome --web-port=5000 --web-renderer=canvaskit`
2. input text "あああ" in first textformfield
3. press tab key to convert characters

### Expected results

The first of the character conversion candidates is selected and moves to the next focus.

### Actual results

Move into a character conversion candidate

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class SamplePage extends StatefulWidget {

  SamplePage(): super();

  @override
  SamplePageState createState() => SamplePageState();
}

class SamplePageState extends State<SamplePage> with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // FocusScope.of(context).requestFocus(new FocusNode());
    // FocusManager.instance.primaryFocus?.unfocus();
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      body: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            padding: EdgeInsets.only(top: 50, left: 20, right: 20),
            color: Colors.red.withOpacity(0.5),
            child: TextFormField(),
          ),
          Container(
            padding: EdgeInsets.only(top: 50, left: 20, right: 20),
            color: Colors.blue.withOpacity(0.5),
            child: TextFormField(),
          ),
        ]
      ),
    );
  }

}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Expected movement video( running in windows ) 

https://github.com/flutter/flutter/assets/7422251/c8cbbb99-4305-44ad-b0af-699fb2f388ca

Actual movement video( running in mac ) 

https://github.com/flutter/flutter/assets/7422251/646ff729-0fb2-49a0-90f8-0eff2ca5b90c

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.22631.3737], locale ja-JP)
    • Flutter version 3.22.1 on channel stable at C:\Users\81708\Desktop\develop\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\81708\AppData\Local\Android\sdk
    • Platform android-34, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.90.0)
    • VS Code at C:\Users\81708\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.90.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3737]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.142
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.92

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-06-14 11:33
This is a duplicate of https://github.com/flutter/flutter/issues/79775. 

Kindly follow up in the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-06-14 11:33 UTC
Labels: in triage
