### ISSUE TITLE
[macOS]: canvas shakes on repaint on latest beta

### ISSUE THREAD

**Issue by likang** [flutter/flutter#112907] opened 2022-10-05 03:22 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample, target macOS
2. Click the `Click Me` button multiple times

**Expected results:** 
a stable canvas

**Actual results:** 
canvas shakes, see the `Hello` text in video

**Additional info:**

- issue found on macOS
- issue not found on Android
- issue disappear if I remove `RepaintBoundary` 
- issue disappear if I do not `scale` the matrix
- issue may disappear if I change the `start` or `end` position of the line

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      title: 'Canvas Stack',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Canvas Stack'),
        ),
        body: const CanvasStack(),
      ),
    );
  }
}

class CanvasStack extends StatefulWidget {
  const CanvasStack({Key? key}) : super(key: key);

  @override
  State<CanvasStack> createState() => _CanvasStackState();
}

class _CanvasStackState extends State<CanvasStack> {
  ValueNotifier<int> repaint = ValueNotifier(0);

  @override
  Widget build(BuildContext context) {
    Matrix4 matrix4 = Matrix4.identity();
    matrix4.scale(1.3, 1.3);

    return Stack(
      fit: StackFit.expand,
      children: [
        Transform(
          transform: matrix4,
          child: RepaintBoundary(child: CustomPaint(painter: StackPainter(repaint: repaint))),
        ),
        Center(
          child: ElevatedButton(
            onPressed: () {
              repaint.value = repaint.value + 1;
            },
            child: const Text("Click Me"),
          ),
        )
      ],
    );
  }
}




class StackPainter extends CustomPainter {
  const StackPainter({ super.repaint });

  @override
  void paint(Canvas canvas, Size size) {
    debugPrint('paint $size');

    Offset start = Offset(30, size.height/2);
    Offset end = Offset(size.width-200, size.height*0.7);

    Path path = Path();
    path.moveTo(start.dx, start.dy);
    path.lineTo(end.dx, end.dy);

    Paint paint = Paint()
      ..style =PaintingStyle.stroke
      ..color = Colors.orange
      ..strokeWidth = 4
      ..strokeCap = StrokeCap.round;
    canvas.drawPath(path, paint);

    TextPainter textPainter = TextPainter(
      text: const TextSpan(text: "Hello",
        style: TextStyle(
          color: Colors.black87,
          fontSize: 14,
        ),
      ),
      maxLines: null,
      textDirection: TextDirection.ltr,
    );
    textPainter.layout();

    textPainter.paint(canvas, start);

  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }

}
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 3.4.0-17.2.pre, on macOS 12.4 21F79 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.4.0-17.2.pre on channel beta at /Users/likang/SDKs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d6260f127f (13 days ago), 2022-09-21 13:33:49 -0500
    • Engine revision 3950c6140a
    • Dart version 2.19.0 (build 2.19.0-146.2.beta)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/likang/SDKs/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 12.4 21F79 darwin-arm
```

</details>

https://user-images.githubusercontent.com/850711/193974197-4d15970d-7a76-4209-93c2-dd436302a145.mov

**Comment by darshankawar** [comment] 2022-10-05 07:47
Thanks for the report. Verified this on latest beta, stable and master and the behavior only occurs on macOS desktop and that too on latest beta.

1. Beta behavior:


https://user-images.githubusercontent.com/67046386/194006829-6222bf16-f32c-4221-9800-bcb0b87c437c.mov


2. Stable and master behavior:


https://user-images.githubusercontent.com/67046386/194006873-faa11b4e-4ff3-4d99-a59e-25178004e65e.mov

Also verified the same on web and mobile, but this behavior doesn't occur on these platforms.

<details>
<summary> beta flutter doctor </summary>

```

[✓] Flutter (Channel beta, 3.4.0-17.2.pre, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.4.0-17.2.pre on channel beta at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d6260f127f (2 weeks ago), 2022-09-21 13:33:49 -0500
    • Engine revision 3950c6140a
    • Dart version 2.19.0 (build 2.19.0-146.2.beta)
    • DevTools version 2.16.0

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 3BD8F2FF-FDB5-4074-8C91-54F99C79156D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     •
      macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript •
      Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 3.3.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.3 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (2 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 3.4.0-40.0.pre.16, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.4.0-40.0.pre.16 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c99780dea8 (45 minutes ago), 2022-10-04 21:41:27 -0700
    • Engine revision 9692f09afd
    • Dart version 2.19.0 (build 2.19.0-273.0.dev)
    • DevTools version 2.18.0
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by darshankawar** [comment] 2022-10-05 07:47
Labeling this as a regression, since this happens on latest beta, but not on other versions.

**Comment by gspencergoog** [comment] 2022-10-06 18:09
(Desktop Triage) Thank you for the report!

However, we are going close this, since it seems to already be fixed on master.  If this re-occurs in a later master, please reopen.

**Closed by gspencergoog** 2022-10-06 18:09 UTC
Labels: severe: regression, framework, engine, platform-mac, a: typography, a: desktop, has reproducible steps, found in release: 3.4
