### ISSUE TITLE
Flutter Crash since 1.7

### ISSUE THREAD

**Issue by Navil** [flutter/flutter#36356] opened 2019-07-17 10:02 UTC
## Steps to Reproduce
```
flutter run 
```
(The app worked perfectly untiI I upgraded Flutter to 1.7)

## command
```
flutter build bundle --target C:\Users\Thomas\Documents\GitHub\appname\lib\main.dart --target-platform android-arm64 --filesystem-scheme org-dartlang-root --depfile C:\Users\Thomas\Documents\GitHub\appname\build\app\intermediates\flutter\debug\android-arm64/snapshot_blob.bin.d --asset-dir C:\Users\Thomas\Documents\GitHub\appname\build\app\intermediates\flutter\debug\android-arm64/flutter_assets --debug
```
## exception
```
NoSuchMethodError: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
```

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Uri._uriEncode (dart:core-patch/uri_patch.dart:44:23)
#2      Uri.encodeFull (dart:core/uri.dart:1145:17)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:40)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      FlutterManifest.assets (package:flutter_tools/src/flutter_manifest.dart:187:11)
#7      _parseAssets (package:flutter_tools/src/asset.dart:559:40)
#8      _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:143:53)
<asynchronous suspension>
#9      buildAssets (package:flutter_tools/src/bundle.dart:136:40)
<asynchronous suspension>
#10     BundleBuilder.build (package:flutter_tools/src/bundle.dart:105:38)
<asynchronous suspension>
#11     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:116:25)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CommandRunner.run (package:args/command_runner.dart:112:14)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1500:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#46     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#47     run (package:flutter_tools/runner.dart:51:10)
#48     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#49     main (file:///D:/Edu/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale de-AT)
    • Flutter version 1.7.8+hotfix.3 at D:\Edu\flutter
    • Framework revision b712a172f9 (8 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\Edu\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\Edu\android-sdk
    • Java binary at: C:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[!] VS Code, 64-bit edition (version 1.35.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Redmi 5 Plus • 35b499480005 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by shajeeck** [comment] 2019-07-21 05:38
found this issue which was caused due to a formatting error in `pubspec.yaml` in my case
Cleared after correcting it

**Comment by iapicca** [comment] 2020-01-16 10:44
Hi @Navil 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by Navil** [comment] 2020-01-16 12:25
> Hi @Navil
> are you still experiencing this issue with the latest stable version of flutter?
> If so could you please provide your updated `flutter doctor -v`
> and your `flutter run --verbose` and a reproducible minimal code sample
> or the steps to reproduce the problem.
> Thank you

Hey, no I do not. It got fixed by itself some versions later.

**Comment by VladyslavBondarenko** [comment] 2020-01-16 12:32
@Navil 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by VladyslavBondarenko** 2020-01-16 12:32 UTC
