### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to get length of null array

### ISSUE THREAD

**Issue by RaviPradad** [flutter/flutter#121813] opened 2023-03-02 17:54 UTC
java.nio.ByteBufferAsIntBuffer.put (ByteBufferAsIntBuffer.java:122)
com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.i (n.java:2)
com.google.maps.api.android.lib6.gmm6.vector.gl.buffer.n.d (n.java:3)
com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.y.s (y.java:16)
com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.s (ao.java:8)
com.google.maps.api.android.lib6.gmm6.vector.bz.s (bz.java:29)
com.google.maps.api.android.lib6.gmm6.vector.bs.b (bs.java:151)
com.google.maps.api.android.lib6.gmm6.vector.av.run (av.java:48)

My apps is  crashing and getting this error ,please reply me someone

**Comment by stuartmorgan** [comment] 2023-03-02 19:34
Duplicate of https://github.com/flutter/flutter/issues/105965

**Closed by stuartmorgan** 2023-03-02 19:34 UTC

**Comment by RaviPradad** [comment] 2023-03-03 05:47
> Duplicate of #105965

Thank you for reply
