### ISSUE TITLE
Flutter Web visual density issue and laggy animation

### ISSUE THREAD

**Issue by Henzelix** [flutter/flutter#77350] opened 2021-03-05 10:34 UTC
I upgraded my web app to Flutter 2.0 stable version and I've got 2 problems.

1. Text and icons are very blurry and thick. Every element on my page got smaller. This image shows the comparison - on the left Flutter 2.0 and on the right Flutter 1.22:
![image](https://user-images.githubusercontent.com/50414544/110103435-3f00eb00-7da6-11eb-85cc-03928f9b741e.png)

2. First animation is always laggy. This wasn't an issue for me in Flutter 1.22

**Comment by darshankawar** [comment] 2021-03-05 11:19
@Henzelix 
Can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the difference / issue ?

**Comment by Henzelix** [comment] 2021-03-05 11:31
@darshankawar I hope that's what you ask for. Even in DartPad you can see that text doesn't look like it should
`Card(
            margin: EdgeInsets.only(top: 15),
                              color: Colors.purple,
                              child: ListTile(
                                
                         
                                title: Text("Test", style: TextStyle(
                                  fontSize: 20,
                                  fontWeight: FontWeight.w600,
                                  color: Colors.white,
                                ),),
                                leading: Column(
                                  children: [
                                    Text("5", style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 29,
                                      fontWeight: FontWeight.bold,
                                    ),),
                                    Text("april", style: TextStyle(
                                      //fontFamily: 'Nunito',
                                      color: Colors.white,
                                    ),),
                                  ],
                                ),
                                trailing: Icon(Icons.edit, color: Colors.white,),
                                subtitle: Text("hgbhrghrgbh", style: TextStyle(
                                  color: Colors.white,
                                ), overflow: TextOverflow.ellipsis, maxLines: 2,),
                                isThreeLine: true,
                              ),
                            )`

**Comment by darshankawar** [comment] 2021-03-05 12:51
@Henzelix 
Web on stable version started from 2.0.0, so how did you compare 1.22 vs 2.0 on web ?

**Comment by Henzelix** [comment] 2021-03-05 12:53
> @Henzelix 
> Web on stable version started from 2.0.0, so how did you compare 1.22 vs 2.0 on web ?
> 

I started this project when Web was in beta. Maybe this wasn't exactly 1.22 (I can't check it) but it was something near that

**Comment by Henzelix** [comment] 2021-03-05 15:45
@darshankawar any idea how to fix it?

**Comment by msoham123** [comment] 2021-03-05 22:35
It could be that before stable you were using one web renderer and after 2.0 you're using a different one. I've seen this level of difference in rendering between canvas kit and HTML renderers. Could you try `flutter run` with `--web-renderer canvaskit` and then with `--web-renderer html`.

**Comment by Henzelix** [comment] 2021-03-05 22:59
> It could be that before stable you were using one web renderer and after 2.0 you're using a different one. I've seen this level of difference in rendering between canvas kit and HTML renderers. Could you try `flutter run` with `--web-renderer canvaskit` and then with `--web-renderer html`.

@msoham123 `--web-renderer html` fixed text issue, but icons are stil blurry and ListTiles are significantly smaller in comparison with my Flutter 1.22 beta version

**Comment by darshankawar** [comment] 2021-03-08 06:11
@Henzelix 
Flutter 1.22 was an older version which isn't compatible or feasible to go back to. 
I tried your code sample on beta 1.26 vs beta 2.0.0 using canvaskit and html renderers, but didn't see any difference.

1. beta 1.26 canvaskit vs html:

<img width="1203" alt="beta_1 26_canvaskit" src="https://user-images.githubusercontent.com/67046386/110281451-c5b20400-8002-11eb-8d24-3ee2717110b2.png">

<img width="1200" alt="beta_1 26_html" src="https://user-images.githubusercontent.com/67046386/110281458-c8acf480-8002-11eb-87dd-e18448eb7c6f.png">

2. beta 2.0.0 canvaskit vs html:

<img width="1200" alt="beta_2_canvaskit" src="https://user-images.githubusercontent.com/67046386/110281481-d6fb1080-8002-11eb-93f0-38772109883b.png">
<img width="1203" alt="beta_2_html" src="https://user-images.githubusercontent.com/67046386/110281489-d8c4d400-8002-11eb-858e-878818ffae4a.png">

If you are running `flutter run -d chrome`, it defaults to canvaskit rendering, so that may be one of the reasons why you may be seeing the difference in text and icons rendering, because canvaskit renders the widgets a bit differently than html.

<details>
<summary>1.26 and 2.0.0 beta flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 1.26.0-17.6.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a29104a69b (3 weeks ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.192

! Doctor found issues in 1 category.

[✓] Flutter (Channel beta, 2.0.0, on Mac OS X 10.15.4 19E2269 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.0 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 60bd88df91 (5 days ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.192

! Doctor found issues in 1 category.

```

</details>

You may try again with 1.26 and 2.0.1 and check if you still see the same behavior or not. If so, provide the details accordingly.

**Comment by msoham123** [comment] 2021-03-08 06:40
@Henzelix  I don't know if this matters, but try running `flutter clean` and see if that changes anything. I don't know much about dart2js and building for web but maybe some old 1.22 build files have remained after the upgrade to 2.0, and that causes these discrepancies.

**Comment by Henzelix** [comment] 2021-03-08 07:23
> @Henzelix  I don't know if this matters, but try running `flutter clean` and see if that changes anything. I don't know much about dart2js and building for web but maybe some old 1.22 build files have remained after the upgrade to 2.0, and that causes these discrepancies. 

@msoham123 already tried it - nothing has changed

**Comment by Henzelix** [comment] 2021-03-08 07:33
> @Henzelix 
> Flutter 1.22 was an older version which isn't compatible or feasible to go back to. 
> I tried your code sample on beta 1.26 vs beta 2.0.0 using canvaskit and html renderers, but didn't see any difference.
> 
> 1. beta 1.26 canvaskit vs html:
> 
> <img width="1203" alt="beta_1 26_canvaskit" src="https://user-images.githubusercontent.com/67046386/110281451-c5b20400-8002-11eb-8d24-3ee2717110b2.png">
> 
> <img width="1200" alt="beta_1 26_html" src="https://user-images.githubusercontent.com/67046386/110281458-c8acf480-8002-11eb-87dd-e18448eb7c6f.png">
> 
> 2. beta 2.0.0 canvaskit vs html:
> 
> <img width="1200" alt="beta_2_canvaskit" src="https://user-images.githubusercontent.com/67046386/110281481-d6fb1080-8002-11eb-93f0-38772109883b.png">
> <img width="1203" alt="beta_2_html" src="https://user-images.githubusercontent.com/67046386/110281489-d8c4d400-8002-11eb-858e-878818ffae4a.png">
> 
> If you are running `flutter run -d chrome`, it defaults to canvaskit rendering, so that may be one of the reasons why you may be seeing the difference in text and icons rendering, because canvaskit renders the widgets a bit differently than html.
> 
> <details>
> <summary>1.26 and 2.0.0 beta flutter doctor -v</summary>
> 
> ```
> [✓] Flutter (Channel beta, 1.26.0-17.6.pre, on Mac OS X 10.15.4 19E2269
>     darwin-x64, locale en-GB)
>     • Flutter version 1.26.0-17.6.pre at /Users/dhs/documents/Fluttersdk/flutter
>     • Framework revision a29104a69b (3 weeks ago), 2021-02-16 09:26:56 -0800
>     • Engine revision 21fa8bb99e
>     • Dart version 2.12.0 (build 2.12.0-259.12.beta)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
>     • Android SDK at /Users/dhs/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.0
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [!] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.3, Build version 12C33
>     ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
>         CocoaPods is used to retrieve the iOS and macOS platform side's plugin
>         code that responds to your plugin usage on the Dart side.
>         Without CocoaPods, plugins will not work on iOS or macOS.
>         For more info, see https://flutter.dev/platform-plugins
>       To upgrade see
>       https://guides.cocoapods.org/using/getting-started.html#installation for
>       instructions.
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.54.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.18.1
> 
> [✓] Connected device (2 available)
>     • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
>       27)
>     • Chrome (web)      • chrome           • web-javascript • Google Chrome
>       88.0.4324.192
> 
> ! Doctor found issues in 1 category.
> 
> [✓] Flutter (Channel beta, 2.0.0, on Mac OS X 10.15.4 19E2269 darwin-x64, locale
>     en-GB)
>     • Flutter version 2.0.0 at /Users/dhs/documents/Fluttersdk/flutter
>     • Framework revision 60bd88df91 (5 days ago), 2021-03-03 09:13:17 -0800
>     • Engine revision 40441def69
>     • Dart version 2.12.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
>     • Android SDK at /Users/dhs/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.0
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [!] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.3, Build version 12C33
>     ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
>         CocoaPods is used to retrieve the iOS and macOS platform side's plugin
>         code that responds to your plugin usage on the Dart side.
>         Without CocoaPods, plugins will not work on iOS or macOS.
>         For more info, see https://flutter.dev/platform-plugins
>       To upgrade see
>       https://guides.cocoapods.org/using/getting-started.html#installation for
>       instructions.
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.54.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.18.1
> 
> [✓] Connected device (3 available)
>     • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
>       27)
>     • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
>       19E2269 darwin-x64
>     • Chrome (web)      • chrome           • web-javascript • Google Chrome
>       88.0.4324.192
> 
> ! Doctor found issues in 1 category.
> 
> ```
> 
> </details>
> 
> You may try again with 1.26 and 2.0.1 and check if you still see the same behavior or not. If so, provide the details accordingly.
> 

@darshankawar Interesting that there is no difference on your computer 🤔 I already switched to 1.26 to continue working my project, but I might comeback to 2.0 in few weeks and check everything once again.

**Comment by pedromassangocode** [comment] 2021-03-30 11:03
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-30 11:03 UTC
Labels: in triage, waiting for customer response
