### ISSUE TITLE
ListView.builder jank when scrolling quickly

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#54195] opened 2020-04-07 14:23 UTC
[video (tested on macos)](https://drive.google.com/file/d/1dGF2pVkZn79XK9MDegypI76GTOXVzyhn/view?usp=sharing)

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyHomePage());
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView.builder(
          itemCount: 10000,
          itemBuilder: (context, index) => Text("$index"),
        ),
      ),
    );
  }
}

```

```
[✓] Flutter (Channel flutter-1.18-candidate.4, v1.18.1-pre.4, on Mac OS X
    10.15.3 19D76, locale de-DE)
    • Flutter version 1.18.1-pre.4 at /Users/valauskasmodestas/Desktop/flutter
    • Framework revision 8f7327f83a (12 hours ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/valauskasmodestas/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_152-ea-b05)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.3 19D76
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by TahaTesser** [comment] 2020-04-07 16:00
Duplicate of [#52207](https://github.com/flutter/flutter/issues/52207)

**Closed by TahaTesser** 2020-04-07 16:00 UTC
