### ISSUE TITLE
[tool_crash] ProcessException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. Command: C:\dev\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 225

### ISSUE THREAD

**Issue by HSSN2003** [flutter/flutter#147512] opened 2024-04-29 10:04 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
 Command: C:\dev\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 225
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:686:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:556:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:685:12)
#6      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:874:37)
#7      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:734:14)
#8      _RecompileRequest._run (package:flutter_tools/src/compile.dart:420:16)
#9      _CompilationRequest.run (package:flutter_tools/src/compile.dart:394:30)
#10     DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:780:23)
#11     _rootRunUnary (dart:async/zone.dart:1407:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#15     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#16     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#17     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#18     _rootRun (dart:async/zone.dart:1391:47)
#19     _CustomZone.run (dart:async/zone.dart:1301:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
```
```
[✓] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.19.5 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (5 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop Windows apps
    ✗ Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 124.0.6367.63
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 124.0.2478.67

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 300451adae589accbece3490f4396f10bdf15e6e

**Comment by danagbemava-nc** [comment] 2024-04-29 12:32
Closing this as a duplicate of https://github.com/flutter/flutter/issues/61997

**Closed by danagbemava-nc** 2024-04-29 12:32 UTC
Labels: in triage
