### ISSUE TITLE
FileUploadInputElement does not always work in Safari

### ISSUE THREAD

**Issue by svprdga** [flutter/flutter#74644] opened 2021-01-25 16:17 UTC
## Steps to Reproduce

1. Create flutter web project.
2. Add a button that triggers a file upload:

```
  _uploadImage() {
    InputElement uploadInput = FileUploadInputElement();
    uploadInput.accept = '.png,.jpg,.jpeg';
    uploadInput.click();

    uploadInput.onChange.listen((e) {
      // read file content as dataURL
      final files = uploadInput.files;
      if (files.length == 1) {
        final file = files[0];
        FileReader reader = FileReader();

        reader.onLoadEnd.listen((e) {
          _bloc.uploadImage(reader.result, file.type);
        });

        reader.onError.listen((fileEvent) {
          _log.e('Error uploading content image: $fileEvent');
        });

        reader.readAsArrayBuffer(file);
      }
    });
  }
```

3. Run the website in Safari (I experience the bug in Safari 14.0.2)
4. Click and select a file to upload

**Expected results:** 

After selecting a file, the onChange listener is triggered.

**Actual results:** 

The onChange listener is not always triggered.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale es-ES)
    • Flutter version 1.25.0-8.3.pre at /Users/svprdga/opt/flutter
    • Framework revision 5d36f2e7f5 (11 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/svprdga/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-01-26 09:07
Hi @svprdga 
Thanks for filing the issue, just created a minimal code sample, running on the same Safari version. it works every time. 

<details>
<summary>code sample</summary>

```dart
import 'dart:html';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String fileType;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text(fileType ?? ""),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          InputElement uploadInput = FileUploadInputElement();
          uploadInput.accept = '.png,.jpg,.jpeg';
          uploadInput.click();

          uploadInput.onChange.listen((e) {
            // read file content as dataURL
            final files = uploadInput.files;
            if (files.length == 1) {
              final file = files[0];
              FileReader reader = FileReader();

              reader.onLoadEnd.listen((event) {
                print(event.timeStamp);
                setState(() {
                  fileType = event.toString();
                });
              });

              reader.onError.listen((fileEvent) {
                print(fileEvent.type);
                setState(() {
                  // fileType = fileEvent.type;
                });
              });

              reader.readAsArrayBuffer(file);
            }
          });
        },
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.3.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 5d36f2e7f5 (11 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-13.0.pre.178, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.178 at /Users/tahatesser/Code/flutter_master
    • Framework revision 22f1700427 (21 minutes ago), 2021-01-26 14:34:03 +0800
    • Engine revision 6e391c5942
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

</details>

Thank you

**Comment by svprdga** [comment] 2021-01-26 09:23
Thanks for the response @TahaTesser, I don't have right now a mac but as soon as I get one I will try your sample and post back the result. Please await for my response before closing this issue.

Thanks.

**Comment by pedromassangocode** [comment] 2021-02-17 09:50
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-17 09:50 UTC
Labels: in triage, waiting for customer response

**Comment by venkatd** [comment] 2021-06-22 22:36
Hi @svprdga while I'm not sure of the exact cause, I can paste some internal code that has worked for us:

```dart
import 'dart:async';
import 'dart:html';

import 'package:turtle_app/file_manager/file_picker/file_picker.dart';
import 'package:turtle_app/util/platform_file/platform_file.dart';

FilePicker getFilePicker() => HtmlFilePicker();

class HtmlFilePicker implements FilePicker {
  @override
  Future<PlatformFile?> getFile(FilePickerSource source) {
    if (source == FilePickerSource.file) {
      final completer = Completer<PlatformFile>();

      final uploadInput = FileUploadInputElement();
      document.body!.append(uploadInput);

      void onUploadInputChange(e) {
        void dispose() {
          uploadInput.removeEventListener('change', onUploadInputChange);
          uploadInput.remove();
        }

        final files = uploadInput.files;
        if (files == null) return completer.complete(null);
        completer.complete(PlatformFile.fromHandleSync(files.first));

        // Add an arbitrary delay to clean up to avoid premature
        // disposal of the element 
        Future.delayed(const Duration(seconds: 1)).then((value) => dispose());
      }

      uploadInput.addEventListener('change', onUploadInputChange);
      uploadInput.click();

      return completer.future;
    }

    throw UnsupportedError('${source} not supported on this platform');
  }
}
```

I'm not sure of the exact cause, but here are some key differences I'm noticing:
- In Safari, it appears input elements may need to be part of the dom to have an effect (https://stackoverflow.com/questions/47664777/javascript-file-input-onchange-not-working-ios-safari-only)
- I use addEventListener which is synchronous. In some browsers, async handlers (such as the `onChange` stream) may not work
- I add the listener *before* calling onClick to ensure proper order of operations
- The dialog can only open in response to a click event due to security reasons

It also looks like this fails only on versions some Safari browsers which make it difficult to reproduce. I'm on 14.0.3 (14610.4.3.1.7). 

The code I'm sharing is coupled to our app, but you can scan through it to see how you might modify your code to match to see if it resolves your issues.
