### ISSUE TITLE
[video_player] Specified video is rotated 180 degrees

### ISSUE THREAD

**Issue by AlexV525** [flutter/flutter#79220] opened 2021-03-28 09:51 UTC
Issue only appeared with a specific video. System's gallery handles correctly.

## Steps to Reproduce

1. Run the example.
2. Play the video, no matter with `.asset`, `.file`, or `.network` with the media uri.
3. The video was rotated 180 degrees.

Or run this [demo](https://github.com/AlexV525/flutter_issue_79220) directly.

System's gallery seems correct.

| Demo | System |
| ------ | ------ |
| ![Screenshot_20210328-172820](https://user-images.githubusercontent.com/15884415/112748349-adc01580-8fed-11eb-99ad-e268a9e4e0a2.jpg) | ![Screenshot_20210328-174714](https://user-images.githubusercontent.com/15884415/112748351-af89d900-8fed-11eb-90fa-2f40d1a0524b.jpg) |

```
[√] Flutter (Channel master, 2.1.0-13.0.pre.293, on Microsoft Windows [Version 10.0.19041.867], locale zh-CN)
    • Flutter version 2.1.0-13.0.pre.293 at J:\SDK\flutter-master
    • Framework revision 304f155ac2 (12 hours ago), 2021-03-27 14:22:36 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Connected device (1 available)
    • IN2020 (mobile)   • 4761b967 • android-arm64  • Android 11 (API 30)
```

**Comment by darshankawar** [comment] 2021-03-29 11:06
@AlexV525 
Does the same behavior occur using `image_picker` plugin [example](https://pub.dev/packages/image_picker/example) ?

**Comment by AlexV525** [comment] 2021-03-29 12:35
Yes. It has the same behavior when testing with the `image_picker` plugin's example.

![Screenshot_20210329-203333](https://user-images.githubusercontent.com/15884415/112837203-2b5b5280-90ce-11eb-8a00-0ceab467c547.jpg)

PS: The video is provided in the previous demo's repo.

**Comment by darshankawar** [comment] 2021-03-29 13:36
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 4d7946a68d (10 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.4.1
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.90

! Doctor found issues in 1 category.

```

</details>

**Comment by KyleFin** [comment] 2021-04-15 03:41
Duplicate of https://github.com/flutter/flutter/issues/60327?

**Comment by maheshmnj** [comment] 2021-06-30 11:42
Hi @AlexV525,
Thanks for filing the issue, There's similar open issue #60327 describing this case, please follow-up in it for further updates. So closing this issue as a duplicate.

If you think this is not the case feel free to write back with relevant details and I will reopen it.

Thank you for your contribution.

**Closed** 2021-06-30 11:43 UTC
Labels: P4, found in release: 2.0, has reproducible steps, p: first party, p: video_player, platform-android, plugin
