### ISSUE TITLE
Tapping with keyboard on

### ISSUE THREAD

**Issue by r4doshka** [flutter/flutter#111735] opened 2022-09-16 08:20 UTC
I need to tap  twice on the button if field focused and keyboard open, the first tap is for dismiss focus, and second is for tapping the button.  Any idea on how to fix it?

**Comment by darshankawar** [comment] 2022-09-16 12:23
@r4doshka 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is not a bug or a feature request.

**Closed by darshankawar** 2022-09-16 12:23 UTC
Labels: in triage
