### ISSUE TITLE
(website) widget "gallery"doesn't have images

### ISSUE THREAD

**Issue by ph-hs** [flutter/flutter#722] opened 2015-12-04 11:35 UTC
gallery implies images.

There's a huge percentage of people won't continue reading without seeing visuals. The FuseTools people got this right in the first launch of their site - the QML people never have in 6 or so years.

**Comment by abarth** [comment] 2015-12-04 16:50
Yeah, we definitely want image in the widget gallery.  We're working on a companion app so you can interact with the widgets on a device.  Once we have that, we'll take screenshots of it for the web site.

**Comment by sethladd** [comment] 2016-01-28 22:51
Closing as a dupe of https://github.com/flutter/flutter/issues/1433

But yes, moar screenshots! :)

**Closed by sethladd** 2016-01-28 22:51 UTC
Labels: affects: dev experience, affects: docs, ⚠ clear documentation
