### ISSUE TITLE
Camera: 0.6.1 -> 0.6.2.1 CameraValue with property isTakingPicture allway true

### ISSUE THREAD

**Issue by trantrongkim98** [flutter/flutter#72920] opened 2020-12-24 09:43 UTC
# Camera version 0.6.1 -> 0.6.2.1 property isTakingPicker alway is true
- Source Code
```
Future<XFile> takeImage()async{
    /// the line code below alway is true
    if (controller.value.isTakingPicture) return null; 
    return await controller.takePicture();
  }
```
- when i try ignore condition then i see log

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)
```

## Description 

- Device: Vsmart Live

- OS: Android 10

- flutter doctor -v

```
✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/pro2014/flutter
    • Framework revision 7891006299 (2 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pro2014/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • Live (mobile) • AHW00019835 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by danielroek** [comment] 2020-12-24 11:54
Been able to reproduce this issue. takePicture() never completes. 
In main.dart debugPrint prints false once. Stays true after that.  
 ```
 Future<XFile> takePicture() async {
    if (!controller.value.isInitialized) {
      showInSnackBar('Error: select a camera first.');
      return null;
    }
    debugPrint('isTakingPicture is ${controller.value.isTakingPicture.toString()}');

    if (controller.value.isTakingPicture) {
      // A capture is already pending, do nothing.
      return null;
    }

    try {
      XFile file = await controller.takePicture();
      return file;
    } on CameraException catch (e) {
      _showCameraException(e);
      return null;
    }
  }
```
in camera_controller.dart `takePicture is called` gets printed. The other prints are never reached.
```
Future<XFile> takePicture() async {
    if (!value.isInitialized || _isDisposed) {
      throw CameraException(
        'Uninitialized CameraController.',
        'takePicture was called on uninitialized CameraController',
      );
    }
    if (value.isTakingPicture) {
      throw CameraException(
        'Previous capture has not returned yet.',
        'takePicture was called before the previous capture returned.',
      );
    }
    try {
      debugPrint('takePicture called');
      value = value.copyWith(isTakingPicture: true);
      XFile file = await CameraPlatform.instance.takePicture(_cameraId);
      value = value.copyWith(isTakingPicture: false);
      debugPrint('takePicture done');
      return file;
    } on PlatformException catch (e) {
      value = value.copyWith(isTakingPicture: false);
      debugPrint('takePicture error');
      throw CameraException(e.code, e.message);
    }
  }
```

**Comment by mvanbeusekom** [comment] 2020-12-24 12:47
duplicate of #72649, we will be submitting a fix today. Thank you for raising the issue.

**Closed by mvanbeusekom** 2020-12-24 12:47 UTC
