### ISSUE TITLE
SliverList through SliverPersistentHeader

### ISSUE THREAD

**Issue by zzzj1233** [flutter/flutter#49968] opened 2020-02-02 10:37 UTC
code
```
CustomScrollView(
        slivers: <Widget>[
          SliverPersistentHeader(
            pinned: true,
            delegate: SliverCustomHeaderDelegate(
                title: "每日推荐",
                collapsedHeight: 30,
                expandedHeight: 150,
                paddingTop: MediaQuery.of(context).padding.top,
                coverImgUrl: "images/onlytheyoung.jpg"),
          ),
          SliverPersistentHeader(
            floating: false,
            pinned: true,
            /// StickyHeaderDelegate : maxExtent&minExtent = fixedHeight,build=>child
            delegate: StickyHeaderDelegate(
                child: Container(
                  height: 50,
                  color: Colors.transparent,
                  child: Text("SliverPersistentHeader",style: TextStyle(fontSize: 20),),
                ),
                fixedHeight: 50),
          ),
          SliverFixedExtentList(
            itemExtent: 50,
            delegate: SliverChildBuilderDelegate(
              (context, index) {
                return Container(
                  height: 50,
                  child: Text(index.toString()),
                );
              },
              childCount: 20,
            ),
          )
        ],
      )
```

show

![show](https://user-images.githubusercontent.com/44407821/73607131-542ca880-45ed-11ea-8b53-96f5dab0b5a3.gif)

What I want to achieve

![want](https://user-images.githubusercontent.com/44407821/73606963-1890df00-45eb-11ea-9565-dd5bae1c5282.gif)

**Comment by zzzj1233** [comment] 2020-02-02 10:49
[√] Flutter (Channel stable, v1.9.1, on Microsoft Windows [Version 10.0.18362.592], locale zh-CN)
    • Flutter version 1.9.1 at D:\flutter
    • Framework revision c382b8e990 (6 months ago), 2019-08-18 15:22:36 -0400
    • Engine revision 5540684152
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\android-sdk-windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\android-sdk-windows
    • Java binary at: D:\java\jdk\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[!] Connected device
    ! No devices available

**Comment by zzzj1233** [comment] 2020-02-02 10:49
```
[√] Flutter (Channel stable, v1.9.1, on Microsoft Windows [Version 10.0.18362.592], locale zh-CN)
    • Flutter version 1.9.1 at D:\flutter
    • Framework revision c382b8e990 (6 months ago), 2019-08-18 15:22:36 -0400
    • Engine revision 5540684152
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\android-sdk-windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\android-sdk-windows
    • Java binary at: D:\java\jdk\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.1
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[!] Connected device
    ! No devices available
```

**Comment by dnfield** [comment] 2020-02-02 20:06
This would be a more suitable question for a site like StackOverflow.

Since this is not a bug or a feature request, I'm closing this issue.

**Closed by dnfield** 2020-02-02 20:06 UTC
Labels: created via support template

**Comment by adnankhan74444** [comment] 2020-08-28 20:04
@zzzj1233 did you find this solution i am also looking for this functionality ?

**Comment by omidraha** [comment] 2021-03-13 20:55
Related link:  [Here](https://github.com/SmallStoneSK/flutter_training_app/blob/master/lib/sliver_widgets/custom_sliver_header_usage.dart)
