### ISSUE TITLE
Navigator.of(context).push() Throws Failed assertion: line 5531 pos 12: '!_debugLocked': is not true.

### ISSUE THREAD

**Issue by noahwons** [flutter/flutter#152510] opened 2024-07-29 21:30 UTC
### Steps to reproduce

In Android Studio
Create a separate file containing details for a stateless material button with an onPressed function as a required parameter.
Create an instance of the material button in a separate class and pass in a Navigator.of(context).push() function for the on pressed parameter.

### Expected results

It is expected that the onPressed function can accept a Navigator.of(context).push() function to redirect the user to a new stateful screen when the button is pressed.

### Actual results

Without calling the stateless material button and instead providing the same code the Navigator.of(context).push() function works as expected. In this case I pass in CupertinoPageRoute(builder: (context) => PlaceHolderScreen(),)  for the push function.

### Code sample

<details open><summary>Code sample</summary>

```dart
// Class declatation
class RoundedButton extends StatelessWidget {
  final Function onPressed;
  final String text;
  final Color color;
  final Color textColor;
  const RoundedButton(
      {super.key,
      required this.onPressed,
      required this.text,
      required this.color,
      required this.textColor});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 24.0, horizontal: 20),
      child: Material(
        borderRadius: const BorderRadius.all(Radius.circular(30)),
        color: color,
        child: MaterialButton(
          height: 50,
          onPressed: onPressed(),
          child: Text(
            text,
            textAlign: TextAlign.center,
            style: TextStyle(
              color: textColor,
              fontSize: 20.0,
            ),
          ),
        ),
      ),
    );
  }
}

// Function call in separate file
RoundedButton(
            onPressed: () {
              Navigator.of(context).push(CupertinoPageRoute(
                builder: (context) => WorkoutFrequencyScreen(),
              ));
            },
            text: 'Next',
            color: Colors.black,
            textColor: Colors.white,
          )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

</details>

### Logs

<details open><summary>Logs</summary>

```console
Performing hot reload...
Syncing files to device Android SDK built for x86...
Reloaded 14 of 1101 libraries in 464ms (compile: 53 ms, reload: 149 ms, reassemble: 176 ms).

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#f98d8](dirty, dependencies: [HeroControllerScope, UnmanagedRestorationScope], state: NavigatorState#b4f80(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5531 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/Users/noahw/StudioProjects/nutrition_ai/lib/main.dart:36:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5531:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5599:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#11     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#12     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#27     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#35     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#39     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#43     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#47     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#50     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#52     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#56     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#60     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#65     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#69     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#73     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#78     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#81     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#82     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#86     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#90     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#95     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#97     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#104    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#107    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#109    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#112    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#114    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#117    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#118    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#121    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#123    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#125    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#127    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#128    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#129    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#130    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#133    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#135    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#138    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#140    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#144    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#147    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#148    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#149    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#151    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#155    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#156    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#159    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#160    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#161    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#162    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#164    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#165    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#166    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#169    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#170    StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#172    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#173    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#175    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#176    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#177    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#180    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#182    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#185    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#186    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#187    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#188    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#190    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#191    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#192    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#194    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#195    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#196    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#197    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#198    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#199    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#200    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#201    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#203    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#204    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#205    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#207    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#208    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#209    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#212    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#213    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#214    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#216    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#217    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#218    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#221    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#222    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#223    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#224    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#225    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:14)
#226    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#227    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#228    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#229    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#230    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#233    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#234    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#235    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#238    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#239    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#240    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#242    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#243    ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#245    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#246    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#247    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#248    StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:5)
#249    Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#251    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#252    Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#253    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
#254    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:21)
#255    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#256    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#257    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#258    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1035:9)
#259    PlatformDispatcher.scheduleWarmUpFrame.<anonymous closure> (dart:ui/platform_dispatcher.dart:837:16)
#263    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
====================================================================================================

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
The most similar command is
        diagnose
PS C:\Users\noahw\StudioProjects\nutrition_ai\android> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.22631.3880], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2024.1)
[√] VS Code (version 1.91.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-30 07:02
Closing this as a duplicate of https://github.com/flutter/flutter/issues/151571

**Closed by danagbemava-nc** 2024-07-30 07:02 UTC
Labels: in triage
