### ISSUE TITLE
[tool_crash] UnknownException

### ISSUE THREAD

**Issue by rgjurgens** [flutter/flutter#131297] opened 2023-07-25 22:10 UTC
## Command
```
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d web-server --no-headless
```

## Steps to Reproduce
1. Run the chromedriver (for Chrome Version 115.0.5790.102)
2. Run the above command
3. And crash!

The terminal also shows this error message:
```
Oops; flutter has exited unexpectedly: "UnknownException (500): unknown error: cannot find Chrome binary".
A crash report has been written to /Users/*/dev/flutter_test/yetsa/flutter_10.log.
```

## Logs
UnknownException
```
#0      parseW3cResponse (package:webdriver/src/handler/w3c/utils.dart:102:9)
#1      W3cSessionHandler.parseCreateResponse (package:webdriver/src/handler/w3c/session.dart:19:21)
#2      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:106:34)
#3      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#4      createDriver (package:webdriver/async_core.dart:62:19)
<asynchronous suspension>
#5      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:145:19)
<asynchronous suspension>
#6      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:332:30)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.10.1, on macOS 13.4 22F66 darwin-arm64, locale en-NL)
    [32m•[39m Flutter version 3.10.1 on channel stable at /Users/rjurgens/dev/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision d3d8effc68 (2 months ago), 2023-05-16 17:59:05 -0700
    [32m•[39m Engine revision b4fb11214d
    [32m•[39m Dart version 3.0.1
    [32m•[39m DevTools version 2.23.1

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 14.3.1)
    [32m•[39m Xcode at /Applications/Xcode 14.2.app/Contents/Developer
    [32m•[39m Build 14E300c
    [32m•[39m CocoaPods version 1.11.3

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.74.3)
    [32m•[39m VS Code at /Users/rjurgens/Downloads/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m macOS (desktop)  • macos      • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    [32m•[39m Web Server (web) • web-server • web-javascript • Flutter Tools
    [32m•[39m Chrome (web)     • chrome     • web-javascript • Google Chrome 115.0.5790.102

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: d3d8effc686d73e0114d71abdcccef63fa1f25d2
### Plugins
integration_test

**Comment by darshankawar** [comment] 2023-07-26 07:28
Closing this as a duplicate of https://github.com/flutter/flutter/issues/123602.
Also see https://github.com/flutter/flutter/issues/123602#issuecomment-1490895875 for solution and check if it works for you. You may also share your findings in the linked issue.

**Closed by darshankawar** 2023-07-26 07:28 UTC
Labels: in triage

**Comment by damcur** [comment] 2023-07-26 09:50
Hello @darshankawar 
I have the same problem after upgrading Chrome and chromedriver from v113 to v115. However, I'm not using the selenium. Flutter crashes just after
`fvm flutter drive --target=test_driver/app.dart --browser-name=chrome --web-renderer=html --debug -d web-server`
on newest Chrome version. 

Sorry, but I don't get the solution from #123602. Should we just wait for the newer Chrome version? 

Thanks in advance for your help
