### ISSUE TITLE
[flutter_web] Flutter web application totally crashes browser (Chrome/Edge) after weeks

### ISSUE THREAD

**Issue by mikron123** [flutter/flutter#74568] opened 2021-01-23 16:17 UTC
I created a flutter web application/website with Firebase. 
The website is running great, however, for some users, the site totally CRASHES THE BROWSER during login process after a few weeks they have been using it almost every day.

By crashing I mean that you can see the circular loading widget I put in the website during its loading, and then the whole browser is crashing without any notice!

If the user tries to open it again, it will keep on crashing.
If the user will clean the caches and history of the browser, access the website, and login. it will work great again.. until the next crash a couple of weeks later.

How do I even tackle the issue if the browser doesn't remain open?

Channel master, 1.24.0-4.0.pre.57

**Comment by iapicca** [comment] 2021-01-23 16:52
> I created a flutter web application/website with Firebase.

[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)
or provide your `flutter doctor -v`, your `flutter run -d chrome -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without 3rd party plugins

**Comment by mikron123** [comment] 2021-01-23 17:15
How can I provide reproducible code if  I can reproduce it as I've said.. the infrastructure is Flutter and it's pretty safe to say a browser crash is due to Flutter not Firebase.
The issue happened to only 2 out of 10 users twice a month while using it daily. It never happened to me.

Channel master, 1.24.0-4.0.pre.57
Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

I don't have more details since I switched a version to Beta to see if it is going to happen again.

**Comment by iapicca** [comment] 2021-01-23 17:45
@mikron123 
can you provide any `crashlog`?

**Comment by mikron123** [comment] 2021-01-23 18:44
No, as crashlog on users chrome is disabled. I updated to Beta channel, the user refreshed with Ctrl+F5, it still crashes

**Comment by msoham123** [comment] 2021-01-23 18:44
Are you storing sensitive data in cookies? Because a similar thing had happened to a web app I'm developing and the cause was that doing a certain action removed an essential cookie, and the app depended on said cookie when other cookies were still present. Although, I don't know why that would crash the browser. The bug I had in my code would only crash my app.

**Comment by iapicca** [comment] 2021-01-23 19:15
@mikron123 
I'm not sure if the issue can be workable without any `logs` / `crashlogs` or `repro code`
especially considering that **the crash might not be cause by flutter itself**, 
but come from 3rd party plugins such as `firebase`

is @msoham123 's explaination describe your case?
> [...] a certain action removed an essential cookie, and the app depended on said cookie when other cookies were still present.

**Comment by mikron123** [comment] 2021-01-23 19:23
Deleting the cookies and site data solves it. Until it happens again.
 @msoham123's case doesn't make sense for mine, it crashed directly in the login page. 
we're also using https://jsstore.net/ but it's not even loaded via the flutter pages, but with another JS page on the same domain, so I doubt the problem is there. 

I will try to update the firebase plugins. There's a change it happens just after the initialization process which relies on Firebase, as the UI is shown for a second or two.
Thanks

**Comment by TahaTesser** [comment] 2021-01-25 09:46
Hi @mikron123 
As @iapicca mentioned, to better address the issue, we need the details from https://github.com/flutter/flutter/issues/74568#issuecomment-766164439
Let us know if you isolate the cause of the issue and if it occurs within Flutter without Firebase 
Thank you

**Comment by pedromassangocode** [comment] 2021-02-17 09:46
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-17 09:46 UTC
Labels: in triage, waiting for customer response
