### ISSUE TITLE
Flutter layout not updated when Large iOS custom keyboard is dismissed.

### ISSUE THREAD

**Issue by coldstar96** [flutter/flutter#99951] opened 2022-03-11 03:35 UTC
## Steps to Reproduce
Keyboard dismiss is not handled properly for iOS custom keyboards. If you look at second video, it seems like the issue happens if the custom keyboard height is too large when dismissed.

Precondition: Download custom keyboards: [Bitmoji](https://apps.apple.com/us/app/bitmoji/id868077558), [Slyder](https://apps.apple.com/us/app/slyder/id1121553033)
1. Copy paste [main.dart](https://gist.github.com/coldstar96/13efc23e0d9a8ffb8b1b5b23b8bc7cb7) to new project
2. Follow steps

|  |  | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/3282437/157796438-1ba7671d-77cb-4955-a925-8818ffec03cf.MP4" /> | <video src="https://user-images.githubusercontent.com/3282437/157796912-ba368451-774d-4475-96aa-355648e9d371.MP4" /> |

**Expected results:** Lays out widgets properly when keyboard is dismissed

**Actual results:** It doesn't listen to keyboard dismiss when custom keyboard is too large.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Container(
        color: Colors.blue.shade100,
        child: Column(
          children: [
            const SizedBox(height: 48),
            const Padding(
              padding: EdgeInsets.symmetric(horizontal: 16),
              child: Text(
                '1. Change iOS keyboard to Bitmoji or Slyder keyboard.\n'
                '2. Tap on the button below.\n'
                '3. Navigate back to previous route.\n'
                '4. Check that shaded blue(Scaffold.body) not covering entire screen.\n'
                '5. Compare the behavior with OS keyboard',
                style: TextStyle(fontSize: 20),
              ),
            ),
            const TextField(autofocus: true),
            const Spacer(),
            ElevatedButton(
              onPressed: () {
                FocusScope.of(context).unfocus();
                Navigator.of(context).push(CupertinoPageRoute(
                  builder: (context) {
                    return const MyHomePage(title: 'Another Page');
                  },
                ));
              },
              child: const Text('Hello', style: TextStyle(fontSize: 30)),
            )
          ],
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
        items: [Icons.abc, Icons.train]
            .map((e) => BottomNavigationBarItem(icon: Icon(e), label: 'hi'))
            .toList(),
      ),
    );
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment] 2022-03-11 10:29
Hi @coldstar96, thanks for reporting this. 

Please provide the output of `flutter doctor -v`. 

Thank you

**Comment by coldstar96** [comment] 2022-03-11 21:05
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.1 21C52 darwin-arm, locale en-US)
    • Flutter version 2.10.3 at /Users/c/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (9 days ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/c/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 99.0.4844.51
    ! Error: ABC X is not connected. Xcode will continue when ABC X is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by danagbemava-nc** [comment] 2022-03-14 06:38
Hi @coldstar96, I'm attempting to reproduce but it doesn't seem to occur for me. Kindly check the video below and let me know if I'm missing something 

https://user-images.githubusercontent.com/88313112/158117831-f04fe874-42d5-48a4-9fab-00740c33277d.MP4

**Comment by coldstar96** [comment] 2022-03-18 04:21
hmm.. I'm not sure if there's additional environment but it seems like @luckysmg was able to repro from https://github.com/flutter/engine/pull/31982

If this helps, my device is iPhone 13 pro max, iOS 15.3.1

**Comment by luckysmg** [comment] 2022-03-18 04:51
Yes, @coldstar96 @danagbemava-nc I can reproduce this issue.
My test device is iPhone13 Pro. iOS 15.4

**Comment by danagbemava-nc** [comment] 2022-03-18 07:05
Hmm, you both appear to be using a variation of iPhone 13, perhaps this only affects newer iphones? 
I tested on an iPhone XS with the sample provided by @luckysmg  and I still was unable to reproduce it. 


<details>
<summary>video</summary>

<video src="https://user-images.githubusercontent.com/88313112/158952937-9fc5f160-fa3f-4167-a5ec-b75b0b449430.MP4" />

</details>

> If his change seems reasonable, would you be able to approve it?

The reviewers will make that decision. 

Labeling this for further investigation as I cannot reproduce this locally.

**Comment by chinmaygarde** [comment] 2022-03-21 18:14
cc @LongCatIsLooong

**Comment by luckysmg** [comment] 2022-04-01 00:19
Fixed by https://github.com/flutter/engine/pull/31982

**Comment by danagbemava-nc** [comment] 2022-04-01 06:23
@luckysmg thanks for your contribution.

**Closed by danagbemava-nc** 2022-04-01 06:23 UTC
Labels: a: text input, platform-ios, engine, waiting for PR to land (fixed), severe: rendering, P4
