### ISSUE TITLE
[iOS][Impeller] The `FilterQuality` of `Transform` causes the child widget not to be displayed.

### ISSUE THREAD

**Issue by AmosHuKe** [flutter/flutter#132750] opened 2023-08-17 14:31 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Flutter 3.13.0
Use code sample.

### Expected results

Display normally.

### Actual results

https://github.com/flutter/flutter/assets/32262985/09d2bd16-f06f-4467-a8a0-d445bc68b9fa

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

final filterValueNotifier = ValueNotifier<FilterQuality>(FilterQuality.none);
final useNullFilterValueNotifier = ValueNotifier<bool>(false);

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Demo')),
        floatingActionButton: Column(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            FloatingActionButton(
              heroTag: 'Use null',
              onPressed: () {
                useNullFilterValueNotifier.value =
                    !useNullFilterValueNotifier.value;
              },
              child: const Text('Null'),
            ),
            const SizedBox(height: 20),
            FloatingActionButton(
              heroTag: 'Filter quality',
              onPressed: () {
                filterValueNotifier.value = FilterQuality.values[
                    (filterValueNotifier.value.index + 1) %
                        FilterQuality.values.length];
              },
              child: const Text('Filter'),
            ),
          ],
        ),
        body: ValueListenableBuilder(
          valueListenable: useNullFilterValueNotifier,
          builder: (context, useNull, child) {
            return Center(
              child: ValueListenableBuilder(
                valueListenable: filterValueNotifier,
                builder: (context, value, child) {
                  return Column(
                    children: [
                      Text('Using null filter quality: $useNull'),
                      const SizedBox(height: 10),
                      Text('Filter value: $value'),
                      const SizedBox(height: 50),
                      Transform(
                        filterQuality: useNull ? null : value,
                        alignment: Alignment.center,
                        transform: Matrix4.identity()
                          ..setEntry(3, 2, 0.001)
                          ..rotateX(0.8)
                          ..rotateY(0.8),
                        child: Stack(
                          children: [
                            child!,
                            Transform(
                              filterQuality: useNull ? null : value,
                              transform: Matrix4.identity()
                                ..translate(15.0, 15.0),
                              child: const Text('Demo'),
                            ),
                          ],
                        ),
                      ),
                    ],
                  );
                },
                child: Container(
                  width: 350,
                  height: 200,
                  color: Colors.blueAccent,
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F82 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.13.0 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (2 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Platform android-33, build-tools 33.0.
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web

[✓] Android Studio (version 2021.3)
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.81.1)
    • Flutter extension version 3.70.0
```

</details>

**Comment by huycozy** [comment] 2023-08-18 06:17
Hi @AmosHuKe 
This issue seems to have been fixed on the latest master channel as I cannot reproduce it there.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/baf82142-1fde-4140-9e08-7525c4446514
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (25 hours ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-7.0.pre.19, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-7.0.pre.19 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 03664d0acb (19 minutes ago), 2023-08-18 04:58:20 +0200
    • Engine revision 866b43f656
    • Dart version 3.2.0 (build 3.2.0-83.0.dev)
    • DevTools version 2.26.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

I'll close this issue as fixed on the latest channels. If you still experience this issue, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2023-08-18 06:17 UTC
Labels: in triage

**Comment by AmosHuKe** [comment] 2023-08-18 09:37
@huycozy Thanks for the reply, `master` channel fixed it. I can display it normally now.
