### ISSUE TITLE
[ios][path_provider] Not working if ran on isolate (MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider))

### ISSUE THREAD

**Issue by brunodmn** [flutter/flutter#99683] opened 2022-03-07 14:07 UTC
**Describe the error**
Trying to use path_provider  with workmanager on iOS.
In my mainframe I can inject and use the path_provider, but when I trigger it from workmanager it wont work at all. Already tried `flutter clean/get`, `flutter pub cache repair`, close and reopen emulator and IDE..nothing works.

Here is a minimum code to reproduce: [link](https://github.com/brunodmn/flutter_path_test)
1 - created new flutter project
2 - added packages workamanager/path_provider
3 - initialized workmanager and setup iOS especific configuration
4 - opened xcode, ran the project then selected `debug>simulate background fetch`
5 - expected to see successful return with path created, but actually see `MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)`

**Output of `flutter doctor -v`**
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.1 21C52 darwin-arm, locale en-BR)
    • Flutter version 2.10.2 at /Users/brunoandrade/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/brunoandrade/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

**Comment by stuartmorgan** [comment] 2022-03-07 15:36
Duplicate of https://github.com/flutter/flutter/issues/99155

**Closed by stuartmorgan** 2022-03-07 15:36 UTC
