### ISSUE TITLE
Webview does not scroll smoothly

### ISSUE THREAD

**Issue by soyangel** [flutter/flutter#27180] opened 2019-01-28 11:52 UTC
Scrolling on the webview example is not smooth, also happens with animations. Compare with a native webview embedded on an Android app.

Will it be possible to have smooth scroll using webview or it is a known limitation of platform views?

## Steps to Reproduce

- Compile webview example https://github.com/flutter/plugins/tree/master/packages/webview_flutter/example
- Run and try scrolling (e.g. loading a webpage like https://flutter.io)

## Logs

Analyzing example...                                             
No issues found! (ran in 4.6s)

```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale es_ES.UTF-8)
    • Flutter version 1.0.0 at /home/angel/flutter/soft/flutter
    • Framework revision 5391447fae (hace 8 semanas), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/angel/android/soft/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/angel/android/soft/sdk
    • Java binary at: /home/angel/android/soft/android-studio-3.2/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/angel/android/soft/android-studio-3.1
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.2)
    • Android Studio at /home/angel/android/soft/android-studio-3.2
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 2.3)
    • Android Studio at /home/angel/android/soft/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • ONEPLUS A3003 • c0fc1ff3 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by matthewlloyd** [comment] 2019-05-12 22:04
I took a look into this hoping I could fix it, since it will affect my upcoming app release. It seems that pointer motion events from the Android OS are intercepted by https://github.com/flutter/engine/blob/master/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java where they are encoded and forwarded to the Flutter engine. Flutter then runs the GestureDetectors and gesture arenas on the events. If no Flutter views absorb the events, the PlatformView re-encodes them and sends them back to the Android engine host. My guess is that some information gets lost in the process, which prevents fling scroll gestures working for WebViews and perhaps other PlatformViews too. They work fine on iOS, but the architecture is different.

**Comment by amirh** [comment] 2019-05-13 17:00
Thanks for reporting, which device are you running on? also it would help to better understand what do you mean by not smooth if you can share screen recordings showing the Flutter and the pure Android webview scrolling on that device.

**Comment by matthewlloyd** [comment] 2019-05-13 17:34
Thanks for the reply, Amir. Scratch that, my bad, in the process of putting together an example app to demonstrate the issue, I figured out the problem. The HTML I was loading had the following buried under mountain of CSS:

```
body {
  overflow: hidden;
}
```

Removing that line fixed the scrolling and now it is smooth with nice fling gesture physics just as it should be.

Curiously, with `overflow: hidden`, I also noticed that the scroll distance was incorrect, e.g. if I moved the pointer by 10 pixels, the view would scroll by about 20-30 pixels. This is on a Pixel 3 with a `2.75` pixel density. It may be a bug in the underlying Android `WebView` implementation. It worked fine on iOS.

**Comment by amirh** [comment] 2019-05-13 17:43
@matthewlloyd can you file a separate issue for the scroll distance? (ideally with a minimal code sample to reproduce the issue).

@soyangel - if you still see the issue can you post screen recordings?

Thanks!

**Comment by matthewlloyd** [comment] 2019-05-13 20:09
@amirh done!

**Comment by soyangel** [comment] 2019-05-13 20:20
Just tried with Flutter 1.5.4-hotfix.2 running the example on https://github.com/flutter/plugins/tree/master/packages/webview_flutter/example on a Pixel 3a and it's smooth like butter. Good job!

So I guess we can close this if you like so.

Thanks for your hard work on Flutter it's appreciated.

**Comment by amirh** [comment] 2019-05-13 20:39
Thanks @soyangel please close the issue if you believe it is fixed.

**Closed** 2019-05-13 20:41 UTC
Labels: p: first party, p: webview, plugin

**Comment by x4080** [comment] 2019-05-16 23:55
Hi, I think the laggy webview is still happening compared to like flutter_webview which is not using platformview ? Is it because flutter intercept the gesture first then send it to the native webview ? Is there any switch to disable the intercept, so it goes directly to webview ?

**Comment by grandleaf** [comment] 2019-07-19 18:56
When creating a WebView, do this:
WebView(
.........
gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
          Factory<OneSequenceGestureRecognizer>(() => EagerGestureRecognizer()),
        ].toSet(),
)

**Comment by x4080** [comment] 2019-07-21 22:09
@grandleaf Thanks for the suggestion I'll try it

**Comment by TEENSTITAN** [comment] 2019-09-04 08:51
> When creating a WebView, do this:
> WebView(
> .........
> gestureRecognizers: <Factory>[
> Factory(() => EagerGestureRecognizer()),
> ].toSet(),
> )

NOT work on me!

**Comment by figo-fe** [comment] 2020-03-27 11:05
not work for me too
