### ISSUE TITLE
Flutter keeps getting stuck in "Syncing files to device" when installing app on a real iOS Device. 

### ISSUE THREAD

**Issue by real1900** [flutter/flutter#65746] opened 2020-09-14 07:08 UTC
I see : 

**Running Xcode build...
Xcode build done.                                           426.0s
Installing and launching...
Waiting for Suleman’s iPhone  to report its views...
Debug service listening on ws://localhost:59585/ws
Syncing files to device Suleman’s iPhone ...**

Flutter doctor shows: 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.5 19F101, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.2)
[✓] Connected device (4 available)
    ! Error: Suleman’s iPhone 6s is not connected. Xcode will continue when Suleman’s iPhone 6s is connected. (code -13)

• No issues found!

**Comment by ykrank** [comment] 2020-09-14 08:43
this bug make my app could not debug in ios

**Comment by pedromassangocode** [comment] 2020-09-14 10:49
Hi @real1900 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and your `pubspec.yaml`.
Thank you

**Comment by lvlrSajjad** [comment] 2020-09-14 17:25
I have this problem too
This is my flutter doctor:
```
 flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.3 at /Users/lvlrx/development/flutter
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lvlrx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Sajjad Asadi’s iPhone (mobile) • cd1ab62b9ce2e34bb73637391f9e97b36cf2ce2c • ios • iOS 13.6

• No issues found!
lxvr.xaus@Sajjads-MacBook-Pro pmx_flutter_v2 % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.3 at /Users/lvlrx/development/flutter
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lvlrx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Sajjad Asadi’s iPhone (mobile) • cd1ab62b9ce2e34bb73637391f9e97b36cf2ce2c • ios • iOS 13.6

• No issues found!
```
This is my pubspec.yaml
```
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.3+200113

environment:
  sdk: ">=2.2.2 <3.0.0"
#  flutter: ^1.17.0

dependencies:
  flutter:
    sdk: flutter
  inject:
    path: ./injection/inject.dart/package/inject
  apple_sign_in: 0.1.0
  audioplayers: 0.16.1
  cached_network_image: 2.3.2+1
  #  carousel_slider: 1.4.1
  cloud_firestore: 0.14.0+2
  cloud_functions: 0.6.0
  connectivity: 0.4.9+2
  country_pickers: 1.3.0
  cupertino_icons: 1.0.0
  device_id: 0.2.0
  device_info: 0.4.2+7
  firebase_ml_vision: 0.9.6+2
  #  firebase_admob: 0.9.3+4
  firebase_analytics: 6.0.0
  firebase_auth: 0.18.0+1
  firebase_core: 0.5.0
  firebase_crashlytics: 0.1.4+1
  firebase_messaging: 7.0.0
  firebase_performance: 0.4.0
  firebase_remote_config: 0.4.0
  firebase_storage: 4.0.0
  flare_flutter: 2.0.6
  flash: 1.3.1
  flutter_cache_manager: 1.4.2
  flutter_facebook_login: 3.0.0
  #  flutter_ip: 0.2.0
  flutter_native_splash: 0.1.9
  flutter_secure_storage: 3.3.3
  flutter_slidable: 0.5.7
  #  flutter_svg: 0.17.4
  font_awesome_flutter: 8.8.1
  geocoder: 0.2.1
  geohash: 0.2.1
  geolocator: 6.0.0+4
  geocoding: 1.0.3
  google_sign_in: 4.5.3
  googleapis: 0.55.0
  http: 0.12.2
  image_cropper: 1.3.1 # Don't upgrade this plugin to 1.3.0 because it has a pod problem
  image_downloader: 0.20.0
  image_picker: 0.6.7+7
  #  in_app_purchase: ^0.3.4+1
  intl: 0.16.1
  #  json_serializable: 3.1.0
  local_auth: 0.6.3+1
  location: 3.0.2
  location_permissions: 3.0.0+1
  material_design_icons_flutter: 3.4.5045+1 # For now, it is better to stick with this version because It seems new version changed icon names - - 7 may 2020
  package_info: 0.4.3
  path: 1.7.0
  path_provider: 1.6.14
  permission_handler: 5.0.1+1
  photo_view: 0.10.2
  reorderables: 0.3.2
  rxdart: 0.24.1
  sembast: 2.4.7+6
  share: 0.6.5
  shared_preferences: 0.5.10
  store_redirect: 1.0.2
  transparent_image: 1.0.0
  url_launcher: 5.5.3
  vibration: 1.4.0
  smooth_page_indicator: 0.2.0
  flutter_app_badger: 1.1.2
  rate_my_app: 0.7.1+1
  agora_rtc_engine: 3.0.1-dev.7
  carousel_slider: 2.2.1
  auto_animated: 2.1.0
  circular_countdown_timer: 0.0.6
  #  flutter_inapp_purchase: 2.2.0
  purchases_flutter: 1.2.1
  sembast_cloud_firestore_type_adapters:
    git:
      url: git://github.com/tekartik/sembast_flutter_more.dart
      path: cloud_firestore_type_adapters
      ref: dart2
    version: '>=0.1.0'
#  flutter_voip_push_notification: 0.0.3
#  flutter_call_kit: 0.0.2
#  flutter_callkit_voximplant: 1.1.0+2
#  algolia: 0.1.7
#  clipboard_manager: ^0.0.4
#  flutter_google_places: 0.2.3
#  flutter_twitter_login: 1.1.0
#  geoflutterfire: 2.0.3+8
#  toast: 0.1.5
#  video_player: 0.10.5
#dependency_overrides:
#  firebase_core: 0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
#  build_runner: 1.10.0
  inject_generator:
    path: ./injection/inject.dart/package/inject_generator
#  cloud_firestore_mocks: 0.4.1
#  firebase_storage_mocks: 0.1.0
#  google_sign_in_mocks: 0.1.0+2
#  firebase_auth_mocks: 0.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/countries.json
    - assets/no_profile_picture.png
    - assets/notification.mp3
    - assets/soft_notification.mp3
    - assets/matched.mp3
    - assets/message.mp3

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

**Comment by sommestad** [comment] 2020-09-15 06:10
Same thing happens for me:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale sv-SE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.5)
 
[✓] Connected device (2 available)   
```

**Comment by real1900** [comment] 2020-09-15 07:30
Thank you @pedromassangocode 

My flutter doctor - v : 

sulemanimdad@Sulemans-MacBook-Pro ios % flutter doctor -v
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.5 19F101, locale en)
    • Flutter version 1.21.0-9.2.pre at /Users/sulemanimdad/Developer/flutter
    • Framework revision 81a45ec2e5 (3 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/sulemanimdad/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • 36F2010B-46A9-44A7-A07E-2427487E6E0D • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 85.0.4183.102
    ! Error: Suleman’s iPhone  is not connected. Xcode will continue when Suleman’s iPhone  is connected. (code -13)
    ! Error: Suleman’s iPhone 6s is not connected. Xcode will continue when Suleman’s iPhone 6s is connected. (code -13)

• No issues found!


My Yaml file : 


name: submission_flutter
description: Submission App built using Flutter and Dart

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  flutter_compass: ^0.4.2
  provider: ^4.0.0
  location: ^3.0.0
  intl: ^ 0.16.1
  shared_preferences: ^0.5.6+3
  percent_indicator: ^2.1.1
  hijri: ^0.2.5
  geocoder: ^0.2.1
  line_awesome_icons: ^1.0.4+2
  google_maps_flutter: ^0.5.28
  google_maps_flutter_web: ^0.1.0 #for displaying on the web with the regular build - missing markers
  google_maps: ^3.4.5 # stricty being used just for building with web only
  vibration: ^1.2.4
  firebase_core: any
  firebase_auth: any
  firebase_auth_platform_interface: any
  firebase_auth_web: any
  cloud_firestore: ^0.13.4+2
  cached_network_image: ^2.3.1 #to use cached images
  flutter_playout: ^1.0.38  # for Video Player
  dart_notification_center: ^1.0.0+1  # for event Notifications within the code for media player etc
  marquee_flutter: ^0.1.4 # for sliding text in Media Player
  flutter_sound: any #audio
  path_provider: ^1.6.1 #audio
  path: ^1.6.4 #audio
  google_fonts: ^0.4.0 #for fonts
  transparent_image: ^1.0.0 # for placeholders
  wakelock: ^0.1.4+1 # prevents app from sleeping
  flutter_local_notifications: ^1.4.4+2 # for salat Notifications
  audioplayers: ^0.15.1
  flutter_tts: ^1.0.0
  flutter_staggered_animations: ^0.1.2
  animate_do: ^1.7.2
  flutter_share: ^1.0.2+1
  html: ^0.14.0+3 #for appendix cleaning
  device_info: ^0.4.2+4
  rxdart: ^0.24.1 #for combining streams
  webview_flutter: ^0.3.22+1 #for Appendices
  scrollable_positioned_list: ^0.1.6 # for jumping inside listview == REMOVE LATER
  scroll_to_index: ^1.0.6 # for jumping inside listview  == BEST CHOICE
  recase: ^3.0.0 #convert cases for Google Fonts /camel case etc
  sembast: ^2.4.7+6 #search Quran
  dynamic_text_highlighting: ^2.2.0 #search Quran highlight text
  just_debounce_it: ^3.0.0+2 #debouncing for better search experience
  background_fetch: ^0.5.1 #used for background task of updating text
  epub: ^2.1.0
  flutter_widget_from_html_core: ^0.4.3
  websafe_platform: ^1.0.2 #for switching to web
  native_pdf_view: ^3.8.0
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.3
  apple_sign_in: ^0.1.0
  firebase_dynamic_links: ^0.3.0
  flutter_facebook_login: ^3.0.0
  indexed_list_view: ^1.0.9 # for jumping inside listview


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "images/Icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/

  fonts:
    - family:  NafeesNastaleeq
      fonts:
       - asset: fonts/nafees_nastaleeq.ttf
    - family:  IranNastaleeq
      fonts:
       - asset: fonts/iran_nastaleeq.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by pedromassangocode** [comment] 2020-09-15 11:25
Hi @real1900 
Are you able to reproduce the issue by running `flutter run --verbose`?

**Comment by bazinac** [comment] 2020-09-17 16:41
Hi, hitting this as well with Android Studio on Mac.

`fluter doctor -v`

```
[✓] Flutter (Channel beta, 1.22.0-12.1.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-12.1.pre at /Users/vocom.studio/SW/flutter
    • Framework revision 8b3760638a (2 days ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vocom.studio/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Vojtech - iPhone (mobile) • 00008030-000C4C3C0213802E • ios • iOS 14.0
```

Had that with stable and iOS 13.7 device as well.

**Comment by real1900** [comment] 2020-09-17 17:10
I am running Android Studio

**Comment by real1900** [comment] 2020-09-17 17:11
I also get the same behavior with VSCode

**Comment by pedromassangocode** [comment] 2020-09-18 06:35
I noticed that you was running on a physical device, are you having the same issue using a simulator? What is the OS version of the device you are having this issue?

**Comment by dodatw** [comment] 2020-09-21 06:31
I also get the same behavior with Android Studio.
But I only can reproduce when Run debug by IDE.
If run by "flutter run -v", seem no this issue.
BUT,  I saw this log, I don't know if helpful.
 (app can use, bug log stuck at "Updating files.")

```
[  +65 ms] Updating files
[+239030 ms] Error writing "build/flutter_assets/images/btn_setting_n.png" to DevFS: HttpException: , uri = http://localhost:57657
```
Note: the "file path" different every times.

**Comment by hossam-zaki** [comment] 2020-09-23 01:13
I have this problem as well. I do not get this issue on the simulator, but I do when running on an external ios device

**Comment by pedromassangocode** [comment] 2020-09-23 07:42
I’m unable to reproduce the issue to pinpoint the cause, but there are reports from several users. The issue needs further investigation.

**Comment by dodatw** [comment] 2020-09-23 08:03
I think it should be same issue, 
https://github.com/flutter/flutter/pull/66152

**Comment by hossam-zaki** [comment] 2020-09-24 06:03
@pedromassangocode They way it messes up for me is that I connect my phone (iPhone SE first gen running iOS 13) to my computer. I do ```flutter run -d all``` and it doesn't work for me at all. I would really appreciate someone to look into this or try to reproduce it as well because it's a pain to always use the simulator, especially with regard to features like camera, texting, etc...

**Comment by pedromassangocode** [comment] 2020-09-24 07:31
Hi @hossam-zaki 
Please file a new issue for this and completely fill out the template. We don't track more than one problem in a GitHub issue as they may be duplicates of different existing issues, or may need different teams to look at them.

**Comment by pedromassangocode** [comment] 2020-09-29 10:16
Updating title since this seems to be happening on VS code as well.

**Comment by jmagman** [comment] 2020-09-29 21:38
I agree with @dodatw, this looks like a duplicate of https://github.com/flutter/flutter/issues/65402 

This should be alleviated with https://github.com/flutter/flutter/pull/66152, which is available on the [master channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels), and was just [hotfixed to the beta channel](https://github.com/flutter/flutter/pull/66849) (it's kind of weird but it hasn't made it to dev yet, but it will be there soon).

**Closed by jmagman** 2020-09-29 21:38 UTC
Labels: P4, platform-mac, tool, will need additional triage

**Comment by AriesL-ux** [comment] 2021-01-12 03:23
I have this problem as well.My  flutter run --verbose
 #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      DeviceManager._chooseOneOfAvailableDevices (package:flutter_tools/src/device.dart:288:7)
           <asynchronous suspension>
           #2      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:276:43)
           <asynchronous suspension>
           #3      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:1001:48)
           #4      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:351:21)
           <asynchronous suspension>
           #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:933:11)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:836:33)
           <asynchronous suspension>
           #7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
           #9      _rootRun (dart:async/zone.dart:1190:13)
           #10     _CustomZone.run (dart:async/zone.dart:1093:19)
           #11     _runZoned (dart:async/zone.dart:1630:10)
           #12     runZoned (dart:async/zone.dart:1550:10)
           #13     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
           #14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:825:20)
           #15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
           #16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:335:21)
           #17     _rootRunUnary (dart:async/zone.dart:1198:47)
           #18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #25     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
           #26     _rootRunUnary (dart:async/zone.dart:1198:47)
           #27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #28     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #30     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #31     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #32     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #33     _rootRun (dart:async/zone.dart:1190:13)
           #34     _CustomZone.run (dart:async/zone.dart:1093:19)
           #35     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by eliysha** [comment] 2021-01-17 18:41
Hi

Same issue here, I've switched on beta and master channels but still the same problem 

How to fix ?

Thx

**Comment by mohamedsamirmohamedsalem** [comment] 2021-01-20 14:01
flutter clean 
invalidate cache and restart 
flutter pub get 
flutter run

**Comment by guihackmann** [comment] 2021-04-07 17:55
Hi all,

I had the same situation today, and took me a few hours to find out the solution, and it was very simple.

I basically started building a loop, then got distracted with something else, and forgot to delete it.

So what caused my "Syncing files to device" not to finish, and my initial page to freeze, was this. I had an infinite loop in my Home initState.

Hope this helps someone.

**Comment by alhafoudh** [comment] 2021-05-28 18:22
This is still an issue :( It happens only on iOS device and iOS Simulator for me.
I tried both Intel Mac and M1 Mac. I am using flutter 2.2.1. I have tried it with flutter 2.2.0. Same behavior.

**Comment by santhoshsail2c** [comment] 2021-07-20 18:02
> This hot reload issue is still happening. It happens only on iOS device and iOS Simulator for me.
> I tried both Intel Mac and M1 Mac. I am using flutter 2.2.1. I have tried it with flutter 2.2.0. Same behavior.
> 
> Android device and Android Emulator are working fine with hot reload.

+1
