### ISSUE TITLE
[tool_crash] ProcessException: The directory name is invalid. Command: C:\opt\flutter_windows_2.0.5-stable\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 267

### ISSUE THREAD

**Issue by cloosli** [flutter/flutter#80933] opened 2021-04-22 09:42 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. Followed the instruction on https://flutter.dev/docs/get-started/install/windows
2. Run flutter doctor

## Logs
ProcessException: The directory name is invalid.
 Command: C:\opt\flutter_windows_2.0.5-stable\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 267
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:39:20)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:282:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:222:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/cache.dart:774:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:562:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
```
```
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-CH)
    • Flutter version 2.0.5 at C:\opt\flutter_windows_2.0.5-stable\flutter
    • Framework revision adc687823a (6 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\christian.loosli_wab\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.128
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 89.0.774.77

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by cloosli** [comment] 2021-04-22 09:47
$ where flutter dart
C:\opt\flutter_windows_2.0.5-stable\flutter\bin\flutter
C:\opt\flutter_windows_2.0.5-stable\flutter\bin\flutter.bat
C:\opt\flutter_windows_2.0.5-stable\flutter\bin\dart
C:\opt\flutter_windows_2.0.5-stable\flutter\bin\dart.bat

**Comment by TahaTesser** [comment] 2021-04-22 09:48
duplicate of https://github.com/flutter/flutter/issues/80418

**Closed by TahaTesser** 2021-04-22 09:48 UTC
Labels: in triage

**Comment by cloosli** [comment] 2021-04-22 10:00
My solution was to install the dart sdk. I don't know why this is not mentioned in the installtion guide.
After I installed the dart sdk flutter doctor worked. So make sure you have dart.exe at the end of your path
$ where flutter dart
C:\opt\flutter\bin\flutter
C:\opt\flutter\bin\flutter.bat
C:\opt\flutter\bin\dart
C:\opt\flutter\bin\dart.bat
C:\opt\dart-sdk\bin\dart.exe
