### ISSUE TITLE
upgrade to 1.12.13+hotfix.5 , flutter run apk always crashed

### ISSUE THREAD

**Issue by lalilajiao** [flutter/flutter#48010] opened 2019-12-31 08:13 UTC
## step

1. first i upgrade to 1.12.13+hotfix.5
2. i work well in debug mode for all devices
3. when i run "flutter run apk" the apk crashed on the devices

**Target Platform:Android
**Devices:physical devices

## device info

```
model: HUAWEI Mate 20 Pro
system version: 10.0 
```

## crash logs

```
1 java.lang.IllegalStateException:Instancing transport exception, e.n.b.b.i.<init> [class java.lang.String, interface e.n.b.e.a.a, class java.lang.Class]
--
2 e.n.b.f.b.c.a(:12)
3 ......
4 Caused by:
5 java.lang.NoSuchMethodException:e.n.b.b.i.<init> [class java.lang.String, interface e.n.b.e.a.a, class java.lang.Class]
6 java.lang.Class.getConstructor0(Class.java:2332)
7 java.lang.Class.getConstructor(Class.java:1728)
8 e.n.b.f.b.c.a(:9)
9 e.n.b.f.b.c.<init>(:7)
10 e.n.b.f.b.a.b.<init>(:1)
11 e.n.b.f.b.a.a.a(:1)
12 e.n.b.b.f.w(:3)
13 e.n.b.b.f.onServiceConnected(:12)
14 android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2037)
15 android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2069)
16 android.os.Handler.handleCallback(Handler.java:888)
17 android.os.Handler.dispatchMessage(Handler.java:100)
18 android.os.Looper.loop(Looper.java:213)
19 android.app.ActivityThread.main(ActivityThread.java:8147)
20 java.lang.reflect.Method.invoke(Native Method)
21 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
22 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

## flutter run --verbose

```
[  +37 ms] executing: [/Users/zhancheng/Tools/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/Users/zhancheng/Tools/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +33 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[  +10 ms] executing: [/Users/zhancheng/Tools/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/zhancheng/Tools/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +66 ms] executing: [/Users/zhancheng/Tools/flutter/] git rev-parse --abbrev-ref HEAD
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +10 ms] executing: sw_vers -productName
[  +25 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +21 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G95
[  +38 ms] executing: /usr/bin/xcode-select --print-path
[  +17 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +232 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.2.1
           Build version 11B53
[  +84 ms] executing: /Users/zhancheng/Library/Android/sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /Users/zhancheng/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           3EP7N19507005213       device usb:337641472X product:LYA-AL00 model:LYA_AL00 device:HWLYA transport_id:16
[  +27 ms] executing: /Users/zhancheng/Tools/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +57 ms] /usr/bin/xcrun simctl list --json devices
[ +169 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +4 ms] /Users/zhancheng/Library/Android/sdk/platform-tools/adb -s 3EP7N19507005213 shell getprop
[  +54 ms] ro.hardware = kirin980
[        ] ro.build.characteristics = default
[   +5 ms] LYA AL00          • 3EP7N19507005213                     • android-arm64 • Android 10 (API 29)
[        ] iPhone 11 Pro Max • FE4473B5-D372-4FE3-B6E7-CA33B190A469 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
[  +16 ms] "flutter run" took 814ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/zhancheng/Tools/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)
```

**Comment by JonathanJude** [comment] 2020-01-01 01:07
i also have this issue.

**Comment by jmagman** [comment] 2020-01-02 21:32
I know this isn't what you are reporting, but the `flutter run` logs aren't useful because it's missing a `-d` device flag:
```
More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
```
Can you also resolve the Android licensing issue and paste the output of `flutter doctor -v`?

**Comment by ericalderman-emilio** [comment] 2020-01-02 21:38
I'm having this same issue.  Nothing significant has changed except upgrading to 1.12.13+hotfix.5.  Works fine in testing on simulators and attached devices, but when I create a release APK and release through Firebase Distribution to a device,  get only a brief flash of the splash screen of the app and then crashes.

Here's output of my flutter doctor -v:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/ericalderman/development/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ericalderman/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • LG H918 • LGH918d6f4b171 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by shadyshrif** [comment] 2020-02-05 10:34
Same issue here

**Comment by azhanglongfei** [comment] 2020-02-10 05:27
> Same issue here



> i also have this issue.

Is there a solution

**Comment by shadyshrif** [comment] 2020-02-10 18:12
I downgraded to flutter `v1.9.1+hotfix.6` everything worked perfect again!

**Comment by jmagman** [comment] 2020-02-10 19:27
@shadyshrif @JonathanJude  @azhanglongfei 
We weren't able to get enough information from the issue author to make this bug actionable.  Can any of you give us reproduction steps?  Or more context from `flutter run --verbose`?

**Comment by goderbauer** [comment] 2020-03-18 22:07
@jmagman Did you mean to keep this one open? Looks like there's still no additional information posted that would help in debugging this. Should this still be "waiting for customer response"?

**Comment by jmagman** [comment] 2020-03-18 22:52
@goderbauer I asked for more information on Feb 10, but wasn't waiting for a response from the originator @lalilajiao, I didn't want it to close if @shadyshrif @JonathanJude @azhanglongfei responded.  It's been more than 21 days though so I'll close.

**Comment by jmagman** [comment] 2020-03-18 22:52
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-03-18 22:52 UTC
Labels: framework, severe: crash, severe: regression, ▣ platform-android
