### ISSUE TITLE
Multi-touch gesture on Windows not working.

### ISSUE THREAD

**Issue by SahajRana** [flutter/flutter#47939] opened 2019-12-29 10:24 UTC
Hi Flutter team, It's been great using Flutter for development. I just got stuck on Flutter for Windows. How can we detect multi-finger gesture on touchpad like for zoom purposes? (Single touch gesture works, but not multi-gesture). Thanks!

**Comment by stuartmorgan** [comment] 2019-12-31 03:55
Duplicate of https://github.com/flutter/flutter/issues/23604

**Closed by stuartmorgan** 2019-12-31 03:55 UTC
Labels: f: gestures, proposal, severe: new feature, ❖ platform-windows
