### ISSUE TITLE
could not read recipe result file at "C:\b\s\w\ir\tmp\recipe-result.json"

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#69435] opened 2020-10-30 20:10 UTC
Multiple reports (from different PRs) of LUCI windows framework presubmit infra failures (across different shards) failing to find the file recipe-result.json.

https://ci.chromium.org/p/flutter/builders/try/Windows%20Plugins/977?
https://ci.chromium.org/p/flutter/builders/try/Windows%20tool_tests/4974?
https://ci.chromium.org/p/flutter/builders/try/Windows%20framework_tests/4209?

**Comment by zanderso** [comment] 2020-10-30 20:11
Duplicate of https://github.com/flutter/flutter/issues/69434

**Closed by zanderso** 2020-10-30 20:11 UTC
Labels: team: infra

**Comment by christopherfujino** [comment] 2020-10-30 20:19
beat me by a minute :)
