### ISSUE TITLE
State.setState Null check operator used on a null value

### ISSUE THREAD

**Issue by Shubham-Narkhede** [flutter/flutter#117138] opened 2022-12-15 12:55 UTC
Getting issue _Null check operator used on a null value_ on **setState**. I don't know why this issue getting on the production release app. These issues are not printing on the console. We integrated sentry in the app on the sentry console these issues are reported

**Comment by exaby73** [comment] 2022-12-15 14:14
Hello @Shubham-Narkhede . Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by Shubham-Narkhede** [comment] 2022-12-15 15:09
@exaby73 Bro, This issue happening on the production app not from the local so maybe this will not helpful but still will share u

**Comment by Shubham-Narkhede** [comment] 2022-12-15 15:10
<details><summary>CLICK ME</summary>
<p>

#### We can hide anything, even code!

```ruby
   puts "Hello World"
```

</p>
</details>

**Comment by Shubham-Narkhede** [comment] 2022-12-15 15:12
<details><summary>flutter doctor -v</summary>
<p>
 
```ruby
   [✓] Flutter (Channel stable, 3.3.9, on Linux Mint 20 5.4.0-56-generic, locale en_GB.UTF-8)
    • Flutter version 3.3.9 on channel stable at /home/vltp001/flutter_3.3.9/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/vltp001/Android/Sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /home/vltp001/Desktop/Shubham/android_studio_setup/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    • pkg-config version 0.29.1
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[✓] Android Studio (version 4.2)
    • Android Studio at /home/vltp001/Desktop/Shubham/android_studio_setup/android-studio
    • Flutter plugin version 56.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 20 5.4.0-56-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.52

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</p>
</details>

**Comment by Shubham-Narkhede** [comment] 2022-12-15 15:13
<details><summary>flutter run -v</summary>
<p>
 

```ruby
[  +48 ms] executing: uname -m
[  +26 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +5 ms] executing: [/home/vltp001/flutter_3.3.9/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b8f7f1f9869bb2d116aa6a70dbeac61000b52849
[        ] executing: [/home/vltp001/flutter_3.3.9/flutter/] git tag --points-at b8f7f1f9869bb2d116aa6a70dbeac61000b52849
[  +14 ms] Exit code 0 from: git tag --points-at b8f7f1f9869bb2d116aa6a70dbeac61000b52849
[        ] 3.3.9
[  +38 ms] executing: [/home/vltp001/flutter_3.3.9/flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[        ] origin/stable
[        ] executing: [/home/vltp001/flutter_3.3.9/flutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +36 ms] executing: [/home/vltp001/flutter_3.3.9/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +37 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +45 ms] executing: /home/vltp001/Android/Sdk/platform-tools/adb devices -l
[  +41 ms] List of devices attached
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms] No supported devices connected.
[  +35 ms] The following devices were found, but are not supported by this project:
           Linux (desktop) • linux  • linux-x64      • Linux Mint 20 5.4.0-56-generic
           Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.52
           If you would like your app to run on linux or web, consider running `flutter create .` to generate projects for these platforms.
           
[  +14 ms] "flutter run" took 204ms.
[  +19 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:491:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1330:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +258 ms] ensureAnalyticsSent: 253ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
   
```

</p>
</details>

**Comment by exaby73** [comment] 2022-12-16 09:06
Can you post the crash logs?

**Comment by Shubham-Narkhede** [comment] 2022-12-16 11:34
there is no crash log available in the console as well as on the sentry dashboard 
![image](https://user-images.githubusercontent.com/55597383/208089509-7af39821-c50a-43fe-b0d2-f03ebd65b4ad.png)

**Comment by exaby73** [comment] 2022-12-16 13:23
This error looks like a logical error. You are probably using the null check `!` operator on a null value somewhere in `setState`

**Comment by Shubham-Narkhede** [comment] 2022-12-16 13:24
let me share u code snippet

**Comment by Shubham-Narkhede** [comment] 2022-12-16 13:26
![image](https://user-images.githubusercontent.com/55597383/208108304-d79612fb-8636-454f-b848-4e76a3774af3.png)

here On line number 225 I'm getting error

**Comment by Shubham-Narkhede** [comment] 2022-12-16 13:27
![image](https://user-images.githubusercontent.com/55597383/208108503-b6bce8d4-fea3-49f5-8601-761c6a7f5cff.png)

here on line number 206 getting error

**Comment by exaby73** [comment] 2022-12-16 13:46
In https://github.com/flutter/flutter/issues/117138#issuecomment-1354764254, `selectedVehicle` might be null. Now I cannot be sure where the exact issue is, maybe posting your queries on StackOverflow would yield better results, but all in all, I do not think this is an issue with Flutter itself. You may try asking for help on resources found on https://flutter.dev/community. But since this is not an issue with Flutter, I am closing this issue. Thank you

**Closed by exaby73** 2022-12-16 13:46 UTC
Labels: in triage
