### ISSUE TITLE
cloud_firestore support for get(source)

### ISSUE THREAD

**Issue by MichalMisiaszek** [flutter/flutter#31334] opened 2019-04-19 23:30 UTC
Hi,
I have a query looking for names in large database.
It works quite slow and I suspect due to loading table to the device.
The firestore API defines get with source which allows to skip cache.
Can we have it as well in plugin ?
Thanks
Michal

**Comment by Stone2517** [comment] 2019-04-24 20:00
Hey @MichalMisiaszek Check this but it only supports for only android not ios.

**Comment by Mmisiek** [comment] 2019-04-24 20:09
Thanks but I need both :(

**Comment by larssn** [comment] 2019-05-16 10:42
Duplicate of https://github.com/flutter/flutter/issues/19078

**Comment by Stone2517** [comment] 2019-05-28 05:25
@Mmisiek Check this If you want to do it manually on ios and android 
https://github.com/flutter/plugins/pull/1538#issuecomment-496367142

**Comment by BondarenkoStas** [comment] 2019-10-12 15:14
I'm going to close the issue as a duplicate, please follow #19078 and upvote it.

**Closed by BondarenkoStas** 2019-10-12 15:14 UTC
