### ISSUE TITLE
[InteractiveViewer] Issue with scroll boundaries

### ISSUE THREAD

**Issue by JuanGriggio** [flutter/flutter#111186] opened 2022-09-08 13:49 UTC
Hello, 

I'm having an issue with an InteractiveViewer in which the scroll limits are not working as expected: user can scroll past the limit of the content, and the content inside the InteractiveViewer can get out of sight. I believe this is an issue related to the boundaryMargin property, which is adding that extra scrollable margin after the end of the rows/cols. The thing is that if I put no boundaryMargin at all, as soon as I start doing pinch to zoom, zooming gets stuck and I can't resize the content anymore.

Code and video:

```
class TableGrid extends StatefulWidget {
  final ReferenceEntity roomRef;
  const TableGrid({
    required this.roomRef,
    Key? key,
  }) : super(key: key);

  @override
  State<TableGrid> createState() => _TableGridState();
}

class _TableGridState extends State<TableGrid> with TickerProviderStateMixin {
  late TransformationController transformationController;
  late AnimationController animationController;
  late Animation<Matrix4> animation;

  @override
  void initState() {
    super.initState();
    transformationController = TransformationController();
    animationController = AnimationController(
      duration: const Duration(milliseconds: 200),
      vsync: this,
    );
  }

  @override
  void dispose() {
    super.dispose();
    transformationController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final gridData = context.watch(GetRef.view.tables.tableListComputed.roomGrid(widget.roomRef));

    return StateListener(
      watchable: GetRef.view.tables.tableListStateRef.select((state) => state.triggerReset),
      onStateChanged: _handleReset,
      child: LayoutBuilder(builder: (context, constraints) {
        final maxSize = min(
          constraints.maxHeight * 0.25,
          constraints.maxWidth * 0.25,
        );
        final widgetSize = Size(constraints.maxWidth, constraints.maxHeight);
        final tgiSize = min(
          maxSize,
          min(widgetSize.width / gridData.item1.columns, widgetSize.height / gridData.item1.rows),
        );
        final maxScale = maxSize / tgiSize;
        return InteractiveViewer(
          transformationController: transformationController,
          maxScale: maxScale < 1 ? 1 : maxScale,
          minScale: 1,
          boundaryMargin: EdgeInsets.only(right: widgetSize.width, bottom: widgetSize.height),
          constrained: false,
          child: GestureDetector(
            behavior: HitTestBehavior.translucent,
            onTap: () => context.use(GetRef.view.tables.tableListLogic).setSelectedTable(null),
            child: Column(
              children: List.generate(
                gridData.item1.rows,
                (row) => Row(
                  children: List.generate(
                    gridData.item1.columns,
                    (column) => SizedBox(
                      width: tgiSize,
                      height: tgiSize,
                      child: TableGridItem(table: gridData.item2['$row, $column']),
                    ),
                  ),
                ),
              ),
            ),
          ),
        );
      }),
    );
  }
  }
}
```

https://user-images.githubusercontent.com/56193426/189138900-421b1bbf-066b-462c-84d6-d3fb405eaaa5.mp4

**Comment by exaby73** [comment] 2022-09-08 23:13
Hello @JuanGriggio . Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
- The output of `flutter doctor -v`

**Comment by JuanGriggio** [comment] 2022-09-09 16:08
Hello @exaby73, here is a working code example:

```
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: TableGrid(),
      ),
    );
  }
}

class TableGrid extends StatefulWidget {
  const TableGrid({
    Key? key,
  }) : super(key: key);

  @override
  State<TableGrid> createState() => _TableGridState();
}

class _TableGridState extends State<TableGrid> with TickerProviderStateMixin {
  late TransformationController transformationController;

  @override
  void initState() {
    super.initState();
    transformationController = TransformationController();
  }

  @override
  void dispose() {
    super.dispose();
    transformationController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) {
        const rows = 20;
        const cols = 2;
        final maxSize = min(
          constraints.maxHeight * 0.25,
          constraints.maxWidth * 0.25,
        );
        final widgetSize = Size(constraints.maxWidth, constraints.maxHeight);
        final tgiSize = min(
          maxSize,
          min(widgetSize.width / cols, widgetSize.height / rows),
        );
        final maxScale = maxSize / tgiSize;
        return InteractiveViewer(
          transformationController: transformationController,
          maxScale: maxScale < 1 ? 1 : maxScale,
          minScale: 1,
          // boundaryMargin: EdgeInsets.only(right: widgetSize.width, bottom: widgetSize.height),
          constrained: false,
          child: Column(
            children: List.generate(
              rows,
              (row) => Row(
                children: List.generate(
                  cols,
                  (column) => SizedBox(
                    width: tgiSize,
                    height: tgiSize,
                    child: Container(
                      decoration: BoxDecoration(
                        color: Colors.red,
                        border: Border.all(color: Colors.black),
                      ),
                      width: double.infinity,
                      height: double.infinity,
                    ),
                  ),
                ),
              ),
            ),
          ),
        );
      },
    );
  }
}
```

And the output of `flutter doctor -v`:

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.4 21F2081 darwin-arm, locale en-AR)
    • Flutter version 3.3.0 on channel stable at /Users/juan/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (11 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/juan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F2081 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by exaby73** [comment] 2022-09-09 16:26
@JuanGriggio Your code sample is either not working for me or it's not reproducing the issue. 

https://user-images.githubusercontent.com/50555895/189397152-81a24bbd-5c12-4dee-95a5-5dae257164db.mp4

**Comment by JuanGriggio** [comment] 2022-09-09 17:10
Sorry, i left the boundaryMargin property commented in the example. If it is commented (not set), when you zoom in, it locks in the maxScale and does not allow to go back to minScale. If you uncomment the boundaryMargin property, it allows you to scroll and get the content out of view.

**Comment by exaby73** [comment] 2022-09-12 09:15
The way you have implemented, it's working as expected. Try changing the `boundaryMargin` to the following:

```dart
boundaryMargin: EdgeInsets.only(
  right: widgetSize.width - 10,
  bottom: widgetSize.height - 100,
),
```

Below is the screenshot when trying to scroll past the right and bottom edge:

<img width="300" src="https://user-images.githubusercontent.com/50555895/189617010-a3fa9b94-a1f5-4c33-87f1-54d5fda8e63a.png">

This is working as expected.

**Comment by exaby73** [comment] 2022-09-12 21:06
In my code sample (https://github.com/flutter/flutter/issues/111186#issuecomment-1243446377), you can see that all I did was subtract from the margin. I am not sure what you are trying to implement here but playing around with those values might give you the result you want.

Since this is working as expected, I am closing this issue. If you need more assistance, you can try sites like StackoverFlow or find help on https://flutter.dev/community. If you disagree with my decision, please comment and I can reopen it. Thank you.

**Closed by exaby73** 2022-09-12 21:06 UTC
Labels: in triage
