### ISSUE TITLE
System theme not get correctly in some cases

### ISSUE THREAD

**Issue by Nandhini-Ravichandran** [flutter/flutter#63769] opened 2020-08-14 12:27 UTC
Dark mode of the mobile device does not get correctly get in some cases. 

Scenario:  I was setting my mobile theme as dark mode and running my flutter application with it, but the system theme not update in the below scenario

## Steps to Reproduce
1. Set the mobile default theme as dark
2. Run the below code snippet

```
import 'package:flutter/material.dart';
 
class Sample extends StatefulWidget {
  Sample();
  ThemeData systemTheme;
  @override
  _SampleState createState() => _SampleState();
}
class _SampleState extends State<Sample> {
  @override
  void initState() {
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
     widget.systemTheme = Theme.of(context);
    return MaterialApp(
        theme: ThemeData.light(),
        darkTheme: ThemeData.dark(),
        themeMode: ThemeMode.system,
        home: Builder(builder: (BuildContext context) {     
           return HomePage(widget.systemTheme);
    }));
  }
}
class HomePage extends StatefulWidget {
  HomePage(this.sysytemTheme);
  final ThemeData sysytemTheme;
  @override
  _HomePageState createState() => _HomePageState();
}
class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Container(
        color: widget.sysytemTheme.brightness == Brightness.dark
            ? Colors.red
            : Colors.green,
        child: Text(widget.sysytemTheme.brightness.toString()));
  }
}
```

**Expected results:**  
![image](https://user-images.githubusercontent.com/56873926/90248455-5aca9100-de56-11ea-8c3e-adda5c5bb3aa.png)

**Actual results:** 
![image](https://user-images.githubusercontent.com/56873926/90248583-9c5b3c00-de56-11ea-8ff6-97f5c5c6678f.png)

system theme does not update correctly when the theme is taken from the context of the build (root widget of Sample browser).

```

@override
Widget build(BuildContext context) {
    systemTheme = Theme.of(context);
     return MaterialApp(...);
}

```

*  Updates correctly when the system theme is taken from the context of the home widget of MaterialApp

```
@override
Widget build(BuildContext context) {
     return MaterialApp(
     home: Builder(builder: (BuildContext context) {
          systemTheme = Theme.of(context);
          return ...
    }));
}

```
 it works correctly in the below sample: 

```

import 'package:flutter/material.dart';
 
class Sample extends StatefulWidget {
  Sample();
  ThemeData systemTheme;
  @override
  _SampleState createState() => _SampleState();
}
class _SampleState extends State<Sample> {
  @override
  void initState() {
    super.initState();
  }
  @override  Widget build(BuildContext context) {
    return MaterialApp(
        theme: ThemeData.light(),
        darkTheme: ThemeData.dark(),
        themeMode: ThemeMode.system,
        home: Builder(builder: (BuildContext context) { 
           widget.systemTheme = Theme.of(context);
           return HomePage(widget.systemTheme);
    }));
  }
}
class HomePage extends StatefulWidget {
  HomePage(this.sysytemTheme);
  final ThemeData sysytemTheme;
  @override
  _HomePageState createState() => _HomePageState();
}
class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Container(
        color: widget.sysytemTheme.brightness == Brightness.dark
            ? Colors.red
            : Colors.green,
        child: Text(widget.sysytemTheme.brightness.toString()));
  }
}

```

**Comment by TahaTesser** [comment] 2020-08-14 14:31
Hi @Nandhini-Ravichandran 
I believe this is by design, theme needs to be under Material App for context. Is there a reason you're putting it outside?  Also can you point to api docs where it happens we can do this? 

I don't expect `Theme.of(context);` to work outside of MaterialApp, am i mistaken?
```
    systemTheme = Theme.of(context);
     return MaterialApp(...);
```

Can you please provide your `flutter doctor -v` your `flutter run --verbose` 
Thank you

**Comment by Nandhini-Ravichandran** [comment] 2020-08-17 06:27
**flutter doctor -v**

[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version 10.0.17763.1039], locale en-IN)
    • Flutter version 1.20.0 at D:\flutter\flutter
    • Framework revision 916c3ac648 (2 weeks ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Nandhini\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.42.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • Redmi 3S (mobile) • 48eaa88a7d83 • android-arm64  • Android 6.0.1 (API 23)
    • Web Server (web)  • web-server   • web-javascript • Flutter Tools
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 84.0.4147.125

• No issues found!

**Comment by TahaTesser** [comment] 2020-08-17 08:32
HI @Nandhini-Ravichandran 
Please provide more details from https://github.com/flutter/flutter/issues/63769#issuecomment-674103182

**Comment by Nandhini-Ravichandran** [comment] 2020-08-17 08:38
The same Theme.of(context)  gives different result, when we using inside and outside the MaterialApp. But it has to give same result for both the samples(above mentioned). Is it right?

**Comment by TahaTesser** [comment] 2020-08-17 09:37
Hi @Nandhini-Ravichandran 
Thanks for providing `flutter doctor -v`
It detect dark mode using code sample on latest `beta`

![flutter_01](https://user-images.githubusercontent.com/48603081/90381595-390e1b80-e09b-11ea-9c8c-67591c88849d.png)





<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Sample(),
    );
  }
}

class Sample extends StatefulWidget {
  Sample();
  ThemeData systemTheme;
  @override
  _SampleState createState() => _SampleState();
}

class _SampleState extends State<Sample> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    widget.systemTheme = Theme.of(context);
    return MaterialApp(
        theme: ThemeData.light(),
        darkTheme: ThemeData.dark(),
        themeMode: ThemeMode.system,
        home: Builder(builder: (BuildContext context) {
          return HomePage(widget.systemTheme);
        }));
  }
}

class HomePage extends StatefulWidget {
  HomePage(this.sysytemTheme);
  final ThemeData sysytemTheme;
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Container(
        color: widget.sysytemTheme.brightness == Brightness.dark
            ? Colors.red
            : Colors.green,
        child: Text(widget.sysytemTheme.brightness.toString()));
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_beta
    • Framework revision bbfbf1770c (4 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```

</details>

**Comment by Nandhini-Ravichandran** [comment] 2020-08-17 10:38
In your code if we commenting the line `theme: ThemeData.dark(),` from below  and setting mobile in dark mode it returns light theme output only




```

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      // theme: ThemeData.dark(),
      home: Sample(),
    );
  }
}
```

**Comment by Nandhini-Ravichandran** [comment] 2020-08-17 10:58
if we not commenting the below line, it returns dark theme by default (when my mobile theme not setting in dark mode)
 `theme: ThemeData.dark(),`

**Comment by TahaTesser** [comment] 2020-08-18 07:03
Hi @Nandhini-Ravichandran 
i accidentally another MaterialApp in my code sample but this isn't an issue, you're calling ` systemTheme = Theme.of(context);` outside materialApp. Whole point of calling Theme.of is to get context from materialApp which you cannot achieve by Theme.of before MaterialApp was called 

Your working code sample is the intended way to get this,  you call theme.of before `MaterialApp` there is no material theming initialisation done, you won't get any system theme 

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it and provide API docs 
Thank you

**Closed by TahaTesser** 2020-08-18 07:03 UTC
Labels: in triage
