### ISSUE TITLE
HarmonyOS support

### ISSUE THREAD

**Issue by WangweitaoTT** [flutter/flutter#134200] opened 2023-09-07 07:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

There are currently reliable sources saying that HarmonyOS 5.0 will no longer support Android applications, and apk files will not be recognized in the HarmonyOS. Is the flutter official ready to provide relevant support for the Hongmeng system so that the flutter application can run on the HarmonyOS?

### Proposal

As flutter development engineers, we eagerly hope that flutter can provide relevant support for HarmonyOS, otherwise we may need to develop Hongmeng native apps, which is a very painful thing

**Comment by LX19930301** [comment] 2023-09-07 08:02
I'd also like to know the details

**Comment by kjxbyz** [comment] 2023-09-07 08:06
It seems that OpenHarmony does not support apk, not HarmonyOS

**Comment by stuartmorgan** [comment] 2023-09-07 09:56
Closing as a duplicate of https://github.com/flutter/flutter/issues/38437

**Closed by stuartmorgan** 2023-09-07 09:56 UTC

**Comment by sawwas** [comment] 2023-09-12 03:39
> ### Is there an existing issue for this?
> * [x]  I have searched the [existing issues](https://github.com/flutter/flutter/issues)
> * [x]  I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)
> 
> ### Use case
> There are currently reliable sources saying that HarmonyOS 5.0 will no longer support Android applications, and apk files will not be recognized in the HarmonyOS. Is the flutter official ready to provide relevant support for the Hongmeng system so that the flutter application can run on the HarmonyOS?
> 
> ### Proposal
> As flutter development engineers, we eagerly hope that flutter can provide relevant support for HarmonyOS, otherwise we may need to develop Hongmeng native apps, which is a very painful thing

I fell read the Harmony official documentation, writing and flutter is highly similar, you can also not be compatible.

**Comment by OliverVin** [comment] 2023-09-14 05:22
The base of the Harmony is getting larger and larger, and domestic developers cannot bypass it. If Flutter does not support it anymore, it will become one out of two. I hope the official can provide attention and support.

**Comment by stuartmorgan** [comment] 2023-09-14 14:21
> If Flutter does not support it anymore

Flutter has never supported HarmonyOS; see the linked issue and https://docs.flutter.dev/reference/supported-platforms

If HarmonyOS used to support Android applications and then stops doing so, that's a change in support by HarmonyOS, not a change in Flutter's support matrix.

> I hope the official can provide attention and support.

Please see https://github.com/flutter/flutter/issues/38437#issuecomment-528469296. If there are developers interested in using Flutter for HarmonyOS development, they are certainly welcome to build a HarmonyOS embedding for Flutter (using the same API that the majority of the Flutter-team-supported embeddings use).

**Comment by OliverVin** [comment] 2023-09-20 02:58
Lao Tie, blessed! Here comes the HarmonyOS version of Flutter.   https://gitee.com/openharmony-sig/flutter_flutter
