### ISSUE TITLE
in_app_purchase

### ISSUE THREAD

**Issue by Bharavi26** [flutter/flutter#78852] opened 2021-03-23 09:46 UTC
Error Domain=SKErrorDomain Code=0 "UNKNOWN_ERROR"
 UserInfo={NSLocalizedDescription=UNKNOWN_ERROR, NSUnderlyingError=0x600002d61d10
 {Error Domain=ASDErrorDomain Code=507 "Error decoding object" UserInfo={NSLocalizedDescription=Error decoding object, NSLocalizedFailureReason=Attempted to decode store response}}}

------------------------------

i am testing in ios, also added test productid in apple account by creating item there,
but getting error like above while try to get product details..

ProductDetailsResponse productDetailResponse = await connection
                .queryProductDetails([appleitemid].toSet()); 

-------------------------
is there any solution of above issue ?

**Comment by TahaTesser** [comment] 2021-03-23 10:00
Hi @Bharavi26 
Are you trying to test it on the simulator?  https://github.com/flutter/flutter/issues/74181
Looks like a duplicate of https://github.com/flutter/flutter/issues/78256
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-23 10:00 UTC
Labels: in triage

**Comment by Bharavi26** [comment] 2021-03-23 11:05
@TahaTesser sir, thank you for response

i tested on real device too, in real device i am not getting product info..
it returns empty details

--------------------------------
ProductDetailsResponse productDetailResponse = await connection
.queryProductDetails([appleitemid].toSet());
----------------------------------------
print("====data=len=${productDetailResponse.productDetails.length}==${productDetailResponse.productDetails.toString()}");
---------------------
flutter: ====data=len=0==[]

**Comment by TahaTesser** [comment] 2021-03-23 12:56
Hi @Bharavi26 
Please follow up on the duplicate with the issue, with the details, code sample, logs, instead of a screenshot
Thank you
