### ISSUE TITLE
canvas draw an image and export it without image 

### ISSUE THREAD

**Issue by lyqiai** [flutter/flutter#24814] opened 2018-11-28 05:07 UTC
code:
```dart
var pictureRecorder = ui.PictureRecorder();
    var canvas = Canvas(pictureRecorder, Rect.fromLTWH(0.0, 0.0, image.width.toDouble(), image.height.toDouble()));
    var paint = Paint();
    paint.isAntiAlias = true;
    var src = Rect.fromLTWH(
        0.0, 0.0, image.width.toDouble(), image.height.toDouble());
    var dst =
    Rect.fromLTWH(0.0, 0.0, image.width.toDouble(), image.height.toDouble());
    canvas.drawImageRect(image, src, dst, paint);
    canvas.drawRect(Rect.fromLTWH(0.0, 0.0, 100.0, 100.0), paint);
    var pic = pictureRecorder.endRecording();
    ui.Image img = pic.toImage(image.width, image.height);`
.......to Uint8List
```

use image.memory widget load it just can see a rect

**Comment by lyqiai** [comment] 2018-11-28 07:12
[√] Flutter (Channel beta, v0.11.9, on Microsoft Windows [Version 10.0.17134.407], locale zh-CN)
    • Flutter version 0.11.9 at F:\flutter\flutter
    • Framework revision d48e6e433c (7 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\16329\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: F:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    X Android license status unknown.

[√] Android Studio (version 3.2)
    • Android Studio at F:\Android Studio
    • Flutter plugin version 30.0.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.


`import 'dart:convert';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'dart:io';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _imageUrl = 'https://cdn.jsdelivr.net/gh/flutterchina/website@1.0/images/flutter-mark-square-100.png';
  var _img;

  @override
  Widget build(BuildContext context) {
    var widget = _img != null ? Image.memory(_img) : Text('place click button');
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: widget
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          var uri = Uri.parse(_imageUrl);
          var httpClient = HttpClient();
          var request = await httpClient.getUrl(uri);
          var response = await request.close();
          response.listen((data) async {
            ui.Image image = await decodeImageFromList(data);
            var pictureRecorder = ui.PictureRecorder();
            var canvas = Canvas(pictureRecorder);
            var paint = Paint();
            paint.isAntiAlias = true;
            var src = Rect.fromLTWH(
                0.0, 0.0, image.width.toDouble(), image.height.toDouble());
            var dst =
            Rect.fromLTWH(0.0, 0.0, image.width.toDouble(), image.height.toDouble());
            canvas.drawRect(Rect.fromLTWH(0.0, 0.0, 100.0, 100.0), paint);
            canvas.drawImageRect(image, src, dst, paint);
            var pic = pictureRecorder.endRecording();
            ui.Image img = pic.toImage(image.width, image.height);
            var byteData = await img.toByteData(format: ui.ImageByteFormat.png);
            var buffer = byteData.buffer.asUint8List();
            setState((){
              _img = buffer;
            });
          });
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by zoechi** [comment] 2018-11-28 10:08
Could be a dup of #23621

If I use
```
canvas.drawLine(Offset.zero, Offset(100, 100), paint);
```
instead of `drawImage...()` then the line is shown.

There is also an issue in your code how you fetch the image.
You only take the first chunk but the image data can arrive in multiple chunks (and did for me).

```
          var response = await request.close();

          final dataBuffer = <int>[];
          await response.forEach(dataBuffer.addAll);
          assert(dataBuffer.length == response.contentLength);
```

**Comment by dkashkin** [comment] 2018-12-07 20:37
I just bumped into the same issue with my app. The problem does not reproduce on iOS devices or simulator - only on Android. Images obtained from ui.instantiateImageCodec refuse to draw on Canvas. One interesting detail - if I load the same source image in any widget and use RenderRepaintBoundary.toImage in order to get the binary data then I am able to draw the image on Android Canvas. I tested this with several JPG and PNG images that had different encoding and none of them worked, so this cannot be blamed on some weird codec.

**Comment by zoechi** [comment] 2019-01-16 10:19
Same as https://github.com/flutter/flutter/issues/24814#issuecomment-442378374 but with an additional `await` before ` pic.toImage(`

```dart
import 'dart:convert';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'dart:io';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  var _imageUrl =
      'https://cdn.jsdelivr.net/gh/flutterchina/website@1.0/images/flutter-mark-square-100.png';
  var _img;

  @override
  Widget build(BuildContext context) {
    var widget = _img != null ? Image.memory(_img) : Text('place click button');
    return Scaffold(
      appBar: AppBar(),
      body: Center(child: widget),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          var uri = Uri.parse(_imageUrl);
          var httpClient = HttpClient();
          var request = await httpClient.getUrl(uri);
          var response = await request.close();
          response.listen((data) async {
            ui.Image image = await decodeImageFromList(data);
            var pictureRecorder = ui.PictureRecorder();
            var canvas = Canvas(pictureRecorder);
            var paint = Paint();
            paint.isAntiAlias = true;
            var src = Rect.fromLTWH(
                0.0, 0.0, image.width.toDouble(), image.height.toDouble());
            var dst = Rect.fromLTWH(
                0.0, 0.0, image.width.toDouble(), image.height.toDouble());
            canvas.drawRect(Rect.fromLTWH(0.0, 0.0, 100.0, 100.0), paint);
            canvas.drawImageRect(image, src, dst, paint);
            var pic = pictureRecorder.endRecording();
            ui.Image img = await pic.toImage(image.width, image.height);
            var byteData = await img.toByteData(format: ui.ImageByteFormat.png);
            var buffer = byteData.buffer.asUint8List();
            setState(() {
              _img = buffer;
            });
          });
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

I get
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 3,369ms.
E/flutter ( 7682): [ERROR:flutter/lib/ui/painting/codec.cc(97)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
E/flutter ( 7682): [ERROR:flutter/lib/ui/painting/codec.cc(97)] Failed decoding image. Data is either invalid, or it is encoded using an unsupported format.
E/flutter ( 7682): [ERROR:flutter/shell/common/shell.cc(178)] Dart Error: Unhandled exception:
E/flutter ( 7682): Exception: operation failed
E/flutter ( 7682): #0      decodeImageFromList (package:flutter/src/painting/image_decoder.dart:24:26)
E/flutter ( 7682): <asynchronous suspension>
E/flutter ( 7682): #1      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:flutter_0_generic/main.dart:49:36)
E/flutter ( 7682): <asynchronous suspension>
E/flutter ( 7682): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7682): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7682): #4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7682): #5      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
E/flutter ( 7682): #6      _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
E/flutter ( 7682): #7      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
E/flutter ( 7682): #8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7682): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7682): #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7682): #11     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
E/flutter ( 7682): #12     _StreamController._add (dart:async/stream_controller.dart:640:7)
E/flutter ( 7682): #13     _StreamController.add (dart:async/stream_controller.dart:586:5)
E/flutter ( 7682): #14     _HttpParser._doParse (dart:_http/http_parser.dart:767:27)
E/flutter ( 7682): #15     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
E/flutter ( 7682): #16     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
E/flutter ( 7682): #17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7682): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7682): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7682): #20     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
E/flutter ( 7682): #21     _StreamController._add (dart:async/stream_controller.dart:640:7)
E/flutter ( 7682): #22     _StreamController.add (dart:async/stream_controller.dart:586:5)
E/flutter ( 7682): #23     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1722:41)
E/flutter ( 7682): #24     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7682): #25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7682): #26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7682): #27     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
E/flutter ( 7682): #28     _StreamController._add (dart:async/stream_controller.dart:640:7)
E/flutter ( 7682): #29     _StreamController.add (dart:async/stream_controller.dart:586:5)
E/flutter ( 7682): #30     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:996:19)
E/flutter ( 7682): #31     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter ( 7682): #32     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter ( 7682): #33     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter ( 7682): #34     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter ( 7682): [ERROR:flutter/shell/common/shell.cc(178)] Dart Error: Unhandled exception:
E/flutter ( 7682): Exception: operation failed
E/flutter ( 7682): #0      decodeImageFromList (package:flutter/src/painting/image_decoder.dart:24:26)
E/flutter ( 7682): <asynchronous suspension>
E/flutter ( 7682): #1      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:flutter_0_generic/main.dart:49:36)
E/flutter ( 7682): <asynchronous suspension>
E/flutter ( 7682): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7682): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7682): #4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7682): #5      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
E/flutter ( 7682): #6      _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
E/flutter ( 7682): #7      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
E/flutter ( 7682): #8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7682): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7682): #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7682): #11     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
E/flutter ( 7682): #12     _StreamController._add (dart:async/stream_controller.dart:640:7)
E/flutter ( 7682): #13     _StreamController.add (dart:async/stream_controller.dart:586:5)
E/flutter ( 7682): #14     _HttpParser._doParse (dart:_http/http_parser.dart:767:27)
E/flutter ( 7682): #15     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
E/flutter ( 7682): #16     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
E/flutter ( 7682): #17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7682): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7682): #19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7682): #20     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
E/flutter ( 7682): #21     _StreamController._add (dart:async/stream_controller.dart:640:7)
E/flutter ( 7682): #22     _StreamController.add (dart:async/stream_controller.dart:586:5)
E/flutter ( 7682): #23     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1722:41)
E/flutter ( 7682): #24     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter ( 7682): #25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7682): #26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7682): #27     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
E/flutter ( 7682): #28     _StreamController._add (dart:async/stream_controller.dart:640:7)
E/flutter ( 7682): #29     _StreamController.add (dart:async/stream_controller.dart:586:5)
E/flutter ( 7682): #30     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:996:19)
E/flutter ( 7682): #31     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter ( 7682): #32     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter ( 7682): #33     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter ( 7682): #34     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
[✓] Flutter (Channel master, v1.1.10-pre.76, on Mac OS X 10.14.1 18B75, locale en-AT)
    • Flutter version 1.1.10-pre.76 at /Users/zoechi/flutter/flutter
    • Framework revision 684d050791 (4 hours ago), 2019-01-16 01:01:51 -0500
    • Engine revision fdfb0e72f0
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 d9944433af)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.1.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.5124

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2019-01-16 10:37
Duplicate of #23621

**Closed by zoechi** 2019-01-16 10:37 UTC
Labels: engine
