### ISSUE TITLE
Could not resolve all files for configuration ':shared_preferences:classpath'.

### ISSUE THREAD

**Issue by patrioticcow** [flutter/flutter#14010] opened 2018-01-10 06:50 UTC
I'm fallowing this steps to upgrade Gradle https://github.com/flutter/flutter/wiki/Updating-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1

I've been using Android Studio to double check that Gradle upgrade had no issues. Everything seems fine there. 

My dependence are
```
dependencies:
  flutter:
    sdk: flutter
  http: '>=0.11.3+12'
  shared_preferences: "^0.3.0"
  firebase_auth : "^0.4.0"
```

The error I'm getting when I run flutter:
```
Launching lib\main.dart on BLN L24 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: E:\Work\scuba_flutter\android\gradlew.bat app:properties:
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.
Configuration 'profileCompile' in project ':app' is deprecated. Use 'profileImplementation' instead.
Configuration 'releaseCompile' in project ':app' is deprecated. Use 'releaseImplementation' instead.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Finished with error: Please review your Gradle project setup in the android/ folder.
Configuration 'debugProvided' in project ':firebase_auth' is deprecated. Use 'debugCompileOnly' instead.
Configuration 'releaseProvided' in project ':firebase_auth' is deprecated. Use 'releaseCompileOnly' instead.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':shared_preferences'.
> Could not resolve all files for configuration ':shared_preferences:classpath'.
   > Could not find com.android.tools.build:gradle:3.0.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
     Required by:
         project :shared_preferences

```

**Comment by patrioticcow** [comment] 2018-01-10 06:53
Looks like I had to manually remove `shared_preferences-0.2.5` from `C:\Users\my_user\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org`

**Comment by ethanyuwang** [comment] 2018-02-12 22:39
@patrioticcow  do you know whats the equivalent in a mac?

**Comment by lucamtudor** [comment] 2018-02-16 17:16
@ethanyuwang it's "~/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.3.2"

**Comment by zoechi** [comment] 2018-02-19 18:42
You can also try `pub cache repair` if you have a normal Dart SDK installed (re-downloads all packages)
I don't think this is available through the `flutter` command yet.

I didn't have a need to use it for a long time though (in early pub days this was more common)
From time to time it might make sense to purge the `~/.pub-cache/hosted/pub.dartlang.org/` directory to get rid of outdated packages (you then need to run `flutter packages get` in every project again)

**Comment by Hixie** [comment] 2018-05-29 23:55
It's not clear how to reproduce this or what we can do to make this better.

I'm going to close this bug since it's not really actionable for us. Please don't hesitate to open a new bug if you can reliably reproduce this. We'd be interested in being able to detect this case and have a more useful error message, for example.

**Closed by Hixie** 2018-05-29 23:55 UTC

**Comment by rahmanrezaee** [comment] 2020-03-28 14:19
Command to `flutter pub cache repair`
