### ISSUE TITLE
Flutter app restarts after it is minimised in release mode [Only for iPad, Working for other Devices]

### ISSUE THREAD

**Issue by pinkal-simform** [flutter/flutter#149804] opened 2024-06-06 11:17 UTC
### Steps to reproduce

Requirement: Test these steps only on an iPad
 
Step 1: Open the app and go to any screen
Step 2: Minimize the app with any of the screens
Step 3: Open the app from the minimized state by clicking on the app icon or from the recent app.

### Expected results

App is restarted and started from the beginning splash screen.

### Actual results

It should open from the same state when we minimize the app.

### Code sample

Not needed

### Flutter Wonderous app:

**iPhone [Working]:** [Video Link](https://drive.google.com/file/d/1ZDuARM9i1vvhuxz0BB8eDW4I0TH06VRf/view?usp=sharing)

**iPad [Not Working]:** [Video Link](https://drive.google.com/file/d/1LuRBzh5lzaOqmLUvA6Y3QhfJ2QqCEHLK/view?usp=sharing)

### Logs

Not needed

### Flutter Doctor output

Not needed

**Comment by moffatman** [comment] 2024-06-06 13:51
When an app gets put in the background in iPadOS, it gets rapidly resized and screenshotted at different sizes, so that if placed in multitasking view, it looks correct right away. It's possible the dynamic layout/Navigation for different screen sizes is being reset.

**Comment by Livinglist** [comment] 2024-06-06 21:19
Same issue here

**Comment by pinkal-simform** [comment] 2024-06-07 05:51
@moffatman Might be possible when we are rotating the device but what about when we are in stable condition like portrait mode and resume from the background? because I cross-checked with other iOS natively built apps in iOS which are resuming from where we left off while we moved to the background. 

You can also play with any iOS native app on iPad which works similarly to the iPhone.

**Comment by darshankawar** [comment] 2024-06-07 07:09
Thanks for the report @pinkal-simform 
I tried couple of sample apps (default counter and [navigation](https://docs.flutter.dev/cookbook/navigation/navigation-basics#interactive-example)) using latest master version and running on ipad simulator (since I don't have physical ipad) and I observed that the state is preserved upon opening the app as shown below:


https://github.com/flutter/flutter/assets/67046386/d012be9f-3f73-41c8-9ede-b35fc2efabf3

Can you check using same sample apps on the device to see if you still get same behavior or not ? Or is it something specific to wonderous app you are using ?

**Comment by pinkal-simform** [comment] 2024-06-07 08:07
@darshankawar Please check in release mode, sometime it is working fine in debug mode.

**Comment by pinkal-simform** [comment] 2024-06-07 08:52
@darshankawar I tried Flutter new project, here is the result in a real iPad.

iPad video: [link](https://drive.google.com/file/d/11xtxzjWY_7ZVV5UNjBwycIuFL9rJ-2A0/view?usp=sharing)

**Comment by moffatman** [comment] 2024-06-07 13:29
So it's not the problem I think above; because the new project is really simple and doesn't have display-size-based-navigation

**Comment by darshankawar** [comment] 2024-06-10 05:36
Thanks for the update. Currently I don't have physical ipad device to replicate / verify this further, but based on the report and video attached, I'll keep the issue open for team's tracking.

**Comment by pinkal-simform** [comment] 2024-06-12 12:02
iPad 12 Pro with iPad OS 17.5.1

Fast App Termination was on. When I turn off, then app state was maintained. Can you share me, what is the default state when developer settings is off in any iPhone or iPad?

**Flutter doctor:**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.0)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is
      unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
    ! Error: Browsing on the local area network for SF-IPAD-005. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2024-06-12 13:09
By default `Fast App Termination` is not on. It is a setting used by developers when they want to test state restoration. You can find out more about state restoration in https://api.flutter.dev/flutter/services/RestorationManager-class.html. 

Given that this was due `Fast App Termination` being on, I'll be closing this as working as intended. 

Thank you

**Closed by danagbemava-nc** 2024-06-12 13:09 UTC
Labels: e: device-specific, platform-ios, a: release, team-ios
