### ISSUE TITLE
On iOS, plugins have no opportunity to cleanup when FlutterEngines are deallocated

### ISSUE THREAD

**Issue by talisk** [flutter/flutter#44256] opened 2019-11-06 09:14 UTC
``` shell
➜flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F203,
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)
• No issues found!
```

As we all know, the engine will free memory when I call `destroyContext`. But after the calling, some platform messages which were sent from Dart code cannot be received by native code,  `handleMethodCall` won't be called.
So there is a serious problem. Some plugins need to do something after the `dealloc` calling. For example, "video_player" plugin will remove observer of the player's KVO. After calling `destroyContext`, the message "dispose" won't be received. And the KVO's observer won't be removed, the app will crash.
What is the suitable time to call the destroyContext on iOS?

**Comment by iapicca** [comment] 2019-11-06 12:29
Hi @talisk 
I believe this [issue ](https://github.com/flutter/flutter/issues/19754)is connected to your question 
although it's not a duplicate in my opinion,
thank you for your question

**Comment by talisk** [comment] 2019-11-06 13:07
Hi @iapicca 
I have been paying attention to this [issue](https://github.com/flutter/flutter/issues/19754) for a long time.
Actually, I want to figure out how to free memory as much as possible when all of the FlutterViewControllers destroyed in a Flutter-native hybrid app. Because the memory of our app is very huge even if no Flutter used. Leaving FlutterViewController without engine's memory free is so terrible.

**Comment by talisk** [comment] 2019-11-06 13:14
Also, I noticed that FlutterViewController will send 'FlutterViewControllerWillDealloc' notification when it call 'dealloc'. And FlutterEngine will receive the notification and call 'destroyContext' when the '_allowHeadlessExecution' is NO. This may mean some method messages won't be handle in that case.

**Comment by liyuqian** [comment] 2019-11-11 23:11
Thank you @talisk very much for posting the issue! Can you please provide a minimal reproduction app so we can better understand your problem, and see how we can help? I understand that this is an add-to-app (hybrid) scenario so a single `main.dart` reproduction may not be sufficient. Maybe creating a Github repo for a sample app so we can clone and test?

@xster : currently, does add-to-app provide or use any performance test framework? For example, is there anything equivalent to the driver test used by `complex_layout_scroll_perf__memory` device lab test?

Also CC @gaaclarke , @chinmaygarde for their iOS expertise.

**Comment by talisk** [comment] 2019-11-12 06:29
@liyuqian Thank you for paying attention to this issue. Here's a [demo project](https://github.com/talisk/flutter_ios_destroydemo) reproduces the issue on iOS.

## Steps to reproduce

MainViewController is the root ViewController. And we push into FlutterViewController with an engine that allowHeadlessExecution is NO. Then pop back to MainViewController.The app crashed because video_player cannot receive the dispose platform message. 

Flutter called destroyContext when the FlutterViewController instance call dealloc. Some dispose method of video_player won't be called.

**Comment by cbracken** [comment] 2019-11-12 19:09
Can you take a look at @mehmetf's response to https://github.com/flutter/flutter/issues/28134 and see if that resolves your issue?

**Comment by gaaclarke** [comment] 2019-11-18 20:51
I've tried to reproduce this locally and was unable to.  @talisk, your sample code is missing the host of the code.

Popping the FlutterViewController didn't cause a crash for me.  But the video didn't play for me either.  The player just endlessly showed a progress indicator so it might not be 100% representative.

**Comment by talisk** [comment] 2019-12-04 08:47
@cbracken I think it's better to have a message to notify that the engine will be destroyed and dart code can handle the destroy message. The reply by @Hixie in [42643](https://github.com/flutter/flutter/issues/42643) proposed a solution.

In addition, I have explored a possible solution might solve the problem. Call destroyContext with a few seconds delay after the instance of FlutterViewController call dealloc. If you push another FlutterViewController in the few seconds, you can reuse the instance of FlutterEngine. Over the few seconds, you may alloc a new instance of FlutterEngine.

This sounds a bit complicated, but currently works. FlutterEngine's memory can be released after FlutterViewController quit.

**Comment by xster** [comment] 2019-12-18 23:24
Also some additional details from Alibaba: setting `leak_vm` to false doesn't actually fully free the VM from destroying the engine (as expected on Android and iOS) and there isn't a way to unload the last bit of resident 27mb from the VM when needed.

**Comment by talisk** [comment] 2019-12-23 03:52
> Also some additional details from Alibaba: setting `leak_vm` to false doesn't actually fully free the VM from destroying the engine (as expected on Android and iOS) and there isn't a way to unload the last bit of resident 27mb from the VM when needed.

Yep. In fact, there are some repair methods to minimize this part of leaked memory. We are working in progress to reduce the leaks.

**Comment by Hixie** [comment] 2020-01-08 00:16
@cbracken says he will have a better idea of the timeline for fixing this in a week.

**Comment by gaaclarke** [comment] 2020-01-13 21:12
Here are a couple of thoughts:

### 1) The Destroyer is the Cleaner
The documentation for `destroyContext` states: 
> the object will be in an unusable state until it is deallocated.  Accessing properties or sending messages to it will result in undefined behavior or runtime errors.

So, it seems to be behaving as expected.  Can you not have the caller that calls `destroyContext` do the other cleanup like removing the KVO observers?

### 2) Cleanup message

> So there is a serious problem. Some plugins need to do something after the dealloc

If 1 doesn't work couldn't you just send a custom message to your plugins to cleanup and when they have finished, call `destroyContext`?

### 3) Android's onDetachedFromEngine

Have you seen the new Plugin API for Android?  `FlutterPlugin` now has `onDetachedFromEngine`( [source](https://github.com/flutter/engine/blob/5ef2c7968c7215acaffddd008a8ccabeb7cb6706/shell/platform/android/io/flutter/embedding/engine/plugins/FlutterPlugin.java#L87)).  Is this similar to what you are asking for?  There isn't an equivalent for iOS currently.

**Comment by talisk** [comment] 2020-01-15 07:16
Thanks @gaaclarke .

I am afraid these thoughts cannot be adopted. There are two facts.

1. There's only one destroyer in an application. It manages engine, determines engine creation and destruction. But there are a lot of plugins in different iOS `Pods`. The Destroyer and the Cleaner couldn't be the same one.

2. In my case, the KVO observer belongs to `video_player` plugin. But `video_player` is an official plugin maintained by Flutter Team. I don't think I should modify code which isn't belongs to me.

I have seen the new APIs in FlutterPlugin. Could iOS also have the new API in the future and upgrade existing plugins to the new APIs?

**Comment by gaaclarke** [comment] 2020-01-17 16:52
@talisk OK, can you provide a minimal reproduction code.  You already have the demo code written for Flutter but it is missing the part of the code that causes the crash.  Ideally I could launch your project, tap a button and it crashes.  It's just too complicated to communicate without seeing exactly how you are using the API.

**Comment by gaaclarke** [comment] 2020-01-17 17:05
Crash log:
```
#0	0x0000000102a64e06 in flutter::Shell::GetPlatformView() at /Users/aaclarke/dev/engine/src/flutter/shell/common/shell.cc:547
#1	0x0000000102854a3d in ::-[FlutterEngine textureFrameAvailable:](int64_t) at /Users/aaclarke/dev/engine/src/flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:626
#2	0x000000010241ae4a in -[FLTFrameUpdater onDisplayLink:] at /Users/aaclarke/dev/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.5+2/ios/Classes/FLTVideoPlayerPlugin.m:29
#3	0x00007fff2afeb266 in CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) ()
#4	0x00007fff2b0c3e03 in display_timer_callback(__CFMachPort*, void*, long, void*) ()
#5	0x00007fff23b9503d in __CFMachPortPerform ()
#6	0x00007fff23bd4bc9 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ ()
#7	0x00007fff23bd4228 in __CFRunLoopDoSource1 ()
#8	0x00007fff23bced64 in __CFRunLoopRun ()
#9	0x00007fff23bce066 in CFRunLoopRunSpecific ()
#10	0x00007fff384c0bb0 in GSEventRunModal ()
#11	0x00007fff48092d4d in UIApplicationMain ()
#12	0x000000010241a750 in main at /Users/aaclarke/dev/flutter-examples/flutter_ios_destroydemo/ios/Runner/main.m:7
#13	0x00007fff5227ec25 in start ()
```

**Comment by gaaclarke** [comment] 2020-01-17 17:39
@amirh @mklim @xster @cbracken 

So, here is the crux of this problem.  On iOS, when deleting a FlutterViewController, plugins aren't notified so they don't have an opportunity to cleanup.  In this case a plugin has an active display link that is calling into Flutter assuming everything is still alive.

This isn't an issue on Android anymore because of the attach and detach notifications for plugins.

I think we need to supply the same semantics for iOS plugins in order to support the Add-to-app case.

**Comment by gaaclarke** [comment] 2020-01-17 17:47
@talisk As a workaround for now you can subclass FlutterViewController and in its dealloc you can send a "dispose" message on to the video player plugin.

See: https://github.com/flutter/plugins/blob/64c9c5e1a6af37f0bb93b5284d06877a160154f9/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m#L493

**Comment by talisk** [comment] 2020-01-19 02:49
> @talisk As a workaround for now you can subclass FlutterViewController and in its dealloc you can send a "dispose" message on to the video player plugin.
> 
> See: https://github.com/flutter/plugins/blob/64c9c5e1a6af37f0bb93b5284d06877a160154f9/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m#L493

Hi @gaaclarke 

It's easy to subclass ViewController. However, in the FlutterViewController's dealloc method, sending messages to the plugins that need to be disposed, looks strange. I need to read the code of each plugin before I know if the plugin needs to receive messages and what messages need to be received.

If this is just a temporary solution, I think the [delayed engine destruction](https://github.com/flutter/flutter/issues/19754#issuecomment-561540797) might be better. But a more suitable way is to add a lifecycle mechanism to the plugin, just like the Android platform. The plugin handles itself's things after the engine is destroyed.

**Comment by gaaclarke** [comment] 2020-01-22 18:40
> If this is just a temporary solution

It is a temporary solution.  Unfortunately the semantics for plugins in iOS don't provide the authors with the appropriate hooks to do the cleanup you want so you'll have to introspect and it do it for them until we can come up with a solution which will probably mean upgrading plugins.  We went through this already with Android, it's a bit of a headache, it will take a while to get everything working.

**Comment by gaaclarke** [comment] 2020-01-23 00:20
I had a talk about this issue with @amirh.  We're going to write up a design doc for a long term solution.  Once we have something we are happy with it will get shipped with a later version of flutter and there will be a transition period where developers will be able to update their plugins.

The design doc will roughly look like a new API to get notifications when the engine is attached and detached, like in Android.  Until the new API ships with flutter and the plugins have been updated the workaround will need to be used.

cc @zoeyfan

**Comment by talisk** [comment] 2020-01-23 04:04
@gaaclarke 

Ok. The current temporary solution for the delayed release engine is available and stable to me. If there's any developer encountered the same issue, you can share this case to him.

**Comment by Hixie** [comment] 2020-01-29 00:11
Since we have a workaround for now and a plan for a long-term solution, I'm moving this off the blocker list. Please don't hesitate to put the label back if you are still blocked.

**Comment by gaaclarke** [comment] 2020-02-07 17:15
There is now a solution from https://github.com/flutter/engine/pull/16336 but requires plugin developers to take advantage of it.

**Closed by gaaclarke** 2020-02-07 17:15 UTC
Labels: a: existing-apps, customer: gold, customer: hand, engine, plugin, severe: new feature, severe: performance, ⌺‬ platform-ios
