### ISSUE TITLE
"Failure to dismiss dialog" errors on Mac_ios 20flutter_gallery__transition_perf_e2e_ios

### ISSUE THREAD

**Issue by flar** [flutter/flutter#104675] opened 2022-05-26 00:58 UTC
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery__transition_perf_e2e_ios

Examples:

https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery__transition_perf_e2e_ios/2292
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery__transition_perf_e2e_ios/2294
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery__transition_perf_e2e_ios/2295
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery__transition_perf_e2e_ios/2296
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery__transition_perf_e2e_ios/2298
https://ci.chromium.org/p/flutter/builders/staging/Mac_ios%20flutter_gallery__transition_perf_e2e_ios/2299

**Comment by christopherfujino** [comment] 2022-05-26 02:05
Thank you for filing this issue! However, I am going to close it as a duplicate of https://github.com/flutter/flutter/issues/104672. Please follow that issue for for more information and updates. Thanks!

**Closed by christopherfujino** 2022-05-26 02:05 UTC
Labels: team: infra
