### ISSUE TITLE
[video_player] Playback is jittery when another PlatformVIew is present

### ISSUE THREAD

**Issue by jaggernod** [flutter/flutter#79874] opened 2021-04-06 16:54 UTC
Whenever there is another PlatformView active (tested with `google_mobile_ads` and `youtube_player_iframe`) the video is played at 1 FPS.

Reproduction steps:
1. clone the official example from video_player
2. Add `youtube_player_iframe` or `google_mobile_ads` plugins
3. Place the `youtube_player_iframe` or `google_mobile_ads` widget under video player widget.

Expected result:
Video is played at a normal rate (> 30 FPS)

Observed result:
Video is played at a really slow rate (~1 FPS)

Screen recording:
https://user-images.githubusercontent.com/2519463/113746386-91675b80-9706-11eb-9f0a-d55cc73b371c.mp4

Git Patch of the example repo:
[jitter_patch.txt](https://github.com/flutter/flutter/files/6266339/jitter_patch.txt)

**Comment by iapicca** [comment] 2021-04-06 20:03
@jaggernod 
[youtube_player_iframe](https://pub.dev/packages/youtube_player_iframe) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/sarbagyastha/youtube_player_flutter/issues)
or provide your `flutter doctor -v`, your `flutter run -v` 
and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

**Comment by jaggernod** [comment] 2021-04-07 08:29
Thank you for the quick response. 
**youtube_player_iframe** was just one of the not working examples. [google_mobile_ads](https://pub.dev/packages/google_mobile_ads) which is maintained by the Flutter team (1st party plugin) and has the same issue.

I'm more than happy to create a new project just with **video_player** and a custom PlatformView exposing an Android view. 
Could you please tell me @iapicca if it is what you need?

**Comment by TahaTesser** [comment] 2021-04-07 12:18
Hi @jaggernod 
I tried to reproduce the issue using a platformview (`google_map_flutter`) with `video_player`, no jitter

<details> 
<summary>code sample</summary> 

```dart
import 'dart:async';

import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;
  Completer<GoogleMapController> _mapController = Completer();

  static final CameraPosition _kGooglePlex = CameraPosition(
    target: LatLng(37.42796133580664, -122.085749655962),
    zoom: 14.4746,
  );

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
      ..initialize()
      ..setLooping(true)
      ..play().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Column(
          children: [
            Center(
              child: _controller.value.isInitialized
                  ? AspectRatio(
                      aspectRatio: _controller.value.aspectRatio,
                      child: VideoPlayer(_controller),
                    )
                  : Container(),
            ),
            Container(
              height: 200,
              child: GoogleMap(
                mapType: MapType.hybrid,
                initialCameraPosition: _kGooglePlex,
                onMapCreated: (GoogleMapController controller) {
                  _mapController.complete(controller);
                },
              ),
            )
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

``` 

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision b1395592de (6 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • IN2011 (mobile) • c9d8ee0c • android-arm64  • Android 11 (API 30)
    • macOS (desktop) • macos    • darwin-x64     • macOS 11.2.3 20D91
      darwin-x64
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```
	
</details>

Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter run --verbose` logs running the minimal code sample?
Thank you

**Comment by iapicca** [comment] 2021-04-07 12:28
> [google_mobile_ads](https://pub.dev/packages/google_mobile_ads) which is maintained by the Flutter team (1st party plugin) and has the same issue.

@TahaTesser is this assertion true? seems 3rd party to me judging from [repo](https://github.com/googleads/googleads-mobile-flutter/issues) and [publisher](https://pub.dev/packages/google_mobile_ads)

**Comment by TahaTesser** [comment] 2021-04-07 13:26
@iapicca 
it is a a third-party package,  has separate repo but the issue is related to platform view so it should reproduce reproduce with `google_maps_flutter` or `webview_flutter`

**Comment by jaggernod** [comment] 2021-04-07 15:24
Thanks a lot for help and trying to reproduce the issue. 
I will try to reproduce the jitter with the Google maps package or or another Google package.
It would be really wierd if only the 2 packages I'm using have this issue.

**Comment by jaggernod** [comment] 2021-04-08 10:30
After further investigation, it turned out that there are two sets of plugins.
1. `webview_flutter`, `google_maps_flutter`, `video_player`
2. `google_mobile_ads`, `youtube_player_iframe`

If one uses just the plugins from a single group. 1 or 2 the jitter does not happen. However, when one mixes the groups then we have the jitter. 

I haven't noticed that as I was using all plugins from 2. with just  `video_player` from 1. Therefore I inferred that it is  `video_player` that is causing the jitter. 

As group 1 is the more stable and official flutter plugins I will report the issue to [googleads-mobile-flutter](https://github.com/googleads/googleads-mobile-flutter) and [youtube_player_iframe](https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_iframe).

Thank you very much for helping figure out the issue.

If someone in the future would like to reproduce the issue I will attach the code and my flutter doctor info:
<details>
  <summary>Code sample</summary>

<p>

```dart
import 'dart:async';

import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';
import 'package:youtube_player_iframe/youtube_player_iframe.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4')
      ..initialize()
      ..setLooping(true)
      ..play().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: ListView(
          children: [
            Container(
              height: 200,
              child: WebView(
                initialUrl:
                    'https://www.youtube.com/watch?v=oYnpQ3Mjg_g&ab_channel=TeslaDaily',
                javascriptMode: JavascriptMode.unrestricted,
              ),
            ),
            Container(
              height: 200,
              child: BannerAdWidget(AdSize.banner),
            ),
            Container(
              height: 200,
              child: YoutubeDemo(),
            ),
            Center(
              child: _controller.value.isInitialized
                  ? AspectRatio(
                      aspectRatio: _controller.value.aspectRatio,
                      child: VideoPlayer(_controller),
                    )
                  : Container(),
            ),
          ],
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              _controller.value.isPlaying
                  ? _controller.pause()
                  : _controller.play();
            });
          },
          child: Icon(
            _controller.value.isPlaying ? Icons.pause : Icons.play_arrow,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

class BannerAdWidget extends StatefulWidget {
  BannerAdWidget(this.size);

  final AdSize size;

  @override
  State<StatefulWidget> createState() => BannerAdState();
}

class BannerAdState extends State<BannerAdWidget> {
  BannerAd _bannerAd;
  final Completer<BannerAd> bannerCompleter = Completer<BannerAd>();

  @override
  void initState() {
    super.initState();
    _bannerAd = BannerAd(
      adUnitId: BannerAd.testAdUnitId,
      request: AdRequest(),
      size: widget.size,
      listener: AdListener(
        onAdLoaded: (Ad ad) {
          bannerCompleter.complete(ad as BannerAd);
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          ad.dispose();
          bannerCompleter.completeError(error);
        },
      ),
    );
    Future<void>.delayed(Duration(seconds: 1), () => _bannerAd.load());
  }

  @override
  void dispose() {
    super.dispose();
    _bannerAd.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<BannerAd>(
      future: bannerCompleter.future,
      builder: (BuildContext context, AsyncSnapshot<BannerAd> snapshot) {
        Widget child;

        switch (snapshot.connectionState) {
          case ConnectionState.none:
          case ConnectionState.waiting:
          case ConnectionState.active:
            child = Container();
            break;
          case ConnectionState.done:
            if (snapshot.hasData) {
              child = AdWidget(ad: _bannerAd);
            } else {
              child = Text('Error loading $BannerAd');
            }
        }

        return Container(
          width: _bannerAd.size.width.toDouble(),
          height: _bannerAd.size.height.toDouble(),
          color: Colors.blueGrey,
          child: child,
        );
      },
    );
  }
}

class YoutubeDemo extends StatefulWidget {
  @override
  _YoutubeDemoState createState() => _YoutubeDemoState();
}

class _YoutubeDemoState extends State<YoutubeDemo> {
  YoutubePlayerController _controller;

  @override
  void initState() {
    super.initState();

    _controller = YoutubePlayerController(
      initialVideoId: 'tcodrIK2P_I',
      params: const YoutubePlayerParams(
        playlist: [
          'nPt8bK2gbaU',
        ],
        startAt: const Duration(minutes: 1, seconds: 36),
        showControls: true,
        showFullscreenButton: true,
        desktopMode: true,
        privacyEnhanced: true,
        useHybridComposition: true,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return YoutubePlayerControllerProvider(
      controller: _controller,
      child: YoutubePlayerIFrame(),
    );
  }

  @override
  void dispose() {
    _controller.close();

    super.dispose();
  }
}
```

</p>
</details>

<details>
  <summary>flutter doctor -v</summary>

<p>

```bash
[✓] Flutter (Channel unknown, 2.1.0-12.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-12.2.pre at /home/jaggernod/work/tools/flutter
    • Framework revision 5bedb7b1d5 (3 weeks ago), 2021-03-17 17:06:30 -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/jaggernod/work/android-sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/101/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 11.0.0-2
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.2

[✓] Android Studio (version 4.1)
    • Android Studio at /snap/android-studio/101/android-studio
    • Flutter plugin version 52.2.1
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • Redmi Note 9 Pro (mobile) • a9626ba6 • android-arm64  • Android 10 (API 29)
    • Linux (desktop)           • linux    • linux-x64      • Linux
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

</p>
</details>

**Comment by TahaTesser** [comment] 2021-04-09 10:11
Hi @jaggernod 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-04-09 10:11 UTC
Labels: in triage
