### ISSUE TITLE
 Add a command line to select the version during upgrade

### ISSUE THREAD

**Issue by ahmedGibran** [flutter/flutter#109030] opened 2022-08-05 09:12 UTC
i'm unable to switch to the a specific version during upgrade! But I'm able to use that with downgrade e.g : `flutter downgrade v2.8.2` and I suggest to have something like `flutter upgrade v2.10.0 ` which is not exist now.

**Comment by exaby73** [comment] 2022-08-05 10:29
Closing as duplicate of https://github.com/flutter/flutter/issues/14230

**Closed by exaby73** 2022-08-05 10:29 UTC
Labels: in triage
