### ISSUE TITLE
[tool_crash] StateError: Bad state: The client closed with pending request "_yieldControlToDDS".

### ISSUE THREAD

**Issue by Benjith** [flutter/flutter#66823] opened 2020-09-28 13:50 UTC
## Command
```
flutter run --machine --target lib\main.dart -d 192.168.1.104:5555 --track-widget-creation --dart-define=flutter.inspector.structuredErrors=true --start-paused --web-server-debug-protocol ws --web-server-debug-backend-protocol ws --web-allow-expose-url
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: The client closed with pending request "_yieldControlToDDS".
```
#0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
#1      _rootRun (dart:async/zone.dart:1182:47)
#2      _CustomZone.run (dart:async/zone.dart:1093:19)
#3      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:167:18)
#4      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:666:39)
#5      Future._propagateToListeners (dart:async/future_impl.dart:722:37)
#6      Future._propagateToListeners (dart:async/future_impl.dart:621:9)
#7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#9      _rootRun (dart:async/zone.dart:1190:13)
#10     _CustomZone.run (dart:async/zone.dart:1093:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.251, on Microsoft Windows [Version 10.0.17763.1457], locale en-IN)
    • Flutter version 1.22.0-10.0.pre.251 at C:\sdk\flutter
    • Framework revision d26268bb9e (11 days ago), 2020-09-18 09:06:26 +0900
    • Engine revision 2abe69c608
    • Dart version 2.10.0 (build 2.10.0-136.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Benjith\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Benjith\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.49.2)
    • VS Code at C:\Users\Benjith\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[✓] Connected device (6 available)
    • Nokia 6 1 Plus (mobile) • 192.168.1.101:5555 • android-arm    • Android null (API null)
    • Moto C Plus (mobile)    • 192.168.1.104:5555 • android-arm    • Android 7.0 (API 24)
    • Windows (desktop)       • windows            • windows-x64    • Microsoft Windows [Version 10.0.17763.1457]
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 85.0.4183.121
    • Edge (web)              • edge               • web-javascript • Microsoft Edge 85.0.564.63

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: e0ed12c73a3df00b72af6e5657d35035a76c90db
### Plugins
device_info-0.4.2+6
firebase_core-0.5.0
firebase_core_web-0.2.0
firebase_messaging-7.0.0
flutter_local_notifications-1.4.4+4
flutter_mailer-0.5.1
flutter_plugin_android_lifecycle-1.0.8
flutter_share-1.0.2+1
fluttertoast-7.0.2
image_cropper-1.3.1
image_picker-0.6.7+4
package_info-0.4.1
path_provider-1.6.11
path_provider_linux-0.0.1+2
path_provider_macos-0.0.4+3
permission_handler-5.0.1+1
screen-0.0.5
shared_preferences-0.5.8
shared_preferences_linux-0.0.2+1
shared_preferences_macos-0.0.1+10
shared_preferences_web-0.1.2+7
sqflite-1.3.1
store_redirect-1.0.2
url_launcher-5.5.0
url_launcher_linux-0.0.1+1
url_launcher_macos-0.0.1+7
url_launcher_web-0.1.2+1
video_player-0.10.12
video_player_web-0.1.3+2
wakelock-0.1.4+2
webview_flutter-0.3.22+1

**Comment by jonahwilliams** [comment] 2020-09-28 14:34
Duplicate of https://github.com/flutter/flutter/issues/66514

**Closed by jonahwilliams** 2020-09-28 14:34 UTC
