### ISSUE TITLE
Helpers for native views integration testing

### ISSUE THREAD

**Issue by cedvdb** [flutter/flutter#100414] opened 2022-03-19 13:23 UTC
When doing integration testing, the usual main blocker that is consistently painful is dealing with native platform side effects. 

For example:

  - Accepting a geolocation request.
  - Changing user position on the underlying platform
  - Take a picture
  - Select files
  - ...
  
All of those require to go into the source code of the plugin used and mock the method channel result, which is very cumbersome because you have to dig the plugin source. It also couples your test tightly with the plugin used. It would be nice if there was a simpler way to do this. The best way would be without mocking, where an helper would allow us to interact with native views.

Something like:

```dart
NativePlatform.acceptPermission();
NativePlatform.takePicture();
NativePlatform.setUserPosition(lat: 0, long: 0);
```

**Comment by stuartmorgan** [comment] 2022-03-19 14:51
Duplicate of https://github.com/flutter/flutter/issues/86295

**Closed by stuartmorgan** 2022-03-19 14:51 UTC
