### ISSUE TITLE
Flutter doesn't have a built-in sound play library

### ISSUE THREAD

**Issue by yingshaoxo** [flutter/flutter#131162] opened 2023-07-23 17:10 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

Flutter doesn't have a built-in sound play library

So you can't use flutter to make music player, video player or game engine.

### Proposal

Make a built-in wav or mp3 play function.

**Comment by stuartmorgan** [comment] 2023-07-23 17:48
Closing as a duplicate of https://github.com/flutter/flutter/issues/47105

**Closed by stuartmorgan** 2023-07-23 17:48 UTC

**Comment by stuartmorgan** [comment] 2023-07-23 17:49
> So you can't use flutter to make music player, video player or game engine.

The purpose of Flutter's plugin system is to make it possible to do things that use functionality that is not built-in; there are a variety of audio plugins.

**Comment by yingshaoxo** [comment] 2023-07-23 22:21
I have never seen a frontend framework can't play audio.

Does all flutter user has disability in hearing?
