### ISSUE TITLE
MediaQuery.of(context).platformBrightness doesn't respect system's theme on linux

### ISSUE THREAD

**Issue by qrhfz** [flutter/flutter#116882] opened 2022-12-12 11:40 UTC
## Steps to Reproduce

1. Set your linux DE to use dark theme. Mine is Mint-Y-Dark in Linux Mint Cinnamon
2. Paste the code in code sample to main.dart of a new flutter project
3. run the project
4. see the app and debug log

**Expected results:** App is in dark mode and `MediaQuery.of(context).platformBrightness` returns Brightness.dark

**Actual results:** App is still in light mode and `MediaQuery.of(context).platformBrightness` returns Brightness.light

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      darkTheme: ThemeData.dark(),
      home: Builder(builder: (context) {
        print(MediaQuery.of(context).platformBrightness);
        return const Scaffold();
      }),
    );
  }
}
```
</details>

<details>
  <summary>Logs</summary>

**debug log**
```
Launching lib/main.dart on Linux in debug mode...
lib/main.dart:1
Connecting to VM Service at ws://127.0.0.1:41727/3teH2FVqfdU=/ws
flutter: Brightness.light
```

**flutter doctor**
```
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 3.3.9, on Linux Mint 21 5.15.0-56-generic, locale
    en_US.UTF-8)
    • Flutter version 3.3.9 on channel stable at /home/q/.sauce/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 weeks ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/q/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /home/q/.software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • Homebrew clang version 15.0.6
    • cmake version 3.25.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/q/.software/android-studio
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /home/q/.software/idea
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.54.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 21
      5.15.0-56-generic
    • Chrome (web)    • chrome • web-javascript • Chromium 108.0.5359.94 for
      Linux Mint

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by gintominto5329** [comment] 2022-12-12 13:13
There is not definite way of telling dark mode on gnu/linux, 

gnome does x, 
kde does y, 
others do z, 

what all could be implemented...

**Comment by darshankawar** [comment] 2022-12-13 07:29
Thanks for the report @qrhfz 
Can you check if your issue is same as https://github.com/flutter/flutter/issues/101438 which has since been fixed ?
Also please switch to latest master and see if you still get same behavior or not.

`flutter channel master`
`flutter upgrade`

**Comment by qrhfz** [comment] 2022-12-13 12:56
![Screenshot from 2022-12-13 19-55-02](https://user-images.githubusercontent.com/57665201/207323837-e6454f9c-72c9-43fd-94ba-95bb6d19e993.png)

```
➜  test_brightness flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.7.0-7.0.pre.5, on Linux Mint 21
    5.15.0-56-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3)
[✓] VS Code (version 1.74.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

issue still persist

**Comment by exaby73** [comment] 2022-12-13 14:26
Hello @qrhfz. I cannot reproduce this issue with KDE Plasma. This could be similar to https://github.com/flutter/flutter/issues/116511. Could you check your OS settings to see what it's set to? For example: in Gnome, you can check it using `gsettings`. There have been similar issues with Linux Mint (Cinnamon DE) like https://forums.linuxmint.com/viewtopic.php?t=273055, https://forums.linuxmint.com/viewtopic.php?t=251748

**Comment by qrhfz** [comment] 2022-12-14 11:29
i spun up kubuntu and ubuntu 22.04. i can confirm this isn't issue in kde and gnome. so it is probably correct that this is a regression on cinnamon part.

**Comment by exaby73** [comment] 2022-12-15 08:17
Since this is a regression on Cinnamon, I feel safe to close this issue as it's not an issue with Flutter itself. Thank you

**Closed by exaby73** 2022-12-15 08:17 UTC
Labels: in triage
