### ISSUE TITLE
"Use password" must be clicked twice

### ISSUE THREAD

**Issue by MatsG23** [flutter/flutter#84037] opened 2021-06-05 11:49 UTC
Hello!

This issue is regarded to the Flutter Plugin _local\_auth_.

When I click on the button on the bottom left of the authentication request, "Use password", I must re-press this button again after I entered the device's password and clicked on the Enter button of the keyboard.

**The code snippet I'm using**
```
Future<bool> _authorize() async {
    final bool hasLockScreen = await localAuth.isDeviceSupported();
    if (!hasLockScreen) return true;

    return await localAuth.authenticate(
        localizedReason: "Verifiziere deine Identität, um fortzufahren",
        androidAuthStrings: localAuthStrings,
        stickyAuth: true,
        useErrorDialogs: false);
  }
```

**My versions**
- Flutter 2.2.1
- Framework revision 02c026b03c
- Engine revision 0fdb562ac8
- Dart 2.13.1
- cupertino_icons: ^1.0.3
- http: ^0.13.3
- local_auth: ^1.1.6
- path_provider: ^2.0.2
- flutter_secure_storage: ^4.2.0

Best Regards
Mats

**Comment by TahaTesser** [comment] 2021-06-07 10:53
Hi @MatsG23 
Are you using a Xiaomi device? See https://github.com/flutter/flutter/issues/83773
Please provide more details the device

**Comment by MatsG23** [comment] 2021-06-07 17:13
@TahaTesser
I'm using a Motorola g7 power phone with the normal Android (10).

I must not re-input the passphrase like in the issue you mentioned. The second time I click on the "Use password" button, it simply let me pass.

**Comment by TahaTesser** [comment] 2021-06-08 06:40
Hi @MatsG23 
Let's track this under one issue https://github.com/flutter/flutter/issues/83773
Closing as duplicate of https://github.com/flutter/flutter/issues/83773

**Closed by TahaTesser** 2021-06-08 06:40 UTC
Labels: in triage
