### ISSUE TITLE
Blank space above keyboard

### ISSUE THREAD

**Issue by pedia** [flutter/flutter#14881] opened 2018-02-26 11:14 UTC
## Steps to Reproduce
TextField Code:
```
                 new TextField(
                    style: ...,
                    focusNode: focusNode,
                    controller: textController,
                    onSubmitted: (String content) {},
                    autocorrect: false,
                    maxLines: 1,
                    decoration: new InputDecoration(
                      isDense: true,
                      icon: new Icon(Icons.search,
                          color: Colors.white30, size: 24.0),
                      border: InputBorder.none,
                      hintStyle: searchStyle,
                      hintText: '...',
                    ),
                  )
```

How to avoid blank space above the keyboard?  Same space occurs in Simulator and iOS Phone.

![](https://i.imgur.com/aRk0cFJ.png)

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.1.4-pre.5, on Mac OS X 10.13.3 17D47, locale en-HK)
    • Flutter version 0.1.4-pre.5 at /Users/odd/wa/flutter/flutter
    • Framework revision d8f4b1f55a (2 days ago), 2018-02-24 23:38:54 +0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.3)
    • Android SDK at /Users/odd/Library/Android/sdk
    • Android NDK at /Users/odd/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 26.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 20.0.3
    • Dart plugin version 173.3727.108

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.9.0

[✓] Connected devices (2 available)
    • ONEPLUS A5000 • bd636bb3                             • android-arm64 • Android 7.1.1 (API 25)
    • iPhone 6s     • 28B00868-73F6-4816-8451-FCFF1DD1E855 • ios           • iOS 11.2 (simulator)

• No issues found!
```

**Comment by naeem76** [comment] 2018-02-27 06:19
Same issue

**Comment by pedia** [comment] 2018-03-01 15:17
>> Is this always reproducible?
Yes,  Same on Simulator and iPhone, Android.

>> Do you have any alternate keyboards installed? Does this happen only if you switch between those layouts, or even when the English keyboard is opened?
I have installed only English Keyboard in Simulator.
I have installed English and Chinese Keyboard on iPhone.
I never switched between keyboards. It always keeps space.

@cbracken I created a fresh project with the same code, The blank space has gone.
I will dig in this.

**Comment by pedia** [comment] 2018-03-01 15:23
@cbracken I'm sure this is my bug. Sorry.

@naeem76 I will comment here when I resolved this bug.

**Comment by pedia** [comment] 2018-03-02 09:18
Since I cannot reproduce the bug in a demo project. I dig into the original app.

This image below is the result of widget inspector 
<img width="240" alt="image" src="https://user-images.githubusercontent.com/170561/36891251-e9a301e2-1e3b-11e8-9581-b65d0b769fd8.png">

- The RawImage is not visible, even it's in the right position.
- The blank space is not a Widget able to be inspected.

The hierarchy of this Wiget:
```dart
new Scaffold(
      backgroundColor: Colors.green,
      body: new Column(
        children: [
          new TextField(),
          new Container(),
          ...
          new Expanded(
            child: new ListView.builder())
       ]
   )
);
```



@naeem76 Any advice?

**Comment by cbracken** [comment] 2018-03-07 17:27
@pedia re-closing since this looks unrelated to the original issue. Please open a new bug if you're running into a framework issue (or if we could document existing APIs better).

For non-bug questions about how best to achieve certain results with Flutter, I'd definitely recommend asking on [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or in our [Gitter](gitter.im/flutter/flutter) chat room. They're also likely to have quicker answers.

**Closed by cbracken** 2018-03-07 17:27 UTC
Labels: prod: text input, ⌺‬ platform-ios

**Comment by shrey112710** [comment] 2021-07-12 14:22
Any luck with this issue? 
As I can reproduce this issue for the flutter-web client with `resizeToAvoidBottomInset` set to false. 
I can see the white spacing above the keyboard in the iPad(safari and chrome).
