### ISSUE TITLE
Backspace/delete not working at word boundary after mixing RTL/LTR text

### ISSUE THREAD

**Issue by GaryQian** [flutter/flutter#56149] opened 2020-05-01 22:05 UTC
Extracted from https://github.com/flutter/flutter/issues/22627

As reported by @FlutterIODev:

> Now when you write Arabic words and try to delete them, everything works fine, but if you tried to write English words then try to delete them flutter will be stuck after deleting one word and will never respond to the delete button from the keyboard.
> 
> The problem appears on a physical device as well as on the Android emulator.
> 
> The following [video](https://drive.google.com/open?id=1HBtWoRbv90puAelCSiK1TgtssZrs24GN) describes the problem.
> 
> # Flutter Version
> ```
> [√] Flutter: is fully installed. (Channel master, v1.18.0-9.0.pre.14, on Microsoft Windows [Version 10.0.17763.805],
>     locale en-US)
> [√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 29.0.1)
> [√] Chrome - develop for the web: is fully installed.
> [√] Android Studio: is fully installed. (version 3.5)
> [√] IntelliJ IDEA Community Edition: is fully installed. (version 2019.1)
> [√] VS Code: is fully installed. (version 1.44.2)
> [√] Connected device: is fully installed. (3 available)
> ```
> 
> # Sample Code
> ```
> import 'package:flutter/material.dart';
> import 'package:flutter_localizations/flutter_localizations.dart';
> 
> void main() => runApp(MyApp());
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       localizationsDelegates: [
>         GlobalMaterialLocalizations.delegate,
>         GlobalWidgetsLocalizations.delegate,
>       ],
>       supportedLocales: [Locale("ar")],
>       locale: Locale("ar"),
>       home: Scaffold(
>         appBar: AppBar(),
>         body: Padding(
>           padding: EdgeInsets.all(8),
>           child: TextField(),
>         ),
>       ),
>     );
>   }
> }
> ```

Things to note:

- Works fine in just one language
- If languages are mixed, even erasing and typing in one language again prevents this from working.

**Comment by GaryQian** [comment] 2020-05-01 22:09
This may be due to the insertion of RTL and LTR marks to handle trailing whitespace. Will investigate.

**Comment by alimahdiyar** [comment] 2020-05-02 06:45
I think these strange behaviors come from using Andorid API and it's different behaviors in different API Levels. I wasn't able to repro. Is this problem fixed with flutter/engine#17960?

**Comment by Sal7one** [comment] 2020-05-22 21:04
Same problem! I think it's the cursor Not being able to switch direction

**Comment by alimahdiyar** [comment] 2020-05-23 10:07
@Sal7one Can you please post your flutter doctor output?

**Comment by halahmadi** [comment] 2020-05-24 17:54
Same problem experienced in the beta version.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18362.836], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[!] VS Code (version 1.45.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

**Comment by halahmadi** [comment] 2020-05-24 18:03
The issue also exists in the master channel

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.19.0-2.0.pre.143, on Microsoft Windows [Version 10.0.18362.836], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[!] VS Code (version 1.45.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by halahmadi** [comment] 2020-05-24 18:48
I noticed something strange. In the text properties, if you set the "maxLines" to a value greater than 1 and removes "maxLength" property, the issue goes away!

**Comment by Sal7one** [comment] 2020-05-27 04:57
Yeah this worked and spaces do get deleted now, But that doesn't seem like a good solution now the text field is huge lol

**Comment by Sal7one** [comment] 2020-05-27 04:58
> @Sal7one Can you please post your flutter doctor output?
> Are you experiencing this problem on channel master?

Yes I am sir. on master

**Comment by chinmaygarde** [comment] 2020-06-11 01:06
Triage: @GaryQian, I removed the regression label because it wasn't clear to me that this was a regression. If I am mistaken, please add the label back. Thanks.

**Comment by GaryQian** [comment] 2020-06-11 01:07
I have confirmed that this is indeed a regression, adding back!

**Comment by chinmaygarde** [comment] 2020-06-11 07:23
Ok, adjusting the priority and setting a tentative milestone. Do we know when this regressed?

**Comment by zanderso** [comment] 2020-06-12 15:48
Assigning @GaryQian based on this thread.

@GaryQian modulo any higher priority work, if will be possible to fix this in time for the next stable cutoff, then can we set the June milestone for this?

**Comment by GaryQian** [comment] 2020-06-12 18:42
Yeah will work on this asap.

**Comment by alimahdiyar** [comment] 2020-06-12 19:39
@GaryQian Can I help you?
I wasn't able to reproduce in the Linux engine build. All flutter doctor results are from windows so I'm wondering if it's something related to flutter on windows

**Comment by GaryQian** [comment] 2020-06-12 20:15
Has to do with https://github.com/flutter/flutter/pull/51964

Will try to fix forward, but capping at one day of work at which point we can roll back as this behavior is also currently handled by LibTxt and should not regress.

**Comment by GaryQian** [comment] 2020-06-13 04:40
https://github.com/flutter/flutter/pull/59379 Should fix this.

**Closed** 2020-06-16 17:20 UTC
Labels: P3, a: internationalization, a: text input, a: typography, engine, f: material design, found in release: 1.18, framework, severe: regression, targeted to release: 1.20

**Comment by GaryQian** [comment] 2020-06-16 20:44
#59379 Has landed on master branch, please feel free to let us know if you still see this happening.

**Comment by Sal7one** [comment] 2020-06-16 21:12
@GaryQian Working great Thank you! Tested on Web, Android phone.

Master Channel
