### ISSUE TITLE
Web issue: The following NoSuchMethodError was thrown during a scheduler callback: '<Unexpected Null Value>' method not found Receiver: null Arguments: []

### ISSUE THREAD

**Issue by AbdulRafaySiddiqui** [flutter/flutter#65195] opened 2020-09-03 19:27 UTC
I am getting this error, when I am running my app on the web,
I think its the same issue mentioned below:
[https://github.com/flutter/flutter/issues/43931
](url)
════════ Exception caught by scheduler library ═════════════════════════════════
The following NoSuchMethodError was thrown during a scheduler callback:
'<Unexpected Null Value>'
method not found
Receiver: null
Arguments: []

When the exception was thrown, this was the stack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49      throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 54:3        throwNullValueError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 490:39  _notNull
packages/flutter/src/material/scrollbar.dart 184:33                                                                            [_handleScrollNotification]
packages/flutter/src/widgets/notification_listener.dart 133:41

I am using Flutter 1.21.0-9.2.pre • channel beta
here is my flutter doctor -v

[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.17763.1397], locale en-US)
    • Flutter version 1.21.0-9.2.pre at C:\Flutter SDK\flutter
    • Framework revision 81a45ec2e5 (7 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Dell\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.48.2)
    • VS Code at C:\Users\Dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

• No issues found!

**Comment by darshankawar** [comment] 2020-09-04 06:20
Hi @AbdulRafaySiddiqui,
You are right. It seems to be a duplicate of [43931](https://github.com/flutter/flutter/issues/43931).
Can you switch to latest master and see if you still see the issue ? If you see the issue there too, will reopen 43931.
Thanks.

**Comment by AbdulRafaySiddiqui** [comment] 2020-09-04 11:57
I switched to master but still the same Exception.

**Comment by darshankawar** [comment] 2020-09-04 13:16
Thanks @AbdulRafaySiddiqui. It'll be good if you post your observation in the original ticket along with `flutter doctor -v` and mention that you tried on latest master and still see the issue and request to reopen that issue.
Thanks.

**Comment by AbdulRafaySiddiqui** [comment] 2020-09-04 13:48
Thanks for your response @darshankawar. The original issue is locked, I can't post on it.

**Comment by darshankawar** [comment] 2020-09-04 13:53
Ok, I am reopening that issue and will refer this issue.
Closing this as duplicate.

**Comment by AbdulRafaySiddiqui** [comment] 2020-09-04 15:29
The issue seems to be in the [Scrollbar Widget](https://api.flutter.dev/flutter/material/Scrollbar-class.html), 
`bool _handleScrollNotification(ScrollNotification notification) {
    final ScrollMetrics metrics = notification.metrics;
    **if (metrics.maxScrollExtent <= metrics.minScrollExtent) //this throws the exception** {
      return false;
    }...`
when its **_handleScrollNotification** is called by NotificationListener<ScrollNotification>'s onNotification callback, the notification's metrics.maxScrollExtent && metrics.minScrollExtent seems to be null which throws the exception.
The exception message is the same as the [43931](https://github.com/flutter/flutter/issues/43931) but it's a different issue I think.

**Comment by darshankawar** [comment] 2020-09-11 07:22
Reopening this issue per [this](https://github.com/flutter/flutter/issues/43931#issuecomment-690757013) comment.

**Comment by darshankawar** [comment] 2020-09-11 07:23
Hi @AbdulRafaySiddiqui,
If you are still seeing this issue, please provide a minimal complete reproducible code sample.
Thanks.

**Comment by cjyyz** [comment] 2020-09-24 13:35
same here.

**Comment by TahaTesser** [comment] 2020-10-14 14:21
Hi @AbdulRafaySiddiqui  @cjyyz 
Snce there is no  reproducible codesample 

Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 14:21 UTC
Labels: in triage

**Comment by mohamedhanyyy** [comment] 2021-03-29 09:28
Same issue

**Comment by TahaTesser** [comment] 2021-03-29 13:11
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by abhayzadoo** [comment] 2021-04-29 12:01
I think this issue will be resolved by changing the version of ( firebaseJs to version 7.22.1 and also for firebase-firestore to 7.22.1) in index.html

**Comment by mohamedhanyyy** [comment] 2021-05-22 17:43
thanksss

**Comment by mohamedhanyyy** [comment] 2021-05-22 17:44
Can you find work for me


im flutter dedveloper


i want to do project or tasks not full time
