### ISSUE TITLE
Document that FlutterFragmentActivity, FlutterActivity, FlutterFragment can only be used in an AAR project inside an AndroidX outer project

### ISSUE THREAD

**Issue by YugeCse** [flutter/flutter#46840] opened 2019-12-12 04:02 UTC
FlutterFragmentActivity, FlutterActivity, FlutterFragment is not supprot AndroidX, and They use  support libaries!!!

**Comment by askarsyzdykov** [comment] 2019-12-12 04:57
@YugeCse could you post `flutter --version` output here?

**Comment by YugeCse** [comment] 2019-12-12 05:51
Flutter 1.13.0 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 09126abb22 (8 days ago) • 2019-12-03 17:43:00 -0800
Engine • revision 6179380243
Tools • Dart 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

**Comment by YugeCse** [comment] 2019-12-12 06:03
#askarsyzdykov
  I found that **FlutterActivity** File (Packages: io.flutter.app and io.flutter.embedding.android) still contained the support libraires's code.

**Comment by xster** [comment] 2019-12-12 22:48
Right, the Flutter engine is likely the last thing to migrate since if we migrated now, we're essentially removing the choice for developers who may, for one reason or another, need to keep their own app under Android Support. 

If you're on AndroidX, you can already use jetifier to make the Flutter engine compatible with your app. 

See https://flutter.dev/docs/development/add-to-app/android/project-setup#option-a---depend-on-the-android-archive-aar. 

cc @blasten, do we need to add some additional text to https://flutter.dev/docs/development/add-to-app/android/project-setup to talk about AndroidX?

**Comment by YugeCse** [comment] 2019-12-13 02:04
@xster That's unuseful. Becasuse the classes(FlutterFragmentActivity，FlutterActivity and FlutterFragment)'s code isn't editable. Long Long ago, we could edit Flutter's code in package io.flutter.app, but now, we cannot edit them. Also, package's code (io.flutter.embedding.android) isn't editable , too. So, we cannot let these classes become the AndroidX Code.

**Comment by xster** [comment] 2019-12-17 07:44
I don't mean make them AndroidX compatible by editing the code's import path directly. I meant by turning on jetifier for your project. Jetifier supports AAR modules (which includes your Flutter engine) so you Flutter engine's android support imports actually get turned into AndroidX imports.

**Comment by praveenb** [comment] 2019-12-19 14:42
Still not working with

```
Flutter (Channel master, v1.13.3-pre.83, on Microsoft Windows [Version 10.0.17763.914], locale en-IN)
		• Flutter version 1.13.3-pre.83 at E:\fluttersdk
    • Framework revision 78db965642 (2 hours ago), 2019-12-19 11:23:01 +0100
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

```
Same issue, due to FlutterFragment uses Support library classes. :(

**Comment by xster** [comment] 2019-12-19 19:46
Yes, the source is still Android support in the engine. But it's jetifiable if you enabled it in your host Android project such as https://github.com/flutter/samples/blob/master/add_to_app/android_fullscreen/gradle.properties. 

@blasten for potential additional clarifications in https://github.com/flutter/flutter/issues/32862

**Comment by YugeCse** [comment] 2019-12-20 05:43
My gradle.properties file's content: 

# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
#android.useDeprecatedNdk=true

**Comment by praveenb** [comment] 2019-12-20 07:00
> Yes, the source is still Android support in the engine. But it's jetifiable if you enabled it in your host Android project such as https://github.com/flutter/samples/blob/master/add_to_app/android_fullscreen/gradle.properties.
> 
> @blasten for potential additional clarifications in #32862

Hi @xster , I check gradle.properties file in host app, it has enabled jetifier already, below is the code

```
android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx4608M
org.gradle.java.home=C:/Program Files/Android/Android Studio/jre
```

Thank you.

**Comment by monkeylmj** [comment] 2019-12-26 13:04
> > Yes, the source is still Android support in the engine. But it's jetifiable if you enabled it in your host Android project such as https://github.com/flutter/samples/blob/master/add_to_app/android_fullscreen/gradle.properties.
> > @blasten for potential additional clarifications in #32862
> 
> Hi @xster , I check gradle.properties file in host app, it has enabled jetifier already, below is the code
> 
> ```
> android.enableJetifier=true
> android.useAndroidX=true
> org.gradle.jvmargs=-Xmx4608M
> org.gradle.java.home=C:/Program Files/Android/Android Studio/jre
> ```
> 
> though, its not picking Androidx classes from Flutter.
> 
> Thank you.

I meet the same problem and this works for me. though, it shows error in editor, but it is runnable and works correctly.

**Comment by blasten** [comment] 2020-01-03 23:00
As, @xster mentioned, we will be migrating the Android embedding to AndroidX this quarter.

**Comment by jmagman** [comment] 2020-01-30 22:40
> As, @xster mentioned, we will be migrating the Android embedding to AndroidX this quarter.

@blasten Is the engine work tracked in https://github.com/flutter/flutter/issues/39283?

If so, is this issue just tracking adding a note about Android X to https://flutter.dev/docs/development/add-to-app/android/project-setup?  Is that documentation work already tracked in https://github.com/flutter/flutter/issues/32862?

**Comment by blasten** [comment] 2020-01-30 22:42
Duplicate of https://github.com/flutter/flutter/issues/39283

**Comment by oth-libs** [comment] 2020-02-10 12:55
> As, @xster mentioned, we will be migrating the Android embedding to AndroidX this quarter.

I'm having the same problem.. what can I do now in the meantime?? I'm on `flutter 1.15.2` and still have support classes. I already have `android.enableJetifier=true` in `gradle.properties`

**Comment by xster** [comment] 2020-02-15 06:19
Another clarification, (perhaps we should re-open this ticket to make sure we document this if you guys want to double check it first).

Yes, the engine currently uses support Fragment etc to not force all downstream users from using AndroidX. 

Jetifier doesn't work against a gradle subproject so if you built your flutter module as an AAR (flutter.dev/go/build-aar), then that should let jetifier work as a workaround until we do #39283. Would someone like to try it and report back?

**Comment by xster** [comment] 2020-10-12 17:31
The engine has been migrated to AndroidX now https://github.com/flutter/flutter/issues/39283.

**Closed by xster** 2020-10-12 17:31 UTC
Labels: P4, a: existing-apps, customer: crowd, d: website - content, documentation, platform-android, tool
