### ISSUE TITLE
Bug in slivers

### ISSUE THREAD

**Issue by Sparks1998** [flutter/flutter#41313] opened 2019-09-25 17:49 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

```
```

**Comment by janmoppel** [comment] 2019-09-26 08:10
Hello @Sparks1998 !

Thank you for posting.
However, without any additional information, such as the code to reproduce the issue and `flutter doctor -v` command output, your case cannot be investigated. Due to that, closing this issue.
But feel free to open a new issue and fill the information requested in the template.

Thank you.

**Closed by janmoppel** 2019-09-26 08:10 UTC
