### ISSUE TITLE
https://stackoverflow.com/questions/tagged/flutter?sort=frequent

### ISSUE THREAD

**Issue by SALMONEMMANUEL** [flutter/flutter#42322] opened 2019-10-09 12:07 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment] 2019-10-09 12:11
Hi @SALMONEMMANUEL 
can you please describe the issue?
Also, to better address the issue, would be helpful
if you could provide your `flutter doctor -v`post 
and self contained app on github
or the steps to reproduce it.
Thank you

**Comment by stuartmorgan** [comment] 2019-10-09 14:14
Closing since this appears to have been opened by mistake.

**Closed by stuartmorgan** 2019-10-09 14:14 UTC
Labels: waiting for customer response
