### ISSUE TITLE
IME Deltas - Two-finger scrolling on Mac trackpad changes selection

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/flutter#118642] opened 2023-01-17 21:22 UTC
Reproduction: Place the caret in a `SuperTextField` on a Mac. Place two fingers on the trackpad. Slide in any direction.

Expected: Nothing happens

Actual: The selection moves with the fingers.

https://user-images.githubusercontent.com/7259036/213014630-dc92f27c-402a-4216-a908-8af7b0aecaf9.mov

This behavior may be intentional, but we don't want it, and it's unclear how we turn it off.

We're receiving text editing deltas from the Mac IME, e.g., 

`Received delta: TextEditingDeltaNonTextUpdate#fcaf4(oldText: Super Editor is an open source text editor for Flutter projects., selection: TextSelection(baseOffset: 64, extentOffset: 36, isDirectional: false), composing: TextRange(start: -1, end: -1))`

We can't distinguish between that delta and another delta that represents a legitimate IME selection change.

```
Flutter 3.7.0-21.0.pre.42 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1220245b33 (3 days ago) • 2023-01-14 19:53:06 -0500
Engine • revision f790304409
Tools • Dart 3.0.0 (build 3.0.0-122.0.dev) • DevTools 2.20.0
```

**Comment by matthew-carroll** [comment] 2023-01-17 21:22
CC @justinmc @Renzo-Olivares

**Comment by moffatman** [comment] 2023-01-18 05:12
I checked it out and I think the source is the `PanGestureRecognizer` in `_SuperTextFieldGestureInteractorState`. When I set `supportedDevices: {PointerDeviceKind.mouse}`, it didn't happen any more.

**Comment by matthew-carroll** [comment] 2023-01-18 07:21
Thanks that seems resolve the issue. Do you know how the `PanGestureRecognizer` prevents the creation of IME deltas? Or was Flutter explicitly creating artificial IME deltas from within the gesture system?

**Comment by huycozy** [comment] 2023-01-18 12:25
As I see the issue is temporarily fixed by recent PR. Labeling this as a document issue for further discussion. 

Reference document: [For gesture interactions not suitable for trackpad usage](https://docs.flutter.dev/release/breaking-changes/trackpad-gestures#for-gesture-interactions-not-suitable-for-trackpad-usage)

**Comment by moffatman** [comment] 2023-01-18 14:02
I didn't find any delta coming from flutter. The `_SuperTextFieldGestureInteractorState` was changing the selection in response to the gesture.

**Comment by matthew-carroll** [comment] 2023-01-18 20:55
I pasted the delta log up in the original issue. I've merged this change into super_editor, but if you're able to run super_editor a few commits back, you can enable that log:

initLoggers(Level.ALL, {textfieldImeLog});

**Comment by moffatman** [comment] 2023-01-18 22:48
The delta is being sent from mac IME handling platform code, but the source of the selection change was the framework dart code. For some reason it is being bounced back up to the framework. I don't know enough about this area to say whether that's intended or not, but it seems to happen any time the text selection is changed from the dart side (at least on mac, I didn't check anywhere else).

**Comment by matthew-carroll** [comment] 2023-01-18 23:36
Ok, let's definitely have @justinmc and @Renzo-Olivares take a look at this, then.

**Comment by Renzo-Olivares** [comment] 2023-05-17 07:07
Looks like the engine "bouncing" this message back has to do with these lines of code in the `handleMethodCall` of the macOS TextInputPlugin.

https://github.com/flutter/engine/blob/ea3f27383accfe57b424d1794bfe590a46f7a97b/shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm#L452-L463

Originally added in https://github.com/flutter/engine/pull/13702 for non-delta editing, and it was inherited by delta editing when it was implemented.

I think this bouncing might not be needed anymore at least in the case defined in #13702, where `insertText` is called after the framework has already deleted the selected region. I tried it out and `insertText` is no longer called on the delete key, instead the engine sends `selectors` to the framework which are converted into `Intents` that the framework uses to manipulate its `TextEditingValue`. More context in these lines of code https://github.com/flutter/engine/blob/ea3f27383accfe57b424d1794bfe590a46f7a97b/shell/platform/darwin/macos/framework/Source/FlutterTextInputPlugin.mm#L776-L816 . 

`selectors -> intents` where originally implemented in https://github.com/flutter/engine/pull/33838 .

**Comment by Renzo-Olivares** [comment] 2023-05-26 21:09
Closing this as a fix was merged in https://github.com/flutter/engine/pull/42091 so the engine does not bounce back the editing state on setEditState. Please re-open if you are still experiencing this issue.

**Closed by Renzo-Olivares** 2023-05-26 21:09 UTC
Labels: framework, platform-mac, d: api docs, f: gestures, a: desktop, documentation, P4

**Comment by matthew-carroll** [comment] 2023-05-26 21:24
@angelosilvestre - can you confirm that this issue is resolved in Super Editor?

**Comment by angelosilvestre** [comment] 2023-06-03 19:40
@matthew-carroll I couldn't reproduce the issue in both master and stable branches.
