### ISSUE TITLE
Android crash: android.app.RemoteServiceException

### ISSUE THREAD

**Issue by marcoheine** [flutter/flutter#75623] opened 2021-02-08 11:16 UTC
Hi,

my App works on every device except Samsung Galaxy XCover4 (Android 9 (SDK 28)).

The user says the App crashes every time and the Google Play Console Crash Report gives me that stacktrace:

```bash
android.app.RemoteServiceException: 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1894)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7156)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
```

I have no idea what i could do. I can't reproduce it.

Flutter Doctor: 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.3 19D76 darwin-x64, locale de-DE)
    • Flutter version 1.22.6 at /Users/m.heine/flutter
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at /Users/m.heine/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

```

</details>

**Comment by TahaTesser** [comment] 2021-02-08 14:54
Hi @marcoheine 
Are you using `flutter_background_geolocation`. 
Can you please provide your `pubspec.yaml` & your `flutter run --release --verbose` 
Thank you

**Comment by marcoheine** [comment] 2021-02-12 15:20
Yes, I am using "background_locator".

Now there is a more information:

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:3684)
  at android.app.ActivityThread.access$2000 (ActivityThread.java:218)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1801)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:145)
  at android.app.ActivityThread.main (ActivityThread.java:6914)
  at java.lang.reflect.Method.invoke (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)
Caused by: java.lang.IllegalStateException: 
  at rekab.app.background_locator.IsolateHolderExtensionKt.startLocatorService (IsolateHolderExtensionKt.java)
  at rekab.app.background_locator.IsolateHolderService.onCreate (IsolateHolderService.java)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:3674)
  at android.app.ActivityThread.access$2000 (ActivityThread.java:218)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1801)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:145)
  at android.app.ActivityThread.main (ActivityThread.java:6914)
  at java.lang.reflect.Method.invoke (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)
```

**Comment by TahaTesser** [comment] 2021-02-15 06:54
Hi @marcoheine 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rekab-app/background_locator/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-02-15 06:54 UTC
Labels: in triage
