### ISSUE TITLE
The android app of the flutter shows the letter A P 4 and R with filled gaps in the typography. 

### ISSUE THREAD

**Issue by infinitysush** [flutter/flutter#112546] opened 2022-09-28 12:46 UTC
IOS app does not have this issue, and as well the fonts showed perfectly fine some time back
![Screenshot_20220928-144340](https://user-images.githubusercontent.com/44548333/192781934-a5b58d89-17aa-4823-9769-6334667857eb.jpg)

**Comment by danagbemava-nc** [comment] 2022-09-28 12:59
Hi @infinitysush,

Can you please provide your `flutter doctor -v`  and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Please also provide the fonts you're using and the device(s) you're experiencing this issue on. 


Thank you

**Comment by infinitysush** [comment] 2022-09-28 13:04
@danagbemava-nc 

Here is the flutter doctor:
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-DE)
    • Flutter version 3.0.5 at /Users/sushrut/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/sushrut/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (3 available)
    • ONEPLUS A5000 (mobile) • 6df5abd5 • android-arm64  • Android 10 (API 29)
    • macOS (desktop)        • macos    • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 500
        - asset: fonts/Inter-semiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700

Problem Device: OnePlus 5

I will create minimal reproducible code soon

**Comment by infinitysush** [comment] 2022-09-28 15:04
@danagbemava-nc :  Here you may find the files with minimum reproducible code that produces the issue https://github.com/infinitysush/flutterissue.  

The issue persists only on android and for fontweight >500.

**Comment by danagbemava-nc** [comment] 2022-09-29 07:03
Hi @infinitysush, you appear to be on an older version of flutter, can you upgrade to the latest version of flutter stable to see if you still experience the issue? 

If you do, please provide the updated output of `flutter doctor -v`. 

Thank you

**Comment by infinitysush** [comment] 2022-09-29 07:22
@danagbemava-nc : 

Flutter 3.3.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18a827f393 (14 hours ago) • 2022-09-28 10:03:14 -0700
Engine • revision 5c984c26eb
Tools • Dart 2.18.2 • DevTools 2.15.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.5 21G72 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
(base) sushrut@Sushruts-Air-2 drunkmonkey % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.5 21G72
    darwin-arm, locale en-DE)
    • Flutter version 3.3.3 on channel stable at
      /Users/sushrut/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (14 hours ago), 2022-09-28
      10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK
    version 31.0.0)
    • Android SDK at /Users/sushrut/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] Connected device (4 available)
    • ONEPLUS A5000 (mobile) • 6df5abd5
      • android-arm64  • Android 10 (API 29)
    • iPhone 11 (mobile)     •
      AE268246-8E57-4F64-BF73-39F4EE350832 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)        • macos
      • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)           • chrome
      • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by danagbemava-nc** [comment] 2022-09-29 08:12
Hi @infinitysush, is the OnePlus 5 the only device you're experiencing this issue on? 

I tried the sample you shared on a Pixel 4 Emulator but I was not able to reproduce the issue. 

<details>
<summary>screenshot</summary>

<img src="https://user-images.githubusercontent.com/88313112/192977259-5b13ac71-2975-44fa-ac02-690379250eb6.png" width="300"/>

**Comment by infinitysush** [comment] 2022-09-29 08:23
@danagbemava-nc : its a very strange glitch. It is only on my OnePlus5 debug build, it is not on iOS and as well in the Production launched on android 1 month back this did not exist. I wanted to push an update to android but without changing anything in fonts this is popping up on my device now all of a sudden. That is why I am clueless what to do

**Comment by danagbemava-nc** [comment] 2022-09-29 14:17
Hi @infinitysush, which version were you on where you did not have this bug? 

Also, can you check on the master channel if it reproduces there as well?

**Comment by jason-simmons** [comment] 2022-10-04 01:24
This is caused by the `Simplify` call in `SkScalerContext_FreeType_Base::generateGlyphPath` (see https://github.com/google/skia/commit/b3275e1fd64cbbf57a1e9a2ecb2db0812cfba4dc)

@bungeman

**Comment by bungeman** [comment] 2022-10-04 21:13
Taking a look with this font in Skia, I couldn't initially reproduce, but I think this is an issue with fake bolding, which would also explain why this happens staring at heavier font weights but not lighter. Interestingly the outlines look visually correct, which makes it even more odd that the stroke+fill of the fake bold would run into issues. Will investigate.

**Comment by bungeman** [comment] 2022-10-05 18:23
Yeah, this seems to be more a pre-existing issue with the stroker than anything else. The issue here is that

1. Simplify produces an even-odd fill SkPath.
2. The stroker produces a winding (non-zero) fill SkPath.
3. The even-odd fill SkPath is appended to the winding fill SkPath to produce the stroke+fill SkPath (which is winding).

As a result the even-odd path is rendered as winding and because the inside curve isn't in the proper direction this fills the whole area (the middle holes are in some sense covered twice instead of zero times). This hasn't been an issue before with text since generally fonts use a winding (non-zero) path and winding (non-zero) is the default type for SkPaths.

In theory the correct way to fix this is to fix the stroker in the stroke and fill case, but this case is deprecated and only used by this internal text stuff. As a result, I think the best way to fix this is to fix up the simplified path to winding.

Actually I'm somewhat surprised that we haven't seen this earlier, but I think that's due to the way the overlaps work in this particular font. Many even-odd paths would work out anyway if the inside contour happened to be compatible with being interpreted as winding.

**Comment by bungeman** [comment] 2022-10-05 18:53
I believe https://skia-review.googlesource.com/c/skia/+/587877 should fix this issue.

**Comment by Paul-cbt** [comment] 2022-10-06 13:20
@bungeman Hi, do you know how I can use this fix? Thanks

**Comment by infinitysush** [comment] 2022-10-06 20:37
> hanks

same here, would love to know how to use this version

**Comment by jason-simmons** [comment] 2022-10-06 23:52
The fix is now available on the Flutter master branch

**Comment by chinmaygarde** [comment] 2022-10-10 18:10
Closing as completed as the fix has landed on the `main`.

**Closed by chinmaygarde** 2022-10-10 18:10 UTC
Labels: engine, dependency: skia, a: typography, severe: rendering
