### ISSUE TITLE
cancel download of new flutter broke installation

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#50682] opened 2020-02-13 01:00 UTC
**Error:**
`/Users/aaclarke/dev/flutter/bin/flutter: line 46: /Users/aaclarke/dev/flutter/bin/cache/dart-sdk/bin/pub: No such file or directory`

**Steps to reproduce:**
1) Switch the flutter branch
1) Run a flutter command to start downloading
1) Cancel the download with Ctrl-C
1) Notice flutter no longer works.

There may be a timing issue related to when you press Ctrl-C.  I suspect we may be deleting something prematurely.  The code may say `Delete -> Download` versus `Download -> Delete -> Move`.

**Log:**
```
aaclarke-macbookpro2:flutter aaclarke$ git checkout v1.9.1+hotfix.6
Updating files: 100% (3381/3381), done.
Note: switching to 'v1.9.1+hotfix.6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 68587a091 V1.9.1 hotfix
aaclarke-macbookpro2:flutter aaclarke$ cd -
/Users/aaclarke/dev/flutter-examples/alert_webpage
aaclarke-macbookpro2:alert_webpage aaclarke$ flutter run
Downloading Dart SDK from Flutter engine b863200c37df4ed378042de11c4e9ff34e4e58c9...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  2  263M    2 7099k    0     0   327k      0  0:13:44  0:00:21  0:13:23  570k^C
aaclarke-macbookpro2:alert_webpage aaclarke$ cd ~/dev/flutter
aaclarke-macbookpro2:flutter aaclarke$ git checkout master
Previous HEAD position was 68587a091 V1.9.1 hotfix
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
aaclarke-macbookpro2:flutter aaclarke$ cd -
/Users/aaclarke/dev/flutter-examples/alert_webpage
aaclarke-macbookpro2:alert_webpage aaclarke$ flutter doctor -v
Building flutter tool...
/Users/aaclarke/dev/flutter/bin/flutter: line 46: /Users/aaclarke/dev/flutter/bin/cache/dart-sdk/bin/pub: No such file or directory
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
```

**Comment by gaaclarke** [comment] 2020-02-13 01:04
Executing `rm -rf ${FLUTTER_ROOT}bin/cache/` seems to unlock the error and for a redownload.

**Comment by jonahwilliams** [comment] 2020-02-15 20:34
Duplicate of https://github.com/flutter/flutter/issues/15552

**Closed by jonahwilliams** 2020-02-15 20:34 UTC
Labels: tool
