### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method currentUser on channel plugins.flutter.io/firebase_auth)

### ISSUE THREAD

**Issue by Stinox22** [flutter/flutter#57443] opened 2020-05-17 17:59 UTC
I'm facing this issue after upgrading Flutter to 1.17, it worked fine on 1.12.

```
E/flutter (15385): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method currentUser on channel plugins.flutter.io/firebase_auth)
E/flutter (15385): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (15385): <asynchronous suspension>
E/flutter (15385): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (15385): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:48)
E/flutter (15385): #3      MethodChannelFirebaseAuth.getCurrentUser (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:43:10)
E/flutter (15385): #4      FirebaseAuth.currentUser (package:firebase_auth/src/firebase_auth.dart:316:45)
```

And this Note as well
```bash
Note: C:\flutter-sdk\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

pubspec.yaml
```yaml
environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_database: ^3.1.3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  google_sign_in: ^4.0.4
  firebase_messaging: ^6.0.13
  http: ^0.12.1
```

Flutter Doctor
```console
C:\flutter-sdk\flutter\bin\flutter.bat doctor --verbose

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.836], locale en-IN)
    • Flutter version 1.17.1 at C:\flutter-sdk\flutter
    • Framework revision f7a6a7906b (5 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\xxxxx\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Nexus 5X • 01fxxxxxxxxd69 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
Process finished with exit code 0
```

Everything seemed to work perfectly fine before and I did not change any dependency after upgrading flutter. Kindly review this as let me know what's going wrong

**Comment by Abdusin** [comment] 2020-05-17 22:17
```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.gms:google-services:4.3.3'
    }
}
```
check  in android/build.gradle file , should be like this

**Comment by Stinox22** [comment] 2020-05-18 06:23
> ```
> buildscript {
>     repositories {
>         google()
>         jcenter()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.5.0'
>         classpath 'com.google.gms:google-services:4.3.3'
>     }
> }
> ```
> 
> check in android/build.gradle file , should be like this

Yes it is. Also I had it working perfectly earlier. The setup for firebase is done right. I had Authentication, Firestore and FCM working.
But its not working after the update. I even tried `master` channel, but no luck.

**Comment by Qualcuno** [comment] 2020-05-18 08:26
Very similar problem with MissingPluginException(No implementation found for method currentUser on channel plugins.flutter.io/firebase_core) after upgraded form 1.12.13+hotfix9 to 1.17.1 on stable channel.

**Comment by Abdusin** [comment] 2020-05-18 14:03
did u try
```
flutter clean
flutter packages get
```

**Comment by iapicca** [comment] 2020-05-18 14:13
Hi @Stinox22 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-05-18 14:13 UTC

**Comment by Stinox22** [comment] 2020-05-18 16:07
> Very similar problem with MissingPluginException(No implementation found for method currentUser on channel plugins.flutter.io/firebase_core) after upgraded form 1.12.13+hotfix9 to 1.17.1 on stable channel. I fixed with this solution [#56548 (comment)](https://github.com/flutter/flutter/issues/56548#issuecomment-625239992)

This solution worked perfectly. Finally! Although they should've updated the documentation with these changes or is it a workaround? idk.

**Comment by yoman07** [comment] 2020-05-26 13:04
I have the same problem on iOS. Any solution for that? It doesn't work on 1.17.1 either

**Comment by GNVageesh** [comment] 2020-10-17 15:29
i had got the same error
i resolved it.
make sure u have enabled the way u want to authenticate the users.
I had not enabled signing using email and password so this error came, and now when I enabled them it is working fine
