### ISSUE TITLE
[local_auth] Application crashes on  Android 8.1

### ISSUE THREAD

**Issue by EunyoungY** [flutter/flutter#85536] opened 2021-06-29 13:27 UTC
I tried to apply the local_auth plugin. It works well on emulator.
However, It doesn't work on the actual devices. I've tried 3 devices which are Android 7.0, Android 8.1, Android 9.
When I try to run _authenticate or _authenticateWithBiometrics, It just crashed.

<img src="https://user-images.githubusercontent.com/43934072/123804950-a1b75d00-d928-11eb-981f-635360c51e14.png" height="450" />	|

 
[Code]

<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final LocalAuthentication auth = LocalAuthentication();
  _SupportState _supportState = _SupportState.unknown;
  bool? _canCheckBiometrics;
  List<BiometricType>? _availableBiometrics;
  String _authorized = 'Not Authorized';
  bool _isAuthenticating = false;

  @override
  void initState() {
    super.initState();
    auth.isDeviceSupported().then(
          (isSupported) => setState(() => _supportState = isSupported
          ? _SupportState.supported
          : _SupportState.unsupported),
    );
  }

  Future<void> _checkBiometrics() async {
    late bool canCheckBiometrics;
    try {
      canCheckBiometrics = await auth.canCheckBiometrics;
    } on PlatformException catch (e) {
      canCheckBiometrics = false;
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _canCheckBiometrics = canCheckBiometrics;
    });
  }

  Future<void> _getAvailableBiometrics() async {
    late List<BiometricType> availableBiometrics;
    try {
      availableBiometrics = await auth.getAvailableBiometrics();
    } on PlatformException catch (e) {
      availableBiometrics = <BiometricType>[];
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _availableBiometrics = availableBiometrics;
    });
  }

  Future<void> _authenticate() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticate(
          localizedReason: 'Let OS determine authentication method',
          useErrorDialogs: true,
          stickyAuth: true);
      setState(() {
        _isAuthenticating = false;
      });
    } on PlatformException catch (e) {
      print(e);
      setState(() {
        _isAuthenticating = false;
        _authorized = "Error - ${e.message}";
      });
      return;
    }
    if (!mounted) return;

    setState(
            () => _authorized = authenticated ? 'Authorized' : 'Not Authorized');
  }

  Future<void> _authenticateWithBiometrics() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticate(
          localizedReason:
          'Scan your fingerprint (or face or whatever) to authenticate',
          useErrorDialogs: true,
          stickyAuth: true,
          biometricOnly: true);
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Authenticating';
      });
    } on PlatformException catch (e) {
      print(e);
      setState(() {
        _isAuthenticating = false;
        _authorized = "Error - ${e.message}";
      });
      return;
    }
    if (!mounted) return;

    final String message = authenticated ? 'Authorized' : 'Not Authorized';
    setState(() {
      _authorized = message;
    });
  }

  void _cancelAuthentication() async {
    await auth.stopAuthentication();
    setState(() => _isAuthenticating = false);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: ListView(
          padding: const EdgeInsets.only(top: 30),
          children: [
            Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                if (_supportState == _SupportState.unknown)
                  CircularProgressIndicator()
                else if (_supportState == _SupportState.supported)
                  Text("This device is supported")
                else
                  Text("This device is not supported"),
                Divider(height: 100),
                Text('Can check biometrics: $_canCheckBiometrics\n'),
                ElevatedButton(
                  child: const Text('Check biometrics'),
                  onPressed: _checkBiometrics,
                ),
                Divider(height: 100),
                Text('Available biometrics: $_availableBiometrics\n'),
                ElevatedButton(
                  child: const Text('Get available biometrics'),
                  onPressed: _getAvailableBiometrics,
                ),
                Divider(height: 100),
                Text('Current State: $_authorized\n'),
                (_isAuthenticating)
                    ? ElevatedButton(
                  onPressed: _cancelAuthentication,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text("Cancel Authentication"),
                      Icon(Icons.cancel),
                    ],
                  ),
                )
                    : Column(
                  children: [
                    ElevatedButton(
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text('Authenticate'),
                          Icon(Icons.perm_device_information),
                        ],
                      ),
                      onPressed: _authenticate,
                    ),
                    ElevatedButton(
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text(_isAuthenticating
                              ? 'Cancel'
                              : 'Authenticate: biometrics only'),
                          Icon(Icons.fingerprint),
                        ],
                      ),
                      onPressed: _authenticateWithBiometrics,
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

enum _SupportState {
  unknown,
  supported,
  unsupported,
}

``` 

</details>

[Log]

<details> 
<summary>logs</summary> 
	
```console
D/BezellessGripSuppressionFilter(25599): getdisplaysize, x : 1080 y : 2340
I/Timeline(25599): Timeline: Activity_idle id: android.os.BinderProxy@8cdb70c time:12507830
I/zygote64(25599): Do full code cache collection, code=124KB, data=89KB
I/zygote64(25599): After code cache collection, code=106KB, data=69KB
I/ViewRootImpl(25599): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(25599): ViewRoot's Touch Event : ACTION_UP
I/ViewRootImpl(25599): ViewRoot's Touch Event : ACTION_DOWN
I/zygote64(25599): Do partial code cache collection, code=123KB, data=88KB
I/zygote64(25599): After code cache collection, code=123KB, data=88KB
I/zygote64(25599): Increasing code cache capacity to 512KB
I/ViewRootImpl(25599): ViewRoot's Touch Event : ACTION_UP
W/ResourceType(25599): Invalid package identifier when getting bag for resource number 0x00000311
D/AndroidRuntime(25599): Shutting down VM
E/AndroidRuntime(25599): FATAL EXCEPTION: main
E/AndroidRuntime(25599): Process: com.swfact.qale, PID: 25599
E/AndroidRuntime(25599): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(25599): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
E/AndroidRuntime(25599): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
E/AndroidRuntime(25599): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
E/AndroidRuntime(25599): 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
E/AndroidRuntime(25599): 	at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
E/AndroidRuntime(25599): 	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
E/AndroidRuntime(25599): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:480)
E/AndroidRuntime(25599): 	at android.app.Dialog.show(Dialog.java:379)
E/AndroidRuntime(25599): 	at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:691)
E/AndroidRuntime(25599): 	at androidx.fragment.app.Fragment.performStart(Fragment.java:3021)
E/AndroidRuntime(25599): 	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
E/AndroidRuntime(25599): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
E/AndroidRuntime(25599): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime(25599): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime(25599): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
E/AndroidRuntime(25599): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
E/AndroidRuntime(25599): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(25599): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25599): 	at android.os.Looper.loop(Looper.java:175)
E/AndroidRuntime(25599): 	at android.app.ActivityThread.main(ActivityThread.java:6724)
E/AndroidRuntime(25599): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25599): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(25599): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
Lost connection to device.
```

</details>

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.1.0-13.0.pre.104, on Mac OS X 10.15.7 19H2 darwin-x64, locale ko-KR)
    • Flutter version 2.1.0-13.0.pre.104 at /Users/eunyoung/developer/flutter
    • Framework revision 5be3f215ed (4 months ago), 2021-03-16 08:35:00 +0100
    • Engine revision 20375cebcf
    • Dart version 2.13.0 (build 2.13.0-137.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eunyoung/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • LM Q925L (mobile) • LMQ925L1913f711 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome (web)      • chrome          • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-06-29 14:21
Hi @EunyoungY
Looks like you're a 4 months old Fltutter channel

Can you please upgrade to the latest  `stable` and try the latest `local_auth: ^1.1.6` try again
Execute the following commands to upgrade
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`


If the problem persists, please provide the device details

**Comment by EunyoungY** [comment] 2021-06-30 00:23
Thank you for your help.

1. I tried local_auth: ^1.1.6
2. and I am using multi-sdk, so I changed the Flutter SDK path to 2.2.2

BUT It still doesn't work.

![image](https://user-images.githubusercontent.com/43934072/123883820-b6294300-d984-11eb-8998-00cc1d003fe5.png)

**Comment by EunyoungY** [comment] 2021-06-30 00:41
I add this line to AndroidManifest.xml, and It works!!
It says 'USE_FINGERPRINT' is deprecated so I comment on this line.
However, when I uncomment this, It runs well!!!
  <uses-permission android:name="android.permission.USE_FINGERPRINT"/> 

Thank you so much :) Have a good day!!

**Comment by EunyoungY** [comment] 2021-06-30 01:45
Oh.. It worked one time, and it crashed again...

**Comment by TahaTesser** [comment] 2021-06-30 10:22
Hi @EunyoungY 
To be sure it is a  project issue, can you please clone ` git clone https://github.com/flutter/plugins.git` and run the [example ](https://github.com/flutter/plugins/tree/master/packages/local_auth/example) locally from the cloned repository?

**Comment by destbest94** [comment] 2021-07-02 05:13
I have the same problem. Your example also crashed https://github.com/flutter/plugins/tree/master/packages/local_auth/example

**Comment by EunyoungY** [comment] 2021-07-06 08:45
In my project, only Android Version: 8.1.0 crashed(Model number: LM-A925L) while it works well on Android 7.0.
However, your example works well on Android 7.0, Android 8.1, Android 9.

Thanks for your help!

**Comment by EunyoungY** [comment] 2021-07-07 02:32
![image](https://user-images.githubusercontent.com/43934072/124691263-8515b900-df16-11eb-9366-e6c5a0f9a2f5.png)

I followed Android Integration.
I updated MainActivity.kt and AndroidManifest.xml.
However, It still doesn't work on the device which is Android Version: 8.1.0.
Do you think It's because of "USE_FINGERPRINT' is deprecated"?

**Comment by hosamcr7** [comment] 2021-07-08 18:18
Same problem. 
Any solutions?

**Comment by JovanyOlmos** [comment] 2021-08-12 19:55
I have the same problem. I've tried to change AndroidManifiest.xml, and MainActivity.kt but it doesn't works.

**Comment by REKURDennis** [comment] 2021-08-16 13:21
I just received a bug report for my app, reporting a crash after the authentication has been activated. The user uses Android 8.0 . So does anybody have an idea, how to fix the problem?

**Comment by abreudiego94** [comment] 2021-08-24 00:11
same bug here

**Comment by ManuLpz4** [comment] 2021-08-24 14:42
Any update on it? I'm trying all to solve it

**Comment by Snehal-Singh174** [comment] 2021-08-31 10:58
Refer this to solve your issue.

https://gist.github.com/akifarhan/f70a2c777651f2ea61a15eb92a5939c1

**Comment by ManuLpz4** [comment] 2021-09-11 06:16
@Snehal-Singh174 do you know if the AppCompat fix affects another functionality present or future?

**Comment by alexeenko-frontend** [comment] 2021-09-13 12:05
I have the same problem on simulator ios 14.5

**Comment by dazziman** [comment] 2021-09-29 07:50
USE_FINGERPRINT  => USE_BIOMETRIC

**Comment by TahaTesser** [comment] 2021-09-29 09:58
@alexeenko-frontend
Your issue is unlikely to be same, please file a new issue with all the details

**Comment by adminant** [comment] 2022-01-10 07:54
Unfortunately AppCompat theme fix didn't help, the app still keeps crashing on Android 7.0 and 8.1 devices, while working ok on simulator. Any ideas?

**Comment by prohunterallen** [comment] 2022-01-12 08:08
Hi guys, I have the same problem here
I user Samsung A7 2017 android V8.0.0
My App crash and exit 
I try to debug and found app will crash when call  localAuth.authenticate   (Class LocalAuthentication fuction authenticate)

I have use try catch but is not catch any error. App has force exit when call localAuth.authenticate

Any update or suggestion ?

**Comment by stuartmorgan** [comment] 2023-05-01 12:15
Closing as the cause of the original crash that was reported here is now clearly documented: https://pub.dev/packages/local_auth#android-theme

Anyone who still has a crash after following all of the readme instructions should file a new issue with details, including the crash log, as it would have a different cause.

**Closed by stuartmorgan** 2023-05-01 12:15 UTC
Labels: e: device-specific, platform-android, plugin, p: local_auth, passed first triage, P4, severe: fatal crash
