### ISSUE TITLE
IOS (only on few devices) - flutter: Unauthenticated#0 HttpsCallable.call

### ISSUE THREAD

**Issue by rahulkumar26** [flutter/flutter#47689] opened 2019-12-23 18:39 UTC
Android is all working fine. however, not sure what's causing this issue on few IOS devices (FYI - some IOS devices working fine). Any help would be appreciated.

## Quick note
Firebase functions using Node 8 engine

## onCall script from app
ces2020/stores/login/loginStore.dart
await callable.call(<String, dynamic>{'email': '${email}'}); : line 40
```
Future<bool> validateUserEmail(String email, BuildContext context, Function completion) async{
    Dialogs.showLoadingDialog(context, _keyLoader);
    loading = true;
    try {
      final HttpsCallable callable = CloudFunctions.instance.getHttpsCallable(
        functionName: 'getUserByEmailOnCall',
      );
      final HttpsCallableResult resp =
      await callable.call(<String, dynamic>{'email': '${email}'});
      Map<String, dynamic> data = jsonDecode(resp.data);

      loginResponse = LoginResult.fromMap(data);
      loading = false;
      Navigator.of(_keyLoader.currentContext, rootNavigator: true).pop();
      if (loginResponse.result.data.isEmpty) {
        success = false;
        errorStore.errorMessage = loginResponse.result.message;
        errorStore.showError = true;
        Dialogs.showPopUp(context, "User Not Found, please Register to login.");
        return false;
      } else {
        print("user validated successfully");
        final _appStateStore = Provider.of<AppStateStore>(
            context, listen: false);
        _appStateStore.userEmaiID = email;
        completion();
        return true;
      }
    }
    on CloudFunctionsException catch (e, s) {
      loading = false;
      success = false;
      Navigator.of(_keyLoader.currentContext, rootNavigator: true).pop();
      print(e.message + s.toString());
      errorStore.errorMessage = "Registration failed with error";
      Dialogs.showPopUp(context,"Server unreachable.");
    }
  }
```

**Target Platform:** Iphone
**Target OS version/browser:** 10 >
**Devices:** 11

## error

```
flutter: Unauthenticated#0      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:48:9)
<asynchronous suspension>
#1      _LoginStore.validateUserEmail (package:ces2020/stores/login/loginStore.dart:40:22)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#3      _LoginStore.validateUserEmail (package:ces2020/stores/login/loginStore.dart:32:33)
#4      _LoginPage._signInButtonTapped (package:ces2020/ui/login/userLogin.dart:194:19)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
#10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#22     _rootRunUnary (dart:async/zone.dart:1138:13)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#25     _invoke1 (dart:ui/hooks.dart:273:10)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
```

**Comment by rahulkumar26** [comment] 2019-12-23 18:57
my bad - closing this and opening in firebase.

**Comment by rahulkumar26** [comment] 2019-12-23 19:43
Oops, looks like firebase suggested to open in Flutter :)

**Comment by iapicca** [comment] 2019-12-24 14:26
Hi @rahulkumar26 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-12-24 14:26 UTC
