### ISSUE TITLE
google_maps_flutter library "myLocationEnabled" blue dot is displayed in the wrong place in China 

### ISSUE THREAD

**Issue by JettChen12** [flutter/flutter#124576] opened 2023-04-11 08:24 UTC
## Discription
As far as I know, Google Maps uses the GCJ-02 in China and WGS84 in most other places. Therefore, I speculate that when mylocationEnabled is true, Google Maps will obtain the current location of the device, which may be in WGS84 format and has not been converted to the GCJ-02, leading to the error in the display of the blue dot.
## Steps to Reproduce

1. Using the google_maps_flutter plugin on an Android device located in China.
2. Set myLocationEnabled true.
3. Open the map and tap "mylocation" button to move to my location.

**Expected results:** 
The blue dot should appear at my location

**Actual results:** 
The blue dot is displayed in the wrong place.
<details>
<summary>Code sample</summary>

```dart
Scaffold(
      body: GoogleMap(
        mapType: MapType.hybrid,
        myLocationEnabled: true,
        initialCameraPosition: CameraPosition(target: LatLng(widget.position.latitude, widget.position.longitude), zoom: 14.4746),
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
        },
      )
    );
```

</details>

<details>
  <summary>Logs</summary>

```
no error logs
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.11-0.0.pre.2, on Microsoft Windows [版本 10.0.19044.2728], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)
[√] Android Studio (version 2021.3)
[√] IntelliJ IDEA Community Edition (version 2020.1)
[√] VS Code (version 1.76.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

```

</details>

**Comment by exaby73** [comment] 2023-04-11 08:37
Hello @JettChen12. Is this issue reproducible with a native android project? Or can it only be reproduced with Flutter and the `google_maps_flutter` plugin?

**Comment by exaby73** [comment] 2023-04-12 09:33
From what I can see on https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China, this affects Google Maps as a whole, not just `google_maps_flutter`

> A marker with GCJ-02 coordinates will be displayed at the correct location on a GCJ-02 map. However, the offsets can result in a 100–700 meter error from the actual location if a WGS-84 marker (such as a GPS location) is placed on a GCJ-02 map, or vice versa. The [Google Maps](https://en.wikipedia.org/wiki/Google_Maps) street map is offset by 50–500 meters from its satellite imagery.[[11]](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#cite_note-motherboard-11)[[25]](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#cite_note-25) [Yahoo! Maps](https://en.wikipedia.org/wiki/Yahoo!_Maps) also displayed the street map without major errors when compared to the satellite imagery.[[26]](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#cite_note-yahoo-map-26) MapQuest overlays OpenStreetMap data perfectly as well.[[27]](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#cite_note-27)

**Comment by JettChen12** [comment] 2023-04-13 06:26
> From what I can see on https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China, this affects Google Maps as a whole, not just `google_maps_flutter`
> 
> > A marker with GCJ-02 coordinates will be displayed at the correct location on a GCJ-02 map. However, the offsets can result in a 100–700 meter error from the actual location if a WGS-84 marker (such as a GPS location) is placed on a GCJ-02 map, or vice versa. The [Google Maps](https://en.wikipedia.org/wiki/Google_Maps) street map is offset by 50–500 meters from its satellite imagery.[[11]](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#cite_note-motherboard-11)[[25]](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#cite_note-25) [Yahoo! Maps](https://en.wikipedia.org/wiki/Yahoo!_Maps) also displayed the street map without major errors when compared to the satellite imagery.[[26]](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#cite_note-yahoo-map-26) MapQuest overlays OpenStreetMap data perfectly as well.[[27]](https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#cite_note-27)

Thank you for your response. I understand that the issue with the blue dot being displayed in the wrong place is not specific to google_maps_flutter and affects Google Maps as a whole due to the restrictions on geographic data in China. However, I believe it would still be helpful if the google_maps_flutter library could provide some guidance or workaround for developers who are facing this issue. As you mentioned, a marker with GCJ-02 coordinates will be displayed at the correct location on a GCJ-02 map. Would it be possible for the library to provide support for GCJ-02 coordinates or to convert the coordinates to GCJ-02 before displaying the blue dot? This would be especially helpful for developers who are not familiar with the geographic data restrictions in China and may not know how to convert their coordinates.

Thank you for your time and assistance in this matter.

**Comment by exaby73** [comment] 2023-04-14 07:19
According to Wikipedia, there is a licensing fee associated with the use of this algorithm. Unfortunately, this is out of scope for `google_maps_flutter` as ultimately it's an issue with Google Maps itself, and `google_maps_flutter` is just a plugin allowing you to use it. This question is better asked on sites like Stackoverflow. You may also find resources on https://flutter.dev/community. Due to the specified reasons, I will close this issue. Thank you

**Closed by exaby73** 2023-04-14 07:19 UTC
Labels: in triage
