### ISSUE TITLE
StatelessWidget.build be call again when I click the first TextField in page

### ISSUE THREAD

**Issue by sxd1140** [flutter/flutter#19242] opened 2018-07-11 02:43 UTC
```dart
import 'dart:math';

import 'package:flutter/material.dart';

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('build page1');
    return Scaffold(
      appBar: AppBar(
        title: Text('Math'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: ListView.builder(
          shrinkWrap: true,
          itemCount: 50,
          itemBuilder: (BuildContext context, int index) {
            if (index.isOdd) return Divider();
            final random = new Random();
            final number1 = random.nextInt(10);
            final number2 = random.nextInt(10);
            return Center(
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Text('$number1'),
                  Icon(Icons.add),
                  Text('$number2'),
                  Icon(Icons.drag_handle),
                  Flexible(
                    child: TextField(),
                  )
                ],
              ),
            );
          },
        ),
      ),
    );
  }
}
```

Use 
```dart 
Navigator.push(context,MaterialPageRoute(builder: (context)=>Page1()));
```

The `Page1.build` method be call again when i click any `TextField`.

Then click another `TextField` everything is ok.

If show `Page1` directly not use Navigator, it's have not this issue when I click the `TextField`.

### Logs
```
flutter: build page1
------------------------ click the first TextField
flutter: build page1
------------------------ click other TextField, print no more
```

### flutter doctor -v
```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.5 17F77, locale zh-Hans-CN)
    • Flutter version 0.5.1 at /Users/sxd/libs/flutter
    • Framework revision c7ea3ca377 (6 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0-rc2)
    • Android SDK at /Users/sxd/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0-rc2
    • ANDROID_HOME = /Users/sxd/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 25.0.2
    • Dart plugin version 181.4445.29

[!] VS Code (version 1.25.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • iPhone 7 • E8BD0EB5-4FBA-458F-B223-4326E75F39C7 • ios • iOS 11.4 (simulator)
```

**Comment by jonahwilliams** [comment] 2018-07-11 03:07
This is working as intended, you should assume that flutter may call build as often as it wants to and anything less is an optimization.  If you are trying to preserve the random numbers or any other state you have to use a StatefulWidget.

**Comment by zoechi** [comment] 2018-07-11 07:50
I guess tapping the first text field brings up the keyboard which changes the layout constraints and requires a rebuild to update the UI.

**Comment by sxd1140** [comment] 2018-07-12 02:40
```
void main() => runApp(MaterialApp(
  home:Page1()
));
```
Not use Navigator, no call `build` twice.

**Comment by zoechi** [comment] 2018-09-01 10:55
@sdlu1992 what do you mean with "problem"?
This is how Flutter works.

**Comment by zoechi** [comment] 2018-09-01 10:55
Closing as working as intended.

**Closed by zoechi** 2018-09-01 10:55 UTC
