### ISSUE TITLE
Flutter WEB PWA - Missing Text Bug.

### ISSUE THREAD

**Issue by kaumudpa** [flutter/flutter#65339] opened 2020-09-07 11:52 UTC
This is one of the weirdest Bug i am reporting. A flutter web PWA hosted on firebase hosting misses some texts running on Android device. Note : **Only the Android PWA misses some texts** the site if used through chrome works perfectly fine and the PWA works fine on desktops/laptops as well.

This issue is not seen if the `flutter build web --release` is done with flutter version `1.19.0-4.3.pre` all the flutter versions after `1.19.0-4.3.pre` has this issue.

An Example  relevant block in my code:
```
       color: ColorUtils.screenBackgroundColor,
                  height: Utility.getH(0.05, context),
                  width: Utility.getW(1, context),
                  child: HoverCursor(
                    cursor: Cursor.grab,
                    child: new Center(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: GestureDetector(
                            onTap: () {
                              setState(() {
                                showRights = true;
                              });
                              _controllerScale.forward().whenComplete(() => () {
                                    print("Opened");
                                  });
                            },
                            child: HoverCursor(
                              cursor: Cursor.pointer,
                              child: new AutoSizeText(
                                "Rules & Regulations \u00a9 2016-2020",
                                style: GoogleFonts.lato(
                                    color: Colors.white70,
                                    fontStyle: FontStyle.normal),
                              ),
                            )),
                      ),
                    ),
                  ),
                )
```

View of PWA build with `1.19.0-4.3.pre`

![Screenshot_20200907-164017__01](https://user-images.githubusercontent.com/13520180/92384704-2d5bc500-f12e-11ea-865b-eba503970398.jpg)

View of PWA build even with current master/dev channel.

![Screenshot_20200907-165656__01](https://user-images.githubusercontent.com/13520180/92384789-57ad8280-f12e-11ea-9860-09d953dc975e.jpg)

This issue is persistent across the app.

**Comment by TahaTesser** [comment] 2020-09-07 14:35
Hi @kaumudpa 
I see there's an open issue addressing the case you described. https://github.com/flutter/flutter/issues/65099
Please follow up on that issue and provide more details, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-07 14:35 UTC

**Comment by kaumudpa** [comment] 2020-09-07 14:38
I would request the flutter to understand the issue instead of just closing the issues in a hurry. Kindly reopen this issue.
The issue i just posted is totally different from #65099 as this happens with texts without "-" as well

**Comment by Nash0x7E2** [comment] 2020-09-07 14:39
Hi @kaumudpa, as a temporary workaround, you can use `flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true` when building your project. This solved the issue for me.

**Comment by Nash0x7E2** [comment] 2020-09-07 14:39
Since both bugs are closely related, I think it would make sense to track them from a single issue. @kaumudpa

**Comment by kaumudpa** [comment] 2020-09-07 14:40
> Hi @kaumudpa, as a temporary workaround, you can use `flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true` when building your project. This solved the issue for me.

@Nash0x7E2 Did you face this issue in PWA?

**Comment by Nash0x7E2** [comment] 2020-09-07 14:40
Yes.

**Comment by kaumudpa** [comment] 2020-09-07 15:02
> Hi @kaumudpa, as a temporary workaround, you can use `flutter run --release --dart-define=FLUTTER_WEB_USE_SKIA=true` when building your project. This solved the issue for me.


@Nash0x7E2 
I conform that this workaround works. Thank You.

**Comment by mdebbar** [comment] 2020-09-10 21:54
@kaumudpa this issue has the same root cause as https://github.com/flutter/flutter/issues/65099 like @TahaTesser mentioned.

**Comment by Tom1380** [comment] 2020-10-08 19:41
That workaround makes the text look grainier.
