### ISSUE TITLE
Cannot connect to VM service, process launch fails: failed to get the task for process <pid>

### ISSUE THREAD

**Issue by shockoe-hatch** [flutter/flutter#49361] opened 2020-01-23 18:15 UTC
After a flutter upgrade I am unable to build to an ios device.  Ios sim, Android device and android emulator work fine.  I can build the prod files fine as well so a `flutter build ios -t "main_release.dart" --release` works fine.  I have tried three separate versions of xcode (10.2.1, 10.3.0, 11.3) and still no luck. I am not getting a specific error that is helping me debug this.  
From Xcode I get this: 
`2020-01-23 11:54:59.068707-0500 Runner[1008:1249910] [VERBOSE-2:ptrace_ios.cc(66)] Could not call ptrace(PT_TRACE_ME): Operation not permitted`

From flutter run ios -t "lib/main_dev.dart" I get an unhelpful stack trace:
```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/caleb/Documents/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)```
```
Have also tried changing flutter channel to dev, master, and stable. 

flutter doctor -v 
```
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/caleb/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/caleb/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode11_3.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2018.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Have also tried reverting to the previous version of flutter I was on (1.2.1) and reverting any code changes I had made for the upgrade and was getting some separate issues. Any insight is greatly appreciated thanks.

**Comment by dnfield** [comment] 2020-01-24 09:18
Can you share what version of iOS your device is on?

/cc @sjindel-google @chinmaygarde  - this was likely introduced by https://github.com/flutter/engine/pull/10186

**Comment by dnfield** [comment] 2020-01-24 09:20
Also, can you share the result of `flutter run -v`?

**Comment by shockoe-hatch** [comment] 2020-01-24 14:12
@dnfield The two devices I was trying were on 13.3 and 13.2.2.  The entire response is quite long but here the end of it.  
[flutter_debug.zip](https://github.com/flutter/flutter/files/4108829/flutter_debug.zip)

**Comment by dnfield** [comment] 2020-01-24 17:43
See this part of your log:

```
                                   Compiler message:
                        [   +1 ms] package:catalog_flutter/main.dart: Error: No 'main' method
found.
                        [        ] Try adding a method named 'main' to your program.
                        [  +45 ms] Persisting file store
                        [   +2 ms] Done persisting file store
                        [   +1 ms] Target kernel_snapshot failed: Exception: Errors during snapshot
```

You're missing a main method in your main.dart.

Did the tool fail to print this output when running outside of verbose mode?

/cc @jonahwilliams

**Comment by dnfield** [comment] 2020-01-24 17:45
Possibly related: #49415

**Comment by dnfield** [comment] 2020-01-24 17:46
Also @zanderso @jonahwilliams this is making me think we should filter out most of the stack trace when the tool is not run in verbose mode.  Will file a separate issue.

**Comment by dnfield** [comment] 2020-01-24 17:49
Although I cannot reproduce this locally - if I remove my main method in a sample project, I get the expected output on iOS and Android (but not macOS).  I do not get the full toolExit stack trace outside of verbose mode.

**Comment by shockoe-hatch** [comment] 2020-01-24 18:17
@dnfield That was running the command you requested with just flutter run without a target.  We have two separate main files for different env.  The stack trace in the initial post is the response from the  `flutter run ios -t "lib/main_dev.dart" --verbose`

**Comment by dnfield** [comment] 2020-01-24 18:41
Ahh sorry about that.

Please paste in the full output of `flutter run ios -t "lib/main_dev.dart" --verbose` :)

**Comment by shockoe-hatch** [comment] 2020-01-24 20:27
@dnfield here ya go. 
[verbose_output.zip](https://github.com/flutter/flutter/files/4110533/verbose_output.zip)

**Comment by dnfield** [comment] 2020-01-24 20:38
Can you try opening your project in Xcode and running it from Xcode?

It's crashing before Flutter Tool can make a connection to it.  Xcode will likely give you a better idea of where it's crashing.

**Comment by dnfield** [comment] 2020-01-24 20:38
Also - is it possible to share a small project that reproduces this issue?

**Comment by shockoe-hatch** [comment] 2020-01-24 21:19
Xcode was giving me this `2020-01-23 11:54:59.068707-0500 Runner[1008:1249910] [VERBOSE-2:ptrace_ios.cc(66)] Could not call ptrace(PT_TRACE_ME): Operation not permitted`  But yes I will try to get a base case project to reproduce the issue.

**Comment by shockoe-hatch** [comment] 2020-01-27 14:35
@dnfield I have created a base project that recreates a very similar issue.  Unfortunately wasn't able to add this project as the file is too large.  But I really didn't modify the project much.  I created a new flutter project.  Added these to the pubspec:

```
dev_dependencies:
  barcode_scan_fix: ^1.0.2
  flutter_test:
    sdk: flutter
  meta: ^1.1.2
  sqflite: ^1.2.0
  cupertino_icons: ^0.1.0
  font_awesome_flutter: ^8.4.0
  url_launcher: ^5.0.1
  path_provider: ^1.5.1
  http: ^0.11.3+16
  flutter_secure_storage: ^3.3.1+1
  connectivity: ^0.4.6+2
  cached_network_image: ^2.0.0
  package_info: ^0.3.0
  shared_preferences: ^0.5.6
  photo_view: ^0.9.1
  firebase_core: ^0.4.3+2
  firebase_analytics: ^5.0.9
  firebase_remote_config: ^0.3.0+1
``` 
And added a GoogleService-Info plist file for the project so firebase wouldn't error out and got a stack trace error from flutter run --verbose.  I have attached the output. 

[flutter_output.zip](https://github.com/flutter/flutter/files/4117570/flutter_output.zip)

**Comment by JeronimoRepetto** [comment] 2020-01-29 05:16
Same error here..
Its so sad  :,(

**xcode error:**
2020-01-29 02:07:10.945016-0300 Runner[405:61451] [VERBOSE-2:ptrace_ios.cc(66)] Could not call ptrace(PT_TRACE_ME): Operation not permitted

**flutter doctor -v :**
[✓] Flutter (Channel master, v1.14.7-pre.3, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.14.7-pre.3 at /Users/XXX/Downloads/flutter
    • Framework revision 3bd4c69fd8 (11 hours ago), 2020-01-28 10:14:08 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (2 available)
    • iPhone de XXX • .... • ios • iOS 12.4.2
    • iPhone 11 Pro     • 0AA9CEAD-9240-4982-A7F9-D54D3149106E     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!

**Comment by sanalkv** [comment] 2020-02-04 11:02
facing the same issue , running perfectly fine on the emulator but getting the below issue while trying to run it on a physical device.

2020-03-06 04:07:14.297322+0530 Runner[634:51660] [VERBOSE-2:ptrace_ios.cc(66)] Could not call ptrace(PT_TRACE_ME): Operation not permitted
2020-03-06 04:07:14.300636+0530 Runner[634:51660] Metal API Validation Enabled

Xcode : Version 11.0 beta 6 (11M392r)

**Comment by ronaldmaymone** [comment] 2020-02-06 14:19
> facing the same issue , running perfectly fine on the emulator but getting the below issue while trying to run it on a physical device.
> 
> 2020-03-06 04:07:14.297322+0530 Runner[634:51660] [VERBOSE-2:ptrace_ios.cc(66)] Could not call ptrace(PT_TRACE_ME): Operation not permitted
> 2020-03-06 04:07:14.300636+0530 Runner[634:51660] Metal API Validation Enabled
> 
> Xcode : Version 11.0 beta 6 (11M392r)
> 
> UPDATE : checking Automatically manage signing in Xcode fixed the issue for me.

I was facing the same issue after running flutter upgrade and then downgrading(trace_ios.cc(66)).
Checking Automatically manage signing worked! But for release I needed to uncheck and use my. created signing profiles. Thx.

**Comment by sjindel-google** [comment] 2020-02-06 14:27
The error:

```
Could not call ptrace(PT_TRACE_ME): Operation not permitted
``` 

Is harmless if you are running from Xcode or `flutter run` on the command line. That warning is only important if you see if when launching the app from the home-screen.

However, we try to hide it when running from Xcode and `flutter run`, so if you're seeing it there, it's still a bug, but should not lead to a crash.

**Comment by ronaldmaymone** [comment] 2020-02-06 14:33
> The error:
> 
> ```
> Could not call ptrace(PT_TRACE_ME): Operation not permitted
> ```
> 
> Is harmless if you are running from Xcode or `flutter run` on the command line. That warning is only important if you see if when launching the app from the home-screen.
> 
> However, we try to hide it when running from Xcode and `flutter run`, so if you're seeing it there, it's still a bug, but should not lead to a crash.

What happened is that my app crashed when running with Xcode and this was the output. Just connected the dots, don't know anything further on this issue.

**Comment by sjindel-google** [comment] 2020-02-06 14:35
@ronaldmaymone Can you please try this:

Open Xcode
Go to Window -> Devices and Simulators
Select your iPhone

Do you see any crash reports with a timestamp from right after you saw the crash?

**Comment by jmagman** [comment] 2020-04-08 18:02
1. Failure of tooling to report crashes is tracked in https://github.com/flutter/flutter/issues/22536, made much worse by not getting logging from iOS 13 before VM connection (which doesn't happen on a crash) https://github.com/flutter/flutter/issues/44717
1. https://github.com/flutter/flutter/issues/49361#issuecomment-582929849 `Could not call ptrace(PT_TRACE_ME): Operation not permitted` sounds like a harmless warning.  Just because you see this warning does not mean you are hitting the same crash as the originator.  If you see this warning, please file a new issue, completely fill out the template, and include the crash log matching the timestamp from Xcode > Window > Devices and Simulators > View Device Logs
1. This particular crash isn't possible to track down without a crash log.  If we can get a crash log the engine team can take a look.  If we can't, then we can close this in favor of the "Flutter tool doesn't show crash logs" issues.

**Comment by jmagman** [comment] 2020-04-30 01:07
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-04-30 01:07 UTC
Labels: engine, platform-ios, severe: regression, tool, waiting for customer response
