### ISSUE TITLE
After Xcode 11.4 migration simulator stuck at launch screen

### ISSUE THREAD

**Issue by rajeevjaiswal** [flutter/flutter#56236] opened 2020-05-03 13:13 UTC
Below is the error.

Xcode build done.                                           87.6s
        path: satisfied (Path is satisfied), interface: en0
Failed to find assets path for "Frameworks/App.framework/flutter_assets"
        path: satisfied (Path is satisfied), interface: en0
[Crashlytics] Version 3.14.0 (144)
[Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize
[VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
[VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.

**Comment by TahaTesser** [comment] 2020-05-04 09:28
Hi @rajeevjaiswal 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by rajeevjaiswal** [comment] 2020-05-04 10:07
@TahaTesser  At this moment I don't know whether I will be able ti create a sample project. I am able to create a release build.

I have shared the details you have asked.
[https://gist.github.com/rajeevjaiswal/ac5252eba8366162f413617d130db172](url)

**Comment by TahaTesser** [comment] 2020-05-04 15:12
duplicate of [#54558](https://github.com/flutter/flutter/issues/54558)

**Closed by TahaTesser** 2020-05-04 15:12 UTC
Labels: in triage
