### ISSUE TITLE
Camera: CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)

### ISSUE THREAD

**Issue by HonestElf** [flutter/flutter#120774] opened 2023-02-15 09:17 UTC
My source code is a little different, but I also tried to run official example and got the same error

### Steps to Reproduce
1. copy-paste code from https://docs.flutter.dev/cookbook/plugins/picture-using-camera
2. Run example
3. Press camera button
4. Nothing happens, but camera freezes
5. Press camera button again and get exeption: CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)

### Device
Emulator Pixel XL API 33 
OS: Android Tiramisu

### flutter doctor -v
[√] Flutter (Channel stable, 3.7.3, on Microsoft Windows [Version 10.0.19045.2486], locale ru-RU)
    • Flutter version 3.7.3 on channel stable at C:\flutterSDK\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (6 days ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0) 
    • Android SDK at C:\Users\vd.prokudin\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6) 
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.75.1)
    • VS Code at C:\Users\vd.prokudin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.58.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2486]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 110.0.5481.77
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 109.0.1518.78

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by exaby73** [comment] 2023-02-15 09:37
Hello @HonestElf. Have you added camera permissions to your manifest file before running the app?

**Comment by HonestElf** [comment] 2023-02-15 10:23
>I set minSdkVersion to 21 in build.gradle, and allowed сamera and micro when using my app

**Comment by HonestElf** [comment] 2023-02-16 09:48
@exaby73 camera: 0.10.3

**Comment by exaby73** [comment] 2023-02-17 07:23
This looks like a duplicate of https://github.com/flutter/flutter/issues/113532. Therefore, I am closing this issue. If you disagree, please comment with your reasoning, and I can reopen the issue. Thank you

**Closed by exaby73** 2023-02-17 07:23 UTC
Labels: in triage

**Comment by HonestElf** [comment] 2023-02-17 07:54
@exaby73 I dont think it is a duplicate. As i see, in the https://github.com/flutter/flutter/issues/113532 the problem is in using  _"pausePreview"_, which I dont use it in my example

**Comment by exaby73** [comment] 2023-02-17 14:16
I cannot reproduce the issue you mentioned. I used the camera example at the end of the referenced page, running on an Android 13 emulator

<details>
<summary>Code Sample</summary>

```dart
import 'dart:async';
import 'dart:io';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  // Ensure that plugin services are initialized so that `availableCameras()`
  // can be called before `runApp()`
  WidgetsFlutterBinding.ensureInitialized();

  // Obtain a list of the available cameras on the device.
  final cameras = await availableCameras();

  // Get a specific camera from the list of available cameras.
  final firstCamera = cameras.first;

  runApp(
    MaterialApp(
      theme: ThemeData.dark(),
      home: TakePictureScreen(
        // Pass the appropriate camera to the TakePictureScreen widget.
        camera: firstCamera,
      ),
    ),
  );
}

// A screen that allows users to take a picture using a given camera.
class TakePictureScreen extends StatefulWidget {
  const TakePictureScreen({
    super.key,
    required this.camera,
  });

  final CameraDescription camera;

  @override
  TakePictureScreenState createState() => TakePictureScreenState();
}

class TakePictureScreenState extends State<TakePictureScreen> {
  late CameraController _controller;
  late Future<void> _initializeControllerFuture;

  @override
  void initState() {
    super.initState();
    // To display the current output from the Camera,
    // create a CameraController.
    _controller = CameraController(
      // Get a specific camera from the list of available cameras.
      widget.camera,
      // Define the resolution to use.
      ResolutionPreset.medium,
    );

    // Next, initialize the controller. This returns a Future.
    _initializeControllerFuture = _controller.initialize();
  }

  @override
  void dispose() {
    // Dispose of the controller when the widget is disposed.
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Take a picture')),
      // You must wait until the controller is initialized before displaying the
      // camera preview. Use a FutureBuilder to display a loading spinner until the
      // controller has finished initializing.
      body: FutureBuilder<void>(
        future: _initializeControllerFuture,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            // If the Future is complete, display the preview.
            return CameraPreview(_controller);
          } else {
            // Otherwise, display a loading indicator.
            return const Center(child: CircularProgressIndicator());
          }
        },
      ),
      floatingActionButton: FloatingActionButton(
        // Provide an onPressed callback.
        onPressed: () async {
          // Take the Picture in a try / catch block. If anything goes wrong,
          // catch the error.
          try {
            // Ensure that the camera is initialized.
            await _initializeControllerFuture;

            // Attempt to take a picture and get the file `image`
            // where it was saved.
            final image = await _controller.takePicture();

            if (!mounted) return;

            // If the picture was taken, display it on a new screen.
            await Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) => DisplayPictureScreen(
                  // Pass the automatically generated path to
                  // the DisplayPictureScreen widget.
                  imagePath: image.path,
                ),
              ),
            );
          } catch (e) {
            // If an error occurs, log the error to the console.
            print(e);
          }
        },
        child: const Icon(Icons.camera_alt),
      ),
    );
  }
}

// A widget that displays the picture taken by the user.
class DisplayPictureScreen extends StatelessWidget {
  final String imagePath;

  const DisplayPictureScreen({super.key, required this.imagePath});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Display the Picture')),
      // The image is stored as a file on the device. Use the `Image.file`
      // constructor with the given path to display the image.
      body: Image.file(File(imagePath)),
    );
  }
}
```

</details>

**Comment by HonestElf** [comment] 2023-02-21 14:03
@exaby73 apparently, you are right. The problem was in emulator.
So, for anyone who comes across this kind of error - try changing your emulator.
For me, error was on: 
- Device: Pixel XL API 33
- OS: Android Tiramisu (Google APIs)

But everything works well on
- Device: Nexus 5X API 33
- OS: Android Tiramisu (Google Play)
