### ISSUE TITLE
Support Flutter based replacement of Android services

### ISSUE THREAD

**Issue by vogella** [flutter/flutter#49345] opened 2020-01-23 13:00 UTC
## Use case

AFAIK Flutter provides currently no way to create and run Android services on Android without re-using Android native code. Would be great to write Flutter apss without the need to create native code. I can assume this might be harder so iOS so this request is specific for Android.

<## Proposal

Provide library which wraps the Android service creation into a nice Flutter API.

**Comment by mannprerak2** [comment] 2020-01-23 20:20
duplicate of #32164
related:- #24278 #3671

**Comment by xster** [comment] 2020-05-13 01:34
Merging into #32164

**Closed by xster** 2020-05-13 01:34 UTC
Labels: engine, platform-android, proposal
