### ISSUE TITLE
TextInput.finishAutofillContext() doesn't bring up the system prompt - iOS

### ISSUE THREAD

**Issue by marwanayman11** [flutter/flutter#151983] opened 2024-07-18 18:05 UTC
### Steps to reproduce

1 - Fill email input field
2 -  Fill password input field
3 - Press the "Submit" button which calls TextInput.finishAutofillContext()

### Expected results

iOS prompt to save the password should appear

### Actual results

Pressing the "Submit" button does not do anything.

### Code sample

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: AutofillTestPage(),
    );
  }
}

class AutofillTestPage extends StatefulWidget {
  const AutofillTestPage({super.key});

  @override
  State<AutofillTestPage> createState() => _AutofillTestPageState();
}

class _AutofillTestPageState extends State<AutofillTestPage> {
  final _usernameController = TextEditingController();
  final _passwordController = TextEditingController();
  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Autofill Test'),
      ),
      body: AutofillGroup(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Form(
            key: _formKey,
            child: Column(
              children: [
                TextFormField(
                  controller: _usernameController,
                  autofillHints: const [AutofillHints.username],
                  decoration: const InputDecoration(labelText: 'Username'),
                ),
                TextFormField(
                  controller: _passwordController,
                  autofillHints: const [AutofillHints.password],
                  decoration: const InputDecoration(labelText: 'Password'),
                  obscureText: true,
                ),
                const SizedBox(height: 20),
                ElevatedButton(
                  onPressed: () {
                    if (_formKey.currentState!.validate()) {
                      TextInput.finishAutofillContext();
                    }
                  },
                  child: const Text('Submit'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    _usernameController.dispose();
    _passwordController.dispose();
    super.dispose();
  }
}

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.90.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by darshankawar** [comment] 2024-07-19 08:35
Closing this as duplicate of https://github.com/flutter/flutter/issues/116889

**Closed by darshankawar** 2024-07-19 08:35 UTC
Labels: in triage
