### ISSUE TITLE
Because google_maps_flutter_example depends on google_maps_flutter from path which requires SDK version <2.0.0, version solving failed

### ISSUE THREAD

**Issue by ZackPashkin** [flutter/flutter#25737] opened 2018-12-25 00:41 UTC
Don't know how to solve this? Thank you in advance!

**Because google_maps_flutter_example depends on google_maps_flutter from path which requires SDK version <2.0.0, version solving failed**

```
flutter doctor -v
[✓] Flutter (Channel dev, v1.1.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.1.4 at /media/tienen/c139a775-f6cd-4467-898d-bc3fd2ecccc0/zack/development/tools/flutter
    • Framework revision 7a88fbc5fd (4 days ago), 2018-12-20 11:38:07 -0800
    • Engine revision dbdb5e6f8c
    • **Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)**

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /media/tienen/c139a775-f6cd-4467-898d-bc3fd2ecccc0/zack/development/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /media/tienen/c139a775-f6cd-4467-898d-bc3fd2ecccc0/zack/development/Android/Sdk
    • ANDROID_SDK_ROOT = /media/tienen/c139a775-f6cd-4467-898d-bc3fd2ecccc0/zack/development/Android/Sdk
    • Java binary at: /media/tienen/c139a775-f6cd-4467-898d-bc3fd2ecccc0/zack/development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /media/tienen/c139a775-f6cd-4467-898d-bc3fd2ecccc0/zack/development/android-studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-12-27 13:54
Caused by https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/pubspec.yaml#L24

**Comment by cyanglaz** [comment] 2019-04-05 21:07
cc @iskakaushik

**Comment by iskakaushik** [comment] 2019-04-05 21:09
This should be fixed in the latest version of google_maps plugin. @ZackPashkin can you try and let us know if this is still an issue?

**Closed** 2019-05-12 05:15 UTC
Labels: p: first party, p: maps, plugin, severe: crash, waiting for customer response

**Comment by wvell** [comment] 2019-12-11 09:02
I am running into the same issue. I am on the latest commit `bdea2cf7`

````
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.9.1+hotfix.6 at /usr/local/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/wvellema/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
````

If i run `$ flutter packages get` from the directory `plugins/packages/google_maps_flutter` it gives me the following error.

````bash
The current Flutter SDK version is 1.9.1+hotfix.6.

Because google_maps_flutter requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.
Running "flutter pub get" in google_maps_flutter...
pub get failed (1)
````

**Comment by wvell** [comment] 2019-12-13 09:35
After upgrading flutter on my mac the build error is gone.
I am now on `Flutter version 1.12.13+hotfix.5`

**Comment by sromano1992** [comment] 2020-06-01 18:55
resolved on Windows running "flutter upgrade"
