### ISSUE TITLE
FileSystemException: writeFrom failed, path = '' (OS Error: The pipe is being closed.  , errno = 232)

### ISSUE THREAD

**Issue by HerikaSethiAfiDigital** [flutter/flutter#139723] opened 2023-12-07 07:24 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run Flutter web project in debug mode. 
On Hot Restart, the debug session automatically terminates and shows error logs in debug console.

### Expected results

The debug session should not automatically Terminate.

### Actual results

Debug session terminating.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: The pipe is being closed.

, errno = 232)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:905:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:309:15)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#8      _StreamController._add (dart:async/stream_controller.dart:658:7)
#9      _StreamController.add (dart:async/stream_controller.dart:606:5)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:154:17)
#11     _StdSink.add (dart:io/stdio.dart:350:11)
#12     DaemonStreams.send (package:flutter_tools/src/daemon.dart:218:19)
#13     DaemonConnection.sendEvent (package:flutter_tools/src/daemon.dart:314:20)
#14     Domain.sendEvent (package:flutter_tools/src/commands/daemon.dart:291:23)
#15     AppDomain._sendAppEvent (package:flutter_tools/src/commands/daemon.dart:821:5)
#16     AppRunLogger._sendProgressEvent (package:flutter_tools/src/commands/daemon.dart:1605:15)
#17     AppRunLogger.startProgress (package:flutter_tools/src/commands/daemon.dart:1563:5)
#18     ResidentWebRunner.restart (package:flutter_tools/src/isolated/resident_web_runner.dart:377:35)
#19     AppInstance.restart (package:flutter_tools/src/commands/daemon.dart:1350:20)
#20     AppDomain.restart.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:700:20)
#21     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:1361:18)
#22     AppDomain._queueAndDebounceReloadAction.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:729:17)
#23     DebounceOperationQueue.queueAndDebounce.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:1693:35)
#24     _rootRun (dart:async/zone.dart:1391:47)
#25     _CustomZone.run (dart:async/zone.dart:1301:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#28     _rootRun (dart:async/zone.dart:1399:13)
#29     _CustomZone.run (dart:async/zone.dart:1301:19)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233:23)
#31     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#34     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

### Flutter Doctor output

flutter doctor -v
[√] Flutter (Channel stable, 3.16.1, on Microsoft Windows [Version 10.0.22621.2715], locale en-IN)
    • Flutter version 3.16.1 on channel stable at C:\Users\afi_d\Downloads\flutter_windows_3.16.0-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (10 days ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\afi_d\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\afi_d\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2715]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.200
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.97

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

**Comment by danagbemava-nc** [comment] 2023-12-07 08:22
Closing this as a duplicate of https://github.com/flutter/flutter/issues/81660

**Closed by danagbemava-nc** 2023-12-07 08:22 UTC
Labels: in triage
