### ISSUE TITLE
Separate pass or fail status not appearing for iOS XCTest

### ISSUE THREAD

**Issue by umangdivyanshu** [flutter/flutter#103020] opened 2022-05-04 05:51 UTC
For iOS XCTest, only a single test case with name 'testIntegrationTest' is appearing in the test case result summary.

It does not help to identify which test case is passing or failing. There should be separate test cases with respective pass or fail status.

I had raised this issue with Firebase Support team and after some debugging they came up with below response - 

_"Regarding this issue, after a thorough investigation by our team, it would be best to raise this to Flutter's GitHub Issues so that it can be triaged by the correct folks since this doesn't appear to be limited to FTL and is more of an issue with open source Flutter. I know it could be tedious and frustrating, but this would be helpful in resolving your issue. Thanks for understanding."_

Flutter Version - 2.10.5(Stable)
XCode version used - 13.2.1
iPhone model/device - iPhone 13 Pro
iOS version - iOS 15.2

![image](https://user-images.githubusercontent.com/77405518/166628332-8f06e6a7-9c71-40e8-9b4d-e69408d41445.png)

**Comment by darshankawar** [comment] 2022-05-04 08:08
@umangdivyanshu 
This seems to have been fixed as part of this issue: https://github.com/flutter/flutter/issues/95648 and per [this](https://github.com/flutter/flutter/issues/95648#issuecomment-1013461503) comment, the fix should be available on latest master. 

PR that fixed this issue: https://github.com/flutter/flutter/pull/95704

So please switch to latest master and try again to see the expected behavior.

`flutter channel master`
`flutter upgrade`

**Comment by umangdivyanshu** [comment] 2022-05-06 04:37
Hi @darshankawar 
We are not able to test the fix as Firebase Test Lab is on Stable Channel. 

I have asked them if we could switch to Master Channel during runtime but there is no provision to do it.

I have also asked if they could switch to Master channel from backend so that we could test the fix. Waiting for their response on this.

When can we expect this fix to be available on Stable Channel?

**Comment by darshankawar** [comment] 2022-05-06 05:43
> When can we expect this fix to be available on Stable Channel?

/cc @jmagman for insights on this.  For your reference: https://github.com/flutter/flutter/issues/103020#issuecomment-1117036389

Also, since this has been fixed on master channel, I think it is safe to close it. If otherwise, I'll reopen it.

**Closed by darshankawar** 2022-05-06 05:43 UTC
Labels: in triage

**Comment by jmagman** [comment] 2022-05-06 18:56
This is available on 2.11.0-0.1.pre, which is available in the beta channel.  It will be in the next stable.
https://github.com/flutter/flutter/wiki/Where's-my-Commit%3F#finding-the-versions-that-contain-framework-commit-x

From https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#stable
> Roughly once a quarter, a branch that has been stabilized on beta will become our next stable branch and we will create a stable release from that branch. 

> Also, since this has been fixed on master channel, I think it is safe to close it.

Yes, this is fixed on master so should be closed.

**Comment by umangdivyanshu** [comment] 2022-05-17 05:36
@jmagman Is this fix available now on Flutter 3.0.0 stable channel?

**Comment by jmagman** [comment] 2022-05-17 17:42
Yes it's available in 3.0. If you're seeing issues please file bugs and we'll take a look.
