### ISSUE TITLE
When using BouncingScrollPhysics() on Android, the scroll-objects lock in at the top/bottom while bouncing

### ISSUE THREAD

**Issue by LucasAschenbach** [flutter/flutter#42540] opened 2019-10-11 19:15 UTC
## Description

Whenever using BouncingScrollPhysics() and scrolling to the very top/bottom such that the page bounces and then quickly scrolling into the opposite direction, the page seems to lock-in there, meaning it bounces in the opposite direction instead of normally scrolling. After that the page's scroll position is again the top/bottom of the ListView.

I don't know if this problem also occurs on iOS; so far I have only tested it for Android.

## Steps to Reproduce

Any ListView with BouncingScrollPhysics()
(Make sure the list is longer then the visible portion of the ListView)

## Flutter Doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.15 19A583, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/lucasaschenbach/Developer/flutter
    • Framework revision 2d2a1ffec9 (5 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lucasaschenbach/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • ONEPLUS A3003 • f1e37f9c • android-arm64 • Android 9 (API 28)
```

**Comment by maddada** [comment] 2019-12-22 23:04
Hey there,
I encountered the same issue, did you find any solutions for this?

It looks even worse when SliverPersistentHeader is used, the scroll rebounds to the top of the page abruptly, see here: https://youtu.be/iNuKxbdk3Do

and this shows the effect at the bottom of the list: https://youtu.be/408Xgkic9Ts

I spend a long time trying to find the cause of this, but in the end I just disabled overscrolling with this code:
`
class MyScrolllBehavior extends ScrollBehavior {
  @override
  Widget buildViewportChrome(
      BuildContext context, Widget child, AxisDirection axisDirection) {
    return child;
  }
}

return MaterialApp(
       builder: (context, child) {
        return ScrollConfiguration(
          behavior: MyScrolllBehavior(),
          child: child,
        );
      },
      key: key,
      title: 'Motel',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.getTheme(),
      routes: routes,
    );
`

**Comment by Hixie** [comment] 2020-01-10 02:00
To address this what we really need is a demonstration app that shows the problem in a very easy-to-reproduce way.

**Comment by LucasAschenbach** [comment] 2020-01-10 09:16
The following code should reproduce the issue. Scroll to the top and while the list is still bouncing, scroll into the opposite direction and the page will, against expectation, bounce into the opposite direction instead of scrolling back.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'BouncingScrollPhysics Test',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'BouncingScrollPhysics Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView(
        physics: BouncingScrollPhysics(),
        children: List<Widget>.generate(50, (index) => ListTile(
            title: Text('item $index'),
          ),
        ),
      ),
    );
  }
}

```

**Comment by LucasAschenbach** [comment] 2020-01-11 20:09
I just found the problem.

Currently, in the constructor of the [BouncingScrollSimulation class](https://github.com/flutter/flutter/blob/27321ebbad34b0a3fafe99fac037102196d655ff/packages/flutter/lib/src/widgets/scroll_simulation.dart#L31) the `_springSimulation` is set as the `_underscrollSimulation()` or `_overscrollSimulation()` function, whenever the scroll position is smaller or bigger than the leading or trailing extent respectively, however, not taking into account the sign of the velocity. Therefore, whenever the scroll position is outside the bounds of the leading or trailing extent, every 'fling-action' will trigger a `ScrollSpringSimulation()`, regardless of the fling-direction.

With this code everything should work as expected:

```
BouncingScrollSimulation({
    @required double position,
    @required double velocity,
    @required this.leadingExtent,
    @required this.trailingExtent,
    @required this.spring,
    Tolerance tolerance = Tolerance.defaultTolerance,
  }) : assert(position != null),
       assert(velocity != null),
       assert(leadingExtent != null),
       assert(trailingExtent != null),
       assert(leadingExtent <= trailingExtent),
       assert(spring != null),
       super(tolerance: tolerance) {
    if (velocity <= 0.0 && position < leadingExtent) {              // <---- added velocity <= 0.0
      _springSimulation = _underscrollSimulation(position, velocity);
      _springTime = double.negativeInfinity;
    } else if (velocity >= 0.0 && position > trailingExtent) {      // <---- added velocity >= 0.0
      _springSimulation = _overscrollSimulation(position, velocity);
      _springTime = double.negativeInfinity;
    } else {
      _frictionSimulation = FrictionSimulation(0.135, position, velocity);
      final double finalX = _frictionSimulation.finalX;
      if (velocity > 0.0 && finalX > trailingExtent) {
        _springTime = _frictionSimulation.timeAtX(trailingExtent);
        _springSimulation = _overscrollSimulation(
          trailingExtent,
          math.min(_frictionSimulation.dx(_springTime), maxSpringTransferVelocity),
        );
        assert(_springTime.isFinite);
      } else if (velocity < 0.0 && finalX < leadingExtent) {
        _springTime = _frictionSimulation.timeAtX(leadingExtent);
        _springSimulation = _underscrollSimulation(
          leadingExtent,
          math.min(_frictionSimulation.dx(_springTime), maxSpringTransferVelocity),
        );
        assert(_springTime.isFinite);
      } else {
        _springTime = double.infinity;
      }
    }
    assert(_springTime != null);
  }
...
```


@maddada Could you please check if this also fixes your problem with the `SliverPersistentHeader`?
@Hixie Were you able to reproduce the issue? I created a pull request with the fix deployed: #48650

**Comment by maddada** [comment] 2020-01-14 06:13
@LucasAschenbach 
Hey Lucas, 
thank you for the proposed fix, but it's not working in the `SliverPersistentHeader` case as you can see here: https://photos.app.goo.gl/7yCuq2PkkhcYCcyC6

**Comment by maddada** [comment] 2020-01-14 06:31
Please try with this gist: https://gist.github.com/maddada/2cc7714328ad1c44d5fccabe7a73eb7a

**Comment by maddada** [comment] 2020-01-17 22:37
@LucasAschenbach Hey, I tested this fix and it's working great.
Thank you very much!

If you could fix the problem with the tests that would be great!

**Comment by LucasAschenbach** [comment] 2020-01-18 14:41
Glad it works!

I discovered  that, unfortunately, the fix will have to nclude a little more than just the velocity condition. The problem  with this solution is that, once the scrollable object is overscrolled and experiences just the slightest fling into the opposing direction, the object will under no circumstances snap back to the leading/trailing extent. This is very much intended for higher velocities; however, for lower velocities, this would leave the scrollable object in an overscrolled position. I already checked how iOS handles these exceptions and am now implementing this into the material spring simulation.


Temporary Fix
---
In the mean time, until I finished implementing this, you can add this line:
```
double maxFlingVelocity = 5 * math.min((position - leadingExtent).abs(), (position - trailingExtent).abs());
```
to the constructor and then replace the `0.0` in the condition with `maxFlingVelocity`  and  `-maxFlingVelocity ` respectively. This gets pretty close to the intended behaviour.

**Comment by maddada** [comment] 2020-01-18 18:10
I see, alright I'll use the fix until then.
Thank you :)

**Comment by darshankawar** [comment] 2021-02-03 11:01
I tried the code sample mentioned in above thread, https://github.com/flutter/flutter/issues/42540#issuecomment-572943783 using latest stable and master, but didn't observe / notice the lock at the top/bottom while bouncing, unless I missed the obvious issue.  I also changed the `velocity` but saw the same results.


https://user-images.githubusercontent.com/67046386/106737789-1e296680-663d-11eb-8de5-5f8c66ae8b9f.mp4


I am going ahead and closing this. If anyone disagrees, write in comments and I'll reopen it.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (11 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 1.26.0-18.0.pre.156, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-18.0.pre.156 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 45508985b1 (7 hours ago), 2021-02-02 22:46:04 -0500
    • Engine revision 2c144c3eeb
    • Dart version 2.12.0 (build 2.12.0-282.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      88.0.4324.96

! Doctor found issues in 1 category.


```

</details>

**Closed by darshankawar** 2021-02-03 11:01 UTC
Labels: P4, f: scrolling, found in release: 1.18, framework, has reproducible steps
