### ISSUE TITLE
flutter build appbundle "android x compatibility"

### ISSUE THREAD

**Issue by drexel-ue** [flutter/flutter#38377] opened 2019-08-13 01:24 UTC
when running `flutter build appbundle` two days after a successful android x migration (migration done Saturday Aug 09 2019 and confirmed running on Galaxy s7 edge), getting the following output, ending with an error message saying this is a possible android x compatibility issue:

```vim
ikeshs-MBP:trivia_black_mobile ikeshpack$ flutter clean
Deleting 'build/'.
Deleting '/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/.dart_tool/'.
ikeshs-MBP:trivia_black_mobile ikeshpack$ flutter clean
Deleting 'build/'.
Deleting '/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/.dart_tool/'.
ikeshs-MBP:trivia_black_mobile ikeshpack$ flutter build appbundle
Initializing gradle...                                             41.2s
Resolving dependencies...                                               
  123.1s (!)                                       
Running Gradle task 'bundleRelease'...                                  
ProGuard, version 6.0.3                                         
Reading input...                                                                                                   
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/ce106bf46226698ca883efc4c465c5cf/jetified-flutter.jar] (filtered)
Reading program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/intermediates/flutter/release/libs.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.3.31/e652770b6416c6d85934086899ffed3eccd35813/kotlin-stdlib-jdk7-1.3.31.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/f71aaddb2262a71d7469b0bd0691ecf7/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/1de0ad8d185064a75121b0caf36e697b/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.31/11289d20fd95ae219333f3456072be9f081c30cc/kotlin-stdlib-1.3.31.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/680b9130e72ae3e5374affdca7818c4a/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/5741b875600463ecb2c69eb242b5f870/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/45a3d0d6330b1c79bcd66a66c24e5f2e/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/efb86e67e458d9e1e0d5a6570d74e6af/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/1ca380e32759beef32c792adad207145/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/1d56c16bec96c3672c5c46749a8f006b/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/dc947ff0209a7cded859972b176384b1/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/b175349c0a6f577a951e5d4b3260be1d/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/7e70ba73e42fda0a2fb0c296fb1ed3a5/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/198ff720414ec90dbff483dffaa45bf5/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/7622ec5f6161beeaf1658f8ba763d346/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/8e77132e261e849f2d53c3a25ac5197b/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/615d578b70af01679d45bdc391698d75/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/1f3e4119219120522e16886d5244674d/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/fc7a3b94ba3976172bb66b109466d3e2/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/57a558b6ea84dbc63f9a0dee813ab19a/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/16bf8818c984ca3784d5348a8bc744e0/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/aa62b312f0b2745ad113095b9c428f3b/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/95d25c8c65af2325082135aab98f6196/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/a121df41e8e3ae4f583e8e634c8d5326/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/0789cc87eee0f61c528997c066d41486/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/64235807210916b7f4bd406349a70e53/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/androidx.collection/collection/1.0.0/42858b26cafdaa69b6149f45dfc2894007bc2c7a/collection-1.0.0.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/31e05dc88af2df4208d55555ca23a320/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/f55f5ece050dd3f038c929651b8fa592/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/764a703af44dd0de10084fdd97a72999/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/1091c94e30d577c75f070255327cfd24/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/ff165e0b981b07e55556d761c5ef43e2/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/7b35ab90596c5d9e0c158a0a08180781/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/c2b8ce04d34c68087bb02c6f73ce43c3/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/51806b1cce25609fd503367eb6a966aa/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/8781b9722b9720e82cff5513923c2901/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/androidx.lifecycle/lifecycle-common/2.0.0/e070ffae07452331bc5684734fce6831d531785c/lifecycle-common-2.0.0.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/31745467b1eaf6b0e9e4401d74249b3a/jars/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/androidx.arch.core/core-common/2.0.0/bb21b9a11761451b51624ac428d1f1bb5deeac38/core-common-2.0.0.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.0.2/2f1d597d48e5309e935ce1212eedf5ae69d3f97/annotation-1.0.2.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.31/20c34a04ea25cb1ef0139598bd67c764562cb170/kotlin-stdlib-common-1.3.31.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/com.parse.bolts/bolts-android/1.4.0/cc174c559b5177982887bf6e1b76003aebad9516/bolts-android-1.4.0.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/com.google.zxing/core/3.3.3/b640badcc97f18867c4dfd249ef8d20ec0204c07/core-3.3.3.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/02b758dfa9d34cb45f6aeaec138e098f/jetified-bolts-applinks-1.4.0.jar] (filtered)
Reading program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/com.parse.bolts/bolts-tasks/1.4.0/d85884acf6810a3bbbecb587f239005cbc846dc4/bolts-tasks-1.4.0.jar] (filtered)
Reading program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/flutter_facebook_login/intermediates/runtime_library_classes/release/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/image_picker/intermediates/runtime_library_classes/release/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/path_provider/intermediates/runtime_library_classes/release/classes.jar] (filtered)
Reading program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/package_info/intermediates/runtime_library_classes/release/classes.jar] (filtered)
Reading program directory [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/intermediates/javac/release/compileReleaseJavaWithJavac/classes] (filtered)
Reading program directory [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/tmp/kotlin-classes/release] (filtered)
Reading program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/intermediates/transforms/mergeJavaRes/release/0.jar] (filtered)
Reading library jar [/Users/ikeshpack/Library/Android/sdk/platforms/android-28/android.jar]                        
Reading library jar [/Users/ikeshpack/Library/Android/sdk/build-tools/28.0.3/core-lambda-stubs.jar]                
Reading library jar [/Users/ikeshpack/Library/Android/sdk/platforms/android-28/optional/org.apache.http.legacy.jar]
Reading library jar [/Users/ikeshpack/Library/Android/sdk/platforms/android-28/optional/android.test.mock.jar]     
Reading library jar [/Users/ikeshpack/Library/Android/sdk/platforms/android-28/optional/android.test.base.jar]     
Reading library jar [/Users/ikeshpack/Library/Android/sdk/platforms/android-28/optional/android.test.runner.jar]   
Initializing...                                                                                                    
Note: the configuration refers to the unknown class 'com.android.vending.billing.IInAppBillingService'             
Note: the configuration refers to the unknown class 'com.android.vending.billing.IInAppBillingService'             
Note: com.facebook.appevents.codeless.internal.UnityReflection: can't find dynamically referenced class com.unity3d.player.UnityPlayer
Note: com.facebook.appevents.codeless.internal.ViewHierarchy: can't find dynamically referenced class android.view.View$ListenerInfo
Note: com.facebook.appevents.codeless.internal.ViewHierarchy: can't find dynamically referenced class android.view.View$ListenerInfo
Note: com.facebook.appevents.codeless.internal.ViewHierarchy: can't find dynamically referenced class com.facebook.react.uimanager.TouchTargetHelper
Note: com.facebook.appevents.internal.InAppPurchaseActivityLifecycleTracker: can't find dynamically referenced class com.android.vending.billing.IInAppBillingService$Stub
Note: com.facebook.appevents.internal.InAppPurchaseActivityLifecycleTracker: can't find dynamically referenced class com.android.billingclient.api.ProxyBillingActivity
Note: io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors: can't find dynamically referenced class android.util.LongArray
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.jdk8.JDK8PlatformImplementations
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.JRE8PlatformImplementations
Note: kotlin.internal.PlatformImplementationsKt: can't find dynamically referenced class kotlin.internal.JRE7PlatformImplementations
Note: kotlin.jvm.internal.Reflection: can't find dynamically referenced class kotlin.reflect.jvm.internal.ReflectionFactoryImpl
Note: the configuration keeps the entry point 'com.facebook.login.widget.LoginButton { void setDefaultAudience(com.facebook.login.DefaultAudience); }', but not the descriptor class 'com.facebook.login.DefaultAudience'
Note: the configuration keeps the entry point 'com.facebook.login.widget.LoginButton { void setLoginBehavior(com.facebook.login.LoginBehavior); }', but not the descriptor class 'com.facebook.login.LoginBehavior'
Note: the configuration keeps the entry point 'com.facebook.login.widget.LoginButton { void setToolTipStyle(com.facebook.login.widget.ToolTipPopup$Style); }', but not the descriptor class 'com.facebook.login.widget.ToolTipPopup$Style'
Note: the configuration keeps the entry point 'com.facebook.login.widget.LoginButton { void setToolTipMode(com.facebook.login.widget.LoginButton$ToolTipMode); }', but not the descriptor class 'com.facebook.login.widget.LoginButton$ToolTipMode'
Note: the configuration keeps the entry point 'com.facebook.login.widget.LoginButton { void setProperties(com.facebook.login.widget.LoginButton$LoginButtonProperties); }', but not the descriptor class 'com.facebook.login.widget.LoginButton$LoginButtonProperties'
Note: the configuration keeps the entry point 'com.facebook.login.widget.LoginButton { void setLoginManager(com.facebook.login.LoginManager); }', but not the descriptor class 'com.facebook.login.LoginManager'
Note: the configuration keeps the entry point 'com.facebook.login.widget.ProfilePictureView { void setOnErrorListener(com.facebook.login.widget.ProfilePictureView$OnErrorListener); }', but not the descriptor class 'com.facebook.login.widget.ProfilePictureView$OnErrorListener'
Note: the configuration keeps the entry point 'com.facebook.share.internal.LikeBoxCountView { void setCaretPosition(com.facebook.share.internal.LikeBoxCountView$LikeBoxCountViewCaretPosition); }', but not the descriptor class 'com.facebook.share.internal.LikeBoxCountView$LikeBoxCountViewCaretPosition'
Note: the configuration keeps the entry point 'com.facebook.share.widget.LikeView { void setLikeViewStyle(com.facebook.share.widget.LikeView$Style); }', but not the descriptor class 'com.facebook.share.widget.LikeView$Style'
Note: the configuration keeps the entry point 'com.facebook.share.widget.LikeView { void setAuxiliaryViewPosition(com.facebook.share.widget.LikeView$AuxiliaryViewPosition); }', but not the descriptor class 'com.facebook.share.widget.LikeView$AuxiliaryViewPosition'
Note: the configuration keeps the entry point 'com.facebook.share.widget.LikeView { void setHorizontalAlignment(com.facebook.share.widget.LikeView$HorizontalAlignment); }', but not the descriptor class 'com.facebook.share.widget.LikeView$HorizontalAlignment'
Note: the configuration keeps the entry point 'com.facebook.share.widget.LikeView { void setOnErrorListener(com.facebook.share.widget.LikeView$OnErrorListener); }', but not the descriptor class 'com.facebook.share.widget.LikeView$OnErrorListener'
Note: there were 2 references to unknown classes.                                                                  
      You should check your configuration for typos.                                                               
      (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)                                   
Note: there were 12 unkept descriptor classes in kept class members.                                               
      You should consider explicitly keeping the mentioned classes                                                 
      (using '-keep').                                                                                             
      (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)                                
Note: there were 11 unresolved dynamic references to classes or interfaces.                                        
      You should check if you need to specify additional program jars.                                             
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)                                 
Ignoring unused library classes...                                                                                 
  Original number of library classes: 4803                                                                         
  Final number of library classes:    1448                                                                         
Printing kept classes, fields, and methods...                                                                      
Inlining subroutines...                                                                                            
Shrinking...                                                                                                       
Printing usage to [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/outputs/mapping/release/usage.txt]...
Removing unused program classes and class elements...                                                              
  Original number of program classes: 3815                                                                         
  Final number of program classes:    1370                                                                         
Obfuscating...                                                                                                     
Printing mapping to [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/outputs/mapping/release/mapping.txt]...
Preverifying...                                                                                                    
Writing output...                                                                                                  
Preparing output jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/intermediates/transforms/proguard/release/0.jar]
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/ce106bf46226698ca883efc4c465c5cf/jetified-flutter.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/intermediates/flutter/release/libs.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.3.31/e652770b6416c6d85934086899ffed3eccd35813/kotlin-stdlib-jdk7-1.3.31.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/f71aaddb2262a71d7469b0bd0691ecf7/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/1de0ad8d185064a75121b0caf36e697b/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.3.31/11289d20fd95ae219333f3456072be9f081c30cc/kotlin-stdlib-1.3.31.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/680b9130e72ae3e5374affdca7818c4a/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/5741b875600463ecb2c69eb242b5f870/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/45a3d0d6330b1c79bcd66a66c24e5f2e/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/efb86e67e458d9e1e0d5a6570d74e6af/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/1ca380e32759beef32c792adad207145/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/1d56c16bec96c3672c5c46749a8f006b/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/dc947ff0209a7cded859972b176384b1/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/b175349c0a6f577a951e5d4b3260be1d/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/7e70ba73e42fda0a2fb0c296fb1ed3a5/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/198ff720414ec90dbff483dffaa45bf5/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/7622ec5f6161beeaf1658f8ba763d346/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/8e77132e261e849f2d53c3a25ac5197b/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/615d578b70af01679d45bdc391698d75/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/1f3e4119219120522e16886d5244674d/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/fc7a3b94ba3976172bb66b109466d3e2/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/57a558b6ea84dbc63f9a0dee813ab19a/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/16bf8818c984ca3784d5348a8bc744e0/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/aa62b312f0b2745ad113095b9c428f3b/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/95d25c8c65af2325082135aab98f6196/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/a121df41e8e3ae4f583e8e634c8d5326/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/0789cc87eee0f61c528997c066d41486/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/64235807210916b7f4bd406349a70e53/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/androidx.collection/collection/1.0.0/42858b26cafdaa69b6149f45dfc2894007bc2c7a/collection-1.0.0.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/31e05dc88af2df4208d55555ca23a320/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/f55f5ece050dd3f038c929651b8fa592/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/764a703af44dd0de10084fdd97a72999/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/1091c94e30d577c75f070255327cfd24/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/ff165e0b981b07e55556d761c5ef43e2/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/7b35ab90596c5d9e0c158a0a08180781/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/c2b8ce04d34c68087bb02c6f73ce43c3/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/51806b1cce25609fd503367eb6a966aa/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/8781b9722b9720e82cff5513923c2901/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/androidx.lifecycle/lifecycle-common/2.0.0/e070ffae07452331bc5684734fce6831d531785c/lifecycle-common-2.0.0.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/31745467b1eaf6b0e9e4401d74249b3a/jars/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/androidx.arch.core/core-common/2.0.0/bb21b9a11761451b51624ac428d1f1bb5deeac38/core-common-2.0.0.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.0.2/2f1d597d48e5309e935ce1212eedf5ae69d3f97/annotation-1.0.2.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.3.31/20c34a04ea25cb1ef0139598bd67c764562cb170/kotlin-stdlib-common-1.3.31.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/com.parse.bolts/bolts-android/1.4.0/cc174c559b5177982887bf6e1b76003aebad9516/bolts-android-1.4.0.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/com.google.zxing/core/3.3.3/b640badcc97f18867c4dfd249ef8d20ec0204c07/core-3.3.3.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/transforms-2/files-2.1/02b758dfa9d34cb45f6aeaec138e098f/jetified-bolts-applinks-1.4.0.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/.gradle/caches/modules-2/files-2.1/com.parse.bolts/bolts-tasks/1.4.0/d85884acf6810a3bbbecb587f239005cbc846dc4/bolts-tasks-1.4.0.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/flutter_facebook_login/intermediates/runtime_library_classes/release/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/image_picker/intermediates/runtime_library_classes/release/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/path_provider/intermediates/runtime_library_classes/release/classes.jar] (filtered)
  Copying resources from program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/package_info/intermediates/runtime_library_classes/release/classes.jar] (filtered)
  Copying resources from program directory [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/intermediates/javac/release/compileReleaseJavaWithJavac/classes] (filtered)
  Copying resources from program directory [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/tmp/kotlin-classes/release] (filtered)
  Copying resources from program jar [/Users/ikeshpack/Desktop/Development/upwork/swyft_studios/trivia_black_mobile/build/app/intermediates/transforms/mergeJavaRes/release/0.jar] (filtered)
Running Gradle task 'bundleRelease'...                                                                             
Running Gradle task 'bundleRelease'... Done                       816.9s (!)
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task bundleRelease failed with exit code 1
```

**Comment by developerSam64** [comment] 2019-09-04 04:27
i am also getting this error.. How to resolve this, please explain

**Comment by jonahwilliams** [comment] 2020-04-12 21:04
Duplicate of https://github.com/flutter/flutter/issues/54620

**Closed by jonahwilliams** 2020-04-12 21:04 UTC
Labels: t: gradle, tool
