### ISSUE TITLE
[go_router] Failed assertion: line 3470 pos 18: '!keyReservation.contains(key)': is not true. When pushing the same page with different detail

### ISSUE THREAD

**Issue by johnberang12** [flutter/flutter#108696] opened 2022-07-31 07:24 UTC
Im using a go_router to push a the same screen with different details in my app.  this i smoothly fine using Navigator 1.0, but for go_router it crushes and here below is the error...Let say you are in a list of products, and when you click one of the product, it pushes you to a product detail screen and when you scroll down, you can seen recommended products or other products. When you press one of them, it should push another product detail screen on top of the existing one but with different details. but it crushes and here is the error: 

<details>
<summary>logs</summary>

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building InheritedGoRouter(goRouter: Instance of 'GoRouter'):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3470 pos 18: '!keyReservation.contains(key)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///Users/jober/AndroidStudioProjects/test_app/lib/main.dart:18:24
When the exception was thrown, this was the stack: 
#2      NavigatorState._debugCheckDuplicatedPageKeys.<anonymous closure> (package:flutter/src/widgets/navigator.dart:3470:18)
#3      NavigatorState._debugCheckDuplicatedPageKeys (package:flutter/src/widgets/navigator.dart:3475:6)
#4      NavigatorState._updatePages.<anonymous closure> (package:flutter/src/widgets/navigator.dart:3531:7)
#5      NavigatorState._updatePages (package:flutter/src/widgets/navigator.dart:3534:6)
#6      NavigatorState.didUpdateWidget (package:flutter/src/widgets/navigator.dart:3457:7)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4992:57)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#11     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#15     StatelessElement.update (package:flutter/src/widgets/framework.dart:4883:5)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#19     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#23     ProxyElement.update (package:flutter/src/widgets/framework.dart:5154:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#26     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#28     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#29     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#30     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#31     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#32     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#33     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#37     _invoke (dart:ui/hooks.dart:151:10)
#38     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#39     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
```
</details>

**Comment by johnberang12** [comment] 2022-07-31 07:33
this is not an issue before on my first project, i'm pushing the same screen over and over  using context.pushNamed with out any problem but when i started another project, its no longer working, i wonder if there is an update that i'm not aware of or it is just a programming mistake. i have here a minimum code that produced the error if needed..

**Comment by qrhfz** [comment] 2022-08-01 04:00
i have the same issue

**Comment by johnberang12** [comment] 2022-08-01 06:24
@qrhfz pls let me know if you found a solution

**Comment by qrhfz** [comment] 2022-08-01 06:52
@johnberang12 not a solution but i replaced it with Navigator.of(context).push() at the moment.  

still looking for a proper solution.

**Comment by danagbemava-nc** [comment] 2022-08-01 07:01
Closing this as a duplicate of https://github.com/flutter/flutter/issues/107045. 

Kindly follow up in the linked issue for updates. 

Please upvote the issue linked above as well. 

Thank you

**Closed by danagbemava-nc** 2022-08-01 07:01 UTC
Labels: in triage
