### ISSUE TITLE
[hot reload] [hot restart]: Error -32601 received from application: Method not found

### ISSUE THREAD

**Issue by g123k** [flutter/flutter#48875] opened 2020-01-15 09:07 UTC
Hello,

Since yesterday, Hot Reload and Hot Restart are not working anymore in my project.
I have not changed any dependency, nor changed the Flutter version.
Cleaning the `build/` folder (or with the `flutter clean` command) does not change anything.

Here is the error for an Hot Reload:
```
An isolate is paused; interface might not update.
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
```

And for the Hot Restart:
```
Error 105 received from application: Isolate must be runnable
Restarted application in 1,302ms.
E/flutter (14433): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
E/flutter (14433): NoSuchMethodError: No top-level getter '' declared.
E/flutter (14433): Receiver: top-level
E/flutter (14433): Tried calling: 
E/flutter (14433): #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:202:5)
E/flutter (14433): [ERROR:flutter/runtime/dart_isolate.cc(461)] Could not resolve main entrypoint function.
E/flutter (14433): [ERROR:flutter/shell/common/engine.cc(205)] Could not run the isolate.
E/flutter (14433): [ERROR:flutter/shell/common/engine.cc(137)] Engine not prepare and launch isolate.
E/flutter (14433): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
E/flutter (14433): NoSuchMethodError: No top-level getter '' declared.
E/flutter (14433): Receiver: top-level
E/flutter (14433): Tried calling: 
E/flutter (14433): #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:202:5)
E/flutter (14433): [ERROR:flutter/runtime/dart_isolate.cc(461)] Could not resolve main entrypoint function.
E/flutter (14433): [ERROR:flutter/shell/common/engine.cc(205)] Could not run the isolate.
E/flutter (14433): [ERROR:flutter/shell/common/engine.cc(137)] Engine not prepare and launch isolate.
Error -32000 received from application: Could not run configuration in engine.
Error -32000 received from application: Could not run configuration in engine.
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
```

Also my flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale en-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

Do you have any idea on how I should fix this?
Thanks :)

**Comment by iapicca** [comment] 2020-01-15 09:33
Hi @g123k  
could you please run 
`flutter pub cache repair`
and then again `flutter clean`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
thank you

**Comment by g123k** [comment] 2020-01-15 10:09
It seems that the `flutter pub cache repair` command fixed my issue.
I will keep however the issue open "just in case"

**Comment by g123k** [comment] 2020-01-15 10:24
Unfortunately it was only temporary, after 2 Hot Restarts, the problem is back again:

Here is the `flutter run output`:

```
[+12889 ms] Performing hot restart...
[        ] Refreshing active FlutterViews before restarting.
[        ] Sending to VM service: _flutter.listViews({})
[   +9 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x78dff3ef6e20, isolate: {type: @Isolate, fixedId: true, id:
isolates/3981015728112399, name: main.dart$main-3981015728112399, number: 3981015728112399}}, {type: FlutterView, id: _flutterView/0x78e00dc50b20, isolate:
{type: @Isolate, fixedId: true, id: isolates/1113478553076755, name: main.dart$main-1113478553076755, number: 1113478553076755}}, {type: FlutterView, id:
_flutterView/0x78e00dc51220, isolate: {type: @Isolate, fixedId: true, id: isolates/817293948809963, name: main.dart$main-817293948809963, number:
817293948809963}}]}
[  +12 ms] Scanned through 767 files in 11ms
[        ] Syncing files to device Android SDK built for x86 64...
[        ] Scanning asset files
[        ] <- reset
[        ] Compiling dart to kernel with 1 updated files
[   +1 ms] <- recompile package:icelander/app/entrypoints/main-icelander-dev.dart 64e466e5-5670-4d0c-80cc-50d24e388e98
[        ] <- 64e466e5-5670-4d0c-80cc-50d24e388e98
[ +419 ms] Updating files
[ +929 ms] DevFS: Sync finished
[        ] Syncing files to device Android SDK built for x86 64... (completed in 1,351ms)
[        ] Synced 26.5MB.
[        ] <- accept
[        ] Sending to VM service: getIsolate({isolateId: isolates/3981015728112399})
[        ] Sending to VM service: getIsolate({isolateId: isolates/1113478553076755})
[        ] Sending to VM service: getIsolate({isolateId: isolates/817293948809963})
[   +4 ms] Result: {type: Isolate, id: isolates/3981015728112399, name: main, number: 3981015728112399, _originNumber: 3981015728112399, startTime:
1579026197802, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis...
[   +2 ms] Sending to VM service: resume({isolateId: isolates/3981015728112399})
[  +14 ms] Result: {type: Isolate, id: isolates/817293948809963, name: main, number: 817293948809963, _originNumber: 817293948809963, startTime:
1579026197305, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis: 0...
[   +8 ms] Result: {type: Isolate, id: isolates/1113478553076755, name: main, number: 1113478553076755, _originNumber: 1113478553076755, startTime:
1579026197473, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 14, avgCollectionPeriodMilli...
[   +3 ms] Error 105 received from application: Isolate must be runnable
[        ] {request: {method: resume, params: {isolateId: isolates/3981015728112399}}, details: Isolate must be runnable before this request is made.}
[   +2 ms] Performing hot restart... (completed in 1,410ms)
[        ] Restarted application in 1,410ms.
[   +2 ms] Sending to VM service: _flutter.runInView({viewId: _flutterView/0x78dff3ef6e20, mainScript:
file:///data/user/0/fr.geyserinformatique.icelander.dev/code_cache/mobileKROWQA/mobile/lib/app/entrypoints/main-icelander-dev.dart.dill, packagesFile:
file:///data/user/0/fr.geyserinformatique.icelander.dev/code_cache/mobileKROWQA/mobile/.packages, assetDirectory:
file:///data/user/0/fr.geyserinformatique.icelander.dev/code_cache/mobileKROWQA/mobile/build/flutter_assets})
[        ] Sending to VM service: _flutter.runInView({viewId: _flutterView/0x78e00dc50b20, mainScript:
file:///data/user/0/fr.geyserinformatique.icelander.dev/code_cache/mobileKROWQA/mobile/lib/app/entrypoints/main-icelander-dev.dart.dill, packagesFile:
file:///data/user/0/fr.geyserinformatique.icelander.dev/code_cache/mobileKROWQA/mobile/.packages, assetDirectory:
file:///data/user/0/fr.geyserinformatique.icelander.dev/code_cache/mobileKROWQA/mobile/build/flutter_assets})
[        ] Sending to VM service: _flutter.runInView({viewId: _flutterView/0x78e00dc51220, mainScript:
file:///data/user/0/fr.geyserinformatique.icelander.dev/code_cache/mobileKROWQA/mobile/lib/app/entrypoints/main-icelander-dev.dart.dill, packagesFile:
file:///data/user/0/fr.geyserinformatique.icelander.dev/code_cache/mobileKROWQA/mobile/.packages, assetDirectory:
file:///data/user/0/fr.geyserinformatique.icelander.dev/code_cache/mobileKROWQA/mobile/build/flutter_assets})
[        ] Application finished.
hot restart failed to complete

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1222:11)
<asynchronous suspension>
#2      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1272:13)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#8      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:20)
#9      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:252:5)
#10     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:476:11)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#16     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#17     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#18     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#19     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#20     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#21     _ErrorHandlingAsciiDecoderSink.addSlice (dart:convert/ascii.dart:254:17)
#22     _ErrorHandlingAsciiDecoderSink.add (dart:convert/ascii.dart:240:5)
#23     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#24     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#25     _rootRunUnary (dart:async/zone.dart:1134:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#31     _StreamController._add (dart:async/stream_controller.dart:642:7)
#32     _StreamController.add (dart:async/stream_controller.dart:588:5)
#33     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
#34     _rootRunUnary (dart:async/zone.dart:1138:13)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#39     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#40     _StreamController._add (dart:async/stream_controller.dart:642:7)
#41     _StreamController.add (dart:async/stream_controller.dart:588:5)
#42     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1379:33)
#43     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by dnfield** [comment] 2020-01-15 17:46
It looks like somehow you're trying to hot reload/restart code that has no main entrypoint.

Are you doing somethign like editing out the `main` function?  Are you forgetting to mark a function you want to use as an entrypoint as `@pragma('vm:entry-point')`?

**Comment by dnfield** [comment] 2020-01-15 17:46
Please include a sample project that reproduces this error, and the steps to make it occur.

If this is what I think it is, I'm surprised the Dart compiler is letting it pass.

**Comment by g123k** [comment] 2020-01-17 06:58
Hi Dan,

The app have multiple "main" files, but I only use one when I run the app (`flutter run -t filename.dart`).
And my edits are absolutely never related to this part of the app.

Since the project is internal/private, how can I share it with you?

**Comment by dnfield** [comment] 2020-01-17 15:13
Can you create a smaller project that similarly has multiple files and gives you the same problem?

**Comment by AchalYash** [comment] 2020-01-30 18:34
Go to app\build.gradle and replace "GradleException" with "FileNotFoundException".
That did work for me.

**Comment by g123k** [comment] 2020-02-11 12:15
@dnfield Unfortunately I am unable to isolate the problem (even if it seems that the problem is less frequent on the dev branch)

**Comment by jonahwilliams** [comment] 2020-03-07 18:03
If we don't have any way to reproduce this it's unlikely we're going to be able to make any progress on the issue. I would recommend starting with a fork of your current project and removing features until the issue no longer reproduces. At that point, you should have enough information to determine if it is an issue in you project setup or a bug in flutter.

Without this information, the bug is unfortunately not actionable from our end.

**Comment by jmagman** [comment] 2020-03-30 20:07
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-03-30 20:07 UTC
Labels: severe: crash, t: hot reload, tool, waiting for customer response
