### ISSUE TITLE
FormatException: Unexpected extension byte (at offset 5)

### ISSUE THREAD

**Issue by dipakbari4** [flutter/flutter#97807] opened 2022-02-04 15:44 UTC
## Steps to Reproduce

1. Upgraded my flutter 2.8.x to 2.10
2. Flutter doctor throws error in Intellij Idea part
3. It prints **FormatException: Unexpected extension byte (at offset 5)**

See the logs

## Logs

<details>
<summary>Logs</summary>

![image](https://user-images.githubusercontent.com/18239859/152558305-5dce4f68-cccf-46b7-8496-147d81c73010.png)

```
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X FormatException: Unexpected extension byte (at offset 5)
```

</details>

**Comment by tallpeak** [comment] 2022-02-05 05:39
Through a process of elimination (by moving jar files to temp dirs), I found the exception occurs in reading my Dart.jar dated 12/1/2021,   version 213.5744.122

Oh, duplicate of https://github.com/flutter/flutter/issues/96651, which says this is fixed on the master channel. (So delete my comment after closing as duplicate, I guess!)

**Comment by darshankawar** [comment] 2022-02-07 07:12
@dipakbari4 
The fix is currently available on master and will be rolled out in beta and stable per Flutter's release guidelines.
See https://github.com/flutter/flutter/issues/94060#issuecomment-1018801980 issue comment for your reference.
Closing this as a duplicate.

**Closed by darshankawar** 2022-02-07 07:12 UTC
Labels: in triage
