### ISSUE TITLE
my app crashes after kill from history when I try to rerun it on an iPhone (Android runs fine) .

### ISSUE THREAD

**Issue by mohammad-alshelleh** [flutter/flutter#70931] opened 2020-11-20 10:33 UTC
I'm trying to build a simple app using Flutter for iOS and Android, but the app crashes on startup when I try to run it on an iPhone (Android runs fine). 
 I've been digging around some more and it looks like the crash is related to the Firebase dependencies. If I create the Flutter demo project (flutter create ), it runs fine on iOS. However if I then add Firebase packages to pubspec.yaml, and manually add GoogleServices-info.plist, the app crashes on rerun without android studio or xcode(from my iphone).

No error
flutter doctor:
[✓] Flutter (Channel master, 1.24.0-6.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-JO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)

• No issues found!

**Comment by pedromassangocode** [comment] 2020-11-20 10:41
Hi @mohammad-alshelleh 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-20 10:41 UTC
