### ISSUE TITLE
mac ios failure doesn't have any failure reason for infra failure

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#88043] opened 2021-08-11 16:13 UTC
see build: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/9559/overview

**Comment by yusufm** [comment] 2021-08-11 17:44
Confirmed that its a transient issue, it succeeded on retry.

@godofredoc captured following logs from bot:
```
All pending Futures: (/base/alloc/tmpfs/dynamic_runtimes/python27g/46417889d06c4c16/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py:364)
<Future 3e8cab7efc50 created by transaction_async(model.py:3813) for tasklet transaction(context.py:947) suspended generator transaction(context.py:1033); pending>
 waiting for <Future 3e8cb9328a90 created by transaction(context.py:1033) for tasklet flush(context.py:324); pending>
<MultiFuture 3e8cb2b12910 created by run0(eventloop.py:230) for multi-yield from suspended generator flush(context.py:266); pending>
 waiting for <Future 3e8cb3a2ef90 created by run_queue(context.py:186) for tasklet _get_tasklet(context.py:336); pending>
<Future 3e8cbc2d5550 created by flush(context.py:329) for tasklet flush(context.py:262); pending>
<Future 3e8cb1eff590 created by add(context.py:212) for AutoBatcher(_get_tasklet).add(Key('TaskRequest', 8839185655874236366, 'TaskResultSummary', 1, 'TaskRunResult', 1), None); pending>
<Future 3e8caa885190 created by transaction(txn.py:69) for tasklet transaction_async(txn.py:33) suspended generator transaction_async(txn.py:50); pending>
 waiting for <Future 3e8cab7efc50 created by transaction_async(model.py:3813) for tasklet transaction(context.py:947) suspended generator transaction(context.py:1033); pending>
 waiting for <Future 3e8cb9328a90 created by transaction(context.py:1033) for tasklet flush(context.py:324); pending>
<MultiFuture 3e8cbc2d5f90 created by run0(eventloop.py:230) for multi-yield from suspended generator flush(context.py:329); pending>
 waiting for <Future 3e8cbc2d5550 created by flush(context.py:329) for tasklet flush(context.py:262); pending>
 waiting for <Future 3e8cab9a03d0 created by flush(context.py:329) for tasklet flush(context.py:262); result None>
 waiting for <Future 3e8cb339d310 created by flush(context.py:329) for tasklet flush(context.py:262); result None>
 waiting for <Future 3e8caa2f8250 created by flush(context.py:329) for tasklet flush(context.py:262); result None>
 waiting for <Future 3e8caa2f8550 created by flush(context.py:329) for tasklet flush(context.py:262); result None>
 waiting for <Future 3e8cb3895d90 created by flush(context.py:329) for tasklet flush(context.py:262); result None>
 waiting for <Future 3e8cb2b18ed0 created by flush(context.py:329) for tasklet flush(context.py:262); result None>
<Future 3e8cb9328a90 created by transaction(context.py:1033) for tasklet flush(context.py:324); pending>
<Future 3e8cb1eff2d0 created by get_async(key.py:585) for tasklet get(context.py:690) suspended generator get(context.py:762); pending>
 waiting for <Future 3e8cb1eff590 created by add(context.py:212) for AutoBatcher(_get_tasklet).add(Key('TaskRequest', 8839185655874236366, 'TaskResultSummary', 1, 'TaskRunResult', 1), None); pending>
<Future 3e8cb3a2ef90 created by run_queue(context.py:186) for tasklet _get_tasklet(context.py:336); pending>

Deadlock in <Future 3e8caa885190 created by transaction(txn.py:69) for tasklet transaction_async(txn.py:33) suspended generator transaction_async(txn.py:50); pending> (/base/alloc/tmpfs/dynamic_runtimes/python27g/46417889d06c4c16/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py:363)
```

**Comment by godofredoc** [comment] 2021-08-11 18:03
We may want to open a bug with the swarming team or link and existing one.

**Comment by iskakaushik** [comment] 2021-08-11 18:17
It happened again and is making the engine tree red: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20Web%20Engine/6395/overview

**Comment by godofredoc** [comment] 2021-08-11 18:23
That one looks like a different issue: @yusufm can you please open a chromium bug and reach to luci-users to check.

**Comment by yusufm** [comment] 2021-08-12 00:02
Requesting additional help from LUCI: https://bugs.chromium.org/p/chromium/issues/detail?id=1239029

**Comment by yusufm** [comment] 2021-08-12 16:34
As per information from the LUCI bug, this expected to happen (rarely). They said to keep an eye out if the particular issue happens more frequently. If you haven't seen more of these failures, I'll close this issue and we can reopen if they start cropping up again.

**Comment by yusufm** [comment] 2021-08-12 21:46
Reducing the priority to p2 as initial investigation done and we collect more occurrences to provide to the LUCI team for deeper analysis.

**Comment by iskakaushik** [comment] 2021-08-16 17:15
happened again: https://ci.chromium.org/ui/p/flutter/builders/prod/Mac%20iOS%20Engine%20Release/9625/overview

**Comment by godofredoc** [comment] 2021-08-23 18:11
@yusufm any updates on this bug?

**Comment by godofredoc** [comment] 2021-09-13 18:11
@yusufm any updates?

**Comment by yusufm** [comment] 2021-09-13 18:12
Checking with LUCI team on their investigation.

**Comment by godofredoc** [comment] 2022-03-22 20:21
Updating as P3 this happens rarely and we depend on upstream fixes to avoid the failure.

**Comment by godofredoc** [comment] 2023-03-02 23:44
Closing as obsolete.

**Closed by godofredoc** 2023-03-02 23:44 UTC
Labels: team: infra, passed secondary triage, P3
