### ISSUE TITLE
[Android] Wireless mouse scroll very slow

### ISSUE THREAD

**Issue by selvam920** [flutter/flutter#99219] opened 2022-02-27 04:40 UTC
when we use finger the scroll perfectly moving but using external mouse the scroll is moving very slow
Sample code: just create listview with 20 items and scroll by mouse

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.11.0-0.0.pre.690, on Microsoft Windows [Version 10.0.22000.527], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Comment by darshankawar** [comment] 2022-02-28 09:16
@selvam920 
This looks like duplicate of https://github.com/flutter/flutter/issues/82973, so closing it in favor of original.
Please follow-up in it for further updates.

**Closed by darshankawar** 2022-02-28 09:16 UTC
Labels: in triage
