### ISSUE TITLE
Combining NestedScrollView with TabBarView has problems. (AutomaticKeepAliveMixin, Scroll Position, Laggy Tab Change Animation, PageStorageKey)

### ISSUE THREAD

**Issue by yasinarik** [flutter/flutter#71289] opened 2020-11-26 22:44 UTC
When I use a TabBarView inside a NestedScrollView, there are 2 different results both having different problems.

1. If I use AutomaticKeepAliveMixin to keep the inner scrollers (and each of their children built by `builder:` methods), they are kept alive and when changing between the tabs, there are no lags in animation. 

However, any scrolling of one of the inner scrollers also affects others and the individual scroll positions are not obeyed. Even though I use different PageStorageKey() for all of the scrollers, if AutomaticKeepAliveMixin is applied, scroll positions are problematic. 

2. If I don't apply AutomaticKeepAliveMixin to the inner scrollers, scroll positions have no issues and work as expected. However, this time, because each of the inner scrollers (and their respective children) is completely rebuilt whenever a tab change occurs. 

When there are relatively fewer items inside inner scrollers (like 20-30 items per tab), TabBarView tab change animations are fluid and no issues. However, when after a user scrolls and fills lots of children into inner scrollers, then tab change becomes very laggy. This happens because the inner scrollers build from scratch.

I have to ensure that both the tab change animation is not laggy (inner scrollers are not built from scratch every time the TabBarView changes) and the scroll positions of all of the inner scrollers kept separately (do not affect each other). 

This is an urgent problem at the moment.

## flutter doctor --verbose
<details><summary> Click here to see </summary>
<p>

```

[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.5 19F101 x86_64, locale tr-TR)
    • Flutter version 1.23.0-18.1.pre at /Users/*****/flutter
    • Framework revision 198df796aa (6 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/*****/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

 
[✓] Connected device (3 available)            
    • iPhone 8 (mobile) • B53B348C-20FE-4920-A0FE-C869D8E798EB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Web Server (web)  • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 86.0.4240.198
    ! Error: ***** is not connected. Xcode will continue when ******  is connected. (code -13)

• No issues found!

```
</p>
</details>

**Comment by iapicca** [comment] 2020-11-26 22:56
@yasinarik 
can you provide your `flutter doctor -v` and most importantly a minimal reproducible code sample

**Comment by yasinarik** [comment] 2020-11-26 23:10
> @yasinarik 
> 
> can you provide your `flutter doctor -v` and most importantly a minimal reproducible code sample
> 
> 
> 
> possible duplicate of https://github.com/flutter/flutter/issues/70606

I will provide as soon as I am available. Wrote the issue on mobile. 

For your information, mine is nothing related to the issue you have mentioned.

**Comment by naamapps** [comment] 2020-11-27 06:25
@yasinarik It is somewhat of the same issue..
In my issue I just pointed that the sliver header is showing before reaching the top. But it's happening because the scrolls in the tab bar views are intertwined with each other  when using AutomaticKeepAliveMixin

**Comment by yasinarik** [comment] 2020-11-27 09:40
I added `flutter doctor -v`. I couldn't add a reproducible code at the moment because my implementation includes an all-in-one solution strictly dependent on other complex code. I will try my best to refactor it.

Yesterday, I didn't see the video example. So today I have carefully inspected issue #70606 and although mine has a different explanation, the source of the problem is possibly the same. Sorry for the inconvenience @iapicca and @naamapps . Yet, I would like this issue to stay open too.

I couldn't find anything suspicious after checking the source code of TabBarView and NestedScrollView. However, as @naamapps said if a child of a tab has `AutomaticKeepAliveMixin` overridden `true`, certainly the inner scrollers of the NestedScrollView intertwine each other. 

Moreover, I use a custom `scroll to load more` logic. When I don't use  `AutomaticKeepAliveMixin`, it works great. But if used, the load more is triggered on the other inner scrollers whereas they must be independent of each other.

By the way, no offense, and I am grateful for all the efforts but this kind of view is used in very popular apps. Especially on user profile screens of Instagram, Twitter, TikTok, etc. I expected Flutter to provide a more convenient solution.

**Comment by naamapps** [comment] 2020-11-27 09:45
@yasinarik 
Couldn't agree more with you!
I also use this setup on a profile page and it's just unbearable to deal with in a real world application.
I really hope this gets resolved soon 👍

**Comment by darshankawar** [comment] 2020-12-04 07:19
@yasinarik 
It would be great if you could provide a code sample explaining the issue. You may come up with a sample that has the widgets you mentioned earlier in your post and title (NestedScrollView with TabBarView, AutomaticKeepAliveMixin, ScrollPosition, PageStorageKey). This would help to better analyze and address your issue to become actionable.

Thanks.

**Comment by pedromassangocode** [comment] 2020-12-30 10:44
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-12-30 10:44 UTC
Labels: f: material design, f: scrolling, framework, in triage, waiting for customer response

**Comment by smakarov** [comment] 2021-05-01 16:41
I [wrote](https://github.com/flutter/flutter/issues/81619) related issue with code samples.
