### ISSUE TITLE
Trouble to install any dependencies after updating flutter and android studio to current version on (19/01/21)

### ISSUE THREAD

**Issue by rsinghcoder** [flutter/flutter#74380] opened 2021-01-21 06:07 UTC
I'm new on flutter, a day before my project is working fine and every dependency get install by grp pub but after updating flutter and android studio any dependencies are not installing. 

it gives error 

Execution failed for task ':flutter_tts:extractDebugAnnotations'.
> Could not resolve all files for configuration ':flutter_tts:lintClassPath'.
   > Could not download lint-checks-27.1.1.jar (com.android.tools.lint:lint-checks:27.1.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-checks/27.1.1/lint-checks-27.1.1.jar'.
         > Tag mismatch!
   > Could not download kotlin-compiler-27.1.1.jar (com.android.tools.external.com-intellij:kotlin-compiler:27.1.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/com-intellij/kotlin-compiler/27.1.1/kotlin-compiler-27.1.1.jar'.
         > Tag mismatch!
   > Could not download uast-27.1.1.jar (com.android.tools.external.org-jetbrains:uast:27.1.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/external/org-jetbrains/uast/27.1.1/uast-27.1.1.jar'.
         > Tag mismatch!

for any new dependencies, it gives similar error

**Comment by TahaTesser** [comment] 2021-01-21 08:38
Hi @rsinghcoder 
This is probably due to restricted networks or local ISP blocks. Can you please make sure you've stable internet and unrestricted network (If you're not in a restricted internet country). Maybe a try VPN as it seems to solve the  issue for some in https://github.com/flutter/flutter/issues/63193#issuecomment-703997201

If the problem persists, Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by rsinghcoder** [comment] 2021-01-22 13:55
flutter doctor -v Response 


[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.746], locale en-IN)
    • Flutter version 1.22.5 at C:\Users\webepower\Flutter\flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\Programfile\Andoid\AndroidSDK\Programfile
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = E:\Programfile\Andoid\AndroidSDK\Programfile
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.5)
    • Android Studio at E:\Programfile\Andoid\setup
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.42.1)
    • VS Code at C:\Users\webepower\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 4 categories.






flutter run --verbose    response 



[  +40 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'C:\Users\webepower\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904
[        ] * What went wrong:
[  +71 ms] Execution failed for task ':app:compileFlutterBuildDebug'.
[  +31 ms] > Process 'command 'C:\Users\webepower\Flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[  +19 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 21s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 1 actionable task: 1 executed
[ +565 ms] Running Gradle task 'assembleDebug'... (completed in 23.0s)
[   +7 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 24,406ms.
[   +5 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +232 ms] ensureAnalyticsSent: 229ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +6 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1





And regarding my network, It's not restricted in any way and also I tried with different vendor and devices

**Comment by TahaTesser** [comment] 2021-01-25 07:14
Hi @rsinghcoder 

> [ ] BUILD FAILED in 21s
> [ ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

Please make sure you're using `classpath 'com.android.tools.build:gradle:3.5.0'` in your `build.gradle` and try again. 

If the problem persists, Can you please provide your **complete** `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by pedromassangocode** [comment] 2021-02-17 09:44
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-17 09:44 UTC
Labels: in triage, waiting for customer response
