### ISSUE TITLE
RouteObserver/NavigatorObserver.didPop no longer called on iOS back swipe

### ISSUE THREAD

**Issue by 1AlexFix1** [flutter/flutter#29596] opened 2019-03-19 11:11 UTC
Hello, on master, deb, beta channel didPop no calls, it is bad, because need check screen pop,
```
final RouteObserver<PageRoute> routeObserver = RouteObserver<PageRoute>();

class _BaseWidgetState extends State<BaseWidget>
    with RouteAware, WidgetsBindingObserver {

@override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

@override
  void didChangeDependencies() {
    super.didChangeDependencies();
    routeObserver.subscribe(this, ModalRoute.of(context));
  }

  @override
  void didPushNext() {
    super.didPushNext();
    print('didPushNext');
    if (widget.pushNext != null) widget.pushNext();
  }

  @override
  void didPop() {
    super.didPop();
    print('didPop');
    if (widget.pop != null) widget.pop();
  }

  @override
  void didPopNext() {
    super.didPopNext();
    print('didPopNext');
    if (widget.popNext != null) widget.popNext();
  }

  @override
  void didPush() {
    super.didPush();
    print('didPush');
    if (widget.push != null) widget.push();
  }

  @override
  void dispose() {
    routeObserver.unsubscribe(this);
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

}
```

I test channel
1. stable
//push next screen
flutter: didPushNext
flutter: didPush
-----swipe screen(iOS)
       flutter: didPopNext
       flutter: didPop
-----touch back button (Android)
       flutter: didPopNext
       flutter: didPop

test: successful

2. master
//push next screen
flutter: didPushNext
flutter: didPush
-----swipe screen(iOS)
     no reaction!!!
-----touch back button (Android)
       flutter: didPopNext
       flutter: didPop

3. dev
//push next screen
flutter: didPushNext
flutter: didPush
----- swipe screen(iOS)
           no reaction!!!
-----touch back button (Android)
           flutter: didPopNext
           flutter: didPop

4. beta
//push next screen
flutter: didPushNext
flutter: didPush
-----swipe screen(iOS)
no reaction!!!
-----touch back button (Android)
flutter: didPopNext
flutter: didPop

Flutter 1.3.12-pre.29 • channel master • https://github.com/flutter/flutter.git
Framework • revision af6e09f6ea (34 hours ago) • 2019-03-18 21:40:21 -0700
Engine • revision 5088735e5f
Tools • Dart 2.2.1 (build 2.2.1-dev.1.0 None)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.3.14-pre.7, on Mac OS X 10.14.3 18D109, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!

**Comment by msw333** [comment] 2019-03-20 10:04
Might be related to https://github.com/flutter/flutter/pull/28756

**Comment by xster** [comment] 2019-03-26 21:27
Can you help us clarify what is the API you're trying to use? Since there are 2 'iOS swipe' mechanism that may be relevant to your described issue.

On the one hand, Flutter itself handles iOS back swipes within the Flutter navigation mechanism. That's related to #28756 but not related to WidgetsBinding etc. 

On the other hand, you might be referring to executing an iOS back swipe one level higher on a FlutterViewController part of a UINavigationController that you have in your own native project. And you're manually calling FlutterViewController.popRoute. In that case, it's related to WidgetsBinding. 

These 2 things are somewhat orthogonal. What scenario are you referring to?

**Comment by 1AlexFix1** [comment] 2019-03-26 23:24
> Can you help us clarify what is the API you're trying to use? Since there are 2 'iOS swipe' mechanism that may be relevant to your described issue.
> 
> On the one hand, Flutter itself handles iOS back swipes within the Flutter navigation mechanism. That's related to #28756 but not related to WidgetsBinding etc.
> 
> On the other hand, you might be referring to executing an iOS back swipe one level higher on a FlutterViewController part of a UINavigationController that you have in your own native project. And you're manually calling FlutterViewController.popRoute. In that case, it's related to WidgetsBinding.
> 
> These 2 things are somewhat orthogonal. What scenario are you referring to?

I do Navigator.pushNamed then I do the swipe back and I do not get the message about didPop,

**Comment by xster** [comment] 2019-03-26 23:32
Thanks for the response. This might be a bug in our documentation for not being clearer. Those are orthogonal mechanisms. WidgetsBinding only observes platform triggered navigations against the ViewController or Activity etc. 

To observe the Flutter side Navigator, pass a NavigatorObserver list into the Navigator constructor (or the Material/CupertinoApp etc).

Did I interpret the question correctly?

**Comment by 1AlexFix1** [comment] 2019-03-27 00:59
> Thanks for the response. This might be a bug in our documentation for not being clearer. Those are orthogonal mechanisms. WidgetsBinding only observes platform triggered navigations against the ViewController or Activity etc.
> 
> To observe the Flutter side Navigator, pass a NavigatorObserver list into the Navigator constructor (or the Material/CupertinoApp etc).
> 
> Did I interpret the question correctly?

I think I understood, I'm sorry, I did not provide the full information in the question (full code), I, of course, pass the routeObserver to MaterialApp, I did everything as in the documentation https: //docs.flutter .io / flutter / widgets / RouteObserver -class.html and everything works fine on a stable branch, but on the remaining 3 branches didpop flutter is not called when swipe, if there was a transition using CupertinoPageRoute, however, if you press the button on android onBack, didPop is called

**Comment by msw333** [comment] 2019-03-29 19:13
> Thanks for the response. This might be a bug in our documentation for not being clearer. Those are orthogonal mechanisms. WidgetsBinding only observes platform triggered navigations against the ViewController or Activity etc.
> 
> To observe the Flutter side Navigator, pass a NavigatorObserver list into the Navigator constructor (or the Material/CupertinoApp etc).
> 
> Did I interpret the question correctly?

Can you show us how (example code)? There is no documentation on this.

**Comment by 1AlexFix1** [comment] 2019-03-29 19:50
> > Thanks for the response. This might be a bug in our documentation for not being clearer. Those are orthogonal mechanisms. WidgetsBinding only observes platform triggered navigations against the ViewController or Activity etc.
> > To observe the Flutter side Navigator, pass a NavigatorObserver list into the Navigator constructor (or the Material/CupertinoApp etc).
> > Did I interpret the question correctly?
> 
> Can you show us how (example code)? There is no documentation on this. I think most people (including me) do it like this:
> 
> ```
> final RouteObserver<PageRoute> routeObserver = new RouteObserver<PageRoute>();
> main() {..}
> 
> MaterialApp(
> navigatorObservers: <NavigatorObserver>[routeObserver], ...)
> 
> class SingleChatScreenState extends State<SingleChatScreen>
>     with RouteAware {...
> 
>  void didPopNext() {
>     print('Screen closed');
>   }
> }
> ```
Yes, that's right, I also do this, this code used to work, and is currently running on the stable branch, here I pointed out where the problem lies, we are waiting for a solution
https://github.com/flutter/flutter/pull/28756#issuecomment-469377490

**Comment by xster** [comment] 2019-03-29 20:00
Thanks. The documentation is indeed making it easy to cause the confusion visible in the original question at the top of the thread. Breaking that issue off to #30207. 

Leaving this issue to deal with the NavigatorObserver.didPop regression caused by #28756 as you correctly found.

**Comment by msw333** [comment] 2019-03-29 20:01
@xster since you're active right now. Is it a bug, or a wrong use of code (please see my short code)? Do you have a ready to use adhoc solution?

**Comment by xster** [comment] 2019-03-29 21:55
As a hacky work-around in the meantime, you can listen to NavigatorObserver.didRemove.

**Comment by xster** [comment] 2019-03-29 21:57
Yes, it is related to #28728, which makes the solution to this tricky too. If you popped something and while it's animating, pushed something else, what should we call on the NavigatorObserver? Calling didPop is ambiguous because the route that's popped is no longer the top route by the time it's called.

**Comment by alexelsn** [comment] 2019-04-02 21:00
We are also desperately waiting for a fix. Do you have any update guys ;-)?

**Comment by xster** [comment] 2019-04-03 01:46
As @Hixie suggested, since the navigation is 'committed' as soon as the back swipe gesture's pointer is lifted, we can let the pop happen at the start of the final snap animation instead of at the end of it.

**Comment by xster** [comment] 2019-04-03 02:55
It can probably be worked out but it turned out not as easy as I thought because by calling pop earlier the TransitionRoute.didPop is rather specific on how it animates 
https://github.com/flutter/flutter/blob/72a40834677bde9d9189c0c46a8db09d605917e8/packages/flutter/lib/src/widgets/routes.dart#L206
whereas we want to be very particular about the snapping animation, duration and curve when we drop the back swipe gesture.

**Comment by msw333** [comment] 2019-04-06 11:03
@xster, can you elaborate on the 'hacky' solution. I am doing the following and it is not triggered when page pops:

1.
final NavigatorObserver navigatorObserver = new NavigatorObserver();
MaterialApp( navigatorObservers: <NavigatorObserver>[navigatorObserver]... )

2. 
class ChatScreenState extends State<ChatScreen> with NavigatorObserver { ...

    @override
  void didPop(Route<dynamic> route, Route<dynamic> previousRoute) async{  
// async functions I would like to run if page pops

  }
}

**Comment by xster** [comment] 2019-04-08 19:51
Since the fix is out in https://github.com/flutter/flutter/pull/30422, you could potentially just patch the PR into your Flutter SDK and keep using didPop.

**Comment by msw333** [comment] 2019-04-08 20:04
Any idea when it will be merged into the master? Not feeling well messing around on the SDK.

**Comment by xster** [comment] 2019-04-17 20:53
Sorry for the wait all. It's been fixed.

**Closed** 2019-04-17 20:53 UTC
Labels: f: cupertino, f: routes, framework, severe: regression, waiting for PR to land (fixed), ⌺‬ platform-ios

**Comment by msw333** [comment] 2019-04-20 12:59
Leads to a new behavior on my iPhone X. After some 'using' of swipe gestures, they stop working. I can then only get back via BackButton. Then animation is much slower.

**Comment by alexelsn** [comment] 2019-04-22 16:48
Yes, the fix was also pretty important for us. But now, after some time, the swipe back stops working. Hope for new fix asap :-)

**Comment by xster** [comment] 2019-04-23 05:29
Thanks for reporting. #31471
