### ISSUE TITLE
Samsung One UI 6.0 (Android 14) black screen after background

### ISSUE THREAD

**Issue by calebisstupid** [flutter/flutter#139814] opened 2023-12-08 17:21 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

We have an issue with an application in production specific to Samsung One UI 6.0 (Android 14). After updating to One UI 6.0, our production Flutter app will turn completely black after being backgrounded for ~5min+. There are no exceptions or errors of any kind, and the moment an OS action is triggered again (i.e. trying to screen record, going back to the app swapper and selecting the app again) it immediately pops in and works fine.

Our application was using Flutter 3.7.8, and I upgraded everything to 3.16.2 (and all packages to current versions) this past week but the issue still exists.

1. Background our production app
2. Wait 5min (or background and open apps until it happens)
3. Open app
4. See entire black screen
5. Start video recording or swap back and forth to the app and things work

I can reproduce this with a sample app. Code below.

This is happening on a physical S22 Ultra, a physical S23 Ultra, and a physical S23+ (using Samsung's Remote Test Lab).

### Expected results

No black screen on resume.

### Actual results

Black screen for indefinite time, until some sort of OS action is taken that suddenly refreshes the screen.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void mainTest() {
  runApp(MyTestApp());
}

class MyTestApp extends StatelessWidget {
  const MyTestApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Namer App',
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepOrange),
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Text('This is a sample app'),
          Container(
            height: 100,
            width: 100,
            color: Colors.green,
          ),
        ],
      ),
    );
  }
}

```
</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/2396384/11b0b66f-5500-4987-9b76-fec22b286a82)
![image](https://github.com/flutter/flutter/assets/2396384/8c801b93-1cd9-468c-9bd1-2fb4c80ab335)

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.22621.2715], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.84.2)
[√] Connected device (4 available)
[√] Network resources
```

</details>

**Comment by johnmccutchan** [comment] 2023-12-08 20:32
Closing as a duplicate of https://github.com/flutter/flutter/issues/139630

**Closed by johnmccutchan** 2023-12-08 20:32 UTC
