### ISSUE TITLE
Allow Flutter to match iOS native fonts

### ISSUE THREAD

**Issue by biild** [flutter/flutter#63507] opened 2020-08-11 18:56 UTC
## Use case

The system font in iOS was changed in iOS 11 from SF UI to SF Pro.  See here:  

https://en.wikipedia.org/wiki/San_Francisco_(sans-serif_typeface)#:~:text=In%20macOS%20High%20Sierra%20and,are%20flat%20in%20SF%20Compact.

Also (first paragraph):

https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography

## Proposal

I would like to see the more modern font become the Flutter default.

**Comment by xster** [comment] 2020-11-02 16:50
SF Pro has always been the Cupertino package's default font. Closing. Please re-open if I misinterpreted.

**Comment by otopba** [comment] 2020-11-28 11:20
@xster You are not right. Now flutter use SF UI, but the font must be SF Pro

**Comment by sanekyy** [comment] 2020-11-28 11:20
Same problem:(

**Comment by xster** [comment] 2020-12-01 07:30
@otopba how are you determining that Flutter's using SF UI? We have a overlay comparison tool with iOS in https://github.com/flutter/platform_tests/tree/master/ios_widget_catalog_compare.

**Comment by sanekyy** [comment] 2020-12-01 11:59
@xster 

In your tests you don't use custom text styles like letterSpacing. There you can notice difference.

**Comment by pedromassangocode** [comment] 2020-12-23 09:16
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by xster** [comment] 2021-01-07 18:01
Actually I'll re-open this. I'm not entirely sure what the issue is yet. But worth checking in various permutations using https://github.com/flutter/platform_tests/tree/master/ios_widget_catalog_compare.

**Comment by thomasmol** [comment] 2022-10-28 14:45
I would like to see this as well. The issue is, I think, is that if you create an flutter app with material widgets, it renders, on default, with the SF UI font on iOS devices. However, if you specifically state in a widget to use ```CupertinoTextThemeData()```, like so for example: ``` Text('Sample text', style: CupertinoTextThemeData().textStyle,)```, it does render with the SF Pro font, which is now the 'correct' font for iOS apps.

**Comment by jetlye2804** [comment] 2022-12-10 15:25
@thomasmol your solution is actually incorrect. The font used in `CupertinoTextThemeData().textStyle` is still using SF UI Text. The spacing between letters are hardcoded.

To make a comparison, I imported both SF Pro Text, SF Pro Display font files into the project folder, and use SF Pro Text, Default font rendered by Flutter in iOS (SF UI Text), and SF Pro Display in three respective texts with the same content.

![IMG_3444](https://user-images.githubusercontent.com/82960491/206862463-29ed4a27-03d2-4d8a-be04-c834128a7fbe.PNG)

**Comment by davidhicks980** [comment] 2023-08-30 05:14
I'm not sure if others have observed this, but I think the current specified fonts don't seem to even exist on iOS. .AppleSystemUIFont does though. When referencing system fonts, I think the font family has to be referenced rather than the font name. I'm brand new to Swift though, so I apologize if I'm wrong.

https://github.com/flutter/flutter/assets/59215665/dfe5cee0-166e-433e-bc56-da4f43a96e14




```swift
      let systemFontName = UIFont.systemFont(ofSize: 17)
      print(systemFontName.fontName, " << Font name")
      print(systemFontName.familyName, " << Font family")
```

```cmd
2023-08-30 01:10:34.973562-0400 Runner[4731:280212] Metal API Validation Enabled
.SFUI-Regular  << Font name
.AppleSystemUIFont  << Font family
2023-08-30 01:10:35.410032-0400 Runner[4731:280513] flutter: The Dart VM service is listening on http://127.0.0.1:57822/_E5Dxfnn434=/
2023-08-30 01:10:35.665484-0400 Runner[4731:280498] flutter: Color(0xffffffff)
```

**Comment by MitchellGoodwin** [comment] 2023-09-06 17:24
Still in the progress of looking into this, but the issue is that Apple removed the ability to look up system fonts by name, so dot prefixed names like '.SF Pro Text' and '.SF Pro Display' fail. We fallback to getting what family name we can, which is ".AppleSystemUIFont", which Apple seems to use for all of their system fonts. Weirdly, that does work, but it only returns what seems to be the equivalent of '.SF Pro Text', never ',SF Pro Display'. I believe in the Apple system fonts there currently is no "SF Pro" or "SF UI" font there's just the "Text" and "Display", so functionally we are getting and using the SF Pro Text font, but it looks wrong on larger texts, which should be using SF Pro Display.

Work in progress design doc: flutter.dev/go/flutter-ios-system-font

**Comment by MitchellGoodwin** [comment] 2023-10-19 17:59
Keeping this open for now. [flutter/engine#46857](https://github.com/flutter/engine/pull/46857) allows for opting in to correctly using the system fonts in a way that's unlikely to get broken by changes made to Apple APIs. Keeping this open until the followup framework PR that is coming that will use it in the default themes for Flutter.

**Closed** 2023-10-19 20:45 UTC
Labels: platform-ios, framework, f: cupertino, a: typography, c: proposal, P1, team-ios, triaged-ios, multiteam-retriage-candidate
