### ISSUE TITLE
Jittery performance on first run of animation/transitions due to shader compilations

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#813] opened 2015-12-08 21:27 UTC
On some apps, the first time you run a "big" animation (like a hero transition), there appears to be some jitter/jank. After the animation is warmed up, it appears to become smoother.

This is a tracking issue to investigate and solve.

**Comment by eseidelGoogle** [comment] 2016-05-13 17:25
Now that --release builds exist and use AOT mode, there should no longer be initial compile jitter?  If you have specific traces happy to look at them!

**Comment by sethladd** [comment] 2017-10-11 03:39
Reopening as this is a systemic issue. Report from our mailing list: "2) First time loading shows lag, but after some time experience becomes smoother." and "Initially home screen lags for the first time only, then it gets smoother" and we recently saw it with a customer's app and their initial onboarding screens (on a Pixel, a modern phone).

**Comment by Hixie** [comment] 2017-12-20 00:48
This is a metabug for tracking these similar issues.

Fixing this is our top performance priority.

Assigning to @cbracken who is currently tasked with investigating this.

**Comment by matharumanpreet00** [comment] 2018-04-01 05:16
Any updates on this ?

**Comment by newfivefour** [comment] 2018-04-10 22:58
I'm on 0.2.8 of the flutter.io Gallery app on the Play Store with a Nexus 4.

The performance degradation between first run and subsequent runs seems almost completely gone compared to previous versions. 

There still seems to be a very, very slight difference between first and subsequent runs but it's very, very, slight to the point where I'm not even sure if it's there after looking at it numerous times.

It's still very choppy on my Nexus 7. But I think that is related to https://github.com/flutter/flutter/issues/11861 Or perhaps tablet specific as I'm not sure Google are testing Flutter on tablets.

**Comment by christian-muertz** [comment] 2018-07-09 12:16
Any update on this?

We want to launch our app soon... This performance issue is critically for us :/

**Comment by liyuqian** [comment] 2018-07-09 15:02
I'm now actively working on this. Will give an update by the end of this week.

**Comment by liyuqian** [comment] 2018-07-10 19:56
As comment https://github.com/flutter/flutter/issues/813#issuecomment-380273787 suggests, this issue was almost gone until we recently introduced a new regression. The newly regressed jank is not caused by the slow performance (so our dashboard doesn't catch it), but by the missing image cache. Please see this footage for more details: https://drive.google.com/open?id=1Y9tETl-Elr8_VAlapTTPqoqGHMJYmo75 . A patch https://github.com/flutter/flutter/pull/19220 is on the way.

Meanwhile, we do have some performance issues caused by Dart garbage collection. But that's not related with the "first run of animation". It's more like a random jank in the middle of some animations.

**Comment by liyuqian** [comment] 2018-07-12 00:02
I'm sorry to hear that @christian-muertz . A video or a reproduction sample app would be very helpful 😃

**Comment by liyuqian** [comment] 2018-07-13 00:13
@christian-muertz Thanks for the information! However, I do need a little bit more information for debugging:

1. Run your app in profile mode `flutter run --profile` (note that the default `flutter run` and the green play triangle in the IDE are running your app in debug mode, and the first animation is definitely going to be very slow in that mode; that slowness should go away once you run in profile or release mode).

2. Manipulate your app until right before you start the first slow animation

3. Go to the observatory web page following the link in the command line (e.g., `An Observatory debugger and profiler on Nexus 5X is available at http://127.0.0.1:38585/`)

4. Click the `timeline` link in the observatory web page.

5. Click the `all` button for `Recorded Streams Profile` on the left so all the check boxes below are checked.

6. Click the `View Options` drop down on the right and check `Flow events` and `Highlight VSync` check boxes.

7. Manipulate your app to start the first slow animation, and probably start a second fast animation

8. Go back to the web page and click `Refresh` button on the top right.

9. Click the `save` button on the top right, and save the current web page as html and send them to us so we can see which things are causing the jank

Finally, a sample app for us to reproduce the problem is also highly useful. If you have some more time after finishing the steps above, please send us a sample app :smile:

**Comment by christian-muertz** [comment] 2018-07-13 13:15
Thanks for your effort. Here are the files!
I will work an sample app and i will send it to you asap :D

**Comment by christian-muertz** [comment] 2018-07-13 14:04
Hmm my sample app has no jank

**Comment by liyuqian** [comment] 2018-07-13 18:32
@christian-muertz : according to the timeline trace you sent, we believe that it's caused by font loading. Can you try to add a few empty paragraphs to your first screen with all the fonts that your app uses, and see if there's still a jank when you start the first animation? Hopefully this will also help you create a sample app to demonstrate the issue.

**Comment by christian-muertz** [comment] 2018-07-14 11:00
Ok now i broke everything 😅 I cant even start our app in profile mode now 😕

`[VERBOSE-3:dart_vm.cc(423)] Error while initializing the Dart VM: Snapshot not compatible with the current VM configuration: the snapshot requires 'product no-type_checks no-asserts no-error_on_bad_type no-error_on_bad_override no-sync_async reify_generic_functions arm64' but the VM has 'release no-type_checks no-asserts no-error_on_bad_type no-error_on_bad_override no-sync_async reify_generic_functions arm64'
`

**Comment by christian-muertz** [comment] 2018-07-14 15:20
Ok problem is gone... Simply changed the app id and the install was successfully...

**Comment by christian-muertz** [comment] 2018-07-14 15:51
Ok removed all fonts from our app. Still having the same jank. Here are my new files!
[Archiv.zip](https://github.com/flutter/flutter/files/2195061/Archiv.zip)

**Comment by liyuqian** [comment] 2018-07-20 20:16
Sorry for the late reply. We've had some merging crisis recently. By looking at your new traces, we don't find anything new. Can you please provide us the "open a cupertino route with an empty scaffold" app source code, and the jank video so we can better understand the problem?

**Comment by Chozzle** [comment] 2018-08-02 07:00
I'll post a video soon @liyuqian. We have this same issue. Performance is also our company's number one issue with flutter.

**Comment by Chozzle** [comment] 2018-08-02 08:26
Here I created an app from the Flutter starter app with a page transition to a blank page with an app bar. You can see that the first animation is worse, then as I go back and forward between pages it improves. Notice that the pop animation is always janky. On a Samsung Note 4 (Exynos).
I've included the observatory output and also a video of the same events.
[dart-timeline-2018-7-2-617.txt](https://github.com/flutter/flutter/files/2252688/dart-timeline-2018-7-2-617.txt)

[https://drive.google.com/file/d/1bxAvFuLAzX-V-c3agshNWUxNCjuEnFkA/view?usp=sharing](url)

Here is the additional code to reproduce the app:
``` 
onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (context) => PageTwo())),
        tooltip: 'Increment',
        child: new Icon(Icons.navigate_next),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Page two'),
      ),
    );
  }
}```

**Comment by liyuqian** [comment] 2018-08-02 21:44
@Chozzle thank you for the report and the really simple reproduction app! This is caused by the first time to compile a GL shader and we had https://github.com/flutter/flutter/issues/14028 filed to solve it.

You can see a more detailed trace by `flutter run --profile --trace-skia`:

![image](https://user-images.githubusercontent.com/22987568/43612855-674dfed2-9662-11e8-8677-28e43ad3a906.png)

**Comment by Chozzle** [comment] 2018-08-08 06:14
@liyuqian. I tried ```MaterialPageRoute.debugEnableFadingRoutes = true;``` and it makes a big improvement to the feel of the app. I might suggest turning that on by default. Here's the video.
[Video](https://drive.google.com/open?id=1hA9f5ThZZwQ4pgzjjZtey3m23rDUk_Ny)

**Comment by liyuqian** [comment] 2018-08-08 17:16
@Chozzle : Yes, with animated opacity, the transition looks much better. We currently don't turn it on because of https://github.com/flutter/flutter/issues/13736 . We've made many progress in the last few months regarding that issue and we're now very close (90%) to our 60fps goal. There's one last step that I plan to finish before October. Let me ask @Hixie to see if we can turn it on a little earlier.

**Comment by liyuqian** [comment] 2018-09-27 22:37
This issue should now be fixed thanks to the closing of https://github.com/flutter/flutter/issues/14028

**Comment by liyuqian** [comment] 2018-12-06 22:35
Reopen as https://github.com/flutter/flutter/issues/14028 has been disabled for stability issues. We'll have a more stable solution soon.

**Comment by uenx** [comment] 2018-12-20 06:55
Vote up. This happens to me everytime I start the Reflecty android app by tapping on its notification

**Comment by liyuqian** [comment] 2018-12-20 23:22
@uenx I'm surprised to learn that the animation is smooth after a restart. Can you provide us the version of Reflectly app and the Flutter version being used in that Reflectly version? The only possible way that I can imagine is that Reflectly uses a Flutter version that has our persistent cache before we reverted it. And somehow each morning our persistent cache is removed somehow?

**Comment by liyuqian** [comment] 2018-12-26 17:43
@uenx : it's probably difficult for us to get that information. Also, your animation issue might be caused by some other reasons that are unrelated with Flutter. For example, the app may initiate a costly network communication every morning that blocks the animation. Therefore, I think it's better to directly contact the reflectly app team about this issue: 
hello@reflectly.app (according to https://reflectly.app/)

**Comment by qwilbird** [comment] 2019-01-16 15:32
+1 Is there an ETA on this issue? We have a big app going in prod soon, and that does not really give a sense of polish...

**Comment by liyuqian** [comment] 2019-01-16 18:06
We're aiming for Q1 2019.

**Comment by miguelpruivo** [comment] 2019-01-27 00:37
+1 on this. I’ve an app that’s going to be released soon and it launches with a loop animation that lags until it first completes the first time. Happens on both release and debug. Not critical but it’s definetely there.

**Comment by filiph** [comment] 2019-02-19 21:49
This is blocking for customer `solaris`.

**Comment by miguelcmedeiros** [comment] 2019-02-25 15:47
I was going to test out the fix (coming from #27660) in my app, but it seems that the changes were reverted (in #28376). 
Is it possible to reopen this issue until final fix lands in master?

**Comment by liyuqian** [comment] 2019-02-25 18:22
Yes, I'll fix the flaky tests soon and reland the PR. Meanwhile, I'll reopen this issue until the reland PR is merged.

**Comment by frasza** [comment] 2019-03-01 09:32
@liyuqian What is current status with this? as owner of iPhone XS, I can feel the performance not being the best when generally scrolling or navigating around - I can feel some FPS drop.
Let me know if I can assist at testing solutions. Would be very happy to help.

**Comment by liyuqian** [comment] 2019-03-01 17:52
If the FPS only drops when the animation first appears and it's smooth afterwards, then it's probably related to this bug. Otherwise, it's probably a different issue (so it's better to post it on another thread).

To help us better fix your performance issue, please
1. Give us your Flutter version: `flutter doctor -v`
2. Run your app on a physical device using profile mode: `flutter run --profile`
3. Take a video of the performance issue so we can have an intuitive understanding of what happened.
4. Show us a screenshot of performance overlay (https://flutter.dev/docs/testing/ui-performance#the-performance-overlay) so we know which thread is causing the issue
5. Open observatory and save a timeline trace of your performance issue and send it to us so we know which functions might be causing the issue (https://medium.com/flutter-io/profiling-flutter-applications-using-the-timeline-a1a434964af3).
   * Depending on the specific issue, we might need a trace with Skia info. You can get that trace with `flutter run --profile --trace-skia`.
6. Construct a single-file minimal Flutter app that can reproduce the issue. That way, we can test our fixes and maybe add it to our continuous performance benchmarks.

**Comment by eseidelGoogle** [comment] 2019-03-07 18:41
@liyuqian has a working solution (via the shader warm-up) for this which he is testing with an internal customer.  I expect we're *finally* close to closing this. :)  Thanks all for your patience.

**Comment by liyuqian** [comment] 2019-03-08 19:25
Can everyone please check your issue with the tip-of-tree master Flutter? Now the shader persistent cache should be turned on by default in both Android (binary cache) and iOS (SkSL cache), and there's a default pre-warm-up that eliminates some common compilations. Hence I expect that most of these issues should have already been solved.

**Comment by msw333** [comment] 2019-03-19 14:50
Unfortunately, this problem is exactly the same on the new master:
https://github.com/flutter/flutter/issues/28113

**Comment by i-schuetz** [comment] 2019-03-19 15:43
See also https://github.com/flutter/flutter/pull/27660#issuecomment-474230411

**Comment by Hixie** [comment] 2019-03-19 23:26
This specific bug was for us to track the performance of the gallery. It is probably best at this point if each occurrence of this gets its own bug with its own small reproducable test case, so we can track each individual cause separately.

**Comment by eseidelGoogle** [comment] 2019-03-29 19:43
Such an anti-climactic ending to a 3.5 year old bug. :)

**Comment by i-schuetz** [comment] 2019-03-29 20:53
I guess it's continued here? 
https://github.com/flutter/flutter/issues/28113
And partly also the discussion at the end of this PR
https://github.com/flutter/flutter/pull/27660

**Comment by liyuqian** [comment] 2019-04-09 17:43
Reopen this issue as there's still ongoing work related with this.

Meanwhile, I've modified the description of this bug to only include first-animation-jank that caused by shader compilations.

Other first-animation-jank (such as font loading) will be tracked in separate issues such as https://github.com/flutter/flutter/issues/28113

**Comment by miguelpruivo** [comment] 2019-04-21 01:47
Thumbs on this. Reported 3 month ago and now the app is already on production and a new one is coming soon with the same issue on iOS.

As soon as it launches there’s jittery in the animations/scroll or overall experience for about 3-4 seconds with an iPhone X. After _warming up_ it’s fine. 

If you run a static screen before anything else for about this same time (eg. an onboarding screen without animations or scrolls), then, afterwards, it will run smoothly. 

Definitely looks like some sort of Skia engine warming up but that only affects in iOS.

**Comment by msw333** [comment] 2019-04-21 08:46
That’s exactly the experience we have. The issue is, that the ‚warming up‘ is also persistent when apps are switched, so a 3-4s (!) onboarding screen has to be shown for every rebuild...

...which makes the entire Flutter framework pretty useless for professional apps right now...we desperately hope for a fix.

**Comment by kf6gpe** [comment] 2019-04-23 23:20
@msw333, @miguelpruivo Have you been able to test your application behavior using the latest in the master channel to see if @liyuqian's work has resolved it?

**Comment by liyuqian** [comment] 2019-04-23 23:56
I haven't uploaded a solution yet. But I've added some tracing as mentioned in https://github.com/flutter/flutter/issues/28113#issuecomment-480618431 . It would be nice if you can trace your performance issues with master channel and see if the font loading is the cause.

**Comment by miguelpruivo** [comment] 2019-04-24 01:11
@kf6gpe I’m sitting at 1.5.3 @ dev. When was it synced with master? Anyhow, I’m looking to release an app with this issue (if not fixed until then) early next month. 

Fingers crossed for a solution on this. It always look like the app is doing some heavy task in those little seconds.

**Comment by liyuqian** [comment] 2019-04-24 17:07
@miguelcmedeiros : v1.5.3 should have the added trace events. Can you please follow https://github.com/flutter/flutter/issues/813#issuecomment-468751700 (especially item 5) to capture a trace of your issue so we can figure out how to help you?

**Comment by yunyu** [comment] 2019-04-25 18:15
@liyuqian I'm not sure if this is the correct place to post this, but here is a ~200 LoC single file example which exhibits the issue (as well as #28113 and #31086) on iOS but works fine on Android (with `android.permission.INTERNET`): https://github.com/yunyu/flutter_scroll_stutter_test/blob/master/lib/main.dart

**Comment by miguelpruivo** [comment] 2019-04-27 01:24
Noticed that this also happens when the iPhone is in lower power mode. It completely jitters scroll and animations.

**Comment by liyuqian** [comment] 2019-04-29 22:40
@yunyu : Thank you very much for your example app! I did reproduced the stutter on an iPhone X, and it didn't stutter on an iPhone 6S. I checked the trace and it's not related to the shader compilations of this issue so I'll route the discussion to https://github.com/flutter/flutter/issues/31086#issuecomment-487768379

**Comment by liyuqian** [comment] 2019-05-01 00:16
I'm closing this bug since all new complaints here seem to be unrelated with our original issue. I created a new issue https://github.com/flutter/flutter/issues/31881 for our original task of improving flutter_gallery's shader compilation jank. Other iOS related first animation jank issues should be routed to either https://github.com/flutter/flutter/issues/28113 or https://github.com/flutter/flutter/issues/31086. If both of them don't seem to be the issue that you had, please feel free to create a new issue.

**Closed by liyuqian** 2019-05-01 00:16 UTC
Labels: customer: solaris, engine, framework, severe: customer critical, severe: performance, waiting for customer response

**Comment by shinayser** [comment] 2019-05-28 15:07
I am experiencing this problem on current production app (flutter v1.5.4). The first time my animations run janky, then it runs smooth.
Both **Android** and `iOS`.

**Comment by michinchin** [comment] 2019-06-20 20:32
Experiencing this specifically with hero animations. Other animations seem to run smooth. However, initial hero animation is a bit janky

**Comment by arsen** [comment] 2019-06-20 20:47
Same for me, initial run of a hero animation is missing frames.

**Comment by miguelpruivo** [comment] 2019-06-20 21:01
It seems to happen with _all_ animations at start of an iOS app and/or reloading from background. It’s 2/3 seconds janky and then smooth until closed and reopen again. You can replicate it everytime in an iPhone X (at least).

**Comment by michinchin** [comment] 2019-06-20 21:09
Anyone find a fix? Or a workaround for this?

**Comment by michinchin** [comment] 2019-06-20 21:17
Found it lags for the first time on both Android and iOS initial start up

**Comment by liyuqian** [comment] 2019-06-20 21:21
We're coming up with a long-term solution for this and that progress is tracked publicly on https://github.com/flutter/flutter/issues/32170 . Currently, we have a 16-page internal draft design doc with 9 different proposed solutions in it.

In shorter terms, we believe that there might be some specific issues that we can quickly solve just for iPhone X since the issue seems to be less bad on older iPhones. We're currently purchasing iPhone X to add to our device lab so we can debug the performance of iPhone X: https://github.com/flutter/flutter/issues/34590

**Comment by michinchin** [comment] 2019-06-20 21:23
> #32170

This is not only an issue on the iPhone X. We have done testing on the Pixel 3 and other android devices and have found the same effect.

**Comment by liyuqian** [comment] 2019-06-20 21:37
@michinchin : we're aware of that hence https://github.com/flutter/flutter/issues/32170 is not just for iOS, but also for Android, Fuchsia, Desktop, and probably all platforms that Flutter directly compiles into binaries.

iOS currently just has additional issues. For example, we can store binary persistent shader cache on Android, but we can only store GLSL persistent shader cache on iOS. That requires iOS to do one more compilation (compared to Android). For that, we're also enabling Metal backend for iOS which should help this specific issue.

**Comment by miguelpruivo** [comment] 2019-06-20 22:09
@liyuqian thank you for the updates. Currently (and because I’m an iPhone X user) I immediately noticed it and I must say that despite of being an issue already tracked, it bothers me somehow to have a production app that launches on a scroll screen where it _always_ feel janky as the user starts it on iPhone for the first 2 seconds.

Oddly and in my experience, it seems to affect only the iOS. Android devices were I’ve tested it, seem to be good and smooth right from the launch point.

**Comment by liyuqian** [comment] 2019-06-20 22:15
@miguelcmedeiros : that's exactly the difference between binary persistent shader cache and GLSL persistent shader cache. On Android, there's 0 work if you close the app and re-open the app. On iOS, re-opening the app triggers another GLSL to binary compilation.

**Comment by miguelpruivo** [comment] 2019-06-21 00:00
@liyuqian got it. Do you have an idea of when a fix may be available? Have you already found a solution for it or still drafting for?

PS: You've tagged the wrong person. 😄

**Comment by liyuqian** [comment] 2019-06-21 00:08
Oops. We haven't picked which solution to pursue. Will update https://github.com/flutter/flutter/issues/32170 with some proper time estimation once we made the decision.

**Comment by erf** [comment] 2020-03-08 01:17
@liyuqian Any news on this?

I'm experiencing jaggy animations every first time i do:
```
Navigator.push(MaterialPageRoute(fullscreenDialog: true, builder: (context) => SomePage()));
```
Second time i open a page, it' much smoother.

I'm on an iPhone 7.

```
flutter --version
Flutter 1.15.18 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 9437639590 (31 hours ago) • 2020-03-06 10:24:23 -0800
Engine • revision 5aff311948
Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
```

**Comment by liyuqian** [comment] 2020-03-10 18:09
@erf : we're actively working on SkSL shader warm-up. Some preliminary results on iOS should be available in 1-2 months.

**Comment by liyuqian** [comment] 2020-03-26 00:51
For progress, please check https://github.com/flutter/flutter/issues/32170 . We'll be referencing it when we're making smaller fixes.

**Comment by erf** [comment] 2020-03-30 10:45
@liyuqian i feel the performance has been improved in the latest dev version 1.16.3 ..?

**Comment by liyuqian** [comment] 2020-03-30 18:06
@erf : it's nice to hear that! We're always working hard to improve the performance. While https://github.com/flutter/flutter/issues/32170 isn't fixed yet, we've made at least 13 other quantified improvements between Sep 2019 and Dec 2019.
