### ISSUE TITLE
[web] scroll using desktop keyboard arrow keys

### ISSUE THREAD

**Issue by bhaskar8088** [flutter/flutter#58243] opened 2020-05-29 13:38 UTC
Hi, is it possible to scroll using desktop keyboard arrow keys in flutter web. I tried but couldnt. But I can scroll mouse left button and drag and using mouse wheel.

Here is my flutter doctor -v

```
bhaskar > flutter doctor -v
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Linux, locale en_IN)
    • Flutter version 1.19.0-1.0.pre at /home/bhaskar/flutter
    • Framework revision 456d80b9dd (3 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/bhaskar/Android/Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /home/bhaskar/Android/Sdk
    • Java binary at: /home/bhaskar/Desktop/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.4)
    • Android Studio at /home/bhaskar/Desktop/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

! Doctor found issues in 1 category.

```

Here is the sample code:

```
import 'package:flutter/material.dart';

class TestScrollWidget extends StatefulWidget {
  @override
  _TestScrollWidgetState createState() => _TestScrollWidgetState();
}

class _TestScrollWidgetState extends State<TestScrollWidget> {

  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
          return SingleChildScrollView(

              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Image.asset("lib/assets/img/1024x500.png"),
                  Image.asset("lib/assets/img/1024x500.png"),
                  Image.asset("lib/assets/img/1024x500.png"),
                  Image.asset("lib/assets/img/1024x500.png"),
                ],
              )
            );
  }
}


```

Can I use flutter web in production or any issues?

**Comment by bhaskar8088** [comment] 2020-05-30 05:50
Desktop means, in a browser of a laptop I mean :) Wanted to know if scrollling using keyboard arrow keys work or not in a browser of laptop.

**Comment by bhaskar8088** [comment] 2020-06-02 12:12
@VladyslavBondarenko May I know how many months or years it might (just a guess) take for flutter to be production ready for a web application. Our web app is used by many so wanted to check this. I have been building like lots of forms for various insurances. Initially I used flutter because I needed flutter mobile and web. But now, our requirement is only for web, but we still flutter web but worried about stability and comfort scrolling. If I know how many years it might take for it to be production ready, I can make plans accordingly.

**Comment by VladyslavBondarenko** [comment] 2020-06-02 12:50
@bhaskar8088 
I added `a: desktop` because if you build a desktop app, you can't scroll there by keyboard arrows as well.

I can't guess estimates, I'm doing only initial issue triage. 
These links may be useful:
https://flutter.dev/docs/development/platform-integration/web
https://medium.com/flutter/flutter-web-support-updates-8b14bfe6a908
https://stackoverflow.com/questions/61558794/should-i-use-flutter-web-for-a-website-project-that-shall-go-into-production-not

**Comment by yjbanov** [comment] 2020-06-04 22:20
This looks like a duplicate of https://github.com/flutter/flutter/issues/43694

**Closed by yjbanov** 2020-06-04 22:20 UTC
Labels: a: desktop, f: scrolling, framework, platform-web, severe: new feature
