### ISSUE TITLE
Unable to run release APK

### ISSUE THREAD

**Issue by Akshiiitsaxena** [flutter/flutter#118156] opened 2023-01-08 12:46 UTC
## Steps to Reproduce

1. Execute `flutter build APK`

I am unable to **run** or **build** a release/profile APK

`flutter run` and `flutter build apk --debug` **work as expected**

The output of `flutter build apk` gets stuck at
`Running Gradle task 'assembleRelease'...`

Running `flutter run --release -vv` gets stuck at
```
[+1994 ms] > Task :app:compileFlutterBuildRelease
[        ] Caching disabled for task ':app:compileFlutterBuildRelease' because:
[        ]   Build cache is disabled
[        ] Task ':app:compileFlutterBuildRelease' is not up-to-date because:
[        ]   Value of input property 'dartDefines' has changed for task ':app:compileFlutterBuildRelease'
[        ]   Value of input property 'fileSystemScheme' has changed for task ':app:compileFlutterBuildRelease'
[        ]   Value of input property 'targetPath' has changed for task ':app:compileFlutterBuildRelease'
[        ] Starting process 'command '/Users/akshit-saxena/Dev/flutter/bin/flutter''. Working directory: /Users/akshit-saxena/MealGuide/mealguide
Command: /Users/akshit-saxena/Dev/flutter/bin/flutter --quiet assemble --no-version-check --depfile
/Users/akshit-saxena/MealGuide/mealguide/build/app/intermediates/flutter/release/flutter_build.d --output
/Users/akshit-saxena/MealGuide/mealguide/build/app/intermediates/flutter/release -dTargetFile=/Users/akshit-saxena/MealGuide/mealguide/lib/main.dart
-dTargetPlatform=android -dBuildMode=release -dTrackWidgetCreation=true --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==
android_aot_bundle_release_android-arm64
[        ] Successfully started process 'command '/Users/akshit-saxena/Dev/flutter/bin/flutter''
```

Output of `flutter doctor -v`:

```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.5.1 21G83 darwin-arm, locale en-IN)
    • Flutter version 3.3.10 on channel stable at /Users/akshit-saxena/Dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (3 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/akshit-saxena/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • Pixel 7 (mobile) • 29211FDH2008YW • android-arm64 • Android 13 (API 33)
    • macOS (desktop)  • macos          • darwin-arm64  • macOS 12.5.1 21G83 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

Contents of `android/build.gradle`

```
buildscript {
    ext.kotlin_version = '1.6.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.2'
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.10'
        // END: FlutterFire Configuration
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

Contents of `android/gradle/wrapper/gradle-wrapper.properties`

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip
```

**Comment by yusuff122** [comment] 2023-01-08 12:57
flutter build apk --release,  try this

**Comment by yusuff122** [comment] 2023-01-08 12:59
You can find the solution https://stackoverflow.com/questions/49874194/flutter-build-apk-on-release-mode-cannot-generate-updated-version from this link.

**Comment by Akshiiitsaxena** [comment] 2023-01-08 13:11
> flutter build apk --release, try this

I've tried this, the output is stuck at
`Running Gradle task 'assembleRelease'...`

**Comment by MerdanDev** [comment] 2023-01-08 17:14
@Akshiiitsaxena can you build release apk for other projects?
And can you show app level build.gradle for minSdk and targetSdk versions, and packages you are using as flutter dependencies because they maybe cause for your problem.

**Comment by Akshiiitsaxena** [comment] 2023-01-09 06:59
> @Akshiiitsaxena can you build release apk for other projects? And can you show app level build.gradle for minSdk and targetSdk versions, and packages you are using as flutter dependencies because they maybe cause for your problem.

yes, I am able to build release APK for other projects. 

this is android/app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
// START: FlutterFire Configuration
apply plugin: 'com.google.gms.google-services'
// END: FlutterFire Configuration
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
   def keystorePropertiesFile = rootProject.file('key.properties')
   if (keystorePropertiesFile.exists()) {
       keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
   }


android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.mealguide.nutrify"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
   }
   buildTypes {
       release {
           signingConfig signingConfigs.release
       }
   }

    // buildTypes {
    //     release {
    //         // TODO: Add your own signing config for the release build.
    //         // Signing with the debug keys for now, so `flutter run --release` works.
    //         signingConfig signingConfigs.release
    //         shrinkResources false
    //         minifyEnabled false
    //     }
    // }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```


These are the dependencies

```
environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.4
  sizer: ^2.0.15
  cached_network_image: ^3.2.3
  fraction: ^4.1.4
  persistent_bottom_nav_bar_v2: ^4.2.6
  intl: ^0.17.0
  hive: ^2.2.3
  path_provider: ^2.0.11
  scrollable_positioned_list: ^0.3.5
  dio: ^4.0.6
  syncfusion_flutter_sliders: ^20.4.38
  syncfusion_flutter_core: ^20.4.38
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  pin_code_fields: ^7.4.0
  percent_indicator: ^4.2.2
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.2
```

**Comment by huycozy** [comment] 2023-01-09 09:29
@Akshiiitsaxena Please share the complete output of `flutter run --release -v` so that we may verify the issue. If the log is too long, please save it into a file and attach it here. Thanks!

**Comment by Akshiiitsaxena** [comment] 2023-01-09 10:05
> @Akshiiitsaxena Please share the complete output of `flutter run --release -v` so that we may verify the issue. If the log is too long, please save it into a file and attach it here. Thanks!

`flutter run --release -v` never completes, it gets stuck at this stage, I have had it running for 1+ hours:

```[+1894 ms] > Task :app:compileFlutterBuildRelease
[        ] Caching disabled for task ':app:compileFlutterBuildRelease' because:
[        ]   Build cache is disabled
[        ] Task ':app:compileFlutterBuildRelease' is not up-to-date because:
[        ]   Task has failed previously.
[        ] Starting process 'command '/Users/akshit-saxena/Dev/flutter/bin/flutter''. Working directory: /Users/akshit-saxena/MealGuide/mealguide Command:
/Users/akshit-saxena/Dev/flutter/bin/flutter --quiet assemble --no-version-check --depfile /Users/akshit-saxena/MealGuide/mealguide/build/app/intermediates/flutter/release/flutter_build.d
--output /Users/akshit-saxena/MealGuide/mealguide/build/app/intermediates/flutter/release -dTargetFile=/Users/akshit-saxena/MealGuide/mealguide/lib/main.dart -dTargetPlatform=android
-dBuildMode=release -dTrackWidgetCreation=true --DartDefines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== android_aot_bundle_release_android-arm64
[        ] Successfully started process 'command '/Users/akshit-saxena/Dev/flutter/bin/flutter''
```


Here is an output file with the complete output until this stage.
[release-v-output.txt](https://github.com/flutter/flutter/files/10372155/release-v-output.txt)

**Comment by MerdanDev** [comment] 2023-01-09 13:19
@Akshiiitsaxena I think your problem is in flutter_native_timezone package as [release-v-output.txt](https://github.com/flutter/flutter/files/10372155/release-v-output.txt) has lines in which written *'Registrar' is deprecated. Deprecated in Java*. 
Can you try building release apk without this package?

**Comment by huycozy** [comment] 2023-01-10 04:35
`flutter_native_timezone` may be the cause of the issue. 
@Akshiiitsaxena: you may try @MerdanDev 's suggestion to see if it works.

**Comment by Akshiiitsaxena** [comment] 2023-01-10 07:47
> `flutter_native_timezone` may be the cause of the issue. @Akshiiitsaxena: you may try @MerdanDev 's suggestion to see if it works.

I did remove that but it still did not work, oddly enough the problem was in one of the `.dart` files
I had a huge json (4MB+) that was in a dart file as `data.dart` 
which had a variable `var data = <huge JSON>` and that is how I was reading it in the app.

And it seemed to have no problems in the debug version but wouldn't compile the release/profile versions.

Anyway I have added it now as an asset with a `.json` file ext. And reading it asynchronously parsing the asset first, and now it works fine now.

**Comment by MerdanDev** [comment] 2023-01-10 08:33
Hey @huycozy how do you think? 
I think it's not flutter sdk reletad issue, sounds like more his project issue.

**Comment by huycozy** [comment] 2023-01-11 03:09
>I think it's not flutter sdk reletad issue, sounds like more his project issue.

It might be, but we still need to confirm whether the issue can be reproducible with a sample code if any.

> Anyway I have added it now as an asset with a .json file ext. And reading it asynchronously parsing the asset first, and now it works fine now.

It seems you solved the issue now, right? If so, feel free to close the issue. Thanks!

**Closed** 2023-01-11 10:39 UTC
Labels: waiting for customer response, in triage
