### ISSUE TITLE
[google_sign_in] Login Consent Screen Stuck in an endless loop

### ISSUE THREAD

**Issue by EchoShao8899** [flutter/flutter#89291] opened 2021-09-01 12:27 UTC
This issue is identical to #86785. I meet the same problem again, since that thread was closed, I open a new issue here.

I'm doing Google Cloud integration with flutter and now I use firebase to register my app. Everything works fine on iOS, but on Android, the login consent screen fails to show up after selecting the user account in an endless loop. Sometimes, the login process is successful, but there is no login consent screen asking users for permission which is also abnormal.

<img src="https://user-images.githubusercontent.com/67158122/131670769-d8cbe8ec-be57-4bd5-83b0-9e0626e813b2.png" height="450" />	

My operations are as follows:
1. Create a firebase project and add my app.
![image](https://user-images.githubusercontent.com/67158122/131669149-a4629ff4-b125-454c-8b66-7cbb108aac51.png)

2. Enable the Google Cloud API and Google Cloud JSON API on Google Cloud console.
3. Use codes like this to login.

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;
  late GoogleSignInAccount? _account;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
    signIn();  // Press the floating button to sign in
  }

  Future signIn() async {
    widget._account = await GoogleSignInApi.login();
    print(widget._account!.displayName);
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        leading: IconButton(
          icon: Icon(Icons.exit_to_app),
          onPressed: () async{
            await GoogleSignInApi.logout();
            print("logout successfully!");
          },
        ),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


class GoogleSignInApi {
  static final _googleSignIn = GoogleSignIn(scopes: <String>[
    'https://www.googleapis.com/auth/devstorage.read_write'
  ]);

  static Future<GoogleSignInAccount?> login() => _googleSignIn.signIn();

  static Future logout() => _googleSignIn.disconnect();
}
``` 
	
</details>

Personally, I think the code is correct because there is no problem on iOS. And I'm wondering if this is related to the setting of "OAuth consent screen" because when I change the publishing status to 'testing', there is no problem with Android. Since Google Cloud storage is a sensitive API scope and my app is still in developing stage, I haven't verified my app yet. I'm not sure if this is the problem. 
![image](https://user-images.githubusercontent.com/67158122/131670476-6996ea7c-3428-4fc1-80bc-2174b635d9c9.png)

Thank you so much if you can have a look at this problem on Android.

P.S. Here is the results of flutter doctor. I paste it here, in case it is needed.

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.1)
[✓] Connected device (4 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-09-02 08:07
Hi @EchoShao8899 
I have the same APIs enabled already, never had this issue.
![image](https://user-images.githubusercontent.com/48603081/131806624-079a6d85-d9e3-4677-b759-1b5d10ed4d47.png)

![image](https://user-images.githubusercontent.com/48603081/131806650-a9375686-7212-49b7-99fd-365c3d163071.png)

> , the login process is successful, but there is no login consent screen asking users for permission which is also abnormal.


Can you please try disabling these APIs,  let me know if you can login consistently?

**Comment by EchoShao8899** [comment] 2021-09-02 09:48
Thanks for your reply!
After disabling these two APIs, I can still login on both Android and iOS. This time, on both two platforms, the OAuth consent screen doesn't show and I haven't meet the endless loop in my trials. I think this is still strange because the app should ask for user's permission to use the scopes.

I clear up the user data on the simulator and this is the whole login procedure I experienced after disabling those APIs. You can see I sign in successfully after entering my user name and my password but there is no consent screen.
![image](https://user-images.githubusercontent.com/67158122/131822002-657b143f-7d6e-466f-bc7c-3ec867bc7443.png)
![image](https://user-images.githubusercontent.com/67158122/131822091-35d29284-38bd-43e5-8c52-347818fe2e5c.png)
![image](https://user-images.githubusercontent.com/67158122/131822166-603dd2e2-c4a5-417b-8773-1097cb0a540e.png)
![image](https://user-images.githubusercontent.com/67158122/131822255-471bd10e-0e97-4ea9-b1e5-ce5728735ff8.png)
![image](https://user-images.githubusercontent.com/67158122/131822413-e2ff6151-6ac9-4d96-b6e3-a622ca4c76ba.png)

**Comment by TahaTesser** [comment] 2021-09-03 06:58
@EchoShao8899 

> I clear up the user data on the simulator and this is the whole login procedure I experienced after disabling those APIs. You can see I sign in successfully after entering my user name and my password but there is no consent screen.


Can you please repeat the steps with both APIs enabled now? Try different devices or emulators, make it is not specific to a device or emulator

**Comment by EchoShao8899** [comment] 2021-09-03 07:07
I just tries the logging procedure again still with both APIs disabled. On Android device, it stuck in an endless loop again and on iOS, everything goes on well with the consent screen appear. 

I'm dubious if the problem is related to Google service backend. But I'll do the experiments as you suggested, thanks for your timely help!

**Comment by TahaTesser** [comment] 2021-09-03 10:20
Hi @EchoShao8899 
Since the issue reproduces on your side, are you familiar with Android development, it will require only a few and you can copy this code [sample](https://gist.github.com/ianbarber/5170508), see if it is a native Android app without this Flutter packages has the issue?

**Comment by EchoShao8899** [comment] 2021-09-07 08:49
Sry, I'm not familiar with Android development. I'm still trying to figure out how to test this code sample.

**Comment by TahaTesser** [comment] 2021-09-07 12:44
@EchoShao8899 
Let me know if you find any more information

**Comment by TahaTesser** [comment] 2021-09-29 11:50
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-29 11:50 UTC
