### ISSUE TITLE
Inconsistant rendering of list of Card with FlatButton (vanishing shadows)

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#1246] opened 2016-01-14 21:25 UTC
On the alpha branch with e20ef502215ba25bfa2f63def287ea233ff0f9c8

The following code create a list of 4 cards. When the child of each Card is a Text the rendering of Card are correct. If I insert a FlatButton then only the first element of the list is rendered like a Card. The next elements are displayed without borders.

```dart
import 'package:flutter/material.dart';

void main() {
  createButton(String text) => new Card(
      child: new FractionallySizedBox(
          width: 1.0,
          child: new FlatButton(child: new Text(text)))); // Problem
          //child: new Text(text))); // Ok
  runApp(new MaterialApp(routes: {
    '/': (RouteArguments args) => new Scaffold(
        toolBar: new ToolBar(center: new Text('Test')),
        body: new Column([
          createButton('a'),
          createButton('b'),
          createButton('c'),
          createButton('d'),
        ], justifyContent: FlexJustifyContent.spaceAround)),
  }));
}
```

**Comment by Hixie** [comment] 2016-01-14 21:30
cc @abarth in case this is compositor-related

**Comment by abarth** [comment] 2016-01-15 00:01
I'll take a look.  Would be interesting to know if its fixed on the master branch.

**Comment by a14n** [comment] 2016-01-20 07:54
bug still there in the last alpha update 548dbf08701dec7673f8c3bd7a58848df21db9b8

**Comment by abarth** [comment] 2016-01-20 16:02
Thanks.  I'll take a look.

**Comment by sethladd** [comment] 2016-01-20 17:06
Thanks for the report!

**Comment by Hixie** [comment] 2016-02-25 22:04
dupe of https://github.com/flutter/flutter/issues/1576

**Closed by Hixie** 2016-02-25 22:04 UTC
Labels: adoption blocker, ⚠ bug
