### ISSUE TITLE
allow chained futures to be created immediately

### ISSUE THREAD

**Issue by Fnalsk** [flutter/flutter#80833] opened 2021-04-21 00:29 UTC
## Use case

I have:

```
List<Future> lst = [];
lst.add(
    somethingThatReturnsAFuture().then((){
        //do stuff here
    })
);
```

The intent of the above code snippet is to add the future corresponding to the `then` call to the list of futures.

However this future does not get added to the list until `somethingThatReturnsAFuture()` completes successfully. So if somewhere else in the code you have something like `await lst.first`, you may encounter an exception because lst doesn't actually have any futures in it.

## Proposal

I think it would make sense if the future that corresponds to `then` is added to lst right away, even though it itself cannot get started until `somethingThatReturnsAFuture()` completes. To do this would require "chained" futures to all be created immediately. The workaround that I see in the current state of flutter is for you to first ensure that `somethingThatReturnsAFuture()` has completed, and only then add the future you're actually interested in to the list, which isn't as clean.

**Comment by pedromassangocode** [comment] 2021-04-21 08:15
Hi @Fnalsk 
From what I can see, the issue is related to Dart rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/dart-lang/sdk/issues).

I think `Future.wait(futures)` is what you are looking for.

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-04-21 08:15 UTC
Labels: in triage
