### ISSUE TITLE
Object comparison gives different result in Debug and Release/Profile modes

### ISSUE THREAD

**Issue by deepak786** [flutter/flutter#113045] opened 2022-10-06 17:04 UTC
The object comparison in debug and release/profile mode is giving different results.

<details>
<summary>Reproducible code</summary>

```dart
import 'package:flutter/material.dart';

class StateObject {
  final TextStyle titleStyle;

  final TextStyle subTitleStyle;

  final Widget? trailing;

  const StateObject._({
    this.titleStyle = const TextStyle(color: Colors.black),
    this.subTitleStyle = const TextStyle(color: Colors.black26),
    this.trailing,
  });

  static const StateObject s1 = StateObject._(trailing: Text("Hello"));

  static const StateObject s2 = StateObject._(trailing: Text("Hello"));

  static const StateObject s3 = StateObject._();

  static const StateObject s4 = StateObject._();
}

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(),
        body: Center(
          child: ElevatedButton(
            child: Text("Press"),
            onPressed: () {
              // true in release/profile mode
              // false in debug mode
              // TODO: Why it has different result in debug and release/profile?
              print("s1 == s2: ${StateObject.s1 == StateObject.s2}");

              // false in release/profile mode
              // false in debug mode
              print("s2 == s3: ${StateObject.s2 == StateObject.s3}");

              // true in release/profile mode
              // true in debug mode
              print("s3 == s4: ${StateObject.s3 == StateObject.s4}");

              // false in release/profile mode
              // false in debug mode
              print("s1 == s4: ${StateObject.s1 == StateObject.s4}");
            },
          ),
        ),
      ),
    );
  }
}


```

</details>

**Reproducible Steps:**
1. Run the code sample in debug mode `flutter run`.
2. Run the code sample in release/profile mode `flutter run --profile` or `flutter run --release`.
3. Observe the results from both above steps by clicking the "Press" button. The comparison of s1 and s2 is different in debug and release/profile mode.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.3.1 21E258 darwin-x64, locale
    en-US)
    • Flutter version 3.3.3 on channel stable at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (8 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/appleapple/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Deepak’s iPhone (mobile) • 00008101-00117D690A80801E • ios            •
      iOS 15.5 19F77
    • macOS (desktop)          • macos                     • darwin-x64     •
      macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)             • chrome                    • web-javascript •
      Google Chrome 106.0.5249.103

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-10-07 12:19
Hello @deepak786. Which platforms are you testing on?

**Comment by deepak786** [comment] 2022-10-07 12:20
@exaby73 I have tested on the Web and Android.

**Comment by exaby73** [comment] 2022-10-07 14:35
## Triage report

I can reproduce this on Web. Currently my physical android device is not with me so I cannot confirm the issue on Android. Though on Windows, I couldn't reproduce this issue as well. 

This may be related to the dart2js compiler and the Dart SDK repo might be a better place to raise this issue. But since this issue is related to the different build modes Flutter provides, I am labelling this issue.

**Comment by alexmarkov** [comment] 2022-10-07 15:04
This is likely because of the [widget creation tracking](https://docs.flutter.dev/development/tools/devtools/inspector#track-widget-creation) in debug mode. `s1`/`s2` objects involve `Text` widgets which have distinct source locations and thus not equal.

See https://docs.flutter.dev/testing/debugging#widgets-marked-const-that-should-be-equal-to-each-other-arent for details.

**Comment by exaby73** [comment] 2022-10-07 18:56
@alexmarkov Thank you for the clarification :). Can this issue be closed since this is working as expected or is this considered a bug?

**Comment by alexmarkov** [comment] 2022-10-10 12:08
Yes, we can close this issue. Please open another issue against documentation if you have any suggestions on how to improve the documentation about this subtle behavior or make it more discoverable.

**Closed by alexmarkov** 2022-10-10 12:08 UTC
Labels: engine, dependency: dart, has reproducible steps, found in release: 3.3, found in release: 3.4
