### ISSUE TITLE
How to manage state of Stateless Widget

### ISSUE THREAD

**Issue by marobr001** [flutter/flutter#39612] opened 2019-08-31 09:29 UTC
Hi, I'm working on a weather forecast app - [Source Code](https://github.com/marobr001/weather_app), where I use *CustomScrollView* Widgets as Hourly and Daily forecast, switched by *BottomAppBar*. The problem is, when I want to change the city (FloatingActionButton triggers new page with *TextField*), *CustomScrollView* doesn't update. **I have it defined as Stateless Widget, because Scaffold's body property cannot take Stateful.** 

Do You have any suggestions?

**Comment by alexpavelm** [comment] 2019-08-31 16:37
Not sure if this fixes it, but here's how i would solve it:
Create a StatefulWidget that just returns a State:

```
class MyScrollViewWidget extends StatefulWidget {
  String text;

  MyScrollViewWidget(this.text);

  @override
  State<StatefulWidget> createState() {
    return MyScrollView(text);
  }
```

And i would change your MyScrollView as follows:

`class MyScrollView extends State<StatefulWidget> {`

And now every call you had for MyScrollView you replace with your StatefulWidget.

I would recommend watching a really good video on managing states by Dart devs(or any other, this is the one i remember): https://www.youtube.com/watch?v=d_m5csmrf7I

**Comment by keshava19** [comment] 2019-08-31 21:11
This is a more appropriate question for stack-overflow, you should post it over there.

**Comment by marobr001** [comment] 2019-09-01 11:56
@keshava19 I have already tried my luck there...

**Comment by marobr001** [comment] 2019-09-01 12:17
@alexpavelm Thanks, something is happening now - I see that ScrollView redraws, but the values stay the same... What could be the problem with that?

**Comment by alexpavelm** [comment] 2019-09-01 17:35
It's probably redrawing the list with default values because you don't actually modify them when you switch city. Follow your values through the code, starting from the button that triggers the city change and see if it changes what you actually want. 

I suggest doing state management correctly, as shown in that video I've linked above and then check where the problem is - redrawing everytime might be one of the problems.

**Comment by marobr001** [comment] 2019-09-01 18:26
I'm really not sure, because _changeCity() method when called (after button press) modifies the values. The ScrollView just ignores it.

**Comment by alexpavelm** [comment] 2019-09-01 19:35
You have to keep your data inside the parent widget, because your CustomScrollView rebuilds itself everytime (this is why i recommend you to do the states management properly); or global for an easy fix **only** to see if it works, but again, not good code practice.

**Comment by BondarenkoStas** [comment] 2019-09-02 14:37
Thank you @alexpavelm !
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. @marobr001 see also https://flutter.dev/community for support options, hope you find a way to solve your issue.

**Closed by BondarenkoStas** 2019-09-02 14:37 UTC
