### ISSUE TITLE
My app stuck on splash screen (IOS 13 device) 

### ISSUE THREAD

**Issue by 2013abdullah1** [flutter/flutter#43409] opened 2019-10-24 07:27 UTC
when I use firebase in my app not working
My app stuck on splash screen (IOS 13 device) after updating to xcode 11 without showing any error in logs !!.

- [flutter run 
 
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           3.7s
 └─Compiling, linking and signing...                        15.8s
Xcode build done.                                           130.4s
Configuring the default Firebase app...
        path: satisfied (Path is satisfied), interface: en0, expensive
        path: satisfied (Path is satisfied), interface: en0, expensive
        path: satisfied (Path is satisfied), interface: en0, expensive
Configured the default Firebase app __FIRAPP_DEFAULT.
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:73:7)
#1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:86:4)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
<asynchronous suspension>                                               
#4      MethodChannel.invokeMapMethod (package:f<…>                     
flutter: Overflow on channel: flutter/lifecycle.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
flutter: Overflow on channel: flutter/lifecycle.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
        [C1.1 8A029A22-F19E-4618-8708-21906DEFB7DB 172.20.10.5:55210<->216.58.207.106:443]
        Connected Path: satisfied (Path is satisfied), interface: en0, expensive
        Duration: 0.845s, DNS @0.002s took 0.073s, TCP @0.077s took 0.151s, TLS took 0.305s
        bytes in/out: 5103/1379, packets in/out: 9/11, rtt: 0.159s, retransmitted packets: 0, out-of-order packets: 0
        [C2.1 CDAF9B4F-D764-485F-9542-CC98EE518B62 172.20.10.5:55213<->216.58.207.106:443]
        Connected Path: satisfied (Path is satisfied), interface: en0, expensive
        Duration: 0.774s, DNS @0.000s took 0.002s, TCP @0.003s took 0.153s, TLS took 0.346s
        bytes in/out: 5145/1348, packets in/out: 9/10, rtt: 0.151s, retransmitted packets: 0, out-of-order packets: 0
Syncing files to device iPhone 11 Pro Max...                            
 2,140ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on iPhone 11 Pro Max is available at: http://127.0.0.1:55208/P3E46Sh_vyk=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
        [C3.1 2580B6EB-78FD-4CB4-ACE4-8B311F79DE5C 172.20.10.5:55938<->172.217.19.14:443]
        Connected Path: satisfied (Path is satisfied), interface: en0, expensive
        Duration: 0.959s, DNS @0.001s took 0.003s, TCP @0.004s took 0.182s, TLS took 0.333s
        bytes in/out: 4230/1068, packets in/out: 8/9, rtt: 0.304s, retransmitted packets: 0, out-of-order packets: 0
        [C4.1 0D81A6A0-605F-4178-8FFF-3629B775EF90 172.20.10.5:55939<->172.217.19.14:443]
        Connected Path: satisfied (Path is satisfied), interface: en0, expensive
        Duration: 0.921s, DNS @0.000s took 0.002s, TCP @0.003s took 0.188s, TLS took 0.331s
        bytes in/out: 4183/1465, packets in/out: 8/10, rtt: 0.209s, retransmitted packets: 0, out-of-order packets: 0
 ] 

- [ flutter doctor -v 
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.6 18G103, locale en-SA)
    • Flutter version 1.10.14 at /Users/macc/Downloads/delef/flutter
    • Framework revision 1946fc4da0 (2 weeks ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/macc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • E7315366-0790-470F-92B2-6E365047F7DE • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!]

**Comment by iapicca** [comment] 2019-10-24 07:41
Hi @2013abdullah1 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by iapicca** 2019-10-24 07:41 UTC

**Comment by 2013abdullah1** [comment] 2019-10-24 08:11
ok, what is wrong with me?
 
when I add firebase my app stuck on splash screen 
when I delete  firebase my app working

**Comment by sunjianan9900** [comment] 2019-12-18 07:02
I don't think it is Firebase issue
because i running well for many times
and i had this issue without changing any code
