### ISSUE TITLE
当Container包含platform view时，圆角不生效 (Fillet does not take effect when Container contains platform view)

### ISSUE THREAD

**Issue by Lillls** [flutter/flutter#41275] opened 2019-09-25 09:43 UTC
当Container包含platform view时，圆角不生效
(Google translate) Fillet does not take effect when Container contains platform view

**Comment by BondarenkoStas** [comment] 2019-09-25 11:29
@Lillls Can you please explain in more details what exactly the issue is? Please provide your flutter doctor -v, and some reproducible code example.

**Comment by BondarenkoStas** [comment] 2019-09-25 11:30
Duplicate of #41280

**Closed by BondarenkoStas** 2019-09-25 11:30 UTC
