### ISSUE TITLE
Can not run hello world app

### ISSUE THREAD

**Issue by Zeyad-37** [flutter/flutter#7492] opened 2017-01-13 22:46 UTC
## Steps to Reproduce

Ran the Hello World guide, the app crashes when i run it in debug mode. But then i can start app the app normally and everything works fine, but i could not find a way to attach a debugger.

I am using a tablet: Lenovo TB3 710I

## Logs

```
Exception from flutter run: FormatException: Bad UTF-8 encoding 0xb4
dart:convert/utf.dart 558                                  _Utf8Decoder.convert
dart:convert/string_conversion.dart 333                    _Utf8ConversionSink.addSlice
dart:convert/string_conversion.dart 329                    _Utf8ConversionSink.add
dart:convert/chunked_conversion.dart 92                    _ConverterStreamEventSink.add
dart:async/stream_transformers.dart 119                    _SinkTransformerStreamSubscription._handleData
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>
dart:async/zone.dart 1158                                  _rootRunUnary
dart:async/zone.dart 1037                                  _CustomZone.runUnary
dart:async/zone.dart 932                                   _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 331                            _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 258                            _BufferingStreamSubscription._add
dart:async/stream_controller.dart 768                      _StreamController&&_SyncStreamControllerDispatch._sendData
dart:async/stream_controller.dart 635                      _StreamController._add
dart:async/stream_controller.dart 581                      _StreamController.add
dart:io-patch/socket_patch.dart 1680                       _Socket._onData
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
package:stack_trace/src/stack_zone_specification.dart 185  StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 107  StackZoneSpecification._registerUnaryCallback.<fn>
dart:async/zone.dart 1162                                  _rootRunUnary
dart:async/zone.dart 1037                                  _CustomZone.runUnary
dart:async/zone.dart 932                                   _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 331                            _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 258                            _BufferingStreamSubscription._add
dart:async/stream_controller.dart 768                      _StreamController&&_SyncStreamControllerDispatch._sendData
dart:async/stream_controller.dart 635                      _StreamController._add
dart:async/stream_controller.dart 581                      _StreamController.add
dart:io-patch/socket_patch.dart 1247                       _RawSocket._RawSocket.<fn>
dart:io-patch/socket_patch.dart 781                        _NativeSocket.issueReadEvent.issue
dart:async/schedule_microtask.dart 41                      _microtaskLoop
dart:async/schedule_microtask.dart 50                      _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 96                   _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                  _RawReceivePortImpl._handleMessage
```

## Flutter Doctor

I cant run any flutter command from the IntelliJ terminal. 
output:
flutter: command not found

Flutter --version output:

Flutter • channel master • https://github.com/flutter/flutter.git
Framework • revision 3150e3fbd4 (2 hours ago) • 2017-01-13 12:46:13
Engine • revision b3ed79122e
Tools • Dart 1.21.

**Comment by sethladd** [comment] 2017-01-13 22:51
Thanks for the report!

Let's try to fix your command line. Did you add `$FLUTTER_ROOT/bin` to your path? If so, how?

**Comment by eseidelGoogle** [comment] 2017-01-13 23:01
Out of curiosity, what language are the computer and tablet set to?  The full `flutter doctor` output would tell us what type of machine you're using (mac/linux) which would also be useful to know.

**Comment by Zeyad-37** [comment] 2017-01-13 23:01
Yes
export PATH=FLUTTER_ROOT/bin:

**Comment by Zeyad-37** [comment] 2017-01-13 23:01
the language of the tablet is spanish

**Comment by Zeyad-37** [comment] 2017-01-13 23:03
but weirdly when i export the path from the intelliJ terminal i get a different result then when i do it from guake

**Comment by cbracken** [comment] 2017-02-22 18:17
Potentially related? #7779

**Comment by SupriyaKalghatgi** [comment] 2017-08-23 07:08
I have added Flutter into PATH
Still, I cant find it when its echoed on terminal

**Comment by ezrayoung** [comment] 2017-11-10 02:32
@SupriyaKalghatgi I was having the same problem. To get it to work, I did the following:

1.  Navigate to the directory that contains the top-level folder of the cloned repository.
2. "export PATH=`pwd`/flutter/bin:$PATH" (Note: ` is a back-tick, not an apostrophe ' )
3. "source $HOME/.bash_profile"
4. "echo $PATH"

If you begin in the correct directory, you should be able to simply copy/paste what is written in double quotes above.
The results of the echo are not clear, but somewhere in there you should see your working directory appended by "flutter/bin":. You should be able to run flutter commands after that.

Best of luck!

**Comment by mit-mit** [comment] 2017-12-13 11:55
Closing as a duplicate of https://github.com/flutter/flutter/issues/7779

**Closed by mit-mit** 2017-12-13 11:55 UTC
