### ISSUE TITLE
[Web] :Dropdownbutton's menu item position is mis-placed.

### ISSUE THREAD

**Issue by AbdulRafaySiddiqui** [flutter/flutter#65724] opened 2020-09-13 17:07 UTC
My dropdown button's popup position is incorrect, popup moves on the right side of the button. When I remove MaterialApp's builder method it works fine but not with the builder. I am on the master branch.

Below is the sample code, just paste it on Dartpad and you will see.

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: (context, child) => Scaffold(
        body: Row(
          children: [
            Container(
              width: 200,
              color: Colors.blue,
              child: Column(children: [
                 Text("Side Menu"),
              ])
            ),
            Expanded(child: child),
          ],
        ),
      ),
      initialRoute: "/",
      onGenerateRoute: (_) => MaterialPageRoute(
        builder: (BuildContext context) => Center(
          child: DropdownButton(
            hint: Text("test"),
            value: 0,
            items: [
              DropdownMenuItem(child: Text("test 1"), value: 0),
              DropdownMenuItem(child: Text("test 2"), value: 1),
              DropdownMenuItem(child: Text("test 3"), value: 2),
            ],
            onChanged: (value) {},
          ),
        ),
      ),
    );
  }
}
```

**Comment by songfei** [comment] 2020-09-14 08:52
#65605

**Comment by darshankawar** [comment] 2020-09-14 09:41
Hi @AbdulRafaySiddiqui,
I ran your code on physical device and see the dropdown menu items position as expected.

![65724](https://user-images.githubusercontent.com/67046386/93070310-58996380-f69c-11ea-87bd-3f12710838da.png)

Tested this on latest master.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.161, on Mac OS X 10.15.4 19E2269,
    locale en-IN)
    • Flutter version 1.22.0-10.0.pre.161 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision cba91c97d0 (9 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 85.0.4183.102

• No issues found!

```

</details>

Can you try on a device and see if you still see the same behavior as on dartpad ?
Thanks.

**Comment by AbdulRafaySiddiqui** [comment] 2020-09-14 11:06
@darshankawar I am facing this on the web, check @songfei reply he has fixed it, kindly merge it on the master.
> #65605
> 
> I fix it , please review

@songfei  thanks for your work

**Comment by songfei** [comment] 2020-09-14 11:30
@darshankawar    try my code:

```dart
Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Row(
        children: [
          SizedBox(
            width: 200.0,
          ),
          SizedBox(
            width: 800.0,
            child: Navigator(
              initialRoute: '/',
              onGenerateRoute: ((settings) {
                return MaterialPageRoute(builder: (context) {
                  return Container(
                    color: Colors.red,
                    child: Column(
                      children: [
                        Container(
                          width: 500.0,
                          child: DropdownButton<String>(
                            value: '1',
                            // underline: Container(height: 0),
                            isExpanded: true,
                            onChanged: (value) => setState(() => 1),
                            items: [
                              DropdownMenuItem(
                                value: '1',
                                child: Text('boy'),
                              ),
                              DropdownMenuItem(
                                value: '2',
                                child: Text('girl'),
                              )
                            ],
                          ),
                        ),
                      ],
                    ),
                  );
                });
              }),
            ),
          )
        ],
      ), 
    );
``` 
run in iPad simulator or  Chrome

**Comment by darshankawar** [comment] 2020-09-14 12:53
Issue replicable on latest master.

<img width="1082" alt="Screenshot 2020-09-14 at 6 21 14 PM" src="https://user-images.githubusercontent.com/67046386/93088146-2e08d400-f6b7-11ea-9927-55d679b4949e.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.161, on Mac OS X 10.15.4 19E2269,
    locale en-IN)
    • Flutter version 1.22.0-10.0.pre.161 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision cba91c97d0 (9 hours ago), 2020-09-13 18:57:03 -0400
    • Engine revision 2fc054147e
    • Dart version 2.10.0 (build 2.10.0-121.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm    • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 312977A7-2DB1-4737-AEBB-35FA6522A309
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

@AbdulRafaySiddiqui @songfei thanks for indicating it's on web, as the original description didn't mention it.

**Comment by yjbanov** [comment] 2020-09-17 21:37
This feels like a general issue with the framework misplacing the popup on a big screen, so I'll remove the platform-web label. However, please feel free to add it back if this is web-specific (e.g. you can try running using macOS/Linux desktop variant, or switching to CanvasKit using `--dart-define=FLUTTER_WEB_USE_SKIA=true`).

**Comment by kartalbas** [comment] 2020-09-20 20:15
I face the same issue on flutter for web (Flutter, Channel master, 1.22.0-10.0.pre.269, on Microsoft Windows [Version 10.0.19041.508], locale gsw-CH)

![image](https://user-images.githubusercontent.com/5513005/93721240-d672d880-fb8e-11ea-9289-4e855aab28b2.png)

**Comment by yjbanov** [comment] 2020-10-15 22:10
The fix is purely on the framework side, so it's not web-specific. I'll remove the platform-web label

**Comment by rbozan** [comment] 2020-10-16 07:42
PopupMenuButton doesn’t show this behavior, which seems odd to me without having seen the Flutter codebase.

**Comment by slavap** [comment] 2020-11-24 07:09
In 1.24.0-10.2.pre problem with PopupMenuButton misplacement is not fixed, though https://github.com/flutter/flutter/issues/68930 is Closed.

**Comment by TahaTesser** [comment] 2021-01-12 15:52
Closing as duplicate of https://github.com/flutter/flutter/issues/31683, which also fixed on the `master` channel. 

This seems to be fixed on the latest `master` channel. 
| stable, beta, dev | master |
| --------------- | --------------- |
<img width="202" alt="Screenshot 2021-01-12 at 9 05 59 PM" src="https://user-images.githubusercontent.com/48603081/104337460-85ab3500-551b-11eb-9935-afc7a0d99cd0.png">	| <img width="200" alt="Screenshot 2021-01-12 at 9 06 58 PM" src="https://user-images.githubusercontent.com/48603081/104337519-96f44180-551b-11eb-981c-7ebd422ac5db.png">



<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      builder: (context, child) => Scaffold(
        body: Row(
          children: [
            Container(
              width: 200,
              color: Colors.blue,
              child: Column(children: [
                 Text("Side Menu"),
              ])
            ),
            Expanded(child: child),
          ],
        ),
      ),
      initialRoute: "/",
      onGenerateRoute: (_) => MaterialPageRoute(
        builder: (BuildContext context) => Center(
          child: DropdownButton(
            hint: Text("test"),
            value: 0,
            items: [
              DropdownMenuItem(child: Text("test 1"), value: 0),
              DropdownMenuItem(child: Text("test 2"), value: 1),
              DropdownMenuItem(child: Text("test 3"), value: 2),
            ],
            onChanged: (value) {},
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86 • Android 10 (API 29) (emulator)
    • Taha’s iPad (mobile)               • 00008020-000255113EE8402E • ios         • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-8.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision b0a2299859 (7 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86    • Android 10 (API 29) (emulator)
    • Taha’s iPad (mobile)               • 00008020-000255113EE8402E • ios            • iOS 14.3
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
```bash
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 63062a6443 (4 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86    • Android 10 (API 29) (emulator)
    • Taha’s iPad (mobile)               • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)                    • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.296, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.296 at /Users/tahatesser/Code/flutter_master
    • Framework revision 737496e8db (8 hours ago), 2021-01-12 02:54:03 -0500
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554             • android-x86    • Android 10 (API 29) (emulator)
    • Taha’s iPad (mobile)               • 00008020-000255113EE8402E • ios            • iOS 14.3
    • macOS (desktop)                    • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                       • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

Thank you

**Closed by TahaTesser** 2021-01-12 15:52 UTC
Labels: a: quality, f: material design, found in release: 1.22, framework, has reproducible steps
