### ISSUE TITLE
Why flutter can’t update the UI when the app is inactive?

### ISSUE THREAD

**Issue by cocoayang** [flutter/flutter#50732] opened 2020-02-13 16:19 UTC
Why flutter can’t update the UI when the app is inactive? on my iPhone, when I change the theme to dark mode via the Control Center panel, I expect that the flutter UI could be updated immediately, But in fact it could not be updated until the Control Center panel hides, in other words the app becomes active again. what’s worse, the duration between the Control Center panel hides and the app becomes active is as long as 1400ms. Is there some way to update the ui when the app is inactive?   
Steps to repeat:  
1,  Slide up on the screen from the bottom of iPhone to see if the Dark Mode exists on Control Center, If not, it can be added by following the step2.  
2, Launch the Settings app, and then tap Control center, scroll the list to MORE CONTROLS and find the Dark Mode cell and tap the green plus icon. This step can be ignored If the Dark Mode already exists in Control Center.  
3, Tap the Dark Mode icon on Control Center Panel, thus the app theme changes to dark mode.  
At this moment,  the iOS UI can be updated immediately even if the the Control Center Panel floats on screen. In flutter, I observed the theme changing event and the didChangePlatformBrightness method is called immediately，I called setState in didChangePlatformBrightness. But the build function is not scheduled. 
4, Slide down on the screen to hide the  Control Center panel.   
After about 1400 ms, the build method of _MyAppState is called and the UI is updated. What I expect is that the flutter UI can be updated immediately when the theme changed even if the app is inactive or when the Control Center panel hides. Waiting for 1400 ms can’t be accepted.   
My test code is attached as below.  

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  Brightness brightness;

  @override
  void initState() {
    super.initState();
    brightness = Brightness.light;
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('example app'),
        ),
        body: Center(
          child: Container(
            color: brightness == Brightness.dark ? Colors.black : Colors.white,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangePlatformBrightness() {
    setState(() {
      brightness =
          WidgetsBinding.instance.window.platformBrightness;
    });
  }
}
```

**Comment by Zazo032** [comment] 2020-02-13 16:27
Did you try setting your app's `brightness` using [`MaterialApp`](https://api.flutter.dev/flutter/material/MaterialApp-class.html)'s [`theme`](https://api.flutter.dev/flutter/material/MaterialApp/theme.html) and [`darkTheme`](https://api.flutter.dev/flutter/material/MaterialApp/darkTheme.html) attributes?

**Comment by cocoayang** [comment] 2020-02-13 16:33
The attached video is how the example app works
[demo.mp4.zip](https://github.com/flutter/flutter/files/4199500/demo.mp4.zip)

**Comment by cocoayang** [comment] 2020-02-13 16:36
> Did you try setting your app's `brightness` using [`MaterialApp`](https://api.flutter.dev/flutter/material/MaterialApp-class.html)'s [`theme`](https://api.flutter.dev/flutter/material/MaterialApp/theme.html) and [`darkTheme`](https://api.flutter.dev/flutter/material/MaterialApp/darkTheme.html) attributes?

No, I didn't, I just save the brightness and rebuild the MaterialApp with the new brightness to change the Container widget's color.

**Comment by cocoayang** [comment] 2020-02-13 17:03
> Did you try setting your app's `brightness` using [`MaterialApp`](https://api.flutter.dev/flutter/material/MaterialApp-class.html)'s [`theme`](https://api.flutter.dev/flutter/material/MaterialApp/theme.html) and [`darkTheme`](https://api.flutter.dev/flutter/material/MaterialApp/darkTheme.html) attributes?

I added theme and dartThme in MaterialApp, the color changed when switch to dark mode, but it works the same way as the setState mode. Thus, the ui WOULDN'T update until about 1400 ms later after the Contol Center panel hids.   
The code:  

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  //Brightness brightness;

  @override
  void initState() {
    super.initState();
//    brightness = Brightness.light;
//    WidgetsBinding.instance.addObserver(this);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        backgroundColor: Colors.black,
        primaryColor: Colors.black,
      ),
      theme: ThemeData(
        brightness: Brightness.light,
        backgroundColor: Colors.white,
        primaryColor: Colors.white,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('example app'),
        ),
        body: Center(
          child: Container(
            //color: brightness == Brightness.dark ? Colors.black : Colors.white,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    //WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

//  @override
//  void didChangePlatformBrightness() {
//    setState(() {
//      brightness = WidgetsBinding.instance.window.platformBrightness;
//    });
//  }
}
```

**Comment by cocoayang** [comment] 2020-02-13 17:05
> Did you try setting your app's `brightness` using [`MaterialApp`](https://api.flutter.dev/flutter/material/MaterialApp-class.html)'s [`theme`](https://api.flutter.dev/flutter/material/MaterialApp/theme.html) and [`darkTheme`](https://api.flutter.dev/flutter/material/MaterialApp/darkTheme.html) attributes?

I added theme and darkTheme in MaterialApp, the color changed when switch to dark mode, but it works the same way as the setState mode. Thus, the ui WOULDN'T update until about 1400 ms later after the Contol Center panel hids.   
The code:  

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  //Brightness brightness;

  @override
  void initState() {
    super.initState();
//    brightness = Brightness.light;
//    WidgetsBinding.instance.addObserver(this);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        backgroundColor: Colors.black,
        primaryColor: Colors.black,
      ),
      theme: ThemeData(
        brightness: Brightness.light,
        backgroundColor: Colors.white,
        primaryColor: Colors.white,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('example app'),
        ),
        body: Center(
          child: Container(
            //color: brightness == Brightness.dark ? Colors.black : Colors.white,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    //WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

//  @override
//  void didChangePlatformBrightness() {
//    setState(() {
//      brightness = WidgetsBinding.instance.window.platformBrightness;
//    });
//  }
}
```

**Comment by cocoayang** [comment] 2020-02-13 17:05
> Did you try setting your app's `brightness` using [`MaterialApp`](https://api.flutter.dev/flutter/material/MaterialApp-class.html)'s [`theme`](https://api.flutter.dev/flutter/material/MaterialApp/theme.html) and [`darkTheme`](https://api.flutter.dev/flutter/material/MaterialApp/darkTheme.html) attributes?

I added theme and darkTheme in MaterialApp, the color changed when switch to dark mode, but it works the same way as the setState mode. Thus, the ui WOULDN'T update until about 1400 ms later after the Contol Center panel hides.   
The code:  

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  //Brightness brightness;

  @override
  void initState() {
    super.initState();
//    brightness = Brightness.light;
//    WidgetsBinding.instance.addObserver(this);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        backgroundColor: Colors.black,
        primaryColor: Colors.black,
      ),
      theme: ThemeData(
        brightness: Brightness.light,
        backgroundColor: Colors.white,
        primaryColor: Colors.white,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('example app'),
        ),
        body: Center(
          child: Container(
            //color: brightness == Brightness.dark ? Colors.black : Colors.white,
          ),
        ),
      ),
    );
  }

  @override
  void dispose() {
    //WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

//  @override
//  void didChangePlatformBrightness() {
//    setState(() {
//      brightness = WidgetsBinding.instance.window.platformBrightness;
//    });
//  }
}
```

**Comment by cocoayang** [comment] 2020-02-17 13:19
Is there anyone know?

**Comment by danspano** [comment] 2020-02-25 19:47
@cocoayang I believe your issue relates to this: https://github.com/flutter/flutter/issues/33236

All of the following things cause the app to be "inactive" which prevents flutter from calling the build method on your UI:
- System dialog (FaceID/TouchID)
- Control Center
- Notification Center
- Pressing home button / Home gesture
- Showing app switcher

iOS apps built with UIKit don't stop rendering during these events, but Flutter will stop rendering. There are workarounds in the issue I linked but there is ongoing debate as to whether this is a Flutter "issue" or expected behaviour.

**Comment by TahaTesser** [comment] 2020-09-23 11:38
This is a duplicate of https://github.com/flutter/flutter/issues/43806  and still reproducible https://github.com/flutter/flutter/issues/43806#issuecomment-696759377

**Closed by TahaTesser** 2020-09-23 11:38 UTC
Labels: a: fidelity, engine, framework, platform-ios
