### ISSUE TITLE
[video_player] PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error)

### ISSUE THREAD

**Issue by mhbdev** [flutter/flutter#131753] opened 2023-08-02 09:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Try to run the simplest application that runs a video from this url using video_player package: (The device I am confronting this issue is Samsung A23 Android 13.) 
The video is playing on other devices like S21 Ultra, Samsung A40, ... .

[video url](https://dl2.apexteam.net/pana/vendor/course_1.mp4)

### Expected results

I know that the error message indicates that the ExoPlayer encountered an error while attempting to play the video. Specifically, the error occurred in the MediaCodecVideoRenderer, which is responsible for decoding and rendering the video frames.
I don't want to lower my video resolution of frame rate. and there is no option to do so using VideoPlayerController on client side.

### Actual results

The video is not playing on Samsung A23 and some other devices and getting this error:

```console
PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, -1, null, [3840, 2160, 30.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES, null, null)
```

### Code sample

<details><summary>Create a simple class with the code below in it and try to run on said devices</summary>

```dart
late VideoPlayerController _videoPlayerController;

 @override
  void initState() {
    super.initState();

    _videoPlayerController =
        VideoPlayerController.network('https://dl2.apexteam.net/pana/vendor/course_1.mp4');
  }

  Future<bool> started() async {
    await _videoPlayerController.initialize();
    await _videoPlayerController.play();
    return true;
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      child: Center(
        child: FutureBuilder<bool>(
          future: started(),
          builder: (BuildContext context, AsyncSnapshot<bool> snapshot) {
            if (snapshot.data ?? false) {
              return AspectRatio(
                aspectRatio: _videoPlayerController.value.aspectRatio,
                child: VideoPlayer(_videoPlayerController),
              );
            } else {
              return const Text('waiting for video to load');
            }
          },
        ),
      ),
    );
  }

  @override
  void dispose() {
    _videoPlayerController.dispose();
    super.dispose();
  }
```

</details>

### Logs

<details><summary>Logs</summary>

```console
E/ExoPlayerImplInternal(29644): Playback error
E/ExoPlayerImplInternal(29644):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, -1, null, [3840, 2160, 30.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
E/ExoPlayerImplInternal(29644):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(29644):       at android.os.Looper.loopOnce(Looper.java:226)
E/ExoPlayerImplInternal(29644):       at android.os.Looper.loop(Looper.java:313)
E/ExoPlayerImplInternal(29644):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(29644):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.640033, -1, null, [3840, 2160, 30.0], [-1, -1])
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1021)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:537)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1453)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:917)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:954)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:769)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
E/ExoPlayerImplInternal(29644):       ... 4 more
E/ExoPlayerImplInternal(29644):   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
E/ExoPlayerImplInternal(29644):       at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(29644):       at android.media.MediaCodec.configure(MediaCodec.java:2214)
E/ExoPlayerImplInternal(29644):       at android.media.MediaCodec.configure(MediaCodec.java:2130)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:156)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:111)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1099)
E/ExoPlayerImplInternal(29644):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1010)
E/ExoPlayerImplInternal(29644):       ... 11 more
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.10.2, on Microsoft Windows [Version 10.0.19045.3086], locale en-US)
    • Flutter version 3.10.2 on channel stable at C:\FlutterStable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (2 months ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\AndroidSdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = C:\AndroidSdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community

[√] VS Code (version 1.80.1)
    • VS Code at C:\Users\MonoBit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.3086]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 115.0.5790.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 114.0.1823.82

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by mhbdev** [comment] 2023-08-02 10:05
Sharing my crashlytic info in case it helps:

Devices:
![image](https://github.com/flutter/flutter/assets/53684884/e834c778-1bfe-45d8-becc-d20c37e24f31)
![image](https://github.com/flutter/flutter/assets/53684884/c0ec0b71-8f4f-483b-a520-694113f2313a)

OS versions:
![image](https://github.com/flutter/flutter/assets/53684884/465b5da5-9b37-4036-8eba-8855163f4d79)

**Comment by huycozy** [comment] 2023-08-02 11:59
Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/81804. Please follow up on it for further updates. Also, this is more like an ExoPlayer's issue, please see this [filter](https://github.com/google/ExoPlayer/issues?q=is%3Aissue+is%3Aopen+com.google.android.exoplayer2.ExoPlaybackException%3A+MediaCodecVideoRenderer+error) on ExoPlayer repository.

**Closed by huycozy** 2023-08-02 11:59 UTC
Labels: in triage
