### ISSUE TITLE
[tool_crash] DartDevelopmentServiceException

### ISSUE THREAD

**Issue by dritiu666** [flutter/flutter#124967] opened 2023-04-17 13:43 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
DartDevelopmentServiceException
```
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:133:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DebugService.startDartDevelopmentService (package:dwds/src/services/debug_service.dart:154:12)
<asynchronous suspension>
#3      DevHandler._createAppDebugServices (package:dwds/src/handlers/dev_handler.dart:466:7)
<asynchronous suspension>
#4      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:241:21)
<asynchronous suspension>
#5      Dwds.debugConnection (package:dwds/dart_web_debug_service.dart:61:30)
<asynchronous suspension>
#6      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/isolated/devfs_web.dart:713:15)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.11, on Deepin 20.8 5.15.77-amd64-desktop, locale zh_CN.UTF-8)
    [32m•[39m Flutter version 3.7.11 on channel stable at /home/Yhy/Code/My/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision f72efea43c (6 天前), 2023-04-11 11:57:21 -0700
    [32m•[39m Engine revision 1a65d409c7
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[31m[✗][39m Linux toolchain - develop for Linux desktop
    [31m✗[39m clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    [31m✗[39m CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from https://cmake.org/download/
    [31m✗[39m ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    [32m•[39m pkg-config version 0.29
    [31m✗[39m GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.76.0)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.62.0

[33m[!][39m Proxy Configuration
    [32m•[39m HTTP_PROXY is set
    [32m•[39m NO_PROXY is localhost,127.0.0.0/8,::1
    [32m•[39m NO_PROXY contains localhost
    [33m![39m NO_PROXY does not contain 127.0.0.1
    [32m•[39m NO_PROXY contains ::1

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Deepin 20.8 5.15.77-amd64-desktop
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 112.0.5615.121

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[33m![39m Doctor found issues in 4 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f72efea43c3013323d1b95cff571f3c1caa37583

**Comment by huycozy** [comment] 2023-04-18 05:08
Hi @dritiu666 
Are you seeing this crash when running on Web platform? May be a duplicate of https://github.com/flutter/flutter/issues/108848.

**Comment by huycozy** [comment] 2023-04-18 05:12
Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/108848 which has the similar stack trace.

**Closed by huycozy** 2023-04-18 05:12 UTC
Labels: waiting for customer response, in triage
