### ISSUE TITLE
HarmonyOS supported ？

### ISSUE THREAD

**Issue by Jason-lyl** [flutter/flutter#143727] opened 2024-02-20 03:31 UTC
### Steps to reproduce

HarmonyOS supported ？

### Expected results

HarmonyOS supported ？

### Actual results

HarmonyOS supported ？

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

HarmonyOS supported ？

**Comment by hyiso** [comment] 2024-02-20 03:45
duplicate of #38437

This work is doing by a third group, see https://gitee.com/openharmony-sig/flutter_flutter

**Comment by huycozy** [comment] 2024-02-20 04:59
Closing as a duplicate of https://github.com/flutter/flutter/issues/38437

**Closed by huycozy** 2024-02-20 04:59 UTC
Labels: in triage
