### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by zancheng** [flutter/flutter#104395] opened 2022-05-23 08:04 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. flutter pub get
2. Console display:
```
Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = clients2.google.com, port = 53398
Oops; flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path =
'C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\path_provider_android-2.0.14\android\src\main\java\io\flutter\plugins\pa
thprovider\PathProviderPlugin.java'".
```
3. Deleting the corresponding dependency will work normally

Several dependent individual files will be prompted like this
## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:186:53)
#4      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:133:49)
#5      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart)
#6      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:127:30)
#7      _extractPlatformMaps (package:flutter_tools/src/flutter_plugins.dart:341:40)
#8      _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:357:5)
#9      injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1082:11)
<asynchronous suspension>
#10     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:335:5)
<asynchronous suspension>
#11     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:177:5)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1526], locale zh-CN)
    • Flutter version 2.8.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\workApps\android-sdk-windows-new
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at E:\workApps\Visual-studio-m
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1)
    • Android Studio at E:\workApps\android studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at E:\workApps\IntelliJ IDEA 2021.1.2
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7798

[✓] VS Code (version 1.67.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • YAL AL10 (mobile) • ERLDU20423010578 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1526]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 98.0.1108.56
    ! Device 192.168.21.148:5555 is not authorized.
      You might need to check your device for an authorization dialog.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.0.0+1
**Material**: true
**Android X**: true
**Module**: true
**Plugin**: false
**Android package**: com.example.flutter_module
**iOS bundle identifier**: com.example.flutterModule
**Creation channel**: null
**Creation framework version**: null
### Plugins
path_provider-2.0.10
path_provider_android-2.0.14
path_provider_ios-2.0.9
path_provider_linux-2.1.6
path_provider_macos-2.0.6
path_provider_windows-2.0.6
permission_handler-8.3.0
vibration-1.7.4-nullsafety.0
vibration_web-1.6.3-nullsafety.0
webview_flutter-3.0.4
webview_flutter_android-2.8.8
webview_flutter_wkwebview-2.7.5

**Comment by darshankawar** [comment] 2022-05-23 09:52
Closing this as duplicate of https://github.com/flutter/flutter/issues/65021

**Closed by darshankawar** 2022-05-23 09:52 UTC
Labels: in triage

**Comment by zancheng** [comment] 2022-05-31 01:03
> Closing this as duplicate of #65021

I tried deleting Flutter plugins file, but it seems useless.
I don't know how to deal with it now.
```
Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = clients2.google.com, port = 51638
Oops; flutter has exited unexpectedly: "FileSystemException: Failed to decode data using encoding 'utf-8', path =
'C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\shared_preferences_android-2.0.12\android\src\main\java\io\flutter\plugi
ns\sharedpreferences\SharedPreferencesPlugin.java'".
```
