### ISSUE TITLE
Different spacing behaviour with wrap layout between mobile and desktop 

### ISSUE THREAD

**Issue by yankai-victor** [flutter/flutter#67797] opened 2020-10-10 02:35 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 

create main.dart like this

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'app demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'app demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _purpose = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Wrap(
        direction: Axis.horizontal,
        spacing: 10,
        children: [
          ChoiceChip(
            label: Text("purpose1"),
            selected: _purpose == 0,
            onSelected: (isSelected) {
              if (isSelected) {
                setState(() {
                  _purpose = 0;
                });
              }
            },
          ),
          ChoiceChip(
            label: Text("purpose2"),
            selected: _purpose == 1,
            onSelected: (isSelected) {
              if (isSelected) {
                setState(() {
                  _purpose = 1;
                });
              }
            },
          ),
          ChoiceChip(
            label: Text("purpose3"),
            selected: _purpose == 2,
            onSelected: (isSelected) {
              if (isSelected) {
                setState(() {
                  _purpose = 2;
                });
              }
            },
          ),
          ChoiceChip(
            label: Text("purpose4"),
            selected: _purpose == 3,
            onSelected: (isSelected) {
              if (isSelected) {
                setState(() {
                  _purpose = 3;
                });
              }
            },
          ),
          ChoiceChip(
            label: Text("purpose5"),
            selected: _purpose == 4,
            onSelected: (isSelected) {
              if (isSelected) {
                setState(() {
                  _purpose = 4;
                });
              }
            },
          ),
        ],
      ),
    );
  }
}

```

</details> 

3. Run the app on an Android simulator and web server(I use Opera and Safari).

**Expected results:** 
The same UI on Android simulator and web browser

**Actual results:** 
Web browser is on the left. Android simulator is on the right.
![image](https://user-images.githubusercontent.com/8499363/95643349-44048b80-0ae1-11eb-80cf-e119f537a72b.png)

<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.253, on Mac OS X 10.14.4 18E226 x86_64, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 7.3)
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2019.3.5)
[✓] Connected device (2 available)
```

</details>

**Comment by jonahwilliams** [comment] 2020-10-10 03:12
This is probably due to using a different MaterialTapTargetSize

**Comment by jonahwilliams** [comment] 2020-10-10 03:13
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/chip.dart#L1928

**Comment by TahaTesser** [comment] 2020-10-12 14:45
Hi @yankai-victor 
I tried to track the commits to find this regression on the master channel 

<img width="1440" alt="Screenshot 2020-10-12 at 8 13 20 PM" src="https://user-images.githubusercontent.com/48603081/95759513-6b1cb200-0cc7-11eb-8a6a-650274f081f0.png">

My guess is regression happened here https://github.com/flutter/flutter/issues/66754

### Issue on  commit https://github.com/flutter/flutter/commit/9efdcf61d2eaa7d7126b8e15a23ce097c28449f5
<img width="345" alt="Screenshot 2020-10-12 at 8 10 12 PM" src="https://user-images.githubusercontent.com/48603081/95759713-ae772080-0cc7-11eb-9c5d-12e1d02c4c2e.png">



### No Issue on  commit https://github.com/flutter/flutter/commit/3063182e7775e9824a33e41b535961a30400f70c
<img width="335" alt="Screenshot 2020-10-12 at 3 40 25 PM" src="https://user-images.githubusercontent.com/48603081/95758228-cd74b300-0cc5-11eb-8ac9-cd02f355808b.png">





<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel unknown, 1.23.0-8.0.pre.42, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.23.0-8.0.pre.42 at /Users/tahatesser/Code/flutter_master
    • Framework revision 9efdcf61d2 (2 weeks ago), 2020-09-28 18:22:02 -0400
    • Engine revision 77701d303e
    • Dart version 2.11.0 (build 2.11.0-174.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (4 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.0.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.7 19H2 x86_64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!


```

</details>

**Comment by ferhatb** [comment] 2020-10-23 04:59
@gspencergoog , @goderbauer density seems wrong for desktop ?
Not sure if TapTargetSize should be set lower but not zero for desktop.
Otherwise, users will have to compensate in all multiplat apps.

**Comment by gspencergoog** [comment] 2020-10-23 19:32
Density will change on the web based on the platform that it thinks it is running on: there is code to check the browser and see if it's running on desktop or mobile, and pick different densities by default based on that.

However, the density isn't the problem here, it's the change in shrink-wrapping behavior of the touch targets for desktop platforms. I think that part is WAI, except that [Chip]s are a little odd in that they don't have any intrinsic padding, because they often need to be presenting in a very compact way. Perhaps Chips should keep their touch target size a minimum of 2dp outside of their bounding box instead of shrink wrapping. @willlarche from a Material perspective, what do you think the guidance should be?

**Comment by ferhatb** [comment] 2020-11-12 17:24
@willlarche, any guidance on this? Is 2dp a good solution? Otherwise every chip may need to be wrapped inside a padding to make your app multiplat.

**Comment by clocksmith** [comment] 2020-11-12 17:41
Could you elaborate on the proposed solution? Is it altering behavior of `shrinkWrap` for chips, or changing the default? 

Or could it be to add 2dp of padding to the child of `_ChipRedirectingHitDetectionWidget` when the `MaterialTapTargetSize` is `shrinkWrap`?: https://github.com/flutter/flutter/blob/8874f21e79d7ec66d0457c7ab338348e31b17f1d/packages/flutter/lib/src/material/chip.dart#L1941

**Comment by ferhatb** [comment] 2020-12-02 21:16
@clocksmith , its about default, is guidance using 2dp?

**Comment by clocksmith** [comment] 2021-01-14 20:33
@ferhatb The guidance is that there should be 8dp above and below the chip top and chip bottom

**Comment by ferhatb** [comment] 2021-01-15 17:32
@gspencergoog given guidance above , does the shrinkwrap default for desktop need to be changed?

**Comment by gspencergoog** [comment] 2021-01-15 17:50
Yes, probably so.

**Comment by iCodify** [comment] 2021-07-23 15:26
I've just encountered this as well 😊

`
Wrap(
  spacing: 4,
  runSpacing: 4,
  children: List<Widget>.generate(arrLength, (int index) {
    final item = arr[index];
    return ChoiceChip(
      shape: RoundedRectangleBorder(),
      label: Text(item.name),
      selected: _selectedItemId == item.id,
      onSelected: (bool selected) {
        setState(() {
          _selectedItemId = item.id;
        });
      },
    );
  }),
),
`

I'm actually only developing my app for the 'Web' & I debug the app in Chrome, then do 'flutter build web' => firebase deploy :)

When I open the website on my PC, the spacing is fine, but when I open the same link on my Android device, the spacing is .. well, it looks at least 4x the size :D

**Comment by n00bvn** [comment] 2021-09-01 07:36
I'm encountering this issue as well. The spacing on mobile is too much.

**Comment by bunjongy** [comment] 2021-09-20 11:11
found same issue as well

**Comment by Colin-XKL** [comment] 2021-10-04 10:09
Any progress about this question? The bug has been here for almost one year now.

**Comment by luissalgadofreire** [comment] 2022-07-11 11:24
Not sure it is a wrong hunch but I'm going to risk it nonetheless.

My workaround was something like the below:

```dart
@override
  Widget build(BuildContext context) {
    return Container(
        padding: EdgeInsets.symmetric(
          /// Only necessary because [Wrap] is misbehaving between platforms.
          // See: https://github.com/flutter/flutter/issues/67797.
          // FIXME: monitor the aforementioned issue to remove this workaround.
          vertical: _platform == PlatformType.desktop
              ? verticalPadding
              : verticalPadding - tagPadding,
        ),
        child: Wrap(
          /// Only necessary because [Wrap] is misbehaving between platforms.
          // See: https://github.com/flutter/flutter/issues/67797.
          // FIXME: monitor the aforementioned issue to remove this workaround.
            runSpacing: _platform == PlatformType.desktop
                ? tagPadding
                : -tagPadding,
            spacing: tagPadding,
            children: <Widget>[
              ...tags.map((t) => _buildTagChip(
                  context: context,
                  name: t.name,
                  icon: t.icon,
                  color: t.color
              )),
              _buildTagChip(context: context, name: 'Add tag', isAddTag: true)
            ]
        )
    );
  }
```

I haven't investigated more thoroughly but, at first glance, it almost seems like the value of `spacing` is being added to both the padding around the whole `Wrap` and the `runSpacing`. Subtracting `spacing` from both seems to do the trick.

This can turn out to be a misleading coincidence or it may point to the root cause of the problem. Again, I haven't investigated enough to check which.

**Comment by TahaTesser** [comment] 2022-07-27 12:09
Desktop vs mobile

| Preview | 
| --------------- | 
| <img src="https://user-images.githubusercontent.com/48603081/181243334-f391b6f0-525a-45e1-9016-7257f48a89a7.png" height="450" />	|

**Comment by TahaTesser** [comment] 2022-07-27 19:21
This seems to be working as intended, see https://github.com/flutter/flutter/pull/108436

**Comment by gspencergoog** [comment] 2022-09-08 18:16
@TahaTesser what was the reason for reopening this? (Desktop Triage)

**Comment by TahaTesser** [comment] 2022-09-08 21:49
@gspencergoog 
 It seems `MaterialTapTargetSize` is not valid for clicks? https://github.com/flutter/flutter/pull/108436#issuecomment-1197221499

**Comment by gspencergoog** [comment] 2022-09-22 18:33
@TahaTesser Can you close this and file another bug that describes the remaining issue, if any?  It sounds like the original reported issue here should be closed as "working as intended", but that perhaps there is a change that could help make it easier to use?

**Comment by TahaTesser** [comment] 2022-09-23 08:43
I will close this for WAI (working as intended). 
AFAIK, we can set [density](https://master-api.flutter.dev/flutter/material/Chip/visualDensity.html) for chips, if you want spacings for desktop as well.
If there is a specific proposal to make it easier, please file a new issue.

**Closed by TahaTesser** 2022-09-23 08:43 UTC
Labels: severe: regression, framework, f: material design, a: desktop, has reproducible steps, P3, found in release: 1.23
