### ISSUE TITLE
Inconsistent layout of buttons in Row widget android/linux/windows

### ISSUE THREAD

**Issue by billthefarmer** [flutter/flutter#143643] opened 2024-02-17 13:52 UTC
### Steps to reproduce

1. Include more than one button in a `Row` widget using `mainAxisSize: MainAxisSize.min` in an app.
2. Test the app on android/linux/windows. Macos/iOS untested.
3. The buttons in android will be nicely spaced with about 8dp (or whatever you call your spacing units) between them.
4. The buttons in linux/windows will be immediately adjacent, requiring the use of conditional `Padding`.

### Expected results

I would expect the layout to be identical on all platforms.

### Actual results

Inconsistent layout on different platforms.

### Code sample

<details open><summary>Code sample</summary>

```dart
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Padding(
                      padding: EdgeInsets.only(
                        right: Platform.isWindows || Platform.isLinux ? 4 : 0),
                      child: IconButton(
                        icon: const Icon(Icons.add),
                        color: Colors.white,
                        style: ButtonStyle(
                          backgroundColor: const MaterialStatePropertyAll(
                            Colors.indigo),
                          shape: MaterialStatePropertyAll(
                            RoundedRectangleBorder(
                              borderRadius: BorderRadius.all(
                                Radius.circular(8),
                              ),
                            ),
                          ),
                        ),
                        onPressed: () {
                          zoomIn();
                          showZoomButtons();
                        },
                      ),
                    ),
                    Padding(
                      padding: EdgeInsets.only(
                        left: Platform.isWindows || Platform.isLinux ? 4 : 0),
                      child: IconButton(
                        icon: const Icon(Icons.remove),
                        color: Colors.white,
                        style: ButtonStyle(
                          backgroundColor: const MaterialStatePropertyAll(
                            Colors.indigo),
                          shape: MaterialStatePropertyAll(
                            RoundedRectangleBorder(
                              borderRadius: BorderRadius.all(
                                Radius.circular(8),
                              ),
                            ),
                          ),
                        ),
                        onPressed: () {
                          zoomOut();
                          showZoomButtons();
                        },
                      ),
                    ),
                  ],
                ),
```
Edit: The app is on https://github.com/billthefarmer/busapp
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot_20240217-134454 1](https://github.com/flutter/flutter/assets/3448386/74b5fda2-2ec4-4d20-9f2e-0c707778a9a7)

</details>
This is the android app with no padding. The linux/windows appearance is similar because of the conditional padding I have added.

### Logs

<details open><summary>Logs</summary>

```console
N/A
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
$ flutter doctor -v
[√] Flutter (Channel stable, 3.19.0, on Microsoft Windows [Version 10.0.19045.4046], locale en-GB)
    • Flutter version 3.19.0 on channel stable at D:\adt\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (4 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\adt\android-sdk-windows
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34408.163
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] Connected device (4 available)
    • Moto G (mobile)   • TA93003J7P • android-arm    • Android 7.1.2 (API 25)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [Version 10.0.19045.4046]
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 121.0.6167.161
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 121.0.2277.112

[√] Network resources
    • All expected network resources are available.

• No issues found!


```

</details>

**Comment by nate-thegrate** [comment] 2024-02-18 19:09
I've run into the same issue. It turns out that this is intentional—according to Material design specs, mobile apps should have a minimum tap target size of 48x48 dp.

If you want to make this consistent across devices, you can set the `tapTargetSize` as part of your button style (and unrelated, but you can use `.styleFrom()` and you won't need `MaterialStateProperty` classes):

```dart
IconButton(
  icon: const Icon(Icons.add),
  color: Colors.white,
  style: IconButton.styleFrom(
    backgroundColor: Colors.indigo,
    shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.all(Radius.circular(8)),
    ),
    padding: EdgeInsets.zero,
    tapTargetSize: MaterialTapTargetSize.padded,
  ),
),
```

**Comment by dam-ease** [comment] 2024-02-19 08:23
Thanks for filing this @billthefarmer.
I can reproduce this on the latest `master` and `stable` channels without the conditional padding (reproduced this on macOS and iOS).

| macOS | iOS |
|--------|--------|
| <img width="156" alt="Screenshot 2024-02-19 at 09 14 47" src="https://github.com/flutter/flutter/assets/53122008/e8095500-41a9-4edb-963c-7ff4c2a53ca6"> | <img width="156" alt="Screenshot 2024-02-19 at 09 19 10" src="https://github.com/flutter/flutter/assets/53122008/7057defe-59e2-42f4-a826-2698826d5125"> | 

With the workaround shared here https://github.com/flutter/flutter/issues/143643#issuecomment-1951417350, I can't seem to reproduce this, can you try this out as well?

**Comment by billthefarmer** [comment] 2024-02-19 10:12
@nate-thegrate @dam-ease Yes, I've tried that and it works fine. Thank you.

**Comment by dam-ease** [comment] 2024-02-20 06:14
Thanks for your response. Closing this as this is WAI

**Closed by dam-ease** 2024-02-20 06:14 UTC
Labels: in triage
