### ISSUE TITLE
ChangeNotifier `dispose` does not clear inner listeners collection

### ISSUE THREAD

**Issue by bambinoua** [flutter/flutter#86473] opened 2021-07-15 09:43 UTC
As I remember it was before when I called method `dispose` of `ChangeNotifier` it also clears the inner collection of listeners (`_listeners`). Now as I see the `dispose` method **does not do anything** except setting `_debugDisposed` to `true`. So why then is it for? Why listeners are not cleared (as it was before)? Is it a bug or a feature? Is it possible to clear listeners on disposing? Is it possible to add public method like `clearListeneners`?

**Comment by maheshmnj** [comment] 2021-07-15 10:03
Hi @bambinoua,
Could you please provide a minimal reproducible code along with the output of `flutter doctor -v` to better addrress the issue. 
Thank you.

**Comment by bambinoua** [comment] 2021-07-15 13:11
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final valueNotifier = MyValueNotifier(0);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('ChangeNotifier'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ValueListenableBuilder<int>(
                valueListenable: valueNotifier,
                builder: (context, counter, child) {
                  return Text(
                    counter.toString(),
                    style: Theme.of(context).textTheme.headline4,
                  );
                },
              ),
              const SizedBox(height: 32.0),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton(
                    onPressed: () {
                      valueNotifier.value += 1;
                    },
                    child: const Text('COUNT'),
                  ),
                  const SizedBox(width: 32.0),
                  ElevatedButton(
                    onPressed: () {
                      // There is one item in _listeners.
                      valueNotifier.dispose();
                      // Still there is one item in _listeners.
                      // So what dispose does?
                    },
                    child: const Text('DISPOSE'),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class MyValueNotifier<T> extends ValueNotifier<T> {
  MyValueNotifier(T value) : super(value);

  @override
  bool get hasListeners => super.hasListeners;
}
```

**Comment by maheshmnj** [comment] 2021-07-15 14:47
Once you have called dispose() method, you can no longer interact with the object this includes adding or removing listeners.

[Taken from the docs](https://api.flutter.dev/flutter/foundation/ChangeNotifier/dispose.html)
>Discards any resources used by the object. After this is called, the object is not in a usable state and should be discarded (calls to addListener and removeListener will throw after the object is disposed)
This method should only be called by the object's owner.

I would suggest you to look at the docs for more info on `dispose` and other APIs, Since this issue doesn't report a bug or make a feature request this is considered to be invalid. So I am going to close this issue, If you disagree feel free to write in the comments and I will reopen it.
Thank you.

**Closed by maheshmnj** 2021-07-15 14:47 UTC
Labels: in triage
