### ISSUE TITLE
[Web] `addEventListener$2` method not found

### ISSUE THREAD

**Issue by Sunbreak** [flutter/flutter#97357] opened 2022-01-27 08:03 UTC
Example fails in `profile`/`release` mode while works in `debug` mode

Repo: https://github.com/woodemi/web_hid.dart
Branch: [repoduce/addEventLisenter](https://github.com/woodemi/web_hid.dart/tree/repoduce/addEventLisenter)

```
NoSuchMethodError: method not found: 'addEventListener$2' (J.getInterceptor$x(...).addEventListener$2 is not a function)
```

## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Press button `hid.subscribeConnect` or `hid.subscribeDisconnect`

**Expected results:**

```
print('hid.subscribeConnect success');
...
print('hid.subscribeDisconnect success');
```

**Actual results:**

```
NoSuchMethodError: method not found: 'addEventListener$2' (J.getInterceptor$x(...).addEventListener$2 is not a function)
js_primitives.dart:47     at Object.addEventListener$2$x (http://localhost:65055/main.dart.js:28209:43)
js_primitives.dart:47     at MyHomePage_build_closure0.call$0 (http://localhost:65055/main.dart.js:92205:9)
js_primitives.dart:47     at _InkResponseState._handleTap$0 (http://localhost:65055/main.dart.js:65650:27)
js_primitives.dart:47     at tear_off.<anonymous> (http://localhost:65055/main.dart.js:7277:45)
js_primitives.dart:47     at TapGestureRecognizer.invokeCallback$1$3$debugReport (http://localhost:65055/main.dart.js:62520:27)
js_primitives.dart:47     at TapGestureRecognizer.invokeCallback$2 (http://localhost:65055/main.dart.js:62530:19)
js_primitives.dart:47     at TapGestureRecognizer.handleTapUp$2$down$up (http://localhost:65055/main.dart.js:62849:18)
js_primitives.dart:47     at TapGestureRecognizer._checkUp$0 (http://localhost:65055/main.dart.js:62791:13)
js_primitives.dart:47     at TapGestureRecognizer.handlePrimaryPointer$1 (http://localhost:65055/main.dart.js:62720:15)
js_primitives.dart:47     at TapGestureRecognizer.handleEvent$1 (http://localhost:65055/main.dart.js:62641:17)
```

<details>
<summary>Code sample</summary>

Example in the repo

</details>

<details>
  <summary>Logs</summary>

```
NoSuchMethodError: method not found: 'addEventListener$2' (J.getInterceptor$x(...).addEventListener$2 is not a function)
js_primitives.dart:47     at Object.addEventListener$2$x (http://localhost:65055/main.dart.js:28209:43)
js_primitives.dart:47     at MyHomePage_build_closure0.call$0 (http://localhost:65055/main.dart.js:92205:9)
js_primitives.dart:47     at _InkResponseState._handleTap$0 (http://localhost:65055/main.dart.js:65650:27)
js_primitives.dart:47     at tear_off.<anonymous> (http://localhost:65055/main.dart.js:7277:45)
js_primitives.dart:47     at TapGestureRecognizer.invokeCallback$1$3$debugReport (http://localhost:65055/main.dart.js:62520:27)
js_primitives.dart:47     at TapGestureRecognizer.invokeCallback$2 (http://localhost:65055/main.dart.js:62530:19)
js_primitives.dart:47     at TapGestureRecognizer.handleTapUp$2$down$up (http://localhost:65055/main.dart.js:62849:18)
js_primitives.dart:47     at TapGestureRecognizer._checkUp$0 (http://localhost:65055/main.dart.js:62791:13)
js_primitives.dart:47     at TapGestureRecognizer.handlePrimaryPointer$1 (http://localhost:65055/main.dart.js:62720:15)
js_primitives.dart:47     at TapGestureRecognizer.handleEvent$1 (http://localhost:65055/main.dart.js:62641:17)
```

- `flutter analyze`

NONE

- `flutter doctor -v` on Windows

```sh
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1466], locale en-US)
    • Flutter version 2.8.1 at C:\Users\sunbr\google\flutter-2.8.x
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 77d935af4d (6 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\sunbr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.32.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 97.0.1072.69

! Doctor found issues in 2 categories.
```

</details>

**Comment by maheshmnj** [comment] 2022-01-27 13:28
Hi @Sunbreak, Thanks for filing the issue. I am able to reproduce the issue on both stable and the master channel. The error comes only in profile and release mode and works fine in debug mode.


<details>
<summary>chrome console logs(profile mode)</summary>

```
Installed new service worker.
js_primitives.dart:47 NoSuchMethodError: method not found: 'addEventListener$2' (J.getInterceptor$x(...).addEventListener$2 is not a function)
js_primitives.dart:47     at Object.addEventListener$2$x (http://localhost:54367/main.dart.js:28209:43)
js_primitives.dart:47     at MyHomePage_build_closure0.call$0 (http://localhost:54367/main.dart.js:92205:9)
js_primitives.dart:47     at _InkResponseState._handleTap$0 (http://localhost:54367/main.dart.js:65650:27)
js_primitives.dart:47     at tear_off.<anonymous> (http://localhost:54367/main.dart.js:7277:45)
js_primitives.dart:47     at TapGestureRecognizer.invokeCallback$1$3$debugReport (http://localhost:54367/main.dart.js:62520:27)
js_primitives.dart:47     at TapGestureRecognizer.invokeCallback$2 (http://localhost:54367/main.dart.js:62530:19)
js_primitives.dart:47     at TapGestureRecognizer.handleTapUp$2$down$up (http://localhost:54367/main.dart.js:62849:18)
js_primitives.dart:47     at TapGestureRecognizer._checkUp$0 (http://localhost:54367/main.dart.js:62791:13)
js_primitives.dart:47     at TapGestureRecognizer.handlePrimaryPointer$1 (http://localhost:54367/main.dart.js:62720:15)
js_primitives.dart:47     at TapGestureRecognizer.handleEvent$1 (http://localhost:54367/main.dart.js:62641:17)
2js_primitives.dart:47 Another exception was thrown: Instance of 'ErrorSummary'
```
</details>

<details>
<summary>chrome console logs (release)</summary>

```
Installed new service worker.
js_primitives.dart:47 NoSuchMethodError: method not found: 'eD' (J.j(...).eD is not a function)
js_primitives.dart:47     at Object.o_ (http://localhost:56473/main.dart.js:15329:25)
js_primitives.dart:47     at NJ.$0 (http://localhost:56473/main.dart.js:46859:8)
js_primitives.dart:47     at tq.wO (http://localhost:56473/main.dart.js:33719:15)
js_primitives.dart:47     at tear_off.<anonymous> (http://localhost:56473/main.dart.js:3831:79)
js_primitives.dart:47     at eM.AC (http://localhost:56473/main.dart.js:31935:9)
js_primitives.dart:47     at eM.fm (http://localhost:56473/main.dart.js:31939:21)
js_primitives.dart:47     at eM.Ah (http://localhost:56473/main.dart.js:32091:17)
js_primitives.dart:47     at eM.vN (http://localhost:56473/main.dart.js:32064:3)
js_primitives.dart:47     at eM.Af (http://localhost:56473/main.dart.js:32027:3)
js_primitives.dart:47     at eM.j1 (http://localhost:56473/main.dart.js:31992:16)
js_primitives.dart:47 Another exception was thrown: Instance of 'minified:em<void>'

```
</details>


<details>
<summary>debug logs</summary>

```
mahesh@Maheshs-MacBook-Air-M1 example % flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             20.2s
This app is linked to the debug service: ws://127.0.0.1:54138/eXLVZ5oY8cE=/ws
Debug service listening on ws://127.0.0.1:54138/eXLVZ5oY8cE=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:54138/eXLVZ5oY8cE=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:54138/eXLVZ5oY8cE=
hid.subscribeConnect success
hid.subscribeDisconnect success
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.3:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 13 Pro (mobile) • 0FA2FB93-2A89-4FDB-8293-DF66188F1E54 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.307, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.10.0-1.0.pre.307 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b7424c619c (7 hours ago), 2022-01-26 17:25:45 -0800
    • Engine revision c248c6e38e
    • Dart version 2.17.0 (build 2.17.0-63.0.dev)
    • DevTools version 2.10.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 97.0.4692.99

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by redDwarf03** [comment] 2022-01-27 18:00
@maheshmnj hello. have you a temporary solution to generate and deploy a build in debug mode please ?

**Comment by ditman** [comment] 2022-01-27 20:29
I suspect this has to do with the JS-interop code; maybe it's attempting to extend a `@Native` type or hitting some of the current limitations of `dart:js`?

I'm going to invoke @srujzs on this issue to take a quick look, he's seen way more JS-interop code than I have, and will probably be able to spot any weirdness.

**Comment by annagrin** [comment] 2022-01-27 21:42
[dart rotation'] Looks similar to https://github.com/dart-lang/sdk/issues/48240

**Comment by srujzs** [comment] 2022-01-27 21:57
[This](https://github.com/woodemi/web_hid.dart/blob/5f2672c413a0303855a0f67f2c65d8fe2031178d/lib/src/web_hid_base.dart#L22) is the relevant call.

I think this is because there isn't a `@Native` definition for the type `HID`. Even though it's an `EventTarget`, a class binding for the type isn't available in `dart:html`. What this then means on the dart2js side is that the interceptor is `UnknownJavaScriptObject`, the same as any other JS type that isn't bound in `dart:html`. Since a `package:js` class was never written with `addEventListener$2` (the number is the number of parameters), this symbol doesn't exist on that interceptor, and therefore the call fails.

On the DDC side, it's a little more interesting. DDC installs symbols e.g. `dartx.addEventListener` onto the prototype of native types e.g. `EventTarget`. When `delegate.addEventListener` is called, we get `delegate[$addEventListener]` which is translated to `delegate[dartx.addEventListener]`. Here, `delegate` is a `HID` type, which is a native subtype of `EventTarget`. *Because* we install symbols onto the prototype of `EventTarget`, this accurately calls `HID.addEventListener`, leading to the successful behavior. Note that even though `DDC` succeeds in this manner, it isn't (imo) really *intended behavior*.

The correct way to handle this is to use interop to define a `package:js` interface (preferably `@staticInterop` if you want to update to version 0.64) for the native type `HID` and disentangle it from `EventTarget`. It's a bit unfortunate though, since you lose out on the polymorphism, meaning you can't use `EventTarget` as the type of `delegate` if you want to support `HID`s, as the class you define is a `package:js` class, and `EventTarget` is a `@Native` class. @sigmundch @rileyporter , do you have a better way of potentially handling this?

**Comment by Sunbreak** [comment] 2022-01-28 02:43
@srujzs Thanks for your explaination

`@staticInterop` seems to be disabled according to https://github.com/dart-lang/sdk/commit/7990144badcb4b32fd1a99b0964d50e9011264a8

Any other workaround?

**Comment by Sunbreak** [comment] 2022-01-28 03:39
> I think this is because there isn't a `@Native` definition for the type `HID`. Even though it's an `EventTarget`, a class binding for the type isn't available in `dart:html`.

`Bluetooth` has a similiar problem: https://github.com/woodemi/web_blue.dart/blob/bfc826f7064ce6566b6c84a185befd6e32f54b88/lib/src/web_blue_base.dart#L12-L19

There is a `@Native` definition for the type `Bluetooth`

```dart
@Native("Bluetooth")
abstract class _Bluetooth extends Interceptor {
}
```

`subscribeAvailabilitychanged` still fails in profile/release mode while works in debug mode

```dart
  // FIXME allowInterop
  void subscribeAvailabilitychanged(EventListener listener) {
    delegate.addEventListener('availabilitychanged', listener);
  }
```

**Comment by srujzs** [comment] 2022-01-28 17:55
It should be enabled again. That was a temporary CL until we had all the plumbing in place. It will however require updating to `2.16` and `package:js` version `0.64`:

- https://pub.dev/packages/js/versions/0.6.4#interop-with-native-types-using-staticinterop
- https://github.com/dart-lang/sdk/blob/main/sdk/lib/html/doc/WORKAROUNDS.md

If that isn't possible yet, a `@JS` class can be used for `HID`, e.g.

```dart
@JS('HID')
class Hid {
  external void addEventListener(...);
}
```

`Bluetooth` has a slightly different but very similar problem. `Bluetooth` does not extend from `EventTarget` (which we should fix or remove altogether, but that doesn't entirely resolve your polymorphic case) even though a `dart:html` class for it exists, so `addEventListener` isn't visible on that class and therefore its interceptor.

For `Bluetooth`, however, the above alternative (using `@JS()` only without `@staticInterop`) doesn't work. This is because `@Native` classes reserve the native type, unfortunately. `@staticInterop` will resolve your issue with `Bluetooth` as well e.g.

```dart
@JS()
@staticInterop
class JSEventTarget {}

extension JSEventTargetExtension on JSEventTarget {
  external void addEventListener(...);
}
```

Using `JSEventTarget` as the type of `delegate` will get you the polymorphism you desire here. If `@staticInterop` isn't possible, the best alternative might be `dart:js_util` here. You would simply replace `addEventListener` calls on `delegate` with `js_util.callMethod(delegate, 'addEventListener', ...)`.

**Comment by Sunbreak** [comment] 2022-02-03 06:20
> ```dart
> @JS('HID')
> class Hid {
>   external void addEventListener(...);
> }
> ```

https://github.com/woodemi/web_hid.dart/commit/d41ec950981a5c2f24442f0b239b21b03b975db7

It works. Thx

**Comment by ditman** [comment] 2023-03-06 23:19
> https://github.com/woodemi/web_hid.dart/commit/d41ec950981a5c2f24442f0b239b21b03b975db7
> 
> It works. Thx

Closing as fixed.

**Closed by ditman** 2023-03-06 23:19 UTC
Labels: dependency: dart, platform-web, has reproducible steps, blocked, found in release: 2.8, found in release: 2.10
