### ISSUE TITLE
Engine -> Framework roll failing on customer_testing failure

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#138813] opened 2023-11-21 15:42 UTC
Starting with https://github.com/flutter/flutter/pull/138777 which contained only the Dart SDK roll https://github.com/flutter/engine/pull/48257, the Engine -> Framework roll started failing on customer_testing as in:

https://ci.chromium.org/ui/p/flutter/builders/try/Windows%20customer_testing/67455/overview

The failure in the logs looks like:
```
>> dart fix --apply
| Computing fixes in devtools_test...
| Error from the analysis server: Exception while getting bulk fixes: type 'YamlMap' is not a subtype of type 'YamlScalar' in type cast
| #0      PubspecFixGenerator._addMissingDependency (package:analysis_server/src/services/correction/fix/pubspec/fix_generator.dart:217:39)
| <asynchronous suspension>
| #1      PubspecFixGenerator.computeFixes (package:analysis_server/src/services/correction/fix/pubspec/fix_generator.dart:121:7)
| <asynchronous suspension>
| #2      BulkFixProcessor._runPubspecValidatorAndFixGenerator (package:analysis_server/src/services/correction/bulk_fix_processor.dart:952:14)
| <asynchronous suspension>
| #3      BulkFixProcessor._computeChangesToPubspec (package:analysis_server/src/services/correction/bulk_fix_processor.dart:399:20)
| <asynchronous suspension>
| #4      EditBulkFixes.handle (package:analysis_server/src/handler/legacy/edit_bulk_fixes.dart:56:22)
| <asynchronous suspension>
| #5      LegacyAnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:559:11)
| <asynchronous suspension>
| #6      OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:172:14)
| <asynchronous suspension>
| #7      LegacyAnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/legacy_analysis_server.dart:540:7)
| <asynchronous suspension>
```

So, it seems like the cause might be the re-land here https://dart.googlesource.com/sdk.git/+/3c3dd78bc1fb10666bc8033c7affb04a3bfb8ed0

cc @keertip @eyebrowsoffire

**Comment by zanderso** [comment] 2023-11-21 15:48
Reverting the Dart SDK rolls here https://github.com/flutter/engine/pull/48272

**Comment by eyebrowsoffire** [comment] 2023-11-21 17:42
I confirmed locally that reverting the dart change fixes the issue. Revert is here: https://dart-review.googlesource.com/c/sdk/+/337603.

Steps to reproduce the crash:
* Clone https://github.com/flutter/devtools
* cd into `devtools/packages/devtools_test`
* Run `flutter packages get` and then `dart fix --apply`

With https://dart-review.googlesource.com/c/sdk/+/337160 it crashes, without it it doesn't.

**Comment by goderbauer** [comment] 2023-11-21 23:40
(critical triage): @eyebrowsoffire I assigned this to you since you seem to be looking into this. Please re-assign if necessary.

**Closed** 2023-11-27 18:32 UTC
Labels: dependency: dart, P0, team-engine
