### ISSUE TITLE
The color of the container shines through the picture

### ISSUE THREAD

**Issue by politebarista** [flutter/flutter#91021] opened 2021-09-30 10:54 UTC
<img src="https://i.imgur.com/6BeaTMi.png"/>

Hi everybody. Caught this bug recently at work. The point is this: The container has a background, which is red, it also has a background image, which is a duck on a white background. The fit used for the image - cover. The red thin line at the bottom and left of the photo is not part of the photo - it is the color of the container.

## Steps to Reproduce
Create a container and give it a background color, and set a decoration image for the container. Ready to go :)

p.s. For some reason the picture doesn't display correctly. Direct link to the picture: https://imgur.com/6BeaTMi

**Comment by maheshmnj** [comment] 2021-09-30 12:49
Hi @politebarista Thanks for filing the issue. Please share the output of `flutter doctor -v` I could not reproduce the issue on the latest `stable 2.5.1`.

<img src="https://user-images.githubusercontent.com/31410839/135457781-78f75724-de53-49dc-bea8-38acb5193a43.png" width ="300">



<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home:
          // MyStatelessWidget()
          const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  String selected = 'Doge';
  final String imageUrl =
      'https://static.wikia.nocookie.net/heroes-and-villians/images/2/2a/150985468.jpg';
  bool toggle = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              height: 200,
              width: 200,
              decoration: BoxDecoration(
                color: Colors.red,
                image: DecorationImage(
                  image: NetworkImage("$imageUrl"),
                  fit: BoxFit.cover,
                ),
              ),
              // child: Image.network('$imageUrl', fit: BoxFit.cover),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30)
      (emulator)
    • iPhone X (mobile)         • B6C32C16-12A3-4613-9ADF-8C521ACD6302 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 11.6 20G165
      darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome
      94.0.4606.61

• No issues found!
```
</details>

**Comment by politebarista** [comment] 2021-09-30 13:45
Thank you for your prompt reply.
I just updated the flutter version, but the shine is still there. I used your code to create this screenshot.
<img src="https://imgur.com/Wz0HL6L">

<details><summary>flutter doctor -v</summary>
<p>
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale ru-RU)
    • Flutter version 2.5.1 at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\polit\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\polit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.61
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 94.0.992.31

• No issues found!
</p>
</details>

**Comment by maheshmnj** [comment] 2021-09-30 14:25
@politebarista thanks for the info, does this issue reproduce only on a specific emulator or real device too?

>There's something wrong with the screenshot again: https://imgur.com/a/VoTWdbZ

The reason being the URL is a web page URL and not a image Url.

Thanks

**Comment by politebarista** [comment] 2021-09-30 15:55
I just checked - the bug is reproduced on at least two other devices:
1. real one - ASUS ZenFone Max Pro M1, Android 9, build: PKQ1.WW_Phone-16.2017.2009.087-20200826
2. virtual device - Pixel 4 XL API 30, Android 11 (Google APIs)

The screenshots correspond to the devices
<img src="https://i.imgur.com/R23qIS2.jpg" width=300 /><img src="https://i.imgur.com/AZygEdi.png" width=300 />

It's a bit strange that the arrangement of the lines is different. Also, I want to say that this is not a Windows specific bug, because at work I use an iMac for development. The same bug was noticed on it as well.

**Comment by maheshmnj** [comment] 2021-10-01 06:39
Thanks for the details, I could reproduce it on an ios simulator, but not on few other devices like Xiaomi K20 pro, Pixel 3a emulator (Api 30,31).  This looks like more of a device-specific issue, Please refer the reproducible output for more details. 

### Reproducible
<details>
<summary>Reproducible Output</summary>

iPhone 12 pro (simulator)              |  Enlarged Image
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/31410839/135572819-e532080f-6814-435c-938f-8f4bd16b4652.png)  |  ![](https://user-images.githubusercontent.com/31410839/135573226-9d7e3346-a552-4dce-a9e9-ce6bbd623e43.png)

The issue can be easily reproduced on a Desktop or web as well by resizing the window (external monitor) 

https://user-images.githubusercontent.com/31410839/135574997-91fd1ad1-0688-4da8-9520-31797541bf57.mov


But when I bring the window to my main screen (mac) issue is not reproducible so probably related to screen density and resolution.

https://user-images.githubusercontent.com/31410839/135575898-e3fa9262-42d6-4e47-89a9-bd29e0d0dd61.mov


</details>


<details>
<summary>Not reproducible output</summary>

Xiaomi K20 pro (real device)            |  Pixel 3a api 30 (Emulator)
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/31410839/135574062-026817bb-056b-4928-b491-f35549ede316.png)  |  ![](https://user-images.githubusercontent.com/31410839/135574154-57ac09c6-2488-494f-b0ce-eeccfb61b3c5.png)

</details>



<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.5.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (13 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (5 available)
    • Redmi K20 Pro (mobile)                        • android-arm64  • Android 11 (API
      30)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API
      30) (emulator)
    • iPhone 12 Pro (mobile)    • F4DD7611-6C3F-4E04-B1BD-18ACA85F14AE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 11.6 20G165
      darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome
      94.0.4606.71

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.165, on macOS 11.6 20G165 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-12.0.pre.165 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a20743ddfe (3 hours ago), 2021-09-30 23:43:02 -0400
    • Engine revision 8ec71b64f6
    • Dart version 2.15.0 (build 2.15.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (5 available)
    • Redmi K20 Pro (mobile)                        • android-arm64  • Android 11 (API
      30)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API
      30) (emulator)
    • iPhone 12 Pro (mobile)    • F4DD7611-6C3F-4E04-B1BD-18ACA85F14AE • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)           • macos                                • darwin-arm64   • macOS 11.6 20G165
      darwin-arm
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome
      94.0.4606.71

• No issues found!
```
</details>

**Comment by gktc** [comment] 2021-10-02 05:21
Hey, may I try to resolve this issue? I think I can solve this one.

**Comment by maheshmnj** [comment] 2021-10-04 05:56
@gktc sure, assigning it to you.

**Comment by gktc** [comment] 2021-10-04 06:41
![screenshot](https://user-images.githubusercontent.com/85929063/135804598-71f5ced4-5520-40de-99d7-66deb1b9dd90.png)

- I changed the **background color** to _white_ instead of _red_ and it was working fine for me in different emulators.
- This screenshot was taken on the flutter emulator.

**Comment by gktc** [comment] 2021-10-04 07:08
![pixel](https://user-images.githubusercontent.com/85929063/135807960-19106598-06c7-477b-943c-987a170bbd90.PNG)

### Code
<details>
<h2>I've changed the background color to white otherwise red color will pop up based on the size of your image.</h2>
<p>

```python
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home:
          // MyStatelessWidget()
          const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  String selected = 'Doge';
  final String imageUrl =
      'https://static.wikia.nocookie.net/heroes-and-villians/images/2/2a/150985468.jpg';
  bool toggle = false;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text("This is on PIXEL XL API 29"),
            Container(
              height: 200,
              width: 200,
              decoration: BoxDecoration(
                color: Colors.white,
                image: DecorationImage(
                  image: NetworkImage(imageUrl),
                  fit: BoxFit.fill,
                ),
              ),
              // child: Image.network('$imageUrl', fit: BoxFit.cover),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

**Comment by politebarista** [comment] 2021-10-04 07:49
@gktc Bug is still here. The white is still showing through, but you can't see it because of the background color of the picture.

**Comment by maheshmnj** [comment] 2021-10-04 08:07
@gktc this isn't reproducible on all devices.

**Comment by gktc** [comment] 2021-10-04 08:12
> @gktc this isn't reproducible on all devices.

Can you tell me which devices have this problem?

**Comment by gktc** [comment] 2021-10-04 08:14
> @gktc Bug is still here. The white is still showing through, but you can't see it because of the background color of the picture.

If you want to remove the background of the image it would be better to make it as a png and remove the background and then using it.

**Comment by gktc** [comment] 2021-10-04 08:49
https://user-images.githubusercontent.com/85929063/135820079-0f3a7c7c-115c-43b9-ab6f-828691acf7a0.mp4

**Comment by maheshmnj** [comment] 2021-10-04 10:12
> Can you tell me which devices have this problem?
As @politebarista  mentioned above

> real one - ASUS ZenFone Max Pro M1, Android 9, build: PKQ1.WW_Phone-16.2017.2009.087-20200826
> virtual device - Pixel 4 XL API 30, Android 11 (Google APIs)

and on web/Desktop I could reproduce on an external monitor and not on the primary Display.

**Comment by maheshmnj** [comment] 2021-10-04 10:17
> If you want to remove the background of the image it would be better to make it as a png and remove the background and then using it.

It's not about removing the image background, But about the container's decoration color that is visible when the decoration image is covering the container.

**Comment by gktc** [comment] 2021-10-04 10:35
Yeah, thank you @maheshmnj and I got the same issue @politebarista while simulating on chrome after giving the background color. When I did the simulation on Pixel 4 it was working fine without red lines. So it may be due to some bugs.
Thank you.

**Comment by maheshmnj** [comment] 2021-10-04 10:54
@gktc you may unassign yourself if you won't be working on this issue so that others can take over.

Thanks

**Comment by goderbauer** [comment] 2022-03-02 23:31
This looks like an antialiasing problem. The problem occurs because of the mapping from logical pixels to device pixels. There's an open issue for a documentation fix: https://github.com/flutter/flutter/issues/14288

More info about the problem can be found here:
https://github.com/flutter/flutter/issues/25009
https://github.com/flutter/flutter/issues/14288 (comment)
https://github.com/flutter/flutter/issues/17084 (comment)
https://github.com/flutter/flutter/issues/15035 (comment)

**Closed by goderbauer** 2022-03-02 23:31 UTC
Labels: e: device-specific, framework, severe: rendering, has reproducible steps, found in release: 2.5, found in release: 2.6
