### ISSUE TITLE
Error when Deploying iOS app with Xcode 10.2

### ISSUE THREAD

**Issue by v-rohith** [flutter/flutter#39425] opened 2019-08-28 19:27 UTC
I'm trying to deploy an iOS app through Xcode by archiving it and then deploying it using the Development option. The archiving works fine but when I try to deploy, it returns me the follow error.

Failed to verify bitcode in Flutter.framework/Flutter:
error: Cannot extract bundle from /var/folders/vv/tzfmqkn92ss1xsc_pwfld4bm0000gn/T/XcodeDistPipeline.~~~k6v9M2/Root/Payload/Runner.app/Frameworks/Flutter.framework/Flutter (armv7)

But this archiving and deploying has worked for many months and I've been doing it for many versions of the app. But this error came about yesterday when I was trying to roll out a new update.

**Comment by jmagman** [comment] 2019-08-29 00:34
Duplicate of https://github.com/flutter/flutter/issues/39222.

@v-rohith Can you `flutter upgrade` and try again?

**Closed by jmagman** 2019-08-29 00:34 UTC
