### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#66338] opened 2020-09-22 10:07 UTC
I tried to release build an android apk and install it. It's stuck on my splash screen. I checked my log and found it.

**flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --flavor dev -t lib/main_dev.dart**

```
2020-09-22 15:35:20.246 23493-23547/? I/vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib/hw/gralloc.msm8953.so from the current namespace instead.
2020-09-22 15:35:20.259 1470-3752/? V/WindowManager: finishDrawingLocked: mDrawState=COMMIT_DRAW_PENDING Window{27911ec u0 com.orelgodriver.dev/com.orelgodriver.dev.MainActivity} in Surface(name=com.orelgodriver.dev/com.orelgodriver.dev.MainActivity)
2020-09-22 15:35:20.266 1470-1588/? D/ViewRootImpl@91e31cb[dev]: dispatchDetachedFromWindow
2020-09-22 15:35:20.267 1470-1588/? D/InputEventReceiver: channel '3093da8 Splash Screen com.orelgodriver.dev (client)' ~ Disposing input event receiver.
2020-09-22 15:35:20.267 1470-1588/? D/InputEventReceiver: channel '3093da8 Splash Screen com.orelgodriver.dev (client)' ~NativeInputEventReceiver.
2020-09-22 15:35:20.269 1470-1588/? D/InputTransport: Input channel destroyed: fd=430
2020-09-22 15:35:20.269 1470-1588/? D/InputTransport: Input channel destroyed: fd=432
2020-09-22 15:35:20.272 1470-1931/? V/WindowManager: rotationForOrientationLw(orient=12, last=0); user=0 USER_ROTATION_LOCKED sensorRotation=-1 mLidState=-1 mDockMode=0 mHdmiPlugged=false
2020-09-22 15:35:20.280 1470-1494/? I/ActivityManager: Displayed com.orelgodriver.dev/.MainActivity: +673ms
2020-09-22 15:35:20.280 1470-1494/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
2020-09-22 15:35:20.280 1470-1494/? E/ANDR-PERF-JNI: gIOPHAl initialized
2020-09-22 15:35:20.282 393-393/? W//system/bin/hwservicemanager: getTransportFromManifest: Cannot find entry vendor.qti.hardware.iop@1.0::IIop in either framework or device manifest, using default transport.
2020-09-22 15:35:20.313 532-532/? I/SurfaceFlinger: Display 0 HWC layers:
        type    |    handle    | flag |  format   |   source crop (l,t,r,b)    |         frame       | name 
    ------------+--------------+------+-----------+----------------------------+---------------------+------
     SolidColor |              | 0002 |  Unknown  |   0.0    0.0   -1.0   -1.0 |    0    0 1080 1920 | Background for - SurfaceView - com.o[...]godriver.dev.MainActivity@97d20c@0#0
         Device | 0x728607c380 | 0000 | RGBA_8888 |   0.0    0.0 1080.0 1920.0 |    0    0 1080 1920 | com.orelgodriver.dev/com.orelgodriver.dev.MainActivity#0
         Device | 0x72861bf480 | 0002 | RGBA_8888 |   0.0    0.0 1080.0 1920.0 |    0    0 1080 1920 | Splash Screen com.orelgodriver.dev#0
         Device | 0x72861bfe00 | 0000 | RGBA_8888 |   0.0    0.0 1080.0   72.0 |    0    0 1080   72 | StatusBar#0
2020-09-22 15:35:20.318 1470-1494/? E/ANDR-PERF-JNI: gIOPHAl calling iopstart from default
2020-09-22 15:35:20.318 1470-1494/? E/ANDR-IOP: IOP HAL: Received pkg_name = com.orelgodriver.dev pid = 23493
2020-09-22 15:35:20.318 1470-1494/? E/ANDR-IOP: event data pool ran empty
2020-09-22 15:35:20.319 1470-1494/? D/CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1689600  uid : 1000  pid : 1470  pkgName : AMS_RESUME_TAIL@CPU_MIN@54
2020-09-22 15:35:20.319 1470-1494/? D/ActivityManagerPerformance: AMP_acquire() TAIL
2020-09-22 15:35:20.319 1470-1494/? D/CustomFrequencyManagerService: FrequencyrequestList.getNextSchedTunePolicyRequest, index: 0
2020-09-22 15:35:20.319 1470-1494/? D/CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 2208000  uid : 1000  pid : 1470  tag : AMS_APP_SWITCH@CPU_MIN@48
2020-09-22 15:35:20.319 1470-1494/? D/ActivityManagerPerformance: AMP_release() APP_SWITCH
2020-09-22 15:35:20.326 3127-3127/? D/StageManager: saved stages : inStack [1, 2] , outStack[]
2020-09-22 15:35:20.334 23493-23532/? D/libGLESv2: STS_GLApi : DTS, ODTC are not allowed for Package : com.orelgodriver.dev
2020-09-22 15:35:20.334 23493-23531/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159)
    <asynchronous suspension>
    #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:361)
    <asynchronous suspension>
    #2      PackageInfo.fromPlatform (package:package_info/package_info.dart:43)
    <asynchronous suspension>
    #3      SplashLogic.versionCheck (package:orel_go_driver/screens/Splash/logic/splashLogic.dart:15)
    <asynchronous suspension>
    #4      _SplashState.initState.<anonymous closure>.<anonymous closure> (package:orel_go_driver/screens/Splash/splash.dart:21)
    <asynchronous suspension>
```

And I remove packge_info plugin and tried it. now it's said,

`Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/sharedpreference)`.

Please help me to fix this.

**Comment by darshankawar** [comment] 2020-09-22 12:18
Hi @bhanuka96,
I think the issue is occurring if you do a release build with `shrink` flag. If you try with `no-shrink`, I guess you won't see the error, correct ? I remember you saying something like this [here](https://github.com/flutter/flutter/issues/64169#issuecomment-692745028).  Is it the same issue or different one ?

Please see [this](https://github.com/flutter/flutter/issues/65334) open issue which talks about same issue you are facing. Please follow-up there for updates and any questions.
I am closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-09-22 12:18 UTC

**Comment by bhanuka96** [comment] 2020-09-22 12:20
@darshankawar why did you close without any solution? my other projects are working without issuing `no-shrink`. by the way I don't use this. please re-open. please don't close

**Comment by bhanuka96** [comment] 2020-09-22 12:22
@darshankawar this is not a solution right?

**Comment by darshankawar** [comment] 2020-09-22 12:45
@bhanuka96 No that's not the solution and I am not recommending to use that command. I closed this issue, since there's already a similar open issue that will be worked upon soon with a fix.
