### ISSUE TITLE
With Textformfield the cursor cannot move at the middle of a word.

### ISSUE THREAD

**Issue by GENL** [flutter/flutter#58638] opened 2020-06-03 22:37 UTC
Hi! With TextFormField and TextField if tap a word inside of the field the cursor is not moved at the place. It moves only when I type a white space. 
Is it voluntary from Flutter, how cannot we change this behavior?

I have been dealing with this behavior on all flutter channels for a long time.

**Comment by VladyslavBondarenko** [comment] 2020-06-04 09:27
I can change cursor position by tapping on Android. On iOS I can't change it by tapping, but I can drag the cursor, the same and for native android apps.
I cannot change cursor position in web and desktop (tried MacOS desktop)

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.19.0-4.0.pre.47, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.19.0-4.0.pre.47 at /Users/nevercode/dev/flutter
    • Framework revision 28138ec5e3 (5 hours ago), 2020-06-04 00:33:01 -0400
    • Engine revision 2608f2ee9f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 54adfeb93f)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • Redmi Note 7 • 6345c469   • android-arm64  • Android 9 (API 28)
    • macOS        • macOS      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server   • web-server • web-javascript • Flutter Tools
    • Chrome       • chrome     • web-javascript • Google Chrome 83.0.4103.61

• No issues found!
```

</details>

@GENL do you mean web?

**Comment by GENL** [comment] 2020-06-04 10:03
No not web. This behavior happens on Android devices.

**Comment by GENL** [comment] 2020-06-04 10:13
@VladyslavBondarenko your answer helped me. When I read you I asked myself if the problem wasn't by my side. So I looked up through my app and I found out in the ThemeData of the MaterialApp, I had set platform: Platform.ios instead of Platform.android.

Everything is ok now. Thanks

**Comment by VladyslavBondarenko** [comment] 2020-06-04 12:47
@GENL 
I'll reopen it in order to keep track the issue about web and desktop

**Comment by VladyslavBondarenko** [comment] 2020-06-11 08:11
@mdebbar 
I left the issue open not because of iOS, but because of web and desktop (tried with MacOS desktop), where I can't move cursor to the middle of words as well.
Tried with current beta `1.19.0-4.1.pre`, current dev `1.19.0-5.0.pre`, current master `1.19.0-6.0.pre.57`.

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: Center(
          child: TextField(),
        ),
      ),
    );
  }
}
```

</details>

**Comment by geriby23** [comment] 2020-06-18 15:01
I have the same issue. I'm on macOS and I can't move the cursor to the middle of the word by my mouse(It's flutter web).
But I have tested it on the different platforms and noticed that flutter web when it's running on some other OS(for example Windows) has the behavior of an android app where I'm able to put the cursor in the middle of the word. And macOS have the behavior of the ios app.  I think flutter web inputs should have a unique solution for this, the user should be able to edit his input by clicking on the typo place by mouse. Currently, there is a possibility for macOS users to edit input word by placing cursor with arrow buttons.

**Comment by phackwer** [comment] 2020-06-18 16:51
Originally (about a month-45 days ago) we didn't had this issue.

**Comment by pedromassangocode** [comment] 2020-12-23 10:51
Hi @GENL @VladyslavBondarenko 
I cannot reproduce the issue anymore on latest `master` channel.

![gif](https://user-images.githubusercontent.com/67424416/102988882-fb237700-4514-11eb-8f17-bfe0e0ebfae8.gif)

Closing as probably fixed, if you disagree please feel free to write a comment providing more details bellow and I will reopen it.
Thank you

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.117, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.117 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 15c009b805 (10 hours ago), 2020-12-22 20:09:03 -0500
    • Engine revision b7cd3f8e70
    • Dart version 2.12.0 (build 2.12.0-173.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Closed by pedromassangocode** 2020-12-23 10:51 UTC
Labels: P5, a: desktop, a: text input, f: material design, found in release: 1.18, found in release: 1.19, framework, has reproducible steps, platform-web

**Comment by emreakcan** [comment] 2021-05-08 18:27
Hey all, I'm having this issue on ios 12 pro max simulator.

https://user-images.githubusercontent.com/29652273/117549583-22499380-b033-11eb-8b7d-4b9aa775ca2b.mov
```

[✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-GB)
    • Flutter version 2.0.6 at /Users/emreakcan/Documents/flutter
    • Framework revision 1d9032c7e1 (9 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/emreakcan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.4
    • Dart plugin version 203.8173

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • F146217F-A73A-4E38-9E16-5EB713374255 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

**Comment by Sylvain17** [comment] 2021-05-24 13:27
Because I thought the bug was here again 
==> Normal behavior on iOS
For "Hello world" 
- If you only tap, the cursor is placed at the beginning or at the end of one of your words
- If you "tap & hold" you can go inside the word (and at the same time, "Paste | Select All" becomes visible)
It's ok for me (iOS 14.5.1 / flutter stable channel 2.2.0)

**Comment by jasonhoo95** [comment] 2021-06-23 12:02
is this normal on ios, tap and hold only go inside the word, cause normally you should just tap the word and then should go inside right? I think this is a bug right?

**Comment by jasonhoo95** [comment] 2021-06-23 12:28
This is really a major bugs, most of the ios app they can go inside the text only flutter cannot this is really not user friendly
