### ISSUE TITLE
[1.20] Warning: Podfile is out of date - error: no such module X

### ISSUE THREAD

**Issue by SebAubin** [flutter/flutter#63018] opened 2020-08-05 20:48 UTC
Hi, since I have updated to Flutter 1.20 my app does not build anymore. Before the 1.20, my Podfile was containing a few pods for my Autofill extension written in Swift. Now, when I build the app with I get this message:
```
Warning: Podfile is out of date
  This can cause issues if your application depends on plugins that do not support iOS.
  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile
```

The problem with this warning is that I cannot delete my Podfile since i've modified it to add my pods like this: 
```
...
target 'Runner' do
  use_frameworks!
  pod 'KeychainSwift', '~> 16.0'
  pod 'Just'
  pod 'JOSESwift'
  pod 'CryptoSwift'
  pod 'JGProgressHUD'
  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  use_modular_headers!
  
  # Flutter Pod
...
```

When I do delete my Podfile and re-add my pod inside the new Podfile created by Flutter I get this error:

```
/Users/moi/Documents/git/password-hub-app/ios/autofill/http/HttpRequests.swift:10:8: error: no such module 'Just'
import Just
```

I've tried multiple solution found online but nothing seems to be working.

Here's my flutter doctor -v command:

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.6 19G73, locale fr-CA)
    • Flutter version 1.20.0 at /Users/moi/Documents/git/flutter
    • Framework revision 840c9205b3 (il y a 17 heures), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/moi/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/moi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/moi/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6514223/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone test (mobile) • 00008020-00091D880E21002E • ios • iOS 13.6
```

</details>

**Comment by kaichengyan** [comment] 2020-08-05 21:59
Having the same issue with 1.20. Official plugins in the [flutter/plugins repo](https://github.com/flutter/plugins) that have XCTests (image_picker, for example) also seem to fail tests because of the same issue:

```
/Users/kyleyan/plugins/packages/image_picker/image_picker/ios/Tests/ImageUtilTests.m:7:9: fatal error: module 'image_picker' not found
@import image_picker;
 ~~~~~~~^~~~~~~~~~~~

warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'image_picker_exampleTests' from project 'Runner')


Test session results, code coverage, and logs:
        /Users/kyleyan/Library/Developer/Xcode/DerivedData/Runner-cxumoovbxhqwvkgoudctyzqtmhlu/Logs/Test/Test-Runner-2020.08.05_14-53-03--0700.xcresult

Testing failed:
        Module 'image_picker' not found
        Testing cancelled because the build failed.

** TEST FAILED **


The following build commands failed:
        CompileC /Users/kyleyan/Library/Developer/Xcode/DerivedData/Runner-cxumoovbxhqwvkgoudctyzqtmhlu/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/image_picker_exampleTests.build/Objects-normal/x86_64/MetaDataUtilTests.o /Users/kyleyan/plugins/packages/image_picker/image_picker/ios/Tests/MetaDataUtilTests.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by TahaTesser** [comment] 2020-08-06 10:55
Hi @kaichengyan 
Not able to reproduce this issue on latest `stable` 

### Podfile
```
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  pod 'KeychainSwift', '~> 16.0'
  pod 'Just'
  pod 'JOSESwift'
  pod 'CryptoSwift'
  pod 'JGProgressHUD'
  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  use_modular_headers!
    
  # Flutter Pod

end

```

<details> 
<summary>logs</summary> 

``` 
taha@Tahas-MacBook-Pro ios % pod install
Analyzing dependencies
Downloading dependencies
Installing CryptoSwift (1.3.1)
Installing JGProgressHUD (2.1)
Installing JOSESwift (2.2.1)
Installing Just (0.8.0)
Installing KeychainSwift (16.0.1)
Installing Kingfisher (5.14.1)
Installing SwiftyJSON (4.3.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 7 dependencies from the Podfile and 7 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.20.0 at /Users/taha/Code/flutter_stable
    • Framework revision 840c9205b3 (31 hours ago), 2020-08-04 20:55:12 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • SM M305F (mobile)      • 32003c30dc19668f                     •
      android-arm64 • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.6
    • iPhone 11 (mobile)     • 1EB615AF-5AB9-4AAA-A587-A6642BB79484 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!a
```

</details>

**Comment by pumuckelo** [comment] 2020-08-06 17:53
same issue, needed to downgrade to 1.17.5 because I had custom code in my Podfile and adding it to the new one that I generated with flutter didn't help

**Comment by SebAubin** [comment] 2020-08-06 17:54
Yes, downgrading to 1.17.5 is a temporary fix for me as well

**Comment by kaichengyan** [comment] 2020-08-06 18:06
> Hi @kaichengyan
> Please check this [#45197 (comment)](https://github.com/flutter/flutter/issues/45197#issuecomment-642201335) for solution
> 
> Not able to reproduce this issue on latest `stable`
> 
> ### Podfile
> ```
> # Uncomment the next line to define a global platform for your project
> platform :ios, '13.0'
> 
> target 'Runner' do
>   # Comment the next line if you don't want to use dynamic frameworks
>   use_frameworks!
> 
>   # Pods for Runner
> 
>   pod 'KeychainSwift', '~> 16.0'
>   pod 'Just'
>   pod 'JOSESwift'
>   pod 'CryptoSwift'
>   pod 'JGProgressHUD'
>   pod 'Kingfisher', '~> 5.0'
>   pod 'SwiftyJSON', '~> 4.0'
>   use_modular_headers!
>     
>   # Flutter Pod
> 
> end
> ```
> 
> logs
> flutter doctor -v
> Does this happen in a new project on `1.20`?

Thank you for getting back to us! Deleting and regenerating the Podfile didn't work in my case. For the image_picker plugin, re-running `flutter clean` then `flutter build ios --no-codesign` also didn't solve the issue.

**Comment by TahaTesser** [comment] 2020-08-07 08:33
I’m unable to reproduce the issue to pinpoint the cause, but there are reports from several users. The issue needs further investigation.

**Comment by artrmz** [comment] 2020-08-07 08:56
I had same issue and eventually made it work by removing `Podfile`, `Podfile.lock` and updating plugins to latest versions. I guess the last step for the 'key' as seems like changes to plugins versions cleared some cache maybe?

**Comment by jmagman** [comment] 2020-08-07 16:31
You're right, the Podfile format has changed as of https://github.com/flutter/flutter/pull/59044.  This change was made to support [plugins that do not support the iOS platform](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms) and was developed to hopefully prevent painful developer migrations like this to be necessary in the future by simplifying it, and moving more logic into the Flutter SDK.

The new Podfile looks different, but the [key sections are the same](https://guides.cocoapods.org/syntax/podfile.html).  
### target 'Runner'
There's a `target 'Runner'` section where you can add your custom pods to be embedded in your app.  It calls a Ruby method `flutter_install_all_ios_pods` that now lives in the Flutter SDK and will take care of embedding your Flutter plugins and the Flutter.framework.

```ruby
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

# ADD YOUR CUSTOM PODS HERE!
end
```
@SebAubin Yours would look something like:
```ruby
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  pod 'KeychainSwift', '~> 16.0'
  pod 'Just'
  pod 'JOSESwift'
  pod 'CryptoSwift'
  pod 'JGProgressHUD'
  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
end
```
### project 'Runner'
`project 'Runner` is still at the top and is unchanged.  If you have flavors set up with custom build configurations, copy it from your old Podfile exactly.
```ruby
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
```
for example, if you had a `Staging` build configuration:
```ruby
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Staging' => :release,
  'Release' => :release,
}
```

### post_install
There's also a [`post_install` section](https://guides.cocoapods.org/syntax/podfile.html#post_install) if you have custom build settings or other changes you want to make to your Pod targets.  It calls a Ruby method `flutter_additional_ios_build_settings` that now lives in the Flutter SDK and will take care of setting `ENABLE_BITCODE=NO` and other build settings.
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # YOUR CUSTOM TARGET CODE HERE.
  end
end
```
for example, if your old Podfile set your plugins' `SWIFT_VERSION`:
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.1'
    end
  end
end
```

**Comment by jmagman** [comment] 2020-08-07 22:25
Closing, I added the instructions to https://github.com/flutter/flutter/issues/45197#issuecomment-670602842.  This change is intentional, as the error message indicates.

**Closed** 2020-08-12 13:50 UTC
Labels: customer: crowd, found in release: 1.20, platform-ios, t: xcode, tool, will need additional triage

**Comment by exeptionerror** [comment] 2021-06-26 05:47
All Possible working solution [[Solved] Flutter iOS build failed Warning: Podfile is out of date](https://fluttercorner.com/flutter-ios-build-failed-warning-podfile-is-out-of-date/)
