### ISSUE TITLE
im trying to code flutter in android studio, but when i created an app and try to run on real device, its failed. help me

### ISSUE THREAD

**Issue by Fiv38** [flutter/flutter#23327] opened 2018-10-20 07:20 UTC
Help me, i dont know whats wrong with this. (note : i can run aplication well if i create app on android studio project but when i create flutter on android studio, i got this error logs.)
## Steps to Reproduce

1. created an app flutter in android studio
2. when it done, i try to run it on my real device
3. and i got this error logs

## Logs
```
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: D:\Flutter Dev\venue_loka\android\gradlew.bat app:properties:
Checking the license for package Android SDK Build-Tools 27.0.3 in C:\Program Files (x86)\Android\android-sdk\licenses
License for package Android SDK Build-Tools 27.0.3 accepted.
Preparing "Install Android SDK Build-Tools 27.0.3 (revision: 27.0.3)".
Warning: Failed to read or create install properties file.


FAILURE: Build failed with an exception.

Finished with error: Please review your Gradle project setup in the android/ folder.
* Where:
Build file 'D:\Flutter Dev\venue_loka\android\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Failed to install the following SDK components:
         build-tools;27.0.3 Android SDK Build-Tools 27.0.3
     The SDK directory is not writable (C:\Program Files (x86)\Android\android-sdk)


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
```

**Comment by zoechi** [comment] 2018-10-23 07:34
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2018-12-11 12:56
Probably https://github.com/flutter/flutter/issues/14020#issuecomment-380178542
  - https://stackoverflow.com/questions/44653261/android-dependency-has-different-version-for-the-compile-and-runtime

Duplicate of #14020

**Closed by zoechi** 2018-12-11 12:56 UTC
Labels: waiting for customer response
