### ISSUE TITLE
[connectivity]ConnectivityBroadcastReceiver.java uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by silentchild** [flutter/flutter#60985] opened 2020-07-07 12:34 UTC
When I first added it to the project and executed "flutter run", there will be such a warning, but the program can run, I hope to solve this warning, thank you. Warning content:
Note: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\connectivity-0.4.9\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by silentchild** [comment] 2020-07-07 12:35
connectivity: ^0.4.8+6

Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (7 days ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

**Comment by TahaTesser** [comment] 2020-07-07 13:12
duplicate of https://github.com/flutter/flutter/issues/44580

**Closed by TahaTesser** 2020-07-07 13:12 UTC
