### ISSUE TITLE
showDialog inserts wrong context into builder

### ISSUE THREAD

**Issue by Dommicrafter** [flutter/flutter#52411] opened 2020-03-11 15:21 UTC
## Steps to Reproduce

Tried this issue with stable channel and dev channel both don't work

1. Use any widget
2. call showDialog
3. get the theme of both contextsts and see the difference

My Code looks like this:
```dart
class OverviewState extends State<Overview> {
    Widget build(BuildContext context) {
        ....
           onSelected () {
                showDialog(context: context, builder: (BuildContext buildContext) { //this buildContext is btw empty and dirty
                        var test = Theme.of(context).scaffoldBackgroundColor; //Color(0xff121212)
                        var test2 = Theme.of(buildContext).scaffoldBackgroundColor;//Color(0xfffafafa)
                 }
           }
        ....
    }
}
```

**Expected results:** 

- these theme Colors should be the same

**Actual results:** 

- the Theme Color changed, as a new context was generate, from my point of view

<details>
  <summary>Logs</summary>

```
```

```
[√] Flutter (Channel dev, v1.15.19, on Microsoft Windows [Version 10.0.18362.657], locale de-DE)
    • Flutter version 1.15.19 at D:\Programming-libs\flutter
    • Framework revision 60d0fef17a (34 hours ago), 2020-03-09 22:07:34 -0700
    • Engine revision 0e2c8feeeb
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Dommi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.43.0)
    • VS Code at C:\Users\Dommi\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-03-11 16:34
Hi @Dommicrafter 

<details>
 <summary>with such code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: MyApp()));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: () {
            showDialog(
              context: context,
              builder: (BuildContext buildContext) {
                var test = Theme.of(context)
                    .scaffoldBackgroundColor; //Color(0xff121212)
                var test2 = Theme.of(buildContext)
                    .scaffoldBackgroundColor; //Color(0xfffafafa)
                print(test);
                print(test2);
                return AlertDialog(
                  title: Text('title'),
                  actions: <Widget>[
                    FlatButton(
                      child: Text('Ok'),
                      onPressed: () {
                        Navigator.of(context).pop();
                      },
                    ),
                  ],
                );
              },
            );
          },
        ),
      ),
    );
  }
}
```
</details>

On flutter master v1.15.20 I have expected result

```
I/flutter (11260): Color(0xfffafafa)
I/flutter (11260): Color(0xfffafafa)
```

Could you provide complete minimal code sample to reproduce your issue?

**Comment by Dommicrafter** [comment] 2020-03-12 10:15
Thank you @VladyslavBondarenko 

To conclude: My basic structure is: MaterialApp -> Scaffold -> ListView.seperated -> itemBuilder ->Card -> trailing -> PopupMenuButton -> showdialog

therefore my Code looks sth like this

<details>
    <summary>code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

enum options {
  edit,
  delete,
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      darkTheme: ThemeData.dark().copyWith(primaryColor: Colors.green),
      theme: ThemeData.light().copyWith(primaryColor: Colors.green),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Scaffold(
        appBar: AppBar(
          title: Text("Test"),
        ),
        body: ListView.separated(
            itemBuilder: (BuildContext context, int num) {
              return Card(
                child: ListTile(
                  title: Text("Test"),
                  trailing: PopupMenuButton(onSelected: (result) {
                    showDialog(
                        context: context,
                        builder: (BuildContext buildContext) {
                          var test = Theme.of(context).scaffoldBackgroundColor;
                          var test2 =
                              Theme.of(buildContext).scaffoldBackgroundColor;
                          print(test);
                          print(test2);
                          return AlertDialog(
                            content: Text(
                              "Hello!",
                            ),
                          );
                        });
                  },
                    itemBuilder: (BuildContext context) =>
                    <PopupMenuEntry<options>>[
                      PopupMenuItem<options>(
                        value: options.edit,
                        child: Text("edit"),
                      ),
                      PopupMenuItem<options>(
                        value: options.delete,
                        child: Text("delete"),
                      ),
                    ],),
                ),
              );
            },
            separatorBuilder: (BuildContext context, int index) =>
            const Divider(),
            itemCount: 1),
      ),
      floatingActionButton: FloatingActionButton(
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```
</details>

and it actually works. I have no idea why this works in a new projet but not in my own. As I build the basic structure of the App into the new App...

**Comment by VladyslavBondarenko** [comment] 2020-03-12 10:31
@Dommicrafter 
Then this issue seems to be not actionable, closing it,
If you disagree or can provide extra information about this case 
please write in the comments and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-03-12 10:31 UTC
Labels: waiting for customer response
