### ISSUE TITLE
Search no longer works in examples/stocks

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#9395] opened 2017-04-14 15:04 UTC
I attempted to crib some search code from the stocks example, only to be surprised that it doesn't work. :)

I think it's missing something listening to the onChange of the search box and calling setState on the stocks list?  But I'm not sure the exact right pattern, so filing this issue.

I'm using an iOS simulator with the physical keyboard, but I doubt that matters.

@abarth 

![simulator screen shot apr 14 2017 8 01 43 am](https://cloud.githubusercontent.com/assets/11857803/25046898/c35ffe28-20e8-11e7-9ce9-de5b13af0a46.png)

**Comment by jason-simmons** [comment] 2017-04-17 19:24
fwiw, this is working for me on Android.

Note that the search query will not take effect until the text is committed to the IME and propagates to the TextEditingController (e.g. by tapping the Enter key on Android)

**Comment by eseidelGoogle** [comment] 2017-04-17 20:01
I guess I had just assumed it was live.  I can test on iOS to see if the enter button helped.  I think I tried and it didn't.

**Comment by Hixie** [comment] 2018-01-03 00:19
We're pretty sure this is working as intended.

**Closed by Hixie** 2018-01-03 00:19 UTC
Labels: dev: examples, prod: text input, regression
