### ISSUE TITLE
CocoaPods installed but not initialised

### ISSUE THREAD

**Issue by haita2008** [flutter/flutter#41291] opened 2019-09-25 13:50 UTC
After running pod setup, flutter doctor still returned the following
```
dadas-Mac-mini:~ dada$ pod setup
dadas-Mac-mini:~ dada$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale
    en-AU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
Please help, I only followed the instruction and know very little of each of the command.

**Comment by BondarenkoStas** [comment] 2019-09-25 14:01
It seems to be very similar to #41253. Please try to install lower cocoapods as advised in the issue body. Report please if that will help.

**Comment by yuesaka** [comment] 2019-09-25 17:02
No the OP, but having the same issue.
Installing CoacoaPods 1.7.5 did the trick.

As per solution in #41253: 
`sudo gem uninstall cocoapods`
`sudo gem install cocoapods -v 1.7.5`
`pod setup`

**Comment by c-p-i-o** [comment] 2019-09-25 20:52
@yuesaka FWIW, I had the same issue and downgrading to `1.7.5` worked for me too.  Thanks for suggesting the workaround.

**Comment by tnoor-co** [comment] 2019-09-25 23:40
Worked great on macOS Catalina. Thank you for the fix @yuesaka

**Comment by stuartmorgan** [comment] 2019-09-26 01:21
Duplicate of #41253

**Comment by haita2008** [comment] 2019-09-26 05:30
Many thanks to all, I followed @yuesaka's instruction and flutter doctor found no issue.

**Comment by janmoppel** [comment] 2019-09-26 08:14
Closing this issue, as the solution was found.

**Comment by davidcavazos** [comment] 2019-09-27 17:58
See [workaround](https://github.com/flutter/flutter/issues/41253#issuecomment-536039050)

**Comment by Gaulepal** [comment] 2019-09-27 18:22
As per solution in #41253:
sudo gem uninstall cocoapods
sudo gem install cocoapods -v 1.7.5
pod setup
sudo gem install cocoapods      (if you want latest version)

**Comment by IhwanID** [comment] 2019-10-02 11:29
Nice Thanks

**Comment by NickitaX** [comment] 2019-10-03 07:02
Great, it worked! Thanks @yuesaka 🔥

**Comment by davidair** [comment] 2019-10-07 03:08
I'd recommend avoiding to downgrade CocoaPods unless something is actually broken (other than the warning from flutter doctor).

**Comment by MrSykes** [comment] 2019-10-07 15:14
> I'd recommend avoiding to downgrade CocoaPods unless something is actually broken (other than the warning from flutter doctor).

I agree but it must be broken. I just had the same problem and 1.7.5 fixed it. The issue was that "pod setup" wouldn't do anything. After the downgrade "pod setup" now immediately starts "Setting up CocoaPods master repo" and it appears to be working now.

**Comment by ffrey** [comment] 2019-10-07 15:39
Same as MrSykes, downgrading to 1.7.5 did the trick.

**Comment by kentcb** [comment] 2019-10-14 03:52
I'm surprised this was closed. Whilst the workaround works, it means that cloud builds in Azure take over 7 minutes longer (since that's the cost of uninstalling the newer cocoapods and installing `1.7.5`). Surely the actual solution is to ensure Flutter works with newer versions on cocoapods?

**Comment by BondarenkoStas** [comment] 2019-10-14 10:45
@kentcb this actually was fixed in https://github.com/flutter/flutter/pull/41491 and went to 1.10.7.
https://github.com/flutter/flutter/issues/41253#issuecomment-539124598

**Closed by BondarenkoStas** 2019-10-14 10:45 UTC

**Comment by kentcb** [comment] 2019-10-14 23:17
@BondarenkoStas Great to know - thanks! I'm on stable so can't take advantage of this just yet, but looking forward to it.

**Comment by phamquan** [comment] 2019-10-23 14:28
> As per solution in #41253:
> sudo gem uninstall cocoapods
> sudo gem install cocoapods -v 1.7.5
> pod setup
> sudo gem install cocoapods (if you want latest version)

This is excellent reply

**Comment by kentcb** [comment] 2019-10-23 22:56
@phamquan the workaround isn't required any more because the fix has landed in `stable`. By removing the workaround my build time has dropped by nearly 8 minutes :tada:

**Comment by dkotrada** [comment] 2019-10-30 22:34
> @phamquan the workaround isn't required any more because the fix has landed in `stable`. By removing the workaround my build time has dropped by nearly 8 minutes 🎉

This is not true as of now. It does not work. Only with workaround.

**Comment by akhileshPandey16** [comment] 2019-11-03 18:56
@yuesaka Thanks, only your workaround works as of today on MacOS 10.13.6 High Sierra

**Comment by bakboem** [comment] 2020-02-12 06:34
****sudo  chmod -R 777 [your flutter file folder]
and run: 

--  sudo gem uninstall cocoapods
--  sudo gem install cocoapods -v 1.7.5
--  pod setup

**Comment by giri-gonzai** [comment] 2020-03-28 06:37
@yuesaka , your fix is legendary. Worked for everyone. Kudos

**Comment by Zinkspieler** [comment] 2020-04-08 18:45
For some reason

-- sudo gem uninstall cocoapods
-- sudo gem install cocoapods -v 1.7.5
-- pod setup

installs cocoapods version 1.8.3. Does anyone have any idea why that might be?

**Comment by samuelsennott** [comment] 2020-04-18 06:21
> No the OP, but having the same issue.
> Installing CoacoaPods 1.7.5 did the trick.
> 
> As per solution in #41253:
> `sudo gem uninstall cocoapods`
> `sudo gem install cocoapods -v 1.7.5`
> `pod setup`

Thank you. That worked for me.

**Comment by xis24** [comment] 2020-04-18 22:16
I have tried everything mentioned above, and I'm still getting the following thing. I'm on Mac OS Catalina. Could someone help me here ? Thank you.

[!] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
