### ISSUE TITLE
Keyboard key event listener

### ISSUE THREAD

**Issue by Faiyyaz** [flutter/flutter#61590] opened 2020-07-16 02:37 UTC
Hey,

I want to achieve something for that i need to know if user presses spacebar on his keyboard. So how to know if user presses spacebar? I tried using keyboard listener class and its not working

**Expected results:** I should be able to know when user presses spacebar

**Actual results:** No way to listen key press

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /users/faiyyazkhatri/StudioProjects/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /users/faiyyazkhatri/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /users/faiyyazkhatri/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone X • D3E62461-D931-44CD-842D-DF73590F8890 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!

```

**Comment by TahaTesser** [comment] 2020-07-16 09:34
Hi @Faiyyaz 

`RawKeyboardListener` is working fine on MacOS and Web. 


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  FocusNode _focusNode = new FocusNode();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Center(
          child: RawKeyboardListener(
              focusNode: _focusNode,
              onKey: (RawKeyEvent event) {
                // if (event.runtimeType.toString() == 'RawKeyDownEvent') {
                //   RawKeyEventDataWeb data = event.data as RawKeyEventDataWeb;
                //   String _keyCode;
                //   _keyCode =
                //       data.key.toString(); //keycode of key event (66 is return)

                //   print("$_keyCode is pressed");
                // }

                // if (event.runtimeType.toString() == 'RawKeyDownEvent') {
                //   RawKeyEventDataMacOs data =
                //       event.data as RawKeyEventDataMacOs;
                //   String _keyCode;
                //   _keyCode = data.keyCode
                //       .toString(); //keycode of key event (66 is return)

                //   print("$_keyCode is pressed");
                // }

                print('GOT AN EVENT! $event');
              },
              child: TextField()),
        ),
      ),
    );
  }
}

``` 

</details> 
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (5 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!


```

</details> 

if you're looking iOS key events, there is an open issue for it, f you disagree, please write in the comments and I will reopen it.
Closing as duplicate of https://github.com/flutter/flutter/issues/31945
Thank you

**Closed by TahaTesser** 2020-07-16 09:34 UTC
