### ISSUE TITLE
[tool_crash] RangeError (index): Index out of range: no indices are valid: 0

### ISSUE THREAD

**Issue by rootmap** [flutter/flutter#58389] opened 2020-05-31 21:27 UTC
## Command
```
flutter clean
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
IndexError: RangeError (index): Index out of range: no indices are valid: 0
```
#0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:3932:7)
#1      InputStream.readUint16 (package:archive/src/util/input_stream.dart:206:22)
#2      GZipDecoder._readHeader (package:archive/src/gzip_decoder.dart:89:29)
#3      GZipDecoder.decodeBuffer (package:archive/src/gzip_decoder.dart:26:5)
#4      GZipDecoder.decodeBytes (package:archive/src/gzip_decoder.dart:17:12)
#5      _WindowsUtils.verifyGzip (package:flutter_tools/src/base/os.dart:352:21)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:605:20)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:638:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:604:12)
#9      CachedArtifact._downloadZippedTarball (package:flutter_tools/src/cache.dart:630:12)
#10     GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:1070:12)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:560:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:432:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:698:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
```
```
[✓] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.17.2 at E:\flutter\flutter_kit\flutter
    • Framework revision 5f21edf8b6 (3 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at E:\flutter\flutter_kit\android_sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = E:\flutter\flutter_kit\android_sdk
    ✗ No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in
      your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[✓] Android Studio (version 4.0)
    • Android Studio at E:\flutter\flutter_kit\android_lib
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Android Studio
    • Android Studio at E:\xampp\htdocs\android
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ android-studio-dir = E:\xampp\htdocs\android
    ✗ Android Studio not found at E:\xampp\htdocs\android
    • Try updating or re-installing Android Studio.
    • Consider removing your android-studio-dir setting by running:
      flutter config --android-studio-dir=

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\Fahad Bhuyian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by jonahwilliams** [comment] 2020-05-31 22:01
Duplicate of https://github.com/flutter/flutter/issues/48014

**Closed by jonahwilliams** 2020-05-31 22:01 UTC
