### ISSUE TITLE
[Proposal]Support for `flutter/flutter` dart code auto formatter like flutter/engine's `format.dart -f`

### ISSUE THREAD

**Issue by eggfly** [flutter/flutter#94923] opened 2021-12-09 10:03 UTC
As title. We can use this command for git pre push hook locally and auto format the new commit code locally before running the ci on server.
As main branch now(ref: commit 81fc9a6807958679309f4185026af3ef3a2e05de HEAD -> main, I run `cd packages/flutter && flutter analyze`, the result is:
```

Analyzing flutter...                                                    

  error • Target of URI doesn't exist: 'package:process_runner/process_runner.dart' • test_private/bin/test_private.dart:9:8 • uri_does_not_exist
  error • Undefined class 'ProcessRunner' • test_private/bin/test_private.dart:205:11 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • test_private/bin/test_private.dart:205:34 • avoid_dynamic_calls
  error • The method 'ProcessRunner' isn't defined for the type 'TestCase' • test_private/bin/test_private.dart:205:34 • undefined_method
  error • Undefined class 'ProcessRunnerResult' • test_private/bin/test_private.dart:209:11 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • test_private/bin/test_private.dart:209:46 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • test_private/bin/test_private.dart:213:9 • avoid_dynamic_calls
  error • Undefined class 'ProcessRunner' • test_private/bin/test_private.dart:220:11 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • test_private/bin/test_private.dart:220:34 • avoid_dynamic_calls
  error • The method 'ProcessRunner' isn't defined for the type 'TestCase' • test_private/bin/test_private.dart:220:34 • undefined_method
  error • Undefined class 'ProcessRunnerResult' • test_private/bin/test_private.dart:227:13 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • test_private/bin/test_private.dart:227:48 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • test_private/bin/test_private.dart:231:11 • avoid_dynamic_calls

13 issues found. (ran in 3.3s)
```
![image](https://user-images.githubusercontent.com/922837/145375965-20c0fffd-eade-464c-9d56-5052867bb9f2.png)

**Comment by maheshmnj** [comment] 2021-12-09 10:35
Hi @eggfly, I believe you are talking about formatting flutter code in the repo(not a flutter project) if so please take a look at this https://github.com/flutter/flutter/wiki/Using-the-Dart-analyzer. You should be using `flutter analyze --flutter-repo`

**Comment by eggfly** [comment] 2021-12-09 10:42
@maheshmnj  I want to run the dart auto formatter in flutter framework repo: https://github.com/flutter/flutter, and before I contribute the code, I think there's a convenient way to auto check and auto format my newly written code.
Just like engine's `dart format.dart -f` command. 😄

**Comment by eggfly** [comment] 2021-12-09 10:43
`flutter analyze --flutter-repo` gives a very long result:
```
  error • The name 'IntegrationTestWidgetsFlutterBinding' isn't a type, so it can't be used in an 'as' expression • ../integration_test/test/data/pass_test_script.dart:11:116 • cast_to_non_type
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_test_script.dart:12:3 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_test_script.dart:12:3 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_test_script.dart:12:3 • avoid_dynamic_calls
  error • Missing parameter type for '_' • ../integration_test/test/data/pass_test_script.dart:12:39 • implicit_dynamic_parameter
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_test_script.dart:15:76 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_test_script.dart:18:3 • avoid_dynamic_calls
  error • The function 'testWidgets' isn't defined • ../integration_test/test/data/pass_test_script.dart:18:3 • undefined_function
  error • Undefined class 'WidgetTester' • ../integration_test/test/data/pass_test_script.dart:18:34 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_test_script.dart:19:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/data/pass_test_script.dart:19:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_test_script.dart:22:3 • avoid_dynamic_calls
  error • The function 'testWidgets' isn't defined • ../integration_test/test/data/pass_test_script.dart:22:3 • undefined_function
  error • Undefined class 'WidgetTester' • ../integration_test/test/data/pass_test_script.dart:22:34 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_test_script.dart:23:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/data/pass_test_script.dart:23:5 • undefined_function
  error • Target of URI doesn't exist: 'package:flutter_test/flutter_test.dart' • ../integration_test/test/data/pass_then_fail_test_script.dart:7:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:integration_test/integration_test.dart' • ../integration_test/test/data/pass_then_fail_test_script.dart:8:8 • uri_does_not_exist
  error • Undefined class 'IntegrationTestWidgetsFlutterBinding' • ../integration_test/test/data/pass_then_fail_test_script.dart:11:9 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_then_fail_test_script.dart:11:56 • avoid_dynamic_calls
  error • Undefined name 'IntegrationTestWidgetsFlutterBinding' • ../integration_test/test/data/pass_then_fail_test_script.dart:11:56 • undefined_identifier
  error • The name 'IntegrationTestWidgetsFlutterBinding' isn't a type, so it can't be used in an 'as' expression • ../integration_test/test/data/pass_then_fail_test_script.dart:11:116 • cast_to_non_type
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_then_fail_test_script.dart:12:3 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_then_fail_test_script.dart:12:3 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_then_fail_test_script.dart:12:3 • avoid_dynamic_calls
  error • Missing parameter type for '_' • ../integration_test/test/data/pass_then_fail_test_script.dart:12:39 • implicit_dynamic_parameter
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_then_fail_test_script.dart:15:76 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_then_fail_test_script.dart:18:3 • avoid_dynamic_calls
  error • The function 'testWidgets' isn't defined • ../integration_test/test/data/pass_then_fail_test_script.dart:18:3 • undefined_function
  error • Undefined class 'WidgetTester' • ../integration_test/test/data/pass_then_fail_test_script.dart:18:32 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_then_fail_test_script.dart:19:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/data/pass_then_fail_test_script.dart:19:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_then_fail_test_script.dart:22:3 • avoid_dynamic_calls
  error • The function 'testWidgets' isn't defined • ../integration_test/test/data/pass_then_fail_test_script.dart:22:3 • undefined_function
  error • Undefined class 'WidgetTester' • ../integration_test/test/data/pass_then_fail_test_script.dart:22:32 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/data/pass_then_fail_test_script.dart:23:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/data/pass_then_fail_test_script.dart:23:5 • undefined_function
  error • Target of URI doesn't exist: 'package:flutter_test/flutter_test.dart' • ../integration_test/test/response_serialization_test.dart:5:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:integration_test/common.dart' • ../integration_test/test/response_serialization_test.dart:7:8 • uri_does_not_exist
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:10:3 • avoid_dynamic_calls
  error • The function 'test' isn't defined • ../integration_test/test/response_serialization_test.dart:10:3 • undefined_function
  error • Undefined class 'Failure' • ../integration_test/test/response_serialization_test.dart:11:11 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:11:26 • avoid_dynamic_calls
  error • The function 'Failure' isn't defined • ../integration_test/test/response_serialization_test.dart:11:26 • undefined_function
  error • Undefined class 'Failure' • ../integration_test/test/response_serialization_test.dart:12:11 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:12:30 • avoid_dynamic_calls
  error • Undefined name 'Failure' • ../integration_test/test/response_serialization_test.dart:12:30 • undefined_identifier
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:13:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:13:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:13:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:13:33 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:14:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:14:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:14:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:14:30 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:17:3 • avoid_dynamic_calls
  error • The function 'test' isn't defined • ../integration_test/test/response_serialization_test.dart:17:3 • undefined_function
  error • Undefined class 'Response' • ../integration_test/test/response_serialization_test.dart:18:5 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:21:16 • avoid_dynamic_calls
  error • Undefined name 'Response' • ../integration_test/test/response_serialization_test.dart:21:16 • undefined_identifier
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:22:18 • avoid_dynamic_calls
  error • A value of type 'dynamic' can't be assigned to a variable of type 'String' • ../integration_test/test/response_serialization_test.dart:22:18 • invalid_assignment
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:23:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:23:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:24:16 • avoid_dynamic_calls
  error • Undefined name 'Response' • ../integration_test/test/response_serialization_test.dart:24:16 • undefined_identifier
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:25:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:25:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:25:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:25:37 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:26:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:26:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:26:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:27:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:27:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:27:12 • avoid_dynamic_calls
  error • Undefined class 'Failure' • ../integration_test/test/response_serialization_test.dart:29:11 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:29:26 • avoid_dynamic_calls
  error • The function 'Failure' isn't defined • ../integration_test/test/response_serialization_test.dart:29:26 • undefined_function
  error • Undefined class 'Failure' • ../integration_test/test/response_serialization_test.dart:30:11 • undefined_class
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:30:27 • avoid_dynamic_calls
  error • The function 'Failure' isn't defined • ../integration_test/test/response_serialization_test.dart:30:27 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:31:16 • avoid_dynamic_calls
  error • Undefined name 'Response' • ../integration_test/test/response_serialization_test.dart:31:16 • undefined_identifier
  error • The name 'Failure' isn't a type so it can't be used as a type argument • ../integration_test/test/response_serialization_test.dart:31:42 • non_type_as_type_argument
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:32:18 • avoid_dynamic_calls
  error • A value of type 'dynamic' can't be assigned to a variable of type 'String' • ../integration_test/test/response_serialization_test.dart:32:18 • invalid_assignment
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:33:16 • avoid_dynamic_calls
  error • Undefined name 'Response' • ../integration_test/test/response_serialization_test.dart:33:16 • undefined_identifier
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:34:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:34:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:34:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:34:37 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:35:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:35:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:35:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:36:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:36:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:36:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:36:46 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:39:16 • avoid_dynamic_calls
  error • Undefined name 'Response' • ../integration_test/test/response_serialization_test.dart:39:16 • undefined_identifier
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:40:18 • avoid_dynamic_calls
  error • A value of type 'dynamic' can't be assigned to a variable of type 'String' • ../integration_test/test/response_serialization_test.dart:40:18 • invalid_assignment
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:41:16 • avoid_dynamic_calls
  error • Undefined name 'Response' • ../integration_test/test/response_serialization_test.dart:41:16 • undefined_identifier
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:42:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:42:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:42:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:42:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:43:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:43:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:43:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:43:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:45:16 • avoid_dynamic_calls
  error • Undefined name 'Response' • ../integration_test/test/response_serialization_test.dart:45:16 • undefined_identifier
  error • The name 'Failure' isn't a type so it can't be used as a type argument • ../integration_test/test/response_serialization_test.dart:45:42 • non_type_as_type_argument
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:46:18 • avoid_dynamic_calls
  error • A value of type 'dynamic' can't be assigned to a variable of type 'String' • ../integration_test/test/response_serialization_test.dart:46:18 • invalid_assignment
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:47:16 • avoid_dynamic_calls
  error • Undefined name 'Response' • ../integration_test/test/response_serialization_test.dart:47:16 • undefined_identifier
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:48:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:48:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:48:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:48:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:49:5 • avoid_dynamic_calls
  error • The function 'expect' isn't defined • ../integration_test/test/response_serialization_test.dart:49:5 • undefined_function
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:49:12 • avoid_dynamic_calls
   info • Avoid method calls or property accesses on a "dynamic" target • ../integration_test/test/response_serialization_test.dart:49:12 • avoid_dynamic_calls

100822 issues found. (ran in 36.5s)

```

**Comment by maheshmnj** [comment] 2021-12-09 10:50
Sorry I misunderstood. There isn't any such tool to format code as per the style guide. All formatting is done manually. 
Closing as this isn't really an issue with the flutter framework.

**Comment by eggfly** [comment] 2021-12-09 10:53
Or we can leave this open for discussions and some futher PRs. Thanks~

**Comment by maheshmnj** [comment] 2021-12-09 11:01
sure labeling it as a proposal.

**Comment by nt4f04uNd** [comment] 2021-12-09 12:06
This seems to be a duplicate of https://github.com/flutter/flutter/issues/2025

**Comment by stuartmorgan** [comment] 2021-12-09 12:31
> I want to run the dart auto formatter in flutter framework repo

Per the style guide, flutter/flutter explicitly does not use `dart format`, so what you want to do violates the Flutter style guide; that's not something we want to provide a command to do.

> Just like engine's `dart ci/bin/format.dart -f` command.

The engine repo has a different policy, which is why it has a script.

> And we can update this wiki (https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#formatting) to provide framework contributors a command to do it!

There is no command that can generate manually formatted output, which is the flutter/flutter repo's explicit policy.

(There also seems to be some confusion, you are talking about the auto formatter, but keep posting analyzer output; the two are unrelated.)

**Closed by stuartmorgan** 2021-12-09 12:31 UTC
Labels: severe: new feature, team, tool, proposal, passed first triage

**Comment by AlexV525** [comment] 2021-12-09 16:04
@stuartmorgan I think what he's trying to say is the current analysis workflow is too hard and complex for contributors, especially for those first-time-contributors. Let's try to make things clear and see if they are reasonable.

### Make lint rules more clear or visible to other tools

We know that we have multiple tests that working for analysis, which means these tests must be follow a collection of rules to detect where commits have style violation. So can these rules exported or copied to other places like the `analysis_options.yaml` or packages like `flutter_lint`?

### Improve the workflow by providing tools to format files separately or once for all

As @eggfly mentioned, the engine repo does have a script to format codes. Policies are defined by us, so why can't we create a tool for this policy? This is how "legal tools" worked.
By providing tools for formatting, people who want to contribute to flutter/flutter won't spend too much time to to familiar with the style guide (since it have a bunch of rules), or worry about not getting passed with tests after a huge amount of codes have been written.
Also, Flutter/Dart developers are already familiar with tools like `flutter format` and `dart format`, so it's quite easy to imagine that we can have such tools for the repo.

You can see contributors like @eggfly are focused on engine PRs, who have that convenience when dealing with engine codes formatting, struggled when dealing with framework. Even contributors like us who usually contribute to the framework already familiar with the guide, could make mistakes when formatting. It's not that important but more user-friendly and time-saving.

**Comment by AlexV525** [comment] 2021-12-09 16:19
> This seems to be a duplicate of #2025

This seems to draw another feature.

P.S. When things are easy for first-time-contributor, more fixes/enhancements we can receive, contributors can be more focused on the goal. That's somehow like the design doc, which is a little bit complex at present.

**Comment by stuartmorgan** [comment] 2021-12-09 16:59
> @stuartmorgan I think what he's trying to say is the current analysis workflow is too hard and complex for contributors

Again, analysis and autoformat are *completely unrelated*. If there are issues with doing *analysis* locally, that should be a new issue, clearly describing the problem, and not mixing in an unrelated discussion about autoformat.

> So can these rules exported or copied to other places like the `analysis_options.yaml` or packages like `flutter_lint`?

If there are cases where analysis isn't done via the analyzer, please include that information in the new issue.

> As @eggfly mentioned, the engine repo does have a script to format codes.

Yes, because its policy is to use `dart format`, so there's a script to do it.

> Policies are defined by us, so why can't we create a tool for this policy?

Again, the current policy, as documented, is "flutter/flutter code should be hand-formatted". There is no tool that can hand-format code.

If you want an auto-formatter that will meet all of Hixie's requirements to change that policy, that's #2025.

> By providing tools for formatting, people who want to contribute to flutter/flutter won't spend too much time to to familiar with the style guide (since it have a bunch of rules) [...]

I understand the arguments for autoformatters. Hixie (who is the arbiter of this policy) is as well. The discussions have happened many times, and the **explicit decision** after evaluating the tradeoffs is to use hand-formatted code for flutter/flutter. The reasons for this are documented in the style guide.
