### ISSUE TITLE
The tool_tests_commands flakes on `test\commands.shard\permeable\packages_test.dart` TimeoutException

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#97831] opened 2022-02-04 20:08 UTC
(part of https://github.com/flutter/flutter/issues/97036)
One recent flake on `test\commands.shard\permeable\packages_test.dart` TimeoutException

https://ci.chromium.org/ui/p/flutter/builders/prod/Windows%20tool_tests_commands/3491/overview

```
23:30 +572 -1: test\commands.shard\permeable\packages_test.dart: packages get/upgrade set no plugins as usage value [E]                                                                                
  TimeoutException after 0:15:00.000000: Test timed out after 15 minutes.
  dart:isolate  _RawReceivePortImpl._handleMessage
```

**Comment by keyonghan** [comment] 2022-02-04 20:10
Assigning to @zanderso for initial triage.

**Comment by zanderso** [comment] 2022-02-04 20:24
Tests in that file will do real invocations of `pub`. This appears to be by design. Real invocations of `pub` will fail or timeout occasionally on network, infra, etc. issues. There isn't much that can be done in the tool about that, so removing the label.

**Comment by godofredoc** [comment] 2022-12-08 23:16
Closing as obsolete.

**Closed by godofredoc** 2022-12-08 23:16 UTC
Labels: dependency: dart, team: flakes, team: infra, passed secondary triage
