### ISSUE TITLE
CupertinoDatePicker lag and slow after upgrade to flutter 3.0

### ISSUE THREAD

**Issue by adham-ashraf77** [flutter/flutter#104049] opened 2022-05-18 07:43 UTC
Hello, I upgraded recently to flutter 3.0 after the upgrade CupertinoDatePicker show very lag and slow and that wasn't before in the 2.10.5 version.

**Comment by genevaspur** [comment] 2022-05-18 08:36
Same here.
I just tested on new project and still laggy.

**Comment by adham-ashraf77** [comment] 2022-05-18 09:37
@danagbemava-nc  you can run it local on your device and you will see the lag 
CupertinoDatePicker(
                      mode: CupertinoDatePickerMode.date,
                      initialDateTime: DateTime.now(),
                    ),

**Comment by genevaspur** [comment] 2022-05-18 10:05
@danagbemava-nc 
![laggy](https://user-images.githubusercontent.com/45225412/169013333-5f6d2a9c-fcce-41c0-97c2-8f7be2412805.gif)

[sample_code.txt](https://github.com/flutter/flutter/files/8715245/sample_code.txt)

[flutter_doctor.txt](https://github.com/flutter/flutter/files/8715247/flutter_doctor.txt)



**Tested on Android / iOS emulator and iphone13 promax,  LG Q6, Galaxy S22.**

**Comment by danagbemava-nc** [comment] 2022-05-19 07:06
Hi @genevaspur & @adham-ashraf77, while I could reproduce this on the `stable` branch, I could not reproduce this on the `master` branch. See the recordings below.

<details>
<summary>recordings</summary>

| master | stable |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/169229429-5a4668c5-4c8c-4acd-8929-a62e07697623.MP4" /> | <video src="https://user-images.githubusercontent.com/88313112/169229458-e0bc0503-e24b-4df7-ab1b-616a39f8bff7.MP4" /> |

 </details>

Given that this does not reproduce on the `master` branch, I would say this issue has been fixed. As such, I'll be closing this issue as fixed. If any of you run into this issue on the `master` branch, kindly leave a comment below and I will reopen this. 

Thank you

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.0.0 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (9 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Nexus (mobile)     • 00008020-001875E83A38002E            • ios            • iOS 15.4.1 19E258
    • iPhone 13 (mobile) • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.799, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.799 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 348a2b4f2f (3 hours ago), 2022-05-19 00:33:08 -0400
    • Engine revision 1965c92ea4
    • Dart version 2.18.0 (build 2.18.0-130.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Nexus (mobile)     • 00008020-001875E83A38002E            • ios            • iOS 15.4.1 19E258
    • iPhone 13 (mobile) • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Closed by danagbemava-nc** 2022-05-19 07:06 UTC
Labels: in triage

**Comment by taosimple** [comment] 2022-05-27 12:14
> Hi @genevaspur @adham-ashraf77, could either of you provide a complete minimal sample that we can use to verify this behaviour? I ran the sample found in https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html and I didn't notice any lag. The frame rate was around 56fps in `debug` mode and around 60fps in `profile` mode.
> 
> What platforms are you experiencing this issue on?
> 
> Please provide the output of `flutter doctor -v` as well.
> 
> video

@danagbemava-nc  I copy https://api.flutter.dev/flutter/cupertino/CupertinoDatePicker-class.html code, run on flutter Flutter 3.0.1 Android 10 can reproduce this issue, you need scroll up and down several times, it suddenly become very lag.
It seems change to `DateTime dateTime = DateTime.now();` will Increase the probability of occurrence

**Comment by danagbemava-nc** [comment] 2022-05-27 12:46
@taosimple, I was able to reproduce it on `stable` but not on the `master` channel. If this reproduces on the `master` channel for you, kindly provide the output of `flutter doctor -v` on the master channel. 

Thank you
