### ISSUE TITLE
[Desktop] Flutter pages as separate windows?

### ISSUE THREAD

**Issue by giaur500** [flutter/flutter#38578] opened 2019-08-14 22:27 UTC
Currently, entire Flutter app is always embedded inside only single window. As that's fair enough in most cases, that also does not look like as real desktop app, as any regular desktop app uses multiple windows on desktop.

Proposal: add support for embedding each single Flutter page in its own window, rather than entire app.

**Comment by stuartmorgan** [comment] 2019-08-14 23:37
Duplicate of #30701

**Closed by stuartmorgan** 2019-08-14 23:37 UTC
