### ISSUE TITLE
InteractiveView widget zoom functionality not working properly in Realme  X2 device.

### ISSUE THREAD

**Issue by Rupak-66** [flutter/flutter#63281] opened 2020-08-08 11:34 UTC
## Problem Statement

I have tried my RealME X2 android device for testing flutter's brand new InteractiveViewer widget. Zoom is not properly working in the device. Sometimes it works and mostly not. I tried my Old samsung device but there it is working seamlessly.
I have tested release APK for both the cases.

## Code snippet

```
class InterACtive extends StatefulWidget {
  @override
  _InterACtiveState createState() => _InterACtiveState();
}

class _InterACtiveState extends State<InterACtive> {
  final TransformationController _controller = TransformationController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: InteractiveViewer(
        transformationController: _controller,
        onInteractionEnd: (details){
          _controller.value = Matrix4.identity();
        },
        child: Center(child: Image.asset("assets/images/pubg.png")),
      ),
    );
  }
}
```

**Comment by Rupak-66** [comment] 2020-08-08 11:44
``class _InterACtiveState extends State<InterACtive> {
  final TransformationController _controller = TransformationController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: InteractiveViewer(
        transformationController: _controller,
        onInteractionEnd: (details){
          _controller.value = Matrix4.identity();
        },
        child: Center(child: Image.asset("assets/images/pubg.png")),
      ),
    );
  }
}

**Comment by TahaTesser** [comment] 2020-08-10 13:28
Hi @Rupak-66 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` while  running code sample and using zoom functionality
Thank you

**Comment by HansMuller** [comment] 2020-08-10 15:27
CC @justinmc

**Comment by justinmc** [comment] 2020-08-12 01:58
This sounds like a duplicate of https://github.com/flutter/flutter/issues/63006, which should be fixed soon.

**Comment by justinmc** [comment] 2020-08-13 00:22
@Rupak-66 Let me know if this issue wasn't fixed by https://github.com/flutter/flutter/pull/63543 and I'll be happy to reopen!

**Comment by redevRx** [comment] 2020-08-14 06:50
I use Flutter channel stable and it not working

**Comment by Rupak-66** [comment] 2020-08-14 14:04
@justinmc I have tested with Flutter version 1.20.2 and Dart version 2.9.1. I am still facing the issue.

**Comment by Rupak-66** [comment] 2020-08-14 14:28
@TahaTesser Sorry for late response. In emulator it is working fine. But when I am making APK and installing in one of my real device(RealMe X2. Andriod Version 10) then it is not working. I am using Flutter version 1.20.2 and Dart version 2.9.1.

**Comment by justinmc** [comment] 2020-08-14 15:54
You'll have to use the master channel to pick up my fix since I just merged it.

**Comment by Rupak-66** [comment] 2020-08-15 08:19
@justinmc Hi. I have tested using master channel and the same code is working seamlessly.

**Comment by Rupak-66** [comment] 2020-08-15 11:00
@justinmc Is there any way we can tap or double tap to zoom using InteractiveViewer ? I was going through the documentation but couldn't find out a way

**Comment by Patcher56** [comment] 2020-08-15 21:59
Seems like I also have this error while debugging on my iPhone X, on the emulator it works fine.

**Comment by TahaTesser** [comment] 2020-08-17 06:50
Hi @Rupak-66  @Patcher56 
Can you please provide your `flutter doctor -v` **with latest  master channel this bug reproduces in**,  your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by Patcher56** [comment] 2020-08-17 07:00
Hello @TahaTesser, I tested it with the master branch on iOS yesterday and it worked fine. When does the changes get released?

**Comment by justinmc** [comment] 2020-08-17 21:31
I think this should be in the next release after 1.20.2.  I'll close this unless someone still sees a problem specific to this device in master.

I made an improvement to this gesture here: https://github.com/flutter/flutter/pull/63543

See also https://github.com/flutter/flutter/issues/63006.

**Comment by justinmc** [comment] 2020-08-18 16:21
@Rupak-66 I've wondered if double-tap-to-zoom is something we should support out of the box...  You can do it yourself but it's a little tricky:

  1. Pas a TransformationController to your InteractiveViewer.
  1. Listen to double taps by wrapping InteractiveViewer in a GestureDetector.
  1. On double tap, get the `value` of the TransformationController. Create a new Matrix4 by transforming the `value` matrix to  whatever increase in zoom you want.  Set `value` to the new matrix.  You may want to animate this.

It may be difficult to calculate the correct zoomed in matrix.  Maybe TransformationController should expose some helper methods for things like that.

**Comment by Rupak-66** [comment] 2020-08-19 04:25
@justinmc Thanks for explanation. Yeah it would be good if TransformationController exposes some helper methods to achieve it. Looking forward to it.

**Closed** 2020-08-19 04:26 UTC
Labels: f: material design, framework, in triage

**Comment by justinmc** [comment] 2020-08-19 15:25
I went ahead and created a new issue for double tap to zoom: https://github.com/flutter/flutter/issues/64156

**Comment by Rupak-66** [comment] 2020-08-20 05:28
@justinmc Thanks for including this in your road-map

**Comment by kamleshwebtech** [comment] 2020-11-08 05:20
InteractiveViewer does not work properly with CarouselSlider. If we want to see left or right portion of an image then slider shows previous image or next image respectively. Do you have any suggestion? how can we fix it. Thanks a lot.

**Comment by justinmc** [comment] 2020-11-09 16:30
@kamleshwebtech Please open a new issue with a full reproduction case.  Or, see these two issues which may already cover your problem: https://github.com/flutter/flutter/issues/63980 https://github.com/flutter/flutter/issues/68594
