### ISSUE TITLE
Cupertino scrollbar can no longer be flung in flutter 2

### ISSUE THREAD

**Issue by Kavantix** [flutter/flutter#78688] opened 2021-03-20 12:10 UTC
In the previous stable release of flutter (1.22.6) the cupertino scrollbar could be flung giving it some inertia just like the real scrollbar on iOS.
After the refactor done in #71664 this behavior was accidentally removed.

In pr #78689 I added a widget test for this behavior that passes on 1.22.6 and fails on the current master and stable channels

**Comment by Kavantix** [comment] 2021-03-20 12:17
@Piinks FYI

**Comment by TahaTesser** [comment] 2021-03-22 11:03
Hi @Kavantix 
Thanks for filing the issue and PR, I can reproduce the difference between `1.22.6` and `2.0+`

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Cupertino App',
      home: CupertinoPageScaffold(
        navigationBar: CupertinoNavigationBar(
          middle: Text('Cupertino App Bar'),
        ),
        child: Center(
          child: Container(
            child: ListView.builder(
              itemCount: 20,
              itemBuilder: (BuildContext context, int index) {
                return Image.network(
                  'https://i.imgur.com/QCNbOAo.png',
                  fit: BoxFit.cover,
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```dart
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 4d7946a68d (3 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 89.0.4389.90

• No issues found!
``` 

```bash
[✓] Flutter (Channel master, 2.1.0-13.0.pre.194, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.194 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision e58ee0fbc7 (6 hours ago), 2021-03-22 13:06:06 +0800
    • Engine revision e6db3a275e
    • Dart version 2.13.0 (build 2.13.0-149.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.4.1
    • macOS (desktop)        • macos                     • darwin-x64     •
      macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 89.0.4389.90

• No issues found!
```

</details>

Thank you

**Comment by Piinks** [comment] 2021-03-22 15:44
Hey @Kavantix thanks for filing this - and providing a test! Super helpful! :)

We should definitely find a way to restore this. This feature appears to be specific to just the `CupertinoScrollbar`. We changed the way the scrollbar handled interactions in #71664 because the previous implementation would crash (https://github.com/flutter/flutter/issues/70105).

I haven't taken a look at this yet, but I am thinking we might just need to override RawScrollbarState.handleThumbPressEnd in CupertinoScrollbarState to carry the velocity once the scrollbar has been released. We may also want to check the PointerDeviceKind from the drag details, and only apply this when the input is touch. I am guessing that will help avoid that crash and maintain the expected behavior for mouse and touch input.

**Comment by Kavantix** [comment] 2021-03-22 15:53
Well actually, I just tested it on my ipad and if I drag the scrollbar with a mouse instead of my finger it still has inertia.
So it should actually depend on the platform not on the pointerkind, which means probably just android and iOS then?
Or perhaps make that the default and make it configurable (but that is beyond the scope of this ticket I think)

**Comment by Piinks** [comment] 2021-03-22 16:09
> Well actually, I just tested it on my ipad and if I drag the scrollbar with a mouse instead of my finger it still has inertia.
> So it should actually depend on the platform not on the pointerkind, which means probably just android and iOS then?
> Or perhaps make that the default and make it configurable (but that is beyond the scope of this ticket I think)

Thanks for checking! I had not thought about the mouse on iPad, so maybe you are right and we need platform-specific behavior. We should definitely make sure we do not re-introduce that crash though, which happens when you drag and pointer scroll at the same time.

**Comment by Kavantix** [comment] 2021-03-23 20:54
I've done a bit more testing on the iPad and the behavior there seems fairly odd.

In iOS apps:
- If you drag the scrollbar and then start scrolling the wheel the scrollbar and scrollview jump back to the place that you grabbed the scrollbar from and neither moving the mouse nor scrolling the wheel will do anything until the mouse button is released
- While scrolling with the mousewheel the scrollbar disappears very very quickly unless your pointer is already near the scrollbar when scroling
- When hovering over the scrollbar with the mouse it will already expand and become darker

In macos:
- If you drag de scrollbar and then start scrolling the wheel the scrollview will scroll with the wheel.
  - But if you then move the mouse again (while still holding the button) the bar will sync back up with the mouse
- When hovering over the scrollbar with the mouse it will become darker

Flutter currently:
- While dragging the scrollbar and hovering exactly over the scrollbar the mousewheel won't have any effect
- While dragging the scrollbar and hovering over the scrollview the view will scroll and the bar will also move, leaving the mouse and the bar in different vertical positions but still linked
- There is no hover effect
- The scrollbar appears just as long as when scrolling with a finger

So it seems to me if we implement the 'correct' behaviour for the scrollbar then the crash should not be able to happen since that case is explicitely handled

**Comment by Piinks** [comment] 2021-03-24 00:04
This is really great! Thank you for putting together all of this research! 
We have not yet implemented a desktop native version of the CupertinoScrollbar, right now I think it is just the iOS version of the scrollbar, so yes we do need to add those behaviors. These lists will be very helpful in developing test cases for this. :)

**Comment by Kavantix** [comment] 2021-03-24 05:32
> This is really great! Thank you for putting together all of this research!
> We have not yet implemented a desktop native version of the CupertinoScrollbar, right now I think it is just the iOS version of the scrollbar (without any mouse-specific behavior), so yes we do need to add those behaviors. These lists will be very helpful in developing test cases for this. :)

Happy to do it :)

> We may also want to check the PointerDeviceKind from the drag details, and only apply this when the input is touch. I am guessing that will help avoid that crash and maintain the expected behavior for mouse and touch input.

Is there already a testcase for this crash that fails on 1.22.6 and passes on the current version?

**Comment by Piinks** [comment] 2021-03-29 19:26
There should have been  a test case, it looks like it was lost in one of the branches I was working on for #71664. I was able to find them though! I just put them up in #79297

**Comment by dam-ease** [comment] 2023-05-15 08:23
I am able to reproduce this issue on the latest `stable` and `master` channels.
[Code Sample](https://github.com/flutter/flutter/issues/78688#issuecomment-803975185)

<details> <summary> flutter doctor -v </summary>

```bash
[✓] Flutter (Channel master, 3.11.0-2.0.pre.55, on macOS 13.3 22E252 darwin-arm64, locale en-NG)
    • Flutter version 3.11.0-2.0.pre.55 on channel master at /Users/dammya/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 835b892d7f (9 days ago), 2023-05-07 01:30:22 +0530
    • Engine revision 23f730efbf
    • Dart version 3.1.0 (build 3.1.0-83.0.dev)
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Damilola’s iPhone (mobile) • 71c843fa5f3dec767999f36224653c0faa78660e • ios            • iOS 16.4 20E247
    • macOS (desktop)            • macos                                    • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                                   • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```
```bash
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3 22E252 darwin-arm64, locale
    en-NG)
    • Flutter version 3.10.0 on channel stable at /Users/dammya/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (6 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/dammya/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/dammya/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] VS Code (version 1.78.0)
    • VS Code at /Users/dammya/.Trash/Visual Studio Code 20.07.05.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • Damilola’s iPhone (mobile) • 71c843fa5f3dec767999f36224653c0faa78660e •
      ios            • iOS 16.4 20E247
    • macOS (desktop)            • macos                                    •
      darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by Piinks** [comment] 2024-06-26 01:05
This was fixed by https://github.com/flutter/flutter/pull/146654

**Closed by Piinks** 2024-06-26 01:05 UTC
Labels: c: regression, platform-ios, framework, a: fidelity, f: scrolling, f: cupertino, has reproducible steps, P2, found in release: 3.10, found in release: 3.11, team-ios, triaged-ios

**Comment by Kavantix** [comment] 2024-06-26 09:09
Good to hear!
@Piinks did you also include my test? If not perhaps worth reopening my PR
