### ISSUE TITLE
if I update the devicePixelRatio in createViewConfiguration, webview font like this

### ISSUE THREAD

**Issue by phoenixsky** [flutter/flutter#39735] opened 2019-09-03 10:35 UTC
1.  I wrap theWidgetsFlutterBinding in `main()`
    ```dart 
      InnerWidgetsFlutterBinding.ensureInitialized()
      ..attachRootWidget(App())
      ..scheduleWarmUpFrame();
    ```
2. update the `devicePixelRatio`
```dart
const double SCREEN_WIDTH = 414;
class InnerWidgetsFlutterBinding extends WidgetsFlutterBinding {
  static bool adjust = true;

  static WidgetsBinding ensureInitialized() {
    if (WidgetsBinding.instance == null) InnerWidgetsFlutterBinding();
    return WidgetsBinding.instance;
  }
  double get adapterRatio {
    return ui.window.physicalSize.width / SCREEN_WIDTH;
  }
  @override
  ViewConfiguration createViewConfiguration() {
    return ViewConfiguration(
      size: window.physicalSize / adapterRatio,
      devicePixelRatio: adapterRatio,
    );
  }
...
}
```
> [detai code](https://github.com/phoenixsky/fun_android_flutter/blob/master/lib/config/ui_adapter_config.dart)

3. the webview font not clear
![image](https://user-images.githubusercontent.com/6359214/64166090-fe56a780-ce78-11e9-8277-252f0e82f390.png)

* It happens on some android devices like samsung note 4

* maybe also happens on native view 

so how can I fix it

**Comment by darshankawar** [comment] 2020-07-06 12:50
Hi @phoenixsky, 
Can you please confirm if you still experience this issue on latest Flutter channel (eg : dev) and with latest version of `webview_flutter` plugin ?

**Comment by VladyslavBondarenko** [comment] 2020-07-29 11:29
I can't reproduce it with https://github.com/phoenixsky/fun_android_flutter running with current master `1.21.0-6.0.pre.90` on Redmi Note 7 Android 9 (API 28).

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.90, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.90 at /Users/nevercode/dev/flutter
    • Framework revision 531ee9452a (85 minutes ago), 2020-07-29 02:26:03 -0400
    • Engine revision 1ba310017c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (6 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone 11 Pro Max (mobile)  • 55C8466B-5367-492B-8EFE-EC45D980571F     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>

Closing. 
@phoenixsky if the problem persists comment here with complete minimal reproducible code sample and your `flutter doctor -v` or consider to file a new issue

**Closed by VladyslavBondarenko** 2020-07-29 11:29 UTC
Labels: a: internationalization, a: typography, p: webview, plugin, waiting for customer response
