### ISSUE TITLE
Error Build Apk with jit_release mode with local engine.

### ISSUE THREAD

**Issue by canewsin** [flutter/flutter#83412] opened 2021-05-26 14:05 UTC
## Steps to Reproduce

Followed all the steps here

https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment
https://github.com/flutter/flutter/wiki/Compiling-the-engine

Build 
```
flutter build apk --local-engine-src-path "/home/pramukesh/flutter-build/engine/src" --local-engine=android_jit_release_arm64 -v --release --target-platform=android-arm64
```

**Expected results:** Should build normally.

**Actual results:** Error Compiling.

<details>
  <summary>Logs</summary>

    flutter build apk --local-engine-src-path "/home/pramukesh/flutter-build/engine/src" --local-engine=android_jit_release_arm64 -v --release --target-platform=android-arm64
    [  +45 ms] executing: uname -m
    [  +19 ms] Exit code 0 from: uname -m
    [        ] x86_64
    [   +3 ms] executing: [/home/pramukesh/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
    [   +1 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
    [        ] 1d1973418348d6a453d58cf7c472b209a31ac79b
    [        ] executing: [/home/pramukesh/flutter/] git tag --points-at 1d1973418348d6a453d58cf7c472b209a31ac79b
    [   +5 ms] Exit code 0 from: git tag --points-at 1d1973418348d6a453d58cf7c472b209a31ac79b
    [        ] executing: [/home/pramukesh/flutter/] git describe --match *.*.* --long --tags 1d1973418348d6a453d58cf7c472b209a31ac79b
    [  +18 ms] Exit code 0 from: git describe --match *.*.* --long --tags 1d1973418348d6a453d58cf7c472b209a31ac79b
    [        ] 2.3.0-12.0.pre-162-g1d19734183
    [   +3 ms] executing: [/home/pramukesh/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
    [   +1 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
    [        ] origin/master
    [        ] executing: [/home/pramukesh/flutter/] git ls-remote --get-url origin
    [   +1 ms] Exit code 0 from: git ls-remote --get-url origin
    [        ] https://github.com/flutter/flutter.git
    [  +22 ms] Local engine source at /home/pramukesh/flutter-build/engine/src
    [  +40 ms] executing: [/home/pramukesh/flutter/] git rev-parse --abbrev-ref HEAD
    [   +1 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
    [        ] master
    [  +51 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
    [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
    [  +69 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
    [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
    [   +4 ms] Downloading android-arm-profile/linux-x64 tools...
    [ +472 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm-profile/linux-x64.zip md5 hash: AZabY0JQy9LXsD6/wHzYIg==
    [ +475 ms] Downloading android-arm-profile/linux-x64 tools... (completed in 941ms)
    [   +1 ms] executing: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm-profile/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64
    [  +42 ms] Exit code 0 from: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm-profile/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64
    [   +5 ms] Downloading android-arm-release/linux-x64 tools...
    [ +314 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm-release/linux-x64.zip md5 hash: WAQ2zVjJe5KHn6TKv8lJBA==
    [ +321 ms] Downloading android-arm-release/linux-x64 tools... (completed in 635ms)
    [   +3 ms] executing: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm-release/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64
    [  +34 ms] Exit code 0 from: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm-release/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-arm-release/linux-x64
    [   +4 ms] Downloading android-arm64-profile/linux-x64 tools...
    [ +310 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm64-profile/linux-x64.zip md5 hash: LuMIqJ8UKgPxlIsM3ZzTdA==
    [ +398 ms] Downloading android-arm64-profile/linux-x64 tools... (completed in 708ms)
    [        ] executing: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm64-profile/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-arm64-profile/linux-x64
    [  +38 ms] Exit code 0 from: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm64-profile/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-arm64-profile/linux-x64
    [   +4 ms] Downloading android-arm64-release/linux-x64 tools...
    [ +309 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm64-release/linux-x64.zip md5 hash: 4cRB1fYCxpfaU9TbICGrMw==
    [ +325 ms] Downloading android-arm64-release/linux-x64 tools... (completed in 635ms)
    [        ] executing: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm64-release/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-arm64-release/linux-x64
    [  +35 ms] Exit code 0 from: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-arm64-release/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-arm64-release/linux-x64
    [   +3 ms] Downloading android-x64-profile/linux-x64 tools...
    [ +313 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-x64-profile/linux-x64.zip md5 hash: p+cg0h1QsESNkyKPKdWq+g==
    [ +369 ms] Downloading android-x64-profile/linux-x64 tools... (completed in 683ms)
    [   +1 ms] executing: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-x64-profile/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-x64-profile/linux-x64
    [  +41 ms] Exit code 0 from: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-x64-profile/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-x64-profile/linux-x64
    [   +3 ms] Downloading android-x64-release/linux-x64 tools...
    [ +326 ms] Content https://storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-x64-release/linux-x64.zip md5 hash: 25kKqVr4anOws0h/1MTq4w==
    [ +325 ms] Downloading android-x64-release/linux-x64 tools... (completed in 651ms)
    [   +3 ms] executing: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-x64-release/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-x64-release/linux-x64
    [  +38 ms] Exit code 0 from: unzip -o -q /home/pramukesh/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra_release/flutter/b1385c0df12549b9dce7ce3fee361bd4898f49ae/android-x64-release/linux-x64.zip -d
    /home/pramukesh/flutter/bin/cache/artifacts/engine/android-x64-release/linux-x64
    [   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
    [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
    [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
    [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
    [  +33 ms] Skipping pub get: version match.
    [  +22 ms] Found plugin r_upgrade at /home/pramukesh/flutter/.pub-cache/git/r_upgrade-f1902ef7567a3177ce72d5534f03655f9ced0301/
    [  +38 ms] Found plugin cloud_firestore at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.2.0/
    [   +3 ms] Found plugin cloud_firestore_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-2.1.0/
    [   +4 ms] Found plugin connectivity_plus at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus-1.0.1/
    [   +1 ms] Found plugin connectivity_plus_linux at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_linux-1.0.1/
    [   +1 ms] Found plugin connectivity_plus_macos at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_macos-1.0.1/
    [   +1 ms] Found plugin connectivity_plus_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_web-1.0.1/
    [        ] Found plugin connectivity_plus_windows at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_windows-1.0.1/
    [   +7 ms] Found plugin firebase_app_check at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_app_check-0.0.1/
    [   +2 ms] Found plugin firebase_app_check_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_app_check_web-0.0.1/
    [   +1 ms] Found plugin firebase_auth at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.2.0/
    [   +1 ms] Found plugin firebase_auth_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.1.3/
    [   +1 ms] Found plugin firebase_core at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.2.0/
    [   +1 ms] Found plugin firebase_core_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/
    [   +1 ms] Found plugin firebase_crashlytics at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.0.4/
    [   +3 ms] Found plugin flutter_facebook_login at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
    [   +1 ms] Found plugin flutter_inappwebview at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/
    [        ] Found plugin flutter_native_env at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_env-0.0.1+2/
    [   +6 ms] Found plugin google_mobile_ads at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/google_mobile_ads-0.13.0/
    [        ] Found plugin google_sign_in at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-5.0.3/
    [   +1 ms] Found plugin google_sign_in_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.10.0/
    [   +8 ms] Found plugin libphonenumber at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/libphonenumber-2.0.0/
    [   +1 ms] Found plugin libphonenumber_plugin at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/libphonenumber_plugin-0.2.3/
    [        ] Found plugin libphonenumber_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/libphonenumber_web-0.2.0+1/
    [   +3 ms] Found plugin package_info at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-2.0.0/
    [   +1 ms] Found plugin path_provider at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
    [        ] Found plugin path_provider_linux at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
    [        ] Found plugin path_provider_macos at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
    [   +1 ms] Found plugin path_provider_windows at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
    [   +4 ms] Found plugin shared_preferences at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/
    [        ] Found plugin shared_preferences_linux at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
    [        ] Found plugin shared_preferences_macos at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
    [   +1 ms] Found plugin shared_preferences_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
    [   +1 ms] Found plugin shared_preferences_windows at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
    [   +3 ms] Found plugin sqflite at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+3/
    [   +7 ms] Found plugin url_launcher at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.4/
    [        ] Found plugin url_launcher_linux at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.0/
    [        ] Found plugin url_launcher_macos at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.0/
    [   +1 ms] Found plugin url_launcher_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.0/
    [        ] Found plugin url_launcher_windows at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.0/
    [   +3 ms] Found plugin wiredash at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/wiredash-0.6.2/
    [  +77 ms] Found plugin r_upgrade at /home/pramukesh/flutter/.pub-cache/git/r_upgrade-f1902ef7567a3177ce72d5534f03655f9ced0301/
    [   +5 ms] Found plugin cloud_firestore at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-2.2.0/
    [        ] Found plugin cloud_firestore_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-2.1.0/
    [        ] Found plugin connectivity_plus at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus-1.0.1/
    [        ] Found plugin connectivity_plus_linux at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_linux-1.0.1/
    [        ] Found plugin connectivity_plus_macos at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_macos-1.0.1/
    [        ] Found plugin connectivity_plus_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_web-1.0.1/
    [        ] Found plugin connectivity_plus_windows at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity_plus_windows-1.0.1/
    [   +1 ms] Found plugin firebase_app_check at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_app_check-0.0.1/
    [        ] Found plugin firebase_app_check_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_app_check_web-0.0.1/
    [        ] Found plugin firebase_auth at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.2.0/
    [        ] Found plugin firebase_auth_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.1.3/
    [        ] Found plugin firebase_core at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.2.0/
    [        ] Found plugin firebase_core_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.1.0/
    [        ] Found plugin firebase_crashlytics at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.0.4/
    [        ] Found plugin flutter_facebook_login at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_login-3.0.0/
    [        ] Found plugin flutter_inappwebview at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/
    [        ] Found plugin flutter_native_env at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_native_env-0.0.1+2/
    [   +1 ms] Found plugin google_mobile_ads at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/google_mobile_ads-0.13.0/
    [        ] Found plugin google_sign_in at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-5.0.3/
    [   +1 ms] Found plugin google_sign_in_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.10.0/
    [   +2 ms] Found plugin libphonenumber at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/libphonenumber-2.0.0/
    [        ] Found plugin libphonenumber_plugin at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/libphonenumber_plugin-0.2.3/
    [        ] Found plugin libphonenumber_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/libphonenumber_web-0.2.0+1/
    [   +1 ms] Found plugin package_info at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-2.0.0/
    [        ] Found plugin path_provider at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.1/
    [        ] Found plugin path_provider_linux at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.0/
    [        ] Found plugin path_provider_macos at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.0/
    [        ] Found plugin path_provider_windows at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.1/
    [   +1 ms] Found plugin shared_preferences at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.5/
    [        ] Found plugin shared_preferences_linux at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.0/
    [        ] Found plugin shared_preferences_macos at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.0/
    [        ] Found plugin shared_preferences_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.0/
    [        ] Found plugin shared_preferences_windows at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.0/
    [   +1 ms] Found plugin sqflite at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+3/
    [   +2 ms] Found plugin url_launcher at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.4/
    [        ] Found plugin url_launcher_linux at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.0/
    [        ] Found plugin url_launcher_macos at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.0/
    [        ] Found plugin url_launcher_web at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.0/
    [        ] Found plugin url_launcher_windows at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.0/
    [        ] Found plugin wiredash at /home/pramukesh/flutter/.pub-cache/hosted/pub.dartlang.org/wiredash-0.6.2/
    [  +33 ms] Generating /home/pramukesh/MovieRoar/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
    [ +120 ms] Building without sound null safety
    [        ] For more information see https://dart.dev/null-safety/unsound-null-safety
    [  +12 ms] Running Gradle task 'assembleRelease'...
    [   +2 ms] Using gradle from /home/pramukesh/MovieRoar/android/gradlew.
    [   +5 ms] "flutter apk" took 5,109ms.
    [   +2 ms] The file /home/pramukesh/flutter-build/engine/src/out/android_jit_release_arm64/flutter_embedding_release.pom wasn't found in the local engine out directory.
    [        ]
               #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
               #1      _getLocalArtifactVersion (package:flutter_tools/src/android/gradle.dart:1063:5)
               #2      _getLocalEngineRepo (package:flutter_tools/src/android/gradle.dart:1103:34)
               #3      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:341:41)
               #4      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:231:11)
               #5      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:26)
               <asynchronous suspension>
               #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1114:27)
               <asynchronous suspension>
               #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
               <asynchronous suspension>
               #8      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
               <asynchronous suspension>
               #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
               <asynchronous suspension>
               #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
               <asynchronous suspension>
               #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
               <asynchronous suspension>
               #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
               <asynchronous suspension>
               #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
               <asynchronous suspension>
               #14     main (package:flutter_tools/executable.dart:91:3)
               <asynchronous suspension>
    
    
    [ +164 ms] ensureAnalyticsSent: 163ms
    [   +4 ms] Running shutdown hooks
    [   +1 ms] Shutdown hooks complete
    [   +1 ms] exiting with code 1

**Comment by jonahwilliams** [comment] 2021-05-26 15:31
The flutter tool does not support building in jIT release mode. You can use the artifacts but you'd have to do everything yourself

Duplicate of https://github.com/flutter/flutter/issues/45415

**Closed by jonahwilliams** 2021-05-26 15:31 UTC
