### ISSUE TITLE
[MacOS] Pressing SHIFT first in a multi-key shortcut causes other keys to not be registered as pressed.

### ISSUE THREAD

**Issue by JSANL** [flutter/flutter#65096] opened 2020-09-02 12:27 UTC
## Steps to Reproduce

1. Create a new app with the following code:
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// Pressing SHIFT + N (first SHIFT, then N) works on Web but not Mac 

void main() {
  runApp(KeyboardShortcut());
}

class KeyboardShortcut extends StatefulWidget {
  @override
  _KeyboardShortcutState createState() => _KeyboardShortcutState();
}

class _KeyboardShortcutState extends State<KeyboardShortcut> {
  int pressed;

  @override
  void initState() {
    super.initState();
    pressed = 0;
    RawKeyboard.instance.addListener((event) {
      if (event.isShiftPressed && event.isKeyPressed(LogicalKeyboardKey.keyN)) {
        print('Pressed Shortcut');
        setState(() {
          pressed += 1;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Center(child: Text('Pressed $pressed times.')));
  }
}
```
2. Run the App on MacOS

**Expected results:**
If I firstly hold down SHIFT then press "N" then the keypress of "N" should be registered (the counter should count up).

**Actual results:**
If I firstly hold down SHIFT then press "N" then the keypress of "N" was not registered (the counter did not count up).

The Bug does not exist in web. I did not test other platforms.

```
jonassander@MacBook-Pro keyboard_bug % flutter doctor -v
[✓] Flutter (Channel master, 1.22.0-10.0.pre.39, on Mac OS X 10.15.6 19G2021, locale de-DE)
    • Flutter version 1.22.0-10.0.pre.39 at /Users/jonassander/development/flutter
    • Framework revision a8281e31af (vor 18 Stunden), 2020-09-01 10:57:59 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jonassander/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (3 available)            
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

• No issues found!
```

**Comment by JSANL** [comment] 2020-09-02 12:31
What I also found was that if I hold N then hold Shift the counter will not continue to count up.
If I e.g. change the key combination to "A + N" and hold both keys the counter will continue to count up.

**Comment by darshankawar** [comment] 2020-09-02 13:00
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.22.0-9.0.pre, on Mac OS X 10.15.2 19C57, locale
    en-US)
    • Flutter version 1.22.0-9.0.pre at
      /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision 7a43175198 (4 days ago), 2020-08-28 23:18:04 -0400
    • Engine revision 07e2520d5d
    • Dart version 2.10.0 (build 2.10.0-73.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

 
[✓] Connected device (4 available)            
    • iPhone SE (2nd generation) (mobile) • CB0E1E07-B83C-49E6-896E-267AC418AC7A
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.2 19C57
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 85.0.4183.83

! Doctor found issues in 1 category.

```

</details>

**Comment by stuartmorgan** [comment] 2020-09-02 14:05
@darshankawar Please apply "a: desktop" when triaging issues that are about running on Windows, macOS, or Linux, so that they end up in the correct triage queue.

**Comment by darshankawar** [comment] 2020-09-02 14:09
Thanks @stuartmorgan for the tip. Will make sure going forward.

**Comment by gspencergoog** [comment] 2020-09-02 22:43
@JSANL The code in your gist is missing (dartpad can't load that URL).  Can you paste the code here so it gets preserved with the issue?

**Comment by JSANL** [comment] 2020-09-03 12:24
@gspencergoog Thanks for noticing, I updated the ticket.

**Comment by gspencergoog** [comment] 2020-09-13 22:04
Thanks for the report: this is indeed a problem.

Your code doesn't work because you are considering the symbol `LogicalKeyboardKey.keyN` to be independent of case.  It's not, because the keyId for the 'n' key is different than it is for an uppercase 'N' (but this isn't really how it should be).

This code would work right now for your use case:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// Pressing SHIFT + N (first SHIFT, then N) works on Web but not Mac 

void main() {
  runApp(KeyboardShortcut());
}

class KeyboardShortcut extends StatefulWidget {
  @override
  _KeyboardShortcutState createState() => _KeyboardShortcutState();
}

class _KeyboardShortcutState extends State<KeyboardShortcut> {
  int pressed;

  @override
  void initState() {
    super.initState();
    pressed = 0;
	const LogicalKeyboardKey uppercaseN = LogicalKeyboardKey(0x0000004e, keyLabel: 'N', debugName: 'Uppercase N');
    RawKeyboard.instance.addListener((event) {
      if (event.isKeyPressed(uppercaseN)) {
        print('Pressed Shortcut');
        setState(() {
          pressed += 1;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Center(child: Text('Pressed $pressed times.')));
  }
}
```

But, as (bad) luck would have it, this updated code works on all platforms _except_ web. I filed https://github.com/flutter/flutter/issues/65668 so we can address this.

As a workaround, you could use the `RawEvent.character` attribute to detect that the key you are looking for produced an uppercase N, but it also appears that Flutter had a fundamental bug with the setting of the "character" attribute on the events (https://github.com/flutter/flutter/issues/65401), which I just created a PR for (https://github.com/flutter/flutter/pull/65667). After that lands, you should probably look at `RawEvent.character` to see if a key event produces the character that you care about, as that is much more independent of keyboard mapping.

If what you really want is the key at the physical location of the "N" key (as for a game), then you could check for both the physical shiftLeft (and/or shiftRight) key and the physical N key, which already works on all platforms, like so:

```dart
if (RawKeyboard.instance.physicalKeysPressed.contains(PhysicalKeyboardKey.shiftLeft) &&
    RawKeyboard.instance.physicalKeysPressed.contains(PhysicalKeyboardKey.keyN)) {
  ///  ...
}
```

**Comment by gspencergoog** [comment] 2020-09-16 19:37
OK, https://github.com/flutter/flutter/pull/65667 has landed, so you should be able to check the `event.character` attribute and compare it to 'N' to decide if shift-N has been pressed, like so:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

// Pressing SHIFT + N (first SHIFT, then N) works on Web but not Mac

void main() {
  runApp(KeyboardShortcut());
}

class KeyboardShortcut extends StatefulWidget {
  @override
  _KeyboardShortcutState createState() => _KeyboardShortcutState();
}

class _KeyboardShortcutState extends State<KeyboardShortcut> {
  int pressed;

  @override
  void initState() {
    super.initState();
    pressed = 0;
    RawKeyboard.instance.addListener((RawKeyEvent event) {
      if (event.character == 'N') {
        print('Pressed Shortcut');
        setState(() {
          pressed += 1;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Center(child: Text('Pressed $pressed times.')));
  }
}
```

**Comment by gspencergoog** [comment] 2020-09-18 19:33
I'm going to close this as a duplicate of #65668, now that there is a workaround.

**Closed by gspencergoog** 2020-09-18 19:33 UTC
Labels: P4, a: desktop, found in release: 1.22, framework, has reproducible steps, platform-mac

**Comment by JSANL** [comment] 2020-09-19 08:05
> I'm going to close this as a duplicate of #65668, now that there is a workaround.

Thanks! 

> What I also found was that if I hold N then hold Shift the counter will not continue to count up.
If I e.g. change the key combination to "A + N" and hold both keys the counter will continue to count up.

Could you reproduce this behavior? I wasn't sure if this is a bug or not.

**Comment by JSANL** [comment] 2020-09-24 11:37
> Your code doesn't work because you are considering the symbol LogicalKeyboardKey.keyN to be independent of case. It's not, because the keyId for the 'n' key is different than it is for an uppercase 'N' (but this isn't really how it should be).

Shouldn't `ShortcutManager` also take a Set of `PhysicalKeyboardKey `, not a `LogicalKeySet`?
@gspencergoog

**Comment by gspencergoog** [comment] 2020-09-24 16:38
Yes, it probably should take a `KeySet` (abstract class), and work for either, I just haven't built that yet.
