### ISSUE TITLE
image_picker pops 2 image picking screens on first load with permission alert

### ISSUE THREAD

**Issue by fysoul17** [flutter/flutter#50002] opened 2020-02-03 13:58 UTC
Image picker is displaying galleries twice only on the first load when permission is asked. After permission is granted, only one gallery screen is poping which is normal behavior.

Interesting thing is that when I copy the exact same code into 'main.dart' at image_picker's example code, it works as normal. It only shows 1 gallery screen. 

![screen](https://user-images.githubusercontent.com/7436491/73658448-6dfee600-46e8-11ea-8441-2f00ee68c6ad.gif)

## Steps to Reproduce

1. Create a brand new flutter app.
2. Import image_picker: ^0.6.3+1
3. Replace codes inside of _incrementCounter() function with below line.
```dart
ImagePicker.pickImage(source: ImageSource.gallery);
```
4. Run and press FAB (+) button then grant permission.
5. Pick any image, then you will see another screen for image picking.

<details>
  <summary>Logs</summary>

```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.592], locale ko-KR)
    • Flutter version 1.12.13+hotfix.7 at D:\Flutter
    • Framework revision 9f5ff2306b (7 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Terry\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Terry\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.0

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-02-03 14:39
I can't reproduce it with image_picker: ^0.6.3+1 on Android 9 (API 28) with stable, v1.12.13+hotfix.7, not sure what can be the cause of this

**Comment by fysoul17** [comment] 2020-02-04 01:09
@VladyslavBondarenko  Thanks for testing it out! 

I just ran a test with an old project that I made a year ago, and it worked okay. So weird.

I think it has something to do with the project I create with the current setting?
I created a java based project instead of kotlin and both have the same problem.

[Here](https://github.com/fysoul17/temp_app) is the empty project (kotlin based) I created with just one line of code added. (ImagePicker.pickImage(source: ImageSource.gallery))

Anyone having the same issue?

**Comment by avalentic** [comment] 2020-02-06 18:04
I'm experiencing the same problem on Flutter's stable channel, v1.12.13+hotfix.7, testing on real Pixel 2 XL (Android 10, API 29) and Android emulator running the same Android 10, API 29

**Comment by gilbertoalexsantos** [comment] 2020-02-07 23:28
I'm experiencing the same problem.

Android: 8.1.0, Real device (Moto G5 S Plus)
Flutter: 1.12.13+hotfix.7
Plugin Version: 0.6.3+1

**Comment by emersonsiega** [comment] 2020-02-14 11:42
Same problem here...

Tested on real device - Motorola Moto G3.
Tested on emulator.

```shell
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale pt-BR)
    • Flutter version 1.12.13+hotfix.5 at /Users/emerson.siega/development/flutter
    • Framework revision 27321ebbad (9 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/emerson.siega/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/emerson.siega/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
```

**Comment by emersonsiega** [comment] 2020-02-14 13:30
Workaround: 
- [Handle permissions manually](https://pub.dev/packages/permission_handler)
- If permissions are granted, open ImagePicker

This solves the problem for me.

**Comment by AndroidNils** [comment] 2020-03-16 22:47
Same Problem!

**Comment by fmiyahira** [comment] 2020-03-31 13:08
@emersonsiega Thank you so much!

**Comment by payam-zahedi** [comment] 2020-05-01 09:05
I hade the same problem in Android:
flutter version: 1.12.13+hotfix.8

**Comment by zenghuixiang** [comment] 2020-05-09 03:31
I had the same problem, and I solved it this way.
` Future getImage(index) async {
    Map<PermissionGroup, PermissionStatus> permissions =
    await PermissionHandler()
        .requestPermissions([PermissionGroup.camera]);
    if(permissions[PermissionGroup.camera] != PermissionStatus.granted){
      showToast("无相机访问权限，请设置允许相机权限");
      return;
    }
    var image = await ImagePicker.pickImage(source: ImageSource.camera);
    setState(() {
       _image = image;
    });
  }`

**Comment by fysoul17** [comment] 2020-05-09 04:04
@zenghuixiang 
Thanks for posting but, that is not a solution. It is a workaround which needs additional package to import.
Also, it was mentioned by emersonsiega before.

**Comment by pedromassangocode** [comment] 2021-02-09 13:54
Hi @fysoul17 
I cannot reproduce the issue on latest version of the plugin.

<img height="720" src="https://user-images.githubusercontent.com/67424416/107373177-84ebcb80-6ae6-11eb-8bb8-ca3d4ccb27b6.gif">

I'm closing this as probably fixed. For anyone facing this exact same issue please feel free to write in the comments bellow and I will reopen it.
Thank you

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: SafeArea(
          child: Center(
            child: ElevatedButton(
              child: Text('Pick Image'),
              onPressed: () async {
                final file = await ImagePicker().getImage(source: ImageSource.gallery);
                print(file);
              },
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-AO)
    • Flutter version 1.22.6 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

**Closed** 2021-02-09 13:54 UTC
Labels: customer: crowd, p: image_picker, platform-android, plugin
