### ISSUE TITLE
Would be nice to have Material Theme'd Shrine

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#17779] opened 2018-05-21 18:43 UTC
It might already be in the plans.  But I notice the Shrine we show in flutter_gallery is the only pre-Material-theming shrine.

This is not at all urgent.

![image](https://user-images.githubusercontent.com/11857803/40324056-2d56b188-5cec-11e8-941d-b6e5df9e0cd2.png)

FYI @willlarche

**Comment by willlarche** [comment] 2018-05-21 18:46
Known! It will be a port of [the codelabs'](https://codelabs.developers.google.com/codelabs/mdc-104-flutter/index.html?index=..%2F..%2Findex#0) final result and maybe some more.

**Comment by willlarche** [comment] 2018-11-02 19:14
Duplicate of #22722

**Closed by willlarche** 2018-11-02 19:14 UTC
Labels: team: gallery
