### ISSUE TITLE
Add alignment property to SnackBar

### ISSUE THREAD

**Issue by joodo** [flutter/flutter#148164] opened 2024-05-11 07:48 UTC
### Use case

When setting `SnackBarBehavior.floating` and `width`, the snack bar will be centered horizontally, and there's no way to set it alignment, e.g. to left.

But according to  [M3 Design Guideline](https://m3.material.io/components/snackbar/guidelines#cf0196bb-45b0-43bd-8c20-24fec49de62a), snack bar could be left-aligned in wider layouts.

### Proposal

It's nice if there's a `alignment` property to control it.

btw, design guide link in "See also" in [flutter document](https://api.flutter.dev/flutter/material/SnackBar-class.html) is still for material 2, maybe it could update to material 3

**Comment by danagbemava-nc** [comment] 2024-05-13 07:52
Closing this as a duplicate of https://github.com/flutter/flutter/issues/113039. Please feel free to share your thoughts in the issue linked above. 

> btw, design guide link in "See also" in [flutter document](https://api.flutter.dev/flutter/material/SnackBar-class.html) is still for material 2, maybe it could update to material 3

Please feel free to file a new issue for this so it can be properly tracked. 

Thank you

**Closed by danagbemava-nc** 2024-05-13 07:52 UTC
Labels: in triage
