### ISSUE TITLE
Keyboard on iOS flashes when switching between textfields when obscured and crash

### ISSUE THREAD

**Issue by fransboumans** [flutter/flutter#64628] opened 2020-08-26 09:16 UTC
## Steps to Reproduce

On an iOS device/emulator, when switching between the two textfields that have `obscureText: false`, nothing happens. When switching between a textfield that has `obscureText: false` and a textfield that has `obscureText: true`, the keyboard flashes. This also happens when switching between textfields that both have `obscureText: true`.

![screen rec](https://user-images.githubusercontent.com/47666110/91285975-24620f80-e78e-11ea-9bb9-fc2ebf8f366e.gif)

~~Sometimes when I repeated these step, the app closed down completely without any error in de console, besides the message that the connection to the device has been lost.~~

This only happens on iOS (tested several iPhones & iPads), running the app on an Android device/emulator does not show this problem.

**Sample App**
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: MyHomePage());
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: EdgeInsets.symmetric(horizontal: 30.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CupertinoTextField(
              placeholder: 'Not obscure',
              autocorrect: false,
            ),
            CupertinoTextField(
              placeholder: 'Not obscure',
              autocorrect: false,
            ),
            CupertinoTextField(
              placeholder: 'Obscure',
              obscureText: true,
            ),
            CupertinoTextField(
              placeholder: 'Obscure',
              obscureText: true,
            ),
          ],
        ),
      ),
    );
  }
}
```

**Flutter doctor**
```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.78, on Mac OS X 10.15.6 19G2021, locale nl-NL)
    • Flutter version 1.22.0-2.0.pre.78 at /Users/fransboumans/flutter
    • Framework revision d0596582fe (3 hours ago), 2020-08-25 23:26:06 -0700
    • Engine revision b1d9f863db
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/fransboumans/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • E472E464-3C65-4013-9403-4B936440DE21 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-08-26 15:50
### No Issue `Channel stable, 1.20.2`

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.20.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision bbfbf1770c (13 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 13.6.1

• No issues found!
```

</details> 

### Reproduces on  beta to master






<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.21.0-9.1.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision be9bc8cb39 (8 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (3 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6.1
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 84.0.4147.135

• No issues found!
```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.22.0-1.0.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.22.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision ce40de69b7 (6 days ago), 2020-08-20 07:31:50 -0700
    • Engine revision 81027ab0cc
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (4 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 84.0.4147.135

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.81, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-2.0.pre.81 at /Users/tahatesser/Code/flutter_master
    • Framework revision 8c8b91069d (3 hours ago), 2020-08-26 06:03:05 -0700
    • Engine revision c7467a4359
    • Dart version 2.10.0 (build 2.10.0-59.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

 
[✓] Connected device (4 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      84.0.4147.135

• No issues found!
```

</details>

**Comment by LongCatIsLooong** [comment] 2020-08-26 16:34
What would be the best way to reproduce the crash? I kept trying for a few minutes but the sample app didn't crash.

**Comment by fransboumans** [comment] 2020-08-26 19:47
It sometimes crashes when switching between the fields that causes the flickering. Like selecting and/or using the keyboard done/next button using focus nodes. But it's quite random, the app shuts down completely and the log doesn't show anything accept that the connection to the device is lost.

**Comment by LongCatIsLooong** [comment] 2020-08-26 20:26
Still no luck :(.

@fransboumans how frequently does the crash happen for you? Do you mind running the project using xcode (using the "ios/Runner.xcworkspace" file), and sharing the objective C crash log?

**Comment by tesserx** [comment] 2020-08-27 02:19
@LongCatIsLooong also random crash for me, no logs just lost connection but keyboard flickers beta to master every time

**Comment by TahaTesser** [comment] 2020-08-27 02:23
@LongCatIsLooong  Also random crash for me, no logs just lost connection, but keyboard flickers beta to master every time

**Comment by LongCatIsLooong** [comment] 2020-08-27 02:41
@TahaTesser the crash and the flickering seem to be different problems. How often does it crash? It hasn't crashed a single time for me. Could you run the app from Xcode and see what the objective c exception is?

**Comment by TahaTesser** [comment] 2020-08-27 03:03
Now trying to reproduce, it's not crashing but keyboard flickers, it might have been related 
```
2020-08-27 08:28:33.292457+0530 Runner[4514:1203803] Metal API Validation Enabled
2020-08-27 08:28:33.620603+0530 Runner[4514:1204024] flutter: Observatory listening on http://127.0.0.1:51292/s4o0w-3-1Xg=/
2020-08-27 08:28:49.810055+0530 Runner[4514:1203803] [Common] _BSMachError: port bf3f; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2020-08-27 08:30:08.064592+0530 Runner[4514:1204016] [VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
```

@fransboumans 
If the crash is reproducible for you, please provide logs from Xcode by running app from xcodd. Iif see the crash again, I will post results. 

Editing title for now

**Comment by fransboumans** [comment] 2020-08-27 06:42
Seems I can't make it crash anymore. Must have been unrelated, my apologies for wasting any time on that! But the keyboard flickering still present.

**Comment by fransboumans** [comment] 2020-08-27 06:50
A second after writing my previous comment, it crashed. Got the Xcode log:

```
2020-08-27 08:46:07.149827+0200 Runner[2289:39872] flutter: Observatory listening on http://127.0.0.1:50099/KdK8G5as0JE=/
2020-08-27 08:46:09.177759+0200 Runner[2289:38641] Simulator user has requested new graphics quality: 100
2020-08-27 08:46:25.072924+0200 Runner[2289:38641] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString substringWithRange:]: Range {0, 5} out of bounds; string length 0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23ed09d1 _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff23ed0afe -[__NSCFString substringWithRange:].cold.1 + 94
	4   CoreFoundation                      0x00007fff23d725f1 -[__NSCFString substringWithRange:] + 177
	5   UIKitCore                           0x00007fff48fa3f36 -[TIDocumentState(UITextInputAdditions) copyTextInRange:fromDocument:] + 92
	6   UIKitCore                           0x00007fff48fa49cb -[TIDocumentState(UITextInputAdditions) initWithDocument:contextBoundary:] + 587
	7   UIKitCore                           0x00007fff48fa3d60 +[TIDocumentState(UITextInputAdditions) documentStateOfDocument:] + 53
	8   UIKitCore                           0x00007fff4912aa8a -[UIKeyboardImpl syncDocumentStateToInputDelegateWithExecutionContext:] + 1191
	9   UIKitCore                           0x00007fff4912b16f -[UIKeyboardImpl updateForChangedSelectionWithExecutionContext:] + 521
	10  UIKitCore                           0x00007fff4915c69d -[UIKeyboardTaskEntry execute:] + 147
	11  UIKitCore                           0x00007fff4915b1b3 -[UIKeyboardTaskQueue continueExecutionOnMainThread] + 310
	12  UIKitCore                           0x00007fff4911f09e -[UIKeyboardImpl setDelegate:force:] + 4597
	13  UIKitCore                           0x00007fff48dc7a61 -[UIInputResponderController _reloadInputViewsForKeyWindowSceneResponder:] + 2184
	14  UIKitCore                           0x00007fff48dc71bc -[UIInputResponderController _reloadInputViewsForResponder:] + 148
	15  UIKitCore                           0x00007fff493589f2 -[UIResponder(UIResponderInputViewAdditions) reloadInputViews] + 133
	16  UIKitCore                           0x00007fff49353b8b -[UIResponder becomeFirstResponder] + 830
	17  UIKitCore                           0x00007fff49816d52 -[UIView(Hierarchy) becomeFirstResponder] + 145
	18  Flutter                             0x0000000103456ad1 -[FlutterTextInputPlugin handleMethodCall:result:] + 149
	19  Flutter                             0x0000000103c7b96e __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	20  Flutter                             0x0000000103465756 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	21  Flutter                             0x000000010346a528 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	22  Flutter                             0x00000001037b4dc7 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_33NS_9allocatorIS8_EEFvvEEclEv + 83
	23  Flutter                             0x000000010347240d _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 117
	24  Flutter                             0x000000010347717a _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	25  CoreFoundation                      0x00007fff23da2414 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	26  CoreFoundation                      0x00007fff23da20ae __CFRunLoopDoTimer + 1038
	27  CoreFoundation                      0x00007fff23da170a __CFRunLoopDoTimers + 282
	28  CoreFoundation                      0x00007fff23d9c35e __CFRunLoopRun + 1950
	29  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	30  GraphicsServices                    0x00007fff38c39bbe GSEventRunModal + 139
	31  UIKitCore                           0x00007fff49325968 UIApplicationMain + 1605
	32  Runner                              0x00000001031cf0ab main + 75
	33  libdyld.dylib                       0x00007fff520ce1fd start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
2020-08-27 08:47:04.852323+0200 Runner[2289:39854] [VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (os/kern) invalid argument
(lldb) a
```

**Comment by TahaTesser** [comment] 2020-08-27 08:20
Following the steps from https://github.com/flutter/flutter/issues/64628#issuecomment-681631939, I can reproduce this crash 

```
2020-08-27 13:47:29.326076+0530 Runner[4665:1256066] Metal API Validation Enabled
2020-08-27 13:47:29.560252+0530 Runner[4665:1256268] flutter: Observatory listening on http://127.0.0.1:52289/2F1_2tStWOA=/
2020-08-27 13:48:10.822233+0530 Runner[4665:1256415] [general] Connection to daemon was invalidated
2020-08-27 13:48:38.349320+0530 Runner[4665:1256066] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString substringWithRange:]: Range {0, 7} out of bounds; string length 0'
*** First throw call stack:
(0x1a58c9344 0x1a55decc0 0x1a5922550 0x1a5922650 0x1a57a7c0c 0x1a9692b38 0x1a9693588 0x1a9692914 0x1a9800750 0x1a9800eb0 0x1a9834188 0x1a9832af0 0x1a5ccef94 0x1a5844d14 0x1a5844c68 0x1a5844420 0x1a583f1fc 0x1a583ebc8 0x1afc205cc 0x1a99f1744 0x104316c24 0x1a56bb384)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

**Comment by LongCatIsLooong** [comment] 2020-08-27 08:48
Thank you so much, this is tremendously helpful!  

The crash is probably caused by this line in the iOS input plugin:
https://github.com/flutter/engine/blob/871a402c752b47723bfcb5797f946caf9a3cb138/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L1279-L1281
Taking a closer look.

**Comment by Hixie** [comment] 2020-09-01 23:12
fixed by https://github.com/flutter/engine/pull/20805

**Closed** 2020-09-03 20:55 UTC
Labels: P2, a: quality, a: text input, engine, found in release: 1.21, found in release: 1.22, framework, has reproducible steps, platform-ios, severe: regression, waiting for PR to land (fixed)

**Comment by johnatdoshii** [comment] 2020-09-14 16:27
This issue appears to be occurring for us in beta channel (required as we also build for web), when will this fix be ported?

**Comment by tobycaulk** [comment] 2021-05-09 16:56
I'm seeing the screen flickering again, still between a `TextField` which has `isObscure` set to true and another `TextField` with `isObscure` set to false.

Flutter 2.0.5
iOS 14.5

https://user-images.githubusercontent.com/11463426/117580317-68e7ce00-b0c5-11eb-8b4a-c889587701b6.mov

**Comment by thomas-stockx** [comment] 2021-07-12 09:49
Why is this issue closed? The original report is about flickering, not a crash. So a crash fix shouldn't close an unrelated issue?

**Comment by TahaTesser** [comment] 2021-07-15 11:13
I just tried on the latest `stable` and `master`, there is no flickering 

|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5284e darwin-x64, locale
    en-GB)
    • Flutter version 2.2.3 at /Users/tahatesser/Code/flutter_stable
    • Framework revision f4abaa0735 (2 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.6
    • iPhone 12 Pro (mobile) • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • macOS 12.0 21A5284e darwin-x64
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.

```

```console
[✓] Flutter (Channel master, 2.4.0-5.0.pre.55, on macOS 12.0 21A5284e darwin-x64, locale en-GB)
    • Flutter version 2.4.0-5.0.pre.55 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b549e829e8 (12 hours ago), 2021-07-14 15:51:10 -0700
    • Engine revision 093c4ed1a3
    • Dart version 2.14.0 (build 2.14.0-312.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Code/openjdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.58.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • e534bcc711c9a011aa892eb51cdb60f40b3acddb • ios            • iOS 12.5.4 16H50
    • iPhone 12 Pro (mobile) • 77C62AB9-8B71-43CF-BCAB-85B0A5B52F85     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                    • darwin-x64     • macOS 12.0 21A5284e darwin-x64
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 91.0.4472.114

! Doctor found issues in 1 category.
```
		
</details>

✅ : No Issue ❌: Issue reproduced
