### ISSUE TITLE
"type 'Null' is not a subtype of type 'String' in type cast" exception when taking a screenshot in flutter drive on web

### ISSUE THREAD

**Issue by AlexanderArendar** [flutter/flutter#123768] opened 2023-03-30 12:02 UTC
I am assessing writing integration tests for flutter web.
I am running my test with flutter drive.
My flutter version is Flutter 3.7.7 • channel stable

The code for taking a screenshot is standard:
```
Future<void> main() async {
  await integrationDriver(
    onScreenshot: (String screenshotName, List<int> screenshotBytes) async {
      final File image = await File('screenshots/$screenshotName.png').create(recursive: true);
      image.writeAsBytesSync(screenshotBytes);
      return true;
    },
  );
}
```
The screenshot is created but also the app fails with the following exception:
```
Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast
#0      integrationDriver (package:integration_test/integration_test_driver_extended.dart:103:60)
<asynchronous suspension>
#1      main (file:///home/alex/Projects/whatif-analysis/ui/integration_test/driver.dart:5:3)
<asynchronous suspension>
Application finished.
```
I see the [ticket](https://github.com/flutter/flutter/issues/117077) which already supposed to have this fixed. It is closed but the problem looks like still actual or reappeared.

**Comment by exaby73** [comment] 2023-03-31 09:33
Could you try to produce a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by kwiatek91** [comment] 2023-04-13 08:56
i have exactly same issue after upgrading flutter to 3.7.9 from 3.0.1

`Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast
#0      integrationDriver (package:integration_test/integration_test_driver_extended.dart:103:60)
<asynchronous suspension>
#1      main (file:///Users/arkadiuszkwiatkowski/projekty/eSonel_client/apps/esonel_web/integration_test/test_driver/integration_test.dart:5:3)
<asynchronous suspension>
`

my test:

`import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:tests_elements/src/pages/mic/main_panel_page.dart';

import 'test_config/mock_authorization.dart';
import 'test_main.dart' as app;

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized() as IntegrationTestWidgetsFlutterBinding;

  MainPanelPage mainPanelPage;
  MockAuthorization mockAuthorization;
  const String token =
      'tokenHide';

  testWidgets('correct login as guest to form', (WidgetTester tester) async {
    mockAuthorization = MockAuthorization(token, token);
    await app.main([], mockAuthorization);

    await tester.pumpAndSettle(const Duration(seconds: 1));
    mainPanelPage = MainPanelPage(tester);
    await binding.takeScreenshot('screenshot-1');
    await mainPanelPage.ensureHelpButtonIsVisible();
  });
}
`

**Comment by exaby73** [comment] 2023-04-14 07:26
@kwiatek91 Could you provide a [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by kwiatek91** [comment] 2023-04-14 11:37
@exaby73  I download some demo project from github and i just add binding.takeScreenshot 
here is full project just download and run using standard command like:
flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart -d chrome --headless


[Flutter-Testing-master.zip](https://github.com/flutter/flutter/files/11232304/Flutter-Testing-master.zip)

**Comment by exaby73** [comment] 2023-04-17 06:52
I need a minimal example. Basically, as little code as possible to reproduce the issue, which does not use any 3rd party libraries. Please read [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) for more information

**Comment by kwiatek91** [comment] 2023-04-17 07:18
> I need a minimal example. Basically, as little code as possible to reproduce the issue, which does not use any 3rd party libraries. Please read [complete and minimal, reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) for more information
@exaby73 
[test.zip](https://github.com/flutter/flutter/files/11247325/test.zip)

**Comment by exaby73** [comment] 2023-04-17 07:46
@kwiatek91 Please provide a code sample along with the command being run. The code sample you provided is a complete app, and not minimal

**Comment by kwiatek91** [comment] 2023-04-17 10:19
@exaby73  that was demo app from command flutter create 
but here You have just integration test:
[integration_test.zip](https://github.com/flutter/flutter/files/11248899/integration_test.zip)
and command:
`flutter drive --driver=integration_test/test_driver/integration_test.dart --target=integration_test/main_view_test.dart -d chrome --no-headless`

**Comment by exaby73** [comment] 2023-04-18 07:05
While I can reproduce this issue on stable, this issue seems fixed on master. Therefore there is nothing to do here. Due to this, I'll close this issue. Thank you

**Comment by TahaTesser** [comment] 2023-06-14 07:05
Based on the above [comment](https://github.com/flutter/flutter/issues/123768#issuecomment-1512553260) and lack of activity, I feel safe to close this issue. 

Feel free to below comment if the issue is still reproducible non-stable channel.

**Closed by TahaTesser** 2023-06-14 07:05 UTC
Labels: r: invalid
