### ISSUE TITLE
SingleChildScrollView(GridView(CustomScrollView())) strange scrollbar artefact

### ISSUE THREAD

**Issue by renanyoy** [flutter/flutter#124379] opened 2023-04-07 08:09 UTC
## Steps to Reproduce

CustomScrollView in grid children on flutter web

1. Execute `flutter run` on the code sample 
scrolling one grid item, scroll also others scrollbars..

**Expected results:** 
ScrollBars shouldn't synchronize

**Actual results:** 
ScrollBars are synchronized

<details>
<summary>Code sample</summary>

```dart

GridView.builder(itemBuilder: (_,__) => CustomScrollView(slivers:[...]));

```

</details>

<details>
  <summary>Logs</summary>

```

no errors in log

```

```
Analyzing l2k.io...                                                     
No issues found! (ran in 2.3s)
```

```
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2.1 22D68 darwin-arm64, locale en-FR)
    • Flutter version 3.7.10 on channel stable at /Users/renanyoy/code/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (3 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/renanyoy/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • IPhone14.renan (mobile) • 00008120-0009582C2100C01E • ios            • iOS 16.3.1 20D67
    • macOS (desktop)         • macos                     • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 111.0.5563.146
    ! Device 902149303267 is not authorized.
      You might need to check your device for an authorization dialog.

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

https://user-images.githubusercontent.com/259671/230569710-1f43098a-8241-4e88-a352-39aa7b90a21e.mp4

**Comment by huycozy** [comment] 2023-04-07 10:46
From your demo video, it looks like the issue is coming with Scrollbar rather than the list inside GridView since I see the 2nd list didn't move. 

In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 
I built a simple minimal sample here and don't see the issue (perhaps I haven't added a Scrollbar but I'm not sure about your case). You may continue using it to represent your case. 

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: GridView.builder(
          itemBuilder: (_, __) => CustomScrollView(
            slivers: [
              SliverFixedExtentList(
                itemExtent: 50.0,
                delegate: SliverChildBuilderDelegate(
                  (BuildContext context, int index) {
                    return Container(
                      alignment: Alignment.center,
                      color: Colors.lightBlue[100 * (index % 9)],
                      child: Text('List Item $index'),
                    );
                  },
                ),
              ),
            ],
          ),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
          ),
        ),
      ),
    );
  }
}

```
</details>


https://user-images.githubusercontent.com/104349824/230595881-87c03c31-fe6d-4d42-998d-83a074820739.mov

**Comment by huycozy** [comment] 2023-04-11 11:37
As far as I can see, it seems it is caused by the implementation. When removing `Scrollbar` widget on your lastest sample code above, I see it works well with its Scrollbar, and the scrolling behavior is not conflicted between lists (compared to your origin video).

https://user-images.githubusercontent.com/104349824/231150086-8c3b3866-9a5a-41d7-b0df-4a4dcbfe0de9.mov

Please try removing `Scrollbar` widget and confirm if it's solved on your end.

**Comment by renanyoy** [comment] 2023-04-11 12:19
I don't have any scrollbar widget in my code

**Comment by renanyoy** [comment] 2023-04-11 15:00
https://user-images.githubusercontent.com/259671/231204190-12f7128c-8ba9-4e19-ba6c-d807697bcadf.mp4

**Comment by huycozy** [comment] 2023-04-12 05:02
It seems there is a conflict between controllers that I see they don't exist on your sample code. I would suggest you attach the corresponding controller for scroll views to see if it can solve your case.

**Comment by renanyoy** [comment] 2023-04-12 05:14
I tried that on my app,it didn't worked, same for keys, that's why I opened an issue here..

**Comment by huycozy** [comment] 2023-04-13 04:46
Hi. I see it already worked as my demo at https://github.com/flutter/flutter/issues/124379#issuecomment-1503168499. Can you share the reason why you need to put `SingleChildScrollView` outside `GridView`, it seems redundant and make the layout more complicated. 

Also, as the problem is going differently from the original description (and sample code), this will be difficult for anyone to deal with next steps. If you still want to continue using `SingleChildScrollView` for this case, please leave a comment describing the problem (Description of the problem, actual/expected result and final sample code) or file a new issue would be appreciated. Thank you!

**Comment by renanyoy** [comment] 2023-04-13 05:51
it's a complex web site with the with the main scroll view managed and at a different level than the page contents..
I opened a new issue #124770

**Comment by huycozy** [comment] 2023-04-13 07:45
Thanks for filing a new issue. I will close this issue in favor of a new one at https://github.com/flutter/flutter/issues/124770.

**Closed by huycozy** 2023-04-13 07:45 UTC
Labels: in triage
