### ISSUE TITLE
Is it possible to interact to Unity wrapped by Flutter?

### ISSUE THREAD

**Issue by Amasian** [flutter/flutter#35759] opened 2019-07-08 20:05 UTC
I want to use flutter to figure out the smartphone model of the user and send the data to Unity. Is it possible to send such data to inside of Unity app?

**Comment by ketanm** [comment] 2019-07-10 02:49
This is not a Flutter related question.

Also, you can directly use Unity/C# API (https://docs.unity3d.com/ScriptReference/SystemInfo.html) to query device info. If you need more information than better to write a native plugin and call it from Unity.

**Comment by BondarenkoStas** [comment] 2019-09-30 13:36
As mentioned above, I think it's safe to close the issue. If there is something more to add, please comment and I will re-open it.

**Closed by BondarenkoStas** 2019-09-30 13:36 UTC

**Comment by iapicca** [comment] 2021-01-05 08:06
duplicate of duplicate of https://github.com/flutter/flutter/issues/18509
