### ISSUE TITLE
Getting the size of a widget should have a simplified API

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2321] opened 2016-03-02 18:10 UTC
Currently to get the size of a widget you need to do this:

```dart
  Size get _size {
    assert(mounted);
    RenderBox box = context.findRenderObject();
    assert(box != null);
    assert(box.hasSize);
    return box.size;
  }
```

It'd be nice to have this as a built in api.

((I'm copying this code all over the place.))

Similarly getting the size of the widget via  GlobalKey would be good too.  Maybe something can be added to GlobalKey?

**Comment by abarth** [comment] 2016-03-02 18:20
From @Hixie duplicate of this bug.

This is a common pattern:

```
  Size get size {
    assert(mounted);
    RenderBox box = context.findRenderObject();
    assert(box != null);
    assert(box.hasSize);
    return box.size;
  }
```

We should add this to the BuildContext method as a function that returns a Size. It should assert we're not calling it during a frame (certainly not in the build phase, anyway). In checked mode, it should return a _WidgetDebugSize, a new class that refuses to be used during the build phase.

**Closed** 2016-10-17 19:33 UTC
Labels: affects: framework, easy fix, ⚠ brand new feature
