### ISSUE TITLE
Throws LateInitializationError: Field `_devToolsStart@403127165` has not been initialized in flutter web.

### ISSUE THREAD

**Issue by Anas35** [flutter/flutter#118009] opened 2022-12-23 03:08 UTC
**Steps to reproduce:**

`flutter create test`
`cd test`

`flutter run -v` and select chrome

once build, open dev tools using link

**Error message:**
```
DevHandler: VmService proxy responded with an error:
           {error: {code: -32000, message: LateInitializationError: Field '_devToolsStart@403127165' has not been
           initialized., data: {details: #0      DwdsStats._devToolsStart (package:dwds/src/events.dart)
           flutter/devtools#1      DwdsStats.devToolsStart (package:dwds/src/events.dart:16:33)
           flutter/devtools#2      _processSendEvent (package:dwds/src/dwds_vm_client.dart:158:39)
           flutter/devtools#3      DwdsVmClient.create.<anonymous closure> (package:dwds/src/dwds_vm_client.dart:107:7)
           flutter/devtools#4      VmService._routeRequest (package:vm_service/src/vm_service.dart:2393:27)
           flutter/devtools#5      VmService._processRequest (package:vm_service/src/vm_service.dart:2363:25)
           flutter/devtools#6      VmService._processMessageStr (package:vm_service/src/vm_service.dart:2330:9)
           flutter/devtools#7      VmService._processMessage (package:vm_service/src/vm_service.dart:2288:7)
           flutter/devtools#8      _rootRunUnary (dart:async/zone.dart:1406:47)
           flutter/devtools#9      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
           flutter/devtools#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
           flutter/devtools#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           flutter/devtools#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           flutter/devtools#13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
           flutter/devtools#14     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
           flutter/devtools#15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
           flutter/devtools#16     _rootRunUnary (dart:async/zone.dart:1414:13)
           flutter/devtools#17     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
           flutter/devtools#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
           flutter/devtools#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           flutter/devtools#20     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
           flutter/devtools#21     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
           flutter/devtools#22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
           flutter/devtools#23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:204:15)
           flutter/devtools#24     StackZoneSpecification._registerCallback.<anonymous closure>
           (package:stack_trace/src/stack_zone_specification.dart:114:48)
           flutter/devtools#25     _rootRun (dart:async/zone.dart:1390:47)
           flutter/devtools#26     _CustomZone.run (dart:async/zone.dart:1300:19)
           flutter/devtools#27     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
           flutter/devtools#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
           flutter/devtools#29     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:204:15)
           flutter/devtools#30     StackZoneSpecification._registerCallback.<anonymous closure>
           (package:stack_trace/src/stack_zone_specification.dart:114:48)
           flutter/devtools#31     _rootRun (dart:async/zone.dart:1398:13)
           flutter/devtools#32     _CustomZone.run (dart:async/zone.dart:1300:19)
           flutter/devtools#33     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
           flutter/devtools#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
           flutter/devtools#35     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           flutter/devtools#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           flutter/devtools#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
           flutter/devtools#38     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
           }}, id: 59, jsonrpc: 2.0}
```

**flutter doctor -v**
```
[√] Flutter (Channel beta, 3.7.0-1.2.pre, on Microsoft Windows [Version 10.0.19045.2364], locale en-IN)
    • Flutter version 3.7.0-1.2.pre on channel beta at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c29b09b878 (3 days ago), 2022-12-19 18:30:12 -0600
    • Engine revision 8c99b0feaf
    • Dart version 2.19.0 (build 2.19.0-444.2.beta)
    • DevTools version 2.20.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\moham\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.72.1)
    • VS Code at C:\Users\moham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2364]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.54

[√] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by huycozy** [comment] 2023-01-05 04:49
@Anas35 thanks for filing the issue. I also can reproduce this on the latest `beta` and `master` channels. 

Below are reports on some environments and channels:
- On `stable`, there is also the error message `DevHandler: VmService proxy responded with an error`, the stack trace doesn't exist though.
- This issue is only reproducible on Web whilst it doesn't happen on macOS, Android, or iOS.
- Moreover, it only happens with verbose running (-v).

<details>
<summary>Logs (master 3.7.0-14.0.pre.39)</summary>

```bash
[+17568 ms] DevHandler: VmService proxy responded with an error:
                     {jsonrpc: 2.0, id: 21, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method:
                     _setStreamIncludePrivateMembers, id: 21, params: {streamId: Debug, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 22, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           22, params: {streamId: Extension, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 24, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           24, params: {streamId: Isolate, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 25, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           25, params: {streamId: Logging, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 26, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           26, params: {streamId: Stderr, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 27, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           27, params: {streamId: Stdout, includePrivateMembers: false}}}}
[ +646 ms] DwdsVmClient: Received DevTools event: {type: DevtoolsEvent, payload: {screen: inspector, action: pageReady}, isolateId: 1}
[   +3 ms] DevHandler: VmService proxy responded with an error:
           {error: {code: -32000, message: LateInitializationError: Field '_devToolsStart@401127165' has not been initialized., data: {details: #0
           DwdsStats._devToolsStart (package:dwds/src/events.dart)
           #1      DwdsStats.devToolsStart (package:dwds/src/events.dart:16:33)
           #2      _processSendEvent (package:dwds/src/dwds_vm_client.dart:158:39)
           #3      DwdsVmClient.create.<anonymous closure> (package:dwds/src/dwds_vm_client.dart:107:7)
           #4      VmService._routeRequest (package:vm_service/src/vm_service.dart:2393:27)
           #5      VmService._processRequest (package:vm_service/src/vm_service.dart:2363:25)
           #6      VmService._processMessageStr (package:vm_service/src/vm_service.dart:2330:9)
           #7      VmService._processMessage (package:vm_service/src/vm_service.dart:2288:7)
           #8      _rootRunUnary (dart:async/zone.dart:1406:47)
           #9      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
           #10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
           #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
           #13     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
           #14     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
           #15     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
           #16     _rootRunUnary (dart:async/zone.dart:1414:13)
           #17     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
           #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
           #19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
           #20     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
           #21     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
           #22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
           #23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:204:15)
           #24     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:114:48)
           #25     _rootRun (dart:async/zone.dart:1390:47)
           #26     _CustomZone.run (dart:async/zone.dart:1300:19)
           #27     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
           #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
           #29     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:204:15)
           #30     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:114:48)
           #31     _rootRun (dart:async/zone.dart:1398:13)
           #32     _CustomZone.run (dart:async/zone.dart:1300:19)
           #33     _CustomZone.runGuarded (dart:async/zone.dart:1208:7)
           #34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248:23)
           #35     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
           #36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
           #37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
           #38     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
           }}, id: 59, jsonrpc: 2.0}
[   +5 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 60, error: {code: -32602, message: Source report kind Coverage not supported}}


```
</details>
<details>
<summary>Logs (stable 3.3.10)</summary>

```bash
[+21950 ms] DevHandler: VmService proxy responded with an error:
                     {jsonrpc: 2.0, id: 21, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method:
                     _setStreamIncludePrivateMembers, id: 21, params: {streamId: Debug, includePrivateMembers: false}}}}
[   +2 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 22, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           22, params: {streamId: Extension, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 24, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           24, params: {streamId: Isolate, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 25, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           25, params: {streamId: Logging, includePrivateMembers: false}}}}
[        ] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 26, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           26, params: {streamId: Stderr, includePrivateMembers: false}}}}
[   +1 ms] DevHandler: VmService proxy responded with an error:
           {jsonrpc: 2.0, id: 27, error: {code: -32601, message: Method not found, data: {jsonrpc: 2.0, method: _setStreamIncludePrivateMembers, id:
           27, params: {streamId: Stdout, includePrivateMembers: false}}}}
[ +692 ms] DevHandler: VmService proxy responded with an error:
                    {jsonrpc: 2.0, id: 56, error: {code: -32602, message: Source report kind Coverage not supported}}
```
</details>

<details>
<summary>flutter doctor -v (stable, beta, master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.7.0-14.0.pre.39, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-14.0.pre.39 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision da1a854911 (36 minutes ago), 2023-01-04 22:36:16 -0500
    • Engine revision 35b7dee32b
    • Dart version 3.0.0 (build 3.0.0-85.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

```bash
[!] Flutter (Channel beta, 3.7.0-1.2.pre, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-1.2.pre on channel beta at /Users/huynq/Documents/GitHub/flutter_beta
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_beta. Consider adding /Users/huynq/Documents/GitHub/flutter_beta/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_beta. Consider adding /Users/huynq/Documents/GitHub/flutter_beta/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c29b09b878 (2 weeks ago), 2022-12-19 18:30:12 -0600
    • Engine revision 8c99b0feaf
    • Dart version 2.19.0 (build 2.19.0-444.2.beta)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by jason-simmons** [comment] 2023-01-10 01:00
@annagrin Is this a duplicate of https://github.com/dart-lang/webdev/issues/1874?

**Comment by fishythefish** [comment] 2023-07-26 19:41
@annagrin: This is showing up in triage. Do we need to take any further action?

**Comment by elliette** [comment] 2023-07-27 18:17
Closing as duplicate of https://github.com/dart-lang/webdev/issues/1874

**Closed by elliette** 2023-07-27 18:17 UTC
Labels: c: crash, dependency: dart, platform-web, d: devtools, has reproducible steps, found in release: 3.7, team-web
