### ISSUE TITLE
PathProviderPlugin  uses or overrides a deprecated API. Note: Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#54749] opened 2020-04-14 13:08 UTC
Note: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.5\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by VladyslavBondarenko** [comment] 2020-04-14 13:38
Hi @kw2019ltd 
This isn't an error and just "deliberate and temporary" warning
Closing as duplicate of https://github.com/flutter/flutter/issues/47153

**Closed by VladyslavBondarenko** 2020-04-14 13:38 UTC
