### ISSUE TITLE
Slider label text not rendered when nested in a Row

### ISSUE THREAD

**Issue by xqwzts** [flutter/flutter#15659] opened 2018-03-18 00:49 UTC
When nesting a Slider widget in a Row the thumb shows up, but the text isn't rendered:

![flutter_01](https://user-images.githubusercontent.com/798935/37561408-9158165e-2a56-11e8-94b6-6558eea5ec18.png)

```dart
Widget _buildLineControls() {
    return new Column(
      children: <Widget>[
        new Row(
          children: <Widget>[
            const Text('Line width:'),
            new Expanded(
              child: new Slider(
                min: 1.0,
                max: 15.0,
                divisions: 15,
                label: '${lineWidth.round()}',
                value: lineWidth,
                activeColor: lineColor,
                onChanged: onLineWidthChanged,
              ),
            ),
          ],
        ),
      ],
    );
  }
```

But it works fine without the Row:

![flutter_02](https://user-images.githubusercontent.com/798935/37561421-cc897a7e-2a56-11e8-950b-1fe527c2d9f5.png)

```dart
Widget _buildLineControls() {
    return new Column(
      children: <Widget>[
               new Slider(
                min: 1.0,
                max: 15.0,
                divisions: 15,
                label: '${lineWidth.round()}',
                value: lineWidth,
                activeColor: lineColor,
                onChanged: onLineWidthChanged,
              ),
      ],
    );
  }
```

This is on the latest master version:
> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.2.3-pre.41, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Community Edition (version 2017.2)
[✓] VS Code (version 1.21.1)
[✓] Connected devices (1 available)

**Comment by jason-simmons** [comment] 2018-03-21 00:21
Duplicate of https://github.com/flutter/flutter/issues/15702

**Closed by jason-simmons** 2018-03-21 00:21 UTC
