### ISSUE TITLE
generated .gitignore for flutter module shouldn't include .android directory.

### ISSUE THREAD

**Issue by efortuna** [flutter/flutter#21706] opened 2018-09-11 22:41 UTC
Currently the .gitignore generated when you type `flutter create -t module foo` inside `foo` contains the line ".android". My testing suggests excluding this from a git checkout causes problems for other people trying to check out your project. 

You can test this by:

1. Start with some existing android project and follow the instructions here: https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
1. Create a repository with both the android app and the flutter module. Commit and push.
1. Somewhere else, check out that repository and try to load in android studio.
You will see an error like the following: 

```
Error:/usr/local/google/home/efortuna/github/flutter_dof/.android/include_flutter.groovy (/usr/local/google/home/efortuna/github/flutter_dof/.android/include_flutter.groovy)

Consult IDE log for more details (Help | Show Log)
```

```
 $ flutter doctor -v
[✓] Flutter (Channel master, v0.8.3-pre.28, on Linux, locale en_US.UTF-8)
    • Flutter version 0.8.3-pre.28 at /usr/local/google/home/efortuna/googleio/flutter
    • Framework revision 0e8103ff13 (5 hours ago), 2018-09-11 18:16:21 +0200
    • Engine revision 9a173a8dc8
    • Dart version 2.1.0-dev.4.0.flutter-ef72098353

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/google/home/efortuna/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 27.0.3
    • Java binary at: /opt/android-studio-3.0/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.0)
    • Android Studio at /opt/android-studio-3.0
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at /opt/intellij-ce-2018.1
    • Flutter plugin version 27.0.2
    • Dart plugin version 181.4892.1

[✓] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at /opt/intellij-ce-2017.3
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700

[✓] VS Code (version 1.25.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Pixel 2 XL • 711KPAE0891080 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by zoechi** [comment] 2019-02-14 10:12
Still added
```
[✓] Flutter (Channel master, v1.2.1-pre.142, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by neiljaywarner** [comment] 2019-03-01 01:01
@efortuna @zoechi  this is one of my major concerns for our team of 10 iOS/10 Android developers.

(But of course if you check in .android, then you check in local.properties ..)

**Comment by arturdm** [comment] 2019-03-13 12:40
@neiljaywarner you could modify your generated `.android/Flutter/build.gradle` file to fallback to `FLUTTER_ROOT` environment variable if there is no `local.properties`. It's not a nice solution to change generated files but it works for now.

Here's the diff for flutter repository:

```
diff --git a/packages/flutter_tools/templates/app/android-java.tmpl/app/build.gradle.tmpl b/packages/flutter_tools/templates/app/android-java.tmpl/app/build.gradle.tmpl
index d41c8b8a1..aa3d1b9f6 100644
--- a/packages/flutter_tools/templates/app/android-java.tmpl/app/build.gradle.tmpl
+++ b/packages/flutter_tools/templates/app/android-java.tmpl/app/build.gradle.tmpl
@@ -6,9 +6,9 @@ if (localPropertiesFile.exists()) {
     }
 }

-def flutterRoot = localProperties.getProperty('flutter.sdk')
+def flutterRoot = localProperties.getProperty('flutter.sdk') ?: System.getenv("FLUTTER_ROOT")
 if (flutterRoot == null) {
-    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
+    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file or with a FLUTTER_ROOT environment variable.")
 }

 def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
```

@efortuna @zoechi What do you think about applying this patch? Unfortunately, it does not solve the  main issue of adding the `.android` to the repository in the first place.

**Comment by arturdm** [comment] 2019-03-29 12:12
Found a better way and it's not necessary to keep `.android` in the repo anymore.

`.android` is generated when running `flutter packages get` inside the module so we can force gradle to call it before evaluating flutter module in `settings.gradle`:

```
include ':app'

Process process = "flutter packages get".execute(
    System.getenv().collect { key, value -> "$key=$value" },
    new File("<FLUTTER_MODULE_PATH>"))
process.waitForProcessOutput(System.out, System.err)

setBinding(new Binding([gradle: this]))
evaluate(new File(
        settingsDir,
        "<FLUTTER_MODULE_PATH>/.android/include_flutter.groovy"
))

```

**Comment by jmagman** [comment] 2019-12-19 22:22
There was some attempt to document this with https://flutter.dev/docs/development/add-to-app/ios/project-setup#module-organization and https://flutter.dev/docs/development/add-to-app/android/project-setup#create-a-flutter-module with the ".ios/.android directory is emphemeral, run `flutter pub get` to generate it.

@stevemessick @xster Does Android Studio handle a missing .android directory (like after a git clone) in the module?  Does it ever run `flutter pub get` or `flutter build` in the module, or mostly is just creation supported?
https://flutter.dev/docs/development/add-to-app/android/project-setup#using-android-studio

**Comment by jmagman** [comment] 2019-12-19 23:40
@stevemessick That button is going to run `flutter pub get` in the module, not the host app, right?

**Comment by blasten** [comment] 2020-01-04 00:12
Duplicate of https://github.com/flutter/flutter/issues/30842  (cc @xster)

**Comment by jmagman** [comment] 2020-01-04 00:58
Reopening, that's a duplicate of this.

**Closed** 2020-01-09 04:35 UTC
Labels: a: existing-apps, tool, ▣ platform-android
