### ISSUE TITLE
[Fonts] Icon request: electric_bolt

### ISSUE THREAD

**Issue by this-is-allan** [flutter/flutter#100873] opened 2022-03-28 01:09 UTC
put the icon: electric_bolt: https://fonts.google.com/icons?selected=Material+Icons&icon.query=electric_bolt

**Comment by shreykinshu** [comment] 2022-03-28 05:27
can I work on this issue

**Comment by maheini** [comment] 2022-03-28 08:07
You can use [flash_on](https://api.flutter.dev/flutter/material/Icons/flash_on-constant.html)

**Comment by guidezpl** [comment] 2022-03-28 08:36
Duplicate of https://github.com/flutter/flutter/issues/100873

**Closed by guidezpl** 2022-03-28 08:36 UTC
Labels: in triage
