### ISSUE TITLE
rfw golden pixel customer test blocking engine -> framework roll

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#151611] opened 2024-07-11 20:30 UTC
Starting with https://github.com/flutter/flutter/pull/151594, which contains only Skia rolls.

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8742693942250287281/+/u/run_test.dart_for_customer_testing_shard_and_subshard_None/stdout

```
| 00:13 +41: /b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.VLKIXZ/tests/packages/rfw/test/material_widgets_test.dart: Material widgets
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following assertion was thrown while running async test code:
| Golden "goldens/material_test.scaffold.png": Pixel test failed, 0.00%, 4px diff detected.
```

And others.

cc @bdero @Hixie

**Comment by zanderso** [comment] 2024-07-11 20:31
cc @goderbauer

**Comment by zanderso** [comment] 2024-07-11 20:32
Maybe the pixel test could have a larger tolerance?

**Comment by Hixie** [comment] 2024-07-11 20:33
fine by me. long term we should probably move to the "silver test" thing i'm working on, to avoid skia internals affecting this, though it does mean we'd stop catching a large class of potential regressions...

**Comment by zanderso** [comment] 2024-07-11 22:25
@Hixie or @goderbauer are you able to make the change to make the test pass?

**Comment by zanderso** [comment] 2024-07-12 15:06
I disabled the rfw tests in https://github.com/flutter/tests/pull/386 and filed https://github.com/flutter/flutter/issues/151659 to re-enable them. Leaving this issue open to track the engine -> framework roll recovering.

**Comment by goderbauer** [comment] 2024-07-16 09:50
(triage): Closing this as it looks like the engine roll has recovered and we have https://github.com/flutter/flutter/issues/151659 on file to track the follow-up work.

**Closed by goderbauer** 2024-07-16 09:50 UTC
Labels: package, P0, p: rfw, team-framework
