### ISSUE TITLE
Execution failed for task ":app:processDebugResources"

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#27420] opened 2019-02-02 03:00 UTC
I executed `flutter run -v` and below messages are error of that. What issues are related to this problem? How can I fix it? `flutter doctor -v` is no problem.

> [        ] FAILURE: Build failed with an exception.
> [   +7 ms] * What went wrong:
> [   +1 ms] Execution failed for task ':app:processDebugResources'.
> [        ] > Android resource linking failed
> [        ]   Output:
> C:\haram\github\Privacy-of-Animal\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:137:
> error: resource android:attr/fontVariationSettings not found.
> [   +1 ms]
> C:\haram\github\Privacy-of-Animal\build\app\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:137:
> error: resource android:attr/ttcIndex not found.
> [   +1 ms]   error: failed linking references.
> [   +1 ms]   Command:
> C:\Users\baeharam\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\896b1c8eb3cbaaac863640ff790ded2c\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
> [   +1 ms]           C:\AndroidSDK\platforms\android-27\android.jar\
> [   +1 ms]           --manifest\
> [        ]
> C:\haram\github\Privacy-of-Animal\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
> [   +1 ms]           -o\
> [        ]
> C:\haram\github\Privacy-of-Animal\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\[   +1 ms]           -R\
> [        ]
> @C:\haram\github\Privacy-of-Animal\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
> [   +1 ms]           --auto-add-overlay\
> [   +1 ms]           --java\
> [   +1 ms]
> C:\haram\github\Privacy-of-Animal\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
> [   +1 ms]           --custom-package\
> [        ]           com.handong.privacyofanimal\
> [   +1 ms]           -0\
> [   +1 ms]           apk\
> [   +1 ms]           --output-text-symbols\
> [        ]           C:\haram\github\Privacy-of-Animal\build\app\intermediates\symbols\debug\R.txt\
> [        ]           --no-version-vectors
> [   +1 ms]   Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
> [        ]   Output:
> C:\Users\baeharam\.gradle\caches\transforms-1\files-1.1\core-1.0.0.aar\b0636d1937382dd2344264c93f4f6ef2\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.
> [   +1 ms]
> C:\Users\baeharam\.gradle\caches\transforms-1\files-1.1\core-1.0.0.aar\b0636d1937382dd2344264c93f4f6ef2\res\values\values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.
> [        ]   error: failed linking references.
> [        ]   Command:
> C:\Users\baeharam\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\896b1c8eb3cbaaac863640ff790ded2c\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
> [   +1 ms]           C:\AndroidSDK\platforms\android-27\android.jar\
> [        ]           --manifest\
> [        ]
> C:\haram\github\Privacy-of-Animal\build\app\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
> [        ]           -o\
> [        ]
> C:\haram\github\Privacy-of-Animal\build\app\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\[        ]           -R\
> [        ]
> @C:\haram\github\Privacy-of-Animal\build\app\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
> [   +1 ms]           --auto-add-overlay\
> [        ]           --java\
> [        ]
> C:\haram\github\Privacy-of-Animal\build\app\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
> [        ]           --custom-package\
> [        ]           com.handong.privacyofanimal\
> [        ]           -0\
> [        ]           apk\
> [        ]           --output-text-symbols\
> [   +1 ms]           C:\haram\github\Privacy-of-Animal\build\app\intermediates\symbols\debug\R.txt\
> [   +1 ms]           --no-version-vectors
> [        ]   Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
> [        ] * Try:
> [        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> [   +1 ms] * Get more help at https://help.gradle.org
> [        ] BUILD FAILED in 14s

**Comment by gabrc52** [comment] 2019-02-02 19:31
What plugins are you using?

**Comment by Mikkelet** [comment] 2019-02-03 00:04
Im getting the same issue. I think it is caused by the cloud firestore plugin.

**Comment by nemoryoliver** [comment] 2019-02-04 03:17
make sure all your plugins are Android X ready. check all plugins for updates.

**Comment by mklim** [comment] 2019-02-06 02:32
This is caused by #27106, closing this as a duplicate.

[This comment](https://github.com/flutter/flutter/issues/27106#issuecomment-458366675) has more details and info on how to fix the compile problem.

**Closed by mklim** 2019-02-06 02:32 UTC
