### ISSUE TITLE
Autofill email and password not working in iOS

### ISSUE THREAD

**Issue by bakht200** [flutter/flutter#132933] opened 2023-08-21 07:11 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I used autofill hints in the text form field and autofill group it works fine in Android but not in any IOS version, I already enabled the autofill in iOS devices.

Added an associated domain 
<img width="341" alt="Screenshot 2023-08-21 at 12 07 54 PM" src="https://github.com/flutter/flutter/assets/62112170/c1323df3-a0cc-447d-8469-159c45bda61d">

enabled autofill credential provider in the Xcode too.

### Expected results

When I click on the login button I'm calling this function

  TextInput.finishAutofillContext(shouldSave: true);
  
 it works perfectly fine and shows me a dialogue box while clicking on the login button to save my email and password But in IOS after clicking on iOS it should also save my email and password in the Chrome password manager

### Actual results

When I click on the login button I'm calling this function

  TextInput.finishAutofillContext(shouldSave: true);
  
 it works perfectly fine and show me a dialogue box while clicking on login button to save my email and password But in IOS after clicking on iOS it doesnt save my email and password in the chrome password manager

### Code sample

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: Scaffold(
        appBar: AppBar(title: const Text(_title)),
        body: MyStatefulWidget(),
      ),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  var isSameAddress = true;

  final billingAddress1Key = UniqueKey();
  final billingAddress2Key = UniqueKey();
  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) => Form(
        key: _formKey,
        child: AutofillGroup(
          onDisposeAction: AutofillContextAction.commit,
          child: ListView(
            padding: EdgeInsets.symmetric(horizontal: 16),
            children: [
              Column(
                children: [
                  TextFormField(
                    autofillHints: [AutofillHints.email],
                    validator: (value) =>
                        value!.isEmpty ? "some email please" : null,
                    decoration: const InputDecoration(
                      labelText: 'email',
                      hintText: 'enter email adress',
                    ),
                  ),
                  TextFormField(
                    autofillHints: [AutofillHints.password],
                    validator: (value) =>
                        value!.isEmpty ? "some password please" : null,
                    decoration: const InputDecoration(
                      labelText: 'password',
                      hintText: 'enter your password',
                    ),
                  ),
                ],
              ),
              MaterialButton(
                child: Text("submit"),
                onPressed: () {
                  if (_formKey.currentState!.validate()) {
                    TextInput.finishAutofillContext(shouldSave: true);
                    debugPrint("----> Naigate to 2nd Page");
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => SecondRoute()),
                    );
                  }
                },
              ),
            ],
          ),
        ),
      );

  @override
  void dispose() {
    debugPrint("Form widget disposed");
    super.dispose();
  }
}

class SecondRoute extends StatefulWidget {
  @override
  _SecondRouteState createState() => _SecondRouteState();
}

class _SecondRouteState extends State<SecondRoute> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second Route"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            debugPrint("----> Naigate back to first page");
            Navigator.pop(context);
            //Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => MyApp()));
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }

  @override
  void dispose() {
    debugPrint("2nd Screen widget disposed");
    super.dispose();
  }
}

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.0.1 22A400 darwin-arm64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.68.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!

**Comment by dam-ease** [comment] 2023-08-21 11:54
Hi @bakht200. Thanks for filing this. I see there is an already open issue describing this exact case. Closing this as a duplicate of https://github.com/flutter/flutter/issues/116889, kindly upvote, comment and follow up on the issue for updates.
Thank you!

**Closed by dam-ease** 2023-08-21 11:54 UTC
Labels: in triage
