### ISSUE TITLE
Material buttons don't respect ThemeData ButtonStyle Text Color

### ISSUE THREAD

**Issue by steeling** [flutter/flutter#81998] opened 2021-05-06 22:16 UTC
When using themedata, and setting elevatedbuttonthemedata's textstyle color, it does not respect the color. It does respect things like font size and fonts.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

```
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (5 weeks ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2
```

**Comment by TahaTesser** [comment] 2021-05-10 12:52
Hi @steeling 
Thanks for filing the issue! It's not just `ElevatedButtonThemeData` but also other buttons such as `TextButtonThemeData` 

Reproduced the issue using the following minimal code sample below on the latest channels

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData().copyWith(
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ButtonStyle(
            textStyle: MaterialStateProperty.all(
              TextStyle(
                color: Colors.red,
                backgroundColor: Colors.blue[700],
              ),
            ),
          ),
        ),
        textButtonTheme: TextButtonThemeData(
          style: ButtonStyle(
            textStyle: MaterialStateProperty.all(
              TextStyle(
                color: Colors.red,
                backgroundColor: Colors.blue[700],
              ),
            ),
          ),
        ),
      ),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              child: Text('Global theme - textStyle - color not working'),
              onPressed: () {},
            ),
            TextButton(
              onPressed: () {},
              child: Text('Global theme - textStyle - color not working'),
            ),
            ElevatedButtonTheme(
              data: ElevatedButtonThemeData(
                style: ButtonStyle(
                  textStyle: MaterialStateProperty.all(
                    TextStyle(
                      color: Colors.red,
                      backgroundColor: Colors.blue[700],
                    ),
                  ),
                ),
              ),
              child: ElevatedButton(
                onPressed: () {},
                child: Text(
                    'ElevatedButtonTheme - textStyle - color also not working'),
              ),
            ),
            SizedBox(height:25),
            Text(
              "All buttons above should have red text like this",
              style: TextStyle(
                color: Colors.red,
                backgroundColor: Colors.blue[700],
              ),
            ),
            Text(
              "Notice Global theme/ElevatedButtonTheme - textStyle - backgroundColor is working",
              style: TextStyle(
                color: Colors.red,
                backgroundColor: Colors.blue[700],
              ),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details>

Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ✅  |   ✅  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1d9032c7e1 (11 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.3.0-1.0.pre.269, on macOS 11.3 20E232 darwin-x64,
    locale en-GB)
    • Flutter version 2.3.0-1.0.pre.269 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d28737eedf (15 hours ago), 2021-05-09 14:24:19 -0700
    • Engine revision f5b97d0b23
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Volumes/Extreme/IntelliJ IDEA CE.app
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```
		
</details>

**Comment by HansMuller** [comment] 2021-05-10 18:00
There are two possible sources for the text color in buttons, the ButtonStyle's foregroundColor and its textStyle color. To simplify overriding _just_ the text color, which has a non-null default value, the foregroundColor is used. The [defaultStyleOf](https://api.flutter.dev/flutter/material/ElevatedButton/defaultStyleOf.html) method does mention this:

> The color of the ButtonStyle.textStyle is not used, the ButtonStyle.foregroundColor color is used instead.

Here's a version of the example that works as expected:

<details>
<summary>Working code sample</summary>

```dart
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              child: Text('Global theme - textStyle - color not working'),
              onPressed: () {},
            ),
            TextButton(
              onPressed: () {},
              child: Text('Global theme - textStyle - color not working'),
            ),
            ElevatedButtonTheme(
              data: ElevatedButtonThemeData(
                style: ButtonStyle(
                  foregroundColor: MaterialStateProperty.all<Color>(Colors.red),
                  textStyle: MaterialStateProperty.all(
                    TextStyle(
                      backgroundColor: Colors.blue[700],
                    ),
                  ),
                ),
              ),
              child: ElevatedButton(
                onPressed: () {},
                child: Text(
                    'ElevatedButtonTheme - textStyle - color also not working'),
              ),
            ),
            SizedBox(height:25),
            Text(
              "All buttons above should have red text like this",
              style: TextStyle(
                color: Colors.red,
                backgroundColor: Colors.blue[700],
              ),
            ),
            Text(
              "Notice Global theme/ElevatedButtonTheme - textStyle - backgroundColor is working",
              style: TextStyle(
                color: Colors.red,
                backgroundColor: Colors.blue[700],
              ),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}


class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData().copyWith(
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ButtonStyle(
            foregroundColor: MaterialStateProperty.all<Color>(Colors.red),
            textStyle: MaterialStateProperty.all(
              TextStyle(
                backgroundColor: Colors.blue[700],
              ),
            ),
          ),
        ),
        textButtonTheme: TextButtonThemeData(
          style: ButtonStyle(
            foregroundColor: MaterialStateProperty.all<Color>(Colors.red),
            textStyle: MaterialStateProperty.all(
              TextStyle(
                backgroundColor: Colors.blue[700],
              ),
            ),
          ),
        ),
      ),
      home: Home(),
    );
  }
}


void main(){
  runApp(MyApp());
}
```

</details>

**Comment by bitsydarel** [comment] 2021-05-14 13:58
I think if the only things to be modified is the button text color and it's an app wide change, then it's better to just use ColorScheme as material design guideline suggest.

**Comment by HansMuller** [comment] 2024-02-28 17:58
Closing this since we've (finally) included a more comprehensive set of button examples. See for examples https://main-api.flutter.dev/flutter/material/TextButton-class.html

**Closed by HansMuller** 2024-02-28 17:58 UTC
Labels: framework, f: material design, d: api docs, d: examples, has reproducible steps, found in release: 2.0, found in release: 2.3, team-design, multiteam-retriage-candidate
