### ISSUE TITLE
macOS apps by default can't make http requests, we should document that

### ISSUE THREAD

**Issue by xster** [flutter/flutter#53982] opened 2020-04-04 07:29 UTC
Seems like macOS default apps can't make outgoing http requests. 
https://stackoverflow.com/questions/57841871/flutter-http-get-fails-on-macos-build-target-connection-failed

Confirmed on tot. 

Seems like something we should document in https://flutter.dev/desktop.

**Comment by stuartmorgan** [comment] 2020-04-04 13:50
Duplicate of #52902

**Closed by stuartmorgan** 2020-04-04 13:50 UTC
Labels: d: website - content, platform-mac
