### ISSUE TITLE
Windows 11, Flutter app (Target: Windows) doesn't Start, Fails to Find a file "app.so" in runner\Debug\data.

### ISSUE THREAD

**Issue by DuaRobin** [flutter/flutter#99221] opened 2022-02-27 05:50 UTC
## Steps to Reproduce
1. I'm on windows 11, Using Flutter 2.10.2, Created a new application with built in template using 'flutter create hello_flutter'. 
2. Executed `flutter run` and chose 1 for Windows.

**Expected results:** 

- Windows App should have started.

**Actual results:**

- App never started because of below error.

<details>
<summary>Code sample</summary>

```
Template Project w/ Flutter 2.10.2 and NO Changes
```
</details>

<details>
<summary>Logs</summary>

```
Launching lib\main.dart on Windows in debug mode...
Can't load AOT data from C:\Users\<user>\source\repos\hello_flutter\build\windows\runner\Debug\data\app.so; no such file.
Unable to start engine without AOT data.
Failed to create view controller.
Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
Error launching application on Windows.
Exited (sigterm)
```
</details>

<details>
<summary>Additional Info</summary>

```
Note:

Build for Windows is generating a file app.so, and it's there in 'C:\Users\<user>\source\repos\hello_flutter\build\windows\app.so'.
However, during run time, it's trying to find the same file 'C:\Users\<user>\source\repos\hello_flutter\build\windows\runner\Debug\data\????'
```
</details>

**Comment by CodeDoctorDE** [comment] 2022-02-27 17:08
Duplicate of #https://github.com/flutter/flutter/issues/97086

**Closed** 2022-02-27 18:58 UTC
