### ISSUE TITLE
Cloud firestore crashes app in APK release mode

### ISSUE THREAD

**Issue by Jumpbotron** [flutter/flutter#41576] opened 2019-09-29 17:59 UTC
Flutter Cloud Firestore is creating an error on my Flutter App, when i execute it on a APK in release mode it just crashes the app and close it. I have AndroidX and everything works fine when i try the app from flutter run --release and i have my device connected. I have this issue for a week and I haven't found a way to solve it. First I thought it was an issue with the Google Maps Plugin but later I realize that it also happened in other parts of the app where i don't use it but where I used the cloud_firestore library too. So I think there is an issue with this

This is my flutter build apk log: 
```
Gabriels-MacBook-Pro:Safer jumpbotron$ flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              1.3s
Resolving dependencies...                                           4.0s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /Users/jumpbotron/Documents/programming/installations/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.9+2/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/jumpbotron/Documents/programming/installations/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.9+2/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/jumpbotron/Documents/programming/installations/flutter/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.3+6/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/jumpbotron/Documents/programming/installations/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.0+6/android/src/main/java/io/flutter/plugins/firebase/core/FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
RRemoved unused resources: Binary resource data reduced from 256KB to 233KB: Removed 8%
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                     117.5s
Built build/app/outputs/apk/release/app-release.apk (7.2MB).
```
 With flutter run 
![1](https://user-images.githubusercontent.com/24376974/65837068-eb3cc900-e2b8-11e9-8bb9-92c0a8ae7380.gif)

With APK file
![2](https://user-images.githubusercontent.com/24376974/65837072-eed05000-e2b8-11e9-9d61-658c5120f25b.gif)

**Comment by BondarenkoStas** [comment] 2019-09-29 19:36
@Jumpbotron did you migrate to AndroidX? What version of cloud_firestore do you use?
Also, may be related to #38934.

**Comment by Jumpbotron** [comment] 2019-09-30 01:15
> @Jumpbotron did you migrate to AndroidX? What version of cloud_firestore do you use?
> Also, may be related to #38934.

Yes i dit the migration to AndroidX I'm using cloud_firestore: ^0.12.9+2
As i said everything works fine with the flutter run command but the problem is when i make the  apk and i try to run the app from it

**Comment by sarbagyastha** [comment] 2019-09-30 08:22
Have you added proper proguard rules ?

**Comment by BondarenkoStas** [comment] 2019-09-30 10:28
@Jumpbotron and in build.gradle you use `classpath 'com.android.tools.build:gradle:3.4.2'`, not `3.5.0`, right?

**Comment by Jumpbotron** [comment] 2019-10-04 01:14
> @Jumpbotron and in build.gradle you use `classpath 'com.android.tools.build:gradle:3.4.2'`, not `3.5.0`, right?

That was the solution I needed, thank you very much. Why is it necessary to work with this version of Gradle?
Thank U very much

**Comment by BondarenkoStas** [comment] 2019-10-04 10:02
@Jumpbotron Cool, then I think it's safe to close this one. You can try using dev or master channel, if it will repeat there, please comment and I will re-open the issue right away.

The app bundle is built successfully. The issue is that in Android Gradle plugin 3.5.0, the app bundle is named app-<build-type>.aab instead of app.aab, which is what the Flutter tool expects. This will be fixed, but in the meanwhile the app bundle will be contained in build/app/outputs/bundle/<build-type>/ where <build-type> is release, debug or profile.

It was fixed here https://github.com/flutter/flutter/pull/39126 and went to the version 1.9.6, so not on stable/beta yet. I didn't see your flutter doctor, just assumed that if you encounter it, you may use stable.

**Closed** 2019-10-04 10:02 UTC
Labels: a: build, p: cloud_firestore, p: firebase, plugin, severe: crash

**Comment by kroikie** [comment] 2019-10-13 17:31
@Jumpbotron

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/325. Any further collaboration will be done there.

**Comment by hello-paulvin** [comment] 2021-06-03 11:52
I have this issue
