### ISSUE TITLE
print doesn't print log when call from dispose?

### ISSUE THREAD

**Issue by bravekingzhang** [flutter/flutter#20170] opened 2018-08-03 02:05 UTC
I make a plugin with platform_channels ,And I have print log in `EventChannel.StreamHandler`  callback function `onCancel`,
![image](https://user-images.githubusercontent.com/4476322/43620258-6307597a-9704-11e8-9231-c754f4d3c0e8.png)

 I  make call `mStreamSubscription.cancel()` in dispose(), which I expect print log ,but nothing do.

while ,if I trigger `mStreamSubscription.cancel()` in RaisedButton  onTap callback ,print do well.

**Comment by zoechi** [comment] 2018-08-03 05:48
Please add the output of `flutter doctor -v`.

When you set a breakpoint, is it hit?

Can you please post a complete main.dart that allows to reproduce?

**Comment by zoechi** [comment] 2018-10-08 09:11
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by zoechi** [comment] 2018-10-16 13:55
@ghwaldo 
Please add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2019-02-18 17:01
This is working as intended. When the app is killed, `dispose` is not executed.

You are probably looking for something like 
https://stackoverflow.com/questions/52074265/flutter-detect-killing-off-the-app/52074534#52074534 or #6827

**Closed by zoechi** 2019-02-18 17:01 UTC
Labels: engine, p: framework

**Comment by ghwaldo** [comment] 2019-04-15 06:21
Thank you, zoechi.
But one question: what's the function of dispose when it is never called ? Or is it called ? How can i check it ? What should be done in dispose when it is called ?
