### ISSUE TITLE
Google's pre-lauch report shows Android compatibility warnings

### ISSUE THREAD

**Issue by sanuzzi** [flutter/flutter#52201] opened 2020-03-08 16:24 UTC
In response to @iapicca in #36915:
> are you still experiencing this issue with the latest stable version of flutter?

And to @TahaTesser 
> Could everyone who still has this problem please file a new issue

Yes. The issue #36915 still happens.

![image](https://user-images.githubusercontent.com/1631264/76165854-16192c00-6139-11ea-8a4b-ee3a2e47c81e.png)

Stacktrace 1:
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/util/LongArray;->get(I)J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:113)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:151)
	at io.flutter.view.g.onAttachedToWindow(Unknown Source:51)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1764)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Stacktrace 2:
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:13)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:151)
	at io.flutter.view.g.onAttachedToWindow(Unknown Source:51)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1764)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Stacktrace 3:
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredField(Native Method)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:92)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:151)
	at io.flutter.view.g.onAttachedToWindow(Unknown Source:51)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1764)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Stacktrace 4:
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:28)
	at io.flutter.view.AccessibilityViewEmbedder$b.<init>(Unknown Source:0)
	at io.flutter.view.AccessibilityViewEmbedder.<init>(Unknown Source:6)
	at io.flutter.view.c.<init>(Unknown Source:151)
	at io.flutter.view.g.onAttachedToWindow(Unknown Source:51)
	at android.view.View.dispatchAttachedToWindow(View.java:18347)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1764)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

As @TahaTesser asked, I ran `flutter doctor -v`:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [VersiÃ³n 10.0.18362.476], locale es-AR)
    • Flutter version 1.12.13+hotfix.8 at C:\Flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Sanuzzi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.5
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7402

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (1 available)
    • SM A505G • R28M70Q97LH • android-arm64 • Android 9 (API 28)

• No issues found!
```

And my pubspec:
```
environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.0
  google_sign_in: ^4.1.1
  cupertino_icons: ^0.1.2
  uuid: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

From [this comment](https://github.com/flutter/flutter/issues/36915#issuecomment-525668810), I understand that it may not affect the users, but it would be great to have a clean lauch that guarantees it.

**Comment by jonahwilliams** [comment] 2020-03-08 16:29
Please don't intentionally file duplicate issues. 

Closing as duplicate of https://github.com/flutter/flutter/issues/36915

**Closed by jonahwilliams** 2020-03-08 16:29 UTC

**Comment by sanuzzi** [comment] 2020-03-09 23:33
They closed the previous issue and ask for submit new ones if the problem still happens. 
Now both are closed. Can you reopen the original one at least? Thank you
