### ISSUE TITLE
 a lot of TapGestureRecognizer cause scroll lag in IOS

### ISSUE THREAD

**Issue by pndaza** [flutter/flutter#123322] opened 2023-03-23 10:48 UTC
## Details
I am utilizing the TapGestureRecognizer and OnTap callback to retrieve the clicked word in a list of Text widgets. While scrolling is smooth on other platforms, there is a lag when scrolling on iOS.

**Target Platform:** IOS
**Flutter Version:** Flutter 3.7.7 stable

## Logs

<details>
<summary>Code sample</summary>

``` dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const WordsView(),
    );
  }
}

const text = '''
Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. 
It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
''';

class WordsView extends StatelessWidget {
  const WordsView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: ListView.builder(
              itemCount: 50,
              itemBuilder: (context, index) {
                return WordClickableText(
                    text: text,
                    onTap: (text) {
                      debugPrint('$text is tapped');
                    });
              }),
        ));
  }
}

class WordClickableText extends StatelessWidget {
  const WordClickableText({
    super.key,
    required this.text,
    this.style,
    this.onTap,
  });

  final String text;
  final TextStyle? style;
  final ValueChanged<String>? onTap;

  @override
  Widget build(BuildContext context) {
    return Text.rich(TextSpan(children: _getTextSpans(text)));
  }

  List<TextSpan> _getTextSpans(String text) {
    final spans = <TextSpan>[];
    final words = text.split(' ');
    for (final word in words) {
      spans.add(TextSpan(
        text: word,
        style: style,
        recognizer: TapGestureRecognizer()
          ..onTap = () {
            onTap?.call(word);
          },
      ));
      spans.add(TextSpan(
        text: ' ',
        style: style,
      ));
    }
    return spans;
  }
}
```

</details>

https://user-images.githubusercontent.com/37981688/227179859-9bbadd00-de0b-4d49-b7f5-058fa435bc00.mp4

**Comment by huycozy** [comment] 2023-03-23 12:32
It looks like the issue only happens on specific devices. I can scroll smoothly and see the tapped text on the output log as well. 

- iPhone 7, iOS 15.7.2 (physical device) ✅
- iPhone 14 Pro, iOS 16.1 (emulator) ✅
- iPad Air 5th generation, iOS 16.1 (emulator) ❌

✅: No Issue ❌: Issue reproduced

Do you have a such physical device (iPad Air 5th generation)? (Since the performance issue should be reproduced on profile/release mode and physical device)

**Comment by huycozy** [comment] 2023-03-24 05:26
Thanks for your response. But the performance issue should be reproducible in the physical device in profile mode with Skia tracing enabled (see https://github.com/flutter/flutter/issues/74833#issue-795394794 and https://github.com/flutter/flutter/issues/122807#issuecomment-1472451339) so that we may see slow frame/janks/etc and also investigate it better. 
So I would suggest you keep an eye on the physical device and observe it to see if it can be reproducible. If you are unable to see it, feel free to close it and write a comment when you can reproduce it on such a device. Thanks!

**Comment by bksubhuti** [comment] 2023-03-25 13:35
It is broken in ios 16 (or mostly) but not lower versions.
related issue was filed on the HtmlWidget but later found to be an issue on flutter framework without the widget.
Sample app is there as well if needed but uses html widget
https://github.com/daohoangson/flutter_widget_from_html/issues/875

**Comment by bksubhuti** [comment] 2023-04-05 02:44
I was able to know that one iPad Air, 3 iOS version 6.2 was fine and did not reproduce this bug.
The person who had this working software without the bug rarely updates and might have been on a pre 3.7 build.  I'm not sure if this helps.

**Closed** 2023-04-18 10:09 UTC
Labels: waiting for customer response, in triage

**Comment by bksubhuti** [comment] 2023-04-25 06:43
how can we re-open this issue and please give response as to what information you want.  Non of the devs have an Ipad.. but I can open a testing channel for someone out there to test.  Our app is not so very small.  We have 1,800 users on android alone.  We ship on MacOS and Windows and of course ios.  To make this work we disabled a major feature.  We have a vanilla app we can send you.  Would that be okay?  Then you the flutter devs can figure this out.  It is independent of outside widgets and fails on only 9 list items containing 1 page of text each.  It is not unreasonable to have each word as a gesture.
