### ISSUE TITLE
30 fps when tapping a button in Cards demo of Gallery

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#6239] opened 2016-10-06 22:43 UTC
On a Moto G4, in release mode, we're seeing 30 fps when tapping on the SHARE and EXPLORE buttons in the Card demo of the Gallery.

Not sure what we should expect here, but since barely nothing is changing on the screen when we tap these buttons, surprised to see 30 fps.

![screenshot_20161006-154047](https://cloud.githubusercontent.com/assets/5479/19173311/8d7bb39e-8bdb-11e6-844d-712a319fc8f3.png)

**Comment by eseidelGoogle** [comment] 2017-02-08 22:12
Looks like the gpu is being overloaded.  Likely shadows or tiling related.  There were just a bunch of changes this week with regards to upload tiling, which may have improved this.  Jason is also working on moving us to a faster shadow path in Skia.  We should check this bug again in a couple weeks and it's likely to be improved.

**Comment by eseidelGoogle** [comment] 2017-02-08 22:13
FYI @chinmaygarde @jason-simmons (no action necessary, just likely that your current fixes may have affect here).  Seth has a Moto G4 on his desk.

**Comment by zoechi** [comment] 2018-12-04 14:52
Is this issue still relevant?

**Comment by guidezpl** [comment] 2022-04-13 12:23
Closing as not reproducible. If you disagree, please file an issue at https://github.com/flutter/gallery.

**Closed by guidezpl** 2022-04-13 12:23 UTC
Labels: framework, engine, severe: performance, team: gallery, passed first triage, P4
