### ISSUE TITLE
Flakiness in rollers trying to set up environment

### ISSUE THREAD

**Issue by flar** [flutter/flutter#136923] opened 2023-10-19 21:25 UTC
The following rolls failed due to some missing files that failed to populate. This looks to be an intermittent issue.

Failed Skia roll: https://github.com/flutter/engine/pull/47108
Failed Fuchsia roll: https://github.com/flutter/engine/pull/47109

**Comment by godofredoc** [comment] 2023-10-19 21:29
This was caused by the false assumption that local are always complete and that they reliably include the vs_toolchain configuration file.

**Comment by godofredoc** [comment] 2023-10-19 21:29
Fix: https://flutter-review.googlesource.com/c/recipes/+/51662

**Comment by godofredoc** [comment] 2023-10-19 22:15
Change has landed and builds should now be working as expected.

**Closed by godofredoc** 2023-10-19 22:15 UTC
Labels: team-infra
