### ISSUE TITLE
Asset images are not loading (with Internet Download Manager installed on Microsoft Windows)

### ISSUE THREAD

**Issue by mhbdev** [flutter/flutter#124883] opened 2023-04-14 19:28 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a simple flutter project (Which supports web)
2. Just create an Image widget and load a png image from your assets
3. Run your application on chrome

### Expected results

I expected flutter to render my asset image normally.

### Actual results

Since I have been upgraded to the latest flutter version which is 3.10.0-6.0.pre.9 on master channel I am confronting this issue. First of all my asset images are not loading anywhere in the application.
This is a little bit odd but it might be helpful. When application runs and renders an Image widget which is loading from assets, my IDM application download dialog pops up and asks to download AssetManifest.bin.

**Note**: All assets images were loading in flutter v3.7.x and my images are not corrupted.

Here is the picture 
![image](https://user-images.githubusercontent.com/53684884/232137606-67f6eb53-62c4-47f5-84cb-3d9e6881a40e.png)

**Note**: I have IDM installed on my system all the time and this problem is happening after upgrading flutter to the latest version on master channel.

### Code sample

<details><summary>Code sample</summary>

```yaml
flutter:
  assets:
    - assets/images/logo.png
```

```dart
Image.asset('assets/images/logo.png', width: 85, height: 85, )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://user-images.githubusercontent.com/53684884/232136840-5cfcd597-f7c7-479f-a96d-19890bca7ece.png)

</details>

### Logs

<details><summary>Logs</summary>

```console
The following FormatException was thrown while resolving an image:
Message corrupted

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49  throw_
packages/flutter/src/services/message_codecs.dart 475:7                       readValue
packages/flutter/src/services/message_codecs.dart 342:28                      decodeMessage
packages/flutter/src/services/asset_manifest.dart 57:55                       fromStandardMessageCodecMessage
packages/flutter/src/services/asset_manifest.dart 59:3                        _#fromStandardMessageCodecMessage#tearOff
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 784:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 584:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 657:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15           <fn>
Image provider: ScrollAwareImageProvider<Object>()
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#97f8e(), devicePixelRatio: 1.0, locale: en_US, textDirection: TextDirection.ltr, size: Size(135.0, 135.0), platform: windows)
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel master, 3.10.0-6.0.pre.9, on Microsoft Windows [Version 10.0.19045.2846], locale en-US)
    • Flutter version 3.10.0-6.0.pre.9 on channel master at C:\FlutterSdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 119744a63c (2 hours ago), 2023-04-14 10:43:17 -0700
    • Engine revision ea0e1b1700
    • Dart version 3.1.0 (build 3.1.0-4.0.dev)
    • DevTools version 2.23.1
    • Pub download mirror https://pub.dev

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\AndroidSdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.0)
    • VS Code at C:\Users\MonoBit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2846]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.49
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.39

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by mhbdev** [comment] 2023-04-14 19:40
I Prevented IDM from capturing links on chrome browser and the problem is solved. But I cannot tell my users to deactivate this feature on their IDM. Is there any explanation for this event? This problem is revealed in this version.

**Comment by huycozy** [comment] 2023-04-17 06:06
I also see this issue after installing IDM again (my IDM license has expired already so the download popup won't display but still can see the same issue with stack trace).

>I Prevented IDM from capturing links on chrome browser and the problem is solved.

Can you share how to do this? (I can not figure out this as my IDM has expired).

Also, on the latest stable channel (`3.7.11`), there is no issue but the image can not display (only a white screen there). Do you see the same result?

**Comment by mhbdev** [comment] 2023-04-21 15:09
> > I also see this issue after installing IDM again (my IDM license has expired already so the download popup won't display but still can see the same issue with stack trace).
> > > I Prevented IDM from capturing links on chrome browser and the problem is solved.
> > 
> > 
> > Can you share how to do this? (I can not figure out this as my IDM has expired).
> > Also, on the latest stable channel (`3.7.11`), there is no issue but the image can not display (only a white screen there). Do you see the same result?
> 
> This will help but as I said we cannot ask our users to disable this feature on their IDM.
> 
> ![image](https://user-images.githubusercontent.com/53684884/232488015-40f38e8e-31d0-41ee-b1dc-98e0ff5b4743.png) ![image](https://user-images.githubusercontent.com/53684884/232488135-5ee4ca30-28ae-4105-b4b9-62f2bd25c744.png)
> 
> I am using flutter master channel. I am trying to move back to stable channel. I will share the result further on.

I have tried to reproduce the issue on flutter stable channel version 3.7.11 and the problem does not exist there. I think this has something to do with Images codec decoding.

<details>
<summary>`flutter doctor -v`</summary>
[√] Flutter (Channel stable, 3.7.11, on Microsoft Windows [Version 10.0.19045.2846], locale en-US)
    • Flutter version 3.7.11 on channel stable at C:\FlutterStable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (10 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • Pub download mirror https://pub.dev

[√] Windows Version (Installed version of Windows is version 10 or higher)

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\AndroidSdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.0)
    • VS Code at C:\Users\MonoBit\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2846]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

**Comment by huycozy** [comment] 2023-04-24 03:35
Thanks for your update. Labeling the issue for further insights! 

I also only see the issue on the master channel but it works well on the latest stable `3.7.12`. The issue happens after IDM is started on the system. The crash log is the same as above.
- master `3.10.0-12.0.pre.29`: ❌
- stable `3.7.12`: ✅

✅: No Issue ❌: Issue reproduced

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.19045.2846], locale en-US)
    • Flutter version 3.7.12 on channel stable at C:\WIP\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (6 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2846]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.10.0-12.0.pre.29, on Microsoft Windows [Version 10.0.19045.2846], locale en-US)
    • Flutter version 3.10.0-12.0.pre.29 on channel master at C:\WIP\flutter_master
    ! Warning: `flutter` on your path resolves to C:\WIP\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at
      C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\WIP\flutter\bin\dart, which is not inside your current Flutter SDK checkout at
      C:\WIP\flutter_master. Consider adding C:\WIP\flutter_master\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 60077ff979 (16 hours ago), 2023-04-23 07:09:16 -0400
    • Engine revision fcf46af2d3
    • Dart version 3.1.0 (build 3.1.0-35.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio Electric Eel 2022.1.1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
    • Visual Studio at D:\DOWNLOADWORK\VS2022
    • Visual Studio Community 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio Electric Eel 2022.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\ADMIN\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2846]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.54

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by yjbanov** [comment] 2023-04-24 04:18
cc @andrewkolos

**Comment by yjbanov** [comment] 2023-04-24 04:23
The fact that it's a message decoding error makes me think that the server might be responding with incorrect manifest file. What does the browser's "Network" tab show?

**Comment by huycozy** [comment] 2023-04-24 04:34
@yjbanov I see `AssetManifest.bin` has code `204 Intercepted by the IDM Advanced Integration`. 

<img width="600" src="https://user-images.githubusercontent.com/104349824/233900553-4fd27c4b-59bf-4590-821a-24481dd0dca7.PNG">

I attach the exported `.har` file here: [har file.zip](https://github.com/flutter/flutter/files/11306594/har.file.zip)

**Comment by biggs0125** [comment] 2023-04-24 15:43
This seems like an issue for the Flutter framework itself rather than for Dart. Removing the `dependency: dart` label. If you think this is wrong please add it back with a justification.

**Comment by andrewkolos** [comment] 2023-04-28 06:09
`AssetManifest.bin` is a special file that is generated on build. When the framework performs its first asset load (your image in this case), it first loads this file. I can only wonder why IDM intercepts this request. Nonetheless, this seems like a bug with IDM.

Before the [introduction ](https://github.com/flutter/flutter/pull/122505)of `AssetManifest.bin`, we generated and loaded a functionally-identical file called `AssetManifest.json`.

To test if the new extension might be the issue, I made a simple flutter app that loads a single image. In the code of my local flutter install, I renamed all references to `AssetManifest.bin` to `AssetManifest.foo`, cleaned the flutter cache, and ran my local repro again. It worked without a problem.

**Comment by andrewkolos** [comment] 2023-05-02 20:47
I'll go ahead and change the file extension of `AssetManifest.bin` to hopefully resolve this issue, though it might take a few days since this will involve some changes to g3.

**Comment by anmol-me** [comment] 2023-05-11 07:40
Even with the release of Flutter 3.10.0 and Dart 3.0.0 on stable channels, the issue still persists.

**Comment by eerive** [comment] 2023-05-11 12:39
It also happens when I'm executing unit tests with test that use a TestAssetBundle, i.e.
```
 home: DefaultAssetBundle(
        bundle: TestAssetBundle(),
        child: Material(
          child: child,
        ),
      ),

```
The TestAssetBundle returns a `await rootBundle.load("assets/fallback.png");` on load, which seems to be corrupted for some reason. 
When building our app, it doesn't break nor show any errors - it only happens when it tries to load our fallback image for testing purposes.

Log: 
```
The following FormatException was thrown while resolving an image:
Message corrupted

When the exception was thrown, this was the stack:
#0      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:533:16)
#1      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478:12)
#2      StandardMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:342:28)
#3      new _AssetManifestBin.fromStandardMessageCodecMessage (package:flutter/src/services/asset_manifest.dart:57:55)
<asynchronous suspension>
<asynchronous suspension>
(elided 6 frames from dart:async and package:stack_trace)

Image provider: ScrollAwareImageProvider<Object>()
Image configuration: ImageConfiguration(bundle: TestAssetBundle#ebf47(), devicePixelRatio: 3.0,
  locale: en_US, textDirection: TextDirection.ltr, platform: android)
```

Flutter doc:
```
Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (2 days ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1
```

**Comment by spkersten** [comment] 2023-05-11 16:21
We're also seeing many failing tests of UI in our repo after upgraden to Flutter 2.10 with
```
The following FormatException was thrown while resolving an image:
Message corrupted
#0      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:475:7)
#1      StandardMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:342:28)
#2      new _AssetManifestBin.fromStandardMessageCodecMessage (package:flutter/src/services/asset_manifest.dart:57:55)
#3      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:39)
#4      CachingAssetBundle.loadStructuredBinaryData (package:flutter/src/services/asset_bundle.dart:273:8)
#5      AssetManifest.loadFromAssetBundle (package:flutter/src/services/asset_manifest.dart:19:19)
#6      AssetImage.obtainKey (package:flutter/src/painting/image_resolution.dart:284:19)
#7      ScrollAwareImageProvider.obtainKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:118:74)
```
(on macOS)

**Comment by BrockMekonnen** [comment] 2023-05-11 17:23
Changing the file extension seems to fix the IDM problem but the asset is not being loaded

**Comment by andrewkolos** [comment] 2023-05-11 17:58
> It also happens when I'm executing unit tests that use a DefaultAssetBundle, ...

@eerive @spkersten, this seems like a separate issue (though it is related to same change that caused this one). I would be happy to investigate further, but this should be filed as as a new issue (ideally with a reproducible example).

**Comment by eerive** [comment] 2023-05-11 22:53
@andrewkolos Created a separate issue: #126612

**Comment by mateendev3** [comment] 2023-05-13 10:26
Any solution I'm still facing this issue. I just updated my Flutter SDK to 3.10.0, This error suddenly appears.

`The following FormatException was thrown while resolving an image:
Message corrupted
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49  throw_
packages/flutter/src/services/message_codecs.dart 475:7                       readValue
packages/flutter/src/services/message_codecs.dart 342:28                      decodeMessage
packages/flutter/src/services/asset_manifest.dart 57:55                       fromStandardMessageCodecMessage
packages/flutter/src/services/asset_manifest.dart 59:3                        _#fromStandardMessageCodecMessage#tearOff
dart-sdk/lib/async/zone.dart 1661:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 784:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 584:5                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 657:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15           <fn>
Image provider: ScrollAwareImageProvider<Object>()
Image configuration: ImageConfiguration(bundle: PlatformAssetBundle#ff931(), devicePixelRatio: 1.3,
  locale: en_US, textDirection: TextDirection.ltr, platform: windows)`

**Comment by andrewkolos** [comment] 2023-05-15 15:52
Filed cherry-pick to get this into the stable release: https://github.com/flutter/flutter/issues/126839

**Comment by anmol-me** [comment] 2023-05-19 04:00
Flutter 3.10.1 fixes the issue.

[flutter/124883](https://github.com/flutter/flutter/issues/124883) - Fixes an issue where images do not render on Flutter web apps when the host machine has Internet Download Manager installed.

**Comment by garrettlove8** [comment] 2023-05-21 15:57
This issue exists for me when running tests. I have upgraded Flutter to latest version on stable channel.

```
Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d3d8effc68 (5 days ago) • 2023-05-16 17:59:05 -0700
Engine • revision b4fb11214d
Tools • Dart 3.0.1 • DevTools 2.23.1
```

**Comment by andrewkolos** [comment] 2023-05-21 20:53
@garrettlove8 Do you have Internet Download Manager installed? If so, the issue shouldn't be limited to tests. If not, then your issue is not related to this one. Either way, feel free to open a new issue.

**Comment by garrettlove8** [comment] 2023-05-21 23:02
@andrewkolos Thanks for the quick response. I'm on a Mac and it looks like IDMs are a Windows thing, is that correct? Perhaps this is a different issue since running the app in simulator and on real device works as expected. I will open a new issue, thanks.

**Comment by garrettlove8** [comment] 2023-05-21 23:35
Issue created #127297

**Comment by andrewkolos** [comment] 2023-06-12 19:15
I am reopening and unlocking this issue, because it is likely to reappear in an upcoming patch. This is because https://github.com/flutter/flutter/pull/128621 landed, which will effectively revert the fix for this. See https://github.com/flutter/flutter/issues/128456 for an explanation as to why the fix was reverted.

To re-summarize this issue, Internet Download Manager (IDM), by default, intercepts any requests the browser makes for certain file types (which includes `.bin`). See ["File Types tab" in the IDM Options Dialog support page](https://www.internetdownloadmanager.com/support/options.html).  This intercepts flutter's request for the asset manifest file, which is needed to load assets. 

The prior-mentioned issue [has some discussion](https://github.com/flutter/flutter/issues/128456#issuecomment-1583218046) as to how we could better prevent issues such as this one. However, I don't see such a significant change coming until at least the next minor version of flutter.

**Comment by Void-0x32** [comment] 2023-07-07 12:45
> I Prevented IDM from capturing links on chrome browser and the problem is solved. But I cannot tell my users to deactivate this feature on their IDM. Is there any explanation for this event? This problem is revealed in this version.

surprised how deactivating IDM worked for me too, but can someone please explain why it is so?

**Comment by Zeinab-Kouhkan** [comment] 2023-07-08 11:48
When I upload the web release to the server not localhost, it does not get the error and IDM does not download the AssetManifest.bin file and it is resolved.
I think it's related to server setting.

**Comment by Vladeouz** [comment] 2023-07-12 01:59
Well, i tried to remove the "BIN" file types from IDM's settings, and it works well.
![Screenshot 2023-07-12 085507](https://github.com/flutter/flutter/assets/89472314/3958e576-c62c-40b8-a734-52d5bb845f47)

**Comment by Ajee139** [comment] 2023-08-10 11:12
> I am reopening and unlocking this issue, because it is likely to reappear in an upcoming patch. This is because #128621 landed, which will effectively revert the fix for this. See #128456 for an explanation as to why the fix was reverted.
> 
> To re-summarize this issue, Internet Download Manager (IDM), by default, intercepts any requests the browser makes for certain file types (which includes `.bin`). See ["File Types tab" in the IDM Options Dialog support page](https://www.internetdownloadmanager.com/support/options.html). This intercepts flutter's request for the asset manifest file, which is needed to load assets.
> 
> The prior-mentioned issue [has some discussion](https://github.com/flutter/flutter/issues/128456#issuecomment-1583218046) as to how we could better prevent issues such as this one. However, I don't see such a significant change coming until at least the next minor version of flutter.

Like he said, IDM is configured to grab downloads for certain files. I had this same issue. To fix, just go to file types in IDM and delete the BIN option. After this, rerun or reload your flutter app.

**Comment by fakhravari** [comment] 2023-08-12 19:11
I have this problem too

√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22000.2124], locale en-US)
    • Flutter version 3.10.6 on channel stable
    • Framework revision f468f3366c ![Uploading Screenshot 2023-08-12 212721.png…]()
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1


![Uploading Screenshot 2023-08-12 212721.png…]()

**Comment by Ajee139** [comment] 2023-09-14 21:26
Good evening to you. Basically, what IDM does is to grab your downloads
immediately they are triggered. It also has specific files types it grabs
and it has a settings where you can add or remove file types. Head to file
types at the top of the settings, highlight the "BIN" file type and delete
it. Now save and close IDM. Now you can launch your Flutter app in peace.
Why the asset images do not load is because IDM grabs the asset.bin file
that Flutter initiates a download for and places them somewhere else. When
you stop it from grabbing the .bin folder, your Flutter app can now
download the asset.bin file into the folder it wants. I hope this helps.

**Comment by fakhravari** [comment] 2023-09-19 06:51
Thank you. Yes, if you manipulate idm, the project will be executed
But the problem is that amateur users do not know that they should do this.
Why doesn't the Flutter engine do this itself?

**Closed** 2023-09-19 22:38 UTC
Labels: c: regression, c: crash, a: assets, platform-web, a: images, has reproducible steps, P2, found in release: 3.10, team-web, triaged-web
