### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by TheEighthDayS** [flutter/flutter#141342] opened 2024-01-11 03:41 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#6      AndroidPlugin._getSupportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:210:53)
#7      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart:158:49)
#8      AndroidPlugin._supportedEmbeddings (package:flutter_tools/src/platform_plugins.dart)
#9      AndroidPlugin.toMap (package:flutter_tools/src/platform_plugins.dart:152:30)
#10     _extractPlatformMaps (package:flutter_tools/src/flutter_plugins.dart:361:40)
#11     _writeAndroidPluginRegistrant (package:flutter_tools/src/flutter_plugins.dart:375:53)
#12     injectPlugins (package:flutter_tools/src/flutter_plugins.dart:1164:11)
<asynchronous suspension>
#13     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:378:5)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1665:7)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
```
```
[✓] Flutter (Channel stable, 3.16.6, on Microsoft Windows [版本 10.0.22621.3007], locale zh-CN)
    • Flutter version 3.16.6 on channel stable at D:\Flutter\flutter_windows_3.16.6-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46787ee49c (29 hours ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • Pub download mirror https://mirrors.cloud.tencent.com/dart-pub
    • Flutter download mirror https://mirrors.cloud.tencent.com/flutter

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\A-AndioidSDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:/A-AndioidSDK
    • Java binary at: D:\Program Files\AdNew\jbr\bin\java
    • Java version Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.8.3)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.8.34330.188
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.1)
    • Android Studio at D:\Program Files\AdNew
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)

[✓] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.2
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.13135.65

[✓] Connected device (3 available)
    • HD1910 (mobile)   • emulator-5554 • android-x86    • Android 5.1.1 (API 22)
    • Windows (desktop) • windows       • windows-x64    • Microsoft Windows [版本 10.0.22621.3007]
    • Edge (web)        • edge          • web-javascript • Microsoft Edge 120.0.2210.91

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: ffccd96b62ee8cec7740dab303538c5fc26ac543
### Plugins
fluttertoast-8.2.4
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2

**Comment by dam-ease** [comment] 2024-01-11 07:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021.

**Closed by dam-ease** 2024-01-11 07:55 UTC
Labels: in triage
