### ISSUE TITLE
showDateRangePicker crashes due to "No MaterialLocalizations found" but MaterialLocalizations are added

### ISSUE THREAD

**Issue by JGeek00** [flutter/flutter#136200] opened 2023-10-09 13:44 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

0. Use Flutter web. I don't know if the same issue happens on other platforms.
1. Use the ``MaterialApp.router`` instead of the normal ``MaterialApp`` (i'm using go_router on the app)
2. This is the delegates list that I have
```
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            DefaultMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            AppLocalizations.delegate
          ],
```
3. Trigger a Date Picker with ``showDateRangePicker``. I'm triggering it from a button that's on a Dialog.
4. I have this error: ``No MaterialLocalizations found. DateRangePickerDialog widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.``

If I add a Localizations widget with it's delegates over the IconButton that triggers the showDateRangePicker (check code below) it's the same result.

### Expected results

The dialog has to open successfully and the app shouldn't crash.

### Actual results

![image](https://github.com/flutter/flutter/assets/47545344/51ecf532-75f3-4ea5-98af-890fbfc710b4)

### Code sample

<details><summary>Code sample</summary>

**main.dart**
```dart
 MaterialApp.router(
          title: 'App',
          theme: lightDynamic != null
              ? lightThemeDynamic(lightDynamic)
              : lightTheme(),
          darkTheme:
              darkDynamic != null ? darkThemeDynamic(darkDynamic) : darkTheme(),
          debugShowCheckedModeBanner: false,
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            DefaultMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
            AppLocalizations.delegate
          ],
          supportedLocales: const [
            Locale("en"),
            Locale("es"),
          ],
          routerConfig: router,
        ),
```

**modal.dart**
```dart
IconButton(
                    onPressed: () => showDateRangePicker(
                      context: context,
                      firstDate: DateTime.now(),
                      lastDate: DateTime(
                        DateTime.now().year + 1,
                        DateTime.now().month,
                        DateTime.now().day,
                      ),
                      locale: Locale(Platform.localeName),
                    ),
                    icon: const Icon(Icons.edit_rounded),
                  )
```

**Same test but adding a Localizations widget**
```dart
Localizations(
                    delegates: [
                      GlobalMaterialLocalizations.delegate,
                      DefaultMaterialLocalizations.delegate,
                    ],
                    locale: Locale(Platform.localeName),
                    child: IconButton(
                      onPressed: () => showDateRangePicker(
                        context: context,
                        firstDate: DateTime.now(),
                        lastDate: DateTime(
                          DateTime.now().year + 1,
                          DateTime.now().month,
                          DateTime.now().day,
                        ),
                        locale: Locale(Platform.localeName),
                      ),
                      icon: const Icon(Icons.edit_rounded),
                    ),
                  )
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.19044.3448], locale es-ES)
    • Flutter version 3.13.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (3 weeks ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\jgilsanz\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.15)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32510.428
    • Windows 10 SDK version 10.0.19041.0
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.83.0)
    • VS Code at C:\Users\jgilsanz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.3448]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.149
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.31

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2023-10-10 07:00
Hi @JGeek00, please provide a complete minimal reproducible code sample instead of code snippets so that we can investigate this issue. 

Thank you

**Comment by JGeek00** [comment] 2023-10-10 11:41
Here you have it:

**main.dart**
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:test/router.dart';
import 'package:url_strategy/url_strategy.dart';

void main() {
  setPathUrlStrategy();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        DefaultMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        DefaultWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        DefaultCupertinoLocalizations.delegate
      ],
      routerConfig: router,
    );
  }
}
```

**router.dart**
```dart
```

**Comment by danagbemava-nc** [comment] 2023-10-11 07:22
Hi @JGeek00, this is an issue with your usage of `Platform.localeName`. `Platform.localeName` returns the locale in this format `xx_yy`, with xx being the language and yy being the country code. The `Locale` object expects the first parameter to be the language but since you're using `Platform.localeName` you end up passing the language and country code all at once so instead of something like `Locale(en, us)` you end up with `Locale(en_us)` which does not end up matching any of the locales that have been defined in material. 

What you should do is check the delimiter/separator that is used by your target platforms and splitting the string before you set your locale value. 

So something like 

`final locale = Locale(Platform.localeName.split("_").first, Platform.localeName.split("_").lastOrNull);` instead of `Locale(Platform.localeName)`.

Please note that on the web, it may be a dash('-') instead of an underscore. 

I'll be closing this since this is an implementation issue. If you still experience this issue after making the required change, kindly leave a comment below and I will reopen this issue. 

Thank you

**Closed by danagbemava-nc** 2023-10-11 07:22 UTC
Labels: in triage
