### ISSUE TITLE
firebase_admob: Program type already present: com.google.android.gms.internal.measurement.zzdz

### ISSUE THREAD

**Issue by davidgalarza** [flutter/flutter#29744] opened 2019-03-21 15:32 UTC
## Steps to Reproduce
When I build my app on release mode

1. I migrate to androidX usign android Studio as describe: https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#how-to-migrate-a-flutter-app-to-androidx
2. My app works like a charm and I try to install firebase_admob
my pubspec.yaml:

`
cloud_firestore: ^0.9.5+2
  firebase_auth: ^0.8.1+4
  google_sign_in: ^4.0.1+1
  flutter_svg: ^0.12.0
  flutter_facebook_login: ^2.0.0
  modal_progress_hud: ^0.1.2
  percent_indicator: ^1.0.14
  flutter_tts: ^0.2.4
  audioplayer2:
  path_provider: ^0.5.0+1
  firebase_analytics: ^2.0.3
  shared_preferences: ^0.5.1+1
  app_review: ^0.1.0
  flare_flutter: ^1.3.3
  font_awesome_flutter: ^8.0.1
  timeago: ^2.0.8
  fluro: ^1.3.7
  fluttertoast: ^3.0.3
  highlighter_coachmark: ^0.0.3
  translator: ^0.1.0+5
  firebase_remote_config: ^0.1.0+2
  firebase_admob: ^0.8.0+3
  flutter_swiper: ^1.1.4
  revenuecat: ^1.0.4
  flutter_sequence_animation: ^3.0.1
  badges: ^0.0.6
  diff_match_patch: ^0.3.0
  onesignal: ^1.0.0
  flutter_youtube_view: ^1.1.0
`

3. Now my app does not work either in debug or release mode

## Logs

flutter build apk --release 
```
Note: /Users/davidgalarza/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_admob-0.8.0+3/android/src/main/java/io/flutter/plugins/firebaseadmob/AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
D8: Program type already present: com.google.android.gms.internal.measurement.zzdz
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.google.android.gms.internal.measurement.zzdz
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 12s                                                  
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      73,1s
Gradle task assembleRelease failed with exit code 1
```

flutter analyze
```
Analyzing Sounter...                                                    

   info • Cancel instances of dart.async.StreamSubscription •
          lib/screens/Courses/courses.dart:50:22 • cancel_subscriptions
   info • This class (or a class which this class inherits from) is marked as
          '@immutable', but one or more of its instance fields are not final:
          FirstCourseScreen.isOnBoarded •
          lib/screens/FirstCourse/firstCourse.dart:13:7 • must_be_immutable
   info • The method '_renderLoadingVideo' isn't used •
          lib/screens/Karaoke/karaoke.dart:553:10 • unused_element
   info • Unused import: 'package:sounter/services/authApi.dart' •
          lib/screens/Path3/path.dart:15:8 • unused_import
   info • The method '_logEvent' isn't used •
          lib/screens/Profile/profile.dart:52:16 • unused_element
   info • The value of the field '_isPlaying' isn't used •
          lib/screens/PullRequest/pullRequest.dart:47:8 • unused_field
   info • The value of the field '_playerState' isn't used •
          lib/screens/PullRequest/pullRequest.dart:50:10 • unused_field
   info • The value of the field '_controller' isn't used •
          lib/screens/PullRequest/pullRequest.dart:51:32 • unused_field
   info • The value of the field '_preferences' isn't used •
          lib/screens/SongList/songList.dart:45:21 • unused_field
   info • The method '_showDialog' isn't used • lib/screens/Sync/sync.dart:303:8
          • unused_element
   info • This function has a return type of 'Future<int>', but doesn't end with
          a return statement • lib/services/firestore.dart:85:3 • missing_return

11 issues found. (ran in 10.1s)

```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.5 17F77, locale es-EC)
    • Flutter version 1.2.1 at /Users/davidgalarza/development/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/davidgalarza/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • ANE LX3 • KPS7N18425000775 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by kroikie** [comment] 2019-10-13 18:20
@davidgalarza

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/396. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:48
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment] 2019-10-23 12:32
Hi @davidgalarza
are you still experiencing this issue with the latest version of Flutter and [firebase_admob](https://pub.dev/packages/firebase_admob)?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-14 15:15
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  

Thanks for your contribution.Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-14 15:15 UTC
Labels: p: firebase, p: firebase_admob, plugin, transferred, waiting for customer response
