### ISSUE TITLE
[iOS] AppStore: ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _ptrace.

### ISSUE THREAD

**Issue by Mallika-Tung** [flutter/flutter#46067] opened 2019-12-04 09:36 UTC
ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _ptrace. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/Though you are not required to fix the following issues, we wanted to make you aware of them:ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information. | ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _ptrace. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/Though you are not required to fix the following issues, we wanted to make you aware of them:ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
-- | --
ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/Flutter.framework/Flutter: _ptrace. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/Though you are not required to fix the following issues, we wanted to make you aware of them:ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

i have submitted release build but by default it takes debug build

**Comment by iapicca** [comment] 2019-12-04 12:02
Hi @Mallika-Tung 
does this [workaround ](https://github.com/flutter/flutter/issues/45129#issuecomment-555277635)work for you?
If it doesn't could you please provide 
your updated  `flutter doctor -v`?
Thank you

**Comment by Mallika-Tung** [comment] 2019-12-04 12:44
I have not used UIWebview in the entire project .Even no third party plugin also does not using UIWebview ,still it warning coming.
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs .

**Comment by iapicca** [comment] 2019-12-04 13:02
possible duplicate https://github.com/flutter/flutter/issues/37850

**Comment by jmagman** [comment] 2019-12-04 21:23
Yes, duplicate of https://github.com/flutter/flutter/issues/37850.

**Closed by jmagman** 2019-12-04 21:23 UTC
Labels: t: xcode, tool, ⌺‬ platform-ios
