### ISSUE TITLE
There is no function like JumpTo () or AnimateTo () to scroll with items of different heights.

### ISSUE THREAD

**Issue by oseiasmribeiro** [flutter/flutter#29098] opened 2019-03-09 14:40 UTC
There is no flutter method in the ScrollController, such as JumpTo () or AnimateTo (), to skip the scroll to a particular item, where items have different heights. It's okay if heights are the same.

I want a JumpTo () that can skip from screen A, which shows the result of the search of words in several books, for Screen B that shows the paragraph of the book clicked. See the example in the image:

![pergunta](https://user-images.githubusercontent.com/36827173/54072966-4dbc7200-4260-11e9-9973-f8ed572a71f3.jpg)

Could someone give me a solution?

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.2.0, on Microsoft Windows [versÃ£o 10.0.17134.590], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.32.1)
[√] Connected device (1 available)

• No issues found!

**Comment by dnfield** [comment] 2019-03-09 18:25
Duplicate of https://github.com/flutter/flutter/issues/12319

**Closed by dnfield** 2019-03-09 18:25 UTC

**Comment by oseiasmribeiro** [comment] 2019-03-10 00:26
Sorry to ask for that, but could you give me a way to do this?

**Comment by dnfield** [comment] 2019-03-10 00:32
There is no way currently, but the request is the same as in the linked issue.  Unfortunately it's a hard problem to solve without destroying performance.

**Comment by oseiasmribeiro** [comment] 2019-03-10 00:35
OK thank you!
