### ISSUE TITLE
flutter listView memory performance

### ISSUE THREAD

**Issue by potatoker** [flutter/flutter#29782] opened 2019-03-22 04:05 UTC
I have a simple flutter listView page in my app, And it looks like this:

![image](https://user-images.githubusercontent.com/5286501/54799357-c5928f80-4c97-11e9-8415-8f6a07afb8e8.png)

And the code fragment:

 ```
  Widget _buildSuggestions() {
    return ListView.builder(
        padding: const EdgeInsets.all(16.0),
        itemBuilder: (context, i) {
          if (i.isOdd) return Divider();
          final index = i ~/ 2;
          if (index >= _suggestions.length) {
            _suggestions.addAll(generateWordPairs().take(10));
            return _buildItem(context, i, ObjectKey(index), _suggestions[index%_suggestions.length]);
          }
          return _buildItem(context, i, ObjectKey(index), _suggestions[index]);
        });
  }

```
I inspect the memory consumption of the app in Android studio profiler and flutter performance plugin when scrolling the list. I found that the total memory in AS profiler will increase to a stable value. But the dart heap memory is not stable and even going down sharply. I think the dart vm gc hanppend there. 

total memory increase and then keep stable in AS profiler when keep scrolling
![image](https://user-images.githubusercontent.com/5286501/54799805-b3195580-4c99-11e9-8740-95ccfee662e7.png)

dart vm heap memory shake when keep scrolling
![image](https://user-images.githubusercontent.com/5286501/54799853-f1af1000-4c99-11e9-9d7b-34212924ba5f.png)

Based on these observations. I have some questions about the memory manage mechanism of Flutter ListView.

1. flutter ListView has no "recycler mechanism", so its memory consumption will keep increasing when dart vm gc happen.  Is this statement right?

2. If  the first question's  answer is "yes". why the memory consumption in AS profiler keep increasing and then stop someWhere. And why dart vm memory consumption going down and up in the graph of flutter performance plugin but no such "shaking" in AS profiler.

3. when dart vm heap gc happens, it deallocate the widgets memory. Do the corresponding renderingObjects also be collected? why the gc seemed influence the total memory in As profiler so subtle?

**Comment by potatoker** [comment] 2019-03-22 10:09
I have some more weird observation:
I open the as profiler and the flutter performance plugin to observe the memory change. I scroll the flutter listView, at the same point:

![image](https://user-images.githubusercontent.com/5286501/54815404-dd383b00-4ccc-11e9-9938-e813f2c5e708.png)

![image](https://user-images.githubusercontent.com/5286501/54815513-27212100-4ccd-11e9-9cc8-89e69b194174.png)

in the flutter performance plugin. the memory going down sharply. But there seems subtle change in the AS profiler? which profiler is not correct? so confused about this problem.

**Comment by x4080** [comment] 2019-04-23 07:30
Hi @potatoker,

Do you have 'jank' when scrolling list view in android ? Because in my old devices it will jank while when using native android its very smooth

And I thought that list view builder should recycle the item, I don't know if I'm wrong :)

**Comment by potatoker** [comment] 2019-06-19 12:09
@x4080 yes. list view in flutter absolutely not as smooth as native in old devices, we have the same observation, but it is acceptable.

And listview item in flutter have no recycler mechanism I believe.

**Comment by x4080** [comment] 2019-06-25 09:04
@potatoker thanks for replying

**Comment by fzyzcjy** [comment] 2020-01-19 08:53
Hi, is there any updates -- does it run as smooth as native or still not well? Thanks!

**Comment by pedromassangocode** [comment] 2020-09-18 12:54
Hi @potatoker 
Are you still having this issue? If yes, please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by pedromassangocode** [comment] 2020-10-21 13:36
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-10-21 13:36 UTC
Labels: f: scrolling, framework, severe: performance

**Comment by syfulin** [comment] 2020-10-30 06:16
Thanks for the support. I have a problem with ListView in web application too.

In the desktop browser, the listview works perfectly, but in all mobile browsers the scroll animation looks ugly, as if it twitches.
I've tested this on all iPhones and only the iPhone 12 has perfect scrolling (as in the desktop browser).

Perhaps I need to optimize the listview somehow?

Application:
http://hhhhtyu.000webhostapp.com/test111/

Minimal complete reproducible code:
(main problem code in main.dart)
https://github.com/syfulin/test_listview

flutter doctor -v:
```
PS C:\Users\Alexey\Documents\dev\Flutter\Examples\test_listview_optimize\listview_optimize> flutter doctor -v
[√] Flutter (Channel master, 1.24.0-4.0.pre.138, on Microsoft Windows [Version 10.0.18363.1139], locale ru-RU)
    • Flutter version 1.24.0-4.0.pre.138 at C:\tools\Flutter
    • Framework revision 13896b3bd1 (27 hours ago), 2020-10-28 19:43:19 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Android SDK at C:\Users\Alexey\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\Alexey\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)       • edge       • web-javascript • Microsoft Edge 86.0.622.51

• No issues found!
PS C:\Users\Alexey\Documents\dev\Flutter\Examples\test_listview_optimize\listview_optimize>
```

**Comment by pedromassangocode** [comment] 2020-10-30 10:21
Hi @syfulin 
I recommend you to file a new issue as this one was discontinued.
