### ISSUE TITLE
Error connecting to the service protocol: HttpException

### ISSUE THREAD

**Issue by timtraversy** [flutter/flutter#26811] opened 2019-01-19 20:22 UTC
I'm starting to see this error every time I run my app on iPhone or iPad:

`Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/ws`

This was mentioned at #25112, but that was resolved as a proxy error, and I don't believe my home wi-fi has that.

I've restarted Android Studio, uninstalled and reinstalled the app, and I'm still getting the error.

**Comment by BradHoffman96** [comment] 2019-01-20 05:02
Experiencing the same issue. Tried to upgrade and switch channels, but those did not help. Also deleted the app and restarted VSCode

**Comment by zoechi** [comment] 2019-01-20 12:43
- https://github.com/flutter/flutter/issues/13747#issuecomment-369322275
- https://github.com/flutter/flutter/issues/13747#issuecomment-402802659
- https://github.com/flutter/flutter/issues/13747#issuecomment-451307615
might help

Closing as Duplicate of #13747

**Closed by zoechi** 2019-01-20 12:43 UTC
