### ISSUE TITLE
[Web] Form not working if it's not on screen

### ISSUE THREAD

**Issue by MatteoAntolini** [flutter/flutter#104093] opened 2022-05-18 16:12 UTC
If the `TextFormFiled` is not visible, the functions `onSaved` and `validator` are not called

<details>
<summary>Code sample</summary>

```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final GlobalKey<FormState> _key = GlobalKey<FormState>();

  late String text;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(builder: (context) {
          return Form(
            key: _key,
            child: ListView(
              children: [
                TextFormField(
                  validator: (value) =>
                      value != null && value != "" ? null : "Error",
                  onSaved: (value) {
                    text = value!;
                  },
                ),
                SizedBox(height: 10000),
                MaterialButton(
                  onPressed: () {
                    if (_key.currentState!.validate()) {
                      _key.currentState!.save();
                      ScaffoldMessenger.of(context)
                          .showSnackBar(SnackBar(content: Text(text)));
                    }
                  },
                  child: Text("BUTTON"),
                )
              ],
            ),
          );
        }),
      ),
    );
  }
}
```

</details>

If you remove `SizedBox(height: 10000),` the app works correctly. 

<details>
  <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Versione 10.0.19043.1706], locale it-IT)
    • Flutter version 3.0.0 at C:\Users\Matteo Antolini\Documenti\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (9 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Matteo Antolini\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)    
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\Matteo Antolini\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Versione 10.0.19043.1706] 
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 101.0.1210.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category. 
```

</details>

**Comment by danagbemava-nc** [comment] 2022-05-19 08:56
Hi @MatteoAntolini, this is working as intended. ScrollViews have a `cacheExtent` that determines when items within the list should be drawn. See https://api.flutter.dev/flutter/widgets/ScrollView/cacheExtent.html. 

You can set a custom `cacheExtent` depending on the size of your list that will ensure that your form elements are rendered and your validation will work. 

Alternatively, you can replace the `ListView` with a `Column` and wrap the `Column` with a `SingleChildScrollView`. This way you wouldn't need to try to calculate the `cacheExtent` since `SingleChildScrollView` draws all its children at once. 

I have attached below two code samples that should work the same. One uses a `SingleChildScrollView` with a `Column` and the other uses a `ListView` with a specified `cacheExtent`.

Closing this as this is working as intended.

As a side note: if your form ever becomes too big, it's generally a good idea to break it down into smaller pieces. Filling long forms at once isn't really a good user experience.

<details>
<summary>sample with ListView + cacheExtent</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final GlobalKey<FormState> _key = GlobalKey<FormState>();

  String? text;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(builder: (context) {
          return Form(
            key: _key,
            child: ListView(
              cacheExtent: 100000,
              children: [
                TextFormField(
                  validator: (value) =>
                      value != null && value != "" ? null : "Error",
                  onSaved: (value) {
                    text = value!;
                  },
                ),
                const SizedBox(height: 10000),
                MaterialButton(
                  onPressed: () {
                    if (_key.currentState!.validate()) {
                      _key.currentState!.save();
                      ScaffoldMessenger.of(context)
                          .showSnackBar(SnackBar(content: Text(text!)));
                    }
                  },
                  child: const Text("BUTTON"),
                )
              ],
            ),
          );
        }),
      ),
    );
  }
}

```
</details>

<details>
<summary>Sample using SingleChildScrollView</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final GlobalKey<FormState> _key = GlobalKey<FormState>();

  String? text;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Builder(builder: (context) {
          return Form(
            key: _key,
            child: SingleChildScrollView(
              child: Column(
                children: [
                  TextFormField(
                    validator: (value) =>
                        value != null && value != "" ? null : "Error",
                    onSaved: (value) {
                      text = value!;
                    },
                  ),
                  const SizedBox(height: 10000),
                  MaterialButton(
                    onPressed: () {
                      if (_key.currentState!.validate()) {
                        _key.currentState!.save();
                        ScaffoldMessenger.of(context)
                            .showSnackBar(SnackBar(content: Text(text!)));
                      }
                    },
                    child: const Text("BUTTON"),
                  )
                ],
              ),
            ),
          );
        }),
      ),
    );
  }
}

```
</details>

**Closed by danagbemava-nc** 2022-05-19 08:56 UTC
Labels: in triage
