### ISSUE TITLE
Dart snapshot generator failed with exit code -6

### ISSUE THREAD

**Issue by agiletelescope** [flutter/flutter#21831] opened 2018-09-13 19:48 UTC
I had a Flutter app that was working just fine until today. I realized that `flutter build apk` wasn't building the Flutter app with the latest code. Looked up on the internet. Did a `flutter clean`. Then built the app again with `flutter build apk`. The following is the error I'm getting,
On Beta channel.

===== CRASH =====
```
version=2.1.0-dev.1.0.flutter-ccb16f7282 (Tue Aug 21 22:21:20 2018 +0000) on "linux_simarm"
si_signo=Segmentation fault(11), si_code=1, si_addr=0x4
Dart snapshot generator failed with exit code -6
Snapshotting exited with non-zero exit code: -6
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
39.5s
Built build/app/outputs/apk/release/app-release.apk (4.3MB).
```
Before doing "flutter clean" the app size was 6.5 MB.

On master channel.
===== CRASH =====
```
version=2.1.0-dev.4.0.flutter-05ccfa8502 (Tue Sep 11 09:03:02 2018 +0000) on "linux_simarm"
si_signo=Segmentation fault(11), si_code=1, si_addr=0x5
Dart snapshot generator failed with exit code -6
Snapshotting exited with non-zero exit code: -6

FAILURE: Build failed with an exception.

* Where:
Script '/opt/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 428

* What went wrong:
Execution failed for task ':app:flutterBuildRelease'.
> Process 'command '/opt/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

I then downgraded Flutter. The `flutter build apk` is working just fine.
How do I resolve this issue?.

Flutter Doctor Output:
```
[✓] Flutter (Channel beta, v0.7.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.25.1)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```
Some related content I found regarding this same issue.
[#14891](https://github.com/flutter/flutter/issues/14891), [#21025](https://github.com/flutter/flutter/issues/21025)

Thank you.

**Comment by zoechi** [comment] 2018-09-13 20:04
#21685 might also be related. 
When the mentioned fix is available you can check to know for sure.

**Comment by zoechi** [comment] 2018-09-14 02:59
Waiting until the fixes land in master

**Comment by agiletelescope** [comment] 2018-09-15 21:45
I was able to resolve the issue. The problem was with one of the libraries that I was using to dynamically switch themes. Removed that and included my own code for switching themes and the app is building fine now. [Here's](https://github.com/Norbert515/dynamic_theme) the library I used.

**Comment by sujaybr** [comment] 2018-09-16 08:30
@zoechi Any idea when this issue is going to be fixed?. Was about to release an app but now waiting for this to be resolved. Been struggling with it the past few days. Don't want to downgrade flutter version cause it increases the app size and will have to change significant amount of code.

**Comment by mraleph** [comment] 2018-09-18 17:37
The fix has reached Flutter master channel. Try upgrading now.

**Comment by mraleph** [comment] 2018-09-18 17:37
Duplicate of #21685

**Closed by mraleph** 2018-09-18 17:37 UTC
Labels: dependency: dart, severe: crash, tool

**Comment by agiletelescope** [comment] 2018-09-18 19:13
@mraleph Thanks a lot.
