### ISSUE TITLE
LUCI output on GitHub is garbled

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#126942] opened 2023-05-16 19:11 UTC
Looks like we're dropping newlines or something:
![](https://github.com/flutter/flutter/assets/551196/1b9e5752-381e-418a-8dd6-fc7de4071172)

**Comment by ricardoamador** [comment] 2023-05-16 23:46
Took a very quick look and the output is formatted like this in LUCI. I believe some work was done to clean this up but I will take a closer look tomorrow. Here is an example where you can see the output is formatted this except that some symbols are not rendering properly so this appears to be coming from the LUCI side:

![image](https://github.com/flutter/flutter/assets/32242716/4e99b5cf-d12b-4dbd-835e-b41c458e8b7f)

**Comment by ricardoamador** [comment] 2023-05-17 23:30
Closing as duplicate of https://github.com/flutter/flutter/issues/117099.

**Closed by ricardoamador** 2023-05-17 23:30 UTC
Labels: team: infra
