### ISSUE TITLE
Web: UnimplementedError was thrown

### ISSUE THREAD

**Issue by alexfanchina** [flutter/flutter#48259] opened 2020-01-06 20:20 UTC
I'm adding Flutter web to an existing project. I using Flutter `dev` branch and there's this error thrown; tried `master` branch, same error. The UI in browser is all blank other than the "debug" banner where it's supposed to be other stuff: 

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following UnimplementedError was thrown during paint():
UnimplementedError

The relevant error-causing widget was:
RawPicture org-dartlang-app:///packages/flutter_svg/svg.dart:729:22

When the exception was thrown, this was the stack:
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
package:build_web_compilers/lib/ui/src/ui/canvas.dart 892:5                           drawPicture
package:flutter_svg/src/render_picture.dart 193:12                                    paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                                   paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                                   paint
package:flutter/src/rendering/object.dart 542:14                                      pushTransform
package:flutter/src/rendering/proxy_box.dart 2338:21                                  [_paintChildWithTransform]
package:flutter/src/rendering/proxy_box.dart 2355:17                                  paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                                   paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                                   paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                                   paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/shifted_box.dart 70:14                                  paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/box.dart 2508:14                                        defaultPaint
package:flutter/src/rendering/custom_layout.dart 396:5                                paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                                   paint
package:flutter/src/material/material.dart 530:11                                     paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                                   paint
package:flutter/src/rendering/object.dart 384:12                                      pushLayer
package:flutter/src/rendering/proxy_box.dart 1755:14                                  paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                                   paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 184:12                                      paintChild
package:flutter/src/rendering/proxy_box.dart 123:14                                   paint
package:flutter/src/rendering/object.dart 2219:7                                      [_paintWithContext]
package:flutter/src/rendering/object.dart 135:10                                      _repaintCompositedChild
package:flutter/src/rendering/object.dart 95:5                                        repaintCompositedChild
package:flutter/src/rendering/object.dart 937:29                                      flushPaint
package:flutter/src/rendering/binding.dart 346:19                                     drawFrame
package:flutter/src/widgets/binding.dart 774:13                                       drawFrame
package:flutter/src/rendering/binding.dart 283:5                                      [_handlePersistentFrameCallback]
package:flutter/src/scheduler/binding.dart 1102:15                                    [_invokeFrameCallback]
package:flutter/src/scheduler/binding.dart 1041:9                                     handleDrawFrame
package:flutter/src/scheduler/binding.dart 957:5                                      [_handleDrawFrame]
package:build_web_compilers/lib/_engine/engine.dart 180:21                            <fn>

The following RenderObject was being processed when the exception was fired: RenderPicture#935d0:
creator: RawPicture ← SizedBox ← FittedBox ← SizedBox ← Semantics ← SvgPicture ← ConstrainedBox ←
Container ← Center ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← ⋯
parentData: <none> (can use size)
constraints: BoxConstraints(w=112.0, h=112.0)
size: Size(112.0, 112.0)
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by egorbelibov** [comment] 2020-01-07 00:07
+1 Here (on channel **master**).  @dnfield Can you have a look at this?
![Network Preview of local asset](https://drive.google.com/uc?export=view&id=10x7dhI1Arri4YsAN8lz-QCzD07NzImOR)

Issue caused by the `flutter_svg` library upon rendering an SVG asset.

**Comment by dnfield** [comment] 2020-01-07 00:17
flutter_svg does not support web yet.  That is being tracked at https://github.com/dnfield/flutter_svg/issues/173

There are many unimplemented methods in Flutter for web at this point - I'm not sure this issue is all that helpful to leave open.  Closing in favor of the flutter_svg bug

**Closed by dnfield** 2020-01-07 00:17 UTC

**Comment by fathah** [comment] 2020-09-22 04:40
But how can we know, which library is spitting this error? So we can do further actions.
