### ISSUE TITLE
Widget inspector stopped working after update

### ISSUE THREAD

**Issue by diamond95** [flutter/flutter#73024] opened 2020-12-28 08:43 UTC
## Steps to Reproduce

1. I've created new application yesterday, and flutter devTools automatically updated, and now when I open devTools widget inspector, it does not work, blank page shown in visual studio code.

## Logs

```
C:\Users\iMiljanic\Desktop\vinkovci>flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale hr-HR)
    • Flutter version 1.22.5 at C:\flutter
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\iMiljanic\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\iMiljanic\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • SM A405FN (mobile) • R58N12CL0HN • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

If I open in browser, it still shows blank page with some console errors.

**Comment by pedromassangocode** [comment] 2020-12-28 11:29
Hi @diamond95  
Can you please provide the steps to reproduce the issue along with the actual vs expected behavior?
Thank you

**Comment by diamond95** [comment] 2020-12-28 15:57
Hi @pedromassango,
when I run my project on device, I tried 50x times to open Widget inspector, to check some styling on device, but It's "running" and blank page is shown. 

Before update everything was perfect. 
**Now it looks like this:** 
https://i.gyazo.com/1597b9294763ca1a081aa9e3c4ae0f6f.mp4

**It should be like this:** https://user-images.githubusercontent.com/6405390/95697404-33831b00-0c71-11eb-800c-3fb7223f38cc.png

I tried to open devTool in browser, nothing happens, blank page.. ( http://127.0.0.1:9100/#?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A62882%2F1krUCxxv7D4%3D%2F )  with some console errors; https://gyazo.com/de33d0b6283fb8ce1a42ea8fc1c4bd6e

Let me know If I can provide more details somehow. 
Ivan

**Comment by diamond95** [comment] 2020-12-28 22:24
Update: 5 mins ago I started project again, and devTools again was updating, and this dialog pop up: 
![image](https://user-images.githubusercontent.com/17730752/103246414-a1cba580-4963-11eb-960f-8c11f3d131c7.png)
I pressed "allways open", but still Widget Inspector is blank.

**Comment by pedromassangocode** [comment] 2020-12-29 08:05
Hi @diamond95 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).

I have found a similar issue there, see https://github.com/Dart-Code/Dart-Code/issues/3024

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-12-29 08:05 UTC
Labels: in triage
