### ISSUE TITLE
FirebaseDatabase plugin gets ints as ints, loads them from persistence as double on iOS

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#10825] opened 2017-06-19 14:39 UTC
## Steps to Reproduce

- Use FirebaseDatabase in a project, 0.0.7 is the version I'm using
- call `setPersistenceEnabled(true)`
- Get some node data with an int in it, parse the value out and assign it to an int, doesn't throw error.
- Put on the networklinkconditioner to drop 100%, since airplane mode will crash the app
- The data that is loaded and persisted will be loaded as a double, when it's an int, and will throw an exception

## Flutter Doctor
[✓] Flutter (on Mac OS X 10.12.4 16E195, locale en-US, channel master)
    • Flutter at /Users/KG/Developer/Flutter/flutter
    • Framework revision 6965312822 (2 days ago), 2017-06-16 10:05:18 -0700
    • Engine revision 784e975672
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

**Comment by collinjackson** [comment] 2017-06-19 22:33
I am able to reproduce the automatic conversion of ints to doubles on iOS. It does require calling `keepSynced` on a `Query` but doesn't seem to require putting the device into airplane mode.

**Comment by collinjackson** [comment] 2017-06-20 03:07
I spent some time today investigating this and it does seem to be a interesting behavior coming from the [iOS Firebase persistence database](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Database/Persistence/FLevelDBStorageEngine.m).

Minimal code to reproduce in Objective-C

```
#import "AppDelegate.h"
@import Firebase;
@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [FIRApp configure];
  [[FIRDatabase database] setPersistenceEnabled:YES];
  FIRDatabaseReference *ref = [[FIRDatabase database].reference child:@"counter"];
  [ref keepSynced:YES];
  [ref observeSingleEventOfType:FIRDataEventTypeValue withBlock:^(FIRDataSnapshot * _Nonnull snapshot) {
    NSLog(@"Type of %@ is %d", snapshot.value, (int)CFNumberGetType((CFNumberRef)snapshot.value));
  }];
  [ref setValue:[NSNumber numberWithInt:42]];
  return YES;
}
@end
```

The first time this code runs, the snapshot is an integer NSNumber. The second time, it's an NSDecimalNumber with a CFNumberType of kCFNumberDoubleType. Presumably this is because the persistent store is serializing numbers differently from the cloud Firebase. They probably never noticed because if you call snapshot.value.intValue you'll get the right answer, but in our case we don't know whether the client code is expecting an int or a double, so we return a double.

I can think of a few possible resolutions:

1. Require Flutter developers to explicitly handle this case.
1. Get Firebase to not give us a kCFNumberDoubleType
1. Before we send the results of a query back to Dart-land, detect any NSDecimalNumbers that happen to be integers and convert them to integers.

The last option introduces some performance overhead but is probably the most realistic.

**Comment by eseidelGoogle** [comment] 2017-06-20 03:22
FYI @kroikie (just in case you're curious).

**Comment by mit-mit** [comment] 2017-06-20 12:12
cc @mravn-google

**Comment by collinjackson** [comment] 2017-06-20 16:57
cc @matanlurey

The two key questions for me are:
* Will Dart 2.0 support coercion of ints to doubles, e.g. `1 + 1.0 == 2.0`? If so then we should probably continue using ints and doubles.
* Will the Firebase team eventually fix firebase/firebase-ios-sdk#91? If it's WONTFIX or will take a long time, we should implement a workaround on iOS that converts all round doubles to ints.

**Comment by collinjackson** [comment] 2017-06-20 19:51
I am checking with @floitschG on the first question

I haven't gotten a response yet on firebase/firebase-ios-sdk#91 about a timeline for a fix. After talking to @lukef about this I think we're going to go ahead and just convert round doubles to ints on the native side. We can remove that workaround if it's fixed in a new Firebase release.

**Closed** 2017-06-20 22:45 UTC
Labels: customer blocker, customer: posse (eap), plugin: firebase, waiting for PR to land (fixed), ⌺‬ platform-ios

**Comment by kroikie** [comment] 2019-10-13 19:28
@KevinTheGray

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/992. Any further collaboration will be done there.
