### ISSUE TITLE
Text field cursor position in RTL goes to the penultimate character

### ISSUE THREAD

**Issue by dshpindler** [flutter/flutter#115696] opened 2022-11-19 15:00 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. tap at the end of the text in the textfield (see video)

**Expected results:**
The cursor position should be after the last character.

**Actual results:**
The cursor position moves to the penultimate character.

NOTE: I saw [this issue](https://github.com/flutter/flutter/issues/107006) that was closed due to 'solved on master', however the same issue still exists on master.

In multiline textfield, this will happen only if tapping the end of the last line, or if the next line is blank (just `\n`)

<details>
<summary>Code sample</summary>

can be run in `https://dartpad.dev/`:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: TextField(
          controller: TextEditingController(text: 'שלום שלום'),
          textAlign: TextAlign.right,
        ),
      )
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
➜  test_project flutter analyze
Analyzing test_project...                                               
No issues found! (ran in 1.8s)
```

```
➜  test_project flutter doctor -v
[✓] Flutter (Channel master, 3.6.0-6.0.pre.22, on macOS 12.1 21C52 darwin-x64, locale en-IL)
    • Flutter version 3.6.0-6.0.pre.22 on channel master at /Users/dshpindler/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 633d7ef046 (6 hours ago), 2022-11-19 03:27:24 -0500
    • Engine revision 916fd798de
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dshpindler/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • ANDROID_HOME = /Users/dshpindler/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (4 available)
    • SM A750F (mobile)            • 320085494e1c164b • android-arm64  • Android 10 (API 29)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 12 (API 31) (emulator)
    • macOS (desktop)              • macos            • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
➜  test_project 
```

</details>

https://user-images.githubusercontent.com/30801944/202856381-229d4e7e-049c-4dba-a5b0-d8649cdab7e3.mov

**Comment by kiaxseventh** [comment] 2022-11-20 16:13
i have same issue on flutter stable chanel
version 3.3.7 and 3.3.8

**Comment by kiaxseventh** [comment] 2022-11-20 16:15
#107006

**Comment by asashour** [comment] 2022-11-20 20:15
Duplicate of #110416

**Comment by darshankawar** [comment] 2022-11-21 06:30
Closing this as duplicate of https://github.com/flutter/flutter/issues/110416

**Closed by darshankawar** 2022-11-21 06:30 UTC
Labels: in triage
