### ISSUE TITLE
Unable to run flutter doctor on Mac. The flutter tool cannot access the file or directory.

### ISSUE THREAD

**Issue by nirjanmunshi** [flutter/flutter#111262] opened 2022-09-09 13:03 UTC
I am not new to flutter. Currently, I am using Mac OS Monterey 12.5.1. Previously Flutter was in this machine and working fine. After Formatting the MacBook I am facing some strange issues while installing the latest flutter (3.3.1).

After extracting the latest flutter for the intel chip I am setting the path to using `vim .zshrc`.

`export PATH="$PATH:/Users/Nirjan/src/flutter/bin"`

After doing this in **terminal** `which flutter` command is give me this is as output `/Users/Nirjan/src/flutter/bin/flutter`.

But when I run `flutter doctor` it is showing me this.

```
Nirjan@Administrators-MacBook-Air ~ % flutter doctor -v
The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has
read/write permissions for the current user.



#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException
(package:flutter_tools/src/base/error_handling_io.dart:820:3)
#2      _handlePosixException
(package:flutter_tools/src/base/error_handling_io.dart:761:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:614:7)
#4      ErrorHandlingProcessManager.runSync
(package:flutter_tools/src/base/error_handling_io.dart:711:12)
#5      _DefaultProcessUtils.runSync
(package:flutter_tools/src/base/process.dart:372:51)
#6      AndroidStudio._init
(package:flutter_tools/src/android/android_studio.dart:458:39)
#7      new AndroidStudio
(package:flutter_tools/src/android/android_studio.dart:40:5)
#8      AndroidStudio.fromMacOSBundle
(package:flutter_tools/src/android/android_studio.dart:90:12)
#9      AndroidStudio._allMacOS.<anonymous closure>
(package:flutter_tools/src/android/android_studio.dart:316:68)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#12     WhereTypeIterator.moveNext (dart:_internal/iterable.dart:869:20)
#13     new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#14     new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#15     new List.of (dart:core-patch/array_patch.dart:51:28)
#16     Iterable.toList (dart:core/iterable.dart:470:12)
#17     AndroidStudio._allMacOS
(package:flutter_tools/src/android/android_studio.dart:318:10)
#18     AndroidStudio.allInstalled
(package:flutter_tools/src/android/android_studio.dart:247:34)
#19     AndroidStudio.latestValid
(package:flutter_tools/src/android/android_studio.dart:232:41)
#20     AppContext._generateIfNecessary.<anonymous closure>
(package:flutter_tools/src/base/context.dart:104:42)
#21     _LinkedHashMapMixin.putIfAbsent
(dart:collection-patch/compact_hash.dart:527:23)
#22     AppContext._generateIfNecessary
(package:flutter_tools/src/base/context.dart:92:20)
#23     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#24     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#25     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#26     androidStudio (package:flutter_tools/src/globals.dart:62:45)
#27     runInContext.<anonymous closure>
(package:flutter_tools/src/context_runner.dart:103:32)
#28     AppContext._generateIfNecessary.<anonymous closure>
(package:flutter_tools/src/base/context.dart:104:42)
#29     _LinkedHashMapMixin.putIfAbsent
(dart:collection-patch/compact_hash.dart:527:23)
#30     AppContext._generateIfNecessary
(package:flutter_tools/src/base/context.dart:92:20)
#31     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#32     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#33     AppContext.get (package:flutter_tools/src/base/context.dart:119:24)
#34     androidLicenseValidator
(package:flutter_tools/src/android/android_workflow.dart:30:65)
#35     DoctorCommand.runCommand
(package:flutter_tools/src/commands/doctor.dart:53:32)
#36     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1374:12)
<asynchronous suspension>
#37     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#39     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#40     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#41     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#42     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#43     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
#44     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#45     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>
```

From the error, it is clear that there are some permission issues. So attaching the screenshot of `src` folder
That src folder has `read/write` permission also.
![image](https://user-images.githubusercontent.com/47732775/189355213-f7375e64-acb0-41ca-a3ae-1f0387612e84.png)

I can't understand what is going wrong. Need some references for solving this.

**Comment by huycozy** [comment] 2022-09-12 04:59
Hi @nirjanmunshi 
From your logs, it seems the issue is caused by Android Studio installation. I see there's an open issue addressing the case you described #70216
Closing this issue as a duplicate, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2022-09-12 04:59 UTC
Labels: in triage
