### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by umairMobologics** [flutter/flutter#160836] opened 2024-12-25 08:02 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.5, on macOS 15.1 24B83 darwin-arm64, locale en-US)
    [32m•[39m Flutter version 3.24.5 on channel stable at /Users/mac/Downloads/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision dec2ee5c1f (6 weeks ago), 2024-11-13 11:13:06 -0800
    [32m•[39m Engine revision a18df97ca5
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/mac/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16B40
    [32m•[39m CocoaPods version 1.16.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[32m[✓][39m VS Code (version 1.96.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.102.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m Umair’s iPhone (mobile)         • 00008101-000D64212E63003A • ios            • iOS 18.1.1 22B91
    [32m•[39m macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1 24B83 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1 24B83 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.205

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 2663184aa79047d0a33a14a3b607954f8fdd8730
### Plugins
app_tracking_transparency-2.0.6
awesome_notifications-0.10.0
cloud_firestore-5.4.4
cloud_firestore_web-4.3.2
connectivity_plus-6.0.5
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4+1
file_selector_windows-0.9.3+2
firebase_analytics-11.3.2
firebase_analytics_web-0.5.10+1
firebase_core-3.6.0
firebase_core_web-2.18.1
firebase_crashlytics-4.1.2
firebase_remote_config-5.1.2
firebase_remote_config_web-1.7.1
flutter_plugin_android_lifecycle-2.0.22
flutter_tts-4.0.2
google_mobile_ads-5.1.0
image_cropper-6.0.0
image_cropper_for_web-4.0.0
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
in_app_purchase-3.2.0
in_app_purchase_android-0.3.6+8
in_app_purchase_storekit-0.3.18+1
in_app_review-2.0.9
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.12
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
share_plus-10.0.2
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
speech_to_text-6.6.2
speech_to_text_macos-1.1.0
sqflite-2.4.0
sqflite_android-2.4.0
sqflite_darwin-2.4.1-1
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
webview_flutter-4.9.0
webview_flutter_android-3.16.7
webview_flutter_wkwebview-3.15.0

**Comment by danagbemava-nc** [comment] 2024-12-30 07:32
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-12-30 07:32 UTC
Labels: in triage
