### ISSUE TITLE
The console outputs too much information. How do I turn it off

### ISSUE THREAD

**Issue by Lidinghua** [flutter/flutter#76689] opened 2021-02-24 09:58 UTC
The console outputs too much information When I debug the application.How do I turn it off.

<details>
<summary>logs</summary>

```bash
https://github.com/flutter/flutter/files/6035019/console.txt
[ +114 ms] executing: [D:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +66 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 78910062997c3a836feee883712c241a5fd22983
[        ] executing: [D:\flutter/] git tag --points-at HEAD
[  +47 ms] Exit code 0 from: git tag --points-at HEAD
[        ] 1.22.5
[   +6 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\flutter/] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +625 ms] executing: [D:\flutter/] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +126 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +16 ms] executing: D:\Android\platform-tools\adb.exe devices -l
[ +102 ms] List of devices attached
           381023ed               device product:picasso model:Redmi_K30_5G device:picasso transport_id:1
[   +6 ms] D:\Android\platform-tools\adb.exe -s 381023ed shell getprop
[ +133 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.```
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +83 ms] event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in material_flutter...}
[   +6 ms] Using D:\flutter\.pub-cache for the pub cache.
[   +1 ms] executing: [D:\myProject\material_flutter/] D:\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning get --no-precompile
```
</details>

**Comment by iapicca** [comment] 2021-02-24 10:05
@Lidinghua 
is this the output of `flutter run -v` or `flutter run` ?
can you provide your `flutter doctor -v`

**Comment by Lidinghua** [comment] 2021-02-24 10:08
Click the Debug button for IntelliJ IDEA.


D:\myProject\material_flutter>flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.18363.1379], locale zh-CN)
    • Flutter version 1.22.5 at D:\flutter
    • Framework revision 7891006299 (3 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Android
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = D:\Android
    • Java binary at: D:\jdk\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at D:\IntelliJ IDEA 2019.3.5
    • Flutter plugin installed
    • Dart plugin version 193.7547

[√] Connected device (1 available)
    • Redmi K30 5G (mobile) • 381023ed • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

**Comment by TahaTesser** [comment] 2021-02-24 12:14
Hi @Lidinghua 
Trying on the latest `stable` with a new project I'm getting the following lines in debug mode in Android Studio
```bash
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Waiting for Android SDK built for x86 to report its views...
Debug service listening on ws://127.0.0.1:50180/oE34yTIFcUM=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 5016): eglMakeCurrent: 0x987fcec0: ver 2 0 (tinfo 0x9b403fb0)
```

Can you please upgrade to the latest `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

If the problem persists, Can you please provide your `flutter doctor -v` with the upgrade, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by Lidinghua** [comment] 2021-02-25 01:14
It's too tedious to try.The application is still working, although the console output is heavy.I just tried this method two days ago, and this is what happened
`flutter.bat pub global activate devtools`
`flutter.bat pub global run devtools`

If there is no suggestion now, the question can be ignored.It's just a bit of a hassle to find information on the console

**Comment by pedromassangocode** [comment] 2021-02-25 14:27
Hi @Lidinghua 
It is not clear what this issue is about, can you please elaborate?
Your first logs does not match with the steps you described in your last comment.

Please elaborate or if you have any proposal, just close this what open a new issue filling the issue-template and describing your proposal.
Thank you

**Comment by Lidinghua** [comment] 2021-02-25 14:33
I want to simplify the console output, just like yours

**Comment by pedromassangocode** [comment] 2021-02-26 08:23
Hi @Lidinghua 
Can you please provide the command you ran that gives you "too much information"? It is still not clear what cause this issue and how to replicate it.
Thank you

**Comment by Lidinghua** [comment] 2021-02-26 08:36
Simplified console output
![image](https://user-images.githubusercontent.com/46698923/109276261-c43d4a80-7850-11eb-9c42-9a4564caa513.png)

**Comment by Lidinghua** [comment] 2021-02-26 08:37
Maybe I'm not very good at expressing it

**Comment by pedromassangocode** [comment] 2021-02-26 08:44
Hi @Lidinghua 
What Flutter command are you running?

**Comment by Lidinghua** [comment] 2021-02-26 08:48
![image](https://user-images.githubusercontent.com/46698923/109277324-28144300-7852-11eb-9a44-21dac0feb157.png)
intellij IDEA

**Comment by Lidinghua** [comment] 2021-02-26 08:49
![image](https://user-images.githubusercontent.com/46698923/109277669-978a3280-7852-11eb-9323-39b50d401759.png)

**Comment by pedromassangocode** [comment] 2021-02-26 10:47
Hi @Lidinghua 
Can you please share a screenshot fo your Run Configuration screen? You can follow the steps in the .gif bellow and share the screenshot of the last window.

![gif](https://user-images.githubusercontent.com/67424416/109290626-25045d00-7828-11eb-8cee-8be96d7d958e.gif)

**Comment by Lidinghua** [comment] 2021-03-03 05:56
Sorry, I forgot about it
![image](https://user-images.githubusercontent.com/46698923/109759568-28348a00-7c28-11eb-9b0f-977426a6f426.png)

**Comment by Lidinghua** [comment] 2021-03-03 06:23
I followed the steps and got the same result

https://user-images.githubusercontent.com/46698923/109760861-6763da80-7c2a-11eb-9912-21ca966367af.mp4

the screenshot of my application.This is a login page.
![Screenshot_2021-03-03-14](https://user-images.githubusercontent.com/46698923/109761489-23250a00-7c2b-11eb-929b-f80dfca97655.jpg)

**Comment by pedromassangocode** [comment] 2021-03-03 06:53
Hi @Lidinghua 
It seems that you are getting "too much information" when passing `--verbose` to the `flutter run` command which is an expected result.

If you want to remove all the logs, you can just remove the `--verbose`  flag.

**Comment by Lidinghua** [comment] 2021-03-03 07:29
It seems like when I run `flutter run`, I get the output I want, and when I hit the Debug button, I get a lot of output, not related to the `--verbose` parameter
![image](https://user-images.githubusercontent.com/46698923/109769438-27eebb80-7c35-11eb-8923-ff761b8fe476.png)

**Comment by pedromassangocode** [comment] 2021-03-03 09:49
> and when I hit the Debug button, I get a lot of output, not related to the `--verbose` parameter

That is probably because you added the `--verbose` flag in the run/debug configuration.

I'm closing this for now as this does not seems a valid issue but a misconfiguration of the run/debug settings.
Thank you

**Closed by pedromassangocode** 2021-03-03 09:49 UTC
Labels: in triage
