### ISSUE TITLE
[Web] Transform perspective on a Stack affects child widgets inconsistently

### ISSUE THREAD

**Issue by devvercer** [flutter/flutter#61245] opened 2020-07-10 16:59 UTC
## Steps to Reproduce

Create a heirarchy
```
Transform
  Stack
    Image
    Container
    Text
```
On Android the entire Stack is transformed as if it were a flat single layer.  On web the child elements are transformed in different amounts / directions.

My transform is this:
```
Transform(
      transform: Matrix4.identity()
        ..setEntry(3, 2, PERSPECTIVE) // perspective
        ..rotateY(offset * math.pi),
      alignment: Alignment.centerLeft,
      transformHitTests: false,
      child: child,
    );
```
    

**Expected results:** 

Works correctly on Android:
<img width="344" alt="Screen Shot 2020-07-10 at 19 01 14" src="https://user-images.githubusercontent.com/29699435/87179888-c6619180-c2df-11ea-80b3-dac72979fa9f.png">

**Actual results:** 

On Chrome it looks like this:

<img width="500" alt="Screen Shot 2020-07-10 at 18 37 54" src="https://user-images.githubusercontent.com/29699435/87179498-1e4bc880-c2df-11ea-8862-e633913a8089.png">

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.5 19F101, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.1.3)
[✓] Connected device (3 available)
```

Chrome version: Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by TahaTesser** [comment] 2020-07-13 09:26
Hi @devvercer 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by devvercer** [comment] 2020-07-13 20:07
I had trouble distilling this problem which led to a useful observation.

When I include an image in the stack this problem occurs.  When the image below is commented out the problem does not occur.


```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: buildScaffold());

  Widget buildScaffold() {
    return SafeArea(
      child: Container(
        color: Colors.grey,
        padding: const EdgeInsets.symmetric(vertical: 40),
        child: Transform(
          transform: Matrix4.identity()
            ..setEntry(3, 2, 0.0005) // perspective
            ..rotateY(1),
          alignment: Alignment.centerLeft,
          child: buildStack(),
        ),
      ),
    );
  }

  Stack buildStack() {
    return Stack(
      fit: StackFit.expand,
      children: [
        Container(
          color: Colors.blue,
        ),
        Image(
          fit: BoxFit.cover,
          alignment: AlignmentDirectional.center,
          image: AssetImage('assets/yellow_woman.jpg'),
        ),
        Align(
            alignment: Alignment.centerRight,
            child: Container(
              color: Colors.black,
              child: Text(
                'Hello there',
                style: TextStyle(color: Colors.white),
              ),
            )),
      ],
    );
  }
}
```

The minimal sample above produces this mess:

<img width="516" alt="Screen Shot 2020-07-13 at 22 05 50" src="https://user-images.githubusercontent.com/29699435/87348506-22811b80-c555-11ea-9825-acd05eaa6ac3.png">

When the image is commented out it shows like this:

<img width="503" alt="Screen Shot 2020-07-13 at 22 06 09" src="https://user-images.githubusercontent.com/29699435/87348537-3298fb00-c555-11ea-9e75-144f36ea3c78.png">

**Comment by TahaTesser** [comment] 2020-07-14 07:08
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-7.1.pre at /home/taha/Code/flutter_master
    • Framework revision 7736f3bc90 (3 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /home/taha/Code/sdk
    • Java binary at: /home/taha/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1
[✓] Android Studio (version 4.0)
    • Android Studio at /home/taha/Code/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
[✓] VS Code (version 1.47.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.12.2
[✓] Connected device (3 available)
    • Linux (desktop)  • linux      • linux-x64      • Linux
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      83.0.4103.116
• No issues found!
```

</details>

**Comment by ferhatb** [comment] 2020-08-28 04:14
Seems to be fixed by flutter/engine#20310. Please retry on master channel (tried it and it correctly set transform on image and container). 

If you still see issue please reopen.

**Comment by devvercer** [comment] 2020-08-29 15:05
This bug is not fixed :(

I changed to master and upgraded (see flutter doctor output below)

flutter clean && flutter build web

I ran the newly generated files and verified the changes made.

The result is the same as shown above - incorrect transform only when an image is loaded.

![image](https://user-images.githubusercontent.com/29699435/91639856-c34e6c00-ea19-11ea-87ff-daef151ccead.png)

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-2.0.pre.130, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by devvercer** [comment] 2020-08-31 20:15
One further note: when the page loads the image takes some time to display and until that time the text renders correctly.  When the image finishes loading, the text changes position to be incorrect.

**Comment by devvercer** [comment] 2020-08-31 20:53
When I run the app like this, it works:

flutter run -d Chrome --dart-define=FLUTTER_WEB_USE_SKIA=true --release

**Comment by TahaTesser** [comment] 2020-09-01 09:47
The issue is reproducible on the latest `master`

**Web Desktop**

<img width="218" alt="Screenshot 2020-09-01 at 3 10 07 PM" src="https://user-images.githubusercontent.com/48603081/91834849-32b89b80-ec66-11ea-90dd-93f1f5e3b2f0.png">

**Web Mobile**

![Simulator Screen Shot - iPhone 11 - 2020-09-01 at 15 15 37](https://user-images.githubusercontent.com/48603081/91834867-3b10d680-ec66-11ea-972f-cbe27fac15b5.png)


**Mobile**

![Simulator Screen Shot - iPhone 11 - 2020-09-01 at 15 09 06](https://user-images.githubusercontent.com/48603081/91834886-4237e480-ec66-11ea-992c-0b91bcc6d591.png)



<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: buildScaffold());

  Widget buildScaffold() {
    return SafeArea(
      child: Container(
        color: Colors.grey,
        padding: const EdgeInsets.symmetric(vertical: 40),
        child: Transform(
          transform: Matrix4.identity()
            ..setEntry(3, 2, 0.0005) // perspective
            ..rotateY(1),
          alignment: Alignment.centerLeft,
          child: buildStack(),
        ),
      ),
    );
  }

  Stack buildStack() {
    return Stack(
      fit: StackFit.expand,
      children: [
        Container(
          color: Colors.blue,
        ),
        Image(
          fit: BoxFit.cover,
          alignment: AlignmentDirectional.center,
          image: NetworkImage('https://i.imgur.com/QCNbOAo.png'),
        ),
        Align(
            alignment: Alignment.centerRight,
            child: Container(
              color: Colors.black,
              child: Text(
                'Hello there',
                style: TextStyle(color: Colors.white),
              ),
            )),
      ],
    );
  }
}


```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.161, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-2.0.pre.161 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision ba78539bdb (8 hours ago), 2020-08-31 19:13:04 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • iPhone 11 (mobile) • A63D6F51-59F3-4A75-961F-3769709F3A92 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 84.0.4147.135

• No issues found!
```

</details>

**Comment by ferhatb** [comment] 2020-10-23 01:04
PR landed in master. 

![Screen Shot 2020-10-22 at 6 03 40 PM](https://user-images.githubusercontent.com/5061034/96944881-fb5db280-1490-11eb-9658-fc1143013dcd.png)

**Closed by ferhatb** 2020-10-23 01:04 UTC
Labels: P3, a: images, a: quality, found in release: 1.19, found in release: 1.20, found in release: 1.22, framework, has reproducible steps, platform-web, waiting for PR to land (fixed)
