### ISSUE TITLE
SliverAppBar not honoring safe area when not the first

### ISSUE THREAD

**Issue by cvolzke4** [flutter/flutter#37529] opened 2019-08-03 03:03 UTC
I'm trying to add a floating SliverAppHeader, rendered underneath another Sliver, but am having issues with the cutout above when sliding in the SliverAppHeader.

The stack of slivers is configured as follows:
```
List<Widget> _buildSlivers(AuthService authService) [
  // Must be shown below the top safe area (notch).
  SliverSafeArea(sliver: SliverToBoxAdapter(child: _buildBlogListDropDown()),
  // Must be shown below the top safe area (notch).
  SliverAppBar(floating: true, primary: true, title: _buildPostTypeTabs(context)),
  // Must be free to scroll over the entire screen, including the safe area.
  SliverList(delegate: ...),
];
```
The intended (working) behavior can be seen here:
https://drive.google.com/file/d/16lY_ZOGmyS37ncv1XKWOVd6BGXdSJk3T

The issue is that SliverAppBar either:
a) With primary=false, it doesn't respect the safe area for SliverAppBar (when scrolling up the page).
b) With primary=true, it respects the safe area, but renders a larger gap between Sliver #1 and SliverAppBar when using a device with a notch.

I've tried a few things to try and resolve this:

Set primary=true - but the gap between Sliver #1 and SliverAppBar widens based on whether there's a notch.
Set primary=false and render a gap below Sliver #1, and another gap above SliverAppBar - but then I have to find space from Sliver #1 which isn't available.
I managed to get this working by dynamically opening and closing a gap between Sliver #1 and SliverAppHeader for padding at the top of SliverAppHeader as the user scrolls down the page, see:
cl/260892122

But I was hoping there would be an easier way to achieve this.

**Comment by Piinks** [comment] 2019-10-01 21:07
Hi @cvolzke4, Have you tried using a [`SliverPersistentHeader`](https://master-api.flutter.dev/flutter/widgets/SliverPersistentHeader-class.html)? 
According to the documentation for `SliverAppBar`

> Sliver app bars are typically used as the first child of a CustomScrollView, which lets the app bar integrate with the scroll view so that it can vary in height according to the scroll offset or float above the other content in the scroll view. 

`SliverPersistentHeader` can be used anywhere in your scroll view.

**Comment by cvolzke4** [comment] 2019-10-03 08:32
SliverAppBar can also be used anywhere in the scroll view, and simply wraps
around a SliverPersistentHeader (if you look at it's build method).

**Comment by Piinks** [comment] 2019-10-04 19:49
Would you be able to share a runnable code snippet that reproduces the undesirable behavior?
I do not fully understand the issue you are describing. It seems that the safe area is not being honored because the app bar is not inside of it? Possibly?

**Comment by Flavsditz** [comment] 2020-02-21 19:12
I am having the same problem. 
Maybe I can provide an example of where I am at:

```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyWidget(),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: CustomScrollView(
          slivers: <Widget>[
            SliverAppBar(
              title: Text("Hey"),
              expandedHeight: 100,
            ),
            SliverPersistentHeader(
              pinned: true,
              delegate: MyDynamicHeader(),
            ),
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (BuildContext context, int index) {
                  return Container(
                    child: ListTile(
                      title: Text("Item $index"),
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class MyDynamicHeader extends SliverPersistentHeaderDelegate {
  int index = 0;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return LayoutBuilder(
      builder: (context, constraints) {
        print("Min, max ($minExtent, $maxExtent, ${constraints.maxHeight})");

        final double percentage =
            (constraints.maxHeight - minExtent) / (maxExtent - minExtent);

        if (++index > Colors.primaries.length - 1) index = 0;

        return Container(
          decoration: BoxDecoration(
            boxShadow: [BoxShadow(blurRadius: 4.0, color: Colors.black45)],
            color: Colors.red,
          ),
          height: constraints.maxHeight,
          child: SafeArea(
            child: Center(
              child: CircularProgressIndicator(
                value: percentage,
                valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
              ),
            ),
          ),
        );
      },
    );
  }

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate _) => true;

  @override
  double get maxExtent => 250.0;

  @override
  double get minExtent => 80.0;
}

```

One can see that the SliverAppBar hides when we scroll up however the SliverPersistentHeader goes partly under the status Bar. In this example, it looks like it doesn't matter but in my actual app I have text inside which then just looks cutoff.

**Comment by darshankawar** [comment] 2020-09-15 12:03
Issue replicable on latest master, going by @Flavsditz's code sample.

![37529](https://user-images.githubusercontent.com/67046386/93207990-7688c600-f779-11ea-9f7d-ee466a8d3fae.png)

<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.22.0-10.0.pre.174 • channel master • https://github.com/flutter/flutter.git
Framework • revision 37b03ec2c2 (4 hours ago) • 2020-09-14 23:52:04 -0400
Engine • revision 7e962ba911
Tools • Dart 2.10.0 (build 2.10.0-124.0.dev)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.22.0-10.0.pre.174, on Mac OS X 10.15.4 19E2269, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (4 available)

• No issues found!
```

</details>

**Comment by sannykhan3777** [comment] 2022-01-19 13:52
having the same issue 
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:get/get.dart';
import 'package:jobfindapp/constants/constants.dart';
import 'package:jobfindapp/controllers/notificationscreen_controller.dart';
import 'package:jobfindapp/controllers/searchscreen_controller.dart';
import 'package:jobfindapp/screens/home_screen.dart';
import 'package:outline_search_bar/outline_search_bar.dart';


class SearchScreen extends StatefulWidget {
  const SearchScreen({Key? key}) : super(key: key);

  @override
  _SearchScreenState createState() => _SearchScreenState();
}

class _SearchScreenState extends State<SearchScreen> {
  SearchScreenController searchScreenController =
  Get.put(SearchScreenController());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
          child: CustomScrollView(
            physics: BouncingScrollPhysics(),
            slivers: <Widget>[
              // SliverPersistentHeader(
              // delegate: 
              // ),

              SliverList(
                delegate: SliverChildBuilderDelegate(
                      (BuildContext context, int index) {
                    return Padding(
                      padding: const EdgeInsets.symmetric(
                          vertical: 3.0, horizontal: 14.0),
                      child: Obx(()=> ListTile(
                        isThreeLine: true,
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(20.0)),
                        // minVerticalPadding: 35.0,
                        // minLeadingWidth: 10.0,
                        contentPadding: EdgeInsets.symmetric(vertical: 10.0 , horizontal: 1.0),

                        // selected: true,
                        // selectedColor:
                        // selectedTileColor: Colors.yellow,
                        textColor: searchScreenController.isSelected[index] ? Colors.white : black,
                        tileColor: searchScreenController.isSelected[index] ? Color(0xFF008479) : Colors.white,
                        enableFeedback: true,

                        onTap: () {
                          searchScreenController.isSelected[index] = !searchScreenController.isSelected[index];

                          // searchScreenController.isSelected.value = true;

                        },
                        leading: Container(
                          width: Get.width * 0.22,
                          child: Row(
                            children: [
                              CircleAvatar(
                                radius: 40,
                                child: Image.network(
                                    'https://www.kindpng.com/picc/m/271-2711764_girl-image-in-circle-hd-png-download.png'),
                              ),
                            ],
                          ),
                        ),
                        trailing: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            IconButton(
                              icon: Icon(
                                Icons.favorite_border_rounded,
                                size: 20,
                                color: searchScreenController.isSelected[index] ? Colors.white : black,
                              ),
                              onPressed: () {},
                            ),
                            Text(
                              "${DateTime.now().second} s",
                              style: TextStyle(fontSize: 10.0),
                            ),
                          ],
                        ),
                        title: Text("Google"),
                        subtitle: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text("Full Time Designer"),
                            Text("10\$ Tokyo, Japan"),
                          ],
                        ),
                      ),
                      ),
                    );
                  },
                  childCount: 40,
                ),
              ),

              //3

            ],
          ),
        ),
    );
  }
}
`

![image](https://user-images.githubusercontent.com/52849890/150143987-a3530ccc-0958-41e8-b2b4-360ed7263fd4.png)

**Comment by maheshmnj** [comment] 2022-12-24 02:59
Hi @cvolzke4, I verified the below code sample and I am not able to reproduce the issue. SliverPersistentHeader shrinks to minExtent and stays pinned at the top

SliverPersistentHeader (expands to full height: 250) | SliverPersistentHeader (Pinned to minHeight:80)
:-------------------------:|:-------------------------:
![simulator_screenshot_C1013F50-5A03-472F-B99F-7B74DCE6CBF6](https://user-images.githubusercontent.com/31410839/209418854-4a0b05f1-b485-4aa8-9c70-c0bff1be13d8.png) | ![simulator_screenshot_38436D4D-B16D-42BD-8605-DB443AA697F3](https://user-images.githubusercontent.com/31410839/209418858-e0d530bc-5158-4d78-bb25-8afab57a5b1b.png)


<details>
<summary>logs</summary>

```console
Restarted application in 338ms.
flutter: Min, max (80.0, 250.0, 250.0)
flutter: Min, max (80.0, 250.0, 243.90718001140385)
flutter: Min, max (80.0, 250.0, 222.3796257458008)
flutter: Min, max (80.0, 250.0, 201.55743307484852)
flutter: Min, max (80.0, 250.0, 181.41753085862763)
flutter: Min, max (80.0, 250.0, 161.94104896745978)
flutter: Min, max (80.0, 250.0, 143.09716663723793)
flutter: Min, max (80.0, 250.0, 124.87738347208278)
flutter: Min, max (80.0, 250.0, 107.26293434751301)
flutter: Min, max (80.0, 250.0, 90.21939303701606)
flutter: Min, max (80.0, 250.0, 80.0)
```
</details> 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyWidget(),
    );
  }
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: CustomScrollView(
          slivers: <Widget>[
            const SliverAppBar(
              title: Text("Hey"),
              expandedHeight: 100,
            ),
            SliverPersistentHeader(
              pinned: true,
              delegate: MyDynamicHeader(),
            ),
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (BuildContext context, int index) {
                  return Container(
                    child: ListTile(
                      title: Text("Item $index"),
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class MyDynamicHeader extends SliverPersistentHeaderDelegate {
  int index = 0;

  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return LayoutBuilder(
      builder: (context, constraints) {
        print("Min, max ($minExtent, $maxExtent, ${constraints.maxHeight})");

        final double percentage =
            (constraints.maxHeight - minExtent) / (maxExtent - minExtent);

        if (++index > Colors.primaries.length - 1) index = 0;

        return Container(
          decoration: const BoxDecoration(
            boxShadow: [BoxShadow(blurRadius: 4.0, color: Colors.black45)],
            color: Colors.red,
          ),
          height: constraints.maxHeight,
          child: SafeArea(
            child: Center(
              child: CircularProgressIndicator(
                value: percentage,
                valueColor: const AlwaysStoppedAnimation<Color>(Colors.white),
              ),
            ),
          ),
        );
      },
    );
  }

  @override
  bool shouldRebuild(SliverPersistentHeaderDelegate _) => true;

  @override
  double get maxExtent => 250.0;

  @override
  double get minExtent => 80.0;
}

```
</details> 

Closing as fixed. Incase anyone still encounters the issue, then Please write in the comments with more details and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-12-24 02:59 UTC
Labels: framework, f: scrolling, passed first triage, has reproducible steps, found in release: 1.22
