### ISSUE TITLE
Allow persistent BottomNavigationBar across all pages and sub pages as per Material Design Specs!

### ISSUE THREAD

**Issue by giorgio79** [flutter/flutter#63941] opened 2020-08-17 09:57 UTC
Hello,

When we navigate in the app to a page that is not included in the BottomNavigationBar, the bar gets hidden...

Material Design now recommends having persistent bottomnavbar as per https://material.io/components/bottom-navigation#behavior

Please implement the sub-navigation Bottom Navigation behavior as outlined in the spec. You can feature flag it if that makes it easier. persistNavigationBar? subNavigator?
Here is a community solution https://pub.dev/packages/persistent_bottom_nav_bar

A previous issue was closed by error of the Google team... https://github.com/flutter/flutter/issues/16221

![image](https://user-images.githubusercontent.com/283347/90383969-2b4b9c80-e081-11ea-8a4c-630e41bc8a50.png)

**Comment by yoliva** [comment] 2021-06-28 14:08
Hello, any updates on this one?

**Comment by MrBirb** [comment] 2021-07-29 11:44
@TahaTesser Looks like a duplicate of #18740

**Comment by TahaTesser** [comment] 2021-07-30 10:41
Hi @MrBirb 
Thanks!  Closing as duplicate of https://github.com/flutter/flutter/issues/18740

**Closed by TahaTesser** 2021-07-30 10:41 UTC
Labels: f: material design, f: routes, framework, passed first triage, proposal, severe: new feature
