### ISSUE TITLE
ReorderableListView causing a crash in Windows "stable channel" !

### ISSUE THREAD

**Issue by hamzaj9** [flutter/flutter#100610] opened 2022-03-23 11:03 UTC
Hello, 
my windows app is crashing after launching it. I believe its because of the ReorderableListView.

I just created new project, copied the sample code from "https://api.flutter.dev/flutter/material/ReorderableListView-class.html" and tested it. can i know exactly what's happening?

some times I got this messages in the terminal:
`[ERROR:accessibility_bridge.cc(76)] Failed to update ui::AXTree, error: 28 will not be in the tree and is not the new root`
some times I got other messages but still containing `Failed to update ui::AXTree`
most of the time, i got nothing, the app crashed and lost connection

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.2)
[√] Android Studio (version 4.1)
[√] VS Code (version 1.65.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

**Comment by hamzaj9** [comment] 2022-03-23 11:28
Note: we test the release exe in 4 different machines. all machines are windows 10.
- 2 of the machines having this issue (crashing when launching the app). these 2 machines we are using for developing. so it may caused by some development libraries (C++ runtime libraries or other)
- the other 2 are just working fine

**Comment by hamzaj9** [comment] 2022-03-23 12:18
we got it solved by downloading the latest C++ library from here:
https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
but we still didn't know why it happened in the first place

**Comment by maheshmnj** [comment] 2022-03-23 12:30
Thanks for the update @hamzaj9, Closing the issue as solved. However, I couldn't reproduce it on my side. In case you see the crash again feel free to file a new issue or comment on this issue and we will reopen it.

> [ERROR:accessibility_bridge.cc(76)] Failed to update ui::AXTree, error: 28 will not be in the tree and is not the new root

Regarding this message in the console, This is being tracked here #98099, Please follow up there for further updates.

**Closed by maheshmnj** 2022-03-23 12:30 UTC
Labels: in triage
