### ISSUE TITLE
High CPU usage on windows desktop

### ISSUE THREAD

**Issue by deekay42** [flutter/flutter#32002] opened 2019-05-02 21:10 UTC
I'm running the vanilla flutter-desktop-embedding demo app (the counter) on windows.
CPU utilization hovers around 33% but occasionally shoots up to over 40%. For a trivial app that's idling this seems pretty high. Is there any way to reduce this?

**Comment by stuartmorgan** [comment] 2019-05-03 02:40
This is a duplicate of #30730

**Closed by stuartmorgan** 2019-05-03 02:40 UTC
