### ISSUE TITLE
Error when running macOS app: `Could not find macOS binary at build/macos/Build/Products/Debug/<app-name>.app/Contents/MacOS/<app-name>`

### ISSUE THREAD

**Issue by jeremiahlukus** [flutter/flutter#142011] opened 2024-01-22 22:39 UTC
### Steps to reproduce

flutter create test
flutter config --enable-macos-desktop
flutter build macos  or flutter run -d macos

### Actual results

```
Could not find macOS binary at build/macos/Build/Products/Debug/test.app/Contents/MacOS/test
Unable to start executable "build/macos/Build/Products/Debug/test.app/Contents/MacOS/test": ProcessException: Failed to find
"build/macos/Build/Products/Debug/test.app/Contents/MacOS/test" in the search path.
  Command: build/macos/Build/Products/Debug/test.app/Contents/MacOS/test 
ProcessException: Failed to find "build/macos/Build/Products/Debug/test.app/Contents/MacOS/test" in the search path.
  Command: build/macos/Build/Products/Debug/test.app/Contents/MacOS/test 
  ```

### Logs

<details open>
<summary>Logs</summary>

```console

[  +81 ms] ** BUILD SUCCEEDED **
[  +13 ms] Building macOS application... (completed in 9.1s)
[  +12 ms] executing: /usr/bin/plutil -convert xml1 -o - /Users/jeremiah.parrack/freelance/pep/test/build/macos/Build/Products/Debug/test.app/Contents/Info.plist
[  +16 ms] Exit code 0 from: /usr/bin/plutil -convert xml1 -o - /Users/jeremiah.parrack/freelance/pep/test/build/macos/Build/Products/Debug/test.app/Contents/Info.plist
[        ] <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
           <plist version="1.0">
           <dict>
           	<key>BuildMachineOSBuild</key>
           	<string>23D56</string>
           	<key>CFBundleDevelopmentRegion</key>
           	<string>en</string>
           	<key>CFBundleExecutable</key>
           	<string>test</string>
           	<key>CFBundleIconFile</key>
           	<string>AppIcon</string>
           	<key>CFBundleIconName</key>
           	<string>AppIcon</string>
           	<key>CFBundleIdentifier</key>
           	<string>com.jparrack.test</string>
           	<key>CFBundleInfoDictionaryVersion</key>
           	<string>6.0</string>
           	<key>CFBundleName</key>
           	<string>test</string>
           	<key>CFBundlePackageType</key>
           	<string>APPL</string>
           	<key>CFBundleShortVersionString</key>
           	<string>1.0.0</string>
           	<key>CFBundleSupportedPlatforms</key>
           	<array>
           		<string>MacOSX</string>
           	</array>
           	<key>CFBundleVersion</key>
           	<string>1</string>
           	<key>DTCompiler</key>
           	<string>com.apple.compilers.llvm.clang.1_0</string>
           	<key>DTPlatformBuild</key>
           	<string></string>
           	<key>DTPlatformName</key>
           	<string>macosx</string>
           	<key>DTPlatformVersion</key>
           	<string>14.2</string>
           	<key>DTSDKBuild</key>
           	<string>23C53</string>
           	<key>DTSDKName</key>
           	<string>macosx14.2</string>
           	<key>DTXcode</key>
           	<string>1520</string>
           	<key>DTXcodeBuild</key>
           	<string>15C500b</string>
           	<key>LSMinimumSystemVersion</key>
           	<string>10.14</string>
           	<key>NSHumanReadableCopyright</key>
           	<string>Copyright © 2024 com.example. All rights reserved.</string>
           	<key>NSMainNibFile</key>
           	<string>MainMenu</string>
           	<key>NSPrincipalClass</key>
           	<string>NSApplication</string>
           </dict>
           </plist>
[   +1 ms] Could not find macOS binary at build/macos/Build/Products/Debug/test.app/Contents/MacOS/test
[   +2 ms] Unable to start executable "build/macos/Build/Products/Debug/test.app/Contents/MacOS/test": ProcessException: Failed to find
           "build/macos/Build/Products/Debug/test.app/Contents/MacOS/test" in the search path.
             Command: build/macos/Build/Products/Debug/test.app/Contents/MacOS/test 
[        ] ProcessException: Failed to find "build/macos/Build/Products/Debug/test.app/Contents/MacOS/test" in the search path.
             Command: build/macos/Build/Products/Debug/test.app/Contents/MacOS/test 
[        ] "flutter run" took 17,926ms.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:790:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +14 ms] ensureAnalyticsSent: 13ms
[        ] Running 1 shutdown hook
[   +2 ms] Shutdown hooks complete
[        ] exiting with code 1

```

</details>

### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.16.8, on macOS 14.3 23D56 darwin-arm64, locale en-US)
    • Flutter version 3.16.8 on channel stable at /Users/jeremiah.parrack/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (6 days ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jeremiah.parrack/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.3 23D56 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.234
    ! Error: Browsing on the local area network for iPhone (154). Ensure the device is unlocked and attached with a cable or associated with the same local area network as
      this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by huycozy** [comment] 2024-01-23 09:11
Thanks for the report!

The error is thrown at:
https://github.com/flutter/flutter/blob/aac6f33e51d00f28e3b5570f586b7a9f18c07030/packages/flutter_tools/lib/src/macos/application_package.dart#L101

I guess there is a race condition here when using `existsSync()`. A proposal at https://github.com/flutter/flutter/issues/129746 may be helpful if this conjecture is reasonable. 

I can't reproduce this on my end (I'm also using XCode 15.2). Labeling this for other's insights.

**Comment by gspencergoog** [comment] 2024-01-25 19:18
This seems like there are some missing steps in the reproduction steps.

What *should* happen here is that it should fail with a message like "No macOS desktop project configured.", because if you have manually disabled with `--no-enable-macos-desktop`, and then run `flutter create test`, then it should create a project that has no macos directory.  Running `flutter config --enable-macos-desktop` doesn't create it for you (and isn't supposed to).  If you want it to create it, you need to run `flutter create test` after enabling the feature.

My suspicion is that there is a leftover `macos` directory in your test, and something is messed up in it.

Was `flutter config --no-enable-macos-desktop` run before you did your create step?

(Desktop triage)

**Comment by jeremiahlukus** [comment] 2024-01-25 20:29
`flutter config --no-enable-macos-desktop` was not ran before. 

After running the commands again today I am unable to reproduce. I have no idea why I got this error nor can i reproduce it again. I have created at least 10 new projects and unable to reproduce.

**Comment by cbracken** [comment] 2024-01-25 21:01
I'll close the issue for now, but if you do find a way to repro this, please file a new issue and ideally link back to this one in the description. We should be creating macOS artifacts by default and things _should_ build, or for projects with no macOS artifacts, it should fail immediately, so the behaviour reported is definitely a bug if it can be repro'ed.

Thanks for looking into this!

**Closed by cbracken** 2024-01-25 21:01 UTC
Labels: c: crash, platform-mac, a: desktop, P2, needs repro info, team-desktop, triaged-desktop
