### ISSUE TITLE
Default `TextField` styles result in cursor overlapping `labelText`

### ISSUE THREAD

**Issue by parlough** [flutter/flutter#141354] opened 2024-01-11 07:11 UTC
Last update: https://github.com/flutter/flutter/issues/141354#issuecomment-1978770576

---

### Steps to reproduce

1. Have M3 enabled and a non-outlined `TextField` with a `labelText` specified
2. Run the app (I tried macOS, CanvasKit, and skwasm)
3. Enter the text field and start typing
4. Notice the cursor overlaps the label text

### Expected results

When typing in a `TextField` with `labelText`, the default styling won't result in the cursor overlapping the label text.

The [M3 spec](https://m3.material.io/components/text-fields/specs#dbc210fc-c916-4d28-8541-f3ecdb954a62) showcases the cursor as much thinner and shorter, preventing this from occurring.

### Actual results

The cursor overlaps the label text, making it potentially harder to read.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: 300,
            child: TextField(
              decoration: InputDecoration(
                labelText: 'Label text',
                filled: true,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots

<details open>
<summary>Screenshot</summary>

<img width="373" alt="TextField with cursor overlapping label text" src="https://github.com/flutter/flutter/assets/18372958/7ab7f8a7-a395-4874-9967-85d584132565">

</details>

### Flutter version info

<details><summary>Version</summary>

```console
Flutter 3.19.0-3.0.pre.43 • channel main • https://github.com/flutter/flutter
Framework • revision f961fdf2ba (4 hours ago) • 2024-01-10 17:37:07 -0500
Engine • revision a045134c91
Tools • Dart 3.4.0 (build 3.4.0-14.0.dev) • DevTools 2.31.0
```

</details>

**Comment by dam-ease** [comment] 2024-01-11 12:51
Thanks for filing this!
I can reproduce this on the latest `master` and `stable` channels on macOS and Web. This doesn't overlap on mobile.

| Mobile | MacOS | Web |
|--------|--------|--------|
| ❌ | ✅ | ✅ | 
✅- Reproduces
❌- Doesn't reproduce

| useMaterial3: false | useMaterial3: true |
|--------|--------|
| <img width="335" alt="Screenshot 2024-01-11 at 13 42 44" src="https://github.com/flutter/flutter/assets/53122008/2eea35f6-f7a1-4a9c-976a-92122d931e01"> | <img width="335" alt="Screenshot 2024-01-11 at 13 35 43" src="https://github.com/flutter/flutter/assets/53122008/b6cf206f-f69a-4163-b678-505b96076100"> | 

<details><summary>stable, master flutter doctor -v</summary>
<p>

```
[!] Flutter (Channel stable, 3.16.6, on macOS 14.2.1 23C71 darwin-arm64, locale
    en-NG)
    • Flutter version 3.16.6 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    ! Warning: `dart` on your path resolves to
      /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/damilolaalimi/sdks/flutter.
      Consider adding /Users/damilolaalimi/sdks/flutter/bin to the front of your
      path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 46787ee49c (32 hours ago), 2024-01-09 14:36:07 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • Damilola’s iPhone (mobile)  • 00008110-001964480AE1801E            • ios
      • iOS 17.1.1 21B91
    • iPhone 15 (mobile)          • F17D2919-6D61-4295-8408-1719692FE958 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
``` 
```
[!] Flutter (Channel master, 3.19.0-3.0.pre.50, on macOS 14.2.1 23C71 darwin-arm64, locale en-NG)
    • Flutter version 3.19.0-3.0.pre.50 on channel master at /Users/damilolaalimi/fvm/versions/master
    ! Warning: `flutter` on your path resolves to /Users/damilolaalimi/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/damilolaalimi/fvm/versions/master. Consider adding /Users/damilolaalimi/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3e5cad037c (3 hours ago), 2024-01-10 22:42:23 -0500
    • Engine revision ade9f18fa0
    • Dart version 3.4.0 (build 3.4.0-16.0.dev)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] VS Code (version 1.83.1)
    • VS Code at /Users/damilolaalimi/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • Damilola’s iPhone (mobile) • 00008110-001964480AE1801E • ios            • iOS 17.1.1 21B91
    • macOS (desktop)            • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 120.0.6099.216

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
exit code 0
``` 

</p>
</details>

**Comment by bleroux** [comment] 2024-01-25 15:21
FYI, since https://github.com/flutter/flutter/pull/141943 has landed, the rendering is a little less worse (not very visible but the cursor in no more inside the 'b' of 'label'):

![Capture d’écran 2024-01-25 à 16 07 57](https://github.com/flutter/flutter/assets/840911/64205a98-cab7-4110-863b-f0879d1aaca7)


This is because the main problem was related to the label positioning not taking properly line height into account (the label text line height is 1.5 for M3, for M2 it was 1.0, with this recent PR label line height is forced to 1.0, which is not compliant with M3 spec, but gives a better result). I will see if it is possible to get a proper positioning for the label text without forcing line height to 1.0.

A secondary problem is that the cursor height is too much. This is because it defaults to `preferredLineHeight`, and with M3 the text inside a TextField also has a line height of 1.5. One way to somewhat mitigate this issue is to explicitly set cursor height (unfortunately there is no way for the moment to set this at a theme level and also the vertical alignement of the cursor does not seem right).

<details><summary>Updated code sample with cursor height sets to 18 :</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: 300,
            child: TextField(
              cursorHeight: 18.0,
              decoration: InputDecoration(
                labelText: 'Label text',
                filled: true,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details> 

Which renders this way:

![Capture d’écran 2024-01-25 à 16 09 30](https://github.com/flutter/flutter/assets/840911/119ecb2d-69f3-4468-a714-7e9bba23af33)

@justinmc Do you know if there is some ongoing work related to adjusting the cursor position?

**Comment by bleroux** [comment] 2024-01-25 16:16
Just noticed that on Android this issue is not visible.
This is because the TextField height is 64 instead of 56.
![Capture d’écran 2024-01-25 à 17 05 45](https://github.com/flutter/flutter/assets/840911/6a00d9ee-9da9-4f4f-ac4a-627685cc6b0c)

@justinmc Sorry to bother you again, do you know if this is on purpose? From M3 specification, the text field height is supposed to be 56, see https://m3.material.io/components/text-fields/specs#0d36c3fe-7948-4ec2-ab8a-4fe39cca19cc.

**Comment by justinmc** [comment] 2024-02-09 18:30
Sorry for missing these questions, answered in https://github.com/flutter/flutter/pull/143216#pullrequestreview-1872948221.

**Comment by bleroux** [comment] 2024-03-05 13:24
Unassigning myself for the moment as there is no consensus on a valid solution.

Summary of this issue: on Apple platforms, the cursor height is 26 for a default Material 3 text field (font size is 16, text field height is 24, as specified on M3 spec).

Why the current cursor height is 26 on Apple platforms? :
- Cursor height defaults to `preferredLineHeight` (which is fontSize * lineHeight).
- Material 3 default text style for `TextField` has a font size of 16 and a line height of 1.5.
- Cursor height is increased by 2 on iOS and macOS.

In order to make progress we should answer the following questions:
1. Is this cursor height wrong or WAI?
2. Does setting default cursor height to `preferredLineHeight` is something we are willing to change?
3. Does cursor height and selection highlight height should be the same?

For reference, a video illustrating current default cursor height and default selection highlight height:

https://github.com/flutter/flutter/assets/840911/6afef77c-5446-4f63-b6d3-20c81e9cada1

**Comment by bleroux** [comment] 2024-04-09 09:17
While migrating InputDecorator tetss, I found that in addition to the cursor being too tall on Apple platforms, the label is wrongly posiitoned on desktop (Visual density is ignored).

Filed https://github.com/flutter/flutter/pull/146488.

**Closed** 2024-04-09 21:11 UTC
Labels: a: text input, framework, f: material design, has reproducible steps, P1, team-design, triaged-design, found in release: 3.16, found in release: 3.18
