### ISSUE TITLE
[video_player] Add support for changing the uri of the video

### ISSUE THREAD

**Issue by VictorUvarov** [flutter/flutter#120219] opened 2023-02-07 18:23 UTC
**Usecase**: Video players are memory intense for screens like a feed of posts. Modern apps reuse just 1 video player instance for the screen. Currently the flutter video player plugin hasn't implemented this functionality. I've currently working on implementing this feature in our app. Just wanted to create this Issue to track if the team has this item planned or is open to a PR to extend the video player functionality.

Android exoplayer has [setMediaItem](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#setMediaItem(com.google.android.exoplayer2.MediaItem)): Clears the playlist, adds the specified [MediaItem](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/MediaItem.html) and resets the position to the default position.

iOS AVplayer has [replaceCurrentItem](https://developer.apple.com/documentation/avfoundation/avplayer/1390806-replacecurrentitem): The new item for the player object to play.

The web video player has the [src attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video): I believing just changing the src attribute will resest and change the video.

**Comment by danagbemava-nc** [comment] 2023-02-08 07:14
Hi @VictorUvarov, I believe this is a duplicate of https://github.com/flutter/flutter/issues/44690. 

Feel free to share your findings in the issue linked above and yes PRs are always welcome. 

Closing this as a duplicate of the issue linked above. 

If you disagree, leave a comment below and I will reopen this. 

Thank you

**Closed by danagbemava-nc** 2023-02-08 07:14 UTC
Labels: in triage
