### ISSUE TITLE
Regression on several benchmarks...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#83427] opened 2021-05-26 17:18 UTC
Looks like hotReloadDevFSSyncMilliseconds [dashboard](https://flutter-flutter-perf.skia.org/e/?begin=1621453742&end=1622035443&keys=X9002f78bc50bc60a2d3a4d160effcfb0&requestType=0&xbaroffset=24270), FirstRecompileTime, FistRestartTime, SecondRestartTime, hotReloadDevFSSyncMilliseconds, hotReloadDevFSSyncMillisecondsAfterChange, and hotReloadMillisecondsToFrame [dashboard](https://flutter-flutter-perf.skia.org/e/?begin=1621892352&end=1621972628&keys=X346920f5c94803f176991dc27644e937&num_commits=50&request_type=1&xbaroffset=24269) have all regressed. 

The culprit commit is hard to identify. It's around https://github.com/flutter/flutter/pull/82991 or https://github.com/flutter/plugins/pull/3972, but I really don't believe that either of these are the culprit (certainly not the second, and I don't think the first, either). I think a bisect will be necessary.

**Comment by jonahwilliams** [comment] 2021-05-26 17:36
#82991 did slightly change how some of the hot reload file operations were performed and is a likely candidate. @chingjun could you investigate?

**Comment by chingjun** [comment] 2021-05-26 19:57
I can reproduce this with #82991 being applied.

Narrowed down to run_hot.dart:1258 in https://github.com/flutter/flutter/pull/82991/files

I think it's because it created one more object in an inner loop.

**Comment by GaryQian** [comment] 2021-05-27 01:59
Fixed by https://github.com/flutter/flutter/pull/83437

**Closed by GaryQian** 2021-05-27 01:59 UTC
Labels: P0, engine, perf: speed, severe: performance, severe: regression, t: hot reload, tool
