### ISSUE TITLE
Flutter Commands Never Finish

### ISSUE THREAD

**Issue by SSashaSStartsev** [flutter/flutter#17967] opened 2018-05-28 14:41 UTC
## Steps to Reproduce

1. Install Flutter on Windows
2. Put in the right Path
3. Run any Flutter command in the console, including help and doctor
4. Wait forever. Consumes 24% of CPU though.

## Logs
none

**Comment by DanTup** [comment] 2018-05-28 17:14
How did you install Flutter? If you use the [zip version](https://storage.googleapis.com/flutter_infra/releases/beta/windows/flutter_windows_v0.4.4-beta.zip) and run `console.bat` then type `flutter doctor` in there, does it work there?

**Comment by DanTup** [comment] 2018-05-28 17:28
Glad you got it sorted. I'll close this since the issue is resolved, though it'd be good to understand what's wrong with the zip so if you're happy to debug a little more so we might be able to avoid others hitting this, please shout!

**Closed by DanTup** 2018-05-28 17:28 UTC

**Comment by DanTup** [comment] 2018-05-28 17:39
There's a similar report at https://github.com/flutter/flutter/issues/17742 which suggests rthis might be permissions - if you've put it in `Program Files` it won't work properly without `Admin Privileges`.
