### ISSUE TITLE
120 hz fresh rate support?

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#70561] opened 2020-11-15 09:53 UTC
Hi, I don't know if Flutter support 120 Hz fresh rate or not, but on my Samsung Galaxy 20+ the animation in flutter not as smooth as native apps.

It's that because of fresh rate issue on my screen?

**Comment by volskaya** [comment] 2020-11-15 14:27
Flutter doesn't set a high refresh rate preferred display mode.
Here's a package that lets you do it - https://pub.dev/packages/flutter_displaymode, or if you're comfortable with native android, you could set it yourself in MainActivity.

**Comment by jinfagang** [comment] 2020-11-16 09:19
@volskaya thanks. Look like a solution.

But I got another question: my phone's system using 120 Hz, why flutter doesn't fit my system settings? I though it's not controlled by flutter itself but should adapt to system, isn't it?

**Comment by TahaTesser** [comment] 2020-11-16 13:14
Hi @jinfagang 
Like @volskaya mentioned, this can be done using the package. 
Why a package?
Please read this comment https://github.com/flutter/flutter/issues/35162#issuecomment-607387634
duplicate of https://github.com/flutter/flutter/issues/35162
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-11-16 13:14 UTC

**Comment by xster** [comment] 2021-07-26 19:56
Since this is the most searchable issue, just wanted to close the loop. Flutter doesn't need to explicitly enable any frame rates or request any frame rates. Generally, Flutter will follow the vsync signals at any rate the OS sends them, whether it's 60Hz, 90 or 120. Flutter also doesn't need to signal to the OS that it needs a higher or lower frame rate. Generally, the OS will increase the FPS on user input such as any gestures on the screen and automatically lower the FPS after a few seconds.  

The big caveat is that individual OEMs can choose to do something different. And there, Flutter, like native Android apps, can't entirely predict or control what the OEMs do. The plugin above https://pub.dev/packages/flutter_displaymode could be tried to see if the OEMs respond to explicit requests to change the FPS. But it may not work. For instance, OnePlus (see https://github.com/flutter/flutter/issues/78117) ignores system calls to change the FPS, and places where it turns on higher FPS may be hardcoded as a whitelist.
