### ISSUE TITLE
change foregroundColor in appBar(material ui 3) does not change the default leading icon color

### ISSUE THREAD

**Issue by 1057437122** [flutter/flutter#116771] opened 2022-12-09 11:06 UTC
when I was using material ui 2, change forgroundColor in appBar options means to change the color of default leading icon, but it doesnot work in material ui 3.
below is my code:
```
import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/container.dart';
import 'package:flutter/src/widgets/framework.dart';

class SecondRoute extends StatelessWidget {
  const SecondRoute({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('leading color'),
        foregroundColor: Colors.red,// it works in material 2, but not in 3
       
      ),
      body: Center(
        child: Text(
            '''the forground color is set to Colors.red, but the color of leading icon is still black->
            appBar: AppBar(
        title: Text('leading color'),
        foregroundColor: Colors.red, // this works in Material ui 2
        iconTheme: IconThemeData(
          color: Colors.red,
        ),
        actionsIconTheme: IconThemeData(
          color: Colors.red,
        ),
      ),
            '''),
      ),
    );
  }
}

```
and this is my test repository:  [appbar default leading color](https://github.com/1057437122/material3appbarleadingiconcolor.git)

**Comment by darshankawar** [comment] 2022-12-09 12:55
Thanks for the report @1057437122 
The expected behavior seems to be occuring on latest master after running your code with `useMaterial3: true`:

<img width="338" alt="Screenshot 2022-12-09 at 6 21 42 PM" src="https://user-images.githubusercontent.com/67046386/206707119-7d180c1e-f7fa-4580-a67a-0d0f8f2ccd7e.png">

On latest stable though, I see the current behavior you reported:

<img width="321" alt="Screenshot 2022-12-09 at 6 15 58 PM" src="https://user-images.githubusercontent.com/67046386/206707172-5710d247-c88f-42bc-95a1-79c068907125.png">

Since this works as expected on latest master, I am going ahead and closing this as fixed. It will most probably be available on stable's next release. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-12-09 12:55 UTC
Labels: in triage
