### ISSUE TITLE
Invalid height calculate on android device webview_flutter 4.7.0 

### ISSUE THREAD

**Issue by karanSman** [flutter/flutter#151070] opened 2024-06-30 20:30 UTC
### Steps to reproduce

i used runJavaScriptReturningResult on ios it is giving correct height as 64 where as on android it is showing 669

### Expected results

Correct height calculation

### Actual results

height issue on android

### Code sample

class _WebviewHtmlTextState extends State<WebviewHtmlText> {
  late final WebViewController _webController;
  double? webViewHeight;

  @override
  void initState() {
    super.initState();
    // #docregion platform_features
    late final PlatformWebViewControllerCreationParams params;
    if (WebViewPlatform.instance is WebKitWebViewPlatform) {
      params = WebKitWebViewControllerCreationParams(
        allowsInlineMediaPlayback: true,
        mediaTypesRequiringUserAction: const <PlaybackMediaTypes>{},
      );
    } else {
      params = const PlatformWebViewControllerCreationParams();
    }

    final WebViewController webController =
        WebViewController.fromPlatformCreationParams(params);
    if (webController.platform is AndroidWebViewController) {
      (webController.platform as AndroidWebViewController)
          .setMediaPlaybackRequiresUserGesture(true);
    }

    webController
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(Color(0xffF5FAFF))
      ..loadRequest(Uri.dataFromString(
              IhwUtils.addMetaInHead(widget.htmlText!),
              mimeType: 'text/html',
              encoding: Encoding.getByName('utf-8'))
          ,)
      ..addJavaScriptChannel('messageHandler',
          onMessageReceived: (JavaScriptMessage message) async {
        print('message from the web view=\"${message.message}\"');
      })
      ..setNavigationDelegate(
        NavigationDelegate(
          onNavigationRequest: (request) {
            if (request.url.startsWith('https://www.youtube.com/')) {
              Get.toNamed<dynamic>(Routes.YOUTUBE_PLAYER.routePath,
                  arguments: request.url);
              return NavigationDecision.prevent;
            } else if (Uri.tryParse(request.url)?.hasAbsolutePath ?? false) {
              Get.toNamed<dynamic>(Routes.WEB_VIEW.name, parameters: {
                'web_url': request.url,
                'title': '',
                'landscape': 'false',
                'fullscreen': 'false'
              });
              return NavigationDecision.prevent;
            }
            return NavigationDecision.navigate;
          },
          onPageFinished: (String url) async {
            // Add some delay before evaluate
            await Future<dynamic>.delayed(const Duration(milliseconds: 500));
            var _height =  await webController.runJavaScriptReturningResult(
                  'document.body.offsetHeight;');
            setState(() {
              webViewHeight = (_height as num).toDouble();
            });
          },
        ),
      );

    _webController = webController;
  }
  
  class IhwUtils {
  // add meta tag in head tag of html for ios
  static String addMetaInHead(String htmlString) {
  
      if (htmlString.contains('<head>')) {
        htmlString = htmlString.replaceAll(RegExp('<head>'),
            '<head><meta name="viewport" content="width=device-width, initial-scale=1.0">');
      } else {
        htmlString =
            '<html><head><meta name="viewport" content="width=device-width,user-scalable=no, initial-scale=1.0">' +
                htmlString +
                '</head></html>';
      }
    
    return htmlString;
  }
}

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-07-01 08:59
Duplicate of https://github.com/flutter/flutter/issues/151054.

**Closed by huycozy** 2024-07-01 08:59 UTC
Labels: in triage
