### ISSUE TITLE
Glitch occures when app is in app switcher

### ISSUE THREAD

**Issue by yasincidem** [flutter/flutter#21921] opened 2018-09-16 19:05 UTC
I am running flutter app from the repository [https://github.com/yasincidem/flutterApp](https://github.com/yasincidem/flutterApp) but the glitch occurs on ZTE BLADE V7 LITE(API 23)  independent from the which flutter app running.

![flutter-issue](https://user-images.githubusercontent.com/13544246/45599671-7aea3f00-b9f8-11e8-8972-3900844ac9d3.gif)

## Log when app is in app switcher

``` 
D/ActivityThread( 5795): ACT-AM_ON_PAUSE_CALLED ActivityRecord{7966e0d 
oken=android.os.BinderProxy@ba301c2 {com.example.educateapp/com.example.educateapp.MainActivity}}
D/ActivityThread( 5795): ACT-PAUSE_ACTIVITY handled : 3 / android.os.BinderProxy@ba301c2
V/ActivityThread( 5795): Finishing stop of ActivityRecord{7966e0d token=android.os.BinderProxy@ba301c2 {com.example.educateapp/com.example.educateapp.MainActivity}}: show=false win=com.android.internal.policy.PhoneWindow@2b5aef7
V/PhoneWindow( 5795): DecorView setVisiblity: visibility = 4 ,Parent =ViewRoot{35b6aca com.example.educateapp/com.example.educateapp.MainActivity,ident = 0}, this =com.android.internal.policy.PhoneWindow$DecorView{248de09 I.E...... R.....ID 0,0-720,1280}
D/ActivityThread( 5795): ACT-STOP_ACTIVITY_HIDE handled : 0 / android.os.BinderProxy@ba301c2
I/SurfaceView( 5795): updateWindow -- onWindowVisibilityChanged, visibility = 4, this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}

I/SurfaceView( 5795): Changes: creating=false format=false size=false visible=true left=false top=false mUpdateWindowNeeded=false mReportDrawNeeded=false redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=false, this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}
I/SurfaceView( 5795): Cur surface: Surface(name=null)/@0xa6c6758, this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}
I/SurfaceView( 5795): New surface: Surface(name=null)/@0xdb500b1, vis=false, frame=Rect(0, 0 - 720, 1280), this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}
I/SurfaceView( 5795): Callback --> surfaceDestroyed, this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}
I/SurfaceView( 5795): surfaceDestroyed callback +, this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}
D/Surface ( 5795): Surface::disconnect(this=0x9f431e00,api=1)
D/GraphicBuffer( 5795): unregister, handle(0x9e621620) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
I/[MALI][Gralloc]( 5795): [-]r_hnd(0x9e621620), client(49), share_fd(66)
D/GraphicBuffer( 5795): unregister, handle(0x9e61ff00) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
I/[MALI][Gralloc]( 5795): [-]r_hnd(0x9e61ff00), client(49), share_fd(67)
D/GraphicBuffer( 5795): unregister, handle(0x9e61f780) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
I/[MALI][Gralloc]( 5795): [-]r_hnd(0x9e61f780), client(49), share_fd(71)
D/Surface ( 5795): Surface::disconnect(this=0x9f431e00,api=1)
I/SurfaceView( 5795): surfaceDestroyed callback -, this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}
V/SurfaceView( 5795): Layout: x=0 y=0 w=720 h=1280, frame=Rect(0, 0 - 720, 1280), this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}


D/Surface ( 5795): Surface::disconnect(this=0x9f434800,api=1)
D/GraphicBuffer( 5795): unregister, handle(0x9e61f320) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
I/[MALI][Gralloc]( 5795): [-]r_hnd(0x9e61f320), client(49), share_fd(65)
D/GraphicBuffer( 5795): unregister, handle(0xb473ec00) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
I/[MALI][Gralloc]( 5795): [-]r_hnd(0xb473ec00), client(49), share_fd(68)
E/Surface ( 5795): getSlotFromBufferLocked: unknown buffer: 0x9e620c20
D/mali_winsys( 5795): [MALI] win=0x9f434808, native_buffer=0xb473f1a8, fd=-1
D/GraphicBuffer( 5795): unregister, handle(0x9e620c20) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
I/[MALI][Gralloc]( 5795): [-]r_hnd(0x9e620c20), client(49), share_fd(69)
D/Surface ( 5795): Surface::disconnect(this=0x9f434800,api=1)
I/SurfaceView( 5795): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}
I/SurfaceView( 5795): updateWindow -- onWindowVisibilityChanged, visibility = 8, this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}
I/SurfaceView( 5795): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}
I/SurfaceView( 5795): updateWindow -- OnPreDrawListener, mHaveFrame = true, this = io.flutter.view.FlutterView{a435f72 VFED..... .F....I. 0,0-720,1280}
I/System  ( 5795): FinalizerDaemon: finalize objects = 36

```

```

     >flutter analyze
      Analyzing educateapp...
      No issues found! (ran in 32.8s)

```

    [√] Flutter (Channel beta, v0.7.3, on Microsoft Windows [Version 10.0.17134.285], locale tr-TR)
    • Flutter version 0.7.3 at C:\src\flutter
    • Framework revision 3b309bda07 (3 weeks ago), 2018-08-28 12:39:24 -0700
    • Engine revision af42b6dc95
    • Dart version 2.1.0-dev.1.0.flutter-ccb16f7282

    [!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\yasin_000\AppData\Local\Android\sdk1
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Users\yasin_000\AppData\Local\Android\sdk1
    • Java binary at: C:\Users\yasin_000\Desktop\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

    [√] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

    [√] Android Studio (version 3.1)
    • Android Studio at C:\Users\yasin_000\Desktop\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

    [!] IntelliJ IDEA Community Edition (version 2016.2)
    • IntelliJ at C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

    [!] IntelliJ IDEA Ultimate Edition (version 2017.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

    [√] VS Code, 32-bit edition (version 1.27.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.18.0

    [√] Connected devices (1 available)
    • ZTE BLADE V7 LITE • 0123456789ABCDEF • android-arm • Android 6.0 (API 23)

**Comment by zoechi** [comment] 2019-02-14 16:00
What is the "glitch" about?

**Comment by zoechi** [comment] 2019-02-14 16:02
Is this a duplicate of #2766 ?

**Comment by yasincidem** [comment] 2019-02-15 20:02
I updated flutter on dev channel, built the default flutter app in release and debug but the issue still exists.
Yes, it looks this is a duplicate of #2766

`>flutter --version`

`
Flutter 1.2.1 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (17 hours ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)`

**Comment by zoechi** [comment] 2019-02-17 13:09
Duplicate of #2766

**Closed by zoechi** 2019-02-17 13:09 UTC
Labels: a: fidelity, engine, framework, ▣ platform-android
