### ISSUE TITLE
OCR doesn't work correctly.

### ISSUE THREAD

**Issue by RenaSki** [flutter/flutter#83296] opened 2021-05-24 20:38 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.0.6 at C:\flutter_windows_2.0.6-stable\flutter
    • Framework revision 1d9032c7e1 (4 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\sakai017\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.

C:\Users\sakai017>flutter create bug
Recreating project bug...
Running "flutter pub get" in bug...                              1,520ms
Wrote 3 files.

All done!
In order to run your application, type:

  $ cd bug
  $ flutter run

To enable null safety, type:

  $ cd bug
  $ dart migrate --apply-changes

Your application code is in bug\lib\main.dart.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
I would like to see the characters scanned by OCR.
**Actual results:** 
 I get an error below.
D/skia    (19838): onFlyCompress
W/DynamiteModule(19838): Local module descriptor class for com.google.android.gms.vision.dynamite.ocr not found.
I/DynamiteModule(19838): Considering local module com.google.android.gms.vision.dynamite.ocr:0 and remote module com.google.android.gms.vision.dynamite.ocr:0
D/TextNativeHandle(19838): Cannot load feature, fall back to load dynamite module.
W/DynamiteModule(19838): Local module descriptor class for com.google.android.gms.vision.ocr not found.
I/DynamiteModule(19838): Considering local module com.google.android.gms.vision.ocr:0 and remote module com.google.android.gms.vision.ocr:0
E/Vision  (19838): Error loading module com.google.android.gms.vision.ocr optional module true: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
W/DynamiteModule(19838): Local module descriptor class for com.google.android.gms.vision.dynamite.ocr not found.
I/DynamiteModule(19838): Considering local module com.google.android.gms.vision.dynamite.ocr:0 and remote module com.google.android.gms.vision.dynamite.ocr:0

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.0.6 at C:\flutter_windows_2.0.6-stable\flutter
    • Framework revision 1d9032c7e1 (4 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\sakai017\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 90.0.818.56

! Doctor found issues in 1 category.

```

</details>

**Comment by TahaTesser** [comment] 2021-05-25 11:22
Hi @RenaSki 
It seems you're using some third-party package to get use OCR 
`com.google.android.gms.vision.ocr` 

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated repository
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-25 11:22 UTC
Labels: in triage
