### ISSUE TITLE
Fix obsolete gradle warnings

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#26544] opened 2019-01-14 20:43 UTC
Currently the main `flutter.gradle` file contains a couple of deprecations that will throw warnings in Android Studio 3.3 with the latest gradle plugin.
```
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: Called from:<flutterpath>/packages/flutter_tools/gradle/flutter.gradle:394

WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: Called from: /<flutterpath>/packages/flutter_tools/gradle/flutter.gradle:406
```

Appropriate output from `flutter doctor`:

```
[✓] Flutter (Channel master, v1.1.10-pre.52, on Linux, locale en_US.UTF-8)
    • Flutter version 1.1.10-pre.52 at /opt/google/flutter
    • Framework revision d22cc77d27 (87 minutes ago), 2019-01-14 14:14:48 -0500
    • Engine revision fea645b801
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 1c9eb3cef8)
```

**Comment by afamobius** [comment] 2019-01-25 15:47
not that the upgrade is reverted , the warning is back

**Comment by dnfield** [comment] 2019-04-08 23:22
Reopening since this got reverted.

**Comment by benedicte69** [comment] 2019-04-10 16:56
Thanks for reopening,
Strangely if I follow this link and copy the licences directory of Android SDK to my flutter SDK, the warming is no longer appearing
https://developer.android.com/studio/intro/update#download-with-gradle
hope it can help

**Comment by benedicte69** [comment] 2019-04-10 17:08
it seems to settle the missing  Gradle version 4.10.1 files ! Whaou...Please check on your side if it works and tell me if it is at least the good way to fix the issue because it had taken me time to find among all the releases which one could do something. Thanks for your feedback

**Comment by benedicte69** [comment] 2019-04-11 23:19
Unfortunately, the error came back BUT:
Here are the lines that will have to be 'updated':
\flutter\packages\flutter_tools\gradle\flutter.gradle:400

else {                    dependsOn variant.mergeAssets                    dependsOn "clean${variant.mergeAssets.name.capitalize()}"                    into variant.mergeAssets.outputDir                }


 \flutter\packages\flutter_tools\gradle\flutter.gradle:422
else {                variant.outputs[0].processResources.dependsOn(copyFlutterAssetsTask)            }
    Le mercredi 10 avril 2019 à 19:09:36 UTC+2, Benedicte <notifications@github.com> a écrit :  
 
 
it seems to settle the missing Gradle version 4.10.1 files ! Whaou...Please check on your side if it works and tell me if it is at least the good way to fix the issue because it had taken me time to find among all the releases which one could do something. Thanks for your feedback

**Comment by benedicte69** [comment] 2019-04-11 23:21
Unfortunately, the error came back BUT:
Here are the lines that will have to be 'updated':
\flutter\packages\flutter_tools\gradle\flutter.gradle:400

else {                    dependsOn variant.mergeAssets                    dependsOn "clean${variant.mergeAssets.name.capitalize()}"                    into variant.mergeAssets.outputDir                }


 \flutter\packages\flutter_tools\gradle\flutter.gradle:422
else {                variant.outputs[0].processResources.dependsOn(copyFlutterAssetsTask)            }

**Comment by benedicte69** [comment] 2019-04-12 00:14
ERROR: The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
root project 'android' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

**Comment by benedicte69** [comment] 2019-04-12 12:45
`            ------------------------------------------------------------
            Project :app
            ------------------------------------------------------------

            INTERNAL__CHECKED_MINIMUM_PLUGIN_VERSIONS: true
            allprojects: [project ':app']
            android: com.android.build.gradle.internal.dsl.BaseAppModuleExtension_Decorated@158c480c
			
			(...)
			kotlin: org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension_Decorated@1483cb0c
            kotlin_version: 1.2.71
            layout: org.gradle.api.internal.file.DefaultProjectLayout@3359878b
			`

**Comment by chunhunghan** [comment] 2019-05-22 02:14
Face the same issue too, gradle version is 3.3.1

**Comment by chunhunghan** [comment] 2019-05-23 01:39
Works fine after migrate referenced package to AndroidX. 
Thank you for your help.

**Comment by iftee939** [comment] 2019-05-23 10:44
Got the Same issue, gradle version 3.4.1

**Comment by benedicte69** [comment] 2019-05-24 14:52
thank you,
may 24 2019, using AS, gradle should be 5.1.1:
16:48:29.050 29 info flutter.tools            Gradle 5.1.1

    Le jeudi 23 mai 2019 à 12:46:02 UTC+2, iftee939 <notifications@github.com> a écrit :  
 
 
Got the Same issue, gradle version 3.4.1

**Comment by micsan13br** [comment] 2019-07-23 15:13
This fixed it for me, in android\build.gradle (and version 1.3 also didn't work):

ext.kotlin_version = '1.3.41' 

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.0'
    }

**Comment by goksoy66** [comment] 2019-07-28 14:30
> Works fine after migrate referenced package to AndroidX.
> Thank you for your help.

Thank you very much @chunhunghan ! For almost 10 days, I was trying to solve the above mentioned problem. It's fixed finally. Thank you.

**Comment by therichiekumar** [comment] 2019-09-16 14:56
I face same issue
 
Gradle - 5.4.1
FLutter - 1.9.1

**Comment by FineTillYouCameAlong** [comment] 2019-10-08 11:56
This is ridiculous. Why do we have to deal with this? Gradle is such cancer.

**Comment by giovanniantonaccio** [comment] 2019-10-08 20:55
Does anyone has an update about this issue?

I'm still facing the same error:
```
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app
```

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

```

```
buildscript {
    ext.kotlin_version = '1.3.41'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.2'
    }
}
```

**Comment by dnfield** [comment] 2019-10-08 21:06
We plan to fix this.  That said, it's not quite as dire as it seems.  For now it will block you from upgrading the Android Gradle plugin come 2020, but you could continue to use the current one.

We expect that by the time that is the case, we will have removed the obsolete/deprecated API usages.

/cc @blasten who may have more details.

**Comment by benedicte69** [comment] 2019-10-08 21:13
That is just a 'WARNING:' they should deal with it by te end of the year I think... I hope.My concern is more about the gradle which has to be frequently updated, in Android Studio it is possible to keep it update, in VS I do not know but in VS gradle is always obsolete'

    Le mardi 8 octobre 2019 à 22:57:50 UTC+2, Giovanni Antonaccio <notifications@github.com> a écrit :  
 
 
Does anyone has an update about this issue?

I'm still facing the same error:
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: app
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

buildscript {
    ext.kotlin_version = '1.3.41'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.2'
    }
}

**Comment by benedicte69** [comment] 2019-10-08 21:13
Thanks
    Le mardi 8 octobre 2019 à 23:09:27 UTC+2, Dan Field <notifications@github.com> a écrit :  
 
 
We plan to fix this. That said, it's not quite as dire as it seems. For now it will block you from upgrading the Android Gradle plugin come 2020, but you could continue to use the current one.

We expect that by the time that is the case, we will have removed the obsolete/deprecated API usages.

/cc @blasten who may have more details.

**Comment by giovanniantonaccio** [comment] 2019-10-08 21:45
Thanks for the update guys!

**Comment by blasten** [comment] 2019-10-09 04:47
This issue is already fixed on the master channel and it will be available in the next stable release.

**Closed by blasten** 2019-10-09 04:47 UTC
Labels: t: gradle, tool

**Comment by nohli** [comment] 2019-10-09 07:05
@blasten 

You fixed both

> API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'

and

> API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'

in master channel? :)

**Comment by yann007new** [comment] 2019-10-15 11:25
open: gradlew.bat in your project
C:\Users\ETERNEL\Desktop\your_project\android\gradlew.bat
after an automatic download, I restarted the project and everything is fine now. I hope you would have the same luck as me.

**Comment by mctrivia** [comment] 2019-10-21 08:31
> open: gradlew.bat in your project
> C:\Users\ETERNEL\Desktop\your_project\android\gradlew.bat
> after an automatic download, I restarted the project and everything is fine now. I hope you would have the same luck as me.

I tried this but I get 

	Starting a Gradle Daemon (subsequent builds will be faster)

	> Configure project :app
	WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
	It will be removed at the end of 2019.
	For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
	To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
	WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
	It will be removed at the end of 2019.
	For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
	To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
			 *********************************************************
	WARNING: This version of package_info will break your Android build if it or its dependencies aren't compatible with AndroidX.
			 See https://goo.gl/CP92wY for more information on the problem and how to fix it.
			 This warning prints for all Android build failures. The real root cause of the error may be unrelated.
			 *********************************************************

in reply

**Comment by seunbanwo** [comment] 2019-11-05 01:37
> This issue is already fixed on the master channel and it will be available in the next stable release.

Any update on this release?
