### ISSUE TITLE
flutter_admob is causing my app to crash on iOS

### ISSUE THREAD

**Issue by mjaffa-figure** [flutter/flutter#23927] opened 2018-11-05 03:53 UTC
flutter_admob after showing a reward video sometimes freezes the app or crashes it. I don't get any logs just says disconnected device. On Android I can watch ad after ad over and over and it works just fine.

This is happening on AdMob versions firebase_admob: ^0.5.7 and above. I have tried the latest.

**Comment by 5ummit** [comment] 2018-11-05 11:29
Had this problem before, they updated the docs take a look in https://firebase.google.com/docs/admob/ios/quick-start

<img width="256" alt="screenshot 2018-11-05 at 13 28 57" src="https://user-images.githubusercontent.com/33470998/47995702-d2ef1900-e0fe-11e8-9690-7c4fd0d06feb.png">

**Comment by mjaffa-figure** [comment] 2018-11-05 14:40
@5ummit 
That doesn't help. I am integrating this through flutter, shouldn't have to do those steps.
These are the instructions for flutter https://pub.dartlang.org/documentation/firebase_admob/latest/

Works great on Android, and I get ads showing up on iOS. If they click my reward button like 3 times in a row, or click on the privacy policy for the ad that takes them out of the app and comes back. Then after dismissing the ad or trying to display another one the app either crashes or freezes.

**Comment by zoechi** [comment] 2018-11-07 07:16
Please add the output of `flutter doctor -v`.

**Comment by mjaffa-figure** [comment] 2018-11-07 14:42
flutter doctor -v
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel master, v0.10.3-pre.123, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.10.3-pre.123 at /Users/matthewjaffa/flutter
    • Framework revision 028087d0fc (8 hours ago), 2018-11-06 22:44:01 -0800
    • Engine revision 4f4c470d24
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/matthewjaffa/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[!] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone • d9617f604551fb2aacd0e26f1e87814572f3af67 • ios • iOS 11.4.1

! Doctor found issues in 1 category.

**Comment by apinprastya** [comment] 2019-01-17 11:38
It happen on me, but when I run debug on XCode I found the problem. The problem for video reward crash is because the MobileAdTargetingInfo is null.
So its better if the MobileAdTargetInfo set as require on Reward ads

**Comment by DaniyarGilimov** [comment] 2019-03-06 13:12
i'm facing with the same issue, i'm doing mobile game using unity3d. The same, when i watch the video (rewarded video) till the end and if after that i load one again, app crushes.
@apinprastya what you mean with MobileAdTargetingInfo? Is it .TagForChildDirectedTreatment(false) this one, or you mean another? I already added this .TagForChildDirectedTreatment(false)

**Comment by apinprastya** [comment] 2019-03-06 22:12
@DaniyarGilimov this thread is for flutter related issue, I don't really understand using admob on unity3d and never doing admob on IOS native. Maybe you have the same issue but you are in wrong room.

**Comment by 888MAXIMUS888** [comment] 2019-03-20 11:42
flutter_admob causes streams in the application when updating banner in ios. what could be the problem???

**Comment by kroikie** [comment] 2019-10-13 18:42
@mjaffa-figure

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/585. Any further collaboration will be done there.

**Comment by kroikie** [comment] 2019-10-14 17:55
Since `firebase_admob` issues require work on the Flutter side as well as the plugin side these issues will remain open here as well until resolved.

**Comment by iapicca** [comment] 2019-10-22 14:59
Hi @mjaffa-figure
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-14 15:12
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  

Thanks for your contribution.Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-14 15:12 UTC
Labels: p: firebase, p: firebase_admob, p: first party, plugin, waiting for customer response
