### ISSUE TITLE
My Flutter Android App don't navigate from splash screen to home screen

### ISSUE THREAD

**Issue by GnuaAruht** [flutter/flutter#144757] opened 2024-03-07 08:11 UTC
### Steps to reproduce

I run the my old project , it doesn't run properly. I upgraded Flutter to 3.19.2 .

### Actual results

The app can not redirect to Home page. 

### Logs

W/ViewRootImpl(11021): cancelAndRedraw cancelDueToPreDrawListener true cancelDraw false mDrewOnceForSync false isSyncRequest false

### Flutter Doctor output

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)

**Comment by huycozy** [comment] 2024-03-07 10:35
Hi @GnuaAruht 
The goal of this Github repo is not to assist in personal code or the whole package/plugin project but to improve Flutter framework reporting bugs or feature requests.

If you encounter behavior that you believe could be a Flutter framework bug, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that represents the problem and more information possible for investigation (device OS/model, crash log if any, etc).

Because the issue doesn't have much information to go forward, I'm going to close it. Once you update the issue, I will re-open it for further investigation. Thanks!

**Closed by huycozy** 2024-03-07 10:35 UTC
Labels: in triage
