### ISSUE TITLE
Stream Builder issue

### ISSUE THREAD

**Issue by HassanEm** [flutter/flutter#85025] opened 2021-06-22 08:30 UTC
Hi, I have a problem that I think is due to flutter
I have a class `media_pool` that holds a list of objects made up of a custom class `media` in which there is a stream builder in the custom class `media` that is responsible for showing the progress bar And when several objects are being streamed, the flutter gives this error `Bad state: Stream has already been listened to.` while they have separate stream builders and controllers and are not related to each other, and `broadcast` them is useless.

I write a demo code that show you what is happening

https://user-images.githubusercontent.com/24267954/122889671-3d106700-d358-11eb-822d-2d9091f7d7b1.mp4

and I catch this error after stream error when I use `Navigator.pop(context);` for closing the dialog
![Capture](https://user-images.githubusercontent.com/24267954/122893737-d8570b80-d35b-11eb-9c9d-711698709426.JPG)

`flutter doctor -v`
```[√] Flutter (Channel dev, 2.3.0-24.0.pre, on Microsoft Windows [Version 10.0.19041.1052], locale en-US)
    • Flutter version 2.3.0-24.0.pre at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2b9537c783 (11 days ago), 2021-06-11 22:11:53 -0700
    • Engine revision ddbac024d1
    • Dart version 2.14.0 (build 2.14.0-188.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Apps\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\hassa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.1052]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.54

! Doctor found issues in 1 category.
```
here complete minimal reproducible code sample
https://github.com/HassanEm/stream_builder_issue/

**Comment by darshankawar** [comment] 2021-06-22 09:28
@HassanEm 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.
Please note that the code sample should not have any 3rd party plugin code.

**Comment by HassanEm** [comment] 2021-06-23 12:49
> @HassanEm
> Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
> Thanks.
> Please note that the code sample should not have any 3rd party plugin code.

Thank you for your response. I created a repository that contains some code to display my case, I wish to be helpful.

**Comment by darshankawar** [comment] 2021-06-25 06:21
@HassanEm 
Is this for Windows desktop or web ? Does it occur on mobile too ?

Thanks.

**Comment by HassanEm** [comment] 2021-06-25 18:02
> @HassanEm
> Is this for Windows desktop or web ? Does it occur on mobile too ?
> 
> Thanks.

I try with Android(physical device), web(Chrome, Edge), and Desktop(Windows) and I got the same result.

**Comment by darshankawar** [comment] 2021-06-28 06:13
@HassanEm 
The error seems to be pointing to provider file:

```
An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:50831/CqA2H5wbLBQ=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:50831/CqA2H5wbLBQ=
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following StateError was thrown building Consumer<Media>(dependencies:
[_InheritedProviderScope<Media>]):
Bad state: Stream has already been listened to.

The relevant error-causing widget was:
  Consumer<Media>
  Consumer:file:///Users/dhs/Documents/NCFlutter/stream_builder_issue/lib/main.dart:37:32

```

As I see you are using `provider` plugin which is 3rd party. Can you try by removing / commenting out the plugin code and see if you still get same error / behavior ?

**Comment by HassanEm** [comment] 2021-06-28 10:53
> @HassanEm
> The error seems to be pointing to provider file:
> 
> ```
> An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:50831/CqA2H5wbLBQ=
> The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:50831/CqA2H5wbLBQ=
> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> The following StateError was thrown building Consumer<Media>(dependencies:
> [_InheritedProviderScope<Media>]):
> Bad state: Stream has already been listened to.
> 
> The relevant error-causing widget was:
>   Consumer<Media>
>   Consumer:file:///Users/dhs/Documents/NCFlutter/stream_builder_issue/lib/main.dart:37:32
> ```
> 
> As I see you are using `provider` plugin which is 3rd party. Can you try by removing / commenting out the plugin code and see if you still get same error / behavior ?

I used `valueNotifier` and `setState` to uptade my states but I got weird result in different cases
_Note: all cases developed with `ValueNotifier` and `setState`_
when I use `List<Media> = [];` directly without `MediaPool` it works fine
but when I use `MediaPool` to store my Medias I got `Badstate` error again. after that I change the `_medias.insert(0, media);` 
to `_medias.add(media);` it works, so I change my origin project with the `Provider` and I got that error again

**Comment by darshankawar** [comment] 2021-06-29 05:47
@HassanEm 
Sorry but I didn't understand what are you trying to implement exactly. From your code, I see you are using `ChangeNotifierProvider` which is coming from `provider` package. 

Can you try the same using core `StreamBuilder` example and see if you get same issue ? https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html#widgets.StreamBuilder.1

**Comment by HassanEm** [comment] 2021-07-14 06:36
> @HassanEm
> Sorry but I didn't understand what are you trying to implement exactly. From your code, I see you are using `ChangeNotifierProvider` which is coming from `provider` package.
> 
> Can you try the same using core `StreamBuilder` example and see if you get same issue ? https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html#widgets.StreamBuilder.1

I I also don't understand what happens because I encounter strange cases, but the general problem is that each object is different from the other object and should have different stream builders, but it seems that the system can not do it recognize.

I try to use it just like you said, hopefully we can figure out what going on.
by the way, thank you for your response

**Comment by TahaTesser** [comment] 2021-08-06 16:04
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-08-06 16:04 UTC
