### ISSUE TITLE
google_maps_flutter breaks image_picker

### ISSUE THREAD

**Issue by CAJazzer** [flutter/flutter#101470] opened 2022-04-07 03:07 UTC
Adding latest google_maps_flutter plugin causes image_picker to not return from pickImage().

**Comment by maheshmnj** [comment] 2022-04-07 08:19
Hi @CAJazzer, Thanks for filing the issue. What target platform is this issue on ?  Please share the output
 of `flutter doctor -v`.

**Comment by CAJazzer** [comment] 2022-04-13 18:51
My Platform info (Macbook Pro M1 Max)

[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-US)
    • Flutter version 2.10.4 at /Users/brazosm1max/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/brazosm1max/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/brazosm1max/Library/Android/sdk
    • Java binary at: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by maheshmnj** [comment] 2022-04-14 05:20
Thanks for the info @CAJazzer, 
> Add the following keys to your Info.plist file, located in <project root>/ios/Runner/Info.plist:

>NSPhotoLibraryUsageDescription - describe why your app needs permission for the photo library. This is called Privacy - Photo Library Usage Description in the visual editor.
NSCameraUsageDescription - describe why your app needs access to the camera. This is called Privacy - Camera Usage Description in the visual editor.
NSMicrophoneUsageDescription - describe why your app needs access to the microphone, if you intend to record videos. This is called Privacy - Microphone Usage Description in the visual editor.

Please ensure that you have added the above keys in the `info.plist` file. Also, Do you see any exceptions or error logs in the console when this issue occurs?

**Comment by CAJazzer** [comment] 2022-04-18 20:31
Thank you @[maheshmnj](https://github.com/maheshmnj).

I did have the required keys added to my Info.plist.  I am starting to wonder if this is an M1 chip issue as the same code is working correctly on my Intel Mac.

**Comment by maheshmnj** [comment] 2022-04-19 05:29
Thanks for the update @CAJazzer, Are you seeing this issue on a physical ios device or a simulator? if the latter, then you are very likely hitting this issue https://github.com/flutter/flutter/issues/82602. However, we would need more info such as  logs or errors, exceptions to confirm.

**Comment by CAJazzer** [comment] 2022-04-20 19:38
The combination of [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) and [image_picker](https://pub.dev/packages/image_picker) appears to be only an issue in the iOS simulator.  Testing on a iOS device worked properly.  Thank you for the timely help.

**Comment by maheshmnj** [comment] 2022-04-21 05:03
@CAJazzer  Do you get any exception or errors when the image is not returned by image picker?

**Comment by CAJazzer** [comment] 2022-04-21 19:19
No,  the code hangs at:
``
final XFile? pickedFile = await _picker.pickImage(
            source: source,
            maxWidth: maxWidth,
            maxHeight: maxHeight,
            imageQuality: quality,
          );
``

Performing a second requests yields the multiple request error:
``
code:"multiple_request"
details:null
message:"Cancelled by a second request"
stacktrace:null
hashCode:561512101
runtimeType:Type (PlatformException)
``

**Comment by maheshmnj** [comment] 2022-04-22 05:10
Thanks for the error log closing this issue as a duplicate of https://github.com/flutter/flutter/issues/82602

**Closed by maheshmnj** 2022-04-22 05:10 UTC
Labels: in triage
