### ISSUE TITLE
[web] ImageIcon inside AppBar renders incorrectly

### ISSUE THREAD

**Issue by woutervanwijk** [flutter/flutter#65616] opened 2020-09-11 08:32 UTC
When you put an ImageIcon inside an AppBar, it displays the icon on the bottom if you compile for web. On a device it looks ok.

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('bug?'),
        leading: ImageIcon(
          NetworkImage(
              'https://www.gstatic.com/images/branding/googlelogo/1x/googlelogo_color_92x36dp.png'),
          size: 20,
        ),
      ),
    );
  }
}
```

**Expected results:** 
Same rendering as in on a device

**Actual results:** 
Icon is displayed on the bottom 

<details>
  <summary>Logs</summary>

```
no need, it's just rendering
```

```
Analyzing iconimagebug...                                               
No issues found! (ran in 2.2s)
```

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale nl-NL)
    • Flutter version 1.21.0-9.2.pre at /Users/wouter/Library/flutter
    • Framework revision 81a45ec2e5 (2 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/wouter/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/wouter/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

**Comment by pedromassangocode** [comment] 2020-09-11 13:21
I was able to reproduce this on latest `beta` channel.

![Screen Shot 2020-09-11 at 14 20 08](https://user-images.githubusercontent.com/67424416/92930384-e9243980-f439-11ea-97fc-394750d91c8f.png)

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.21.0-9.2.pre at /Users/pedromassango/dev/SDKs/flutter_beta
    • Framework revision 81a45ec2e5 (2 weeks ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 11 Pro Max (mobile)  • 3DA251B5-C982-48C8-8FF5-C4D1DB21ED89 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • Web Server (web)            • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by yjbanov** [comment] 2020-09-15 21:36
The text is also pushed to the bottom. I'm wondering if there's an issue with text layout not reporting correct baseline or losing style information. /cc @mdebbar

**Comment by mdebbar** [comment] 2020-10-22 21:23
After investigation, I can confirm this is due to an SVG element not having a `position` attribute and adding a gap to the top (which is pushing the app bar title down).

This should've been fixed in https://github.com/flutter/engine/pull/21939 but got reverted in https://github.com/flutter/engine/pull/21986. cc @ferhatb I'm de-duplicating this issue with the one you fixed: https://github.com/flutter/flutter/issues/59451.

Duplicate of https://github.com/flutter/flutter/issues/59451

**Closed by mdebbar** 2020-10-22 21:23 UTC
Labels: assigned for triage, f: material design, found in release: 1.21, framework, has reproducible steps, platform-web
