### ISSUE TITLE
im getting the following  below error while using smart refresher

### ISSUE THREAD

**Issue by srinivasPaidisetti** [flutter/flutter#70562] opened 2020-11-15 10:37 UTC
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during perform layout():
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 582 pos 12: '_pendingDimensions': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
When the exception was thrown, this was the stack: 
#2      ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:582:12)
#3      ScrollPositionWithSingleContext.applyNewDimensions (package:flutter/src/widgets/scroll_position_with_single_context.dart:108:11)
#4      RenderSliverRefresh.performLayout (package:pull_to_refresh/src/internals/slivers.dart:189:39)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
#6      RenderSliverRefresh.layout (package:pull_to_refresh/src/internals/slivers.dart:147:13)
...
The following RenderObject was being processed when the exception was fired: RenderSliverRefresh#63d9b relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...  needs compositing
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 550.0, overlap: -0.8, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 550.0, remainingCacheExtent: 800.0, cacheOrigin: 0.0)
...  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
...    scrollExtent: 0.0
...    hidden
...    maxPaintExtent: 0.0
RenderObject: RenderSliverRefresh#63d9b relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
  needs compositing
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.forward, scrollOffset: 0.0, remainingPaintExtent: 550.0, overlap: -0.8, crossAxisExtent: 411.4, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 550.0, remainingCacheExtent: 800.0, cacheOrigin: 0.0)
  geometry: SliverGeometry(scrollExtent: 0.0, hidden, maxPaintExtent: 0.0)
    scrollExtent: 0.0
    hidden
    maxPaintExtent: 0.0
...  child: RenderRotatedBox#5bb2b relayoutBoundary=up2 NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, -0.0) (can use size)
...    constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...    size: Size(411.4, 48.0)
...    child: RenderFractionalTranslation#3a27d relayoutBoundary=up3 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...      size: Size(411.4, 48.0)
...      translation: Offset(0.0, -1.0)
...      transformHitTests: true
...      child: RenderTransform#03e5d relayoutBoundary=up4 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...        layer: TransformLayer#b1353 DETACHED
...          engine layer: TransformEngineLayer#5f3e2
...          offset: Offset(0.0, 0.0)
...          transform: [0] 0.0,0.0,0.0,205.4
[1] 0.0,0.0,0.0,60.5
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        size: Size(411.4, 48.0)
...        transform matrix: [0] 1.0,0.0,0.0,0.0
[1] 0.0,1.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: center
...        textDirection: ltr
...        transformHitTests: true
...        child: RenderPositionedBox#92e05 relayoutBoundary=up5 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
...          size: Size(411.4, 48.0)
...          alignment: topCenter
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by iapicca** [comment] 2020-11-15 17:12
@srinivasPaidisetti 
can you provide you `flutter doctor -v `and most importantly a minimal reproducible code sample?

**Comment by srinivasPaidisetti** [comment] 2020-11-16 05:48
> @srinivasPaidisetti
> can you provide you `flutter doctor -v `and most importantly a minimal reproducible code sample?

 Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1198], locale en-IN)
    • Flutter version 1.22.3 at C:\Users\ASUS\flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

**Comment by pedromassangocode** [comment] 2020-11-16 08:04
Hi @srinivasPaidisetti 
From what I can see, the issue is related to a 3rd party package (**pull_to_refresh**) rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/peng8350/flutter_pulltorefresh).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-16 08:04 UTC
