### ISSUE TITLE
Extract DiagnostictsProperty & co as a package

### ISSUE THREAD

**Issue by rrousselGit** [flutter/flutter#48511] opened 2020-01-09 17:01 UTC
Hello!

The request is pretty straightforward:

Could we extract things like `DiagnostricsPropety` and the related interfaces/mixins like `DiagnosticsNode` in a package separate from Flutter (which Flutter could then re-export)?

#### Motivation

There are situations where we have a class that is in a package that (voluntarily) _doesn't_ depend on Flutter (like Mobx's `Store`, bloc's `Bloc`, or anything custom made).

There's no issue with that, but when plugged onto Flutter we may want to make it pretty on Flutter dev-tool  – which is done with `Diagnostics`.

But since `Diagnostics` depends on Flutter, this is not feasible (or at least not in a natural way).

**Comment by dnfield** [comment] 2020-01-30 17:42
I'm going to close this as a duplicate of https://github.com/flutter/flutter/issues/29230

**Comment by dnfield** [comment] 2020-01-30 17:43
(I know this is slightly more focused on a few classes from foundation rather than all of foundation, but there's  more context at the other issue and its' basically the same problem)

**Closed by dnfield** 2020-01-30 17:42 UTC
Labels: framework, proposal
