### ISSUE TITLE
Background colors when use 'Material 3' mode

### ISSUE THREAD

**Issue by yegor-pelykh** [flutter/flutter#113480] opened 2022-10-15 12:50 UTC
When use 'Material 3' theme mode, background colors look wrong.

## Steps to Reproduce

1. Turn on Material 3 theme mode by setting `useMaterial3` flag of `ThemeData` to true
2. Set any `background`  color of the current color scheme

**Expected results:** The Scaffold background and dialog background sets to the mentioned above background color.

**Actual results:** The Scaffold background and dialog background sets to gray color.

**Temporary workaround:** Set the `backgroundColor`, `dialogBackgroundColor`, `scaffoldBackgroundColor` of `ThemeData` to that `background` color in color scheme.

Flutter version: 3.3.4

Related to #91605.

**Comment by yegor-pelykh** [comment] 2022-10-21 08:16
Example:
<details><summary>main.dart</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  static const colorSchemeDark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFFB688),
    onPrimary: Color(0xFF512400),
    primaryContainer: Color(0xFF733600),
    onPrimaryContainer: Color(0xFFFFDBC7),
    secondary: Color(0xFF7CD0FF),
    onSecondary: Color(0xFF00344A),
    secondaryContainer: Color(0xFF004C69),
    onSecondaryContainer: Color(0xFFC4E7FF),
    tertiary: Color(0xFF6ADC9B),
    onTertiary: Color(0xFF00391F),
    tertiaryContainer: Color(0xFF00522F),
    onTertiaryContainer: Color(0xFF87F9B5),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF1F1B18),
    onBackground: Color(0xFFFFDEA0),
    surface: Color(0xFF1F1B18),
    onSurface: Color(0xFFFFDEA0),
    surfaceVariant: Color(0xFF52443C),
    onSurfaceVariant: Color(0xFFD7C3B8),
    outline: Color(0xFF9F8D83),
    onInverseSurface: Color(0xFF1F1B18),
    inverseSurface: Color(0xFFFFDEA0),
    inversePrimary: Color(0xFF974800),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFFFB688),
  );

  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      darkTheme: ThemeData(
        useMaterial3: true,
        colorScheme: MyApp.colorSchemeDark,
      ),
      themeMode: ThemeMode.dark,
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Wrong background example'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showDialog(
              context: context,
              builder: (context) {
                return const AlertDialog(
                  content: Text('''
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore 
et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut 
aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse 
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in 
culpa qui officia deserunt mollit anim id est laborum.'''),
                );
              });
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}

```
</p>
</details>

The output of `flutter doctor -v`:
<details><summary>output</summary>
<p>

```console
[√] Flutter (Channel stable, 3.3.5, on Microsoft Windows [Version 10.0.22621.674], locale ru-UA)
    • Flutter version 3.3.5 on channel stable at C:\SDK\Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (2 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\SDK\AndroidSdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\Chromium\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\Yegor\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.674]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 106.0.1370.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</p>
</details>

As you can see, the Scaffold background is colored #303030, which is not the background color from the dark theme fully described in the example.
Additionally, if you click on the fab in the bottom right corner, a simple AlertDialog will open with the color #424242, which is also not the correct background color from the theme.

Temporary workaround in my app is to define additional flutter theme colors:

```dart
      darkTheme: ThemeData(
        useMaterial3: true,
        colorScheme: MyApp.colorSchemeDark,
        dialogBackgroundColor: MyApp.colorSchemeDark.background,
        scaffoldBackgroundColor: MyApp.colorSchemeDark.background,
      ),
```

But these colors should already be based on the color scheme of the application, without these additional definitions.

**Comment by TahaTesser** [comment] 2022-10-21 12:36
Hi @yegor-pelykh 
Thanks for raising this issue, this is a known [issue](https://github.com/flutter/flutter/issues/113480) and it should be fixed by https://github.com/flutter/flutter/pull/112666.

I can confirm it with the following code:
```dart
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        colorScheme: const ColorScheme.light().copyWith(
          background: Colors.amber,
        ),
      ),
```

<img src="https://user-images.githubusercontent.com/48603081/197196982-efa54437-f24a-49e9-9078-e689b6b9697d.png" height="450" />



Closing as duplicate of https://github.com/flutter/flutter/issues/111520

**Closed by TahaTesser** 2022-10-21 12:36 UTC
Labels: in triage
