### ISSUE TITLE
firebase

### ISSUE THREAD

**Issue by Tokikko** [flutter/flutter#43491] opened 2019-10-25 08:24 UTC
## Steps to Reproduce

1. ...
2. ...
3. ...

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
```

```
```

```
```

**Comment by iapicca** [comment] 2019-10-25 08:40
Hi @Tokikko 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it

**Closed by iapicca** 2019-10-25 08:40 UTC
