### ISSUE TITLE
Exception: Build process failed

### ISSUE THREAD

**Issue by ansarizafar** [flutter/flutter#57641] opened 2020-05-20 06:21 UTC
I have created a new application and when I try to run it I am getting an exception. Commands to reproduce

````
flutter create desktop
flutter run -d Linux

````
Output of flutter doctor -v command

````
[✓] Flutter (Channel master, 1.19.0-2.0.pre.114, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-2.0.pre.114 at /home/zafar/flutter
    • Framework revision 1cfd792a38 (31 hours ago), 2020-05-18 18:18:16 -0500
    • Engine revision 4b1a70e6a2
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/opt/android-sdk-linux
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk-linux
    • Java binary at: /home/zafar/softwares/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 9.0.0 (https://github.com/llvm-mirror/llvm
      c62b24f070c9a4bb1a76409e623042a740cac4cd)
    • cmake version 3.17.2
    • ninja version 1.10.0

[!] Android Studio (version 2.3)
    • Android Studio at /home/zafar/softwares/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • Linux      • Linux      • linux-x64      • Linux
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 76.0.3809.100

! Doctor found issues in 1 category.

````

Output of flutter run --verbose command

````
[  +17 ms] executing: [/home/zafar/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +55 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 1cfd792a380034e1cbd0a4c067b00165222b1f35
[   +1 ms] executing: [/home/zafar/flutter/] git tag --contains HEAD
[ +251 ms] Exit code 0 from: git tag --contains HEAD
[   +4 ms] executing: [/home/zafar/flutter/] git describe --match *.*.*-*.*.pre --first-parent
--long --tags
[ +211 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.19.0-1.0.pre-114-g1cfd792
[  +13 ms] executing: [/home/zafar/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/zafar/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +93 ms] executing: [/home/zafar/flutter/] git rev-parse --abbrev-ref HEAD
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +79 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +30 ms] executing: /usr/local/opt/android-sdk-linux/platform-tools/adb devices -l
[ +167 ms] List of devices attached
[  +20 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +139 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag,
or use '-d
                    all' to act on all devices.
[ +106 ms] Linux      • Linux      • linux-x64      • Linux
[   +1 ms] Web Server • web-server • web-javascript • Flutter Tools
[        ] Chrome     • chrome     • web-javascript • Google Chrome 76.0.3809.100
[  +16 ms] "flutter run" took 527ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:333:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:777:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:694:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZoned (dart:async/zone.dart:1550:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:684:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
#23     _rootRunUnary (dart:async/zone.dart:1198:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#30     _rootRun (dart:async/zone.dart:1190:13)
#31     _CustomZone.run (dart:async/zone.dart:1093:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


````

**Comment by imeDevelopers** [comment] 2020-05-20 09:07
@ansarizafar
Open your android studio , from the tool bar select plugins .. and search for flutter plugin and dart plugin and install them .. no you foxed this problem ..

**Comment by VladyslavBondarenko** [comment] 2020-05-20 10:24
@ansarizafar 
what the exception do you have? provide your `flutter run -d Linux --verbose` log

**Comment by ansarizafar** [comment] 2020-05-20 10:32
@VladyslavBondarenko  here is the output of flutter run -d Linux --verbose
````
[  +26 ms] executing: [/home/zafar/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +203 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 1cfd792a380034e1cbd0a4c067b00165222b1f35
[        ] executing: [/home/zafar/flutter/] git tag --contains HEAD
[+1650 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] executing: [/home/zafar/flutter/] git describe --match *.*.*-*.*.pre --first-parent
--long --tags
[ +364 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.19.0-1.0.pre-114-g1cfd792
[  +13 ms] executing: [/home/zafar/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/zafar/flutter/] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +123 ms] executing: [/home/zafar/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +120 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +54 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +77 ms] executing: /usr/local/opt/android-sdk-linux/platform-tools/adb devices -l
[+3210 ms] List of devices attached
                    * daemon not running. starting it now at tcp:5037 *
                    * daemon started successfully *
[   +7 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +901 ms] Generating
/home/zafar/projects/dart/desktop/android/app/src/main/java/io/flutter/plugins/GeneratedPluginReg
istrant.java
[ +168 ms] Starting incremental build...
[   +4 ms] Initializing file store
[  +27 ms] Skipping target: gen_localizations
[  +11 ms] complete
[   +7 ms] Launching lib/main.dart on Linux in debug mode...
[   +8 ms] /home/zafar/flutter/bin/cache/dart-sdk/bin/dart
/home/zafar/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/zafar/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental
--target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
/tmp/flutter_tools.QMNKHT/flutter_tool.HIVZHQ/app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,kee
p-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[  +66 ms] Building Linux application...
[  +19 ms] <- compile package:desktop/main.dart
[   +5 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
/home/zafar/projects/dart/desktop/linux
[+2680 ms] -- Configuring done
[ +803 ms] -- Generating done
[ +118 ms] -- Build files have been written to:
/home/zafar/projects/dart/desktop/build/linux/debug
[   +5 ms] executing: ninja -C build/linux/debug install
[   +9 ms] ninja: Entering directory `build/linux/debug'
[+25074 ms] [1/13] Generating
/home/zafar/projects/dart/desktop/linux/flutter/ephemeral/libflutter_linux_glfw.so,
flutter_export.h, flutter_glfw.h, flutter_messenger.h, flutter_plugin_registrar.h,
/home/zafar/projects/dart/desktop/linux/flutter/ephemeral/cpp_client_wrapper_glfw/engine_method_r
esult.cc,
/home/zafar/projects/dart/desktop/linux/flutter/ephemeral/cpp_client_wrapper_glfw/standard_codec.
cc,
/home/zafar/projects/dart/desktop/linux/flutter/ephemeral/cpp_client_wrapper_glfw/plugin_registra
r.cc,
/home/zafar/projects/dart/desktop/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_window_
controller.cc, _phony_
[   +2 ms] [  +18 ms] executing: [/home/zafar/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [  +49 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [        ] 1cfd792a380034e1cbd0a4c067b00165222b1f35
[        ] [   +1 ms] executing: [/home/zafar/flutter/] git tag --contains HEAD
[        ] [ +250 ms] Exit code 0 from: git tag --contains HEAD
[        ] [   +4 ms] executing: [/home/zafar/flutter/] git describe --match *.*.*-*.*.pre
--first-parent --long --tags
[        ] [ +218 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long
--tags
[        ] [        ] 1.19.0-1.0.pre-114-g1cfd792
[        ] [  +21 ms] executing: [/home/zafar/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[        ] [  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/home/zafar/flutter/] git ls-remote --get-url origin
[        ] [   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +88 ms] executing: [/home/zafar/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [  +90 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] [   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] [   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] [  +22 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required,
skipping update.
[   +4 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping
update.
[        ] [   +8 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping
update.
[        ] [ +187 ms] Initializing file store
[        ] [  +65 ms] Done initializing file store
[        ] [ +123 ms] Skipping target: gen_localizations
[        ] [+6610 ms] Skipping target: kernel_snapshot
[        ] [+10781 ms] Skipping target: unpack_linux
[        ] [ +299 ms] debug_bundle_linux_assets: Starting due to
{InvalidatedReason.outputMissing}
[        ] [ +504 ms] debug_bundle_linux_assets: Complete
[        ] [ +491 ms] Persisting file store
[        ] [  +16 ms] Done persisting file store
[        ] [  +22 ms] build succeeded.
[        ] [  +12 ms] "flutter assemble" took 19,215ms.
[+5299 ms] [2/5] Building CXX object
CMakeFiles/desktop.dir/flutter/generated_plugin_registrant.cc.o
[ +460 ms] [3/5] Building CXX object CMakeFiles/desktop.dir/main.cc.o
[+1059 ms] [4/5] Linking CXX executable desktop
[        ] FAILED: desktop 
[        ] : && /home/zafar/Downloads/clang_9.0.0/bin/clang++  -g
CMakeFiles/desktop.dir/main.cc.o CMakeFiles/desktop.dir/window_configuration.cc.o
CMakeFiles/desktop.dir/flutter/generated_plugin_registrant.cc.o  -o desktop
-Wl,-rpath,/home/zafar/projects/dart/desktop/linux/flutter/ephemeral:
flutter/libflutter_wrapper_app.a
/home/zafar/projects/dart/desktop/linux/flutter/ephemeral/libflutter_linux_glfw.so && :
[        ] CMakeFiles/desktop.dir/main.cc.o: In function `(anonymous
namespace)::RunHeadless(std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> > > > const&)':
[   +1 ms] /home/zafar/projects/dart/desktop/linux/main.cc:20: undefined reference to
`flutter::FlutterEngine::FlutterEngine()'
[        ] /home/zafar/projects/dart/desktop/linux/main.cc:21: undefined reference to
`flutter::FlutterEngine::Start(std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>,
std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> > > > const&)'
[   +1 ms] /home/zafar/projects/dart/desktop/linux/main.cc:24: undefined reference to
`flutter::FlutterEngine::RunEventLoopWithTimeout(std::chrono::duration<long, std::ratio<1l,
1000l> >)'
[        ] /home/zafar/projects/dart/desktop/linux/main.cc:26: undefined reference to
`flutter::FlutterEngine::~FlutterEngine()'
[        ] clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
[        ] ninja: build stopped: subcommand failed.
[  +21 ms] Building Linux application... (completed in 35.6s)
[   +2 ms] Exception: Build process failed
[   +8 ms] "flutter run" took 40,237ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:797:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:694:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZoned (dart:async/zone.dart:1550:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:684:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
#23     _rootRunUnary (dart:async/zone.dart:1198:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#30     _rootRun (dart:async/zone.dart:1190:13)
#31     _CustomZone.run (dart:async/zone.dart:1093:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)



[  +16 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +11 ms] Shutdown hooks complete

````

**Comment by VladyslavBondarenko** [comment] 2020-05-20 12:43
@ansarizafar 
this should be already fixed in current master,
closing as duplicate of https://github.com/flutter/flutter/issues/57533,
if you are still experiencing the error - comment in the mentioned issue

**Closed by VladyslavBondarenko** 2020-05-20 12:43 UTC
Labels: in triage

**Comment by sonuishaq67** [comment] 2020-07-13 11:43
Hey I'm getting this error while adding linux support to a existing app for android 
It uses firebase

**Comment by mdev88** [comment] 2020-08-06 15:42
Same here. I am currently using dev trying to run the app from Android Studio. Curious thing is if I manually run `flutter run -d linux` it works fine, it only fails if I use the green play button in Android Studio.

```
[+1477 ms] Exception: Build process failed
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:460:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:869:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
$ flutter --version
Flutter 1.21.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision f25bd9c55c (3 weeks ago) • 2020-07-14 20:26:01 -0400
Engine • revision 99c2b3a245
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
```

**Comment by sonuishaq67** [comment] 2020-08-06 15:51
Hey @mdev88 try ```flutter pub get && flutter pub upgrade```  in the root directory of your project 
it might be the automatic pub detection failures

**Comment by mdev88** [comment] 2020-08-06 15:55
Hey @sonuishaq67 , I tried that, same result.

Note that if I run `flutter run -d linux` in the console the app runs correctly. 

I also tried adding `-d linux` to 'Aditional arguments' in the run/debug config in Android Studio, but no luck...

**Comment by sonuishaq67** [comment] 2020-08-06 16:09
Ahh @mdev88 it's not a problem innit if It works fine on the terminal,
anyway I guess you have to wait for the experts to arrive

**Comment by mdev88** [comment] 2020-08-06 16:34
... I don't think they're coming. This issue was closed...

**Comment by stuartmorgan** [comment] 2020-08-08 06:00
> Hey I'm getting this error while adding linux support to a existing app for android

It is extremely unlikely that you are getting this error; it would mean you used a *very* specific broken version of Flutter master from May to add Linux support to your project.

If what you mean is that your build says "Exception: Build process failed" (I've fixed the title of this issue so it's not that), literally any issue that causes a build failure will say that (and have the same Dart `throwToolExit` stack). All that means is that the native build step failed.

The interesting part is earlier in the log, where the actual native build error is. You should file new bugs with the details of your native build failures.
