### ISSUE TITLE
Binding has not yet been initialized. compute isolate issue.

### ISSUE THREAD

**Issue by SpirikleOfficial** [flutter/flutter#132481] opened 2023-08-14 09:31 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. open a flutter plugin project for the default code.
2. instead of calling invokeMethodChannel (of getPlatformVersion) directly, call it in a compute isolate.
3. Also I have initiaized in main.dart of example folder:

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

### Expected results

There should be no error when calling the function from compute isolate.

### Actual results

I am getting error which I have shown in the logs section.

### Code sample

<details><summary>Code sample of main.dart in the example folder for a flutter plugin project</summary>

```dart
import 'dart:io';
import 'dart:ui';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'dart:async';

import 'package:flutter/services.dart';
**/// your plugin name here when reproducing**
import 'package:scanclan_filters/scanclan_filters.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  // const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Photo Filter Example'),
        ),
        body: Center(
          child: Container(
            height: 100,
            width: 100,
            color: Colors.blue,
            child: MaterialButton(
              onPressed: () async {
                var value = await compute(testFunctionForPlatformVersion, 0);
              },
            ),
          ),
        ),
      ),
    );
  }
}

///function to test
FutureOr<dynamic> testFunctionForPlatformVersion(int dummyvalue) async {
  ScanclanFilters _scanclanFiltersPlugin = ScanclanFilters();
  String result;

  try {
    result = await _scanclanFiltersPlugin.getPlatformVersion();
  } on PlatformException {
    print('ERROR!!!!!!!');
    return "error";
  }
  return result;
}
``` 

</details>

### Logs

<details><summary>Logs</summary>

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Binding has not yet been initialized.
E/flutter (20377): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
E/flutter (20377): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
E/flutter (20377): In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
E/flutter (20377): If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.
E/flutter (20377): #0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:284:9)
E/flutter (20377): #1      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:366:6)
E/flutter (20377): #2      ServicesBinding.instance (package:flutter/src/services/binding.dart:54:54)
E/flutter (20377): #3      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:254:45)
E/flutter (20377): #4      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:289:15)
E/flutter (20377): #5      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:472:12)
E/flutter (20377): #6      MethodChannelScanclanFilters.getPlatformVersion (package:scanclan_filters/scanclan_filters_method_channel.dart:15:29)
E/flutter (20377): #7      ScanclanFilters.getPlatformVersion (package:scanclan_filters/scanclan_filters.dart:11:45)
E/flutter (20377): #8      testFunctionForPlatformVersion (package:scanclan_filters_example/main.dart:136:43)
E/flutter (20377): #9      _IsolateConfiguration.applyAndTime.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:108:21)
E/flutter (20377): #10     Timeline.timeSync (dart:developer/timeline.dart:160:22)
E/flutter (20377): #11     _IsolateConfiguration.applyAndTime (package:flutter/src/foundation/_isolates_io.dart:106:21)
E/flutter (20377): #12     _spawn (package:flutter/src/foundation/_isolates_io.dart:127:67)
E/flutter (20377): #13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
E/flutter (20377): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```
flutter doctor -v
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22621.2134], locale en-CA)
    • Flutter version 3.3.9 on channel stable at C:\src\flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (9 months ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.81.0)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • 22021211RI (mobile) • 15693259 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.22621.2134]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 115.0.5790.171
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 115.0.1901.203

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2023-08-14 12:27
Hi @SpirikleOfficial. Thanks for filing this issue. This seems to be similar to https://github.com/flutter/flutter/issues/130570 and per this https://github.com/flutter/flutter/issues/130570#issuecomment-1654208398, I'd be closing as a duplicate of https://github.com/flutter/flutter/issues/119207.
If you disagree, kindly write in the comments and I'd reopen this.
Thank you!

**Closed by dam-ease** 2023-08-14 12:27 UTC
Labels: in triage
