### ISSUE TITLE
Missing Material Icons

### ISSUE THREAD

**Issue by atulmodi** [flutter/flutter#71425] opened 2020-11-30 18:22 UTC
Flutter is not using the latest set of material Icons. Icons like "groups" icon are missing. Can we update flutter to use the latest set of Icons please?

**Comment by YazeedAlKhalaf** [comment] 2020-11-30 18:32
@atulmodi  I have just checked and it seems the icons need an upgrade. I can do a Pull Request but need icons a list of icons to be added or the last version of icons that have been added.

**Comment by YazeedAlKhalaf** [comment] 2020-11-30 18:40
Found the way to update the icons but needs someone who has `@google.com` email to download `MaterialIcons-Regular.otf` and Generate the new codepoints list. For more info read this: [https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts-&-Icons](https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts-&-Icons)

**Comment by HansMuller** [comment] 2020-11-30 19:26
CC @willlarche

**Comment by YazeedAlKhalaf** [comment] 2020-12-01 06:26
I think this is a duplicate of #71233

**Comment by atulmodi** [comment] 2020-12-01 06:47
Marked closed as this is a duplicate of #71233

**Closed** 2020-12-01 06:47 UTC
Labels: f: material design, framework
