### ISSUE TITLE
Same ambient photo is getting displayed multiple times on holding the screen and swiping to next photo

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#60605] opened 2020-06-30 15:01 UTC
https://b.corp.google.com/issues/160119560.

cc @chinmaygarde who has commented on the upstream issue. Provisionally assigning this a P2.

**Comment by kf6gpe** [comment] 2020-06-30 17:31
We're looking to the submitting team to provide a reduced reproducible case.

**Comment by chinmaygarde** [comment] 2020-06-30 17:34
This seems to be caused by https://github.com/flutter/flutter/issues/11884 which leads to the page controller getting gesture offsets that are greater than the size of 1 page. Once the reduced test case confirms this, we can mark this issue as a duplicate of that one.

**Comment by Hixie** [comment] 2020-06-30 23:13
Awaiting reduced testcase.

**Comment by chinmaygarde** [comment] 2020-07-06 17:50
@kf6gpe Is prompting again for a reduced test case.

**Comment by chinmaygarde** [comment] 2020-07-13 17:44
Triage: Internally, this has been assigned to someone working on a reduced test case.

**Comment by chinmaygarde** [comment] 2020-07-20 17:38
Triage: No update. @kf6gpe if following up. Reducing priority.

**Comment by goderbauer** [comment] 2020-07-22 21:34
Reducing to P3 per previous comment and @kf6gpe.

**Comment by jonahwilliams** [comment] 2024-08-13 03:44
No reduced test case in many years, closing as a waste of time

**Closed by jonahwilliams** 2024-08-13 03:44 UTC
Labels: framework, engine, customer: dream (g3), P2, team-engine, triaged-engine
