### ISSUE TITLE
Memory Leak when animation is playing in iOS

### ISSUE THREAD

**Issue by roychan2016** [flutter/flutter#48066] opened 2020-01-02 10:08 UTC
@dnfield Unfortunately, only part of the problem has been fixed by the [above method](https://github.com/flutter/flutter/issues/47108).
You can see that the memory is still growing, but the memory shown in the instrument is not growing. My guess is that there is growth in the GPU part.
![image](https://user-images.githubusercontent.com/18565410/71661929-b1350480-2d8a-11ea-8f07-419e2a826a9c.png)
![image](https://user-images.githubusercontent.com/18565410/71661939-b8f4a900-2d8a-11ea-8369-3934e33b7e99.png)
I will continue to try to locate the problem, but the GPU memory problem is difficult to locate, I hope to get your help.（you can reproduces this problem by the same code）
Do you have some methods to locate GPU problems, can you share them?

**Comment by roychan2016** [comment] 2020-01-02 10:09
@dnfield

**Comment by kangwang1988** [comment] 2020-01-02 10:11
This issue is from xianyu @ Alibaba
and related to https://github.com/flutter/flutter/issues/47108

@zoeyfan  @dnfield

**Comment by dnfield** [comment] 2020-01-02 16:33
@liyuqian @brianosman fyi

**Comment by dnfield** [comment] 2020-01-02 22:20
@jason-simmons as well

**Comment by dnfield** [comment] 2020-01-03 17:46
I'm able to reproduce some strange memory usage increases in debug mode (in one test run, memory inexpicably jumped about 20MB at some point during the run?), but not in release mode.  I have not tried profile, but I suspect the issue would go away there as well.

@roychan2016 are you able to reproduce this when you run your app in release mode?

**Comment by dnfield** [comment] 2020-01-03 17:47
And to clarify - if this is debug mode only, we should fix it, but it will likely be prioritized lower than bugs that are affecting release applications :)

**Comment by ds84182** [comment] 2020-01-07 17:21
@dnfield Does it reproduce in jit release mode? If so, it might be the Dart VM doing code compilation in the background

**Comment by dnfield** [comment] 2020-01-07 18:11
@ds84182 that's what I'm thinkin gas well.  I only see memory usage increasing in JIT mode.

**Comment by MxSoul** [comment] 2020-01-08 03:53
@dnfield field we also reproduce it in release mode. But we can't locate the problem in release mode. 

We found that the number of layers was growing abnormally in debug mode. It might be the reason of memory growth.

LeakStack is here:
``` c++
   0 libsystem_malloc.dylib malloc
   1 libc++abi.dylib operator new(unsigned long)
   2 Flutter 0x100701a27
   3 Flutter 0x100710da3
   4 Flutter 0x100710edf
   5 Flutter 0x1007123cb
   6 Flutter 0x10071234b
   7 Flutter 0x100b57933
   8 Flutter 0x100c4e7cb
   9 Flutter 0x100c4a36f
  10 Flutter 0x100b0094b
  11 Flutter 0x100b9b7e3
  12 Flutter 0x100e033b7
  13 Flutter 0x1007352e7
  14 Flutter 0x10073ebaf
  15 Flutter 0x100746273
  16 Flutter 0x100743133
  17 Flutter 0x1006fbddb
  18 Flutter 0x10075ab8f
  19 Flutter 0x10070bac7
  20 Flutter 0x10070f1d3

Flutter
void std::__1::vector<std::__1::shared_ptr<flutter::Layer>, std::__1::allocator<std::__1::shared_ptr<flutter::Layer> > >::__push_back_slow_path<std::__1::shared_ptr<flutter::Layer> >(std::__1::shared_ptr<flutter::Layer>&&) (in Flutter) + 123
3
Flutter
flutter::SceneBuilder::PushLayer(std::__1::shared_ptr<flutter::ContainerLayer>) (in Flutter) + 59
4
Flutter
flutter::SceneBuilder::pushOffset(double, double) (in Flutter) + 147
5
Flutter
tonic::DartDispatcher<tonic::IndicesHolder<0ul, 1ul>, fml::RefPtr<flutter::EngineLayer> (flutter::SceneBuilder::*)(double, double)>::Dispatch(fml::RefPtr<flutter::EngineLayer> (flutter::SceneBuilder::*)(double, double)) (in Flutter) + 107
6
Flutter
void tonic::DartCall<fml::RefPtr<flutter::EngineLayer> (flutter::SceneBuilder::*)(double, double)>(fml::RefPtr<flutter::EngineLayer> (flutter::SceneBuilder::*)(double, double), _Dart_NativeArguments*) (in Flutter) + 135
7
Flutter
dart::NativeEntry::AutoScopeNativeCallWrapperNoStackCheck(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)) (in Flutter) + 139
8
Flutter
dart::InvokeNative(dart::Thread*, dart::Simulator*, void (*)(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*)), void (*)(_Dart_NativeArguments*), _Dart_NativeArguments*) (in Flutter) + 99
9
Flutter
dart::Simulator::Call(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*) (in Flutter) + 6579
10
Flutter
dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long) (in Flutter) + 851
11
Flutter
dart::Library::Invoke(dart::String const&, dart::Array const&, dart::Array const&, bool, bool) const (in Flutter) + 1367
12
Flutter
Dart_Invoke (in Flutter) + 1503
13
Flutter
flutter::Window::BeginFrame(fml::TimePoint) (in Flutter) + 267
14
Flutter
flutter::RuntimeController::BeginFrame(fml::TimePoint) (in Flutter) + 31
15
Flutter
flutter::Engine::BeginFrame(fml::TimePoint) (in Flutter) + 59
16
Flutter
flutter::Animator::BeginFrame(fml::TimePoint, fml::TimePoint) (in Flutter) + 427
17
Flutter
std::__1::function<void (fml::TimePoint, fml::TimePoint)>::operator()(fml::TimePoint, fml::TimePoint) const (in Flutter) + 43
18
Flutter
std::__1::__function::__func<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0, std::__1::allocator<flutter::VsyncWaiter::FireCallback(fml::TimePoint, fml::TimePoint)::$_0>, void ()>::operator()() (in Flutter) + 111
19
Flutter
fml::MessageLoopImpl::FlushTasks(fml::MessageLoopImpl::FlushType) (in Flutter) + 815
20
Flutter
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) + 31
```

**Comment by dnfield** [comment] 2020-01-08 05:03
Are you running a different application? I ran the application from https://github.com/flutter/flutter/issues/47108#issuecomment-565933430 on an iPhone X for 40 or so minutes in release mode, and noticed no memory growth whatsoever.

**Comment by dnfield** [comment] 2020-01-08 05:04
That stack makes it look like we're holding on to a shared pointer reference to a layer beyond what's needed - but I haven't observed that locally.

**Comment by MxSoul** [comment] 2020-01-08 13:53
@dnfield  I ran the application from #47108 (comment) on an iPhone 6 plus.

**Comment by MxSoul** [comment] 2020-01-08 14:30
@dnfield It can found some leak by iPhone 6 plus ( It can't be reproduce leak in other phone, but memory growth can reproduce in any iPhone )

![image](https://user-images.githubusercontent.com/20944001/71985500-a6d0aa00-3265-11ea-9862-7f7bbdbc9ef8.png)
I try to parser some stack. You can download by this [LeakStack](https://gw.alicdn.com/bao/uploaded/TB1ztpJtpY7gK0jSZKzXXaikpXa.zip?spm=a1z3i.a4.0.0.196deb1dpwKge6&file=TB1ztpJtpY7gK0jSZKzXXaikpXa.zip).

**Comment by dnfield** [comment] 2020-01-08 14:47
There are some known leaks from certificate/ssl usage, but I've seen them be stable and they've been hard to track down.  It's either in Boring SSL or the way dart is using it:  https://github.com/dart-lang/sdk/issues/36935

Are you sure that's not what you're seeing?  I don't see it grow since my patch linked in that issue, but we still do leak a small amount one time.

**Comment by MxSoul** [comment] 2020-01-09 02:50
@dnfield  This has nothing to do with SSL, because I can still duplicate the memory growth by replacing the image with a local resource.
After the repair, the memory growth in the instrument is very small, but in the memory statistics of Xcode, a significant increase can be seen. I think this means less CPU memory growth, but more GPU memory growth.
The above Stack seems to be related to the Layer. Is there any unexpected holding?

**Comment by dnfield** [comment] 2020-01-09 06:39
I still haven't been able to reproduce this.  /cc @liyuqian or @jason-simmons

**Comment by dnfield** [comment] 2020-01-09 06:40
Oh -  I also still have to try on an iPhone 6 though.

**Comment by MxSoul** [comment] 2020-02-12 11:11
@liyuqian  The leak looks like a cache for the layer.  If we know in advance that the layer must change, can we set it to not be cached.

**Comment by liyuqian** [comment] 2020-02-25 22:59
@MxSoul : if the layer isn't reused it should be freed automatically. If not, we should fix that, but I think we'll have to first focus on how to reproduce this leak. Since @dnfield failed to reproduce this leak in the master branch, I wonder what Flutter version did you use. Can you please share the result of `flutter doctor -v`?

**Comment by dnfield** [comment] 2020-03-18 20:40
@mxsoul - I'm still not able to reproduce this issue on master.  If you can share a sample application that leaks memory like this on latest commit in Flutter, I'd be happy to re-open this.  Since I can't reproduce it currently, I'm going to close this issue for now.

**Closed by dnfield** 2020-03-18 20:40 UTC
Labels: customer: gold, engine, perf: memory, severe: performance, waiting for customer response
