### ISSUE TITLE
Allow rebuilding suggestions for Searchbar manually

### ISSUE THREAD

**Issue by Chiggy-Playz** [flutter/flutter#149082] opened 2024-05-25 08:24 UTC
### Use case

Currently, the only way to rebuild the suggestions for a `SearchBar` (and by extension `SearchAnchor.bar`) is to update the `SearchController`'s value (as implemented by #134337). But this method of rebuilding cannot be used when there's we need to refresh the suggestions based on non-textual input. For example: using chips to filter the search further.
Example:

| Current Behaviour | Expected Behaviour (Using workaround) |
|--------|--------|
| <video src="https://github.com/flutter/flutter/assets/49774426/48c68b0d-830d-4101-9be0-89f29a1d5bcf"> | <video src="https://github.com/flutter/flutter/assets/49774426/6f747cca-fd29-4d74-811a-1fe81fc85fa2"> | 
| The suggestions only rebuild when the text changes or if the view is closed and opened again | The suggestions rebuild as soon as the chip is clicked |

Here's how GMail does it:
<video src="https://github.com/flutter/flutter/assets/49774426/3e3e597a-0fe4-4dd2-bb5c-75a035fbd603">
<details>
<summary>Code (With rebuilding issues)</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late SearchController _searchController;
  final FocusScopeNode focusNode = FocusScopeNode();
  bool? official;

  @override
  void initState() {
    super.initState();
    _searchController = SearchController();
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text("Searchbar Demo"),
        ),
        body: Padding(
          padding: const EdgeInsets.all(32),
          // This focus node is needed to prevent the search anchor from
          // stealing the focus and displaying the keyboard
          // https://github.com/flutter/flutter/issues/138099
          child: FocusScope(
            node: focusNode,
            onFocusChange: (value) {
              if (value) {
                focusNode.unfocus();
              }
            },
            child: SearchAnchor.bar(
              searchController: _searchController,
              viewBackgroundColor: Theme.of(context).scaffoldBackgroundColor,
              textInputAction: TextInputAction.search,
              suggestionsBuilder: (context, controller) {
                return [
                  Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: Row(
                      children: [
                        ActionChip(
                          label: Text(official == null
                              ? "Any"
                              : official!
                                  ? "Official"
                                  : "Unofficial"),
                          onPressed: () {
                            if (official == null) {
                              official = true;
                            } else if (official!) {
                              official = !official!;
                            } else {
                              official = null;
                            }
                          },
                        ),
                      ],
                    ),
                  )
                ];
              },
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary> Temporary workaround </summary>

We can force a rebuild by manually changing the controller's text value and resetting it. New `onPressed` callback:

```dart
onPressed: () {
  if (official == null) {
    official = true;
  } else if (official!) {
    official = !official!;
  } else {
    official = null;
  }
  controller.text = controller.text + " ";
  controller.text = controller.text.trim();
}
```
</details>

### Proposal

I propose a method on the `SearchController` which triggers a rebuild of the suggestions.

**Comment by huycozy** [comment] 2024-05-27 08:44
Thanks for the detailed proposal but there is already one similar issue to this at https://github.com/flutter/flutter/issues/148778. Closing this as a duplicate of that one.

**Closed by huycozy** 2024-05-27 08:44 UTC
Labels: in triage
