### ISSUE TITLE
Transform.rotate broken on iOS on Flutter 3.24.0

### ISSUE THREAD

**Issue by ericacentofanti** [flutter/flutter#153078] opened 2024-08-08 08:59 UTC
### Steps to reproduce

1. Create a new project
2. Execute a `Transform.rotate` with a `angle: pi` on iOS

### Expected results

The child widget should be mirrored on Y axis.

### Actual results

The child is not mirrored and is only moved outside its parent, but only on iOS. On Android and web it's working fine as you can see from the screenshot below.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Colors.black,
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              // The normal icon
              Container(
                color: Colors.yellow,
                child: const Icon(
                  Icons.arrow_back,
                  size: 16.0,
                  color: Colors.white,
                ),
              ),
              // The one that should be mirrored
              Transform.rotate(
                angle: pi,
                child: Container(
                  color: Colors.green,
                  child: const Icon(
                    Icons.arrow_back,
                    size: 16.0,
                    color: Colors.white,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot 2024-08-08 alle 10 55 42](https://github.com/user-attachments/assets/e1e7afe8-c3d0-489f-8f7f-ee415a37fcc0)

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6 23G80 darwin-arm64, locale it-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.92.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by ericacentofanti** [comment] 2024-08-08 09:07
A workaround that we have found right now is to use `Transform` with a matrix.

```dart
Transform(
  transform: Matrix4.identity()..rotateZ(pi),
  // Center point as half the size of the child
  origin: const Offset(20, 20),
  child: Container(
    color: Colors.green,
    child: const Icon(
      Icons.arrow_back,
      size: 40.0,
      color: Colors.white,
    ),
  ),
),
```

This problem is triggered only when you need mirroring and using `angle: pi` in `Transform.rotate` and `Transform.flip`.

**Comment by jonahwilliams** [comment] 2024-08-08 09:10
Duplicate of https://github.com/flutter/flutter/issues/153036

(The text is missing the transform in this case)

**Closed by jonahwilliams** 2024-08-08 09:10 UTC
