### ISSUE TITLE
flutter image_picker shows a choose file button on web

### ISSUE THREAD

**Issue by Dooardarshan** [flutter/flutter#109782] opened 2022-08-18 17:03 UTC
Is there any way to get rid of choose button on the page?
![ggw](https://user-images.githubusercontent.com/35467046/185453296-22dee8f8-b461-480e-ad4a-d7a3ea8831f9.png)

**Comment by maheshmnj** [comment] 2022-08-19 07:28
Hi @Dooardarshan, Can you please share a code sample that shows the unexpected button?

**Comment by Dooardarshan** [comment] 2022-08-19 09:27
This is the function:

 Future<void> _pickImage() async {
    ImagePicker _picker = ImagePicker();
    XFile? image = await _picker.pickImage(source: ImageSource.gallery);
    if (image != null) {
      var wi = await image.readAsBytes();
      setState(() {
        webImage = wi;
      });
    }
  }

Here is put it inside a Container
Container(
                  width: 200,
                  height: 200,
                  child: Image.memory(webImage, fit: BoxFit.fill))

**Comment by Dooardarshan** [comment] 2022-08-19 09:29
This is the function:

```
Future _pickImage() async {
ImagePicker _picker = ImagePicker();
XFile? image = await _picker.pickImage(source: ImageSource.gallery);
if (image != null) {
var wi = await image.readAsBytes();
setState(() {
webImage = wi;
});
}
}
```


Here is put it inside a Container
```
Container(
width: 200,
height: 200,
child: Image.memory(webImage, fit: BoxFit.fill))
```

**Comment by Dooardarshan** [comment] 2022-08-19 18:55
![image](https://user-images.githubusercontent.com/35467046/185687625-99ec9ca9-5a68-402d-9459-67cd85f0a38e.png)

Complete code:

```
import 'dart:typed_data';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'dart:io';
import 'package:image_picker/image_picker.dart';

class image_resize extends StatefulWidget {
  const image_resize({Key? key}) : super(key: key);

  @override
  _image_resizeState createState() => _image_resizeState();
}

class _image_resizeState extends State<image_resize> {
  File? _pickedImage;
  Uint8List webImage = Uint8List(8);
  Future<void> _pickImage() async {
    ImagePicker _picker = ImagePicker();
    XFile? image = await _picker.pickImage(source: ImageSource.gallery);
    if (image != null) {
      var wi = await image.readAsBytes();
      setState(() {
        webImage = wi;
      });
    }
  }


  @override
  Widget build(BuildContext context) {
    return Container(
      child: Row(
        children: [
          TextButton(
            child: Text(' choose image'),
            onPressed: () {
              _pickImage();
            },
          ),
          _pickedImage == null
              ? Container(
                  width: 200, height: 200, child: Text('Choose an Image'))
              : Container(
                  width: 200,
                  height: 200,
                  child: Image.memory(webImage, fit: BoxFit.fill))

        ],
      ),
    );
  }
}
```

![image](https://user-images.githubusercontent.com/35467046/185688117-643e1998-ea3c-4e01-94b6-c45c71e92686.png)

**Comment by maheshmnj** [comment] 2022-08-22 05:55
Thanks for the info @Dooardarshan, I cannot reproduce with your code sample.

<img width="939" alt="Screenshot 2022-08-22 at 11 20 47 AM" src="https://user-images.githubusercontent.com/31410839/185848452-67355557-c3b1-42b8-9835-e38139f30e43.png">
 
Have you modified `web/index.html` By any chance, (Ensure there is no input tag in `index.html` file)? Can you please share the `web/index.html`

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by oscarshaitan** [comment] 2022-08-30 18:12
I have the same in the past, My fix was to add a color on the page cuz there is no solution for this (that was the answer in the time closing all the issues about this)

**Closed** 2022-09-13 13:24 UTC
Labels: waiting for customer response, in triage
