### ISSUE TITLE
Renaming a file doesn't rename it in other files in VS Code

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#57376] opened 2020-05-16 12:09 UTC
I'm not sure where exactly to file it. When renaming a file in Android Studio it correctly renames it in every file—not in VS Code.

<details>
<summary>
Logs
</summary>

```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.73, on Mac OS X 10.15.4 19E287, locale es-ES)
    • Flutter version 1.19.0-2.0.pre.73 at /Users/tomas/Developer/flutter
    • Framework revision 32547dcc7e (18 hours ago), 2020-05-15 10:42:37 -0700
    • Engine revision 50e55cf69e
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • iPhone 11  • 8945646B-58CE-451E-82E8-487FB361872E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Web Server • web-server                           • web-javascript • Flutter Tools
    • Chrome     • chrome                               • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by DanTup** [comment] 2020-05-16 17:52
There's an open issue in the Dart-Code repo for this:

https://github.com/Dart-Code/Dart-Code/issues/548

I've been trying to progress it recently, but there are differences with how the VS Code and Dart analysis server APIs work that make it hard, so it'll need some server work first.

I'll close this as a dupe of the above - subscribe there for updates. Thanks!

**Closed by DanTup** 2020-05-16 17:52 UTC
