### ISSUE TITLE
Failed to attach a stencil buffer. Rendering will be skipped.

### ISSUE THREAD

**Issue by Clemy-beep** [flutter/flutter#73339] opened 2021-01-05 17:31 UTC
### Steps to Reproduce
1. Run flutter create bug.
2. cd bug
3. flutter run

**Expected results:**
The user interface is rendered correctly.

**Actual results:**
The user interface isn't rendered correctly:

- android
- windows x64

works if we change the size of the window or if we navigate in the application

```Flutter 1.26.0-2.0.pre.181 • channel master • https://github.com/flutter/flutter.git
Framework • revision be8b6bf071 (76 minutes ago) • 2021-01-05 11:04:03 -0500
Engine • revision 022bb11fa7
Tools • Dart 2.12.0 (build 2.12.0-179.0.dev)

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.26.0-2.0.pre.181, on Microsoft Windows [version 10.0.18363.1256], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.1)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (4 available)

• No issues found!
```
![image](https://user-images.githubusercontent.com/71656865/103678697-2467ec80-4f84-11eb-9894-1b4194fed51e.png)

**Comment by timsneath** [comment] 2021-01-05 22:58
Duplicate of #72632

**Closed by timsneath** 2021-01-05 22:58 UTC
