### ISSUE TITLE
[go_router] Dialog widget would build again when navigating a dialog then dismiss and push to another view

### ISSUE THREAD

**Issue by ininmm** [flutter/flutter#152906] opened 2024-08-06 03:11 UTC
### Steps to reproduce

1. Create a dialog GoRoute, and create a non-const dialog widget with a param.
2. From view A, navigate a dialog with params and do some async works.
3. After async work complete, dismiss dialog and navigate to view B.
4. The dialog would build again when push into view B.

### Expected results

There is unnessessary to build dialog widget again when navigate to another view.

### Actual results

Dialog widget would build again when navigate to another view.

Here is my GoRoute sample
```dart
  GoRoute(
    path: LoadingDialog.routePath,
    pageBuilder: (BuildContext context, GoRouterState state) {
      return DialogPage<void>(builder: (BuildContext context) {
        return const LoadingDialog();
      });
    },
  ),
  GoRoute(
    path: LoadingDialog.routePathWithParam,
    pageBuilder: (BuildContext context, GoRouterState state) {
      final text = state.extra as String;
      return DialogPage<void>(builder: (BuildContext context) {
        return LoadingDialog(
          text: text,
        );
      });
    },
  ),
```

I have noticed that if I create LoadingDialog as a const widget, everything works fine.
However if I create a dialog with construct params, the dialog would be rebuild when user dismiss dialog and navigate to another view.

See potentially related questions on [stackoverflow](https://stackoverflow.com/q/78573344/5643911) 

### Code sample

<details open><summary>Code sample</summary>

I have created a github sample and print logs to reproduce the bugs.

[here is the link](https://github.com/ininmm/sample)

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[log] didPush: is Page true
[log] FirstPage <= navigate to first page
[log] didPush: is Page true
[log] print Loading <= here is the loading dialog built
[log] didPush: is Page true
[log] SecondPage <= navigate to second page
[log] print Loading <= the loading dialog build again
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-08-06 10:05
Hi @ininmm, this is not a specific issue with dialog route as it also happens with PageRoute as well (you can try with MaterialPageRoute) and this is explained as an intended behavior, please see https://github.com/flutter/flutter/issues/132049#issuecomment-1673962209 and also https://github.com/flutter/flutter/issues/138708. Closing this as a duplicate of https://github.com/flutter/flutter/issues/132049.

**Closed by huycozy** 2024-08-06 10:05 UTC
Labels: in triage

**Comment by ininmm** [comment] 2024-08-08 03:25
Got it, and according to https://github.com/flutter/flutter/issues/132049#issuecomment-1673962209, I am curious why we need to rebuild the previous widget. 

@huycozy @chunhtai Could you explain why we need this behavior?
