### ISSUE TITLE
AnimatedSize is stuck after Navigator.push

### ISSUE THREAD

**Issue by illia-romanenko** [flutter/flutter#43749] opened 2019-10-29 20:22 UTC
## Steps to Reproduce

1. Create AnimatedSize widget - set long duration
2. Use Navigator to move to another screen before AnimatedSize is completed
3. Return back to original screen and notice that Animation is stuck 

Here is a very simple app to illustrate the point:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  var height = 0.0;

  void _incrementCounter() {
    setState(() {
      if (height == 0) {
        height = 200;
      } else {
        height = 0;
      }
    });
    Future.delayed(Duration(seconds: 1))
        .then((_) => Navigator.push(context, MaterialPageRoute(builder: (context) => Scaffold())));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AnimatedSize(
          vsync: this,
          duration: Duration(seconds: 5),
          child: Container(
            color: Colors.black,
            height: height,
            width: 100,
          )),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

**Target OS version/browser:iOS 13 simulator, Android 10**

## Logs

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A602, locale
    en-UA)
    • Flutter version 1.9.1+hotfix.4 at /Users/illia/flutter
    • Framework revision cc949a8e8b (5 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/illia/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

```

**Comment by pedromassangocode** [comment] 2020-08-18 13:36
Hi @illia-romanenko 
I cannot reproduce this issue on latest master channel. As you can see in the video bellow the animation continues after navigating away from the page where the same animation was started.

![slider](https://user-images.githubusercontent.com/67424416/90519395-dc286900-e15f-11ea-8dcc-93b371f5c43b.gif)

Closing this as fixed. If you disagree please feel free to comment and I will reopen it.
Thank you

<details>
<summary> flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-10.0.pre.138, on Mac OS X 10.15.6 19G2021,
    locale en)
    • Flutter version 1.21.0-10.0.pre.138 at
      /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 3562b3c0de (2 hours ago), 2020-08-18 01:46:02 -0400
    • Engine revision 02de4eb7ce
    • Dart version 2.10.0 (build 2.10.0-37.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.0.4
    • Dart plugin version 202.6397.47

[!] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.125

! Doctor found issues in 3 categories.
```
</details>

**Closed by pedromassangocode** 2020-08-18 13:36 UTC
Labels: a: animation, framework
