### ISSUE TITLE
Flutter doctor 'Unable to determine Android Studio version' Issue in Android Studio Hedgehog

### ISSUE THREAD

**Issue by burhanaksendir** [flutter/flutter#135662] opened 2023-09-28 09:33 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1- Open a terminal or command prompt.
2- Run the following command to check for the error:
`flutter doctor -v`

### Expected results

When running the flutter doctor command in Android Studio Hedgehog | 2023.1.1 Beta 6, I expect it to correctly determine the Android Studio version and provide information about the Flutter development environment without any errors. There should be no "Unable to determine Android Studio version" error, and the command should run smoothly.

### Actual results

When running the flutter doctor -v command in Android Studio Hedgehog | 2023.1.1 Beta 6, I am encountering the following error:

> Unable to determine Android Studio version.

### Code sample

`flutter doctor -v`

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.5, on macOS 14.0 23A344 darwin-arm64, locale
    tr-TR)
    • Flutter version 3.13.5 on channel stable at
      /Volumes/Media/Development/Flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (9 days ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Volumes/Media/Development/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Volumes/Media/Development/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • M iPhone (mobile) • 00008120-000E44E10393D01E • ios            • iOS
      17.0.2 21A351
    • macOS (desktop)        • macos                     • darwin-arm64   •
      macOS 14.0 23A344 darwin-arm64
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by dam-ease** [comment] 2023-09-28 11:36
Hi @burhanaksendir. Thanks for filing this. Currently upgrading to this version of Android Studio to reproduce this. Can you confirm this doesn't occur on other versions of Android Studio on your end?

**Comment by burhanaksendir** [comment] 2023-09-28 12:13
Hi @dam-ease 
Thanks. I did not encounter the "Unable to determine Android Studio version" error with Android Studio Giraffe | 2022.3.1. This issue started occurring after upgrading to Android Studio Hedgehog | 2023.1.1 Beta 6.

**Comment by dam-ease** [comment] 2023-09-29 08:15
Hi @burhanaksendir. Thanks for your response. I upgraded to Android Studio Hedgehog | 2023.1.1 Beta 6 and can reproduce this issue on my end as well.

<details><summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.0 22A380 darwin-arm64, locale
    en-NG)
    • Flutter version 3.13.6 on channel stable at
      /Users/damilolaalimi/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (2 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/damilolaalimi/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/damilolaalimi/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[!] Android Studio (version unknown)
    • Android Studio at /Users/damilolaalimi/Downloads/Android Studio
      Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        •
      android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro (mobile)      • 6548B0D1-7674-4306-9852-198C465F1104 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • iPhone 14 Pro Max (mobile)  • BB55E997-7F31-462D-B3B1-6B177D9B40C7 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                •
      darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)                • chrome                               •
      web-javascript • Google Chrome 117.0.5938.132

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
``` 

</p>
</details>

**Comment by navaronbracke** [comment] 2023-10-02 20:43
@andrewkolos Could it be that the tool gets confused about the Beta 6 release? I wouldn't think that the `2023.1.1` version would break it, since we look for the `jbr` folder from the 2022 versions onwards.

**Comment by andrewkolos** [comment] 2023-10-04 12:26
Hiya, I was able to reproduce this on macOS (same OS used in opening comment). This is probably highly-related to https://github.com/flutter/flutter/issues/121925. In short, we determine Android Studio's version by examining some field(s) on the package's Info.plist file. However, the Android Studio team uses non-standard field values for Preview versions of Android Studio. I will update the title of #121925 to make it applicable to any Preview version of Android Studio. I will then close this issue as duplicate of that.

However, before I do that. I want to verify something.

> @andrewkolos Could it be that the tool gets confused about the Beta 6 release? I wouldn't think that the `2023.1.1` version would break it, but perhaps the version parsing fails due to the beta portion.
> 
> The `product-info.json` for that beta has `"dataDirectoryName": "AndroidStudioPreview2023.1",` and no dot folder anymore under the home dir in Windows?

Question for @navaronbracke (or myself in a few days): Is this bug appearing on Windows? I tested it on Linux, where it did not appear. Make sure to run Android Studio Preview at least once to generate the `AppData` folder. I won't have access to a Windows machine for a few days.

**Comment by navaronbracke** [comment] 2023-10-04 12:33
I will verify later today if this also occurs on Windows with Hedgehog Beta 6.

I'll provide the verbose doctor logs when I do.

**Closed** 2023-10-05 07:45 UTC
Labels: tool, t: flutter doctor, has reproducible steps, team-tool, found in release: 3.13, found in release: 3.15
