### ISSUE TITLE
White spaces while resizing app using chrome console device switching

### ISSUE THREAD

**Issue by shatanikmahanty** [flutter/flutter#87916] opened 2021-08-08 16:35 UTC
## Steps to Reproduce

Run a flutter web app on Chrome. Open console using F12 key. Change device options. I have attached a video for reference.
This is happening on both debug and release builds. This however doesnot happen incase I use resize on the browser window using mouse cursor.

https://user-images.githubusercontent.com/67138059/128638792-9dc5b3f6-fd52-4b74-9b3d-f34f0fbd94a1.mp4

**Expected results:** App should resize correctly

**Actual results:** App resizes with white space at bottom or sometimes the whole webpage goes blank

<details>
  <summary>Logs</summary>

```
`flutter analyze` Outputs

warning - The include file 'package:flutter_lints/flutter.yaml' in 'D:\AndroidStudioProjects\wenelsahra_admin\analysis_options.yaml' can't be found when analyzing
       'D:\AndroidStudioProjects\wenelsahra_admin' - analysis_options.yaml:10:10 - include_file_not_found
   info - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\artist\update_artist.dart:304:24 - deprecated_member_use
   info - 'FlatButton.icon' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\artist\update_artist.dart:304:24 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\artist\update_artist.dart:406:11 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\business\Account\signup_business.dart:146:28 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\contactus\about_us.dart:76:9 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\contactus\personal.dart:77:9 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\misc\misc.dart:81:9 - deprecated_member_use
   info - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\news\news.dart:55:13 - deprecated_member_use
   info - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\news\news.dart:89:22 - deprecated_member_use
   info - 'FlatButton.icon' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\news\news.dart:89:22 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\news\news.dart:108:22 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\screens\specialOffer\specialOffer.dart:50:9 - deprecated_member_use
   info - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\widgets\common_widgets.dart:24:9 - deprecated_member_use
   info - 'FlatButton.icon' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was
          deprecated after v1.26.0-18.0.pre. - lib\widgets\common_widgets.dart:24:9 - deprecated_member_use

15 issues found. (ran in 2.4s)

```

```
[√] Flutter (Channel beta, 2.4.0-4.2.pre, on Microsoft Windows [Version 10.0.19043.1151], locale en-IN)
    • Flutter version 2.4.0-4.2.pre at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f18b9281c2 (2 weeks ago), 2021-07-22 14:08:30 -0700
    • Engine revision 844c29f42a
    • Dart version 2.14.0 (build 2.14.0-301.2.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\shata\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\shata\AppData\Local\Android\Sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at D:\IntelliJ IDEA 2020.3.1
    • Flutter plugin version 54.0.3
    • Dart plugin version 203.7759

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1151]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 92.0.902.67

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-08-09 15:13
Hi @shatanikmahanty 
This is the same issue as https://github.com/flutter/flutter/issues/77084
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/77084
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-09 15:13 UTC
Labels: in triage
