### ISSUE TITLE
License check script looks at files it shouldn't

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#8492] opened 2017-03-01 15:55 UTC
If there are generated (e.g. .pyc) or otherwise stray files in the checkout, these are read by the license check script and entries are made for them in the output.

The license check script should rather use 'git ls-files' to collect the files it needs to look at, pulling the list of  the git repos it needs to look at out of the DEPS file, and using a whitelist of things that don't come from git repos to walk over on its own.

**Comment by Hixie** [comment] 2017-03-01 18:54
Dupe of https://github.com/flutter/flutter/issues/8115

**Closed by Hixie** 2017-03-01 18:54 UTC
