### ISSUE TITLE
Image with Colors.transparent not rendering correctly on Web platform

### ISSUE THREAD

**Issue by APP-DEVTING** [flutter/flutter#143670] opened 2024-02-18 17:46 UTC
**Description**:
When using `Colors.transparent` in Flutter to apply transparency to an image rendered with `Image.asset`, the image becomes completely invisible on Android and Windows platforms. This behavior is inconsistent with how it behaves on web platforms, where the transparency works as expected. (means nothing happens to icon on web but on android and windows they go full transparent)

**Steps to Reproduce**:
1. Create a Flutter app with an image asset that should become transparent upon a certain condition.
2. Use `Colors.transparent` and `BlendMode.srcIn` to apply transparency to the image when the condition is met.
3. Run the app on Android or Windows platform.
4. Observe that the image becomes completely invisible instead of transparent.

**Expected Behavior**:
The image should become transparent when using `Colors.transparent` and `BlendMode.srcIn`, allowing other content behind it to be partially visible.

**Actual Behavior**:
The image becomes completely invisible when using `Colors.transparent` and `BlendMode.srcIn` on Android and Windows platforms.

**Additional Information**:
- Flutter SDK version: [Insert your Flutter SDK version here]
- Platform(s) affected: Android, Windows
- Code example (Causing Bug):
```dart
Image.asset(
  tile.switchState ? tile.onIconFileName : tile.offIconFileName,
  width: 50, // Adjust image size
  height: 50,
  fit: BoxFit.contain,
  color: tile.switchState ? Colors.transparent : colors.offIconColor,
  colorBlendMode: BlendMode.srcIn,
)
```

**Fix**:
```dart
// Image
Image.asset(
  tile.switchState ? tile.onIconFileName : tile.offIconFileName,
  width: 50, // Adjust image size
  height: 50,
  fit: BoxFit.contain,
  color: tile.switchState ? null : colors.offIconColor,
  colorBlendMode: BlendMode.srcIn,
)
```

after much effort I found the fix and sharing with you all.
Regards,

Happy Devting! 🤗
[issue.txt](https://github.com/flutter/flutter/files/14323650/issue.txt)

**Comment by huycozy** [comment] 2024-02-19 09:15
Reproduced this issue on the latest stable/master channels using this image asset:

<details>
<summary>Image asset</summary>

![house](https://github.com/flutter/flutter/assets/104349824/a0b6e815-993c-4c6f-91e3-e0827c4c40db)

</details>

<details>
<summary>Demo</summary>

| Web | Android app | macOS app |
| --------------- | --------------- | --------------- |
<img width="400" src="https://github.com/flutter/flutter/assets/104349824/2e338196-4d85-4476-a510-d45adafb34b7"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/2e5b5ad7-f920-4596-a400-cd86d9d71063"> | <img width="400" src="https://github.com/flutter/flutter/assets/104349824/fa7a91e4-958d-4c37-9a8a-8e5dd4958982">
</details>

<details>
<summary>Sample code</summary>

```dart
import 'package:flutter/material.dart';

void main() async {
  runApp(
    const MaterialApp(
      title: 'Flutter Demo',
      home: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Image.asset(
          'assets/house.png',
          width: 50, // Adjust image size
          height: 50,
          fit: BoxFit.contain,
          color: Colors.transparent,
          colorBlendMode: BlendMode.srcIn,
        ),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.19.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (2 days ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 121.0.6167.160
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.20.0-10.0.pre.42, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.20.0-10.0.pre.42 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4c8e30cc7f (2 hours ago), 2024-02-18 19:58:28 -0500
    • Engine revision 80d6745c6f
    • Dart version 3.4.0 (build 3.4.0-154.0.dev)
    • DevTools version 2.33.0-dev.6
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio Hedgehog.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.86.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.82.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.184
    ! Error: Browsing on the local area network for iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

Based on reference above, marking this as an issue on Web.

**Comment by APP-DEVTING** [comment] 2024-02-21 00:58
How can I help to fix this issue?

**Comment by yjbanov** [comment] 2024-03-14 18:11
The fix is likely in the engine. Either the `Paint` doesn't apply the colorBlendMode correctly, or the ColorFilterLayer is bugged.

**Comment by muffpy** [comment] 2024-03-18 15:31
@yjbanov Hi! I'm happy to write a patch for this. Would need some guidance on navigating the codebase 😅

**Comment by PedroFrancoDev** [comment] 2024-03-27 15:07
@APP-DEVTING 

Can I contribute to this issue?

**Comment by APP-DEVTING** [comment] 2024-03-27 17:25
Yes, Sure, Please post your suggestions here.

**Comment by randcyp** [comment] 2024-04-15 01:00
This seems to be fixed in the latest beta (Flutter 3.22.0-0.1.pre) build, but still present in the stable (3.19.5) build.

**Comment by huycozy** [comment] 2024-04-15 03:48
Thanks for checking this @randcyp. I also see the issue doesn't occur on beta `3.22.0-0.1.pre` and master channel `3.22.0-10.0.pre`. 

@yjbanov I'm not sure which PR fixed this issue. Is this safe to close the issue as fixed?

**Comment by jason-simmons** [comment] 2024-04-29 20:36
This was fixed by https://github.com/flutter/engine/commit/6bb4374938cc9ab8c00d490986e70f4f9e8717e5

**Comment by huycozy** [comment] 2024-05-02 03:31
Per comment above, closing the issue as fixed.

**Closed by huycozy** 2024-05-02 03:31 UTC
Labels: engine, platform-web, a: images, c: rendering, good first issue, e: web_canvaskit, has reproducible steps, P2, team-web, triaged-web, found in release: 3.19, found in release: 3.20
