### ISSUE TITLE
Australian MaterialLocalizations has incorrect mm/dd/yyyy dateHelpText

### ISSUE THREAD

**Issue by MichaelMarner** [flutter/flutter#70341] opened 2020-11-12 01:33 UTC
Flutters `en_AU` localizations give the wrong `dateHelpText`. Specifically, they inherit from MaterialLocalizationEn - which uses US style mm/dd/yyyy. [That's not how things are done in Australia.](https://en.wikipedia.org/wiki/Date_and_time_notation_in_Australia)

While the help text is incorrect, the underlying DateFormat locale uses the correct d/m/yyyy formatting. This confuses the user, because when they enter a date as specified by the help desk, the parsed DateTime result is incorrect.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Follow the [Internationalization guide](https://flutter.dev/docs/development/accessibility-and-localization/internationalization#setting-up) to configure localizations
2. Add flutter_localizations to pubspec
2. Set the app's supported locale to en_AU
3. Render the helpText.

**Minimal Example**

`pubspec.yaml`

```yaml
name: dateformat
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
```

`main.dart`

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Date Format Test',
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        const Locale('en', 'AU'),
        // ... other locales the app supports
      ],
      home: Scaffold(
        appBar: AppBar(title: Text('Date Format Test')),
        body: Builder(builder: (context) {
          final locale = Localizations.localeOf(context);
          final localizations = MaterialLocalizations.of(context);
          final date = DateTime(2020, 11, 12);
          return ListView(
            children: [
              Text('Current Locale: ${locale.toString()}'),
              Text('dateHelpText: ${localizations.dateHelpText}'),
              Text('Compact Date: ${localizations.formatCompactDate(date)}'),
              Text('Short Date: ${localizations.formatShortDate(date)}'),
              Text('Medium Date: ${localizations.formatMediumDate(date)}'),
              Text('Full Date: ${localizations.formatFullDate(date)}'),
            ],
          );
        }),
      ),
    );
  }
}
```

**Expected results:** 

Help text should be dd/mm/yyyy

**Actual results:** 

Help text shows as mm/dd/yyyy

<details>
  <summary>Logs</summary>

no errors when `flutter run --verbose`

```
```
Analyzing dateformat...
No issues found! (ran in 4.2s)
```
```

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-AU)
    • Flutter version 1.23.0-18.1.pre at /Users/michael/.bin/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/michael/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 11 (mobile) • F3EA93B5-C2C5-4293-BF6C-B8E48251D7E0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
```

</details>

**Comment by MichaelMarner** [comment] 2020-11-12 04:06
Further looking around I thought this may have been an issue in the `intl` package instead, but over there Australian date formats are [correctly defined](https://github.com/dart-lang/intl/blob/master/lib/date_symbol_data_local.dart#L3558).

**Comment by darshankawar** [comment] 2020-11-12 07:25
@MichaelMarner 
Tried your code sample on latest beta and on latest stable. Although I see the date format is showing up as `mm/dd/yyyy`, the actual date is rendered correctly as : `12/11/2020`, as opposed to the one you mentioned in actual results section.

<img width="547" alt="Screenshot 2020-11-12 at 12 46 56 PM" src="https://user-images.githubusercontent.com/67046386/98908068-daafd800-24e5-11eb-8216-94c68c2efd45.png">

<details>
<summary>beta and stable flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.4 19E2269 x86_64,
    locale en-IN)
    • Flutter version 1.23.0-18.1.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      86.0.4240.193

• No issues found!


[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (13 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 14.0

• No issues found!


```

</details>

**Comment by MichaelMarner** [comment] 2020-11-12 22:30
Hi @darshankawar - My apologies, you are correct. The `dateHelpText` is incorrect, but the date parsing seems to be working. I'm not sure what I was seeing yesterday.

I have edited my original report to reflect what is actually happening

**Comment by shihaohong** [comment] 2020-11-13 04:24
I just filed a request to the translation console to look into this.

**Comment by richardheap** [comment] 2020-12-22 03:21
The same seems to be true for other English-speaking day-before-month countries, such as en_GB, en_IE, en_NZ,, (probably) en_IN. mm/dd/yyyy is obviously correct for en_US. I'm not sure about Canada and Singapore, but presumably the help text should match the formatter. In generated_date_localizations.dart, Canada seems to use mm/dd/yy and Singapore dd/mm/yy. South Africa uses y/m/d???

At the least, the help format that ends up in generated_material_localizations should match the date format in generated_date_localizations.dart.

**Comment by danielocampo2** [comment] 2021-03-17 11:05
@shihaohong Is it planned to get the rest of the localizations fixed? Particularly interested in en_GB that still has the wrong date format for the dateHelpText.
Didn't want to create a new ticket as this one is still open.

**Comment by richardheap** [comment] 2021-03-17 14:20
@danielocampo2 The workaround I use is to add a string to your own localizations and pass that localized string to, for example, the date picker when you need it. For example, showDateRangePicker takes two optional parameters fieldStartHintText and fieldEndHintText to override the default. Pass in your own value here.

**Comment by danielocampo2** [comment] 2021-03-17 15:11
@richardheap yes, thanks, we are actually doing the same thing, but it'd be nice to have it fixed eventually.

**Comment by MichaelMarner** [comment] 2021-03-18 22:35
Our workaround is to register our own AU localisations delegate:

```dart
class TrueBlueAussieLocalizations extends MaterialLocalizationEnAu {
  TrueBlueAussieLocalizations({String localeName = 'en_AU'})
      : super(
          localeName: localeName,
          compactDateFormat: intl.DateFormat('dd/MM/y'),
          fullYearFormat: intl.DateFormat('y', localeName),
          shortDateFormat: intl.DateFormat('yMMMd', localeName),
          mediumDateFormat: intl.DateFormat('EEE, MMM d', localeName),
          longDateFormat: intl.DateFormat('EEEE, MMMM d, y', localeName),
          yearMonthFormat: intl.DateFormat('MMMM y', localeName),
          shortMonthDayFormat: intl.DateFormat('MMM d'),
          decimalFormat: intl.NumberFormat('#,##0.###', localeName),
          twoDigitZeroPaddedFormat: intl.NumberFormat('00', localeName),
        );

  @override
  String get dateHelpText => 'dd/mm/yyyy';

  static const LocalizationsDelegate<MaterialLocalizations> delegate =
      TrueBlueLocalizationsDelegate();
}

class TrueBlueLocalizationsDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const TrueBlueLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      locale.languageCode == 'en' && locale.countryCode == 'AU';

  @override
  Future<MaterialLocalizations> load(Locale locale) async {
    final String localeName = intl.Intl.canonicalizedLocale(locale.toString());
    return SynchronousFuture<MaterialLocalizations>(
      TrueBlueAussieLocalizations(localeName: localeName),
    );
  }

  @override
  bool shouldReload(TrueBlueLocalizationsDelegate old) => true;
}```

**Comment by danielocampo2** [comment] 2021-03-19 15:43
@MichaelMarner That looks like a good solution. Will consider changing to this in case we need to customise other fields.

> The issue of manually giving hint strings to the DatePicker is that now you need to have your app check the locale to decide whether manually passing strings is necessary, or to let l10n deal with it.
The way we are doing it we don't need to check the locale, we currently have the following extension:

```
extension MaterialLocalizationsExtension on MaterialLocalizations {

  String ensureCorrecDateHelpText() {
    if (this is MaterialLocalizationEnGb) {
      return "dd/mm/yyyy";
    }

    return this.dateHelpText;
  }
}
```

**Comment by Guthers** [comment] 2021-12-09 04:38
Any update on this at all? Looks pretty terrible when this will affect most English countries using Flutter.
@shihaohong, any update from your request to the translation console?

**Comment by Morpa** [comment] 2022-11-16 22:05
Does anyone know how I can get around this situation? @MichaelMarner  did you manage to solve this?

**Comment by MichaelMarner** [comment] 2022-11-18 07:21
@Morpa as I mentioned in my comment [here](https://github.com/flutter/flutter/issues/70341#issuecomment-802355415), we worked around it by creating our own Localization.

I know everyone is busy, but it's disappointing to see this issue still open after 2 years. Internationalisation is important.

**Comment by Morpa** [comment] 2022-11-18 07:35
> @Morpa as I mentioned in my comment [here](https://github.com/flutter/flutter/issues/70341#issuecomment-802355415), we worked around it by creating our own Localization.
> 
> I know everyone is busy, but it's disappointing to see this issue still open after 2 years. Internationalisation is important.

I tried do the same, but for me don't work. possibly I did something wrong.  I'm agreed with you. A long time for the simple issue.

**Comment by maheshmnj** [comment] 2023-01-05 02:12
Reproducible on stable 3.3 and master 3.7 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/31410839/210685812-613375b0-d3e3-47cb-9400-05e0b9fa576e.png">


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by thkim1011** [comment] 2023-05-31 17:26
This is fixed now as of https://github.com/flutter/flutter/pull/124094,
![image](https://github.com/flutter/flutter/assets/2004742/5d67cda1-b47a-4284-99e3-b080320d9661)

**Closed by thkim1011** 2023-05-31 17:26 UTC
Labels: framework, f: material design, a: internationalization, has reproducible steps, found in release: 3.3, found in release: 3.7
