### ISSUE TITLE
TextFiled backspace delete 2 charactors one time problem happend again!!

### ISSUE THREAD

**Issue by jinfagang** [flutter/flutter#74480] opened 2021-01-22 10:00 UTC
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.26.0-13.0.pre.120, on Linux, locale en_HK.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ The blkid development library is required for Linux development.
      It is likely available from your distribution (e.g.: apt install libblkid-dev)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.


```

Lastest flutter. 

For reproducing, I think there will someoen comment blow that they have same issue.

Previously I solved it by switch to master, now master also have that problem..... damn it

**Comment by TahaTesser** [comment] 2021-01-22 10:35
Hi @jinfagang 
Your own issue is still open and this is a duplicate of https://github.com/flutter/flutter/issues/71404
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-22 10:35 UTC

**Comment by jinfagang** [comment] 2021-01-24 12:51
@TahaTesser No. That issue has been resolved by switch to master and upgrade. But now I am ready on master and upgrade to latest, happened again.

PS: I re-tested, it seems happens only on Linux!

**Comment by TahaTesser** [comment] 2021-01-25 15:10
@jinfagang 
Please add those details in your issue, the issue isn't closed and we don't need a new issue for the same.
