### ISSUE TITLE
TextField and TextFormField don't use error color from ColorScheme

### ISSUE THREAD

**Issue by rares45** [flutter/flutter#87868] opened 2021-08-07 17:42 UTC
TextField and TextForm field use theme's ColorScheme to get their colours, but they don't get the error colour from the ColorScheme. They get it from errorColor in ThemeData. And it is an inconsistency.

## Steps to reproduce

1. Create a ColorScheme and set the `error` propriety 
2. Create a TextField

**Expected results:** a TextField with error color same in the ColorScheme

**Actual results:** TextField gets its error colour from errorColor in ThemeData
I think this is an inconsistency.

Also, it would be nice that ThemeData proprieties would have a description that recommends using a color scheme

Sample code:
   ```dart
MaterialApp(
      theme: ThemeData(
        colorScheme: ColorScheme.light(
          error: Colors.green,
        ),
      ),
      home: Scaffold(
        body: TextField(
          decoration: InputDecoration(
            errorText: "Some error",
          ),
        ),
      ),
    )
```
This result in 
![image](https://user-images.githubusercontent.com/42469755/129027338-fe46512e-c683-42ee-87db-fdf22c747cfa.png)

As you can see this is not green

<details> <summary>  Previous description </summary>
## Steps to Reproduce

1. Set some colours in the theme
2. Create a TextField

**Expected results:** a TextField themed properly (accent coloured border, etc.)

In version 2.0.x it worked like this.
Also, the documentation says it should be using the theme so it is a bug.

**Actual results:** the TextField has a default blue coloured border and not even the error colour(which is very annoying to set using InputDecoration) is inherited

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.2.3 at /home/rares/snap/flutter/common/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/rares/.apps/android-sdk/
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /var/lib/snapd/snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = google-chrome-stable

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /var/lib/snapd/snap/android-studio/114/android-studio
    • Flutter plugin version 59.0.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Android Studio (version 4.2)
    • Android Studio at /var/lib/snapd/snap/android-studio/113/android-studio
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Android Studio
    • Android Studio at /var/lib/snapd/snap/android-studio/current/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /var/lib/snapd/snap/android-studio/current/android-studio/
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

! Doctor found issues in 1 category.
```

</details>

**Comment by maheshmnj** [comment] 2021-08-09 13:05
Hi @rares45, Thanks for filing the issue, Could you please provide a minimal reproducible code to better address the issue.

Thanks.

**Comment by rares45** [comment] 2021-08-10 16:32
I know I can use InputDecorationTheme, but that is not great, especially when I want more forum types, but with the same colours.

Code sample:
```dart
MaterialApp(
      themeMode: ThemeMode.dark,
      darkTheme: ThemeData.dark().copyWith(
        primaryColor: Colors.amber,
        accentColor: Colors.green,
      ),
      home: Scaffold(
        body: TextField(),
      ),
    )
```

Actual result of this:
![image](https://user-images.githubusercontent.com/42469755/128896860-251a45b6-1b32-4a3b-a232-93822541f554.png)

The color is not amber nor green.

> > and not even the error colour
> 
> I am not sure I understand what you meant by this.

I mean the errorColor in ThemeData which is used to show error(that's dispalyed when the validate function retunr a error). ThemeData.dark() comes with a desatured red, but when TextFormField show a simple red from the light theme.

**Comment by maheshmnj** [comment] 2021-08-11 06:09
@rares45 thanks for the clarification I can reproduce the issue using theme the color of the border isn't changing, Also note that accent color is now deprecated and is now replaced with secondary color of  [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html), You can read more about the [deprecation here](https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties)
This issue seems to be related to https://github.com/flutter/flutter/issues/44100
You can read about the [current theme updates here](https://docs.google.com/document/d/1kzIOQN4QYfVsc5lMZgy_A-FWGXBAJBMySGqZqsJytcE/edit#)

**Comment by rares45** [comment] 2021-08-11 10:45
@maheshmnj So after some more experimenting I moved everything to ColorScheme and this fixed everything. So this is more a problem accentColor is not properly marked as deprecated. Also, I found out that setting errorColor in ThemeData sets the error colour, but if I set error in ColorScheme it does nothing.

So basically my issue is just some small lack of documentation and a problem with not using ColorScheme in error.

**Comment by maheshmnj** [comment] 2021-08-11 11:47
@rares45 Thanks for the details, could you please update the above description with sufficient details, so that we could update the issue accordingly.

Thanks

**Comment by maheshmnj** [comment] 2021-08-12 07:46
@rares45 Thanks for the update, I can reproduce it, Error color is not being applied to error text from ColorScheme.error

**Comment by markusaksli-nc** [comment] 2022-01-05 10:43
This is part of https://github.com/flutter/flutter/issues/91772

> Deprecate `ThemeData.errorColor` (4) ⇒ `ColorScheme.error`

**Comment by guanshuwen** [comment] 2022-06-15 07:24
Is there any propriety to set fillColor of an outlined TextField? 
In InputDecoration we can set filled: true and fillColor: _bgColor and use setState when focus changed, error occurred or widget disabled, but it's cumbersome for so much status and their background colors.

**Comment by hangyujin** [comment] 2022-07-28 16:50
TextField in material 2 is using ThemeData.errorColor as a fallback. 

But in Material 3 we have updated the fallback error color to use the ColorScheme, so the issue is fixed in M3.

Related PR:  #107943

**Closed by hangyujin** 2022-07-28 16:50 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 2.2, found in release: 2.5

**Comment by hangyujin** [comment] 2022-07-28 17:03
@guanshuwen The fill color is a separated issue from the `errorColor` issue.
If you want to set different fillColors in different states, try [MaterialStateColor].
If you want to discuss it further. You can create another issue.
