### ISSUE TITLE
Flutter (the doctor check crashed)

### ISSUE THREAD

**Issue by Asyl1476** [flutter/flutter#146052] opened 2024-03-31 17:45 UTC
### Steps to reproduce

flutter doctor -v

### Actual results

```
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X FileSystemException: Cannot resolve symbolic links, path = 'C:\Users\ASUS\OneDrive\ђ Ў®зЁ© бв®«\qr_bonus_waiter-main\flutter\bin\flutter' (OS Error:    
      The system cannot find the specified path.
      , errno = 3)
    • #0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:829:7)
      #1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:348:5)
      #2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
      #3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
      #4      FlutterValidator._validateSdkBinary (package:flutter_tools/src/doctor.dart:624:51)
      #5      FlutterValidator._validateRequiredBinaries (package:flutter_tools/src/doctor.dart:604:47)
      #6      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:518:7)
      #7      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:258:72)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #9      _rootRun (dart:async/zone.dart:1399:13)
      #10     _CustomZone.run (dart:async/zone.dart:1301:19)
      #11     _runZoned (dart:async/zone.dart:1804:10)
      #12     runZonedGuarded (dart:async/zone.dart:1792:12)
      #13     runZoned (dart:async/zone.dart:1744:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:250:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:378:72)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:48)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1662:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:90:3)
      <asynchronous suspension>


[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • Java binary at: C:\Users\ASUS\Downloads\Android Studio\And\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Users\ASUS\Downloads\Android Studio\And
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3374]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.65

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

### Logs

<details open>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

### Flutter Doctor output

```
[☠] Flutter (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X FileSystemException: Cannot resolve symbolic links, path = 'C:\Users\ASUS\OneDrive\ђ Ў®зЁ© бв®«\qr_bonus_waiter-main\flutter\bin\flutter' (OS Error:    
      The system cannot find the specified path.
      , errno = 3)
    • #0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:829:7)
      #1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:348:5)
      #2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
      #3      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56:49)
      #4      FlutterValidator._validateSdkBinary (package:flutter_tools/src/doctor.dart:624:51)
      #5      FlutterValidator._validateRequiredBinaries (package:flutter_tools/src/doctor.dart:604:47)
      #6      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:518:7)
      #7      Doctor.startValidatorTasks.<anonymous closure> (package:flutter_tools/src/doctor.dart:258:72)
      #8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #9      _rootRun (dart:async/zone.dart:1399:13)
      #10     _CustomZone.run (dart:async/zone.dart:1301:19)
      #11     _runZoned (dart:async/zone.dart:1804:10)
      #12     runZonedGuarded (dart:async/zone.dart:1792:12)
      #13     runZoned (dart:async/zone.dart:1744:12)
      #14     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #15     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:250:9)
      #16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:378:72)
      #17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:49:48)
      #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1662:12)
      <asynchronous suspension>
      #19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
      <asynchronous suspension>
      #20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #21     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
      <asynchronous suspension>
      #22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
      <asynchronous suspension>
      #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     main (package:flutter_tools/executable.dart:90:3)
      <asynchronous suspension>


[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • Java binary at: C:\Users\ASUS\Downloads\Android Studio\And\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Users\ASUS\Downloads\Android Studio\And
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3374]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.65

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by danagbemava-nc** [comment] 2024-04-01 10:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/59770

**Closed by danagbemava-nc** 2024-04-01 10:55 UTC
Labels: in triage
