### ISSUE TITLE
flutter analyze doesn't work well with nested (and different) .packages files

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#10015] opened 2017-05-11 23:21 UTC
If you run `flutter analyze` on https://github.com/flutter/plugins/tree/master/packages/firebase_auth you get the following output:

```
Analyzing /Users/goderbauer/dev/plugins/packages/firebase_auth...
    error • Target of URI doesn't exist: 'package:google_sign_in/google_sign_in.dart' at example/lib/main.dart:10:8 • uri_does_not_exist
    error • Undefined class 'GoogleSignIn' at example/lib/main.dart:13:7 • undefined_class
    error • Undefined class 'GoogleSignIn' at example/lib/main.dart:13:39 • undefined_class
    error • Undefined class 'GoogleSignInAccount' at example/lib/main.dart:63:5 • undefined_class
    error • Undefined class 'GoogleSignInAuthentication' at example/lib/main.dart:64:5 • undefined_class
5 issues found.
```

All those issues are bogus. Apparently, `flutter analyze` can't deal with the fact that plugins have an `example` sub-package.

/cc @mit-mit

**Comment by eseidelGoogle** [comment] 2017-05-12 00:23
It looks like example is the right pattern:
https://www.dartlang.org/tools/pub/package-layout#examples

Just maybe it's not supposed to be a full pub package itself?  @devoncarew

**Comment by devoncarew** [comment] 2017-05-12 02:40
I'll take a look, but w/o looking at the repo, what I suspect is that the example/ uses additional packages from the repo root, but pub hasn't been run in the example/ dir.

**Comment by goderbauer** [comment] 2017-05-12 17:05
@devoncarew Same result with explicitly running pub in both packages:

```ps1
C:\src\plugins\packages\firebase_auth\example> flutter packages get
Running 'flutter packages get' in example...          2.8s
C:\src\plugins\packages\firebase_auth\example> cd ..
C:\src\plugins\packages\firebase_auth> flutter packages get
Running 'flutter packages get' in firebase_auth...    6.3s
C:\src\plugins\packages\firebase_auth> flutter analyze
Analyzing C:\src\plugins\packages\firebase_auth...
    error - Target of URI doesn't exist: 'package:google_sign_in/google_sign_in.dart' at example\lib\main.dart:10:8 - uri_does_not_exist
    error - Undefined class 'GoogleSignIn' at example\lib\main.dart:13:7 - undefined_class
    error - Undefined class 'GoogleSignIn' at example\lib\main.dart:13:39 - undefined_class
    error - Undefined class 'GoogleSignInAccount' at example\lib\main.dart:63:5 - undefined_class
    error - Undefined class 'GoogleSignInAuthentication' at example\lib\main.dart:64:5 - undefined_class
5 issues found.
(Ran in 6.9s)
```

**Comment by devoncarew** [comment] 2017-05-15 05:58
So, I can repro:

- git clone https://github.com/flutter/plugins.git
- cd plugins/packages/firebase_auth
- flutter packages get
- flutter analyze ==> shows analysis issues in examples/
- cd examples
- flutter packages get
- flutter analyze ==> shows no analysis issues (the created .packages file has a ref to package:google_sign_in)
- cd ..
- flutter analyze ==> still see the analysis issues from the first run

I think what's happening here is that `flutter analyze` is using the root `.packages` file to analyze all the code it finds in the project. However, what it needs to do is use `examples/.packages` for the example dir and the top level .packages file for the rest.

@danrubel @bwilkerson have discussed some unification of how analysis contexts are build that would solve this. We've also talked about just using an analysis server based CLI to implement `flutter analyze`, which would also solve this (running `tuneup` in this dir does do the right thing).

**Comment by danrubel** [comment] 2017-05-15 12:39
Yes, moving `flutter analyze` to use the analysis server rather than `dartanalyzer` makes sense to me.

**Comment by mit-mit** [comment] 2017-05-16 16:18
@danrubel can we assign this to you?

**Comment by danrubel** [comment] 2017-05-16 16:28
Sure :-)

**Comment by mit-mit** [comment] 2017-05-31 09:19
@danrubel any news?

**Comment by danrubel** [comment] 2017-06-12 22:41
Started merging `flutter analyze` and `flutter analyze --watch` to both use analysis server.
https://github.com/flutter/flutter/pull/10641

**Comment by danrubel** [comment] 2017-09-23 16:44
CFE is consuming all my time through EOY. Happy to revisit this in the new year.

**Comment by devoncarew** [comment] 2018-01-02 17:00
@pq, once the latest SDK rolls into flutter (https://github.com/flutter/flutter/pull/13741), we should look at the work necessary to do this. I think that means transitioning `flutter analyze` to fully use the analysis server, and seeing how we can support (or remove) `flutter analyze` features (perhaps by post-processing the analysis server output).

**Comment by Hixie** [comment] 2018-01-02 22:15
We can't move to the analysis server without significant performance work on the analysis server. Right now, it takes 40s in batch mode and 66s in server mode to analyze the repo. Moving batch mode to the server would be a huge regression.

**Comment by devoncarew** [comment] 2018-01-02 23:37
That would be a drawback. We could look at the performance difference to see if anything stands out. But moving to a server based impl would have benefits, including fixing this issue.

**Comment by devoncarew** [comment] 2018-01-03 01:41
let me elaborate a bit though:

> right now, it takes 40s in batch mode and 66s in server mode to analyze the repo

That's for the flutter repo itself, which is a bit of a special case (and was special-cased by flutter analyze). User's themselves should see a performance benefit with the analysis server; it'll be using the cached analysis contents via the analysis driver - runs after the first one should be relatively speedy.

I'd like to run a few speed tests on the flutter repo when doing one-shot analysis via the analysis server, just to see why there's a performance difference between it and `flutter analyze`.

**Comment by pq** [comment] 2018-01-03 21:50
66s is a bit shocking.  That said, whatever the initial run is it should be *much* faster the second time.  If it isn't then we've got other problems.

Anyway, doing some speed tests is a great idea.

**Comment by Hixie** [comment] 2018-01-05 00:39
For the repo the initial run is really what matters, because the bots are usually doing an initial run.

**Comment by Hixie** [comment] 2018-01-05 00:40
The numbers above come from our benchmarks, btw. It's the first four graphs on https://flutter-dashboard.appspot.com/benchmarks.html. Hover over the graphs and click the magnifying class at the top-right of each graph to see the long-term trends.

**Comment by Hixie** [comment] 2018-01-05 00:41
(For the analyzer_benchmark mega_gallery_batch benchmark, the numbers for batch and server are comparable, about 25s each. That's more representative of what our users will see on their bots.)

**Comment by ezrasandzerbell** [comment] 2018-03-16 20:20
Has this issue been addressed? I'm having trouble with 'package:intl/intl.dart'. Tried simple debugging like refreshing Analysis, restarted Android Studio, running flutter get. None of that has worked so far...

**Comment by devoncarew** [comment] 2018-05-19 18:15
fixed as part of a general flutter analyze re-write

**Closed by devoncarew** 2018-05-19 18:15 UTC
Labels: p: tooling, plugin, tool
