### ISSUE TITLE
Relative Dependency of a Git Dependency Fails to Resolve

### ISSUE THREAD

**Issue by CengizhanParlak** [flutter/flutter#111514] opened 2022-09-13 20:59 UTC
## Steps to Reproduce

1. Create a new Flutter project: `flutter create git_package`
2. Create a folder in the project's root directory as `custom_libs/my_relative_package` and run `flutter create .` inside `my_relative_package` folder from terminal
3. Go to project's `pubspec.yaml` and add the other project as a relative dependency:
```yaml
dependencies:
  ...
  my_relative_package:
    path: custom_libs/my_relative_package
```
4. Upload project to github
5. Create any other project that adds `git_package` as a dependency:
```yaml
dependencies:
  ...
  git_package:
    git:
      url: https://github.com/yourUserName/git_package.git
      ref: main
```
6. run `flutter pub get` in your newly created project that depends on `git package`

**Expected results:** 
Relative import at `git_package` to be resolved automatically

**Actual results:** 
```sh
Invalid description in the "git_package" pubspec on the "my_relative" dependency: "custom_libs/my_relative_package" is a relative path, but this isn't a local pubspec.
   ╷
37 │     path: custom_libs/my_relative_package
```

I'm pretty sure I am missing something essential regarding resolving package dependencies. My best guess is that I can't have a local package as a dependency in a remote URL. Could anybody shed a light to this matter if possible? Thanks in advance.

**Comment by christopherfujino** [comment] 2022-09-13 21:37
> I'm pretty sure I am missing something essential regarding resolving package dependencies. My best guess is that I can't have a local package as a dependency in a remote URL. Could anybody shed a light to this matter if possible? Thanks in advance.

Per https://dart.dev/tools/pub/dependencies#path-packages, it sounds like a path dependency only works in the project you're working on, not a project's dependency. Closing this as unrelated to the Flutter SDK (this is a limitation of https://github.com/dart-lang/pub/issues), although it also sounds like this is working as intended. If you have a feature request, the pub issue tracker would be the place to track. Thanks!

**Closed by christopherfujino** 2022-09-13 21:37 UTC
