### ISSUE TITLE
CupertinoAlertDialog Font Issue

### ISSUE THREAD

**Issue by ivanchaukn** [flutter/flutter#50905] opened 2020-02-17 06:10 UTC
Hi,

After a recent flutter upgrade, the font of the title and probably content does not follow the Apple Human Interface Guidelines anymore. Is this an intended change or an overlooked mistake?

## Steps to Reproduce

1. show a CupertinoAlertDialog with title and content set with a Text widget.

**Expected results:**
![Screen Shot 2020-02-17 at 1 08 01 AM](https://user-images.githubusercontent.com/8071296/74627814-f7b7a600-5121-11ea-98af-2bf4f2a22a9e.png)

**Actual results:**
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-17 at 01 03 24](https://user-images.githubusercontent.com/8071296/74627703-b3c4a100-5121-11ea-80b1-db8e1e244eaf.png)

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-CA)
    • Flutter version 1.14.6 at /Users/ivanchau/Documents/flutter
    • Framework revision fabeb2a16f (3 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ivanchau/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/ivanchau/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 10 (API 29) (emulator)
    • Ivan’s iPhone             • 46e4b34f2a7f7450a3d0afd052bb1e34d5a7fdb4 • ios         • iOS 10.2.1
    • iPhone 11 Pro Max         • 2A11239A-754B-4A0F-A492-71EB877F3C6C     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

</details>

**Comment by Vanethos** [comment] 2020-02-17 06:33
Hello @ivanchaukn is it possible to add the code you are using?

Thank you

**Comment by ivanchaukn** [comment] 2020-02-17 15:45
I simply just use the Flutter Demo app and add a CupertinoAlertDialog.
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and usae it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        child: Container(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showDialog(
              context: context,
              builder: (BuildContext context) {
                return CupertinoAlertDialog(
                  title: Text('Test'),
                  content: Text('Text Body'),
                  actions: <Widget>[
                    CupertinoDialogAction(child: Text('Cancel')),
                    CupertinoDialogAction(child: Text('Submit'))
                  ],
                );
              });
        },
        child: Icon(Icons.add),
      ),
    );
  }
}
```

**Comment by flyrboy96** [comment] 2020-02-17 17:00
This looks similar to #49492

**Comment by LongCatIsLooong** [comment] 2020-02-18 19:01
Duplicate of #49492

**Closed by LongCatIsLooong** 2020-02-18 19:01 UTC
Labels: a: typography, f: cupertino, framework, severe: regression
