### ISSUE TITLE
App crash when phone number firebase auth is used.

### ISSUE THREAD

**Issue by samaddestring** [flutter/flutter#71540] opened 2020-12-02 08:34 UTC
Here is the log errors.whenever i try i get this captchae browser error. please help out asap.thanks

E/AndroidRuntime(15997): FATAL EXCEPTION: main
E/AndroidRuntime(15997): Process: com.hunarmand, PID: 15997
E/AndroidRuntime(15997): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/browser/customtabs/CustomTabsIntent$Builder;
E/AndroidRuntime(15997): 	at com.google.firebase.auth.internal.RecaptchaActivity.zza(com.google.firebase:firebase-auth@@20.0.1:13)
E/AndroidRuntime(15997): 	at com.google.android.gms.internal.firebase-auth-api.zzth.zzb(com.google.firebase:firebase-auth@@20.0.1:7)
E/AndroidRuntime(15997): 	at com.google.android.gms.internal.firebase-auth-api.zzth.onPostExecute(com.google.firebase:firebase-auth@@20.0.1)
E/AndroidRuntime(15997): 	at android.os.AsyncTask.finish(AsyncTask.java:636)
E/AndroidRuntime(15997): 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
E/AndroidRuntime(15997): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
E/AndroidRuntime(15997): 	at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime(15997): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime(15997): 	at android.app.ActivityThread.main(ActivityThread.java:5637)
E/AndroidRuntime(15997): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15997): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(15997): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
E/AndroidRuntime(15997): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
E/AndroidRuntime(15997): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.browser.customtabs.CustomTabsIntent$Builder" on path: DexPathList[[zip file "/data/app/com.hunarmand-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hunarmand-1/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(15997): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(15997): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(15997): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(15997): 	... 13 more
E/AndroidRuntime(15997): 	Suppressed: java.lang.ClassNotFoundException: androidx.browser.customtabs.CustomTabsIntent$Builder
E/AndroidRuntime(15997): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(15997): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(15997): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(15997): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(15997): 		... 14 more
E/AndroidRuntime(15997): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by TahaTesser** [comment] 2020-12-02 10:21
Hi @samaddestring 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-02 10:21 UTC

**Comment by samaddestring** [comment] 2020-12-02 10:25
hi, the issue is resolved.I implemented a dependency of browser for capchae in android side.
