### ISSUE TITLE
[go_router] Make it possible to set 'extra' in 'redirect' callbacks.

### ISSUE THREAD

**Issue by arthurbcd** [flutter/flutter#140298] opened 2023-12-17 20:49 UTC
### Use case

Some routes require an extra argument to exist. If you can navigate with an extra argument, why can't you also redirect with an extra argument? It should be available in all use cases.

### Proposal

We should be able to dynamically modify the extra argument or either rework the redirect callback for allowing this use case.

**Comment by danagbemava-nc** [comment] 2023-12-18 06:56
Closing this as a duplicate of https://github.com/flutter/flutter/issues/114131. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-12-18 06:56 UTC
Labels: in triage
