### ISSUE TITLE
[google_maps_flutter_web] Marker made with BitmapDescriptor.fromBytes not working

### ISSUE THREAD

**Issue by BoHellgren** [flutter/flutter#114894] opened 2022-11-08 15:02 UTC
See issue #73789
I ran the test program there using 

flutter 3.3.5
google_maps_flutter: ^2.2.1
google_maps_flutter_web: ^0.4.0+3

I changed the last three lines to
  
var pngBytes =
    await (await p.toImage(markerWidth, markerWidth)).toByteData(format: ImageByteFormat.png);
    Uint8List data = Uint8List.view(pngBytes!.buffer);
    return BitmapDescriptor.fromBytes(data, size: Size.square(300));

and ran main.dart with
flutter run -d web-server --web-renderer canvaskit

On the map, the custom marker only shows the number 1, not the image!

<img width="400" alt="localhost_60646_(Samsung Galaxy A51_71)" src="https://user-images.githubusercontent.com/18601125/200598345-2e780351-f468-46df-812b-ff4914b4944e.png">

The console shows
![image](https://user-images.githubusercontent.com/18601125/200598879-19b9149c-6d25-4b46-b05b-2b5243c528ec.png)

**Comment by BoHellgren** [comment] 2022-11-08 15:22
On Android, the same code works without problem.
![Screenshot_20221108_161832](https://user-images.githubusercontent.com/18601125/200604522-5c0895bb-5f12-46bb-a71d-8af119eb51fe.jpg)

**Comment by huycozy** [comment] 2022-11-09 09:02
Hi @BoHellgren. This issue is reproducible on the `stable` channel. But it seems to have been fixed on the latest `master` channel. Please see the demo. 

<details>
<summary>Demo</summary>

![Screenshot 2022-11-09 at 16 01 07](https://user-images.githubusercontent.com/104349824/200786124-7e6a06bc-e3ac-48de-a56c-bf3ac21e5b0e.png)

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.3.7 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (27 hours ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.72.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.5.0-12.0.pre.175, on macOS 13.0 22A380 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-12.0.pre.175 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 92f10ed712 (83 minutes ago), 2022-11-08 17:57:52 -0800
    • Engine revision e7d7edab98
    • Dart version 2.19.0 (build 2.19.0-374.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

Please try running app again on the latest master channel and confirm if this issue is fixed.

**Comment by BoHellgren** [comment] 2022-11-09 13:06
It doesn't look fixed to me - there should not be a black square behind the marker!

**Comment by huycozy** [comment] 2022-11-10 04:33
@BoHellgren That's because your provided photo at https://github.com/flutter/flutter/issues/73789#issuecomment-760272853 had a black background, I couldn't find one without a background. 
Please try running app again on the latest master channel and confirm if this issue is fixed.

**Comment by BoHellgren** [comment] 2022-11-10 15:32
I have made a workaround (using Paint3D and BitmapDescriptor.fromAssetImage) that works for me. I cannot spend more time on this bug. When it is fixed on the stable channel, let me know.

**Comment by huycozy** [comment] 2022-11-11 02:54
Hi @BoHellgren 
Can you confirm this issue is fixed on the `master` channel? Or does this still persist?

In case it's fixed on the master, it takes a couple of months to land stable fixes to release channels. You can read more about the build release channels here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels.

**Comment by BoHellgren** [comment] 2022-11-11 09:24
No, I can not spend more time on this bug. You said it is reproducible. Then please fix it. Thanks.

**Comment by huycozy** [comment] 2022-11-11 10:44
>This issue is reproducible on the stable channel. But it seems to have been fixed on the latest master channel.

@BoHellgren It's reproducible on `stable` channel but not on `master` from my side. Once the issue is fixed on master we have the plan to land on stable periodically as described at https://github.com/flutter/flutter/issues/114894#issuecomment-1311166576. Please check this carefully by verifying on the latest `master` channel.

**Closed** 2022-12-02 11:09 UTC
Labels: waiting for customer response, in triage
