### ISSUE TITLE
command `flutter version 1.12.13+hotfix.7`,  flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by zigang93** [flutter/flutter#51442] opened 2020-02-26 00:36 UTC
## command

flutter version 1.12.13+hotfix.7

## exception

VersionCheckError: VersionCheckError: Command exited with code -9: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard error: 

```
#0      _runSync (package:flutter_tools/src/version.dart:543:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:143:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.toString (package:flutter_tools/src/version.dart:110:99)
#4      VersionCommand.runCommand (package:flutter_tools/src/commands/version.dart:117:32)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
1
1
1
[33m[!][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-GB)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at /Users/tanzigang/flutter
    [31m✗[39m Command exited with code -9: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
      Standard error: 
    [31m✗[39m Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/tanzigang/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 28.0.3
    [31m✗[39m No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in your PATH. You can download the JDK from
      https://www.oracle.com/technetwork/java/javase/downloads/.

[31m[✗][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[33m[!][39m Android Studio
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [31m✗[39m Unable to determine bundled Java version.
    [32m•[39m Try updating or re-installing Android Studio.

[32m[✓][39m VS Code (version 1.42.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.8.1

[31m[☠][39m Connected device (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    [31m✗[39m Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: /Users/tanzigang/Library/Android/sdk/platform-tools/adb
    [32m•[39m #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
      #1      getAdbDevices (package:flutter_tools/src/android/android_device.dart:731:5)
      #2      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:65:53)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:851:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:205:26)
      #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
      #18     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:7)
      #20     _rootRun (dart:async/zone.dart:1126:13)
      #21     _CustomZone.run (dart:async/zone.dart:1023:19)
      #22     _runZoned (dart:async/zone.dart:1518:10)
      #23     runZoned (dart:async/zone.dart:1465:12)
      #24     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
      #25     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #26     AppContext.run (package:flutter_tools/src/base/context.dart:132:19)
      #27     _doctorText (package:flutter_tools/runner.dart:204:19)
      #28     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #29     _doctorText (package:flutter_tools/runner.dart:200:27)
      #30     _createLocalCrashReport (package:flutter_tools/runner.dart:182:32)
      #31     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #32     _createLocalCrashReport (package:flutter_tools/runner.dart:167:37)
      #33     _handleToolError (package:flutter_tools/runner.dart:138:31)
      #34     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
      #35     _rootRunUnary (dart:async/zone.dart:1134:38)
      #36     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #37     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
      #39     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #40     Future._completeWithValue (dart:async/future_impl.dart:524:5)
      #41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
      #42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
      #43     CrashReportSender.sendReport (package:flutter_tools/src/reporting/crash_reporting.dart)
      #44     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
      #45     _rootRunUnary (dart:async/zone.dart:1134:38)
      #46     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #47     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
      #49     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #50     Future._complete (dart:async/future_impl.dart:514:7)
      #51     Stream.fold.<anonymous closure> (dart:async/stream.dart:805:18)
      #52     _rootRun (dart:async/zone.dart:1122:38)
      #53     _CustomZone.run (dart:async/zone.dart:1023:19)
      #54     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #55     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
      #56     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
      #57     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
      #58     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
      #59     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
      #60     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
      #61     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
      #62     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
      #63     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
      #64     _rootRun (dart:async/zone.dart:1122:38)
      #65     _CustomZone.run (dart:async/zone.dart:1023:19)
      #66     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #67     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
      #68     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
      #69     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
      #70     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
      #71     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:174:13)
      #72     _rootRun (dart:async/zone.dart:1122:38)
      #73     _CustomZone.run (dart:async/zone.dart:1023:19)
      #74     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #75     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
      #76     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
      #77     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
      #78     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
      #79     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
      #80     _Uint8ListConversionSink.close (dart:_http/http_impl.dart:581:13)
      #81     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
      #82     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
      #83     _rootRun (dart:async/zone.dart:1122:38)
      #84     _CustomZone.run (dart:async/zone.dart:1023:19)
      #85     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #86     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
      #87     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
      #88     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
      #89     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
      #90     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
      #91     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:64:11)
      #92     _FilterSink.close (dart:io/data_transformer.dart:639:11)
      #93     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
      #94     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
      #95     _rootRun (dart:async/zone.dart:1122:38)
      #96     _CustomZone.run (dart:async/zone.dart:1023:19)
      #97     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #98     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
      #99     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
      #100    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
      #101    _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
      #102    _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:174:13)
      #103    _rootRun (dart:async/zone.dart:1122:38)
      #104    _CustomZone.run (dart:async/zone.dart:1023:19)
      #105    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #106    _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
      #107    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
      #108    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
      #109    _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
      #110    _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
      #111    _StreamController.close (dart:async/stream_controller.dart:624:5)
      #112    _HttpParser._closeIncoming (dart:_http/http_parser.dart:1039:23)
      #113    _HttpParser._doParse (dart:_http/http_parser.dart:754:11)
      #114    _HttpParser._parse (dart:_http/http_parser.dart:320:7)
      #115    _HttpParser._onData (dart:_http/http_parser.dart:812:5)
      #116    _rootRunUnary (dart:async/zone.dart:1134:38)
      #117    _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #118    _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
      #119    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
      #120    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
      #121    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
      #122    _StreamController._add (dart:async/stream_controller.dart:642:7)
      #123    _StreamController.add (dart:async/stream_controller.dart:588:5)
      #124    _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
      #125    _rootRunUnary (dart:async/zone.dart:1134:38)
      #126    _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #127    _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
      #128    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
      #129    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
      #130    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
      #131    _StreamController._add (dart:async/stream_controller.dart:642:7)
      #132    _StreamController.add (dart:async/stream_controller.dart:588:5)
      #133    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1018:19)
      #134    _rootRun (dart:async/zone.dart:1122:38)
      #135    _CustomZone.run (dart:async/zone.dart:1023:19)
      #136    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #137    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
      #138    _rootRun (dart:async/zone.dart:1126:13)
      #139    _CustomZone.run (dart:async/zone.dart:1023:19)
      #140    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
      #141    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
      #142    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
      #143    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
      #144    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


[33m![39m Doctor found issues in 5 categories.
```

**Comment by jonahwilliams** [comment] 2020-02-26 00:37
Duplicate of https://github.com/flutter/flutter/issues/50902

**Closed by jonahwilliams** 2020-02-26 00:37 UTC
