### ISSUE TITLE
Confusion over pendingCompletePurchase for in_app_purchase

### ISSUE THREAD

**Issue by mvrsn** [flutter/flutter#78046] opened 2021-03-12 17:39 UTC
### Background
I'm trying to use the `in_app_purchase` package but  there is one thing I don't fully understand in regards to the `pendingCompletePurchase` property in `PurchaseDetails`

The comment for the property states the following
> The developer has to call [InAppPurchaseConnection.completePurchase] if the value is `true` and the product has been delivered to the user.

I've followed this instruction and called `completePurchase()` and after that I send the verification data to my backend and acknowledge the purchase, but when I reload the subscriptions with `queryPastPurchases` the `pendingCompletePurchase` property is still `true`. 

Is this intentional?

After some more investigation I see that in the `PurchaseDetails.fromPurchase(PurchaseWrapper purchase)` method the `purchase` object has a property named `isAcknowledged` which is `true`.

### Question
Shouldn't the `isAcknowledged` property also be used to decide if the `pendingCompletePurchase` property should be set to `true` or not? Alternatively the `isAcknowledged` property (or something similar to indicate that the purchase has been finalized) could also be made available in the `PurchaseDetails` object

PS: I've only looked at this from the Android side so far so I'm not yet aware of if there are big differences in how payments are processed and acknowledged with the App Store

**Comment by darshankawar** [comment] 2021-03-15 07:22
@mvrsn 
For `pendingCompletePurchase`, see [this](https://github.com/flutter/flutter/issues/51773) issue and it's underlying comments.

For `isAcknowledged`, see [this](https://github.com/flutter/flutter/issues/53606#issuecomment-683374418) issue comment.

Let us know if above clears your doubts.

**Comment by mvrsn** [comment] 2021-03-17 18:46
@darshankawar I've read through both linked issues but they don't really answer my question

According to the comment for `PurchaseDetails.pendingCompletePurchase` it seems that it should be `false` if a purchase has been acknowledged, but that is not the case today

I believe this could be done by checking `PurchaseWrapper.isAcknowledged ` in `PurchaseDetails.fromPurchase()`, but I'm not sure if maybe it's intentional that the `pendingCompletePurchase` is behaving the way it does? 

I think changing this could prevent some developer confusion (if it is a correct change)

**Comment by darshankawar** [comment] 2021-03-18 05:35
Thanks for clarifying @mvrsn.

**Comment by mvanbeusekom** [comment] 2021-05-20 11:28
Hi @mvrsn, this is working as intended. The `queryPastPurchases` method should be used (especially on iOS) to restore purchases in cases where a user moves to a new device or reinstalls the app after having removed it from the device. On iOS this will create new transactions which each in turn need to be verified and also completed (see also [Apple's documentation](https://developer.apple.com/documentation/storekit/in-app_purchase/restoring_purchased_products?language=objc)).This is also the reason why the method got renamed to `restorePurchases` as off version 0.6.0 of the in_app_purchase plugin.

I will close this issue now; however if you feel this doesn't fully answers your question please don't hesitate to leave a comment and I would be happy to re-open the issue and have a more detailed investigation.

**Closed by mvanbeusekom** 2021-05-20 11:28 UTC
Labels: P4, a: quality, documentation, p: first party, p: in_app_purchase, passed first triage, plugin
