### ISSUE TITLE
Android 9 Pie Keypad does not appear in TextField

### ISSUE THREAD

**Issue by vijayanmmm** [flutter/flutter#28211] opened 2019-02-20 15:20 UTC
After the new update 10 hours ago, the keypad for Android 9 is not opening. Before also it wasn't working, yesterday updated to new version then this issue disappeared. But now again the same. It's been two weeks i am fighting with it,

Flutter 1.2.2-pre.22 • channel master • https://github.com/flutter/flutter.git
Framework • revision dd23be3936 (10 hours ago) • 2019-02-19 21:35:31 -0800
Engine • revision f45572e95f
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

Build.gradle.
minSdkVersion 21
In compileSdkVersion & targetSdkVersion - tried different combinations from 26 to 28, doesn't help.

Using Firebase-auth & cloudfirestore packages, Tried with two settings (with AndroidX and without)
  firebase_auth: ^0.7.0
  cloud_firestore: 0.8.2+1
as well as
  firebase_auth: ^0.8.0
  cloud_firestore: 0.9.0+1

**Comment by zoechi** [comment] 2019-02-20 15:29
Tentatively adding `today`.

**Comment by jonahwilliams** [comment] 2019-02-21 02:03
Duplicate of https://github.com/flutter/flutter/issues/28218

**Closed by jonahwilliams** 2019-02-21 02:03 UTC
Labels: a: text input, e: device-specific, engine, severe: regression, ▣ platform-android, ⚠ TODAY
