### ISSUE TITLE
[google_maps_flutter] add support to customize pins and info window

### ISSUE THREAD

**Issue by hewa-jalal** [flutter/flutter#67199] opened 2020-10-03 05:59 UTC
i recently worked with maps in my app and when i was about to put the markers and info windows in my app i thought this will be very easy as i will be able to provide my own widget to them like everything else in flutter! but to my surprise i can't! and they are just built-in with zero customizations choices, and to add your own custom markers and info windows and it required a lot of unnecessary code, we need them to be turned to widgets so it can be fully customizable like everything else in flutter.

**Comment by darshankawar** [comment] 2020-10-05 09:20
@hiwa-jalal 
Please provide `flutter doctor -v`, plugin version and a minimal code sample that shows the issue you are facing and how would you like the markers and info windows to be customised to achieve your requirement.
Thanks.

**Comment by hiwa-jalal** [comment] 2020-10-05 15:47
the output of flutter doctor 
```[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)
    • Flutter version 1.22.0 at C:\flutter
    • Framework revision d408d302e2 (6 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0) 
    • Android SDK at C:\Users\hiwad\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\hiwad\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.3)
    • VS Code at C:\Users\hiwad\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```
when we need to add markers to our map the only way you can do it is using the `Marker` class
like this 
```dart
_markers.add(
          Marker(
            markerId: MarkerId('0'),
            position: _center,
            infoWindow: InfoWindow(title: 'Title', snippet: 'Snippet'),
          ),
        ));
```
but `Marker` is just a built-in class and provide us almost 0 customizability which is something we are not used on as flutter developers, we used to rendering our custom widgets everywhere but here we can't do that and we must go with the built-in `Marker` class, so i am suggesting just let us use any `Widget` as a marker so we can have full customizability, the [flutter_map](https://pub.dev/packages/flutter_map) package already does this here is a sample of it's code
```dart
 layers: [
      new TileLayerOptions(
        urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
        subdomains: ['a', 'b', 'c']
      ),
      new MarkerLayerOptions(
        markers: [
          new Marker(
            width: 80.0,
            height: 80.0,
            point: new LatLng(51.5, -0.09),
            builder: (ctx) =>
            new Container(
              child: new FlutterLogo(),
            ),
          ),
        ],
      ),
    ],
```
as you can see we can put any `Widget` in place of that container and it will be displayed as a marker on the map, the same thing is for info windows it's just like the `Marker` class that is built-in and doesn't give us customizability options so i am suggesting that both those built-in classes be replaced with `Widget` so we can provide our own custom widget for the map markers and it's info window.

**Comment by Sammius** [comment] 2020-10-06 09:20
@hiwa-jalal, we are all waiting for this :)

I don't think this will be done quickly. So I found a temporary trick:

1. For each marker, I make two widgets, a main marker and a marker with infoWindow.
2. Convert them into `Uint8List` using the [createImageFromWidget](https://stackoverflow.com/questions/64132115/how-to-create-an-image-from-a-widget-in-flutter-web) function.
3. Create two `Set`s: `mainMarkers` and `infoMarkers`. 
4. In the `onTap` of the main markers, I put the `_currentMarker = markerId` and redraw the map forming a set of markers from the `mainMarkers` with replacing the `_currentMarker` with an `infoMarker`.

It doesn't look bad for a temporary solution, but as stated in the link above, this solution is not suitable for the Web (I had to come up with other tricks). And of course no animation.

**Comment by hiwa-jalal** [comment] 2020-10-11 20:38
thank you for the help @Sammius

**Comment by DanielRobert1** [comment] 2020-10-30 10:56
Please we need this fixed asap. Please  Please Please.

**Comment by ChristianEdwardPadilla** [comment] 2022-10-17 13:58
Bumping this a bit since there is a Google app that would like this feature.

**Comment by stuartmorgan** [comment] 2023-03-02 15:47
Closing as a duplicate of https://github.com/flutter/flutter/issues/52878 and https://github.com/flutter/flutter/issues/24213.

**Closed by stuartmorgan** 2023-03-02 15:47 UTC
Labels: new feature, plugin, p: maps, passed first triage, P5
