### ISSUE TITLE
Failed to find snapshot: Frameworks/App.framework/flutter_assets/kernel_blob.bin

### ISSUE THREAD

**Issue by gfranks** [flutter/flutter#33292] opened 2019-05-24 03:56 UTC
Application stuck on splash screen for iOS builds. I've researched other issues similar to this and have tried each approach including recreating the `ios` directory multiple times but to no avail. 

## Steps to Reproduce

These steps cannot be fully listed but I'll list what I can
1. Create a new flutter app
2. Create 2 targets/schemes (flavors)
3. Create entry points for each target/flavor (lib/main_flavor1.dart, lib/main_flavor2.dart)
4. Create xcconfigs for each configuration variant and set the appropriate flutter values

```
(i.e. 
    Release-flavor1.xcconfig, 
    Release-flavor2.xcconfig,
    Debug-flavor1.xcconfig,
    Debug-flavor2.xcconfig,
    Ad-Hoc-flavor1.xcconfig,
    Ad-Hoc-flavor2.xcconfig
)
```

```
FLUTTER_TARGET=lib/main_flavor<#>.dart
FLUTTER_BUILD_MODE=release/debug (adhoc and release use "release")
```
5. Deploy to fabric beta via Bitrise workflow using custom script with these commands

```
gym(
      workspace: "./Runner.xcworkspace",
      scheme: "flavor1", 
      configuration: "Ad Hoc",
      export_method: "ad-hoc",
      clean: true
)

crashlytics(
      api_token: ENV["CRASHLYTICS_API_TOKEN"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
      groups: "Fabric Test Group",
      crashlytics_path: "./Pods/Crashlytics/submit",
      notes: last_git_commit[:message]
)
```

6. Install build from fabric beta and launch

## Logs

```
default	23:26:19.423222 -0400	backboardd	[BKEventFocusManager] Setting foreground application to: com.lawntap.partner-adhoc (1613)
default	23:26:19.453794 -0400	partner	Failed to find snapshot: /var/containers/Bundle/Application/0EE686C6-F8D4-4382-9D36-BDE81F379807/partner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
error	23:26:19.457452 -0400	kernel	Sandbox: partner(1613) deny(1) sysctl-read machdep.cpu.brand_string
default	23:26:19.506812 -0400	partner	Configuring the default Firebase app...

```

## Flutter Analyze

```
@~/Dev/Mobile/lawntap-mobile-flutter (master*)$ flutter analyze
Analyzing lawntap-mobile-flutter...
No issues found! (ran in 4.6s)
```

## Flutter Doctor

```
@~/Dev/Mobile/lawntap-mobile-flutter (master*)$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/franks/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/franks/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/franks/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (2 available)
    • iPhone X  • XXXXXXXXXXXXXXXX • ios • iOS 12.3
    • iPhone Xʀ • 4A8911A8-2BBA-47B8-B962-AE3AC7C003A8     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

### Versions
CocoaPods: `COCOAPODS: 1.7.0`
Bundler: `1.16.1`

Builds ran via xcode (Run command uses debug configuration for each flavor) have no issues both with the simulator and a real device. I am able to fully load past the splash screen. Android has no issues deploying and running.

When I build and run locally, the following files are included in the `flutter_assets` but when building a release version with the above steps, they are missing.

<img width="305" alt="Screen Shot 2019-05-24 at 1 32 36 AM" src="https://user-images.githubusercontent.com/2064984/58304851-04da7b00-7dc4-11e9-82f8-b627a599866a.png">

**Comment by matthewlloyd** [comment] 2019-05-24 22:12
I've been seeing this issue frequently over the last few days. I recreated my `ios` directory which fixed the issue temporarily, but it came back. 

What I learned is that it is expected that kernel_blob.bin is not present in release builds, because that file contains your Dart sources in bytecode form ready for JIT, but release builds don't use JIT, they use AOT and your Dart files are compiled into a binary that is placed under App.framework. Rather, this error happens because the release build of the app is incorrectly incorporating the debug (i.e. JIT) version of the Flutter engine.

The best solution I've found so far is to move the build folder to the trash (`flutter clean` is not working and hangs indefinitely on deleting the build folder for some reason), run `flutter clean`, run `flutter build ios --release` from the command line first, then (in my case) create the archive in Xcode.

**Comment by gfranks** [comment] 2019-05-24 23:54
@matthewlloyd this was very helpful. I was able to test this locally and deploy a binary to fabric. After installing, I was finally able to get past the splash screen. Next up, writing a script for bitrise to follow this paradigm and hopefully get the same result. Thanks for the advice.

**Comment by gfranks** [comment] 2019-05-25 01:39
Posting additional info for anyone here experiencing this issue with any CI tool. The following seemed to work pretty well and each binary was successfully built and uploaded to fabric beta.

Using Bitrise and fastlane
Bitrise uses a Script Runner with the following. In my case, I have 2 different flavors. Not the usual `debug` and `production` you see in samples showing flavor usage, but rather 2 completely different products using a shared code base.

Between each build, run `clean` and `build ios` on each flavor you wish to build and distribute.
```
flutter clean
flutter build ios --flavor <flavor> -t lib/main_<flavor>.dart --release
cd $PWD/ios
fastlane <lane> (uses gym and crashlytics for building and distribution)
cd ../
flutter clean
flutter build ios --flavor <flavor> -t lib/main_<flavor>.dart --release
cd $PWD/ios
fastlane <lane> (uses gym and crashlytics for building and distribution)
```

**Comment by matthewlloyd** [comment] 2019-05-25 02:03
It might be worth reopening the issue since the underlying issue is a serious one and needs addressing by the Flutter team.

**Comment by atsu85** [comment] 2019-07-31 20:31
I encountered similar problem - after installing flutter APP from TestFlight (while running debug build locally works fine on real iPhone) it freezes with white screen before app content is loaded and console contains:
`Failed to find snapshot: /var/containers/Bundle/Application/4D93C808-D050-4661-911E-65DBA8856B32/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin`
In my case i'm not using multiple flavors and my build directory isn't versioned, so in CI server running `flutter clean` before `flutter build ios --release` isn't changing anything.

I started seeing this issue after updating flutter version from 1.5.8 to 1.6.0 (same with 1.7.8-hotfix.4) but really weird thing is that it also happens when flutter/dart versions remain the same
```bash
flutter doctor -v
[✓] Flutter (Channel unknown, v1.5.8, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 1.5.8 at /Users/distiller/flutter
    • Framework revision 0ba67226ee (3 months ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)
```
and i remove all plugins and application specific custom code by:
* removing almost all dependencies from pubspec.yaml except cupertino_icons
* running `flutter pub get` to update pubspec.lock file
* running `cd ios && pod install` to update ios/Podfile.lock
* removing all code from lib folder, except lib/main.dart that i reverted back to bare minimum, so it would just show some text when app is successfully loaded, no other functionality at all.
* committing everything, pushing to CI server

**Comment by hasen6** [comment] 2019-08-11 17:20
I had the same problem with the same error message when running the app on a real device for the first time. I tried `flutter build ios --release`, then cleaned the build folder and then it worked ok.

**Comment by iapicca** [comment] 2019-10-09 14:26
Hi @gfranks 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-08 11:02
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 11:02 UTC
Labels: waiting for customer response

**Comment by mesonny** [comment] 2019-11-09 06:30
I confirm encountering this problem when build release version of iOS and archive it.
When launching the app, an error message "Runner	Failed to find snapshot: /private/var/containers/Bundle/Application/014A6351-4794-415A-901B-5B4203BD98F9/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
"
the app cannot even show first viewcontroller, it just closed.

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale zh-Hant-TW)
    • Flutter version 1.9.1+hotfix.6 
    • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME 
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 11 •• ios • iOS 13.2.2

**Comment by prabh045** [comment] 2019-12-04 09:01
I am experiencing the same thing  i tried following
>running flutter clean and then flutter run --release
>changing flutter channel to beta and master
>deleting build folder and then flutter clean and flutter run --release
>flutter clean > flutter build ios > archive in Xcode to test on the test flight

it still persists and i dont know what to do

**Comment by thanhhai08sk** [comment] 2020-03-28 09:12
I'm still experiencing this problem. Tried to delete the ios folder, sometimes it works but now it doesn't anymore.

**Comment by iapicca** [comment] 2020-04-03 09:15
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
