### ISSUE TITLE
Postsubmit checks are running out of order

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#71492] opened 2020-12-01 18:26 UTC
Builds on master are executing in the wrong order, or are not reflecting the right commit. 
Earlier commits are reflecting failures caused by changes that landed after them.

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20framework_tests/1217/overview 
This build (from https://github.com/flutter/flutter/commit/0a08f8afffb129f46610b18c528dbed058ca82c4) is showing failures caused by a change that landed 6 minutes later, https://github.com/flutter/flutter/commit/e244724794b0cb700b5d3c0096c9a1463e06c8e9

**Comment by christopherfujino** [comment] 2020-12-01 18:51
For the same build, the gitiles input commit is `0a08f8afffb129f46610b18c528dbed058ca82c4`, but per the logs, it's actually checking out `e244724794b0cb700b5d3c0096c9a1463e06c8e9`

![Uploading Screen Shot 2020-12-01 at 10.50.16 AM.png…]()

**Comment by christopherfujino** [comment] 2020-12-01 19:19
Ok, I think I found the cause of this, working on a fix now.

**Comment by christopherfujino** [comment] 2020-12-01 20:20
https://flutter-review.googlesource.com/c/recipes/+/9080 should fix this

**Comment by christopherfujino** [comment] 2020-12-01 20:46
fixed in https://flutter-review.googlesource.com/c/recipes/+/9080

**Closed by christopherfujino** 2020-12-01 20:46 UTC
Labels: P1, team: infra
