### ISSUE TITLE
Framework Error When Replacing Column with Row Using CrossAxisAlignment.stretch

### ISSUE THREAD

**Issue by loairebouh** [flutter/flutter#160732] opened 2024-12-22 09:54 UTC
### Steps to reproduce

If the code works fine with Column but causes a framework error when replaced with Row, the issue might stem from the Row widget requiring additional constraints to layout its children properly, particularly when crossAxisAlignment: CrossAxisAlignment.stretch is applied.

In Flutter, Row attempts to layout its children horizontally within its available width. When crossAxisAlignment: CrossAxisAlignment.stretch is used in a Row, it stretches its children vertically, which might conflict with their layout constraints, causing an error.

```dart
child: Row( // Replace Column with Row
  crossAxisAlignment: CrossAxisAlignment.stretch,
  children: [
    Container(
      height: 100,
      width: double.infinity,
      margin: const EdgeInsets.only(left: 30),
      color: Colors.white,
      child: const Text("Container 1"),
    ),
    const SizedBox(
      height: 20,
    ),
    Container(
      height: 100,
      width: double.infinity,
      margin: const EdgeInsets.only(left: 30),
      color: Colors.blue,
      child: const Text("Container 2"),
    ),
    const SizedBox(
      height: 20,
    ),
    Container(
      height: 100,
      width: double.infinity,
      margin: const EdgeInsets.only(left: 30),
      color: Colors.orange,
      child: const Text("Hello"),
    ),
    const SizedBox(
      height: 20,
    ),
  ],
),
```

### Expected results

The Row should layout the Container widgets horizontally without errors, applying the specified constraints.

### Actual results

The application throws a framework error when using Row with crossAxisAlignment: CrossAxisAlignment.stretch.

### Code sample

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Row( // Replace Column with Row to reproduce the issue
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Container(
              height: 100,
              width: double.infinity,
              margin: const EdgeInsets.only(left: 30),
              color: Colors.white,
              child: const Text("Container 1"),
            ),
            const SizedBox(
              height: 20,
            ),
            Container(
              height: 100,
              width: double.infinity,
              margin: const EdgeInsets.only(left: 30),
              color: Colors.blue,
              child: const Text("Container 2"),
            ),
            const SizedBox(
              height: 20,
            ),
            Container(
              height: 100,
              width: double.infinity,
              margin: const EdgeInsets.only(left: 30),
              color: Colors.orange,
              child: const Text("Hello"),
            ),
            const SizedBox(
              height: 20,
            ),
          ],
        ),
      ),
    );
  }
}
```
### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1 24B83 darwin-arm64, locale
    en-US)
    • Flutter version 3.24.5 on channel stable at
      /opt/homebrew/Caskroom/flutter/3.24.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (6 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/aoue42/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Users/aoue42/Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-16.0.0-Beta.app/Contents/Developer
    • Build 16A5171c
    ✗ CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS platform code.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/to/platform-plugins
      For installation instructions, see
      https://guides.cocoapods.org/using/getting-started.html#installation

[✗] Chrome - develop for the web (Cannot find Chrome executable at
    /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.2)
    • Android Studio at /Users/aoue42/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.3)
    • IntelliJ at /Users/aoue42/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 243.22562.3

[✓] VS Code (version 1.96.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             •
      android-arm64 • Android 14 (API 34) (emulator)
    • LOAI’s Iphone (mobile)          • 00008130-00180C2C2168001C • ios
      • iOS 18.2 22C5142a
    • macOS (desktop)                 • macos                     • darwin-arm64
      • macOS 15.1 24B83 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin
      • macOS 15.1 24B83 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by maheshj01** [comment] 2024-12-28 01:30
Hi @loairebouh, This is working as intended.
> The Row should layout the Container widgets horizontally without errors,

Your containers should have a finite width inorder to place them in a row. Closing as solved.

**Closed by maheshj01** 2024-12-28 01:30 UTC
Labels: in triage
