### ISSUE TITLE
[GoRouter] initial location ignored when `getInitialRoute` is overridden in Android

### ISSUE THREAD

**Issue by opxdelwin** [flutter/flutter#132557] opened 2023-08-15 08:33 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

From issue #132402 

When initalRoute is mentioned in `MainActivity.kt`, GoRouter's initalRoute doesn't work. Implemeneted in [2275](https://github.com/flutter/packages/pull/2275)

```dart
package com.example.go_route.test_go_route

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
    override fun getInitialRoute(): String? {
        return "/home"
    }

}
```

### Proposal

Implement a new optional bool parameter such as `overridePlatformDefaultLocation`, which would override platform set initial location.

**Comment by chunhtai** [comment] 2023-08-17 21:44
a  duplicate of https://github.com/flutter/flutter/issues/132402

**Closed by chunhtai** 2023-08-17 21:44 UTC
Labels: package, c: proposal, p: go_router, team-go_router
