### ISSUE TITLE
ListTile Exception Error

### ISSUE THREAD

**Issue by dingowhiz** [flutter/flutter#54002] opened 2020-04-04 17:09 UTC
when rendering a card widget, encountered exception error 

```bash
"EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (18785): The following assertion was thrown during performLayout():"

Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 14 pixels on the bottom.

The relevant error-causing widget was
    Column 
lib\widgets\header.dart:19
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.


[  +27 ms] executing: [C:\Tech\Flutter\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +335 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [C:\Tech\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +383 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[  +18 ms] executing: [C:\Tech\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +321 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Tech\Flutter\flutter\] git ls-remote --get-url origin
[ +256 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +353 ms] executing: [C:\Tech\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[ +313 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +101 ms] "flutter run" took 413ms.

```

```console
<!-- [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\Tech\Flutter\flutter
    • Framework revision f139b11009 (5 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2 -->

```

**Comment by dingowhiz** [comment] 2020-04-04 17:12
trying to render a card widget on a HuaWei Y6 Pro 2019 (MRD LX2) using ListTile widget and encounter exception error as displayed on Y6 "BOTTOM OVERFLOWED BY 14 PIXELS

**Comment by enricobenedos** [comment] 2020-04-05 09:20
It seems only a widgets usage error, not a Flutter one. 
You are using a Column that is a non scrollable widget. Try to wrap your column on [SingleChildScrollView](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html) or substitute it with [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html) widget.
Please close it.

**Comment by iapicca** [comment] 2020-04-06 07:03
Hi @dingowhiz 
I agree with @enricobenedos assessment
as the log suggest the error appears to be caused by the app's code
rather than flutter itself

Closing, as this isn't an issue with Flutter itself;

if you disagree please write in the
providing your `flutter doctor -v` , 
your `flutter run --verbose`,
and  a reproducible minimal code sample
and I will reopen the issue.
Thank you

**Closed by iapicca** 2020-04-06 07:03 UTC
