### ISSUE TITLE
Flutter log prints thousands of verbose/spam logs

### ISSUE THREAD

**Issue by Omi231** [flutter/flutter#51281] opened 2020-02-23 07:44 UTC
I am trying to debug a complex app but flutter printing so much verbose that it is difficult for me to find things which i am printing.

Is there any way to set log level or disable default log entirely?

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] VS Code, 64-bit edition (version 1.42.1)
[√] Connected USB device (1 available)

## Steps to Reproduce

1. Run `flutter run`.

**Expected results:** 
print('Pls print this line');

**Actual results:** 

<details>
  <summary>Logs</summary>

- Tens/Hundreds of system debug messages
- I/flutter ( 9154): Pls print this line
- Tens/Hundreds of system debug messages

```
```

```
```

```
```

</details>

**Comment by phemmelliot** [comment] 2020-02-23 10:22
If you use android studio, you can check out this S/O post [Flutter disable system debug messages in Run Tab](https://stackoverflow.com/questions/55437643/flutter-disable-system-debug-messages-in-run-tab)

**Comment by TahaTesser** [comment] 2020-02-24 09:08
Duplicate of [#50808](https://github.com/flutter/flutter/issues/50808)

**Closed by TahaTesser** 2020-02-24 09:08 UTC
