### ISSUE TITLE
Do make API Docs fonts better

### ISSUE THREAD

**Issue by asavchuk** [flutter/flutter#86988] opened 2021-07-24 15:41 UTC
Fore some reason the fonts used in api docs looks not too clear. Here's  screnhotts from Chrome & Firefox, there is almost no difference in quality. How about changing those fonts?
https://i.ibb.co/HH25mCv/chrome.png
https://i.ibb.co/FXd0QCF/firefox.png

**Comment by TahaTesser** [comment] 2021-07-26 10:26
Hi @asavchuk 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/84505
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-26 10:26 UTC
Labels: in triage
