### ISSUE TITLE
[iPad][iOS] Some functions of Scribble doesn't work (text deletion, space insertion)

### ISSUE THREAD

**Issue by meowofficial** [flutter/flutter#122013] opened 2023-03-06 13:28 UTC
Scrible doesn't work on all flutter channels stable 3.7.6, beta 3.8.0-10.1.pre, and last master version. Tested on iPadOS 16.0 and 16.3.1. On stable and master you can write text, but features such as text deletion, space insertion and others don't work. On beta channel text writing with scribble doesn't work. 

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(),
        body: Container(
          height: double.infinity,
          width: double.infinity,
          color: CupertinoColors.lightBackgroundGray,
          child: Center(
            child: CupertinoTextField(
              scribbleEnabled: true,
              textAlign: TextAlign.center,
            ),
          ),
        ),
        resizeToAvoidBottomInset: false,
      ),
    );
  }
}
```

**Comment by huycozy** [comment] 2023-03-07 05:53
There are some fixes recently related to the scribble function and are available on the **master** channel now. But as your description, some functions don't work. Can you please provide a recorded video along with `Steps to reproduce` this? 

Also, please provide the output of `flutter doctor -v` as well. Thank you!

**Comment by meowofficial** [comment] 2023-03-07 15:01
@huycozy
```
$ flutter doctor -v
[✓] Flutter (Channel beta, 3.8.0-10.1.pre, on macOS 13.0 22A380 darwin-x64, locale en-GB)
    • Flutter version 3.8.0-10.1.pre on channel beta at /Users/admin/Programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1a0a03a41d (3 weeks ago), 2023-02-16 22:03:58 -0600
    • Engine revision 639e313f99
    • Dart version 3.0.0 (build 3.0.0-218.1.beta)
    • DevTools version 2.21.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8617.8

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone (Evgeniy) (mobile) • e76e0fcd66228b1dafcb0709786bbd6ca0792fb8 • ios            • iOS 15.7.1 19H117
    • macOS (desktop)           • macos                                    • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```


https://user-images.githubusercontent.com/35203503/223460418-b3570467-e5c9-4e70-bca4-aaef78948163.MP4

**Comment by meowofficial** [comment] 2023-03-07 15:10
@huycozy 

```
$ flutter doctor -v
[✓] Flutter (Channel master, 3.9.0-1.0.pre.74, on macOS 13.0 22A380 darwin-x64, locale en-GB)
    • Flutter version 3.9.0-1.0.pre.74 on channel master at /Users/admin/Programs/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bee84a122d (4 hours ago), 2023-03-07 06:35:29 -0500
    • Engine revision 4e6cbe0fc2
    • Dart version 3.0.0 (build 3.0.0-300.0.dev)
    • DevTools version 2.22.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/admin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 72.1.4
    • Dart plugin version 223.8617.8

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPad (Evgeniy) (mobile) • 00008020-001029592629402E • ios            • iOS 16.3.1 20D67
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 110.0.5481.177

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

https://user-images.githubusercontent.com/35203503/223463043-2754f62f-b16f-48a4-baea-c519a68d80e6.MP4

**Comment by huycozy** [comment] 2023-03-08 03:20
Thanks for providing more information. It seems it works on the latest master channel, right? (I don't have the such device so I can not test this right now). If so, feel free to close the issue as it's fixed.

**Comment by meowofficial** [comment] 2023-03-08 06:10
@huycozy No, it doesn't work. Only text recognition seems to work, but features such as text deletion, space insertion and others don't work. This features demonstrated in iPad Settings -> Apple Pencil -> Try scribble.

**Comment by huycozy** [comment] 2023-03-08 08:36
Thanks for confirming this on the latest channels. I can see the wrong behavior in your videos. Labeling the issue for the team's attention.

**Comment by jmagman** [comment] 2023-03-08 18:00
Looks like a duplicate of https://github.com/flutter/flutter/issues/121868

**Closed by jmagman** 2023-03-08 18:00 UTC
Labels: a: text input, platform-ios, framework, a: tablet, f: gestures, has reproducible steps, found in release: 3.7, found in release: 3.8, found in release: 3.9
