### ISSUE TITLE
[web] Images pixelated on CanvasKit

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#79846] opened 2021-04-06 08:32 UTC
## Problem

Running on CanvasKit, all images are pixelated, looking exremely over sharpened.

Here is an illustration:

| HTML renderer | CanvasKit renderer |
| :-----------------: | :-----------------------: |
| ![](https://user-images.githubusercontent.com/19204050/113310085-5c6a9b80-92f7-11eb-80ba-418757a3f649.png) | ![](https://user-images.githubusercontent.com/19204050/113310077-5a084180-92f7-11eb-940a-32269e59b17d.png) |
| ![](https://user-images.githubusercontent.com/19204050/113310105-612f4f80-92f7-11eb-9aaa-18d1fc62e1f2.png) | ![](https://user-images.githubusercontent.com/19204050/113681346-61da3400-96b1-11eb-83af-1fec8aa79806.png) |

### Filter quality

In https://github.com/flutter/flutter/issues/60120#issuecomment-738491339, it is said that this was supposed to be a problem with the default [`FilterQuality` on `Image`](https://api.flutter.dev/flutter/widgets/Image/filterQuality.html).  
According to that, using `FilterQuality.low` should resolve the problem. However, in the sample images, we **are** indeed using `FilterQuality.low` (or rather, we are using the default filter quality, which is low).

## Version

```
Flutter 2.1.0-12.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5bedb7b1d5 (3 weeks ago) • 2021-03-17 17:06:30 -0700
Engine • revision 711ab3fda0
Tools • Dart 2.13.0 (build 2.13.0-116.0.dev)
```

The app is built using `flutter build web --web-renderer canvaskit` on channel `beta`. The default filter quality on beta is low.

## Related issues

* https://github.com/flutter/flutter/issues/60120, which has been closed. As this is considered as fixed, I opened a new issue.
* Explained it in [the comment](https://github.com/flutter/flutter/issues/60120#issuecomment-811951952) as well.

As the [comment closing the other issue](https://github.com/flutter/flutter/issues/60120#issuecomment-738491339) was written in December 2020, I assume this is a different issue. The current beta version is 3 weeks old. Furthermore, the filter quality is set to `FilterQuality.low`, which should resolve the issue according to the comment.

**Comment by pedromassangocode** [comment] 2021-04-06 09:43
This seems to be a duplicate of https://github.com/flutter/flutter/issues/76513 / https://github.com/flutter/flutter/issues/73714 which was recently fixed by https://github.com/flutter/engine/commit/5dc0408e6c79f2e39f3ac6888ef216b665d9786c / https://github.com/flutter/flutter/pull/74854 respectively.

I'm not sure if those changes are in the beta channel. Can you please try on latest master channel? If the issue persists, please provide your `flutter doctor -v` and a minimal reproducible code sample.
Thank you

**Comment by creativecreatorormaybenot** [comment] 2021-04-06 10:03
If you take a look at https://github.com/flutter/flutter/issues/76513#issuecomment-783759171, the revision should have landed on Feb 22.

The revision on the `beta` channel is from 3 weeks ago (Mar 17).

I feel like it should have landed then, right? @pedromassango

**Comment by nt4f04uNd** [comment] 2021-04-06 13:13
duplicate of https://github.com/flutter/flutter/issues/79645

**Comment by pedromassangocode** [comment] 2021-04-07 08:15
> I feel like it should have landed then, right? @pedromassango

The only way to verify this is to try on master. Can you please provide a reproducible code sample?


> duplicate of #79645

This one seems to  be a different issue, it is related to anti aliasing rather than canvasKit/html renderer.

**Comment by creativecreatorormaybenot** [comment] 2021-04-07 13:11
@pedromassango still the same:

![image](https://user-images.githubusercontent.com/19204050/113871619-9d086000-97a2-11eb-9275-04d4593587c1.png)

```
Flutter 2.1.0-13.0.pre.499 • channel master • https://github.com/flutter/flutter.git
Framework • revision 3dbe7f23c5 (7 hours ago) • 2021-04-07 14:04:02 +0800
Engine • revision 92f4dfb048
Tools • Dart 2.13.0 (build 2.13.0-208.0.dev)
```

**Comment by pedromassangocode** [comment] 2021-04-08 06:29
> Can you please provide a reproducible code sample?

**Comment by creativecreatorormaybenot** [comment] 2021-04-08 16:05
I will unfortunately not get to creating a sample at this time. If someone else experiencing this problem could do so, that would be great!  
Otherwise, I will try to create a sample at a later point.

**Comment by nt4f04uNd** [comment] 2021-04-08 16:11
> This one seems to be a different issue, it is related to anti aliasing rather than canvasKit/html renderer.

you might have misread the OP, i don't know, but the main topic of this issue not that it's related to canvas_kit, but that there's no antialiasing on canvas_kit, which is not the case with html renderer

i tried reproducible from #79645 with both renderers and see the exact same described behavior, which makes this issue a duplicate of it

**Comment by creativecreatorormaybenot** [comment] 2021-04-08 16:15
@nt4f04uNd no, this issue is about CanvasKit (see the title). If you look at the screenshots, you can see the comparison between the images. Using the exact same app, it is over sharpened / pixelated on CanvasKit but not using the HTML renderer.

**Comment by iapicca** [comment] 2021-04-09 08:46
this issue seems to keep coming back https://github.com/flutter/flutter/issues/60120
I think would be great if before closing the issue would be added a test to prevent this from happening again

**Comment by pedromassangocode** [comment] 2021-05-07 10:54
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 10:54 UTC
Labels: in triage, waiting for customer response
