### ISSUE TITLE
[go_router] Could we have a way to get the current GoRouteData?

### ISSUE THREAD

**Issue by GP4cK** [flutter/flutter#115334] opened 2022-11-15 01:27 UTC
## Use case

When using a `ShellRoute`, the Shell widget often depends on the current route. [For example, to calculate the current index in a BottomNavigationBar](https://github.com/flutter/packages/blob/6a03dd47ec86bc69bafae904a99777e8ea952724/packages/go_router/example/lib/shell_route.dart#L154).
Currently, the way to do this is to call `GoRouterState.of(context).location` and manually parse the url, which go_router has already done with the GoRouteInformationParser. If the current route was exposed via the state, instead of 

```dart
if (location.startsWith('/a')) {...}
```

We could do something like 

```dart
if (route is MyRoute) { ... }
```

<details>
<summary>A bit more sophisticated example</summary>
In my app, I have a big top bar which is on every page of the app, pretty similar to the github one actually (a search bar, some navigation items, profile pic etc.). So it's a good candidate to refactor it using a ShellRoute.

However, this top bar includes a section which is dependant on the child route. For example, if you are on the home page, it will display a greeting with your username. If you are on another user's page, it may display their username and their status.

It would really be awesome if I could make all my `TypedGoRoute` extend an abstract class like this:

```dart
abstract class AbstractRoute extends GoRouteData {
  Widget buildTopBarTitle(BuildContext context);
}
```

This way, in my ShellWidget, I could just do:

```dart
final route = GoRouterState.of(context).route;
if (!route is AbstractRoute) return SizedBox();
return route.buildTopBarTitle(context);
```
</details>

## Proposal

Expose the current route in the GoRouterState.

**Comment by ValentinVignal** [comment] 2022-11-15 01:31
I think this is a duplicate of https://github.com/flutter/flutter/issues/107993

**Closed** 2022-11-15 09:40 UTC
Labels: in triage, r: duplicate
