### ISSUE TITLE
_initialButtons == kPrimaryButton': is not true.

### ISSUE THREAD

**Issue by ycg520520** [flutter/flutter#68296] opened 2020-10-16 10:20 UTC
` bash
```
════════ Exception caught by gesture library ═══════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 379 pos 12: '_initialButtons == kPrimaryButton': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      DragGestureRecognizer._checkStart 
package:flutter/…/gestures/monodrag.dart:379
#3      DragGestureRecognizer.acceptGesture 
package:flutter/…/gestures/monodrag.dart:310
#4      GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:158
#5      GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:224
#6      GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:200
...
Event: PointerUpEvent#02b3f(position: Offset(0.0, 667.0))
    position: Offset(0.0, 667.0)
Target: <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════
`
```

**Comment by sidrao2006** [comment] 2020-10-16 10:47
Hello @,
Could you please post the output of `flutter doctor -v`
Thank you!

**Comment by darshankawar** [comment] 2020-10-16 10:49
@ycg520520 
Provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue.

**Comment by ycg520520** [comment] 2020-10-19 01:04
Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
    • Flutter version 1.20.3 at /Users/yangchaoguo/Documents/flutter
    • Framework revision 216dee60c0 (7 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by sidrao2006** [comment] 2020-10-19 02:19
Duplicate of #66454

**Comment by darshankawar** [comment] 2020-10-19 06:59
@ycg520520 
Please upgrade to latest stable and try again to see if it works. If issue persists, please provide minimal complete reproducible code sample that shows the issue.
Thanks.

**Comment by ycg520520** [comment] 2020-10-19 08:45
@darshankawar
Thanks.

**Comment by pedromassangocode** [comment] 2020-11-09 13:18
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-09 13:18 UTC
Labels: in triage
