### ISSUE TITLE
The asynchronous execution order is inconsistent between Android and the web.

### ISSUE THREAD

**Issue by Stitch-Taotao** [flutter/flutter#151579] opened 2024-07-11 06:37 UTC
### Steps to reproduce

Run code bellow in Android platform and web individually.
Click floatingButton and see result.
Execution order should same in different platform,otherwise, it could potentially lead to **_critical bugs_**, or we may have to discuss implementing different logic for different platforms(But I'm not sure if the specific behavior will change with different versions. And I think it should not be handled this way).

### Expected results

Console log result should be same.

### Actual results

1. On Web:
res:0
res:2

1. On Android :
res:0
res:0

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          test1();
          res = 2;
        },
        child: Icon(Icons.add),
      ),
    );
  }

  int res = 0;
  void test1() async {
    print("res:$res");
    await syncAction();
    print("res:$res");
  }

  Future<int> syncAction() {
    return SynchronousFuture(1);
  }
}
```

</details>

### Logs

flutter version : 3.22.2 stable 

### Flutter Doctor output

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [版本 10.0.22631.3737], locale zh-CN)
    • Flutter version 3.22.2 on channel stable at C:\Users\letpub_it_data\fvm\versions\3.13.9
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

**Comment by danagbemava-nc** [comment] 2024-07-11 08:48
Hi @Stitch-Taotao, I'm curios, why don't you make `test1` return a future so that you can await it in the FloatingActionButton onPressed function?

**Comment by Stitch-Taotao** [comment] 2024-07-11 08:59
This is just an example to illustrate the inconsistency in execution across different platforms. 

Yes, prefixing test1 with await in the example can ensure that res = 2; always executes after test1, but this only holds true in this context because onTap can accept an async function.

However, in some contexts, there isn't an async function , and I cannot add await. So, this example is merely for demonstrating the inconsistent behavior.

**Comment by danagbemava-nc** [comment] 2024-07-12 07:27
Reproducible using the code sample provided above. This may be due to how the web works in general rather than a bug specific to flutter. Labeling for further insight 

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.22.2 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (5 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (4 available)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.127
    ! Error: (null) needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
  
```
[✓] Flutter (Channel master, 3.24.0-1.0.pre.93, on macOS 14.4.1 23E224 darwin-arm64, locale en-GB)
    • Flutter version 3.24.0-1.0.pre.93 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dddea4d155 (7 hours ago), 2024-07-11 17:16:10 -0700
    • Engine revision 36dccf7bb2
    • Dart version 3.6.0 (build 3.6.0-26.0.dev)
    • DevTools version 2.37.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode-15.3.0.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 77.2.2
    • Dart plugin version 232.10286

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.92.0

[✓] Connected device (4 available)
    • Nexus (mobile)                  • 00008020-001875E83A38002E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.127
    ! Error: (null) needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and unlocked. (code 1)
    ! Error: Browsing on the local area network for Dean’s iPad. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by mraleph** [comment] 2024-07-12 08:09
Don't use `SynchronousFuture` with `await`. It violates existing `Future` contract and leads to undefined non-portable behavior. 

Behavior you get on the Web is not correct, `await f` should not resume synchronously (according to the current semantics). Native behavior is more in line with what is currently expected and specified.

cc @nshahan @sigmundch 
cc @lrhn

**Comment by Stitch-Taotao** [comment] 2024-07-12 09:11
If SynchronousFuture  cannot be used with await,

If I expect all methods that might return a SyncFuture to be handled synchronously, and those returning a Future to be handled asynchronously, then I would have to use .then() to handle all future returining methods which I expect maybe a sync process（Because I don't know whether a method controled by user returns a regular Future or a synchronous Future.).

like this :
```
  void test1() async {
    print("res:$res");
    final f = syncAction();

    f.then((e) {
      print("then res:$res");
    });
  }
```

    
This seems to add a significant cognitive load .

Or we must indicate in the documentation that if one expects a Future to potentially complete synchronously, they must use .then() to handle it.

**Comment by lrhn** [comment] 2024-07-12 09:15
`SynchronousFuture.then` _is_ an invalid implementation of to the `Future` API, so there is no guarantee that anything works with it, including `await`.

I'd say that the behavior of `await` of a `SynchronousFuture` on the web is not _wrong_, but it's also not required or even guaranteed.

An `await` of a future must resume at some time after the future has completed. If the future is completed, or was already complete with awaited, we can promise that the resume will happen inside the same microtask queue, but we do not promise when.
The web behavior where computation continues synchronously at the `await` is equivalent to suspending and then resuming in the very next microtask. In that sense it's not _invalid_ behavior. 
It may be accidental that it works, though. 

In general, code should not assume any ordering between unrelated microtasks. 
Related microtasks are tasks scheduled, using `scheduleMicrotask` or `Future. Microtask`, during the same microtask or event callback.

If one thing needs to happen after another, they should synchronize using a future, not rely on microtask ordering.

**Comment by sigmundch** [comment] 2024-07-12 20:35
cc @natebiggs - maybe our upcoming changes to the async lowering in DDC will bring the behavior closer to the native behavior.

Re `SynchronousFuture`: I'm curious if this was meant to have a very limited use within the flutter framework and whether it is worth limiting how it is used (e.g. via a lint). I'm having a hard time seeing where it is better than using `Future.value`.

**Comment by biggs0125** [comment] 2024-07-13 04:27
I reproduced this locally with the old DDC async lowering. And then I confirmed that the new lowering exhibits the same behavior as the VM, it prints `res:0` twice.

This makes sense as it'll call `SynchronousFuture.then` with a callback that re-enters the async function body. The callback will be invoked immediately and so it'll finish executing `test1` before returning back to `onPressed`.

**Comment by a-siva** [comment] 2024-07-17 20:48
@biggs0125 assigning this to you as you have a change in the pipeline to address it.

**Comment by Stitch-Taotao** [comment] 2024-07-24 03:02
I believe the crux of the issue is that the results of executing await and then on a SynchronousFuture are different. In my usual practice, I would assume that then and await serve the same purpose, but now I realize that for a SynchronousFuture, the effects of await and then are distinct. I'm not sure if they should be identical, but I expect await to behave the same as then. Currently, they function identically in the native environment but differently in the web environment. I think the behavior in the native environment is correct. What's your take on this?

You can look at the following example：

On Web: click test1 result 0,1 ; click test2 result 0,0; 
On Native : all button result 0,0;

> The web behavior, where computation continues synchronously at the await, is equivalent to suspending and then resuming in the very next microtask.

@lrhn  I believe that if a SynchronousFuture is detected after an await, it should not suspend and then resume in the very next microtask, but instead, the callback should be executed immediately
### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const App());
}

class App extends StatefulWidget {
  const App({Key? key}) : super(key: key);

  @override
  State<App> createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Flutter Demo',
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(),
      floatingActionButton: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          ElevatedButton(
            onPressed: () {
              test1();
              res++;
            },
            child: const Text("test1"),
          ),
          ElevatedButton(
            onPressed: () {
              test2();
              res++;
            },
            child: const Text("test2"),
          ),
        ],
      ),
    );
  }

  int res = 0;
  void test1() async {
    beginOp();
    await syncAction();
    finalOp();
  }

  Future<int> syncAction() {
    return SynchronousFuture(1);
  }

  void test2() async {
    beginOp();
    final f = syncAction();
    f.then((e) {
      finalOp();
    });
  }

  void beginOp() {
    res = 0;
    print("res:$res");
  }

  void finalOp() {
    print("res:$res");
  }
}

```

</details>

**Comment by lrhn** [comment] 2024-07-24 07:44
> I believe the crux of the issue is that the results of executing await and then on a SynchronousFuture are different

The Crux is that `SynchronousFuture`'s behavior is not valid behavior for a `Future`, so the behavior of `await` of one is unspecified. If `await` had thrown a `StateError` every time it awaited a `SynchronousFuture`, or even a `ConcurrentModificationError`, it would be reasonable behavior.
(The language specification doesn't say that, because it assumes futures behave correctly. It also doesn't say what happens if a `Future` calls its callback twice.)

> I would assume that then and await serve the same purpose, but now I realize that for a SynchronousFuture, the effects of await and then are distinct.

The `then` and `await` serve different, but similar, purposes. The behavior of `SynchronousFuture`, if supported at all, is very visible when using `then`, because the callback happens immediately, synchronously, when calling `then`, before the synchronous continuation of calling `then` gets to run. 
If that continuation depends on the callback not having happened, things break 

Using `SynchronousFuture` with `await` is _less_ visible because it happens at a point where the code would otherwise be suspended, at least if the entire call stack back to the event loop is async functions. It's (exactly) like a call to `then`, where _nothing_ happens in the synchronous continuation, which is therefore not as likely to break. The only difference will then be timing, the code after the `await` won't run until after the future has completed in any case.

That is, if `await` itself doesn't break on a `SynchronousFuture`, which it is allowed to do.

So, it's not correct to say that `then` and `await` should work identically. You can say that they should have equivalent timing for the callback/asynchronous continuation, but that has never been a guarantee. It has never mattered (much) because when it's being called in a later microtask, it doesn't matter as much which later microtask it is. 

The behavior of `SynchronousFuture` is an invalid implementation of the `Future` protocol, so everything about it is unspecified behavior. Being able to continue in the _same_ microtask is very easy to distinguish from a later microtask.

**Comment by biggs0125** [comment] 2024-11-20 23:26
I don't have the ability to close this issue but I don't think there is any more work to do here. `SynchronousFuture` should only be used in very specific places. It doesn't interact predictably with async/await. DDC, dart2js, and the VM should all be aligned on this behavior now.

**Closed** 2024-11-21 08:41 UTC
Labels: dependency: dart, platform-web, has reproducible steps, team-web, :hourglass_flowing_sand:, dependency:dart-triaged, found in release: 3.22, found in release: 3.24
