### ISSUE TITLE
Memory leak in offscreen layout pass

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#8510] opened 2017-03-01 23:32 UTC
## Steps to Reproduce

My Flutter code involves an offscreen layout pass, which is nearly identical to the test in `flutter/test/widgets/independent_widget_layout_test.dart`. Unlike this test, my program performs potentially millions of these offscreen layout passes. Each pass, it creates a new `OffscreenWidgetTree` and calls `pumpWidget()` once on it. After the layout pass, the `OffscreenWidgetTree` instance is not stored. 

My expectation is that the `OffscreenWidgetTree` and all pumped widgets would be garbage-collected, as there is no reference to them in my code. However, it appears from `Observatory` that all pumped widgets continue to be stored in memory for the duration of the program, referenced by a `_registry` variable internal to Flutter. This memory leak prevents my code from being able to make it past ~140k layout passes without using upwards of 30GB of memory. This behavior appears to be no better when the code uses a single `OffscreenWidgetTree` instance for all `pumpWidget()` calls.

Is there some teardown I need to be doing to remove all references to these widgets?

## Flutter Doctor
```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/emshack/flutter
    • Framework revision 83b9142468 (13 days ago), 2017-02-16 22:37:53
    • Engine revision 8218674d4a
    • Tools Dart version 1.22.0-dev.10.6

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1

[✓] IntelliJ IDEA Community Edition (version 2016.3.1)
    • Dart plugin version 163.9166.22
    • Flutter plugin version 0.1.8.1

[✓] Connected devices
    • None
```

**Comment by abarth** [comment] 2017-03-02 06:01
The only `_registry` I see in the framework is the one that's a static member of GlobalKey.  I presume that's the one you mean.

**Comment by abarth** [comment] 2017-03-02 06:05
What happens if you call `pumpWidget(new Container());` after your layout pass?  Does that unregister the objects from the `_registry` variable and remove the leak?

**Comment by abarth** [comment] 2017-03-02 06:06
My theory is that when you let `OffscreenWidgetTree` get garbage collected, the widgets never get unmounted, so they never complete their lifecycle, which means they never unregister themselves.

**Comment by emshack** [comment] 2017-03-02 17:37
Yes, I'm referring to the _registry of GlobalKey.

Calling pumpWidget(new Container()); does not remove the leak, approximately the same amount of memory is used (perhaps slightly more from the extra Containers).

I tried adding a step after the layout pass: `root.visitChildElements((child) {child.unmount();});`
This also did not fix the leak.

**Comment by krisgiesing** [comment] 2017-03-02 23:23
I think what's happening is that the manual layout pass isn't enforcing the desired element lifecycle. The elements are never marked inactive, so they're never unmounted (even if unmount() is called explicitly).

I poked around for a bit but it's not clear what the right solution is here. Can we get some advice from a Flutter dev on this? The test Emily was using as a model is likely also wrong (mea culpa).

**Comment by krisgiesing** [comment] 2017-03-02 23:28
PS. The relevant code looks like this, where pumpWidget is being called many times:

```
class OffscreenWidgetTree {
  final BuildOwner buildOwner = new BuildOwner();
  final PipelineOwner pipelineOwner = new PipelineOwner();
  final Size _rectangleSize;
  RenderView renderView;
  RenderObjectToWidgetElement<RenderBox> root;

  OffscreenWidgetTree(this._rectangleSize) {
    renderView = new OffscreenRenderView(_rectangleSize);
    renderView.attach(pipelineOwner);
    renderView.scheduleInitialFrame();
  }

  void pumpWidget(Widget app) {
    root = new RenderObjectToWidgetAdapter<RenderBox>(
            container: renderView, debugShortDescription: '[root]', child: app)
        .attachToRenderTree(buildOwner, root);
    pumpFrame();
  }

  void pumpFrame() {
    buildOwner.buildScope(root);
    pipelineOwner.flushLayout();
  }

... more methods...
}
```

**Comment by Hixie** [comment] 2017-03-03 00:15
We probably need an explicit `dispose` on the `BuildOwner` and `PipelineOwner` classes that makes sure to detach and unmount everything so that they reach their terminal state.

**Comment by Hixie** [comment] 2017-03-03 00:17
> This behavior appears to be no better when the code uses a single OffscreenWidgetTree instance for all pumpWidget() calls

This is concerning, as is the fact that pumping a `new Container()` doesn't at least reduce the leak substantially (I wouldn't expect it to eliminate it).

**Comment by turnidge** [comment] 2017-09-26 18:10
(I'm studying how flutter users diagnose and fix memory problems, so I'm following this bug - @turnidge)

**Comment by Hixie** [comment] 2017-12-19 03:28
Definitely want to fix this but it's not a priority at this time.

**Comment by markusaksli-nc** [comment] 2020-07-27 11:21
<img src="" width="200" height="400" />

Reproducible on the latest master `1.21.0-6.0.pre.17`.
<details>
 <summary>Minimal reproducible code sample</summary>

 ```
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

const Size _kTestViewSize = Size(800.0, 600.0);

class OffscreenRenderView extends RenderView {
  OffscreenRenderView()
      : super(
          configuration: const ViewConfiguration(size: _kTestViewSize),
          window: WidgetsBinding.instance.window,
        );

  @override
  void compositeFrame() {
    // Don't draw to ui.window
  }
}

class OffscreenWidgetTree {
  OffscreenWidgetTree() {
    renderView.attach(pipelineOwner);
    renderView.prepareInitialFrame();
    pipelineOwner.requestVisualUpdate();
  }

  final RenderView renderView = OffscreenRenderView();
  final BuildOwner buildOwner = BuildOwner();
  final PipelineOwner pipelineOwner = PipelineOwner();
  RenderObjectToWidgetElement<RenderBox> root;

  void pumpWidget(Widget app) {
    root = RenderObjectToWidgetAdapter<RenderBox>(
      container: renderView,
      debugShortDescription: '[root]',
      child: app,
    ).attachToRenderTree(buildOwner, root);
    pumpFrame();
  }

  void pumpFrame() {
    buildOwner.buildScope(root);
    pipelineOwner.flushLayout();
    pipelineOwner.flushCompositingBits();
    pipelineOwner.flushPaint();
    renderView.compositeFrame();
    pipelineOwner.flushSemantics();
    buildOwner.finalizeTree();
  }
}

void main() {
  while (true) {
      pass();
  }
}

void pass() async{
  final OffscreenWidgetTree tree = OffscreenWidgetTree();
  tree.pumpWidget(Container());
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.21.0-6.0.pre.38, on Microsoft Windows [Version 10.0.18362.959], locale et-EE)
    • Flutter version 1.21.0-6.0.pre.38 at C:\Development\flutter_master
    • Framework revision 8e0eee9008 (2 hours ago), 2020-07-26 23:38:01 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30309.148
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Isa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (5 available)
    • sdk gphone x86 (mobile)     • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • sdk gphone x86 arm (mobile) • emulator-5556 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.18362.959]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

**Comment by emshack** [comment] 2024-03-20 17:05
I haven't used Flutter for development in a couple years, so unfortunately I'm not familiar with the latest framework updates. Feel free to close out if this issue is not reproducible.

**Comment by krisgiesing** [comment] 2024-03-20 17:23
The code base against which this issue was filed is no longer around. Let's just close it out.

**Comment by darshankawar** [comment] 2024-03-21 05:16
Closing as obsolete.

**Closed by darshankawar** 2024-03-21 05:16 UTC
Labels: a: tests, c: crash, framework, c: performance, has reproducible steps, P3, found in release: 1.21, team-framework, triaged-framework
