### ISSUE TITLE
[WEB] Weird text field behavior on mobile web

### ISSUE THREAD

**Issue by jperezr21** [flutter/flutter#127444] opened 2023-05-23 23:02 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Visit https://gallery.flutter.dev/#/demo/text-field on a mobile device
2. Try editing a text field and moving the cursor

### Expected results

Single cursor, no white space

### Actual results

Double cursors, white space between keyboard and text field.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/12447726/a30dc781-c81b-4388-8689-df452586fe00

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by stavgafny** [comment] 2023-05-23 23:10
@jperezr21 can you provide a code sample with the minimal code needed to run the example in one file

**Comment by stavgafny** [comment] 2023-05-23 23:17
Weird, just tried it out myself and I get the same behavior.
I'm pretty sure the white space is caused by the keyboard raise because it seems to happen only when tapping on it from the bottom, I could be wrong though.

**Comment by darshankawar** [comment] 2023-05-24 08:07
Thanks for the report @jperezr21 
This seems to be similar to already filed issue https://github.com/flutter/flutter/issues/124205, so please follow-up in it for further updates. You may upvote the original description of the issue to get team's attention and also share your findings in it for better tracking.
Closing this as a duplicate. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-05-24 08:07 UTC
Labels: in triage
