### ISSUE TITLE
Android release build crashes with proguard error

### ISSUE THREAD

**Issue by abacaj** [flutter/flutter#25951] opened 2019-01-02 01:44 UTC
This appears to be new as I have changed no code and was working 2 weeks ago... All i did was flutter upgrade.
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```
Flutter version:
```
[✓] Flutter (Channel master, v1.1.5-pre.38, on Mac OS X 10.13.6
    17G65, locale en-US)
    • Flutter version 1.1.5-pre.38 at /Users/anton/flutter
    • Framework revision b9f9e384cb (9 hours ago), 2019-01-01
      11:47:29 -0500
    • Engine revision b1a9a6e794
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 88e6fe0f67)
```

**Comment by zoechi** [comment] 2019-01-02 07:55
Can you reproduce in `dev` channel?

**Comment by ezraaaa** [comment] 2019-01-02 10:10
I'm having the same problem too. I've tried dev channel and it I'd returning the same thing

**Comment by abacaj** [comment] 2019-01-03 20:56
Yes tried all channels available, same result.

**Comment by remosingh** [comment] 2019-01-06 22:42
same issue....

**Comment by zoechi** [comment] 2019-01-22 08:13
As far as I understand Proguard is currently not fully supported.
I'm closing this as duplicate of #11099

**Closed by zoechi** 2019-01-22 08:13 UTC
Labels: severe: crash, severe: regression, tool, ▣ platform-android

**Comment by xiaoxiaocainiao** [comment] 2019-03-04 06:55
try this one:
`minifyEnabled false`

**Comment by fleetcor** [comment] 2019-04-24 01:08
@xiaoxiaocainiao thanks man, it works!

**Comment by fleetcor** [comment] 2019-04-24 01:56
@xiaoxiaocainiao ， thanks  man, it works!

**Comment by cfguimaraes** [comment] 2019-05-12 03:54
@xiaoxiaocainiao that work for me too. Thank you.

In case some face this problem, the path to setting is `android/app/build.gradle`

**Comment by muammarridho** [comment] 2019-07-14 14:44
@xiaoxiaocainiao it works, thanks bro.

**Comment by dheeraj2dj** [comment] 2019-07-16 04:03
If you are not intending to change `minifyEnabled false`, this worked fine for me - https://github.com/flutter/flutter/issues/19250#issuecomment-469416592

**Comment by gitaaron** [comment] 2019-11-19 02:57
Does this increase the size of the final binary?

**Comment by TobiCrackIT** [comment] 2019-12-06 14:51
**minifyEnabled false** worked

**Comment by Nisthar** [comment] 2019-12-13 07:48
> Does this increase the size of the final binary?

Yes. i wish there was a way to fix this with minify enabled.

**Comment by WBlackstorm** [comment] 2020-07-29 21:56
minifyEnabled false
shrinkResources false

Solved to me.
