### ISSUE TITLE
More fault tolerance for npm-install step on Travis

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#12928] opened 2017-11-08 19:15 UTC
#Flakes seen in both the `coverage` and `docs` slices of the Travis framework build today:

```
+gem install coveralls-lcov
Fetching: coveralls-lcov-1.5.1.gem (100%)
Successfully installed coveralls-lcov-1.5.1
1 gem installed
+npm install -g 'firebase-tools@>=3.6.1 <3.7.0'
npm ERR! fetch failed https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz
npm ERR! Linux 4.13.11-041311-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.12.0/bin/node" "/home/travis/.nvm/versions/node/v6.12.0/bin/npm" "install" "-g" "firebase-tools@>=3.6.1 <3.7.0"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! fetch failed with status code 503
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/flutter/flutter/npm-debug.log
The command "./dev/bots/travis_install.sh" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by DanTup** [comment] 2018-06-27 10:49
Seen this twice today but without the network error output:

```
Successfully installed bundler-1.16.2
1 gem installed
+npm install -g 'firebase-tools@>=3.6.1 <3.7.0'
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

It's on the `docs` shard of the Travis built. I restarted it on the first failure and then it did exactly the same. The NPM status page suggests there are no current issues and Travis status page says "npm, Inc. Registry Reads" are "Operational" 🤔

Closing #13960 as a dupe of this one.

**Comment by DanTup** [comment] 2018-06-28 16:15
Maybe this'll help?

https://github.com/flutter/flutter/pull/18918

It'll retry the npm step up to 5 times with 5 second pauses. I don't think it solves the issue I've been seeing (npm hangs, so the build gets terminated), but might help with when it just fails like the original message posted?

**Comment by DanTup** [comment] 2018-06-28 16:20
Also seems like we're on a > 1yr old version of npm - should we try something newer?

**Comment by zoechi** [comment] 2019-01-24 11:48
Is this still an issue?

**Comment by DanTup** [comment] 2019-01-24 12:16
I've not seen any of these in a long time. Whether NPM got better or the retries in #18918 mask it, I'm not sure, but I think we're probably good to close this. If anyone sees it again, we can easily re-open.

**Closed by DanTup** 2019-01-24 12:16 UTC
Labels: team, team: flakes
