### ISSUE TITLE
[local_auth] getAvailableBiometrics returns fingerprint even if there is no fingerprint registered

### ISSUE THREAD

**Issue by tudor07** [flutter/flutter#87188] opened 2021-07-28 13:00 UTC
I am using `local_auth` version `1.1.6`.
I have a phone (Lenovo P2, Android 7.0) that has fingerprint feature but I did not actually register a fingerprint in the system.
The `getAvailableBiometrics` returns `[BiometricType.fingerprint]` but then if later I call `authenticate` it doesn't ask for fingerprint rightly so since there are none. I am thinking that maybe it should not return fingerprint support from `getAvailableBiometrics` as well, or at least provide some method to check if there is actually a fingerprint registered.

<details>
  <summary>flutter doctor</summary>
Doctor summary (to see all details, run flutter doctor -v):

[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-RO)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)

    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google 

Chrome.app/Contents/MacOS/Google Chrome)

    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio

    ✗ Unable to find bundled Java version.

[✓] Android Studio (version 4.2)

[✓] IntelliJ IDEA Community Edition (version 2021.1.3)

[✓] VS Code (version 1.58.2)

[✓] Connected device (2 available)

! Doctor found issues in 3 categories.
</details>

**Comment by TahaTesser** [comment] 2021-07-28 14:18
Hi @tudor07 
This looks related to https://github.com/flutter/flutter/issues/80259, there are some regressions in the package for authentication. Since it false reports finger is available on this device, I will label this issue and consider it related but not duplicate 
Thanks for fling the issue

**Comment by stuartmorgan** [comment] 2021-07-28 15:42
Duplicate of https://github.com/flutter/flutter/issues/45497

**Closed by stuartmorgan** 2021-07-28 15:42 UTC
Labels: e: device-specific, p: first party, p: local_auth, passed first triage, plugin

**Comment by TahaTesser** [comment] 2021-07-28 16:18
@stuartmorgan 
Thanks, I didn't know there is a no way feature to check if fingerprint is registered.
