### ISSUE TITLE
Serious scrolling and performance issues

### ISSUE THREAD

**Issue by Constans** [flutter/flutter#45605] opened 2019-11-26 11:40 UTC
Serious scrolling issues and overall performance for the web platform since the release of **1.12.6 and up** (**1.12.5** still performed).
Also, images tend to reload endlessly (might be related to the scrolling issue?).
## Steps to Reproduce

1. Create an app that contains nested scrolling widgets (both vertical and horizontal). 
2. Run/build for the web platform. 
3. The vertical scroll works very, very slow. Painfully slow (it seems like an endless redraw, elements jump from place to place). The horizontal scroll doesn't work at all.

**Target Platform:**
Web
**Target OS version/browser:**
macOS Catalina Version 10.15.1 (19B88) / 
Chrome Version 78.0.3904.108 (Official Build) (64-bit) (desktop & mobile)
**Devices:**
Chrome Version 78.0.3904.108 (Official Build) (64-bit)

## Logs

```
flutter doctor -v
[✓] Flutter (Channel unknown, v1.12.5, on Mac OS X 10.15.1 19B88, locale en-NL)
    • Flutter version 1.12.5 at /Users/user/development/flutter
    • Framework revision 2c7af1e24e (6 days ago), 2019-11-20 12:18:44 -0800
    • Engine revision 176f563296
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4694.29

[✓] Connected device (3 available)
    • User’s iPad • 308580731e7fc46b563fe33fe7bc60db5cb8b1ee • ios            • iOS 13.1.3
    • Chrome       • chrome                                   • web-javascript • Google Chrome 78.0.3904.108
    • Web Server   • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

**Comment by Constans** [comment] 2019-11-26 14:03
@iapicca , please note that this is also reported only for the web platform. Thanks!

**Comment by YuhApps** [comment] 2019-11-27 19:26
On version 1.12.11-pre.10, it works fine on desktop. However, on mobile Chrome on Android and iOS, horizontal scroll does not work at all, while vertical scroll is extremely laggy. I tried both ListView and SingleChildScrollView.

**Comment by mikepyts** [comment] 2019-11-28 08:41
We are experiencing similar issues with vertical scrolling on Web platform too

**Comment by Constans** [comment] 2019-11-28 11:02
Versions **1.12.6** and up web builds became so unstable that I decided to play with **1.10.16** for a while (the last stable version for web as far as I've tested regarding rendering and overall performance).
As I've said before, I suppose there are major changes happening across the framework and things get broken on the way.

**Comment by YuhApps** [comment] 2019-11-28 11:32
> Versions **1.12.6** and up web builds became so unstable that I decided to play with **1.10.16** for a while (the last stable version for web as far as I've tested regarding rendering and overall performance).
> Not always the latest is the greatest... :)
> As I've said before, I suppose there are major changes happening across the framework and things get broken on the way.

Thanks man, you've saved me from drowning.

**Comment by Constans** [comment] 2019-11-28 20:15
> On version 1.12.11-pre.10, it works fine on desktop. However, on mobile Chrome on Android and iOS, horizontal scroll does not work at all, while vertical scroll does not work in most cases and when it does, it's very laggy. I tried both ListView and SingleChildScrollView and got the same result.

I messed up the axis. It was the vertical working very badly and horizontal not working at all on mobile.
Also on desktop the story was a bit different: the vertical worked better than on mobile, horizontal scroll worked randomly.

Maybe these mentions help in tracking and resolving the issue. I've also reported some rendering issues that happened in the latest builds (they all might be related).

**Comment by tmtong** [comment] 2019-12-01 16:41
I change my code completely so that there are not too much to render. But I find that it is a flutter issue after upgrade
In the Flutter install directory execute
git checkout v1.10.16
flutter doctor

**Comment by YuhApps** [comment] 2019-12-01 16:52
> > On version 1.12.11-pre.10, it works fine on desktop. However, on mobile Chrome on Android and iOS, horizontal scroll does not work at all, while vertical scroll does not work in most cases and when it does, it's very laggy. I tried both ListView and SingleChildScrollView and got the same result.
> 
> I messed up the axis. It was the vertical working very badly and horizontal not working at all on mobile.
> Also on desktop the story was a bit different: the vertical worked better than on mobile, horizontal scroll worked randomly.
> 
> Maybe these mentions help in tracking and resolving the issue. I've also reported some rendering issues that happened in the latest builds (they all might be related).

The latest version master 1.12.16-pre.35 improves vertical scroll on mobile, but it's still laggy and does not work with horizontal scroll. There's no problem on desktop. However, Safari compatibility is still painful, like Roboto fonts don't apply and some stateful widgets randomly rebuild themselves, like InkWell and Tooltip. But in generall, things are improved.

> I changed my code completely so that there are not too much to render. But I find that it is a flutter issue after upgrade
> In the Flutter install directory execute
> git checkout v1.10.16
> flutter doctor

Version 1.10.16 seems very stable on desktop and mobile Chrome, but it does not work well on Safari. For example, TextAlign.justify.

**Comment by liyuqian** [comment] 2019-12-02 23:22
@yjbanov : can you please take on this issue? This might also be a good opportunity to add our first web scrolling performance test.

**Comment by yjbanov** [comment] 2019-12-03 04:36
This is a duplicate of https://github.com/flutter/flutter/issues/45510. A fix is in the works.

**Closed by yjbanov** 2019-12-03 04:36 UTC
Labels: customer: crowd, f: scrolling, perf: speed, severe: performance, severe: regression, ☸ platform-web

**Comment by yjbanov** [comment] 2019-12-03 04:37
For the image issue what's happening is when you open Chrome dev tools it usually disables image cache. Closing the dev tools or unchecking the "Disable cache" checkbox should help. We are working on a more permanent fix for images as part of https://github.com/flutter/flutter/issues/44845

**Comment by app4app** [comment] 2020-02-27 12:26
> > On version 1.12.11-pre.10, it works fine on desktop. However, on mobile Chrome on Android and iOS, horizontal scroll does not work at all, while vertical scroll does not work in most cases and when it does, it's very laggy. I tried both ListView and SingleChildScrollView and got the same result.
> 
> I messed up the axis. It was the vertical working very badly and horizontal not working at all on mobile.
> Also on desktop the story was a bit different: the vertical worked better than on mobile, horizontal scroll worked randomly.
> 
> Maybe these mentions help in tracking and resolving the issue. I've also reported some rendering issues that happened in the latest builds (they all might be related).

At the official samples is the same...

**Comment by chandrikaReddyBunga** [comment] 2020-05-23 10:16
hi everyone,  i am developing web app but in mobile screens scrolling is very slow how to solve that problem , i am using singlechildscrollview  with column widgets , and listview builder but that two options not working.

**Comment by iapicca** [comment] 2020-05-26 09:58
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by chandrikaReddyBunga** [comment] 2020-05-27 05:31
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

My Flutter version is: Flutter 1.14.6 • channel beta • https://github.com/flutter/flutter.git
