### ISSUE TITLE
Signing errors on iOS pod bundle resources on Xcode 14 "Signing for "x" requires a development team."

### ISSUE THREAD

**Issue by appcapsergen** [flutter/flutter#111475] opened 2022-09-13 13:22 UTC
Since I upgraded to Xcode 14, my Flutter project doesn't run because of Signing issues of iOS pods

Error:
```console
Could not build the precompiled application for the device.
Error (Xcode): Signing for "DKPhotoGallery-DKPhotoGallery" requires a development team. Select a development team in the Signing & Capabilities editor.
{path to project folder}/ios/Pods/Pods.xcodeproj

Error (Xcode): Signing for "DKImagePickerController-DKImagePickerController" requires a development team. Select a development team in the Signing & Capabilities editor.
{path to project folder}/ios/Pods/Pods.xcodeproj

Error (Xcode): Signing for "TOCropViewController-TOCropViewControllerBundle" requires a development team. Select a development team in the Signing & Capabilities editor.
{path to project folder}/ios/Pods/Pods.xcodeproj
```

<details><summary>My project's dependencies (to reproduce the problem, the error is from one of these dependencies and the corresponding iOS Pod)</summary>

```yaml
dependencies:
  flutter:
    sdk: flutter

  # TODO: Switch back to main package when this is merged: https://github.com/jhomlala/betterplayer/pull/1059
  better_player:
    git:
      url: https://github.com/matthewrice345/betterplayer.git
      ref: Issue1057
  blur: 3.1.0
  bugsnag_flutter: 2.2.0
  cached_network_image: 3.2.2
  connectivity_plus: 2.3.6+1
  # Needed for tus_client
  cross_file: 0.3.3+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.5
  device_info_plus: 4.1.2
  dio: 4.0.6
  easy_localization: 3.0.1
  expandable: 5.0.1
  fading_edge_scrollview: 3.0.0
  faker: 2.0.0
  file_picker: 5.0.1
  firebase_analytics: 9.3.4
  firebase_core: 1.22.0
  firebase_messaging: 13.0.1
  flare_flutter: 3.0.2
  flinq: 2.0.2
  flutter_app_badger: 1.4.0
  flutter_facebook_auth: 4.4.1
  flutter_inappwebview: 5.4.3+7
  flutter_keyboard_visibility: 5.3.0
  flutter_local_notifications: 9.9.1
  flutter_polygon_clipper: 1.0.4
  flutter_slidable: 2.0.0
  flutter_spinkit: 5.1.0
  flutter_staggered_grid_view: 0.6.2
  flutter_svg: 1.1.5
  fluttertoast: 8.0.9
  font_awesome_flutter: 10.2.1
  form_field_validator: 1.1.0
  google_maps_flutter: 2.2.0
  html: 0.15.0
  html_unescape: 2.0.0
  http: 0.13.5
  http_parser: 4.0.1
  image_cropper: 3.0.0
  image_downloader: 0.31.0
  image_picker: 0.8.5+3
  intl: 0.17.0
  json_annotation: 4.6.0
  jwt_decoder: 2.0.1
  mime: 1.0.2
  # TODO: Remove this dependency if it is added to the Flutter core: https://github.com/flutter/flutter/pull/67515
  modal_bottom_sheet: 2.1.2
  # Version checking
  package_info_plus: 1.4.3+1
  path: 1.8.2
  path_provider: 2.0.11
  percent_indicator: 4.2.2
  photo_view: 0.14.0
  pin_code_fields: 7.4.0
  provider: 6.0.3
  pusher_client:
    git:
      url: https://github.com/appcapsergen/pusher_client
  scroll_to_index: 3.0.1
  shared_preferences: 2.0.15
  shimmer: 2.0.0
  sign_in_with_apple: 4.1.0
  timeago: 3.3.0
  tus_client: 1.0.2
  uni_links: 0.5.1
  url_launcher: 6.1.5
  uuid: 3.0.6
  video_player: 2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.10.0
  json_serializable: 6.3.1
  linter: 1.28.0
```
</details>

<details><summary>flutter doctor -v:</summary>

```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm, locale en-NL)
    • Flutter version 3.3.1 on channel stable at {path to Flutter folder}
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (7 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/{user}/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Users/{user}/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/{user}/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/{user}/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8609683/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by uzuki-P** [comment] 2022-09-13 14:39
![Screen Shot 2022-09-13 at 21 33 03](https://user-images.githubusercontent.com/16524713/189930013-9b7860e1-3968-4fbe-b414-bad5fc7661e8.jpg)

For me selecting the team for every error on Xcode actually working. After selecting I can just run flutter using Android Studio.

**Comment by uzuki-P** [comment] 2022-09-13 14:57
Just realised, if you call `pod install` again the team will be unselected again. There's [this method](https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1149585364) tho

**Comment by appcapsergen** [comment] 2022-09-13 16:26
@uzuki-P These solutions don't work with CI tools and multiple Teams for (multiple app flavors)

**Comment by jsmeke** [comment] 2022-09-13 19:45
Same issue here.

**Comment by armandojimenez** [comment] 2022-09-14 02:37
Happens to me after Xcode 14, for it to function I have to select my teams. Also happens every time I run pod install

**Comment by vasscher** [comment] 2022-09-14 04:43
+1

**Comment by danagbemava-nc** [comment] 2022-09-14 06:37
Hi @appcapsergen @uzuki-P @armandojimenez @vasscher  and anyone else experiencing this, please provide a complete minimal sample along with steps to reproduce so that we can investigate this.

Please also provide the output of `flutter doctor -v` as well. 

Thank you

**Comment by KhadgaPortPro** [comment] 2022-09-14 06:57
same issue after upgrading to Xcode 14

**Comment by KhadgaPortPro** [comment] 2022-09-14 07:13
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.6 21G115 darwin-arm, locale en-NP)
    • Flutter version 2.10.5 at /Users/kodega/fvm/versions/2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/kodega/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/kodega/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.5588

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by svartalfheim** [comment] 2022-09-14 07:50
I fixed it by this method.
https://github.com/TimOliver/TOCropViewController/issues/533#issuecomment-1245332415

**Comment by appcapsergen** [comment] 2022-09-14 07:59
Hi @danagbemava-nc ! I added the `flutter doctor -v` to the issue.
The steps to reproduce, however, are simply to implement my dependencies into a Flutter project and installing them for iOS. If you then try to run, it throws that error.
I did not change anything in my project and it worked before, but since I only upgraded my project to Xcode 14, this error occurs.
Hope that helps!

**Comment by uzuki-P** [comment] 2022-09-14 09:39
@danagbemava-nc 
this is the minimal sample
the only thing I add is `file_picker` package

https://github.com/uzuki-P/pod_sign_error_xcode_14

**Comment by kamleshsangani** [comment] 2022-09-14 10:48
You can disable code signing from podfile for all dependencies.

`post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
       end
    end
  end`

**Comment by danagbemava-nc** [comment] 2022-09-14 10:55
Hi @appcapsergen  @uzuki-P, what command do you run or action do you perform that results in the signing errors?

**Comment by appcapsergen** [comment] 2022-09-14 10:56
@danagbemava-nc running on an iOS device, aka `flutter run`

**Comment by danagbemava-nc** [comment] 2022-09-14 12:14
@appcapsergen thanks for the info and @uzuki-P, thanks for the repro. 

I think these issues should be reported in the repos of the respective plugins. 

I tested some of the first_party plugins, (`file_selector`, `image_picker`, `video_player`, and `in_app_purchase`) but I was not able to reproduce the issue with them. I was however, able to reproduce the issue with the `file_picker` plugin which might mean that there is an issue with how they are doing their implementation. 

I'm still making my way through the first_party plugins and will update when I am done.

**Comment by uzuki-P** [comment] 2022-09-14 12:45
@appcapsergen 
I believe `google_sign_in` also have problem with it

also a module with that blue icon. I never develop iOS natively before, don't know what it's called
![image](https://user-images.githubusercontent.com/16524713/190157017-dd398c81-0f81-4dd5-92fa-1bc598534531.png)

**Comment by ps9310** [comment] 2022-09-14 19:18
Same issue here with ```google_sign_in``` after xcode 14 upgrade

**Comment by danagbemava-nc** [comment] 2022-09-15 06:56
Yes, during my testing of the first-party plugins I run into this issue with `google_sign_in`. `google_sign_in` depends on the `GoogleSignInIOS` native plugin so I went to the repo to see if there are reports of this. See https://github.com/google/GoogleSignIn-iOS/issues/105 This has been an issue since the beta version of Xcode 14 was released.  

This StackOverflow comment seems to summarise the issue and workaround quite well https://stackoverflow.com/a/39949186. 

This issue most likely has to be fixed by the cocoapods team but for now, I will label for further insight from the tool team. 
The original issue tracking this on cocoapods can be found at https://github.com/CocoaPods/CocoaPods/issues/11402. 


### Steps to reproduce
- Be on Xcode 14
- flutter create bug
- `flutter pub add google_sign_in`
- Select dev team in xcode
- `flutter run` on a physical device

[flutter_run.log](https://github.com/flutter/flutter/files/9572643/flutter_run.log)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.1 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (8 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 16.0 20A362
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 3.4.0-19.0.pre.272, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-19.0.pre.272 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2262892e3b (2 hours ago), 2022-09-15 00:44:22 -0400
    • Engine revision 63cc5ea2b1
    • Dart version 2.19.0 (build 2.19.0-201.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 16.0 20A362
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by AlexV525** [comment] 2022-09-15 08:39
The exact workarounds should be https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1149585364 and https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1188774894.

**Comment by jmagman** [comment] 2022-09-15 17:45
I wonder why I've never seen this locally or in CI in all the months I've been testing the Xcode 14 betas...

**Comment by jmagman** [comment] 2022-09-15 23:01
> I wonder why I've never seen this in CI

It's because we pass in `CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY=""` most places, at least in the framework.

**Comment by nguyen703** [comment] 2022-09-16 06:05
> The exact workarounds should be [CocoaPods/CocoaPods#11402 (comment)](https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1149585364) and [CocoaPods/CocoaPods#11402 (comment)](https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1188774894).

This works like a charm. Thank you!

**Comment by jmagman** [comment] 2022-09-16 17:32
iOS PR out for review at https://github.com/flutter/flutter/pull/111714.  Still need to do macOS.

In the meantime you can workaround this issue until Xcode releases a fix for this, or CocoaPods adds a similar workaround:

1. Open `ios/Podfile`
2. Replace the following:
```diff
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

+   # Workaround https://github.com/flutter/flutter/issues/111475.
+   target_is_resource_bundle = target.respond_to?(:product_type) && target.product_type == 'com.apple.product-type.bundle'
+   target.build_configurations.each do |build_configuration|
+     if target_is_resource_bundle
+       build_configuration.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
+       build_configuration.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
+       build_configuration.build_settings['CODE_SIGNING_IDENTITY'] = '-'
+       build_configuration.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = '-'
+     end
+   end
  end
end
```

macOS workaround looks similar:
1. Open `macos/Podfile`
2. Replace the following:
```diff
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)

+   # Workaround https://github.com/flutter/flutter/issues/111475.
+   target_is_resource_bundle = target.respond_to?(:product_type) && target.product_type == 'com.apple.product-type.bundle'
+   target.build_configurations.each do |build_configuration|
+     if target_is_resource_bundle
+       build_configuration.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
+       build_configuration.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
+       build_configuration.build_settings['CODE_SIGNING_IDENTITY'] = '-'
+       build_configuration.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = '-'
+     end
+   end
  end
end
```

**Comment by jmagman** [comment] 2022-09-16 17:51
My workaround turns off codesigning the resource bundles (images, localization files, etc) as opposed to setting `DEVELOPMENT_TEAM`, which would codesign them.

Can anyone confirm that my posted workarounds work when you validate/submit your app?

**Comment by maxlapides** [comment] 2022-09-16 17:59
> My workaround turns off codesigning the resource bundles (images, localization files, etc) as opposed to setting `DEVELOPMENT_TEAM`, which would codesign them.
> 
> 
> 
> Can anyone confirm that my posted workarounds work when you validate/submit your app? 

I used this workaround and the build was accepted by TestFlight, so I imagine your more robust version will work as well 🙂

![image](https://user-images.githubusercontent.com/1874682/190702996-86e86688-c3e8-4190-8a8a-fdb1bd2e3a2e.jpeg)

**Comment by jmagman** [comment] 2022-09-16 18:01
@maxlapides I'm not sure if that's correct either, I believe the frameworks should be codesigned in your app, only `com.apple.product-type.bundle` should not be codesigned.

**Comment by jmagman** [comment] 2022-09-16 18:01
> @maxlapides I'm not sure if that's correct either, I believe the frameworks should be codesigned in your app, only `com.apple.product-type.bundle` should not be codesigned.

Meaning, are you sure it doesn't crash at runtime?

**Closed** 2022-09-16 18:02 UTC
Labels: tool, customer: crowd, t: xcode, has reproducible steps, P1, found in release: 3.3, found in release: 3.4

**Comment by jmagman** [comment] 2022-09-16 18:19
> > I wonder why I've never seen this in CI
> 
> It's because we pass in `CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY=""` and `--no-codesign` in most places in CI since we don't have certs set up.

Filed https://github.com/flutter/flutter/issues/111760

**Comment by jmagman** [comment] 2022-09-16 18:29
> #111714 has merged to master. Can someone confirm that their app builds and runs on master with codesigning on, without any workaround in your `Podfile`?

Particularly want to validate the App Store submission doesn't complain:
<img width="719" alt="158854586-ac6d815b-8a7d-40da-abc7-fa907a664a05" src="https://user-images.githubusercontent.com/682784/190707195-0b647917-6a9c-4711-bc62-ec8318866d62.png">

If we actually have to codesign this by parsing the `DEVELOPMENT_TEAM` and not skip codesigning this is going to be an extremely tricky workaround on Flutter's end...

**Comment by JagandeepBrar** [comment] 2022-09-17 06:14
@jmagman I did not pull master but I did the changes outlined in https://github.com/flutter/flutter/issues/111475#issuecomment-1249615346 while using [flutter_file_picker](https://github.com/miguelpruivo/flutter_file_picker) and can confirm that I was successfully able to submit a build for both iOS and macOS without any processing errors. Can also confirm that the functionality continues to work throughout the application on both platforms.

**Comment by jmagman** [comment] 2022-09-19 17:58
Thank you so much, @JagandeepBrar!

**Comment by blue492** [comment] 2022-09-20 07:33
After upgrading to Xcode 14, I got these errors messages when I try build/run my project on Mac: 
Android studio -> Build -> Flutter -> Build iOS

shared_preferences: ^2.0.15
Flutter version: 3.3.2

Note that everything were working without any problem before the upgrading

```
Automatically signing iOS for device deployment using specified development team in Xcode project: 65456KJ35R
Running Xcode build...                                          
Xcode build done.                                           18.4s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/cc/3b8b8j7s3nd92qwt4_6zgzhh0000gn/T/flutter_tools.DBua0Q/flutter_ios_build_temp_dirdSTTIY/temporary_xcresult_bundle

    /Users/test/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/ios/Classes/FLTSharedPreferencesPlugin.m:27:41: error: no type or protocol named 'FlutterPluginRegistrar'
    + (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
                                            ^
    /Users/test/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/ios/Classes/FLTSharedPreferencesPlugin.m:29:34: error: property 'messenger' not found on object of type 'NSObject *'
      UserDefaultsApiSetup(registrar.messenger, plugin);
                                     ^
    3 errors generated.
    Command SwiftCompile failed with a nonzero exit code
    note: Building targets in dependency order
    warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
    warning: Run script build phase 'Thin Binary' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')

    Result bundle written to path:
    	/var/folders/cc/3b8b8j7s3nd92qwt4_6zgzhh0000gn/T/flutter_tools.DBua0Q/flutter_ios_build_temp_dirdSTTIY/temporary_xcresult_bundle


Generics Issue (Xcode): No type or protocol named 'FlutterPlugin'
/Users/test/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/ios/Classes/FLTSharedPreferencesPlugin.h:5:50

Generics Issue (Xcode): No type or protocol named 'FlutterPluginRegistrar'
/Users/test/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/ios/Classes/FLTSharedPreferencesPlugin.m:26:40

Semantic Issue (Xcode): Property 'messenger' not found on object of type 'NSObject *'
/Users/test/.pub-cache/hosted/pub.dartlang.org/shared_preferences_ios-2.1.1/ios/Classes/FLTSharedPreferencesPlugin.m:28:33

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

Encountered error while building for device.
Process finished with exit code 1
```

**Comment by AlexV525** [comment] 2022-09-20 08:19
> Note that everything were working without any problem before the upgrading

@blue492 Please submit separate issues to track this, thanks.

**Comment by akashgk** [comment] 2022-09-26 04:54
Im also getting the same issues. currently I am signing these pods with my development team certificates.

What should be the proper resolution?

```
Error (Xcode): Signing for "DKImagePickerController-DKImagePickerController" requires a development team. Select a development team in the Signing & Capabilities editor.
/Users/akashgkrishnan/Documents/pyjamahr/ios/Pods/Pods.xcodeproj


Error (Xcode): Signing for "DKPhotoGallery-DKPhotoGallery" requires a development team. Select a development team in the Signing & Capabilities editor.
/Users/akashgkrishnan/Documents/pyjamahr/ios/Pods/Pods.xcodeproj


Error (Xcode): Signing for "GoogleSignIn-GoogleSignIn" requires a development team. Select a development team in the Signing & Capabilities editor.
/Users/akashgkrishnan/Documents/pyjamahr/ios/Pods/Pods.xcodeproj


Encountered error while archiving for device.
```

**Comment by jmagman** [comment] 2022-09-28 20:10
This fix is now available in Flutter 3.3, and you may remove any build setting workarounds you've added to your Podfile.
Thank you for your patience!

**Comment by blue492** [comment] 2022-09-29 06:41
> build setting workarounds

I could not build my project with Flutter 3.3 Without the  build setting workarounds in podfile. I got a build issue with `connectivity_plus` package. So I keep it for now

**Comment by tobiasht** [comment] 2022-09-30 07:15
He meant 3.3.3 and i can confirm that it works!

**Comment by jmagman** [comment] 2022-09-30 17:37
> meant 3.3.3 and i can confirm that it works!

I did, thanks.

**Comment by verifiedanswer** [comment] 2022-10-19 03:37
[[Solved] Select a development team in the Signing & Capabilities editor](https://verifiedanswer.com/select-a-development-team-in-the-signing-capabilities-editor/)

**Comment by oscarshaitan** [comment] 2022-11-01 14:29
I still got the issue with 3.3.6 but for 
<img width="243" alt="Screen Shot 2022-11-01 at 14 29 49" src="https://user-images.githubusercontent.com/9093952/199257637-e70d2555-b184-4f16-9cf7-383f5c09b560.png">

**Comment by jmagman** [comment] 2022-11-01 18:06
@oscarshaitan please file a new issue and completely fill out the template.
