### ISSUE TITLE
 Incorrect IntrinsicHeight calculation for RichText

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#48679] opened 2020-01-12 18:19 UTC
Internal: b/147481532

This IntrinsicHeight calculation being incorrect seems to be the underlying issue for a number of things that customer:money is seeing.

I've stripped it back to a simplistic example.

With `IntrinsicHeight` absent, this is what I see:

![image](https://user-images.githubusercontent.com/6687929/72223545-d9f49100-3524-11ea-8bc9-1e4b7bcee26f.png)

With `IntrinsicHeight` present, this is what I see:

![image](https://user-images.githubusercontent.com/6687929/72223548-e7aa1680-3524-11ea-856f-ae5cf2b2c73f.png)

**The expectation is that both of these should look the same.**

Full repro code:

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'IntrinsicHeight',
      theme: ThemeData(primarySwatch: Colors.blue),
      darkTheme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        appBar: AppBar(title: Text('IntrinsicHeight Test')),
        body: Align(
          alignment: Alignment.topLeft,
          child: Container(
            color: Colors.green,
            child: IntrinsicHeight(
              child: RichText(
                text: TextSpan(
                  text: 'Root\n',
                  children: [
                    TextSpan(text: 'Start\n'),
                    WidgetSpan(
                      child: Row(
                        children: [
                          Icon(Icons.edit, size: 16),
                        ],
                      ),
                    ),
                    TextSpan(text: 'End'),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by mehmetf** [comment] 2020-01-12 18:20
A number of issues with no workaround is dependent on this; thus marking as critical.

**Comment by jason-simmons** [comment] 2020-01-15 20:22
`RenderParagraph` is computing different values for the embedded `Row`'s width in the intrinsic height layout pass versus the final layout.

The intrinsic height calculation uses `RenderParagraph._computeChildrenHeightWithMinIntrinsics`.  This calls `child.getMinIntrinsicHeight(width)` and then calls `child.getMinIntrinsicWidth` for that height.  The resulting `Row` width is the width of the `Icon`.  The `Row` width is given to the text layout subsystem, which fits the `End` text on the same line as the `Row`.  The paragraph's height is the total height of the resulting three lines (`Root`, `Start`, and `Icon`/`End`).

The final layout calls `RenderParagraph._layoutChildren`, which calls `child.layout` with a `BoxConstraints(maxWidth: constraints.maxWidth)`.  This computes a `Row` width equal to the `constraints.maxWidth`.  The `Row` thus consumes the full third line of the text layout, and the `End` text is shifted to the fourth line.

However, the `IntrinsicHeight` widget causes the paragraph to be truncated to the height computed in the first pass, and the fourth line of text is not visible.

@Hixie @GaryQian How should dimensions for a container like a `Row` be calculated when it is embedded inside a text layout?

As a quick workaround for this example, you could:
  * remove the `Row` container (if you want the `Icon` and the `End` text to be laid out on the same line)
  * add a `TextSpan(text: '\n')` after the `Row` (if you want `End` to be consistently laid out on a separate line)

**Comment by goderbauer** [comment] 2020-01-16 00:37
Assuming the row is actually required for this use case: Another work-around is to set `mainAxisSize: MainAxisSize.min` on the Row. That way, layout will calculate the same width for the Row as the intrinsics calculation did.

**Comment by goderbauer** [comment] 2020-01-16 01:25
For some context, these are this is the code jason is refering to:
https://github.com/flutter/flutter/blob/c195b771ccbe9c9c7c2b467c4b43bf7f67cb3797/packages/flutter/lib/src/rendering/paragraph.dart#L398
https://github.com/flutter/flutter/blob/c195b771ccbe9c9c7c2b467c4b43bf7f67cb3797/packages/flutter/lib/src/rendering/paragraph.dart#L517-L521

**Comment by goderbauer** [comment] 2020-01-23 00:57
Notes from a discussion with Ian:
* We currently don't have API to handle this case, we would need to add a new intrinsics method to handle this case
* New method would basically implement a non-destructive dry layout (actually, there would be two new methods (get/compute) similar to the existing intrinsics.
* It would take in Constraints and return the Size that the RenderBox would layout at given the constraints.
* performResize could be re-implemented in terms of computeDryLayout
* in layout we can assert if computeDryLayout calculates the same size as layout.
* When getDryLayout is called we should set a flag to mark our parent as dirty when markNeedsLayout is called on us
* Consider implementing a cache similar to the other intrinsics
* default implementation on RenderBox should throw (for backwards compatibility) 

This is a pretty big change, though. It is necessary to solve this in a generic way. However, specific use cases can also be solved with a custom RenderObject that just lays out the children, measures them, and sets its own size accordingly.

**Comment by goderbauer** [comment] 2020-01-27 21:02
Thinking about this more, this may actually not fix the full class of problems that intrinsics has, example: https://gist.github.com/goderbauer/fea3a2e524f17491e303167a9ff4a400

**Comment by goderbauer** [comment] 2020-01-27 21:37
Never mind, it would actually work if we don't call any of the existing intrinsics functions on a child of RenderParagraph and instead only use dryLayout to compute the size of the children.

**Comment by parkskier426** [comment] 2020-01-29 22:42
I'm experiencing the issue as well. As in this [example](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html), when using a single child scroll view with a constrained box and an InternsicHeight as it's child, I'm experiencing overflows due to a miscalculation of RichText element's heights.

**Comment by Hixie** [comment] 2020-02-12 00:18
We believe this is no longer blocking a customer, but leaving open since we will eventually have to address this.

**Comment by tomgilder** [comment] 2020-05-01 12:05
Is this the same root cause as #27293? That has a much simpler reproduction:

```
IntrinsicHeight(
  child: SizedBox(
    width: 100,
    child: Column(
      children: [Text('I only get a height of my first line')],
    ),
  ),
)
```

**Comment by markusaksli-nc** [comment] 2020-07-28 11:28
Reproducible on the latest master `1.21.0-6.0.pre.41`.
<details>
 <summary>flutter doctor -v</summary>

 ```
[√] Flutter (Channel master, 1.21.0-6.0.pre.41, on Microsoft Windows [Version 10.0.18362.959], locale et-EE)
    • Flutter version 1.21.0-6.0.pre.41 at C:\Development\flutter_master
    • Framework revision 39fa00201d (5 hours ago), 2020-07-27 21:11:43 -0700
    • Engine revision f27729e97b
    • Dart version 2.10.0 (build 2.10.0-0.0.dev 24c7666def)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Isa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30309.148
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Isa\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\Isa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (5 available)
    • SM G950F (mobile)       • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows            • windows-x64    • Microsoft Windows [Version 10.0.18362.959]
    • Web Server (web)        • web-server         • web-javascript • Flutter Tools
    • Chrome (web)            • chrome             • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```
</details>

Very likely related issue #59719

**Comment by markusaksli-nc** [comment] 2020-07-28 11:34
I would consider closing both #27293 and #59719 as they are probably duplicates of this. Leaving them open for confirmation, as they are still slightly different cases.

**Comment by goderbauer** [comment] 2020-07-28 18:03
Indeed, https://github.com/flutter/flutter/issues/27293 has some other good examples for the issue.

**Comment by goderbauer** [comment] 2020-08-03 20:26
Regarding (last bullet in https://github.com/flutter/flutter/issues/48679#issuecomment-577456960):

> Check Wrap if it suffers under similar problems and wether they can be solved with this API

It looks like wrap suffers under the same problem, see https://github.com/flutter/flutter/issues/61204. We still need to investigate whether the newly proposed API will fix it there as well.

**Comment by Hixie** [comment] 2020-08-18 22:38
Does the fix in https://github.com/flutter/flutter/issues/63302 use the new API proposal? Does it affect this bug?

**Comment by chunhtai** [comment] 2020-08-19 21:35
@Hixie No, It was a bug fixes in Wrap. I manage to fix it without the new api

**Comment by chunhtai** [comment] 2020-08-20 20:26
@goderbauer It looks like we can apply the same philosophy to fix the render paragraph here as well? Try to let children rendering with infinite constraint, and I chop off the size if the size the children return does not meet my constraint.

**Comment by Hixie** [comment] 2020-08-20 20:47
The Paragraph has to be laid out with the correct width so it knows where to ellipsize.

**Comment by tvolkert** [comment] 2020-09-15 22:35
Also related in that fixing it would require extra method(s) on RenderBox: https://github.com/flutter/flutter/issues/65895

**Closed** 2020-11-21 01:24 UTC
Labels: P2, a: typography, customer: money (g3), found in release: 1.21, framework, has reproducible steps
