### ISSUE TITLE
Slider with round thumb will create a wired square background on white scaffold background

### ISSUE THREAD

**Issue by linsendidi** [flutter/flutter#138853] opened 2023-11-21 23:50 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the demo on real ios device (iPhone 15 Pro, 17.1.1)
2. See the thumb with wired square background

### Expected results

The round thumb should just be the circle

### Actual results

The round thumb will draw the circle with an unexpected background

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double currentSliderValue = 10000;
  final double max = 80000;

  final double min = 10000;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            SliderTheme(
              data: SliderTheme.of(context).copyWith(
                thumbShape: const RoundSliderThumbShape(
                  enabledThumbRadius: 15,
                  elevation: 0,
                  pressedElevation: 0,
                ),
                trackHeight: 6,
                overlayShape: SliderComponentShape.noOverlay,
                // trackShape: FullWidthRoundedTrackShape(),
                activeTickMarkColor: Colors.blue,
                inactiveTickMarkColor: Colors.lightBlue,
                activeTrackColor: Colors.blue,
                inactiveTrackColor: Colors.lightBlue,
                thumbColor: Colors.blue,
              ),
              child: Slider(
                value: currentSliderValue,
                min: min,
                max: max,
                divisions: getDivisions(),
                onChanged: (double value) {
                  setState(() {
                    currentSliderValue = value;
                  });
                },
              ),
            ),
          ],
        ),
      ),
    );
  }

  int getDivisions() {
    return ((max - min) / 1000).ceil();
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![MicrosoftTeams-image (10)](https://github.com/flutter/flutter/assets/25985620/30e365cf-3053-4ee8-af9f-1c5f0bbf7aab)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1 23B74 darwin-arm64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.84.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2023-11-22 10:21
Closing this as a duplicate of https://github.com/flutter/flutter/issues/138842

**Closed by danagbemava-nc** 2023-11-22 10:21 UTC
Labels: in triage
