### ISSUE TITLE
[url_launcher_web] 'UrlLauncherPlatform.linkDelegate' is missing

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#68628] opened 2020-10-20 16:44 UTC
## Steps to Reproduce

1. Depend on `url_launcher: ^5.7.5`.
2. Run `flutter pub upgrade`.
3. Run `flutter run` or `flutter build`.

## Logs

```
Pub/Cache/hosted/pub.dartlang.org/url_launcher_web-0.1.4+1/lib/url_launcher_web.dart:22:7: Error: The non-abstract class 'UrlLauncherPlugin' is missing implementations for these members:
 - UrlLauncherPlatform.linkDelegate
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class UrlLauncherPlugin extends UrlLauncherPlatform {
      ^^^^^^^^^^^^^^^^^
Pub/Cache/hosted/pub.dartlang.org/url_launcher_platform_interface-1.0.9/lib/url_launcher_platform_interface.dart:43:20: Context: 'UrlLauncherPlatform.linkDelegate' is defined here.
  LinkDelegate get linkDelegate;
                   ^^^^^^^^^^^^
Failed to compile application.
```

## Reason

This is because the `url_launcher_platform_interface` dependency in `url_launcher` is loose and the `Laid the groundwork for introducing a Link widget.` (see [changelog](https://pub.dev/packages/url_launcher_platform_interface/changelog#109)) screwed that yp.

**Comment by jeansebastienZ** [comment] 2020-10-20 17:02
Any solution avalaible ?

**Comment by creativecreatorormaybenot** [comment] 2020-10-20 17:06
@jeansebastienZ Yes, you can do the following:

```
dependency_overrides:
  url_launcher_platform_interface: 1.0.8
```

**Comment by creativecreatorormaybenot** [comment] 2020-10-20 17:07
cc @mdebbar

**Comment by mdebbar** [comment] 2020-10-20 17:09
Thanks for suggesting the workaround @creativecreatorormaybenot! That is the correct workaround until the issue is fixed.

This issue is a duplicate of https://github.com/flutter/flutter/issues/68545

**Closed by mdebbar** 2020-10-20 17:09 UTC
