### ISSUE TITLE
[Impeller]: UI jitter occurs when running the app on the iOS simulator, after upgrading to flutter 3.22.1.

### ISSUE THREAD

**Issue by kjxbyz** [flutter/flutter#149036] opened 2024-05-24 09:49 UTC
### Steps to reproduce

This is a placeholder, a minimal reproducible example will be uploaded soon.

### Expected results

When the impeller is enabled, running the app on the iOS simulator works fine.

### Actual results

UI jitter occurs when running the app on the iOS simulator, after upgrading to flutter 3.22.1.

It works fine when the impeller is disabled.

This problem only occurs in debug mode and works normally in release mode.

### Code sample

<details open><summary>Code sample</summary>

```dart
// This is a placeholder, a minimal reproducible example will be uploaded soon.
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/47768002/153fe36c-6967-4bdd-98ad-183aa5eb6efd

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.22.1 on channel stable at /Users/ying/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (2 天前), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ying/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/ying/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 79.2.3
    • Dart plugin version 241.17502

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • Kimmy's iPhone (mobile)    • 00008020-000A1D110A32002E            • ios            • iOS 17.5.1 21F90
    • iPhone 15 Pro Max (mobile) • 6657C5CB-CF27-4DEE-84C6-E4D25870363F • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 14.5 23F79 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 125.0.6422.113
    ! Error: Browsing on the local area network for Kimmy's Apple Watch. Ensure the device is unlocked and discoverable
      via Bluetooth. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2024-05-24 12:06
> This is a placeholder, a minimal reproducible example will be uploaded soon.

@kjxbyz I'll save your time. This is a duplicate of already reported issue in which you can follow-up for further updates.
Closing as such.

**Closed by darshankawar** 2024-05-24 12:06 UTC
Labels: in triage
