### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by ravimandal06** [flutter/flutter#147636] opened 2024-05-01 10:41 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1928:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2493:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2464:14)
#3      VmService.callMethod (package:vm_service/src/vm_service.dart:2446:12)
#4      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:579:28)
#5      FlutterVmService.renderFrameWithRasterStats (package:flutter_tools/src/vmservice.dart:679:49)
#6      ResidentHandlers.debugFrameJankMetrics (package:flutter_tools/src/resident_runner.dart:728:35)
<asynchronous suspension>
#7      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1831:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.13.2, on Microsoft Windows
    [Version 10.0.22631.3527], locale en-IN)
    [32m•[39m Flutter version 3.13.2 on channel stable at
      C:\src\flutter\flutter
    [32m•[39m Upstream repository
      https://github.com/flutter/flutter.git
    [32m•[39m Framework revision ff5b5b5fa6 (8 months ago),
      2023-08-24 08:12:28 -0500
    [32m•[39m Engine revision b20183e040
    [32m•[39m Dart version 3.1.0
    [32m•[39m DevTools version 2.25.0

[32m[✓][39m Windows Version (Installed version of Windows is version
    10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android
    SDK version 33.0.0-rc2)
    [32m•[39m Android SDK at
      C:\Users\91707\AppData\Local\Android\Sdk
    [32m•[39m Platform android-34, build-tools 33.0.0-rc2
    [32m•[39m ANDROID_HOME =
      C:\Users\91707\AppData\Local\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android
      Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program
      Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Visual Studio - develop Windows apps (Visual Studio
    Build Tools 2019 16.9.4)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft
      Visual Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.9.31205.134
    [32m•[39m Windows 10 SDK version 10.0.19041.0

[32m[✓][39m Android Studio (version 2021.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android
      Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build
      11.0.12+7-b1504.28-7817840)

[32m[✓][39m VS Code (version 1.88.1)
    [32m•[39m VS Code at
      C:\Users\91707\AppData\Local\Programs\Microsoft VS
      Code
    [32m•[39m Flutter extension version 3.86.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m sdk gphone64 x86 64 (mobile) • emulator-5554 •
      android-x64    • Android 12 (API 32) (emulator)
    [32m•[39m Windows (desktop)            • windows       •
      windows-x64    • Microsoft Windows [Version
      10.0.22631.3527]
    [32m•[39m Chrome (web)                 • chrome        •
      web-javascript • Google Chrome 124.0.6367.63
    [32m•[39m Edge (web)                   • edge          •
      web-javascript • Microsoft Edge 124.0.2478.67

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.0.4+28
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: b55bbb7bffc79adf9cce33ebda0582df41aae280
### Plugins
android_intent_plus-2.1.0
app_links-3.5.0
camera-0.10.5+9
camera_android-0.10.8+16
camera_avfoundation-0.9.13+10
camera_web-0.3.2+4
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_analytics-10.8.0
firebase_analytics_web-0.5.5+12
firebase_core-2.24.2
firebase_core_web-2.10.0
firebase_crashlytics-3.4.9
firebase_messaging-14.7.10
firebase_messaging_web-3.5.18
firebase_performance-0.9.3+8
firebase_performance_web-0.1.4+16
flutter_local_notifications-13.0.0
flutter_phone_direct_caller-2.1.1
flutter_plugin_android_lifecycle-2.0.17
fluttertoast-8.2.4
geocoding-2.1.1
geocoding_android-2.1.2
geocoding_ios-2.1.1
geolocator-8.2.1
geolocator_android-3.2.1
geolocator_apple-2.3.5
geolocator_web-2.2.1
geolocator_windows-0.1.3
google_maps_flutter-2.5.3
google_maps_flutter_android-2.7.0
google_maps_flutter_ios-2.3.6
google_maps_flutter_web-0.5.4+3
gtk-2.1.0
image_picker-0.8.9
image_picker_android-0.8.9+3
image_picker_for_web-2.2.0
image_picker_ios-0.8.9+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
libphonenumber_plugin-0.3.3
libphonenumber_web-0.3.2
package_info_plus-3.1.2
path_provider-2.1.2
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
share_plus-6.3.4
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.5
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
smart_auth-1.1.1
sms_autofill-2.3.1
sqflite-2.3.2
url_launcher-6.2.4
url_launcher_android-6.2.2
url_launcher_ios-6.2.4
url_launcher_linux-3.1.1
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.1
webview_flutter-2.8.0
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by danagbemava-nc** [comment] 2024-05-02 07:42
Closing this as a duplicate of https://github.com/flutter/flutter/issues/117988

**Closed by danagbemava-nc** 2024-05-02 07:42 UTC
Labels: in triage
