### ISSUE TITLE
[Flutter Web] Save Image Created with Custom Paint

### ISSUE THREAD

**Issue by lelitob** [flutter/flutter#57942] opened 2020-05-25 12:22 UTC
Hello, 
I'm porting an app from mobile to web, it simply draw based on user input. 
To draw the app use Custom Paint and to take the image from the canvas and save it, i use repaintBoundary.

Since dart:ui isn't supported yet in Flutter Web it does not work, i asked and searched on SO /reddit and various discord and facebook groups, but with no luck. I would like to know if there is   a way to make it work on Flutter Web

**Comment by TahaTesser** [comment] 2020-05-25 13:44
duplicate of https://github.com/flutter/flutter/issues/47721

**Closed by TahaTesser** 2020-05-25 13:44 UTC
