### ISSUE TITLE
flutter TextFormField crashes and doesn't take keyboard input

### ISSUE THREAD

**Issue by jesussmile** [flutter/flutter#122998] opened 2023-03-20 10:06 UTC
have this strange issue when i click on the TextFormField the keyboard will either freeze or the app will crash. On IOS the keyboard will freeze where as on android, i cant type anything on the textformfield, How can i fix it ?, sometimes it get focus but there is no text input even when i type

If i run the same code from xcode, the textformfield works fine.
```ruby
 @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Column(
      children: [
        Container(
          decoration:
              const BoxDecoration(color: Color.fromARGB(255, 231, 133, 36)),
          height: 8.h,
          width: 135.w,
          child: Padding(
            padding: const EdgeInsets.fromLTRB(8, 40, 0, 0),
            child: Row(
              children: [
                ElevatedButton(
                    style: ButtonStyle(
                        backgroundColor: MaterialStateProperty.all(
                            const Color.fromARGB(255, 62, 84, 122))),
                    onPressed: () {
                      setState(() {
                        _isExpanded = !_isExpanded;
                      });
                    },
                    child: const Text(
                      'Flight Plan',
                      style: TextStyle(color: Colors.white),
                    )),
              ],
            ),
          ),
        ),
        Expanded(
          child: Stack(
            children: [
              Positioned(
                  top: 0,
                  left: 0,
                  // bottom: 0,
                  child: SizedBox(
                    height: 67.h,
                    width: 135.w,
                    //child: flutterMap(context),
                  )),
              Positioned(
                top: -30,
                left: 135,
                child: AnimatedContainer(
                  color: const Color.fromARGB(255, 62, 84, 122),
                  duration: const Duration(milliseconds: 800),
                  curve: Curves.bounceInOut,
                  height: 20.h,
                  width: 100.w,
                  margin: const EdgeInsets.only(top: 30),
                  child: Column(
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.end,
                        children: const [
                          IconButton(
                              icon: Icon(Icons.skip_previous), onPressed: null),
                        ],
                      ),
                      Center(
                        child: Padding(
                          padding: const EdgeInsets.all(8.0),
                          child: TextFormField(
                            autofocus: true,
                            onChanged: (value) => setState(() {}),
                            controller: textFieldController,
                            maxLines: 2,
                            style:
                                const TextStyle(decorationColor: Colors.black),
                            decoration: const InputDecoration(
                                filled: true,
                                fillColor: Colors.white,
                                border: OutlineInputBorder(
                                    borderRadius: BorderRadius.all(
                                        Radius.circular(4.0)))),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    ));
  }
```
this is the flutter doctor result
```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.2, on macOS 12.6.3 21G419 darwin-x64, locale en-US)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.17.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/pannam/Documents/flutter. Consider adding
      /Users/pannam/Documents/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.76.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```
Here is the bare minimum github repository [github][1]

  [1]: https://github.com/jesussmile/text_formfield_issue

**Comment by LinXunFeng** [comment] 2023-03-20 10:37
Hi, you should move the code `TextEditingController textFieldController = TextEditingController();` outside the method. Such as:

```diff
class _MyHomePageState extends State<MyHomePage> {
  bool _isExpanded = false;
+  TextEditingController textFieldController = TextEditingController();
  ...
}
```

```diff
Positioned FlightPlanContainer() {
-    TextEditingController textFieldController = TextEditingController();
    return Positioned(
      top: -30,
      ...
}
```

**Comment by huycozy** [comment] 2023-03-20 10:46
@jesussmile You can try @LinXunFeng's solution above (I see it works from my end as well). 

<details>
<summary>Demo</summary>

![Screenshot 2023-03-20 at 17 45 34](https://user-images.githubusercontent.com/104349824/226317434-67234207-b135-4876-bcd4-966f053f3524.png)

</details>


Since this issue is caused by your implementation code, I will close this issue as soved. If you disagree, please write in the comments and I will reopen it. Thank @LinXunFeng for the solution.

**Closed by huycozy** 2023-03-20 10:46 UTC
Labels: in triage
