### ISSUE TITLE
[Flutter 2.0] Destroying FlutterEngine created by FlutterEngineGroup will cause the App to freeze 

### ISSUE THREAD

**Issue by yrom** [flutter/flutter#77690] opened 2021-03-09 09:22 UTC
I am trying to follow the sample code to introduce the new FlutterEngineGroup API to my App, see https://github.com/flutter/samples/tree/master/add_to_app/multiple_flutters.
And I noticed that, in the sample, the FlutterEngine instance created by FlutterEngineGroup has no chance to be destoryed. The doc does not discuss how to deal with this case. Then I add codes below:
```diff
--- a/add_to_app/multiple_flutters/multiple_flutters_android/app/src/main/java/dev/flutter/multipleflutters/DoubleFlutterActivity.kt
+++ b/add_to_app/multiple_flutters/multiple_flutters_android/app/src/main/java/dev/flutter/multipleflutters/DoubleFlutterActivity.kt
@@ -49,7 +49,9 @@ class DoubleFlutterActivity : FragmentActivity(), EngineBindingsDelegate {
             val engine = if (i == 0) topBindings.engine else bottomBindings.engine
             FlutterEngineCache.getInstance().put(i.toString(), engine)
             val flutterFragment =
-                FlutterFragment.withCachedEngine(i.toString()).build<FlutterFragment>()
+                FlutterFragment.withCachedEngine(i.toString())
+                    .destroyEngineWithFragment(true)
+                    .build<FlutterFragment>()
             fragmentManager
                 .beginTransaction()
                 .add(
--- a/add_to_app/multiple_flutters/multiple_flutters_android/app/src/main/java/dev/flutter/multipleflutters/SingleFlutterActivity.kt
+++ b/add_to_app/multiple_flutters/multiple_flutters_android/app/src/main/java/dev/flutter/multipleflutters/SingleFlutterActivity.kt
@@ -30,6 +30,9 @@ class SingleFlutterActivity : FlutterActivity(), EngineBindingsDelegate {
         return engineBindings.engine
     }
 
+    override fun shouldDestroyEngineWithHost(): Boolean {
+        return true
+    }
     override fun onNext() {
         val flutterIntent = Intent(this, MainActivity::class.java)
         startActivity(flutterIntent)
```

However, when the FlutterEngine is destroyed, the App freezes (see attachment).

Flutter: 2.0.1, revision c5a4b4029c
Device: Android Emulator API 29

[device-2021-03-09-171225.webm.zip](https://github.com/flutter/flutter/files/6107373/device-2021-03-09-171225.webm.zip)

**Comment by TahaTesser** [comment] 2021-03-09 12:02
Hi @yrom 
When trying to follow the video, it's not clear where the click is happening, I tried to go back, there is no crash
Can you please step by step reproduce the issue?

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.4
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.2.2 20D80 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```

</details>


Thank you

**Comment by yrom** [comment] 2021-03-10 02:36
Hi @TahaTesser 
MainActivity  ---Next-->   SingleFlutterActivity  ---Next-->  MainActivity  ---Next-->   DoubleFlutterActivity
SingleFlutterActivity (app freezes) <---Back--- MainActivity <---Back----DoubleFlutterActivity  (Flutter engine destroyed)

**Comment by yrom** [comment] 2021-03-10 02:44
BTW, I'm not sure if it is fixed by https://github.com/flutter/engine/pull/24644, it seems to be a same issue https://github.com/flutter/flutter/issues/76597

**Comment by TahaTesser** [comment] 2021-03-10 09:25
Hi @yrom 
I just tried two different devices (Samsung & Realme) both running API 29
Following the steps from https://github.com/flutter/flutter/issues/77690#issuecomment-794765989 has no freeze or crash

### Preview



https://user-images.githubusercontent.com/48603081/110606803-90e3af80-81b0-11eb-9619-c1db3e342a91.mp4





<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.4.1
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.2.3 20D91 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 89.0.4389.82
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.180, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.180 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision be8989f185 (2 hours ago), 2021-03-09 23:31:02 -0800
    • Engine revision 7764b5c55f
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (4 available)
    • SM M025F (mobile)    • R9ZR205XX0A               • android-arm    •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.4.1
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.2.3 20D91 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 89.0.4389.82
    ! Error: Taha’s iPad is busy: Copying cache files from device. Xcode will
      continue when Taha’s iPad is finished. (code -10)

• No issues found!
```

</details>

**Comment by yrom** [comment] 2021-03-10 10:25
Hi @TahaTesser, 
Did you add `destroyEngineWithFragment(true)`?

https://github.com/flutter/samples/blob/master/add_to_app/multiple_flutters/multiple_flutters_android/app/src/main/java/dev/flutter/multipleflutters/DoubleFlutterActivity.kt#L60-L61

```kt 
val flutterFragment =
        FlutterFragment.withCachedEngine(engineId.toString()).destroyEngineWithFragment(true).build<FlutterFragment>()
```

https://user-images.githubusercontent.com/2888674/110614826-b337f600-81cd-11eb-9070-198a82c14b2e.mp4

<details>
<summary>flutter doctor -v</summary>
<pre>
  
    [✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H512 darwin-x64, locale zh-Hans-CN)
        • Flutter version 2.0.1 at /Users/wangyongrong/Library/flutter-2.0
        • Framework revision c5a4b4029c (6 days ago), 2021-03-04 09:47:48 -0800
        • Engine revision 40441def69
        • Dart version 2.12.0
        • Pub download mirror https://pub.flutter-io.cn
        • Flutter download mirror https://storage.flutter-io.cn
    
    [!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
        • Android SDK at /Users/wangyongrong/Documents/Android-SDK
        • Platform android-30, build-tools 30.0.2
        • ANDROID_HOME = /Users/wangyongrong/Documents/Android-SDK
        • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
        ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
    
    [✓] Xcode - develop for iOS and macOS
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Xcode 12.2, Build version 12B45b
        • CocoaPods version 1.10.0
    
    [✓] Chrome - develop for the web
        • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
    [✓] Android Studio (version 3.6)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    
    [✓] VS Code (version 1.54.1)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.20.0
    
    [✓] Connected device (3 available)
        • VOG AL10 (mobile) • APH7N19329001298 • android-arm64  • Android 10 (API 29)
        • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.7 19H512 darwin-x64
        • Chrome (web)      • chrome           • web-javascript • Google Chrome 88.0.4324.192

</pre>
</details>

**Comment by TahaTesser** [comment] 2021-03-11 09:55
Hi @yrom 
Adding this line to `DoubleFlutterActivity`, makes the app freeze  to 
```kt
            val engine = if (i == 0) topBindings.engine else bottomBindings.engine
            FlutterEngineCache.getInstance().put(engineId.toString(), engine)
//            val flutterFragment =
//                FlutterFragment.withCachedEngine(engineId.toString()).build<FlutterFragment>()
            val flutterFragment =
                FlutterFragment.withCachedEngine(engineId.toString()).destroyEngineWithFragment(true).build<FlutterFragment>()
```


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale
    en-GB)
    • Flutter version 2.0.1 at /Users/tahatesser/Code/flutter_stable
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM M025F (mobile) • R9ZR205XX0A • android-arm    • Android 10 (API 29)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 11.2.3 20D91
      darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      89.0.4389.82

• No issues found!
```

```bash
[✓] Flutter (Channel master, 2.1.0-11.0.pre.205, on macOS 11.2.3 20D91
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-11.0.pre.205 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 267f66a7dc (6 hours ago), 2021-03-10 23:15:03 -0500
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • SM M025F (mobile) • R9ZR205XX0A • android-arm    • Android 10 (API 29)
    • macOS (desktop)   • macos       • darwin-x64     • macOS 11.2.3 20D91
      darwin-x64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      89.0.4389.82

• No issues found!
```

</details>

Thanks for filing the issue

**Comment by chinmaygarde** [comment] 2021-03-15 18:19
cc @xster @gaaclarke

**Comment by xster** [comment] 2021-03-15 18:21
It should be a dupe of https://github.com/flutter/flutter/issues/76597. To be hotfixed in the next patch. Please reopen if I got it wrong.

**Closed by xster** 2021-03-15 18:21 UTC
Labels: P2, a: existing-apps, engine, found in release: 2.0, found in release: 2.1, has reproducible steps, platform-android, severe: crash, severe: fatal crash

**Comment by yrom** [comment] 2021-03-18 06:52
Hi all,
I've tested with Flutter 2.0.2 and this issue has been resolved.
