### ISSUE TITLE
Container Inner shadow

### ISSUE THREAD

**Issue by Chandresh97Jain** [flutter/flutter#154336] opened 2024-08-29 13:20 UTC
### Use case

I'm trying to create a container with an inward shadow effect, but since Flutter doesn't currently support this directly, I'm using custom painters to achieve the effect.

### Proposal

I think it is a valid issue and should be added in the near future updates.

**Comment by danagbemava-nc** [comment] 2024-08-29 13:47
Closing this as a duplicate of https://github.com/flutter/flutter/issues/18636

**Closed by danagbemava-nc** 2024-08-29 13:47 UTC
Labels: in triage
