### ISSUE TITLE
Flutter display blank web page with webview_flutter on Android

### ISSUE THREAD

**Issue by riccardopirani** [flutter/flutter#106088] opened 2022-06-16 06:45 UTC
I have a problem with the visualization of a web page with webview_flutter, I have to display a web view, when I run the code on ios the view is displayed correctly, when I run the same code on android I have a blank page, how do I solve this thing? To what it is due, I report below the source codes

## Steps to Reproduce

1. flutter pub get
2. flutte run
3.

**Expected results:** Display web page

**Actual results:** Display Blank page only on Android on ios it works

<details>
<summary>Pubspec.yaml</summary>

```yaml
name: myapp
description: sss

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  shared_preferences: ^2.0.0
  rflutter_alert: ^2.0.4
  flutter_rating_bar: ^4.0.0
  intl: ^0.17.0
  animations: ^2.0.0
  webview_flutter: ^3.0.4
  dio: ^4.0.6
  dartdoc: ^5.0.1
  nfc_manager: ^3.1.1
  permission_handler: ^9.2.0
  flutter_nfc_reader:
    git:
      url: git://github.com/matteocrippa/flutter-nfc-reader.git
      ref: master
  flutter_nfc_kit: ^3.3.1
  ndef: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
```
</details>

<details>
<summary>Flutter Code</summary>

```dart
import 'dart:io';

import 'package:appsafetyeurope/model/Manutenzione.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

String URLLOAD = "https://marconisoftware.com";

class ReportView extends StatefulWidget {
  final Manutenzione man;
  final String token;
  final String url;

  const ReportView(this.man, this.token, this.url);

  @override
  createState() => ReportViewState();
}

class ReportViewState extends State<ReportView> {
  void _handleLoad(String value) {}

  @override
  void initState() {
    super.initState();
    // Enable virtual display.
    if (Platform.isAndroid) {
      //WebView.platform = SurfaceAndroidWebView();
      WebView.platform = AndroidWebView();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            leading: IconButton(
              icon: Icon(Icons.arrow_back_ios),
              iconSize: 20.0,
              onPressed: () {
                Navigator.pop(context);
              },
            ),
            centerTitle: true,
            title: Text('Report')),
        body: IndexedStack(
          index: 0,
          children: [
            Column(
              children: <Widget>[
                Expanded(
                    child: WebView(
                  javascriptMode: JavascriptMode.unrestricted,
                  onWebViewCreated: (WebViewController webViewController) {
                    Map<String, String> headers = {"Cmdbuild-authorization": widget.token};
                    webViewController.loadUrl(
                        "https://platform.safetyeurope.eu/openmaint-test/services/rest/v3/reports/286763/Activity%20report.pdf?extension=pdf&parameters=%7B%22ProcessId%22%3A22222
                            "%7D",
                        headers: headers);
                  },
                  onPageFinished: _handleLoad,
                )),
              ],
            ),
            Container(
              color: Colors.white,
              child: Center(
                child: CircularProgressIndicator(),
              ),
            ),
          ],
        ));
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1
    21E258 darwin-arm, locale en-IT)
    • Flutter version 2.10.4 at
      /Users/riccardo/development/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 months ago),
      2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices
    (Android SDK version 31.0.0)
    • Android SDK at /Users/riccardo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • iPhone with Apple Watch (mobile) •
      66B7106A-CDE3-4FDF-988D-ACDC23A79EC9 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-5
      (unsupported) (simulator)
    • Chrome (web)                     • chrome
      • web-javascript • Google Chrome 102.0.5005.115
    ! Error: iPhone di Riccardo is not connected. Xcode
      will continue when iPhone di Riccardo is connected.
      (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by huycozy** [comment] 2022-06-16 10:18
@riccardopirani

From what I can see, there is existed a 3rd party plugin (`appsafetyeurope`) inside your sample code. Try to provide us a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy-paste and run to verify this issue.

By the way, I tried running [webview_flutter](https://github.com/flutter/plugins/tree/main/packages/webview_flutter/webview_flutter) example and see it worked normally as in the demo.

<details>
<summary>Demo</summary>

![Screen Shot 2022-06-16 at 17 12 09](https://user-images.githubusercontent.com/104349824/174049190-8ef6f860-5521-4497-a1fb-f7e2d270e891.png)

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.2 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (4 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1265, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1265 at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6671503789 (2 hours ago), 2022-06-15 18:36:08 -0700
    • Engine revision f8c0dc87bc
    • Dart version 2.18.0 (build 2.18.0-189.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/203.7185775/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.68.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 964AY0WL20 • android-arm64  • Android 12 (API 32)
    • macOS (desktop)   • macos      • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 102.0.5005.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

And I see that your flutter SDK is outdated, the latest stable is `3.0.2` and master is `3.1.0-0.0.pre.1265`. So, please upgrade SDK to the latest then try again.

**Comment by riccardopirani** [comment] 2022-06-16 11:13
@

> @riccardopirani
> 
> From what I can see, there is existed a 3rd party plugin (`appsafetyeurope`) inside your sample code. Try to provide us a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy-paste and run to verify this issue.
> 
> By the way, I tried running [webview_flutter](https://github.com/flutter/plugins/tree/main/packages/webview_flutter/webview_flutter) example and see it worked normally as in the demo.
> Demo
> flutter doctor -v
> 
> And I see that your flutter SDK is outdated, the latest stable is `3.0.2` and master is `3.1.0-0.0.pre.1265`. So, please upgrade SDK to the latest then try again.

In my case it performs a blank page only on android while on ios it works correctly, I try to update the flutter version but it doesn't work

**Comment by huycozy** [comment] 2022-06-16 11:20
@riccardopirani 
We can not conclude the issue if the sample code is not completed and minimal.

```dart
webViewController.loadUrl(
    widget.url +
        "/services/rest/v3/reports/286763/Activity%20report.pdf?extension=pdf&parameters=%7B%22ProcessId%22%3A" +
        widget.man.id.toString() +
        "%7D"
```

Try to provide us a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly copy-paste and run to verify this issue.

**Comment by srihariash999** [comment] 2022-06-16 12:14
@riccardopirani  your code sample has a widget that requires these parameters to be passed in 

```
  final Manutenzione man;
  final String token;
  final String url;

```
which are unknown to anyone.  Also the url you are trying to load into webview 

"https://platform.safetyeurope.eu/openmaint-test/services/rest/v3/reports/286763/Activity%20report.pdf?extension=pdf&parameters=%7B%22ProcessId%22%3A22222%7D"  

it is returning some json response (which i think is because I did not provide a valid token in the headers) if I just try to load this particular url anyway, the webview seems to be functioning correctly. 


<img width="304" alt="image" src="https://user-images.githubusercontent.com/30948010/174066959-cec07903-0c61-4f41-ae42-c31fe0360ba9.png">


Modify your sample code to contain a valid token !

**Comment by huycozy** [comment] 2022-06-17 02:40
@riccardopirani 

>my token is valid, it works on IOS and not on Android

What is your token? Can you run your [sample code](https://github.com/flutter/flutter/issues/106088#issue-1273126979) without providing it or `ReportView`'s  wrapper widget?
Without additional information, we are unfortunately not sure how to resolve this issue.

**Comment by riccardopirani** [comment] 2022-06-17 06:23
The token is not default it changes every time you log in, is a system variable obtained at login

**Comment by riccardopirani** [comment] 2022-06-17 12:30
> @riccardopirani
> 
> > my token is valid, it works on IOS and not on Android
> 
> What is your token? Can you run your [sample code](https://github.com/flutter/flutter/issues/106088#issue-1273126979) without providing it or `ReportView`'s wrapper widget? Without additional information, we are unfortunately not sure how to resolve this issue.

The token is not default it changes every time you log in, is a system variable obtained at login

**Comment by huycozy** [comment] 2022-06-17 13:03
@riccardopirani 
We can not verify the issue if your sample code is not **`completed and minimal`**. In this case, your widget `ReportView` is dependent on another widget's data that provides `token`.

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
Without additional information, we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the issue if you have any more information for us. Thanks!

**Closed by huycozy** 2022-06-17 13:03 UTC
Labels: in triage
