### ISSUE TITLE
<WEB> Uninplemented error on layer.dart

### ISSUE THREAD

**Issue by joselicht90** [flutter/flutter#47964] opened 2019-12-30 01:14 UTC
Hi! I'm trying to run on chrome some code i already run on android. im getting this error on layer.dart, exactly this method

 @override
  void addToScene(ui.SceneBuilder builder, [ Offset layerOffset = Offset.zero ]) {
    assert(shader != null);
    assert(maskRect != null);
    assert(blendMode != null);
    final Rect shiftedMaskRect = layerOffset == Offset.zero ? maskRect : maskRect.shift(layerOffset);
    engineLayer = builder.pushShaderMask(shader, shiftedMaskRect, blendMode, oldLayer: _engineLayer);
    addChildrenToScene(builder, layerOffset);
    builder.pop();
  }

I know this happen when i got a shadermask on the page. My code look like this:

ShaderMask(
            shaderCallback: (rect) {
              return LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [Colors.white, Colors.transparent],
              ).createShader(Rect.fromLTRB(0, 0, rect.width, rect.height));
            },
            blendMode: BlendMode.dstIn,
            child: Image(
              image: AssetImage('assets/images/home_image.jpg'),
              fit: BoxFit.cover,
            ),
          ),

**Comment by jonahwilliams** [comment] 2019-12-30 06:50
Duplicate of https://github.com/flutter/flutter/issues/44152

**Closed by jonahwilliams** 2019-12-30 06:50 UTC
