### ISSUE TITLE
Flutter calls Dart_NotifyIdle(deadline) mostly when it's not idle and often with interesting deadlines

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#48241] opened 2020-01-06 16:07 UTC
Mirror issue for https://b.corp.google.com/issues/146925122. 

/cc @chinmaygarde

**Comment by chinmaygarde** [comment] 2020-01-14 01:07
Just got back from vacation today. My initial impression based on reported behavior is that collection is working as intended. Let me explain:
* `Dart_NotifyIdle` is advisory and not making the same or making it with insufficient deadlines does not mean that the VM will keep consuming memory indefinitely. Even if the engine made absolutely no calls to `Dart_NotifyIdle`, the VM would still perform garbage collection. The only issue in such a world would be that the GC pause (more later) would happen in the middle of a frame workload.
* The garbage collection mechanism and its thresholds are implementation details to both the Flutter Engine and the application but the following should serve to explain what is going on internally. I don’t work on the VM and this is only based on my conversations with the Dart VM folks. I am greatly simplifying things here as well but hopefully this serves to calibrate expectations about GC behavior.
  * When the Dart VM and its root isolate are initialized, the memory consumed upto that point are treated as a baseline.
  * A fixed percentage of the memory consumed (I’ve heard this is currently 20% but please don’t quote me on that) over the baseline is treated as the hard threshold.
  * The memory in play is divided into old space and new space. The new space is typically very small and fills up rapidly.
  * The baseline plus the threshold is considered the old space while the small new space is a separate region (typically a few pages).
  * The total old space size minus the max new space size is treated as the soft threshold.
  * In a world where there is no call to `Dart_NotifyIdle`, when the total allocation exceeds the soft threshold, a concurrent mark is initiated in the VM. There is a “small” pause that occurs when the concurrent mark is initiated and another pause when the mark concludes and a sweep is initiated.
  * If the total allocations exceeds the the hard threshold, a “big” stop-the-world pause is initiated.
  * If after either the sweep after the concurrent mark, or, the stop-the-world pause, the consumption returns to be below the soft threshold, the dance begins anew.
  * If after both the “small” and “big” pauses, memory usage is still over the hard threshold, i.e, the objects are still reachable, that amount of memory is treated as the new baseline and a fixed percentage of the new baseline over the new baseline is now the new hard threshold.
  * Updating the baseline will continue till memory for the updated old space can be allocated from the operating system. These allocations will typically fail due to address space exhaustion on 32-bit systems and page table exhaustion on 64-bit systems.
  * Back to `Dart_NotifyIdle`, all it does is initiate the concurrent mark preemptively. The deadline is used by the VM to determine if the corresponding sweep can be performed within the deadline. This way, jank due to “small” pauses can be ameliorated. That’s all.
  * There is no ability to stop a “big” pause on reaching the hard threshold in the old space. The best you can do is release (by making them unreachable) objects eagerly so that the are marked as unreachable in the concurrent mark initiated by either reaching the soft threshold or an explicit `Dart_NotifyIdle`.
  * If you are running out of memory, its because too many large objects were allocation and remained reachable such that the the old space kept growing till it could grow no more.
  * At the edges of allocation thresholds, failures can occur gracefully if the instigating allocation was made in the Dart VM or rather gracelessly if the allocation is made by some native component.
  * That the `Dart_NotifyIdle` is made with extremely small deadlines (sub frame interval) is totally fine because we are attempting to ameliorate the “small” pauses. That most of these notifications do nothing is fine is also fine.

For this reason, I am concluding that this is working as intended. We can of course be smarter in the way we call Dart_NotifyIdle, but if the allegation is that not calling this appropriately is leading to OOMs, that is not true for the reasons listed above. OOMs are due to not enough object being unreachable/collectable.

**Comment by chinmaygarde** [comment] 2020-01-14 01:08
This is WAI for the reason above. Will close pending verification on the internal issue.

**Comment by chinmaygarde** [comment] 2020-01-14 01:09
cc @rmacnak-google @a-siva who know more about the implementation details of the GC (and who explained this to me and may be able to elaborate more on).

**Comment by mehmetf** [comment] 2020-01-14 17:49
I discussed this offline with Gallium team as well.

They are OK with this being WAI provided that the contract of `Dart_NotifyIdle` dictates that it is simple and fast. They were worried that the implementation currently is convoluted and an unintended change in the underlying API calls might cause regression. 

As long as @a-siva is aware of how Flutter is using this API and is committed to keeping that contract, we can close this issue.

**Comment by mehmetf** [comment] 2020-01-14 17:54
Internal bug 146925122 has been closed.

**Comment by chinmaygarde** [comment] 2020-01-14 19:46
> committed to keeping that contract

Was a change to this contract ever under consideration? I was under the impression that this was pretty rock stable. But its possible I have not been privy to planned changes.

> Internal bug 146925122 has been closed.

I closed this. But it hasn't been verified yet. The protocol for syncing internal bugs in not completely clear to me. Should I close issues here that I have marked as Fixed or Wont-Fix but are pending verification?

**Closed** 2020-01-21 19:25 UTC
Labels: customer: dream (g3), engine
