### ISSUE TITLE
shorebird

### ISSUE THREAD

**Issue by Hellomik2002** [flutter/flutter#135220] opened 2023-09-21 13:11 UTC
### Is there an existing issue for this?
https://shorebird.dev/architecture
- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Use case

UPdate mobile app very fast, not in 4-6 days

### Proposal

it is a killer feature, please can you add it to your engine function of shorebird. And allow to create self hosted server that will update builds

**Comment by danagbemava-nc** [comment] 2023-09-21 13:27
Closing this as a duplicate of https://github.com/flutter/flutter/issues/14330

**Closed by danagbemava-nc** 2023-09-21 13:27 UTC
Labels: in triage
