### ISSUE TITLE
Reversed scrollview scrolls in wrong direction on desktop (macos)

### ISSUE THREAD

**Issue by lesnitsky** [flutter/flutter#39194] opened 2019-08-24 21:29 UTC
## flutter doctor:

```
[✓] Flutter (Channel master, v1.9.6-pre.3, on Mac OS X 10.14.5 18F132, locale en-BY)
    • Flutter version 1.9.6-pre.3 at /Users/r1zzu/flutter
    • Framework revision d70daf5021 (19 hours ago), 2019-08-23 22:24:36 -0400
    • Engine revision 00b72a1475
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/r1zzu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/r1zzu/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/r1zzu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2017.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.14.5 18F132

! Doctor found issues in 1 category.
```

## Steps to reproduce

create a custom scroll view and pass `reverse: true` and try to scroll it on macos

## Expected result

view scrolls correctly

## Actual result

scroll direction is reversed

**Comment by lesnitsky** [comment] 2019-08-24 21:37
@gspencergoog could you please have a look at #39159 
This is still a draft, just want to make sure this is an appropriate way to fix the issue

**Comment by stuartmorgan** [comment] 2019-08-24 22:00
Is this a duplicate of #35442?

**Comment by lesnitsky** [comment] 2019-08-24 22:04
oh, didn't find this one.. yes, issues are the same, sorry for the duplicate

**Comment by lesnitsky** [comment] 2019-08-24 22:07
not sure if the root cause is the same for web and desktop. will double check if PR also fixes web issue (probably should)

**Comment by lesnitsky** [comment] 2019-08-25 17:45
@stuartmorgan just checked the web, the same fix works for web as well

**Comment by stuartmorgan** [comment] 2019-08-25 20:45
In that case, closing as a duplicate of #35422

**Closed by stuartmorgan** 2019-08-25 20:45 UTC
Labels: a: desktop, framework
