### ISSUE TITLE
Flutter doctor crashes

### ISSUE THREAD

**Issue by dafta** [flutter/flutter#25620] opened 2018-12-20 12:50 UTC
## Steps to Reproduce
I'm not really sure. It's definitely a local problem because two different versions of flutter had the same issue. Flutter worked before, then suddenly it stopped. I am not sure what changed. I don't even know where to look at to fix the issue, so any help is appreciated.

This is running on a Mac.

## Logs
When running flutter doctor -v:

```
[✓] Flutter (Channel dev, v1.1.3, on Mac OS X 10.13.6 17G65, locale en-HR)
    • Flutter version 1.1.3 at /Users/dream/flutter
    • Framework revision b5df920681 (18 hours ago), 2018-12-19 14:04:42 -0500
    • Engine revision 526e0e3afb
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

⣾Unhandled exception:
FormatException: Unexpected character (at character 1)
Install Started
^

#0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1358:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert/runtime/libconvert_patch.dart:1254:9)
#2      _ChunkedJsonParser.parse (dart:convert/runtime/libconvert_patch.dart:922:22)
#3      _parseJson (dart:convert/runtime/libconvert_patch.dart:29:10)
#4      JsonDecoder.convert (dart:convert/json.dart:540:36)
#5      JsonCodec.decode (dart:convert/json.dart:167:41)
#6      SimControl._list (package:flutter_tools/src/ios/simulators.dart:88:17)
#7      SimControl.getDevices (package:flutter_tools/src/ios/simulators.dart:95:49)
#8      SimControl.getConnectedDevices (package:flutter_tools/src/ios/simulators.dart:109:12)
#9      IOSSimulatorUtils.getAttachedDevices (package:flutter_tools/src/ios/simulators.dart:49:32)
#10     IOSSimulators.pollingGetDevices (package:flutter_tools/src/ios/simulators.dart:38:80)
<asynchronous suspension>
#11     PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:166:52)
<asynchronous suspension>
#12     DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:94:46)
<asynchronous suspension>
#13     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:676:54)
<asynchronous suspension>
#14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:112:52)
#15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:185:41)
#16     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#17     Doctor.diagnose (package:flutter_tools/src/doctor.dart:175:24)
#18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#19     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:448:18)
#22     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#28     Future._complete (dart:async/future_impl.dart:476:7)
#29     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#30     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

I downloaded flutter 1.0.0 and tried running it, and it had the same error.

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-HR)
    • Flutter version 1.0.0 at /Users/dream/flutter
    • Framework revision 5391447fae (3 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

⣾Unhandled exception:
FormatException: Unexpected character (at character 1)
Install Started
^

#0      _ChunkedJsonParser.fail (dart:convert/runtime/libconvert_patch.dart:1358:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert/runtime/libconvert_patch.dart:1254:9)
#2      _ChunkedJsonParser.parse (dart:convert/runtime/libconvert_patch.dart:922:22)
#3      _parseJson (dart:convert/runtime/libconvert_patch.dart:29:10)
#4      JsonDecoder.convert (dart:convert/json.dart:540:36)
#5      JsonCodec.decode (dart:convert/json.dart:167:41)
#6      SimControl._list (package:flutter_tools/src/ios/simulators.dart:88:17)
#7      SimControl.getDevices (package:flutter_tools/src/ios/simulators.dart:95:49)
#8      SimControl.getConnectedDevices (package:flutter_tools/src/ios/simulators.dart:109:12)
#9      IOSSimulatorUtils.getAttachedDevices (package:flutter_tools/src/ios/simulators.dart:49:32)
#10     IOSSimulators.pollingGetDevices (package:flutter_tools/src/ios/simulators.dart:38:80)
<asynchronous suspension>
#11     PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:166:52)
<asynchronous suspension>
#12     DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:94:46)
<asynchronous suspension>
#13     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:687:54)
<asynchronous suspension>
#14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:111:52)
#15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
#16     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#17     Doctor.diagnose (package:flutter_tools/src/doctor.dart:174:24)
#18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#19     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#22     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#28     Future._complete (dart:async/future_impl.dart:476:7)
#29     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#30     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

**Comment by zoechi** [comment] 2018-12-20 13:08
Duplicate of #24811

**Comment by zoechi** [comment] 2018-12-20 13:09
Can you please follow #24811 and if possible provide more information about how to reproduce there - like `xcrun simctl list --json` as mentioned in https://github.com/flutter/flutter/issues/24811#issuecomment-442298621

**Closed by zoechi** 2018-12-20 13:08 UTC

**Comment by dafta** [comment] 2018-12-21 13:36
I don't see how this is a duplicate. The error message is the same but the stack trace is completely different, not to mention I'm running a different command. Clicking 'run' in Android Studio makes no sense because flutter doctor fails everywhere, not just in a project.
