### ISSUE TITLE
flutter run does not launch app on Android 13 (api 33)

### ISSUE THREAD

**Issue by akadatsky** [flutter/flutter#110157] opened 2022-08-24 08:52 UTC
Console command "flutter run" (and IDE button also) can't run app on Andoid 13+ (api 33).

flutter run at the end execute this command:
`adb -s emulator-5556 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example/com.example.MainActivity`

It works pre Android 13, but since that it shows this error:
```
Error type 3
Error: Activity class {com.example/com.example.MainActivity} does not exist.
```

If I replace RUN with MAIN it works:
`adb -s emulator-5556 shell am start -a android.intent.action.MAIN -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example/com.example.MainActivity`

`Starting: Intent { act=android.intent.action.MAIN flg=0x20000000 cmp=com.example/com.example.MainActivity (has extras) }`

Could you please fix it?

**Comment by darshankawar** [comment] 2022-08-24 11:19
Closing this as a duplicate of https://github.com/flutter/flutter/issues/109963

**Closed by darshankawar** 2022-08-24 11:19 UTC
Labels: in triage
