### ISSUE TITLE
Flutter run produces "This app is only...debugger" screen, reload commands do not work

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#49555] opened 2020-01-27 16:48 UTC
I used `flutter create` to create a new project; lib/main.dart is this:
```dart
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(child: Text('Hello World')),
    );
  }
}

void main() {
  runApp(MaterialApp(home: Home()));
}
```

When the app is run a "This app is only meant to be run under the Flutter debugger" screen appears for a moment. Once the real main screen appears, interactive commands like 'r' or 'R' no longer work.

![flutter_01](https://user-images.githubusercontent.com/1377460/73194851-aba8b100-40e1-11ea-9cd3-3f968659e806.png)

**Comment by jonahwilliams** [comment] 2020-01-27 16:53
Duplicate of https://github.com/flutter/flutter/issues/49499

**Comment by zanderso** [comment] 2020-01-27 17:01
Is this a duplicate? It seems like this is not about being slower, but rather is about 'r' and 'R' not working.

**Comment by HansMuller** [comment] 2020-01-27 17:38
Running the app with `--no-fast-start` does "fix" the problem.

**Comment by jonahwilliams** [comment] 2020-01-27 17:39
I'll turn the flag off by default for now, it sounds like there is some more work to do

**Comment by jonahwilliams** [comment] 2020-01-27 21:47
Reducing severity tags now that we're off by default again

**Comment by Siddharthvariya** [comment] 2020-01-31 12:12
"This app is only meant to be run the flutter debugger" show this message first time run the app after second time not show app only show to above message. r and R not  working

**Comment by jonahwilliams** [comment] 2020-05-23 18:07
Going to dedupe into https://github.com/flutter/flutter/issues/49499

**Closed by jonahwilliams** 2020-05-23 18:07 UTC
Labels: a: first hour, t: hot reload, tool
