### ISSUE TITLE
Best practice around async functions and set state

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3951] opened 2016-05-16 22:57 UTC
I have an async function that can end up manipulating the state in multiple places. Where should I setState()?

```
class SomeWidgetState extends State<SomeWidget> {
  String value = "default";
  bool isLoaded = false;

  SomeWidgetState() {
    setupState();
  }

  Future setupState() async {
    var settings = await getSettings();
    try {
      if ( await determineIfShouldUseCustomValue(settings) ) {
        value = await getCustomValue(); // THIS_CHANGES_STATE
      }
    } catch (e) {
      print("error initializing value: $e. using default.");
    } finally {
      isLoaded = true; // THIS_CHANGES_STATE
    }
  }

  Future<Setttings> getSettings() async { // use your imagination }
  Future<bool> determineIfShouldUseCustomValue(Setttings settings) async { // use your imagination }
  Future<String> getCustomValue() { // use your imagination }
}
```

I could just do an empty setState() at the end of my async function. Or I could wrap each individual assignment into its own setState: use a temporary value for `await getCustomValue();` and then assign it to `value` inside of a setState. I would then use a separate setState wrapper around `isLoaded = true`. Which should I go with? Is there a better solution?

Here is what the function may look like for the above solution.
```
  Future setupState() async {
    var setupResult = await setup();
    try {
      if ( await determineIfShouldUseCustomValue(setupResult) ) {
        var tmpValue = await getCustomValue();
        setState((){ value = tmpValue; });
      }
    } catch (e) {
      print("error initializing value: $e. using default.");
    } finally {
      setState((){ isLoaded = true; });
    }
  }
```

Note: I have not attempted to compile any of this code.

**Comment by eseidelGoogle** [comment] 2016-05-16 22:59
This relates to https://github.com/flutter/flutter/issues/3949 as well.

**Comment by abarth** [comment] 2016-05-17 00:02
> I could just do an empty setState() at the end of my async function.

That would have the effect of queuing the writes such that you'd only see their visual effect after all the asynchronous work had completed.  However, the queue wouldn't be reliable.  It's possible for something else in your app to cause the widget to rebuild, in which case you'll see the effects of the individual writes.

> Or I could wrap each individual assignment into its own setState: use a temporary value for await getCustomValue(); and then assign it to value inside of a setState.

That would ensure that you see visual updates for each incremental state change (assuming there's enough time between the asynchronous tasks to put up a frame).

> Which should I go with?

Are the intermediate states meaningful to the user?  Specifically, do you want to ensure that the visual appears of your app updates as you progress through this sequence of operations?  Conversely, do you want to prevent the intermediate states from being shown to the user?

If you want the user to see the intermediate states, you probably want to wrap each write in a setState call.  If you want to prevent the intermediate states from being visible, you might want to actually queue the writes and have them all happen atomically at the end of the series of asynchronous operations.

Putting a single setState at the end of the function is something of the worse of both worlds because the intermediate states will be visible arbitrarily depending on what else is happening in your app.  In the worst case, the intermediate states could be buggy and hard to reproduce.

> Is there a better solution?

Assuming you want to wait for all the operations to complete and then atomically update the state of your object, I'd recommend having the asynchronous object return a representation of all the state changes.  Once the asynchronous operation completes, I'd commit all the changes to your state synchronously inside a single setState call.  That will have the effect of changing your state atomically and ensuring that the visual appearance of your app is updated.

Another issue to consider is what happens if the widget is removed from the tree while the asynchronous operation is pending.  Ideally you'd cancel the asynchronous operation to save resources, but if that's not an option, you might want to check the `mounted` boolean on your State object before committing the changes.

**Comment by drewwarren** [comment] 2016-05-17 00:15
Perfect. thanks.

**Comment by eseidelGoogle** [comment] 2016-05-17 17:27
Do we need to turn this into documentation before closing?  FYI @qchong

**Comment by Hixie** [comment] 2016-05-17 17:46
Incidentally, `Function myFunc() async { }` isn't valid Dart. `Function` here is the return value, but `async` requires that the return value be a `Future<something>`.

**Comment by Hixie** [comment] 2016-05-17 17:46
(Running `flutter analyze` on your package will catch this kind of thing.)

**Comment by drewwarren** [comment] 2016-05-17 18:02
@Hixie yeah, this was me retyping the general idea so I'm sure there are a few mistakes like that. 

> Note: I have not attempted to compile any of this code.

**Comment by eseidelGoogle** [comment] 2016-05-25 16:56
My understanding is that setState now asserts that it's not passed a future-returning function, so I think we can close this.

**Closed by eseidelGoogle** 2016-05-25 16:56 UTC
Labels: affects: framework, customer: fast, ⚠ clear documentation

**Comment by blastrock** [comment] 2017-11-04 20:34
After having read this and googling, it is still not clear to me how to manage state in an async context.

Let's take for example a simple application with two pages. The first page lists Things by name, and the second page allows to edit the name of a Thing.
The Things are stored in a sqlite database and I'm using sqflite which only exposes an async API.

I use a FutureBuilder to make the list appear after the SQL query has finished, but when should I redo the query to refresh the list?

- Refreshing in the build() method makes the screen flash on each rebuild because the query is done again.
- Refreshing in the initState() method would not make the view refresh when the second page changes the name of a Thing.

Whith the second option, one solution I thought of (but didn't test) is to store the first page in a GlobalKey, so that in the second page we can call a refresh method on it. However, this solution scales poorly. If I have an application with lots of pages, I have to remember to refresh all the pages that need a refresh each time I change the state.

I can't find a clean way to implement such a use-case. What would you recommend? Maybe it should be added to the documentation.

**Comment by Hixie** [comment] 2017-11-09 00:44
> when should I redo the query to refresh the list?

This is entirely up to your application. One option may be to have a single class somewhere that wraps your Sqlite database, and that implements the Listenable interface (as well as an interface to update the data, read the data, etc). Then you would pass this object to each widget that cares about the database, rather than have the widgets know anything about Sqlite. Each such widget listens to the object, and when it's time to refresh, you just have that object send a notification to signal each widget to update.

This is more or less what Animation and the classes that use Animations do, for instance.

**Comment by blastrock** [comment] 2017-11-09 19:32
Thanks for the answer. That is indeed a cleaner solution.

I have another question though. There is a page in which I need to wait for the end of a SQL query to set the AppBar title. Having the AppBar title set after the page is shown to the user, or putting a spinner in there seems awkward. For the moment, I make the SQL query in the previous page and put the result in the route, then I parse the route to extract the title so that I can show it right when the page appears. Would you recommend something else?

**Comment by stevenroose** [comment] 2018-01-28 10:49
I have problem with this as well. I have a view where I fetch a resource from a server and when the future returns, I set the state (after the await). Now it crashes when the user already changed views since the future was launched. ("calling setstate after dispose was called").

Do I need like a manual flag "isDisposed" or something to make sure I can setState? 

Actually, this happened to me using a TabBar. So the middle tab would do this async resource fetch and update state. Somehow, going from the first to the third tab, the tabbarview swipes past the middle view, which triggered the http fetch, but the widget got disposed immediately.

**Comment by sroddy** [comment] 2018-01-28 11:25
@stevenroose when your future returns, check the isMounted property and call setState only if true.
Regarding the http requests, I don’t know the tabs api in depth but I would avoid using the initstate method as a trigger and rely on a state that persists across the different tabs and fire the http requests using some callbacks of the tab controller itself

**Comment by Hixie** [comment] 2018-01-29 22:46
better than checking `mounted` is to cancel the work when `dispose` is called.

**Comment by stevenroose** [comment] 2018-01-30 08:35
An http request can't be canceled AFAIK. I first tried with a timer of
300ms that I could cancel in dispose, but eventually decided to redesign
the whole thing with a cache that holds the resources until used.

**Comment by lukepighetti** [comment] 2018-07-10 21:02
I'm coming from React and I'm very confused about how to get data asynchronously and then call setState when its done. Can anyone shed any general wisdom?

**Comment by zoechi** [comment] 2018-07-11 09:12
@lukepighetti https://youtu.be/RS36gBEp8OI might help

**Comment by brokercl** [comment] 2020-11-13 13:39
same trouble

1 StatefulWidget widget execute Posts of Liks GraphQL Query -> ok
2 listView show the Links each of one with a delete Icon that execute the delete mutation(id) when is pressed -> ok
3 the problem is after delete a Link , the widget not rebuild

if (!resutlExeGraphQl.hasException) {
  print(
      'successful condition to rebuild the widget..');
  // refresh page
  setState(() {});
} else {
  print(resutlExeGraphQl.exception);
}

 the code:

import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:navigate09/classes/exeGraphQl.dart';
import 'package:navigate09/mutations/mutations.dart';
import 'package:navigate09/queries/userQuery.dart';

class UserViewScreen extends StatefulWidget {
  final token;
  final userId;
  final userName;

  UserViewScreen({this.token, this.userId, this.userName});
  @override
  _UserViewScreenState createState() => _UserViewScreenState();
}

class _UserViewScreenState extends State<UserViewScreen> {
  var resutlExeGraphQl;
  Mutations mutations = Mutations();
  var titleMessageError;
  var messageError;

  @override
  Widget build(BuildContext context) {

    return Scaffold(
// 1
      body: Query(
        options: QueryOptions(
          documentNode: gql(userQuery),
          variables: {
            'id': widget.userId,
          },
        ),
        builder: (QueryResult result,
            {VoidCallback refetch, FetchMore fetchMore}) {
          if (result.hasException) {
            print(result.exception);
            return Text(result.exception.toString());
          }
          if (result.loading) {
            return Center(child: CircularProgressIndicator());
          }

          if (result.data == null) {
            return Center(child: Text('User not found.'));
          }
// 2
          List links = result.data['user']['links'];
          return Column(
            children: <Widget>[
              Text('links: ${links.length}'),
              ListView.builder(
                shrinkWrap: true,
                itemCount: links.length,
                itemBuilder: (context, linksIndex) {
                  return Column(
                    children: <Widget>[
                      Text(''),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Text(
                            'link ${linksIndex + 1}: ' +
                                'url: ' +
                                links[linksIndex]['url'],
                          ),
                          IconButton(
                              icon: Icon(Icons.delete),
                              onPressed: () async {
                                var resultGraphql = exeGraphQl(
                                    context,
                                    widget.token,
                                    mutations.deleteLink,
                                    'mutation with 1 single variable', // instruccion for the mutation
                                    'linkId',
                                    links[linksIndex]['id'],
                                    null, //var2 tag
                                    null, //var2
                                    null, // var3 tag
                                    null, // var3
                                    titleMessageError,
                                    messageError);
                                resutlExeGraphQl = await resultGraphql;
// 3
                                if (!resutlExeGraphQl.hasException) {
                                  print(
                                      'successful condition to rebuild the widget..');
                                  // refresh page
                                  setState(() {});  // not working..   help
                                } else {
                                  print(resutlExeGraphQl.exception);
                                }
                              }),

                        ],
                      ),
                      Text(
                        'description: ' + links[linksIndex]['description'],
                      ),
                    ],
                  );
                },
              ),
            ],
          );
        },
      ),
    );
  }
}
