### ISSUE TITLE
Size of ipa file is 68.9MB. Is it too large?

### ISSUE THREAD

**Issue by swingywc** [flutter/flutter#23548] opened 2018-10-26 02:47 UTC
I have followed the [instruction](https://flutter.io/get-started/codelab/) to make flutter app. (stop at list of word pairings tutorial). Next I try building release version of iOS following [instruction](https://flutter.io/ios-release/#create-a-build-archive), archives and export from Xcode. 

The ipa file is 68.9MB, while release version of apk file is 5.5MB. Is this normal?
If the size in not normal, how could I find and fix the issue in iOS?
Appreciate for any helps.

**Comment by swingywc** [comment] 2018-10-26 02:52
I run `flutter build ios --flavor production` and see the output path is `build/ios/iphoneos/Runner.app`.
Isn't the correct path should be `build/ios/Release-production-iphoneos/Runner.app`?

![image](https://user-images.githubusercontent.com/9659080/47541791-3910ba80-d90d-11e8-9959-06f1b425667d.png)

**Comment by MisterJimson** [comment] 2018-10-26 20:15
Are you using Swift or Obj C?

Swift will result in much larger ipas.

**Comment by hariprasadiit** [comment] 2018-10-26 22:46
duplicate of #22270

**Comment by zoechi** [comment] 2018-10-27 12:08
@hariprasadiit thanks!
Merging with #22270

**Closed by zoechi** 2018-10-27 12:08 UTC

**Comment by swingywc** [comment] 2018-10-27 12:12
Hi @MisterJimson. How can I know which language I am using?
I am newbie on Flutter so doesn't know much, I just following the installation guide and tutorial.

**Comment by swingywc** [comment] 2018-10-27 12:29
Thank you @zoechi . You saved my days! :)
