### ISSUE TITLE
[Android] Textfield `onChanged` callback triggered on dismissing the keyboard with non empty textfield

### ISSUE THREAD

**Issue by Mayank-9018** [flutter/flutter#92783] opened 2021-10-31 09:39 UTC
## Steps to Reproduce

1. Run this code on Android:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Center(
        child: TextField(
          onChanged: callback,
        ),
      ),
    ));
  }

  void callback(String s) {
    print(s);
  }
}
```
2. Start typing in the textfield and press the back key to dismiss keyboard.

**Expected results:** 

On pressing the back key to dismiss the keyboard, the callback method should **not** be called.

**Actual results:** 

The callback method is called on dismissing the keyboard by pressing the back button

https://user-images.githubusercontent.com/77046231/139576427-5d4fa3e9-6703-436d-8c27-f370705b5c8b.mp4

[Video on youtube if above not playable](https://youtu.be/hGuRvvQaP7E)

This happens only if the textfield has some text. If the textfield is empty, it does not happen. 

<details>

```
[✓] Flutter (Channel stable, 2.5.3, on Pop!_OS 21.04 5.13.0-7620-generic, locale
    en_US.UTF-8)
    • Flutter version 2.5.3 at /home/mayank-pop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mayank-pop/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 12.0.0-3ubuntu1~21.04.2
    • cmake version 3.18.4
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 61.2.2
    • Dart plugin version 203.8430
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12
      (API 31) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Pop!_OS
      21.04 5.13.0-7620-generic
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 95.0.4638.69

• No issues found!

```

</details>

**Comment by nokia6290** [comment] 2021-11-01 07:03
When dismissing the keyboard the textField gets cleaned thus changed. Is it actually a bug?

**Comment by maheshmnj** [comment] 2021-11-01 13:10
Hi @Mayank-9018, thanks for filing the issue I was able to replicate the behaviour on `stable 2.5.3`  and the master channel `2.6.0-12.0.pre.536`. On closing the keyboard by pressing the back button `onChanged` is triggered, This can be reproduced with a non-empty textfield. 

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale en_GB.UTF-8)
    • Flutter version 2.5.3 at /home/mahesh/flutter_sdk/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (2 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile)       • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-38-generic
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.536, on Ubuntu 20.04.3 LTS 5.11.0-38-generic, locale en_GB.UTF-8)
    • Flutter version 2.6.0-12.0.pre.536 at /home/mahesh/flutter_sdk/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7b507f6f6e (2 hours ago), 2021-11-01 11:40:48 +0100
    • Engine revision 3a0a63c2d2
    • Dart version 2.15.0 (build 2.15.0-262.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/mahesh/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.27.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile)       • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 11 (API 30) (emulator)
    • Linux (desktop)                    • linux         • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-38-generic
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 94.0.4606.81

• No issues found!
```
</details>


cc: @justinmc

**Comment by justinmc** [comment] 2021-11-02 18:15
The reason that `onChanged` is triggered is because the composing region is collapsed when the keyboard is hidden.  If you log the whole TextEditingValue you can see what happens (using Gboard in English):

```
TextEditingValue(text: ┤hello├, selection: TextSelection.collapsed(offset: 5, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: 0, end: 5))
TextEditingValue(text: ┤hello├, selection: TextSelection.collapsed(offset: 5, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
```

Because of that I think I'll close this issue.  @Mayank-9018 is this behavior creating a problem for you or can you work around it?  You could check the TextEditingController's TextEditingValue to see if it really changed or not.

**Closed by justinmc** 2021-11-02 18:15 UTC
Labels: a: text input, platform-android, framework, has reproducible steps, found in release: 2.5, found in release: 2.6
