### ISSUE TITLE
Windows 7 Problem event name: AppCrash

### ISSUE THREAD

**Issue by 86speed** [flutter/flutter#74106] opened 2021-01-16 05:50 UTC
## Steps to Reproduce
When I develop and use vs2019 on Windows 7, I can compile and run normally, and when I publish it to windows 10, I can also use it normally. But when I copy the published file to another clean windows 7, I report an error

**Expected results:** 
normal operation

**Actual results:** 
Signature:
Problem event name: AppCrash
Application Name: test2.exe
Application version: 1.0.0.0
Application timestamp: 600263d5
Fault module name: flutter_ windows.dll
Fault module version: 0.0.0.0
Fault module timestamp: 5fd27166
Exception code: 4000015
Anomaly migration: 00000000008e322b
OS version: 6.1.7601.2.1.0.256.1
Locale ID: 2057
Other information 1: 0cc9
Other information 2: 0cc9a80ddcb658055df6cc2ae0b32f41
Other information 3: 41f1
Other information 4: 41f1fbe2976c75f8f5e0b8e9b1577421
Read the privacy statement online:
http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

If you are unable to obtain the online privacy statement, please read our privacy statement offline:
C:\Windows\system32\zh-CN\ erofflps.txt

**Comment by Abhishek01039** [comment] 2021-01-16 06:12
Windows 7 is the end of the life.

**Comment by 86speed** [comment] 2021-01-16 10:06
I probably know what's wrong with GPU,First of all, win7 is on my Parallels Desktop The virtual machine is running. One windows7 has vs2019 installed, which can be developed and displayed normally. The other windows7 is a clean environment. I have developed the vs2019 in windows7 dxgi.dll And d3d11. DLL are copied to the root directory of the EXE program. The program can be opened without any error, but the page displays a black or white screen, but the elements inside can be clicked. So it should be that the page is not rendered normally, and everything else is normal. Is there anything that can be solved?

**Comment by stuartmorgan** [comment] 2021-01-16 14:35
You've described two completely different behaviors here. Does it crash, or does it run but fail to render?

> I have developed the vs2019 in windows7 dxgi.dll And d3d11. DLL are copied to the root directory of the EXE program.

Are you saying you copied OS graphics libraries between machines? You should definitely not be doing that, if so.

**Comment by 86speed** [comment] 2021-01-17 01:45
> You've described two completely different behaviors here. Does it crash, or does it run but fail to render?
> 
> > I have developed the vs2019 in windows7 dxgi.dll And d3d11. DLL are copied to the root directory of the EXE program.
> 
> Are you saying you copied OS graphics libraries between machines? You should definitely not be doing that, if so.

Because my two windows are running on the same MacBook. But win7 can be used normally. Then I checked the dependencies with depends2 and found that their dxgi.dll And d3d11.dll is inconsistent. Copy a good one to another and find that it can run normally, but the page is black and cannot be rendered.

**Comment by stuartmorgan** [comment] 2021-01-17 02:28
Running witha hybrid of graphics libraries from two different OS installs is definitely not supported. Given that that's how you are reproducing this issue, closing.

**Comment by 86speed** [comment] 2021-01-17 04:12
> Running with a hybrid of graphics libraries from two different OS installs is definitely not supported. Given that that's how you are reproducing this issue, closing.
Well, I understand that I'm trying to rule out what caused it,

Direct operation will directly AppCrash
![image](https://user-images.githubusercontent.com/67633762/104830814-44b97480-58bd-11eb-8315-73b8b9c13ffe.png)

**Comment by 86speed** [comment] 2021-01-17 04:18
![image](https://user-images.githubusercontent.com/67633762/104830860-ac6fbf80-58bd-11eb-94b4-ef4560bfc13c.png)
Figure 1 shows the development environment Windows 7

![image](https://user-images.githubusercontent.com/67633762/104830872-e04ae500-58bd-11eb-902e-bceff057e776.png)
Figure 2, clean windows 7

The above two windows 7 are running on the same physical machine

**Comment by stuartmorgan** [comment] 2021-01-17 06:40
I see. I was confused because when I asked for clarification on the issue you were trying to report you focused exclusively on the version where you had copied system libraries around.

Please provide a dump file from the crash, and the `flutter doctor -v` output from your build environment.

**Comment by 86speed** [comment] 2021-01-17 06:58
> I see. I was confused because when I asked for clarification on the issue you were trying to report you focused exclusively on the version where you had copied system libraries around.
> 
> Please provide a dump file from the crash, and the `flutter doctor -v` output from your build environment.

Microsoft Windows [版版本本 6.1.7601]
版版权权所所有有 (c) 2009 Microsoft Corporation。。保保留留所所有有权权利利。。

C:\speed86win>flutter doctor -v
[√] Flutter (Channel dev, 1.26.0-1.0.pre, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.26.0-1.0.pre at C:\flutter
    • Framework revision 63062a6443 (5 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions).

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\win7pz\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 6.1.7601]

! Doctor found issues in 2 categories.


dump:  
http://a1.devtool.com/temp/test2.zip

Store for 24 hours

**Comment by stuartmorgan** [comment] 2021-01-18 00:28
This is failing the `gl_version_string assertion during graphics setup. Duplicate of https://github.com/flutter/flutter/issues/51286

**Closed by stuartmorgan** 2021-01-18 00:28 UTC

**Comment by 86speed** [comment] 2021-01-18 02:12
> This is failing the `gl_version_string assertion during graphics setup. Duplicate of #51286

It's a little different, because my two windows 7 are running on the same physical machine, and the driver of the graphics card is the same. Why is one normal and the other not working?

**Comment by stuartmorgan** [comment] 2021-01-18 13:04
> Why is one normal and the other not working?

Debugging your VM configuration differences is not in scope for Flutter's issue tracker. At this point, the issues are the same from Flutter's perspective: you have a (virtual) machine where the graphics configuration fails, and Flutter should ideally detect that failure and use a fallback.
