### ISSUE TITLE
Stack trace for a failed flutter drive test overflows my bash history

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#5332] opened 2016-08-11 01:12 UTC
I can't see what actually caused the test to fail.

**Comment by abarth** [comment] 2016-08-11 02:31
Can you email us the stack?  We have some code to trim down the stacks and having an example would help us see what else needs to be trimmed.

/cc @Hixie

**Comment by abarth** [comment] 2016-08-11 03:04
Looks like `flutter drive` is missing the stack elider.  The stack has lots of `dart:async/zone.dart`

**Comment by Hixie** [comment] 2016-08-11 16:25
This is a @yjbanov thing, I think. We should probably move it to using the foundation/assertions.dart APIs for handling errors.

**Comment by yjbanov** [comment] 2016-08-11 16:41
This is a duplicate of https://github.com/flutter/flutter/issues/4261

**Closed** 2016-08-11 16:41 UTC
