### ISSUE TITLE
VSCode auto import not working

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#77886] opened 2021-03-11 07:57 UTC
Hello,

I am building app with flutter and noticed that weired behaviour wen VSCode dart auto import stops working. 
When I open vscode fresh auto import works as expected but after some time of development OR after running code generator auto import just stops and i have to re-open vscode. Thi sis frustruating.

Not sure if this 100% applies here but please redirect me to some other sources if it does not belong here.

p.s. i searched on internet about this problem - cannot find any solutions like here: https://www.reddit.com/r/flutterhelp/comments/hgz70k/vs_code_autoimport_suggestions_have_stopped/

**Comment by TahaTesser** [comment] 2021-03-11 11:41
Hi @vytautas-pranskunas- 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-11 11:41 UTC
Labels: in triage
