### ISSUE TITLE
Flutter Autocomplete for Packages Not Working.

### ISSUE THREAD

**Issue by Jatin-Sondagar** [flutter/flutter#60472] opened 2020-06-28 14:38 UTC
Hello there,
I am trying to learn flutter. I have tried installing packages from website : "https://pub.dev/flutter/packages".
packages for firebase integration in android. I have followed all the steps needed to integrate firebase in flutter and it works.
But When i try to use classes from those packages like FirebaseUser, the autocomplete not working.
**ISSUE** : when i type something like Fire then it should show all the related suggestions from all lib but its not working as expected.
It does not show classes from external packages.
I have tried so many solutions but nothing worked.

Help me solve this.

**Comment by bierbaumtim** [comment] 2020-06-28 15:58
Hi @Jatin-Sondagar 
could you provide your `flutter doctor -v` and which IDE you use?

**Comment by Jatin-Sondagar** [comment] 2020-06-29 04:07
Hello,

I am using

flutter plugin version : 47.0.2
Dart Plugin version : 193.7361

I am using Android Studio 4.0.

Thanks

**Comment by darshankawar** [comment] 2020-06-29 05:24
Hi @Jatin-Sondagar , by Flutter Autocomplete, are you referring to this plugin https://pub.dev/packages/autocomplete_textfield ?

**Comment by Jatin-Sondagar** [comment] 2020-06-29 07:05
hello there,

sorry for misspelled.

autocomplete in terms that when i try to type a class name like Firebase
then it must show all class related to firebase but that's not working.

i need help with this.
Thanks

**Comment by darshankawar** [comment] 2020-06-29 07:12
Hi @Jatin-Sondagar, 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by Jatin-Sondagar** [comment] 2020-06-29 08:12
Flutter plugin version :  47.0.2
Android Studio : 4.0
Dart  Version : 2.8.4

Please check the attached image for what actually is not working.

**Comment by darshankawar** [comment] 2020-06-29 12:28
Hi @Jatin-Sondagar, I can't find the image you attached. Please attached again in your comment.

**Comment by Jatin-Sondagar** [comment] 2020-06-29 12:30
Please check this image

**Comment by darshankawar** [comment] 2020-06-29 13:25
@Jatin-Sondagar, I still don't see any image you attached. Check this link on how to attach an image (https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests). Also, share `flutter doctor -v` log. You need to run the command `flutter doctor -v` from the terminal from root of your flutter project path, and paste the log here in proper format.

**Comment by Jatin-Sondagar** [comment] 2020-06-29 14:13
> Hello there,
> I am trying to learn flutter. I have tried installing packages from website : "https://pub.dev/flutter/packages".
> packages for firebase integration in android. I have followed all the steps needed to integrate firebase in flutter and it works.
> But When i try to use classes from those packages like FirebaseUser, the autocomplete not working.
> **ISSUE** : when i type something like Fire then it should show all the related suggestions from all lib but its not working as expected.
> It does not show classes from external packages.
> I have tried so many solutions but nothing worked.
> 
> Help me solve this.

![Untitled](https://user-images.githubusercontent.com/47779311/86016675-bb397680-ba40-11ea-918e-a097266e46c7.png)

**Comment by thatsenam** [comment] 2020-06-29 20:09
> > Hello there,
> > I am trying to learn flutter. I have tried installing packages from website : "https://pub.dev/flutter/packages".
> > packages for firebase integration in android. I have followed all the steps needed to integrate firebase in flutter and it works.
> > But When i try to use classes from those packages like FirebaseUser, the autocomplete not working.
> > **ISSUE** : when i type something like Fire then it should show all the related suggestions from all lib but its not working as expected.
> > It does not show classes from external packages.
> > I have tried so many solutions but nothing worked.
> > Help me solve this.
> 
> ![Untitled](https://user-images.githubusercontent.com/47779311/86016675-bb397680-ba40-11ea-918e-a097266e46c7.png)

May be you are missing android flutter or dart extension.  You can download this from Android Studio > Plugins > search for dart and flutter and restart the ide.

**Comment by Jatin-Sondagar** [comment] 2020-06-30 05:17
that's all i have already tried but not working anything.

**Comment by darshankawar** [comment] 2020-06-30 05:37
@Jatin-Sondagar , did you try by restarting the IDE through `File -> Invalidate Caches/Restart -> Invalidate and Restart ?`

**Comment by Jatin-Sondagar** [comment] 2020-06-30 05:38
yes

**Comment by Jatin-Sondagar** [comment] 2020-06-30 05:39
yes but still not resolved

**Comment by thatsenam** [comment] 2020-06-30 07:01
Ok you enablec power mood in android studio. Turn it off. File> Power
Saving Mode. And restart AS.

**Comment by Jatin-Sondagar** [comment] 2020-06-30 07:59
I didn't have enabled power saving mode still the same issue

**Comment by thatsenam** [comment] 2020-06-30 08:07
[image: image.png]
toggle the power saving mode sometimes and restart AS

**Comment by darshankawar** [comment] 2020-06-30 13:07
@Jatin-Sondagar, can you try to replicate this issue in vscode ?

**Comment by Jatin-Sondagar** [comment] 2020-06-30 13:11
i don't have visual studio to replicate code

**Comment by bierbaumtim** [comment] 2020-06-30 13:16
@darshankawar I experience some similar issues is VS Code.
After adding a package to a pubspec the IntelliSense for this package does not work. After reloading the window everything works fine. 
But I have all four flutter version installed. So maybe that does not work together.

Also in some projects the automatic import does not work, but because I can’t reproduce it completely I did not file an issue for that.

**Comment by TahaTesser** [comment] 2020-06-30 14:17
I’m unable to reproduce the issue to pinpoint the cause, but there are reports from several users. The issue needs further investigation.

**Comment by Jatin-Sondagar** [comment] 2020-06-30 15:00
so you mean i need to continue with this issue, right?

**Comment by devoncarew** [comment] 2020-07-01 00:02
@TahaTesser - what are the other issues? Is there a common theme / one issue w/ the most repro steps?

@Jatin-Sondagar - for https://github.com/flutter/flutter/issues/60472#issuecomment-651149193, what are the imports in your file? Do they include the firebase libraries? Do you see completion working for symbols from libraries that you do have imports for?

**Comment by devoncarew** [comment] 2020-07-01 00:03
In this thread, I don't see the version of the flutter sdk in use; that info would be useful as well.

**Comment by TahaTesser** [comment] 2020-07-01 07:59
@Jatin-Sondagar 
Please provide `flutter doctor -v` as asked here https://github.com/flutter/flutter/issues/60472#issuecomment-650976640  here https://github.com/flutter/flutter/issues/60472#issuecomment-650785641 and here https://github.com/flutter/flutter/issues/60472#issuecomment-651119283

Also please answer details asked here https://github.com/flutter/flutter/issues/60472#issuecomment-652109472

We need more information to better address the issue

**Comment by Jatin-Sondagar** [comment] 2020-07-01 09:03
> @Jatin-Sondagar
> Please provide `flutter doctor -v` as asked here [#60472 (comment)](https://github.com/flutter/flutter/issues/60472#issuecomment-650976640) here [#60472 (comment)](https://github.com/flutter/flutter/issues/60472#issuecomment-650785641) and here [#60472 (comment)](https://github.com/flutter/flutter/issues/60472#issuecomment-651119283)
> 
> Also please answer details asked here [#60472 (comment)](https://github.com/flutter/flutter/issues/60472#issuecomment-652109472)
> 
> We need more information to better address the issue



flutter doctor -v == 
![Untitled](https://user-images.githubusercontent.com/47779311/86224346-63b51b00-bba6-11ea-8932-0c533ccf4c85.png)

code i am using == https://drive.google.com/file/d/1s5bck2XD-wcfoxjGVr46q3I-XDYWa9br/view?usp=sharing


try to resolve ASAP

**Comment by thatsenam** [comment] 2020-07-01 10:23
Is it happening only for firebase or the whole flutter framework??

**Comment by TahaTesser** [comment] 2020-07-01 12:45
Hi @Jatin-Sondagar 
Looks like an issue with your project itself 
Here i can tried fresh new project and your project on latest `stable` channel 

### New Project with `cloud_firestore`
![Annotation 2020-07-01 181122](https://user-images.githubusercontent.com/48603081/86244960-5dcf3200-bbc6-11ea-957b-8de145c04717.png)



### Your  Project with `cloud_firestore`
![Annotation 2020-07-01 180636](https://user-images.githubusercontent.com/48603081/86244730-0761f380-bbc6-11ea-9184-9e72b71c3c4a.png)

<details> 
<summary>flutter doctor -v</summary> 

``` 
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.331], locale en-US)
    • Flutter version 1.17.5 at C:\Code\flutter_stable
    • Framework revision 8af6b2f038 (17 hours ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.
[√] Android Studio (version 4.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0
[!] Connected device
    ! No devices available
! Doctor found issues in 1 category.
``` 

</details> 

Please a create fresh new project and add `cloud_firestore` and type Firestore in your code
Thank you

**Comment by Jatin-Sondagar** [comment] 2020-07-02 04:30
I have done it already and you have imported my code in vs so how will you
get the isuue if its android studio issue

**Comment by TahaTesser** [comment] 2020-07-02 06:53
@Jatin-Sondagar 
It's an issue with your project, i can reproduce the issue your project files but not with new project in Android Studio
Please try new project in Android Studio as mentioned earlier https://github.com/flutter/flutter/issues/60472#issuecomment-652396430 

Thank you

**Comment by iapicca** [comment] 2020-07-29 12:26
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-07-29 12:26 UTC
Labels: in triage, waiting for customer response

**Comment by MuhammadFaizan980** [comment] 2020-08-06 13:44
Make sure you have put the dependencies under "dependencies", not under "dev_dependencies",

**Comment by perseus98** [comment] 2020-12-18 11:50
I am also facing the same issue for somewhat a month from now, in my case, the code completion does recognizes any widgets but it pops suggestions for attributes.

**Comment by mamd33** [comment] 2020-12-18 17:17
> EDIT: after tweaking some settings in android studio, looks like everything is back to normal, P.S. I accidently turned 'OFF' code completion in experimental section of compiler settings

Please can you be more clear ? "Code completion" in "Compiler Settings" ? Using Android Studio ?
