### ISSUE TITLE
Keyboard Automatically close on tap in textfield in samsung Galaxy J6 and other samsung device  and Some Time tap on textfield to crash app 

### ISSUE THREAD

**Issue by gautamchauhan1702** [flutter/flutter#78760] opened 2021-03-22 04:48 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2021-03-22 13:49
Hi @gautamchauhan1702 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by gautamchauhan1702** [comment] 2021-03-23 04:16
@TahaTesser 
flutter doctor -v
Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/lw-37/Development/flutter
    • Framework revision 9b2d32b605 (8 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/lw-37/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

**Comment by TahaTesser** [comment] 2021-03-23 07:51
Hi @gautamchauhan1702 
You seem to use an older `stable` setup. 
Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Also please provide cash logs with `flutter run --verbose` and a minimal code sample. 
Which version of Android you're using on J6? (since you're missing details `flutter doctor -v`
Thank you

**Comment by gautamchauhan1702** [comment] 2021-03-26 04:54
Hi @TahaTesser 
Android 11

**Comment by TahaTesser** [comment] 2021-03-26 07:08
@gautamchauhan1702 
Can you please provide all the details from https://github.com/flutter/flutter/issues/78760#issuecomment-804694274 and Galaxy J6 seems to have [Android 10 as the latest update](https://user-images.githubusercontent.com/48603081/112595217-c58f7200-8e12-11eb-9c7d-e0d1fcc02f2a.png), not Android 11

**Comment by pedromassangocode** [comment] 2021-04-16 08:51
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-16 08:51 UTC
Labels: in triage, waiting for customer response
