### ISSUE TITLE
Virtual keyboard action does not change when focus change.

### ISSUE THREAD

**Issue by ltvu93** [flutter/flutter#34309] opened 2019-06-12 03:41 UTC
Hi guys. Today I try to implement form field in flutter follow [this page](https://flutter.dev/docs/cookbook/forms/focus). Although I declared two different textInputAction in TextFields, keyboard action does not change when focus change. If I declare different keyboardType in TextFields everything works like normal. Seems like textInputAction does not notify keyboard to change.

**Steps to reproduce:**
1/ Click on first TextField to show virtual keyboard (action  Next).
2/ Click on FloatingActionButton to change focus to second TextField. Keyboard action doesn't change, still in action Next, must change to action Done).
If I just click on the second TextField when the keyboard doesn't show, everything works like expected, keyboard action is Done.

```

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Image picker',
      theme: new ThemeData(
        primaryColor: const Color(0xFF02BB9F),
        primaryColorDark: const Color(0xFF167F67),
        accentColor: const Color(0xFF167F67),
      ),
      home: MyCustomForm(),
    );
  }
}

class MyCustomForm extends StatefulWidget {
  @override
  _MyCustomFormState createState() => _MyCustomFormState();
}


class _MyCustomFormState extends State<MyCustomForm> {

  FocusNode myFocusNode;
  final GlobalKey<FormState> _formKey = new GlobalKey<FormState>();

  @override
  void initState() {
    super.initState();

    myFocusNode = FocusNode();
  }

  @override
  void dispose() {
    myFocusNode.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Text Field Focus'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextField(
//                Enable this code bellow, keyboard action change like expected
//                keyboardType: TextInputType.emailAddress,

                autofocus: true,
                textInputAction: TextInputAction.next,
              ),
              TextField(

                focusNode: myFocusNode,
                textInputAction: TextInputAction.done,
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => FocusScope.of(context).requestFocus(myFocusNode),
        tooltip: 'Focus Second Text Field',
        child: Icon(Icons.edit),
      ),
    );
  }
}
```

**flutter doctor infos**
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.557], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.4)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code, 64-bit edition (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

Test on Nokia 7 plus (android 9), emulator (android 5).

**Comment by shihaohong** [comment] 2019-06-12 20:43
Hi @ltvu93, I just tested this on the `master` branch and it seems to be working. What I'm observing is:
1. Keyboard starts off showing `TextInputAction.next` button on bottom-right of keyboard.
2. Tap on FAB or second `TextField`.
3. Keyboard now shows `TextInputAction.done` button. 

Let me know if I interpreted your issue correctly, and if not, please correct my understanding! Thanks

**Comment by ltvu93** [comment] 2019-06-13 02:39
@shihaohong Sorry, I posted working code in yesterday, please check my edited comment for bugs code block and addition information.

**Comment by shihaohong** [comment] 2019-06-13 03:00
I'll test this again tomorrow since it's the end of the day for me here, but if I remember correctly, I did try commenting out `keyboardType: TextInputType.emailAddress,` and it still turned out okay. Could you check with the `master` branch to see if this is still happening for you? Thank you for adding more details to the original post!

**Comment by ltvu93** [comment] 2019-06-13 03:27
@shihaohong I switched to master channel to test, still get this bug.
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.7.4-pre.85, on Microsoft Windows [Version 10.0.17763.557], locale en-US)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
[√] Android Studio (version 3.4)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] VS Code, 64-bit edition (version 1.33.1)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by shihaohong** [comment] 2019-06-14 16:29
It seems to work fine for me, the bottom right button icon changes when I focus on the second field.
![virtual keyboard](https://user-images.githubusercontent.com/27032613/59523654-b120f600-8e86-11e9-9e48-12e6d20e4074.gif)

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.7.4-pre.108, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.34.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by ltvu93** [comment] 2019-06-17 08:22
@shihaohong I think I found what causes this issue. This bug only happens when I use a custom keyboard if I use default google keyboard everything work fine.

**Custom keyboard (Laban key)**
![custom](https://im2.ezgif.com/tmp/ezgif-2-d010487ba7b1.gif)
**Google keyboard**
![goole](https://im2.ezgif.com/tmp/ezgif-2-0be9ccdaa268.gif)

**Comment by carmas123** [comment] 2020-01-17 10:27
This problem reappear in Flutter 1.12

**Comment by TahaTesser** [comment] 2020-06-05 11:30
@ltvu93  @carmas123  
Are you still experiencing this issue on latest `Channel stable, v1.17.3`?
I am not able to reproduce the issue on latest `(Channel dev, 1.19.0-3.0.pre` gboard or samsung keyboard

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.19.0-3.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 6135091de9 (3 days ago), 2020-06-01 17:17:03 -0700
    • Engine revision e39301f23f
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details> 
Thank you

**Comment by huafu** [comment] 2020-06-05 13:36
@TahaTesser (_I'm not sure it's the same issue_): I'm on slow connection and actually going from Flutter `1.17.2` to `1.17.3` right now. Anyway in the `1.17.2` with only one input wrapped by a `BlocBuilder` (from `flutter_bloc`), when the state changes, the `decoration` modification is reflected visually but not the `textInputAction` (from `TextInputAction.none` to `TextInputAction.search`).

**Comment by darshankawar** [comment] 2020-08-12 09:45
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-08-12 09:45 UTC
Labels: a: text input, f: material design, framework, waiting for customer response

**Comment by omidraha** [comment] 2021-03-02 06:11
Same issue here.

**Comment by TahaTesser** [comment] 2021-03-02 11:25
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
