### ISSUE TITLE
Camera API for Desktop

### ISSUE THREAD

**Issue by InvertedX** [flutter/flutter#74658] opened 2021-01-25 17:50 UTC
## Use case
This would be really helpful for desktop platform to take photos or scanning QR codes.
Flutter camera package is already exist but only for android and IOS 
is there any plan for this ?

**Comment by stuartmorgan** [comment] 2021-01-25 18:19
Duplicate of #41708, #41709, #41710

**Closed by stuartmorgan** 2021-01-25 18:19 UTC
