### ISSUE TITLE
[cupertino_icons] add tree shaking

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/flutter#80288] opened 2021-04-12 16:48 UTC
1. create any flutter app and `cupertino_icons` to dependencies
```yaml
cupertino_icons: ^1.0.1
```
2. `flutter build apk`
3. deobfuscate (for example with https://www.decompiler.com)
4. see the contents of `resources/assets/flutter_assets/packages/cupertino_icons/assets`, which contains `CupertinoIcons.ttf` of size 277 KB

here's an already deobfuscated file
[app.apk.zip](https://github.com/flutter/flutter/files/6298401/app.apk.zip)

the font should be tree shaked, and if i didn't use `CupertinoIcons` at all, it should not end up being in the release archive

<details>
<summary>code sample (empty flutter app)</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'App',
      home: Scaffold(
        body: Container(),
      ),
    );
  }
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.574, on Microsoft Windows [Version 10.0.19041.867], locale ru-RU)
    • Flutter version 2.1.0-13.0.pre.574 at c:\dev\src\flutter
    • Framework revision 02efffc134 (33 hours ago), 2021-04-10 03:49:01 -0400
    • Engine revision 8863afff16
    • Dart version 2.13.0 (build 2.13.0-222.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\danya\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.1)
    • VS Code at C:\Users\danya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
```
</details>

**Comment by darshankawar** [comment] 2021-04-13 07:32
I got the CupertinoIcons.ttf file size of 283kb.

Labeling this as a proposal.

**Comment by jonahwilliams** [comment] 2021-04-13 19:49
FYI @dnfield . I'm not sure if there is anything special about cupertino icons - maybe the font and the constants being in separate packages?

**Comment by dnfield** [comment] 2021-04-13 19:56
If you didn't use them at all you will end up with the full set. We can only shake if you used at least one.

**Comment by jonahwilliams** [comment] 2021-04-13 19:56
TIL

**Comment by dnfield** [comment] 2021-04-13 19:57
I can't remember exactly why that is now. I'll try to find the issue

**Comment by MrBirb** [comment] 2021-04-13 20:00
@dnfield #63920

**Comment by dnfield** [comment] 2021-04-13 20:03
Yes, thanks!  Closing this as a duplicate of #64106

**Closed by dnfield** 2021-04-13 20:03 UTC
Labels: f: cupertino, framework, passed first triage, proposal, severe: new feature, tool
