### ISSUE TITLE
Landscape mode in not working on iOS 14 in Chewie video player 

### ISSUE THREAD

**Issue by Paras2895** [flutter/flutter#69652] opened 2020-11-03 08:07 UTC
I'm using Chewie video player (https://pub.dev/packages/chewie) for my flutter application to play video in app, but I stuck into a problem. I have three devices :
Iphone 11     iOS 14
iPhone 6s    iOS 14
iPhone 6s   iOS 13

In my iPhone 6s with iOS 13 video player in landscape mode is working fine but when I come to other two mobile having iOS 14 with same code landscape mode is not working. Please help me to resolve my concern.

**Comment by pedromassangocode** [comment] 2020-11-03 08:27
Hi @Paras2895 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/brianegan/chewie).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-11-03 08:27 UTC

**Comment by Paras2895** [comment] 2020-11-03 08:33
Hi can you please suggest me what i can do to enable landscape mode in
ios14 because in ios13 it works

**Comment by pedromassangocode** [comment] 2020-11-03 13:57
Hi @Paras2895 
I would suggest you to contact the owner of the package so that he fix this issue in the package itself.
