### ISSUE TITLE
textCapitalization seemingly not working to spec (.none / .sentences)

### ISSUE THREAD

**Issue by chornbe** [flutter/flutter#37613] opened 2019-08-05 12:04 UTC
**Issue**:
When I have two text fields on a screen, one with textCapitalization.none and the next with .sentences, switching between the two text fields doesn't change the keyboard appearance, or the upper- / lower- of the first letter of a sentence.

I specifically only tested this on iOS; behavior is the same in emulator and on device. I did not check Android yet. Will follow up with Android testing at some point. For now, it's easily viewed in the attached GIF.

**Code**:
```
          TextField(
            controller: tc,
            decoration: InputDecoration(
              hintText: "Name of your medication",
            ),
            onEditingComplete: (){
              FocusScope.of(context).requestFocus(new FocusNode());
            },
            textCapitalization: TextCapitalization.none,
            autocorrect: true,
            keyboardType: TextInputType.text,
          ),

```
      TextField(
        controller: tcd,
        decoration: InputDecoration(
          hintText: "Describe the medication",
        ),
        maxLines: 2,
        textCapitalization: TextCapitalization.sentences,
        autocorrect: true,
        keyboardType: TextInputType.text,
      ),

**Additional info**:
The cap works if I tap into the second field first, but doesn't reset when I go to the first field, and vice-versa starting at first field.

Using Cupertino text boxes rather than Material doesn't seem to make a difference, nor does changing the keyboard types, autoCorrect (nor should it), etc. It kinda just does whatever the first-focused textfield is configured to do and doesn't change from there on.

Thanks!

**GIF showing issue**:
![62432679-119e1800-b6ff-11e9-8d9a-6f4e72894786](https://user-images.githubusercontent.com/7502201/62463377-db40b700-b757-11e9-8e20-e006da51be27.gif)

**Comment by justinmc** [comment] 2019-09-17 21:10
This seems to not affect Android if I'm understanding correctly:

![capitalization](https://user-images.githubusercontent.com/389558/65079774-bb0a3780-d954-11e9-9934-aa163262eba1.gif)

**Comment by encounter** [comment] 2020-01-13 21:06
I also discovered this issue on several forms in my app where the textCapitalization property differs between TextFields.

This commit in Qt for iOS details a possible solution: https://github.com/qt/qtbase/commit/6910b8a552de6f0cd98fdfa50620825d59d63363, utilizing UIResponders that get recreated on certain properties changed instead of updating a UITextInput directly.

This may also eliminate the need for separate UITextViews for normal/secure input: https://github.com/flutter/engine/blob/5ef2c7968c7215acaffddd008a8ccabeb7cb6706/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm#L685-L687 if I'm understanding correctly.

I'm not able to work on a solution for it at the moment, but thought I'd share my findings.

**Comment by justinmc** [comment] 2020-01-13 21:49
@encounter Nice detective work, that could be on the right track.  Thanks for taking a look.

**Comment by TahaTesser** [comment] 2020-07-01 13:38
duplicate of https://github.com/flutter/flutter/issues/59374

**Closed by TahaTesser** 2020-07-01 13:38 UTC
Labels: a: text input, f: material design, framework
