### ISSUE TITLE
Dropdown should follow the App Theme settings

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#37473] opened 2019-08-02 11:11 UTC
I have a DropDown and a TextField side by side and the couple looks odd.
The two obvious issues are underline color and content spacing on the dropdown.
I can come up with a workaround using Dropdown's custom underline and hand-tuned inputDecorationTheme.contentPadding but it should really be implemented inside the framework.
FWIW I use app-wide theme with custom underline color and input contentPadding.

![image](https://user-images.githubusercontent.com/1481807/62366485-b0741a00-b52f-11e9-8a6b-4ada2951e059.png)

**Comment by Hixie** [comment] 2023-03-17 22:21
I'm going to close this because it's lacking a test case that we can use to reproduce it. Please don't hesitate to file a new bug if you're still seeing this.

**Closed by Hixie** 2023-03-17 22:21 UTC
Labels: new feature, framework, f: material design
