### ISSUE TITLE
Profile builds reporting drastically poorer performance than release builds

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#35409] opened 2019-07-01 16:53 UTC
This isn't the usual performance build slowdown, but appears to be a greater disparity. Internal bug at https://b.corp.google.com/issues/134769255; please refer to the conversation there.

**Comment by Hixie** [comment] 2019-07-02 23:50
This is scheduled to happen after customer:dream P0s.

**Comment by Hixie** [comment] 2019-07-11 22:18
The plan here is to try to add more testing (see #34069) to identify the issue.

**Comment by Hixie** [comment] 2019-09-03 23:14
Status: waiting for dream to give us concrete reproduction instructions.

**Comment by liyuqian** [comment] 2019-09-09 21:21
Instructions received. Trying them now. Will give an update by the end of today.

**Comment by liyuqian** [comment] 2019-09-10 00:20
Both Jason and I tried to follow those steps and ran into the same issue. More details of the problem is posted to b/134769255

**Comment by Hixie** [comment] 2019-09-17 23:46
We are unaware of any actionable work here. Leaving the bug open so we remember to check with the upstream bug regularly.

**Comment by liyuqian** [comment] 2019-09-19 23:32
Closing this issue as https://b.corp.google.com/issues/134769255 is marked as "Won't Fix (Not reproducible)"

**Closed** 2019-09-23 18:23 UTC
Labels: customer: dream (g3), engine, severe: customer critical, severe: performance
