### ISSUE TITLE
[Android] App shows black screen after being in the background.

### ISSUE THREAD

**Issue by vanth0me** [flutter/flutter#93276] opened 2021-11-08 20:41 UTC
## Steps to Reproduce

It seems to happen on different Flutter apps. Open a Flutter app, go to your home screen and open some other apps. Wait for some time and open the Flutter app again. There is now a chance that the app shows a black screen. No Appbar, BottomBar or any widget. It happens pretty frequently if you know how to trigger it. 

<img src="https://user-images.githubusercontent.com/28623044/140814927-46414cbf-b39d-4c8c-a957-42ecdb9e0475.jpg" width ="300">

The app seems to respond to user interaction, just had it on the debugger but there is no useful information, no errors, no exceptions thrown. Moving to the android recents screen and returning to the app fixes this. I haven't tried to do this with iOS.

Was able to reproduce this on some older installed apps, app created with Flutter stable 2.5.3 and the latest beta build (2.7.0 iirc).

I can't really create an app sample because it is pretty hard to know when it exactly happens because it is not guaranteed to happen. It does occur on multiple devices and some users have noticed it too. No data on crashlytics or runguarded zone.

```
[✓] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.282], locale en-NL)
    • Flutter version 2.5.3 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\dxzds\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.2)
    • VS Code at C:\Users\dxzds\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • IN2023 (mobile) • 192.168.0.165:40423 • android-arm64  • Android 11 (API 30)
    • Chrome (web)    • chrome              • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)      • edge                • web-javascript • Microsoft Edge 95.0.1020.44
```

**Comment by maheshmnj** [comment] 2021-11-09 08:56
Hi @vanth0me, Thanks for filing the issue.

> I can't really create an app sample because it is pretty hard to know when it exactly happens because it is not guaranteed to happen. It does occur on multiple devices and some users have noticed it too. No data on crashlytics or runguarded zone.

 Can you please share some more details 
- How long have you put the app in the background?
- which Android devices reproduce the issue?
- Does this reproduce on an emulator too or only on a real device?
- Can you please also check if this happens with a specific flutter project or a newly created flutter project too?

**Comment by vanth0me** [comment] 2021-11-09 09:13
Thank you for your response!
I think usually happens after 5+min, but I've had it sooner. From the devices I know it is my OnePlus 8 Pro, Samsung S10 and the emulator too. I recreated the project and moved the code and the same thing happened. As I have said older self made apps also show this. I don't know if I can trigger it with the base app. I will have to try that later today.

**Comment by maheshmnj** [comment] 2021-11-09 09:41
>  I don't know if I can trigger it with the base app. I will have to try that later today.

Sure please verify and let us know and also please check the android version of the devices to make sure if this is/ is not related to the OS version.

**Comment by vanth0me** [comment] 2021-11-09 10:29
Yes will do. My emulator is running Android 12 and the devices are running Android 11.

**Comment by vanth0me** [comment] 2021-11-10 11:06
I am, for now, at least unable to trigger a black screen in the New Flutter Project app. I wonder if it has something to do with more memory usage.

**Comment by maheshmnj** [comment] 2021-11-10 11:57
@vanth0me without any code sample or logs its not possible to find the cause of the issue.

> I am, for now, at least unable to trigger a black screen in the New Flutter Project app. I wonder if it has something to do with more memory usage.

Are there any logs that you can share?
Is it possible for you to share a repository containing the reproducible code?

**Comment by vanth0me** [comment] 2021-11-10 12:24
I can't share the app I'm currently working on, but I can share a private project where it just happend. I think it is on BitBucket, is there an easy way to share this with you?

**Comment by liwangyong** [comment] 2021-11-11 01:57
me too

**Comment by zhangruiyu** [comment] 2021-11-11 02:45
Huawei Mate30 Pro, I have encountered this problem many times

**Comment by maheshmnj** [comment] 2021-11-11 05:45
@liwangyong @zhangruiyu can you guys please share a reproducible steps along with the output of `flutter doctor -v` and the related logs?

**Comment by maheshmnj** [comment] 2021-11-11 08:39
@vanth0me I tried running your project and it fails to build it, looks like there are some compile-time errors could you please recheck?

**Comment by vanth0me** [comment] 2021-11-11 09:24
@maheshmnj I fixed it, looked like it was a really early version for some reason. The steps are open the app, I don't know if logging in helps but then just switch to another app, wait some time and hope it gives a black screen. The difficulty is finding the balance between opening too soon and the app being killed. There is sadly no guarantee it will happen.

**Comment by maheshmnj** [comment] 2021-11-11 10:26
@vanth0me there is a build time error now the `bezier_chart` doesn't seem to support null safety. Alternatively, you may also try upgrading to latest master by running 

```
flutter channel master 
flutter upgrade
```

> From the devices I know it is my OnePlus 8 Pro, Samsung S10 and the emulator too

And if you still face the issue please provide the emulator details on which the issue reproduces as the above devices are not available for me to test.


<details>
<summary>build failure logs</summary>

```
mahesh@Maheshs-MacBook-Air-M1 black-screen-test % git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Updating 1b0523f..331937e
error: The following untracked working tree files would be overwritten by merge:
        .flutter-plugins
        .flutter-plugins-dependencies
        .packages
        pubspec.lock
Please move or remove them before you merge.
Aborting
mahesh@Maheshs-MacBook-Air-M1 black-screen-test % git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Updating 1b0523f..331937e
Fast-forward
 .flutter-plugins                       |  17 ++++
 .flutter-plugins-dependencies          |   1 +
 .gitignore                             |  74 ++++++++++++++
 .metadata                              |  10 ++
 .packages                              |  80 +++++++++++++++
 analysis_options.yaml                  |  29 ++++++
 lease_log.iml                          |  33 ++++++
 lib/extensions/date.dart               |  11 ++
 lib/generated_plugin_registrant.dart   |  21 ----
 lib/main.dart                          |  56 ++++++-----
 lib/models/log.dart                    |  43 ++++++++
 lib/models/ride.dart                   |   4 -
 lib/models/tank.dart                   |  25 +++++
 lib/models/user.dart                   |  35 +++++++
 lib/providers/circularData.dart        |  43 ++++++++
 lib/providers/data.dart                | 190 ++++++++++++++++++++++++++++++++++
 lib/providers/fuel.dart                | 115 +++++++++++++++++++++
 lib/providers/initialSetup.dart        |  90 +++++++++++++++++
 lib/providers/lease.dart               |  38 +++++++
 lib/providers/login.dart               |  69 ++++++++-----
 lib/providers/monthlyChart.dart        |  40 ++++++++
 lib/providers/theme.dart               |   3 +
 lib/providers/totalChartB.dart         |  65 ++++++++++++
 lib/providers/user.dart                |  40 ++++++++
 lib/screens/data.dart                  |  26 +++++
 lib/screens/homescreen.dart            | 105 +++++++++++++++++--
 lib/screens/initialSetup.dart          | 214 +++++++++++++++++++++++++++++++++++++++
 lib/screens/loginScreen.dart           |  88 ++++++++++++++--
 lib/theme/dark.dart                    |  43 ++++++++
 lib/theme/light.dart                   |  40 ++++++++
 lib/todos                              |   1 +
 lib/widgets/addRide.dart               |  53 +++++++++-
 lib/widgets/circularProgress.dart      | 120 ++++++++++++++++++++++
 lib/widgets/distanceGraph.dart         |   8 --
 lib/widgets/formFieldWrapper.dart      |  39 +++++++
 lib/widgets/fuel/addFuel.dart          | 126 +++++++++++++++++++++++
 lib/widgets/fuel/fuelTable.dart        |  59 +++++++++++
 lib/widgets/fuel/lastFuel.dart         |  52 ++++++++++
 lib/widgets/history.dart               |  80 +++++++++++++++
 lib/widgets/monthlyGraph.dart          |  74 ++++++++++++++
 lib/widgets/parts/fuel.dart            |  37 +++++++
 lib/widgets/parts/lease.dart           | 118 ++++++++++++++++++++++
 lib/widgets/privacy/orDivider.dart     |  24 +++++
 lib/widgets/privacy/privacyDialog.dart |  73 ++++++++++++++
 lib/widgets/privacy/termsOfUse.dart    |  58 +++++++++++
 lib/widgets/settings.dart              |  37 +++++++
 lib/widgets/textField.dart             |  42 ++++++++
 lib/widgets/totalGraphBezier.dart      |  87 ++++++++++++++++
 pubspec.lock                           | 509 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 pubspec.yaml                           |  31 ++++--
 50 files changed, 3170 insertions(+), 106 deletions(-)
 create mode 100644 .flutter-plugins
 create mode 100644 .flutter-plugins-dependencies
 create mode 100644 .gitignore
 create mode 100644 .metadata
 create mode 100644 .packages
 create mode 100644 analysis_options.yaml
 create mode 100644 lease_log.iml
 create mode 100644 lib/extensions/date.dart
 delete mode 100644 lib/generated_plugin_registrant.dart
 create mode 100644 lib/models/log.dart
 delete mode 100644 lib/models/ride.dart
 create mode 100644 lib/models/tank.dart
 create mode 100644 lib/models/user.dart
 create mode 100644 lib/providers/circularData.dart
 create mode 100644 lib/providers/data.dart
 create mode 100644 lib/providers/fuel.dart
 create mode 100644 lib/providers/initialSetup.dart
 create mode 100644 lib/providers/lease.dart
 create mode 100644 lib/providers/monthlyChart.dart
 create mode 100644 lib/providers/theme.dart
 create mode 100644 lib/providers/totalChartB.dart
 create mode 100644 lib/providers/user.dart
 create mode 100644 lib/screens/data.dart
 create mode 100644 lib/screens/initialSetup.dart
 create mode 100644 lib/theme/dark.dart
 create mode 100644 lib/theme/light.dart
 create mode 100644 lib/todos
 create mode 100644 lib/widgets/circularProgress.dart
mahesh@Maheshs-MacBook-Air-M1 black-screen-test % flutter build apk 

💪 Building with sound null safety 💪

Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:bezier_chart

For solutions, see https://dart.dev/go/unsound-null-safety


FAILURE: Build failed with an exception.

* Where:
Script '/Users/mahesh/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/mahesh/Documents/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s
Running Gradle task 'assembleRelease'...                           53.8s
Gradle task assembleRelease failed with exit code 1
mahesh@Maheshs-MacBook-Air-M1 black-screen-test % 
```
</details>

Please make the final changes and make sure the app runs.

Thanks.

**Comment by vanth0me** [comment] 2021-11-11 10:56
I'm sorry, should have mentioned that building is with the no null sound safety option, because of the package. I'm pretty sure the last time it happend on an emulator it was an Android 12 x86_64 (Google APIs) based on a Pixel 5.

**Comment by maheshmnj** [comment] 2021-11-11 12:04
@vanth0me I ran your app and it did not go past the login screen because of the Google sign-in error (probably due to missing app signature) I kept it in the background for around 15-20 mins did not see the black screen when switching back to app.
.

**Comment by vanth0me** [comment] 2021-11-11 12:08
That's why it's kind of hard to tell what exactly triggers it. I guess you could download the play store version to observe the behavior, but I don't know if you can get anything useful out of that.

Thanks for looking into it, best to just open the app sometimes and do other stuff. Emulator is even harder I feel. If you have an android phone I'm sure you can recreate it as well, I don't think the brand really matters.

**Comment by maheshmnj** [comment] 2021-11-11 12:45
@vanth0me for this issue to be actionable and investigate further we would need a minimal reproducible project that is public so that the other team members could take a look at it, Is it possible for you to remove the confidential part from your code and also remove the unnecessary part (that may not help to reproduce the issue) and make the repository public?

**Comment by vanth0me** [comment] 2021-11-11 12:54
@maheshmnj I don't really mind, but I don't know what parts cause it and what not, so I can't help you with that. Also I don't think uploading the keystore is a safe idea, so how should I let you guys log in?

**Comment by maheshmnj** [comment] 2021-11-11 13:02
> Also I don't think uploading the keystore is a safe idea, so how should I let you guys log in?

Can't we skip the login part? If login is necessary may be you can hardcode the required info, And before you share the app please ensure the issue reproduces with the shared code sample.

**Comment by vanth0me** [comment] 2021-11-11 13:26
I'll check if only the login screen triggers it. I do feel that the app has to have more data in it for it to happen faster.

**Comment by vanth0me** [comment] 2021-11-12 08:43
I'll have to check sunday if I have the time to generate a second key or something. Triggering it from the login screen seems almost impossible.

**Comment by liwangyong** [comment] 2021-11-12 10:14
> @liwangyong @zhangruiyu你们能分享一个可重现的步骤以及`flutter doctor -v`相关日志的输出吗？

![image](https://user-images.githubusercontent.com/50942378/141450398-bdf37024-8b74-40ba-9997-72351eb6f529.png)

**Comment by liwangyong** [comment] 2021-11-12 10:17
> > @liwangyong  @zhangruiyu你们能分享一个可再现的步骤以及`flutter doctor -v`相关日志的吗？
> 
> ![图片](https://user-images.githubusercontent.com/50942378/141450398-bdf37024-8b74-40ba-9997-72351eb6f529.png)

I also have this problem in version 1.22

**Comment by liwangyong** [comment] 2021-11-12 10:18
> @maheshmnj我修复了它，由于某种原因，它看起来像是一个非常早期的版本。步骤是打开应用程序，我不知道登录是否有帮助，然后只需切换到另一个应用程序，等待一段时间并希望它会出现黑屏。困难在于在过早打开和应用程序被杀死之间找到平衡。遗憾的是不能保证它会发生。

How to fix it

**Comment by liwangyong** [comment] 2021-11-12 10:19
> @maheshmnj I fixed it, looked like it was a really early version for some reason. The steps are open the app, I don't know if logging in helps but then just switch to another app, wait some time and hope it gives a black screen. The difficulty is finding the balance between opening too soon and the app being killed. There is sadly no guarantee it will happen.

How to fix it

**Comment by maheshmnj** [comment] 2021-11-12 10:26
@liwangyong  I haven't been able to reproduce the issue yet, It would be great if you could provide a code sample with reproducible steps.

**Comment by liwangyong** [comment] 2021-11-13 10:52
> @liwangyong I haven't been able to reproduce the issue yet, It would be great if you could provide a code sample with reproducible steps.

My current project has a volume of 34m. When it stands in the background for a few minutes and then cuts back, the screen will be black

**Comment by liwangyong** [comment] 2021-11-13 10:55
> you

I don't think it has anything to do with the project code

**Comment by liwangyong** [comment] 2021-11-13 10:55
> @liwangyong I haven't been able to reproduce the issue yet, It would be great if you could provide a code sample with reproducible steps.

I don't think it has anything to do with the project code

**Comment by liwangyong** [comment] 2021-11-13 10:56
> @liwangyong I haven't been able to reproduce the issue yet, It would be great if you could provide a code sample with reproducible steps.

flutter 1.22 and flutter 2.5.3 both have problems

**Comment by vanth0me** [comment] 2021-11-13 13:20
Yeah I also have a feeling that it happens when more is loaded in. Maybe a larger tree or memory usage. That's why I think providing just code is kinda hard.

**Comment by liwangyong** [comment] 2021-11-15 02:01
> > @liwangyong I haven't been able to reproduce the issue yet, It would be great if you could provide a code sample with reproducible steps.
> 
> My current project has a volume of 34m. When it stands in the background for a few minutes and then cuts back, the screen will be black

Although the package size of my project is 34m, the cache used by my app reaches about 100m

**Comment by liwangyong** [comment] 2021-11-15 02:02
> > > @liwangyong I haven't been able to reproduce the issue yet, It would be great if you could provide a code sample with reproducible steps.
> > 
> > 
> > My current project has a volume of 34m. When it stands in the background for a few minutes and then cuts back, the screen will be black
> 
> Although the package size of my project is 34m, the cache used by my app reaches about 100m

And cut the black screen once, and then cut it again to restore the original state

**Comment by maheshmnj** [comment] 2021-11-15 05:10
@liwangyong @vanth0me can you guys please try cloning the [flutter gallery](https://github.com/flutter/gallery) app?  I believe it is considerably large enough and see if the issue can be reproduced with it?

**Comment by vanth0me** [comment] 2021-11-15 07:19
Great idea. I will try it starting today and will let you know if I was successful in generating a black screen.

**Comment by vanth0me** [comment] 2021-11-15 08:41
@maheshmnj Got it working after going to the shopping app, selecting a few items and locking the screen and keeping the app in the foreground. After about 5 minutes I opened my phone and saw a black screen. I created a video of it. (I'll add it with an edit)

**Comment by maheshmnj** [comment] 2021-11-15 13:26
Hi @vanth0me thanks for the confirmation, Unfortunately, I could not verify the issue [the gallery app fails to build on Android](https://github.com/flutter/gallery/issues/558), Labelling this issue for further investigation.

Thanks

**Comment by vanth0me** [comment] 2021-11-15 13:35
Thank you too. I hope you can provide me with more information soon, would be really nice if we can fix this together. If you need my help again, you can let me know.

**Comment by liwangyong** [comment] 2021-11-16 01:57
> Hi @vanth0me, thanks for the confirmation, Unfortunately, I could not verify the issue [the gallery app fails to build on Android](https://github.com/flutter/gallery/issues/558), Labelling this issue for further investigation from the team.
> 
> Thanks

Thank you too

**Comment by llgoer** [comment] 2021-11-21 12:37
same issues

**Comment by maheshmnj** [comment] 2021-11-23 06:26
Update: - I ran the flutter gallery app on Xiaomi k20 pro (Android 11) built on `stable 2.5.3` in debug mode 
- browsed the shrine app (added few items to cart)
- locked the screen with app still in foreground
- after 5-10 mins unlocked the screen and I could see a black screen for few seconds is this the same issue @vanth0me?

https://user-images.githubusercontent.com/31410839/142979365-5ede4573-3760-406e-93d2-21125549e9a8.mov

**Comment by vanth0me** [comment] 2021-11-23 07:44
@maheshmnj It does not seem like the same problem. From my experience the black screen does not disappear if you do nothing. I have not tried locking and unlocking to see if it disappears. In theory it could stay there for hours if you do not do anything with the phone.

**Comment by luojt** [comment] 2021-11-23 08:12
same issues.When I use Samsung S10 +, there is a certain probability that a black screen will appear when I switch back from the background. If I try again, it will be displayed normally.Do you use octo_ Image or cached_ network_ Image package? @vanth0me

**Comment by vanth0me** [comment] 2021-11-23 08:38
@luojt No I'm not using those packages, also cant find them in the pubspec.lock. For now I am convinced its some kind of render issue, since the app still works.

**Comment by luojt** [comment] 2021-11-23 09:01
@vanth0me @maheshmnj I wrote the smallest example code, which will produce a black screen, but it is difficult to reproduce. [Download this](https://github.com/luojt/hello)

**Comment by maheshmnj** [comment] 2021-11-23 11:49
Thanks, will check.

**Comment by maheshmnj** [comment] 2021-11-25 06:40
@luojt I can't really reproduce it on Xiaomi k20 pro Running (Android 11). 
- Ran your sample app moved the app to the background (app auto-locked in 30 seconds) for around 10 minutes 
- unlocked the phone switch to the app and it was running no black screen at all.

I wonder, How long did you keep the app in the background (The screenshot timings look in appropriate though), Anyways I have labeled this issue for further investigation from the team.

**Comment by luojt** [comment] 2021-11-29 05:17
@maheshmnj Thank you. At present, I reproduce the bug on Huawei and Samsung mobile phones. You can run it in the background and open other apps. After operating for a period of time (about 10-20 minutes), open the app for this test. There is a probability that the screen will be black. Try it again and again. The probability is high in the app I developed, and the recurrence probability of the app in this test is very low.

**Comment by chinmaygarde** [comment] 2021-12-06 18:54
cc @blasten

**Comment by davidmartos96** [comment] 2021-12-06 18:58
Could these two issues be related? https://github.com/flutter/flutter/issues/94094
I'm the OP of that issue and I sometimes get the black screen issue on a Flutter app with the same device that reproduces the other issue.

**Comment by blasten** [comment] 2021-12-06 21:47
Can you share the logcat?  e.g. `adb logcat -s FlutterSurfaceView > log.txt`

This can happen if the Flutter activity is destroyed. Also, in your device, can you check that you don't have this turn on? Developer options > Don't keep activities.  (Destroy activities as soon as user leaves it)

**Comment by vanth0me** [comment] 2021-12-07 09:17
@davidmartos96 As far as I know the app does keep running, and can also happen with no futures running at the time. So it is responsive.

**Comment by maheshmnj** [comment] 2021-12-07 12:47
Anyone who is able to reproduce the issue please share the requested info, inorder to investigate further.

>Can you share the logcat? e.g. adb logcat -s FlutterSurfaceView > log.txt then upload log.txt in your reply.

>This can happen if the Flutter activity is destroyed. Also, in your device, can you check that you don't have this turn on? Developer options > Don't keep activities. (Destroy activities as soon as user leaves it)

**Comment by xuelongqy** [comment] 2021-12-15 07:14
https://github.com/flutter/flutter/issues/94921

**Comment by vanth0me** [comment] 2021-12-17 09:02
Sorry for the late response, it was a busy week!
I thought I'd try to the logcat thing, but I have a more difficult time recreating a black screen.  The app now runs the latest Flutter 2.8, but I'll keep trying for today.

**Comment by Moice** [comment] 2021-12-21 14:07
The same problem, the log has not been crawled, and the most found in Huawei mobile phones at present, please solve it

**Comment by Moice** [comment] 2021-12-22 01:41
> Anyone who is able to reproduce the issue please share the requested info, inorder to investigate further.
> 
> > Can you share the logcat? e.g. adb logcat -s FlutterSurfaceView > log.txt then upload log.txt in your reply.
> 
> > This can happen if the Flutter activity is destroyed. Also, in your device, can you check that you don't have this turn on? Developer options > Don't keep activities. (Destroy activities as soon as user leaves it)



At present, the probability of occurrence is relatively high. Set the lock screen password on the mobile phone, then run the program in the background, then lock the screen and place it for 5 minutes, then turn off the lock screen password in the setting, enter the no password state, and then enter the mobile phone operation state. Then hot start the open program and repeat it for 10 times to reproduce the black screen

**Comment by RaymondBakker** [comment] 2021-12-31 11:05
I have found you don't necessarily have to wait any amount of time. I can reproduce this about 35% of the time on a OnePlus Nord device with the following steps:

1. Run -> Flutter run 'main.dart' in release mode
2. Wait for phone to show app
3. Turn off display by pressing power button once
4. Tap to wake for fingerprint scanner
5. Scan fingerprint to unlock
6. About 35% of the time the screen will stay black
7. If there is no black screen go back to step 1.

The app stays interactive during the black screen because I can see log lines coming through. You can press Android's Overview button and navigate back to the app to get rid of the black screen. Rotating the device to landscape forcing orientation changes also fixes it. (Basically anything triggering Android's onResume)

**Comment by Stage18** [comment] 2022-01-05 11:08
Same question

**Comment by ChenJinCan** [comment] 2022-01-10 01:31
Huawei Mate20 Pro, I have encountered this problem many times

**Comment by ColdPaleLight** [comment] 2022-01-12 00:57
Can you guys try this and see if this issue can be avoided: 
```
void main() {
  // Put this on the first line of main
  PaintingBinding.shaderWarmUp = null; 
  ......
}
```

**Comment by RaymondBakker** [comment] 2022-01-12 08:17
@ColdPaleLight This does not fix it for me.

**Comment by ColdPaleLight** [comment] 2022-01-12 08:25
> @ColdPaleLight This does not fix it for me.

According to your description, what you encountered looks like should be the same as https://github.com/flutter/flutter/issues/94921

**Comment by RaymondBakker** [comment] 2022-01-12 08:46
> > @ColdPaleLight This does not fix it for me.
> 
> According to your description, what you encountered looks like should be the same as #94921

You may be right. I believe this issue and #94921 are identical and that there is no direct connection to waiting any amount of time like people are suggesting here.

People in this issue are connecting the black screen to waiting an amount of time but I think this is just because they only start noticing the black screen once their phone goes to sleep mode while they work on code meanwhile and then eventually wake their phones and see black screens.

**Comment by davidmartos96** [comment] 2022-01-12 08:52
> > > @ColdPaleLight This does not fix it for me.
> > 
> > According to your description, what you encountered looks like should be the same as #94921
> 
> You may be right. I believe this issue and #94921 are identical and that there is no direct connection to waiting any amount of time like people are suggesting here.
> 
> People in this issue are connecting the black screen to waiting an amount of time but I think this is just because they only start noticing the black screen once their phone goes to sleep mode while they work on code meanwhile and then eventually wake their phones and see black screens.

Yes, it's exactly the same I noticed with this other issue on my OnePlus https://github.com/flutter/flutter/issues/94094
I still believe they could be somewhat related. It would be useful to know if other people having the black screen issue also have the other one.
Have you tried if disabling Battery optimization from the app settings "solves" the black screen issue?

**Comment by RaymondBakker** [comment] 2022-01-12 09:05
@davidmartos96 Disabling Battery optimization doesn't resolve this. Also tried the didChangeAppLifecycleState fix from #94094 and this does also not resolve this.

**Comment by vanth0me** [comment] 2022-01-12 12:28
> > > @ColdPaleLight This does not fix it for me.
> > 
> > 
> > According to your description, what you encountered looks like should be the same as #94921
> 
> You may be right. I believe this issue and #94921 are identical and that there is no direct connection to waiting any amount of time like people are suggesting here.
> 
> People in this issue are connecting the black screen to waiting an amount of time but I think this is just because they only start noticing the black screen once their phone goes to sleep mode while they work on code meanwhile and then eventually wake their phones and see black screens.
> 
> The problem is that OP #94921 is linking this issue to debug scene, which is probably also not a correct observation.

Hmm interesting, maybe the app does something self to mimic this behavior. I can also reproduce this issue with launching a release app on my phone, locking the screen and unlocking it. Guaranteed black screen. Nice find from #94921 OP

**Comment by dnfield** [comment] 2022-01-12 17:52
I added some comments about what I think is going on here: https://github.com/flutter/engine/pull/30590/files#r783307849

I unfortunately have not been able to reproduce this locally but it should be fixable.

**Comment by RaymondBakker** [comment] 2022-01-12 18:02
@dnfield Have you tried to reproduce this with the steps I posted at https://github.com/flutter/flutter/issues/93276#issuecomment-1003346244? Judging by other responses, it seems easy to reproduce this way.

**Comment by vanth0me** [comment] 2022-01-13 07:50
> @dnfield Have you tried to reproduce this with the steps I posted at [#93276 (comment)](https://github.com/flutter/flutter/issues/93276#issuecomment-1003346244)? Judging by other responses, it seems easy to reproduce this way.

Trying your method with an installed app didn't create any black screens if the app is idle. It is however very ease to do during boot if the app is changing screens.

**Comment by dnfield** [comment] 2022-01-13 18:32
https://github.com/flutter/engine/pull/30590 has landed as fab19829949dba28eaea411bf5f12e98f91f5e9a.

Once that's finished on CI, you might be able to just update your `bin/internal/engine.version` and test this.

I found a OnePlus phone but still can't seem to reproduce this myself.

**Comment by dnfield** [comment] 2022-01-13 18:33
(It's still building on CI but should be done within the next hour)

**Comment by RaymondBakker** [comment] 2022-01-13 19:38
```
Flutter 2.9.0-1.0.pre.351 • channel master • https://github.com/flutter/flutter.git
Framework • revision 4fda08efa9 (19 minutes ago) • 2022-01-13 14:15:18 -0500
Engine • revision fab1982994
Tools • Dart 2.17.0 (build 2.17.0-10.0.dev) • DevTools 2.9.2

```
The black screen is still occurring for me.

**Comment by dnfield** [comment] 2022-01-13 19:43
What would help at this point is a reproduction that happens consistently, or at least that happens with higher frequency on a greater number of devices.

**Comment by ColdPaleLight** [comment] 2022-01-14 09:52
I was able to reproduce this Issue and I did some investigation on it.

Normally, after we open the flutter app and turn off the screen, `FlutterSurfaceView.surfaceCallback.surfaceDestroyed` will be called. And when we turn on the screen, `FlutterSurfaceView.surfaceCallback.surfaceCreated` and `FlutterSurfaceView.surfaceCallback.surfaceChanged` will be called.

But on my OnePlus phone, when I turn off the screen, first `FlutterSurfaceView.surfaceCallback.surfaceDestroyed` is called, and then `FlutterSurfaceView.surfaceCallback.surfaceCreated` and `FlutterSurfaceView.surfaceCallback.surfaceChanged` are also called. And when I turn on the screen, only `FlutterSurfaceView.surfaceCallback.surfaceChanged` is called.

**AFAICS, if `AndroidSurfaceGL::onscreen_surface_` has not been recreated after the screen is turned on, it will show a black screen.**, And the abnormal timing of the callback of the `SurfaceHolder.Callback` of the OnePlus phone caused it.

**Comment by dnfield** [comment] 2022-01-14 15:45
Sounds like we need to check if surface changed got called without a surface created and if so, insert creation.  This is almost certainly a vendor bug though.

**Comment by ColdPaleLight** [comment] 2022-01-14 15:53
> Sounds like we need to check if surface changed got called without a surface created and if so, insert creation. This is almost certainly a vendor bug though.

Here I have encountered two situations. The first is that only `surfaceChanged` is called after the screen is turned on. The second is that even `surfaceChanged` is not called after the screen is turned on (no method is called). The first case be solved by the solution you mentioned, but the second case is can not.

**Comment by dnfield** [comment] 2022-01-14 17:34
I see.

Is the `FlutterSurfaceView.init` getting called in the case where we never get any callbacks?

**Comment by dnfield** [comment] 2022-01-14 17:37
Another thing to look at: if we implemented https://developer.android.com/reference/android/view/SurfaceHolder.Callback2 instead, do we get `surfaceRedrawNeeded` calls even if there's no `surfaceCreated` call?

**Comment by ColdPaleLight** [comment] 2022-01-16 15:41
@dnfield @blasten 

According to the log, `surfaceCreated` is actually called, but not when the screen is turned on, it's called when the screen is turned off.

Usually, when the `Activity`/`Fragment` enters `onStop`, the window will be in an invisible state, and the view tree will not be updated. In theory `surfaceCreated` should not be called when the screen is turned off. But the one plus mobile phone can update the view tree when screen turned off. When I turned off the screen, I saw such a line of log.
```
2022-01-15 00:22:29.102 29257-29257/com.example.text_displayed_outside D/ActivityThread: override visible to true while stopped. name= ComponentInfo{com.example.text_displayed_outside/com.example.text_displayed_outside.MainActivity}
```
It seemed that the OnePlus phone forced the window in visible state  when the `Activity`/`Fragment` enters `onStop` , so the view tree could still be updated, and the `surfaceCreated` could also be called.

I found a way to fix this:
Set the visibility of FlutterSurfaceView to View.GONE when onStop, and set it to View.VISIBLE when onStart. It works well in my OnePlus phone. Here is the PR:
https://github.com/flutter/engine/pull/30897

Please let me know if you guys have any thoughts on this?

**Comment by vanth0me** [comment] 2022-01-16 16:50
> Sounds like we need to check if surface changed got called without a surface created and if so, insert creation.  This is almost certainly a vendor bug though.

I'd say not. Almost every major brand has issues with this. Xiaomi, Samsung, huawei, pixel, iPhones, and probably more.

**Comment by ColdPaleLight** [comment] 2022-01-17 02:56
@vanth0me @RaymondBakker @davidmartos96 
Can you guys try this and see if this issue can be avoided?
https://github.com/flutter/flutter/issues/94921#issuecomment-1014088312

**Comment by RaymondBakker** [comment] 2022-01-17 09:49
@ColdPaleLight The code that @AlexV525 posted at https://github.com/flutter/flutter/issues/94921#issuecomment-1014088312 fixes the issue for me. It also gets rid of the occasional black flickering when turning the screen back on.

**Comment by vanth0me** [comment] 2022-01-17 16:45
> @vanth0me @RaymondBakker @davidmartos96 Can you guys try this and see if this issue can be avoided? [#94921 (comment)](https://github.com/flutter/flutter/issues/94921#issuecomment-1014088312)

Did not fix it for me for the black screen bug when the app has been in de background. Was unable to reproduce the blacksreen launching the app and locking/unlocking the phone. Could also be me being unlucky, but who knows.

**Comment by dnfield** [comment] 2022-01-18 19:15
> > Sounds like we need to check if surface changed got called without a surface created and if so, insert creation.  This is almost certainly a vendor bug though.
> 
> I'd say not. Almost every major brand has issues with this. Xiaomi, Samsung, huawei, pixel, iPhones, and probably more.
> 

I have not been able to reproduce this on a Pixel (including two or three different Pixel phones I've tried).

If this bug exists on iPhone it is definitely a different bug in different code. We'd need a reproduction for that as well.

**Comment by vanth0me** [comment] 2022-01-19 10:57
> 

A lot of colleagues of mine use a Pixel and that's how know about the iPhone users as well. From what I have heard iPhone users usually get a black screen after a pop or push. I only had that a few times on Android. It's pretty random and requires the app was in the background for some time.

**Comment by dnfield** [comment] 2022-01-19 23:27
@vanth0me it would be helpful if you could provide a minimal reproduction that results in a black screen as you're discussing.

**Comment by vanth0me** [comment] 2022-01-20 08:16
@dnfield That's the hard part, it's random. It happens just the same as I have described earlier. Have an app with state (I also got it to work with the gallery example shine store app)(Having state makes it seem easier to trigger), put in in the background, wait some time and open the app. I really have not found anything else that creates it that has not been discussed here already.

**Closed** 2022-01-20 21:05 UTC
Labels: e: device-specific, platform-android, engine, passed first triage, P4

**Comment by ColdPaleLight** [comment] 2022-01-21 01:11
Hi, @vanth0me 
The patch has landed, you can try the latest master channel. If that still doesn't solve your problem, I suggest writing a new Issue :)
