### ISSUE TITLE
CMake Error when i build my app for linux.

### ISSUE THREAD

**Issue by nyakokitsu** [flutter/flutter#131555] opened 2023-07-29 17:12 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Init prj with Linux support
2. Add flame example
3. flutter build linux --release

### Expected results

Building linux exebutable

### Actual results

```
CMake Error at /usr/local/share/cmake-3.27/Modules/FindPkgConfig.cmake:607 (message):
Building Linux application...                                   
  A required package was not found
Call Stack (most recent call first):
  /usr/local/share/cmake-3.27/Modules/FindPkgConfig.cmake:82[9]([REDACTED]/actions/runs/[REDACTED]/job/[REDACTED]#step:7:10) (_pkg_check_modules_internal)
  flutter/CMakeLists.txt:25 (pkg_check_modules)
```

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

Flutter doctor says my linux development is enabled and all toolchains installed

</details>

**Comment by stuartmorgan** [comment] 2023-07-29 18:01
> flutter/CMakeLists.txt:25 (pkg_check_modules)

This line is the check for `gtk+-3.0`, so CMake is unable to locate the configuration for that library.

> Flutter doctor says my linux development is enabled and all toolchains installed

Please post the full output; `doctor` should be checking for the presence of `gtk+-3.0`.

**Comment by nyakokitsu** [comment] 2023-07-29 19:02
> > flutter/CMakeLists.txt:25 (pkg_check_modules)
> 
> This line is the check for `gtk+-3.0`, so CMake is unable to locate the configuration for that library.
> 
> > Flutter doctor says my linux development is enabled and all toolchains installed
> 
> Please post the full output; `doctor` should be checking for the presence of `gtk+-3.0`.

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.6, on Ubuntu 22.04.1 LTS 5.19.0-46-generic,
    locale ru_RU.UTF-8)
    ! Warning: `dart` on your path resolves to /usr/lib/dart/bin/dart, which is
      not inside your current Flutter SDK checkout at
      /home/nknodev/.fluttersdk/flutter. Consider adding
      /home/nknodev/.fluttersdk/flutter/bin to the front of your path.
[✗] Android toolchain - develop for Android devices
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.70.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```

**Comment by huycozy** [comment] 2023-07-31 11:34
@nyakokitsu Your flutter doctor output with GTK check is passed, maybe this is related to https://github.com/flutter/flutter/issues/115378. 

Can you check if gtk3 exists on your system?

```bash
pkg-config --modversion gtk+-3.0
```

**Comment by stuartmorgan** [comment] 2023-07-31 14:23
If you make a simple "hello world" style CMake project (without Flutter), and add `gtk+-3.0`, does it work? It seems like there may be an issue with your CMake installation, since you have the library but CMake can't find it.

**Comment by nyakokitsu** [comment] 2023-08-01 21:11
> If you make a simple "hello world" style CMake project (without Flutter), and add `gtk+-3.0`, does it work? It seems like there may be an issue with your CMake installation, since you have the library but CMake can't find it.

yes, its works

**Comment by stuartmorgan** [comment] 2023-08-02 00:24
Could you post the CMakeList.txt that you were able to successfully build using `gtk+-3.0`? If it had [these lines](https://github.com/flutter/flutter/blob/35213ceabd4d3f33e1d71dc8d4ce79f08b83c0f7/packages/flutter_tools/templates/app_shared/linux.tmpl/flutter/CMakeLists.txt#L24-L25) and worked, then it's very strange that they wouldn't work when driving the build via `flutter`.

**Comment by nyakokitsu** [comment] 2023-08-02 09:18
> Could you post the CMakeList.txt that you were able to successfully build using `gtk+-3.0`? If it had [these lines](https://github.com/flutter/flutter/blob/35213ceabd4d3f33e1d71dc8d4ce79f08b83c0f7/packages/flutter_tools/templates/app_shared/linux.tmpl/flutter/CMakeLists.txt#L24-L25) and worked, then it's very strange that they wouldn't work when driving the build via `flutter`.

```
project(hello-world C CXX)

# Set the minimum version of cmake required to build this project
cmake_minimum_required(VERSION 3.10)

# Use the package PkgConfig to detect GTK+ headers/library files
find_package(PkgConfig REQUIRED)
pkg_check_modules(GTK REQUIRED gtkmm-3.0)


add_executable(hello main.cpp)
target_link_libraries(hello PRIVATE ${GTKMM_LIBRARIES})


# Add other flags to the compiler
target_compile_definitions(hello PRIVATE ${GTKMM_CFLAGS_OTHER})


# Setup CMake to use GTK+, tell the compiler where to look for headers
# and to the linker where to look for libraries
target_include_directories(hello PRIVATE ${GTKMM_INCLUDE_DIRS})
target_link_directories(hello PRIVATE ${GTKMM_LIBRARY_DIRS})

```

**Comment by stuartmorgan** [comment] 2023-08-02 10:45
> pkg_check_modules(GTK REQUIRED gtkmm-3.0)

This is a slightly different library; does it work if you use exactly the check linked in my comment above?

**Comment by nyakokitsu** [comment] 2023-08-02 11:53
> > pkg_check_modules(GTK REQUIRED gtkmm-3.0)
> 
> This is a slightly different library; does it work if you use exactly the check linked in my comment above?

Yes, I tried with your library and it works

**Comment by huycozy** [comment] 2023-08-03 04:53
@nyakokitsu I also tried reproducing this issue on my side but the issue didn't appear. I wonder if the issue still appears without adding `flame` to the project?

**Comment by nyakokitsu** [comment] 2023-08-03 07:25
Yes, the problem disappears when I build the application without flame.

чт, 3 авг. 2023 г., 07:53 huycozy ***@***.***>:

**Comment by huycozy** [comment] 2023-08-04 04:12
Did you install Flutter manually or with `snapd`? Can you please provide the output of `flutter doctor -v` (with verbose)?

I'm asking this because I see there is an issue that might be related: https://github.com/flame-engine/flame/issues/1836 (see issue on https://github.com/bluefireteam/audioplayers/issues/1538 as well). In that case, `audioplayers_linux` package caused that issue by snap didn't use right CMake version, and it was fixed after OP install Flutter manually instead.

**Comment by huycozy** [comment] 2023-08-04 10:48
@nyakokitsu Thanks for your update. Unfortunately, since the issue is only reproduced by adding `flame`, I would suggest you file an issue at the [flame repository](https://github.com/flame-engine/flame) for better support there.

Once the issue is identified as caused by Flutter, please come back here with more information and I will re-open this for further investigation. Closing the issue from here.

**Closed by huycozy** 2023-08-04 10:48 UTC
Labels: in triage
