### ISSUE TITLE
Assets not needed when generating iOS Frameworks

### ISSUE THREAD

**Issue by isacjunior** [flutter/flutter#52435] opened 2020-03-11 19:28 UTC
When creating ios frameworks, `App.frameworks` includes all of the images sizes in `flutter_assets`, but iOS requires only `@1x` `@2x` and `@3x`. This increased the `App.framework` and final bundle.

**How to reproduce:** 

1. Create a project.
2. Create assets for all sizes: 
```
0.75x - Android
1.0x - iOS/Android
1.5x - Android
2.0x - iOS/Android
3.0x - iOS/Android
4.0x - Android
```
3. `flutter build ios-framework`
4. See the result in `build/framework/{Mode}/App.framework/flutter_assets/`

**Expected results:** 
In iOS, only the sizes mentioned above.

**Actual results:** 
All of sizes in `flutter_assets`

**Comment by jmagman** [comment] 2020-03-11 19:35
\cc @jonahwilliams @dnfield

**Comment by dnfield** [comment] 2020-03-11 20:13
Should we have some multioption or config file to determine this?  I imagine this could change with the release of some new iPhone or even iOS version.

**Comment by dnfield** [comment] 2020-03-11 20:14
Also a flutter app could still decide to use the 4x  or 1.5x assets even on iOS (e.g. by explicitly asking for it or by overriding the MediaQuery).

**Comment by jmagman** [comment] 2020-03-11 20:20
I don't mind that App.framework has them unused assets, but ideally it's structured to be app thinned on the end-user device?

**Comment by jonahwilliams** [comment] 2020-03-11 21:29
Duplicate of https://github.com/flutter/flutter/issues/8230 ?

**Comment by ElaineSchwner** [comment] 2020-03-12 13:19
Besides that when uploaded for  App Store, it is not accepted, it says the 1024 icon for App Store can not be transparent. It always has to be replaced.

**Comment by jonahwilliams** [comment] 2020-05-01 03:58
I'm going to de-dupe this into #8230  , since the solution to both will be the same. Like Dan says, we cannot simple remove the assets as a flutter app may decide to use them

**Closed by jonahwilliams** 2020-05-01 03:58 UTC
Labels: a: assets, a: existing-apps, a: size, perf: app size, platform-ios, severe: performance, tool
