### ISSUE TITLE
[google_maps_flutter] Maps crashing on iOS (TabBarView and ClipRRect)

### ISSUE THREAD

**Issue by AndrsDev** [flutter/flutter#52818] opened 2020-03-18 14:13 UTC
## What is happening?
We have a TabBarView and a tab with a GoogleMap widget inside a ClipRRect. When you try to change tabs the application crashes. 

## Steps to Reproduce

1. Run `flutter create test_crash`.
2. Follow [getting started](https://pub.dev/packages/google_maps_flutter#getting-started) guide to setup google maps on IOS. 
3. In **lib/main.dart** delete all its contents and paste the following code:
```
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Google Maps Issue test Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with SingleTickerProviderStateMixin{
  Completer<GoogleMapController> _mapController = Completer();
  TabController _tabController;
  CameraPosition _selectedLocation;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(vsync: this, length: 2, initialIndex: 0);  
    _selectedLocation = CameraPosition(
      target: LatLng(37.42796133580664, -122.085749655962),
      zoom: 15,
    );
  }


  @override
  Widget build(BuildContext context) {

    return Scaffold(
      body: TabBarView(
        controller: _tabController,
        children: <Widget>[

          //Tab with a google map inside a ClipRRect widget
          Scaffold(
            appBar: AppBar(),
            body: Center(
              child: Container(
                margin: const EdgeInsets.all(24),
                height: 200,
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: GoogleMap(
                    initialCameraPosition: _selectedLocation,
                    onMapCreated: (GoogleMapController controller) {   
                      if(!_mapController.isCompleted)
                        _mapController.complete(controller);       
                    },
                  ),
                ),
              ),
            ),
          ),

          //Second tab to test
          Scaffold(
            appBar: AppBar(),
            body: Center(child: Text('Second tab')),
          ),

        ],
      ),
    );
  }
}

```
4. Run the app with `flutter run`
5. Finally just swipe left to change tabs.

**Expected results:** Change tabs

**Actual results:** The application crashes.

<details>
  <summary>Logs</summary>

flutter run --verbose
```
[+12617 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device
(file:///Users/andressanabria/Library/Developer/CoreSimulator/Devices/AC83C8EE-7EA6-4C18-ACA7-E1402F08CFCE/data/Containers/Data/Application/6B7969F1-70A
D-4C6B-88B9-2C717C2FBD8F/tmp/issue_testSVbLwE/issue_test/)
[        ] Sending to VM service: _deleteDevFS({fsName: issue_test})
[ +253 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] "flutter run" took 46,666ms.
```

flutter analyze
```
Analyzing issue_test...                                                 
No issues found! (ran in 2.2s)
```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/andressanabria/Development/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/andressanabria/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 Pro • AC83C8EE-7EA6-4C18-ACA7-E1402F08CFCE • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-03-18 14:36
Hi @AndrsDev 
I can reproduce it with stable, but not with latest master or dev. Seems to be fixed. Can you confirm?

**Comment by TahaTesser** [comment] 2020-04-09 08:59
Hi @AndrsDev 
As the [comment](https://github.com/flutter/flutter/issues/52818#issuecomment-600659335) above suggests that the issues doesn't reproduce `dev` and `master`. 
Closing it as fixed and no confirmation 
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-04-09 08:59 UTC
Labels: waiting for customer response
