### ISSUE TITLE
[web] Image Asset color not working

### ISSUE THREAD

**Issue by mkiisoft** [flutter/flutter#33316] opened 2019-05-24 19:20 UTC
Using ```import 'package:flutter_web/material.dart';``` on my first test using Flutter Web I had noticed this issue. Every time I touch the screen I want to change the color of the png file. On Android, iOS, Desktop works as expected but it doesn't on Web.

Example:

```
Image.asset(
              "{asset path png}",
              height: 200.0,
              fit: BoxFit.fill,
              color: tap ? Color(0x80FFFFFF) : null, // tap boolean value every time I touch the screen
            )
```

I gave it a try with Colors.white (for example) and also not working.

```
Flutter (Channel master, v1.6.2-pre.29, on Mac OS X 10.14.4 18E226, locale en-US)
```

**Comment by kenthinson** [comment] 2019-05-31 14:46
@mkiisoft I cant even get a image asset to display at all. For you it displays?

**Comment by mkiisoft** [comment] 2019-05-31 16:37
@kenthinson the image loads as expected without issues... changing the color of the image is the only thing that doesn't work. I did a "walk-around" by changing the opacity of the image but it will be better to have this working.

**Comment by dbacinski** [comment] 2019-06-03 14:58
The same issue here, I am not able to tint an image.

**Comment by robertonic** [comment] 2019-06-08 18:45
>> @mkiisoft I cant even get a image asset to display at all. For you it displays?

It must be in the folder web/assets   not  assets.

**Comment by Levi-Lesches** [comment] 2019-07-21 23:29
I am also having this problem. By extension it affects `ImageIcon` instances, which cannot honor the ambient `IconThemeData`. A practical concern here is the appBar leading icon. I did not want to have to bundle an entire icons font for a single back arrow, so I used my own `.png` and changed `MaterialApp.theme.appBarTheme.iconTheme.color` and my icon did not change.

**Comment by GAM3RG33K** [comment] 2019-12-03 07:01
I am also having a problem applying the color tint to my custom image asset. I am using these images as `icon` in `IconButton`. 

The Icon button created by the following code **does not change color when the theme changes**:
```dart
IconButton(
  icon: ImageIcon(Image.asset('images/view_list_custom.png').image,
            color: Theme.of(context).iconTheme.color,
          ),
  color: Theme.of(context).iconTheme.color,
)
```

However other icons buttons created with the following code **changes color with theme change**:
```dart
IconButton(
  icon: Icon(Icons.view_list),
)
```

As you can see I have also added color parameter for `ImageIcon` as well as the `IconButton`, still it does not work.

**Comment by KenAragorn** [comment] 2019-12-27 10:23
Hi, 

I having the same issue. However, as the image icon that I needed is already been provided by a third party library [https://pub.dev/packages/community_material_icon](https://pub.dev/packages/community_material_icon), so this resolve the issue. For those in needs, try to look for your icon is it available here such as github and other social icon that the default Flutter Icon doesn't have it. However, if you need to include your own icon, for the obvious reason, have to wait for the official bugs to be fix.

**Comment by ferraridamiano** [comment] 2020-01-30 11:08
Same issue here with the latest beta version (1.13.6)

**Comment by asjqkkkk** [comment] 2020-02-01 04:30
Same issue here with the latest beta version (1.14.6)

**Comment by asjqkkkk** [comment] 2020-02-01 04:30
Same issue here with the latest master version (1.14.6)

**Comment by h65wang** [comment] 2020-02-11 19:57
Same issue. The web version does not respect the `color` property of `Image` widgets. The mobile version from the same code base works well.

**Comment by ronytesler** [comment] 2020-02-15 20:10
Same for me.

**Comment by jonahwilliams** [comment] 2020-02-15 20:18
Please refrain from posting "+1", "Same", or other low effort comments on issues or pull requests, see the [repository guidelines](https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-to-or-same-comments-to-bugs). If you wish to express that the issue is important, it is preferable to use a reaction "+1" on the original issue instead of commenting to avoid creating extra noise for other contributors.

You may wish to read [when will my bug be fixed](https://github.com/flutter/flutter/wiki/Issue-hygiene#when-will-my-bug-be-fixed) for an explanation of how the issue tracker is used, and how to determine if work is scheduled.

**Comment by tapeo** [comment] 2020-02-27 11:50
Using `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true` the images are colored correctly. Maybe it can be useful.

**Comment by GAM3RG33K** [comment] 2020-02-27 14:18
if I remember it correctly, the above command does not support `--debug` flag yet. However, I'll try it out.

**Comment by NaikSoftware** [comment] 2020-03-31 16:24
> Using `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true` the images are colored correctly. Maybe it can be useful.

It works, but now I have issues with other widgets, for example text view has artifacts with ellipsize.

**Comment by IoanaAlexandru** [comment] 2020-04-12 16:09
Is there another workaround for this? `FLUTTER_WEB_USE_SKIA` doesn't work for me, text isn't rendering at all... (I have a custom font)

**Comment by anik786** [comment] 2020-04-15 15:41
Is there an update for this issue as it's quite severe and was reported a year ago. Therefore it affect other widgets such as `ImageIcon` and `AppBar`.

The only work-around seems to be using `FLUTTER_WEB_USE_SKIA`, but that also has some other issues such as remote images not showing up, and still being marked as experimental.

**Comment by JErazo7** [comment] 2020-05-06 18:59
Same problem, using Image Icon doesn't get the originals colors

**Comment by gskinner-shared** [comment] 2020-05-09 00:11
I think this was a dupe and has been fixed? https://github.com/flutter/flutter/issues/56071

**Comment by jsroest** [comment] 2020-05-12 08:52
@gskinner-shared I checked it and can confirm that the fix that landed in master, fixed this issue for me.

**Comment by ferraridamiano** [comment] 2020-06-21 08:02
> @gskinner-shared I checked it and can confirm that the fix that landed in master, fixed this issue for me.

I also tried yesterday with the latest beta version (1.19.0-4.1.pre) and it works fine!

**Comment by iapicca** [comment] 2020-07-03 10:29
Hi @mkiisoft 
the issue doesn't seems to occur with the latest master

<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  static const String _url =
      'https://flutter.dev/assets/flutter-lockup-c13da9c9303e26b8d5fc208d2a1fa20c1ef47eb021ecadf27046dea04c0cebf6.png';

  @override
  Widget build(BuildContext context) => Material(
        child: Center(
          child: Image.network(
            _url,
            color: Colors.orange,
          ),
        ),
      );
}
```


</details>


<details>
  <summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/86460243-b28ebc00-bd30-11ea-8286-cf93dfac4525.png)


</details>

<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-3.0.pre.126, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.126 at /Users/nevercode/development/flutter_master
    • Framework revision 462b0ea76e (14 hours ago), 2020-07-02 16:13:02 -0400
    • Engine revision 51ca1432b3
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 8afe9875a6)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max (mobile) • D6967F45-CB0F-4D4E-AFD5-278816A21CAE • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

I'm closing the issue as solved
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-03 10:29 UTC
Labels: P5, platform-web, severe: new feature

**Comment by goncalo-palma-3r** [comment] 2020-12-11 11:08
We are still finding this issue, specifically on Safari, iOS

`[✓] Flutter (Channel unknown, 1.24.0-7.0.pre, on Linux, locale en_US.UTF-8)`

**Comment by iapicca** [comment] 2020-12-11 13:02
@goncalo-palma-3r 
I can reproduce that

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      const MaterialApp(
        home: Material(
          child: Center(
            child: Image(
              image: NetworkImage(
                  'https://flutter.dev/assets/homepage/carousel/slide_1-bg-4e2fcef9a7343692a5f7784d68241a786c57c79d55f0fe37e6b82a653d146b93.jpg'),
              color: Colors.orange,
            ),
          ),
        ),
      ),
    );

```

</details>

<details>
<summary>logs</summary>

```bash 
[ +427 ms] Launching lib/main.dart on Chrome in debug mode...
[ +175 ms] Updating assets
[ +185 ms] Waiting for connection from debug service on Chrome...
[  +83 ms] Found plugin integration_test at /home/francesco/snap/flutter/common/flutter/packages/integration_test/
[  +72 ms] Found plugin integration_test at /home/francesco/snap/flutter/common/flutter/packages/integration_test/
[ +131 ms] <- reset
[  +11 ms] /home/francesco/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/francesco/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/
--incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata --output-dill /tmp/flutter_tools.VMPSMS/flutter_tool.YLAHND/app.dill --libraries-spec
file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json --packages /home/francesco/projects/issue/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.VMPSMS/flutter_tools.DCPKFJ --filesystem-scheme org-dartlang-app --initialize-from-dill
build/fbbe6a61fb7a1de317d381f8df4814e5.cache.dill.track.dill --platform file:///home/francesco/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +41 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+23542 ms] Waiting for connection from debug service on Chrome... (completed in 23.9s)
[        ] Synced 28.5MB.
[        ] <- accept
[        ] Caching compiled dill
[ +476 ms] Using Google Chrome 87.0.4280.88 

[+1110 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:35675/devtools/browser/ea32a57e-9d2b-4143-b572-b58a4c08f87e
[+2499 ms] DwdsInjector: Received request for entrypoint at http://localhost:43023/main_module.bootstrap.js
[   +5 ms] MetadataProvider: Loading debug metadata...
[  +11 ms] MetadataProvider: Loaded debug metadata
[  +12 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:43023/main_module.bootstrap.js
[+3400 ms] DevHandler: Debug service listening on ws://127.0.0.1:40853/YahjkJq5v_8=/ws

[   +9 ms] Debug service listening on ws://127.0.0.1:40853/YahjkJq5v_8=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
[+45235 ms] DevHandler: Stopped debug service on ws://127.0.0.1:34275

[ +376 ms] Application finished.
[   +4 ms] "flutter run" took 78,783ms.
[ +256 ms] ensureAnalyticsSent: 252ms
[   +4 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[ +133 ms] Shutdown hooks complete
[   +2 ms] exiting with code 0

```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.25.0-9.0.pre.24, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-9.0.pre.24 at /home/francesco/snap/flutter/common/flutter
    • Framework revision a1070e4f4c (6 hours ago), 2020-12-10 23:24:21 -0800
    • Engine revision 827aa5d073
    • Dart version 2.12.0 (build 2.12.0-135.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

• No issues found!

```

</details>

[screenshot](https://user-images.githubusercontent.com/45637986/101906407-93d70000-3bc1-11eb-8e9f-86dd184704bb.png)


tagging @TahaTesser  for visibility

**Comment by TahaTesser** [comment] 2020-12-11 16:09
@iapicca 
Using your code sample Safari on Mac and Safari on iOS
| Desktop | iOS |
| --------------- | --------------- |
<img width="320" alt="Screenshot 2020-12-11 at 9 22 26 PM" src="https://user-images.githubusercontent.com/48603081/101925309-ba179280-3bf7-11eb-9af9-1a9143171087.png"> | ![Image from iOS](https://user-images.githubusercontent.com/48603081/101925328-bedc4680-3bf7-11eb-86d8-070d66fcaaa3.png)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.25.0-9.0.pre.24, on macOS 11.0.1 20B29
    darwin-x64, locale en-GB)
    • Flutter version 1.25.0-9.0.pre.24 at /Users/tahatesser/Code/flutter_master
    • Framework revision a1070e4f4c (9 hours ago), 2020-12-10 23:24:21 -0800
    • Engine revision 827aa5d073
    • Dart version 2.12.0 (build 2.12.0-135.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS
      14.2
    • macOS (desktop)      • macos                     • darwin-x64     • macOS
      11.0.1 20B29 darwin-x64
    • Chrome (web)         • chrome                    • web-javascript • Google
      Chrome 87.0.4280.88

• No issues found!
```

</details>

Also tried setState color from https://github.com/flutter/flutter/issues/33316#issue-448319787
| Desktop  |  iOS |
| --------------- | --------------- |
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/48603081/101926453-3068c480-3bf9-11eb-8440-bdd033145aa5.gif) | ![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/48603081/101926520-48404880-3bf9-11eb-91d5-d6823416e67e.gif)



Is the color being assigned, not sure what the issue is

**Comment by Levi-Lesches** [comment] 2020-12-11 16:57
Guys the Flutter team already sort of fixed this with [ColorFiltered](https://www.youtube.com/watch?v=F7Cll22Dno8). They also acknowledge that this bug happens.

**Comment by esDotDev** [comment] 2020-12-11 17:10
Are you saying that we should just live `image.color` being ignored because ColorFiltered exists??

**Comment by h65wang** [comment] 2020-12-11 17:13
> @goncalo-palma-3r
> I can reproduce that
> 
> code sample
> logs
> doctor
> [screenshot](https://user-images.githubusercontent.com/45637986/101906407-93d70000-3bc1-11eb-8e9f-86dd184704bb.png)
> 
> tagging @TahaTesser for visibility

It seems to be working as intended in your screenshot. For a picture without transparent pixels, it will turn the whole picture into a color you specify, so in this case you get a big orange box. 

Not sure what you mean by "I can reproduce that".

@Levi-Lesches, this is not a "bug", it's intended. The default color blend mode is `SrcIn`, and a full orange picture is what you get when applying a color filter that way, you can try it in Photoshop. If the picture did NOT turn orange, and instead, turned out to be exactly identical to the original (as if no filter was applied at all), that would be the bug. You can try different blend mode in the `Image` widget too, for example: `colorBlendMode: BlendMode.softLight`.
