### ISSUE TITLE
How Can I Change TextField Toolbar Style?

### ISSUE THREAD

**Issue by mafanwei** [flutter/flutter#39387] opened 2019-08-28 08:35 UTC
here is my code. I simplified the code. This code in main.dart. TextField is in another dart file.
```
MaterialApp(
      theme: ThemeData(
        splashColor: Colors.transparent,
        highlightColor: Colors.transparent,
        primaryColorBrightness: Brightness.light,
        buttonTheme: ButtonThemeData(
          minWidth: 0,
          padding: EdgeInsets.all(0), // Notice this
          materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
          splashColor: Colors.transparent,
          highlightColor: Colors.transparent,
        ),home:SizedBox()
 )
```

```
TextField(
              style: CustomTextStyle.textField14TextStyle,
              keyboardType: widget.keyboardType,
              autocorrect: false,
              enableInteractiveSelection: true,
              decoration: InputDecoration(
                hintText: _getHintText(),
                hintStyle: CustomTextStyle.minorGray14TextStyle,
                enabledBorder: UnderlineInputBorder(
                  borderSide: BorderSide(color: widget.isError ? Color(0xffbb424a) : Color(0xff333333)),
                ),
                focusedBorder: UnderlineInputBorder(
                  borderSide: BorderSide(color: widget.isError ? Color(0xffbb424a) : CustomColor.obviousTextColor),
                ),
                contentPadding: EdgeInsets.symmetric(vertical: Global.isShortScreen ? 15 : 20),
              ),
              onSubmitted: (text) {
                if (widget.onSubmitted != null) {
                  widget.onSubmitted();
                }
              },
              controller: widget.controller,
              cursorColor: CustomColor.obviousTextColor,
            )
```

When I change the padding,the TextField Toolbar Padding will changed.I am a bit confused,how can I change it when theme unchanged. I find nothing helpful in TextStyle.
I notice that when I use `materialTapTargetSize: MaterialTapTargetSize.padded` it helpful to change Textfield Toolbar's padding, but I find nothing helpful to change it style such as background color,span color and etc.

I try to use something like `Material( child: Theme(data:ThemeData(),child:TextField())` but it doesn't work.

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/mafanwei/Downloads/flutter
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/mafanwei/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • EML AL00 • CLB0219517002332 • android-arm64 • Android 8.1.0 (API 27)
```

**Comment by mafanwei** [comment] 2019-09-23 10:16
Is this problem not considered in the design, or is it my own problem?

**Comment by TahaTesser** [comment] 2020-04-09 10:35
Hi @mafanwei 
Looks like this a a new feature request
Duplicate of [#22210](https://github.com/flutter/flutter/issues/22210)

Thank you

**Closed by TahaTesser** 2020-04-09 10:35 UTC
Labels: f: material design, framework

**Comment by mafanwei** [comment] 2020-04-09 11:12
Is it complete now?
If not, when will it be completed?
Thank you
