### ISSUE TITLE
Dart Analyzer Still crashes with ERR_STREAM_DESTROYED

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#62036] opened 2020-07-22 14:16 UTC
I've posted this here, on dart/dart. Is there any way I can solve this myself? I've been dealing with this for over 6 months now, and it just feels so awful to constantly have to rebuild the entire app every other hotload because dart analyzer crashes. 

```
[10:13:11 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.12.2\out\dist\extension.js:1:150996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.12.2\out\dist\extension.js:1:145499)
	at …
```

This even happens on the sample quickstart flutter project. I've caused this on multiple systems, reinstalled flutter/vscode to try and fix.

![wow](https://user-images.githubusercontent.com/10619135/88187814-ffb1cf80-cc04-11ea-955c-026524451f4d.gif)

**Comment by TahaTesser** [comment] 2020-07-23 09:01
duplicate of https://github.com/flutter/flutter/issues/53014

**Closed by TahaTesser** 2020-07-23 09:01 UTC
