### ISSUE TITLE
flutter doctor check throws `FormatException: Unexpected extension byte (at offset 5)`

### ISSUE THREAD

**Issue by michael-shields** [flutter/flutter#94478] opened 2021-12-01 17:43 UTC
After update Flutter is no longer supported in this version.  Flutter doctor reports [x] due to an error, the doctor check did not complete, FormatException: Unexpected extension byte (at offset 5), IntelliJ Version (2021.3 Ultimate Edition), flutter version 2.6.0-12.0.pre.871.

**Comment by meike02** [comment] 2021-12-01 18:31
Same problem...

**Comment by bernaferrari** [comment] 2021-12-01 19:08
Duplicate of https://github.com/flutter/flutter-intellij/issues/5872

**Comment by bernaferrari** [comment] 2021-12-01 23:08
Fixed.

**Comment by michael-shields** [comment] 2021-12-01 23:29
I’m a little confused?  What, where and how?  I don’t see a fix in IntelliJ and rebuilt the Flutter tool, after the build the Flutter doctor repots a crash still.  Can you elaborate on your ‘Fixed’ statement?  Regards.

**Comment by michael-shields** [comment] 2021-12-02 00:19
Yes, I just loaded the new Flutter PLUGIN and my Flutter has been re-established as it was.  Regards and thank you.

**Comment by meike02** [comment] 2021-12-02 03:27
thank you soooooooooooo much！！！！！！

**Comment by darshankawar** [comment] 2021-12-02 07:48
Closing this as fixed in dedicated plugin and per above comments.

**Comment by darshankawar** [comment] 2021-12-14 06:03
Reopening this, as this seems to be a Flutter tool issue and have received several reports on it:


/cc @christopherfujino

**Comment by danagbemava-nc** [comment] 2021-12-14 06:47
Duplicate of #94060

**Closed** 2021-12-14 06:49 UTC
Labels: severe: crash, tool, t: flutter doctor, passed first triage, d: intellij
