### ISSUE TITLE
Flutter: Execution failed for task ':package_info:verifyReleaseResources'

### ISSUE THREAD

**Issue by bobanminic96** [flutter/flutter#47669] opened 2019-12-23 11:40 UTC
Trying to build signed apk for android on windows. Have the same problem with debug. 
This is so strange, unable to move forward with development.

Previously, let's say 7 days ago, i created signed apk with compileSdkVersion 28 successfully, so it is already set on 28.

I tried to solve it with: #42310 #27226 #47337 but no success.

```bash
java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
[PATH]\flutter\mobile_client\build\package_info\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.
[PATH]\flutter\mobile_client\build\package_info\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found.

error: failed linking references.
```

Running -doctor says everything is fine.

---- UPDATE ----
Looks like, problem is with 'android_intent' package. Have any ideas ?

**Comment by srburton** [comment] 2019-12-23 12:10
Flutter really has this serious problem, unable to generate apk release. I'm facing the same problem .... this has been happening to a lot of people since last week ...

**Comment by iapicca** [comment] 2019-12-23 12:29
Hi @bobanminic96 
are none of the proposed solution working for you?

https://github.com/flutter/flutter/issues/42310#issuecomment-548531304
https://github.com/flutter/flutter/issues/42310#issuecomment-551445474
https://github.com/flutter/flutter/issues/47337#issuecomment-567145427

if so
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by bobanminic96** [comment] 2019-12-23 13:06
Hi @iapicca , thanks for feedback.

I'll provide you gradle. Thing is, that i just had to rebuild my app for play store release with new version code, so i did not change anything except version code. Last week i did it without any  problem and now after i upgraded flutter, there is an error which i can not resolve.

I did already set compileSdkVersion to 28. 

doctor -v:
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\src\Flutter\flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:/Users/Boban/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:/Users/Boban/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Boban\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

Ok, there is some red on: flutter run --verbose:

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/src/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by iapicca** [comment] 2019-12-24 14:16
Hi @bobanminic96 

> ...Thing is, that i just had to rebuild my app for play store release with new version code, so i did not change anything except version code. Last week i did it without any problem and now after i upgraded flutter, there is an error which i can not resolve.

could you please run 
`flutter clean`
`flutter pub cache repair`
let me know if the issue persists
thank you

**Comment by bobanminic96** [comment] 2019-12-24 14:50
I tried it many times in last almost 48hrs. Still stuck. I think i tried every solution i found on internet so far, but cant move forward.

Obviously debug works, but can create release build.

**Comment by bobanminic96** [comment] 2019-12-24 14:59
Here is gradle file:

`
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.liveweb.clientchatapp"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("********.jks")
            storePassword "********"
            keyAlias "********"
            keyPassword "********"
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            //signingConfig signingConfigs.debug
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
    implementation 'com.google.firebase:firebase-core:17.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'

}

// ADD THIS AT THE BOTTOM
apply plugin: 'com.google.gms.google-services'

`

**Comment by bravekingzhang** [comment] 2019-12-26 08:51
```java
Execution failed for task ':flutter_mmkv_cache:verifyReleaseResources'.
266
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
267
   > Android resource linking failed
268
     /Users/bkdevops/.gradle/caches/transforms-2/files-2.1/7faf2ad74a0b9932e38d86e684646e95/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
269
         
270
     /Users/bkdevops/.gradle/caches/transforms-2/files-2.1/7faf2ad74a0b9932e38d86e684646e95/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
```

@bobanminic96 same to you

**Comment by bobanminic96** [comment] 2019-12-26 10:00
> ```java
> Execution failed for task ':flutter_mmkv_cache:verifyReleaseResources'.
> 266
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> 267
>    > Android resource linking failed
> 268
>      /Users/bkdevops/.gradle/caches/transforms-2/files-2.1/7faf2ad74a0b9932e38d86e684646e95/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
> 269
>          
> 270
>      /Users/bkdevops/.gradle/caches/transforms-2/files-2.1/7faf2ad74a0b9932e38d86e684646e95/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
> ```
> 
> @bobanminic96 same to you

@bravekingzhang did u solved it ?

**Comment by srburton** [comment] 2019-12-26 13:37
@bobanminic96 #47798


run the `flutter build apk -v` command

and put the part that is giving error here ... I think it is the same as my case. dependencies on flutter-maintained packages that are experiencing this problem ...

**Comment by bobanminic96** [comment] 2019-12-26 14:54
Ok, here is the console error:

```console
[ +177 ms] FAILURE: Build failed with an exception.
[ +189 ms] * What went wrong:
[   +6 ms] Execution failed for task ':package_info:verifyReleaseResources'.
[  +58 ms] > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
[ +245 ms]   C:\Repo\revert_flutter\mobile_client\flutter\mobile_client\build\package_info\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.
[ +127 ms]   C:\Repo\revert_flutter\mobile_client\flutter\mobile_client\build\package_info\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found.
[  +29 ms]   error: failed linking references.
[  +97 ms] * Try:
[  +40 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +9 ms] * Get more help at https://help.gradle.org
[   +2 ms] BUILD FAILED in 3m 41s


```

part II

```console

 FAILURE: Build failed with an exception.

                     * What went wrong:
                     A problem occurred configuring root project 'android_intent'.
                     > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

                     * Try:
                     Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                     * Get more help at https://help.gradle.org

                     BUILD FAILED in 36s
[  +12 ms] Running Gradle task 'assembleAarRelease'... (completed in 38.8s)
[   +1 ms] Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
           
[   +2 ms] 
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           A problem occurred configuring root project 'android_intent'.
           > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 36s
           
[  +16 ms] "flutter apk" took 263,380ms.
The plugin android_intent could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:726:7)
#2      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#3      _rootRunBinary (dart:async/zone.dart:1146:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#8      Future._completeError (dart:async/future_impl.dart:532:5)
#9      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#10     buildGradleAar (package:flutter_tools/src/android/gradle.dart)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#12     _rootRunUnary (dart:async/zone.dart:1134:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#20     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#22     _rootRunUnary (dart:async/zone.dart:1134:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#28     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#29     _rootRunUnary (dart:async/zone.dart:1134:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#34     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#35     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by srburton** [comment] 2019-12-26 15:53
@bobanminic96 

The flutter is having serious issues with this ANDROID_HOME, I hope it's fixing before 2020. It was in the hotfix-5 update that it started to give these problems throughout the project ... it could be more careful when releasing an update that affects all.

I suggest you downgrade your version so you can build it, and wait for them to recognize the error and release an urgent fix.

```
 * What went wrong:
           A problem occurred configuring root project 'android_intent'.
           > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```

**Comment by bravekingzhang** [comment] 2019-12-27 03:06
@bobanminic96 

yes ,I have solved this problem

please see this issue https://github.com/adee42/flutter_keyboard_visibility/issues/42

**Comment by bobanminic96** [comment] 2019-12-27 10:25
> @bobanminic96
> 
> yes ,I have solved this problem
> 
> please see this issue [adee42/flutter_keyboard_visibility#42](https://github.com/adee42/flutter_keyboard_visibility/issues/42)

But it is already set on 28

```gradle

group 'io.flutter.plugins.androidintent'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    testOptions {
        unitTests.includeAndroidResources = true
    }
}

dependencies {
    compileOnly 'androidx.annotation:annotation:1.0.0'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:1.10.19'
    testImplementation 'androidx.test:core:1.0.0'
    testImplementation 'org.robolectric:robolectric:4.3'
}

// TODO(mklim): Remove this hack once androidx.lifecycle is included on stable. https://github.com/flutter/flutter/issues/42348
afterEvaluate {
    def containsEmbeddingDependencies = false
    for (def configuration : configurations.all) {
        for (def dependency : configuration.dependencies) {
            if (dependency.group == 'io.flutter' &&
                dependency.name.startsWith('flutter_embedding') &&
                dependency.isTransitive())
            {
                containsEmbeddingDependencies = true
                break
            }
        }
    }
    if (!containsEmbeddingDependencies) {
        android {
            dependencies {
                def lifecycle_version = "1.1.1"
                compileOnly "android.arch.lifecycle:runtime:$lifecycle_version"
                compileOnly "android.arch.lifecycle:common:$lifecycle_version"
                compileOnly "android.arch.lifecycle:common-java8:$lifecycle_version"
            }
        }
    }
}

```

**Comment by bobanminic96** [comment] 2019-12-27 12:11
@bravekingzhang 

Tried this: https://github.com/adee42/flutter_keyboard_visibility/issues/42#issuecomment-565158413

Tried this: https://github.com/adee42/flutter_keyboard_visibility/issues/42#issuecomment-566656630

with this: https://github.com/flutter/flutter/issues/46881#issuecomment-565055083

Did not move forward yet. Same issue all the time.

**Comment by srburton** [comment] 2019-12-27 19:36
@bobanminic96 did it work?

**Comment by bobanminic96** [comment] 2019-12-27 22:40
@srburton No, it isnt.

**Comment by bravekingzhang** [comment] 2019-12-29 03:05
@bobanminic96 maybe, my project is sample than yours, but I do think this is not a bug of flutter.
it's something about gradle version, mutil version of gradle .

**Comment by srburton** [comment] 2020-01-09 20:18
@bobanminic96 did it work?

**Comment by srburton** [comment] 2020-01-09 21:19
@bobanminic96 


1 You need to use this indacation with the latest version of... :)

1) In android/gradle/wrapper/gradle-wrapper.properties
Replace the line starting with distributionUrl by the latest gradle :

distributionUrl = https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

2) In android/build.gradle

you need to replace:

dependencies {
  classpath 'com.android.tools.build:**gradle:x.x.x**'
 }

with

dependencies { classpath 'com.android.tools.build:**gradle:3.5.0**' }

3) In android/gradle.properties paste this

android.enableJetifier=true 
android.useAndroidX=true

4) In android/app/build.gradle: make sure compileSdkVersion and targetSdkVersion are at least 28``

The most imrportant is here: In android/app/build.gradle: replace

testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

with

 testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"


replace

androidTestImplementation 'com.android.support.test:runner:x.x.x'
androidTestImplementation 'com.android.support.test.espresso:espresso-core:x.x.x'

with

androidTestImplementation androidx.test:runner:1.1.1
androidTestImplementation androidx.test.espresso:espresso-core:3.1.1

**Comment by iapicca** [comment] 2020-01-14 07:01
possibly related to https://github.com/flutter/flutter/issues/46881

**Comment by bobanminic96** [comment] 2020-01-14 09:34
> @bobanminic96
> 
> https://stackoverflow.com/questions/56494895/flutter-androidx-incompatibility-how-to-set-a-dependency-manually
> 
> 1 You need to use this indacation with the latest version of... :)
> 
> 1. In android/gradle/wrapper/gradle-wrapper.properties
>    Replace the line starting with distributionUrl by the latest gradle :
> 
> distributionUrl = https://services.gradle.org/distributions/gradle-5.4.1-all.zip
> 
> 1. In android/build.gradle
> 
> you need to replace:
> 
> dependencies {
> classpath 'com.android.tools.build:**gradle:x.x.x**'
> }
> 
> with
> 
> dependencies { classpath 'com.android.tools.build:**gradle:3.5.0**' }
> 
> 1. In android/gradle.properties paste this
> 
> android.enableJetifier=true
> android.useAndroidX=true
> 
> 1. In android/app/build.gradle: make sure compileSdkVersion and targetSdkVersion are at least 28``
> 
> The most imrportant is here: In android/app/build.gradle: replace
> 
> testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
> 
> with
> 
> testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
> 
> replace
> 
> androidTestImplementation 'com.android.support.test🏃x.x.x'
> androidTestImplementation 'com.android.support.test.espresso:espresso-core:x.x.x'
> 
> with
> 
> androidTestImplementation androidx.test🏃1.1.1
> androidTestImplementation androidx.test.espresso:espresso-core:3.1.1

@srburton I was on holiday so thats the reason why i did not reply so far.

I tried what u mention above, but it didnt work. This is my build,gradle file:

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.xxx.xxx"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file("*")
            storePassword "*"
            keyAlias "*"
            keyPassword "*"
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            //signingConfig signingConfigs.debug
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-core:16.0.8'
    //implementation 'com.android.support:appcompat-v7:28.0.0'
    //implementation 'com.android.support:support-v4:28.0.0'

}

// ADD THIS AT THE BOTTOM
apply plugin: 'com.google.gms.google-services'

**Comment by jonahwilliams** [comment] 2020-02-06 07:41
Duplicate of https://github.com/flutter/flutter/issues/46881

**Closed by jonahwilliams** 2020-02-06 07:41 UTC
Labels: customer: crowd, dependency: android, severe: crash, t: devtools, t: gradle, tool, ▣ platform-android
