### ISSUE TITLE
App not working properly after building it

### ISSUE THREAD

**Issue by hgpt185** [flutter/flutter#89105] opened 2021-08-28 14:27 UTC
![Screenshot_2021-08-25-18-13-33-423_com example to_do_list](https://user-images.githubusercontent.com/75779709/131221095-47212a4f-67b6-4381-b0ed-bd178807a52f.jpg)
![Screenshot_2021-08-25-18-14-38-176_com example to_do_list](https://user-images.githubusercontent.com/75779709/131221096-dd517c5b-8128-494b-b2f5-ea8edd3d51e9.jpg)

The first one is in debug mode and the second when i released the app.
In the second image the bottom sheet container is completely empty.
Can anyone help me out with this.

Flutter doctor.
![IMG_20210828_195604_568](https://user-images.githubusercontent.com/75779709/131221225-4e56ac4f-a004-45f9-8661-386c5d829e47.png)

**Comment by davidmartos96** [comment] 2021-08-29 13:49
That looks like an error that happened while creating the widget, that's why it gets built in grey.
You can get more information about what happened if you look at the logs in the console.
`flutter run --release` with your device connected

**Comment by darshankawar** [comment] 2021-08-30 07:58
@hgpt185 
See above comment and look at the logs and see if it helps to determine the cause.

**Comment by TahaTesser** [comment] 2021-09-23 11:46
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-23 11:46 UTC
