### ISSUE TITLE
Image picker crashed - invoke interface method 'void MethodChannel$Result.success(java.lang.Object)' on a null object

### ISSUE THREAD

**Issue by sleith** [flutter/flutter#26698] opened 2019-01-17 10:05 UTC
Hi,
I found my app crashed on some devices. It crashed on Image picker.
I'm using version 0.4.12.
Please find the crash log:

```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess(Unknown Source:2)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleCaptureImageResult(Unknown Source:17)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(Unknown Source:10)
       at io.flutter.app.FlutterPluginRegistry.onActivityResult(Unknown Source:18)
       at io.flutter.app.FlutterActivityDelegate.onActivityResult(Unknown Source:6)
       at io.flutter.app.FlutterActivity.onActivityResult(Unknown Source:2)
       at android.app.Activity.dispatchActivityResult(Activity.java:7454)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4375)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4424)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

My flutter doctor:
```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-ID)
    • Flutter version 1.0.0 at /Users/raymond.rulin/flutter
    • Framework revision 5391447fae (7 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/raymond.rulin/Library/Android/sdk
    • Android NDK at /Users/raymond.rulin/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.
[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
```
It crashed many times on many devices. Here's the devices report from fabric:
![screen shot 2019-01-17 at 17 04 01](https://user-images.githubusercontent.com/90533/51310825-14466200-1a7a-11e9-8e6a-efcbbb4724a8.png)

Thank you

**Comment by zgosalvez** [comment] 2019-01-17 10:12
I'm getting a `flutter: PlatformException(multiple_request, Cancelled by a second request, null)` error on the iOS simulator. Related?

**Comment by davidmartos96** [comment] 2019-01-17 11:13
Maybe this is related?
https://github.com/flutter/plugins/pull/1089

**Comment by wouterhardeman** [comment] 2019-01-17 12:18
I probably found the issue. So when the image_picker is called before another call is finished it should return an error with the MethodResult object that came the last method call. But instead it uses the MethodResult from the first method call. When finishing the first method call, the `pendingResult` variable will already be set to null.

Relevant code: https://github.com/flutter/plugins/blob/82bab678d76c69e56456f97879452eebd4ea66da/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerDelegate.java#L490

**Comment by sleith** [comment] 2019-01-18 03:10
Hi @cyanglaz , 
The crash happened on client's app (production) :)
I also tried to turn on 'don't keep activities', indeed it crashed with the same exact log.
So it means their activities was destroyed? this happened on 78 users which is quite weird.

Meanwhile I'm trying to contact the user to know more details.
Thank you :)

**Comment by wouterhardeman** [comment] 2019-01-19 16:32
I was able to reproduce this error. I will try to fix it and send a pull request over the weekend.

**Comment by cyanglaz** [comment] 2019-01-31 00:46
@wouterhardeman 
Could you share a detailed step to how to reproduce the issue? 

> I'm getting a `flutter: PlatformException(multiple_request, Cancelled by a second request, null)` error on the iOS simulator. Related?

Thank you for finding the issue on iOS.
It doesn't seems to be related. Could you please open another issue for iOS and include details to reproduce the issue?

**Comment by wouterhardeman** [comment] 2019-01-31 15:58
@cyanglaz 

1. Open the example in `image_picker`
2. Double click on any of the buttons
3. Select an image/video or take a picture/video (depending on which option you selected) or just go back.
4. The app will crash with the error mentioned in this issue.

**Comment by cyanglaz** [comment] 2019-01-31 17:16
> I'm getting a `flutter: PlatformException(multiple_request, Cancelled by a second request, null)` error on the iOS simulator. Related?

@zgosalvez 
Thank you for finding the issue on iOS.
It doesn't seems to be related. Could you please open another issue for iOS and include details to reproduce the issue?

**Comment by cyanglaz** [comment] 2019-01-31 17:30
This is a duplicate of https://github.com/flutter/flutter/issues/19819
Closing this issue now and please follow https://github.com/flutter/flutter/issues/19819 for fixing status.

**Closed by cyanglaz** 2019-01-31 17:30 UTC
Labels: p: first party, p: image_picker, plugin, severe: crash
