### ISSUE TITLE
Need a method in video player plugin to release previous resources held by it.

### ISSUE THREAD

**Issue by Kishan-Somaiya** [flutter/flutter#64693] opened 2020-08-27 07:08 UTC
Okay so i'm using Listview.builder to create a list of videos from an url but after loading 10-15 videos in the list it won't load videos at random. After searching on this for few days i got to know that video player isn't releasing codecs it held that's why new videos aren't loading. it would be great if we have a method in video_player so that we can release the resources held by it programatically. I have currently 25 videos in my list out of which only 13 is playing and remaining 12 doesn't load at all. Any help and suggestions are appreciated. below is the error i'm getting in terminal.  

`[I/OMXClient(21924):](url) IOmx service obtained
E/ACodec  (21924): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  (21924): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec(21924): Codec reported err 0xfffffff4, actionCode 0, while in state 1
W/MediaCodec-JNI(21924): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI(21924): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/MediaCodecRenderer(21924): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(21924): android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer(21924): 	at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer(21924): 	at android.media.MediaCodec.<init>(MediaCodec.java:1864)
W/MediaCodecRenderer(21924): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1842)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(21924): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/MediaCodecRenderer(21924): 	at android.os.Looper.loop(Looper.java:224)
W/MediaCodecRenderer(21924): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(21924): Playback error.
E/ExoPlayerImplInternal(21924): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(21924): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(21924): 	at android.os.Looper.loop(Looper.java:224)
E/ExoPlayerImplInternal(21924): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(21924): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(21924): 	... 9 more
E/ExoPlayerImplInternal(21924): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal(21924): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal(21924): 	at android.media.MediaCodec.<init>(MediaCodec.java:1864)
E/ExoPlayerImplInternal(21924): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1842)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(21924): 	... 10 more
E/flutter (21924): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1]), null)
I/OMXClient(21924): IOmx service obtained
E/ACodec  (21924): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  (21924): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec(21924): Codec reported err 0xfffffff4, actionCode 0, while in state 1
W/MediaCodec-JNI(21924): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI(21924): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/MediaCodecRenderer(21924): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(21924): android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer(21924): 	at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer(21924): 	at android.media.MediaCodec.<init>(MediaCodec.java:1864)
W/MediaCodecRenderer(21924): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1842)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(21924): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/MediaCodecRenderer(21924): 	at android.os.Looper.loop(Looper.java:224)
W/MediaCodecRenderer(21924): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(21924): Playback error.
E/ExoPlayerImplInternal(21924): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(21924): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(21924): 	at android.os.Looper.loop(Looper.java:224)
E/ExoPlayerImplInternal(21924): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(21924): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(21924): 	... 9 more
E/ExoPlayerImplInternal(21924): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal(21924): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal(21924): 	at android.media.MediaCodec.<init>(MediaCodec.java:1864)
E/ExoPlayerImplInternal(21924): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1842)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(21924): 	... 10 more
E/flutter (21924): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1]), null)
E/flutter (21924): 
I/OMXClient(21924): IOmx service obtained
E/ACodec  (21924): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  (21924): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec(21924): Codec reported err 0xfffffff4, actionCode 0, while in state 1
W/MediaCodec-JNI(21924): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI(21924): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/MediaCodecRenderer(21924): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(21924): android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer(21924): 	at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer(21924): 	at android.media.MediaCodec.<init>(MediaCodec.java:1864)
W/MediaCodecRenderer(21924): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1842)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(21924): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/MediaCodecRenderer(21924): 	at android.os.Looper.loop(Looper.java:224)
W/MediaCodecRenderer(21924): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(21924): Playback error.
E/ExoPlayerImplInternal(21924): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [852, 480, -1.0], [-1, -1])
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(21924): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(21924): 	at android.os.Looper.loop(Looper.java:224)
E/ExoPlayerImplInternal(21924): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(21924): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [852, 480, -1.0], [-1, -1])
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(21924): 	... 9 more
E/ExoPlayerImplInternal(21924): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal(21924): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal(21924): 	at android.media.MediaCodec.<init>(MediaCodec.java:1864)
E/ExoPlayerImplInternal(21924): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1842)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
E/ExoPlayerImplInternal(21924): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(21924): 	... 10 more
E/flutter (21924): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [852, 480, -1.0], [-1, -1]), null)
`

**Comment by pedromassangocode** [comment] 2020-08-27 08:35
Hi @Kishan-Somaiya 

Not sure if I understood you right but the [video_player](https://pub.dev/packages/video_player) plugin provides a controller that you can use to release resources used by the VideoPlayer object. Read more at https://pub.dev/documentation/video_player/latest/video_player/VideoPlayerController/dispose.html.

Closing as this does not seems to be a valid proposal. If you disagree please write in the comment bellow and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-27 08:35 UTC

**Comment by Kishan-Somaiya** [comment] 2020-08-27 12:03
i'm aware of the dispose method and i'm also using controller.dispose() method in dispose method but still i'm not able to play more than 12-13 videos in listview. it's giving me the above error. @pedromassangocode

**Comment by pedromassangocode** [comment] 2020-08-27 13:27
Hi @Kishan-Somaiya 
Please provide a minimal reproducible sample code that reproduces the issue.
Thank you

**Comment by Dhua-v** [comment] 2020-08-27 13:46
@pedromassangocode it feels strange, from 2 years, we are not able to use videos in flutter, but talk about advanced 2d animations.
Video works even in html.

**Comment by Kishan-Somaiya** [comment] 2020-08-27 13:49
yes and i've also seen other people also complaining these issue and it's still not resolved. flutter should resolve these issues first and then should move to web,desktop. @pedromassangocode

**Comment by pedromassangocode** [comment] 2020-08-28 06:22
Hi @Dhua-v @Kishan-Somaiya 
Flutter team is always focused on most important tasks. The issues are solved by the `thumbs up` on it so I would suggest you to share the most important issues with the community and ask people having the same issue to `thumbs up` the issue that is important to you, that way it will attract more attention from the Flutter team.
Thank you

**Comment by Dhua-v** [comment] 2020-08-28 06:43
People cant even believe that flutter cant play videos, thats why we don't get attention. 
Also, devs generally test in iphones, hence they cant see the issue untill they release. Thats what happened wid me.

Flutter team, pls take this one as an exception.

**Comment by Kishan-Somaiya** [comment] 2020-09-21 06:29
Hi @Dhua-v , I saw your comment in another post., thought it will be good if I post solution in my issue. My Solution is based on the following answer and it has worked for me, but it isn't a good solution. It's just a workaround and it's definitely not a good user experience, but we can't do anything else other than using a workaround, can we ? anyways let me know if you need any other help.

https://stackoverflow.com/a/58959097/14312868

**Comment by Dhua-v** [comment] 2020-09-22 01:12
Thanks very much . Really!!

**Comment by Kishan-Somaiya** [comment] 2020-09-22 11:56
@Dhua-v Did it worked for you as well ?

**Comment by Dhua-v** [comment] 2020-09-22 15:11
> @Dhua-v Did it worked for you as well ?

No bro, it didn't, there was a limit.

**Comment by RafaRuiz** [comment] 2021-04-08 22:53
I wouldn't say the `dispose` "workaround" is a solution, is a must!
