### ISSUE TITLE
[tool_crash] NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.Receiver: nullTried calling: assetPathsToEvict

### ISSUE THREAD

**Issue by shashank-gupta-shipsy** [flutter/flutter#102068] opened 2022-04-18 08:28 UTC
## Command
```
flutter run --flavor shipsy --dart-define=BUILD_MODE=dev
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'assetPathsToEvict' was called on null.
Receiver: null
Tried calling: assetPathsToEvict
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      HotRunner._resetDirtyAssets (package:flutter_tools/src/run_hot.dart:507:20)
#2      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:575:5)
<asynchronous suspension>
#3      HotRunner._fullRestartHelper (package:flutter_tools/src/run_hot.dart:751:16)
<asynchronous suspension>
#4      HotRunner.restart (package:flutter_tools/src/run_hot.dart:698:38)
<asynchronous suspension>
#5      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1619:40)
<asynchronous suspension>
#6      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1659:7)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.3.1 21E258 darwin-arm, locale en-IN)
    • Flutter version 2.5.3 at /Users/shashankgupta/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/shashankgupta/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.3.1, Build version 13E500a
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • Redmi Note 6 Pro (mobile) • 2d399ab0 • android-arm64  • Android 9 (API 28)
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 100.0.4896.88

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.2.10+41
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: db6e2d8aa5bb9a0bd3e75fc7470268b5a56fd0b0
### Plugins
background_fetch-1.0.3
battery-2.0.3
better_player-0.0.81
camera-0.9.4+18
camera_web-0.2.1+3
connectivity_plus-2.2.0
connectivity_plus_linux-1.2.0
connectivity_plus_macos-1.2.1
connectivity_plus_web-1.2.0
connectivity_plus_windows-1.2.0
firebase_analytics-8.3.3
firebase_analytics_web-0.3.0+1
firebase_core-1.7.0
firebase_core_web-1.6.0
firebase_crashlytics-2.2.2
flutter_barcode_scanner-2.0.0
flutter_local_notifications-9.4.0
flutter_native_image-0.0.6+1
flutter_plugin_android_lifecycle-2.0.5
geocoding-2.0.4
google_ml_kit-0.7.3
image_picker-0.8.4+11
image_picker_for_web-2.1.6
location-4.3.0
location_web-3.1.1
maps_launcher-2.0.1
open_file-3.2.1
package_info-2.0.2
package_info_plus-1.4.0
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.4
path_provider-2.0.9
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
permission_handler-8.3.0
sensors-2.0.3
share-2.0.4
shared_preferences-2.0.13
shared_preferences_android-2.0.10
shared_preferences_ios-2.0.9
shared_preferences_linux-2.1.0
shared_preferences_macos-2.0.3
shared_preferences_web-2.0.3
shared_preferences_windows-2.1.0
sqflite-2.0.2
store_redirect-2.0.1
url_launcher-6.0.20
url_launcher_android-6.0.14
url_launcher_ios-6.0.14
url_launcher_linux-3.0.0
url_launcher_macos-3.0.0
url_launcher_web-2.0.7
url_launcher_windows-3.0.0
video_player-2.2.17
video_player_web-2.0.7
video_thumbnail-0.4.6
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0

**Comment by danagbemava-nc** [comment] 2022-04-18 09:47
Duplicate of #89738

**Closed by danagbemava-nc** 2022-04-18 09:47 UTC
Labels: in triage
