### ISSUE TITLE
Colors.green looks different on Android and IOS

### ISSUE THREAD

**Issue by JohnnyGilMejia** [flutter/flutter#46552] opened 2019-12-08 22:37 UTC
I'm building an app and i just realized that Colors.green have a different tone on IOS and Android, it doesnt look the same kind of green

## Steps to Reproduce

Im just calling Colors.green on different parts of my screen and the green color looks different between IOS and Android emulator

https://gist.github.com/JohnnyGilMejia/0b5e043b5fbe529f2849b51c8baae4cb

<img width="1011" alt="Screen Shot 2019-12-08 at 5 53 47 PM" src="https://user-images.githubusercontent.com/19478273/70397514-41309a00-19e9-11ea-954e-cd6616c6cfad.png">

1. ... Im just calling Colors.green on different parts of my screen and the green color looks different on IOS and Android emulator (iphone 11 and Pixel 3)

**Target Platform: IOS/ANDROID
**Devices:** emulator

## Logs

```bash
[  +25 ms] executing: [/Users/johnnygilmejia/flutter/] git log -n 1 --pretty=format:%H
[  +33 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 68587a0916366e9512a78df22c44163d041dd5f3
[        ] executing: [/Users/johnnygilmejia/flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +6 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.6-0-g68587a091
[   +8 ms] executing: [/Users/johnnygilmejia/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/johnnygilmejia/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +51 ms] executing: [/Users/johnnygilmejia/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +374 ms] executing: /Users/johnnygilmejia/Library/Android/sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /Users/johnnygilmejia/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +17 ms] executing: /Users/johnnygilmejia/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +52 ms] /usr/bin/xcrun simctl list --json devices
[ +137 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +3 ms] /Users/johnnygilmejia/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +28 ms] ro.hardware = ranchu
[   +5 ms] Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
[        ] iPhone 11                 • 63A38C25-5FB0-4398-AA7B-BE22811EA2A2 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
[  +11 ms] "flutter run" took 648ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:281:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

## flutter doctor -v
```bash
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-DO)
    • Flutter version 1.9.1+hotfix.6 at /Users/johnnygilmejia/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/johnnygilmejia/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone 11                 • 63A38C25-5FB0-4398-AA7B-BE22811EA2A2 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!
```

**Comment by TheJulianJES** [comment] 2019-12-08 23:40
Couldn't this be also related to the iOS / Android Simulator?

**Comment by gmaggio** [comment] 2020-07-05 13:53
It's not just green, unfortunately. It's every color apart from gray scales.

**Comment by gaaclarke** [comment] 2020-10-12 18:00
I had this problem on previous projects I worked on.  I found that the saturation on the Android devices I was using was always higher than iOS devices.  Even if we got the simulator and the emulator looking the same they would look different on device since manufacturers have some control over saturation in their device and the color levels can also be adjusted on devices with operating system settings on both platforms.

There isn't any code in the framework or engine that is explicitly setting the colors different based on the platform.

**Comment by darshankawar** [comment] 2020-11-25 12:00
Issue replicable on latest stable version.

<img width="894" alt="Screenshot 2020-11-25 at 5 29 07 PM" src="https://user-images.githubusercontent.com/67046386/100225209-db178c80-2f43-11eb-81b0-f1c3b7cb8b7d.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (12 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (1 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm • Android 8.1.0 (API
      27)

• No issues found!


```

</details>

**Comment by SushantChandla** [comment] 2021-09-22 04:53
Any Updates? It happens on desktop also
` Color.fromRGBO(255, 132, 85, 1);`
![image](https://i.imgur.com/6dgHAnQ.png)

**Comment by dJani97** [comment] 2022-01-19 10:12
This is not a Flutter issue. Open the same image or website on both iOS Simulator and Android Emulator, and the colors will be different.

It seems to me that the colors in iOS Simulator are true to life, while the Android Emulator is oversaturated.

Running the Android Emulator on Windows has the correct colors though. I suppose this could be a MacOS-specific issue, probably caused by the difference between the colorspace used by the Android Emulator, and the Apple RGB colorspace.

**Comment by nicolasvahidzein** [comment] 2022-06-16 23:09
Came here to say that. Issues with Pink FF3586 looking perfect on android and dull on iOS.

**Comment by exaby73** [comment] 2023-02-08 11:40
This issue does not seem to be an issue with Flutter. While I can reproduce the color difference, taking a screenshot of the Android sample, and opening the image in iOS using photos, reproduces this color difference. This seems like just a difference with how Android and iOS processes colors and therefore, I am closing this issue

<details>
<summary>Screenshot</summary>

![46552](https://user-images.githubusercontent.com/50555895/217519894-d18d7bc4-7f75-4eff-b8c8-e0546d26c1e3.jpg)

</details>

**Closed by exaby73** 2023-02-08 11:40 UTC
Labels: engine, a: fidelity, a: quality, customer: crowd, severe: rendering, passed first triage, has reproducible steps, P4, found in release: 1.22
