### ISSUE TITLE
VMServiceFlutterDriver: request_data message is taking a long time to complete... stuck on 2.8.1 vs 2.5.3

### ISSUE THREAD

**Issue by krjw-eyev** [flutter/flutter#96172] opened 2022-01-05 10:31 UTC
We are using integration tests for our App (iOS and Windows) and we recently upgraded to 2.8.1 and the integration tests run fine on macOS and Windows but on our Windows Jenkins machine they do not complete. On 2.5.3 they worked.

They get stuck at `VMServiceFlutterDriver: request_data message is taking a long time to complete...`

`flutter drive -d windows --driver=test_driver/main.dart --target=integration_test/main.dart`

Any suggestions appreciated.

**Comment by maheshmnj** [comment] 2022-01-06 07:31
Hi @krjw-eyev, Thanks for filing the issue. This looks like a duplicate of https://github.com/flutter/flutter/issues/73355. Please follow up on the linked issue for further updates.
Closing this issue as a duplicate.

**Closed by maheshmnj** 2022-01-06 07:31 UTC
Labels: in triage

**Comment by krjw-eyev** [comment] 2022-01-08 10:11
That is where I [commented ](https://github.com/flutter/flutter/issues/73355#issuecomment-990118713)first and since I got no answer and the issue must have been introduced in 2.8.0 and the issue is a jear old, I thought filing a new one would be appropriate.
