### ISSUE TITLE
Long build times 30x after upgrade to Flutter 3.22.x with a lot of image assets

### ISSUE THREAD

**Issue by rokarnus** [flutter/flutter#151160] opened 2024-07-02 09:24 UTC
### Steps to reproduce

1.) Install Flutter 3.22.0 or later on Windows. I’m using 3.22.2
2.) Create a new Flutter project
3.) Add a lot of images to the assets folder. Can get 1000 test images here https://github.com/EliSchwartz/imagenet-sample-images
4.) Add assets folder in pubspec.yaml
5.) Run flutter app on Android device or emulator. To get the whole log as a file use “flutter -v run > build_log.txt”

In this test project impellerc goes from 0.6s to 24s build time. In our actual image editor projec with over 4000 sample images the impellerc build time goes from 3s to over 3 minutes.

**After upgrading from 3.19.5 to Flutter 3.22.2 our build times are 30x as long.**

### Expected results

This is part of the the build log from Flutter 3.19.5. impellerc.exe less than a second

`[        ] [ +607 ms] shaderc command: [C:\Users\Rok\Flutter SDK\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe, --runtime-stage-gles, --iplr, --sl=C:\Users\Rok\FlutterProjects\Test\test_build_time_02\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag, --spirv=C:\Users\Rok\FlutterProjects\Test\test_build_time_02\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag.spirv, --input=C:\Users\Rok\Flutter SDK\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag, --input-type=frag, --include=C:\Users\Rok\Flutter SDK\flutter\packages\flutter\lib\src\material\shaders, --include=C:\Users\Rok\Flutter SDK\flutter\bin\cache\artifacts\engine\windows-x64\shader_lib]`

### Actual results

This is part of the the build log from Flutter 3.22.2. impellerc.exe now takes 24 seconds

`[+24399 ms] [+24335 ms] shaderc command: [C:\Users\Rok\Flutter SDK\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe, --sksl, --runtime-stage-gles, --runtime-stage-vulkan, --iplr, --sl=C:\Users\Rok\FlutterProjects\Test\test_build_time_02\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag, --spirv=C:\Users\Rok\FlutterProjects\Test\test_build_time_02\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag.spirv, --input=C:\Users\Rok\Flutter SDK\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag, --input-type=frag, --include=C:\Users\Rok\Flutter SDK\flutter\packages\flutter\lib\src\material\shaders, --include=C:\Users\Rok\Flutter SDK\flutter\bin\cache\artifacts\engine\windows-x64\shader_lib]
`
### Code sample

<details open><summary>pubspec.yaml file</summary>

```yaml
name: test_build_time_02
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-SI)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.90.2)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2024-07-02 12:31
> Add assets folder in pubspec.yaml
> 5.) Run flutter app on Android device or emulator. To get the whole log as a file use “flutter -v run > build_log.txt”

@rokarnus Is the difference in build time occuring with impeller enabled or disabled in android ?
Also, are you trying to load the images or just having them in pubspec is showing added time ? If you are using the images, can you share code sample you are using ?

**Comment by rokarnus** [comment] 2024-07-02 13:08
@darshankawar 
Tried running the test app with “flutter -v run --enable-impeller > build_log_impeller.txt”
The build time is the same:

`[+22100 ms] [+22107 ms] shaderc command: [C:\Users\Rok\Flutter SDK\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe, --sksl, --runtime-stage-gles, --runtime-stage-vulkan, --iplr, --sl=C:\Users\Rok\FlutterProjects\Test\test_build_time_02\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag, --spirv=C:\Users\Rok\FlutterProjects\Test\test_build_time_02\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag.spirv, --input=C:\Users\Rok\Flutter SDK\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag, --input-type=frag, --include=C:\Users\Rok\Flutter SDK\flutter\packages\flutter\lib\src\material\shaders, --include=C:\Users\Rok\Flutter SDK\flutter\bin\cache\artifacts\engine\windows-x64\shader_lib]
`

This is just with having the images in pubspec.yaml. I have created a fresh "Hello world" project test_build_time_02 which doesn't even use images in the app. Our actual images are jpg and the test images from the sample above are also jpg.

**Comment by darshankawar** [comment] 2024-07-03 06:09
> This is just with having the images in pubspec.yaml.

Is there a way to know after how many images, do you start getting the increase in build time ? Randomly adding 1000 images at once in pubspec doesn't seem to be ideal.

**Comment by rokarnus** [comment] 2024-07-03 08:53
> > This is just with having the images in pubspec.yaml.
> 
> Is there a way to know after how many images, do you start getting the increase in build time ? Randomly adding 1000 images at once in pubspec doesn't seem to be ideal.

We are building an image editor "Meme Generator" app with a huge collection of funny images, stickers etc.  Our actual project has 4000+ images. We already have a successful Android Java app. Now we are making it cross platform with Flutter. 

I haven't tested what happens at 100, 200 or 500 images since it doesn't help our use case. In our actual app with with 4000+ images impellerc takes around 100 seconds. It's not linear growth, but it does increase the more image you add.

Has this something to do with added Android Vulkan support? Something must have changed in the Flutter 3.22 to cause this slowdown.

**Comment by darshankawar** [comment] 2024-07-04 05:29
Thanks for the update. Keeping the issue open and labeling for team's attention based on the reported behavior.

**Comment by andrewkolos** [comment] 2024-07-04 21:34
I was unable to repro.

My steps:
1. Checkout flutter 3.22.2 (commit hash 761747b)
2. Create a fresh flutter project (to avoid caching where we can): `flutter create -e build_time_test322`
3. Add the 1000 images provided in the issue comment to a folder in the project named `assets`
4. Include the `assets` directory in the `flutter:assets` section in pubspec.yaml:
```yaml
flutter:
  assets:
    - assets/
```
5. Run the app on an Android emulator `flutter run -d emu -v`
6. Repeat previous steps with  flutter 3.19.5 (commit hash 300451a)

Time for the app to open and display "hello world" on the emulator:
* 3.22.2: approximately 1 minute and 54 seconds ([log gist](https://gist.github.com/andrewkolos/2a56fe418d54474e9d6696cbc6d940ae))
* 3.19.5: approximately 1 minute and 45 seconds ([log gist](https://gist.github.com/andrewkolos/f6b0bfc2b175ff039746c5de3e52a0c1))

**Comment by rokarnus** [comment] 2024-07-05 09:01
> I was unable to repro.
> 
> My steps:
> 
> 1. Checkout flutter 3.22.2 (commit hash [761747b](https://github.com/flutter/flutter/commit/761747bfc538b5af34aa0d3fac380f1bc331ec49))
> 2. Create a fresh flutter project (to avoid caching where we can): `flutter create -e build_time_test322`
> 3. Add the 1000 images provided in the issue comment to a folder in the project named `assets`
> 4. Include the `assets` directory in the `flutter:assets` section in pubspec.yaml:
> 
> ```yaml
> flutter:
>   assets:
>     - assets/
> ```
> 
> 5. Run the app on an Android emulator `flutter run -d emu -v`
> 6. Repeat previous steps with  flutter 3.19.5 (commit hash [300451a](https://github.com/flutter/flutter/commit/300451adae589accbece3490f4396f10bdf15e6e))
> 
> Time for the app to open and display "hello world" on the emulator:
> 
> * 3.22.2: approximately 1 minute and 54 seconds ([log gist](https://gist.github.com/andrewkolos/2a56fe418d54474e9d6696cbc6d940ae))
> * 3.19.5: approximately 1 minute and 45 seconds ([log gist](https://gist.github.com/andrewkolos/f6b0bfc2b175ff039746c5de3e52a0c1))

@andrewkolos 
Looking at your logs, you have replicated the issue. The result seems less obvious since the whole (non cached) build takes over 1 min. When you run build again, for example to deploy the APK to Android device impellerc.exe is executed every time. This means it takes us 90 seconds every time we deploy na APK  with 4000+ images.

3.19.5 took you 1 second:
`[+1005 ms] [+1030 ms] shaderc command: [C:\Users\Jozz\Documents\GitHub\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe, --runtime-stage-gles, --iplr, --sl=C:\Users\Jozz\Desktop\deleteme\build_time_test319\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag, --spirv=C:\Users\Jozz\Desktop\deleteme\build_time_test319\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag.spirv, --input=C:\Users\Jozz\Documents\GitHub\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag, --input-type=frag, --include=C:\Users\Jozz\Documents\GitHub\flutter\packages\flutter\lib\src\material\shaders, --include=C:\Users\Jozz\Documents\GitHub\flutter\bin\cache\artifacts\engine\windows-x64\shader_lib]`

3.22.2 took you 28 seconds:
`[+28607 ms] [+28606 ms] shaderc command: [C:\Users\Jozz\Documents\GitHub\flutter\bin\cache\artifacts\engine\windows-x64\impellerc.exe, --sksl, --runtime-stage-gles, --runtime-stage-vulkan, --iplr, --sl=C:\Users\Jozz\Desktop\deleteme\build_time_test3222\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag, --spirv=C:\Users\Jozz\Desktop\deleteme\build_time_test3222\build\app\intermediates\flutter\debug\flutter_assets\shaders/ink_sparkle.frag.spirv, --input=C:\Users\Jozz\Documents\GitHub\flutter\packages\flutter\lib\src\material\shaders\ink_sparkle.frag, --input-type=frag, --include=C:\Users\Jozz\Documents\GitHub\flutter\packages\flutter\lib\src\material\shaders, --include=C:\Users\Jozz\Documents\GitHub\flutter\bin\cache\artifacts\engine\windows-x64\shader_lib]`

I have prepared another dataset with 5000 images. This will take impeller around 2 minutes. You can download it without being logged in to dropbox. You can also use any other set of 4000+ images:
https://www.dropbox.com/scl/fi/hhad117b168342duuogyl/skin_5000_images.zip?rlkey=0s7n9mp5e65kaox4yxsc6436y&dl=0

**Comment by andrewkolos** [comment] 2024-07-08 06:50
Indeed, it appears I was a bit hasty here. Thank you for digging into my logs for me. I reran the experiment with a much larger directory of assets (2500+ files, ~60Mb), and the disparity in build times was much more pronounced.

I'm guessing this has nothing to do with shader compilation (i.e. `impellerc`). The [print trace](https://github.com/flutter/flutter/blob/ac7879e2aa6de40afec1fe2af9730a8d55de3e06/packages/flutter_tools/lib/src/build_system/tools/shader_compiler.dart#L181) just happens to come after the asset bundle is built, and the previous print trace happens before the asset bundle is built, making it seem like `impellerc` took a long time.

Assigning myself to try to bisect the cause of this issue whenever I can find the time.

**Comment by andrewkolos** [comment] 2024-07-09 08:08
FYI that this appears to be reproducible using `flutter build appbundle`, which was more convenient for writing a script to bisect this. Interestingly, I couldn't reproduce this issue on my macOS machine, so I continued to use my personal Windows machine.

I think I've bisected this down to https://github.com/flutter/flutter/commit/1d304d38828a08f37f40c37a08f23e012b29c243, an engine roll that bumped the Dart SDK and Skia versions. This surprised me, as I was expecting this regression to be due to some change to asset bundling. Perhaps the assumptions from my previous comment were wrong. Keeping myself assigned to perform further investigation.

**Comment by jason-simmons** [comment] 2024-07-10 05:41
The regression in build time started with https://dart.googlesource.com/sdk/+/c2e9ceeb6b97329f75a84bd41e40b540dd40e7a4

The asset bundler is using Dart's file copy API to copy all of these image assets into an intermediate directory.

The Windows implementation of Dart's `File::Copy` copies the source file to a temporary file and then moves the temporary file to the final location.

That commit changed `CopyIntoTempFile` to concatenate the destination directory path and the random temporary file suffix:
```
swprintf(file_path.get(), file_path_buf_size, L"%s%x", dir.get(),
             suffix_bytes);
```
This places the temporary file in the parent directory of the destination directory.  So when `File::Copy` later moves the file, the `MoveFileW` call now needs to move the file across directories.  Apparently that takes significantly longer than renaming a file within its current directory.

The regression goes away if I patch the code above to insert a slash between the destination directory path and the suffix (matching the behavior prior to that commit).

@mraleph

**Comment by mraleph** [comment] 2024-07-10 07:12
FWIW this is already fixed by dart-lang/sdk@4928998ebe7d45ca27846af1e8cd4fd45cd475e3 upstream. 

I will request cherry pick into stable/beta branch - though I need to figure out where we are in the release process.

**Comment by mraleph** [comment] 2024-07-10 07:28
I have confirmed that it will be part of the next stable. I don't think there will be any more patch releases for the current stable - so there is not much we can do about it right now.

**Comment by andrewkolos** [comment] 2024-07-10 18:25
Thank you folks for the fantastic investigation.

I will be closing this since it should be resolved in `master` and the cutoff for the last 3.22 cherry pick has already passed.

**Closed by andrewkolos** 2024-07-10 18:25 UTC
Labels: platform-android, tool, a: assets, a: images, a: build, P2, team-tool, triaged-tool, fyi-windows

**Comment by rokarnus** [comment] 2024-07-10 20:18
Tnx to everyone involved. Appreciate the fast response and resolve.
