### ISSUE TITLE
Error (Xcode): Target debug_unpack_ios failed: Exception: Failed to codesign

### ISSUE THREAD

**Issue by kibu7** [flutter/flutter#152261] opened 2024-07-24 20:05 UTC
The folder is not in a cloud-synced directory

### Steps to reproduce

1. create a flutter application
2. choose iOS simulator
3. start debug

### Expected results

App should start in debug mode on iPhone

### Actual results

`Launching lib/main.dart on iPhone 15 Pro in debug mode...
Xcode build done.                                            5.3s
Failed to build iOS app
Error (Xcode): Target debug_unpack_ios failed: Exception: Failed to codesign /Users/user/Flutter/flutter_application_3/build/ios/Debug-iphonesimulator/Flutter.framework/Flutter with identity -.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.`

### Code sample

just the example application

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.22.3 on channel stable at /Users/user/Documents/development/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (8 days ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.91.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • iPhone 15 Pro (mobile)          • 2FA73B88-0A41-4877-A36C-B29EB3850349 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 126.0.6478.183

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment] 2024-07-25 08:47
Hi @kibu7, I believe this is a duplicate of https://github.com/flutter/flutter/issues/130639.  Kindly follow up in the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-07-25 08:47 UTC
Labels: in triage
