### ISSUE TITLE
SkParagraph doesn't account for `applyHeightToFirstAscent` `applyHeightToLastDescent` on empty paragraphs with strut enabled

### ISSUE THREAD

**Issue by LongCatIsLooong** [flutter/flutter#112123] opened 2022-09-21 22:45 UTC
## Steps to Reproduce

```dart
const style = TextStyle(height: 11, fontSize: 7);
const simple = TextSpan(text: 'x', style: style);
const emptyString = TextSpan(text: '', style: style);
const emptyParagraph = TextSpan(style: style);

final painter = TextPainter(
  textDirection: TextDirection.ltr,
  strutStyle: StrutStyle.fromTextStyle(style),
  textHeightBehavior: const TextHeightBehavior(applyHeightToFirstAscent: false, applyHeightToLastDescent: false),
);

for (final span in [simple, emptyString, emptyParagraph]) {
  painter.text = span;
  painter.layout();
  final realHeight = painter.height;
  final preferredHeight = painter.preferredLineHeight;
  print('${span.text} > real height: $realHeight, preferred height: $preferredHeight');
}
```
"real height" should always be the same as "preferred height" (8 px) in all 3 cases. However right now for both "emptyString" and "emptyParagraph" the reported "real height" is 77.0.

**Comment by jason-simmons** [comment] 2022-09-23 22:48
I tried the example in SkParagraph and the old Libtxt text layout library:

#### Libtxt
Text | painter.height | painter. preferredLineHeight | painter.size
:---: | :---: | :---: | :---:
simple | 77.0 | 77.0 | (4.0, 77.0)
emptyString | 77.0 | 77.0 | (0.0, 77.0)
emptyParagraph | 77.0 | 77.0 | (0.0, 77.0)

#### SkParagraph
Text | painter.height | painter. preferredLineHeight | painter.size
:---: | :---: | :---: | :---:
simple | 8.0 | 8.0 | (4.0, 8.0)
emptyString | 77.0 | 8.0 | (0.0, 77.0)
emptyParagraph | 77.0 | 8.0 | (0.0, 77.0)

I think that Libtxt's results are correct in this case.  SkParagraph does not appear to be applying the strut as intended.

The strut defines a minimum line height that applies to all lines in the paragraph (see https://api.flutter.dev/flutter/painting/StrutStyle-class.html).  But for some of these paragraphs SkParagraph is calculating height and preferredLineHeight that is less than the strut height.

SkParagraph does produce results similar to Libtxt if the app does not set the `TextHeightBehavior(applyHeightToFirstAscent: false, applyHeightToLastDescent: false)` parameter.  So it looks like SkParagraph is improperly allowing the `TextHeightBehavior` to override the strut height.

@Rusino

**Comment by jason-simmons** [comment] 2022-10-11 22:55
The fix has landed on the Flutter master branch
(see https://skia.googlesource.com/skia/+/d0ee294bc90fe676458b32417737ecae409a4c21)

**Closed by jason-simmons** 2022-10-11 22:55 UTC
Labels: a: text input, framework, f: material design, dependency: skia, a: typography
