### ISSUE TITLE
When use maxLength in TextField, my cursor has set custom color, but cursor color will be red

### ISSUE THREAD

**Issue by BonyYeah** [flutter/flutter#136236] opened 2023-10-10 04:15 UTC
<img width="296" alt="截屏2023-10-10 12 13 29" src="https://github.com/flutter/flutter/assets/40587706/02474d70-96a2-4235-b19b-9a4e4806a04c">
I had tried set autoCorrect :false and enableSuggestions: false, when I input text the cursor color is my custom color, but when I close keyboard and open again, the cursor color may be red.

**Comment by opxdelwin** [comment] 2023-10-10 06:38
Hi @BonyYeah ,
Please do attach a minimal reproducible code as it'd let us test the issue efficiently.

**Comment by BonyYeah** [comment] 2023-10-10 07:33
Hi @opxdelwin , Thanks for your reply, next code is the minimal reproducible, maybe the '-' and the length to 9 cause the cursor color be red,  but I don't need red cursor color to remind user, how can I do for it?
 TextField(
   controller: controller,
   focusNode: focusNode,
   keyboardType: TextInputType.number,
   autocorrect: false,
   maxLength: 8,
   cursorColor: Colors.yellow,
   inputFormatters: [
     FilteringTextInputFormatter.allow(RegExp("[0-9]")),
   ],
   onChanged: (value) {
     if (value.length > 4) {
       if (!value.contains("-")) {
         controller.text = value.substring(0, 4) + "-" + value.substring(4, value.length);
       }
     }
   },
 ),

**Comment by dam-ease** [comment] 2023-10-10 09:22
Hi @BonyYeah. Thanks for filing this issue. I can reproduce this on my end as well because the cursor is assigned the same colour as the error's when the input value is more than the maximum length specified. The issue relating to the cursor's colour changing relative to this is being tracked here https://github.com/flutter/flutter/issues/135580. Kindly upvote and follow up on this issue for updates.
Closing this in favour of the already open issue, if you disagree please comment and I'll reopen this.

**Closed by dam-ease** 2023-10-10 09:22 UTC
Labels: in triage

**Comment by BonyYeah** [comment] 2023-10-10 10:17
Hi @dam-ease , Thanks for your reply, it looks no way to solve this question directly?
