### ISSUE TITLE
Material Card containing InkWell does not properly clip corners

### ISSUE THREAD

**Issue by bryanoltman** [flutter/flutter#109776] opened 2022-08-18 14:57 UTC
## Steps to Reproduce

This can be seen on the example "This sample shows creation of a [Card](https://api.flutter.dev/flutter/material/Card-class.html) widget that can be tapped" on https://api.flutter.dev/flutter/material/Card-class.html.

Also:

1. Execute `flutter run` on the code sample 
2. Tap the card

**Expected results:** 
The InkWell's Ink has the same rounded corners as the Card

**Actual results:** 
The InkWell's ink does not have rounded corners:
![Simulator Screen Shot - iPhone 13 - 2022-08-18 at 10 55 46](https://user-images.githubusercontent.com/581764/185427052-63460d3d-2118-4ed9-a650-82ebcee3426e.png)

## Note
I understand that this issue is occurring because the Card has a border radius and the child InkWell does not. While a user can work around this by adding their own border radius with a hardcoded value that matches the Card's, this seems like it shouldn't be necessary – is there any case where someone would _want_ the child widget's UI to extend beyond the rounded corners of the Card? _Users should not have to use workarounds because the out-of-the-box behavior looks broken when we are completely in control of said out-of-the-box behavior_.

Ideally this change would be made in the Card (this would allow people to create better-looking UI with less code), but I know that there could be any number of reasons that making this change in Card isn't the right move (unforeseen performance problems, greatly increased complexity, etc. etc. etc.). If we can't make the change in Card, the documentation example should at least be updated to show an example that doesn't look broken. 

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TappableCardContainer(),
    );
  }
}

class TappableCardContainer extends StatelessWidget {
  const TappableCardContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Card(
          child: InkWell(
            onTap: () {},
            child: Padding(
              padding: EdgeInsets.all(20),
              child: Text('hello'),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

**Comment by ShimronAlakkal** [comment] 2022-08-18 15:56
Try using the `borderRadius` or the `customBorder` param in the InkWell like 
 ```dart
       InkWell(
            onTap: () {},
            borderRadius: BorderRadius.circular( <radius that fits, use MediaQuery to make it dynamic> ),
            child: Padding(
                  padding: EdgeInsets.all(20),
                  child: Text('hello'),
            ),
       ),
```

or 

```dart
     InkWell(
            onTap: () {},
           customBorder: CircularBorder(),
            child: Padding(
                  padding: EdgeInsets.all(20),
                  child: Text('hello'),
            ),
       ),
```

**Comment by bryanoltman** [comment] 2022-08-18 16:20
@ShimronAlakkal Neither of these are quite 100%, but my point was more that I either 1) shouldn't have to do this or 2) the example should be updated to reflect the Right way to do this.

**Comment by adilwahla** [comment] 2022-08-18 17:02
share code here plz

**Comment by bryanoltman** [comment] 2022-08-18 17:12
@adilwahla It's already there at the end of the [original post](https://github.com/flutter/flutter/issues/109776#issue-1343230882).

**Comment by adilwahla** [comment] 2022-08-18 17:18
I finally got this to work by specifying the same border radius in both the parent card widget and the child inkwell widget. The other solutions don't correctly render rounded corners for the ink well animation. The below worked perfectly for me:
```
Card(
    elevation: 2,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(8),
    ),
    child: InkWell(
      borderRadius: BorderRadius.circular(8),
      onTap: (){},
      child: Container(
        height: 58,
      ),
    ),
  );
```

**Comment by adilwahla** [comment] 2022-08-18 17:20
otherwise wrap inkwell into material like this
```
Card(
  margin: EdgeInsets.all(10.0),
  shape: RoundedRectangleBorder(
    borderRadius: BorderRadius.circular(10.0),
  ),
  child: Material(
    child: InkWell(
      splashColor: Colors.orange,
      onTap: (){
        print('Tapped!');
      },
      child: Container(
        // My design code here
      )
     ),
    ),
  ),
        
```

**Comment by adilwahla** [comment] 2022-08-18 17:23
@bryanoltman feel free to reach me out if still getting problem 
hope so this closes #109776

**Comment by bryanoltman** [comment] 2022-08-18 17:29
It doesn't, unfortunately – the issue isn't that it _can't_ be done, it's that the solution is non-obvious and not documented, and that the relevant example doesn't demonstrate the behavior that developers probably want. Hardcoding the radius values is also brittle – what if the Card's border radius changes in a future version of Material?

**Comment by adilwahla** [comment] 2022-08-18 17:48
In my opinion you should close it and reopen issue with better explanation. By all means this stated issue doesn't seems relevant to your actual idea So, be specific to explain 
Thanks  

> It doesn't, unfortunately – the issue isn't that it _can't_ be done, it's that the solution is non-obvious and not documented, and that the relevant example doesn't demonstrate the behavior that developers probably want. Hardcoding the radius values is also brittle – what if the Card's border radius changes in a future version of Material?

**Comment by bryanoltman** [comment] 2022-08-18 18:43
I appreciate your input, but respectfully disagree. The issue focuses on the problem (the default/documented way of doing something yields surprising/unexpected results), and whether the solution is to update the docs or to make a change to the Card class is up to whoever resolves this issue.

**Comment by ShimronAlakkal** [comment] 2022-08-19 06:34
Could you please share the docs link that you used? 
You don't have to hardcode the radius; you could use `MediaQuery.of(context).size.width * <the appropriate value that you think fits the radius>` to make a dynamic radius. Use in both the parent widget -- the card in this case -- and the child with the same value like @adilwahla above solution and it should be fine. Works for me.

> It doesn't, unfortunately – the issue isn't that it _can't_ be done, it's that the solution is non-obvious and not documented, and that the relevant example doesn't demonstrate the behavior that developers probably want. Hardcoding the radius values is also brittle – what if the Card's border radius changes in a future version of Material?

**Comment by maheshmnj** [comment] 2022-08-19 06:58
Hi @bryanoltman, Thanks for filing the issue. This is working as intended, The reason the corners are visible is because both Inkwell and card don't seem to have a uniform borderRadius. Card by default has a borderRadius of 4.0, Specifying the same borderRadius to InkWell should give the desired result.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: TappableCardContainer(),
    );
  }
}

class TappableCardContainer extends StatelessWidget {
  const TappableCardContainer({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Card(
          // shape: RoundedRectangleBorder(
          //   borderRadius: BorderRadius.circular(8.0),
          // ),
          child: InkWell(
            borderRadius: BorderRadius.circular(4.0),
            onTap: () {},
            child: Padding(
              padding: EdgeInsets.all(32),
              child: Text('hello'),
            ),
          ),
        ),
      ),
    );
  }
}

```
</details>   


### output

https://user-images.githubusercontent.com/31410839/185561764-c1734307-e046-44bf-a0a9-64aa7a18aa16.mov

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.0.5 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-08-19 06:58
Closing as this is working as intended, Incase you disagree feel free to write in the comments and we will reopen it.

Thank you.

**Comment by bryanoltman** [comment] 2022-08-19 14:43
@maheshmnj Thanks for taking the time to post a detailed response. I 100% understand why this issue is occurring and that a workaround exists (I can add my own border radius with a hardcoded value to match the Card's). The reason I think this needs addressing is that I can't think of a single case where the default behavior, demonstrated in the original post/[Card+InkWell example](https://api.flutter.dev/flutter/material/Card-class.html), would be desirable or not look broken to someone. Maybe there's a scenario I'm not thinking of though?

There could be any number of reasons that making this change in Card isn't the right move (unforeseen performance problems, greatly increased complexity, etc. etc. etc.), but at the very least, the examples should provide guidance that doesn't look broken. I'll add some of these thoughts to the original post, but I believe "The simplest-case behavior (that is also documented as an example on the official Flutter site) looks bad" is absolutely worth addressing.

**Comment by bryanoltman** [comment] 2022-08-19 15:32
Also, fwiw, I think the best workaround would be to set `clipBehavior: Clip.antiAlias` on the Card, which ensures that it will still look right even if the Card border radius changes. Maybe the answer is just that we need to document that in the example (with any performance caveats that may be involved).

**Comment by maheshmnj** [comment] 2022-08-22 06:02
Thanks for the info considering this as a documentation request and for further insights from the team.

**Closed** 2022-08-22 15:24 UTC
Labels: framework, f: material design, d: api docs, documentation

**Comment by dnfield** [comment] 2022-08-22 15:46
> Also, fwiw, I think the best workaround would be to set `clipBehavior: Clip.antiAlias` on the Card, which ensures that it will still look right even if the Card border radius changes. Maybe the answer is just that we need to document that in the example (with any performance caveats that may be involved).

I think you'd really want Clip.hardEdge but yes

**Comment by bryanoltman** [comment] 2022-08-22 15:52
@dnfield +1, the PR that addresses this issue uses `Clip.hardEdge`
