### ISSUE TITLE
Tab bar animates into view during initial load in release mode (unexpected behavior)

### ISSUE THREAD

**Issue by alardizabal** [flutter/flutter#10542] opened 2017-06-06 22:34 UTC
@eseidelGoogle @Hixie Per our conversation this afternoon, in release mode on Android, the tab bar animates into view during its initial load. This behavior is not visible in debug mode.

I'm using a Scaffold and in the appBar property I have the following:

    new PreferredSize(
       preferredSize: const Size.fromHeight(30.0),
       child: new Padding(
         padding: const EdgeInsets.symmetric(horizontal: 15.0),
         child: new Align(
            alignment: FractionalOffset.center,
            child: new TabBar(
              controller: _controller // TabController instance,
              isScrollable: true,
              tabs: tabs // List of Tab widgets,
            ),
          ),
        ),
      ),

**Comment by Hixie** [comment] 2017-06-07 18:18
Thanks!

Dupe of https://github.com/flutter/flutter/issues/10531

**Closed by Hixie** 2017-06-07 18:18 UTC
