### ISSUE TITLE
Camera Plugin not respect resolutionPreset

### ISSUE THREAD

**Issue by Ehudp** [flutter/flutter#111172] opened 2022-09-08 08:30 UTC
**What the Issue:**
when initializing the camera controller it does not respect the resolution 

```
 camController = CameraController(
      desc,
      ResolutionPreset.veryHigh,
      imageFormatGroup: ImageFormatGroup.yuv420         
    );
```

Then start the image stream
 `camController!.startImageStream((image) => _processCameraImage(image));`
```
 void _processCameraImage(CameraImage image) async {
    print('image.height ${image.height} image.width ${image.width}');
  }
```

The image size should be 1080p (1920x1080)

when set:  high, veryHigh, ultraHigh, max 
always get /// 720p (1280x720) high

scale down work : low 240p (320x240), medium (720x480)

**Device model:**
Xiaomi Mi 9 Light 
Ram 6
Android 10  QKQ1.190828.002

**flutter doctor** 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2403, on macOS 12.5.1 21G83
    darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Expected results:**

When startImageStream on the controller and get the image the ResolutionPreset should respect

**Comment by exaby73** [comment] 2022-09-08 12:54
Hello @Ehudp. Could you provide a [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you.

**Comment by Ehudp** [comment] 2022-09-11 04:52
Hi, 
I add a sample project and video that display the problem 
 
[camera_resolution_p
[Screen Recording 2022-09-11 at 7.46.36.mov.zip](https://github.com/flutter/flutter/files/9541795/Screen.Recording.2022-09-11.at.7.46.36.mov.zip)
reset.zip](https://github.com/flutter/flutter/files/9541792/camera_resolution_preset.zip)

**Comment by exaby73** [comment] 2022-09-12 09:51
This issue looks like a duplicate of https://github.com/flutter/flutter/issues/78247. Please upvote the original issue. Closing this one as a duplicate. Thank you.

**Closed by exaby73** 2022-09-12 09:51 UTC
Labels: in triage
