### ISSUE TITLE
Snackbar on wide screens does not comply with material 3

### ISSUE THREAD

**Issue by ltOgt** [flutter/flutter#150780] opened 2024-06-25 15:02 UTC
### Steps to reproduce

Snackbars are currently either full width or a fixed size and center aligned.
```dart
const SnackBarThemeData({
    this.backgroundColor,
    this.actionTextColor,
    this.disabledActionTextColor,
    this.contentTextStyle,
    this.elevation,
    this.shape,
    this.behavior,
    /// If this property is null, then the snack bar will take up the full device
    /// width less the margin. This value is only used when [behavior] is [SnackBarBehavior.floating].
    this.width,  // null by default => full width; specific value => fixed width to that value
    this.insetPadding,
    this.showCloseIcon,
    this.closeIconColor,
    this.actionOverflowThreshold,
    this.actionBackgroundColor,
    this.disabledActionBackgroundColor,
    this.dismissDirection,
  })
```

```dart
const SnackBar({
    super.key,
    required this.content,
    this.backgroundColor,
    this.elevation,
    this.margin,
    this.padding,
    this.width, // <------- same here
    this.shape,
    this.hitTestBehavior,
    this.behavior,
    this.action,
    this.actionOverflowThreshold,
    this.showCloseIcon,
    this.closeIconColor,
    this.duration = _snackBarDisplayDuration,
    this.animation,
    this.onVisible,
    this.dismissDirection,
    this.clipBehavior = Clip.hardEdge,
  })
```

___

Both Material 3 and Material 2 specify that on wide screens, the Snackbar should be aligned to the left or to the center, and grow horizontally to fit the content.

https://m3.material.io/components/snackbar/guidelines#418d202e-db21-429f-b72d-f34fd8723c35

```
On medium and expanded window sizes, like tablet and desktop, snackbars should scale horizontally to accommodate longer text strings, keeping in mind that the ideal line length for text is typically between 40-60 characters.
```

<img width="967" alt="Screenshot 2024-06-25 at 16 49 59" src="https://github.com/flutter/flutter/assets/24209580/b83fce6b-5a81-496e-b872-9bfc184b2d52">

(Although there is also this image)
![image](https://github.com/flutter/flutter/assets/24209580/319b847d-9e10-4f6d-9ec1-ca7d0c3c880d)

___

From just above https://m2.material.io/components/snackbars#placement ("Scaling and adaptation")
```
On medium and large screens, snackbars should scale horizontally to accommodate longer text strings,
keeping in mind that the ideal line length for text is typically between 40-60 characters.
```

<img width="786" alt="Screenshot 2024-06-25 at 16 46 34" src="https://github.com/flutter/flutter/assets/24209580/9e2a9ece-b61e-42d1-bb5b-205ba8a91efe">

From just above https://m2.material.io/components/snackbars#specs ("Snackbars in wide layouts")
```
In wide layouts, snackbars can be left-aligned or center-aligned if they are consistently placed on the same spot at the bottom of the screen.
```

<img width="812" alt="Screenshot 2024-06-25 at 16 47 28" src="https://github.com/flutter/flutter/assets/24209580/24022865-7e18-4fff-b34e-724d91012e49">

___

These are the options currently available:

fixed width (`width: 123`)
<img width="1326" alt="Screenshot 2024-06-25 at 16 54 59" src="https://github.com/flutter/flutter/assets/24209580/e5cdcb5d-b4e0-4d4e-8d15-01b7dc8b4dab">

full width (`width: null`)
<img width="1382" alt="Screenshot 2024-06-25 at 16 55 16" src="https://github.com/flutter/flutter/assets/24209580/1709f901-0286-47e6-bc7b-b6f7e6ca9548">

```dart

import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        snackBarTheme: const SnackBarThemeData(
          //no option for left alignment
          //
          // width: null, // <- fills full screen (default)
          // width: 123, // <- fixed width
          behavior: SnackBarBehavior.floating,
        ),
      ),
      home: Scaffold(
        body: const SizedBox(),
        floatingActionButton: Builder(
          builder: (c) => FloatingActionButton(
            onPressed: () {
              ScaffoldMessenger.of(c).showSnackBar(
                const SnackBar(
                  content: Text("text text text text text text"),
                ),
              );
            },
            child: const Icon(Icons.add),
          ),
        ),
      ),
    );
  }
}
```

### Expected results

Some way to have a snackbar that
- grows horizontally to accommodate longer text strings
- can be left or center aligned

### Actual results

No way to have a snackbar that
- grows horizontally to accommodate longer text strings
- can be left aligned

### Code sample

See above

### Screenshots or Video

See above

### Flutter Doctor output

Flutter (Channel stable, 3.22.0, on macOS 14.1 23B74 darwin-arm64, locale en-DE)

**Comment by huycozy** [comment] 2024-06-26 06:23
Hi @ltOgt 

>can be left or center aligned

This is a known issue being tracked at https://github.com/flutter/flutter/issues/52114. 

>grows horizontally to accommodate longer text strings

I'm not sure I understand this. Since you set a fixed width `width: 123`, the text will be shrunk and I think this works as intended. What is the expected result in this case?

**Comment by ltOgt** [comment] 2024-06-26 07:55
@huycozy thx for pointing to the existing issue regarding placement.

The part with the width is about there being no way to have snackbars with dynamic width, i.e. that fit the content.

you either have a fixed size or the snackbar fills the entire width of the screen (which honestly looks awful)

**Comment by huycozy** [comment] 2024-06-27 04:25
>The part with the width is about there being no way to have snackbars with dynamic width, i.e. that fit the content.

I see, there is already existing issue for this case https://github.com/flutter/flutter/issues/113039. Please follow up on that issue.

Closing this as a duplicate of those issues as mentioned.

**Closed by huycozy** 2024-06-27 04:25 UTC
Labels: in triage

**Comment by iapicca** [comment] 2024-06-27 04:59
@huycozy 

in the original [post](https://github.com/flutter/flutter/issues/150780#issue-2372930222)
is clearly mentioned that the specification for snackbar in M3 is [aligned](https://m3.material.io/components/snackbar/guidelines#418d202e-db21-429f-b72d-f34fd8723c35) either left or center

for my understanding
https://github.com/flutter/flutter/issues/113039 argument is to make the snackbar "customizable"
while this issue is reporting a lack of fidelity with M3 guidelines; it ain't the same thing

cc
@rydmike
