### ISSUE TITLE
[webview_flutter] will there be support for devices other than mobile anytime soon in this plugin?

### ISSUE THREAD

**Issue by ninetynin** [flutter/flutter#114978] opened 2022-11-09 15:38 UTC
I need to use webview for desktop platforms and im just curious like if there will be support added in official plugin
as i came across this https://pub.dev/packages/webview_flutter_platform_interface which is unlisted

or will it not be added 
current desktop supported webviews : https://pub.dev/packages/desktop_webview_window

**Comment by stuartmorgan** [comment] 2022-11-09 15:54
Duplicate of https://github.com/flutter/flutter/issues/37597, https://github.com/flutter/flutter/issues/41725, and https://github.com/flutter/flutter/issues/41726.

**Closed by stuartmorgan** 2022-11-09 15:54 UTC
