### ISSUE TITLE
framework.dart's updateChildren isn't as flexible as it seems to be

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#3846] opened 2016-05-11 17:03 UTC
If you use slots that aren't Elements it doesn't work as it passes the previousChild as the slot to updateChild.

**Comment by Hixie** [comment] 2017-01-29 00:06
The documentation does say that this is what it does. I'm going to close this Working As Intended. If you had a particular other resolution in mind instead let me know.

**Closed by Hixie** 2017-01-29 00:06 UTC
