### ISSUE TITLE
iOS page transition jank on iOS (ListView.children case)

### ISSUE THREAD

**Issue by sma** [flutter/flutter#76515] opened 2021-02-22 10:16 UTC
Inspired by the recent "jank" discussion on Reddit, I'd like to provide an example of jank which is a typical annoyance in apps we create. The main problem is that while we argue that building something in Flutter is faster and looks better than a HTML based app, the first impression customers have seems to proof that this statement is untrue. This is … unfortunate.

The code provided below demonstrates that on the first run (press the FAB), the page transition to a typical legal text page has no or nearly no animation. Going back to the start page and opening the legal text page for a second time has the usual "butter smooth" transition animation.

This misbehavior is clearly visible on modern iPhones like my 11+ and on the iOS simulator. You can also experience it when using macOS and dragging the window as wide as possible. On the first run, a lot of frames are dropped while animating the page transition. Thereafter, this isn't the case.

<details>
<summary>code sample</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';

final _random = Random();
final paragraphs = Iterable.generate(
  50,
  (i) => i == 0 || _random.nextInt(7) == 0
      ? '# Consetetur Sadipscing Elitr'
      : Iterable.generate(
          _random.nextInt(30) + _random.nextInt(20) + 10,
          (_) => const [
            'Lorem',
            'ipsum',
            'dolor',
            'sit',
            'amet.',
          ][_random.nextInt(5)],
        ).join(' '),
).toList();

void main() {
  print(paragraphs.length); // build paragraphs
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: StartPage(),
    );
  }
}

class StartPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Start Page')),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.push(
            context,
            MaterialPageRoute(builder: (_) => LegalPage()),
          );
        },
        child: Icon(Icons.arrow_forward),
      ),
    );
  }
}

class LegalPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Legal Page')),
      body: ListView(
        key: ValueKey('legal'),
        padding: const EdgeInsets.all(16),
        children: [
          ...paragraphs.map((p) {
            if (p.startsWith('# ')) {
              return Padding(
                padding: EdgeInsets.only(
                  top: 32,
                ),
                child: Text(
                  p.substring(2),
                  textScaleFactor: 1.5,
                ),
              );
            }
            return Padding(
              padding: const EdgeInsets.only(top: 16),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.baseline,
                textBaseline: TextBaseline.alphabetic,
                children: [
                  Text('  •  '),
                  Expanded(child: Text(p)),
                ],
              ),
            );
          }),
        ],
      ),
    );
  }
}
```
</details>

**Comment by pedromassangocode** [comment] 2021-02-22 13:02
Hi @sma 
Can you please provide your `flutter doctor -v` and the Timeline Trace of this issue? There is a guide in how to Profile a Flutter app: https://medium.com/flutter/profiling-flutter-applications-using-the-timeline-a1a434964af3#a499.

Eventually related to https://github.com/flutter/flutter/issues/76180.
Thank you

**Comment by sma** [comment] 2021-02-22 14:37
Here's the doctor output, rest follows later…
```
[✓] Flutter (Channel master, 1.27.0-5.0.pre.94, on macOS 11.2.1 20D74 darwin-x64, locale de-DE)
    • Flutter version 1.27.0-5.0.pre.94 at /Users/sma/Work/flutter
    • Framework revision 5642bed237 (12 hours ago), 2021-02-21 21:41:03 -0500
    • Engine revision b793775d2a
    • Dart version 2.13.0 (build 2.13.0-52.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sma/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
```

**Comment by sma** [comment] 2021-02-22 15:07
Here's a hopefully useful link to a timeline. Frankly, I don't really understand it. https://drive.google.com/file/d/1h5-Aj8EGPKGbOPzrQJYctDiXlbHd2Y0U/view?usp=sharing

**Comment by Hixie** [comment] 2021-02-25 06:08
I don't see any particular slow frames on that trace, unfortunately. Can you post a video showing what you are seeing, ideally showing several transitions so that we can see if it gets faster with each run, and attach a trace taken while recording that video? (I'm sure you already are, but just to be extra safe, make sure to use a `--profile` build.)

**Comment by Hixie** [comment] 2021-03-05 22:52
Running this on Android I see a small stutter when the frame page first comes in, which I believe may be from building all the text widgets. There's also some evidence of shader compilation in the trace, though not as much as I would expect.

@sma having a video and traces of the stuttering you are seeing would definitely help here (there's no point us chasing down a different problem than you're seeing!).

**Comment by sma** [comment] 2021-03-06 07:56
I'm sorry i took so long. Here's a [video](https://user-images.githubusercontent.com/14989/110199619-8300f800-7e59-11eb-8624-520fbfa0c68e.mov) running the application, just after building & installing it with `flutter run -d <id> --release`. The first time, I open the "legal" page, just jumps into existence, but didn't move smoothly. This is very noticable on the second try. Thereafter, it is smooth as it should be.

**Comment by Hixie** [comment] 2021-03-06 08:17
Perfect, thanks, that's super helpful! Definitely more obvious there than what I was seeing locally.
I wonder if the cause is the shaders for the blurs, I don't see anything else that would be changing during the animation.

Can you try importing `package:flutter/painting.dart` and setting debugDisableShadows to true in your `void main`, then recording the video again? It'll look terrible (assuming the flag works), but it might tell us if the blurred shadows are the cause of the problem or not.

**Comment by sma** [comment] 2021-03-06 08:59
I added the setting but I didn't see a visual difference in release mode, only in debug mode. And I actually like the bold look of the FAB :) Still, the [release build looks better](https://user-images.githubusercontent.com/14989/110201266-7b921c80-7e62-11eb-9f99-a48367cf5648.mov) for the first two transitions. I've also recorded the [debug version](https://user-images.githubusercontent.com/14989/110201294-9d8b9f00-7e62-11eb-952a-dfb9ecc69400.mov) in case you need it.

**Comment by Hixie** [comment] 2021-03-06 09:15
Ah it's possible we don't support that in profile builds, right. Ah well.

**Comment by sma** [comment] 2021-03-06 09:19
PS: I set the `elevation` of `FAB` and `AppBar` to 0 and [tried again](https://user-images.githubusercontent.com/14989/110201564-fdcf1080-7e63-11eb-9e6f-24f2aea822cc.mov). To me, this looks much better – or my phone got used to the animation. At second 4, however, there's sudden jank. 

My example throws away the `LegalPage` widget and therefore I assume all elements and render objects are also thrown away and recreated every time. Could this be a garbage collection delay?

I tried to reproduce this with a profile build, but failed. All I got was this:

![image](https://user-images.githubusercontent.com/14989/110201766-2572a880-7e65-11eb-802b-3e2f1a3126d6.png)

There's a subtile tip once but everything else looks fine.

**Comment by Hixie** [comment] 2021-03-06 09:24
> Could this be a garbage collection delay?

Maybe. Hard to say without a profile. Could also be something the phone was doing unrelated to Flutter (like maybe your calendar app decided to sync at that point and the system scheduler missed a frame). The only way to know for sure would be to get a system trace that includes every the OS is doing. (If it reliably happens at the same place each time then it's more likely a Flutter thing.)

That setting the elevations to 0 removes a lot of the jank is definitely telling and is certainly consistent with other cases of jank we've seen where it's all about the shadows...

**Comment by sma** [comment] 2021-03-06 09:39
Here is a comparison of [elevation 0](https://user-images.githubusercontent.com/14989/110202119-0117cb80-7e67-11eb-8576-a6ae406742fa.mov) and [elevation 24](https://user-images.githubusercontent.com/14989/110202133-0ecd5100-7e67-11eb-93c0-ac816520c211.mov).

There's still a shadow because of the `CupertinoPageTransition` that has some kind of shadow animation, and while there's still jank, I think, there's less jank with less shadow.

I will remove the shadows from our app to improve the first impression. While nobody complained and nobody really reads the legal stuff (I'm sure) it still feels cheapish if the transition looks sluggish. And of course we argued that with Flutter you get native performance compared other alternatives.

**Comment by vincenzosarnataro** [comment] 2021-03-16 10:21
@sma Can you try in dev channel? The CupertinoTransition has been optimized with this pull request https://github.com/flutter/flutter/pull/75670

**Comment by sma** [comment] 2021-03-16 15:03
I don't use `dev`, but I'll try on `master` tomorrow :-)

**Comment by sma** [comment] 2021-03-17 07:19
Here is a new [recording](https://user-images.githubusercontent.com/14989/111429355-317a2800-86f9-11eb-819f-fbe30bce8b4a.mov). There is less initial jank, but the second transition still feels a bit smoother. But it's an improvement. Thanks.

**Comment by danagbemava-nc** [comment] 2021-11-17 12:32
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by danagbemava-nc** 2021-11-17 12:32 UTC
Labels: platform-ios, waiting for customer response, engine, severe: performance, severe: rendering, passed first triage, perf: speed
