### ISSUE TITLE
AnimatedList & ListView item's image changes temporarily when add and remove

### ISSUE THREAD

**Issue by shinyo17** [flutter/flutter#75400] opened 2021-02-04 07:22 UTC
**Expected results:** 
I want to see it just change their order by tapping the image, but they are changing each other.
so it don't looks smoothly.

**Actual results:** 
using ListView
![Feb-04-2021 16-26-20](https://user-images.githubusercontent.com/63589031/106858998-cb67b180-6705-11eb-9538-f32a29670fec.gif)

using AnimatedList
![Feb-03-2021 18-48-53](https://user-images.githubusercontent.com/63589031/106858755-7c218100-6705-11eb-9f9a-916fb02c9e76.gif)

My code about ListView and the item

<details>
<summary>code sample</summary>

```dart
companionListView(List<Companion> companions) {
    return Container(
      height: 60,
      width: 60.0 * (companions.length),
      child: Center(
        child: ListView.builder(
          scrollDirection: Axis.horizontal,
          itemCount: companions.length,
          shrinkWrap: true,
          itemBuilder: (BuildContext context, int index) {
              return Align(
                      widthFactor: 0.57,
                      child: Stack(
                        overflow: Overflow.visible,
                        children: [
                          GestureDetector(
                            onTap: () {
                              removeCompanion(companions, index);
                            },
                            child: CircleAvatar(
                              backgroundColor: Color(0xFFffffff),
                              radius: 30,
                              backgroundImage: companions[index].image.isNotEmpty
                                  ? CachedNetworkImageProvider(companions[index].image)
                                  : AssetImage('assets/images/abcd.png'),
                            ),
                          ),
                          Positioned(
                              top: 0,
                              left: 0,
                              child: Image.asset('assets/images/border_check_y.png', width: 20, height: 20))
                        ],
                      ),
                    );
            }
          },
        ),
      ),
    );
  }

```

```
removeCompanion(List<Companion> companions, int index) {
      companions.add(companions[index]);
      companions.remove(companions[index]);
  }
```

My code about AnimatedList and Item
```
companionAnimatedList(List<Companion> companions) {
    return Container(
      height: 60,
      width: 40.0 * (companions.length),
      child: Center(
        child: AnimatedList(
          shrinkWrap: true,
          key: key1,
          scrollDirection: Axis.horizontal,
          initialItemCount: companions?.length ?? 0,
          itemBuilder: (context, index, animation) {
            return Align(
              widthFactor: 0.57,
              child: buildCompanion(
                companions,
                companions[index],
                selectedList,
                index,
                animation,
                companionSelection,
              ),
            );
          },
        ),
      ),
    );
  }

  Widget buildCompanion(
    companions,
    companion,
    selectedList,
    int index,
    Animation<double> animation,
    companionSelection,
  ) {
    return companionWidget(
      index,
      companions,
      companion,
      selectedList,
      animation,
      companionSelection,
    );
  }

  Widget companionWidget(index, companions, companion, selectedList, animation, companionSelection) {
      return SizeTransition(sizeFactor: animation, child: buildStack(index, companions));
  }

  buildStack(index, companions) {
    if (companionSelection[companions[index].id] == false) {
      return Stack(
        overflow: Overflow.visible,
        children: [
          GestureDetector(
            onTap: () {
              removeCompanion(index, companions, idx, selectedList, companionSelection, key1);}
            child: ColorFiltered(
              colorFilter: ColorFilter.mode(Colors.grey[200], BlendMode.modulate),
              child: CircleAvatar(
                backgroundColor: Color(0xFFffffff),
                radius: 30,
                backgroundImage: companions[index].image.isNotEmpty
                    ? CachedNetworkImageProvider(companions[index].image)
                    : AssetImage('assets/images/abcd.png'),
              ),
            ),
          ),
          Positioned(top: 0, left: 0, child: Image.asset('assets/images/border_check_g.png', width: 20, height: 20)),
        ],
      );
    } 
    }
  }


  void removeCompanion(index, companions, idx, selectedList, companionSelection, key1) {
   
      companions.add(companions[index]);
      selectedList.remove(companions[index]);
      companions.removeAt(index);
      key1.currentState.removeItem(index, (context, animation) => Container());
      key1.currentState.insertItem(companions.length - 1);

   

  }
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale ko-KR)
    • Flutter version 1.22.6 at /Users/shinyounglee/flutter
    • Framework revision 9b2d32b605 (12일 전), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices
    • Android SDK at /Users/shinyounglee/Library/Android/sdk
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    ✗ No valid Android SDK platforms found in /Users/shinyounglee/Library/Android/sdk/platforms. Directory was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone 12 mini (mobile) • 8B8F502D-559C-4E10-A395-2AFD9ABE50F9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 2 categories.
```
</details>

</details>

**Comment by pedromassangocode** [comment] 2021-02-04 07:43
Hi @shinyo17 
Can you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that does not uses any third-party plugin/package?
Thank you

**Comment by shinyo17** [comment] 2021-02-05 01:21
Hi @pedromassangocode 
I remove the another codes my best.

**Comment by pedromassangocode** [comment] 2021-02-05 06:19
Hi @shinyo17 
I still cannot reproduce the issue using the code you provided because it contains references for files that are missing.

**Comment by pedromassangocode** [comment] 2021-02-26 13:01
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-02-26 13:01 UTC
Labels: in triage, waiting for customer response
