### ISSUE TITLE
fresh linux & flutter install giving error building andoid app

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#89224] opened 2021-08-31 15:56 UTC
Brand new install of flutter 2.2.1 stable on new install of ubuntu 21.04 is giving the following error:

```
/snap/flutter/current/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
```
Any advice how to resolve would be really appreciated.

Thanks

## Logs

<details>
<summary>Logs</summary>

```
Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bitmap:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/jimmyff/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/jimmyff/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/bitmap-0.1.2/android/.cxx/cmake/debug/armeabi-v7a --target bitmap}
  [1/2] Building CXX object CMakeFiles/bitmap.dir/home/jimmyff/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/bitmap-0.1.2/ios/Classes/bitmap.cpp.o

  FAILED: /home/jimmyff/Android/Sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=armv7-none-linux-androideabi16 --gcc-toolchain=/home/jimmyff/Android/Sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/jimmyff/Android/Sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -Dbitmap_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/bitmap.dir/home/jimmyff/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/bitmap-0.1.2/ios/Classes/bitmap.cpp.o -MF CMakeFiles/bitmap.dir/home/jimmyff/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/bitmap-0.1.2/ios/Classes/bitmap.cpp.o.d -o CMakeFiles/bitmap.dir/home/jimmyff/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/bitmap-0.1.2/ios/Classes/bitmap.cpp.o -c /home/jimmyff/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/bitmap-0.1.2/ios/Classes/bitmap.cpp
  In file included from /home/jimmyff/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/bitmap-0.1.2/ios/Classes/bitmap.cpp:1:
  In file included from /snap/flutter/current/usr/include/c++/8/stdlib.h:36:
  In file included from /snap/flutter/current/usr/include/c++/8/cstdlib:41:
  In file included from /snap/flutter/current/usr/include/x86_64-linux-gnu/c++/8/bits/c++config.h:508:
  In file included from /snap/flutter/current/usr/include/x86_64-linux-gnu/c++/8/bits/os_defines.h:39:
  In file included from /snap/flutter/current/usr/include/features.h:448:
  /snap/flutter/current/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
  # include <gnu/stubs-32.h>
            ^~~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

```
jimmyff@ubuntubox:~/dev/os_app$ flutter doctor -v
[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.2.1 at /home/jimmyff/snap/flutter/common/flutter
    • Framework revision 02c026b03c (3 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/jimmyff/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /home/jimmyff/tools/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /home/jimmyff/tools/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (1 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 31) (emulator)

```

</details>

**Comment by darshankawar** [comment] 2021-09-01 07:47
@jimmyff 
`fatal error: 'gnu/stubs-32.h' file not found` seems to be coming from `snap` installation.
Please check [this](https://github.com/flutter/flutter/issues/72415#issuecomment-789561263) issue comment for more details. You will need to open this issue in snap's dedicated repo.

Closing from here as duplicate of https://github.com/flutter/flutter/issues/72415

**Closed by darshankawar** 2021-09-01 07:47 UTC
Labels: in triage
