### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by ketanchoyal** [flutter/flutter#93126] opened 2021-11-05 14:01 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
As soon as I choose flutter v 2.5.3, I get the following error

## Logs
FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:433:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:432:12)
#5      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:794:19)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:688:5)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:557:9)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1227:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-CA)
    • Flutter version 2.5.3 at /Users/ketanchoyal/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ketanchoyal/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] VS Code (version 1.62.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (3 available)
    • iPhone 13 Pro (mobile) • 4A7F5873-9F07-4E31-96E6-EFD68A757A56 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 95.0.4638.69
    ! Error: Ketan's iPad is not connected. Xcode will continue when Ketan's iPad is connected. (code -13)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 5d36f2e7f5387b6c751449258ade8e4e6edf99be
### Plugins
connectivity_plus-1.0.6
connectivity_plus_linux-1.0.3
connectivity_plus_macos-1.0.2
connectivity_plus_web-1.0.2
connectivity_plus_windows-1.0.2
device_info-2.0.0
file_picker-4.1.4
firebase_auth-3.1.3
firebase_auth_web-3.1.2
firebase_core-1.7.0
firebase_core_web-1.1.0
firebase_messaging-10.0.8
firebase_messaging_web-2.0.6
flutter_keyboard_visibility-5.1.0
flutter_keyboard_visibility_web-2.0.0
flutter_plugin_android_lifecycle-2.0.3
google_maps_flutter-2.0.9
google_maps_flutter_web-0.3.1
image_gallery_saver-1.7.1
image_picker-0.8.3
image_picker_for_web-2.1.2
package_info_plus-1.0.1
package_info_plus_macos-1.1.1
package_info_plus_web-1.0.1
path_provider-2.0.1
path_provider_linux-2.0.0
path_provider_macos-2.0.0
path_provider_windows-2.0.0
photo_manager-1.3.0
sentry_flutter-5.1.0
share_plus-2.1.4
share_plus_macos-2.0.2
share_plus_web-2.0.4
shared_preferences-2.0.5
shared_preferences_linux-2.0.0
shared_preferences_macos-2.0.0
shared_preferences_web-2.0.0
shared_preferences_windows-2.0.0
sqflite-2.0.0+3
url_launcher-6.0.7
url_launcher_linux-2.0.0
url_launcher_macos-2.0.0
url_launcher_web-2.0.1
url_launcher_windows-2.0.0
video_compress-3.1.0
video_player-2.1.12
video_player_web-2.0.2
video_thumbnail-0.4.3
wakelock-0.5.2
wakelock_macos-0.1.0+1
wakelock_web-0.2.0+1

**Comment by maheshmnj** [comment] 2021-11-08 07:38
Hi @ketanchoyal, Thanks for filing the issue. Can you please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue?

Thanks

**Comment by maheshmnj** [comment] 2021-11-09 10:27
Closing this issue as a duplicate of https://github.com/flutter/flutter/issues/65242

**Closed by maheshmnj** 2021-11-09 10:27 UTC
