### ISSUE TITLE
WidgetSpan alignment not working in Textfield 

### ISSUE THREAD

**Issue by radha1990kumari** [flutter/flutter#102570] opened 2022-04-26 11:58 UTC
## Steps to Reproduce

Please run this code 
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final WidgetSpanTextEditingController _controller =
      WidgetSpanTextEditingController(
          text: 'The quick brown fox jumps over the lazy \uffff dog.');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: TextField(
          controller: _controller,
          maxLines: null,
        ),
      ),
    );
  }
}

class WidgetSpanTextEditingController extends TextEditingController {
  WidgetSpanTextEditingController({String? text})
      : super.fromValue(text == null
            ? TextEditingValue.empty
            : TextEditingValue(text: text));

  @override
  TextSpan buildTextSpan(
      {required BuildContext context,
      TextStyle? style,
      required bool withComposing}) {
    TextRange? matchedRange;

    if (text.contains('\uffff')) {
      matchedRange = _findMatchedRange(text);
    }

    if (matchedRange != null) {
      return TextSpan(
        children: [
          TextSpan(text: matchedRange.textBefore(text)),
          const WidgetSpan(
              baseline: TextBaseline.ideographic,
              alignment: PlaceholderAlignment.aboveBaseline,
              child: FlutterLogo()),
          TextSpan(text: matchedRange.textAfter(text)),
        ],
        style: style,
      );
    }

    return TextSpan(text: text, style: style);
  }

  TextRange _findMatchedRange(String text) {
    final RegExp matchPattern = RegExp(RegExp.escape('\uffff'));
    late TextRange matchedRange;

    for (final Match match in matchPattern.allMatches(text)) {
      matchedRange = TextRange(start: match.start, end: match.end);
    }

    return matchedRange;
  }
}

```

**Expected results:** 

The alignment of Flutter logo should change as I vary alignment values

**Actual results:** 

Nothing happens 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment] 2022-04-26 13:53
Hi @radha1990kumari, thanks for filing the issue. Please provide the output of `flutter doctor -v`. 

A video/screen recording of how to reproduce the issue would also be helpful in this case. 

Thank you

**Comment by radha1990kumari** [comment] 2022-04-26 14:13
Please just run the code sample and change the alignment value in `WidgetSpan` widget  to see that it doesn't have any effect.

Here's the doctor output 

```
[√] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19043.1645], locale en-US)
    • Flutter version 2.10.4 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (5 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\Skylum\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1645]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 100.0.4896.127
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 100.0.1185.50

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by danagbemava-nc** [comment] 2022-04-27 08:02
Hi @radha1990kumari, it looks like this has been fixed on `master`. See screen recordings below. Can you confirm if this is the case for you as well?

<details>
<summary>videos</summary>

| stable | master |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/165470658-dacdadba-1724-4b37-80a2-8e5e8138f13e.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/165470673-e63af5a6-a7aa-41ea-9881-289d2ede8b34.mov" /> |



</details>

<details>
<summary>code sample used</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  WidgetSpanTextEditingController _controller = WidgetSpanTextEditingController(
      text: 'The quick brown fox jumps over the lazy \uffff dog.');

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                child: Column(
                  children: PlaceholderAlignment.values
                      .map(
                        (e) => Text.rich(
                          TextSpan(children: [
                            TextSpan(text: e.toString()),
                            WidgetSpan(
                              baseline: TextBaseline.ideographic,
                              alignment: e,
                              child: const FlutterLogo(),
                            ),
                          ]),
                        ),
                      )
                      .toList(),
                ),
              ),
            ),
            Text('_controller.widgetSpanAlignment: ${_controller.widgetSpanAlignment}'),
            Expanded(
              child: TextField(
                controller: _controller,
                maxLines: null,
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.text_format),
        onPressed: () {
          PlaceholderAlignment alignment = PlaceholderAlignment.values[
              (PlaceholderAlignment.values
                          .indexOf(_controller.widgetSpanAlignment) +
                      1) %
                  PlaceholderAlignment.values.length];

          setState(() {
            _controller = WidgetSpanTextEditingController(
              text: _controller.value.text,
              widgetSpanAlignment: alignment,
            );
          });
        },
      ),
    );
  }
}

class WidgetSpanTextEditingController extends TextEditingController {
  final PlaceholderAlignment widgetSpanAlignment;

  WidgetSpanTextEditingController(
      {String? text, this.widgetSpanAlignment = PlaceholderAlignment.bottom})
      : super.fromValue(text == null
            ? TextEditingValue.empty
            : TextEditingValue(text: text));

  @override
  TextSpan buildTextSpan(
      {required BuildContext context,
      TextStyle? style,
      required bool withComposing}) {
    TextRange? matchedRange;

    if (text.contains('\uffff')) {
      matchedRange = _findMatchedRange(text);
    }

    if (matchedRange != null) {
      return TextSpan(
        children: [
          TextSpan(text: matchedRange.textBefore(text)),
          WidgetSpan(
            baseline: TextBaseline.ideographic,
            alignment: widgetSpanAlignment,
            child: const FlutterLogo(),
          ),
          TextSpan(text: matchedRange.textAfter(text)),
        ],
        style: style,
      );
    }

    return TextSpan(text: text, style: style);
  }

  TextRange _findMatchedRange(String text) {
    final RegExp matchPattern = RegExp(RegExp.escape('\uffff'));
    late TextRange matchedRange;

    for (final Match match in matchPattern.allMatches(text)) {
      matchedRange = TextRange(start: match.start, end: match.end);
    }

    return matchedRange;
  }
}

```
</details>

**Comment by radha1990kumari** [comment] 2022-04-28 06:54
@danagbemava-nc Thank you for the clarification , so when should I expect this to be fixed in stable as well, in the meantime could you also suggest how to make it workable in stable channel

**Closed** 2022-04-28 07:15 UTC
Labels: in triage
