### ISSUE TITLE
[iOS bug] Gap between elevation shadow and Card widget

### ISSUE THREAD

**Issue by kofan** [flutter/flutter#67848] opened 2020-10-10 22:36 UTC
## Steps to Reproduce

Hi! Here is a simple example of the Flutter application where you can see the gap beneath the `Card` widget that appears between its bottom and the elevation shadow (run it on **iPhone 11 Pro Max**):

```dart
import 'package:flutter/material.dart';

void main() => runApp(GapApp());

class GapApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'Gap',
        home: Scaffold(
          appBar: AppBar(title: Text('Gap on iPhone 11 Pro Max')),
          body: Padding(
            padding: EdgeInsets.symmetric(vertical: 50, horizontal: 25.0),
            child: Card(
              elevation: 10.0,
              color: Colors.amber,
              child: Container(),
            ),
          ),
        ),
      );
}
```

<img src="https://user-images.githubusercontent.com/4638248/95665787-33ddc200-0b5c-11eb-9ea5-1c4d1aff92d2.png" width="350" />

**Expected results:** The elevation shadow displayed correctly without the gap.

**Actual results:** The gap appears between the `Card` widget and its elevation shadow.

**Additional notes:** 
- A bigger value of `elevation` property results in a bigger gap.
- I see this problem on all iOS devices with big screens (iPhone XS Max, iPhone 11 Pro Max, iPad...)
- I do **not** see this problem on Android (tested using **Pixel 2/3** and **Pixel C** devices).
- A similar issue **https://github.com/flutter/flutter/issues/18984** was closed without being resolved **FOR 2 YEARS**.

<details>
<summary><strong><code>flutter analyze</code></strong></summary>

```
Analyzing gap_issue...                                                  
No issues found! (ran in 1.8s)
```
</details>

<details>
<summary><strong><code>flutter doctor -v</code></strong></summary>

```
[✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G73, locale en-UA)
    • Flutter version 1.22.1 at /Users/mkofan/Software/flutter
    • Framework revision f30b7f4db9 (2 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/mkofan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • A5EC5A06-1ADC-48F1-B4EB-FF880D2136E0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!
```
</details>

<details>
<summary><strong><code>flutter run --verbose</code></strong></summary>

It's too big, so I've attached it as a file: [`flutter_run_verbose.txt`](https://github.com/flutter/flutter/files/5360359/flutter_run_verbose.txt)

</details>

**Comment by darshankawar** [comment] 2020-10-12 11:46
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.221, on Mac OS X 10.15.4 19E2269
    x86_64, locale en-IN)
    • Flutter version 1.23.0-8.0.pre.221 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 0d8d4f77aa (4 days ago), 2020-10-08 09:26:30 +0200
    • Engine revision 2eac514f26
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios            • iOS 14.0
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 x86_64
    • Web Server (web)                    • web-server
      • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 86.0.4240.75

• No issues found!

```

</details>

<img width="375" alt="Screenshot 2020-10-12 at 5 12 38 PM" src="https://user-images.githubusercontent.com/67046386/95742875-626bb200-0cae-11eb-9395-139c5e1427b0.png">

**Comment by maheshmnj** [comment] 2022-11-25 22:13
I am unable to reproduce the issue on the latest master 3.6, So It is very likely that the issue is fixed.

<img src="https://user-images.githubusercontent.com/31410839/204059439-71a57040-147c-4752-b129-72c1d35a0f7c.png" width ="300"> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.6.0-6.0.pre.33, on macOS 12.6 21G115 darwin-arm64,
    locale en-IN)
    • Flutter version 3.6.0-6.0.pre.33 on channel master at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9858ec524 (72 minutes ago), 2022-11-21 10:58:11 -0500
    • Engine revision 46a6b54295
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>


Closing since its not reproducible. Incase anyone still encounters the issue, feel free to leave a comment on the issue and we will reopen it right away. 

Thank you.

**Closed by maheshmnj** 2022-11-25 22:13 UTC
Labels: platform-ios, framework, f: material design, has reproducible steps, found in release: 1.23
