### ISSUE TITLE
[in_app_purchase] Can't restore purchases

### ISSUE THREAD

**Issue by erperejildo** [flutter/flutter#108362] opened 2022-07-26 11:11 UTC
This was working already but I updated package to latest version (as well Flutter to v3):
https://pub.dev/packages/in_app_purchase

I can make the payment and check what I bought but after refresh it doesn't restore this. If I try to buy the same version again it says that I already own it:

<img width="247" alt="Screenshot 2022-07-25 at 11 04 20" src="https://user-images.githubusercontent.com/5629919/180992558-b7e5107a-c05f-47b7-a1a4-4ab5d5881190.png">

    Future<void> initStore() async {
        final bool isAvailableTemp = await inAppPurchase.isAvailable();
        if (!isAvailable) {
          isAvailable = isAvailableTemp;
          products = [];
          purchases = [];
          notFoundIds = [];
          purchasePending = false;
          loading = false;
          return;
        }
    
        if (Platform.isIOS) {
          final InAppPurchaseStoreKitPlatformAddition iosPlatformAddition =
              inAppPurchase
                  .getPlatformAddition<InAppPurchaseStoreKitPlatformAddition>();
          await iosPlatformAddition.setDelegate(PaymentQueueDelegate());
        }
    
        final ProductDetailsResponse productDetailResponse =
            await inAppPurchase.queryProductDetails(_androidProductIds.toSet());
    
        if (productDetailResponse.error != null) {
          queryProductError = productDetailResponse.error!.message;
          isAvailable = isAvailable;
          products = productDetailResponse.productDetails;
          purchases = <PurchaseDetails>[];
          notFoundIds = productDetailResponse.notFoundIDs;
          purchasePending = false;
          loading = false;
          return;
        }
      }
    
      Future<List<ProductDetails>> getProducts() async {
        if (products.isEmpty) {
          final ProductDetailsResponse products =
              await inAppPurchase.queryProductDetails(
            Platform.isAndroid
                ? _androidProductIds.toSet()
                : _iOSProductIds.toSet(),
          );
          if (products.productDetails.isNotEmpty) {
            // double check the order of the products
            if (Helpers.containsInStringIgnoreCase(
                products.productDetails[0].title, "plus")) {
              this.products.addAll(products.productDetails);
            } else {
              // pro comes first
              this.products.add(products.productDetails[1]);
              this.products.add(products.productDetails[0]);
            }
          }
        }
        return products;
      }

    Future<List<PurchaseDetails>> getPastPurchases(BuildContext context) async {
        if (purchases.isEmpty) {
          final Stream<List<PurchaseDetails>> purchaseUpdated =
              inAppPurchase.purchaseStream;
    
          _subscription = purchaseUpdated.listen((purchaseDetailsList) {
            if (purchaseDetailsList.isEmpty) {
              detectProVideo(context);
            } else {
              // this.purchases.addAll(purchaseDetailsList);
              listenToPurchaseUpdated(context, purchaseDetailsList);
            }
            _subscription.cancel();
          }, onDone: () {
            _subscription.cancel();
          }, onError: (error) {
            // handle error here.
            _subscription.cancel();
          });
    
          await inAppPurchase.restorePurchases();
    
          if (Platform.isIOS) {
            Map<String, PurchaseDetails> purchases =
                Map.fromEntries(this.purchases.map((PurchaseDetails purchase) {
              if (purchase.pendingCompletePurchase) {
                inAppPurchase.completePurchase(purchase);
              }
              return MapEntry<String, PurchaseDetails>(
                  purchase.productID, purchase);
            }));
            if (purchases.isEmpty) {
              Provider.of<AdState>(context, listen: false).toggleAds(context, true);
            } else {
              Provider.of<AdState>(context, listen: false)
                  .toggleAds(context, false);
            }
          }
        }
        return purchases;
      }

So this is always `true`:

    if (purchaseDetailsList.isEmpty) {

Testing locally on an Android emulator

doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by exaby73** [comment] 2022-07-26 14:03
Duplicate of https://github.com/flutter/flutter/issues/107454

**Closed by exaby73** 2022-07-26 14:03 UTC
Labels: in triage
