### ISSUE TITLE
The overflowing RenderFlex in question: NavigationRail and NavigationRailDestination

### ISSUE THREAD

**Issue by Amoystyle** [flutter/flutter#99968] opened 2022-03-11 10:36 UTC
**Build for Window Desktop.**

**Version:** 
```
Flutter 2.11.0-0.0.pre.794 • channel master • https://github.com/flutter/flutter.git
Framework • revision dce7f869cc (5 days ago) • 2022-03-06 17:11:15 -0500
Engine • revision 6576bd428a
Tools • Dart 2.17.0 (build 2.17.0-180.0.dev) • DevTools 2.11.1
```
**Error Msg**
```
The relevant error-causing widget was
Row
lib\main.dart:69
To inspect this widget in Flutter DevTools, visit: [http://127.0.0.1:9100/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A51282%2F2uROG0czKjg%3D%2F&inspectorRef=inspector-0]()
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#939a0 relayoutBoundary=up1 OVERFLOWING
```

**Code:**
```dart
import 'dart:math';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        textTheme: GoogleFonts.robotoMonoTextTheme(Theme.of(context).textTheme),
      ),
      scrollBehavior: AppScrollBehavior(),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _selectedIndex = 0;
  final PageController _pageController = PageController();

  _pageChanged(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  _destinationSelected(int index) {
    setState(() {
      _selectedIndex = index;
      _pageController.jumpToPage(index);
    });
  }

  @override
  void initState() {
    super.initState();
    //_pageController = PageController();
    _pageController.addListener(() {
      // double offset = _pageController.offset;
      // double? page = _pageController.page;
      // debugPrint('$offset, $page');
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Row(
        children: <Widget>[
          LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
              debugPrint('$constraints');
              return ScrollConfiguration(
                behavior: ScrollConfiguration.of(context).copyWith(scrollbars: false),
                child: SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: ConstrainedBox(
                    constraints: BoxConstraints(minHeight: constraints.maxHeight),
                    child: IntrinsicHeight(
                      child: NavigationRail(
                        backgroundColor: Colors.grey[300],
                        unselectedIconTheme: const IconThemeData(color: Color.fromARGB(255, 59, 141, 182)),
                        unselectedLabelTextStyle: const TextStyle(color: Colors.blueGrey),

                        ///
                        elevation: 1.0,

                        ///
                        selectedIndex: _selectedIndex,
                        onDestinationSelected: _destinationSelected,

                        ///
                        minWidth: 56,
                        labelType: NavigationRailLabelType.none,
                        extended: true,
                        minExtendedWidth: 190,

                        ///
                        destinations: const [
                          NavigationRailDestination(icon: Icon(Icons.label_outline), label: Text('1')),
                          NavigationRailDestination(icon: Icon(Icons.label_outline), label: Text('22')),
                          NavigationRailDestination(icon: Icon(Icons.label_outline), label: Text('333')),
                          NavigationRailDestination(icon: Icon(Icons.label_outline), label: Text('4444')),
                          NavigationRailDestination(icon: Icon(Icons.label_outline), label: Text('55555')),
                          NavigationRailDestination(icon: Icon(Icons.label_outline), label: Text('666666')),
                          NavigationRailDestination(icon: Icon(Icons.label_outline), label: Text('7777777')),
                          NavigationRailDestination(icon: Icon(Icons.label_outline), label: Text('888888888888')),
                        ],
                      ),
                    ),
                  ),
                ),
              );
            },
          ),

          //const VerticalDivider(thickness: 1, width: 1),

          /// This is the main content.
          Expanded(
            child: PageView(
              scrollDirection: Axis.vertical,
              controller: _pageController,
              physics: const NeverScrollableScrollPhysics(),

              ///
              onPageChanged: _pageChanged,
              children: <Widget>[
                Container(
                  color: Colors.blue,
                ),
                Container(
                  color: Colors.green,
                ),
                Container(
                  color: Colors.indigo,
                ),
                Container(
                  color: Colors.pink,
                ),
                Container(
                  color: Colors.orange,
                ),
                Container(
                  color: Colors.red,
                ),
                Container(
                  color: Colors.yellow,
                ),
                Container(
                  color: Colors.teal,
                ),
                Container(
                  color: Colors.cyan,
                ),
                Container(
                  color: Colors.brown,
                ),
              ],
            ),
          )
        ],
      ),
    );
  }
}

class AppScrollBehavior extends MaterialScrollBehavior {
  @override
  Set<PointerDeviceKind> get dragDevices => {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
      };
}

Color randomColor() {
  return Color.fromARGB(255, Random().nextInt(256) + 0, Random().nextInt(256) + 0, Random().nextInt(256) + 0);
}
```

**I tried everything. How to Fix it?**

**Comment by maheshmnj** [comment] 2022-03-11 13:16
Hi @Amoystyle, I ran your code sample and I couldn't reproduce any error. However, if you are seeing it,  This is usually caused by the widgets being too big to fit within the available space, and as the error mentions you should see where the overflow is with yellow stripes 

> The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

If you need help fixing those errors I would suggest you please ask such questions on community forums like StackOverflow with sufficient code sample and explanation. Please note that the issue tracker is to file bugs and feature requests in flutter framework.

Closing as this is neither a bug nor a feature request in case you disagree fee free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2022-03-11 13:16 UTC
Labels: in triage

**Comment by Amoystyle** [comment] 2022-03-14 02:06
> Hi @Amoystyle, I ran your code sample and I couldn't reproduce any error. However, if you are seeing it, This is usually caused by the widgets being too big to fit within the available space, and as the error mentions you should see where the overflow is with yellow stripes
> 
> > The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
> 
> If you need help fixing those errors I would suggest you please ask such questions on community forums like StackOverflow with sufficient code sample and explanation. Please note that the issue tracker is to file bugs and feature requests in flutter framework.
> 
> Closing as this is neither a bug nor a feature request in case you disagree fee free to write in the comments and we will reopen it.
> 
> Thank you.

I drag the window to the left to the smallest.
I tried using **Expanded widgets** but it didn't work.

![image](https://user-images.githubusercontent.com/5343265/158091856-37664608-dc2d-4675-8bc2-9943e9ac188b.png)
