### ISSUE TITLE
Shrine: motion of item from homescreen

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4435] opened 2016-06-07 22:39 UTC
Here's a movie of how the motion of the item from the home of shrine should animate: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B14F_FSUCc01emlGOWRnRkpMOVk/GoodTransition_QuickDo-v4.webm

On iOS, the item goes full screen too quickly, compared to the video.

**Comment by eseidelGoogle** [comment] 2016-06-16 16:22
More hero transitions which are unlikely to make the first gallery release. Keeping this one in the milestone for now, needs more investigation as to what exactly would be involved here.

**Comment by zoechi** [comment] 2018-12-31 08:44
Is this still an issue? (Can't check myself because of #18409)

**Comment by TahaTesser** [comment] 2020-05-21 15:38
Shrine now  is totally different than the video linked  
Since the issue is outdated for new shrine
https://gallery.flutter.dev/#/shrine

Closing the issue as non-actionable 
if you disagree please write in the comments and I will reopen it 
Thank you

**Closed by TahaTesser** 2020-05-21 15:38 UTC
Labels: f: material design, framework, team, team: gallery
