### ISSUE TITLE
There's no (easy) way to turn an image to grayscale

### ISSUE THREAD

**Issue by nicoroy2561** [flutter/flutter#51734] opened 2020-03-01 11:01 UTC
Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale ja-JP)

I've been trying many different solutions within the past few days, and I really can't figure out how to make an image (with transparent background) grayed out.
I've tried using a Container with BoxDecoration, using a Stack (with a Container with a gray image on top), using ColorFiltered, using ShaderMask..

So basically what I'm trying to achieve is the effect I would get in CSS by having an image(PNG with transparent background) and setting filter: grayscale(100%).
It turned out to be a small nightmare (something it really shouldn't be), as Flutter doesn't handle transparency on many of its BlendModes. In fact, there is a mode that does what I need (BlendMode.**saturation**), but since it doesn't handle transparency it displays a grey box around the image (this also happens with boxed widgets).
Try this code with any image that has a transparent background :
```
Image.asset("assets/image.png", color: Colors.grey,
colorBlendMode: BlendMode.saturation)
```
Then there is **srcATop**, which works in that keeps the shape of the original image, but just makes it all gray, giving a **silhouette**. Ideally what I'd need is a combination of those two modes.
Best result I got so far is using srcATop with a lower opacity gray color, which isn't of course the same as having a gray image.

Your guide on [BlendMode](https://api.flutter.dev/flutter/dart-ui/BlendMode-class.html)s suggests that you can **composite two different image sources into one**, so I thought I could use that to merge the normal image with another same image already grayed out (using srcATop) using saturation on the two. Not exactly neat since I'd have to load the image twice, but it would've done the trick. Yet, of all the widgets, **there seem not to be a single one that allows to blend two different images** (and yes I didn't want to turn to using a Canvas for that).

Unless I'm missing anything here, I'd like you to either add a way to do that (a GrayedOut widget or something similar would be nice, but it could also just be another blend mode or an optional parameter).
I'd also like to suggest, if there isn't one already, to add a BlendImages() widget that allows you to blend two different image sources easily specifying one of the BlendModes you already have.

**Comment by SpajicM** [comment] 2020-03-01 22:23
https://github.com/brendan-duncan/image/blob/master/lib/src/filter/grayscale.dart

**Comment by nicoroy2561** [comment] 2020-03-02 01:38
@SpajicM thank you. I tried my best to make it work, but still (3 hours now) for some reason it won't display any image.
I use now 
` getGrayscale(String src) async {
  ByteData imageData = await rootBundle.load(src);

  Image image = grayscale(decodePng(Uint8List.view(imageData.buffer)));

  return encodePng(image);`

and, the widget
`FutureBuilder(
                          future: getGrayscale("assets/my_png.png"),
                          builder:
                              (BuildContext context, AsyncSnapshot snapshot) {
                            if (snapshot.hasData) {
                              return Image.memory(snapshot.data);
                            }
                            return Placeholder();
                          },
                        ),`

It doesn't show anything on the screen, but yet, if I change the Image.memory to a simple Text (and use snapshot.data.toString()) I can see the values returned from the function (it is properly reading the data and applying the filter, yet the return values for some reason don't get shown by Image.memory). 

I am still convinced that if one has to spend 3 days trying to achieve such a simple effect there should be a widget in the main library for it.

**Comment by SpajicM** [comment] 2020-03-02 01:52
Are you sure using the "Image" object from the image library I linked above?

`import 'package:image/image.dart' as imageLib;`

Don't mix it up with Flutter's widget Image or dart:ui Image.

**Comment by nicoroy2561** [comment] 2020-03-02 10:18
Thank you. I tried to change the code as per your suggestion but it didn't change anything (I already had the getGrayscale() function on a separate .dart file, with only the image/image.dart import for the Image class):
```
import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:image/image.dart' as imgLib;

/// Convert the image to grayscale.
 getGrayscale(String src) async {
  ByteData imageData = await rootBundle.load(src);

  imgLib.Image image = imgLib.grayscale(imgLib.decodePng(Uint8List.view(imageData.buffer)));

  return imgLib.encodePng(image);
}

```
The other part (futurebuilder) works as per before - or rather doesn't as well? 
I'm sure I'm missing something trivial here, since you all can get to use this library no problem. I noticed that wether I apply the grayscale() or not it doesn't affect the result, so it likely is about how I pass the data back to the Image.asset function. I resolved using encodePng as simply trying to pass Image.getBytes() would result in an Exception "can't instantiate decoder". Using encodeJpg also resulted in the same (no exception thrown but nothing being displayed by Image.asset)

**Comment by TahaTesser** [comment] 2020-03-02 12:37
Hi @nicoroy2561 

Please try this easy example
### Code Sample
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: ColorFiltered(
          colorFilter: ColorFilter.mode(
            Colors.grey,
            BlendMode.saturation,
          ),
          child: Image.network('https://i.imgur.com/C5xknx8.png'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```
Thank you

**Comment by nicoroy2561** [comment] 2020-03-02 13:28
I had already tried that, to no avail since as you can see there is a grey background applied to the image:
 
![Screenshot_2020-03-02-14-23-06-412_com example image_test](https://user-images.githubusercontent.com/55353223/75680294-95b67f00-5c91-11ea-80a2-5e763bd92247.jpg)

(which isn't there in the original one:)
![C5xknx8](https://user-images.githubusercontent.com/55353223/75680393-ce565880-5c91-11ea-8671-6397b37cf3d5.png)

My issue is with images with transparent background, as is yours. I searched all over the internet and tried many different options, but there seem to be no way to make it grayscale without having a gray box displayed around it (which is ugly and clearly defeats the purpose).

**Comment by TahaTesser** [comment] 2020-03-02 14:04
Duplicate of [#12990](https://github.com/flutter/flutter/issues/12990)

**Closed by TahaTesser** 2020-03-02 14:04 UTC

**Comment by kamleshwebtech** [comment] 2020-10-23 18:16
> Thank you. I tried to change the code as per your suggestion but it didn't change anything (I already had the getGrayscale() function on a separate .dart file, with only the image/image.dart import for the Image class):
> 
> ```
> import 'dart:typed_data';
> import 'package:flutter/services.dart';
> import 'package:image/image.dart' as imgLib;
> 
> /// Convert the image to grayscale.
>  getGrayscale(String src) async {
>   ByteData imageData = await rootBundle.load(src);
> 
>   imgLib.Image image = imgLib.grayscale(imgLib.decodePng(Uint8List.view(imageData.buffer)));
> 
>   return imgLib.encodePng(image);
> }
> ```
> 
> The other part (futurebuilder) works as per before - or rather doesn't as well?
> I'm sure I'm missing something trivial here, since you all can get to use this library no problem. I noticed that wether I apply the grayscale() or not it doesn't affect the result, so it likely is about how I pass the data back to the Image.asset function. I resolved using encodePng as simply trying to pass Image.getBytes() would result in an Exception "can't instantiate decoder". Using encodeJpg also resulted in the same (no exception thrown but nothing being displayed by Image.asset)
> 
> PS I also tried using flutter clean, no changes.

I have tried but transparent png image is converted to black background color in case of storing png image into jpg image. Any suggestion?
