### ISSUE TITLE
Multiple tests timing out "Waiting for observatory port to be available"

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83941] opened 2021-06-03 20:38 UTC
Timed out on:
```
[platform_view__start_up] [STDOUT] stdout: [        ] Waiting for observatory port to be available...
[platform_view__start_up] [STDOUT] stdout: [ +156 ms] E/DartVM  (16166): sizeof(UntaggedScript) got 48, AOT_Script_InstanceSize expected 40
[platform_view__start_up] [STDOUT] stdout: [        ] E/DartVM  (16166): version=2.14.0-178.0.dev (dev) (Wed Jun 2 23:28:09 2021 -0700) on "android_arm"
```

Examples:

https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20platform_view__start_up/1426
https://ci.chromium.org/p/flutter/builders/prod/Linux%20textfield_perf__e2e_summary/1593

Started on roll https://github.com/flutter/flutter/commit/c03a75768d2c52ebd99ecdc86ac790d9c96b6634

**Comment by keyonghan** [comment] 2021-06-03 20:41
All are caused by timeout on the test step:
```
Waiting for observatory port to be available
```

**Comment by keyonghan** [comment] 2021-06-03 20:43
Related: https://github.com/flutter/flutter/issues/77193

**Comment by jmagman** [comment] 2021-06-03 20:44
Oh, you're right, I missed the blue timeout.

**Comment by jmagman** [comment] 2021-06-03 20:51
Engine roll reverted at https://github.com/flutter/flutter/pull/83942, autoroller has been paused.

**Comment by zanderso** [comment] 2021-06-03 20:54
This might need a bisect, but I am suspicious of this change from the Dart SDK roll in this Engine roll: https://dart.googlesource.com/sdk.git/+/fa5da6a944485e62f7bba5761ccbc54f0b80326e @bkonyi

**Comment by zanderso** [comment] 2021-06-03 20:55
Also /cc @rmacnak-google

**Comment by zanderso** [comment] 2021-06-03 20:56
Sorry, meant this one: https://dart.googlesource.com/sdk.git/+/a10e038f092b1177748674eaf83c52b3cbf882c3

**Comment by zanderso** [comment] 2021-06-03 20:57
Oh, I see there's already a revert merged here: https://dart-review.googlesource.com/c/sdk/+/202300. We may just need to wait for a newer Dart SDK to roll into the Engine. /cc @iskakaushik

**Comment by rmacnak-google** [comment] 2021-06-03 21:00
The broken CL caused ARM32 apps to abort at startup, so if you observe timeouts, then whichever test harness this is is failing to watch for process exit.

**Comment by iskakaushik** [comment] 2021-06-04 17:26
resumed the roller, please reopen if after the next engine roll the failures are still seen.

**Comment by iskakaushik** [comment] 2021-06-04 17:26
revert has rolled into the engine

**Closed by iskakaushik** 2021-06-04 17:26 UTC
Labels: P0, engine
