### ISSUE TITLE
Flutter web Completer don`t work

### ISSUE THREAD

**Issue by zhangwei911** [flutter/flutter#83970] opened 2021-06-04 06:01 UTC
`
1. flutter build web
2. put it into an other android project assets
3. build apk and visit it by webview
4. it invoke android http request function by js bridge(with callback)
5. when callback return data,the Completer is null
`

**Comment by TahaTesser** [comment] 2021-06-04 11:55
Hi @zhangwei911 

> flutter build web
> put it into an other android project assets
> build apk and visit it by webview

Running flutter web app inside webview in flutter release apk? 



Can you please provide your `flutter doctor -v`, a complete reproducible minimal code samples

> it invoke android http request function by js bridge(with callback)

please provide an example of this
Thank you

**Comment by zhangwei911** [comment] 2021-06-10 08:49
1.in another normal apk with webview not flutter

2.flutter doctor -v

```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.985], locale zh-CN)
    • Flutter version 2.2.0 at E:\flutter
    • Framework revision b22742018b (4 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at c:\Users\dell\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\dell\Desktop\AS_Arctic_Fox
    • ANDROID_SDK_ROOT = C:\Users\dell\AppData\Local\Android\Sdk
    • Java binary at: C:\Users\dell\Desktop\AS_Arctic_Fox\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+0-b77-7246554)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at E:\Software\ASStable
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] Android Studio
    • Android Studio at C:\Users\dell\Desktop\AS_Arctic_Fox
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Users\dell\Desktop\AS_Arctic_Fox
    • Java version OpenJDK Runtime Environment (build 11.0.9.1+0-b77-7246554)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at E:\Software\II2020
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at E:\Software\II2021
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\dell\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • STF AL10 (mobile) • 5JP0217830003366 • android-arm64  • Android 9 (API 28)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 91.0.864.41

• No issues found!

```

3.js 

```
var WebApp = {
        callbackIndex:0,
        callbackArray: new Array(),
        JSCallBack: function(i, json){
            var callBack = this.getCallback(i);
            callBack(json);
        },

        saveCallback: function(a) {
            var index = this.callbackIndex;
            this.callbackArray[index] = a;
            this.callbackIndex++;
            return index;
        },

        getCallback: function(i) {
            return this.callbackArray[i]
        },
        testFunc: function(success, failed){
            var si = this.saveCallback(success);
            var fi = this.saveCallback(failed);
            window.nativePlugin.invoke(si, fi);
        }
}
```

4.dart
```
import 'dart:async';
import 'dart:html';
import 'dart:js';
import 'dart:js_util';

import 'package:js/js.dart';

@JS()
class WebApp {
  external static invoke(void Function(dynamic res) success, void Function(dynamic err) failure);

  static Future invokeFuture() {
    Completer completer = Completer();
    invoke((res) {
      completer.complete(res);
    }, (err) {
      completer.completeError(err);
    });
    return completer.future;
  }
}
```

**Comment by TahaTesser** [comment] 2021-06-10 09:49
Hi @zhangwei911 
Firstly explain the issue what's the issue is, then provide complete reproduction steps with a complete code sample
Starting from scratch and cover all the steps required

Code snippets you provided are random, doesn't explain the process to reproduce the issue and what is expected result and actual results

**Comment by zhangwei911** [comment] 2021-06-11 01:43
An Android application that only contains WebView and a JS call. loads the flutter web application packaged in application assets through WebView. Flutter calls JS method containing callback by using completer, but null pointer exception occurs when completer.complete is executed in callback. If you don't understand, I will close this problem

**Comment by TahaTesser** [comment] 2021-06-11 07:47
Hi @zhangwei911 
Starting from scratch here what I understand (it is still not completely clear)
1. Create a Native Android app that contains a webview.
2. That native Android app makes JS call and loads Flutter web application as assets? 
3. This Flutter web has callback by using complete and that where the issue occurs?


Can you please complete an example o this native app with flutter web as assets? Also, provide Flutter app used to generate Flutter web build. You can both of these in a repository for testing

**Comment by zhangwei911** [comment] 2021-06-17 05:30
it's ok now,but i don't know why
maybe had fixed.
[https://gitee.com/swzw/jsdemo](https://gitee.com/swzw/jsdemo)

**Comment by TahaTesser** [comment] 2021-06-17 07:19
@zhangwei911 
If there is no issue anymore, I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-06-17 07:19 UTC
Labels: in triage

**Comment by zhangwei911** [comment] 2021-06-30 07:48
when i exec 'flutter build web --profile',the code like the below
```
WebApp_xuanZeFuJianFuture2: function() {
      var t1 = new P._Future($.Zone__current, type$._Future_dynamic);
      self.WebApp.xuanZeFuJian(new S.WebApp_xuanZeFuJianFuture2_closure(new P._AsyncCompleter(t1, type$._AsyncCompleter_dynamic)));
      return t1;
    },
```
after invoke,i found it`s a dart closure
i add H.convertDartClosureToJS(xxx,1),and it works;
```
WebApp_xuanZeFuJianFuture2: function() {
      var t1 = new P._Future($.Zone__current, type$._Future_dynamic);
      self.WebApp.xuanZeFuJian(H.convertDartClosureToJS(new S.WebApp_xuanZeFuJianFuture2_closure(new P._AsyncCompleter(t1, type$._AsyncCompleter_dynamic)), 1));
      return t1;
    },
```
thus,i need to know how to use convertDartClosureToJS func

**Comment by zhangwei911** [comment] 2021-07-02 01:47
allowInterop can fix my issue
