### ISSUE TITLE
VS Code Latest Dart/Flutter plugin: Failed to create server socket (OS Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.

### ISSUE THREAD

**Issue by JohnGalt1717** [flutter/flutter#60618] opened 2020-06-30 18:14 UTC
## Steps to Reproduce

I have the following launch.json:

```
    {
      "name": "Admin Flutter Web",
      "request": "launch",
      "type": "dart",
      "deviceId": "chrome",
      "program": "Admin/lib/main.dart",
      "args": ["--web-port", "51190"]
    },

```

I am specifying the port because random doesn't work when you're authenticating against an openid IdP.

This worked fine until the latest update of the dart/flutter vs code plugin.

Now it receives the above error message after a few starts/shut downs of the app. Can't find any process stuck, restart of VS Code doesn't work. Only restarting the computer does.

There are no chrome browsers in task manager etc. (Windows 10 2004 fully patched, final, not insider or anything)

netstat -a shows that the port isn't in use.

*Edit* Killing all dart.exe processes that don't seem to close fixes the problem.

## Logs

Launching lib\main.dart on Chrome in debug mode...
Failed to bind web development server:
SocketException: Failed to create server socket (OS Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.
, errno = 10048), address = localhost, port = 51190
Exited (sigterm)

```
[√] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.19.0-4.2.pre at D:\Programs\flutter
    • Framework revision 9b9b543d92 (8 days ago), 2020-06-22 12:19:28 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\jrlh\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.46.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

**Comment by iapicca** [comment] 2020-07-01 06:28
Hi @JohnGalt1717 
Following the indication of [VS Code Flutter Extension](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/Dart-Code/Dart-Code/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-01 06:28 UTC
