### ISSUE TITLE
VideoPlayer on desktop

### ISSUE THREAD

**Issue by Bonfra04** [flutter/flutter#57171] opened 2020-05-13 23:18 UTC
with IOS/Android i use chewie but on windows desktop i can't find any alternatives. if still not exist pleas add.

(sorry for grammar. i'm italian)

**Comment by stuartmorgan** [comment] 2020-05-13 23:53
Duplicate of https://github.com/flutter/flutter/issues/37673

**Closed by stuartmorgan** 2020-05-13 23:53 UTC
