### ISSUE TITLE
Support debug mode for WASM builds

### ISSUE THREAD

**Issue by Rexios80** [flutter/flutter#148850] opened 2024-05-22 11:34 UTC
### Steps to reproduce

1. Create a new project
2. Call `print(kDebugMode)`
3. Run `flutter run --debug -d chrome --wasm`
4. It prints false

### Expected results

It prints true

### Actual results

It prints false

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/foundation.dart';

void main() {
  print(kDebugMode);
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
rexios@Aarons-MBP pub_stats % flutter doctor -v
[✓] Flutter (Channel main, 3.22.0-42.0.pre.6, on macOS 14.5 23F79 darwin-arm64, locale en-US)
    • Flutter version 3.22.0-42.0.pre.6 on channel main at /Users/rexios/repos/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision 112e8b5509 (4 hours ago), 2024-05-22 09:25:21 +0200
    • Engine revision c89defa558
    • Dart version 3.5.0 (build 3.5.0-177.0.dev)
    • DevTools version 2.36.0-dev.10

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/rexios/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11609105)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (4 available)
    • Aaron’s iPhone (mobile)         • 00008130-001C35CE3A20001C • ios            • iOS 17.5.1 21F90
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 124.0.6367.208

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2024-05-22 12:23
> 3\. Run `flutter run --debug -d chrome --wasm`

@Rexios80 According to https://docs.flutter.dev/platform-integration/web/wasm#only-build-support, currently wasm has only build support and not `flutter run`, so could be that you are seeing the reported behavior.

**Comment by Rexios80** [comment] 2024-05-22 12:35
I am running the latest Flutter main commit which does support `flutter run`. Should I not report issues with using it?

**Comment by darshankawar** [comment] 2024-05-23 06:01
Thanks for the feedback. It seems the said command doesn't work in stable yet, so I thought to refer the documentation if that's the case, but I checked in master which ran the command and printed false as below:

<img width="783" alt="Screenshot 2024-05-23 at 11 29 25 AM" src="https://github.com/flutter/flutter/assets/67046386/e2dfb009-5450-48e9-bf9d-33d29ba7690f">

Keeping the issue open and labeling for team's tracking.

**Comment by Rexios80** [comment] 2024-06-02 20:31
The `--debug` flag does not seem to work for `dart2wasm` either. That is probably the root cause of this.

**Comment by mkustermann** [comment] 2024-06-04 17:36
> The --debug flag does not seem to work for dart2wasm either. That is probably the root cause of this

The Dart2Wasm compiler is only used for `--profile` / `--release` builds (just like Dart2JS). For iterative development DDC (which also compiles to JS) compiler is used.

The fact that `flutter run -d chrome` accepts the `--wasm` flag may be not intentional  /cc @yjbanov @eyebrowsoffire

**Comment by eyebrowsoffire** [comment] 2024-06-04 17:40
It is intentional. You can do `flutter run` with release builds, for example `flutter run -d chrome --release`. `--wasm` essentially implies `--release` in practice, so this is intended behavior. We may want to add an error message if someone attempts to use `--wasm` and `--debug` together, it is currently not a valid combination.

**Comment by mkustermann** [comment] 2024-06-04 17:49
> We may want to add an error message if someone attempts to use --wasm and --debug together, it is currently not a valid combination.

@eyebrowsoffire Currently `flutter run -d chrome --wasm` runs and it even claims it uses hot-reload:
```
% flutter run -d chrome --wasm
Launching lib/main.dart on Chrome in debug mode...
Compiling lib/main.dart for the Web...                             798ms
✓ Built build/web

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
```
That cannot be intentional. Either it should warn/error on the `--wasm` flag or it should run in release mode with wasm and not claim it supports hot-reload

**Comment by Rexios80** [comment] 2024-06-04 17:56
Are we saying that there is no way to compile to WASM in such a way that kDebugMode would be true and that is intentional?

**Comment by eyebrowsoffire** [comment] 2024-06-04 18:15
> That cannot be intentional. Either it should warn/error on the --wasm flag or it should run in release mode with wasm and not claim it supports hot-reload

It is hot restart, not hot reload, and it does actually work. If you make a change to the code and then press "r", it will recompile the code and send a signal to chrome to reload, and it will do so. This is the existing behavior for `flutter build web --release`, which uses dart2js.

>Are we saying that there is no way to compile to WASM in such a way that kDebugMode would be true and that is intentional?

Yes. Wasm compilation does not support debug mode currently.

**Comment by Rexios80** [comment] 2024-06-10 12:46
Is there an existing issue to support debug mode in WASM builds or should we repurpose this one to be it?

**Comment by Rexios80** [comment] 2024-07-11 20:28
@eyebrowsoffire sorry for the ping but I would like to clarify this if possible. Should we create an issue to support debug mode in WASM builds or is there already an existing issue for that?

**Comment by eyebrowsoffire** [comment] 2024-07-11 20:34
Let's repurpose this bug to track that.

**Comment by Rexios80** [comment] 2024-07-23 20:10
@eyebrowsoffire What is the reason we can't just make `kDebugMode` true with `flutter run --wasm` and false with `flutter run --wasm --release`? Are there bigger implications that I'm not seeing? The biggest use-case for this in my projects is using Firebase emulators when `kDebugMode` is true, which makes testing locally with WASM really annoying.

**Comment by eyebrowsoffire** [comment] 2024-07-23 20:36
We can do as you're suggesting, I just haven't implemented it yet. The reason it is the way it is right now is just mostly implementation warts. I plan on at least making it so that `kDebugMode` is true here, even if you won't get a full "debug mode" experience (attaching devtools, etc).

**Comment by eyebrowsoffire** [comment] 2024-07-25 22:10
Fixed with https://github.com/flutter/flutter/issues/148850

**Comment by Rexios80** [comment] 2024-07-26 01:17
Confirmed `kDebugMode` is true when running `flutter run -d chrome --wasm` on Flutter master

**Closed** 2024-07-26 01:18 UTC
Labels: platform-web, has reproducible steps, P2, e: wasm, team-web, triaged-web, found in release: 3.22
