### ISSUE TITLE
shell.run() is causing applications crash or hang-up.

### ISSUE THREAD

**Issue by unoravi** [flutter/flutter#78414] opened 2021-03-17 10:18 UTC
To execute shell commands on desktop platforms, I am using process_run dependency. Sample code as shown below.

```
var shell = Shell();
var res = await shell.run("ls");
print(res.outLines);
```

Application hangup or crash at the time of execution of second line. Please provide a latest solution for this issue. Here is the flutter doctor -v

```
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.1.0-10.0.pre at /home/ravi/flutter
    • Framework revision cc9b78fc5c (3 weeks ago), 2021-02-25 13:26:03 -0800
    • Engine revision a252ec09b7
    • Dart version 2.13.0 (build 2.13.0-77.0.dev)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.146

! Doctor found issues in 2 categories.
```

Thanks

**Comment by pedromassangocode** [comment] 2021-03-17 10:32
Hi @unoravi 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/tekartik/process_run.dart).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-17 10:32 UTC
Labels: in triage
