### ISSUE TITLE
Flutter package does not support iOS 32 bit out of the box (iPhone 5)

### ISSUE THREAD

**Issue by uKL** [flutter/flutter#7923] opened 2017-02-07 12:35 UTC
## Steps to Reproduce

Trying to compile Flutter application which uses FlutterViewController for iPhone5 (ARM 32 bit)

## Logs

Run your application with `flutter run` and attach all the log output.

```
pawelurban@MacBook-Pro-4 ~/w/Flutter-Demo> ../flutter/bin/flutter run  
Launching lib/main.dart on iPhone (Test) in debug mode...
2017-02-07 13:31:00.989 ios-deploy[84260:11111874] [ !! ] Error 0xe8000087: This application does not support this device's CPU type. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)
Could not install build/ios/Release-iphoneos/Runner.app on 116fe6f14b81cb490ebab9c2f150d45810a740ed.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcodeproj

Error launching application on iPhone (Test).
```

## Flutter Doctor

```
pawelurban@MacBook-Pro-4 ~/w/Flutter-Demo> ../flutter/bin/flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/pawelurban/workspace/flutter
    • Framework revision 06f879b57e (6 hours ago), 2017-02-06 22:15:36
    • Engine revision cbf49d0652
    • Tools Dart version 1.22.0-dev.10.3

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/pawelurban/Library/Android/sdk
    • Platform android-25, build-tools 25.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_77-b03)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.0

[✓] IntelliJ IDEA Community Edition (version 2016.3.4)
    • Dart plugin version 163.13137
    • Flutter plugin version 0.1.9.1

[✓] Connected devices
    • iPhone (Test) • 116fe6f14b81cb490ebab9c2f150d45810a740ed • ios • iOS 10.0.2 (14A456)
```

**Comment by eseidelGoogle** [comment] 2017-02-07 17:50
I think this is a duplicate of https://github.com/flutter/flutter/issues/2089?

**Comment by uKL** [comment] 2017-02-07 17:51
Correct, would you mind closing it?
W dniu wt., 7.02.2017 o 18:50 Eric Seidel <notifications@github.com>
napisał(a):

**Closed** 2017-02-07 17:53 UTC
Labels: ⌺‬ platform-ios
