### ISSUE TITLE
"Flutter plugin not installed" mistakenly reported by Doctor for IntelliJ IDEA

### ISSUE THREAD

**Issue by thomasweitzel** [flutter/flutter#46702] opened 2019-12-10 17:43 UTC
## Steps to Reproduce

1. Install `flutter_linux_v1.9.1+hotfix.6-stable.tar.xz`
2. Install Dart & Flutter Plugins in IDEA-U, restart
3. Run `flutter -v doctor`

## System information

- OS `Ubuntu 16.04.6 LTS`
- IntelliJ IDEA-U `193.5233.102` (`2019.3`)

## Installed IDEA-U plugins

![ideau-plugins](https://user-images.githubusercontent.com/3513156/70553442-6ce38980-1b7b-11ea-8c50-355979c11db3.png)

## What I tried

- reinstalled `flutter`
- reinstalled IntelliJ IDEA plugins
- restarted IntelliJ IDEA (with/without invalidate caches)
- restarted computer

The only thing I can think of is that my Jetbrains applications are installed under `/opt/jetbrains`, which is not the standard location.

## Logs

```
$ flutter -v doctor
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /opt/google/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/thomy/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/jetbrains/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/jetbrains/apps/AndroidStudio/ch-0/191.6010548
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /opt/jetbrains/apps/IDEA-U/ch-0/193.5233.102
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.40.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by thomasweitzel** [comment] 2019-12-14 10:32
This issue still persists with the new version `1.12.13+hotfix.5`:

```
$ flutter -v doctor
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /opt/google/flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/thomy/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/jetbrains/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/jetbrains/apps/AndroidStudio/ch-0/191.6010548
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /opt/jetbrains/apps/IDEA-U/ch-0/193.5233.102
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.41.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by georgeherby** [comment] 2019-12-16 13:55
I am getting the same on Mac, on beta 1.12/13+hotfix.6
```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.6 18G103, locale
    en-GB)
    • Flutter version 1.12.13+hotfix.6 at /Users/george/development/flutter
    • Framework revision 18cd7a3601 (5 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/george/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/george/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/george/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android
      Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Users/george/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 29A27947-BE61-48DC-AA92-D509BD53E3B4 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.

```

**Comment by georgeherby** [comment] 2019-12-16 14:09
So I downgraded to 2019.2.4 with Dart 192.7761 and Flutter 42.1.3 even though doctor reported and the doctor gave the green tick - but gave different versions to what was installed:
```
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Users/george/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 37.1.4
    • Dart plugin version 192.5728.12
```
Upgraded again to 2019.3 and it failed
```
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Users/george/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
```

**Comment by Articdive** [comment] 2020-01-14 17:58
Also having this problem on Windows using IDEA-U,
```
Microsoft Windows [Version 10.0.18363.535]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Lukas>flutter doctor -v
[√] Flutter (Channel master, v1.13.9-pre.82, on Microsoft Windows [Version 10.0.18363.535], locale en-GB)
    • Flutter version 1.13.9-pre.82 at D:\flutter
    • Framework revision 68d0c89ffc (2 hours ago), 2020-01-14 16:18:48 +0000
    • Engine revision fd269f60bf
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 28c335d5a2)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\android-sdk
    • Java binary at: C:\Users\Lukas\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\Lukas\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Users\Lukas\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.5662.53
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Lukas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by tnaseem** [comment] 2020-01-23 23:58
Just a heads up:

This also happens for me to with IntelliJ 2019.3.2 - build 193.6015.39.

When doing a verbose output of _flutter doctor_ I can see that it's looking in the following folder for the plugins:

`<User Folder>\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.6015.39`

However, it appears that the plugins are actually being installed in:

`<User Folder>\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.6015.39.plugins`

**Comment by stefandevo** [comment] 2020-02-10 22:23
Any news on this, it still exists!

**Comment by daharper** [comment] 2020-02-15 04:19
Still happening for me too

**Comment by thomasweitzel** [comment] 2020-02-15 11:25
For the latest versions of Flutter 1.12.13+hotfix.8, Jetbrains IDEA-U 193.6494.35 (219.3.3) and Flutter plugin, nothing has changed.

**Comment by brian-daley** [comment] 2020-03-14 18:18
Issue persists:

[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.14.6 at /Users/daleyb2/dev/flutter
    • Framework revision fabeb2a16f (7 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Users/XXXXX/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

**Comment by christopherfujino** [comment] 2020-03-17 21:09
possibly related to https://github.com/flutter/flutter/issues/48568

**Comment by christopherfujino** [comment] 2020-03-17 21:13
Thanks for filing this! I am closing this as a duplicate of https://github.com/flutter/flutter/issues/36414, please follow there for updates.

**Closed by christopherfujino** 2020-03-17 21:13 UTC
Labels: t: flutter doctor, tool
