### ISSUE TITLE
iOS App crash after playing 4 or 5 times Camara snapshot

### ISSUE THREAD

**Issue by patricktslee** [flutter/flutter#26850] opened 2019-01-21 11:12 UTC
Hi All,

I tried to test the App on iPhone 6s plus device (Not emulator) to capture the photo.  When I tap the 'User camera' to capture image more than 4 times.  The App is frozen and crashed.  On the Xcode log for the last message is

`2019-01-20 21:51:46.319619+0800 Runner[15854:3676008] [Snapshotting] Snapshotting a view (0x10589e000, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.
`

Here is Flutter code to capture image by camera.  Here is part of my code.

```dart
  void _getImage(BuildContext context, ImageSource source) {
    ImagePicker.pickImage(source: source, maxWidth: 400.0).then((File image) {
      setState(() {
        _imageFile = image;
      });
      widget.setImage(image);
      Navigator.pop(context);
    });
  }

```

```dart
              FlatButton(
                textColor: Theme.of(context).primaryColor,
                child: Text('Use Camera'),
                onPressed: () {
                  _getImage(context, ImageSource.camera);
                },
              ),

```

Thanks

Patrick Lee

**Comment by Errichamonda** [comment] 2019-01-21 13:01
I'm having the same issue, but it crashes when I select the photo that i've just taken. In Android works fine. It looks like iOS might be killing the application.

**Comment by kangwang1988** [comment] 2019-01-22 10:56
@patricktslee  @Errichamonda 
`flutter doctor -v` and a minimal demo project which can help reproduce it would help.

**Comment by patricktslee** [comment] 2019-01-23 14:10
Hi Kangwang1988,

Here is flutter doctor -v and simple demo code.

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-HK)
    • Flutter version 1.0.0 at /Users/patrick/flutter/flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/patrick/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4155.35

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • iPhone    • f61f9a391b3eb2f9596ef680ad4fd2ea3e201591 • ios • iOS 12.1.2
    • iPhone XR • D3A72D19-84DD-4921-B264-F45FE1D928B1     • ios • iOS 12.1 (simulator)

• No issues found!
```

```
import 'package:flutter/material.dart';
import 'dart:io';

import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  File _imageFile;

  void _getImage(BuildContext context, ImageSource source) {
    ImagePicker.pickImage(source: source, maxWidth: 400.0).then((File image) {
      setState(() {
        _imageFile = image;
      });
      Navigator.pop(context);
    });
  }

  void _openImagePicker(BuildContext context) {
    showModalBottomSheet(
        context: context,
        builder: (BuildContext context) {
          return Container(
            height: 150.0,
            padding: EdgeInsets.all(10.0),
            child: Column(children: [
              Text(
                'Pick an Image',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              SizedBox(
                height: 10.0,
              ),
              FlatButton(
                textColor: Theme.of(context).primaryColor,
                child: Text('Use Camera'),
                onPressed: () {
                  _getImage(context, ImageSource.camera);
                },
              ),
              FlatButton(
                textColor: Theme.of(context).primaryColor,
                child: Text('Use Gallery'),
                onPressed: () {
                  _getImage(context, ImageSource.gallery);
                },
              )
            ]),
          );
        });
  }

  @override
  Widget build(BuildContext context) {
    final buttonColor = Theme.of(context).primaryColor;
    Widget previewImage = Text('Please select an image.');
    if (_imageFile != null) {
      previewImage = Image.file(
        _imageFile,
        fit: BoxFit.cover,
        height: 300.0,
        width: MediaQuery.of(context).size.width,
        alignment: Alignment.topCenter,
      );
    }
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            OutlineButton(
              borderSide: BorderSide(
                color: buttonColor,
                width: 2.0,
              ),
              onPressed: () {
                _openImagePicker(context);
              },
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Icon(
                    Icons.camera_alt,
                    color: buttonColor,
                  ),
                  SizedBox(
                    width: 5.0,
                  ),
                  Text(
                    'Add Image',
                    style: TextStyle(color: buttonColor),
                  )
                ],
              ),
            ),
            SizedBox(height: 10.0),
            previewImage
          ],
        ),
      ),
    );
  }
}
```

Thanks
Patrick Lee

**Comment by cyanglaz** [comment] 2019-04-26 00:31
@patricktslee Does this issue still exist? I tried your example app and couldn't reproduce the crash.

**Comment by chrise1967** [comment] 2019-05-10 06:41
I confirm I’m experiencing the same problem on iPhone 6s. I find once it crashes after taking a phone it will then immediately crash trying it again. I have found that closing other running apps will allow the app to take photos however it will crash again after 4 or 5 photos.

**Closed** 2019-05-22 22:06 UTC
Labels: p: first party, p: image_picker, plugin, severe: crash, waiting for customer response, ⌺‬ platform-ios
