### ISSUE TITLE
type 'BorderRadiusDirectional' is not a subtype of type 'BorderRadius?' in type cast

### ISSUE THREAD

**Issue by Abdelazeem777** [flutter/flutter#88349] opened 2021-08-17 11:33 UTC
# flutter doctor

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-EG)
    • Flutter version 2.2.3 at /Users/user/Desktop/flutterSDK1/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 64F083A4-D5B9-4850-9D88-3B14DC620737 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

```
════════ Exception caught by rendering library ═════════════════════════════════
The following _CastError was thrown during paint():
type 'BorderRadiusDirectional' is not a subtype of type 'BorderRadius?' in type cast

The relevant error-causing widget was
Container
lib/…/tester_home_tab/tester_home_tab_view.dart:139
When the exception was thrown, this was the stack
#0      _BoxDecorationPainter.paint
package:flutter/…/painting/box_decoration.dart:488
#1      RenderDecoratedBox.paint
package:flutter/…/rendering/proxy_box.dart:2143
#2      RenderObject._paintWithContext
package:flutter/…/rendering/object.dart:2317
#3      PaintingContext.paintChild
package:flutter/…/rendering/object.dart:187
#4      RenderProxyBoxMixin.paint
package:flutter/…/rendering/proxy_box.dart:140
```

# My code 

```
Container(
          decoration: BoxDecoration(
            borderRadius: BorderRadiusDirectional.horizontal(
                    start: Radius.circular(50.0),
                  ),
          ),
)
```

## Bug location

![Bug location](https://user-images.githubusercontent.com/30933932/129717828-c054661e-0289-47ba-96fd-4c5d261f0faf.png)

**Comment by maheshmnj** [comment] 2021-08-17 13:25
looks like a duplicate of https://github.com/flutter/flutter/issues/88039

**Comment by TahaTesser** [comment] 2021-08-17 13:26
closing as duplicate of https://github.com/flutter/flutter/issues/88039

**Closed by TahaTesser** 2021-08-17 13:26 UTC
Labels: in triage
