### ISSUE TITLE
[path_provider] Problem with archive on iOS

### ISSUE THREAD

**Issue by yoman07** [flutter/flutter#59385] opened 2020-06-13 05:31 UTC
## Steps to Reproduce

1.  Use Flutter 1.17.3 on existing iOS app with Swift
2. Add `path_provider`.

**Expected results:** 
App should archive successfully 

**Actual results:** 

```
Ld /Users/******/Library/Developer/Xcode/DerivedData/AppName-gfrzygeyshuyopebtymifixfwmlh/Build/Intermediates.noindex/ArchiveIntermediates/AppNameRelease/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/path_provider.build/Objects-normal/armv7/Binary/path_provider normal armv7 (in target 'path_provider' from project 'Pods')
    cd /Users/******/Development/Clients/idea/AppName/AppName_ios/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target armv7-apple-ios8.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk -L/Users/**/Library/Developer/Xcode/DerivedData/AppName-gfrzygeyshuyopebtymifixfwmlh/Build/Intermediates.noindex/ArchiveIntermediates/AppNameRelease/BuildProductsPath/Release-iphoneos/path_provider -F/Users/******/Library/Developer/Xcode/DerivedData/AppName-gfrzygeyshuyopebtymifixfwmlh/Build/Intermediates.noindex/ArchiveIntermediates/AppNameRelease/BuildProductsPath/Release-iphoneos/path_provider -F/Users/******/Development/Clients/idea/AppName/AppName_ios/Pods/../../AppName_flutter/.ios/Flutter/engine -filelist /Users/******/Library/Developer/Xcode/DerivedData/AppName-gfrzygeyshuyopebtymifixfwmlh/Build/Intermediates.noindex/ArchiveIntermediates/AppNameRelease/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/path_provider.build/Objects-normal/armv7/path_provider.LinkFileList -install_name @rpath/path_provider.framework/path_provider -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/******/Library/Developer/Xcode/DerivedData/AppName-gfrzygeyshuyopebtymifixfwmlh/Build/Intermediates.noindex/ArchiveIntermediates/AppNameRelease/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/path_provider.build/Objects-normal/armv7/path_provider_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/******/Library/Developer/Xcode/DerivedData/AppName-gfrzygeyshuyopebtymifixfwmlh/Build/Intermediates.noindex/ArchiveIntermediates/AppNameRelease/BuildProductsPath/Release-iphoneos/path_provider -fobjc-arc -fobjc-link-runtime -framework Flutter -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/******/Library/Developer/Xcode/DerivedData/AppName-gfrzygeyshuyopebtymifixfwmlh/Build/Intermediates.noindex/ArchiveIntermediates/AppNameRelease/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/path_provider.build/Objects-normal/armv7/path_provider_dependency_info.dat -o /Users/******/Library/Developer/Xcode/DerivedData/AppName-gfrzygeyshuyopebtymifixfwmlh/Build/Intermediates.noindex/ArchiveIntermediates/AppNameRelease/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/path_provider.build/Objects-normal/armv7/Binary/path_provider

ld: bitcode bundle could not be generated because '/Users/******/Development/Clients/idea/AppName/AppName_flutter/.ios/Flutter/engine/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/******/Development/Clients/idea/AppName/AppName_flutter/.ios/Flutter/engine/Flutter.framework/Flutter' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
If I remove `path_provider` everything is building correctly
<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.4 19E266, locale en-PL)
    • Flutter version 1.17.3 at /Users/****/Development/flutter
    • Framework revision b041144f83 (9 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/****/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • iPhone 11 Pro     • 374CBC71-CC80-4BA5-8E0E-F8906ADB6689 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • iPhone 11 Pro Max • DF82D292-36B1-45A3-AE61-CF41ACC85BF3 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator
```

</details>

**Comment by TahaTesser** [comment] 2020-06-15 09:46
Issue exist when using `path_provider: ^1.6.10` in existing app when building archive 
it's work fine when using normal Flutter project and building archive 

```
...flutter_module/.ios/Flutter/engine/Flutter.framework/Flutter' was built without full bitcode.
lutter_module/.ios/Flutter/engine/Flutter.framework/Flutter' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-0.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision d9653445f4 (5 days ago), 2020-06-09 18:43:03 -0400
    • Engine revision e8c13aa012
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 5c1376615e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.97

• No issues found!
``` 

</details>

**Comment by jmagman** [comment] 2020-06-18 22:58
Duplicate of #48092, see https://github.com/flutter/flutter/issues/48092#issuecomment-577345215

**Closed by jmagman** 2020-06-18 22:58 UTC
Labels: a: build, a: existing-apps, found in release: 1.20, has reproducible steps, p: first party, p: path_provider, platform-ios, plugin, severe: crash
