### ISSUE TITLE
If Flutter is UI builder for iOS and Android but why don't you build IDE Studio for that?

### ISSUE THREAD

**Issue by williamgh2019** [flutter/flutter#65681] opened 2020-09-12 08:04 UTC
I am new to Flutter and I read a lot about Flutter and it really assume UI.

The code is really well.

Is it possible to create IDE Studio for Flutter in the future?

I mean Flutter should has an IDE Studio for drag and drop UI for designer and the code is auto generate a long the way and we can click on any action components to coding action such button, image, or any part we want to coding action.

Thanks.

**Comment by iapicca** [comment] 2020-09-12 09:39
quote from https://github.com/flutter/flutter/issues/60001#issuecomment-653947452

> We have no plans at present to create a whole new IDE for Flutter; Android
> Studio provides everything that Flutter needs in terms of IntelliJ-based
> IDEs.

**Comment by williamgh2019** [comment] 2020-09-12 09:56
> quote from [#60001 (comment)](https://github.com/flutter/flutter/issues/60001#issuecomment-653947452)
> 
> > We have no plans at present to create a whole new IDE for Flutter; Android
> > Studio provides everything that Flutter needs in terms of IntelliJ-based
> > IDEs.

Hmmm... Thanks

**Comment by Abhishek01039** [comment] 2020-09-12 15:47
Hi @williamgh2019 
VScode is also doing a great job for flutter development which is a lightweight code editor backed by Microsoft.

**Comment by PixelToast** [comment] 2020-09-12 16:29
Duplicate of #60001

I love the idea but so far we have no plans of building an IDE in Flutter 😢

**Closed by PixelToast** 2020-09-12 16:29 UTC
