### ISSUE TITLE
Android studio does not recognize flutter plugin java source code.

### ISSUE THREAD

**Issue by HoyoShaw** [flutter/flutter#33491] opened 2019-05-29 04:05 UTC
## Steps to Reproduce

use this command to create a flutter plugin project:
1. `flutter create --org com.hoyo.example --template=plugin install`
2. import the project to AS(3.4.1)

The AS can NOT recognize java source code,even though the source code exists in the folder.
![image](https://user-images.githubusercontent.com/3354115/58528588-ac630d80-8209-11e9-82de-0237a0978595.png)
![image](https://user-images.githubusercontent.com/3354115/58528607-ca307280-8209-11e9-8162-a6a3be5fba8f.png)

## Logs

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.1 18B75, locale zh-Hans-HK)
    • Flutter version 1.5.4-hotfix.2 at /Users/xiaohongyao/Work/flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xiaohongyao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.2.2
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

```

**Comment by iapicca** [comment] 2019-10-09 11:00
Hi @HoyoShaw 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your  new `flutter doctor -v`?
Thank you

**Comment by iapicca** [comment] 2019-11-08 11:15
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 11:15 UTC
Labels: waiting for customer response

**Comment by Blasanka** [comment] 2020-02-05 08:30
I just created a new Flutter plugin by following doc and my Flutter version is the latest one upto now(stable). I did everything even invalidate cache and restart and system restart also. But still the AS did not identifieng plugin source.  Here is a screenshot:

![source not recognizing flutter plugin](https://user-images.githubusercontent.com/7420109/73824227-c97fbf80-481f-11ea-94eb-8b2b941ba19a.jpg)

I know that I can add lib manually to AS but is that the expected behaviour?

**Comment by Blasanka** [comment] 2020-02-05 08:36
Duplicate of #https://github.com/flutter/flutter/issues/19830

**Comment by iapicca** [comment] 2020-02-06 09:31
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
