### ISSUE TITLE
Flutter not rendering text after sitting idle 

### ISSUE THREAD

**Issue by dukemike** [flutter/flutter#67778] opened 2020-10-09 22:20 UTC
refs #57676
refs #55969
refs #64558

Our app uses flutter_background_fetch to send queued data to our API in the background.

We see missing image assets, icons and text on a regular basis. Force closing the app and restarting always fixes the issue.

[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.22.0 at /Users/mikerevoir/fvm/versions/stable
    • Framework revision d408d302e2 (10 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mikerevoir/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by iapicca** [comment] 2020-10-11 08:45
@dukemike 
ccan you provide a minimal reproducible code sample 
that doesn't rely on 3rd party plugins like [background_fetch](https://pub.dev/packages/background_fetch)

if you believe the issue is caused by said plugin I recommend you to open an issue in the dedicated [github](https://github.com/transistorsoft/flutter_background_fetch/issues)

**Comment by darshankawar** [comment] 2020-10-12 09:01
@dukemike 
Please provide a code sample as requested above that shows the issue you are facing.
Thanks.

**Comment by dukemike** [comment] 2020-10-12 12:54
@darshankawar unfortunately I'm not able to reproduce the issue at will. I don't remember if this issue started to occur before or after adding that plugin.

**Comment by darshankawar** [comment] 2020-10-13 06:29
@dukemike we'll atleast need reproducible use case that could possibly show the issue you are facing.

**Comment by dnfield** [comment] 2020-10-20 07:31
This is almost certainly a duplicate of https://github.com/flutter/flutter/issues/64558

**Comment by dukemike** [comment] 2020-10-20 13:00
@dnfield Completely agree. We received one crash log on iOS that showed that the app was attempting to make a metal call while it was in the background.

**Comment by darshankawar** [comment] 2020-10-20 13:17
Closing this as duplicate of [64558](https://github.com/flutter/flutter/issues/64558) per [this](https://github.com/flutter/flutter/issues/67778#issuecomment-712654792) comment.

**Closed by darshankawar** 2020-10-20 13:17 UTC
Labels: in triage
