### ISSUE TITLE
StatefulWidget inside DefaultTabController <-- TabBarView, re-initState when showDialog

### ISSUE THREAD

**Issue by kaquay** [flutter/flutter#12398] opened 2017-10-04 08:47 UTC
the StatefulWidget call initState when dialog show or dismiss( touch outside). I cannot pop to dismiss Dialog also ( Another exception was thrown: Looking up a deactivated widget's ancestor is unsafe.)

**Comment by sethladd** [comment] 2017-10-04 16:06
Thanks for the feedback!

Is the issue that initState is being called, when you don't expect it to be called?

**Comment by kaquay** [comment] 2017-10-05 04:53
yes. I expect that initState just call one time .

**Comment by Hixie** [comment] 2018-05-24 19:17
Can you attach some sample code to explain what you mean? I'm not really sure I follow what the problem is.

**Comment by kaquay** [comment] 2018-05-25 04:49
thank for your attention, it's has been fixed by using static globalKey

**Comment by frey1esm** [comment] 2018-07-06 12:13
@kaquay Could you show your code, then close the issue if it's resolved.

**Closed** 2018-07-06 12:15 UTC
