### ISSUE TITLE
Devices are detected by Vs code and Android Studio but running failed.

### ISSUE THREAD

**Issue by AurelAgbodoyetin** [flutter/flutter#39990] opened 2019-09-06 17:24 UTC
## Steps to Reproduce

1. ...Both Android Studio and Vs Code detect my devices
2. ... When a start running, i see "Resolving dependencies" and then error like below

## command
```
flutter run --machine --target lib\main.dart -d 034900986S002500 --track-widget-creation --start-paused
```
## exception
```
String: Exit code 1 from: C:\sdk\Android\Sdk\platform-tools\adb.exe -s 034900986S002500 shell -x logcat -v time -t 1
```

```
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:375:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:297:10)
#2      AndroidDevice.runAdbCheckedSync (package:flutter_tools/src/android/android_device.dart:180:12)
#3      AndroidDevice.lastLogcatTimestamp (package:flutter_tools/src/android/android_device.dart:571:27)
#4      _AdbLogReader._start (package:flutter_tools/src/android/android_device.dart:751:41)
#5      _runGuarded (dart:async/stream_controller.dart:805:24)
#6      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
#7      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#8      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#9      FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:325:38)
#10     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:368:5)
<asynchronous suspension>
#11     HotRunner.run (package:flutter_tools/src/run_hot.dart:251:39)
<asynchronous suspension>
#12     AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:447:23)
#13     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:507:26)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#20     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:887:20)
#21     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:505:15)
<asynchronous suspension>
#22     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:441:12)
<asynchronous suspension>
#23     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:329:38)
<asynchronous suspension>
#24     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#25     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#32     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#33     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#34     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#41     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#42     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#43     new Future.sync (dart:async/future.dart:224:31)
#44     CommandRunner.run (package:args/command_runner.dart:112:14)
#45     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#46     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#47     _rootRun (dart:async/zone.dart:1124:13)
#48     _CustomZone.run (dart:async/zone.dart:1021:19)
#49     _runZoned (dart:async/zone.dart:1516:10)
#50     runZoned (dart:async/zone.dart:1500:12)
#51     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#52     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#53     _rootRun (dart:async/zone.dart:1124:13)
#54     _CustomZone.run (dart:async/zone.dart:1021:19)
#55     _runZoned (dart:async/zone.dart:1516:10)
#56     runZoned (dart:async/zone.dart:1463:12)
#57     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#58     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#59     run (package:flutter_tools/runner.dart:51:10)
#60     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#61     main (file:///E:/SDK/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#62     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [version 10.0.18362.295], locale fr-BJ)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\sdk\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\sdk\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.38.0)
    • VS Code at C:\Users\Aurel Agbodoyetin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • TECNO KA7O • 034900986S002500 • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [version 10.0.18362.295], locale fr-BJ)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\sdk\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\sdk\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.38.0)
    • VS Code at C:\Users\Aurel Agbodoyetin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by AurelAgbodoyetin** [comment] 2019-09-06 18:16
The problem is already solved
In fact launch.json file was misconfigured(I think)
It's content by default was
` 
"name": "Dart",
            "program": "bin/main.dart",
            "request": "launch",
            "type": "dart"
`
and I changed it to
`
 "name": "Flutter",
            "type": "dart",
            "request": "launch"
`
Is it the best way to fix the problem ??

**Comment by DanTup** [comment] 2019-10-24 08:44
It's definitely correct to remove `"program": "bin/main.dart"` for a Flutter project, as that's not where the entry point is. When creating launch configurations, there are snippets for both Dart and Flutter, and the Flutter one should not insert `bin/main.dart`.

I think that might be a red herring though - I don't it's related to this error. Android Studio doesn't use the VS Code `launch.json` and the command above shows that it was already using `lib\main.dart`:

```
flutter run --machine --target lib\main.dart 
```

And if you pass the wrong entry point to Flutter, the failure usually looks like this:

![Screenshot 2019-10-24 at 9 38 02 am](https://user-images.githubusercontent.com/1078012/67468199-fe398380-f641-11e9-8e88-797a6f448e72.png)

The error shows that a call to `logcat` failed. This shouldn't be impacted by the entry point, and might be a connectivity issue with the device (perhaps the cable wasn't inserted fully and it was connecting/disconnecting at the time?).

Have you seen it since? Can you reproduce it on demand?

**Comment by Hixie** [comment] 2019-12-18 00:41
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by Hixie** 2019-12-18 00:41 UTC
Labels: t: gradle, tool, waiting for customer response
