### ISSUE TITLE
Empty space on PopupMenuButton

### ISSUE THREAD

**Issue by edwin-alvarez** [flutter/flutter#58873] opened 2020-06-06 17:39 UTC
![image](https://user-images.githubusercontent.com/5774873/83950719-bc7cd800-a7e1-11ea-8888-6b9b1fc671fd.png)

please provide the option to remove this empty space at the beginning and end of PopupMenuButton

  Widget _offsetPopup() => PopupMenuButton<int>(
        itemBuilder: (context) => [
          PopupMenuItem(
            value: 1,
            child: Text(
              'Delete',
              style: TextStyle(color: Colors.black),
            ),
          ),
        ],
        elevation: 7,
        padding: EdgeInsets.symmetric(horizontal: 0),
        child: Container(
          height: 20,
          width: 20,
          child: Icon(Icons.more_vert),
        ),
        offset: Offset(0, 40),
        onSelected: (result) {
          // confirmDeletePerson();
        },
      );

**Comment by TahaTesser** [comment] 2020-06-08 09:36
Custom padding options are needed
Closing as duplicate of https://github.com/flutter/flutter/issues/57110

**Closed by TahaTesser** 2020-06-08 09:36 UTC

**Comment by kinton** [comment] 2020-06-16 18:08
@TahaTesser hello! So there no way to rid of this except modifying popupMenuButton?

**Comment by edwin-alvarez** [comment] 2020-06-16 18:59
Looks like there is not option. @TahaTesser. Can this be re open, looks like it is a common request.

**Comment by TahaTesser** [comment] 2020-06-17 10:33
@kinton  @edwin-alvarez 
https://github.com/flutter/flutter/issues/57110 this issue already raised it, need for custom padding. There is no  other option as far as i know
