### ISSUE TITLE
 Exception caught by scheduler library 

### ISSUE THREAD

**Issue by chiggosVikash** [flutter/flutter#97520] opened 2022-01-31 12:49 UTC
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 822 pos 12: 'elapsedInSeconds >= 0.0': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
![Screenshot from 2022-01-31 18-16-33](https://user-images.githubusercontent.com/98211278/151796410-ec0c3f75-6037-4016-ba24-bfb1c879f20d.png)

**Comment by danagbemava-nc** [comment] 2022-01-31 13:43
Hi @chiggosVikash, when filing an issue it is important that you provide all/most of the information that is provided in the issue template. 
Your error message alone is not enough to tell what the issue is or why it happened. 

I'm going to close this issue for now. But if you do run into any more issues in the future
- check public forums first to see if there's a solution
- check if there are any similar issues in this repo
- file an issue if any of the above is false and provide all the relevant information. 


Thank you

**Closed by danagbemava-nc** 2022-01-31 13:43 UTC
Labels: in triage
