### ISSUE TITLE
Flutter 1.17.5 keeps changing to unexisting version v1.17.0-4.0.pre.9

### ISSUE THREAD

**Issue by edgarfroes** [flutter/flutter#85655] opened 2021-06-30 21:43 UTC
I run Flutter 1.17.5 with `fvm` to switch between versions. A few hours ago I switched from 2.2.2 to 1.17.5, and Flutter suddenly started to change the version to `v1.17.0-4.0.pre.9` (currently an unexistent tag). I can checkout succesfully to 1.22.X onwards, but 1.17.5 downwards won't work. I though this was a problem with fvm, so I downloaded and installed Flutter directly from the official SDK pages and ran `flutter doctor` and it changes automatically to `v1.17.0-4.0.pre.9`. I noticed the file `version` in the root folder of Flutter is downloaded with the value `1.17.5`, and, as soon as I run `flutter doctor` or `flutter --version`, it changes to `v1.17.0-4.0.pre.9`.

## Steps to Reproduce

1. Download, unzip and add to path the version `1.17.5` available here: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_1.17.5-stable.zip
2. Run `flutter doctor` to download and install dependencies.
3. The displayed version should wrongly be `v1.17.0-4.0.pre.9` instead of `v1.17.5`

## Logs

<details>
<summary>Logs</summary>

```
```

[✓] Flutter (Channel stable, v1.17.0-4.0.pre.9, on macOS 11.4 20F71, locale pt-BR)
    • Flutter version 1.17.0-4.0.pre.9 at /Users/foo/fvm/versions/1.17.5
    • Framework revision 8af6b2f038 (1 year ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/foo/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

! Doctor found issues in 2 categories.

```
```

</details>

**Comment by TahaTesser** [comment] 2021-07-01 12:28
Hi @edgarfroes 
Unfortunately, the version you're using is outdated and is no longer supported, it's not feasible to provide any bug fixes for such an old version of Flutter.

I kindly advise you to update to the latest Fluter `stable`, if you encounter this issue, please comment below with the details from the latest stable, including steps to replicate the issue.

Thank you

**Comment by edgarfroes** [comment] 2021-07-01 13:18
Can you guys at least help me understand why it's referencing an unexisting version of Flutter?

**Comment by edgarfroes** [comment] 2021-07-01 14:08
I had a crazy idea. Maybe I can hack the version to explicitely tell it that it should be recognized as `1.17.5`. Is there any file on the Flutter folder that I can change to force the version string to `1.17.5`?

**Comment by TahaTesser** [comment] 2021-07-02 07:51
Hi @edgarfroes 
I'm not sure why is it pointing to this version. As mentioned, there would be no support for older stable. If it reproduces with the latest stable, we can definitely try to find the cause of the issue.

Given that feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2021-07-02 07:51 UTC
Labels: in triage
