### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by MazenCoder** [flutter/flutter#155752] opened 2024-09-26 12:06 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008130-001465643EF2001C --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-SA)
    • Flutter version 3.24.3 on channel stable at /Users/mazen/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (2 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/mazen/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] Connected device (5 available)
    • SM A047F (mobile)               • R58T90VHK3T               • android-arm64  • Android 14 (API 34)
    • MAZEN’s iPhone (mobile)         • 00008130-001465643EF2001C • ios            • iOS 18.0 22A3354
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 128.0.6613.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.1.25+32
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 4d7946a68d26794349189cf21b3f68cc6fe61dcb
### Plugins
app_badge_plus-1.1.5
apple_pay_flutter-1.0.2
audio_session-0.1.21
connectivity_plus-6.0.5
device_info_plus-10.1.2
facebook_auth_desktop-1.0.3
file_selector-1.0.3
file_selector_android-0.5.1+7
file_selector_ios-0.5.3
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4+1
file_selector_web-0.9.4+2
file_selector_windows-0.9.3+2
firebase_analytics-11.3.2
firebase_analytics_web-0.5.10+1
firebase_core-3.5.0
firebase_core_web-2.18.1
firebase_crashlytics-4.1.2
firebase_database-11.1.3
firebase_database_web-0.2.6+1
firebase_messaging-15.1.2
firebase_messaging_web-3.9.1
flutter_clickpay_bridge-2.4.2
flutter_facebook_auth-6.1.1
flutter_facebook_auth_web-5.0.0
flutter_inappwebview-6.1.0+1
flutter_inappwebview_android-1.1.0+1
flutter_inappwebview_ios-1.1.0+1
flutter_inappwebview_macos-1.1.0+1
flutter_inappwebview_web-1.1.0
flutter_inappwebview_windows-0.1.0
flutter_keyboard_visibility-5.4.1
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_local_notifications-17.2.3
flutter_local_notifications_linux-4.0.1
flutter_native_splash-2.4.1
flutter_plugin_android_lifecycle-2.0.22
flutter_secure_storage-9.2.2
flutter_secure_storage_linux-1.2.1
flutter_secure_storage_macos-3.1.2
flutter_secure_storage_web-1.2.1
flutter_secure_storage_windows-3.1.2
geolocator-12.0.0
geolocator_android-4.6.1
geolocator_apple-2.3.7
geolocator_web-4.1.1
geolocator_windows-0.2.3
go_sell_sdk_flutter-2.4.9
google_maps_flutter-2.9.0
google_maps_flutter_android-2.14.7
google_maps_flutter_ios-2.13.0
google_maps_flutter_web-0.5.10
google_sign_in-5.4.4
google_sign_in_android-6.1.30
google_sign_in_ios-5.7.7
google_sign_in_web-0.10.2+1
image_picker-1.1.2
image_picker_android-0.8.12+13
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
just_audio-0.9.40
just_audio_web-0.4.13
package_info_plus-8.0.2
path_provider-2.1.4
path_provider_android-2.2.10
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.12
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+2
permission_handler_windows-0.2.1
phone_number-2.1.0
pointer_interceptor-0.10.1+2
pointer_interceptor_ios-0.10.1
pointer_interceptor_web-0.10.2+1
share_plus-10.0.2
shared_preferences-2.3.2
shared_preferences_android-2.3.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.2
shared_preferences_windows-2.4.1
sign_in_with_apple-4.3.0
sign_in_with_apple_web-1.0.1
sqflite-2.3.3+1
tap_apple_pay_flutter-1.0.3
url_launcher-6.3.0
url_launcher_android-6.3.10
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
video_player-2.9.1
video_player_android-2.7.3
video_player_avfoundation-2.6.1
video_player_web-2.3.2
wakelock_plus-1.2.8
webview_flutter-3.0.4
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by danagbemava-nc** [comment] 2024-09-26 12:40
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-09-26 12:40 UTC
Labels: in triage
