### ISSUE TITLE
 Adjacent texts show different sizes and style

### ISSUE THREAD

**Issue by pxc0215** [flutter/flutter#48556] opened 2020-01-10 06:38 UTC
There is a long list with Chinese font and images in my application. But, keep on rolling the list moment will got the following error: the text display different style and size even though the same row. The exception objects are colored in red as follow

![font_exception](https://user-images.githubusercontent.com/7680117/72135630-edd3b200-33c1-11ea-8b51-b22751cfbc39.png)

## Steps to Reproduce

1. it works well at the very beginning.
2. just keep on rolling the list, but you may then see the exception.

It seem to have a connection with memory ?

**Target Platform: iOS**
**Target OS version/browser: 13.3**
**Devices: iPhone Xs**

## flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1+hotfix.2, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.40.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.

```

**Comment by dnfield** [comment] 2020-01-10 06:53
Looks like you forgot to fill out the issue template!

Please feel free to edit and then comment to ping this and get it re-opened - or just file a new issue with the details.  Please be sure to include a minimal reproduction that leads to this issue.

**Comment by pxc0215** [comment] 2020-01-10 08:02
@dnfield Sorry, I just forgot to fill out the issue template. It is now correct, please open the issue.

**Comment by dnfield** [comment] 2020-01-10 08:04
Can you add the code to reproduce this?

**Comment by TahaTesser** [comment] 2020-03-06 12:26
Hi @pxc0215 

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-03-06 12:26 UTC
