### ISSUE TITLE
Error launching application on iPhone 12.

### ISSUE THREAD

**Issue by BringTheChill** [flutter/flutter#79987] opened 2021-04-07 22:03 UTC
I just can not run my app (it's working just from Xcode) on my iPhone 12 with iOS 14.4.2 but it's working fine on iPhone 7 with iOS 14.4.1. I use Android Studio as IDE.
It's literally kind of the same problem from #69632 but solutions from there is not working for me and topic is closed now.

## Steps to Reproduce
Just try to run an app from Android Studio with iOS 14.4.2 and and you see it's not working.

<details>
 flutter run --verbose:

```
[        ] Application launched on the device. Waiting for
observatory port.
[+30013 ms] Installing and launching... (completed in 53.6s)
[        ] Error launching application on Florin Robert’s iPhone.
[   +8 ms] "flutter run" took 132,510ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[  +72 ms] (lldb) process detach
[ +200 ms] ensureAnalyticsSent: 202ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

```
flutter analyze:

```
Analyzing bestill...                                                    
No issues found! (ran in 4.3s)
```

flutter doctor -v:

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at /Users/robert/Developer/flutter
    • Framework revision 4d7946a68d (3 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/robert/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • Florin Robert’s iPhone (mobile) • 00008101-001609403E84001E • ios            • iOS 14.4.2
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```
</details>
@jmagman thanks for trying to help and I hope this ticket is what you need.

**Comment by jmagman** [comment] 2021-04-07 23:16
Not related to https://github.com/flutter/flutter/issues/69632, that's an issue with CocoaPods and plugins, this looks like a timeout waiting for the app to launch.

Looks closer to https://github.com/flutter/flutter/issues/72161.

**Comment by BringTheChill** [comment] 2021-04-08 05:12
> Not related to #69632, that's an issue with CocoaPods and plugins, this looks like a timeout waiting for the app to launch.
> 
> Looks closer to #72161.

ok then. i am still waiting for a fix :(

**Comment by pedromassangocode** [comment] 2021-04-08 09:33
Hi @BringTheChill 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose`?
Thank you

**Comment by BringTheChill** [comment] 2021-04-08 09:53
> Hi @BringTheChill
> Can you please provide your `flutter doctor -v`, your `flutter run --verbose`?
> Thank you

I did it ... Look on Details

**Comment by pedromassangocode** [comment] 2021-04-08 11:39
Sorry I meant the complete output of `flutter run --verbose`.

**Comment by BringTheChill** [comment] 2021-04-08 12:34
@pedromassango too many characters for github so I will let you some pastebin links.

For flutter run --verbose: https://pastebin.com/seRt78FZ
For Podfile: https://pastebin.com/ejnN573U

**Comment by sstadtl** [comment] 2021-04-08 14:55
I have the same problem, but only with debug build.
If i use release, then he app starts on device just fine
maybe my logs can help:
verbose: https://pastebin.com/SuFQqPiz
doctor: https://pastebin.com/EuGhkxjd

switching back to 2.0.3 with fvm works for me right now

**Comment by Neojoke** [comment] 2021-04-09 11:35
I also have the same problem, old device like iPhone7 work fine~ 😅

**Comment by jmagman** [comment] 2021-04-09 17:42
I've never been able to reproduce this on an iPad Pro, a iPhone 12 Pro, or an iPhone 6s running 14.4.2.  I'm not sure what's going on with the launch delays.  I'm going to close this in favor of https://github.com/flutter/flutter/issues/72161.  It seems to be a periodic problem that isn't really related to Flutter--people have reporting fixing it by replacing their charging cable, changing the port it's plugged into, and installing any pending iOS updates.

**Closed by jmagman** 2021-04-09 17:42 UTC
Labels: in triage

**Comment by sstadtl** [comment] 2021-04-10 09:05
i am sad to see this bug getting closed without any action.
3 users report the same problem with ip12 (13.2hardware).
i can confirm it is not affection latest ipad air or ip7.
it is most likely not a flutter problem directly, but a problem affection the build chain for debugging on device anyway.
(used several cable, fully updated mac and iPhone)
Any chance you could get your hands on a iPhone 12 (13.2 hardware)?
Steps to reproduce:
flutter create problemapp
cd problemapp
flutter run

one thing i noticed is that i am not getting a prompt to allow local debugging.
Maybe that part is broken in 14.4.2 on ip12?

**Comment by reesz** [comment] 2021-04-10 10:01
Can confirm this on my iPhone 12 Pro / 14.4.2 after updating to Flutter 2.0.4.

**Comment by jmagman** [comment] 2021-04-12 17:54
> i am sad to see this bug getting closed without any action.

It's not closed because it's not a bug, it was closed as a duplicate.  We don't keep duplicate reports open.

> one thing i noticed is that i am not getting a prompt to allow local debugging.

That shouldn't matter on a `flutter run`, just `flutter attach`.  Try uninstalling the app totally then running again.  Please file a new issue and completely fill out the template if you're seeing that.

> Any chance you could get your hands on a iPhone 12 (13.2 hardware)?

I just tried again on Flutter 2.0.4 on an iPhone 12 Pro on a newly created project.  It launched the app very quickly on a `flutter run` (and I do see the local network prompt).  Which doesn't mean you're not hitting a problem, but it doesn't seem to be reproducing 100% and there's some other environmental issue going on.

**Comment by sstadtl** [comment] 2021-04-14 11:22
installing, uninstalling, new project with new name, using visual studio code, or using just terminal, different cable, different ports:  all the same. can not run in debug mode on my iPhone 12 (not pro!).
running on my old iPhone 7 works.

If i can help with any more debug let me know

**Comment by DJSL1NKY** [comment] 2021-04-14 11:49
@sstadtl This Issue is closed due to duplication of this https://github.com/flutter/flutter/issues/72161

**Comment by smallLabel** [comment] 2021-07-12 04:14
iPhone 8 plus(iOS 14.6) is OK, but my iPhone 12(iOS  14.6)  not working
