### ISSUE TITLE
Missing Material Icons

### ISSUE THREAD

**Issue by darrencole** [flutter/flutter#27956] opened 2019-02-14 20:28 UTC
I noticed that some material icons are missing from Flutter including `bookmarks`, `file_copy` and `ballot`.
```
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.1.8 at C:\src\flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\dcole\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\dcole\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4999

[√] Connected device (1 available)
    • TA 1039 • PLEGAR2791811777 • android-arm64 • Android 8.1.0 (API 27)
```

**Comment by Kartik1607** [comment] 2019-02-15 07:26
Adding on

**Icons missing from Flutter**
```
all_inbox
arrow_right_alt
ballot
bar_chart
battery_20
battery_30
battery_50
battery_60
battery_80
battery_90
battery_charging_20
battery_charging_30
battery_charging_50
battery_charging_60
battery_charging_80
battery_charging_90
bookmarks
cancel_presentation
cast_for_education
cell_wifi
commute
compass_calibration
contact_support
control_camera
desktop_access_disabled
domain_disabled
drag_indicator
duo
explore_off
file_copy
how_to_reg
how_to_vote
image_search
insert_chart
insert_chart_outlined
list_alt
meeting_room
mobile_friendly
mobile_off
mobile_screen_share
mode_comment
money
music_off
no_meeting_room
notes
pause_presentation
person_add_disabled
phone_callback
play_circle_filled_white
power_off
print_disabled
signal_cellular_0_bar
signal_cellular_1_bar
signal_cellular_2_bar
signal_cellular_3_bar
signal_cellular_alt
signal_cellular_connected_no_internet_0_bar
signal_cellular_connected_no_internet_1_bar
signal_cellular_connected_no_internet_2_bar
signal_cellular_connected_no_internet_3_bar
signal_wifi_0_bar
signal_wifi_1_bar
signal_wifi_1_bar_lock
signal_wifi_2_bar
signal_wifi_2_bar_lock
signal_wifi_3_bar
signal_wifi_3_bar_lock
star_rate
thumb_down_alt
thumb_up_alt
toggle_off
toggle_on
tv_off
unsubscribe
vertical_split
voice_over_off
waves
where_to_vote
work_off
work_outline
```

**Additional Icons  in Flutter**

```
 add_call
 content_copy
 content_cut
 content_paste
 do_not_disturb
 do_not_disturb_alt
 do_not_disturb_off
 do_not_disturb_on
 file_download
 file_upload
 headset_off
 info_outline
 insert_chart
 lightbulb_outline
 lock_outline
 mode_comment
 mode_edit
 pie_chart_outlined
 sim_card_alert
 system_update_alt
 text_rotation_angledown
 text_rotation_angleup

```

**Comment by zoechi** [comment] 2019-02-15 08:20
You could create a PR like https://github.com/flutter/flutter/pull/19725 to get them added

**Comment by Kartik1607** [comment] 2019-02-15 14:35
@zoechi Just saw the code for `IconData`. For material app, the icon data is auto-generated. To update the fonts the guideline is [here](https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts). It unfortunately, can only be updated by a google employee.

**Comment by zoechi** [comment] 2019-02-15 14:42
Sorry, seems that was bad advice. 
I thought I saw several such PRs, but it seems I'm mistaken. 
The only ones I found now are for Cupertino icons and they are all closed and replaced by the PR I linked to above.

**Comment by sgon00** [comment] 2019-04-26 14:10
The most important `home_outline` is missing. 

https://material.io/tools/icons/?search=home&style=outline

**Comment by sgon00** [comment] 2019-04-26 16:10
I am not sure if this issue https://github.com/google/material-design-icons/issues/786 is the root cause or not.
Btw, this issue is related to https://github.com/flutter/flutter/issues/18849.

**Comment by bobajeff** [comment] 2019-11-12 19:02
Sense no one mentioned it. Today I noticed `add_box_outline` is missing.

**Comment by haroonkhan9426** [comment] 2020-01-02 09:47
Just noticed `apartment` is also missing.

**Comment by nvma** [comment] 2020-01-14 22:29
There a lot of icons missing at this point. A lot more variations are missing too. These icons are an integral part of Material apps, is there any help required to expedite update?

**Comment by amendgit** [comment] 2020-01-16 09:18
need the music_off icon.

**Comment by willhaslett** [comment] 2020-02-09 13:39
This issue seems both important and, on the face of it, easy to address. How can the community help here? In the meantime, can we get a workaround posted on this thread?

**Comment by feinstein** [comment] 2020-02-19 00:15
Since this isn't a breaking change I can't see why not just merge the new icons?

**Comment by pedroassis** [comment] 2020-03-16 15:49
The icon file in the flutter app doesn't contain the icons, so its not just the mappings.
The icon file in the icons repo is also missing icons (wat?) see https://github.com/google/material-design-icons/blob/master/iconfont/MaterialIcons-Regular.ttf

I checked the icons website: https://material.io/resources/icons/ and it works by using a woff2 file instead of the ttf which flutter is using.

The work around is to use the woff2 file instead https://fonts.gstatic.com/s/materialicons/v50/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2 idk if this link will work forever, just grab this file from the material.io website network if it does.

Now flutter doesn't seem to support woff2 files, so I went ahead and converted it to ttf.

Now add the [maticon.ttf.zip](https://github.com/flutter/flutter/files/4339002/maticon.ttf.zip) file attached to your font definitions: pubspec.yaml
```yaml
  fonts:
    - family: maticons
      fonts:
        - asset: fonts/maticon.ttf
```

To use the icons is pretty neat: 
```dart
Text(
   // Get the string code from https://material.io/resources/icons/
   // eg: music_off, apartment, add_box_outline, home_outline, add_call 
  'ballot',
  style: TextStyle(
    fontFamily: 'maticons',
  ),
),
```

Turns out not all icons mentioned here seem to be included, such as: battery_*

**Comment by feinstein** [comment] 2020-03-16 16:08
You can also download them as SVG and show them as an SVG Picture.

**Comment by aliyazdi75** [comment] 2020-03-17 12:03
Emoji icons too, like this: https://material.io/resources/icons/?icon=emoji_events&style=round

**Comment by atilkan** [comment] 2020-03-17 21:47
This requires little attention from flutter team.

**Comment by bnayagrawal** [comment] 2020-03-24 06:45
Almost all the outline icons are missing.

**Comment by dickamorenj** [comment] 2020-03-26 03:42
I was a little taken aback when discovering the number of icons that are not included in Flutter Icons from Material icons. When working with designers I need to be able to point them to Material.io/resources/icons and say 'These are the icons you can pick from!'.  Instead, I'm having to say 'you know those icons backed by Google are not all available in this mobile framework also backed by Google.'  Any chance we can get this fixed by next release?  
The workarounds are hacks compared to being able to use "new Icon(Icons.[favoriteIconHere])" and it works with the component's styles and colors flawlessly.
Or is there any way I can help get this done?

**Comment by bnayagrawal** [comment] 2020-03-26 03:46
@dickamorenj There's a workaround to get those icons. You download the icons that you want in svg format from material.io/resources/icons and then go to fluttericon.com and convert the icons to a single font file and use it. It looks as good as SVG.

**Comment by feinstein** [comment] 2020-03-26 03:53
@dickamorenj if you want to help, then you can map which icons are missing and submit a pull request with their code into the `Icons` class. I can't help you there as I am not sure how to translate between SVG to the encodings there.

**Comment by dickamorenj** [comment] 2020-03-26 04:18
@feinstein I'd love to help but after further investigation and if the documentation is to be believed then in 
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/icons.dart on line 68 (at the time of this comment) it says not to manually modify that file as it is generated and to see
https://github.com/flutter/flutter/wiki/Updating-Material-Design-Fonts

**The instructions on that file specifically say to clone a repository but that it's (Google only sorry) !!!!! Following the repository link does confirm that it requires a google.com account to login.**

Looks like we need this escalated and maintained as Material icons change in the future. Seems like this might be a process oversight.

**Comment by feinstein** [comment] 2020-03-26 04:19
Hmm interesting...

**Comment by nvma** [comment] 2020-03-26 09:10
Getting Material icons shouldn't involve any workarounds though, it really should work out of the box in Flutter of all frameworks.

**Comment by cgalvar** [comment] 2020-04-13 06:57
So in the mean time I will download the png, because svg images doesnt work that well either

**Comment by zherman91** [comment] 2020-04-15 17:39
Is there any further update on this? I just started building out my company's app and sold them on flutter, went to use an icon i always use with the Vue version of the application and its no where to be found.. Really would like to not waste time on something as simple as icons. Please let us know!

**Comment by feinstein** [comment] 2020-04-16 22:56
Don't expect any updates on this any short, as this is a very long thread already, with no updates. If you need an icon, you can import it to your project in SVG format, or PNG or JPG as an asset. 

Material Icons are just a quick way to solve this, but you are not limited to just using it. It's not as convenient using an SVG, but it works.

**Comment by atilkan** [comment] 2020-04-17 00:34
@feinstein this is not a reasonable explanation. Flutter is a framework and should handle this without compromise.

**Comment by feinstein** [comment] 2020-04-17 03:31
I am just pointing out how can you go around this and not have your app deployment stopped or delayed.

**Comment by atilkan** [comment] 2020-04-17 09:06
We are already doing it. Doesnt feel clean.

**Comment by feinstein** [comment] 2020-04-17 12:27
AFAIK that's how you do for every framework, on every platform, either you import your icons as assets, or you import an icon library, they never come as part of the Framework, Flutter is the first one that I know that gives us this. IMHO they embedded the icons on the Framework so we could try Flutter quickly and see it's power, but they didn't intend to keep updating it, I wouldn't be surprised if this becomes a separate library (material_icons_extended) in the future.

Don't take me wrong I want them to update it, I just don't think they will, not any time soon.

**Comment by atilkan** [comment] 2020-04-17 12:50
No you don’t do it for every framework. That is why they called framework. 
So according to flutter team we should try this quickly but foot in the hole on every couple step.

**Comment by aliyazdi75** [comment] 2020-04-17 16:54
It's very annoying guys, please don't leave a comment about what have been already commented. Just let flutter team speak.

**Comment by zherman91** [comment] 2020-04-17 17:37
I actually found a really easy way to do this. 

Using the [cheat sheet](https://cdn.materialdesignicons.com/5.1.45/) for material design icons you can copy the hex code content value of the icon you want and then create a constants file and add the icons as you go. It's super simple and you don't have to deal with SVGs or anything else. 

```
class MyIcons {
  static const IconData alert = IconData(0xF05D6, fontFamily: 'maticons');
  static const IconData progress = IconData(0xF0995, fontFamily: 'maticons');
  static const IconData account_plus = IconData(0xF0014, fontFamily: 'maticons');
  static const IconData close_circle_outline = IconData(0xF015A, fontFamily: 'maticons');
}

// Example Usage

Icon(MyIcons.progress);      

```

In my opinion, the lack of icons should not reflect negatively on the entire Flutter framework. I'm coming directly from Vue and Flutter flows just as nice. Definitely an amazing piece of work. I simply tried the above solution and it flat out just worked.

**Comment by atilkan** [comment] 2020-04-17 17:45
@zherman91 Did you read the issue. You don't have any missing icon in your example.

**Comment by zherman91** [comment] 2020-04-17 17:53
@atilkan That's just an example of how I set up the file. Any icon that's on the cheat sheet, including those that aren't in flutter out of the box, can be pulled in this way. 

I did however forget to mention that you have to add the `material_fonts.tff` font family in order to reference icons this way. You can either reference the font family in the icon file or set it as the default font which may not work for everyone but did in my case. I can update my previous post to include that if need be.

**Comment by atilkan** [comment] 2020-04-17 18:03
@zherman91 Please try with missing icons.

**Comment by nvma** [comment] 2020-04-17 22:50
I'd like to point out that nobody is underplaying the busyness of the Flutter team. We all greatly appreciate the stellar work they've done so far. But I can't agree with @feinstein's 
`IMHO they embedded the icons on the Framework so we could try Flutter quickly and see it's power, but they didn't intend to keep updating it`
notion. 
As I've said before, Material Icons are an integral part of any Material Design application and one of the reasons I've picked Flutter for my company's native app over React is that the Flutter is said to provide pixel perfect Material Design spec. It turns out it doesn't. Every Javascript framework has update its icons long time ago, but native Google's framework has not.
There's no shortage of volunteers to help expedite the process, but the pipeline is allegedly setuped only for usage by Google employees. This show work out of the box, period.

**Comment by zherman91** [comment] 2020-04-18 03:22
I'm really not sure why this is so difficult. Saying that all the icons should be included into the framework itself doesn't make sense to me. That's like saying that Vue should come with icon components out of the box.. Without importing a library like Vuetify that pulls the icons in for you, you'd have to manually import them or use a CDN link or something. 

When i first commented on this, i didn't think about it that way. And since i found an extremely easy way to pull in just about any material design icon you can imagine, i thought i would share it with everyone to hopefully help out.. Not stir up more nonsense about something so trivial. 

Thanks Flutter team! Keep doing what you're doing!

**Comment by feinstein** [comment] 2020-04-18 23:02
@nvma there's a difference between Material Design and Material Icons. 

Material Design refers to the general idea of a Material object and the UI controls that derive from it, that's generally abstract and mutates from project to project, as the Material Design Team showed us with Material Theaming.

Material Icons are just icons that comply with those ideas but you can still adhere to Material Design and use other icons from other packages or sources.

Being pixel perfect has nothing to do with having icons or not, but with the sense that the buttons and text fields renders the same on every platform.

I will refrain from commenting on this thread any further as it clearly has gone beyond its original scope and its only polluting the thread.

**Comment by cgalvar** [comment] 2020-04-25 17:26
> I actually found a really easy way to do this. 
> 
> Using the [cheat sheet](https://cdn.materialdesignicons.com/5.1.45/) for material design icons you can copy the hex code content value of the icon you want and then create a constants file and add the icons as you go. It's super simple and you don't have to deal with SVGs or anything else. 
> 
> ```
> class MyIcons {
>   static const IconData alert = IconData(0xF05D6, fontFamily: 'maticons');
>   static const IconData progress = IconData(0xF0995, fontFamily: 'maticons');
>   static const IconData account_plus = IconData(0xF0014, fontFamily: 'maticons');
>   static const IconData close_circle_outline = IconData(0xF015A, fontFamily: 'maticons');
> }
> 
> // Example Usage
> 
> Icon(MyIcons.progress);      
> 
> ```
> 
> In my opinion, the lack of icons should not reflect negatively on the entire Flutter framework. I'm coming directly from Vue and Flutter flows just as nice. Definitely an amazing piece of work. I simply tried the above solution and it flat out just worked. 
> 
> Update:
> I forgot to mention that you also need to add the `material_icons.ttf` font family to pull icons in this way. 
> 

I will try it bro, hope it works, better than importing png files, and sadly I haven't been able to get running svg in my project, so I appreciate your help, and of course thanks to the Flutter team, let's not forget we are not paying for it, and they are doing a great job, gracias!

**Comment by ksankumar** [comment] 2020-04-30 15:51
> @atilkan That's just an example of how I set up the file. Any icon that's on the cheat sheet, including those that aren't in flutter out of the box, can be pulled in this way.
> 
> I did however forget to mention that you have to add the `material_fonts.ttf` font family in order to reference icons this way. You can either reference the font family in the icon file or set it as the default font which may not work for everyone but did in my case. I can update my previous post to include that if need be.

Can you please include the link for download `material_fonts.ttf`

**Comment by zherman91** [comment] 2020-05-01 16:06
@ksankumar - Sorry for the late response.. You can find the `material_fonts.ttf` at the following site: 
https://materialdesignicons.com/ 

Towards the top right, there's a download button that allows you to download the webfont which contains the file you need after you unzip. After you include that in your project and set the font family to 'maticons', you can begin adding missing icons to the file like i showed above and reference it whenever you need a missing icon. 

I've been using this method for a week or two now actively developing an app and i haven't found an icon i couldn't pull in from the site above. 

Let me know if you have any other questions.

**Comment by some3uddy** [comment] 2020-06-13 12:55
filter_alt is also missing

**Comment by travisjayday** [comment] 2020-06-16 19:57
pending, pending_action are also missing :(

**Comment by jordan-johnson** [comment] 2020-06-16 20:19
video_settings is missing too

**Comment by rizaalifwildani** [comment] 2020-06-18 05:25
Try using this method : 

first run " flutter clean " and then " flutter run " in terminal

**Comment by atilkan** [comment] 2020-06-18 07:31
@rizaalifwildani Thanks it did it. All icons are working, also my broken car also fixed.

**Closed** 2020-07-24 22:41 UTC
Labels: P4, customer: crowd, f: material design, framework, passed first triage

**Comment by ben-xx** [comment] 2020-08-14 18:03
Some kind soul has made the @zherman91 solution into a [pub.dev package:
**material_design_icons_flutter**](https://pub.dev/packages/material_design_icons_flutter).

**Comment by SPlus91** [comment] 2020-09-22 15:49
Cannot find stop_circle, could you please add this one?

**Comment by tehsunnliu** [comment] 2020-10-23 06:43
Hi all. qr_code, qr_code_2, and qr_code_scanner icons are also missing.

**Comment by BasharShehab** [comment] 2021-02-22 22:51
smart_toy is missing as well

**Comment by mshukuno** [comment] 2021-02-26 17:22
health_and_safety is missing

**Comment by JaffaKetchup** [comment] 2021-05-03 10:53
emergency_outlined is missing

**Comment by ColonisationCaptain** [comment] 2021-06-01 20:36
water_drop_outlined is also missing

**Comment by JaffaKetchup** [comment] 2021-06-01 20:48
Flutter team, can this be reopened please? We need a way to automatically update the flutter icons when new material icons are released.

**Comment by Y0ngg4n** [comment] 2021-06-06 20:30
Missing `waving_hand_outlined`

**Comment by komritza** [comment] 2021-06-15 09:16
Also missing all disabled_by_default(outlined, sharp and rounded). I also noticed that the hex codes are completely wrong and they don't match given icons.

**Comment by kollinmurphy** [comment] 2021-06-25 00:18
south_america is missing

**Comment by AndrejGono** [comment] 2021-07-05 16:58
sensors and sensors_off? :)

**Comment by Albertbol** [comment] 2021-07-13 06:19
dark_mode, light_mode

**Comment by dalton5** [comment] 2021-07-16 17:15
workspace_premium missing

**Comment by ozburo** [comment] 2021-07-27 17:39
group_remove missing too ;/
