### ISSUE TITLE
Flutter in release mode is 6X slower than debug

### ISSUE THREAD

**Issue by ejthayer** [flutter/flutter#51199] opened 2020-02-21 15:06 UTC
I have written a small app that does a speed test of the dart language. 10 million integer and floating point calcuations, and 50k different string manipulations. Debug mode takes about 1 second, release mode takes 6 seconds. I made sure I am running debug vs release by checking the app size, release being about half the size of debug.

I am also not the only one experiencing this. Doing some searching there were several other people having the same problem.

What is the problem here? Does the flutter team even know about the problem? Are they in some sort of denial? Like saying this is user/programmer error?

Why would running an app in release mode be a full 6X slower than debug? That just makes no sense at all.

**Comment by iapicca** [comment] 2020-02-21 15:26
Hi @ejthayer 
would be very useful to have some more data about the situation you are describing,
release app should be much faster than debug counterpart.

can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-03-16 10:30
Hi @ejthayer 
Closing the issue since additional info wasn't provided.
if you disagree and can provide your code sample for reproduction please write in the comments and I will reopen it
Thank you

**Comment by ejthayer** [comment] 2020-03-16 13:01
The code sample was not provided because the question is nonsense. The code is irrelevant, run any app you want while testing the code speed, release mode is slower than debug. Asking for a code sample implies you want to blame the user, I have no interest in that. Go ahead and close it.

**Closed** 2020-03-16 14:14 UTC
Labels: in triage
