### ISSUE TITLE
TextAlign property does not differentiate between letter width

### ISSUE THREAD

**Issue by ljmatan** [flutter/flutter#73214] opened 2021-01-02 16:58 UTC
## Steps to Reproduce

Create a text widget, add textAlign property (set to TextAlignment.center). The letters will be aligned according to a fixed spacing, i.e., the Flutter framework's textAlign property assumes that all of the characters have the same width. 

![image](https://user-images.githubusercontent.com/73232684/103462215-ff753e80-4d23-11eb-8bae-5b22ca062ac6.png)

**Expected results:** 

Text alignment that aligns text according to the text size, not according to the number of letters

**Actual results:** 

Text alignment with fixed letter width

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.131, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.131 at /home/user/Development/flutter
    • Framework revision ff03a9c362 (10 days ago), 2020-12-23 22:49:02 -0500
    • Engine revision 1c975f1e7c
    • Dart version 2.12.0 (build 2.12.0-177.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/user/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /home/user/Documents/android-studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • SM A530F (mobile) • 52007e785ffc85c7 • android-arm64  • Android 9 (API 28)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 87.0.4280.66

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2021-01-04 10:09
@ljmatan 
Can you provide a minimal complete reproducible code sample along with what should be the text alignment for it as compared to the actual behavior ?
Thanks.

**Comment by ljmatan** [comment] 2021-01-04 14:50
Of course.

Minimal code example: 

```
import 'package:flutter/material.dart';

void main() => runApp(CodeSample());

class CodeSample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Google font - https://fonts.google.com/specimen/Oswald
      theme: ThemeData(fontFamily: 'Oswald'),
      home: Scaffold(
        body: Center(
        child: RichText(
          textAlign: TextAlign.center,
          text: TextSpan(
            style: const TextStyle(color: Colors.black),
            children: [
              TextSpan(
                text: '12\n',
                style: const TextStyle(
                  fontSize: 33,
                  fontWeight: FontWeight.w300,
                ),
              ),
              TextSpan(
                text: 'mins',
                style: const TextStyle(fontSize: 10),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

As for how it should look, you can compare the following screenshot to the one in my original post. The screenshot in the original post displays what TextAlign.center property looks like in the app, and the below screenshot displays how it should actually look like. 

![Screenshot_2021-01-04_15-42-39](https://user-images.githubusercontent.com/73232684/103546840-e4c9d380-4ea3-11eb-9c61-c38664cbd404.png)

**Comment by darshankawar** [comment] 2021-01-05 06:23
<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by maheshmnj** [comment] 2022-12-07 13:41
Hello @ljmatan, I verified the issue and I cannot reproduce it, Please see the below output which shows each letter has its own width.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/31410839/206193994-fd16af47-8267-48b4-aa1a-ebd1098b73f5.png">


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(CodeSample());

class CodeSample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Google font - https://fonts.google.com/specimen/Oswald
      theme: ThemeData(fontFamily: 'Oswald'),
      home: Scaffold(
        body: Center(
        child: ListView(
          children: [
            for(int i=0;i<10;i++)
          RichText(
          textAlign: TextAlign.center,
          text:TextSpan(
            style: const TextStyle(color: Colors.black),
            children: [
              TextSpan(
                text: '1\n',
                style:const  TextStyle(
                  fontSize: 33,
                  backgroundColor: Colors.red,
                  fontWeight: FontWeight.w300,
                ),
              ),
              TextSpan(
                text: '$i\n',
                style:const  TextStyle(
                  backgroundColor: Colors.red,
                  fontSize: 33,
                  fontWeight: FontWeight.w300,
                ),
              ),
              const TextSpan(
                text: 'mins',
                style:  TextStyle(fontSize: 10),
              ),
            ],
          ),
        ),
          ],
        )
      ),
    ));
  }
}
```
</details> 


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing since this is no longer reproducible, In case you encounter the issue, Please feel free to write in the comments and we will reopen it.

**Closed by maheshmnj** 2022-12-07 13:41 UTC
Labels: framework, f: material design, passed first triage, has reproducible steps, found in release: 1.22
