### ISSUE TITLE
[in_app_purchase] Codelabs for IAP says `com.android.vending.BILLING` will be added in manifest

### ISSUE THREAD

**Issue by tkshnwesper** [flutter/flutter#121676] opened 2023-03-01 09:26 UTC
Hi,

While going through [Codelabs for IAP](https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases#2), I noticed this sentence

> Click pub get to download the package or run flutter pub get in the command line. This will ensure the `com.android.vending.BILLING` permission is added to the `android/app/src/main/AndroidManifest.xml` file in your Flutter application.

which I believe is [no longer valid](https://stackoverflow.com/a/68173792/2513269) as `BillingClient` is being used internally in the `in_app_purchase` plugin.

**Comment by danagbemava-nc** [comment] 2023-03-01 09:34
Closing this as a duplicate of https://github.com/flutter/flutter/issues/120067

**Closed by danagbemava-nc** 2023-03-01 09:34 UTC
Labels: in triage
