### ISSUE TITLE
Expose AOT snapshot size profiler in flutter tool

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#26609] opened 2019-01-16 00:09 UTC
It'd be nice if there was a way to trigger https://github.com/dart-lang/sdk/blob/master/runtime/docs/snapshot_profiling.md from the `flutter` command.

**Comment by Hixie** [comment] 2019-01-16 00:11
(In the meantime, you can use `--extra-gen-snapshot-options` to use it.)

**Comment by dnfield** [comment] 2020-03-03 13:59
#51594 is a dupe of this but has more details

**Closed by dnfield** 2020-03-03 13:59 UTC
Labels: severe: new feature, tool
