### ISSUE TITLE
Recorded Video using Camera [Plugin] can not be played using video player [Plugin]

### ISSUE THREAD

**Issue by Loopex2019** [flutter/flutter#59022] opened 2020-06-08 22:15 UTC
I have really a strange behavior using the video player plugin. It only plays videos picked up for example using the image picker . But recorded ones using the camera plugin do not get played. I think that this issue is only android related since the exception is about the Exoplayer. Here is my video player code : 
<details>
<summary>code sample</summary>

```
  VideoPlayerController _controller;
  double _opacity = 1.0;

  String get _duration =>
      _controller.value.duration?.toString()?.substring(2)?.split('.')?.first ??
      '';
  String get _position =>
      _controller.value.position?.toString()?.substring(2)?.split('.')?.first ??
      '';

  void _listener() {
    setState(() {
      if (_position == _duration) {
        _opacity = 1.0;
      }
    });
  }

  @override
  void initState() {
    super.initState();
    
    _controller = VideoPlayerController.file(
      File(widget.videoPath),
    );
    _controller.addListener(_listener);
    print(widget.videoPath);
    _controller.initialize().then((_) => setState(() {}));
    _controller.play();
  }

  @override
  void dispose() {
    _controller.dispose();
    _controller.removeListener(_listener);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        setState(() {
          if (_opacity == 1.0) {
            _opacity = 0.0;
          } else {
            _opacity = 1.0;
          }
        });
      },
      child: Scaffold(
        body: Stack(
          children: <Widget>[
            SizedBox.expand(
              child: FittedBox(
                fit: BoxFit.cover,
                child: SizedBox(
                  width: _controller.value.size?.width ?? 0,
                  height: _controller.value.size?.height ?? 0,
                  child: VideoPlayer(_controller),
                ),
              ),
            ),
            Align(
              alignment: Alignment.topRight,
              child: Padding(
                padding: const EdgeInsets.symmetric(
                  vertical: 25,
                  horizontal: 10,
                ),
                child: IconButton(
                  icon: Icon(
                    Icons.close,
                    color: Colors.white,
                  ),
                  iconSize: 35,
                  onPressed: () {
                    Navigator.pop(context);
                  },
                ),
              ),
            ),
            Center(
              child: AnimatedOpacity(
                opacity: _opacity,
                duration: Duration(milliseconds: 350),
                curve: Curves.easeIn,
                child: FlatButton(
                  shape: CircleBorder(),
                  onPressed: () {
                    setState(() {
                      if (_controller.value.isPlaying) {
                        _controller.pause();
                        print(widget.videoPath);
                      } else if (!_controller.value.isPlaying &&
                          _position != _duration) {
                        _controller.play();
                        _opacity = 0.0;
                      } else if (_position == _duration) {
                        _controller.seekTo(Duration.zero);
                        _controller.play();
                        _opacity = 0.0;
                      } else {
                        return;
                      }
                    });
                  },
                  child: FaIcon(
                    _controller.value.isPlaying
                        ? Icons.pause
                        : _position == _duration
                            ? Icons.replay
                            : Icons.play_arrow,
                    color: Colors.white,
                    size: 50,
                  ),
                ),
              ),
            ),
            Align(
              alignment: Alignment.bottomCenter,
              child: VideoProgressIndicator(
                _controller,
                allowScrubbing: true,
              ),
            ),
          ],
        ),
      ),
    );
  }

```
</details>

<details>
<summary>And here is the Exception logs : </summary>

```
I/ExoPlayerImpl(  920): Init 3549221 [ExoPlayerLib/2.9.6] [j7velte, SM-J701F, samsung, 28]
E/LoadTask(  920): Unexpected exception loading stream
E/LoadTask(  920): java.lang.IllegalStateException: Top bit not zero: -121179826
E/LoadTask(  920): 	at com.google.android.exoplayer2.util.ParsableByteArray.readUnsignedIntToInt(ParsableByteArray.java:397)
E/LoadTask(  920): 	at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:179)
E/LoadTask(  920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.getTrackSampleTables(Mp4Extractor.java:457)
E/LoadTask(  920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:398)
E/LoadTask(  920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:360)
E/LoadTask(  920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:351)
E/LoadTask(  920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:182)
E/LoadTask(  920): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)
E/LoadTask(  920): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/LoadTask(  920): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/LoadTask(  920): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/LoadTask(  920): 	at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal(  920): Source error.

E/ExoPlayerImplInternal(  920): java.io.EOFException
E/ExoPlayerImplInternal(  920): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:265)
E/ExoPlayerImplInternal(  920): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:72)
E/ExoPlayerImplInternal(  920): 	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:81)
E/ExoPlayerImplInternal(  920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:336)
E/ExoPlayerImplInternal(  920): 	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:182)
E/ExoPlayerImplInternal(  920): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:898)

E/ExoPlayerImplInternal(  920): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(  920): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(  920): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(  920): 	at java.lang.Thread.run(Thread.java:764)
E/flutter (  920): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: java.io.EOFException, null)
E/flutter (  920):

```
</details>

As you can see the last line shows a Platform Exception. But i don't get it .

**Comment by VladyslavBondarenko** [comment] 2020-06-09 14:24
Hi @Loopex2019 
could you provide your `flutter doctor -v` and what version of video_player and camera are you using?

**Comment by Loopex2019** [comment] 2020-06-09 16:41
The doctor : 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.45.1)
[√] Connected device (1 available)

• No issues found!

```
`video_player: ^0.10.11+1` and `camera: ^0.5.8+2`

**Comment by VladyslavBondarenko** [comment] 2020-06-10 07:58
@Loopex2019 
Can you see the same error when running this code sample on your Samsung SM-J701F? https://pub.dev/packages/camera#-example-tab-

(I couldn't with Redmi Note 7 Android 9 (API 28))

**Comment by Loopex2019** [comment] 2020-06-10 09:02
Yes its the same with Android 9 (API 28)

**Comment by Luc45L4nn35** [comment] 2020-06-11 14:15
Hello, I think this is not a platform specific problem because I got this weird behavior on iOS too. Basically, the video recorded starts playing but it freezes 1 second later. The Debug Console doesn't show anything, but I printed some values of the Video Player Controller and found no errors or weird values. Everything is okay. The isPlaying is true; duration is greater than 1 second; but position doesn't update anytime.

**Comment by Luc45L4nn35** [comment] 2020-06-11 16:16
@Loopex2019 

Can you try add the code `await Future.delayed(Duration(milliseconds: 1000));` between the lines `_controller = VideoPlayerController.file...` and `_controller.initialize().then...`? I don't know why, but the video plays without freezes with this workaround.

**Comment by ariefwijaya** [comment] 2020-06-16 11:05
I have this problem too,  I think it is because camera failed when stop recording and output the corrupted video. So, your video player cannot play it. You can inspect the video file using android studio in device explorer. 
And still have no solution for this problem.

**Comment by ariefwijaya** [comment] 2020-06-19 09:28
Any update on this issue ?

**Comment by PabloG6** [comment] 2020-06-30 00:07
Having the exact same problem.

**Comment by PabloG6** [comment] 2020-07-03 07:30
Guess there's no fix on this issue, might just look into it myself

**Comment by kishan92** [comment] 2020-08-25 07:07
Any updates?

**Comment by kishan92** [comment] 2020-08-26 11:04
The issue in my case was occurring due to broken audio in the video recorded using camera plugin(recognized this by setting enableAudio to false in the CameraController parameters)...as a work around I resolved this using [flutter_ffmpeg](https://pub.dev/packages/flutter_ffmpeg) to process the video before playing it on the video player...this seems to work in my case..hope this helps!

**Comment by AncientPixel** [comment] 2020-10-27 14:37
I'm having a the same issue on iOS, I'm getting "PlatformException(VideoError, Failed to load video: Cannot Open, null)" error from "await controller.initialize();" where controller is VideoPlayerController.
The video file is present and was recorded using the 'camera' package. I think the 'camera' package breaks something on the file as I can't open the file with other packages that expect a valid 'mp4' file.
And yes I did " await _controller.stopVideoRecording();" before trying to access the file.

**Comment by willallendev** [comment] 2020-11-25 18:39
> The issue in my case was occurring due to broken audio in the video recorded using camera plugin(recognized this by setting enableAudio to false in the CameraController parameters)...as a work around I resolved this using [flutter_ffmpeg](https://pub.dev/packages/flutter_ffmpeg) to process the video before playing it on the video player...this seems to work in my case..hope this helps!

I did help but it just take way too long, do you have any sugestions? are you facing the same problem as me? if not, what command/config are you running? Thanks for your solution, at least I have something that works

**Comment by maheshmnj** [comment] 2021-07-01 08:29
Hi @Loopex2019, Are you still experiencing this issue? I would request everyone who is facing this issue to try this [example app](https://github.com/flutter/plugins/blob/master/packages/camera/camera/example/lib/main.dart) with the latest ```video_player ^2.1.6``` plugin , with this example I am able to see the recorded video playing. if you still see the issue feel free to comment with more details and exact steps to reproduce the issue.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.2 at /Users/mahesh/Documents/flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • d9dac45d • android-arm64  • Android 10 (API 29)
    • macOS (desktop)        • macos    • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
<details>

Thank you.

**Comment by TahaTesser** [comment] 2021-07-23 12:56
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-07-23 12:56 UTC
Labels: e: device-specific, p: camera, p: video_player, platform-android, plugin, severe: crash
