### ISSUE TITLE
http.post() - flutter stable - Flutter-Web with Chrome

### ISSUE THREAD

**Issue by christhirst** [flutter/flutter#77536] opened 2021-03-07 22:01 UTC
## Steps to Reproduce

Hello,

when I try to send json-Data to my server, I tested it with postman - proxy, then I get an empty http body.
When I don't specify the headers I get the body in postman.

1.
https://flutter.dev/docs/cookbook/networking/send-data
```

Future<http.Response> createAlbum(String title) {
  return http.post(
    Uri.https('jsonplaceholder.typicode.com', 'albums'),
    headers: <String, String>{
      'Content-Type': 'application/json; charset=UTF-8',
    },
    body: jsonEncode(<String, String>{
      'title': title,
    }),
  );
}
```
2. "browser_client.dart" opens in either way.

**Expected results:** 
I just want to make a post with json and receive it.

**Actual results:** 
I don't get the json with the right media type.

<details>
  <summary>I don't get any logs or errors without --verbose</summary>

```
      [   +2 ms] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+7014 ms] Error: XMLHttpRequest error.
                        dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get
current
                    packages/http/src/browser_client.dart 84:22                                       <fn>
                    dart-sdk/lib/async/zone.dart 1612:54                                              runUnary
                    dart-sdk/lib/async/future_impl.dart 152:18
handleValue
                    dart-sdk/lib/async/future_impl.dart 704:44
handleValueCallback
                    dart-sdk/lib/async/future_impl.dart 733:13
_propagateToListeners
                    dart-sdk/lib/async/future_impl.dart 530:7
[_complete]
                    dart-sdk/lib/async/stream_pipe.dart 61:11
_cancelAndValue
                    dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
                    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14
_checkAndCall
                    dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
                    dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>
                    
                    
                        at Object.createErrorWithStack (http://localhost:44495/dart_sdk.js:5348:12)
                        at Object._rethrow (http://localhost:44495/dart_sdk.js:39350:16)
                        at async._AsyncCallbackEntry.new.callback (http://localhost:44495/dart_sdk.js:39344:13)
                        at Object._microtaskLoop (http://localhost:44495/dart_sdk.js:39176:13)
                        at _startMicrotaskLoop (http://localhost:44495/dart_sdk.js:39182:13)
                        at http://localhost:44495/dart_sdk.js:34689:9
```

```
```

</details>
Thanks for your help.

**Comment by intoxicated** [comment] 2021-03-08 04:09
What happen if you add 'Accept' : 'application/json' in your header?

**Comment by intoxicated** [comment] 2021-03-08 04:10
Did you try to define `Accept` header field with your expected media type? are you expecting to get json?

**Comment by pedromassangocode** [comment] 2021-03-08 10:23
Hi @illabo 
From what I can see, the issue is related to http requests rather than to Flutter itself. Please open the issue in the dedicated Dart SDK [repository](https://github.com/dart-lang/sdk/issues).
Closing, as this isn't an issue with Flutter itself.  
Thank you

**Closed by pedromassangocode** 2021-03-08 10:23 UTC
Labels: in triage
