### ISSUE TITLE
Document how to change the window configuration in a test

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#29934] opened 2019-03-25 20:53 UTC
Currently, the widget tests have a fixed configuration of devicePixelRatio 3.0, 800x600 logical pixels (2400x1800 real pixels). 

It would be great to be able to configure this in flutter_tester especially now that widget tests support screenshotting. That way, clients can write tests against specific form factors they are testing.

**Comment by mehmetf** [comment] 2019-03-25 20:56
Note that @tvolkert and I have said no to this request because widget tests are not supposed to emulate any particular device **exactly** (it is an unattainable goal). However, a lot of clients have been asking for this including dream so we need to have a proper answer for it. Perhaps we can set expectations better?

**Comment by tvolkert** [comment] 2019-03-25 21:23
@Hixie's answer to this in the past was:

> If you want a custom-sized "screen", just wrap your widget in a SizedBox and a MediaQuery so that the screen is the size you expect. (If you want to take a screenshot of that, add in a RepaintBoundary so that you can snapshot that, rather than the whole 800x600 screen.) (You will want to put the SizedBox inside a widget that lets the child change size, e.g. a Center.)

**Comment by Hixie** [comment] 2019-03-26 03:37
We do support this now, actually.
Set tester.binding.window.physicalSizeTestValue to an arbitrary value.
https://docs.flutter.dev/flutter/flutter_test/TestWindow/physicalSizeTestValue.html

**Comment by dballesteros7** [comment] 2019-03-26 09:55
That along with https://docs.flutter.dev/flutter/flutter_test/TestWindow/devicePixelRatioTestValue.html sounds exactly what I was looking for. I'll give it a try.

**Comment by Hixie** [comment] 2019-03-26 23:29
Should we close the bug then?

**Comment by Hixie** [comment] 2019-04-02 23:15
We have three ways to do this:
Setting `tester.binding.window.physicalSizeTestValue`, calling `tester.binding.setSurfaceSize()`, and putting the test widget inside a `MediaQuery`/`SizedBox`.

Where should we document this to make it clearer?

**Comment by Hixie** [comment] 2019-04-02 23:15
(I've removed the customer critical label since the original issue is resolved and we're now treating this as a doc issue. Please don't hesitate to put the label back if we misunderstood.)

**Comment by dballesteros7** [comment] 2019-04-05 15:21
I tried `physicalSizeTestValue` and `devicePixelRatioTestValue` and it gave the expected results. Thanks! +1 on improving the documentation around this.

**Comment by tp** [comment] 2019-07-11 16:42
I don't see the values set this way reflected on `ui.window.physicalSize` and `ui.window.devicePixelRatio`.

Is that expected behavior or should I file an issue for that?

**Comment by jamesderlin** [comment] 2020-07-28 23:31
Is there any substantial difference between this and #12994?

**Comment by markusaksli-nc** [comment] 2020-07-30 14:21
Closing this as a duplicate of #12994 as they both seem to describe the exact same documentation issue. Feel free to reopen if this is not the case.

**Closed by markusaksli-nc** 2020-07-30 14:21 UTC
Labels: P4, a: tests, d: api docs, framework
