### ISSUE TITLE
[in_app_purchase] [Android] Automatically refunded subscription still treated as restored

### ISSUE THREAD

**Issue by KarlScholl97** [flutter/flutter#124518] opened 2023-04-10 15:20 UTC
## Problem description
After making a test purchase within a Flutter-App I am developing, the app crashed due to a purchase-unrelated error and did not call completePurcase. As a result, the subscription was refunded after two 5-minute subscription intervals, judging by the history in the emulator's PlayStore-App. Since then, when listening to the purchase stream (e.g. on app start), the status of the purchase remains "restored", meaning that the potential user has access to the subscription features without paying for them.

This seems to be similar behavior to the closed issue #107454 and was also mentioned here #107755

## Setup
Running on Pixel 3a emulator, targeting Sdk 33, using the following package versions in dependecies:
`in_app_purchase: ^3.1.5`
`in_app_purchase_android: ^0.2.4+3`

## Steps to Reproduce

1. Purchase a test subscription with 5-minute subscription periods.
2. Do not call completePurchase and wait for the automatic refund.
3. Perform a hot restart and init purchaseStream.
4. Check status of subscription payment.

You can use the in_app_purchase sample app for reproduction, just take out completePurchase.

**Expected results:**
Purchase status should be PurchaseStatus.canceled or another status that indicates that the subscription is not active.

**Actual results:**
Purchase status is PurchaseStatus.restored

**Logs:**
Providing logs seems moot to me, because this seems to be a package logic issue. I can upload them on request, though.

**PS:**
This is the first issue I've ever filed, hope it's reasonably well-composed.

**Comment by KarlScholl97** [comment] 2023-04-10 16:20
Quick update: Turns out I was able to purchase the subscription despite PurchaseStatus == restored. After that, behavior returned to normal. Not sure if this is something that the in_app_purchase can resolve or if it has to do with Google's purchase flow. Will leave it to the moderators to close this issue if appropriate.

**Comment by huycozy** [comment] 2023-04-11 09:40
Hi @KarlScholl97 
When debugging this, I see that the purchase is valid after `_verifyPurchase(purchaseDetails)`. But as you don't call `completePurchase`, the purchase will be canceled. I received the email about it with content:

>This test purchase was cancelled because it was not acknowledged. You should ensure all purchases are acknowledged so they are not subject to refunds. 

From the console after adding the log, I see the purchase status is `called` as expected. You can try my below snippet code:

<details>
<summary>Snippet code (origin from plugin sample code)</summary>

```dart

  void _listenToPurchaseUpdated(List<PurchaseDetails> purchaseDetailsList) {
    print('items in purchaseDetailsList: ${purchaseDetailsList.length}');
    purchaseDetailsList.forEach((PurchaseDetails purchaseDetails) async {

      switch (purchaseDetails.status) {
        case PurchaseStatus.pending:
          print('pending called');
          break;
        case PurchaseStatus.purchased:
          print('purchased called');
          break;
        case PurchaseStatus.restored:
          print('restored called');
          break;
        case PurchaseStatus.error:
          print('error called');
          break;
        case PurchaseStatus.canceled:
          print('canceled called');
          break;
      }

      if (purchaseDetails.status == PurchaseStatus.pending) {
        showPendingUI();
      } else {
        if (purchaseDetails.status == PurchaseStatus.error) {
          handleError(purchaseDetails.error!);
        } else if (purchaseDetails.status == PurchaseStatus.purchased) {
          bool valid = await _verifyPurchase(purchaseDetails);
          if (valid) {
            deliverProduct(purchaseDetails);
          } else {
            _handleInvalidPurchase(purchaseDetails);
            return;
          }
        }
        if (Platform.isAndroid) {
          if (!_kAutoConsume && purchaseDetails.productID == _kConsumableId) {
            final InAppPurchaseAndroidPlatformAddition androidAddition =
                _inAppPurchase.getPlatformAddition<
                    InAppPurchaseAndroidPlatformAddition>();
            await androidAddition.consumePurchase(purchaseDetails);
          }
        }
        if (purchaseDetails.pendingCompletePurchase) {
          // await _inAppPurchase.completePurchase(purchaseDetails);
        }
      }
    });
  }

```
</details>

**Comment by huycozy** [comment] 2023-04-12 05:26
I received `PurchaseStatus.purchased` status by printing the log as the snippet code above. I'm not sure why you receive `restored` status.

Moreover, in case it works as intended when returning `purchased` status, it will continue calling `_verifyPurchase` to confirm that everything about the purchase is valid (maybe you need to validate it by your own server?). I think it should be handled by your implementation here for unexpected exceptions during the purchase. In the example code, it returns  true as default and also has a warning there:

```
  Future<bool> _verifyPurchase(PurchaseDetails purchaseDetails) {
    // IMPORTANT!! Always verify a purchase before delivering the product.
    // For the purpose of an example, we directly return true.
    return Future<bool>.value(true);
  }
```

**Comment by KarlScholl97** [comment] 2023-04-12 07:12
> I received PurchaseStatus.purchased status by printing the log as the snippet code above. I'm not sure why you receive restored status.

That is a bit odd. However, aren't both cases kind of counterintuitive? In both cases, the subscription was cancelled and therefore is not active. Why does that return `purchased` or `restored`?

> I think it should be handled by your implementation here for unexpected exceptions during the purchase.

Seems like my verification logic requires improvement then :)

**Comment by huycozy** [comment] 2023-04-13 04:59
>That is a bit odd. However, aren't both cases kind of counterintuitive? In both cases, the subscription was cancelled and therefore is not active. Why does that return purchased or restored?

The purchase is marked as canceled after 5 min (for eg), so I don't think the plugin can guarantee this case unless you implement it by your own workaround. For eg: try to catch crash while doing the purchase process; once it happens, do verify the purchase by your own implementation.

Also, I'm not sure why you get `restored` state, can you try put log printed on the code as my snippet above and share the result here?

My result (after purchasing):

```
I/flutter (25503): items in purchaseDetailsList: 1
I/flutter (25503): purchased called
```

**Closed** 2023-05-04 05:09 UTC
Labels: waiting for customer response, in triage
