### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by Massawe14** [flutter/flutter#154237] opened 2024-08-28 09:02 UTC
## Command

flutter run

## exception

RPCError: _flutter.listViews: (-32000) Service connection disposed

## Logs
RPCError
```console
#0      VmService._call (package:vm_service/src/vm_service.dart:1774:7)
#1      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1726:14)
#2      VmService.callMethod (package:vm_service/src/vm_service.dart:1717:12)
#3      FlutterVmService.callMethodWrapper (package:flutter_tools/src/vmservice.dart:501:28)
#4      FlutterVmService.getFlutterViews (package:flutter_tools/src/vmservice.dart:913:51)
#5      HotRunner.attach (package:flutter_tools/src/run_hot.dart:304:63)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
## flutter doctor
```console
[32m[✓][39m Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22000.3147], locale en-US)
    [32m•[39m Flutter version 3.24.0 on channel stable at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 80c2e84975 (4 weeks ago), 2024-07-30 23:06:49 +0700
    [32m•[39m Engine revision b8800d88be
    [32m•[39m Dart version 3.5.0
    [32m•[39m DevTools version 2.37.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\MASSAWE\AppData\Local\Android\sdk
    [32m•[39m Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2023.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[32m[✓][39m VS Code, 64-bit edition (version 1.92.2)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension version 3.26.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m SM A260F (mobile) • 52007c69de8a9619 • android-arm    • Android 8.1.0 (API 27)
    [32m•[39m Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.3147]
    [32m•[39m Chrome (web)      • chrome           • web-javascript • Google Chrome 126.0.6478.127
    [32m•[39m Edge (web)        • edge             • web-javascript • Microsoft Edge 128.0.2739.42

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: abb292a07e20d696c4568099f918f6c5f330e6b0
### Plugins
cloud_firestore-5.2.1
cloud_firestore_web-4.1.1
connectivity_plus-6.0.5
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+2
firebase_auth-5.1.4
firebase_auth_web-5.12.5
firebase_core-3.3.0
firebase_core_web-2.17.4
firebase_messaging-15.0.4
firebase_messaging_web-3.8.12
firebase_storage-12.1.3
firebase_storage_web-3.9.12
flutter_plugin_android_lifecycle-2.0.19
geolocator-12.0.0
geolocator_android-4.6.1
geolocator_apple-2.3.7
geolocator_web-4.0.0
geolocator_windows-0.2.3
google_sign_in-6.2.1
google_sign_in_android-6.1.28
google_sign_in_ios-5.7.6
google_sign_in_web-0.12.4+2
image_picker-1.1.2
image_picker_android-0.8.12+1
image_picker_for_web-3.0.5
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
path_provider-2.1.4
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.5.2
shared_preferences_linux-2.4.1
shared_preferences_web-2.4.1
shared_preferences_windows-2.4.1
sqflite-2.3.3+1
sqlite3_flutter_libs-0.5.24
url_launcher-6.3.0
url_launcher_android-6.3.2
url_launcher_ios-6.3.1
url_launcher_linux-3.2.0
url_launcher_macos-3.2.0
url_launcher_web-2.3.3
url_launcher_windows-3.1.2

**Comment by danagbemava-nc** [comment] 2024-08-28 10:00
Closing this as a duplicate of https://github.com/flutter/flutter/issues/117988

**Closed by danagbemava-nc** 2024-08-28 10:00 UTC
Labels: in triage
