### ISSUE TITLE
Listview throwing traceback: Failed assertion: line 195 pos 12: '!_debugDuringDeviceUpdate': is not true.

### ISSUE THREAD

**Issue by nishaalnaseer** [flutter/flutter#127870] opened 2023-05-30 18:48 UTC
how i think the issue can be reproduced:
copy the widget tree and create the childrenModels variable, its a DataTable 6 columns wide and 12 rows long. 
idk im really posting here because flutter asked me to
hope these help

stacktrace: 
======== Exception caught by gestures library ======================================================
The following assertion was thrown while handling a pointer data packet:
'package:flutter/src/rendering/mouse_tracker.dart': Failed assertion: line 195 pos 12: '!_debugDuringDeviceUpdate': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

stacktrace is thrown when categorySelected is equals to true, so i guess the issue is here, copied the most relevant(IMO) widgets because the whole tree is 80 lines long :

``
categorySelected ? Container(child: ListView(
                children: [
                  Container(
                    padding: const EdgeInsets.all(10),
                    child: Container(
                      decoration: BoxDecoration(
                        border: Border.all(
                          color: Colors.black,
                          width: 1.0,
                        ),
                        borderRadius: BorderRadius.circular(8.0),
                      ),
                      child: childrenModels,
                    ),
                  )
                ],
              ),)
``

**Comment by danagbemava-nc** [comment] 2023-05-31 08:27
Closing this as a duplicate of https://github.com/flutter/flutter/issues/84241

**Closed by danagbemava-nc** 2023-05-31 08:27 UTC
Labels: in triage
