### ISSUE TITLE
String.hashCode returns different values with same sequence

### ISSUE THREAD

**Issue by najeira** [flutter/flutter#20122] opened 2018-08-02 01:43 UTC
## Steps to Reproduce

String.hashCode returns different values with same sequence.

This only happens when the app is running on iOS simulator/device.

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
    home: new MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return new MyAppState();
  }
}

class MyAppState extends State<MyApp> {
  final Map<Object, dynamic> map = <Object, dynamic>{};
  
  Foo foo1;
  Foo foo2;
  
  @override
  void initState() {
    super.initState();
    
    foo1 = _foo("test");
    foo2 = _foo("test");
    
    // this is that!
    map[foo1] = foo1;
  }
  
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text("String.hashCode"),
      ),
      body: new Container(
        padding: const EdgeInsets.all(20.0),
        child: new Column(
          children: <Widget>[
            new Text("${foo1.name} ${foo1.name.hashCode}"),
            new Text("${foo2.name} ${foo2.name.hashCode}"),
          ],
        ),
      ),
    );
  }
}

Foo _foo(String name) {
  return new Foo("prefix-${name}", "value");
}

class Foo {
  const Foo(this.name, this.value);
  
  final String name;
  final String value;
  
  @override
  int get hashCode {
    return identityHashCode(name) ^ identityHashCode(value);
  }
  
  @override
  bool operator ==(other) {
    if (identical(this, other)) {
      return true;
    }
    return other is Foo 
      && this.name == other.name 
      && this.value == other.value;
  }
}
```

Therefore, String can not be used as the key of Map.

## Logs

```
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.12.6 16G1314, locale ja-JP)
    • Flutter version 0.5.1 at /Applications/flutter
    • Framework revision c7ea3ca377 (9 weeks ago), 2018-05-29 21:07:33 +0200
    • Engine revision 1ed25ca7b7
    • Dart version 2.0.0-dev.58.0.flutter-f981f09760

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/najeira/Library/Android/sdk
    • Android NDK at /Users/najeira/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/najeira/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.1.3
    • Dart plugin version 181.4203.498

[!] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected devices (1 available)
    • iPhone X • 3264D9F7-7AB5-4C13-8863-85CEC0730DB1 • ios • iOS 11.2 (simulator)
```

I tested it on v0.4.4, v0.5.1, v0.5.7.

**Comment by najeira** [comment] 2018-08-02 07:32
Thank you very much for replying.

The actual output is this:

```
flutter: 'hoge-test' 849354836
flutter: 'hoge-test' 455516103
```

- `someFunc` makes a string like `return "prefix-${value}"`.
- It occurs in debug and release on iOS. not occurs on Android.
- It occurs with both Latin and Japanese strings.

I found that when `someFunc` is changed to `return value` from `return "prefix-${value}"`, it does not occur.

**Comment by mraleph** [comment] 2018-08-02 07:35
@najeira just to clarify: does you function actually say `return "hoge-${value}"` (based on the output)?

**Comment by najeira** [comment] 2018-08-02 07:43
@mraleph No, it's more complicated.

My code like this:

```
class Foo {
  Foo(this.name);
  final String name;
}

Foo someFunc(String name) {
  return new Foo("prefix-${name}");
}
```

```
foo1 = someFunc("test");

// ...

foo2 = someFunc("test");

// ...

debugPrint(foo1.name == foo2.name); // true
debugPrint(foo1.name.hashCode == foo2.name.hashCode); // false
```

**Comment by najeira** [comment] 2018-08-02 07:51
If debugPrint is inserted after someFunc, there is no problem.

```
var foo1 = someFunc("test");
debugPrint("${foo1.name} ${foo1.name.hashCode}"); // prefix-test 795436880

// ...

var foo2 = someFunc("test");
debugPrint("${foo2.name} ${foo2.name.hashCode}"); // prefix-test 795436880

// ...

debugPrint(foo1.name == foo2.name); // true
debugPrint(foo1.name.hashCode == foo2.name.hashCode); // true
```

**Comment by mraleph** [comment] 2018-08-02 08:33
I think we might need a reproduction of this to actually figure it out - I reviewed logic for hash computation and it does not seem like there are any bugs there. 

I have tried to trigger various misoptimizations - but so far I was not successful.

**Comment by najeira** [comment] 2018-08-02 09:54
@mraleph I found the reproduction code, I updated the first comment.

The followings are important for this:

- `Foo` overrides `hashCode` and use `identityHashCode`.
- Inserting `Foo` object to `Map` as key.

**Comment by mraleph** [comment] 2018-08-02 10:02
Thanks for the additional information! Reduction: 

```dart
make(v) => 'x${v}';

void main() {
  final x = make('test');
  final y = make('test');
  identityHashCode(y);  // initialize hidden hash field with identity hash.
  print(x.hashCode == y.hashCode);  // will print false on x64 and ARM64.
}
```

The issue is that `identityHashCode` should treat strings and some other types specially when we cache object hash in the object header.

I will submit a fix upstream.

**Comment by mraleph** [comment] 2018-08-02 10:37
The fix is uploaded upstream: https://dart-review.googlesource.com/c/sdk/+/68042

**Comment by mraleph** [comment] 2018-08-02 11:57
The fix has landed upstream. Waiting for the roll into Flutter to pick it up.

**Comment by mraleph** [comment] 2018-08-20 13:56
Dart with a fix has reached Flutter. Closing.

**Closed by mraleph** 2018-08-20 13:56 UTC
Labels: dependency: dart, waiting for PR to land (fixed)
