### ISSUE TITLE
Duplicate classes error on android when including firebase packages

### ISSUE THREAD

**Issue by nateshmbhat** [flutter/flutter#61696] opened 2020-07-17 05:18 UTC
I have developed a flutter plugin called "card_scanner" which uses "firebase's ML vision kit" as the native android dependency.

When a user includes "card_scanner" in his pubspec.yaml and also includes the "firebase" flutter packages , then there occurs a Duplicate classes error.

`java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.firebase.components.AbstractComponentContainer found in modules firebase-common-19.2.0-runtime.jar (com.google.firebase:firebase-common:19.2.0) and jetified-firebase-components-16.0.0-runtime.jar (com.google.firebase:firebase-components:16.0.0)
`

I guess the issue is because , in android build.gradle i am using the ML kit vision library which in turn uses the firebase-common and firebase-components libraries.

This is my native android `build.gradle` of `card_scanner` library.

```
implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.gms:play-services-mlkit-text-recognition:16.1.0'


    def camerax_version = "1.0.0-beta03"
// CameraX core library using camera2 implementation
    implementation "androidx.camera:camera-camera2:1.0.0-beta06"
// CameraX Lifecycle Library
    implementation "androidx.camera:camera-lifecycle:$camerax_version"
// CameraX View class
    implementation "androidx.camera:camera-view:1.0.0-alpha13"
```

More Details here : 
[https://github.com/nateshmbhat/card-scanner-flutter/issues/9](https://github.com/nateshmbhat/card-scanner-flutter/issues/9
)

### Flutter Doctor : 
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.2 19C57, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2019.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.47.0)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment] 2020-07-17 10:56
Hi @nateshmbhat 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-07-17 10:56 UTC
