### ISSUE TITLE
Dart/Flutter Language inheritance of optional params and static class fields issues.

### ISSUE THREAD

**Issue by wyattbiker** [flutter/flutter#32847] opened 2019-05-16 23:11 UTC
**(I cross posted this to dart-lang/sdk)**

1. Shouldn't the subclass constructor, automatically know the optional fields of it's parent?
2. Shouldn't an instance of a subclass have access to static of it's parent?

If I create a subclass of a Flutter Widget, I would need to list all the optional parameters in the subclass constructor? There could be tens of these, including actions (e.g. onTap). This means if I change a widget to a child widget, I have to initialize the complete optionals as instance variables. I know this can be fixed with `dart:mirrors` but its not supported with Flutter. Is there some other way of coding this?

Below is a very simple example where `width` is not accessible as an optional parameter by child constructor.

Also, static `height` is not accessible by the child class constructor.

```dart
// Parent widget
class PWidget {
  String color = 'red';
  int width;
  static int height = 5;
  PWidget(this.color, {this.width});
}

// Child Widget
class CWidget extends PWidget {
  @override
  String color = 'green';
  CWidget(String color) : color = color, super(color);
}

main() {
  // Width is only define in parent so cannot be accessed 
  CWidget c = CWidget('blue', width: 10);
  // Static height cannot be accessed.
  print(CWidget.height);
}
```

**Comment by VladyslavBondarenko** [comment] 2020-07-29 14:32
Closing as duplicate of https://github.com/dart-lang/language/issues/367, https://github.com/dart-lang/language/issues/368

**Closed by VladyslavBondarenko** 2020-07-29 14:32 UTC
Labels: dependency: dart, framework
