### ISSUE TITLE
SelectionArea Didn’t Match The Expected Behavior with Text.rich

### ISSUE THREAD

**Issue by zhouxiaofu** [flutter/flutter#134520] opened 2023-09-12 10:31 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Long press to select all

### Expected results

All text should be selected

### Actual results

When using Text.rich in SelectionArea, if there is a WidgetSpan in it, the text after this line will not be selected.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(SelectionAreaExampleApp());

class SelectionAreaExampleApp extends StatelessWidget {
  final FocusNode focusNode = FocusNode();

  SelectionAreaExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    TextStyle style = const TextStyle(color: Colors.black);
    return MaterialApp(
      home: SelectionArea(
        magnifierConfiguration: TextMagnifier.adaptiveMagnifierConfiguration,
        child: Scaffold(
          appBar: AppBar(title: const Text('SelectionArea Sample')),
          body: ListView.builder(
            itemCount: 1000,
            itemExtent: 50,
            itemBuilder: (BuildContext context, int index) => Container(
              height: 50,
              alignment: Alignment.center,
              child: Text.rich(TextSpan(children: [
                TextSpan(text: "row $index 1", style: style),
                const WidgetSpan(child: SizedBox(width: 10)),
                TextSpan(text: "row $index 2", style: style),
                const WidgetSpan(child: SizedBox(width: 10)),
                TextSpan(text: "row $index 3", style: style)
              ])),
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/flutter/flutter/assets/34471928/98ec29c7-74fb-42fb-8244-43dd5152ebce)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
PS E:\flutter\flutter_demo> flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [版本 10.0.22621.2134], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Ultimate Edition (version 2023.1)
[√] Connected device (4 available)
[!] Network resources             
    X An HTTP error occurred while checking "https://github.com/": 信号灯超时时间已到


! Doctor found issues in 3 categories.

```

</details>

**Comment by darshankawar** [comment] 2023-09-12 12:36
Thanks for the report. I was able to replicate this using latest stable and master versions. Using `select all` from selection bar doesn't select all the text.
Also, on desktop and web, using trackpad and trying to select all text isn't possible as it gets stuck as shown in the screenshots section.

Maybe related to https://github.com/flutter/flutter/issues/127942 ?

/cc @hangyujin

**Comment by zhouxiaofu** [comment] 2023-09-13 02:09
If there is WidgetSpan->Sizebox, the last text cannot be selected.

```dart

Text.rich(TextSpan(children: [
                TextSpan(text: "row $index 1", style: style),
                const WidgetSpan(child: SizedBox(width: 10)),
                TextSpan(text: "row $index 2", style: style),
                const WidgetSpan(child: SizedBox(width: 10)),
                TextSpan(text: "row $index 3", style: style)
              ])

```

**Comment by nidhiignite** [comment] 2023-09-23 17:58
If you set **height** of **SizedBox** , then it will work. 
Text.rich(TextSpan(children: [
         TextSpan(text: "row1", style: style),
         const WidgetSpan(child: SizedBox(width:10,height: 10,)),
         TextSpan(text: "row2", style: style),
         const WidgetSpan(child: SizedBox(width:10,height: 10,)),
         TextSpan(text: "row3", style: style),

**Comment by zhouxiaofu** [comment] 2023-10-09 02:42
> @zhouxiaofu @darshankawar 如果您设置**SizedBox**的**高度**，那么它就会起作用。****
> 
> Text.rich(TextSpan(children: [ TextSpan(text: "行 $index 1", style: style), const WidgetSpan( child: SizedBox( 宽度: 10, height: 10, )), TextSpan(text: "行 $索引 2", 样式: 样式), const WidgetSpan( child: SizedBox( 宽度: 10, 高度: 10, )), TextSpan(文本: "行 $index 3", 样式: 样式) ])),

After setting the height, the SizedBox is blank after selection.
![Screenshot_2023-10-09-10-36-35-651_com example flutter_demo](https://github.com/flutter/flutter/assets/34471928/7d24a329-daea-4807-9c5a-067d58304a6d)

**Comment by Renzo-Olivares** [comment] 2024-04-24 20:35
@zhouxiaofu Can you confirm this is still an issue on `master`? There have been some recent changes that may have improved the situation. I have tested this locally on my pixel 8 pro and it seems to work as expected.

**Comment by annd22** [comment] 2024-05-14 10:47
Confirm this issue on latest version of flutter: https://dartpad.dev/?id=fe3dad732641b84aabac2b19856c7552

![image](https://github.com/flutter/flutter/assets/83078116/768b4680-f40a-4783-9ab5-11d82b4f5352)

As you can see, the block code `asdsa` is not selected, and in a real life desktop chat application, which has many markdowns like mention, emoji, hyperlink, link,..., it will have a lot of combination of WidgetSpan and TextSpan in a chat message. 

I am facing this issue and my chat application has a terrible selection experience when users cannot select chat message smooth.


> @zhouxiaofu Can you confirm this is still an issue on `master`? There have been some recent changes that may have improved the situation. I have tested this locally on my pixel 8 pro and it seems to work as expected.

**Comment by Renzo-Olivares** [comment] 2024-05-14 18:08
@annd22 Sorry, just to confirm is this using the `master` branch or the `stable` branch?

**Comment by annd22** [comment] 2024-05-15 02:28
Hi @Renzo-Olivares , the dartpad is using `stable`, and if I try with `main` branch as you said, the selection become smooth.

So I have to switch my project from `stable` to `main` branch to fix this issue?

**Comment by Renzo-Olivares** [comment] 2024-05-21 20:43
@annd22 Yes, that is the case until the fix lands in `stable`. I will close this issue since I have confirmed it is no longer reproducible, please feel free to re-open if this is not the case.

**Closed by Renzo-Olivares** 2024-05-21 20:43 UTC
Labels: waiting for customer response, framework, has reproducible steps, P2, f: selection, team-framework, triaged-framework, found in release: 3.13, found in release: 3.14
