### ISSUE TITLE
libflutter.so missing when add flutter to existing app

### ISSUE THREAD

**Issue by TedaLIEz** [flutter/flutter#48550] opened 2020-01-10 03:22 UTC
## Steps to Reproduce

1. include a flutter module to a native application according to [https://flutter.dev/docs/development/add-to-app/android/project-setup](https://flutter.dev/docs/development/add-to-app/android/project-setup)
2. my application `build.gradle` setting: 
```groovy

defaultConfig {
        applicationId rootProject.ext.applicationId
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName
        buildConfigField 'int', 'TINKER_FLAG', "${buildInfo_TINKER_FLAG()}"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi"
        }
        multiDexEnabled true
    }
```
3. application crashs

**Target Platform:** Android
**Target OS version/browser:** Android 10
**Devices:** OnePlus 7TPro

## Logs

```
exception:java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tencent.mp-2S0n9t6f7_XuEM6uoDUzbg==/base.apk"],nativeLibraryDirectories=[/data/app/com.test.app-2S0n9t6f7_XuEM6uoDUzbg==/lib/arm, /data/app/com.test.app-2S0n9t6f7_XuEM6uoDUzbg==/base.apk!/lib/armeabi, /system/lib, /product/lib]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:122)
        at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:93)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:183)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:152)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:142)
```

flutter doctor -v
```
[✓] Flutter (Channel master, v1.13.7-pre.41, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.13.7-pre.41 at /Users/fredguo/bin/flutter
    • Framework revision fa337f5922 (3 days ago), 2020-01-06 16:44:12 -0800
    • Engine revision 3851981b86
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 2f57602411)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/fredguo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/fredguo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2018.2.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • HD1910 • c0215d95 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
```

I found many issues similar, which says `libflutter.so` will be packaged in `armeabi-v7a`, I managed to change `abiFilters` settings to `armeabi-v7a` and it works. But for some reason, I have to use `armeabi`.

How can I include an `armeabi` version of `libflutter.so` to my build?

**Comment by jmagman** [comment] 2020-01-15 20:08
Duplicate of https://github.com/flutter/flutter/issues/45882

**Closed by jmagman** 2020-01-15 20:08 UTC
Labels: a: existing-apps, t: gradle, tool, ▣ platform-android
