### ISSUE TITLE
[Flutter 3] Web app fails to load in firefox if "Delete cookies and site data when Firefox is closed" is checked in settings

### ISSUE THREAD

**Issue by Velliane** [flutter/flutter#103972] opened 2022-05-17 11:43 UTC
Hello, 

I have a web app deployed with Firebase.
It's work fine with almost all browsers. But with Firefox, it gave me this error: `Failed to load app from service worker`

<img width="850" alt="Capture d’écran 2022-05-17 à 13 36 14" src="https://user-images.githubusercontent.com/44947503/168802356-cd429078-4f5f-497e-ad73-f4ec4c5af0e3.png">

Firefox version: 100.0

Flutter doctor -v:

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3 21E230 darwin-arm, locale fr-FR)
    • Flutter version 2.10.5 at /Users/appspanel/Documents/development/utils/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/appspanel/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554                        • android-arm64  • Android 10
      (API 29) (emulator)
    • iPhone 8 (mobile)                    • C0CAAD9F-196D-4329-9089-188F7A95FC53 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome
      101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

Thanks for your help

**Comment by kaboc** [comment] 2022-05-19 07:33
This happens even in a plain project unchanged after it is created with `flutter create`.
The web app does not start and the page on Firefox remains blank.

<img src="https://user-images.githubusercontent.com/20254485/169232012-05ae4ac8-be9b-46fd-864b-e6f9d7da82af.png">

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22000.675], locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] VS Code (version 1.67.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```
</details>

**Steps to reproduce**

1. Create a new project with `flutter create bug`.
2. Change the current directory to the new project with `cd path/to/the/project`.
3. Build a web app bundle with `flutter build web`.
4. Start an HTTP server with `dart pub global run dhttpd --path build/web`.
5. Open the developer tool and switch to its Console tab on Firefox.
6. Open `http://localhost:8080/` on Firefox.

**Comment by maheshmnj** [comment] 2022-05-23 13:04
Thanks for the reproducible steps @kaboc I am not able to reproduce the issue. Flutter app loads fine in firefox browser verified on both mac and windows



### windows 

<details>
<summary>logs</summary>

```
```
</details> 

### Mac 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31410839/169825186-0b9363df-a3e6-4209-bd62-4e85650d04af.png">

<details>
<summary>logs</summary>

```
mahesh@Maheshs-MacBook-Air-M1 newapp % flutter create .
Signing iOS app for device deployment using developer identity: "Apple Development: mahesh@nevercode.io (8QBZ8V54QM)"
Recreating project ....
  web/favicon.png (created)
  web/index.html (created)
  web/manifest.json (created)
  web/icons/Icon-maskable-512.png (created)
  web/icons/Icon-192.png (created)
  web/icons/Icon-maskable-192.png (created)
  web/icons/Icon-512.png (created)
Running "flutter pub get" in newapp...                           1,893ms
Wrote 10 files.

All done!
In order to run your application, type:

  $ cd .
  $ flutter run

Your application code is in ./lib/main.dart.

mahesh@Maheshs-MacBook-Air-M1 newapp % flutter build web

💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                             12.0s
mahesh@Maheshs-MacBook-Air-M1 newapp % dart pub global run dhttpd --path build/web.
No active package dhttpd.
mahesh@Maheshs-MacBook-Air-M1 newapp %  dart pub global activate dhttpd
+ args 2.3.1pendencies... (1.5s)
+ async 2.9.0
+ build_cli_annotations 2.0.0
+ collection 1.16.0
+ convert 3.0.1
+ dhttpd 4.0.1
+ http_parser 4.0.1
+ meta 1.8.0
+ mime 1.0.2
+ path 1.8.2
+ shelf 1.3.0
+ shelf_static 1.1.0
+ source_span 1.9.0
+ stack_trace 1.10.0
+ stream_channel 2.1.0
+ string_scanner 1.1.1
+ term_glyph 1.2.0
+ typed_data 1.3.1
Downloading dhttpd 4.0.1...
Downloading build_cli_annotations 2.0.0...
Downloading http_parser 4.0.1...
Downloading path 1.8.2...
Downloading meta 1.8.0...
Building package executables... 
Built dhttpd:dhttpd.
Installed executable dhttpd.
Activated dhttpd 4.0.1.
mahesh@Maheshs-MacBook-Air-M1 newapp % dart pub global run dhttpd --path build/web.
Unhandled exception:
Invalid argument(s): A directory corresponding to fileSystemPath "build/web." could not be found
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      Dhttpd.start (package:dhttpd/dhttpd.dart:41:21)
#2      main (file:///Users/mahesh/.pub-cache/hosted/pub.dartlang.org/dhttpd-4.0.1/bin/dhttpd.dart:22:16)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
mahesh@Maheshs-MacBook-Air-M1 newapp % dhttpd --path build/web/                    
Server started on port 8080
2022-05-23T18:13:37.503352  0:00:00.010687 GET     [200] /
2022-05-23T18:13:37.553104  0:00:00.000621 GET     [200] /flutter.js
2022-05-23T18:13:37.556086  0:00:00.000414 GET     [200] /icons/Icon-192.png
2022-05-23T18:13:37.557136  0:00:00.000320 GET     [200] /favicon.png
2022-05-23T18:13:37.559254  0:00:00.000301 GET     [200] /flutter_service_worker.js?v=653089107
2022-05-23T18:13:37.573781  0:00:00.000724 GET     [200] /main.dart.js
2022-05-23T18:13:37.574221  0:00:00.000487 GET     [200] /index.html
2022-05-23T18:13:37.575011  0:00:00.000834 GET     [200] /assets/NOTICES
2022-05-23T18:13:37.575383  0:00:00.000593 GET     [200] /assets/FontManifest.json
2022-05-23T18:13:37.575672  0:00:00.000422 GET     [200] /assets/AssetManifest.json
2022-05-23T18:13:38.762803  0:00:00.013273 GET     [304] /flutter_service_worker.js?v=653089107
2022-05-23T18:13:39.578492  0:00:00.001666 GET     [200] /assets/fonts/MaterialIcons-Regular.otf
2022-05-23T18:13:39.579610  0:00:00.001017 GET     [200] /assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by Velliane** [comment] 2022-05-23 16:44
Hello,

Sorry for this late response.
I found an explanation here: https://bugzilla.mozilla.org/show_bug.cgi?id=1429714
`Note, if you have cookies set to "Keep until I close firefox", we also block service workers.  This is because we don't have support for actually wiping non-cookie storage like Cache API, IDB, etc at the end of the browsing session yet. `
I was able to correct the error about the service worker, but I still can't load the app.

**Comment by maheshmnj** [comment] 2022-05-24 05:03
Thanks for the update @Velliane, Closing as solved based on the above response.

**Comment by kaboc** [comment] 2022-05-24 08:22
@maheshmnj 
There are three options in the cookie/history setting. I tried all of these:

- Remember history
- Never remember history
- Use custom settings for history

The sample app only worked with the second one. Do you think it is fine? It is very unlikely that users have switched browser history off. If it is right, web apps created with Flutter don't run on Firefox in most cases.

Additionally, I think this is an avoidable bug because it didn't exist in Flutter 2.10. Probably #100177 is related.

**Comment by maheshmnj** [comment] 2022-06-01 13:18
@kaboc Can you please help me with steps to verify this, On my side, it seems to work fine in firefox.

**Comment by kaboc** [comment] 2022-06-01 13:35
@maheshmnj 
Please try this:

1. Open the settings page of Firefox.
2. Click on "Privacy & Security" on the left column.
3. Find the History section and choose "Remember history" there.
4. Run a Flutter web app in the browser by following the steps I wrote before.
    - Make sure to use a **non**-private window.

**Comment by kaboc** [comment] 2022-06-01 14:28
@maheshmnj 
Thanks for the screencast. I compared it with my settings and found out how to reproduce the issue.

<img src="https://user-images.githubusercontent.com/20254485/171425340-7bd433f3-dbaf-4eeb-833b-41d1882243be.png" height="160">

I'm sorry, it seems the history setting was irrelevant. My app started successfully after I unchecked "Delete cookies and site data when Firefox is closed".

I'm not sure what percentage of users have the setting enabled. It may not affect so many people, but I think it is a bug / regression because it didn't happen in projects created with older Flutter versions. If it is not fixed, you'll have to tell your users to change their browser settings so that they can start using your app.

**Comment by kaboc** [comment] 2022-06-01 14:43
> it seems the history setting was irrelevant.

Let me correct myself. It's not totally irrelevant. Looks like it matters if the "Delete cookies ..." setting has been enabled.

**Comment by kaboc** [comment] 2022-06-08 07:20
@maheshmnj
Could you have a look again please? Otherwise this thread will be locked before long. As my personal opinion, I think this issue should be reopened.

**Comment by maheshmnj** [comment] 2022-06-08 07:32
Sorry for the delay @kaboc, I though I had responded.

**Comment by maheshmnj** [comment] 2022-06-08 07:41
I can reproduce the issue when trying to load a flutter web app (built using flutter 3 stable/master) in the firefox browser the app fails to load if  `Delete cookies and site data when Firefox is closed` is checked in firefox settings.

However with this settings enabled I see that the old flutter web apps seems to load

Error in the dev console when the app fails to load

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/31410839/172559530-c6c0baa0-dfdf-4811-9a49-ac950a92d867.png">



### steps to reproduce 


1.  Check `Delete cookies and site data when Firefox is closed` in firefox settings under privacy
2. Try to load a newly created flutter web app (with flutter 3)  and the one created using flutter 2

Here are a few of the  sample apps for quick reproduction with the deployed version

flutter stable 2.10.3: https://textfield.netlify.app/
flutter stable 2.5 or 2.8: https://flutterlistview.netlify.app/

flutter master 3.1.0: https://chromebug.netlify.app/


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1138, on macOS 12.4 21F79 darwin-arm, locale en-IN)
    • Flutter version 3.1.0-0.0.pre.1138 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9be807192 (26 hours ago), 2022-06-06 21:16:49 -0700
    • Engine revision 48864fc837
    • Dart version 2.18.0 (build 2.18.0-170.0.dev)
    • DevTools version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 6AE1D692-DB57-4C3E-ADCA-66842182426B • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-06-08 07:44
cc: @yjbanov

**Comment by rillbert** [comment] 2022-06-08 11:49
I just want to chime in since I believe that I see the same behavior and it has been driving me crazy the last couple of days.
 
My development environment:

1. An ubuntu box with
- VSCode (with latest flutter/dart tools)
- Firefox
- Chrome

2. A raspberry pi running a web server (nginx)

To deploy the web app to the raspberry I do:

1. `flutter build web`
2. Copy the resulting `build/web` catalogue to the nginx deployment catalogue on the raspberry pi.
3. Browse to the raspberry's ip address using Firefox
4. Browse to the raspberry's ip address using Chrome

The result:
- Firefox always displays the same version of my flutter web application as the first time I loaded the web page. Using 'F5' to refresh the page do not have any effect.
- Chrome displays the newest version when refreshing the page using 'F5'.

The only ways I have found to clear the firefox cache and thus reload the app is to go to 
`preferences->privacy & security`, under `Cookies & Site data` click on `Clear Data` and select `Cached Web content` for deletion.

After this, I will see the latest version of the flutter app when hitting 'F5'.

This might be regarded as a bug in Firefox but all the same, it is in the case of flutter development where this has bitten me..

...and yes, I also run Firefox with the setting 'Delete cookies and site data when Firefox is closing'.

---- 

Flutter doctor output:

13:35 $ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.1, on Ubuntu 20.04.4 LTS 5.13.0-44-generic, locale en_US.UTF-8)
    • Flutter version 3.0.1 at /home/andersr/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.67.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.4 LTS 5.13.0-44-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by maheshmnj** [comment] 2022-06-08 13:28
Not sure if this change was intentional, Adding a regression label since the old flutter apps (created prior to flutter 3) load fine with the [firefox settings specified](https://github.com/flutter/flutter/issues/103972#issuecomment-1149573718).

**Comment by rillbert** [comment] 2022-06-08 15:17
I have indications that MS Edge behaves the same way but can not test this  in a more controlled way.

**Comment by ditman** [comment] 2022-06-15 23:24
I've posted a PR with a fix above, people may test my "fixed" flutter.js here:

* https://dit-bootstrap-tests.web.app

(This file could be used to workaround the problems for those affected: https://dit-bootstrap-tests.web.app/firebase.js)

**Comment by ditman** [comment] 2022-06-17 17:54
The fix for this is now available in Flutter channel `master`.

**Closed** 2022-06-17 17:54 UTC
Labels: severe: regression, tool, platform-web, a: release, has reproducible steps, browser: firefox, assigned for triage, found in release: 3.0, found in release: 3.1
