### ISSUE TITLE
[Impeller] Picture.toImageSync may return null when Impeller is enabled.

### ISSUE THREAD

**Issue by KoheiKanagu** [flutter/flutter#124181] opened 2023-04-05 03:36 UTC
## Steps to Reproduce

1. build in release mode with Impeller enabled.
2. when you run the application on an actual iOS device, an exception will occur at `toImageSync`.
3. the first time you install the app on the actual device and run it for the first time, the exception may not occur. Try to kill the app once and then run it again.

If you disable Impeller, this exception will not occur, so I think Impeller is related to this.

**Expected results:** 

Must not result in a null exception.

**Actual results:** 

As you can see in the attached log, I get an Exception and cannot draw the image.

<details>
<summary>Code sample</summary>

Here is a sample repository.
https://github.com/KoheiKanagu/flutter_issue_to_image_sync

```dart
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: FutureBuilder(
            builder: (context, snapshot) {
              if (snapshot.hasError) {
                print(snapshot.error);
              }

              final data = snapshot.data;
              if (data != null) {
                return Image(
                  image: data,
                );
              }
              return const CircularProgressIndicator();
            },
            future: canvasToMemoryImage(16),
          ),
        ),
      ),
    );
  }
}

Future<MemoryImage> canvasToMemoryImage(int size) async {
  final paint = Paint()..color = Colors.red;

  final recorder = PictureRecorder();
  final canvas = Canvas(recorder);

  canvas.drawCircle(Offset.zero, 10, paint);

  final picture = recorder.endRecording();

  final image = picture.toImageSync(size, size); // Image was null
  final byteData = await image.toByteData(
    format: ImageByteFormat.png,
  );
  final result = MemoryImage(
    byteData?.buffer.asUint8List() ?? Uint8List(0),
  );
  return result;
}
```

</details>

<details>
  <summary>Logs</summary>

This log was checked with the macOS console app.

```log
12:10:50.943691+0900	Runner	[VERBOSE-2:image_encoding_impeller.cc(66)] Image was null.
12:10:50.943852+0900	Runner	[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _Image.toByteData.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:1891)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.2.1 22D68 darwin-arm64, locale ja-JP)
    • Flutter version 3.7.9 on channel stable at /Users/kingu/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 62bd79521d (5 days ago), 2023-03-30 10:59:36 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/kingu/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /Users/kingu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode-14.2.0.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Users/kingu/Develop/global/dotfiles/google-chrome-unsafe.sh

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] VS Code (version 1.78.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (5 available)
    • KingPad K10 (mobile)            • VKK104GJP0000443                     • android-arm64  • Android 10 (API 29)
    • KiPhone 14 Pro (mobile)         • 00008120-001159C40CEB401E            • ios            • iOS 16.3.1 20D67
    • iPad (10th generation) (mobile) • 5D03F545-E381-4681-86B9-FF00A4C904AF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 111.0.5563.146
    ! Error: Apple Watch Series 5 needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need
      to be restarted and unlocked. (code 1)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by KoheiKanagu** [comment] 2023-04-05 05:15
If you use toImage as follows, no Image object will be returned.
```dart
final image = await pictureInfo.picture.toImage(size, size);
```

Maybe the image is null.
https://github.com/flutter/engine/blob/f95b1f65a81beb06e71730fa79d27ddb01adf543/lib/ui/painting.dart#L6025-L6026

**Comment by exaby73** [comment] 2023-04-05 08:23
Hello @KoheiKanagu. Could you provide a code sample that reproduces the issue but that does not use any 3rd party libraries?

**Comment by KoheiKanagu** [comment] 2023-04-05 08:58
Hello! @exaby73 

Fixed the sample code to not use 3rd party libraries.
The problem continues to occur.

**Comment by exaby73** [comment] 2023-04-05 12:55
Are you able to reproduce this issue with the master channel? Also, does this occur in a physical device, simulator or both?

**Comment by KoheiKanagu** [comment] 2023-04-06 01:30
The problem was reproduced on the master channel.

This problem seems to occur only on release builds, so it is happening only on physical devices.

```log
flutter doctor -v
[✓] Flutter (Channel master, 3.9.0-22.0.pre.48, on macOS 13.2.1 22D68 darwin-arm64, locale ja-JP)
    • Flutter version 3.9.0-22.0.pre.48 on channel master at /Users/kingu/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 667220c9fc (52 minutes ago), 2023-04-05 20:33:09 -0400
    • Engine revision 610cdf0ae1
    • Dart version 3.0.0 (build 3.0.0-411.0.dev)
    • DevTools version 2.23.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/kingu/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = /Users/kingu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode-14.2.0.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Users/kingu/Develop/global/dotfiles/google-chrome-unsafe.sh

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] VS Code (version 1.78.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (5 available)
    • KingPad K10 (mobile)            • VKK104GJP0000443                     • android-arm64  • Android 10 (API 29)
    • KiPhone 14 Pro (mobile)         • 00008120-001159C40CEB401E            • ios            • iOS 16.3.1 20D67
    • iPad (10th generation) (mobile) • 5D03F545-E381-4681-86B9-FF00A4C904AF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 111.0.5563.146
    ! Error: Apple Watch Series 5 needs to connect to determine its availability. Check the connection between the device and its companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need
      to be restarted and unlocked. (code 1)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2023-04-06 07:18
Hi @KoheiKanagu, when I run your sample, I see only `CircularProgressIndicator`. 

Is this the same case for you as well?

**Comment by KoheiKanagu** [comment] 2023-04-06 07:36
Hello! @danagbemava-nc 
Yes, it shows `CircularProgressIndicator` and no Image.

If you look at the log in the macOS console app then, I think you see exception.
```log
12:10:50.943691+0900	Runner	[VERBOSE-2:image_encoding_impeller.cc(66)] Image was null.
12:10:50.943852+0900	Runner	[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _Image.toByteData.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:1891)
```

**Comment by danagbemava-nc** [comment] 2023-04-06 13:01
Thanks for the confirmation. 

The issue is reproducible using the code sample in https://github.com/flutter/flutter/issues/124181#issue-1654875213 in `release` & `profile` mode. In `debug` mode it works just fine and the image is displayed properly. 

The logs below are captured from `profile` mode. 


```
[VERBOSE-2:image_encoding_impeller.cc(88)] Image was null.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _Image.toByteData.<anonymous closure>.<anonymous closure> (dart:ui/painting.dart:1959)

```

<details>
<summary>flutter doctor -v</summary>


```
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3 22E252 darwin-arm64, locale en-GB)
    • Flutter version 3.7.10 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (3 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 16.4 20E247
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 111.0.5563.146

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[!] Flutter (Channel master, 3.9.0-22.0.pre.56, on macOS 13.3 22E252 darwin-arm64, locale en-GB)
    • Flutter version 3.9.0-22.0.pre.56 on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 822632b510 (7 hours ago), 2023-04-05 23:04:50 -0700
    • Engine revision 1ec74c62fd
    • Dart version 3.0.0 (build 3.0.0-411.0.dev)
    • DevTools version 2.23.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9619390/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.1)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/221.6008.13.2211.9477386/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 73.0.4
    • Dart plugin version 231.8109.91

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.8109.175/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.77.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • Nexus (mobile)  • 00008020-001875E83A38002E • ios            • iOS 16.4 20E247
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 13.3 22E252 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 111.0.5563.146
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```
</details>

**Comment by jason-simmons** [comment] 2023-04-06 20:47
@dnfield What is the fallback strategy if `SnapshotControllerImpeller::DoMakeRasterSnapshot` is called before the surface and `AiksContext` are available?

**Comment by dnfield** [comment] 2023-04-06 21:05
@ColdPaleLight did that implementation.  I'm not sure we ca have a fallback there without a CPU based backend.

However, we can probably do something via the texture registry API (or something like it) so that the DL deferred image doesn't try to rasterize until the snapshot controller is ready.

**Comment by chinmaygarde** [comment] 2023-04-10 17:57
From Triage: Not sure why this needs a surface. But we should rework this to access the context instead to fix the race. Marking this as a candidate for cherry-picking.

**Comment by dnfield** [comment] 2023-04-11 03:28
Oh! The problem isn't with toImageSync, it's with `toByteData`...

**Closed** 2023-04-14 03:02 UTC
Labels: severe: crash, platform-ios, engine, a: release, has reproducible steps, P4, impeller, found in release: 3.7, found in release: 3.9
