### ISSUE TITLE
Obscured text(points) with custom fontFamily are jumping while typing

### ISSUE THREAD

**Issue by XuanTung95** [flutter/flutter#147279] opened 2024-04-24 02:46 UTC
### Steps to reproduce

This reopen #59854 because it is locked.

1. Create a TextField with obscureText: true
2. Input letter then input number

### Expected results

2. The dot characters are not jumping while typing the number character

### Actual results

2. The dot characters are jumping while typing the number character 
(Reproducible when the last character is visible for a brief moment, tested on Android, other OS may not show the last input character)

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    theme: ThemeData(
      fontFamily: 'Inter',
    ),
    home: Scaffold(
      body: Center(
        child: const TextField(obscureText: true),
      ),
    ),
  ));
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://user-images.githubusercontent.com/42138594/85150554-5a00ee80-b25b-11ea-96b9-effafd7b6c2f.gif

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.0 23A344 darwin-x64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.88.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

```

</details>

**Comment by XuanTung95** [comment] 2024-04-24 09:25
Hi @danagbemava-nc 

Could you try to input letters then numbers, like "aaaa1234"
Also can you try with custom fontFamily: 'Inter'.

**Comment by LongCatIsLooong** [comment] 2024-04-25 07:58
This font probably supports the [case](https://learn.microsoft.com/en-us/typography/opentype/spec/features_ae#case) font feature and that's why it shifts up when you enter upper case characters. Try disable this font feature in the `TextStyle`?

**Comment by XuanTung95** [comment] 2024-04-25 08:55
Enabling the case-sensitive with `fontFeatures: [const FontFeature.caseSensitiveForms()]` seems fix the issue.

**Comment by justinmc** [comment] 2024-05-02 22:16
@LongCatIsLooong Should we close this then, or is there anything we can do to help people avoid this problem? Enable that automatically when obscured or something?

**Comment by LongCatIsLooong** [comment] 2024-05-03 03:01
Closing since this seems to be working as intended.

**Closed by LongCatIsLooong** 2024-05-03 03:01 UTC
Labels: a: text input, platform-android, framework, has reproducible steps, P3, workaround available, found in release: 3.19, team-text-input, triaged-text-input, found in release: 3.22
