### ISSUE TITLE
Error: Superclass has no method named 'inheritFromElement'.

### ISSUE THREAD

**Issue by AzilMahdi** [flutter/flutter#80277] opened 2021-04-12 14:08 UTC
hello 
i was working on a shop app following a course and i accidently clicked on UPGRADE PACKAGES
![upgrade icon](https://user-images.githubusercontent.com/76602806/114407767-a75e9b80-9ba0-11eb-82f1-e42e5811364f.jpg)

AND NOW EVERY TIME I RUN MY APP IT RETURNS THIS MESSAGE 

![ERROR](https://user-images.githubusercontent.com/76602806/114407932-d4ab4980-9ba0-11eb-8f9e-6dbd17346460.jpg)

**Comment by TahaTesser** [comment] 2021-04-13 06:57
Hi @AzilMahdi 
Looks like you're running older third-party packages on a newer flutter version, update the 

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rrousselGit/provider/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-13 06:57 UTC
Labels: in triage
