### ISSUE TITLE
Text anti-aliasing broken in Flutter 3.3.0

### ISSUE THREAD

**Issue by HaijunWei** [flutter/flutter#110738] opened 2022-09-01 02:33 UTC
Text or Container border looks jagged on Android, normal on Apple.

Not all pages will be jagged, such as the following code, the comment `Divider` can be displayed normally.
Or modify the height of `_Statistics` to display normally. On my device height 10 or 86 reproduces the problem.

On my device this problem only occurs with scrollable components.

![271661998860_ pic](https://user-images.githubusercontent.com/7686137/187818500-83652ce4-8ffe-4da8-8fcf-5f8140e9d8e8.jpg)

<details>
<summary>Code</summary>

``` dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: CupertinoButton(
          child: const Text('Click'),
          onPressed: () {
            Navigator.of(context).push(CupertinoPageRoute(
              builder: (context) => const Page1(),
            ));
          },
        ),
      ),
    );
  }
}

class Page1 extends StatelessWidget {
  const Page1({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: CustomScrollView(
        slivers: [
          const _Statistics(),
          SliverList(
            delegate: SliverChildBuilderDelegate(
              (context, index) {
                return Container(
                  margin: const EdgeInsets.fromLTRB(16, 0, 16, 10),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Column(
                    children: const [
                      Text(
                        'BTC Staking',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      Text(
                        '0.2 BTC',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      Text(
                        '0 BTC Earns',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w500,
                          color: Color(0xFF35B589),
                        ),
                      ),
                      Text(
                        '0 BTC Earns',
                        style: TextStyle(
                          fontSize: 14,
                          color: Color(0xFF35B589),
                        ),
                      ),
                      Divider(),
                    ],
                  ),
                );
              },
              childCount: 1,
            ),
          ),
        ],
      ),
    );
  }
}

class _Statistics extends StatelessWidget {
  const _Statistics({super.key});

  @override
  Widget build(BuildContext context) {
    return SliverToBoxAdapter(
      child: Container(
        height: 10,
        color: Colors.red,
      ),
    );
  }
}

```

</details>

<details>
<summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.4 21F79 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

<details>
<summary>Device</summary>

Brand: Xiaomi Civi
Screen size:  6.5 inch
Resolution: 2400 * 1080

</details>

**Comment by seanharding** [comment] 2022-09-01 02:37
I've been having some similar problems, but on iOS. Been trying to narrow it down enough to submit a bug report. Earlier I had one where there were a bunch of TextButtons embedded into a GridView. Replacing the TextButton with a GestureDetector + Padding solved the problem in that case. But I'm not confident that I have figured out the root cause, and I have seen reports of similar problems in other parts of my app that involve neither TextButtons nor GridViews. 

One thing I noticed in the GridView case is that it seemed to initially render ok for the parts that were on-screen, but as soon as I scrolled, the stuff that was off-screen looked jaggedy, and scrolling back up, the part that was originally on-screen looked jaggedy too. Also for some reason in this specific case, it seemed like only one column of items in the GridView was affected. (I know this all seems random, and that's why I didn't file an Issue of my own until I isolated the problem more. But I wanted to throw it out there in case it helps.)

**Comment by seanharding** [comment] 2022-09-01 02:39
Here's a screenshot where you may be able to see that the item in the third column has this aliasing issue. It's not just the text, but also the border on the Container.

![Simulator Screen Shot - iPhone 13 mini - 2022-08-31 at 13 52 40](https://user-images.githubusercontent.com/2908560/187820438-1f981aee-d11a-48e0-82f9-c3b75ee53d54.png)

**Comment by HaijunWei** [comment] 2022-09-01 02:41
> Here's a screenshot where you may be able to see that the item in the third column has this aliasing issue. It's not just the text, but also the border on the Container.
> 
> ![Simulator Screen Shot - iPhone 13 mini - 2022-08-31 at 13 52 40](https://user-images.githubusercontent.com/2908560/187820438-1f981aee-d11a-48e0-82f9-c3b75ee53d54.png)

Yes, I just found that the border will also have jaggedness, and the problem has been supplemented.

**Comment by elliotrtd** [comment] 2022-09-01 07:32
I have also found the same with AlertDialogs. The dialog itself, title and content all had the same issue. This was on Android - I'm not able to test on iOS currently. 

![image](https://user-images.githubusercontent.com/43793032/187857594-b8484e04-35ce-4bca-bf72-09af518e647c.png)

I'm going to see if I can reproduce this at all in a very basic app to provide some code. 

For anyone else with the same - in one case switching to a SimpleDialog and adding a row with the actions I wanted below worked for the content. May help but ultimately did not 100% for me.

**Comment by bleroux** [comment] 2022-09-01 07:54
@jonahwilliams Could this issue be related to fractional support? https://github.com/flutter/flutter/issues/107733#issuecomment-1221022815
It seems somewhat similar to what @jpnurmi described on desktop: https://github.com/flutter/flutter/issues/107733#issuecomment-1221265160

**Comment by alexmercerind** [comment] 2022-09-01 10:36
Flutter 3.3.0 was hurried, let's be honest.

**Comment by exaby73** [comment] 2022-09-01 11:49
I can't really reproduce this issue on my Windows machine (1080p, 15" screen) or my Macbook Air M1. Labelling for further insights from the team.

**Comment by seanharding** [comment] 2022-09-01 13:29
Just to be clear, this is labeled platform-android, but I am seeing this (and my screenshot above) is iOS. Similar to @elliotrtd, I have also had testers show me screenshots of the problem in AlertDialogs (again, on iOS).

**Comment by nimr77** [comment] 2022-09-01 14:30
It's on the web and desktop too,  in my case I had to wrap the column that has the ```Text``` widget with ```SingleChildScrollView```

**Comment by seanharding** [comment] 2022-09-01 15:11
This code below reproduces it for me. It renders correctly initially, but if you scroll down to push the text up and under the app bar, when you let go, part of it comes back pixelated (on my simulator iPhone 13 Mini, it's the 3rd item only). If I change the padding amount in the `Padding` widget to 0, the problem does not seem to happen. Padding of even 1 does cause it to happen (I have not exhaustively tested all padding values to see if some reproduce it and some don't, but 0 does not, while 1 and 8 do).

The larger text size is not required, but does make it easier to see the issue.

```
class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Issue 110738"),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: GridView.builder(
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 4,
              childAspectRatio: 0.7,
              crossAxisSpacing: 4,
              mainAxisSpacing: 0),
          itemCount: 4,
          itemBuilder: (BuildContext ctx, index) {
            return TextButton(
              onPressed: () => print("Pressed"),
              child: Container(
                child: AspectRatio(
                  aspectRatio: 1,
                  child: Text(
                    "Hello, World",
                    style: TextStyle(fontSize: 24),
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

**Comment by elliotrtd** [comment] 2022-09-02 04:55
> It's on the web and desktop too, in my case I had to wrap the column that has the `Text` widget with `SingleChildScrollView`

That's helped with the AlertDialog issue too! If I set the AlertDialog to scrollable: true then the issue is not visible. Thanks!

**Comment by liu731** [comment] 2022-09-02 10:40
[Flutter 3.3.0] Reproduce a specific device and complex Widget Tree

Device parameters:
device Redmi Note 9(M2010J19SC)
processor Qualcomm Snapdragon 662
resolution 2340*1080
android 11

Looks like
1. The rounded corners (Clip.hardEdge) have obvious jaggedness and exceed the specified size range
2. Image and Text are blurry
3. Appears to shake left and right when scrolling

If run with "--enable-software-rendering", everything is solved. But this is not acceptable.

Unable to reproduce on iPhone 12 and some other Android devices

**Comment by hlwhl** [comment] 2022-09-02 10:49
> Just to be clear, this is labeled platform-android, but I am seeing this (and my screenshot above is) on iOS. Similar to @elliotrtd, I have also had testers show me screenshots of the problem in AlertDialogs (again, on iOS).
> 
> For now we are rolling back to 3.0.5 but I will continue watching this Issue for updates…

Met the same issue on macOS and Windows.

**Comment by moffatman** [comment] 2022-09-02 14:42
I believe it's caused by pixel snapping being removed. I have used this change in local engine to fix, but I guess it's not appropriate to merge? https://github.com/flutter/engine/pull/35538

**Comment by armandojimenez** [comment] 2022-09-02 23:23
Happens in my app using AlertDialogs only on iOS, does not happen in 3.0.5

**Comment by armandojimenez** [comment] 2022-09-02 23:30
Some images:
Flutter 3.0.5
![IMG_8939](https://user-images.githubusercontent.com/28992210/188246171-9ce08fa1-156d-451f-a2fe-bd1b195a9c7b.jpg)

Flutter 3.3
![IMG_8941](https://user-images.githubusercontent.com/28992210/188246186-20651729-dc26-44e3-837e-b39614c2f35e.jpg)

This is only on iPhone, also, it happens to some SVGs
![IMG_8940](https://user-images.githubusercontent.com/28992210/188246208-5497994e-a671-4b07-8d4a-b20f2eaf9548.jpg)

**Comment by nimr77** [comment] 2022-09-03 19:36
> Some images:
> 
> Flutter 3.0.5
> 
> ![IMG_8939](https://user-images.githubusercontent.com/28992210/188246171-9ce08fa1-156d-451f-a2fe-bd1b195a9c7b.jpg)
> 
> 
> 
> Flutter 3.3
> 
> ![IMG_8941](https://user-images.githubusercontent.com/28992210/188246186-20651729-dc26-44e3-837e-b39614c2f35e.jpg)
> 
> 
> 
> This is only on iPhone, also, it happens to some SVGs
> 
> ![IMG_8940](https://user-images.githubusercontent.com/28992210/188246208-5497994e-a671-4b07-8d4a-b20f2eaf9548.jpg)
> 
> 
> 
> Also happens on Master.
> 
> Another thing is, if you put the app on background and then come back, you can see the text like moving, its really weird
> 
> 

#
Try to change the filter quality to medium or low, mostly it's the case on png or SVG

**Comment by GiacomoPignoni** [comment] 2022-09-04 10:48
I'm also experimenting something similar with CustomPainter. 
The screenshot are from Windows build, but I have the same issues on iOS and Android.

3.0.5
![3 0 5](https://user-images.githubusercontent.com/34923063/188309625-42af4566-48fd-4663-bf6e-c8bae01754d6.png)

3.3.0
![3 3 0](https://user-images.githubusercontent.com/34923063/188309631-a62316f4-0ca2-47b7-8990-436fbe0f9a84.png)

**Comment by AlexV525** [comment] 2022-09-09 08:43
Can anyone do `git bisect` for the framework with the reproducible example to determine which is the first bad commit?

**Comment by jpnurmi** [comment] 2022-09-09 09:11
This will be fixed by:
- flutter/engine#35981 (CP: [#111231](https://github.com/flutter/flutter/issues/111231))
- flutter/flutter#111207 (CP: [#111208](https://github.com/flutter/flutter/issues/111208))

**Comment by NikosTsesmelis** [comment] 2022-09-09 09:16
@jpnurmi  Is this coming as a hotfix?

**Comment by jpnurmi** [comment] 2022-09-09 09:21
Yes, here are the cherry-picks:
- flutter/flutter#111208 ([#111207](https://github.com/flutter/flutter/pull/111207))
- flutter/flutter#111231 ([#36022](https://github.com/flutter/engine/pull/36022))

**Comment by goderbauer** [comment] 2022-09-13 22:30
Closing this based on https://github.com/flutter/flutter/issues/110738#issuecomment-1241714590.

**Closed by goderbauer** 2022-09-13 22:30 UTC
Labels: severe: regression, framework, a: typography, severe: rendering, P3
