### ISSUE TITLE
add support to allows pick multi image for plugin image_picker 

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#60515] opened 2020-06-29 11:16 UTC
pls add support to allows pick multi image.

right now this plugin in only support one file picker.

https://pub.dev/packages/image_picker#-example-tab-

**Comment by daniellampl** [comment] 2020-07-01 21:17
#25508

**Comment by darshankawar** [comment] 2020-07-02 05:56
Closing this as duplicate of [16054](https://github.com/flutter/flutter/issues/16054)

**Closed by darshankawar** 2020-07-02 05:56 UTC
