### ISSUE TITLE
Flutter 2.8.1 crashed on iOS because of EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by BlakeWuh** [flutter/flutter#96851] opened 2022-01-19 10:31 UTC
## Steps to Reproduce

1. 5% of this crash happens in foreground.
2. The crash got reported to Firebase console.
3. I havn't found a way to reproduce it.

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

```
crashed: com.apple.main-thread 
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000006a8
Crashed: com.apple.main-thread
0  Flutter                        0x3b8404 (missing)
1  Flutter                        0x3e464 (missing)
2  Flutter                        0x3c1f0 (missing)
3  Flutter                        0x3c67ac (missing)
4  Flutter                        0x3c6150 (missing)
5  Flutter                        0x12b2c (missing)
6  Flutter                        0xf1cc (missing)
7  CoreFoundation                 0x84d70 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
8  CoreFoundation                 0x84d10 ___CFXRegistrationPost_block_invoke + 52
9  CoreFoundation                 0x8427c _CFXRegistrationPost + 456
10 CoreFoundation                 0x83c2c _CFXNotificationPost + 716
11 Foundation                     0x745c -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
12 UIKitCore                      0xbd6224 -[UIApplication _terminateWithStatus:] + 300
13 UIKitCore                      0x2228d4 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
14 UIKitCore                      0x222504 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 220
15 UIKitCore                      0xbcbdc0 -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
16 FrontBoardServices             0x69a8 <redacted> + 88
17 FrontBoardServices             0x353d4 <redacted> + 80
18 FrontBoardServices             0x196a4 <redacted> + 240
19 FrontBoardServices             0x3536c <redacted> + 132
20 libdispatch.dylib              0x481c _dispatch_client_callout + 20
21 libdispatch.dylib              0x830c _dispatch_block_invoke_direct + 268
22 FrontBoardServices             0x5dfa0 <redacted> + 48
23 FrontBoardServices             0x5dc30 <redacted> + 448
24 FrontBoardServices             0x5e184 <redacted> + 32
25 CoreFoundation                 0xa407c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
26 CoreFoundation                 0xa3f78 __CFRunLoopDoSource0 + 208
27 CoreFoundation                 0xa327c __CFRunLoopDoSources0 + 268
28 CoreFoundation                 0x9d25c __CFRunLoopRun + 820
29 CoreFoundation                 0x9c9f4 CFRunLoopRunSpecific + 600
30 GraphicsServices               0x3734 GSEventRunModal + 164
31 UIKitCore                      0xbca75c -[UIApplication _run] + 1072
32 UIKitCore                      0xbcffcc UIApplicationMain + 168
33 Runner                         0x5e9c main + 10 (main.swift:10)
34 libdyld.dylib                  0x1cf8 start + 4
```

<details>
  <summary>Logs</summary>

```
crashed: com.apple.main-thread 
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000006a8
Crashed: com.apple.main-thread
0  Flutter                        0x3b8404 (missing)
1  Flutter                        0x3e464 (missing)
2  Flutter                        0x3c1f0 (missing)
3  Flutter                        0x3c67ac (missing)
4  Flutter                        0x3c6150 (missing)
5  Flutter                        0x12b2c (missing)
6  Flutter                        0xf1cc (missing)
7  CoreFoundation                 0x84d70 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
8  CoreFoundation                 0x84d10 ___CFXRegistrationPost_block_invoke + 52
9  CoreFoundation                 0x8427c _CFXRegistrationPost + 456
10 CoreFoundation                 0x83c2c _CFXNotificationPost + 716
11 Foundation                     0x745c -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
12 UIKitCore                      0xbd6224 -[UIApplication _terminateWithStatus:] + 300
13 UIKitCore                      0x2228d4 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
14 UIKitCore                      0x222504 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 220
15 UIKitCore                      0xbcbdc0 -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
16 FrontBoardServices             0x69a8 <redacted> + 88
17 FrontBoardServices             0x353d4 <redacted> + 80
18 FrontBoardServices             0x196a4 <redacted> + 240
19 FrontBoardServices             0x3536c <redacted> + 132
20 libdispatch.dylib              0x481c _dispatch_client_callout + 20
21 libdispatch.dylib              0x830c _dispatch_block_invoke_direct + 268
22 FrontBoardServices             0x5dfa0 <redacted> + 48
23 FrontBoardServices             0x5dc30 <redacted> + 448
24 FrontBoardServices             0x5e184 <redacted> + 32
25 CoreFoundation                 0xa407c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
26 CoreFoundation                 0xa3f78 __CFRunLoopDoSource0 + 208
27 CoreFoundation                 0xa327c __CFRunLoopDoSources0 + 268
28 CoreFoundation                 0x9d25c __CFRunLoopRun + 820
29 CoreFoundation                 0x9c9f4 CFRunLoopRunSpecific + 600
30 GraphicsServices               0x3734 GSEventRunModal + 164
31 UIKitCore                      0xbca75c -[UIApplication _run] + 1072
32 UIKitCore                      0xbcffcc UIApplicationMain + 168
33 Runner                         0x5e9c main + 10 (main.swift:10)
34 libdyld.dylib                  0x1cf8 start + 4
```

```
```

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.8.1 at /Users/blake/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/blake/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/blake/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

</details>

**Comment by BlakeWuh** [comment] 2022-01-19 11:39
@flutter-symbolizer-bot [#96851 (comment)](https://github.com/flutter/flutter/issues/96851#issue-1107927716) flutter#v2.8.1 force ios release arm64

**Comment by BlakeWuh** [comment] 2022-01-19 11:48
@flutter-symbolizer-bot [#96207 (comment)](https://github.com/flutter/flutter/issues/96851#issue-1107927716) flutter#v2.8.1 force ios release arm64

**Comment by maheshmnj** [comment] 2022-01-19 12:08
duplicate of https://github.com/flutter/flutter/issues/96612 which is likely fixed on master channel. Please follow up on the linked issue.

**Comment by BlakeWuh** [comment] 2022-01-20 06:16
Is this issue related to the other issue [issue 96854](https://github.com/flutter/flutter/issues/96854) ?

**Comment by maheshmnj** [comment] 2022-01-20 06:41
Leaving this issue open for further insights from the team.

**Comment by maheshmnj** [comment] 2022-01-20 06:43
cc: @jason-simmons

**Comment by mkay-42069** [comment] 2022-01-20 09:55
@maheshmnj I seriously wonder why you're keeping this issue open...

It's clearly the same issue as:
https://github.com/flutter/flutter/issues/96424
https://github.com/flutter/flutter/issues/95844
https://github.com/flutter/flutter/issues/96768

Which was fixed with https://github.com/flutter/engine/pull/30835, and was pushed to master.
Now only needs to be released to beta and stable.

**Comment by maheshmnj** [comment] 2022-01-20 10:56
@mkay-42069 This issue was reported in production from the firebase console, The ones you pointed out are reproducible locally when closing the app.  Also, the logs don't look similar to this issue.

So I think it's better to wait for the teams input.

**Comment by jason-simmons** [comment] 2022-01-20 18:14
The symbolized stack trace in https://github.com/flutter/flutter/issues/96851#issuecomment-1016409516 includes a crash in `flutter::Shell::OnPlatformViewSetSemanticsEnabled` during destruction of the `flutter::Shell`.  So this is a duplicate of https://github.com/flutter/flutter/issues/95844

**Comment by jmagman** [comment] 2022-01-20 18:51
Thanks @jason-simmons, closing as duplicate of #95844 then.

**Closed by jmagman** 2022-01-20 18:51 UTC
Labels: severe: crash, platform-ios, engine, a: production, severe: fatal crash
