### ISSUE TITLE
[DropdownMenu] Disable text input 

### ISSUE THREAD

**Issue by LasseRosenow** [flutter/flutter#116587] opened 2022-12-06 12:22 UTC
Kindly marking @QuncCccccc as I think the widget is developed by you? :)

In general the new DropDown menu is really good. I am happy to finally have a good and modern replacement for the old DropdownButton.

But I find that it's behavior to always open the keyboard even on mobile is a bit annoying especially in small menus with < 10 options to select from. There is no real benefits from opening the keyboard and it makes the user experience a bit worse by moving the menus around and massively reducing the screen space.

I think having the ability to use the keyboard in general is a good idea, especially with hardware keyboards, but on mobile it is a not so good default.

## Example code

<details><summary>CLICK ME</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() => runApp(DropdownMenuExample());

class DropdownMenuExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.green),
      home: const Scaffold(
        body: SafeArea(
          child: DropdownMenu<String>(
            initialSelection: "yellow",
            label: const Text('Color'),
            dropdownMenuEntries: [
              DropdownMenuEntry<String>(
                value: "red",
                label: "Red",
              ),
              DropdownMenuEntry<String>(
                value: "yellow",
                label: "Yellow",
              ),
              DropdownMenuEntry<String>(
                value: "green",
                label: "Green",
              ),
              DropdownMenuEntry<String>(
                value: "blue",
                label: "Blue",
              ),
              DropdownMenuEntry<String>(
                value: "purple",
                label: "Purple",
              ),
              DropdownMenuEntry<String>(
                value: "black",
                label: "Black",
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

</p>
</details>

### a)
- Disable the keyboard input on touch events.. only show on mouse click.
- Add possibility to manually overwrite this behavior with some flag

### b)
- Disable the keyboard input for small lists (< 10 items)
- Add possibility to manually overwrite this behavior with some flag

### c)
- keep as is, but enable possibility to manually overwrite this his behavior with some flag

**Comment by exaby73** [comment] 2022-12-06 14:13
Hello @LasseRosenow. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

PS: Kindly refrain from mentioning team members. I know you have good intentions but as a best practice, it's better allow the team to look at this issue once it's triaged, which is why I am here :)

**Comment by LasseRosenow** [comment] 2022-12-06 19:13
Thank you for your quick response. And sorry for the ping, I will not do it again :)

So I added a minimal example that should be enough to show the issue.

**Comment by exaby73** [comment] 2022-12-07 08:27
As per [the documentation](https://master-api.flutter.dev/flutter/material/DropdownMenu-class.html):

> A dropdown menu that can be opened from a [TextField](https://master-api.flutter.dev/flutter/material/TextField-class.html). The selected menu item is displayed in that field.

This is meant to be a "searchable" `TextField`. I think for your usecase, `DropdownButton` makes more sense. Since there is already a widget that provides a dropdown without text input, it doesn't make sense to change this widget as `DropdownMenu` is not a replacement for `DropdownButton`.

Due to the above reasons, I do not think this issue is valid, and therefore I am closing this issue. If you disagree, please comment with your reasoning and I can reopen it. Thank you

**Comment by LasseRosenow** [comment] 2022-12-07 11:11
I don't agree.

The material design specification does not have a drop-down button. In the material 4 Specification everything is a menu and should use the menu internally.

The flutter drop-down button implementation is a mess as it draws it's own menu instead of reusing the menu widget internally like the new DropdownButton does.

Drop-down button also had a version that could be used inside a text field. I am really certain that this is indeed a replacement of that version. Also based on some discussion I was following on GitHub. 

The material 3 documentation says, that a menu can be triggered by a text field. That this text field must be usable by the keyboard is "unspecified".

The native android components don't open the keyboard. See the Google contact app for example, so this new experience feels awkward inside the android material design ecosystem.

![Screenshot_20221207-121024_Kontakte.png](https://user-images.githubusercontent.com/10547444/206164280-b7d6e839-925b-430e-90c9-0c6551ce48c3.png)

**Comment by LasseRosenow** [comment] 2022-12-07 11:17
I don't agree.

The material design specification does not have a drop-down button. In the material 4 Specification everything is a menu and should use the menu internally.

The flutter drop-down button implementation is a mess as it draws it's own menu instead of reusing the menu widget internally like the new DropdownButton does.

Drop-down button also had a version that could be used inside a text field. I am really certain that this is indeed a replacement of that version. Also based on some discussion I was following on GitHub. 

The material 3 documentation says, that a menu can be triggered by a text field. That this text field must be usable by the keyboard is "unspecified".

The native android components don't open the keyboard. See the Google contact app for example, so this new experience feels awkward inside the android material design ecosystem.

![Screenshot_20221207-121024_Kontakte.png](https://user-images.githubusercontent.com/10547444/206164280-b7d6e839-925b-430e-90c9-0c6551ce48c3.png)

PS: you see in #115005 that the author clearly states, that `DropdownMenu` is an update to the `DropdownButton`. I am sure, that `DropdownButton` will be deprecated in time as it should.

**Comment by LasseRosenow** [comment] 2022-12-07 13:40
Okay I spend some more time reading the material design 3 guidelines and actually find proof that the guidelines would not show the keyboard on touch by default. Because every example video does not.

Like this for example:

https://user-images.githubusercontent.com/10547444/206194116-492cb129-5ae2-4af2-ab5e-230cdc873599.mp4

Source: https://m3.material.io/components/menus/guidelines

**Comment by LasseRosenow** [comment] 2022-12-07 13:44
In general it seems that this "filtering" is more a special use case as the specification speaks about it:

**Closed** 2023-01-27 19:12 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.3, found in release: 3.7
