### ISSUE TITLE
Spaces do not appear in multi-line TextField before new line character

### ISSUE THREAD

**Issue by droidery** [flutter/flutter#47813] opened 2019-12-26 10:16 UTC
## Steps to Reproduce

1. Create multi-line `TextField` with initial text including a new line character (`\n`)
2. Insert spaces **before** the new line character
3. Spaces do not appear as expected in the `TextField`
4. Spaces only appear when inserting a non-space character

Video:
![gif](https://user-images.githubusercontent.com/34681083/71471794-b17e4e80-2824-11ea-9911-24ed311bd71e.gif)

Sample code used:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: TextField(
          keyboardType: TextInputType.multiline,
          controller: TextEditingController()..text = 'new line =>\n<=  ',
          maxLines: 5,
          maxLength: null,
        ),
      ),
    );
  }
}
```

**Target Platform:** iOS
**Target OS version/browser:** iOS 13.3
**Devices:** iPhone (simulator and real devices)

Issue can be reproduced in the Flutter master and dev channels but not the Flutter stable channel.

## Logs

```
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on iPhone 11 is available at: http://127.0.0.1:60813/kx-QhJeGsmU=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+53388 ms] [DEVICE LOG] 2019-12-26 21:10:50.027401+1100  localhost Runner[23532]: (ManagedConfiguration)
[com.apple.ManagedConfiguration:MC] Got system group container path from MCM for systemgroup.com.apple.configurationprofiles:
/Users/user/Library/Developer/CoreSimulator/Devices/FC6EC590-15BB-44AD-B193-4ABFBEE35007/data/Containers/Shared/SystemGroup/systemgroup.
com.apple.configurationprofiles
[  +20 ms] [DEVICE LOG] 2019-12-26 21:10:50.047855+1100  localhost Runner[23532]: (AggregateDictionary) AggregateDictionary is not
supported on this platform
[  +50 ms] [DEVICE LOG] 2019-12-26 21:10:50.098648+1100  localhost Runner[23532]: (CallKit) [com.apple.calls.callkit:Default] Call host
has no calls
[  +23 ms] [DEVICE LOG] 2019-12-26 21:10:50.119900+1100  localhost Runner[23532]: (CoreFoundation) Created Activity ID: 0x3dd98,
Description: Updating Key-Value Observers Of Preferences
[   +4 ms] [DEVICE LOG] 2019-12-26 21:10:50.126352+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
activate generator with style: TurnOn; activationCount: 0 -> 1; styleActivationCount: 0 -> 1; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[   +7 ms] [DEVICE LOG] 2019-12-26 21:10:50.126557+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] activate engine
<_UIFeedbackSystemSoundEngine: 0x6000022f66f0>, clientCount: 0 -> 1
[   +1 ms] [DEVICE LOG] 2019-12-26 21:10:50.126642+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] activating
engine <_UIFeedbackSystemSoundEngine: 0x6000022f66f0>
[   +1 ms] [DEVICE LOG] 2019-12-26 21:10:50.127042+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] engine
<_UIFeedbackSystemSoundEngine: 0x6000022f66f0: state=3, numberOfClients=1, prewarmCount=0, _internal_isSuspended=0> state changed:
Inactive -> Activating
[   +1 ms] [DEVICE LOG] 2019-12-26 21:10:50.127197+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] engine
<_UIFeedbackSystemSoundEngine: 0x6000022f66f0: state=4, numberOfClients=1, prewarmCount=0, _internal_isSuspended=0> state changed:
Activating -> Running
[   +1 ms] [DEVICE LOG] 2019-12-26 21:10:50.132872+1100  localhost Runner[23532]: (RunningBoardServices) Created Activity ID: 0x3dd99,
Description: didChangeInheritances
[+1309 ms] [DEVICE LOG] 2019-12-26 21:10:51.449615+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
activate generator with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[        ] [DEVICE LOG] 2019-12-26 21:10:51.449838+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] generator
<_UIKeyboardFeedbackGenerator: 0x6000038bc280> playing feedback <_UICustomDiscreteFeedback: 0x600003b92be0>
[        ] [DEVICE LOG] 2019-12-26 21:10:51.449995+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] player dequeue
needed - initial request for feedback <_UICustomDiscreteFeedback: 0x600003b92be0>
[        ] [DEVICE LOG] 2019-12-26 21:10:51.450077+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] player dequeue
finished for feedback <_UICustomDiscreteFeedback: 0x600003b92be0> with player <_UIFeedbackSystemSoundEngine: 0x6000022f66f0>
[   +3 ms] [DEVICE LOG] 2019-12-26 21:10:51.455510+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
deactivate generator with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[   +1 ms] [DEVICE LOG] 2019-12-26 21:10:51.455580+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] played feedback
<_UICustomDiscreteFeedback: 0x600003b92be0> with engine <_UIFeedbackSystemSoundEngine: 0x6000022f66f0> at time 23840.446575
[ +985 ms] [DEVICE LOG] 2019-12-26 21:10:52.441493+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
activate generator with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[        ] [DEVICE LOG] 2019-12-26 21:10:52.441685+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] generator
<_UIKeyboardFeedbackGenerator: 0x6000038bc280> playing feedback <_UICustomDiscreteFeedback: 0x600003b92be0>
[        ] [DEVICE LOG] 2019-12-26 21:10:52.443687+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
deactivate generator with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[        ] [DEVICE LOG] 2019-12-26 21:10:52.443762+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] played feedback
<_UICustomDiscreteFeedback: 0x600003b92be0> with engine <_UIFeedbackSystemSoundEngine: 0x6000022f66f0> at time 23841.438417
[ +772 ms] [DEVICE LOG] 2019-12-26 21:10:53.216269+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
activate generator with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[   +1 ms] [DEVICE LOG] 2019-12-26 21:10:53.216452+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] generator
<_UIKeyboardFeedbackGenerator: 0x6000038bc280> playing feedback <_UICustomDiscreteFeedback: 0x600003b92be0>
[   +1 ms] [DEVICE LOG] 2019-12-26 21:10:53.220053+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
deactivate generator with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[        ] [DEVICE LOG] 2019-12-26 21:10:53.220120+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] played feedback
<_UICustomDiscreteFeedback: 0x600003b92be0> with engine <_UIFeedbackSystemSoundEngine: 0x6000022f66f0> at time 23842.213184
[ +441 ms] [DEVICE LOG] 2019-12-26 21:10:53.662199+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
activate generator with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[        ] [DEVICE LOG] 2019-12-26 21:10:53.662338+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] generator
<_UIKeyboardFeedbackGenerator: 0x6000038bc280> playing feedback <_UICustomDiscreteFeedback: 0x600003b92be0>
[        ] [DEVICE LOG] 2019-12-26 21:10:53.663689+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
deactivate generator with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[        ] [DEVICE LOG] 2019-12-26 21:10:53.663751+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] played feedback
<_UICustomDiscreteFeedback: 0x600003b92be0> with engine <_UIFeedbackSystemSoundEngine: 0x6000022f66f0> at time 23842.659070
[ +392 ms] [DEVICE LOG] 2019-12-26 21:10:54.056374+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
activate generator with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[        ] [DEVICE LOG] 2019-12-26 21:10:54.056495+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] generator
<_UIKeyboardFeedbackGenerator: 0x6000038bc280> playing feedback <_UICustomDiscreteFeedback: 0x600003b92be0>
[        ] [DEVICE LOG] 2019-12-26 21:10:54.057663+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
deactivate generator with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[        ] [DEVICE LOG] 2019-12-26 21:10:54.057734+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] played feedback
<_UICustomDiscreteFeedback: 0x600003b92be0> with engine <_UIFeedbackSystemSoundEngine: 0x6000022f66f0> at time 23843.053225
[+5985 ms] [DEVICE LOG] 2019-12-26 21:11:00.043115+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
activate generator with style: TurnOn; activationCount: 1 -> 2; styleActivationCount: 1 -> 2; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[   +2 ms] [DEVICE LOG] 2019-12-26 21:11:00.043473+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] generator
<_UIKeyboardFeedbackGenerator: 0x6000038bc280> playing feedback <_UICustomDiscreteFeedback: 0x600003b92be0>
[   +1 ms] [DEVICE LOG] 2019-12-26 21:11:00.047371+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:FeedbackActivation]
deactivate generator with style: TurnOn; activationCount: 2 -> 1; styleActivationCount: 2 -> 1; <_UIKeyboardFeedbackGenerator:
0x6000038bc280>
[        ] [DEVICE LOG] 2019-12-26 21:11:00.047487+1100  localhost Runner[23532]: (UIKitCore) [com.apple.UIKit:Feedback] played feedback
<_UICustomDiscreteFeedback: 0x600003b92be0> with engine <_UIFeedbackSystemSoundEngine: 0x6000022f66f0> at time 23849.040288
```

```
Analyzing textfield_repro...                                            
No issues found! (ran in 3.8s)
```

```
[✓] Flutter (Channel master, v1.13.6-pre.23, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.6-pre.23 at /Users/droidery/flutter
    • Framework revision 6e72facad1 (2 days ago), 2019-12-24 10:54:04 -0800
    • Engine revision 33813929e3
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/droidery/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 • FD6EC120-15AA-44AD-B193-4ABFXDD01002 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

**Comment by shihaohong** [comment] 2019-12-26 16:54
cc/ @justinmc

**Comment by justinmc** [comment] 2019-12-26 18:02
I think this is a duplicate of https://github.com/flutter/flutter/issues/40095, so I'm going to close this to focus discussion over there.  Let me know if I'm wrong and that issue doesn't cover everything here and I'll reopen, though.

**Closed by justinmc** 2019-12-26 18:02 UTC
Labels: a: text input, f: material design, framework
