### ISSUE TITLE
 Start black screen after updating 1.12+

### ISSUE THREAD

**Issue by MuZiLee** [flutter/flutter#48552] opened 2020-01-10 03:48 UTC
[black screen screenshot](https://user-images.githubusercontent.com/7467318/72123974-0e8a1080-339e-11ea-890e-f0d0495460ba.png)

> 当我发现出现黑屏时,我尝试了在清单文件修改:android:theme="@android:style/Theme.Wallpaper.NoTitleBar"
> 还是会出现黑屏.
> 我尝试在style.xml文件修改为:android:style/Theme.Wallpaper.NoTitleBar

[code screenshot](https://user-images.githubusercontent.com/7467318/72124033-485b1700-339e-11ea-9b07-f83465dbf240.png)

> 不是会出现黑屏.
> 我尝试加入条种flutter的群,更新后不少人出现了黑屏问题,有的说编译后就正常.然而我编译后只是黑屏的时间短了一些.
> 我又尝试了重新创建了一个全新的flutter工程,不是会出现黑屏.
> 难道大goole的开发人员没有出现过这个问题?
> 然后,请问各路大神,我的黑屏应该怎么解决?

When I found a black screen, I tried to modify the manifest file: android: theme = "@ android: style / Theme.Wallpaper.NoTitleBar"
A black screen still appears.

I try to modify the style.xml file to: android: style / Theme.Wallpaper.NoTitleBar
No black screen will appear.

I tried to join various flutter groups. After the update, many people experienced black screen problems, and some said that it was normal after compilation. However, the black screen time was shorter after compilation.
I tried to re-create a brand new flutter project, and no black screen appears.
Hasn't the developer of big goole ever encountered this problem?
Then, may I ask the gods, how should I solve my black screen?

**Comment by huage2580** [comment] 2020-01-10 07:11
1.提issue使用英文，仅有的几个单词还拼错了，‘activate’，‘goole’ 你连机翻都做不到，不配得到别人的帮助。 
遵守issue模板，或者提供完整的信息。这不是论坛。
2.提问前请先搜索issue，相关 #47582 , #48480  

1. Please use English. 
Follow the issue template, and provide complete information.
This is not a forum.
2. Please search for issues before asking questions, related # 47582, # 48480

**Comment by iapicca** [comment] 2020-01-10 07:45
Hi @secret620 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/47582) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-01-10 07:45 UTC

**Comment by MuZiLee** [comment] 2020-01-11 01:41
我的问题都没有解决为什么要关闭我的问题?

**Comment by MuZiLee** [comment] 2020-01-11 01:43
@huage2580 你中文有问题就不要怪别人?我一个英文都没有写,都是从终端复制粘贴上来的

**Comment by iapicca** [comment] 2020-01-13 07:38
Hi @MuZiLee 
the issue isn't solve yet, please follow up in the link I've provided in my previous answer
thank you.
