### ISSUE TITLE
[Linux] Arrow keys and shortcut keys not working

### ISSUE THREAD

**Issue by HidenoriMatsubayashi** [flutter/flutter#65220] opened 2020-09-04 01:58 UTC
Arrow keys and shortcut keys (Ctrl + C, Ctrl + V etc) not working in the latest version.

## Sample code

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text('Keyboard Input')),
        body: Center(
            child: TextField(
          keyboardType: TextInputType.multiline,
          textInputAction: TextInputAction.newline,
          expands: true,
          minLines: null,
          maxLines: null,
        )));
  }
}
```

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.82, on Linux, locale ja_JP.UTF-8)
    • Flutter version 1.22.0-10.0.pre.82 at /opt/flutter
    • Framework revision 9248fda410 (3 hours ago), 2020-09-03 16:08:01 -0700
    • Engine revision 3f05b521b9
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)
 
[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1
```

</details>

**Comment by TahaTesser** [comment] 2020-09-04 07:56
Hi @HidenoriMatsubayashi 
I see there are open issues addressing the cases you described.

Copy/Paste
 https://github.com/flutter/flutter/issues/23603
Arrows keys 
https://github.com/flutter/flutter/issues/58473

Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by HidenoriMatsubayashi** [comment] 2020-09-04 08:05
@TahaTesser 

> Arrows keys
> #58473

That is the different issue.
In previous versions, I could use arrow keys to move the cursor. Now, it is not possible.

> Copy/Paste
> #23603

Shortcut keys (Ctrl + A, Ctrl + C, etc) are similar. It used to work before.

**Comment by maks** [comment] 2020-09-04 08:23
@TahaTesser  I'm not certain this is the same issue as #58473. That issue report is about shift+arrow keys not selecting. This one is about the arrow keys by themselves not moving the cursor. If it is just aspects of the same problem then 58473 should have its title updated to reflect that its arrow keys in general not working.

**Comment by TahaTesser** [comment] 2020-09-04 09:55
Hi @HidenoriMatsubayashi 
Please check out my comment https://github.com/flutter/flutter/issues/58473#issuecomment-687047874
Closing as duplicate of https://github.com/flutter/flutter/issues/58473

**Closed by TahaTesser** 2020-09-04 09:55 UTC
