### ISSUE TITLE
Issue about the RichText，when the TextSpan. text is emoji text.

### ISSUE THREAD

**Issue by BeanWei** [flutter/flutter#26263] opened 2019-01-09 01:41 UTC
```dart
RichText(
  text: TextSpan(
    text: '😥 ',
    style: new TextStyle(color: Colors.black, fontSize: 200),
  ),
)
```
as you see, I use the emoji text. When I set the fontsize over 100, the emoji will missing, but less than 100, it works. 

Anybody can help me? Tks.~

**Comment by Kartik1607** [comment] 2019-01-09 06:51
Will need more code to find the issue. This seems to be working fine. 

Code tested on
```dart
void main() {
  // runApp(MaterialApp(
  //     color: Color(0xFF00D99D),
  //     theme: ThemeData.light().copyWith(
  //         cursorColor: Colors.black,
  //         textSelectionColor: Color(0x4400D99D),
  //         textSelectionHandleColor: Color(0xFF00D99D)),
  //     home: SearchRest()));
  runApp(MaterialApp(
    title: 'Sample',
    home: Scaffold(
        body: Container(
      child: RichText(
        text: TextSpan(
          text: '😥 ',
          style: new TextStyle(color: Colors.black, fontSize: 200),
        ),
      ),
    )),
  ));
}
```

**OUTPUT** 

<img src='https://i.imgur.com/y0siHDD.png' width='150'/>

**Comment by zoechi** [comment] 2019-01-09 07:38
Duplicate of #16386

**Comment by zoechi** [comment] 2019-01-09 07:38
Please add a comment to have the issue reopened if you don't think this is a duplicate.

**Closed by zoechi** 2019-01-09 07:38 UTC
Labels: a: typography
