### ISSUE TITLE
Lost connection to device(iOS)(It lasts only five seconds at a time and then disconnects.)

### ISSUE THREAD

**Issue by xhw0525** [flutter/flutter#35099] opened 2019-06-26 05:24 UTC
...
[   +1 ms] Connected to _flutterView/0x101a0aca8.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild
state),
           press "R".
[   +1 ms] An Observatory debugger and profiler on iPhone-v is available at:
http://127.0.0.1:1025/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit,
press "q".
 [+4998 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/38B1EF94-492E-4CF2-BE45-55B7C24526
E0/tmp/hahat3Rulm/haha/)
[        ] Sending to VM service: _deleteDevFS({fsName: haha})
[ +260 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000:
Future not completed
[   +6 ms] Unforwarding port ForwardedPort HOST:1025 to DEVICE:56605
[   +3 ms] "flutter attach" took 12,239ms.
[        ] "flutter attach" took 12,239ms.

**Comment by najeira** [comment] 2019-06-26 06:39
same as #34629

Which version does this occur? Is it stable branch?

**Comment by xhw0525** [comment] 2019-06-26 07:48
> 与[＃34629](https://github.com/flutter/flutter/issues/34629)相同[](https://github.com/flutter/flutter/issues/34629)
> 
> 这种情况发生在哪个版本？它是稳定的分支吗？

"flutter doctor -v "
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/xhw/Android/flutter
    • Framework revision 8661d8aecd (4 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xhw/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.2

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (2 available)
    • DUIA-SJ-00056 • 6cc0e296728355f6eeafae231234184a7ce8d8b7 • ios • iOS 11.4.1
    • iPhone 6s     • 090326AE-69C0-4DBC-9E9F-427DAC77079D     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.

```

**Comment by xhw0525** [comment] 2019-06-26 08:26
hia~hia~, I fix it
see
https://github.com/flutter/flutter/issues/35102#issue-460782718

**Comment by xhw0525** [comment] 2019-06-26 08:27
Replace files in the "/usr/local/Cellar/usbmuxd" directory with colleagues,

**Comment by WATER1350** [comment] 2019-06-26 13:33
@xhw0525 it work

**Comment by christopherfujino** [comment] 2019-06-26 16:09
Closed as a duplicate of #35102

**Closed by christopherfujino** 2019-06-26 16:09 UTC
Labels: tool

**Comment by Jerry-Lau** [comment] 2020-08-03 13:00
> Replace files in the "/usr/local/Cellar/usbmuxd" directory with colleagues,

what does with colleagues mean? @xhw0525

**Comment by kharitonovAL** [comment] 2021-02-22 14:07
@Jerry-Lau 

> > Replace files in the "/usr/local/Cellar/usbmuxd" directory with colleagues,
> 
> what does with colleagues mean? @xhw0525


Hey, did you get what “colleagues” means?

thanks!
