### ISSUE TITLE
Flutter app is stuck in Waiting for VM Service port to be available...

### ISSUE THREAD

**Issue by Edijae** [flutter/flutter#136222] opened 2023-10-09 21:04 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I'm trying to run a flutter app on a samsung A53 device from android studio but the app is stuck on a white screen and showing `"waiting for VM Service to be available..."` message on the android studio terminal.

I've tried to restart the laptop, mobile phone but without success.

### Expected results

App is launched successfully

### Actual results

App is stuck.

### Code sample

<details><summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
       
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
       
        title: Text(widget.title),
      ),
      body: Center(
       
        child: Column(
         
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

<img width="400" src="https://github.com/flutter/flutter/assets/14346659/62024050-4664-431d-a2d2-9891c02e559f">

</details>

### Logs

<details><summary>Logs</summary>

```console
[  +13 ms] executing: /Users/m/Library/Android/sdk/platform-tools/adb -s adb-RZCT20BH7NK-rGpIzp._adb-tls-connect._tcp. shell am start -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x20000000 --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.example.test/com.example.test.MainActivity
[ +195 ms] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x20000000 cmp=com.example.test/.MainActivity (has extras) }
[        ] Waiting for VM Service port to be available...

```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.13.6, on macOS 13.4 22F66 darwin-x64, locale en-KE)
    • Flutter version 3.13.6 on channel stable at /Users/m/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (13 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/m/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • ANDROID_HOME = /Users/m/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/m/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio old.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • SM A536E (mobile) • adb-RZCT20BH7NK-rGpIzp._adb-tls-connect._tcp. • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos                                         • darwin-x64     • macOS 13.4 22F66 darwin-x64
    • Chrome (web)      • chrome                                        • web-javascript • Google Chrome 117.0.5938.149

[✓] Network resources
    • All expected network resources are available.

• No issues found!
Process finished with exit code 0
```
</details>

Flutter run -v  output: https://pastes.io/ebhpsjs2ry

**Comment by huycozy** [comment] 2023-10-10 08:42
Hi @Edijae 
Your sample code is not complete and using 3rd package. 

In order to address the issue properly, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code.

Also, please provide the entire output of `flutter run -v`  so that we may verify this further.

**Comment by Edijae** [comment] 2023-10-10 13:39
@huycozy I've updated the question and added `flutter run -v` output and also attached a screenshoot of the app state when i click the run button from the android studio

**Comment by huycozy** [comment] 2023-10-11 04:25
Thanks for the update. The output run log is too long so I moved it to `pastes.io` for better readability. 

I noticed you updated the screenshot with Flutter logo. Did you implement Splash screen on Android native module? Does the issue occur on a newly created Flutter project?

This seems to be similar to https://github.com/flutter/flutter/issues/111594. Please also take a look at comments there if your case is the same.

**Comment by Edijae** [comment] 2023-10-11 09:28
@huycozy The issue is almost similar to the one you mentioned, but the suggested fix doesn't resolve the problem in this ticket. It seems like the Flutter app is in a deadlock, as it remains stuck at 'waiting for VM Service to be available...' in the log. I attempted to add a log in the main method, but it doesn't appear to be reached. This indicates that the main method isn't being called. I'm experiencing this issue on the Samsung A53 phone, although the test app runs perfectly on the emulator. Below are the logs from the emulator:

```
Waiting for VM Service port to be available...
[+7735 ms] VM Service URL on device: http://127.0.0.1:43943/X_d9hXcIlaw=/
[   +1 ms] executing: /Users/m/Library/Android/sdk/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:43943
[  +59 ms] 54986
[        ] Forwarded host port 54986 to device port 43943 for VM Service
[   +8 ms] Caching compiled dill
[ +250 ms] Connecting to service protocol: http://127.0.0.1:54986/X_d9hXcIlaw=/
[+1018 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:54986/X_d9hXcIlaw=/.
[ +801 ms] DDS is listening at http://127.0.0.1:54994/eBpkDYyNoFA=/.
[ +111 ms] Successfully connected to service protocol: http://127.0.0.1:54986/X_d9hXcIlaw=/

```

**Comment by huycozy** [comment] 2023-10-11 11:57
That issue is still open and hasn't been solved yet. I would suggest you follow up on it for updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. 

Closing this issue in favor of that one.

**Closed by huycozy** 2023-10-11 11:57 UTC
Labels: in triage
