### ISSUE TITLE
Exception does not include line number of the causing statement (when null aware operator inside an if inside a list literal resolves to null)

### ISSUE THREAD

**Issue by fourman-alex** [flutter/flutter#70302] opened 2020-11-11 16:45 UTC
## Steps to Reproduce
This happens when using `if` inside a `list` literal like so:
```
[
    if (string?.isNotEmpty) Text('Appears if condition is not null'),
    Text('Appears always'),
]
```
**Pay attention that this is caused by the `?.` null aware conditional access operator**
Yet the stacktrace should still show the line number of this statement when throwing with `Failed assertion: boolean expression must not be null`

While this is obviously a developer's mistake to have the if statement that can resolve to `null`, this is tricky to find in a big file.

See the reproducable code:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  String string = null;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Column(
        children: [
          if (string?.isNotEmpty) Text('Appears if condition is not null'),
          Text('Appears always'),
        ],
      ),
    );
  }
}
```

The exception:
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building MyApp(dirty):
Failed assertion: boolean expression must not be null

The relevant error-causing widget was: 
  MyApp file:///home/alex/StudioProjects/test_boolean/lib/main.dart:4:10
When the exception was thrown, this was the stack: 
#0      MyApp.build (package:test_boolean/main.dart)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:4749:28)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4369:5)
#4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2777:33)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 529 libraries in 285ms.
```

**Comment by darshankawar** [comment] 2020-11-12 06:26
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.208, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-8.0.pre.208 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 15d2d8a875 (5 hours ago), 2020-11-11 20:04:03 -0500
    • Engine revision d97a81c889
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      86.0.4240.193

• No issues found!


```

</details>

**Comment by Hixie** [comment] 2021-01-06 19:17
cc @leafpetersen this is probably an issue on the Dart side

**Comment by leafpetersen** [comment] 2021-01-12 23:46
I don't think this is null safety related.  This is pre-null safety code.  I can reproduce fairly easily, e.g.  

```
// @dart = 2.9

void test2() {
  String string = null;
  if (string?.isNotEmpty);
}
void main() {
  try {
    test2();
  } catch (e, s) {
    print(s);
  }
}
```

prints

#0      test2 (file:///Users/leafp/tmp/test.dart)
#1      main (file:///Users/leafp/tmp/test.dart:9:5)

cc @a-siva

**Comment by Hixie** [comment] 2021-01-13 00:36
Ah, excellent, let me remove this from our null safety tracking list then. Thanks.

**Comment by a-siva** [comment] 2021-01-13 01:44
This seems to be a pure Dart issue, I have created https://github.com/dart-lang/sdk/issues/44654 to track this issue, we can close it here.

**Comment by darshankawar** [comment] 2021-01-13 05:36
Closing this based on comment above.

**Closed by darshankawar** 2021-01-13 05:36 UTC
Labels: P3, a: error message, dependency: dart, found in release: 1.24, has reproducible steps, passed first triage
