### ISSUE TITLE
image_picker v0.8.6 - Choosing "Selected Photos" permission shows all photos not the selected one

### ISSUE THREAD

**Issue by igupta72** [flutter/flutter#117885] opened 2023-01-03 05:58 UTC
1. Opened App settings
2. Chose "Selected Photos"
3. Selected Edit Selected Photos and mark the selection that need to be shown
4. Went back to App, opened File Picker, Select from Photo Library and It shows all photos not the selected ones.

I am facing this problem.

**Comment by exaby73** [comment] 2023-01-03 08:57
Hello @igupta72. Thank you for filing this issue. Can you please provide the following information?

- A [complete and minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Ideally, a single `main.dart` file that can be run directly.
- The output of `flutter doctor -v`
- The output of `flutter run -v`

Please provide the information in the form of text. See how to make collapsible sections with Markdown [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections).

**Comment by igupta72** [comment] 2023-01-03 10:13
@exaby73 
https://user-images.githubusercontent.com/90826346/210337423-3a1449b3-d0ad-436a-856c-2d6490a001d2.mp4

Here I have chosen **Selected Photos**, but still showing **All photos**.

**Comment by exaby73** [comment] 2023-01-03 10:34
Please provide a complete code sample that can be run directly

**Comment by igupta72** [comment] 2023-01-04 10:17
@exaby73 
**Run this simple code** - Its showing all images instead of selected image when select image is chosen

`import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';


void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Image Picker Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Image Picker Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  final ImagePicker _picker = ImagePicker();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
              child: Text("Photo Library"),
              onPressed: () async {
                final file = await _picker.pickImage(source: ImageSource.gallery);
              },
            ),
            const SizedBox(height: 20,),
          ],
        ),
      ),
    );
  }
}
`

**Comment by exaby73** [comment] 2023-01-05 07:30
## Triage report

I can reproduce this issue with `image_picker: 0.8.6` and `Master (3.7.0-14.0.pre.40)` on an iOS 16.2 simulator.

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[!] Flutter (Channel master, 3.7.0-14.0.pre.40, on macOS 13.0.1 22A400 darwin-arm64, locale en-US)
    • Flutter version 3.7.0-14.0.pre.40 on channel master at /Users/nabeelparkar/fvm/versions/master
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nabeelparkar/fvm/versions/master. Consider adding /Users/nabeelparkar/fvm/versions/master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a562fe2d8a (2 hours ago), 2023-01-04 23:53:41 -0500
    • Engine revision b9b0193ea8
    • Dart version 3.0.0 (build 3.0.0-85.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9123335/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/nabeelparkar/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 71.2.6
    • Dart plugin version 223.8214.16

[✓] IntelliJ IDEA Ultimate Edition (version 2022.3.1)
    • IntelliJ at /Users/nabeelparkar/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8214.52/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 108.1.46.144

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by hellohuanlin** [comment] 2023-01-07 01:20
This seems to be the same issue as https://github.com/flutter/flutter/issues/90373. The reason for all photos are displayed is because the picker runs in a separate process so does not use the same permission settings as the app. More details [here](https://github.com/flutter/flutter/issues/90373#issuecomment-1204481839).

**Comment by hellohuanlin** [comment] 2023-01-07 01:21
I'm gonna close this one since it should be auto fixed after [the other issue](https://github.com/flutter/flutter/issues/90373) is fixed.

**Closed by hellohuanlin** 2023-01-07 01:21 UTC
Labels: platform-ios, plugin, p: first party, p: image_picker, has reproducible steps, r: duplicate, found in release: 3.3, found in release: 3.7
