### ISSUE TITLE
[image_picker] Feature request: Allow picking both photos and vidoes

### ISSUE THREAD

**Issue by mgenware** [flutter/flutter#122971] opened 2023-03-19 12:22 UTC
This is a feature request for [image_picker](https://pub.dev/packages/image_picker).

Android photo picker can select both photos and videos via `PickMultipleVisualMedia` as demonstrated in [this](https://developer.android.com/training/data-storage/shared/photopicker):
```kt
// Registers a photo picker activity launcher in multi-select mode.
// In this example, the app allows the user to select up to 5 media files.
val pickMultipleMedia =
        registerForActivityResult(PickMultipleVisualMedia(5)) { uris ->
    // Callback is invoked after the user selects media items or closes the
    // photo picker.
    if (uris.isNotEmpty()) {
        Log.d("PhotoPicker", "Number of items selected: ${uris.size}")
    } else {
        Log.d("PhotoPicker", "No media selected")
    }
}

// For this example, launch the photo picker and allow the user to choose images
// and videos. If you want the user to select a specific type of media file,
// use the overloaded versions of launch(), as shown in the section about how
// to [select a single media item](https://developer.android.com/training/data-storage/shared/photopicker#select-single-item).
pickMultipleMedia.launch(PickVisualMediaRequest(PickVisualMedia.ImageAndVideo))
```

This plugin doesn't seem to support it (at least not documented).

**Comment by stuartmorgan** [comment] 2023-03-19 13:02
Closing as a duplicate of https://github.com/flutter/flutter/issues/89159

**Closed by stuartmorgan** 2023-03-19 13:02 UTC
