### ISSUE TITLE
engine try job did not pick up `os`, `runtime_versions`, or `xcode` config changes

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#100797] opened 2022-03-25 21:13 UTC
This PR updated `.ci.yaml` `os`, `runtime_versions`, `xcode`, and some caches:
https://github.com/flutter/engine/pull/32254 branched off https://github.com/flutter/engine/commit/2aa8e16ba1
However, the Mac Web Engine try job used the old configuration properties:
```
$flutter/osx_sdk | { "sdk_version": "12c33" }
...
os | "Mac-10.15"
...
xcode | "12c33"
```
https://ci.chromium.org/p/flutter/builders/try/Mac%20Web%20Engine/23946

A `Mac Web Engine` job from a very similar PR https://github.com/flutter/engine/pull/31915 branched off https://github.com/flutter/engine/commit/b8ff8f138a _did_ pick up the new properties:
https://github.com/flutter/engine/pull/31915, and failed due to an issue with the new version of Xcode https://ci.chromium.org/p/flutter/builders/try/Mac%20Web%20Engine/23954.

**Comment by keyonghan** [comment] 2022-03-25 21:42
Interestingly that on the same commit:
New changes are not populated in 
 Mac Web Engine: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Web%20Engine/23946/overview, but populated in Mac Host Engine: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20Host%20Engine/35173/overview

**Comment by jmagman** [comment] 2022-03-28 19:43
Not sure if this is the same issue, but on one PR the properties picked up correctly on the first test run, which failed (I cancelled it).  When I re-ran the test it didn't pick up the properties.
First run, has updated Xcode properties: https://ci.chromium.org/p/flutter/builders/try/Mac%20Web%20Engine/23994
Hit re-run in the PR checks UI, does not have updated Xcode properties: https://ci.chromium.org/old/p/flutter/builders/try/Mac%20Web%20Engine/24005

**Comment by keyonghan** [comment] 2022-04-05 21:12
Sounds of duplicate of https://github.com/flutter/flutter/issues/99523? But fix seemed landed before this issue.

**Comment by CaseyHillers** [comment] 2022-04-05 21:21
> Sounds of duplicate of https://github.com/flutter/flutter/issues/99523? But fix seemed landed before this issue.

Agreed. I triaged this, and was wondering if it was a bad cocoon rollout that someone did (not containing the latest changes).

**Comment by godofredoc** [comment] 2022-04-08 20:19
Closing as not replicable. Please reopen if this happens again.

**Closed by godofredoc** 2022-04-08 20:19 UTC
Labels: team: infra
