### ISSUE TITLE
[local_auth] [android] Non-biometrics authentication will not work on Android 10 and below. It will prompt to setup Biometrics.

### ISSUE THREAD

**Issue by jacktty** [flutter/flutter#112519] opened 2022-09-28 04:15 UTC
https://user-images.githubusercontent.com/42466125/192686111-4848e7fe-449e-4b9b-ad76-1a21bdc41873.mp4

I have tried non-biometrics authentication such as pin, password or pattern on emulators of Android 10 and below. All will show the dialog box to setup biometrics. However, once i bumped up to Android 11 and above, its working.
I have tested on devices such as Samsung Note 8 (Android 9) and Huawei P40 Pro (Android 10). Both showed the same dialog box result.
For my Samsung Note 20 (Android 12), it worked.

## Steps to Reproduce

(using example [App of 2.1.2 ](https://github.com/flutter/plugins/tree/main/packages/local_auth/local_auth/example))

1. Setup non-biometric such as password, pin or pattern
2. Go to the App and click on the Authenticate button

**Expected results:** 

It should prompt the window to authenticate via password, pin or pattern

**Actual results:** 

It prompt a dialog stating "Biometric required"

## Flutter Doctor
```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale en-SG)
    • Flutter version 3.3.2 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (2 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jacksontan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by jacktty** [comment] 2022-09-28 04:29
As of [LocalAuthPlugin.java](https://github.com/flutter/plugins/blob/main/packages/local_auth/local_auth_android/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java) in local_auth_android

line 151 onwards
```
boolean isBiometricOnly = call.argument("biometricOnly");
boolean allowCredentials = !isBiometricOnly && canAuthenticateWithDeviceCredential();
sendAuthenticationRequest(call, completionHandler, allowCredentials);
```
 If `isBiometricOnly` is false, it will also check the values from the method `canAuthenticateWithDeviceCredential()`


while in `canAuthenticateWithDeviceCredential()`

```
private boolean canAuthenticateWithDeviceCredential() {
    if (biometricManager == null) return false;
    return biometricManager.canAuthenticate(BiometricManager.Authenticators.DEVICE_CREDENTIAL)
        == BiometricManager.BIOMETRIC_SUCCESS;
  }
```

This line could be returning false. From Android 10 and below, DEVICE_CREDENTIAL alone is unsupported. This is stated on [Android Docs](https://developer.android.com/reference/androidx/biometric/BiometricManager#canAuthenticate(int))

Please do help on this. Thanks.

**Comment by danagbemava-nc** [comment] 2022-09-28 11:06
Hi @jacktty, quick question, did this work for you prior to flutter 3, or has it always been this way? There's a similar report about this but the reports seem to indicate that this was working fine prior to flutter 3. See https://github.com/flutter/flutter/issues/108945 for the report

**Comment by jacktty** [comment] 2022-09-28 12:59
> Hi @jacktty, quick question, did this work for you prior to flutter 3, or has it always been this way? There's a similar report about this but the reports seem to indicate that this was working fine prior to flutter 3. See #108945 for the report

Nope. I started on Flutter 3. From report #108945, it seems that the same issue happened on local_auth 2.1.1 and above.
I have checked the local_auth_code of 2.1.0 and 2.1.1, thats where the changes are made.

LocalAuthPlugin of [2.1.1](https://github.com/flutter/plugins/blob/local_auth-v2.1.1/packages/local_auth/local_auth_android/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java) uses just `BiometricManager.Authenticators.DEVICE_CREDENTIAL` alone to check. This would return false as stated on Android Docs, as mentioned on my posting. Basically the same as 2.1.2.

LocalAuthPlugin of [2.1.0](https://github.com/flutter/plugins/blob/local_auth-v2.1.0/packages/local_auth/local_auth_android/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java) does it differently.
It does not check based on `DEVICE_CREDENTIAL`, rather, its based on Android Build version (and other conditions) and set the boolean values straight to the constructor of `AuthenticationHelper`.

I believed thats the difference on how its handled.

**Comment by jacktty** [comment] 2022-09-28 14:14
I have updated the method `canAuthenticateWithDeviceCredential` on my local.

```
private boolean canAuthenticateWithDeviceCredential() {
    //supports from Android 23 onwards
    if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.R ) {
      if (biometricManager == null) return false;
      return biometricManager.canAuthenticate(BiometricManager.Authenticators.DEVICE_CREDENTIAL)
          == BiometricManager.BIOMETRIC_SUCCESS;
    }else if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.M ) {
      if (keyguardManager == null) return false;
      return keyguardManager.isDeviceSecure();
    }
    return false;
}
```

Seems to be working from Android 23 onwards. However, seems like from Android 29 and below, the sticky auth will cause it to prompt more than once. Similar issue with  #80438. Have to set it to false and it will only prompt once.

**Comment by danagbemava-nc** [comment] 2022-09-29 08:21
I can reproduce the bug on android 10 but it works just fine on android 12. 

This may yet be a duplicate of #108945 but the information here seems valuable. 

This is reproducible using the plugin sample code. 

Labeling for further investigation. 

<details>
<summary>recordings</summary>

| android 12 | android 10 | 
| -- | -- |
| <video src="https://user-images.githubusercontent.com/88313112/192977965-8fb73e9a-213f-4b15-ba4d-5fcb88fb1fb7.mov" /> | <video src="https://user-images.githubusercontent.com/88313112/192977977-3004bb46-9f9f-43fd-962e-2dd257043b46.mov" />

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-arm, locale en-GB)
    • Flutter version 3.3.3 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (15 hours ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Users/nexus/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (6 available)
    • sdk gphone64 arm64 (mobile)          • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • Android SDK built for arm64 (mobile) • emulator-5556                        • android-arm64  • Android 10 (API 29) (emulator)
    • Nexus (mobile)                       • 00008020-001875E83A38002E            • ios            • iOS 16.0.2 20A380
    • iPhone 14 Pro (mobile)               • 4302007A-B132-4B89-887A-C5993FCA3284 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)                      • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 105.0.5195.125
    ! Error: Nexus is busy: Fetching debug symbols for Nexus. Xcode will continue when Nexus is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 3.4.0-34.0.pre.8, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
    • Flutter version 3.4.0-34.0.pre.8 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c522996be (3 hours ago), 2022-09-29 13:04:19 +0800
    • Engine revision c003042e52
    • Dart version 2.19.0 (build 2.19.0-252.0.dev)
    • DevTools version 2.17.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[!] Android Studio
    • Android Studio at /Users/nexus/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/213.7172.25.2113.9014738/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8815526/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)          • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • Android SDK built for arm64 (mobile) • emulator-5556                        • android-arm64  • Android 10 (API 29) (emulator)
    • iPhone 14 Pro (mobile)               • 4302007A-B132-4B89-887A-C5993FCA3284 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)                      • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by camsim99** [comment] 2022-09-30 21:00
Closing this as a duplicate of https://github.com/flutter/flutter/issues/111025. [This comment](https://github.com/flutter/flutter/issues/112519#issuecomment-1260372762) contains the context for the fix. Thank you @jacktty!

**Closed by camsim99** 2022-09-30 21:00 UTC
Labels: platform-android, plugin, p: first party, p: local_auth, has reproducible steps, P4, found in release: 3.3, found in release: 3.4

**Comment by amit-astha** [comment] 2022-10-04 05:58
Add this dependency in app gradle file, implementation 'androidx.biometric:biometric:1.1.0'

**Comment by amit-astha** [comment] 2022-10-04 06:24
Add biometric dependency in android app gradle file. "implementation 'androidx.biometric:biometric:1.2.0-alpha05'"
