### ISSUE TITLE
AnimatedOpacity has erratic animation with colored Container as child (Flutter 3.13, iOS)

### ISSUE THREAD

**Issue by SmashHighlights** [flutter/flutter#133012] opened 2023-08-22 00:33 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

If you have an **AnimatedOpacity** with a colored **Container** as its child, it will animate erratically on iOS since the Flutter 3.13 update. In my screen recording you will see that displaying a **CircularProgressIndicator** makes the **AnimatedOpacity** animate smoothly, presumably because it forces the widget to refresh every frame.

I've noticed that an **AnimatedOpacity** with a different child, like **FlutterLogo** or **Icon**, does not exhibit this erratic animation problem.

### Expected results

**AnimatedOpacity** with a colored **Container** child should smoothly animate its opacity.

### Actual results

**AnimatedOpacity** with a colored **Container** child flashes and animates erratically.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'AnimatedOpacity issue (Flutter 3.13)',
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  bool isOpaque = true;
  bool displayProgressIndicator = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('AnimatedOpacity issue'),
      ),
      body: Column(
        children: [
          SwitchListTile(
            value: isOpaque,
            onChanged: (value) => setState(() => isOpaque = !isOpaque),
            title: const Text('Is opaque'),
          ),
          SwitchListTile(
            value: displayProgressIndicator,
            onChanged: (value) => setState(
                () => displayProgressIndicator = !displayProgressIndicator),
            title: const Text('Display progress indicator'),
          ),
          AnimatedOpacity(
            duration: const Duration(milliseconds: 1000),
            opacity: isOpaque ? 1.0 : 0.0,
            child: Container(
              color: Colors.red,
              height: 200,
              margin: const EdgeInsets.all(10),
            ),
          ),
          if (displayProgressIndicator)
            const Center(
              child: CircularProgressIndicator(),
            ),
        ],
      ),
    );
  }
}
```

</details>

### Video demonstration

https://github.com/flutter/flutter/assets/37321068/459333b6-cc8f-4e46-af2c-3393aeae253d

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Flutter (Channel stable, 3.13.0, on macOS 12.5.1 21G83 darwin-x64, locale
    en-GB)
    • Flutter version 3.13.0 on channel stable at
      /Users/mattperren/Desktop/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (6 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mattperren/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPad (mobile)   • 00008103-000D58E01E2B401E • ios            • iOS 16.1
      20B82
    • macOS (desktop) • macos                     • darwin-x64     • macOS
      12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome                    • web-javascript • Google
      Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2023-08-22 09:39
Thanks for filing the issue. I can reproduce this on stable channel but it seems to have been fixed on the latest master channel as I cannot reproduce it there.

<details>
<summary>Demo</summary>

https://github.com/flutter/flutter/assets/104349824/4e7213cf-6987-4b35-b3d9-75ae34b694d3

</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.13.0 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (25 hours ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```bash
[!] Flutter (Channel master, 3.14.0-9.0.pre.24, on macOS 13.5 22G74 darwin-x64, locale en-VN)
    • Flutter version 3.14.0-9.0.pre.24 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8e7304bb27 (26 minutes ago), 2023-08-21 22:35:36 -0400
    • Engine revision 1ab054967c
    • Dart version 3.2.0 (build 3.2.0-94.0.dev)
    • DevTools version 2.26.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • iPhone (mobile) • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.7.2 19H218
    • macOS (desktop) • macos                                    • darwin-x64     • macOS 13.5 22G74 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

I'll close this issue as fixed on the latest channels. If you still experience this issue, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2023-08-22 09:39 UTC
Labels: in triage

**Comment by matehat** [comment] 2023-08-26 00:57
@huycozy Our app exhibits this issue pretty drastically on both Flutter 3.13.0 and 3.13.1. It is not exhibiting this issue on 3.10.x. (though not releasable because of the iOS 16.6 jank bug), nor on the master channel. Any idea when this will be made available on the stable channel so we can finally do a release using the stable branch?

**Comment by huycozy** [comment] 2023-08-28 03:45
You can read about it here: https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#will-a-particular-bug-fix-be-provided-in-a-hotfix-release (and whole that page for more info)

**Comment by matehat** [comment] 2023-08-30 18:55
@huycozy Our production healthcare app [Braver](https://apps.apple.com/ca/app/braver/id1514643813) is currently experiencing [an embarrassing animation issue](https://github.com/flutter/flutter/issues/131319) on 3.10.x that we can't fix because the fix is only available on 3.13.x, which now exhibits a _new_ pretty ugly animation issue (this one here), that will only be available when beta/master makes it to stable, as far as I understand it.

https://github.com/flutter/flutter/assets/1283/93a2fd0c-b5ef-4b68-bc78-6f6e60c7f5db

Even if this issue is now fixed in master, we should prioritize it high enough so it eventually lands in a hotfix release, because it currently affects apps in production running 3.13.x. 

In our case (and I suppose for many others), it's not an option to use beta or master channel in production, because multiple breaking changes landed there, like WillPopScope that was removed, and some deprecated-now-removed types that third-party libraries haven't yet removed.

**Comment by matehat** [comment] 2023-09-01 18:54
@huycozy to be more explicit, can you put a decent priority on this issue so a hotfix can be considered? Just filing it as fixed on master is not going to make it considered at all.

Our app has become incredibly janky on iOS, it's embarassing, and we currently can't do anything about it.

/cc @Hixie

**Comment by SmashHighlights** [comment] 2023-09-03 18:06
@matehat Small suggestion in case you haven't considered: If you implemented the scrim yourself, you could replace the `AnimatedOpacity` with an `AnimatedContainer` that changes color. I've found that `AnimatedContainer` doesn't exhibit this bug in stable.

**Comment by Hixie** [comment] 2023-09-04 02:12
This issue is closed so the priority would have no effect; see https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process for instructions on how to get a hotfix applied.

**Comment by matehat** [comment] 2023-09-06 22:39
> This issue is closed so the priority would have no effect; see https://github.com/flutter/flutter/wiki/Flutter-Cherrypick-Process for instructions on how to get a hotfix applied.

@Hixie thanks for the pointer, but there's no commit hash identified at this point, we just know that something on main has fixed the issue. I was hoping someone more knowledgeable of Impeller would have an idea, hence why I mentioned you (sorry if I bothered you btw).

>  I've found that AnimatedContainer doesn't exhibit this bug in stable.

@SmashHighlights thanks for pointer, will try it out and post back if it fixes it for us too!

**Comment by matehat** [comment] 2023-09-06 22:44
For the record, it doesn't fix it for us. So another issue could be at play. I'll make a minimal reproducible example (that breaks on stable but works on master) and file another issue.

**Comment by ganwumeng** [comment] 2023-09-09 09:24
The same.It runs well in 3.10, but it runs badly in 3.13(Only iOS).

**Comment by matehat** [comment] 2023-09-21 12:49
In our case, after playing around with tweaks, we could make it work by doing the equivalent of replacing:

```dart
AnimatedOpacity(
  opacity: opacity,
  child: Container(
    color: someColor
    ...
  ),
)
```

or even 

```dart
Opacity(
  opacity: animation.value,
  child: Container(
    color: someColor
    ...
  ),
)
```

by

```dart
Container(
  color: someColor.withOpacity(animation.value),
  ...
)
```
