### ISSUE TITLE
Share plugin does not work on iOS when it is invalid for a view controller to be presented on iOS's root view controller

### ISSUE THREAD

**Issue by sianxz** [flutter/flutter#67103] opened 2020-10-02 03:30 UTC
The current implementation attempts to present the share sheet on the current window's root view controller. This does not work if the root view controller is not active, resulting in errors like: 

"Attempt to present <UIActivityViewController: 0x142a8d000> on ... whose view is not in the window hierarchy!".

An example of this situation is when a view controller is being presented. This is probably common when doing add-to-app, where you might present the FlutterViewController (as done in the add-to-app examples).

**Comment by TahaTesser** [comment] 2020-10-02 09:58
Hi @sianxz 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by mehmetf** [comment] 2020-10-08 05:16
Reproduction is:

- Take an add-to-app example which presents a FlutterViewController from a native controller.
- Try to use share plugin from inside Flutter.

@sianxz is that accurate?

**Comment by sianxz** [comment] 2020-10-08 06:08
Yep, that should repro it; the issue occurs whenever it's invalid to present the share sheet on the root view controller, e.g., when something is already being presented on the root view controller.

**Comment by TahaTesser** [comment] 2020-10-08 08:12
Hi @sianxz 
Thanks, I can reproduce on the latest `master` channel 

### Preview
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/95432191-f1559300-096b-11eb-99a4-8144b0b02a4b.gif)


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.220, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.23.0-8.0.pre.220 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 0b78110b26 (6 hours ago), 2020-10-07 19:29:47 -0700
    • Engine revision 2eac514f26
    • Dart version 2.11.0 (build 2.11.0-186.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile)     • 00008020-001059882212002E            • ios            • iOS
      14.0.1
    • iPhone 11 Pro Max (mobile) • 8077196C-CC09-401F-8842-06A94368FF46 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac
      OS X 10.15.7 19H2 x86_64
    • Web Server (web)           • web-server                           • web-javascript •
      Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!

```

</details>

**Comment by ajmalsalim** [comment] 2020-12-01 13:33
Related to #34787 and  #3105

**Comment by ajmalsalim** [comment] 2020-12-01 13:36
The issue is related to image_picker: Attempt to present on whose view is not in the window hierarchy #34787

Also, PR https://github.com/flutter/plugins/pull/3105

**Comment by stuartmorgan** [comment] 2021-05-27 14:53
Closing, as share is now deprecated in favor of [share_plus](https://pub.dev/packages/share_plus).

**Closed by stuartmorgan** 2021-05-27 14:53 UTC
Labels: P6, a: existing-apps, customer: google, found in release: 1.23, has reproducible steps, p: first party, p: share, platform-ios, plugin
