### ISSUE TITLE
Hiding keyboard in multiple buttons onPressed

### ISSUE THREAD

**Issue by perfoWorks** [flutter/flutter#59678] opened 2020-06-17 13:23 UTC
I'm trying to hide keyboard when tapped everywhere outside of textField even on buttons clicked. Reason: I've got many buttons doing different things and so I want to avoid duplicate codes in each button onPressed to unfocus keyboard. So I wrapped Scaffold with GestureDetector and set onTap with unfocused(). That works well however when a button is pressed then the keyboard is still active

```
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => FocusScope.of(context).unfocus(),
      child: Scaffold(
        appBar: AppBar(
          actions: <Widget>[FlatButton(child: Text('Done'), onPressed: () {})],
        ),
        body: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            FlatButton(
              child: Text('something'),
              onPressed: () {},
            ),
            TextField(),
          ],
        ),
      ),
    );
  }
```

so I've changed GestureDetector parameter with 

```
GestureDetector(
 onPanDown: (pd) => FocusScope.of(context).unfocus(),
...
```

That work well however when you click on already focused textField it comes with an exception thrown in run terminal

> (
>     "<NSLayoutConstraint:0x6000035170c0 'assistantHeight' TUISystemInputAssistantView:0x7fe96143dc60.height == 44   (active)>",
>     "<NSLayoutConstraint:0x60000357c3c0 'assistantView.bottom' TUISystemInputAssistantView:0x7fe96143dc60.bottom == _UIKBCompatInputView:0x7fe96144e060.top   (active)>",
>     "<NSLayoutConstraint:0x60000357fa70 'assistantView.top' V:|-(0)-[TUISystemInputAssistantView:0x7fe96143dc60]   (active, names: '|':UIInputSetHostView:0x7fe96143e910 )>",
>     "<NSLayoutConstraint:0x600003516c60 'inputView.top' V:|-(0)-[_UIKBCompatInputView:0x7fe96144e060]   (active, names: '|':UIInputSetHostView:0x7fe96143e910 )>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x60000357c3c0 'assistantView.bottom' TUISystemInputAssistantView:0x7fe96143dc60.bottom == _UIKBCompatInputView:0x7fe96144e060.top   (active)>
> 
> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
> The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

Link to SO question
[https://stackoverflow.com/questions/62425982/removing-keyboard-focus-on-multiple-buttons-pressed/62429354#62429354](url)

Flutter doctor

> /Users/peter/development/tools/flutter/bin/flutter doctor --verbose
> [✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-GB)
>     • Flutter version 1.17.3 at /Users/peter/development/tools/flutter
>     • Framework revision b041144f83 (13 days ago), 2020-06-04 09:26:11 -0700
>     • Engine revision ee76268252
>     • Dart version 2.8.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/peter/Library/Android/sdk
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.5, Build version 11E608c
>     • CocoaPods version 1.8.4
> 
> [✓] Android Studio (version 4.0)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 46.0.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.45.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.10.2
> 
> [✓] Connected device (1 available)
>     • iPhone SE (2nd generation) • F933AAC4-9E3C-4026-B525-E2D39F4704A8 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
> 
> • No issues found!

**Comment by VladyslavBondarenko** [comment] 2020-06-17 13:35
Hi @perfoWorks 
could you provide your `flutter doctor -v`?
I can't reproduce it when running with current dev `1.20.0-0.0.pre` on Android 9 device

**Comment by perfoWorks** [comment] 2020-06-17 13:41
@VladyslavBondarenko I have added flutter doctor into the comment.. BTW the same error is thrown when GestureDetector has onTap parameter set to unfocused

**Comment by VladyslavBondarenko** [comment] 2020-06-17 13:57
Reproduced with stable stable `v1.17.3` and current dev `1.20.0-0.0.pre` on iOS 13.5. 
App doesn't crash. The error is visible only in xcode terminal, isn't shown when running with `flutter run` or `flutter run --verbose`

**Comment by perfoWorks** [comment] 2020-06-17 14:06
@VladyslavBondarenko it is also visible in AS run terminal.. The app doesn't crash an it works fine.. However adding GestureDetector at the top of the widget tree to un focus keyboard when tap outside of the textfield remove ability to move cursor in TextField by taping on it. I actually meant to place this comment as feature request but didn't find proper place for it.. Is there any chance to add this feature? Please if you need more details then let me know

**Comment by exaby73** [comment] 2022-05-17 10:39
Issue is fixed in the latest stable and master channels. Clicking on the `TextField` even after it's focused doesn't produce any errors in the console. Though by the video you can see the the keyboard is momentarily hidden, then shown again. Though that's expected as the `GestureDetector`'s `onPanDown` is executed before the `TextField` requests for focus.

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onPanDown: (_) => FocusScope.of(context).unfocus(),
      child: Scaffold(
        appBar: AppBar(
          actions: <Widget>[
            TextButton(
              child: const Text('Done'),
              onPressed: () {},
            ),
          ],
        ),
        body: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            TextButton(
              child: const Text('something'),
              onPressed: () {},
            ),
            const TextField(),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details><summary>Video</summary>

https://user-images.githubusercontent.com/50555895/168792654-1cd0c545-31f3-4ac4-942b-4cb9c8c73590.mov

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.0.0 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (7 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.52

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 101.1.38.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.745, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.745 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c248854d17 (5 hours ago), 2022-05-16 23:57:08 -0400
    • Engine revision fce741dd83
    • Dart version 2.18.0 (build 2.18.0-120.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.52

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • V2050 (mobile)  • 3085425058000NM • android-arm64  • Android 12 (API 31)
    • macOS (desktop) • macos           • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)    • chrome          • web-javascript • Brave Browser 101.1.38.115

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Closed** 2022-05-17 10:40 UTC
Labels: platform-ios, framework, f: focus, has reproducible steps, found in release: 1.17, found in release: 1.20, r: fixed
