### ISSUE TITLE
Line breaks doesn't work in Flutter Textfield on Android.

### ISSUE THREAD

**Issue by Dorbmon** [flutter/flutter#50470] opened 2020-02-10 14:56 UTC
This is am example program.

```
import 'dart:ui';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return tt();
  }
}

class tt extends State<MyApp> {
  final cc = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      appBar: AppBar(
        title: Text("test"),
      ),
      body: SingleChildScrollView(
          child: TextField(
            keyboardType: TextInputType.multiline,
        maxLines: null,
        controller: cc,
      )),
    ));
  }
}

```
When I input enter on Android,it doesn't work.And I found it works well on web and stable channel.I dont know why.
My flutter doctor -v:
```
[✓] Flutter (Channel master, v1.15.3-pre.37, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.15.3-pre.37 at /media/dorbmon/code/flutter
    • Framework revision 6dc3bfaa98 (3 天前), 2020-02-07 18:28:02 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/dorbmon/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /media/dorbmon/code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /media/dorbmon/code/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • PCT AL10   • 5ENDU19321010017 • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome           • web-javascript • Google Chrome
      79.0.3945.130
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!
```

**Comment by Dorbmon** [comment] 2020-02-10 14:59
I have tried master,dev,beta channels.line break doesn't work on these channels.
It seems it only works on stable channel and web.

**Comment by justinmc** [comment] 2020-02-10 17:19
@Dorbmon What kind of keyboard are you using?  I tried this out randomly on English, Russian, and Chinese keyboards on an Anrdoid emulator, and I was able to reproduce the problem only on the Chinese keyboard.

**Comment by justinmc** [comment] 2020-02-10 18:38
I think I've found the cause of the bug in https://github.com/flutter/flutter/issues/50328.

I'm going to close this issue so we can focus conversation over there.  I'm assuming that they're the same bug and whatever solves https://github.com/flutter/flutter/issues/50328 will solve this issue too, but if that's not true, let me know and I'll reopen this!

**Closed by justinmc** 2020-02-10 18:38 UTC
Labels: a: internationalization, a: text input, f: material design, framework, severe: regression
