### ISSUE TITLE
TextField input emoji of "shy",the cursor jump to the start of text

### ISSUE THREAD

**Issue by czronaldo11** [flutter/flutter#29841] opened 2019-03-23 12:54 UTC
## Steps to Reproduce

TextField input emoji of "shy",the cursor jump to the start of text

## Logs

```
```

[âˆš] Flutter (Channel dev, v1.3.13, on Microsoft Windows [Version 6.1.7601],
    locale zh-CN)
    â€¢ Flutter version 1.3.13 at D:\flutter
    â€¢ Framework revision 59ce7d6bff (5 days ago), 2019-03-18 11:20:10 -0700
    â€¢ Engine revision e75f6de01f
    â€¢ Dart version 2.2.1 (build 2.2.1-dev.1.1 None)

[âˆš] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    â€¢ Android SDK at E:\Users\Administrator\AppData\Local\Android\sdk
    â€¢ Android NDK location not configured (optional; useful for native profiling
      support)
    â€¢ Platform android-28, build-tools 28.0.3
    â€¢ ANDROID_HOME = E:\Users\Administrator\AppData\Local\Android\sdk
    â€¢ Java binary at: E:\Program Files\Android\Android Studio\jre\bin\java
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    â€¢ All Android licenses accepted.

[âˆš] Android Studio (version 3.2)
    â€¢ Android Studio at E:\Program Files\Android\Android Studio
    â€¢ Flutter plugin version 29.1.1
    â€¢ Dart plugin version 181.5656
    â€¢ Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[âˆš] Connected device (1 available)

![Image](https://user-images.githubusercontent.com/11837386/54866364-ddf4ce00-4dad-11e9-86a2-e57489df04f9.png)

**Comment by justinmc** [comment] 2020-04-06 18:19
I believe this is a duplicate of https://github.com/flutter/flutter/issues/31818, so I'm going to close this, but please let me know if this seems to be a different issue and we can reopen it.

We're currently investigating providing much better support for emojis (see https://github.com/flutter/flutter/pull/53381), so either way this will hopefully be resolved soon.

**Closed by justinmc** 2020-04-06 18:19 UTC
Labels: a: text input, framework
