### ISSUE TITLE
Flutter web needs a way to support updating meta tags open graph sharing and basic seo

### ISSUE THREAD

**Issue by AlmogRnD** [flutter/flutter#86629] opened 2021-07-18 21:35 UTC
## Use case

If your developing any kind of web-based platform using Flutter let's say something like Reddit, Facebook, or pretty anything you need to be able to dynamical update the open graph meta tags and SEO meta tags so if a user is sharing a public page or posting a URL on LinkedIn, Slack or anywhere the correct title, description, and preview image can be shown.   

I don't expect to have full SSR support but something basic there is not a web-based frontend framework that you can't do this with.

**Comment by TahaTesser** [comment] 2021-07-20 08:12
Hi @AlmogRnD 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/46789
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-20 08:12 UTC
Labels: in triage
