### ISSUE TITLE
package:flutter/src/widgets/framework.dart': Failed assertion: line 3571 pos 12: '!_dirty': is not : true

### ISSUE THREAD

**Issue by dmlzj** [flutter/flutter#35718] opened 2019-07-08 03:43 UTC
## Steps to Reproduce

1. I created a global event listener on the home page, created OverlayEntry when the value is true, and displays it on other pages;
2. Now OverlayEntry is displayed, but this error is reported, not sure if it is my own problem. !

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while rebuilding dirty elements:
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3571 pos 12: '!_dirty': is not
flutter: true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      Element.rebuild 
package:flutter/…/widgets/framework.dart:3571
flutter: #3      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2278
flutter: #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:700
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:286
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1012
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:952
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:864
flutter: #12     _invoke  (dart:ui/hooks.dart:219:10)
flutter: #13     _drawFrame  (dart:ui/hooks.dart:178:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
```

```
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/dmlzj/www/flutter/source
    • Framework revision 7a4c33425d (10 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dmlzj/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/dmlzj/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • iPhone 6s Plus • 6429CE55-63CE-4D56-A211-AF805487B982 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • iPhone X       • 797028AE-1310-4EC8-8BBD-AC3591ABD83E • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by dmlzj** [comment] 2019-07-08 03:47
My code :
```dart
class Index extends StatefulWidget {
  @override
  _IndexState createState() => _IndexState();
}

class _IndexState extends State<Index> {
  int tabIndex = 0;
  OverlayEntry overlayEntry;
  @override
  void initState() {
    bus.on('globalAudio', (arg) async{
      LogUtil.v(arg);
      if (arg) {
        await createGlobalAudio(context);
      } else {
        overlayEntry.remove();
      }
    });
    super.initState();
  }

  List<Widget> pageView = [HomeView(), ReadInnovation(), MyView()];
  @override
  void dispose() {
    super.dispose();
  }

  void selectTab(int index) {
    setState(() {
      tabIndex = index;
    });
  }

  // 创建全局音频窗口
  Future createGlobalAudio(BuildContext context) async{
    overlayEntry = new OverlayEntry(
      builder: (context) {
        // FocusScope.of(context).setFirstFocus(focusScopeNode);
        return Positioned(
            width: MediaQuery.of(context).size.width,
            height: 54,
            bottom: 180,
            // color: Colors.red,
            child: new Material(
              child: Padding(
                  padding: const EdgeInsets.all(0.0),
                  child: Column(
                    children: <Widget>[
                      DecoratedBox(
                        decoration: new BoxDecoration(
                          // border: new Border.all(
                          //     color: Color(0xFFFF0000), width: 0.5), // 边色与边宽度
                          // 生成俩层阴影，一层绿，一层黄， 阴影位置由offset决定,阴影模糊层度由blurRadius大小决定（大就更透明更扩散），阴影模糊大小由spreadRadius决定
                          borderRadius: BorderRadius.only(topLeft: Radius.circular(8), topRight: Radius.circular(8)),
                          boxShadow: [
                            BoxShadow(
                                color: Color.fromRGBO(0, 0, 0, 0.12),
                                offset: Offset(5.0, -5.0),
                                blurRadius: 10.0,
                                spreadRadius: 5.0),
                            // BoxShadow(
                            //     // color: Color(0x9900FF00),
                            //     offset: Offset(1.0, 1.0)), 
                            BoxShadow(color: Color.fromRGBO(255, 255, 255, 0.9))
                          ],
                        ),
                        child: Row(
                          children: <Widget>[
                            Text('data', style: TextStyle(color: Colors.red),)
                          ],
                        )
                      )
                    ],
                  ),
                ),
            
            ),);
      },
    );
    //往Overlay中插入插入OverlayEntry    
    Overlay.of(context).insert(overlayEntry);

    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    
    return Scaffold(
      body: pageView[tabIndex],
      bottomNavigationBar: BottomNavigationBar(
        selectedItemColor: Colors.red,
        items: const <BottomNavigationBarItem>[
          BottomNavigationBarItem(
            icon: Icon(Icons.home),
            title: Text('home'),
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.chrome_reader_mode),
            title: Text('read'),
          ),
          BottomNavigationBarItem(
            icon: Icon(
              Icons.people,
            ),
            title: Text('my'),
          )
        ],
        currentIndex: tabIndex,
        onTap: selectTab,
      ),
    );
  }
}
```

**Comment by vinodlee** [comment] 2019-11-04 08:39
**Am facing  this Error**
'package:flutter/src/widgets/framework.dart': Failed assertion: line 2306 pos 12: '!_debugBuilding': is not true. 

How can I fix this?

**Comment by and301** [comment] 2020-01-09 00:53
do not use flutter

**Comment by iapicca** [comment] 2020-07-01 12:01
Hi @dmlzj 
Could you please run `flutter upgrade --force`. 
If the issue persists, please provide your updated `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal reproducible code sample.
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-07-23 09:03
@dmlzj 
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with filling out template

**Closed by VladyslavBondarenko** 2020-07-23 09:03 UTC
Labels: in triage, waiting for customer response

**Comment by daixianceng** [comment] 2021-04-26 07:59
While this error because you called `setState` more than one times in a lifecycle. Try to merges `setState` into a single call.
