### ISSUE TITLE
1.16.4-pre.{50,72}: Linking fails with missing symbols for Firebase et al on arm64

### ISSUE THREAD

**Issue by jrmiddle** [flutter/flutter#53881] opened 2020-04-02 23:21 UTC
Starting with 1.16.4-pre.50, and continuing with 1.16.4-pre.72, `arm64` builds fail linking for Firebase/Google related symbols.

## Error Message

```
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_GULHeartbeatDateStorage", referenced from:
          objc-class-ref in FirebaseCore(FIRHeartbeatInfo.o)
      "_OBJC_CLASS_$_GMSPolyline", referenced from:
          objc-class-ref in google_maps_flutter(GoogleMapPolylineController.o)
      "_OBJC_CLASS_$_GMSMarker", referenced from:
          objc-class-ref in google_maps_flutter(GoogleMapMarkerController.o)
      "_GULLogBasic", referenced from:
          _FIRLogBasic in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_GULReachabilityChecker", referenced from:
          objc-class-ref in FirebaseMessaging(FIRMessaging.o)
      "_OBJC_CLASS_$_GMSCameraPosition", referenced from:
          objc-class-ref in google_maps_flutter(GoogleMapController.o)
      "_GULIsLoggableLevel", referenced from:
          _FIRIsLoggableLevel in FirebaseCore(FIRLogger.o)
      "_GULLoggerEnableSTDERR", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_GMSMutablePath", referenced from:
          objc-class-ref in google_maps_flutter(GoogleMapPolylineController.o)
      "_OBJC_CLASS_$_GMSCoordinateBounds", referenced from:
          objc-class-ref in google_maps_flutter(GoogleMapController.o)
      "_OBJC_CLASS_$_GULSecureCoding", referenced from:
          objc-class-ref in FirebaseMessaging(FIRMessagingPubSub.o)
      "_OBJC_CLASS_$_GMSMapView", referenced from:
          objc-class-ref in google_maps_flutter(GoogleMapController.o)
      "_kGMSMinZoomLevel", referenced from:
          _InterpretMapOptions in google_maps_flutter(GoogleMapController.o)
      "_kGMSMaxZoomLevel", referenced from:
          _InterpretMapOptions in google_maps_flutter(GoogleMapController.o)
      "_OBJC_CLASS_$_Fabric", referenced from:
          objc-class-ref in flutter_crashlytics(FlutterCrashlyticsPlugin.o)
      "_GULLoggerForceDebug", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_GULUserDefaults", referenced from:
          objc-class-ref in FirebaseInstanceID(FIRInstanceID.o)
          objc-class-ref in FirebaseMessaging(FIRMessaging.o)
          objc-class-ref in FirebaseInstanceID(FIRInstanceIDUtilities.o)
          objc-class-ref in FirebaseMessaging(FIRMessagingPubSub.o)
          objc-class-ref in FirebaseInstallations(FIRInstallationsStore.o)
          objc-class-ref in FirebaseInstanceID(FIRInstanceIDCheckinPreferences.o)
      "_GULResetLogger", referenced from:
          _FIRResetLogger in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_GULAppEnvironmentUtil", referenced from:
          objc-class-ref in FirebaseCore(FIRApp.o)
          objc-class-ref in FirebaseInstanceID(FIRInstanceID.o)
          objc-class-ref in FirebaseCore(FIRBundleUtil.o)
      "_GULSetLoggerLevel", referenced from:
          _FIRSetLoggerLevel in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_CLSStackFrame", referenced from:
          objc-class-ref in flutter_crashlytics(FlutterCrashlyticsPlugin.o)
      "_GULLoggerInitializeASL", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_GULLoggerRegisterVersion", referenced from:
          ___FIRLoggerInitializeASL_block_invoke in FirebaseCore(FIRLogger.o)
      "_OBJC_CLASS_$_GMSServices", referenced from:
          objc-class-ref in AppDelegate.o
      "_CLSLog", referenced from:
          -[FlutterCrashlyticsPlugin onInitialisedMethodCall:result:] in flutter_crashlytics(FlutterCrashlyticsPlugin.o)
          -[FlutterCrashlyticsPlugin crash:reason:frames:] in flutter_crashlytics(FlutterCrashlyticsPlugin.o)
      "_OBJC_CLASS_$_GMSCameraUpdate", referenced from:
          objc-class-ref in google_maps_flutter(GoogleMapController.o)
      "_OBJC_CLASS_$_GULAppDelegateSwizzler", referenced from:
          objc-class-ref in FirebaseMessaging(FIRMessaging.o)
          objc-class-ref in FirebaseMessaging(FIRMessagingAnalytics.o)
          objc-class-ref in FirebaseMessaging(FIRMessagingContextManagerService.o)
          objc-class-ref in FirebaseMessaging(FIRMessagingRemoteNotificationsProxy.o)
      "_OBJC_CLASS_$_Crashlytics", referenced from:
          objc-class-ref in flutter_crashlytics(FlutterCrashlyticsPlugin.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
Could not build the precompiled application for the device.

Error launching application on Jenkins iPhone SE.
Exited (sigterm)

```

## `flutter doctor` output

*Note, I'm using VSCode and not compiling on Android at the moment.*

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.16.4-pre.72, on Mac OS X 10.15.4 19E266, locale en-US)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

! Doctor found issues in 4 categories.
```

## `flutter build --debug --verbose` output

[flutter-run-log.txt](https://github.com/flutter/flutter/files/4424252/flutter-run-log.txt)

**Comment by iapicca** [comment] 2020-04-03 06:24
Hi @jrmiddle 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-04-03 06:24 UTC

**Comment by jrmiddle** [comment] 2020-04-03 14:34
Thanks @iapicca, will do.

**Comment by jrmiddle** [comment] 2020-04-03 14:42
FirebaseExtended/flutterfire#2296
