### ISSUE TITLE
Crashed: com.apple.main-thread /  ___CFXRegistrationPost_block_invoke + 52

### ISSUE THREAD

**Issue by YDA93** [flutter/flutter#96827] opened 2022-01-19 00:44 UTC
## Steps to Reproduce

Crash is not reproducible. Only can be found in Crashlytics dashboard.

**Event summary**
<details>
2.1.1 (64)
iOS 14.5.0
iPhone 12 Pro Max
Jan 17, 2022, 10:09:41 PM
</details>

------------------------
**Actual results:** 

<details>
<summary>
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000006a8
</summary>

```

Crashed: com.apple.main-thread
0  Flutter                        0x3b8404 (Missing)
1  Flutter                        0x3e464 (Missing)
2  Flutter                        0x3c1f0 (Missing)
3  Flutter                        0x3c67ac (Missing)
4  Flutter                        0x3c6150 (Missing)
5  Flutter                        0x12b2c (Missing)
6  Flutter                        0xf1cc (Missing)
7  CoreFoundation                 0x84534 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
8  CoreFoundation                 0x844dc ___CFXRegistrationPost_block_invoke + 52
9  CoreFoundation                 0x83a48 _CFXRegistrationPost + 440
10 CoreFoundation                 0x83408 _CFXNotificationPost + 716
11 Foundation                     0x667c -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
12 UIKitCore                      0xbd62ac -[UIApplication _terminateWithStatus:] + 300
13 UIKitCore                      0x222cc0 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
14 UIKitCore                      0x2228f0 -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 220
15 UIKitCore                      0xbcbe48 -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
16 FrontBoardServices             0x69a8 -[FBSUIApplicationWorkspaceShim workspaceShouldExit:withTransitionContext:] + 88
17 FrontBoardServices             0x353d4 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 80
18 FrontBoardServices             0x196a4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
19 FrontBoardServices             0x3536c __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 132
20 libdispatch.dylib              0x47ec _dispatch_client_callout + 20
21 libdispatch.dylib              0x82dc _dispatch_block_invoke_direct + 268
22 FrontBoardServices             0x5dfa0 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
23 FrontBoardServices             0x5dc30 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 448
24 FrontBoardServices             0x5e184 -[FBSSerialQueue _performNextFromRunLoopSource] + 32
25 CoreFoundation                 0xa3848 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
26 CoreFoundation                 0xa3744 __CFRunLoopDoSource0 + 208
27 CoreFoundation                 0xa2a48 __CFRunLoopDoSources0 + 268
28 CoreFoundation                 0x9ca28 __CFRunLoopRun + 820
29 CoreFoundation                 0x9c1c0 CFRunLoopRunSpecific + 600
30 GraphicsServices               0x3734 GSEventRunModal + 164
31 UIKitCore                      0xbca7e4 -[UIApplication _run] + 1072
32 UIKitCore                      0xbd0054 UIApplicationMain + 168
33 Runner                         0x5bc0 main + 5 (AppDelegate.swift:5)
34 libdyld.dylib                  0x1cf8 start + 4

```
</details>

------------------------
**flutter doctor -v**
<details>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-KW)
    • Flutter version 2.8.1 at /Users/yousefalmutairi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/yousefalmutairi/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-11.0.12.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • SM G965F (mobile) • 2449cd411a1c7ece • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 97.0.4692.71

• No issues found!

```
</details>

**Comment by mkay-42069** [comment] 2022-01-19 06:20
And once again, is a known and already fixed bug, only needs to be pushed to beta/stable.

https://github.com/flutter/flutter/issues/96424
https://github.com/flutter/flutter/issues/95844
https://github.com/flutter/flutter/issues/96768

**Comment by darshankawar** [comment] 2022-01-19 06:49
@mkay-42069 
This seems to be duplicate of https://github.com/flutter/flutter/issues/95844 which has been merged on master. You'll need to wait until this fix is pushed to stable.
Closing as duplicate and already fixed.

**Closed by darshankawar** 2022-01-19 06:49 UTC
Labels: in triage
