### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by MfmRifath** [flutter/flutter#159693] opened 2024-12-02 21:02 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008030-001A19493A78202E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#7      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-LK)
    • Flutter version 3.24.5 on channel stable at /Users/mohammedfareesmohammedrifath/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/mohammedfareesmohammedrifath/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.2)
    • VS Code at /Users/mohammedfareesmohammedrifath/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone (mobile)                 • 00008030-001A19493A78202E • ios            • iOS 18.0 22A3354
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.86

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: dec2ee5c1f98f8e84a7d5380c05eb8a3d0a81668
### Plugins
cloud_firestore-5.5.0
cloud_firestore_web-4.3.4
cloud_functions-5.1.5
cloud_functions_web-4.10.4
file_selector_linux-0.9.3+2
file_selector_macos-0.9.4+2
file_selector_windows-0.9.3+3
firebase_auth-5.3.3
firebase_auth_web-5.13.4
firebase_core-3.8.0
firebase_core_web-2.18.1
firebase_storage-12.3.6
firebase_storage_web-3.10.5
flutter_inappwebview-6.1.5
flutter_inappwebview_android-1.1.3
flutter_inappwebview_ios-1.1.2
flutter_inappwebview_macos-1.1.2
flutter_inappwebview_web-1.1.2
flutter_inappwebview_windows-0.6.0
flutter_native_splash-2.4.3
flutter_plugin_android_lifecycle-2.0.23
geolocator-13.0.2
geolocator_android-4.6.1
geolocator_apple-2.3.8+1
geolocator_web-4.1.1
geolocator_windows-0.2.3
google_maps_flutter-2.10.0
google_maps_flutter_android-2.14.11
google_maps_flutter_ios-2.13.2
google_maps_flutter_web-0.5.10
google_sign_in-6.2.2
google_sign_in_android-6.1.33
google_sign_in_ios-5.7.8
google_sign_in_web-0.12.4+3
image_picker-1.1.2
image_picker_android-0.8.12+18
image_picker_for_web-3.0.6
image_picker_ios-0.8.12+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
payhere_mobilesdk_flutter-3.0.11
permission_handler-11.3.1
permission_handler_android-12.0.13
permission_handler_apple-9.4.5
permission_handler_html-0.1.3+5
permission_handler_windows-0.2.1

**Comment by danagbemava-nc** [comment] 2024-12-03 07:48
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131

**Closed by danagbemava-nc** 2024-12-03 07:48 UTC
Labels: in triage
