### ISSUE TITLE
[webview_flutter] AppBar doesn't change when navigating to a WebView widget

### ISSUE THREAD

**Issue by HaHongDo** [flutter/flutter#104381] opened 2022-05-23 03:29 UTC
The output is shown in the video, the AppBar title was supposed to change to the product's name. This doesn't happen when i remove the WebView widget. If I change the url to something else like google.com, the problem still persists. I'm using get (version ^4.3.4) to navigate between pages. The webview_flutter version is 3.0.4.

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:**  The AppBar title shound change to the product's name

**Actual results:**  

https://user-images.githubusercontent.com/63568276/169737550-412e3dab-cf87-4e7b-9a79-1d4ee35056a4.mp4

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.22000.675], locale en-US)
    • Flutter version 2.10.5 at D:\Android_Modules\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (5 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at D:\Android_Modules\Sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: D:\JetBrains\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at E:\Microsoft Visual Studio
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at D:\JetBrains\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Community Edition (version 2021.2)
    • IntelliJ at E:\JetBrains\IntelliJ IDEA Community Edition 2021.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • ONEPLUS A5000 (mobile) • localhost:52669 • android-x64    • Android 7.1.1 (API 25)
    • Windows (desktop)      • windows         • windows-x64    • Microsoft Windows [Version 10.0.22000.675]
    • Chrome (web)           • chrome          • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)             • edge            • web-javascript • Microsoft Edge 101.0.1210.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2022-05-23 11:15
Hi @HaHongDo, Thanks for filing the issue. Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue. Also, You seem to be using the older version of flutter, I would advise updating to latest `stable 3.0.1` and see if that helps fix the issue.

**Comment by HaHongDo** [comment] 2022-05-23 17:04
Minimal code:
main.dart:
```
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get/get_core/src/get_main.dart';
import 'package:sample_application/webViewScreen.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
          centerTitle: true,
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: const <Widget>[],
          ),
        ),
        floatingActionButton: Center(
          child: FloatingActionButton(
            onPressed: () => Get.to(() => WebViewScreen()),
            child: const Icon(Icons.refresh),
          ),
        ) // This trailing comma makes auto-formatting nicer for build methods.
        );
  }
}
```
webViewScreen.dart
```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class WebViewScreen extends StatefulWidget {
  const WebViewScreen({Key? key}) : super(key: key);

  @override
  State<WebViewScreen> createState() => _WebViewScreenState();
}

class _WebViewScreenState extends State<WebViewScreen> {
  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) WebView.platform = SurfaceAndroidWebView();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text("Product Title"),
          centerTitle: true,
        ),
        body: const WebView(
          initialUrl: "https://google.com",
        ));
  }
}
```
I just edit a little bit the default flutter code android studio generated, to run the application add webview_flutter: 3.0.4 and get:  4.6.5 to pubspec.yaml, also add minSdkVersion 19 to defaultConfig in build.gradle. I'm using flutter 2.10.5 because upgrading to flutter 3.0.1 results in a bunch of null safety errors in multiple flutter packages that even running pub upgrade can't solve.

**Comment by maheshmnj** [comment] 2022-05-24 07:19
Hi @HaHongDo, thanks fo the code sample I verified on `stable 3.0.0` and I see it working as intended. The appbar changes on navigation.

https://user-images.githubusercontent.com/31410839/169971979-68cc6494-6242-4c59-afa8-5d9905bd3b80.mov

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by HaHongDo** [comment] 2022-05-25 03:33
Thanks, @maheshmnj, it seems to be a problem with flutter 2.10.5. I have to find a workaround for this problem.

**Comment by maheshmnj** [comment] 2022-05-25 04:53
Thanks for the update @HaHongDo, However upgrading to `stable 3.0.0` should fix the issue for you.

> I'm using flutter 2.10.5 because upgrading to flutter 3.0.1 results in a bunch of null safety errors in multiple flutter packages that even running pub upgrade can't solve.

Regarding this probably you are seeing widget binding warnings same as https://github.com/flutter/flutter/issues/103561 if you do then that should not interrupt the build process, In case, it does feel free to file a new issue and we would love to investigate. 
Closing as your code sample works fine on stable 3.0.0

**Closed by maheshmnj** 2022-05-25 04:53 UTC
Labels: in triage
