### ISSUE TITLE
flutter doctor --android-licenses: ProcessException: The system cannot find the file specified C:\Users\admin\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --version

### ISSUE THREAD

**Issue by vikrantmalla** [flutter/flutter#47071] opened 2019-12-15 07:17 UTC
[flutter_01.log](https://github.com/flutter/flutter/files/3964688/flutter_01.log)

**Comment by JerryMatera** [comment] 2019-12-15 08:11
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor --android-licenses

## exception

ProcessException: ProcessException: The system cannot find the file specified.

  Command: C:\Users\admin\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --version

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:368:50)
#5      AndroidSdk.sdkManagerVersion (package:flutter_tools/src/android/android_sdk.dart:595:43)
#6      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:314:64)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:243:38)
#8      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version
    6.3.9600], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (4 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.40.2)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and
      ANDROID_HOME environment variable:
      C:\Users\admin\AppData\Local\Android\sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
      #1      getAdbDevices
      (package:flutter_tools/src/android/android_device.dart:731:5)
      #2      AndroidDevices.pollingGetDevices
      (package:flutter_tools/src/android/android_device.dart:65:53)
      #3      PollingDeviceDiscovery.devices
      (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices
      (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate
      (package:flutter_tools/src/doctor.dart:851:54)
      #6      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start
      (dart:async-patch/async_patch.dart:45:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     _doctorText.<anonymous closure>
      (package:flutter_tools/runner.dart:205:26)
      #17     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:146:29)
      #18     _AsyncAwaitCompleter.start
      (dart:async-patch/async_patch.dart:45:6)
      #19     AppContext.run.<anonymous closure>
      (package:flutter_tools/src/base/context.dart:146:7)
      #20     _rootRun (dart:async/zone.dart:1126:13)
      #21     _CustomZone.run (dart:async/zone.dart:1023:19)
      #22     _runZoned (dart:async/zone.dart:1518:10)
      #23     runZoned (dart:async/zone.dart:1465:12)
      #24     AppContext.run
      (package:flutter_tools/src/base/context.dart:145:18)
      #25     _AsyncAwaitCompleter.start
      (dart:async-patch/async_patch.dart:45:6)
      #26     AppContext.run
      (package:flutter_tools/src/base/context.dart:132:19)
      #27     _doctorText (package:flutter_tools/runner.dart:204:19)
      #28     _AsyncAwaitCompleter.start
      (dart:async-patch/async_patch.dart:45:6)
      #29     _doctorText (package:flutter_tools/runner.dart:200:27)
      #30     _createLocalCrashReport (package:flutter_tools/runner.dart:182:32)
      #31     _AsyncAwaitCompleter.start
      (dart:async-patch/async_patch.dart:45:6)
      #32     _createLocalCrashReport (package:flutter_tools/runner.dart:167:37)
      #33     _handleToolError (package:flutter_tools/runner.dart:138:31)
      #34     _asyncThenWrapperHelper.<anonymous closure>
      (dart:async-patch/async_patch.dart:73:64)
      #35     _rootRunUnary (dart:async/zone.dart:1134:38)
      #36     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #37     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #38     Future._propagateToListeners.handleValueCallback
      (dart:async/future_impl.dart:680:45)
      #39     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #40     Future._completeWithValue (dart:async/future_impl.dart:524:5)
      #41     _AsyncAwaitCompleter.complete
      (dart:async-patch/async_patch.dart:32:15)
      #42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
      #43     CrashReportSender.sendReport
      (package:flutter_tools/src/reporting/crash_reporting.dart)
      #44     _asyncThenWrapperHelper.<anonymous closure>
      (dart:async-patch/async_patch.dart:73:64)
      #45     _rootRunUnary (dart:async/zone.dart:1134:38)
      #46     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #47     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #48     Future._propagateToListeners.handleValueCallback
      (dart:async/future_impl.dart:680:45)
      #49     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #50     Future._complete (dart:async/future_impl.dart:514:7)
      #51     Stream.fold.<anonymous closure> (dart:async/stream.dart:805:18)
      #52     _rootRun (dart:async/zone.dart:1122:38)
      #53     _CustomZone.run (dart:async/zone.dart:1023:19)
      #54     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #55     _BufferingStreamSubscription._sendDone.sendDone
      (dart:async/stream_impl.dart:391:13)
      #56     _BufferingStreamSubscription._sendDone
      (dart:async/stream_impl.dart:401:15)
      #57     _BufferingStreamSubscription._close
      (dart:async/stream_impl.dart:285:7)
      #58     _SinkTransformerStreamSubscription._close
      (dart:async/stream_transformers.dart:98:11)
      #59     _EventSinkWrapper.close
      (dart:async/stream_transformers.dart:25:11)
      #60     _StringAdapterSink.close
      (dart:convert/string_conversion.dart:251:11)
      #61     _Utf8ConversionSink.close
      (dart:convert/string_conversion.dart:302:20)
      #62     _ConverterStreamEventSink.close
      (dart:convert/chunked_conversion.dart:82:18)
      #63     _SinkTransformerStreamSubscription._handleDone
      (dart:async/stream_transformers.dart:143:24)
      #64     _rootRun (dart:async/zone.dart:1122:38)
      #65     _CustomZone.run (dart:async/zone.dart:1023:19)
      #66     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #67     _BufferingStreamSubscription._sendDone.sendDone
      (dart:async/stream_impl.dart:391:13)
      #68     _BufferingStreamSubscription._sendDone
      (dart:async/stream_impl.dart:401:15)
      #69     _BufferingStreamSubscription._close
      (dart:async/stream_impl.dart:285:7)
      #70     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
      #71     _ForwardingStreamSubscription._handleDone
      (dart:async/stream_pipe.dart:174:13)
      #72     _rootRun (dart:async/zone.dart:1122:38)
      #73     _CustomZone.run (dart:async/zone.dart:1023:19)
      #74     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #75     _BufferingStreamSubscription._sendDone.sendDone
      (dart:async/stream_impl.dart:391:13)
      #76     _BufferingStreamSubscription._sendDone
      (dart:async/stream_impl.dart:401:15)
      #77     _BufferingStreamSubscription._close
      (dart:async/stream_impl.dart:285:7)
      #78     _SinkTransformerStreamSubscription._close
      (dart:async/stream_transformers.dart:98:11)
      #79     _EventSinkWrapper.close
      (dart:async/stream_transformers.dart:25:11)
      #80     _Uint8ListConversionSink.close (dart:_http/http_impl.dart:581:13)
      #81     _ConverterStreamEventSink.close
      (dart:convert/chunked_conversion.dart:82:18)
      #82     _SinkTransformerStreamSubscription._handleDone
      (dart:async/stream_transformers.dart:143:24)
      #83     _rootRun (dart:async/zone.dart:1122:38)
      #84     _CustomZone.run (dart:async/zone.dart:1023:19)
      #85     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #86     _BufferingStreamSubscription._sendDone.sendDone
      (dart:async/stream_impl.dart:391:13)
      #87     _BufferingStreamSubscription._sendDone
      (dart:async/stream_impl.dart:401:15)
      #88     _BufferingStreamSubscription._close
      (dart:async/stream_impl.dart:285:7)
      #89     _SinkTransformerStreamSubscription._close
      (dart:async/stream_transformers.dart:98:11)
      #90     _EventSinkWrapper.close
      (dart:async/stream_transformers.dart:25:11)
      #91     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:64:11)
      #92     _FilterSink.close (dart:io/data_transformer.dart:639:11)
      #93     _ConverterStreamEventSink.close
      (dart:convert/chunked_conversion.dart:82:18)
      #94     _SinkTransformerStreamSubscription._handleDone
      (dart:async/stream_transformers.dart:143:24)
      #95     _rootRun (dart:async/zone.dart:1122:38)
      #96     _CustomZone.run (dart:async/zone.dart:1023:19)
      #97     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #98     _BufferingStreamSubscription._sendDone.sendDone
      (dart:async/stream_impl.dart:391:13)
      #99     _BufferingStreamSubscription._sendDone
      (dart:async/stream_impl.dart:401:15)
      #100    _BufferingStreamSubscription._close
      (dart:async/stream_impl.dart:285:7)
      #101    _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
      #102    _ForwardingStreamSubscription._handleDone
      (dart:async/stream_pipe.dart:174:13)
      #103    _rootRun (dart:async/zone.dart:1122:38)
      #104    _CustomZone.run (dart:async/zone.dart:1023:19)
      #105    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #106    _BufferingStreamSubscription._sendDone.sendDone
      (dart:async/stream_impl.dart:391:13)
      #107    _BufferingStreamSubscription._sendDone
      (dart:async/stream_impl.dart:401:15)
      #108    _BufferingStreamSubscription._close
      (dart:async/stream_impl.dart:285:7)
      #109    _SyncStreamControllerDispatch._sendDone
      (dart:async/stream_controller.dart:774:19)
      #110    _StreamController._closeUnchecked
      (dart:async/stream_controller.dart:631:7)
      #111    _StreamController.close (dart:async/stream_controller.dart:624:5)
      #112    _HttpParser._closeIncoming (dart:_http/http_parser.dart:1039:23)
      #113    _HttpParser._doParse (dart:_http/http_parser.dart:754:11)
      #114    _HttpParser._parse (dart:_http/http_parser.dart:320:7)
      #115    _HttpParser._onData (dart:_http/http_parser.dart:812:5)
      #116    _rootRunUnary (dart:async/zone.dart:1134:38)
      #117    _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #118    _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
      #119    _BufferingStreamSubscription._sendData
      (dart:async/stream_impl.dart:338:11)
      #120    _BufferingStreamSubscription._add
      (dart:async/stream_impl.dart:265:7)
      #121    _SyncStreamControllerDispatch._sendData
      (dart:async/stream_controller.dart:766:19)
      #122    _StreamController._add (dart:async/stream_controller.dart:642:7)
      #123    _StreamController.add (dart:async/stream_controller.dart:588:5)
      #124    _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
      #125    _rootRunUnary (dart:async/zone.dart:1134:38)
      #126    _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #127    _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
      #128    _BufferingStreamSubscription._sendData
      (dart:async/stream_impl.dart:338:11)
      #129    _BufferingStreamSubscription._add
      (dart:async/stream_impl.dart:265:7)
      #130    _SyncStreamControllerDispatch._sendData
      (dart:async/stream_controller.dart:766:19)
      #131    _StreamController._add (dart:async/stream_controller.dart:642:7)
      #132    _StreamController.add (dart:async/stream_controller.dart:588:5)
      #133    _RawSecureSocket._sendReadEvent
      (dart:io/secure_socket.dart:1018:19)
      #134    _rootRun (dart:async/zone.dart:1122:38)
      #135    _CustomZone.run (dart:async/zone.dart:1023:19)
      #136    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #137    _CustomZone.bindCallbackGuarded.<anonymous closure>
      (dart:async/zone.dart:965:23)
      #138    _rootRun (dart:async/zone.dart:1126:13)
      #139    _CustomZone.run (dart:async/zone.dart:1023:19)
      #140    _CustomZone.bindCallback.<anonymous closure>
      (dart:async/zone.dart:949:23)
      #141    Timer._createTimer.<anonymous closure>
      (dart:async-patch/timer_patch.dart:23:15)
      #142    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
      #143    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
      #144    _RawReceivePortImpl._handleMessage
      (dart:isolate-patch/isolate_patch.dart:174:12)


! Doctor found issues in 2 categories.
```

**Comment by JerryMatera** [comment] 2019-12-15 08:13
@vikrantmalla That's your log file. I'm having almost the same issue share your solution if you find any

**Comment by iapicca** [comment] 2019-12-16 08:51
possibly related to https://github.com/flutter/flutter/issues/46938

**Comment by christopherfujino** [comment] 2020-03-04 23:22
@vikrantmalla and @JerryMatera it looks like either the tool thinks your Android SDK is in a location it isn't, or your Android SDK install is missing files. Can you verify if you actually have the Android SDK installed at the location the doctor thinks it is?

**Comment by JerryMatera** [comment] 2020-03-07 12:22
@christopherfujino Where does flutter doctor thinks it is. I also do native android development and i know i have Android SDK installed

**Comment by iapicca** [comment] 2020-03-09 12:32
Hi @vikrantmalla 
does the proposed solution in this [issue](https://github.com/flutter/flutter/issues/51712)
solve the problem?
Thank you

**Comment by christopherfujino** [comment] 2020-03-09 17:50
@JerryMatera `flutter doctor` will tell you where it thinks it is, with a line **like**:

`    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk`

**Comment by sandy9808** [comment] 2020-03-26 19:16
hey bro @vikrantmalla  is the issue solved?

**Comment by sandy9808** [comment] 2020-03-26 20:34
can anybody solve this issue please..
I am having the same exact problem.

**Comment by christopherfujino** [comment] 2020-03-26 21:40
@sandy9808 see my comment https://github.com/flutter/flutter/issues/47071#issuecomment-594927182 - we'll need more information in order to determine the cause of the issue.

**Comment by sandy9808** [comment] 2020-03-26 22:37
Well Hurry up! I have to do a lot of fluttering in this quarintine.

**Comment by sandy9808** [comment] 2020-03-26 23:38
**command:**
flutter doctor --android-licenses

**output:**
C:\Users\user>flutter doctor --android-licenses
'git rev-parse HEAD' is not recognized as an internal or external command,
operable program or batch file.
Building flutter tool...
Running pub upgrade...
'dir /a:l "C:\realflutter\flutter\bin\cache\dart-sdk\" 2>nul   | find ">     bin [" 2>nul' is not recognized as an internal or external command,
operable program or batch file.
CreateProcessW failed 2

Sending crash report to Google.
Crash report sent (report ID: 557252744ea32c2d)
Oops; flutter has exited unexpectedly.
\CreateProcessW failed 2
Crash report written to C:\Users\user\flutter_20.log;
please let us know at https://github.com/flutter/flutter/issues.

**the text in the log file is:**
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor --android-licenses

## exception

ProcessException: ProcessException: The system cannot find the file specified.

  Command: C:\Users\user\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --version

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:368:50)
#5      AndroidSdk.sdkManagerVersion (package:flutter_tools/src/android/android_sdk.dart:595:43)
#6      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:314:64)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:243:38)
#8      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at C:\realflutter\flutter
    [32m•[39m Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at C:\Users\user\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-R, build-tools 29.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    [31m✗[39m Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[32m[✓][39m Android Studio (version 3.6)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 44.0.2
    [32m•[39m Dart plugin version 192.7761
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[32m[✓][39m VS Code (version 1.43.2)
    [32m•[39m VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.8.1

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 2 categories.
```
And P.S don't try to give me any link to other issues.
I have tried nearly all of them.

**Comment by christopherfujino** [comment] 2020-03-30 21:24
@sandrasandeep do you have git installed and on your user path? I see `'git rev-parse HEAD' is not recognized as an internal or external command,`

**Comment by sandy9808** [comment] 2020-03-30 21:30
Yes Sir, I do have git installed in my computer(windows 10)

**Comment by sandy9808** [comment] 2020-03-31 00:39
'git rev-parse HEAD' is not recognized as an internal or external command, I HAVE CLEARED THIS ERROR.

**Comment by christopherfujino** [comment] 2020-03-31 00:40
> 'git rev-parse HEAD' is not recognized as an internal or external command, I HAVE CLEARED THIS ERROR.

I'm sorry, but can you clarify? What do you mean by "cleared this error"?

**Comment by sandy9808** [comment] 2020-03-31 00:42
$ flutter doctor --android-licenses --verbose
CreateProcessW failed 2
Android sdkmanager tool was found, but failed to run (C:\Users\user\AppData\Local\Android\Sdk\tools\bin\sdkmanager): "ProcessException: The system cannot find the file specified.

  Command: C:\Users\user\AppData\Local\Android\Sdk\tools\bin\sdkmanager.BAT --licenses".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/setup/#android-setup for detailed instructions.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:394:7)
<asynchronous suspension>
#2      Doctor.diagnose (package:flutter_tools/src/doctor.dart:262:38)
#3      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:58:39)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:711:18)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
I mean that no more "git rev-parse HEAD' is not recognized as an internal or external command"
is written anymore in the output of command.

**Comment by sandy9808** [comment] 2020-03-31 00:44
My version of flutter is:
### flutter --version
Flutter 1.15.17 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2294d75bfa (3 weeks ago) • 2020-03-07 00:28:38 +0900
Engine • revision 5aff311948
Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

**Comment by christopherfujino** [comment] 2020-03-31 19:06
I am closing this issue as a duplicate of https://github.com/flutter/flutter/issues/51712. The current status is contained in this comment https://github.com/flutter/flutter/issues/51712#issuecomment-601863075.

**Comment by sandy9808** [comment] 2020-03-31 23:12
so it is a work in progress i guess.

**Comment by christopherfujino** [comment] 2020-03-31 23:45
@sandrasandeep per https://github.com/flutter/flutter/pull/51980#issuecomment-606152832, the fix is in v1.15.12, which is on the beta channel, so you can either switch to the beta channel, or do the workaround specified on the linked issue.

**Comment by sandy9808** [comment] 2020-04-01 01:28
@christopherfujino but i am using ths version 

flutter --version
Flutter 1.15.17 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2294d75 (3 weeks ago) • 2020-03-07 00:28:38 +0900
Engine • revision 5aff311948
Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
So,it should work right.

**Comment by christopherfujino** [comment] 2020-04-01 23:10
> @christopherfujino but i am using ths version
> 
> flutter --version
> Flutter 1.15.17 • channel beta • https://github.com/flutter/flutter.git
> Framework • revision [2294d75](https://github.com/flutter/flutter/commit/2294d75bfa8d067ba90230c0fc2268f3636d7584) (3 weeks ago) • 2020-03-07 00:28:38 +0900
> Engine • revision 5aff311948
> Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)
> So,it should work right.

Hmm, good point...

**Comment by sandy9808** [comment] 2020-04-02 00:47
@christopherfujino  do you need more information?

**Comment by codermihirpaldhikar** [comment] 2020-04-05 08:17
Hi @vikrantmalla, I checked out your logs. As per the exception thrown by the flutter doctor, it says sdkmanager.bat not found.  The sdkmanager is a command-line tool that allows you to view, install, update, and uninstall packages for the Android SDK. As per the exception, sdkmanager file is missing. I suggest try to reinstall the SDK and before that, you should also check the sdkmanager if already exist in the path android_sdk/tools/bin/

let me know if you need any help
Happy Coding!!

**Comment by sandy9808** [comment] 2020-04-05 08:26
sdkmanager.bat is present in tools/bin folder.
And reinstalling the sdk means what?

**Comment by codermihirpaldhikar** [comment] 2020-04-05 08:43
HI @sandy9808 reinstalling the SDK means to again install whole Android SDK either by reinstalling the Android Studio or by the CLI by downloading sdkmanager from https://developer.android.com/studio under sub-section named "Command line tools only"

**Comment by nihalsarwar17** [comment] 2020-10-06 19:39
g=me tumse pyaar krta hun

**Closed** 2020-12-29 03:57 UTC
Labels: P4, severe: crash, t: flutter doctor, tool
