### ISSUE TITLE
Could not open settings generic class cache for settings file 'C:\flutterproject\barcode_scanner\android\settings.gradle' (C:\.gradle\caches\6.7\scripts\1fnwrr8g4rohfp291nvlxj5qe).

### ISSUE THREAD

**Issue by danieluac** [flutter/flutter#81636] opened 2021-05-02 06:59 UTC
FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'C:\flutterproject\barcode_scanner\android\settings.gradle' (C:\.gradle\caches\6.7\scripts\1fnwrr8g4rohfp291nvlxj5qe).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 60

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

**Comment by pedromassangocode** [comment] 2021-05-03 09:09
Hi @danieluac 
This issue seems to be caused by the [barcode_scanner](https://pub.dev/packages/barcode_scanner) package, if that is true then please file an issue in is appropriated repository. Otherwise, please provide the steps to reproduce this issue (without third-party packages).

Thank you

**Comment by TahaTesser** [comment] 2021-05-27 12:43
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-05-27 12:43 UTC

**Comment by uzaif-lab** [comment] 2021-06-08 15:14
Yes same issue happen when i connect my android emulator with vs code and run the program but if run same program with chrome that works perfectly fine what to do??
