### ISSUE TITLE
flutter update-packages --force-upgrade failed

### ISSUE THREAD

**Issue by realcarlos** [flutter/flutter#15237] opened 2018-03-07 09:57 UTC
Upgrading packages...
Running "flutter packages upgrade" in flutter_update_packages_qQnlPY...      
! analyzer 0.31.2-alpha.0 from path /Users/xxx/Documents/GitHub/flutter/packages/flutter_tools/../../bin/cache/dart-sdk/lib/analyzer
! front_end 0.1.0-alpha.10 from path /Users/xxx/Documents/GitHub/flutter/packages/flutter_tools/../../bin/cache/dart-sdk/lib/front_end
! kernel 0.3.0-alpha.10 from path /Users/xxx/Documents/GitHub/flutter/packages/flutter_tools/../../bin/cache/dart-sdk/lib/kernel
Running "flutter packages get" in bots...                    0.6s
Running "flutter packages get" in vitool...                  0.6s
Running "flutter packages get" in tools...                   0.6s
Running "flutter packages get" in ui...                      0.6s
Running "flutter packages get" in external_ui...             0.6s
Running "flutter packages get" in flavors...                 0.6s
Running "flutter packages get" in platform_interaction...    0.6s
Running "flutter packages get" in channels...                0.6s
Running "flutter packages get" in manual_tests...            0.6s
Running "flutter packages get" in devicelab...               0.6s
Running "flutter packages get" in complex_layout...          0.7s
Running "flutter packages get" in microbenchmarks...             
Package intl_translation has no versions that match 0.16.1 derived from:
- microbenchmarks depends on version 0.16.1
pub get failed (1)

**Comment by jason-simmons** [comment] 2018-03-08 21:46
intl_translation has a constraint on `analyzer: '>=0.29.1 <0.31.0'` which does not allow the latest version of the `analyzer` package

Duplicate of https://github.com/flutter/flutter/issues/15261

**Closed by jason-simmons** 2018-03-08 21:46 UTC
