### ISSUE TITLE
App doesn't launch after upgrading to Android SDK 33

### ISSUE THREAD

**Issue by josh-burton** [flutter/flutter#109963] opened 2022-08-21 22:24 UTC
## Steps to Reproduce

- update Android targetSdkVersion to 33
- Attempt to run the app

The app fails to launch with 'Activity class not found' error.

This is a duplicate of issue #105764 which has been closed because the issue mentions that the problem is fixed in the master channel. 

As Android 13 has launched to stable now, Flutter is in a state where an app cannot be run on the latest version of Anrdoid, and I believe this should be hotfixed to stable.

**Comment by exaby73** [comment] 2022-08-22 12:05
Hello @josh-burton. Thank you for filing this request. I can confirm that currently, on stable, Flutter doesn't not launch on API 33. Below you will find the logs for the issue at hand. 

To reproduce, set the `compileSdkVersion` and `targetSdkVersion` to 33 in `android/app/build.gradle`, then run `flutter run`.

#### Error logs (sippet of running `flutter run -v`)

```
[ +307 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.issue_109963/.MainActivity (has extras) }

           Error type 3
           Error: Activity class {com.example.issue_109963/com.example.issue_109963.MainActivity} does not exist.
```

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.856], locale en-IN)
    • Flutter version 3.0.5 at C:\Users\Nabeel Parkar\fvm\versions\stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.2
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3739.24

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\Nabeel Parkar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.2403, on Microsoft Windows [Version 10.0.22000.856], locale en-IN)
    • Flutter version 3.1.0-0.0.pre.2403 on channel master at C:\Users\Nabeel Parkar\fvm\versions\master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a10c921aba (3 hours ago), 2022-08-21 23:44:38 -0400
    • Engine revision d311584c79
    • Dart version 2.19.0 (build 2.19.0-120.0.dev)
    • DevTools version 2.16.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\android-sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.2
    • Flutter plugin version 69.0.5
    • Dart plugin version 222.3739.24

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\Nabeel Parkar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.856]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 104.0.1293.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

cc: @blasten for further details on cherry-picking this issue.

**Comment by exaby73** [comment] 2022-08-22 13:21
An update to this issue. Cherry-pick issue is raised here: https://github.com/flutter/flutter/issues/109964

**Comment by stuartmorgan** [comment] 2022-08-23 17:33
Does this work on the current `beta`?

**Comment by josh-burton** [comment] 2022-08-23 20:02
> Does this work on the current `beta`?

Yes it works on the current beta channel (`3.3.0-0.5.pre`)

**Comment by jack24254029** [comment] 2022-08-24 07:38
When the progress bar of installing flutter apk gone, you can open the app by yourself.
It seems work fine like launch app by IDE

**Comment by stuartmorgan** [comment] 2022-08-30 17:16
Closing as a duplicate of https://github.com/flutter/flutter/issues/109964

**Closed by stuartmorgan** 2022-08-30 17:16 UTC
Labels: severe: crash, platform-android, tool, e: OS Version specific, has reproducible steps, severe: fatal crash, r: duplicate, found in release: 3.0
