### ISSUE TITLE
cupertino backdrop filter / alert dialog wrong on web

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#55928] opened 2020-04-29 03:08 UTC
The dialog shows up with the discard button wrong.  I think that's just a bug with backdrop filter, since the backdrop filter is also missing.  @ferhatb fixed a bug a few days back, so possibly this is just a dupe of that: https://github.com/flutter/flutter/issues/54871

![image](https://user-images.githubusercontent.com/11857803/80557476-e4c81a00-898b-11ea-8ad1-a4eaedf543be.png)

**Comment by yjbanov** [comment] 2020-04-29 22:17
This is a duplicate of https://github.com/flutter/flutter/issues/49877.

**Closed by yjbanov** 2020-04-29 22:17 UTC
Labels: f: cupertino, framework, platform-web, severe: rendering
