### ISSUE TITLE
How to delete the NOTICES file generated by flutter packaging apk

### ISSUE THREAD

**Issue by 132056135** [flutter/flutter#88417] opened 2021-08-18 07:57 UTC
1.flutter 打包apk时 生成的NOTICES文件 怎么删除 因为要过移动信息安全等保等级 生成的NOTICES有很多url 会被检测出来 2.混淆问题 minifyEnabled true 、proguard-rules.pro也设置好了，打包release版本后安装时出现闪退 这个是什么原因啊

Translation:

1. How to delete the NOTICES file generated when flutter is packaging the apk. Because the NOTICES generated by mobile information security has many URLs, it will be detected. 2. Confusion issues minifyEnabled true and proguard-rules.pro are also set, and the release is packaged What is the reason for the crash when installing after the version?

**Comment by darshankawar** [comment] 2021-08-18 09:13
@132056135 
Your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here, as this is a `how to` question and not a bug or feature request.

**Closed by darshankawar** 2021-08-18 09:13 UTC
Labels: in triage
