### ISSUE TITLE
[web]: Refreshing TextField makes findRenderObject null 

### ISSUE THREAD

**Issue by davidcavazos** [flutter/flutter#42201] opened 2019-10-08 01:32 UTC
Hi team, while testing forms and form inputs from the [Build a form with validation](https://flutter.dev/docs/cookbook/forms/validation) guide, I noticed some errors when using `TextFormField`. Digging more into the issue, it seems to be an issue with `TextField`. I managed to simplify the error it to the following program:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
      title: 'TextField error',
      home: Scaffold(
        appBar: AppBar(title: Text('TextField error')),
        body: TextField(),
      ),
    ));
```

If I run it with `flutter run -d chrome -v`, it compiles and renders correctly. If I do nothing but refresh, it refreshes correctly with the following message:

```
[+6591 ms] Performing hot restart...
[ +543 ms] About to build [web]...
[        ] Running build...
[  +77 ms] Running build completed, took 36ms

[        ] Caching finalized dependency graph...
[   +2 ms] Caching finalized dependency graph completed, took 43ms

[   +1 ms] Succeeded after 82ms with 0 outputs (0 actions)

[  +57 ms] Restarted application in 681ms.
[        ] Performing hot restart... (completed in 682ms)
```

If I just *click* on the `TextField` (or edit the value) and then refresh, I get the following error:

```
[        ] Performing hot restart... (completed in 499ms)
[ +496 ms] ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
[        ] The following JSNoSuchMethodError was thrown while notifying listeners for AnimationController:
[        ] NoSuchMethodError: invalid member on null: 'findRenderObject'
[   +4 ms] When the exception was thrown, this was the stack:
[        ] package:flutter/src/widgets/editable_text.dart 1726:68            get renderEditable
[        ] package:flutter/src/widgets/editable_text.dart 1590:20            [_onCursorColorTick]
[        ] package:flutter/src/animation/listener_helpers.dart 124:21        notifyListeners
[        ] package:flutter/src/animation/animation_controller.dart 362:5     set value
[        ] package:flutter/src/widgets/editable_text.dart 1625:37            [_cursorTick]
[        ] package:build_web_compilers/src/dev_compiler/dart_sdk.js 28721:9  <fn>
[        ] The AnimationController notifying listeners was:
[        ] AnimationController#798f1(⏮ 0.000; paused)
[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +349 ms] Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
[ +552 ms] Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
[ +522 ms] Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
[ +495 ms] Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
[ +429 ms] Another exception was thrown: NoSuchMethodError: invalid member on null: 'findRenderObject'
....
```

And it just keeps going until I do a *hard refresh* on Chrome for the entire page.

[Reference app](https://github.com/davidcavazos/flutter-issues/tree/master/textfield_refresh)

**Comment by davidcavazos** [comment] 2019-10-08 01:32
```
> flutter doctor -v       
[✓] Flutter (Channel master, v1.10.14-pre.12, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.14-pre.12 at /Users/dcavazos/local/flutter
    • Framework revision cdc2d9901d (2 hours ago), 2019-10-07 16:43:04 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dcavazos/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.8.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6262.58

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (2 available)
    • Chrome          • chrome          • web-javascript • Google Chrome 77.0.3865.90
    • Headless Server • headless-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by mikhail-tokarev** [comment] 2019-10-08 10:22
Hi @davidcavazos 
can you please post a self contained app on github to better address the issue,
thank you

**Comment by davidcavazos** [comment] 2019-10-08 17:06
Sure thing, [here it is](https://github.com/davidcavazos/flutter-issues/tree/master/textfield_refresh).

**Comment by nturgut** [comment] 2019-10-10 16:49
duplicate of #41284

**Closed by nturgut** 2019-10-10 16:49 UTC
Labels: ☸ platform-web
