### ISSUE TITLE
Flutter`skia::textlayout::Run::calculateWidth(unsigned long, unsigned long, bool) const + 72

### ISSUE THREAD

**Issue by smileKH** [flutter/flutter#107529] opened 2022-07-13 10:44 UTC
## Steps to Reproduce

1. Execute flutter run on the code sample

**Expected results:** 
Text can be displayed normally
![1201657708152_ pic_hd](https://user-images.githubusercontent.com/15364507/178715391-c418afca-f7e5-40d2-8e28-b6b4bf093720.jpg)

**Actual results:** 
APP flash back, is a must
Note
This is true on iOS and Android
Will now
Flash back information
```
thread https://github.com/flutter/flutter/pull/10, name = 'io.flutter.1.ui', stop reason = EXC_BAD_ACCESS (code=1, address=0x2c6292ea8)
frame #0: 0x000000010514df8c Flutterskia::textlayout::Run::calculateWidth(unsigned long, unsigned long, bool) const + 72 Flutterskia::textlayout::Run::calculateWidth:
-> 0x10514df8c <+72>: ldr s1, [x8, x9]
0x10514df90 <+76>: sbfiz x9, x1, https://github.com/flutter/flutter/pull/3, https://github.com/flutter/flutter/pull/32
0x10514df94 <+80>: ldr s2, [x8, x9]
0x10514df98 <+84>: fsub s1, s1, s2
Target 0: (Runner) stopped.
```

<details>
<summary>Code sample</summary>

```
import 'package:flutter/material.dart';

void main() {
runApp(const MyApp());
}

class MyApp extends StatelessWidget {
const MyApp({Key? key}) : super(key: key);

// This widget is the root of your application.
@OverRide
Widget build(BuildContext context) {
return MaterialApp(
title: 'Flutter Demo',
theme: ThemeData(
primarySwatch: Colors.blue,
),
home: const MyHomePage(title: 'Flutter Demo Home Page'),
);
}
}

class MyHomePage extends StatefulWidget {
const MyHomePage({Key? key, required this.title}) : super(key: key);

final String title;

@OverRide
State createState() => _MyHomePageState();
}

class _MyHomePageState extends State {
@OverRide
Widget build(BuildContext context) {
return Scaffold(
appBar: AppBar(
title: Text(widget.title),
),
body: Center(
child: Column(
mainAxisAlignment: MainAxisAlignment.center,
children: const [
Text('(๑•॒̀ ູ॒•́๑)啦啦啦'),
],
),
), // This trailing comma makes auto-formatting nicer for build methods.
);
}
}
```

</details>

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.3 20E217 darwin-arm, locale zh-Hans-CN)
• Flutter version 3.0.1 at /Applications/flutter_3.0.1
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision https://github.com/flutter/flutter/commit/fb57da5f945d02ef4f98dfd9409a72b7cce74268 (8 weeks ago), 2022-05-19 15:50:29 -0700
• Engine revision caaafc5604
• Dart version 2.17.1
• DevTools version 2.12.2
• Pub download mirror https://pub.dartlang.org/
• Flutter download mirror https://storage.flutter-io.cn/

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
• Android SDK at /Users/mxmac/Library/Android/sdk
• Platform android-32, build-tools 32.1.0-rc1
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
• Xcode at /Applications/Xcode.app/Contents/Developer
• CocoaPods version 1.11.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (3 available)
• iPhone胡明波 (mobile) • 00008101-0005784E3C89001E • ios • iOS 14.6 18F72
• macOS (desktop) • macos • darwin-arm64 • macOS 11.3 20E217 darwin-arm
• Chrome (web) • chrome • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
• All required HTTP hosts are available

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2022-07-13 11:00
Hi @smileKH, please refrain from filing multiple issues to report the same bug. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/107509

**Closed by danagbemava-nc** 2022-07-13 11:00 UTC
Labels: in triage
