### ISSUE TITLE
TextCapitalization words falls back to capitals when resetting the focus

### ISSUE THREAD

**Issue by remonh87** [flutter/flutter#39567] opened 2019-08-30 13:02 UTC
## Steps to Reproduce

Create following app: 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text("Test"),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              TextField(
                textCapitalization: TextCapitalization.words,
              ),
              TextField(),
            ],
          ),
        ),
      ),
    );
  }
}
```

1. Start app on a Samsung device reproduced it myself on: Samsung j7, samsung galaxy note8, samsung galaxy s10
2. Select top textfield and enter some string e.g. Test
3. Tap lower textfield and enter some value
4. Set focus back to textfield and notice that text input is capital again (see screen). This isn't the case for other devices like a Google Pixel (that device has the correct behavior).
https://user-images.githubusercontent.com/48603081/81196993-60097b80-8fdd-11ea-9c8c-9181c88738b2.png

<img src="https://user-images.githubusercontent.com/20230599/64022508-b8c37300-cb36-11e9-985c-2a4b251eeabf.jpg" width="300" height="550" />

## Logs
```
[   +1 ms] Syncing files to device SM N950F... (completed in 1,471ms)
[        ] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +5 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x76ed2b6220, isolate: {type: @Isolate, fixedId: true, id: isolates/480747230, name: main.dart$main-480747230, number: 480747230}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x76ed2b6220.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on SM N950F is available at: http://127.0.0.1:54777/ey3QFCjkGww=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+6983 ms] D/ViewRootImpl@ece0549[MainActivity](19114): ViewPostIme pointer 0
[  +87 ms] D/ViewRootImpl@ece0549[MainActivity](19114): ViewPostIme pointer 1
[ +162 ms] D/InputMethodManager(19114): SSI - flag : 0 Pid : 19114 view : com.example.test_app_capatalisation
[   +2 ms] D/InputMethodManager(19114): prepareNavigationBarInfo() DecorView@f40c511[MainActivity]
[        ] D/InputMethodManager(19114): getNavigationBarColor() -855310
[        ] V/InputMethodManager(19114): Starting input: tba=com.example.test_app_capatalisation ic=io.flutter.plugin.editing.InputConnectionAdaptor@7421ff1 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
[        ] D/InputMethodManager(19114): startInputInner - Id : 0
[        ] I/InputMethodManager(19114): startInputInner - mService.startInputOrWindowGainedFocus
[   +2 ms] D/InputTransport(19114): Input channel constructed: fd=106
[        ] D/InputTransport(19114): Input channel destroyed: fd=95
[        ] D/InputMethodManager(19114): prepareNavigationBarInfo() DecorView@f40c511[MainActivity]
[        ] D/InputMethodManager(19114): getNavigationBarColor() -855310
[  +81 ms] D/ViewRootImpl@ece0549[MainActivity](19114): MSG_RESIZED: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 963) vi=Rect(0, 63 - 0, 963) or=1
[  +25 ms] D/ViewRootImpl@ece0549[MainActivity](19114): Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=true 510266732544} changed=false
[+3853 ms] D/ViewRootImpl@ece0549[MainActivity](19114): ViewPostIme pointer 0
[  +64 ms] D/ViewRootImpl@ece0549[MainActivity](19114): ViewPostIme pointer 1
[  +26 ms] D/InputMethodManager(19114): prepareNavigationBarInfo() DecorView@f40c511[MainActivity]
[        ] D/InputMethodManager(19114): getNavigationBarColor() -855310
[        ] V/InputMethodManager(19114): Starting input: tba=com.example.test_app_capatalisation ic=io.flutter.plugin.editing.InputConnectionAdaptor@db42a57 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
[        ] D/InputMethodManager(19114): startInputInner - Id : 0
[   +3 ms] I/InputMethodManager(19114): startInputInner - mService.startInputOrWindowGainedFocus
[   +7 ms] D/InputTransport(19114): Input channel constructed: fd=104
[        ] D/InputTransport(19114): Input channel destroyed: fd=106
[        ] D/InputMethodManager(19114): SSI - flag : 0 Pid : 19114 view : com.example.test_app_capatalisation
[        ] D/InputMethodManager(19114): prepareNavigationBarInfo() DecorView@f40c511[MainActivity]
[        ] D/InputMethodManager(19114): getNavigationBarColor() -855310
[+2572 ms] D/ViewRootImpl@ece0549[MainActivity](19114): ViewPostIme pointer 0
[  +71 ms] D/ViewRootImpl@ece0549[MainActivity](19114): ViewPostIme pointer 1
[  +23 ms] D/InputMethodManager(19114): prepareNavigationBarInfo() DecorView@f40c511[MainActivity]
[        ] D/InputMethodManager(19114): getNavigationBarColor() -855310
[        ] V/InputMethodManager(19114): Starting input: tba=com.example.test_app_capatalisation ic=io.flutter.plugin.editing.InputConnectionAdaptor@85511e5 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
[        ] D/InputMethodManager(19114): startInputInner - Id : 0
[   +3 ms] I/InputMethodManager(19114): startInputInner - mService.startInputOrWindowGainedFocus
[   +6 ms] D/InputTransport(19114): Input channel constructed: fd=106
[        ] D/InputTransport(19114): Input channel destroyed: fd=104
[   +3 ms] D/InputMethodManager(19114): SSI - flag : 0 Pid : 19114 view : com.example.test_app_capatalisation
[        ] D/InputMethodManager(19114): prepareNavigationBarInfo() DecorView@f40c511[MainActivity]
[        ] D/InputMethodManager(19114): getNavigationBarColor() -855310
[+1921 ms] D/ViewRootImpl@ece0549[MainActivity](19114): ViewPostIme pointer 0
[  +52 ms] D/ViewRootImpl@ece0549[MainActivity](19114): ViewPostIme pointer 1
[  +25 ms] D/InputMethodManager(19114): prepareNavigationBarInfo() DecorView@f40c511[MainActivity]
[        ] D/InputMethodManager(19114): getNavigationBarColor() -855310
[        ] V/InputMethodManager(19114): Starting input: tba=com.example.test_app_capatalisation ic=io.flutter.plugin.editing.InputConnectionAdaptor@949e761 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
[        ] D/InputMethodManager(19114): startInputInner - Id : 0
[   +4 ms] I/InputMethodManager(19114): startInputInner - mService.startInputOrWindowGainedFocus
[   +3 ms] D/InputTransport(19114): Input channel constructed: fd=95
[        ] D/InputTransport(19114): Input channel destroyed: fd=106
[   +5 ms] D/InputMethodManager(19114): SSI - flag : 0 Pid : 19114 view : com.example.test_app_capatalisation
[        ] D/InputMethodManager(19114): prepareNavigationBarInfo() DecorView@f40c511[MainActivity]
[        ] D/InputMethodManager(19114): getNavigationBarColor() -855310

```

Flutter doctor output
```
[✓] Flutter (Channel unknown, v1.7.8+hotfix.3, on Mac OS X 10.14.6 18G87, locale en-NL)
    • Flutter version 1.7.8+hotfix.3 at /Users/user/dev/flutter
    • Framework revision b712a172f9 (7 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.5 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6459

[✓] VS Code (version 1.28.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.15.0

[✓] Connected device (3 available)
    • SM N950F • 123456 • android-arm64  • Android 9 (API 28)
    • macOS    • macOS                • darwin-x64     • Mac OS X 10.14.6 18G87
    • web      • web                  • web-javascript • Google Chrome 76.0.3809.132
```

**Comment by remonh87** [comment] 2019-08-30 13:03
Can be related to #38876

**Comment by TahaTesser** [comment] 2020-05-06 15:37
Testing tje code sample, i was able to reproduce this on issue on `stable` channel but no issue on `dev` channel


![flutter_05](https://user-images.githubusercontent.com/48603081/81196993-60097b80-8fdd-11ea-9c8c-9181c88738b2.png)

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Users/tahatesser/Code/flutter_stable
    • Framework revision e6b34c2b5c (4 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

 
[✓] Connected device (1 available)            
    • SM M305F • 32003c30dc19668f • android-arm64 • Android 10 (API 29)

• No issues found!
``` 

</details>

**Comment by TahaTesser** [comment] 2020-12-30 13:31
Doesn't reproduce on Realme device (as expected) 

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.156, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.156 at /Users/tahatesser/Code/flutter_master
    • Framework revision e7e7bb2ef5 (8 hours ago), 2020-12-29 23:44:01 -0500
    • Engine revision d3a0669458
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-03-12 12:06
I check this on `Galaxy Tab A7 Lite (Android 14)` but can't reproduce the issue on the latest Flutter master channel. @remonh87 Could you please retry this on the latest Flutter stable/master channels? Thanks!

**Comment by darshankawar** [comment] 2024-03-14 12:08
Verified this issue using Samsung S10 galaxy device by running the original code sample and on latest stable (3.19.3) and observed that the reported behavior doesn't occur anymore. See screenshot below:

<img width="285" alt="Screenshot 2024-03-14 at 5 35 45 PM" src="https://github.com/flutter/flutter/assets/67046386/67928f81-107e-4849-baf4-44fe9fbf7871">

This isn't replicable anymore and also based on above comment, I'll optimisitcally close this as resolved. If anybody disagrees, or still sees this as an issue on latest version, write in comments and I'll reopen it or file a new issue.

**Closed by darshankawar** 2024-03-14 12:08 UTC
Labels: a: text input, e: device-specific, waiting for customer response, framework, f: material design, a: quality, has reproducible steps, found in release: 1.17, P2, e: samsung, team-design, triaged-design
