### ISSUE TITLE
Engine roll crashing benchmarks

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#59346] opened 2020-06-12 17:28 UTC
The engine roll here https://github.com/flutter/flutter/pull/59282 reverted here https://github.com/flutter/flutter/pull/59334 caused smoke_catalina_hot_mode_dev_cycle__benchmark and hot_mode_dev_cycle_win__benchmark to segfault during hot reload with:

```
2020-06-11T16:55:00.810412: stdout: [   +1 ms] Performing hot restart...
2020-06-11T16:55:00.818030: stdout: [   +7 ms] Scanned through 574 files in 5ms
2020-06-11T16:55:00.818193: stdout: [        ] Syncing files to device Moto G 4...
stdout: [        ] Scanning asset files
2020-06-11T16:55:00.822897: stdout: [   +4 ms] <- reset
stdout: [        ] Compiling dart to kernel with 0 updated files
2020-06-11T16:55:00.823123: stdout: [        ] <- recompile package:flutter_gallery/main.dart 6a27207d-14e3-42b8-ac61-6f5ba73da67b
stdout: [        ] <- 6a27207d-14e3-42b8-ac61-6f5ba73da67b
2020-06-11T16:55:00.870589: stdout: [  +47 ms] Updating files
2020-06-11T16:55:01.573872: stdout: [ +703 ms] F/libc    (31066): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4302cc in tid 31066 (er.demo.gallery)
2020-06-11T16:55:01.672723: stdout: [  +98 ms] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
stdout: [        ] Build fingerprint: 'motorola/athene/athene:7.0/NPJS25.93-14-8.1-9/4:user/release-keys'
2020-06-11T16:55:01.672828: stdout: [        ] Revision: 'p2a0'
2020-06-11T16:55:01.672927: stdout: [        ] ABI: 'arm'
stdout: [        ] pid: 31066, tid: 31066, name: er.demo.gallery  >>> io.flutter.demo.gallery <<<
2020-06-11T16:55:01.673060: stdout: [        ] signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4302cc
2020-06-11T16:55:01.673181: stdout: [        ]     r0 00430000  r1 bed533cc  r2 00430000  r3 00000000
2020-06-11T16:55:01.673309: stdout: [        ]     r4 a5b62cc0  r5 bed53710  r6 bed534b0  r7 bed53470
stdout: [        ]     r8 bed53710  r9 aca05400  sl aca0548c  fp bed5343c
2020-06-11T16:55:01.673424: stdout: [        ]     ip 943a2f4f  sp bed533c0  lr 94e38679  pc 9439e948  cpsr 600b0030
2020-06-11T16:55:01.673529: stdout: [        ] backtrace:
2020-06-11T16:55:01.673647: stdout: [        ]     #00 pc 00001948  /data/app/io.flutter.demo.gallery-2/lib/arm/libflutter.so (offset 0xfd6000)
2020-06-11T16:55:01.673728: stdout: [        ]     #01 pc 0033f677  /data/app/io.flutter.demo.gallery-2/oat/arm/base.odex (offset 0x326000)
```

@jason-simmons

**Comment by aam** [comment] 2020-06-12 18:12
Tried reproducing the crash on my mac/pixel4 on 1d407de925 on smoke_catalina_hot_mode_dev_cycle__benchmark and it worked fine:
```
$ ../../bin/cache/dart-sdk/bin/dart bin/run.dart -t smoke_catalina_hot_mode_dev_cycle__benchmark
Task result:
{
  "success": true,
  "data": {
    "hotReloadInitialDevFSSyncMilliseconds": 2136,
    "hotRestartMillisecondsToFrame": 612,
    "hotReloadMillisecondsToFrame": 317,
    "hotReloadDevFSSyncMilliseconds": 32,
    "hotReloadFlutterReassembleMilliseconds": 261,
    "hotReloadVMReloadMilliseconds": 23,
    "hotReloadMillisecondsToFrameAfterChange": 340,
    "hotReloadDevFSSyncMillisecondsAfterChange": 54,
    "hotReloadFlutterReassembleMillisecondsAfterChange": 167,
    "hotReloadVMReloadMillisecondsAfterChange": 119,
    "hotReloadInitialDevFSSyncAfterRelaunchMilliseconds": 1960
  },
  "benchmarkScoreKeys": [
    "hotReloadInitialDevFSSyncMilliseconds",
    "hotRestartMillisecondsToFrame",
    "hotReloadMillisecondsToFrame",
    "hotReloadDevFSSyncMilliseconds",
    "hotReloadFlutterReassembleMilliseconds",
    "hotReloadVMReloadMilliseconds",
    "hotReloadMillisecondsToFrameAfterChange",
    "hotReloadDevFSSyncMillisecondsAfterChange",
    "hotReloadFlutterReassembleMillisecondsAfterChange",
    "hotReloadVMReloadMillisecondsAfterChange",
    "hotReloadInitialDevFSSyncAfterRelaunchMilliseconds"
  ]
}


════╡ ••• Finished task "smoke_catalina_hot_mode_dev_cycle__benchmark" ••• ╞════
```

**Comment by Zazo032** [comment] 2020-06-12 18:33
Today I saw some crashes similar to that one while running my app on that engine version. Sometimes the crash happended while hot reloading, sometimes while hot restarting, sometimes while installing the debug apk and even when the app was running but "idle" (IDE was not being used, but debug app was running).

**Comment by jason-simmons** [comment] 2020-06-12 18:40
I found that this crash can be reproduced by running an app on Android and pressing the task switcher.  (It seems to happen inconsistently when running the `smoke_catalina_hot_mode_dev_cycle__benchmark`)

**Comment by dnfield** [comment] 2020-06-12 18:45
Symbolicated stack trace from @goderbauer when backgrounding the app on android:

```
********** Crash dump: **********
Build fingerprint: 'google/flame/flame:10/QQ2A.200405.005/6254899:user/release-keys'
#00 0x0148e0d6 /data/app/com.example.crashrepro-mexCu2CrICyGsDTccDrs-g==/lib/arm/libflutter.so (BuildId: 58e5ad5dae2d3311f4d5d8902da1687d85a3da20)
                                                                                                SkRefCntBase::unref() const::'lambda'()::operator()() const
                                                                                                /Users/goderbauer/dev/engine/src/out/android_debug_unopt/../../third_party/skia/include/core/SkRefCnt.h:72:9
#01 0x0148aa57 /data/app/com.example.crashrepro-mexCu2CrICyGsDTccDrs-g==/lib/arm/libflutter.so (BuildId: 58e5ad5dae2d3311f4d5d8902da1687d85a3da20)
                                                                                                ??
                                                                                                ??:0:0
Crash dump is completed
```

**Comment by goderbauer** [comment] 2020-06-12 18:46
I am also running into this crash locally. Here's the symbolicated dump I am getting:

```
********** Crash dump: **********
Build fingerprint: 'google/flame/flame:10/QQ2A.200405.005/6254899:user/release-keys'
#00 0x0148e0d6 /data/app/com.example.crashrepro-mexCu2CrICyGsDTccDrs-g==/lib/arm/libflutter.so (BuildId: 58e5ad5dae2d3311f4d5d8902da1687d85a3da20)
                                                                                                SkRefCntBase::unref() const::'lambda'()::operator()() const
                                                                                                /Users/goderbauer/dev/engine/src/out/android_debug_unopt/../../third_party/skia/include/core/SkRefCnt.h:72:9
#01 0x0148aa57 /data/app/com.example.crashrepro-mexCu2CrICyGsDTccDrs-g==/lib/arm/libflutter.so (BuildId: 58e5ad5dae2d3311f4d5d8902da1687d85a3da20)
                                                                                                ??
                                                                                                ??:0:0
Crash dump is completed
```

**Comment by goderbauer** [comment] 2020-06-12 18:50
Sometimes I am also seeing this slightly different dump:
```
********** Crash dump: **********
Build fingerprint: 'google/flame/flame:10/QQ2A.200405.005/6254899:user/release-keys'
#00 0x0148e0d6 /data/app/com.example.crashrepro-fddQYYeY-n5VM34aONjcKA==/lib/arm/libflutter.so (BuildId: 58e5ad5dae2d3311f4d5d8902da1687d85a3da20)
                                                                                                void std::__1::__cxx_atomic_store<unsigned int>(std::__1::__cxx_atomic_base_impl<unsigned int>*, unsigned int, std::__1::memory_order)
                                                                                                /Users/goderbauer/dev/engine/src/out/android_debug_unopt/../../third_party/libcxx/include/atomic:956:0
#01 0x0148aa57 /data/app/com.example.crashrepro-fddQYYeY-n5VM34aONjcKA==/lib/arm/libflutter.so (BuildId: 58e5ad5dae2d3311f4d5d8902da1687d85a3da20)
                                                                                                ??
                                                                                                ??:0:0
Crash dump is completed
```

**Comment by jason-simmons** [comment] 2020-06-12 19:37
This is related to https://github.com/flutter/engine/commit/f5ab179e7a793e2bd5d087d59911e99f8b45e6c9

`nativeNotifyLowMemoryWarning` needs to explicitly pass the `nativePlatformViewId` as a parameter so that the native function can extract it as the `shell_holder`

@dnfield

**Comment by dnfield** [comment] 2020-06-12 19:55
Thanks Jason.  Since this was reverted I think we can close this bug right?  I'll work to reland my change properly

**Closed** 2020-06-12 19:58 UTC
Labels: P0, engine, severe: crash
