### ISSUE TITLE
Physical keyboard keys event not detected

### ISSUE THREAD

**Issue by MunibullahShah** [flutter/flutter#159516] opened 2024-11-26 23:14 UTC
### Steps to reproduce

1. Attach a physical keyboard with Macbook pro M1
2. Have a textfield using FlutterFormBuilder
3. Start typing with a little bit fast speed, having debugger on

### Expected results

Keys pressed should be appear in the application

### Actual results

```
Got this Error with having no keys Entered
======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#dbcab(physicalKey: PhysicalKeyboardKey#86a89(usbHidUsage: "0x00070008", debugName: "Key E"), logicalKey: LogicalKeyboardKey#1e0f5(keyId: "0x00000065", keyLabel: "E", debugName: "Key E"), character: null, timeStamp: 296:33:14.409007)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 509 pos 16: '_pressedKeys.containsKey(event.physicalKey)'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
```

### Code sample

<details open><summary>Code sample</summary>

```
import 'package:auno/common/widgets.dart';
import 'package:auno/models/product_short_entity.dart';
import 'package:auno/pages/plans/plans_page.dart';
import 'package:auno/providers/products_list_provider.dart';
import 'package:auno/router.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:flutter_svg/svg.dart';
import 'package:provider/provider.dart';

class SearchList extends StatefulWidget {
  const SearchList({Key? key}) : super(key: key);
  static const routeName = '/search_list';
  @override
  _SearchListState createState() => _SearchListState();
}

class _SearchListState extends State<SearchList> {
  String search = "";
  late ScrollController _scrollController;

  List<ProductShortEntity> data = [];
  bool notSearch = true;

  @override
  void initState() {
    _scrollController = ScrollController();
    super.initState();
    data = context.read<ProductsListProvider>().popular;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: body(),
    );
  }

  @override
  Widget body() {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.only(
          top: 5,
          right: 5.0,
        ),
        child: Column(
          children: [
            Padding(
              padding: const EdgeInsets.only(left: 16.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Container(
                    width: MediaQuery.of(context).size.width - 95,
                    height: 50,
                    child: FormBuilderTextField(
                      name: 'search',
                      onChanged: _onSearchChanged,
                      onSubmitted: (value) {
                        setState(() {
                          search = value ?? "";
                          _onSearchChanged(value);
                        });
                      },
                      decoration: MyInputDecoration(
                        hintText: 'Search',
                        prefixIcon: Padding(
                          padding: const EdgeInsets.only(
                              top: 8.0, bottom: 9, left: 10, right: 8),
                          child: SvgPicture.asset(
                            'svg/search.svg',
                            color: const Color(0xff2F384C),
                          ),
                        ),
                        borderRadius: 7,
                        borderColor: const Color(0xffE8E8E8),
                      ),
                    ),
                  ),
                  TextButton(
                    onPressed: () {
                      router.pop();
                    },
                    child: Text(
                      'Cancel',
                      style: TextStyle(
                        color: Theme.of(context).primaryColor,
                        fontFamily: 'OverUsed',
                      ),
                    ),
                  ),
                ],
              ),
            ),
            if (data.length != 0)
              Expanded(
                child: ListView.builder(
                  itemCount: data.length,
                  scrollDirection: Axis.vertical,
                  shrinkWrap: true,
                  // controller: scrollController,
                  itemBuilder: (context, index) {
                    return Column(
                      children: [
                        if (notSearch && index == 0)
                          Container(
                            alignment: Alignment.centerLeft,
                            padding: const EdgeInsets.only(
                                left: 16.0, bottom: 8.0, top: 20),
                            child: Text(
                              'Popular',
                              style: TextStyle(
                                fontFamily: 'OverUsed',
                                fontSize: 16,
                                color: Colors.black,
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ),
                        ListTile(
                          onTap: () {
                            // remove focus
                            FocusScope.of(context).unfocus();
                            router.push(PlansPage.routeName,
                                extra: data[index]);
                          },
                          style: ListTileStyle.drawer,
                          title: Text(data[index].name),
                          leading: NetworkImageWithPlaceholder(
                            data[index].flag,
                            circular: true,
                            width: 40,
                            height: 40,
                          ),
                        ),
                      ],
                    );
                  },
                ),
              ),
            if (data.length == 0)
              Container(
                padding: const EdgeInsets.all(8.0),
                alignment: Alignment.center,
                child: Column(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      SvgPicture.asset(
                        'svg/Location_Not_Found.svg',
                      ),
                      const SizedBox(height: 20),
                      const Text(
                        'No Results Found',
                        style: TextStyle(
                          color: Colors.black,
                          fontWeight: FontWeight.bold,
                          fontFamily: 'OverUsed',
                          fontSize: 20,
                        ),
                      ),
                      const SizedBox(height: 10),
                      const Padding(
                        padding: EdgeInsets.all(.0),
                        child: Text(
                          "We couldn’t find the destination you’re looking for, Try checking all of our destinations.",
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontFamily: 'OverUsed',
                            fontSize: 16,
                          ),
                        ),
                      ),
                    ]),
              ),
          ],
        ),
      ),
    );
  }



  searching(String value) {
    List<ProductShortEntity> searchResult = [];
    if (value.isNotEmpty) {
      data.forEach((element) {
        if (element.name.toLowerCase().contains(value.toLowerCase())) {
          searchResult.add(element);
        }
      });
      setState(() {
        data = searchResult;
      });
      return;
    } else {
      setState(() {
        data = data;
      });
    }
  }

  void _onSearchChanged(String? query) {
    notSearch = query == null || query.isEmpty;
    setState(() {
      search = query ?? "";
      data = context.read<ProductsListProvider>().search(search);
    });
    if (data.isNotEmpty) {
      print('data: ${data.first.name}');
    }
  }

  @override
  // bool get withScaffold => true;

  @override
  // bool get withAppBar => false;
  @override
  bool get paginate => true;

  @override
  void dispose() {
    super.dispose();
    // _debounce?.cancel();
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 15.1 24B83 darwin-arm64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Munibullah Shah’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Munibullah Shah’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by darshankawar** [comment] 2024-11-27 10:00
@MunibullahShah 
In order to properly address the issue, please provide us only minimal but complete reproducible code sample (ex: main.dart) without third party package implementation.
This might well be a duplicate of https://github.com/flutter/flutter/issues/125975 that you can check.

**Closed** 2024-12-18 10:09 UTC
Labels: waiting for customer response, in triage
