### ISSUE TITLE
`flutter` tool doesn't understand that -T can be missing

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#4552] opened 2016-06-14 15:08 UTC
This is running on Genymotion (attempting to verify https://github.com/flutter/flutter/issues/490), but I think the relevant part is that the target device (emulator) is using API 19, thus an old ADB.

We supposedly support all the way back to API 16?
https://flutter.io/faq/#what-devices-and-os-versions-does-flutter-run-on

@devoncarew 

```
eseidel@eseidel-macbookpro /src/flutter/examples/flutter_gallery %flutter run                                     [/src/flutter/examples/flutter_gallery]
Building flutter tool...
Running 'pub get' in flutter_gallery...              27.4s
Building APK in debug mode (android-x86)...              
Warning: signing the APK using the debug keystore.
Built build/app.apk (31.9MB).
Running lib/main.dart on Samsung Galaxy S5, 4 4 4, API 19, 1080x1920...
logcat: invalid option -- T
Unrecognized Option
Usage: logcat [options] [filterspecs]
options include:
  -s              Set default filter to silent.
                  Like specifying filterspec '*:s'
  -f <filename>   Log to file. Default to stdout
  -r [<kbytes>]   Rotate log every kbytes. (16 if unspecified). Requires -f
  -n <count>      Sets max number of rotated logs to <count>, default 4
  -v <format>     Sets the log print format, where <format> is one of:

                  brief process tag thread raw time threadtime long

  -c              clear (flush) the entire log and exit
  -d              dump the log and then exit (don't block)
  -t <count>      print only the most recent <count> lines (implies -d)
  -g              get the size of the log's ring buffer and exit
  -b <buffer>     Request alternate ring buffer, 'main', 'system', 'radio'
                  or 'events'. Multiple -b parameters are allowed and the
                  results are interleaved. The default is -b main -b system.
  -B              output the log in binary
filterspecs are a series of 
  <tag>[:priority]

where <tag> is a log component tag (or * for all) and priority is:
  V    Verbose
  D    Debug
  I    Info
  W    Warn
  E    Error
  F    Fatal
  S    Silent (supress all output)

'*' means '*:d' and <tag> by itself means <tag>:v

If not specified on the commandline, filterspec is set from ANDROID_LOG_TAGS.
If no filterspec is found, filter defaults to '*:I'

If not specified with -v, format is set from ANDROID_PRINTF_LOG
or defaults to "brief"

^C
```

**Comment by eseidelGoogle** [comment] 2016-06-14 15:08
```
eseidel@eseidel-macbookpro /src/flutter/examples/flutter_gallery %flutter doctor                                  [/src/flutter/examples/flutter_gallery]
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /src/flutter
    • Framework revision 2b2d782503 (13 hours ago), engine revision 864beb8d26

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/eseidel/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.2
    • dartlang plugin version 0.6.19
```

**Comment by devoncarew** [comment] 2016-06-14 16:07
dupe of https://github.com/flutter/flutter/issues/3037; we should fix to get compatibility back to the old devices

**Closed by devoncarew** 2016-06-14 16:07 UTC
Labels: affects: tools
