### ISSUE TITLE
Firebase Storage PDF file is not showing in Webview only showing white screen

### ISSUE THREAD

**Issue by narimetisaigopi** [flutter/flutter#59517] opened 2020-06-16 00:56 UTC
```
String url =
      "https://firebasestorage.googleapis.com/v0/b/campusfriend-1adac.appspot.com/o/courses%2Fbcom%2FClass%20Notes%2Fhb.pdf?alt=media&token=c8be5d46-8335-43ad-a557-99670bdb256d";
 
return WebView(
           javascriptMode: JavascriptMode.unrestricted,
           initialUrl: url,
);
```

**Comment by TahaTesser** [comment] 2020-06-16 09:53
Hi @narimetisaigopi 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-16 09:53 UTC
