### ISSUE TITLE
[web] Image.network() drawing black if cacheWidth/cacheHeight set

### ISSUE THREAD

**Issue by milke** [flutter/flutter#160199] opened 2024-12-12 21:41 UTC
### Steps to reproduce

Stable version 3.27.0, `Image.network() `and `FadeInImage.memoryNetwork()` both draw black if `cacheWidth/cacheHeight` or `imageCacheWidth/imageCacheHeight` is set.

In Browser console: `WebGL: INVALID_VALUE: texImage2D: The source data has been detached`

On another note, I tried removing the cacheWidth/Height and Image eviction didn't work unless I refresh. Calling setState to refresh image didn't work either.

### Expected results

I would expect an image to draw normally.

### Actual results

The image draws black instead. Calling `setState` to refresh the image has no effect.

### Code sample

N/A

### Screenshots or Video

N/A

### Logs

Browser console: `WebGL: INVALID_VALUE: texImage2D: The source data has been detached`

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.27.0, on Debian GNU/Linux 12 (bookworm)
    6.1.0-28-amd64, locale en_US.UTF-8)
    • Flutter version 3.27.0 on channel stable at
      /home/steve/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (27 hours ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/steve/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/steve/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[✓] Linux toolchain - develop for Linux desktop
    • Debian clang version 14.0.6
    • cmake version 3.25.1
    • ninja version 1.11.1
    • pkg-config version 1.8.1
[✓] Android Studio (version 2023.1)
    • Android Studio at /home/steve/android-studio
    • Flutter plugin version 77.1.2
    • Dart plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-17.0.7b1000.6-10550314)
[✓] VS Code (version 1.95.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.102.0
[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Debian GNU/Linux 12 (bookworm)
      6.1.0-28-amd64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 131.0.6778.139
[✓] Network resources
    • All expected network resources are available.
• No issues found!
```

**Comment by danagbemava-nc** [comment] 2024-12-13 08:50
Reproducible on the latest versions of stable and master. It works as expected on the previous stable. 

<img width="645" alt="Screenshot 2024-12-13 at 8 15 40 AM" src="https://github.com/user-attachments/assets/bfbccfcf-7452-4364-911f-b63c5cbfab98" />


```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    var title = 'Web Images';

    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Image.network(
          'https://picsum.photos/250?image=9',
          cacheHeight: 100,
        ),
      ),
    );
  }
}

```

<details>
<summary>flutter doctor -v</summary>

```
[!] Flutter (Channel [user-branch], 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    ! Flutter version 3.24.5 on channel [user-branch] at /Users/deanli/dev/switcher
    • Framework revision dec2ee5c1f (4 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3
```

```
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.27.0 on channel stable at /Users/deanli/dev/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (2 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2
```

```
[!] Flutter (Channel master, 3.28.0-1.0.pre.99, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.28.0-1.0.pre.99 on channel master at /Users/deanli/dev/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6a5445833b (4 hours ago), 2024-12-12 22:53:26 -0500
    • Engine revision 5eedfefe38
    • Dart version 3.7.0 (build 3.7.0-243.0.dev)
    • DevTools version 2.41.0
```
</details>

**Comment by michaelheider** [comment] 2024-12-16 14:06
Duplicate of #158093

**Closed** 2024-12-16 19:10 UTC
Labels: c: regression, engine, platform-web, a: images, c: rendering, e: web_canvaskit, has reproducible steps, team-web, found in release: 3.27, found in release: 3.28
