### ISSUE TITLE
Flutter Web, Autofills saved passwords without showing Suggestion for TextFormField(obscureText: true)

### ISSUE THREAD

**Issue by akashgk** [flutter/flutter#160114] opened 2024-12-11 21:07 UTC
### Steps to reproduce

- Run Project on Stable Mode in Flutter Web
- Create TextFormField(obscureText: true)
- On Browser save password popup save the credentials
- Refresh app and Click(Focus) on the text field.
- It will get filled with the stored credential instead of suggesting it.

### Expected results

The user should be shown the browser credential selection dropdown instead of automatically filling the text field upon focus.

### Actual results

The Text field gets filled with saved credentials on focus.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyWidget());
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      
      routes: {
      '': (context) => const MyForm(),
      'details': (context) => const MyForm(),
    }, home: const MyForm());
  }
}

class MyForm extends StatefulWidget {
  const MyForm({super.key});

  @override
  State<MyForm> createState() => _MyFormState();
}

class _MyFormState extends State<MyForm> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Form(
        key: _formKey,
        child: Column(
          children: [
            TextFormField(
              obscureText: true,
            ),
            TextFormField(
              obscureText: true,
            ),
            TextFormField(
              obscureText: true,
            ),
            TextFormField(
              obscureText: true,
            ),
            ElevatedButton(
                onPressed: () {
                  _formKey.currentState?.save();
                  Navigator.of(context).pushNamed('details');
                },
                child: const Text("Go to details")),
          ],
        ),
      ),
    );
  }
}

class DetailsScreen extends StatefulWidget {
  const DetailsScreen({super.key});

  @override
  State<DetailsScreen> createState() => _DetailsScreenState();
}

class _DetailsScreenState extends State<DetailsScreen> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Form(
        key: _formKey,
        child: Column(
          children: [
            TextFormField(
              obscureText: true,
            ),
            TextFormField(
              obscureText: true,
            ),
            TextFormField(
              obscureText: true,
            ),
            TextFormField(
              obscureText: true,
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/d329f93e-9079-4046-b106-a63693dce88d

</details>

### Logs

<details open><summary>Logs</summary>

```console
NO Logs being printed for the above reproducible code.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console

[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-QA)
    • Flutter version 3.24.5 on channel stable at /Users/akashkrishnan/Documents/SDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (4 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/akashkrishnan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (3 available)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 15.1.1 24B91 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 15.1.1 24B91 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by maheshj01** [comment] 2024-12-12 04:58
Hi @akashgk, Thanks for filing the issue. Closing as duplicate of https://github.com/flutter/flutter/issues/152879
Please follow up on that issue for further updates.

**Closed by maheshj01** 2024-12-12 04:58 UTC
Labels: in triage
