### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: The system cannot find the specified file. , errno = 2

### ISSUE THREAD

**Issue by OndrejZmatlik** [flutter/flutter#138952] opened 2023-11-23 17:31 UTC
## Command
```
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: The system cannot find the specified file.
, errno = 2
```
#0      _Directory.createSync (dart:io/directory_impl.dart:129:7)
#1      _File.createSync (dart:io/file_impl.dart:303:14)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:26:16)
#3      ErrorHandlingFile.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:283:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.createSync (package:flutter_tools/src/base/error_handling_io.dart:282:5)
#6      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:321:28)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#8      Template.render (package:flutter_tools/src/template.dart:281:24)
#9      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:483:21)
<asynchronous suspension>
#10     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:506:23)
<asynchronous suspension>
#11     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:351:31)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[!] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22631.2715], locale cs-CZ)
    • Flutter version 3.16.0 on channel stable at C:\Users\FarSniper\flutter\flutter
    ! Warning: `flutter` on your path resolves to C:\Users\FarSniper\flutter\bin\flutter, which is not inside your current Flutter SDK checkout at C:\Users\FarSniper\flutter\flutter. Consider adding C:\Users\FarSniper\flutter\flutter\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\FarSniper\flutter\bin\dart, which is not inside your current Flutter SDK checkout at C:\Users\FarSniper\flutter\flutter. Consider adding C:\Users\FarSniper\flutter\flutter\bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (8 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\FarSniper\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.8.34309.116
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at C:\Users\FarSniper\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.2715]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.160
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.72

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment] 2023-11-24 08:40
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98066. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-11-24 08:40 UTC
Labels: in triage
