### ISSUE TITLE
String.toUpperCase not supporting certain languages

### ISSUE THREAD

**Issue by chingjun** [flutter/flutter#81030] opened 2021-04-23 08:01 UTC
Internal bug: b/185975409

Currently Flutter's toUpperCase is using language independent unicode mapping and thus couldnt handle certain languages with special requirements, e.g. Greek and Turkish.

(https://api.flutter.dev/flutter/dart-core/String/toUpperCase.html)

Are there any plans to add the capability to handle these languages to flutter?

Input: Ειδοποιήσεις
Expected Result: ΕΙΔΟΠΟΙΗΣΕΙΣ
Actual result: ΕΙΔΟΠΟΙ'ΗΣΕΙΣ

**Comment by mraleph** [comment] 2021-04-26 10:22
I would imagine one basically  needs Dart level bindings to ICU would solve this sort of problem. (`dart:icu` was at development at some point but I don't know the status now)

/fyi @lrhn

**Comment by lrhn** [comment] 2021-04-26 10:48
The Dart libraries are locale independent. That was necessary originally because compiling to JavaScript didn't give us any locale-dependent implementations. They do now, so we might have a chance of adding locale support blowing up the code size.
We don't have any current *plans* for it, though.

It is something which requires platform cooperation. possibly by interfacing with the ICU library, because we do not want to deploy as huge Dart library containing all the Unicode tables. We've done so with `package:characters`, which only does grapheme break detection and is heavily size-optimized for just that, and it's still fairly large (14K of tables). It won't scale to all Unicode processing. So, it probably needs to be platform based, and it will need some design to make it work both native and in the browser.

**Comment by jiahaog** [comment] 2021-05-05 23:00
Updating to P3 to match the internal priority

**Comment by a-siva** [comment] 2023-07-24 16:43
Who should own this issue?

**Comment by Hixie** [comment] 2023-07-25 22:37
@mraleph Is this a WONTFIX? Does dart:intl provide this functionality?

**Comment by mraleph** [comment] 2023-07-26 07:13
I think as phrased it is "working as intended" per @lrhn comment. 

I don't see any APIs in intl which directly expose exactly that. The closest is https://api.flutter.dev/flutter/intl/toBeginningOfSentenceCase.html

Any opinions on this @mosuem ?

**Comment by Hixie** [comment] 2023-07-31 01:34
I think this is probably best considered a feature request for the `intl` package, which is locale-aware (unlike the dart:core APIs). https://github.com/dart-lang/i18n/issues/new/choose would be the right place to file it.

**Comment by mosuem** [comment] 2023-07-31 09:40
`package:intl` sounds like the right place for this. https://unicode-org.github.io/icu/userguide/transforms/casemappings.html would be the place to start looking if one would try to implement it.

But as parts of ICU4C are already in Flutter, couldn't it be also implemented there? @Manishearth

**Comment by Manishearth** [comment] 2023-07-31 15:51
ICU4C already has the right casemapping APIs, and ICU4X implements the same casing algorithms[^1]. So yes, ICU4C should be sufficient here; you can uppercase with the locale and get the special Greek behavior.



 [^1]: Note that this includes things that aren't specced: Greek uppercasing is currently not specced as a special case, but ICU4C and ICU4X implement it.

**Comment by Hixie** [comment] 2023-08-01 17:46
Long term we want to expose ICU4X in a way that reuses the bits that are shipped with the app, but that's not likely to happen any time soon. I think that's sort of orthogonal to this issue though.

Would anyone like to file the issue on package:intl?

**Comment by Hixie** [comment] 2023-08-08 22:34
Looks like there already is one: https://github.com/dart-lang/i18n/issues/229

I'm closing this as a duplicate of that issue. Thanks for filing it!

**Closed by Hixie** 2023-08-08 22:34 UTC
Labels: waiting for customer response, a: internationalization, dependency: dart, will need additional triage, customer: money (g3), P2
