### ISSUE TITLE
Add Setting to generate info.plist in flutter_module case

### ISSUE THREAD

**Issue by dodatw** [flutter/flutter#117883] opened 2023-01-03 04:03 UTC
I'm using the flutter_module solution to integrate flutter into an existing project.
I followed the steps in this document:
https://docs.flutter.dev/development/add-to-app/ios/project-setup

It will generate `.ios/` folder which can help us to run test flutter project on iOS.
But I have a request, I need a permission to add NSPhotoLibraryUsageDescription in .ios/Runner/Info.plist

But `.ios` seems to be a generated file and should not be modified. Can we add some parameters in yaml to generate info.plist including these settings?

**Comment by danagbemava-nc** [comment] 2023-01-03 07:13
Hi @dodatw, for this case, you should be able to add the permission to the main iOS app and it should work just fine. Or are you trying to test the module in isolation before you add it to the iOS app?

**Comment by dodatw** [comment] 2023-01-10 04:09
@danagbemava-nc, 
Yes, We already add the permission on main iOS project.
But for testbed, I also want to test module in isolation.

**Comment by danagbemava-nc** [comment] 2023-01-10 05:53
Hi @dodatw, then this is a duplicate of the discussion in https://github.com/flutter/flutter/issues/98077. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

Thank you

**Closed by danagbemava-nc** 2023-01-10 05:53 UTC
Labels: in triage
