### ISSUE TITLE
`flutter run` crashes if the `pidfile` is not writable

### ISSUE THREAD

**Issue by kika** [flutter/flutter#48657] opened 2020-01-11 21:48 UTC
Reproduce: run `fultter run --pidfile=/var/run/flutter.pid` if the `/var/run` is not writable for the current user (or specify any other directory which is not writable).

<details><summary>Crash log: </summary>
<p>
Flutter crash report; please file at https://github.com/flutter/flutter/issues

## command

flutter run -d AB156805-3811-4364-B30E-EE3C6B000D9F --track-widget-creation --pid-file /var/run/flutter2.pid

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/var/run/flutter2.pid' (OS Error: Permission denied, errno = 13)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      writePidFile (package:flutter_tools/src/base/utils.dart:371:22)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:337:5)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#19     _rootRunUnary (dart:async/zone.dart:1134:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#25     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#26     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#27     IosProject.isSwift (package:flutter_tools/src/project.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#29     _rootRunUnary (dart:async/zone.dart:1134:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#34     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#35     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#36     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#37     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#39     _rootRunUnary (dart:async/zone.dart:1134:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#44     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#45     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#46     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#47     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#48     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#49     _rootRunUnary (dart:async/zone.dart:1134:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#51     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#52     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#53     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#54     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#55     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#56     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#57     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#58     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#59     _rootRunUnary (dart:async/zone.dart:1134:38)
#60     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#61     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#62     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#63     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#64     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#65     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#66     _rootRunUnary (dart:async/zone.dart:1134:38)
#67     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#68     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#69     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#70     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#71     Future._complete (dart:async/future_impl.dart:514:7)
#72     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#73     _rootRun (dart:async/zone.dart:1122:38)
#74     _CustomZone.run (dart:async/zone.dart:1023:19)
#75     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#76     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#77     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#78     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#79     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#80     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#81     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#82     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#83     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#84     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#85     _rootRun (dart:async/zone.dart:1122:38)
#86     _CustomZone.run (dart:async/zone.dart:1023:19)
#87     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#88     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#89     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#90     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#91     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#92     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#93     _StreamController.close (dart:async/stream_controller.dart:624:5)
#94     _Socket._onData (dart:io-patch/socket_patch.dart:1838:21)
#95     _rootRunUnary (dart:async/zone.dart:1138:13)
#96     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#97     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#98     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#99     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#100    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#101    _StreamController._add (dart:async/stream_controller.dart:642:7)
#102    _StreamController.add (dart:async/stream_controller.dart:588:5)
#103    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1386:35)
#104    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:892:18)
#105    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#106    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#107    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#108    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Volumes/ExtStripe/Scratch/flutter
    [32m•[39m Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/kika/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3, Build version 11C29
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 33.4.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (4 available)
    [32m•[39m Android SDK built for x86 • emulator-5554                            • android-x86 • Android 5.1.1 (API 22)
      (emulator)
    [32m•[39m Cuida iPhone6             • dc3208577c85154c9f37da96f8e04f5d004652d0 • ios         • iOS 12.4.4
    [32m•[39m iPhone 5s                 • 0B3D73C5-1448-4647-A42E-5D37434D3126     • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)
    [32m•[39m iPhone X                  • AB156805-3811-4364-B30E-EE3C6B000D9F     • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)

[32m•[39m No issues found!
```
</details>

<details><summary>`flutter doctor -v`</summary>
<p>

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Volumes/ExtStripe/Scratch/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kika/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 5.1.1 (API 22) (emulator)
    • Cuida iPhone6             • dc3208577c85154c9f37da96f8e04f5d004652d0 • ios         • iOS 12.4.4
    • iPhone 5s                 • 0B3D73C5-1448-4647-A42E-5D37434D3126     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)
    • iPhone X                  • AB156805-3811-4364-B30E-EE3C6B000D9F     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)

• No issues found!
```
</details>

**Comment by jonahwilliams** [comment] 2020-02-15 22:02
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-15 22:02 UTC
Labels: tool
