### ISSUE TITLE
Please do support for Windows 10/UWP this month

### ISSUE THREAD

**Issue by fisforfaheem** [flutter/flutter#55404] opened 2020-04-22 20:23 UTC
Is there any plan to add support for Windows 10/UWP? The reason I ask this is because there are almost 1billion windows 10 devices on the internet now and more that are not even on the internet.

**Comment by stuartmorgan** [comment] 2020-04-22 20:59
Duplicate of https://github.com/flutter/flutter/issues/14967

Please don't file multiple issues requesting the same thing; it just wastes developer time.

**Closed by stuartmorgan** 2020-04-22 20:59 UTC
