### ISSUE TITLE
In landscape orientation, the validator is working incorrectly

### ISSUE THREAD

**Issue by Aashu-Jha** [flutter/flutter#79228] opened 2021-03-28 14:34 UTC
## Steps to Reproduce

1. [.Offline_password_manager](https://github.com/Aashu-Jha/secure_af) Import this repository.
2. Run App.
3.  - Click on FloatingButton(Add) and change the orientation to landscape.
     - Now without filling details above just go to password, fill it  and then click next in keyboard(the focus will go to website).
     - Now click on save (upper-right-corner).
     - The data will get saved but it should not have to because of validator.
     - Do same procedure in potrait orientation, the validator will work fine.

**Expected results:** 
I wanted to see the error message 'required field' in TextFormField('title').

**Actual results:** 
The validator passed the data and the data get saved without title.

<details>
  <summary>Logs</summary>

**Flutter run --verbose Logs**
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD SUCCESSFUL in 16s
[        ] 132 actionable tasks: 7 executed, 125 up-to-date
[ +552 ms] Running Gradle task 'assembleDebug'... (completed in 17.1s)
[  +52 ms] calculateSha: LocalDirectory: 'C:\Users\Aashish Jha\StudioProjects\secure_af\build\app\outputs\flutter-apk'/app.apk
[  +41 ms] calculateSha: reading file took 40us
[ +668 ms] calculateSha: computing sha took 667us
[  +14 ms] √ Built build\app\outputs\flutter-apk\app-debug.apk.
[  +12 ms] executing: C:\Android\sdk\build-tools\30.0.3\aapt dump xmltree C:\Users\Aashish
Jha\StudioProjects\secure_af\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[  +22 ms] Exit code 0 from: C:\Android\sdk\build-tools\30.0.3\aapt dump xmltree C:\Users\Aashish
Jha\StudioProjects\secure_af\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1e
               A: android:compileSdkVersionCodename(0x01010573)="11" (Raw: "11")
               A: package="com.iamaashish.secure_af" (Raw: "com.iamaashish.secure_af")
               A: platformBuildVersionCode=(type 0x10)0x1e
               A: platformBuildVersionName=(type 0x10)0xb
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1e
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=16)
                 A: android:label(0x01010001)="secure_af" (Raw: "secure_af")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw:
                 "androidx.core.app.CoreComponentFactory")
                 E: activity (line=21)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.iamaashish.secure_af.MainActivity" (Raw:
                   "com.iamaashish.secure_af.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=35)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw:
                     "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: meta-data (line=45)
                     A: android:name(0x01010003)="io.flutter.embedding.android.SplashScreenDrawable" (Raw:
                     "io.flutter.embedding.android.SplashScreenDrawable")
                     A: android:resource(0x01010025)=@0x7f040000
                   E: intent-filter (line=49)
                     E: action (line=50)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=52)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER") 
                 E: meta-data (line=59)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: activity (line=63)
                   A: android:theme(0x01010000)=@0x01030007
                   A: android:name(0x01010003)="io.flutter.plugins.urllauncher.WebViewActivity" (Raw:
                   "io.flutter.plugins.urllauncher.WebViewActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
[  +11 ms] Stopping app 'app.apk' on RMX1851.
[   +3 ms] executing: C:\Android\sdk\platform-tools\adb.exe -s 4f7be5f2 shell am force-stop com.iamaashish.secure_af
[ +200 ms] executing: C:\Android\sdk\platform-tools\adb.exe -s 4f7be5f2 shell pm list packages com.iamaashish.secure_af
[ +174 ms] package:com.iamaashish.secure_af
[   +2 ms] executing: C:\Android\sdk\platform-tools\adb.exe -s 4f7be5f2 shell cat
/data/local/tmp/sky.com.iamaashish.secure_af.sha1
[ +103 ms] a891b089f7447381bcf838f9fdc3cc789d2b2cc5
[   +1 ms] Installing APK.
[   +1 ms] Installing build\app\outputs\flutter-apk\app.apk...
[        ] executing: C:\Android\sdk\platform-tools\adb.exe -s 4f7be5f2 install -t -r C:\Users\Aashish
Jha\StudioProjects\secure_af\build\app\outputs\flutter-apk\app.apk
[+7635 ms] Performing Streamed Install
                    Success
[        ] Installing build\app\outputs\flutter-apk\app.apk... (completed in 7.6s)
[   +1 ms] executing: C:\Android\sdk\platform-tools\adb.exe -s 4f7be5f2 shell echo -n 4d5b195fea08b2dba20bf20cc43c95282544b5fd >/data/local/tmp/sky.com.iamaashish.secure_af.sha1
[  +62 ms] executing: C:\Android\sdk\platform-tools\adb.exe -s 4f7be5f2 shell -x logcat -v time -t 1
[ +116 ms] --------- beginning of main
                    03-28 19:44:43.103 D/Launcher.ColorBubbleTextView( 4360): applyIconAndLabel: AppInfo(@f8fc902id=-1 type=APP 
                    container=-1 screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} installStateType=-1     
                    installSource=null
                    component=ComponentInfo{in.amazon.mShop.android.shopping/com.amazon.mShop.home.HomeActivity}, update=false, 
                    limit=false, runtime=110000000 componentName =
                    ComponentInfo{in.amazon.mShop.android.shopping/com.amazon.mShop.home.HomeActivity}), isLimitedState = false,                    isLimitedIconEnabled = true
[   +6 ms] executing: C:\Android\sdk\platform-tools\adb.exe -s 4f7be5f2 shell am start -a android.intent.action.RUN -f
0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez
verify-entry-points true com.iamaashish.secure_af/com.iamaashish.secure_af.MainActivity
[ +291 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.iamaashish.secure_af/.MainActivity (has
extras) }
[   +1 ms] Waiting for observatory port to be available...
[+2478 ms] Observatory URL on device: http://127.0.0.1:40407/bDceoHzA1Qw=/
[   +1 ms] executing: C:\Android\sdk\platform-tools\adb.exe -s 4f7be5f2 forward tcp:0 tcp:40407
[  +15 ms] 51645
[   +1 ms] Forwarded host port 51645 to device port 40407 for Observatory
[   +6 ms] Caching compiled dill
[  +41 ms] Connecting to service protocol: http://127.0.0.1:51645/bDceoHzA1Qw=/
[ +502 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at
http://127.0.0.1:51645/bDceoHzA1Qw=/.
[ +264 ms] DDS is listening at http://127.0.0.1:51651/i7kvDUL8Jkg=/.
[  +49 ms] Successfully connected to service protocol: http://127.0.0.1:51645/bDceoHzA1Qw=/
[ +984 ms] Activating Dart DevTools...
[+3488 ms] Activating Dart DevTools... (completed in 3.5s)
[ +527 ms] DevFS: Creating new filesystem on the device (null)
[  +61 ms] DevFS: Created new filesystem on the device
(file:///data/user/0/com.iamaashish.secure_af/code_cache/secure_afZNCUKC/secure_af/)
[   +4 ms] Updating assets
[ +102 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see
#56466.
[   +3 ms] Syncing files to device RMX1851...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:secure_af/main.dart a26b0a1c-40c4-4c22-8526-e6f7f5b6f596
[        ] <- a26b0a1c-40c4-4c22-8526-e6f7f5b6f596
[ +119 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device RMX1851... (completed in 125ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[  +18 ms] Connected to _flutterView/0x739558d020.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[   +1 ms] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on RMX1851 is available at: http://127.0.0.1:51651/i7kvDUL8Jkg=/
[   +2 ms] 
           Flutter DevTools, a Flutter debugger and profiler, on RMX1851 is available at:
           http://127.0.0.1:9105?uri=http%3A%2F%2F127.0.0.1%3A51651%2Fi7kvDUL8Jkg%3D%2F
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+6151 ms] I/shish.secure_a( 8899): ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=5000

```

```
no analyzer warnings
```

'''
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-IN)
    • Flutter version 2.0.3 at C:\src\flutter
    • Framework revision 4d7946a68d (10 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Android
    • ANDROID_SDK_ROOT = C:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\Aashish Jha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • RMX1851 (mobile) • 4f7be5f2 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)       • edge     • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!
'''

</details>

**Comment by iapicca** [comment] 2021-03-28 15:00
@Aashu-Jha 
```yaml
 provider: ^4.3.2+4
  cupertino_icons: ^1.0.2
  sqflite: ^1.3.2+4
  http: ^0.13.1
  url_launcher: ^6.0.2
  shared_preferences: ^0.5.12+4
  font_awesome_flutter: ^8.12.0
```

can you provide a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)  (not a full project)
**_without 3rd party plugins_**

**Comment by pedromassangocode** [comment] 2021-03-29 09:50
Hi @Aashu-Jha 
Please provide what was asked in https://github.com/flutter/flutter/issues/79228#issuecomment-808908547.

**Comment by Aashu-Jha** [comment] 2021-03-29 10:36
Hi @pedromassangocode @iapicca 
I tried to make minimal sample code but you know, I'm a beginner so without the 'provider' package, I'm unable to produce the same problem, but I am trying to make sample code.

Can I use the 'provider' package in the sample code?

For your help, I'm attaching a video link where you can see the problem I'm talking about.

![Problem_Screen_Recording](https://github.com/Aashu-Jha/Images/blob/main/20210329_155955.gif)

**Comment by pedromassangocode** [comment] 2021-03-29 14:08
> Can I use the 'provider' package in the sample code?

I suggest to not use it to make it easy to find the root cause!

**Comment by Aashu-Jha** [comment] 2021-03-30 20:35
@pedromassangocode 
I couldn't able to generate the bug in sample code. It's working fine.

What should I do now? Actually, I'm a beginner in both flutter n github and It's my first issue also. I don't know much about this all.

**Comment by pedromassangocode** [comment] 2021-03-31 06:20
> I couldn't able to generate the bug in the sample code. It's working fine.

Do you mean the issue is solved now? Otherwise I would still need what was asked in https://github.com/flutter/flutter/issues/79228#issuecomment-808908547.

**Comment by Aashu-Jha** [comment] 2021-03-31 06:23
> > I couldn't able to generate the bug in the sample code. It's working fine.
> 
> Do you mean the issue is solved now? Otherwise I would still need what was asked in [#79228 (comment)](https://github.com/flutter/flutter/issues/79228#issuecomment-808908547).

No, in the main app, the issue is still there.

**Comment by pedromassangocode** [comment] 2021-03-31 06:46
Then I do need a minimal reproducible code without third-party packages. Please refer to the following link to see how to create a minimal reproducible code: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by pedromassangocode** [comment] 2021-04-21 09:13
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-21 09:13 UTC
Labels: in triage, waiting for customer response
