### ISSUE TITLE
Error connecting to the service protocol: HttpException

### ISSUE THREAD

**Issue by quetool** [flutter/flutter#38971] opened 2019-08-21 12:42 UTC
```
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1026/kzYQ5sX6I8E=/ws
```

This error is really annoing. Happens when my iPhone Xr is connected, already tried evrything i found here related to it. Some things fix it, some not. But it happens 9 times out of 10

```
AlfredoMBPro:apperto alfredo$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale es-AR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.1)
[✓] Connected device (2 available)

• No issues found!
AlfredoMBPro:apperto alfredo$ 
```

**Comment by thavlik** [comment] 2019-08-21 13:39
Are you experiencing this when launching from VS Code? I find these things have different behavior when launching via XCode, VS Code, or `flutter run`.

**Comment by quetool** [comment] 2019-08-21 13:45
@thavlik yep, when launching via Start debugging command on VScode (F5). I rarely use `flutter run`

**Comment by thavlik** [comment] 2019-08-21 13:56
Does it work reliably with `flutter run`? Have you tried shutting off wifi when deploying?

**Comment by quetool** [comment] 2019-08-21 14:02
@thavlik I will run my app with `flutter run` from now on and let you know. Yes, shutting off wifi during run solves the problem most of the time, but I can't be shutting off wifi everytime I run the app

**Comment by thavlik** [comment] 2019-08-21 15:20
Good deal. These sorts of issues are pervasive on iOS. I hope fixes come soon! <3

**Comment by jmagman** [comment] 2019-08-22 02:06
In Xcode do you have Window > Devices and Simulator > Connect via Network checked?

**Comment by quetool** [comment] 2019-08-22 12:45
@jmagman nop, didn't have it. I already checked it but did not solve my problem 
![Captura de Pantalla 2019-08-22 a la(s) 09 44 40](https://user-images.githubusercontent.com/14978705/63515571-86c06a00-c4c1-11e9-9895-eed029045fb0.png)

**Comment by quetool** [comment] 2019-08-22 12:53
Oh, wait! I restarted VScode and now seems to be running... I will post any update here...

**Comment by quetool** [comment] 2019-08-22 13:23
Nop, still happening with Connect via Network checked

**Comment by jmagman** [comment] 2019-08-22 17:44
> Nop, still happening with Connect via Network checked

I've seen some issues with Connect via Network being checked, so try unchecking it if it is checked.

Might be a duplicate of https://github.com/flutter/flutter/issues/33130 but the log snippet doesn't say why the connection was closed.  @DanTup

**Comment by quetool** [comment] 2019-08-23 13:10
This is happening too often lately.

@jmagman it was unchecked, I checked it as you suggested...

**Comment by DanTup** [comment] 2019-08-26 08:03
Yeah, this seems like #33130. Can you reproduce with `flutter run -v` from the terminal? If so, can you paste the full output into a gist and link it here?

If it only occurs from VS Code, run the **Dart: Capture Logs** command and tick just Observatory/Debugger, then reproduce the issue and click **Stop Logging** (the notification may have collapsed into the bell icon in the status bar by then), and provide the log in a gist. Thanks!

**Comment by quetool** [comment] 2019-08-26 12:32
@DanTup Hi! This is a gist for your second request. That from VScode...

https://gist.github.com/quetool/14c77e9ebaf24163f6338f6f64bbefd1

How can I capture output from `flutter run -v`? It's sooooo long

**Comment by DanTup** [comment] 2019-08-26 12:40
> This is a gist for your second request. That from VScode...

Hmmm, something is weird here - there's almost nothing logged. The debug config also shows `"forceFlutterVerboseMode": false,` but it should show `true` if you're logging at the time you start the debug session.

How are you running this? Just with `F5`? Do you have a `launch.json`?

> How can I capture output from `flutter run -v`? It's sooooo long

You can use `tee` to write the output to a file while still showing it in the terminal with `flutter run -v | tee output.txt`.

**Comment by quetool** [comment] 2019-08-26 12:49
launch.json
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Flutter",
      "request": "launch",
      "type": "dart"
    }
  ]
}
```

Yes, I do run with F5. Steps are: Shift+Command+P -> Dart: Capture Logs check only Observatory/Debugger then I press F5. 

Here it is the output for `flutter run -v`. It's weird because this time went right but I paste the log anyway...
https://gist.github.com/quetool/ef5bee58c64bfaa5e45b4ce16ef77736

**Comment by DanTup** [comment] 2019-08-26 13:02
Hmm ok, let's try forcing verbose mode manually... in your `launch.json`, please add:

```js
    args: ["-v"],
```

Into the launch config. Then repeat, and hopefully the VS Code log will be more detailed.

> Here it is the output for `flutter run -v`. It's weird because this time went right

Thanks, though if it didn't happen the log doesn't help much - does it work reliably from the terminal, or is it intermittent there?

**Comment by quetool** [comment] 2019-08-26 13:43
> Hmm ok, let's try forcing verbose mode manually... in your `launch.json`, please add:
> 
> ```js
>     args: ["-v"],
> ```
> 
> Into the launch config. Then repeat, and hopefully the VS Code log will be more detailed.
> 

I got the same output (launching from F5)... I paste it here...

```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.3.0
Flutter extension: 3.3.0 (not activated)
VS Code: 1.37.1
Platform: mac
Workspace type: Flutter
Multi-root?: false
Dart SDK:
    Loc: /Users/alfredo/Desktop/flutter/bin/cache/dart-sdk
    Ver: 2.4.0
Flutter SDK:
    Loc: /Users/alfredo/Desktop/flutter
    Ver: 1.7.8+hotfix.4
HTTP_PROXY: undefined
NO_PROXY: undefined

Mon Aug 26 2019 [10:37:25 GMT-0300 (Argentina Standard Time)] Log file started
[10:37:27 AM] [General] [Info] Starting debug session...
[10:37:27 AM] [General] [Info]     workspace: /Users/alfredo/Documents/proyectos/flutter/apperto
[10:37:27 AM] [General] [Info] Using found common entry point: /Users/alfredo/Documents/proyectos/flutter/apperto/lib/main.dart
[10:37:27 AM] [General] [Info] Using workspace as cwd: /Users/alfredo/Documents/proyectos/flutter/apperto
[10:37:27 AM] [General] [Info] Detected launch project as Flutter
[10:37:27 AM] [General] [Info] Using Flutter debug adapter for this session
[10:37:27 AM] [General] [Info] Checking for errors before launching
[10:37:27 AM] [General] [Info] Spawning a new flutter debugger
[10:37:27 AM] [General] [Info] Debug session starting...
    {
        "name": "Flutter",
        "request": "launch",
        "type": "dart",
        "args": [
            "-v"
        ],
        "program": "/Users/alfredo/Documents/proyectos/flutter/apperto/lib/main.dart",
        "cwd": "/Users/alfredo/Documents/proyectos/flutter/apperto",
        "vmAdditionalArgs": [],
        "vmServicePort": 0,
        "dartPath": "/Users/alfredo/Desktop/flutter/bin/cache/dart-sdk/bin/dart",
        "maxLogLineLength": 2000,
        "pubPath": "/Users/alfredo/Desktop/flutter/bin/cache/dart-sdk/bin/pub",
        "pubSnapshotPath": "/Users/alfredo/Desktop/flutter/bin/cache/dart-sdk/bin/snapshots/pub.dart.snapshot",
        "debugSdkLibraries": false,
        "debugExternalLibraries": false,
        "showDartDeveloperLogs": true,
        "useFlutterStructuredErrors": true,
        "evaluateGettersInDebugViews": true,
        "forceFlutterVerboseMode": true,
        "flutterTrackWidgetCreation": true,
        "flutterMode": "debug",
        "flutterPlatform": "default",
        "flutterPath": "/Users/alfredo/Desktop/flutter/bin/flutter",
        "deviceId": "00008020-001A03CE1161002E",
        "deviceName": "iPhone Alfredo (ios)",
        "showMemoryUsage": false,
        "debugServer": 54311,
        "debuggerType": 2
    }
[10:37:27 AM] [General] [Warn] Did not find session 8d33eb4c-6086-4978-9037-1aad6542cf58 to handle dart.launching. There were 0 sessions:
[10:37:27 AM] [General] [Warn] Event will be queued and processed when the session start event fires
[10:37:27 AM] [General] [Info] Processing delayed event dart.launching for session 8d33eb4c-6086-4978-9037-1aad6542cf58
[10:39:18 AM] [FlutterRun] [Error] [ +408 ms] Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1027/NixDSnQCGg0=/ws
[10:39:18 AM] [Observatory] [Info] Process exited (sigterm)
[10:39:18 AM] [Observatory] [Info] Disconnect requested!
[10:39:18 AM] [Observatory] [Info] TERM: Requested to terminate with SIGINT...
[10:39:18 AM] [Observatory] [Info] TERM: Did not need to terminate processes
[10:39:18 AM] [Observatory] [Info] TERM: Removing all stored data...
[10:39:18 AM] [Observatory] [Info] TERM: Waiting for process to finish...
[10:39:18 AM] [Observatory] [Info] TERM: Disconnecting...
[10:39:18 AM] [General] [Info] Debugger:SessionDuration timing: 110873ms (Flutter)
Mon Aug 26 2019 [10:39:28 GMT-0300 (Argentina Standard Time)] Log file ended
```

> Thanks, though if it didn't happen the log doesn't help much - does it work reliably from the terminal, or is it intermittent there?

I really do not launch the app from terminal, so I might say it is working fine from there...

**Comment by quetool** [comment] 2019-08-26 13:48
I will try to copy debug log manually...

**Comment by DanTup** [comment] 2019-08-27 13:29
It's the `Flutter Run` log that would be interesting here. Your logs seem to be missing almost everything though and I'm not sure why. When I add `args["-v"]` to my launch config, here's what I see:

```
[2:25:55 PM] [FlutterRun] [Info] Spawning /Users/dantup/Dev/Google/flutter/bin/flutter with args ["run","--machine","--target","lib/main.dart","-d","31B1C998-21CC-4A32-ADB1-0C84568FA24A","--track-widget-creation","--start-paused","-v"]
[2:25:55 PM] [FlutterRun] [Info] ..  in /Users/dantup/Dev/Google/flutter/examples/flutter_gallery
[2:25:55 PM] [FlutterRun] [Info]     PID: 41942
[2:25:55 PM] [General] [Info] Processing delayed event dart.launching for session a190fded-6c4d-423c-a520-907526dd2f84
[2:25:55 PM] [FlutterRun] [Info] <== [  +30 ms] executing: [/Users/dantup/Dev/Google/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[2:25:55 PM] [FlutterRun] [Info] <== [  +38 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
```

The first few lines log the exact command being executed, and then all of the verbose Flutter output also appears in the log.

What happens if you go into a terminal in the project location and run `flutter run --machine -v` ? Do you see lots of output, or still only a single line with the error? If you try it using the iOS simulator, is that any different? (I don't have an iOS device to test with, so I'm testing with the simulator).

**Comment by DanTup** [comment] 2019-08-28 07:45
> Yep, I do see a lots of outputs, on a real device, because in a simulator `flutter run --machine -v` doesn't work...

I'm not sure what this means - `flutter run --machine -v` should work fine for the simulator too (that's how VS Code runs Flutter projects).

> But like I said before, I do not have problems with flutter run, the problem occurs when debuggin vía F5...

When you press F5 in VS Code, it just runs `flutter run` with the `--machine` flag, which allows communication with JSON messages. The reason I wanted you to try this, is that your VS Code log does not contain as much as it should - you're running the same command from the terminal and it sounds like it does. It seems like something is wrong with the logging in VS Code (though I can't explain what). If you'd be happy to try a debug build of VS Code to track that down (which might help track this issue down), please open an issue at https://github.com/Dart-Code/Dart-Code and we can try to figure that out.

**Comment by DanTup** [comment] 2019-08-29 09:07
> it means on simulator process was being "killed" after few seconds... The app is never laucnhed... But I realize just now it was because there were 2 devices connected, simulator and real device... 

I think it should tell you that there are multiple devices and have you provide one with the `-d` switch, is that not happening?

> I know that but I don't know why when I launch from CL on a real device works just fine and when I launch from F5 I got the error...

Is it trying to launch on the same device? For VS Code it will always explicitly pass the device that's shown in the status bar (bottom right), which may differ from what `flutter run` does if you do not pass the `-d` flag. It would be easier to tell what VS Code is doing with the log, but I'm not sure why that's not working. You could try enabling the [Flutter Run](https://dartcode.org/docs/logging/#flutter-run) log file which should always write to disk (not just when you run **Capture Logs**). If you open an issue at https://github.com/Dart-Code/Dart-Code we can try and figure that out - then we can compare the logs from terminal/VS Code easily to see what's different.

**Comment by quetool** [comment] 2019-08-29 12:56
> I think it should tell you that there are multiple devices and have you provide one with the -d switch, is that not happening?

That's right, that is not happening like shown on the gif I posted...

So this last log is useless too? 👇
>And here it is the entire log from flutter run --machine -v on an iOS simulator.
https://gist.github.com/quetool/cfabb8fd84b35f84f353e08c3f95bcde

I will open an issue on /Dart-Code as soon as I can understand what is happening with different loggin methods... Thanks for your patient...

**Comment by DanTup** [comment] 2019-08-29 13:07
> So this last log is useless too?

As far as I can tell, it doesn't include the error ("Error connecting to the service protocol") so I think it would only be useful as a comparison against a log where it failed.

Oh, I figured out what's going on with the logging 🙈 The instructions I gave you above were slightly incorrect - I told you to only tick Observatory/Debugger, but we want Flutter Run too :( The reason there was *some* Flutter Run, is that the logs include Errors from all categories, but only Info from the selected ones. Sorry for the mis-information :(

So - could you run **Dart: Capture Logs** and tick both **Flutter Run** and **Observatory** and repro, and hopefully that'll have some more info (including the exact flags we're launching with).

**Comment by quetool** [comment] 2019-08-29 14:02
@DanTup You won't believe me but today is running just fine even when I run from F5 🤦‍♂ 
I will post the log as soon the issue come back!

**Comment by DanTup** [comment] 2019-08-29 14:54
Oh yeah, did I forget to mention that I fixed it? 😏

But yeah, let me know when you see it next and if you can get a log. I've seen other people with similar issues that fixed it by unplugged and re-plugging the cable... I don't know why that helps though 😞

**Comment by quetool** [comment] 2019-08-29 14:59
> I've seen other people with similar issues that fixed it by unplugged and re-plugging the cable...

Worked for me too till I upgrade to stable 1.7.8 🤷‍♂️

**Comment by quetool** [comment] 2019-08-29 17:16
Ok, here were are, I think this is what you need, @DanTup, Observatory and Flutter Run ticked, pressed F5 and wait until it crashes on the issue

https://gist.github.com/quetool/312c1546bb904a573731554b55f61b63#file-gistfile1-txt-L2163

**Comment by quetool** [comment] 2019-08-30 19:53
Hi @DanTup,  here it is an update: Sometimes it happens the following situation.
When I get the error, usually i kill the app, I switch of wifi on device, I run again, when app is running ok, I switch on wifi again. That's fine, but sometimes, when I hot reload the app, it doesn't work, it stucks on _Syncing..._ forever... 

Evidently, on iOS there is something wrong with wifi and flutter...

**Comment by DanTup** [comment] 2019-09-02 13:37
> on iOS there is something wrong with wifi and flutter...

It does seem like there are problems. There's https://github.com/flutter/flutter/issues/15072 open tracking debugging over WiFi, however my understanding was that things should still work when connected via WiFi as long as it's also connected via cable - but I've seen several reports where disabling WiFi has fixed it.

I don't know a lot about this, but I've pinged @cbracken on that issue since it seems he may be a little more familiar with the issue. It's not clear if this should be considered a dupe, or if these are two different issues.

**Comment by quetool** [comment] 2019-09-02 15:20
Thanks @DanTup! Last gist I provided was what you wanted?

**Comment by DanTup** [comment] 2019-09-03 08:00
It was, though this seems like the same WiFi issue others have reported (I thought it might be something else). It seems like the connection may be unreliable. Flutter runs iProxy in a loop to forward a port - if iProxy quits with no output, the port failed to forward so the port number is increased and then tried again, until it prints something (eg. Forwarded port ForwardedPort HOST:1047 to DEVICE:54513).

```
[2:12:26 PM] [FlutterRun] [Info] <== [   +8 ms] Observatory URL on device: http://127.0.0.1:54513/ks53t3kcKQs=/
[2:12:26 PM] [FlutterRun] [Info] <== [   +1 ms] attempting to forward device port 54513 to host port 1024
[2:12:26 PM] [FlutterRun] [Info] <== [        ] executing: /usr/local/bin/iproxy 1024 54513 00008020-001A03CE1161002E
[2:12:26 PM] [FlutterRun] [Info] <== [  +10 ms] attempting to forward device port 54513 to host port 1025
[2:12:26 PM] [FlutterRun] [Info] <== [        ] executing: /usr/local/bin/iproxy 1025 54513 00008020-001A03CE1161002E
[2:12:26 PM] [FlutterRun] [Info] <== [   +6 ms] [Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize
[2:12:26 PM] [FlutterRun] [Info] <== [   +1 ms] attempting to forward device port 54513 to host port 1026
[2:12:26 PM] [FlutterRun] [Info] <== [        ] executing: /usr/local/bin/iproxy 1026 54513 00008020-001A03CE1161002E
// SNIP many more the same, with ascending port numbers
[2:12:28 PM] [FlutterRun] [Info] <== [+1006 ms] Forwarded port ForwardedPort HOST:1047 to DEVICE:54513
[2:12:28 PM] [FlutterRun] [Info] <== [        ] Forwarded host port 1047 to device port 54513 for Observatory
[2:12:28 PM] [FlutterRun] [Info] <== [{"event":"app.progress","params":{"appId":"b8195105-9883-440a-b157-6fdb138dd703","id":"1","progressId":null,"finished":true}}]
[2:12:28 PM] [FlutterRun] [Info] <== [   +9 ms] Connecting to service protocol: http://127.0.0.1:1047/ks53t3kcKQs=/
[2:12:28 PM] [FlutterRun] [Error] [ +157 ms] Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1047/ks53t3kcKQs=/ws
```

It seems like it eventually manages to forward the port, however the subsequent connection doesn't work. It'd be interesting to know why the first few calls all failed, but I don't know if you can easily just call them from the terminal if there's not already something listening on the device on that port (unfortunately I don't have access to an iOS device to test).

**Comment by quetool** [comment] 2019-09-03 12:09
@DanTup Many thanks for the explanation! It seems something is beyond my knowledge so I leave it for the experts :P

**Comment by BondarenkoStas** [comment] 2019-09-18 10:40
Taking into account https://github.com/flutter/flutter/issues/38971#issuecomment-527350165, that another issue is open, I think it's safe to close this one. If you disagree, please comment and I will re-open it right away.

**Comment by quetool** [comment] 2019-09-18 13:02
@BondarenkoStas  I am ok with that if you just provide me the other opened issue :P

**Comment by BondarenkoStas** [comment] 2019-09-18 13:45
@quetool My bad, I didn't pay proper attention and was too fast on closing ( https://github.com/flutter/flutter/issues/15072#issuecomment-531203185)

**Comment by iapicca** [comment] 2019-11-08 10:48
Hi @quetool 
could you please run 
`
 flutter channel stable
`
`
 flutter upgrade
`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by quetool** [comment] 2019-11-08 15:36
Hi, @iapicca, I was already on stable channel and with the last version, anyway here it is...
```
AlfredoMBPro:apperto alfredo$ flutter channel stable
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:  * [new branch]          CaseyHillers-patch-1 -> origin/CaseyHillers-patch-1
git:    1946fc4da..fbabb264e  dev                  -> origin/dev
git:    ee032f67c..ff95b14ad  master               -> origin/master
git:  * [new branch]          revert-42236-add_rally_to_examples -> origin/revert-42236-add_rally_to_examples
git:  * [new branch]          revert-43576-web_compiler -> origin/revert-43576-web_compiler
git:  * [new branch]          revert-44315-roll_branch -> origin/revert-44315-roll_branch
git:  * [new tag]             v1.10.15             -> v1.10.15
git: Already on 'stable'
git: Your branch is up to date with 'origin/stable'.
AlfredoMBPro:apperto alfredo$ flutter upgrade
Upgrading Flutter from /Users/alfredo/Desktop/flutter...
Updating c382b8e99..68587a091
 25 files changed, 574 insertions(+), 331 deletions(-)
Building flutter tool...

Upgrading engine...

Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (8 weeks ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale es-AR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (5 available)

• No issues found!
AlfredoMBPro:apperto alfredo$ 
```

This is `flutter doctor -v`
```
AlfredoMBPro:apperto alfredo$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale es-AR)
    • Flutter version 1.9.1+hotfix.6 at /Users/alfredo/Desktop/flutter
    • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alfredo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (5 available)
    • GT I9190             • 07ea470b                                 • android-arm • Android 7.1.2 (API 25)
    • SM G900H             • 4d0070a74a4821bd                         • android-arm • Android 6.0.1 (API 23)
    • iPhone Alfredo       • 00008020-001A03CE1161002E                • ios         • iOS 13.2
    • iPhone SE de Alfredo • 1ef594b0026a2a873a22f86bfa4e3e768b66f9ca • ios         • iOS 13.1.3
    • iPhone Xr12          • D9D6E659-D615-4AED-9023-8F542E15A7BC     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-0 (simulator)

• No issues found!
AlfredoMBPro:apperto alfredo$ 
```

This is what console shows me when I try to run with F5
```
Running "flutter pub get" in apperto...                             1,2s
Launching lib/main.dart on iPhone Alfredo in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 37S53BMSN9
Xcode build done.                                           41,6s
Checking for advertised Dart observatories...
Checking for available port on co.apperto.Appertomvp._dartobservatory._tcp.local
Checking for authentication code for co.apperto.Appertomvp._dartobservatory._tcp.local
Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1027/5R8Kg2DN5I8=/ws
Exited (sigterm)
```

A minimal code is useless, even with the example code in Flutter docs is enough...
Te issue appears only on a physical iPhone connected on WiFi.

**Comment by quetool** [comment] 2019-11-08 15:38
I am now realizing it doesn´t happen on my physical iPhone SE
```• iPhone SE de Alfredo • 1ef594b0026a2a873a22f86bfa4e3e768b66f9ca • ios         • iOS 13.1.3

**Comment by quetool** [comment] 2019-11-08 15:40
I am now realizing it doesn't happen on my physical iPhone SE
```
• iPhone SE de Alfredo • 1ef594b0026a2a873a22f86bfa4e3e768b66f9ca • ios         • iOS 13.1.3
```

But it does happen on my physical iPhone Xr
```
• iPhone Alfredo       • 00008020-001A03CE1161002E                • ios         • iOS 13.2
```

**Comment by DanTup** [comment] 2019-11-08 16:38
> Te issue appears only on a physical iPhone connected on WiFi.

By this do you mean if you disable WiFi the problem goes away? If so, I think this is the same as https://github.com/flutter/flutter/issues/41301.

**Comment by quetool** [comment] 2019-11-08 22:43
> > Te issue appears only on a physical iPhone connected on WiFi.
> 
> By this do you mean if you disable WiFi the problem goes away? If so, I think this is the same as #41301.

Yep, I mean that, but I thought it was clear. Anyway, that issue don´t have a solution either, I will try on monday with Mac and iPhone connected on two differents wifi

**Comment by DanTup** [comment] 2019-11-10 16:40
> Yep, I mean that, but I thought it was clear.

I just wanted to be sure since this issue was already closed and re-opened once :-)

I'll close this as a dupe of #41301 (I know this one was open first, but the title of that one is very clear and there's less comments to scan through to understand the issue).

I don't know if anyone has a solution yet, but if you find any more info that might be useful to track this down, please add it to #41301. Thanks!

**Closed by DanTup** 2019-11-10 16:40 UTC
Labels: ⌺‬ platform-ios

**Comment by quetool** [comment] 2019-11-11 21:31
@DanTup No problem, I have more info so I will comment that issue, thanks!
