### ISSUE TITLE
TextFields value is animated on rerender for no reason

### ISSUE THREAD

**Issue by konsultaner** [flutter/flutter#154243] opened 2024-08-28 09:48 UTC
### Steps to reproduce

1. Add a Textfield with an initial value into an ListView.
2. If ListView is long enough, scroll up and down.
3. When ListView rerenders the TextField the Value displayed in the TextField is animated 

### Expected results

No Animation or at least the possibility to turn it off.

### Actual results

This is what the animation looks like:

https://github.com/user-attachments/assets/99bca698-617b-4f74-87e2-4514d26536d3

### Flutter version:

```
Flutter 3.24.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5874a72aa4 (vor 8 Tagen) • 2024-08-20 16:46:00 -0500
Engine • revision c9b9d5780d
Tools • Dart 3.5.1 • DevTools 2.37.2
```

**Comment by jellynoone** [comment] 2024-08-28 10:33
I think this might be due to the `TextField` saving its scroll offset under the same slot as the outer `ListView`.

Consider adding a `PageStorageKey` on every `TextField` in the `ListView`.


Generally, the scroll positions on a page are saved to `PageStorage` this enables a `ScrollView` to restore its position. For instance, if you have two tabs and switch between them, the scroll position is maintained for each, if both scroll views have different `PageStorageKey`s.

This doesn't just apply to `ListView`s but all scrolling widgets.

The `TextField` internally uses a `ScrollView` so in case the text is too long it can be scrolled.

However, this also means that it tries to save its scroll offset. The `PageStorageKey` is then used to ensure different elements on the page save their offsets to different slots.

**Comment by huycozy** [comment] 2024-08-28 11:31
Hi @konsultaner 

Which platform are you seeing this issue? 

For the issue to be workable, it needs to be reproducible with a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include 3rd party plugins or complex production code. Please provide such a sample. Thanks!

**Comment by konsultaner** [comment] 2024-08-28 12:00
@jellynoone Your solution worked for me!
@huycozy I tried, but it seems to be related to my structure. As soon as i have it, I'll post it here.

**Comment by konsultaner** [comment] 2024-08-28 12:15
> Which platform are you seeing this issue?

Web, Android have both shown this issue.

**Comment by huycozy** [comment] 2024-09-11 03:43
If you think this is an implementation issue and can be solved with solution above, feel free to close this. I will add waiting label to keep the issue open in the meantime until you provide a minimal sample code for reproduction if you persist with this as a Flutter framework bug.

**Closed** 2024-10-02 05:09 UTC
Labels: waiting for customer response, in triage
