### ISSUE TITLE
Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到

### ISSUE THREAD

**Issue by ihad1102** [flutter/flutter#86330] opened 2021-07-13 02:12 UTC
Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = clients2.google.com, port = 62502
Oops; flutter has exited unexpectedly: "Invalid argument(s): No host specified in URI http://:62501/ws".
A crash report has been written to D:\AndroidProject\flutterproject\flutter_demo1\flutter_01.log.
[flutter_01.log](https://github.com/flutter/flutter/files/6805423/flutter_01.log)

**Comment by roohaani786** [comment] 2021-07-13 04:28
@ihad1102 please check your api server for debugging into what's the problem is. Although you are getting it while running a flutter project , this issue isn't related to flutter.

**Comment by maheshmnj** [comment] 2021-07-13 06:08
Hi @ihad1102,
Thanks for filing the issue, Could you please share the output of ```flutter doctor -v```, Along with the exact steps to reproduce the issue and possibly a [minimal reproducible code sample ](https://stackoverflow.com/help/minimal-reproducible-example) if that's applicable. This will help to better address the issue.
Thank you

**Comment by TahaTesser** [comment] 2021-08-06 15:23
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-08-06 15:23 UTC
