### ISSUE TITLE
Add EmptyView to ListView and GridView and keep scroll physics

### ISSUE THREAD

**Issue by ekasetiawans** [flutter/flutter#62159] opened 2020-07-23 21:25 UTC
## Use case
show another widget when ListView's or GridView's children are empty and keep scroll physics for RefreshIndicator.

## Proposal

currently, I have to create like this

```
...
List items = ...;
...
return 
  RefreshIndicator(,
  onRefresh: ...,
  child: Stack(
  alignment: Alignment.center,
  children: [
    Positioned.fill(
      child: ListView.builder(
      physics: AlwaysScrollablePhysics(),
       ...),
    ),
    if (items.isEmpty)
    Text("no data available"),
  ]
));
```

it would be easier if we could do this
```
return RefreshIndicator(
onRefresh: ...,
child: ListView.builder(
   physics: AlwaysScrollablePhysics(),
   emptyBuilder: () => Text("no data available"),
),);

```

we need to use AlwaysScrollablePhysics to make RefreshIndicator works when ListView's children are empty.

Thank you.

**Comment by darshankawar** [comment] 2020-07-24 06:21
Related to [41191](https://github.com/flutter/flutter/issues/41191)

**Comment by ekasetiawans** [comment] 2020-07-24 06:53
> Hi @ekasetiawans, Please see this [open](https://github.com/flutter/flutter/issues/41191) ticket. Does it sound similar to your request ?

oh, i didn't know that was already there.
thanks @darshankawar

**Comment by darshankawar** [comment] 2020-07-24 08:41
@ekasetiawans closing this ticket as duplicate of [41191](https://github.com/flutter/flutter/issues/41191) and I'd suggest you to follow-up there for updates.
Thanks.

**Closed by darshankawar** 2020-07-24 08:41 UTC
Labels: in triage
