### ISSUE TITLE
flutter run --debug

### ISSUE THREAD

**Issue by SteplerPaulo** [flutter/flutter#112291] opened 2022-09-23 17:48 UTC
Flutter crash report.

## command

flutter run --debug

## exception

FileSystemException: FileSystemException: Directory listing failed, path = 'C:\myapp\android\app\build\intermediates\flutter\prodDebug\flutter_assets\android\app\build\intermediates\flutter\devDebug\flutter_assets\android\app\build\intermediates\flutter\prodDebug\flutter_assets\android\app\build\intermediates\flutter\*' (OS Error: The system cannot find the path specified.
, errno = 3)

```
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:243:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#3      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:43:12)
#4      _AssetDirectoryCache.variantsFor (package:flutter_tools/src/asset.dart:1041:78)
#5      ManifestAssetBundle._parseAssetFromFile (package:flutter_tools/src/asset.dart:866:37)
#6      ManifestAssetBundle._parseAssets (package:flutter_tools/src/asset.dart:753:9)
#7      ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:261:54)
<asynchronous suspension>
#8      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:470:26)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```

## flutter doctor

```
[✓] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2006], locale en-PH)
    • Flutter version 3.3.2 on channel stable at D:\Tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (9 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Paulo\AppData\Local\Android\sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32630.192
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at C:\Users\Paulo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2006]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.42

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darshankawar** [comment] 2022-09-26 06:18
Closing this as duplicate of https://github.com/flutter/flutter/issues/106953

**Closed by darshankawar** 2022-09-26 06:18 UTC
Labels: in triage

**Comment by SteplerPaulo** [comment] 2022-09-26 10:53
For Window user run

> flutter clean
 
Delete android/app/build 

> dart pub get
> flutter pub get


and then try adding args into .vscode/launch.json file

> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Dart",
>             "type": "dart",
>             "request": "launch",
>             "program": "lib/main.dart",
>             "args": [
>                 "--flavor",
>                 "dev" //development or staging or production
>             ]
>         }
>     ]
>   }
