### ISSUE TITLE
Linux Web Framework tests often flake with timeouts

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/flutter#117538] opened 2022-12-22 16:35 UTC
Six out of the last 200 runs of the Linux Web Framework tests have flaked with a timeout:

https://ci.chromium.org/p/flutter/builders/prod/Linux%20Web%20Framework%20tests?limit=200

Here is one such example:

https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/28682/overview

Due to the intermittent nature of this issue, and how generic the failure is, this will be difficult to track down.

**Comment by bdero** [comment] 2023-03-22 19:28
We seem to currently be double digit for flakes on this builder now: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Web%20Framework%20tests?limit=200

It looks like we run some extremely heavy integration tests that use chrome (presumably headless), I haven't found any examples of hanging yet. Our options are probably between increasing the timeout, splitting out more shards, or running on faster hardware.

The most recent timeout: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/79692/overview

The step times out at 10 minutes, but there are other recent web_test-1 invocations that allow for 15 minutes on this step: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Production%20Engine%20Drone/79949/overview

No idea if the shards are deterministic order or not.

**Comment by keyonghan** [comment] 2023-03-22 20:57
These are caused by sub builds running on devicelab bots. Fix is https://flutter-review.googlesource.com/c/recipes/+/41040.

**Comment by keyonghan** [comment] 2023-03-22 23:04
Sub builds are on now host only bots as expected: https://chromium-swarm.appspot.com/task?id=612458155ae02f10&o=true&w=true

Closing.

**Closed by keyonghan** 2023-03-22 23:04 UTC
Labels: team: infra, P2, severe: flake
