### ISSUE TITLE
flutter doctor

### ISSUE THREAD

**Issue by majianch** [flutter/flutter#98462] opened 2022-02-15 01:42 UTC
I've come across a mistake when  run flutter doctor
HTTP host https://maven.google.com/ is not reachable. Reason: An error occurred while checking the HTTP host:

**Comment by icerking** [comment] 2022-02-15 02:27
我的也是这个问题

**Comment by darshankawar** [comment] 2022-02-15 08:30
Closing this as duplicate of https://github.com/flutter/flutter/issues/98170

**Closed by darshankawar** 2022-02-15 08:30 UTC
Labels: in triage
