### ISSUE TITLE
Canary versions of Android Studio are not supported by the Flutter plugin

### ISSUE THREAD

**Issue by dong-lufei** [flutter/flutter#120165] opened 2023-02-07 08:21 UTC
Android Studio Giraffe | 2022.3.1 Canary 2
Plugins:Flutter  72.0.4

Flutter 3.7.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7048ed95a5 (6 days ago) • 2023-02-01 09:07:31 -0800
Engine • revision 800594f1f4
Tools • Dart 2.19.1 • DevTools 2.20.1

**Comment by danagbemava-nc** [comment] 2023-02-07 08:53
Kindly see https://github.com/flutter/flutter-intellij/issues/6573#issuecomment-1397458295.

PS: The flutter intellij plugin lives in its own repo not on the main flutter repo. 

Closing from here as this is not a flutter issue and per the link shared above, this is by design.

**Closed by danagbemava-nc** 2023-02-07 08:53 UTC
Labels: in triage
