### ISSUE TITLE
On/off labels for CupertinoSwitch

### ISSUE THREAD

**Issue by Tridie2000** [flutter/flutter#36938] opened 2019-07-25 11:17 UTC
When we're using Cupertino controls in our apps, they should look and behave like the native components. The current implementation of a CupertinoSwitch / Switch.adaptive doesn't support the on/off labels like a UIKit UISwitch does.
![fullsizeoutput_36a](https://user-images.githubusercontent.com/24608795/61870446-6c08ce80-aede-11e9-9ed5-5e71a674b0b8.jpeg)

**Comment by HansMuller** [comment] 2019-07-25 15:15
CC @brandondiamond 

The switch visuals were updated yesterday - https://github.com/flutter/flutter/pull/36087. Did we miss something?

**Comment by Tridie2000** [comment] 2019-07-25 15:30
I’m using Flutter 1.7.8+hotfix.4. In the iOS accessibility settings there is this setting called on/off labels. This shows a little 0 or 1 indicating the enabled/disabled status of the switch. I guess this is a lot harder to implement than the new look of switches in iOS 13 but it would mean a lot to all the users that use this accessibility setting. 
![B89D2774-3119-46C7-B349-0BA4DC21A797](https://user-images.githubusercontent.com/24608795/61887391-cebf9180-af01-11e9-849d-b9e640c59f26.jpeg)
![E325A2B9-0D42-4D7B-ABDC-79C0B964E4CF](https://user-images.githubusercontent.com/24608795/61887392-cf582800-af01-11e9-8fef-1f0b09ad4ba1.jpeg)

**Comment by brandondiamond** [comment] 2019-07-25 15:50
Ah, very interesting. Do you happen to know whether these symbols are
universal or whether they’re locale dependent?

**Comment by jonahwilliams** [comment] 2019-07-25 17:28
Duplicate of https://github.com/flutter/flutter/issues/16395 (more details on that bug)

**Comment by jonahwilliams** [comment] 2019-07-25 17:28
Ahh wrong issue

**Comment by jonahwilliams** [comment] 2019-07-25 17:28
This https://github.com/flutter/flutter/issues/4830

**Comment by jonahwilliams** [comment] 2019-07-25 17:28
Duplicate of https://github.com/flutter/flutter/issues/4830

**Closed by jonahwilliams** 2019-07-25 17:28 UTC
Labels: f: cupertino, framework
