### ISSUE TITLE
widget.toStringShort() suppose to return widget's class name but instead return "Widget" in release mode, working fine in debug mode

### ISSUE THREAD

**Issue by chunlee-thong** [flutter/flutter#65160] opened 2020-09-03 09:08 UTC

**Comment by TahaTesser** [comment] 2020-09-03 11:20
Hi @chunlee-thong 
This is by design, debug will return more information 
Please check out this https://github.com/flutter/flutter/issues/56537#issuecomment-626785648
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-03 11:20 UTC

**Comment by CemenLangemec** [comment] 2021-07-21 03:08
Hi. everybody.
I  was  developing app  with Flutter.
Here, I  used  widget.toStringShort() function to compare to something.
In debug mode,  this is working well. so, all logic works.
But, in release mode, it is not working.
if  someone has some solution about this, please help me.
Thanks.
