### ISSUE TITLE
google sign in error only on flutter web Uncaught (in promise) Error: [object Object]

### ISSUE THREAD

**Issue by ShamanJaggia** [flutter/flutter#64411] opened 2020-08-23 12:31 UTC
Error reported by framework on line `await googleSignIn.signIn();`  - 

```
Uncaught (in promise) Error: [object Object]
    at Object.createErrorWithStack (errors.dart:245)
    at Object._rethrow (async_patch.dart:200)
    at async._AsyncCallbackEntry.new.callback (zone.dart:1175)
    at Object._microtaskLoop (schedule_microtask.dart:41)
    at _startMicrotaskLoop (schedule_microtask.dart:50)
    at async_patch.dart:166
```

The above error only occurs in flutter web on Flutter beta channel.

Here's an output of flutter doctor -v:
[✓] Flutter (Channel beta, 1.21.0-9.1.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-9.1.pre at /.../Development/flutter
    • Framework revision be9bc8cb39 (5 days ago), 2020-08-18 09:46:08 -0700
    • Engine revision 267070c17a
    • Dart version 2.10.0 (build 2.10.0-7.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /.../Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.135

• No issues found!

**Comment by darshankawar** [comment] 2020-08-24 09:26
Hi @ShamanJaggia,
There's similar open issue describing your case, [53745](https://github.com/flutter/flutter/issues/53745).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by darshankawar** [comment] 2020-08-25 05:53
@ShamanJaggia thanks and fair point, reopened.

**Comment by darshankawar** [comment] 2020-08-25 05:54
@ShamanJaggia,
Please provide a minimal complete reproducible code sample that shows the issue.

**Comment by ShamanJaggia** [comment] 2020-08-25 14:48
@darshankawar, 
here is the code sample, pretty standard i believe from various tutorials. You would though need to setup your own test firebase project and obtain google-services.json, enable google sign in etc. 
this is my index.html:-
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="tuturo">
  <meta name="google-signin-scope" content="profile email">
  <meta name="google-signin-client_id" content="....YOUR GOOGLE CLIENT ID....">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="favicon.png"/>

  <title>FlutterWeb</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>

<script src="https://apis.google.com/js/platform.js" async defer></script>

  <!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/7.18.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.18.0/firebase-auth.js"></script>
<!-- TODO: Add SDKs for Firebase products that you want to use
     https://firebase.google.com/docs/web/setup#available-libraries -->
<script src="https://www.gstatic.com/firebasejs/7.18.0/firebase-analytics.js"></script>

<script>
  // Your web app's Firebase configuration
  var firebaseConfig = {
    .... YOUR FIREBASE CONFIG ....
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  firebase.analytics();
</script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```

Following is my main.dart:-
```
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'auth_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'FlutterWeb',
      theme: ThemeData(
        primarySwatch: Colors.red,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: AuthService().authWidget(),
    );
  }
}
```

Following is my auth_service.dart:-
```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

class AuthService {
  GoogleSignIn googleSignIn;
  GoogleSignInAccount _currentUserAccount;
  FirebaseAuth _auth = FirebaseAuth.instance;

  // FirebaseUser user;

  get currentUserAccount => _currentUserAccount;

  AuthService() {
    googleSignIn = new GoogleSignIn(
      hostedDomain: "gmail.com",
      signInOption: SignInOption.standard,
      scopes: [
        'email',
        // 'https://www.googleapis.com/auth/contacts.readonly',
      ],
    );

    googleSignIn.onCurrentUserChanged
        .listen((GoogleSignInAccount account) async {
      _currentUserAccount = account;
      if (_currentUserAccount != null) {
        _signinToFirebaseWithGoogleAccount(_currentUserAccount);
      }
    });
    googleSignIn.signInSilently();
  }
  //Handle Authentication
  Widget authWidget() {
    return StreamBuilder<User>(
      stream: _auth.authStateChanges(),
      builder: (BuildContext context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(
            child: new Container(
              height: 50,
              width: 50,
              color: Colors.white,
              child: CircularProgressIndicator(),
            ),
          );
        } else {
          if (snapshot.hasData) {
            User user = snapshot.data;
            return Center(
             Container(
               child: Text('Logged In')
             ));
          } else {
            //user not logged in
            return Center(
             Container(
               child: Text('Not Logged In')
             ));
          }
        }
      },
    );
  }

  signOut() async {
    await _auth.signOut();
    if (googleSignIn != null) {
      await googleSignIn.disconnect();
    }
  }

  Future<bool> signInAnonymous() async {
    User user = (await _auth.signInAnonymously()).user;
    return true;
  }

  Future<bool> signInWithGoogle() async {
    await googleSignIn.signIn(); // <----getting ERROR HERE. same code works with android, but not in web.
    if (_currentUserAccount == null) return false;
    return true;
  }


  Future<void> _signinToFirebaseWithGoogleAccount(
      GoogleSignInAccount currentUserAccount) async {
    final GoogleSignInAuthentication googleAuth =
        await _currentUserAccount.authentication;
    final AuthCredential credential = GoogleAuthProvider.credential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );
    User user = (await _auth.signInWithCredential(credential)).user;
    print("Signed in user is ${user.email}");
  }
}
```

Hope this helps in reproducing the issue. Thanks.

**Comment by ShamanJaggia** [comment] 2020-08-25 14:50
> @ShamanJaggia,
> Please provide a minimal complete reproducible code sample that shows the issue.
@darshankawar, reverted with main code in above comment.

**Comment by darshankawar** [comment] 2020-08-26 06:38
Hi @ShamanJaggia,
Thanks for code sample. When do you exactly get the error ? Are you able to see the popup to select account ?
Also, can you please try the official [example](https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in_web) and see if you get same error with it too ?
Thanks.

**Comment by ShamanJaggia** [comment] 2020-08-26 20:46
> Hi @ShamanJaggia,
> Thanks for code sample. When do you exactly get the error ? Are you able to see the popup to select account ?
> Also, can you please try the official [example](https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in_web) and see if you get same error with it too ?
> Thanks.

**Comment by ShamanJaggia** [comment] 2020-08-26 21:04
Hi @darshankawar,  I have been through the latest official example for web and i am following it to the tee as far as i see it.
Just to give you a little more background, i have used older version of google_sign_in package before for flutter web successfully in production for now deprecated site. 
The code listed above is currently working in Android.
I am able to get the popup, and am able to select my sign account. As soon as i select the account, i get following error on java script browser console:-
```
errors.dart:163 Uncaught (in promise) Error: [object Object]
    at Object.createErrorWithStack (errors.dart:245)
    at Object._rethrow (async_patch.dart:200)
    at async._AsyncCallbackEntry.new.callback (zone.dart:1175)
    at Object._microtaskLoop (schedule_microtask.dart:41)
    at _startMicrotaskLoop (schedule_microtask.dart:50)
    at async_patch.dart:166
```
and following error on my vs code debug console:-
```
Error: [object Object]
    at Object.createErrorWithStack (http://localhost:5000/dart_sdk.js:4348:12)
    at Object._rethrow (http://localhost:5000/dart_sdk.js:37892:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:37886:13)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37718:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37724:13)
```
If you can confirm that this package (google_sign_in: ^4.5.3) is working for you on flutter web beta channel with dart sdk 2.9.1 (stable), i would be surprised and further glad if you share your working code for this.
I only raised this issue as a last resort, after going through lot of reported issues and debugging the code line by line.

**Comment by ShamanJaggia** [comment] 2020-08-26 21:19
Heres my screen recording of the error
[Error Screen Recording.zip](https://github.com/flutter/flutter/files/5132820/Error.Screen.Recording.zip)

**Comment by darshankawar** [comment] 2020-08-27 05:52
Thanks @ShamanJaggia for digging more into this.

**Comment by jessp01** [comment] 2020-11-06 22:33
Hello all,

Hate to be one of those that comment without adding more info but, I have the same issue and I see it's been some time since the last update. Any news or additional info that may help debug this which I can provide?

>   google_sign_in:
    dependency: "direct main"
    description:
      name: google_sign_in
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.5.5"

> $ flutter doctor -v
[✓] Flutter (Channel unknown, 1.20.3, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.20.3 at /opt/flutter
    • Framework revision 216dee60c0 (9 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/james/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.183

• No issues found!


Cheers,

**Comment by hillelcoren** [comment] 2021-03-15 15:11
I believe I'm seeing the same issue, in my tests it fails the first time but the succeeds the second time. This makes me think it may be related to #53745 mentioned above.

**Comment by huycozy** [comment] 2023-01-13 12:06
Hi @ShamanJaggia, @jessp01
This issue seems to have been fixed on the latest plugin version `google_sign_in: ^5.4.3` as I cannot reproduce it on the latest Flutter stable and master channels. See the demo below.

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/212316231-f8d5c915-280c-432d-99fa-6f428f202572.mov


</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.3.10 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (13 hours ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.54.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 12 (API 31)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[!] Flutter (Channel master, 3.7.0-20.0.pre.26, on macOS 13.0.1 22A400 darwin-x64, locale en-VN)
    • Flutter version 3.7.0-20.0.pre.26 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f7b444e117 (17 minutes ago), 2023-01-13 03:11:08 +0100
    • Engine revision 8aa26baa9d
    • Dart version 3.0.0 (build 3.0.0-119.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.0.1 22A400 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
</details>

I'll close this issue since it has already been fixed. If you still experience this issue, kindly leave a comment below and I will reopen this. Thank you!

**Closed by huycozy** 2023-01-13 12:06 UTC
Labels: severe: crash, plugin, p: first party, p: google_sign_in, has reproducible steps, P4, found in release: 1.21
