### ISSUE TITLE
Camera: Square aspect ratio in camera preview.

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [flutter/flutter#84337] opened 2021-06-10 09:25 UTC
camera : aspect ratio is currently set to as default aspect ratio given by camera and if we try to set another aspect ratio then it stretches the camera preview.

**Comment by darshankawar** [comment] 2021-06-10 11:12
Closing this as duplicate of https://github.com/flutter/flutter/issues/80513

**Comment by darshankawar** [comment] 2021-06-10 11:12
Also, similar issues are: https://github.com/flutter/flutter/issues/15953, https://github.com/flutter/flutter/issues/80393

**Closed by darshankawar** 2021-06-10 11:12 UTC
Labels: in triage
