### ISSUE TITLE
It is not possible to set the initial size of the window or its position, including a multi-monitor configuration, nor size constraints (Flutter 2.0.1 Desktop Windows - Beta Channel)

### ISSUE THREAD

**Issue by Josua2012** [flutter/flutter#77541] opened 2021-03-07 22:30 UTC
Hi,
It is necessary that flutter desktop has the possibility of putting constraints on the size of the windows, as well as being able to initially specify their position and size, and being able to retrieve or save these parameters from shared_preferences.
Thanks.
Regards,
Jose

**Comment by stuartmorgan** [comment] 2021-03-07 22:41
Duplicate of https://github.com/flutter/flutter/issues/30736

**Closed by stuartmorgan** 2021-03-07 22:41 UTC
