### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by joaowd** [flutter/flutter#27949] opened 2019-02-14 18:41 UTC
I'm getting this error when I try to deploy on the Android Simulator. Already tried the flutter clean, didn't work.
```
FAILURE: Build failed with an exception.
What went wrong:

Execution failed for task ':app:processDebugResources'.
 Android resource linking failed
  Output:  /Users/joaopalma/Documents/NexSo.Mobile/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/joaopalma/Documents/NexSo.Mobile/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/joaopalma/Documents/NexSo.Mobile/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:861: error: resource android:attr/fontVariationSettings not found.
  /Users/joaopalma/Documents/NexSo.Mobile/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:861: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
  Command: /Users/joaopalma/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/49bde82e2adcb152ec95ed61c5e73f62/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/joaopalma/Library/Android/sdk/platforms/android-27/android.jar\
          --manifest\
          /Users/joaopalma/Documents/NexSo.Mobile/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /Users/joaopalma/Documents/NexSo.Mobile/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/Users/joaopalma/Documents/NexSo.Mobile/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /Users/joaopalma/Documents/NexSo.Mobile/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
```

**Comment by zoechi** [comment] 2019-02-14 18:49
Duplcate of #27901

**Comment by zoechi** [comment] 2019-02-14 18:52
Duplicate of #27106

**Closed by zoechi** 2019-02-14 18:52 UTC
