### ISSUE TITLE
Github not closing linked issues of PRs merged by new `autosubmit` bot (?)

### ISSUE THREAD

**Issue by ditman** [flutter/flutter#106211] opened 2022-06-17 17:37 UTC
It seems that **the new `autosubmit` bot is not closing the related issues/PRs of the PRs it merges**, for example:

* Merged PR: https://github.com/flutter/flutter/pull/106072
* Didn't close: https://github.com/flutter/flutter/issues/103972

Another example:

* Merged PR: https://github.com/flutter/plugins/pull/5952
* Didn't close: https://github.com/flutter/flutter/issues/104062

In both cases, **I had linked the PR to the Issue before it was merged by the bot** (with Github's [keyword syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)), but in neither case the **auto-submit** bot closed the related Issue/PR.

The **previous auto-merge bot used to do this**, for example:

* Merged PR: https://github.com/flutter/plugins/pull/5963
* Automatically closed: https://github.com/flutter/flutter/issues/102741 and https://github.com/flutter/plugins/pull/5431

**Comment by ditman** [comment] 2022-06-17 17:53
This might be a Github issue :/

> When you merge a linked pull request into the default branch of a repository, its linked issue is automatically closed. For more information about the default branch, see "[Changing the default branch](https://docs.github.com/en/github/administering-a-repository/changing-the-default-branch)."

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by TahaTesser** [comment] 2022-07-15 13:25
Indeed, `autosubmit` isn't closing the issue when PR is merged, for instance, https://github.com/flutter/flutter/pull/106731

**Comment by bdero** [comment] 2022-07-21 20:15
Filed a GH [support ticket](https://support.github.com/ticket/personal/0/1714850) about the failed auto closures for linked issues. Not sure if the issue is visible to others but it's filed under the flutter org.

**Comment by bdero** [comment] 2022-07-21 20:16
Earliest known failure: https://github.com/flutter/flutter/pull/107435
Last known successful closure: https://github.com/flutter/flutter/pull/107396

**Comment by ditman** [comment] 2022-07-21 20:26
> Last known successful closure: https://github.com/flutter/flutter/pull/107396

@bdero that one seems to have been merged by a user, and not the `autosubmit` bot.

**Comment by bdero** [comment] 2022-07-21 20:29
The autosubmit bot is unrelated to the problem. GitHub automatically closes linked issues whether they're merged by a bot or not.

**Comment by bdero** [comment] 2022-07-21 20:31
Hmm, actually reading the bug more carefully, it does make make sense that the user probably has to have write permission... maybe that's the problem after all?

**Comment by bdero** [comment] 2022-07-21 20:33
It's happening on manual merges as well, so indeed I don't think it's related to the autosubmit bot. I think everyone who has permission to merge PRs has permission to edit bugs.

For example: https://github.com/flutter/flutter/pull/107328

**Comment by keyonghan** [comment] 2022-07-21 20:36
> Hmm, actually reading the bug more carefully, it does make make sense that the user probably has to have write permission... maybe that's the problem after all?

That's correct. All members already have write permission to issues.

**Comment by keyonghan** [comment] 2022-07-21 20:37
> It's happening on manual merges as well, so indeed I don't think it's related to the autosubmit bot. I think everyone who has permission to merge PRs has permission to edit bugs.
> 
> For example: #107328

This PR was landed to a release branch, and the auto fix works only when merging to the default branch.

**Comment by bdero** [comment] 2022-07-21 21:11
Ah, gotcha. In my list of repros there aren't any counterexamples. They're all either autosubmit merges or merges to something other than main.

**Comment by zanderso** [comment] 2022-07-25 17:40
@keyonghan This appears to still not be working. This isn't a show stopper, but it is pretty annoying since this used to work.

**Comment by godofredoc** [comment] 2022-07-25 19:46
Autosubmit bot permissions are now updated to allow commenting and closing bugs.

**Comment by keyonghan** [comment] 2022-07-25 20:08
Validated in https://github.com/flutter/cocoon/pull/2004, which auto closes https://github.com/flutter/flutter/issues/108300.

**Comment by keyonghan** [comment] 2022-07-25 20:10
Proactively marked as resolved. Please reopen if any one still sees the issues.

**Closed by keyonghan** 2022-07-25 20:10 UTC
Labels: team: infra, P3

**Comment by ditman** [comment] 2022-07-26 18:33
Totally missed this fix, thanks for the fix!!
