### ISSUE TITLE
camera takepicture function returning error and crashes app every time

### ISSUE THREAD

**Issue by kamleshwebtech** [flutter/flutter#75133] opened 2021-02-01 10:32 UTC
I am getting below error when i use "await camController.takePicture();" function:

```
I/flutter ( 3986): Error: camera initialized
I/RequestQueue( 3986): Repeating capture request cancelled.
I/RequestQueue( 3986): Repeating capture request set.
W/LegacyRequestMapper( 3986): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyRequestMapper( 3986): mapAeAndFlashMode - Ignore control.aeMode == ON_AUTO_FLASH;camera does not support it
W/LegacyRequestMapper( 3986): convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
I/art     ( 3986): Do partial code cache collection, code=60KB, data=61KB
I/art     ( 3986): After code cache collection, code=60KB, data=61KB
I/art     ( 3986): Increasing code cache capacity to 256KB
D/AndroidRuntime( 3986): Shutting down VM
E/AndroidRuntime( 3986): FATAL EXCEPTION: main
E/AndroidRuntime( 3986): Process: com.example.whatsupflutter, PID: 3986
E/AndroidRuntime( 3986): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
E/AndroidRuntime( 3986): 	at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:60)
E/AndroidRuntime( 3986): 	at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:55)
E/AndroidRuntime( 3986): 	at io.flutter.plugins.camera.Camera.runPictureCapture(Camera.java:552)
E/AndroidRuntime( 3986): 	at io.flutter.plugins.camera.Camera.access$1500(Camera.java:73)
E/AndroidRuntime( 3986): 	at io.flutter.plugins.camera.Camera$3.processCapture(Camera.java:510)
E/AndroidRuntime( 3986): 	at io.flutter.plugins.camera.Camera$3.onCaptureCompleted(Camera.java:442)
E/AndroidRuntime( 3986): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3986): 	at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
E/AndroidRuntime( 3986): 	at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
E/AndroidRuntime( 3986): 	at android.os.Handler.handleCallback(Handler.java:754)
E/AndroidRuntime( 3986): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 3986): 	at android.os.Looper.loop(Looper.java:165)
E/AndroidRuntime( 3986): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
E/AndroidRuntime( 3986): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3986): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/AndroidRuntime( 3986): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
I/Process ( 3986): Sending signal. PID: 3986 SIG: 9
Lost connection to device.
Exited (sigterm)
```

Please check and suggest what is the issue and solution? Thanks a lot.

**Comment by kamleshwebtech** [comment] 2021-02-01 10:34
I have already checked it with low, medium and high resolution on emulator and on real devices. Getting same issue every time. Please suggest. Thanks.

**Comment by TahaTesser** [comment] 2021-02-01 11:52
Hi @kamleshwebtech 
Can you please provide the details asked in https://github.com/flutter/flutter/issues/40519#issuecomment-770765774 and which device are you using?
Thank you

**Comment by gertdrui** [comment] 2021-02-02 13:00
I have the exact same issue, happening on almost all calls to takePicture (some work). This happens in both my local builds as well as builds ran in Bitrise

I'm using a Pixel 4

1. camera 0.7.0+1
2. flutter doctor:

[✓] Flutter (Channel stable, 1.22.6, on macOS 11.0.1 20B29 darwin-arm, locale en-EE)
    • Flutter version 1.22.6 at /Users/gertdrui/flutter
    • Framework revision 9b2d32b605 (11 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/gertdrui/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Pixel 4 (mobile) • 9B011FFAZ0013E • android-arm64 • Android 11 (API 30)

**Comment by amzahrani** [comment] 2021-02-09 15:42
Me to I am trying to figure what is the problem every time the app calls takePicture() the app crashes:
E/AndroidRuntime(17032): java.lang.NullPointerException: Attempt to invoke virtual method 'int io.flutter.embedding.engine.systemchannels.PlatformChannel$DeviceOrientation.ordinal()' on a null object reference

**Comment by JamesMasterman** [comment] 2021-02-09 22:59
I am also seeing this. Crashes nearly every time I call takePicture().

Stack trace as above

1. Using camera 0.7.0+2 (I was previously using 0.6.4+3 which didn't suffer from this issue)
2. Mainly testing on Samsung Galaxy S9+, but also see it on emulator with Pixel4 image.

Flutter doctor -v output as follows:
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-AU)
    • Flutter version 1.22.6 at /Users/jamesmasterman/Documents/Development/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jamesmasterman/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by ZiiwareJordanc** [comment] 2021-02-18 18:17
I see that a task was merged that says it fixes the crash, is there any sort of ETA on when this would be in an available version?

**Comment by sovaz1997** [comment] 2021-02-21 21:08
It seems I have such promlem too:

```
D/AndroidRuntime(18591): Shutting down VM
E/AndroidRuntime(18591): FATAL EXCEPTION: main
E/AndroidRuntime(18591): Process: com.example.app, PID: 18591
E/AndroidRuntime(18591): java.lang.NullPointerException: Attempt to invoke virtual method 'int io.flutter.embedding.engine.systemchannels.PlatformChannel$DeviceOrientation.ordinal()' on a null object reference
E/AndroidRuntime(18591): 	at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:58)
E/AndroidRuntime(18591): 	at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:53)
E/AndroidRuntime(18591): 	at io.flutter.plugins.camera.Camera.runPictureCapture(Camera.java:552)
E/AndroidRuntime(18591): 	at io.flutter.plugins.camera.Camera.access$1500(Camera.java:73)
E/AndroidRuntime(18591): 	at io.flutter.plugins.camera.Camera$3.processCapture(Camera.java:510)
E/AndroidRuntime(18591): 	at io.flutter.plugins.camera.Camera$3.onCaptureProgressed(Camera.java:450)
E/AndroidRuntime(18591): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureProgressed$2$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:627)
E/AndroidRuntime(18591): 	at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$7mSdNTTAoYA0D3ITDxzDJKGykz0.run(Unknown Source:8)
E/AndroidRuntime(18591): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(18591): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(18591): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(18591): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime(18591): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18591): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(18591): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process (18591): Sending signal. PID: 18591 SIG: 9
```

This was not on the emulator, but it did appear on a real device.
I would be glad if someone can solve it. Thanks!

**Comment by IonVillarreal** [comment] 2021-02-23 15:20
I have the same problem, after taking a photo several times

**Comment by IonVillarreal** [comment] 2021-02-23 15:57
after initializing the controller, I call the _await controller.lockCaptureOrientation()_ method

After that adjustment, I no longer got an error, can someone verify it?

**Comment by t-animal** [comment] 2021-02-24 15:11
I can confirm this problem exists, it also happened on a Nokia 7.2. Calling `await controller.lockCaptureOrientation()` fixed the problem. After I had this call there and confirming the problem was gone, I removed the call again for testing purposes (I thought maybe it had something to do with device orientation) and played around with the auto-rotate settings. Since then, I can't reproduce the problem any more, even with the call removed. Very mysterious.

**Comment by acoutts** [comment] 2021-03-01 23:27
Please try my PR here and see if it resolves your issue: https://github.com/flutter/plugins/pull/3651

**Comment by petost** [comment] 2021-03-03 10:43
For us, the crash only happened when the device was flat on the table, any kind of tilt, and the crash does not appear.

await controller.lockCaptureOrientation() fixed it for me as well, once I figured out that it should be used after initialize().

**Comment by lobachsvyatoslav** [comment] 2021-03-31 10:19
> after initializing the controller, I call the _await controller.lockCaptureOrientation()_ method
> 
> After that adjustment, I no longer got an error, can someone verify it?


await controller.lockCaptureOrientation() after initialize() fixed the problem for me too. Xiaomi Mi9 Lite

**Comment by Purvik** [comment] 2021-04-28 14:32
Faced same issue on Samsung device but App did not crashed but FIrebase Crashlytics captured this crash in Flutter Camera Module. 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int io.flutter.embedding.engine.systemchannels.PlatformChannel$DeviceOrientation.ordinal()' on a null object reference
       at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:58)
       at io.flutter.plugins.camera.DeviceOrientationManager.getMediaOrientation(DeviceOrientationManager.java:53)
       at io.flutter.plugins.camera.Camera.runPictureCapture(Camera.java:552)
       at io.flutter.plugins.camera.Camera.access$1500(Camera.java:73)
       at io.flutter.plugins.camera.Camera$3.processCapture(Camera.java:510)
       at io.flutter.plugins.camera.Camera$3.onCaptureProgressed(Camera.java:450)
       at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureProgressed$2$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:626)
       at android.hardware.camera2.impl.-$$Lambda$CameraCaptureSessionImpl$1$7mSdNTTAoYA0D3ITDxzDJKGykz0.run(:8)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7807)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
```

**Comment by chiuhol** [comment] 2021-06-17 06:51
> after initializing the controller, I call the _await controller.lockCaptureOrientation()_ method
> 
> After that adjustment, I no longer got an error, can someone verify it?

It works for me

**Comment by mariopepe** [comment] 2022-02-21 14:53
The issue is till here in Flutter 2.10.2 and camera ^0.9.4+14.

Adding `await controller.lockCaptureOrientation()` did not help.

```
camera device has encountered a serious error
E/CameraCaptureSession( 4786): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2350)
E/CameraCaptureSession( 4786): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1277)
E/CameraCaptureSession( 4786): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
E/CameraCaptureSession( 4786): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1114)
E/CameraCaptureSession( 4786): 	at io.flutter.plugins.camera.Camera.close(Camera.java:1121)
E/CameraCaptureSession( 4786): 	at io.flutter.plugins.camera.Camera$1.onError(Camera.java:302)
E/CameraCaptureSession( 4786): 	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1748)
E/CameraCaptureSession( 4786): 	at android.hardware.camera2.impl.CameraDeviceImpl.$r8$lambda$KBQCqQRdhVVn7uHI9Xdha6OqnsU(Unknown Source:0)
E/CameraCaptureSession( 4786): 	at android.hardware.camera2.impl.CameraDeviceImpl$$ExternalSyntheticLambda0.accept(Unknown Source:8)
E/CameraCaptureSession( 4786): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
E/CameraCaptureSession( 4786): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
E/CameraCaptureSession( 4786): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
E/CameraCaptureSession( 4786): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession( 4786): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession( 4786): 	at android.os.Looper.loopOnce(Looper.java:201)
E/CameraCaptureSession( 4786): 	at android.os.Looper.loop(Looper.java:288)
E/CameraCaptureSession( 4786): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by vietlinhtspt** [comment] 2022-05-31 04:13
I faced same issue.

**Comment by darshankawar** [comment] 2024-07-11 11:32
I tried the camera plugin example with latest stable version running on S10+ device in which I didn't get the reported behavior.

@kamleshwebtech Can you check if the reported error still persists at your end using latest camera plugin version and latest stable ? Looking at some of the above comments, it seemed to have resolved for them with the solution given.

**Closed** 2024-08-01 12:10 UTC
Labels: e: device-specific, platform-android, waiting for customer response, p: camera, package, P2, team-android, triaged-android
