### ISSUE TITLE
Support developing iOS extension targets

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#16092] opened 2018-03-30 05:42 UTC
Are they any docs on building an iOS extension using Flutter?

**Comment by s-bauer** [comment] 2018-03-30 11:39
All you need can be found here "https://flutter.io/developing-packages/".
For specific iOS Api documentation you can refer to apples docs https://developer.apple.com/documentation/

**Comment by long1eu** [comment] 2018-03-30 11:45
I'm talikng about this https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/index.html :D Not plugins.

**Comment by ugoArangino** [comment] 2018-05-15 07:07
I am also interested in this. Using FlutterViewController (and adding the Frameworks) in an extension leads to a crash.

**Comment by mrgrauel** [comment] 2019-01-11 10:48
Any news on this one?

**Comment by zoechi** [comment] 2019-01-11 10:55
@mrgrauel 
Using "add reaction" on the initial comment would increase priority while `+1` comments are rather pointless and cause lots of people to get notified for no reason.
To get notified yourself use the [Subscribe] button to the top right instead.

**Comment by Hixie** [comment] 2019-01-16 00:43
Latest documentation is: https://developer.apple.com/app-extensions/

**Comment by andreasunterhuber** [comment] 2019-03-21 13:55
@long1eu hi! Try to remove all the "Other Linker Flags" within the Target (your Extension) in "Build Settings" (see screen). This caused the linker problems in my project. Removing them, solved it! You don't have to touch the Podfile at all. 

![flutter-ios-extension](https://user-images.githubusercontent.com/5103661/54756819-46468280-4be9-11e9-802b-eee1f5b29cb6.png)

**Comment by alcsan** [comment] 2019-04-03 17:27
> @long1eu and @ugoArangino hi! Try to remove all the "Other Linker Flags" within the Target (your Extension) in "Build Settings" (see screen). This caused the linker problems in my project. Removing them, solved it! You don't have to touch the Podfile at all.
> 
> ![flutter-ios-extension](https://user-images.githubusercontent.com/5103661/54756819-46468280-4be9-11e9-802b-eee1f5b29cb6.png)

Hi Andreas!
Did you actually manage to run Flutter in an App Extension? Or it is just a Flutter app + native App Extension?

**Comment by LinusU** [comment] 2019-04-11 18:29
I'm actively pursuing this in a project I'm currently working on. By using the [Add-to-App method](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) I've managed to start a Flutter view from within my extension.

However, the view is simply black, and connecting to the debugger from the observatory, I'm greeted by the following message:

```text
Paused until embedder makes the isolate runnable.
```

I think I'm missing some important step that tells the Flutter isolate to start running, that is probably coming from the FlutterAppDelegate. (since this is an app extension, I don't have an app delegate, only a ViewController)

Will keep updating here as I try to move further with this...

**Comment by alcsan** [comment] 2019-06-02 17:19
> Will keep updating here as I try to move further with this...

@LinusU Any updates on this?

**Comment by alcsan** [comment] 2019-06-02 17:19
> I'm actively pursuing this in a project I'm currently working on. By using the [Add-to-App method](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) I've managed to start a Flutter view from within my extension.
> 
> However, the view is simply black, and connecting to the debugger from the observatory, I'm greeted by the following message:
> 
> ```
> Paused until embedder makes the isolate runnable.
> ```
> 
> I think I'm missing some important step that tells the Flutter isolate to start running, that is probably coming from the FlutterAppDelegate. (since this is an app extension, I don't have an app delegate, only a ViewController)
> 
> Will keep updating here as I try to move further with this...
> 
> my code:
> ```swift
> import AuthenticationServices
> import MobileCoreServices
> import UIKit
> 
> import Flutter
> import FlutterPluginRegistrant
> 
> @objc(CredentialProviderViewController)
> 
> class CredentialProviderViewController: ASCredentialProviderViewController {
>     var flutterEngine: FlutterEngine!
>     var flutterViewController: FlutterViewController!
> 
>     override func prepareCredentialList(for serviceIdentifiers: [ASCredentialServiceIdentifier]) {
>         flutterEngine = FlutterEngine(name: "io.flutter", project: nil)
>         flutterEngine.run(withEntrypoint: nil)
> 
>         GeneratedPluginRegistrant.register(with: self.flutterEngine)
> 
>         flutterViewController = FlutterViewController(engine: flutterEngine, nibName: nil, bundle: nil)!
>         view.addSubview(flutterViewController.view)
>     }
> }
> ```

@LinusU Any updates on this?

**Comment by LinusU** [comment] 2019-06-03 09:40
Unfortunately not, at the moment our app extension is written using only native code and views 😞 

Would love to have support for Flutter here though!

**Comment by jmagman** [comment] 2019-09-18 01:58
Even if add-to-app for app extensions worked and the extension lifecycle was hooked up, I believe it would be rejected from the App Store:
```
ld: warning: linking against a dylib which is not safe for use in application extensions: test_notification_extensions/flutterapp/.ios/Flutter/App.framework/App
ld: warning: linking against a dylib which is not safe for use in application extensions: test_notification_extensions/flutterapp/.ios/Flutter/engine/Flutter.framework/Flutter
```
https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fapplication-extension

**Comment by spkersten** [comment] 2019-10-24 08:53
We managed to run dart code from an extension by starting `FlutterEngine` and using the platform channel (binaryMessenger) to communicate. (We only wanted to reuse business logic in dart.) However, that only worked for a non-flutter app. Trying the same for a flutter app, CocoaPods complained about pods with the same name: Flutter.framework and App.framework. Using only a single Flutter.framework is possible, but the "App.framework" name is hardcoded in several places: xcode_backend.sh, pod helper.rb, <prj>.podspec, AppFrameworkInfo.plist (and maybe others we missed). Also the CFBundleIdentifier of both App.framework is hardcoded, while it must be unique per bundle.

**Comment by jmagman** [comment] 2019-10-24 23:36
> We managed to run dart code from an extension by starting `FlutterEngine` and using the platform channel (binaryMessenger) to communicate. (We only wanted to reuse business logic in dart.) However, that only worked for a non-flutter app. Trying the same for a flutter app, CocoaPods complained about pods with the same name: Flutter.framework and App.framework. Using only a single Flutter.framework is possible, but the "App.framework" name is hardcoded in several places: xcode_backend.sh, pod helper.rb, .podspec, AppFrameworkInfo.plist (and maybe others we missed). Also the CFBundleIdentifier of both App.framework is hardcoded, while it must be unique per bundle.

Having two copies of Flutter and the App (compiled dart code) would make the app huge.  Probably the Flutter app and extension would need to import that once (two Podfile targets using the same pod) with different entry points into the App.framework.  I'm just thinking out loud--the Flutter tooling doesn't support this use-case at the moment.

**Comment by csells** [comment] 2019-10-29 23:39
Adding @matthew-carroll @xster for their thoughts.

**Comment by matthew-carroll** [comment] 2019-10-29 23:50
Seems like an interesting use-case, but I'll defer to @jmagman on the technical feasibility as well as timeline.

**Comment by Albert221** [comment] 2021-04-14 13:09
https://github.com/flutter/flutter/issues/16092#issuecomment-475237976

@andreasunterhuber this is the solution to my problem that I've spent few hours on! Thank you!

Flutter team, I beg you to add this issue to some flutter.dev website on App Extensions. Adding `firebase_*` pub packages prevented my app with App Extension to compile. Removing the `firebase_*` flags with their corresponding `-framework` pair successfully resolved my problem.

**Comment by jmagman** [comment] 2021-04-14 17:48
@Albert221 I don't think you or @andreasunterhuber are talking about using Flutter in an extension, as @alcsan pointed out (and I missed when I last looked at this issue).

> Did you actually manage to run Flutter in an App Extension? Or it is just a Flutter app + native App Extension?

And that's not really related to this feature request to use Flutter in an app extension.  I'd actually like to take a look at what you were seeing.  We want non-Flutter app extensions to be able to be added to Flutter apps without any project files workarounds like the one you figured out.

Would you mind filing a new issue with your original `flutter build` or `run` command with the `--verbose` flag, completely fill out the issue template, and @ me in it?  I'm wondering if part of your problem wasn't already fixed with https://github.com/flutter/flutter/pull/78592 in 2.0.4.

**Comment by izouxv** [comment] 2021-09-01 04:54
you can craete a duplicate of app. named "buildFlutterPKG", and then edit this app scheme , scheme -> build -> targets ->add (select the build flutterpkg sheme), and set the buildFlutterPkg to the first line. and then disable the "Parallelize build"
build the app 
it's done

**Comment by alcsan** [comment] 2021-10-04 09:31
@jmagman Any updates on this issue? Is there a chance that it will be fixed soon if it was added to "iOS Developer Experience"?

**Comment by jmagman** [comment] 2021-10-04 17:09
No updates at this time.

**Comment by alcsan** [comment] 2021-10-05 16:28
> you can create a duplicate of app scheme. named "buildFlutterPKG", remove all extension config of buildFlutterPKG and then edit this app scheme , scheme -> build -> targets ->add (select the build flutterpkg sheme), and set the buildFlutterPkg to the first line. and then disable the "Parallelize build" build the app it's done

Is it a way to use Flutter in an App Extension?

**Comment by jmagman** [comment] 2021-10-05 23:46
It really depends what kind of extension target you want to add.  For example, I wrote up how to add an App Clip extension https://flutter.dev/docs/development/platform-integration/ios-app-clip and https://github.com/flutter/flutter/issues/60029
But unfortunately you can't ship it because the app size grows over 10MB https://github.com/flutter/flutter/issues/71098

So it may be possible depending on what you're doing, but you need to figure out how to only embed the Flutter framework once (and link against it in the extension), and to have different entry points in your dart app (App.framework) for your app vs the extension, and set up the build settings per target to point to the different entry points.  We have zero documentation for it.

**Comment by gatzsche** [comment] 2021-12-02 20:42
We developed Audanika, a serious music app in Flutter. Many of our customers are asking for AUV3 support. Is there someone here from Google, I could talk about? 

https://medium.com/@audanika/help-us-to-implement-auv3-support-for-audanika-ea325870fa6a

**Comment by jmagman** [comment] 2021-12-02 21:22
@gatzsche Maybe I don't understand your use case, but why do you need to use Flutter in your AUv3 extension?  Open `ios/Runner.xcworkspace` and add your extension target as you would in a normal Xcode project.  If you need to present UI or subclass `AUAudioUnit` in your Flutter app, that could be a good use case for a Flutter plugin.

**Comment by gatzsche** [comment] 2021-12-04 05:30
> If you need to present UI or subclass AUAudioUnit in your Flutter app, that could be a good use case for a Flutter plugin.

That is exactly what I want to do. Based on this thread I had doubt that showing a Flutter View Controller in an extension might work. But I will try out. 

@jmagman Is there some documentation? If not, how could I contribute to create some?

**Comment by jmagman** [comment] 2021-12-06 17:27
> Based on this thread I had doubt that showing a Flutter View Controller in an extension might work.

I see, then you do what to use Flutter in your extension.  By "you need to present UI or subclass AUAudioUnit in your Flutter app, that could be a good use case for a Flutter plugin" I meant in YOUR app that already embeds Flutter and your dart code, not in the extension used by other apps.

You would need to link against and embed the Flutter frameworks in the extension, as well as the framework that contains your compiled Dart code.  The tooling doesn't support this and there's no docs, but it can be done manually.  As I said, I wrote an example of how to do this with App Clip extensions, though that exact use case didn't work because it hit the 10MB upload limit: https://docs.flutter.dev/development/platform-integration/ios-app-clip.

Your best bet is probably to break out of Flutter for this use case and implement your extension entirely in Swift/Obj-C in Xcode.

**Comment by gatzsche** [comment] 2021-12-28 10:18
@jmagman Hi Jenn, thanks for your answer. Currently, it looks that Audio Unit Extensions might work with Flutter. The flutter code is executed and also the widget build functions are executed. The only thing: The FlutterViewController does not show the flutter content. 

Would you mind checking out this example:
https://github.com/gatzsche/flutter-audio-unit-extension-experiments

At the end, you should see the flutter default app in the extension. But it is not shown. Also, no error is output.

Should I create a separate issue for that?

**Comment by jmagman** [comment] 2022-01-04 22:53
You should create a separate issue.  Or maybe someone can help on StackOverflow.

**Comment by Shawn-sudo** [comment] 2022-05-22 22:34
I've heard that there's memory limit [(15-16mb)](https://stackoverflow.com/questions/37361261/ios-app-extensions-maximum-memory-budget#:~:text=raised%20to%2015MB%20since%20iOS%2010%20Beta%202.), which is less than the memory required to even preload flutter engine [(22mb)](https://docs.flutter.dev/development/add-to-app/performance#:~:text=22%20MB%20and%20860%20ms%20to%20prewarm%20on%20iOS.%20260%20ms%20of%20it%20is%20a%20blocking%20call%20on%20the%20main%20thread.)

**Comment by vanlooverenkoen** [comment] 2022-06-10 06:01
> @long1eu and @ugoArangino hi! Try to remove all the "Other Linker Flags" within the Target (your Extension) in "Build Settings" (see screen). This caused the linker problems in my project. Removing them, solved it! You don't have to touch the Podfile at all.
> 
> ![flutter-ios-extension](https://user-images.githubusercontent.com/5103661/54756819-46468280-4be9-11e9-802b-eee1f5b29cb6.png)

Isn't this breaking something else? I am working with flavors. in my main app & extension. 
- I can run DebugDev on my device without any problems.
- I can't run DebugDev on my simulator
- I can't run DebugAlpha, DebugBeta, DebugProd on my device/simulator

When I remove the `Other linker flags` it does work. But why are they added if they are not used? Isn't this breaking something else?

**Comment by tomduncalf** [comment] 2022-10-23 20:21
In case anyone is still interested, I was able to get a simple Flutter AUv3 running with some hacks to Flutter 🎉

I compiled Flutter from source with the `-fappliation-extension` clang flag to detect any code which can't be used in an app extension, and then removed all references to `[UIApplication sharedApplication]`, which is forbidden in app extensions. I'm not sure if this was actually causing it to fail loading or not but would presumably fail the App Store checks – I still do get a warning about `Linking against a dylib which is not safe for use in application extensions` but it sounds like this can be shown even when the usage is actually safe. I'm hoping to submit a simple AUv3 to the App Store to see if it passes the real checks.

I was then was able to see an error in the console `Failed to find assets path for "Frameworks/App.framework/flutter_assets"` when loading the AUv3 – I'm not sure if this was only visible because my local build of Flutter was a debug build, or if the changes to remove `sharedApplication` references meant it could get further in loading. It turns out that if you are in an app extension, `[NSBundle mainBundle]` points to the `.appex` inside the bundle rather than the top level bundle, and so Flutter was not able to locate the assets [here](https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm#L44-L52). 

I added a hack into that bit of code to use the parent directory if we are in an app extension (from [StackOverflow](https://stackoverflow.com/questions/26189060/get-the-main-app-bundle-from-within-extension)) and it seems to work! 🎉

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/5458070/197416131-3d1e742b-d4e1-40dd-ba7e-a9a7f713efb0.png">

I'll continue working on this and document how I get on, and will see if I can create a PR for Flutter with the changes that I had to make – if they're not suitable for merging as they are, they are fairly simple and minimal, so it should be possible for anyone interested to compile Flutter themselves locally with the changes applied.

**Comment by oliverbytes** [comment] 2022-10-23 20:44
> In case anyone is still interested, I was able to get a simple Flutter AUv3 running with some hacks to Flutter 🎉
> 
> I compiled Flutter from source with the `-fapplication-extension` `clang` flag added to the `gn` config, to detect any code which can't be used in an app extension, and then removed all references to `[UIApplication sharedApplication]`, which is forbidden in app extensions. I'm not sure if this was actually causing it to fail loading or not, but would presumably cause an app to fail the App Store API usage checks. 
> 
> I still do get a warning about `Linking against a dylib which is not safe for use in application extensions` in the parent app, but it sounds like this can be shown even when the usage is actually safe. I'm hoping to submit a simple AUv3 to the App Store to see if it passes the real checks.
> 
> I was then was able to see a new error in the console, `Failed to find assets path for "Frameworks/App.framework/flutter_assets"`, when loading the AUv3 – I'm not sure if this was only visible because my local build of Flutter was a debug build, or if the changes to remove `sharedApplication` references meant it could get further in loading. It turns out that if you are in an app extension, `[NSBundle mainBundle]` points to the `.appex` inside the bundle rather than the top level bundle, and so Flutter was not able to locate the assets [here](https://github.com/flutter/engine/blob/main/shell/platform/darwin/ios/framework/Source/FlutterDartProject.mm#L44-L52). 
> 
> I added a hack into that bit of code to use the parent directory if we are in an app extension (from [StackOverflow](https://stackoverflow.com/questions/26189060/get-the-main-app-bundle-from-within-extension)) and it seems to work! 🎉
> 
> <img width="1071" alt="image" src="https://user-images.githubusercontent.com/5458070/197416131-3d1e742b-d4e1-40dd-ba7e-a9a7f713efb0.png">
> 
> I'll continue working on this and document how I get on, and will see if I can create a PR for Flutter with the changes that I had to make – if they're not suitable for merging as they are, they are fairly simple and minimal, so it should be possible for anyone interested to compile Flutter themselves locally with the changes applied.

Great discovery! Excited for more updates to this 👏

**Comment by gatzsche** [comment] 2022-10-24 07:08
That is so good news. Cannot express how happy I'm to hear this. 🤩🤩🤩🤩🤩🤩

**Comment by tomduncalf** [comment] 2022-10-24 07:18
Hey @gatzsche, I was going to reach out to you about this as your repo for this was helpful in figuring out how to set up an AUv3 inside the runner app, so thanks for that :)

My plan here is to create an integration between JUCE and Flutter, so you can build a JUCE plugin with a Flutter UI, which I think would be a nice combo for a lot of of music software in terms of Flutter’s ease of building nice custom UIs etc. I’ve done a lot of work with JUCE and React Native and web UIs, so have some ideas how to make this work well. The core of the solution will be reusable without JUCE though. 

The main hurdle I can see to getting support for this merged into Flutter is that my understanding is the Flutter.framework would need to contain no references to `sharedApplication` at all to pass the App Store checks - just not calling it at runtime isn’t enough - so this would mean a separate distribution of the framework for extensions. Not sure if there’s a precedent for this already? Maybe the Flutter team will have some ideas. In any case, compiling it locally is not too painful for now!

**Comment by gatzsche** [comment] 2022-10-29 18:42
Hey, @tomduncalf thanks for that details. 
Do I understand right, that `Flutter.framework` must not contain a reference to `sharedApplication`, but such a reference is needed to make an extension work?

Can you add some references so I can understand the problem better?

**Comment by tomduncalf** [comment] 2022-10-30 16:55
@gatzsche in order for the app extension to be accepted on to the App Store, my understanding is there can be no references to `sharedApplication` in the linked frameworks. Flutter uses this in various places to hook into various lifecycle events, device rotation, font size etc., but in an app extension context most/all of this is irrelevant anyway and it works fine with it commented out/otherwise removed. 

However, I don't think that this is the cause of a Flutter app extension failing to start up, it's just something that needs to happen in order for an app built with it to be accepted – the cause of the app not starting is that the assets path is incorrect when running as an app extension, because `[NSBundle mainBundle]` returns the path of the `.appex` inside the bundle, rather than the top level bundle, so when Flutter constructs the assets path from this, it's incorrect. You can see the fixes I did here: https://github.com/tomduncalf/engine/pull/1/files

I will write this up in more detail when I find time, but it might not be for a few weeks so if you want to play around with it for now, you can compile Flutter from source using my branch. It works great, I've got a basic AUv3 plugin working with a Flutter UI and a JUCE backend, communcating between the two using channels!

**Comment by stamhe** [comment] 2023-01-22 10:05
> @gatzsche in order for the app extension to be accepted on to the App Store, my understanding is there can be no references to `sharedApplication` in the linked frameworks. Flutter uses this in various places to hook into various lifecycle events, device rotation, font size etc., but in an app extension context most/all of this is irrelevant anyway and it works fine with it commented out/otherwise removed.
> 
> However, I don't think that this is the cause of a Flutter app extension failing to start up, it's just something that needs to happen in order for an app built with it to be accepted – the cause of the app not starting is that the assets path is incorrect when running as an app extension. This is because `[NSBundle mainBundle]` returns the path of the `.appex` inside the bundle, rather than the top level bundle, so when Flutter constructs the assets path from this, it's incorrect. You can see the fixes I did here: https://github.com/tomduncalf/engine/pull/1/files
> 
> I will write this up in more detail when I find time, but it might not be for a few weeks so if you want to play around with it for now, you can compile Flutter engine from source using my branch. It works great, I've got a basic AUv3 plugin working with a Flutter UI and a JUCE backend, communcating between the two using channels!

greet work....

**Comment by kaciula** [comment] 2023-01-26 17:06
@tomduncalf Do you happen to have some step-by-step documentation on how to implement an iOS extension in Flutter? I would really appreciate it.

**Comment by sophanox** [comment] 2023-02-02 10:22
hey @tomduncalf - thanks for the info so far. just wondering if you were able to ever write this up in the end? thanks!

**Comment by gatzsche** [comment] 2023-02-02 12:19
@sophanox @kaciula 
In https://github.com/gatzsche/flutter-audio-unit-extension-experiments you find steps to implement an app extension. In that code, the `FlutterViewController` did not show up. With https://github.com/tomduncalf/engine/pull/1/files @tomduncalf  shows how to fix that.

I did not yet apply @tomduncalf's solution to my code. But both together should give a running app extension.

**Comment by leighajarett** [comment] 2023-02-15 15:39
Hi! Im working on some new docs and including the steps @tomduncalf mentioned. Tom - I was wondering if you can create a PR on the Flutter engine (we'll close it, but this will give us a stable link to use in the docs)?

Feel free to add comments to the docs PR if there are pieces missing that you would like included: 

https://github.com/flutter/website/pull/8265

**Comment by tomduncalf** [comment] 2023-02-15 21:55
Hey all, I'm afraid I've not had time to revisit this since my original post, the project kind of fizzled out!

@leighajarett I'll see if I can find my changes and send them over!

**Comment by tomduncalf** [comment] 2023-02-25 16:00
@leighajarett you can see the changes I made to get flutter to compile here:

https://github.com/tomduncalf/engine/commit/581a4170717907c8ee882872190c4c2e3202c35a (this would need doing properly, I just commented out a load of stuff)
and
https://github.com/tomduncalf/engine/commit/d31c18b5ac0ed0441e7793347c5d87927dbc1dd0

Let me know if I can share anything else useful!

**Comment by cyanglaz** [comment] 2023-11-14 18:15
The Flutter Engine can be build to support extension starting from 3.16.0. There is also a Flutter.xcframework that supports extension under <path_to_flutter>/bin/cache/artifacts/engine/ios/extension_safe/Flutter.xcframework.

See this [doc](https://docs.google.com/document/d/1mWpg1qmCGWG1RreFrOI8-Y3p9usV50MHsECbeoQzDHk/edit) for an example on how to use such framework to build share extension with Flutter. 
The guide document on flutter website will be available in the future after https://github.com/flutter/website/pull/9698 lands.

**Closed by cyanglaz** 2023-11-14 18:15 UTC
Labels: c: new feature, platform-ios, tool, engine, customer: crowd, customer: amplify, t: xcode, P1, team-ios, triaged-ios, multiteam-retriage-candidate
