### ISSUE TITLE
Bottom of emojis are not displayed in Channel beta 1.21.0-9.2.pre but there is no problem in Channel beta 1.20.2

### ISSUE THREAD

**Issue by officer47p** [flutter/flutter#65174] opened 2020-09-03 13:33 UTC
Bottom of emojis are not displayed in Channel beta 1.21.0-9.2.pre but there is no problem in Channel beta 1.20.2

**Channel beta, 1.21.0-9.2.pre:**
![Screenshot (80)](https://user-images.githubusercontent.com/40776589/92121102-258ae080-ee0f-11ea-9d76-8c79fa8cd972.png)

**Channel beta, 1.20.2:**
![Screenshot (81)](https://user-images.githubusercontent.com/40776589/92121354-6be03f80-ee0f-11ea-921e-1a8c42149d25.png)

**Code for that part:**
![Screenshot (82)](https://user-images.githubusercontent.com/40776589/92121596-b2359e80-ee0f-11ea-8332-7f71d8f31f87.png)

**Flutter doctor -v output:** 
```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-9.2.pre at D:\flutter
    • Framework revision 81a45ec2e5 (7 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\offic\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.48.2)
    • VS Code at C:\Users\offic\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-09-03 14:30
Hi @officer47p 
Can you please provide your `flutter run --verbose` and a complete reproducible minimal code sample (not screenshot)
Thank you

**Comment by officer47p** [comment] 2020-09-04 19:28
Hi Taha,
Sorry about the late reply, [here](https://github.com/officer47p/project-management) is my repo.
I'm gonna send the `flutter run --verbose` results once I got my computer.
Thanks

**Comment by TahaTesser** [comment] 2020-09-07 07:45
Hi @officer47p 
Please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) not a production code to better the address, isolate the code that causes the issue

Using this minimal code sample,  couldn't reproduce the issue

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text(
            'No Done Task To Show\n😀',
            style: TextStyle(
              color: Colors.black,
              fontFamily: 'Ubuntu',
            ),
            textAlign: TextAlign.center,
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.6 19G2021, locale
    en-GB)
    • Flutter version 1.21.0-9.2.pre at /Users/tahatesser/Code/flutter_beta
    • Framework revision 81a45ec2e5 (10 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)   • EUYTFEUSQSRGDA6D                     • android-arm64
      • Android 10 (API 29)
    • iPhone 11 (mobile) • 73130414-6DF8-4E37-B9AF-F81FA0F9068B • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • Web Server (web)   • web-server                           • web-javascript
      • Flutter Tools
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 85.0.4183.83

• No issues found!

```

</details> 

Thank you

**Comment by TahaTesser** [comment] 2020-10-14 14:19
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-10-14 14:19 UTC
Labels: in triage
