### ISSUE TITLE
Execution failed for task ':cloud_firestore:verifyReleaseResources' when build release apk

### ISSUE THREAD

**Issue by zanecidan** [flutter/flutter#27385] opened 2019-02-01 04:24 UTC
I'm getting this error when running 'flutter build apk'. I can run debug without problem. This looks similar to #26287 but I couldn't solve it with the same solution. I've already migrated my app to AndroidX via Android Studio migration tool.

Error log:
```
Execution failed for task ':cloud_firestore:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  C:\My Projects\ehs_mobile_app\ehs_mobile_app\build\cloud_firestore\intermediates\res\merged\release\values\values.xml:276: error: resource android:attr/fontVariationSettings not found.
  C:\My Projects\ehs_mobile_app\ehs_mobile_app\build\cloud_firestore\intermediates\res\merged\release\values\values.xml:277: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

flutter doctor -v
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.0.0 at C:\src\flutter\flutter_windows_v0.5.1-beta\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Chin Ying Jie\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.25.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by nemoryoliver** [comment] 2019-02-04 03:18
make sure all your plugins are updated and have migrated to android x as well.. some plugins haven't updated yet

**Comment by zanecidan** [comment] 2019-02-04 09:21
After manually set the version of multiple plugins, it compiles now. I was using "any" version in the pubspec.yaml file, wonder why it wasn't using the correct androidx version.

**Comment by nemoryoliver** [comment] 2019-02-04 09:30
Happy to hear! I always use the latest version number instead of 'any'. I think it's better so you also know exactly which version you use and so you track changes to the package

**Comment by mklim** [comment] 2019-02-06 02:33
Closing as a duplicate of #27106.

**Closed by mklim** 2019-02-06 02:33 UTC
