### ISSUE TITLE
Flutter won't run on real ios device ( iPhone X - 13.3.1)

### ISSUE THREAD

**Issue by DariusBuhai** [flutter/flutter#50602] opened 2020-02-11 21:40 UTC
Flutter does not work on my iOS device (iPhone X).

When I run using 'flutter run' it keeps compiling ( up to 'Installing and launching...' ) and opening a blank app for like a second.

```
Automatically signing iOS for device deployment using specified development team
in Xcode project: T7F892A6HV
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           3.5s
 └─Compiling, linking and signing...                         7.5s
Xcode build done.                                           13.8s
Installing and launching...                                             
(This is taking an unexpectedly long time.)       ⣽
```

When I run my app using Xcode, it opens a blank app, and I receive this error message:

```
dyld`__abort_with_payload:
0x1013975dc <+0>:  mov    x16, #0x209
0x1013975e0 <+4>:  svc    #0x80
->  0x1013975e4 <+8>:  b.lo   0x101397600               ; <+36>     #Thread 1: signal SIGABRT
0x1013975e8 <+12>: stp    x29, x30, [sp, #-0x10]!
0x1013975ec <+16>: mov    x29, sp
0x1013975f0 <+20>: bl     0x101395be8               ; cerror_nocancel
0x1013975f4 <+24>: mov    sp, x29
0x1013975f8 <+28>: ldp    x29, x30, [sp], #0x10
0x1013975fc <+32>: ret    
0x101397600 <+36>: ret    
```
and:

```
dyld: Library not loaded: @rpath/Flutter.framework/Flutter
Referenced from: /private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Runner
Reason: no suitable image found.  Did find:
/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter'

/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter'

/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter: stat() failed with errno=1
/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter'

/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter: stat() failed with errno=1
/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter'

/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter: stat() failed with errno=1
/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter'

/private/var/containers/Bundle/Application/57467581-3BC4-4097-AA4A-717D2AA9BF93/Runner.app/Frameworks/Flutter.framework/Flutter: stat() failed with errno=1
```
Flutter doctor:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76,
locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)


• No issues found!
```

iOS version: 13.3.1

MacOs version: Catalina 10.15.3

Important notice: It works on my iPad or on a Simulator ( iOS and Android ).

**Comment by DariusBuhai** [comment] 2020-02-11 22:04
So I found out that no flutter apps work on my ios device.
There are 2 possible issues:
 1) Flutter fails to work on ios 13.3.1
 2) My phone is retarded

**Comment by jmagman** [comment] 2020-02-11 22:09
Duplicate of https://github.com/flutter/flutter/issues/49504.

**Closed by jmagman** 2020-02-11 22:09 UTC

**Comment by chenyongze** [comment] 2020-02-16 14:32
yes
Library not loaded: @rpath/Flutter.framework/Flutter

**Comment by theguymeyer** [comment] 2020-02-19 05:06
Hi, has this been resolved... I am running into the same issue

**Comment by jmagman** [comment] 2020-02-19 05:11
Please see the duplicate. This is an iOS issue and is not specific to Flutter.

**Comment by DariusBuhai** [comment] 2020-02-19 11:07
> 

Hello Darius, You may be correct here. There does seem to be a bug in the process. I have done some research and we do not have any more information to this issue. I would advise to submit a bug report so our engineers can have a closer look at this issue.   https://developer.apple.com/bug-reporting/ | Hello Darius, You may be correct here. There does seem to be a bug in the process. I have done some research and we do not have any more information to this issue. I would advise to submit a bug report so our engineers can have a closer look at this issue.   https://developer.apple.com/bug-reporting/ | Hello Darius, You may be correct here. There does seem to be a bug in the process. I have done some research and we do not have any more information to this issue. I would advise to submit a bug report so our engineers can have a closer look at this issue.   https://developer.apple.com/bug-reporting/
-- | -- | --
Hello Darius, You may be correct here. There does seem to be a bug in the process. I have done some research and we do not have any more information to this issue. I would advise to submit a bug report so our engineers can have a closer look at this issue.   https://developer.apple.com/bug-reporting/ | Hello Darius, You may be correct here. There does seem to be a bug in the process. I have done some research and we do not have any more information to this issue. I would advise to submit a bug report so our engineers can have a closer look at this issue.   https://developer.apple.com/bug-reporting/
Hello Darius, You may be correct here. There does seem to be a bug in the process. I have done some research and we do not have any more information to this issue. I would advise to submit a bug report so our engineers can have a closer look at this issue.   https://developer.apple.com/bug-reporting/

Just received this from Apple, event though I just bought a paid developer account

**Comment by DariusBuhai** [comment] 2020-02-19 11:08
Hello Darius, You may be correct here. There does seem to be a bug in the process. I have done some research and we do not have any more information to this issue. I would advise to submit a bug report so our engineers can have a closer look at this issue.   https://developer.apple.com/bug-reporting

Just received this from Apple, even though I just bought a paid developer account

**Comment by jmagman** [comment] 2020-02-19 18:15
@DariusBuhai If you have a paid developer account, you should be able to use the non-Personal Team provisioning profile to sign your app.  If you're seeing a crash with that, please file a new issue.

**Comment by mpzadmin** [comment] 2020-03-03 21:54
This bug is related to iOS 13.3.1, I tested it on two same device with iOS 13.3 and iOS 13.3.1
Problem just happened with iOS 13.3.1

**Comment by jmagman** [comment] 2020-03-03 22:34
@mpzadmin You are hitting https://github.com/flutter/flutter/issues/49504#issuecomment-592767041
