### ISSUE TITLE
Failed to establish connection with the application instance in Chrome.

### ISSUE THREAD

**Issue by mayankhardiya** [flutter/flutter#54169] opened 2020-04-07 05:43 UTC
This can happen if the websocket connection used by the web tooling is unable to correctly establish a connection, for example due to a firewall.

**Comment by TahaTesser** [comment] 2020-04-07 07:57
Duplicate of [#49482](https://github.com/flutter/flutter/issues/49482)

**Closed by TahaTesser** 2020-04-07 07:57 UTC

**Comment by mayankhardiya** [comment] 2020-04-09 07:09
but this error occurs every time when i run my code ???
