### ISSUE TITLE
[web] Keyboard opens in every tap after typing on TextField. Channel master on iOS

### ISSUE THREAD

**Issue by Bilonik** [flutter/flutter#87118] opened 2021-07-27 16:30 UTC
## Steps to Reproduce

<details> 
<summary>minimal code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //  final wordPair = WordPair.random();
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Column(
            children: [
              TextField(
                autofillHints: [AutofillHints.email],
                style: TextStyle(fontSize: 20, color: Colors.black),
                decoration: InputDecoration(
                  hintStyle: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 20,
                      color: Colors.black),
                  hintText: "Email",
                ),
              ),
              TextField(
                autofillHints: [AutofillHints.password],
                style: TextStyle(fontSize: 20, color: Colors.black),
                decoration: InputDecoration(
                  hintStyle: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 20,
                      color: Colors.black),
                  hintText: "Password",
                ),
              ),
              TextButton(child: Text("Submit"), onPressed: null)
            ],
          ),
        ),
      ),
    );
  }
}
``` 

</details>

<details>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.4.0-5.0.pre.205, on macOS 11.5.1 20G80 darwin-x64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.58.2)
[✓] VS Code (version 1.59.0-insider)
[✓] Connected device (2 available)
```

</details>

@TahaTesser  #84817 

https://user-images.githubusercontent.com/8235588/127192093-46ef4247-df7c-452b-bd91-8c115defaf22.MP4

**Comment by TahaTesser** [comment] 2021-07-28 10:46
Hi @Bilonik 
I just tried with default `flutter build web` on the latest master on iOS 14.7 Safari, no issue


https://user-images.githubusercontent.com/48603081/127309759-ca54c2f1-44d1-424f-959f-b7be86bb77d4.MP4


<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel master, 2.5.0-2.0.pre.46, on macOS 12.0 21A5294g
    darwin-x64, locale en-GB)
    • Flutter version 2.5.0-2.0.pre.46 at /Users/tahatesser/Code/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f4f170dd2 (74 minutes ago), 2021-07-28 02:32:08 -0700
    • Engine revision 3cc37d3b4d
    • Dart version 2.14.0 (build 2.14.0-358.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Android Studio (version 4.2)
    • Android Studio at /Users/tahatesser/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.0 21A5294g darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

**Comment by Bilonik** [comment] 2021-07-28 14:49
Hi @TahaTesser ,

After typing -> Press Done in the keyboard -> Touch anywhere on the screen (Not on textfield) -> It will pop up the keyboard. 

Just updated to latest flutter master 2.5.0-2.0.pre.47 and deploy (https://fir-quickstart-30f7f.web.app) for you to try.

Thanks.

**Comment by TahaTesser** [comment] 2021-07-29 07:33
Hi  @Bilonik 

> After typing -> Press Done in the keyboard -> Touch anywhere on the screen (Not on textfield) -> It will pop up the keyboard.

I can reproduce the issue with these steps and ti is already reproduced in https://github.com/flutter/flutter/issues/85759#issuecomment-883643457 before PR from https://github.com/flutter/flutter/issues/84817 we merged and the issue exist on current beta too

Closing as duplicate of https://github.com/flutter/flutter/issues/85759

**Closed by TahaTesser** 2021-07-29 07:33 UTC
Labels: in triage
