### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65. ios18 and macOS 15

### ISSUE THREAD

**Issue by d4rk-lucif3r** [flutter/flutter#150688] opened 2024-06-24 09:41 UTC
## Command
```
flutter run --machine --start-paused -d 00008110-0001358A3468401E --devtools-server-address http://127.0.0.1:9100/ --target /Users/arshanwar/Projects/med-assist/lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1269:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2584:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:225:14)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:618:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 3.22.0-18.0.pre.48, on macOS 15.0 24A5264n darwin-arm64, locale en-IN)
    • Flutter version 3.22.0-18.0.pre.48 on channel master at /Users/arshanwar/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f9933b6994 (8 weeks ago), 2024-04-27 01:41:24 -0400
    • Engine revision 20fb62ba14
    • Dart version 3.5.0 (build 3.5.0-105.0.dev)
    • DevTools version 2.35.0-dev.8

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/arshanwar/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 16A5171c
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.91.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.91.20240529

[✓] Connected device (4 available)
    • Arsh’s iPhone (mobile)          • 00008110-0001358A3468401E • ios            • iOS 18.0 22A5282m
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A5264n darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A5264n darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.63
    ! Error: Browsing on the local area network for Arsh’s iPhone2. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5dcb86f68f239346676ceb1ed1ea385bd215fba1
### Plugins
camera-0.11.0+1
camera_android_camerax-0.6.5+2
camera_avfoundation-0.9.16
camera_web-0.3.3
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+1
firebase_auth-5.1.0
firebase_auth_web-5.12.2
firebase_core-3.1.0
firebase_core_web-2.17.2
firebase_messaging-15.0.1
firebase_messaging_web-3.8.9
flutter_native_splash-2.4.0
flutter_plugin_android_lifecycle-2.0.19
flutter_tts-4.0.2
fluttertoast-8.2.6
google_sign_in-6.2.1
google_sign_in_android-6.1.23
google_sign_in_ios-5.7.6
google_sign_in_web-0.12.4+1
image_picker-1.1.2
image_picker_android-0.8.12+1
image_picker_for_web-3.0.4
image_picker_ios-0.8.12
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
package_info_plus-8.0.0
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sign_in_with_apple-6.1.1
sign_in_with_apple_web-2.1.0
speech_to_text-6.6.2
speech_to_text_macos-1.1.0
wakelock_plus-1.2.5

**Comment by huycozy** [comment] 2024-06-24 10:59
Closing this as a duplicate of https://github.com/flutter/flutter/issues/150131. Please follow up on it for updates.

**Closed by huycozy** 2024-06-24 10:59 UTC
Labels: in triage
