### ISSUE TITLE
AnimatedContainer is not working on Flutter Web on Release mode

### ISSUE THREAD

**Issue by limonadev** [flutter/flutter#65358] opened 2020-09-08 00:37 UTC
## Steps to Reproduce

1. Create a new Flutter project on Master/Dev channel with web support.
2. Replace the `main.dart` with [this](https://gist.github.com/limonadev/d4f32cecbc62dfb13ff2c4486b904385).
3. Run `flutter channel master && flutter upgrade && flutter clean && flutter run -d web --release`

**Expected results:**

![captured (1)](https://user-images.githubusercontent.com/16759478/92421712-8ed85f80-f13f-11ea-91af-4c376ea0c26a.gif)

**Actual results:** 

![captured](https://user-images.githubusercontent.com/16759478/92421645-40c35c00-f13f-11ea-9140-570e62db303e.gif)

<details>
  <summary>Logs</summary>

## Verbose

[  +88 ms] executing: [/home/ademir/BetaFlutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +25 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e10bdbbd9de69a79101d8e79030532ee2be58b89
[        ] executing: [/home/ademir/BetaFlutter/] git tag --points-at HEAD
[  +10 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] executing: [/home/ademir/BetaFlutter/] git describe --match *.*.* --first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.22.0-9.0.pre-88-ge10bdbbd9
[   +6 ms] executing: [/home/ademir/BetaFlutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/ademir/BetaFlutter/] git ls-remote --get-url origin
[   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +30 ms] executing: [/home/ademir/BetaFlutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +31 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +10 ms] executing: /home/ademir/Android/Sdk/platform-tools/adb devices -l
[  +28 ms] List of devices attached
[   +3 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +154 ms] Generating /home/ademir/random_tests/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +52 ms] Launching lib/main.dart on Web Server in release mode...
[  +55 ms] Generating /home/ademir/random_tests/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[   +2 ms] Compiling lib/main.dart for the Web...
[   +2 ms] Initializing file store
[   +2 ms] Done initializing file store
[  +32 ms] Skipping target: gen_localizations
[   +9 ms] Skipping target: web_entrypoint
[ +426 ms] Skipping target: dart2js
[  +66 ms] Skipping target: web_release_bundle
[  +23 ms] Skipping target: web_service_worker
[        ] Persisting file store
[   +5 ms] Done persisting file store
[  +11 ms] Compiling lib/main.dart for the Web... (completed in 0,6s)
[   +1 ms] lib/main.dart is being served at http://localhost:40451
[        ] The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
[   +3 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".

## Flutter doctor

[✓] Flutter (Channel master, 1.22.0-10.0.pre.88, on Linux, locale es_PE.UTF-8)
    • Flutter version 1.22.0-10.0.pre.88 at /home/ademir/BetaFlutter
    • Framework revision e10bdbbd9d (hace 6 horas), 2020-09-07 11:40:03 -0700
    • Engine revision ac8b9c4c52
    • Dart version 2.10.0 (build 2.10.0-86.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/ademir/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /opt/google/chrome/chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.83 unknown

• No issues found!

</details>

**Comment by darshankawar** [comment] 2020-09-08 06:44
Hi @limonadev,
I tried your code sample on latest beta and it works as expected.

[65358.mov.zip](https://github.com/flutter/flutter/files/5186521/65358.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.2 19C57, locale
    en-US)
    • Flutter version 1.21.0-9.2.pre at
      /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision 81a45ec2e5 (11 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

 
[✓] Connected device (3 available)            
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      85.0.4183.83

! Doctor found issues in 1 category.
```

</details>

Can you switch to latest beta and see if it works for you ?
Thanks.

**Comment by darshankawar** [comment] 2020-09-08 06:53
Hi @limonadev,
I tried your code sample on latest beta in release mode and was able to see the expected behavior.

[65358_rel.mov.zip](https://github.com/flutter/flutter/files/5186565/65358_rel.mov.zip)

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Mac OS X 10.15.2 19C57, locale
    en-US)
    • Flutter version 1.21.0-9.2.pre at
      /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision 81a45ec2e5 (11 days ago), 2020-08-27 14:14:33 -0700
    • Engine revision 20a9531835
    • Dart version 2.10.0 (build 2.10.0-7.3.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

 
[✓] Connected device (3 available)            
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      85.0.4183.83

! Doctor found issues in 1 category.
```

</details>

Can you switch to latest beta and see if it works for you ?
Thanks.

**Comment by limonadev** [comment] 2020-09-08 14:01
In beta channel the `AnimatedContainer` works as expected. Just to report the problem on dev/master channels.

**Comment by darshankawar** [comment] 2020-09-09 06:11
Issue replicable on latest master in release mode, but works fine in debug mode.

[65358_master_rel.mov.zip](https://github.com/flutter/flutter/files/5192939/65358_master_rel.mov.zip) 


[65358_latest_master.mov.zip](https://github.com/flutter/flutter/files/5192938/65358_latest_master.mov.zip)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.107, on Mac OS X 10.15.2 19C57,
    locale en-US)
    • Flutter version 1.22.0-10.0.pre.107 at
      /Users/deeptibelsare/Documents/Fluttersdk/flutter
    • Framework revision 54ade88365 (61 minutes ago), 2020-09-08 22:08:57 -0700
    • Engine revision d1d848e842
    • Dart version 2.10.0 (build 2.10.0-98.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeptibelsare/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/deeptibelsare/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/deeptibelsare/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.2 19C57
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      85.0.4183.83

! Doctor found issues in 1 category.
```

</details>

**Comment by ferhatb** [comment] 2020-09-09 18:10
Verified that it is the same BoxBorder crash as in Duplicate of https://github.com/flutter/flutter/issues/63740. P2 Dart team working on fix.

**Closed by ferhatb** 2020-09-09 18:10 UTC
Labels: a: animation, a: release, f: material design, found in release: 1.22, framework, has reproducible steps, platform-web

**Comment by rydmike** [comment] 2020-09-09 18:32
@darshankawar Good to see that others have noticed similar issue as the case
https://github.com/flutter/flutter/issues/63740

And thanks @ferhatb for working on it in https://github.com/dart-lang/sdk/issues/43366
I also think that issue https://github.com/flutter/flutter/issues/63740 is related to this issue even if no borders are involved in the example.

I have noticed some strange behavior on some other implicit animated widgets (like AnimatedSwitcher) as well and also animated theme changes are acting up sometimes.

Could it be possible that null checks are incorrectly optimized out also for other Flutter lerp use cases than just this border case and that this is causing issues elsewhere too?
