### ISSUE TITLE
Possible mistake in a code snippet in Flutter Codelab: Get to know Firebase

### ISSUE THREAD

**Issue by DanGalkin** [flutter/flutter#116065] opened 2022-11-27 09:44 UTC
On step 5. Add RSVP functionality: the 5th code snippet about updating the HomePage widget: Consumer<ApplicationState> is wrapping twice: I believe it is excessive.
<img width="489" alt="Screenshot_2" src="https://user-images.githubusercontent.com/4963513/204128766-7ab639d7-cc39-4648-a81c-95363c3426e0.png">

**Comment by iapicca** [comment] 2022-11-27 10:46
possible dupe of https://github.com/flutter/flutter/issues/116051

**Comment by DanGalkin** [comment] 2022-11-27 11:29
@iapicca I think this mistake shouldn't influence the work of a program, but it is confusing in terms of studying Flutter and this codelab particularly.

**Comment by exaby73** [comment] 2022-11-28 09:20
Hello @DanGalkin. Can you confirm that the code works with only one `Comsumer` widget?

**Comment by DanGalkin** [comment] 2022-11-28 14:51
Yes, either of them.

**Comment by exaby73** [comment] 2022-11-29 06:06
Thanks for the input. I'll label this issue for visibility by the team

**Comment by maheshmnj** [comment] 2023-01-10 00:04
cc: @domesticmouse

**Comment by domesticmouse** [comment] 2023-01-10 01:16
PTAL @miquelbeltran

**Comment by miquelbeltran** [comment] 2023-01-11 12:28
The code in the repo seems correct to me: https://github.com/flutter/codelabs/blob/main/firebase-get-to-know-flutter/step_05/lib/home_page.dart it does not wrap the whole Widget with a `Consumer`.

The error seems to be just in the codelab md file.

I'll correct that error on my PR as well: https://github.com/flutter/codelabs/pull/1333

**Closed** 2023-02-02 22:35 UTC
Labels: d: codelabs, p: firebase, documentation, has reproducible steps
