### ISSUE TITLE
Engine -> Framework roll failing on super_editor customer tests

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#146506] opened 2024-04-09 14:31 UTC
Starting with the engine roll here https://github.com/flutter/flutter/pull/146483, which contains only the Dart roll here https://github.com/flutter/engine/pull/51980, the super_editor customer tests started failing in presubmit like here https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8751160061603811569/+/u/run_test.dart_for_customer_testing_shard_and_subshard_None/stdout, with the error message:

```
| Resolving dependencies...
| Because super_editor depends on example_docs any which doesn't exist (could not find package example_docs at https://pub.dev/), version solving failed.
Processing ./../../bin/cache/pkg/tests/registry/super_editor.test...
```

I took a look through the repo at the pinned commit, and couldn't find any pubspec files that mentioned the example_docs package: https://github.com/superlistapp/super_editor/tree/bcba72823a3c21336960f0ac40a73d68d9034623.

cc @chinmaygarde incoming engine sheriff

**Comment by jason-simmons** [comment] 2024-04-09 15:37
This is a Dart SDK regression affecting `dart fix` starting with https://dart.googlesource.com/sdk/+/409fa2c19e044f11dcd050924f8f6632d9142b82

With that change, if you run `dart fix` in https://github.com/superlistapp/super_editor/tree/bcba72823a3c21336960f0ac40a73d68d9034623 it will add an `example_docs: any` line to `super_editor/pubspec.yaml`.  This causes errors when running `pub get`.

@pq

**Comment by srawlins** [comment] 2024-04-09 16:05
CC @keertip @bwilkerson

**Comment by pq** [comment] 2024-04-09 16:15
Thanks for all the context @jason-simmons! A follow-up question:

> With that change, if you run dart fix in https://github.com/superlistapp/super_editor/tree/bcba72823a3c21336960f0ac40a73d68d9034623 

Is `super_editor` the working directory when `dart fix` is run or is it being run from a parent directory?

**Comment by jason-simmons** [comment] 2024-04-09 16:25
When this happens `dart fix` is being run from the `super_editor` subdirectory
(https://github.com/superlistapp/super_editor/tree/main/super_editor - one level down from the root of the repository)

**Comment by aam** [comment] 2024-04-09 16:46
>  Should I go ahead and do a revert of my change to the Dart SDK to keep you rolling?

Reverts are preferred because they keep dart sdk rolls smaller, easier to analyze in case of any other failures.

**Comment by pq** [comment] 2024-04-09 17:00
Revert: https://dart-review.googlesource.com/c/sdk/+/362000

Tracking issue: https://github.com/dart-lang/sdk/issues/55413

**Comment by chinmaygarde** [comment] 2024-04-09 18:42
The revert has landed. May I unpause the roller?

**Comment by chinmaygarde** [comment] 2024-04-09 18:57
The following reverts have landed and I'm unpausing the roller:

* https://github.com/dart-lang/sdk/commit/cd2c566bcf2263e93bef877443a784f3afe35549
* https://github.com/dart-lang/sdk/commit/5f05c279c9c97383c68e4a12df7fdc078f9f3285

**Comment by IchordeDionysos** [comment] 2024-04-10 14:16
Those changes have landed on the dev branch 
![image](https://github.com/flutter/flutter/assets/10195482/d9d26a4c-90e6-4842-bb16-0b9a2cc36970)
Can the autoroller be enabled again? 😌

**Comment by chinmaygarde** [comment] 2024-04-10 21:06
Yes! Things are rolling now.

**Closed by chinmaygarde** 2024-04-10 21:06 UTC
Labels: dependency: dart, P0, team-engine
