### ISSUE TITLE
Putting a `Navigator` widget in which has a `CustomScrollView` in the child of `NestedScrollView`

### ISSUE THREAD

**Issue by hosseinhadi** [flutter/flutter#84718] opened 2021-06-16 17:53 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
Just change the `main.dart` file according to the following :
```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: MyHomePage(),
  ));
}

class MyHomePage extends StatelessWidget {
  MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    Widget scrollView = Material(
      child: NestedScrollView(
        physics: BouncingScrollPhysics(),
        headerSliverBuilder: (context, innerScrolled) => <Widget>[
          SliverOverlapAbsorber(
            handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
            sliver: SliverAppBar(
              pinned: true,
              stretch: true,
              title: Text('username'),
              expandedHeight: 325,
              flexibleSpace: Stack(
                children: <Widget>[
                  Positioned.fill(
                    child: Placeholder(),
                  ),
                ],
              ),
            ),
          ),
        ],
        body: Builder(
          builder: (context) => Navigator(
            onGenerateRoute: (settings) => MaterialPageRoute(
              builder: (context) => CustomScrollView(
                slivers: <Widget>[
                  SliverOverlapInjector(
                    handle: NestedScrollView.sliverOverlapAbsorberHandleFor(
                      context,
                    ),
                  ),
                  SliverFixedExtentList(
                    delegate: SliverChildBuilderDelegate(
                      (_, index) => Text('not working'),
                      childCount: 100,
                    ),
                    itemExtent: 25,
                  )
                ],
              ),
            ),
          ),
        ),
      ),
    );
    Widget content = scrollView;
    return content;
  }
}

```
3. Just run the code.

**Expected results:** 
The expected result is to minimize the sliver app bar first , and then scrolling the `CustomScrollView` (bottom of screen). This is a very common scenario for example in the web design in which you want the whole screen to be as a `NestedScrollView` and you want to change some portion of screen to a new page while the other main sections (like Appbar) remains unchanged just like this Github page in which has an appbar and a changable content in the middle of the page.
This could be named properly as **Persistent Appbar in `NestedScrollView`**.
My expected result is what will be the result of removing the `Navigator` from the above code, I mean if you change the above code to this :
```
@override
  Widget build(BuildContext context) {
    Widget scrollView = Material(
      child: NestedScrollView(
        physics: BouncingScrollPhysics(),
        headerSliverBuilder: (context, innerScrolled) => <Widget>[
          SliverOverlapAbsorber(
            handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
            sliver: SliverAppBar(
              pinned: true,
              stretch: true,
              title: Text('username'),
              expandedHeight: 325,
              flexibleSpace: Stack(
                children: <Widget>[
                  Positioned.fill(
                    child: Placeholder(),
                  ),
                ],
              ),
            ),
          ),
        ],
        body: Builder(
          builder: (context) =>
              /*Navigator(
            onGenerateRoute: (settings) => MaterialPageRoute(
              builder: (context) => */
              CustomScrollView(
            slivers: <Widget>[
              SliverOverlapInjector(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(
                  context,
                ),
              ),
              SliverFixedExtentList(
                delegate: SliverChildBuilderDelegate(
                  (_, index) => Text('not working'),
                  childCount: 100,
                ),
                itemExtent: 25,
              )
            ],
          ),
        ),
      ),
      /* ),
      ),*/
    );
    Widget content = scrollView;
    return content;
  }
```
you would get the desired result.

**Actual results:** 
As you would see the bottom of the page scrolls up independently of the appbar. If you had removed the `Navigator` widget while the child being remained , you would see that first the appbar collapses and then the `CustomScrollView` being scrolled up.

<details>
  <summary>Logs</summary>

```
This issue does not need the details of run.
```

```
Analyzing bug...
No issues found! (ran in 4.3s)

```

```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
    • Flutter version 2.2.2 at C:\src\flutter
    • Framework revision d79295af24 (5 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Hossein\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.9.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.9.31129.286
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.0)
    • VS Code at C:\Users\Hossein\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.985]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.66

• No issues found!

```

</details>

**Comment by nt4f04uNd** [comment] 2021-06-17 08:20
Looks like it's a duplicate of https://github.com/flutter/flutter/issues/80239

**Comment by darshankawar** [comment] 2021-06-17 11:17
@hosseinhadi 
Check https://github.com/flutter/flutter/issues/80239 as it describes similar case as yours. Please follow-up in it for further updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-06-17 11:17 UTC
Labels: in triage

**Comment by hosseinhadi** [comment] 2021-06-17 11:44
Thanks sir.

It's a very important and common issue and is a vast scenario and I wish it to be solved as fast as possible in order to share my project which just has been paused just because of this issue .

Again thanks 😊.
