### ISSUE TITLE
[iOS] Platform views is rendered above another widget when scrolling

### ISSUE THREAD

**Issue by reklada** [flutter/flutter#153904] opened 2024-08-22 06:40 UTC
### Steps to reproduce

1. Clone repo: https://github.com/reklada/flutter-webview-render-issue.git
2. Run on iOS 
3. Scroll view

### Expected results

The amber-colored container should remain visible at the top of the view at all times, regardless of the scrolling activity in the ListView below it. The container's position should be fixed and unaffected by the scrolling behavior of the underlying content.

### Actual results

When the ListView is scrolled and the WebView within it reaches the bottom edge of the AppBar (located under the top container), the WebView is rendered above the amber-colored container, obscuring it from view. This issue also occurs in our production app with a similar setup involving WebViews and Google Mobile Ads, where the container is unexpectedly covered instead of remaining visible. Notably, this issue does not occur on previous Flutter version 3.22.2.

### Code sample

https://github.com/reklada/flutter-webview-render-issue.git

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/1e58e011-0145-4f1e-8141-dc54c73a88d7
</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.2 23C64 darwin-arm64, locale fi-FI)
    • Flutter version 3.24.1 on channel stable at /Users/paanarek/Documents/GitRepositories/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5874a72aa4 (33 hours ago), 2024-08-20 16:46:00 -0500
    • Engine revision c9b9d5780d
    • Dart version 3.5.1
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/paanarek/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/paanarek/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • iPhone (Reko) (mobile)          • 00008130-000A44A11E8B803A            • ios            • iOS 18.0 22A5338b
    • iPhone 15 Pro (mobile)          • 338C721F-7A5A-4A81-BB3C-FF72B38D4DD6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 127.0.6533.120

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by huycozy** [comment] 2024-08-22 11:43
Thank you for the report. I can also reproduce this issue with pure platform views sample code: [scroll_render_ios_153904](https://github.com/huycozy/platformviews-demo/tree/scroll_render_ios_153904). This issue doesn't happen on Android app target.

<details open>
<summary>Demo</summary>


https://github.com/user-attachments/assets/97945c9d-f477-4899-a862-c99696e20745


</details>

Reproduced this on Flutter master channel `3.25.0-1.0.pre.78`. Since this doesn't occur on previous stable release, marking this as a regression.

**Comment by hellstrom** [comment] 2024-08-23 07:48
We are rebuilding an existing app from scratch using Flutter and we are also encountering this problem with our Google Mobile Ads. The ads overlap the header of the app with is very annoying and poor user experience. It's actually a blocker for us for releasing the new app. We would really appreciate if this bug can be solved soon! Thanks in advance.

**Comment by tv24-git** [comment] 2024-08-23 08:27
+1 please get this fixed.

**Comment by dw2kim** [comment] 2024-08-23 13:32
+1 

![Simulator Screenshot - iPhone 15 - 2024-08-21 at 15 18 55](https://github.com/user-attachments/assets/fb7e2218-dbef-4ed3-8647-0ef22cf046c9)

**Comment by huycozy** [comment] 2024-08-23 14:27
I bisected this to dccc26a28afe79f88a6c4c804253041678fbb46f which is a Roll Flutter Engine commit. It seems the culprit is:

>2024-06-06 41930132+hellohuanlin@users.noreply.github.com Reland "[ios][platform_view] Use CAShapeLayer as the mask to avoid software rendering https://github.com/flutter/flutter/issues/53072" (https://github.com/flutter/engine/pull/53256)

Kindly cc @hellohuanlin for thoughts

**Comment by MaksimLosich** [comment] 2024-08-23 15:21
+1 here. Our Ads are overlapping SliverPersistentHeaders and even SafeAreas.

**Comment by dw2kim** [comment] 2024-08-26 15:06
+1 This happens when the Google maps component or the Ads are overlapping.

<img src=https://github.com/user-attachments/assets/298d7061-2b26-4430-a6a0-7dcf12e125e2 width=400>

**Comment by hellohuanlin** [comment] 2024-08-27 18:20
We changed a lot of platform view logic. Wondering if this is a recent regression.

**Comment by jmagman** [comment] 2024-08-27 18:27
> What was the latest version that worked?

It was bisected to https://github.com/flutter/engine/pull/53256

> I bisected this to [dccc26a](https://github.com/flutter/flutter/commit/dccc26a28afe79f88a6c4c804253041678fbb46f) which is a Roll Flutter Engine commit.

**Comment by nateshmbhat** [comment] 2024-09-02 08:12
facing this exact same issue. will try after rolling back to above mentioned commit

**Comment by nateshmbhat** [comment] 2024-09-02 16:08
this works fine in 3.22 version but breaks in 3.24 and above.

**Closed** 2024-09-03 20:36 UTC
Labels: c: regression, platform-ios, f: scrolling, a: platform-views, c: rendering, has reproducible steps, team-ios, found in release: 3.24, found in release: 3.25
