### ISSUE TITLE
handle link and navigate with firebase dynamic links in flutter

### ISSUE THREAD

**Issue by TheGhostDevlopper** [flutter/flutter#51510] opened 2020-02-26 22:33 UTC
I am using firebase_dynamic_links 0.5.0 in my flutter project app. I am using bloc for state management and I have the issue with the navigation. I am handling the link normally but when I try to navigate to another page that's not work . I don't know why ?

I have this error :
E/flutter (10216): The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.

PS : I have test the [firebase_dynamic_links example](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_dynamic_links/example/lib/main.dart) and that's work normally

```
main() {
  WidgetsFlutterBinding.ensureInitialized();

  // Production code
  ErrorWidget.builder = (FlutterErrorDetails details) => Container();


  runApp(MyApp());
}
// Myapp class here I get the result of print but navigation don't work

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _authBloc = AuthBloc();

  final _progressBloc = new ProgressBloc();

  @override
  void initState() {
    super.initState();
    initDynamicLinks();
  }

  void initDynamicLinks() async {
    final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;

       //print("hhhhhhh" + deepLink.path);

    if (deepLink != null) {
      print("Link :" + deepLink.path);

      // this line don't work 
      Navigator.pushNamed(context, '/helloworld');
    }

    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData dynamicLink) async {
      final Uri deepLink = dynamicLink?.link;

      if (deepLink != null) {
        print("Link :" + deepLink.path);

        Navigator.pushNamed(context, '/helloworld');
      }
    }, onError: (OnLinkErrorException e) async {
      print('onLinkError');
      print(e.message);
    });
  }

  @override
  Widget build(BuildContext context) {
    ThemeData themeData = ThemeData(
      fontFamily: Constants.DEFAULT_FONT_NAME,
      textTheme: Theme.of(context)
          .textTheme
          .apply(fontFamily: Constants.DEFAULT_FONT_NAME),
      brightness: Brightness.light,
      canvasColor: Colors.black12,
      scaffoldBackgroundColor: Colors.white,
      primaryIconTheme:
          Theme.of(context).primaryIconTheme.copyWith(color: Colors.white),
      accentIconTheme:
          Theme.of(context).accentIconTheme.copyWith(color: Colors.white),
      primaryTextTheme:
          Theme.of(context).primaryTextTheme.apply(bodyColor: Colors.white),
      primaryColorLight: Colors.white,
      primaryColorBrightness: Brightness.light,
      primarySwatch: Constants.COLOR_PRIMARY,
      primaryColor: Constants.COLOR_PRIMARY,
    );

    var home = Stack(children: <Widget>[
      RootPage(),
      ProgressDialog(),
    ]);

    return ProgressProvider(
      dialog: _progressBloc,
      child: AuthBlocProvider(
        bloc: _authBloc,
        child: StoreBlocProvider(
          store: Store(),
          child: RootProvider(
            bloc: new RootBloc(),
            child: MaterialApp(
              localizationsDelegates: [
                GlobalMaterialLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate,
              ],
              supportedLocales: [
                const Locale('en'), // English
                const Locale('fr'), // Hebrew
              ],
              title: 'Foodynasty',
              theme: themeData,
              debugShowCheckedModeBanner: false,
              routes: <String, WidgetBuilder>{
                '/': (BuildContext context) => home,
                '/helloworld': (BuildContext context) => RestaurantShare(
                      restaurantId: 'test',
                    ),
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment] 2020-02-27 08:37
Hi @TheGhostDevlopper 
You need wrap your `MyApp` into `MaterialApp`

You can see in the example code
```
void main() {
  runApp(MaterialApp(
    title: 'Dynamic Links Example',
    routes: <String, WidgetBuilder>{
      '/': (BuildContext context) => _MainScreen(),
      '/helloworld': (BuildContext context) => _DynamicLinkScreen(),
    },
  ));
}
```
You're trying to use navigator from parent of your `MaterialApp` [Stackoverflow Answer]
(https://stackoverflow.com/a/50125296)

I believe this isn't an issue `firebase_dynamic_links`

**Comment by TheGhostDevlopper** [comment] 2020-02-27 09:39
thanks for ur answer, no the issue isn't firebase_dynamic_links, but I already did that

but I have two issue :  two issue my provider and in my theme context .

thank you I solve this by using navigator key in my material .


`

**Comment by TahaTesser** [comment] 2020-02-27 09:43
Hi @TheGhostDevlopper 
given your last message, `no the issue isn't firebase_dynamic_links,`  
I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-02-27 09:43 UTC
