### ISSUE TITLE
Crash while running app in hot mode

### ISSUE THREAD

**Issue by alanlgardner** [flutter/flutter#6221] opened 2016-10-05 18:24 UTC
## Steps to Reproduce
Attempt to run flutter application in hot mode.

## Logs

```
E/FlutterMain: Unable to load Sky Engine binary.
E/FlutterMain: org.chromium.base.library_loader.ProcessInitException
E/FlutterMain:  at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:262)
E/FlutterMain:  at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123)
E/FlutterMain:  at io.flutter.view.FlutterMain.initNative(FlutterMain.java:369)
E/FlutterMain:  at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:147)
E/FlutterMain:  at org.domokit.sky.shell.SkyApplication.onCreate(SkyApplication.java:19)
E/FlutterMain:  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
E/FlutterMain:  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
E/FlutterMain:  at android.app.ActivityThread.-wrap1(ActivityThread.java)
E/FlutterMain:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
E/FlutterMain:  at android.os.Handler.dispatchMessage(Handler.java:102)
E/FlutterMain:  at android.os.Looper.loop(Looper.java:148)
E/FlutterMain:  at android.app.ActivityThread.main(ActivityThread.java:5417)
E/FlutterMain:  at java.lang.reflect.Method.invoke(Native Method)
E/FlutterMain:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/FlutterMain:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/FlutterMain: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/com.google.fuchsia.armadillo-1/lib/arm/libsky_shell.so"...
E/FlutterMain:  at java.lang.Runtime.loadLibrary(Runtime.java:372)
E/FlutterMain:  at java.lang.System.loadLibrary(System.java:1076)
E/FlutterMain:  at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:250)
E/FlutterMain:  ... 14 more
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.google.fuchsia.armadillo, PID: 22234
E/AndroidRuntime: java.lang.RuntimeException: Unable to create application org.domokit.sky.shell.SkyApplication: java.lang.RuntimeException: org.chromium.base.library_loader.ProcessInitException
E/AndroidRuntime:       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
E/AndroidRuntime:       at android.app.ActivityThread.-wrap1(ActivityThread.java)
E/AndroidRuntime:       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
E/AndroidRuntime:       at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime:       at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime:       at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime:       at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/AndroidRuntime: Caused by: java.lang.RuntimeException: org.chromium.base.library_loader.ProcessInitException
E/AndroidRuntime:       at io.flutter.view.FlutterMain.initNative(FlutterMain.java:373)
E/AndroidRuntime:       at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:147)
E/AndroidRuntime:       at org.domokit.sky.shell.SkyApplication.onCreate(SkyApplication.java:19)
E/AndroidRuntime:       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
E/AndroidRuntime:       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
E/AndroidRuntime:       ... 8 more
E/AndroidRuntime: Caused by: org.chromium.base.library_loader.ProcessInitException
E/AndroidRuntime:       at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:262)
E/AndroidRuntime:       at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123)
E/AndroidRuntime:       at io.flutter.view.FlutterMain.initNative(FlutterMain.java:369)
E/AndroidRuntime:       ... 12 more
E/AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy" referenced by "/data/app/com.google.fuchsia.armadillo-1/lib/arm/libsky_shell.so"...
E/AndroidRuntime:       at java.lang.Runtime.loadLibrary(Runtime.java:372)
E/AndroidRuntime:       at java.lang.System.loadLibrary(System.java:1076)
E/AndroidRuntime:       at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:250)
E/AndroidRuntime:       ... 14 more
W/ActivityManager:   Force finishing activity com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity
W/ActivityManager: Activity pause timeout for ActivityRecord{e242967 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity t373 f}
W/ActivityManager: Activity destroy timeout for ActivityRecord{e242967 u0 com.google.fuchsia.armadillo/org.domokit.sky.shell.SkyActivity t373 f}
Timed out while waiting for a debug connection.
Error launching DevFS loader on Nexus 9.
```

## Flutter Doctor
```
[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/alangardner/src/fuchsia/sysui/third_party/flutter
    • Framework revision 16e3424805 (5 days ago), 2016-09-30 13:57:39
    • Engine revision 71f2871f00
    • Tools Dart version 1.20.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/alangardner/tools/android-sdk-linux
    • Platform android-24, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-132676107-132666263)

[x] Atom - a lightweight development environment for Flutter
    • flutter plugin not installed; this adds Flutter specific functionality to Atom.
      Install the plugin from Atom or run 'apm install flutter'.
    • dartlang plugin version 0.6.40

[✓] Connected devices
    • Nexus 9 • HT4A1JT03343 • android-arm
```

**Comment by chinmaygarde** [comment] 2016-10-05 18:34
This was fixed in https://github.com/flutter/flutter/commit/9b35ebf021296771aaf1e6664ee52a8291d5aa28. The framework revision you are using is 5 days old. The fix was two days ago. The issue is Android M only. A temporary workaround would be to use a non-M device. Or just update.

**Closed by chinmaygarde** 2016-10-05 18:34 UTC
