### ISSUE TITLE
[go_router_builder][go_router] `GoRouterState state` is not available in `pageBuilder`

### ISSUE THREAD

**Issue by ValentinVignal** [flutter/flutter#109440] opened 2022-08-12 03:51 UTC
I would like to implement custom transition and I was following the documentation 
https://gorouter.dev/typed-routing#custom-transitions

```dart
class FancyRoute extends GoRouteData {
  @override
  MaterialPage<void> buildPage(BuildContext context, GoRouterState state) =>
    CustomTransitionPage<void>(
      key: state.pageKey,
      child: FancyPage(),
      transitionsBuilder: (context, animation, animation2, child) =>
          RotationTransition(turns: animation, child: child),
    ),
}
```

But on the current version of `go_router` (`4.2.7`) , the type signature of `buildPage` is

```dart
Page<void> buildPage(BuildContext context);
```

and not 

```dart
Page<void> buildPage(BuildContext context, goRouterState state)
```

https://github.com/flutter/packages/blob/33bc15043c93e41912aa6aced45ec280f0d14e8c/packages/go_router/lib/src/route_data.dart#L31-L41

I would need to reuse the `state` to access `state.pageKey`

**Comment by ValentinVignal** [comment] 2022-08-12 06:32
So for now, I have this 

```dart
class FancyRoute extends GoRouteData {
  @override
  MaterialPage<void> buildPage(BuildContext context, GoRouterState state) =>
    CustomTransitionPage<void>(
      key: null, // What do I put here?
      child: FancyPage(),
      transitionsBuilder: (context, animation, animation2, child) =>
          RotationTransition(turns: animation, child: child),
    ),
}
```

I tried to find a work-around but I am a bit stuck.

I cannot leave `null` as there won't be any transition. So I need to create a key.
- If we give the `GoRouter.location` (or URL), the history cannot
  contain 2 pages with the same key / URL. This has been fixed in
  https://github.com/flutter/packages/pull/2339 on
  `GoRouterState.pageKey` but as said earlier, we cannot access it.
- If I combine the `GoRouter.location` with something unique:
  - Ex: `DateTime.now()`, this doesn't fix the issue as in go_router,
    `RouteBuilder.getPages()` is used to get the pages and all the
    pages are evaluated at once all together so `DateTime.now()` can
    be equal between 2 pages if the execution is fast enough. And we
    fallback in the duplicated key issue. This is also not a good fix
    as between 2 calls of `RouteBuilder.getPages()`, `DateTime.now()`
    and all the existing pages will get a new key and will be rebuilt.
  - Ex: Create a static variable `_count = 0` and increment it every time a page is built (`_count++`). This is not a fix as
    `getPages()` will return all the pages (even the ones already in
    the history), so the already existing pages will be given and new
    key and will be rebuilt.


Is there another solution I didn't think of?

**Comment by exaby73** [comment] 2022-08-12 10:59
Hello @ValentinVignal. Thank you for filing this request. Labelling for further insights from the team

**Comment by johnpryan** [comment] 2022-08-18 21:44
I think this is a duplicate of https://github.com/flutter/flutter/issues/103985

**Closed** 2022-08-18 21:44 UTC
Labels: p: first party, package, proposal, r: duplicate, p: go_router
