### ISSUE TITLE
[Navigator 2.0] All pages rebuild on push/pop on Flutter 3.19.x

### ISSUE THREAD

**Issue by francescreig** [flutter/flutter#146132] opened 2024-04-02 14:43 UTC
### Steps to reproduce

Hello, I just found that on the newest versions of Flutter (3.19.X) we are having the same problem that it was described few months ago on this [issue](https://github.com/flutter/flutter/issues/139053). 

The issue is what the title describes, after pushing/popping to/from  a page, the underline page is rebuilt again (also with having the widgets declared as const).

Could you reopen that issue, or further investigate on this one?

Thank you.

### Expected results

To not rebuild the underlying page when pushing/popping to another page.

### Actual results

The underlying page is being rebuild once before showing the underlying page.

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.3 23D56 darwin-arm64, locale en-ES)
    • Flutter version 3.19.5 on channel stable at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (6 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at 
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.87.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device 

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2024-04-03 06:35
Thanks for the report @francescreig 


Can you check [this](https://github.com/flutter/flutter/issues/72487#issuecomment-749843511) and see if it helps in your case or not ?

Also, is the reported behavior only occuring in 3.19 and not in previous version (ex: 3.16) ?

**Comment by francescreig** [comment] 2024-04-03 07:35
Hello @darshankawar,

I am gonna check out the answer from @chunhtai but I don't think using the GlobalKey of the Navigator state would help.

This started to happen on the new Flutter version 3.19.X (on any patch version of 3.19). On the previous Flutter version (3.16.X) it is not happening. I wrote the issue since it could lead to unexpected behaviours when pushing, but specially when popping from another pages (it is happening to me for example in form states). I think it should be taken seriously into consideration. 

Thank you.

**Comment by honghai2196** [comment] 2024-04-04 04:39
Any update on this ? It's so annoying

**Comment by darshankawar** [comment] 2024-04-04 06:23
@francescreig Thanks for the update. I tried below code sample on latest stable and previous version and shared the log I observed after incrementing the counter -> pushing to new page and then going back, which resets the counter.

<details>
<summary> runnable code sample </summary>

```

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp.router(
    routerDelegate: MyDelegate(routes),
    routeInformationParser: MyParser(routes),
  ));
}

class MyParser extends RouteInformationParser<String> {
  final List<MyRoute> routes;

  MyParser(this.routes);

  @override
  Future<String> parseRouteInformation(RouteInformation routeInformation) {
    final uri = routeInformation.uri;
    final route = routes.firstWhere((element) {
      return element.path == uri.toString();
    }, orElse: () {
      return routes.first;
    });
    print('[parseRouteInformation] Route path is ${route.path}');
    print('[parseRouteInformation] URI is ${uri.toString()}');
    return SynchronousFuture(route.path);
  }
}

class MyDelegate extends RouterDelegate<String>
    with PopNavigatorRouterDelegateMixin<String>, ChangeNotifier {
  final List<MyRoute> routes;

  MyDelegate(this.routes);

  final List<Page> pages = [];

  @override
  Widget build(BuildContext context) {
    print(
        '[Widget build(BuildContext context)] is trigger ${pages.toString()}');
    return Navigator(
      key: navigatorKey,
      pages: pages,
      onPopPage: (route, result) {
        if (!route.didPop(result)) {
          return false;
        }
        if (pages.isNotEmpty) {
          pages.removeLast();
          notifyListeners();
        }
        return true;
      },
    );
  }

  String get _currentConfiguration => routes.first.path;

  @override
  String? get currentConfiguration => _currentConfiguration;

  @override
  GlobalKey<NavigatorState>? get navigatorKey => GlobalKey<NavigatorState>();

  void _addPage(MyRoute route) {
    pages.add(
      MaterialPage(
        key: ValueKey<String>(route.path),
        child: route.child,
        name: route.path,
      ),
    );
  }

  @override
  Future<void> setNewRoutePath(String configuration) {
    final route = routes.firstWhere(
          (element) => element.path == configuration,
      orElse: () => routes.first,
    );
    _addPage(route);
    notifyListeners();
    return SynchronousFuture(null);
  }
}

final routes = [
  MyRoute(path: '/1', child: Page1()),
  MyRoute(path: '/2', child: const Page2()),
];

class MyRoute {
  final String path;
  final Widget child;
  final Function? dependencies;
  final bool isInitial;

  MyRoute({
    required this.path,
    required this.child,
    this.dependencies,
    this.isInitial = false,
  });
}

class Page1 extends StatefulWidget {
  Page1({super.key});

  @override
  State<Page1> createState() => _Page1State();
}

class _Page1State extends State<Page1> {
  int count = 0;

  @override
  void initState() {
    print('>>>>>>> initState() Page1 is trigger');
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Router.of(context).routerDelegate.setNewRoutePath('/2');
        },
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('Page 1'),
            ElevatedButton(
              onPressed: () {
                count++;
                setState(() {});
              },
              child: Text(
                count.toString(),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class Page2 extends StatefulWidget {
  const Page2({super.key});

  @override
  State<Page2> createState() => _Page2State();
}

class _Page2State extends State<Page2> {
  @override
  void initState() {
    print('>>>>>>> initState() Page2 is trigger');
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: const Text('Back'),
        ),
      ),
    );
  }
}

```

</details>


<details>
<summary> stable 3.19.5 and 3.16.0 console log </summary>

```
stable 3.19.5:

I/flutter (12896): >>>>>>> initState() Page1 is trigger
D/EGL_emulation(12896): app_time_stats: avg=1853.28ms min=275.59ms max=3430.96ms count=2
D/EGL_emulation(12896): app_time_stats: avg=16.65ms min=2.80ms max=34.63ms count=56
D/EGL_emulation(12896): app_time_stats: avg=29.73ms min=2.30ms max=767.66ms count=43
I/flutter (12896): [Widget build(BuildContext context)] is trigger [MaterialPage<dynamic>("/1", [<'/1'>], null), MaterialPage<dynamic>("/2", [<'/2'>], null)]
I/flutter (12896): >>>>>>> initState() Page1 is trigger
I/flutter (12896): >>>>>>> initState() Page2 is trigger
W/OnBackInvokedCallback(12896): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback(12896): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/EGL_emulation(12896): app_time_stats: avg=449.83ms min=14.11ms max=3005.39ms count=7
I/flutter (12896): [Widget build(BuildContext context)] is trigger [MaterialPage<dynamic>("/1", [<'/1'>], null)]
I/flutter (12896): >>>>>>> initState() Page1 is trigger


```

</details>

Can you go through the code sample and log and check if this is expected or you are seeing anything different ?

**Comment by firgia** [comment] 2024-04-04 13:50
Same issue with Flutter 3.19.5. 

I'm using Flutter 3.13.8 the page is not rebuilt when push/pop, but when I upgrade to Flutter 3.19.5 every page is rebuilt when push/pop.

**Comment by francescreig** [comment] 2024-04-04 16:29
Hi @darshankawar I've tried the runnable code sample you shared and worked as expected on both versions (3.16.0 and 3.19.5). That's working as expected because we are playing with the _routerDeletate_ and the _routeInformationParser_, we are defining them as custom, but that's not the ideal, since most of the apps will not use that specific implementation of the _delegate_ and _parser_. On the MaterialApp (without _.router_) is where I've been experiencing this problems (and seems that other users too).

Here is another [discussion](https://github.com/flutter/flutter/issues/11655) (actually went very hot) where probably is happening the same. The thing is that it seemed that it was solved long time ago, and now we are facing the same problem 🤔 .

Let's see if you can provide more clearance about this, or any workaround.

Thank you.

**Comment by darshankawar** [comment] 2024-04-05 05:53
Thanks for the update @francescreig 
Please provide a runnable code sample that shows the difference in results in 3.16 and 3.19 if your case / implementation is different from the one I shared earlier, so that we can verify this further and make the issue actionable.

**Comment by firgia** [comment] 2024-04-05 06:21
> Thanks for the update @francescreig Please provide a runnable code sample that shows the difference in results in 3.16 and 3.19 if your case / implementation is different from the one I shared earlier, so that we can verify this further and make the issue actionable.

### **Step to reproduce**
1. Copy the code below
2. Run on iOS simulator
3. Press "Go to second page" button


Please try those steps on Flutter 3.13.8 and Flutter 3.19.5

### **Expected results**
Print "BUILD FIRST PAGE" not called every push or pop page

### **Actual results**
Print "BUILD FIRST PAGE" is called every push or pop page only on Flutter 3.19.xxx

### **Code sample**
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: NavigationServices.navigatorKey,
      navigatorObservers: [NavigationServices.routeObserver],
      title: 'Flutter Demo',
      home: const FistPage(),
    );
  }
}

class NavigationServices {
  static GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
  static RouteObserver<PageRoute> routeObserver = RouteObserver<PageRoute>();

  static NavigationServices? _instance;
  factory NavigationServices() => _instance ??= NavigationServices._();
  NavigationServices._();
}

class FistPage extends StatefulWidget {
  const FistPage({super.key});

  @override
  State<FistPage> createState() => _FistPageState();
}

class _FistPageState extends State<FistPage>
    with RouteAware, WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    NavigationServices.routeObserver
        .subscribe(this, ModalRoute.of(context) as PageRoute);
  }

  @override
  void dispose() {
    NavigationServices.routeObserver.unsubscribe(this);
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    print("BUILD FIRST PAGE");

    return Scaffold(
      appBar: AppBar(
        title: const Text("First Page"),
      ),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => const SecondPage(),
              ),
            );
          },
          child: const Text("Go To Second Page"),
        ),
      ),
    );
  }
}

class SecondPage extends StatefulWidget {
  const SecondPage({super.key});

  @override
  State<SecondPage> createState() => _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Second page"),
      ),
    );
  }
}
```

**Comment by francescreig** [comment] 2024-04-05 10:17
Hello @darshankawar the example @firgia shared is enough to reproduce the example. 

Thanks

**Comment by francescreig** [comment] 2024-04-05 10:34
I found a similar issue that probably relates to this one: https://github.com/flutter/flutter/issues/116994

**Comment by darshankawar** [comment] 2024-04-05 11:50
Thanks for the update. I was able to replicate the reported behavior on latest stable on which we get below log:

```
I/flutter ( 7394): BUILD FIRST PAGE
W/Parcel  ( 7394): Expecting binder but got null!
I/flutter ( 7394): BUILD FIRST PAGE
W/OnBackInvokedCallback( 7394): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback( 7394): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
I/flutter ( 7394): BUILD FIRST PAGE
D/EGL_emulation( 7394): app_time_stats: avg=1778.11ms min=2.75ms max=14580.61ms count=10
```

Whereas, on stable 3.16.0, I get below:

```
I/flutter ( 5666): BUILD FIRST PAGE
W/Parcel  ( 5666): Expecting binder but got null!
D/ProfileInstaller( 5666): Installing profile for com.example.app_foo_stable
W/OnBackInvokedCallback( 5666): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback( 5666): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/EGL_emulation( 5666): app_time_stats: avg=2086.07ms min=16.57ms max=4155.57ms count=2
D/EGL_emulation( 5666): app_time_stats: avg=2112.18ms min=17.00ms max=6283.86ms count=3
```

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.19.5, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.19.5 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (4 days ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.22.0-5.0.pre.29, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.22.0-5.0.pre.29 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1964cf4f0 (3 hours ago), 2024-04-05 00:05:20 -0400
    • Engine revision f17d586de6
    • Dart version 3.5.0 (build 3.5.0-18.0.dev)
    • DevTools version 2.34.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by darshankawar** [comment] 2024-04-05 11:58
Actually, revisiting this issue, I came across [this](https://github.com/flutter/flutter/issues/145136) issue and [this](https://github.com/flutter/flutter/issues/145136#issuecomment-2013198686) comment claiming it is WAI, so check the same and see if it helps in your case or not @francescreig @firgia 

The code sample provided above also uses `ModalRoute.of(context)` as mentioned in the issue comment.

**Comment by darshankawar** [comment] 2024-04-08 05:18
> I don't know if that's an expected behaviour or not, but I firmly confirm that this was not happening Flutter 3.16.x and now it is happening on the newer version of Flutter 3.19.x.

@francescreig Probably [this](https://github.com/flutter/flutter/pull/134554) is the PR that might have introduced it that you can check and confirm.

**Comment by francescreig** [comment] 2024-04-08 07:44
Hi @darshankawar yes, I think that this PR did introduce this issue. I haven't test it, but looking at `rotues.dart` on this PR, the line 1729, marking the modal barrier to rebuild could potentially introduce this problem (also in conjunction with _didChangeNext_ and _didPopNext_ functions.

**Comment by darshankawar** [comment] 2024-04-08 12:35
Thanks for feedback @francescreig 
You can check https://github.com/flutter/flutter/pull/145389 to see if it'll help to address the rebuild issue.
Mainly it also highlights to resolve it: https://github.com/flutter/flutter/pull/145389#issuecomment-2033378887

**Comment by francescreig** [comment] 2024-04-09 13:26
Hello @darshankawar thanks for also finding the PR that could solve this. I will also look into this comment https://github.com/flutter/flutter/pull/145389#issuecomment-2035045393 to check if there's any news regarding this topic.

I solved the issue about rebuilding using the _onGenerateRoute_ on _MaterialApp_ as I explained on this comment https://github.com/flutter/flutter/issues/146132#issuecomment-2039797386, but I don't think it is the ideal solution to it, so I will not close the issue, until we have some response from @goderbauer 

Thank you

**Comment by haidang-uit** [comment] 2024-04-10 01:56
Hello @darshankawar 
I think this is a big issue. We can not change our base navigator which is use normally in 3.16.x due to a issue from Flutter framework in 3.19.x.
It will take much more time and waste our time to re-test our application

**Comment by darshankawar** [comment] 2024-04-10 05:25
Thanks for all the updates. I am keeping the issue open and label this for team's input / attention.

**Comment by haidang-uit** [comment] 2024-04-12 09:51
@darshankawar can you add label found in release 3.19 to this. No one cares this issue.

**Comment by chunhtai** [comment] 2024-04-16 23:15
> So extracting the arguments using ModalRoute.of(context) on the build was the problem. It seems now that when pushing/popping, since the route is changing, it will also perform a change on the ModalRoute that will trigger a build when going from/to a page.
>
>I don't know if that's an expected behaviour or not, but I firmly confirm that this was not happening Flutter 3.16.x and now it is happening on the newer version of Flutter 3.19.x.

This is expected, and is a behavior i specifically fixed in the last release. Imagine someone does this.
```dart
Widget build(context) {
   if (ModalRoute.of(context).isActive) {
      return Text('OH I AM ACTIVE');
   }
   return Text('oooh...');
}
```

If it doesn't rebuild when a new route push on top, the content won't be updated.

**Closed** 2024-04-16 23:20 UTC
Labels: framework, f: routes, team-framework

**Comment by CoderBuck** [comment] 2024-04-17 03:10
I have a case where I only want to monitor route changes on the `HomePage` and not trigger a `rebuild` of the `HomePage ` when pushing the `SettingPage` (rebuild is unnecessary and performance-intensive). What should I do?

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

var routeObserver = RouteObserver();

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorObservers: [routeObserver],
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});
  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> with RouteAware {
  void _incrementCounter() {
    Navigator.push(context, MaterialPageRoute(builder: (context) => SettingPage()));
  }

  @override
  Widget build(BuildContext context) {
    print("HomePage: build");
    return Scaffold(
      appBar: AppBar(title: Text("Home")),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    routeObserver.subscribe(this, ModalRoute.of(context)!);
  }

  @override
  void didPushNext() {
    print("HomePage: didPushNext");
  }

  @override
  void didPop() {
    print("HomePage: didPop");
  }

  @override
  void didPush() {
    print("HomePage: didPush");
  }

  @override
  void didPopNext() {
    print("HomePage: didPopNext");
  }
}


class SettingPage extends StatelessWidget {
  const SettingPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Setting')),
    );
  }
}

```

**Comment by francescreig** [comment] 2024-04-17 08:41
@chunhtai Okay, maybe it is working as intended but I would not close this issue until you provide a solution to what is expected to work, for example when passing arguments to a new page. 

Here [in this section of Flutter's cookbook](https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments#2-create-a-widget-that-extracts-the-arguments), using Navigator 2.0, when you want to extract the arguments using for example
```dart
final args = ModalRoute.of(context)!.settings.arguments as ScreenArguments;
```
it's when the issue happens, and the screen/page will rebuild on push/pop. 

So please, for future people that would face this problem:
1. Wether update the docs, or,
2. Provide an alternative solution (or make clear to only use _onGenerateRoute_, since the other solution will lead into unnecessary rebuilds).

Thank you.

PS: @darshankawar I don't think the issue should be marked as _solved_ since I guess a lot of people will face the same issue, using the method I linked you above. I think it should be marked as solved when we can assure one or both points.

**Comment by chunhtai** [comment] 2024-04-17 16:19
I don't say that is unnecessary rebuilds, the properties on the ModalRoute has changed.

Perhaps an inheritedModal https://api.flutter.dev/flutter/widgets/InheritedModel-class.html maybe more suitable to implement the ModalRoute.of in this case so that looking on one property will not causes rebuild when irrelevant properties change.

Either way, please open a new issue if you have other suggestions.

**Comment by cindy-chin** [comment] 2024-04-24 01:51
can anybody fix this? what if i do a minor calculation using provider, it rebuild when i push, it trigger the calculation twice. it just does'nt make sense to me

**Comment by darshankawar** [comment] 2024-04-24 05:19
@cindy-chin As mentioned earlier, please file a new issue with relevant details so that we can properly address the issue.
