### ISSUE TITLE
Video_player plugin. Add HTTP headers support like in Image.network

### ISSUE THREAD

**Issue by Olegas** [flutter/flutter#57049] opened 2020-05-12 20:48 UTC
## Use case
My application is using video_player to show videos from a web site. Authentication is required to access media files.
With `Image.network` I can use `headers` argument and pass cookies or token. But `VideoPlayerController.network` does not have this ability

## Proposal
Add support of passing arbitrary HTTP headers to `VideoPlayerControler.network` constructor.

**Comment by jaysephjw** [comment] 2020-07-08 19:25
Duplicate of #16466 :) 

@Olegas note the issue blocking $16466 should not prevent using cookies, just other types of headers. I am going to work on a PR for that.

**Comment by pedromassangocode** [comment] 2021-03-02 11:49
Closing as duplicate of https://github.com/flutter/flutter/issues/16466.

**Closed by pedromassangocode** 2021-03-02 11:49 UTC
Labels: p: first party, p: video_player, plugin, proposal, severe: new feature
