### ISSUE TITLE
[image_picker] throw PlatformException(already_active, Image picker is already active, null, null) when pick photo from gallery

### ISSUE THREAD

**Issue by gaochang1993** [flutter/flutter#156385] opened 2024-10-08 03:21 UTC
### Steps to reproduce

My application uses the image_picker plug-in, but some online users have this problem, and I have not reproduced it.

### Expected results

pick a picture normally

### Actual results

throw PlatformException(already_active, Image picker is already active, null, null)

### Code sample

    final file = await ImagePicker().pickImage(source: ImageSource.gallery);
    if (file == null) {
      return null;
    }

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.2, on macOS 15.0 24A335 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.24.2 on channel stable at /Users/gaochang/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (5 weeks ago), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/gaochang/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/gaochang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    ! iOS 18.0 Simulator not installed; this may be necessary for iOS and macOS development.
      To download and install the platform, open Xcode, select Xcode > Settings > Platforms,
      and click the GET button for the required platform.

      For more information, please visit:
        https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Community Edition (version 2023.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 231.9161.14

[✓] VS Code (version 1.93.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.92.2)
    • VS Code at /Users/gaochang/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • 22041211AC (mobile)             • 4DMBYHA6UWONCET8                     • android-arm64  • Android 13 (API 33)
    • iPhone 15 Pro Max (mobile)      • 61B33049-5986-4BF0-AC39-4F9422DC6A81 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 129.0.6668.90

[✓] Network resources
    • All expected network resources are available.

**Comment by danagbemava-nc** [comment] 2024-10-08 09:55
Hi @gaochang1993, what device(s) are you seeing this issue on? What version of `android` or `iOS` are experiencing this issue? What version of `image_picker` & `image_picker_android` are you using in your project?

**Comment by stuartmorgan** [comment] 2024-10-08 14:56
> ### Code sample
> ```
> final file = await ImagePicker().pickImage(source: ImageSource.gallery);
> if (file == null) {
>   return null;
> }
> ```

Please provide a more complete code sample. Having multiple in-flight calls to `pickImage` is a programming error (as indicated by the error message), and this is not enough code to indicate whether you are preventing that from happening.

For instance, if this is the entire contents of an asynchronous button tap handler, then this is an issue in your code, because nothing would prevent someone from tapping the button twice in a row and triggering two simultaneous async calls to `pickImage`.

**Comment by gaochang1993** [comment] 2024-10-09 03:14
> Hi @gaochang1993, what device(s) are you seeing this issue on? What version of `android` or `iOS` are experiencing this issue? What version of `image_picker` & `image_picker_android` are you using in your project?

  image_picker: ^1.1.2
image_picker_android: 0.8.12+13

**Comment by danagbemava-nc** [comment] 2024-10-09 06:26
Hi @gaochang1993, are you using the throttle code in production? What happens if you increase the throttle time? Do your users still experience this? Are you able to reproduce this without the throttle?

**Comment by gaochang1993** [comment] 2024-10-09 08:42
> Hi @gaochang1993, are you using the throttle code in production? What happens if you increase the throttle time? Do your users still experience this? Are you able to reproduce this without the throttle?

Yes, I do use the throttle code in production to fix pick picture to fix when the same crash when  click the buttons in rapid succession. And I'm sure it works thus this crash has not occurred for quite some time.
But it occurred again on the latest release version
What the the throttle time for? It is used to limit the user to click multiple times within a certain period of time and only trigger one processing。The 200 millisecond setting can maintain a smooth interaction and experience. Increasing this time will result in a longer period of time without being able to respond to user clicks.

**Comment by stuartmorgan** [comment] 2024-10-09 10:54
It's extremely unlikely that the `pickImage` future will resolve within 200ms, so that code will not prevent a second simultaneous call, only make it less likely. In particular, https://github.com/flutter/flutter/issues/14720 could be allowing taps on this button to register even when it is hidden.

> Increasing this time will result in a longer period of time without being able to respond to user clicks.

Rather than use an arbitrary time, you can disable (or ignore) the button until the `pickImage` future resolves. That does not create a responsiveness problem, because it would never be correct to call `pickImage` while a previous call is still resolving.

Closing as this is the intended behavior of the plugin, and to the extent that there's a Flutter issue here it's tracked by the engine issue above.

**Closed by stuartmorgan** 2024-10-09 10:54 UTC
Labels: in triage
