### ISSUE TITLE
We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs

### ISSUE THREAD

**Issue by Junaidhassan99** [flutter/flutter#80738] opened 2021-04-19 16:43 UTC
Hi!
I have an app on Google play store that uses the image_picker. I have received an alert from Google which says that I cannot use requestLegacyExternalStorage =true in my manifest file. I am confused and don't know what to do because in the documentation of image_picker it clearly says that we should use requestLegacyExternalStorage in the manifest file. Please help me solve this problem and is there a workaround for this?
![Capture](https://user-images.githubusercontent.com/61021884/115272801-3e56c500-a158-11eb-91ba-f727d8e7175a.PNG)

**Comment by darshankawar** [comment] 2021-04-20 06:31
Closing this as duplicate of https://github.com/flutter/flutter/issues/80502

**Closed by darshankawar** 2021-04-20 06:31 UTC
Labels: in triage
