### ISSUE TITLE
Unable to set notification bar icon color/brightness when in ios dark mode

### ISSUE THREAD

**Issue by vlowe85** [flutter/flutter#41188] opened 2019-09-24 11:43 UTC
When the ios device is in dark mode and an AppBar is set to white background then i am unable to set the notification bar icons to dark so they are visible. The `brightness: Brightness.light` parameter does nothing.

```
      appBar: AppBar(
        title: Text(widget.title),
        backgroundColor: Colors.white,
        brightness: Brightness.light,
      ),
```
I understand that in dark mode usually you would not set a white AppBar background, but i would like it to look the same as it does in light mode until we have time to fully implement a dark mode design.

I have tried using setSystemUIOverlayStyle method and annotatedRegion.

Sample app - https://github.com/vlowe85/flutter_ios_dark_mode

**Comment by HansMuller** [comment] 2019-09-24 15:34
CC @darrenaustin

**Comment by vlowe85** [comment] 2019-09-26 07:34
Same issue on the dev channel fyi

**Comment by ToniTornado** [comment] 2019-09-26 19:17
Calling `SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.dark);` has also no effect when the device is set to dark mode. It works as expected in light mode when I call it with `SystemUiOverlayStyle.light` or `SystemUiOverlayStyle.dark`. I'm on iOS 13.1.

**Comment by fabryx92** [comment] 2019-10-08 00:46
## Steps to Reproduce
This is enough to reproduce the issue:
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion(
      value: SystemUiOverlayStyle.light,
      child: MaterialApp(
        home: Scaffold(),
      ),
    );
  }
}
```
In iOS, when the system Dark mode is enabled, the color of the status bar icons doesn't change by changing the `SystemUiOverlayStyle`.

Tested on:
**Target Platform:**
iOS
**Target OS version/browser:**
13
**Devices:**
- simulated iPhone 11 Pro Max
- real iPhone X

## Logs

```
Analyzing ios_statusbar...                                              
No issues found! (ran in 2.2s)

```



```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-IT)
    • Flutter version 1.9.1+hotfix.4 at /Users/fabryx/Development/flutter
    • Framework revision cc949a8e8b (10 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fabryx/Development/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/fabryx/Development/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Users/fabryx/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 192.6603.23
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 7A686F03-80F0-43E2-B1F8-F776C4391DD9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 2 categories.

```

**Comment by fabryx92** [comment] 2019-10-08 00:54
Also tried with the master channel, same result.

(here the `flutter doctor` output)

```
[✓] Flutter (Channel master, v1.10.14-pre.12, on Mac OS X 10.14.6 18G95, locale en-IT)
    • Flutter version 1.10.14-pre.12 at /Users/fabryx/Development/flutter
    • Framework revision cdc2d9901d (70 minutes ago), 2019-10-07 16:43:04 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fabryx/Development/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/fabryx/Development/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Users/fabryx/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 192.6603.23
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 7A686F03-80F0-43E2-B1F8-F776C4391DD9 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 2 categories.

```

**Comment by huangchaosysu** [comment] 2019-10-14 09:14
same issue

**Comment by huangchaosysu** [comment] 2019-10-14 09:20
i don't have a app bar in scaffold

**Comment by supermebing** [comment] 2019-10-14 10:03
> 我没有脚手架上的应用程序栏

 我也遇到了   应该是bug

**Comment by marcoms** [comment] 2019-10-18 23:51
Also facing this issue. I was initially super confused since I could set the status bar color when running in the simulator (which must have defaulted to light mode) but not on a physical device. My app always has a light background so the status bar is effectively invisible when dark mode is on.

**Comment by darrenaustin** [comment] 2019-10-21 22:08
This is a duplicate of https://github.com/flutter/flutter/issues/41067. 

There is an engine PR that will fix this that hasn't landed yet: https://github.com/flutter/engine/pull/13119

**Closed by darrenaustin** 2019-10-21 22:08 UTC
Labels: customer: crowd, f: material design, framework, ⌺‬ platform-ios
