### ISSUE TITLE
Console output advised filing a bug

### ISSUE THREAD

**Issue by willhaslett** [flutter/flutter#68885] opened 2020-10-23 14:56 UTC
Not sure what context to add except that he action that intermittently results in this error is pushing a named route to the Navigator

```

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#bfe7e](state: OverlayState#93591(entries: [OverlayEntry#6e5b9(opaque: true; maintainState: false), OverlayEntry#ff704(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 5144 pos 14: '_dependents.isEmpty': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was
MaterialApp
lib/main.dart:54
When the exception was thrown, this was the stack
#2      InheritedElement.debugDeactivated.<anonymous closure>
package:flutter/…/widgets/framework.dart:5144
#3      InheritedElement.debugDeactivated
package:flutter/…/widgets/framework.dart:5146
#4      _InactiveElements._deactivateRecursively.<anonymous closure>
package:flutter/…/widgets/framework.dart:2048
#5      _InactiveElements._deactivateRecursively
package:flutter/…/widgets/framework.dart:2050
#6      ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4729
...
════════════════════════════════════════════════════════════════════════════════
```

**Comment by Abhishek01039** [comment] 2020-10-24 04:03
Hi @willhaslett 
can you please provide `flutter run -v, and minimal reproduction code?
Thanks

**Comment by pedromassangocode** [comment] 2020-10-26 06:37
Hi @willhaslett 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by willhaslett** [comment] 2020-10-26 14:35
The failure is intermittent and I have only seen it on Android, though I don't use iOS during dev much. The context is pressing this button, while in the context of of a viewmodel that is managed by the Stacked package, in case that may have anything to do with it. I certainly wish that it were an open-source project, but it's not.

``` 
RaisedButton(
  child: Text('Dev home'),
  onPressed: () => Navigator.pushAndRemoveUntil(
    context,
    MaterialPageRoute(
      builder: (context) => DevHomeScreen(),
    ),
    (Route<dynamic> route) => false,
  ),
),
```


```~/code/mt2 % flutter doctor -v
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-US)
    • Flutter version 1.23.0-18.1.pre at /Users/wh/flutter
    • Framework revision 198df796aa (11 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/wh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 9AUAY1FS35 • android-arm64  • Android 11 (API 30)
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 86.0.4240.111
    ! Error: William’s iPhone is not connected. Xcode will continue when William’s iPhone is connected. (code -13)

• No issues found!

[flutter_run-v.txt](https://github.com/flutter/flutter/files/5439368/flutter_run-v.txt)

**Comment by pedromassangocode** [comment] 2020-10-27 07:42
Hi @willhaslett 
I will need a minimal complete code sample to reproduce the issue. Please provide such code!
Thank you

**Comment by willhaslett** [comment] 2020-10-27 14:36
I can't reliably reproduce the error. It's intermittent. Therefore, the engineering effort to figure out what a minimum code sample would be to reproduce it is way out of scope for this process. If the project were open-source, I would point you to the repo.

**Comment by pedromassangocode** [comment] 2020-10-28 08:45
Hi @willhaslett 
You surely should not share any private code. But you may know where and when the issue happen and try to reproduce in a brand new project if necessary.

Without the reproducible code sample we are unable to reproduce the issue and there is nothing we can do.

**Comment by pedromassangocode** [comment] 2020-11-24 09:59
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2020-11-24 09:59 UTC
Labels: in triage, waiting for customer response
