### ISSUE TITLE
popscope widget is making so many troubles with go_router

### ISSUE THREAD

**Issue by mahdiqdi** [flutter/flutter#142852] opened 2024-02-03 06:10 UTC
### Steps to reproduce

the popScope widget is making so many difficulties
i have a screen with a pageView 
when i am in first screen and i want to use context.goNamed()
the app crashes with grey screen
the error is this in sentry
builder.dart in _PagePopContext.onPopPage at line 595 within go_router
this widget is aweful

### Expected results

when using willPopScope its okay and navigation happens

### Actual results

but with this new widget screen goes gray
the error is here 
![Screen Shot 2024-02-03 at 09 39 00](https://github.com/flutter/flutter/assets/67858014/ed77038e-bb89-457a-9c51-6d2e53a5cd1e)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screen Shot 2024-02-03 at 09 34 30](https://github.com/flutter/flutter/assets/67858014/11e1b6db-e1f9-4b1a-8811-91633b4096ca)
![Screen Shot 2024-02-03 at 09 35 15](https://github.com/flutter/flutter/assets/67858014/a5e92fb7-2803-4ee8-8509-1ec448a98a8a)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.1, on macOS 12.6.1 21G217 darwin-x64, locale en-TR)
    • Flutter version 3.16.1 on channel stable at /Users/mac/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f20e5d18c (10 weeks ago), 2023-11-27 09:47:30 -0800
    • Engine revision 22b600f240
    • Dart version 3.2.1
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio Preview.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version unknown)
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by dam-ease** [comment] 2024-02-05 08:29
Hello @mahdiqdi.
You seem to be hitting an existing issue https://github.com/flutter/flutter/issues/140869.
Can you please comment, upvote and follow up on that issue for updates?
Closing this as a duplicate of the already existing issue, if you disagree, please comment with reasons and a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I'll reopen this.
Thank you!

**Closed by dam-ease** 2024-02-05 08:29 UTC
Labels: in triage

**Comment by mahdiqdi** [comment] 2024-02-05 08:34
hello @dam-ease 
my problem is not the same with that issue
i am using v12 go_router
physical back button is working perfect
the problem is when response comes from api and context.goNamed() wants to navigate user popScope does not let and screen goes grey
