### ISSUE TITLE
[tool_crash] String: <168 characters>

### ISSUE THREAD

**Issue by linslouis** [flutter/flutter#153914] opened 2024-08-22 09:04 UTC
## Command
```sh
flutter run --profile
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
String: <168 characters>
```console

```
```console
[32m[✓][39m Flutter (Channel master, 3.24.0-1.0.pre.509, on macOS 14.6.1 23G93 darwin-arm64, locale en-IN)
    [32m•[39m Flutter version 3.24.0-1.0.pre.509 on channel master at /Users/linslouis/Developer/fluttergit/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 925ad4e6fa (2 weeks ago), 2024-08-08 00:38:29 -0400
    [32m•[39m Engine revision 94cf8c8fad
    [32m•[39m Dart version 3.6.0 (build 3.6.0-127.0.dev)
    [32m•[39m DevTools version 2.38.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/linslouis/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m ANDROID_HOME = /Users/linslouis/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 15.4)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 15F31d
    [32m•[39m CocoaPods version 1.15.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m android-studio-dir = /Applications/Android Studio.app
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[32m[✓][39m VS Code (version 1.92.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.94.0

[32m[✓][39m Connected device (4 available)
    [32m•[39m ASUS I003DD (mobile)            • L8AIGF00128699H       • android-arm64  • Android 12 (API 31)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6.1 23G93 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6.1 23G93 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.120

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.1.6+6
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: b712a172f9694745f50505c93340883493b505e5
### Plugins
audioplayers-6.0.0
audioplayers_android-5.0.0
audioplayers_darwin-6.0.0
audioplayers_linux-4.0.0
audioplayers_web-5.0.0
audioplayers_windows-4.0.0
emoji_picker_flutter-2.2.0
file_picker-8.0.7
firebase_analytics-11.2.1
firebase_analytics_web-0.5.9+1
firebase_core-3.3.0
firebase_core_web-2.17.4
firebase_crashlytics-4.0.4
flutter_image_compress-2.3.0
flutter_image_compress_common-1.0.5
flutter_image_compress_macos-1.0.2
flutter_image_compress_ohos-0.0.3
flutter_image_compress_web-0.1.4+1
flutter_native_splash-2.4.1
flutter_plugin_android_lifecycle-2.0.21
fluttertoast-8.2.6
open_file-3.3.2
package_info_plus-8.0.1
path_provider-2.1.3
path_provider_android-2.2.9
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.3.0
permission_handler-11.3.1
permission_handler_android-12.0.7
permission_handler_apple-9.4.5
permission_handler_html-0.1.2
permission_handler_windows-0.2.1
photo_gallery-fa58e4e2d01828dbc421e8336f1a8c897abff542
record-5.1.2
record_android-1.2.4
record_darwin-1.1.1
record_linux-0.7.2
record_web-1.1.1
record_windows-1.0.3
share_plus-10.0.0
shared_preferences-2.2.3
shared_preferences_android-2.2.4
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
sqflite-2.3.3+1
url_launcher-6.3.0
url_launcher_android-6.3.7
url_launcher_ios-6.3.1
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.2
wakelock_plus-1.2.7

**Comment by danagbemava-nc** [comment] 2024-08-22 11:04
Closing this as a duplicate of https://github.com/flutter/flutter/issues/108812

**Closed by danagbemava-nc** 2024-08-22 11:04 UTC
Labels: in triage
