### ISSUE TITLE
Assets path is different depending on compilation mode on web.

### ISSUE THREAD

**Issue by polina-c** [flutter/flutter#149866] opened 2024-06-07 00:35 UTC
https://pub.dev/packages/flutter_markdown gets images differently depending on platform and on build mode.

Markdown:
```
...
click the ![import]($uploadImageUrl) button
...
```

uploadImageUrl:
```
  const isWebProd = kIsWeb && !kDebugMode;
  const imagePath = isWebProd ? 'assets/' : '';
  final uploadImageUrl = '${imagePath}assets/img/doc/upload_$filePostfix.png';
```

Relates SO post: https://stackoverflow.com/questions/62292512/firebase-flutter-web-app-works-locally-but-when-deployed-images-are-not-shown
 

PR in DevTools that has to do this trick: https://github.com/flutter/devtools/pull/7843/files#diff

**Comment by huycozy** [comment] 2024-06-07 10:24
Hi @polina-c 
I checked this using [basic_markdown_demo](https://github.com/flutter/packages/blob/main/packages/flutter_markdown/example/lib/demos/basic_markdown_demo.dart) sample code which loads an asset as `![import](assets/logo.png)` but I see the `logo.png` still is displaying on both `debug` and `release` modes. 

Can you provide more clues to reproduce this issue?

**Comment by polina-c** [comment] 2024-06-07 17:19
Sure!
Steps to repro:

1. Checkout https://github.com/flutter/devtools at 40b9a2ccfe98bcbfa5751ce24dc68b9cdc004acf
2. cd packages/devtools_app
3. Run `dart run benchmark/scripts/run_benchmarks.dart`
4. See it is passing
5. Replace `const imagePath = isWebProd ? 'assets/' : '';` with  `const imagePath = ''`
6. Run the script again
7. See it fails with error, while it is expected not to fail:
 
```
Unrecognized URL path: /assets/img/doc/upload_dark.png
Unhandled exception:
Caught browser-side error: Instance of 'ProgressEvent'
```
8. Run `flutter run -d chrome`
9. In opened Chrome navigate to Memory tab
10. Find arrow rendered:

<img width="400" alt="Screenshot 2024-06-07 at 10 12 18 AM" src="https://github.com/flutter/flutter/assets/12115586/21ee4e89-8069-42b2-abda-e20fe4f000fa">

9 . Run:
```
flutter build web --release --no-tree-shake-icons
cd build/web
python3 -m http.server 8000
```
10. Open http://localhost:8000/home
11. Navigate to Momory tab
12. See the arrow is not here

**Comment by polina-c** [comment] 2024-06-07 17:20
```
Flutter 3.23.0-12.0.pre • channel [user-branch] • unknown source
Framework • revision 35ae519140 (10 days ago) • 2024-05-29 00:33:07 -0400
Engine • revision b26e1b023c
Tools • Dart 3.5.0 (build 3.5.0-191.0.dev) • DevTools 2.36.0-dev.10
```

**Comment by polina-c** [comment] 2024-06-07 17:20
I am on Apple M1 Pro

**Comment by polina-c** [comment] 2024-06-07 17:25
> Hi @polina-c I checked this using [basic_markdown_demo](https://github.com/flutter/packages/blob/main/packages/flutter_markdown/example/lib/demos/basic_markdown_demo.dart) sample code which loads an asset as `![import](assets/logo.png)` but I see the `logo.png` still is displaying on both `debug` and `release` modes.
> 
> Can you provide more clues to reproduce this issue?

May be basic example will repro if you serve web, not just do `flutter run ...`:

```
flutter build web --release --no-tree-shake-icons
cd build/web
python3 -m http.server 8000
```

**Comment by huycozy** [comment] 2024-06-10 07:55
Thanks for your update, @polina-c. I can't reproduce this with [basic_markdown_demo](https://github.com/flutter/packages/blob/main/packages/flutter_markdown/example/lib/demos/basic_markdown_demo.dart) sample code (non-edited version) but I can reproduce with [devtools](https://github.com/flutter/devtools) as shared above. Labeling the issue for input from others.

![Screenshot 2024-06-10 at 14 54 49](https://github.com/flutter/flutter/assets/104349824/3aa15ce6-5602-4fee-825a-dce6371a1fac)


<details>
<summary>flutter doctor -v</summary>

```bash
[!] Flutter (Channel master, 3.23.0-13.0.pre.168, on macOS 14.1 23B74 darwin-x64, locale en-VN)
    • Flutter version 3.23.0-13.0.pre.168 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 32081aab69 (34 hours ago), 2024-06-08 10:35:21 -0700
    • Engine revision 1cdbebee19
    • Dart version 3.5.0 (build 3.5.0-236.0.dev)
    • DevTools version 2.36.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode15.3.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /Applications/Android Studio.app/
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 2B171FDH20084L                           • android-arm64  • Android 14 (API 34)
    • iPhone (mobile)  • d9a94afe2b649fef56ba0bfeb052f0f2a7dae95e • ios            • iOS 15.8 19H370
    • macOS (desktop)  • macos                                    • darwin-x64     • macOS 14.1 23B74 darwin-x64
    • Chrome (web)     • chrome                                   • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by stuartmorgan** [comment] 2024-06-11 19:49
@polina-c Is this actually related to `flutter_markdown`, or is it a general assets behavior and this specific repro just happens to use `flutter_markdown`?

**Comment by polina-c** [comment] 2024-06-12 20:03
> @polina-c Is this actually related to `flutter_markdown`, or is it a general assets behavior and this specific repro just happens to use `flutter_markdown`?

There is no issues with other images in DevTools, rendered without markdown.

**Comment by yjbanov** [comment] 2024-06-20 18:14
I think this is a duplicate of https://github.com/flutter/flutter/issues/86833

**Closed by yjbanov** 2024-06-20 18:14 UTC
Labels: platform-web, package, has reproducible steps, p: flutter_markdown, team-web, found in release: 3.23
