### ISSUE TITLE
PlatformView (AndroidView and UIKitView) does not constrain painted content from plugin even when parent object provides bounded layout constraints

### ISSUE THREAD

**Issue by sjschultze** [flutter/flutter#85791] opened 2021-07-02 17:42 UTC
Filing this issue to put #85171 back on the stack after it was closed as "invalid" by @TahaTesser, who couldn't get the build to work.  After it was closed I posted [a build fix and more details](https://github.com/flutter/flutter/issues/85171#issuecomment-873155214). Anybody should now be able to build and replicate the issue.

**Comment by TahaTesser** [comment] 2021-07-05 08:48
duplicate of https://github.com/flutter/flutter/issues/85171,pleaase follow up there
Thank you

**Closed by TahaTesser** 2021-07-05 08:48 UTC
Labels: in triage
