### ISSUE TITLE
Misplaced shadows on transformed objects

### ISSUE THREAD

**Issue by wmleler** [flutter/flutter#18376] opened 2018-06-11 21:30 UTC
If you 3D transform a set of material widgets using a Transform widget, the material shadows can appear in the wrong place. To see this, here's a simple example:
https://gist.github.com/wmleler/68281434cb704504ca069140105669aa
Run this file in Flutter (change its name to main.dart, of course).
Display it in the iOS simulator, in an iPhone X - 11.3
This is what you get:

![matrix1](https://user-images.githubusercontent.com/50357/41257750-d7b034be-6d82-11e8-9bde-31d0c81c6768.png)

Note the shadow on the FAB. This will happen on any device (iOS or Android, physical or emulated). It just happens for different rotations depending on the physical size of the screen.

**Comment by jslavitz** [comment] 2018-07-03 21:45
I'm not getting anything to display with that code on an emulated iphone x 11.4: 
![screen shot 2018-07-03 at 2 44 26 pm](https://user-images.githubusercontent.com/7806031/42245967-aecc2bee-7ecf-11e8-9d52-0010ebf20544.png)

**Comment by wmleler** [comment] 2018-07-04 03:29
This appears to be a bug in the master branch. If I switch to flutter
channel beta, then it does work.
The bug seems to be that if you have a Transform widget that does a rotateX
or rotateY with a rotation value of anything other than zero, then nothing
is drawn.

**Comment by wmleler** [comment] 2018-07-04 03:46
The bug is also in the dev branch.

**Comment by jslavitz** [comment] 2018-07-06 21:29
Ok, also if I'm not mistaken, it looks like this shadow is actually drawn in the framework, not the engine.

**Comment by jslavitz** [comment] 2018-07-10 23:31
Ok, so I looked into this a fair bit and it definitely seems to be an issue with skia and not with flutter or the engine. There's some magic constants in the physical_shape_layer.drawshadow function (added by a skia developer) that seem to heavily impact how the shadows are drawn. I'm also guessing part of the error comes from from using the wrong transformation matrix when projecting the shadows onto the shadow plane. 

I'm thinking the target functionality should be to render the shadows so they look the same way they do in 2d, with the entire plane (shadows included) rendered in perspective. (As I don't think skia is designed to render 3d shadows anyway).

I'm also wondering if another way to fix this may be to render the shadows before we apply the perspective transformation.

**Comment by zoechi** [comment] 2019-01-24 13:25
Emulator
![screenshot_20190124-142101](https://user-images.githubusercontent.com/405837/51681053-c8e50400-1fe3-11e9-8436-6081860a1469.png)

Pixel XL
![screenshot_1548336053](https://user-images.githubusercontent.com/405837/51680959-81f70e80-1fe3-11e9-8a2b-30e2bd3116fd.png)

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.3 18D42, locale en-AT)
[✓] Connected device (2 available)
    • Pixel XL                  • HT69V0203649  • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)
```

**Comment by markusaksli-nc** [comment] 2020-10-19 10:23
Closing this as probably fixed since it is no longer reproducible on the latest master `1.23.0-19.0.pre.95` (emulator and physical).
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.23.0-19.0.pre.95, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.23.0-19.0.pre.95 at C:\Development\flutter_master
    • Framework revision a837557634 (24 hours ago), 2020-10-18 06:12:02 -0400
    • Engine revision 499a70f5e2
    • Dart version 2.11.0 (build 2.11.0-234.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.4818.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 86.0.622.38

• No issues found!
```
</details>

**Closed by markusaksli-nc** 2020-10-19 10:23 UTC
Labels: P4, dependency: skia, engine
