### ISSUE TITLE
About HDR problem

### ISSUE THREAD

**Issue by wswszhys** [flutter/flutter#130766] opened 2023-07-18 01:22 UTC
Hi, I was writing a video player using Flutter and encountered the following problem.
```
18:37:45.133  E  getHdrCapabilities failed for display -1: Invalid display
18:37:45.134  I  Reconfiguring input devices.  changes=0x00000004
18:37:45.134  D  EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
18:37:45.135  E  getSupportedPerFrameMetadata failed for display -1: Invalid display
18:37:45.156  E  *** FATAL EXCEPTION IN SYSTEM PROCESS: ActivityManager
                 java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.view.Display$HdrCapabilities.getSupportedHdrTypes()' on a null object reference
                 	at com.android.server.display.LogicalDisplay.updateRuntimeDisplayInfoLocked(LogicalDisplay.java:283)
                 	at com.android.server.display.DisplayManagerService.getDisplayInfoInternal(DisplayManagerService.java:548)
                 	at com.android.server.display.DisplayManagerService.access$2000(DisplayManagerService.java:145)
                 	at com.android.server.display.DisplayManagerService$BinderService.getDisplayInfo(DisplayManagerService.java:1577)
                 	at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:124)
                 	at android.hardware.display.DisplayManagerGlobal.getCompatibleDisplay(DisplayManagerGlobal.java:199)
                 	at android.hardware.display.DisplayManager.getOrCreateDisplayLocked(DisplayManager.java:393)
                 	at android.hardware.display.DisplayManager.getDisplay(DisplayManager.java:316)
                 	at com.android.server.am.ActivityStackSupervisor.getActivityDisplayOrCreateLocked(ActivityStackSupervisor.java:4306)
                 	at com.android.server.am.ActivityStackSupervisor.handleDisplayAdded(ActivityStackSupervisor.java:4273)
                 	at com.android.server.am.ActivityStackSupervisor.access$100(ActivityStackSupervisor.java:192)
                 	at com.android.server.am.ActivityStackSupervisor$ActivityStackSupervisorHandler.handleMessage(ActivityStackSupervisor.java:4722)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loop(Looper.java:193)
                 	at android.os.HandlerThread.run(HandlerThread.java:65)
                 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
18:37:45.163  E  Failed to handle method call
                 java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.view.Display$HdrCapabilities.getSupportedHdrTypes()' on a null object reference
                 	at android.os.Parcel.createException(Parcel.java:1948)
                 	at android.os.Parcel.readException(Parcel.java:1910)
                 	at android.os.Parcel.readException(Parcel.java:1860)
                 	at android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayInfo(IDisplayManager.java:405)
                 	at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:124)
                 	at android.hardware.display.DisplayManagerGlobal.getCompatibleDisplay(DisplayManagerGlobal.java:181)
                 	at android.hardware.display.DisplayManagerGlobal.getRealDisplay(DisplayManagerGlobal.java:213)
                 	at android.hardware.display.DisplayManagerGlobal.createVirtualDisplay(DisplayManagerGlobal.java:424)
                 	at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:617)
                 	at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:608)
                 	at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:559)
                 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:59)
                 	at io.flutter.plugin.platform.PlatformViewsController$1.configureForVirtualDisplay(PlatformViewsController.java:541)
                 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:219)
                 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
                 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
                 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
                 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
                 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
                 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                 	at android.os.Handler.handleCallback(Handler.java:873)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loop(Looper.java:193)
                 	at android.app.ActivityThread.main(ActivityThread.java:6669)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                 Caused by: android.os.RemoteException: Remote stack trace:
                 	at com.android.server.display.LogicalDisplay.updateRuntimeDisplayInfoLocked(LogicalDisplay.java:283)
                 	at com.android.server.display.DisplayManagerService.getDisplayInfoInternal(DisplayManagerService.java:548)
                 	at com.android.server.display.DisplayManagerService.access$2000(DisplayManagerService.java:145)
                 	at com.android.server.display.DisplayManagerService$BinderService.getDisplayInfo(DisplayManagerService.java:1577)
                 	at android.hardware.display.IDisplayManager$Stub.onTransact(IDisplayManager.java:52)
18:37:45.169  E  System zygote died with exception
                 java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.view.Display$HdrCapabilities.getSupportedHdrTypes()' on a null object reference
                 	at com.android.server.display.LogicalDisplay.updateRuntimeDisplayInfoLocked(LogicalDisplay.java:283)
                 	at com.android.server.display.DisplayManagerService.getDisplayInfoInternal(DisplayManagerService.java:548)
                 	at com.android.server.display.DisplayManagerService.access$2000(DisplayManagerService.java:145)
                 	at com.android.server.display.DisplayManagerService$BinderService.getDisplayInfo(DisplayManagerService.java:1577)
                 	at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:124)
                 	at android.hardware.display.DisplayManagerGlobal.getCompatibleDisplay(DisplayManagerGlobal.java:199)
                 	at android.hardware.display.DisplayManager.getOrCreateDisplayLocked(DisplayManager.java:393)
                 	at android.hardware.display.DisplayManager.addPresentationDisplaysLocked(DisplayManager.java:376)
                 	at android.hardware.display.DisplayManager.getDisplays(DisplayManager.java:352)
                 	at android.media.MediaRouter$Static.getAllPresentationDisplays(MediaRouter.java:345)
                 	at android.media.MediaRouter$RouteInfo.choosePresentationDisplay(MediaRouter.java:2000)
                 	at android.media.MediaRouter$RouteInfo.updatePresentationDisplay(MediaRouter.java:1990)
                 	at android.media.MediaRouter$Static.updatePresentationDisplays(MediaRouter.java:352)
                 	at android.media.MediaRouter$Static.onDisplayAdded(MediaRouter.java:331)
                 	at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:630)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loop(Looper.java:193)
                 	at com.android.server.SystemServer.run(SystemServer.java:466)
                 	at com.android.server.SystemServer.main(SystemServer.java:297)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)
18:37:45.169  D  Shutting down VM
18:37:45.169  I  Sending signal. PID: 22884 SIG: 9
18:37:45.266  E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int[] android.view.Display$HdrCapabilities.getSupportedHdrTypes()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.view.Display$HdrCapabilities.getSupportedHdrTypes()' on a null object reference
                 	at android.os.Parcel.createException(Parcel.java:1948)
                 	at android.os.Parcel.readException(Parcel.java:1910)
                 	at android.os.Parcel.readException(Parcel.java:1860)å
                 	at android.hardware.display.IDisplayManager$Stub$Proxy.getDisplayInfo(IDisplayManager.java:405)
                 	at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:124)
                 	at android.hardware.display.DisplayManagerGlobal.getCompatibleDisplay(DisplayManagerGlobal.java:181)
                 	at android.hardware.display.DisplayManagerGlobal.getRealDisplay(DisplayManagerGlobal.java:213)
                 	at android.hardware.display.DisplayManagerGlobal.createVirtualDisplay(DisplayManagerGlobal.java:424)
                 	at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:617)
                 	at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:608)
                 	at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:559)
                 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:59)
                 	at io.flutter.plugin.platform.PlatformViewsController$1.configureForVirtualDisplay(PlatformViewsController.java:541)
                 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:219)
                 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
                 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
                 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
                 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
                 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
                 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                 	at android.os.Handler.handleCallback(Handler.java:873)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loop(Looper.java:193)
                 	at android.app.ActivityThread.main(ActivityThread.java:6669)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                 Caused by: android.os.RemoteException: Remote stack trace:
                 	at com.android.server.display.LogicalDisplay.updateRuntimeDisplayInfoLocked(LogicalDisplay.java:283)
                 	at com.android.server.display.DisplayManagerService.getDisplayInfoInternal(DisplayManagerService.java:548)
                 	at com.android.server.display.DisplayManagerService.access$2000(DisplayManagerService.java:145)
                 	at com.android.server.display.DisplayManagerService$BinderService.getDisplayInfo(DisplayManagerService.java:1577)
                 	at android.hardware.display.IDisplayManager$Stub.onTransact(IDisplayManager.java:52)
                 
                 )
                 #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
                 #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
                 <asynchronous suspension>
                 #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1100:28)
                 <asynchronous suspension>
                 #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:763:5)
                 <asynchronous suspension>
                 #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:790:7)
                 <asynchronous suspension>
                 #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
                 <asynchronous suspension>
18:37:45.289  I  Framework disconnect
18:37:45.521  I  lmkd data connection dropped
18:37:45.521  I  closing lmkd data connection
18:37:45.528  W  statscompanion service died
```

**Comment by darshankawar** [comment] 2023-07-18 07:38
@wswszhys 
When opening an issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with.
Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without any third party package implementation along with [flutter doctor -v](https://stackoverflow.com/help/minimal-reproducible-example) so that we can address it properly.

**Comment by wswszhys** [comment] 2023-07-18 14:26
I wrote a native player based on libvlc and it worked properly. Then I migrated the logic to Flutter and used "flutter_vlc_player" plugin.I changed the VLCTextureview in its code to Surfaceview, can play normally on regular Android phones. However, when I installed it on a TV box, I encountered the above error. I saw similar issues elsewhere ([issue](https://github.com/nova-video-player/aos-AVP/issues/743),[fix](https://github.com/nova-video-player/aos-Video/commit/87cb5d090e6ddd3c3924c089a6e5e1f1b87ae041)), and I'm not sure if it's caused by Flutter's underlying code.

`18:37:45.266  E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int[] android.view.Display$HdrCapabilities.getSupportedHdrTypes()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.view.Display$HdrCapabilities.getSupportedHdrTypes()' on a null object reference`

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 11.7.8 20G1351 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 3.10.6 on channel stable at
      /Users/wzlu/Documents/software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (6 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/wzlu/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/wzlu/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.7.8 20G1351
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.
```

**Comment by darshankawar** [comment] 2023-07-19 05:26
The error log seems to be mostly coming from native Android. In order to properly address the issue, please provide us minimal code sample or a repo that we can clone to verify it properly.

**Comment by wswszhys** [comment] 2023-07-20 01:49
Forget it, I don't have to solve this problem either. But I think based on your experience, it should be easy to identify the problem. The native app I wrote has no problems running on TVBox except for Flutter. Perhaps TVBox needs a native app instead of Flutter. Yesterday, I tried to modify Flutter. Gradle, but the problem still persists. I often have difficulty accessing GitHub and cannot upload it. Please close the issue

**Comment by huycozy** [comment] 2023-07-20 05:02
Closing issue from here. Once you can provide more information, please write in the comments and we will open the issue for further investigation.

**Closed by huycozy** 2023-07-20 05:02 UTC
Labels: in triage
