### ISSUE TITLE
Module development tests with the flutter run command are inconvenient

### ISSUE THREAD

**Issue by qssq** [flutter/flutter#95717] opened 2021-12-23 07:38 UTC
## Use case

flutter app module test ,by flutter commond or  ide,
During the production development phase, I needed to test the Flutter as a normal application. But it's very troublesome. I need to copy all the files so that I can run some tests. Android I plan to use native development and reference some Of the Flutter modules, but ios uses the whole Flutter project, so I created a module project, but Android only uses some of the features, while ios devices use all of the features. But I encountered a very difficult problem in the process of development, the module will automatically generate. Android folder, modification is usually invalid, will automatically restore.
## Proposal
Module development tests with the flutter run command are inconvenient because android folders are automatically restored after modification and cannot be tested on Windows.

**Comment by mamuseferha** [comment] 2021-12-23 09:10
Hi @qssq 
Can you please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so I can verify this on my end?
Thank you

**Comment by qssq** [comment] 2021-12-23 15:37
why ,module launch not contain android folder,but auto genereate .android  so  auto delete. but i need keep .android folder  or include android folder

**Comment by mamuseferha** [comment] 2021-12-27 08:16
Hi @qssq, From what I understand you have a flutter module project that does not include the android folder. But when you run tests in the project, the folder is automatically generated which is not convenient for you.

So can you please provide a sample code, a simple reproducible project so i can confirm this behavior on my end too?

**Comment by qssq** [comment] 2021-12-27 08:22
This does not require a demo. You have always stressed the need to provide a demo. Is it Yi? If necessary, you can create a module with the command, and then add a value under the Android project, or modify the Android manifest XML app_ Name, and then execute the operations such as fluent clean and pub get to replicate this operation. What I said about automatic deletion is that it will be restored after a series of operations, but it is normal to directly modify and then fluent run. However, I do develop based on modules, but I do not want to restore some specific properties. This is a bit of a headache.

**Comment by mamuseferha** [comment] 2021-12-28 07:38
@qssq, it is not normal to modify the contents of .android directory as it it autogenerated and the content can be changed/deleted anytime. See https://docs.flutter.dev/development/add-to-app/android/project-setup#create-a-flutter-module

There's also a discussion here why it is neccessary/or not to modify the content of the .android folder https://github.com/flutter/flutter/issues/32989
https://github.com/flutter/flutter/issues/28135


You can make changes in your wrapper android folder instead of the autogenerated .android folder.

I'll go ahead and close this as a duplicate of https://github.com/flutter/flutter/issues/23123, you can follow up the issue from there.

**Closed by mamuseferha** 2021-12-28 07:38 UTC
Labels: in triage
