### ISSUE TITLE
Flutter App crashes when ImagePicker is called double tapped

### ISSUE THREAD

**Issue by PreritO** [flutter/flutter#19819] opened 2018-07-26 15:56 UTC
Hi everyone, I seem to be having a problem using the flutter image_picker plugin. My application is crashing whenever I double tap a button which launches image_picker with the following error:

![image](https://user-images.githubusercontent.com/9142309/43272634-b70e12dc-90b7-11e8-9b1a-21211a8d12a8.png)

## Steps to Reproduce

1. Open the demo image_picker application 
3. Double-Tap the camera icon to take an image
2. Click "Deny" when the runtime permissions dialog comes up asking for phone to grant permissions
4. Application crashes

## Logs

![image](https://user-images.githubusercontent.com/9142309/43273521-e0fbb53e-90b9-11e8-9a2b-e8d1440fe07e.png)

## Flutter Analyze

![image](https://user-images.githubusercontent.com/9142309/43273586-0d2bddd2-90ba-11e8-91a1-e4a4b3949c3c.png)

## Flutter Doctor

![image](https://user-images.githubusercontent.com/9142309/43273628-26b30c44-90ba-11e8-9e4b-a8259ffc6e55.png)

**Comment by PreritO** [comment] 2018-08-03 20:01
Hey! Has anyone looked at this issue from Flutter yet? Would really appreciate some feedback on how I should continue with this.

**Comment by anthonylauzon** [comment] 2018-12-05 04:59
https://github.com/flutter/plugins/pull/958

**Comment by Will-W** [comment] 2019-01-10 14:37
An even simpler method of repeating this is to double tap the button, then take a photo but press cancel. For others with the same issue, this is the code I am using to work around the problem, as suggested by @zoechi:

```
bool _pickInProgress = false;

_pickPhoto(ImageSource source) async {
  if (_pickInProgress) {
    return;
  }
  _pickInProgress = true;
  var image = await ImagePicker.pickImage(source: source);
  if (image != null) {
    setState(() {
      images.add(image);
    });
  }
  _pickInProgress = false;
}
```

**Comment by anthonylauzon** [comment] 2019-01-10 22:18
they fixed this in the main branch https://github.com/flutter/plugins/commit/61d6a1f63ba9b5c698c8a2c907f8c976f8cb6960

**Comment by Will-W** [comment] 2019-01-11 07:07
No, that commit fixes #1051, which is slightly different, and has been released with 0.4.12
This bug occurs on (at least) Android, and is still present in 0.4.12.

**Comment by callumclift** [comment] 2019-01-20 16:51
Was having a similar issue in my app and the workaround by @Will-W seems to have stopped the crashing! Much appreciated!

**Closed** 2019-01-31 19:48 UTC
Labels: p: first party, p: image_picker, plugin, severe: crash

**Comment by cyanglaz** [comment] 2019-01-31 19:54
This issue has been resolved with https://github.com/flutter/plugins/pull/1093
Please update the version of Image Picker to 0.5.0+1.
I'm closing the issue. If any related issue has been found, please reopen the ticket with additional details.

**Comment by ngoctranfire** [comment] 2020-02-19 11:48
I'm sadly still able to reproduce this and I'm on Android and on this version

`  image_picker: ^0.6.0+17`

Here is what my error looks like:

`java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 6932): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime( 6932): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime( 6932): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 6932): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 6932): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 6932): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime( 6932): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 6932): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 6932): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 6932): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6932): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 6932): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 6932): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 6932): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.finishWithSuccess(ImageCropperDelegate.java:115)
E/AndroidRuntime( 6932): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.onActivityResult(ImageCropperDelegate.java:99)
E/AndroidRuntime( 6932): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime( 6932): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime( 6932): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime( 6932): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime( 6932): 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
E/AndroidRuntime( 6932): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime( 6932): 	... 11 more
I/Process ( 6932): Sending signal. PID: 6932 SIG: 9`

**Comment by kw2019ltd** [comment] 2020-07-06 06:15
same getting, using latest ver 

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.sangcomz.fishbun.adapter.image.ImageAdapter.loadImage(android.widget.ImageView, android.net.Uri)' on a null object reference
       at com.sangcomz.fishbun.adapter.view.PickerGridAdapter.onBindViewHolder(PickerGridAdapter.java:98)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
       at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
       at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
       at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
       at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1892)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
       at android.view.View.layout(View.java:20710)
       at android.view.ViewGroup.layout(ViewGroup.java:6198)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2871)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2398)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1534)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7420)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1100)
       at android.view.Choreographer.doCallbacks(Choreographer.java:895)
       at android.view.Choreographer.doFrame(Choreographer.java:826)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1086)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
