### ISSUE TITLE
Run a Flutter desktop app on Windows 32 bits

### ISSUE THREAD

**Issue by eakeur** [flutter/flutter#83561] opened 2021-05-28 14:32 UTC
## Use case

I am developing an application for Android, web and Windows devices for a client of mine. Everything was going well until this client came to me with a 32 bit Windows machine and, for my surprise, the desktop build of my app won't run on 32 bits environments. I know I can use the Flutter Web build, which is already stable, as a PWA, but it is of my interest also run it as a desktop windows application.

## Proposal

Is there any way of running this app in a 32 bits enviroment? If not, do you people plan to add this feature to the future versions of flutter?

**Comment by stuartmorgan** [comment] 2021-05-28 14:47
Duplicate of https://github.com/flutter/flutter/issues/37777

**Closed by stuartmorgan** 2021-05-28 14:47 UTC
