### ISSUE TITLE
TextField causing assertion errors on hot reload

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#26714] opened 2019-01-17 18:59 UTC
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(HelloWorld());

Widget field(String placeholder) {
  return Theme(
    data: ThemeData(textSelectionColor: Colors.orange.shade200),
    child: TextField(
      textAlign: TextAlign.center,
      controller: TextEditingController(text: placeholder),
    ),
  );
}

class HelloWorld extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: DefaultTextStyle.merge(
          style: const TextStyle(fontSize: 10),
          child: ListView(
            children: <Widget>[
              field('Cyan'),
              field('Orange'),
              field('Thick Rounded Cursor'),
            ],
          ),
        ),
      ),
    );
  }
}
```

1. Run the above app.
2. Change `textAlign` to `TextAlign.start`.
3. Hot reload will throw assertions.

## Logs

```
I/flutter ( 4166): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4166): The following assertion was thrown during performLayout():
I/flutter ( 4166): 'package:flutter/src/painting/text_painter.dart': Failed assertion: line 300 pos 12:
I/flutter ( 4166): '!_needsLayout': is not true.
```

## Info
* This is from flutter master (currently at https://github.com/flutter/flutter/commit/7e22b5f2c58db166522d5c4061aaead542f84512).
* I'm running the app using VS Code (which does hot reload on save).

**Comment by zoechi** [comment] 2019-01-18 07:40
Duplicate of #20611

**Closed by zoechi** 2019-01-18 07:40 UTC
Labels: framework, t: hot reload

**Comment by kkacquah** [comment] 2019-07-21 21:14
The error here #36640 seems to be related to this.
