### ISSUE TITLE
Trigger AppLifecycleState when a dialog is open or unfocus the render of base widget

### ISSUE THREAD

**Issue by parmarravi** [flutter/flutter#93205] opened 2021-11-07 05:32 UTC
I have noticed a couple of things when integrating Lottie animations in a flutter. And I want to know how can we improve the performance with Lottie in a flutter

The Test is done on One Plus 7T mobile.

1.) Lottie animated file renders the view frequently and the frame rate is 30

Can this be improved? I have already taken out Lottie in a separate stateless widget to avoid rendering the entire widget every time

![image](https://user-images.githubusercontent.com/7616089/140633609-904d6a2e-d2e2-48e4-9e45-682088b8a76d.png)

2.) There is a second scenario where the performance is heavily impacted and I think flutter core has to do something in this.

Suppose you have a screen with flutter animation or some gif going on and you open a dialog with another flutter file running, the screen will render a lot in this case as two animations are running.

The flutter core should be clever enough to prevent any such render on the screen with the focus moving to the dialog instead of running both animations.

With Two Lottie animations one on dialog and one below the screen.

![image](https://user-images.githubusercontent.com/7616089/140633635-17a8abc3-31f4-4111-9fb6-31786781e7c3.png)

Lottie animation without dialog

![image](https://user-images.githubusercontent.com/7616089/140633657-50e94b26-2cb7-4e81-8f34-976b16f3605e.png)

**Comment by parmarravi** [comment] 2021-11-07 06:41
One way, I stop the animation is Using Getx obx.

I listened to retry dialog state and use the obx value in Lottie animation to stop or play animation when the dialog is open or close. 

This does work and improves the performance.

Another thing I have noticed is if I have a screen with a lot of widgets and the Lottie animated widget is placed extremely below in screen the screen keeps on rendering even if the widget is not visible until I scroll the screen.

This should be improved like a recycler view in android if the widget is not visible the screen should not render that widget. when the user scrolls the widget should render as per that thus recycling the widgets on the screen.

**Comment by maheshmnj** [comment] 2021-11-08 11:16
Hi @parmarravi,

> 1.) Lottie animated file renders the view frequently and the frame rate is 30
Can this be improved?

I believe the frames are dropping because the  UI thread is getting blocked, to find the exact cause of the issue a  [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) is required along with your output of `flutter doctor -v`.

> Suppose you have a screen with flutter animation or some gif going on and you open a dialog with another flutter file running, the screen will render a lot in this case as two animations are running.

Flutter runs on a single thread so I believe this is expected to happen as the control keeps shifting frequently between to animations as both are simultaneously running. As an alternative, I think you should pause the animation beneath the dialog when the dialog comes into focus and resume when the dialog disposes off for better performance.


> Another thing I have noticed is if I have a screen with a lot of widgets and the Lottie animated widget is placed extremely below in screen the screen keeps on rendering even if the widget is not visible until I scroll the screen.

For lazy loading widgets, you need to make sure you are using widgets like `ListView.builder` which creates widgets on-demand which are within the [cacheExtent](https://api.flutter.dev/flutter/rendering/RenderViewportBase/cacheExtent.html), On the Other Hand Scroll Widgets like ListView, SingleChildScrollView they render all the children at once and this might affect the performance and might cause a jank while scrolling depending on the number of widgets and How heavy a widget is.

**Comment by parmarravi** [comment] 2021-11-08 16:28
cant SingleChildScrollView default behavior can be a lazy loading widget?

**Comment by maheshmnj** [comment] 2021-11-09 05:55
> cant SingleChildScrollView default behavior can be a lazy loading widget?

Flutter does provide complex scrolling behaviors with lazy load with the help of Slivers, I would recommend you to check the [Slivers Docs](https://flutter.dev/docs/development/ui/advanced/slivers), specifically this [slivers workshop.](https://youtu.be/YY-_yrZdjGc) for your use case which transforms a SingleChildScrollView to a SliverList.

**Comment by maheshmnj** [comment] 2021-12-06 12:39
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by maheshmnj** 2021-12-06 12:39 UTC
