### ISSUE TITLE
Problems for running selected targets

### ISSUE THREAD

**Issue by Nopik** [flutter/flutter#94724] opened 2021-12-06 15:17 UTC
When using multiple targets in single app (e.g. by defining widgetbook application), when they are both run, it breaks hot-restart and hot-reload functionality. This happens on latest stable (2.5.3), and seem to be a regression fixed in https://github.com/flutter/flutter/issues/91535 few days after last stable release. That fix, however, is marked as 2.6 version, while I'm also experiencing it on 2.5.3.

## Steps to Reproduce

1. Create new application
2. Copy `lib/main.dart` to `lib/main2.dart`
3. Modify `lib/main2.dart` to contain visible changes (e.g. change homepage title to `Flutter Demo Home Page 2`).
4. Add `shared_preferences` to pubspec.yaml (`flutter pub add shared_preferences`).
5. Run main app: `flutter run -t lib/main.dart -d iphone`
6. Optionally: verify that hot reload and hot restart work as expected
7. Without stopping the first app, run second app: `flutter run -t lib/main2.dart -d macos`
8. Verify that hot-reload works fine on macos app
9. In this moment hot-reload stops working on iphone app completely. If hot restart is performed, wrong target (`main2.dart`) gets loaded instead. 

Problem goes away after updating Flutter to beta (`2.8.0-3.3.pre`), as it already contains the fix for issue mentioned above.

**Comment by stuartmorgan** [comment] 2021-12-06 15:35
Closing as a duplicate since, as you described above, this is already fixed. (It's not clear to me why you intentionally filed a duplicate of a fixed issue.)

**Closed by stuartmorgan** 2021-12-06 15:35 UTC

**Comment by Nopik** [comment] 2021-12-06 15:49
I opened this, as the bugfix mentioned is marked as 2.6 and not released as a part of the stable branch. So, I want to make sure that the next stable release (2.5.4?) will contain it as well. Will it?

**Comment by Nopik** [comment] 2021-12-06 15:51
Specifically, it was mentioned that the bug was not reproducible before on stable - but I am able to reproduce it there.

**Comment by Nopik** [comment] 2021-12-06 16:55
@stuartmorgan will the fix mentioned above be released in Flutter 2.5.4?

**Comment by stuartmorgan** [comment] 2021-12-06 17:23
> @stuartmorgan will the fix mentioned above be released in Flutter 2.5.4?

No, the fix for this issue will not be hot-fixed on the 2.5 branch.

**Comment by Nopik** [comment] 2021-12-06 17:27
@stuartmorgan that is why I'm opening this bug - as the problem is causing 2.5.3 to misbehave, too. Can we reopen?

**Comment by stuartmorgan** [comment] 2021-12-06 17:31
No, the issue will not be re-opened. The described bug is:
- a duplicate,
- already fixed on master, and
- will not be hot-fixed on stable

There's no further work to track.
