### ISSUE TITLE
[WEB] [CanvasKit] HtmlElementView is displayed on top of new route

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#74802] opened 2021-01-27 11:03 UTC
![ezgif-6-c768241ae942](https://user-images.githubusercontent.com/814785/105980747-8b655680-6095-11eb-9168-605879386e02.gif)

instead of

![good](https://user-images.githubusercontent.com/814785/105983282-c7e68180-6098-11eb-90ff-a986d377d935.gif)

/cc @yjbanov @hterkelsen 

```dart
import 'dart:html';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

final String src1 =
    'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4';
final String src2 =
    'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              WebVideoElement(src: src1),
              ElevatedButton(
                onPressed: () {
                  Navigator.of(context).push(
                    MaterialPageRoute(
                      builder: (_) => SecondPage(),
                    ),
                  );
                },
                child: Text('PRESS ME'),
              ),
            ],
          ),
        ));
  }
}

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: WebVideoElement(src: src2),
      ),
    );
  }
}

class WebVideoElement extends StatefulWidget {
  WebVideoElement({Key key, this.src}) : super(key: key);

  final String src;

  @override
  _WebVideoElementState createState() => _WebVideoElementState();
}

class _WebVideoElementState extends State<WebVideoElement> {
  @override
  void initState() {
    super.initState();
    ui.platformViewRegistry.registerViewFactory(
      widget.src,
      (int viewId) => VideoElement()
        ..src = widget.src
        ..width = 320
        ..height = 180
        ..controls = false
        ..autoplay = true
        ..style.border = 'none',
    );
  }

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: SizedBox(
        width: 320,
        height: 180,
        child: HtmlElementView(viewType: widget.src),
      ),
    );
  }
}
```

```
[✓] Flutter (Channel master, 1.26.0-13.0.pre.194, on macOS 11.1 20C69 darwin-arm, locale de)
    • Flutter version 1.26.0-13.0.pre.194 at /Users/ben/development/flutter
    • Framework revision 71aec53acb (5 hours ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ben/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/ben/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/ben/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.1 20C69 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-01-27 14:43
Hi @cbenhagen 
I can reproduce the issue, this is a duplicate of https://github.com/flutter/flutter/issues/74676
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-27 14:43 UTC
