### ISSUE TITLE
CMake Error: Error: generator : Visual Studio 17 2022 Does not match the generator used previously: Visual Studio 16 2019 Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory. Exception: Unable to generate build files

### ISSUE THREAD

**Issue by Basmala2000** [flutter/flutter#98883] opened 2022-02-21 21:46 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by stuartmorgan** [comment] 2022-02-21 21:57
Duplicate of https://github.com/flutter/flutter/issues/93680

**Closed by stuartmorgan** 2022-02-21 21:57 UTC
