### ISSUE TITLE
flutter content handler on fuchsia can only launch one app per environment

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#7266] opened 2016-12-14 23:52 UTC
Subsequent apps don't seem to start.

**Comment by apwilson** [comment] 2016-12-14 23:53
@gmesch

**Comment by abarth** [comment] 2016-12-14 23:53
Sounds like a regression because this was working previously.

**Comment by gmesch** [comment] 2016-12-15 00:17
This was https://fuchsia-review.googlesource.com/#/c/17309/. So we can close it here.

**Comment by Hixie** [comment] 2017-02-27 23:06
Closing per last comment.

**Closed by Hixie** 2017-02-27 23:06 UTC
