### ISSUE TITLE
Some Rive animations have a huge peak memory usage, leading to hardware freeze or crash

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#63120] opened 2020-08-06 19:44 UTC
Mirror issue for https://buganizer.corp.google.com/issues/150220596. 

This is with respect to some very complex Rive animations. We've done some initial communicating with the Rive team before --- see "https://github.com/2d-inc/Flare-Flutter/issues/99 and  https://github.com/2d-inc/Flare-Flutter/issues/249.

That said, until a general diagnosis is found, conversation should occur on the upstream issue.

cc @zanderso @dnfield

**Comment by dnfield** [comment] 2020-08-11 06:11
Customer provided reproduction appears to be working fine at head. I've updated the internal bug requesting either an updated reproduction or more information about what is wrong. I'll leave this assigned for now, but lowering the priority until customer can provide more detalis.

**Comment by kf6gpe** [comment] 2020-09-08 18:21
Upstream bug now has a reproducible case for Android. Upgrading priority.

**Comment by chinmaygarde** [comment] 2020-09-14 17:42
Per Ray, Dan is conducting one final investigation but there isn't expected to be too much work on this front. Setting an appropriate milestone.

**Comment by kf6gpe** [comment] 2020-09-22 16:51
Dan has one item remaining in his investigation, pending some work done by the upstream team. Leaving open, but no need to discuss at Tuesday's triage.

**Comment by dnfield** [comment] 2020-09-22 17:09
@ravenblackx actually did something similar to what I was going to try (rewrite the animation as something just in Dart).

Locally, it looks like the RSS usage is slightly lower, but still has a sizable jump, particularly when the animation is played.  For example, I observe about a 20MB spike after loading the animation initially, and a 30-40mb spike after playing it.

AFAICT, this is all or mainly GPU driver related. We really don't have control over this, and it's not something the Flutter team can further investigate - closing as WAI.

**Closed by dnfield** 2020-09-22 17:09 UTC
Labels: P2, customer: dream (g3), engine, passed first triage, perf: memory
