### ISSUE TITLE
[Impeller] Widget doesn't build properly unless wrapped with RepaintBoundary

### ISSUE THREAD

**Issue by AlexDochioiu** [flutter/flutter#127104] opened 2023-05-18 12:28 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

I attached the code below for the class that I use.

### Expected results

Widget paints properly

### Actual results

In the `UPCOMING` section, both rows are the exact same widget:
1. First one is SliverToBoxAdapter -> RepaintBoundary -> LinearPercentIndicator
2. Second one is SliverToBoxAdapter -> LinearPercentIndicator 

The one that's not wrapped inside RepaintBoundary misses some of the text in the `Reward` section.

<img width="530" alt="image" src="https://github.com/flutter/flutter/assets/38853913/edd21be4-3899-4826-b2d7-0a2c79f35b08">

### Code sample

<details><summary>Code sample</summary>

```dart
LinearPercentIndicator(
                duration: const Duration(milliseconds: 500),
                fill: LinearPercentIndicator_LineModel.gradient(
                        progressPercent: 0.5,
                        progressGradient: LinearGradient(colors: context.colorScheme.progressGradient),
                        onProgressColor: Colors.black,
                        glow: true,
                      ),
                contentBuilder: (context, color, child) => _LineContentWidget(
                  color: color,
                  date: upcomingReward!.dateTime,
                  ticker: "PSB",
                  showDateAsCountdown: true,
                  formattedRewardAmount: "2.335431,
                ),
              )
```

```dart
import 'package:core/export.dart';
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:nft_craze_wallet/config/size.dart';
import 'package:nft_craze_wallet/pages/home/wallet/wallet_page.dart';
import 'package:nft_craze_wallet/utils/color_extensions.dart';
import 'package:nft_craze_wallet/utils/ui/blur.dart';
import 'package:simple_animations/simple_animations.dart';

part 'linear_percent_indicator.freezed.dart';

@freezed
class LinearPercentIndicator_LineModel with _$LinearPercentIndicator_LineModel {
  const LinearPercentIndicator_LineModel._();

  const factory LinearPercentIndicator_LineModel.color({
    Color? progressColor,
    Color? onProgressColor,
    @Default(false) bool glow,
    required double progressPercent,
  }) = LinearPercentIndicator_LineModel_Color;

  const factory LinearPercentIndicator_LineModel.gradient({
    required Gradient progressGradient,
    Color? onProgressColor,
    @Default(false) bool glow,
    required double progressPercent,
  }) = LinearPercentIndicator_LineModel_Gradient;
}

class LinearPercentIndicator extends StatelessWidget {
  const LinearPercentIndicator({
    super.key,
    required this.duration,
    required this.fill,
    this.secondFill,
    required this.contentBuilder,
    this.backgroundColor,
    this.onBackgroundColor,
  });

  final Duration duration;

  final LinearPercentIndicator_LineModel fill;
  final LinearPercentIndicator_LineModel? secondFill;
  final ValueWidgetBuilder<Color> contentBuilder;
  final Color? backgroundColor;
  final Color? onBackgroundColor;

  @override
  Widget build(BuildContext context) {
    final maxWidth =
        ((MediaQuery.of(context).size.width - SizeConst.WINDOW_INSET * 2) / (secondFill == null ? 1 : 2.5)).atLeast(0);
    final percent = fill.progressPercent.isNaN ? 0.5 : fill.progressPercent;
    final secondPercent = secondFill == null
        ? null
        : secondFill!.progressPercent.isNaN
            ? 0.5
            : secondFill!.progressPercent;

    final leftChild = PlayAnimationBuilder(
      duration: duration,
      tween: Tween<double>(begin: 0, end: percent),
      builder: (context, value, child) => Container(
        width: maxWidth * value,
        height: SizeConst.SIZE_24x,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(10),
          gradient: fill.map(
            color: (c) => null,
            gradient: (g) => g.progressGradient,
          ),
          color: fill.map(
            color: (c) => c.progressColor ?? const Color(0xFF1A75FF),
            gradient: (g) => null,
          ),
        ),
      ),
    );

    final rightChild = secondFill == null
        ? null
        : PlayAnimationBuilder(
            duration: duration,
            tween: Tween<double>(begin: 0, end: secondPercent!),
            builder: (context, value, child) => Container(
              width: maxWidth * value,
              height: SizeConst.SIZE_24x,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(10),
                gradient: secondFill?.map(
                  color: (c) => null,
                  gradient: (g) => g.progressGradient,
                ),
                color: secondFill?.map(
                  color: (c) => c.progressColor ?? const Color(0xFF1A75FF),
                  gradient: (g) => null,
                ),
              ),
            ),
          );

    return Padding(
      padding: const EdgeInsets.only(
        bottom: SizeConst.SIZE_16x,
        left: SizeConst.WINDOW_INSET,
        right: SizeConst.WINDOW_INSET,
      ),
      child: Stack(
        alignment: Alignment.centerLeft,
        clipBehavior: Clip.none,
        children: [
          if (context.isDarkMode || backgroundColor != null)
            Container(
              height: SizeConst.SIZE_24x,
              width: double.infinity,
              clipBehavior: Clip.hardEdge,
              decoration: BoxDecoration(
                borderRadius: const BorderRadius.all(Radius.circular(10.0)),
                color: backgroundColor ?? context.colorScheme.progressBarBackground,
              ),
            ),
          contentBuilder(context, context.colorScheme.onProgressBarBackground, null),
          leftChild,
          Align(alignment: Alignment.topRight, child: rightChild),
          if (fill.glow) Blurred(tileMode: TileMode.decal, child: leftChild),
          if (secondFill?.glow == true && rightChild != null)
            Align(
              alignment: Alignment.topRight,
              child: Blurred(tileMode: TileMode.decal, child: rightChild),
            ),
          Align(
            alignment: Alignment.centerLeft,
            child: ClipRect(
              child: PlayAnimationBuilder(
                duration: duration,
                tween: Tween<double>(begin: 0, end: 1 / (secondPercent == null ? 1 : 2.5)),
                child: contentBuilder(context, fill.onProgressColor ?? Colors.white, null),
                builder: (context, value, child) => Align(
                  alignment: Alignment.centerLeft,
                  widthFactor: percent * value,
                  child: child,
                ),
              ),
            ),
          ),
          if (secondPercent != null)
            Align(
              alignment: Alignment.centerRight,
              child: ClipRect(
                child: PlayAnimationBuilder(
                  duration: duration,
                  tween: Tween<double>(begin: 0, end: secondPercent / 2.5),
                  child: contentBuilder(context, fill.onProgressColor ?? Colors.white, null),
                  builder: (context, value, child) => Align(
                    alignment: Alignment.centerRight,
                    widthFactor: value,
                    child: child,
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}

class _LineContentWidget extends StatelessWidget {
  const _LineContentWidget({
    Key? key,
    required this.color,
    required this.date,
    required this.showDateAsCountdown,
    required this.formattedRewardAmount,
    this.onRewardTextTapped,
    required this.ticker,
  }) : super(key: key);

  final Color color;
  final DateTime date;
  final bool showDateAsCountdown;

  final String formattedRewardAmount;
  final void Function(BuildContext context)? onRewardTextTapped;

  final String? ticker;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: double.maxFinite,
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: SizeConst.SIZE_12x + 2),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Expanded(
              child: showDateAsCountdown
                  ? RepaintBoundary(
                      child: CountdownTimer(
                        widgetBuilder: (context, time) => Text.rich(
                          TextSpan(
                            children: [
                              TextSpan(
                                text: context.loc.rewardsPageCountdownTimeLeft(_builderCountdownTimer(time, true)),
                                style:
                                    context.textTheme.labelSmall?.copyWith(color: color, fontWeight: FontWeight.w500),
                              ),
                            ],
                          ),
                        ),
                        endTime: date.millisecondsSinceEpoch,
                      ),
                    )
                  : Text(
                      DateFormat.yMMMd().format(date),
                      style: context.textTheme.labelSmall?.copyWith(color: color, fontWeight: FontWeight.w500),
                    ),
            ),
            GestureDetector(
              onTap: onRewardTextTapped != null ? () => onRewardTextTapped!(context) : null,
              child: DiscreteWidget(
                blurSigmaY: 3,
                child: Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(text: '$formattedRewardAmount '),
                      Constants.ADA_SYMBOL,
                      if (onRewardTextTapped != null) ...[
                        const TextSpan(text: '  '),
                        const TextSpan(
                          children: [Constants.INFO_SYMBOL],
                          style: TextStyle(fontSize: 11),
                        ),
                      ]
                    ],
                  ),
                  style: context.textTheme.labelSmall?.copyWith(
                    color: onRewardTextTapped != null ? context.colorScheme.actionBlue : color,
                    fontWeight: onRewardTextTapped != null ? FontWeight.w700 : FontWeight.w500,
                  ),
                ),
              ),
            ),
            Expanded(
              child: Text(
                ticker ?? context.loc.rewardsPageRegisteredNALabel,
                textAlign: TextAlign.right,
                style: context.textTheme.labelSmall
                    ?.copyWith(color: color, fontStyle: FontStyle.italic, fontWeight: FontWeight.w700),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-GB)
    • Flutter version 3.10.1 on channel stable at /Users/alexandrudochioiu/.asdf/installs/flutter/3.10.1-stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (35 hours ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/alexandrudochioiu/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/alexandrudochioiu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • A1A6A512-11DF-47F0-B0E6-30171868398B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2023-05-19 06:24
Thanks for the report. Seeing the same behavior as reported.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.10.1, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.10.1 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (35 hours ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.11.0-6.0.pre.154, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.11.0-6.0.pre.154 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fcba066bea (32 minutes ago), 2023-05-19 01:26:16 -0400
    • Engine revision 6bc60c8a98
    • Dart version 3.1.0 (build 3.1.0-125.0.dev)
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by AlexDochioiu** [comment] 2023-05-19 08:29
Hey @darshankawar , just reported another issue happening on the same screen https://github.com/flutter/flutter/issues/127173

**Comment by jonahwilliams** [comment] 2023-08-25 16:42
I'm trying to run this to check if it still reproduces, however pub can't seem to find nft_craze_wallet and I'm not sure how to rebuild this.

**Comment by chinmaygarde** [comment] 2023-09-01 20:08
This was part of the initial preview reports. We've done a ton of work in this area and since this isn't easy to verify, I am closing this. But feel free to re-open.

**Closed by chinmaygarde** 2023-09-01 20:08 UTC
Labels: platform-ios, engine, has reproducible steps, P2, e: impeller, found in release: 3.10, found in release: 3.11, team-engine, triaged-engine, multiteam-retriage-candidate
