### ISSUE TITLE
AnimatedCrossFade with Text is not smooth

### ISSUE THREAD

**Issue by mofada** [flutter/flutter#36429] opened 2019-07-18 06:53 UTC
I wrote a timer widget that runs fine on android, but it will flash on ios. The effect is as follows

![ios](https://user-images.githubusercontent.com/22286246/61435511-2e9ac300-a96b-11e9-8357-61880409d032.gif)

This is my code

```
import 'dart:async';

import 'date_time_util.dart' as DateTimeUtil;
import 'package:flutter/material.dart';

/// @author : fada
/// @email : fada@mofada.cn
/// @date : 2019-07-15 16:37
/// @description : 计时文字， 使用[AnimatedCrossFade]动画

class TimerText extends StatefulWidget {
  TimerText({Key key}) : super(key: key);

  @override
  TimerTextState createState() => TimerTextState();
}

class TimerTextState extends State<TimerText> with TickerProviderStateMixin {
  ///一秒的间隔
  static const _secondDuration = const Duration(seconds: 1);

  Timer _timer;
  String text = '';

  @override
  void initState() {
    super.initState();
    _timer = Timer.periodic(_secondDuration, (Timer timer) {
      setState(() {});
    });
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    String lastTime = _timer.isActive
        ? DateTimeUtil.intToHHMMSS(_timer.tick - 1)
        : '00:00:00';
    String currentTime =
        _timer.isActive ? DateTimeUtil.intToHHMMSS(_timer.tick) : '00:00:00';

    return Container(
      padding: const EdgeInsets.only(
        top: 21,
        bottom: 19,
      ),
      child: Center(
        child: AnimatedCrossFade(
          duration: _secondDuration,
          firstChild: Text(
            '练习用时：${_timer.tick % 2 == 0 ? currentTime : lastTime}',
            style: TextStyle(
              fontSize: 16,
              color: const Color(0xFFE32416),
            ),
          ),
          crossFadeState: _timer.tick % 2 == 0
              ? CrossFadeState.showFirst
              : CrossFadeState.showSecond,
          secondChild: Text(
            '练习用时：${_timer.tick % 2 != 0 ? currentTime : lastTime}',
            style: TextStyle(
              fontSize: 16,
              color: const Color(0xFFE32416),
            ),
          ),
        ),
      ),
    );
  }

  ///重置计时器
  void reset() {
    _timer.cancel();
    _timer = Timer.periodic(_secondDuration, (Timer timer) {
      setState(() {});
    });
  }

  ///获取当前总耗时
  int get time => _timer.tick;

  @override
  void didUpdateWidget(TimerText oldWidget) {
    super.didUpdateWidget(oldWidget);
  }
}

```

## Logs

```
fadadeiMac:bole_student fada$ flutter analyze
Analyzing bole_student...                                               

   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: BoleListTitle.contentWidget • lib/views/bole_list_title.dart:9:7 • must_be_immutable
   info • Avoid empty statements • lib/views/home/bole_float_button.dart:48:5 • empty_statements
   info • Dead code • lib/views/home/bole_float_button.dart:48:5 • dead_code
   info • Avoid empty statements • lib/views/home/index/notice_view.dart:60:5 • empty_statements
   info • Dead code • lib/views/home/index/notice_view.dart:60:5 • dead_code
   info • Unused import: 'package:intl/intl.dart' • lib/views/home/study/calendar/calendar_util.dart:1:8 • unused_import
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: CalendarView.onMonthChange, CalendarView.onDateChecked, CalendarView.onCalendarExpand,
          CalendarView.calendarItems, CalendarView.year, CalendarView.month, CalendarView.currentDate, CalendarView.isExpand • lib/views/home/study/calendar/calendar_view.dart:19:7 • must_be_immutable
   info • Avoid empty statements • lib/views/home/study/classes_item.dart:78:5 • empty_statements
   info • Dead code • lib/views/home/study/classes_item.dart:78:5 • dead_code
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: TeacherHeader.man, TeacherHeader.main • lib/views/home/study/teacher_header.dart:8:7 •
          must_be_immutable
   info • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:8:8 • unused_import
   info • Unused import: 'package:bole_student/app.dart' • test/widget_test.dart:11:8 • unused_import

12 issues found. (ran in 17.5s)

```

```
fadadeiMac:bole_student fada$ flutter doctor -v
[✓] Flutter (Channel master, v1.8.2-pre.42, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.8.2-pre.42 at /Users/fada/Library/flutter
    • Framework revision 35b07a1f7f (2 days ago), 2019-07-15 23:43:27 -0400
    • Engine revision 74af88ba9f
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 24725a8559)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/fada/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/fada/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.7830
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (4 available)
    • Pixel 3 XL • 8BAY0W6W8                                • android-arm64  • Android 10 (API 29)
    • 发达的 iPhone • 9100d7b48c2681fccbf90fb6888ed04d25fe46e5 • ios            • iOS 12.2
    • macOS      • macOS                                    • darwin-x64     • Mac OS X 10.14.5 18F132
    • Chrome     • chrome                                   • web-javascript • Google Chrome 75.0.3770.100 


! Doctor found issues in 1 category.

```

**Comment by BondarenkoStas** [comment] 2019-09-26 15:24
@mofada Is it the same while using current flutter stable or master?

**Comment by mofada** [comment] 2019-09-26 15:41
Yes, I am the master branch, because the user feels a little blinking, it is canceled, I am not sure if it is still flashing now.

**Comment by markusaksli-nc** [comment] 2020-08-12 11:41
Reproducible on the latest master `1.21.0-8.0.pre.176`.
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: "Sample",
      home: Scaffold(
        appBar: AppBar(title: Text("Sample"),),
        body: TimerText(),
      ),
    ),
  );
}

class TimerText extends StatefulWidget {
  TimerText({Key key}) : super(key: key);

  @override
  TimerTextState createState() => TimerTextState();
}

class TimerTextState extends State<TimerText> with TickerProviderStateMixin {
  static const _secondDuration = const Duration(seconds: 1);

  Timer _timer;
  String text = '';

  @override
  void initState() {
    super.initState();
    _timer = Timer.periodic(_secondDuration, (Timer timer) {
      setState(() {});
    });
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

  String _printDuration(Duration duration) {
    String twoDigits(int n) => n.toString().padLeft(2, "0");
    String twoDigitMinutes = twoDigits(duration.inMinutes.remainder(60));
    String twoDigitSeconds = twoDigits(duration.inSeconds.remainder(60));
    return "${twoDigits(duration.inHours)}:$twoDigitMinutes:$twoDigitSeconds";
  }

  @override
  Widget build(BuildContext context) {
    String lastTime = _timer.isActive
        ? _printDuration(Duration(seconds: _timer.tick - 1))
        : '00:00:00';
    String currentTime = _timer.isActive
        ? _printDuration(Duration(seconds: _timer.tick))
        : '00:00:00';

    return Container(
      padding: const EdgeInsets.only(
        top: 21,
        bottom: 19,
      ),
      child: Center(
        child: AnimatedCrossFade(
          duration: _secondDuration,
          firstChild: Text(
            '${_timer.tick % 2 == 0 ? currentTime : lastTime}',
            style: TextStyle(
              fontSize: 16,
              color: const Color(0xFFE32416),
            ),
          ),
          crossFadeState: _timer.tick % 2 == 0
              ? CrossFadeState.showFirst
              : CrossFadeState.showSecond,
          secondChild: Text(
            '${_timer.tick % 2 != 0 ? currentTime : lastTime}',
            style: TextStyle(
              fontSize: 16,
              color: const Color(0xFFE32416),
            ),
          ),
        ),
      ),
    );
  }

  void reset() {
    _timer.cancel();
    _timer = Timer.periodic(_secondDuration, (Timer timer) {
      setState(() {});
    });
  }

  int get time => _timer.tick;

  @override
  void didUpdateWidget(TimerText oldWidget) {
    super.didUpdateWidget(oldWidget);
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-8.0.pre.176, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-8.0.pre.176 at /Users/markus/development/flutter_master
    • Framework revision d9637ed784 (7 hours ago), 2020-08-11 23:51:03 -0400
    • Engine revision 6381b1511b
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/markus/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/markus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

 
[✓] Connected device (5 available)            
    • Nevercode’s iPhone (mobile)         • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • iPhone SE (2nd generation) (mobile) • E88D23AA-71AC-49A6-A418-058CDE0D2FC4     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
    • macOS (desktop)                     • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)                    • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                        • chrome                                   • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

The extreme flashing in the original issue no longer seems present but the behavior is still buggy on iOS.
![RPReplay-Final1597232176](https://user-images.githubusercontent.com/68219924/90011202-d804d300-dca9-11ea-81b8-354e1e57cf24.gif)
This does not repro on Android or web.

**Comment by mofada** [comment] 2020-08-13 01:22
I think I solved it, thanks for your help

**Comment by markusaksli-nc** [comment] 2020-08-13 07:40
I'm going to keep this open since the behavior here still seems to be unexpected. Here is a simplified version that reproduces on Android, iOS, and web:

<details>
 <summary>Expected behavior</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());


class MyApp extends StatelessWidget {
  final title = 'AnimatedCrossFade example';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: title,
      home: MyHomePage(title: title,),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  const MyHomePage({Key key, this.title}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _first = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
          child: AnimatedCrossFade(
            duration: const Duration(seconds: 1),
            firstChild: const FlutterLogo(style: FlutterLogoStyle.horizontal, size: 100.0),
            secondChild: const FlutterLogo(style: FlutterLogoStyle.stacked, size: 100.0),
            crossFadeState: _first ? CrossFadeState.showFirst : CrossFadeState.showSecond,
          )
      ),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.transform),
          onPressed: () {
            setState(() {
              _first = !_first;
            });
          }
      ),
    );
  }
}
```
</details>
<img src="https://user-images.githubusercontent.com/68219924/90107091-fffb4180-dd50-11ea-8394-3c15b5fa78de.gif" height="600" />
<details>
 <summary>Unexpected behavior with Text</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());


class MyApp extends StatelessWidget {
  final title = 'AnimatedCrossFade example';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: title,
      home: MyHomePage(title: title,),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  const MyHomePage({Key key, this.title}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _first = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
          child: AnimatedCrossFade(
            duration: const Duration(seconds: 1),
            firstChild: const Text("This will not fade smoothly: Foo"),
            secondChild: const Text("This will not fade smoothly: Bar"),
            crossFadeState: _first ? CrossFadeState.showFirst : CrossFadeState.showSecond,
          )
      ),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.transform),
          onPressed: () {
            setState(() {
              _first = !_first;
            });
          }
      ),
    );
  }
}
```
</details>
<img src="https://user-images.githubusercontent.com/68219924/90107314-481a6400-dd51-11ea-8b56-564a098db4a0.gif" height="600" />


@mofada How did you solve it?

**Comment by mofada** [comment] 2020-08-13 07:49
Oh (⊙o⊙)? , How does the retracting effect of your code do?

**Comment by gaaclarke** [comment] 2020-10-26 21:17
The documentation for AnimatedCrossFade  states "This widget is intended to be used to fade a pair of widgets with the same width."  The reproduction code is crossfading between widgets of different size because of variable width fonts.  You can eliminate the glitch by animating across fixed width containers like so:
```dart
import 'dart:async';

import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: "Sample",
      home: Scaffold(
        appBar: AppBar(
          title: Text("Sample"),
        ),
        body: TimerText(),
      ),
    ),
  );
}

class TimerText extends StatefulWidget {
  TimerText({Key key}) : super(key: key);

  @override
  TimerTextState createState() => TimerTextState();
}

class TimerTextState extends State<TimerText> with TickerProviderStateMixin {
  static const _secondDuration = const Duration(seconds: 1);

  Timer _timer;
  String text = '';

  @override
  void initState() {
    super.initState();
    _timer = Timer.periodic(_secondDuration, (Timer timer) {
      setState(() {});
    });
  }

  @override
  void dispose() {
    _timer.cancel();
    super.dispose();
  }

  String _printDuration(Duration duration) {
    String twoDigits(int n) => n.toString().padLeft(2, "0");
    String twoDigitMinutes = twoDigits(duration.inMinutes.remainder(60));
    String twoDigitSeconds = twoDigits(duration.inSeconds.remainder(60));
    return "${twoDigits(duration.inHours)}:$twoDigitMinutes:$twoDigitSeconds";
  }

  @override
  Widget build(BuildContext context) {
    String lastTime = _timer.isActive
        ? _printDuration(Duration(seconds: _timer.tick - 1))
        : '00:00:00';
    String currentTime = _timer.isActive
        ? _printDuration(Duration(seconds: _timer.tick))
        : '00:00:00';

    return Container(
      padding: const EdgeInsets.only(
        top: 21,
        bottom: 19,
      ),
      child: Center(
        child: AnimatedCrossFade(
          duration: _secondDuration,
          firstChild: Container(
              color: Colors.blue,
              width: 200,
              child: Text(
                '${_timer.tick % 2 == 0 ? currentTime : lastTime}',
                style: TextStyle(
                  fontSize: 16,
                  color: const Color(0xFFE32416),
                ),
              )),
          crossFadeState: _timer.tick % 2 == 0
              ? CrossFadeState.showFirst
              : CrossFadeState.showSecond,
          secondChild: Container(
            color: Colors.blue,
            width: 200,
            child: Text('${_timer.tick % 2 != 0 ? currentTime : lastTime}',
                style: TextStyle(
                  fontSize: 16,
                  color: const Color(0xFFE32416),
                )),
          ),
        ),
      ),
    );
  }

  void reset() {
    _timer.cancel();
    _timer = Timer.periodic(_secondDuration, (Timer timer) {
      setState(() {});
    });
  }

  int get time => _timer.tick;

  @override
  void didUpdateWidget(TimerText oldWidget) {
    super.didUpdateWidget(oldWidget);
  }
}
```

Closing as works as intended.

**Closed by gaaclarke** 2020-10-26 21:17 UTC
Labels: a: animation, found in release: 1.21, framework, has reproducible steps, platform-ios, severe: rendering
