### ISSUE TITLE
Linux Fuchsia: `Download for build xxxx` failure 

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#68520] opened 2020-10-19 20:41 UTC
We are repeatedly seeing failures on Fuchsia Linux bots in https://ci.chromium.org/p/flutter/g/engine/console

The failed steps are in `Download for build xxxx`.  The logs won't load and don't seem helpful. to me.

Example: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Fuchsia/5894

**Comment by godofredoc** [comment] 2020-10-19 21:09
The problem is this build is taking more than an hour and it is being killed by a timeout. I'm checking whether the execution time have increased or if this is just a side effect on setting task execution timeout to one hour.

**Comment by godofredoc** [comment] 2020-10-19 21:12
![image](https://user-images.githubusercontent.com/54371434/96512279-1b813d80-1215-11eb-8b05-d33ed8f71331.png)

**Comment by godofredoc** [comment] 2020-10-19 21:23
This is a cold vs hot cache.

* On the passing task checking out the source code takes ~3mins and in the failing one ~7mins
* On the passing task building fuchsia tests takes ~4 mins and in the failing one ~12.

Increasing the timeout for this build to 1 hour and half as with cold caches it takes a little bit more than an hour to complete.

**Comment by godofredoc** [comment] 2020-10-19 22:00
Moving to P1 while we monitor the new builds

**Closed** 2020-10-20 00:05 UTC
Labels: P1, team: infra
