### ISSUE TITLE
Exception: Could not instantiate image codec. while decoding JSON

### ISSUE THREAD

**Issue by Chaitanyaha** [flutter/flutter#40654] opened 2019-09-17 08:14 UTC
#33749  Steps to Reproduce

1. ...
![Screenshot (32)](https://user-images.githubusercontent.com/46054472/65023765-28b46480-d951-11e9-8cd8-ce6cd007bef1.png)

2. ...
![Screenshot (1)](https://user-images.githubusercontent.com/46054472/65023774-2e11af00-d951-11e9-80b3-3186534fd88e.png)

3. ... 
![Screenshot (33)](https://user-images.githubusercontent.com/46054472/65024531-b04ea300-d952-11e9-92f2-0746c28c1a51.png)
![Screenshot (40)](https://user-images.githubusercontent.com/46054472/65024543-b3499380-d952-11e9-81ae-b962f3f472bc.png)

**Comment by BondarenkoStas** [comment] 2019-09-17 11:36
@Chaitanyaha Please do not include screenshots of code. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example. Can you please paste the code and logs in a text version?

**Comment by escamoteur** [comment] 2019-09-17 11:37
Could you check where the `The getter length was called on Null`comes from? Best to enable break on all exceptions in your debugger. I'm a bit confused because  in the exception it states line 108 of _HomPageState.build, in your screenshots the build function is on completely different line numbers.

**Comment by janmoppel** [comment] 2019-11-12 11:04
Hello @Chaitanyaha !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Closed by janmoppel** 2019-11-12 11:04 UTC
Labels: waiting for customer response

**Comment by wdlmm** [comment] 2019-11-20 05:43
url  ：  http://fistchain.org/download/icons/USDT.png    
code：
  Image(
                  image: NetworkImage(widget.token.icon),
                  height: 30,
                  width: 30,
                ),
error： 
![image](https://user-images.githubusercontent.com/16712407/69212231-b3a51b80-0b9b-11ea-87ab-0ef9251cfcbb.png)

**Comment by ishaileshmishra** [comment] 2020-01-22 08:14
Hi, 
Getting Exception: Could not instantiate image codec.

find the log for your reference.

Initializing hot reload...
Syncing files to device iPhone 11 Pro Max...
Reloaded 0 of 590 libraries in 285ms.
flutter: 250

════════ Exception caught by image resource service ════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Could not instantiate image codec.

When the exception was thrown, this was the stack: 
#0      _futurize (dart:ui/painting.dart:4304:5)
#1      instantiateImageCodec (dart:ui/painting.dart:1682:10)
#2      PaintingBinding.instantiateImageCodec (package:flutter/src/painting/binding.dart:88:12)
#3      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:104:20)
<asynchronous suspension>
...
Image provider: NetworkImage("https://restcountries.eu/data/aze.svg", scale: 1.0)
Image key: NetworkImage("https://restcountries.eu/data/aze.svg", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by image resource service ════════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by image resource service ════════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by image resource service ════════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (5) Exception caught by image resource service ════════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (6) Exception caught by image resource service ════════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (7) Exception caught by image resource service ════════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (8) Exception caught by image resource service ════════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (9) Exception caught by image resource service ════════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (10) Exception caught by image resource service ═══════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (11) Exception caught by image resource service ═══════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (12) Exception caught by image resource service ═══════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (13) Exception caught by image resource service ═══════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (14) Exception caught by image resource service ═══════════════════════════════════════════
Exception: Could not instantiate image codec.
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by rbluethl** [comment] 2020-02-03 16:25
Same here. @ishaileshmishra, did you find a solution?

**Comment by BasharAlayan** [comment] 2020-02-27 23:44
Hi,
I have the same problem @ishaileshmishra , did you find a solution ?

**Comment by mohammadne** [comment] 2020-02-28 07:01
same for a Uint8List image.

**Comment by Sreejith93** [comment] 2020-03-01 11:34
same error!!!

**Comment by ebsene** [comment] 2020-03-04 21:32
I have the same problem too

**Comment by jinfagang** [comment] 2020-03-06 16:10
So how do we solve it? I get back an image from sqlite, before it can show after decode to uint8list then it fails to show. anything left behind?

**Comment by jinfagang** [comment] 2020-03-06 16:10
So how do we solve it? I get back an image from sqlite, before it can show after decode to uint8list then it fails to show. anything left behind?

**Comment by aboutmydreams** [comment] 2020-03-13 12:05
same problem

**Comment by Fethi1** [comment] 2020-03-15 14:11
i have the same issue i'm trying to decode an image but it says the error

**Comment by shdw2x** [comment] 2020-03-15 14:41
I have the same issue.

**Comment by jinfagang** [comment] 2020-03-16 02:43
So seems kinda common problem.... which may comes from flutter or dart

**Comment by Faisal-Alhazzani** [comment] 2020-03-17 10:07
Same issue!

**Comment by TaykYoku** [comment] 2020-03-21 13:15
the same

**Comment by escamoteur** [comment] 2020-03-23 13:52
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by jinfagang** [comment] 2020-03-24 04:51
Hardly to reveal it, but get image from sqlite always here this error.

**Comment by Fethi1** [comment] 2020-03-24 10:12
The image i was trying to display is stored in a CSV file and it fired the same error,
somehow i found a workaround using the image package.
`import 'package:image/image.dart' as im;
im.encodePng(im.decodeImage(image.getBytes()))`

**Comment by tiagorossig** [comment] 2020-04-03 10:20
Same issue.

**Comment by sarahelmasryy** [comment] 2020-04-08 19:52
same issue.

**Comment by sarahelmasryy** [comment] 2020-04-08 19:53
same issue!

**Comment by kevto** [comment] 2020-04-11 19:37
I used to have the same issue. I'm using GCP Storage for my static images and Google has 2 URLs to use for the image. One is a direct url to the image which worked and the other one redirected to the actual image. From what I figured, Image.network() is not able to handle HTTP redirections.

**Comment by sheetal-gupta812** [comment] 2020-04-13 04:32
same problem please provide solution

**Comment by kw2019ltd** [comment] 2020-04-17 09:46
same

![image](https://user-images.githubusercontent.com/47334522/79556224-7345bd00-80a9-11ea-911e-9f9278154e44.png)

**Comment by jinfagang** [comment] 2020-04-17 12:35
Seems no one investigate this problem?

**Comment by pathakvivek7865** [comment] 2020-04-22 12:09
why closed without solving this..?

**Comment by elvinaspredkelis** [comment] 2020-04-28 10:40
I have the same problem when I try to load an image from AWS.

My current workaround uses **CachedNetworkImage**.

`
import 'package:cached_network_image/cached_network_image.dart';
Image( image: CachedNetworkImage(imageUrl) )
`

**Comment by nmeri17** [comment] 2020-04-30 13:32
I eventually realized this error only occurs while attempting to use SVGs. At no point in time does the doc say you can't pass SVGs into Image.asset, kept getting this error and couldn't figure out why. So, even if you're not passing in that mime type, verify you're passing correct images

**Comment by positrix** [comment] 2020-05-14 10:14
> I used to have the same issue. I'm using GCP Storage for my static images and Google has 2 URLs to use for the image. One is a direct url to the image which worked and the other one redirected to the actual image. From what I figured, Image.network() is not able to handle HTTP redirections.

For GCP storage public objects you can use https://storage.googleapis.com/ instead of https://storage.cloud.google.com/ for your images. so the final url will look like https://storage.googleapis.com/<bucket-name>/<filename> instead of https://storage.cloud.google.com/<bucket-name>/<filename>

More info on accessing public objects at https://cloud.google.com/storage/docs/access-public-data

This solved the problem for me.

**Comment by serenebkj** [comment] 2020-06-12 11:18
I had the same problem, but I solved it by opening the image in a new tab and copying that URL instead of the image URL from simply selecting the google image. Well, I was simply displaying a networkImage from google images. I am a starter :)
