### ISSUE TITLE
Add unused imports linter to engine presubmit

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#50353] opened 2020-02-07 19:08 UTC
These are frequently caught by internal infra during rolls. We should run an unused imports linter in the engine as part of android presubmit.

**Comment by mklim** [comment] 2020-02-07 19:09
I think I'm going to close this as a dupe of flutter/flutter#19031.

**Closed by mklim** 2020-02-07 19:09 UTC
Labels: engine, team: infra

**Comment by mklim** [comment] 2020-02-07 19:46
Actually my mistake, this is really a duplicate of #42534. Just using `google-java-format` would remove unused imports. I think the linter issue I mentioned earlier should be closed.
