### ISSUE TITLE
flutter doctor always shows plugins are not installed in Android Studio

### ISSUE THREAD

**Issue by yanshouwang** [flutter/flutter#55718] opened 2020-04-27 06:32 UTC
## Steps to Reproduce

1. download flutter sdk
2. install Android Studio and Flutter plugins
3. run flutter doctor

## Logs

![image](https://user-images.githubusercontent.com/24455689/80341217-9b48d380-8894-11ea-99bd-d8d37cb64277.png)

```
```

```
```

**Comment by joekendal** [comment] 2020-04-27 07:03
Have you configured the plugin settings to set the SDK path?

**Comment by yanshouwang** [comment] 2020-04-27 07:10
@joekendal No, should I configure something to the plugin?

**Comment by joekendal** [comment] 2020-04-27 07:13
@yanshouwang File->Settings->Languages & Frameworks->Dart 
make sure enabled and SDK path is set
Then same for File->Settings->Languages & Frameworks->Flutter

**Comment by yanshouwang** [comment] 2020-04-27 07:22
@joekendal I set the path, but the warning still shows
![image](https://user-images.githubusercontent.com/24455689/80344831-cc2c0700-889a-11ea-9ea7-e25d9502b3e8.png)

**Comment by TahaTesser** [comment] 2020-04-27 10:33
duplicate of [#54867](https://github.com/flutter/flutter/issues/54867)

**Closed by TahaTesser** 2020-04-27 10:33 UTC
