### ISSUE TITLE
[share] Sharing via email without a subject crashes app on iOS

### ISSUE THREAD

**Issue by luketg8** [flutter/flutter#39740] opened 2019-09-03 11:37 UTC
Internal: b/141557699

Getting app crashes when trying to share a link via email using this plugin. Created a new Flutter app to test this issue and was able to recreate.

```
Scaffold(
      body: FlatButton(
              child: Text("Click me and share via email to crash"),
              onPressed: () =>
                  Share.share('check out my website https://example.com'),
            )
    );
```

(Flutter Version *stable* 1.7.8+hotfix.4)

**Comment by BondarenkoStas** [comment] 2019-09-03 17:55
@luketg8 Please provide ```flutter doctor -v``` output as well as logs if possible.

**Comment by luketg8** [comment] 2019-09-03 18:06
@BondarenkoStas 
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-GB)
    • Flutter version 1.7.8+hotfix.4 at /Users/**/Development/flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/**/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.0

[✓] Connected device (1 available)
    • iPhone XR • 4A6ED565-DF1A-4740-A8BC-C21E0B4C5302 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-1 (simulator)

**Comment by dalebulmer** [comment] 2019-09-03 23:23
Getting same issue on same flutter version

**Comment by dalebulmer** [comment] 2019-09-03 23:32
Logs for crash from my app:

Sep  4 09:30:28 Ipad nsurlsessiond[732] <Warning>: 732: CFNetwork internal error (0xc01a:/BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork/CFNetwork-758.5.3/Loading/URLConnectionLoader.cpp:289)
Sep  4 09:30:36 Ipad MailCompositionService[1735] <Warning>: <NSXPCConnection: 0x17d9f750> connection from pid 1742: Warning: Exception caught during decoding of received message, dropping incoming message.
        Exception: Exception while decoding argument 0 (#2 of invocation):
        <NSInvocation: 0x17efaa40>
        return value: {v} void
        target: {@} 0x0
        selector: {:} setCompositionValues:
        argument 2: {@} 0x0

        Exception: value for key 'NS.objects' was of unexpected class 'NSNull'. Allowed classes are '{(
            NSNumber,
            NSString,
            NSURL,
            NSDictionary,
            NSArray
        )}'.
Sep  4 09:30:36 Ipad Runner[1742] <Warning>: viewServiceDidTerminateWithError: Error Domain=_UIViewServiceInterfaceErrorDomain Code=3 "(null)" UserInfo={Message=Service Connection Interrupted}
Sep  4 09:30:37 Ipad Runner[1742] <Error>: -[NSNull length]: unrecognized selector sent to instance 0x3b692310
Sep  4 09:30:37 Ipad Runner[1742] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x3b692310'
        *** First throw call stack:
        (0x2473b91b 0x23ed6e17 0x247412b5 0x2473eee1 0x2466a238 0x24ea3f39 0x28d6920b 0x2dd5b805 0x2dd5b67f 0x28cb6a1f 0x28cb6971 0x29046fb5 0x29009351 0x29005cdb 0x28f5f4c9 0x28f6b7db 0x28ca9b1d 0x246fd6c9 0x246fb9cd 0x246fbdff 0x2464b229 0x2464b015 0x25c3bac9 0x28d1f189 0x82e85 0x242f3873)
Sep  4 09:30:37 Ipad com.apple.xpc.launchd[1] (UIKitApplication:com.wordoftravel.wordoftravel[0xb01a][1742]) <Notice>: Service exited due to signal: Abort trap: 6
Sep  4 09:30:37 Ipad SpringBoard[47] <Warning>: UNNotificationRegistrarConnectionListener connection invalidated

**Comment by Kieranshb** [comment] 2019-09-17 17:23
Hello,

I have encountered this problem as well. I was able to get the plugin to work by adding a subject to the share like so

`Share.share(“Your message“, subject:"Email subject")`

Hopefully this helps anyone who is currently blocked by this issue!

**Comment by jkurtw** [comment] 2019-09-24 19:03
b/141557699

**Comment by amirh** [comment] 2019-09-24 21:13
Seems like setting null as the value for the "subject" key of activityController isn't supported and crashes.

The problem is that this API in general doesn't seem to be officially documented, it seems like there is an officially documented alternative which is using [activityViewController:subjectForActivityType:](https://developer.apple.com/documentation/uikit/uiactivityitemsource/1620455-activityviewcontroller?language=objc) to set the subject. Which I think we should migrate the plugin to use regardless.

Anyway for the immediate term it seems like applications can work around the issue by just never passing null as the subject (set it to empty string if there's no subject).

I think it makes sense to make the plugin use not set the subject when the value is null, though covering this with a test isn't possible until we have the testing infrastructure to drive a flutter app and also drive iOS UI (e.g in this case we will need to select the "Mail" option from the system's share dialog).

Before we can test this I'm considering setting the subject to "" on the Dart side, I'm not sure yet whether this have any side affects on Android sharing (setting [Intent.EXTRA_SUBJECT](https://developer.android.com/reference/android/content/Intent.html#EXTRA_SUBJECT) to null vs to an empty string, intuitively sounds to me like we shouldn't be setting it to null ever).

**Comment by ds84182** [comment] 2019-09-26 21:34
Technically, this is a regression for all applications using the share plugin. https://github.com/flutter/plugins/commit/c057bc973b7dcb987056ff4c403149380742472d was the commit that added subject support. Any callers that do not use the subject (either because they're unaware of it's existence or code was written before the subject was added) will now crash on iOS when using the built-in Mail app.

**Comment by Hixie** [comment] 2019-09-30 23:08
Seems like the easiest fix is to make the `subject` parameter have a default value of `''` and then assert that it's not null.

**Comment by cyanglaz** [comment] 2019-10-04 17:08
Fixed with https://github.com/flutter/plugins/pull/2131
To apply the fix, update the plugin to the newest version (0.6.2+3)
I'm closing the issue.

**Closed by cyanglaz** 2019-10-04 17:08 UTC
Labels: customer: fun (g3), p: share, plugin, severe: customer blocker, waiting for PR to land (fixed), ⌺‬ platform-ios
