### ISSUE TITLE
[tool_crash] TemplateException: Value was missing for variable tag: macosIdentifier. (11:29) PRODUCT_BUNDLE_IDENTIFIER = {{macosIdentifier}}

### ISSUE THREAD

**Issue by Ahd-Karman** [flutter/flutter#80114] opened 2021-04-09 13:27 UTC
I can not start new flutter project in Android Studio  ,  I just installed it and try to run my first project , but I get "Error creating project " , I hope you can help me 

Crash Report  :
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color create --offline --template app --description A new Flutter application. --org com.example --project-name helloworld helloworld

## exception

TemplateException: Value was missing for variable tag: macosIdentifier. (11:29)
PRODUCT_BUNDLE_IDENTIFIER = {{macosIdentifier}}
                            ^

```
#0      Renderer.visitVariable (package:mustache/src/renderer.dart:101:9)
#1      VariableNode.accept (package:mustache/src/node.dart:45:43)
#2      Renderer.render.<anonymous closure> (package:mustache/src/renderer.dart:58:30)
#3      List.forEach (dart:core-patch/growable_array.dart:278:8)
#4      Renderer.render (package:mustache/src/renderer.dart:58:13)
#5      Template.render (package:mustache/src/template.dart:40:14)
#6      Template.renderString (package:mustache/src/template.dart:33:5)
#7      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:162:77)
#8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#9      Template.render (package:flutter_tools/src/template.dart:114:24)
#10     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:622:21)
#11     CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:545:23)
<asynchronous suspension>
#12     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:396:37)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#22     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#30     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#31     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#32     new Future.sync (dart:async/future.dart:224:31)
#33     CommandRunner.run (package:args/command_runner.dart:112:14)
#34     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#35     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1500:12)
#40     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#41     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _runZoned (dart:async/zone.dart:1516:10)
#45     runZoned (dart:async/zone.dart:1463:12)
#46     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#47     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#48     run (package:flutter_tools/runner.dart:51:10)
#49     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#50     main (file:///C:/1111/mobile_env/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#51     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8, on Microsoft Windows [Version 10.0.18363.476], locale ar-SA)
    • Flutter version 1.7.8 at C:\1111\mobile_env\flutter
    • Framework revision d51fd86cdb (1 year, 10 months ago), 2019-06-21 22:31:55 -0400
    • Engine revision d004bcd4d6
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by Ahd-Karman** [comment] 2021-04-09 13:31
![image](https://user-images.githubusercontent.com/80492499/114187448-ae8f6a80-9950-11eb-92c3-1a998705e4fa.png)


It looks like this :(

**Comment by TahaTesser** [comment] 2021-04-09 14:18
Related to https://github.com/flutter/flutter/issues/43734

This issue was when there was no desktop support on stable and fix includes deleting this error causing file but now desktop support is on stable and this issue is reported

**Comment by jmagman** [comment] 2021-04-15 01:39
This is a duplicate of https://github.com/flutter/flutter/issues/43734.

@Ahd-Karman try upgrading your Flutter version, `v1.7.8` is almost 2 years old.

**Closed by jmagman** 2021-04-15 01:39 UTC
Labels: a: first hour, passed first triage, severe: crash, tool

**Comment by TahaTesser** [comment] 2021-04-15 09:25
My bad, I thought it was latest `stable`


@Ahd-Karman 
Please upgrade to the latest `stable`
