### ISSUE TITLE
TextInputType.number broken on Samsung devices

### ISSUE THREAD

**Issue by KorbinianMossandl** [flutter/flutter#48409] opened 2020-01-08 16:03 UTC
## Steps to Reproduce
1. Add a `TextField` or `TextFormField` to your flutter app
2. Set `keyboardType` to `TextInputType.number`
3. Install app to any recent samsung phone running android 9 or 10 (tested on S10, S8 and S7)
4. Try to edit the text field
5. The custom number keyboard that samsung devices uses freezes (no input, won't disappear again even outside app)

**Target Platform:**
Android
**Target OS version/browser:**
Android 9 + 10
**Devices:**
most likely all samsung devices

## Logs

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/zool/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/zool/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /home/zool/Android/Sdk
    • Java binary at: /home/zool/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/zool/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by HansMuller** [comment] 2020-01-08 16:52
CC @GaryQian

**Comment by GaryQian** [comment] 2020-01-09 21:10
Not all samsung devices are affected. Verified working fine on a Note 9.

**Comment by GaryQian** [comment] 2020-01-10 00:41
This may be a duplicate of this: https://github.com/flutter/flutter/issues/46159

**Comment by KorbinianMossandl** [comment] 2020-01-12 13:50
@GaryQian yes, it seems to be fixed on master

**Comment by GaryQian** [comment] 2020-01-31 22:11
Great! I will close this for now, please let me know if you still have issues regarding this!

**Closed by GaryQian** 2020-01-31 22:11 UTC
Labels: a: text input, e: device-specific, f: material design, framework, severe: regression, ▣ platform-android

**Comment by machadoguilhermebr** [comment] 2020-07-17 12:35
when I uses 
mask_text_input_formatter 
or any other plugins of mask
mey keybord in samsung devices freezes, do you know how fix it?

**Comment by GaryQian** [comment] 2020-07-20 14:00
@machadoguilhermebr can you file an issue with further details about this?

**Comment by parth-ibl** [comment] 2021-04-02 06:40
@GaryQian My testing team testing one of the projects in Samsung Galaxy J7 Pro Android version 9. Our keyboard type is the number and the user not able to add "-" minus sign from the keyboard in the text field.

**Comment by GaryQian** [comment] 2021-04-02 09:25
@parth-ibl can you file a separate issue for what you are seeing? This issue doesn't accurately describe your symptoms. Please link it here and feel free to tag me in it.
