### ISSUE TITLE
When the exception was thrown, this was the stack: 

### ISSUE THREAD

**Issue by akbarali1** [flutter/flutter#133761] opened 2023-08-31 14:14 UTC
```
When the exception was thrown, this was the stack: 
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:434:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:445:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:537:5)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:956:37)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:212:49)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:35)
#8      _invoke2 (dart:ui/hooks.dart:174:13)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#10     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:686:22)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 2 frames from class _AssertionError)
```
====================================================================================================

======== Exception caught by services library ======================================================
The following assertion was thrown during a platform message callback:
A KeyUpEvent is dispatched, but the state shows that the physical key is not pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#2b79e(physicalKey: PhysicalKeyboardKey#8de52(usbHidUsage: "0x1100000043", debugName: "Key with ID 0x1100000043"), logicalKey: LogicalKeyboardKey#147d9(keyId: "0x100000008", keyLabel: "Backspace", debugName: "Backspace"), character: null, timeStamp: 0:01:54.941672)
'package:flutter/src/services/hardware_keyboard.dart':
Failed assertion: line 434 pos 16: '_pressedKeys.containsKey(event.physicalKey)'

**Comment by dam-ease** [comment] 2023-08-31 14:28
Hi @akbarali1. Thanks for filing this. From the logs, it seems similar/related to https://github.com/flutter/flutter/issues/107972.
Closing this as a duplicate of an already open issue, kindly comment, upvote and follow up on that issue for updates. If you disagree, kindly comment here and I'd reopen this.
Thank you!

**Closed by dam-ease** 2023-08-31 14:28 UTC
Labels: in triage
