### ISSUE TITLE
flutter attach on iphone is not stable: "error connecting..." or stuck on "waiting for a connection"

### ISSUE THREAD

**Issue by impCheng** [flutter/flutter#52805] opened 2020-03-18 11:15 UTC
## Steps to Reproduce

I tried lots of cases in differrent environment: 
1.MacOS: 10.15.3 && 10.14
2.iOS: iOS13 && iOS12
3.project: pure flutter project && iOS-flutter-mixed project
4.network: wifi && 4g

for android devices or iOS simulators, it works fine: I excute "flutter attach" and launch my app
but for iOS devices, if I do the same, I will stuck on "Waiting for a connection from Flutter on iPhone..."
I can resolve this by "launch app at first and then excute flutter attach"
but it's not stable, sometimes it works, sometimes I got the error "Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/i9RzQqgbFSs=/ws"

all in all, 
MacOS 10.14 works better than 10.15
iOS 12 better than iOS 13
pure flutter project better than mixed
4g better than wifi

## Logs

```
in most cases,there are two problems:
1. Waiting for a connection from Flutter on iPhone...
2. Error connecting to the service protocol: HttpException: , uri = http://127.0.0.1:1024/i9RzQqgbFSs=/ws
```

```
[✓] Flutter (Channel v1.9.1-hotfixes, v1.9.1+hotfix.6-pre.1, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6-pre.1 
    • Framework revision eb6877bf92 (5 months ago), 2019-10-23 15:17:08 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/imp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by TahaTesser** [comment] 2020-03-18 11:16
duplicate of [#52729](https://github.com/flutter/flutter/issues/52729)

**Closed by TahaTesser** 2020-03-18 11:16 UTC
