### ISSUE TITLE
App immediately shuts down when running integration test on real device

### ISSUE THREAD

**Issue by CalebRBPittman** [flutter/flutter#104116] opened 2022-05-18 19:31 UTC
## My problem:

I'm attempting to run Flutter integration tests on a real device (Galaxy S8), and I'm having some trouble. Here's what I've done:
1. run `flutter drive --flavor dev \ --driver=test_driver/integration_test_driver.dart \ --target=integration_test/worker-log-in.dart` in my terminal
2. Wait for the app to build
3. Observe results

Note: I previously posted another issue, #104004 , which had to do with integration testing. Although I figured out my issue with that ticket, I was blocked due to the issue observed in #34499 .

**Expected results:** 
I'd like for the app to run my integration test, and tell me if I succeeded or failed

**Actual results:** 
Instead, the app almost immediately shuts down when I run the test.
Here's a video: https://user-images.githubusercontent.com/77282560/169140450-ba92d5b9-9164-4234-a7d4-c26bd6e1db85.mp4

Here's my terminal output:
```
Running Gradle task 'assembleDevDebug'...                          30.3s
√  Built build\app\outputs\flutter-apk\app-dev-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                11.6s
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:53262/86zTR03h6cU=/
VMServiceFlutterDriver: Isolate found with number: 479578345223051
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
I/flutter (32028): 00:00 +0: Log In Tests:  1. Log In
VMServiceFlutterDriver: Connected to Flutter application.
D/FRCPlugin(32028): Sending fetchTimeout: 60
I/flutter (32028): crashlytics is disabled
I/System.out(32028): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(32028): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(32028): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(32028): (HTTPLog)-Static: isSBSettingEnabled false
D/FRCPlugin(32028): Sending fetchTimeout: 10
I/System.out(32028): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(32028): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(32028): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out(32028): (HTTPLog)-Static: isSBSettingEnabled false
D/SensorManager(32028): registerListener :: 1, LSM6DSL Accelerometer, 200000, 0,
I/System.out(32028): (HTTPLog)-Static: isSBSettingEnabled false
I/chatty  (32028): uid=10290(com.spotapp.spot) firebase-instal identical 2 lines
I/System.out(32028): (HTTPLog)-Static: isSBSettingEnabled false
D/FRCPlugin(32028): Sending fetchTimeout: 10
I/flutter (32028): 00:06 +0: Log In Tests:  1. Log In [E]
I/flutter (32028):   'package:flutter_test/src/binding.dart': Failed assertion: line 775 pos 14:
'_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to return it to its original  
state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before  
restoring FlutterError.onError.
I/flutter (32028):   dart:core-patch/errors_patch.dart 51:61                _AssertionError._doThrowNew
I/flutter (32028):   dart:core-patch/errors_patch.dart 40:5                 _AssertionError._throwNew
I/flutter (32028):   package:flutter_test/src/binding.dart 775:14
TestWidgetsFlutterBinding._runTest.handleUncaughtError
I/flutter (32028):   package:flutter_test/src/binding.dart 780:9            TestWidgetsFlutterBinding._runTest.<fn>      
I/flutter (32028):   dart:async/zone.dart 1109:14                           _Zone._processUncaughtError
I/flutter (32028):   dart:async/zone.dart 1312:5                            _CustomZone.handleUncaughtError
I/flutter (32028):   dart:async/future_impl.dart 680:16                     Future._propagateToListeners
I/flutter (32028):   dart:async/future_impl.dart 609:5                      Future._completeError
I/flutter (32028):   dart:async-patch/async_patch.dart 272:13               _completeOnAsyncError
I/flutter (32028):   package:firebase_remote_config/src/remote_config.dart  RemoteConfig.fetchAndActivate
I/flutter (32028):
I/flutter (32028):   'package:flutter_test/src/binding.dart': Failed assertion: line 1649 pos 12: '_pendingFrame ==      
null': is not true.
I/flutter (32028):   dart:core-patch/errors_patch.dart 51:61           _AssertionError._doThrowNew
I/flutter (32028):   dart:core-patch/errors_patch.dart 40:5            _AssertionError._throwNew
I/flutter (32028):   package:flutter_test/src/binding.dart 1649:12     LiveTestWidgetsFlutterBinding.postTest
I/flutter (32028):   dart:async/future.dart 296:31                     new Future.sync
I/flutter (32028):   package:test_api/src/backend/invoker.dart 236:18  Invoker.runTearDowns.<fn>.<fn>
I/flutter (32028):   package:test_api/src/backend/invoker.dart 257:15  Invoker._waitForOutstandingCallbacks.<fn>
I/flutter (32028):   package:test_api/src/backend/invoker.dart 254:14  Invoker._waitForOutstandingCallbacks.<fn>
I/flutter (32028):   dart:async/zone.dart 1426:13                      _rootRun
I/flutter (32028):   dart:async/zone.dart 1328:19                      _CustomZone.run
I/flutter (32028):   dart:async/zone.dart 1861:10                      _runZoned
I/flutter (32028):   dart:async/zone.dart 1783:10                      runZoned
I/flutter (32028):   package:test_api/src/backend/invoker.dart 254:5   Invoker._waitForOutstandingCallbacks
I/flutter (32028):   package:test_api/src/backend/invoker.dart 235:9   Invoker.runTearDowns.<fn>
I/flutter (32028):   package:test_a
I/flutter (32028): 00:06 +0 -1: Log In Tests:  (tearDownAll)
I/flutter (32028): 00:07 +1 -1: Some tests failed.
All tests passed.
```
<details>

<summary>Code sample</summary>

Here is my worker-log-in.dart file, which is located in the integration_test directory
```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'dart:io';
import 'package:spot/main.dart' as app;

// Run the following line to run all the tests in this file:
// flutter drive --flavor dev \ --driver=test_driver/integration_test_driver.dart \ --target=integration_test/worker-log-in.dart

void main () {
    group("Log In Tests: ", () {
        final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized()
            as IntegrationTestWidgetsFlutterBinding;
        binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;
        
        // Log into the app as a known user
        testWidgets("1. Log In", (tester) async {

            // Open App
            app.main();
            sleep(const Duration(seconds: 5));
            await tester.pumpAndSettle(Duration(seconds: 5));

            // Click Log In
            final WorkerLogIn = find.byKey(Key("WorkerLogIn"));
            await tester.tap(WorkerLogIn);
            await tester.pumpAndSettle();

            // Enter Phone Number
            final WorkerPhoneNumber = find.byKey(Key("WorkerPhoneNumber"));
            await tester.enterText(WorkerPhoneNumber, "5550000002");
            await tester.pumpAndSettle();

            // Send Verification Code
            final SendVerification = find.byKey(Key("SendVerification"));
            await tester.ensureVisible(SendVerification);
            await tester.tap(SendVerification);
            await tester.pumpAndSettle();

            // Enter Verification Code
            final EnterVerification = find.byKey(Key("EnterVerification"));
            await tester.enterText(EnterVerification, "123456");
            await tester.pumpAndSettle();

            // Submit Verification Code
            final SubmitVerification = find.byKey(Key("SubmitVerification"));
            await tester.ensureVisible(SubmitVerification);
            await tester.tap(SubmitVerification);
            await tester.pumpAndSettle();
            
        });
    });
}
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19043.1706], locale en-CA)
    • Flutter version 2.10.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\calrb\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32421.90
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.67.2)
    • VS Code at C:\Users\calrb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM G950W (mobile) • 988bdb303358355338 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19043.1706]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 101.0.1210.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2022-05-19 08:31
Looking at the error it is throwing:

`I/flutter (32028):   'package:flutter_test/src/binding.dart': Failed assertion: line 775 pos 14:
'_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to return it to its original  
state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before  
restoring FlutterError.onError.`

It seems to be coming from `flutter_test` package itself and not specific to `integration_test` because it leverages `flutter_test` implementation. There's an open issue for it https://github.com/flutter/flutter/issues/34499 in which you can follow-up for further updates.
Closing this as a duplicate because the real reason root-cause seems to be in `flutter_test` package.

**Closed by darshankawar** 2022-05-19 08:31 UTC
Labels: in triage
