### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by liudonjun** [flutter/flutter#123988] opened 2023-04-03 04:40 UTC
## Command
```
flutter --quiet assemble --no-version-check --depfile D:\code\pda_app\build\app\intermediates\flutter\debug/flutter_build.d --output D:\code\pda_app\build\app\intermediates\flutter\debug -dTargetFile=D:\code\pda_app\lib\main.dart -dTargetPlatform=android -dBuildMode=debug -dTrackWidgetCreation=true --DartDefines=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9iMjg1NWUwNzRkZWIxZTIzMjlhZWI3ZjM2YjMwNmZiMDcyMmQwOWRjLw== debug_android_application
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:624:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:99:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:218:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:217:12)
#6      SourceVisitor.visitDepfile (package:flutter_tools/src/build_system/source.dart:55:37)
#7      List.forEach (dart:core-patch/growable_array.dart:416:8)
#8      Target._resolveConfiguration (package:flutter_tools/src/build_system/build_system.dart:250:14)
#9      Target.resolveInputs (package:flutter_tools/src/build_system/build_system.dart:195:12)
#10     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:148:39)
#11     Target._toNode (package:flutter_tools/src/build_system/build_system.dart:155:58)
#12     FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:30)
#13     AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:315:51)
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1563:12)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1331:27)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
```
```
[✓] Flutter (Channel master, 3.9.0-20.0.pre.71, on Microsoft Windows [版本 10.0.22621.607], locale zh-CN)
    • Flutter version 3.9.0-20.0.pre.71 on channel master at D:\FlutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dd7d4b9521 (2 days ago), 2023-03-31 18:46:59 -0500
    • Engine revision b2855e074d
    • Dart version 3.0.0 (build 3.0.0-387.0.dev)
    • DevTools version 2.22.2

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-33-ext5, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.76.2)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • HD1910 (mobile)   • emulator-5554 • android-x64    • Android 9 (API 28)
    • Windows (desktop) • windows       • windows-x64    • Microsoft Windows [版本 10.0.22621.607]
    • Chrome (web)      • chrome        • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge          • web-javascript • Microsoft Edge 111.0.1661.62

[!] Network resources
    ✗ A network error occurred while checking "https://maven.google.com/": 信号灯超时时间已到

    ✗ An HTTP error occurred while checking "https://github.com/": 信号灯超时时间已到


! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: dd7d4b952112f988cb85dcc905eb7858e83f62a2

**Comment by danagbemava-nc** [comment] 2023-04-03 09:05
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021

Kindly upvote the original issue. 

Thank you

**Closed by danagbemava-nc** 2023-04-03 09:05 UTC
Labels: in triage
