### ISSUE TITLE
Add barcode icon to `Icons` class

### ISSUE THREAD

**Issue by twoco** [flutter/flutter#108254] opened 2022-07-24 22:54 UTC
https://fonts.google.com/icons?icon.query=barcode

![image](https://user-images.githubusercontent.com/53160891/180669129-ca997a0a-d2c6-4e48-b1e4-c83897bb8e84.png)

```dart
Icons.barcode
```

**Comment by exaby73** [comment] 2022-07-25 07:31
Hello @twoco. Thank you for filing this feature request. Looks like a valid one.

**Comment by guidezpl** [comment] 2022-07-28 16:34
Hey, this is a duplicate of #105897, #106201. Google Symbols is coming soon!

**Closed by guidezpl** 2022-07-28 16:34 UTC
Labels: new feature, framework, f: material design, proposal

**Comment by twoco** [comment] 2022-07-28 17:52
Ok, if I understand correctly, Flutter uses the `cupertino_icons` (pubspec.yaml, [docs](https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html)).
Without digging into the source code, I'm wondering where the icons come from and what needs to be done to add new ones. Who prevents us from adding new symbols? Where to post proposals?

Interesting that Flutter (from Google) uses Cupertino icons over Material icons, even if the UI is based on Material Design. ^^ Anyway, good to know it comes with #102560.

**Comment by guidezpl** [comment] 2022-07-29 02:39
That's not quite right. Flutter uses both Material `Icons` and `CupertinoIcons`. Material icons come from setting `useMaterial` to true in the pubspec (support is baked in the framework), while `CupertinoIcons` come from a package. The link shared above is for Material `Symbols` (`Icons`' eventual replacement). For Material at least, the aim is to provide exactly the sets from https://fonts.google.com/icons?icon.set=Material+Icons and https://fonts.google.com/icons?icon.set=Material+Symbols.

You can send feedback on those pages for adding new icons.

**Comment by twoco** [comment] 2022-07-29 16:24
Oh, I missed the difference between `Symbols` and `Icons`. Not quite understood yet. But ok ... I think I go with custom icons. I searched the web I bit and it seems to be a bit more complex to add custom icons to Flutter than to other web frontends. I come from HTML based frontends like Angular and Ionic. In most cases a SVG icon is used. Whatever... Flutter could offer an easier way to add custom icons and provide some docs on how to do it. Which way would a more experienced Flutter developer prefer?

**Comment by guidezpl** [comment] 2022-07-29 17:54
The path that most icon packages use (including the ones mentioned above) is to use an icon font file. There's a fair number of resources on that, https://www.flutterclutter.dev/flutter/tutorials/2022-04-01-icons-in-flutter/, https://medium.com/codechai/how-to-use-custom-icons-in-flutter-834a079d977, etc..
