### ISSUE TITLE
Scrollable WrapView with builder and separated methods

### ISSUE THREAD

**Issue by OutdatedGuy** [flutter/flutter#107361] opened 2022-07-10 01:49 UTC
## Use case

As flutter supports many platforms with a wide range of screen sizes, it is very necessary to have a responsive scroll view.
`ListView` and `GridView` are great but implementing responsiveness is very complex.

Implementing a responsive scroll view with `GridView` is possible but becomes very messy with a lot of conditional checking.

## Proposal

To have a `WrapView` widget similar to `Wrap` widget which can be scrolled.

Furthermore it could have methods like `WrapView.builder` to take advantages of lazy loading and `WrapView.separated` to differ sections.

https://user-images.githubusercontent.com/74326345/178128151-9f930035-2686-49c4-9e1d-95b29dfbb56d.mp4

**Comment by exaby73** [comment] 2022-07-11 07:37
Hello @OutdatedGuy. Thanks for filing this feature request. Looks like a valid one. Labelling as such

**Comment by goderbauer** [comment] 2022-07-13 21:50
@Piinks

**Comment by Piinks** [comment] 2022-07-13 22:40
The sample in the video above is already possible with a grid view, using the [SliverGridDelegateWithMaxCrossAxisExtent](https://api.flutter.dev/flutter/rendering/SliverGridDelegateWithMaxCrossAxisExtent-class.html).

However, a scrolling wrap widget type of widget is in the work for variable sized children. :)
Closing this as a duplicate of https://github.com/flutter/flutter/issues/97544, follow that issue for updates on the feature. Thank you!

FYI @snat-s & @DavBot02, here is another use case.

**Closed by Piinks** 2022-07-13 22:40 UTC
Labels: new feature, framework, f: scrolling, proposal

**Comment by OutdatedGuy** [comment] 2022-07-14 12:01
> The sample in the video above is already possible with a grid view, using the [SliverGridDelegateWithMaxCrossAxisExtent](https://api.flutter.dev/flutter/rendering/SliverGridDelegateWithMaxCrossAxisExtent-class.html).

I have tried using it, but it resizes it's children which I don't want.
I want to have children with fixed size for large screen and 80% screen width for smaller screens.

**Comment by OutdatedGuy** [comment] 2022-07-14 21:05
> I see, you could also use SliverGridDelegateWithFixedCrossAxisCount, and change the number of grid tiles in the row based on the MediaQueryData about the window. In your case, cross axis count would be 1 on smaller screens, and increase as the screen gets larger. This is typically how adaptive layouts are created in Flutter.

That was the first thing I tried. But the **child resizing** issue persist.
I think _scrollable wrap_ would be the only way to place **fixed size** widgets without resizing them.

It looks like the Flutter team is working on it. So I'll just be patient till then 🥲

Thank you!
