### ISSUE TITLE
DropdownButtonFormField does not update

### ISSUE THREAD

**Issue by RaulBR** [flutter/flutter#57615] opened 2020-05-19 21:42 UTC
Hi,
`DropdownButtonFormField` does not update from a later call of setState 
the call is made by some data change in my app, but i get the same result by running the code underneath (same thing works fine with DropdownButton)

The DropdownButtonFormField  never changes from a.
code:
```dart
class DropdownExampleListWidged extends StatefulWidget {
  @override
  _DropdownExampleListWidgedState createState() =>
      _DropdownExampleListWidgedState();
}

class _DropdownExampleListWidgedState extends State<DropdownExampleListWidged> {
  List<String> list = ['a', 'b', 'c', 'd'];
  String selected;
  void initState() {
    setState(() {
      selected = list[0];
    });
    Future.delayed(const Duration(milliseconds: 3000), () {
      setState(() {
        selected = list[3];
      });
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    print(selected);
    return DropdownButtonFormField<String>(
      value: selected,
      onChanged: (String newValue) {
        setState(() {
          selected = newValue;
        });
      },
      items: (list).map<DropdownMenuItem<String>>((String value) {
        return DropdownMenuItem<String>(
          value: value,
          child: Text(value),
        );
      }).toList(),
    );
  }
}

```
console output:

```bash
Reloaded 9 of 1012 libraries in 1,490ms.
V/ViewRootImpl[MainActivity](15691): debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=31.970398, y[0]=167.92523, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=351164558, downTime=351164558, deviceId=1, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{4ba4c65 com.example.ehsfocus/com.example.ehsfocus.MainActivity,ident = 0}
V/ViewRootImpl[MainActivity](15691): debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=31.970398, y[0]=167.92523, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=351164630, downTime=351164558, deviceId=1, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{4ba4c65 com.example.ehsfocus/com.example.ehsfocus.MainActivity,ident = 0}
I/flutter (15691): enviroment
V/ViewRootImpl[MainActivity](15691): debug enqueueInputEvent: event = MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=283.73727, y[0]=375.83267, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=351166142, downTime=351166142, deviceId=1, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{4ba4c65 com.example.ehsfocus/com.example.ehsfocus.MainActivity,ident = 0}
V/ViewRootImpl[MainActivity](15691): debug enqueueInputEvent: event = MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=283.73727, y[0]=375.83267, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=351166186, downTime=351166142, deviceId=1, source=0x1002 },processImmediately = true,mProcessInputEventsScheduled = false, this = ViewRoot{4ba4c65 com.example.ehsfocus/com.example.ehsfocus.MainActivity,ident = 0}
I/flutter (15691): enviroment
I/flutter (15691): a
I/flutter (15691): d
```

**Comment by iapicca** [comment] 2020-05-20 08:53
Hi @RaulBR 
running the code above with the latest master the issue doesn't seem to occur
<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

/// source [https://gist.github.com/iapicca/34af401a8977828c338d61022dd1e0e7]

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) =>  MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey _formKey = GlobalKey<FormState>();
  static const List<int> _list = [0, 1, 2, 3];

  int _value = _list.first;

  @override
  Widget build(BuildContext context) => 
  Scaffold(
    body: Center(
      child: Form(
        key: _formKey,
        child: DropdownButtonFormField<int>(
          value: _value,
          icon: Icon(Icons.arrow_downward),
          iconSize: 24,
          elevation: 16,
          style: TextStyle(
              color: Colors.deepPurple
          ),
          onChanged: (int newValue) => setState(() => _value = newValue),
          items: [
            for (int i in _list) DropdownMenuItem(
              value: i,
              child: Text('$i'),
            )
          ],
        ),
      ),
    ),
    floatingActionButton: FloatingActionButton(
      onPressed: () => setState(() => _value = _list.first),
      child: Icon(Icons.update),
    ),
  );
}
```

</details>


<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.19.0-2.0.pre.131, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.19.0-2.0.pre.131 at /Users/nevercode/development/flutter_master
    • Framework revision 478d4c9c1a (6 hours ago), 2020-05-19 20:22:01 -0700
    • Engine revision 2d4e83921d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>
does this code represent the issue you are describing?
Thank you

**Comment by demsey2** [comment] 2020-05-20 09:04
hi @iapicca  it has been fixed in master a few days ago, I just verified that unfortunately, I have other issues not related to this one

https://github.com/flutter/flutter/issues/27821

**Comment by HansMuller** [comment] 2020-05-20 15:22
I believe this is a duplicate of https://github.com/flutter/flutter/issues/56898 which was fixed by https://github.com/flutter/flutter/pull/57037

**Comment by RaulBR** [comment] 2020-05-20 16:24
> ```
> Channel maste
> ```
You are right an update solved it!
Thank you!

**Closed** 2020-05-20 16:34 UTC
Labels: f: material design, framework, in triage
