### ISSUE TITLE
[image_picker] [IOS] crash on the second time using getVideo

### ISSUE THREAD

**Issue by lvlrSajjad** [flutter/flutter#74232] opened 2021-01-19 10:11 UTC
## Steps to Reproduce

1. Create a flutter app
2. install image_picker: 0.6.7+21 using the instructions from https://pub.dev/packages/image_picker
3. Make a UI to be able to pick a video
4. use this code to pick a video file: ```PickedFile video = await ImagePicker().getVideo(source: ImageSource.gallery);``` 
5. select the file
6. again use this code to pick a video file: ```PickedFile video = await ImagePicker().getVideo(source: ImageSource.gallery);```
7. you should see the crash

**Expected results:** Select a video file for the second time

**Actual results:** Crashes when we try to select a video file for the second time in the video selection screen

**Comment by darshankawar** [comment] 2021-01-19 12:30
@lvlrSajjad 
Tried the official `image_picker` plugin [example](https://pub.dev/packages/image_picker/example) on latest master using iPhone 6s device and followed the steps you mentioned, but didn't see the crash. I was able to select video file for the second and subsequent times.

Do you see the crash in debug mode or in release mode ?
Can you provide video / gif of the issue  along with `flutter doctor -v` ?

**Comment by lvlrSajjad** [comment] 2021-01-20 06:40
```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/lvlrx/development/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lvlrx/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 0A42584C-1AE4-43C6-AC5D-369EB1815BEF • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

• No issues found!
```
@darshankawar It's weird. Are you sure you have tested "image_picker: 0.6.7+21" version?

**Comment by lvlrSajjad** [comment] 2021-01-20 06:44
@darshankawar I have found out the problem was something else. And now, it is solved.
So I'll close this issue.

**Comment by n305225282** [comment] 2021-01-21 03:53
> @darshankawar I have found out the problem was something else. And now, it is solved.
> So I'll close this issue.

I have the same problem , how did you solve it ?

**Comment by lvlrSajjad** [comment] 2021-01-21 13:39
@darshankawar It seems the issue still is there.

**Comment by TahaTesser** [comment] 2021-01-21 15:38
Hi @lvlrSajjad  @n305225282 
I just tried to reproduce the using code line provided in the description in a minimal code sample and it prints the selected video path on `image_picker: ^0.6.7+21` on physical XR or simulator running `iOS 14.3`  in both `select photos` and `all photos` permissions on the latest `stable` channel.


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          PickedFile video =
              await ImagePicker().getVideo(source: ImageSource.gallery);

          print(video.path);
        },
      ),
    );
  }
}
```
</details>



Below are the logs of multiple tries, no crash. 
<details>
<summary>logs</summary>

```bash
[ +132 ms] Syncing files to device Taha’s iPhone...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +2 ms] <- recompile package:triage/main.dart 9f7f1d89-5671-4399-b83d-e0f2045be45b
[        ] <- 9f7f1d89-5671-4399-b83d-e0f2045be45b
[ +122 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device Taha’s iPhone... (completed in 128ms)
[        ] Synced 0.0MB.
[        ] <- accept
[  +10 ms] Connected to _flutterView/0x105039a20.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Taha’s iPhone is available at: http://127.0.0.1:52031/U3yB6DZ3vX4=/
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[+8223 ms] flutter:
/private/var/mobile/Containers/Data/Application/5153208B-7858-4DB7-A12D-240C4068293B/tmp/trim.0E7A6DD9-DC53-4269-83AE-
EA4A181E12EB.MOV
[+4244 ms] flutter:
/private/var/mobile/Containers/Data/Application/5153208B-7858-4DB7-A12D-240C4068293B/tmp/trim.6B60E036-933B-4A26-95C0-
711B0B62619B.MOV
[+3324 ms] flutter:
/private/var/mobile/Containers/Data/Application/5153208B-7858-4DB7-A12D-240C4068293B/tmp/trim.973ED8D6-137A-4373-81B5-
F97FF8232FC7.MOV
[+3300 ms] flutter:
/private/var/mobile/Containers/Data/Application/5153208B-7858-4DB7-A12D-240C4068293B/tmp/trim.73C37919-C442-470C-8F25-
3BB1977920ED.MOV
[+3443 ms] flutter:
/private/var/mobile/Containers/Data/Application/5153208B-7858-4DB7-A12D-240C4068293B/tmp/trim.A92D9F0F-1BA6-43B1-8BAF-
C9FAF65529B8.MOV
[+5105 ms] flutter:
/private/var/mobile/Containers/Data/Application/5153208B-7858-4DB7-A12D-240C4068293B/tmp/trim.08D39C77-8765-4B11-873A-
4EA3D487F7E5.MOV
[+3733 ms] flutter:
/private/var/mobile/Containers/Data/Application/5153208B-7858-4DB7-A12D-240C4068293B/tmp/trim.64E13E53-5F2B-4A60-B5DC-
D0F364EA90FD.MOV
[+2910 ms] flutter:
/private/var/mobile/Containers/Data/Application/5153208B-7858-4DB7-A12D-240C4068293B/tmp/trim.E164136F-7B79-42FB-85C7-
75E85DFEF66D.MOV
```
</details>



<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone 12 (mobile) • E211FBCD-71F3-40E5-BA3E-2E4D6B321693 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```

</details>


Does it reproduce for on simulator physical? Can you please provide crash logs by running the example from Xcode?   Which permissions are you using for reproduction? 
Thank you

**Comment by kavehmb** [comment] 2021-01-21 16:01
I am facing this issue on iOS 13.4 simulator, running code by Android Studio in debug mode.
the app just crashes without any log.

**Comment by TahaTesser** [comment] 2021-01-21 16:41
@kavehmb 
Could you run it from Xcode, there will be crash logs there if not in Flutter logs

**Comment by lvlrSajjad** [comment] 2021-01-21 18:42
@TahaTesser I'll run my code with just the functionality of printing the path to see if the problem is from this piece of code or something else.

And can you tell me how to run the app from Xcode? Can I run it like the native iOS sources?

**Comment by lvlrSajjad** [comment] 2021-01-21 18:56
@TahaTesser I tried something like what you did 

```
File videoFile;

        PickedFile video = await picker.getVideo(source: ImageSource.gallery);
        videoFile = File(video.path);
        print(video.path);
        print (videoFile.path);
        return;
```

This time it crashed on almost after 6-7 attempts.

**Comment by lvlrSajjad** [comment] 2021-01-21 19:18
Xcode crash logs
<details>
```
2021-01-21 11:15:27.475425-0800 Runner[1176:1968545] [connection] nw_socket_handle_socket_event [C58.1:3] Socket SO_ERROR [61: Connection refused]
2021-01-21 11:15:27.477982-0800 Runner[1176:1968545] Connection 58: received failure notification
2021-01-21 11:15:27.478209-0800 Runner[1176:1968545] Connection 58: failed to connect 1:61, reason -1
2021-01-21 11:15:27.478403-0800 Runner[1176:1968545] Connection 58: encountered error(1:61)
2021-01-21 11:15:27.483758-0800 Runner[1176:1968545] Task <47C763F0-200C-44D5-9B0B-518CD8C35CDF>.<46> HTTP load failed, 0/0 bytes (error code: -1004 [1:61])
2021-01-21 11:15:27.484406-0800 Runner[1176:1968545] Task <47C763F0-200C-44D5-9B0B-518CD8C35CDF>.<46> finished with error [-1004] Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x600000382f10 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <47C763F0-200C-44D5-9B0B-518CD8C35CDF>.<46>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <47C763F0-200C-44D5-9B0B-518CD8C35CDF>.<46>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=https://firebaselogging.googleapis.com/v0cc/log/batch, NSErrorFailingURLKey=https://firebaselogging.googleapis.com/v0cc/log/batch, _kCFStreamErrorDomainKey=1}
2021-01-21 11:15:32.121949-0800 Runner[1176:1963742] [VERBOSE-2:profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port
2021-01-21 11:15:35.366166-0800 Runner[1176:1963739] flutter: /Users/lvlrx/Library/Developer/CoreSimulator/Devices/0A42584C-1AE4-43C6-AC5D-369EB1815BEF/data/Containers/Data/Application/7754D849-A834-4D1D-9658-3A5A1907BD4D/tmp/trim.003A48FB-BA6F-4DDE-9006-4A6F73F42318.MOV
2021-01-21 11:15:36.102596-0800 Runner[1176:1968544] [connection] nw_socket_handle_socket_event [C59.1:3] Socket SO_ERROR [61: Connection refused]
2021-01-21 11:15:36.106056-0800 Runner[1176:1968544] Connection 59: received failure notification
2021-01-21 11:15:36.106278-0800 Runner[1176:1968544] Connection 59: failed to connect 1:61, reason -1
2021-01-21 11:15:36.106409-0800 Runner[1176:1968544] Connection 59: encountered error(1:61)
2021-01-21 11:15:36.108835-0800 Runner[1176:1968544] Task <4B4121AD-92B7-4D91-B12E-53F6FDD8AA8D>.<47> HTTP load failed, 0/0 bytes (error code: -1004 [1:61])
2021-01-21 11:15:36.109208-0800 Runner[1176:1968544] Task <4B4121AD-92B7-4D91-B12E-53F6FDD8AA8D>.<47> finished with error [-1004] Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x6000001bcf60 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <4B4121AD-92B7-4D91-B12E-53F6FDD8AA8D>.<47>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <4B4121AD-92B7-4D91-B12E-53F6FDD8AA8D>.<47>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=https://firebaselogging.googleapis.com/v0cc/log/batch, NSErrorFailingURLKey=https://firebaselogging.googleapis.com/v0cc/log/batch, _kCFStreamErrorDomainKey=1}
2021-01-21 11:15:36.306438-0800 Runner[1176:1968546] 7.3.0 - [Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '519527277732'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
2021-01-21 11:15:36.356705-0800 Runner[1176:1963740] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
 Stack:(
	0   CoreAutoLayout                      0x00007fff59575b9b _AssertAutoLayoutOnAllowedThreadsOnly + 190
	1   CoreAutoLayout                      0x00007fff59575926 -[NSISEngine _optimizeWithoutRebuilding] + 54
	2   CoreAutoLayout                      0x00007fff59575459 -[NSISEngine optimize] + 92
	3   CoreAutoLayout                      0x00007fff595708c4 -[NSISEngine performPendingChangeNotifications] + 82
	4   UIKitCore                           0x00007fff24bdee75 -[UIView(Hierarchy) layoutSubviews] + 491
	5   UIKitCore                           0x00007fff24bf25b8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2924
	6   QuartzCore                          0x00007fff27aa2c33 -[CALayer layoutSublayers] + 258
	7   QuartzCore                          0x00007fff27aa91a5 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575
	8   QuartzCore                          0x00007fff27ab4f47 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	9   QuartzCore                          0x00007fff279f4408 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496
	10  QuartzCore                          0x00007fff27a2b1ef _ZN2CA11Transaction6commitEv + 783
	11  QuartzCore                          0x00007fff27a2c3ab _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79
	12  CoreFoundation                      0x00007fff2038e1f8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	13  CoreFoundation                      0x00007fff20388a77 __CFRunLoopDoObservers + 547
	14  CoreFoundation                      0x00007fff2038901a __CFRunLoopRun + 1113
	15  CoreFoundation                      0x00007fff203886d6 CFRunLoopRunSpecific + 567
	16  Flutter                             0x0000000107f88651 _ZN3fml17MessageLoopDarwin3RunEv + 65
	17  Flutter                             0x0000000107f836ca _ZN3fml15MessageLoopImpl5DoRunEv + 22
	18  Flutter                             0x0000000107f87350 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ + 170
	19  libsystem_pthread.dylib             0x00007fff60c91950 _pthread_start + 224
	20  libsystem_pthread.dylib             0x00007fff60c8d47b thread_start + 15
)
2021-01-21 11:15:36.364129-0800 Runner[1176:1963740] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreAutoLayout                      0x00007fff59575c89 -[NSISEngine tryToOptimizeReturningMutuallyExclusiveConstraints] + 0
	3   CoreAutoLayout                      0x00007fff59575926 -[NSISEngine _optimizeWithoutRebuilding] + 54
	4   CoreAutoLayout                      0x00007fff59575459 -[NSISEngine optimize] + 92
	5   CoreAutoLayout                      0x00007fff595708c4 -[NSISEngine performPendingChangeNotifications] + 82
	6   UIKitCore                           0x00007fff24bdee75 -[UIView(Hierarchy) layoutSubviews] + 491
	7   UIKitCore                           0x00007fff24bf25b8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2924
	8   QuartzCore                          0x00007fff27aa2c33 -[CALayer layoutSublayers] + 258
	9   QuartzCore                          0x00007fff27aa91a5 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575
	10  QuartzCore                          0x00007fff27ab4f47 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
	11  QuartzCore                          0x00007fff279f4408 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496
	12  QuartzCore                          0x00007fff27a2b1ef _ZN2CA11Transaction6commitEv + 783
	13  QuartzCore                          0x00007fff27a2c3ab _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79
	14  CoreFoundation                      0x00007fff2038e1f8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	15  CoreFoundation                      0x00007fff20388a77 __CFRunLoopDoObservers + 547
	16  CoreFoundation                      0x00007fff2038901a __CFRunLoopRun + 1113
	17  CoreFoundation                      0x00007fff203886d6 CFRunLoopRunSpecific + 567
	18  Flutter                             0x0000000107f88651 _ZN3fml17MessageLoopDarwin3RunEv + 65
	19  Flutter                             0x0000000107f836ca _ZN3fml15MessageLoopImpl5DoRunEv + 22
	20  Flutter                             0x0000000107f87350 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN3fml6ThreadC1ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE3$_0EEEEEPvSJ_ + 170
	21  libsystem_pthread.dylib             0x00007fff60c91950 _pthread_start + 224
	22  libsystem_pthread.dylib             0x00007fff60c8d47b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 12 Pro Max (0A42584C-1AE4-43C6-AC5D-369EB1815BEF) - Runtime: iOS 14.3 (18C61) - DeviceType: iPhone 12 Pro Max
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.'
terminating with uncaught exception of type NSException
CoreSimulator 732.18.6 - Device: iPhone 12 Pro Max (0A42584C-1AE4-43C6-AC5D-369EB1815BEF) - Runtime: iOS 14.3 (18C61) - DeviceType: iPhone 12 Pro Max
2021-01-21 11:16:05.136029-0800 Runner[1176:1963739] flutter: SocketException: OS Error: Connection reset by peer, errno = 54, address = freegeoip.app, port = 56979
(lldb) 
```
</details>

**Comment by lvlrSajjad** [comment] 2021-01-21 19:34
@TahaTesser Does it have anything to do with
https://github.com/flutter/flutter/issues/65995#issuecomment-694113405

**Comment by TahaTesser** [comment] 2021-01-22 07:46
Hi @lvlrSajjad 
You're hitting https://github.com/flutter/flutter/issues/68283, which is fixed on beta and above channels for simulators. It's not an issue on a stable channel for physical devices. This is only for the simulator and it is fixed on beta  
Here is my reproduction https://github.com/flutter/flutter/issues/68283#issuecomment-726091322 and closed as fixed.
BTW, you don't need to use permission_handler to manage `image_picker` permission, it will be asked by `image_picker` itself if the permissions are not set. 

https://github.com/flutter/flutter/issues/65995 is tracking a bug with `select photos`, it shows all pics instead of just selected pic. 

Closing as fixed and duplicate of https://github.com/flutter/flutter/issues/68283
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-01-22 07:46 UTC
Labels: in triage
