### ISSUE TITLE
[file_selector] plugin is not supporting windows

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#74555] opened 2021-01-23 10:56 UTC
When I try to use any method it says it returns:
```
MissingPluginException (MissingPluginException(No implementation found for method getDirectoryPath on channel plugins.flutter.io/file_selector))
```

Before I was using file_chooser which was in the google desktop embedding and it worked like a charm, but it got deleted from there and it directs me to the new plugin called `file_elector` which does not work

The project I am facing problem with is in this project: https://github.com/YazeedAlKhalaf/Flutter_Installer/
The exact place I use the method: https://github.com/YazeedAlKhalaf/Flutter_Installer/blob/master/lib/src/ui/views/steps/customize/customize_view_model.dart#L73-L95

**Comment by stuartmorgan** [comment] 2021-01-23 14:36
Duplicate of https://github.com/flutter/flutter/issues/70221

> it directs me to the new plugin called `file_elector` which does not work

Specifically it links to the README for the unendorsed desktop implementations, which explains how to use them.

**Closed by stuartmorgan** 2021-01-23 14:36 UTC
