### ISSUE TITLE
Flutter Web and Kaspersky Anti-Virus incompatibles

### ISSUE THREAD

**Issue by leonardocustodio** [flutter/flutter#81511] opened 2021-04-29 22:31 UTC
For some reason Flutter Web doesn't work with Kaspersky Anti-Virus.
If protection is enabled I get a blank page and the 

flutter run -d chrome -v

Stays stuck on:

```
[  +85 ms] Launching lib\main.dart on Chrome in debug mode...
[  +74 ms] Updating assets
[  +66 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more information see #56466.
[   +2 ms] Waiting for connection from debug service on Chrome...
[ +107 ms] <- reset
[   +4 ms] C:\Users\leona\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\Users\leona\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\Users\leona\flutter\bin\cache\flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\leona\AppData\Local\Temp\flutter_tools.dda824f\flutter_tool.c4364b86\app.dill --libraries-spec
file:///C:/Users/leona/flutter/bin/cache/flutter_web_sdk/libraries.json --packages C:\Users\leona\Documents\FlutterProjects\ipec\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\leona\AppData\Local\Temp\flutter_tools.dda824f\flutter_tools.a53738e9 --filesystem-scheme org-dartlang-app --initialize-from-dill build\c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform
file:///C:/Users/leona/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[   +9 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+16049 ms] Waiting for connection from debug service on Chrome... (completed in 16.2s)
[   +1 ms] Synced 39.9MB.
[        ] <- accept
[        ] Caching compiled dill
[ +532 ms] Using Abrindo em uma sessão de navegador existente.

[ +470 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:50863/devtools/browser/59ccd9de-8d5d-4b5a-b99a-8fb77e088b22
[ +314 ms] DwdsInjector: Received request for entrypoint at http://localhost:50841/main_module.bootstrap.js
[   +3 ms] MetadataProvider: Loading debug metadata...
[   +7 ms] MetadataProvider: Loaded debug metadata
[   +4 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:50841/main_module.bootstrap.js
[+38951 ms] DwdsInjector: Received request for entrypoint at http://localhost:50841/main_module.bootstrap.js
```

If I pause Kaspersky protection it works fine.

Here is my flutter doctor output:

```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\leona\flutter
    • Framework revision adc687823a (13 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\leona\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.55.1)
    • VS Code at C:\Users\leona\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.49

• No issues found!
```

Regards,

**Comment by TahaTesser** [comment] 2021-04-30 09:50
Hi @leonardocustodio 
You'd need to add flutter, SDK, etc to whitelist/allowlist
Closing as duplicate of https://github.com/flutter/flutter/issues/61997
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-30 09:50 UTC
Labels: in triage

**Comment by leonardocustodio** [comment] 2021-04-30 17:56
No problem looks like it is a similar problem. Still, on the original issue it doesn't say which files should be whitelisted.

I tried those:
![image](https://user-images.githubusercontent.com/5619696/116734889-31419d80-a9c4-11eb-9f32-1b219883ee1e.png)

And still couldn't get it to work. I think it would be nice to list all files that needs to be whitelisted somewhere so people can fix the issue by themself.

**Comment by TahaTesser** [comment] 2021-05-03 11:11
@leonardocustodio 
Please follow up on the original issue
