### ISSUE TITLE
I got this error and i can't resolve it please help me

### ISSUE THREAD

**Issue by AhmedSwilam** [flutter/flutter#60610] opened 2020-06-30 16:08 UTC
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by abhishekUpmanyu** [comment] 2020-06-30 17:39
Hi @AhmedSwilam 
Can you specify the command that you ran?

**Comment by AhmedSwilam** [comment] 2020-06-30 17:49
Hi Abhishek,

i tried to upload a project to github so i used cmd command as mentioned in
github and after i finished this error happened and i can't resolve it,
i think i used git push or git remote i don't remember exactly which one i
used,
also i tried to remove flutter and install again and it's also the same
error.

Thanks for your time

**Comment by abhishekUpmanyu** [comment] 2020-06-30 19:34
This doesn't seem to be a flutter issue, rather an issue caused by pushing your code into a non-existing branch.
Try deleting the .git folder from your project and reinitializing git.

Also, please consider closing this issue as it is not related to Flutter, thanks!

**Comment by AhmedSwilam** [comment] 2020-06-30 20:24
Ok thanks for your help

**Closed** 2020-06-30 20:33 UTC
