### ISSUE TITLE
What I can do with myBackgroundMessageHandler static function/top level function ?

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#44880] opened 2019-11-14 03:43 UTC
I can't show dialog :/
show me some examples of case use this function when using fcm background handle pls  !
I also print value in this function but nothing to see 
```
static Future<dynamic> myBackgroundMessageHandler(
      Map<String, dynamic> message) {
    if (message.containsKey('data')) {
      // Handle data message
      final dynamic data = message['data'];
      print(data);
    }

    if (message.containsKey('notification')) {
      // Handle notification message
      final dynamic notification = message['notification'];
      print(notification);
    }
    return null;
    // Or do other work.
  }
```

**Comment by iapicca** [comment] 2019-11-14 13:40
Hi @tbm98 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2019-11-14 13:40 UTC
