### ISSUE TITLE
FlutterViewController doesn't call deinit when page is closed and result in memory leak problem

### ISSUE THREAD

**Issue by hduhky** [flutter/flutter#131466] opened 2023-07-28 08:47 UTC
## Steps to Reproduce

git@github.com:flutter/samples.git commitId:129818a205274bc7e587192c6546cd856b8d5b0c

run samples/add_to_app/multiple_flutters/multiple_flutters_ios on iOS Simulator
![image](https://github.com/flutter/flutter/assets/12041872/adb6d483-8b1c-45b6-a1de-810e3717706f)
set a breakpoint in SingleFlutterViewController.swift deinit method
![image](https://github.com/flutter/flutter/assets/12041872/07ec2c2a-1b04-4f69-a5b5-2ce77750aa2f)
click Next several Times 
click Back until return to root page
deinit method never get called

## Details

➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 3.10.5, on macOS 12.6.3 21G419 darwin-arm64, locale
    zh-Hans-CN)
    • Flutter version 3.10.5 on channel stable at /Users/hky/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/hky/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (4 available)
    • iPhone (mobile)        • bb1729dd23771f188c20c685cbe145047bf80609 • ios
      • iOS 13.3.1 17D50
    • iPhone 14 Pro (mobile) • 7D58D3CF-58FA-4597-A62F-20AA63A4535B     • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)        • macos                                    •
      darwin-arm64   • macOS 12.6.3 21G419 darwin-arm64
    • Chrome (web)           • chrome                                   •
      web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Target Platform:iOS**
**Target OS version/browser:iOS16.2**
**Devices:iPhone 14 Pro Simulator**

```
```

```
```

</details>

**Comment by danagbemava-nc** [comment] 2023-07-28 09:52
Hi @hduhky, this is a duplicate of https://github.com/flutter/engine/pull/43379 which has been fixed on the master & beta channels. 

Closing from here since this has already been fixed. If you face this issue on either the `master` or `beta` channels kindly leave a comment below and I will reopen this.

Thank you

**Closed by danagbemava-nc** 2023-07-28 09:52 UTC
Labels: in triage
