### ISSUE TITLE
[tool_crash] _TypeError: (#0      GradleWrapper.updateInner (package:flutter_tools/src/flutter_cache.dart:533:49))

### ISSUE THREAD

**Issue by lorenzoermanii** [flutter/flutter#148056] opened 2024-05-09 13:20 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
_TypeError: (#0      GradleWrapper.updateInner (package:flutter_tools/src/flutter_cache.dart:533:49))
```
#0      GradleWrapper.updateInner (package:flutter_tools/src/flutter_cache.dart:533:49)
#1      CachedArtifact.update (package:flutter_tools/src/cache.dart:848:11)
#2      Cache.updateAll (package:flutter_tools/src/cache.dart:715:24)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1699:7)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
#10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.6, on Ubuntu 20.04.5 LTS 5.15.0-105-generic, locale it_IT.UTF-8)
    [32m•[39m Flutter version 3.19.6 on channel stable at /home/user/snap/flutter/common/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 54e66469a9 (3 settimane fa), 2024-04-17 13:08:03 -0700
    [32m•[39m Engine revision c4cd48e186
    [32m•[39m Dart version 3.3.4
    [32m•[39m DevTools version 2.31.1

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /home/user/Android/Sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 10.0.0-4ubuntu1
    [32m•[39m cmake version 3.16.3
    [32m•[39m ninja version 1.10.0
    [32m•[39m pkg-config version 0.29.1

[32m[✓][39m Android Studio (version 2023.2)
    [32m•[39m Android Studio at /snap/android-studio-canary/37/android-studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.8+0-17.0.8b1000.22-10799086)

[32m[✓][39m VS Code (version 1.78.2)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m VS Code (version 1.89.0)
    [32m•[39m VS Code at /snap/code/current/usr/share/code
    [32m•[39m Flutter extension version 3.88.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.5 LTS 5.15.0-105-generic
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment] 2024-05-09 13:26
Closing this as a duplicate of https://github.com/flutter/flutter/issues/91357

**Closed by danagbemava-nc** 2024-05-09 13:26 UTC
Labels: in triage
