### ISSUE TITLE
[add-2-app] AAR build causes maven upload failing because of new classifier features.

### ISSUE THREAD

**Issue by wangmir** [flutter/flutter#113417] opened 2022-10-14 04:16 UTC
The circumstance on the this issue is similar to #111643 but the problem is different.

I've been uploading aar library to the private maven repository (jfrog-based) at CI/CD environment using `mvn` command with following this guide (https://medium.com/google-cloud/flutter-aar-deploy-to-maven-and-gcp-artifact-registry-d107adebec4d).
But from newer version of flutter, there are two problems,

1. Flutter library naming policy changed. No longer `flutter_debug-1.0.aar`, it changed to `flutter-1.0-debug.aar` with using classifier.

So, this command cannot be used directly 
```
find . -name "*.pom" -type f -exec sh -c 'mvn deploy:deploy-file -DrepositoryId="REPOSITORY-ID" -Durl="REPOSITORY-URL" -DpomFile="$0" -Dfile="${0%.pom}.aar"' '{}' \;
```

I think it can be solved by making some shell script to check classifier, it will be complicated, but it can be solved.

2. But the problem is, when I trying to upload flutter-1.0.debug.aar library using maven command like this, (same with debug/profile, and it does not have default library flutter-1.0.aar too, it will be same with flutter-1.0-release.aar but I think it should be created separately.)

```
mvn -s setting_file.xml deploy:deploy-file -DrepositoryId="{repository}" -Durl="{repository url}" -DpomFile=flutter-1.0.pom -Dfile=flutter-1.0-release.aar -Dclassifier=release
```

it fails with this error. 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy-file (default-cli) on project standalone-pom: Failed to deploy artifacts: Could not transfer artifact {module}:flutter:pom:1.0 from/to {repository} ({repository url}): Transfer failed for {repository url}/{module}/flutter/1.0/flutter-1.0.pom 409 Conflict -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

It seems the pom.xml file format for flutter aar library is changed since flutter 3.10~ and it's quite strange to me.

It is like,

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.temp_test</groupId>
  <artifactId>flutter</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>

```

and I'm not sure `pom` is right packaing type for this because it does not have any child pom file, but only contains multiple aar libraries with different classifiers (debug/profile/release).

So, when I manually change the packaging type to aar like `<packaing>aar</packaging>`, the 409 error did not happened.

## Steps to Reproduce
```
flutter create -t module module_test
cd module_test
flutter build aar
cd build/host/outputs/repo/com/example/temp_test_flutter/1.0

mvn -s setting_file.xml deploy:deploy-file -DrepositoryId="{repository}" -Durl="{repository url}" -DpomFile=flutter-1.0.pom -Dfile=flutter-1.0-release.aar -Dclassifier=release

```

**Expected results:** 

Build & upload success

**Actual results:** 

409 error.

## Suggestion

1. Change packaging type of flutter library to aar again. (same as flutter_debug, flutter_release, flutter_profile)
2. Add default library without classifier to the build system too.

**Comment by darshankawar** [comment] 2022-10-14 12:46
Thanks for the detailed report @wangmir 
Can you provide `flutter doctor -v` so that we know on which version does this behavior occur ?

**Comment by wangmir** [comment] 2022-10-15 06:57
@darshankawar this is it.

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-arm, locale
    ko-KR)
    • Flutter version 3.3.4 on channel stable at
      /Users/wangmir/Developments/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (10 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/wangmir/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by darshankawar** [comment] 2022-10-17 05:13
Can you try on latest master as well, since the related / linked issue was fixed and merged into master ?

**Comment by wangmir** [comment] 2022-10-17 07:45
@darshankawar In case of master, `flutter build aar` does not generate flutter directory at `build/host/outputs/repo/com/example/temp_test/flutter/`.
So, it will not be a problem here. But, in this case, my question is, is this feature will be added to the hotfix something like 3.3.5?

**Comment by darshankawar** [comment] 2022-10-17 12:58
> is this feature will be added to the hotfix something like 3.3.5?

If the fix is a low-risk for a hot-fix then the team decides to file for a cherry-pick request to stable. Here you can read more about same: https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel

Otherwise, the fixes in master are released into stable once in every quarter.

**Comment by wangmir** [comment] 2022-10-17 13:16
@darshankawar If it's merged, then does it mean that it will be surely included to the next stable? Because it seems the pr #112149 fully reverted the former PR which changes the aar library structure to use classifier rather than making each pom file for dev, profile, release. So, I'm not sure it will be re-implemented by original other with considering issuer's comments. 
If latter is true, then I mean I think the pom.xml file should be fixed too. (for the record).

**Comment by darshankawar** [comment] 2022-10-17 13:29
> If it's merged, then does it mean that it will be surely included to the next stable?

I am not the right person to answer that :) You will probably need to wait and rely on next stable release to confirm.

Coming back to your original error reported issue, does switching to master fixes the behavior or not yet ?

**Comment by wangmir** [comment] 2022-10-18 01:13
@darshankawar So, the problem is, i need a stable version of flutter for commercial release, but 3.0.5 has a problem with virtual display (https://github.com/flutter/flutter/issues/103630) so I cannot rollback to 3.0.5 too. So, please consider inserting pr #112149 as a hot fix if the direction is correct.

**Comment by darshankawar** [comment] 2022-10-18 05:01
Thanks for the update. I am keeping this issue open for further insights from the team. Currently seeing same behavior as you originally reported on latest stable version.

<details>
<summary> stable doctor -v </summary>

```

[✓] Flutter (Channel stable, 3.3.4, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.4 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Comment by GaryQian** [comment] 2022-10-18 17:31
Since this is fixed on master and there is no expectation that this is going to be cherrypicked, we can close this now. The reverted PR is unlikely to reland in the near future. If there is still anything else to fix here, feel free to comment.

**Closed by GaryQian** 2022-10-18 17:31 UTC
Labels: platform-android, tool, a: existing-apps, has reproducible steps, found in release: 3.4

**Comment by wangmir** [comment] 2022-10-19 15:52
@darshankawar  @GaryQian @AesSedai101   It seems there is multiple related problems.

https://github.com/flutter/flutter/issues/112380 also have similar problem with new references, and I commented in that, there are also problem when solving dependency issue.


When changing the dependencies to use classifier,
Then AndroidManifest.xml failed with this..

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/6769075/196741756-c2ccdfe5-35d0-4b8d-b2de-2989b55fedcc.png">

So, do u have any working solution for the current stable version to be enabled with add-2-app situation?
I'm struggling a lot now...

**Comment by wangmir** [comment] 2022-10-19 16:22
I made a shell script to upload maven repository with fix pom file. Check below.
So, when I change the package name of pom file, then I could upload aar file into jfrog-based maven repository.
But, after that, the build of host application failed with two situation.

1. Failed with referencing classifier-based library, `flutter-1.0-debug`

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/6769075/196741756-c2ccdfe5-35d0-4b8d-b2de-2989b55fedcc.png">

This is the problem. It cannot simply get io.flutter.embedding.android.FlutterActivity 

2. `Failed to resolve: flutter-1.0` when referencing non-classifier-based library, `flutter_debug-1.0`

If build with local maven repository, it was fine with non-classifier-based library.
But when referencing maven remote repository, it fails with `Failed to resolve:flutter-1.0`, 
it is because it does not contains classifier for relocation.

When I check pom.xml of flutter_debug-1.0, I could see that, there are no <classifier>  for that. 

```xml
    <relocation>
      <groupId>flutter</groupId>
      <artifactId>flutter</artifactId>
      <version>1.0</version>
      <message>Use classifiers rather than _variant for new publish plugin</message>
    </relocation>
```


```bash
#!/bin/bash

# TODO: Add help and handling null arguments
POM_PATH=$1
SETTING_FILE_PATH=$2
REPOSITORY_ID=$3
REPOSITORY_URL=$4

echo $POM_PATH
echo $SETTING_FILE_PATH
echo $REPOSITORY_ID
echo $REPOSITORY_URL

POM_NAME=$(basename "${POM_PATH}")
LIB_PATH=$(echo $POM_PATH | sed -e "s/.pom//")
POM_DIR=$(dirname "${POM_PATH}")

# When pom file contains multiple aar with different classifier, it should be uploaded separately.
if [[ -e "${LIB_PATH}-debug.aar" ]] && [[ -e "${LIB_PATH}-profile.aar" ]] && [[ -e "${LIB_PATH}-release.aar" ]]
then
    echo "It's classifier based library!"
    
    # TODO: HOTFIX, it should be removed after release of flutter 3.5 (with this issue https://github.com/flutter/flutter/issues/113417#issuecomment-1283253281)
    echo "Fix buggy pom file to remove pom packaging."
    sed -e "s/\<packaging\>pom\<\/packaging\>/\<packaging\>aar\<\/packaging\>/" $POM_PATH > "${POM_PATH}_mod"
    cp $POM_PATH "${POM_PATH}_back"
    mv "${POM_PATH}_mod" $POM_PATH

    echo "Upload release classifier library..."
    mvn -s $SETTING_FILE_PATH deploy:deploy-file \
        -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
        -Dfile="${LIB_PATH}-release.aar" -Dclassifier=release

    echo "Upload profile classifier library..."
    mvn -s $SETTING_FILE_PATH deploy:deploy-file \
        -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
        -Dfile="${LIB_PATH}-profile.aar" -Dclassifier=profile

    echo "Upload debug classifier library..."
    mvn -s $SETTING_FILE_PATH deploy:deploy-file \
        -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
        -Dfile="${LIB_PATH}-debug.aar" -Dclassifier=debug

else
    echo "It's common aar library!"
    echo "Upload library..."

    mvn -s $SETTING_FILE_PATH deploy:deploy-file \
        -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
        -Dfile="${LIB_PATH}.aar"



fi

echo "::Upload completed::"


```

**Comment by wangmir** [comment] 2022-10-24 04:37
For the record, currently, because of this issue, I personally reverted 8e30cc9 and it does not cause conflict at flutter 3.3.5. I made custom docker image which support this flutter sdk, and it works fine. If u have similar issues around here, then think about personal revert for this.

**Comment by SAGARSURI** [comment] 2022-10-28 04:47
> I made a shell script to upload maven repository with fix pom file. Check below. So, when I change the package name of pom file, then I could upload aar file into jfrog-based maven repository. But, after that, the build of host application failed with two situation.
> 
> 1. Failed with referencing classifier-based library, `flutter-1.0-debug`
> 
> <img alt="image" width="1268" src="https://user-images.githubusercontent.com/6769075/196741756-c2ccdfe5-35d0-4b8d-b2de-2989b55fedcc.png">
> 
> This is the problem. It cannot simply get io.flutter.embedding.android.FlutterActivity
> 
> 2. `Failed to resolve: flutter-1.0` when referencing non-classifier-based library, `flutter_debug-1.0`
> 
> If build with local maven repository, it was fine with non-classifier-based library. But when referencing maven remote repository, it fails with `Failed to resolve:flutter-1.0`, it is because it does not contains classifier for relocation.
> 
> When I check pom.xml of flutter_debug-1.0, I could see that, there are no for that.
> 
> ```
>     <relocation>
>       <groupId>flutter</groupId>
>       <artifactId>flutter</artifactId>
>       <version>1.0</version>
>       <message>Use classifiers rather than _variant for new publish plugin</message>
>     </relocation>
> ```
> 
> ```shell
> #!/bin/bash
> 
> # TODO: Add help and handling null arguments
> POM_PATH=$1
> SETTING_FILE_PATH=$2
> REPOSITORY_ID=$3
> REPOSITORY_URL=$4
> 
> echo $POM_PATH
> echo $SETTING_FILE_PATH
> echo $REPOSITORY_ID
> echo $REPOSITORY_URL
> 
> POM_NAME=$(basename "${POM_PATH}")
> LIB_PATH=$(echo $POM_PATH | sed -e "s/.pom//")
> POM_DIR=$(dirname "${POM_PATH}")
> 
> # When pom file contains multiple aar with different classifier, it should be uploaded separately.
> if [[ -e "${LIB_PATH}-debug.aar" ]] && [[ -e "${LIB_PATH}-profile.aar" ]] && [[ -e "${LIB_PATH}-release.aar" ]]
> then
>     echo "It's classifier based library!"
>     
>     # TODO: HOTFIX, it should be removed after release of flutter 3.5 (with this issue https://github.com/flutter/flutter/issues/113417#issuecomment-1283253281)
>     echo "Fix buggy pom file to remove pom packaging."
>     sed -e "s/\<packaging\>pom\<\/packaging\>/\<packaging\>aar\<\/packaging\>/" $POM_PATH > "${POM_PATH}_mod"
>     cp $POM_PATH "${POM_PATH}_back"
>     mv "${POM_PATH}_mod" $POM_PATH
> 
>     echo "Upload release classifier library..."
>     mvn -s $SETTING_FILE_PATH deploy:deploy-file \
>         -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
>         -Dfile="${LIB_PATH}-release.aar" -Dclassifier=release
> 
>     echo "Upload profile classifier library..."
>     mvn -s $SETTING_FILE_PATH deploy:deploy-file \
>         -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
>         -Dfile="${LIB_PATH}-profile.aar" -Dclassifier=profile
> 
>     echo "Upload debug classifier library..."
>     mvn -s $SETTING_FILE_PATH deploy:deploy-file \
>         -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
>         -Dfile="${LIB_PATH}-debug.aar" -Dclassifier=debug
> 
> else
>     echo "It's common aar library!"
>     echo "Upload library..."
> 
>     mvn -s $SETTING_FILE_PATH deploy:deploy-file \
>         -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
>         -Dfile="${LIB_PATH}.aar"
> 
> 
> 
> fi
> 
> echo "::Upload completed::"
> ```

Hey @wangmir is there any solution for the first problem where the system cannot resolve `io.flutter.embedding.android.FlutterActivity`?

**Comment by kim-json** [comment] 2022-10-28 06:04
> For the record, currently, because of this issue, I personally cherry-picked [8e30cc9](https://github.com/flutter/flutter/commit/8e30cc9c56bcecc6fd921764b8205d22b8a37fd9) and it does not cause conflict at flutter 3.3.5. I made custom docker image which support this flutter sdk, and it works fine. If u have similar issues around here, then think about personal revert for this.

Thank you. The problem is solved 🙏

**Comment by SAGARSURI** [comment] 2022-10-28 06:08
> > For the record, currently, because of this issue, I personally cherry-picked [8e30cc9](https://github.com/flutter/flutter/commit/8e30cc9c56bcecc6fd921764b8205d22b8a37fd9) and it does not cause conflict at flutter 3.3.5. I made custom docker image which support this flutter sdk, and it works fine. If u have similar issues around here, then think about personal revert for this.
> 
> Thank you. The problem is solved 🙏

Hey @kim-json Since there are couple of problems described here. Are you telling that the upload problem is fixed?

**Comment by wangmir** [comment] 2022-10-28 06:55
> > I made a shell script to upload maven repository with fix pom file. Check below. So, when I change the package name of pom file, then I could upload aar file into jfrog-based maven repository. But, after that, the build of host application failed with two situation.
> > 
> > 1. Failed with referencing classifier-based library, `flutter-1.0-debug`
> > 
> > <img alt="image" width="1268" src="https://user-images.githubusercontent.com/6769075/196741756-c2ccdfe5-35d0-4b8d-b2de-2989b55fedcc.png">
> > This is the problem. It cannot simply get io.flutter.embedding.android.FlutterActivity
> > 
> > 2. `Failed to resolve: flutter-1.0` when referencing non-classifier-based library, `flutter_debug-1.0`
> > 
> > If build with local maven repository, it was fine with non-classifier-based library. But when referencing maven remote repository, it fails with `Failed to resolve:flutter-1.0`, it is because it does not contains classifier for relocation.
> > When I check pom.xml of flutter_debug-1.0, I could see that, there are no for that.
> > ```
> >     <relocation>
> >       <groupId>flutter</groupId>
> >       <artifactId>flutter</artifactId>
> >       <version>1.0</version>
> >       <message>Use classifiers rather than _variant for new publish plugin</message>
> >     </relocation>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > #!/bin/bash
> > 
> > # TODO: Add help and handling null arguments
> > POM_PATH=$1
> > SETTING_FILE_PATH=$2
> > REPOSITORY_ID=$3
> > REPOSITORY_URL=$4
> > 
> > echo $POM_PATH
> > echo $SETTING_FILE_PATH
> > echo $REPOSITORY_ID
> > echo $REPOSITORY_URL
> > 
> > POM_NAME=$(basename "${POM_PATH}")
> > LIB_PATH=$(echo $POM_PATH | sed -e "s/.pom//")
> > POM_DIR=$(dirname "${POM_PATH}")
> > 
> > # When pom file contains multiple aar with different classifier, it should be uploaded separately.
> > if [[ -e "${LIB_PATH}-debug.aar" ]] && [[ -e "${LIB_PATH}-profile.aar" ]] && [[ -e "${LIB_PATH}-release.aar" ]]
> > then
> >     echo "It's classifier based library!"
> >     
> >     # TODO: HOTFIX, it should be removed after release of flutter 3.5 (with this issue https://github.com/flutter/flutter/issues/113417#issuecomment-1283253281)
> >     echo "Fix buggy pom file to remove pom packaging."
> >     sed -e "s/\<packaging\>pom\<\/packaging\>/\<packaging\>aar\<\/packaging\>/" $POM_PATH > "${POM_PATH}_mod"
> >     cp $POM_PATH "${POM_PATH}_back"
> >     mv "${POM_PATH}_mod" $POM_PATH
> > 
> >     echo "Upload release classifier library..."
> >     mvn -s $SETTING_FILE_PATH deploy:deploy-file \
> >         -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
> >         -Dfile="${LIB_PATH}-release.aar" -Dclassifier=release
> > 
> >     echo "Upload profile classifier library..."
> >     mvn -s $SETTING_FILE_PATH deploy:deploy-file \
> >         -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
> >         -Dfile="${LIB_PATH}-profile.aar" -Dclassifier=profile
> > 
> >     echo "Upload debug classifier library..."
> >     mvn -s $SETTING_FILE_PATH deploy:deploy-file \
> >         -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
> >         -Dfile="${LIB_PATH}-debug.aar" -Dclassifier=debug
> > 
> > else
> >     echo "It's common aar library!"
> >     echo "Upload library..."
> > 
> >     mvn -s $SETTING_FILE_PATH deploy:deploy-file \
> >         -DrepositoryId=$REPOSITORY_ID -Durl=$REPOSITORY_URL -DpomFile=$POM_PATH \
> >         -Dfile="${LIB_PATH}.aar"
> > 
> > 
> > 
> > fi
> > 
> > echo "::Upload completed::"
> > ```
> 
> Hey @wangmir is there any solution for the first problem where the system cannot resolve `io.flutter.embedding.android.FlutterActivity`?

So, I mean, even when applying the comment I wrote, I failed to solve this problem.
So, I just reverted this feature as following https://github.com/flutter/flutter/commit/8e30cc9c56bcecc6fd921764b8205d22b8a37fd9
