### ISSUE TITLE
[BUG] in_app_purchase does not provide a proper API to query previous purchases

### ISSUE THREAD

**Issue by idish** [flutter/flutter#119229] opened 2023-01-26 11:44 UTC
The only API to get previous purchases after a session ends, is probably via the `inAppPurchase.instance.restorePurchases()` API.
This is not a viable API for production use as Apple clearly states in their documentation:
> Don't automatically restore purchases, especially when your app is launched. Restoring purchases prompts for the user’s App Store credentials, which interrupts the flow of your app.
https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/restoring_purchased_products

This API should only be used on demand, when a user has a new device or for some other exceptional reason, it definitely shouldn't be used in app launch.

Is there any other way to query previous purchases using the `in_app_purchase` flutter official library?

**Comment by exaby73** [comment] 2023-01-26 14:03
Closing as duplicate of https://github.com/flutter/flutter/issues/109523. Please follow up on the original issue

**Closed by exaby73** 2023-01-26 14:03 UTC
Labels: in triage

**Comment by idish** [comment] 2023-01-26 16:29
@exaby73 So as I understand from that thread, currently the only way to retrieve it properly (without `restorePurchases()`) is using a backend? i.e, there's no local solution as there's no yet support for StoreKit2?
Just noting that `SwiftyStoreKit` library does support local verification. See https://github.com/bizz84/SwiftyStoreKit#receipt-verification

**Comment by exaby73** [comment] 2023-01-27 06:42
I guess not right now. If you want to give it a hand, you can submit a PR :D You're always welcome to contribute
