### ISSUE TITLE
[Bug] flutter build web / flutter build bundle copies files to assets which aren't assets

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#45100] opened 2019-11-18 16:35 UTC
I created a demo for this bug: https://github.com/jld3103/flutter_assets_bug

When you use `flutter build web` / `flutter build bundle` files which aren't in the assets, but have the same name. The are copied to `build/web/assets` / `build/flutter_assets/`.

This needs to be fixed very soon.

**Comment by iapicca** [comment] 2019-11-18 16:59
Hi @jld3103 
could you please provide your updated  `flutter doctor -v` ?
Thank you

**Comment by jld3103** [comment] 2019-11-18 17:22
```
[✓] Flutter (Channel master, v1.12.3-pre.49, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.3-pre.49 at /home/jld3103/flutter
    • Framework revision 21e6fe1ddf (13 hours ago), 2019-11-17 23:39:51 -0500
    • Engine revision 3261324fab
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/jld3103/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/jld3103/Android/Sdk
    • Java binary at: /home/jld3103/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.5994180/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/jld3103/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.5994180
    • Flutter plugin version 41.2.3
    • Dart plugin version 192.7402
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /home/jld3103/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/193.5233.12
    • Flutter plugin version 40.2.5
    • Dart plugin version 193.4386.6

[✓] Connected device (3 available)
    • SM G389F   • 9201048484f5b36f • android-arm    • Android 6.0.1 (API 23)
    • Chrome     • chrome           • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!
```

**Comment by jonahwilliams** [comment] 2019-11-18 23:13
Thanks for the repo @jld3103, I'm taking a look now

**Comment by jonahwilliams** [comment] 2019-11-18 23:27
So the issue here is that this code is triggering our variant detection logic. Normally variants are handled such that all of the following assets are bundled with a single `a.png` asset listed in the manifest.

```
2x/a.png
1x/a.png
a.png
```

There isn't any restriction on what the variant should be called though, which leads to us picking up the random txt file.

For reference: https://github.com/flutter/flutter/blob/ad1d67e0a1ebc444ec9e89573d6df97a2fdb2e41/packages/flutter_tools/lib/src/asset.dart#L499

**Comment by jmagman** [comment] 2019-11-19 01:12
Duplicate of https://github.com/flutter/flutter/issues/45075.

**Closed by jmagman** 2019-11-19 01:12 UTC
Labels: a: assets, tool
