### ISSUE TITLE
Add diffTolerance parameter to matchesGolden

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#76337] opened 2021-02-18 21:54 UTC
Currently, the goldens tests will fail if there is any pixel difference. I'd like to be able to pass a tolerance in via `matchesGolden` and have it be used by the comparator.

Example:

```
matchesGoldenFile(goldenPath, diffTolerance: 0.01)
```

\cc @Piinks

**Comment by Piinks** [comment] 2021-02-18 21:57
Related to https://github.com/flutter/flutter/issues/71437
Golden file testing in flutter/tests has been causing difficulty with rolls when an image changes.
The two times this has occurred so far, the changes were minuscule diffs most likely caused by skia changes. This proposal will let customers specify a pass-through for tiny diffs like this.

**Comment by lukepighetti** [comment] 2021-03-09 12:31
We're seeing tests fail due to 0.09% difference from font rendering on macOS vs Linux.

To quote one of our web devs: "the pipeline failed because of 0.09% diff?!?!?!" 😅

**Comment by lukepighetti** [comment] 2021-03-09 12:57
Just saw this PR, will stop work on my PR. https://github.com/flutter/flutter/pull/76545

**Comment by lukepighetti** [comment] 2021-03-10 15:40
Great! I'll close my PR. Thanks Kate!

**Comment by lukepighetti** [comment] 2021-03-15 00:11
I tried #77014 and I have some feedback.

I'm trying this out now and I'm not sure how to proceed. There are private methods we don't have access to. Once you start unraveling that you're better off doing a copy-paste from what I can tell.

<img width="718" alt="Screen Shot 2021-03-14 at 6 57 31 PM" src="https://user-images.githubusercontent.com/666539/111087282-32dc0280-84f7-11eb-88a9-5689afade15e.png">

From https://github.com/flutter/flutter/pull/76545#issuecomment-786894458
> In that case, you would not have to pass a tolerance level for each individual test. That feels a bit annoying and clunky.

I know the ship has sailed, but IMHO that's a non-issue because you can make a curried version of `matchesGoldenFile` with the tolerance baked in and use it everywhere.  I also don't necessarily want to have a global tolerance. My strategy would be to employ this on problematic tests, picking a tolerance that matches what we typically see when they flake. An incremental tolerance that is easy to implement was my strong preference I looked at addressing this.

**Comment by Piinks** [comment] 2021-03-15 22:24
I think that we have done all of the work we decided to do to address this issue, so I am going to close it. If there is more to do, let me know and we'll re-open! :)

**Closed by Piinks** 2021-03-15 22:24 UTC
Labels: a: tests, d: api docs, d: examples, documentation, framework, passed first triage, proposal, severe: new feature

**Comment by alestiago** [comment] 2024-06-17 10:00
> I think all that remains here is adding some examples of how to do this to the docs.

We are still missing a reference to `goldenFileComparator` in `matchesGoldenFile` and some examples that show how to change the tolerant difference with the final approach.

There are still some users that are finding difficulties on finding this type of documentation, for example see: https://github.com/VeryGoodOpenSource/very_good_cli/issues/972 or from [StackOverflow](https://stackoverflow.com/questions/69082930/specify-diff-tolerance-level-for-golden-test-files-in-flutter/78510535#78510535).
