### ISSUE TITLE
Flutter Upgrade doesn't work as intended

### ISSUE THREAD

**Issue by sidrao2006** [flutter/flutter#63791] opened 2020-08-14 19:56 UTC
Though there are newer versions of `flutter channel beta`, running `flutter upgrade` does not work.
I even tried running `flutter channel` to make sure I am on beta.

## Steps to Reproduce

Run `flutter upgrade`

<details>

<summary>flutter upgrade</summary>

```
Flutter is already up to date on channel beta
Flutter 1.20.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 916c3ac648 (13 days ago) • 2020-08-01 09:01:12 -0700
Engine • revision d6ee1499c2
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)
```

</details>

<details>

<summary>flutter doctor -v</summary>

```
[√] Flutter (Channel beta, 1.20.0, on Microsoft Windows [Version
    10.0.19041.450], locale en-US)
    • Flutter version 1.20.0 at C:\Users\Aneesh\flutter
    • Framework revision 916c3ac648 (13 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Aneesh\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\Aneesh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (3 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      84.0.4147.125
    • Edge (web)       • edge       • web-javascript • Microsoft Edge
      84.0.522.58

• No issues found!
```

</details>

**Comment by SAMYAK99** [comment] 2020-08-14 22:09
Did you have a stable Internet Connection  ? 
I have also faced the same issue . Improving the Internet speed had fixed it 😀

**Comment by martinloesethjensen** [comment] 2020-08-14 22:28
You can navigate to the flutter folder in the terminal and run `git pull`.

After that you can run `flutter upgrade` again

This worked for me :)

**Comment by sidrao2006** [comment] 2020-08-15 06:12
@martinloesethjensen thanks, it worked
But I don't think this is supposed happen
So for know I'll keep this issue open as it may be a bug

**Comment by iapicca** [comment] 2020-08-16 14:40
I'd try running `flutter upgrade --force`
if it fails you may want to post the output of `flutter upgrade -f -v`

**Comment by sidrao2006** [comment] 2020-08-16 14:47
Hey @iapicca, in the flutter docs, we have been instructed to run `flutter upgrade` to upgrade our versions of flutter. However that doesn't work and it doesn't seem to be an issue from my side (i.e, internet error or git remote conflicts) so I assumed it as a bug. Please correct me if I am wrong

**Comment by iapicca** [comment] 2020-08-16 15:22
I believe for an issue to be workable should be reproducible
for example `flutter upgrade -v` could provide an insight about the underlying processes;
please consider that the issue you are describing might have been caused by [changes in the root folder](https://stackoverflow.com/questions/53918412/how-to-upgrade-flutter-if-i-have-local-changes-in-my-flutterroot-folder) ([more fixes](https://stackoverflow.com/questions/52397496/flutter-upgrade-fail))
in which case is definitely not a bug

**Comment by sidrao2006** [comment] 2020-08-16 16:16
@iapicca , @martinloesethjensen was able to reproduce this issue

**Comment by martinloesethjensen** [comment] 2020-08-16 16:18
I have not tried to reproduce it after I had the successful `flutter upgrade` to version 1.20.2

**Comment by sidrao2006** [comment] 2020-08-16 16:22
@martinloesethjensen , I followed your steps and it worked. I think this issue is only reproducible in flutter version 1.20.0 . But I can't be sure until I try to upgrade to the next beta

**Comment by iapicca** [comment] 2020-08-16 16:23
I doubt that without providing logs
this issue will be workable

**Comment by sidrao2006** [comment] 2020-08-16 16:24
@iapicca , sorry but we'll either have to wait for the next beta or if this is a problem with v1.20.0, then I won't be able to reproduce it

**Comment by martinloesethjensen** [comment] 2020-08-16 16:25
@sidrao2006 and @iapicca I just ran `flutter downgrade` and got to version 1.20.1 that was last active version.

After that I ran the `flutter upgrade` command without any issues. 

I'm unsure to why it happened in the first place as I haven't made any changes to the flutter root 🤔

**Comment by martinloesethjensen** [comment] 2020-08-16 16:27
I will try to see if I can reproduce it with version 1.20.0

**Comment by martinloesethjensen** [comment] 2020-08-16 16:34
No success to reproduce it for me with 1.20.0

**Comment by sidrao2006** [comment] 2020-08-16 16:47
I am unable to downgrade to 1.20.0

**Comment by martinloesethjensen** [comment] 2020-08-16 20:36
@sidrao2006 you can run `git checkout 1.20.0` and then you will be on the commit for that tag (`840c920`) 

You can only run `flutter upgrade` when you are on either dev, stable, beta, and master, so because you would be in a detached state with the checkout as mentioned above, then you would have to run `flutter channel`. 

I found out that when you run `git describe --tags` on the stable channel it will return the latest git tag for the stable branch. This would in this case be `1.20.2`. So I don't think we can reproduce it. Unless there's some other way that I don't know of 😄 

If this happens again in the future then I agree with @iapicca that providing more info with `flutter upgrade -v` would be the best.

**Comment by sidrao2006** [comment] 2020-08-17 02:22
@martinloesethjensen , yep. I could try to reproduce it by using `flutter version 1.20.0`

> Note: This is a deprecated command and will be removed in a future update

Also, it leaves flutter in a detached state as well

**Comment by TahaTesser** [comment] 2020-08-17 09:42
Hi @sidrao2006
I see there's an open issue addressing the case you described.  https://github.com/flutter/flutter/issues/63485
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by sidrao2006** [comment] 2020-08-17 09:43
Alright thanks

**Closed by TahaTesser** 2020-08-17 09:42 UTC
