### ISSUE TITLE
My app stuck with white screen in iOS 

### ISSUE THREAD

**Issue by developeranshul1986** [flutter/flutter#70837] opened 2020-11-19 13:43 UTC
I am working on the Flutter stable version 1.22.4 and running in the iOS 13.6 simulator. I have updated the code to the latest version of the flutter stable 1.22.4 and when I run the comman flutter run then in the iOS simuator the screen stuck on the white screen and nothing happen and remain as it is nothing happens in the scree.

Please help me on this as I need it urgent.

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2020-11-19 15:14
Hi @developeranshul1986 
Can you please provide your `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by developeranshul1986** [comment] 2020-11-19 15:34
flutter doctor -v

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale
en-GB)
• Flutter version 1.22.4 at /Users/xyz/Documents/FlutterSDK/flutter
• Framework revision 1aafb3a8b9 (5 days ago), 2020-11-13 09:59:28 -0800
• Engine revision 2c956a31c0
• Dart version 2.10.4

[✗] Android toolchain - develop for Android devices
✗ Unable to locate Android SDK.
Install Android Studio from:
https://developer.android.com/studio/index.html
On first launch it will assist you in installing the Android SDK
components.
(or visit https://flutter.dev/docs/get-started/install/macos#android-setup
for detailed instructions).
If the Android SDK has been installed to a custom location, set
ANDROID_SDK_ROOT to that location.
You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.2.1, Build version 11B500
• CocoaPods version 1.10.0

[!] Android Studio (not installed)
• Android Studio not found; download from
https://developer.android.com/studio/index.html
(or visit https://flutter.dev/docs/get-started/install/macos#android-setup
for detailed instructions).


[✓] Connected device (1 available)
• iPhone 11 Pro Max (mobile) • 6B5F6248-65F9-460B-A980-CC7E08BE4FD5 • ios •
com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

When I run the flutter run --verbose , there is very large logs continuously printing which I can't over here

**Comment by developeranshul1986** [comment] 2020-11-19 16:52
This is the xcode output

dyld: Library not loaded: @rpath/AppAuth.framework/AppAuth
Referenced from: /Users/vipulsharma/Library/Developer/CoreSimulator/Devices/EA126775-C98E-4490-B8BB-074AB683CBAB/data/Containers/Bundle/Application/B984E6ED-7575-459A-8910-76BCC5EE6D11/Clearance.ae.app/Clearance.ae
Reason: image not found
(lldb)

**Comment by TahaTesser** [comment] 2020-11-20 08:55
Hi @developeranshul1986 
Closed by accident, 

Can you please provide your complete  `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using the third party packages
Thank you

**Comment by developeranshul1986** [comment] 2020-11-20 08:56
I got this error in the xcode
dyld: Library not loaded: @rpath/AppAuth.framework/AppAuth
Referenced from: /Users/xmyzz/Library/Developer/CoreSimulator/Devices/EA126775-C98E-4490-B8BB-074AB683CBAB/data/Containers/Bundle/Application/B984E6ED-7575-459A-8910-76BCC5EE6D11/xyz.ae.app/xyz.ae
Reason: image not found
(lldb)

**Comment by darshankawar** [comment] 2020-11-24 10:10
@developeranshul1986 
Not sure if it could be happening due to the iOS simulator version you are using. See [this](https://github.com/flutter/flutter/issues/48035#issuecomment-587699924) issue comment for more details. You may try to upgrade Xcode which will also upgrade the iOS simulator version and try again to see if it resolves your issue.

**Comment by developeranshul1986** [comment] 2020-11-30 14:37
I have resolved by downgrading the flutter to 1.17.1 and it works.

There is issue when you run your old projects in the 1.22.4 versions

**Comment by TahaTesser** [comment] 2020-11-30 15:03
Hi @developeranshul1986 
To better address the issue,  Can you please provide your complete  `flutter run --verbose` logs  in a plain text file in the comment attachment, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) without using the third party packages

Without additional reproducible info, it's hard to pinpoint the cause of the issue 
Thank you

**Comment by developeranshul1986** [comment] 2020-12-13 04:27
Hi @TahaTesser ,
I send the error I am getting already,
dyld: Library not loaded: @rpath/AppAuth.framework/AppAuth
Referenced from: /Users/xmyzz/Library/Developer/CoreSimulator/Devices/EA126775-C98E-4490-B8BB-074AB683CBAB/data/Containers/Bundle/Application/B984E6ED-7575-459A-8910-76BCC5EE6D11/xyz.ae.app/xyz.ae
Reason: image not found
(lldb)

The app is created in the version 1.17.1 and I was running on the 1.22.4, so this issue occured due to the pod installationg or something. So I switch back to the 1.17.1 and it works now.

**Comment by TahaTesser** [comment] 2020-12-14 07:01
Hi @developeranshul1986 
To better address the issue, we need complete logs and reproducible a code sample.
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-12-14 07:01 UTC
Labels: in triage
