### ISSUE TITLE
flutter extract as a widget in intellij idea nor working please help

### ISSUE THREAD

**Issue by rashedheydari2001** [flutter/flutter#125772] opened 2023-04-30 16:39 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

flutter extension in intellij idea can't extract as a widget i try ctrl + alt + w but not worked

### Expected results

extract as a widget

### Actual results

nothing just this function not work

### Code sample

nothing

### Screenshots or Video

nothing 

### Logs

nothing

### Flutter Doctor output

nothing

**Comment by tomg2012** [comment] 2023-04-30 18:44
Hi, this is not a bug, but is rather caused by a keyboard shortcut conflict with the Kotlin Plugin's **Run Scratch File** command (also Ctrl+Alt+W ).

To fix your issue (if you don't need that Kotlin keybind):

1. **File -> Settings -> Keymap**  (displays the Keymap settings)
2. Click the **Search**  icon on the  right (Find Actions by Shortcut)
3. Click in the search field and perform the shortcut  (**Ctl+Alt+w** )
4. You will see a filtered list of actions associated with that shortcut
5. Right click on the Kotlin command and select **Remove**
6. The Kotlin Command will disappear from the list.

Now your shortcut will work as advertised!

If you want to keep the Kotlin shortcut, rebind it to an available key instead of removing it.

And, finally, you can also right click on the class you want to extract and use **Refactor->Extract Widget** from the pop up menu.

**Comment by rashedheydari2001** [comment] 2023-04-30 21:34
thanks

**Comment by darshankawar** [comment] 2023-05-02 08:23
Based on https://github.com/flutter/flutter/issues/125772#issuecomment-1529112640, closing as resolved and not a framework bug.

**Closed by darshankawar** 2023-05-02 08:23 UTC
Labels: in triage
