### ISSUE TITLE
[Windows][Desktop]: onLongPress gesture events not firing on touch screen device

### ISSUE THREAD

**Issue by SriramKiranSenthilkumar** [flutter/flutter#84969] opened 2021-06-21 09:20 UTC
## Steps to Reproduce

1. Run the below code in windows machine with touchscreen compatibility.
<details>
<summary>Code snippet</summary>

```
import 'package:flutter/material.dart';

void main() {
  return runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.blue),
      home: _MyHomePage(),
    );
  }
}

class _MyHomePage extends StatefulWidget {
  // ignore: prefer_const_constructors_in_immutables
  _MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<_MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion Flutter chart'),
        ),
        body: Container(
          child: GestureDetector(
            onLongPress: () {
              print("longPress tapped");
            },
            child: Center(
              child: Container(
                height: 300,
                width: 300,
                color: Colors.blue
              ),
            ),
          ),
        ));
  }
}
```

</details>

2. Perform long press gesture on the touch screen, the event won't get fired.
3. We have also attached a screen recording below for reference.
<details>
  <summary>Recording</summary>

https://user-images.githubusercontent.com/63577117/122738800-f0695500-d29f-11eb-9c6a-21a599142eca.mp4

</details>

<details>
  <summary>Logs</summary>

```
Doctor summary
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.1052], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.10.2)
[√] Android Studio (version 4.1.0)
[√] VS Code, 64-bit edition (version 1.57.1)
[√] Connected device (3 available)

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2021-06-21 13:32
@SriramKiranSenthilkumar 
Can you try adding `behavior: HitTestBehavior.translucent` and see if it helps ?

**Comment by SriramKiranSenthilkumar** [comment] 2021-06-22 05:03
@darshankawar 
I have tried setting the `HitTestBehavior` value as `tranclucent` and still the event didn't get fired.

**Comment by darshankawar** [comment] 2021-06-22 06:23
This seems to be specific to touch screen based device, which I don't have to verify and replicate the issue, so I am unable to identify the root-cause and pinpoint the issue. Keeping this open for further investigation from team.

Note: Verified on Windows 10 machine on which the long press using mouse is registered properly.

**Comment by Hixie** [comment] 2023-02-21 22:26
Since we have no way to reproduce this ourselves, we cannot really debug it.

I would encourage you to step through the code with a debugger, or enable the [debugPrintGestureArenaDiagnostics](https://master-api.flutter.dev/flutter/gestures/debugPrintGestureArenaDiagnostics.html) feature, to determine the cause of the issue here, and then file a new issue with the precise problem, and maybe even a PR to fix it. :-)

**Comment by Hixie** [comment] 2023-02-21 22:26
(Closing per last comment.)

**Closed by Hixie** 2023-02-21 22:26 UTC
Labels: framework, platform-windows, f: gestures, a: desktop, passed first triage, P4
