### ISSUE TITLE
TabBar indicatorColor not visible with colorScheme.primary at full opacity

### ISSUE THREAD

**Issue by kksal55** [flutter/flutter#159658] opened 2024-12-02 08:13 UTC
### Steps to reproduce

1. Create a TabBar widget.
2. Set indicatorColor to Theme.of(context).colorScheme.primary.
3. Observe that the indicator is not visible.
4. Change indicatorColor to Theme.of(context).colorScheme.primary.withAlpha(254).
5. Observe that the indicator becomes visible.

### Expected results

The indicator should be visible when using Theme.of(context).colorScheme.primary with full opacity.

### Actual results

The indicator is not visible when using full opacity (255), but becomes visible when using slightly lower opacity (254).

### Code sample

<details open><summary>Code sample</summary>

```dart
TabBar(
  indicatorColor: Theme.of(context).colorScheme.primary, // Not visible
  // indicatorColor: Theme.of(context).colorScheme.primary.withAlpha(254), // Visible
  // indicatorColor: Theme.of(context).colorScheme.primary.withOpacity(0.99), // Visible
  // indicatorColor: Theme.of(context).colorScheme.primary.withOpacity(0.99), // Visible
  // indicatorColor: Colors.pink, // Visible
  // indicatorColor: Theme.of(context).colorScheme.primary.withOpacity(1.0), // Not visible
  // indicatorColor: Theme.of(context).colorScheme.primary.withAlpha(255), //Not visible

  tabs: [
    Tab(text: 'Tab 1'),
    Tab(text: 'Tab 2'),
  ],
)
```

</details>

### My themeData

<details open>
<summary>My themeData</summary>

```dart
final Map<String, ThemeData> THM = {

  "PEMBE": ThemeData(
    useMaterial3: true,
    brightness: Brightness.light,
    primaryColor: Colors.pink[400]!,
    colorScheme: ColorScheme.light(
      primary: Colors.pink[400]!,
      primaryContainer: Colors.pink[300],
      secondary: Colors.pink[300]!,
      secondaryContainer: Colors.pink[200],
.
.
.
```

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B2091 darwin-arm64, locale tr-TR)
    • Flutter version 3.24.5 on channel stable at /Users/koksaliyigun/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc1)
    • Android SDK at /Users/koksaliyigun/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.95.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (6 available)
    • iPhone (mobile)                 • 00008140-001C75560EBB001C            • ios            • iOS 18.1 22B83
    • iPhone 15 Plus (mobile)         • 0769061F-2A8F-4243-AF24-BF1B9FF8110E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • iPhone 15 Pro (mobile)          • 5DB7EE88-CBB7-4E54-A012-F15923F94712 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 15.1.1 24B2091 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 15.1.1 24B2091 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 131.0.6778.86
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local
      area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2024-12-02 09:01
Hi @kksal55 
Thanks for the report. When trying your code sample I can see the indicator color 

<img width="818" alt="Screenshot 2024-12-02 at 10 59 48" src="https://github.com/user-attachments/assets/861a8dfe-3218-4bc9-87e5-993b79a076c4">


### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

/// Flutter code sample for [TabBar].

void main() => runApp(const TabBarApp());

class TabBarApp extends StatelessWidget {
  const TabBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        primaryColor: Colors.pink[400]!,
        colorScheme: ColorScheme.light(
          primary: Colors.pink[400]!,
          primaryContainer: Colors.pink[300],
          secondary: Colors.pink[300]!,
          secondaryContainer: Colors.pink[200],
        ),
      ),
      home: const TabBarExample(),
    );
  }
}

class TabBarExample extends StatelessWidget {
  const TabBarExample({super.key});

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      initialIndex: 1,
      length: 3,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('TabBar Sample'),
          bottom: TabBar(
            indicatorColor:
                Theme.of(context).colorScheme.primary, // Not visible
            tabs: const <Widget>[
              Tab(
                icon: Icon(Icons.cloud_outlined),
              ),
              Tab(
                icon: Icon(Icons.beach_access_sharp),
              ),
              Tab(
                icon: Icon(Icons.brightness_5_sharp),
              ),
            ],
          ),
        ),
        body: const TabBarView(
          children: <Widget>[
            Center(
              child: Text("It's cloudy here"),
            ),
            Center(
              child: Text("It's rainy here"),
            ),
            Center(
              child: Text("It's sunny here"),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>


Could you please share a complete reproducible sample with some screenshots? Thanks!

**Comment by kksal55** [comment] 2024-12-02 10:57
Hello @TahaTesser,
I am experiencing the issue I mentioned when I use the TabBar inside a PreferredSize widget. If I use the TabBar directly as a child of the AppBar, there is no problem. However, when I wrap it as AppBar/bottom: PreferredSize, I encounter an issue with the indicatorColor: Theme.of(context).primaryColor parameter.



```
class TabBarExample extends StatelessWidget {
  const TabBarExample({super.key});

  @override
  Widget build(BuildContext context) {


    return DefaultTabController(
      initialIndex: 1,
      length: 3,
      child: Scaffold(
        appBar: AppBar(
          //iconTheme: IconThemeData(color: Colors.white), // Geri butonu rengi
          backgroundColor: Theme.of(context).primaryColor,
          elevation: 0,
          title: Text(
            "TEST",
            style: TextStyle(
              color: Colors.white,
              fontSize: 20,
              fontWeight: FontWeight.w600,
              letterSpacing: 0.5,
            ),
          ),
          bottom: PreferredSize(
            preferredSize: Size.fromHeight(48),
            child: Container(
              color: Colors.white,
              child: TabBar(
                tabAlignment: TabAlignment.center,
                isScrollable: true,
                dividerColor: Theme.of(context).primaryColor,
                indicatorWeight: 4.5,
                indicatorSize: TabBarIndicatorSize.label,
                indicatorColor: Theme.of(context).primaryColor.withOpacity(1.0), //not visible
                // indicatorColor: Theme.of(context).primaryColor.withOpacity(0.9), //visible
                labelColor: Theme.of(context).primaryColor,
                unselectedLabelColor: Colors.grey[900],
                labelStyle: TextStyle(
                  fontSize: 15,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 0.3,
                ),
                unselectedLabelStyle: TextStyle(
                  fontSize: 15,
                  fontWeight: FontWeight.w400,
                ),
                tabs: List<Widget>.generate(3, (int index) {
                  return Tab(
                    child: Container(
                      padding: EdgeInsets.symmetric(horizontal: 8),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text(
                            "${index + 1}. Tab",
                          ),
                        ],
                      ),
                    ),
                  );
                }),
              ),
            ),
          ),
        ),
        body: const TabBarView(
          children: <Widget>[
            Center(
              child: Text("It's cloudy here"),
            ),
            Center(
              child: Text("It's rainy here"),
            ),
            Center(
              child: Text("It's sunny here"),
            ),
          ],
        ),
      ),
    );
  }
}
```
![Simulator Screenshot - iPhone 15 Pro - 2024-12-02 at 13 56 44](https://github.com/user-attachments/assets/8935d7a8-4428-437e-b012-55b682ec799d)

**Comment by TahaTesser** [comment] 2024-12-05 13:40
Hi! Interestingly, this seems to be an intended behavior. You're primary color as the background for `AppBar` which is applied to the underlying `Material` widget so `TabBar` is looking at this `Material` color and applying a white color adjustment so the indicator is visible on primary color.

https://github.com/flutter/flutter/blob/ab5b20c16d56c8e608773ce65c3f7c39d515d4a5/packages/flutter/lib/src/material/tabs.dart#L1416-L1419

However, you're using white background for `TabBar`  with primary indicator color but color adjusted white indicator becomes invisible on white background. 

<img width="722" alt="Screenshot 2024-12-05 at 15 32 23" src="https://github.com/user-attachments/assets/196a45b3-c88b-4ced-970a-406058717560">

You can disable this automatic  color adjustment by setting [automaticIndicatorColorAdjustment.html](https://api.flutter.dev/flutter/material/TabBar/automaticIndicatorColorAdjustment.html) to `false`.

Here is a minimal sample 

### Code sample

<details>
<summary>expand to view the code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: DefaultTabController(
        initialIndex: 1,
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            backgroundColor: Theme.of(context).colorScheme.primary,
            foregroundColor: Colors.amber,
            title: const Text('TabBar Sample'),
            bottom: PreferredSize(
              preferredSize: const Size.fromHeight(48.0),
              child: ColoredBox(
                color: Colors.white,
                child: TabBar(
                  automaticIndicatorColorAdjustment: false,
                  indicatorColor: Theme.of(context).colorScheme.primary,
                  tabs: const <Widget>[
                    Tab(
                      icon: Icon(Icons.cloud_outlined),
                    ),
                    Tab(
                      icon: Icon(Icons.beach_access_sharp),
                    ),
                    Tab(
                      icon: Icon(Icons.brightness_5_sharp),
                    ),
                  ],
                ),
              ),
            ),
          ),
          body: const TabBarView(
            children: <Widget>[
              Center(
                child: Text("It's cloudy here"),
              ),
              Center(
                child: Text("It's rainy here"),
              ),
              Center(
                child: Text("It's sunny here"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

Closing as resolved.

**Closed by TahaTesser** 2024-12-05 13:40 UTC
Labels: framework, f: material design, team-design
