### ISSUE TITLE
TextField-> maxLines should be backed with minLines

### ISSUE THREAD

**Issue by D4G4** [flutter/flutter#20957] opened 2018-08-23 17:56 UTC
The `maxLines` attribute simply provides with maximum lines pre-generated by the framework, thus increasing the size of `TextField`. 
There should also be an option of `minLines` where `maxLines` will act as the maximum lines to which the TextField can EXPAND and then enables the scrolling. 
![There is no restriction to maxLines either](https://user-images.githubusercontent.com/19249966/44542682-2d492200-a72b-11e8-9d94-28e6b8930519.gif)

Or
`TextInputType.multiline` should set the default `maxLines` to 1 and then maximum lines can grow till the size defined in the attribute.

![third](https://user-images.githubusercontent.com/19249966/44542876-acd6f100-a72b-11e8-9f55-caefbed0e376.gif)

**Comment by goderbauer** [comment] 2019-01-03 19:17
This sounds like a duplicate of https://github.com/flutter/flutter/issues/19105?

**Closed** 2019-01-03 19:18 UTC
Labels: a: text input, framework, severe: new feature
