### ISSUE TITLE
Could not get unknown property 'android' for project ':camera_android' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by christianfunginet** [flutter/flutter#141170] opened 2024-01-09 13:09 UTC
### Steps to reproduce

1 Update camera plugin to 0.10.5+9 
2 Build fail

### Expected results

Im uneable to run app

### Actual results

FAILURE: Build failed with an exception.

* What went wrong:
> Could not load compiled classes for build file 'C:\Users\christian\AppData\Local\Pub\Cache\hosted\pub.dev\camera_android-0.10.8+16\android\build.gradle' from cache.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':camera_android' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':flutter_plugin_android_lifecycle'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':camera_android' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Running Gradle task 'assembleDebug'...                             29,5s
Exception: Gradle task assembleDebug failed with exit code 1

### Code sample

<details open><summary>Code sample</summary>

```dart
pubspect.yaml
name: mushing
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependency_overrides:
  http: ^0.13.1

dependencies:
  flutter:
    sdk: flutter


  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5

  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  video_player: ^2.8.2
  visibility_detector: ^0.4.0+2
  google_fonts: ^6.1.0
  go_router: ^13.0.1
  permission_handler: ^11.1.0
  #gallery_saver: ^2.3.2
  image_picker: ^1.0.4
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10
  firebase_database: ^10.2.5
  cached_network_image: ^3.2.3
  cloud_functions: ^4.3.1

  transparent_image: ^2.0.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.3
  dio: ^5.3.3
  connectivity: ^3.0.6
  universal_io: ^2.2.2
  carousel_slider: ^4.2.1
  like_button: ^2.0.5
  video_compress: ^3.1.2
  video_thumbnail: ^0.5.3
  file_picker: ^6.1.1
  #cached_video_player: ^2.0.4

  exif: ^3.2.1
  flutter_map: ^6.1.0
  location: ^5.0.0
  latlong2: ^0.9.0
  image_stack: ^2.1.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.0.0
  mercadopago_sdk: ^1.3.0
  awesome_card: ^1.1.7
  expandable_bottom_sheet: ^1.1.1+1
  flutter_native_splash: ^2.3.4
  flutter_svg: ^2.0.8
  animate_do: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  crypto: ^3.0.3
  swipe_to: ^1.0.2

  #file_saver: ^0.2.6

  syncfusion_flutter_pdfviewer: ^24.1.44
  flutter_downloader: ^1.11.5
  device_info_plus: ^9.1.1
  widgets_to_image: ^0.0.2
  flutter_chat_ui: ^1.6.10
  record: ^5.0.4
  flutter_audio_waveforms: ^1.2.1+8
  just_audio: ^0.9.34
  marquee: ^2.2.3
  localstorage: ^4.0.1+4
  flutter_chat_types: ^3.6.2
  path_provider: ^2.1.1
  camera: ^0.10.5+9

    

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/mushing_image_gradient.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: "assets/logo/mushing_image_gradient.png"
  adaptive_icon_background: "#77202f"
  web:
    generate: true
    image_path: "assets/logo/mushing_image_gradient.png"
    background_color: "#77202f"
    theme_color: "#77202f"
  windows:
    generate: true
    image_path: "assets/logo/mushing_image_gradient.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/mushing_image_gradient.png"



dev_dependencies:
  build_runner:
  riverpod_generator: ^2.3.2

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/logo/

flutter_intl:
  enabled: true

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
FAILURE: Build failed with an exception.

* What went wrong:
> Could not load compiled classes for build file 'C:\Users\christian\AppData\Local\Pub\Cache\hosted\pub.dev\camera_android-0.10.8+16\android\build.gradle' from cache.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':camera_android' of type org.gradle.api.Project.
   > Could not find method implementation() for arguments [project ':flutter_plugin_android_lifecycle'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   > Could not get unknown property 'android' for project ':camera_android' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s```

</details>


### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.16.5, on Microsoft Windows [Versi¢n 10.0.19045.3803], locale es-AR)
    • Flutter version 3.16.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\christian\AppData\Local\Android\sdk
    • Platform android-34, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.3.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32811.315
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.85.1)
    • VS Code at C:\Users\christian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.80.0

[√] Connected device (4 available)
    • 5048A (mobile)    • 7P55V8NFFE59SSA6 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Versi¢n 10.0.19045.3803]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 120.0.6099.131
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 120.0.2210.121

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by dam-ease** [comment] 2024-01-09 13:47
Hello @christianfunginet.
I added `camera: ^0.10.5+9` to my `pubspec.yaml` file and ran the sample here https://pub.dev/packages/camera/example both on Android and iOS but can't reproduce any issue on my end as it runs fine.
This might be similar to:
https://github.com/flutter/flutter/issues/43247
https://github.com/flutter/flutter/issues/24389
Can you check the comments under these threads to see if any works in your case?

**Comment by dam-ease** [comment] 2024-01-10 06:48
Thanks for your response. Per your last comment, I believe this is working fine now.
Closing this from here, if you disagree, kindly comment and I'll reopen this.

**Closed by dam-ease** 2024-01-10 06:48 UTC
Labels: in triage
