### ISSUE TITLE
Arabic text don't  resize  with padding

### ISSUE THREAD

**Issue by samithe7** [flutter/flutter#101873] opened 2022-04-13 23:50 UTC
```dart

class QMxHadith {
  const QMxHadith(
      {required this.textBangla,
      required this.textArabic,
      required this.name,
      required this.bookName});
  final String textBangla;
  final String textArabic;

  final String name;

  final String bookName;

  static const List<QMxHadith> hadith = [
    QMxHadith(
        textBangla:
            """নবী (সাল্লাল্লাহু ‘আলাইহি ওয়া সাল্লাম) মু’আয (রাঃ)-কে ইয়ামান দেশে (শাসক হিসেবে) প্রেরণ করেন। অতঃপর বললেন, সেখানকার অধিবাসীদেরকে এ সাক্ষ্য দানের প্রতি আহবান করবে যে, আল্লাহ ব্যতীত প্রকৃত কোন উপাস্য নেই এবং আমি আল্লাহর রসূল। যদি তারা তা মেনে নেয় তবে তাদেরকে অবগত কর যে, আল্লাহ তা’আলা তাদের উপর প্রতি দিনে ও রাতে পাঁচ ওয়াক্ত নামায ফরয করেছেন। যদি সেটাও তারা মেনে নেয় তবে তাদেরকে অবগত কর যে, আল্লাহ তা’আলা তাদের উপর তাদের সম্পদের মধ্য থেকে সদকা (যাকাত) ফরয করেছেন। যেটা ধনীদের নিকট থেকে গৃহীত হবে আর দরিদ্রদের মাঝে প্রদান করা হবে।""",
        textArabic:
            """حَدَّثَنَا أَبُو عَاصِمٍ الضَّحَّاكُ بْنُ مَخْلَدٍ، عَنْ زَكَرِيَّاءَ بْنِ إِسْحَاقَ، عَنْ يَحْيَى بْنِ عَبْدِ اللَّهِ بْنِ صَيْفِيٍّ، عَنْ أَبِي مَعْبَدٍ، عَنِ ابْنِ عَبَّاسٍ ـ رضى الله عنهما ـ أَنَّ النَّبِيَّ صلى الله عليه وسلم بَعَثَ مُعَاذًا ـ رضى الله عنه ـ إِلَى الْيَمَنِ فَقَالَ ‏ "‏ ادْعُهُمْ إِلَى شَهَادَةِ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ، وَأَنِّي رَسُولُ اللَّهِ، فَإِنْ هُمْ أَطَاعُوا لِذَلِكَ فَأَعْلِمْهُمْ أَنَّ اللَّهَ قَدِ افْتَرَضَ عَلَيْهِمْ خَمْسَ صَلَوَاتٍ فِي كُلِّ يَوْمٍ وَلَيْلَةٍ، فَإِنْ هُمْ أَطَاعُوا لِذَلِكَ فَأَعْلِمْهُمْ أَنَّ اللَّهَ افْتَرَضَ عَلَيْهِمْ صَدَقَةً فِي أَمْوَالِهِمْ، تُؤْخَذُ مِنْ أَغْنِيَائِهِمْ وَتُرَدُّ عَلَى فُقَرَائِهِمْ ‏"‏‏.‏""",
        name: 'ইব্‌নু ‘আব্বাস (রাঃ) থেকে বর্ণিতঃ',
        bookName: 'বুখারী'),
    QMxHadith(
        textBangla:
            """এক বেদুইন নবী (সাল্লাল্লাহু ‘আলাইহি ওয়া সাল্লাম)-এর নিকট এসে বলল, আমাকে এমন একটি আমলের কথা বলুন যদি আমি তা সম্পাদন করি তবে জান্নাতে প্রবেশ করবো। রাসূল (সাল্লাল্লাহু ‘আলাইহি ওয়া সাল্লাম) বললেনঃ আল্লাহর ইবাদত করবে আর তার সাথে অপর কোন কিছু শরীক করবে না। ফরয সালাত আদায় করবে, ফরয যাকাত প্রদান করবে, রমযান মাসে সিয়াম, পালন করবে। সে বলল, যাঁর হাতে আমার প্রাণ রয়েছে তার শপথ করে বলছি, আমি এর চেয়ে বেশী করবো না। যখন সে ফিরে গেল, নবী (সাল্লাল্লাহু ‘আলাইহি ওয়া সাল্লাম) বললেনঃ যে ব্যক্তি কোন জান্নাতী ব্যক্তিকে দেখতে পছন্দ করে সে যেন এই ব্যক্তি দেখে নেয়। """,
        textArabic:
            """حَدَّثَنِي مُحَمَّدُ بْنُ عَبْدِ الرَّحِيمِ، حَدَّثَنَا عَفَّانُ بْنُ مُسْلِمٍ، حَدَّثَنَا وُهَيْبٌ، عَنْ يَحْيَى بْنِ سَعِيدِ بْنِ حَيَّانَ، عَنْ أَبِي زُرْعَةَ، عَنْ أَبِي هُرَيْرَةَ ـ رضى الله عنه ـ أَنَّ أَعْرَابِيًّا، أَتَى النَّبِيَّ صلى الله عليه وسلم فَقَالَ دُلَّنِي عَلَى عَمَلٍ إِذَا عَمِلْتُهُ دَخَلْتُ الْجَنَّةَ‏.‏ قَالَ ‏"‏ تَعْبُدُ اللَّهَ لاَ تُشْرِكُ بِهِ شَيْئًا، وَتُقِيمُ الصَّلاَةَ الْمَكْتُوبَةَ، وَتُؤَدِّي الزَّكَاةَ الْمَفْرُوضَةَ، وَتَصُومُ رَمَضَانَ ‏"‏‏.‏ قَالَ وَالَّذِي نَفْسِي بِيَدِهِ لاَ أَزِيدُ عَلَى هَذَا‏.‏ فَلَمَّا وَلَّى قَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ مَنْ سَرَّهُ أَنْ يَنْظُرَ إِلَى رَجُلٍ مِنْ أَهْلِ الْجَنَّةِ فَلْيَنْظُرْ إِلَى هَذَا ‏"‏‏.‏ حَدَّثَنَا مُسَدَّدٌ، عَنْ يَحْيَى، عَنْ أَبِي حَيَّانَ، قَالَ أَخْبَرَنِي أَبُو زُرْعَةَ، عَنِ النَّبِيِّ صلى الله عليه وسلم بِهَذَا‏.‏ """,
        name: 'আবূ হুরায়রা (রাঃ) থেকে বর্ণিতঃ',
        bookName: 'বুখারী'),

  ];
}

class GxHadith extends StatelessWidget {
  const GxHadith({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SliverList(
      delegate: SliverChildBuilderDelegate(
        (context, index) {
          final data = QMxHadith.hadith[index];

          return Padding(
            padding: const EdgeInsets.all(11.0),
            child: Column(
              children: [
                Text(data.textArabic),
                Text(data.textBangla),
              ],
            ),
          );
        },
        childCount: 4,
      ),
   
    );
  }
}

```

**Comment by samithe7** [comment] 2022-04-13 23:54
![Screenshot_1649893714](https://user-images.githubusercontent.com/53804061/163288178-4a1cad98-0120-4c4b-9a4a-23d4cc77a27c.png)

**Comment by maheshmnj** [comment] 2022-04-14 08:16
Hi @samithe7, Thanks for filing the issue. I am quite not sure I understood the issue, Can you please add some description to the original report so that it clarifies the issue, along with the output of `flutter doctor -v`?  

However, running your code sample the output looks fine to me.

https://user-images.githubusercontent.com/31410839/163343443-81b2c897-9274-4b9b-b5f0-b3f3b822a039.mov


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('$_counter'),
      ),
      body: CustomScrollView(
        slivers: [GxHadith()],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class QMxHadith {
  const QMxHadith(
      {required this.textBangla,
      required this.textArabic,
      required this.name,
      required this.bookName});
  final String textBangla;
  final String textArabic;

  final String name;

  final String bookName;

  static const List<QMxHadith> hadith = [
    QMxHadith(
        textBangla:
            """নবী (সাল্লাল্লাহু ‘আলাইহি ওয়া সাল্লাম) মু’আয (রাঃ)-কে ইয়ামান দেশে (শাসক হিসেবে) প্রেরণ করেন। অতঃপর বললেন, সেখানকার অধিবাসীদেরকে এ সাক্ষ্য দানের প্রতি আহবান করবে যে, আল্লাহ ব্যতীত প্রকৃত কোন উপাস্য নেই এবং আমি আল্লাহর রসূল। যদি তারা তা মেনে নেয় তবে তাদেরকে অবগত কর যে, আল্লাহ তা’আলা তাদের উপর প্রতি দিনে ও রাতে পাঁচ ওয়াক্ত নামায ফরয করেছেন। যদি সেটাও তারা মেনে নেয় তবে তাদেরকে অবগত কর যে, আল্লাহ তা’আলা তাদের উপর তাদের সম্পদের মধ্য থেকে সদকা (যাকাত) ফরয করেছেন। যেটা ধনীদের নিকট থেকে গৃহীত হবে আর দরিদ্রদের মাঝে প্রদান করা হবে।""",
        textArabic:
            """حَدَّثَنَا أَبُو عَاصِمٍ الضَّحَّاكُ بْنُ مَخْلَدٍ، عَنْ زَكَرِيَّاءَ بْنِ إِسْحَاقَ، عَنْ يَحْيَى بْنِ عَبْدِ اللَّهِ بْنِ صَيْفِيٍّ، عَنْ أَبِي مَعْبَدٍ، عَنِ ابْنِ عَبَّاسٍ ـ رضى الله عنهما ـ أَنَّ النَّبِيَّ صلى الله عليه وسلم بَعَثَ مُعَاذًا ـ رضى الله عنه ـ إِلَى الْيَمَنِ فَقَالَ ‏ "‏ ادْعُهُمْ إِلَى شَهَادَةِ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ، وَأَنِّي رَسُولُ اللَّهِ، فَإِنْ هُمْ أَطَاعُوا لِذَلِكَ فَأَعْلِمْهُمْ أَنَّ اللَّهَ قَدِ افْتَرَضَ عَلَيْهِمْ خَمْسَ صَلَوَاتٍ فِي كُلِّ يَوْمٍ وَلَيْلَةٍ، فَإِنْ هُمْ أَطَاعُوا لِذَلِكَ فَأَعْلِمْهُمْ أَنَّ اللَّهَ افْتَرَضَ عَلَيْهِمْ صَدَقَةً فِي أَمْوَالِهِمْ، تُؤْخَذُ مِنْ أَغْنِيَائِهِمْ وَتُرَدُّ عَلَى فُقَرَائِهِمْ ‏"‏‏.‏""",
        name: 'ইব্‌নু ‘আব্বাস (রাঃ) থেকে বর্ণিতঃ',
        bookName: 'বুখারী'),
    QMxHadith(
        textBangla:
            """এক বেদুইন নবী (সাল্লাল্লাহু ‘আলাইহি ওয়া সাল্লাম)-এর নিকট এসে বলল, আমাকে এমন একটি আমলের কথা বলুন যদি আমি তা সম্পাদন করি তবে জান্নাতে প্রবেশ করবো। রাসূল (সাল্লাল্লাহু ‘আলাইহি ওয়া সাল্লাম) বললেনঃ আল্লাহর ইবাদত করবে আর তার সাথে অপর কোন কিছু শরীক করবে না। ফরয সালাত আদায় করবে, ফরয যাকাত প্রদান করবে, রমযান মাসে সিয়াম, পালন করবে। সে বলল, যাঁর হাতে আমার প্রাণ রয়েছে তার শপথ করে বলছি, আমি এর চেয়ে বেশী করবো না। যখন সে ফিরে গেল, নবী (সাল্লাল্লাহু ‘আলাইহি ওয়া সাল্লাম) বললেনঃ যে ব্যক্তি কোন জান্নাতী ব্যক্তিকে দেখতে পছন্দ করে সে যেন এই ব্যক্তি দেখে নেয়। """,
        textArabic:
            """حَدَّثَنِي مُحَمَّدُ بْنُ عَبْدِ الرَّحِيمِ، حَدَّثَنَا عَفَّانُ بْنُ مُسْلِمٍ، حَدَّثَنَا وُهَيْبٌ، عَنْ يَحْيَى بْنِ سَعِيدِ بْنِ حَيَّانَ، عَنْ أَبِي زُرْعَةَ، عَنْ أَبِي هُرَيْرَةَ ـ رضى الله عنه ـ أَنَّ أَعْرَابِيًّا، أَتَى النَّبِيَّ صلى الله عليه وسلم فَقَالَ دُلَّنِي عَلَى عَمَلٍ إِذَا عَمِلْتُهُ دَخَلْتُ الْجَنَّةَ‏.‏ قَالَ ‏"‏ تَعْبُدُ اللَّهَ لاَ تُشْرِكُ بِهِ شَيْئًا، وَتُقِيمُ الصَّلاَةَ الْمَكْتُوبَةَ، وَتُؤَدِّي الزَّكَاةَ الْمَفْرُوضَةَ، وَتَصُومُ رَمَضَانَ ‏"‏‏.‏ قَالَ وَالَّذِي نَفْسِي بِيَدِهِ لاَ أَزِيدُ عَلَى هَذَا‏.‏ فَلَمَّا وَلَّى قَالَ النَّبِيُّ صلى الله عليه وسلم ‏"‏ مَنْ سَرَّهُ أَنْ يَنْظُرَ إِلَى رَجُلٍ مِنْ أَهْلِ الْجَنَّةِ فَلْيَنْظُرْ إِلَى هَذَا ‏"‏‏.‏ حَدَّثَنَا مُسَدَّدٌ، عَنْ يَحْيَى، عَنْ أَبِي حَيَّانَ، قَالَ أَخْبَرَنِي أَبُو زُرْعَةَ، عَنِ النَّبِيِّ صلى الله عليه وسلم بِهَذَا‏.‏ """,
        name: 'আবূ হুরায়রা (রাঃ) থেকে বর্ণিতঃ',
        bookName: 'বুখারী'),
  ];
}

class GxHadith extends StatelessWidget {
  const GxHadith({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SliverList(
      delegate: SliverChildBuilderDelegate(
        (context, index) {
          final data = QMxHadith.hadith[index];

          return Padding(
            padding: const EdgeInsets.all(11.0),
            child: Column(
              children: [
                Text(data.textArabic),
                Text(data.textBangla),
              ],
            ),
          );
        },
        childCount:QMxHadith.hadith.length ,
      ),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (13 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by samithe7** [comment] 2022-04-14 12:00
I run it android  emulator . maybe  it only android problem  .

**Comment by samithe7** [comment] 2022-04-14 12:02
> flutter doctor -v
[✓] Flutter(Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.19044.1586], locale en-US)
    • Flutter version 2.10.4 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at C:\Users\samiu\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • Java binary at: C:\Users\samiu\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8139111\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Users\samiu\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\211.7628.21.2111.8139111
    • Flutter plugin version 65.2.2
    • Dart plugin version 211.7811
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at C:\Users\samiu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 100.0.4896.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 100.0.1185.36

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by samithe7** [comment] 2022-04-14 12:03
`ddd`

**Comment by samithe7** [comment] 2022-04-14 12:04
- [flutter doctor -v ]

**Comment by samithe7** [comment] 2022-04-14 18:31
i give padding  EdgeInsets.all(11.0)  , but arabic text  don't  give  11p  padding  right  side

**Comment by samithe7** [comment] 2022-04-14 18:37
![dd](https://user-images.githubusercontent.com/53804061/163455139-a8c5539a-869e-4f04-b76e-0bd2696edb32.jpg)

**Comment by maheshmnj** [comment] 2022-04-18 05:34
Thanks for the clarification @samithe7, I ran your code sample on Android, and I was able to reproduce the issue on stable channel but not on the master channel. So it looks like it was fixed recently 

Stable            |  master
:-------------------------:|:-------------------------:
![flutter_04](https://user-images.githubusercontent.com/31410839/163759696-494f277a-9a7e-4a36-ab58-5d7dfdfb08fe.png) | ![flutter_01](https://user-images.githubusercontent.com/31410839/163759750-2cb30a73-0015-4879-8f9d-f76f7e1f816a.png)

This fix is also available on the beta channel, So you can expect this to be fixed in the upcoming stable release. Closing as this is fixed in the new versions.

```
mahesh@Maheshs-MacBook-Air-M1 test_app % flutterb --version
Flutter 2.12.0-4.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5c931b769b (3 weeks ago) • 2022-03-29 10:49:29 -0500
Engine • revision 486f4a749e
Tools • Dart 2.17.0 (build 2.17.0-182.2.beta) • DevTools 2.11.1
```

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.10.4 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (13 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 535317A4-921C-488F-B234-C2CC6D4AE5A1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.548, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 2.13.0-0.0.pre.548 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3aba137efd (4 days ago), 2022-04-14 02:39:05 -0400
    • Engine revision 5b81baaef7
    • Dart version 2.18.0 (build 2.18.0-19.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.39.20220405

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:55555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos             • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome            • web-javascript • Google Chrome 100.0.4896.88

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Closed by maheshmnj** 2022-04-18 05:34 UTC
Labels: in triage
