### ISSUE TITLE
GestureDetector/InkWell onTap does not work in Stack

### ISSUE THREAD

**Issue by bennovw** [flutter/flutter#104519] opened 2022-05-24 16:58 UTC
Related to issue #64461, GestureDetector and InkWell stop working when Positioned outside the Stack's parent. Demo of the issue: [https://dartpad.dev/?id=a1cce36f59e2bcb8a53fb3f84a75ca7d](https://dartpad.dev/?id=a1cce36f59e2bcb8a53fb3f84a75ca7d)

Only the areas of the red and orange squares overlapping the green square (Stack's parent) are clickable. The desired behavior is for widgets in the Stack to be clickable no matter where they are positioned on the screen.

There's an (incorrect?) assumption that a child widget will always exist within the parent's boundaries when RenderBox.hitTest() runs. The Stack widget's children can be located outside of the parent and should always be hit tested to avoid this issue.

The issue is documented on StackOverflow ([link](https://stackoverflow.com/questions/51366761/in-flutter-how-can-a-positioned-widget-feel-taps-outside-of-its-parent-stack-ar)):

> This behavior occurs because the stack checks whether the pointer is inside its bounds before checking whether a child got hit:
> 
> Class: RenderBox (which RenderStack extends)
> 
>
> 
> ```
> bool hitTest(BoxHitTestResult result, { @required Offset position }) {
> 
>     ...
> 
>     if (_size.contains(position)) {
>       if (hitTestChildren(result, position: position) || hitTestSelf(position)) {
>         result.add(BoxHitTestEntry(this, position));
>         return true;
>       }
>     }
>     return false;
> }
> ```
> A workaround is deleting the
> 
> `if (_size.contains(position))`
> 

## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Click on a section of the red or yellow squares located outside the green square.

**Expected results:** 
OnTap is triggered when clicking on any part of the red or yellow squares, including areas outside of the green square.

**Actual results:**
OnTap is _only_ triggered when clicking on areas of the red and yellow squares overlapping the green square.

![2022-05-24 Stack OnPress test](https://user-images.githubusercontent.com/52413058/170103145-9f0e9680-a2cc-4956-a78a-ec9f8f3a038a.jpg)

<details>
<summary>Code sample</summary>

https://dartpad.dev/?id=a1cce36f59e2bcb8a53fb3f84a75ca7d
```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Stack Gesture Tests'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  var horizontalOffset = 150.0;
  var verticalOffset = 150.0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You tapped the red square this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Padding(
                  padding: const EdgeInsets.only(top: 50, bottom: 50, left: 100),
                  child: Container(
                    color: Colors.green,
                    width: 200,
                    height: 200,
                    child: Stack(
                      clipBehavior: Clip.none,
                      children: [
                        Positioned(
                          left: horizontalOffset,
                          top: verticalOffset,
                          child: GestureDetector(
                            onTap: () {
                              _incrementCounter();
                            },
                            child: Container(
                              color: Colors.red.withAlpha(200),
                              width: 100,
                              height: 100,
                              child: const Text('Gesture'),
                            ),
                          ),
                        ),
                        Positioned(
                            left: horizontalOffset,
                            bottom: verticalOffset,
                            child: Material(
                              color: Colors.transparent,
                              child: InkWell(
                                onTap: () {
                                  _incrementCounter();
                                },
                                child: Container(
                                  color: Colors.orange.withAlpha(200),
                                  width: 100,
                                  height: 100,
                                  child: const Text('InkWell'),
                                ),
                              ),
                            ))
                      ],
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(left: 100),
                  child: RotatedBox(
                    quarterTurns: 1,
                    child: ConstrainedBox(
                      constraints: const BoxConstraints(
                        maxWidth: 400,
                      ),
                      child: Slider(
                          value: verticalOffset,
                          min: 0,
                          max: 200,
                          label: 'Vertical Offset',
                          onChanged: (double newValue) {
                            setState(() {
                              verticalOffset = newValue;
                            });
                          }),
                    ),
                  ),
                ),
              ],
            ),
            ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 400),
              child: Slider(
                  value: horizontalOffset,
                  min: 0,
                  max: 200,
                  label: 'Horizontal Offset',
                  onChanged: (double newValue) {
                    setState(() {
                      horizontalOffset = newValue;
                    });
                  }),
            ),
          ],
        ),
      ),
    );
  }
}


```

</details>

<details>
  <summary>Logs</summary>

```
Analyzing testing...                                                    
No issues found! (ran in 1.1s)
```

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.0 at /opt/homebrew/Caskroom/flutter/2.10.4/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/benno/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-05-25 08:19
This issue is reproducible in both stable and master.

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Stack Gesture Tests'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  var horizontalOffset = 150.0;
  var verticalOffset = 150.0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You tapped the red square this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Expanded(
                  child: Padding(
                    padding:
                        const EdgeInsets.only(top: 50, bottom: 50, left: 100),
                    child: Container(
                      color: Colors.green,
                      width: 200,
                      height: 200,
                      child: Stack(
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: horizontalOffset,
                            top: verticalOffset,
                            child: GestureDetector(
                              onTap: () {
                                _incrementCounter();
                              },
                              child: Container(
                                color: Colors.red.withAlpha(200),
                                width: 100,
                                height: 100,
                                child: const Text('Gesture'),
                              ),
                            ),
                          ),
                          Positioned(
                            left: horizontalOffset,
                            bottom: verticalOffset,
                            child: Material(
                              color: Colors.transparent,
                              child: InkWell(
                                onTap: () {
                                  _incrementCounter();
                                },
                                child: Container(
                                  color: Colors.orange.withAlpha(200),
                                  width: 100,
                                  height: 100,
                                  child: const Text('InkWell'),
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(left: 100),
                  child: RotatedBox(
                    quarterTurns: 1,
                    child: ConstrainedBox(
                      constraints: const BoxConstraints(
                        maxWidth: 400,
                      ),
                      child: Slider(
                        value: verticalOffset,
                        min: 0,
                        max: 200,
                        label: 'Vertical Offset',
                        onChanged: (double newValue) {
                          setState(() {
                            verticalOffset = newValue;
                          });
                        },
                      ),
                    ),
                  ),
                ),
              ],
            ),
            ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 400),
              child: Slider(
                value: horizontalOffset,
                min: 0,
                max: 200,
                label: 'Horizontal Offset',
                onChanged: (double newValue) {
                  setState(() {
                    horizontalOffset = newValue;
                  });
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

<details><summary>Video</summary>

https://user-images.githubusercontent.com/50555895/170215489-7d64b646-23cc-41b5-a951-0379893343ef.mov

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.1 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (16 hours ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 16B8F156-111C-489F-A6E5-2D79142036B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Brave Browser 101.1.38.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.897, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.897 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 680a8192b0 (2 hours ago), 2022-05-24 21:23:09 -0700
    • Engine revision 7274f79325
    • Dart version 2.18.0 (build 2.18.0-149.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 16B8F156-111C-489F-A6E5-2D79142036B4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Brave Browser 101.1.38.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by exaby73** [comment] 2022-05-26 06:39
Would you consider that a viable solution to your problem?

**Comment by bennovw** [comment] 2022-05-26 09:31
No, unfortunately `OverlayEntry` is nothing more than a hack. It comes with significant drawbacks because it's difficult to implement, performs poorly, and chops the widget tree in half. 😔

**Comment by exaby73** [comment] 2022-05-26 11:13
Alright. Keeping the issue open for now

**Comment by LongCatIsLooong** [comment] 2022-05-26 16:38
I think this is a duplicate of https://github.com/flutter/flutter/issues/75747. This `if (_size.contains(position)) {` line drastically reduces the number of `RenderBox`es each pointer event has to perform hit test against.

I'm going to close this as a duplicate for now, feel free to reopen if #75747 doesn't fully capture the problem.

**Closed by LongCatIsLooong** 2022-05-26 16:38 UTC
Labels: framework, f: material design, f: gestures, has reproducible steps, found in release: 3.0, found in release: 3.1
