### ISSUE TITLE
In BorderRadius.only, the values of bottomLeft and bottomRight are switched

### ISSUE THREAD

**Issue by sravimohan** [flutter/flutter#47201] opened 2019-12-17 09:34 UTC
When setting border for a ChoiceChip, the values of bottomLeft and bottomRight are switched.

Issue Sample:
https://dartpad.dev/4ce468721cd5fb15def8defb7811db3b

**Comment by iapicca** [comment] 2019-12-17 12:29
Hi @sravimohan 
I can't access the dartpad you shared
`Error loading gist 4ce468721cd5fb15def8defb7811db3b.`
can you please try again or just paste the code sample;
thank you

**Comment by sravimohan** [comment] 2019-12-17 18:45
import 'package:flutter/material.dart';

final Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Container(
            child: Center(
          child: MyWidget(),
        )),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChoiceChip(
        shape: ContinuousRectangleBorder(
          borderRadius: BorderRadius.only(
              topLeft: Radius.circular(20.0),
              topRight: Radius.circular(0.0),
              bottomLeft: Radius.circular(20.0),
              bottomRight: Radius.circular(0.0)),
        ),
        label: Text('Hello World'),
        selected: true,
        onSelected: (bool selected) {});
  }
}

**Comment by sravimohan** [comment] 2019-12-17 18:45
> Hi @sravimohan
> I can't access the dartpad you shared
> `Error loading gist 4ce468721cd5fb15def8defb7811db3b.`
> can you please try again or just paste the code sample;
> thank you

Pasted the code above.

**Comment by jason-simmons** [comment] 2019-12-17 22:32
This should be fixed by https://github.com/flutter/flutter/commit/1160c8fd298f545ab50694eb71f7f204923a52fa

Try upgrading to a newer version of Flutter.

**Comment by TahaTesser** [comment] 2020-07-03 14:14
Not able to reproduce this issue 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

final Color darkBlue = Colors.yellow;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(scaffoldBackgroundColor: darkBlue),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Container(
            child: Center(
          child: MyWidget(),
        )),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChoiceChip(
        shape: ContinuousRectangleBorder(
          borderRadius: BorderRadius.only(
              topLeft: Radius.circular(20.0),
              topRight: Radius.circular(0.0),
              bottomLeft: Radius.circular(20.0),
              bottomRight: Radius.circular(0.0)),
        ),
        label: Text('Hello World'),
        selected: true,
        onSelected: (bool selected) {});
  }
}

``` 

</details> 

<details> 
<summary>stable flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (10 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (5 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS desktop • macos                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
``` 

</details> 

Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Closed by TahaTesser** 2020-07-03 14:14 UTC
Labels: f: material design, framework
