### ISSUE TITLE
Error during scrolling when using LazyBlock

### ISSUE THREAD

**Issue by alhaad** [flutter/flutter#3417] opened 2016-04-19 21:51 UTC
Everyone once in a while (1 in 100 runs), we see the following error.
Neither does it crash nor have any observable change in performance.
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[0419/142636:WARNING:vsync_scheduler.cc(217)] Compositor missed update deadline by 22855 us
The following NoSuchMethodError was thrown during performLayout():
The null object does not have a getter 'inMicroseconds'.

NoSuchMethodError: method not found: 'inMicroseconds'
Receiver: null
Arguments: []
The following RenderObject was being processed when the exception was fired:
  _RenderLazyBlock NEEDS-LAYOUT
This RenderObject had the following descendants (showing up to depth 5):
  RenderRepaintBoundary relayoutSubtreeRoot=up1
    RenderPadding relayoutSubtreeRoot=up2
      RenderSemanticsGestureHandler relayoutSubtreeRoot=up3
        RenderPointerListener relayoutSubtreeRoot=up4
          RenderSemanticsGestureHandler relayoutSubtreeRoot=up5
  RenderRepaintBoundary relayoutSubtreeRoot=up1
    RenderPadding relayoutSubtreeRoot=up2
      RenderSemanticsGestureHandler relayoutSubtreeRoot=up3
        RenderPointerListener relayoutSubtreeRoot=up4
          RenderSemanticsGestureHandler relayoutSubtreeRoot=up5
  RenderRepaintBoundary relayoutSubtreeRoot=up1
    RenderPadding relayoutSubtreeRoot=up2
      RenderSemanticsGestureHandler relayoutSubtreeRoot=up3
        RenderPointerListener relayoutSubtreeRoot=up4
          RenderSemanticsGestureHandler relayoutSubtreeRoot=up5
Stack trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ScrollableState.didUpdateScrollBehavior (package:flutter/src/widgets/scrollable.dart:393)
#3      _LazyBlockState._handleExtentsChanged.<anonymous closure> (package:flutter/src/widgets/lazy_block.dart:175)
#4      State.setState (package:flutter/src/widgets/framework.dart:419)
#5      _LazyBlockState._handleExtentsChanged (package:flutter/src/widgets/lazy_block.dart:174)
#6      _LazyBlockElement._layout (package:flutter/src/widgets/lazy_block.dart:652)
#7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1325)
#8      _RenderLazyBlock.performLayout (package:flutter/src/widgets/lazy_block.dart:376)
#9      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1123)
#10     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:727)
#11     BindingBase&Scheduler&Gesturer&Services&Renderer.beginFrame (package:flutter/src/rendering/binding.dart:89)
#12     WidgetFlutterBinding.beginFrame (package:flutter/src/widgets/binding.dart:103)
#13     BindingBase&Scheduler&Gesturer&Services&Renderer._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:83)
#14     BindingBase&Scheduler.invokeFrameCallback (package:flutter/src/scheduler/scheduler.dart:304)
#15     BindingBase&Scheduler.handleBeginFrame (package:flutter/src/scheduler/scheduler.dart:277)
#16     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/hooks.dart:48)
```

**Comment by Hixie** [comment] 2016-04-19 22:00
Does it happen if you rotate the screen after a fling? Or something like that?

**Comment by alhaad** [comment] 2016-04-19 22:01
No rotation involved. Just a lot of child views.

**Comment by Hixie** [comment] 2016-04-19 22:03
is this failing in manual testing or in automated testing?

**Comment by Hixie** [comment] 2016-04-19 22:03
is it failing in a flutter app on the outside of the child views or the inside?

**Comment by alhaad** [comment] 2016-04-19 22:07
Failing in manual testing.

In this particular case, there are 3 levels of child widget. It is happening the middle layer flx.

**Comment by Hixie** [comment] 2016-04-19 22:08
i'll try to clean up the code to make it less likely but without steps to reproduce it's very hard to guarantee that it's been fixed :-)

**Comment by alhaad** [comment] 2016-04-19 22:11
No worries, not blocking us in any way. Just wanted to put it on file :)
Thanks!

**Comment by abarth** [comment] 2016-04-20 16:45
Dupe of https://github.com/flutter/flutter/issues/3231 ?

**Comment by Hixie** [comment] 2016-04-20 18:02
This should be fixed now. Please don't hesitate to reopen if not.

**Closed by Hixie** 2016-04-20 18:02 UTC
