### ISSUE TITLE
[multicast_dns] SocketException: Failed to create datagram socket, the requested address is invalid

### ISSUE THREAD

**Issue by liangajianNan** [flutter/flutter#94843] opened 2021-12-08 06:32 UTC
我用multicast_dns: ^0.3.1 运行在Windows 出错，运行在Android是好的
final MDnsClient client = MDnsClient(rawDatagramSocketFactory: factory);
    // Start the client with default options.
    await client.start();
start()报错 OS Error: 在其上下文中，该请求的地址无效。

_translated using google translate_

>I use multicast_dns: ^0.3.1 to run on Windows, but it’s okay to run on Android.
final MDnsClient client = MDnsClient(rawDatagramSocketFactory: factory);
// Start the client with default options.
await client.start();
start() reports an error OS Error: In its context, the requested address is invalid.

**Comment by maheshmnj** [comment] 2021-12-08 08:49
HI @liangajianNan 

can you please provide your `flutter doctor -v` and `flutter run --verbose`

Thank you

**Comment by liangajianNan** [comment] 2021-12-15 07:18
flutter doctor -v and flutter run --verbose 是好的  因为在Android端是可以的，现在问题出现是Windows端

**Comment by liangajianNan** [comment] 2021-12-15 07:19
@maheshmnj

**Comment by maheshmnj** [comment] 2021-12-15 08:24
@liangajianNan, I would need your `flutter doctor -v`  to know what version of flutter are you using and on which host platform. It would be great if you can also share the complete error logs that your are seeing.

Thanks

**Comment by liangajianNan** [comment] 2021-12-16 05:59
@maheshmnj 

[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1415], locale zh-CN)
    • Flutter version 2.5.0 at D:\fluttersdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at D:\AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Users\ECOM\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.0)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • BAH3 W59 (mobile) • 5RXBB21429209059 • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.1415]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 96.0.1054.43

• No issues found!
这是错误日志
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: 在其上下文中，该请求的地址无效。

, errno = 10049), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:981:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:131:40)
<asynchronous suspension>

**Comment by maheshmnj** [comment] 2021-12-16 06:41
Thanks for the info.

**Comment by stuartmorgan** [comment] 2022-01-05 20:00
Duplicate of https://github.com/flutter/flutter/issues/53477

**Closed by stuartmorgan** 2022-01-05 20:00 UTC
Labels: p: first party, package, p: multicast_dns, passed first triage
