### ISSUE TITLE
CheckboxListTile not work with Provider State Management

### ISSUE THREAD

**Issue by imansejati** [flutter/flutter#95954] opened 2021-12-30 07:19 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Use Widget CheckboxListTile is work properly using usual changestate
3. The Problem! Cannot tick the CheckboxListTile when using Provider State Management. Using the same way is work properly on Switch Widget and Checkbox Widget.

<details>
<summary>Code sample</summary>

`import 'package:flutter/material.dart';

import 'package:provider/provider.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<CobaProvider>(
      create: (_) => CobaProvider(),
      child: MaterialApp(
        home: Scaffold(
          appBar: AppBar(
            title: Text('percobaan'),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Consumer<CobaProvider>(
                  builder: (context, cobaProvider, _) => CheckboxListTile(
                      title: Text('Percobaan'),
                      value: cobaProvider.value,
                      onChanged: (newValue) {
                        cobaProvider.value;
                        newValue;
                      }),
                ),
                Consumer<CobaProvider>(
                    builder: (context, cobaProvider, _) => Switch(
                        value: cobaProvider.value,
                        onChanged: (newValue) {
                          cobaProvider.value = newValue;
                        })),
                Consumer<CobaProvider>(
                    builder: (context, cobaProvider, _) => Checkbox(
                        value: cobaProvider.value,
                        onChanged: (newValue) {
                          cobaProvider.value = newValue!;
                        })),
              ],
            ),
          ), // This trailing comma makes auto-formatting nicer for build methods.
        ),
      ),
    );
  }
}

class CobaProvider extends ChangeNotifier {
  bool _value = true;

  bool get value => _value;
  set value(bool v) {
    _value = v;
    notifyListeners();
  }
}`

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

`[✓] Flutter (Channel master, 2.6.0-12.0.pre.718, on Ubuntu 20.04.2 LTS 5.11.0-43-generic, locale en_US.UTF-8)
    • Flutter version 2.6.0-12.0.pre.718 at 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3d889b4e4b (7 weeks ago), 2021-11-13 23:46:03 +0600
    • Engine revision 140bd9399e
    • Dart version 2.16.0 (build 2.16.0-10.0.dev)
    • DevTools version 2.8.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /home/iman/Android/Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /home/iman/Android/Sdk
    • Java binary at: /snap/android-studio/115/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /snap/android-studio/115/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)'
</details>

**Comment by mamuseferha** [comment] 2021-12-30 07:23
Hi @imansejati 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/rrousselGit/provider/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by mamuseferha** 2021-12-30 07:23 UTC
Labels: in triage
