### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by heinminlatt611517** [flutter/flutter#145735] opened 2024-03-26 03:58 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: No such file or directory, errno = 2
```
#0      _Directory.createSync (dart:io/directory_impl.dart:124:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:20:16)
#2      ErrorHandlingDirectory.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:426:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:425:12)
#5      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:954:19)
<asynchronous suspension>
#6      CachedArtifact.update (package:flutter_tools/src/cache.dart:848:5)
<asynchronous suspension>
#7      Cache.updateAll (package:flutter_tools/src/cache.dart:715:9)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1699:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.19.4, on macOS 14.4.1 23E224 darwin-arm64, locale en-TH)
    [32m•[39m Flutter version 3.19.4 on channel stable at /Users/development/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 68b

**Comment by danagbemava-nc** [comment] 2024-03-26 08:35
Closing this as a duplicate of https://github.com/flutter/flutter/issues/137894

**Closed by danagbemava-nc** 2024-03-26 08:35 UTC
Labels: in triage
