### ISSUE TITLE
Connecting an IOS device [ERROR: Could not connect to lockdownd, error code -17]

### ISSUE THREAD

**Issue by nerder** [flutter/flutter#49553] opened 2020-01-26 11:50 UTC
## Steps to Reproduce

- Open Intellij
- plug a not yet configured ios device (Iphone8 used in my tests)
 
## Version info

```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-GB)
    • Flutter version 1.12.13+hotfix.6 at /Users/nerder/flutter
    • Framework revision 18cd7a3601 (7 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nerder/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.6015.9

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available
```

NOTE: when running flutter doctor with the same device connected:

```
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: ideviceinfo returned an error:
      ERROR: Could not connect to lockdownd, error code -17

    • #0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:226:9)
      <asynchronous suspension>
      flutter/flutter-intellij#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:190:55)
      <asynchronous suspension>
      flutter/flutter-intellij#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:115:57)
      flutter/flutter-intellij#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      flutter/flutter-intellij#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      flutter/flutter-intellij#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:851:54)
      flutter/flutter-intellij#6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      flutter/flutter-intellij#7      _rootRun (dart:async/zone.dart:1126:13)
      flutter/flutter-intellij#8      _CustomZone.run (dart:async/zone.dart:1023:19)
      flutter/flutter-intellij#9      _runZoned (dart:async/zone.dart:1518:10)
      flutter/flutter-intellij#10     runZoned (dart:async/zone.dart:1502:12)
      flutter/flutter-intellij#11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      flutter/flutter-intellij#12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      flutter/flutter-intellij#13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      flutter/flutter-intellij#14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      flutter/flutter-intellij#15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      flutter/flutter-intellij#16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      flutter/flutter-intellij#17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      flutter/flutter-intellij#18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
      flutter/flutter-intellij#19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
      flutter/flutter-intellij#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
      flutter/flutter-intellij#21     _rootRunUnary (dart:async/zone.dart:1134:38)
      flutter/flutter-intellij#22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      flutter/flutter-intellij#23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      flutter/flutter-intellij#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
      flutter/flutter-intellij#25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      flutter/flutter-intellij#26     Future._completeWithValue (dart:async/future_impl.dart:524:5)
      flutter/flutter-intellij#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
      flutter/flutter-intellij#28     _rootRun (dart:async/zone.dart:1126:13)
      flutter/flutter-intellij#29     _CustomZone.run (dart:async/zone.dart:1023:19)
      flutter/flutter-intellij#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      flutter/flutter-intellij#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
      flutter/flutter-intellij#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      flutter/flutter-intellij#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      flutter/flutter-intellij#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      flutter/flutter-intellij#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

So maybe the issue should be opened in flutter repo as well.

**Comment by devoncarew** [comment] 2020-01-27 16:41
Thanks for the report! Moving to the flutter/flutter repo.

**Comment by VladyslavBondarenko** [comment] 2020-01-27 17:12
Hi @nerder 
Does https://github.com/flutter/flutter/issues/24600#issuecomment-496414645 help you?

Related to https://github.com/flutter/flutter/issues/44898

**Comment by nerder** [comment] 2020-01-27 17:19
Hey @VladyslavBondarenko think this is related I wonder if this is not a regression, cause from what I understand this has been fixed some time ago by https://github.com/flutter/flutter/pull/38629

In fact, I ask if this was the case here: https://github.com/flutter/flutter/issues/36789#issuecomment-578494842

I don't know what's the best approach to track this, feel free to close this one if you prefer to track the regression in the original one.

**Comment by jmagman** [comment] 2020-01-27 19:54
https://github.com/flutter/flutter/pull/38629 handled error -19 and -21, not -17.

Duplicate of https://github.com/flutter/flutter/issues/49375.

**Closed by jmagman** 2020-01-27 19:54 UTC
Labels: severe: crash, tool, ⌘‬ platform-mac, ⌺‬ platform-ios
