### ISSUE TITLE
Odd Gridview scroll behavior when updating the content count

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter#16680] opened 2018-04-17 22:51 UTC
If you update the number of elements in a Gridview, some very odd scroll behavior can be observed.  For example if you have a lot of items, scroll to the end, then reduce the number of items, the gridview will go blank and then scroll to the rest of the contents.  

I'm building an app where switching between gridview sizes like this will be common, and it's a pretty jarring experience.  Is there a proper way for me to handle this or some work around?  I would prefer if it jumped directly to the end of the old gridview size, or allowed me to specify where the scroll position should be

You can see the behavior in this video here:
https://www.youtube.com/watch?v=X75bajt9JzQ

You can reproduce this for yourself with this build method: 
```dart
class _MyHomePageState extends State<MyHomePage> {
  int _elementCount = 500;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text(widget.title),
      ),
      body: new Center(
        child: new Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            new Expanded(child: new Container()),
            new MaterialButton(
              onPressed: () {
                setState(() {
                  _elementCount = 5;
                });
              },
              color: Colors.green,
              child: new Text("5 elements"),
            ),
            new MaterialButton(
              onPressed: () {
                setState(() {
                  _elementCount = 30;
                });
              },
              color: Colors.green,
              child: new Text("30 elements"),
            ),
            new MaterialButton(
              onPressed: () {
                setState(() {
                  _elementCount = 500;
                });
              },
              color: Colors.green,
              child: new Text("500 elements"),
            ),
            new Container(
              height: 240.0,
              padding: const EdgeInsets.symmetric(vertical: 15.0),
              color: const Color(0xFFEEEEEE),
              child: new GridView.count(
                crossAxisCount: 3,
                scrollDirection: Axis.horizontal,
                controller: new ScrollController(
                  initialScrollOffset: 0.0,
                  keepScrollOffset: false,
                ),
                children: new List<Widget>.generate(
                  _elementCount,
                  (index) {
                    String currentString = '$index';
                    return new Material(
                      color: const Color(0xFFEEEEEE),
                      child: new Stack(
                        children: <Widget>[
                          new Center(
                            child: new Text(
                              currentString,
                              style: new TextStyle(
                                fontSize: 24.0,
                              ),
                            ),
                          ),
                        ],
                      ),
                    );
                  },
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

## Steps to Reproduce
- `flutter create`
- replace `_MyHomePageState` with the above one

## Logs

No interesting output with `flutter run`

### Flutter Analyze
```
No issues found!
Ran in 5.9s
```

## Flutter Doctor

```
[✓] Flutter (Channel master, v0.3.1-pre.15, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 0.3.1-pre.15 at /Users/KG/Developer/Flutter/flutter
    • Framework revision f049f436c8 (25 hours ago), 2018-04-16 14:17:55 -0700
    • Engine revision 76cb311d9c
    • Dart version 2.0.0-dev.47.0.flutter-f76dad0adc

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.2
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.10.0
```

**Comment by zoechi** [comment] 2018-07-16 15:39
Sorry for the late response.
Is this still an issue?

**Comment by KevinTheGray** [comment] 2018-07-16 18:56
Yes, with my current version of flutter it's still an issue.  It is the same effect that can be seen in the youtube video posted above.

Current `flutter doctor`:
```
[✓] Flutter (Channel master, v0.5.8-pre.53, on Mac OS X 10.13.5 17F77, locale en-US)
    • Flutter version 0.5.8-pre.53 at /Users/KG/Developer/Flutter/flutter
    • Framework revision 6a8f904104 (5 hours ago), 2018-07-16 16:21:20 +0200
    • Engine revision c5a63d28bf
    • Dart version 2.0.0-dev.67.0.flutter-84ca27a09e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/KG/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /Users/KG/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 21.2.2
    • Dart plugin version 172.4343.25

[!] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

**Comment by VladyslavBondarenko** [comment] 2020-03-27 16:30
Reproduced. Flutter master v1.16.3-pre.56.

<details>
 <summary>gif</summary>

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/17024977/77777688-9657f080-7058-11ea-8a85-c5ca2ab28150.gif)

</details>

**Comment by VladyslavBondarenko** [comment] 2020-07-27 14:03
Seems to be fixed. Tried with Android 9 (API 28), master 1.21.0-6.0.pre.38.

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.38, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.38 at /Users/nevercode/dev/flutter
    • Framework revision 8e0eee9008 (5 hours ago), 2020-07-26 23:38:01 -0700
    • Engine revision 626244a72c
    • Dart version 2.9.0 (build 2.9.0-21.0.dev a3815b6590)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • Redmi Note 7 (mobile)       • 6345c469                                 • android-arm64  • Android 9 (API 28)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 13.6
    • macOS (desktop)             • macos                                    • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)            • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/17024977/88550930-ebb60580-d02a-11ea-8f41-2754e6e73c55.gif)

Closing. If you disagree please write in comments and I'll reopen

**Closed by VladyslavBondarenko** 2020-07-27 14:03 UTC
Labels: P5, f: scrolling, framework, has reproducible steps
