### ISSUE TITLE
"Add a bottom app bar to the floating action button motion demo" regressed missed_frame_build_budget_count

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#16377] opened 2018-04-09 17:49 UTC
"Add a bottom app bar to the floating action button motion demo" (https://github.com/flutter/flutter/pull/16196) regressed `missed_frame_build_budget_count`.

Please investigate the cause and resolve this issue. Thanks!

(Splitting this off from https://github.com/flutter/flutter/issues/16234)

**Comment by DaveShuckerow** [comment] 2018-04-10 00:26
I ran an experiment to open demo pages 10x after starting the app and recording the GPU ms/frame after doing this.  This was done in profile mode with the performance overlay turned on using a Nexus 6p.

Some results:
as a control, the bottom navigation demo got 17.5 ms/frame

The bab demo as-is got 36.6 ms/frame
The bab demo with bottom bar and fab removed got 24.3 ms/frame
The bab demo with just the bottom bar removed got 25.3 ms/frame
The bab demo with the bab in but its AnimatedCrossFade child removed got 25.8 ms/frame

It appears that the AnimatedCrossFade widget in the bottom app bar is what's causing the slowdown in this demo.

The simple fix to this problem is to just build one set of menu icons and not change it.  I produced that as part of my testing and it's available at #16389

The full fix would involve making the AnimatedCrossFade faster when it's rebuilding but not animating.

**Comment by Hixie** [comment] 2018-04-10 05:47
Wow, great research, thanks!

What on earth is AnimatedCrossFade doing that's so expensive?

(25ms is still a lot. 17ms is a lot. Ideally we'd be below 8ms, so that we get 60Hz with minimal latency, but at least below 16ms, so we get 60Hz with only one frame extra latency.)

**Comment by DaveShuckerow** [comment] 2018-04-10 18:52
From looking at the AnimatedCrossFade source, it looks like it is greedily creating multiple AnimationControllers and setting them up to run every time it's created.  Both `build` and `initState` on it are very busy methods.  The perf tests involve creating and destroying the widget's state very quickly, so we hit the worst case performance.

I think if the crossfade widget were to lazily initialize its internal animations, it would perform better.

**Comment by Hixie** [comment] 2018-04-11 22:00
Reopening so that we don't lose the information you discovered above — the point of the benchmark is to find this kind of problem, not to just paper over them by writing the gallery to work around these issues.

**Comment by DaveShuckerow** [comment] 2018-04-12 22:02
Unassigning this because I have other work to do and want to leave the cookie untouched.

**Comment by Hixie** [comment] 2018-04-17 18:53
Looks like #16389 didn't actually fix this regression.

**Comment by liyuqian** [comment] 2019-04-22 22:18
Close this as this is too old and we're no longer tracking missed_frame_build_budget_count for our performance benchmarks. (Increasing missed_frame_build_budget_count could actually mean an improvement instead of a regression: https://github.com/flutter/flutter/issues/18727.)

**Closed by liyuqian** 2019-04-22 22:18 UTC
Labels: severe: performance, severe: regression, team, team: gallery
