### ISSUE TITLE
assert when passing width: double.infinite to an AnimatedContainer

### ISSUE THREAD

**Issue by renanyoy** [flutter/flutter#40820] opened 2019-09-19 05:28 UTC
## Steps to Reproduce
```
Container(
      child: AnimatedContainer(
        decoration: BoxDecoration(
            color: Skin.skin.colors.full,
            borderRadius: BorderRadius.circular(100)),
        duration: Duration(milliseconds: 300),
        curve: Curves.fastOutSlowIn,
        width: _isButton ? 56 : double.infinity,
        child: Stack(children: <Widget>[
          FloatingActionButton(backgroundColor: Colors.transparent, elevation: 0, child: Icon(Icons.search), onPressed: _switchState,)
        ]),
      ),
    );
```

1. ...
2. ...
3. ...

## Logs

```
[38;5;248m════════ Exception Caught By widgets library ═══════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown building AnimatedContainer(duration: 300ms, bg: BoxDecoration(color: Color(0xff028aff), borderRadius: BorderRadius.circular(100.0)), BoxConstraints(w=Infinity, 0.0<=h<=Infinity), dirty, state: _AnimatedContainerState#c0910(ticker active, bg: DecorationTween(BoxDecoration(color: Color(0xff028aff), borderRadius: BorderRadius.circular(100.0)) → BoxDecoration(color: Color(0xff028aff), borderRadius: BorderRadius.circular(100.0))), BoxConstraintsTween(BoxConstraints(w=56.0, 0.0<=h<=Infinity) → BoxConstraints(w=Infinity, 0.0<=h<=Infinity)))):[39;49m
[38;5;244mCannot interpolate between finite constraints and unbounded constraints.
'package:flutter/src/rendering/box.dart':
Failed assertion: line 463 pos 12: '(a.minWidth.isFinite && b.minWidth.isFinite) || (a.minWidth == double.infinity && b.minWidth == double.infinity)'
[39;49m

[38;5;248mEither the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
[39;49m

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#2      BoxConstraints.lerp[39;49m
[38;5;244m#3      BoxConstraintsTween.lerp[39;49m
[38;5;244m#4      Tween.transform[39;49m
[38;5;244m#5      Animatable.evaluate[39;49m
[38;5;244m#6      _AnimatedContainerState.build[39;49m
[38;5;244m...[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
```

```
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-FR)
    • Flutter version 1.7.8+hotfix.4 at /Users/renanyoy/code/sdk/flutter
    • Framework revision 20e59316b8 (9 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/renanyoy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • MI 6        • ee719fb4                             • android-arm64 • Android 9 (API 28)
    • Renaniphone • 00008020-000640992209002E            • ios           • iOS 12.4.1
    • iPhone Xʀ   • 690C736A-7C7A-49EC-BFB7-846352A9A99C • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by janmoppel** [comment] 2019-09-19 06:17
Hello @renanyoy !

Thank you for posting an issue.
This question seems to be a good question for the StackOverflow. Flutter has a very active and helpful community there, so feel free to post it there too.

Also, it would be very helpful if you could create a self-contained repository with provided code. So that your issue could be easily reproduced.

Thank you.

**Comment by janmoppel** [comment] 2019-11-12 11:01
Hello @renanyoy !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.

**Closed by janmoppel** 2019-11-12 11:01 UTC
Labels: a: animation, a: error message, d: stackoverflow, documentation, framework, waiting for customer response
