### ISSUE TITLE
Black screen when run in release mode

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter#16182] opened 2018-04-03 13:03 UTC
## Steps to Reproduce

```
(dart2) $ flutter run --release
Initializing gradle...                                       0.8s
Resolving dependencies...                                    1.5s
Launching lib/main.dart on Pixel XL in release mode...
Running 'gradlew assembleRelease'...                             
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
compiler message: file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/timeago.dart/lib/src/i18/messages_all.dart:20:24: Error: The top level function has type '() → dynamic' that isn't of expected type '() → dart.async::Fute<dynamic>'.
compiler message: Change the type of the function or the context in which it is used.
compiler message:   'en_short': en_short.loadLibrary,
compiler message:                        ^
compiler message: file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/timeago.dart/lib/src/i18/messages_all.dart:21:12: Error: The top level function has type '() → dynamic' that isn't of expected type '() → dart.async::Fute<dynamic>'.
compiler message: Change the type of the function or the context in which it is used.
compiler message:   'es': es.loadLibrary,
compiler message:            ^
compiler message: file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/timeago.dart/lib/src/i18/messages_all.dart:22:24: Error: The top level function has type '() → dynamic' that isn't of expected type '() → dart.async::Fute<dynamic>'.
compiler message: Change the type of the function or the context in which it is used.
compiler message:   'es_short': es_short.loadLibrary,
compiler message:                        ^
compiler message: file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/timeago.dart/lib/src/i18/messages_all.dart:23:12: Error: The top level function has type '() → dynamic' that isn't of expected type '() → dart.async::Fute<dynamic>'.
compiler message: Change the type of the function or the context in which it is used.
compiler message:   'fr': fr.loadLibrary,
compiler message:            ^
compiler message: file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/timeago.dart/lib/src/i18/messages_all.dart:24:12: Error: The top level function has type '() → dynamic' that isn't of expected type '() → dart.async::Fute<dynamic>'.
compiler message: Change the type of the function or the context in which it is used.
compiler message:   'ja': ja.loadLibrary,
compiler message:            ^
compiler message: file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/timeago.dart/lib/src/i18/messages_all.dart:25:18: Error: The top level function has type '() → dynamic' that isn't of expected type '() → dart.async::Fute<dynamic>'.
compiler message: Change the type of the function or the context in which it is used.
compiler message:   'zh_CN': zh_cn.loadLibrary,
compiler message:                  ^
compiler message: file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/timeago.dart/lib/src/i18/messages_all.dart:26:12: Error: The top level function has type '() → dynamic' that isn't of expected type '() → dart.async::Fute<dynamic>'.
compiler message: Change the type of the function or the context in which it is used.
compiler message:   'zh': zh.loadLibrary
compiler message:            ^
Built build/app/outputs/apk/release/app-release.apk (14.5MB).
Installing build/app/outputs/apk/app.apk...                 10.9s

To repeat this help message, press "h". To quit, press "q".
I/FlutterActivityDelegate(17171): onResume setting current activity to this
```

The intl errors are reported in https://github.com/dart-lang/sdk/issues/32604, but they don't cause issues in debug mode

## Logs

Run your application with `flutter run` and attach all the log output.

Run `flutter analyze` and attach any output of that command also.

## Flutter Doctor

```
(dart2) $ flutter doctor -v
[✓] Flutter (Channel dev, v0.2.2-pre.7, on Mac OS X 10.13.3 17D102, locale en-AT)
    • Flutter version 0.2.2-pre.7 at /Users/zoechi/flutter/flutter
    • Framework revision c0d1eb7513 (2 hours ago), 2018-04-03 12:52:53 +0200
    • Engine revision c903c217a1
    • Dart version 2.0.0-dev.43.0.flutter-52afcba357

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /usr/local/opt/android-sdk
    • Android NDK at /usr/local/opt/android-sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = /usr/local/opt/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] Connected devices (1 available)
    • Pixel XL • HT69V0203649 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by zoechi** [comment] 2018-04-06 07:59
This is the output of `adb logcat`

```
04-06 09:57:05.264  1406  1406 D HeadsetPhoneState: sendDeviceStateChanged. mService=1 mIsSimStateLoaded=true mSignal=4 mRoam=0 mBatteryCharge=5
04-06 09:57:16.022   881  1594 I ActivityManager: Force stopping com.lookatyou.lookatmybaby appid=10377 user=0: from pid 5444
04-06 09:57:16.022   881  1594 I ActivityManager: Killing 5392:com.lookatyou.lookatmybaby/u0a377 (adj 0): stop com.lookatyou.lookatmybaby
04-06 09:57:16.025   881   928 W zygote64: kill(-5392, 9) failed: No such process
04-06 09:57:16.030   881  1594 W ActivityManager: Force removing ActivityRecord{481909e u0 com.lookatyou.lookatmybaby/.MainActivity t8043}: app died, no saved state
04-06 09:57:16.039   881  1594 I WindowManager: Failed to capture screenshot of Token{d6ee77f ActivityRecord{481909e u0 com.lookatyou.lookatmybaby/.MainActivity t8043 f}} appWin=Window{cf69db9 u0 com.lookatyou.lookatmybaby/com.lookatyou.lookatmybaby.MainActivity} drawState=4
04-06 09:57:16.107   881   947 W ActivityManager: setHasOverlayUi called on unknown pid: 5392
04-06 09:57:16.065   881   928 I chatty  : uid=1000(system) ActivityManager identical 1 line
04-06 09:57:16.107   881   928 W zygote64: kill(-5392, 9) failed: No such process
04-06 09:57:16.107   881   928 I zygote64: Successfully killed process cgroup uid 10377 pid 5392 in 82ms
04-06 09:57:16.115  7159  5446 V FA      : Connecting to remote service
04-06 09:57:16.118  1605  1605 D CarrierSvcBindHelper: No carrier app for: 0
04-06 09:57:16.118  7159  5446 V FA      : Activity resumed, time: 2516462872
04-06 09:57:16.128  7159  7159 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
04-06 09:57:16.128  7159  7159 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
04-06 09:57:16.139  2217  2217 D RegisteredNfcFServicesCache: Service unchanged, not updating
04-06 09:57:16.179  7159  7159 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
04-06 09:57:16.180  7159  7159 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
04-06 09:57:16.219  7159  5446 D FA      : Connected to remote service
04-06 09:57:16.219  7159  5446 V FA      : Processing queued up service tasks: 1
04-06 09:57:16.219  2165  2165 I HK/LatinKbdBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{b75d679 V.ED..... ......ID 0,0-1440,675 #7f07000a app:id/LatinkeyboardBaseView}
04-06 09:57:16.388  5448  5448 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
04-06 09:57:16.509  5448  5448 I app_process: The ClassLoaderContext is a special shared library.
04-06 09:57:16.550  5448  5448 D AndroidRuntime: Calling main entry com.android.commands.pm.Pm
04-06 09:57:16.563  5448  5458 W MessageQueue: Handler (android.os.Handler) {24066d3} sending message to a Handler on a dead thread
04-06 09:57:16.563  5448  5458 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {24066d3} sending message to a Handler on a dead thread
04-06 09:57:16.563  5448  5458 W MessageQueue:  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
04-06 09:57:16.563  5448  5458 W MessageQueue:  at android.os.Handler.enqueueMessage(Handler.java:662)
04-06 09:57:16.563  5448  5458 W MessageQueue:  at android.os.Handler.sendMessageAtTime(Handler.java:631)
04-06 09:57:16.563  5448  5458 W MessageQueue:  at android.os.Handler.sendMessageDelayed(Handler.java:601)
04-06 09:57:16.563  5448  5458 W MessageQueue:  at android.os.Handler.post(Handler.java:357)
04-06 09:57:16.563  5448  5458 W MessageQueue:  at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
04-06 09:57:16.563  5448  5458 W MessageQueue:  at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
04-06 09:57:16.563  5448  5458 W MessageQueue:  at android.os.Binder.execTransact(Binder.java:697)
04-06 09:57:16.563  5448  5448 I app_process: System.exit called, status: 0
04-06 09:57:16.563  5448  5448 I AndroidRuntime: VM exiting with result code 0.
04-06 09:57:16.716   881  1594 I ActivityManager: START u0 {act=android.intent.action.RUN flg=0x30000000 cmp=com.lookatyou.lookatmybaby/.MainActivity (has extras)} from uid 2000
04-06 09:57:16.724   693   693 D QCOM PowerHAL: LAUNCH HINT: ON
04-06 09:57:16.727   693   693 D QCOM PowerHAL: Activity launch hint handled
04-06 09:57:16.729  7159  5446 V FA      : Screen exposed for less than 1000 ms. Event not sent. time: 615
04-06 09:57:16.735  7159  5446 V FA      : Activity paused, time: 2516463486
04-06 09:57:16.747   881  4728 I ActivityManager: Start proc 5468:com.lookatyou.lookatmybaby/u0a377 for activity com.lookatyou.lookatmybaby/.MainActivity
04-06 09:57:16.817  5468  5468 W zygote64: Unsupported class loader
04-06 09:57:16.819  5468  5468 W zygote64: Skipping duplicate class check due to unsupported classloader
04-06 09:57:16.821  5468  5468 W DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
04-06 09:57:16.823  5468  5468 W DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
04-06 09:57:16.825  5468  5468 I BiChannelGoogleApi: [FirebaseAuth: ] No Fallback module; NOT setting up for lazy initialization
04-06 09:57:16.828  5468  5484 W DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
04-06 09:57:16.839  5468  5484 I FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
04-06 09:57:16.839  5468  5484 I FirebaseAuth: [FirebaseAuth:] Preparing to create service connection to gms implementation
04-06 09:57:16.839  5468  5468 D FirebaseAuth: Notifying id token listeners about user ( n6spbhq9HdV6CfSzfUlsJSzeyoE3 ).
04-06 09:57:16.849  5468  5468 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
04-06 09:57:16.856  5468  5468 V FA      : Cancelling job. JobID: -632962466
04-06 09:57:16.858  5468  5468 V FA      : Registered activity lifecycle callback
04-06 09:57:16.859  5468  5468 I FirebaseInitProvider: FirebaseApp initialization successful
04-06 09:57:16.869  5468  5488 V FA      : Collection enabled
04-06 09:57:16.870  5468  5488 V FA      : App package, google app id: com.lookatyou.lookatmybaby, 1:757882787177:android:1da792a9eecd27ec
04-06 09:57:16.872  5468  5488 I FA      : App measurement is starting up, version: 11910
04-06 09:57:16.876  5468  5488 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
04-06 09:57:16.876  5468  5488 I FA      : To enable faster debug mode event logging run:
04-06 09:57:16.876  5468  5488 I FA      :   adb shell setprop debug.firebase.analytics.app com.lookatyou.lookatmybaby
04-06 09:57:16.877  5468  5488 D FA      : Debug-level message logging enabled
04-06 09:57:16.886  5468  5468 V FA      : onActivityCreated
04-06 09:57:16.893  5468  5488 V FA      : Connecting to remote service
04-06 09:57:16.896  5468  5468 I Adreno  : QUALCOMM build                   : 2941438, I916dfac403
04-06 09:57:16.896  5468  5468 I Adreno  : Build Date                       : 10/03/17
04-06 09:57:16.896  5468  5468 I Adreno  : OpenGL ES Shader Compiler Version: EV031.21.02.00
04-06 09:57:16.896  5468  5468 I Adreno  : Local Branch                     : O18A
04-06 09:57:16.896  5468  5468 I Adreno  : Remote Branch                    : 
04-06 09:57:16.896  5468  5468 I Adreno  : Remote Branch                    : 
04-06 09:57:16.896  5468  5468 I Adreno  : Reconstruct Branch               : 
04-06 09:57:16.899  5468  5468 I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
04-06 09:57:16.903  5468  5488 V FA      : Connection attempt already in progress
04-06 09:57:16.904  5468  5468 I zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
04-06 09:57:16.916  5468  5468 D MainActivity: onCreate: Was called!
04-06 09:57:16.939  5468  5468 I FlutterActivityDelegate: onResume setting current activity to this
04-06 09:57:16.944  5468  5488 V FA      : Connection attempt already in progress
04-06 09:57:16.947  5468  5488 V FA      : Activity resumed, time: 2516463696
04-06 09:57:16.950  5468  5488 I FA      : Tag Manager is not found and thus will not be used
04-06 09:57:16.952  5468  5498 D OpenGLRenderer: HWUI GL Pipeline
04-06 09:57:16.955  5468  5488 D FA      : Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-3332172919203401071}]
04-06 09:57:16.964  5468  5468 D FirebaseApp: Notifying auth state listeners.
04-06 09:57:16.965  5468  5468 D FirebaseApp: Notified 0 auth state listeners.
04-06 09:57:16.991  5468  5498 I OpenGLRenderer: Initialized EGL, version 1.4
04-06 09:57:16.991  5468  5498 D OpenGLRenderer: Swap behavior 2
04-06 09:57:17.002  5468  5488 V FA      : Connection attempt already in progress
04-06 09:57:17.051   881   947 I ActivityManager: Displayed com.lookatyou.lookatmybaby/.MainActivity: +311ms
04-06 09:57:17.054  5468  5488 D FA      : Connected to remote service
04-06 09:57:17.054  5468  5488 V FA      : Processing queued up service tasks: 4
04-06 09:57:17.067  2165  2165 I HK/LatinKbdBaseView: closing org.pocketworkstation.pckeyboard.LatinKeyboardView{b75d679 V.ED..... ......ID 0,0-1440,675 #7f07000a app:id/LatinkeyboardBaseView}
04-06 09:57:17.076   693   693 D QCOM PowerHAL: LAUNCH HINT: OFF
04-06 09:57:17.669   881  3883 I OpenGLRenderer: Initialized EGL, version 1.4
04-06 09:57:17.669   881  3883 D OpenGLRenderer: Swap behavior 2
04-06 09:57:17.956   881   902 I zygote64: NativeAlloc concurrent copying GC freed 36101(2007KB) AllocSpace objects, 12(496KB) LOS objects, 40% free, 35MB/59MB, paused 106us total 200.963ms
04-06 09:57:21.736  7159  5446 V FA      : Inactivity, disconnecting from the service
04-06 09:57:22.176  5468  5488 V FA      : Inactivity, disconnecting from the service
04-06 09:57:25.736  1406  1406 D HeadsetPhoneState: sendDeviceStateChanged. mService=1 mIsSimStateLoaded=true mSignal=3 mRoam=0 mBatteryCharge=5
04-06 09:57:36.515   881  1368 D RecurrenceRule: Resolving using anchor 2018-04-06T09:57:36.514+02:00[Europe/Vienna]
04-06 09:57:36.539   881  1368 D RecurrenceRule: Resolving using anchor 2018-04-06T09:57:36.539+02:00[Europe/Vienna]
04-06 09:57:36.547   881  1368 D RecurrenceRule: Cycle 26 from 2018-03-22T00:00+01:00[Europe/Vienna] to 2018-04-22T00:00+02:00[Europe/Vienna]
04-06 09:57:36.548   881  1368 D NetworkStats: Resolving plan for NetworkTemplate: matchRule=MOBILE_ALL, subscriberId=232106..., matchSubscriberIds=[232106...]
04-06 09:57:36.552   881  1368 D NetworkStats: Found active matching subId 1
04-06 09:57:36.569   881  1368 D NetworkStats: Resolved to plan null
04-06 09:57:36.584   881  1368 D RecurrenceRule: Resolving using anchor 2018-04-06T09:57:36.584+02:00[Europe/Vienna]
04-06 09:57:36.585   881  4728 I ActivityManager: Start proc 5506:com.android.providers.calendar/u0a5 for content provider com.android.providers.calendar/.CalendarProvider2
04-06 09:57:36.590   881  1368 D RecurrenceRule: Resolving using anchor 2018-04-06T09:57:36.590+02:00[Europe/Vienna]
04-06 09:57:36.598   881  1368 D RecurrenceRule: Cycle 26 from 2018-03-22T00:00+01:00[Europe/Vienna] to 2018-04-22T00:00+02:00[Europe/Vienna]
04-06 09:57:36.602   881  1368 D NetworkStats: Resolving plan for NetworkTemplate: matchRule=MOBILE_ALL, subscriberId=232106..., matchSubscriberIds=[232106...]
04-06 09:57:36.607   881  1368 D NetworkStats: Found active matching subId 1
04-06 09:57:36.618   881  1368 D NetworkStats: Resolved to plan null
04-06 09:57:36.638  5506  5506 I zygote64: The ClassLoaderContext is a special shared library.
04-06 09:57:36.646  5506  5506 I chatty  : uid=10005(com.android.providers.calendar) identical 1 line
04-06 09:57:36.654  5506  5506 I zygote64: The ClassLoaderContext is a special shared library.
04-06 09:57:36.682  5506  5506 I CalendarProvider2: Created com.android.providers.calendar.CalendarAlarmManager@a834b21(com.android.providers.calendar.CalendarProvider2@7513b46)
04-06 09:57:36.763   881  4724 I ActivityManager: Start proc 5522:com.appgenix.biztasks/u0a169 for content provider com.appgenix.biztasks/.database.TaskContentProvider
04-06 09:57:58.422   881  1594 I ActivityManager: Killing 4678:android.process.media/u0a14 (adj 906): empty #17
04-06 09:57:58.428   881  1594 I ActivityManager: Killing 32603:com.google.process.gapps/u0a19 (adj 906): empty #18
04-06 09:57:58.429   881   928 W zygote64: kill(-4678, 9) failed: No such process
04-06 09:57:58.498   881   928 I chatty  : uid=1000(system) ActivityManager identical 2 lines
04-06 09:57:58.544   881   928 W zygote64: kill(-4678, 9) failed: No such process
04-06 09:57:58.544   881   928 I zygote64: Successfully killed process cgroup uid 10014 pid 4678 in 115ms
04-06 09:57:58.545   881   928 W zygote64: kill(-32603, 9) failed: No such process
04-06 09:57:58.545   881   928 I zygote64: Successfully killed process cgroup uid 10019 pid 32603 in 0ms
04-06 09:58:11.820  1406  1406 D HeadsetPhoneState: sendDeviceStateChanged. mService=1 mIsSimStateLoaded=true mSignal=4 mRoam=0 mBatteryCharge=5
04-06 09:58:17.549   881   926 W ActivityManager: Stopping service due to app idle: u0a138 -1m1s441ms com.whatsapp/.messaging.MessageService
04-06 09:58:29.739  1406  1406 D HeadsetPhoneState: sendDeviceStateChanged. mService=1 mIsSimStateLoaded=true mSignal=3 mRoam=0 mBatteryCharge=5
04-06 09:58:42.536  1406  1406 D HeadsetPhoneState: sendDeviceStateChanged. mService=1 mIsSimStateLoaded=true mSignal=4 mRoam=0 mBatteryCharge=5
```

**Comment by tvolkert** [comment] 2018-04-06 17:39
Nothing jumps out at me in those logs... @zoechi does this repro in release mode for iOS as well?

**Comment by zoechi** [comment] 2018-04-07 19:51
@tvolkert I can't test that because it doesn't run in release mode on the emulator and I don't have an iPhone.

**Comment by tvolkert** [comment] 2018-04-07 19:54
What about release mode in Android?  Above, it looks like you were running on Android.

**Comment by zoechi** [comment] 2018-04-07 20:01
@tvolkert yes, that's what the issue is about. 
Since recently I doesn't start in release mode on Android anymore.  
It works fine in debug mode. 
I created the last release build about 2 weeks ago where everything was still fine, 
but 4 days ago when I tried to create another release build this one only shows a black screen when started.

**Comment by zoechi** [comment] 2018-04-07 20:08
This is the output when run in release and then in debug mode
```
zoechi@mac ~/dart/customers/lookatyou/lookatmybaby/lookatmybaby_flutter
 (dart2) $ flutter run --release --preview-dart-2
Initializing gradle...                                       1.2s
Resolving dependencies...                                    9.9s
Launching lib/main.dart on Pixel XL in release mode...
Running 'gradlew assembleRelease'...                             
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Built build/app/outputs/apk/release/app-release.apk (14.5MB).
Installing build/app/outputs/apk/app.apk...                 11.4s

To repeat this help message, press "h". To quit, press "q".
I/FlutterActivityDelegate(11140): onResume setting current activity to this
Application finished.

zoechi@mac ~/dart/customers/lookatyou/lookatmybaby/lookatmybaby_flutter
 (dart2) $ flutter run --preview-dart-2
Launching lib/main.dart on Pixel XL in debug mode...
Initializing gradle...                                       0.8s
Resolving dependencies...                                    1.3s
Running 'gradlew assembleDebug'...                               
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Built build/app/outputs/apk/debug/app-debug.apk (38.2MB).
Installing build/app/outputs/apk/app.apk...                 13.0s
I/FlutterActivityDelegate(11486): onResume setting current activity to this
I/Choreographer(11486): Skipped 42 frames!  The application may be doing too much work on its main thread.
D/FA      (11486): Connected to remote service
V/FA      (11486): Processing queued up service tasks: 4
Syncing files to device Pixel XL...                              
I/zygote64(11486): Do partial code cache collection, code=29KB, data=20KB
I/zygote64(11486): After code cache collection, code=27KB, data=19KB
I/zygote64(11486): Increasing code cache capacity to 128KB

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Pixel XL is available at: http://127.0.0.1:8100/
For a more detailed help message, press "h". To quit, press "q".
V/FA      (11486): Inactivity, disconnecting from the service
W/BiChannelGoogleApi(11486): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms
D/FirebaseAuth(11486): Notifying id token listeners about user ( hFWyZYmtgocsWs69TnpHXuEbBRv1 ).
```

The last line `Application finished.` from the `flutter run --release` is because I pressed `Ctrl+c` after the app didn't do anything for a while.

**Comment by tvolkert** [comment] 2018-04-07 20:09
Oops - that's what I get for responding to too many different issues at once 😄 

Is there any chance you could try bisecting the commits between the last known good commit and your current one to try to find which commit made this start happening?

**Comment by zoechi** [comment] 2018-04-07 20:10
@tvolkert Sure, I can do that.

**Comment by zoechi** [comment] 2018-04-10 09:46
@tvolkert I didn't make much progress using `git bisect`. Most previous commits are not working with the current Flutter version. Getting a previous Flutter version turned out tricky in the past.
Any suggestions how to proceed to track the issue down?

**Comment by tvolkert** [comment] 2018-04-10 15:26
So which was the last good commit?  (or put differently, which was the commit that introduced this issue?)

**Comment by tvolkert** [comment] 2018-04-10 17:49
I'd just like to know _which_ commit (or PR) caused your regression.  You've been able to identify the culprit commit using `git bisect`, correct?

**Comment by zoechi** [comment] 2018-04-10 19:11
Yes, I found the commit. The last good one worked with the current `dev` channel and even without `--no-preview-dart-2`.
I worked hours to check what dependency changes or code changes might have caused the problem.
I thought I checked everything relevant but I wasn't able to make the successor commit work.
As mentioned it was a rather big commit, but most modified files were generated files with changed comments or test files with minor import changes which I didn't check.
The process was rather slow because I had to clean before each build.

**Comment by tvolkert** [comment] 2018-04-10 19:25
I'm looking for the commit hash where this started happening for you...

As of this writing, the current dev channel is at d6d874474b21b512aac03f1dcd0d3b88835cdcdd, and the commit after that is bdc06194fb21c4342f121809714497b1c7be42f3.  Does that mean that your bisect has identified bdc06194fb21c4342f121809714497b1c7be42f3 as the commit that introduced the regression?

**Comment by zoechi** [comment] 2018-04-10 19:45
It seems you mean Flutter commits. I was talking about commits in my code.
I did all with 
```
Flutter 0.2.10 • channel dev • https://github.com/flutter/flutter.git
Framework • revision d6d874474b (4 days ago) • 2018-04-06 13:23:16 -0700
Engine • revision d2b69fec75
Tools • Dart 2.0.0-dev.46.0.flutter-09e1766e6c
```

**Comment by tvolkert** [comment] 2018-04-10 20:29
Ah, I see.  I misunderstood the bug report as being isolated to a commit in the Flutter repository.

So just to verify: against `v0.2.10`, your app works in release mode, **until you make some local change**, after which it starts rendering a black screen?  If so, do you think you could come up with a minimal reproducible case that we could use to try to reproduce locally?

Side-note: trying out older versions of Flutter should work since Flutter pins its dependencies to specific versions.  But you probably would have to fiddle with your `pubspec.yaml` file to make sure you're specifying versions of packages that are compatible with the version of the Dart SDK that is vended by your version of Flutter.

**Comment by zoechi** [comment] 2018-04-11 07:29
This issue confused me a lot so not wonder you're confused by my comments as well ;-)


In `v0.2.10` my app works in release mode only with `--no-preview-dart-2`. 
In debug mode it also works without `--no-preveiw-dart-2`.

"Not working" means the app just stops executing in some built_redux built_value update code without any error. 
The screen stays black because I call this code before `runApp(...)`

A 10 days old version of my app even works without `--no-preview-dart-2` (still with `v0.2.10`) but I wasn't able to track down what change broke it even though I found the commit that where it broke.

When I change the code I have to run `flutter clean` for `flutter run --release` to take up the changes made, otherwise it just runs the previous build. 
If there were some incremental build to reduce build time, the process of tracking down the code that causes the problem would take much less time. 
Not sure if this is working as intended.

**Comment by zoechi** [comment] 2018-04-11 07:46
I now was able to get the exception. It was my fault with global error handling that I didn't get one before: 

```
To repeat this help message, press "h". To quit, press "q".
I/FlutterActivityDelegate( 9032): onResume setting current activity to this
E/flutter ( 9032): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 9032): Attempt to execute code removed by Dart AOT compiler (TFA)
E/flutter ( 9032): #0      RxAppReducers.wasInitialized (package:lookatmybaby_shared/src/client/reducer/app.dart:0)
E/flutter ( 9032): #1      ReducerBuilder.add.<anonymous closure> (package:built_redux/src/reducer_builder.dart:21)
E/flutter ( 9032): #2      ReducerBuilder.build.<anonymous closure> (package:built_redux/src/reducer_builder.dart:76)
E/flutter ( 9032): #3      new Store..<anonymous closure>.<anonymous closure> (package:built_redux/src/store.dart:40)
E/flutter ( 9032): #4      RxAppBuilder.update (file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_shared/lib/src/client/state/app.g.dart:564)
E/flutter ( 9032): #5      _$RxApp.rebuild (file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_shared/lib/src/client/state/app.g.dart:322)
E/flutter ( 9032): #6      new Store..<anonymous closure> (package:built_redux/src/store.dart:40)
E/flutter ( 9032): #7      errorReporterMiddleware.<anonymous closure>.<anonymous closure> (package:lookatmybaby_shared/src/util/rx/middleware/error_reporter_middleware.dart:28)
E/flutter ( 9032): #8      loggingMiddleware.<anonymous closure>.<anonymous closure> (package:lookatmybaby_shared/src/util/rx/middleware/logging_middleware.dart:18)
E/flutter ( 9032): #9      ActionDispatcher.call (package:built_redux/src/action.dart:32)
E/flutter ( 9032): #10     AppController.initializeState (package:lookatmybaby_shared/src/client/controller/app_controller.dart:153)
E/flutter ( 9032): #11     initAndRunApp (package:lookatmybaby_flutter/app.dart:35)
E/flutter ( 9032): <asynchronous suspension>
E/flutter ( 9032): #12     main.<anonymous closure> (file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_flutter/lib/main_zoechi.dart:18)
E/flutter ( 9032): #13     _rootRun (dart:async/zone.dart:1126)
E/flutter ( 9032): #14     _CustomZone.run (dart:async/zone.dart:1023)
E/flutter ( 9032): #15     runZoned (dart:async/zone.dart:1501)
E/flutter ( 9032): #16     main (file:///Users/zoechi/dart/customers/lookatyou/lookatmybaby/lookatmybaby_flutter/lib/main_zoechi.dart:16)
E/flutter ( 9032): #17     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279)
E/flutter ( 9032): #18     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165)
```

**Comment by zoechi** [comment] 2018-04-11 08:57
With `--no-preview-dart-2` missing `new` and `const` are only recognized at runtime, but not at build time.

**Comment by tvolkert** [comment] 2018-04-11 14:52
Thanks @zoechi that's very helpful!

/cc @a-siva @dgrove -- the previous 3 comments (from [here](https://github.com/flutter/flutter/issues/16182#issuecomment-380355280) down) indicate that used code is getting tree-shaken only when run with Dart 2 (possibly due to some interactions with `package:built_redux`)

@zoechi a few questions:
1. Does the app fail if you use `--no-preview-dart-2` and _put back_ all of the missing `new` and `const` keywords?
1. Do you think you could construct a minimal fake app that uses `package:built_redux` to reproduce this problem?

**Comment by zoechi** [comment] 2018-04-11 16:00
@tvolkert The app works fine with `--no-preview-dart-2`.

I had 2 or 3 places where I forgot to add `new` or `const`, otherwise I don't make use of this feature yet. 

The problem was that these 2 or 3 missing `new` or `const` didn't cause build errors, 
but caused an exception at runtime "no such static method" or similar.
After fixing them the app worked with `--no-preview-dart-2`.

**Comment by dgrove** [comment] 2018-04-11 16:03
@zoechi - thanks! When you run the Dart analyzer, do you see errors there?

**Comment by mraleph** [comment] 2018-04-11 16:40
This looks like a bug in TFA (/cc @alexmarkov). We would need more information to reduce it to a repro.

**Comment by mraleph** [comment] 2018-04-11 17:15
I have tried few simple examples but so far I have not been able to reproduce the issue. I have asked @zoechi to provide some information from kernel binaries in attempt to reduce it to a reproduction.

**Comment by alexmarkov** [comment] 2018-04-11 17:48
I was able to reproduce the TFA exception on an example from https://github.com/davidmarne/built_redux package. I'm looking into it now.

Still, it might be useful to get reproduction from your application, in case this is a different bug.

**Comment by zoechi** [comment] 2018-04-11 19:53
@dgrove I have still enabled `--preview-dart-2` (default) in IntelliJ. I'd have to use `--no-preview-dart-2` with DartAnalyzer to see the missing `new` and `const`. I can check tomorrow.

**Comment by alexmarkov** [comment] 2018-04-12 17:15
https://github.com/dart-lang/sdk/commit/17fc446579e2c71983e240a3993ba30deec3be4f fixes the problem, at least on built_redux example. It will be rolled into Flutter soon.

**Comment by alexmarkov** [comment] 2018-04-13 20:42
The fix for 'Attempt to execute code removed by Dart AOT compiler (TFA)' was rolled into flutter (master channel).

@zoechi, could you check if your application works on the latest flutter/master?

**Comment by zoechi** [comment] 2018-04-16 07:00
@alexmarkov works fine in 
```dart
Flutter 0.2.12-pre.34 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6c049ec286 (5 hours ago) • 2018-04-15 19:24:49 -0700
Engine • revision 76cb311d9c
Tools • Dart 2.0.0-dev.47.0.flutter-f76dad0adc
```
thanks a lot for the quick fix 👍

**Comment by tvolkert** [comment] 2018-04-16 15:13
Closing this as fixed. Thanks for the quick fix @alexmarkov and for the patience with me in trying to diagnose @zoechi 😄

**Closed by tvolkert** 2018-04-16 15:13 UTC
Labels: crash, dart2
