### ISSUE TITLE
CupertinoNavigationBar animation flickering

### ISSUE THREAD

**Issue by antekone** [flutter/flutter#42988] opened 2019-10-18 05:24 UTC
## Steps to Reproduce

After updating Flutter to v1.9.1+hotfix.4, I'm getting a weird flickering in `CupertinoNavigationBar` when changing pages. Here's a video that demonstrates the issue, please look at `NavigationBar` during changing screens:

https://youtu.be/MmUaFUVVtyo

Sometimes it's flickering, sometimes it's not, but most of the time it is flickering. If a button exists in the `trailing` property, this button sometimes is rendered *below* the navigation bar for a few frames, and it goes back into proper position. It looks very ugly.

I'm using very simple method for creation of the page:

```
import 'package:flutter/cupertino.dart';

class AddNewDuePage extends StatefulWidget {
  @override
  _AddNewDuePageState createState() => _AddNewDuePageState();
}

class _AddNewDuePageState extends State<AddNewDuePage> {
  Widget buildBody() {
    return Text("OK");
  }

  @override
  Widget build(BuildContext context) {
    var _navigationBar = CupertinoNavigationBar(
      middle: Text("Nowa składka"), // TODO: I18N
    );

    return CupertinoPageScaffold(
      navigationBar: _navigationBar,
      child: SafeArea(child: buildBody()),
    );
  }
}
```

Is this a problem with my Flutter installation, or is it a regression?

The problem exists in Debug compilations on Emulator & real hardware, as well as in Release compilations in real hardware (can't run release compilation in emulator).

**Target Platform:** Linux (emulator) + Android
**Target OS version/browser:** 9
**Devices:** Android Emulator, also Sony Xperia XZ Premium

## Flutter doctor

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.4 at /home/antek/dev/android/flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/antek/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/antek/Android/Sdk
    • Java binary at: /home/antek/dev/android/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_152-release"
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup
      for detailed instructions.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/antek/dev/android/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version openjdk version "1.8.0_152-release"

[!] IntelliJ IDEA Community Edition (version 2019.2-old)
    • IntelliJ at /home/antek/data/apps/idea/idea-IC-192.5728.98
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.

```

Not sure why `doctor` didn't detect flutter/dart plugins for IDEA, because I'm using Idea with those plugins. Also everything is working with my Android toolchain, also not sure why doctor has issues with licenses.

**Comment by HansMuller** [comment] 2019-10-18 15:33
CC @justinmc

**Comment by justinmc** [comment] 2019-10-18 15:50
I was able to reproduce this with a very simple app, so it seems to be a regression bug in Flutter!

```dart
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'First Page'),
      routes: {
        '/second': (BuildContext context) => MyHomePage(title: 'Second Page'),
      },
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text(title),
      ),
      child: Center(
        child: CupertinoButton(
          child: Text('Go'),
          onPressed: () {
            Navigator.pushNamed(context, '/second');
          },
        ),
      ),
    );
  }
}
```

**Comment by justinmc** [comment] 2019-10-18 16:43
It seems to have been caused by https://github.com/flutter/flutter/pull/31614 based on me trying old versions.

**Comment by justinmc** [comment] 2019-10-18 16:54
@gspencergoog Do you have any idea why that PR may have caused the text in CupertinoNavigationBar to flicker between routes?  Nothing jumps out as super obvious to me.

**Comment by justinmc** [comment] 2019-10-18 17:53
Some details:

I confirmed that https://github.com/flutter/flutter/pull/31614 is the first change that has the bug in it.  Checking out its merge commit, 7775c23784fdd7890a453031e0451fbed3731247, exhibits the bug, but checking out the commit directly before it, fdd554fb46e885292fb9c82e91969e21b603a1c3, does not.

That PR is a re-land of https://github.com/flutter/flutter/pull/30040.  If I check out the merge commit from that original PR, 4218c0bc3, then I do not see the bug.

**Comment by LongCatIsLooong** [comment] 2019-10-20 22:01
There's a different issue reported [here](https://github.com/flutter/flutter/issues/36220#issuecomment-544264829) that looks related, video: http://treefortress.com/shared/2019-10-20_09-49-24.mp4. 

> I can manually size the container to get rid of it, but these containers are variable width, depending on the size of their text, so that's not ideal.

@GaryQian could there be a problem with text sizing? From the description it feels like we're not giving the `Text` widget the width it needs.

**Comment by esDotDev** [comment] 2019-10-21 06:28
Here's a minimal code example that should reproduce the problem. Click the text to trigger the transition, you should see it flicker intermittently: 
http://treefortress.com/shared/2019-10-21_00-19-14.mp4

It seems related to horizontal movement. If I change alignments so it animates vertically, (TopLeft > BottomLeft), it doesn't flicker at all. 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Page1());
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: GestureDetector(
        child: Container(
          alignment: Alignment.centerLeft,
          child: HeroContent(),
        ),
        onTap: () {
          Navigator.of(context).push(PageRouteBuilder(
            pageBuilder: (_, __, ___) => Page2(),
            transitionDuration: Duration(seconds: 2),
          ));
        },
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Container(
        color: Colors.transparent,
        alignment: Alignment.centerRight,
        child: HeroContent(),
      ),
    );
  }
}

class HeroContent extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Hero(
      tag: "hero",
      child: Material(
        color: Colors.transparent,
        child: Container(
          child: Text(
            "Aries",
            style: TextStyle(fontSize: 42, color: Colors.white),
          ),
        ),
      ),
    );
  }
}
```

**Comment by esDotDev** [comment] 2019-10-21 16:48
Small update, using Row() does not completely get rid of the issues. When using Row() + MaterialRectArcTween, I get overflow errors in extremely small values:

> The following assertion was thrown during layout:
A RenderFlex overflowed by 0.000895 pixels on the right.

> User-created ancestor of the error-causing widget was: 
  Column file:///D:/_Development/gskinner.com/flutter-vignettes/flutter-vignettes-git/constellations_list/lib/constellation_title_card.dart:31:18
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.


The most robust fix I've found so far is to just wrap the text in spaces " FooBar ".

**Comment by antekone** [comment] 2019-10-28 10:03
Surrounding text with spaces indeed helps with flickering, but doesn't help when sometimes the "trailing" widget in CupertinoNavigationBar is displayed in the wrong place for few frames.

I'll try downgrading Flutter to previous version, it was much more stable than now.

**Comment by antekone** [comment] 2019-12-15 16:33
Unfortunately this issue still exists in 1.12.13+hotfix.5

**Comment by justinmc** [comment] 2019-12-16 19:45
@antekone Can you try it on master?  I just tried my [example app above](https://github.com/flutter/flutter/issues/42988#issuecomment-543806420) on my iPhone 7 and I couldn't reproduce the problem.

**Comment by antekone** [comment] 2019-12-18 14:29
You mean channel master?

When testing your example app on version `1.13.3-pre.60 / channel master` on an Android phone (Xperia G8141), as well as on Android emulator, the problem still exists.

    Flutter 1.13.3-pre.60 • channel master • https://github.com/flutter/flutter.git
    Framework • revision ceef460a64 (6 hours ago) • 2019-12-18 00:23:02 -0800
    Engine • revision 500f9cedf6
    Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 2d332ee1d3)

I don't own a Mac, so I can't check it on an iPhone.

**Comment by antekone** [comment] 2020-01-14 19:40
Newest version (`1.12.13+hotfix5`) has broken lots of additional things (i.e. `showCupertinoDialog` is utterly broken now, where previously it worked well). It's now clear to me that nobody checks if Cupertino theme works on Android.

I've downgraded Flutter to `1.3.9`:

    Framework • revision f91df4abe1 (10 months ago) • 2019-03-09 21:19:28 -0500
    Engine • revision 4e54bc93ca
    Tools • Dart 2.2.1 (build 2.2.1-dev.1.0 2fb6cd9f5f)

Everything is smooth and nice on this version: there is no flickering that I'm describing in the original post, as well as `showCupertinoDialog` works without issues. I'm going to try to release newer version of my app on this older SDK. If it will go well, I'll port my app away from Flutter to some other framework.

**Comment by LongCatIsLooong** [comment] 2020-01-14 20:31
Hi @antekone, sorry about the poor experience you've had with the latest stable. Could you elaborate a bit more on `showCupertinoDialog` being utterly broken (or maybe create a new issue for it)? The gallery app uses `showCupertinoDialog` and it seems to be working fine.

As for this issue, I believe we should keep the issue open since downgrading is not a real fix. I don't have a proper fix for this floating point arithmetic problem yet but I think multiple workarounds exist (e.g., the one @esDotDev pointed out, disabling softwrap on the text widget). In the meantime if you have a proper fix for the problem, pull requests are always welcome!

**Comment by antekone** [comment] 2020-01-14 22:14
@LongCatIsLooong 

1. I don't think this is merely floating point arithmetic problem. If the user has selected a bigger font in system settings, the fonts are jumping around the navigation bar even if I surround them with multiple spaces and disable softWrap property. Here's a link to the video that shows this problem (fast forward to 4:14 if you don't have time to watch through the full test):

    https://www.youtube.com/watch?v=DbJePwR-lno

2. Sorry for using such vague descriptions like "utterly" when ranting about `showCupertinoDialog`. To show you what I mean, I've prepared two repositories: 

    - one for old SDK that can be compiled with Flutter `1.3.9`: https://github.com/antekone/show_cupertino_dialog_bug_old_sdk
    - another one for new SDK that can be compiled with Flutter `1.12.13+hotfix.5`: https://github.com/antekone/show_cupertino_dialog_bug_new_sdk

    Both repositories contain the same project with the same source files in the `lib` directory. Just the build scripts are different, because building 'old_sdk' version fails with new Flutter, and building 'new_sdk' fails when building with old Flutter.

    This is the video what happens under different versions of Flutter. First I'm trying to run it on `1.3.9`, then on `1.12.13+hotfix.5`.

    https://www.youtube.com/watch?v=Zh395g5wkd4

**Comment by LongCatIsLooong** [comment] 2020-01-14 23:57
I think the `showCupertinoDialog` change is a feature: https://github.com/flutter/flutter/pull/42967/files. You can remove the `SystemPadding` widget now since the `viewInsets` is already taken care of by the dialog. To prevent future breakages one option is to provide your tests as suggested here: https://flutter.dev/docs/resources/compatibility.

Haven't had the chance to look into what might have caused 1 but I'll update when I find the issue.

**Comment by antekone** [comment] 2020-01-15 13:36
Thanks you for your help. Indeed, removing SystemPadding helped. Sorry for my frustration about this `showCupertinoDialog`.

I've signed up for `flutter-announce` mailing list and I'll check the page you've linked (btw, there's a typo in it, that results in an invalid url to github).

**Comment by TahaTesser** [comment] 2020-03-30 16:10
Issue still exist 


### Code Sample
```
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      debugShowCheckedModeBanner: false,
      title: 'Cupertino App',
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('Cupertino App Bar'),
      ),
      child: Center(
          child: CupertinoButton(
              child: Text('Go Next'),
              onPressed: () {
                Navigator.push(context,
                    CupertinoPageRoute(builder: (_) => AddNewDuePage()));
              })),
    );
  }
}

class AddNewDuePage extends StatefulWidget {
  @override
  _AddNewDuePageState createState() => _AddNewDuePageState();
}

class _AddNewDuePageState extends State<AddNewDuePage> {
  Widget buildBody() {
    return Text("OK");
  }

  @override
  Widget build(BuildContext context) {
    var _navigationBar = CupertinoNavigationBar(
      middle: Text("Nowa składka"), // TODO: I18N
    );

    return CupertinoPageScaffold(
      navigationBar: _navigationBar,
      child: SafeArea(child: buildBody()),
    );
  }
}
```

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.16.3 at /Users/taha/Code/flutter_dev
    • Framework revision be3a4b37b3 (4 days ago), 2020-03-26 18:08:05 -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • iPhone 11  • 41EB2A85-7EB4-4FD2-8978-FBBE2A681D74 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.4 19E266
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 80.0.3987.149
    • Web Server • web-server                           • web-javascript •
      Flutter Tools

• No issues found!
```

**Comment by LevinGermann** [comment] 2020-04-28 13:59
I experience the same issue, it really seems to be related to horizontal movement. Interesting though is that only the last part flickers, see reference here:

[https://youtu.be/uO5BjCTElY8](https://youtu.be/uO5BjCTElY8)

**Comment by antekone** [comment] 2020-06-07 06:57
Still there in this version:

```
Flutter 1.17.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b041144f83 (3 days ago) • 2020-06-04 09:26:11 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

**Comment by rakeshh025** [comment] 2020-07-01 13:31
Any updates or workaround?

**Comment by moodstubos** [comment] 2021-02-02 15:13
still there on 1.22.6

**Comment by nt4f04uNd** [comment] 2021-05-19 01:06
This is caused by RelativeRect in used in transitions may produce a small overflow from floating point subtraction. The fix is quite simple - just add precisionErrorTolerance to them. I'm wondering how many else places in the framework may contain something unobvious like this

**Closed** 2021-08-31 21:01 UTC
Labels: severe: regression, framework, a: animation, f: cupertino, a: quality, has reproducible steps, found in release: 1.21
