### ISSUE TITLE
iOS The bundle's Info.plist does not contain a CFBundleVersion key or its value is not a string

### ISSUE THREAD

**Issue by XinleZhou2018** [flutter/flutter#75686] opened 2021-02-09 06:55 UTC
Flutter Doctor:

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.0)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

XCODE version 12.3

I change my flutter version in pubspec.yaml file:
`version: 1.5.0+43
`

and Then run my application in VSCode，after success, I open the XCode，I found that the version and build number is empty. I check the info.plist file. CFBundleShortVersionString and CFBundleVersion using the Flutter variable value.
```
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>

	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
```

It seems XCODE did not read these two flutter values correctly.

I change the flutter sdk to 1.12.13, it works well.

**Comment by XinleZhou2018** [comment] 2021-02-09 06:56
@jmagman

**Comment by TahaTesser** [comment] 2021-02-09 08:21
Hi @XinleZhou2018 
Just tried to reproduce the issue on the `stable` channel, when updating `pubspec.yaml`, the version and build number are correctly updated in Xcode and also shows verifiable in the app using [package_info](https://pub.dev/packages/package_info/example).

```yaml
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.0+43

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  package_info: ^0.4.3+4
```

<img width="484" alt="Screenshot 2021-02-09 at 1 39 16 PM" src="https://user-images.githubusercontent.com/48603081/107334768-23732f00-6add-11eb-9e59-f3324142e8a3.png">

<img width="391" alt="Screenshot 2021-02-09 at 1 46 20 PM" src="https://user-images.githubusercontent.com/48603081/107334846-40a7fd80-6add-11eb-832b-21b1cb33f484.png">

Unless you expect this field to change, no issue here, the flutter variable is used here even if you change the version in pubspec
```
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>

	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
```


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2 20D64 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0
[✓] Connected device (2 available)
    • Taha’s iPad (mobile)       • 00008020-000255113EE8402E            • ios • iOS 14.4
    • iPhone 12 Pro Max (mobile) • DB6F8402-E89F-4E94-9644-151970DBE05B • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
! Doctor found issues in 3 categories.
```

</details>


Can you please provide more details?
Thank you

**Comment by Ruzo** [comment] 2021-02-15 12:22
Had this error and found out it was due to the App version and Build number fields being empty. Fixed it by inputing some random values in Xcode.

**Comment by pedromassangocode** [comment] 2021-03-12 14:04
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-03-12 14:04 UTC
Labels: in triage, waiting for customer response
