### ISSUE TITLE
Support transparent FlutterView

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#19190] opened 2018-07-09 23:59 UTC
This is a fork from https://github.com/flutter/flutter/issues/17874 because the use cases for transparent view is a bit different:

- When using a FlutterView which intrinsic sizing, the resize operation causes the contents to be re-rendered. This "flash" is quite visible if the background of the view is black. The flash itself is being tracked here: https://github.com/flutter/flutter/issues/19189
- Customer dream wants to show background set in a native container through the flutter view. For instance, you can imagine a text box being laid on top of a "wallpaper". Setting this wallpaper in native container + in Flutter view would lead to hard to control artifacts such as mismatched seams.
- Certain widgets such as card have implicit margins. This causes a black border to be visible around the card.

**Comment by mklim** [comment] 2018-09-05 01:12
This looks like a duplicate of #9627 to me, will be tracking it there.

**Closed by mklim** 2018-09-05 01:12 UTC
Labels: a: existing-apps, customer: dream (g3), severe: new feature
