### ISSUE TITLE
Image filter support (ex: Tone Curve)

### ISSUE THREAD

**Issue by yagitatsu** [flutter/flutter#18474] opened 2018-06-14 09:56 UTC
I have seen the excellent default library called CIFilter in iOS.
Do you have any plans to support equivalent function ?

**Comment by zoechi** [comment] 2018-06-15 09:06
Can you please add a link to CIFilter to make it more clear what the feature request is about?

**Comment by yagitatsu** [comment] 2018-06-15 09:37
Thanks for your reply.
I'm sorry about that. It would be happy if you check links below: 

https://developer.apple.com/documentation/coreimage/cifilter
https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/CoreImaging/ci_intro/ci_intro.html#//apple_ref/doc/uid/TP30001185

**Comment by zoechi** [comment] 2018-06-15 09:47
@Hixie

**Comment by goderbauer** [comment] 2018-12-29 02:17
Related to (and possibly a dupe of) https://github.com/flutter/flutter/issues/13489 orhttps://github.com/flutter/flutter/issues/16296.

**Comment by jonahwilliams** [comment] 2024-08-13 03:06
Closing in favor of https://github.com/flutter/flutter/issues/16296 .

This can generally be done with fragment shaders, and we're planning to add APIs to make this easier in the future.

**Closed by jonahwilliams** 2024-08-13 03:06 UTC
Labels: c: new feature, framework, engine, P3, team-engine, triaged-engine
