### ISSUE TITLE
SliverPersistentHeader with pinned:true is not pinned when parent CustomScrollView is wrapped in a NestedScrollView 

### ISSUE THREAD

**Issue by jeduden** [flutter/flutter#94116] opened 2021-11-23 16:57 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. Scroll up

**Expected results:**
Red persistent header should stay pinned below appbar.

**Actual results:** 
Red persistent header scrolls with the other items under the appbar.

![Simulator Screen Recording - iPhone 8 - 2021-11-23 at 17 45 09](https://user-images.githubusercontent.com/1117699/143068789-83da9cb5-ece2-4d03-8b8d-e3fe58846a58.gif)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class HeaderDelegate extends SliverPersistentHeaderDelegate {
  @override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Container(height: 48, color: Colors.red);
  }

  @override
  double get maxExtent => 48.0;

  @override
  double get minExtent => 48.0;

  @override
  bool shouldRebuild(covariant SliverPersistentHeaderDelegate oldDelegate) =>
      true;
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: "App",
        home: Scaffold(
          body: NestedScrollView(
            headerSliverBuilder:
                (BuildContext context, bool innerBoxIsScrolled) {
              return <Widget>[
                SliverOverlapAbsorber(
                  handle:
                      NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                  sliver: SliverAppBar(
                    title: const Text('Books'),
                    pinned: true,
                    expandedHeight: 150.0,
                    forceElevated: innerBoxIsScrolled,
                  ),
                ),
              ];
            },
            body: SafeArea(
              top: false,
              bottom: false,
              child: Builder(
                builder: (BuildContext context) {
                  return CustomScrollView(
                    slivers: <Widget>[
                      SliverOverlapInjector(
                        handle: NestedScrollView.sliverOverlapAbsorberHandleFor(
                            context),
                      ),
                      SliverPersistentHeader(
                        delegate: HeaderDelegate(),
                        pinned: true,
                      ),
                      SliverPadding(
                        padding: const EdgeInsets.all(8.0),
                        sliver: SliverFixedExtentList(
                          itemExtent: 48.0,
                          delegate: SliverChildBuilderDelegate(
                            (BuildContext context, int index) {
                              return ListTile(
                                title: Text('Item $index'),
                              );
                            },
                            childCount: 30,
                          ),
                        ),
                      ),
                    ],
                  );
                },
              ),
            ),
          ),
        ));
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
[ +100 ms] executing: sysctl hw.optional.arm64
[  +19 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[   +6 ms] executing: [/usr/local/Caskroom/flutter/1.22.4/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +14 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18116933e77adc82f80866c928266a5b4f1ed64
[        ] executing: [/usr/local/Caskroom/flutter/1.22.4/flutter/] git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[ +128 ms] Exit code 0 from: git tag --points-at 18116933e77adc82f80866c928266a5b4f1ed645
[        ] 2.5.3
[  +12 ms] executing: [/usr/local/Caskroom/flutter/1.22.4/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/usr/local/Caskroom/flutter/1.22.4/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +104 ms] executing: [/usr/local/Caskroom/flutter/1.22.4/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +21 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +17 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.4
[        ] executing: sw_vers -buildVersion
[  +17 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20F71
[  +81 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +53 ms] executing: /Users/jeduden/Library/Android/sdk/platform-tools/adb devices -l
[  +13 ms] executing: sysctl hw.optional.arm64
[   +5 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[ +876 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 13.0
           Build version 13A233
[   +3 ms] executing: xcrun xcdevice list --timeout 2
[   +4 ms] xcrun simctl list --json devices
[        ] executing: xcrun simctl list --json devices
[   +6 ms] executing: xcrun simctl list
[ +164 ms] Exit code 0 from: xcrun simctl list
[        ] == Device Types ==
           iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
           iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
           iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
[...]
[  +53 ms] List of devices attached
           ce081718db14e52105     device usb:336592896X product:dreamltexx model:SM_G950F device:dreamlte transport_id:1
[ +161 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.tvOS-13-2" : [
                          {
                            "availabilityError" : "runtime profile not found",
                            "dataPath" : "\/Users\/jeduden\/Library\/Developer\/CoreSimulator\/Devices\/02AB5E48-E12C-4860-AA77-7F49E158D278\/data",
                            "logPath" : "\/Users\/jeduden\/Library\/Logs\/CoreSimulator\/02AB5E48-E12C-4860-AA77-7F49E158D278",
                            "udid" : "02AB5E48-E12C-4860-AA77-7F49E158D278",
                            "isAvailable" : false,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p",
                            "state" : "Shutdown",
                            "name" : "Apple TV"
                          },
[...]
^[^[[+3042 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "12.2 (16E226)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,4",
                        "identifier" : "B6937D53-0E8E-4E3D-B03F-5B23FC8B00B1",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-8-2",
                        "modelName" : "iPhone 8",
                        "name" : "iPhone 8"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "15.0 (19A339)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,5",
                        "identifier" : "56396665-03B3-4E5A-B14C-0972D83820AB",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-11-pro-max-1",
                        "modelName" : "iPhone 11 Pro Max",
                        "name" : "iPhone 11 Pro Max"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "15.0 (19A339)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone13,4",
                        "identifier" : "26247B50-915F-4DE7-A8FC-9612B8D4C3B3",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-12-pro-max-1",
                        "modelName" : "iPhone 12 Pro Max",
                        "name" : "iPhone 12 Pro Max"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "15.0 (19A339)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,5",
                        "identifier" : "A2236281-E764-4790-9B4A-BB76EAFED02C",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.ipad-pro-11-3rd-1",
                        "modelName" : "iPad Pro (11-inch) (3rd generation)",
                        "name" : "iPad Pro (11-inch) (3rd generation)"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "12.2 (16E226)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone9,1",
                        "identifier" : "D830C871-73D9-4AD8-A0B6-8EE606EA858D",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-7-1",
                        "modelName" : "iPhone 7",
                        "name" : "iPhone 7"
                      },
[...]
[  +19 ms] Skipping pub get: version match.
[ +133 ms] Generating /Users/jeduden/dev/git/nestedscrollviewbug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +84 ms] Initializing file store
[  +12 ms] Skipping target: gen_localizations
[   +7 ms] Skipping target: gen_dart_plugin_registrant
[        ] Skipping target: _composite
[   +2 ms] complete
[   +4 ms] Launching lib/main.dart on iPhone 8 in debug mode...
[   +5 ms] /usr/local/Caskroom/flutter/1.22.4/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /usr/local/Caskroom/flutter/1.22.4/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot
--sdk-root /usr/local/Caskroom/flutter/1.22.4/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /var/folders/2b/hjz_cyln6td6qp1mk3t629ph0000gn/T/flutter_tools.jlwlYB/flutter_tool.1mDUlO/app.dill --packages
/Users/jeduden/dev/git/nestedscrollviewbug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[  +11 ms] executing: [/Users/jeduden/dev/git/nestedscrollviewbug/ios/] xcrun xcodebuild -list
[  +10 ms] <- compile package:nestedscrollviewbug/main.dart
[+3053 ms] Command line invocation:
                        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

                    User defaults from command line:
                        IDEPackageSupportUseBuiltinSCM = YES

                    Information about project "Runner":
                        Targets:
                            Runner

                        Build Configurations:
                            Debug
                            Release
                            Profile

                        If no build configuration is specified and -scheme is not passed then "Release" is used.

                        Schemes:
                            Runner
[  +12 ms] executing: [/Users/jeduden/dev/git/nestedscrollviewbug/ios/Runner.xcodeproj/] xcrun xcodebuild -project /Users/jeduden/dev/git/nestedscrollviewbug/ios/Runner.xcodeproj -scheme Runner -configuration Debug
-showBuildSettings BUILD_DIR=/Users/jeduden/dev/git/nestedscrollviewbug/build/ios
[   +2 ms] executing: [/Users/jeduden/dev/git/nestedscrollviewbug/ios/Runner.xcodeproj/] xcrun xcodebuild -project /Users/jeduden/dev/git/nestedscrollviewbug/ios/Runner.xcodeproj -scheme Runner -configuration Debug
-showBuildSettings BUILD_DIR=/Users/jeduden/dev/git/nestedscrollviewbug/build/ios
[+1660 ms] Command line invocation:
                        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/jeduden/dev/git/nestedscrollviewbug/ios/Runner.xcodeproj -scheme Runner -configuration Debug -showBuildSettings
                        BUILD_DIR=/Users/jeduden/dev/git/nestedscrollviewbug/build/ios

                    User defaults from command line:
                        IDEPackageSupportUseBuiltinSCM = YES

                    Build settings from command line:
                        BUILD_DIR = /Users/jeduden/dev/git/nestedscrollviewbug/build/ios

                    Build settings for action build and target Runner:
                        ACTION = build
                        AD_HOC_CODE_SIGNING_ALLOWED = NO
[...]
[ +139 ms]  └─Compiling, linking and signing... (completed in 5.5s)
[        ] Xcode build done.                                           24.6s
[   +1 ms] executing: rsync -av --delete /Users/jeduden/dev/git/nestedscrollviewbug/build/ios/Debug-iphonesimulator/Runner.app /Users/jeduden/dev/git/nestedscrollviewbug/build/ios/iphonesimulator
[ +841 ms] building file list ... done
                    Runner.app/
                    Runner.app/Info.plist
                    Runner.app/PkgInfo
                    Runner.app/Runner
                    Runner.app/Frameworks/
                    Runner.app/Frameworks/App.framework/
                    Runner.app/Frameworks/App.framework/App
                    Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources
                    Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json
                    Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json
                    Runner.app/Frameworks/App.framework/flutter_assets/NOTICES.Z
                    Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
                    Runner.app/Frameworks/Flutter.framework/
                    Runner.app/Frameworks/Flutter.framework/Flutter
                    Runner.app/Frameworks/Flutter.framework/_CodeSignature/CodeResources
                    Runner.app/_CodeSignature/CodeResources

                    sent 116189973 bytes  received 308 bytes  77460187.33 bytes/sec
                    total size is 145367036  speedup is 1.25
[   +2 ms] executing: xcrun simctl install FC0588FD-0538-47C2-88EB-04AA7D190C9E /Users/jeduden/dev/git/nestedscrollviewbug/build/ios/iphonesimulator/Runner.app
[+1048 ms] executing: /usr/bin/plutil -convert json -o - /Users/jeduden/dev/git/nestedscrollviewbug/build/ios/iphonesimulator/Runner.app/Info.plist
[   +9 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Users/jeduden/dev/git/nestedscrollviewbug/build/ios/iphonesimulator/Runner.app/Info.plist
[        ]
{"CFBundleName":"nestedscrollviewbug","DTXcode":"1300","DTSDKName":"iphonesimulator15.0","UILaunchStoryboardName":"LaunchScreen","CFBundleIcons~ipad":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIco
n29x29","AppIcon40x40","AppIcon60x60","AppIcon76x76","AppIcon83.5x83.5"],"CFBundleIconName":"AppIcon"}},"DTSDKBuild":"19A339","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildMachineOSBuild":"20F71","DTPla
tformName":"iphonesimulator","CFBundlePackageType":"APPL","UIMainStoryboardFile":"Main","CFBundleSupportedPlatforms":["iPhoneSimulator"],"CFBundleShortVersionString":"1.0.0","CFBundleInfoDictionaryVersion":"6.0","CFBu
ndleExecutable":"Runner","DTCompiler":"com.apple.compilers.llvm.clang.1_0","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortrait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLa
ndscapeLeft","UIInterfaceOrientationLandscapeRight"],"MinimumOSVersion":"9.0","CFBundleIdentifier":"com.example.nestedscrollviewbug","UIDeviceFamily":[1,2],"DTPlatformVersion":"15.0","CFBundleSignature":"????","CFBund
leIcons":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60"],"CFBundleIconName":"AppIcon"}},"DTXcodeBuild":"13A233","LSRequiresIPhoneOS":true,"UISupportedInterface
Orientations":["UIInterfaceOrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBarAppearance":false,"NSBonjourServices":["_dartobservatory._tc
p"],"DTPlatformBuild":"19A339","NSLocalNetworkUsageDescription":"Allow Flutter tools on your computer to connect and debug your application. This prompt will not appear on release builds."}
[   +3 ms] executing: xcrun simctl launch FC0588FD-0538-47C2-88EB-04AA7D190C9E com.example.nestedscrollviewbug --enable-dart-profiling --enable-checked-mode --verify-entry-points --observatory-port=0
[ +251 ms] com.example.nestedscrollviewbug: 9563
[        ] Waiting for observatory port to be available...
[ +574 ms] Observatory URL on device: http://127.0.0.1:61452/uyX3QKQ-XMo=/
[   +8 ms] Caching compiled dill
[ +124 ms] Connecting to service protocol: http://127.0.0.1:61452/uyX3QKQ-XMo=/
[ +222 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:61452/uyX3QKQ-XMo=/.
[  +82 ms] DDS is listening at http://127.0.0.1:61456/uJYpYrwakQw=/.
[  +71 ms] Successfully connected to service protocol: http://127.0.0.1:61452/uyX3QKQ-XMo=/
[  +16 ms] DevFS: Creating new filesystem on the device (null)
[  +21 ms] DevFS: Created new filesystem on the device
(file:///Users/jeduden/Library/Developer/CoreSimulator/Devices/FC0588FD-0538-47C2-88EB-04AA7D190C9E/data/Containers/Data/Application/B693AE56-043D-4B32-90B9-E32923D2C49E/tmp/nestedscrollviewbugW85LE4/nestedscrollviewb
ug/)
[   +1 ms] Updating assets
[  +69 ms] Syncing files to device iPhone 8...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:nestedscrollviewbug/main.dart 8071f511-cc19-416c-ad6a-68e63167b7ab
[        ] <- 8071f511-cc19-416c-ad6a-68e63167b7ab
[  +67 ms] Updating files.
[        ] DevFS: Sync finished
[   +1 ms] Syncing files to device iPhone 8... (completed in 73ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +2 ms] Connected to _flutterView/0x7faff8012220.
[   +3 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on iPhone 8 is available at: http://127.0.0.1:61456/uJYpYrwakQw=/
[ +335 ms] Activating Dart DevTools...
[+3551 ms] Activating Dart DevTools... (completed in 3.6s)
[ +463 ms] The Flutter DevTools debugger and profiler on iPhone 8 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:61456/uJYpYrwakQw=/
```

```
Analyzing nestedscrollviewbug...                                        
No issues found! (ran in 1.3s)
```

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-x64, locale en-NL)
    • Flutter version 2.5.3 at /usr/local/Caskroom/flutter/1.22.4/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jeduden/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/jeduden/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (3 available)
    • SM G950F (mobile) • ce081718db14e52105                   • android-arm64  • Android 9 (API 28)
    • iPhone 8 (mobile) • FC0588FD-0538-47C2-88EB-04AA7D190C9E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 96.0.4664.55
    ! Error: Jan-Eric's iPhone is not connected. Xcode will continue when Jan-Eric's iPhone is connected. (code -13)
    ! Error: Jan-Eric's iPhone is not connected. Xcode will continue when Jan-Eric's iPhone is connected. (code -13)

• No issues found!
```

</details>

**Comment by mamuseferha** [comment] 2021-11-24 10:54
Hi @jeduden, I tested this on the latest stable and master channel and the issue is reproducible.

<details>
<summary>output</summary>

https://user-images.githubusercontent.com/92717368/143225220-bfe8cadb-44ce-4371-ba51-1d861cd36fc1.mp4


</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 2.6.0-12.0.pre.826, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.826 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c1455a23a (5 hours ago), 2021-11-23 21:13:05 -0500
    • Engine revision 539239e256
    • Dart version 2.16.0 (build 2.16.0-42.0.dev)
    • DevTools version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (5 available)
    • SM G975U (mobile)                  • R58M95MA95E                          • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)                 • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 2.6.0-12.0.pre.826, on macOS 11.6.1 20G224 darwin-x64, locale en-US)
    • Flutter version 2.6.0-12.0.pre.826 at /Users/flo/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6c1455a23a (5 hours ago), 2021-11-23 21:13:05 -0500
    • Engine revision 539239e256
    • Dart version 2.16.0 (build 2.16.0-42.0.dev)
    • DevTools version 2.8.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/flo/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (5 available)
    • SM G975U (mobile)                  • R58M95MA95E                          • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 (mobile)                 • EF1251D3-C9C4-475E-9F91-58CD010FDA48 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • macOS 11.6.1 20G224 darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 93.0.4577.63

! Doctor found issues in 1 category.
```

</details>

Thank you

**Comment by lotusgate** [comment] 2021-11-25 15:40
I believe this is a duplicate of an issue I posted some time ago https://github.com/flutter/flutter/issues/91972

**Comment by jeduden** [comment] 2021-11-25 17:47
Since the SliverAppBar's build method configures a SliverPersistentHeader. 
See the  [SliverAppBar implementation](https://github.com/flutter/flutter/blob/e1a96b812ecb4057bd7cc171ff31f66974a2f625/packages/flutter/lib/src/material/app_bar.dart#L1753) 
How about closing one issue and amending the other with the other code sample, so that the person who needs to fix this has all information needed to make a solid fix for all scenarios.

**Comment by lotusgate** [comment] 2021-11-27 14:47
Sorry for the late reply.
I can close my issue, but is it a problem to do so if it has been "labeled for further insights"  as mentioned in [this comment](https://github.com/flutter/flutter/issues/91972#issuecomment-945530883)?

**Comment by jeduden** [comment] 2021-11-27 20:04
Good question. Not sure what the best way forward is to ensure this unexpected behaviour gets fixed soon.

**Comment by Piinks** [comment] 2021-12-01 19:58
Hey @jeduden I think this issue is the same as #91972, so I am going to close it. I'll cross link them so they can both be referenced when someone works on it.

**Closed by Piinks** 2021-12-01 19:58 UTC
Labels: framework, f: scrolling, has reproducible steps, found in release: 2.5, found in release: 2.6
