### ISSUE TITLE
Changing the home screen wallpaper restarts Flutter apps on Android 12+

### ISSUE THREAD

**Issue by AKB0N** [flutter/flutter#133722] opened 2023-08-31 00:23 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run a flutter application on Android 12+ (Used a Pixel 7a)
Background the app and change the wallpaper on the device
Foreground the app
Notice the Flutter activity is recreated, losing the app's state.

### Actual results

when i changing phone wallpaper on my android 13 phone (pixel 7a) any flutter app including my flutter app restarts.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_cache_manager/flutter_cache_manager.dart';
import 'package:flutter_wallpaper_manager/flutter_wallpaper_manager.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  MyAppState createState() => MyAppState();
}

class MyAppState extends State<MyApp> {
  String _platformVersion = 'Unknown';
  String __heightWidth = "Unknown";

  @override
  void initState() {
    super.initState();
    initAppState();
  }

  Future<void> initAppState() async {
    String platformVersion;
    String heightWidth;

    try {
      platformVersion =
          await WallpaperManager.platformVersion ?? 'Unknown platform version';
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    }

    try {
      int height = await WallpaperManager.getDesiredMinimumHeight();
      int width = await WallpaperManager.getDesiredMinimumWidth();
      heightWidth = "Width = $width Height = $height";
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
      heightWidth = "Failed to get Height and Width";
    }

    if (!mounted) return;

    setState(() {
      __heightWidth = heightWidth;
      _platformVersion = platformVersion;
    });
  }

  String url = "https://source.unsplash.com/random";
  Future<void> setWallpaper() async {
    try {
      int location = WallpaperManager.BOTH_SCREEN;
      var file = await DefaultCacheManager().getSingleFile(url);
      final bool result =
          await WallpaperManager.setWallpaperFromFile(file.path, location);
      debugPrint(result.toString());
    } on PlatformException catch (e) {
      if (e.code == '???') {
        //
      }
    } catch (e) {
      //
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('wallpaper app'),
        ),
        body: SingleChildScrollView(
          child: Center(
              child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Image(image: NetworkImage(url), fit: BoxFit.cover),
              ),
              Text('Running on: $_platformVersion\n'),
              const SizedBox(
                height: 10,
              ),
              Text('$__heightWidth\n'),
              const SizedBox(
                height: 10,
              ),
              TextButton(
                  onPressed: () => {setWallpaper()},
                  child: const Text("Set Random Wallpaper")),
              const SizedBox(
                height: 10,
              ),
              TextButton(
                  onPressed: () => {(WallpaperManager.clearWallpaper())},
                  child: const Text("Clear Wallpaper"))
            ],
          )),
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/19143657/20bc70f5-33ae-418d-a10c-6ee52cea1645

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [Version 10.0.22621.2134], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• All Android licenses accepted.
[√] Chrome - develop for the web
[√] Android Studio (version 2022.3)
[√] Android Studio (version 2023.1)
[√] Connected device (3 available)
[√] Network resources

```

</details>

**Comment by darshankawar** [comment] 2023-08-31 10:27
Thanks for the report @AKB0N 
Some of the packages you are using are third party, `flutter_wallpaper_manager` and `flutter_cache_manager`
Does the same behavior persists without using these package code implementation ?

**Comment by darshankawar** [comment] 2023-09-01 06:21
I tried this scenario on Pixel 6 emulator running api 33 using latest master version. With it, I wasn't able to replicate the app restart behavior. Although, I selected the default wallpaper provided by the emulator. While trying to use the wallpapers from below options which I guess represents material YOU, the emulator seems to be hanging:

<img width="220" alt="Screenshot 2023-09-01 at 11 47 53 AM" src="https://github.com/flutter/flutter/assets/67046386/640d9616-5ca2-4ef0-afba-285c6f15702d">

@AKB0N Based on @droplet-js comment above, it seems to be happening on native Android too ? Is there a way for you to check that and confirm ?

**Comment by AKB0N** [comment] 2023-09-01 06:38
> 

i used physical devices with google apps to test this problem not emulator, about @droplet-js comment - this problem fixed in 2022 on native Android but problem still happening in flutter apps

**Comment by AKB0N** [comment] 2023-09-01 07:35
> @AKB0N please test push second page before you unit test

bro i have the first in the world icon pack & wallpapers dashboard made using flutter https://play.google.com/store/apps/developer?id=AKBON and i have more than 1 million downloads and 20K daily active users, this problem is huge and serious problem affecting my apps (business) so i tried everything i can do.

<details>
<summary>this record from my dashboard app tested in Pixel 7a real device</summary>

https://github.com/flutter/flutter/assets/19143657/2fea7547-66ec-40f3-a424-78ad2f5d852a


</details>

**Comment by AKB0N** [comment] 2023-09-03 11:05
@darshankawar

**Comment by darshankawar** [comment] 2023-09-04 07:15
@AKB0N Please don't tag unnecessarily. We are aware of the issue and were investigating it.

We were able to replicate the reported behavior using counter example and as shown below:


https://github.com/flutter/flutter/assets/67046386/fffd27c0-d99b-4d9c-b027-55004ce1157e

Thanks @danagbemava-nc for verifying.

<details>
<summary> stable, master flutter doctor -v </summary>

```

[!] Flutter (Channel stable, 3.13.2, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
    • Flutter version 3.13.2 on channel stable at /Users/nexus/dev/sdks/flutter
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutters/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutter. Consider adding /Users/nexus/dev/sdks/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ff5b5b5fa6 (11 days ago), 2023-08-24 08:12:28 -0500
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
    • IntelliJ at /Users/nexus/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.9559.10

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.8660.185/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.9559.62/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 16.6 20G75
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 3.14.0-14.0.pre.93, on macOS 13.4.1 22F770820d darwin-arm64, locale en-GB)
    • Flutter version 3.14.0-14.0.pre.93 on channel master at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef9befc9da (13 hours ago), 2023-09-03 11:23:20 -0700
    • Engine revision fbc6f4a540
    • Dart version 3.2.0 (build 3.2.0-131.0.dev)
    • DevTools version 2.27.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode-14.3.0.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10406996/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.8660.185/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
    • IntelliJ at /Users/nexus/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/232.9559.62/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (4 available)
    • Pixel 7 (mobile) • 28291FDH2001SA            • android-arm64  • Android 13 (API 33)
    • Nexus (mobile)   • 00008020-001875E83A38002E • ios            • iOS 16.6 20G75
    • macOS (desktop)  • macos                     • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by camsim99** [comment] 2023-09-07 18:44
This seems to be a behavior change made by Android and is outside of Flutter's control. Closing as it's not actionable for us.

**Comment by AKB0N** [comment] 2023-09-07 18:55
but this problem showing only in flutter apps any other apps working fine.

**Comment by AKB0N** [comment] 2023-09-07 18:58
> This seems to be a behavior change made by Android and is outside of Flutter's control. Closing as it's not actionable for us.


but this problem showing only in flutter apps any other apps working fine.

**Comment by camsim99** [comment] 2023-09-07 19:53
@AKB0N What do you mean when you referred to "this problem fixed in 2022 on native Android but problem still happening in flutter apps"?

**Comment by AKB0N** [comment] 2023-09-07 20:12
> @AKB0N What do you mean when you referred to "this problem fixed in 2022 on native Android but problem still happening in flutter apps"?
(Changing the home screen wallpaper restarts Flutter apps on Android 12+) this problem was in native android apps also but fixed by Android Jetpack Compose team.  and you guys after added material 3 to flutter this huge problem start showing, i was android ROM developer and native before become flutter developer so i have that knowledge to tell you this problem is from your side, and you have to fix this bug because it is affecting all flutter apps.

**Comment by AKB0N** [comment] 2023-09-07 20:12
> @AKB0N What do you mean when you referred to "this problem fixed in 2022 on native Android but problem still happening in flutter apps"?

(Changing the home screen wallpaper restarts Flutter apps on Android 12+) this problem was in native android apps also but fixed by Android Jetpack Compose team. and you guys after added material 3 to flutter this huge problem start showing, i was android ROM developer and native before become flutter developer so i have that knowledge to tell you this problem is from your side, and you have to fix this bug because it is affecting all flutter apps.

**Comment by camsim99** [comment] 2023-09-07 20:42
@AKB0N Are you familiar with the fix by the Android Jetpack Compose team? Or can you explain how you know about the fix?

**Comment by AKB0N** [comment] 2023-09-07 21:41
> @AKB0N Are you familiar with the fix by the Android Jetpack Compose team? Or can you explain how you know about the fix?


i don't know how they fixed this problem, if i know how they fixed this problem i will not open this issue.

more info about this bug before fix
https://cs.android.com/android/_/android/platform/frameworks/base/+/49a4a1dfceeebc4b94022827b7e68cc971689c84

flutter developer also reporting here but without any answer from google
https://issuetracker.google.com/issues/199995249?pli=1

**Comment by AKB0N** [comment] 2023-09-11 04:14
@droplet-js bro open new issue it seems these developers are lazy and not doing their job, don't mention this problem exit in android Because they claim that the problem is general without any prior research or testing

**Comment by darshankawar** [comment] 2023-09-12 05:01
@droplet-js 
Based on https://github.com/flutter/flutter/issues/133722#issuecomment-1710616502

**Comment by Hixie** [comment] 2023-09-13 15:42
It looks like this issue is valid, since there are steps to reproduce it.

Typically on Android this kind of thing happens when the application's manifest doesn't list the particular event as one that it can handle. Is there something we should be declaring to do that? Similar to how we have to declare that we handle the phone being rotated, etc.

**Comment by stuartmorgan** [comment] 2023-09-14 16:31
> Is there something we should be declaring to do that? Similar to how we have to declare that we handle the phone being rotated, etc.

The [Android docs about config changes](https://developer.android.com/guide/topics/resources/runtime-changes) specifically say that you can't:
> Some configuration changes always cause the activity to restart. You can't disable them. For example, you can't disable the [dynamic colors change](https://developer.android.com/develop/ui/views/theming/dynamic-colors) introduced in Android 12L (API level 32).

> It looks like this issue is valid, since there are steps to reproduce it.

There are steps to reproduce it, but the OS docs say that it can't be prevented. The mitigation is to restore state, which is app-level, not Flutter-level, so it's not clear how this issue would be actionable.

**Comment by Hixie** [comment] 2023-09-14 16:35
Aha, good find.

Yeah in that case the solution is to implement [restoration](https://master-api.flutter.dev/flutter/services/RestorationManager-class.html) logic in the app (and maybe complain to Android).

**Closed by Hixie** 2023-09-14 16:35 UTC
Labels: platform-android, e: OS-version specific, has reproducible steps, team-android, found in release: 3.13, found in release: 3.14

**Comment by stuartmorgan** [comment] 2023-09-25 15:25
@droplet-js If you believe that the official Android documentation is wrong, please file an issue against Android.

**Comment by Hixie** [comment] 2023-09-25 16:37
If you have a simple example of Compose handling this better than Flutter, we could learn from what Compose does in that case. I would recommend filing a new bug with the minimal example of each demonstrating how one handles it automatically and the other does not.
