### ISSUE TITLE
Sky packages should be able to write unit tests that depend on Sky

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#126] opened 2015-11-09 21:14 UTC
<a href="https://github.com/collinjackson"><img src="https://avatars.githubusercontent.com/u/394889?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [collinjackson](https://github.com/collinjackson)**
_Wednesday Aug 12, 2015 at 21:03 GMT_
_Originally opened as https://github.com/flutter/engine/issues/580_

----

jackson-macpro:playfair jackson$ dart --version
Dart VM version: 1.11.0-dev.3.0 (Thu May 28 03:42:12 2015) on "macos_x64"

jackson-macpro:playfair jackson$ pub run test test/playfair_test.dart 
Wrong script snapshot version, expected '146df3da808a6da22679d25262d18cfb' found '6ab2a2a1aedc6faea804a9c1850edf4b'
00:00 +0 -1: loading test/playfair_test.dart                                                       
  Failed to load "test/playfair_test.dart":
  The built-in library 'dart:sky' is not available on the stand-alone VM.
  'package:playfair/playfair.dart': error: line 7 pos 1: library handler failed
  import 'dart:sky' as sky;
  ^
00:00 +0 -1: Some tests failed.                                                                    

If we included the Sky shell executable in the Sky package we could run these tests.

**Comment by FlutterIssues** [comment] 2015-11-09 21:14
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Wednesday Aug 12, 2015 at 21:54 GMT_

----

Discussed this with @abarth.  There are several problems to solve here.

1.  We do not build Mac binaries for releases, currently.  We need a Mac VM in the cloud (maybe http://www.macincloud.com/ ?) to do so.
2.  Once we build Mac binaries, we don't yet upload them to google storage (like we do linux and android-arm: https://github.com/domokit/sky_engine/blob/master/sky/tools/big_red_button.py#L63), but we could once we build them on every revision.
3.  Even once we have those binaries, we need to `sky_shell` to exit at the right time for Dart's `test_runner` to understand.  See https://github.com/domokit/sky_engine/issues/581.

**Comment by abarth** [comment] 2015-11-18 06:17
Duplicate of #307

**Closed by abarth** 2015-11-18 06:17 UTC
Labels: affects: dev experience, affects: tests
