### ISSUE TITLE
[web]: Scroll Website 

### ISSUE THREAD

**Issue by danielreuven** [flutter/flutter#54049] opened 2020-04-05 18:32 UTC
Flutter web: (Channel beta, v1.15.17, on Microsoft Windows [, locale en-US)

Hello,
I am sharing a video and would like to know how to fix it,
Problem: When I open link from Facebook Messenger I cant scroll back.
Link Site: https://danielreuven.page.link/hello
Link Video: https://firebasestorage.googleapis.com/v0/b/mytoradr.appspot.com/o/video-1586110866.mp4?alt=media&token=b79aea4c-f9e5-4b25-afe2-77ae15a64959

Thanks.

**Comment by codermihirpaldhikar** [comment] 2020-04-06 05:04
Hi, @danielreuven It is working fine on my phone. I suggest you try to rearrange your widget tree structure by adjusting the height width of the child widgets because in most of the cases this problem arises due to mismanagement of the child widgets in single child scroll view

Let me know

**Comment by TahaTesser** [comment] 2020-04-06 08:17
Hi @danielreuven 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-04-27 16:22
@danielreuven 
I can't reproduce it.
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related) and the output of 'flutter doctor -v'  please.

**Closed by VladyslavBondarenko** 2020-04-27 16:22 UTC
Labels: waiting for customer response
