### ISSUE TITLE
On some special screen phones, there will be a transparent view at the top of webview_flutter

### ISSUE THREAD

**Issue by XHL-study** [flutter/flutter#43805] opened 2019-10-30 09:12 UTC
On some special screen phones, there will be a transparent view at the top of webview_flutter

**Responding to click event point misalignment**

This is the test video
[test-vedio.zip](https://github.com/flutter/flutter/files/3789355/test-vedio.zip)

Rendering

1.Screenshot of the target phone
![jieping](https://user-images.githubusercontent.com/22956309/67843843-bc27aa80-fb37-11e9-820d-87bfdf99f4bc.png)

![0791019D3BA89D1763B08D42766B8BA1](https://user-images.githubusercontent.com/22956309/67844466-bc747580-fb38-11e9-8384-a02f65d1f1ba.jpg)

2.Photograph
![camer](https://user-images.githubusercontent.com/22956309/67843900-d19cd480-fb37-11e9-8ff5-fb9ccdf4cd27.jpg)

Target phone parameters
![phon-Info](https://user-images.githubusercontent.com/22956309/67843961-e6796800-fb37-11e9-9ae1-ff8bba69d982.jpg)

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.418], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

this my code
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

class TestWebView extends StatelessWidget {
  static final String routeName = "TestWebView";

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red,
      appBar: AppBar(
        title: Text("test WebView"),
      ),
      body: Column(
        children: <Widget>[
          Container(
            child: Text("sss"),
            width: 100,
            color: Colors.white,
          ),
          Expanded(
              child: WebView(
            initialUrl: "https://www.baidu.com/",
            javascriptMode: JavascriptMode.unrestricted,
            navigationDelegate: (NavigationRequest navigation) {
              if (!navigation.url.startsWith("http")) {
                return NavigationDecision.prevent;
              }
              return NavigationDecision.navigate;
            },
          ))
        ],
      ),
    );
  }
}

```

**Comment by Zazo032** [comment] 2019-10-30 15:19
This is caused because of how Xiaomi's pre-Android 9 phones handle the notch

**Comment by lvchenyang** [comment] 2020-07-03 07:39
I have the same problem in Xiaomi

**Comment by danagbemava-nc** [comment] 2021-08-09 08:57
The issue is not reproducible on the latest `stable 2.2.3` and `master 2.5.0-6.0.pre.29` with `webview_flutter: ^2.0.10`. This was tested on a POCO X3 NFC running Android 11.

@XHL-study @lvchenyang can you please confirm on the latest flutter versions if you are still experiencing this issue?

Thank you
![photo_2021-08-09 08 57 05](https://user-images.githubusercontent.com/88313112/128682012-59f476ff-c0d3-4999-98be-518feb5dad75.jpeg)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.5.0-6.0.pre.29, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.5.0-6.0.pre.29 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6876c52b5b (8 hours ago), 2021-08-08 15:34:09 -0700
    • Engine revision c0e59bc7b6
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```


```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android
      12 (API 31) (emulator)
    • iPhone 12 (mobile)          • F2592D43-5FE3-46BB-8A2B-A38BA468DCE9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google
      Chrome 92.0.4515.131

• No issues found!
```
</details>

**Comment by TahaTesser** [comment] 2021-09-03 10:25
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by TahaTesser** 2021-09-03 10:25 UTC
Labels: e: device-specific, platform-android, framework, plugin, a: fidelity, p: first party, f: gestures, p: webview, has reproducible steps, P5, found in release: 1.20
