### ISSUE TITLE
After entering the emoji using sogou input method in the textfield, then deleting the emoji will leave a question mark

### ISSUE THREAD

**Issue by 2534290808** [flutter/flutter#25446] opened 2018-12-17 06:16 UTC
### After entering the emoji using sogou input method in the textfield, then deleting the emoji will leave a question mark

```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.15063], locale zh-CN)
    • Flutter version 1.0.0 at C:\flutter\flutter
    • Framework revision 5391447fae (2 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by zoechi** [comment] 2018-12-17 09:20
Might be https://github.com/flutter/flutter/issues/24203#issuecomment-441865080

**Comment by zoechi** [comment] 2019-01-04 07:22
Duplicate of #23496

**Closed by zoechi** 2019-01-04 07:22 UTC
Labels: a: text input, engine, framework
