### ISSUE TITLE
Linking to other apps on Android can sometimes cause Flutter to leave leftover content over native content

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#46809] opened 2019-12-11 21:34 UTC
https://b.corp.google.com/issues/146070562.

cc @chinmaygarde

**Comment by xster** [comment] 2020-05-12 19:35
ummm sounds like buffers from a different process is being mixed up. @jason-simmons any ideas? The repros don't seem very straight forward unfortunately.

**Comment by jtmcdole** [comment] 2021-01-19 21:13
Has there been any triage for this?

**Comment by zanderso** [comment] 2021-01-20 22:13
Also https://b.corp.google.com/issues/154530076. @xster was there any follow-up? I am removing the priority so that we take a look at this together at our next triage meeting.

**Comment by xster** [comment] 2021-01-25 16:25
@zanderso no, we haven't reproduced it yet.

**Comment by chinmaygarde** [comment] 2021-01-25 18:54
The instructions in the last comment on the bug are fairly involved and require setting up the application in a test environment. @kf6gpe is going to followup on priorities and a reduced test case.

**Comment by GaryQian** [comment] 2022-10-25 18:00
Since the internal bug was verified as resolved, I will go ahead and close this bug.

**Closed by GaryQian** 2022-10-25 18:00 UTC
Labels: severe: regression, platform-android, engine, customer: stadia (g3), passed first triage, P3
