### ISSUE TITLE
Add Desktop Support To webview_flutter Plugin

### ISSUE THREAD

**Issue by maxwell8888** [flutter/flutter#84635] opened 2021-06-15 15:23 UTC
## Use case

I have a cross platform desktop app which supports Windows, MacOS, and Linux. I would like to embed web content using the webview_flutter plugin, however the plugin only supports Android and IOS, not my target platforms.

## Proposal

Please add desktop support to the webview_flutter plugin.

**Comment by darshankawar** [comment] 2021-06-16 08:09
@maxwell8888 
See below open issues describing your case:

https://github.com/flutter/flutter/issues/41726
https://github.com/flutter/flutter/issues/41725
https://github.com/flutter/flutter/issues/37597

You may subscribe to each of them to know latest updates.
Closing this as duplicate of above linked.

**Closed by darshankawar** 2021-06-16 08:09 UTC
Labels: in triage
