### ISSUE TITLE
Cupertino Icons Gallery hyper text leads to blank site

### ISSUE THREAD

**Issue by AshAman999** [flutter/flutter#90943] opened 2021-09-29 08:02 UTC
### Page URL

https://pub.dev/packages/cupertino_icons

### Describe the problem

On the link for cupertino_icons, on the bottom of the screen, that hypertext links leads to a site that is not working
`Cupertino Icons Gallery` and `glyph map`

![image](https://user-images.githubusercontent.com/57723319/135227405-bd955fcf-b9e3-4f5e-94b8-f774768c657d.png)

### Expected fix

If the hyperlinks have been deprecated then remove it  
else link proper sites to those hyperlinks

**Comment by TahaTesser** [comment] 2021-09-29 10:16
Hi @AshAman999 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/88754
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-29 10:16 UTC
