### ISSUE TITLE
Flutter API website fonts are hard to read

### ISSUE THREAD

**Issue by Doomd** [flutter/flutter#50344] opened 2020-02-01 23:18 UTC
![Screenshot 2020-02-01 16 23 50_edit](https://user-images.githubusercontent.com/10950340/73600618-49501600-4510-11ea-82af-972d41315bb2.png)
This is a relatively trivial issue, and I'm not even sure if this is the right place to complain about it, but I still think it merits attention: 

The font and/or weight of the Flutter API website (for example: [https://api.flutter.dev/flutter/widgets/Expanded-class.html](https://api.flutter.dev/flutter/widgets/Expanded-class.html)) is really not easy on the eyes (at least in Chrome on Windows 10). The italics font especially is hard to read (look below the Properties subheading), and all of the links on the right side of the page aren't too easy to read either. 

When I have to read an API reference website, I want it to be legible without squinting...and since Flutter is a design framework with Material Design baked in, I think it would be more appropriate if the API website espoused the [design philosophy of Material Design](https://material.io/design/guidelines-overview/). In fact, the [Material.io](https://material.io/) website is a great example of a docs/reference website that IS easy to navigate and read. Perhaps API.flutter.dev can follow some of its design language...

That's just my opinion...but in spite of having perfect 20/20 vision, the api.flutter.dev makes me wonder if I need to get my eyes checked. I can't be the only one.

**Comment by kf6gpe** [comment] 2020-02-07 16:39
@sfshaza2 Done! Thanks for the reminder. I was a little overzealous. ;)

**Comment by jcollins-g** [comment] 2020-10-20 16:23
dartdoc's default templates use much more readable fonts/font weights to what Flutter is currently using, so I have closed the related dart-lang/dartdoc#2374 as the weight issue is Flutter specific.   The problem is likely partially caused by the overrides [here](https://github.com/flutter/flutter/blob/master/dev/docs/styles.html) being incomplete as some users mentioned in https://github.com/flutter/flutter/pull/48073.  However given it wasn't clear what the right approach was to fix it, I don't know how or if I should proceed with trying, so I will leave this to Flutter documentation folks to choose what to do.  @dnfield @sfshaza2

**Comment by jcollins-g** [comment] 2020-10-20 16:30
If it is helpful, I could attempt to match Flutter's API docs overrides to the settings used elsewhere on Flutter.dev.

**Comment by dnfield** [comment] 2020-10-20 16:41
@jcollins-g I think that would at least be a good start for us, thanks!

**Comment by nt4f04uNd** [comment] 2021-12-08 11:20
A duplicate of https://github.com/flutter/flutter/issues/47796?

**Comment by nt4f04uNd** [comment] 2021-12-16 22:07
Closing per my previous comment.

**Closed by nt4f04uNd** 2021-12-16 22:07 UTC
Labels: framework, d: api docs, d: website - infra, proposal, passed first triage
