### ISSUE TITLE
Multicast datagram throws an error under iOS

### ISSUE THREAD

**Issue by blucell** [flutter/flutter#30621] opened 2019-04-06 21:49 UTC
## Steps to Reproduce

Listen to a multicast UDP address and listen to its events

```dart
import 'dart:convert';
import 'dart:io';

void loadSSDP() async {
  var socket = await RawDatagramSocket.bind(InternetAddress.anyIPv4, 0);

  socket.broadcastEnabled = true;
  socket.readEventsEnabled = true;
  socket.multicastHops = 50;

  socket.listen((event) {
    final datagram = socket.receive();
    if (datagram == null) return;

    const codec = Utf8Codec();
    final message = codec.decode(datagram.data);
    print('received $message');
  });

  socket.joinMulticast(InternetAddress('239.255.255.250'));
}
```

Callback issuance is expected but it errors instead

## Logs

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: OS Error: Can't assign requested address, errno = 49
#0      _NativeSocket.joinMulticast (dart:io/runtime/binsocket_patch.dart:1151:28)
#1      _RawDatagramSocket.joinMulticast (dart:io/runtime/binsocket_patch.dart:1901:13)
#2      loadSSDP
<asynchronous suspension>
#3      Home.build.<anonymous closure>
#4      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:513
#5      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:568
#6      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:120
#7      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:242
#8      TapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:175
#9      PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:369
#10     Pointer<…>
```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-EG)
    • Flutter version 1.2.1 at /Users/blu/.local/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/blu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.3.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.6156.10

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • iPhone 5s • 8BD171CD-7333-4E55-815E-D6DD16003314 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by zxconan** [comment] 2019-05-22 09:22
Same error, any solution?

**Comment by zxconan** [comment] 2019-05-31 08:48
Hi, @blucell any update about this problem

**Comment by blucell** [comment] 2019-05-31 08:52
No. Probably a permissions problem, as it used to work using an older Flutter version.

**Comment by fangli** [comment] 2019-06-25 10:49
Same error, reproducable.

**Comment by toabi** [comment] 2019-09-13 09:57
Related Ticket: https://github.com/flutter/flutter/issues/16335

**Comment by escamoteur** [comment] 2019-10-01 11:09
I close this here because its a double. Please upvote and follow https://github.com/flutter/flutter/issues/16335

**Comment by jaumard** [comment] 2019-10-08 16:19
hey @escamoteur not really a double, as #16335 is focusing on Android, here I'm focusing on iOS.

**Comment by kingctan** [comment] 2019-11-15 02:51
any update for ios? it's a bug.

**Comment by goderbauer** [comment] 2019-12-18 23:13
This doesn't look like a flutter specific bug. Maybe file it over in the dart repository? https://github.com/dart-lang/sdk

**Closed by goderbauer** 2019-12-18 23:13 UTC
Labels: a: quality, framework, ⌺‬ platform-ios

**Comment by kingctan** [comment] 2019-12-30 10:00
but android is ok using dart:io for udp multicast.  @goderbauer
