### ISSUE TITLE
Flutter abort issue resulted from large memory use of pictures in low-memory iPhones.

### ISSUE THREAD

**Issue by kangwang1988** [flutter/flutter#51046] opened 2020-02-19 16:16 UTC
# Problem description
We have been suffering from the memory issue related to flutter application for a long time, especially when there are lots of high quality pictures like commodity description.
This issue can be still reproduced in latest stable branch easily and is now a severe problem for our application where there are a lot of users who are holding an iPhone with low memory, for example iPhone 6plus.

So how can we avoid this issue in low memory iphone devices efficiently. This issue is not unique for us, but a big common problem for many flutter developers. In our real products, the situation would be more serious as we're generally using flutter in add2app form. In other words, the application contains lot of containers, like web, native and flutter, etc. 

# Demo Repo
I have written a pure flutter application to help reproduce it. You can get it from:
https://github.com/FlutterRepo/image_memory_issue

# Reproduce procedure
It's easy to reproduce by scrolling up and down. See more by my recording:
https://www.youtube.com/watch?v=bdg5Tfm3p-I
You can see an abort at about 0:25.

# Enrivonment
```shell
[✓] Flutter (Channel stable/v1.12.13+hotfix.8, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/kylewong/Codes/Flutter/alibaba-flutter/StableV1.12.13/flutter
    • Framework revision 0b8abb4724 (8 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kylewong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ! Unknown CocoaPods version installed.
        Flutter is unable to determine the installed CocoaPods's version.
        Ensure that the output of 'pod --version' contains only digits and . to be recognized by Flutter.
      To upgrade:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • KyleWong’s iPhone6 Plus •  • ios • iOS 12.4.4
```

@liyuqian 
cc @fydx

**Comment by liyuqian** [comment] 2020-02-19 20:10
This seems to be related with https://github.com/flutter/flutter/issues/19558, #32143, #44510, #48305, and #48775

@kangwang1988 : @dnfield and I have recently looked into a bunch of memory issues related with scrolling a list of images. Many fixes have been merged since the last stable release. Can you please try the tip-of-tree master branch and see if the crash still happens?

**Comment by dnfield** [comment] 2020-02-19 20:38
The relevant fixes here are specifically around scrolling.

However, if you're using lots of high quality pictures, you almost certainly want to look at using https://api.flutter.dev/flutter/painting/ResizeImage-class.html to make sure that you're not decoding the image at full quality only to display it at am uch lower resolution.

**Comment by kangwang1988** [comment] 2020-02-20 02:06
@dnfield 
We have policies to resize images/qualities according to network condition, widget size, screen resolution, memory capacity, etc. However, I don't think this is not the final solution.
Is it possible for us to release images(dart&c++ size) which is not visible when necessary like low memory in iphone6 plus?

**Comment by kangwang1988** [comment] 2020-02-20 02:08
@liyuqian 
Do you think the master branch has a good solution for a list of many images? If so, I can have a try using the master branch.

Also, do you know is it possible for me to check a image widget is not visible and i can release the invisible image memory when necessary?

**Comment by dnfield** [comment] 2020-02-20 02:15
The images should get automatically released once you're no longer refering to them, assuming they are not being held in the ImageCache.

The master branch has changes on it that should improve memory usage in lists of images, but primarily to do with scrolling.  We've also made some engine side changes that should help with more aggressively releasing memory for images that are no longer referenced.

**Comment by kangwang1988** [comment] 2020-02-20 05:18
@dnfield 
However, in a long list, those images are refered. Henceforth, though they're not visible, the memory they refer to are still remain. If the user keep scrolling, the memory will always increase until abort.

**Comment by dnfield** [comment] 2020-02-20 06:16
@kangwang1988 as long as you use a ListView.builder (or otherwise use a lazily loaded list), the images should not be retained beyond a few at the head and tail of what's currently visible on the screen - and whatever is in the image cache.

Are you using a non-lazy listview?

**Comment by dnfield** [comment] 2020-02-20 06:17
Ahh I see in your repo - you're using a raw ListView.  Try switching to ListView.builder.

**Comment by fydx** [comment] 2020-02-20 07:20
I have tried to use ListView.builder. But when I scroll, the occupied memory still increases a lot.
![image](https://user-images.githubusercontent.com/3157294/74909615-a6463a00-53f3-11ea-80be-2228c20d981f.png)

**Comment by dnfield** [comment] 2020-02-20 10:04
@fydx  - that is about what I would expect from a long lazily loaded list of images.  There are ways to get it down further currently:

- Decrease the cache extent on your list to avoid holding on to too many leading/trailing images
- Decrease the resolution at which you cache the images
- Decrease the size of the image cache - but really this should be prevent the image from landing in the cache (https://github.com/flutter/flutter/issues/47380)
- Prevent a user from scrolling too much. E.g. how Instagram on an iPhone works (you scroll a bit, then stop and get a loading indicator, then scroll some more, then stop and get a loading indicator, etc.).
- On master, the framework will prevent images from loading if you're scrolling fast. You can control that with custom scroll physics to make it so that if the user is scrolling _at all_ the image won't load.

I do still think #47380 could help cases like this (e.g. you have a long list of images and you don't want any or most of them to ever end up in the cache).  Otherwise, you're mostly left with decisions to make in the application layer about how to make it hard for the user to consume too much memory.

But on an iPhone, ~300mb should be fine - even on older models, you should be fine up until close to 1gb.

**Comment by kangwang1988** [comment] 2020-02-20 12:30
@dnfield 
Unfortunately not. I've reimplement the list using [ListView.builder](https://github.com/FlutterRepo/image_memory_issue/commit/b472e60cb2830c1a24edb2fd2f74b8f9184498b5) , the issue remains and would abort after launch, even without any taps. I've also made a [screen recording](https://www.youtube.com/watch?v=yKAE1Rywor4) and you can see it clearly. The flutter application in release mode would crash when the memory level is about 600MB, which is a reasonable memory level to be killed by iOS.
See:
https://stackoverflow.com/questions/5887248/ios-app-maximum-memory-budget

**Comment by kangwang1988** [comment] 2020-02-20 12:39
@eseidel 
The memory issue is now a blocker for us to bring flutter to more applications in Alibaba.
In the new application we're working on now, the commodity page consists lot of images(more than before we used in Xianyu) for better description. In an application implemented by native iOS/android, the memory can be managed precisely, in Flutter, the developers can't manage the memory that well and it's the biggest issue for us.
Though flutter has that many advantages claimed, if a Flutter application is easily to abort. It will prevent many developers to use it. The low memory devices in China is still in a large number, we should ensure their experience. 
Please help us to resolve this pure flutter application, thx.

**Comment by kangwang1988** [comment] 2020-02-20 13:56
Update:
After I set the [ImageCache to zero](https://github.com/FlutterRepo/image_memory_issue/commit/b90f01ada0f0d8137ed402688f53bd60a0fbf1fa), the application will not abort at launch.
However, after some scrolling, it [abort again](https://www.youtube.com/watch?v=BupOOqJOoGE).

**Comment by dnfield** [comment] 2020-02-20 15:25
@kangwang1988 can you describe some of the memory management you're able to do outside of flutter that is helping?

**Comment by kangwang1988** [comment] 2020-02-20 15:35
@dnfield 
Are you referring to some memory management works we've done in iOS&Android?

**Comment by dnfield** [comment] 2020-02-20 15:37
Yes

**Comment by kangwang1988** [comment] 2020-02-20 16:41
@dnfield 
I created an example with exactly the same datasources(image urls).
See it at: https://github.com/FlutterRepo/ios_image_demo
The memory footprint is very slow: 
![image](https://user-images.githubusercontent.com/817851/74957667-db2dad80-5442-11ea-8a5a-3c70c179384a.png)
You can see that I didn't do something that special for memory use.

**Comment by kangwang1988** [comment] 2020-02-20 16:43
Also CC @mraleph 
Can you have a look at this issue? Maybe there is something can be done in dart&c++ approach.

**Comment by kangwang1988** [comment] 2020-02-20 16:59
@liyuqian 
Can you give a call graph how so many memory are used in this flutter case? Maybe we can find a way to break the reference when needed(low memory and not visible), and notify c++ side to release the relevant memory?

**Comment by dnfield** [comment] 2020-02-20 22:06
It's unlikely that Dart can help much here -this is much more likely a Skia issue.

I noticed something strange when I dump the memory of your example app.  The UIImages in there report as very small - as in 144 bytes.  It seems like Apple does something funny with image memory accounting for UIImages.  I can't seem to find the bytes anywhere in memory for them in the dump.  I also very strongly suspect that your iOS example is in fact downscaling the images more than the Flutter example (which is not downscaling them at all), but that iOS is doing it for you implicitly whereas Flutter does not.

OTOH, when Skia renders an image, we need to have the texture memory for it resident.  I'm not sure if there's any trick we could do to use the same storage backing that UIImage seems to be allowed to use - perhaps using a PlatformView or something like that for it, but that feels pretty heavy and will mess up compositing.

@chinmaygarde @brianosman might have good ideas on this.

**Comment by liyuqian** [comment] 2020-02-20 22:57
@kangwang1988 : I've done some experiments with iPhone Xr (can't get an iPhone 6 as I'm still quarantined at home), and I think I've found the problem and the solution:

- The immediate cause of OOM is that Flutter is loading too many images since the image height isn't specified, and Flutter probably treats it as 0 and loads all those big images during startup.
- A quick fix would be to specify `height: screenSize?.height ?? 750.0` in `Image.network` constructor. Notice that https://api.flutter.dev/flutter/widgets/Image/height.html suggests to specify both width and height. Such fix drops memory usage from 800MB down to less than 100MB on my iPhone Xr.
- I'm pretty sure that https://github.com/flutter/engine/pull/14265 in the master branch which fixes https://github.com/flutter/flutter/issues/19558 would help your case if `height` isn't specified. Treating height as 0 and quickly loading all those images is very similar to quickly scrolling through a long list of large images. In our fast_scroll_large_images__memory benchmark, the fix reduces the memory usage by as much as 500MB.
- One tool that could help you identify this kind of memory issue is the "allocation profile" tab in Observatory. From the screenshot below, you can see that the app somehow loads a ton of images which use a lot of external memory. <img width="414" alt="Screen Shot 2020-02-20 at 2 45 41 PM" src="https://user-images.githubusercontent.com/22987568/74987369-e1466e80-53ef-11ea-891c-56b7e1c02267.png">


On Flutter's side, I think we should do the following optimization to avoid this kind of memory issue:
- Update the width/height of `Image` when it's decoded, and update its visibility in the `ListView`. If it's hidden, release the widget and `Image`.
- Write a performance test that loads large images without specifying height. Verify that we won't use a ton of memory when the startup fully settles.

@dnfield : do you think the above makes sense?

**Comment by dnfield** [comment] 2020-02-20 23:18
Ahh sure, but we're still going to see far more memory used for images in Flutter than in native iOS because iOS won't tell us how much memory it's really using for images :)

I'm not sure updating the width fo the widget when it's decoded makes sense - it's probably too late and the list view will already think it can just load the whole list's worth of images.  However, we do have another bug filed about allowing users to get image width/height before decoding.

**Comment by liyuqian** [comment] 2020-02-20 23:21
@dnfield : can the image decoding callback trigger some kind of widget rebuild? Since we load images sequentially on the IO thread, maybe the first image's decoding callback can trigger a rebuild or re-layout on the UI thread, and subsequently cancels all later image decoding work on the IO thread.

**Comment by dnfield** [comment] 2020-02-20 23:24
Ah! If we use instruments to profile your demo iOS app, you'll see that scrolling brings the memory up to several hundred megs:

![image](https://user-images.githubusercontent.com/8620741/74989408-1b663f00-53f5-11ea-9835-c83d81e85c00.png)

Is a sample run where I just scrolled a bit down the view.

**Comment by dnfield** [comment] 2020-02-20 23:25
@liyuqian the ListView would still see that it has plenty of room to add all the children you're asking for and eagerly instantiate them.  By the time the first image decoded and you knew its size, it's already too late.

**Comment by kangwang1988** [comment] 2020-02-21 16:30
@liyuqian 
The height approach doesn't work.
[After I specify height for it, when the imagecache is enabled](https://github.com/FlutterRepo/image_memory_issue/commit/da8908738923f221048f2248021983201af8400e), it will abort again at about 600MB in my iPhone6 Plus. It would easily reproduce I scroll up and down quickly.

**Comment by kangwang1988** [comment] 2020-02-21 16:37
@dnfield 
I noticed that most of the memory is external memory, which objects in engine(c++ side) are retaining those memories and how can I release them forcefully when needed? (Maybe on memorywarning etc.)

**Comment by dnfield** [comment] 2020-02-21 18:52
@kangwang1988 - if I update your code to this:

```
              return Image.network(
                testImageUrls[idx],
                width: screenSize?.width ?? 750.0,
                height: 500,
                cacheWidth: screenSize?.width?.toInt() ?? 750,
                cacheHeight: 500,
                fit: BoxFit.fitWidth,
              );
```

The app uses less memory than the native app - and I'm fairly confident that iOS UIImage/your special image package in that app is just doing that under the hood.

I'm not sure if there's a good way for us to make that automatic, but for now it should get you where you need to be.  That's what I meant by the bullet point about cache width/height - if you don't specify it, Flutter will store the full resolution of the image (even if that resolution is much higher than you intend to display at) in memory.

**Comment by dnfield** [comment] 2020-02-21 18:52
With those parameters, I'm having trouble getting the app to use more than 200mb no matter how much I scroll (I'm also testing on master, which avoids decoding images if you scroll too fast).

**Comment by dnfield** [comment] 2020-02-21 18:54
Even without those parameters though, I can't get your sample app (using _just_ height and width, not cacheHeight and cacheWidth) to og much over 250mb (which is only slightly higher than your native demo).  Again,t his is on master - I'm sure the situation is worse on stable.

**Comment by liyuqian** [comment] 2020-02-21 21:35
> [After I specify height for it, when the imagecache is enabled](https://github.com/FlutterRepo/image_memory_issue/commit/da8908738923f221048f2248021983201af8400e), it will abort again at about 600MB in my iPhone6 Plus. It would easily reproduce I scroll up and down quickly.

@kangwang1988 : I guess that you're not using master branch because it crashes easily if you scroll up and down quickly. Please ensure that the fix in https://github.com/flutter/engine/pull/14265 is included in the Flutter version that you're testing.

**Comment by kangwang1988** [comment] 2020-02-22 01:25
@liyuqian 
Got it. All the results I given above is using Flutter version 1.12.13+hotfix.8
I will try using the commit you mentioned.

**Comment by kangwang1988** [comment] 2020-02-22 18:43
@liyuqian 
After I cherry-pick the commit: https://github.com/flutter/engine/pull/14265/commits/212fbbaf82501ece966ecc1919596dc03369dd66

The memory performance is improved, though it could rise to about 300MB+ when scrolling fast, it would reduce to about 200MB.
I will see if this could also show some improvements in our real application.

Thanks.

**Comment by dnfield** [comment] 2020-02-22 19:04
For scrolling you also need https://github.com/flutter/flutter/pull/48536

**Comment by liyuqian** [comment] 2020-02-25 06:00
@kangwang1988 : it seems that there are no longer OOM issues with the latest Flutter version? If so, may I close this and mark this as a duplicate of  https://github.com/flutter/flutter/issues/19558 and https://github.com/flutter/flutter/issues/48775 ?

**Comment by kangwang1988** [comment] 2020-02-25 16:50
@liyuqian 
I would like to keep this issue open until we can verify the issue has been reduced to an acceptable level using the appstore applications. We're about to distribute an application in appstore next week using flutterv1.12.13(With Cherry-picks you recommended)

**Comment by kangwang1988** [comment] 2020-03-03 10:24
@liyuqian @dnfield 
The business developers think the memory performance they acquired in the development phase using release mode is acceptable now.
So I'm closing this issue now. If there is abnormal apm reports later, I'll update this issue.,
Thanks for all the efforts you've done.
Best

**Closed** 2020-03-03 10:24 UTC
Labels: a: images, customer: gold, perf: memory, severe: customer critical, severe: performance

**Comment by vanlooverenkoen** [comment] 2020-09-15 06:41
Still having this issue 800mb+ on an iPhone 7plus in profile mode. This is not workable for us

**Comment by dnfield** [comment] 2020-09-15 19:44
@vanlooverenkoen - there were several suggestions in this issue for how to deal with this sort of problem. If you're having a different issue, you could consider filing a new bug for it with a reproduction. Feel free to tag me.

**Comment by vanlooverenkoen** [comment] 2020-09-15 19:46
@dnfield I already did. https://github.com/flutter/flutter/issues/65834
