### ISSUE TITLE
[image_picker] Android (Redmi A1) crash when accessing gallery

### ISSUE THREAD

**Issue by josh-yang92** [flutter/flutter#136213] opened 2023-10-09 18:31 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Copy & paste the [example code](https://pub.dev/packages/image_picker/example).

Choose images from the gallery.

### Expected results

everything to work without crashing

### Actual results

The app crashes when trying to pick from the gallery.
The crash is inconsistent, sometimes you can go back and forth a few times before crashing but sometimes it crashes straight away.

I have tried with the phone's default gallery (I think it's google's gallery, but I have also tried with a gallery downloaded from the app store).

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
I/BufferQueueProducer(16928): [SurfaceView[app.Lazee/app.Lazee.MainActivity]#1(BLAST Consumer)1](id:422000000001,api:1,p:16928,c:16928) disconnect: api 1
I/BufferQueueProducer(16928): [SurfaceView[app.Lazee/app.Lazee.MainActivity]#1(BLAST Consumer)1](id:422000000001,api:0,p:-1,c:16928) disconnect: api -1
E/OpenGLRenderer(16928): EglManager::makeCurrent mED = 0x1, surface = 0x0, mEC = 0x903da0c0, error = EGL_SUCCESS
I/BufferQueueProducer(16928): [ViewRootImpl[MainActivity]#0(BLAST Consumer)0](id:422000000000,api:1,p:16928,c:16928) disconnect: api 1
I/BLASTBufferQueue(16928): [ViewRootImpl[MainActivity]#0] destructor()
I/BufferQueueConsumer(16928): [ViewRootImpl[MainActivity]#0(BLAST Consumer)0](id:422000000000,api:0,p:-1,c:16928) disconnect
I/BLASTBufferQueue(16928): releaseBufferCallbackThunk bufferId:72705206386689 framenumber:1 blastBufferQueue is dead
I/GED     (16928): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
I/FA      (16928): Application backgrounded at: timestamp_millis: 1696875908848
Lost connection to device.

Exited.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB)
    • Flutter version 3.13.4 on channel stable at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 367f9ea16b (4 weeks ago), 2023-09-12 23:27:53 -0500
    • Engine revision 9064459a8b
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/joshyang/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.82.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • 220733SG (mobile) • TSIN55O7INGALZCQ • android-arm    • Android 12 (API 31)
    • macOS (desktop)   • macos            • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 117.0.5938.149
    ! Error: Browsing on the local area network for Josh’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2023-10-09 20:00
Your logs do not show a crash; please see https://pub.dev/packages/image_picker#android

Closing as a duplicate of https://github.com/flutter/flutter/issues/48016. See in particular https://github.com/flutter/flutter/issues/48016#issuecomment-971918009

**Closed by stuartmorgan** 2023-10-09 20:00 UTC
