### ISSUE TITLE
Web mouse gestures error: Cannot set property '_latestEvent' of undefined

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#46027] opened 2019-12-03 22:33 UTC
I bisected to find that https://github.com/flutter/flutter/pull/44631 introduced this. This does not do anything to the application, but it does log an error whenever there is an update to the mouse (which is very often).

## Steps to Reproduce

1. Create a widget that uses the mouse input events.
2. Move the mouse in a web project to get errors logged in the console

## Logs

```
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
js_primitives.dart:49 The following UnknownJsTypeError was thrown while routing a pointer event:
js_primitives.dart:49 Error: Cannot set property '_latestEvent' of undefined
js_primitives.dart:49 
js_primitives.dart:49 When the exception was thrown, this was the stack:
js_primitives.dart:49 TypeError: Cannot set property '_latestEvent' of undefined
js_primitives.dart:49     at MouseTracker._updateDevices$2$handleUpdatedDevice$targetEvent (http://localhost:8000/main.dart.js:49518:36)
js_primitives.dart:49     at MouseTracker._mouse_tracking$_handleEvent$1 (http://localhost:8000/main.dart.js:49501:12)
js_primitives.dart:49     at Object.eval (eval at Closure_forwardCallTo (http://localhost:8000/main.dart.js:3016:14), <anonymous>:1:40)
js_primitives.dart:49     at PointerRouter._dispatch$3 (http://localhost:8000/main.dart.js:49738:15)
js_primitives.dart:49     at PointerRouter__dispatchEventToRoutes_closure.call$2 (http://localhost:8000/main.dart.js:49799:20)
js_primitives.dart:49     at JsLinkedHashMap.forEach$1 (http://localhost:8000/main.dart.js:32950:16)
js_primitives.dart:49     at PointerRouter._dispatchEventToRoutes$3 (http://localhost:8000/main.dart.js:49758:20)
js_primitives.dart:49     at PointerRouter.route$1 (http://localhost:8000/main.dart.js:49755:13)
js_primitives.dart:49     at WidgetsFlutterBinding.dispatchEvent$2 (http://localhost:8000/main.dart.js:48511:45)
js_primitives.dart:49     at WidgetsFlutterBinding._flushPointerEventQueue$0 (http://localhost:8000/main.dart.js:48500:17)
js_primitives.dart:49 
js_primitives.dart:49 Event:
js_primitives.dart:49   PointerHoverEvent#7b3df
```

```
[✓] Flutter (Channel master, v1.12.17-pre.41, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.17-pre.41 at /usr/local/google/home/chillers/flutter
    • Framework revision 0b2bf99491 (6 hours ago), 2019-12-03 08:13:08 -0800
    • Engine revision faa11214c0
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 e4344a568f)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/local/google/home/chillers/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-stable, build-tools 29.0.2
    • Java binary at: /opt/android-studio-with-blaze-3.5/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio-with-blaze-3.4
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio-with-blaze-3.5
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /opt/intellij-ue-2019.1
    • Flutter plugin version 39.0.2
    • Dart plugin version 191.8423

[✓] VS Code (version 1.39.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by CaseyHillers** [comment] 2019-12-03 23:19
\cc dkwingsmt do you know why this would be occurring?

**Comment by dkwingsmt** [comment] 2019-12-06 01:10
@CaseyHillers There was indeed a refactor to the mouse event system that might have caused this, since it relied more on receiving normalized pointer events. That being said, I was not able to reproduce this error. I created a page with a single FAB and ran it on Web. I'd appreciate it if you can come up with a minimal example.

**Comment by CaseyHillers** [comment] 2019-12-06 01:33
@dkwingsmt I did a bit more playing around. This only occurs on CanvasKit version of Flutter for web, not the DOM implementation.

1. `flutter create mouse_errors`
2. `flutter run -d chrome --dart-define FLUTTER_WEB_USE_SKIA=true`
3. Error is in the Chrome DevTools console

**Comment by CaseyHillers** [comment] 2019-12-06 01:34
Demo: https://v324-dot-flutter-dashboard.appspot.com/build.html#/

**Comment by dkwingsmt** [comment] 2019-12-06 02:27
@CaseyHillers I failed to produce any errors with your implementations, even on your demo page, when I hover mouse onto hoverable objects. The following is all errors I see, but they're one-time on page load:
```
Uncaught TypeError: Cannot read property 'call$3' of null
    at EngineWindow.onPlatformMessage$3 (main.dart.js:44485)
    at Keyboard._handleHtmlEvent$1 (main.dart.js:27433)
    at Keyboard$__closure0.call$1 (main.dart.js:27459)
    at invokeClosure (main.dart.js:2817)
    at main.dart.js:2836

Uncaught TypeError: Cannot read property 'call$3' of null
    at EngineWindow.onPlatformMessage$3 (main.dart.js:44485)
    at Keyboard._handleHtmlEvent$1 (main.dart.js:27433)
    at Keyboard$__closure.call$1 (main.dart.js:27453)
    at invokeClosure (main.dart.js:2817)
    at main.dart.js:2836

Uncaught Object
details: "Not a valid origin for the client: https://v324-dot-flutter-dashboard.appspot.com has not been whitelisted for client ID 308150028417-vlj9mqlm3gk1d03fb0efif1fu5nagdtt.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."error: "idpiframe_initialization_failed"
__proto__: Object
```

**Comment by CaseyHillers** [comment] 2019-12-06 14:31
@dkwingsmt I am testing on Chrome 78 and reproduce on both Mac and Linux.

These's errors are just being printed to the console with `console.log` instead of `console.error`. Are you filtering the dev tools console to only show errors as that would hide this exception?

<img width="481" alt="Screen Shot 2019-12-06 at 6 29 29 AM" src="https://user-images.githubusercontent.com/2148558/70330126-c9e4e580-17f1-11ea-9482-e32f5d002f0b.png">

**Comment by dkwingsmt** [comment] 2019-12-06 18:12
@CaseyHillers I can see the error now. It's probably the filter. Thanks for the help. Let me take a look.

**Comment by dkwingsmt** [comment] 2019-12-09 18:59
I can consistently reproduce this error by refreshing the page (while the mouse is within the page).

PR https://github.com/flutter/flutter/pull/46285 should suppress this error, although it was created to avoid breaking existing tests by allowing pointers that have not been added; however this PR does not solve the root cause, which is the pointer event converter failing to guarantee certain assumptions.

**Comment by dkwingsmt** [comment] 2020-01-04 06:15
I'm closing this issue. Feel free to reopen it if it reappears with the latest framework.

**Closed by dkwingsmt** 2020-01-04 06:15 UTC
Labels: e: web_skia, ☸ platform-web
