### ISSUE TITLE
url_launcher 5.7.8 failing on iOS 14+ when a default browser different than Safari is used.

### ISSUE THREAD

**Issue by renecum** [flutter/flutter#69686] opened 2020-11-03 17:07 UTC
In iOS 14 when you select a default browser other than Safari, the in-app browser behavior doesn't work anymore and instead of opening the URL in for example Chrome (which is my default browser). 

In example code, the app goes to the else statement and throws the error `'Could not launch $url';`

_launchURL() async {
  const url = 'https://flutter.dev';
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}

**Comment by henry2man** [comment] 2020-11-04 11:31
@renecum Probably this is a duplicate of #65936 and should be closed. Regards.

**Comment by pedromassangocode** [comment] 2020-11-05 08:41
Yes, this is definitely a duplicate of https://github.com/flutter/flutter/issues/65936.

**Closed by pedromassangocode** 2020-11-05 08:41 UTC
Labels: team: infra
