### ISSUE TITLE
IndexedStack maintains focused element in non-selected index

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#61659] opened 2020-07-16 20:56 UTC
## Steps to reproduce

1. Run the following app in a desktop context (I was on MacOS):

```dart
import 'dart:ui' show window;

import 'package:flutter/material.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatefulWidget {
  @override
  _BugReportState createState() => _BugReportState();
}

class _BugReportState extends State<BugReport> {
  int selectedIndex = 0;

  _setIndex(int value) {
    setState(() {
      selectedIndex = value;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Localizations(
      locale: Locale('en', 'US'),
      delegates: [
        DefaultWidgetsLocalizations.delegate,
        DefaultMaterialLocalizations.delegate,
      ],
      child: MediaQuery(
        data: MediaQueryData.fromWindow(window),
        child: Directionality(
          textDirection: TextDirection.ltr,
          child: Navigator(
            onGenerateRoute: (RouteSettings settings) {
              return MaterialPageRoute<void>(
                settings: settings,
                builder: (BuildContext context) {
                  return Material(
                    child: IndexedStack(
                      index: selectedIndex,
                      children: [
                        Center(
                          child: Column(
                            children: [
                              TextField(),
                              OutlineButton(
                                onPressed: () => _setIndex(1),
                                child: Text('Switch to index 1'),
                              ),
                            ],
                          ),
                        ),
                        Center(
                          child: OutlineButton(
                            onPressed: () => _setIndex(0),
                            child: Text('Switch to index 0'),
                          ),
                        ),
                      ],
                    ),
                  );
                },
              );
            },
          ),
        ),
      ),
    );
  }
}
```

2. Then focus the text field and enter some text
3. Then click on the button to switch to index 1
4. Then type some more
5. Then click the button to switch back to index 0

## Expected behavior

You expect that when you switch from one index to another in `IndexedStack`, that the content in the index you're switching away from would lose focus and not be focusable anymore.  Thus, in step 4 above, your keystrokes would not be sent to the text field.

## Actual behavior

The text field maintains focus the whole time, so in step 4 above, you're adding to the text in the field even though you can't see it until you click back.

## Other information

In this case, it's also a performance concern, since the blinking cursor is still animating in the inactive index (as seen in the performance overlay).

**Comment by tvolkert** [comment] 2020-07-16 20:56
FYI @gspencergoog

**Comment by tvolkert** [comment] 2020-07-16 20:58
This was filed against 6332bc0fde

**Comment by gspencergoog** [comment] 2020-07-16 21:31
This is probably something needs to be fixed in `IndexedStack`, since it's controlling the visibility. Regular `Stack` children are all shown at once, so for them this behavior is WAI.

You can work around this by wrapping each child with an `ExcludeFocus` widget, and setting the `excluding` attribute to `false` when a child is being shown (which is basically what will need to be done to `IndexedStack`.

**Comment by tvolkert** [comment] 2020-07-16 22:15
ExcludeFocus doesn't fully solve it - it causes the focus to move backwards one.  If I update the code above to have two text fields, then focus the second one, then switch indexes in the stack, then focus moves to the first text field rather than losing it altogether:

```dart
import 'dart:ui' show window;

import 'package:flutter/material.dart';

void main() {
  runApp(BugReport());
}

class BugReport extends StatefulWidget {
  @override
  _BugReportState createState() => _BugReportState();
}

class _BugReportState extends State<BugReport> {
  int selectedIndex = 0;

  _setIndex(int value) {
    setState(() {
      selectedIndex = value;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Localizations(
      locale: Locale('en', 'US'),
      delegates: [
        DefaultWidgetsLocalizations.delegate,
        DefaultMaterialLocalizations.delegate,
      ],
      child: MediaQuery(
        data: MediaQueryData.fromWindow(window),
        child: Directionality(
          textDirection: TextDirection.ltr,
          child: Navigator(
            onGenerateRoute: (RouteSettings settings) {
              return MaterialPageRoute<void>(
                settings: settings,
                builder: (BuildContext context) {
                  return Material(
                    child: IndexedStack(
                      index: selectedIndex,
                      children: [
                        ExcludeFocus(
                          excluding: selectedIndex != 0,
                          child: Center(
                            child: Column(
                              children: [
                                TextField(),
                                TextField(),
                                OutlineButton(
                                  onPressed: () => _setIndex(1),
                                  child: Text('Switch to index 1'),
                                ),
                              ],
                            ),
                          ),
                        ),
                        ExcludeFocus(
                          excluding: selectedIndex != 1,
                          child: Center(
                            child: OutlineButton(
                              onPressed: () => _setIndex(0),
                              child: Text('Switch to index 0'),
                            ),
                          ),
                        ),
                      ],
                    ),
                  );
                },
              );
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by tvolkert** [comment] 2020-07-17 06:26
I spawned https://github.com/flutter/flutter/issues/61700 for the fact that `ExcludeFocus` can still allow focus, and this bug can just be about the work that needs doing in `IndexedStack`

**Comment by TahaTesser** [comment] 2020-07-23 14:07
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.21.0-2.0.pre.95, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-2.0.pre.95 at /Users/tahatesser/Code/flutter_master
    • Framework revision 50b87dc6c3 (19 hours ago), 2020-07-22 11:09:59 -0700
    • Engine revision dcc9a4048d
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 9dca49e71e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 84.0.4147.89

• No issues found!
```

</details>

**Comment by MrAlek** [comment] 2021-04-07 14:39
Bumping since this is still an issue as of today.

Adding on to the discussion, yes you can work around the issue of maintaining focus by wrapping with an `ExcludeFocus` widget. But that breaks autofocus for child widgets.

Imagine you have a stack with two text fields, both with `autofocus: true`. Swapping between them with an `IndexedStack` would ideally switch focus automatically. Yet the actual behavior is that it will work for the first text field, but not when switching the index to the second since autofocus runs on `didChangeDependencies`.

I'm not too well versed how everything Focus-related ties together but perhaps autofocus could be triggered inside `updateRenderObject` somehow?

**Comment by derekedelaney** [comment] 2021-06-25 22:20
I have another scenario where this is an issue. If one of the widgets in my `IndexedStack` has a `ListTile` with a `selectedTileColor` property, that color is persistent in the other widgets in the stack. Here is a DartPad with the example: https://dartpad.dev/f52f76eda42e8cae39aac949d9c0ba63?null_safety=true

**Comment by hpp0hpp** [comment] 2021-09-07 11:06
still a issue as of today, is there alternatives on this?

**Comment by littlepeking** [comment] 2022-02-14 20:48
> Bumping since this is still an issue as of today.
> 
> Adding on to the discussion, yes you can work around the issue of maintaining focus by wrapping with an `ExcludeFocus` widget. But that breaks autofocus for child widgets.
> 
> Imagine you have a stack with two text fields, both with `autofocus: true`. Swapping between them with an `IndexedStack` would ideally switch focus automatically. Yet the actual behavior is that it will work for the first text field, but not when switching the index to the second since autofocus runs on `didChangeDependencies`.
> 
> I'm not too well versed how everything Focus-related ties together but perhaps autofocus could be triggered inside `updateRenderObject` somehow?

I experienced the same issue, I have dynamic indexedStack, once click a button, a new page in indexedStack will be created. And I noticed ExcludeFocus will give me one page focused and next page unfocused and third page focused and 4th page unfocused... Right now I have no idea about it, anybody have idea about it? :(

**Comment by littlepeking** [comment] 2022-02-14 21:34
Hi Guys, I just found a workaround: set all other pages to SizedBox and they will no chance to get focus. except the selected page. hopefully it helpful for others before google fix the issue on indexedStack.

**Comment by darshankawar** [comment] 2022-03-22 12:15
@tvolkert Hi,

I verified this behavior on latest stable and master and it seem to be losing the focus upon switching back to previous index ie the textfield doesn't get the focus anymore after the switch:

<img width="520" alt="Screenshot 2022-03-22 at 5 24 36 PM" src="https://user-images.githubusercontent.com/67046386/159479184-20e965eb-e16d-4963-b5cc-f71b951d2888.png">

Although if we tap in the textfield after coming back, it gets the focus and the input gets appended to the original input added in step 2.

Can you confirm if this is the expected behavior and whether issue can be closed as fixed ?

<details>
<summary> stable, master  flutter doctor -v </summary>

```

[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 2.10.3 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (11 hours ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


[✓] Flutter (Channel master, 2.13.0-0.0.pre.191, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.191 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 69b92f0452 (3 minutes ago), 2022-03-21 21:25:09 -0700
    • Engine revision e6233bd30b
    • Dart version 2.17.0 (build 2.17.0-223.0.dev)
    • DevTools version 2.11.4

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.


```

</details>

**Closed** 2022-04-12 13:19 UTC
Labels: waiting for customer response, framework, a: desktop, f: focus, has reproducible steps, P4, found in release: 1.21
