### ISSUE TITLE
[web] Clickhandler on TextField has uninuitive bahaviour

### ISSUE THREAD

**Issue by masseelch** [flutter/flutter#77049] opened 2021-03-02 09:04 UTC
`TextField` does not handle text selection on clicks like I'd expect it would. Double clicking a word in a sentence does highlight that word like expected. On tripple click i'd expect selction of the whole string in the field. 

Double clicking in the field, but not on a word, should select the last word in the string. Triple clicking should select the whole text.

## Steps to Reproduce
Reproducible example:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Padding(
          padding: EdgeInsets.all(16),
          child: TextField(),
        ),
      ),
    );
  }
}
```

**Expected results:** Triple click (anywhere in the field) to select the whole text in the field.

**Actual results:** Triple click selects a word after the first two clicks (if cursor is above a word), the third one then deselects it again.

<details>
  <summary>Logs</summary>

```
» flutter run -d chrome --verbose
[  +79 ms] executing: [/opt/flutter-beta/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 044f2cf5607a26f8818dab0f766400e85c52bdff
[   +1 ms] executing: [/opt/flutter-beta/] git tag --points-at 044f2cf5607a26f8818dab0f766400e85c52bdff
[  +31 ms] Exit code 0 from: git tag --points-at 044f2cf5607a26f8818dab0f766400e85c52bdff
[        ] 1.26.0-17.8.pre
[  +61 ms] executing: [/opt/flutter-beta/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/opt/flutter-beta/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +80 ms] executing: [/opt/flutter-beta/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +109 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +98 ms] executing: /home/jcl/Android/Sdk/platform-tools/adb devices -l
[  +31 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +120 ms] executing: /home/jcl/Android/Sdk/platform-tools/adb devices -l
[  +12 ms] Skipping pub get: version match.
[ +180 ms] Generating /home/jcl/Code/playground/bug/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +106 ms] List of devices attached
[   +3 ms] List of devices attached
[ +115 ms] Launching lib/main.dart on Chrome in debug mode...
[ +140 ms] Updating assets
[ +119 ms] Waiting for connection from debug service on Chrome...
[ +165 ms] <- reset
[   +5 ms] /opt/flutter-beta/bin/cache/dart-sdk/bin/dart --disable-dart-dev /opt/flutter-beta/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root /opt/flutter-beta/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.SOJQLY/flutter_tool.DCVZNG/app.dill --libraries-spec file:///opt/flutter-beta/bin/cache/flutter_web_sdk/libraries.json --packages
/home/jcl/Code/playground/bug/.dart_tool/package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.SOJQLY/flutter_tools.TCKXTW --filesystem-scheme org-dartlang-app --initialize-from-dill
build/c7922d95bf4a2462b75c84a97c312edb.cache.dill.track.dill --platform file:///opt/flutter-beta/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[  +21 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+23112 ms] Waiting for connection from debug service on Chrome... (completed in 23.3s)
[        ] Synced 29.1MB.
[        ] <- accept
[        ] Caching compiled dill
[ +118 ms] Using Google Chrome 88.0.4324.182 

[ +325 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:41433/devtools/browser/bc76506e-624d-49c7-9c67-8bf36513b99e
[ +765 ms] DwdsInjector: Received request for entrypoint at http://localhost:42591/main_module.bootstrap.js
[   +8 ms] MetadataProvider: Loading debug metadata...
[  +62 ms] MetadataProvider: Loaded debug metadata
[  +16 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:42591/main_module.bootstrap.js
[+2851 ms] DevHandler: Debug service listening on ws://127.0.0.1:42329/UUGkAwMSQXI=/ws

[   +9 ms] Debug service listening on ws://127.0.0.1:42329/UUGkAwMSQXI=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
```

```
» flutter analyze
Analyzing bug...                                                        
No issues found! (ran in 3.8s)
```

```
» flutter doctor -v
[✓] Flutter (Channel beta, 1.26.0-17.8.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-17.8.pre at /opt/flutter-beta
    • Framework revision 044f2cf560 (6 days ago), 2021-02-24 13:02:05 -0800
    • Engine revision 042c82b02c
    • Dart version 2.12.0 (build 2.12.0-259.16.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /home/jcl/Android/Sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.182

! Doctor found issues in 1 category.
```
I have Android Studio installed, but in a different path than flutter expects. I didnt fix this, since it doesnt bug me nor does it create any issues.

</details>

**Comment by TahaTesser** [comment] 2021-03-02 10:56
Hi @masseelch 
I can reproduce this behaviour, duplicate of https://github.com/flutter/flutter/issues/63576
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-03-02 10:56 UTC
Labels: in triage

**Comment by masseelch** [comment] 2021-03-02 11:35
Ah, didnt see that. Thanks for noting and sorry.
