### ISSUE TITLE
[tool_crash] SocketException: Send failed, OS Error: No route to host, errno = 65

### ISSUE THREAD

**Issue by hubaib33** [flutter/flutter#158457] opened 2024-11-11 16:57 UTC
## Command
```sh
flutter --no-color run --machine --track-widget-creation --device-id=00008020-001D59393446002E --start-paused --dart-define=flutter.inspector.structuredErrors=true lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
SocketException: Send failed, OS Error: No route to host, errno = 65
```console
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1275:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2590:15)
#2      MDnsClient.lookup (package:multicast_dns/multicast_dns.dart:219:22)
#3      MDnsVmServiceDiscovery._pollingVmService (package:flutter_tools/src/mdns_discovery.dart:232:66)
<asynchronous suspension>
#4      MDnsVmServiceDiscovery.firstMatchingVmService (package:flutter_tools/src/mdns_discovery.dart:188:56)
<asynchronous suspension>
#5      MDnsVmServiceDiscovery.getVMServiceUriForLaunch (package:flutter_tools/src/mdns_discovery.dart:433:50)
<asynchronous suspension>
#6      Future.any.onValue (dart:async/future.dart:628:5)
<asynchronous suspension>
```
```console
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1 24B83 darwin-x64, locale en-US)
    • Flutter version 3.24.3 on channel stable at /usr/local/Caskroom/flutter/2.2.3/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (9 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915915-b509.11)

[✓] VS Code (version 1.94.2)
    • VS Code at /Users/user/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension version 3.98.0

[✓] Connected device (4 available)
    • iPhone (mobile)        • 00008020-001D59393446002E • ios            • iOS 17.7.1 21H216
    • User’s iPhone (mobile) • 00008030-001A58C811F2802E • ios            • iOS 18.0.1 22A3370
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 15.1 24B83 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 130.0.6723.117

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 7482962148e8d758338d8a28f589f317e1e42ba4
### Plugins
connectivity_plus-6.0.5
file_picker-8.1.4
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
flutter_credit_card-master
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_plugin_android_lifecycle-2.0.17
geolocator-13.0.1
geolocator_android-4.6.1
geolocator_apple-2.3.7
geolocator_web-4.1.1
geolocator_windows-0.2.3
google_maps_flutter-2.9.0
google_maps_flutter_android-2.14.6
google_maps_flutter_ios-2.13.0
google_maps_flutter_web-0.5.10
image_cropper-8.0.2
image_cropper_for_web-6.0.2
image_picker-1.1.2
image_picker_android-0.8.9+3
image_picker_for_web-3.0.5
image_picker_ios-0.8.9+2
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
map_location_picker-1.3.1
path_provider-2.1.4
path_provider_android-2.2.2
path_provider_foundation-2.3.2
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.3.1
permission_handler_android-12.0.5
permission_handler_apple-9.4.4
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
pointer_interceptor-0.10.1+2
pointer_interceptor_ios-0.10.1
pointer_interceptor_web-0.10.2+1
share_plus-10.1.0
sqflite-2.3.3+1
url_launcher_linux-3.1.1
url_launcher_web-2.3.3
url_launcher_windows-3.1.2
video_compress-3.1.3
video_thumbnail-0.5.3

**Comment by huycozy** [comment] 2024-11-12 05:44
Duplicate of https://github.com/flutter/flutter/issues/150131.

**Closed by huycozy** 2024-11-12 05:44 UTC
Labels: in triage

**Comment by jmagman** [comment] 2024-11-14 21:09
@hubaib33 Can you confirm this is fixed after following these instructions?

System Settings -> Privacy & Security -> Local Network -> [Find your IDE] -> Toggle ON, then restart your phone.
