### ISSUE TITLE
package info plugin - android build deprecation warning

### ISSUE THREAD

**Issue by danwulff** [flutter/flutter#29772] opened 2019-03-21 23:51 UTC
After adding the package info plugin to a new flutter application (Stable Channel, migrated to androidX) a deprecation warning is present when running a build (Android only).

The warning presented:
> Note: /Users/dwulff/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+2/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.

### option 1)
- clone https://github.com/danwulff/flutter_package_info_deprecation.git
- run `flutter run`

### option 2)
(using stable channel, v1.2.1)
- run `flutter create ___`
- migrate to AndroidX using Android Studio
- add `package_info: 0.4.0+2` to pubspec.yaml
- run `flutter run` in a terminal

## Logs

flutter run
```
$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                              0.7s
Resolving dependencies...                                           1.2s
Note: /Users/dwulff/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+2/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        11.8s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         1.4s
D/EGL_emulation(13729): eglMakeCurrent: 0xec0f6340: ver 3 0 (tinfo 0xd7135320)
D/        (13729): HostConnection::get() New Host Connection established 0xec495540, tid 13752
D/EGL_emulation(13729): eglMakeCurrent: 0xec0f5e60: ver 3 0 (tinfo 0xec4832a0)
Syncing files to device Android SDK built for x86...             1,794ms

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:57437/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/dwulff/development/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dwulff/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/dwulff/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by dwach414** [comment] 2019-03-29 16:14
I have the same issue.

**Comment by danwulff** [comment] 2019-04-01 20:37
I originally opened since #28155 was closed.
It looks like that ^ issue got reopened for some reason?

**Comment by apaatsio** [comment] 2019-04-21 22:33
The `info.versionCode` is the culprit.

```java
  private static long getLongVersionCode(PackageInfo info) {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
      return info.getLongVersionCode();
    }
    //noinspection deprecation
    return info.versionCode;
  }
```

Source: https://github.com/flutter/plugins/blob/b82ae1a6624e80d49f085b0f5ba42bfc2a44443a/packages/package_info/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java#L62

**Comment by wendyadi** [comment] 2019-07-07 12:07
Same issue here

https://developer.android.com/reference/android/content/pm/PackageInfo#versionCode

**Comment by spidgorny** [comment] 2019-07-14 17:07
Is there a workaround?

**Comment by jmagman** [comment] 2019-11-12 19:02
Looks like a duplicate of https://github.com/flutter/flutter/issues/28772.

**Closed by jmagman** 2019-11-12 19:02 UTC
Labels: a: build, a: error message, p: package_info, ▣ platform-android
