### ISSUE TITLE
Firebase In-App Messaging plugin

### ISSUE THREAD

**Issue by maxhelskens** [flutter/flutter#23463] opened 2018-10-24 14:22 UTC
Hi,

Are there any plans to create a [Firebase In-App Messaging](https://firebase.google.com/products/in-app-messaging/) flutter plugin?

Could come in handy!

**Comment by zoechi** [comment] 2019-02-19 11:02
Closing as duplicate of #24933

Please thumbs-up and subscribe there.

**Closed by zoechi** 2019-02-19 11:02 UTC
Labels: p: firebase, p: first party, plugin, severe: new feature

**Comment by kroikie** [comment] 2019-10-13 18:44
@maxhelskens

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/598. Any further collaboration will be done there.
