### ISSUE TITLE
[webview_flutter]MethodChannel has a memory leak.

### ISSUE THREAD

**Issue by gzjaychen** [flutter/flutter#75141] opened 2021-02-01 13:16 UTC
webview_flutter: 1.0.7

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.6 19G2021 darwin-x64,
    locale zh-Hans-CN)
    • Flutter version 1.22.4 at
      /Users/chenjiangfeng/.terra/caches/sdk/v1.22.4-stable/flutter
    • Framework revision 1aafb3a8b9 (3 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/chenjiangfeng/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/chenjiangfeng/Library/Android/sdk
    • Java binary at: /Applications/Android Studio
      4.1.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio 4.1.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • MI 8 (mobile) • 76981e2b • android-arm64 • Android 10 (API 29)
```

</details>
flutter page => webview => return to flutter page => webview

1 webview leaks 1 instance
Both android and iOS.

webview_method_channel.dart
class MethodChannelWebViewPlatform
_channel.setMethodCallHandler(null) should be called when webview disposes.

demo:
https://github.com/gzjaychen/plugins/tree/webview_flutter_channel_leak/packages/webview_flutter

after I enter and exit webview 23 times
![image](https://user-images.githubusercontent.com/7587713/106462055-8b6bb900-64d0-11eb-9ee4-5dc349027f68.png)

**Comment by darshankawar** [comment] 2021-02-02 07:48
@gzjaychen 
I tried the official `webview_flutter` plugin [example](https://pub.dev/packages/webview_flutter/example) which loads `www.flutter.dev` on latest stable and played around to open different links and went back to home page. When exactly do you see the spike / memory leak ?
Also, can you upgrade to latest stable (1.22.6) and try again to see if you still see the same behavior ?

**Comment by gzjaychen** [comment] 2021-02-02 08:09
@darshankawar 
1.22.6 still see the same behavior.
I modify the example, home page is not a webview. You can check the example which I fork from official plugin example.
https://github.com/gzjaychen/plugins/tree/webview_flutter_channel_leak/packages/webview_flutter

**Comment by darshankawar** [comment] 2021-02-02 10:14
<img width="454" alt="Screenshot 2021-02-02 at 3 41 42 PM" src="https://user-images.githubusercontent.com/67046386/106585448-5c575500-656d-11eb-81cb-462af1493430.png">

E/chromium( 7829): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw
E/chromium( 7829): [ERROR:tile_manager.cc(806)] WARNING: tile memory limits exceeded, some content may not draw


<details>
<summary>flutter doctor -v</summary>

```


[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.6 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9b2d32b605 (11 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

 
[✓] Connected device (2 available)            
    • SM A260G (mobile)            • 5200763ebcfa861f • android-arm • Android
      8.1.0 (API 27)
    • AOSP on IA Emulator (mobile) • emulator-5554    • android-x86 • Android 9
      (API 28) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2021-08-18 11:08
I cannot reproduce this issue on `master 2.5.0-7.0.pre.129` and `stable 2.2.3` with `webview_flutter: ^2.0.12`.

I tested the app in both `profile` and `debug` mode and in all cases there was no spike in memory used.

Labelling as fixed and closing the issue. If anyone still experiences this issue, kindly leave a comment and provide `flutter doctor -v` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and I will reopen it. 

Thank you

See screenshots below:
 
`profile` mode
![Screenshot 2021-08-18 at 10 55 57](https://user-images.githubusercontent.com/88313112/129886631-bc12a500-b67f-4a55-be90-50dec93e0e36.png)

`debug` mode
![Screenshot 2021-08-18 at 11 07 53](https://user-images.githubusercontent.com/88313112/129887981-b4c04562-a051-4e36-bd34-f24f625d9a52.png)


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.129, on macOS 11.5.1 20G80
    darwin-arm, locale en-GH)
    • Flutter version 2.5.0-7.0.pre.129 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 29c089c2ed (80 minutes ago), 2021-08-18 01:37:04 -0400
    • Engine revision b13c765675
    • Dart version 2.15.0 (build 2.15.0-24.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.6 18F72
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.1 20G80 darwin-arm, locale
    en-GH)
    • Flutter version 2.2.3 at /Users/nexus/dev/sdks/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile)    • 5dd3be00                  • android-arm64  •
      Android 11 (API 30)
    • Nexus’ IPhone (mobile) • 00008020-001875E83A38002E • ios            • iOS
      14.6
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 92.0.4515.131

• No issues found!
```

</details>

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home()
    );
  }
}


class Home extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('MethodChannel Leak')),
      body: Center(
        child: TextButton(
          onPressed: () {
            Navigator.of(context).push(
                MaterialPageRoute(builder: (BuildContext context) => WebViewPage())
            );
          },
          child: Text('Open WebView'),
        ),
      ),
    );
  }
}

class WebViewPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('WebView Page')),
      body: WebView(
        initialUrl: 'https://google.com',
      ),
    );
  }
}
```
</details>

**Closed by danagbemava-nc** 2021-08-18 11:08 UTC
Labels: platform-android, plugin, p: first party, p: webview, perf: memory, has reproducible steps, P4, found in release: 1.22
