### ISSUE TITLE
[proposal] provide a way to add spacing between the text and its decoration

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#79180] opened 2021-03-27 01:57 UTC
Currently it is not possible to add padding between the text and its underline decoration. For example the code bellow generates:

![Screen Shot 2021-03-27 at 02 55 33](https://user-images.githubusercontent.com/33294549/112706940-e8b83100-8ea7-11eb-9ea9-b5b46a848eb4.png)

### Proposal

Provide a way to cchange the underline vertical offset/margin.

<details>
<summary>code sample</summary>

```dart
                Text(
                  'Start Listening To Songs',
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    wordSpacing: 2,
                    decoration: TextDecoration.underline,
                  ),
                )
```
</details>

**Comment by nucl123** [comment] 2021-03-28 11:24
Try this:

Text(
            "Forgot Password?",
            style: TextStyle(
              shadows: [
                Shadow(
                    color: Colors.black,
                    offset: Offset(0, -5))
              ],
              color: Colors.transparent,
              decoration:
              TextDecoration.underline,
              decorationColor: Colors.blue,
              decorationThickness: 4,
              decorationStyle:
              TextDecorationStyle.dashed,
            ),
          )

**Comment by darshankawar** [comment] 2021-03-29 08:33
Closing this as duplicate of https://github.com/flutter/flutter/issues/30541

**Closed by darshankawar** 2021-03-29 08:33 UTC
Labels: in triage
