### ISSUE TITLE
[Web] : TextField hidden while opening the keyboard in mobile browser

### ISSUE THREAD

**Issue by Sasikumar3595** [flutter/flutter#73171] opened 2020-12-31 13:09 UTC
## Steps to Reproduce

I was created the flutter project with multiple pages and each pages have buttons for navigate to other pages. In the project some of pages have textfield for getting user inputs and the textfields hided when focus the textfield

Note: This only occurred on mobile browser(because of keyboard opening)

Replication steps:
- Run the sample with below attached file on mobile browser
- Click popup page button and focus 'Add Title' text file

**Expected results:** 

Textfield will shown when keyboard opening

**Actual results:** 

Textfield does not shown when keyboard opening

Sample Main.dart file: [main.dart.zip](https://github.com/flutter/flutter/files/5757287/main.dart.zip)
Issue replication video: [Issue replication video](https://user-images.githubusercontent.com/44917578/103411708-62859a80-4b97-11eb-9169-93d21280accb.mp4)

**Comment by iapicca** [comment] 2021-01-01 11:23
possible duplicate of https://github.com/flutter/flutter/issues/56039

**Comment by Sasikumar3595** [comment] 2021-01-04 05:36
@iapicca ,

The mentioned issue not depends on resizeToAvoidBottomInset property(https://github.com/flutter/flutter/issues/56039), because the issue reproduced on both(true and false) value with resizeToAvoidBottomInset.

**Comment by darshankawar** [comment] 2021-01-04 07:05
@Sasikumar3595 
Can you also provide `flutter doctor -v` ?

**Comment by Sasikumar3595** [comment] 2021-01-04 07:15
@darshankawar 

Find the flutter doctor -v details as below,

<details>
<summary> Flutter doctor details </summary>

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.3 19D76 darwin-x64, locale en-US)
    • Flutter version 1.24.0-10.2.pre at /Users/SasikumarArumugam/Documents/flutter
    • Framework revision 022b333a08 (7 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

Error executing simctl: 126
/Applications/Xcode.app/Contents/Developer/usr/bin/simctl: line 15: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/Resources/bin/simctl: No such file or directory
/Applications/Xcode.app/Contents/Developer/usr/bin/simctl: line 15: exec: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/Resources/bin/simctl: cannot execute: No such file or directory

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/SasikumarArumugam/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • Moto G 5S Plus (mobile) • ZY322J5MHK • android-arm    • Android 8.1.0 (API 27)
    • Web Server (web)        • web-server • web-javascript • Flutter Tools
    • Chrome (web)            • chrome     • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 2 categories.
```
</details>

**Comment by darshankawar** [comment] 2021-01-04 11:55
@Sasikumar3595 
So you are running this on web and opening the localhost url in mobile browser ? Can you provide the steps to run this on mobile browser ?
Also, can you upgrade to latest beta (1.25) and check if you still get same behavior ?

**Comment by Sasikumar3595** [comment] 2021-01-05 13:42
@darshankawar,

Yes, i was running the sample on web and opening the localhost url in mobile browser.

Steps for running in mobile browser:

- Run the sample on web by command(flutter run -d chrome --web-port 5000 --web-hostname 0.0.0.0)
- Open the localhost url(0.0.0.0:5000) in mobile browser

**Comment by darshankawar** [comment] 2021-01-06 06:54
Issue replicable on latest master.

<img width="377" alt="Screenshot 2021-01-06 at 12 20 53 PM" src="https://user-images.githubusercontent.com/67046386/103738336-de5d6800-5019-11eb-8875-360efecb7cdf.png">

<img width="545" alt="Screenshot 2021-01-06 at 12 21 25 PM" src="https://user-images.githubusercontent.com/67046386/103738340-e1585880-5019-11eb-828e-e0c84ac67442.png">
<img width="374" alt="Screenshot 2021-01-06 at 12 21 59 PM" src="https://user-images.githubusercontent.com/67046386/103738343-e1585880-5019-11eb-8eeb-a8b060db5ff7.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.179, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.179 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision a293c82251 (22 hours ago), 2021-01-05 04:04:03 -0500
    • Engine revision b7352132cd
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • SM A260G (mobile)           • 5200763ebcfa861f • android-arm    • Android
      8.1.0 (API 27)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86    • Android
      11 (API 30) (emulator)
    • macOS (desktop)             • macos            • darwin-x64     • Mac OS X
      10.15.4 19E2269 darwin-x64
    • Chrome (web)                • chrome           • web-javascript • Google
      Chrome 87.0.4280.88

! Doctor found issues in 1 category.


```

</details>

**Comment by Indumathi1195R** [comment] 2021-02-02 04:23
Hi Team,

Any update on this?

Regards,
Indumathi R

**Comment by maheshmnj** [comment] 2023-01-11 04:50
Hello @Sasikumar3595, I verified the issue on master 3.7  and it is no longer reproducible, So I believe the issue is fixed.

https://user-images.githubusercontent.com/31410839/211720171-4752d271-348c-4bf7-b80d-d2a62e4960c9.mov

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      title: 'Navigation Page Example',
      home: OverviewPage(),
    ),
  );
}

class OverviewPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Overview Page'),
      ),
      body: OutputContainer(),
    );
  }
}

class OutputContainer extends StatefulWidget {
  @override
  OutputContainerState createState() => OutputContainerState();
}

class OutputContainerState extends State<OutputContainer> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: OutputContent());
  }
}

class OutputContent extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Calendar Demo',
        home: Scaffold(
            resizeToAvoidBottomInset: false,
            body: Center(
              child: ElevatedButton(
                child: Text('Popup page'),
                onPressed: () {
                  Navigator.push<Widget>(
                    context,
                    MaterialPageRoute(
                        builder: (BuildContext context) => DemoPage()),
                  );
                },
              ),
            )));
  }
}

class DemoPage extends StatefulWidget {
  @override
  _DemoPageState createState() => _DemoPageState();
}

class _DemoPageState extends State<DemoPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.red,
        leading: IconButton(
          icon: const Icon(
            Icons.close,
            color: Colors.white,
          ),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
      ),
      body: ListView(padding: const EdgeInsets.all(0), children: <Widget>[
        ListTile(
          contentPadding: const EdgeInsets.fromLTRB(5, 0, 5, 5),
          leading: const Text(''),
          title: TextField(
            controller: TextEditingController(text: ''),
            onChanged: (String value) {
              final String _text = value;
            },
            keyboardType: TextInputType.multiline,
            maxLines: null,
            style: TextStyle(
                fontSize: 25, color: Colors.black, fontWeight: FontWeight.w400),
            decoration: const InputDecoration(
              border: InputBorder.none,
              hintText: 'Add title',
            ),
          ),
        ),
        const Divider(
          height: 1.0,
          thickness: 1,
        ),
      ]),
    );
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
</details>

Closing as fixed. Incase you still encounter the issue, then please feel free to write in the comments and we will reopen it.

Thank you.

**Closed by maheshmnj** 2023-01-11 04:50 UTC
Labels: a: text input, engine, platform-web, has reproducible steps, P4, found in release: 1.26
