### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by unibite1** [flutter/flutter#110593] opened 2022-08-30 16:02 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1734:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2245:21)
#2      VmService.getIsolate (package:vm_service/src/vm_service.dart:1974:7)
#3      FlutterVmService.getIsolateOrNull (package:flutter_tools/src/vmservice.dart:903:20)
#4      FlutterVmService.findExtensionIsolate (package:flutter_tools/src/vmservice.dart:868:51)
<asynchronous suspension>
#5      FlutterResidentDevtoolsHandler._waitForExtensionsForDevice (package:flutter_tools/src/resident_devtools_handler.dart:181:7)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
<asynchronous suspension>
#7      FlutterResidentDevtoolsHandler._devicesWithExtensions (package:flutter_tools/src/resident_devtools_handler.dart:171:41)
<asynchronous suspension>
#8      FlutterResidentDevtoolsHandler.hotRestart (package:flutter_tools/src/resident_devtools_handler.dart:248:54)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.17763.3287], locale en-GB)
    • Flutter version 3.0.5 at D:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (7 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.70.2)
    • VS Code at C:\Users\UNIBITE\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.17763.3287]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 104.0.5112.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f1875d570e39de09040c8f79aa13cc56baab8db1
### Plugins
cloud_firestore-3.4.4
cloud_firestore_web-2.8.4
firebase_auth-3.6.3
firebase_auth_web-4.2.3
firebase_core-1.20.1
firebase_core_web-1.7.1
firebase_database-9.1.1
firebase_database_web-0.2.1+3
firebase_storage-10.3.5
firebase_storage_web-3.3.3
path_provider-2.0.11
path_provider_android-2.0.19
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.1.2

**Comment by danagbemava-nc** [comment] 2022-08-31 07:22
Closing this as a duplicate of https://github.com/flutter/flutter/issues/101962.

Kindly upvote the original issue.

Thank you

**Closed by danagbemava-nc** 2022-08-31 07:22 UTC
Labels: in triage
