### ISSUE TITLE
[tool_crash] FormatException

### ISSUE THREAD

**Issue by lakshmanakumar-v** [flutter/flutter#143518] opened 2024-02-15 12:21 UTC
## Command
```
flutter create first_app
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FormatException
```
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      CreateBase._computeTemplateManifest (package:flutter_tools/src/commands/create_base.dart:668:48)
#7      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart:656:43)
#8      CreateBase._templateManifest (package:flutter_tools/src/commands/create_base.dart)
#9      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:481:25)
#10     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:506:29)
#11     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:361:37)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.19045.2006], locale en-IN)
    [32m•[39m Flutter version 3.16.9 on channel stable at C:\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 41456452f2 (3 weeks ago), 2024-01-25 10:06:23 -0800
    [32m•[39m Engine revision f40e976bed
    [32m•[39m Dart version 3.2.6
    [32m•[39m DevTools version 2.28.5

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at C:\Users\LENOVO\AppData\Local\Android\sdk
    [32m•[39m Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    [33m![39m Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[33m[!][39m Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.33)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    [32m•[39m Visual Studio Build Tools 2019 version 16.11.34407.143
    [31m✗[39m The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.

[32m[✓][39m Android Studio (version 2023.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[32m[✓][39m VS Code (version 1.86.1)
    [32m•[39m VS Code at C:\Users\LENOVO\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.82.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.2006]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 121.0.6167.161
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 121.0.2277.112

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 2 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by danagbemava-nc** [comment] 2024-02-15 13:28
Closing this as a duplicate of https://github.com/flutter/flutter/issues/98905

**Closed by danagbemava-nc** 2024-02-15 13:28 UTC
Labels: in triage
