### ISSUE TITLE
Exception caught by widget library, prompted to report

### ISSUE THREAD

**Issue by rgbinnovation** [flutter/flutter#25378] opened 2018-12-14 17:56 UTC
Got the following when building (app still runs though):

```
flutter: The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#c51fa):
flutter: 'package:flutter/src/widgets/app.dart': Failed assertion: line 169 pos 15: 'navigatorObservers !=
flutter: null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new WidgetsApp (package:flutter/src/widgets/app.dart:169:15)
flutter: #3      _MaterialAppState.build (package:flutter/src/material/app.dart:410:14)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #15     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
flutter: #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #19     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
flutter: #20     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
flutter: #21     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
flutter: #22     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
flutter: #23     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
flutter: #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
flutter: #25     runApp (package:flutter/src/widgets/binding.dart:756:7)
```

**Comment by zoechi** [comment] 2018-12-17 10:15
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

Please also add the output of `flutter doctor -v`.

**Comment by zoechi** [comment] 2018-12-17 16:01
Might be a duplicate of #18904

**Comment by zoechi** [comment] 2019-01-14 08:53
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-01-14 08:53 UTC
Labels: f: routes, framework, waiting for customer response

**Comment by junaidTariq32** [comment] 2019-02-03 08:34
![image](https://user-images.githubusercontent.com/47038830/52174607-3cdb9500-27b8-11e9-9637-0e89323cdef5.png)
 when i clled this fuction its give me error in the start when few second its ..... whats the problem
