### ISSUE TITLE
Apropos error when building from .xcodeproj instead of .xcworkspace

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#52059] opened 2020-03-05 23:49 UTC
Users sometimes accidentally build their project from the .xcodproj instead of the .xcworkspace which will result in linker errors if they are using plugins.

Ideally, instead of getting linker errors, we could print out an error that the project should be built from the .xcworkspace instead.

Example issue: https://github.com/flutter/flutter/issues/51992

**Comment by jmagman** [comment] 2020-03-06 01:25
Duplicate of https://github.com/flutter/flutter/issues/10770.

**Closed by jmagman** 2020-03-06 01:25 UTC
Labels: t: xcode
