### ISSUE TITLE
Tapping appbar no longer scrolls to top

### ISSUE THREAD

**Issue by calvinmuller** [flutter/flutter#35050] opened 2019-06-25 11:01 UTC
# Steps to Reproduce
1. scroll to bottom and attempt to tap that app bar
Expected - scroll to top
Current - nudda 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(title: 'Flutter Demo', home: ListViewPage());
  }
}

class ListViewPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        actions: [],
      ),
      body: ListView.builder(
        itemCount: 100,
        itemBuilder: (context, i) => Container(
          child: Text(i.toString()),
        ),
        primary: true,
      ),
    );
  }
}
```
## Logs

Nothing

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.7.10-pre.11, on Mac OS X 10.14.4 18E226, locale en-ZA)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by calvinmuller** [comment] 2019-06-25 11:13
I guess this is is related to iOS 13 - it works on simulator running iOS 12.2.

**Comment by davidlantrip** [comment] 2019-06-26 14:12
I've seen the same issue with flutter on both iOS 13 dev betas, it still work as expected with native apps though.

**Comment by justinmc** [comment] 2019-07-31 16:37
Yeah this looks like it must be caused by some change in iOS 13.  It seems that Flutter's gesture detector for the status bar is not receiving any events: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scaffold.dart#L1834

**Comment by justinmc** [comment] 2019-08-16 17:55
I dug into this and I think it is potentially a problem with iOS13 itself, or if not, then it's a problem with how we listen to touch events in the engine.

First of all, I conclude that the problem is not in the framework because I can see that the framework receives a pointer event on iOS11.3 but not iOS13 here:

https://github.com/flutter/flutter/blob/a11d73148c90dd2980f0ab5a2d88159269937e3a/examples/layers/raw/touch_input.dart#L79

Then digging into the engine, the deepest that I could track the problem is [touchesBegan](https://github.com/flutter/engine/blob/942e6318144648240ff399cfe1b067330c515a42/shell/platform/darwin/ios/framework/Source/FlutterAppDelegate.mm#L51), which seems to be a built in method.  It's not being called when I tap the status bar in iOS13, but it is in iOS11.3.  See also [handleStatusBarTouches](https://github.com/flutter/engine/blob/942e6318144648240ff399cfe1b067330c515a42/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm#L1028), which should be called by `touchesBegan`.

**Comment by ZHCliang** [comment] 2019-08-29 10:31
The status bar is no longer part of the application on iOS13, it’s part of the system UI (“springboard”). So there is no status bar touch event in app. 
After a little dig, I found the event is dispatched through UIStatusBarManager's handleTapAction method ( -[UIStatusBarManager handleTapAction:] ).

**Comment by justinmc** [comment] 2019-08-29 18:37
@ZHCliang I was so hopeful for this but I think that `handleTapAction` is private!  Looking at the docs: https://developer.apple.com/documentation/uikit/uistatusbarmanager.

CC @LongCatIsLooong for pointing this out to me.

**Comment by ilya310300** [comment] 2019-08-29 22:42
So, we are waiting for the flutter fix for iOS 13, right?

**Comment by justinmc** [comment] 2019-08-29 23:16
@ilya310300 I think this is actually just the brainstorming phase now :)

I am unaware of a good way to fix this.  I think including an offscreen UIListView in the engine is probably too hacky.  I can't think of another way to do this right now.  Anyone else?

**Comment by Kavantix** [comment] 2019-09-30 13:54
@justinmc including a UIScrollView in the flutterviewcontroller is most likely the only way to fix this issue.
This would also translate in the future to supporting multiple windows of a single flutter app since they all would have their own viewcontroller and thus their own scrollview with statusbar tap action.

Also, since this really breaks the close to native feel on iOS I would suggest implementing it like this now and changing it if we find a better approach.

**Comment by justinmc** [comment] 2019-09-30 17:13
@Kavantix Thanks, I appreciate the insights.  I'll try this out when I have some time and see if it looks like a viable way to solve this.

**Comment by miguelpruivo** [comment] 2019-11-21 01:48
@justinmc any plans for this? I can confirm that on iOS 13 tapping on status bar is not working anymore and @Kavantix suggestion looks reasonable.

Handling status bar taps with Flutter has been quite a pain for those that really want to add native iOS UX (which is crucial for some customers when selling Flutter as a solution) when you have your own custom `ScrollController`'s as they don't allow you to implement a listener for status bar tap and neither you can't attach `PrimaryScrollController` to multiple `Scrollable`s.

**Comment by agordeev** [comment] 2019-11-21 05:19
I agree that this issue should get a higher priority.

**Comment by fuyucn** [comment] 2019-12-17 19:51
any update on this issue?

**Comment by justinmc** [comment] 2019-12-27 16:54
I plan to make an attempt at implementing [Kavantix's solution above](https://github.com/flutter/flutter/issues/35050#issuecomment-536571525) in the new year.  This seems to be affecting a ton of people given all the 👍's.

**Comment by lqs** [comment] 2020-01-15 08:06
Another way to workaround this issue is creating a dummy WebView (which is backed by a native WKWebView) and handle it's onscroll event:

```
Stack(
  children: <Widget>[
    child,
    Opacity(
      opacity: 0.01,
      child: IgnorePointer(
        child: WebView(
          javascriptMode: JavascriptMode.unrestricted,
          javascriptChannels: <JavascriptChannel>[
            JavascriptChannel(
              name: 'Print',
              onMessageReceived: (message) {
                if (message.message == "scrollToTop") {
                  // do scroll-to-top action here
                }
              },
            ),
          ].toSet(),
          onWebViewCreated: (controller) async {
            final html =
                '<div style="height:200%"></div>'
                '<script>'
                'var canSend = true;'
                'document.body.scrollTop=100;'
                'document.onscroll = () => {'
                '  if (document.body.scrollTop < 100 && canSend) {'
                '    Print.postMessage("scrollToTop");'
                '    canSend = false;'
                '  }'
                '  if (document.body.scrollTop == 0 && !canSend) {'
                '    canSend = true;'
                '    document.body.scrollTop = 100;'
                '  }'
                '};'
                '</script>';
            await controller.loadUrl(Uri.dataFromString(
              html,
              mimeType: 'text/html',
            ).toString());
          },
        ),
      ),
    ),
  ],
),
```

**Comment by tuanbs** [comment] 2020-01-27 10:28
I got the same issue. Any update or workaround please? Thanks in advance.

**Comment by noefroidevaux** [comment] 2020-01-28 14:43
> I plan to make an attempt at implementing [Kavantix's solution above](https://github.com/flutter/flutter/issues/35050#issuecomment-536571525) in the new year. This seems to be affecting a ton of people given all the 👍's.

Any news about the attempt?

**Comment by justinmc** [comment] 2020-01-28 23:39
I haven't gotten to it and won't in the immediate future.  If anyone else wants to try in the meantime let me know!

**Comment by erperejildo** [comment] 2020-02-17 13:57
Facing same issue. Any news?

**Comment by tvolkert** [comment] 2020-02-19 23:30
@xster it looks like this is on your radar already?  @justinmc I'm going to unassign you since it looks like you're not actively working on this.

**Comment by xster** [comment] 2020-02-19 23:46
No timeline yet but one of the top items in the list I'm compiling to pull out of in Q1-2.

**Comment by MG-Han** [comment] 2020-02-25 03:04
I have a tricky workaround about the issue.

1. add a dummy scrollView as a subview of FlutterViewController's view.
2. make the scrollView scrollable, and set contentOffset.y to positive value.

> if the scrollView is not scrollable, status bar's 'scroll to top' event isn't delivered.

3. set the scrollView's frame as same width with root view's and lay it to invisible bottom area(out of view's bounds).

> status bar's 'scroll to top' event only delivers to scrollViews under the touch point's x offset.
> make scrollView to lay in invisible area, so users can't change the content offset accidentally.

4. set the scrollView's delegate and implement scrollViewShouldScrollToTop:.
5. in scrollViewShouldScrollToTop: method, return false and send Platform channel event to Flutter to scroll to top.

> you can receive the scroll event continuously by returning false(make the scroll view not to scroll to top)

    import Flutter
    import UIKit

    class SampleFlutterViewController: FlutterViewController {
        private weak var dummyScrollView: UIScrollView!

        private var eventSink: FlutterEventSink?

        private enum PlatformEvent: Int {
            case scrollToTop = 0
        }

        override func viewDidLoad() {
            super.viewDidLoad()

            let dummyScrollView = UIScrollView()
            dummyScrollView.delegate = self
            dummyScrollView.alwaysBounceVertical = true
            dummyScrollView.contentInset = UIEdgeInsets(top: 100, left: 0, bottom: 0, right: 0)
            view.addSubview(dummyScrollView)
            self.dummyScrollView = dummyScrollView

            dummyScrollView.snp.makeConstraints {
                $0.leading.trailing.equalToSuperview()
                $0.top.equalTo(view.snp.bottom)
                $0.size.equalToSuperview()
            }

            let eventChannel = FlutterEventChannel(name: "sample.eventChannel", binaryMessenger: binaryMessenger)
            eventChannel.setStreamHandler(self)
        }

        override func viewDidLayoutSubviews() {
            super.viewDidLayoutSubviews()

            dummyScrollView.contentOffset.y = 100
        }

        private func sendPlatformEventToFlutter(_ event: PlatformEvent) {
            eventSink?(event.rawValue)
        }
    }

    extension SampleFlutterViewController: UIScrollViewDelegate {
        func scrollViewShouldScrollToTop(_ scrollView: UIScrollView) -> Bool {
            sendPlatformEventToFlutter(.scrollToTop)

            return false
        }
    }

    extension SampleFlutterViewController: FlutterStreamHandler {
        func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink) -> FlutterError? {
            self.eventSink = events
            return nil
        }

        func onCancel(withArguments arguments: Any?) -> FlutterError? {
            eventSink = nil
            return nil
        }
    }


> if you don't familiar with platform channel, the example is: https://github.com/flutter/flutter/tree/master/examples/platform_channel_swift

**Comment by xster** [comment] 2020-02-25 07:20
I think this will make our prioritization cut for Q1-2. 

Pre-emptively cc @gaaclarke. When it ultimately does, this will likely fall in your bucket :D

**Comment by gaaclarke** [comment] 2020-02-26 23:42
I've submitted a PR that does the UIScrollView workaround: https://github.com/flutter/engine/pull/16820

I'll be unavailable for a few days.  I have to do a bit more testing to do on it when I get back, feel free to give it a try in the meanwhile.

**Comment by tvolkert** [comment] 2020-02-27 00:45
Thanks @gaaclarke!  Do we know when/how this broke?  Is there any way we could test it so it doesn't break again?

**Comment by xster** [comment] 2020-02-27 01:15
It broke via implementation breaking change in iOS 13. It's testable via EarlGrey driving both the engine and the framework multiplexed with different iOS versions since everything has to be brought together.
 
https://github.com/flutter/flutter/issues/32987

It's in our candidate work list but will be long term work if it makes the cut and earlgreyflutter is shipped.

**Comment by gaaclarke** [comment] 2020-02-27 01:37
@tvolkert it broke in iOS 13.  Imo it's a bug in Apple's code since they no longer call touchesBegan:withEvent: to application delegates for touches on the status bar.  The best case for automating this test would be a golden image test.  Since the fix involves adding a offscreen dummy view we'd want to capture any case where a bug was introduced that put it on screen.  

I'm not sure if we can 100% test this since we have to send touch events to the status bar which might not be possible.  We can for sure test our portion of the code but that wouldn't have caught this breakage.  Only a test that creates UITouches would do that.

**Comment by xster** [comment] 2020-03-04 21:25
This is now fixed (and tested) in the engine. It should roll into master shortly. Thanks for the quick fix @gaaclarke!

**Closed by xster** 2020-03-04 21:25 UTC
Labels: customer: crowd, customer: solaris, framework, severe: customer critical, severe: regression, ⌺‬ platform-ios

**Comment by superakabo** [comment] 2020-03-27 12:33
> This is now fixed (and tested) in the engine. It should roll into master shortly. Thanks for the quick fix @gaaclarke!

unfortunately your fix only works for SingleChildScrollView

**Comment by x4080** [comment] 2020-04-10 20:52
Hi, is this already fixed in master ? And it works for all ScrollView ? Or just list ?

**Comment by superakabo** [comment] 2020-04-10 20:59
> Hi, is this already fixed in master ? And it works for all ScrollView ? Or just list ?

Yes it is fixed in master and it works for all scrollview descendants.

**Comment by x4080** [comment] 2020-04-13 21:23
Thanks @superakabo I'll tried it

**Comment by lucien144** [comment] 2020-04-16 09:07
@superakabo Do you know when this gets to stable?

**Comment by randyhammond** [comment] 2020-04-16 19:41
> @superakabo Do you know when this gets to stable?

According to [this post](https://groups.google.com/forum/#!topic/flutter-dev/FCPADeOqtyo), 1.17 will be released at the end of April. I've been testing 1.17.0-dev.3.1 for the past week or so, it includes this fix and seems to be stable so far.

**Comment by x4080** [comment] 2020-04-16 20:49
Yes it works now, but anyone can tell how this works ? I mean if I have tablet mode, and have 2 scaffold side by side, how to choose which list got to scroll by tapping the statusbar ?

TIA

**Comment by nohli** [comment] 2020-04-16 20:55
Can confirm, this is already included in flutter beta channel :)

**Comment by Kavantix** [comment] 2020-04-16 23:30
@x4080 it only support 1 scrollview.
What the fix (sadly) does is making a fake tap where the status bar is which the scaffold then can handle.
So looking the code it should send a fake tap to (0,0) So the top left.
Which would mean that in your example the left scaffold would always get the event.

**Comment by gaaclarke** [comment] 2020-04-16 23:51
@Kavantix it depends on what coordinate system (0,0) is in.  If they are app local it won't be a problem.

@x4080 If there is a bug with with side-by-side apps can you file a new bug with reproduction steps please.

**Comment by Kavantix** [comment] 2020-04-17 00:05
@gaaclarke it’s not about two side by side apps but rather a single app with multiple Scaffold widgets in a row.
So since the ios code will always tap at the top left of the viewcontrollers view it will always end up in the ledt Scaffold

**Comment by gaaclarke** [comment] 2020-04-17 00:19
@Kavantix Ahh I see.  The #16820 just duplicated the logic that existed previously.  If that doesn't work, it never worked.  I'm not sure how UIKit apps handle this, we'll have to take a look.  You could have 20 scroll views visible, what happens?  File a bug please with your observed result versus expected result.

**Comment by x4080** [comment] 2020-04-17 01:38
@gaaclarke , @Kavantix  Thanks all, yes I just wondered how to direct the event from status bar if its not possible (manually if not possible automatically)

**Comment by shinsenter** [comment] 2020-04-27 05:39
>Can confirm, this is already included in flutter beta channel :)

I'm in beta channel and this feature does not work at all.
```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.5 19F62f, locale ja)
    • Flutter version 1.17.0 at /Users/develop/flutter
    • Framework revision d3ed9ec945 (3 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)
```

**Comment by Kavantix** [comment] 2020-04-27 06:08
@shinsenter there are a few things to keep in mind for it to work.
- You have to use the `ScrollController` provided by the `Scaffold`, this should be the default unless you explicitly give it another controller or provide another `PrimaryScrollController` somewhere in your widget tree.
- Nested `Scaffolds` will only allow the top most one to get the event.

**Comment by shinsenter** [comment] 2020-04-27 07:48
@Kavantix 
Is the information being documented somewhere?  Do you have a working example?  Please show me.

**Comment by superakabo** [comment] 2020-04-27 08:34
> @Kavantix
> Is the information being documented somewhere? Do you have a working example? Please show me.

````


class Example extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PrimaryScrollController(
      controller: ScrollController(),
      child: Scaffold(
        appBar: AppBar(),
        body: CustomScrollView(
          controller: PrimaryScrollController.of(context),
          slivers: <Widget>[],
        ),
      ),
    );
  }
}

````

**Comment by Kavantix** [comment] 2020-04-27 08:36
@superakabo actually this should work: 

```dart
class Example extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: CustomScrollView(
        slivers: <Widget>[],
      ),
    );
  }
}
```

**Comment by superakabo** [comment] 2020-04-27 08:39
Yes, it does.
It is an example for shinsenter.

**Comment by Kavantix** [comment] 2020-04-27 08:47
> ```dart
> class Example extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return PrimaryScrollController(
>       controller: ScrollController(),
>       child: Scaffold(
>         appBar: AppBar(),
>         body: CustomScrollView(
>           controller: PrimaryScrollController.of(context),
>           slivers: <Widget>[],
>         ),
>       ),
>     );
>   }
> }
> ```
@superakabo Your example will actually not work.
You're taking the `PrimaryScrollController` of the widget above the `Example` widget.
So you're explicitly not using the controller of the scaffold here

**Comment by superakabo** [comment] 2020-04-27 08:56
@Kavantix, it does work. You can put it to the test.

**Comment by nohli** [comment] 2020-04-28 21:12
I would like to be able to scroll to the top when pressing the bottom bar.

My working solution, having a ScrollController in a SingleChildScrollView, doesn't work with this new fix.

Is there a way?
Right now, I can either have a bottom bar or a status bar tap (if I remove the ScrollController) scroll to the top, not both.

**Comment by superakabo** [comment] 2020-04-28 22:00
@nohli you can try this:
```dart
PrimaryScrollController.of(context).animateTo(
        0.0,
        duration: Duration(milliseconds: 500),
        curve: Curves.decelerate,
    );
```

**Comment by nohli** [comment] 2020-04-28 22:07
@superakabo thanks!

That‘s quite similar to my code, which is working (without the status bar tap).

But it won‘t affect the SingleChildScrollView (which should scroll to the top), even when I declare the PrimaryScrollController.of(context) as its controller.

**Comment by superakabo** [comment] 2020-04-28 22:15
@nohli take a look at this:
https://github.com/flutter/flutter/issues/35050#issuecomment-619829514

replace your scroll controller with 
```dart
PrimaryScrollController.of(context)
```
I'd advise you check stackoverflow too.

**Comment by nohli** [comment] 2020-04-28 22:21
I did everything, I actually copied your code and it didn‘t work in my app.
It worked in the sense that it scrolls to top on status bar tap. But I would like that plus scroll to top via a bottom bar tap - which is very common in apps.

**Comment by superakabo** [comment] 2020-04-28 22:23
@nohli can you share your code?

**Comment by nohli** [comment] 2020-04-28 22:38
Gladly :)

This it the 'before' code - which works well, without the new fix. For the fix to work, I have to remove key and controller from SingleChildScrollView. Then, I tried everthing, the scrollToTop function won't work any more...

```
void scrollToTop(int _tab) {
  // this just gives the corresponding ScrollController
  // I unsuccessfully tried changing to PrimaryScrollController.of(context):
  final ScrollController _scrollController = scrollController(_tab);
  if (_scrollController != null) {
    if (_scrollController.hasClients) {
      _scrollController.animateTo(_scrollController.initialScrollOffset,
          duration: const Duration(milliseconds: scrollTime),
          curve: Curves.easeInOutSine);
    }
  }
}
```

```
  Widget build(BuildContext context) {
    buildContext = context;

    final provider = Provider.of<NavigationProvider>(context);

    return Listener(
        onPointerUp: (_) {
          if (!FocusScope.of(context).hasPrimaryFocus) {
            FocusScope.of(context).unfocus();
          }
        },
        child: AnnotatedRegion<SystemUiOverlayStyle>(
            value: systemUiStyle(context),
            // I tried wrapping this in PrimaryScrollController, like you did
            child: Scaffold(
                // resizeToAvoidBottomInset: false,
                body: WillPopScope(
                  onWillPop: willPopScope,
                  child: tabs[provider.currentTab],
                ),
                floatingActionButton: buttons[button],
                bottomNavigationBar: bottomBar(context))));
  }
}
```

```
  Widget _tab(BuildContext context) => SafeArea(
        child: Scrollbar(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: horizontalPadding),
            child: Center(
              child: SingleChildScrollView(
                // for the tap on status bar to work, I have to remove key and controller
                // and then scrollToTop() won't work - even if I write PrimaryScrollController.of(context)
                key: pageStorage(item.active),
                controller: activeScrollController,
                child: Column(
                  children: <Widget>[
```

**Comment by superakabo** [comment] 2020-04-28 22:42
replace _scrollController.animateTo(_scrollController.initialScrollOffset, with 0.0
You can refer to this:
https://stackoverflow.com/questions/53824944/flutter-exception-scrollcontroller-attached-to-multiple-scroll-views

**Comment by Kavantix** [comment] 2020-04-28 22:55
@nohli you can have both by using the `PrimaryScrollController` but you have to use the correct context.
Currently you’re passing the `BuildContext` of the widget that builds the `Scaffold`. But you need a context of a child of the scaffold.
So you could wrap your bottombar function in a `Builder` widget and using its context.

On a sidenote, in general it is better to make a Widget subclass than using methods to divide code, that way you also automatically have access to the correct `BuildContext`.

**Comment by nohli** [comment] 2020-04-29 00:16
It's working now, thanks a lot @superakabo & @Kavantix :))

**Comment by lucien144** [comment] 2020-05-06 19:39
v1.17 has been released as stable today which should contain this fix

**Comment by miguelpruivo** [comment] 2020-05-06 21:50
@lucien144 I still have this issue on v1.17. A simple view with Scaffold and a ListView and it _does not_ scroll to top on status bar tapping.

**Comment by marc-andrew** [comment] 2020-05-07 09:05
I still have this issue on v1.17. as well.

**Comment by miguelpruivo** [comment] 2020-05-07 09:11
I’m willing to know what’s the best way to add a workaround for this. I’ve been waiting for 1.17 expecting it to fix and surprisingly did not.

**Comment by nohli** [comment] 2020-05-07 10:10
Try to wrap the ListView in a SingleChildScrollView.

**Comment by miguelpruivo** [comment] 2020-05-07 10:43
With the help of @Kavantix I was able to fix it, it turns out I wasn't delegating the taps due to a custom `ScrollController` in a nested view.

**Comment by shinsenter** [comment] 2020-05-08 02:05
@Kavantix @superakabo 
Thanks. I wrapped my app with PrimaryScrollController and replaced scroll view's controller with `PrimaryScrollController.of(context)` but it does not work. Using the latest stable version 1.17.

**Comment by SiTianyu** [comment] 2020-05-11 03:36
It does still not work on 1.17.

**Comment by cataCostea** [comment] 2020-05-15 10:56
Any updates on this issue?

**Comment by randyhammond** [comment] 2020-05-15 15:49
@shinsenter, @SiTianyu, @cataCostea - This only works within a Scaffold, are you using one in your app? In most cases you should not have to add a PrimaryScrollController since the Scaffold provides ones. If you added your own that's likely what's causing your problems, so you should try without it. If you want to access the Scaffold's scroll controller (for example, to scroll to the top on a button tap) then you can use the following:

```
PrimaryScrollController.of(context).animateTo(
    0.0,
    duration: const Duration(milliseconds: 300),
    curve: Curves.linear, 
);
```
If it's still not working, then I would suggest that you post a simplified version of your code to Stackoverflow or create a separate issue here.

**Comment by xster** [comment] 2020-05-16 00:59
Since this bug is closed. We aren't tracking it. If you're still facing a related issue, please open a new issue with clear repro steps.

**Comment by Tamerlanchiques** [comment] 2020-05-25 00:08
Still can't "scroll-to-top" in my app. May someone link some step-by-step tutorial with working example?

**Comment by LachlanGrant** [comment] 2020-05-25 04:12
@Kavantix 
> * Nested `Scaffolds` will only allow the top most one to get the event.

Is there a way around this issue? I've got a bottomNavigationBar with each tab having it's own Scaffold (to allow for each tab having a drastically different AppBar).

**Comment by CharlesCCC** [comment] 2020-09-05 02:21
> Still can't "scroll-to-top" in my app. May someone link some step-by-step tutorial with working example?
@Tamerlanchiques 
Are you using customized `ScrollController` ?  if yes, try to replace it with the default `PrimaryScrollController`

like 
`_scrollController = PrimaryScrollController.of(context);` 

```dart
      body: Builder(
        builder: (context) {
          _scrollController = PrimaryScrollController.of(context);
        return Widget(_scrollController);
```

**Comment by eugene-kalaganov** [comment] 2020-09-17 06:26
all above don't work on real device 13.3+

**Comment by JohannDesobry** [comment] 2020-09-17 09:03
Tap to top is working on real device (13.7). But only when I have a simple scaffold.

```
Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: Text(
          'Tap to top',
          style: TextStyle(fontSize: 15),
        ),
      ),
      body: ListView.builder( 
        itemCount: 50, 
        itemBuilder: (BuildContext context,int index){ 
          return ListTile( 
            leading: Icon(Icons.list), 
            trailing: Text(
              "GFG", 
              style: TextStyle( 
                color: Colors.green,fontSize: 15
              ),
            ), 
            title:Text("List item $index") 
            ); 
        } 
      ),
    )
```

**Comment by CharlesCCC** [comment] 2020-10-13 02:09
> > Still can't "scroll-to-top" in my app. May someone link some step-by-step tutorial with working example?
> 
> @Tamerlanchiques
> Are you using customized `ScrollController` ? if yes, try to replace it with the default `PrimaryScrollController`
> 
> like
> `_scrollController = PrimaryScrollController.of(context);`
> 
> ```dart
>       body: Builder(
>         builder: (context) {
>           _scrollController = PrimaryScrollController.of(context);
>         return Widget(_scrollController);
> ```

Apparently this doesn't work anymore (Not remember if is after Flutter update to 1.22 or after iOS 14.0 update)

**Comment by jamesblasco** [comment] 2020-10-13 05:32
@CharlesCCC Are you using Scaffold? 
This widget is the one that takes care of this feature and that adds the PrimaryScrollController that you can use inside your scroll views.

I just tried and it was working fine for me

**Comment by CharlesCCC** [comment] 2020-10-14 02:25
@jamesblasco Thank you for the reply. Yes, I'm using it within the Scaffold. 
The code is like this 

```dart
    return Scaffold(
      resizeToAvoidBottomInset: true,
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          _bulkEditIconButton(context),
        ],
      ),
      drawer: AppDrawer(),
      body: Builder(
        builder: (context) {
          _scrollController = PrimaryScrollController.of(context);
```

And Just now, I realized what was causing the issue, It is happening after 1.22 release. When I added the following to my app:  
```dart
void main() {
    GestureBinding.instance.resamplingEnabled = true;
    run(MyApp());
}
```

reference: https://medium.com/flutter/announcing-flutter-1-22-44f146009e5f

So, I believe I have found a bug with using that flag.

**Comment by virskor** [comment] 2020-12-18 09:02
The same, i am still facing this problem when users tap appbar to scroll back to top.

**Comment by justinmc** [comment] 2020-12-21 17:00
Can anyone that's still seeing this on master create a new issue?

**Comment by alvindrakes** [comment] 2021-01-11 05:43
> @jamesblasco Thank you for the reply. Yes, I'm using it within the Scaffold. 
> 
> The code is like this 
> 
> 
> 
> ```dart
> 
>     return Scaffold(
> 
>       resizeToAvoidBottomInset: true,
> 
>       appBar: AppBar(
> 
>         title: Text(widget.title),
> 
>         actions: <Widget>[
> 
>           _bulkEditIconButton(context),
> 
>         ],
> 
>       ),
> 
>       drawer: AppDrawer(),
> 
>       body: Builder(
> 
>         builder: (context) {
> 
>           _scrollController = PrimaryScrollController.of(context);
> 
> ```
> 
> 
> 
> And Just now, I realized what was causing the issue, It is happening after 1.22 release. When I added the following to my app:  
> 
> ```dart
> 
> void main() {
> 
>     GestureBinding.instance.resamplingEnabled = true;
> 
>     run(MyApp());
> 
> }
> 
> ```
> 
> 
> 
> reference: https://medium.com/flutter/announcing-flutter-1-22-44f146009e5f
> 
> 
> 
> So, I believe I have found a bug with using that flag.  
> 
> 
> 
> 
> 
> 

Nope, I didn't have this flag in my app but the issue still remain. So the issue is not this flag.
