### ISSUE TITLE
[webview_flutter] Support disabling overscroll on Android / iOS

### ISSUE THREAD

**Issue by Reprevise** [flutter/flutter#122533] opened 2023-03-13 15:56 UTC
## Use case

Scrolling content in a webview can be annoying when overscroll is enabled and the option to disable it would be welcomed.

## Proposal

Add a method on the `WebViewController` that allows overscroll to be enabled/disabled on both platforms.

There's a similar issue #57090 however it's for iOS and I think it asks to disable scrolling altogether whereas this issue is just to disable overscroll.

**Comment by stuartmorgan** [comment] 2023-03-13 17:08
Closing as a duplicate of https://github.com/flutter/flutter/issues/57090, which no longer iOS-only.

**Closed by stuartmorgan** 2023-03-13 17:08 UTC
