### ISSUE TITLE
Could not resolve io.flutter:flutter_embedding_debug:1.0.0

### ISSUE THREAD

**Issue by wasabia** [flutter/flutter#57000] opened 2020-05-12 14:02 UTC
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve io.flutter:flutter_embedding_debug:1.0.0-3953c3ccd15a54a0718700aa11ead664b264b7dd.
     Required by:
```

```
 Could not resolve io.flutter:flutter_embedding_debug:1.0.0-3953c3ccd15a54a0718700aa11ead664b264b7dd.
         > Could not get resource 'https://https/storage.flutter-io.cn/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-3953c3ccd15a54a0718700aa11ead664b264b7dd/flutter_embedding_debug-1.0.0-3953c3ccd15a54a0718700aa11ead664b264b7dd.pom'.
            > Could not GET 'https://https/storage.flutter-io.cn/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-3953c3ccd15a54a0718700aa11ead664b264b7dd/flutter_embedding_debug-1.0.0-3953c3ccd15a54a0718700aa11ead664b264b7dd.pom'.
               > Remote host closed connection during handshake
```

```
the url in error log was wrong...
https://https/storage.flutter-io.cn/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-3953c3ccd15a54a0718700aa11ead664b264b7dd/flutter_embedding_debug-1.0.0-3953c3ccd15a54a0718700aa11ead664b264b7dd.pom
```

Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)

**Comment by VladyslavBondarenko** [comment] 2020-05-12 16:54
Hi @wasabia 
have you configured a mirror site as here https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site?

`> Could not GET` link doesn't look correct, there should be `https://storage.flutter-io.cn` instead of `https://https/storage.flutter-io.cn`

**Comment by rongxiong** [comment] 2020-05-13 03:27
I encoutered the same problem on the github pre version, so I switch to the 1.17 stable version which works just fine.

**Comment by iapicca** [comment] 2020-05-13 13:38
possible dupe for https://github.com/flutter/flutter/issues/56861

**Comment by wasabia** [comment] 2020-05-14 05:19
@VladyslavBondarenko 
```
echo $FLUTTER_STORAGE_BASE_URL


https://storage.flutter-io.cn
``` 

for me this error just happened on
```
Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
```

**Comment by TahaTesser** [comment] 2020-05-14 09:11
Hi @wasabia 
can you please provide your **complete** `flutter doctor -v` and `flutter run --verbose`?

**Comment by VladyslavBondarenko** [comment] 2020-05-14 11:19
Possibly a duplicate of https://github.com/flutter/flutter/issues/56861

**Comment by iapicca** [comment] 2020-06-05 05:46
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-06-05 05:46 UTC
Labels: in triage, waiting for customer response
