### ISSUE TITLE
The keyboard is not called if obscureText: true

### ISSUE THREAD

**Issue by karbyshevden** [flutter/flutter#55106] opened 2020-04-18 14:17 UTC
Hi friends!
I have a problem after updating to new version of Flutter today - the keyboard is not called if i touch TextField and if TextField has obscureText: true. But if I turn obscureText to false it's working normal.

[✓] Flutter (Channel master, v1.18.0-6.0.pre.80, on Mac OS X 10.15.4 19E287, locale ru)
    • Flutter version 1.18.0-6.0.pre.80 at /Users/karbyshev/Development/flutter
    • Framework revision cdac97c253 (11 hours ago), 2020-04-17 23:25:01 -0400
    • Engine revision 204adaf268
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 5b19445d9c)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/karbyshev/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Karbyshev • 00008030-0015682A1E3A802E • ios • iOS 13.4.1

• No issues found!

**Comment by imeDevelopers** [comment] 2020-04-18 16:27
code please ?!

make sure to set `readOnly: false,`

**Comment by kunit1** [comment] 2020-04-18 16:28
Is this on Android or iOS?
Seeing this issue on iOS. Pretty serious regression.

**Comment by karbyshevden** [comment] 2020-04-18 16:32
@imeDevelopers here:
Widget _passwordField() {
    final password = AppLocalizations.of(context).translate('password');
    return TextField(
      controller: passwordController,
      keyboardType: TextInputType.text,
      obscureText: true,
      decoration: InputDecoration(
        prefixIcon: Icon(Icons.lock),
        labelText: password,
      ),
    );
  }

**Comment by karbyshevden** [comment] 2020-04-18 16:41
@kunit1 on iOS

**Comment by imeDevelopers** [comment] 2020-04-18 17:05
Is this function in anoter file or the same file ?

Remove keyboard type parameter..

**Comment by imeDevelopers** [comment] 2020-04-18 17:06
And add readOnly: false ..

**Comment by imeDevelopers** [comment] 2020-04-18 17:07
Add enabled: true ..

**Comment by imeDevelopers** [comment] 2020-04-18 17:07
Add focusnode ..

**Comment by karbyshevden** [comment] 2020-04-18 17:08
@imeDevelopers yes, this the same file.
I can try what you ask a bit later, and let you know.

**Comment by hoangminhk4b** [comment] 2020-04-18 17:16
same issue, when set obscureText=true, keyboard don't show when focus it

**Comment by happyphper** [comment] 2020-04-19 14:52
same issue occur. after upgrade xcode and flutter.

**Comment by happyphper** [comment] 2020-04-19 15:28
> same issue occur. after upgrade xcode and flutter.

back to previous version, the code goes to running.

```
Flutter (Channel master, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
```

**Comment by vasilich6107** [comment] 2020-04-19 15:31
Possible duplicate of 55081

**Comment by marcianobandeira** [comment] 2020-04-19 22:31
i have same problem in ios.. master channel

**Comment by LongCatIsLooong** [comment] 2020-04-20 00:21
duplicate of #55081.

**Closed by LongCatIsLooong** 2020-04-20 00:21 UTC
