### ISSUE TITLE
Mac_arm64 custom_package_tests and ios_platform_tests fail when using xcode 14c18

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#125217] opened 2023-04-20 16:17 UTC
Hit the error when updating xcode to 14c18: https://github.com/flutter/packages/pull/3774

Example: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20custom_package_tests%20master/2336/overview

```
Xcode build done.                                           20.9s
Built /Volumes/Work/s/w/ir/x/w/packages/packages/pigeon/platform_tests/alternate_language_test_plugin/example/build/ios/iphonesimulator/Runner.app.
Command line invocation:
    /Volumes/Work/s/w/ir/cache/osx_sdk/xcode_14c18/XCode.app/Contents/Developer/usr/bin/xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13" test

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    SDKROOT = iphonesimulator16.2

Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
2023-04-20 08:52:30.549 xcodebuild[60648:570510] Writing error result bundle to /var/folders/pt/pr94k3sn5353647rpymtk_640000gp/T/ResultBundle_2023-20-04_08-52-0030.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, OS:latest, name:iPhone 13 }

	The requested device could not be found because no available devices matched the request.

	Available destinations for the "Runner" scheme:
		{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008103-000E116C21D3001E }
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
		{ platform:iOS Simulator, id:048A91D4-5B29-4919-AEA0-13673736A233, OS:16.2, name:iPad (10th generation) }
		{ platform:iOS Simulator, id:AE6109C6-B7FE-4D03-AB47-1FC1796EC5ED, OS:16.2, name:iPad Air (5th generation) }
		{ platform:iOS Simulator, id:056A30DF-72C2-4264-BFAD-36C5B66619B2, OS:16.2, name:iPad Pro (11-inch) (4th generation) }
		{ platform:iOS Simulator, id:CAD11B46-6B4D-41E4-BFB7-3C59B7334D4A, OS:16.2, name:iPad Pro (12.9-inch) (6th generation) }
		{ platform:iOS Simulator, id:F07C7275-CC87-4425-9B80-34037F449E3A, OS:16.2, name:iPad mini (6th generation) }
		{ platform:iOS Simulator, id:B8E634F6-76C6-4797-868D-01338008BB97, OS:16.2, name:iPhone 14 }
		{ platform:iOS Simulator, id:54A58026-A4EE-4FCC-A945-060F8AC4A329, OS:16.2, name:iPhone 14 Plus }
		{ platform:iOS Simulator, id:E06CBF00-945E-45CC-8EA2-81BE7556D2DD, OS:16.2, name:iPhone 14 Pro }
		{ platform:iOS Simulator, id:B97539C7-D7A4-4881-8CAF-AE2337366095, OS:16.2, name:iPhone 14 Pro Max }
		{ platform:iOS Simulator, id:F5BA08D5-5D35-4F80-99A6-A0016D4CE87D, OS:16.2, name:iPhone SE (3rd generation) }
[90m
[packages/pigeon completed in 1m 13s][0m
```

/cc @jmagman @stuartmorgan

**Comment by jmagman** [comment] 2023-04-20 17:13
Looks like Xcode 14.3 dropped the `iPhone 13` simulator.

https://github.com/flutter/packages/blob/746750ecef7852548b038a5ed1a319b7d1d65173/packages/pigeon/tool/shared/test_suites.dart#L326

Does it pass when this is updated to:
```diff
-     destination: 'platform=iOS Simulator,name=iPhone 13',
+     destination: 'platform=iOS Simulator,name=iPhone 14',
```

cc @vashworth @cyanglaz

**Comment by keyonghan** [comment] 2023-04-20 17:31
Failure happened on ios_platform_tests too, and updated to use iPhone 14 as well: https://github.com/flutter/packages/pull/3774/commits/526934c9575414e9e297004b4825ec882eb99ac2

**Comment by keyonghan** [comment] 2023-04-20 17:51
The custom_package_tests passed, but the platform_tests still fails complaining:
```
No iOS devices available
```

Example: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_1%20master/2443/overview

**Comment by stuartmorgan** [comment] 2023-04-20 19:14
You need to change the simulator that the platform tests create if you change what platform_tests tries to use: https://github.com/flutter/packages/blob/main/.ci/scripts/create_simulator.sh

**Comment by jmagman** [comment] 2023-04-20 20:30
The actual issue is that the simulator couldn't be created, but the step didn't fail.  Filed https://github.com/flutter/flutter/issues/125243 to fix that.

In the meantime, this should also be updated to iPhone 14 and iOS 16.2
https://github.com/flutter/packages/blob/7e3f5da42e81f6d73789e112fa881acb7652f863/.ci/scripts/create_simulator.sh#L8-L9
```
readonly DEVICE=com.apple.CoreSimulator.SimDeviceType.iPhone-14
readonly OS=com.apple.CoreSimulator.SimRuntime.iOS-16-2
```

**Comment by keyonghan** [comment] 2023-04-20 20:34
with https://github.com/flutter/packages/pull/3774/commits/696650f6604930db27ffac0e8ad99b2e8787f860, most shards passed, but hit some test failure: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783266524818084769/+/u/Run_package_tests/native_test/stdout

```
Test Case '-[PhotoAssetUtilTests testSaveImageWithPickerInfo_ShouldSaveWithTheCorrectExtentionAndMetaData]' started.
/Volumes/Work/s/w/ir/x/w/packages/packages/image_picker/image_picker_ios/example/ios/RunnerTests/PhotoAssetUtilTests.m:90: error: -[PhotoAssetUtilTests testSaveImageWithPickerInfo_ShouldSaveWithTheCorrectExtentionAndMetaData] : ((meta[(__bridge NSString *)kCGImagePropertyExifDictionary] [(__bridge NSString *)kCGImagePropertyExifMakerNote]) equal to (@"aNote")) failed: ("(null)") is not equal to ("aNote")
Test Case '-[PhotoAssetUtilTests testSaveImageWithPickerInfo_ShouldSaveWithTheCorrectExtentionAndMetaData]' failed (0.055 seconds).
Test Suite 'PhotoAssetUtilTests' failed at 2023-04-20 13:25:31.941.
```

**Comment by keyonghan** [comment] 2023-04-20 20:36
Also hit a flake on `Mac_arm64 ios_platform_tests_shard_4 master`: https://ci.chromium.org/ui/p/flutter/builders/try/Mac_arm64%20ios_platform_tests_shard_4%20master/2457/overview (a rerun passed)

```
    t =    33.46s Requesting snapshot of accessibility hierarchy for app with pid 17331
    t =    33.53s Requesting snapshot of accessibility hierarchy for app with pid 17331
/Volumes/Work/s/w/ir/x/w/packages/packages/quick_actions/quick_actions_ios/example/ios/RunnerUITests/RunnerUITests.swift:38: error: -[RunnerUITests.RunnerUITests testQuickActionWithFreshStart] : failed - Failed due to not able to find the actionTwo button from springboard with 30.0 seconds. Springboard debug description: Attributes: Application, 0x147419da0, pid: 17331, label: ' '
Element subtree:
 →Application, 0x147419da0, pid: 17331, label: ' '
```

**Comment by jmagman** [comment] 2023-04-20 22:41
> Test Case '-[PhotoAssetUtilTests testSaveImageWithPickerInfo_ShouldSaveWithTheCorrectExtentionAndMetaData]' failed (0.055 seconds).


I reproduced this one, filed https://github.com/flutter/flutter/issues/125257.

**Comment by jmagman** [comment] 2023-04-20 23:45
> /Volumes/Work/s/w/ir/x/w/packages/packages/quick_actions/quick_actions_ios/example/ios/RunnerUITests/RunnerUITests.swift:38: error: -[RunnerUITests.RunnerUITests testQuickActionWithFreshStart] : failed - Failed due to not able to find the actionTwo button from springboard with 30.0 seconds. Springboard debug description: Attributes: Application, 0x147419da0, pid: 17331, label: ' '

I wasn't able to reproduce this flake locally.

**Comment by jmagman** [comment] 2023-04-21 22:33
Another quick_actions flake: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8783180897936485009/+/u/Run_package_tests/native_test/stdout

**Comment by jmagman** [comment] 2023-04-25 17:48
@cyanglaz is going to investigate the `quick_actions` flake (thank you!)

**Comment by cyanglaz** [comment] 2023-04-28 16:51
https://github.com/flutter/packages/pull/3774 is merged, closing this issue.

**Closed by cyanglaz** 2023-04-28 16:51 UTC
Labels: package, team: infra, P3
