### ISSUE TITLE
Flutter Audio file not recognised.

### ISSUE THREAD

**Issue by Sh00ny** [flutter/flutter#68850] opened 2020-10-23 04:28 UTC
Flutter audio file has a question mark on it. 
It doesn't play.

![image](https://user-images.githubusercontent.com/64748053/96956598-2f2eeb80-1516-11eb-9dd5-f221d2aba3be.png)

**Comment by TahaTesser** [comment] 2020-10-23 08:45
Hi @Sh00ny 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/luanpotter/audioplayers/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-10-23 08:45 UTC
