### ISSUE TITLE
Text overlapping in iOS.

### ISSUE THREAD

**Issue by kadnan0900** [flutter/flutter#71563] opened 2020-12-02 14:02 UTC
i am facing this issue in IOS but in android it works fine.

![Screenshot 2020-12-02 at 6 57 00 PM (1)](https://user-images.githubusercontent.com/51955352/100882134-a621b180-34d0-11eb-83a5-d750ee613605.png)

**Comment by Macacoazul01** [comment] 2020-12-02 14:10
i'm facing this issue too with flutter web on my ios device, when i test the page

**Comment by UzairSun93** [comment] 2020-12-02 14:32
i am facing the same issue on ios when i use rflutter_alert_dialoge ..

**Comment by TahaTesser** [comment] 2020-12-02 15:05
Hi @kadnan0900 
Looks like you're using `rflutter_alert`, the similar dialog in the README, https://pub.dev/packages/rflutter_alert

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/RatelHub/rflutter_alert/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-12-02 15:05 UTC
