### ISSUE TITLE
Can run on iOS from Xcode but not from Android studio

### ISSUE THREAD

**Issue by bcichowlas** [flutter/flutter#71402] opened 2020-11-30 12:13 UTC
I'm on Big Sur 11.1 Beta. (I'm trying to get off the betas, but haven't managed to do it yet.). I'm also fairly new to Flutter.

If I launch from the Xcode project that Flutter builds, first I get the message that I need to set.a development team to run on a device (tethered). I do that and then I'm okay. Since I work with several companies, I have several choices for team in the "Automatic Signing", but any of them seem to work so far.

But when I try to run from Android Studio, it gets to the point where there is a white screen on my iPhone for a long time before crashing back to the app icons on the iPhone. In the Android studio log, it says:

```bash
Running "flutter pub get" in startup_namer...
Launching lib/main.dart on Bruce iphone XS Max in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ............
Running Xcode build...
Xcode build done.                                           10.8s
Installing and launching...
Error launching application on Bruce iphone XS Max.
```
I'm suspicious that it had something to do with the signing, but I'm not sure. I did try
flutter config --clear-ios-signing-cert
I expected it to prompt me for something since that was mentioned in another issue report, but it didn't. There was no error, though. I don't know if perhaps I am supposed to specify the team id I want it to use somewhere within Flutter.

However, I am not sure that the problem has anything to do with the development team id.

**Comment by TahaTesser** [comment] 2020-11-30 12:53
Hi @bcichowlas 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by bcichowlas** [comment] 2020-11-30 14:19
Hi Taha,

I was just trying one of the Flutter examples, so it is similar or identical to what is in the tutorial.

I've been running by selecting my iPhone as the device in Android Studio and then clicking the Debug button, similar to what I do when developing Android apps.  I did "flutter run --verbose" and am attaching the output, but I'm not sure I am doing everything that is needed to run from the command line.

Thanks,
Bruce
[doctor_output.txt](https://github.com/flutter/flutter/files/5616458/doctor_output.txt)
[flutter_run_--verbose_output.txt](https://github.com/flutter/flutter/files/5616459/flutter_run_--verbose_output.txt)
[main.dart.txt](https://github.com/flutter/flutter/files/5616460/main.dart.txt)
[pubspec.yaml.txt](https://github.com/flutter/flutter/files/5616461/pubspec.yaml.txt)

**Comment by TahaTesser** [comment] 2020-12-01 07:57
Hi @bcichowlas 
To launch on physical device, you need to open ios folder of your project in Xcode and go to `Signing & Capabilities` assign team ID and custom bundle identifier. 
It should like this with no warning/errors
<img width="522" alt="Screenshot 2020-12-01 at 1 21 41 PM" src="https://user-images.githubusercontent.com/48603081/100712212-65df0800-33d8-11eb-9fee-4e9bd5338086.png">

If the problem persist, can you please try a fresh project with and do the signing part and launch the app?
Also please provide when executing `flutter run --verbose` from root of your project 
```bash
[  +28 ms] "flutter run" took 2,880ms.
[  +19 ms] Error: No pubspec.yaml file found.
           This command should be run from the root of your Flutter project.
[   +2 ms] 
```


Thank you

**Comment by bcichowlas** [comment] 2020-12-01 20:17
Hi, Taha!

Thanks for your help. I do a lot of iOS work, so my team credentials are set up like the ones you showed above. My only concern was that, since I do iOS work for a lot of places, Flutter might have been confused by all the different team credentials on my computer.

On looking at the log, though, I think the problem may have something to do with what it calls the "observatory port". When I'm running from the command line, it says "Waiting for observatory port" and that is where things stand for a few seconds before it gets into trouble.

What happens then is interesting, however. If I'm running from Android Studio, the app crashes on the iPhone and I see the array of app icons. But if I'm running from the command line, the error happens as shown in the attached log, but after that the app actually starts running on the iPhone, even though it is detached from the computer at that point.

For the attached log, I was simply running the unmodified that flutter installs when you tell Android Studio to create a new Flutter project.

Thanks,
Bruce



[flutter2.txt](https://github.com/flutter/flutter/files/5625104/flutter2.txt)

**Comment by TahaTesser** [comment] 2020-12-02 08:42
Hi @bcichowlas 
Thanks for the logs, using the same flutter channel on a new project when running the app on physical has no issues.  I wonder if it is the Big Sur beta you have installed.

Can you please upgrade to the latest  `master` and try again, just to be sure. 
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

Do you have the same error when running a native iOS app on a physical device as well? Either case, no one in my team is on beta to test this issue.

**Comment by bcichowlas** [comment] 2020-12-02 13:04
Hi, Taha!

I upgraded to the latest master as you suggested.  It didn't change anything.

I don't generally work from the command line and am not sure what to say on the command line to run one of my Xcode native apps.

When I run the default Flutter app from within Xcode, I can run on the simulators okay, but I can't run on the physical device now. (I'm not sure I tried that case before.). I can run my SwiftUI native apps from Xcode on both the simulators and on my iPhone XS Max.

I saw this message in the Xcode build log and have attached the entire log.

Thanks,
Bruce

error: Runner.app/Info.plist does not exist. The Flutter "Thin Binary" build phase must run after "Copy Bundle Resources".
[Build Runner_2020-12-02T07-50-01.txt](https://github.com/flutter/flutter/files/5629420/Build.Runner_2020-12-02T07-50-01.txt)

**Comment by cls8428181** [comment] 2020-12-03 03:24
I also met the same problem, but did not find a solution, if you have a solution, remember to tell me

**Comment by TahaTesser** [comment] 2020-12-03 09:36
Hi @bcichowlas @cls8428181 
I tried on iPhone and iPhone, no issues when running on a physical device.

```bash
Launching lib/main.dart on Taha’s iPad in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: X8NNQ9CYL2
Running Xcode build...
Xcode build done.                                           33.5s
Installing and launching...
Waiting for Taha’s iPad to report its views...
Debug service listening on ws://localhost:52830/ws
Syncing files to device Taha’s iPad...
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

 
[✓] Connected device (1 available)            
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios • iOS 14.2

! Doctor found issues in 1 category.
```

</details>

**Comment by bcichowlas** [comment] 2020-12-03 14:23
Well, I just don't know then. Perhaps it is the BigSur beta, which I hope I will soon be behind me.

But there was the error message about the order in which the "Flutter thin binary" ran. That seemed to refer to something concrete.

I also wonder whether cis8428181 was running the BigSur beta. @cis8428181.

In any event, I appreciate your efforts and look forward to using Flutter successfully in the future.

**Comment by cls8428181** [comment] 2020-12-04 11:11
![image](https://user-images.githubusercontent.com/12572181/101157042-79060800-3664-11eb-9f35-3663c6497de2.png)

**Comment by TahaTesser** [comment] 2020-12-04 15:25
I’m unable to reproduce the issue to pinpoint the cause, but there are reports from several users. The issue needs further investigation.

**Comment by jmagman** [comment] 2020-12-08 21:42
> What happens then is interesting, however. If I'm running from Android Studio, the app crashes on the iPhone and I see the array of app icons.

It sounds like your app is crashing on launch, which is why Flutter can't connect to it.  Can you attach the crash log?

Reproduce, then in Xcode > Window > Devices and Simulators > Bruce iphone XS Max > View Device Logs.  Then right-click on the crash that matches the timestamp of when you reproduced (the Process Name will likely be `Runner`), and Export Log.  Attach here.

**Comment by bcichowlas** [comment] 2020-12-09 15:05
Today I am able to load and run the app on my iPhone. There may have been some Big Sur beta, Xcode or iOS phone updates intervening. I did at first get an error about "iProxy" not being a signed app. When I okayed that through settings, the next time I tried I got a rather large dialog box, also about "iProxy" and I also okayed that. The third time it actually ran! Thanks for the team's help.

**Comment by jmagman** [comment] 2020-12-09 17:50
@bcichowlas I think you hit https://github.com/flutter/flutter/issues/42969.

I'm not sure we ever figured out enough what was happening on your system to track anything actionable for the Flutter team other than the issues we already have open.  Closing.

**Closed by jmagman** 2020-12-09 17:50 UTC
Labels: d: intellij, passed first triage, platform-ios, severe: crash, tool, will need additional triage
