### ISSUE TITLE
`FileSystemEntity.isWatchSupported` return true incorrectly on mobile 

### ISSUE THREAD

**Issue by Lootwig** [flutter/flutter#88974] opened 2021-08-26 16:49 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:

Insert anywhere, e.g. main.dart:

```
import 'dart:io';

...

print(FileSystemEntity.isWatchSupported);
File('/').watch().listen(print);
```

3. Run the app on an Android emulator

**Expected results:** Either prints "false" or does not throw

**Actual results:** Prints "true" and then throws when listening to the watch() stream

<details>
  <summary>Logs</summary>

```
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:62522/JnvrJmewoGg=/ws
Syncing files to device sdk gphone x86...
I/flutter ( 9950): true
E/flutter ( 9950): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FileSystemException: File system watching is not supported on this platform, path = ''
E/flutter ( 9950): #0      _FileSystemWatcher._watch (dart:io-patch/file_patch.dart:125:5)
E/flutter ( 9950): #1      FileSystemEntity.watch (dart:io/file_system_entity.dart:447:33)
E/flutter ( 9950): #2      main (package:watch_bug/main.dart:7:13)
E/flutter ( 9950): #3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter ( 9950): #4      _rootRun (dart:async/zone.dart:1354:13)
E/flutter ( 9950): #5      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter ( 9950): #6      _runZoned (dart:async/zone.dart:1789:10)
E/flutter ( 9950): #7      runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter ( 9950): #8      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter ( 9950): #9      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter ( 9950): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter ( 9950): 

```

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\...\AppData\Local\Android\Sdk\
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\...\AppData\Local\Android\Sdk\
    • ANDROID_SDK_ROOT = C:\Users\...\AppData\Local\Android\Sdk\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.1.2
    • Flutter plugin version 59.0.4
    • Dart plugin version 212.4746.57

[√] VS Code (version 1.58.2)
    • VS Code at C:\Users\...\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.1165]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 92.0.902.78

• No issues found!
```

</details>

**Comment by JaffaKetchup** [comment] 2022-04-02 08:51
Hi there, I'd like an answer to this question as well. I assumed Android watching would be OK since Android is based off Linux.

**Comment by stuartmorgan** [comment] 2022-08-16 18:09
This looks like a duplicate of https://github.com/dart-lang/sdk/issues/46261, which has since been fixed.

**Closed by stuartmorgan** 2022-08-16 18:09 UTC
Labels: platform-android, platform-ios, dependency: dart, has reproducible steps, found in release: 2.2, found in release: 2.6
