### ISSUE TITLE
[iOS]: File system watching is not supported on this platform

### ISSUE THREAD

**Issue by meli27** [flutter/flutter#99456] opened 2022-03-03 05:32 UTC
I'm getting `File system watching is not supported on this platform, path = '' `error trying to use Directory.watch on flutter.
I am using Mac Big Sur 11.2.3. M1
Does anyone know why? Please let me know. Thanks.

**Comment by darshankawar** [comment] 2022-03-03 08:23
@meli27 
Can you provide `flutter doctor -v` and steps to replicate along with platform on which you are getting this error ?

**Comment by meli27** [comment] 2022-03-04 00:28
```
[✓] Flutter (Channel dev, 2.11.0-0.1.pre, on macOS 11.2.3 20D91 darwin-arm,
    locale en-CR)
    • Flutter version 2.11.0-0.1.pre at
      /Users/melissavillalobos/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b101bfe32f (2 weeks ago), 2022-02-16 07:36:54 -0800
    • Engine revision e355993572
    • Dart version 2.17.0 (build 2.17.0-69.2.beta)
    • DevTools version 2.10.0-dev.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/melissavillalobos/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/melissavillalobos/Downloads/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/melissavillalobos/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.56.2)
    • VS Code at /Users/melissavillalobos/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • iPad Air (4th generation) (mobile) • CCD52F2D-F674-4FBE-A5F3-185408E7C7FB • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome
      98.0.4758.109

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```


And I'm getting this error on when using this library on iPad Air 4th gen (iOS 14.5). 
 
https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/43
On this line:

```
final Stream<void> stream =
        storeDirectory!.watch(events: fileSystemEvents).map((event) => null);

```

**Comment by darshankawar** [comment] 2022-03-04 05:03
> Channel dev, 2.11.0-0.1.pre

@meli27 the `dev` version has been already de-commissioned. Can you switch to latest master or stable and try the same and see if you still get same error ?

**Comment by meli27** [comment] 2022-03-04 06:00
` Flutter (Channel beta, 2.11.0-0.1.pre, on macOS 11.2.3 20D91 darwin-arm, locale en-CR)` I just updated, but I got the same issue

**Comment by darshankawar** [comment] 2022-03-04 13:36
@meli27 
Please provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that we can directly use and run to verify this.
Thanks.

**Comment by romreed** [comment] 2022-03-04 16:28
I got same issue!

**Comment by romreed** [comment] 2022-03-04 17:01
@darshankawar https://github.com/JaffaKetchup/flutter_map_tile_caching/tree/main/example
just take this example

**Comment by darshankawar** [comment] 2022-03-07 05:24
Closing this as a duplicate of https://github.com/flutter/flutter/issues/88974

**Comment by darshankawar** [comment] 2022-03-09 05:40
Thanks for the feedback @JaffaKetchup . Reopening.

**Comment by darshankawar** [comment] 2022-03-09 05:42
Running the code sample on iOS shows me the same error as reported. I'll label it for further insights from the team.

/cc @jmagman

**Comment by amos-joshua** [comment] 2022-07-20 10:06
In case it is of use to others, I published the small plugin I've been using as a workaround: [dispatch_source_watcher](https://pub.dev/packages/dispatch_source_watcher) It's an iOS-only package for listening to file system changes.

**Comment by tsinis** [comment] 2022-07-20 11:28
> In case it is of use to others, I published the small plugin I've been using as a workaround: [dispatch_source_watcher](https://pub.dev/packages/dispatch_source_watcher) It's an iOS-only package for listening to file system changes.

Hey, @amos-joshua correct me if I'm wrong, but there is already a package from Google that allows watching directories (with `DirectoryWatcher`) and files (with `FileWatcher`), called [watcher](https://pub.dev/packages/watcher), which provides similar Stream<WatchEvent>.

**Closed** 2022-08-16 18:11 UTC
Labels: platform-ios, documentation, has reproducible steps, found in release: 2.10, found in release: 2.11
