### ISSUE TITLE
[Web Canvaskit]Arabic text has an unexpected linebreak

### ISSUE THREAD

**Issue by navaronbracke** [flutter/flutter#103846] opened 2022-05-15 08:33 UTC
In Flutter 3.0 there are text rendering issues for Arabic text in some cases.

Note for triage: I reproduced it on Dartpad with Flutter 3.0, as I am still on Flutter 2.10.4 and could not test it locally on a device.
I will only be able to migrate to Flutter 3.0 in the next week or two, while I internally await any hotfixes to the stable release.
Therefore I cannot give any meaningful output for `flutter doctor -v` for Flutter 3.0.

The original report came from a discussion on the Flutter Discord.

## Steps to Reproduce

1. `flutter create myapp`
2. Replace the code in main.dart with the code sample
3. `flutter run`
4. The text renders in the middle of the screen, but in two lines.

**Expected results:** The Arabic text should have been rendered on one line.

**Actual results:** The Arabic text renders with a line break in the middle of the text.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final String title;

  const MyHomePage({
    Key? key,
    required this.title,
  }) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Center(
        child: Text(
          'ٱلْرَّحْمَـانُ'
        ),
      ),
    );
  }
}
```

</details>

<details>

### Dartpad output
![Arabic_discord](https://user-images.githubusercontent.com/23480364/168463815-944e33c8-bd60-4448-89d5-e3127ab53324.png)

</details>

**Comment by maheshmnj** [comment] 2022-05-16 08:50
Hi @navaronbracke, Thanks for filing the issue. I am able to reproduce the issue on stable and the master channel. The Arabic text goes multiline on the web with Canvaskit renderer and is a single liner with HTML renderer and on Desktop.

#### Desktop
<img width="912" alt="image" src="https://user-images.githubusercontent.com/31410839/168553700-6c4c2b7c-9bb1-49fb-8c44-8ef21d3d3fe5.png"> 

### Web

Canvaskit             |  HTML
:-------------------------:|:-------------------------:
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/31410839/168553847-b7cd0f3e-23eb-43b7-8b59-d7c9f6532a84.png"> |  <img width="1009" alt="image" src="https://user-images.githubusercontent.com/31410839/168554173-b2f33dad-594c-4c0d-a1f8-20b44d1df99b.png">


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (6 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
    • Flutter version 3.1.0-0.0.pre.419 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2eed8cbf93 (2 weeks ago), 2022-04-28 22:29:06 -0400
    • Engine revision dfdfe0b3b0
    • Dart version 2.18.0 (build 2.18.0-66.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your
        plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

Here is a similar issue: https://github.com/flutter/flutter/issues/103735 (Windows Desktop)

**Comment by limitless-brain** [comment] 2022-05-19 06:47
This also occurs on android.

**Comment by jason-simmons** [comment] 2022-05-24 18:53
Flutter 3 is using the new SkParagraph text renderer by default, and this is an issue in SkParagraph's implementation of line breaking.

SkParagraph may calculate incorrect widths for runs where the glyph positions returned by HarfBuzz are not monotonically increasing throughout the line.  The width computed by functions such as `TextStretch::extend` may reflect the position of the line's last glyph in codepoint order instead of the total width of all glyphs in the run.

If the width is too small, then SkParagraph may insert unnecessary line breaks.

**Comment by jason-simmons** [comment] 2022-05-24 19:11
Until this is fixed in SkParagraph, apps can work around this by reverting to the old Libtxt text renderer.

#### Android

Add this metadata tag to the app's manifest:

```
<meta-data
    android:name="io.flutter.embedding.android.EnableSkParagraph"
    android:value="false" />
```

Also override `getFlutterShellArgs` in the app's `FlutterActivity` subclass to provide the `--enable-skparagraph=false` flag:

```
public FlutterShellArgs getFlutterShellArgs() {
    return new FlutterShellArgs(new String[]{"--enable-skparagraph=false"});
}
```

#### iOS

Add this tag to `ios/Runner/Info.plist`:

```
<key>FLTEnableSkParagraph</key>
<false/>
```

**Comment by limitless-brain** [comment] 2022-05-27 11:32
@jason-simmons android not working after doing the required steps, it still using SKParagraph can you please provide a working example.

**Comment by limitless-brain** [comment] 2022-05-27 20:21
Thank you @jason-simmons, you save my day.
Finally, it works, the problem was the override provideFlutterEngine function by just_audio plugin.

Working example

App manifest

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="package name">
    ....
    <application
        android:icon="@mipmap/ic_launcher"
        android:label="app name">
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        // add this under application level
        <meta-data
            android:name="io.flutter.embedding.android.EnableSkParagraph"
            android:value="false" />

        <activity
            android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:exported="true"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <!-- Notified when user click the notification -->
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>

        </activity>
        ...
    </application>
</manifest>

```
Activity

```
import android.util.Log
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterShellArgs

class MainActivity : FlutterActivity() {
    override fun getFlutterShellArgs(): FlutterShellArgs {
        Log.d("Main Activity", "getFlutterShellArgs: false")
        return FlutterShellArgs(arrayOf("--enable-skparagraph=false"))
    }
}

```

**Comment by thexaib** [comment] 2022-06-12 20:20
i am facing with the same issue. On MacOS same thing happening. I am not compiling for android , so i can not apply the suggested fix. Please investigate to fix this issue on flutter 3.

`flutter doctor -v`
``` Flutter doctor
[✓] Flutter (Channel stable, 3.0.2, on Mac OS X 10.14.6 18G103 darwin-x64, locale en-US)
    • Flutter version 3.0.2 at /Volumes/Drive_E/softw/IDEnTools/flutter_sdk/fvm_flutter_caches/versions/3.0.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (4 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Volumes/Drive_E/softw/IDEnTools/android/AndroidSDK
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Volumes/Drive_E/softw/IDEnTools/android/AndroidSDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.3
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.14.6 18G103 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.61

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```
## Steps to Reproduce
- `flutter create testapp`
- Replace the code in main.dart with the code sample
- `flutter run`

## Expected Output
The arabic words should be on same line.
 
## Sample Code
```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      debugShowCheckedModeBanner: false,
      home: MainScreen(),
    );
  }
}

class BorderedContainer extends StatelessWidget {
  final Widget child;

  const BorderedContainer({Key? key, required this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(2.0),
      child: Container(
        decoration: BoxDecoration(
          border:
              Border.all(width: 0.5, color: Colors.black12.withOpacity(0.5)),
        ),
        child: child,
      ),
    );
  }
}

class MainScreen extends StatelessWidget {
  final List<List<String>> labels = [
    ["In the Name", "بِسْمِ"],
    ["(of) Allah", "ٱللَّهِ"],
    ["the Most Gracious", "ٱلرَّحْمَٰنِ"],
    ["the Most Merciful.", "ٱلرَّحِيمِ"],
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Arabic+English"),
      ),
      body: SingleChildScrollView(
        child: Center(
          child: BorderedContainer(
            child: Wrap(children: [
              ...labels.reversed.map((tple) {
                return BuildColumn(tple[0], tple[1]);
              }).toList(),
              BuildColumn(
                labels.map((e) => e[0] + " ").toList().join(),
                labels.map((e) => e[1] + " ").toList().join(),
              )
            ]),
          ),
        ),
      ),
    );
  }

  Widget BuildColumn(String english, String arabic) {
    const TextStyle style = TextStyle(fontSize: 24);
    return BorderedContainer(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          BorderedContainer(
            child: Text(
              arabic,
              style: style,
            ),
          ),
          BorderedContainer(
            child: Text(
              english,
              style: style,
            ),
          )
        ],
      ),
    );
  }
}

```

![Flutter 2.10.4](https://user-images.githubusercontent.com/3179501/173251547-f4fbd6cc-35b2-4f3b-b207-304e116d598e.jpg)
![Flutter 3.0.2](https://user-images.githubusercontent.com/3179501/173251556-8229a5a5-c1b3-4eb5-b8db-523dcbafee7f.jpg)

**Comment by jason-simmons** [comment] 2022-06-15 19:54
The text layout issue described here is not fixed in 3.0.2.

3.0.2 does contain a patch that makes it easier to revert Android applications to the old text layout engine, which is not affected by this issue (see https://github.com/flutter/flutter/issues/103846#issuecomment-1136334771)

This issue has been fixed on the current master and beta branches.

**Comment by SNNafi** [comment] 2022-08-18 20:01
How to __revert__ to the old Libtxt text renderer in __flutter windows__ ?

**Comment by hterkelsen** [comment] 2022-09-21 21:31
This is confirmed fixed in the latest engine.

**Closed by hterkelsen** 2022-09-21 21:31 UTC
Labels: framework, a: internationalization, dependency: skia, a: typography, platform-web, e: web_canvaskit, has reproducible steps, P3, found in release: 3.0, found in release: 3.1
