### ISSUE TITLE
Flutter Installer Package for GNU/Linux, Mac or Windows

### ISSUE THREAD

**Issue by MarlonJD** [flutter/flutter#87432] opened 2021-08-01 16:41 UTC
I saw many people having trouble about the first install of Flutter, android SDKs, plugins, gradle version etc.
It's hard to support all these and check these dependencies.

We can create installer script and GUI installer without Android Studio.
Android SDKs can be install via command line tools.
Confirmed versions can be installed from WGET or cURL and install on background.
Paths can be add after all those installation.
We can do something for license issues like you did before for android SDKs.
So what do you think about this?

**Comment by iapicca** [comment] 2021-08-01 17:03
@MarlonJD 
I totally agree with you
https://github.com/flutter/flutter/issues/71368

**Comment by TahaTesser** [comment] 2021-08-02 08:54
HI @MarlonJD 
The installer is proposed in https://github.com/flutter/flutter/issues/63619, you can add your comment about the features you need in the installer
Closing as duplicate of https://github.com/flutter/flutter/issues/63619

**Closed by TahaTesser** 2021-08-02 08:54 UTC
Labels: in triage
