### ISSUE TITLE
icon_tree_shaker.dart causes dead code diagnostic

### ISSUE THREAD

**Issue by eernstg** [flutter/flutter#53240] opened 2020-03-25 11:35 UTC
The location https://github.com/flutter/flutter/blob/0c5ffdc9efc4e04ed637645014465b656afc14a5/packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart#L191
gives rise to a `dead_code_on_catch_subtype` diagnostic:

```
   info • Dead code: This on-catch block won’t be executed because 'OSError' is a subtype of 'Exception' and hence will have been caught already • packages/flutter_tools/lib/src/build_system/targets/icon_tree_shaker.dart:191:7 • dead_code_on_catch_subtype
```

The second `catch` clause is unreachable and should be deleted.

**Comment by athomas** [comment] 2020-03-25 11:56
This was caused by this change: https://dart.googlesource.com/sdk/+/ae392b8e007f2a2ad42fab96b7156c0fc68c49c7

@ZichangG

**Comment by jonahwilliams** [comment] 2020-03-25 13:21
We could do something like commit an `ignore`, roll the change, and then remove it afterwards?

**Comment by zanderso** [comment] 2020-04-15 17:06
Added ignore here: https://github.com/flutter/flutter/pull/53258

@ZichangG Could you ping this issue when your `OSError` change rolls into Flutter?

**Comment by ZichangG** [comment] 2020-04-15 18:17
It landed last Friday. https://github.com/dart-lang/sdk/commit/17294842e90ff35d039f778f0721457b79766e47
It is in Flutter now. https://github.com/flutter/engine/pull/17654

**Closed** 2020-04-29 18:43 UTC
Labels: team, tool
