### ISSUE TITLE
[tool_crash] FileSystemException: Cannot copy file to 'C:\Users\Joshua\Desktop\Zenox\flutter_application_1\android\app\src\main\res\mipmap-hdpi\ic_launcher.png', path = 'C:\flutter\packages\flutter_tools\templates\app\android.tmpl\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied., errno = 5)

### ISSUE THREAD

**Issue by Joshua-cloud** [flutter/flutter#80300] opened 2021-04-12 20:01 UTC

**Comment by iapicca** [comment] 2021-04-12 21:39
self-duplicate of https://github.com/flutter/flutter/issues/80298

**Closed** 2021-04-12 22:46 UTC
