### ISSUE TITLE
CustomScrollView crashes when user flings then immediately drags

### ISSUE THREAD

**Issue by OfekI** [flutter/flutter#61473] opened 2020-07-14 18:49 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace the code in `main.dart` with [the following code](https://dartpad.dev/d48cb3a588d45b65c448fa570e28c4ba):
```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() async {
  runApp(
    MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: <Widget>[
            SliverPersistentHeader(
              delegate: MyDelegate(),
            ),
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (_, i) => Text('$i'),
              ),
            ),
          ],
        ),
      ),
    ),
  );
}

class MyDelegate implements SliverPersistentHeaderDelegate {
  double get minExtent => 0;
  double get maxExtent => 200;
  bool shouldRebuild(SliverPersistentHeaderDelegate other) => true;
  FloatingHeaderSnapConfiguration get snapConfiguration => null;
  OverScrollHeaderStretchConfiguration get stretchConfiguration => null;

  Widget build(
    BuildContext context,
    double shrinkOffset,
    bool overlapsContent,
  ) =>
      SnapListener(
        child: Center(
          child: Text('header'),
        ),
      );
}

class SnapListener extends StatefulWidget {
  final Widget child;

  SnapListener({this.child});

  @override
  _SnapListenerState createState() => _SnapListenerState();
}

class _SnapListenerState extends State<SnapListener> {
  ScrollPosition _position;

  @override
  Widget build(BuildContext context) => widget.child;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _position = Scrollable.of(context)?.position;
    _position.isScrollingNotifier.addListener(_isScrollingListener);
  }

  void _isScrollingListener() {
    if (!_position.isScrollingNotifier.value) {
      if (0 < _position.extentBefore && _position.extentBefore < 200) {
        if (_position.userScrollDirection == ScrollDirection.reverse) {
          _position.jumpTo(200);
        } else if (_position.userScrollDirection == ScrollDirection.forward) {
          _position.jumpTo(0);
        }
      }
    }
  }
}
```
3. Fling the ScrollView up and then immediately drag it down. Can use `testWidgets` to do this automatically with the following test:
```dart
testWidgets("doesn't crash if user flings then drags", (WidgetTester tester) async {
  await tester.pumpWidget(/* place widget here */);
  await tester.flingFrom(Offset(400,300), Offset.fromDirection(-math.pi / 2, 100), 500);
  await t.pump(); // this is optional
  await t.dragFrom(Offset(400,300), Offset.fromDirection(math.pi / 2, 100));
});
```
4. This occurs in DartPad as well (although the error information is absent)

**Expected results:** No assertion is thrown

**Actual results:** An assertion is thrown and the app crashes

══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 537 pos 12: '_hold == null':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      ScrollableState._handleDragStart (package:flutter/src/widgets/scrollable.dart:537:12)
#3      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:384:52)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:384:7)
#6      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:308:7)
#7      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
#8      GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
#17     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1099:17)
#18     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1087:35)
(elided 25 frames from class _AssertionError, class _FakeAsync, dart:async, and package:stack_trace)

Handler: "onStart"
Recognizer:
  VerticalDragGestureRecognizer#8de00
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by VladyslavBondarenko** [comment] 2020-07-15 09:52
Reproduces with current master `1.20.0-8.0.pre.102`.
To hit the exception manually, not with test, the gesture should be very short and fast 

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.20.0-8.0.pre.102, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-8.0.pre.102 at /Users/nevercode/dev/flutter
    • Framework revision f95f46e910 (4 hours ago), 2020-07-15 01:46:01 -0400
    • Engine revision be7595bafb
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • Redmi Note 7 (mobile)      • 6345c469                             • android-arm64  • Android 9 (API 28)
    • iPhone 11 Pro Max (mobile) • 9F9AFD9B-7F22-468E-8096-B47E993E0619 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-5
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)           • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by Piinks** [comment] 2020-07-15 17:01
I believe this is a duplicate of #14452. The root cause it that by triggering driven scrolling activities (i.e jumpTo, animateTo) based on scrolling notifiers, you can end up in a situation where one scrolling activity fires before another has completed.
I have seen some folks work around this by checking what kind of scroll activity it is in the notification handler in order to prevent activity clashing.
I'm going to close this as a dupe, if you feel this in't the same issue, let us know and we can re-open it! Thanks! :)

**Closed by Piinks** 2020-07-15 17:01 UTC
Labels: f: scrolling, found in release: 1.20, framework, has reproducible steps, severe: crash
