### ISSUE TITLE
Simpler way to load all assets easily

### ISSUE THREAD

**Issue by FaisalAbid** [flutter/flutter#10491] opened 2017-06-04 01:56 UTC
While porting an Android app to Flutter, here is my drawable-xxhdpi folder on android 
<img width="840" alt="screenshot 2017-06-03 21 53 42" src="https://cloud.githubusercontent.com/assets/253700/26758268/4090880a-48a7-11e7-8732-4ec1632e09e0.png">

Declaring all these assets in the pubspec is going to be a pain, I should be able to just point it to a folder, or perhaps have a standardized folder "assets" where I can throw all my images in.

**Comment by eseidelGoogle** [comment] 2017-06-04 17:27
See also https://github.com/flutter/flutter/issues/4890 and https://github.com/flutter/flutter/issues/9900.

**Comment by sethladd** [comment] 2017-06-05 15:53
@FaisalAbid can you please "thumbs up" 4890 and 9900 ? That helps us sort. Thank you!

**Comment by Hixie** [comment] 2018-04-24 23:53
Duplicate of #4890.

**Closed by Hixie** 2018-04-24 23:53 UTC
