### ISSUE TITLE
url_launcher throws missing plugin exception when published (android)

### ISSUE THREAD

**Issue by ilkerokutman** [flutter/flutter#69674] opened 2020-11-03 13:30 UTC
## Steps to Reproduce

```
  _launchCall() async {
    try {
      if (await canLaunch("tel:${appSettings.phone}")) {
        var res = await launch("tel:${appSettings.phone}");
        Toast.show(res.toString(), context);
      } else {
        Toast.show("could not dial ${appSettings.phone}", context);
      }
    } catch (ex) {
      Toast.show("${ex.toString()}", context);
    }
  }
```

iOS works on debug and release runs and works on Testflight & Appstore
Android works on debug
Android works with command "flutter run --release"  (with signature)
Actually cant see the toast, immediately switchs to dial screen.

Android does not work when published (beta release or internal app sharing) "flutter build appbundle" or apks
Exception toast says: 
`MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)`

<details>
<summary>pubspec.yaml</summary>

```
name: myapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.53+2020110306

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.1 #flutter pub run flutter_launcher_icons:main -f pubspec.yaml
  dio: ^3.0.10
  get: ^3.12.1
  flutter_guid: ^0.1.0
  toast: ^0.1.5
  image_picker: ^0.6.7+11
  modal_progress_hud: ^0.1.3
  flutter_svg: ^0.19.0
  flutter_local_notifications: ^2.0.0
  rflutter_alert: ^1.1.0
  url_launcher: ^5.7.8
  flutter_datetime_picker: ^1.4.0
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon_call.svg
    - assets/images/icon_enroll.svg
    - assets/images/icon_link.svg
    - assets/images/icon_pressure_reminder.svg
    - assets/images/icon_profile.svg
    - assets/images/icon_query.svg

```
</details>

<details>
  <summary>flutter doctor -v</summary>

```
```

```
```

io@ios-Mac-mini dunlop % flutter doctor -v
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-TR)
    • Flutter version 1.22.3 at /Users/io/Library/Flutter
    • Framework revision 8874f21e79 (5 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/io/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9002
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • GT N7100 (mobile)            • 4df1f32b147e9f67                         • android-arm   • Android 5.1.1 (API 22)
    • Redmi Note 8 Pro (mobile)    • onr4kz8x49kve6pj                         • android-arm64 • Android 10 (API 29)
    • Company iPhone’u (mobile) • 3a2b7cd02008d86c4fafb29185a53f540a8f09cb • ios           • iOS 10.3.4
    ! Error: Company iPhone’u is busy: Making Company iPhone’u ready for development. Xcode will continue when Company iPhone’u is finished. (code -10)

• No issues found!

```
```

</details>

<details>
<summary>building</summary>

```
io@ios-Mac-mini myapp % flutter clean && flutter build appbundle
Cleaning Xcode workspace...                                         2.9s
Deleting build...                                                  260ms
Deleting .dart_tool...                                              19ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting App.framework...                                            3ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in dunlop...                              0.5s
Removed unused resources: Binary resource data reduced from 74KB to 71KB: Removed 3%
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        41.9s
✓ Built build/app/outputs/bundle/release/app-release.aab (21.1MB).

```
</details>

**Comment by darshankawar** [comment] 2020-11-04 06:50
@ilkerokutman 
I tried the official `url_launcher` plugin and built a release app of it using following commands and launched it on Android device 8.1.0, which worked fine. The app launched properly and I was able to use all the features of the example.

```
dhs@Dhss-MacBook-Pro example % flutter build appbundle
Running "flutter pub get" in example...                             0.6s
Removed unused resources: Binary resource data reduced from 35KB to 21KB: Removed 40%
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                        58.8s
✓ Built build/app/outputs/bundle/release/app.aab (16.3MB).

dhs@Dhss-MacBook-Pro release % bundletool build-apks --bundle=./app.aab --output=./app.apks
INFO: The APKs will be signed with the debug keystore found at '/Users/dhs/.android/debug.keystore'.
dhs@Dhss-MacBook-Pro release % bundletool install-apks --apks=app.apks
The APKs have been extracted in the directory: /var/folders/w0/6j3m5z913hbd94smbfmz6y6h0000gn/T/5025672729198249020
```

[69674.mp4.zip](https://github.com/flutter/flutter/files/5485901/69674.mp4.zip)

Can you provide a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by ilkerokutman** [comment] 2020-11-04 11:04
I copied my project, cleared irrelevant code and renamed branding strings and replaced images.
[https://github.com/ilkerokutman/example_url_launcher](url)

Also published to Google Play Open Testing.. 
I will update link when reviewing completed.

**Comment by kaciula** [comment] 2020-11-08 19:39
I am also seeing a similar issue. My app runs ok if I build the app as an apk release. But if I build it as an appbundle, it crashes with MissingPluginException. 

My CI pushed the buggy appbundle on the Play Store and now I get constant MissingPluginExceptions. It varies which plugin is to blame so I think it'a actually not the fault of one particular plugin.

I have 2 apps in the wild with this behavior and I've spent hours figuring out that the cause is what I mentioned above. I couldn't find a fix so I had to revert to a previous working version.

I'm using the latest stable flutter version 1.22.3 and all the latest plugins.

**Comment by ilkerokutman** [comment] 2020-11-10 12:24
Strangely the project I copied and published seemed to work!

Not sure but refactoring android package name may cause that.
This time:
1. Created new flutter app with new name in new folder ("flutter create ." did not solve it. )
2. Refactored android package name
3. copied old projects lib folder contents and pubspec.yaml to new one
4. published and it worked.

Before that I always did package name refactoring after copying and when published issue revealed.

Anyway I don't have the problem now. Thank you for your time.

**Comment by darshankawar** [comment] 2020-11-10 13:25
Thanks @ilkerokutman for confirming and glad to know your issue is resolved.
Closing this based on your comment above.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-11-10 13:25 UTC
Labels: in triage
