### ISSUE TITLE
don't run flutter uwp app

### ISSUE THREAD

**Issue by Hadi7546** [flutter/flutter#82951] opened 2021-05-19 22:08 UTC
Hey There

I'm After runnig flutter run -d winuwp:
<details>
  <summary>Logs</summary>
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: the following warning is treated as an error (compiling source file E:\test_uwp\winuwp\runner_uwp\flutter_frameworkview.cpp) [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): error C2220: the following warning is treated as an error (compiling source file E:\test_uwp\winuwp\runner_uwp\main.cpp) [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncOperationCompletedHandler<TResult>,H>' that has a non-virtual destructor results in undefined behavior [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncOperationCompletedHandler<TResult>,H>' that has a non-virtual destructor results in undefined behavior [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncOperationCompletedHandler<TResult>,H>' that has a non-virtual destructor results in undefined behavior [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncOperationCompletedHandler<TResult>,H>' that has a non-virtual destructor results in undefined behavior [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract class 'winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>' that has a non-virtual destructor results in undefined behavior [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract class 'winrt::impl::implements_delegate<winrt::Windows::UI::Core::DispatchedHandler,H>' that has a non-virtual destructor results in undefined behavior [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncActionCompletedHandler,H>' that has a non-virtual destructor results in undefined behavior [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::AsyncActionCompletedHandler,H>' that has a non-virtual destructor results in undefined behavior [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::ApplicationModel::Core::CoreApplicationView,winrt::Windows::ApplicationModel::Activation::IActivatedEventArgs>,H>' that has a non-virtual destructor results in undefined behavior [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\Include\10.0.18362.0\cppwinrt\winrt/base.h(6508,17): warning C5205: delete of an abstract class 'winrt::impl::implements_delegate<winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::ApplicationModel::Core::CoreApplicationView,winrt::Windows::ApplicationModel::Activation::IActivatedEventArgs>,H>' that has a non-virtual destructor results in undefined behavior [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]
E:\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(482,5): error MSB4181: The "CompileXaml" task returned false but did not log an error. [E:\test_uwp\build\winuwp\runner_uwp\app.vcxproj]

</details>

Flutter doctor:
<details>
  <summary>Flutter Doctor</summary>

[✓] Flutter (Channel master, 2.3.0-13.0.pre.35, on Microsoft Windows [Version 10.0.19042.928], locale fa-IR)
    • Flutter version 2.3.0-13.0.pre.35 at E:\SDKs\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b9cd30f00a (12 hours ago), 2021-05-19 06:04:03 -0400
    • Engine revision d844ce3784
    • Dart version 2.14.0 (build 2.14.0-119.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\SDKs\Android\android-sdk
    • Platform android-30, build-tools 31.0.0
    • ANDROID_HOME = E:\SDKs\Android\android-sdk
    • ANDROID_SDK_ROOT = E:\SDKs\Android\android-sdk\cmdline-tools
    • Java binary at: C:\Program Files\Java\jdk8u202-b08\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.7.0)
    • Visual Studio at E:\APP\VisualStudio
    • Visual Studio Enterprise 2019 version 16.7.30330.147
    • Windows 10 SDK version 10.0.18362.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\HADI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • Windows (desktop)       • windows • windows-x64     • Microsoft Windows [Version 10.0.19042.928]
    • Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
    • Chrome (web)            • chrome  • web-javascript  • unknown
    • Edge (web)              • edge    • web-javascript  • Microsoft Edge 90.0.818.62
</details>

**Comment by stuartmorgan** [comment] 2021-05-19 22:11
Duplicate of https://github.com/flutter/flutter/issues/82917

**Closed by stuartmorgan** 2021-05-19 22:11 UTC
