### ISSUE TITLE
[shared_preferences] Support named preferences on Android

### ISSUE THREAD

**Issue by danielgomezrico** [flutter/flutter#66646] opened 2020-09-25 13:29 UTC
## Use case

I have multiple views and all of them have multiple keys, there's a big possibility of key clashing and so another class may store a value with the same key that another class uses and then there will be a bug that is hard to track.

## Proposal

Allow to get a preference name in the `getInstance` and so, every class will not have to think about this for every `key`.

```dart
SharedPreferences.getInstance('my_preference_name');
```

### On Android
On shared preferences you can get that by:
```kotlin
context.getSharedPreferences(name, Context.MODE_PRIVATE)
```

### On iOS

It looks like [there's a function that accepts a name](https://developer.apple.com/documentation/foundation/nsuserdefaults/1409957-initwithsuitename?language=objc) but I am not sure:

```swift
initWithSuiteName
```

**Comment by pedromassangocode** [comment] 2020-10-27 14:03
Closing as duplicate of https://github.com/flutter/flutter/issues/64739.
Please follow up on that issue for more updates.

Thank you

**Comment by danielgomezrico** [comment] 2020-10-27 14:17
@pedromassangocode after checking #64739 it only mentions iOS implementation but what about the android one?

**Comment by pedromassangocode** [comment] 2020-10-28 08:13
Hi @danielgomezrico 
Thanks for checking this out. 
I notice that https://github.com/flutter/flutter/issues/64739 already has a PR to fix the same issue but for iOS only 
so let's leave this open to track the Android side.

**Comment by danielgomezrico** [comment] 2024-12-10 19:15
@pedromassangocode @stuartmorgan do you have a vision on when will this be prioritized?

**Comment by stuartmorgan** [comment] 2024-12-12 19:54
This is a duplicate of https://github.com/flutter/flutter/issues/14337

@danielgomezrico Please see https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-issues-or-prs and https://github.com/flutter/flutter/blob/master/docs/contributing/issue_hygiene/README.md#when-will-my-bug-be-fixed

**Closed by stuartmorgan** 2024-12-12 19:54 UTC
Labels: c: new feature, platform-android, p: shared_preferences, package, c: proposal, P3, team-android, triaged-android
