### ISSUE TITLE
App screen flickers and freezes, when I restart it, it goes away.  it doesn't always happen.

### ISSUE THREAD

**Issue by wangxiaodong1995** [flutter/flutter#104790] opened 2022-05-27 02:15 UTC
Facing same issue on iOS v15.4.1. Getting similar flickering consistently while using app.

[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.51.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

**Comment by danagbemava-nc** [comment] 2022-05-27 06:46
Closing this as a duplicate of #100522. 

Kindly provide any information you can in that thread. 

Thank you

**Closed by danagbemava-nc** 2022-05-27 06:46 UTC
Labels: in triage
