### ISSUE TITLE
Exception: Build process failed (Linux)

### ISSUE THREAD

**Issue by Meta-Cortex** [flutter/flutter#62793] opened 2020-08-03 17:16 UTC
**[xxxxx@localhost graphql_project]$ flutter doctor --verbose**
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Downloading android-arm-profile/linux-x64 tools...                  1.9s
Downloading android-arm-release/linux-x64 tools...                  1.7s
Downloading android-arm64-profile/linux-x64 tools...                1.3s
Downloading android-arm64-release/linux-x64 tools...                1.3s
Downloading android-x64-profile/linux-x64 tools...                  1.6s
Downloading android-x64-release/linux-x64 tools...                  1.3s
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-1.0.pre at /home/xxxxx/snap/flutter/common/flutter
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version 1.47.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.13.1

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 2 categories.

**[xxxxx@localhost graphql_project]$ flutter run -d Linux --verbose**
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ +389 ms] executing: [/home/xxxxx/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +108 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] f25bd9c55c48c139524139b477d04b13e9f36b2c
[   +4 ms] executing: [/home/xxxxx/snap/flutter/common/flutter/] git tag --contains HEAD
[ +331 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.21.0-1.0.pre
           1.21.0-5.0.pre
[  +32 ms] executing: [/home/xxxxx/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/home/xxxxx/snap/flutter/common/flutter/] git ls-remote --get-url origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +119 ms] Unable to locate an Android SDK.
[  +61 ms] executing: [/home/xxxxx/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] dev
[ +166 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +26 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +119 ms] Unable to locate an Android SDK.
[  +85 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +651 ms] Generating /home/xxxxx/Documents/flutter_projects/graphql_project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +445 ms] Starting incremental build...
[  +10 ms] Initializing file store
[  +80 ms] Skipping target: gen_localizations
[  +32 ms] complete
[  +22 ms] Launching lib/main.dart on Linux in debug mode...
[  +36 ms] /home/xxxxx/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/xxxxx/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/xxxxx/snap/flutter/common/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tools.CLPIAE/flutter_tool.MJOOCD/app.dill --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill.track.dill
[ +152 ms] Building Linux application...
[ +127 ms] <- compile package:graphql_project/main.dart
[  +18 ms] executing: [build/linux/debug/] cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug /home/xxxxx/Documents/flutter_projects/graphql_project/linux
[ +725 ms] -- Configuring done
[   +1 ms] -- Generating done
[        ] -- Build files have been written to: /home/xxxxx/Documents/flutter_projects/graphql_project/build/linux/debug
[  +62 ms] executing: ninja -C build/linux/debug install
[  +30 ms] ninja: Entering directory `build/linux/debug'
[+19992 ms] [1/5] Generating /home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/libflutter_linux_gtk.so,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_basic_message_channel.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_binary_codec.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_binary_messenger.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_dart_project.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_engine.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_json_message_codec.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_json_method_codec.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_message_codec.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_method_call.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_method_channel.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_method_codec.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_method_response.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_plugin_registrar.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_plugin_registry.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_standard_message_codec.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_standard_method_codec.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_string_codec.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_value.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/fl_view.h,
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/flutter_linux/flutter_linux.h, _phony_
[  +20 ms] [ +685 ms] executing: [/home/xxxxx/snap/flutter/common/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [ +260 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] [   +1 ms] f25bd9c55c48c139524139b477d04b13e9f36b2c
[        ] [   +2 ms] executing: [/home/xxxxx/snap/flutter/common/flutter/] git tag --contains HEAD
[        ] [ +468 ms] Exit code 0 from: git tag --contains HEAD
[        ] [        ] 1.21.0-1.0.pre
[        ]            1.21.0-5.0.pre
[  +10 ms] [  +69 ms] executing: [/home/xxxxx/snap/flutter/common/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] [  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] [        ] origin/dev
[        ] [        ] executing: [/home/xxxxx/snap/flutter/common/flutter/] git ls-remote --get-url origin
[        ] [  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[   +7 ms] [ +164 ms] Unable to locate an Android SDK.
[        ] [  +45 ms] executing: [/home/xxxxx/snap/flutter/common/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] dev
[        ] [ +297 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +14 ms] [   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] [   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [  +19 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +4 ms] [   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +13 ms] [   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +9 ms] [   +6 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +5 ms] [  +39 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [  +14 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [   +6 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +6 ms] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +9 ms] [   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] [   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [   +7 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] [   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +10 ms] [   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [ +507 ms] Initializing file store
[        ] [  +45 ms] Done initializing file store
[        ] [ +166 ms] Skipping target: gen_localizations
[        ] [+5615 ms] Skipping target: kernel_snapshot
[  +14 ms] [+6546 ms] Skipping target: unpack_linux
[        ] [+1285 ms] Skipping target: debug_bundle_linux_assets
[   +1 ms] [   +2 ms] Persisting file store
[        ] [  +56 ms] Done persisting file store
[   +1 ms] [  +33 ms] build succeeded.
[        ] [  +64 ms] "flutter assemble" took 14,498ms.
[        ] [ +207 ms] ensureAnalyticsSent: 175ms
[  +11 ms] [  +14 ms] Running shutdown hooks
[        ] [  +11 ms] Shutdown hooks complete
[   +4 ms] [   +1 ms] exiting with code 0
[+2929 ms] [2/5] Building CXX object CMakeFiles/graphql_project.dir/flutter/generated_plugin_registrant.cc.o
[ +327 ms] [3/5] Building CXX object CMakeFiles/graphql_project.dir/my_application.cc.o
[ +569 ms] [4/5] Linking CXX executable graphql_project
[        ] FAILED: graphql_project 
[        ] : && /snap/flutter/21/usr/bin/clang++  -g  -L/snap/flutter/21/usr/lib/gcc/x86_64-linux-gnu/8 -L/snap/flutter/21/usr/lib/x86_64-linux-gnu
-L/snap/flutter/21/usr/lib/ CMakeFiles/graphql_project.dir/main.cc.o CMakeFiles/graphql_project.dir/my_application.cc.o
CMakeFiles/graphql_project.dir/flutter/generated_plugin_registrant.cc.o  -o graphql_project
-Wl,-rpath,/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral: /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgtk-3.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk-3.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libpango-1.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libatk-1.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo-gobject.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libcairo.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so
/home/xxxxx/Documents/flutter_projects/graphql_project/linux/flutter/ephemeral/libflutter_linux_gtk.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libgio-2.0.so
/snap/flutter/current/usr/lib/x86_64-linux-gnu/libgobject-2.0.so /snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[   +3 ms] //lib64/libblkid.so.1: undefined reference to `fcntl64@GLIBC_2.28'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ] ninja: build stopped: subcommand failed.
[ +174 ms] Building Linux application... (completed in 25.0s)
[+6248 ms] Exception: Build process failed
[  +31 ms] "flutter run" took 33,185ms.
[  +29 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:593:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:869:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +267 ms] ensureAnalyticsSent: 258ms
[   +3 ms] Running shutdown hooks
[   +1 ms] Shutdown hook priority 4
[   +7 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1

**Comment by stuartmorgan** [comment] 2020-08-03 18:42
Duplicate of https://github.com/flutter/flutter/issues/61329

**Closed by stuartmorgan** 2020-08-03 18:42 UTC
