### ISSUE TITLE
Hot Update Support

### ISSUE THREAD

**Issue by Mrjordon88** [flutter/flutter#106465] opened 2022-06-23 07:51 UTC
Does flutter now have hot update support, especially for IOS projects
The development project team needs to hot update the IOS project of flutter 😂

**Comment by ervindobri** [comment] 2022-06-23 07:53
https://github.com/flutter/flutter/issues/14330

**Comment by Mrjordon88** [comment] 2022-06-23 07:58
> 

thank you for your prompt reply.

**Comment by huycozy** [comment] 2022-06-23 11:23
Closing as duplicate of #14330, so please follow up on it for further updates.

**Closed by huycozy** 2022-06-23 11:23 UTC
Labels: in triage
