### ISSUE TITLE
[LUCI] We should shift parts of the engine build to the engine repo

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#28620] opened 2019-02-28 00:37 UTC
Today, the engine recipe is responsible for building and packaging assets.  It should really just be responsible for setting up the environment, and then should shell out to a script in the engine to actually run `gn` and `ninja` in the right configurations - and a script to do the packaging.

This would help when we want to build older commits of the engine for whatever reason - today, if the recipe has gone out of sync with the artifacts/configurations in that commit, there's no good way to recover.

**Comment by CaseyHillers** [comment] 2021-01-21 23:38
Marking as duplicate of https://github.com/flutter/flutter/issues/73583 as @christopherfujino is working on this.

**Closed by CaseyHillers** 2021-01-21 23:38 UTC
Labels: a: tests, passed secondary triage, team, team: infra
