### ISSUE TITLE
NestedScrollView + TabBarView + AutomaticKeepAliveClientMixin Abnormal behavior

### ISSUE THREAD

**Issue by HaijunWei** [flutter/flutter#73155] opened 2020-12-31 02:08 UTC
Please watch the two videos.

Did not use `AutomaticKeepAliveClientMixin`.
https://user-images.githubusercontent.com/7686137/103390437-5aa20800-4b4f-11eb-917b-ede9a4bdc351.mp4

Used `AutomaticKeepAliveClientMixin`.
https://user-images.githubusercontent.com/7686137/103390442-6097e900-4b4f-11eb-921a-65a86625525a.mp4

After sliding the second page, the `headerSliver` behaves abnormally when sliding the first page again.

``` dart
class DemoPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Demo'),
      ),
      body: NestedScrollView(
        headerSliverBuilder: (context, _) {
          return [
            SliverToBoxAdapter(
              child: Container(
                height: 200,
                color: Colors.red,
              ),
            )
          ];
        },
        body: DefaultTabController(
          length: 2,
          child: TabBarView(
            children: [
              _ListPage1(),
              _ListPage2(),
            ],
          ),
        ),
      ),
    );
  }
}

class _ListPage1 extends StatefulWidget {
  const _ListPage1({
    Key key,
  }) : super(key: key);

  @override
  __ListPage1State createState() => __ListPage1State();
}

class __ListPage1State extends State<_ListPage1>
    with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return ListView.builder(
      itemCount: 100,
      itemBuilder: (context, index) {
        return Container(
          height: 50,
          color: index % 2 == 0 ? Colors.green : Colors.blue,
          alignment: Alignment.center,
          child: Text(index.toString()),
        );
      },
    );
  }

  @override
  bool get wantKeepAlive => true;
}

class _ListPage2 extends StatefulWidget {
  const _ListPage2({
    Key key,
  }) : super(key: key);

  @override
  __ListPage2State createState() => __ListPage2State();
}

class __ListPage2State extends State<_ListPage2>
    with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return ListView.builder(
      itemCount: 5,
      itemBuilder: (context, index) {
        return Container(
          height: 50,
          color: index % 2 == 0 ? Colors.yellow : Colors.amber,
          alignment: Alignment.center,
          child: Text(index.toString()),
        );
      },
    );
  }

  @override
  bool get wantKeepAlive => true;
}
```

**Comment by darshankawar** [comment] 2020-12-31 07:10
@HaijunWei 
Can you check out [this](https://github.com/flutter/flutter/issues/36419) similar open issue and confirm if it resemble yours ?

**Comment by HaijunWei** [comment] 2021-01-04 01:15
Yes, the problem he described also exists

**Comment by darshankawar** [comment] 2021-01-04 06:19
@HaijunWei 
Please provide `flutter doctor -v`.

**Comment by HaijunWei** [comment] 2021-01-04 08:49
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B29 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 1.22.5 at /Users/haijun/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/haijun/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)

**Comment by darshankawar** [comment] 2021-01-04 11:52
@HaijunWei 
What's the issue here again ? I can't find the difference between the videos you linked earlier.

**Comment by HaijunWei** [comment] 2021-01-04 15:54
Please take a closer look. After switching tabs back and forth, headerSliver will appear as if float is turned on, but I did not turn on float.

**Comment by darshankawar** [comment] 2021-01-05 06:29
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11
      (API 30) (emulator)

! Doctor found issues in 1 category.


```

</details>

**Comment by a1005342094** [comment] 2021-01-15 07:09
I have also encountered this problem. Has it been solved?

**Comment by HaijunWei** [comment] 2021-01-16 03:01
No, waiting for the official solution.

**Comment by rikai-trongpq** [comment] 2022-01-21 09:32
This problem has been raised for a long time. Are there any restoration plans in the near future?

**Comment by Piinks** [comment] 2022-06-16 22:39
This looks like a duplicate of https://github.com/flutter/flutter/issues/81619 I am going to close this to focus conversation and work in one place, please continue to follow https://github.com/flutter/flutter/issues/81619.

If you feel that this is a separate issue, let us know and we can take another look! Thanks!

**Closed by Piinks** 2022-06-16 22:39 UTC
Labels: framework, f: scrolling, passed first triage, has reproducible steps, found in release: 1.22
