### ISSUE TITLE
Icon does not clip when it is rendered outside of bounds

### ISSUE THREAD

**Issue by Sasikumar3595** [flutter/flutter#100603] opened 2022-03-23 07:17 UTC
We have created the application with custom widgets, and it has an option to reduce or increase the icon, but the icon will render outside it bounds while increase the size 

## Steps to Reproduce

1. Run the sample code added in the below code sample
2. Icon will render outside of its bounds

**Expected results:**

- The icon widget will crop its region outside of its bounds

**Actual results:** 

- The icon will render outside of it bounds
![Screen Shot 2022-03-23 at 12 47 03 PM](https://user-images.githubusercontent.com/44917578/159644356-08f0c508-c6fc-4c0b-b367-407afebb026b.png)

<details>
<summary>Code sample</summary>

```dart

Container(
  color: Colors.yellow,
  height: 15,
    width: 15,
  child: Icon(Icons.ac_unit, size: 20, color: Colors.red),
)

```

</details>

<details>
  <summary>Logs</summary>

```
Not Applicable
```

</details>

**Comment by danagbemava-nc** [comment] 2022-03-23 08:35
Hi @Sasikumar3595, the default clip behavior is `Clip.none`. You need to specify a Clip behavior before the icon is clipped. With the current code sample that you have shared, you have to change it to something like the code below to get it to work how you want. See https://api.flutter.dev/flutter/widgets/Container/clipBehavior.html for more information. 

Closing as this is working as intended. 

Thank you

```
Container(
          decoration: BoxDecoration(
             color: Colors.yellow,
          ),
          clipBehavior: Clip.antiAlias,
         
          height: 15,
          width: 15,
          child: const Icon(Icons.ac_unit, size: 20, color: Colors.red),
        ),
```

**Closed by danagbemava-nc** 2022-03-23 08:35 UTC
Labels: in triage
