### ISSUE TITLE
integration_test: support --flavor in flutter test

### ISSUE THREAD

**Issue by xvrh** [flutter/flutter#82898] opened 2021-05-19 09:14 UTC
## Steps to Reproduce

1. Create a project that use several flavors (https://flutter.dev/docs/deployment/flavors)
2. Run an integration test: `flutter test integration_test/my_test.dart`
3. Get the error message 
```
The Xcode project defines schemes: dev, prod
Exception: You must specify a --flavor option to select one of the available schemes.
```

4. Try to specify the `--flavor` option: `flutter test --flavor dev integration_test/my_test.dart`

==>
**`Could not find an option named "flavor".`**

<details>
  <summary>Logs</summary>

[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-BE)
    • Flutter version 2.2.0 at /Users/xavier/projects/flutter_stable
    • Framework revision b22742018b (4 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xavier/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/xavier/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/xavier/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.1)
    • IntelliJ at /Users/xavier/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 56.0.3
    • Dart plugin version 203.8173

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (6 available)
    • SM A300FU (mobile)       • 46f057fd                             • android-arm    • Android 6.0.1 (API 23)
    • Moto G 5 Plus (mobile)   • ZY224FKBCL                           • android-arm    • Android 8.1.0 (API 27)
    • Xavier’s iPhone (mobile) • 00008030-00012D9C0212802E            • ios            • iOS 14.4.2
    • iPhone 11 Pro (mobile)   • EDF6FADF-F5D7-4A4D-8C3A-B9A3231F49E6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)          • macos                                • darwin-x64     • Mac OS X 10.15.7 19H15 darwin-x64
    • Chrome (web)             • chrome                               • web-javascript • Google Chrome 90.0.4430.212

! Doctor found issues in 1 category.

</details>

**Comment by darshankawar** [comment] 2021-05-19 12:08
@xvrh 
It seems to be already supporting if I am not wrong.  I tried by using the official `integration_test` package [example](https://github.com/flutter/flutter/tree/master/packages/integration_test/example) on stable version (2.0.6) and added below demo flavors:

```
flavorDimensions "app"
    productFlavors {

        app1 {
            dimension "app"
            applicationId "com.example.integration_test_example.app1"
            versionCode 1
            versionName "1.0"
        }

        app2 {
            dimension "app"
            applicationId "com.example.integration_test_example.app2"
            versionCode 1
            versionName "1.0"
        }
    }
```

And then used below command to run with flavor app1:

`flutter drive --driver=test_driver/integration_test.dart --target=integration_test/example_test.dart --flavor app1`

I followed these instructions for the command:  https://github.com/flutter/flutter/tree/master/packages/integration_test#integration_test

See if it works for you and answers your question.

**Comment by xvrh** [comment] 2021-05-19 12:20
@darshankawar I don't use `flutter drive`, I use `flutter test integration_test`.

`flutter drive` write this warning telling me to use `flutter test`

```
> flutter drive --driver...

flutter: Warning: integration_test plugin was not detected.

If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
```

**Comment by darshankawar** [comment] 2021-05-20 06:50
@xvrh 
I haven't tried it on 2.2.0 yet, but going by your note, trying to run `flutter drive --driver=test_driver/integration_test.dart --target=integration_test/example_test.dart --flavor app1` gives you the above warning ?

**Comment by xvrh** [comment] 2021-05-20 07:59
@darshankawar Yes

When I run:
```
flutter drive --flavor dev \
    --driver=test_driver/integration_test.dart \
    --target=integration_test/login_test.dart
```

This is the full warning I see with Flutter 2.2:

```
 flutter: Warning: integration_test plugin was not detected.
           
If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
           
If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:
           
https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
```

And when I try to follow the advice, I'm stuck with `--flavor` not supported in `flutter test integration_test`

**Comment by darshankawar** [comment] 2021-05-21 06:05
Thanks for the details.

**Comment by acoutts** [comment] 2021-08-02 12:11
I'm noticing the same thing, and every time I upload an iOS test to firebase test lab the test result is "inconclusive", even on a simple test like `expect(true, true)`. Is there a workaround to use xctest integration tests with flavors?

**Comment by HelloCore** [comment] 2021-08-04 11:34
Not sure if there is any reason to not enable flavor option on `flutter test`

Work around here is to modify `flutter_tools` on your local by adding `usesFlavorOption();` to https://github.com/flutter/flutter/blob/8212b58a7f5816a1d6d013cf9c5df9eef9bcc01e/packages/flutter_tools/lib/src/commands/test.dart#L70

And remove 
```
$FLUTTER_SDK/bin/cache/flutter_tools.snapshot
$FLUTTER_SDK/bin/cache/flutter_tools.stamp
```

After that you can run with this command
```
$ flutter test --flavor develop -d iPhone integration_test/bla_bla.dart
```

**Comment by spekary** [comment] 2021-10-05 02:15
Looks like this is stalled. Any way to get it moving?

**Comment by tudor07** [comment] 2021-10-13 08:17
Hi, I also need this feature. Looks like `flutter drive` does not support coverage but `flutter test` does so we need to use `flutter test`. The problem is our app uses flavors but `flutter test` does not support flavors. We need `flutter test` + flavor support.

**Comment by ToniTornado** [comment] 2021-10-13 10:25
@HelloCore's solution is working very well for me. You just have to repeat the procedure after each Flutter version upgrade. So until the fix makes it to stable branch, you can already use that.

**Comment by miroslavkudrnac** [comment] 2021-10-18 07:30
Created PR https://github.com/flutter/flutter/pull/91981

**Comment by jiahaog** [comment] 2021-10-21 05:50
Thanks for creating #89045 and #91981! We'd be happy to merge either of these PRs if the comments there have been addressed.

**Comment by Wian-TMC** [comment] 2021-11-08 09:54
> Not sure if there is any reason to not enable flavor option on `flutter test`
> 
> Work around here is to modify `flutter_tools` on your local by adding `usesFlavorOption();` to
> 
> https://github.com/flutter/flutter/blob/8212b58a7f5816a1d6d013cf9c5df9eef9bcc01e/packages/flutter_tools/lib/src/commands/test.dart#L70
> 
> And remove
> 
> ```
> $FLUTTER_SDK/bin/cache/flutter_tools.snapshot
> $FLUTTER_SDK/bin/cache/flutter_tools.stamp
> ```
> 
> After that you can run with this command
> 
> ```
> $ flutter test --flavor develop -d iPhone integration_test/bla_bla.dart
> ```

After trying this I am now getting the following error:
```
Building flutter tool...
Unhandled exception:
Invalid argument(s): Duplicate option or alias "flavor".
#0      ArgParser._addOption (package:args/src/arg_parser.dart:292:7)
#1      ArgParser.addOption (package:args/src/arg_parser.dart:204:5)
#2      FlutterCommand.usesFlavorOption (package:flutter_tools/src/runner/flutter_command.dart:873:15)
#3      FlutterCommand.addNullSafetyModeOptions (package:flutter_tools/src/runner/flutter_command.dart:700:5)
#4      new BuildAarCommand (package:flutter_tools/src/commands/build_aar.dart:48:5)
#5      new BuildCommand (package:flutter_tools/src/commands/build.dart:27:20)
#6      generateCommands (package:flutter_tools/executable.dart:150:3)
#7      main.<anonymous closure> (package:flutter_tools/executable.dart:94:11)
#8      run.<anonymous closure> (package:flutter_tools/runner.dart:48:13)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     main (package:flutter_tools/executable.dart:92:3)
<asynchronous suspension>
```

**Comment by MrHBS** [comment] 2021-11-11 23:17
@jmagman Perhaps this can be closed now?

**Comment by jmagman** [comment] 2021-11-11 23:19
Yes, fixed by https://github.com/flutter/flutter/pull/89045

**Closed by jmagman** 2021-11-11 23:19 UTC
Labels: a: tests, severe: new feature, tool, package, proposal, passed first triage, integration_test, P4
