### ISSUE TITLE
Doc request for an accessibility guide

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4657] opened 2016-06-21 14:35 UTC
I am updating the FAQ and I'd love to link to a guide on accessibility.

**Comment by Hixie** [comment] 2017-10-24 23:03
cc @goderbauer

**Comment by zoechi** [comment] 2018-12-03 13:52
There is some https://flutter.io/docs/development/accessibility-and-localization/accessibility
but shouldn't this also discuss Semantics stuff?

**Comment by goderbauer** [comment] 2018-12-27 01:33
Dupe of https://github.com/flutter/website/issues/2081.

**Closed by goderbauer** 2018-12-27 01:33 UTC
Labels: a: accessibility, d: api docs, framework
