### ISSUE TITLE
[web]: The widget doesn't rebuild on animation end in web 

### ISSUE THREAD

**Issue by ArunSivaR** [flutter/flutter#50784] opened 2020-02-14 06:29 UTC
Hi Team,

I am creating a custom scroll view, where I can host three views and reusing the view for infinity swiping and for swiping I have using tween animation and animation controller and it works fine as expected in the mobile platform, but it doesn't work as expected in the web.

I have attached the sample and the steps to reproduce the issue are following by:

[flutter_app_panel.zip](https://github.com/flutter/flutter/files/4203040/flutter_app_panel.zip)

1. Run the attached sample on mobile
2. It will display a view with text second view
3. Swipe the view in right to left and it displays a view with the third view
4. Now, swipe again now, the view displays as the first view
5. And swipe again will show the second view and swiping further continue as mentioned.
6. Now, run the sample on the web, and follow the steps mentioned above
7. It doesn't work as same as on mobile.

Regards,
Arun Siva R

**Comment by TahaTesser** [comment] 2020-02-14 07:34
Hi @ArunSivaR 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you

**Comment by ArunSivaR** [comment] 2020-02-14 10:25
Hi @TahaTesser 


The Flutter doctor -v output is following by

[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.17763.973], locale en-US)
    • Flutter version 1.14.6 at C:\src\flutter
    • Framework revision fabeb2a16f (2 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
[√] Connected device (3 available)
    • Redmi Note 4 • 6318aa1a0104 • android-arm64  • Android 7.0 (API 24)
    • Chrome       • chrome       • web-javascript • Google Chrome 79.0.3945.130
    • Web Server   • web-server   • web-javascript • Flutter Tools

• No issues found!

The flutter run --verbose output is following by

[  +26 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+3734 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] fabeb2a16f1d008ab8230f450c49141d35669798
[   +2 ms] executing: [C:\src\flutter/] git describe --match v*.*.* --first-parent --long --tags
[+5018 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.14.6-0-gfabeb2a16
[  +26 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[+5035 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[+5058 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[+5176 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[+5039 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] beta
[+2040 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +32 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[+3987 ms] Exit code 0 from: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +2 ms] List of devices attached
           6318aa1a0104           device product:mido model:Redmi_Note_4 device:mido transport_id:2
[  +48 ms] C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6318aa1a0104 shell getprop
[+3155 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +232 ms] Generating C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +56 ms] ro.hardware = qcom
[  +56 ms] Launching lib\main.dart on Redmi Note 4 in debug mode...
[  +21 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\build-tools\29.0.0\aapt dump xmltree
C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\build\app\outputs\apk\app.apk AndroidManifest.xml
[+2636 ms] Exit code 0 from: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\build-tools\29.0.0\aapt dump xmltree
C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +2 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
 A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.flutter_app_panel" (Raw: "com.example.flutter_app_panel")
               A: platformBuildVersionCode=(type 0x10)0x1
               A: platformBuildVersionName="1.0.0" (Raw: "1.0.0")
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="flutter_app_panel" (Raw: "flutter_app_panel")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="android.support.v4.app.CoreComponentFactory" (Raw: "android.support.v4.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.flutter_app_panel.MainActivity" (Raw: "com.example.flutter_app_panel.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400037b4
  A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=46)
                     E: action (line=47)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=49)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[   +8 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6318aa1a0104 shell -x logcat -v time -t 1
[+3064 ms] Exit code 0 from: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6318aa1a0104 shell -x logcat -v time -t 1
[   +4 ms] --------- beginning of main
           02-14 15:47:02.314 I/MSM-irqbalance(  860): Decided to move IRQ164 from CPU3 [P:0] to CPU4 [P:1] (banned)
[  +21 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +5 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6318aa1a0104 logcat -v time -T 02-14 15:47:02.314
[+3074 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.1-5644136
                    Installed as C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +6 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[+2064 ms] Building APK
[  +33 ms] [!] Your app isn't using AndroidX.
[   +1 ms]     To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
[  +14 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[   +9 ms] Using gradle from C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\android\gradlew.bat.
[   +1 ms] C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +13 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[+4018 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[  +11 ms] executing: [C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\android/]
C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm64 assembleDebug
[+4989 ms] > Configure project :app
[   +1 ms] WARNING: The option setting 'android.enableR8=true' is experimental and unsupported.
[   +1 ms] The current default is 'false'
[   +1 ms] Consider disabling R8 by removing 'android.enableR8=true' from your gradle.properties before publishing your app.
[+14772 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [  +23 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[+4712 ms] [+4701 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] [   +1 ms] fabeb2a16f1d008ab8230f450c49141d35669798
[   +2 ms] [        ] executing: [C:\src\flutter/] git describe --match v*.*.* --first-parent --long --tags
[+5088 ms] [+5107 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] [        ] v1.14.6-0-gfabeb2a16
[   +1 ms] [  +10 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[+5096 ms] [+5079 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] [        ] origin/beta
[   +1 ms] [        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[+5087 ms] [+5071 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[+5097 ms] [+5157 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[+5001 ms] [+5002 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] [        ] beta
[ +103 ms] [  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +17 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +84 ms] [  +81 ms] Initializing file store
[   +1 ms] [  +30 ms] Done initializing file store
[+1573 ms] [+1582 ms] Skipping target: kernel_snapshot
[ +100 ms] [ +101 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +900 ms] [ +863 ms] debug_android_application: Complete
[   +1 ms] [  +23 ms] Persisting file store
[   +1 ms] [  +18 ms] Done persisting file store
[   +1 ms] [   +3 ms] build succeeded.
[   +1 ms] [  +21 ms] "flutter assemble" took 7,776ms.
[+3320 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[ +192 ms] > Task :app:checkDebugClasspath UP-TO-DATE
[   +4 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[  +75 ms] > Task :app:compileDebugRenderscript UP-TO-DATE
[   +1 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:prepareLintJar UP-TO-DATE
[   +1 ms] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +698 ms] > Task :app:copyFlutterAssetsDebug
[   +4 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +2 ms] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[   +2 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +1 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:splitsDiscoveryTaskDebug UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:generateDebugSources UP-TO-DATE
[  +76 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[   +1 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugNdk NO-SOURCE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[  +99 ms] > Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
[   +6 ms] > Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
[   +2 ms] > Task :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
[   +3 ms] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[   +2 ms] > Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
[   +1 ms] > Task :app:checkDebugLibraries UP-TO-DATE
[   +3 ms] > Task :app:processDebugJavaRes NO-SOURCE
[   +1 ms] > Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
[  +50 ms] > Task :app:validateSigningDebug UP-TO-DATE
[   +2 ms] > Task :app:packageDebug UP-TO-DATE
[   +1 ms] > Task :app:assembleDebug UP-TO-DATE
[        ] BUILD SUCCESSFUL in 55s
[        ] 31 actionable tasks: 4 executed, 27 up-to-date
[+4727 ms] Running Gradle task 'assembleDebug'... (completed in 66.0s)
[  +60 ms] calculateSha: LocalDirectory: 'C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\build\app\outputs\apk'/app.apk
[  +83 ms] calculateSha: reading file took 80us
[ +885 ms] calculateSha: computing sha took 884us
[  +14 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[  +23 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\build-tools\29.0.0\aapt dump xmltree
C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\build\app\outputs\apk\app.apk AndroidManifest.xml
[+2999 ms] Exit code 0 from: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\build-tools\29.0.0\aapt dump xmltree
C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +5 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.flutter_app_panel" (Raw: "com.example.flutter_app_panel")
               A: platformBuildVersionCode=(type 0x10)0x1
               A: platformBuildVersionName="1.0.0" (Raw: "1.0.0")
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
   A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="flutter_app_panel" (Raw: "flutter_app_panel")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="android.support.v4.app.CoreComponentFactory" (Raw: "android.support.v4.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.flutter_app_panel.MainActivity" (Raw: "com.example.flutter_app_panel.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400037b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=42)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=46)
                     E: action (line=47)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=49)
  A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[   +9 ms] Stopping app 'app.apk' on Redmi Note 4.
[   +3 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6318aa1a0104 shell am force-stop com.example.flutter_app_panel
[+3034 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6318aa1a0104 shell pm list packages com.example.flutter_app_panel
[+3039 ms] Installing APK.
[  +13 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe version
[+3059 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.1-5644136
                    Installed as C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +6 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[+2996 ms] Installing build\app\outputs\apk\app.apk...
[   +4 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6318aa1a0104 install -t -r
C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\build\app\outputs\apk\app.apk
[+10701 ms] Performing Streamed Install
                     Success
[   +2 ms] Installing build\app\outputs\apk\app.apk... (completed in 10.7s)
[   +5 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6318aa1a0104 shell echo -n 0f1c62a473e877e88947d2e3f92cd1130ca3dc51 >
/data/local/tmp/sky.com.example.flutter_app_panel.sha1
[+2040 ms] Redmi Note 4 startApp
[   +7 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6318aa1a0104 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true
com.example.flutter_app_panel/com.example.flutter_app_panel.MainActivity
[+3047 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.flutter_app_panel/.MainActivity (has extras) }
[   +1 ms] Waiting for observatory port to be available...
[ +215 ms] Observatory URL on device: http://127.0.0.1:44280/pdXkxI1nLjI=/
[   +9 ms] executing: C:\Users\ArunsivaRengaraju\AppData\Local\Android\sdk\platform-tools\adb.exe -s 6318aa1a0104 forward tcp:0 tcp:44280
[+1802 ms] 63819
[   +1 ms] Forwarded host port 63819 to device port 44280 for Observatory
[  +10 ms] Connecting to service protocol: http://127.0.0.1:63819/pdXkxI1nLjI=/
[ +459 ms] Successfully connected to service protocol: http://127.0.0.1:63819/pdXkxI1nLjI=/
[  +13 ms] Sending to VM service: getVM({})
[  +21 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Qualcomm Technologies, Inc MSM8953, operatingSystem: android, targetCPU: arm64, version:
2.8.0-dev.5.0.flutter-fc3af737c7 (Fri Jan 24 09:53:26 2020 +0000) on "android_arm64", _profilerMode: VM, _...
[  +24 ms] Sending to VM service: getIsolate({isolateId: isolates/2231208233335395})
[   +9 ms] Sending to VM service: _flutter.listViews({})
[  +27 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7fac04f820, isolate: {type: @Isolate, fixedId: true, id: isolates/2231208233335395, name:
main.dart$main-2231208233335395, number: 2231208233335395}}]}
[   +6 ms] DevFS: Creating new filesystem on the device (null)
[   +1 ms] Sending to VM service: _createDevFS({fsName: flutter_app_panel})
[  +14 ms] Result: {type: Isolate, id: isolates/2231208233335395, name: main, number: 2231208233335395, _originNumber: 2231208233335395, startTime: 1581675529061, _heaps: {new:
{type: HeapSpace, name: new, vmName: Scavenger, collections: 2, avgCollectionPeriodMillis...
[  +71 ms] Result: {type: FileSystem, name: flutter_app_panel, uri: file:///data/user/0/com.example.flutter_app_panel/code_cache/flutter_app_panelMDGDVY/flutter_app_panel/}
[   +2 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.flutter_app_panel/code_cache/flutter_app_panelMDGDVY/flutter_app_panel/)
[   +6 ms] Updating assets
[ +138 ms] Syncing files to device Redmi Note 4...
[   +2 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +9 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\ARUNSI~1\AppData\Local\Temp\flutter_tool.3348f773-4f13-11ea-a892-98541b03ab78\app.dill --packages
C:\Users\ArunsivaRengaraju\AndroidStudioProjects\flutter_app_panel\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root
[ +196 ms] <- compile package:flutter_app_panel/main.dart
[+9698 ms] Updating files
[ +192 ms] DevFS: Sync finished
[   +2 ms] Syncing files to device Redmi Note 4... (completed in 10,103ms, longer than expected)
[   +1 ms] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +6 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7fac04f820, isolate: {type: @Isolate, fixedId: true, id: isolates/2231208233335395, name:
main.dart$main-2231208233335395, number: 2231208233335395}}]}
[   +1 ms] <- accept
[        ] Connected to _flutterView/0x7fac04f820.
[   +2 ms] Flutter run key commands.
[   +3 ms] r Hot reload. ���
[   +2 ms] R Hot restart.
[   +1 ms] h Repeat this help message.
[   +1 ms] d Detach (terminate "flutter run" but leave application running).
[   +1 ms] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Redmi Note 4 is available at: http://127.0.0.1:63819/pdXkxI1nLjI=/

Regards,
Arun Siva R

**Comment by VladyslavBondarenko** [comment] 2020-02-14 10:37
Closing as duplicate of https://github.com/flutter/flutter/issues/50729

**Closed by VladyslavBondarenko** 2020-02-14 10:37 UTC
