### ISSUE TITLE
invalid text selection: `TextSelection` with `TextEditingController`

### ISSUE THREAD

**Issue by bernaferrari** [flutter/flutter#35848] opened 2019-07-10 04:38 UTC
Probably related to this: https://github.com/flutter/flutter/issues/17647

## Steps to Reproduce
1. Run app
2. Tap on first TextField and type anything (a simple 'a' works).
3. Tap on second TextField (first one will loose focus)
4. Tap on X (clear) button from first TextField, something really weird will happen and an error will be logged.
A buggy ripple will happen and cover the full TextField:
![image](https://user-images.githubusercontent.com/351125/60940770-08ae5800-a2b3-11e9-96bd-a71c75eadeee.png)

Source code:
```dart
import 'package:flutter/material.dart';

final TextEditingController _textController1 = TextEditingController();
final TextEditingController _textController2 = TextEditingController();

class MainPage extends StatelessWidget {
  MainPage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: <Widget>[
            SearchField(textController: _textController1),
            SearchField(textController: _textController2),
          ],
        ),
      ),
    );
  }
}

class SearchField extends StatefulWidget {
  final TextEditingController textController;

  SearchField({this.textController});

  @override
  _SearchFieldState createState() => _SearchFieldState();
}

class _SearchFieldState extends State<SearchField> {
  @override
  Widget build(BuildContext context) {
    return TextField(
      controller: widget.textController,
      decoration: InputDecoration(
        hintText: "hint!",
        prefixIcon: Icon(Icons.search),
        suffixIcon: widget.textController.value.text.isEmpty
            ? null
            : IconButton(
                icon: Icon(Icons.clear, color: Colors.white),
                onPressed: () {
                  setState(() {
                    widget.textController.clear();
                  });
                },
              ),
      ),
      onChanged: (String a) {
        setState(() {});
      },
    );
  }
}
```

## Logs

Run logs:
```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: invalid text selection: TextSelection(baseOffset: 4, extentOffset: 4, affinity:
flutter: TextAffinity.downstream, isDirectional: false)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      TextEditingController.selection= (package:flutter/src/widgets/editable_text.dart:169:7)
flutter: #1      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:1216:23)
flutter: #2      RenderEditable._handlePotentialSelectionChange (package:flutter/src/rendering/editable.dart:369:5)
flutter: #3      RenderEditable.selectWordEdge (package:flutter/src/rendering/editable.dart:1466:9)
flutter: #4      _TextFieldState._handleSingleTapUp (package:flutter/src/material/text_field.dart:768:27)
flutter: #5      _TextSelectionGestureDetectorState._handleTapUp (package:flutter/src/widgets/text_selection.dart:944:16)
flutter: #6      TapGestureRecognizer._checkUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:363:49)
flutter: #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:363:11)
flutter: #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
flutter: #10     _TransparentTapGestureRecognizer.rejectGesture (package:flutter/src/widgets/text_selection.dart:1146:7)
flutter: #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:159:26)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #20     _invoke1 (dart:ui/hooks.dart:250:10)
flutter: #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: Handler: "onTapUp"
flutter: Recognizer:
flutter:   _TransparentTapGestureRecognizer#fa3c6
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

flutter doctor -v
```
[✓] Flutter (Channel dev, v1.8.0, on Mac OS X 10.14.5 18F132, locale en-BR)
    • Flutter version 1.8.0 at /usr/local/Cellar/flutter/dev
    • Framework revision 2fefa8c731 (8 days ago), 2019-07-01 11:33:22 -0700
    • Engine revision 45b66b722e
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/bernardoferrari/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Users/bernardoferrari/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5679705/Android
      Studio 3.6 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio
    • Android Studio at /Users/bernardoferrari/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5675373/Android
      Studio 3.5 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.7830
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Users/bernardoferrari/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5679705/Android
      Studio 3.6 Preview.app/Contents
    • Flutter plugin version 36.1.3
    • Dart plugin version 191.7830
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Users/bernardoferrari/Applications/JetBrains Toolbox/IntelliJ
      IDEA Ultimate.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 0001D530-E48B-4691-ADD7-E9E95F56B340 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 1 category.
```

**Comment by jiachaosun** [comment] 2019-07-10 13:32
Same problem here.

```
flutter: Another exception was thrown: invalid text selection: TextSelection(baseOffset: 5, extentOffset: 5, affinity: TextAffinity.downstream, isDirectional: false)
```

**Comment by justinmc** [comment] 2019-07-10 15:38
I can reproduce this even just using CupertinoTextFields with the built-in clear button.

**Comment by skzwksk** [comment] 2019-07-12 04:31
me too.
- Flutter v1.7.8+hotfix.3
- only Android TextField

not occured
- CupertinoTextField on Android
- TextField on ios

**Comment by MsXam** [comment] 2019-07-21 15:36
Same problem. TextFields when has focus and onscreen keyboard appears. Occurs on both iOS/Android.
1.7.8 hotfix 3. Doesnt occur with 1.5.4 which is what we were using prior to upgrading to 1.7.8.

____________
```
W/IInputConnectionWrapper( 4813): getTextBeforeCursor on inactive InputConnection
I/flutter ( 4813): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 4813): The following assertion was thrown while handling a gesture:
I/flutter ( 4813): invalid text selection: TextSelection(baseOffset: 7, extentOffset: 7, affinity:
I/flutter ( 4813): TextAffinity.upstream, isDirectional: false)
I/flutter ( 4813):
I/flutter ( 4813): When the exception was thrown, this was the stack:
I/flutter ( 4813): #0      TextEditingController.selection= 
I/flutter ( 4813): #1      EditableTextState._handleSelectionChanged 
I/flutter ( 4813): #2      RenderEditable._handlePotentialSelectionChange 
I/flutter ( 4813): #3      RenderEditable.selectPositionAt 
I/flutter ( 4813): #4      RenderEditable.selectPosition 
I/flutter ( 4813): #5      _TextFieldState._handleSingleTapUp 
I/flutter ( 4813): #6      _TextSelectionGestureDetectorState._handleTapUp 
I/flutter ( 4813): #7      TapGestureRecognizer._checkUp.<anonymous closure> 
I/flutter ( 4813): #8      GestureRecognizer.invokeCallback 
I/flutter ( 4813): #9      TapGestureRecognizer._checkUp 
I/flutter ( 4813): #10     TapGestureRecognizer.acceptGesture 
I/flutter ( 4813): #11     _TransparentTapGestureRecognizer.rejectGesture 
I/flutter ( 4813): #12     GestureArenaManager.sweep 
I/flutter ( 4813): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
I/flutter ( 4813): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
I/flutter ( 4813): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
I/flutter ( 4813): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
I/flutter ( 4813): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
I/flutter ( 4813): #21     _invoke1  (dart:ui/hooks.dart:250:10)
I/flutter ( 4813): #22     _dispatchPointerDataPacket  (dart:ui/hooks.dart:159:5)
I/flutter ( 4813): (elided 3 frames from package dart:async)
I/flutter ( 4813):
I/flutter ( 4813): Handler: "onTapUp"
I/flutter ( 4813): Recognizer:
I/flutter ( 4813):   _TransparentTapGestureRecognizer#24097
I/flutter ( 4813): ══════════
```

**Comment by MsXam** [comment] 2019-07-21 17:23
Enabling breakpoint on all Exceptions & stepping through **framework code** shows exception occurred within the framework here : 

```
focus_manager
   for (FocusNode node in _dirtyNodes) {
      node._notify();
    }
    _dirtyNodes.clear();
  }

i.e line 1056 within _applyFocusChange

which causes : 

compact_hash to throw any exception : 

bool moveNext() {
    if (_table._isModifiedSince(_data, _checkSum)) {
      throw new ConcurrentModificationError(_table);
    }

line 443 of compact_hash
```

and 

```
#0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:443:7)
#1      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1056:28)
#2      _rootRun (dart:async/zone.dart:1120:38)
#3      _CustomZone.run (dart:async/zone.dart:1021:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#5      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

```

**Comment by bernaferrari** [comment] 2019-07-21 17:27
Could any of you be able to make a breaking test, so that it can hopefully be added to the framework in the future and avoid a regression?

**Comment by MsXam** [comment] 2019-07-21 19:20
The framework code exception can easily be triggered in 1.7.8 by adding a Listener to a FocusNode that is assigned to a TextFormField. In the listener , when it is triggered - all you would need to do is set focus away from the TextFormField, i.e 

if (mounted) {
           FocusScope.of(context).requestFocus(FocusNode()); // **<--------- FRAMEWORK CODE FALLS OVER HERE IN 1.7.8**
        }

The use case for adding a listener to a focus node in this fashion is say if you have a search field and also An AppBar that has 1 or more actions - if the user taps into the Search Field, the OSK will appear - if the user then taps onto 1 of the AppBar's action - the OSK will still be visible unless you add a Listener for the FocusNode to request focus somewhere else - this will then remove the OSK.

In all versions 1.5.4 and lower - this functionality works. In 1.7.8 its broken.

A complete example of a Stateful TextFormField widget that fires a call to a callback and also dismisses the OSK by setting focus to an unused focus node  :

```
class TextFieldNotifierWidget extends StatefulWidget {
  final int maxCharsAllowed;
  final String prompt;
  final Function callback;
  final String initialText;

  TextFieldNotifierWidget(
      {Key key,
      @required this.prompt,
      @required this.callback,
      this.initialText,
      this.maxCharsAllowed = 100})
      : super(key: key);

  @override
  _TextFieldNotifierWidgetState createState() =>
      _TextFieldNotifierWidgetState();
}

class _TextFieldNotifierWidgetState extends State<TextFieldNotifierWidget> {
  final TextEditingController _controller = TextEditingController();
  final FocusNode _searchFocusNode = FocusNode();

  @override
  void initState() {
    if (widget.initialText != null) {
      _controller.text = widget.initialText;
    }
    _searchFocusNode.addListener(() {
      /// This is required so that when focus is on any of these fields, we update the decoration
      setState(() {});
      // When we dont have focus we want to set the focus to an unused focus node
      if (!_searchFocusNode.hasFocus) {
        if (mounted) {
// ******************* THE NEXT 
// ******************* LINE FAILS IN 1.7.8
          FocusScope.of(context).requestFocus(FocusNode()); 
        }
      }
    });
    _controller.addListener(() {
      widget.callback(_controller.text);
    });
    super.initState();
  }

  @override
  void dispose() {
    _searchFocusNode?.removeListener(() {});
    _controller?.removeListener(() {});
    _searchFocusNode.dispose();
    _controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(2.0),
      child: Column(
        children: [
          Form(
            onChanged: () {
              // This allows the cancel/clear button to show when we start typing
              setState(() {});
            },
            child: _buildFilter(),
          )
        ],
      ),
    );
  }

  Widget _buildFilter() {
    var suffix = !_searchFocusNode.hasFocus
        ? null
        : _controller.text.isEmpty
            ? null
            : IconButton(
                icon: Icon(Icons.cancel, color: Theme.of(context).primaryColor),
                onPressed: () => _controller.clear());
    final rv = Padding(
      padding: const EdgeInsets.only(right: 10, bottom: 5),
      child: TextFormField(
          focusNode: _searchFocusNode,
          maxLength: widget.maxCharsAllowed,
          maxLengthEnforced: true,
          controller: _controller,
          textInputAction: TextInputAction.done,
          maxLines: 1,
          keyboardAppearance: Brightness.light,
          autocorrect: false,
          keyboardType: TextInputType.text,
          decoration: InputDecoration(
            suffixIcon: suffix,
            counterStyle: TextStyle(
                color: _searchFocusNode.hasFocus ? Colors.red : Colors.grey),
            enabledBorder: UnderlineInputBorder(
                borderSide: BorderSide(color: Colors.grey)),
            focusedBorder:
                UnderlineInputBorder(borderSide: BorderSide(color: Colors.red)),
            labelStyle: TextStyle(
                color: _searchFocusNode.hasFocus ? Colors.red : Colors.grey),
            isDense: true,
            hasFloatingPlaceholder: true,

            labelText: widget.prompt,
            // Dont need to show ICON
            icon: Padding(
              padding: const EdgeInsets.all(0.0),
              child: null,
            ),
          )),
    );
    return rv;
  }
}

```

![image](https://user-images.githubusercontent.com/18722796/61595702-60718b00-abf2-11e9-8dd0-8351d7051de8.png)

**Comment by MsXam** [comment] 2019-07-21 19:31
As of 1.7.8 - the recommended way for hiding the keyboard is  : 

**CAUSES EXCEPTION**
FocusScope.of(context).requestFocus(FocusNode());

**WORKS**
 FocusScope.of(context).unfocus();

This fixed my issue.

Can read more about this breaking change here https://github.com/flutter/flutter/issues/7247#issuecomment-491038982

**Comment by shaxxx** [comment] 2019-09-04 11:09
Can also confirm, clearing text in single textfield throws exactly same exception.
FocusScope.of(context).unfocus() did not fix my problem.

**Comment by nalaws** [comment] 2019-09-06 00:59
修改 **text_field.dart**文件中函数 _void_ _handleSingleTapUp(TapUpDetails details)_ . 里的代码

> _renderEditable.selectPosition(cause: SelectionChangedCause.tap); 

为

> if(widget.focusNode != null) {
>             _renderEditable.selectPosition(cause: SelectionChangedCause.tap);
>           }

**Comment by lyf571321556** [comment] 2019-10-13 11:08
> Can also confirm, clearing text in single textfield throws exactly same exception.
> `FocusScope.of(context).unfocus()` did not fix my problem.
> However, if I call _controller.clear() like this
> `WidgetsBinding.instance.addPostFrameCallback( (_) => _controller.clear());`
> it works as expected.



> Can also confirm, clearing text in single textfield throws exactly same exception.
> `FocusScope.of(context).unfocus()` did not fix my problem.
> However, if I call _controller.clear() like this
> `WidgetsBinding.instance.addPostFrameCallback( (_) => _controller.clear());`
> it works as expected.

fix same error  on textformfield by this method,thanks!

**Comment by burkard** [comment] 2019-10-13 19:11
I had the same issue, but I was affraid that your workaround could add the same callback multiple times (like adding a listener every time the widget is built), so I used the following solution (inside the onTap function):
**Future.delayed(Duration(milliseconds: 50)).then((_){ _controller.clear();});**

Hope it helps someone.

**Comment by amrosama2020** [comment] 2019-10-14 08:49
> I had the same issue, but I was affraid that your workaround could add the same callback multiple times (like adding a listener every time the widget is built), so I used the following solution (inside the onTap function):
> **Future.delayed(Duration(milliseconds: 50)).then((_){ _controller.clear();});**
> 
> Hope it helps someone.

THanks for sharing, this workaround worked for me too, hope this gets fixed in flutter soon

**Comment by alevinetx** [comment] 2019-11-04 05:15
IRT the 2 given workarounds, (addPostFrameCallback / Future.delayed), they both remove the error, but leave the field in a state of text selection, as noted by the thumb indicator that allows a 'paste'.   
 Is this the expected/desired behavior of calling .clear(), or is this another issue to be opened?

**Comment by justinmc** [comment] 2019-11-04 19:40
@alevinetx Is this what you mean?

<img width="300" src="https://user-images.githubusercontent.com/389558/68151988-9b74a180-fef7-11e9-9ccb-8cf9b437d027.gif" />

I think it would be best to create a separate issue since it happens independently of this issue.

**Comment by alevinetx** [comment] 2019-11-07 04:20
Indeed, that's what I was referring to.   Okay, this is not the intended behavior then.  

thank you !

**Comment by ajmal-zennify** [comment] 2019-11-24 07:28
This worked for me fine

```
onPressed: () {
                      Future.delayed(Duration(milliseconds: 50)).then((_) {
                        searchBardController.clear();
                        FocusScope.of(context).unfocus();
                      });
```

**Comment by 18487115313** [comment] 2019-12-04 04:05
> I had the same issue, but I was affraid that your workaround could add the same callback multiple times (like adding a listener every time the widget is built), so I used the following solution (inside the onTap function):
> **Future.delayed(Duration(milliseconds: 50)).then((_){ _controller.clear();});**
> 
> Hope it helps someone.

谢谢您,此方法解决了我遇到的问题

**Comment by LeNgocHiep** [comment] 2019-12-05 05:27
> I had the same issue, but I was affraid that your workaround could add the same callback multiple times (like adding a listener every time the widget is built), so I used the following solution (inside the onTap function):
> **Future.delayed(Duration(milliseconds: 50)).then((_){ _controller.clear();});**
> 
> Hope it helps someone.
thanks a lot. worked for me

**Comment by justinmc** [comment] 2019-12-16 22:49
This seems to have a useable workaround above, but it still seems like there is a bug that should be fixed here.  Here's the simplest way I have of reproducing it:

  1. Focus the first text field and type something.
  2. Focus the second text field.
  3. Tap the X clear button.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final TextEditingController controller = TextEditingController();
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              controller: controller,
              decoration: InputDecoration(
                suffixIcon: IconButton(
                  icon: Icon(Icons.clear, color: Colors.red),
                  onPressed: () {
                    controller.clear();
                  },
                ),
              ),
            ),
            TextField(),
          ],
        ),
      ),
    );
  }
}
```

**Comment by cielo** [comment] 2019-12-23 07:44
This bug makes `suffixIcon` useless in `TextFormField`, if the behavior that you want is to keep keyboard open after users press the icon button. 

If the behavior that you want is to keep the keyboard open after user clicks on the icon button on the right side of the textfield, you will need to do something like below, to imitate suffixIcon, without actually using it.

     Container(
        width: double.infinity,
        decoration: BoxDecoration(
            border: Border.all(color: Colors.black),
            borderRadius: BorderRadius.circular(40)),
        child: Row(
          children: [
            Expanded(
                child: Container(child: TextFormField(...)),
            ),
            IconButton(
              icon: Icon(Icons.arrow_send),
              onPressed: (){ ...}
            )
          ],
        ),
      ), 

The code is messy, but does the job that you want the `IconButton` to do gracefully without keyboard stuttering (fast unfocus/focus), exception or encountering text selection (Future.delayed approach).

**Comment by navaronbracke** [comment] 2019-12-24 00:17
@justinmc 's reproduction code is spot on. Wanted to use `TextEditingController.clear()` to implement a clear suffix button. Turns out the following code doesn't know the `TextEditingController.text` is set to empty and fails in the setter for `TextEditingController.selection`: 
```
  set selection(TextSelection newSelection) {
    if (newSelection.start > text.length || newSelection.end > text.length)
      throw FlutterError.fromParts(<DiagnosticsNode>[ErrorSummary('invalid text selection: $newSelection')]);
    value = value.copyWith(selection: newSelection, composing: TextRange.empty);
  }
```

Took a screenshot from my debugger so you can see it for yourself:

https://drive.google.com/file/d/1vsd2by8PbGWljovL8IIaJZMb01rHZ4yp/view?usp=sharing

**Comment by Hixie** [comment] 2020-01-03 10:03
I ran into this and managed to repro with only one text field. Just launch this, then tap the "X":

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final TextEditingController _textEditingController = TextEditingController(
    text: 'Tap the X to the right.',
  );
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Material(
        child: Center(
          child: Padding(
            padding: const EdgeInsets.all(12.0),
            child: TextField(
              controller: _textEditingController,
              decoration: InputDecoration(
                border: OutlineInputBorder(),
                suffixIcon: IconButton(
                  icon: Icon(Icons.close),
                  onPressed: _textEditingController.clear,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by fayaz07** [comment] 2020-01-16 08:32
I observed this issue to happen, while clearing the text with onTap handling of suffix/prefix widget and TextEditingController. 

Until this issue get's resolved we can have button separate to textfield and can implement tap handler. Just like below
```dart 
Row(
      children: <Widget>[
        Expanded(
          flex: 8,
          child: TextFormField(
            controller: _controller,
          ),
        ),
        Expanded(
          flex: 2,
          child: InkWell(
            onTap: () {
              _controller.clear();
            },
            child: Icon(Icons.close),
          ),
        )
      ],
    );     
```

**Comment by hebersousa** [comment] 2020-01-28 17:18
Alternative solution (inside the onTap function):
` Future.microtask(()=>textController.clear());`

**Closed** 2020-03-06 09:26 UTC
Labels: a: text input, f: material design, framework, severe: crash

**Comment by renanmoura100** [comment] 2020-06-12 22:24
solution:
() async {
     await Future.delayed(Duration(seconds: 0)); 
     _Controller.clear();
},
