### ISSUE TITLE
webview_flutter 0.2.0 crashes when url uses javascript redirect

### ISSUE THREAD

**Issue by glomski-dci** [flutter/flutter#27006] opened 2019-01-24 03:42 UTC
## Steps to Reproduce

1. Add `webview_flutter` package to `pubspec.yaml` and add the import at the top of the page.
2. Add the following WebView component to page:
```dart
WebView(
        initialUrl: 'https://open.spotify.com/album/672d5xcV0IY4SEGW7Z3vNK',
        javascriptMode: JavascriptMode.unrestricted,
      )
```
3. Running the app will throw errors, then gets stuck in a never ending loop stating:
```
W/cr_AwContentsClient(28265): Denied starting an intent without a user gesture, URI about:blank
```
4. I always cancel the app once it starts looping on this error message.

## Logs

```
D/        (28265): HostConnection::get() New Host Connection established 0xcd34f4c0, tid 28281
D/        (28265): HostConnection::get() New Host Connection established 0xf077e480, tid 28280
I/WebViewFactory(28265): Loading com.android.chrome version 71.0.3578.99 (code 357809912)
I/cr_LibraryLoader(28265): Time to load native libraries: 4 ms (timestamps 988-992)
I/chromium(28265): [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(28265): Expected native library version number "71.0.3578.99", actual native library version number "71.0.3578.99"
W/cr_ChildProcLH(28265): Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
I/cr_BrowserStartup(28265): Initializing chromium process, singleProcess=false
W/ki.albumtracke(28265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;-><init>(Landroid/content/Context;I)V (light greylist, reflection)
W/ki.albumtracke(28265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker;->logEvent(Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;)V (light greylist, reflection)
W/ki.albumtracke(28265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionStarted(I)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ki.albumtracke(28265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(II)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ki.albumtracke(28265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ki.albumtracke(28265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionModified(IILandroid/view/textclassifier/TextSelection;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ki.albumtracke(28265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(III)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/ki.albumtracke(28265): Accessing hidden method Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent;->selectionAction(IIILandroid/view/textclassifier/TextClassification;)Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/cr_media(28265): Requires BLUETOOTH permission
D/        (28265): HostConnection::get() New Host Connection established 0xd44482c0, tid 28395
D/EGL_emulation(28265): eglCreateContext: 0xcf13edc0: maj 3 min 0 rcv 3
D/EGL_emulation(28265): eglMakeCurrent: 0xcf13edc0: ver 3 0 (tinfo 0xc59444f0)
W/VideoCapabilities(28265): Unrecognized profile 4 for video/hevc
I/VideoCapabilities(28265): Unsupported profile 4 for video/mp4v-es
W/cr_CrashFileManager(28265): /data/user/0/org.glomski.albumtracker/cache/WebView/Crash Reports does not exist or is not a directory
D/EGL_emulation(28265): eglMakeCurrent: 0xec105de0: ver 3 0 (tinfo 0xec103dc0)
W/cr_MediaCodecUtil(28265): HW encoder for video/avc is not available on this device.
I/ki.albumtracke(28265): Background concurrent copying GC freed 74122(2MB) AllocSpace objects, 1(20KB) LOS objects, 50% free, 3MB/7MB, paused 5.869ms total 194.164ms
W/cr_AwContentsClient(28265): Cannot call startActivity on non-activity context.
D/EGL_emulation(28265): eglCreateContext: 0xcebed160: maj 3 min 0 rcv 3
D/EGL_emulation(28265): eglMakeCurrent: 0xcebed160: ver 3 0 (tinfo 0xc59444f0)
W/cr_AwContentsClient(28265): Denied starting an intent without a user gesture, URI spotify:album:672d5xcV0IY4SEGW7Z3vNK?utm_campaign=&utm_source=&utm_medium=&si=&adjust_reftag=cqVgbeUpNdE3g
W/cr_AwContentsClient(28265): Denied starting an intent without a user gesture, URI https://open.spotify.com/album/672d5xcV0IY4SEGW7Z3vNK?nd=1
W/cr_AwContentsClient(28265): Denied starting an intent without a user gesture, URI about:blank
W/cr_AwContentsClient(28265): Denied starting an intent without a user gesture, URI about:blank
```

```
Analyzing album_tracker...                                       

   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) •
          lib/components/full_width_image.dart:3:7 • must_be_immutable
   info • Unused import: 'package:url_launcher/url_launcher.dart' • lib/components/utilities.dart:5:8 • unused_import
   info • Unused import: 'package:webview_flutter/webview_flutter.dart' • lib/components/utilities.dart:6:8 • unused_import
   info • Avoid using braces in interpolation when not needed • lib/components/utilities.dart:112:80 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/components/utilities.dart:119:29 • unnecessary_brace_in_string_interps
   info • Unused import: 'dart:io' • lib/main.dart:4:8 • unused_import
   info • Unused import: 'dart:convert' • lib/main.dart:5:8 • unused_import
   info • Avoid using braces in interpolation when not needed • lib/main.dart:114:28 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/main.dart:118:45 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/pages/album_add.dart:36:77 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/pages/album_add.dart:36:93 • unnecessary_brace_in_string_interps
   info • The value of the field '_auth' isn't used • lib/pages/auth.dart:19:22 • unused_field
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/auth.dart:22:24 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/auth.dart:35:8 • non_constant_identifier_names
   info • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) • lib/pages/bands.dart:4:7 •
          must_be_immutable

15 issues found. (ran in 3.1s)
```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Community Edition (version 2018.3.3)
[✓] VS Code (version 1.30.2)
[✓] Connected device (3 available)
```

**Comment by zoechi** [comment] 2019-01-24 08:32
Duplicate of #25351

**Closed by zoechi** 2019-01-24 08:32 UTC

**Comment by rakeshlanjewarwork** [comment] 2019-02-12 09:55
https://github.com/flutter/flutter/issues/25351#issuecomment-462692003
