### ISSUE TITLE
Listview.separated fails when reverse: true

### ISSUE THREAD

**Issue by dominikheeb** [flutter/flutter#63186] opened 2020-08-07 11:37 UTC
## Steps to Reproduce
1. Use ListView.separated widget and fill up a list with items so that the listview needs to be scrolled. (Set reverse: true)
2. Scroll down trough the list view fast

**Expected results:** 
Scroll should stop at the end of the list with the behaviour configured through the physics.

**Actual results:** 
Exception thrown in the console
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/rendering/sliver.dart': Failed assertion: line 556 pos 15:
flutter: 'scrollOffsetCorrection != 0.0': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: The relevant error-causing widget was:
flutter:   ListView
flutter:   
lib/…/chat/chat_history.dart:116
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new SliverGeometry 
package:flutter/…/rendering/sliver.dart:556
flutter: #3      RenderSliverList.performLayout 
package:flutter/…/rendering/sliver_list.dart:180
flutter: #4      RenderObject.layout 
package:flutter/…/rendering/object.dart:1769
flutter: #5      RenderSliverEdgeInsetsPadding.performLayout 
package:flutter/…/rendering/sliver_padding.dart:137
flutter: #6      RenderSliverPadding.performLayout 
package:flutter/…/rendering/sliver_padding.dart:377
flutter: #7      RenderObject.layout 
package:flutter/…/rendering/object.dart:1769
flutter: #8      RenderViewportBase.layoutChildSequence 

```
Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-CH)
    • Flutter version 1.20.1
    • Framework revision 2ae34518b8 (33 hours ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0
```

**Comment by pedromassangocode** [comment] 2020-08-07 11:54
Hi @... 
Can you please provide a [minimal complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) sample.
Thank you

**Comment by Piinks** [comment] 2020-08-11 23:38
Could already be resolved, see: #62198

**Comment by dominikheeb** [comment] 2020-08-12 05:49
Ok i will check it when 1.21 is released.

**Comment by TahaTesser** [comment] 2020-08-12 06:37
Hi @dominikheeb 
Closing since this was fixed in https://github.com/flutter/flutter/pull/62615 and is being reviewed for a cherrypick to 1.20. Please follow up on https://github.com/flutter/flutter/issues/62198 for updates on this.

**Closed by TahaTesser** 2020-08-12 06:37 UTC
Labels: in triage

**Comment by dominikheeb** [comment] 2020-08-14 12:58
upgrade to 1.20.2 solved the issue... thx for the cherry pick
