### ISSUE TITLE
[Impeller] Images are not displaying correctly on Android device

### ISSUE THREAD

**Issue by Shunt22** [flutter/flutter#156701] opened 2024-10-14 08:23 UTC
### Steps to reproduce

Device is Samsung SM-T220. Android 13.
Probably related to https://github.com/flutter/flutter/issues/143573.

Before Flutter 3.24.3 this device showed green screen. Since the fix there is no more green screen, but my images are not displaying correctly.
Images were drawn in Figma and then exported in png.
 

### Expected results

Images are displayed correctly

### Actual results

Images are not displayed correctly at all

### Code sample

<details open><summary>Code sample</summary>

```dart
Image.asset(
AppIcons.bluetooth,
filterQuality: FilterQuality.high,
width: 24, 
height: 24,
color: Theme.of(context).colorScheme.onSurface,
),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
Good (**without** impeller)
![good](https://github.com/user-attachments/assets/83fda17d-5ce1-4bb0-9992-3f1add5281dc)
Bad (**with** impeller)
![bad](https://github.com/user-attachments/assets/f49b77b7-7f47-4baf-9602-1e2ad876cccc)

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.5011], locale ru-RU)
    • Flutter version 3.24.3 on channel stable at D:\Programs\FlutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (5 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at D:\Programs\AndroidSDK
    • Platform android-35, build-tools 35.0.0
    • Java binary at: D:\Programs\AndroidStudio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.8.6)
    • Visual Studio at D:\Programs\VS2022
    • Visual Studio Build Tools 2022 version 17.8.34525.116
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at D:\Programs\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at D:\Programs\IntelliJ IDEA Community Edition 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM T220 (mobile)  • R9PT50ATQWL • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19045.5011]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 129.0.6668.100
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 128.0.2739.79

[√] Network resources
    • All expected network resources are available.
```

</details>

**Comment by danagbemava-nc** [comment] 2024-10-14 11:07
Hi @Shunt22, can you share some of the images you experience this issue with? Do you experience this with all images? Can you also check the master/beta channels to see if you still experience this issue?

**Comment by Shunt22** [comment] 2024-10-14 12:10
![display_axis](https://github.com/user-attachments/assets/dd64b866-ea4c-4bb1-82b1-9dcb2f2d5ff3)
![updater](https://github.com/user-attachments/assets/81db8820-d044-40b7-89f4-e3b8b93adba1)
![clock](https://github.com/user-attachments/assets/2735347c-c7f4-405f-bb23-e4f81226ee53)

Here are some images.

I've also tested this problem on the Xiaomi Redmi 10. Android 13. It works fine and displays images correctly.

**Comment by Shunt22** [comment] 2024-10-14 12:35
I think I've found the culprit of the problem.

Adding 
`color: Theme.of(context).colorScheme.onSurface,` to Image.asset() breaks image when impeller is enabled.
I made minimal example here:
[impeller_bug.zip](https://github.com/user-attachments/files/17364057/impeller_bug.zip)

**Comment by danagbemava-nc** [comment] 2024-10-15 06:29
Hi @Shunt22, were you able to check on the master or beta channel to see if you still experience this issue? 

I tested on my Pixel 7 and I can't reproduce the issue. I checked the GPU of your Redmi and Samsung SM-T220. Your redmi is using a Mali GPU whereas the Samsung is using a PowerVR GPU, which is likely why it occurs on the Samsung but not the Redmi. Incidentally, my Pixel 7 also uses a Mali GPU.

**Comment by Shunt22** [comment] 2024-10-15 14:28
HI @danagbemava-nc, I've just tested it on Flutter (Channel master, 3.27.0-1.0.pre.50) and it works fine!
Does it mean that the fix is comming to stable soon?
I wonder what version of stable it will be...

**Comment by danagbemava-nc** [comment] 2024-10-16 05:55
Hi @Shunt22, can you check the latest beta as well to see if this works as expected on that version as well? There won't be any more hotfixes to the stable branch, so if it works as expected on the beta channel as well, then this will most likely be included in the next stable version. The current beta is `3.26.0-0.1.pre`

**Comment by Shunt22** [comment] 2024-10-17 04:45
> Hi @Shunt22, can you check the latest beta as well to see if this works as expected on that version as well? There won't be any more hotfixes to the stable branch, so if it works as expected on the beta channel as well, then this will most likely be included in the next stable version. The current beta is `3.26.0-0.1.pre`

Hi, it works on beta channel as well. Hopefully stable release is comming soon.
I guess we can close this issue.
Thank you!

**Comment by danagbemava-nc** [comment] 2024-10-17 06:18
Thanks for confirming the fix. 

Closing this since this has been fixed on beta & master. 

Going by previous release patterns, there might be a release in a month or so.

**Closed by danagbemava-nc** 2024-10-17 06:18 UTC
Labels: in triage
