### ISSUE TITLE
log

### ISSUE THREAD

**Issue by SystemTce** [flutter/flutter#23806] opened 2018-11-01 02:34 UTC
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --device-id=emulator-5554 lib\main.dart

## exception

YamlException: Error on line 43, column 4: Expected a key while parsing a block mapping.
   assets:
   ^

```
#0      Parser._parseBlockMappingKey (package:yaml/src/parser.dart:448:5)
#1      Parser._stateMachine (package:yaml/src/parser.dart:86:16)
#2      Parser.parse (package:yaml/src/parser.dart:47:19)
#3      Loader._loadMapping (package:yaml/src/loader.dart:171:23)
#4      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#5      Loader._loadMapping (package:yaml/src/loader.dart:165:19)
#6      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#7      Loader._loadDocument (package:yaml/src/loader.dart:62:20)
#8      Loader.load (package:yaml/src/loader.dart:54:20)
#9      loadYamlDocument (package:yaml/yaml.dart:51:25)
#10     loadYamlNode (package:yaml/yaml.dart:42:5)
#11     loadYaml (package:yaml/yaml.dart:34:5)
#12     _pluginFromPubspec (package:flutter_tools/src/plugins.dart:62:27)
#13     findPlugins.<anonymous closure> (package:flutter_tools/src/plugins.dart:85:27)
#14     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#15     findPlugins (package:flutter_tools/src/plugins.dart:83:12)
#16     refreshPluginsList (package:flutter_tools/src/plugins.dart:287:32)
#17     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:139:5)
<asynchronous suspension>
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:360:21)
<asynchronous suspension>
#19     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:306:33)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#26     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:297:20)
#27     CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:347:21)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#35     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:303:19)
<asynchronous suspension>
#36     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#37     new Future.sync (dart:async/future.dart:224:31)
#38     CommandRunner.run (package:args/command_runner.dart:109:11)
#39     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:211:18)
#40     run.<anonymous closure> (package:flutter_tools/runner.dart:59:20)
<asynchronous suspension>
#41     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _runZoned (dart:async/zone.dart:1516:10)
#45     runZoned (dart:async/zone.dart:1463:12)
#46     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#47     runInContext (package:flutter_tools/src/context_runner.dart:42:24)
<asynchronous suspension>
#48     run (package:flutter_tools/runner.dart:50:10)
#49     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#50     main (file:///D:/AAFlutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#51     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v0.9.4, on Microsoft Windows [Version 10.0.17134.345], locale zh-CN)
    • Flutter version 0.9.4 at D:\AAFlutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at D:/Android/studio-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:/Android/studio-sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at D:\JetBrains\IntelliJ IDEA 2018.2.1
    • Flutter plugin version 28.0.3
    • Dart plugin version 182.3911.37

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by DanTup** [comment] 2018-11-01 17:03
Looks the same as #23809 so closing as a dupe. It seems like an error parsing the `pubspec.yaml`, though I'm unable to reproduce. Could you attach your pubspec to #23809 for me to test with?

**Closed by DanTup** 2018-11-01 17:03 UTC
