### ISSUE TITLE
bot_update step for Linux Android builds increased by ~5 minutes over the past few days

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#120121] opened 2023-02-06 20:25 UTC
Slow run: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine/20224/overview
Fast run: https://ci.chromium.org/ui/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine/20221/overview

The Android builds are some of the slowest on CI, so this increases the length of the long pole for cycle times.

**Comment by drewroengoogle** [comment] 2023-02-07 20:11
I took a look at the bot_update api in depot_tools, and it doesn't seem like anything has changed there within the last couple of days. I also compared the slow and fast run logs and don't see anything out of the ordinary on either. I'll keep this issue open and keep an eye on this test, as it seems that today it is speeding up a bit.

**Comment by godofredoc** [comment] 2023-02-11 04:33
This is caused by slow swiftshader checkouts:

Slow builds:
`src/third_party/swiftshader (Elapsed: 0:02:49)`

Fast builds:
`src/third_party/swiftshader (Elapsed: 0:00:06)`

**Comment by godofredoc** [comment] 2023-02-11 04:53
It also happens with dart-sdk:

`src/third_party/dart (Elapsed: 0:03:48)`

**Comment by godofredoc** [comment] 2023-02-11 04:53
Confirmed this is not a GoB quota problem.

**Comment by godofredoc** [comment] 2023-02-27 23:18
Yes, but we'll need help from engine team to identify why dart and swiftshader checkouts are extremely slow from time to time.

**Comment by zanderso** [comment] 2023-03-01 15:49
> Yes, but we'll need help from engine team to identify why dart and swiftshader checkouts are extremely slow from time to time.

What aspect of this can the engine team help with? I would have thought that occasionally very slow checkouts from e.g. `dart.googlesource.com` would be a meat-and-potatoes infra issue.

**Comment by godofredoc** [comment] 2023-03-01 16:36
> > Yes, but we'll need help from engine team to identify why dart and swiftshader checkouts are extremely slow from time to time.
> 
> What aspect of this can the engine team help with? I would have thought that occasionally very slow checkouts from e.g. `dart.googlesource.com` would be a meat-and-potatoes infra issue.

Not sure, maybe some historical knowledge of the structure of the repo that could cause slow checkouts in cold caches? from infra point of view, during the checkout there are not errors or throttling from the git servers and it seems to be happening only on dart and swiftshader repos.

@athomas, @whesse do you know how long it takes to checkout the dart repository in a clean cache? is there anything we can do to speed the checkout up?

**Comment by whesse** [comment] 2023-03-01 17:21
When I run the three checkouts (just with git clone) in parallel on my local workstation, I get transfer speeds of about 40 MiB/s, which is more than twice the speed on the builder.  The times taken are 52s, 1m20s, and 1m36s.

I notice that the resolving deltas step is also taking as much time as the downloads, and I see that it is taking a lot of user time (more than twice the real time).  Could this be compute intensive, or disk i/o intensive, and that is slowing it down.  Especially when these are run in parallel.

It also looks like gclient sync may have a limit on the number of repository fetches that it runs in parallel.  But I don't think increasing it would help much - it looks like there may be io or compute bottlenecks as well.

The slow checkout is one with an entirely empty gclient git cache, and the fast one has a populated, up-to-date, gclient git cache.  Check the occurences of the string "skipping mirror update" in the stdout of a fast bot-update step versus on a slow one.

**Comment by keyonghan** [comment] 2023-03-24 17:50
As @whesse mentioned above, the longer builds all hit cold cache
For `dart`, the code cache checkout took from [3min](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8786198922782892801/+/u/Checkout_source_code/bot_update/stdout) to [7min](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8787836512861136033/+/u/Checkout_source_code/bot_update/stdout)
For `swiftshader`, around 2-3min.

This looks as expected? @zanderso Let me know if you want infra to triage anything else.

**Comment by zanderso** [comment] 2023-03-24 21:24
Do we have an issue filed to reduce the cold-cache checkout time already?

**Comment by keyonghan** [comment] 2023-03-24 21:33
How much time do you expect a reasonable number for these two repos? Based on bots or network, the time may vary. I can create a follow-up bug with luci git cache team to see what we can do here.

**Comment by keyonghan** [comment] 2023-03-24 22:27
> Do we have an issue filed to reduce the cold-cache checkout time already?

We have dropped back to 40 mins range for a while. Here are the recent 200 builds: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine?limit=200

Are you concerning about the longer checkout time when we hit the cold cache, or worried we are still encountering the 49 mins build time? Just want to make sure we are on the same page.

**Comment by zanderso** [comment] 2023-03-24 22:36
I'd like to do a `led` run with `--shallow` and `--no-history` passed to `gclient sync`, but since the `gclient sync` invocation is buried in a recipe module, `led` won't pick up my changes IIUC.

Locally when I run `gclient sync` with those flags, a checkout over wifi to my laptop with no caches takes about 3 minutes.

> Are you concerning about the longer checkout time when we hit the cold cache, or worried we are still encountering the 49 mins build time? Just want to make sure we are on the same page.

I'm not sure there's a salient distinction to be made here. When the cycle times get too long, we have to look for all the steps that seem slow.

Also think a little ahead to engine_v2. A 7 minute checkout time will 1.5x to 2x the runtime of some shards.

**Comment by keyonghan** [comment] 2023-03-29 00:30
Slow checkout is affecting other builders. Example: https://ci.chromium.org/p/flutter/builders/try/Linux%20Unopt?limit=200.

Created https://crbug.com/1428757 to follow up with chromium team to see if any issue with bots or configs.

**Comment by keyonghan** [comment] 2023-03-29 21:45
Issue is redirected to GOB team: b/275648448

**Comment by keyonghan** [comment] 2023-03-30 15:43
Gob team had some issue with some cells, and have recovered. But we are still seeing slowness intermittently. Keep following up in b/275648448

**Comment by ricardoamador** [comment] 2023-04-17 18:16
Issue is still occurring, @keyonghan to check if still happening.
When we hit cache the run time is long.
Download speed is really slow 10kb/s.
We should also to look at why the quota dashboards are not populating data related to this issue.

**Comment by godofredoc** [comment] 2023-04-18 19:54
@zanderso any concerns about adding a replica of swiftshader to our flutter host? that will help to have authenticated reads on that repository.

**Comment by zanderso** [comment] 2023-04-18 20:01
@godofredoc Could you give me a little more context? Swiftshader should be coming from swiftshader.googlesource.com, and is very similar in that respect coming from googlesource.com repos. How is it different?

**Comment by godofredoc** [comment] 2023-04-19 02:52
We found documentation stating that infra service accounts need to be explicitly added as readers to the hosts to avoid getting throttled. We'll try out this with the dart host and if it works we can do the same with fuchsia, skia and swiftshader.

**Comment by godofredoc** [comment] 2023-04-26 15:35
@keyonghan is there an easy way to collect the bot update duration across all the builds?

**Comment by keyonghan** [comment] 2023-04-27 17:06
> @keyonghan is there an easy way to collect the bot update duration across all the builds?

Not a straightforward way, but should be doable.

@zanderso I scanned through the recent 200 runs of `Linux Android Debug Engine`: https://ci.chromium.org/p/flutter/builders/prod/Linux%20Android%20Debug%20Engine?limit=200

For any build exceeding 40 mins, it more or less hit the cold cache like dart or skia. Checked a bunch of them, the dart cold cache now is consistent around 3 to 4 mins, and skia is between 1-2 mins. This is aligned with the local test.

On the other hand, I haven't spotted any instance which hit the super slow checkout like 10kb/s, filed under http://b/275648448 to track from Gob side.

I would be concerned when the checkout is consistently slow across builders/commits. Otherwise, most likely transient network issue. Please let us know if anything else you want to check under this bug.

**Comment by zanderso** [comment] 2023-04-27 17:31
I think nothing under this bug specifically, but it would be good to follow-up with additional alerting to sheriff/gardener when the bot_update step pushes build times out of SLO. Not sure if there's already an issue for that.

**Comment by keyonghan** [comment] 2023-04-27 17:43
> We found documentation stating that infra service accounts need to be explicitly added as readers to the hosts to avoid getting throttled. We'll try out this with the dart host and if it works we can do the same with fuchsia, skia and swiftshader.

Thanks @athomas bringing it up. We already have some similar chart for [`deflaking` step](http://data/sites/dash_infra_metrics_datasite/builder_deflaking_time/) on dart side. We can create similar chart for the `bot_update` step on Engine builds. Added to https://github.com/flutter/flutter/issues/125642.

**Comment by keyonghan** [comment] 2023-04-27 17:44
> I think nothing under this bug specifically, but it would be good to follow-up with additional alerting to sheriff/gardener when the bot_update step pushes build times out of SLO. Not sure if there's already an issue for that.

SG. Closing here and created https://github.com/flutter/flutter/issues/125642 to track.

**Closed by keyonghan** 2023-04-27 17:44 UTC
Labels: team: infra, passed secondary triage, P3
