### ISSUE TITLE
Prevent flutter doctor from automatically upgrading

### ISSUE THREAD

**Issue by CAoTx** [flutter/flutter#61534] opened 2020-07-15 11:24 UTC
When I am not on the newest version, flutter doctor automatically upgrades to it. 
This behaviour is not documented (hope I didn't missed something) nor wanted (by me). 

Solution: 
I see tree solutions here..
1. Disable the automatic update function
2. Modify flutter doctor that it takes a special parameter if it should upgrade too. 
3. Document this functionality.  

Thanks :)

**Comment by VladyslavBondarenko** [comment] 2020-07-15 12:45
Hi @CAoTx 
`flutter doctor` doesn't upgrade your flutter version. Could you attach your `flutter doctor -v` and describe your case - from what version does it upgrade, what commands do you use to reproduce it?

**Comment by jonahwilliams** [comment] 2020-07-15 18:17
flutter doctor does not automatically upgrade, but it will download missing cache artifacts if it needs to. Closing as WAI

**Comment by CAoTx** [comment] 2020-07-16 10:47
> Hi @CAoTx
> `flutter doctor` doesn't upgrade your flutter version. Could you attach your `flutter doctor -v` and describe your case - from what version does it upgrade, what commands do you use to reproduce it?

Hey, here is the output of  `flutter doctor -v` after I downgraded and switched from channel dev(1.19) to channel stable

Hey, I downgraded from dev 1.20 to dev 1.19, switched then from channel dev to stable and back again to dev (assuming that I land on dev 1.19. Here's the output of  `flutter doctor -v` after I switched: 


Downloading Dart SDK from Flutter engine d48085141c2f201b1c534e6926eb39bb52d9db3e...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  246M  100  246M    0     0  5965k      0  0:00:42  0:00:42 --:--:-- 5871k
Building flutter tool...
Downloading package sky_engine...                                   0.3s
Downloading flutter_patched_sdk tools...                            1.2s
Downloading flutter_patched_sdk_product tools...                    1.3s
Downloading linux-x64 tools...                                      3.8s
Downloading linux-x64/font-subset tools...                          0.4s
Downloading android-arm-profile/linux-x64 tools...                  0.3s
Downloading android-arm-release/linux-x64 tools...                  0.3s
Downloading android-arm64-profile/linux-x64 tools...                0.3s
Downloading android-arm64-release/linux-x64 tools...                0.3s
Downloading android-x64-profile/linux-x64 tools...                  0.3s
Downloading android-x64-release/linux-x64 tools...                  0.3s
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-7.1.pre at /home/sbey/flutter
    • Framework revision 7736f3bc90 (5 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/sbey/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/sbey/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1~18.04.1
    • cmake version 3.17.3
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.6)
    • Android Studio at /home/sbey/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

• No issues found!

---- 
So after switching from dev 1.19 to stable and back to dev, I am landing on dev 1.20. 
To me that seems like it upgraded or do i miss something?

**Comment by VladyslavBondarenko** [comment] 2020-07-16 16:47
@CAoTx 

I tried to perform the same:

dev 1.20.0-7.1.pre -> dev 1.20.0-7.0.pre -> stable -> dev. It remains on dev 1.20.0-7.0.pre.

<details>
 <summary>log</summary>

```
nevercode@Nevercodes-MacBook-Pro AndroidStudioProjects % flutterd doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.0)
 
[✓] Connected device (5 available)            

• No issues found!
nevercode@Nevercodes-MacBook-Pro AndroidStudioProjects % flutterd downgrade
Downgrade flutter to version 1.20.0-7.0.pre
? [y|n]: y
Success
nevercode@Nevercodes-MacBook-Pro AndroidStudioProjects % flutterd channel stable
Downloading Dart SDK from Flutter engine 0dc86cda19d55aba8b719231c11306eeaca4b798...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  248M  100  248M    0     0  3565k      0  0:01:11  0:01:11 --:--:-- 3523k
Building flutter tool...
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Downloading package sky_engine...                                   1.2s
Downloading flutter_patched_sdk tools...                            3.7s
Downloading flutter_patched_sdk_product tools...                    3.8s
Downloading darwin-x64 tools...                                    10.0s
Downloading darwin-x64/font-subset tools...                         1.6s
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:  * [new branch]          flutter-1.21-candidate.2 -> origin/flutter-1.21-candidate.2
git: Switched to a new branch 'stable'
git: Branch 'stable' set up to track remote branch 'stable' from 'origin'.
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
nevercode@Nevercodes-MacBook-Pro AndroidStudioProjects % flutterd channel dev
Downloading Dart SDK from Flutter engine ee76268252c22f5c11e82a7b87423ca3982e51a7...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  212M  100  212M    0     0  3568k      0  0:01:00  0:01:00 --:--:-- 3568k
Building flutter tool...
Downloading package sky_engine...                                   0.8s
Downloading flutter_patched_sdk tools...                            3.1s
Downloading flutter_patched_sdk_product tools...                    3.2s
Downloading darwin-x64 tools...                                     9.3s
Downloading libimobiledevice...                                     0.4s
Downloading usbmuxd...                                              0.4s
Downloading libplist...                                             0.4s
Downloading openssl...                                              0.5s
Downloading darwin-x64/font-subset tools...                         1.0s
Switching to flutter channel 'dev'...
git: From https://github.com/flutter/flutter
git:    9c4a5ef1e..fc09119d0  master     -> origin/master
git: Switched to branch 'dev'
git: Your branch is behind 'origin/dev' by 1 commit, and can be fast-forwarded.
git:   (use "git pull" to update your local branch)
Successfully switched to flutter channel 'dev'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
nevercode@Nevercodes-MacBook-Pro AndroidStudioProjects % flutterd doctor
Downloading Dart SDK from Flutter engine 0dc86cda19d55aba8b719231c11306eeaca4b798...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  248M  100  248M    0     0  3579k      0  0:01:11  0:01:11 --:--:-- 3710k
Building flutter tool...
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Downloading package sky_engine...                                   1.3s
Downloading flutter_patched_sdk tools...                            3.9s
Downloading flutter_patched_sdk_product tools...                    3.6s
Downloading darwin-x64 tools...                                    10.0s
Downloading libimobiledevice...                                     0.3s
Downloading usbmuxd...                                              0.4s
Downloading libplist...                                             0.2s
Downloading openssl...                                              0.7s
Downloading darwin-x64/font-subset tools...                         1.1s
Downloading android-arm-profile/darwin-x64 tools...                 1.8s
Downloading android-arm-release/darwin-x64 tools...                 1.5s
Downloading android-arm64-profile/darwin-x64 tools...               1.6s
Downloading android-arm64-release/darwin-x64 tools...               1.6s
Downloading android-x64-profile/darwin-x64 tools...                 1.8s
Downloading android-x64-release/darwin-x64 tools...                 1.5s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.20.0-7.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.0)
[✓] Connected device (5 available)

• No issues found!
```

</details>

In what way did you downgrade to `dev 1.19`? does `flutter doctor` show `1.19` after downgrading?

**Comment by CAoTx** [comment] 2020-07-17 08:48
> @CAoTx
> 
> I tried to perform the same:
> 
> dev 1.20.0-7.1.pre -> dev 1.20.0-7.0.pre -> stable -> dev. It remains on dev 1.20.0-7.0.pre.
> log
> 
> In what way did you downgrade to `dev 1.19`? does `flutter doctor` show `1.19` after downgrading?

Interesting, maybe it's only upgrading major versions...?

Here is my output, being on dev 1.19: 

user:user$ flutter doctor -v

[✓] Flutter (Channel unknown, 1.19.0-4.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-4.0.pre at /home/sbey/flutter
    • Framework revision 2f7a59a8da (6 weeks ago), 2020-06-05 03:44:02 -0700
    • Engine revision d17c84e7af
    • Dart version 2.9.0 (build 2.9.0-13.0.dev 02915ec5ce)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/sbey/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/sbey/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1~18.04.1
    • cmake version 3.17.3
    • ninja version 1.8.2

[✓] Android Studio (version 3.6)
    • Android Studio at /home/sbey/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

• No issues found!

user:user$ flutter channel stable

Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:  + 7736f3bc90...f25bd9c55c dev        -> origin/dev  (forced update)
git:    7736f3bc90..394ccaa8a1  flutter-1.20-candidate.7 -> origin/flutter-1.20-candidate.7
git:  * [new branch]            flutter-1.21-candidate.2 -> origin/flutter-1.21-candidate.2
git:    9c4a5ef1ed..1840b7121a  master     -> origin/master
git: Previous HEAD position was 2f7a59a8da Update engine hash for 1.19.0-4.0.pre (#58736)
git: Switched to branch 'stable'
git: Your branch is up to date with 'origin/stable'.
Successfully switched to flutter channel 'stable'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
sbey@nunki:~/Projects/bachelorresearch/Flutter/flutterReference$ flutter channel dev
Downloading Dart SDK from Flutter engine ee76268252c22f5c11e82a7b87423ca3982e51a7...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  212M  100  212M    0     0  5957k      0  0:00:36  0:00:36 --:--:-- 5870k
Building flutter tool...
Downloading package sky_engine...                                   0.3s
Downloading flutter_patched_sdk tools...                            1.2s
Downloading flutter_patched_sdk_product tools...                    1.2s
Downloading linux-x64 tools...                                      3.7s
Downloading linux-x64/font-subset tools...                          0.7s
Switching to flutter channel 'dev'...
git: Switched to branch 'dev'
git: Your branch and 'origin/dev' have diverged,
git: and have 1 and 99 different commits each, respectively.
git:   (use "git pull" to merge the remote branch into yours)
Successfully switched to flutter channel 'dev'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'

user:user$ flutter doctor -v

Downloading Dart SDK from Flutter engine d48085141c2f201b1c534e6926eb39bb52d9db3e...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  246M  100  246M    0     0  5924k      0  0:00:42  0:00:42 --:--:-- 5868k
Building flutter tool...
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Downloading package sky_engine...                                   0.5s
Downloading flutter_patched_sdk tools...                            1.4s
Downloading flutter_patched_sdk_product tools...                    1.3s
Downloading linux-x64 tools...                                      3.7s
Downloading linux-x64/font-subset tools...                          0.9s
Downloading android-arm-profile/linux-x64 tools...                  0.8s
Downloading android-arm-release/linux-x64 tools...                  0.8s
Downloading android-arm64-profile/linux-x64 tools...                0.8s
Downloading android-arm64-release/linux-x64 tools...                0.7s
Downloading android-x64-profile/linux-x64 tools...                  0.6s
Downloading android-x64-release/linux-x64 tools...                  0.8s
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-7.1.pre at /home/sbey/flutter
    • Framework revision 7736f3bc90 (6 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/sbey/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/sbey/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1~18.04.1
    • cmake version 3.17.3
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 3.6)
    • Android Studio at /home/sbey/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

• No issues found!

**Comment by VladyslavBondarenko** [comment] 2020-07-17 10:41
@CAoTx 
after downgrading by `git checkout` or `flutter version` SDK is in a detached HEAD state.
So you have `Channel unknown`. After switching channel back to dev it changes it to the latest dev instead. This was the reason, so it's working as intended

**Closed by VladyslavBondarenko** 2020-07-17 10:41 UTC
Labels: in triage

**Comment by CAoTx** [comment] 2020-07-17 11:20
> @CAoTx
> after downgrading by `git checkout` or `flutter version` SDK is in a detached HEAD state.
> So you have `Channel unknown`. After switching channel back to dev it changes it to the latest dev instead. This was the reason, so it's working as intended

Ok, I'm sorry for the misunderstanding. 
Thanks for the help and clarification!
