### ISSUE TITLE
ios random crash on Flutter Channel beta, 1.24.0-10.2.pre

### ISSUE THREAD

**Issue by ghostgzt** [flutter/flutter#71775] opened 2020-12-05 12:23 UTC
ios random crash on Flutter Channel beta, 1.24.0-10.2.pre
@aam 

```
Thread 64 name:  DartWorker
Thread 64 Crashed:
0   Flutter                       	0x00000001035bf51c 0x1031d4000 + 4109596
1   Flutter                       	0x00000001036b4d9c 0x1031d4000 + 5115292
2   Flutter                       	0x00000001036b356c 0x1031d4000 + 5109100
3   Flutter                       	0x00000001036b3150 0x1031d4000 + 5108048
4   Flutter                       	0x00000001037332fc 0x1031d4000 + 5632764
5   Flutter                       	0x00000001036ed69c 0x1031d4000 + 5346972
6   libsystem_pthread.dylib       	0x00000001ba92dd8c _pthread_start + 156
7   libsystem_pthread.dylib       	0x00000001ba93176c thread_start + 8

```

```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.6 19G73 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.24.0-10.2.pre at /Users/gentle/Public/Flutter
    • Framework revision 022b333a08 (2 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone (mobile) • a160e1ee76946e3408af0d2907a874f2d194b8de • ios • iOS 13.3.1

! Doctor found issues in 2 categories.
```

**Comment by ghostgzt** [comment] 2020-12-05 16:43
@flutter-symbolizer-bot force ios arm64 engine#07c1eed46b #71775(comment)

**Comment by mraleph** [comment] 2020-12-05 21:20
@flutter-symbolizer-bot force ios arm64 engine#07c1eed46b https://github.com/flutter/flutter/issues/71775#issue-757669400

**Comment by mraleph** [comment] 2020-12-05 21:22
Duplicate of https://github.com/flutter/flutter/issues/70800

**Closed by mraleph** 2020-12-05 21:22 UTC
