### ISSUE TITLE
Swiping up in Buttons demo moves the tab to the left and right slightly

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#9220] opened 2017-04-05 17:50 UTC
Open the Gallery, open Buttons. Swipe over to FLAT. Now, swipe up and down.

Expected: nothing.

Actual: slight movements left or right.

If I fling up or down, I trigger a horizontal scroll.

Seems like the tiniest horizontal movements of my finger are enough to trigger the framework to scroll horizontally.

FWIW this behavior exists in the first version of the gallery. I don't think this is a regression.

To compare with the OEM toolkit, I tested the Google Wifi app, which has three tabs that don't scroll vertically. My scrolls/swipes vertically don't trigger horizontal motion.

**Comment by sethladd** [comment] 2017-04-24 18:02
FWIW, still happening. Swiping up trigger a horizontal transition to the right or left tab.

**Comment by abarth** [comment] 2017-04-24 19:31
I'd have to watch exactly what you're doing with your fingers.  We're more responsible to user input by design.  It's possible we should be less responsive in this situation, but I'd need to understand exactly what the situation is to come up with a good interaction design.

**Comment by Hixie** [comment] 2017-12-06 00:38
This is not on our immediate list of priorities, moving to next milestone.

**Comment by najeira** [comment] 2017-12-08 08:13
It will occur when swipe diagonally.

![d4e57d6df994dd694150eef675a05024](https://user-images.githubusercontent.com/1098127/33756898-e8db0e0a-dc3a-11e7-8e63-3e7c5713caa5.gif)

**Comment by Hixie** [comment] 2017-12-11 21:30
Oh, I see.

That's intentional. There's no vertical scrolling here, so any horizontal movement is captured by the horizontal gesture recognizer.

**Comment by goderbauer** [comment] 2018-12-27 22:00
On iOS native scrollviews respond the same way as in Flutter. I am closing this as working as intended for now.

**Closed by goderbauer** 2018-12-27 22:00 UTC
Labels: f: scrolling, framework, team: gallery
