### ISSUE TITLE
When will flutter engine support Metal?

### ISSUE THREAD

**Issue by yongboQu** [flutter/flutter#31175] opened 2019-04-17 03:20 UTC
According to our experience, use metal in our video app can save 20% of CPU than openGL. But now there has nothing about flutter engine will support metal.
Our flutter version of video app used more energy native version on iOS, in our opinion if use metal in video display the energy usage may have better experience.
At last will flutter support metal in future? And when will these work being started?

**Comment by jonahwilliams** [comment] 2019-04-17 03:23
Duplicate of https://github.com/flutter/flutter/issues/18208

**Closed by jonahwilliams** 2019-04-17 03:23 UTC
