### ISSUE TITLE
ImagePicker cancel button is not showing if is camera accessed first.

### ISSUE THREAD

**Issue by Sukendh** [flutter/flutter#23903] opened 2018-11-03 04:29 UTC
I found an issue in [image picker library](https://pub.dartlang.org/packages/image_picker) in ios only, the cancel button in the navigation bar is not visible if I access camera first. But its working in Andriod.
When I look into the library implementation if found that the image picker controller object reference is missing when camera usage is done. So I tried re-initializing the object each time when we use image picker and deallocating after use manually. It was working fine.
Here what i have done.

```objective-c
- (void)showCamera {
  // Camera is not available on simulators
    _imagePickerController = [[UIImagePickerController alloc] init];
    _imagePickerController.modalPresentationStyle = UIModalPresentationCurrentContext;
    _imagePickerController.delegate = self;
    _imagePickerController.mediaTypes = @[ (NSString *)kUTTypeImage ];
  if ([UIImagePickerController isSourceTypeAvailable:UIImagePickerControllerSourceTypeCamera]) {
    _imagePickerController.sourceType = UIImagePickerControllerSourceTypeCamera;
    [_viewController presentViewController:_imagePickerController animated:YES completion:nil];
  } else {
    [[[UIAlertView alloc] initWithTitle:@"Error"
                                message:@"Camera not available."
                               delegate:nil
                      cancelButtonTitle:@"OK"
                      otherButtonTitles:nil] show];
  }
}

- (void)showPhotoLibrary {
  // No need to check if SourceType is available. It always is.
    _imagePickerController = [[UIImagePickerController alloc] init];
    _imagePickerController.modalPresentationStyle = UIModalPresentationCurrentContext;
    _imagePickerController.delegate = self;
    _imagePickerController.mediaTypes = @[ (NSString *)kUTTypeImage ];
  _imagePickerController.sourceType = UIImagePickerControllerSourceTypePhotoLibrary;
    [_viewController presentViewController:_imagePickerController animated:YES completion: nil];
}

- (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker {
  [_imagePickerController dismissViewControllerAnimated:YES completion:nil];
  _result(nil);

  _result = nil;
  _arguments = nil;
    _imagePickerController = nil;
}
```
Please fix the issue as soon as possible.

**Comment by zoechi** [comment] 2018-11-03 15:58
Please add the output of `flutter doctor -v`.

**Comment by assafsl** [comment] 2019-01-04 10:09
Still experiencing the issue + random crashes without anything written to the console

✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.30.1)
[✓] Connected device (1 available)

`image_picker: "^0.4.10"`

**Comment by zoechi** [comment] 2019-01-08 15:05
Duplicate of #21922

**Closed by zoechi** 2019-01-08 15:05 UTC
Labels: p: first party, p: image_picker, plugin, severe: crash, ⌺‬ platform-ios
