### ISSUE TITLE
Huawei HarmonyOS Black Screen after being in background

### ISSUE THREAD

**Issue by yk3372** [flutter/flutter#109908] opened 2022-08-20 06:08 UTC
Symptom is same to https://github.com/flutter/flutter/issues/108005
When app is brought to foreground from background after a while, the APP will stuck in a black screen.
Only after exited (put into background), and reopened (bring back to foreground), the app will function normally.

The exact trigging condition of the problem is unclear, and it is NOT guaranteed to show on every instance, but can be reproduced fairly often.

I am unable to provide a minimum reproducible example due to the uncertainty of the triggering condition.

I try dump the layout，it looks like normally. The node is exist and it can click? The click logic seems to be normal.
And I checked the flutter view's visibility in OnResume, it's VISIBLE.
The mini layout dump is :

```xml
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<hierarchy rotation="0">
    <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
        <node index="0" text="" resource-id="" class="android.widget.LinearLayout" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
            <node index="0" text="" resource-id="android:id/content" class="android.widget.FrameLayout" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
                <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
                    <node index="0" text="" resource-id="" class="android.view.View" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
                        <node index="0" text="" resource-id="" class="android.view.View" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
                            <node index="0" text="" resource-id="" class="android.view.View" package="com.test.flutter" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,0][1080,2265]">
                                <node index="1" text="" resource-id="" class="android.view.View" package="com.test.flutter" content-desc="作品" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[359,105][539,180]" />
                            </node>
                        </node>
                    </node>
                </node>
            </node>
        </node>
    </node>
</hierarchy>
```

And the flutter logs is below:
```log
V/FlutterActivityAndFragmentDelegate( 6493): Forwarding onUserLeaveHint() to FlutterEngine.
V/FlutterActivityAndFragmentDelegate( 6493): onPause()
V/FlutterSurfaceView( 6493): SurfaceHolder.Callback.stopRenderingToSurface()
V/FlutterActivityAndFragmentDelegate( 6493): onStop()
V/FlutterActivityAndFragmentDelegate( 6493): onSaveInstanceState. Giving framework and plugins an opportunity to save state.

// after a few minutes, come back the App.

V/FlutterActivityAndFragmentDelegate( 6493): onStart()
V/FlutterActivityAndFragmentDelegate( 6493): Forwarding onNewIntent() to FlutterEngine and sending pushRoute message.
V/FlutterActivityAndFragmentDelegate( 6493): onResume()
V/FlutterActivityAndFragmentDelegate( 6493): onPostResume()
V/FlutterSurfaceView( 6493): SurfaceHolder.Callback.startRenderingToSurface()
V/FlutterSurfaceView( 6493): SurfaceHolder.Callback.surfaceChanged()
V/FlutterSurfaceView( 6493): Notifying FlutterRenderer that Android surface size has changed to 1080 x 2340
```

All the log looks like normally, but the screen is black. Even the debug label are also not visible...

The screenshot:
![image](https://user-images.githubusercontent.com/1514899/185731351-550ac007-10e4-452f-b3c0-a405df4c598a.png)

flutter doctor: 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (3 available)

device: Huawei p30 pro

**Comment by BFELFISH** [comment] 2022-08-22 01:58
me too！

**Comment by danagbemava-nc** [comment] 2022-08-22 07:39
Hi @yk3372, how often does this reproduce (like out of 10 times, how many times will this bug occur)? 

Also, can you test with the counter app to see if the bug occurs?

**Comment by yk3372** [comment] 2022-08-23 01:29
@danagbemava-nc 
It may reproduce in about half an hour. I have test the gallery app, it's also reproduce.
Steps to reproduce:
1. open the test app and open a page.
2. press home, go desktop.
3. use other app, such map/video or other big app.
4. a few minutes later, return to the test app.
5. Then it's maybe reproduce in Huawei's Harmony OS.

**Comment by yk3372** [comment] 2022-08-23 02:16
And the change: https://github.com/flutter/engine/pull/30897 ：
Can test this: change `flutterView.setVisibility(View.GONE);` to `flutterView.setVisibility(View.INVISIBLE);`.
I don't know how to test engine. >_<

**Comment by danagbemava-nc** [comment] 2022-08-23 08:16
> And the change: https://github.com/flutter/engine/pull/30897 ：
Can test this: change flutterView.setVisibility(View.GONE); to flutterView.setVisibility(View.INVISIBLE);.
I don't know how to test engine. >_<

This change is already in stable. 


Hi @yk3372, I followed the steps https://github.com/flutter/flutter/issues/109908#issuecomment-1223406521 on my Poco X3 NFC, but I cannot reproduce this issue. 

I also do not have a huawei device to verify this locally, as such I'll be labeling this for further investigation from the team

**Comment by yk3372** [comment] 2022-08-24 10:08
This seems to be only on Huawei phones, and other models have not encountered it for the time being.
Bug I try change the view's visibility to INVISIBLE not GONE, it's looks good.

Can you teach me how to test the engine code? The doc or others? Thanks @danagbemava-nc

**Comment by danagbemava-nc** [comment] 2022-08-24 10:54
Hi @yk3372, see https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment and the rest of the engine section in the flutter wiki for that information

**Comment by stuartmorgan** [comment] 2022-08-26 17:50
HarmonyOS [is not supported by the Flutter team](https://github.com/flutter/flutter/issues/38437), so I'm going to close this.

If there are issues with HarmonyOS's compatibility with Android apps built with Flutter, you'd need to report that to the HarmonyOS developers.

**Closed by stuartmorgan** 2022-08-26 17:50 UTC
Labels: e: device-specific, platform-android, engine, P5

**Comment by fixedyangsir** [comment] 2022-09-02 10:06
@yk3372  Is the problem solved?

**Comment by yk3372** [comment] 2022-09-04 02:30
> And the change: [flutter/engine#30897](https://github.com/flutter/engine/pull/30897) ： Can test this: change `flutterView.setVisibility(View.GONE);` to `flutterView.setVisibility(View.INVISIBLE);`. I don't know how to test engine. >_<

@fixedyangsir You can try this, or below:
```java
@Override
    protected void onStop() {
        super.onStop();
        getWindow().getDecorView().setVisibility(View.INVISIBLE);
    }
```
**I'm not sure if it's works...**

The idea is not make SurfaceView's visibility to GONE, make it always has size.
