### ISSUE TITLE
Images, custom fonts and icons glitch on app launch

### ISSUE THREAD

**Issue by vanelizarov** [flutter/flutter#27675] opened 2019-02-08 09:19 UTC
## Steps to Reproduce

I've supplied some images, custom icon and typography fonts in my app by placing them in assets folder in project's root and defining in `pubspec.yaml`. Suddenly, after latest build, they started to glitch for few milliseconds on app launch. Then all shows and works normally. 

This glitch appears randomly, not on each app launch. Video is better than thousand words:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5096148/52469112-9c141d80-2b9b-11e9-8e6e-4d861434b884.gif)

Here's the glitched frame for better representation:

![2019-02-08 12 13 00](https://user-images.githubusercontent.com/5096148/52469145-b77f2880-2b9b-11e9-91ee-45820bf62b14.jpg)

It also appears if I quickly switch to another tab in tab bar on app launch (that top gray rectangle is an image, which displays broken too):

![image 2019-02-08 12 24 36](https://user-images.githubusercontent.com/5096148/52469446-805d4700-2b9c-11e9-930d-7066d01db70c.jpg)

I don't know in which piece of code lives this bug, so feel free to request one if needed.

Also, this bug appears only on real devices on iOS, on Android and Simulators all is fine. Video and screenshots were recorded on iPhone 8 with iOS 12.2 dev beta 2

## `flutter doctor` output

```
[✓] Flutter (Channel dev, v1.2.0, on Mac OS X 10.14.4 18E174f, locale en-RU)
    • Flutter version 1.2.0 at /Users/vanelizarov/flutter
    • Framework revision 06b979c4d5 (2 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/vanelizarov/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone XR • ADA59AFA-ED85-46B7-8535-87647BDF7A8C • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-1 (simulator)

• No issues found!
```

**Comment by Hixie** [comment] 2019-02-09 08:21
cc @jason-simmons

**Comment by vanelizarov** [comment] 2019-02-11 14:36
Any updates on the issue?..

**Comment by vanelizarov** [comment] 2019-02-15 07:40
@zoechi @Hixie @cbracken possibly related to #27561 #21403 #27158 
Like in these issues, I also have platform views enabled in `Info.plist` and `webview_flutter` installed

**Comment by focux** [comment] 2019-02-17 18:46
I'm also facing this same issue. As you said, this bug appears only on real devices on iOS, on Android and Simulators all is fine. I'm not sure but maybe is related to using flutter dev channel.

![](https://media.discordapp.net/attachments/421445316617961502/546758916814536707/unknown.png)

# Flutter doctor
```
[✓] Flutter (Channel dev, v1.2.1, on Mac OS X 10.14.3 18D42, locale en-US)
    • Flutter version 1.2.1 at /Users/**/Documents/dev/flutter
    • Framework revision 8661d8aecd (3 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/leonardodominguez/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • iPhone de **        • 9e0ece54414f27978c5f66bb68f05a36d9dd60d4 • ios         • iOS 12.1.4
    • iPhone X                  • EDA40A1E-504D-4A85-99CE-F46ECB6B9A34     • ios         • iOS 12.1 (simulator)
    • iPhone XR                 • D40DEF07-4FC1-478B-AC4B-92A7160853E5     • ios         • iOS 12.1 (simulator)
```

**Comment by vanelizarov** [comment] 2019-02-18 09:16
@focux I don't think that's because of dev channel.
I'll try to remove platform view dependent plugins from my app and see if it was the problem.
Thanks for the feedback!

**Comment by focux** [comment] 2019-02-19 14:02
@vanelizarov Actually, as stated in #27561, this is because of the `flutter embedded views preview` configuration for iOS. When you add the line below to your `info.plist`, the bug start happening.

```
<key>io.flutter.embedded_views_preview</key>
	<string>YES</string>
```

In my case, I needed that configuration in order for google maps to work fine, so as a workaround, I had to change from the dev channel to the stable one and now it's working fine.

**Comment by AndreyTCR** [comment] 2019-02-28 00:32
switch to dev channel and working fine

**Comment by spazemantheone** [comment] 2019-02-28 17:55
Tried both dev and stable channels. Still get the rendering issue. It only happens on initial render of the main page. If I remove all images from the view then the page renders properly. Running flutter 1.2.1.

**Comment by AndreyTCR** [comment] 2019-02-28 19:06
Did you clean project after switch to dev channel?

**Comment by spazemantheone** [comment] 2019-02-28 20:56
I did clean the project. I stuck a splash page in on the app start and that fixed my issue.

**Comment by dnfield** [comment] 2019-03-01 09:00
The resource context getting messed up could cause this.

**Comment by slightfoot** [comment] 2019-03-15 14:04
I'd like to contribute some old screenshots of a popular app I was working on back in 2014. I encountered the same issue with the Android framework. It was around this time when HW acceleration was being added the framework itself in Ice Cream Sandwich. I cannot locate the original bug ticket from the android ticket tracker.

However, from what I can remember this relates to the OpenGL graphics pipeline and the stencils used for font rendering. It would happen when the stencil cache would overflow. 

@chinmaygarde might have a more direct idea where to look in the engine source for where this occures.

<img src="https://user-images.githubusercontent.com/906564/54436725-f9673580-472a-11e9-9025-ddcf1069a841.png" width="200"> <img src="https://user-images.githubusercontent.com/906564/54436726-f9673580-472a-11e9-918d-c9c77e869c51.png" width="200"> <img src="https://user-images.githubusercontent.com/906564/54436727-f9673580-472a-11e9-9887-adb82b6e1218.png" width="200">

**Comment by rkunboxed** [comment] 2019-03-15 14:32
Same issue here only mine doesn't flicker. The wonkiness sticks around until I tap in the form field.

![Image from iOS](https://user-images.githubusercontent.com/1129265/54438689-c60db200-46fc-11e9-9da8-2275a87cf700.png)

```
Flutter 1.2.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (4 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

**Comment by rkunboxed** [comment] 2019-03-15 18:44
I also have embedded views enabled in `Info.plist` and `webview_flutter` installed. Removing those resolved the issue for me.

**Comment by faverolles** [comment] 2019-03-21 03:56
I am experiencing this issue as well. I am using ```webview_flutter``` with embedded previews enabled in the ```Info.plist``` file. I have been unable to find a definitive way to reproduce the glitch. It seems to happen somewhat randomly, but only on a physical device and only in iOS. When launching the app, some times all the images render fine but other times they glitch.  I have a logo image in the app bar, and have found that rotating the device between profile and landscape can cause the glitch resulting in the app bar failing to render.  I am currently using the master branch for the platform view fixes discussed here https://github.com/flutter/flutter/issues/29427 and here https://github.com/flutter/flutter/issues/27700.
   
```
[✓] Flutter (Channel master, v1.3.14-pre.10, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.3.14-pre.10 at /flutter
    • Framework revision f8f2b043e1 (34 hours ago), 2019-03-19 10:24:55 -0700
    • Engine revision 5088735e5f
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 None)
```

**Comment by bennibau** [comment] 2019-04-12 06:19
I Have the same isssues which are describes here https://github.com/flutter/flutter/issues/17507#issuecomment-481984103

**Comment by bennibau** [comment] 2019-04-16 07:42
I have found out that the problem is a ListView.builder
I get the glitch if I have the code like this:
`return new Scaffold(
      appBar: new AppBar(title: Text("ODDSET Sport", textAlign: TextAlign.left,),
      elevation: 0.0,),
      backgroundColor: Colors.white,
      body: 
      new ListView.builder(
          itemCount: rows.length,
          itemBuilder: (BuildContext context, int index) {
            return GestureDetector(
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (context) => GameDetails(),)
                );
              },
              child: rows[index],
            );
          })
    );`

but if I remove the ListView like this:

`return new Scaffold(
      appBar: new AppBar(title: Text("ODDSET Sport", textAlign: TextAlign.left,),
      elevation: 0.0,),
      backgroundColor: Colors.white,
      body: new Container()
    );`

the glitch disappears...

**Comment by dnfield** [comment] 2019-04-24 22:05
Does this still reproduce on master?  There have been a few changes to the platform views related code that made this better since this bug was first opened that should improve this, particularly on iOS.

**Comment by bennibau** [comment] 2019-04-25 03:51
No, it was fixed on master.

Von meinem iPhone gesendet

**Comment by dnfield** [comment] 2019-04-25 04:28
I'm going to close this - @vanelizarov please feel free to re-open if you find it is still not working on master.

**Closed** 2019-04-25 04:28 UTC
Labels: a: assets, engine, framework, severe: regression, severe: rendering, waiting for customer response
