### ISSUE TITLE
Flutter web app blank white screen

### ISSUE THREAD

**Issue by YWD** [flutter/flutter#68754] opened 2020-10-22 02:56 UTC
Hi there, I'm develop for web apps then I suddenly into this situation. the flutter run -d chrome gets a white screen in chrome.

1. here is the simple code:

import 'package:flutter/material.dart';

void main() {
  runApp(Container(color: Colors.red,));
}

2. flutter doctor:

ywd:web_app ywd$ ../flutter-beta/bin/flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.22.1, on Mac OS X 10.15.4 19E287, locale en-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.41.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 3 categories.

3. It seems sync files to chrome failed? the hot restart btn is disabled.
![image](https://user-images.githubusercontent.com/8605395/96818722-96846700-1454-11eb-8480-b3440281b291.png)

4. I suddenly into this situation. before this, I can run my web app correctly. I have switched to master channel to run the 'gallery' app. now I'm in beta channel.

**Comment by YWD** [comment] 2020-10-22 03:31
I create a new flutter project and it and run successfully. I can copy files to new project and run correctly. Maybe some config in my previous project cause the problem?

**Comment by pedromassangocode** [comment] 2020-10-22 07:11
Hi @YWD 
I cannot reproduce this issue on the latest `master` channel.
Can you please upgrade to the latest  `master` and try again
`flutter channel master`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by YWD** [comment] 2020-10-22 07:40
hello @pedromassangocode, could you please clone this project 'https://github.com/YWD/flutter_framework_study.git' and run in chrome? It's a very simple app(I delete all other files) , just render a container but It can't work.

**Comment by pedromassangocode** [comment] 2020-10-22 12:50
Hi @YWD 
I cannot reproduce on `master` channel.
![Screen Shot 2020-10-22 at 13 48 44](https://user-images.githubusercontent.com/67424416/96873858-62697000-146d-11eb-934c-5501407bb4c8.png)

 Please either switch to master channel or wait the fix to land on the beta channel.

Closing this as fixed.

**Closed by pedromassangocode** 2020-10-22 12:50 UTC
Labels: in triage

**Comment by Iampato** [comment] 2021-02-09 20:52
so rude @pedromassangocode  if these are the contribution guidlines flutter talks of in there read me i donot want it
