### ISSUE TITLE
[webview_flutter] [android] Crash of WebView in SizedBox

### ISSUE THREAD

**Issue by Z6P0** [flutter/flutter#112923] opened 2022-10-05 08:03 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. ... See the app crash on the device.

**Expected results:** 
A web page.

**Actual results:** 
A crash.
Some webpages crash, some others work.
The emulator does not crash but shows a blank page.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

main() => runApp(_Test());

class _Test extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _TestState();
}

class _TestState extends State<_Test> {
  @override
  Widget build(BuildContext context) {
    const urlOk = 'https://www.wikipedia.org';
    const urlCrash = 'https://flutter.dev';
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: ListView(
          children: [
            FlutterLogo(size: 200),
            _SizedHeightWebView(initialUrl: urlCrash),
          ],
        ),
      ),
    );
  }
}

/// https://stackoverflow.com/a/60228871
class _SizedHeightWebView extends StatefulWidget {
  final String? initialUrl;

  const _SizedHeightWebView({super.key, this.initialUrl});

  @override
  State<_SizedHeightWebView> createState() => _SizedHeightWebViewState();
}

class _SizedHeightWebViewState extends State<_SizedHeightWebView> {
  double webViewHeight = 1;
  bool done = false;
  WebViewController? webViewController;

  @override
  Widget build(BuildContext context) {
    var webView = WebView(
      onWebViewCreated: (controller) {
        webViewController = controller;
      },
      initialUrl: widget.initialUrl,
      javascriptMode: JavascriptMode.unrestricted,
      onPageFinished: (url) {
        if (done) return;
        const js = 'document.documentElement.scrollHeight';
        webViewController!.runJavascriptReturningResult(js).then((height) {
          setState(() {
            webViewHeight = double.parse(height);
            done = true;
          });
        });
      },
    );
    if (!done) {
      return Column(
        children: [
          const LinearProgressIndicator(),
          SizedBox(height: webViewHeight, child: webView),
        ],
      );
    }
    return SizedBox(height: webViewHeight, child: webView);
  }
}

```

</details>

<details>
  <summary>Logs</summary>

```
Launching lib/github_todo.dart on Nokia 7 plus in debug mode...
Running Gradle task 'assembleDebug'...                              6,2s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
D/FlutterGeolocator(10735): Attaching Geolocator to activity
D/FlutterGeolocator(10735): Creating service.
D/FlutterGeolocator(10735): Binding to location service.
D/FlutterGeolocator(10735): Geolocator foreground service connected
D/FlutterGeolocator(10735): Initializing Geolocator services
Syncing files to device Nokia 7 plus...                            126ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Nokia 7 plus is available at: http://127.0.0.1:43511/ZcjEFgbvgEs=/
I/WebViewFactory(10735): Loading com.google.android.webview version 105.0.5195.136 (code 519513633)
W/linker  (10735): Warning: "/data/app/com.google.android.webview-BZHq7gjpS39YteWcH8-rlQ==/base.apk!/lib/arm64-v8a/libmonochrome.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
W/.test_flutter_(10735): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/.test_flutter_(10735): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/.test_flutter_(10735): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/.test_flutter_(10735): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/.test_flutter_(10735): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider(10735): Loaded version=105.0.5195.136 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(10735): Successfully loaded native library
I/cr_CachingUmaRecorder(10735): Flushed 8 samples from 8 histograms.
W/.test_flutter_(10735): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media(10735): Requires BLUETOOTH permission
I/PlatformViewsController(10735): Hosting view in view hierarchy for platform view: 0
W/Gralloc3(10735): mapper 3.x is not supported
W/Gralloc3(10735): allocator 3.x is not supported
The Flutter DevTools debugger and profiler on Nokia 7 plus is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:43511/ZcjEFgbvgEs=/
D/NetworkSecurityConfig(10735): No Network Security Config specified, using platform default
W/VideoCapabilities(10735): Unsupported mime video/divx
W/VideoCapabilities(10735): Unsupported mime video/divx311
W/VideoCapabilities(10735): Unsupported mime video/divx4
W/VideoCapabilities(10735): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(10735): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(10735): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(10735): Unsupported mime video/x-ms-wmv
W/Utils   (10735): could not parse long range '175-174'
I/cr_MediaCodecBridge(10735): create MediaCodec video decoder, mime video/avc
W/MediaCodec(10735): writeStatsLog:fr.tokata.test_flutter_3
I/OMXClient(10735): IOmx service obtained
I/MediaCodec(10735): MediaCodec will operate in async mode
D/SurfaceUtils(10735): connecting to surface 0x7a0a25a010, reason connectToSurface
I/MediaCodec(10735): [OMX.qcom.video.decoder.avc] setting surface generation to 10992641
D/SurfaceUtils(10735): disconnecting from surface 0x7a0a25a010, reason connectToSurface(reconnect)
D/SurfaceUtils(10735): connecting to surface 0x7a0a25a010, reason connectToSurface(reconnect)
I/ExtendedACodec(10735): setupVideoDecoder()
I/ExtendedACodec(10735): Decoder will be in frame by frame mode
D/SurfaceUtils(10735): set up nativeWindow 0x7a0a25a010 for 1632x1080, color 0x7fa30c06, rotation 0, usage 0x20002900
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
I/chatty  (10735): uid=10059(fr.tokata.test_flutter_3) CodecLooper identical 1 line
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
D/SurfaceUtils(10735): set up nativeWindow 0x7a0a25a010 for 1632x1088, color 0x7fa30c06, rotation 0, usage 0x20002900
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
I/chatty  (10735): uid=10059(fr.tokata.test_flutter_3) CodecLooper identical 2 lines
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
D/NdkImageReader(10735): acquireImageLocked: Overriding buffer format YUV_420_888 to 0x7fa30c06.
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
I/cr_MediaCodecBridge(10735): create MediaCodec video decoder, mime video/avc
I/OMXClient(10735): IOmx service obtained
I/MediaCodec(10735): MediaCodec will operate in async mode
D/SurfaceUtils(10735): connecting to surface 0x79af738010, reason connectToSurface
I/MediaCodec(10735): [OMX.qcom.video.decoder.avc] setting surface generation to 10992642
D/SurfaceUtils(10735): disconnecting from surface 0x79af738010, reason connectToSurface(reconnect)
D/SurfaceUtils(10735): connecting to surface 0x79af738010, reason connectToSurface(reconnect)
I/ExtendedACodec(10735): setupVideoDecoder()
I/ExtendedACodec(10735): Decoder will be in frame by frame mode
D/SurfaceUtils(10735): set up nativeWindow 0x79af738010 for 1632x1080, color 0x7fa30c06, rotation 0, usage 0x20002900
I/cr_MediaCodecBridge(10735): create MediaCodec video decoder, mime video/avc
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
I/OMXClient(10735): IOmx service obtained
I/MediaCodec(10735): MediaCodec will operate in async mode
D/SurfaceUtils(10735): connecting to surface 0x79af739010, reason connectToSurface
I/MediaCodec(10735): [OMX.qcom.video.decoder.avc] setting surface generation to 10992643
D/SurfaceUtils(10735): disconnecting from surface 0x79af739010, reason connectToSurface(reconnect)
D/SurfaceUtils(10735): connecting to surface 0x79af739010, reason connectToSurface(reconnect)
I/ExtendedACodec(10735): setupVideoDecoder()
I/ExtendedACodec(10735): Decoder will be in frame by frame mode
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
I/chatty  (10735): uid=10059(fr.tokata.test_flutter_3) CodecLooper identical 2 lines
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
D/SurfaceUtils(10735): set up nativeWindow 0x79af739010 for 1632x1080, color 0x7fa30c06, rotation 0, usage 0x20002900
D/SurfaceUtils(10735): set up nativeWindow 0x79af738010 for 1632x1088, color 0x7fa30c06, rotation 0, usage 0x20002900
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
D/NdkImageReader(10735): acquireImageLocked: Overriding buffer format YUV_420_888 to 0x7fa30c06.
D/SurfaceUtils(10735): set up nativeWindow 0x79af739010 for 1632x1088, color 0x7fa30c06, rotation 0, usage 0x20002900
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
I/chatty  (10735): uid=10059(fr.tokata.test_flutter_3) CodecLooper identical 3 lines
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10735): buffer descriptor with invalid usage bits 0x2000
D/NdkImageReader(10735): acquireImageLocked: Overriding buffer format YUV_420_888 to 0x7fa30c06.
I/PlatformViewsController(10735): Hosting view in view hierarchy for platform view: 1
W/cr_AwContents(10735): WebView.destroy() called while WebView is still attached to window.
W/cr_MediaCodecBridge(10735): Releasing: OMX.qcom.video.decoder.avc
D/SurfaceUtils(10735): disconnecting from surface 0x7a0a25a010, reason disconnectFromSurface
W/cr_MediaCodecBridge(10735): Codec released
W/cr_MediaCodecBridge(10735): Releasing: OMX.qcom.video.decoder.avc
D/SurfaceUtils(10735): disconnecting from surface 0x79af739010, reason disconnectFromSurface
W/cr_MediaCodecBridge(10735): Codec released
W/cr_MediaCodecBridge(10735): Releasing: OMX.qcom.video.decoder.avc
D/SurfaceUtils(10735): disconnecting from surface 0x79af738010, reason disconnectFromSurface
W/cr_MediaCodecBridge(10735): Codec released
E/OpenGLRenderer(10735): [SurfaceTexture-0-10735-1] bindTextureImage: error binding external image: 0x502
E/flutter (10735): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter (10735): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter (10735): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
E/flutter (10735): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(SurfaceTextureWrapper.java:55)
E/flutter (10735): 
F/flutter (10735): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1319)] Check failed: fml::jni::CheckException(env). 
F/libc    (10735): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 10767 (1.raster), pid 10735 (.test_flutter_3)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Nokia/Onyx_00WW/B2N_sprout:10/QKQ1.190828.002/00WW_4_16G:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-10-05 09:58:54+0200
pid: 10735, tid: 10767, name: 1.raster  >>> fr.tokata.test_flutter_3 <<<
uid: 10059
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1319)] Check failed: fml::jni::CheckException(env). 
'
    x0  0000000000000000  x1  0000000000002a0f  x2  0000000000000006  x3  00000079a47bbe70
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000080
    x8  00000000000000f0  x9  54753ba9518091f3  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 0000000000000002  x14 0000000000000001  x15 0000000000000000
    x16 0000007a974048c0  x17 0000007a973e0900  x18 00000079a4060000  x19 00000000000029ef
    x20 0000000000002a0f  x21 00000000ffffffff  x22 000000798cd4bb18  x23 00000079af39be38
    x24 0000007a0a303780  x25 0000000000000000  x26 0000000000000001  x27 0000000000000041
    x28 0000000000000001  x29 00000079a47bbf10
    sp  00000079a47bbe50  lr  0000007a973920c4  pc  0000007a973920f0
backtrace:
      #00 pc 00000000000830f0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: cf739dbc84bcc78f7a1500721bfb3758)
      #01 pc 00000000015bc44c  /data/app/fr.tokata.test_flutter_3-Nyd1zCYbsMSI_rz1XG6FRQ==/lib/arm64/libflutter.so (BuildId: 36a3f11c2e8288daf999b421e4196bf50667cb80)
Lost connection to device.
```

flutter doctor -v

```
[✓] Flutter (Channel stable, 3.3.2, on Ubuntu 20.04.5 LTS 5.4.0-126-generic,
    locale fr_FR.UTF-8)
    • Flutter version 3.3.2 on channel stable at /opt/flutter_3.0.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (il y a 3 semaines), 2022-09-14 08:46:55
      -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/patrick/Android/Sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /opt/idea-IC-202.8194.7
    • Flutter plugin version 66.0.3
    • Dart plugin version 213.7371

[✓] Connected device (2 available)
    • Nokia 7 plus (mobile) • B2NGAA8871902942 • android-arm64 • Android 10 (API
      29)
    • Linux (desktop)       • linux            • linux-x64     • Ubuntu 20.04.5
      LTS 5.4.0-126-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2022-10-05 10:16
Based on error log, this is a duplicate of https://github.com/flutter/flutter/issues/104889. Please follow-up in it for further updates.
Closing as such.

**Closed by darshankawar** 2022-10-05 10:16 UTC
Labels: in triage
