### ISSUE TITLE
Shrine: item image animates over the app bar

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4442] opened 2016-06-08 00:08 UTC
Taking a look at https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B14F_FSUCc01emlGOWRnRkpMOVk/GoodTransition_QuickDo-v4.webm

On iOS build of gallery, it looks like image is popping out and drawing above the app bar and then animating in. When animated back to the homescreen of Shrine, the image animates over the app bar before popping back down.

For a slow-mo video of the behavior, see https://drive.google.com/open?id=0B-w2rH1ryIJdRW5VUHgwMVNyM1E

(protip, watch the slow-mo video at .5 speed to really see the effect in action)

**Comment by sethladd** [comment] 2016-06-08 00:24
Another example: https://drive.google.com/a/google.com/file/d/0B7KN0yzZGUkHMjRORlE1OTFxcnc/view

**Comment by eseidelGoogle** [comment] 2016-06-16 16:18
@HansMuller says this boils down to us needing to implement slightly more complicated hero transitions.

**Comment by eseidelGoogle** [comment] 2016-06-16 16:18
@HansMuller and @abarth recommends we punt this from the first gallery release.

**Comment by HansMuller** [comment] 2017-02-08 22:09
This is a duplicate of #5350, see #5350 (comment)

**Comment by eseidelGoogle** [comment] 2017-02-08 22:36
Closing on hans' behalf :p

**Closed by eseidelGoogle** 2017-02-08 22:36 UTC
Labels: customer: gallery, prod: framework
