### ISSUE TITLE
Improve `expect` failure messages

### ISSUE THREAD

**Issue by WorikQCI** [flutter/flutter#111925] opened 2022-09-19 22:01 UTC
## Use case

I have two classes each with `hashCode` and `operator==` impplemented

In a test when there is a subtle difference the `expect(thing1, thing2)` function's error message on screen is:

```
Exception has occurred.
TestFailure (Expected: <Instance of 'PersistentGlobalVariables'>
  Actual: <Instance of 'PersistentGlobalVariables'>
)
```

That is nonsensical.

To trigger this I have:

```
    thing2.someIntField = 18;
    expect(thing1, thing2);
```

because the test succeeds and for this report I wished to make it fail.  So one field is different.

If you cannot find the actual cause of the failure please fix the error message so it makes sense.

thank you

**Comment by bernaferrari** [comment] 2022-09-20 04:13
It calls `toString()` which you are not overriding. Some plugins (Equatable) automatically make the toString for you. This should also get easier with macro (like add @toString and your class automatically has it) and data classes (already have it for you).

But... for now.. yeah, I agree the dev experience is not good. I just don't know it could be improved. You should open the issue in Dart, as this is unrelated to Flutter.

**Comment by huycozy** [comment] 2022-09-20 12:17
Hi @WorikQCI
Can you elaborate the issue by adding a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify it? 
Thank you!

**Comment by WorikQCI** [comment] 2022-09-20 20:44
```
import 'package:test/test.dart';

class Foo {
  String thing1;
  int thing2;
  Foo(this.thing1, this.thing2);
}

void main() {
  test("Issue 1252271834", () async {
    Foo foo1 = Foo("1", 1);
    Foo foo2 = Foo("2", 2);
    expect(foo1, foo2);
  });
}
```

**Comment by huycozy** [comment] 2022-09-21 05:52
@WorikQCI, thanks for providing the sample code.
In order to compare two instances of Foo, you need to override `==` and `hashCode`, please see: https://dart.dev/guides/language/effective-dart/design#equality

- Sample

```dart
import 'package:test/test.dart';

class Foo {
  String thing1;
  int thing2;

  Foo(this.thing1, this.thing2);

  @override
  bool operator ==(Object other) =>
      other is Foo && other.thing1 == thing1 && other.thing2 == thing2;

  @override
  int get hashCode => thing1.hashCode + thing2.hashCode;
}

void main() {
  test("Issue 1252271834", () async {
    Foo foo1 = Foo("1", 1);
    Foo foo2 = Foo("1", 1);
    expect(foo1, foo2);
  });
}
```

<img width="608" alt="Screen Shot 2022-09-21 at 12 40 23" src="https://user-images.githubusercontent.com/104349824/191423216-eb933ced-3ab1-40ba-90ea-17a9da938645.png">

Or you can archive this by using [equatable](https://pub.dev/packages/equatable) as [bernaferrari](https://github.com/bernaferrari) mentioned above.

About `Improve expect failure messages`, it looks like a proposal/feature request. Please leave a comment if you have the same opinion. It would be better if you have a specific proposal on the desired failure messages.

**Comment by bernaferrari** [comment] 2022-09-21 05:58
He is overriding, his issue is that when they are different, the error message calls toString which he isn't overriding. If it can know the value is incorrect, it can know what variable is incorrect. That's his theory.

**Comment by WorikQCI** [comment] 2022-09-21 20:45
My point is that the message is bizarrely misleading.

```
Expected: <Instance of 'PersistentGlobalVariables'>
  Actual: <Instance of 'PersistentGlobalVariables'>
```

Those are the same.

Better would be:

`arguments differ`.

**Comment by huycozy** [comment] 2022-09-22 04:25
Thanks for your response. Labeling the issue as a feature request.

**Comment by huycozy** [comment] 2022-09-28 12:19
Hi @WorikQCI, 
From what I can see, the issue is related to [test package](https://pub.dev/packages/test). Please open the issue in the [dart-lang/test repository](https://github.com/dart-lang/test/issues) to have better support there.
Sorry for this mistake. Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it. Thanks!

**Closed by huycozy** 2022-09-28 12:19 UTC
Labels: a: tests, new feature, proposal, a: error message
