### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by elmermj** [flutter/flutter#159554] opened 2024-11-27 16:24 UTC
## Command
```sh
flutter run -v
```

## Steps to Reproduce
1. Run the Flutter App on new Mac OS device (Apple Silicon) with openjdk23 installed through homebrew and Flutter 3.24.3

## Logs
RPCError
```console
#0       VmService._call (package:vm_service/src/vm_service.dart:1769:7)
#1      VmService.getVM (package:vm_service/src/vm_service.dart:1245:25)
#2      FlutterDevice.initLogReader (package:flutter_tools/src/resident _runner.dart:428:55)
#3      HotRunner.attach (package:flutter_tools/src/run_hot.dart:266:21)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:27)
 <asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (pack age:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCo mmand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart: 153:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymo us closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
% 2313     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
```
```console
[32m[✓][39m Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale e n-GB)
    [32m•[39m Flutter version 3.24.5 on channel stable at /opt/homebrew/Caskroom/flutter/3.24.5/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    %1 B[32m•[39m Framework revision dec2ee5c1f (2 weeks ago), 2024-11-13 11:13:06 -0800
    [32m•[39m Engine revision a18df97ca5
    [32m•[39m Dart version 3.5.4
    [32m•[39m  DevTools version 2.37.3

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/elmermatthewjapara/Library/Android/sdk
    [ 32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK  Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    [31m✗[39m Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev%2 Fto/macos-android-setup for more details.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 16.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m  Build 16B40
    [31m✗[39m Unable to get list of installed Simulator runtimes.
    [31m✗[39m CocoaPods not installed.
        CocoaPods is a package manager for iOS or macOS plat

**Comment by danagbemava-nc** [comment] 2024-11-28 07:01
Closing this as a duplicate of https://github.com/flutter/flutter/issues/154903

**Closed by danagbemava-nc** 2024-11-28 07:01 UTC
Labels: in triage
