### ISSUE TITLE
Provide a TextMagnifierConfiguration option to the TextFormField widget

### ISSUE THREAD

**Issue by js2702** [flutter/flutter#119724] opened 2023-02-01 16:03 UTC
The magnifier option that exists in TextField is not included in the TextFormField parameters.

## Proposal

Expose the configuration parameter and pass it down to the TextField.

```
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-x64,
    locale es-ES)
    • Flutter version 3.7.0 on channel stable at
      /Users/jorge/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (hace 9 días), 2023-01-23 16:55:55
      -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.1)
    • Android SDK at /Users/jorge/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (5 available)
   

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by huycozy** [comment] 2023-02-02 07:35
Closing this issue as a duplicate of #118029 that has been fixed by PR https://github.com/flutter/flutter/pull/118270. Please switch to the master channel and check this. Thanks!

**Closed by huycozy** 2023-02-02 07:35 UTC
Labels: in triage
