### ISSUE TITLE
takePicture is taking infinite time in android 12 pixel 3 emulator

### ISSUE THREAD

**Issue by Akshit792** [flutter/flutter#129343] opened 2023-06-22 09:51 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. copy the code from the camera package example.
2. run it in the pixel 3 emulator android 12

### Expected results

.

### Actual results

I/Camera  ( 5118): runPrecaptureSequence
I/Camera  ( 5118): refreshPreviewCaptureSession
D/CameraCaptureCallback( 5118): CameraCaptureCallback | state: STATE_WAITING_PRECAPTURE_START | afState: 0 | aeState: 2
D/CameraCaptureCallback( 5118): CameraCaptureCallback | state: STATE_WAITING_PRECAPTURE_DONE | afState: 0 | aeState: 2
I/Camera  ( 5118): captureStillPicture
D/Camera  ( 5118): Updating builder with feature: ExposureLockFeature
D/Camera  ( 5118): Updating builder with feature: ExposurePointFeature
D/Camera  ( 5118): Updating builder with feature: ZoomLevelFeature
D/Camera  ( 5118): Updating builder with feature: AutoFocusFeature
D/Camera  ( 5118): Updating builder with feature: NoiseReductionFeature
I/Camera  ( 5118): updateNoiseReduction | currentSetting: fast
D/Camera  ( 5118): Updating builder with feature: FocusPointFeature
D/Camera  ( 5118): Updating builder with feature: ResolutionFeature
D/Camera  ( 5118): Updating builder with feature: SensorOrientationFeature
D/Camera  ( 5118): Updating builder with feature: FlashFeature
D/Camera  ( 5118): Updating builder with feature: ExposureOffsetFeature
D/Camera  ( 5118): Updating builder with feature: FpsRangeFeature
I/Camera  ( 5118): sending capture request
2
D/CameraCaptureCallback( 5118): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 2
2
D/CameraCaptureCallback( 5118): CameraCaptureCallback | state: STATE_CAPTURING | afState: 0 | aeState: 5
I/Camera  ( 5118): unlockAutoFocus
I/Camera  ( 5118): refreshPreviewCaptureSession
I/Camera  ( 5118): open | onError
I/Camera  ( 5118): close
I/Camera  ( 5118): open | onClosed

### Code sample

// ignore_for_file: use_build_context_synchronously

import 'dart:io';

import 'package:blip_chat_app/common/constants.dart';
import 'package:blip_chat_app/common/helpers.dart';
import 'package:blip_chat_app/common/models/logger.dart';
import 'package:blip_chat_app/stories/bloc/stories_event.dart';
import 'package:blip_chat_app/stories/bloc/stories_state.dart';
import 'package:blip_chat_app/view_images/bloc/view_images_bloc.dart';
import 'package:blip_chat_app/view_images/view_images_screen.dart';
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:path_provider/path_provider.dart';

class StoriesBloc extends Bloc<StoriesEvent, StoriesState> {
  CameraController? controller;
  double minAvailableZoom = 1.0;
  double maxAvailableZoom = 1.0;
  double currentZoomLevel = 1.0;
  FlashMode? currentFlashMode;
  bool _isRearCameraSelected = true;
  bool _isPhotoMode = true;

  StoriesBloc() : super(InitialStoriesState()) {
    on<OnNewCameraSelected>(
      (event, emit) async {
        if (!event.isFlipMode) {
          emit(CameraNotInitilizedState());
        }

        final previousCameraController = controller;

        final CameraController cameraController = CameraController(
          event.cameraDescription,
          ResolutionPreset.veryHigh,
          imageFormatGroup: ImageFormatGroup.jpeg,
        );

        await previousCameraController?.dispose();

        controller = cameraController;

        try {
          await cameraController.initialize();

          cameraController.getMaxZoomLevel().then(
                (value) => maxAvailableZoom = value,
              );

          cameraController.getMinZoomLevel().then(
                (value) => minAvailableZoom = value,
              );

          currentFlashMode = controller!.value.flashMode;
        } on CameraException catch (e, s) {
          LogPrint.error(
            error: e,
            errorMsg: 'Camera Controller Initilize',
            stackTrace: s,
          );
        }

        emit(
          CameraInitilizedState(),
        );
      },
    );
    on<ChangeCameraFlashModeEvent>(
      (event, emit) async {
        if (controller != null && controller!.value.isInitialized) {
          currentFlashMode = event.flashmode;

          await controller?.setFlashMode(
            currentFlashMode ?? FlashMode.off,
          );

          emit(
            CameraInitilizedState(),
          );
        }
      },
    );
    on<ChangeCameraZoomLevelEvent>(
      (event, emit) async {
        if (controller != null && controller!.value.isInitialized) {
          currentZoomLevel = event.zoomLevel;

          await controller!.setZoomLevel(
            currentZoomLevel,
          );

          emit(
            CameraInitilizedState(),
          );
        }
      },
    );
    on<FlipCameraEvent>(
      (event, emit) async {
        _isRearCameraSelected = !_isRearCameraSelected;

        add(
          OnNewCameraSelected(
            context: event.context,
            isFlipMode: true,
            cameraDescription: cameras[_isRearCameraSelected ? 0 : 1],
          ),
        );
      },
    );
    on<TakePictureEvent>(
      (event, emit) async {
        if (controller != null && controller!.value.isInitialized) {
          if (controller!.value.isTakingPicture) {
            LogPrint.info(infoMsg: 'Old picture state');
          } else {
            try {
              XFile? rawImage = await controller!.takePicture();

              File imageFile = File(rawImage.path);

              int currentUnix = DateTime.now().millisecondsSinceEpoch;

              final directory = await getApplicationDocumentsDirectory();

              String fileFormat = imageFile.path.split('.').last;

              await imageFile.copy(
                '${directory.path}/$currentUnix.$fileFormat',
              );

              Navigator.of(event.context).push(
                MaterialPageRoute(
                  builder: (context) {
                    return BlocProvider(
                      create: (BuildContext context) => ViewImageBloc(
                        imagesUrl: [rawImage.path],
                        isImageTypeNetwork: false,
                      ),
                      child: const ViewImageScreen(),
                    );
                  },
                ),
              );
            } catch (e, s) {
              print('camera: error error $e');
              LogPrint.error(
                  error: e, errorMsg: 'Take Pictire Events', stackTrace: s);
            }
          }
        }
      },
    );
  }

  void disposeCameraController() {
    controller!.dispose();
  }
}

### Logs

.

### Flutter Doctor output

[!] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-IN)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.19.6/libexec/bin/dart, which is not inside your current Flutter
      SDK checkout at /Users/akshitsoni/development/flutter. Consider adding /Users/akshitsoni/development/flutter/bin to the front of
      your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Comment by huycozy** [comment] 2023-06-22 12:02
Hi @Akshit792 
Your sample code above is complex and contains 3rd package/plugin. Please retry on [plugin example](https://github.com/flutter/packages/tree/main/packages/camera/camera/example) and confirm if the issue still persists or not. 

Also, it's worth trying on a physical device to compare the results. Thank you!

**Comment by Akshit792** [comment] 2023-06-23 05:14
Hi @huycozy  i tested on the physical device samsung a33 android 13 it works but in the emulator it still gives this error and also i tried the default example code that comes with the package the result is same

i just saw there is an issue like this already 
#126125

please tell me is there is any way by which i can fix this it literally taking infinite time to return the future

XFile file = cameraController.takePicture();

**Comment by huycozy** [comment] 2023-06-23 05:45
Hi @Akshit792 
Thanks for finding out the existing issue. It's still open so I would suggest you work on another emulator with different OS version temporarily or use a physical device instead. 

Closing this issue as a duplicate of the linked issue above.

**Closed by huycozy** 2023-06-23 05:45 UTC
Labels: waiting for customer response, in triage
