### ISSUE TITLE
[docs] Include supported custom font formats into the docs

### ISSUE THREAD

**Issue by sawthinkar** [flutter/flutter#73204] opened 2021-01-02 09:42 UTC
## Use case

According to the documentation, it is not explicitly mentioned that what font formats (.otf, .ttf, .ttc) are supported for custom fonts. Only the .ttf format is shown in the example. [^1] 
Even though TrueType Collection `.ttc` is an extension of TrueType format `ttf`, TrueType Collection does not seem to be supported as a custom font.  

## Proposal

Would not it be better if it includes the supported custom font formats in the documentation? Or suggestions of any official third-party font converters? [^2]

[^1]: <https://flutter.dev/docs/cookbook/design/fonts> 
^1: https://flutter.dev/docs/cookbook/design/fonts. 

[^2]: <https://stackoverflow.com/questions/59875292/how-to-use-open-type-font-otf-in-flutter>  
^2: https://stackoverflow.com/questions/59875292/how-to-use-open-type-font-otf-in-flutter

**Comment by bharat-biradar** [comment] 2021-03-08 04:51
@pedromassango this issue can be closed. [pull request](https://github.com/flutter/flutter/issues/76715) related to the issue.

**Comment by pedromassango** [comment] 2021-03-08 18:58
Cc @pedromassangocode

**Comment by pedromassangocode** [comment] 2021-03-09 12:04
Thats @bharat-biradar 
This seems to a duplicate of https://github.com/flutter/flutter/issues/76715 that was recently closed by https://github.com/flutter/flutter/pull/77230.

**Closed** 2021-03-09 12:05 UTC
Labels: d: api docs, documentation, framework, passed first triage
