### ISSUE TITLE
google_sign_in

### ISSUE THREAD

**Issue by AliKales** [flutter/flutter#89328] opened 2021-09-01 21:10 UTC
After i sign out, i try to log in again, yes it logs in succesfully but the problem is, i start to get error [cloud_firestore/permission-denied] but when i restart my application, it works again well. What am i missing?

**Comment by TahaTesser** [comment] 2021-09-02 06:50
Hi @AliKales 
` i start to get error [cloud_firestore/permission-denied] ` is a Flutterfire error
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  providing your `flutter doctor -v`, your `pubspec.yaml`, a minimal reproducible code sample that does not use 3rd party plugins, your complete `flutter run -v` logs running the minimal code sample 
and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-09-02 06:50 UTC
Labels: in triage
