### ISSUE TITLE
[go_router] Please add a persistent desktop sidebar navigation example

### ISSUE THREAD

**Issue by Kiwi-KiwiCorp** [flutter/flutter#99129] opened 2022-02-25 01:46 UTC
## Use case

This year I chose to make the switch to flutter from a web background and I have been frustratingly working on the same “simple” task for 3 weeks now. That is to simply create a standard persistent web layout for an admin panel style web application. I have tried almost every routing system out there however all seem to have their issues with this “simple” requirement. I have also found next to no content surrounding this use case as they either do not work with URLs or load all the pages at once and just switch between then (not acceptable for my use case). 

## Proposal

In light of the recent transition of ownership for the go_router package, I think this use case would be a perfect showcase for the go_router documentation. Realistically, mobile only apps don’t need anything more complicated than navigator 1 so I think it’s more likely people using this package are building more complex web and desktop applications that have additional requirements. I think this would be a big help in moving more web developers over to the platform. Considering the SEO limitations of flutter at the moment, a complex web admin panel that does not require SEO would be a perfect use case. There are existing demos out there such as rally and the books example from the go_router package but non of them meet all the below requirements:

- a login page with no side bar
- for the rest of the application a persistent and adaptive sidebar navigation column that does not get rebuilt on new routes
- Sidebar can show and highlight the current route your on
- Sidebar can animate between navigation items when selected
- Sidebar can switch between permanent navigation draw, expandable navigation rail, and bottom navigation bar / navigation drawer depending on screen 
- Sidebar can have collapsible nested nav items which need to automatically expand and highlight when navigating directly to a sub route from the URL
- You can navigate to new routes in the nested navigator from the sidebar
- Page transitions only apply to the inner content and clip so they don’t overlap the sidebar for example in the right to left page transition. 
- It would be nice to have the option to retain page state so that it only needs to build once and then is hidden from view when clicking away until returning right where you left off. 

A bit like YouTube’s website UI

**Comment by HansMuller** [comment] 2022-02-25 16:37
CC @chunhtai @johnpryan @craiglabenz

**Comment by johnpryan** [comment] 2022-02-25 16:46
We are adding documentation to flutter.dev for a handful of scenarios that go_router supports, including a few that you mention:

**Lateral navigation** ([snippet](https://gist.github.com/johnpryan/41f959fa611de693ab845766c86cad41
))

![image](https://user-images.githubusercontent.com/1145719/155753530-1a164e53-5383-411b-8d1f-804a4402ba43.png)


**Sign in** ([snippet](https://gist.github.com/johnpryan/b1acd8f2411fac0c4a68d697565c6ecf
))

![image](https://user-images.githubusercontent.com/1145719/155753717-d7e188b6-b702-441a-aa5f-7ccbe9a63c5a.png)

For a sidebar, I'd recommend checking out the [adaptive_navigation](https://pub.dev/packages/adaptive_navigation) package on pub.dev

**Comment by maheshmnj** [comment] 2022-04-13 10:49
You can find the [example here](https://github.com/csells/go_router/blob/main/go_router/example/lib/shared_scaffold.dart) But looks like with persistent sidebar navigation is broken see https://github.com/flutter/flutter/issues/99102

**Comment by esDotDev** [comment] 2022-10-20 17:03
I think the responses are missing the key ask here. What's being asked for is a kitchen-sink demo showing your classic desktop style UI, 

There are really a few core functionalities described here: 
* A stateful scaffold, that surrounds the page routes. 
  * The page routes animate inside the scaffold, while the scaffold itself stays in place
  * The scaffold can have animations, as it's stateful, and is not replaced when routes change.
* The ability for the scaffold to read and react to the current route / url, by changing it's  size or shape, or highlighting a specific button
* Stateful page routes that remember their state when loaded 

I would also throw in the ability for full-screen dialogs, appended onto the route, like:
`/inbox/#compose` - Shows compose dialog, overtop of scaffold and inbox

With a full example like this, all other examples can be derived.

**Comment by johnpryan** [comment] 2022-10-20 18:35
We are planning to make improvements to the go_router documentation to support more scenarios like these.

**Comment by WH-Creations** [comment] 2022-10-30 20:15
This would meet exactly what I'm looking for as well. Navigation with persistence seems to be such a challenge, but it is such a hard requirement for every desktop app. Would love to see this come to fruition. Thanks :)

**Comment by El-GeorgesW** [comment] 2022-10-31 07:43
I think that more and more of us are using Flutter for the development of complex applications, but the problem is often the lack of examples and comments in the source code of Flutter itself because often to understand how certain features work, I have to go directly to read the source code of Flutter and sometimes I find myself faced with missing comments or even //TODO which is not useful during a search, and the example of a persistent navigation bar is really a new problem especially when you have to work on cross-platform solutions or with an administration interface, really there we feel this lack that even pub.dev packages cannot help us

**Comment by WH-Creations** [comment] 2022-11-29 06:59
Any updates on this...particularly surrounding the following:

- You can navigate to new routes in the nested navigator from the sidebar
- Page transitions only apply to the inner content and clip so they don’t overlap the sidebar for example in the right to left page transition.
- It would be nice to have the option to retain page state so that it only needs to build once and then is hidden from view when clicking away until returning right where you left off.

**Comment by johnpryan** [comment] 2022-11-30 20:13
I'm going to close this since we have a nested navigation sample.

@WH-Creations See the "Nested navigation" section of the [Configuration](https://pub.dev/documentation/go_router/latest/topics/Configuration-topic.html) topic in the documentation for details on how to implement this.

**Closed by johnpryan** 2022-11-30 20:13 UTC
Labels: p: first party, d: examples, package, documentation, P5, p: go_router
