### ISSUE TITLE
[Android] App crashes on Xiaomi cas:10 on launch

### ISSUE THREAD

**Issue by mengchaoshen** [flutter/flutter#96727] opened 2022-01-17 04:02 UTC
## Steps to Reproduce

1. dart code to aar
2. implement this aar 
3. install this apk ，and crashed immediately only on Xiaomi cas:10 this type of device

**Expected results:** 

Flutter 2.5.0，when i use flutter 1.17.0， it is OK 

**Actual results:** 

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

01-07 17:18:38.266 1369 1369 F libc : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1369 (init), pid 1369 (init)
01-07 17:18:38.323 1369 1369 F libc : crash_dump helper failed to exec
01-07 17:18:53.137 6839 6839 F libc : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 6839 (om.xx.xx), pid 6839 (om.xx.xx)
01-07 17:18:53.247 7294 7294 F DEBUG : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-07 17:18:53.247 7294 7294 F DEBUG : Build fingerprint: 'Xiaomi/cas/cas:10/QKQ1.200419.002/V12.0.15.0.QJJCNXM:user/release-keys'
01-07 17:18:53.247 7294 7294 F DEBUG : Revision: '0'
01-07 17:18:53.247 7294 7294 F DEBUG : ABI: 'arm'
01-07 17:18:53.248 7294 7294 F DEBUG : Timestamp: 2022-01-07 17:18:53+0800
01-07 17:18:53.248 7294 7294 F DEBUG : pid: 6839, tid: 6839, name: om.xx.xx >>> com.xx.xx <<<
01-07 17:18:53.248 7294 7294 F DEBUG : uid: 10447
01-07 17:18:53.248 7294 7294 F DEBUG : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
01-07 17:18:53.248 7294 7294 F DEBUG : Cause: null pointer dereference
01-07 17:18:53.248 7294 7294 F DEBUG : r0 00000000 r1 00000001 r2 00000004 r3 00000008
01-07 17:18:53.248 7294 7294 F DEBUG : r4 0000011a r5 c2472658 r6 db7ece80 r7 00000000
01-07 17:18:53.248 7294 7294 F DEBUG : r8 00000000 r9 c86e6200 r10 01000000 r11 c2472648
01-07 17:18:53.248 7294 7294 F DEBUG : ip ffd5f158 sp ffd5fa98 lr c230e1ed pc c228685a
01-07 17:18:53.252 7294 7294 F DEBUG :
01-07 17:18:53.252 7294 7294 F DEBUG : backtrace:
01-07 17:18:53.252 7294 7294 F DEBUG : #0 pc 0043d85a /data/app/com.xx.xx-k95jV2FJ_lgK-7EMqM8uLw==/lib/arm/libflutter.so (BuildId: 75d0a85be5512d52e38068c56cbbafa595c0012b)
01-07 17:18:53.252 7294 7294 F DEBUG : #1 pc 0018f06f /data/app/com.xx.xx-k95jV2FJ_lgK-7EMqM8uLw==/lib/arm/libflutter.so (BuildId: 75d0a85be5512d52e38068c56cbbafa595c0012b)
01-07 17:18:53.252 7294 7294 F DEBUG : #2 pc 0026cc6f /data/app/com.xx.xx-k95jV2FJ_lgK-7EMqM8uLw==/lib/arm/libflutter.so (BuildId: 75d0a85be5512d52e38068c56cbbafa595c0012b)
01-07 17:18:53.253 7294 7294 F DEBUG : #3 pc 0004a6f3 /apex/com.android.runtime/lib/bionic/libc.so (je_extent_alloc_wrapper+206) (BuildId: ad9864790c4bab27c51eb9dd56fb7b92)
01-07 17:18:53.253 7294 7294 F DEBUG : #4 pc 00001000
01-07 17:19:10.675 9895 9895 F libc : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 9895 (om.xx.xx), pid 9895 (om.xx.xx)

**Comment by Kushh37** [comment] 2022-01-17 06:46
show to code samples

**Comment by maheshmnj** [comment] 2022-01-17 13:13
Hi @mengchaoshen, Thanks for filing the issue. You are using a old version of flutter, This issue could very likely be fixed in the new releases. I would advise you to please update to latest `stable 2.8.1` and see if the issue is fixed.
If you still encounter the crash, Please share the updated output of `flutter doctor -v` and the complete output of 
`flutter run -v`, Also is the crash happening in debug/release/profile or all?

Thanks

**Closed** 2022-02-07 14:09 UTC
Labels: waiting for customer response, in triage
