### ISSUE TITLE
Android emulator terminate (Lost connection to device) when run this code (stable/beta/master)

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#137018] opened 2023-10-21 14:55 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Run my minimal project [here](https://github.com/tbm98/oi_doi_oi) and emulator crash

### Expected results

run ok, not crash

### Actual results

Android emulator terminates (Lost connection to device) without any error log (Probably due to memory leaks) on all channel (stable/beta/master)

### Code sample

Run my minimal project [here](https://github.com/tbm98/oi_doi_oi)

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel master, 3.16.0-15.0.pre.28, on Microsoft Windows [Version 10.0.19045.3570], locale en-US)
    • Flutter version 3.16.0-15.0.pre.28 on channel master at C:\Users\tbm98\fvm\default
    ! Warning: `flutter` on your path resolves to C:\Users\tbm98\fvm\versions\master\bin\flutter, which is not inside
      your current Flutter SDK checkout at C:\Users\tbm98\fvm\default. Consider adding C:\Users\tbm98\fvm\default\bin to
      the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\tbm98\fvm\versions\master\bin\dart, which is not inside your
      current Flutter SDK checkout at C:\Users\tbm98\fvm\default. Consider adding C:\Users\tbm98\fvm\default\bin to the
      front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67f5b92059 (3 hours ago), 2023-10-21 07:36:22 -0400
    • Engine revision 755c477c96
    • Dart version 3.3.0 (build 3.3.0-48.0.dev)
    • DevTools version 2.28.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\tbm98\AppData\Local\Android\sdk
    • Platform android-UpsideDownCakePrivacySandbox, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34202.233
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Community Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.1
    • Flutter plugin version 75.1.4
    • Dart plugin version 232.8660.129

[√] VS Code (version 1.83.1)
    • VS Code at C:\Users\tbm98\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.3570]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 118.0.5993.89
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 115.0.1901.203

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by darshankawar** [comment] 2023-10-23 07:29
@tbm98 
The repo you shared seems to be a complete project with implementations from other community packages. In order to properly address the issue, please only provide a minimal but complete runnable code sample without any third party package implementation that still shows the error you are reporting. Also, provide the entire log which shows any error entires in it.

**Comment by tbm98** [comment] 2023-10-23 07:37
@darshankawar This error only occurs when using the flutter_animate library, I have also created an issue in that library's repo. However, I'm not sure whether the error is caused by the library or flutter itself.
Because in my example I use code that I think is rarely used, there is also a possibility that the error is caused by flutter itself.

**Comment by tbm98** [comment] 2023-10-23 08:42
@darshankawar I just got an error even after removing the code that uses the flutter_animate library

**Comment by tbm98** [comment] 2023-10-23 09:43
When I run code by Intellij, emulator exit and error popup give this message:

INFO | Android emulator version 32.1.15.0 (build_id 10696886) (CL:N/A) INFO | Found systemPath C:\Users\tbm98\AppData\Local\Android\Sdk\system-images\android-33\google_apis_playstore\x86_64\ ERROR | Failed to create Vulkan instance. INFO | Storing crashdata in: C:\Users\tbm98\AppData\Local\Temp\\AndroidEmulator\emu-crash.db, detection is enabled INFO | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag. INFO | IPv4 server found: 192.168.1.1 INFO | added library vulkan-1.dll INFO | Sending adb public key [QAAAAGMy28C1IDOHEbFgm2gUzRjA01jg2jBPF3hPio/sQx7e+u/OlSUqFeU99jz/+UelWQqmaacOYWcRPHreBi7efya+d3onUVey9PDVyYg/QFTW1pWFTs26RLFg2/65OUkNkhc1wIlh3eJ0ph7zKnCsdM/xd+yKGmETfBpNYD4T65W5zJLMIHyUe0MRoWovEYh0/MintCLYbhR8uF2u73/kDa60b7JIR59FvGUyg1Y5Y5Tb0K4WClatYU0kKP8+LNqrWtui6Iyrk8FKgaOtS3uVjBMAfTRgR2fHv6IQ6BD/8OiESmTOudSuon/kAS5LLe1t9tG4bMjYMNJgFt3xF+McHt9TeASuon9TfohJdIEbHP7xUcfvtJXzy81eX6f/iDAxfwv7W11g5ePpTAP4YeDpyvgtikANBitfM894p75z2lfExpT7k58qt8yJAb3ShhjClSZt5f5n31TlFZfie9yavTTfw+faa7uG70cR1kEiCydjvD4JPVNZZ2vIhcPL0FRWx7idWRSht7IdfHz45gtPaZpy7boRWzIEgx3cku8ImJnKIVIzlxmf7pFN5pTfJjAWalOR6+KkKlVyeSDcBVhhgRoCMSls0oRGa+m343EnNS5z2oOYxCXWn63sOuqvpyVhz6eco1pcRHDgLdmejB1MeTigFNh2axOp2DB+CAFvQ/bvJDg2hAEAAQA= @unknown] HAX is working and emulator runs in fast virt mode. pc_memory_init: above 4g size: 40000000 dsound: Could not initialize DirectSoundCapture dsound: Reason: No sound driver is available for use, or the given GUID is not a valid DirectSound device ID WARNING | *** No gRPC protection active, consider launching with the -grpc-use-jwt flag.*** INFO | Started GRPC server at 127.0.0.1:8554, security: Local, auth: none INFO | Advertising in: C:\Users\tbm98\AppData\Local\Temp\avd\running\pid_8920.ini INFO | Setting display: 0 configuration to: 1440x3120, dpi: 560x560 INFO | Boot completed INFO | Increasing screen off timeout, logcat buffer size to 2M. INFO | Revoking microphone permissions for Google App. INFO | IPv4 server found: 192.168.1.1

log file:  [AndroidEmulator.zip](https://github.com/flutter/flutter/files/13068597/AndroidEmulator.zip)

**Comment by tbm98** [comment] 2023-10-23 10:57
It only error on emulator, work normal on real device (tested on samsung galaxy s9 (android 10), xiaomi 11t (android 13))

**Comment by darshankawar** [comment] 2023-10-24 05:47
@tbm98 
`Could not initialize DirectSoundCapture dsound: Reason: No sound driver is available for use, or the given GUID is not a valid`

Seems to be emulator specific and may not be specific to Flutter itself. Can you try on other emulators with proper / latest config like api version, play store enabled and run again ?
I'll close this for now since it doesn't seem to be specific to Flutter, but with Android emulator you are using. Since it works on real device that is also an indication that it is not a bug in framework code. You may file this issue in support channels like StackOverflow for further resolution.

**Closed by darshankawar** 2023-10-24 05:47 UTC
Labels: in triage

**Comment by tbm98** [comment] 2023-10-24 05:56
@darshankawar  My virtual machine is created from Android studio, tried api 33 and 34, has Google service support. However, I will try more using another emulator
