### ISSUE TITLE
[Web] The selected `ListTile` is not clipped by parent `Container` with `Clip.hardEdge`

### ISSUE THREAD

**Issue by MacDeveloper1** [flutter/flutter#154236] opened 2024-08-28 08:53 UTC
### Steps to reproduce

1. Click on button `Click`
2. On opened widget scroll the `ListView` with the scrollbar.

### Expected results

The selected colored `ListTile` should be clipped by top container side.

### Actual results

The selected colored `ListTile` **is not** clipped by top container side.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Clip Bug',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child: Builder(builder: (context) {
            return TextButton(
              onPressed: () {
                showDialog(
                    context: context,
                    builder: (_) {
                      return const Material(child: DialogPage());
                    });
              },
              child: const Text('CLICK'),
            );
          }),
        ),
      ),
    );
  }
}

class DialogPage extends StatefulWidget {
  const DialogPage({super.key});

  @override
  State<DialogPage> createState() => _DialogPageState();
}

class _DialogPageState extends State<DialogPage> {
  int _selectedIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: Dialog(
        elevation: 12,
        shadowColor: Colors.black,
        shape: const RoundedRectangleBorder(
          side: BorderSide(),
        ),
        child: Container(
          width: 600,
          height: 600,
          padding: const EdgeInsets.all(100),
          child: SizedBox(
            width: 200,
            height: 200,
            child: Container(
              clipBehavior: Clip.hardEdge,
              padding: const EdgeInsets.all(2),
              decoration: const ShapeDecoration(
                shape: RoundedRectangleBorder(
                  side: BorderSide(),
                ),
              ),
              child: ListView.separated(
                itemCount: 20,
                itemBuilder: (_, index) {
                  return ListTile(
                    title: Text('Item $index'),
                    selected: index == _selectedIndex,
                    tileColor: Colors.grey.withOpacity(0.1),
                    selectedTileColor: Colors.amber.withOpacity(0.1),
                    onTap: () => setState(() {
                      _selectedIndex = index;
                    }),
                  );
                },
                separatorBuilder: (_, index) => const Divider(height: 1),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.22631.4037], locale en-NL)
    • Flutter version 3.22.1 on channel stable at C:\data\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (3 months ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\at\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.92.2)
    • VS Code at C:\Users\at\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4037]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 127.0.6533.122
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.65

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

P.S. I also tried to use `ClipRect` but it does not help.

**Comment by MacDeveloper1** [comment] 2024-08-28 09:55
I've updated the sample code. I've added the `tileColor` value and now the `ListView` is out the bordered container.

**Comment by danagbemava-nc** [comment] 2024-08-28 09:58
This isn't a web issue nor is it related to the Clipping of the container. It is due to how the `Ink` widget works. You just need to add a `Material` widget somewhere in the tree above your `ListView`. This is a duplicate of  https://github.com/flutter/flutter/issues/86584

You should be able to get the desired effect with the updated code below. 

Closing from here. 

<details>
<summary>updated sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Clip Bug',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: Scaffold(
        body: Center(
          child: Builder(builder: (context) {
            return TextButton(
              onPressed: () {
                showDialog(
                    context: context,
                    builder: (_) {
                      return const Material(child: DialogPage());
                    });
              },
              child: const Text('CLICK'),
            );
          }),
        ),
      ),
    );
  }
}

class DialogPage extends StatefulWidget {
  const DialogPage({super.key});

  @override
  State<DialogPage> createState() => _DialogPageState();
}

class _DialogPageState extends State<DialogPage> {
  int _selectedIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      body: Dialog(
        elevation: 12,
        shadowColor: Colors.black,
        shape: const RoundedRectangleBorder(
          side: BorderSide(),
        ),
        child: Container(
          width: 600,
          height: 600,
          padding: const EdgeInsets.all(100),
          child: Material(
            child: SizedBox(
              width: 200,
              height: 200,
              child: Container(
                clipBehavior: Clip.hardEdge,
                padding: const EdgeInsets.all(2),
                decoration: const ShapeDecoration(
                  shape: RoundedRectangleBorder(
                    side: BorderSide(),
                  ),
                ),
                child: ListView.separated(
                  itemCount: 20,
                  itemBuilder: (_, index) {
                    return ListTile(
                      title: Text('Item $index'),
                      selected: index == _selectedIndex,
                      tileColor: Colors.grey.withOpacity(0.1),
                      selectedTileColor: Colors.amber.withOpacity(0.1),
                      onTap: () => setState(() {
                        _selectedIndex = index;
                      }),
                    );
                  },
                  separatorBuilder: (_, index) => const Divider(height: 1),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```
</details>

**Closed by danagbemava-nc** 2024-08-28 09:58 UTC
Labels: in triage
