### ISSUE TITLE
[Camera] Only one back camera is returned instead of 3 with availableCameras() on iPhone 12 Pro

### ISSUE THREAD

**Issue by barnabashomola** [flutter/flutter#80865] opened 2021-04-21 14:09 UTC
## Steps to Reproduce

When using `availableCameras()` it only returns 2 cameras (one front and one back camera) on an iPhone 12 Pro. However, I specifically want to use the telephoto camera. Is this a bug or it's not possible to have control over which back camera to use?

`camera` plugin version: `version: "0.8.1"`

**Expected results:** 

Return a list of 4 cameras (one front and three back cameras).

**Actual results:** 

Returns a list of only 2 cameras.
```
[0]:CameraDescription (CameraDescription(com.apple.avfoundation.avcapturedevice.built-in_video:0, CameraLensDirection.back, 90))
[1]:CameraDescription (CameraDescription(com.apple.avfoundation.avcapturedevice.built-in_video:1, CameraLensDirection.front, 90))
```

<details>
  <summary>Logs</summary>

`flutter doctor -v`:

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-DK)
    • Flutter version 2.0.3 at /Users/barnabashomola/Developer/flutter
    • Framework revision 4d7946a68d (5 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/barnabashomola/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • Kuatro’s iPhone (mobile) • 00008101-0016305A0E21001E • ios            • iOS 14.4.2
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

</details>

**Comment by utsavDave97** [comment] 2021-07-28 13:45
same issues with iPhone 11 / Samsung S21 and also other Android Devices which have multiple back cameras...any update on this one?

**Comment by urossm** [comment] 2021-10-04 18:56
The problem here is that Camera2 API uses multi-camera system which takes all the back cameras and group them in one logical back camera, same for the front if there is multiple front cameras. So the camera plugin returns only first back camera in that logical system and same for the front. The thing that has to be done is to somehow based on the FOV choose the physical camera that you need(standard wide, ultrawide or telephoto) and pass it to flutter

**Comment by urossm** [comment] 2021-10-04 18:57
https://developer.android.com/training/camera2/multi-camera

**Comment by csomers** [comment] 2021-11-17 11:49
Another vote to get this one fixed.

**Comment by devnullpointer** [comment] 2021-11-30 22:26
@csomers and another one here as well. This is a must and don't know why its taken 3 phone versions for it to even be considered since the ultra wide came out with the iPhone 11, we are now at iPhone 13.

**Comment by utsavDave97** [comment] 2021-11-30 22:37
Any solutions?

**Comment by w3ggy** [comment] 2022-02-22 08:34
+1
There is no solution still 😄 
iPhone 13 Pro return only 2 cameras (back and front)

**Comment by lumisoft** [comment] 2022-03-09 09:37
+1 vote for the fix smile
iPhone 12 the same issue

**Comment by backandy** [comment] 2022-04-05 16:52
+1
please fix it

**Comment by maheshmnj** [comment] 2022-04-06 01:58
Please avoid comments like  "+1" as it doesn't provide any helpful info to fix the issue and the important comments might get unnoticed. If you are affected by this issue Please leave an upvote 👍🏻 on the original post. The number of upvotes is one of the factors that help the flutter team to prioritize the issue.

**Comment by lumisoft** [comment] 2022-04-07 12:35
I was facing the same issue, and made a quick fix here to solve this:
https://github.com/lumisoft/plugins/commit/f5eced2306c938492504ba3e9fadebf21e36f9f5
Working now on my iPad having more than one back camera.

**Comment by martingeorgiu** [comment] 2022-05-06 17:02
I've created PR to solve this issue. Hopefully, it will be soon merged:)

https://github.com/flutter/plugins/pull/5636

**Closed** 2022-05-23 16:48 UTC
Labels: e: device-specific, platform-ios, plugin, p: first party, p: camera, passed first triage, P4

**Comment by martingeorgiu** [comment] 2022-05-23 16:58
@TahaTesser @jmagman  Could you please reopen this issue as this [PR](https://github.com/flutter/plugins/pull/5636) only fixed the iOS part, but this Issue serves for both iOS and Android, because [similar issue](https://github.com/flutter/flutter/issues/91247) for this on Android was closed as duplicate of this

**Comment by jmagman** [comment] 2022-05-23 17:54
I reopened https://github.com/flutter/flutter/issues/91247.
