### ISSUE TITLE
Unhandled exception: RangeError (index): Invalid value: Only valid value is 0: 1

### ISSUE THREAD

**Issue by itsgm** [flutter/flutter#28864] opened 2019-03-05 01:04 UTC
When I flutter doctor, It's this Crash.

Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core/runtime/libgrowable_array.dart:145:60)
#1      AndroidNdk.locateNdk.findNdkMajorVersion.<anonymous closure> (package:flutter_tools/src/android/android_sdk.dart:222:42)
#2      MapBase._fillMapWithMappedIterable (dart:collection/maps.dart:67:32)
#3      new LinkedHashMap.fromIterable (dart:collection/linked_hash_map.dart:124:13)
#4      AndroidNdk.locateNdk.findNdkMajorVersion (package:flutter_tools/src/android/android_sdk.dart:219:44)
#5      AndroidNdk.locateNdk (package:flutter_tools/src/android/android_sdk.dart:233:47)
#6      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:341:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#10     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#11     AppContext.[] (package:flutter_tools/src/base/context.dart:113:22)
#12     androidSdk (package:flutter_tools/src/android/android_sdk.dart:20:37)
#13     AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:180:9)
<asynchronous suspension>
#14     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:318:52)
#15     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#16     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:315:36)
#17     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#18     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#19     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#20     Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#21     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#23     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#30     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#32     _doctorText (package:flutter_tools/runner.dart:187:19)
#33     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#34     _doctorText (package:flutter_tools/runner.dart:183:27)
#35     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#36     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#37     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#38     _handleToolError (package:flutter_tools/runner.dart:120:33)
#39     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#44     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#45     Future._complete (dart:async/future_impl.dart:473:7)
#46     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#47     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#48     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#49     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#50     _asyncErrorWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:84:45)
#51     _rootRunBinary (dart:async/zone.dart:1144:38)
#52     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#53     _FutureListener.handleError (dart:async/future_impl.dart:140:20)
#54     Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#55     Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#56     Future._completeError (dart:async/future_impl.dart:491:5)
#57     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#58     _Completer.completeError (dart:async/future_impl.dart:27:5)
#59     _AsyncAwaitCompleter.completeError (dart:async/runtime/libasync_patch.dart:40:18)
#60     IOClient.send (package:http/src/io_client.dart)
#61     _asyncErrorWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:84:45)
#62     _rootRunBinary (dart:async/zone.dart:1144:38)
#63     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#64     _FutureListener.handleError (dart:async/future_impl.dart:140:20)
#65     Future._propagateToListeners.handleError (dart:async/future_impl.dart:651:47)
#66     Future._propagateToListeners (dart:async/future_impl.dart:672:24)
#67     Future._completeError (dart:async/future_impl.dart:491:5)
#68     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:539:7)
#69     _rootRun (dart:async/zone.dart:1124:13)
#70     _CustomZone.run (dart:async/zone.dart:1021:19)
#71     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#72     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#73     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#74     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#75     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by chandreshsankhala** [comment] 2019-03-17 04:46
i have get same errors as @itsgm  get , please some one help

**Comment by fengmingye** [comment] 2019-03-18 03:13
i have get same errors as @itsgm get , please some one help

**Comment by jonahwilliams** [comment] 2019-03-18 05:08
Duplicate of https://github.com/flutter/flutter/issues/29486 (which I have a fix pending for in  https://github.com/flutter/flutter/pull/29528)

**Closed by jonahwilliams** 2019-03-18 05:08 UTC

**Comment by debasmitasarkar** [comment] 2019-10-17 06:26
I am getting this. Any fix?

**Comment by khaliqdadmohmand** [comment] 2020-04-30 12:39
try this it will help you:
https://youtu.be/KkHq5fzV-u0
