### ISSUE TITLE
Can the Flutter create desktop application in android studio?

### ISSUE THREAD

**Issue by biij5698** [flutter/flutter#35693] opened 2019-07-07 07:23 UTC
I know the flutter now can create desktop application, but it's hard to use, it would be very good if it can be created desktop application in android studio.

**Comment by stuartmorgan** [comment] 2019-07-07 12:45
This is not the issue tracker for the Android Studio Flutter plugin; please file requests for it at https://github.com/flutter/flutter-intellij/ in the future.

This is a duplicate of https://github.com/flutter/flutter-intellij/issues/3508

**Closed by stuartmorgan** 2019-07-07 12:45 UTC
