### ISSUE TITLE
Running flutter iOS App in Release mode on M1 Macbook (My Mac Designed for iPad) crashes

### ISSUE THREAD

**Issue by marcel-bluestone** [flutter/flutter#82859] opened 2021-05-18 21:46 UTC
When trying to run a release version of my flutter 2.2 app via Xcode 12 on the M1 Macbook with target My Mac (Designed 
for iPad) the app crashes with the following error:

```
VM snapshot invalid and could not be inferred from settings.
2021-05-18 23:20:22.291114+0200 Runner[5131:59431] [VERBOSE-2:dart_vm.cc(257)] Could not set up VM data to bootstrap the VM from.
2021-05-18 23:20:22.291171+0200 Runner[5131:59431] [VERBOSE-2:dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
2021-05-18 23:20:22.291228+0200 Runner[5131:59431] [VERBOSE-3:shell.cc(155)] Check failed: vm. Must be able to initialize the VM.
```

Everything works fine with a debug build.
As I only "see" the My Mac device in Xcode, I cannot run the app from Android Studio and flutter doctor does not find the device. 

Is there anything special missing for the release mode to run flutter on the arm64 chip or is this a bug?

**Comment by marcel-bluestone** [comment] 2021-05-19 12:18
Hi @TahaTesser 

here's the output of flutter doctor -v:
`[✓] Flutter (Channel stable, 2.2.0, on macOS 11.3.1 20E241 darwin-arm, locale de-DE)
    • Flutter version 2.2.0 at /Users/marcel/Downloads/flutter
    • Framework revision b22742018b (vor 4 Tagen), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/marcel/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
`

Here's my pubspec.yaml file:
`name: test_sensors
description:
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_gauges: ^19.1.54
  bluestone_bluetooth:
    path: ./libraries/bluestone_bluetooth
  permission_handler: ^6.0.1+1
  sqflite_sqlcipher: ^2.0.0-nullsafety.0
  crypto: ^3.0.0
  vector_math: ^2.0.8
  flutter_cube: ^0.1.1
  fl_chart: ^0.20.1
  stats: ^2.0.0
  image: ^3.0.1
  scidart: ^0.0.1-dev.6
  video_player: ^2.0.2
  pdf: ^3.0.1
  flutter_full_pdf_viewer: ^1.0.6
  path: ^1.6.14
  path_parsing: ^0.2.0-nullsafety.0
  path_drawing: 0.5.0-nullsafety.0
  crypt: ^4.0.1
  provider: ^5.0.0
  intl: any
  flutter_localizations:
    sdk: flutter
  http: any
  json_annotation: ^4.0.0
  path_provider: ^2.0.1
  charts_flutter: ^0.10.0
  url_launcher: ^6.0.2
  wakelock: ^0.5.0+2
  flutter_echarts: #latest version
  printing: ^5.0.0
  rxdart: ^0.26.0
  plugin_platform_interface: ^2.0.0
  flutter_tts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.2
  build_runner: any
  flutter_launcher_icons: ^0.9.0

flutter_icons:
    android: true #"launcher_icon"
    ios: true
    image_path: "assets/images/deubellogo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/deubellogo.png
    - assets/images/config.png
    - assets/images/history.png
    - assets/images/measure.png
    - assets/images/measuregame.png
    - assets/images/ski.png
    - assets/images/training.png
    - assets/images/blocks.png
    - assets/knee_model/lower_knee.obj
    - assets/knee_model/upper_knee.obj
    - assets/knee_model/lower_knee.mtl
    - assets/knee_model/upper_knee.mtl
    - assets/point/point.obj
    - assets/point/point.mtl
    - assets/ski_game/player_left.png
    - assets/ski_game/player_right.png
    - assets/ski_game/player_straight.png
    - assets/ski_game/snow.png
    - assets/ski_game/tree.png
    - assets/videos/dropjump.mp4
    - assets/videos/jumpgame.mp4
    - assets/videos/normal_measure_squat.mp4
    - assets/videos/squat_description.mp4
    - assets/images/meter.png
    - assets/images/measure.png
    - assets/images/history.png
    - assets/images/db_sidebias_left.png
    - assets/images/db_sidebias_right.png
    - assets/images/training2.png
    - assets/images/training.png
    - assets/images/drop.png
    - assets/images/squat.png
    - assets/images/long.png
    - assets/images/ski2.png
    - assets/measure/target_large_spot.png
    - assets/measure/target_small_spot.png
    - assets/measure/target_no_spot.png
    - assets/tilt_display/back.png
    - assets/tilt_display/front.png
    - assets/tilt_display/left.png
    - assets/tilt_display/right.png
    - assets/tilt_display/straight.png
flutter_intl:
  main_locale: en_US
  enabled: true
`

The code sample is complicated as our entire package comprises of 200+ files.

**Comment by TahaTesser** [comment] 2021-05-20 07:45
Hi @marcel-bluestone 
Since you're running in release mode, that might be the cause, since Flutter doesn't support release on simulators 
https://github.com/flutter/flutter/issues/11754 which would apply to M1 target iOS as well 
Also, read https://github.com/flutter/flutter/issues/64502#issuecomment-755839408
For release mode, you need to use a device 
Closing as duplicate of https://github.com/flutter/flutter/issues/11754

**Closed by TahaTesser** 2021-05-20 07:45 UTC
Labels: in triage
