### ISSUE TITLE
[go_router] ShellRoute '!keyReservation.contains(key)': is not true. If navigate outside of shell and push again [go_router]

### ISSUE THREAD

**Issue by yelmuratoff** [flutter/flutter#156585] opened 2024-10-11 12:36 UTC
### Steps to reproduce

1. Open the application and ensure you are on the home page.
2. Click on the Profile icon in the navigation bar (navbar).
3. On the Profile page, locate and click on the Tap button.
4. This action should navigate you to the Programs page.
5. While on the Programs page, click the Tap button again.
6. This should push (navigate) you to the Search page.
7. Note: The Search page is outside the current stack, and it's a child of the Feed page.
8. On the Search page, click the Tap button once again.
9. An error should occur at this step.

### Expected results

Each Tap button click (push between pages) should successfully navigate between pages without issues.

### Actual results

Clicking the Tap button on the Search page results in an error.

### Code sample

pubspect.yaml:

```
name: shell_providers
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

final GlobalKey<NavigatorState> _rootNavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'root');
final GlobalKey<NavigatorState> _sectionANavigatorKey = GlobalKey<NavigatorState>(debugLabel: 'feed');
final GlobalKey<NavigatorState> _shellProgramsKey = GlobalKey<NavigatorState>(debugLabel: 'shell');

void main() {
  runApp(NestedTabNavigationExampleApp());
}

class NestedTabNavigationExampleApp extends StatelessWidget {
  NestedTabNavigationExampleApp({super.key});

  final GoRouter _router = GoRouter(
    navigatorKey: _rootNavigatorKey,
    initialLocation: '/feed',
    routes: <RouteBase>[
      StatefulShellRoute.indexedStack(
        builder: (BuildContext context, GoRouterState state, StatefulNavigationShell navigationShell) {
          return ScaffoldWithNavBar(
            navigationShell: navigationShell,
          );
        },
        branches: <StatefulShellBranch>[
          StatefulShellBranch(
            navigatorKey: _sectionANavigatorKey,
            routes: <RouteBase>[
              GoRoute(
                path: '/feed',
                builder: (BuildContext context, GoRouterState state) => const TabScreen(
                  text: 'Feed',
                ),
                routes: [
                  GoRoute(
                    path: 'search',
                    builder: (BuildContext context, GoRouterState state) => TabScreen(
                      text: 'Search',
                      onTap: () {
                        GoRouter.of(context).push('/profile/programs/1');
                      },
                    ),
                  ),
                ],
              ),
            ],
          ),
          StatefulShellBranch(
            routes: <RouteBase>[
              GoRoute(
                  path: '/profile',
                  builder: (BuildContext context, GoRouterState state) => TabScreen(
                        text: 'Profile',
                        onTap: () {
                          GoRouter.of(context).push('/profile/programs');
                        },
                      ),
                  routes: [
                    // Nested ShellRoute
                    // I use it like scope wrapper for my providers inside builder.
                    ShellRoute(
                      navigatorKey: _shellProgramsKey,
                      builder: (context, state, child) {
                        return child;
                      },
                      routes: [
                        GoRoute(
                          path: 'programs',
                          builder: (BuildContext context, GoRouterState state) => TabScreen(
                            text: 'Programs',
                            onTap: () {
                              GoRouter.of(context).push('/feed/search');
                            },
                          ),
                          routes: [
                            GoRoute(
                              path: ':id',
                              builder: (BuildContext context, GoRouterState state) => TabScreen(
                                text: 'ID: ${state.pathParameters['id']}',
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ]),
            ],
          ),
        ],
      ),
    ],
  );

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routerConfig: _router,
      );
}

class TabScreen extends StatelessWidget {
  const TabScreen({
    required this.text,
    this.onTap,
    super.key,
  });

  final String text;
  final void Function()? onTap;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: Text(
              text,
              style: const TextStyle(fontSize: 24),
            ),
          ),
          ElevatedButton(
            onPressed: onTap,
            child: const Text('Tap'),
          ),
        ],
      ),
    );
  }
}

class ScaffoldWithNavBar extends StatefulWidget {
  const ScaffoldWithNavBar({
    required this.navigationShell,
    Key? key,
  }) : super(key: key ?? const ValueKey<String>('ScaffoldWithNavBar'));

  final StatefulNavigationShell navigationShell;

  @override
  State<ScaffoldWithNavBar> createState() => _ScaffoldWithNavBarState();
}

class _ScaffoldWithNavBarState extends State<ScaffoldWithNavBar> with TickerProviderStateMixin {
  late final TabController _tabController = TabController(length: 2, vsync: this);

  @override
  void dispose() {
    super.dispose();
    _tabController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: widget.navigationShell,
      bottomNavigationBar: TabBar(
        controller: _tabController,
        tabs: const <Tab>[
          Tab(icon: Icon(Icons.feed), text: 'Feed'),
          Tab(icon: Icon(Icons.person), text: 'Profile'),
        ],
        onTap: (int index) async {
          widget.navigationShell.goBranch(
            index,
            initialLocation: index == widget.navigationShell.currentIndex,
          );
        },
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

VIDEO:

</details>

https://github.com/user-attachments/assets/6182731f-5d7b-4e5f-a88c-b1406e10650b

### Logs

<details open><summary>Logs</summary>

```console
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building HeroControllerScope:
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3925 pos 18: '!keyReservation.contains(key)': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 15.0 24A335 darwin-arm64, locale en-KZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment] 2024-10-11 12:54
Hi @yelmuratoff, this is a duplicate of https://github.com/flutter/flutter/issues/140586. 

Kindly subscribe to the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2024-10-11 12:54 UTC
Labels: in triage
