### ISSUE TITLE
url_launcher: ^5.7.2 gives error

### ISSUE THREAD

**Issue by wijesijp** [flutter/flutter#67405] opened 2020-10-06 10:30 UTC
I have installed url_launcher: ^5.7.2
when i run the application it gives me following error message;

Note:..\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.7.2\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

I am using build:gradle:3.5.0

Even though i get the error message the application runs and url launcher works

**Comment by Dasunx** [comment] 2020-10-06 10:49
Duplicate of #37616

This isn't an error message, just a warning. you can refer issue #37616 to more details

**Comment by darshankawar** [comment] 2020-10-06 11:33
Closing as duplicate of [37616](https://github.com/flutter/flutter/issues/37616)

**Closed by darshankawar** 2020-10-06 11:33 UTC
