### ISSUE TITLE
Web: Cursor jumps to the start, if TextField (with Autofill) changes size or transform

### ISSUE THREAD

**Issue by AndroidNils** [flutter/flutter#63596] opened 2020-08-12 18:37 UTC
## Description
![TextfieldBug](https://user-images.githubusercontent.com/24459435/90053335-9d675e80-dcda-11ea-9709-465044306fac.gif)

If an `TextField` with the autofill parameter (this is important) gets an error from a `StreamBuilder` / `FutureBuilder` the cursor goes to the start of the `TextField` and it isn't possible to type anything new.

## Steps to Reproduce

<details>
  <summary>Code to reproduce</summary>

```
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  Future<int> throwExecptionAfter3Seconds() async {
    await Future.delayed(const Duration(seconds: 3));
    throw Random().nextInt(1000);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      home: Material(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Center(
            child: FutureBuilder<void>(
              future: throwExecptionAfter3Seconds(),
              builder: (context, snapshot) {
                return TextField(
                  autofillHints: [AutofillHints.email], // Bug works only with this line!
                  decoration:
                      InputDecoration(errorText: snapshot.error?.toString()),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

1. Run code.
2. Type something before the error (from `FutureBuilder`) is thrown --> error will be thrown after 3 seconds.
3. See that cursor at the beginning and typing isn't possible anymore.

#### Flutter doctor

<details>
  <summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-10.0.pre.55, on Mac OS X 10.15.5 19F101,
    locale en-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.47.3)
 
[✓] Connected device (4 available)            
    ! Error: iPhone von Roland is not connected. Xcode will continue when iPhone
      von Roland is connected. (code -13)

• No issues found!
```

</details>

cc: @nturgut @LongCatIsLooong

**Comment by LongCatIsLooong** [comment] 2020-08-13 08:20
I couldn't reproduce the bug on iOS or Android. I followed the steps and the cursor stayed at the end of the text, and the text field remained responsive, after the error text showed up. I'm on Channel master, 1.21.0-10.0.pre.70.

**Comment by markusaksli-nc** [comment] 2020-08-13 09:10
Can't reproduce on Android or Windows desktop, didn't test MacOS desktop.

### iOS:
If I place the cursor at the beginning, can't type at all anymore, moving cursor doesn't help.

### Steps used for web

1. `flutter build web`
2. `cd build/web`
3. `http-server` (Node.js package)

### Windows web:

- Chrome: Cursor jumps to beginning, can't type anymore. Can type again after repositioning cursor.
- Firefox: Cursor doesn't move, can type. If I place the cursor at the beginning, can't type at all anymore, moving cursor doesn't help.
- Edge: Weird double cursor issue and field gets cleared randomly but this doesn't repro.

### MacOS web:

- Chrome: Same as windows
- Firefox: Same as windows. Also cursor gets more and more offset from the end of the text the more I type?
- Safari: Cursor doesn't move, can't type. Can type again after repositioning cursor. Same issue with cursor offset.

In any case, the behavior is very buggy here. Marking as reproducible on latest master `1.21.0-10.0.pre.70`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.70, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.21.0-10.0.pre.70 at C:\Development\flutter_master
    • Framework revision 0629030a05 (5 hours ago), 2020-08-13 00:01:03 -0400
    • Engine revision 7571e7c380
    • Dart version 2.10.0 (build 2.10.0-11.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.125

• No issues found!
```
</details>

**Comment by markusaksli-nc** [comment] 2020-08-13 09:21
Dartpad seems to produce the same results https://dartpad.dev/61afe9770fdfc4334eb4aa31e016d889

**Comment by nturgut** [comment] 2020-08-13 17:36
@AndroidNils  can you share an example code piece? 

@markusaksli-nc unfortunately Dart Pad is behind. It is best to test Autofill related features on the master channel.

**Comment by AndroidNils** [comment] 2020-08-13 17:52
I forgot to mention this: This is an only Flutter web issue!

@nturgut There is already an example in the description. Again:

```
import 'dart:math';

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  Future<int> throwExecptionAfter3Seconds() async {
    await Future.delayed(const Duration(seconds: 3));
    throw Random().nextInt(1000);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Demo',
      home: Material(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Center(
            child: FutureBuilder<void>(
              future: throwExecptionAfter3Seconds(),
              builder: (context, snapshot) {
                return TextField(
                  autofillHints: [AutofillHints.email], // Bug works only with this line!
                  decoration:
                      InputDecoration(errorText: snapshot.error?.toString()),
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by nturgut** [comment] 2020-08-18 23:18
I'm looking at this example here are a few things:

1) On web only having email field won't be a good design for most browsers. The information will be filled for sure. However, Chrome for example recognizes the form after some fields are all filled and save the information. (This is not related to web, it is how browsers are designed.) 
2) Why there is an exception thrown in 30 seconds? If you can explain with a real life situation?

**Comment by nturgut** [comment] 2020-08-19 01:20
Ah, I see the issue is not the exception or the errors. The issue is the location is changing, framework triggers the size/transform [message](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/text_input.dart#L891).

I'm renaming the issue.

**Comment by AndroidNils** [comment] 2020-08-19 08:07
@nturgut Example: You have a login form, where a BLoC validates the data. If the user enters a wrong character, the BLoC will throw an error (via a `StreamBuilder`), like "Invalid character", "Invalid mail", "Password is too short", "Password is no correct". If this happens, the cursor jumps to the start and the user can not enter the correct data.

**Closed** 2020-08-19 21:03 UTC
Labels: P5, a: text input, found in release: 1.21, platform-web

**Comment by AndroidNils** [comment] 2020-08-19 21:49
@nturgut Thank you for the quick fix! 💙
