### ISSUE TITLE
[firebase_admob] iOS 14 App Tracking Transparency authorization

### ISSUE THREAD

**Issue by tonypottera24** [flutter/flutter#64949] opened 2020-08-31 13:31 UTC
According to google's document
https://developers.google.com/admob/ios/ios14

Starting in iOS 14, IDFA will be unavailable until an app calls the App Tracking Transparency framework to present the app-tracking authorization request to the end user. If an app does not present this request, the IDFA will automatically be zeroed out which may lead to a significant loss in ad revenue.

It would be helpful if firebase_admob can add a function to request tracking.
```
import AppTrackingTransparency
import AdSupport
...
func requestIDFA() {
  ATTrackingManager.requestTrackingAuthorization(completionHandler: { status in
    // Tracking authorization completed. Start loading ads here.
    // loadAd()
  })
}
```

**Comment by TahaTesser** [comment] 2020-08-31 14:10
Hi @tonypottera24 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-08-31 14:10 UTC
