### ISSUE TITLE
Issue with gradle after adding android intent plus dependency

### ISSUE THREAD

**Issue by subins829** [flutter/flutter#125626] opened 2023-04-27 12:36 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

Trying to build app -- not working after using android_intent_plus 

### Expected results

App can be build before

### Actual results

Couldn't build the app after adding android_intent_plus dependency

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![image](https://user-images.githubusercontent.com/90414446/234863184-0fa2aa9b-8073-4788-bfd7-c0b07fd25f24.png)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
![image](https://user-images.githubusercontent.com/90414446/234863558-44d595c2-45b7-44c5-bef8-8282540f07de.png)
```

</details>

**Comment by subins829** [comment] 2023-04-27 12:37
![image](https://user-images.githubusercontent.com/90414446/234863952-5f4c497b-f3e9-400f-b1b5-037cfb0646f7.png)

**Comment by darshankawar** [comment] 2023-04-27 12:54
Closing as duplicate of https://github.com/flutter/flutter/issues/125621.

**Closed by darshankawar** 2023-04-27 12:54 UTC
Labels: in triage
