### ISSUE TITLE
Flutter Gallery TextField emoji issue

### ISSUE THREAD

**Issue by lishuhao** [flutter/flutter#30281] opened 2019-04-01 02:13 UTC
## When delete emoji , always leave a question mark

![](https://raw.githubusercontent.com/lishuhao/assets/master/emoji_issue.gif)

## Steps to Reproduce
1. Open Flutter Gallery App
1. Tap material panel
1. Tap Text fields
1. Input emoji
1. delete emoji

```
👉  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by HansMuller** [comment] 2019-04-01 16:39
CC @GaryQian

**Comment by GaryQian** [comment] 2019-04-01 17:35
Duplicate of https://github.com/flutter/flutter/issues/23496. This only happens with a chinese locale.

Closing to de-dupe.

**Closed by GaryQian** 2019-04-01 17:35 UTC
Labels: a: text input, a: typography, f: material design, framework
