### ISSUE TITLE
[tool_crash] FileSystemException: Exists failed, OS Error: Le périphérique n’est pas prêt., errno = 21

### ISSUE THREAD

**Issue by achil21** [flutter/flutter#104724] opened 2022-05-26 15:20 UTC
## Command
```
flutter clean
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Exists failed, OS Error: Le périphérique n’est pas prêt.
, errno = 21
```
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:43:33)
#2      ErrorHandlingDirectory.existsSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:497:22)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#4      ErrorHandlingDirectory.existsSync (package:flutter_tools/src/base/error_handling_io.dart:496:12)
#5      PubDependencies.isUpToDate (package:flutter_tools/src/flutter_cache.dart:102:57)
<asynchronous suspension>
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:677:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1275:7)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, 2.10.0-1.0.pre.250, on Microsoft Windows [version 10.0.19044.1288], locale fr-FR)
    • Flutter version 2.10.0-1.0.pre.250 at H:\android\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f1ef491e0 (4 months ago), 2022-01-23 07:45:11 -0500
    • Engine revision 8162e8d86e
    • Dart version 2.17.0 (build 2.17.0-48.0.dev)
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\MALKI\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: H:\android\Nouveau dossier\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at H:\android\Android_studio\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Android Studio (version 2020.3)
    • Android Studio at H:\android\Nouveau dossier
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.67.2)
    • VS Code at C:\Users\MALKI\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • Samsung Galaxy S10 (mobile) • 192.168.170.101:5555 • android-x86    • Android 10 (API 29)
    • Chrome (web)                • chrome               • web-javascript • Google Chrome 101.0.4951.64
    • Edge (web)                  • edge                 • web-javascript • Microsoft Edge 92.0.902.67

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: malformed
**Version**: 1.2.4+23
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
cloud_firestore-3.1.0
cloud_firestore_web-2.6.7
firebase_auth-3.2.0
firebase_auth_web-3.3.7
firebase_core-1.10.0
firebase_core_web-1.5.4
firebase_messaging-11.1.0
firebase_messaging_web-2.2.7
firebase_storage-10.1.0
firebase_storage_web-3.2.7
flutter_plugin_android_lifecycle-2.0.5
geolocator-7.7.1
geolocator_android-2.1.0
geolocator_apple-1.2.2
geolocator_web-2.0.6
google_api_headers-1.1.1
google_maps_flutter-2.1.1
google_maps_flutter_web-0.3.2
image_picker-0.8.4+4
image_picker_for_web-2.1.5
package_info_plus-1.3.0
package_info_plus_macos-1.3.0
package_info_plus_web-1.0.4
path_provider-2.0.8
path_provider_android-2.0.11
path_provider_ios-2.0.7
path_provider_linux-2.1.5
path_provider_macos-2.0.5
path_provider_windows-2.0.5
permission_handler-8.3.0
sqflite-2.0.2
url_launcher-6.0.15
url_launcher_linux-2.0.4
url_launcher_macos-2.0.4
url_launcher_web-2.0.6
url_launcher_windows-2.0.3
video_player-2.2.18
video_player_android-2.2.17
video_player_avfoundation-2.2.18
video_player_web-2.0.6
wakelock-0.5.6
wakelock_macos-0.4.0
wakelock_web-0.4.0
webview_flutter-2.3.1
webview_flutter_android-2.8.2
webview_flutter_wkwebview-2.7.1

**Comment by iapicca** [comment] 2022-05-26 17:43
possibly related to https://github.com/flutter/flutter/issues/81146

**Comment by exaby73** [comment] 2022-05-27 06:37
Upon further investigation, this does seem like a duplicate of #81146

**Closed by exaby73** 2022-05-27 06:37 UTC
