### ISSUE TITLE
Option to make truly blank projects with the flutter CLI

### ISSUE THREAD

**Issue by Matt-Gleich** [flutter/flutter#51497] opened 2020-02-26 20:26 UTC
## Proposal

It would be great if the flutter CLI could have a flag that allows you to make a truly blank project with a blank lib/main.dart, blank test/main_test.dart and pubspec.yaml with no comments.

**Comment by jmagman** [comment] 2020-02-27 02:45
Duplicate of #14719
See https://github.com/flutter/flutter/issues/14719#issuecomment-366109914

**Closed by jmagman** 2020-02-27 02:45 UTC
Labels: proposal, tool
