### ISSUE TITLE
EXCEPTION CAUGHT BY FLUTTER FRAMEWORK

### ISSUE THREAD

**Issue by amirbahrawy** [flutter/flutter#132289] opened 2023-08-10 06:59 UTC
The following assertion was thrown while executing callbacks for FrameTiming:
'package:flutter/src/widgets/binding.dart': Failed assertion: line 841 pos 16: 'sendFramesToEngine':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      WidgetsBinding.drawFrame.<anonymous closure> (package:flutter/src/widgets/binding.dart:841:16)
#3      SchedulerBinding._executeTimingsCallbacks (package:flutter/src/scheduler/binding.dart:329:19)
#7      _invoke1 (dart:ui/hooks.dart:166:10)

**Comment by danagbemava-nc** [comment] 2023-08-10 08:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/89651

**Closed by danagbemava-nc** 2023-08-10 08:14 UTC
Labels: in triage
