### ISSUE TITLE
flutter build ipa failing with `Target aot_assembly_release failed: Exception: AOT snapshotter exited with code -9` exception

### ISSUE THREAD

**Issue by albertocappellina** [flutter/flutter#95269] opened 2021-12-14 17:19 UTC
## Steps to Reproduce

(my app has 2 environment and 2 flavours)

1.  flutter run --dart-define=ENVIRONMENT=dev --flavor=dev workss ok on iphone
2. flutter build ipa --dart-define=ENVIRONMENT=dev --flavor prod 

complete with error

   1 warning generated.
    Dart snapshot generator failed with exit code -9
    Failed to package /Users/alberto.cappellina/sources/namirial/app_rao.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

"same command"  flutter build apk --dart-define=ENVIRONMENT=dev --flavor prod completes without errors

## Logs

<details>
<summary>Logs</summary>

[log.txt](https://github.com/flutter/flutter/files/7713513/log.txt)

[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.5.3 at /Users/alberto.cappellina/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/alberto.cappellina/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/alberto.cappellina/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/alberto.cappellina/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 4.2.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio 4.2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
➜  app_rao git:(develop) ✗ 

</details>

**Comment by darshankawar** [comment] 2021-12-15 07:40
@albertocappellina 
From the log, it seems to be failing due to below:
```

Dart snapshot generator failed with exit code -9
               [   +8 ms] Target aot_assembly_release failed: Exception: AOT snapshotter exited with code -9
                          #0      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:112:7)
                          <asynchronous suspension>
                          #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:836:9)
                          <asynchronous suspension>
                          #2      Future.wait.<anonymous closure> (dart:async/future.dart)
                          <asynchronous suspension>
                          #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:774:32)
                          <asynchronous suspension>
                          #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:603:16)
                          <asynchronous suspension>
                          #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:314:32)
                          <asynchronous suspension>
                          #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
                          <asynchronous suspension>
                          #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                          <asynchronous suspension>
                          #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
                          <asynchronous suspension>
                          #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
                          <asynchronous suspension>
                          #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                          <asynchronous suspension>
                          #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #14     main (package:flutter_tools/executable.dart:92:3)
                          <asynchronous suspension>

               [   +3 ms] 
                          #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
                          #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:331:7)
                          <asynchronous suspension>
                          #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
                          <asynchronous suspension>
                          #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
                          <asynchronous suspension>
                          #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
                          <asynchronous suspension>
                          #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
                          <asynchronous suspension>
                          #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
                          <asynchronous suspension>
                          #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
                          <asynchronous suspension>
                          #10     main (package:flutter_tools/executable.dart:92:3)
                          <asynchronous suspension>
               Failed to package /Users/alberto.cappellina/sources/namirial/app_rao.
               Command PhaseScriptExecution failed with a nonzero exit code
```

Can you provide us a complete minimal reproducible code sample or a github repo that we can clone ?
Also, please try to upgrade to latest stable and see if issue still persists or not.

**Comment by albertocappellina** [comment] 2021-12-15 07:47
Thanks for your answer, i'm not sure i can provide the repo access, gotta ask it to my client. For the other part of your statement, what should i update to latest stable? flutter ? thanks

**Comment by albertocappellina** [comment] 2021-12-15 07:56
A quick follow up: i upgraded flutter to 2.8.0 and retryed, i received same error tho

**Comment by albertocappellina** [comment] 2021-12-15 08:20
when i try to archive from xcode (instead of using flutter command) i can see this error in log

```
   /bin/sh -c /Users/alberto.cappellina/Library/Developer/Xcode/DerivedData/Runner-atvpgtrojxyigveellzgdbioeeni/Build/Intermediates.noindex/ArchiveIntermediates/dev/IntermediateBuildFilesPath/Runner.build/Release-dev-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh

Dart snapshot generator failed with exit code -9
Failed to package /Users/alberto.cappellina/sources/namirial/app_rao.
Command PhaseScriptExecution failed with a nonzero exit code
```


i tried to open the script and this is its content

`#!/bin/sh
/bin/sh "$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh" build`

**Comment by albertocappellina** [comment] 2021-12-15 09:42
@darshankawar tried the same procedure with stable/dev and beta channel

**Comment by albertocappellina** [comment] 2021-12-15 11:26
@darshankawar before than yesterday we could build for release (we have the very same app approved by apple) 
i also tried with checking out older version of flutter
* 2.5.2
* 2.5.3

but i get always the same error

**Comment by darshankawar** [comment] 2021-12-16 06:12
@albertocappellina 
Thanks for the details. I tried a sample flavors app by running below command which built the ipa properly without any issues:

`flutter build ipa --flavor dev -t lib/main_dev.dart`

```

dhs@Dhss-MacBook-Pro flavors_example % flutter build ipa --flavor dev -t lib/main_dev.dart 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It is being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the --ignore-deprecation flag to
ignore this check and continue with the deprecated v1 embedding. However,
the v1 Android embedding will be removed in future versions of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The detected reason was:

  /Users/dhs/Documents/NCFlutter/triage-examples/flutter_examples/flavors_example/android/app/src/main/AndroidManifest.xml uses `android:name="io.flutter.app.FutterApplication"`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
Archiving com.nevercode.triage...
Updating minimum iOS deployment target from 8.0 to 9.0.
Upgrading project.pbxproj
Upgrading AppFrameworkInfo.plist
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Found saved certificate choice "Apple Development: Darshan Kawar (AV76JL68FU)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "Apple Development: Darshan Kawar (AV76JL68FU)"
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        14.0s
Xcode archive done.                                         50.6s
Built /Users/dhs/Documents/NCFlutter/triage-examples/flutter_examples/flavors_example/build/ios/archive/Runner.xcarchive.

Building without sound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

dhs@Dhss-MacBook-Pro flavors_example % 

```

I didn't try yet with `--dart-defines` because I don't have the env set for it.
Can you try without that flag (ie --dart-defines) and see if it helps ?

Also, not sure if that's intended or a typo but in your original description, you mentioned below commands:



> * flutter run --dart-define=ENVIRONMENT=dev --flavor=dev workss ok on iphone
> * flutter build ipa --dart-define=ENVIRONMENT=dev --flavor prod

For second command, should it be `prod` instead of `dev` ?

**Comment by albertocappellina** [comment] 2021-12-16 06:46
@darshankawar thanks for your kind answer.

i tried removing the --dart-define part but nothing changes: same error.
yesterdey i removed the ios project and recreated it also without flavors so i tried the same command without --flavor but had same result.

for the second part of you answer, it was a typo but we can use dev/prod with no "compiling" issue so changing (and i tried a lot yesterday) won't change a thing

what else can i do?
recreating the project from scratch ? reinstalling flutter?

thanks
Alberto

**Comment by darshankawar** [comment] 2021-12-17 05:17
@albertocappellina Thanks for digging in, but we wouldn't know for sure what specifics you've unless you provide us a clone of the app (doesn't have to be your actual app, but maybe clone with sample data) that'll be enough to replicate the issue.

Also, couple of commands you can try to run for us to verify and share the output:

1. After the crash please try rerunning `/Users/alberto.cappellina/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64 --deterministic --snapshot_kind=app-aot-assembly --assembly=/Users/alberto.cappellina/sources/namirial/app_rao/.dart_tool/flutter_build/2ebfec6f34dde17e3e1d88815fae2a4b/arm64/snapshot_assembly.S --strip /Users/alberto.cappellina/sources/namirial/app_rao/.dart_tool/flutter_build/2ebfec6f34dde17e3e1d88815fae2a4b/app.dill` command under `lldb` and post backtrace here.

2. Run above command again but add  `--trace-compiler` to list of `gen_snapshot_arm64` flags (e.g. right after `--deterministic`). After it crashes can you type `bt` command into LLDB to print the backtrace?

**Comment by albertocappellina** [comment] 2021-12-30 11:57
Hi @darshankawar , sorry for the delay 

so i ran the command on mac console

`/Users/alberto.cappellina/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64 --deterministic --snapshot_kind=app-aot-assembly --assembly=/Users/alberto.cappellina/sources/namirial/app_rao/.dart_tool/flutter_build/<...>/arm64/snapshot_assembly.S --strip /Users/alberto.cappellina/sources/namirial/app_rao/.dart_tool/flutter_build/<....>/app.dill`

and what i got back was

Warning: Generating assembly code without DWARF debugging information.

is it the right place to run it ? i'm on mac, i'm running the command inside Android Studio terminale

**Comment by darshankawar** [comment] 2021-12-31 05:19
@albertocappellina 
The warning is the result of `gen_snapshot` directly, although it was fixed last year by the tool. You may provide the log output of that command.

**Comment by albertocappellina** [comment] 2021-12-31 08:13
@darshankawar  the first command just give that output

"Warning: Generating assembly code without DWARF debugging information."

the second one generates this log.

thanks

[2.log](https://github.com/flutter/flutter/files/7795652/2.log)

**Comment by darshankawar** [comment] 2021-12-31 09:27
Thanks for the log. Labeling it for further input from the team.

/cc @jmagman

**Comment by jmagman** [comment] 2022-01-05 02:02
@mraleph can you help getting a useful dump from the reporter?

**Comment by mraleph** [comment] 2022-01-05 08:51
-9 means SIGKILL. SIGKILL likely means OS killing it, might be out of memory or security policy violation. OOM is most likely especially because running build on its own succeeds. 

I suggest the following, either run the build that fails and look for any mentions of `gen_snapshot` in the output of `dmesg` (immediately after it fails): `sudo dmesg | grep gen_snapshot` and `sudo dmesg | grep kill` 

Alternatively open `Console` app and start streaming system log messages, then kick of the build and let it fail. See if there are any mentions of "kill" and "gen_snapshot" there.

**Comment by albertocappellina** [comment] 2022-01-10 11:16
Hi @mraleph and thanks for support.

Sadly i tried both "dmesg" commands but both the grep bring no output for gen_snapshot nor kill.

I don't know how to upen "Console" app tho, can you help me with the second task you suggested? Thanks

A

**Comment by mraleph** [comment] 2022-01-10 13:24
1. `Console` can be launched from Spotlight (by searching for `Console`) or by launching `/System/Applications/Utilities/Console.app`. 
2. Once you have `Console` open, click start streaming. 
3. Once you have log messages streaming, run the IPA build.
4. Once it fails stop streaming by clicking `Pause` button (it will be where `Start` button was).
5. Then use search field to filter for messages. Try looking for Flutter and `gen_snapshot`. 

Post the results if any.

<img width="1345" alt="Screenshot 2022-01-10 at 14 21 36" src="https://user-images.githubusercontent.com/131846/148773186-acedb792-8d27-49af-9f13-5b812e2d8d20.png">

**Comment by albertocappellina** [comment] 2022-01-10 13:26
Yes, at the end I understood what you mean and did exactly as you said (stream to console and search for gen_snaphost or kill) but nothing came up

any other log i could provide?

Thanks
A

**Comment by mraleph** [comment] 2022-01-10 15:22
Unfortunately I don't have any other ideas. Do you have any antivirus software installed?

**Comment by albertocappellina** [comment] 2022-01-11 14:51
@mraleph  it looks like it was the antivirus indeed. i removed from my computer and launched the build and it completed sucessfully.

i don't know what to say if not thanks a lot for the patience.

for your information the antivirus was Apex One for mac 

I'm goint to report this information to our it repart too. thanks again

**Comment by mraleph** [comment] 2022-01-11 14:53
Thanks @albertocappellina, happy to help!

I will close this issue then.

**Closed by mraleph** 2022-01-11 14:53 UTC
Labels: severe: crash, platform-ios, tool, dependency: dart, passed first triage

**Comment by albertocappellina** [comment] 2022-01-11 14:56
yes, thanks again
