### ISSUE TITLE
[Desktop] PopupMenuButton rebuilding child on hover 

### ISSUE THREAD

**Issue by terryang** [flutter/flutter#90052] opened 2021-09-14 13:56 UTC
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: PopupMenuButton<dynamic>(
            onSelected: (dynamic result) {},
            child: MyTestPage(),
            itemBuilder: (BuildContext context) => <PopupMenuEntry<dynamic>>[
              const PopupMenuItem<dynamic>(
                value: 1,
                child: Text('Menu...'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class MyTestPage extends StatefulWidget {
  @override
  _MyTestPageState createState() => _MyTestPageState();
}

class _MyTestPageState extends State<MyTestPage> {
  @override
  Widget build(BuildContext context) {
    //trigger rebuild here
    return Text("Text.....");
  }
}
```
**What did I do wrong?? It is flutter PopupMenuButton child can not use a StatefulWidget??**

**Comment by maheshmnj** [comment] 2021-09-15 06:13
Hi @terryang Thanks for filing the issue, I am able to replicate the issue on stable `2.2.3` and `2.5.0` and the master channel `2.6..0`. The popMenuButton child is rebuilding on hovering the window. This issue is only on the Desktop and does not rebuild on the web. This can be well understood from the below output video



https://user-images.githubusercontent.com/31410839/133379588-9e3a4556-f436-4fe4-a3c7-49b78a66af3a.mov

_The video shows prints statements in the console from the child widget which indicates the widget is rebuilding_

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: PopupMenuButton<dynamic>(
            onSelected: (dynamic result) {},
            child: MyTestPage(),
            itemBuilder: (BuildContext context) => <PopupMenuEntry<dynamic>>[
              const PopupMenuItem<dynamic>(
                value: 1,
                child: Text('Menu...'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class MyTestPage extends StatefulWidget {
  @override
  _MyTestPageState createState() => _MyTestPageState();
}

class _MyTestPageState extends State<MyTestPage> {
  @override
  Widget build(BuildContext context) {
    //trigger rebuild here
    print('rebuilds');
    return Text("text...");
  }
}

```
</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter_dev
    • Framework revision f4abaa0735 (3 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)                          • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```console
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```

```
[✓] Flutter (Channel master, 2.6.0-1.0.pre.103, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.103 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2c30b252a5 (3 weeks ago), 2021-08-27 23:26:03 -0400
    • Engine revision ca52647cd2
    • Dart version 2.15.0 (build 2.15.0-65.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)                       • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 93.0.4577.63

• No issues found!
```
</details>

**Comment by terryang** [comment] 2021-09-15 07:05
@maheshmnj Thanks a lot

**Comment by gspencergoog** [comment] 2021-09-23 18:16
@terryang I'm not clear on what the issue is here: is it that you can't get the child widget to rebuild?  Or that it is rebuilding whenever the mouse hovers over it?

In your example where it says "//trigger rebuild here" is that where the rebuild is being triggered?  Or that there is missing code there that would trigger a rebuild (which is a bad idea in a build method)?

**Comment by terryang** [comment] 2021-09-24 14:36
> @terryang I'm not clear on what the issue is here: is it that you can't get the child widget to rebuild? Or that it is rebuilding whenever the mouse hovers over it?
> 
> In your example where it says "//trigger rebuild here" is that where the rebuild is being triggered? Or that there is missing code there that would trigger a rebuild (which is a bad idea in a build method)?

The mouse hovers over  the window should not trigger popMenuButton child rebuild.Thanks.
You can see the following video
https://github.com/flutter/flutter/issues/90052#issuecomment-919730308

**Comment by kirolous-nashaat** [comment] 2021-09-24 14:40
Flutter widgets are supposed to rebuild rapidly, that's the point of the rebuild method.
You shouldn't put any logic in the build function anyway.

**Comment by gspencergoog** [comment] 2021-09-24 15:04
> The mouse hovers over the window should not trigger popMenuButton child rebuild

Flutter is a reactive framework, so widgets can rebuild for a number of reasons. In this case, it is rebuilding to show the focus highlight. Popup menu items are placed over an `InkWell`, which changes its color based on whether the widget is being hovered over or not. This change in color requires a rebuild, and a rebuild of the children of that widget, including the items you add to the menu.

This makes me think that Flutter is acting correctly in this case.

If you absolutely want to avoid rebuilding here, you can subclass `PopupMenuItem` and `PopupMenuItemState` and omit anything that would cause a rebuild on hover.  I think that is probably the wrong goal, however, and won't do what you expect, however: it'll present the popup menu very statically, without any highlighting or animation.

You might consider doing any calculations in one of the other lifecycle functions, like `initState` or `didUpdateWidget`.

**Comment by terryang** [comment] 2021-09-25 07:29
@gspencergoog @kirolous-nashaat Thank you for your reply.One more question is this issue only on the Desktop and does not rebuild on the web. Is it the right result？

**Comment by kirolous-nashaat** [comment] 2021-10-05 17:38
@terryang AFAIK, rebuilds can happen at anytime because of several reasons; some of them may depend on specific state changing on one platform and not the other.
so yes, it should be okay.

**Comment by maheshmnj** [comment] 2021-10-06 02:48
Closing, as working as intended based on the above comment https://github.com/flutter/flutter/issues/90052#issuecomment-926699368

**Closed by maheshmnj** 2021-10-06 02:48 UTC
Labels: framework, f: material design, a: desktop, has reproducible steps, P4, found in release: 2.5, found in release: 2.6
