### ISSUE TITLE
[Impeller] Apparent regression in backdrop filter benchmark

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#143945] opened 2024-02-22 16:47 UTC
It's hard to tell because the blur has been changing.  But it looks like the `backdrop_filter_perf_ios__timeline_summary` has become particularly noisy around Feb 3rd.  At first I thought maybe this was a fluke where we were happening to get different downsample levels in the blur.  Now after having reduced the kernel size and not seeing the benchmarks move, I think it may be something else.  February 1st was completely flat and the benchmark was flat before that.

<img width="1754" alt="Screenshot 2024-02-22 at 8 40 58 AM" src="https://github.com/flutter/flutter/assets/30870216/7e50dc74-fbe0-422f-b728-91ce26295fa8">

[skia perf link](https://flutter-flutter-perf.skia.org/e/?begin=1706031314&end=1708616827&queries=sub_result%3Daverage_frame_rasterizer_time_millis%26test%3Dbackdrop_filter_perf_ios__timeline_summary&requestType=0&selected=commit%3D39167%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_frame_rasterizer_time_millis%252Ctest%253Dbackdrop_filter_perf_ios__timeline_summary%252C)

**Comment by gaaclarke** [comment] 2024-02-22 16:59
Here is 90th percentile rasterizer time graphed with the average.  It's very peculiar that they are almost the same.  Maybe that from a low sample count?

<img width="1752" alt="Screenshot 2024-02-22 at 8 55 22 AM" src="https://github.com/flutter/flutter/assets/30870216/5a69259f-4ab5-4cc0-9699-6adfed29c7be">

**Comment by gaaclarke** [comment] 2024-02-22 17:17
Here is a similar oddity showing up with `animated_blur_backdrop_filter_perf_ios__timeline_summary`:`average_cpu_usage`.  The other lines on the graph are rasterizer/gpu related and don't move.

<img width="1734" alt="Screenshot 2024-02-22 at 9 14 18 AM" src="https://github.com/flutter/flutter/assets/30870216/3a0dc038-1453-4694-9d5c-255de0b9094c">

[skia perf link](https://flutter-flutter-perf.skia.org/e/?begin=1706024656&end=1708616827&queries=sub_result%3Daverage_gpu_frame_time%26sub_result%3Daverage_cpu_usage%26sub_result%3Daverage_frame_rasterizer_time_millis%26test%3Danimated_blur_backdrop_filter_perf_ios__timeline_summary&requestType=0&selected=commit%3D39167%26name%3D%252Carch%253Dintel%252Cbranch%253Dmaster%252Cconfig%253Ddefault%252Cdevice_type%253DiPhone_11%252Cdevice_version%253Dnone%252Chost_type%253Dmac%252Csub_result%253Daverage_cpu_usage%252Ctest%253Danimated_blur_backdrop_filter_perf_ios__timeline_summary%252C)

**Comment by gaaclarke** [comment] 2024-02-22 17:33
Here it is in new gallery too:
<img width="1742" alt="Screenshot 2024-02-22 at 9 31 08 AM" src="https://github.com/flutter/flutter/assets/30870216/be0c1be0-a490-4b54-bce7-7a688fdbf0a5">
[skia perf link](https://flutter-flutter-perf.skia.org/e/?begin=1706721473&end=1708622126&queries=sub_result%3Daverage_cpu_usage%26sub_result%3Daverage_frame_rasterizer_time_millis%26sub_result%3Daverage_gpu_frame_time%26test%3Dnew_gallery_ios__transition_perf&requestType=0)

**Comment by jonahwilliams** [comment] 2024-02-22 17:47
I wonder if this is due to natural variation in the benchmark, or varying device performance.

**Comment by gaaclarke** [comment] 2024-02-22 17:56
> I wonder if this is due to natural variation in the benchmark, or varying device performance.

It seems to take off at some point around Feb 3rd though.  Unless there was some sort of infra change at that time, it shouldn't be some natural variation.

I've read through the commits around that time and I'm not seeing anything jump out at me.  I'll now try running them locally and see if I can pinpoint some point where it changed.

**Comment by jonahwilliams** [comment] 2024-02-22 17:59
Infra or device changes could have happened without any commits though. I would check if you can find out which device ran each benchmark and if those devices got updated at all

**Comment by gaaclarke** [comment] 2024-02-22 18:29
Okay, I looked at 2 different benchmarks.  One that was slow and one that was fast and looked at the devices.  One of them is iOS 16, one of them is iOS 17.  That is what is accounting for this super noisy benchmark.

I'm not sure how helpful it is to have a super noisy benchmark.  I would like it if we could separate them by operating system.

Related pr: https://github.com/flutter/flutter/issues/142989
cc @zanderso 

## supporting evidence
New gallery @ 6facb9695360aec7d8b19e10234844f88f14a659 - iOS 17
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8757143164065350129/+/u/run_new_gallery_ios__transition_perf/test_stdout

New gallery @ 3280be93714c8633f57a940b57a1e4286a11ac21 - iOS 16
https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8757141295755484817/+/u/run_new_gallery_ios__transition_perf/test_stdout

**Comment by vashworth** [comment] 2024-02-23 16:52
> @vashworth may be able to speak to the timeline for getting all of the devices onto iOS 17.

I plan to updates tests to run exclusively on iOS 17 today or Monday (https://github.com/flutter/flutter/pull/144022), so that should help with the noisiness.

**Comment by vashworth** [comment] 2024-03-12 14:53
All tests are running on iOS 17 as of Feb 23, which has reduced the noise on the benchmark and makes it clear that it's the cause of the regression. 

I've been told previously that the goal of the benchmarks is to be representative of the devices our users run on and if it has regressed then it has regressed. Closing as non-actionable.

**Closed by vashworth** 2024-03-12 14:53 UTC
Labels: c: performance, P1, e: impeller, team-engine, triaged-engine
