### ISSUE TITLE
The getter 'address' was called on null. Bluetooth connection to a device

### ISSUE THREAD

**Issue by GinLegucki** [flutter/flutter#59598] opened 2020-06-16 21:29 UTC
Hello,
I am trying to create an app that controls the device I'm making via bluetooth and am really new to flutter.
I am getting an error:
'The following NoSuchMethodError was thrown while handling a gesture:
The getter 'address' was called on null.
Receiver: null
Tried calling: address'
When the program is trying to run the _getBTConnection function.

Any help much appreciated!

```dart
import 'dart:typed_data';
import 'package:bartender/BluetoothDeviceListEntry.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bluetooth_serial/flutter_bluetooth_serial.dart';


void main() => runApp(MaterialApp(
  theme: ThemeData(fontFamily: 'Ubuntu-Light'),
  home: MainPage(),
));

class MainPage extends StatefulWidget{
  HomePage createState()=> HomePage();
}

class HomePage extends State<MainPage>{
  var slider1Value = 20.0;
  var slider2Value = 2.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        title: Text("Bartender 1.0"),
        centerTitle: true,
        backgroundColor: Colors.grey[900],
        actions: <Widget>[
          IconButton(
            icon: Icon(Icons.devices_other),
            tooltip: "Połącz się z urządzeniem i zaraz zaczniemy polewać!",
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => BTConnect())
              );
            },
          ),
        ],
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Expanded(
            flex: 5,
            child: Image.asset("assets/vodka_background.jpeg",
              fit: BoxFit.cover,),
          ),
          Expanded(
            flex: 4,
            child: Container(
              margin: EdgeInsets.fromLTRB(0.0, 5.0, 0.0, 5.0),
              // padding: EdgeInsets.all(50.0),
              color: Colors.grey[900],
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    Text("Może wódeczki?",
                    style: TextStyle(
                      color: Colors.white,
                      fontStyle: FontStyle.italic,
                      fontSize: 30.0,
                    ) ,
                      ),
                    ButtonTheme(
                      minWidth: 800,
                      height: 60,
                      child: RaisedButton(
                        onPressed: () {},
                        color: Colors.amber[700],
                        child: Text("Polej!",
                        style: TextStyle(
                          fontSize: 25.0,
                        ) ,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          Expanded(
            flex: 3,
            child: Container(
              margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 5.0),
              padding: EdgeInsets.all(30.0),
              color: Colors.grey[900],
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  SliderTheme(
                    data: SliderTheme.of(context).copyWith(
                      activeTrackColor: Colors.amber[400],
                      inactiveTrackColor: Colors.white,
                      trackShape: RoundedRectSliderTrackShape(),
                      trackHeight: 3.0,
                      thumbShape: RoundSliderThumbShape(enabledThumbRadius: 8.0),
                      thumbColor: Colors.amber[800],
                      overlayColor: Colors.amber.withAlpha(32),
                      overlayShape: RoundSliderOverlayShape(overlayRadius: 15.0),
                      tickMarkShape: RoundSliderTickMarkShape(),
                      activeTickMarkColor: Colors.amber[900],
                      inactiveTickMarkColor: Colors.amber[300],
                      valueIndicatorShape: PaddleSliderValueIndicatorShape(),
                      valueIndicatorColor: Colors.amber,
                      valueIndicatorTextStyle: TextStyle(
                        color: Colors.white,
                      ),
                    ),
                    child: Slider(
                      min: 20.0,
                      max: 50.0,
                      divisions: 3,
                      value: slider1Value,
                      label: "$slider1Value",
                      onChanged: (newValue) {
                        setState(() {
                          slider1Value = newValue;
                        });
                      },
                    ),
                  ),
                  Text(
                    "Jak duże kielonki polać?",
                    style: TextStyle(
                      fontSize: 18.0,
                      color: Colors.white,
                    ),
                  ),
                ],
              ),
            ),
          ),
          Expanded(
            flex: 3,
            child: Container(
              margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 5.0),
              padding: EdgeInsets.all(30.0),
              color: Colors.grey[900],
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  SliderTheme(
                    data: SliderTheme.of(context).copyWith(
                      activeTrackColor: Colors.amber[400],
                      inactiveTrackColor: Colors.white,
                      trackShape: RoundedRectSliderTrackShape(),
                      trackHeight: 3.0,
                      thumbShape: RoundSliderThumbShape(enabledThumbRadius: 8.0),
                      thumbColor: Colors.amber[800],
                      overlayColor: Colors.amber.withAlpha(32),
                      overlayShape: RoundSliderOverlayShape(overlayRadius: 15.0),
                      tickMarkShape: RoundSliderTickMarkShape(),
                      activeTickMarkColor: Colors.amber[900],
                      inactiveTickMarkColor: Colors.amber[300],
                      valueIndicatorShape: PaddleSliderValueIndicatorShape(),
                      valueIndicatorColor: Colors.amber,
                      valueIndicatorTextStyle: TextStyle(
                        color: Colors.white,
                      ),
                    ),
                    child: Slider(
                      min: 2,
                      max: 6,
                      divisions: 4,
                      value: slider2Value,
                      label: "$slider2Value",
                      onChanged: (newValue) {
                        setState(() {
                          slider2Value = newValue;
                        });
                      },
                    ),
                  ),
                  Text(
                    "Ile osób pije?",
                    style: TextStyle(
                      fontSize: 18.0,
                      color: Colors.white,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class BTConnect extends StatefulWidget {
  final BluetoothDevice server;

  const BTConnect({this.server});

  @override
  BTConnectRoute createState()=> BTConnectRoute();
}

class BTConnectRoute extends State<BTConnect> with WidgetsBindingObserver{

  BluetoothState _bluetoothState = BluetoothState.UNKNOWN;
  List<BluetoothDevice> devices = List<BluetoothDevice>();

  BluetoothConnection connection;
  bool isConnecting = true;
  bool get isConnected => connection != null && connection.isConnected;
  bool isDisconnecting = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _getBTState();
    _stateChangeListener();
    // _getBTConnection();
  }

  @override
  void dispose() {
    if(isConnected){
      isDisconnecting = true;
      connection.dispose();
      connection = null;
      WidgetsBinding.instance.removeObserver(this);
    }
    super.dispose();
  }

  _getBTConnection (){
    BluetoothConnection.toAddress(widget.server.address).then((_connection) {
      connection = _connection;
      isConnecting = false;
      isDisconnecting = false;
      setState(() {});
      connection.input.listen(_onDataReceived).onDone((){
        if(isDisconnecting){
          print("Disconnecting locally");
        }else{
          print("Disconnecting remotely");
        }
        if(this.mounted){
          setState(() {});
        }
        Navigator.of(context).pop();
      });
    }).catchError((error) {
        Navigator.of(context).pop();
    });
  }

  void _onDataReceived(Uint8List data){

  }

//  @override
//  void dispose() {
//    WidgetsBinding.instance.removeObserver(this);
//    super.dispose();
//  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state.index == 0){
      //resume
      if(_bluetoothState.isEnabled){
        _listBondedDevices();
      }
    }
  }

  _getBTState() {

    FlutterBluetoothSerial.instance.state.then((state){
      _bluetoothState = state;
      if (_bluetoothState.isEnabled){
        _listBondedDevices();
      }
      setState(() {});
    });
  }

  _stateChangeListener(){
    FlutterBluetoothSerial.instance.onStateChanged().listen((BluetoothState state) {
      _bluetoothState = state;
      if (_bluetoothState.isEnabled){
        _listBondedDevices();
      }else{
        devices.clear();
      }
      print("State isEnabled: $state");
    });
  }

  _listBondedDevices(){
    FlutterBluetoothSerial.instance.getBondedDevices().then((List<BluetoothDevice> bondedDevices){
      devices = bondedDevices;
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[850],
      appBar: AppBar(
        title: Text("Wybierz urządzenie bluetooth"),
        backgroundColor: Colors.grey[900],
      ),
      body: Container(
        child: Column(
          children: <Widget>[
            SwitchListTile(
              activeColor: Colors.amber[700],
              title: Text("Włącz Bluetooth",
              style: TextStyle(
                color: Colors.white,
              ),),
              value: _bluetoothState.isEnabled,
              onChanged: (bool value){
                future() async {
                  if (value) {
                    await FlutterBluetoothSerial.instance.requestEnable();
                    } else {
                    await FlutterBluetoothSerial.instance.requestDisable();
                  }
                  future().then((_) {
                    setState(() {});
                  });
                }
              },
            ),
            ListTile(
              title: Text("Status Bluetooth",
              style: TextStyle(
                color: Colors.white,
              ),),
              subtitle: Text(_bluetoothState.toString(),
                style: TextStyle(
                  color: Colors.white30,
                ),),
              trailing: RaisedButton(
                color: Colors.amber[700],
                  child: Text("Ustawienia"),
                onPressed: () {
                    FlutterBluetoothSerial.instance.openSettings();
                },
              ),
            ),
            Expanded(
              child: ListView(
                children: devices
                  .map((_device) => BluetoothDeviceListEntry(
                    device: _device,
                    enabled: true,
                    onTap: () {
                      print("Item");
                      _getBTConnection();
                      final snackBar = SnackBar(
                        content: (isConnecting
                            ? Text("Łączy się z ${widget.server.name}")
                            : isConnected
                            ? Text("Połączono z ${widget.server.name}")
                            : Text("Rozłączono z ${widget.server.name}")),
                      );
                      Scaffold.of(context).showSnackBar(snackBar);
                    },
                  ))
                  .toList(),
              )
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment] 2020-06-17 10:17
Hi @GinLegucki 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/edufolly/flutter_bluetooth_serial/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-17 10:17 UTC
