### ISSUE TITLE
Appbar actions doesn't respect the Appbar theme with Material3!

### ISSUE THREAD

**Issue by EhabSalah** [flutter/flutter#118377] opened 2023-01-12 10:00 UTC
#111339

**Comment by danagbemava-nc** [comment] 2023-01-12 10:21
Hi @EhabSalah  as reported in https://github.com/flutter/flutter/issues/111339#issuecomment-1243290674, this has already been fixed. I just confirmed that the fix is also available on the `beta` channel so it should be in the next `stable`. 

Since this has already been fixed, I'll be closing this issue. Thank you

**Closed by danagbemava-nc** 2023-01-12 10:21 UTC
Labels: in triage
