### ISSUE TITLE
Android Deep Linking Drops Additional Query Parameters

### ISSUE THREAD

**Issue by AristideVB** [flutter/flutter#134733] opened 2023-09-14 14:09 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing package issues](https://github.com/flutter/flutter/issues?q=is%3Aopen+is%3Aissue+label%3Apackage)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### What package does this bug report belong to?

go_router

### What target platforms are you seeing this bug on?

Android

### Have you already upgraded your packages?

Yes

### Dependency versions

<details><summary>pubspec.lock</summary>

```lock
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  boolean_selector:
    dependency: transitive
    description:
      name: boolean_selector
      sha256: "6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04a925763edad70e8443c99234dc3328f442e811f1d8fd1a72f1c8ad0f69a605"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.0"
  clock:
    dependency: transitive
    description:
      name: clock
      sha256: cb6d7f03e1de671e34607e909a7213e31d7752be4fb66a86d29fe1eb14bfb5cf
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: f092b211a4319e98e5ff58223576de6c2803db36221657b46c82574721240687
      url: "https://pub.dev"
    source: hosted
    version: "1.17.2"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      sha256: e35129dc44c9118cee2a5603506d823bab99c68393879edb440e0090d07586be
      url: "https://pub.dev"
    source: hosted
    version: "1.0.5"
  fake_async:
    dependency: transitive
    description:
      name: fake_async
      sha256: "511392330127add0b769b75a987850d136345d9227c6b94c96a04cf4a391bf78"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      sha256: a25a15ebbdfc33ab1cd26c63a6ee519df92338a9c10f122adda92938253bef04
      url: "https://pub.dev"
    source: hosted
    version: "2.0.3"
  flutter_test:
    dependency: "direct dev"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  go_router:
    dependency: "direct main"
    description:
      name: go_router
      sha256: "5668e6d3dbcb2d0dfa25f7567554b88c57e1e3f3c440b672b24d4a9477017d5b"
      url: "https://pub.dev"
    source: hosted
    version: "10.1.2"
  lints:
    dependency: transitive
    description:
      name: lints
      sha256: "0a217c6c989d21039f1498c3ed9f3ed71b354e69873f13a8dfc3c9fe76f1b452"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  logging:
    dependency: transitive
    description:
      name: logging
      sha256: "623a88c9594aa774443aa3eb2d41807a48486b5613e67599fb4c41c0ad47c340"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: "1803e76e6653768d64ed8ff2e1e67bea3ad4b923eb5c56a295c3e634bad5960e"
      url: "https://pub.dev"
    source: hosted
    version: "0.12.16"
  material_color_utilities:
    dependency: transitive
    description:
      name: material_color_utilities
      sha256: "9528f2f296073ff54cb9fee677df673ace1218163c3bc7628093e7eed5203d41"
      url: "https://pub.dev"
    source: hosted
    version: "0.5.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "3c74dbf8763d36539f114c799d8a2d87343b5067e9d796ca22b5eb8437090ee3"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.1"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "8829d8a55c13fc0e37127c29fedf290c102f4e40ae94ada574091fe0ff96c917"
      url: "https://pub.dev"
    source: hosted
    version: "1.8.3"
  sky_engine:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.99"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "53e943d4206a5e30df338fd4c6e7a077e02254531b138a15aec3bd143c1a8b3c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      sha256: c3c7d8edb15bee7f0f74debd4b9c5f3c2ea86766fe4178eb2a18eb30a0bdaed5
      url: "https://pub.dev"
    source: hosted
    version: "1.11.0"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      sha256: "83615bee9045c1d322bbbd1ba209b7a749c2cbcdcb3fdd1df8eb488b3279c1c8"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.1"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  test_api:
    dependency: transitive
    description:
      name: test_api
      sha256: "75760ffd7786fffdfb9597c35c5b27eaeec82be8edfb6d71d32651128ed7aab8"
      url: "https://pub.dev"
    source: hosted
    version: "0.6.0"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  web:
    dependency: transitive
    description:
      name: web
      sha256: dc8ccd225a2005c1be616fe02951e2e342092edf968cf0844220383757ef8f10
      url: "https://pub.dev"
    source: hosted
    version: "0.1.4-beta"
sdks:
  dart: ">=3.1.0 <4.0.0"
  flutter: ">=3.7.0"

```

</details>

### Steps to reproduce

Clone the minimal reproducible example Flutter app from https://github.com/AristideVB/uri_param_bug and run it on an Android device or emulator

Execute the following adb shell command:
```bash
adb shell am start -a android.intent.action.VIEW -d "uriParamBug://example/home?user=john&name=Doe"
```

### Expected results

Both `user` and `name` query parameters should be parsed correctly and available in the Flutter app.

`goRouterState.uri` should return the full URI with all query parameters, like `/home?user=john&name=Doe`

### Actual results

Only the first query parameter (user) is parsed and available in the Flutter app. Subsequent query parameters (name, etc.) are missing.

`goRouterState.uri` currently returns an incomplete URI, missing additional query parameters: `/home?user=john`

### Code sample

<details><summary>Code sample</summary>

```dart
final _router = GoRouter(
  routes: [
    GoRoute(
      path: '/',
      builder: (context, state) {
        return MyHomePage(
          uri: '',
          routeName: 'Initial',

        );
      },
      routes: [
        // adb shell am start -a android.intent.action.VIEW -d "uriParamBug://com.example.uriParamBug/home?user=john&name=Doe"
       GoRoute(
          path: 'home',
          name: 'home',
          builder: (context, state) {
            print(state.uri); //  /home?user=john
            return MyHomePage(
              uri: state.uri.toString(),
              routeName: 'Home',
            );
          },
        ),
      ],
    ),
  ],
);
```

</details>

### Screenshots or Videos

<details>
<summary>Screenshots / Video demonstration</summary>

<img src="https://github.com/flutter/flutter/assets/97469482/07d8ca5b-0e71-4094-86cc-83b9226be509" width="200">

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.4, on macOS 13.5.2 22G91 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.82.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by AristideVB** [comment] 2023-09-14 14:15
### Additional Information

I would like to clarify that this issue is not restricted to using `adb` shell commands for triggering deep links. The same problem occurs when a user clicks on a link configured with App Links to open the app using either `http` or `https` schemes.

In this real-world scenario, `goRouterState.uri` also returns incomplete URIs, missing additional query parameters.

**Comment by AristideVB** [comment] 2023-09-14 17:38
### Update on Issue and Debugging Steps

I was able to pinpoint that the issue originates from the native Android side, rather than the Flutter side. Below are the steps I took to debug and my findings.

<details>
  <summary>Debugging Code in MainActivity.kt</summary>

  \`\`\`kotlin
  // MainActivity.kt
  import android.content.Intent
  import android.util.Log
  import io.flutter.embedding.android.FlutterActivity

  class MainActivity: FlutterActivity() {
      override fun onNewIntent(intent: Intent?) {
          super.onNewIntent(intent)
          handleIntent(intent)
      }

      override fun onResume() {
          super.onResume()
          handleIntent(intent)
      }

      private fun handleIntent(intent: Intent?) {
          intent?.let {
              val action = it.action
              val data = it.data

              Log.d("MainActivity", "Action: $action, Data: $data")
          }
      }
  }
  \`\`\`

</details>

<details>
  <summary>Log Output</summary>

  \`\`\`
  2023-09-14 19:13:12.496 19336-19336 MainActivity            com.example.uri_param_bug            D  Action: android.intent.action.VIEW, Data: uriParamBug://example/home?user=john
  \`\`\`

</details>

**Solution:**
Replacing the `&` with its encoded equivalent `%26` solved the issue. It seems like the issue doesn't lie within Flutter or the `go_router` package but rather on the Android side of the code.

**Comment by huycozy** [comment] 2023-09-15 11:49
Hi @AristideVB 
I found that the correct adb command should be (added ' (simple quotes)), see [this](https://stackoverflow.com/questions/35645414/android-deep-linking-with-multiple-query-parameters).

```
adb shell 'am start -a android.intent.action.VIEW -d "uriParamBug://example/home?user=john&name=Doe"'
```
Maybe this is a limitation on Android that needs tricky handling as you did. Anyway, glad you found the cause and solved it. 

Closing as it's not Flutter issue.

**Comment by AristideVB** [comment] 2023-09-15 11:52
### Revised Update on Issue and Debugging Steps

After further investigation using my production app (which is configured with app links), it appears that the issue is actually on the Flutter side, not the native Android side.

#### Log Output
<details>
  <summary>Revised Log Output on Production App</summary>

\`\`\`
2023-09-15 13:29:03.550 13032-13032 MainActivity            production.app                  D  Action: android.intent.action.VIEW, Data: https://production.com/#/reset-password?code=hello&email=john
\`\`\`

</details>

#### Additional ADB Test
It is worth noting that while testing with \`adb\`, I initially encountered the same issue. However, it can be resolved by escaping the \`&\` symbol with \`\\\` in the command line, as suggested in this [StackOverflow post](https://stackoverflow.com/questions/35645414/android-deep-linking-with-multiple-query-parameters/35645448#35645448).

\`\`\`bash
adb shell am start -W -a android.intent.action.VIEW -d "myCustomScheme://myHost?key=category_parent_id\\\&value=92\\\&title=test" com.myApp.android
\`\`\`

#### Conclusion
Given these findings, the issue appears to be on the Flutter side of the application, not on the Android native side.
Since goRouteState.uri returns `/reset-password?code=hello&email=john`  @huycozy do you need me to configure a minimum repro sample configured with app links ? it is a bit tricky to do

**Comment by huycozy** [comment] 2023-09-18 14:59
I re-open the issue for further discussion. 

>While on the Flutter side goRouteState.uri returns /reset-password?code=hello&email=john

As I understand this is working properly on Flutter, right? Or are you mistyping the results between Android and Flutter?

>do you need me to configure a minimum repro sample configured with app links ? it is a bit tricky to do

If the issue still exists with App Links, please provide a minimal sample. And please confirm whether the issue also exists for Deep Links (as the issue title)

**Comment by AristideVB** [comment] 2023-09-18 15:26
Hello @huycozy  I've opened a new issue as I was not right on the root cause of this issue which was the hash in my URL https://github.com/flutter/flutter/issues/134933

**Comment by huycozy** [comment] 2023-09-19 05:16
I see, closing this issue in favor of new one.

**Closed by huycozy** 2023-09-19 05:16 UTC
Labels: in triage
