### ISSUE TITLE
RawScrollBarState doesn't gracefully handle having zero or multiple scroll positions attached to the controller

### ISSUE THREAD

**Issue by SimeonZV** [flutter/flutter#78487] opened 2021-03-17 23:53 UTC
I started observing many "Bad state: No element." errors in Crashlytics since I've deployed the app built with flutter 2.0.2 (after upgrading from 1.22.6)

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: No element. Error thrown Instance of 'ErrorDescription'.
       at _GrowableList.single(_GrowableList.java)
       at ScrollController.position(ScrollController.java:110)
       at RawScrollbarState._handleTrackTapDown(RawScrollbarState.java:1007)
       at TapGestureRecognizer.<fn>(TapGestureRecognizer.java:580)
       at GestureRecognizer.invokeCallback(GestureRecognizer.java:182)
       at TapGestureRecognizer.handleTapDown(TapGestureRecognizer.java:580)
       at BaseTapGestureRecognizer._checkDown(BaseTapGestureRecognizer.java:287)
       at BaseTapGestureRecognizer.didExceedDeadline(BaseTapGestureRecognizer.java:258)
       at PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent(PrimaryPointerGestureRecognizer.java:501)
       at PrimaryPointerGestureRecognizer.<fn>(PrimaryPointerGestureRecognizer.java:454)
       at _CustomZone.<fn>(_CustomZone.java)
       at TickerFuture.thunk(TickerFuture.java:407)
```

Unfortunately I can't reproduce it, but it's reported from many users and from many devices for Android.

P.S. I apologize for .java in stacktraces. I've already added a comment about it in  https://github.com/FirebaseExtended/flutterfire/issues/80

**Comment by darshankawar** [comment] 2021-03-18 09:39
@SimeonZV 
Without a reproducible use case, it'll be tough to identify the root-cause. Looking at the log above, can you try to explore more in the app where you are using scrolling and gestures. May be it occurs while you are trying to scroll a list fast ?

**Comment by SimeonZV** [comment] 2021-03-18 10:55
I fully understand that it's difficult to fix an issue without being able to reproduce it. But I really tried hard and didn't manage it. I use scrolling in many places and I believe I went through all of them with no luck.

The only place where I see exceptions is Crashlytics. And I can say that it started happening only in the latest release of my app that I deployed just 2 days ago built with flutter 2.0.2. I believe I only had changes related to upgrades of external libraries to make them compatible with flutter 2.0.2 without any significant changes in my code.

Anyway thanks for looking at it.

**Comment by SimeonZV** [comment] 2021-03-18 11:58
I can just add that the issue is not Android specific. Today I've got the first iOS error in Crashlytics

```
Non-fatal Exception: FlutterError
0  ???                            0x0 single (dart:core)
1  ???                            0x0 position + 110 (scroll_controller.dart:110)
2  ???                            0x0 _handleTrackTapDown + 1007 (scrollbar.dart:1007)
3  ???                            0x0 <fn> + 580 (tap.dart:580)
4  ???                            0x0 invokeCallback + 182 (recognizer.dart:182)
5  ???                            0x0 handleTapDown + 580 (tap.dart:580)
6  ???                            0x0 _checkDown + 287 (tap.dart:287)
7  ???                            0x0 didExceedDeadline + 258 (tap.dart:258)
8  ???                            0x0 didExceedDeadlineWithEvent + 501 (recognizer.dart:501)
9  ???                            0x0 <fn> + 454 (recognizer.dart:454)
```

**Comment by darshankawar** [comment] 2021-03-19 07:11
Keeping this issue open for further triage, since there's no reproducible use case to identify the root-cause.

**Comment by Hixie** [comment] 2021-03-23 22:58
This stack trace represents ScrollController.position being accessed when it is not registered with a Scrollable, after the use taps the track of a scroll bar.

Do you have any explicit scroll bar widgets?

**Comment by SimeonZV** [comment] 2021-03-24 17:37
Yes, we do use CupertinoScrollbar widget explicitly. And I've managed to reproduce it exactly in a way you described! The only thing is that a Scrollable child is always there.

**Comment by Piinks** [comment] 2021-03-25 17:02
Looking at #78486 and this, I am hoping https://github.com/flutter/flutter/pull/77107 can help provide better insight and guidance here.

@SimeonZV can you provide a minimal code sample of how you have your `CupertinoScrollbar` configured? I have noticed some common configuration issues lately, especially when `isAlwaysShown` is being used.

**Comment by SimeonZV** [comment] 2021-03-25 17:55
I've just provided the code in https://github.com/flutter/flutter/issues/78486#issuecomment-807183638

**Comment by Piinks** [comment] 2021-03-25 19:43
Awesome! Thank you! I am going to close this as a dupe per your comment above. Please follow up in the other issue. If this is not the same issue, let me know and we can reopen. :)

**Closed by Piinks** 2021-03-25 19:43 UTC
Labels: a: production, f: material design, framework, passed first triage, severe: crash

**Comment by SimeonZV** [comment] 2021-03-25 20:52
Well, so far I didn't manage to reproduce this issue. I only believe that they are related because @Hixie mentioned that this issue may happen in the scenario https://github.com/flutter/flutter/issues/78487#issuecomment-805323013 that triggered reproduction of the other one :)

**Comment by Piinks** [comment] 2021-03-25 21:01
> Well, so far I didn't manage to reproduce this issue. I only believe that they are related because @Hixie mentioned that this issue may happen in the scenario [#78487 (comment)](https://github.com/flutter/flutter/issues/78487#issuecomment-805323013) that triggered reproduction of the other one :)

Ok! If you are able to reproduce this as a separate issue, just let us know! :)
