### ISSUE TITLE
url_launcher does not work for flutter web

### ISSUE THREAD

**Issue by c-p-i-o** [flutter/flutter#44012] opened 2019-11-01 20:48 UTC
I was working on a package 
https://pub.dev/packages/oauth2
This `oauth2` package is marked *web* on pub.dev
However, this package uses url_launcher, and url_launcher does not work with *web*
If you look at the oauth2 package and attempt to run the example via 
*flutter run -d chrome*,
You'll see that the code hangs in the `canLaunch(url)` code in lib/oauth.dart
```
    if (await canLaunch(url)) {
      await launch(url);
    } else {
      throw 'Could not launch $url';
    }
  }
```
The function never returns.

**Comment by jmagman** [comment] 2019-11-02 01:02
Not sure if this is https://github.com/flutter/flutter/issues/33126 since that has like no information about what "can't use" means.

**Comment by c-p-i-o** [comment] 2019-11-04 17:42
Thanks @jmagman.  Yes this issue definitely seems related. I'm more concerned that the `oauth2` package is tagged with *web* on pub.dev and it simply won't work without modifications to it.  I was able to make the `oauth2` package work by not using `url_launcher` package in the code that I pointed out above.

**Comment by CaseyHillers** [comment] 2019-11-05 00:36
To follow up, I am experiencing this issue too with the latest version of the plugin (v5.2.5). The plugin works with v5.2.4 for me. Possibly related to https://github.com/flutter/plugins/pull/2232

Error:
```
Overflow on channel: flutter/platform.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel

Uncaught MissingPluginException(No implementation found for method launch on channel plugins.flutter.io/url_launcher)
    at Object.c (https://flutter-dashboard.appspot.com/v2/main.dart.js:1690:3)
    at https://flutter-dashboard.appspot.com/v2/main.dart.js:34043:20
    at SC.a (https://flutter-dashboard.appspot.com/v2/main.dart.js:2561:71)
    at SC.$2 (https://flutter-dashboard.appspot.com/v2/main.dart.js:18702:23)
    at S0.$1 (https://flutter-dashboard.appspot.com/v2/main.dart.js:18694:30)
    at Qt.tj (https://flutter-dashboard.appspot.com/v2/main.dart.js:19646:40)
    at Qt.ja (https://flutter-dashboard.appspot.com/v2/main.dart.js:19648:30)
    at OE.$0 (https://flutter-dashboard.appspot.com/v2/main.dart.js:19049:13)
    at Object.jy (https://flutter-dashboard.appspot.com/v2/main.dart.js:2678:41)
    at N.jz (https://flutter-dashboard.appspot.com/v2/main.dart.js:18965:3)
```

**Comment by hterkelsen** [comment] 2019-11-08 01:32
@c-p-i-o Try the instructions here to enable `url_launcher` for the web: https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_web

**Comment by c-p-i-o** [comment] 2019-11-12 17:53
Thanks @hterkelsen for the suggestion.  
I don't directly use `url_launcher`.  I was hoping to use `oauth2` package - which in turn uses `url_launcher`.  I attempted to do the following by adding a direct `url_launcher_web` dependency in my `pubspec.yaml` but it didn't work:

```
  oauth2: ^1.4.0
  url_launcher: ^5.2.5
  url_launcher_web:
    git:
      url: git://github.com/flutter/plugins.git
      path: packages/url_launcher/url_launcher_web  
```
Perhaps I'm doing something wrong?  I'll keep on trying to see if I can get this to work.

**Comment by hterkelsen** [comment] 2019-11-20 22:30
Closing as a duplicate of https://github.com/flutter/flutter/issues/33126

**Closed by hterkelsen** 2019-11-20 22:30 UTC
Labels: p: url_launcher, plugin, ☸ platform-web
