### ISSUE TITLE
Feature Request : Modify DropdownMenu to extend TextFormField to add validation

### ISSUE THREAD

**Issue by TRAINEE-ECFILE** [flutter/flutter#155390] opened 2024-09-19 05:42 UTC
### Use case

Currently the built-in Dropdown Menu widget is extending TextFeild class which doesn't support validation . I would i nice to have validation since i use this widget a lot and its good to have

### Proposal

  final Widget textField = TextFormField(
            key: _anchorKey,
            mouseCursor: effectiveMouseCursor,
            canRequestFocus: canRequestFocus(),
            enableInteractiveSelection: canRequestFocus(),
            textAlignVertical: TextAlignVertical.center,
            validator: widget.validator,
            style: effectiveTextStyle,
            controller: _textEditingController,
            
            i have modified the widget to extend TextFormField which supports validation

**Comment by awazgyawali** [comment] 2024-09-19 06:15
Have you tried https://api.flutter.dev/flutter/material/DropdownButtonFormField-class.html?

**Comment by danagbemava-nc** [comment] 2024-09-19 08:09
Closing this as a duplicate of https://github.com/flutter/flutter/issues/152131

**Closed by danagbemava-nc** 2024-09-19 08:09 UTC
Labels: in triage

**Comment by TRAINEE-ECFILE** [comment] 2024-09-20 04:14
yes i have tried it . it doesnt have the type to filter or search
functionality . so when you have a long list of suggestions its makes sense
to use the autocomplete widget where you can type to filter out the
suggestions. So my request is still a valid one
