### ISSUE TITLE
Green tree check for flutter/plugins considers in-progress runs green

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#83009] opened 2021-05-20 11:50 UTC
The flutter/plugins tree has been red for the past day or so, and we've been landing PRs to fix aspects of the redness. Every time we do, everything with the "waiting for tree to go green" label is landed even though the last completed run was red, and the new run hadn't greened those failing checks (and in fact, they were in several cases still red on completion due to compounded errors).

**Comment by godofredoc** [comment] 2021-06-03 22:19
@stuartmorgan were the failures on Cirrus or LUCI?

**Comment by stuartmorgan** [comment] 2021-06-03 22:59
I'm sure I've seen it with Cirrus, since that's where essentially all the plugin tests are. I'm not sure if it happens with LUCI.

**Comment by godofredoc** [comment] 2021-06-03 23:54
Is there a PR that I can use to validate the "waiting for tree to go green workflow"?

**Comment by stuartmorgan** [comment] 2021-06-04 03:34
You could put it on https://github.com/flutter/plugins/pull/4009. The tree isn't red though, so it'll land immediately.

(I suspect, but haven't validated, that the `submit-queue` check would show the wrong status in this case, and that the problem is with that check rather than the waiting label logic itself.)

**Comment by stuartmorgan** [comment] 2021-06-16 20:15
Just saw this happen with the following Cirrus postsubmit tests all still in progress, with the previous run being red:
```
build-apks+java-test+firebase-test-lab CHANNEL:master PLUGIN_SHARDING:--shardIndex 0 --shardCount 4 In progress — This check has started...
build-apks+java-test+firebase-test-lab CHANNEL:master PLUGIN_SHARDING:--shardIndex 1 --shardCount 4 In progress — This check has started...
build-web+drive-examples CHANNEL:master In progress — This check has started...
build-web+drive-examples CHANNEL:stable In progress — This check has started...
test CHANNEL:master In progress — This check has started...
```

I verified that in open PRs, the `submit-queue` check was incorrectly showing green.

**Comment by godofredoc** [comment] 2021-06-16 20:21
We don't own the submit-queue check, we can either ask @fkorotkov to take a look or migrate to a check from cocoon backend.

**Comment by godofredoc** [comment] 2022-01-12 01:34
This is a blocker for enabling the auto-submit validation in plugins and packages.

**Comment by ditman** [comment] 2022-09-07 23:48
I think this one is resolved. Autosubmit seems to be working as intended. What do you think @stuartmorgan ?

**Comment by stuartmorgan** [comment] 2022-09-08 00:13
I haven't seen a specific test case for this recently, so I'm not sure whether it's still happening or not.

Next time the tree is broken we can try to recreate the problem (by putting autosubmit on something else and then landing the tree fix) and see what happens.

**Comment by godofredoc** [comment] 2022-09-08 00:15
I believe this was fixed by either @keyonghan or @ricardoamador

**Comment by godofredoc** [comment] 2022-11-16 20:50
Duplicate of https://github.com/flutter/flutter/issues/106209

**Closed by godofredoc** 2022-11-16 20:50 UTC
Labels: team: infra, passed secondary triage
