### ISSUE TITLE
navigationDelegate android webview not working

### ISSUE THREAD

**Issue by hungnv1709** [flutter/flutter#82674] opened 2021-05-17 05:36 UTC
i am using webview_flutter: ^2.0.3 on my app.
When i use method "navigationDelegate" to check url contain something. Its work on IOS, but not on android. 

<details> 
<summary>code snippet</summary> 

```dart
WebView(
                              initialUrl: url,
                              javascriptMode: JavascriptMode.unrestricted,
                              gestureNavigationEnabled: true,
                              onWebViewCreated:
                                  (WebViewController webViewController) {
                                _controller = webViewController;
                                if (url != null) {
                                  _controller.loadUrl(url);
                                }
                              },
                              onProgress: (int progress) {
                                print(
                                    "WebView is loading (progress : $progress%)");
                              },
                              javascriptChannels: <JavascriptChannel>{},
                              navigationDelegate:
                                  (NavigationRequest request) {
                                if (request.url == null) {
                                  print('blocking navigation to $request');
                                  return NavigationDecision.prevent;
                                }
                                if (request.url.contains('success')) {
                                  print('payment complete');
                                  Get.toNamed('/purchase_result', arguments: true);
                                }
                                if (request.url.contains('failure') || request.url.contains('incomplete')) {
                                  print('payment complete');
                                  Get.toNamed('/purchase_result', arguments: false);
                                }
                                print('allowing navigation to $request');
                                return NavigationDecision.navigate;
                              },
                              onPageStarted: (String url) {
                                print('Page started loading: $url');
                              },
                              onPageFinished: (_) {
                                controller.readJS(_controller);
                              },
                            )
```

</details>
<details> 
<summary>flutter doctor</summary> 
	
```console

[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15 19A583 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.2.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.2 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

</details>

**Comment by SarthakVaswani** [comment] 2021-05-17 10:41
Its working fine for me

**Comment by TahaTesser** [comment] 2021-05-17 14:56
Hi @hungnv1709 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/39441
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-17 14:56 UTC
Labels: in triage
