### ISSUE TITLE
Checkbox animation renders incorrectly

### ISSUE THREAD

**Issue by lukef** [flutter/flutter#9935] opened 2017-05-09 21:40 UTC
The checkbox animation on Android renders incorrectly. I assume that this is meant to be an ink transition?

See attached video (slow animations turned on): 
[checkbox-anim-issue.zip](https://github.com/flutter/flutter/files/988093/checkbox-anim-issue.zip)

**Comment by eseidelGoogle** [comment] 2017-05-09 21:42
Here is a YT version: https://youtu.be/oRG66HTp_kY

**Comment by lukef** [comment] 2017-05-09 21:42
See this image (from [here](https://material.io/guidelines/components/selection-controls.html#selection-controls-switch)) for splash specification.

![components_switches_check3](https://cloud.githubusercontent.com/assets/37941/25874060/b66af880-34c5-11e7-8541-e3386271e020.png)

**Comment by eseidelGoogle** [comment] 2017-05-09 21:43
@chinmaygarde this looks like a skia bug?

**Comment by Hixie** [comment] 2017-05-09 21:43
Woah. That's new.

**Comment by eseidelGoogle** [comment] 2017-05-09 21:45
This is another argument for us needing some sort of visual correctness testing.  This should be possible to test with our internal system FYI @tvolkert, but we also need something to catch this kind of bug in our engine testing, e.g. https://github.com/flutter/flutter/issues/3227

**Comment by tvolkert** [comment] 2017-05-09 21:49
Now that @abarth fixed #6774, we're not too far from being able to do image capture during host-based (`flutter_tester`) tests.  Then all that's missing is an image diffing library wired up to `package:test`

**Comment by chinmaygarde** [comment] 2017-05-09 22:08
I am not able to reproduce this on ToT that includes a Skia roll.

**Comment by eseidelGoogle** [comment] 2017-05-10 17:28
We have not yet rolled the engine since.  However we expect to in the coming day(s) at which point we should be able to verify that this bug is fixed.  `alpha` will not be updated for a couple weeks however.

**Comment by eseidelGoogle** [comment] 2017-05-10 17:44
@lukef notes that this only occurred for him on Android, both device and Emulator (with GPU enabled)

**Comment by Hixie** [comment] 2017-05-10 19:25
Status: We believe this will be resolved on master soon, with a roll of the engine today. We are not expecting to roll this into alpha in the next week.

**Comment by chinmaygarde** [comment] 2017-05-11 18:52
The engine roll was completed. Can we close this?

**Comment by Hixie** [comment] 2017-05-17 21:34
I'm closing this on the basis that as far as we know it is fixed. Please reopen if you still see it.

**Closed by Hixie** 2017-05-17 21:34 UTC
Labels: customer: posse (eap), dependency: skia, prod: material design, regression, waiting for PR to land (fixed)
