### ISSUE TITLE
Dart2 Flutter Test slow to start (dart2)

### ISSUE THREAD

**Issue by brianegan** [flutter/flutter#15767] opened 2018-03-20 22:04 UTC
Hey there! I've been noticing an interesting problem as I upgrade my libs to Dart 2. I run my tests very often, and have seen them take far longer to start up than in Dart 1. If you're running many iterations of a test trying to fix a bug, it can feel a bit sluggish compared to how fast it was before.

## Steps to Reproduce

  1. Create a new Flutter project
  2. Enter project
  3. Run `flutter test` from command line
  4. Tests take 5-6 seconds to run
  5. Compare to Dart1, which was 1-2 seconds

### Dart 1

```
gunter lab/slow_tests »  time flutter test                                                                  
00:01 +1: All tests passed!                                                                                      
flutter test  2.02s user 0.36s system 111% cpu 2.125 total
gunter lab/slow_tests » time flutter test
00:01 +1: All tests passed!                                                                                      
flutter test  2.01s user 0.35s system 112% cpu 2.104 total
gunter lab/slow_tests » time flutter test
00:01 +1: All tests passed!                                                                                      
flutter test  2.02s user 0.36s system 112% cpu 2.115 total
```

### Dart 2

```
gunter lab/slow_tests » time flutter test --preview-dart-2
00:04 +1: All tests passed!                                                                                      
flutter test --preview-dart-2  6.19s user 0.70s system 134% cpu 5.134 total
gunter lab/slow_tests » time flutter test --preview-dart-2
00:04 +1: All tests passed!                                                                                      
flutter test --preview-dart-2  6.26s user 0.68s system 134% cpu 5.163 total
gunter lab/slow_tests » time flutter test --preview-dart-2
00:04 +1: All tests passed!                                                                                      
flutter test --preview-dart-2  6.32s user 0.69s system 134% cpu 5.234 total
```

## Flutter Doctor

```dart
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-US)
    • Flutter version 0.1.5 at /Users/phillywiggins/lab/flutter
    • Framework revision 3ea4d06340 (4 weeks ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.2)
    • Android SDK at /Users/phillywiggins/Library/Android/sdk
    • Android NDK at /Users/phillywiggins/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.2
    • ANDROID_HOME = /Users/phillywiggins/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Community Edition (version 2017.3.5)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[✓] VS Code (version 1.21.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Dart Code extension version 2.8.2

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
```

**Comment by Hixie** [comment] 2018-03-20 23:30
cc @a-siva

**Comment by mraleph** [comment] 2018-03-21 10:51
@jensjoha will be looking into this as part of his work.

**Comment by brianegan** [comment] 2018-03-21 10:56
Thanks for the help everyone :)

**Comment by xster** [comment] 2018-06-02 04:50
any updates on this one? I'd like to demo widget testing using Flutter at a conference but the speed might give a bad impression.

**Comment by mraleph** [comment] 2018-06-05 08:39
@xster no updates, unfortunately most of the resources are consumed by Dart 2 release at the moment. Addressing this however is at the top of our list.

**Comment by AweiLoveAndroid** [comment] 2018-06-09 03:28
I have find the problems too.

One win7 System computer:

`console`  screenshots:

it runs for 5 minutes,and it's too slow   and the log is too much more.


![](https://github.com/AweiLoveAndroid/Flutter-learning/blob/master/pics/Run%20Console1.png?raw=true)

----

But another win7 System computer:

`console`  screenshots like this:

look, it's very succinct,it runs for 1 minutes

![](https://github.com/AweiLoveAndroid/Flutter-learning/blob/master/pics/Run%20Console2.png?raw=true)

**Comment by mraleph** [comment] 2018-06-09 06:18
@AweiLoveAndroid if you are experiencing slow builds it's a different issue. please file a different issue for that. this issue is purely about `flutter test` performance.

**Comment by twistedinferno** [comment] 2018-09-05 16:30
Is there an update for this?  I write and run unit tests for the majority of my code so this is having a substantial impact on my development.  For non flutter tests (ie self contained classes that could run as a dart console app), could we run them outside of the flutter test (ie just use the dart test package)?  I noticed that the test dart package supports running them in node...

https://pub.dartlang.org/packages/test#running-tests-on-nodejs

...would this be a good short term fix?

**Comment by mraleph** [comment] 2018-09-05 16:48
@jensjoha has just landed #20414 which should cut some of the cost down. Can you try updating to master and see what it does for you?

**Comment by twistedinferno** [comment] 2018-09-06 09:36
Hi, I've updated to master and I've run a very basic test (the project has a yaml file with the test pub dependency and one test), it says it takes 5seconds but from pressing return in the console to getting a result back it's taking 7 seconds.  In my opinion / experience this is still too long to wait to do proper TDD dev (in c# a simple test returns results in less than a second, javascript too).  In my proper flutter app with more dependencies tests take around 7 seconds also.  

I went back to the beta channel but it has now gone to 7.3?  So I couldn't compare this to the previous timings, maybe there is improvement but it still feels way to sluggish.

_If anyone can try running the dart tests in node.js and let me know if its worth looking at that as a quick fix I would be greatly appreciative._

**Comment by jensjoha** [comment] 2018-09-06 09:39
The change @mraleph mentioned does not really have any effect the first time you run the test.
If you try to update to master again, and run `flutter test` twice (or more) the subsequent runs should be faster.

So maybe 5 seconds the first time, 2 seconds the second time.

**Comment by twistedinferno** [comment] 2018-09-06 10:28
I went back to beta 7.3 and the simple test takes 7 seconds but the test in the larger project takes about 14 seconds.

in master 7.6-pre.57 running the simple tests also takes 7 seconds but the test in the larger project it also seems to take between 10 and 14 seconds...it still seems slow.

I ran tests multiple times and the code being tested is pretty simple.

**Comment by jensjoha** [comment] 2018-09-06 10:35
Hmm...

```
$ flutter create issue15767
Creating project issue15767...
  issue15767/android/.gitignore (created)
[...]
  issue15767/ios/Runner/AppDelegate.m (created)
Running "flutter packages get" in issue15767...              7.6s
Wrote 65 files.
[...]

$ cd issue15767/
/issue15767$ flutter test
00:05 +0: loading /usr/local/google/home/jensj/code/nobackup/flutter/tmp/flutter_15767/issue15767/test/widget_test.dart                                                                      Shell: Do not know weight for: TeXGyreSchola (BoldItalic) 
00:06 +1: All tests passed!                                                                                                                                                                  

/issue15767$ flutter test
00:01 +0: loading /usr/local/google/home/jensj/code/nobackup/flutter/tmp/flutter_15767/issue15767/test/widget_test.dart                                                                      Shell: Do not know weight for: TeXGyreSchola (BoldItalic) 
00:02 +1: All tests passed!                                                                                                                                                                  
```

Could you perhaps share the simple tests you're refering to?

**Comment by twistedinferno** [comment] 2018-09-06 10:53
...sure (hope I'm not doing anything stupid!)

Video
https://drive.google.com/file/d/1JclqqOFaff172YWA60RTHXxRP9uMaTOW/view

Gist of test & yaml
https://gist.github.com/twistedinferno/bc005a192014b919ffd3133e380d3fc5
https://gist.github.com/twistedinferno/fa7570a1e6f2d27b1ea2a21a71ad1a69

**Comment by jensjoha** [comment] 2018-09-06 11:10
Thank you.

Initial thoughts:

a) When I run this (on Linux, though VSCode with the `Dart Code` plugin) this doesn't use flutter at all. On my machine the command run is something like `[wherever/path/to]/flutter/bin/cache/dart-sdk/bin/dart testingTest.dart --name "^String\.split\(\) splits the string on the delimiter"`. (So it does use dart from within flutter, but not actually flutter itself). For this scenario the opimitzation in https://github.com/flutter/flutter/pull/20414 doesn't go into effect at all (and it shouldn't really have to because the dependencies are much, much smaller).

b) On my machine its much faster. If I from the (linux) command line prepend "time" it tells me `real	0m1.108s` (i.e. it took ~1.1 seconds). While that is probably also too slow, its nowhere near what you're seeing.

Are you using the `Dart Code` plugin, or the specific flutter version or something else? 
I noticed that you have your phone attached. Does the timing change if you unplug it first?

**Comment by twistedinferno** [comment] 2018-09-06 11:16
Hi, I'm using the Dart Code plugin 2.18.0, that is my only plugin actually
![image](https://user-images.githubusercontent.com/4139336/45154138-6f17a500-b1ce-11e8-9709-a33df7f0e886.png)

unplugging the phone doesn't make any difference unfortunately.

_I would be happy with 1.1seconds :-)_

**Comment by DanTup** [comment] 2018-09-06 11:17
> When I run this (on Linux, though VSCode with the Dart Code plugin) this doesn't use flutter at all. 

If running through the editor, this depends on whether we detect you have a Flutter project open. If we do, we'll run with `flutter test` and if not, we'll run with `pub run test`. The easiest way to tell exactly what's running is by running the `Dart: Capture Logs` command and ticking `Flutter Test` and `Pub Test`, run the test, then hit Stop Logging and it'll show the exact command/switches being used.

> (So it does use dart from within flutter, but not actually flutter itself)

This should only happen if that's the Dart you have on `PATH` or in `dart.sdkPath`. Generally we prefer using a standard Dart SDK when running Dart projects and the Flutter one for Flutter.

Of course, if you run commands from inside the terminal in Code (like in the screenshot above) it'll just run that with whatever is on `PATH` (type `which pub` to see which) and doesn't interact with the extension at all.

**Comment by twistedinferno** [comment] 2018-09-06 11:27
Here is a log file of my test (this is my simple test but run in a flutter app)

https://drive.google.com/open?id=1cct-IX8acKvRxTMRrVkN_x8ogWseHOF6

_I couldn't see where to write the `which pub `command, directly in the terminal?  (it says it can't find a command called `which`!)_

**Comment by DanTup** [comment] 2018-09-06 11:33
The log shows that these tests are being run with Flutter (0.7.6-pre.57):

```
[12:21:52 GMT+0100 (GMT Daylight Time)] [FlutterTest] [Info] Spawning c:\Flutter\flutter\bin\flutter.bat with args ["test","--machine","--name","^String\\.split\\(\\) splits the string on the delimiter$","test\\testing_test.dart"]
[12:21:52 GMT+0100 (GMT Daylight Time)] [FlutterTest] [Info] ..  in C:\Dev\flutter\examples\test_testing
```

The test runner is reporting 4.6 seconds:

```
{"success":true,"type":"done","time":4662}
```

However there will be some extra on there for stuff in the VS Code and Flutter (the time reported is only the part inside package test).

**Comment by twistedinferno** [comment] 2018-09-06 11:48
Log file where it uses Dart _(I think!)_

https://drive.google.com/open?id=1cct-IX8acKvRxTMRrVkN_x8ogWseHOF6

The UI here says 0:00 seconds but my stopwatch says 7 seconds again.  Couldn't see a time property in the log file.
![image](https://user-images.githubusercontent.com/4139336/45155511-29a9a680-b1d3-11e8-9604-af35b64ef6c9.png)

**Comment by jensjoha** [comment] 2018-09-06 11:54
(I'm currently trying to get VSCode and Dart Code to work on my Windows machine --- so far without luck)

**Comment by DanTup** [comment] 2018-09-06 11:58
@jensjoha What problem(s) are you having? You can ping me in Gitter (https://gitter.im/dart-code/Dart-Code) or Hangouts (dantup @ google) if you get stuck. It should be as simple as installing the Dart extension and ensuring flutter is in your `PATH` (or if it doesn't find it, for ex. if you set `PATH` in a terminal startup script where VS Code won't get it, you can click the `Locate SDK` button on the error message and manually point at the folder).

**Comment by jensjoha** [comment] 2018-09-06 12:15
So I forgot the pubspec update...
@twistedinferno : It seems you now have a different config than the video and gists you gave earlier (e.g. the test file is now inside a "test" directory etc).
Nonetheless, on my Windows machine, with ~the same config as in the video and on my Linux machine it does indeed go much slower... 
It took ~1 second on my Linux machine, but takes ~3.5 seconds on my Windows machine...

I think this warrents further investigation...
@mraleph do you have any insights/ideas here?

**Comment by twistedinferno** [comment] 2018-09-06 12:52
many thanks for investigating @jensjoha, good to know you can recreate it.  btw, the second log I think is the same config as in the video (I was testing a few things out)

**Comment by jensjoha** [comment] 2018-09-06 12:56
For good measure, could you try to open a command line and time
`c:\\Flutter\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe C:\\Dev\\flutter\\examples\\test_testing\\test\\testing_test.dart` with your stopwatch?

As well as creating a file `hello.dart` with content
```
main() {
  print("Hello, World!");
}
```
and from a command line then run and time
`c:\\Flutter\\flutter\\bin\\cache\\dart-sdk\\bin\\dart.exe hello.dart` with your stopwatch?

Thanks!

**Comment by jensjoha** [comment] 2018-09-06 13:27
Thank you. I'll try to investigate as time allows.

**Comment by jensjoha** [comment] 2018-09-07 13:26
I found something. Fixing it turns the needle on my Windows machine from ~3.3 seconds on "testingTest.dart" to ~1.3 seconds. For "hello.dart" it goes from ~0.8 seconds to ~0.3 seconds.

Nothing has landed in the dart-sdk yet though.

**Comment by rrousselGit** [comment] 2018-09-07 16:16
Not sure if this helps, but with AngularDart I face a similar issue. 
Tests themselves are relatively fast. But there's a 5-7 seconds delay before they are started, without any log in the console.

**Comment by jensjoha** [comment] 2018-09-10 11:07
> I found something. Fixing it turns the needle on my Windows machine from ~3.3 seconds on "testingTest.dart" to ~1.3 seconds. For "hello.dart" it goes from ~0.8 seconds to ~0.3 seconds.
> 
> Nothing has landed in the dart-sdk yet though.

It has landed and should have rolled into flutter. @twistedinferno could you (on flutter master) do a `flutter upgrade` and perform your measurements again?

**Comment by brianegan** [comment] 2018-09-11 15:46
Hi @jensjoha -- Thanks for helping out :) I've just run the test comparing the beta branch to the master branch and wanted to share my results. This is on the same project originally referenced in this issue. 

Summary: First run is slower than first reported (~8 seconds compared to ~6 when I first created the issue), subsequent runs are a now faster than before, but still about 2-3x slower than the Dart 1 measurements I recorded, and is still the speed I'd love to see again if possible.

Here are my results:

## Beta

```
GIR lab/test_speed_test » flutter --version
Flutter 0.6.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 9299c02cf7 (4 weeks ago) • 2018-08-16 00:35:12 +0200
Engine • revision e3687f70c7
Tools • Dart 2.1.0-dev.0.0.flutter-be6309690f
GIR lab/slow_tests » time flutter test
00:05 +1: All tests passed!
flutter test  8.00s user 0.78s system 135% cpu 6.493 total
GIR lab/slow_tests » time flutter test
00:05 +1: All tests passed!
flutter test  7.97s user 0.77s system 135% cpu 6.457 total
GIR lab/slow_tests » time flutter test
00:05 +1: All tests passed!
flutter test  8.00s user 0.79s system 134% cpu 6.522 total
GIR lab/slow_tests »
```

```
GIR lab/slow_tests » flutter --version
Flutter 0.8.3-pre.25 • channel master • https://github.com/flutter/flutter.git
Framework • revision fa0a857d02 (13 minutes ago) • 2018-09-11 08:27:32 -0700
Engine • revision e65beb89da
Tools • Dart 2.1.0-dev.4.0.flutter-ef72098353
GIR lab/slow_tests » time flutter test
00:05 +1: All tests passed!
flutter test  8.69s user 0.86s system 140% cpu 6.799 total
GIR lab/slow_tests » time flutter test
00:02 +1: All tests passed!
flutter test  4.44s user 0.75s system 127% cpu 4.058 total
GIR lab/slow_tests » time flutter test
00:02 +1: All tests passed!
flutter test  4.38s user 0.74s system 127% cpu 4.015 total
GIR lab/slow_tests »
```

**Comment by twistedinferno** [comment] 2018-09-17 08:08
Hi @jensjoha, thanks for looking into this, however, I can't see an improvement

I have updated to the latest master version (0.8.5-pre.7)

2.4s hello.dart
6.6s testing_test.dart
and 10s for a test in my actual application

_Apologies for the delay in responding, I was away and missed your notification from the thread_

**Comment by keertip** [comment] 2018-09-19 22:11
@jensjoha, what is the commit hash for your fix?

**Comment by jensjoha** [comment] 2018-09-20 09:00
@twistedinferno :( Can you give the command you're actually running so I can make sure I'm attempting the same thing as you?
@keertip https://github.com/dart-lang/sdk/commit/1e4b3e97540493dc179cf261508da2f729c0b379

**Comment by jensjoha** [comment] 2018-09-21 11:33
@twistedinferno : The bat script specifically just says `dart` meaning you're using the `dart` on your path, i.e. not the one from within flutter which is (probably?) newer (and includes the fix I talked about at https://github.com/flutter/flutter/issues/15767#issuecomment-419438642

**Comment by twistedinferno** [comment] 2018-09-21 11:41
my bad!  Apologies, this is indeed faster

**Comment by jensjoha** [comment] 2018-09-21 11:54
Good to hear - how long does stuff take now?

**Comment by twistedinferno** [comment] 2018-09-21 11:57
The hello.dart takes .5s (this is great)
testing_test.dart takes 2.2s (this is ok too, I would like it to be less than a second but hey...2x speed improvement...I can wait for the next)
I'll just test my real world app now

however, if I run `flutter test` in the console or press the test link in VSCode this takes 7s with just the one _test.dart file in test folder, is that expected?  I would have expected that to be taking the same time as the flutter\bin\cache\dart.exe

https://drive.google.com/open?id=1GIVaurrdJqSUrDzbFls_3MJpful7d0xE

**Comment by jensjoha** [comment] 2018-09-21 12:17
Well.. I at least is getting this:
```
>flutter test
00:05 +1: All tests passed!

>flutter test
00:03 +1: All tests passed!

>flutter test
00:02 +1: All tests passed!

>flutter test
00:02 +1: All tests passed!

>flutter test
00:02 +1: All tests passed!
```
(in practise the "2 seconds" is more like 4.6 seconds though --- but still better than the initially reported 5 seconds (actually more like ~9 seconds))

As to why it's that much slower... I don't know, but I'll try to investigate.

**Comment by twistedinferno** [comment] 2018-09-21 12:38
That's great, thanks for looking into this.  Yes, if you can find out why `flutter test` is still slow that would be great (I think I need `flutter test` to work unless my tests are testing pure dart code, I get a `not found dart:ui` error when testing flutter code using dart.exe...which I'm not sure I undersand)

**Comment by jensjoha** [comment] 2018-09-21 12:55
Yeah, for actual flutter tests you need to run `flutter test`.

So I have an explanation:
 - When you say `flutter` it runs a batch script (on Windows, a shell script on Linux), which - at least on my Windows machine - takes ~0.5 seconds.
 - When saying `flutter test` it creates a wrapper script that imports all kinds of stuff (which explains why the cached file in `build` becomes so big (16 MB big!)). If I turn the test file into a file with just an empty main file (no imports or anything) the file produced is still 16 MB and contains all kinds of stuff.
   - among the contained things are 354 libraries from `package:flutter`.

So despite you're test not really having anything to do with flutter, flutter is included, i.e. on the first run (no cache) the flutter package (among other stuff) is compiled, serialized and loaded by the dart VM; on subsequent runs (with cache) it is deserialized, serialized and loaded by the VM.

Unfortunately this is not going away today. Hopefully with time, though, we can do better.

**Comment by twistedinferno** [comment] 2018-09-21 13:18
ok, so it is much faster for pure dart tests but still 9s for my flutter real app flutter tests.  Thanks for your updates and help...it feels like it is possible to do TDD in dart 2 now (maybe some more improvements in the future) but I still don't feel it's possible to do real TDD in Flutter.

**Comment by jensjoha** [comment] 2018-09-24 08:56
@twistedinferno I understand your frustration. I plan to look more into this. How fast do you feel would be 'fast enough for TDD'?

**Comment by brianegan** [comment] 2018-09-24 09:47
@jensjoha Just my two cents, but I'd love to see this get back down into the 1-2 second range again as it was in Dart 1 (the entire time it takes to launch the tests and get feedback -- what I've been measuring in my reports).

At that speed, I can make a change, run the test, and verify quickly whether it works or not then keep going. I think of it in similar terms to Hot Reload -- I would like to be able to maintain "Flow" and not lose focus while quickly iterating on tests / the code that I'm verifying.

Currently, I find myself writing groups of tests and running them in batches far more often b/c repeatedly waiting 8-9 seconds for the test to run kinda breaks that flow.

**Comment by alextekartik** [comment] 2018-09-24 10:18
+1 on @brianegan comments. I'm a huge fan of TDD since java where 1s was the expected delay when running a test. Dart1 had very good TDD support and we were in this range (i.e. save/pub run test was almost immediate). Flutter dart and even dart regular test are painfully slower in dart2 (having to wait an extra 5s or more). I personally feel being less productive and more reluctent in writing tests.

**Comment by rrousselGit** [comment] 2018-09-24 13:04
Would a watch-mode with incremental build help reduce loading time?

I personally love what Jest offers in term of tests. It's not only fast but also able to run only the tests impacted by your uncommitted changes. And it also offers the ability to replay only failed tests.

These don't directly impact performances but are definitely helping in reducing time spent.

**Comment by keertip** [comment] 2018-09-24 15:41
Issue  #4719 does sketch out a plan to implement a watch mode for flutter tests.  Would that be something you would use, if available?  @brianegan

**Comment by brianegan** [comment] 2018-09-24 15:56
@keertip I could certainly see watching for changes as a useful feature for many folks, but might not be as useful for me personally because IntelliJ easily allows you to run tests / rerun failed tests with quick keyboard-shortcuts.

If it's a matter of resourcing, I'd much rather see this issue resolved first (since it's a pretty big regression from the Dart 1 experience), then worry about extra functionality.

**Comment by DanTup** [comment] 2018-09-24 15:56
It'd be great if it was implemented in a tool-friendly way. Eg. editors can spawn it in `watch` mode in the BG and send it commands to run individual tests, so the existing behaviour for running individual tests/groups can be used (running all tests on a change might result in a longer run than people want).

**Comment by twistedinferno** [comment] 2018-11-15 21:36
Hi, has there been any update on this?  I have gone back to flutter land, I updated to the latest master channel and when running dart only tests they are taking 3+seconds instead of 0.5s.  Is it ok to use the commit with the improvements or was there a problem with that specific fix?  The flutter revision id is 449e3c2a0a.

**Comment by jensjoha** [comment] 2018-11-16 08:02
Is what you're saying, that something like `C:\path\to\flutter\bin\cache\dart-sdk\bin\dart.exe helloworld.dart` takes 3+ seconds?

**Comment by twistedinferno** [comment] 2018-11-16 12:30
using `dart 2.1.0-dev.9.4.flutter-f9ebf21297` (latest version from master)
yes, using the flutter\bin\cache\dart.exe , I reran it now and it took 2.5 seconds to run a test on my machine (windows i5) (I may have counted the seconds incorrectly last night to 3.5 or used the path dart.exe), I think the 0.5 was for the helloworld.dart and not the test so I think this is what had been achieved 6 weeks or so ago.
I think for me 2.5seconds per test is kind of workable for the moment, do you think there will be an improvement on this in the future or any other thoughts about improving the speed?  (I should probably just get on with my work now though!)

**Comment by jensjoha** [comment] 2018-11-16 14:44
Am I summarizing correctly here:
* ~6 weeks ago we got helloworld.dart to ~0.5 seconds and testing_test.dart to ~2.5 seconds.
* This is still where we are today (i.e. no new regression)

?

I realize that it's unfortunate that it haven't improved further.
We are always trying to make things go faster, but unfortunately it's not always as easy as deciding that we want to...

**Comment by twistedinferno** [comment] 2018-11-16 15:30
I thought it had slowed over the last six weeks but that isn't the case.  Yes, the speeds are the same as six weeks ago, improved, still a bit slower than I would like and slower than dart1 but it is better now.  I appreciate this work so many many thanks for all of it and being part of the people who has brought us these tools, that is all very much appreciated too; yup, sometimes things aren't always straight forward.  Keep us updated of course with any updates and of course I'll be very keen to hear of any further improvements if they come along :-)

**Comment by JSANL** [comment] 2018-12-01 15:31
Sorry, if I don't understand this correctly, but is it expected behavior that flutter runs a `FlutterTest` even when just using "normal" dart code?
If I run `flutter test` (or use the "run" text in vscode) for my simple test case, then it takes 2 sec (really about 5) and if I run it with `[...]/flutter/bin/cache/dart-sdk.exe` it runs in a <1 sec (really about 1.30 sec).

Here's my simple test:
```dart
import 'package:test/test.dart';

List<int> factorsOf(int n) {
  final List<int> factors = [];
  int divisor = 2;
  while (n > 1) {
    while (n % divisor == 0) {
      factors.add(divisor);
      n = n ~/ divisor;
    }
    divisor++;
  }
  return factors;
}

void main() {
  group('PrimeFactorTests', () {
    test('factors', () {
      expect(factorsOf(1), []);
      expect(factorsOf(2), [2]);
      expect(factorsOf(3), [3]);
      expect(factorsOf(4), [2, 2]);
      expect(factorsOf(5), [5]);
      expect(factorsOf(6), [2,3]);
      expect(factorsOf(7), [7]);
      expect(factorsOf(8), [2,2,2]);
      expect(factorsOf(9), [3,3]);
      expect(factorsOf(2 * 2 * 3 * 3 * 5 * 7 * 11 * 11 * 13), [2,2,3,3,5,7,11,11,13]);
    });
  });
}
```
Flutter doctor:
```
[√] Flutter (Channel master, v0.11.14-pre.2, on Microsoft Windows [Version 10.0.17134.407], locale de-DE)
    • Flutter version 0.11.14-pre.2 at E:\Development\flutter
    • Framework revision a226c0f0d9 (15 hours ago), 2018-11-30 16:18:18 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at E:\Development\Android_SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: E:\Development\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at E:\Development\Android Studio
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Also I'm pretty happy that you guys already shortened the normal flutter tests, but I think for TDD it should probably be even lower... I guess you already know that though😉

**Comment by DanTup** [comment] 2018-12-03 08:06
> Sorry, if I don't understand this correctly, but is it expected behavior that flutter runs a `FlutterTest` even when just using "normal" dart code?

I'm not sure where you're running this but generally I believe the answer is yes. It's the same as running `pub run test` versus `dart.exe` for non-Flutter tests. Running directly with the VM works, but you lose functionality added by the test runners (for example in the case of running from an IDE, they ability to output results as JSON so that the results can be shown in a structured tree).

**Comment by DanTup** [comment] 2018-12-03 12:36
> If there are only pure dart tests to be run, then just use the dart.exe, else use the FlutterTest.

I'm not sure where you'd like this change to be made. If you're running from the terminal you're invoking `dart` or `flutter run` yourself but if you're running from an IDE using the test runner then it's required to run the full test runner so the results can be parsed.

**Comment by jeking3** [comment] 2019-01-23 12:53
I am seeing a dramatic slowdown in the execution of dart programs with dart 2.0.0 and 2.1.0.  A relatively simple program in the Apache Thrift cross-language test suite took 1.7 seconds to run with dart 1.24.3 and it takes 7.7 seconds to run with dart 2.1.0 on linux.  It takes about 4.4 seconds just to fail when I don't give it any arguments.  This is with or without "--checked".  Something is seriously wrong.

**Comment by mraleph** [comment] 2019-01-23 15:07
@jeking3 what you are seeing is the cost of parsing. 1.24.3 used a very lazy parser written in C++ (which would only parse the code that needs to be executed, would not report any static type errors, etc), 2.x onward use very eager parser written in Dart which parses your whole program and all its dependencies, does type inference and reports static errors before execution of your program even starts. (Also if your `dart` binary is a symbolic link you might observe even worse performance.,)  

If you run same program repetitively during deployment you can use snapshots to speed up the startup (`dart --snapshot=main.snapshot main.dart`).

During development you would need to have a build-system and/or persistent compiler process - this is unfortunately not something that we currently distribute with SDK. 

Also note that this is bug about Flutter - if you would like to report bugs against Dart SDK then you need to file those at dart-lang/sdk.

**Comment by jeking3** [comment] 2019-01-24 04:09
Seems like a significant regression in dart 2 if you ask me (the performance issue, not the correctness).  Anyway thanks.

**Comment by liyuqian** [comment] 2019-04-22 22:24
Duplicate of https://github.com/flutter/flutter/issues/17130. Closing.

**Closed by liyuqian** 2019-04-22 22:24 UTC
Labels: a: tests, dependency: dart, severe: performance, severe: regression
