### ISSUE TITLE
> Android webview load html get too many`updateAcquireFence: Did not find frame.`

### ISSUE THREAD

**Issue by toknT** [flutter/flutter#155068] opened 2024-09-12 06:50 UTC
In my case just load html no pdf or docx.

It's a html of ali captcha v2.0 , they say use webview in mobile app.

```html
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>验证码</title>
    <!-- 阿里验证码2.0用webview 的,这是加载的html -->
  </head>
  <body style="margin: 0;">
    <div id="space-semantic">
      <div id="embed-wrapper" style="background-color: aqua;">
        <div class="embed-wrapper">
          <!-- <div>
            <label>用户名：</label>
            <input id="username-embed" class="biz-input" />
          </div>
          <div>
            <label>密码：</label>
            <input id="password-embed" type="password" class="biz-input" />
          </div> -->
          <div id="captcha-element"></div>
          <!-- <button id="button" class="login-btn">登录</button> -->
        </div>
      </div>
    </div>
    <script
      type="text/javascript"
      src="https://o.alicdn.com/captcha-frontend/aliyunCaptcha/AliyunCaptcha.js"
    ></script>
    <script>
      let captcha;
      // 嵌入式
      initAliyunCaptcha({
        SceneId: "1b3w5bb2", // 场景ID。通过步骤一添加验证场景后，您可以在验证码场景列表，获取该场景的场景ID
        prefix: "1j6vcl", // 身份标。开通阿里云验证码2.0后，您可以在控制台概览页面的实例基本信息卡片区域，获取身份标
        mode: "embed", // 验证码模式。embed表示要集成的验证码模式为嵌入式。无需修改
        element: "#captcha-element", // 页面上预留的渲染验证码的元素，与原代码中预留的页面元素保持一致。
        button: "#button", // 触发业务请求的元素。button表示单击登录按钮后，触发captchaVerifyCallback函数。您可以根据实际使用的元素修改element的值
        captchaVerifyCallback: captchaVerifyCallback, // 业务请求(带验证码校验)回调函数，无需修改
        onBizResultCallback: onBizResultCallback, // 业务请求结果回调函数，无需修改
        getInstance: getInstance, // 绑定验证码实例函数，无需修改
        slideStyle: {
          width: 350,
          height: 40,
        }, // 滑块验证码样式，支持自定义宽度和高度，单位为px。其中，width最小值为320 px
        language: "cn", // 验证码语言类型，支持简体中文（cn）、繁体中文（tw）、英文（en）
        immediate: true, // 完成验证后，是否立即发送验证请求（调用captchaVerifyCallback函数）
        region: "cn",
      });

      // 绑定验证码实例函数。该函数为固定写法，无需修改
      function getInstance(instance) {
        captcha = instance;
      }

      // 业务请求(带验证码校验)回调函数
      /**
       * @name verifyCaptchaCallback
       * @function
       * 请求参数：由验证码脚本回调的验证参数，不需要做任何处理，直接传给服务端即可
       * @params {string} captchaVerifyParam
       * 返回参数：字段名固定，captchaResult为必选；如无业务验证场景时，bizResult为可选
       * @returns {{captchaResult: boolean, bizResult?: boolean|undefined}}
       */
      async function captchaVerifyCallback(captchaVerifyParam) {
        CaptchaVerifyCallback.postMessage(JSON.stringify(captchaVerifyParam))
      }

      // 业务请求结果回调函数
      function onBizResultCallback(bizResult) {
        console.debug("onBizResultCallback", bizResult);
      }
    </script>
  </body>
</html>

```

              > Tested on docx and pdf.

Android webviews are not generic document viewers; they don't support either of those file types.

Closing as this is a behavior of the underlying platform control, and not within the control of the plugin. Displaying PDFs would require a PDF viewer plugin.

_Originally posted by @stuartmorgan in https://github.com/flutter/flutter/issues/143525#issuecomment-1946736540_

**Comment by danagbemava-nc** [comment] 2024-09-12 09:17
Closing this as a duplicate of https://github.com/flutter/flutter/issues/104268. This isn't specifically related to the content you load in the web view but related to the android operating system itself. See https://github.com/flutter/flutter/issues/104268#issuecomment-1134964433

**Closed by danagbemava-nc** 2024-09-12 09:17 UTC
Labels: in triage
