### ISSUE TITLE
Unable to build on iOS when adding some packages, Flutter version 3.5.4, xCode 15.4

### ISSUE THREAD

**Issue by duc0** [flutter/flutter#157765] opened 2024-10-29 01:05 UTC
### Steps to reproduce

Start a fresh Flutter sample project
Add a package to the project, such as in_app_review (flutter pub add in_app_review). This issue can be reproduced with several package.

Build on iOS.

### Expected results

App launched on iOS

### Actual results

Received errors:

Error (Xcode): double-quoted include "InAppReviewPlugin.h" in framework header, expected angle-bracketed instead
/Users/U/Development/Space64/test_bug_oct29/ios/Pods/Target%20Support%20Files/in_app_review/in_app_review-umbrella.h:12:8

Error (Xcode): 'Flutter/Flutter.h' file not found
/Users/U/.pub-cache/hosted/pub.dev/in_app_review-2.0.9/ios/Classes/InAppReviewPlugin.h:0:8

Error (Xcode): (fatal) could not build module 'in_app_review'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c++_arm64-apple-ios12.0-simulator_gnu++20/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c++_arm64-apple-ios12.0-simulator_gnu++20/Test/Test.mm:0:8

Error (Xcode): (fatal) could not build module 'in_app_review'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c++_x86_64-apple-ios12.0-simulator_gnu++20/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c++_x86_64-apple-ios12.0-simulator_gnu++20/Test/Test.mm:0:8

Error (Xcode): (fatal) could not build module 'in_app_review'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c_arm64-apple-ios12.0-simulator_gnu17/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c_arm64-apple-ios12.0-simulator_gnu17/Test/Test.m:0:8

Error (Xcode): (fatal) could not build module 'in_app_review'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c_x86_64-apple-ios12.0-simulator_gnu17/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c_x86_64-apple-ios12.0-simulator_gnu17/Test/Test.m:0:8

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:in_app_review/in_app_review.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  void review() async {
    final InAppReview inAppReview = InAppReview.instance;

    if (await inAppReview.isAvailable()) {
      inAppReview.requestReview();
    }
  }
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    review();

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // TRY THIS: Try running your application with "flutter run". You'll see
        // the application has a purple toolbar. Then, without quitting the app,
        // try changing the seedColor in the colorScheme below to Colors.green
        // and then invoke "hot reload" (save your changes or press the "hot
        // reload" button in a Flutter-supported IDE, or press "r" if you used
        // the command line to start the app).
        //
        // Notice that the counter didn't reset back to zero; the application
        // state is not lost during the reload. To reset the state, use hot
        // restart instead.
        //
        // This works for code too, not just values: Most code changes can be
        // tested with just a hot reload.
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // TRY THIS: Try changing the color here to a specific color (to
        // Colors.amber, perhaps?) and trigger a hot reload to see the AppBar
        // change color while the other colors stay the same.
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          //
          // TRY THIS: Invoke "debug painting" (choose the "Toggle Debug Paint"
          // action in the IDE, or press "p" in the console), to see the
          // wireframe for each widget.
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
Resolving dependencies...
Downloading packages...
  async 2.11.0 (2.12.0 available)
  boolean_selector 2.1.1 (2.1.2 available)
  characters 1.3.0 (1.3.1 available)
  clock 1.1.1 (1.1.2 available)
  collection 1.18.0 (1.19.1 available)
  fake_async 1.3.1 (1.3.2 available)
  flutter_lints 4.0.0 (5.0.0 available)
< in_app_review 2.0.0 (was 2.0.1) (2.0.9 available)
  leak_tracker 10.0.5 (10.0.8 available)
  leak_tracker_flutter_testing 3.0.5 (3.0.9 available)
  lints 4.0.0 (5.1.0 available)
  matcher 0.12.16+1 (0.12.17 available)
  material_color_utilities 0.11.1 (0.12.0 available)
  meta 1.15.0 (1.16.0 available)
  path 1.9.0 (1.9.1 available)
  stack_trace 1.11.1 (1.12.0 available)
  string_scanner 1.2.0 (1.4.0 available)
  test_api 0.7.2 (0.7.3 available)
  vm_service 14.2.5 (14.3.1 available)
Changed 1 dependency!
19 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on iPhone14PlusiOS16 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                            7.5s
Failed to build iOS app
Error (Xcode): double-quoted include "InAppReviewPlugin.h" in framework header, expected angle-bracketed instead
/Users/U/Development/Space64/test_bug_oct29/ios/Pods/Target%20Support%20Files/in_app_review/in_app_review-umbrella.h:12:8

Error (Xcode): 'Flutter/Flutter.h' file not found
/Users/U/.pub-cache/hosted/pub.dev/in_app_review-2.0.0/ios/Classes/InAppReviewPlugin.h:0:8

Error (Xcode): (fatal) could not build module 'in_app_review'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c++_arm64-apple-ios12.0-simulator_gnu++20/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c++_arm64-apple-ios12.0-simulator_gnu++20/Test/Test.mm:0:8

Error (Xcode): (fatal) could not build module 'in_app_review'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c++_x86_64-apple-ios12.0-simulator_gnu++20/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c++_x86_64-apple-ios12.0-simulator_gnu++20/Test/Test.mm:0:8

Error (Xcode): (fatal) could not build module 'in_app_review'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c_arm64-apple-ios12.0-simulator_gnu17/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c_arm64-apple-ios12.0-simulator_gnu17/Test/Test.m:0:8

Error (Xcode): (fatal) could not build module 'in_app_review'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c_x86_64-apple-ios12.0-simulator_gnu17/Test/Test.framework/Headers/Test.h:0:8

Error (Xcode): (fatal) could not build module 'Test'
/Users/U/Library/Developer/Xcode/DerivedData/Runner-dxhrsfxrtgauhegulchxkouxcuub/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/in_app_review.build/VerifyModule/in_app_review_objective-c_x86_64-apple-ios12.0-simulator_gnu17/Test/Test.m:0:8

Could not build the application for the simulator.
Error launching application on iPhone14PlusiOS16.

```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 14.5 23F79 darwin-arm64 (Rosetta), locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.2.5)
[✓] VS Code (version 1.94.2)
[✓] Connected device (7 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by matehat** [comment] 2024-10-29 01:56
It seems to be a duplicate of https://github.com/flutter/flutter/issues/157761

**Comment by berbsd** [comment] 2024-10-29 01:59
same issue as  #157694

**Comment by huycozy** [comment] 2024-10-29 09:49
Closing this in favor of https://github.com/flutter/flutter/issues/157761, please check https://github.com/flutter/flutter/issues/157761#issuecomment-2443732531.

**Closed by huycozy** 2024-10-29 09:49 UTC
Labels: in triage

**Comment by duc0** [comment] 2024-10-30 00:15
Confirmed that updating cocoapods fixed the issues.
