### ISSUE TITLE
Textfield without bottom contentPadding overflows inside IntrinsicHeight widget

### ISSUE THREAD

**Issue by GnafGnaf** [flutter/flutter#51396] opened 2020-02-25 08:05 UTC
## Steps to Reproduce
1. Run `flutter create bug`.
2. Update the files as follows: 
Replace main.dart with

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: IntrinsicHeight(
            child: Column(
              children: <Widget>[
                TextField(
                  decoration: InputDecoration(
                    contentPadding: EdgeInsets.zero,
                    labelText: 'hello world',
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

3. Run app
**Expected results:** A textfield in the center.
**Actual results:** An overflow warning
**Workaround:** Instead of EdgeInsets.zero use EdgeInsets.only(bottom: 13). You always need a bottom padding of at least 13.

## Doctor summary:
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

**Comment by ibobo** [comment] 2020-05-04 14:06
Happens to me also

**Comment by AramSemerjyan** [comment] 2020-06-30 13:06
Yup, still there.

**Comment by TahaTesser** [comment] 2020-07-08 13:07
Hi @GnafGnaf  @ibobo  @AramSemerjyan 

Not able to reproduce this issue,  please logs using latest `dev` channel 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: IntrinsicHeight(
            child: Column(
              children: <Widget>[
                TextField(
                  decoration: InputDecoration(
                    contentPadding: EdgeInsets.zero,
                    // contentPadding: EdgeInsets.only(bottom: 13),
                    labelText: 'hello world',
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (4 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (3 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.5.1
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details> 

Thank you

**Comment by GnafGnaf** [comment] 2020-07-09 12:51
It works on Dev Channel but not on Stable. So it should be fixed with the next merge. Thank you.

**Comment by TahaTesser** [comment] 2020-07-09 13:44
Hi @GnafGnaf 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-07-09 13:44 UTC
Labels: a: text input, engine, f: material design, framework
