### ISSUE TITLE
Form Fields which cause a validation error off-screen with ListView.builder do not have an error when you scroll down

### ISSUE THREAD

**Issue by MilesAdamson** [flutter/flutter#97167] opened 2022-01-24 23:00 UTC
## Steps to Reproduce

1. Create a form long enough that you want to use `ListView.builder` for performance
2. Submit the form with a field off screen past what is built lazily
3. When you scroll down, the widget will not show an error
4. If you scroll back up, widgets which used to show errors have them cleared
5. If you press submit again and there is an error at the top still, the fields which used to have an error do not display anything

**Expected results:** 
An error message on fields which blocked the form from submitting

**Actual results:** 
No error (but it's worth noting the fields off screen do properly block the forms validation)

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  final formKey = GlobalKey<FormState>();

  final controllers = List.generate(20, (index) => TextEditingController());

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.send),
        onPressed: () {
          final isValid = formKey.currentState!.validate();

          if (!isValid) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                backgroundColor: Colors.red,
                content: Text('Correct the form'),
              ),
            );
          } else {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                backgroundColor: Colors.green,
                content: Text('Form valid'),
              ),
            );
          }
        },
      ),
      body: Form(
        key: formKey,
        child: buildListViewBuilder(),
      ),
    );
  }

  // This will show errors on off-screen widgets when you scroll down
  Widget buildSingleChildScrollView() {
    return SingleChildScrollView(
      child: Column(
          children: controllers
              .map((c) => MyFormField(
                    controller: c,
                    i: controllers.indexOf(c),
                  ))
              .toList()),
    );
  }

  // This will not show errors on off-screen widgets when you scroll
  Widget buildListViewBuilder() {
    return ListView.builder(
      itemCount: 20,
      itemBuilder: (context, i) {
        return MyFormField(
          controller: controllers[i],
          i: i,
        );
      },
    );
  }
}

class MyFormField extends StatefulWidget {
  final TextEditingController controller;
  final int i;

  const MyFormField({
    Key? key,
    required this.controller,
    required this.i,
  }) : super(key: key);

  @override
  State<MyFormField> createState() => _MyFormFieldState();
}

class _MyFormFieldState extends State<MyFormField> {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: TextFormField(
        controller: widget.controller,
        decoration: InputDecoration(
          labelText: "Field ${widget.i + 1}",
        ),
        validator: (s) {
          if (s == null || s.isEmpty) {
            return "Field is required";
          }
        },
      ),
    );
  }
}


```

</details>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19043.1466], locale en-CA)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

• No issues found!
```

https://user-images.githubusercontent.com/29047682/150879128-8773dc01-296e-4b73-9c75-76357fc908fe.mp4

## Notes
- `AutomaticKeepAliveClientMixin` does NOT cause fields which have never been rendered yet to properly display an error when you scroll down. It does however, cause fields which displayed an error to still be red when you scroll back up
- `restorationId` on the form and fields does not fix it either

**Comment by maheshmnj** [comment] 2022-01-25 12:07
Hi @MilesAdamson, Thanks for filing the issue. This is working as intended considering `ListView.builder` builds its items on demand which means when the item is about to be visible in the viewport it gets built and destroyed when its gets off screen based on the cacheExtent value, You can control this length using [cacheExtent](https://api.flutter.dev/flutter/widgets/ScrollView/cacheExtent.html) 

e.g  adding cache extent 2000 (should be maxExtent) fixes the issue for your case

```dart
  Widget buildListViewBuilder() {
    return ListView.builder(
      itemCount: 20,
      cacheExtent: 2000,
      itemBuilder: (context, i) {
        return MyFormField(
          controller: controllers[i],
          i: i,
        );
      },
    );
  }
```
 while in case of any other ScrollView like SingleChildScrollView or ListView all its child / children are created at once regardless of the length of the list and are stored in memory until the lifetime of the widget.
 
 Closing as this is working as intended, if you disagree feel free to write in the comments and I will reopen it. 
 
 Thank you.

**Closed by maheshmnj** 2022-01-25 12:07 UTC
Labels: in triage

**Comment by MilesAdamson** [comment] 2022-01-25 17:00
Hey @maheshmnj, using `cacheExtent` and/or the `ListView(`  constructor does not let form fields render on their first build with an error. Only putting all of the children in a `SingleChildScrollView` + `Column` works, which could have performance issues with a long enough form

![image](https://user-images.githubusercontent.com/29047682/151022456-23b288d0-8c1c-4b77-b979-fa3180fb71bd.png)

**Comment by MilesAdamson** [comment] 2022-01-25 17:03
Also before anyone says "just make the form shorter and multiple pages" the app works with JSON schema and I do not have complete control over the length of the form. Some pages are obscenely long

**Comment by maheshmnj** [comment] 2022-01-26 07:19
@MilesAdamson you are using a cache extent of 20  as a result you are still seeing the error getting reset. try setting it to 2000, Alternatively, you could maintain the errors in the state of the app and show errors for selective fields, Heres is a similar discussion on StackOverflow for your reference https://stackoverflow.com/questions/47409181/losing-state-of-each-form-field-when-the-form-is-scrolled-off-screen

**Comment by MilesAdamson** [comment] 2022-01-26 20:57
Yes I could re-write the form field and form state, and house all the errors in my app state. However, why can't the form field draw itself with an error when it has an error on its first build? Its not clear to me how that it's intended and a non-issue that form fields can have an error which invalidates the form, but visually have no error

**Comment by maheshmnj** [comment] 2022-01-27 05:24
> However, why can't the form field draw itself with an error when it has an error on its first build?

This is happening for two reasons firstly your form is long and secondly, you are using `ListView.builder` the listview Items are erased and rebuilt from memory when they go off-screen and are brought into the screen (made visible).
Heres a short video from flutter to understand this https://www.youtube.com/watch?v=KJpkjHGiI5A

**Comment by MilesAdamson** [comment] 2022-01-27 16:57
I understand the widget is erased from memory. What I don't understand, is that when a TextFormField comes into memory, and my form state has an error, why does it not display that error? Its state does not match what is rendered.

As you said I could house the errors in my own app state and make a form field render with an error on its first build. Why can't TextFormField's do the same?
