### ISSUE TITLE
[camera][iOS] using startImageStream() can lead to memory crash on iOS

### ISSUE THREAD

**Issue by renanyoy** [flutter/flutter#97941] opened 2022-02-07 08:21 UTC
## Steps to Reproduce

1. Execute `flutter run` on the code sample 
2. memory problems..

<details>
<summary>Code sample</summary>

```dart

    final controller = CameraController(camera, ResolutionPreset.max,
        enableAudio: false, imageFormatGroup: ImageFormatGroup.bgra8888);
    await controller.initialize();
    controller.lockCaptureOrientation(DeviceOrientation.portraitUp);
      controller.startImageStream((image) async {
        if (paused) return;
        //this.image = image;
      });

```

</details>

<details>
  <summary>Logs</summary>

```
[ +322 ms] flutter: |L2K|camera initialized
[+1156 ms] [ServicesDaemonManager] interruptionHandler is called. -[FontServicesDaemonManager connection]_block_invoke
[ +434 ms] *** Terminating app due to uncaught exception 'NSMallocException', reason: 'Failed to grow buffer'
[        ] *** First throw call stack:
[        ] (0x18091d0fc 0x199169d64 0x180a2ab24 0x180a22e10 0x1808b733c 0x1820e1ad8 0x1820dd764 0x182125870 0x182127fa8 0x18210d69c 0x10f30d234 0x10f30d044 0x10f30d234 0x10f30d788 0x10f30af84 0x10c445528 0x18058d924 0x18058f670 0x18059db70 0x1808d5d84 0x18088ff5c 0x1808a3468 0x19c44338c
0x1832465d0 0x182fc4f74 0x10404085c 0x10b795aa4)
[        ] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** NSAllocateMemoryPages(33177600) failed'
[        ] *** First throw call stack:
[        ] (0x18091d0fc 0x199169d64 0x182127f30 0x1820d3260 0x1820e69e0 0x10c444ab0 0x19f304124 0x19f2ee27c 0x19f534098 0x19f6ea6b8 0x18058f670 0x180592b44 0x1805a5c48 0x180596ccc 0x180597968 0x1805a21b8 0x1f13ab0f4 0x1f13aae94)
[        ] libc++abi: terminating with uncaught exception of type NSException
[        ] libc++abi: terminating with uncaught exception of type NSException
[ +305 ms] Process 4459 stopped
[        ] * thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
[        ]     frame #0: 0x00000001b7e79964 libsystem_kernel.dylib`__pthread_kill + 8
[        ] libsystem_kernel.dylib`__pthread_kill:
[        ] ->  0x1b7e79964 <+8>:  b.lo   0x1b7e79984               ; <+40>
[        ]     0x1b7e79968 <+12>: pacibsp 
[        ]     0x1b7e7996c <+16>: stp    x29, x30, [sp, #-0x10]!
[        ]     0x1b7e79970 <+20>: mov    x29, sp
[        ] Target 0: (Runner) stopped.
[        ] ios-deploy exited with code 0
[ +157 ms] Service protocol connection closed.
[        ] Lost connection to device.
```

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-x64, locale en-FR)
    • Flutter version 2.10.0 at /Users/renanyoy/code/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (5 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/renanyoy/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.0.rc.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • Renaniphone (mobile) • 00008020-000640992209002E • ios        • iOS 15.3 19D50
    • macOS (desktop)      • macos                     • darwin-x64 • macOS 12.1 21C52 darwin-x64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by danagbemava-nc** [comment] 2022-02-07 13:06
Hi @renanyoy, thanks for filing the issue. 

Please provide a complete minimal reproducible code sample and the full `flutter run -v` logs. 

Also, what version of `camera` are you using? 

Thank you

**Comment by renanyoy** [comment] 2022-02-07 13:26
the log and the sample are in the first post 

we are using the latest camera addon 0.9.4+10.

also, when seeking after responses, I found that the problem should fixed with this pull request
https://github.com/flutter/plugins/pull/4520

**Comment by danagbemava-nc** [comment] 2022-02-07 14:25
Neither of the info you provided in the initial post is complete, which is why I asked for a `complete minimal reproducible code sample` as well as full logs. 

Also, the steps to reproduce aren't quite clear to me. 

Does the app crash on startup or does it crash after a certain period of time? Also, what device did you experience the crash with? 

> also, when seeking after solutions, I found that the problem should be fixed with this pull request
flutter/plugins#4520

If this PR should fix the issue, then this issue should probably be dedup'd with #44436

**Comment by renanyoy** [comment] 2022-02-08 09:43
it crash at startImageStream(..)

**Comment by renanyoy** [comment] 2022-02-09 08:42
the full code

```dart

import 'dart:developer' as dev;
import 'dart:math';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key? key}) : super(key: key);
  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  late CameraController controller;
  bool initialized = false;

  @override
  void initState() {
    super.initState();
    init();
  }

  Future<CameraController> initCamera(CameraDescription camera) async {
    final controller = CameraController(camera, ResolutionPreset.max,
        enableAudio: false, imageFormatGroup: ImageFormatGroup.yuv420);
    await controller.initialize();
    controller.lockCaptureOrientation(DeviceOrientation.portraitUp);
    return controller;
  }

  Future<void> init() async {
    final cameras = await availableCameras();
    controller = await initCamera(cameras.first);
    initialized = true;
    setState(() {});
    controller.startImageStream((image) {
      dev.log('frame');
    });
    (() async {
      // OCR cpu usage simulation
      while (true) {
        await Future.delayed(const Duration(seconds: 2));
        double z = 0;
        for (int i = 0; i < 100000000; i++) {
          z = cos(z);
        }
      }
    })();
  }

  @override
  Widget build(BuildContext context) {
    return initialized ? CameraPreview(controller) : Container();
  }
}

```

**Comment by danagbemava-nc** [comment] 2022-02-09 12:38
Hi @renanyoy, can you also provide the full `flutter run -v` log? Also, did you experience this issue in `debug` mode or `profile/release` mode?

**Comment by renanyoy** [comment] 2022-02-11 08:52
it crash in debug and release
but I seen it working one time without crashing

https://pub.waves.pw/ms/crash.log.txt
log is too big to post here

**Comment by danagbemava-nc** [comment] 2022-02-11 12:52
Hi @renanyoy, what device were you testing with?

**Comment by renanyoy** [comment] 2022-02-11 13:19
iPhone XR

**Comment by hellohuanlin** [comment] 2022-02-11 21:40
@danagbemava-nc how long did it take for you to crash on your device? I couldn't get it crash on my iPhone 13 mini but can try my old phone.

**Comment by hellohuanlin** [comment] 2022-02-11 22:11
I wasn't able to get it crashed on my phone, but i do notice the lagging, which is expected because of the expensive operation in the example: 

```
      // OCR cpu usage simulation
      while (true) {
        await Future.delayed(const Duration(seconds: 2));
        double z = 0;
        for (int i = 0; i < 100000000; i++) {
          z = cos(z);
        }
      }
```

**Comment by renanyoy** [comment] 2022-02-12 07:53
in the real app, there is a block doing the OCR using google ML kit, in that case it always crashes. you can try 

```
// OCR cpu usage simulation
      while (true) {
        await Future.delayed(const Duration(milliseconds: 200));
        double z = 0;
        for (int i = 0; i < 1000000000; i++) {
          z = cos(z);
        }
      }

```

**Comment by renanyoy** [comment] 2022-02-12 08:10
maybe it's possible to add a ram usage stress too, to get the crash more often.

**Comment by danagbemava-nc** [comment] 2022-02-15 06:31
> @danagbemava-nc how long did it take for you to crash on your device? I couldn't get it crash on my iPhone 13 mini but can try my old phone.

@hellohuanlin  It took about 2 minutes. This time around, instead of moving the camera around, I just left the phone by itself.

**Comment by Anfet** [comment] 2022-02-15 11:06
Not only IOS, but android experience issues with memory on  several samsung and xiaomi phones.

I'm intererested why "stopImageStream" actually somehow stops and resets camera.

**Comment by hellohuanlin** [comment] 2022-02-15 21:13
@renanyoy the skipping frame part sounds somewhat related to https://github.com/flutter/flutter/issues/97941#issuecomment-1037051617 but I am not sure yet. 

Is it possible to bring that heavy computation off the ui thread? Or is it required to be on UI thread?

**Comment by renanyoy** [comment] 2022-02-16 03:43
the computation is here to provoke the crash, like in a real app

**Comment by stuartmorgan** [comment] 2022-02-17 21:30
Duplicate of https://github.com/flutter/flutter/issues/44436

**Closed by stuartmorgan** 2022-02-17 21:30 UTC
Labels: platform-ios, plugin, p: first party, p: camera, perf: memory, has reproducible steps, severe: fatal crash, found in release: 2.10, found in release: 2.11
