### ISSUE TITLE
`testwidgets()` in widget_tester.dart does not respect the skip from group

### ISSUE THREAD

**Issue by timnew** [flutter/flutter#69465] opened 2020-10-31 12:19 UTC
## Steps to Reproduce
1. Create a test group, and mark its `skip` to `true`
2. Create a `testWidgets` test inside of the group
3. Run the test suite

**Expected results:** all tests in the group are skipped
**Actual results:** normal tests are skipped, but not the widget tests.

![image](https://user-images.githubusercontent.com/1287238/97778875-6f553480-1bce-11eb-86e6-d686806b6c61.png)
![image](https://user-images.githubusercontent.com/1287238/97778882-78460600-1bce-11eb-83be-73ff78b603dd.png)

<details>
  <summary>Logs</summary>

```
n/a
```

```
Analyzing response_builder...
No issues found! (ran in 2.6s)
```

```
⋊> ~/W/response_builder on master ⨯ flutter doctor -v                                                                                                                                                                 23:15:34
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.5 19F101, locale en-AU)
    • Flutter version 1.22.2 at /Users/tim.wen/Workspace/flutter
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tim.wen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = Users/tim.wen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
</details>

**Comment by timnew** [comment] 2020-10-31 12:19
It is related to https://github.com/flutter/flutter/issues/21462 but it is a different issue.

**Comment by hamdikahloun** [comment] 2020-10-31 14:17
Hi @timnew 

Can you please provide your `flutter doctor -v`?

Thank you

**Comment by timnew** [comment] 2020-11-01 09:18
Hey @hamdikahloun I have included in the original post, but happy to paste here again:

```
⋊> ~/W/response_builder on master ⨯ flutter doctor -v                                                                                                                                                                 23:15:34
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.5 19F101, locale en-AU)
    • Flutter version 1.22.2 at /Users/tim.wen/Workspace/flutter
    • Framework revision 84f3d28555 (2 weeks ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tim.wen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = Users/tim.wen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
 
`Flutter plugin`, and `Dart plugin` not found is caused by another bug of flutter doctor(https://github.com/flutter/flutter/issues/61246)

**Comment by hamdikahloun** [comment] 2020-11-01 09:53
I'm able to reproduce the issue

<details>
  <summary>main.dart</summary>

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Flutter example app'),
        ),
        body: Center(
          child: Text('Triage'),
        ),
      ),
    );
  }
}

```

</details>

<details>
  <summary>widget_test.dart</summary>

```
// This is a basic Flutter widget test.
//
// To perform an interaction with a widget in your test, use the WidgetTester
// utility that Flutter provides. For example, you can send tap and scroll
// gestures. You can also use WidgetTester to find child widgets in the widget
// tree, read text, and verify that the values of widget properties are correct.

import 'package:flutter_test/flutter_test.dart';
import 'package:hello_example/main.dart';

void main() {
  group('skip disabled', () {
    test('.split() splits the string on the delimiter', () {
      var string = 'foo,bar,baz';
      expect(string.split(','), equals(['foo', 'bar', 'baz']));
    });

    test('.trim() removes surrounding whitespace', () {
      var string = '  foo ';
      expect(string.trim(), equals('foo'));
    });
  });

  group('skip enabled', () {
    String text = "My Text";

    test('Verify text', () {
      expect("Other Text", text);
    });

    testWidgets('Verify Widget', (WidgetTester tester) async {
      await tester.pumpWidget(MyApp());

      expectSync(find.text(text), findsOneWidget);
    });

    test('Verify text again', () {
      expect("Other Text too", text);
    });

  }, skip: "TODO: add Text error-checking.");
}

```

</details>

**Comment by darshankawar** [comment] 2020-11-02 10:13
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.22.3 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8874f21e79 (3 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!



```

</details>

<img width="704" alt="Screenshot 2020-11-02 at 3 43 11 PM" src="https://user-images.githubusercontent.com/67046386/97856319-21e9dc00-1d22-11eb-8704-263f2b30feb5.png">

**Comment by jason-simmons** [comment] 2021-03-20 00:15
Duplicate of https://github.com/flutter/flutter/issues/76135

**Closed by jason-simmons** 2021-03-20 00:15 UTC
Labels: a: tests, found in release: 1.22, has reproducible steps, passed first triage
