### ISSUE TITLE
[tool_crash] FileSystemException: Deletion failed, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by huzaifamughal076** [flutter/flutter#139541] opened 2023-12-05 05:34 UTC
## Command
```
flutter pub get --no-example
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Deletion failed, OS Error: The system cannot find the file specified.
, errno = 2
```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:193:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:70:16)
#3      ErrorHandlingDirectory.deleteSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:481:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:590:14)
#5      ErrorHandlingDirectory.deleteSync (package:flutter_tools/src/base/error_handling_io.dart:480:12)
#6      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1041:22)
#7      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:985:5)
#8      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:357:5)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:337:7)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
```
```
[✓] Flutter (Channel stable, 3.13.5, on Microsoft Windows [Version 10.0.22631.2715], locale en-US)
    • Flutter version 3.13.5 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (3 months ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\HP\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34024.191
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at C:\Users\HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.2715]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 119.0.6045.200
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 119.0.2151.93

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.2+3
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: adc687823a831bbebe28bdccfac1a628ca621513
### Plugins
device_info_plus-8.2.2
file_picker-5.3.1
file_selector_linux-0.9.2+1
file_selector_macos-0.9.3+3
file_selector_windows-0.9.3+1
firebase_core-2.24.0
firebase_core_web-2.9.0
firebase_messaging-14.7.6
firebase_messaging_web-3.5.15
flutter_image_compress-2.1.0
flutter_image_compress_common-1.0.3
flutter_image_compress_macos-1.0.1
flutter_image_compress_web-0.1.3+2
flutter_local_notifications-13.0.0
flutter_plugin_android_lifecycle-2.0.17
fluttertoast-8.2.4
google_maps_flutter-2.5.0
google_maps_flutter_android-2.6.0
google_maps_flutter_ios-2.3.3
google_maps_flutter_web-0.5.4+2
image_cropper-4.0.1
image_cropper_for_web-2.0.0
image_picker-1.0.4
image_picker_android-0.8.8+2
image_picker_for_web-3.0.1
image_picker_ios-0.8.8+4
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
location-4.4.0
location_web-3.1.1
open_filex-4.3.4
path_provider-2.1.1
path_provider_android-2.2.1
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-10.4.5
permission_handler_android-10.3.6
permission_handler_apple-9.1.4
permission_handler_windows-0.1.3
shared_preferences-2.2.2
shared_preferences_android-2.2.1
shared_preferences_foundation-2.3.4
shared_preferences_linux-2.3.2
shared_preferences_web-2.2.1
shared_preferences_windows-2.3.2
sqflite-2.3.0
url_launcher-6.2.1
url_launcher_android-6.2.0
url_launcher_ios-6.2.1
url_launcher_linux-3.1.0
url_launcher_macos-3.1.0
url_launcher_web-2.2.0
url_launcher_windows-3.1.0

**Comment by danagbemava-nc** [comment] 2023-12-05 08:19
Closing this as a duplicate of https://github.com/flutter/flutter/issues/106953

**Closed by danagbemava-nc** 2023-12-05 08:19 UTC
Labels: in triage
