### ISSUE TITLE
Could not resolve all artifacts for configuration ':classpath'.

### ISSUE THREAD

**Issue by KHALED-LAKEHAL** [flutter/flutter#49782] opened 2020-01-30 11:25 UTC
FAILURE: Build failed with an exception.

                      * What went wrong:
                      A problem occurred configuring root project 'android_device_info'.
                      > Could not resolve all artifacts for configuration ':classpath'.
                         > Could not resolve com.android.tools.build:gradle:3.4.0.
                           Required by:
                               project :
                            > Could not resolve com.android.tools.build:gradle:3.4.0.
                               > Could not get resource
                               'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.0/gra
                               dle-3.4.0.pom'.
                                  > Could not HEAD
                                  'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4.0/
                                  gradle-3.4.0.pom'.
                                     > dl.google.com: Name or service not known
                            > Could not resolve com.android.tools.build:gradle:3.4.0.
                               > Could not get resource
                               'https://jcenter.bintray.com/com/android/tools/build/gradle/3.4.0/gradle-3.4.0.po
                               m'.
                                  > Could not HEAD
                                  'https://jcenter.bintray.com/com/android/tools/build/gradle/3.4.0/gradle-3.4.0
                                  .pom'.
                                     > jcenter.bintray.com: Name or service not known

                      * Try:
                      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to
                      get more log output. Run with --scan to get full insights.

                      * Get more help at https://help.gradle.org

**build.gradle**
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
         maven {
           url 'https://maven.fabric.io/public'
         }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.2'
        classpath 'io.fabric.tools:gradle:1.30.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
           url 'https://maven.fabric.io/public'
         }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
**app/build.gradle**
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
   keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "dz.khaledsoft.kchatter"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

  signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
           storePassword keystoreProperties['storePassword']
       }
   }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            ndk {
                  if (project.hasProperty('target-platform')) {
                        if (project.property('target-platform') == 'android-arm,android-arm64')
                            abiFilters 'armeabi-v7a', 'arm64-v8a'
                        else if (project.property('target-platform') == 'android-arm')
                            abiFilters 'armeabi-v7a'
                        else if (project.property('target-platform') == 'android-arm64')
                            abiFilters 'arm64-v8a'
                    }
                }

        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.1.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.1.1'
}

apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
```

**Comment by iapicca** [comment] 2020-01-31 12:41
Hi @KHALED-LAKEHAL 
if you are experiencing problems using the 3rd party plugin [android_device_info](https://pub.dev/packages/android_device_info)
consider open an issue in the dedicated [github](https://github.com/hush2/android_device_info/issues).

If you are experiencing issues with flutter itself
please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-02-25 10:23
@KHALED-LAKEHAL 
Closing since the issue is probably caused by the third party plugin
if you disagree please write in the comments and I will reopen it
Thank you

**Closed by VladyslavBondarenko** 2020-02-25 10:23 UTC
Labels: waiting for customer response
