### ISSUE TITLE
[BUG-Web] Route animations not working with Pages API

### ISSUE THREAD

**Issue by KristianBalaj** [flutter/flutter#90385] opened 2021-09-20 15:25 UTC
### Actual behavior 

Following code is not displaying transition animations on the web platform. 

In the example `MaterialPageRoute` is defined for the pages, but no material animation is played. When popping a route with a button in the example, there is a little delay after the click until the route pops (it looks like it is delayed by the time of the route animation, but no animation is displayed).

The same behavior is with the `CupertinoPageRoute`. 
Tested also on the iOS platform and the transitions work there properly.

### Expected behavior

All the transition animations should be displayed when using `MaterialPageRoute` for the pages on the web. Or at least, the transition should not be at least delayed when it has no animation.

## Code example

Here is a minimal code example where this can be reproduced using the Pages API. 
There are 4 pages `APage`, `BPage`, `CPage` and `DPage`. These are extending the `Page<void>`.

In the `APage`, there is a nested `Navigator`, where the nested stack can contain `BPage` and `CPage`. 
The root `Navigator` can have`APage` and `DPage` in the stack.

For simple state management of this example, the package `hooks_riverpod: ^0.14.0+4` is used. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: MaterialApp(
        home: Scaffold(
          body: Consumer(
            builder: (context, watch, child) {
              final pushD = watch(pushDPageProvider).state;

              return Navigator(
                pages: [APage(), if (pushD) DPage()],
                onPopPage: (route, dynamic result) {
                  return false;
                },
              );
            },
          ),
        ),
      ),
    );
  }
}

// These are riverpod providers
final pushBPageProvider = StateProvider((_) => false);
final pushDPageProvider = StateProvider((_) => false);

class APage extends Page<void> {
  @override
  Route<void> createRoute(BuildContext context) => MaterialPageRoute(
        settings: this,
        builder: (context) => Scaffold(
          backgroundColor: Colors.blue,
          body: Consumer(
            builder: (context, watch, child) {
              final push = watch(pushBPageProvider).state;

              return Row(
                children: [
                  ElevatedButton(
                    onPressed: () {
                      context.read(pushDPageProvider).state = true;
                    },
                    child: Text(
                      'push D',
                      style: TextStyle(color: Colors.yellow),
                    ),
                  ),
                  Expanded(
                    child: Navigator(
                      pages: [
                        BPage(),
                        if (push) CPage(),
                      ],
                      onPopPage: (route, dynamic result) {
                        return false;
                      },
                    ),
                  ),
                ],
              );
            },
          ),
        ),
      );
}

class BPage extends Page<void> {
  @override
  Route<void> createRoute(BuildContext context) => MaterialPageRoute(
        settings: this,
        builder: (context) => Scaffold(
          backgroundColor: Colors.yellow,
          body: ElevatedButton(
            onPressed: () {
              context.read(pushBPageProvider).state = true;
            },
            child: Text('push C'),
          ),
        ),
      );
}

class CPage extends Page<void> {
  @override
  Route<void> createRoute(BuildContext context) => MaterialPageRoute(
        settings: this,
        builder: (context) => Scaffold(
          backgroundColor: Colors.green,
          body: ElevatedButton(
            onPressed: () {
              context.read(pushBPageProvider).state = false;
            },
            child: Text('pop C'),
          ),
        ),
      );
}

class DPage extends Page<void> {
  @override
  Route<void> createRoute(BuildContext context) => MaterialPageRoute(
        settings: this,
        builder: (context) => Scaffold(
          backgroundColor: Colors.red,
          body: ElevatedButton(
            onPressed: () {
              context.read(pushDPageProvider).state = false;
            },
            child: Text('pop D'),
          ),
        ),
      );
}
```
</details>

<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
    • Flutter version 2.6.0-5.2.pre at /Users/kristian/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (5 days ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kristian/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```

</details>

**Comment by maheshmnj** [comment] 2021-09-21 06:37
Hi @KristianBalaj This is an intended change please see https://github.com/flutter/flutter/issues/82053. This change is also mentioned in the [stable 2.5 release notes](https://flutter.dev/docs/development/tools/sdk/release-notes/release-notes-2.5.0).

However, you can restore the previous behaviour by adding pageTransitionsTheme to MaterialApp. 

 
```dart
MaterialApp(
  theme: ThemeData(
      pageTransitionsTheme: const PageTransitionsTheme(
        builders: <TargetPlatform, PageTransitionsBuilder>{
          TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
          TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
          TargetPlatform.linux: FadeUpwardsPageTransitionsBuilder(),
          TargetPlatform.macOS: CupertinoPageTransitionsBuilder(),
          TargetPlatform.windows: FadeUpwardsPageTransitionsBuilder(),
        },
      )
  )
)
``` 

as [mentioned in the PR](https://github.com/flutter/flutter/pull/82596). 

Closing this issue, Since it is working as intended if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed by maheshmnj** 2021-09-21 06:37 UTC
Labels: in triage

**Comment by KristianBalaj** [comment] 2021-09-23 16:30
Confirming this.

But still, there is one more inconstitency. When making `pop` in the example above, there is some delay before the page is popped after clicking the button.

The delay is like 200 or 300ms.

### Unexpected behaviour
I would expect the pop to be made immediatelly when the transitions are disabled on the web platform, but there is a delay.

**Comment by maheshmnj** [comment] 2021-09-24 05:20
@KristianBalaj you are right there is an open issue for it too and is being tracked here https://github.com/flutter/flutter/issues/88221
