### ISSUE TITLE
Make own IDE For Flutter Instead of Android Studio 

### ISSUE THREAD

**Issue by YahyaAtta** [flutter/flutter#119260] opened 2023-01-26 18:33 UTC
Make own IDE For Flutter Instead of Android Studio 
Contains Design View Drag and Drop
And Backend Codeing

**Comment by stuartmorgan** [comment] 2023-01-26 20:12
Duplicate of https://github.com/flutter/flutter/issues/60001

**Closed by stuartmorgan** 2023-01-26 20:12 UTC
