### ISSUE TITLE
Flutter frame number id provided by engine is not incrementing properly

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#94896] opened 2021-12-08 23:55 UTC
The frame ids included in the FrameTiming api are not incrementing by 1. The ids are incrementing by 2 (2, 4, 6, etc.). This is forcing us (DevTools) to manually divide frame ids by 2 to get the chronological ordering the user expects:
![Screen Shot 2021-12-08 at 3 54 41 PM](https://user-images.githubusercontent.com/43759233/145309840-36dd83e0-444a-48ab-820b-448a183c5b9e.png)

This is a fine workaround, but is not as robust as we'd like.
@iskakaushik

**Comment by jason-simmons** [comment] 2021-12-11 00:19
The frame numbers are not guaranteed to be contiguous.

Each vsync generates a new frame number.  However, not all vsyncs will result in a frame that is rendered on screen and added to the FrameTiming buffer.

If the animator has been producing frames faster than the rasterizer can consume them, then on the next vsync the animator will not immediately produce a new frame.  That vsync's frame number will be skipped in the FrameTiming sequence.

**Comment by dnfield** [comment] 2021-12-13 19:15
IOW - these could potentially increase by more than 2, or they could sometimes increase by 1.

**Comment by chinmaygarde** [comment] 2021-12-13 19:17
Closing this as working as intended. Per the comments above, I would recommended against dividing by 2.

**Closed by chinmaygarde** 2021-12-13 19:17 UTC
Labels: engine, d: devtools, passed first triage
