### ISSUE TITLE
Linux routing_test infra failure

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#83435] opened 2021-05-26 19:48 UTC
I can't tell what actually went wrong here, but it closed the tree.

https://ci.chromium.org/old/p/flutter/builders/prod/Linux%20routing_test/1500

**Comment by godofredoc** [comment] 2021-05-26 20:03
This is a duplicate of https://github.com/flutter/flutter/issues/82836

**Comment by godofredoc** [comment] 2021-05-26 20:05
The issue is that lab's network is not reliable, the bot gets a connection reset-by-peer when grabbing the task and dies.

**Comment by godofredoc** [comment] 2021-05-26 20:05
We'll track the fix in #82836

**Closed by godofredoc** 2021-05-26 20:05 UTC
Labels: P1, team: infra
