### ISSUE TITLE
Formfields in a Form lose values on scroll/kb popup

### ISSUE THREAD

**Issue by rickbsgu** [flutter/flutter#11629] opened 2017-08-15 20:55 UTC
You can see this with the 'Text fields' sub-app in the 'Gallery' app.  Pop up a keyboard, enter values, scroll around.  Happens on iOS and Android.  Hidden/scrolled out fields get set back to their initial value(s).

This seems to be a bug or incomplete implementation.  I would think a normal expectation would be to create the form and whatever values are entered in the fields while the form is active should remain until the form is either submitted or dismissed (or initial values explicitly restored.)  You shouldn't have to do anything out of the ordinary to preserve values through scrolling/keyboard popups or whatever else might inadvertently destroy the fields while using it (the form.)

If otherwise, the demo needs to be beefed up to show how to preserve values through scrolling/hiding/other operations while the form is active.

**Comment by Hixie** [comment] 2017-08-15 21:41
Yup. Dupe of #11500.

**Closed by Hixie** 2017-08-15 21:41 UTC
