### ISSUE TITLE
Sending crash report to Google

### ISSUE THREAD

**Issue by water-cooling** [flutter/flutter#51017] opened 2020-02-19 03:03 UTC
I use fluent run to run demo in China. Direct reporting error
MacBook-Pro:flutterdemo03 humengfan$ flutter run 

Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: Operation
timed out, errno = 60, address = clients2.google.com, port = 49325
Oops; flutter has exited unexpectedly.
 
Crash report written to /var/folders/ss/hlktshs11bs5zw8tt0l4j67m0000gn/T/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
MacBook-Pro:flutterdemo03 humengfan$ flutter run 

Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: Operation
timed out, errno = 60, address = clients2.google.com, port = 51734
Oops; flutter has exited unexpectedly.
Crash report written to /var/folders/ss/hlktshs11bs5zw8tt0l4j67m0000gn/T/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
log
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

FileSystemException: FileSystemException: Failed to set file modification time, path = '/Users/humengfan/Documents/flutterdemo/flutterdemo03/.packages' (OS Error: Operation not permitted, errno = 1)

```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:211:19)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:599:17)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _runZoned (dart:async/zone.dart:1518:10)
#18     runZoned (dart:async/zone.dart:1465:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1502:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1465:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#37     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
#40     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at /Users/humengfan/Documents/flutter_mac/flutter
    [32m•[39m Framework revision 0b8abb4724 (7 days ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m ANDROID_HOME = /Users/humengfan/Library/Android/sdk
      but Android SDK not found at this location.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.1, Build version 11A1027
    [32m•[39m CocoaPods version 1.9.0.beta.2

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.42.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.8.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 11 Pro Max • 89363DBA-C750-4644-BA4D-336283E73638 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by jonahwilliams** [comment] 2020-02-19 03:14
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-19 03:14 UTC
