### ISSUE TITLE
[webview_flutter] unable to load camera

### ISSUE THREAD

**Issue by MinhyukChoi** [flutter/flutter#120769] opened 2023-02-15 08:47 UTC
## Steps to Reproduce

I'm using webview_flutter 4.0.2 version and building on Android.
I want to use the device's camera and audio functions within the webview, but it seems to be throwing an error.

I guess that When I try to use these functions, it seems that an error occurs due to a permission-related problem. Is there any soultions?

Umm... Actually, I know this issue is solved in flutter_inappwebview library.
It seems that androidOnPermissionRequest is probably playing that role.

However, I'm curious if there is a solution to this, so I'm asking.

p.s) All related permission have been written, and when the app is run, permission alert pops up. 
Then I accept the permissions and run next work.

**Actual results:** 

<details>
<summary>Code sample</summary>

    late final PlatformWebViewControllerCreationParams params;
    if (WebViewPlatform.instance is WebKitWebViewPlatform) {
      params = WebKitWebViewControllerCreationParams(
        allowsInlineMediaPlayback: true,
        mediaTypesRequiringUserAction: const <PlaybackMediaTypes>{PlaybackMediaTypes.audio, PlaybackMediaTypes.video},
      );
    } else {
      params = const PlatformWebViewControllerCreationParams();
    }

    webview = WebViewController.fromPlatformCreationParams(params);

    webview!
      ..clearCache()
      ..setBackgroundColor(Colors.amber)
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {},
          onPageStarted: (String url) {
            setState(() {
              EasyLoading.show(status: 'wait...');
            });
          },
          onPageFinished: (String url) {
            setState(() {
              EasyLoading.dismiss();
            });
          },
          onWebResourceError: (WebResourceError error) {},
        ),
      )
      ..loadRequest(Uri.parse(baseurl)});

    if (webview!.platform is AndroidWebViewController) {
      AndroidWebViewController.enableDebugging(true);
      (webview!.platform as AndroidWebViewController).setMediaPlaybackRequiresUserGesture(flase);
    }

```dart
```

</details>

<details>
  <summary>Logs</summary>

I/chromium(20872): [INFO:CONSOLE(2)] "device error: [object DOMException]", source: https://~~~.js

```
[√] Flutter (Channel stable, 3.3.0, on Microsoft Windows [Version 10.0.22621.1105], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.75.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2023-02-15 09:22
Closing this as a duplicate of https://github.com/flutter/flutter/issues/78147.

Kindly subscribe tp the issue linked above for updates. 

Thank you

**Closed by danagbemava-nc** 2023-02-15 09:22 UTC
Labels: in triage
