### ISSUE TITLE
Web debugging - hot restart causes breakpoints to stop working

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#74903] opened 2021-01-28 16:59 UTC
Performing a hot restart causes expression evaluation to stop working and displays an error icon in the breakpoints column:

<img width="371" alt="Screen Shot 2021-01-28 at 8 54 40 AM" src="https://user-images.githubusercontent.com/1145719/106171949-09ce0100-6147-11eb-9c55-758d1f4963db.png">
<img width="582" alt="Screen Shot 2021-01-28 at 8 54 48 AM" src="https://user-images.githubusercontent.com/1145719/106171953-0aff2e00-6147-11eb-857f-8d8d100d1d6f.png">

## Steps to reproduce
- Open counter app
- Set a breakpoint on line 58 (incrementCounter)
- Run app in debug mode
- Tap the plus button
- Observe evaluate expression is working and breakpoints can be enabled / disabled
- Click the Hot Restart button
- Observe that the breakpoint displays an error icon, and expression evaluation doesn't work

**Comment by pedromassangocode** [comment] 2021-01-29 13:56
Issue easily reproducible on Master channel.

![Screen Shot 2021-01-29 at 14 55 32](https://user-images.githubusercontent.com/67424416/106283298-0b302400-6242-11eb-839a-766f8fdfee57.png)


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel master, 1.26.0-18.0.pre.73, on macOS 11.1 20C69 darwin-x64, locale en)
    • Flutter version 1.26.0-18.0.pre.73 at /Users/pedromassango/Code/flutter_master
    • Framework revision 791edc230d (55 minutes ago), 2021-01-28 21:54:03 -0800
    • Engine revision 4ba79a34a0
    • Dart version 2.12.0 (build 2.12.0-272.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 88.0.4324.96

! Doctor found issues in 1 category.
```

</details>

**Comment by annagrin** [comment] 2021-04-09 00:58
This should be fixed now, see https://github.com/dart-lang/sdk/issues/45266

**Comment by johnpryan** [comment] 2021-04-09 17:17
Expression evaluation works now on the master channel, but the breakpoint still displays an error icon after a restart:

<img width="132" alt="Screen Shot 2021-04-09 at 10 16 11 AM" src="https://user-images.githubusercontent.com/1145719/114217246-c51bce80-991c-11eb-9853-24d94ffa0e68.png">

**Comment by annagrin** [comment] 2021-04-12 19:45
I can repro that on hello_world example, looks like some extensions are being called before isolate has restarted. Will look into that, and keep this thread posted.

**Comment by annagrin** [comment] 2021-04-15 01:18
It looks like this issue has several components. I suspect that disabled breakpoints are part of the same
collection of issues:

- VM Service API implemented by dwds do not wait for the new isolate initialization to complete before doing work.

- If the application is paused on start, devtools is not waiting for `kIsolateStarted` event to update the current
  isolate ID and starts re-registering service extensions with an old isolate ID. Those registrations fail and cause
  the exception message in the VSCode debug console. The failed extensions, such as  the ones used in the 
  layout explorer, do not work as a result. 

I managed to make changes in dwds and potential changes in devtools that work together, will need to have a few
checkins to resolve this.

@kenzieschmoll I had to make following changes in devtools for extensions to register after hot restart, both
for devtools run by dart-code, and devtools run manually  and attached to a paused app:

https://github.com/flutter/devtools/pull/2909

It needs my dwds changes above to work. Does it seem like a bug in devtools? It can be easier to work on this 
after my current dwds changes propagate to flutter though. I will create a devtools  issue as soon as it happens.

**Comment by kenzieschmoll** [comment] 2021-04-15 17:57
Left a couple comments on the CL. Tagging @jacob314 for your input here as you've worked with this code quite a bit, too.

**Comment by jacob314** [comment] 2021-04-19 17:01
DevTools should never be registering service extensions until it is notified by the VM that the service extensions are available. Sounds like you have caught a bug and some of the logic in the ServiceManager needs to be made more robust. In particular, we need to do a better job of more stopping async work for isolates that are no longer the default.

@annagrin can you tell me more about your repro case. Are you triggering hot-restart while the app is paused on startup or are you letting the app run and then hitting hot restart?

**Comment by annagrin** [comment] 2021-04-20 18:20
@jacob  let's wait until dwds is updated in flutter_tools with the latest fixes so we an have an easy repro (if it still there).

I am going to hand this off to @grouma - here is what I discovered so far:

What happens here is that flutter app is not run yet fully when it is stopped at a breakpoint, so extensions added in flutter libraries are not added to the VMService yet. When dwds hot restarts, it has to first resume  and then restart, causing all the extensions to be added for the terminating isolate, and VSCode happens to receive them after the old isolate terminated - therefore failing to run them with the outdated isolate id:

https://github.com/Dart-Code/Dart-Code/blob/7a270e1f3f0b32f3a0037fc4d73e99ffa4c832f9/src/extension/flutter/vm_service_extensions.ts#L99

I suspect this is at least a contributing issue to IntelliJ losing breakpoints as well.

Potential solutions:

- All subscribers to the Isolate stream should ignore kServiceExtensionAdded events for old isolates. That means they need to track the isolate exit and start events and have some state machinery around it. @DanTup would it be possible to do this in dart-code? @jacob314 I think devtools is already doing this, so hopefully only dart-code would need to be changed, but I am not sure if running an app and adding extensions for exiting isolate will cause a problem in other parts of flutter and flutter tools.

- Alternatively, dwds does not run the app before restarting. I tried that but discovered that restart does not complete in that case - I found that flutter engine extension call to "ext.flutter.disassemble" never completes (@jonahwilliams - I appreciate hints if you know why), and await calls in the injected client do not complete either. @grouma is it because the app is stopped and injected client runs a part of it? Is it possible to make it run while the app has stopped at all?

Engine callback not finishing:
https://github.com/dart-lang/webdev/blob/699fd191cfa2fd3674f0a887520c0a2df3fd9d70/dwds/web/reloader/require_restarter.dart#L107

Getting digests not finishing:
https://github.com/dart-lang/webdev/blob/699fd191cfa2fd3674f0a887520c0a2df3fd9d70/dwds/web/reloader/require_restarter.dart#L112

**Comment by DanTup** [comment] 2021-04-20 18:35
> All subscribers to the Isolate stream should ignore kServiceExtensionAdded events for old isolates. That means they need to track the isolate exit and start events and have some state machinery around it. @DanTup would it be possible to do this in dart-code?

It the serviceExtensionAdded events come through in the stream _before_ the isolateExit event, I'm not sure we'd be able to do this (though if we did, I think there's always a potential race where the isolate _wasn't_ exiting when we got the event, but _was_ before we then tried to call the service?).

Would it be better to handle the failures gracefully (the VM/proxy can reject them, and then the editors will pick up the events for the new isolate)?

**Comment by annagrin** [comment] 2021-04-20 18:37
@dantup they arrive to dart-code after the exit in this bug, there should not be a problem with calling the extensions before the isolate exit even if the program is restarting.

**Comment by annagrin** [comment] 2021-04-20 19:10
@dantup I think this is working, thanks for the suggestion! Devtools shows a WIP error on hot restart but still works, we can investigate the issue later. Will send a fix to dwds.

**Comment by annagrin** [comment] 2021-04-21 01:07
@jwren @helin24 I appreciate your advice and help here.

I am still seeing disabled breakpoints after hot restart. I added some prints and it looks like IntelliJ plugin calls `addBreakpointWithScriptUri` after hot restart, which fail because dwds re-establishes breakpoints after hot restart.

**Comment by annagrin** [comment] 2021-04-21 19:41
Found the problem - we have a difference between VM and ChromeProxyService in how they handle adding breakpoints  multiple times. Will submit a fix to dwds soon.

**Comment by helin24** [comment] 2021-04-22 16:13
@annagrin will your fix also address this issue from intellij? https://github.com/flutter/flutter-intellij/issues/5128 This was posted a while ago but I just realized it's probably related.

**Comment by annagrin** [comment] 2021-04-22 17:00
@helin24 it does seem so on my mac. I need to do some setup on windows to verify that it works for that particular issue, will let you know what comes out of it.

**Comment by annagrin** [comment] 2021-04-22 18:19
@helin24 yes:)

**Comment by helin24** [comment] 2021-04-22 18:51
@annagrin thanks for checking! I'll mark that other one as a duplicate so it'll get closed when this one is closed.

**Comment by jonahwilliams** [comment] 2021-04-28 18:36
Fixed dwds has rolled in via https://github.com/flutter/flutter/pull/81403

**Closed by jonahwilliams** 2021-04-28 18:36 UTC
Labels: d: intellij, debugging_web, found in release: 1.26, has reproducible steps, tool
