### ISSUE TITLE
[Impeller] Mask blur with sigma <= 0 renders incorrectly on iOS

### ISSUE THREAD

**Issue by GManzke** [flutter/flutter#138842] opened 2023-11-21 20:30 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Use a physical iOS device (with version 16+);
2. Use provided dart code;
3. Run the application on a physical iOS device to observe the issue.

### Expected results

No shadows and no square borders/background.

### Actual results

When an elevation of 0 is set for the RoundSliderThumbShape on iOS, a square white background appears around the thumb, contrary to the expected outcome of having no background/shadow. This only happens on a physical device and only happens at elevation 0.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(const SliderApp());

class SliderApp extends StatelessWidget {
  const SliderApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: SliderExample(),
    );
  }
}

class SliderExample extends StatefulWidget {
  const SliderExample({super.key});

  @override
  State<SliderExample> createState() => _SliderExampleState();
}

class _SliderExampleState extends State<SliderExample> {
  double _currentSliderValue = 20;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Slider')),
      backgroundColor: Colors.red,
      body: SliderTheme(
        data: const SliderThemeData(
          thumbShape: RoundSliderThumbShape(
            enabledThumbRadius: 32,
            elevation: 0,
          ),
        ),
        child: Slider(
          value: _currentSliderValue,
          max: 100,
          divisions: 5,
          label: _currentSliderValue.round().toString(),
          onChanged: (double value) {
            setState(() {
              _currentSliderValue = value;
            });
          },
        ),
      ),
    );
  }
}

```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![IMG_3436BF1AADBE-1](https://github.com/flutter/flutter/assets/52476927/3184e9ed-2395-46ab-b542-1a3b7effe1e0)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.9, on macOS 14.1.1 23B81 darwin-arm64, locale pt-BR)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current
      Flutter SDK checkout at /Users/gabriel.manzke/fvm/versions/3.13.9. Consider adding
      /Users/gabriel.manzke/fvm/versions/3.13.9/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
[✓] IntelliJ IDEA Community Edition (version 2023.2.5)
[✓] VS Code (version 1.82.3)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by danagbemava-nc** [comment] 2023-11-22 10:13
Reproducible using the code sample provided above. 

It does not appear to reproduce with SKIA. 


| IMPELLER | SKIA | 
| -- | -- |
| <video src="https://github.com/flutter/flutter/assets/88313112/ca804c15-f0e4-4939-8b0e-3af6bbbac1c3" /> | <video src="https://github.com/flutter/flutter/assets/88313112/91c8ce89-045c-49ab-af89-689f499321bc" /> |

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-GB)
    • Flutter version 3.16.0 on channel stable at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (7 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.1.1 21B91
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1 21B74
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

```
[!] Flutter (Channel master, 3.17.0-13.0.pre, on macOS 14.1.1 23B81 darwin-arm64, locale en-GB)
    • Flutter version 3.17.0-13.0.pre on channel master at /Users/nexus/dev/sdks/flutters
    ! Warning: `flutter` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/nexus/dev/sdks/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/nexus/dev/sdks/flutters. Consider adding /Users/nexus/dev/sdks/flutters/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b6ef78e955 (29 hours ago), 2023-11-20 23:37:25 -0500
    • Engine revision 70b1c73412
    • Dart version 3.3.0 (build 3.3.0-152.0.dev)
    • DevTools version 2.30.0-dev.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc1)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0-rc1
    • Java binary at: /Users/nexus/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode-15.0.0-Release.Candidate.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/nexus/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/nexus/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (4 available)
    • Nexus (mobile)       • 00008020-001875E83A38002E • ios            • iOS 17.1.1 21B91
    • Dean’s iPad (mobile) • 00008103-000825C811E3401E • ios            • iOS 17.1 21B74
    • macOS (desktop)      • macos                     • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 119.0.6045.159

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```
</details>

**Comment by meloalex** [comment] 2023-11-24 09:46
I have the same issue, it can be easily reproduced 🥲

**Comment by jonahwilliams** [comment] 2023-11-25 00:52
I can reproduce this everytime we create an RREct blur fast path with a Sigma <= 0. which would be this path: https://github.com/flutter/engine/blob/main/impeller/entity/shaders/rrect_blur.frag#L79 

I'm not sure if this is a regression, or a floating point precision issue, or we should be dropping these blurs instead. At 0 elevation there should be no visible shadow.

**Comment by jonahwilliams** [comment] 2023-11-27 18:59
FYI @bdero , elevation of zero should create no shadow as far as I know. but when the rrect_blur shader runs with a sigma of zero, we get these weird artifacts. I'm not sure what the intention of that code in the shader is, or what that is intended to look like - but dropping the mask blur at 0 matches the Skia implementation.

**Comment by jonahwilliams** [comment] 2023-11-27 21:25
This regressed with Wide gamut. With "normal" gamut we don't show any elevation, with wide gamut the rendering is incorrect. I think we've hit issues like this before on the gaussian but I don't remember what the resolution was.

**Comment by bdero** [comment] 2023-11-28 18:26
This sounds like another case of NaNs being returned from a shader. The Metal driver maps NaNs to zero for attachments with a uint format, but maps NaNs to a negative number for attachments with a float format (like that which we use for wide gamut).

**Comment by chinmaygarde** [comment] 2023-11-30 23:53
Fixed in https://github.com/flutter/engine/pull/48457

**Closed by chinmaygarde** 2023-11-30 23:53 UTC
Labels: platform-ios, engine, has reproducible steps, P1, e: impeller, team-engine, triaged-engine, found in release: 3.16, found in release: 3.17
