### ISSUE TITLE
[web]  image stutters when resizing.

### ISSUE THREAD

**Issue by NicTanghe** [flutter/flutter#33941] opened 2019-06-05 20:47 UTC
##Discription

image stutters when resizing window.
Image is not cropping or moving.

( i know i should just css + html for something like this but meh)

##gif
https://giphy.com/gifs/cnujHKXj66ghQM8CHf/html5

## Steps to Reproduce

``` Dart
@override
  Widget build(BuildContext context) {
    return Stack(
      children: <Widget>[
        Image.asset("monokimonoXL.jpg",
        fit: BoxFit.cover,),
        Row(
          children: <Widget>[
            Container(
              width: 400,
            ),
            
            Column(
              children: <Widget>[
                Expanded(
                  flex: 1,
                  child: Container(),
                ),
                Text(
                  "monokimono",
                  style:
                
                   TextStyle(
                    fontFamily: "title1",
                    fontSize: 100,
                    color: Colors.white70,
                  ), 
                ),
                Expanded(
                  flex:4,
                  child: Container(),
                ),
              ],
            ),
            Expanded(
              flex: 4,
              child: Container(),
            )
          ],
        )
      ],
    );
```

**Comment by kenthinson** [comment] 2019-06-05 21:57
@NicTanghe I cant reproduce on my machine. Maybe upload your project so it can be downloaded and tested?

**Comment by NicTanghe** [comment] 2019-06-12 23:00
You can find evrything at 
https://github.com/NicTanghe/nictanghe.github.io
hosted is nictanghe.github.io

**Comment by NicTanghe** [comment] 2020-03-18 13:55
Jeah the link i provided is no longer working becouse i updated the site and now it's broke.

**Comment by darshankawar** [comment] 2020-10-23 10:16
@NicTanghe 
Tried your code sample on latest dev and was able to see the image being resized and moved as I resized the window. Didn't notice any stutter / shake while doing it.

[33941.mov.zip](https://github.com/flutter/flutter/files/5428827/33941.mov.zip)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, 1.24.0-1.0.pre, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.24.0-1.0.pre at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 12bea61c29 (8 days ago), 2020-10-14 15:57:04 -0700
    • Engine revision 069b3cf8f0
    • Dart version 2.11.0 (build 2.11.0-218.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (4 available)
    • SM A260G (mobile) • 5200763ebcfa861f • android-arm    • Android 8.1.0 (API
      27)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.4
      19E2269 darwin-x64
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      86.0.4240.111

• No issues found!

```

</details>

Based on the code sample you shared earlier (which now works) and since the link to your project isn't working, I am going ahead and closing this as fixed. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-10-23 10:16 UTC
Labels: P4, engine, platform-web, severe: performance, severe: rendering
