### ISSUE TITLE
[tool_crash] RangeError (index): Index out of range: no indices are valid: 0

### ISSUE THREAD

**Issue by shrutipanjwani** [flutter/flutter#60765] opened 2020-07-02 12:05 UTC
I have this error. I'm trying to solve this but cannot. Please tell me the solution anyone.
The Error is :--
Oops; flutter has exited unexpectedly: "RangeError (index): Index out of range: no indices
are valid: 0".
A crash report has been written to C:\Users\DELL\Downloads\flutter\flutter_20.log
[flutter_20.log](https://github.com/flutter/flutter/files/4864066/flutter_20.log)

## command

flutter doctor

## exception

IndexError: RangeError (index): Index out of range: no indices are valid: 0

```
#0      _Uint8ArrayView.[] (dart:typed_data-patch/typed_data_patch.dart:3932:7)
#1      InputStream.readUint16 (package:archive/src/util/input_stream.dart:206:22)
#2      GZipDecoder._readHeader (package:archive/src/gzip_decoder.dart:89:29)
#3      GZipDecoder.decodeBuffer (package:archive/src/gzip_decoder.dart:26:5)
#4      GZipDecoder.decodeBytes (package:archive/src/gzip_decoder.dart:17:12)
#5      _WindowsUtils.verifyGzip (package:flutter_tools/src/base/os.dart:352:21)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:605:20)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:638:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:604:12)
#9      CachedArtifact._downloadZippedTarball (package:flutter_tools/src/cache.dart:630:12)
#10     GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:1070:12)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:560:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:432:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:698:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:620:33)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1184:13)
#18     _CustomZone.run (dart:async/zone.dart:1077:19)
#19     _runZoned (dart:async/zone.dart:1619:10)
#20     runZoned (dart:async/zone.dart:1539:10)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#22     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:610:20)
#23     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#24     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _runZoned (dart:async/zone.dart:1619:10)
#30     runZoned (dart:async/zone.dart:1539:10)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#32     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#33     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#34     new Future.sync (dart:async/future.dart:224:31)
#35     CommandRunner.run (package:args/command_runner.dart:112:14)
#36     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#37     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#38     _rootRun (dart:async/zone.dart:1184:13)
#39     _CustomZone.run (dart:async/zone.dart:1077:19)
#40     _runZoned (dart:async/zone.dart:1619:10)
#41     runZonedGuarded (dart:async/zone.dart:1608:12)
#42     runZoned (dart:async/zone.dart:1536:12)
#43     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#44     run.<anonymous closure> (package:flutter_tools/runner.dart)
#45     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:64:18)
<asynchronous suspension>
#46     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#47     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#48     _rootRun (dart:async/zone.dart:1184:13)
#49     _CustomZone.run (dart:async/zone.dart:1077:19)
#50     _runZoned (dart:async/zone.dart:1619:10)
#51     runZoned (dart:async/zone.dart:1539:10)
#52     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#53     runInContext (package:flutter_tools/src/context_runner.dart:67:24)
#54     run (package:flutter_tools/runner.dart:48:10)
#55     main (package:flutter_tools/executable.dart:69:9)
#56     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#57     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#58     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 6.1.7601], locale en-IN)
    • Flutter version 1.17.4 at C:\Users\DELL\Downloads\flutter
    • Framework revision 1ad9baa8b9 (2 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\DELL\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions.

[✓] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

</details>

My Code is here
[sss.txt](https://github.com/flutter/flutter/files/4864094/sss.txt)

<details>
 <summary>code</summary>

```
import 'package:flutter/material.dart';

void main(){
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: HomePage(),
    )
  );
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(
        backgroundColor: Colors.yellowAccent,
        title: Text('Style On'),
        actions: <Widget>[
          new IconButton(icon: Icon(Icons.search , color: Colors.white,), onPressed: (){}),
          new IconButton(icon: Icon(Icons.shopping_cart , color: Colors.white,), onPressed: (){}),
        ],
      ),
      drawer: new Drawer(
        child: new ListView(
          children: <Widget>[
//            header
          new UserAccountsDrawerHeader(
              accountName: Text('Style On'),
              accountEmail: Text('shrutipanjwani13@gmail.com'),
          currentAccountPicture: GestureDetector(
            child: new CircleAvatar(
              backgroundColor: Colors.grey,
              child: Icon(Icons.person, color: Colors.white,),
            ),
          ),),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-07-02 12:41
Hi @shrutipanjwani 
Are you hitting the error on every run?

Duplicate of https://github.com/flutter/flutter/issues/48014

**Comment by shrutipanjwani** [comment] 2020-07-02 18:11
hey @VladyslavBondarenko 
Yes It's hitting error in each run. It is like I run "flutter clean" then also it is showing this and when I run "flutter analyze" then also this error is showing. 
I am using DELL-PC.

**Comment by VladyslavBondarenko** [comment] 2020-07-03 07:32
@shrutipanjwani I meant android device / emulator)

I see in your log

> Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions.

does the error persist after installing Android SDK Tools and accepting licenses? https://github.com/flutter/flutter/issues/51712#issuecomment-600394582

**Comment by shrutipanjwani** [comment] 2020-07-03 07:52
@VladyslavBondarenko  Oh , I am using Samsung Galaxy Tab 3V.
Yes After Installing and updating Android Sdk tools and accepting the licenses , the error persists !

**Comment by jmagman** [comment] 2020-07-29 21:46
Duplicate of https://github.com/flutter/flutter/issues/48014.

**Closed by jmagman** 2020-07-29 21:46 UTC
Labels: platform-android, platform-windows, severe: crash, severe: fatal crash, tool
