### ISSUE TITLE
O compilador da Web falhou ao compilar o aplicativo flutter existente

### ISSUE THREAD

**Issue by maitemedina** [flutter/flutter#121516] opened 2023-02-27 10:05 UTC
Obs: Se usar o compilador mobile ele funciona normalmente.

![image](https://user-images.githubusercontent.com/67907249/221531690-2562a3e8-c2df-42b9-a351-df51269f4897.png)
![image](https://user-images.githubusercontent.com/67907249/221533333-ab27f532-71db-4d06-b0aa-e3f3e6fdeaed.png)
![image](https://user-images.githubusercontent.com/67907249/221532025-df328983-c7ba-4855-8e6e-e7a7be101b03.png)
![image](https://user-images.githubusercontent.com/67907249/221532178-e9fe4fef-7981-4c33-9fa1-4daec2f9bdb9.png)

**Comment by huycozy** [comment] 2023-02-27 15:08
@maitemedina 
From what I can see, the issue is related to a 3rd party plugin (https://pub.dev/packages/lists) rather than to Flutter itself. And it's discontinued now. You may try asking this on StackOverflow for solutions if any.

Closing, as this isn't an issue with Flutter itself. Next time when you open another new issue, please provide the information in text format instead of a screenshot for better readability. Thanks!

**Closed by huycozy** 2023-02-27 15:08 UTC
Labels: in triage
