### ISSUE TITLE
Cant start Alice HTTP Inspector. Please add NavigatorKey to your application 

### ISSUE THREAD

**Issue by jigarparmar21** [flutter/flutter#59979] opened 2020-06-22 11:19 UTC
navigatorKey has already been added to the code, still it shows error(red line) under the navigatorKey. i have already run the only individual alice inspector and it works fine. but i want to integrate alice inspector in my existing code  for tracking of http calls. 

@override
Widget build(BuildContext context) {
return WillPopScope(
navigatorKey: _alice.getNavigatorKey(),
child: Theme(
data: ThemeData(
brightness: Brightness.light,
primarySwatch: AppColor.appColor,
primaryColor: AppColor.white,
buttonTheme: ButtonThemeData().copyWith(
buttonColor: AppColor.appColor,
textTheme: ButtonTextTheme.primary),
fontFamily: "EncodeSans",
),
child: layout()),

onWillPop: () {
  return handleBackPress();
});
}

**Comment by iapicca** [comment] 2020-06-22 12:44
duplicate of https://github.com/flutter/flutter/issues/59972

**Closed** 2020-06-22 12:48 UTC
