### ISSUE TITLE
Renaming folder starting with dot will cause Flutter Android toolchain to recreate unexpected folder in `build/app/intermediates`

### ISSUE THREAD

**Issue by r2d2Proton** [flutter/flutter#157164] opened 2024-10-18 15:57 UTC
### Steps to reproduce

Create project. Rename top-level folder. Run the build.

### Expected results

Not expecting recreation of old folders. Expected the toolchain to honor my naming.

### Actual results

 I was asked by the team to rename my folder from .r2d2Proton to r2d2Proton and try the Impeller process again. Ran into the same issue though. But Flutter, Dart, and the build tools apparently did not appreciate my efforts. It recreated .r2d2Proton\logo_animations folder. All the subfolders are empty. Made sure the project was closed in VSCode. Deleted the unwanted folder and tried again. The problem appears to have not occurred again. Take that with a grain of salt.

The unwanted created folder structure:

E:\Dev\Repos\\.r2d2Proton\logo_animations\build\app\intermediates\flutter\debug\flutter_assets
	fonts
		--- empty ---
	packages
		cupertino_icons
			assets
				--- empty ---
	shaders
		--- empty ---

![RenamingFolders](https://github.com/user-attachments/assets/bedd890d-c4ee-479f-88b0-f26f93e38595)
![RenamingFolders-02](https://github.com/user-attachments/assets/0e03c4c7-ac6b-46bc-b450-85fb688e601c)
![RenamingFolders-03](https://github.com/user-attachments/assets/6f570ced-d9a0-4572-a86d-f300935eb63e)

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-10-21 06:43
Hi @r2d2Proton 

>rename my folder from .r2d2Proton to r2d2Proton and try the Impeller process again

Which exact command did you execute with Impeller? Does the issue only occur when Impeller is enabled? Please share the step-by-step reproduction that will help to make the issue more clearly. 

I tried this on my end but couldn't reproduce the issue on a newly created Flutter project with the following commands (the `demo` folder is not recreated)

```console
flutter create demo
cd demo
mkdir logo_animations
cd ..
ren "demo" "demo_renamed"
cd demo_renamed
flutter build apk
```

Also, please provide the output of `flutter doctor -v`. Thanks!

**Comment by r2d2Proton** [comment] 2024-10-23 00:08
@huycozy My apologies for the late response. I am new to Flutter/Dart. I do not know any other commands. I believe the following commands were executed from a VS 2022 Developer prompt:

flutter config --enable-native-assets
flutter clean
flutter run -d 1322224009825 --enable-impeller --verbose

I read through some of the impeller documentation, slowly coming up to speed with its architecture. I am excited to learn the ins and outs of it. It looks good. Made sense. At the moment I am trying to finish a project that I need a good, reliable demo to show our attorney. Hopefully, I can be done within 30 to 45 days. Maybe not the best Flutter practices but a reliable demo/product that can be shown. Once I am passed this point, I will have more time to thoroughly study the build tools and code.

Is this the correct command to start impeller? I tried for my Android Pixel 7 Pro phone, and an NVIDIA SHIELD based on Android. My understanding impeller is not ready for Windows. The targets are decent Android devices. Please let me know if you need anything else. As for the gpu_test project, I will rename the shaders.shaderbundler.json to the same name used in the document.

**Comment by huycozy** [comment] 2024-10-23 05:51
>Is this the correct command to start impeller?

Yes, it is. But I don't think this issue is related to Impeller. Can you retry reproducing the issue without Impeller being involved? (build or run without Impeller: replace `--enable-impeller` to `--no-enable-impeller`).
This is more likely a Flutter tool issue instead, I think. Flutter tool takes care of stuff for command line (create, run, build, test..).

If you persist with this issue, please help to make it more clearly. I wonder how did you create the original project with a name started with dot `.r2d2Proton`. I tried on my end with a name like ` .abc` but it will display an error like this:

```console
C:\Users\ADMIN\Desktop>flutterm create .abc --platforms=android
".abc" is not a valid Dart package name.

The name should consist of lowercase words separated by underscores, "like_this". Use only basic Latin letters and Arabic digits: [a-z0-9_], and ensure the
name is a valid Dart identifier (i.e. it does not start with a digit and is not a reserved word).

See https://dart.dev/tools/pub/pubspec#name for more information.
```

Can you please also provide output of `flutter doctor -v`? Thanks!

**Comment by r2d2Proton** [comment] 2024-10-24 15:55
Yes, the --no-enable-impeller created a beautiful image:

![NoEnableFlutter-01](https://github.com/user-attachments/assets/655124d2-1886-4896-971b-7ca6a6ab2457)

Anxious to test the performance of no impeller support with my main app :D . . . Not sure if the bellow Access denied are important:

E:\Dev\Repos\r2d2Proton\defult_counter_app>flutter run --no-enable-impeller
Launching lib\main.dart on SHIELD Android TV in debug mode...
Running Gradle task 'assembleDebug'...                              4.4s
✓ Built build\app\outputs\flutter-apk\app-debug.apk
Syncing files to device SHIELD Android TV...                        50ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on SHIELD Android TV is available at: http://127.0.0.1:53806/yWUtKXUy-8s=/
I/Choreographer( 8635): Skipped 191 frames!  The application may be doing too much work on its main thread.
D/View    ( 8635): com.nvidia.immediateInput = false
D/View    ( 8635): com.nvidia.mRawCursorInputRequested = false
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_ASYNC"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_ASYNC"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_ASYNC"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_LOGFPS"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_PROCESS_NAME"
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_FPSDYNAMIC"
I/Gralloc4( 8635): mapper 4.x is not supported
W/Gralloc3( 8635): mapper 3.x is not supported
E/libc    ( 8635): Access denied finding property "ro.vendor.sys.NV_DECOMPRESSION"
The Flutter DevTools debugger and profiler on SHIELD Android TV is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:53806/yWUtKXUy-8s=/
W/libc    ( 8635): invalid pthread_t (0) passed to pthread_join
I/Choreographer( 8635): Skipped 42 frames!  The application may be doing too much work on its main thread.
D/ProfileInstaller( 8635): Installing profile for com.example.defult_counter_app

**Comment by r2d2Proton** [comment] 2024-10-24 17:00
@huycozy Testing with my main app. The performance with --no-impeller-enabled is impressive. Addicting. My desktop (Windows 11) I has two HD monitors. Watching our app on that great beautiful 4K TV brings all smiles :) :) :)

**Comment by huycozy** [comment] 2024-10-25 05:20
>Not sure if the bellow Access denied are important:

It seems to come from C standard libraries. I'm unsure if it's related to Flutter or not. If you think it's a bug and can impact to Flutter app, please file a separate issue to track that issue better.

For the original issue here (`recreation of old folders`), please help to clarify information in my comment [above](https://github.com/flutter/flutter/issues/157164#issuecomment-2430970737), thanks!

**Comment by r2d2Proton** [comment] 2024-10-25 16:13
@huycozy My development directory existed for years, on my desktop, long before using flutter. "E:\Dev\Repos\.r2d2Proton". All the flutter commands were executed, performed, under a Visual Studio 2022 Developer Command prompt:

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.11.4
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
E:\Dev\Repos\.r2d2Proton>

I am not sure about your statement regarding flutter create .abc. That I did not try.

But I just created a .test directory under my E:\Dev\Repos directory and ran another test that works. Now try renaming .test to test and try the build:

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.11.4
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************

E:\Dev\Repos\.test>flutter create an_app
Creating project an_app...
Resolving dependencies in `an_app`...
Downloading packages...
Got dependencies in `an_app`.
Wrote 130 files.

All done!

**Comment by huycozy** [comment] 2024-10-28 06:10
I can reproduce this issue with the following steps:

1. flutter create demo
2. Change folder name `demo` to `.demo`
3. cd .demo and run `flutter build apk`
5. Change folder name `.demo` back to `demo`
6. cd demo and run `flutter build apk` again
Notice that `.demo` folder is created here outside (same level as `demo` folder), see screenshot for the generated folder tree.

```console
├── .demo
│   └── build
│       └── app
│           └── intermediates
├── demo
│   ├── build
│   │   └── app
│   │       ├── generated
│   │       ├── intermediates
│   │       ├── kotlin
│   │       ├── kotlinToolingMetadata
│   │       ├── outputs
│   │       └── tmp
```

### Triage report
- This happens on both Windows and macOS host machines. I haven't checked on Linux host but I think the same result there.
- Tested with Android/MacOS/Windows app as build target:
    - Android build: issue is reproduced
    - MacOS and Windows build: can't trigger build after renaming Flutter project directory (if I already triggered a build before renaming) as there are different errors on each platform that are not related to this issue. I assume the reported issue is not reproduced here on these target builds.

<details>
<summary>Flutter versions (stable and master)</summary>

```console
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-x64, locale en-VN)
    • Flutter version 3.24.4 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 603104015d (12 hours ago), 2024-10-24 08:01:25 -0700
    • Engine revision db49896cf2
    • Dart version 3.5.4
    • DevTools version 2.37.3
```

```console
[!] Flutter (Channel master, 3.27.0-1.0.pre.231, on macOS 15.0.1 24A348 darwin-x64, locale en-VN)
    • Flutter version 3.27.0-1.0.pre.231 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    ! Warning: `flutter` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/huynq/Documents/GitHub/flutter/bin/dart, which is not inside your current Flutter SDK checkout at /Users/huynq/Documents/GitHub/flutter_master. Consider adding /Users/huynq/Documents/GitHub/flutter_master/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41b362b12c (22 minutes ago), 2024-10-24 22:59:25 -0400
    • Engine revision b1c2ba8c4d
    • Dart version 3.7.0 (build 3.7.0-65.0.dev)
    • DevTools version 2.40.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.
```
</details>

**Comment by bkonyi** [comment] 2024-10-29 18:34
@christopherfujino seems to think that this could be an issue with a cache not being invalidated. Does this work correctly if you run a `flutter clean` first?

**Comment by yaakovschectman** [comment] 2024-10-29 18:47
From triage: Closing, running `flutter create` multiple times after modifying the folder structure is not an intended use case.

You can try to run `find . -type f | xargs grep -e "*r2d2Proton*"` to find references to the previous folder name if you would like to try to manually modify your project.

**Closed by yaakovschectman** 2024-10-29 18:47 UTC
Labels: platform-android, waiting for customer response, tool, a: build, has reproducible steps, team-android, fyi-tool, found in release: 3.24, found in release: 3.27
