### ISSUE TITLE
[tool] Crash w/ error: "Oops; flutter has exited unexpectedly..."

### ISSUE THREAD

**Issue by jt112** [flutter/flutter#55865] opened 2020-04-28 16:22 UTC
when I create new flutter application via 
command : `flutter create jt`

```bash
Sending crash report to Google.
Crash report sent (report ID: 8ea875864d8716e5)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Windows\System32\flutter_12.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by jt112** [comment] 2020-04-28 16:28
when I create new flutter application via 
command : flutter create jt

Sending crash report to Google.
Crash report sent (report ID: 8ea875864d8716e5)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Windows\System32\flutter_12.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by jt112** [comment] 2020-04-28 16:46
C:\Windows\System32>flutter create hello_world
Creating project hello_world... androidx: true
  hello_world\.gitignore (created)
  hello_world\.idea\libraries\Dart_SDK.xml (created)
  hello_world\.idea\libraries\Flutter_for_Android.xml (created)
  hello_world\.idea\libraries\KotlinJavaRuntime.xml (created)
  hello_world\.idea\modules.xml (created)
  hello_world\.idea\runConfigurations\main_dart.xml (created)
  hello_world\.idea\workspace.xml (created)
  hello_world\.metadata (created)
  hello_world\android\app\build.gradle (created)
  hello_world\android\app\src\main\kotlin\com\example\hello_world\MainActivity.kt (created)
  hello_world\android\build.gradle (created)
  hello_world\android\hello_world_android.iml (created)
  hello_world\android\.gitignore (created)
  hello_world\android\app\src\debug\AndroidManifest.xml (created)
  hello_world\android\app\src\main\AndroidManifest.xml (created)
  hello_world\android\app\src\main\res\drawable\launch_background.xml (created)
  hello_world\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  hello_world\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  hello_world\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  hello_world\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  hello_world\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  hello_world\android\app\src\main\res\values\styles.xml (created)
  hello_world\android\app\src\profile\AndroidManifest.xml (created)
  hello_world\android\gradle\wrapper\gradle-wrapper.properties (created)
  hello_world\android\gradle.properties (created)
  hello_world\android\settings.gradle (created)
  hello_world\ios\Runner\AppDelegate.swift (created)
  hello_world\ios\Runner\Runner-Bridging-Header.h (created)
  hello_world\ios\Runner.xcodeproj\project.pbxproj (created)
  hello_world\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (created)
  hello_world\ios\.gitignore (created)
  hello_world\ios\Flutter\AppFrameworkInfo.plist (created)
  hello_world\ios\Flutter\Debug.xcconfig (created)
  hello_world\ios\Flutter\Release.xcconfig (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (created)
  hello_world\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (created)
  hello_world\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (created)
  hello_world\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (created)
  hello_world\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (created)
  hello_world\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (created)
  hello_world\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (created)
  hello_world\ios\Runner\Base.lproj\LaunchScreen.storyboard (created)
  hello_world\ios\Runner\Base.lproj\Main.storyboard (created)
  hello_world\ios\Runner\Info.plist (created)
  hello_world\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (created)
  hello_world\ios\Runner.xcworkspace\contents.xcworkspacedata (created)
  hello_world\lib\main.dart (created)
  hello_world\hello_world.iml (created)
  hello_world\pubspec.yaml (created)
  hello_world\README.md (created)
  hello_world\test\widget_test.dart (created)
Running "flutter pub get" in hello_world...                         9.6s

Sending crash report to Google.
Crash report sent (report ID: fec5c22fda932a9c)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Windows\System32\flutter_14.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by iapicca** [comment] 2020-04-29 06:44
Hi @jt112 
can you please provide your `flutter doctor -v`
Thank you

**Comment by iapicca** [comment] 2020-04-30 10:46
Hi @jt112 
I see you are answering on another [issue](https://github.com/flutter/flutter/issues/55867#issuecomment-621672459)
let's keep the cases separated until we are sure that it's the same situation

**Comment by jt112** [comment] 2020-04-30 10:56
Same issue sir

**Comment by iapicca** [comment] 2020-04-30 10:59
Hi @jt112 
even though I don't have all the elements to be certain
that the issue is identical,
with the given information I think the best strategy is
consolidating on https://github.com/flutter/flutter/issues/48014

I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-04-30 10:59 UTC
Labels: in triage

**Comment by jt112** [comment] 2020-04-30 11:06
I am ready to give all information what you
want. I want to solutions

**Comment by iapicca** [comment] 2020-04-30 12:26
Hi @iapicca 
you are welcome to provide those info
issue linked above
thank you
