### ISSUE TITLE
crash when turn on talk back

### ISSUE THREAD

**Issue by ruoyuruoshui** [flutter/flutter#33550] opened 2019-05-30 03:22 UTC
## Steps to Reproduce

   we used [flutter_boost](https://github.com/alibaba/flutter_boost) in our app. i found if user turn on talk back, app will crash when use enter new flutter page. and the flutter_boost () demo crash too.

## Logs

```
E/AndroidRuntime(15968): FATAL EXCEPTION: main
E/AndroidRuntime(15968): Process: nio.com.trident_module.host, PID: 15968
E/AndroidRuntime(15968): java.lang.NullPointerException: Attempt to invoke direct method 'io.flutter.view.AccessibilityBridge$SemanticsNode io.flutter.view.AccessibilityBridge$SemanticsNode.hitTest(float[])' on a null object reference
E/AndroidRuntime(15968): 	at io.flutter.view.AccessibilityBridge$SemanticsNode.access$3500(AccessibilityBridge.java:1680)
E/AndroidRuntime(15968): 	at io.flutter.view.AccessibilityBridge.onAccessibilityHoverEvent(AccessibilityBridge.java:1119)
E/AndroidRuntime(15968): 	at io.flutter.view.FlutterView.onHoverEvent(FlutterView.java:414)
E/AndroidRuntime(15968): 	at android.view.View.dispatchHoverEvent(View.java:10197)
E/AndroidRuntime(15968): 	at android.view.View.dispatchGenericMotionEvent(View.java:10099)
E/AndroidRuntime(15968): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2181)
E/AndroidRuntime(15968): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1883)
E/AndroidRuntime(15968): 	at android.view.View.dispatchGenericMotionEvent(View.java:10099)
E/AndroidRuntime(15968): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2181)
E/AndroidRuntime(15968): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1883)
E/AndroidRuntime(15968): 	at android.view.View.dispatchGenericMotionEvent(View.java:10099)
E/AndroidRuntime(15968): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2181)
E/AndroidRuntime(15968): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1883)
E/AndroidRuntime(15968): 	at android.view.View.dispatchGenericMotionEvent(View.java:10099)
E/AndroidRuntime(15968): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2181)
E/AndroidRuntime(15968): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1883)
E/AndroidRuntime(15968): 	at android.view.View.dispatchGenericMotionEvent(View.java:10099)
E/AndroidRuntime(15968): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2181)
E/AndroidRuntime(15968): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1883)
E/AndroidRuntime(15968): 	at android.view.View.dispatchGenericMotionEvent(View.java:10099)
E/AndroidRuntime(15968): 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2877)
E/AndroidRuntime(15968): 	at com.android.internal.policy.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1871)
E/AndroidRuntime(15968): 	at android.app.Activity.dispatchGenericMotionEvent(Activity.java:3097)
E/AndroidRuntime(15968): 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2844)
E/AndroidRuntime(15968): 	at android.view.View.dispatchPointerEvent(View.java:10255)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5527)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5363)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4808)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4861)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4827)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4968)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4835)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5025)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4808)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4861)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4827)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4835)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4808)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7529)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7397)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7358)
E/AndroidRuntime(15968): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7639)
E/AndroidRuntime(15968): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
E/AndroidRuntime(15968): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(15968): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/AndroidRuntime(15968): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(15968): 	at android.app.ActivityThread.main(ActivityThread.java:7407)
E/AndroidRuntime(15968): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15968): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1321)
E/AndroidRuntime(15968): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1211)
I/Process (15968): Sending signal. PID: 15968 SIG: 9
Lost connection to device.
```

```
Analyzing trident_module...                                             

   info • Unused import: '../services/error_report_service.dart' • lib/common/nio_error.dart:2:8 • unused_import
   info • Avoid using braces in interpolation when not needed • lib/generated/i18n.dart:58:57 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/generated/i18n.dart:59:60 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/generated/i18n.dart:60:48 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/generated/i18n.dart:146:57 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/generated/i18n.dart:148:48 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/generated/i18n.dart:150:60 • unnecessary_brace_in_string_interps
   info • Unused import: 'package:flutter/rendering.dart' • lib/main.dart:10:8 • unused_import
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: MyHeadInfoWidget._context •
          lib/myinfo/components/my_head_info.dart:52:7 • must_be_immutable
   info • Unused import: 'package:fluttertoast/fluttertoast.dart' • lib/myinfo/integral_detail.dart:10:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/myinfo/integral_detail.dart:24:10 • non_constant_identifier_names

11 issues found. (ran in 4.5s)

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by ruoyuruoshui** [comment] 2019-06-04 14:49
when i debug , if i open new page, i found the root SemanticsNode is not dirty. so it will not send to native. then the flutterSemanticsTree is clean because root node is null. 

when is add code (rendering/object.dart) like this, it works. anyone will help me

```
owner._semantics ??= SemanticsNode.root(
      showOnScreen: owner.showOnScreen,
      owner: owner.owner.semanticsOwner,
    );
    owner._semantics.markDirty();
```

**Comment by iapicca** [comment] 2019-10-09 09:47
Hi @ruoyuruoshui 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your flutter doctor -v.

I understand that your are referring to a 3rd party plugin, 
if so could you provide your `pubspec.yaml`
in case the issue is caused by that plugin 
you might want to consider opening an issue on the plugin's github.
Thank you

**Comment by iapicca** [comment] 2019-11-08 11:16
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Closed by iapicca** 2019-11-08 11:16 UTC
Labels: waiting for customer response
