### ISSUE TITLE
Type error when using ImageShader with web 

### ISSUE THREAD

**Issue by kickwaxapps** [flutter/flutter#53500] opened 2020-03-28 21:32 UTC
<
## Steps to Reproduce

1. Create a new flutter DartPad and cut and paste the contents of main.dart reference in the gist below.
[https://gist.github.com/kickwaxapps/c5a08bbaae4690c6a82ea1e4125c2b7b](https://gist.github.com/kickwaxapps/c5a08bbaae4690c6a82ea1e4125c2b7b)

2. Run the new  DartPad

**Expected results:** 
  * Except to see no errors in console, and for ImageShader to work.

**Actual results:** 
 *  Browser console log contains the following error:
 
```
Uncaught (in promise) Error: Expected a value of type 'EngineGradient', but got one of type 'ImageShader'
    at Object.throw_ [as throw] (storage.googleapis.com/compilation_artifacts/2.8.0-edge.ba8baa46b4527a631c077f5a59c348931688d91a/dart_sdk.js:4062)
    at Object.castError (storage.googleapis.com/compilation_artifacts/2.8.0-edge.ba8baa46b4527a631c077f5a59c348931688d91a/dart_sdk.js:4022)
    at Object.cast [as as] (storage.googleapis.com/compilation_artifacts/2.8.0-edge.ba8baa46b4527a631c077f5a59c348931688d91a/dart_sdk.js:4329)
    at Function.as_C [as as] (storage.googleapis.com/compilation_artifacts/2.8.0-edge.ba8baa46b4527a631c077f5a59c348931688d91a/dart_sdk.js:3998)
    at _engine.BitmapCanvas.new.[_applyPaint] (storage.googleapis.com/compilation_artifacts/2.8.0-edge.ba8baa46b4527a631c077f5a59c348931688d91a/dart_sdk.js:127604)
    at _engine.BitmapCanvas.new.drawRect (storage.googleapis.com/compilation_artifacts/2.8.0-edge.ba8baa46b4527a631c077f5a59c348931688d91a/dart_sdk.js:127676)
    at _engine.PaintDrawRect.new.apply (storage.googleapis.com/compilation_artifacts/2.8.0-edge.ba8baa46b4527a631c077f5a59c348931688d91a/dart_sdk.js:154030)
    at _engine.RecordingCanvas.new.apply (storage.googleapis.com/compilation_artifacts/2.8.0-edge.ba8baa46b4527a631c077f5a59c348931688d91a/dart_sdk.js:152990)
    at _engine.EnginePicture.new.toImage (storage.googleapis.com/compilation_artifacts/2.8.0-edge.ba8baa46b4527a631c077f5a59c348931688d91a/dart_sdk.js:142544)
```
This error appears to be a result of this line where only EngineShader expected in applyPaint.

[(https://github.com/flutter/engine/blob/d41e25b5492dc380620508fa08569bf032aa0248/lib/web_ui/lib/src/engine/bitmap_canvas.dart#L211)
](https://github.com/flutter/engine/blob/d41e25b5492dc380620508fa08569bf032aa0248/lib/web_ui/lib/src/engine/bitmap_canvas.dart#L211)

**Comment by ferhatb** [comment] 2020-05-20 18:59
Duplicate of https://github.com/flutter/flutter/issues/33616
ImageShader not supported yet.

**Closed** 2020-05-20 18:59 UTC
Labels: platform-web, severe: crash
