### ISSUE TITLE
TextField longpress throw Exception caught by rendering library

### ISSUE THREAD

**Issue by doerme** [flutter/flutter#47901] opened 2019-12-28 02:43 UTC
<details>
	<summary>logs</summary>

```bash
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 1692 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
                 (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
When the exception was thrown, this was the stack: 
#2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1692:18)
#3      RenderBox.size (package:flutter/src/rendering/box.dart:1698:6)
#4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2466:24)
#5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2274:24)
#6      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2236:31)
...
The following RenderObject was being processed when the exception was fired: _ToolbarRenderBox#9a6cd NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, h=667.0)
...  size: Size(375.0, 667.0)
RenderObject: _ToolbarRenderBox#9a6cd NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=375.0, h=667.0)
  size: Size(375.0, 667.0)
...  child: RenderDecoratedBox#556d5 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0), arrowXOffsetFromCenter=null (can use size)
...    constraints: BoxConstraints(0.0<=w<=359.0, h=43.0)
...    size: Size(170.5, 43.0)
...    decoration: BoxDecoration
...      color: Color(0xff808080)
...    configuration: ImageConfiguration(bundle: PlatformAssetBundle#a7699(), devicePixelRatio: 2.0, locale: en, textDirection: TextDirection.ltr, platform: iOS)
...    child: RenderFlex#9513e relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(0.0<=w<=359.0, h=43.0)
...      size: Size(170.5, 43.0)
...      direction: horizontal
...      mainAxisAlignment: start
...      mainAxisSize: min
...      crossAxisAlignment: center
...      textDirection: ltr
...      verticalDirection: down
...      child 1: RenderSemanticsGestureHandler#36284 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=43.0)
...        size: Size(73.0, 43.0)
...        gestures: tap
...        child: RenderPointerListener#a6dcf relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=43.0)
...          size: Size(73.0, 43.0)
...          behavior: opaque
...          listeners: down
...      child 2: RenderConstrainedBox#54008 relayoutBoundary=up3 NEEDS-PAINT
...        parentData: offset=Offset(73.0, 21.5); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=43.0)
...        size: Size(0.5, 0.0)
...        additionalConstraints: BoxConstraints(w=0.5, 0.0<=h<=Infinity)
...      child 3: RenderSemanticsGestureHandler#ba072 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: offset=Offset(73.5, 0.0); flex=null; fit=null (can use size)
...        constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=43.0)
...        size: Size(97.0, 43.0)
...        gestures: tap
...        child: RenderPointerListener#db95b relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=43.0)
...          size: Size(97.0, 43.0)
...          behavior: opaque
...          listeners: down
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
```

</details>

## My textField code

```dart
TextField(
                        readOnly: chat.isBlockedByYou,
                        onTap: onInputTap,
                        textInputAction: TextInputAction.send,
                        onSubmitted: handleSummit,
                        focusNode: _focusNode,
                        keyboardAppearance: Brightness.light,
                        keyboardType: TextInputType.text,
                        controller: _textEditingController,
                        minLines: 1,
                        maxLines: 3,
                        maxLength: 500,
                        autofocus: false,
                        enableInteractiveSelection: true,
                        style: TextStyle(
                          color: AppThemeColorConfig.titleColor,
                          fontSize: screenInst.setSp(28),
                        ),
                        decoration: InputDecoration(
                          counterText: "",
                          suffixIcon: GestureDetector(
                            onTap: () {
                              if (_isSendDisabled) return;
                              handleSummit(_textEditingController.text);
                            },
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: <Widget>[
                                // Text('emoji'),
                                Container(
                                  width: screenInst.setWidth(88),
                                  height: screenInst.setWidth(66),
                                  child: Image.asset(
                                    'lib/assets/icon/icon_send${_isSendDisabled ? '_disabled' : ''}.png',
                                    width: screenInst.setWidth(44),
                                    height: screenInst.setWidth(44),
                                    package: 'flutter_im_plugin',
                                  ),
                                )
                              ],
                            ),
                          ),
                          fillColor: AppThemeColorConfig.white,
                          contentPadding: EdgeInsets.fromLTRB(
                              screenInst.setWidth(32),
                              screenInst.setWidth(16),
                              screenInst.setWidth(32),
                              screenInst.setWidth(16)),
                          hintText: StickerI18nDict.sendMessageText(),
                          filled: true,
                          hintStyle: TextStyle(
                            fontSize: screenInst.setSp(28),
                            color: AppThemeColorConfig.graySubTitleColor,
                          ),
                          border: OutlineInputBorder(
                            borderSide: BorderSide.none,
                            borderRadius: BorderRadius.all(
                              Radius.circular(20.0),
                            ),
                          ),
                        ),
                        onChanged: (String value) {
                          print('textfield on change $value');
                        },
                      )
```

longpress the longpress menu not show

```console
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)


```

**Comment by iapicca** [comment] 2019-12-30 09:17
Hi @doerme 
I don't see any `GestureDetector` handling `onLongpress `,
regardless you might want to move your `onLongPress `outside the `TextField`
[sample](https://dartpad.dartlang.org/95068226ef68284e5e262c2fe603b542)
does this solve your issue?
thank you

**Comment by justinmc** [comment] 2020-01-10 06:50
+1 to what @iapicca said.

I tried to simplify this to something that can run, but I couldn't reproduce the problem.  Here's the simplified code:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        body: Center( 
          child: TextField(
            readOnly: false,//chat.isBlockedByYou,
                        //onTap: onInputTap,
                        textInputAction: TextInputAction.send,
                        //onSubmitted: handleSummit,
                        //focusNode: _focusNode,
                        keyboardAppearance: Brightness.light,
                        keyboardType: TextInputType.text,
                        //controller: _textEditingController,
                        minLines: 1,
                        maxLines: 3,
                        maxLength: 500,
                        autofocus: false,
                        enableInteractiveSelection: true,
                        style: TextStyle(
                          //color: AppThemeColorConfig.titleColor,
                          //fontSize: screenInst.setSp(28),
                        ),
                        decoration: InputDecoration(
                          counterText: "",
                          suffixIcon: GestureDetector(
                            onTap: () {
                              //if (_isSendDisabled) return;
                              //handleSummit(_textEditingController.text);
                            },
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: <Widget>[
                                // Text('emoji'),
                                Container(
                                  //width: screenInst.setWidth(88),
                                  //height: screenInst.setWidth(66),
                                    /*
                                  child: Image.asset(
                                    'lib/assets/icon/icon_send.png',
                                    //width: screenInst.setWidth(44),
                                    //height: screenInst.setWidth(44),
                                    package: 'flutter_im_plugin',
                                  ),
                                  */
                                )
                              ],
                            ),
                          ),
                          //fillColor: AppThemeColorConfig.white,
                          /*
                          contentPadding: EdgeInsets.fromLTRB(
                              screenInst.setWidth(32),
                              screenInst.setWidth(16),
                              screenInst.setWidth(32),
                              screenInst.setWidth(16)),
                              */
                          //hintText: StickerI18nDict.sendMessageText(),
                          filled: true,
                          hintStyle: TextStyle(
                            //fontSize: screenInst.setSp(28),
                            //color: AppThemeColorConfig.graySubTitleColor,
                          ),
                          border: OutlineInputBorder(
                            borderSide: BorderSide.none,
                            borderRadius: BorderRadius.all(
                              Radius.circular(20.0),
                            ),
                          ),
                        ),
                        onChanged: (String value) {
                          print('textfield on change $value');
                        },
                      ),
        ),
      ),
    );
  }
}

```

**Comment by iapicca** [comment] 2020-02-26 13:05
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Closed by iapicca** 2020-02-26 13:05 UTC
Labels: a: text input, f: material design, framework, waiting for customer response
