### ISSUE TITLE
bin/cache/dart-sdk is out of sync with stamp file

### ISSUE THREAD

**Issue by atebitftw** [flutter/flutter#44222] opened 2019-11-05 23:36 UTC
## Steps to Reproduce

I've been running on the stable channel with no issues (Windows 10) but wanted to switch to master in order to do some flutter web coding...

1. installed a fresh copy of 1.9.1+hotfix.6-stable into src\flutter
2. flutter doctor reports everything is fine on the stable channel
3. flutter channel master
4. flutter upgrade
this is the result...
```
c:\src\flutter>flutter channel master
Switching to flutter channel 'master'...
git: From https://github.com/flutter/flutter
git:  * [new branch]          blasten-patch-1 -> origin/blasten-patch-1
git:    ed36fe5dd..02aac5072  master          -> origin/master
git:  * [new branch]          revert-42236-add_rally_to_examples -> origin/revert-42236-add_rally_to_examples
git: Branch 'master' set up to track remote branch 'master' from 'origin'.
git: Switched to a new branch 'master'

c:\src\flutter>flutter upgrade
Checking Dart SDK version...
Building flutter tool...
Running pub upgrade...
The current Dart SDK version is 2.5.0.

Because flutter_tools depends on build_runner >=1.7.2 which requires SDK version >=2.6.0-dev.8.0 <3.0.0, version
  solving failed.
Error (1): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

Waiting for 0 seconds, press CTRL+C to quit ...
Running pub upgrade...
^CTerminate batch job (Y/N)? y
```

Using --verbose flag doesn't provide any further detail

**Comment by iapicca** [comment] 2019-11-06 09:14
https://github.com/flutter/flutter/issues/39705

**Comment by jonahwilliams** [comment] 2020-02-08 19:56
This can happen when the version of dart in the cache gets out of sync with what is built already. The best way to resolve it (unfortunately) is to delete the cache folder (rm -rf bin/cache)

**Comment by exaby73** [comment] 2022-07-29 11:52
Hello @atebitftw. I am not able to reproduce this issue with the current stable. Therefore, I will be closing this issue as fixed. If you disagree, and are able to reproduce it, please comment with your findings and we can re-open it. Thank you

**Closed by exaby73** 2022-07-29 11:52 UTC
Labels: tool
