### ISSUE TITLE
[tool_crash] ShaderCompilerException

### ISSUE THREAD

**Issue by jartesfigueres** [flutter/flutter#112535] opened 2022-09-28 10:16 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. Changeto Flutter dev channel
2. Create Flutter project for Linux
3. Flutter run, option chrome

## Logs
ShaderCompilerException
```
#0      ShaderCompiler.compileShader (package:flutter_tools/src/build_system/targets/shader_compiler.dart:189:9)
<asynchronous suspension>
#1      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle_builder.dart:185:25)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      writeBundle (package:flutter_tools/src/bundle_builder.dart:163:3)
<asynchronous suspension>
#4      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:866:9)
<asynchronous suspension>
#5      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:489:35)
<asynchronous suspension>
#6      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:283:41)
<asynchronous suspension>
#7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel dev, 3.4.0-17.2.pre, on Kali GNU/Linux Rolling 5.10.16.3-microsoft-standard-WSL2, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.4.0-17.2.pre on channel dev at /home/admin/Documents/flutter/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision d6260f127f (7 days ago), 2022-09-21 13:33:49 -0500
    [32m•[39m Engine revision 3950c6140a
    [32m•[39m Dart version 2.19.0 (build 2.19.0-146.2.beta)
    [32m•[39m DevTools version 2.16.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /home/admin/Android/Sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: /usr/local/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m Debian clang version 14.0.6-2
    [32m•[39m cmake version 3.24.1
    [32m•[39m ninja version 1.11.1
    [32m•[39m pkg-config version 0.29.2

[32m[✓][39m Android Studio (version 2021.3)
    [32m•[39m Android Studio at /usr/local/android-studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Kali GNU/Linux Rolling 5.10.16.3-microsoft-standard-WSL2
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 106.0.5249.61

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e3c29ec00c9c825c891d75054c63fcc46454dca1
### Plugins
path_provider_linux-2.1.7
path_provider_windows-2.1.3
shared_preferences-2.0.15
shared_preferences_android-2.0.13
shared_preferences_ios-2.1.1
shared_preferences_linux-2.1.1
shared_preferences_macos-2.0.4
shared_preferences_web-2.0.4
shared_preferences_windows-2.1.1

**Comment by darshankawar** [comment] 2022-09-28 11:11
Closing as duplicate of https://github.com/flutter/flutter/issues/107590

**Closed by darshankawar** 2022-09-28 11:11 UTC
Labels: in triage
