### ISSUE TITLE
package:flutter/src/painting/text_style.dart': Failed assertion: line 1063 pos 12: 'a == null || b == null || a.inherit == b.inherit': is not true.

### ISSUE THREAD

**Issue by MohammadAminZamaniAfshar** [flutter/flutter#110438] opened 2022-08-28 16:58 UTC
### I using theme in my app and i get TextStyles from Theme to using in my HorizontalNumberPicker widget as seeing below 
![image](https://user-images.githubusercontent.com/88077166/187084452-6cc893d7-dcca-490b-a2a4-6b229ec9e757.png)
![image](https://user-images.githubusercontent.com/88077166/187084524-909a6372-1b80-4978-8bfe-4da846f7c836.png)
![image](https://user-images.githubusercontent.com/88077166/187084558-fe8a959b-9720-4df9-9216-9b864f615fbd.png)

### And i add some text animation to my HorizontalNumberPicker with AnimatedTweenTextStyle widget.
![image](https://user-images.githubusercontent.com/88077166/187084632-aeaec672-2ce1-46d2-b6b8-1b187c4f672a.png)

### It takes a text style and whenever rebuilds with new text style it will animate between them.
![image](https://user-images.githubusercontent.com/88077166/187084718-412cf5ff-91bd-4f72-9c2e-a5bd0556cb22.png)

### For doing that it use TextStyle.lerp method but i got an assertion error as seeing below
![image](https://user-images.githubusercontent.com/88077166/187084763-dafac007-23b5-4461-8963-21cbcc90579d.png)

 ### and i look to the flutter sdk and i realized the error comes from this line:
![image](https://user-images.githubusercontent.com/88077166/187084786-eb10c39a-edb6-4d06-8611-efc65553851b.png)

### And then after a while  i find two way to fix this error:
 - ### 1 comment that line in the flutter sdk
 - ### 2 stop getting TextStyles from theme 

### flutter doctor 
``` text
C:\Users\zaman>fvm spawn 3.0.4 doctor -v
Spawning version "3.0.4"...
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19044.1706], locale fa-IR)
    • Flutter version 3.0.4 at C:\Users\zaman\fvm\versions\3.0.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (8 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\zaman\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.70.0)
    • VS Code at C:\Users\zaman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • SM A310F (mobile) • 5203280dc0b58331 • android-arm    • Android 7.0 (API 24)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 104.0.5112.102
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 104.0.1293.70

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

##  I curioused why this happen?

**Comment by danagbemava-nc** [comment] 2022-08-29 09:15
See also 
https://github.com/flutter/flutter/issues/70281
https://github.com/flutter/flutter/issues/103864

Closing this as a duplicate of #103864

**Closed by danagbemava-nc** 2022-08-29 09:15 UTC
Labels: in triage
