### ISSUE TITLE
Home screen widget in dart instead of in native code.

### ISSUE THREAD

**Issue by lablnet** [flutter/flutter#67927] opened 2020-10-12 15:01 UTC
## Use case
Ummm, I am working on app for my University and classmates there is today's classes section that shows today's classes timing snd names etc, I would like to add support for home screen widget but I didn't find any way to do so but I read on net that we have to do by native code and involved that method from flutter.

## Proposal
As dart compiles to native code so I love if there is features or libs that allows us to write Android home screen widget on Dart, am not iOS developer and user I think similar concept in iOS.

That's all.

Reference: https://developer.android.com/guide/topics/appwidgets#CreatingLayout

**Comment by TahaTesser** [comment] 2020-10-13 10:10
Hi @lablnet 
I doubt this is possible as of now in Flutter to create widgets from the dart. We can't probably use platform-view to render as well 

 if you look at requirements for 
app widgets https://developer.android.com/guide/topics/appwidgets/index.html#CreatingLayout 
```
Creating the App Widget layout is simple if you're familiar with Layouts. However, you must be aware that App Widget layouts are based on RemoteViews, which do not support every kind of layout or view widget.

A RemoteViews object (and, consequently, an App Widget) can support the following layout classes:

FrameLayout
LinearLayout
RelativeLayout
GridLayout
```
As  you can see a tiny amount of views are supported 

Please watch this https://www.youtube.com/watch?v=8Svk7xmscKk

I'm gonna this as a possible proposal if it can be a reality with Hybrid composition

**Comment by pedromassangocode** [comment] 2020-10-22 11:37
Closing this as a duplicate of https://github.com/flutter/flutter/issues/67927

**Closed by pedromassangocode** 2020-10-22 11:37 UTC
Labels: a: platform-views, engine, passed first triage, proposal, severe: new feature

**Comment by imReker** [comment] 2020-10-27 15:04
@TahaTesser 
We can render in memory and draw to home widget.
There is 2 methods to archive currently, I made a full demo:
https://github.com/imReker/FlutterHomeWidget

Hope this function could be officially supported soon.
