### ISSUE TITLE
Support pin shortcuts feature in android

### ISSUE THREAD

**Issue by varindergroove** [flutter/flutter#156564] opened 2024-10-11 05:22 UTC
### Use case

New feature request
I went to add pin shortcut in android platform, please add new method to add a pin shortcut in android I when the both feature used for different ways. I edited your code, it is possible to add request pin shortcut. used this code
 ShortcutManagerCompat.requestPinShortcut(context, shortcuts.get(0), null);
 I add the code for using demo purpose, its working fine. Please add you in proper ways and enhance your library and shortcut for to different way if person add dynamic shortcut use previous one other wise if person use pin shortcut use new one method. if this possible to add this please let me know other wise i used this package in manual import.

### Proposal

<img width="681" alt="image" src="https://github.com/user-attachments/assets/75408db7-a928-4328-85c5-80cf18430c64">

**Comment by huycozy** [comment] 2024-10-11 09:23
Are you using [quick_actions](https://pub.dev/packages/quick_actions) and request adding `requestPinShortcut` into it? 

Or are you proposing a new plugin for your case? If so, please check [flutter_pinned_shortcut](https://pub.dev/packages/flutter_pinned_shortcut) to see if it fits your case.

**Comment by varindergroove** [comment] 2024-10-11 10:55
> Are you using [quick_actions](https://pub.dev/packages/quick_actions) and request adding `requestPinShortcut` into it?
> 
> Or are you proposing a new plugin for your case? If so, please check [flutter_pinned_shortcut](https://pub.dev/packages/flutter_pinned_shortcut) to see if it fits your case.

flutter_pinned_shortcut not behave correctly , always of start follow of the app, 

quick_actions behave correct, i went no new plugin, integrated in same plugin, create new method to createPinshortcut method

**Comment by huycozy** [comment] 2024-10-11 11:55
>quick_actions behave correct, i went no new plugin, integrated in same plugin, create new method to createPinshortcut method

This seems to be beyond `quick_actions` plugin's scope, please see https://github.com/flutter/flutter/issues/44987#issuecomment-825217057. 

Closing this as a duplicate of https://github.com/flutter/flutter/issues/44987.

**Closed by huycozy** 2024-10-11 11:55 UTC
Labels: in triage
