### ISSUE TITLE
Flutter doesn't run. Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by rubenramos4** [flutter/flutter#49202] opened 2020-01-21 10:36 UTC
Cannot run. Only works once after doing the flutter clean command. Can someone help?
Here is the log:

## command

```
flutter build bundle --target C:\DEV\mobile-connected\feature_modules\vehicle_status\sandbox\lib\main.dart --target-platform android-x86 --filesystem-scheme org-dartlang-root --track-widget-creation --depfile C:\DEV\mobile-connected\feature_modules\vehicle_status\sandbox\build\app\intermediates\flutter\debug\android-x86/snapshot_blob.bin.d --asset-dir C:\DEV\mobile-connected\feature_modules\vehicle_status\sandbox\build\app\intermediates\flutter\debug\android-x86/flutter_assets --debug
```

## exception

```
FileSystemException: FileSystemException: Creation failed, path = 'C:\DEV\mobile-connected\feature_modules\vehicle_status\sandbox\build\app\intermediates\flutter\debug\android-x86/flutter_assets\packages/vehicle_status/sandbox/build/app/intermediates/flutter/debug/android-x86/flutter_assets/packages/connected/sandbox' (OS Error: The filename or extension is too long.
, errno = 206)
```

```
#0      _Directory.createSync (dart:io/directory_impl.dart:138:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:133:16)
#2      _Directory.createSync (dart:io/directory_impl.dart:133:16)
#3      _Directory.createSync (dart:io/directory_impl.dart:133:16)
#4      _Directory.createSync (dart:io/directory_impl.dart:133:16)
#5      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#6      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle.dart:191:21)
<asynchronous suspension>
#7      MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
#8      Future.wait (dart:async/future.dart:393:26)
#9      writeBundle (package:flutter_tools/src/bundle.dart:186:16)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11     writeBundle (package:flutter_tools/src/bundle.dart:176:25)
#12     assemble (package:flutter_tools/src/bundle.dart:172:9)
#13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#14     assemble (package:flutter_tools/src/bundle.dart:150:22)
#15     BundleBuilder.build (package:flutter_tools/src/bundle.dart:115:11)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#25     buildAssets (package:flutter_tools/src/bundle.dart)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#32     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#35     _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart)
#36     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#37     _rootRunUnary (dart:async/zone.dart:1132:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#40     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#41     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#42     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#43     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#44     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#45     _obtainLicenses (package:flutter_tools/src/asset.dart)
#46     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#47     _rootRunUnary (dart:async/zone.dart:1132:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#50     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#51     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#52     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#53     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#54     _rootRun (dart:async/zone.dart:1124:13)
#55     _CustomZone.run (dart:async/zone.dart:1021:19)
#56     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#57     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#58     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#60     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17763.973], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\DEV\flutter
    • Framework revision 68587a0916 (4 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\USER-Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at C:\Users\USER-Admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by marafelismino** [comment] 2020-01-21 10:51
+1

**Comment by VladyslavBondarenko** [comment] 2020-01-21 11:02
Hi @rubenramos4 
I see there's an issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/40479
The exception is clear enough - The filename is too long
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Comment by VladyslavBondarenko** [comment] 2020-01-21 12:38
@rubenramos4 
You can take a look at this issue https://github.com/flutter/flutter/issues/27234#issuecomment-487357736
Or do you face the problem after trying steps described [here ](https://medium.com/@nabil6391/solutions-to-flutter-error-gradle-task-assembledebug-failed-with-exit-code-1-1d2c36b2001a)?

**Comment by paulojorgesg** [comment] 2020-01-21 22:32
I have the same problem. I tried the solution before but no results, i have tested remove on dependency  in pubspec.yaml ( 
my_feature_pack:
    path: ../
) and works. If put again (because i need that to run in my main), do not work again.
Flutter version 1.9.1+hotfix.6
I have put all my directories in a short names, but i do not have success in fixing.

**Comment by rubenramos4** [comment] 2020-01-22 08:10
> @rubenramos4
> You can take a look at this issue [#27234 (comment)](https://github.com/flutter/flutter/issues/27234#issuecomment-487357736)
> Or do you face the problem after trying steps described [here ](https://medium.com/@nabil6391/solutions-to-flutter-error-gradle-task-assembledebug-failed-with-exit-code-1-1d2c36b2001a)?



> I have the same problem. I tried the solution before but no results, i have tested remove on dependency in pubspec.yaml (
> my_feature_pack:
> path: ../
> ) and works. If put again (because i need that to run in my main), do not work again.
> Flutter version 1.9.1+hotfix.6
> I have put all my directories in a short names, but i do not have success in fixing.

@VladyslavBondarenko 
Making downgrade to my dependencies won't do it for me.
Now even the flutter clean command doesn't always work to let me run the app.
I find it really odd that this problem is only happening for windows machines, but it's working fine in macintosh.

**Comment by rubenramos4** [comment] 2020-01-22 17:43
I found out something.
It seems that there's a dependency in the pubspec.yaml that is the filename.md (example name).
Once we remove that, it starts working again normally.
I still don't understand why this problem happens and the logs should be more enlightening. And specially I don't understand why it's a problem only on windows machines.

**Comment by jonahwilliams** [comment] 2020-02-15 22:01
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-02-15 22:01 UTC
Labels: severe: crash, t: gradle, tool, ▣ platform-android, ❖ platform-windows
