### ISSUE TITLE
flutter ui crash

### ISSUE THREAD

**Issue by YWD** [flutter/flutter#36797] opened 2019-07-24 03:43 UTC
hi, There's something wrong with my flutter application.
I used 'AliyunOSSiOS' to upload file. the crash always happens when I upload files, It's seems not the sdk's error.
below are the xcode crash log. if you need other information, I will provide later.
![image](https://user-images.githubusercontent.com/8605395/61763473-1feb5a80-ae08-11e9-887e-e48235b42c0a.png)
![image](https://user-images.githubusercontent.com/8605395/61763485-2a0d5900-ae08-11e9-919e-53f4ba4f10e9.png)
![image](https://user-images.githubusercontent.com/8605395/61763496-309bd080-ae08-11e9-92ef-eb16202c77ac.png)

**Comment by timsneath** [comment] 2019-07-24 22:14
Thanks for the report. This looks like a code signing issue, rather than a Flutter issue, for example: 
https://stackoverflow.com/questions/44872071/removing-the-code-signature-from-a-mac-app-executable

**Comment by YWD** [comment] 2019-07-25 14:36
I used 'aws s3' to upload file, it also will crash sometime. It seems It will crash when I have background operate(in other situation no fileupload ,It won't crash). do you have any idea about this?

**Comment by timsneath** [comment] 2019-07-25 21:28
Ah -- now that I look into this further, I'm seeing similarities with https://github.com/flutter/flutter/issues/29022. 

What version of Flutter are you running, @YWD? (Run `flutter doctor -v` and paste the results.)

Adding @mraleph and @rmacnak-google, who looked at the other bug.

**Comment by YWD** [comment] 2019-07-26 05:20
here are the flutter doctor -v print
yangwendongdeMacBook-Pro:ocs_crowd ywd$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/ywd/FlutterProj/flutter
    • Framework revision 8661d8aecd (5 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ywd/Library/Android/sdk
    • Android NDK at /Users/ywd/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ywd/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • 杨文冬的 iPhone • e32a50313989341c90a1b2a11e69c11e9cb9bf4f • ios • iOS 12.2

! Doctor found issues in 1 category.

**Comment by timsneath** [comment] 2019-07-26 05:30
That is an ancient version of Flutter: you are two stable releases behind
the current build. Could you please run flutter upgrade and migrate to the
current version? This is probably a duplicate of the bug linked, which was
fixed in 1.5.

**Comment by YWD** [comment] 2019-07-26 09:27
I upgrade flutter, the crash before hasn't occur. but I find another serious bug.
the EventChannel cannot receive msg from android platform.
here are some code
dart code:
const eventChannel = EventChannel("event_stream");

eventChannel.receiveBroadcastStream().listen(_onResult);

  _onResult(dynamic obj) {
    print('obj:$obj');
    String key = obj['key'];
    String url = obj['picUrl'];
    print('result:$key,$url');
}
android code:
                    LogUtil.d("eventSink:" + url);
                    eventSink.success(stringStringMap);

in logcat I can see the 'eventSink + url' message，but I can't receive message in _onResult method.
I will submit new issue for this.

**Comment by YWD** [comment] 2019-07-26 10:20
how can I downgrade flutter. 
I use 'flutter version v1.2.1' or 'git checkout v1.2.1' ，this will loss channel
![image](https://user-images.githubusercontent.com/8605395/61944989-7fe12d00-afd1-11e9-9e1f-b5c6036dcabf.png)
I run my app the error occour
![image](https://user-images.githubusercontent.com/8605395/61945060-a56e3680-afd1-11e9-87b0-0e3c3fe15e85.png)

**Comment by YWD** [comment] 2019-07-27 09:20
I solved this problem temporary by remove 'flutter/bin/cache' directory

**Closed** 2019-08-01 07:01 UTC
Labels: engine, severe: crash
