### ISSUE TITLE
[tool_crash] RPCError

### ISSUE THREAD

**Issue by Peter-DevX** [flutter/flutter#151051] opened 2024-06-29 20:48 UTC
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
RPCError
```
#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:265:34)
#1      VmService._call.<anonymous closure> (package:vm_service/src/vm_service.dart:1772:25)
#2      VmService._call (package:vm_service/src/vm_service.dart:1784:8)
#3      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:1733:14)
#4      FlutterVmService._checkedCallServiceExtension (package:flutter_tools/src/vmservice.dart:868:28)
#5      FlutterVmService.invokeFlutterExtensionRpcRaw (package:flutter_tools/src/vmservice.dart:887:49)
#6      FlutterVmService.flutterPlatformOverride (package:flutter_tools/src/vmservice.dart:826:48)
#7      ResidentHandlers.debugTogglePlatform (package:flutter_tools/src/resident_runner.dart:941:26)
<asynchronous suspension>
#8      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1841:7)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.19045.4529], locale en-US)
    [32m•[39m Flutter version 3.22.2 on channel stable at C:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
    [32m•[39m Engine revision edd8546116
    [32m•[39m Dart version 3.4.3
    [32m•[39m DevTools version 2.34.3

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[31m[✗][39m Android toolchain - develop for Android devices
    [32m•[39m Android SDK at C:\Users\peter\AppData\Local\Android\sdk
    [31m✗[39m cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[31m[✗][39m Visual Studio - develop Windows apps
    [31m✗[39m Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[32m[✓][39m Android Studio (version 2024.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[32m[✓][39m VS Code (version 1.90.2)
    [32m•[39m VS Code at C:\Users\peter\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.90.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4529]
    [32m•[39m Chrome (web)      • chrome  • web-javascript • Google Chrome 126.0.6478.127
    [32m•[39m Edge (web)        • edge    • web-javascript • Microsoft Edge 126.0.2592.68

[33m[!][39m Network resources
    [31m✗[39m A network error occurred while checking "https://pub.dev/": The semaphore timeout period has expired.

    [31m✗[39m A network error occurred while checking "https://storage.googleapis.com/": Failed host lookup: 'storage.googleapis.com'
    [31m✗[39m A network error occurred while checking "https://maven.google.com/": The semaphore timeout period has expired.

    [31m✗[39m A network error occurred while checking "https://cocoapods.org/": The semaphore timeout period has expired.

    [31m✗[39m A network error occurred while checking "https://github.com/": The semaphore timeout period has expired.


[33m![39m Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 761747bfc538b5af34aa0d3fac380f1bc331ec49

**Comment by danagbemava-nc** [comment] 2024-07-01 08:00
Closing this as a duplicate of https://github.com/flutter/flutter/issues/117988

**Closed by danagbemava-nc** 2024-07-01 08:00 UTC
Labels: in triage
