### ISSUE TITLE
Line (drawn using canvas.drawPoints()) placed above an interactive viewer disappears partially when a widget is placed above it 

### ISSUE THREAD

**Issue by SheenaJacob** [flutter/flutter#106793] opened 2022-06-29 10:19 UTC
## Steps to Reproduce

The issue was previously described in https://github.com/flutter/flutter/issues/106187 and was closed as it didn't have a problem on the master branch. The current code includes the addition of the line being placed on top of an interactive viewer and has also been tested on the master branch.

1. Execute `flutter run` on the code sample 
2. Tap on the TextField and hover the mouse on the screen

**Expected results:** Line below the text field should remain the same length and not get cut off on hovering above it.

**Actual results:** Part of the line below disappears from time to time when clicking the text box and hovering the mouse over the screen.

<details>
<summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() async {
  runApp(const MaterialApp(
      debugShowCheckedModeBanner: false, home: DistanceProvider()));
}

class DistanceProvider extends StatelessWidget {
  const DistanceProvider({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Finds the center of the screen
    final width = MediaQuery.of(context).size.width / 2;
    final height = MediaQuery.of(context).size.height / 2;

    return Scaffold(
      body: InteractiveViewer(
        child: Stack(
          children: [
            // Draws a line using the Custom painter at the center of the screen (width :400 px)
            CustomPaint(
              size: Size.infinite,
              painter: _DrawPath(
                offsetPoints: [
                  Offset(width - 200, height),
                  Offset(width + 200, height)
                ],
              ),
            ),
            // Places a text box to enter the distance between the two points
            Center(
              child: Container(
                width: 50,
                decoration: const BoxDecoration(color: Colors.white),
                child: TextField(
                  onChanged: (String value) {},
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

///Creates a path by drawing a line from one consecutive point to the next
class _DrawPath extends CustomPainter {
  _DrawPath({
    required this.offsetPoints,
  });

  final List<Offset> offsetPoints;

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawPoints(PointMode.polygon, offsetPoints, Paint());
  }

  @override
  bool shouldRepaint(_DrawPath oldDelegate) => true;
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

Analyzing disappearing_line_bug...                                      
No issues found! (ran in 3.6s)

flutter doctor -v
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-x64, locale en-DE)
    • Flutter version 3.0.3 at /Users/jshe/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (7 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jshe/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.0)
    • VS Code at /Users/jshe/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

<!--
      Consider also attaching screenshots and/or videos to better
      illustrate the issue.

      You can upload them directly on GitHub.
      Beware that video file size is limited to 10MB.
--

https://user-images.githubusercontent.com/60810797/176413148-d5094180-23ac-46e3-bce2-b50b7c85aa13.mov

>

**Comment by exaby73** [comment] 2022-06-29 10:30
Hello @SheenaJacob. If you are still facing this issue, please follow up on the original issue you posted. Since this is a duplicate issue, I'm closing this one. You can post your findings on https://github.com/flutter/flutter/issues/106187 and ask for it to be reopened. If you disagree with my decision, feel free to comment. Thank you.

**Comment by SheenaJacob** [comment] 2022-06-29 10:47
Hello @exaby73 .Thanks for the feedback.  I just wanted to specify that the issue is slightly different from the first one, as it happens under different circumstances. The first one didn't have an interactive viewer involved and was actually fixed on the master branch. The problem that occurs is of course the same.

**Comment by exaby73** [comment] 2022-06-29 11:10
I can reproduce this on stable and master on Desktop (MacOS)

<details><summary>Video</summary>

https://user-images.githubusercontent.com/50555895/176422785-a81d18a9-435a-432e-baff-d4085e564a71.mov

</details>

<details><summary>Code sample</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';

void main() async {
  runApp(
    const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: DistanceProvider(),
    ),
  );
}

class DistanceProvider extends StatelessWidget {
  const DistanceProvider({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Finds the center of the screen
    final width = MediaQuery.of(context).size.width / 2;
    final height = MediaQuery.of(context).size.height / 2;

    return Scaffold(
      body: InteractiveViewer(
        child: Stack(
          children: [
            // Draws a line using the Custom painter at the center of the screen (width :400 px)
            CustomPaint(
              size: Size.infinite,
              painter: _DrawPath(
                offsetPoints: [
                  Offset(width - 200, height),
                  Offset(width + 200, height)
                ],
              ),
            ),
            // Places a text box to enter the distance between the two points
            Center(
              child: Container(
                width: 50,
                decoration: const BoxDecoration(color: Colors.white),
                child: TextField(
                  onChanged: (String value) {},
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

///Creates a path by drawing a line from one consecutive point to the next
class _DrawPath extends CustomPainter {
  _DrawPath({
    required this.offsetPoints,
  });

  final List<Offset> offsetPoints;

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawPoints(PointMode.polygon, offsetPoints, Paint());
  }

  @override
  bool shouldRepaint(_DrawPath oldDelegate) => true;
}
```

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.3 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (7 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.40.107

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1422, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1422 on channel master at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1d5c189d28 (52 minutes ago), 2022-06-29 02:19:02 -0400
    • Engine revision 8c36371fa7
    • Dart version 2.18.0 (build 2.18.0-234.0.dev)
    • DevTools version 2.14.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 68.1.4
    • Dart plugin version 221.5921.27

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 103.1.40.107

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by HansMuller** [comment] 2022-06-30 16:12
CC @justinmc

**Comment by jason-simmons** [comment] 2022-07-01 01:51
This works as expected if I disable display lists.

@flar

**Comment by flar** [comment] 2022-07-01 17:44
It looks like our "empty bounds" rejection was a little too over-aggressive. For drawPoints(), it eliminates the bounds of completely horizontal or vertical sets of points before we get a chance to apply the stroke attributes (because they cover no area - which is fine for stroked paths).

**Comment by flar** [comment] 2022-07-01 21:32
Fixed in https://github.com/flutter/engine/pull/34430

**Closed by flar** 2022-07-01 21:32 UTC
Labels: framework, f: material design, a: desktop, has reproducible steps, P4, found in release: 3.0, found in release: 3.1

**Comment by justinmc** [comment] 2022-07-01 23:45
Thanks @flar!
