### ISSUE TITLE
App.framework/App: mach-o, but not built for iOS simulator

### ISSUE THREAD

**Issue by m-zaink** [flutter/flutter#52726] opened 2020-03-17 08:50 UTC
# STEPS TO REPRODUCE
* I have an flutter module that I intend to embed in an application written in native iOS.
* I build the flutter module using `flutter build ios-framework` and embed the frameworks so generated (App.framework and Flutter.framework from Debug folder during debug build of my native app) into my native app.
* I build my native app but I'm met with the `App.framework/App: mach-o, but not built for iOS simulator` error in the console. 

What do I do? 

Note I have checked the architectures present using `lipo` in the built frameworks and I found the following output:
`Architectures in the fat file: App are: x86_64 armv7 arm64`

# Error Logs In Native
`dyld: Library not loaded: @rpath/App.framework/App
  Referenced from: /Users/mohammadsadiq/Library/Developer/CoreSimulator/Devices/4ECD2FE2-59DE-4C33-B975-E0E91798A7B2/data/Containers/Bundle/Application/BEFAFDBF-8C6C-490C-AA71-E76B5839CD6D/ModularApp.app/ModularApp
  Reason: no suitable image found.  Did find:
	/Users/mohammadsadiq/Library/Developer/CoreSimulator/Devices/4ECD2FE2-59DE-4C33-B975-E0E91798A7B2/data/Containers/Bundle/Application/BEFAFDBF-8C6C-490C-AA71-E76B5839CD6D/ModularApp.app/Frameworks/App.framework/App: mach-o, but not built for iOS simulator
	/Users/mohammadsadiq/Library/Developer/CoreSimulator/Devices/4ECD2FE2-59DE-4C33-B975-E0E91798A7B2/data/Containers/Bundle/Application/BEFAFDBF-8C6C-490C-AA71-E76B5839CD6D/ModularApp.app/Frameworks/App.framework/App: mach-o, but not built for iOS simulator
	/Users/mohammadsadiq/Library/Developer/CoreSimulator/Devices/4ECD2FE2-59DE-4C33-B975-E0E91798A7B2/data/Containers/Bundle/Application/BEFAFDBF-8C6C-490C-AA71-E76B5839CD6D/ModularApp.app/Frameworks/App.framework/App: mach-o, but not built for iOS simulator`

**Comment by VladyslavBondarenko** [comment] 2020-03-17 11:52
https://github.com/flutter/flutter/issues/51036

**Comment by jmagman** [comment] 2020-03-17 21:20
Duplicate of https://github.com/flutter/flutter/issues/50568.  See
https://github.com/flutter/flutter/issues/50568#issuecomment-594961985.

**Closed by jmagman** 2020-03-17 21:20 UTC
Labels: a: existing-apps, tool, ⌺‬ platform-ios
