### ISSUE TITLE
`ReorderableListView` reorder does not start with a `ReorderableDragStartListener` when built inside another `Scrollable`

### ISSUE THREAD

**Issue by robertodoering** [flutter/flutter#103804] opened 2022-05-14 12:55 UTC
When building a `ReorderableListView` with `shrinkWrap: true` and `physics: const NeverScrollableScrollPhysics()` inside a `ListView`, the `ReorderableDragStartListener` will no longer initiate the reordering of the `ReorderableListView`.

This broke with flutter 3.0.0. In flutter 2.10.x this worked as expected.

Note:
Using `ReorderableDelayedDragStartListener` to start the reorder with a long press works as expected. Only the `ReorderableDragStartListener` has this issue.

## Steps to Reproduce

1. Execute `flutter run` on the code sample
2. Attempt to reorder the `ListTile` by vertically dragging the drag handle (as shown in the video)

**Expected results:** 
Vertical gestures on the drag handle will initiate the reorder of the `ReorderableListView` and don't scroll the `ListView`.

**Actual results:** 
Vertical gestures on the drag handle scroll the `ListView` and doesn't initiate a reorder.

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MaterialApp(
      home: HomePage(),
    ),
  );
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: [
          const ListTile(title: Text('list tile')),
          ReorderableListView(
            buildDefaultDragHandles: false,
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            onReorder: (_, __) {},
            children: List.generate(
              15,
              (index) => MyReorderableListCard(
                index: index,
                key: UniqueKey(),
              ),
            ),
          ),
          const ListTile(title: Text('list tile')),
        ],
      ),
    );
  }
}

class MyReorderableListCard extends StatelessWidget {
  const MyReorderableListCard({
    required this.index,
    super.key,
  });

  final int index;

  @override
  Widget build(BuildContext context) {
    return ListTile(
      title: Text('reorderable list tile $index'),
      trailing: ReorderableDragStartListener(
        index: index,
        child: Container(
          color: Colors.red,
          child: const Icon(Icons.drag_handle),
        ),
      ),
    );
  }
}
```

</details>

<details>
  <summary>Logs</summary>

```
[  +45 ms] executing: uname -m
[  +22 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +3 ms] executing: [/home/rby/.local/share/flutter_stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] executing: [/home/rby/.local/share/flutter_stable/] git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[   +9 ms] Exit code 0 from: git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] 3.0.0
[   +5 ms] executing: [/home/rby/.local/share/flutter_stable/] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/rby/.local/share/flutter_stable/] git ls-remote --get-url origin
[   +2 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +59 ms] executing: [/home/rby/.local/share/flutter_stable/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +34 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +36 ms] executing: /home/rby/.local/share/android/platform-tools/adb devices -l
[  +26 ms] List of devices attached
           emulator-5554          device product:sdk_gphone64_x86_64 model:sdk_gphone64_x86_64 device:emulator64_x86_64_arm64 transport_id:3
[   +6 ms] /home/rby/.local/share/android/platform-tools/adb -s emulator-5554 shell getprop
[  +24 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +78 ms] Skipping pub get: version match.
[  +43 ms] Generating /data/dev/reorderable_list_view_fix/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +39 ms] ro.hardware = ranchu
[   +6 ms] Using hardware rendering with device sdk gphone64 x86 64. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +16 ms] Initializing file store
[   +8 ms] Skipping target: gen_localizations
[   +4 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/data/dev/reorderable_list_view_fix/.dart_tool/package_config_subset}
[  +14 ms] gen_dart_plugin_registrant: Complete
[        ] Skipping target: _composite
[   +1 ms] complete
[   +3 ms] Launching lib/main.dart on sdk gphone64 x86 64 in debug mode...
[   +3 ms] /home/rby/.local/share/flutter_stable/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/home/rby/.local/share/flutter_stable/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root
/home/rby/.local/share/flutter_stable/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill /tmp/flutter_tools.QLHJCX/flutter_tool.PPLVMG/app.dill --packages /data/dev/reorderable_list_view_fix/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build/c075001b96339384a97db4862b8ab8db.cache.dill.track.dill --enable-experiment=alternative-invalidation-strategy
[   +5 ms] executing: /home/rby/.local/share/android/build-tools/32.0.0/aapt dump xmltree /data/dev/reorderable_list_view_fix/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +6 ms] Exit code 0 from: /home/rby/.local/share/android/build-tools/32.0.0/aapt dump xmltree /data/dev/reorderable_list_view_fix/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.reorderable_list_view_fix" (Raw: "com.example.reorderable_list_view_fix")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="reorderable_list_view_fix" (Raw: "reorderable_list_view_fix")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.reorderable_list_view_fix.MainActivity" (Raw: "com.example.reorderable_list_view_fix.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +4 ms] executing: /home/rby/.local/share/android/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +10 ms] <- compile package:reorderable_list_view_fix/main.dart
[  +34 ms] --------- beginning of kernel
           05-14 14:21:20.516 I/init    (    0): Untracked pid 7425 received signal 1
[   +8 ms] executing: /home/rby/.local/share/android/platform-tools/adb version
[   +7 ms] Android Debug Bridge version 1.0.41
           Version 31.0.3-7562133
           Installed as /home/rby/.local/share/android/platform-tools/adb
[   +1 ms] executing: /home/rby/.local/share/android/platform-tools/adb start-server
[   +6 ms] Building APK
[  +11 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] Using gradle from /data/dev/reorderable_list_view_fix/android/gradlew.
[  +11 ms] executing: [/data/dev/reorderable_list_view_fix/android/] /data/dev/reorderable_list_view_fix/android/gradlew -Pverbose=true -Ptarget-platform=android-x64
-Ptarget=/data/dev/reorderable_list_view_fix/lib/main.dart -Pbase-application-name=android.app.Application -Pdart-defines=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ== -Pdart-obfuscation=false
-Ptrack-widget-creation=true -Ptree-shake-icons=false -Pfilesystem-scheme=org-dartlang-root assembleDebug
[  +40 ms] Picked up _JAVA_OPTIONS: -Djava.util.prefs.userRoot=/home/rby/.config/java
[ +420 ms] Welcome to Gradle 7.4!
[        ] Here are the highlights of this release:
[        ]  - Aggregated test and JaCoCo reports
[        ]  - Marking additional test source directories as tests in IntelliJ
[        ]  - Support for Adoptium JDKs in Java toolchains
[        ] For more details see https://docs.gradle.org/7.4/release-notes.html
[ +398 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
[+8496 ms] > Task :app:compileFlutterBuildDebug
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[  +99 ms] > Task :app:checkDebugAarMetadata UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders NO-SOURCE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[  +99 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[ +100 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:extractDeepLinksDebug UP-TO-DATE
[        ] > Task :app:processDebugMainManifest UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugManifestForPackage UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[  +99 ms] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[        ] > Task :app:checkDebugDuplicateClasses UP-TO-DATE
[        ] > Task :app:dexBuilderDebug UP-TO-DATE
[        ] > Task :app:desugarDebugFileDependencies UP-TO-DATE
[        ] > Task :app:mergeExtDexDebug UP-TO-DATE
[        ] > Task :app:mergeDexDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[        ] > Task :app:mergeDebugNativeLibs UP-TO-DATE
[        ] > Task :app:stripDebugDebugSymbols UP-TO-DATE
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[        ] > Task :app:writeDebugAppMetadata UP-TO-DATE
[        ] > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
[ +398 ms] > Task :app:compressDebugAssets
[        ] Execution optimizations have been disabled for task ':app:compressDebugAssets' to ensure correctness due to the following reasons:
[        ]   - Gradle detected a problem with the following location: '/data/dev/reorderable_list_view_fix/build/app/intermediates/assets/debug/mergeDebugAssets'. Reason: Task
':app:compressDebugAssets' uses this output of task ':app:copyFlutterAssetsDebug' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced,
depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[ +499 ms] > Task :app:packageDebug
[        ] > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
[        ] > Task :app:assembleDebug
[  +18 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[        ] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[        ] See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
[        ] Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
[        ] Please consult deprecation warnings for more details.
[        ] BUILD SUCCESSFUL in 10s
[        ] 35 actionable tasks: 7 executed, 28 up-to-date
[ +328 ms] Running Gradle task 'assembleDebug'... (completed in 11.0s)
[  +40 ms] calculateSha: LocalDirectory: '/data/dev/reorderable_list_view_fix/build/app/outputs/flutter-apk'/app.apk
[ +507 ms] ✓  Built build/app/outputs/flutter-apk/app-debug.apk.
[   +1 ms] executing: /home/rby/.local/share/android/build-tools/32.0.0/aapt dump xmltree /data/dev/reorderable_list_view_fix/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[   +7 ms] Exit code 0 from: /home/rby/.local/share/android/build-tools/32.0.0/aapt dump xmltree /data/dev/reorderable_list_view_fix/build/app/outputs/flutter-apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1f
               A: android:compileSdkVersionCodename(0x01010573)="12" (Raw: "12")
               A: package="com.example.reorderable_list_view_fix" (Raw: "com.example.reorderable_list_view_fix")
               A: platformBuildVersionCode=(type 0x10)0x1f
               A: platformBuildVersionName=(type 0x10)0xc
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1f
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=17)
                 A: android:label(0x01010001)="reorderable_list_view_fix" (Raw: "reorderable_list_view_fix")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="android.app.Application" (Raw: "android.app.Application")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=23)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.reorderable_list_view_fix.MainActivity" (Raw: "com.example.reorderable_list_view_fix.MainActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=38)
                     A: android:name(0x01010003)="io.flutter.embedding.android.NormalTheme" (Raw: "io.flutter.embedding.android.NormalTheme")
                     A: android:resource(0x01010025)=@0x7f0a0001
                   E: intent-filter (line=42)
                     E: action (line=43)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=45)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                 E: meta-data (line=52)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
                 E: uses-library (line=56)
                   A: android:name(0x01010003)="androidx.window.extensions" (Raw: "androidx.window.extensions")
                   A: android:required(0x0101028e)=(type 0x12)0x0
                 E: uses-library (line=59)
                   A: android:name(0x01010003)="androidx.window.sidecar" (Raw: "androidx.window.sidecar")
                   A: android:required(0x0101028e)=(type 0x12)0x0
[   +1 ms] Stopping app 'app.apk' on sdk gphone64 x86 64.
[        ] executing: /home/rby/.local/share/android/platform-tools/adb -s emulator-5554 shell am force-stop com.example.reorderable_list_view_fix
[  +34 ms] executing: /home/rby/.local/share/android/platform-tools/adb -s emulator-5554 shell pm list packages com.example.reorderable_list_view_fix
[  +23 ms] package:com.example.reorderable_list_view_fix
[   +1 ms] executing: /home/rby/.local/share/android/platform-tools/adb -s emulator-5554 shell cat /data/local/tmp/sky.com.example.reorderable_list_view_fix.sha1
[  +24 ms] a781bdeeddc2261f6d394a4e309bd61eb01efcaf
[        ] Installing APK.
[        ] Installing build/app/outputs/flutter-apk/app.apk...
[        ] executing: /home/rby/.local/share/android/platform-tools/adb -s emulator-5554 install -t -r /data/dev/reorderable_list_view_fix/build/app/outputs/flutter-apk/app.apk
[ +668 ms] Performing Streamed Install
           Success
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 668ms)
[        ] executing: /home/rby/.local/share/android/platform-tools/adb -s emulator-5554 shell echo -n e2d8ef03bd02d0a64b1b8086e448596823cdca36 >
/data/local/tmp/sky.com.example.reorderable_list_view_fix.sha1
[  +26 ms] executing: /home/rby/.local/share/android/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +41 ms] --------- beginning of system
           05-14 14:21:34.293 D/CompatibilityChangeReporter(  568): Compat change id reported: 135634846; UID 1000; state: DISABLED
[  +10 ms] executing: /home/rby/.local/share/android/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-dart-profiling true --ez
enable-checked-mode true --ez verify-entry-points true com.example.reorderable_list_view_fix/com.example.reorderable_list_view_fix.MainActivity
[  +78 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.reorderable_list_view_fix/.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[ +646 ms] Observatory URL on device: http://127.0.0.1:35845/pS9U0IX3tsk=/
[        ] executing: /home/rby/.local/share/android/platform-tools/adb -s emulator-5554 forward tcp:0 tcp:35845
[   +9 ms] 35829
[        ] Forwarded host port 35829 to device port 35845 for Observatory
[   +4 ms] Caching compiled dill
[  +26 ms] Connecting to service protocol: http://127.0.0.1:35829/pS9U0IX3tsk=/
[ +123 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:35829/pS9U0IX3tsk=/.
[ +143 ms] DDS is listening at http://127.0.0.1:37509/0wUUBvjcPuI=/.
[  +46 ms] Successfully connected to service protocol: http://127.0.0.1:35829/pS9U0IX3tsk=/
[  +63 ms] DevFS: Creating new filesystem on the device (null)
[  +14 ms] DevFS: Created new filesystem on the device (file:///data/user/0/com.example.reorderable_list_view_fix/code_cache/reorderable_list_view_fixJSPBRA/reorderable_list_view_fix/)
[   +1 ms] Updating assets
[  +47 ms] Syncing files to device sdk gphone64 x86 64...
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] Processing bundle.
[        ] <- recompile package:reorderable_list_view_fix/main.dart 9a0c2e29-f016-4694-aa69-29daa5977202
[        ] <- 9a0c2e29-f016-4694-aa69-29daa5977202
[        ] Bundle processing done.
[  +63 ms] Updating files.
[        ] DevFS: Sync finished
[        ] Syncing files to device sdk gphone64 x86 64... (completed in 66ms)
[        ] Synced 0.0MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0x7b22805bb430.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[        ] R Hot restart.
[        ] h List all available interactive commands.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] 💪 Running with sound null safety 💪
[        ] An Observatory debugger and profiler on sdk gphone64 x86 64 is available at: http://127.0.0.1:37509/0wUUBvjcPuI=/
[ +319 ms] The Flutter DevTools debugger and profiler on sdk gphone64 x86 64 is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:37509/0wUUBvjcPuI=/
[+4503 ms] D/EGL_emulation( 7865): app_time_stats: avg=2246.18ms min=72.22ms max=4420.13ms count=2
[+2950 ms] D/EGL_emulation( 7865): app_time_stats: avg=56.75ms min=10.21ms max=2006.63ms count=52
[+4609 ms] Application finished.
```

```
Analyzing reorderable_list_view_fix...                          
No issues found! (ran in 1.0s)
```

```
[✓] Flutter (Channel stable, 3.0.0, on Arch Linux 5.17.5-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.0.0 at /home/rby/.local/share/flutter_stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (5 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/rby/.local/share/android
    • Platform android-32, build-tools 32.0.0
    • ANDROID_SDK_ROOT = /home/rby/.local/share/android/sdk
    • Java binary at: /usr/lib/jvm/java-11-openjdk/bin/java
    • Java version openjdk version "11.0.15" 2022-04-19
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at /bin/chromium)
    ! /bin/chromium is not executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 13.0.1
    • cmake version 3.23.1
    • ninja version 1.10.2
    • pkg-config version 1.8.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64 • Android 12 (API 32) (emulator)
    • Linux (desktop)              • linux         • linux-x64   • Arch Linux 5.17.5-arch1-1

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

--- 

### current behavior (flutter 3.0.0) 
https://user-images.githubusercontent.com/20045287/168426194-e411265d-5f8f-40e6-bcb4-15f930cacbbf.mp4

### expected behavior (2.10.5)
https://user-images.githubusercontent.com/20045287/168426196-e0348f5b-64a9-4b29-971d-35310417a279.mp4

**Comment by robertodoering** [comment] 2022-05-14 12:57
If anyone else has this problem, a simple workaround is to create a custom `ReorderableDragStartListener` that creates a `DelayedMultiDragGestureRecognizer` with a delay of zero.
This will have the same behavior that the `ReorderableDragStartListener` previously had.

```dart
class MyReorderableDragStartListener extends ReorderableDragStartListener {
  const MyReorderableDragStartListener({
    required super.child,
    required super.index,
    super.key,
    super.enabled,
  });

  @override
  MultiDragGestureRecognizer createRecognizer() {
    return DelayedMultiDragGestureRecognizer(
      debugOwner: this,
      delay: Duration.zero,
    );
  }
}
```

**Comment by jonahwilliams** [comment] 2022-05-14 16:54
@xu-baolin is the same as https://github.com/flutter/flutter/issues/103663 ?

**Comment by xu-baolin** [comment] 2022-05-15 04:26
Very likely, will double check tomorrow.

**Comment by darshankawar** [comment] 2022-05-16 07:13
This indeed looks same as https://github.com/flutter/flutter/issues/103663 which has been fixed per https://github.com/flutter/flutter/issues/103404.
Closing this as duplicate of https://github.com/flutter/flutter/issues/103663. If anybody disagrees, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-05-16 07:13 UTC
Labels: in triage

**Comment by xu-baolin** [comment] 2022-05-16 09:04
This is indeed already fixed on master and @jonahwilliams is pushing the cherry-pick to the stable branch.

@robertodoering, thanks for reporting, #103663 provide a more simple workaround.
