### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by Hleysonn** [flutter/flutter#113300] opened 2022-10-11 23:00 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:564:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:584:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:96:16)
#3      ErrorHandlingFile.readAsStringSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:222:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:597:14)
#5      ErrorHandlingFile.readAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:221:12)
#6      new SettingsFile.parseFromFile (package:flutter_tools/src/base/utils.dart:145:36)
#7      updateLocalProperties (package:flutter_tools/src/android/gradle_utils.dart:231:29)
#8      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:534:12)
#9      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:352:21)
<asynchronous suspension>
#10     PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:175:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.3.4, on Microsoft Windows [version 10.0.22000.978], locale fr-BE)
    • Flutter version 3.3.4 on channel stable at C:\Users\Hleysonn\OneDrive\Bureau\N_Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (7 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Hleysonn\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[✓] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[✓] VS Code (version 1.72.1)
    • VS Code at C:\Users\Hleysonn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [version 10.0.22000.978]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 106.0.5249.103
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 106.0.1370.37

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: fb57da5f945d02ef4f98dfd9409a72b7cce74268
### Plugins
cloud_firestore-3.5.1
cloud_firestore_web-2.8.10
firebase_auth-3.11.2
firebase_auth_web-4.6.1
firebase_core-1.24.0
firebase_core_web-1.7.3
firebase_storage-10.3.11
firebase_storage_web-3.3.9
flutter_plugin_android_lifecycle-2.0.7
flutter_stripe-4.0.0
google_sign_in-5.4.2
google_sign_in_android-6.1.1
google_sign_in_ios-5.5.0
google_sign_in_web-0.10.2
image_picker-0.8.6
image_picker_android-0.8.5+3
image_picker_for_web-2.1.10
image_picker_ios-0.8.6+1
path_provider-2.0.11
path_provider_android-2.0.20
path_provider_ios-2.0.11
path_provider_linux-2.1.7
path_provider_macos-2.0.6
path_provider_windows-2.0.7
stripe_android-4.0.0
stripe_ios-4.0.0

**Comment by danagbemava-nc** [comment] 2022-10-12 07:19
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021. 

Kindly follow up in the issue linked above for updates. Please upvote the issue linked above as well. 

Thank you

**Closed by danagbemava-nc** 2022-10-12 07:19 UTC
Labels: in triage
