### ISSUE TITLE
[web] [canvaskit]: cursor position is wrong when using left and right arrow key in multiline textfield

### ISSUE THREAD

**Issue by tenutos** [flutter/flutter#78192] opened 2021-03-15 05:58 UTC
in canvasKit mode. When the TextField box is in multi-line mode, there is a problem with the cursor when pressing enter.
Try it in multi-line mode, press the enter key to wrap, and then press the left or right cursor key.
in html mode. is normal.

**Comment by darshankawar** [comment] 2021-03-15 11:46
@tenutos 
Can you provide `flutter doctor -v` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by tenutos** [comment] 2021-03-15 11:50
The latest flutter version is used (I will upgrade the flutter version every day to keep it up to date), this does not require fragment code, this problem exists in any branch, you can just follow my method Reproduce.

**Comment by darshankawar** [comment] 2021-03-16 05:58
@tenutos 

1. with canvaskit:


https://user-images.githubusercontent.com/67046386/111262592-801cb900-864a-11eb-9052-33c3bc848a2f.mov


2. with html:


https://user-images.githubusercontent.com/67046386/111262613-89a62100-864a-11eb-893b-f4dbc38dc016.mov



code sample:

```
return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextField(
            maxLines: 3,
            decoration: InputDecoration(
              hintText: 'enter here'
            ),
          ),
        ),
      ),
    );
```

Saw the same behavior on both renderers unless I misinterpreted the issue. Can you confirm this ?

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.103, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.103 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 0cbe597540 (6 hours ago), 2021-03-15 16:28:02 -0700
    • Engine revision 20375cebcf
    • Dart version 2.13.0 (build 2.13.0-137.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by tenutos** [comment] 2021-03-16 10:07
@darshankawar 
https://user-images.githubusercontent.com/31977578/111291349-128c7f00-8682-11eb-8262-a2ff0ec54ed9.mp4

Pay attention to the position of the cursor in the textField box when I press the left arrow key for the first time...

code:
class Test extends StatelessWidget {
  final node = FocusNode();
  final ValueNotifier<List<String>> hotKey = ValueNotifier<List<String>>([]);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RawKeyboardListener(
            focusNode: node,
            autofocus: false,
            onKey: (e) {
              if (e is RawKeyDownEvent) hotKey.value = List.from(hotKey.value)..add(e.physicalKey.debugName);
              return false;
            },
            child: Column(
              children: [
                Text("enter List:"),
                ValueListenableBuilder<List<String>>(
                    valueListenable: hotKey,
                    builder: (context, value, child) {
                      return Container(
                          height: 200,
                          child: Wrap(
                            children: value.map((e) => Text(" $e ")).toList(),
                          ));
                    }),
                TextField(
                  maxLines: 3,
                  decoration: InputDecoration(hintText: 'enter here'),
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by darshankawar** [comment] 2021-03-16 12:52
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.2 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 89.0.4389.82

! Doctor found issues in 1 category.

```

</details>

**Comment by mdebbar** [comment] 2021-03-23 17:49
@darshankawar it only happens when there's whitespaces at the end of the line. In your video, you didn't add whitespace to the end of the line, that's why you didn't see the issue.

This issue is a duplicate of https://github.com/flutter/flutter/issues/77929.

**Closed by mdebbar** 2021-03-23 17:49 UTC
Labels: a: text input, assigned for triage, e: web_canvaskit, found in release: 2.0, has reproducible steps, platform-web
