### ISSUE TITLE
A memory leak occurred while I was using a Canvas receipt image and converting it to ui.Image

### ISSUE THREAD

**Issue by linb1111111** [flutter/flutter#145211] opened 2024-03-15 14:00 UTC
### Steps to reproduce

void setPixelcolor(List<Offset> points, double brushsize, Color color)(_recorder ??= ui.PictureRecorder()；
_canvas ??= ui.Canvas(_recorder!)；
_canvas?.dravImage(layers[currentEditLayout].uiImage!, Offset.zero, Paint())；
canvas!.drawPoints(
ui.PointMode.points, 
points, 
Paint()
..color = color
..strokeWidth = 1);
_picture = _recorder!.endRecording();
layers[currentEditLayout].uiImage = _picture!.toImageSync(canvassize.width.toInt(),canvassize.height.toInt())；picture!.dispose()；
_picture = null;

This is the function executed

### Expected results

Memory is stable

### Actual results

I execute 5000 times, and the memory goes up badly

### Code sample

<details open><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by huycozy** [comment] 2024-03-18 05:41
Closing this as a duplicate of https://github.com/flutter/flutter/issues/145210. Please don't file multiple issues for the same reason.

**Closed by huycozy** 2024-03-18 05:41 UTC
Labels: in triage
