### ISSUE TITLE
[tool_crash] ProcessException: The command failed  Command: unzip -o -q /Users/deeas/development/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/ee76268252c22f5c11e82a7b87423ca3982e51a7/darwin-x64/artifacts.zip -d /Users/deeas/development/flutter/bin/cache/artifacts/engine/darwin-x64

### ISSUE THREAD

**Issue by msmoradi** [flutter/flutter#60770] opened 2020-07-02 13:46 UTC
## Command
```
flutter --no-color pub upgrade
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: ProcessException: The command failed
  Command: unzip -o -q /Users/deeas/development/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/ee76268252c22f5c11e82a7b87423ca3982e51a7/darwin-x64/artifacts.zip -d /Users/deeas/development/flutter/bin/cache/artifacts/engine/darwin-x64
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:448:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:218:19)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:619:16)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#12     Cache.downloadFile (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1192:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
```
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-VI)
    • Flutter version 1.17.5 at /Users/deeas/development/flutter
    • Framework revision 8af6b2f038 (2 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/deeas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f

**Comment by VladyslavBondarenko** [comment] 2020-07-02 15:01
Related to https://github.com/flutter/flutter/issues/52437

**Comment by christopherfujino** [comment] 2020-07-14 23:30
thanks for filing this; however I am closing as a duplicate of #52437. Please follow there for updates.

**Closed by christopherfujino** 2020-07-14 23:30 UTC
Labels: severe: fatal crash, tool
