### ISSUE TITLE
Target of URI doesn't exist

### ISSUE THREAD

**Issue by keinou** [flutter/flutter#49702] opened 2020-01-29 16:08 UTC
## Steps to Reproduce

1. Create a project with two pages.
2. Add the import of the second file, and create the route for navigation.
3. Add accented text on the second pag.

**Actual results:** Target of URI doesn't exist:

```
info - Unused import: 'dart:convert' - lib\api\autentication.dart:1:8 - unused_import
   info - Unused import: 'dart:ui' - lib\generated_plugin_registrant.dart:4:8 - unused_import
   info - Unused import: 'dart:convert' - lib\model\main\dashdata.dart:1:8 - unused_import
   info - Unused import: 'package:hello/model/global.dart' - lib\model\main\key.dart:2:8 - unused_import
  error - Target of URI doesn't exist: 'package:hello/pages/financeiro/aprov_pagar.dart' - lib\pages\main\home_page.dart:2:8 -
         uri_does_not_exist
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [versÃ£o 10.0.18362.592], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 3.4)
[√] VS Code (version 1.41.1)
[√] Connected device (3 available)

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment] 2020-01-29 16:34
Hi @keinou 
But does `/pages/financeiro/aprov_pagar.dart` exist?
the same if to use relative path? (like `../../financeiro/aprov_pagar.dart`)

To better address the issue, would be helpful
if you could post a self contained app on github
Thank you

**Comment by keinou** [comment] 2020-01-29 18:02
Hi @VladyslavBondarenko 
I created a project for example of the problem:
https://github.com/keinou/IssueFlutter

This is the problem:
![image](https://user-images.githubusercontent.com/20158261/73382615-38986980-429e-11ea-90d0-15f38b10f395.png)

If I have the file open, it doesn't happen:
![image](https://user-images.githubusercontent.com/20158261/73382849-ac3a7680-429e-11ea-96b4-9b96c63a0e94.png)

In Android Studio he doesn't even recognize it with the file open.
Of course, this only happens if I have accented text, if I remove the file it is normally found.
Remove the accentuation from the text "Confirma a rejeição do titulo?" in other_page.dart and watch.

**Comment by iapicca** [comment] 2020-01-30 07:54
Hi @keinou 
I cannot reproduce the issue you are describing [issues_49702](https://user-images.githubusercontent.com/45637986/73430029-acda1800-4345-11ea-9ce3-7f586df03234.png).

Best case scenario it's just a problem with your Android Studio installation;
the annoying workaround might just be reinstalling AS.

If it doesn't solve it being potentially a problem with Android Studio's plugin itself
please follow the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter)  opening an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-01-30 07:54 UTC

**Comment by OliverNarramore** [comment] 2020-02-17 07:23
I attempted many of the fixes other users suggested such as clearing cache, running flutter pub get, restarting Xcode etc.

I believe the issue is if the .dart file is inside a folder which contains spaces in its title. For example:
Test File -> test_file.dart

No other files will be able to import test_file.dart, despite it suggesting the the pathway. It simply states "Target of URI doesn't exist"

**Comment by zyzhangyu** [comment] 2020-04-08 01:35
1. in .yaml file,   the top line code is -> name:todo_app.

2. in main.dart file, import 'package:todo_app/UI/intro_page.dart';

IDEA report this message: Target of URI doesn't exist: 'package:todo_app/UI/intro_page.dart'.

3. in main.dart file, import 'package:project_name/UI/intro_page.dart' is OK!

**Comment by iapicca** [comment] 2020-04-08 11:14
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
