### ISSUE TITLE
Google Testing CI check is flaky

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#116357] opened 2022-12-01 15:19 UTC
Example: https://github.com/flutter/flutter/pull/116218

This is mainly being tracked internally (b/260764527), but this bug card is meant to give visibility of progress on the issue

**Comment by drewroengoogle** [comment] 2022-12-01 15:20
@muditatandon Is it okay to assign this to you?

**Comment by christopherfujino** [comment] 2022-12-01 18:51
Internally tracked b/260764527

**Comment by nehalvpatel** [comment] 2022-12-12 19:11
Looks like a fix was landed but it is still being reproduced. Continuing to be tracked internally.

**Comment by godofredoc** [comment] 2023-01-13 23:00
Any updates in this bug?

**Comment by muditatandon** [comment] 2023-01-17 19:15
Noticed that the entries were present in the database, but not being displayed on the client. Continuing work on this bug.

**Comment by ricardoamador** [comment] 2023-01-25 22:47
Internal issue has been assigned to @XilaiZhang.

**Comment by XilaiZhang** [comment] 2023-04-12 21:29
will close this for now since we haven't been seeing recently reported cases.

**Closed by XilaiZhang** 2023-04-12 21:29 UTC
Labels: team: google testing
