### ISSUE TITLE
camera_android_camerax: Failed to find supported resolutions (IllegalArgumentException)

### ISSUE THREAD

**Issue by andynewman10** [flutter/flutter#135293] opened 2023-09-22 10:24 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Create a Flutter application using Flutter 3.13.3. I use VS Code on Windows.
2. Design a basic camera application using:
```
camera: ^0.10.5+4
camera_android_camerax: ^0.5.0+18
```
3. Create a camera controller in the following way:
```
    List<CameraDescription> cameras = await availableCameras();

    CameraDescription? cameraDescription;
    for (int i = 0; i < cameras.length; i++) {
      if (cameras[i].lensDirection == CameraLensDirection.back) {
        cameraDescription = cameras[i];
      }
    }

    if (cameraDescription == null) {
      throw Exception("Could not find any back-facing camera");
    }

    final cameraController = CameraController(
        cameraDescription, ResolutionPreset.medium,
        enableAudio: false, imageFormatGroup: ImageFormatGroup.yuv420);

    await cameraController.initialize();
```
5. Run the application on an Android 13 device, I personally use a Google Pixel 6a.
6. The following exception is thrown:
```
IllegalArgumentException: Failed to find supported resolutions
```
7. Now, remove the following line from your pubspec.yaml:
```
# camera_android_camerax: ^0.5.0+18
```
8. Run the application again: no error.

### Expected results

The code should be running fine.

### Actual results

Exception being thrown.

### Code sample

<details><summary>Code sample</summary>

```dart
See above
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [version 10.0.22000.2416], locale fr-FR)
    • Flutter version 3.13.3 on channel stable at C:\Users\andy\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (2 weeks ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\andy\AppData\Local\Android\sdk
    • Platform android-33, build-tools 34.0.0
    • Java binary at: C:\Users\andy\Documents\Applications\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Users\andy\Documents\Applications\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Users\andy\Documents\Applications\IntelliJ
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.82.2)
    • VS Code at C:\Users\andy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (4 available)
    • Pixel 6a (mobile) • 29231JEGR03669 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows        • windows-x64    • Microsoft Windows [version 10.0.22000.2416]
    • Chrome (web)      • chrome         • web-javascript • Google Chrome 116.0.5845.188
    • Edge (web)        • edge           • web-javascript • Microsoft Edge 117.0.2045.36

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by andynewman10** [comment] 2023-09-22 15:30
I do confirm the bug exists on my Google Pixel 6a device with your code (unmodified).

**Comment by darshankawar** [comment] 2023-09-25 05:45
Thanks for the update. Although I didn't see the exact reported error, but got below in console:

```
I/flutter (21891): Error: java.lang.IllegalArgumentException: Unable to find supported quality by QualitySelector
I/flutter (21891): Error Message: IllegalArgumentException

```

**Comment by gmackall** [comment] 2023-10-12 18:18
@camsim99 assigning to you for visibility, feel free to un-assign if you won't immediately have time to work on this

**Comment by camsim99** [comment] 2023-10-25 15:51
The error `java.lang.IllegalArgumentException: Failed to find supported resolutions` is being thrown by CameraX ([source](https://android.googlesource.com/platform/frameworks/support/+/27d045fbd961cb27edcacd2b93bd756adf5546e5/camera/camera2/src/main/java/androidx/camera/camera2/impl/SupportedSurfaceCombination.java#409)). I was unable to reproduce this on a Pixel 3A, but my gut tells me this may be because of the fallback strategy I decided to use for choosing a resolution. For instance, the Pixel 6A may not support lower resolutions, but the strategy I chose will only look for the specified resolution preset or lower and thus, may be failing when you try to choose those. Will investigate.

@andynewman10 In terms of `_TypeError (Null check operator used on a null value)` error, do you have a full log for this? I would like to debug further but I wasn't able to reproduce this either.

**Comment by camsim99** [comment] 2023-10-26 20:50
Going to propose https://github.com/flutter/packages/pull/5239 to attempt fixing this issue, although will be unable to confirm myself. However, making this change will make selecting a resolution safer overall, so I think it's worth it either way.

**Comment by andynewman10** [comment] 2023-10-28 11:25
@camsim99 sorry it took a few days to reply. There is no additional information in the log.

However, here is the stacktrace of the `_TypeError: Null check operator used on a null value` exception:

```
#0      AndroidCameraCameraX._getResolutionSelectorFromPreset (package:camera_android_camerax/src/android_camera_camerax.dart:892:33)
#1      AndroidCameraCameraX.createCamera (package:camera_android_camerax/src/android_camera_camerax.dart:239:9)
<asynchronous suspension>
#2      CameraController._initializeWithDescription (package:camera/src/camera_controller.dart:316:19)
<asynchronous suspension>
...
```
Version info (from my pubspec.lock):

- android_camera_camerax: 0.5.0+19
- camera: 0.10.5+5

**Comment by camsim99** [comment] 2023-10-30 20:24
@andynewman10 No worries! Thank you for the stacktrace. I will take a look.

On the primary issue, though, if you can let me know if the error still occurs with `camera_android_camerax` version `0.5.0+21`, that would be great!

**Comment by andynewman10** [comment] 2023-10-30 22:11
@camsim99 indeed! Initializing a CameraController with `ResolutionPreset.medium` does work now with `0.5.0+21` on my Pixel 6a, great!
The `CameraImage` instance I get in `processCameraImage` is exactly 640x480, which is perfect.

I have two important questions though.

1) Could you confirm that if I ask for a specific resolution (medium in my case which is exactly 640x480 on Android), I am **guaranteed** to have a CameraImage instance in `processCameraImage` with a size of **at least** 640x480?
It is critical for me to request a specific resolution and to get something that is **at least** the size requested when this function is entered because I need to crop the image that goes through processCameraImage. cropping will crash if I get something smaller and I don't want to perform upscaling.

2) Assuming the specific resolution I asked for was not exactly supported by the hardware, I understand from your changelog entry that you try lower resolutions first, and then, higher resolutions:

```
Changes fallback resolution strategies for camera use cases to look for a higher
resolution if neither the desired resolution nor any lower resolutions are available.
```
I understand here

- that you're looking for the specific resolution I am asking for. If it is supported, you just return the image.
- if it is not supported, you attempt to find a LOWER resolution (and then, you upscale to the resolution I wanted, right? See my question above)
- only if a lower resolution is not supported, you try higher resolutions.

I would expect the code to try higher resolutions first?

**Comment by camsim99** [comment] 2023-10-31 18:05
@andynewman10 To respond to your questions:

1. Assuming the call succeeds, yes you will get a `CameraImage` with at least the resolution requested when taking a photo (not sure exactly what `processCameraImage` is but this is what I assume you're referencing). This really is a question for the underlying Android APIs but this is 100% my understanding :)
2. If the requested resolution *is not* supported by the device, it will look for the next highest resolution available (looking down) first. So, in that way, the plugin assumes that if a resolution is not supported, neither are higher resolutions. This is how the plugin is implemented across platforms I believe, so if you think this should be changed, I'd suggest opening another bug because that's out of scope of just the Android implementation. My change makes it so that if neither the requested resolution nor the lower resolutions are available, it will look at higher resolutions to see if they're available, which seems to be safer choice for cases like this bug you filed! The plugin does not change the size of the image at all, only tells the underlying Android APIs what resolution to target, so developers have to resize the image accordingly ([like in the plugin example app](https://github.com/flutter/packages/blob/e7ebc2071f5009beab5fa73ae5009d52839828f6/packages/camera/camera_android_camerax/example/lib/camera_preview.dart#L28)).

**Comment by andynewman10** [comment] 2023-10-31 18:38
> (not sure exactly what `processCameraImage` is but this is what I assume you're referencing). 

Sorry about `processCameraImage`, my mistake: in my code it is the function passed to `CameraController.startImageStream(<processCameraImage>)`. I am really focused on the camera stream, I should have pointed it out better.

> @andynewman10 To respond to your questions:
> 
> 1. Assuming the call succeeds, yes you will get a `CameraImage` with at least the resolution requested when taking a photo This really is a question for the underlying Android APIs but this is 100% my understanding :)

So, I am only guaranteed to get the requested resolution (or a higher resolution) **but only when taking a photo** (when `CameraController.takePicture` is called), **not during the camera stream** (`CameraController.startImageStream`)? From what you write, I understand that I might get a lower resolution during the camera stream, right? If you can confirm this, I would be really pleased - if this is the case I'll detect this and upscale appropriately.

> 2. If the requested resolution _is not_ supported by the device, it will look for the next highest resolution available (looking down) first. So, in a way, the plugin assumes that if a resolution is not supported, neither are higher resolutions or that the developer wishes to choose a maximum resolution of that requested (I'm not sure about the context on the original design decision here). This is how the plugin is implemented across platforms I believe, so if you think this should be changed, I'd suggest opening another bug because that's out of scope of just the Android implementation.

In question 1., above, you wrote that I am guaranteed to get AT LEAST the requested resolution, when taking a photo.
But here you write that I might get a lower resolution --> you mean for the camera stream, right?

> My change makes it so that if neither the requested resolution nor the lower resolutions are available, it will look at higher resolutions to see if they're available, which seems to be safer choice for cases like this bug you filed! The plugin does not change the size of the image at all, only tells the underlying Android APIs what resolution to target, so developers have to resize the image accordingly ([like in the plugin example app](https://github.com/flutter/packages/blob/e7ebc2071f5009beab5fa73ae5009d52839828f6/packages/camera/camera_android_camerax/example/lib/camera_preview.dart#L28)).

Quite frankly, I would completely leave this to user code. Basically, I expect your API *and* CameraX to

- see if the requested resolution is supported
- fail if it isn't. No big deal.
- it's up to user code to try alternate resolutions.

Everything else seems wrong to me. Smart logic is always best performed by user code, and the camera API is a striking example. Is it possible for you to call CameraX APIs to behave this way? I don't believe you will get developer bugs/issues if you adopt this behavior.

When I filed this bug I noticed:

- `camera_android` was accepting a resolution of `medium`
- `camera_android_camerax` wasn't. From there, I filed a bug because I suspected medium was a hardware-supported resolution on my Pixel 6a device and that `camera_android_camerax` was _mistakenly_ not supporting it.

**Comment by camsim99** [comment] 2023-10-31 21:13
What I wrote is not particular to taking pictures; I was just trying to address your question. We use the following strategies for finding a fallback resolution:

- https://developer.android.com/reference/androidx/camera/core/resolutionselector/ResolutionStrategy#FALLBACK_RULE_CLOSEST_LOWER_THEN_HIGHER() (for all non-video use cases)
- https://developer.android.com/reference/androidx/camera/video/FallbackStrategy#lowerQualityOrHigherThan(androidx.camera.video.Quality) (for video)

*Originally, we were using
- https://developer.android.com/reference/androidx/camera/core/resolutionselector/ResolutionStrategy#FALLBACK_RULE_CLOSEST_LOWER() (for all non-video use cases)
- https://developer.android.com/reference/androidx/camera/video/FallbackStrategy#lowerQualityThan(androidx.camera.video.Quality)https://developer.android.com/reference/androidx/camera/video/FallbackStrategy#lowerQualityThan(androidx.camera.video.Quality) (for video)

`camera_android` behaves more similarly to the old way* from my understanding. I'm not sure about how the Android camera libraries work under the hood fully, but to fix this bug, I found the new way to be a safer option that still follows the `camera_android` implementation in that it will first fallback to the next highest (but lower) resolution.

In terms of your suggestion

> Quite frankly, I would completely leave this to user code. Basically, I expect your API and CameraX to
> 
> see if the requested resolution is supported
> fail if it isn't. No big deal.
> it's up to user code to try alternate resolutions.

I would file another bug for this, as I think this is a proposal for new behavior of the `camera` plugin as a whole.

**Comment by camsim99** [comment] 2023-10-31 22:28
> @camsim99 sorry it took a few days to reply. There is no additional information in the log.
> 
> However, here is the stacktrace of the `_TypeError: Null check operator used on a null value` exception:
> 
> ```
> #0      AndroidCameraCameraX._getResolutionSelectorFromPreset (package:camera_android_camerax/src/android_camera_camerax.dart:892:33)
> #1      AndroidCameraCameraX.createCamera (package:camera_android_camerax/src/android_camera_camerax.dart:239:9)
> <asynchronous suspension>
> #2      CameraController._initializeWithDescription (package:camera/src/camera_controller.dart:316:19)
> <asynchronous suspension>
> ...
> ```
> 
> Version info (from my pubspec.lock):
> 
> * android_camera_camerax: 0.5.0+19
> * camera: 0.10.5+5

Thank you again for pointing out this issue too! This was a bug on my part. Going to submit https://github.com/flutter/packages/pull/5287 to finish fixing this issue :)

**Closed** 2023-11-02 21:43 UTC
Labels: platform-android, p: camera, package, has reproducible steps, P1, team-android, triaged-android, found in release: 3.13, found in release: 3.15

**Comment by andynewman10** [comment] 2023-11-03 07:52
I confirm the `_TypeError` error is gone on my Pixel 6a, when using the `max` setting with the `0.5.0+22` release!
