### ISSUE TITLE
[Proposal][Web]: Ability to change web-entry point with flutter build web

### ISSUE THREAD

**Issue by abegehr** [flutter/flutter#103777] opened 2022-05-14 02:15 UTC
## Use case

I'm trying to build two websites out of one flutter codebase. The website should have differing icons and manifest.json.

## Proposal

Ability to change web-entry point with `flutter build web` from the default `web/index.html` to another one like `web-admin/index.html` and receive build output in `build/web-admin/`.

**Comment by abegehr** [comment] 2022-05-14 03:19
My current workaround is having two web folders `web-admin` and `web-crm` and copying over files pre and post building for web. Example for web-admin:

Pre build
`rm -rf ./web && cp -r ./web-admin ./web`
Build web
`flutter build web --release`
Post build
`rm -rf ./web && mv ./build/web ./build/web-admin`

**Comment by darshankawar** [comment] 2022-05-16 06:41
@abegehr 
Thanks for the report. Please check [this](https://github.com/flutter/flutter/issues/59388#issuecomment-644202660) issue comment from Flutter team member about supporting flavors on web.

Based on that, I am going ahead and closing this as not feasible currently.

**Comment by abegehr** [comment] 2022-05-16 06:58
Hey @darshankawar, thank you for the swift reply. However, I think in this case @jonahwilliams comment does not apply since different dart entry points or dart-defines don't allow for changes to the web/index.html file. Specifically, I would need to set the html-file entry point, not just the dart-entry point to build two webapps with different icons and manifest.json from the same flutter codebase. Does that distinction make sense or is there a better way of achieving this?

**Comment by darshankawar** [comment] 2022-05-17 04:53
Thanks for the feedback @abegehr. Reopening and labeling for further insights from the team.

/cc @yjbanov

**Comment by ditman** [comment] 2022-05-27 02:18
I think this is a duplicate of https://github.com/flutter/flutter/issues/78254.

Closing this as a duplicate, but the idea of completely different `web` directories toggling slightly different output in the build directory is cool, and I don't think it was mentioned in the original issue.

Do you mind if we continue the discussion in #78254, @abegehr?

**Closed** 2022-05-27 02:19 UTC
Labels: platform-web, proposal, assigned for triage
