### ISSUE TITLE
[shared_preferences] No implementation found for method getAll on iOS

### ISSUE THREAD

**Issue by krillefear** [flutter/flutter#119318] opened 2023-01-27 08:14 UTC
## Steps to Reproduce

1. Run `SharedPreferences.getInstance()` on iOS
2. It will crash with:

```
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```

This happens since the upgrade to Flutter 3.7

<details>
<summary>Code sample</summary>

```dart
await SharedPreferences.getInstance();
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
No errors
```

```
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.0.1 22A400 darwin-arm64, locale de-DE)
    • Flutter version 3.7.0 on channel stable at /Users/christianpauly/develop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (vor 3 Tagen), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/christianpauly/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/christianpauly/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.74.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 73C57179-0498-4B4C-9BB6-FB949A5908E9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS
      13.0.1 22A400 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by stuartmorgan** [comment] 2023-01-27 10:50
Duplicate of https://github.com/flutter/flutter/issues/118401

**Closed by stuartmorgan** 2023-01-27 10:50 UTC
