### ISSUE TITLE
Emojis on ios are displayed in a weird way

### ISSUE THREAD

**Issue by karlchkeiban** [flutter/flutter#80082] opened 2021-04-08 21:14 UTC

**Comment by karlchkeiban** [comment] 2021-04-08 21:16
the size of the emojis (and space between 2 consecutive emojis) is off on ios wether it is in a textfield or in a simple text

**Comment by nt4f04uNd** [comment] 2021-04-08 21:30
duplicate of https://github.com/flutter/flutter/issues/28894

**Closed** 2021-04-08 22:00 UTC
Labels: r: duplicate
