### ISSUE TITLE
doctor check crashed if Visual Studio Preview is installed

### ISSUE THREAD

**Issue by mjauernig** [flutter/flutter#105116] opened 2022-06-01 11:27 UTC
## Steps to Reproduce

1. Install Visual Studio Preview 17.3
2. Download flutter stable from https://docs.flutter.dev/get-started/install/windows
3. run flutter doctor

## Result
[☠] Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Bad UTF-8 encoding (U+FFFD; REPLACEMENT CHARACTER) found while decoding string: [
        {
          "instanceId": "ff57f5ea",
          "installDate": "2022-06-01T06:09:04Z",
          "installationName": "VisualStudioPreview/17.3.0-pre.1.1+32519.111",
          "installationPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview",
          "installationVersion": "17.3.32519.111",
          "productId": "Microsoft.VisualStudio.Product.Professional",
          "productPath": "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\Common7\\IDE\\devenv.exe",
          "state": 4294967295,
          "isComplete": true,
          "isLaunchable": true,
          "isPrerelease": true,
          "isRebootRequired": false,
          "displayName": "Visual Studio Professional 2022",
          "description": "Professionelle IDE, optimal f�r kleine Teams",
          "channelId": "VisualStudio.17.Preview",
          "channelUri": "https://aka.ms/vs/17/pre/channel",
          "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
          Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
          "installedChannelUri": "https://aka.ms/vs/17/pre/channel",
          "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=661273#17.3.0-pre.1.1",
          "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=661288",
          "updateDate": "2022-06-01T06:09:04.0860793Z",
          "catalog": {
            "buildBranch": "d17.3",
            "buildVersion": "17.3.32519.111",
            "id": "VisualStudioPreview/17.3.0-pre.1.1+32519.111",
            "localBuild": "build-lab",
            "manifestName": "VisualStudioPreview",
            "manifestType": "installer",
            "productDisplayVersion": "17.3.0 Preview 1.1",
            "productLine": "Dev17",
            "productLineVersion": "2022",
            "productMilestone": "Preview",
            "productMilestoneIsPreRelease": "True",
            "productName": "Visual Studio",
            "productPatchVersion": "0",
            "productPreReleaseMilestoneSuffix": "1.1",
            "productSemanticVersion": "17.3.0-pre.1.1+32519.111",
            "requiredEngineVersion": "3.3.1070.38845"
          },
          "properties": {
            "campaignId": "2030:e1265c26-c435-4023-8b51-168a05801860",
            "channelManifestId": "VisualStudio.17.Preview/17.3.0-pre.1.1+32519.111",
            "nickname": "",
            "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\setup.exe"
          }
        }
      ]
      . The Flutter team would greatly appreciate if you could file a bug explaining exactly what you were doing when
      this happened:
      https://github.com/flutter/flutter/issues/new/choose

**Comment by exaby73** [comment] 2022-06-01 11:55
Closing as duplicate of #102451

**Closed by exaby73** 2022-06-01 11:55 UTC
Labels: in triage
