### ISSUE TITLE
What is the purpose of "flutter build ios" when it still rebuild during xcode archive

### ISSUE THREAD

**Issue by sooxt98** [flutter/flutter#71909] opened 2020-12-08 13:41 UTC
Is there a way to just trigger xcode version number without build the project with flutter cli?

**Comment by darshankawar** [comment] 2020-12-08 13:52
@sooxt98 
Your question is better suited for StackOver flow as it doesn't seem to describe a bug or a feature request.
Please see https://flutter.dev/community for resources.
Closing, as this isn't an issue but a support question.

**Comment by sooxt98** [comment] 2020-12-08 15:58
@darshankawar Its has been 6 month no one answering the questions, please open back my issue https://stackoverflow.com/questions/61851720/what-exactly-does-flutter-build-ios-do-is-this-really-necessary

**Comment by darshankawar** [comment] 2020-12-09 06:27
@sooxt98 
Please provide `flutter doctor -v` and details on the issue you are facing along with steps to replicate, related logs, expected and actual behavior.
Thanks.

**Comment by sooxt98** [comment] 2020-12-09 06:37
@darshankawar I think it happen in all the flutter version, not sure is xcode problem or flutter itself


```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 1.22.4 at /Users/sheldon/Documents/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sheldon/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (1 available)
    • Router (mobile) • 00008020-001C5D592EF8002E • ios • iOS 14.0.1

• No issues found!
```

**Comment by darshankawar** [comment] 2020-12-09 06:52
@sooxt98 
You should follow-up on the issue you linked, https://github.com/flutter/flutter/issues/64626. There are corresponding issue comments from Flutter team members and I already see you have commented on it, so better to track this issue at one place, rather than opening new issue. I am going ahead and closing this as duplicate of https://github.com/flutter/flutter/issues/64626.

**Closed by darshankawar** 2020-12-09 06:52 UTC
Labels: in triage
