### ISSUE TITLE
[tool_crash] ProcessException: The requested operation requires elevation. Command: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe", OS error code: 740

### ISSUE THREAD

**Issue by yacinegithub** [flutter/flutter#98655] opened 2022-02-17 11:36 UTC
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The requested operation requires elevation.
 Command: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe", OS error code: 740
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:42:22)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:691:24)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:567:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:690:12)
#6      ChromiumLauncher._spawnChromiumProcess (package:flutter_tools/src/web/chrome.dart:256:53)
#7      ChromiumLauncher.launch (package:flutter_tools/src/web/chrome.dart:221:36)
<asynchronous suspension>
#8      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:134:17)
<asynchronous suspension>
#9      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
<asynchronous suspension>
#10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19043.1466], locale en-US)
    • Flutter version 2.10.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (8 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\YASSINE\AppData\Local\Android\Sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = C:\Users\YASSINE\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necesth C++" workload, including all of its default components

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1466]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 91.0.864.70

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in

**Comment by darshankawar** [comment] 2022-02-17 13:24
Closing this as a duplicate of https://github.com/flutter/flutter/issues/78240

**Closed by darshankawar** 2022-02-17 13:24 UTC
Labels: in triage
