### ISSUE TITLE
Flutter how to set value for Flutter DropdownButton from Sqflite

### ISSUE THREAD

**Issue by bharadwajdaya** [flutter/flutter#60625] opened 2020-06-30 18:59 UTC
```dart
final dbHelper = DatabaseHelper.instance;
  List<Map<String,dynamic>> category_list;
  String category_val;
  _loadCatList() async{
    category_list=await dbHelper.queryAllCategories();
    
    print(category_list);
     setState(() {
    
     });
  }
  @override
  void initState() {
    super.initState();
    _loadCatList();
  }
  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Container(
      child: DropdownButton<String>(
        icon: Icon(Icons.arrow_drop_down),
        iconSize: 24,
         value: category_val=="" ? 'Others': category_val,
        onChanged: (String newValue) async{
          print(newValue);
          setState(() {
            category_val=newValue;
          });
        },
        hint: Text('Category'),
       
        items: category_list?.map<DropdownMenuItem<String>>((Map<String,dynamic> val){
          return DropdownMenuItem(
            value: val['name'],
            child: Text(val['name']),
          );
        })?.toList() ?? [],

      ),
    );
  }
```

How to set value in dropdownButton. First time its working when setting for the second time getting this error
There should be exactly one item with [DropdownButton]'s value: Range. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value

`package:flutter/src/material/dropdown.dart':`
```bash
Failed assertion: line 805 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1
```

**Comment by toritroniks** [comment] 2020-07-01 03:36
I tested your code, and it worked fine.

Your error appears when the selected value has repeated values in the list.

for example:
if your Categories looks like this
```
    final category_list = <Map<String, String>>[
      {'name': 'Others'},
      {'name': 'a'},
      {'name': 'b'},
      {'name': 'b'},
    ];
```
and your `category_val='b'` the dropdown wouldn't know witch 'b' to highlight as the selected element, so it throws an error.

Could you print your `category_list` here?

**Comment by iapicca** [comment] 2020-07-01 06:26
Hi @bharadwajdaya 
[dropdown](https://dartpad.dev/34af401a8977828c338d61022dd1e0e7) button seems to work just fine, 
I agree with @toritroniks  the issue seems to be caused by passing multiple identical values in the `category_list`'s values

Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-01 06:26 UTC
Labels: created via support template

**Comment by bharadwajdaya** [comment] 2020-07-02 09:04
Ya you were right I had duplicate entries ! In my case there is no need for Duplicate Entries but if at all there is a application which needs such case what shall we do !

**Comment by toritroniks** [comment] 2020-07-02 12:02
Hi @bharadwajdaya 
The dropdown items contains a value and a child.
The value is used to identify the selected item, so it needs to be unique.
The child is what the user will see in the item. So if you want duplicate items, just make the child duplicate, but keep the values unique.
