### ISSUE TITLE
ListView triggers errors when scrolling up and down fastly when there's a TextOverflow.ellipsis

### ISSUE THREAD

**Issue by ZikBurns** [flutter/flutter#72461] opened 2020-12-16 19:37 UTC
I have this list that I get from my Firestore using a StreamProvider.
```
class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return StreamProvider<List<Activity>>.value(
      value: ActivityService().activities,
      child: Scaffold(
        body: Container(
          color: Colors.black12,
          child: Column(
            children: [
              Flexible(
                child: HomeList(),
              )
            ],
          ),
        ),
        ),
      );
  }
}
```
HomeList calls this other class:
```
class HomeList extends StatefulWidget {
  @override
  _State createState() => _State();
}

class _State extends State<HomeList> {

  @override
  Widget build(BuildContext context) {
    var list_activities=Provider.of<List<Activity>>(context) ?? [];
      return ListView.builder(
          itemCount: list_activities.length,
          itemBuilder: (context,index){
            return Padding(
              padding: const EdgeInsets.all(4.0),
              child: Card(
                  child: ListTile(
                    title:Text(list_activities[index].title,style:TextStyle(fontSize: 18.0,fontWeight: FontWeight.bold)),
                    subtitle: Text(list_activities[index].desc, maxLines: 3,overflow: TextOverflow.ellipsis),
            )
              ),
            );
          }
      );
    }
  }
```
When I start in this in chrome, everything is fine. 

![image](https://user-images.githubusercontent.com/45241208/102398062-1525fc80-3fdf-11eb-8196-b5f858c88ed2.png)

The problem is that if I scroll up and down fastly with the wheel of my mouse, I get empty ListTiles:

![image](https://user-images.githubusercontent.com/45241208/102398320-6930e100-3fdf-11eb-8fc5-b86d9bdba66a.png)

But if I scroll up and down fastly dragging with left click of my mouse, the app stops showing this error: 

```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/html/picture.dart:54:10
canvas == null || !_recycledCanvases.contains(canvas)
is not true
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
PersistedPhysicalShape: is in an unexpected state.
Expected one of: PersistedSurfaceState.active, PersistedSurfaceState.released
But was: PersistedSurfaceState.pendingRetention
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Weirdly, if I delete the `overflow: TextOverflow.ellipsis` and leave the subtitle like below, both errors are gone:
`subtitle: Text(list_activities[index].desc, maxLines: 3)`
That's why I think that this error can be reproduced with any implementation of ListView with ListTiles (I haven't tried). 
Does anybody know why the use of TextOverflow.ellipsis in this case is causing this problem? 

This is my `flutter doctor -v`:
```
[√] Flutter (Channel dev, 1.25.0-8.0.pre, on Microsoft Windows [Version 10.0.19041.685], locale ca-ES)
    • Flutter version 1.25.0-8.0.pre at C:\src\flutter
    • Framework revision a12e2a473a (8 days ago), 2020-12-08 23:13:04 -0500
    • Engine revision df39e5c515
    • Dart version 2.12.0 (build 2.12.0-133.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\ZikBu\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at D:\Android
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 86.0.622.69

• No issues found!
```
When I deploy my app to host it, the problem is also when I access from chrome in android. BUT, the problem is not there when using the application built for android 
(apk). The problem may be TextOverflow.ellipsis in Web.

**Comment by ZikBurns** [comment] 2020-12-16 19:54
It may be connected to https://github.com/flutter/flutter/issues/72171

**Comment by darshankawar** [comment] 2020-12-17 08:03
@ZikBurns 
I believe this is a duplicate of https://github.com/flutter/flutter/issues/72171 since, even without using `textoverflow.ellipsis`, and scroll fast, we see blank list tiles and then throws the error you are seeing. 
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2020-12-17 08:03 UTC

**Comment by ZikBurns** [comment] 2020-12-17 08:41
> @ZikBurns 
> I believe this is a duplicate of https://github.com/flutter/flutter/issues/72171 since, even without using `textoverflow.ellipsis`, and scroll fast, we see blank list tiles and then throws the error you are seeing. 
> Closing this as duplicate. If you disagree, write in comments and I'll reopen it.
> Thanks.

You're right. I made some more tests and is not related to textoverflow. The error shows up anyway.
