### ISSUE TITLE
running gradle error

### ISSUE THREAD

**Issue by sami7568** [flutter/flutter#79154] opened 2021-03-26 18:36 UTC
```
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.0.0+1/lib/src/delegate_widget.dart:189:18: Error: Superclass has no method named 'inheritFromElement'.
    return super.inheritFromElement(ancestor, aspect: aspect);
                 ^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.0.0+1/lib/src/provider.dart:222:19: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildConte
xt'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'inheritFromWidgetOfExactType'.
        ? context.inheritFromWidgetOfExactType(type) as InheritedProvider<T>
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.0.0+1/lib/src/provider.dart:223:19: Error: The method 'ancestorInheritedElementForWidgetOfExactType' isn't defined for the c
lass 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorInheritedElementForWidgetOfExactType'.
        : context.ancestorInheritedElementForWidgetOfExactType(type)?.widget
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_google_places-0.2.4/lib/src/flutter_google_places.dart:72:15: Error: The method 'ancestorStateOfType' isn't defined for the cla
ss 'BuildContext'.
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ancestorStateOfType'.
      context.ancestorStateOfType(const TypeMatcher<PlacesAutocompleteState>());
              ^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.
```

**Comment by iapicca** [comment] 2021-03-27 05:31
@sami7568 
can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) **_without 3rd party plugins_**

> ^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/provider-3.0.0+1/lib/src/**_provider_**.dart:222:19: Error: The method 'inheritFromWidgetOfExactType' isn't defined for the class 'BuildConte
> xt'.
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/**_flutter_google_places_**-0.2.4/lib/src/flutter_google_places.dart:72:15: Error: The method 'ancestorStateOfType' isn't defined for the cla
> ss 'BuildContext'.

**Comment by sami7568** [comment] 2021-03-27 05:48
C:\Users\sa\Desktop\angela_flutter_cource\code\samiProjectCoding\practice\uberClone\taxi_app-master>flutter
run -v
[ +392 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log
-n 1 --pretty=format:%H
[ +510 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +3 ms] 8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[   +3 ms] executing: [C:\src\flutter/] git tag --points-at
8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[ +290 ms] Exit code 0 from: git tag --points-at
8962f6dc68ec8e2206ac2fa874da4a453856c7d3
[   +2 ms] 2.0.2
[ +173 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[ +416 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/stable
[   +2 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +200 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[ +434 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +217 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +3 ms] stable
[ +498 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[  +24 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[ +486 ms] executing:
C:\Users\sa\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +266 ms] List of devices attached
[  +46 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not
required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not
required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required,
skipping update.
[ +128 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required,
skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[ +634 ms] No supported devices connected.
[ +280 ms] The following devices were found, but are not supported by this
project:
                    Chrome (web) • chrome • web-javascript • Google Chrome
89.0.4389.90
                    Edge (web)   • edge   • web-javascript • Microsoft Edge
89.0.774.57
                    If you would like your app to run on web, consider
running `flutter create .` to generate projects for these platforms.

[  +98 ms] "flutter run" took 2,118ms.
[ +287 ms]
                    #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
                    #1      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:442:7)
                    <asynchronous suspension>
                    #2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:1114:5)
                    <asynchronous suspension>
                    #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1009:27)
                    <asynchronous suspension>
                    #4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #5      AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
                    <asynchronous suspension>
                    #6      CommandRunner.runCommand
(package:args/command_runner.dart:197:13)
                    <asynchronous suspension>
                    #7      FlutterCommandRunner.runCommand.<anonymous
closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
                    <asynchronous suspension>
                    #8      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #9      AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
                    <asynchronous suspension>
                    #10     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
                    <asynchronous suspension>
                    #11     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
                    <asynchronous suspension>
                    #12     run.<anonymous closure>
(package:flutter_tools/runner.dart:62:12)
                    <asynchronous suspension>
                    #13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
                    <asynchronous suspension>
                    #14     AppContext.run
(package:flutter_tools/src/base/context.dart:149:12)
                    <asynchronous suspension>
                    #15     runInContext
(package:flutter_tools/src/context_runner.dart:73:10)
                    <asynchronous suspension>
                    #16     main
(package:flutter_tools/executable.dart:90:3)
                    <asynchronous suspension>


[ +275 ms] ensureAnalyticsSent: 255ms
[  +23 ms] Running shutdown hooks
[   +4 ms] Shutdown hooks complete
[ +227 ms] exiting with code 1

**Comment by sami7568** [comment] 2021-03-27 05:51
code:



@override
Widget build(BuildContext context) {
  UserProvider userProvider = Provider.of<UserProvider>(context);
  AppStateProvider appState = Provider.of<AppStateProvider>(context);
  return SafeArea(
    child: Scaffold(
      key: scaffoldState,
      drawer: Drawer(
          child: ListView(
        children: [
          UserAccountsDrawerHeader(
              accountName: CustomText(
                text: userProvider.userModel?.name ?? "This is null",
                size: 18,
                weight: FontWeight.bold,
              ),
              accountEmail: CustomText(
                text: userProvider.userModel?.email ?? "This is null",
              )),
          ListTile(
            leading: Icon(Icons.exit_to_app),
            title: CustomText(text: "Log out"),
            onTap: () {
              userProvider.signOut();
              changeScreenReplacement(context, LoginScreen());
            },
          )
        ],
      )),

**Comment by sami7568** [comment] 2021-03-27 05:59
code


class TripWidget extends StatelessWidget {
  final CallsAndMessagesService _service = locator<CallsAndMessagesService>();

  @override
  Widget build(BuildContext context) {
    AppStateProvider appState = Provider.of<AppStateProvider>(context);

    return DraggableScrollableSheet(
        initialChildSize: 0.2,
        minChildSize: 0.05,
        maxChildSize: 0.8,
        builder: (BuildContext context, myscrollController) {
          return Container(
            decoration: BoxDecoration(color: white,
//                        borderRadius: BorderRadius.only(
//                            topLeft: Radius.circular(20),
//                            topRight: Radius.circular(20)),
                boxShadow: [
                  BoxShadow(
                      color: grey.withOpacity(.8),
                      offset: Offset(3, 2),
                      blurRadius: 7)
                ]),

**Comment by iapicca** [comment] 2021-03-27 06:57
@sami7568 

can you provide 
- your `flutter doctor -v`
- your `flutter run -v`(actually running the app)
> ```bash
> required, skipping update.
> [ +634 ms] No supported devices connected.
> [ +280 ms] The following devices were found, but are not supported by this
> project:
> ```

- a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) 
### without 3rd party plugins

> ```dart
> @override
> Widget build(BuildContext context) {
>   UserProvider userProvider = Provider.of<UserProvider>(context);
> ```
> ```dart
>   final CallsAndMessagesService _service = locator<CallsAndMessagesService>();
> ```

**Comment by sami7568** [comment] 2021-03-27 07:07
flutter doctor -v


C:\Users\sa\Desktop\angela_flutter_cource\code\samiProjectCoding\practice\uberClone\taxi_app-master>flutter doctor -v
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.2 at C:\src\flutter
    • Framework revision 8962f6dc68 (2 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\sa\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • STK L21 (mobile) • TMF4C19A30000867 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)       • edge             • web-javascript • Microsoft Edge 89.0.774.57

! Doctor found issues in 1 category.

**Comment by sami7568** [comment] 2021-03-27 07:40
flutter run -v
 #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)

**Comment by darshankawar** [comment] 2021-03-29 06:57
@sami7568 
First of all, please provide the requested details in formatted text instead of posting the code as a comment. 

From your `flutter run -v`, it shows below error:

```
[ +634 ms] No supported devices connected.
[ +280 ms] The following devices were found, but are not supported by this
project:
                    Chrome (web) • chrome • web-javascript • Google Chrome
89.0.4389.90
                    Edge (web)   • edge   • web-javascript • Microsoft Edge
89.0.774.57
                    If you would like your app to run on web, consider
running `flutter create .` to generate projects for these platforms.
```

Also, the errors seems to be pointing towards `provider` plugin which is 3rd party. Can you remove the plugin and try again to see if you still get same errors ?

**Comment by pedromassangocode** [comment] 2021-04-21 09:07
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-21 09:07 UTC
Labels: in triage, waiting for customer response
