### ISSUE TITLE
Project not compiling

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#80284] opened 2021-04-12 15:46 UTC
vytautas-pranskunas- opened this issue 19 minutes ago · 1 comment
Comments
@vytautas-pranskunas- vytautas-pranskunas- commented 19 minutes ago • 
Hello i was trying to upgrade flutter to null safety but realised that there amny dependencies that are not still ready So i decided to revert it back. After reverting my project is not compiling any more. I have tried everything i know even re-installed flutter. But i still getting this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > Problems reading data from Binary store in C:\Users\...\AppData\Local\Temp\gradle1077061253750656152.bin offset 379137 exists? true

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

I would appreciate if you can help me to resolve it.

Thanks

P. S. Flutter doctor has no issues

**Comment by iapicca** [comment] 2021-04-12 15:48
self duplicate of https://github.com/flutter/flutter/issues/80283

**Closed** 2021-04-12 17:02 UTC
