### ISSUE TITLE
TextOverflow: add option to put the ellipsis in the center rather than end

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#59540] opened 2020-06-16 08:43 UTC
## Use case

Sometime the text ending is too relevant and important to hide with the ellipsis. One obvious example is the file name extension.

## Proposal

Picture example taken from https://stackoverflow.com/questions/42900585/text-overflow-ellipsis-the-dots-should-be-center-of-the-text
![image](https://user-images.githubusercontent.com/1481807/84752518-86500d00-afc6-11ea-97b4-a7f589504ec6.png)

**Comment by pedromassangocode** [comment] 2021-03-01 08:18
Duplicate of https://github.com/flutter/flutter/issues/45336

**Closed by pedromassangocode** 2021-03-01 08:18 UTC
Labels: P5, a: typography, framework, proposal, severe: new feature
