### ISSUE TITLE
Performance lag with onPanUpdate event

### ISSUE THREAD

**Issue by dharanidharandharmasivam** [flutter/flutter#54359] opened 2020-04-09 14:50 UTC
I have shown an alert box on panning a container widget. In the **GestureDetector** widget, when **onPanUpdate**  event alone is initialized then panning is working fine. If other events (onTapDown, onDoubleTap, onLongPressMoveUpdate, etc) are initialized, there is performance lag i.e in order to show the alert box, we need to move a pretty far distance, then only the alert box appears.

**My Code**

> 
    import 'package:flutter/material.dart';
    void main() {
       return runApp(ChartApp());
    }
    class ChartApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
         return MaterialApp(
            home: MyHomePage(),
        );
      }
    }
    class MyHomePage extends StatefulWidget {
       // ignore: prefer_const_constructors_in_immutables
      MyHomePage({Key key}) : super(key: key);
      @override
     _MyHomePageState createState() => _MyHomePageState();
    }
    class _MyHomePageState extends State<MyHomePage> {
       @override
       Widget build(BuildContext context) {
            return Scaffold(
                appBar: AppBar(
                     title: const Text('Test'),
                ),
                body: GestureDetector(
                    // onTapDown: (TapDownDetails details) {},
                    // onDoubleTap: () {},
                    // onLongPressMoveUpdate: (LongPressMoveUpdateDetails details) {},
                    // onLongPress: () {},
                    // onLongPressEnd: (LongPressEndDetails details) {},
                    onPanUpdate: (DragUpdateDetails details) {
                        showDialog(
                         context: context,
                         builder: (BuildContext context) {
                           return AlertDialog(
                             title: new Text("Alert"),
                             actions: <Widget>[
                               new FlatButton(
                                  child: new Text("Close"),
                                  onPressed: () {
                                      Navigator.of(context).pop();
                                  },
                               ),
                             ],
                         );
                        },
                       );
                     },
                    child: Container(
                      decoration: BoxDecoration(
                        color: Colors.red[500],
                      ),
                    ),
        ));
      }
    }

**Steps to replicate the issue**

1. Run the above sample, now the pan on the container(red-colored area), panning will be working fine.
2. Uncomment the events in the GestureDetector widget and now pan, you need to move pretty far distance in comparing in step 1, to show the alert box.

**Other details:**

[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17134.1304], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at D:\Applications\flutter-sdk\flutter_windows_v1.12.13+hotfix.8-stable\flutter
    • Framework revision f139b11009 (10 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\DharanidharanDharmas\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\DharanidharanDharmas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Mi A1 • d2c9ceae0804 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by liyuqian** [comment] 2020-04-13 21:54
@goderbauer @tvolkert : this looks like a performance issue with the gesture detector. Do you know who's in charge of our gesture detector now?

**Comment by goderbauer** [comment] 2020-04-14 18:05
This is working as intended. When you have multiple gesture recognizers listening to pointer events at a certain location on the screen we need to disambiguate which gesture recognizer will win and process the gesture (details are described in https://flutter.dev/docs/development/ui/advanced/gestures#gesture-disambiguation). If the Pan gesture is competing with other gestures, it claims victory when the pointer has at least moved a distance of `kPanSlop` pixels (https://master-api.flutter.dev/flutter/gestures/kPanSlop-constant.html), which is currently defined to be 36 logical pixel. That's why you need to move further to recognize a Pan if you have competing gesture detectors.

**Comment by TahaTesser** [comment] 2020-09-03 15:03
Closing based https://github.com/flutter/flutter/issues/54359#issuecomment-613594324, confirmed to be working as intended 
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-09-03 15:03 UTC
Labels: f: gestures, framework, perf: speed, severe: performance
