### ISSUE TITLE
webview_flutter [null-safety]: `allowsInlineMediaPlayback` doesn't show video in full screen on mobile

### ISSUE THREAD

**Issue by gokhanbe** [flutter/flutter#73768] opened 2021-01-12 06:29 UTC
webview_flutter 1.0.7 using your package. https://github.com/flutter/plugins/pull/3334/commits/1d7e5ebab3c86bf5f2bf252ae14bca87be33c414 
I made the changes on the page. Although I made all the changes, the ipad is working in full screen but the iphone does not work. Thanks for your help

sample videos as below 
https://user-images.githubusercontent.com/57063848/104122686-8abf8700-5357-11eb-96b4-beb18cc5c4e1.mov
https://user-images.githubusercontent.com/57063848/104122691-901cd180-5357-11eb-9dcc-aa6b842263de.mov

sample code

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());


class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Welcome to Flutter',
      home: Scaffold(
        body: WebView(
          initialUrl: "https://www.medivizyon.com.tr/in5",
          javascriptMode: JavascriptMode.unrestricted,
          initialMediaPlaybackPolicy: AutoMediaPlaybackPolicy.always_allow,
          allowsInlineMediaPlayback: true,
          ),
      ),
    );
  }
```

```
flutter doctor -v

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale tr-TR)
    • Flutter version 1.22.5 at /Users/gokhan/flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/gokhan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1
```

pubspec.yaml

```
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  webview_flutter: ^1.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
```

**Comment by darshankawar** [comment] 2021-01-12 10:25
@gokhanbe 
The commit you referred earlier, ie, the PR was merged into master https://github.com/flutter/plugins/pull/3334, so I am not sure yet if it has landed in stable. Can you switch to latest master and try again to see if it works or no ?

**Comment by gokhanbe** [comment] 2021-01-12 13:04
@darshankawar 
I tried the package on the link but the result did not change. While the latest version is 1.0.7, the file on the site also has 1.0.8.
![image](https://user-images.githubusercontent.com/57063848/104317917-b4abb180-54ef-11eb-874b-125004c0d29a.png)

**Comment by darshankawar** [comment] 2021-01-13 06:14
@gokhanbe 
I tried on latest stable and master to use that property, but get compile error on it:

<img width="502" alt="Screenshot 2021-01-13 at 11 42 48 AM" src="https://user-images.githubusercontent.com/67046386/104413634-a6fc3780-5594-11eb-937f-31f2f9fb26b6.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.312, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.312 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7c75c01fc3 (3 hours ago), 2021-01-12 19:01:18 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Deepti 's iPhone (mobile) • 0554e90e563e81fd41bfd2ff9a2c6960595b9825 • ios
      • iOS 12.4.9
    • macOS (desktop)           • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 87.0.4280.141
    ! Error: Deepti 's iPhone is busy: Copying cache files from device. Xcode
      will continue when Deepti 's iPhone is finished. (code -10)

! Doctor found issues in 1 category.


```

</details>

**Comment by gokhanbe** [comment] 2021-01-13 06:41
@darshankawar 
Stable version does not have this feature. By changing the files in the link below, you can gain that feature.
https://github.com/flutter/plugins/pull/3334/files

**Comment by darshankawar** [comment] 2021-01-13 09:57
@gokhanbe 
You don't need to make changes to the files manually, just use the latest null safety version of the [plugin](https://pub.dev/packages/webview_flutter/versions/2.0.0-nullsafety.3/install) and issue is reproduced.


https://user-images.githubusercontent.com/67046386/104436414-93ac9480-55b3-11eb-9e6a-199ad1fb160a.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.312, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-IN)
    • Flutter version 1.26.0-2.0.pre.312 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7c75c01fc3 (7 hours ago), 2021-01-12 19:01:18 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)           •
      21150b119064aecc249dfcfe05e259197461ce23 • ios            • iOS 14.2
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • macOS (desktop)                     • macos
      • darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)                        • chrome
      • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.

```

</details>

**Comment by gokhanbe** [comment] 2021-01-13 17:48
@darshankawar 
As you said yes, there is no need to change it. Although I installed the package, I could not remove the difference between ipad and iphone. When the application is opened for the first time, the video does not open in full screen and control buttons appear. Ipad runs exactly the way I want it.

**Comment by kaiserleka** [comment] 2021-01-15 20:31
Check if FlutterWebView.m file contains **configuration.allowsInlineMediaPlayback = true;**
If not, copy package to project folder and add that line

**Comment by pythoneer** [comment] 2021-03-23 10:54
What is the current state of this issue? Flutter 2 is stable and released and the same is true for webview_flutter in version 2.0.2 . I can see [changes being made to allow this](https://github.com/flutter/plugins/blob/webview_flutter-v2.0.2/packages/webview_flutter/ios/Classes/FlutterWebView.m#L350)

```objective-c
    } else if ([key isEqualToString:@"allowsInlineMediaPlayback"]) {
      NSNumber* allowsInlineMediaPlayback = settings[key];
      _webView.configuration.allowsInlineMediaPlayback = [allowsInlineMediaPlayback boolValue];
    } else {
```

But i don't have the desired effect. It is still not working as described in this issue. If i fork this and [apply the changes manually](https://github.com/webviewflutter2-0-2allowInlinePatch/plugins/blob/master/packages/webview_flutter/ios/Classes/FlutterWebView.m#L96)

```objective-c
    WKWebViewConfiguration* configuration = [[WKWebViewConfiguration alloc] init];
    configuration.userContentController = userContentController;
    [self updateAutoMediaPlaybackPolicy:args[@"autoMediaPlaybackPolicy"]
                        inConfiguration:configuration];
    
    configuration.allowsInlineMediaPlayback = true;
```

it is working as expected.

**Comment by gokhanbe** [comment] 2021-03-23 11:23
> What is the current state of this issue? Flutter 2 is stable and released and the same is true for webview_flutter in version 2.0.2 . I can see [changes being made to allow this](https://github.com/flutter/plugins/blob/webview_flutter-v2.0.2/packages/webview_flutter/ios/Classes/FlutterWebView.m#L350)
> 
> ```objc
>     } else if ([key isEqualToString:@"allowsInlineMediaPlayback"]) {
>       NSNumber* allowsInlineMediaPlayback = settings[key];
>       _webView.configuration.allowsInlineMediaPlayback = [allowsInlineMediaPlayback boolValue];
>     } else {
> ```
> 
> But i don't have the desired effect. It is still not working as described in this issue. If i fork this and [apply the changes manually](https://github.com/webviewflutter2-0-2allowInlinePatch/plugins/blob/master/packages/webview_flutter/ios/Classes/FlutterWebView.m#L96)
> 
> ```objc
>     WKWebViewConfiguration* configuration = [[WKWebViewConfiguration alloc] init];
>     configuration.userContentController = userContentController;
>     [self updateAutoMediaPlaybackPolicy:args[@"autoMediaPlaybackPolicy"]
>                         inConfiguration:configuration];
>     
>     configuration.allowsInlineMediaPlayback = true;
> ```
> 
> it is working as expected.

Unbelievable. I did as in the codes you gave. Thank you so much.

**Comment by stuartmorgan** [comment] 2021-04-05 19:11
I'm confused by exactly what is being reported here; there's discussion of trying to use it in 1.0.x, which *did not have the feature*, but also discussion of differences between iPhone and iPad. There's also discussion of forking, but applying the change manually to a current fork shouldn't work since the code is already there so I'm unclear what is being forked (and what is being tested)

Can you clarify what exactly is the issue, when using 2.0.0 or later without modification?

**Comment by lgArlequin** [comment] 2021-04-05 19:13
Simply, the feature is not working even in the latest version, even though it has been added.

**Comment by lgArlequin** [comment] 2021-04-05 19:17
Sorry for not elaborating.
In my case, if I don't add the lines manually in a fork, no matter how much I add "allowsInlineMediaPlayback: true", the videos on ios keep playing in fullscreen by default.

**Comment by cyanglaz** [comment] 2021-04-05 19:49
I think the issue is that we are trying to change the configuration after applying it to the webview, which is not allowed. 
https://developer.apple.com/documentation/webkit/wkwebviewconfiguration?language=objc
```
You create a WKWebViewConfiguration object in your code, configure its properties, and pass it to the initializer of your WKWebView object. The web view incorporates your configuration settings only at creation time; you cannot change those settings dynamically later.
```

That explains why @gokhanbe 's example works. This can be fixed pretty easily by applying the setting earlier, before the configuration is set. https://github.com/flutter/plugins/blob/master/packages/webview_flutter/ios/Classes/FlutterWebView.m#L112

**Closed** 2021-04-07 04:09 UTC
Labels: P4, found in release: 1.26, has reproducible steps, p: first party, p: webview, plugin
