### ISSUE TITLE
On Android API version 33 devices, Japanese text starting with a newline character looks broken

### ISSUE THREAD

**Issue by risafj** [flutter/flutter#114963] opened 2022-11-09 09:48 UTC
## Steps to Reproduce

1. Execute `flutter run` on the sample repo 
2. On Android devices and emulators that have API version 33 (Android 13), the text looks broken (a phenomenon called 文字化け in Japanese).

__Sample repo__
https://github.com/risafj/tofu_example
*Note: This is the default Flutter project that's created with `flutter create`. I just changed one string to reproduce this bug. The same bug is happening with our production app as well.

**Expected results:** 

This string printed normally: `\r\nこんにちは。改行で始まる日本語の文章です。\r\nHello. This is a string starting with a newline character and containing Japanese characters.'`

**Actual results:** 

The English letters are printed just fine, but the Japanese letters are broken and look like squares with Xs.
Please see the image for details.

<img src="https://user-images.githubusercontent.com/43341670/200794326-c8c0adb6-163f-4697-a90b-c52fe9381cb2.png" width=400 />

<details>
  <summary>Logs</summary>

Note: I couldn't post my `flutter run --verbose` logs because Github said they're too long. If required, please ask and I will attach a file.

```
$ fvm flutter analyze                                   
Analyzing tofu_example...                                       
No issues found! (ran in 5.2s)
```

```
$ fvm flutter doctor -v
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.3.1 21E258 darwin-x64, locale en-JP)
    • Flutter version 3.3.7 on channel stable at /Users/risafujii/fvm/versions/3.3.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (7 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/risafujii/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Users/risafujii/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/risafujii/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7784292/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 12.3.1 21E258 darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by danagbemava-nc** [comment] 2022-11-09 12:10
Hi @risafj, it would appear that this has been fixed on the `master` channel as I can reproduce this on stable but not on master. 
Can you check on the master channel to see if this is the case for you as well?

<details>
<summary>screenshots</summary>

| stable | master | 
| -- | -- |
| <img src="https://user-images.githubusercontent.com/88313112/200826519-69c9e7c9-fa76-440f-8c56-1e33627cc87f.png"/> | <img src="https://user-images.githubusercontent.com/88313112/200826537-12966a86-c187-43ed-a2a8-e174f0efb486.png" /> |

</details>

**Comment by risafj** [comment] 2022-11-09 12:44
Hi @danagbemava-nc , thank you so much for your quick response!
I just checked and you're right, the bug can be reproduced on `stable` but not master.

**Comment by danagbemava-nc** [comment] 2022-11-09 13:17
Hi @risafj, thanks for confirming this. 

Per our triage policy, I'll be closing this issue since it has been fixed on the master channel. 

Thank you

**Closed by danagbemava-nc** 2022-11-09 13:17 UTC
Labels: in triage
