### ISSUE TITLE
Mac_ios flutter_gallery__transition_perf_e2e_ios32 Infra Failure, no steps completed

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#79493] opened 2021-03-31 22:28 UTC
Tree is closed on `Mac_ios flutter_gallery__transition_perf_e2e_ios32` infra failure, but no steps seems to have run.
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20flutter_gallery__transition_perf_e2e_ios32/351
https://ci.chromium.org/p/flutter/builders/prod/Mac_ios%20flutter_gallery__transition_perf_e2e_ios32/352

**Comment by keyonghan** [comment] 2021-03-31 22:31
bot is quarantined: https://chromium-swarm.appspot.com/bot?id=flutter-devicelab-mac-11
<img width="759" alt="Screen Shot 2021-03-31 at 3 30 40 PM" src="https://user-images.githubusercontent.com/54558023/113219350-11d51a80-9236-11eb-8aab-c65664b4ed5e.png">

Looking to see if recoverable remotely.

**Comment by jmagman** [comment] 2021-03-31 22:33
Was the infra failure because there were no un-quarantined agents?

**Comment by keyonghan** [comment] 2021-03-31 22:36
That's true. No resource is available to run the 32 test (since mac11 is the only bot).
```
flutter@flutter-devicelab-mac-11 ~ % idevicepair pair
QueryType failed, error code -256
```
@jmagman do you know how to fix this error code?

**Comment by jmagman** [comment] 2021-03-31 22:40
-256 is `LOCKDOWN_E_UNKNOWN_ERROR`, so that doesn't bode well.  What does `idevicepair validate` say?

**Comment by keyonghan** [comment] 2021-03-31 22:40
Here is from the swarming task page: https://chromium-swarm.appspot.com/task?id=52a32e7171e4ad10&o=true&w=true
![Screen Shot 2021-03-31 at 3 40 16 PM](https://user-images.githubusercontent.com/54558023/113220061-6af17e00-9237-11eb-9ab6-e0154726edb9.png)

**Comment by keyonghan** [comment] 2021-03-31 22:41
> -256 is `LOCKDOWN_E_UNKNOWN_ERROR`, so that doesn't bode well. What does `idevicepair validate` say?

It's the same:
```
flutter@flutter-devicelab-mac-11 ~ % idevicepair validate
QueryType failed, error code -256
```

**Comment by keyonghan** [comment] 2021-03-31 22:46
The certificate check also returns 0 valid identifies:
```
security find-identity -p codesigning -v
     0 valid identities found
```

**Comment by keyonghan** [comment] 2021-03-31 23:08
1 valid identity returned when running as `swarming` user, which is expected. So the issue is still with `idevicepair validate` error.

**Comment by keyonghan** [comment] 2021-03-31 23:17
@jmagman do you think we can skip the `idevicepair` check for 32 device?

**Comment by jmagman** [comment] 2021-03-31 23:21
I bet it's legitimately not paired, so the tests will fail.  These 9 year old phones are so hard to keep upright ☹️

**Comment by jmagman** [comment] 2021-03-31 23:22
https://github.com/flutter/flutter/pull/79496 is merged, lowering priority.

**Comment by godofredoc** [comment] 2021-03-31 23:28
The reason that phone requires manual intervention is because it doesn't have a sim card. Would it be worth adding one even if it is not activated?

**Comment by keyonghan** [comment] 2021-03-31 23:40
Filed a [request](http://fxbug.dev/73495) to manually reboot the device.

**Comment by keyonghan** [comment] 2021-04-01 16:08
The phone came back online. Reverting: https://github.com/flutter/flutter/pull/79560

**Comment by keyonghan** [comment] 2021-04-01 20:41
Reverted. Closing.

**Closed by keyonghan** 2021-04-01 20:41 UTC
Labels: P3, passed first triage, team, team: infra
