### ISSUE TITLE
Image Picker should be a Media Picker

### ISSUE THREAD

**Issue by ride4sun** [flutter/flutter#13234] opened 2017-11-28 22:54 UTC
It seems like the Image picker should be extended to be a media picker which should also support video picking and video recording that would keep both use cases consistent and a big help for every flutter developer.

**Comment by Skylled** [comment] 2017-11-29 14:46
Dupe of #13124

**Comment by Hixie** [comment] 2018-05-21 22:57
Closing as dupe.

**Closed by Hixie** 2018-05-21 22:57 UTC
