### ISSUE TITLE
Shift key gets "stuck" on windows

### ISSUE THREAD

**Issue by erickzanardo** [flutter/flutter#81079] opened 2021-04-23 21:03 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  late TextEditingController _controller;

  @override
  void initState() {
    super.initState();

    _controller = TextEditingController();
  }

  @override
  void dispose() {
    super.dispose();

    _controller.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('Type something'),
            TextField(controller: _controller),
          ],
        ),
      ),
    );
  }
}
````
3. Focus on the text field, hold shift and type a letter a
4. Release the shift key and type again the letter a

https://user-images.githubusercontent.com/835641/115929402-246df880-a45e-11eb-85f6-9a7af142cc77.mp4

**Expected results:** A lower case `a` should be input since the shift key is not pressed

**Actual results:** A upcase letter `A` is inputted instead

<details>

```
[√] Flutter (Channel master, 2.2.0-11.0.pre.260, on Microsoft Windows [versÃ£o 10.0.18363.900], locale pt-BR)
    • Flutter version 2.2.0-11.0.pre.260 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 59fc92168a (14 minutes ago), 2021-04-23 22:47:40 +0200
    • Engine revision 6fa0fb0059
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\erick\AppData\Local\Android\sdk
    X Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31205.134
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\erick\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.18363.900]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 2 categories.
```

</details>

**Comment by stuartmorgan** [comment] 2021-04-23 22:30
Duplicate of https://github.com/flutter/flutter/issues/75675

**Closed by stuartmorgan** 2021-04-23 22:30 UTC
Labels: a: text input, framework, passed first triage
