### ISSUE TITLE
GrMtlCommandBuffer::getRenderCommandEncoder(MTLRenderPassDescriptor*, GrMtlOpsRenderPass*) (in Flutter) (GrMtlCommandBuffer.mm:152)

### ISSUE THREAD

**Issue by zjrwdl** [flutter/flutter#104810] opened 2022-05-27 08:19 UTC
we met crash in flutter 2.8 which was similar with this case.
https://github.com/flutter/engine/pull/24503
https://github.com/flutter/flutter/issues/76772
which flutter version fix these crash?

<details>
<summary>Logs</summary>

```bash
GrMtlCommandBuffer::getRenderCommandEncoder(MTLRenderPassDescriptor*, GrMtlOpsRenderPass*) (in Flutter) (GrMtlCommandBuffer.mm:152)
GrMtlGpu::onGetOpsRenderPass(GrRenderTarget*, bool, GrAttachment*, GrSurfaceOrigin, SkIRect const&, GrOpsRenderPass::LoadAndStoreInfo const&, GrOpsRenderPass::StencilLoadAndStoreInfo const&, SkTArray<GrSurfaceProxy*, true> const&, GrXferBarrierFlags) (in Flutter) (GrMtlGpu.mm:173)
skgpu::v1::OpsTask::onExecute(GrOpFlushState*) (in Flutter) (OpsTask.cpp:618)
GrDrawingManager::flush(SkSpan<GrSurfaceProxy*>, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrBackendSurfaceMutableState const*) (in Flutter) (GrDrawingManager.cpp:234)
GrDrawingManager::flushSurfaces(SkSpan<GrSurfaceProxy*>, SkSurface::BackendSurfaceAccess, GrFlushInfo const&, GrBackendSurfaceMutableState const*) (in Flutter) (GrDrawingManager.cpp:533)
SkCanvas::onFlush() (in Flutter) (SkCanvas.cpp:510)
std::__1::__function::__func<flutter::GPUSurfaceMetal::AcquireFrameFromCAMetalLayer(SkISize const&)::$_1, std::__1::allocator<flutter::GPUSurfaceMetal::AcquireFrameFromCAMetalLayer(SkISize const&)::$_1>, bool (flutter::SurfaceFrame const&, SkCanvas*)>::operator()(flutter::SurfaceFrame const&, SkCanvas*&&) (in Flutter) (functional:1720)
flutter::SurfaceFrame::Submit() (in Flutter) (surface_frame.cc:43)
flutter::Rasterizer::DrawToSurfaceUnsafe(flutter::FrameTimingsRecorder&, flutter::LayerTree&) (in Flutter) (rasterizer.cc:556)
std::__1::__function::__func<flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&)::$_8, std::__1::allocator<flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&)::$_8>, void ()>::operator()() (in Flutter) (functional:1720)
fml::SyncSwitch::Execute(fml::SyncSwitch::Handlers const&) const (in Flutter) (sync_switch.cc:30)
flutter::Rasterizer::DrawToSurface(flutter::FrameTimingsRecorder&, flutter::LayerTree&) (in Flutter) (rasterizer.cc:479)
std::__1::__function::__func<flutter::Rasterizer::Draw(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >, std::__1::shared_ptr<flutter::Pipeline<flutter::LayerTree> >, std::__1::function<bool (flutter::LayerTree&)>)::$_2, std::__1::allocator<flutter::Rasterizer::Draw(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >, std::__1::shared_ptr<flutter::Pipeline<flutter::LayerTree> >, std::__1::function<bool (flutter::LayerTree&)>)::$_2>, void (std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >)>::operator()(std::__1::unique_ptr<flutter::LayerTree, std::__1::default_delete<flutter::LayerTree> >&&) (in Flutter) (functional:1720)
flutter::Rasterizer::Draw(std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >, std::__1::shared_ptr<flutter::Pipeline<flutter::LayerTree> >, std::__1::function<bool (flutter::LayerTree&)>) (in Flutter) (rasterizer.cc:183)
std::__1::__function::__func<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDraw(std::__1::shared_ptr<flutter::Pipeline<flutter::LayerTree> >, std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >)::$_14>, std::__1::allocator<fml::internal::CopyableLambda<flutter::Shell::OnAnimatorDraw(std::__1::shared_ptr<flutter::Pipeline<flutter::LayerTree> >, std::__1::unique_ptr<flutter::FrameTimingsRecorder, std::__1::default_delete<flutter::FrameTimingsRecorder> >)::$_14> >, void ()>::operator()() (in Flutter) (functional:1720)
fml::MessageLoopImpl::FlushTasks(fml::FlushType) (in Flutter) (message_loop_impl.cc:132)
fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*) (in Flutter) (message_loop_darwin.mm:81)
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
```
</details>

@[gaaclarke](https://github.com/gaaclarke)

**Comment by huycozy** [comment] 2022-05-27 11:33
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/104810#issue-1250481123 force flutter#v2.8.0 ios release arm64

**Comment by huycozy** [comment] 2022-05-27 11:59
Hi, thanks for filing the issue. 
I see there's an open issue addressing the case you described.
Closing as duplicate of #99313, so please follow up on it for further updates.

**Closed by huycozy** 2022-05-27 11:59 UTC
Labels: in triage
