### ISSUE TITLE
shared_preferences conflict with flutter_facebook_login 

### ISSUE THREAD

**Issue by Mustafa-Elsir** [flutter/flutter#59453] opened 2020-06-15 06:36 UTC
Hello:

I am using **shared_preferences** lib in my flutter app but when I install [flutter_facebook_login ](https://pub.dev/packages/flutter_facebook_login), I always got this error,

### I tried to solve it by:

- Run the command: `flutter clean` (Nothing changed)
- Cold run (close the entire app and run again) but nothing changed
- Uninstall the app from my phone and install it again (Nothing changed)

`E/flutter (16302): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

**Comment by TahaTesser** [comment] 2020-06-15 11:39
Hi @Mustafa-Elsir 
Conflicts from third party packages should be handled third party package maintainers

From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself.
 Please open the issue in the dedicated [repository](https://github.com/roughike/flutter_facebook_login/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-15 11:39 UTC
