### ISSUE TITLE
[image_picker] plugin causes crash in release appbundle.

### ISSUE THREAD

**Issue by zl910627** [flutter/flutter#61281] opened 2020-07-11 06:01 UTC
it works on debug build / release apk very well.
But when I build appbundle / upload to google play, it causes crash immediately when app startsup.
Here is logcat.
![image](https://user-images.githubusercontent.com/53897531/87217701-daa89b80-c37e-11ea-84e5-7d10bcf823fe.png)
this is result of `flutter doctor`
![image](https://user-images.githubusercontent.com/53897531/87217716-f613a680-c37e-11ea-93a5-24d5f981cf90.png)
Please please, let me know what is wrong.
Otherwise, I will lost my customers due this issue!
Thank you.

**Comment by TahaTesser** [comment] 2020-07-13 10:09
Hi @zl910627 
Can you please provide your `flutter build bundle --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by zl910627** [comment] 2020-07-13 11:04
thank you for your considering my report.
Nothing special really.
I think this issue is duplicate with issue #60505
But I think this needs to be fixed to get working on latest android gradle plugin - 4.0.0
It works on debug / release apk, but not on app bundle.
Thank you

**Comment by TahaTesser** [comment] 2020-07-14 07:15
duplicate of https://github.com/flutter/flutter/issues/58479

**Closed by TahaTesser** 2020-07-14 07:15 UTC
Labels: in triage
