### ISSUE TITLE
text selection toolbar over flow !

### ISSUE THREAD

**Issue by MoSala7** [flutter/flutter#35826] opened 2019-07-09 21:24 UTC
A problem happens in **TextFormField** Widget when trying to select part of the input text the **Selection toolbar** show up but not normally it overflow by 3.0 pixels from the right!!!
The funny part that it left more than 3.0 pixels from the left side of screen which its not centered!!

## Picture for the problem
https://ibb.co/k9Rk13M

## Logs

```
`Container(
                                height:
                                    MediaQuery.of(context).size.height * 0.25,
                                margin: EdgeInsets.fromLTRB(marginFixed * 0.5,
                                    0.0, marginFixed * 0.5, marginFixed * 0.5),
                                child: TextField(
                                  enableInteractiveSelection: true,
                                  expands: true,
                                  controller: _noteController,
                                  style: TextStyle(
                                      color: StyleCustom.txtPrimary,
                                      fontSize: 16.0),
                                  maxLines: null,
                                  minLines: null,
                                  decoration: InputDecoration(
                                    hintStyle: TextStyle(
                                        color: StyleCustom.txtSecondry),
                                    border: InputBorder.none,
                                    hintText: 'write your note here',
                                  ),
                                  onChanged: (String value) {
                                    debugPrint(value);
                                  },
                                ),
                              ),`
```

```
`
I/flutter ( 5019): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5019): The following assertion was thrown during layout:
I/flutter ( 5019): A RenderFlex overflowed by 3.0 pixels on the right.
I/flutter ( 5019):
I/flutter ( 5019): The overflowing RenderFlex has an orientation of Axis.horizontal.
I/flutter ( 5019): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter ( 5019): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter ( 5019): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter ( 5019): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter ( 5019): This is considered an error condition because it indicates that there is content that cannot be
I/flutter ( 5019): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter ( 5019): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter ( 5019): like a ListView.
I/flutter ( 5019): The specific RenderFlex in question is: RenderFlex#70842 relayoutBoundary=up4 OVERFLOWING:
I/flutter ( 5019):   creator: Row ← ConstrainedBox ← Container ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter ( 5019):     _InkFeatures-[GlobalKey#e7167 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter ( 5019):     PhysicalModel ← AnimatedPhysicalModel ← Material ← _TextSelectionToolbar ← CustomSingleChildLayout
I/flutter ( 5019):     ← ⋯
I/flutter ( 5019):   parentData: <none> (can use size)
I/flutter ( 5019):   constraints: BoxConstraints(0.0<=w<=360.0, h=44.0)
I/flutter ( 5019):   size: Size(360.0, 44.0)
I/flutter ( 5019):   direction: horizontal
I/flutter ( 5019):   mainAxisAlignment: start
I/flutter ( 5019):   mainAxisSize: min
I/flutter ( 5019):   crossAxisAlignment: center
I/flutter ( 5019):   textDirection: ltr
I/flutter ( 5019):   verticalDirection: down
I/flutter ( 5019): ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
I/flutter ( 5019): ════════════════════════════════════════════════════════════════════════════════════════════════════`
```

```
`[√] Flutter (Channel stable, v1.7.8+hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.7.8+hotfix.2 at C:\src\flutter
    • Framework revision 2e540931f7 (7 days ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\midos\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Java\jdk1.8.0_211\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.3
    • Flutter plugin version 36.0.4
    • Dart plugin version 191.7479.14

[√] VS Code, 64-bit edition (version 1.36.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • COR L29 • XTX7N18A31001552 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.`
```

**Comment by justinmc** [comment] 2019-07-10 15:10
Thanks for the issue @MoSala7.  Can you post the code that reproduces the overflow?

**Comment by MoSala7** [comment] 2019-07-10 22:03
> Thanks for the issue @MoSala7. Can you post the code that reproduces the overflow?

Thanks for notifying me, code updated in the isuue.

**Comment by westracer** [comment] 2019-07-11 09:12
I am experiencing the same problem. Material toolbar overflows almost every time when using russian localization (because words are quite long). Wrapping _TextSelectionToolbar in SingleChildScrollView with horizontal scroll axis could help (/material/text_selection.dart:176).

**Comment by justinmc** [comment] 2019-07-11 15:45
@westracer Does this happen on native Android as well with a Russian locale?  Does native handle it by scrolling the menu horizontally?

It seems like we should definitely handle the possibility of the selection menu being wider than the screen.  I don't see this happening on a simulated Pixel 2, but I imagine it could be common on narrower phones and other locales.

**Comment by westracer** [comment] 2019-07-12 02:29
@justinmc Yes, it happens. I've seen multiple ways to handle overflow on native Android. For example, rendering "more" button that shows overflowed buttons in a dropdown list ( [https://i.imgur.com/Up9iMZj.png](https://i.imgur.com/Up9iMZj.png) [https://i.imgur.com/p6tjkjB.png](https://i.imgur.com/p6tjkjB.png) ), making whole toolbar scrollable or just clipping text and removing padding for every toolbar button. 

In native iOS, to see overflowed buttons you need to press "right arrow" and it will show you next set of buttons ([https://i.imgur.com/D6Ac1KG.png](https://i.imgur.com/D6Ac1KG.png)).

**Comment by justinmc** [comment] 2019-07-16 17:53
@westracer Thanks for the screenshots.  We should probably support both of these.  I see the "more" button solution in the native Google Keep app on Android, so that should probably be our Android solution, along with the right arrow on iOS.

This will be even more important if we support custom items in the selection menu.

**Comment by MCOfficer** [comment] 2019-07-19 08:23
that looks a lot like #36005

**Comment by justinmc** [comment] 2019-07-19 15:26
Thanks for finding the duplicate.  I'll close that one to focus the discussion here.

**Comment by CloudyPadmal** [comment] 2019-07-27 11:37
When the screen is wide enough to fit the whole menu, this issue doesn't occur. I'm also having this issue where it doesn't happen in emulator when the screen is wide but in my real device where the screen width is smaller. Anyone have a workaround? :)

**Comment by Nico04** [comment] 2019-07-27 13:56
Personally I had to change the App Button Theme's minWidth as a workaround

**Comment by henriquearthur** [comment] 2019-07-28 01:18
Is it possible to change the toolbar font size as workaround until this is fixed?

**Comment by Nico04** [comment] 2019-07-28 11:49
@henriquearthur you can try by modifying the ThemeData of the buttonTheme property of the App main theme

**Comment by adarshgurjar** [comment] 2019-08-02 16:40
@justinmc , When we can expect the issue fixed officially ? The only workaround seems to be changing minWidth in ThemeData as suggested by @Nico04

**Comment by justinmc** [comment] 2019-08-02 18:15
As a quick and dirty workaround using horizontal scrolling, you could replace this line:

https://github.com/flutter/flutter/blob/5df17acb1f852f6a3c1ad0b7fcd869bb09e13db0/packages/flutter/lib/src/material/text_selection.dart#L61

With this:
```dart
        child: ListView(
          scrollDirection: Axis.horizontal,
          children: items,
        ),
```

**Comment by justinmc** [comment] 2019-08-02 18:16
Long term we'll need to implement the native solution on Android and iOS.  Here is what it looks like on Android:

<img width="250" src="https://user-images.githubusercontent.com/389558/62390332-dccf6c80-b516-11e9-80cb-22bb924ab070.gif" />

**Comment by adarshgurjar** [comment] 2019-08-03 04:11
> Long term we'll need to implement the native solution on Android and iOS. Here is what it looks like on Android:
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/389558/62390332-dccf6c80-b516-11e9-80cb-22bb924ab070.gif">

Looks good, hope we get to see it on flutter soon, thanks !

**Comment by daka-kolp** [comment] 2019-08-14 12:27
The problem with _TextSelectionToolbar in sourse file  flutter/packages/flutter/lib/src/material/text_selection.dart. I don't know how it works with cupertino. 
But simple solution that I use: 
rows 57-63 in text_selection.dart: 

return Material(
      elevation: 1.0,
      child: Container(
        height: _kToolbarHeight,
        child: FittedBox(
           child: Row(mainAxisSize: MainAxisSize.min, children: items)),
      ),
    );

I don't think it is right, because the TextField can have more than 4 options.

**Comment by jaumard** [comment] 2019-08-15 09:48
same here (in Spanish)
![Screenshot_20190815-043348](https://user-images.githubusercontent.com/2970449/63087451-86b8eb00-bf52-11e9-950c-ec3903d1d451.png)

**Comment by deisold** [comment] 2019-08-22 14:45
Are there any news on the topic? I'm having this problem as well.

**Comment by justinmc** [comment] 2019-08-22 15:21
There is a PR open with a temporary solution, it's just missing a bugfix and some tests: https://github.com/flutter/flutter/pull/38561

**Comment by deisold** [comment] 2019-08-22 15:26
@justinmc in what branch will it be available then? dev? or something more stable?

**Comment by justinmc** [comment] 2019-08-22 15:39
If/when that PR is merged, it will immediately end up in master.  Then it will follow the usual process of being propagated out to our other [channels](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels) over time.

**Comment by JayakumarB** [comment] 2019-08-25 16:18
> ```dart
> ListView(
>           scrollDirection: Axis.horizontal,
>           children: items,
>         ),
> ```



> As a quick and dirty workaround using horizontal scrolling, you could replace this line:
> 
> https://github.com/flutter/flutter/blob/5df17acb1f852f6a3c1ad0b7fcd869bb09e13db0/packages/flutter/lib/src/material/text_selection.dart#L61
> 
> With this:
> 
> ```dart
>         child: ListView(
>           scrollDirection: Axis.horizontal,
>           children: items,
>         ),
> ```

This works like a charm, but need a temporary fix.

**Comment by codetime79** [comment] 2019-08-29 13:11
same in persian language !!

**Comment by imlegend19** [comment] 2019-09-01 07:15
I have implemented the native solution for text selection. I have added valid tests for my code, but still, my PR fails some tests. Can someone tell me what's the problem?

**Comment by duzenko** [comment] 2019-09-02 12:59
Same error on LG G6 and _English_ localization
Most vexing
![Screenshot_2019-09-02-15-49-17 1](https://user-images.githubusercontent.com/1481807/64116157-320ed000-cd9a-11e9-8e4e-ffbee11c9d70.png)

**Comment by CalmAndCoDe** [comment] 2019-09-04 08:46
same here, any progress ?

**Comment by rallz-dev** [comment] 2019-09-04 15:36
I also have the same problem, with Brazilian Portuguese. Any plans of fixing this in some new release ?

**Comment by justinmc** [comment] 2019-09-04 17:32
There is a PR linked above from @imlegend19 that is working towards fixing this.

**Comment by jonataslaw** [comment] 2019-09-05 18:38
I also have the same problem, with Brazilian Portuguese.

**Comment by EArminjon** [comment] 2019-09-06 05:10
Same issue as duzenko...
My tree : 
CupertinoTheme => scaffold  => ListView => scaffold => Container => TextFormField

[✓] Flutter (Channel beta, v1.9.1+hotfix.1, on Linux, locale fr_FR.UTF-8)
    • Flutter version 1.9.1+hotfix.1 at /home/user/flutter
    • Framework revision a1fb3fabec (il y a 2 jours), 2019-09-03 18:07:52 -0700
    • Engine revision cc88fa45db
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/user/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/user/Android/Sdk
    • Java binary at: /home/user/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/user/Documents/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /home/user/Documents/idea-IU-182.4892.20
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6262.58

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

**Comment by jobehi** [comment] 2019-09-07 16:11
Hi, any official fix ?

**Comment by MCOfficer** [comment] 2019-09-07 16:59
if you read up a bit, you will see that there is a PR in the works.

**Comment by geegog** [comment] 2019-09-11 05:23
I will love to see this issue fixed :)

**Comment by felipewom** [comment] 2019-09-16 14:41
Any updates?

**Comment by mbdax034** [comment] 2019-10-03 15:57
The current solution for this probleme is to change **buttonTheme** and 
**textTheme** in the MaterialApp
for me 
```dart
theme: ThemeData(
        buttonTheme: ButtonThemeData(minWidth: 10,),
        textTheme: TextTheme(button: TextStyle(fontSize: 10)),
)
```

**Comment by louia** [comment] 2019-10-31 10:25
Same here in French with Samsung S8 on the latest stable version of flutter : 1.9.1+hotfix.6

**Comment by justinmc** [comment] 2019-11-05 20:55
Related: https://github.com/flutter/flutter/issues/44005

**Comment by bobajeff** [comment] 2019-11-13 02:02
I see that this is being worked on but here's mine.

![Screenshot_1573613501](https://user-images.githubusercontent.com/8573364/68726470-2ce2b400-0587-11ea-9e6a-31c683c0432a.png)

**Comment by justinmc** [comment] 2019-11-13 17:52
Another related issue was opened that showed Large Display settings causing this problem as well: https://github.com/flutter/flutter/issues/44005.

**Comment by CristopherVidalMachado** [comment] 2019-11-27 20:24
My temporary solution

`ThemeData(
      buttonTheme: ButtonThemeData(minWidth: 12)
);`

**Comment by thibaultrousset** [comment] 2019-12-04 14:13
Same issue on Samsung J6 french.
my temporary solution in flutter/packages/flutter/lib/src/material/text_selection.dart : 

`    return Material(
      elevation: 1.0,
      child: Container(
        height: _kToolbarHeight,
        child: FittedBox(
          child: Row(mainAxisSize: MainAxisSize.max, children: items),
        ),
      ),
    );
`

**Comment by akshaykhatale** [comment] 2019-12-09 03:25
I had the same problem 
 ```
ThemeData(   
        buttonTheme:ButtonThemeData(minWidth: 5),
        scaffoldBackgroundColor: Colors.blue,
        primarySwatch: Colors.blue,
      ),
```
this is  a temporary fix but works for me.

**Comment by slemankfa** [comment] 2019-12-09 23:41
it works with me ^^>.

**Comment by DenisBogatirov** [comment] 2019-12-12 17:42
Any progress here? Flutter already released stable version 1.12 and this is still an issue ((

**Comment by morijoon** [comment] 2019-12-23 12:08
The best way I found is to wrap the Row(children: items, mainAxisSize: MainAxisSize.min); with SingleChildScrollView. works perfect.

**Comment by phanirithvij** [comment] 2019-12-27 07:47
This also occurs with a regular `TextField` widget.

e.g.
```dart
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(home: TextFieldApp()));

class TextFieldApp extends StatefulWidget {
  @override
  _TextFieldAppState createState() => _TextFieldAppState();
}

class _TextFieldAppState extends State<TextFieldApp> {
  TextEditingController controller;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: TextFormField(
        keyboardType: TextInputType.multiline,
        controller: controller,
        maxLines: 10,
        maxLength: null,
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    controller = TextEditingController();
    controller.text = 'line 1\nline2 contents\nline3';
    super.initState();
  }
}
```

Error info.
```dart
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 6.0 pixels on the right.

User-created ancestor of the error-causing widget was
    MaterialApp 
lib\main.dart:3
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#6e948 relayoutBoundary=up4 OVERFLOWING
════════════════════════════════════════════════════════════════════════════════
```

[Screenshot](https://user-images.githubusercontent.com/29627898/71507584-06fd3e80-28ab-11ea-8091-a0f508fc5042.png)

**Comment by Kacper1263** [comment] 2019-12-28 18:36
> The best way I found is to wrap the Row(children: items, mainAxisSize: MainAxisSize.min); with SingleChildScrollView. works perfect.

Thanks. Works well. You just have to remember about setting scrollDirection to Axis.horizontal

**Comment by gokul-a-krishnan** [comment] 2019-12-30 05:18
See My Answer on [Stackoverflow](https://stackoverflow.com/a/59525924/9889855)

**Warning!** 

Create a Backup of `flutter/packages/flutter/lib/src/material/text_selection.dart` else you cant **update or upgrade** Flutter

I made a little Improvements on [SergICE's](https://stackoverflow.com/users/11643644/sergice) [answer](https://stackoverflow.com/questions/56974261/flutter-text-selection-toolbar-overflow-showed-on-tap/57559924?r=SearchResults&s=2|21.4276#57559924).

In `flutter/packages/flutter/lib/src/material/text_selection.dart` on `Line: 60`

Change 

     return Material(
          elevation: 1.0,
          child: Container(
            height: _kToolbarHeight,
            child: Row(mainAxisSize: MainAxisSize.min, children: items), //Remove This line
            child: _buildTextHandler(items), //add this
        ),
    );

now create a method `_buildTextHandler(List<Widget> items)` in `_TextSelectionToolbar` Class

      List<Widget>_buildTextHandler(List<Widget> items) {
        if (items.length > 3) {
          return SizedBox(
            width: 300.0,
            child: ListView(
              scrollDirection: Axis.horizontal,
              children: items,
            ),
          );
        } else {
          return Row(mainAxisSize: MainAxisSize.min, children: items);
        }
     }

**Comment by tnoor-co** [comment] 2020-01-01 00:16
>  width: 300.0,

@gokul-a-krishnan - I'm intrigued as to why the arbitrary 300 pixel was chosen?

--

Out of all of the suggestions, the following worked best for me.  

- Updating `buttonTheme` `minWidth` in the app `ThemeData`

```
theme: ThemeData(
        buttonTheme: ButtonThemeData(minWidth: 10,),
)
```

-  Encapsulating the Text Selection FlatButton list `items` with a `ListView` & shrinkWrap = true.

```
    return Material(
      elevation: 1.0,
      child: Container(
        height: _kToolbarHeight,
        child: ListView(
          shrinkWrap: true,
          scrollDirection: Axis.horizontal,
          children: items,
        ),
      ),
    );
```

It made the buttons more condensed and did not make it seem very small (e.g. when the font size was changed). This issue seems to primarily happen on smaller width devices (mine happened at 360px), so making it smaller seemed counter-intuitive.

Thank y'all!

**Comment by christianarduino** [comment] 2020-01-05 20:37
Same problem with Italian

> ```
> ThemeData(   
>   buttonTheme:ButtonThemeData(minWidth: 5),
> ),
> ```
> 
> this is a temporary fix but works for me.

It seems to work

**Comment by fernandolopes** [comment] 2020-01-10 19:01
> Veja Minha resposta no [Stackoverflow](https://stackoverflow.com/a/59525924/9889855)
> 
> **Atenção!**
> 
> Crie um backup, caso `flutter/packages/flutter/lib/src/material/text_selection.dart`contrário você não pode **atualizar ou atualizar o** Flutter
> 
> Fiz [algumas](https://stackoverflow.com/users/11643644/sergice) melhorias na [resposta ](https://stackoverflow.com/questions/56974261/flutter-text-selection-toolbar-overflow-showed-on-tap/57559924?r=SearchResults&s=2%7C21.4276#57559924)[do SergICE](https://stackoverflow.com/users/11643644/sergice) .
> 
> Em `flutter/packages/flutter/lib/src/material/text_selection.dart`diante`Line: 60`
> 
> mudança
> 
> ```
>  return Material(
>       elevation: 1.0,
>       child: Container(
>         height: _kToolbarHeight,
>         child: Row(mainAxisSize: MainAxisSize.min, children: items), //Remove This line
>         child: _buildTextHandler(items), //add this
>     ),
> );
> ```
> 
> agora crie um método `_buildTextHandler(List<Widget> items)`na `_TextSelectionToolbar`classe
> 
> ```
>   Widget _buildTextHandler(List<Widget> items) {
>     if (items.length > 3) {
>       return SizedBox(
>         width: 300.0,
>         child: ListView(
>           scrollDirection: Axis.horizontal,
>           children: items,
>         ),
>       );
>     } else {
>       return Row(mainAxisSize: MainAxisSize.min, children: items);
>     }
>  }
> ```

Wouldn't it be a case of creating a fork to solve the problem?

**Comment by Jemaz** [comment] 2020-01-12 08:14
> This also occurs with a regular `TextField` widget.
> 
> e.g.
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> void main() => runApp(MaterialApp(home: TextFieldApp()));
> 
> class TextFieldApp extends StatefulWidget {
>   @override
>   _TextFieldAppState createState() => _TextFieldAppState();
> }
> 
> class _TextFieldAppState extends State<TextFieldApp> {
>   TextEditingController controller;
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(),
>       body: TextFormField(
>         keyboardType: TextInputType.multiline,
>         controller: controller,
>         maxLines: 10,
>         maxLength: null,
>       ),
>     );
>   }
> 
>   @override
>   void dispose() {
>     super.dispose();
>   }
> 
>   @override
>   void initState() {
>     controller = TextEditingController();
>     controller.text = 'line 1\nline2 contents\nline3';
>     super.initState();
>   }
> }
> ```
> 
> Error info.
> 
> ```dart
> ════════ Exception caught by rendering library ═════════════════════════════════
> The following assertion was thrown during layout:
> A RenderFlex overflowed by 6.0 pixels on the right.
> 
> User-created ancestor of the error-causing widget was
>     MaterialApp 
> lib\main.dart:3
> The overflowing RenderFlex has an orientation of Axis.horizontal.
> The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
> 
> Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
> This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.
> 
> The specific RenderFlex in question is: RenderFlex#6e948 relayoutBoundary=up4 OVERFLOWING
> ════════════════════════════════════════════════════════════════════════════════
> ```
> 
> [Screenshot](https://user-images.githubusercontent.com/29627898/71507584-06fd3e80-28ab-11ea-8091-a0f508fc5042.png)

I will add that I too am getting the same bug with a simple TextFormField (using the same code as @phanirithvij provided).

I added my Flutter doctor's response if it's any help:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found
```

**Comment by MsXam** [comment] 2020-01-17 21:03
Have the exact same issue.

The only fix is to disable the toolbar until this is fixed...

Easily done with **enableInteractiveSelection: false,**


![image](https://user-images.githubusercontent.com/18722796/72645914-ac687700-396c-11ea-8f13-4f9804d7808d.png)

**Comment by kamleshwebtech** [comment] 2020-03-09 08:26
> The best way I found is to wrap the Row(children: items, mainAxisSize: MainAxisSize.min); with SingleChildScrollView. works perfect.

Getting below error:
RenderBox was not laid out: RenderRepaintBoundary#2f05f relayoutBoundary=up4 NEEDS-PAINT

**Comment by kamleshwebtech** [comment] 2020-03-09 08:32
> Long term we'll need to implement the native solution on Android and iOS. Here is what it looks like on Android:
> 
> <img alt="" width="250" src="https://user-images.githubusercontent.com/389558/62390332-dccf6c80-b516-11e9-80cb-22bb924ab070.gif">

how to do in flutter?, please explain. Thanks

**Comment by gokul-a-krishnan** [comment] 2020-03-09 09:21
> > width: 300.0,
> 
> @gokul-a-krishnan - I'm intrigued as to why the arbitrary 300 pixel was chosen?
I choose 300 pixel becoz it will hide some text on "select all" so user think it's scrollable (inspired from Realms devices)

**Comment by justinmc** [comment] 2020-03-09 15:52
@kamleshwebtech The full solution is under review in https://github.com/flutter/flutter/pull/49391, it's not yet released.

**Comment by justinmc** [comment] 2020-03-11 22:11
This has now been fixed in master with https://github.com/flutter/flutter/issues/50935.  iOS fix is in the works.  I'll link to it when I open a PR.

**Comment by tonikwater** [comment] 2020-04-08 21:24
Another simple solution I found using the `Wrap Widget` is the following ...
In `flutter\packages\flutter\lib\src\material\text_selection.dart` replace line 60 with this:
`        child: Wrap(direction: Axis.vertical, children: items),`
and line 21 with this:
`const double _kToolbarHeight = 96.0;`
I set the height to `96.0` because it's the threshold value where the toolbar becomes quadratic and looks like this now:
![textSelectionToolbarFix](https://user-images.githubusercontent.com/51098576/78835240-1afb2500-79f0-11ea-8e17-2891ecc50a11.png)

**Closed** 2020-04-14 16:49 UTC
Labels: a: annoyance, a: text input, customer: amplify, customer: crowd, f: material design, framework

**Comment by justinmc** [comment] 2020-04-14 17:45
The iOS solution (https://github.com/flutter/flutter/pull/54140) has been merged.

Check the version tags on the merge commits to see what version these fixes will end up in.
Android: https://github.com/flutter/flutter/commit/4841a7ed6fb36774974d6cf2aafb7f791908ab8d
iOS: https://github.com/flutter/flutter/commit/f646e26e9044d3e565a79a77f32965be020fa3d9

**Comment by nohli** [comment] 2020-06-03 10:36
> Have the exact same issue.
> 
> The only fix is to disable the toolbar (Assuming you dont need cut/copy/select etc) until this is fixed...
> 
> Easily done with **enableInteractiveSelection: false,**
> 
> ![image](https://user-images.githubusercontent.com/18722796/72645914-ac687700-396c-11ea-8f13-4f9804d7808d.png)

Has anyone addressed the vertical overflow?

Like in this issue: https://github.com/flutter/flutter/issues/58512

The font size should have a minimum and maximum - like the native iOS controls have.

Right now it looks bad with a small iOS font size and it doesn't fit with a large font size (not even through accesibility, a regular larger iOS font size).

**Comment by justinmc** [comment] 2020-06-04 19:27
@nohli Can you open a new issue to track the vertical size problems?  I don't think there's an open issue about that right now.
