### ISSUE TITLE
The following assertion was thrown while handling a gesture: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 829 pos 12: '_hold == null': is not true.

### ISSUE THREAD

**Issue by 99robong** [flutter/flutter#154386] opened 2024-08-30 05:56 UTC
### Steps to reproduce

1. In a NotificationListener<ScrollNotification>, set a onNotification like sample code.
2.  Run code.
3. Scroll, and Scroll again before the first scroll ends.

### Expected results

Scroller may be faster.

### Actual results

Scroll stopped and the error causes.

### Code sample

<details open><summary>Code sample</summary>

```dart
NotificationListener<ScrollNotification> {
onNotification: (ScrollNotification notification) {
                    if (notification is ScrollStartNotification) {
                      isScrolling = true;
                    }
                    if (notification.context != null && isScrolling) {
                      if (notification.metrics.axis == Axis.vertical) {
                        ScrollController scroller =
                            timetableProvider.tableVertScrollController!;
                        if (!scroller.position.isScrollingNotifier.value) {
                          var currentScrollPosition = scroller.position.pixels;

                          timetableProvider.setScroller(scroller, timeHeight,
                              (currentScrollPosition / timeHeight).round());
                          isScrolling = false;
                        }
                      }
                      if (notification.metrics.axis == Axis.horizontal) {
                        ScrollController scroller =
                            timetableProvider.tableHorScrollController!;
                        if (!scroller.position.isScrollingNotifier.value) {
                          var currentScrollPosition = scroller.position.pixels;

                          timetableProvider.setScroller(scroller, timeWidth,
                              (currentScrollPosition / timeWidth).round());
                          isScrolling = false;
                        }
                      }
                    }
                    return false;
                  },
  child: [Some ScrollView]
}


void setScroller(ScrollController controller, double timeLength, int mul) {
    double targetOffset = timeLength * mul;
    if (controller.offset != targetOffset) {
      if (controller.hasClients && controller.position.pixels != targetOffset) {
        controller.animateTo(
          targetOffset,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeInOut,
        );
        notifyListeners();
      }
    }
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 829 pos 12: '_hold == null':
is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      ScrollableState._handleDragStart (package:flutter/src/widgets/scrollable.dart:829:12)
#3      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:787:53)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#5      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:787:7)
#6      DragGestureRecognizer._checkDrag (package:flutter/src/gestures/monodrag.dart:754:5)
#7      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:681:7)
#8      GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:282:12)
#9      GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:233:11)
#10     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:53:12)
#11     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:444:13)
#12     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:648:15)
#13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
#21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#25     _invoke1 (dart:ui/hooks.dart:328:13)
#26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#27     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
(elided 2 frames from class _AssertionError)

Handler: "onStart"
Recognizer:
  HorizontalDragGestureRecognizer#19581
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 834 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 834 pos 12: '_hold == null || _drag == null': is not true.
Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 840 pos 12: '_hold == null || _drag == null': is not true.
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.5 23F79 darwin-arm64, locale en-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.0)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by danagbemava-nc** [comment] 2024-08-30 07:55
Closing this as a duplicate of https://github.com/flutter/flutter/issues/14452

**Closed by danagbemava-nc** 2024-08-30 07:55 UTC
Labels: in triage
