### ISSUE TITLE
Default iOS project from flutter create lacks "+" icon in action button

### ISSUE THREAD

**Issue by collinjackson** [flutter/flutter#5389] opened 2016-08-15 17:09 UTC
## Steps to Reproduce

flutter create myapp
cd myapp
flutter run

<img width="423" alt="screen shot 2016-08-15 at 10 08 57 am" src="https://cloud.githubusercontent.com/assets/394889/17672254/598b2594-62d0-11e6-81a8-fb7fa07aded3.png">

## Flutter Doctor

[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/jackson/git/flutter
    • Framework revision facd3e238f (33 minutes ago), engine revision fe509b0d96

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/jackson/Library/Android/sdk/
    • Platform android-N, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.31

It works fine on Android

**Comment by sethladd** [comment] 2016-08-15 17:22
Good catch!

When we fix this, is it something testable?

**Comment by eseidelGoogle** [comment] 2016-08-15 17:25
Reference tests could catch this kind of thing: https://github.com/flutter/flutter/issues/3227

**Comment by Hixie** [comment] 2016-08-15 18:22
This is probably a dupe of https://github.com/flutter/flutter/issues/5395

**Comment by chinmaygarde** [comment] 2016-08-16 00:18
Dupe of https://github.com/flutter/flutter/issues/5410.

**Comment by jakobr-google** [comment] 2016-08-16 13:55
If you run `flutter build ios && flutter install`, it works fine (for me, at least). If I use `flutter run`, ti can't find its resources (wrong fonts are used).

If I remove the app's preferences plist after using `flutter run`, and then restart the app, it works fine. So everything's installed correctly, the app just can't find its resources when invoked with the arguments that `flutter run` uses.

**Comment by eseidelGoogle** [comment] 2016-08-16 14:45
I wonder if https://github.com/flutter/flutter/issues/5417 is at all related.  That was running flutter_gallery on the iOS simulator.

**Comment by jakobr-google** [comment] 2016-08-16 14:54
I think it's the same. Looks like we're unable to load assets if we're invoked with the `--flx`, `--dart-main`, and `--packages` arguments that `flutter run` uses.

**Comment by Hixie** [comment] 2016-08-16 19:34
I can't test this because of https://github.com/flutter/flutter/issues/5398 (flutter run hangs on project made with flutter create)

**Comment by jakobr-google** [comment] 2016-08-16 19:38
As a workaround to #5398, try opening ios/Runner.xcworkspace in Xcode. After doing that, `flutter run` should work for that project.

**Comment by chinmaygarde** [comment] 2016-08-16 19:43
https://github.com/flutter/engine/commit/5515d3e27288db7ed1eef5b97a7c2e185881a309 fixes this issue. Needs an engine roll.

**Comment by Hixie** [comment] 2016-08-16 19:44
Even without that fix, I can't reproduce this.

**Comment by sethladd** [comment] 2016-09-14 17:32
Going to close. Please reopen if you still see the issue.

**Closed by sethladd** 2016-09-14 17:32 UTC
Labels: affects: dev experience, ⌺‬ platform-ios, ⚠ bug
