### ISSUE TITLE
OutlinedButton not respecting fixedSize theme

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#79894] opened 2021-04-06 21:17 UTC
The outlinedButtonTheme is specified as such:

```dart
  theme.copyWith(
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        minimumSize: const Size(buttonMinWidth, defaultButtonHeight),
        fixedSize: const Size.fromHeight(defaultButtonHeight),
      ),
    ),
  ),
```

but outlined buttons are rendering at a different height than `defaultButtonHeight`. The same theming is applied for `textButtonTheme` and `elevatedButtonTheme` and button heights for those buttons are `defaultButtonHeight` as intended.

**Comment by pedromassangocode** [comment] 2021-04-07 11:10
I cannot reproduce this issue, the code bellow generated the button in the following image.

![Screen Shot 2021-04-07 at 12 09 08](https://user-images.githubusercontent.com/67424416/113857149-118ad100-979a-11eb-9993-bb1b55151395.png)


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PlayGround',
      theme: ThemeData().copyWith(
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            minimumSize: Size(50, 50),
            fixedSize: Size.fromHeight(200),
          ),
        ),
      ),
      home: Scaffold
        (body: Center(
          child: OutlinedButton(child: Text('fixedSize: 200'), onPressed: () {},)),
      ),
    );
  }
}
```
</details>

**Comment by HansMuller** [comment] 2021-04-09 16:08
I just checked this as well, on master.  Made the minimum height match the fixed height per the original sample. Seems to work as expected:

<img width="284" alt="Screen Shot 2021-04-09 at 9 08 21 AM" src="https://user-images.githubusercontent.com/1377460/114209142-28a0fe80-9913-11eb-867b-f0aa2543c792.png">

```dart
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            OutlinedButton(
              style: OutlinedButton.styleFrom(
                minimumSize: Size(50, 50),
                fixedSize: Size.fromHeight(50),
              ),
              onPressed: () {},
              child: Text('fixedSize: height=50'),
            ),
            SizedBox(width: 16),
            Container(
              color: Colors.green,
              width: 100,
              height: 50,
            ),
          ],
        ),
      ),
    );
  }
}

void main() {
  runApp(MaterialApp(home: Home())),
}
```

**Comment by HansMuller** [comment] 2021-04-14 15:37
I'm closing this as not a bug.  @kenzieschmoll - if there's a test case that fails, please reopen the issue with it.

**Closed by HansMuller** 2021-04-14 15:37 UTC
Labels: f: material design, framework, in triage, waiting for customer response
