### ISSUE TITLE
Improve error message when ui-as-code is used with incorrect SDK version constraints

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#52826] opened 2020-03-18 16:44 UTC
We should show a meaningful error message if ui-as-code features are used with SDK version `>=2.1.0 <3.0.0` (the constraint generated by `flutter create` )

## Steps to reproduce
1. Create a new Flutter project
2. Observe that pubspec.yaml specifies SDK version `>=2.1.0 <3.0.0`
3. Use update `main.dart` to use ui-as-code features:

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var otherWidgets = <Widget>[];
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            ...otherWidgets
          ],
        ),
      ),
    );
  }
}

```
4. Observe analyzer errors: `error • This requires the 'spread-collections' experiment to be enabled • lib/main.dart:15:13 • experiment_not_enabled`

## Use case

Creating a new Flutter project doesn't allow for ui-as-code features and the error messages are misleading.

## Proposal

Instead of this type of error, we should let users know that they need to update their SDK version constraint to `>=2.3.0 <3.0.0` in `pubspec.yaml`

**Comment by johnpryan** [comment] 2020-03-18 16:47
Moved to https://github.com/dart-lang/sdk/issues/41096

**Comment by mit-mit** [comment] 2020-04-03 07:58
Re-activating; given the error message looks OK in the Dart SDK, but not in the Flutter SDK, is there something here the Flutter SDK overrides?

Repro main.dart:
```dart
main() {
  var l = [...[1,2,3], 4];
  print(l);
}
```

Analysis output:
```console
$ dartanalyzer bin/main.dart
Analyzing bin/main.dart...
  hint • The for, if, and spread elements weren't supported until version 2.3.0, but this code is required to be able to run on earlier versions. • bin/main.dart:2:12 • sdk_version_ui_as_code

$ flutter analyze .
Analyzing testapp2...

  error • This requires the 'spread-collections' experiment to be enabled • lib/main.dart:2:12 • experiment_not_enabled
```

**Comment by TahaTesser** [comment] 2020-09-01 15:34
Looks like this is now throwing same error as dartanalyzer  when changing min sdk to 2.2.0 for testing on latest master 
```
Analyzing master_flutter...                                             

   info • The for, if, and spread elements weren't supported until version 2.3.0, but this code is required to be able to
          run on earlier versions • lib/main.dart:5:5 • sdk_version_ui_as_code

1 issue found. (ran in 3.6s)
```

<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() {
  var l = [
    ...[1, 2, 3],
    4
  ];
  print(l);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

```

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.162, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-2.0.pre.162 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision bcfad2068e (77 minutes ago), 2020-09-01 08:34:25 -0400
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6
      19G2021
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome
      84.0.4147.135

• No issues found!
```

</details> 

Closing as fixed . If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by johnpryan** [comment] 2020-09-01 19:44
If the min SDK is `2.0.0`, the error is:

```
  error • This requires the 'spread-collections' language feature to be enabled •
         lib/main.dart:2:12 • experiment_not_enabled
```

If the error is 2.2.0, the error is 

```
   info • The for, if, and spread elements weren't supported until version 2.3.0, but this
          code is required to be able to run on earlier versions • lib/main.dart:2:12 •
          sdk_version_ui_as_code
```

Running `dartanalyzer lib/main.dart` works in both cases.

**Comment by TahaTesser** [comment] 2020-09-02 11:30
@johnpryan 
Thank you, I can reproduce the issue 

```
tahatesser@Tahas-MacBook-Pro master_flutter % flutterm analyze
Analyzing master_flutter...                                             

   info • The for, if, and spread elements weren't supported until version 2.3.0, but this code is required to be able to
          run on earlier versions • lib/main.dart:5:5 • sdk_version_ui_as_code

1 issue found. (ran in 2.1s)
tahatesser@Tahas-MacBook-Pro master_flutter % flutterm analyze
Analyzing master_flutter...                                             

  error • This requires the 'spread-collections' language feature to be enabled • lib/main.dart:5:5 • experiment_not_enabled

1 issue found. (ran in 3.2s)
tahatesser@Tahas-MacBook-Pro master_flutter % 
```

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.39, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.39 at /Users/tahatesser/Code/flutter_master
    • Framework revision a8281e31af (18 hours ago), 2020-09-01 10:57:59 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios            • iOS 13.7
    • iPhone 11 (mobile)     • EDB19945-0B9F-4A6E-BAA1-425E68E3B6D6 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64     • Mac OS X
      10.15.6 19G2021
    • Web Server (web)       • web-server                           • web-javascript • Flutter
      Tools
    • Chrome (web)           • chrome                               • web-javascript • Google
      Chrome 85.0.4183.83

• No issues found!


```

</details>

**Comment by christopherfujino** [comment] 2022-09-27 20:19
cc @eliasyishak

**Comment by eliasyishak** [comment] 2022-09-28 19:29
Closing after confirming that the error messages are more helpful now. `dart analyze` even suggests to update the sdk version in description.

```
eliasyishak-macbookpro:testing_app eliasyishak$ flutter analyze
Analyzing testing_app...                                                

   info • The for, if, and spread elements weren't supported until version 2.3.0, but this code is required to be able to run on earlier versions • lib/main.dart:5:5 • sdk_version_ui_as_code

1 issue found. (ran in 0.6s)
eliasyishak-macbookpro:testing_app eliasyishak$ dart analyze
Analyzing testing_app...               0.7s

   info • lib/main.dart:5:5 • The for, if, and spread elements weren't supported until version 2.3.0, but this code is required to be able to run on earlier versions. Try updating the SDK constraints. •
          sdk_version_ui_as_code

1 issue found.
```


Flutter Doctor Info
```
[!] Flutter (Channel master, 3.4.0-29.0.pre.73, on macOS 12.6 21G115 darwin-arm64, locale en)
    • Flutter version 3.4.0-29.0.pre.73 on channel master at /Users/eliasyishak/Desktop/flutter
    ! Upstream repository https://github.com/eliasyishak/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/eliasyishak/flutter.git to dismiss this error.
    • Framework revision 48653e4853 (8 days ago), 2022-09-20 11:16:55 -0400
    • Engine revision 4e051fed8a
    • Dart version 2.19.0 (build 2.19.0-221.0.dev)
    • DevTools version 2.17.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.
```

**Closed by eliasyishak** 2022-09-28 19:29 UTC
Labels: tool, dependency: dart, a: error message, has reproducible steps, P4, found in release: 1.22
