### ISSUE TITLE
Text align Justify right is missing in flutter

### ISSUE THREAD

**Issue by aboda1986** [flutter/flutter#28700] opened 2019-03-01 06:44 UTC
Hi,

i try to justify Arabic text to right, but text always justify left.

here is the code:
`Directionality(
          textDirection: TextDirection.rtl,
         child:Text( 'يمكنكم مشاهدة هذا الفيديو وجميع فيديوهاتنا عبر قناة بابلي تولز الفضائية على النايل سات تردد 11177 أفقي ترميز 27500',  textAlign: TextAlign.justify,   )
)`

kindly check the issue, and add TextAlign.justifyRight attribute.

**Comment by aboda1986** [comment] 2019-03-01 06:46
flutter doctor:

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)
```

**Comment by TarekkMA** [comment] 2019-03-02 19:02
I'm also having this issue.
The text is justified but for lines that take the whole width of the screen but for things like the last line or lines that contain few words it is aligned to the left, not the right.

``flutter doctor -v`` yields the following.
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/tarekkma/Developer/Libs/flutter
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

Text Code
```dart
Text(
            article.content,
            style: TextStyle(color: Colors.white,fontSize: 16),
            textAlign: TextAlign.justify,
            textDirection: TextDirection.rtl,
          ),
```

![screen shot 2019-03-02 at 8 39 45 pm](https://user-images.githubusercontent.com/6633545/53686067-67732c00-3d2b-11e9-8ede-f1de11c6c4d7.png)

**Comment by a7medsalah** [comment] 2019-06-12 19:20
I am having the same problem.

**Comment by MahdiPishguy** [comment] 2019-06-14 12:37
+1

**Comment by aliforever** [comment] 2019-06-28 14:13
+1

**Comment by Saifallak** [comment] 2019-07-13 19:01
not working on Channel stable, v1.7.8+hotfix.3 too

**Comment by Saifallak** [comment] 2019-07-13 19:05
@HansMuller any updates on this ?!

**Comment by HansMuller** [comment] 2019-07-15 22:39
CC @GaryQian

**Comment by GaryQian** [comment] 2019-07-16 00:29
Acknowledged, I can look at this.

**Comment by GaryQian** [comment] 2019-07-16 23:16
https://github.com/flutter/engine/pull/9859 Fixes this.

**Comment by GaryQian** [comment] 2019-07-17 20:57
This should be fixed. When justifying, we now right align when the paragraph is in a RTL language, and left align when the paragraph is in a LTR language.

**Comment by GaryQian** [comment] 2019-07-17 20:58
If anyone needs the ability to left align RTL languages (or vice versa) please let me know! With this fix, it is no longer possible to left align RTL or right align LRT when justifying, but I imagine not many people want to do that anyways.

**Comment by mahmoudparandeh** [comment] 2019-08-24 06:39
> 
> 
> If anyone needs the ability to left align RTL languages (or vice versa) please let me know! With this fix, it is no longer possible to left align RTL or right align LTR when justifying, but I imagine not many people want to do that anyways.

when will this fix add to release version? i need this feature.

**Comment by MahdiPishguy** [comment] 2019-08-24 08:18
@GaryQian "but I imagine not many people want to do that anyways." ???

that's a good reason to justify :) it should be accessible for developers

**Comment by Saifallak** [comment] 2019-08-24 08:41
@GaryQian i think we need this. because if you have string like this:

```
اهلا \n بكم في تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا 
```

you will get first word aligned left not right

**Comment by MahdiPishguy** [comment] 2019-08-24 09:13
@Saifallak could you attach screen shot?

**Comment by Saifallak** [comment] 2019-08-24 12:22
Okay i'm using default app created with flutter create
just changed the text to:

```
            Text(
              'اهلا \n بكم في تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا'
              ' تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا',
              textAlign: TextAlign.justify,
              textDirection: TextDirection.rtl,
            ),
```


# Full Code:
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'اهلا \n بكم في تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا'
              ' تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا تطبيقنا',
              textAlign: TextAlign.justify,
              textDirection: TextDirection.rtl,
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

# ScreenShot

![Screenshot_1566649165](https://user-images.githubusercontent.com/6053156/63637202-3cceb400-c67a-11e9-8cc5-3a3e512eb109.png)


# Flutter Doctor -v

```
flutter doctor -v
[√] Flutter (Channel dev, v1.9.2, on Microsoft Windows [Version 10.0.18362.295], locale en-US)
    • Flutter version 1.9.2 at C:\SDKs\flutter
    • Framework revision 6815f540c9 (5 days ago), 2019-08-19 20:37:36 -0400
    • Engine revision 3e10d92b2b
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\SDKs\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6459

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by pr-Mais** [comment] 2019-08-31 03:55
Having same issue, I hope it can get resolved soon...
Need to justify text written in Arabic.
![Screenshot_1567223692](https://user-images.githubusercontent.com/41123719/64059025-5319ca00-cbbc-11e9-8500-d368ed5a3c82.png)

**Comment by Saifallak** [comment] 2019-09-01 12:28
> Having same issue, I hope it can get resolved soon...
> Need to justify text written in Arabic.
> 
> ![Screenshot_1567223692](https://user-images.githubusercontent.com/41123719/64059025-5319ca00-cbbc-11e9-8500-d368ed5a3c82.png)

your issue is fixed in #9859 , just move to beta or dev channel

**Comment by Tokenyet** [comment] 2019-09-03 10:21
For chinese, justify with center is more common to use, I hope there are `JustifyCenter`, `JustifyRight`, and `JustifyLeft` someday 🙏

**Comment by OsamaAbbas** [comment] 2019-09-03 14:41
> Thanks for reporting, I'll take a look at this!

The issue now is that the [RTL] justification breaks if the text has `\n` in it. All the paragraphs will be justified to the left except the last one. That's why the first word in @Saifallak screenshot went to the left while the other paragraph was justified correctly.

The issue exists even if we divide the text into `TextSpan` widgets. (this was the workaround that I thought it may work).

**Comment by GaryQian** [comment] 2019-09-03 20:37
Just an update, this is in the queue of issues that I plan to resolve! I am currently working through a backlog of other bugs, and I will try to get to this ASAP. Thanks everyone for providing this feedback, and please continue to update with relevant information as it will help track down what's going on here. I hope I can get to resolving this very soon.

**Comment by GaryQian** [comment] 2019-09-03 21:37
Turns out this was easier to fix than I thought. I put up https://github.com/flutter/engine/pull/11842 which should resolve this.

**Closed** 2019-09-03 23:42 UTC
Labels: a: typography, framework

**Comment by GaryQian** [comment] 2019-09-03 23:45
Landed the fix. This will need to roll into the framework before it is available on the master channel.

Please let me know if there are any other questions regarding this bug and thanks everyone for all the input, it allowed me to rapidly zero in on the issue!

**Comment by OsamaAbbas** [comment] 2019-09-06 15:42
> Landed the fix. This will need to roll into the framework before it is available on the master channel.

I have tested the fix. While it is better than before, it still has some serious issues.

See this screenshot:

![image](https://user-images.githubusercontent.com/3346502/64440260-a03ef400-d106-11e9-8234-f2637b60ae68.png)
> 1 - العربية لغة رسمية في كل دول الوطن العربي إضافة إلى كونها لغة رسمية في تشاد وإريتريا وإسرائيل. وهي إحدى اللغات الرسمية الست في منظمة الأمم المتحدة، ويُحتفل باليوم العالمي للغة العربية في 18 ديسمبر كذكرى اعتماد العربية بين لغات العمل في الأمم المتحدة.\n1 - العربية لغة رسمية في كل دول الوطن العربي إضافة إلى كونها لغة رسمية في تشاد وإريتريا وإسرائيل. وهي إحدى اللغات الرسمية الست في منظمة الأمم المتحدة، ويُحتفل باليوم العالمي للغة العربية في 18 ديسمبر كذكرى اعتماد العربية بين لغات العمل في الأمم المتحدة.\n

As mentioned here: https://github.com/flutter/flutter/issues/39755#issuecomment-528157466, mixed text breaks the RTL justification. The engine apparently considers the numbers (0-9) as latin text.

So I tried to replace (0123456789) with (٠١٢٣٤٥٦٧٨٩), here is the result:

![image](https://user-images.githubusercontent.com/3346502/64440813-9ff32880-d107-11e9-9a56-3cb830586727.png)
> "١ - العربية لغة رسمية في كل دول الوطن العربي إضافة إلى كونها لغة رسمية في تشاد وإريتريا وإسرائيل. وهي إحدى اللغات الرسمية الست في منظمة الأمم المتحدة، ويُحتفل باليوم العالمي للغة العربية في ١٨ ديسمبر كذكرى اعتماد العربية بين لغات العمل في الأمم المتحدة.\n١ - العربية لغة رسمية في كل دول الوطن العربي إضافة إلى كونها لغة رسمية في تشاد وإريتريا وإسرائيل. وهي إحدى اللغات الرسمية الست في منظمة الأمم المتحدة، ويُحتفل باليوم العالمي للغة العربية في ١٨ ديسمبر كذكرى اعتماد العربية بين لغات العمل في الأمم المتحدة.\n"

It's better, but still not perfect. The digit ١ (that is 1) has no bad effect, but the digit ٨ (that is 8) breaks its line.

Of course if we inserted some English letters it will break too.

Hope you find this review useful and find some time to look into it!

**Comment by pr-Mais** [comment] 2019-09-06 15:57
> > Landed the fix. This will need to roll into the framework before it is available on the master channel.
> 
> I have tested the fix. While it is better than before, it still has some serious issues.
> 
> See this screenshot:
> 
> ![image](https://user-images.githubusercontent.com/3346502/64440260-a03ef400-d106-11e9-8234-f2637b60ae68.png)
> 
> > 1 - العربية لغة رسمية في كل دول الوطن العربي إضافة إلى كونها لغة رسمية في تشاد وإريتريا وإسرائيل. وهي إحدى اللغات الرسمية الست في منظمة الأمم المتحدة، ويُحتفل باليوم العالمي للغة العربية في 18 ديسمبر كذكرى اعتماد العربية بين لغات العمل في الأمم المتحدة.\n1 - العربية لغة رسمية في كل دول الوطن العربي إضافة إلى كونها لغة رسمية في تشاد وإريتريا وإسرائيل. وهي إحدى اللغات الرسمية الست في منظمة الأمم المتحدة، ويُحتفل باليوم العالمي للغة العربية في 18 ديسمبر كذكرى اعتماد العربية بين لغات العمل في الأمم المتحدة.\n
> 
> As mentioned here: [#39755 (comment)](https://github.com/flutter/flutter/issues/39755#issuecomment-528157466), mixed text breaks the RTL justification. The engine apparently considers the numbers (0-9) as latin text.
> 
> So I tried to replace (0123456789) with (٠١٢٣٤٥٦٧٨٩), here is the result:
> 
> ![image](https://user-images.githubusercontent.com/3346502/64440813-9ff32880-d107-11e9-9a56-3cb830586727.png)
> 
> > "١ - العربية لغة رسمية في كل دول الوطن العربي إضافة إلى كونها لغة رسمية في تشاد وإريتريا وإسرائيل. وهي إحدى اللغات الرسمية الست في منظمة الأمم المتحدة، ويُحتفل باليوم العالمي للغة العربية في ١٨ ديسمبر كذكرى اعتماد العربية بين لغات العمل في الأمم المتحدة.\n١ - العربية لغة رسمية في كل دول الوطن العربي إضافة إلى كونها لغة رسمية في تشاد وإريتريا وإسرائيل. وهي إحدى اللغات الرسمية الست في منظمة الأمم المتحدة، ويُحتفل باليوم العالمي للغة العربية في ١٨ ديسمبر كذكرى اعتماد العربية بين لغات العمل في الأمم المتحدة.\n"
> 
> It's better, but still not perfect. The digit ١ (that is 1) has no bad effect, but the digit ٨ (that is 8) breaks its line.
> 
> Of course if we inserted some English letters it will break too.
> 
> Hope you find this review useful and find some time to look into it!

I have the same issue, look here:

![Screenshot_1567785269](https://user-images.githubusercontent.com/41123719/64442068-d749e100-d0d7-11e9-8985-4dcc67cf1e15.png)

And this is the text:

"بسم الله الرحمن الرحيم ﴿قُل هُوَ اللَّهُ أَحَدٌ {١} اللَّهُ الصَّمَدُ {٢} لَم يَلِد وَلَم يولَد {٣} وَلَم يَكُن لَهُ كُفُواً أَحَدٌ﴾ [الإخلاص: ١-٤]."

The problem happens when I start using Arabic numbers ١ ٢ ٣... it breaks
and I tried many fonts and also the default but still same
I really hope this issue can be resolved

**Comment by OsamaAbbas** [comment] 2019-09-06 16:13
@pr-Mais : My advice is to use `textAlign: center` in your app. Your texts are short in general and they are very memorable. They will look perfect if centered, maybe better that justified. This way you don't have to wait for this issue to be fixed.

Another hint: use Amiri font. It's perfect for your app.

**Comment by pr-Mais** [comment] 2019-09-06 16:30
> @pr-Mais : My advice is to use `textAlign: TextAlign.center,` in your app. Your texts are short in general and they are very memorable. They will look perfect if centered, maybe better that justified. This way you don't have to wait for this issue to be fixed.
> 
> Another hint: use Amiri font. It's perfect for your app.

That's what I wanted to do, but the designer is strict about it and wants it to be justified, later down there will be longer texts
Let's hope they have a solution

**Comment by mohamed6996** [comment] 2019-09-10 15:03
Any updates?

**Comment by GaryQian** [comment] 2019-09-10 23:27
I'm currently at a conference, and will continue to work on this as soon as I'm back.

**Comment by amirtabasi** [comment] 2019-09-18 17:45
hi, 
in the new release (1.9) the justify for rtl text just correct the last line of text ! not all of lines that have space or enter in the sentence !

(in this photo i have a long string for text)
![image](https://user-images.githubusercontent.com/55507206/65171675-a61aca80-da60-11e9-9eb2-a52ba532f3b8.png)

**Comment by GaryQian** [comment] 2019-09-18 19:17
@amirtabasi https://github.com/flutter/engine/pull/11842 should have fixed what you see there, are you on the master or dev channel? This change has not made it to stable yet.

I believe the remaining issue to fix is determining the side to justify in the case of a typically LTR character in the beginning of the text.

**Comment by OsamaAbbas** [comment] 2019-09-18 19:27
> I believe the remaining issue to fix is determining the side to justify in the case of a typically LTR characters mixed in the text.

Yes, that's it. Hope it get fixed soon :)

**Comment by GaryQian** [comment] 2019-09-18 19:34
@Hixie What is your opinion on adding an explicit `justifyLeft` and `justifyRight` to force justify towards a certain direction? Currently, we are assuming based off of content (similar to what android actually does) but evidently this is not sufficient for proper alignment.

**Comment by Hixie** [comment] 2019-09-18 22:02
This bug is closed. I recommend filing new bugs for new issues.

For something like `justifyRight`/`justifyLeft`, or `justifyEnd` for that matter, I think we should focus on what the use cases are (in new bugs, which describe the use cases).

**Comment by OsamaAbbas** [comment] 2019-09-19 15:20
Did anybody open a new issue?

I've found another manifestation of this issue (the mixed character issue). When you use `overflow: TextOverflow.ellipsis` with `textDirection: TextDirection.rtl`, the ellipsis position is wrong in the case of mixed text.

**Comment by mahmoudparandeh** [comment] 2019-09-24 15:50
any update? is this fix merged to master?

**Comment by amirtabasi** [comment] 2019-09-24 16:01
> any update? is this fix merged to master?

i use a function to split my string to a list of strings that every item of list is a single paragraph !

![image](https://user-images.githubusercontent.com/55507206/65528602-8d4b6280-df01-11e9-8ae6-055fd5cb6add.png)

**Comment by amirtabasi** [comment] 2019-09-24 16:05
> @amirtabasi [flutter/engine#11842](https://github.com/flutter/engine/pull/11842) should have fixed what you see there, are you on the master or dev channel? This change has not made it to stable yet.
> 
> I believe the remaining issue to fix is determining the side to justify in the case of a typically LTR characters mixed in the text.

sorry i don't know anything about master or dev channel right now ! :(
but i fixed this in my way ! :)
tnx

**Comment by mahmoudatef925** [comment] 2019-10-29 12:59
split by ' ' or what ?

**Comment by OsamaAbbas** [comment] 2019-10-29 13:51
It's obvious that he means split by new lines `\n`. You don't need that hack though. This was fixed already. Change to master channel and upgrade.

```bash
$ flutter channel master
$ flutter upgrade
```

The only remaining issue is when the text contains a mix of LTR and RTL characters. As mentioned above (https://github.com/flutter/flutter/issues/28700#issuecomment-532827648)

**Comment by OsamaAbbas** [comment] 2019-10-29 13:54
@GaryQian any updates on this?

> I believe the remaining issue to fix is determining the side to justify in the case of a typically LTR characters mixed in the text.

**Comment by sunilbcit** [comment] 2019-11-06 07:26
@OsamaAbbas have you find the solution of it. I am facing the same issue i have mixed text both in english and hebrew with TextOverflow.ellipsis not getting the expected result when use textAlign right and textDirection rtl.

**Comment by OsamaAbbas** [comment] 2019-11-06 11:03
Not yet. I'm waiting for a fix. I think it's better to open an issue for this bug specifically.

**Comment by saioufe** [comment] 2019-11-19 14:03
please fix this bug i can justify the arabic text which contain numbers ( the number will break the line )
and after i delete the numbers everything work ok 
![Screenshot_1574172209](https://user-images.githubusercontent.com/32012762/69153004-88182780-0aee-11ea-818d-8ce65217bb5e.png)

**Comment by mahmoudatef925** [comment] 2019-11-20 09:46
@saioufe i'm working in a great work like this but i have an issue -- text never justify Correctly even if i remove numbers i solve it by fit each line but it causes another issue is that there's line smaller than another .
can you show me how you make it jsutify ?

**Comment by saioufe** [comment] 2019-11-20 10:20
@mahmoudatef925 i have used a package called AutoSizeText to resize the text according to the container Height and use it like this 

        Expanded(
          child: Container(
            child: AutoSizeText(
              textToEnter,
              textAlign: TextAlign.center,
              textDirection: TextDirection.rtl,
              style: TextStyle(
                fontFamily: 'uthmanTnB',
                fontSize: 22,
              ),
            ),
          ),
        ),

**Comment by mahmoudatef925** [comment] 2019-11-20 10:24
thanks , but you view page by page not line by line ?

**Comment by saioufe** [comment] 2019-11-20 10:39
@mahmoudatef925 what do you mean line by line

**Comment by mahmoudatef925** [comment] 2019-11-20 10:53
![WhatsApp Image 2019-11-05 at 6 58 45 PM](https://user-images.githubusercontent.com/36286101/69232961-adf80780-0b94-11ea-8750-381f074ae636.jpeg)

**Comment by mahmoudatef925** [comment] 2019-11-20 10:55
i'm using textspan and Container for each line to view tajweed , this page is good but in other pages there is line bigger than next line

**Comment by saioufe** [comment] 2019-11-24 15:34
@mahmoudatef925 can you please tell me how did you do that i have been trying to make it justify but it does not work , can you send me the code please

**Comment by saioufe** [comment] 2019-11-25 13:29
@mahmoudatef925 can you tell please

**Comment by mahmoudatef925** [comment] 2019-11-25 13:31
Give me your whats app number to contact you

**Comment by saioufe** [comment] 2019-11-25 13:32
+9647803040266 @mahmoudatef925 thanksss

**Comment by OsamaAbbas** [comment] 2019-11-25 16:22
There is an ugly workaround for your issues.

Add this unicode character before your text: `U+202E`.

For example:

```Dart
String fixedText = '\u202E' + originalText;
```

There is a drawback here, all numbers will be reversed (so if you have `103` it will be displayed `301`). You can fix this by reversing all the numbers in your text. This is very ugly, espicially if you want your users to be able to select and copy your text. If this is not the case, just reverse all numbers and you are good to go.

**Comment by GaryQian** [comment] 2019-11-26 01:53
@mahmoudatef925 @saioufe Please try not to request/exchange personal contact on a public forum, as it can endanger your privacy and security. I'm going to remove the comment for you so it won't be posted here forever :)

**Comment by GaryQian** [comment] 2019-11-26 01:55
Update on the issue, I will try to see if we can add the directional justify API.

**Comment by saioufe** [comment] 2019-11-26 09:03
@GaryQian that will be great

**Comment by GaryQian** [comment] 2019-11-26 13:38
So after a bit more research and staring at the code, it I don't actually think the problem is insufficient API. There is actually something strange going on with treating numbers/mixed runs as (possibly) breaks or something, which is causing it to trigger the "dont justify last line in paragraph" logic. I'll see if I can figure out what is going on here.

**Comment by GaryQian** [comment] 2019-11-26 13:56
I'm going to continue work on this issue in https://github.com/flutter/flutter/issues/44449, which is a bit more focused! If you have new information, it would be preferred to discuss it there!

**Comment by skmohammadi** [comment] 2020-05-04 10:16
> ```dart
> '\u202E'
> ```

Worked for me like a charm!
