### ISSUE TITLE
can not build from visual studio 2022 on windows 11

### ISSUE THREAD

**Issue by imiskolee** [flutter/flutter#94198] opened 2021-11-25 05:21 UTC
build error log 

```sh
CMake Error at CMakeLists.txt:2 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.
```

```bash
flutter doctor
```

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.348], locale zh-CN)
[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.1)
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
[√] Connected device (3 available)

! Doctor found issues in 2 categories.

```

**Comment by parthraghav** [comment] 2021-11-25 12:56
1. Install Android Studio from https://developer.android.com/studio/index.html (as mentioned above)
2. Locate Android SDK. The path is usually `/Users/<username>/Library/Android/sdk` on MacOS. Alternatively, open Android Studio, go to settings, and search "sdk", you should see the path highlighted.
3. Run the command to install command-line tools `<path_to_sdk>/tools/bin/sdkmanager --install "cmdline-tools;latest"`
4. Accept the license by running this command `flutter doctor --android-licenses`

You missed some installation steps. They're available here:
https://docs.flutter.dev/get-started/install

**Comment by imiskolee** [comment] 2021-11-25 14:11
@parthraghav  thanks , but i am working on desktop now, so mobile SDK is not reason for this issue.

**Comment by stuartmorgan** [comment] 2021-11-25 14:17
Duplicate of https://github.com/flutter/flutter/issues/85922

This is supported on master.

**Closed by stuartmorgan** 2021-11-25 14:17 UTC
