### ISSUE TITLE
Flutter web app doesn't react to line space changes

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#158030] opened 2024-11-01 23:09 UTC
### Steps to reproduce

https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html

1) Go to https://codepen.io/stevef/full/YLMqbo
2) Drag the "Text Spacing" link in to the bookmarks bar
3) Open a Flutter app
4) Click on the Text Spacing bookmark

### Expected results

The text in the app should increase its line spacing

### Actual results

Nothing happens

### Code sample

    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Repro examples'),
        ),
        body: Center(
          child: Semantics(
            header: true,
            child: Text('''Hello World\n'''
                '''New line \n'''
                '''Next line \n'''),
          ),
        ),
      ),
    );

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by franciscojma86** [comment] 2024-11-01 23:10
b/328308198

**Comment by Juliotati** [comment] 2024-11-02 10:29
@franciscojma86 can you provide a video of the steps above?

**Comment by huycozy** [comment] 2024-11-04 08:01
This is similar to https://github.com/flutter/flutter/issues/100710 and it was marked as a duplicate of https://github.com/flutter/flutter/issues/142712 so I will close this in favor of https://github.com/flutter/flutter/issues/142712. Please follow it for update.

**Closed by huycozy** 2024-11-04 08:01 UTC
Labels: in triage
