### ISSUE TITLE
Crash on Production App - java.lang.IllegalStateException 

### ISSUE THREAD

**Issue by sroddy** [flutter/flutter#24287] opened 2018-11-13 14:37 UTC
## Steps to Reproduce
We have a crash on our production app that started to surface after updating flutter to v0.10.2

It is happening on both android 8.0 and 8.1 on the following devices:

P20 (HWEML)
Mate 20 lite (HWSNE)
FIG-LX1 (HWFIG-H)
Mate 10 Pro (HWBLA)

## Logs
```

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3173)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3284)
  at android.app.ActivityThread.-wrap12 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1894)
  at android.os.Handler.dispatchMessage (Handler.java:109)
  at android.os.Looper.loop (Looper.java:166)
  at android.app.ActivityThread.main (ActivityThread.java:7383)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:963)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:178)
  at io.flutter.app.FlutterActivityDelegate.onCreate (FlutterActivityDelegate.java:152)
  at io.flutter.app.FlutterActivity.onCreate (FlutterActivity.java:85)
  at com.bendingspoons.live.quiz.MainActivity.onCreate (MainActivity.kt:11)
  at android.app.Activity.performCreate (Activity.java:7362)
  at android.app.Activity.performCreate (Activity.java:7353)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1219)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3126)
```

**Comment by allanwolski** [comment] 2018-11-19 10:47
Same issue here with the production app.
_Samsung Galaxy J5 (j5lte), Android 6.0_

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3319)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3415)
  at android.app.ActivityThread.access$1100 (ActivityThread.java:229)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1821)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:7325)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:178)
  at io.flutter.app.FlutterActivityDelegate.onCreate (FlutterActivityDelegate.java:152)
  at io.flutter.app.FlutterActivity.onCreate (FlutterActivity.java:85)
  at com.bsoft.freteminimo.MainActivity.onCreate (MainActivity.java:10)
  at android.app.Activity.performCreate (Activity.java:6904)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1136)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3266)
```

**Comment by dnfield** [comment] 2018-11-21 06:37
The logs are helpful - by any chance are you able to reproduce this/know what sequence of events lead to this crash, or are these just coming in from analytics from your users?

**Comment by dnfield** [comment] 2018-11-21 08:36
It looks like this can be caused when the Activity's onCreate gets called without a call to the Application's onCreate.  

I think @jason-simmons or @matthew-carroll might know more about how the Android lifecycle could result in this - my rough understanding is that we're getting into a state where the Application is maintained but the Activity is lost (and so is FlutterMain).  When the Activity is re-launched, it doesn't find settings and thinks things have gone out of order.

Check was introduced by https://github.com/flutter/engine/pull/5614 but not a ton of context there :(

**Comment by dnfield** [comment] 2018-11-21 16:48
Do you know what version this was working on?

**Comment by matthew-carroll** [comment] 2018-11-22 03:34
@dnfield I don't think its possible for an Activity to be created before the Application class.  The Application class is the closing thing in Android to a representation of the process....if the process exists then so does the Application class.

I agree that the error seems to point to initialization not happening.  We've seen some reports of this before.  But I don't think we were able to root cause the previous instances of this.

@sroddy does this issue only occur on a fresh launch of an app?  only on a relaunch of an app? or both?

Are you working with a pure Flutter app, or did you add Flutter to an existing app?

**Comment by dnfield** [comment] 2018-11-22 03:37
Could something be causing the activity to be created a second time, but the application didn't stop running?

**Comment by zoechi** [comment] 2018-12-13 15:21
Did flutter/engine#5614 fix this?

**Comment by zoechi** [comment] 2019-01-11 09:10
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-01-11 09:10 UTC
Labels: engine, severe: crash, severe: regression, waiting for customer response, ▣ platform-android

**Comment by allanwolski** [comment] 2019-02-27 12:36
This crash is still recorded by Google Play Console.
It happened 10x in 1 day with the same device.

- Flutter Channel stable, v1.2.1
- Android: 8.0, 8.1
- Devices: Galaxy J6 (j6lte), Galaxy J7 Neo (j7velte), Moto G (5S) (montana)

### Logs
`java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2957)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3032)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1696)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6944)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.view.FlutterMain.ensureInitializationComplete (FlutterMain.java:178)
  at io.flutter.app.FlutterActivityDelegate.onCreate (FlutterActivityDelegate.java:152)
  at io.flutter.app.FlutterActivity.onCreate (FlutterActivity.java:85)
  at com.bsoft.freteminimo.MainActivity.onCreate (MainActivity.java:10)
  at android.app.Activity.performCreate (Activity.java:7183)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1220)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2910)`

**Comment by gabrc52** [comment] 2019-02-28 19:13
Also happening on HWDRA-MG on Android 8.1 (#26997)

**Comment by lhcdims** [comment] 2019-05-29 04:17
I can't reproduce this error with my own devices.

Got the following error report from Google Play ANRs & crashes reports @ 2019/05/29:

```
Today, 01:54 on app version 105
Samsung Galaxy J7 Neo2 (j7topltemtr), Android 8.0
Report 1 of 1
java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4491)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:4534)
  at android.app.ActivityThread.-wrap20 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1752)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6944)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:124)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:204)
  at com.baseflow.permissionhandler.PermissionHandlerPlugin.processResult (PermissionHandlerPlugin.java:406)
  at com.baseflow.permissionhandler.PermissionHandlerPlugin.handlePermissionsRequest (PermissionHandlerPlugin.java:397)
  at com.baseflow.permissionhandler.PermissionHandlerPlugin.access$000 (PermissionHandlerPlugin.java:34)
  at com.baseflow.permissionhandler.PermissionHandlerPlugin$1.onRequestPermissionsResult (PermissionHandlerPlugin.java:126)
  at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult (FlutterPluginRegistry.java:203)
  at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult (FlutterActivityDelegate.java:128)
  at io.flutter.app.FlutterActivity.onRequestPermissionsResult (FlutterActivity.java:137)
  at android.app.Activity.dispatchRequestPermissionsResult (Activity.java:7737)
  at android.app.Activity.dispatchActivityResult (Activity.java:7560)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4487)
```

**Comment by AndroidNils** [comment] 2019-08-15 19:25
Same problem.

**Comment by JakMar17** [comment] 2020-07-02 20:49
Having same problem in Google Play crashes reports. Cannot preproduced it myself.

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4640)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:4682)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:49)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1957)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7099)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:139)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:231)
  at com.lyokone.location.FlutterLocation.onActivityResult (FlutterLocation.java:164)
  at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEnginePluginRegistry.java:691)
  at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult (FlutterEnginePluginRegistry.java:378)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java:597)
  at io.flutter.embedding.android.FlutterActivity.onActivityResult (FlutterActivity.java:582)
  at android.app.Activity.dispatchActivityResult (Activity.java:7802)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:4633)
```

**Comment by yoman07** [comment] 2020-12-18 13:39
`java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3556)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3703)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2216)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7948)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1075)
Caused by: java.lang.IllegalStateException: 
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine (FlutterActivityAndFragmentDelegate.java:208)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach (FlutterActivityAndFragmentDelegate.java:154)
  at io.flutter.embedding.android.FlutterFragment.onAttach (FlutterFragment.java:582)
  at androidx.fragment.app.Fragment.performAttach (Fragment.java:2574)
  at androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:828)
  at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManagerImpl.java:1238)
  at androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:1303)
  at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange (FragmentManagerImpl.java:2659)
  at androidx.fragment.app.FragmentManagerImpl.dispatchCreate (FragmentManagerImpl.java:2607)
  at androidx.fragment.app.FragmentController.dispatchCreate (FragmentController.java:235)
  at androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:316)
  at androidx.appcompat.app.AppCompatActivity.onCreate (AppCompatActivity.java:115)
  at androidgecko.com.******.ui.BaseActivity.onCreate (BaseActivity.java:31)
  at android.app.Activity.performCreate (Activity.java:7955)
  at android.app.Activity.performCreate (Activity.java:7944)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1307)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3531)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3703)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2216)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7948)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1075)`

I have the same problem. Any updates for it?

**Comment by gabrc52** [comment] 2020-12-18 14:49
The issue was closed already due to lack of information. But it seems like no one here has reproduced it other than the logs on Google Play Console.

Someone should get one of the devices where the issue occurs or ask someone who has such a device, and do some testing and getting more info.
