### ISSUE TITLE
[Web] Text with RTL and LTR languages mixed freezes the app

### ISSUE THREAD

**Issue by fourman-alex** [flutter/flutter#76128] opened 2021-02-16 17:27 UTC
To reproduce basically have a `Text` that has `rtl` and `ltr` languages mixed. This is a new issue that apeared after upgrade to `1.26.0-17.5.pre` on **Web only**

```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(),
      home: Text(
        'A ‎א',
      ),
    );
  }
}
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2020.1)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by darshankawar** [comment] 2021-02-17 08:01
@fourman-alex 
Thanks for reporting this. I tried your code sample but somehow unable to have the `Text(
        'א A',
      ),` in same order as you have. Anything I need to do to show up in same order ? 

Are you trying with canvaskit or html as web renderer ?  what indicates that the app freezes ?

Moreover, can you upgrade to latest beta and see if issue persists ?

**Comment by darshankawar** [comment] 2021-02-17 08:01
May be similar / related to https://github.com/flutter/flutter/issues/75836

**Comment by fourman-alex** [comment] 2021-02-17 09:12
> what indicates that the app freezes ?

The `Text` widget is not being rendered.
If you run the code snippet in debug mode and pause execution you'll see it hang on `/flutter/packages/flutter/lib/src/painting/text_span.dart:204`

Here is the string that will freeze the page: `'A ‎א'` 
My initial code had the wrong string. The important difference being is the special character `\u200e` which is the left-to-right mark (so it seems). I'll update the code snippet to have the correct string.

I'm running the default html renderer.

You can try that code in dart pad as well it will freeze the page as well.

This persists in 1.26.0-17.6.pre as well.

**Comment by darshankawar** [comment] 2021-02-17 10:51
@fourman-alex Thanks for details. I believe if you are running `flutter run -d chrome`, it defaults to canvaskit rendering on desktop browsers. With that said, running above command or it's variant `flutter run -d chrome --web-renderer canvaskit ` does lead to `Text` widget not rendering.

<img width="453" alt="Screenshot 2021-02-17 at 4 08 01 PM" src="https://user-images.githubusercontent.com/67046386/108193830-e392f400-713b-11eb-9a6d-763fa4b7e226.png">

Whereas, running with html rendering (`flutter run -d chrome --web-renderer html)`, the `Text` widget shows up properly:

<img width="425" alt="Screenshot 2021-02-17 at 4 06 48 PM" src="https://user-images.githubusercontent.com/67046386/108193878-f279a680-713b-11eb-9c7c-2b5a84466e41.png">

Does this represent your issue properly ?

**Comment by fourman-alex** [comment] 2021-02-17 11:59
@darshankawar Yes, that is exactly right.

**Comment by darshankawar** [comment] 2021-02-17 13:31
@fourman-alex 
In that case, I don't think the issue is related to RTL or LTR, but using special character to render on web using canvaskit. Because if you only have that special char in `Text` widget, it won't still render with canvaskit, whereas, a regular `A` char will render.
This scenario points to a recently fixed issue that I mentioned earlier, https://github.com/flutter/flutter/issues/75836. I suggest you to switch to latest master and try again with your code and see if it works there properly. If not, then the fix made may not have still fixed the issue, but will need to follow-up in that ticket (and possibly reopening it).

I am closing this as duplicate. 
Thanks.

**Closed by darshankawar** 2021-02-17 13:31 UTC
Labels: in triage
