### ISSUE TITLE
onSubmitted with TextField when pressing Enter key

### ISSUE THREAD

**Issue by droidery** [flutter/flutter#19027] opened 2018-07-03 01:04 UTC
## Steps to Reproduce

1. Create a `TextField` with `onSubmitted` function
2. Run app in Android simulator
3. Press enter on keyboard
4. `onSubmitted` is not called

## Logs

Whenever you press Enter these come up in the error log:

```
W/IInputConnectionWrapper( 8999): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper( 8999): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 8999): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 8999): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 8999): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 8999): endBatchEdit on inactive InputConnection
```

```
```

```
[✓] Flutter (Channel master, v0.5.6-pre.121, on Mac OS X 10.13.5, locale en-US)
    • Flutter version 0.5.6-pre.121 at /Users/droider/flutter
    • Framework revision a4faa2e067 (85 minutes ago), 2018-07-02 16:35:43 -0700
    • Engine revision 6fe748490d
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/droider/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.2

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android P (API 27) (emulator)
```

**Comment by droidery** [comment] 2018-07-04 07:47
On iOS when you hit enter on the keyboard it submits the `TextField` and calls `onSubmitted`, but if you're on Android it doesn't submit when you press enter.

Shouldn't the behavior be consistent.

**Comment by code4ghana** [comment] 2018-08-25 22:50
```
void _handleSubmission(String text) {
// Not triggered when you press enter on keyboard in  android simulator
// Triggers if you tap on the Done button.
}
new TextField(
  maxLines: 1,
  onSubmitted: _handleSubmission)
```

**Comment by Jon-Salmon** [comment] 2018-11-23 15:10
I'm also running into this issue when a bluetooth keyboard is connected on android. On screen keyboard works fine but an external one does not.
I havn't tried an emulator.

**Comment by zoechi** [comment] 2018-12-19 15:18
Is this a duplicate of #15757 ?

**Comment by baeharam** [comment] 2019-01-27 06:18
Any implementation yet?

**Comment by jicg** [comment] 2019-07-03 08:54
how to handle the enter key ？

**Comment by MichealReed** [comment] 2019-07-07 01:19
Would be great if web is supported here as well.

**Comment by jicg** [comment] 2019-07-07 01:26
This topic has been a year... I don’t know when the gods can achieve it. . .

**Comment by Caizoo** [comment] 2019-08-03 09:57
Use a TextFormField and then you can set the onEditingComplete to then handle submission

**Comment by MichealReed** [comment] 2019-08-12 21:53
Wrap the page in a keyboard listener to achieve the same effect.

```                child: RawKeyboardListener(
                  focusNode: FocusNode(),
                  onKey: (event) {
                    //print(event.data.logicalKey.keyId);
                     /* if (event.runtimeType == RawKeyDownEvent &&
                          (event.logicalKey.keyId == 54)) {Navigator.pop(context, this._textController.text);} */
                    
                  },
                  child: TextFormField(
                    controller: _textController,
                    onFieldSubmitted: (_textController) {
                      Navigator.pop(context, this._textController.text);
                    },
                    ),
                  ),```

**Comment by SystemTce** [comment] 2019-11-16 07:56
[https://stackoverflow.com/a/58888683/12376696](url)
I tried to capture the "enter key" in onChanged.

**Comment by dewball345** [comment] 2019-12-01 03:32
Hello there,
I actually had a similar problem as well! Here's my reasoning to it:
On an actual android phone, there is no actual enter key, just a "submit" button marked with a check. Therefore, the onSubmit function only gets called when the "check" button is pressed.

However, I really don't know why it works with iOS. Maybe it's just the way flutter works?

Good Luck!

**Comment by maryleneb** [comment] 2019-12-12 20:44
I think it is an issue and it should be added. My app runs on a handheld computer that has a keyboard built in. Nobody is gonna use the virtual keyboard so it would make sense that the enter would submit the form

**Comment by csells** [comment] 2020-01-13 20:25
@gspencergoog I believe this should work and that it's part of the work you're already doing, correct?

**Comment by gspencergoog** [comment] 2020-01-13 20:38
Yes, this should be fixed. I haven't addressed it yet in my actions/shortcuts work yet, but it will require that text fields use Actions and Shortcuts to fix properly. Since that might take a while, it might be good idea to put in an interim fix to this.

**Closed** 2020-01-15 19:13 UTC
Labels: a: desktop, a: fidelity, a: text input, customer: soldier, dependency: android, framework

**Comment by venkatd** [comment] 2020-11-27 17:26
> Yes, this should get fixed. I haven't addressed it yet in my actions/shortcuts work yet, but it will require that text fields use Actions and Shortcuts to fix properly. Since that might take a while, it might be good idea to put in an interim fix to this.

@gspencergoog would moving TextFields to Actions+Shortcuts allow us to override default behavior such as enter, tab, and the arrow keys? I'm having some frustrations overriding this behavior. Our app has some custom uses for text fields such as:

- Using arrow keys to select mentions when typing and the tab key to complete a selection
- Hitting enter while editing a task would immediately move to creating a new task instead

**Comment by gspencergoog** [comment] 2020-11-30 17:45
@venkatd Yes, that should help with your use case, and is in the plan. It is currently hard coded, and shouldn't be, but we're still working on migration of the text input to use actions/shortcuts.

**Comment by venkatd** [comment] 2020-11-30 19:32
Great! Is there an issue I can track related to this? Our app is very on text fields (popups, editing tasks, chat composers, etc) and shortcuts (keyboard nav, power user shortcuts, etc).

Happy to help with documentation for the FocusableActionDetector and make a good example once it's ready.
