### ISSUE TITLE
Title Bar on Ubuntu is messed up

### ISSUE THREAD

**Issue by Masterxilo** [flutter/flutter#113643] opened 2022-10-18 20:40 UTC
This is on Ubuntu 20.04.2 LTS & Flutter:
```
$ flutter --version
Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision eb6d86ee27 (2 weeks ago) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0
```

repro:
```
sudo snap install --classic flutter
flutter sdk-path
flutter config --no-analytics
flutter create flutterhelloworld
flutter run
```
then
```
Multiple devices found:
Linux (desktop) • linux  • linux-x64      • Ubuntu 20.04.2 LTS 5.13.0-51-generic
Chrome (web)    • chrome • web-javascript • Google Chrome 99.0.4844.82
[1]: Linux (linux)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
```
then the first error came:
```
** (flutterhelloworld:12682): CRITICAL **: 22:24:55.522: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
```
still the app launched. The title bar was completely nuts, not sure it has anything to do with the initial "CRITICAL" (or not so critical? not critical enough to prevent a starting?)
![image](https://user-images.githubusercontent.com/2378665/196539739-a0619215-af7a-4033-a0a6-1ec94f7255ab.png)
I also saw it repainting itself on the desktop/wallpaper and not getting updated, it was sometimes completely white or transparent with maybe only the buttons showing up.

When quitting:
```
(flutterhelloworld:12682): GLib-GObject-WARNING **: 22:28:15.793: ../../../gobject/gsignal.c:2736: instance '0xb8c290' has no handler with id '243'
```

**Comment by Masterxilo** [comment] 2022-10-18 21:06
on the second run, I got quite a few additional error logs while the app was running before I quit it
```
** (flutterhelloworld:14334): CRITICAL **: 22:38:15.418: void update_pressing_state(FlKeyEmbedderResponder *, uint64_t, uint64_t): assertion 'lookup_hash_table(self->pressing_records, physical_key) == 0' failed
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 428 pos 16: '!_pressedKeys.containsKey(event.physicalKey)': A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#cd1fd(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 0:32:28.549000, synthesized)
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:428:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:808:29)
#6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:410:41)
#7      _invoke1 (dart:ui/hooks.dart:167:13)
#8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:408:7)
#9      _invoke2 (dart:ui/hooks.dart:186:13)
#10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#11     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#12     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#14     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 428 pos 16: '!_pressedKeys.containsKey(event.physicalKey)': A KeyDownEvent is dispatched, but the state shows that the physical key is already pressed. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyDownEvent#cd1fd(physicalKey: PhysicalKeyboardKey#700e2(usbHidUsage: "0x000700e2", debugName: "Alt Left"), logicalKey: LogicalKeyboardKey#00104(keyId: "0x200000104", keyLabel: "Alt Left", debugName: "Alt Left"), character: null, timeStamp: 0:32:28.549000, synthesized)
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:428:16)
#3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:443:6)
#4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:535:5)
#5      KeyEventManager.handleKeyData (package:flutter/src/services/hardware_keyboard.dart:808:29)
#6      PlatformDispatcher._keyDataListener.<anonymous closure>.<anonymous closure> (dart:ui/platform_dispatcher.dart:410:41)
#7      _invoke1 (dart:ui/hooks.dart:167:13)
#8      PlatformDispatcher._keyDataListener.<anonymous closure> (dart:ui/platform_dispatcher.dart:408:7)
#9      _invoke2 (dart:ui/hooks.dart:186:13)
#10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#11     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#12     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#14     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)

Lost connection to device.

(flutterhelloworld:14334): GLib-GObject-WARNING **: 22:41:17.605: ../../../gobject/gsignal.c:2736: instance '0x9fe290' has no handler with id '244'
```

**Comment by Masterxilo** [comment] 2022-10-18 21:21
yes, the built native app flutterhelloworld/build/linux/x64/release/bundle/flutterhelloworld has the same problem, maybe it does on your machine too?

[bundle.zip](https://github.com/flutter/flutter/files/9815199/bundle.zip)

**Comment by huycozy** [comment] 2022-10-19 09:08
@Masterxilo 
It displays well from my side with your [provided release build](https://github.com/flutter/flutter/issues/113643#issuecomment-1283019563).
I'm using `Ubuntu 22.04.1 LTS 5.15.0-48-generic`.

<details>
<summary>Demo</summary>

<img width="600" src="https://user-images.githubusercontent.com/104349824/196642965-3921b86a-ae8e-445d-bbe6-c3fc9f072195.png">
</details>

<details>
<summary>flutter doctor -v (stable & master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.4, on Ubuntu 22.04.1 LTS 5.15.0-48-generic, locale en_US.UTF-8)
    • Flutter version 3.3.4 on channel stable at /home/huynq/Documents/Working/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (27 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/huynq/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-48-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

```bash
[✓] Flutter (Channel master, 3.5.0-8.0.pre.46, on Ubuntu 22.04.1 LTS 5.15.0-48-generic, locale en_US.UTF-8)
    • Flutter version 3.5.0-8.0.pre.46 on channel master at /home/huynq/Documents/Working/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abfaec6811 (81 minutes ago), 2022-10-19 08:13:17 +0100
    • Engine revision 563b8e830c
    • Dart version 2.19.0 (build 2.19.0-317.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/huynq/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/huynq/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/huynq/Documents/android-studio
    • Flutter plugin version 67.0.1
    • Dart plugin version 211.7817
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.71.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.50.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.1 LTS 5.15.0-48-generic
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Please provide the output of  `flutter doctor -v` and also retry on the latest Flutter master channel to see if the issue still reproduces.

In case the issue hasn't been fixed on the master, please take a look at https://github.com/flutter/flutter/issues/75948#issuecomment-1040633877. It looks like a Ubuntu issue rather than Flutter.

**Comment by Masterxilo** [comment] 2022-10-19 19:32
Thanks for the feedback. I accept that it may be an issue caused by incompatibilities between my version of Ubuntu & Flutter, potentially with other software (and hardware?) issues in the mix. Here is the requested output:

[flutter.doctor.v.txt](https://github.com/flutter/flutter/files/9823603/flutter.doctor.v.txt)

I don't have time to test with another combination of versions as I am just looking around for options to build an app and unfortunately this issue and the FATAL/CRITICAL warnings and [#](https://github.com/flutter/gallery/issues/811) & https://github.com/flutter/gallery/issues/813 where a somewhat rough/discouraging start.

Not completely discarding flutter yet though of course; you definitely built something awesome, it's just a bit less shiny and more real than the keynote talks suggest. I suggest you provide flutter as a service, through an online IDE & simulator where people build apps in a managed environment where you are absolutely sure everything works. As an easier step, an officially maintained flutter devcontainer would already help. Cheers

**Comment by huycozy** [comment] 2022-10-20 03:28
Hi @Masterxilo 

As mentioned at https://github.com/flutter/flutter/issues/75948#issuecomment-1041557355, it seems this issue has been fixed in GTK release. Please check [gtk+3.0/+bug/1960947](https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1960947) for further info (you may want to take a look at https://bugs.launchpad.net/ubuntu/+source/gtk+3.0/+bug/1960947/comments/4 as a quick test for this).

In case the test on patch fix is successful, please confirm so that someone else with the same issue can know how to solve it. Thank you!

**Closed** 2022-11-10 03:35 UTC
Labels: waiting for customer response, in triage
