### ISSUE TITLE
Support hot reload of StatelessWidget to StatefulWidget and vice versa

### ISSUE THREAD

**Issue by matanlurey** [flutter/flutter#13192] opened 2017-11-23 23:01 UTC
## Steps to Reproduce

I wrote ~the following:

```dart
// Start our flutter application.
void main() => runApp(const App());

class App extends StatelessWidget {
  const App();

  @override
  Widget build() => const Text('Hello World');
}
```

And then decided I needed state:

```dart
void main() => runApp(new App());

class App extends StatefulWidget {
  @override
  State<App> createState() => new _AppState();
}

class _AppState extends State<App> {
  @override
  Widget build(_) => const Text('Hello World');
}
```

And tried using the hot-restart (shift-f5 in VSCode) and got an unfixable exception - it looks like it had some stale dart code compared to my actual code I wrote. If I shut down the application manually and re-ran it everything worked fine.

## Logs

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while rebuilding dirty elements:
type 'App' is not a subtype of type 'StatelessWidget' of 'function result' where
App is from
/Users/matan/Library/Developer/CoreSimulator/Devices/9F33391B-D2D7-4E44-95C4-9A912FDCD824/data/Containers/Data/Application/3CE9D5F1-F0EA-48F3-A9F7-827055FC432B/tmp/flutter_data_structuresgYBbaN/flutter_data_structures/lib/main.dart
StatelessWidget is from package:flutter/src/widgets/framework.dart
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
type 'App' is not a subtype of type 'StatelessWidget' of 'function result' where
App is from
/Users/matan/Library/Developer/CoreSimulator/Devices/9F33391B-D2D7-4E44-95C4-9A912FDCD824/data/Containers/Data/Application/3CE9D5F1-F0EA-48F3-A9F7-827055FC432B/tmp/flutter_data_structuresgYBbaN/flutter_data_structures/lib/main.dart
StatelessWidget is from package:flutter/src/widgets/framework.dart
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.6 16G29, locale en-US, channel master)
    • Flutter at /Users/matan/git/flutter
    • Framework revision 167382480a (14 hours ago), 2017-11-23 10:24:16 +0100
    • Engine revision 93b2179597
    • Tools Dart version 1.25.0-dev.11.0

[✓] Android toolchain - develop for Android devices (Android SDK 25.0.2)
    • Android SDK at /Users/matan/Library/Android/sdk
    • Unable to locate Android NDK.

    • Unable to locate compiler in Android NDK.

    • Platform android-25, build-tools 25.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.1, Build version 9B55
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 2.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b05)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.5)
    • Flutter plugin version 17.0
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • iPhone SE • 9F33391B-D2D7-4E44-95C4-9A912FDCD824 • ios • iOS 11.1 (simulator)
```

**Comment by seklum** [comment] 2017-11-25 18:13
It sounds like the compiler is requesting a stateless widget in runApp().

```
// Start our flutter application.
void main() => runApp(const App());

class App extends StatelessWidget {
  const App();

  @override
  Widget build() => new MyWidget();
}

class MyWidget extends StatefulWidget {
  @override
  State<App> createState() => new _AppState();
}

class _MyWidgetState extends State<MyWidget> {
  @override
  Widget build(_) => const Text('Hello World');
}
```

**Comment by derekurizar** [comment] 2018-05-20 04:42
WHen you change Statless to StatefulWidget or StatefulWidget to Statless
you need to close the app and restart the debuf because for the moment Hot Debug can't detect that change.

**Comment by goderbauer** [comment] 2018-12-28 18:56
Dupe of https://github.com/flutter/flutter/issues/9811, which has more information.

**Closed by goderbauer** 2018-12-28 18:56 UTC
Labels: framework, severe: crash, t: hot reload
