### ISSUE TITLE
Various ParagraphTest tests failing in engine presubmit

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#68493] opened 2020-10-19 17:00 UTC
In `build_and_test_linux_unopt_debug` on Cirrus:

e.g. https://api.cirrus-ci.com/v1/task/6724797990174720/logs/test_host.log

```
[ RUN      ] ParagraphTest.GetRectsForRangeParagraphNewlineLeftAlign
../../flutter/third_party/txt/tests/paragraph_unittests.cc:4046: Failure
Expected equality of these values:
  boxes[0].rect.bottom()
    Which is: 76
  75
../../flutter/third_party/txt/tests/paragraph_unittests.cc:4058: Failure
Expected equality of these values:
  boxes[0].rect.bottom()
    Which is: 135
  134
../../flutter/third_party/txt/tests/paragraph_unittests.cc:4068: Failure
Expected equality of these values:
  boxes[0].rect.bottom()
    Which is: 194
  193
[  FAILED  ] ParagraphTest.GetRectsForRangeParagraphNewlineLeftAlign (148 ms)
```

**Comment by gaaclarke** [comment] 2020-10-19 17:26
I ran `./out/host_debug_unopt/txt_unittests` locally from e66e3f5352774d6a2b78383a693bfd2f40b83e9d and the problem didn't reproduce.

**Comment by chinmaygarde** [comment] 2020-10-19 17:41
@gaaclarke Tentatively assigning to you since you seem to be working on reproducing this. Feel free to remove your assignment if you are not. @jason-simmons is of the opinion that we should be able to get away with making the test more resilient. We can just do that instead of trying to reproduce this/

**Comment by gaaclarke** [comment] 2020-10-19 17:57
I was unable to reproduce it locally on mac and jason was unable to on linux.  His speculation is that there is something peculiar about the cirrus CI setup.  The best course of action is to make the tests more resilient.  @jason-simmons it sounds like this could take a couple of hours at least.  Do you think we should disable those tests in the meantime?

**Comment by gaaclarke** [comment] 2020-10-19 18:55
The tests have been disabled, this is no longer blocking until a fix can be landed.

**Comment by jason-simmons** [comment] 2020-10-19 21:58
Landed https://github.com/flutter/engine/pull/21974

**Closed by jason-simmons** 2020-10-19 21:58 UTC
Labels: P3, a: tests, engine, team, team: flakes
