### ISSUE TITLE
WidgetTester flake

### ISSUE THREAD

**Issue by amirh** [flutter/flutter#66593] opened 2020-09-24 22:16 UTC
the path_provider_linux test just failed in what looks like a flake within the (WidgetTester?) test infrastructure:

https://cirrus-ci.com/task/5526647522721792?command=test#L1153

@dnfield

**Comment by dnfield** [comment] 2020-09-25 23:34
I would have expected this to print the exception out. @jiahaog have you seen this before?

**Comment by jiahaog** [comment] 2020-09-26 05:28
Yeah I would have expected the exception to show up as well. My guess would be something to do with zones, #50816 might fix the reoorting.

**Comment by jiahaog** [comment] 2020-10-12 02:22
Looked into this further - my above comment is incorrect. This isn't actually a test with `package:integration_test`, but rather a widget test. The exception for the failure is not showing up because they are [dropped](https://github.com/flutter/plugins/blob/a346783045c027ea514262fd1e6acdadd6cd0ddf/packages/path_provider/path_provider_linux/example/lib/main.dart#L36-L57) in the test application

**Comment by jiahaog** [comment] 2020-10-15 12:33
I haven't been able to reproduce this locally after running the test 100+ times. I'll send a PR to log the errors properly, and we should be able to close this.

**Comment by cyanglaz** [comment] 2020-10-15 18:07
Tentatively assigning this to @jiahaog . Feel free to add a milestone :)

**Comment by cyanglaz** [comment] 2020-11-19 19:09
@jiahaog Friendly ping, is it still on track of the November milestone?

**Comment by jiahaog** [comment] 2020-11-19 23:43
Sorry for the delay, I added the logging and we should be able to close this now - my last repeated runs of the tests locally wasn't able to reproduce the failures. Please reopen if they occur again 🙂

**Closed by jiahaog** 2020-11-19 23:43 UTC
Labels: P4, passed first triage, plugin, team: flakes
