### ISSUE TITLE
Flutter installation Error

### ISSUE THREAD

**Issue by svdivya** [flutter/flutter#81376] opened 2021-04-28 12:11 UTC
For all flutter commands, I am getting this error, tried to change the read/write permission .config file, but unable to change permission. After running the flutter doctor -v command, I am getting the below exception, please suggest me the solution

<details> 
<summary>logs</summary> 

```console
Unhandled exception:
Exception: Flutter failed to create a directory at "/Users/catalina/.config/flutter". The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:749:3)
#2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:697:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:561:7)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:408:12)
#5      new Config (package:flutter_tools/src/base/config.dart:33:17)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:146:21)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#11     config (package:flutter_tools/src/globals.dart:47:30)
#12     getBuildDirectory (package:flutter_tools/src/build_info.dart:673:48)
#13     defaultDepfilePath (package:flutter_tools/src/bundle.dart:29:55)
#14     new BuildBundleCommand (package:flutter_tools/src/commands/build_bundle.dart:24:42)
#15     new BuildCommand (package:flutter_tools/src/commands/build.dart:33:19)
#16     main.<anonymous closure> (package:flutter_tools/executable.dart:102:5)
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:50:13)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#20     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
catalina@Shrinivas-MacBook-Pro mca_care % clear
catalina@Shrinivas-MacBook-Pro mca_care % flutter doctor -v
Unhandled exception:
Exception: Flutter failed to create a directory at "/Users/catalina/.config/flutter". The flutter tool cannot access the file or directory.
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:749:3)
#2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:697:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:561:7)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:408:12)
#5      new Config (package:flutter_tools/src/base/config.dart:33:17)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:146:21)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#11     config (package:flutter_tools/src/globals.dart:47:30)
#12     getBuildDirectory (package:flutter_tools/src/build_info.dart:673:48)
#13     defaultDepfilePath (package:flutter_tools/src/bundle.dart:29:55)
#14     new BuildBundleCommand (package:flutter_tools/src/commands/build_bundle.dart:24:42)
#15     new BuildCommand (package:flutter_tools/src/commands/build.dart:33:19)
#16     main.<anonymous closure> (package:flutter_tools/executable.dart:102:5)
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:50:13)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#19     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#20     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
<asynchronous suspension>
#21     main (package:flutter_tools/executable.dart:90:3)
<asynchronous suspension>
```

</details>

**Comment by mehtahardikr** [comment] 2021-04-28 12:36
possible duplicate of :  https://github.com/flutter/flutter/issues/67840

**Comment by TahaTesser** [comment] 2021-04-28 13:13
Hi @svdivya 
Which flutter version you've installed? Are you using `git clone` or zip download?

**Comment by pedromassangocode** [comment] 2021-05-19 12:17
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-19 12:17 UTC
Labels: in triage, waiting for customer response

**Comment by CatEatFishs** [comment] 2021-06-19 09:51
I meet same problem。this sdk is flutter2.2.1
in android studio the log：
5:36 PM	Flutter device daemon
				Flutter device daemon #1 exited (exit code 255), stderr: Unhandled exception:
				Exception: Flutter failed to write to a file at "/Users/lm/.flutter_tool_state". The flutter tool cannot access the file or directory.
				Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
				#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
				#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:778:3)
				#2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:726:3)
				#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:583:7)
				#4      ErrorHandlingFile.writeAsStringSync (package:flutter_tools/src/base/error_handling_io.dart:266:5)
				#5      Config._flushValues (package:flutter_tools/src/base/config.dart:134:11)
				#6      Config.setValue (package:flutter_tools/src/base/config.dart:123:5)
				#7      _DefaultPersistentToolState.isRunningOnBot= (package:flu... (show balloon)
in mac terminal run flutter doctor -v
 Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.1 at /Users/lm/develop/flutter_2.2.1
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/lm/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/lm/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.106
is ok ,but in android studio is bad.show that problem

**Comment by TahaTesser** [comment] 2021-07-01 10:53
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
