### ISSUE TITLE
Video_player from Stream

### ISSUE THREAD

**Issue by marcodecarolisidt** [flutter/flutter#81363] opened 2021-04-28 07:30 UTC
## Use case

I would like to play and cache a network video.

With [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manage) I can cache a video from a URL into a file:
```
DefaultCacheManager().downloadFile(videoUrl);;
```
To play a video with [video_player](https://pub.dev/packages/video_player) I can use the videoUrl and play it from the network using the VideoController.

If I want to cache the video and play it at the same time, I would have to start the video from the VideoController and also use 
the DefaultCacheManager to cache it, downloading it twice.

## Proposal

Is it possible to play and cache it at the same time, so the client will consume data only to download the video one time?

[flutter_cache_manager](https://pub.dev/packages/flutter_cache_manage) has also:
```
Stream<FileResponse> DefaultCacheManager().getFileStream(videoUrl)
```
Could maybe be possible to use VideoController to play a video from a stream to implement this feature?

**Comment by TahaTesser** [comment] 2021-04-28 08:57
Hi @marcodecarolisidt 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/28094
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-04-28 08:57 UTC
Labels: in triage
