### ISSUE TITLE
Flutter Firestore update an array in an array in a document

### ISSUE THREAD

**Issue by klaszlo8207** [flutter/flutter#53562] opened 2020-03-30 09:07 UTC
So basically I have a collection that contains only one document.

That document contains 1 array of maps, and in that array I have an other array

How to update only the inner array?

Tried this:

```
        _teams.document(result.documents.first.documentID).updateData(<String, dynamic>{
          "teams/${team.index}/memberUids": FieldValue.arrayUnion([myUserId])
        });
```

got this:

**Use FieldPath.of() for field names containing '~*/[]'.**

**Comment by iapicca** [comment] 2020-03-30 09:15
Hi @klaszlo8207 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-03-30 09:15 UTC
