### ISSUE TITLE
Support Material 3 Carousel

### ISSUE THREAD

**Issue by RomilPipaliya** [flutter/flutter#144673] opened 2024-03-06 08:19 UTC
### Carousels

Carousels show a collection of items that can be scrolled on and off the screen

### Use Cases
- Navigate to the carousel container

- Navigate between different carousel items

- Activate a carousel item

- Skip over the carousel items

You can see other specs [here](https://m3.material.io/components/carousel/specs)

### **Carousel**

[Check this Material 3 Carousel](https://firebasestorage.googleapis.com/v0/b/design-spec/o/projects%2Fgoogle-material-3%2Fimages%2Flq26qy1q-carousel_a11y_arrow-affordance_1P.mp4?alt=media&token=a72ee989-6525-47f7-840d-8833bdc0974b)

- [ ] Add support for Carousel

**Comment by danagbemava-nc** [comment] 2024-03-06 08:39
Closing this as a duplicate of https://github.com/flutter/flutter/issues/125980

**Closed by danagbemava-nc** 2024-03-06 08:39 UTC
Labels: in triage
