### ISSUE TITLE
Missing Feature: Streaming and Playing Audio

### ISSUE THREAD

**Issue by DeRealMorgan** [flutter/flutter#32399] opened 2019-05-09 11:39 UTC
This is a very important feature:

I need to record audio on client A and send it in realtime using a server to client B to **then play the audio**.
-I need it to make a voice call with others.

What I have so far:
1. https://pub.dev/packages/audio_streams#-readme-tab- - Gives a byte-stream of the microphone for iOS only
2. https://pub.dev/packages/mic_stream - Gives a byte-stream of the microphone for Android only

--
1. It is not convenient for such a simple feature to be handled platform specific (or without an abstraction)
2. **There is no way** (I have not found one) to use a byte-stream to then play it directly as a sound!
-That is the important part!

**Comment by pcdavis** [comment] 2019-05-10 19:06
I agree. The third-party libraries are not sufficient for such an critical feature.

**Comment by DeRealMorgan** [comment] 2019-05-13 19:49
I do not know what the procedure is and I also really do not want to let this request get lost behind 5000 other requests.

What will happen with my request in the future?

**Comment by malvinpratama** [comment] 2019-08-09 19:16
i agree. flutter need implement this feature as soon as possible

**Comment by remoteportal** [comment] 2019-10-31 12:09
And recording audio, too.

**Comment by marwan-at-work** [comment] 2019-12-12 01:32
Streaming audio from a URL is also very frequent, most of the third party packages out there are quite buggy, would love to see better support for this.

**Comment by suragch** [comment] 2019-12-16 03:25
Playing audio should support the web in addition to Android and iOS.

**Comment by stuartmorgan** [comment] 2023-03-11 00:35
Closing as a duplicate of https://github.com/flutter/flutter/issues/47105 since that's where most of the voting and discussion has happened.

**Closed by stuartmorgan** 2023-03-11 00:35 UTC
Labels: new feature, plugin, P5
