### ISSUE TITLE
add2app .gitignore has .android and .ios in it.

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#25931] opened 2019-01-01 00:30 UTC
This seems like a bug if the entire wrapper project is omitted from source control

**Comment by filleduchaos** [comment] 2019-01-01 23:38
That is [by design](https://github.com/flutter/flutter/pull/18726), as it's generated code. Not everything goes into source control.

(Of course, if you have cause to modify the generated code then you're at liberty to check it into source control).

**Comment by neiljaywarner** [comment] 2019-01-01 23:53
This doesn't seem right because it won't regenerate when another dev pulls it down

And won't build because the Gradle script is missing.

Keeping generated code out of source control makes sense if it regenerates automatically...

**Comment by filleduchaos** [comment] 2019-01-02 00:09
It regenerates when another dev pulls it down, yes. That's kind of what *generated* code does.

**Comment by filleduchaos** [comment] 2019-01-02 00:10
(In this case, it's generated as part of the initial and any subsequent `flutter packages get` runs)

**Comment by zoechi** [comment] 2019-01-02 08:00
@neiljaywarner does `flutter packages get` recreate the platform-specific generated code for you?

**Comment by neiljaywarner** [comment] 2019-01-02 16:46
@zoechi  it sure does, I'm so sorry. I did run the outer app and it gave an error which is why I thought it did not autogenerate, and this is new/experimental features.

I also tried asking several people about it several different ways including the flutter-dev email group and the gitter channel (twice i think) before posting it as a possible bug, but again, I'm sorry. With flutter being so IDE agnostic, i should've looked harder for a CLI way like that.

in addition, i doesn't seem like a package I'm getting, plus my goal is/was to have little/no setup required on the devs for the outer project.

so i wonder 
1) is there any way to get it to "just work" by default, at least with help from the Intellij/Visual studio plugins or something?
2) Can we treat it as an area for improvement in the documentation please
3) perhaps change local.properties to have a comment header, similar to Android's comment header.

again, I'm sorry about that.

**Comment by zoechi** [comment] 2019-01-02 17:08
Adding Flutter to existing apps is still experimental and lots of work in progress.
Flutter usually runs `flutter packages get` before run/build, but perhaps not in that scenario (haven't used it myself yet).

**Comment by neiljaywarner** [comment] 2019-03-01 00:51
@zoechi  is there an ETA for add2app being "not experimental"?  Should we be concerned about it being in production, or is it just a ymmv thing?

**Comment by jmagman** [comment] 2019-12-19 22:14
Add-to-app is no longer experimental.

There was some attempt to document this with https://flutter.dev/docs/development/add-to-app/ios/project-setup#module-organization and https://flutter.dev/docs/development/add-to-app/android/project-setup#create-a-flutter-module with the ".ios/.android directory is emphemeral, run `flutter pub get` to generate it.

@stevemessick @xster Does Android Studio handle a missing .android directory (like after a git clone) in the module?  Does it ever run `flutter pub get` or `flutter build` in the module, or mostly is just creation supported?
https://flutter.dev/docs/development/add-to-app/android/project-setup#using-android-studio

**Comment by jmagman** [comment] 2019-12-19 22:22
This is a duplicate of https://github.com/flutter/flutter/issues/25931, I'll take my IDE question over there.

**Closed** 2019-12-19 22:22 UTC
Labels: a: existing-apps, d: wiki, engine

**Comment by jmagman** [comment] 2019-12-19 23:14
Sorry, I meant duplicate of https://github.com/flutter/flutter/issues/21706.
