### ISSUE TITLE
Gap between elevation shadow and content when translated

### ISSUE THREAD

**Issue by slightfoot** [flutter/flutter#18984] opened 2018-07-02 01:58 UTC
When you use a negative translation value in a Transform it causes a gap to appear between the elevation shadow and content.

<img width="540" alt="screenshot-2018-07-02_01 34 43 647" src="https://user-images.githubusercontent.com/906564/42141842-c62a1a62-7da3-11e8-8d65-47c6e9529713.png">

## Steps to Reproduce
Run example code.

**bug_shadow.dart**
```dart
import 'dart:math' show pi;
import 'package:flutter/material.dart';

void main() => runApp(TestApp());

class TestApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Container(
        alignment: Alignment.center,
        color: Colors.white,
        child: Transform(
          transform: Matrix4.identity()
            ..translate(0.0, -40.0)
            ..rotateZ((pi / 180.0) * 8.0),
          alignment: Alignment.center,
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Card(
              elevation: 8.0,
              color: Colors.white,
              shape: const RoundedRectangleBorder(
                side: BorderSide(color: Colors.blueGrey, width: 1.0),
                borderRadius: const BorderRadius.all(const Radius.circular(4.0)),
              ),
              child: AspectRatio(
                aspectRatio: 1.0,
                child: Center(
                  child: Text('Text', style: const TextStyle(fontSize: 32.0)),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

## Logs

**flutter doctor -v**
```
[√] Flutter (Channel master, v0.5.6-pre.76, on Microsoft Windows [Version 10.0.17134.112], locale en-GB)
    • Flutter version 0.5.6-pre.76 at C:\Android\flutter
    • Framework revision 579116412f (6 days ago), 2018-06-26 12:18:50 +0200
    • Engine revision 549c855e89
    • Dart version 2.0.0-dev.63.0.flutter-4c9689c1d2

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-P, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\SDK
    • Java binary at: C:\Android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Android\Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1
    • Flutter plugin version 24.0.2
    • Dart plugin version 181.4203.498

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Users\Simon\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\181.4892.42
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[√] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.14.0

[√] Connected devices (1 available)
    • Google Nexus 5X, 8 0, API 26, 1080x1920 • 192.168.188.101:5555 • android-x86 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by sceee** [comment] 2019-07-13 18:00
I actually have the same issue with Cards in a `PageView`. But in my case, this issue only occurs on iOS. On my Android devices, it does not occur. But I guess, **that it is somehow sensitive to screen sizes** and I do not have as large screens on Android compared to iOS. Because if I use smaller iOS devices, it does also not occur.

And it's directly related to the elevation. If I'm using an elevation of 30, it's a large gap between the shadow:
![30elev](https://user-images.githubusercontent.com/11340487/61174913-3216fe80-a5a7-11e9-9514-50b8c2558e6a.png)
If I'm using an elevation of 8, it's a smaller gap:
![8elev](https://user-images.githubusercontent.com/11340487/61174910-23c8e280-a5a7-11e9-907a-749daae30915.png)

Also, the area without shadow (that should be part of the shadow) gets narrower the higher the elevation (until a certain point).

It somehow feels that the shadow has too much offset on the y-axis and that this area should normally be behind the card. So I guess some calculation is incorrect.


Is there anything we can do against it? Except for setting the elevation to 0 (=killing the "Auto-shadow") and manually adding the shadow somehow?

**This is the excerpt from flutter doctor from the mac (android built is done on another machine)**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale de-DE)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

**Comment by kofan** [comment] 2020-02-05 02:09
I have the same issue for the `Card` widget on iOS even when it is not in the `PageView` and is not transformed, but when it has a decent height, e.g., when the card is higher than the half screen of iPhone Xs Max. I see the gap when using an elevation `>= 3.0`

**Comment by johngilesyoder** [comment] 2020-02-20 19:15
Having the exact same issue in iOS on a larger phone. Related to elevation and Cards. Regardless of PageView. Definitely a bug.

**Comment by darshankawar** [comment] 2020-08-26 12:10
Hi @slightfoot,
I verified this bug on latest stable (1.20.2) and noticed that the gap isn't there anymore. Tested on Android 8.1.0.

![18984](https://user-images.githubusercontent.com/67046386/91301709-f8ad4c80-e7c2-11ea-864e-b66c38f8e6ca.png)


<details>
<summary>flutter doctor -v</summary>

```
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (15 hours ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

Can you confirm this at your end and see if it has resolved ?
Thanks.

**Comment by kofan** [comment] 2020-08-27 08:21
It is not an Android problem - it is an iOS problem...

**Comment by darshankawar** [comment] 2020-09-16 09:53
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-16 09:53 UTC
Labels: P4, dependency: skia, engine, framework, waiting for customer response

**Comment by kofan** [comment] 2020-10-10 22:56
The issue is still reproduced on the latest version of Flutter (`1.22.1`), see **#67848**.
