### ISSUE TITLE
ReorderableListView#onReorder passes an unexpected new index

### ISSUE THREAD

**Issue by chrislambe** [flutter/flutter#24786] opened 2018-11-27 15:33 UTC
The `ReorderableListView` widget seems to passing an incorrect `newIndex` parameter when triggering the `onReorder` handler.

## Steps to Reproduce
Here's a demo of the behavior as described in the below steps:  
https://gist.github.com/chrislambe/b9aa44a5f3d3cc7dc6fdb24fb221982d

1. Create an app with a `ReorderableListView` widget and dummy data.
2. In the `onReorder` handler, print out the new index.
3. Drag the item in the 0 index position down until it swaps positions with the item in 1 index then, without releasing the item, drag it back to its original position and release. Note that the printed new index is `1` instead of `0`, even though the intent was to drop the item in its original position.
4. Drag the item to the bottom of the list and release. Note that the new index is 1 greater than the bounds of the `children` `List`.

### Result of above step 3
```
flutter: oldIndex: 0, newIndex: 1, length: 4
```

### Result of above step 4
```
flutter: oldIndex: 0, newIndex: 4, length: 4
```

### `flutter analyze`

```
$ flutter analyze
Analyzing on_reorder_broken...
No issues found! (ran in 2.3s)
```

### `flutter doctor -v`

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v0.11.9, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 0.11.9 at /Applications/flutter
    • Framework revision d48e6e433c (7 days ago), 2018-11-20 22:05:23 -0500
    • Engine revision 5c8147450d
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/chris/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (2 available)
    • moto x4   • ZY224KS2L3                           • android-arm64 • Android 8.1.0 (API 27)
    • iPhone XR • F2133438-AFB5-421D-9CC0-36FD9FE97D28 • ios           • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by jason-simmons** [comment] 2018-11-30 19:15
@DaveShuckerow

**Comment by Daniel-BD** [comment] 2019-10-25 20:07
I'm having the exact same issue, almost a year after this issue was opened. I'm running stable channel, v1.9.1+hotfix.2

Is this being worked on? Seems like this widget is pretty much useless without this being fixed :)

**Comment by ffeu** [comment] 2019-10-25 21:33
There's an easy workaround.

Check this out:
https://stackoverflow.com/a/54164333/796963

**Comment by fellow7000** [comment] 2020-01-18 17:53
Funny (not really) that more than one year later this simple bug is still in the framework,,,

Hello, Flutter Team, are you going to do anything on that?..

**Comment by esDotDev** [comment] 2020-02-19 16:29
The workaround is a pretty big hack, and still doesn't work 100%. This really needs to get fixed.

**Comment by TahaTesser** [comment] 2020-05-11 12:07
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-0.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-0.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision a849daf283 (3 days ago), 2020-05-07 18:59:02 -0700
    • Engine revision 3953c3ccd1
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 4da5b40fb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!


``` 

</details>

**Comment by Nomeleel** [comment] 2020-05-11 12:37
I have same issue [When use ReorderableListView dragging item from up to down, "newIndex" is incorrect.](https://github.com/flutter/flutter/issues/56821)

**Comment by vagaone** [comment] 2020-06-08 22:43
I digged a bit into it. The indices in reorderable_list.dart are mainly used for the UI handling of the droppable space and don't represent the array position of the elements being dragged. But, and that is the problem, the indices are then used for the reorder callback.

```
    // Places the value from startIndex one space before the element at endIndex.
    void reorder(int startIndex, int endIndex) {
      setState(() {
        if (startIndex != endIndex)
          widget.onReorder(startIndex, endIndex);
        // Animates leftover space in the drop area closed.
        // TODO(djshuckerow): bring the animation in line with the Material
        // specifications.
        _ghostController.reverse(from: 0.1);
        _entranceController.reverse(from: 0.1);
        _dragging = null;
      });
    }
```

A quick fix for the issue would be to decrease the endIndex if it is larger then the startIndex:

```
    void reorder(int startIndex, int endIndex) {
      setState(() {
        if (startIndex != endIndex) {
          if(endIndex > startIndex) {
            endIndex -= 1;
          }
          widget.onReorder(startIndex, endIndex);
        }
          
        // Animates leftover space in the drop area closed.
        // TODO(djshuckerow): bring the animation in line with the Material
        // specifications.
        _ghostController.reverse(from: 0.1);
        _entranceController.reverse(from: 0.1);
        _dragging = null;
      });
    }
```

Can anyone take a look and give some thought's on that? I don't think it is a really nice solution, but it works.

**Comment by perclasson** [comment] 2020-06-15 15:42
I believe this is intended behaviour if you take a look at the ReorderCallback documentation:
https://api.flutter.dev/flutter/material/ReorderCallback.html

There are some sample code at the bottom for how to handle the indexes inside of onOrder:

```dart
final List<MyDataObject> backingList = <MyDataObject>[/* ... */];

void handleReorder(int oldIndex, int newIndex) {
  if (oldIndex < newIndex) {
    // removing the item at oldIndex will shorten the list by 1.
    newIndex -= 1;
  }
  final MyDataObject element = backingList.removeAt(oldIndex);
  backingList.insert(newIndex, element);
}
```

Updating the API for this would be a breaking change for any existing apps that are implementing that behavior, so we would have to make sure to make any changes to this an opt in behavior to safely migrate any customers. The documentation for [ReordableListView](https://api.flutter.dev/flutter/material/ReorderableListView-class.html) should probably also be updated with an example for how to use the `onReorder`.

**Comment by AlbertoMonteiro** [comment] 2020-06-16 17:02
@perclasson I don't think so.
This same widget does have another bug that is even it does have only a single item, it allows being reordered, and even worst, it calls `onReorder` with values (0 and 1), but the list does not have index[1], since it does only have one single item

**Comment by esDotDev** [comment] 2020-06-16 18:36
That sample code still produces incorrect sorting in certain cases. This is not as designed.

**Comment by perclasson** [comment] 2020-06-16 19:21
@AlbertoMonteiro If you don't mind, please file another issue for the single item being re-orderable. It sounds like something that should be addressed too.
@esDotDev I agree that the API is confusing and I believe @vagaone is working on the issue so it should be improved. Also feel free to add any other incorrect sorting cases that you find here, that will help with debugging the change.

**Comment by AlbertoMonteiro** [comment] 2020-06-16 21:33
I've done it @perclasson #59599

**Comment by grantespo** [comment] 2020-09-26 03:18
Has this really been an issue for 2 years? lmao

Trying to implement this Widget but new index is incorrect, thus makes it useless :/

**Comment by toysonlocation** [comment] 2020-12-13 22:27
Fix this. It's a breaking change, and it needs to happen.

**Comment by pedromassangocode** [comment] 2020-12-30 13:20
By following the steps in the OP I was able to reproduce the issue, and here is my logs after following the steps in the OP:

```console
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1,211ms.
I/flutter ( 6035): oldIndex: 0, newIndex: 1, length: 4
I/flutter ( 6035): oldIndex: 0, newIndex: 4, length: 4
```

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.157, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.26.0-2.0.pre.157 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 4b83be6c23 (6 hours ago), 2020-12-30 02:09:03 -0500
    • Engine revision 0e5a25d779
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.1.5
    • Dart plugin version 203.5981.152

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (4 available)
    • Redmi 5 Plus (mobile)              • 0258ff700005  • android-arm64  • Android 8.1.0 (API 27)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by johnpryan** [comment] 2021-02-04 16:08
Another case where this shows up is simply dragging between index 0 and 1:

```
| index | before | after |
|-------|--------|-------|
| 0     | A      | B     |
| 1     | B      | A     |
| 2     | C      | C     |
```

This before / after table could represent either:
1. Dragging from index 0 to index 1
2. Dragging from index 1 to index 0

In both of these scenarios, it's reasonable to expect that the only two indexes we are working with are 0 and 1. But this is not the case:
1. `oldIndex` = 0, `newIndex` = 2.
2. `oldIndex` = 1, `newIndex` = 0.

This requires an additional check as recommended in the [ReorderCallback documentation](https://api.flutter.dev/flutter/material/ReorderCallback.html): 

```dart
final List<MyDataObject> backingList = <MyDataObject>[/* ... */];

void handleReorder(int oldIndex, int newIndex) {
  if (oldIndex < newIndex) {
    // removing the item at oldIndex will shorten the list by 1.
    newIndex -= 1;
  }
  final MyDataObject element = backingList.removeAt(oldIndex);
  backingList.insert(newIndex, element);
}
```

The question is why can't the implementation of `handleReorder` simply be:

```dart
void handleReorder(int oldIndex, int newIndex) {
  backingList.insert(newIndex, backingList.removeAt(_oldIndex));
}
```

The comment in the sample is also not very enlightening "Removing the item at oldIndex will shorten the list by 1". this is true, but would not be a problem if `newIndex` always represented *the index at which to insert the removed item*.

**Comment by pasrot943** [comment] 2021-02-23 08:31
Change the onReorder function to this one and it will work!

void _onReorder(int oldIndex, int newIndex) {
    setState(() {
      newIndex > oldIndex ? (){newIndex--;
      int row = V755.removeAt(oldIndex);
      V755.insert(newIndex, row);}() : (){int row = V755.removeAt(oldIndex);V755.insert(newIndex, row);}();
    });
  }

**Comment by pasrot943** [comment] 2021-02-23 08:32
V7555 is a list BTW!

**Comment by BurningAXE** [comment] 2021-03-08 16:30
I cannot comprehend how this serious issue with a popular widget and a simple fix is still around more than 2 years later...

**Comment by toysonlocation** [comment] 2021-03-08 16:42
Probably because they don't want to break existing code. Should have been fixed immediately, now there's a legacy. I'd say it's a disruptive enough bug that it should get a breaking fix, but I don't have to answer their support calls. Perhaps a second non-conventional call that does the right thing and warn people it will replace the bad call in next "big" release?  onReorderRight (?)

**Comment by BurningAXE** [comment] 2021-03-08 16:45
or onReorderFixed() :D Fine with me either way, just get it fixed!

**Comment by esDotDev** [comment] 2021-03-08 17:34
Isn't that what major version releases are for?

**Comment by toysonlocation** [comment] 2021-03-08 17:35
@esDotDev are you saying you know it will be fixed in the next release?

**Comment by esDotDev** [comment] 2021-03-08 17:39
No, I have no insight into any of that, just saying that it being a breaking change shouldn't really be an issue. Bump the version number and fix it? I guess it would be a rather sneaky one because the breakage would be non-obvious

**Comment by toysonlocation** [comment] 2021-03-08 17:42
Yeah, it's easy to be cynical and just want it fixed, I mean I do, but I'm sure it would jack a bunch of folks IF they recompiled or changed up their SDKs. Should be ok if they do nothing, right? Maybe the Web is different? Anyway if it takes a rebuild action on the developer's part to suddenly be exposed to correct functionality, then I agree with you, just do it!

**Comment by alexmercerind** [comment] 2021-03-20 19:19
What a great progress so far.

**Comment by araruna** [comment] 2021-05-28 03:37
I believe that the 'most promising' interpretation for the `newIndex` should be that it represents the _old index_ of the item that is now **after** the moved item. Then, the only annoying situation seems to be when we drag an item down and then place it back, which triggers the `onReorder` unnecessarily...

This even applies to the OP's case and seems to make sense of why sometimes this value is equal to the List's `length` (which would mean that none of the items is now after the moved item).

At least this is what seems to happen to me using the current version.

```text
$ flutter --version

Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (8 hours ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

**Comment by ronytesler** [comment] 2021-07-12 16:51
Any working workaround on web?!

**Comment by ronytesler** [comment] 2021-07-12 16:55
will it be correct to reduce 1 from newIndex if the item was moved from a lower index?

**Comment by kenthinson** [comment] 2021-07-23 15:54
@ronytesler 

This is what I'm using that seems to be working in my testing.

```

                                array.insert(newIndex, array[oldIndex]);
                            if (oldIndex < newIndex) {
                              array.removeAt(oldIndex);
                            } else {
                              array.removeAt(oldIndex + 1);
                            }
                            setState(() {});
```

**Comment by Pitazzo** [comment] 2021-07-27 16:40
I can't believe this bug is 2 years old

**Comment by Flucadetena** [comment] 2021-09-22 14:40
Same Issue, in my case when you move a Widget "higher" in the list, from 0 to 1, the "newIdx" comes wrong with a "+1". So instead of 1 you get 2. But when you move the widget "down" in the list, the values come wright. So my code looks like this:

```
onReorder: (oldIdx, newIdx) {

        Widget wid = widgets.removeAt(oldIdx);
        if (newIdx > oldIdx)
          widgets.insert(newIdx - 1, wid);
        else
          widgets.insert(newIdx, wid);

        setState(() {});
      },

```

**Comment by banderberg** [comment] 2021-10-14 12:59
Just discovered this bug for myself this morning.  Surely the fix can't be very difficult to implement.

**Comment by HansMuller** [comment] 2022-02-08 19:19
We've decided not to correct this issue because the obvious fix introduces a backwards incompatibility that can't be automatically corrected. More here: https://github.com/flutter/flutter/pull/93146#issuecomment-1032082749

I apologize for not resolving this quickly, when it would have been possible to just make the break.

**Closed by HansMuller** 2022-02-08 19:19 UTC
Labels: framework, f: material design, severe: API break, f: scrolling, a: quality, customer: crowd, has reproducible steps, P4, found in release: 1.26
