### ISSUE TITLE
Chinese garbled, on the web

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#74785] opened 2021-01-27 06:49 UTC
![image](https://user-images.githubusercontent.com/3191545/105953750-abedda80-60ae-11eb-9ccf-d5134d2f0c3d.png)
macos displays normally, but there is a problem with Chinese on the web

**Comment by iapicca** [comment] 2021-01-27 07:16
duplicate of https://github.com/flutter/flutter/issues/73628

@chongbo2013 
the issue should be fixed on master
you may want to try 
```console
flutter channel master
flutter upgrade -f
```

**Comment by pedromassangocode** [comment] 2021-01-27 08:05
Closing as a duplicate of #73628.
This should be fixed on master.

**Closed by pedromassangocode** 2021-01-27 08:05 UTC
