### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create link, OS Error: 잘못된 기능입니다., errno = 1

### ISSUE THREAD

**Issue by Icerea** [flutter/flutter#124378] opened 2023-04-07 07:53 UTC
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot create link, OS Error: 잘못된 기능입니다.
, errno = 1
```
#0      _Link.throwIfError (dart:io/link.dart:254:7)
#1      _Link.createSync (dart:io/link.dart:182:5)
#2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#3      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20:16)
#4      _createPlatformPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:1055:12)
#5      createPluginSymlinks (package:flutter_tools/src/flutter_plugins.dart:992:5)
#6      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1087:5)
<asynchronous suspension>
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:353:5)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:326:7)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1312:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
```
```
[32m[✓][39m Flutter (Channel master, 3.9.0-20.0.pre.27, on Microsoft Windows [Version 10.0.19044.1586], locale ko-KR)
    [32m•[39m Flutter version 3.9.0-20.0.pre.27 on channel master at E:\src\flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision a72a8baabe (8 days ago), 2023-03-30 06:38:26 -0400
    [32m•[39m Engine revision 72b4e88c44
    [32m•[39m Dart version 3.0.0 (build 3.0.0-384.0.dev)
    [32m•[39m DevTools version 2.22.2

[32m[✓][39m Windows Version (Installed version of Windows is version 10 or higher)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: E:\windows\Programs (x86)\android studio\jbr\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[32m[✓][39m Android Studio (version 2022.1)
    [32m•[39m Android Studio at E:\windows\Programs (x86)\android studio
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[32m[✓][39m VS Code (version 1.72.0)
    [32m•[39m VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.60.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Chrome (web) • chrome • web-javascript • Google Chrome 111.0.5563.148
    [32m•[39m Edge (web)   • edge   • web-javascript • Microsoft Edge 111.0.1661.62

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 87ac905a5a1bc7cba1d655c3d004269a6a30d7fb
### Plugins
flutter_local_notifications-13.0.0
path_provider_linux-2.1.10
path_provider_windows-2.1.5
shared_preferences-2.0.20
shared_preferences_android-2.0.17
shared_preferences_foundation-2.1.5
shared_preferences_linux-2.1.5
shared_preferences_web-2.0.6
shared_preferences_windows-2.1.5

**Comment by huycozy** [comment] 2023-04-07 08:40
Closing as duplicate of https://github.com/flutter/flutter/issues/66224

**Closed by huycozy** 2023-04-07 08:40 UTC
Labels: in triage
