### ISSUE TITLE
Sky APKs have no way to report Dart errors from the field

### ISSUE THREAD

**Issue by FlutterIssues** [flutter/flutter#128] opened 2015-11-09 21:15 UTC
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Tuesday Aug 18, 2015 at 18:10 GMT_
_Originally opened as https://github.com/flutter/engine/issues/674_

----

Maybe there is a Play Store API we can hook into?  Maybe we need to build our own (or presumably there is a third party solution?)  Difficult to know when users hit Dart exceptions in our apps.

Others must have solved this...
@abarth @collinjackson

**Comment by FlutterIssues** [comment] 2015-11-09 21:15
<a href="https://github.com/eseidelGoogle"><img src="https://avatars.githubusercontent.com/u/11857803?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eseidelGoogle](https://github.com/eseidelGoogle)**
_Tuesday Aug 18, 2015 at 18:11 GMT_

----

https://airbrake.io/ is one 3rd party.  https://raygun.io/ is another.

**Comment by Hixie** [comment] 2015-12-11 23:19
Duplicate of https://github.com/flutter/flutter/issues/614

**Closed by Hixie** 2015-12-11 23:19 UTC
