### ISSUE TITLE
Can't get MediaQuery.of(context).viewInsets.bottom when in fullscreen and the keyboard is open.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#25050] opened 2018-12-06 21:12 UTC
When the keyboard opens, `MediaQuery.of(context).viewInsets.bottom` changes to reflect the new bottom (which is now at the top of the keyboard).

However, the Android app may be in fullscreen:
```xml
    <?xml version="1.0" encoding="utf-8"?>
    <resources>
        <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
            <!-- Show a splash screen on the activity. Automatically removed when
                 Flutter draws its first frame -->
            <item name="android:windowBackground">@drawable/launch_background</item>
            <item name="android:windowFullscreen">true</item>
        </style>
        <color name="xxx">#FFFF00</color>
    </resources>
```
(See: https://medium.com/@diegoveloper/flutter-splash-screen-9f4e05542548)

When this is the case, `viewInsets.bottom` will always be `0.0`, even when the keyboard is open, which is wrong and creates all sorts of problems.

**Comment by budo385** [comment] 2019-04-04 22:19
Hi all, any update on this would be very appreciated!

**Comment by kkroid** [comment] 2019-04-11 03:41
Just encountered the same issue, any update on this?

**Comment by g-balas** [comment] 2019-06-29 10:36
Same problem on iOS, not even fullscreen

**Comment by eckhartcke** [comment] 2019-07-19 00:25
Also seeing this on IOS. My use case is a page within a PageView, plus I am doing custom scaling to the page widget, but the _MediaQuery.of(context).viewInsets.bottom_ value is always zero whether keyboard is present or no.
I can post a gist if it would help to troubleshoot the issue.

**Comment by KiraDiShira** [comment] 2019-07-22 15:15
Any news about this?

**Comment by wwwdata** [comment] 2019-07-22 15:25
Also had this issue but after setting this scaffold property to false I am getting the insets again. Did you guys also set it to false? See: https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomInset.html

**Comment by MrCreeper1008** [comment] 2019-09-15 17:39
I set `resizeToAvoidBottomInset` to `false`. Same problem.

**Comment by zhanglei829** [comment] 2019-09-19 08:14
I found that `mediaquery.of (context). ViewInsets. Bottom `always returns `zero` when used with `bottomNavigationBar`

**Comment by TutOsirisOm** [comment] 2019-10-21 17:39
I have this issue as well

**Comment by amen71311** [comment] 2019-11-20 09:23
I ran into this issue by adding to existing app, but my existing app not even set the fullscreen option. 
It work well on iOS, but not in Android.
`resizeToAvoidBottomInset` is also useless in this situation. 
Hope we got some news about this.

**Comment by MichealReed** [comment] 2020-01-19 01:14
Running into same. Anyone have any other best practices to share when working with full screen flutter?

**Comment by amen71311** [comment] 2020-01-19 01:28
> Running into same. Anyone have any other best practices to share when working with full screen flutter?

If you are adding Flutter to existing project. They have update the new docs here to open Flutter with your own activity. Or else, you can try to write some platform specific code to open a new activity by yourself.

https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen

**Comment by xiongcen** [comment] 2020-03-10 14:32
when I set FlutterActivity android:windowSoftInputMode="adjustResize" or other attributes，MediaQuery.of(context).viewInsets.bottom not return 0.0

I think viewInsets.bottom‘s value have a relationship with windowSoftInputMode. I just try this one.

**Comment by Xgamefactory** [comment] 2020-03-27 18:07
if u are using sub widgets try pass scaffold buildcontext to this widget.
and try  MediaQuery.of(context).viewInsets.bottom  with scaffold context not child widgets one.

**Comment by febg11** [comment] 2020-03-27 20:40
So I use a bottom navigation bar and I am trying to get the height of the keyboard.

When I call 

```
mediaquery.of (context).viewInsets.Bottom
```
It always includes the keyboards height + the bottom navigation bar height. Is there anyway to just get the keyboard height?

I have tried to use 

```
SizedBox(
              height: MediaQuery.of(contextField).viewInsets.bottom - widget.bottomNavigationBarKey.currentContext.size.height,
              child: Container(color:Colors.pink),
            )
```

But this fails because its trying to reference something that hasn't been built (bottomNavigationBarKey)  in the build method.

**Comment by davidmartos96** [comment] 2020-06-16 08:47
I think is worth noting that this issue also occurs when not using an app in fullscreen, but the demo app template instead. If one tries to get the bottom viewInset from a different context inside a `Scaffold` with a `BottomNavigationBar`, the viewInset is always zero. 
Using a `GlobalKey` context to the `Scaffold` works correctly, but it's not reactive when the keyboard opens and closes.

Should the title of the issue be updated?

<details><summary>Minimal code sample</summary>
<p>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

final GlobalKey<ScaffoldState> scaffoldKey = GlobalKey();

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: scaffoldKey,
      appBar: AppBar(
        title: Text("View insets"),
      ),
      body: ScaffoldBody(),
      bottomNavigationBar: BottomNavigationBar(items: [
        BottomNavigationBarItem(
          icon: Icon(Icons.home),
          title: Text("Tab 1"),
        ),
        BottomNavigationBarItem(
          icon: Icon(Icons.settings),
          title: Text("Tab 2"),
        ),
      ]),
    );
  }
}

class ScaffoldBody extends StatelessWidget {
  const ScaffoldBody({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          FlatButton(
            onPressed: () {
              final mq1 = MediaQuery.of(context);
              final mq2 = MediaQuery.of(scaffoldKey.currentContext);
              print("View insets (current context) = ${mq1.viewInsets}");
              print("View insets (scaffold context) = ${mq2.viewInsets}");
              print("");
            },
            child: Text("Print view insets"),
          ),
          TextField(
            decoration: InputDecoration(hintText: "Some textfield..."),
          ),
        ],
      ),
    );
  }
}
```

</p>
</details>

**Comment by battlecook** [comment] 2020-07-07 05:25
Any other news about it?

**Comment by AugustToko** [comment] 2020-08-06 11:47
> try MediaQuery.of(context).viewInsets.bottom with scaffold context not child widgets one.

Works for me

**Comment by pedromassangocode** [comment] 2020-09-09 13:35
Hi @marcglasberg 
Are you still facing this issue?

With the code bellow the print output is: 
```
Restarted application in 1,336ms.
I/flutter ( 5326): Bottom is: 0.0
```

When the keyboard opens it prints:
`I/flutter ( 5326): Bottom is: 249.0909090909091`

Tested on Pixel 3a emulator with the fullscreen configuration in the Android side provided by you.

<details><summary>sample code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MaterialApp(home: InputPage(),));
class InputPage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return InputPageState();
  }
}

class InputPageState extends State<InputPage> {

  void show() async {
    showGeneralDialog(
        context: context,
        barrierDismissible: true,
        barrierLabel:
        MaterialLocalizations.of(context).modalBarrierDismissLabel,
        barrierColor: Colors.black45,
        transitionDuration: const Duration(milliseconds: 200),
        pageBuilder: (BuildContext buildContext, Animation animation,
            Animation secondaryAnimation) {
          return AlertDialog(
              contentPadding: EdgeInsets.all(0),
              content: Container(
                  height: 200,
                  width: 200,
                  color: Colors.red,
                  child: TextField(
                    keyboardType: TextInputType.multiline,
                    minLines: 5, //Normal textInputField will be displayed
                    maxLines: 5, // when user presses enter it will adapt to it
                    textAlign: TextAlign.left,
                  )));
        });
  }

  @override
  Widget build(BuildContext context) {
    final bottom = MediaQuery.of(context).viewInsets.bottom;
    print('Bottom is: $bottom');

    return Scaffold(
      appBar: AppBar(
        title: Text("Test"),
      ),
      body: Center(
        child: TextField(),
      ),
    );
  }
}
```
</details>

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en)
    • Flutter version 1.20.3 at /Users/pedromassango/dev/SDKs/flutter_stable
    • Framework revision 216dee60c0 (8 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```
</details>

**Comment by darshankawar** [comment] 2020-09-30 11:03
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by darshankawar** 2020-09-30 11:03 UTC
Labels: P4, customer: crowd, engine, framework, platform-android, waiting for customer response

**Comment by noteScript** [comment] 2020-10-23 12:38
> try MediaQuery.of(context).viewInsets.bottom with scaffold context not child widgets one.

Try to use scaffold's context instead of the local widget's. This situation is usually caused by incorrect context.

**Comment by azack** [comment] 2020-11-18 02:51
This is reproduceable in `flutter beta` `1.23.0-18.1.pre` on an `Android 10` emulator or device.  On an `Android 11` device, it works as expected.

The sample code from @pedromassangocode 's comment https://github.com/flutter/flutter/issues/25050#issuecomment-689567401 is sufficient to reproduce this.

### Steps to reproduce

#### Part 1: Control test
1. Create a new flutter project
1. Replace main.dart with the code from https://github.com/flutter/flutter/issues/25050#issuecomment-689567401
1. Run the flutter app on an Android 10 emulator or device; it should work as expected, showing a `bottom:` with some non-zero value.

#### Part 2: Introducing bug
1. Modify `android/app/src/main/res/values/styles.xml`, adding `<item name="android:windowFullscreen">true</item>` under `<style name="NormalTheme" [...]` to set the app as fullscreen
1. Rerun the flutter app on an Android 10 emulator or device.  Now notice that the viewInsets are always zero even when the keyboard is up.

**Comment by noteScript** [comment] 2020-11-18 03:22
@azack @pedromassangocode You just need to use the right context to work, The correct context is a full screen widget.
For example: `scaffold` `Stack` ...

**Comment by azack** [comment] 2020-11-18 03:58
@noteScript In my testing it appears to depend on the method in which the app is set to fullscreen, even when checking the correct context -  see the table below.

#### MediaQuery.of(SomeContext).viewInsets.bottom on API 29 & 30 Emulators

Using sample code above, with minor change to also examine Scaffold context

| FullScreen Method | Works on API 29? | InputPageState / Scaffold |  Works on API 30? | InputPageState / Scaffold |
| -- | -- | -- | -- | -- | 
| `SystemChrome.setEnabledSystemUIOverlays([]);` | Yes | 393 | Yes | 297 |
| `<item name="android:windowFullscreen">true</item>` | **No** | 0 |  Yes | 249 |
| Both of the above | **No** | 0 |  Yes | 297 |
| Not fullscreen | Yes | 337 | Yes | 249 |

**Comment by noteScript** [comment] 2020-11-18 08:58
@azack 

Sorry, I didn't encounter this situation. The version I used is:
```bash
Flutter channels:
  master
  dev
  beta
* stable
```

```bash
Flutter 1.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84f3d28555 (- -) • 2020-10-15 16:26:19 -0700
Engine • revision b8752bbfff
Tools • Dart 2.10.2
```

**Comment by azack** [comment] 2020-11-18 15:19
Thanks for the additional information, @noteScript .  Maybe there's something else varying in our environments and with the original reporter.

I continue to see the bug with latest stable `1.22.4`:

|  Method | Flutter Version | Works on API 29? | Bottom | Works on API 30? | Bottom  |
| --- | --- | --- | --- | --- | --- |
| `<item name="android:windowFullscreen">true</item>` | 1.22.4 | No | 0 | Yes | 249 |

<details>
<summary>flutter doctor</summary>

```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.22.4 at development\flutter
    • Framework revision 1aafb3a8b9 (5 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.51.1)
    • VS Code at AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 2 categories.

```
</details>

**Comment by andersonmendesdev** [comment] 2021-04-22 16:49
Problem still exists in stable channel 2.0.5 Android and iOS
Instead of `MediaQuery.of(context).viewInsets.bottom` I am using `WidgetsBinding.instance.window.viewInsets.bottom`, but on some android 11 and 10 it remains as 0 when the keyboard is open.

**Comment by NikarashiHatsu** [comment] 2021-06-06 11:44
I'm sorry to the maintainer for the bump, to this date as I write this, the bug is still exists in Android.
If you use `GlobalKey<ScaffoldState>` for the `Scaffold`'s `key`, then you're probably having the same problem as I am.

The quick solution on how I fix this is simply by using `MediaQuery.of(_scaffoldKey.currentContext!).viewInsets.bottom`.

**Comment by 0x1af2aec8f957** [comment] 2021-06-17 15:24
@andersonmendesdev 

In the version of 'stable channel 2.0.5', this problem has been fixed, and `mediaquery.of(context). Viewinsets. Bottom` is no longer needed. However, in the version of 'stable channel 2.2.2', this problem occurs again.
