### ISSUE TITLE
Material gallery crashes when you press the drop-down button

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#620] opened 2015-11-30 06:15 UTC

**Comment by Hixie** [comment] 2015-11-30 06:15
(A red screen of death crash, not an engine crash.)

**Comment by abarth** [comment] 2015-11-30 06:16
Yeah, I broke this with RepaintBoundary.  The problem is that dropdown list uses `Positioned` to position itself instead of using the OverlayPosition.

**Comment by HansMuller** [comment] 2015-11-30 22:07
Do you mean that _DropDownRoute<T> should provide an override of:
```
  ModalPosition get position => null; // from ModalRoute<T>
```

**Comment by abarth** [comment] 2015-11-30 22:13
Yes, exactly.

**Comment by abarth** [comment] 2015-12-04 23:07
Closing as duplicate of #630

**Closed by abarth** 2015-12-04 23:07 UTC
Labels: affects: framework, affects: material design, customer: demos, ⚠ bug (regression), ⚠ crash
