### ISSUE TITLE
ListTile needs sample code showing how to replace it with Row when it doesn't quite fit the use case

### ISSUE THREAD

**Issue by gabrc52** [flutter/flutter#28685] opened 2019-03-01 00:18 UTC
`ListTile`'s leading widget doesn't appear properly centered. This seems to be a regression as it rendered properly before.

![image](https://user-images.githubusercontent.com/24363938/53607664-496bc700-3b85-11e9-9972-c83591cf63e3.png)

```
[✓] Flutter (Channel beta, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1
    • Framework revision 8661d8aecd (2 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

```dart
import 'package:flutter/material.dart';

void main() => runApp(
      MaterialApp(
        home: Scaffold(
          body: ListView(
            children: <Widget>[
              ListTile(
                title: Text("I'm a ListTile"),
                subtitle: Text('Look at the leading icon'),
                leading: Icon(Icons.info),
                trailing: Icon(Icons.launch),
              ),
            ],
          ),
        ),
      ),
    );
```

**Comment by Adrianogba** [comment] 2019-03-06 01:50
Everything you put on the leading property is. Still happening on 1.3.4.

**Comment by daniloadorno** [comment] 2019-03-07 20:48
line 997 to line 1033 of the file list_tile.dart
new value:
double leadingY;
    double trailingY;
    if (tileHeight > 72.0) {
      leadingY = 16.0;
      trailingY = 16.0;
    } else {
      leadingY = math.min((tileHeight - leadingSize.height) / 2.0, 16.0);
      trailingY = (tileHeight - trailingSize.height) / 2.0;
    }

old value:
final double leadingY = (tileHeight - leadingSize.height) / 2.0;
final double trailingY = (tileHeight - trailingSize.height) / 2.0;

**Comment by ashihCT** [comment] 2019-03-08 20:25
ugh... I just upgraded Flutter and now my Leading & Trailing alignments are all jacked up.

**Comment by ashihCT** [comment] 2019-03-08 20:57
> final double leadingY = (tileHeight - leadingSize.height) / 2.0;
> final double trailingY = (tileHeight - trailingSize.height) / 2.0;

That is indeed the problem...

**Comment by shihaohong** [comment] 2019-03-29 19:59
Hi everyone, this change was a result of [this PR](https://github.com/flutter/flutter/pull/26778), which updated the `leading` icon logic to allow for implementations seen in the [material spec](https://material.io/design/components/lists.html#specs). Notice that for three-line widgets, leading icons are not necessarily centered vertically.

If you'd like to center your widget, a recommendation I have is to wrap your widget in a center-aligned container:
```
ListTile(
  leading: Container(
    width: 40, // can be whatever value you want
    alignment: Alignment.center,
    child: Icon(Icons.access_alarm),
  ),
  title: Text('title'),
  subtitle: Text('this is the subtitle'),
)
```

**Comment by shihaohong** [comment] 2019-03-29 20:12
I'm going to close this issue for now, since the change was intentional, but please feel free to re-open this if there are there are other problems related to the `leading` widget.

**Comment by daniloadorno** [comment] 2019-03-29 22:37
in this case it will not be aligned vertically, and impute height in it for that, can not define a parameter to choose the alignment of it?

**Comment by shihaohong** [comment] 2019-03-29 22:45
@daniloadorno I don't understand your question. Could you define a use-case to clarify?

**Comment by daniloadorno** [comment] 2019-03-29 22:59
the example you submitted does not allow vertical alignment.


ListView.builder(
  itemCount: 50,
  physics: const AlwaysScrollableScrollPhysics(),
  itemBuilder: (context, index) {
	return new Column(
	  children: <Widget>[
		new ListTile(
		  title: new Column(
			crossAxisAlignment: CrossAxisAlignment.start,
			children: <Widget>[
			  SizedBox(height: 8.0),
			  new Text("Value 1",
				style: TextStyle(fontWeight: FontWeight.bold),
			  )
			],
		  ),
		  subtitle: new Column(
			crossAxisAlignment: CrossAxisAlignment.start,
			children: <Widget>[

			  new SizedBox(height: 4.0),

			  new Text("Value 2",
				style: TextStyle(fontWeight: FontWeight.bold),
			  ),

			  new SizedBox(height: 4.0),

			  new Text("Value 3",
				style: TextStyle(fontWeight: FontWeight.normal),
			  ),

			  new SizedBox(height: 4.0),

			  new Text("Value 4",
				style: TextStyle(fontWeight: FontWeight.normal),
			  ),

			  new SizedBox(height: 4.0),

			  new Text("Value 4",
				style: TextStyle(fontWeight: FontWeight.normal),
			  ),

			  new SizedBox(height: 4.0),

			  new Text("Value 4",
				style: TextStyle(fontWeight: FontWeight.normal),
			  ),

			  new SizedBox(height: 8.0),

			],
		  ),
		  leading: new Container(
			width: 40,
			alignment: Alignment.center,
			child: new Text(
			  "29-03\n2019",
			  style: TextStyle(fontWeight: FontWeight.bold),
			  textAlign: TextAlign.center,
			),
		  ),
		),
		new Divider(height: 4.0),
	  ],
	);
  }),

**Comment by daniloadorno** [comment] 2019-03-29 23:01
![Flutter](https://user-images.githubusercontent.com/12452595/55266783-687d7780-525d-11e9-859c-a1d5d0340dbe.PNG)

**Comment by shihaohong** [comment] 2019-03-29 23:09
@daniloadorno The implementation you're using is probably better suited for a `Row` widget. A `ListTile` should only have at most 3 lines of text. In this case, you're using it with 6 rows.

**Comment by ashihCT** [comment] 2019-04-01 16:29
@shihaohong I agree with @daniloadorno, this doesn't solve the alignment issue.
I followed your suggestion by adding an alignment:

```
  ListTile buildListTile(Show show) => ListTile(
        contentPadding: EdgeInsets.symmetric(horizontal: 10.0, vertical: 5.0),
        leading: _buildLeadingTile(),
        title: Text(
          show.artist,
          style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
        ),
        subtitle: _buildSubtitleTile(show),
        trailing: Icon(Icons.keyboard_arrow_right,
            color: FestivalColor.tango, size: 25.0),
        onTap: () {
          Navigator.push(
              context,
              MaterialPageRoute(
                  builder: (context) => ArtistDetail(show: show)));
        },
      );

  Widget _buildLeadingTile() {
    return Container(
      padding: EdgeInsets.only(right: 10.0),
      width: 85,
      alignment: Alignment.center,
      decoration: new BoxDecoration(
          border: new Border(
              right: new BorderSide(width: 1.0, color: FestivalColor.wasabi))),
      child: Container(
        width: 75,
        height: 75,
        child: Image.network(
            "https://picsum.photos/250?image=${Random.secure().nextInt(50)}"),
        decoration: BoxDecoration(
          image: DecorationImage(
            image: ExactAssetImage("images/bandIcon.png"),
            fit: BoxFit.cover,
          ),
        ),
      ),
    );
  }
```
Alignment is off for Leading & Trailing widgets.
<img width="350" alt="Screen Shot 2019-04-01 at 12 20 36 PM" src="https://user-images.githubusercontent.com/42871040/55343207-a4405900-5478-11e9-9f22-de0c521c37f8.png">

I don't understand what you mean by a `Row` widget is better suited. Should you not be using ListBuild & ListTiles to build lists? 
It seems to me like both iOS & Android versions of Google's YouTube violate the 3 line text limit:

<img width="350" src="https://user-images.githubusercontent.com/42871040/55343428-1618a280-5479-11e9-80d9-b73f741c0458.PNG">

<img width="350" alt="Screen Shot 2019-04-01 at 12 28 12 PM" src="https://user-images.githubusercontent.com/42871040/55343709-a8b94180-5479-11e9-840f-fc6dfa50b265.png">

I am basically trying to achieve the same thing.

**Comment by ashihCT** [comment] 2019-04-02 14:35
Rebuilt my List without `ListTile` but with `Row` and `Column` and works fine.
`ListTile` seems pretty useless unless it's less than 72 height with a calculated leading less than 16.0 regardless of number of lines. Meh

**Comment by Hixie** [comment] 2019-04-05 19:44
ListTile is indeed not useful if your use case is not one of the ones it was designed for (the ones in the material spec).

What we really should do is put some sample code in the ListTile docs showing how to recreate ListTile using Row and company, for the cases where it doesn't quite match what you want. I thought we had a bug on this but I can't find it...

**Comment by Hixie** [comment] 2019-04-05 19:46
(btw, @ashihCT, please take another look at https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md when you have a chance — "pretty useless" and "meh" aren't examples of the positive attitude that we would like to keep in these bugs.)

**Comment by gabrc52** [comment] 2019-04-05 21:11
@shihaohong

Hmm. In the specification, the leading widget in tiles with one line in its subtitle does appear nicely centered:

![2-line](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1-YqqvjVvKr2aWHg6yQ9KOP9yFbk-4o9t%2Flist-spec-doubleline-individual.png)

![3-line](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F12GMB_cxP-3KCbZ2JxkAizaX2pGWXmOMA%2Flist-spec-threeline-individual.png)

However, for three-line items it's centered if the widget is large enough.

Ideally we should have a property such as `bool centerLeadingWidget`, to give developers more control.

**Comment by Hixie** [comment] 2019-04-05 21:16
Our goal with ListTile is to implement exactly the cases in the spec and no others.
It's easy to create custom variants. We should definitely show how to do so. But once you can do so, there's really no reason to keep using ListTile.

**Comment by ashihCT** [comment] 2019-04-05 21:30
@Hixie reworded.

**Comment by shihaohong** [comment] 2019-04-05 21:44
Here's the bug: https://github.com/flutter/flutter/issues/10673
Here's the[PR I'm currently working on: https://github.com/flutter/flutter/pull/30537

I'm still working on two more examples to add for when `ListTile` doesn't suit the developer's needs.

**Closed** 2019-04-09 17:10 UTC
Labels: d: api docs, f: material design, framework
