### ISSUE TITLE
Application crashed

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [flutter/flutter#81820] opened 2021-05-04 11:03 UTC
Hi, I have migrated my code to null-safety and am using latest flutter version. App crashes all the time when i am hovering over ```DateTime``` variable once stoped on break point. here is an error:

<details> 
<summary>logs</summary> 
	
```console
    ../../third_party/dart/runtime/vm/object.cc: 24140: error: Fatal error in ExternalTypedData::New: invalid len -937022072
E/Dart    (25094):
E/DartVM  (25094): version=2.12.3 (stable) (Wed Apr 14 11:02:39 2021 +0200) on "android_ia32"
E/DartVM  (25094): pid=25094, thread=25153, isolate_group=main(0xf724c5b0), isolate=main(0xf714d810)
E/DartVM  (25094): isolate_instructions=c750f300, vm_instructions=c750f300
E/DartVM  (25094):   pc 0xc763fb3b fp 0xc8262c68 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1828b3b
E/DartVM  (25094):   pc 0xc78d0b51 fp 0xc8262c88 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1ab9b51
E/DartVM  (25094):   pc 0xc750f497 fp 0xc8262cb8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x16f8497
E/DartVM  (25094):   pc 0xc7618cfd fp 0xc8262d08 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1801cfd
E/DartVM  (25094):   pc 0xc76995fe fp 0xc8262e08 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x18825fe
E/DartVM  (25094):   pc 0xc769065a fp 0xc8262ef8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x187965a
E/DartVM  (25094):   pc 0xc7690c9b fp 0xc8262f38 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1879c9b
E/DartVM  (25094):   pc 0xc75864fa fp 0xc8263088 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x176f4fa
E/DartVM  (25094):   pc 0xc75b1b0c fp 0xc82630e8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x179ab0c
E/DartVM  (25094):   pc 0xc75b1f2f fp 0xc8263128 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x179af2f
E/DartVM  (25094):   pc 0xc78b9648 fp 0xc8263198 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1aa2648
E/DartVM  (25094):   pc 0xc758ba96 fp 0xc82631f8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1774a96
E/DartVM  (25094):   pc 0xc7567fc4 fp 0xc82632f8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1750fc4
E/DartVM  (25094):   pc 0xc7570f28 fp 0xc8263408 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1759f28
E/DartVM  (25094):   pc 0xc7685877 fp 0xc8263478 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x186e877
E/DartVM  (25094):   pc 0xc4b012ac fp 0xc8263494 Unknown symbol
E/DartVM  (25094):   pc 0xc4b01bf7 fp 0xc82634a8 Unknown symbol
E/DartVM  (25094):   pc 0xab8ac7a8 fp 0xc82634c0 Unknown symbol
E/DartVM  (25094):   pc 0xab8ac5a8 fp 0xc82634f4 Unknown symbol
E/DartVM  (25094):   pc 0xac7fc61e fp 0xc8263514 Unknown symbol
E/DartVM  (25094):   pc 0xac7fb433 fp 0xc826358c Unknown symbol
E/DartVM  (25094):   pc 0xc4b017d8 fp 0xc82635dc Unknown symbol
E/DartVM  (25094):   pc 0xab8f306b fp 0xc8263634 Unknown symbol
E/DartVM  (25094):   pc 0xab8ffc00 fp 0xc8263674 Unknown symbol
E/DartVM  (25094):   pc 0xab8fb83a fp 0xc8263698 Unknown symbol
E/DartVM  (25094):   pc 0xab8fe64e fp 0xc82636b0 Unknown symbol
E/DartVM  (25094):   pc 0xab8fe0a7 fp 0xc82636d4 Unknown symbol
E/DartVM  (25094):   pc 0xab8f46ed fp 0xc82636f0 Unknown symbol
E/DartVM  (25094):   pc 0xab8e6922 fp 0xc826372c Unknown symbol
E/DartVM  (25094):   pc 0xab8d3cbe fp 0xc8263750 Unknown symbol
E/DartVM  (25094):   pc 0xab8d3631 fp 0xc8263774 Unknown symbol
E/DartVM  (25094):   pc 0xab8d1c47 fp 0xc8263790 Unknown symbol
E/DartVM  (25094):   pc 0xbbd5f5de fp 0xc82637ac Unknown symbol
E/DartVM  (25094):   pc 0xab8c7430 fp 0xc82637c4 Unknown symbol
E/DartVM  (25094):   pc 0xab8c72d3 fp 0xc82637e0 Unknown symbol
E/DartVM  (25094):   pc 0xc387f966 fp 0xc8263818 Unknown symbol
E/DartVM  (25094):   pc 0xc387f73f fp 0xc8263848 Unknown symbol
E/DartVM  (25094):   pc 0xc387f4a1 fp 0xc8263894 Unknown symbol
E/DartVM  (25094):   pc 0xbc6ae22f fp 0xc82638d4 Unknown symbol
E/DartVM  (25094):   pc 0xb9ebb826 fp 0xc82638fc Unknown symbol
E/DartVM  (25094):   pc 0xab8c3905 fp 0xc8263920 Unknown symbol
E/DartVM  (25094):   pc 0xab8c37e6 fp 0xc8263938 Unknown symbol
E/DartVM  (25094):   pc 0xc4b015a1 fp 0xc8263964 Unknown symbol
E/DartVM  (25094):   pc 0xc75634a6 fp 0xc82639c8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x174c4a6
E/DartVM  (25094):   pc 0xc75632c5 fp 0xc8263a28 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x174c2c5
E/DartVM  (25094):   pc 0xc75f8055 fp 0xc8263ac8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x17e1055
E/DartVM  (25094):   pc 0xc78c930c fp 0xc8263bc8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1ab230c
E/DartVM  (25094):   pc 0xc73cc6e7 fp 0xc8263be8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x15b56e7
E/DartVM  (25094):   pc 0xc7080f2c fp 0xc8263c48 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1269f2c
E/DartVM  (25094):   pc 0xc708a910 fp 0xc8263c88 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1273910
E/DartVM  (25094):   pc 0xc709304c fp 0xc8263ca8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x127c04c
E/DartVM  (25094):   pc 0xc7093081 fp 0xc8263cd8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x127c081
E/DartVM  (25094):   pc 0xc7094102 fp 0xc8263d18 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x127d102
E/DartVM  (25094):   pc 0xc7092bde fp 0xc8263d58 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x127bbde
E/DartVM  (25094):   pc 0xc70a33ab fp 0xc8263d98 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x128c3ab
E/DartVM  (25094):   pc 0xc704a41c fp 0xc8263db8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x123341c
E/DartVM  (25094):   pc 0xc704d214 fp 0xc8263e48 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1236214
E/DartVM  (25094):   pc 0xc704d125 fp 0xc8263e78 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1236125
E/DartVM  (25094):   pc 0xc70538fb fp 0xc8263e98 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x123c8fb
E/DartVM  (25094):   pc 0xc7053929 fp 0xc8263eb8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x123c929
E/DartVM  (25094):   pc 0xf29af318 fp 0xc8263ee8 android::SimpleLooperCallback::handleEvent(int, int, void*)+0x28
E/DartVM  (25094):   pc 0xf29b0348 fp 0xc8264038 android::Looper::pollInner(int)+0x468
E/DartVM  (25094):   pc 0xf29afe77 fp 0xc8264078 android::Looper::pollOnce(int, int*, int*, void**)+0x77
E/DartVM  (25094):   pc 0xea1e83f6 fp 0xc82640c8 ALooper_pollOnce+0x66

E/DartVM  (25094):   pc 0xc705383e fp 0xc82640f8 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x123c83e
E/DartVM  (25094):   pc 0xc704d0d3 fp 0xc8264118 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x12360d3
E/DartVM  (25094):   pc 0xc704cc03 fp 0xc8264138 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1235c03
E/DartVM  (25094):   pc 0xc7050ce0 fp 0xc8264178 /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so+0x1239ce0
E/DartVM  (25094):   pc 0xf6c69785 fp 0xc8264198 /apex/com.android.runtime/lib/bionic/libc.so+0xe6785
E/DartVM  (25094):   pc 0xf6bfb458 fp 0xc82641c8 /apex/com.android.runtime/lib/bionic/libc.so+0x78458
E/DartVM  (25094): -- End of DumpStackTrace
E/DartVM  (25094): [exit     : sp(0) fp(0xc8263494) pc(0)]
E/DartVM  (25094): [stub     : sp(0xc826349c) fp(0xc82634a8) pc(0xc4b01bf7)]
E/DartVM  (25094): [dart     : sp(0xc82634b0) fp(0xc82634c0) pc(0xab8ac7a8) package:senio_assist/page/orders/orders.store.dart__OrdersStore@63113582_onDaySelected ]
E/DartVM  (25094): [dart     : sp(0xc82634c8) fp(0xc82634f4) pc(0xab8ac5a8) package:senio_assist/page/orders/orders.store.dart_OrdersStore_onDaySelected ]
E/DartVM  (25094): [dart     : sp(0xc82634fc) fp(0xc8263514) pc(0xac7fc61e) package:senio_assist/page/orders/orders.store.dart_OrdersStore_onDaySelected_onDaySelected ]
E/DartVM  (25094): [dart     : sp(0xc826351c) fp(0xc8263544) pc(0xc3808207) dart:core__Closure@0150898_dyn_call ]
E/DartVM  (25094): [dart     : sp(0xc826354c) fp(0xc8263570) pc(0xac7fbbdc) package:table_calendar/src/table_calendar.dart__TableCalendarState@532116939__onDayTapped@532116939 ]
E/DartVM  (25094): [dart     : sp(0xc8263578) fp(0xc826358c) pc(0xac7fb433) package:table_calendar/src/table_calendar.dart__TableCalendarState@532116939_build_<anonymous closure>_<anonymous closure> ]
E/DartVM  (25094): [dart     : sp(0xc8263594) fp(0xc82635dc) pc(0xb28f3d55) *dart:core__Closure@0150898_dyn_call ]
E/DartVM  (25094): [dart     : sp(0xc82635e4) fp(0xc8263634) pc(0xab8f306b) package:flutter/src/gestures/recognizer.dart_GestureRecognizer_invokeCallback ]
E/DartVM  (25094): [dart     : sp(0xc826363c) fp(0xc8263674) pc(0xab8ffc00) package:flutter/src/gestures/tap.dart_TapGestureRecognizer_handleTapUp ]
E/DartVM  (25094): [dart     : sp(0xc826367c) fp(0xc8263698) pc(0xab8fb83a) package:flutter/src/gestures/tap.dart_BaseTapGestureRecognizer__checkUp@1526069716 ]
E/DartVM  (25094): [dart     : sp(0xc82636a0) fp(0xc82636b0) pc(0xab8fe64e) package:flutter/src/gestures/tap.dart_BaseTapGestureRecognizer_acceptGesture ]
E/DartVM  (25094): [dart     : sp(0xc82636b8) fp(0xc82636d4) pc(0xab8fe0a7) package:flutter/src/gestures/arena.dart_GestureArenaManager_sweep ]

E/DartVM  (25094): [dart     : sp(0xc82636dc) fp(0xc82636f0) pc(0xab8f46ed) package:flutter/src/widgets/binding.dart__WidgetsFlutterBinding&BindingBase&GestureBinding@872399801_handleEvent ]
E/DartVM  (25094): [dart     : sp(0xc82636f8) fp(0xc826372c) pc(0xab8e6922) package:flutter/src/widgets/binding.dart__WidgetsFlutterBinding&BindingBase&GestureBinding@872399801_dispatchEvent ]
E/DartVM  (25094): [dart     : sp(0xc8263734) fp(0xc8263750) pc(0xab8d3cbe) package:flutter/src/widgets/binding.dart__WidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding@872399801_dispatchEvent ]
E/DartVM  (25094): [dart     : sp(0xc8263758) fp(0xc8263774) pc(0xab8d3631) package:flutter/src/widgets/binding.dart__WidgetsFlutterBinding&BindingBase&GestureBinding@872399801__handlePointerEventImmediately@1506304576 ]
E/DartVM  (25094): [dart     : sp(0xc826377c) fp(0xc8263790) pc(0xab8d1c47) package:flutter/src/widgets/binding.dart__WidgetsFlutterBinding&BindingBase&GestureBinding@872399801_handlePointerEvent ]
E/DartVM  (25094): [dart     : sp(0xc8263798) fp(0xc82637ac) pc(0xbbd5f5de) package:flutter/src/widgets/binding.dart__WidgetsFlutterBinding&BindingBase&GestureBinding@872399801__flushPointerEventQueue@1506304576 ]
E/DartVM  (25094): [dart     : sp(0xc82637b4) fp(0xc82637c4) pc(0xab8c7430) package:flutter/src/widgets/binding.dart__WidgetsFlutterBinding&BindingBase&GestureBinding@872399801__handlePointerDataPacket@1506304576 ]
E/DartVM  (25094): [dart     : sp(0xc82637cc) fp(0xc82637e0) pc(0xab8c72d3) package:flutter/src/widgets/binding.dart__WidgetsFlutterBinding&BindingBase&GestureBinding@872399801__handlePointerDataPacket@1506304576__handlePointerDataPacket@1506304576 ]
E/DartVM  (25094): [dart     : sp(0xc82637e8) fp(0xc8263818) pc(0xc387f966) dart:async_::__rootRunUnary@4048458 ]
E/DartVM  (25094): [dart     : sp(0xc8263820) fp(0xc8263848) pc(0xc387f73f) dart:async_::__rootRunUnary@4048458__rootRunUnary@4048458 ]
E/DartVM  (25094): [dart     : sp(0xc8263850) fp(0xc8263894) pc(0xc387f4a1) dart:async__CustomZone@4048458_runUnary ]
E/DartVM  (25094): [dart     : sp(0xc826389c) fp(0xc82638d4) pc(0xbc6ae22f) dart:async__CustomZone@4048458_runUnaryGuarded ]
E/DartVM  (25094): [dart     : sp(0xc82638dc) fp(0xc82638fc) pc(0xb9ebb826) dart:ui_::__invoke1@15065589 ]
E/DartVM  (25094): [dart     : sp(0xc8263904) fp(0xc8263920) pc(0xab8c3905) dart:ui_PlatformDispatcher__dispatchPointerDataPacket@15065589 ]
E/DartVM  (25094): [dart     : sp(0xc8263928) fp(0xc8263938) pc(0xab8c37e6) dart:ui_::__dispatchPointerDataPacket@15065589 ]
E/DartVM  (25094): [entry    : sp(0xc8263940) fp(0xc8263964) pc(0xc4b015a1)]
F/libc    (25094): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 25153 (1.ui), pid 25094 (om.my-app)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RPB2.200611.012/6677315:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2021-05-04 12:58:35+0200
pid: 25094, tid: 25153, name: 1.ui  >>> com.my-app <<<
uid: 10156

signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    eax 00000000  ebx 00006206  ecx 00006241  edx 00000006
    edi f6c4f62e  esi c8262be0
    ebp f77fab90  esp c8262b88  eip f77fab99
backtrace:
      #00 pc 00000b99  [vdso] (__kernel_vsyscall+9)
      #01 pc 0005ac58  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: 9d4c70ab2a4872e2a5bacc33c5de7c4f)
      #02 pc 00076401  /apex/com.android.runtime/lib/bionic/libc.so (abort+209) (BuildId: 9d4c70ab2a4872e2a5bacc33c5de7c4f)
      #03 pc 016f84a3  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #04 pc 01801cfc  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #05 pc 018825fd  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #06 pc 01879659  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #07 pc 01879c9a  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #08 pc 0176f4f9  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #09 pc 0179ab0b  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #10 pc 0179af2e  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #11 pc 01aa2647  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #12 pc 01774a95  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #13 pc 01750fc3  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #14 pc 01759f27  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #15 pc 0186e876  /data/app/~~oBQACT5NJQV70rogNij-bw==/com.my-app-QXzB103Dk8XXkw30Upf9qg==/lib/x86/libflutter.so (BuildId: 93417d7b4afefcab64ceb95b429a4db8539e442f)
      #16 pc 000012ab  <anonymous:c4b00000>
Lost connection to device.
```

</details>

**Comment by TahaTesser** [comment] 2021-05-04 14:01
Hi @vytautas-pranskunas- 
This bug is fixed, a duplicate of https://github.com/flutter/flutter/issues/80733 https://github.com/flutter/flutter/issues/77728

**Closed by TahaTesser** 2021-05-04 14:01 UTC

**Comment by vytautas-pranskunas-** [comment] 2021-05-04 14:03
perfect - when it is going to be released?

**Comment by boernard** [comment] 2021-05-07 07:12
@vytautas-pranskunas- there is a workaround for the time being:
https://github.com/flutter/flutter/issues/77728#issuecomment-804305523
and specifically if you use VSCode: https://github.com/flutter/flutter/issues/80733#issuecomment-823088387

**Comment by vytautas-pranskunas-** [comment] 2021-05-07 07:26
Thanks I have found it
