### ISSUE TITLE
ExpansionTile collapsed color properties not taking effect after rebuild

### ISSUE THREAD

**Issue by KGMIT** [flutter/flutter#133973] opened 2023-09-04 09:26 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Open ExpansionTile of product item (for my example: Alpha)
2. Tap batch item to add to selectedProductBatchMap (for my example: 1111)
3. Observe print statement after state change and rebuild was called and note that the color printed is blue and not null
4. Close ExpansionTile of selected product item (for my example: Alpha)
5. Observe the color of collapsed ExpansionTile not changing to blue

### Expected results

After the state change and rebuild, I expect the collapsed colors (background, icon, and text) of the ExpansionTile to change according to the specified colors in the ternary expressions. In my example: blue for background and white for text and icon colors.

### Actual results

The color does not change even after an item is selected and the print statement during rebuild process shows that the color should be changed.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> productsList = ["Alpha", "Beta", "Gamma"];
  List<String> batchNumbersList = ["1111", "2222", "3333"];
  Map<String, String> selectedProductBatchMap = {};

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: ListView.builder(
        itemCount: productsList.length,
        itemBuilder: (context, index) {
          final product = productsList[index];
          final productSelected = selectedProductBatchMap.containsKey(product);
          if (productSelected) {
            print("REBUILDING AND PRODUCT $product IS SELECTED");
            print(
                "SHOWN COLOR FOR WHEN MENU IS COLLAPSED SHOULD BE: ${productSelected ? Colors.blue : null}");
          }
          return ExpansionTile(
            title: Text(product),
            collapsedBackgroundColor: productSelected ? Colors.blue : null,
            collapsedIconColor: productSelected ? Colors.white : null,
            collapsedTextColor: productSelected ? Colors.white : null,
            children: batchNumbersList
                .map(
                  (batch) => ListTile(
                    title: Text(batch),
                    onTap: () {
                      selectedProductBatchMap[product] = batch;
                      setState(() {});
                    },
                    onLongPress: () {
                      selectedProductBatchMap.remove(product);
                      setState(() {});
                    },
                  ),
                )
                .toList(),
          );
        },
      ),
    );
  }
}
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/flutter/flutter/assets/16708471/34fcc12a-b641-47b7-a5cb-a23f735bf61b

</details>

### Logs

Logs produced using print statements from above video.

<details><summary>Logs</summary>

```console
I/flutter (26947): REBUILDING AND PRODUCT Alpha IS SELECTED
I/flutter (26947): SHOWN COLOR FOR WHEN MENU IS COLLAPSED SHOULD BE: MaterialColor(primary value: Color(0xff2196f3))
I/flutter (26947): REBUILDING AND PRODUCT Alpha IS SELECTED
I/flutter (26947): SHOWN COLOR FOR WHEN MENU IS COLLAPSED SHOULD BE: MaterialColor(primary value: Color(0xff2196f3))
I/flutter (26947): REBUILDING AND PRODUCT Alpha IS SELECTED
I/flutter (26947): SHOWN COLOR FOR WHEN MENU IS COLLAPSED SHOULD BE: MaterialColor(primary value: Color(0xff2196f3))
```

</details>

### Flutter Doctor output

Please note that I am using Android emulation and developing for Android, so I don't think XCode issue from doctor should be the cause.

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
    • Flutter version 3.13.0 on channel stable at /Users/kostas/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (3 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/kostas/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    ✗ Flutter requires Xcode 14 or higher.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Android SDK built for arm64 (mobile) • emulator-5554 • android-arm64  • Android 10 (API 29) (emulator)
    • macOS (desktop)                      • macos         • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)                         • chrome        • web-javascript • Google Chrome 116.0.5845.140

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by KGMIT** [comment] 2023-09-06 07:09
Hi @dam-ease, any estimate as to when this might be fixed?

**Comment by TahaTesser** [comment] 2023-09-07 08:33
This is a wider issue with all color properties in `ExpansionTile` including background and icon color
Closing as duplicate of https://github.com/flutter/flutter/issues/24493

**Closed by TahaTesser** 2023-09-07 08:33 UTC
Labels: framework, f: material design, has reproducible steps, P2, team-design, triaged-design, found in release: 3.13, found in release: 3.14
