### ISSUE TITLE
Building project fails on generating snapshot with segmentation fault after upgrading to 2.0.1

### ISSUE THREAD

**Issue by taktem** [flutter/flutter#79949] opened 2021-04-07 14:24 UTC
So we've upgraded our flutter SDK to 2.0.1 a couple of days ago.
However, we can not build app since will always fail on generating AOT snapshot. 

Seems like something went wrong during snapshot generating, and I can not submit a new release because of this issue by now.
In addition, We have confirmed that running app via `flutter run` works fine on both device and simulator.
Is there anyone having the same issue? Would be grateful if there is any advice or workaround.

Here is the output:
## Logs

<details>
The project information is shown, and I've extracted and pasted the parts around the crash log.
If there is not enough information, I will add it.

```
$ flutter build ios --no-codesign lib/main_dev.dart --verbose
...
[  +77 ms] executing: [/.../frameworks/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] executing: [/.../frameworks/flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[  +24 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] 2.0.1
[  +44 ms] executing: [/.../frameworks/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/.../frameworks/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:flutter/flutter.git
[  +43 ms] executing: [/.../frameworks/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +42 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +49 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +85 ms] Initializing file store
[  +14 ms] Done initializing file store
[+2598 ms] Skipping target: release_unpack_ios
[   +2 ms] Skipping target: gen_localizations
[+1040 ms] Skipping target: kernel_snapshot
[   +5 ms] aot_assembly_release: Starting due to {}
[   +9 ms] executing: /Users/.../frameworks/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64 --deterministic --snapshot_kind=app-aot-assembly
--assembly=/Users/.../.dart_tool/flutter_build/ea93de50feca09de18a7b247fe8368df/arm64/snapshot_assembly.S --strip
/Users/.../.dart_tool/flutter_build/ea93de50feca09de18a7b247fe8368df/app.dill
[+2084 ms] ===== CRASH =====
[   +2 ms] si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x10
[  +11 ms] Dart snapshot generator failed with exit code -6
[   +7 ms] Persisting file store
[  +17 ms] Done persisting file store
[  +12 ms] Target aot_assembly_release failed: Exception: AOT snapshotter exited with code -6
        #0      AotAssemblyBase.build (package:flutter_tools/src/build_system/targets/ios.dart:112:7)
        <asynchronous suspension>
        #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:9)
        <asynchronous suspension>
        #2      Future.wait.<anonymous closure> (dart:async/future.dart)
        <asynchronous suspension>
        #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
        <asynchronous suspension>
        #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
        <asynchronous suspension>
        #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
        <asynchronous suspension>
        #6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
        <asynchronous suspension>
        #7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
        <asynchronous suspension>
        #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
        <asynchronous suspension>
        #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
        <asynchronous suspension>
        #10     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
        <asynchronous suspension>
        #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
        <asynchronous suspension>
        #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
        <asynchronous suspension>
        #13     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
        <asynchronous suspension>
        #14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
        <asynchronous suspension>
        #15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
        <asynchronous suspension>
        #16     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
        <asynchronous suspension>
        #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
        <asynchronous suspension>
        #18     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
        <asynchronous suspension>
        #19     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
        <asynchronous suspension>
        #20     main (package:flutter_tools/executable.dart:90:3)
        <asynchronous suspension>

[  +14 ms] "flutter assemble" took 5,450ms.
[   +5 ms] 
        #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
        #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:237:7)
        <asynchronous suspension>
        #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
        <asynchronous suspension>
        #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
        <asynchronous suspension>
        #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
        <asynchronous suspension>
        #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
        <asynchronous suspension>
        #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
        <asynchronous suspension>
        #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
        <asynchronous suspension>
        #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
        <asynchronous suspension>
        #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
        <asynchronous suspension>
        #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
        <asynchronous suspension>
        #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
        <asynchronous suspension>
        #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
        <asynchronous suspension>
        #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
        <asynchronous suspension>
        #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
        <asynchronous suspension>
        #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
        <asynchronous suspension>
        #16     main (package:flutter_tools/executable.dart:90:3)
        <asynchronous suspension>


[   +1 ms] ensureAnalyticsSent: 0ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[   +1 ms] exiting with code 1
Command PhaseScriptExecution failed with a nonzero exit code


** BUILD FAILED **


The following build commands failed:
PhaseScriptExecution Run\ Script /Users/.../Library/Developer/Xcode/DerivedData/Runner-cklsrhlocuddlpayurcetuzhsake/Build/Intermediates.noindex/Runner.build/Release-iphoneos/Runner.build/Script-9740EEB61CF901F6004384FC.sh
(1 failure)
[[1m +271 ms[22m] Running Xcode build... (completed in 14.6s)
[   +1 ms] [1mXcode build done.                                           14.6s[22m
[   +2 ms] executing: [/Users/.../ios/] xcrun xcodebuild -configuration Release VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/.../build/ios -sdk iphoneos
SCRIPT_OUTPUT_STREAM_FILE=/var/folders/bg/5_k64h_x5bd0180gjv3xv_zjdwn_8r/T/flutter_tools.zAYhkZ/flutter_build_log_pipe.agRla4/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
[   +1 ms] executing: [/Users/.../ios/] xcrun xcodebuild -configuration Release VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/.../build/ios -sdk iphoneos
SCRIPT_OUTPUT_STREAM_FILE=/var/folders/bg/5_k64h_x5bd0180gjv3xv_zjdwn_8r/T/flutter_tools.zAYhkZ/flutter_build_log_pipe.agRla4/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
[[1m+2958 ms[22m] Command line invocation:
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -configuration Release VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/.../build/ios -sdk iphoneos
SCRIPT_OUTPUT_STREAM_FILE=/var/folders/bg/5_k64h_x5bd0180gjv3xv_zjdwn_8r/T/flutter_tools.zAYhkZ/flutter_build_log_pipe.agRla4/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.1 20D74 darwin-x64, locale ja)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>

**Comment by mraleph** [comment] 2021-04-08 08:16
@taktem after the crash please try rerunning `/Users/.../frameworks/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64 --deterministic --snapshot_kind=app-aot-assembly
--assembly=/Users/.../.dart_tool/flutter_build/ea93de50feca09de18a7b247fe8368df/arm64/snapshot_assembly.S --strip
/Users/.../.dart_tool/flutter_build/ea93de50feca09de18a7b247fe8368df/app.dill` command under `lldb` and post backtrace here.

**Comment by TahaTesser** [comment] 2021-04-08 08:23
Hi @taktem 
Please provide the details asked above. I can't find a similar recent issue to mention.

**Comment by taktem** [comment] 2021-04-10 12:23
@mraleph @TahaTesser 

Thank you for your reply.
I tried to call the command you specified.

Here is the output:

```
lldb /Users/.../bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64 -- --deterministic --snapshot_kind=app-aot-assembly --assembly=/Users/.../.dart_tool/flutter_build/20b0b74a1553256107dac5a35f6d63bd/arm64/snapshot_assembly.S --strip /Users/.../.dart_tool/flutter_build/20b0b74a1553256107dac5a35f6d63bd/app.dill
(lldb) target create "/Users/.../bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64"
Current executable set to '/Users/.../bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64' (x86_64).
(lldb) settings set -- target.run-args  "--deterministic" "--snapshot_kind=app-aot-assembly" "--assembly=/Users/.../.dart_tool/flutter_build/20b0b74a1553256107dac5a35f6d63bd/arm64/snapshot_assembly.S" "--strip" "/Users/.../.dart_tool/flutter_build/20b0b74a1553256107dac5a35f6d63bd/app.dill"
(lldb)
(lldb) run
Process 82974 launched: '/Users/.../bin/cache/artifacts/engine/ios-release/gen_snapshot_arm64' (x86_64)
Process 82974 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x00000001002232b7 gen_snapshot_arm64`dart::LocalScope::AllocateVariables(dart::VariableIndex, int, dart::VariableIndex, dart::LocalScope*, bool*) + 135
gen_snapshot_arm64`dart::LocalScope::AllocateVariables:
->  0x1002232b7 <+135>: cmpq   %r12, 0x10(%r14)
    0x1002232bb <+139>: jne    0x1002232a0               ; <+112>
    0x1002232bd <+141>: cmpb   $0x0, 0x39(%r14)
    0x1002232c2 <+146>: je     0x1002232a0               ; <+112>
Target 0: (gen_snapshot_arm64) stopped.
```

If there is anything else I should check, please let me know.

**Comment by mraleph** [comment] 2021-04-10 16:57
> If there is anything else I should check, please let me know.

Can you run almost the same command but add `--trace-compiler` to list of `gen_snapshot_arm64` flags (e.g. right after `--deterministic`). `--trace-compiler` would make it clear where exactly in the code base it crashes. 

After it crashes can you type `bt` command into LLDB to print the backtrace? 

I think it might be duplicate of dart-lang/sdk#45306 but we need to confirm for sure, most specifically we are looking if it crashes compiling `late final xyz` initializer which contains a closure inside (e.g. `late final xyz = foo(() { ... });`)

**Comment by taktem** [comment] 2021-04-13 13:20
@mraleph  @TahaTesser 

I tried run with added `--trace-compiler`.
Here is output.

```
Precompiling optimized function: 'package:flutter_with_bloc/src/resources/logged_in_info/logged_in_info_bloc.dart_LoggedInInfo_LoggedInInfo.' @ token 4283, size 962
Process 22487 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x00000001002232b7 gen_snapshot_arm64`dart::LocalScope::AllocateVariables(dart::VariableIndex, int, dart::VariableIndex, dart::LocalScope*, bool*) + 135
gen_snapshot_arm64`dart::LocalScope::AllocateVariables:
->  0x1002232b7 <+135>: cmpq   %r12, 0x10(%r14)
    0x1002232bb <+139>: jne    0x1002232a0               ; <+112>
    0x1002232bd <+141>: cmpb   $0x0, 0x39(%r14)
    0x1002232c2 <+146>: je     0x1002232a0               ; <+112>
Target 0: (gen_snapshot_arm64) stopped.
```

I checked the `logged_in_info_bloc.dart` and found the following code.

```
final _sample = SampleClass(
    completionAction: (Xxx action) async {
    return await Future<void>.sync(() {
        final completer = Completer<void>();
        SingletonClass().someFunc(completed: () {
            completer.complete();
        });
        return completer.future;
    });
});
```

Upon closer inspection, I realized that this async is unnecessary.
So I changed the code like this, and the build succeeded without any problems.

```
final _sample = SampleClass(
    completionAction: (Xxx action) {
    return Future<void>.sync(() {
        final completer = Completer<void>();
        SingletonClass().someFunc(completed: () {
            completer.complete();
        });
        return completer.future;
    });
});
```

Also, when I clone and build the master branch, the build was also successful with the code before the modification.

Thank you for your response.
My problem has been solved.

**Comment by mraleph** [comment] 2021-04-13 13:33
Thanks! Based on the information it is indeed the same problem as dart-lang/sdk#45306

**Closed by mraleph** 2021-04-13 13:33 UTC
Labels: in triage, waiting for customer response

**Comment by TahaTesser** [comment] 2021-04-13 13:54
@mraleph 
Thanks so much for analyzing this for dart
