### ISSUE TITLE
Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:  - TextInputClient.didChangeInputControl  - TextInputClient.performSelector Try to either  - provide an implementation,  - inherit an implementation from a superclass or mixin,  - mark the class as abstract, or  - provide a 'noSuchMethod' implementation.  class ChipsInputState<T> extends State<ChipsInput<T>>       ^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by mazab99** [flutter/flutter#119460] opened 2023-01-29 16:11 UTC
Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
 - TextInputClient.didChangeInputControl
 - TextInputClient.performSelector
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ChipsInputState<T> extends State<ChipsInput<T>>
      ^^^^^^^^^^^^^^^

**Comment by huycozy** [comment] 2023-01-30 09:43
@mazab99 
Are you using a 3rd package? If not so, can you share a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this? Also, please provide the output of `flutter doctor -v` as well.

**Comment by mazab99** [comment] 2023-01-30 09:49
@huycozy 

package flutter_chips_input Not compatible with flutter 3.7 , and I use map_location_picker which use this package 

so the solution is to add this in my pubspec.yaml 

dependency_overrides:
  flutter_chips_input:
    git: https://github.com/bradintheusa/flutter_chips_input

I forced to add this

**Comment by huycozy** [comment] 2023-01-30 09:57
@mazab99 
The issue is related to a 3rd party plugin/package rather than to Flutter framework itself. Please open the issue in the dedicated [repository](https://github.com/danvick/flutter_chips_input/issues) or follow the [filed issue](https://github.com/danvick/flutter_chips_input/issues/136) on that repository that I have seen your comment there.

Closing, as this isn't an issue with Flutter itself.

**Closed by huycozy** 2023-01-30 09:57 UTC
Labels: in triage
