### ISSUE TITLE
Example code is a dead link

### ISSUE THREAD

**Issue by sandwichstealer** [flutter/flutter#78693] opened 2021-03-20 15:05 UTC
Located at:

https://firebaseopensource.com/projects/flutter/plugins/packages/firebase_auth/readme/

**Comment by iapicca** [comment] 2021-03-20 15:15
@sandwichstealer 
[firebase](https://firebase.flutter.dev/) is a 3rd party plugin, please open an issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues)

**Comment by pedromassangocode** [comment] 2021-03-22 09:41
Hi @sandwichstealer 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-03-22 09:41 UTC
Labels: in triage
