### ISSUE TITLE
Focus TextField freezes Linux App

### ISSUE THREAD

**Issue by konsultaner** [flutter/flutter#155016] opened 2024-09-11 12:50 UTC
### Steps to reproduce

Open reproducer on linux

```
flutter pub get
flutter run linux
```
klick on "klick me" and select textfield in dialog.

### Expected results

Shouldn't freeze

### Actual results

Freezes the app

### Code sample

[reproducer.zip](https://github.com/user-attachments/files/16963839/reproducer.zip)

### Screenshots or Video

This is where the error happens:

![image](https://github.com/user-attachments/assets/7ec27961-f1c5-4ccb-aa7a-c91a3e35621f)

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.2, on Linux Mint 21.2 5.15.0-76-generic, locale de_DE.UTF-8)
    • Flutter version 3.24.2 on channel stable at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cf269e36d (vor 8 Tagen), 2024-09-03 14:30:00 -0700
    • Engine revision a6bd3f1de1
    • Dart version 3.5.2
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/richi/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /home/richi/.local/share/JetBrains/Toolbox/apps/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 14.0.0-1ubuntu1.1
    • cmake version 3.22.1
    • ninja version 1.10.1
    • pkg-config version 0.29.2

[✓] Android Studio (version 2024.1)
    • Android Studio at /home/richi/.local/share/JetBrains/Toolbox/apps/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at /home/richi/.local/share/JetBrains/Toolbox/apps/intellij-idea-ultimate
    • Flutter plugin version 81.1.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux Mint 21.2 5.15.0-76-generic
    • Chrome (web)    • chrome • web-javascript • Chromium 128.0.6613.119 for Linux Mint

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by danagbemava-nc** [comment] 2024-09-11 13:13
Closing this as a duplicate of https://github.com/flutter/flutter/issues/153560

**Closed by danagbemava-nc** 2024-09-11 13:13 UTC
Labels: in triage
