### ISSUE TITLE
Material Icon barcode_scanner,barcode are missing 

### ISSUE THREAD

**Issue by vavachi** [flutter/flutter#141935] opened 2024-01-20 14:28 UTC
### Use case

I cant find the icons barcode_scanner,barcode in flutter icon library

### Proposal

Add missing material icons

**Comment by danagbemava-nc** [comment] 2024-01-22 08:12
Those icons are material symbols, not material icons. 

Material symbols are not yet supported in flutter. See https://github.com/flutter/flutter/issues/102560

Closing this as a duplicate of the issue linked above. 

Thank you

**Closed by danagbemava-nc** 2024-01-22 08:12 UTC
Labels: in triage
