### ISSUE TITLE
Service worker is not caching assets when base-href is different than "/"

### ISSUE THREAD

**Issue by davidlanderos-digital** [flutter/flutter#115250] opened 2022-11-14 01:07 UTC
## Steps to Reproduce

- create new project: `flutter create demo`
- build it for web using a custom base-href: `flutter build web --base-href /basehreftest/`
- put the build inside /basehreftest/ and start an http server (one folder up) `python -m http.server`
- note how all assets are always redownloaded 💣(sadly this has a big performance impact for my use-case)

**Evidence of service worker not caching assets (such as icons/Icon-192.png)**

https://user-images.githubusercontent.com/79719460/201554426-2db03ccc-2a49-4e21-bdc9-629274e61c70.mp4

**Expected results:** 
Service worker must cache assets, (in the developer console you must see "service-worker" on assets requests)

**Actual results:** 
It always reaches the remote server (may affect loading times, it actually happens in my use-case)

```
[!] Flutter (Channel master, 3.6.0-2.0.pre.14, on Microsoft Windows [Version 10.0.22000.1219], locale en-US)
    • Flutter version 3.6.0-2.0.pre.14 on channel master at E:\developer\flutter_contribution\flutter
    ! Upstream repository https://github.com/davidlanderos-digital/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to https://github.com/davidlanderos-digital/flutter.git to dismiss this
      error.
    • Framework revision f92ff3e06f (26 minutes ago), 2022-11-13 18:39:57 -0600
    • Engine revision b63e6cf558
    • Dart version 2.19.0 (build 2.19.0-394.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\david\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_SDK_ROOT = C:\Users\david\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\david\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1219]
    • Chrome (web)      • chrome  • web-javascript • unknown
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 106.0.1370.52

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

</details>

**Comment by davidlanderos-digital** [comment] 2022-11-14 04:28
I updated web_test.dart to expect the full path in the assets cache manifest, my solution is working perfectly for me, I hope it's useful for anyone facing the same issue..

**Comment by danagbemava-nc** [comment] 2022-11-14 11:18
Hi @davidlanderos-digital, I believe this is a duplicate of https://github.com/flutter/flutter/issues/111866. 

Kindly follow up in the issue linked above for updates. 

Closing from here as duplicate. 

If you disagree, kindly leave a comment below and I will reopen this issue. 

Thank you

**Closed by danagbemava-nc** 2022-11-14 11:18 UTC
Labels: in triage

**Comment by davidlanderos-digital** [comment] 2022-11-14 15:18
ah! thanks for pointing it out,  I updated my PR description
