### ISSUE TITLE
Linux_android list_text_layout_impeller_perf__e2e_summary is failing

### ISSUE THREAD

**Issue by drewroengoogle** [flutter/flutter#113454] opened 2022-10-14 18:19 UTC
https://ci.chromium.org/p/flutter/builders/prod/Linux_android%20list_text_layout_impeller_perf__e2e_summary/1728

An engine commit seems to have caused this, it may need to be reverted

**Comment by drewroengoogle** [comment] 2022-10-14 19:25
I think the failing test is a result of an engine commit that updates clang in the engine - https://github.com/flutter/engine/commit/3711bbaeabb75b69eedd87121b52c80af3ccd8d7

I'm going to contact the Fuchsia toolchain team and see if they know of any recent changes could have caused this, unless there is a better method of solving this issue?

**Comment by drewroengoogle** [comment] 2022-10-14 20:09
https://github.com/flutter/engine/pull/36763 to ensure that the Clang commit is the issue. This won't fix it long term if an additional clang commit is merged

**Comment by drewroengoogle** [comment] 2022-10-14 21:16
Waiting for an autoroll commit that is either this (commit)[https://github.com/flutter/engine/commit/c1f7336db76221488221928fa056015d163132bc] or later in order to fix the tree.

**Comment by drewroengoogle** [comment] 2022-10-14 21:37
https://autoroll.skia.org/r/clang-flutter-engine has been stopped for now. Will be filing a bug

**Comment by jmagman** [comment] 2022-10-14 22:25
@drewroengoogle's manual engine roll is at https://github.com/flutter/flutter/pull/113463

**Comment by jmagman** [comment] 2022-10-15 00:34
Test are passing on the clang roll revert.

cc @bdero engine sheriff

**Comment by bdero** [comment] 2022-10-15 01:24
Was this issue bisected to the clang roll specifically? Is it possible that this issue happened to be fixed by another commit that was roped in during the roll?

cc @dnfield who might have more context for the unique behavior of this benchmark.

**Comment by drewroengoogle** [comment] 2022-10-15 04:23
> Was this issue bisected to the clang roll specifically? Is it possible that this issue happened to be fixed by another commit that was roped in during the manual engine roll?
> 
> cc @dnfield who might have more context for the unique behavior of this benchmark.

In hindsight that's a good point, as the [commit that the tree broke](https://github.com/flutter/flutter/pull/113410) included a couple of rolls and a change from Dan, and any of them could be the culprit. Do you think we should try updating clang and see if the benchmark stays green?

**Comment by bdero** [comment] 2022-10-17 17:55
It's peculiar that a Clang issue would bubble up into Dart runtime errors. And for just this benchmark.
I'm attempting to repro the benchmark failure locally at the moment to verify whether stopping the Clang roll actually fixes it.

**Comment by zanderso** [comment] 2022-10-17 18:12
Adding back P0 since this is blocking the autoroller.

**Comment by bdero** [comment] 2022-10-17 21:18
@jason-simmons tried the latest clang sdk revision b0bf7ffffc3a2a65a22da4afb13feb855baf2042 and confirmed that the benchmark successfully completed. Unpausing the clang roller.

**Comment by bdero** [comment] 2022-10-17 23:24
Had to pause the roller again because the integration label was still on the known broken version.

The integration label has since been updated to a93d03310e2c02fa5e24544df4706650f85788f7, which I successfully tested against the benchmark. So unpausing the clang roller again.

**Comment by bdero** [comment] 2022-10-18 18:37
The new version rolled into the framework last night. Looks like we're in the clear now! https://github.com/flutter/flutter/pull/113586

**Closed by bdero** 2022-10-18 18:37 UTC
Labels: team: infra, P0
