### ISSUE TITLE
Error waiting for a debug connection: The log reader stopped unexpectedly

### ISSUE THREAD

**Issue by eziocodes** [flutter/flutter#127558] opened 2023-05-25 06:49 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Run the application using `flutter run`
2. I am trying this on a real device: Vivo V25 pro
3. After the commands executes, I am getting this error on console:  Error waiting for a debug connection: The log reader stopped unexpectedly [But the application executes properly on the mobile device without any problem]

### Expected results

The app should launch on my mobile device, the console should be able to execute Hot Reload or Hot Refresh commands.

### Actual results

For the very first time after system restart, the console process work properly but the console is `unresponsive`. I cannot execute any hot commands like `Hot Reload using r`, `Hot Restart using Shift + r` or `p`, etc.

From next time onwards (once I close the console), I am getting this error on console every time till I again restart my system:  Error waiting for a debug connection: The log reader stopped unexpectedly `[But the application executes properly on the mobile device without any problem and there is no build error as well]`.

This is happening with a new `sample flutter counter project` as well.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
$ flutter run
Launching lib\main.dart on V2158 in debug mode...
Running Gradle task 'assembleDebug'...                              3.8s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Error waiting for a debug connection: The log reader stopped unexpectedly
Error launching application on V2158.
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
$ flutter doctor -v
[√] Flutter (Channel stable, 3.10.1, on Microsoft Windows [Version 10.0.22621.1702], locale en-IN)
    • Flutter version 3.10.1 on channel stable at D:\development\flutter\flutter_sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (8 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\development\android_sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] VS Code, 64-bit edition (version 1.78.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.64.0

[√] Connected device (4 available)
    • V2158 (mobile)    • 192.168.1.234:5555 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.22621.1702]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 113.0.5672.127
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 113.0.1774.50

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by eziocodes** [comment] 2023-05-25 06:51
I am running this in VS Code on a machine running Windows 11.

**Comment by darshankawar** [comment] 2023-05-25 10:02
Closing this as duplicate of https://github.com/flutter/flutter/issues/106086

**Closed by darshankawar** 2023-05-25 10:02 UTC
Labels: in triage
