### ISSUE TITLE
Cupertino icons are misaligned in latest beta

### ISSUE THREAD

**Issue by DanTup** [flutter/flutter#143069] opened 2024-02-07 12:19 UTC
### Steps to reproduce

While updating icons for https://github.com/flutter/tools_metadata, I noticed all of the Cupertino icons showed as modified. The ones I checked all appear to have shifted up slightly.

So I tried rendering an icon in a standard Flutter app with a border:

```dart
child: Container(
            decoration: BoxDecoration(border: Border.all(color: Colors.red)),
            child: const Icon(CupertinoIcons.xmark_shield_fill, size: 50),
          ),
```

And I see the same thing - the icon looks slightly too far up. This seems to have come up before at https://github.com/flutter/flutter/issues/66285 but that was fixed a long time ago and I can't see why it would have changed since. Both examples are using cupertino_icons 1.0.6.

### Expected results

Icon should be centered in the box.

### Actual results

Icon is too far up in the latest beta. In current stable it is centered.

Left: stable
Right: beta

<img width="122" alt="Screenshot 2024-02-07 at 12 08 35" src="https://github.com/flutter/flutter/assets/1078012/904999a9-149e-441b-ae0e-71a4cc62fec8">

Tested on macOS device.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            decoration: BoxDecoration(border: Border.all(color: Colors.red)),
            child: const Icon(CupertinoIcons.xmark_shield_fill, size: 50),
          ),
        ),
      ),
    );
  }
}
```

</details>

### Screenshots or Video

Beta:

<img width="136" alt="Screenshot 2024-02-07 at 12 05 30" src="https://github.com/flutter/flutter/assets/1078012/9531b15e-fb15-4aa9-adb0-52c225daa01b">

Stable / Beta comparison:

<img width="122" alt="Screenshot 2024-02-07 at 12 08 35" src="https://github.com/flutter/flutter/assets/1078012/1895a30c-0ef5-4379-aacf-7ac2cd22bfaf">

<img width="389" alt="Screenshot 2024-02-07 at 11 45 11" src="https://github.com/flutter/flutter/assets/1078012/5fc9f858-6e4e-452b-b670-399d7136d15b">

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[!] Flutter (Channel beta, 3.19.0-0.4.pre, on macOS 13.4 22F66 darwin-x64, locale en-GB)
    ! Warning: `dart` on your path resolves to /Users/danny/Dev/Dart SDKs/stable/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/danny/Dev/Google/flutter. Consider adding /Users/danny/Dev/Google/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    ! CocoaPods 1.12.1 out of date (1.13.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#updating-cocoapods for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.86.0)
[✓] VS Code (version 1.79.0-insider)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by darshankawar** [comment] 2024-02-08 07:31
Thanks for the detailed bug report @DanTup 

This is also occuring on latest master along with beta and I think it similar to https://github.com/flutter/flutter/issues/140140 (but it seem to also occur on stable 3.16.4)

I'll label this issue as a regression since it works only on stable but not on beta and master.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.16.9, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.16.9 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (12 days ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.20.0-4.0.pre.35, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.20.0-4.0.pre.35 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 28904c0cd3 (3 hours ago), 2024-02-07 22:51:25 -0500
    • Engine revision 104804aa37
    • Dart version 3.4.0 (build 3.4.0-116.0.dev)
    • DevTools version 2.32.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

<details>
<summary> beta flutter doctor </summary>

```

[!] Flutter (Channel beta, 3.19.0-0.4.pre, on macOS 12.2.1 21D62 darwin-x64,
    locale en-GB)
    • Flutter version 3.19.0-0.4.pre on channel beta at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b7e7d46a04 (6 days ago), 2024-02-02 08:21:06 -0600
    • Engine revision 98820f0a77
    • Dart version 3.3.0 (build 3.3.0-279.3.beta)
    • DevTools version 2.31.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • 3BD8F2FF-FDB5-4074-8C91-54F99C79156D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     •
      macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript •
      Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!


```

</details>

**Comment by HansMuller** [comment] 2024-02-09 22:30
CC @MitchellGoodwin

**Comment by parlough** [comment] 2024-02-15 15:51
@LongCatIsLooong

I'm trying to determine if it makes sense for IDEs to surface these updated version of the icons. Would you know if this change is expected or not?

**Comment by jason-simmons** [comment] 2024-03-29 21:34
This behavior changed with https://github.com/flutter/flutter/commit/f2b74725c588f6636a2c718909a23620b8b80617

@LongCatIsLooong

**Comment by LongCatIsLooong** [comment] 2024-03-29 22:01
![image](https://github.com/flutter/flutter/assets/31859944/f6506bce-be9f-4d99-9575-dbdee250c55a)

The glyphs don't seem to be vertically centered within the EM box

**Comment by LongCatIsLooong** [comment] 2024-04-04 20:07
The font from this commit seems to be properly center-aligned: https://github.com/flutter/packages/blob/5884f5096e1eddd0f42fd19cc869d0b543fd0822/third_party/packages/cupertino_icons/assets/CupertinoIcons.ttf (I think the package version is `version: 1.0.0-dev.3`) this can be used as a workaround while I work on a fix.

**Comment by LongCatIsLooong** [comment] 2024-04-14 13:20
Duplicate of https://github.com/flutter/flutter/issues/140140.

**Closed by LongCatIsLooong** 2024-04-14 13:20 UTC
Labels: c: regression, framework, f: cupertino, has reproducible steps, P2, r: duplicate, p: cupertino_icons, team-design, triaged-design, found in release: 3.19, found in release: 3.20
