### ISSUE TITLE
Adreno-GSL: <gsl_memory_alloc_pure:2124>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed

### ISSUE THREAD

**Issue by yuchuan08** [flutter/flutter#31599] opened 2019-04-25 07:41 UTC
Flutter version: 1.2.1 channel stable
Dart     version：2.2.0
Android devices：OppoR11  Android7.1.1
When  in  realease mode，app   run   random  crash，I do not  know  the reason，anyone  has  the same  problem？

**Comment by BondarenkoStas** [comment] 2019-10-16 13:43
Duplicate of #35986

**Closed by BondarenkoStas** 2019-10-16 13:43 UTC
