### ISSUE TITLE
Invalid binary issue on Apple appstore connect submission, issue in flutter 2.5

### ISSUE THREAD

**Issue by niteshcongreja321** [flutter/flutter#90348] opened 2021-09-19 15:34 UTC
I make a build for ios, archive it and upload it to AppStore connect through xcode, everything seemed good but after few moments I received an email from apple saying:

```bash
Dear Developer,

We identified one or more issues with a recent delivery for your app, "APP-NAME" 1.0.1 (2). Please correct the following issues, then upload again.

ITMS-90755: Invalid Binary - The following binaries in your app contains prohibited instructions: /Volumes/data01/app_data/awf/SWImportWorker-mr47p00ce-swpr0068.cse.apple.com-300252/ff03-SoftwareImportWorker-MR_.0/NYH74E2GDJSTMWPVXUPB4IZWH4/umuagyjihbsjsrpn/wspvjpsuvltmmknh/Payload/Runner.app/Frameworks/App.framework/App. Remove the instructions from the binaries, rebuild and resubmit.

Best regards,

The App Store Team
```

I tried again with flutter clean and also increased the IOS deployment target but it didn't help.

My device's Flutter info:

<details> 
<summary>flutter doctor -v</summary> 
	
```console
Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-PK) • Flutter version 2.5.0 at /Users/niteshkongreja/Development/flutter • Upstream repository https://github.com/niteshcongreja321/flutter.git • Framework revision 4cc385b4b8 (10 days ago), 2021-09-07 23:01:49 -0700 • Engine revision f0826da7ef • Dart version 2.14.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0) • Android SDK at /Users/niteshkongreja/Library/Android/sdk • Platform android-31, build-tools 31.0.0 • ANDROID_HOME = /Users/niteshkongreja/Library/Android/sdk • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165) • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS • Xcode at /Applications/Xcode.app/Contents/Developer • Xcode 12.5.1, Build version 12E507 • CocoaPods version 1.10.1

[✓] Chrome - develop for the web • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1) • VS Code at /Applications/Visual Studio Code.app/Contents • Flutter extension version 3.26.0

[✓] Connected device (2 available) • macOS (desktop) • macos • darwin-x64 • macOS 11.5.2 20G95 darwin-x64 • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.82

• No issues found!
```
	
</details>

**Comment by TahaTesser** [comment] 2021-09-20 11:00
duplicate of https://github.com/flutter/flutter/issues/90209

**Comment by TahaTesser** [comment] 2021-09-20 11:10
HI @niteshcongreja321 
Do you have new capabilities enabled? You need to enable them in the App Store portal as well
Please provide complete steps to reproduce the issue

**Comment by niteshcongreja321** [comment] 2021-09-20 12:57
No i don't have any capabilities enabled.

To reproduce the issue you may make any simple app, and try uploading it to appstore connect.

**Comment by TahaTesser** [comment] 2021-09-20 14:24
Hi @niteshcongreja321 
The error is specific to your app, I don't think it will reproduce any app on the stable channel  Please provide more details of your app and steps to reproduce. 

Also provide complete steps that you're taking to publish your app from start

**Closed** 2021-09-20 14:26 UTC
Labels: waiting for customer response, in triage
