### ISSUE TITLE
GSL MEM ERROR when clipping Image with ClipPath

### ISSUE THREAD

**Issue by lschmierer** [flutter/flutter#10913] opened 2017-06-22 20:26 UTC
An "GSL MEM ERROR" occurs when an `Image` is clipped using `ClipPath` when following conditions are met:

- `Image` is clipped using `ClipPath` (clipping a simple `Container` worked)
- ~the `Path` returned by the `CustomClipper` contains a curve (just clipping some polygon works)~ (other shapes like polygons not working either)
- in this case the combination of `Listener` and `Stack` and `Positioned` to make widgets movable by the user (this probably just reveals the memory leak because of ongoing state changes)

I am testing on an Android phone.
I did not try with iOS.

## Steps to Reproduce

Following source code reproduces the issue.
The app crashes once widgets are being moved.

```Dart
import 'package:flutter/material.dart';

const int IMAGES = 10;

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Stack(
      children: new Iterable.generate(
        IMAGES,
        (_) => new _ClippedImage(),
      ).toList(),
    );
  }
}

class _ClippedImage extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => new _ClippedImageState();
}

class _ClippedImageState extends State<_ClippedImage> {
  Offset _pos;

  @override
  void initState() {
    super.initState();
    _pos = Offset.zero;
  }

  @override
  Widget build(BuildContext context) {
    return new Positioned(
        left: _pos.dx,
        top: _pos.dy,
        child: new Listener(
          onPointerMove: (details) {
            setState(() {
              _pos += details.delta;
            });
          },
          child: new ClipPath(
            clipper: new _MyClipper(),
            child: new Image(image: new AssetImage("image.png")),
          ),
        ));
  }
}

class _MyClipper extends CustomClipper<Path> {
  @override
  Path getClip(Size size) {
    return new Path()
      ..quadraticBezierTo(size.width, 0.0, size.width, size.height)
      ..lineTo(0.0, size.height)
      ..close();
  }

  @override
  bool shouldReclip(_MyClipper oldClipper) => false;
}
```

## Logs

`flutter run` output:
```
Launching lib/main.dart on Pixel in debug mode...
Built build/app/outputs/apk/app-debug.apk (21.6MB).
I/zygote  (14652): Do partial code cache collection, code=31KB, data=27KB
I/zygote  (14652): After code cache collection, code=31KB, data=27KB
I/zygote  (14652): Increasing code cache capacity to 128KB
W/Adreno-GSL(14652): <sharedmem_gpuobj_alloc:2311>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(14652): <gsl_memory_alloc_pure:2190>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(14652): <sharedmem_gpuobj_alloc:2311>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(14652): <gsl_memory_alloc_pure:2190>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
W/Adreno-GSL(14652): <sharedmem_gpuobj_alloc:2311>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
E/Adreno-GSL(14652): <gsl_memory_alloc_pure:2190>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
...
```

`flutter analyze` output:

```
Analyzing /Users/lschmierer/Snuzzle/curve_bug...
No issues found!
Ran in 5.3s
```

## Flutter Doctor

```
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-DE, channel alpha)
    • Flutter at /Users/lschmierer/flutter
    • Framework revision d36e2f6191 (22 hours ago), 2017-06-21 15:09:10 -0700
    • Engine revision b0dee695ec
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/lschmierer/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • ANDROID_HOME = /Users/lschmierer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.2.1, Build version 8C1002
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Pixel • FA69N0312108 • android-arm • Android 8.0.0 (API 26)
```

**Comment by eseidelGoogle** [comment] 2017-06-22 20:29
@chinmaygarde is this Skia or Flutter?

**Comment by chinmaygarde** [comment] 2017-06-22 21:44
I'll have to investigate. @lschmierer can you attach the `image.png` you used to the ticket as well (if possible).

**Comment by lschmierer** [comment] 2017-06-22 21:51
Yes, sure. However the actual image does not matter.

![image](https://user-images.githubusercontent.com/2204708/27457613-b461d68c-57a5-11e7-88a9-2ac5c62f8950.png)

**Comment by jason-simmons** [comment] 2017-06-22 22:03
I can reproduce the leak - it shows up as an increase in the the GL heap in "dumpsys meminfo"

**Comment by jason-simmons** [comment] 2017-06-23 00:10
When a picture layer flows through GrClipStackClip::createAlphaClipMask, we seem to be leaking the clip mask texture into the GrResourceCache's scratch map.

Will need some help from Skia to understand the lifecycle of this resource.

@bsalomon

**Comment by bsalomon** [comment] 2017-06-23 13:38
When Skia is under its budget for GPU resources then we will often keep temporary resources around as scratch resources. This is true for clip masks, blurs, saveLayers, etc. We have recently added an API that may be of use: GrContext::purgeResourcesNotUsedInMs(). You give it a millisecond count and any GPU cached but not currently pinned resource that has not been used since now - ms will be freed. It could be called once per frame, for example.

**Comment by jason-simmons** [comment] 2017-06-23 17:10
The scratch map is growing by 1 object on each call to draw the clipped image.  Is is expected for the scratch map to keep growing with no upper bound?

**Comment by bsalomon** [comment] 2017-06-23 17:11
It will grow until either the resource count or byte limit is hit (as specified by GrResourceCache::setResourceCacheLimits).

**Comment by jason-simmons** [comment] 2017-06-23 17:52
GrContext::purgeResourcesNotUsedInMs didn't help, but it looks like this has been fixed in the Skia tip-of-tree

**Comment by jason-simmons** [comment] 2017-06-26 22:45
The Skia roll with this fix has landed

**Closed by jason-simmons** 2017-06-26 22:45 UTC
Labels: crash, dependency: skia, prod: engine
