### ISSUE TITLE
[tool_crash] ProcessException: Failed to find "C:\Users\User\Documents\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the search path. Command: C:\Users\User\Documents\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 0

### ISSUE THREAD

**Issue by manu777r** [flutter/flutter#145692] opened 2024-03-25 15:36 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: Failed to find "C:\Users\User\Documents\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe" in the search path. Command: C:\Users\User\Documents\flutter\bin\cache\dart-sdk\bin\dartaotruntime.exe, OS error code: 0
```
#0      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:56:7)
#1      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:686:24)
#2      _run (package:flutter_tools/src/base/error_handling_io.dart:556:20)
#3      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:685:12)
#4      DefaultResidentCompiler._compile (package:flutter_tools/src/compile.dart:874:37)
#5      DefaultResidentCompiler._recompile (package:flutter_tools/src/compile.dart:734:14)
#6      _RecompileRequest._run (package:flutter_tools/src/compile.dart:420:16)
#7      _CompilationRequest.run (package:flutter_tools/src/compile.dart:394:30)
#8      DefaultResidentCompiler._handleCompilationRequest (package:flutter_tools/src/compile.dart:780:23)
#9      _rootRunUnary (dart:async/zone.dart:1407:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#14     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#16     _rootRun (dart:async/zone.dart:1391:47)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#20     _rootRun (dart:async/zone.dart:1399:13)
#21     _CustomZone.run (dart:async/zone.dart:1301:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
```
```
[✓] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.22631.3296], locale de-DE)
    • Flutter version 3.19.4 on channel stable at C:\Users\User\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (5 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:/Users/User/AppData/Local/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:/Users/User/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34714.143
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22631.3296]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 123.0.6312.58
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 122.0.2365.92

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 68bfaea224880b488c617afe30ab12091ea8fa4e

**Comment by huycozy** [comment] 2024-03-26 06:14
Closing this as a duplicate of https://github.com/flutter/flutter/issues/143391.

**Closed by huycozy** 2024-03-26 06:14 UTC
Labels: in triage
