### ISSUE TITLE
Syncing files to device failed 

### ISSUE THREAD

**Issue by zongkelong** [flutter/flutter#26685] opened 2019-01-17 04:21 UTC
## Steps to Reproduce

1. create a new  flutter project with android studio
2. run the debug app in a  real device(e.g. huawei phone) with the debug button on top of the studio
3. stop debug & uninstall the flutter app which is installed by your android studio in your phone
4. repeat step 2  and you will find the command get stuck.

![image](https://user-images.githubusercontent.com/4134954/51294936-2ad7c380-1a50-11e9-8715-92258d005e41.png)
## Logs

```
[  +42 ms] Resolving dependencies... (completed)
[   +2 ms] executing: /Users/zongkelong/Library/Android/sdk/build-tools/28.0.3/aapt dump xmltree /Users/zongkelong/flutterProjects/hive_demo/flutter_app/build/app/outputs/apk/app.apk
AndroidManifest.xml
[  +28 ms] Exit code 0 from: /Users/zongkelong/Library/Android/sdk/build-tools/28.0.3/aapt dump xmltree
/Users/zongkelong/flutterProjects/hive_demo/flutter_app/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.demo.flutterapp" (Raw: "com.demo.flutterapp")
               A: platformBuildVersionCode=(type 0x10)0x1
               A: platformBuildVersionName="1.0.0" (Raw: "1.0.0")
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1b
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="flutter_app" (Raw: "flutter_app")
                 A: android:icon(0x01010002)=@0x7f020000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 E: activity (line=27)
                   A: android:theme(0x01010000)=@0x7f030000
                   A: android:name(0x01010003)="com.demo.flutterapp.MainActivity" (Raw: "com.demo.flutterapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400035b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=41)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=45)
                     E: action (line=46)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=48)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[   +9 ms] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb -s 5EF0217C08017386 shell -x logcat -v time -t 1
[ +147 ms] Exit code 0 from: /Users/zongkelong/Library/Android/sdk/platform-tools/adb -s 5EF0217C08017386 shell -x logcat -v time -t 1
[        ] --------- beginning of system
           01-17 12:12:25.788 V/BroadcastQueue( 1138): Finished with ordered broadcast BroadcastRecord{2fe2c22 u0 telephony.dataconnection.DNS_MONITOR_ACTION}
[   +2 ms] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb -s 5EF0217C08017386 shell -x logcat -v time
[ +402 ms] DependencyChecker: nothing is modified after 2019-01-17 11:58:27.604.
[   +2 ms] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb version
[  +13 ms] Android Debug Bridge version 1.0.40
           Version 4986621
           Installed as /Users/zongkelong/Library/Android/sdk/platform-tools/adb
[   +2 ms] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb start-server
[   +9 ms] Building APK
[  +15 ms] Gradle task 'assembleDebug'...
[   +1 ms] executing: [/Users/zongkelong/flutterProjects/hive_demo/flutter_app/android/] /Users/zongkelong/flutterProjects/hive_demo/flutter_app/android/gradlew -Pverbose=true
-Ptarget=/Users/zongkelong/flutterProjects/hive_demo/flutter_app/lib/main.dart -Ptrack-widget-creation=false -Pcompilation-trace-file=compilation.txt -Ptarget-platform=android-arm64
assembleDebug
[+2306 ms] > Task :app:flutterBuildX86Jar
[ +196 ms] > Task :app:checkDebugClasspath UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[ +101 ms] > Task :app:compileDebugRenderscript UP-TO-DATE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[+1998 ms] > Task :app:flutterBuildDebug
[        ] [   +8 ms] executing: [/Users/zongkelong/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [/Users/zongkelong/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +13 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] master
[        ] [        ] executing: [/Users/zongkelong/flutter/] git ls-remote --get-url origin
[        ] [  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [        ] executing: [/Users/zongkelong/flutter/] git log -n 1 --pretty=format:%H
[        ] [  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] [        ] 83b9497c69912891431bd43925dbcee7cf867459
[        ] [        ] executing: [/Users/zongkelong/flutter/] git log -n 1 --pretty=format:%ar
[        ] [  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] [        ] 2 hours ago
[        ] [        ] executing: [/Users/zongkelong/flutter/] git describe --match v*.*.* --first-parent --long --tags
[        ] [  +18 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.1.9-96-g83b9497c6
[        ] [ +532 ms] /Users/zongkelong/flutter/bin/cache/dart-sdk/bin/dart /Users/zongkelong/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/zongkelong/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --strong --target=flutter --no-link-platform --incremental --packages
/Users/zongkelong/flutterProjects/hive_demo/flutter_app/.packages --output-dill build/app.dill --depfile
/Users/zongkelong/flutterProjects/hive_demo/flutter_app/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --filesystem-scheme org-dartlang-root package:flutter_app/main.dart
[+2699 ms] [+3770 ms] Building bundle
[        ] [   +2 ms] Writing asset files to /Users/zongkelong/flutterProjects/hive_demo/flutter_app/build/app/intermediates/flutter/debug/flutter_assets
[  +99 ms] [  +45 ms] Wrote /Users/zongkelong/flutterProjects/hive_demo/flutter_app/build/app/intermediates/flutter/debug/flutter_assets
[        ] [   +8 ms] "flutter bundle" took 4,235ms.
[  +95 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +103 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[  +96 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:splitsDiscoveryTaskDebug UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[ +301 ms] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:prepareLintJar UP-TO-DATE
[        ] > Task :app:generateDebugSources UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugNdk NO-SOURCE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[ +200 ms] > Task :app:transformClassesWithDexBuilderForDebug
[        ] > Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
[        ] > Task :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
[        ] > Task :app:mergeDebugJniLibFolders UP-TO-DATE
[ +296 ms] > Task :app:transformNativeLibsWithMergeJniLibsForDebug
[        ] > Task :app:transformNativeLibsWithStripDebugSymbolForDebug UP-TO-DATE
[        ] > Task :app:checkDebugLibraries UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[ +201 ms] > Task :app:transformResourcesWithMergeJavaResForDebug
[        ] > Task :app:validateSigningDebug UP-TO-DATE
[+2166 ms] > Task :app:packageDebug
[        ] > Task :app:assembleDebug
[        ] 33 actionable tasks: 9 executed, 24 up-to-date
[ +376 ms] Gradle task 'assembleDebug'... (completed)
[  +27 ms] calculateSha: LocalDirectory: '/Users/zongkelong/flutterProjects/hive_demo/flutter_app/build/app/outputs/apk'/app.apk
[ +318 ms] Built build/app/outputs/apk/debug/app-debug.apk.
[   +1 ms] executing: /Users/zongkelong/Library/Android/sdk/build-tools/28.0.3/aapt dump xmltree /Users/zongkelong/flutterProjects/hive_demo/flutter_app/build/app/outputs/apk/app.apk
AndroidManifest.xml
[  +12 ms] Exit code 0 from: /Users/zongkelong/Library/Android/sdk/build-tools/28.0.3/aapt dump xmltree
/Users/zongkelong/flutterProjects/hive_demo/flutter_app/build/app/outputs/apk/app.apk AndroidManifest.xml
[   +1 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.demo.flutterapp" (Raw: "com.demo.flutterapp")
               A: platformBuildVersionCode=(type 0x10)0x1
               A: platformBuildVersionName="1.0.0" (Raw: "1.0.0")
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1b
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="flutter_app" (Raw: "flutter_app")
                 A: android:icon(0x01010002)=@0x7f020000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 E: activity (line=27)
                   A: android:theme(0x01010000)=@0x7f030000
                   A: android:name(0x01010003)="com.demo.flutterapp.MainActivity" (Raw: "com.demo.flutterapp.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400035b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=41)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=45)
                     E: action (line=46)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=48)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
[   +1 ms] Stopping app 'app.apk' on BLA AL00.
[        ] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb -s 5EF0217C08017386 shell am force-stop com.demo.flutterapp
[ +104 ms] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb -s 5EF0217C08017386 shell pm list packages com.demo.flutterapp
[  +67 ms] Installing APK.
[   +1 ms] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb version
[   +8 ms] Android Debug Bridge version 1.0.40
           Version 4986621
           Installed as /Users/zongkelong/Library/Android/sdk/platform-tools/adb
[        ] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb start-server
[   +8 ms] Installing build/app/outputs/apk/app.apk...
[        ] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb -s 5EF0217C08017386 install -t -r
/Users/zongkelong/flutterProjects/hive_demo/flutter_app/build/app/outputs/apk/app.apk
[+2471 ms] Success
[        ] Installing build/app/outputs/apk/app.apk... (completed)
[   +2 ms] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb -s 5EF0217C08017386 shell echo -n fddeec71ef5fc050018ff906f2be55456fa37b18 >
/data/local/tmp/sky.com.demo.flutterapp.sha1
[  +25 ms] BLA AL00 startApp
[   +2 ms] executing: /Users/zongkelong/Library/Android/sdk/platform-tools/adb -s 5EF0217C08017386 shell am start -a android.intent.action.RUN -f 0x20000000 --ez
enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true com.demo.flutterapp/com.demo.flutterapp.MainActivity
[  +41 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.demo.flutterapp/.MainActivity (has extras) }

           Error type 3
           Error: Activity class {com.demo.flutterapp/com.demo.flutterapp.MainActivity} does not exist.
[        ] Waiting for observatory port to be available...

```

```
Analyzing flutter_app...                                         
No issues found! (ran in 2.0s)

```

```
[✓] Flutter (Channel master, v1.1.10-pre.96, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
    • Flutter version 1.1.10-pre.96 at /Users/zongkelong/flutter
    • Framework revision 83b9497c69 (3 hours ago), 2019-01-16 17:43:01 -0800
    • Engine revision 3c0aa918de
    • Dart version 2.1.1 (build 2.1.1-dev.1.0 492df72739)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zongkelong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • BLA AL00 • 5EF0217C08017386 • android-arm64 • Android 9 (API 28)

• No issues found!

```

**Comment by zoechi** [comment] 2019-01-17 07:41
Have you tried with `dev` channel as well? `flutter channel dev;flutter doctor`

**Comment by kangwang1988** [comment] 2019-01-17 07:58
> Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.demo.flutterapp/.MainActivity (has extras) }
Error type 3
Error: Activity class {com.demo.flutterapp/com.demo.flutterapp.MainActivity} does not exist.

This might be the cause.
@zongkelong  
Run `flutter clean` and `flutter -v run -v` to see if this problem remains.

**Comment by zoechi** [comment] 2019-02-12 07:56
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Closed by zoechi** 2019-02-12 07:56 UTC
Labels: waiting for customer response
