### ISSUE TITLE
Debug banner doesn't go away on release mode on desktop platforms

### ISSUE THREAD

**Issue by gspencergoog** [flutter/flutter#37352] opened 2019-08-01 00:01 UTC
When running the app with `flutter run --release`, the release build it built, but the "debug" banner doesn't go away.

This is probably because the build isn't actually turning off checked mode in the release configuration.

The relevant code that decides to show the banner is [in CheckedModeBanner](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/banner.dart#L349):
```dart
  @override
  Widget build(BuildContext context) {
    Widget result = child;
    assert(() {
      result = Banner(
        child: result,
        message: 'DEBUG',
        textDirection: TextDirection.ltr,
        location: BannerLocation.topEnd,
      );
      return true;
    }());
    return result;
  }
```

So, it checked mode were being disabled in release, then it wouldn't show.

I tried this on macOS, but may also be occurring on other platforms.

**Comment by gspencergoog** [comment] 2019-08-01 00:09
BTW, I think that this is probably because I ran `flutter run` first, and then ran `flutter run --release`, because if I do a `flutter clean`, and try `flutter run --release`, it just fails to compile with:
```
> flutter run --release
Launching lib/main.dart on macOS in release mode...
Building macOS application...                                           
File "build/macos/Build/Products/Debug/Flutter Desktop Example.app" does not
exist.

Sending crash report to Google.
Crash report sent (report ID: f6b3e08bf8d9e81d)
```

**Comment by stuartmorgan** [comment] 2019-08-01 05:38
It doesn't go away because we don't have a release mode; see the "Note" [here](https://github.com/google/flutter-desktop-embedding#example)

Duplicate of #30672

> it just fails to compile with

That's because you happened to try building right after Jonah landed a change to the Flutter side of the macOS build, but didn't land the FDE side. I just submitted the FDE side to unbreak that.

**Comment by jonahwilliams** [comment] 2019-08-01 06:18
Actually this happened before I landed the flutter side, so it was probably a bug in the old build script.

**Comment by stuartmorgan** [comment] 2019-08-01 12:39
Oh, I missed that it was looking for `Debug` with the `--release` flag.

**Comment by stuartmorgan** [comment] 2019-08-01 18:17
Oops, I meant to close this when I commented, since it's a duplicate.

**Closed by stuartmorgan** 2019-08-01 18:17 UTC
Labels: a: desktop, tool
