### ISSUE TITLE
Cocoon pre-submit checks fail to get updated even though luci build has finished.

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#61560] opened 2020-07-15 17:42 UTC
This issue happens in https://github.com/flutter/cocoon/pull/845

cocoon build shows success: https://ci.chromium.org/p/flutter/builders/try/Cocoon/1030

But the checks on PR is not updated: 
<img width="932" alt="Screen Shot 2020-07-15 at 10 40 19 AM" src="https://user-images.githubusercontent.com/54558023/87577536-e6020c80-c687-11ea-9468-15b3b24e4027.png">

**Comment by godofredoc** [comment] 2020-07-15 18:34
The problem is we used to have two different version of the pub/sub subscription one for staging and one for prod. This morning I deleted the staging one as we were hitting the API quotas and all checks api messages were being processed by the current prod version of flutter-dashboard that do not understand checks API yet.

**Comment by godofredoc** [comment] 2020-07-16 19:11
Closing this as after updating the pub/sub we haven't gotten this error anymore.

**Closed by godofredoc** 2020-07-16 19:11 UTC
Labels: team: infra
