### ISSUE TITLE
Plugin development pod folder structure is wrong in Xcode

### ISSUE THREAD

**Issue by nashfive** [flutter/flutter#19601] opened 2018-07-20 13:06 UTC
I create a plugin by following the documentation :
```shell
flutter create --org com.example --template=plugin hello
cd hello/example; flutter build ios --no-codesign
open ios/Runner.xcworkspace
```

The documentation says that the development files can be found under this folder in the Xcode project navigator:
__`Pods/Development Pods/hello/Classes/`__

But in fact, the project navigator puts them under:
__`Pods/Development Pods/hello/../../example/ios/.symlinks/plugins/hello/ios/Classes`__

Note: the files are physically at the right location `hello/ios/Classes/`, so I guess it's only a symlink issue. 

My environment:
```
Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (7 weeks ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760
```

**Comment by jaumard** [comment] 2018-07-20 13:08
I'm in the same case, no problem on Android side, just iOS

**Comment by jaumard** [comment] 2018-08-21 12:42
I just had a problem with this issue, in fact having all those ".." references is a problem for AppCode, it's not able to scan/index all files and goes in endless loop (issue reference https://youtrack.jetbrains.com/issue/OC-17593) once the references removed and files linked as the doc says (Classes/myFiles) AppCode is able to process correctly

**Comment by jaumard** [comment] 2018-10-12 14:36
Any news on this guys ?

**Comment by CaiJingLong** [comment] 2019-03-07 02:00
When I develop plug-ins, I use this approach to reduce the hierarchy for use in appcode.
https://github.com/CaiJingLong/flutter_photo_manager/blob/d3e5a089ed867bf9200906240621343f0ac1a7aa/example/ios/Podfile#L48-L60

After edit the `Podfile`, enter `$ pod install` in `example/iOS` and refresh it to look like this.

![image](https://user-images.githubusercontent.com/14145407/53926710-7e18da80-40bf-11e9-9917-d54dbe86515a.png)

@jaumard   If you also use appcode to develop plugins/application, you can refer to my approach.

**Comment by jmagman** [comment] 2019-08-16 22:51
@nashfive The documentation doesn't seem to be correct.  

Essentially the plugin example is pretending to be a normal Flutter app, but instead of pointing to the plugin downloaded from pub.dev, it's symlinking up to your plugin directory so you can debug your plugin code as you write it.

If this causing any build issues?  Or would making the documentation correct fix the confusion?

**Comment by nashfive** [comment] 2019-08-19 16:35
@jmagman I don't understand your question. 
The issue I opened doesn't cause any build issues. It's just an annoyance, but it can be quite frustrating for people with little knowledge in iOS development and how Xcode works. Maybe a small "warning" in the documentation stating that the path to access the plugin files in Xcode might look weird with all those '..' folders and that it will eventually be fixed one day ;)

**Comment by jmagman** [comment] 2019-08-30 19:33
Re-labeling as a request to correct path documented at https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-2c-add-ios-platform-code-hmswift.

**Comment by kf6gpe** [comment] 2020-01-27 17:03
Closing per reference in #38897

**Comment by jmagman** [comment] 2020-01-30 01:25
@kf6gpe I think https://github.com/flutter/flutter/issues/38897 was a duplicate of this one, not the other way around.

**Comment by lukepighetti** [comment] 2020-02-08 02:42
Documentation is misleading. 


<img width="900" alt="Screen Shot 2020-02-07 at 9 38 47 PM" src="https://user-images.githubusercontent.com/666539/74077941-698d4280-49f2-11ea-83ff-cda675f5e336.png">


<img width="292" alt="Screen Shot 2020-02-07 at 9 37 57 PM" src="https://user-images.githubusercontent.com/666539/74077942-6d20c980-49f2-11ea-8264-7c02c28c8249.png">

<img width="900" alt="Screen Shot 2020-02-07 at 9 38 47 PM" src="https://user-images.githubusercontent.com/666539/74077965-ac4f1a80-49f2-11ea-810a-f2450876f815.png">

**Comment by jmagman** [comment] 2020-02-10 19:06
https://github.com/flutter/website/pull/3677 is merged, closing.

**Closed by jmagman** 2020-02-10 19:06 UTC
Labels: d: api docs, documentation, plugin, ⌺‬ platform-ios
