### ISSUE TITLE
[Desktop] Center content inside an InteractiveViewer

### ISSUE THREAD

**Issue by erf** [flutter/flutter#94542] opened 2021-12-02 11:44 UTC
## Use case

I tried to center content inside an `InteractiveViewer` using `Center` and `Align` but the content always seem to be top-left aligned.

## Proposal

Add `Alignment` property?

I'm on macOS. Desktop app. 
Flutter 2.8.0-3.3.pre • channel beta
Tools • Dart 2.15.0

**Comment by maheshmnj** [comment] 2021-12-03 07:29
HI @erf, Please share a [minimal and complete reproducible code](https://stackoverflow.com/help/minimal-reproducible-example) to better address the issue

Thanks

**Comment by erf** [comment] 2021-12-03 12:40
My problem is that i would like to center some widget inside `InteractiveViewer` if it is smaller than the window, but if it is larger than the window, i would like to pan/move the content around. So i need to set `InteractiveViewer.constrained = false` to be able to move the view around, but then the view is locked in the top left window, but if i set it to true, then it centers ok.

Here is a code example:

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final controller = TransformationController();

  @override
  void initState() {
    super.initState();

    //controller.value = Matrix4.translation(translation)
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('InteractiveViewer test'),
      ),
      body: InteractiveViewer(
        scaleEnabled: false,
        constrained: false,
        transformationController: controller,
        child: Center(
          child: Container(
            alignment: Alignment.center,
            color: Colors.blue,
            width: 1500,
            height: 1500,
            child: Stack(
              children: [
                Container(
                  alignment: Alignment.topLeft,
                  color: Colors.green,
                  width: 250,
                  height: 250,
                ),
                Container(
                  alignment: Alignment.center,
                  color: Colors.red,
                  width: 250,
                  height: 250,
                )
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by erf** [comment] 2021-12-03 13:15
Hmmm.. Maybe i need to set the min size of the content to the window size for this to work ..

**Comment by erf** [comment] 2021-12-03 13:20
I think maybe this will work:

```
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final windowSize = MediaQuery.of(context).size;
    final paddingTop = MediaQuery.of(context).padding.top + kToolbarHeight;

    return Scaffold(
      appBar: AppBar(
        title: const Text('InteractiveViewer test'),
      ),
      body: InteractiveViewer(
        scaleEnabled: false,
        constrained: false,
        child: ConstrainedBox(
          constraints: BoxConstraints(
            minWidth: windowSize.width,
            minHeight: windowSize.height - paddingTop,
          ),
          child: Align(
            alignment: Alignment.topCenter,
            child: Container(
              alignment: Alignment.center,
              color: Colors.blue,
              width: 500,
              height: 500,
              child: Container(
                color: Colors.green,
                width: 250,
                height: 250,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```

Or is there a better way?

**Comment by maheshmnj** [comment] 2021-12-06 07:20
Hi @erf, I took your first example and modified it a bit to center the content. The child of interactive viewer should have a defined width and height and Incase of your example you gave a large width and height and the child was centered in the middle 1500x1500 somewhere around 750x750. To have the child continuously in the center of scree you should make use of MediaQuery or LayoutBuilder. Your second example looks fine though.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final controller = TransformationController();

  @override
  void initState() {
    super.initState();

    //controller.value = Matrix4.translation(translation)
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('InteractiveViewer test'),
        ),
        body: InteractiveViewer(
            scaleEnabled: false,
            constrained: false,
            transformationController: controller,
            child: Container(
              width: MediaQuery.of(context).size.width,
              height: MediaQuery.of(context).size.height
              alignment: Alignment.center,
              child: Stack(
                children: [
                  Container(
                    alignment: Alignment.topLeft,
                    color: Colors.green,
                    width: 250,
                    height: 250,
                  ),
                  Container(
                    alignment: Alignment.center,
                    color: Colors.red,
                    width: 250,
                    height: 250,
                  )
                ],
              ),
            )));
  }
}

```
</details>

Closing as this isn't really an issue with flutter and is working as intended, if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Closed** 2021-12-06 07:20 UTC
Labels: in triage
