### ISSUE TITLE
[tool_crash] FileSystemException: Failed to decode data using encoding 'utf-8', null

### ISSUE THREAD

**Issue by stevetam8x** [flutter/flutter#150664] opened 2024-06-23 02:16 UTC
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=emulator-5554 --start-paused --dart-define=flutter.inspector.structuredErrors=true lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Failed to decode data using encoding 'utf-8', null
```
#0      _File._tryDecode (dart:io/file_impl.dart:615:7)
#1      _File.readAsString (dart:io/file_impl.dart:621:7)
<asynchronous suspension>
#2      _pluginFromPackage (package:flutter_tools/src/flutter_plugins.dart:51:24)
<asynchronous suspension>
#3      findPlugins (package:flutter_tools/src/flutter_plugins.dart:94:28)
<asynchronous suspension>
#4      refreshPluginsList (package:flutter_tools/src/flutter_plugins.dart:1004:32)
<asynchronous suspension>
#5      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:367:5)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1736:7)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22621.3737], locale en-US)
    • Flutter version 3.22.2 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (2 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\AICLOUDX\AppData\Local\Android\Sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = C:\Users\AICLOUDX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11609105)

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 126.0.6478.115
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 126.0.2592.68

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 52b3dc25f6471c27b2144594abb11c741cb88f57
### Plugins
app_settings-5.1.1
audioplayers-6.0.0
audioplayers_android-5.0.0
audioplayers_darwin-6.0.0
audioplayers_linux-4.0.0
audioplayers_web-5.0.0
audioplayers_windows-4.0.0
connectivity_plus-6.0.3
device_info_plus-10.1.0
file_picker-8.0.3
file_selector_linux-0.9.2+1
file_selector_macos-0.9.4
file_selector_windows-0.9.3+1
firebase_core-3.0.0
firebase_core_web-2.17.1
firebase_crashlytics-4.0.0
firebase_messaging-15.0.0
firebase_messaging_web-3.8.8
flutter_inappwebview-6.0.0
flutter_inappwebview_android-1.0.13
flutter_inappwebview_ios-1.0.13
flutter_inappwebview_macos-1.0.11
flutter_inappwebview_web-1.0.8
flutter_keyboard_visibility-6.0.0
flutter_keyboard_visibility_linux-1.0.0
flutter_keyboard_visibility_macos-1.0.0
flutter_keyboard_visibility_web-2.0.0
flutter_keyboard_visibility_windows-1.0.0
flutter_local_notifications-17.1.2
flutter_plugin_android_lifecycle-2.0.19
fluttertoast-8.2.6
geolocator-12.0.0
geolocator_android-4.6.0
geolocator_apple-2.3.7
geolocator_web-4.0.0
geolocator_windows-0.2.3
google_maps_flutter-2.7.0
google_maps_flutter_android-2.9.0
google_maps_flutter_ios-2.7.0
google_maps_flutter_web-0.5.8
image_picker-1.1.2
image_picker_android-0.8.12+1
image_picker_for_web-3.0.4
image_picker_ios-0.8.11+1
image_picker_linux-0.2.1+1
image_picker_macos-0.2.1+1
image_picker_windows-0.2.1+1
location-6.0.2
location_web-5.0.1
path_provider-2.1.3
path_provider_android-2.2.4
path_provider_foundation-2.4.0
path_provider_linux-2.2.1
path_provider_windows-2.2.1
permission_handler-11.3.1
permission_handler_android-12.0.6
permission_handler_apple-9.4.4
permission_handler_html-0.1.1
permission_handler_windows-0.2.1
pointer_interceptor-0.10.1+1
pointer_interceptor_ios-0.10.0+2
pointer_interceptor_web-0.10.2
shared_preferences-2.2.3
shared_preferences_android-2.2.2
shared_preferences_foundation-2.4.0
shared_preferences_linux-2.3.2
shared_preferences_web-2.3.0
shared_preferences_windows-2.3.2
url_launcher-6.3.0
url_launcher_android-6.3.1
url_launcher_ios-6.3.0
url_launcher_linux-3.1.1
url_launcher_macos-3.2.0
url_launcher_web-2.3.1
url_launcher_windows-3.1.1
vibration-1.9.0

**Comment by huycozy** [comment] 2024-06-24 05:33
Closing this as a duplicate of https://github.com/flutter/flutter/issues/65021.

**Closed by huycozy** 2024-06-24 05:33 UTC
Labels: in triage
