### ISSUE TITLE
Flutter doctor summary 

### ISSUE THREAD

**Issue by zowhair** [flutter/flutter#14962] opened 2018-02-28 14:22 UTC
## Flutter Doctor

E:\>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (on Microsoft Windows [Version 10.0.16299.248], locale en-US, channel beta)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.0)
[√] Android Studio (version 3.0)
[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

What's the problem here???

**Comment by mit-mit** [comment] 2018-02-28 15:22
Closing as a duplicate of https://github.com/flutter/flutter/issues/14963

**Closed** 2018-03-01 00:25 UTC
