### ISSUE TITLE
App crashes on iPhone but works fine with android emulator, android device and iOS simulator

### ISSUE THREAD

**Issue by parikhparth23** [flutter/flutter#50676] opened 2020-02-12 23:25 UTC
I am using iPhone 11 OS 13.3.1.
When i try to install the app through android studio it crashes.
The app works fine on Android device, emulator and iOS simulator.

I did the following:
- [ flutter doctor is fine ] 

- [ upgraded to the latest flutter]  

- [ iOS certificates/signing is valid ] 

- [ flutter clean ]  

it gets stuck at Installing and launching...

**Comment by parikhparth23** [comment] 2020-02-12 23:26
`/Users/parth/AndroidStudioProjects/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, v1.15.4-pre.37, on Mac OS X 10.15.3 19D76, locale en)
    • Flutter version 1.15.4-pre.37 at /Users/parth/AndroidStudioProjects/flutter
    • Framework revision 508c35940b (27 minutes ago), 2020-02-12 19:58:05 -0300
    • Engine revision 0e8ed2715a
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 5244d99a5d)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/parth/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/parth/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.6015.9

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (2 available)
    • iPhone            • 00008030-001A50AA2150802E            • ios • iOS 13.3.1
    • iPhone 11 Pro Max • 9CB53965-BC27-4B77-B233-F7F40363B0E6 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
Process finished with exit code 0`

**Comment by parikhparth23** [comment] 2020-02-12 23:49
@jmagman any idea how to solve this?

**Comment by jmagman** [comment] 2020-02-12 23:55
You're saying the app is crashing on launch?  Need crash logs from the device.

Xcode > Windows > Device and Simulators > Devices > your device > View Device Logs
Please attach the crash with the time stamp matching when it crashed.

**Comment by parikhparth23** [comment] 2020-02-13 00:04
Incident Identifier: 4397FAB4-389F-4D60-8F31-8AB81EB65463
    CrashReporter Key:   a0ee111caa41b0dc0f768b6f0c0e6e0caf63cb7b 
    Hardware Model:      iPhone12,1
    Process:             Runner [376]
    Path:                /private/var/containers/Bundle/Application/2915D6F4-2A94-488F-B9F6- 
    828EBE33225C/Runner.app/Runner
    Identifier:          com.parikhparth23.iAmRich
    Version:             1 (1.0.0)
    Code Type:           ARM-64 (Native)
    Role:                Foreground
    Parent Process:      launchd [1]
    Coalition:           com.parikhparth23.iAmRich [572]


    Date/Time:           2020-02-11 18:33:49.7774 -0800
    Launch Time:         2020-02-11 18:33:49.6749 -0800
    OS Version:          iPhone OS 13.3.1 (17D50)
    Release Type:        User
    Baseband Version:    1.04.06
    Report Version:      104

    Exception Type:  EXC_CRASH (SIGABRT)
    Exception Codes: 0x0000000000000000, 0x0000000000000000
    Exception Note:  EXC_CORPSE_NOTIFY
    Termination Description: DYLD, Library not loaded: @rpath/Flutter.framework/Flutter | Referenced from: 
    /private/var/containers/Bundle/Application/2915D6F4-2A94-488F-B9F6- 
       828EBE33225C/Runner.app/Runner | Reason: no suitable image found.  Did find: | 
        /private/var/containers/Bundle/Application/2915D6F4-2A94-488F-B9F6- 
       828EBE33225C/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for 
        '/private/var/containers/Bundle/Application/2915D6F4-2A94-488F-B9F6- 
        828EBE33225C/Runner.app/Frameworks/Flutter.framework/Flutter'
        Triggered by Thread:  0

    Thread 0 Crashed:
    0   dyld                          	0x000000010289b2ac __abort_with_payload + 8
    1   dyld                          	0x00000001028a2914 abort_with_payload_wrapper_internal + 104
    2   dyld                          	0x00000001028a2948 unw_set_reg.cold.1 + 0
    3   dyld                          	0x000000010289f77c dyld::fastBindLazySymbol(ImageLoader**, unsigned 
    long) + 341884 (.cold.1) + 0
    4   dyld                          	0x0000000102853288 dyld::_main+ 29320 (macho_header const*, 
    unsigned long, int, char const**, char const**, char const**, unsigned long*) + 5260
    5   dyld                          	0x000000010284d22c dyldbootstrap::start+ 4652 (dyld3::MachOLoaded 
    const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 432
    6   dyld                          	0x000000010284d038 _dyld_start + 56

    Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000005   x2: 0x000000016d662c20   x3: 
    0x0000000000000097
        x4: 0x000000016d662820   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 
    0x00000000000003b0
        x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x6f77656d6172462f  x11: 
    0x74756c462f736b72
       x12: 0x74756c462f736b72  x13: 0x6d6172662e726574  x14: 0x6c462f6b726f7765  x15: 
    0x000a277265747475
       x16: 0x0000000000000209  x17: 0x0000000102895860  x18: 0x0000000000000000  x19: 
    0x0000000000000000
       x20: 0x000000016d662820  x21: 0x0000000000000097  x22: 0x000000016d662c20  x23: 
    0x0000000000000005
       x24: 0x0000000000000006  x25: 0x00000001028bc000  x26: 0x00000001028bc000  x27: 
    0x00000001028bc000
       x28: 0x00000001027d4000   fp: 0x000000016d6627f0   lr: 0x00000001028a2914
        sp: 0x000000016d6627b0   pc: 0x000000010289b2ac cpsr: 0x00000000
         esr: 0x56000080  Address size fault

    Binary Images:
    0x10279c000 - 0x1027a3fff Runner arm64  <2541d57647993715b7a65cad6eba3cac> 
    /var/containers/Bundle/Application/2915D6F4-2A94-488F-B9F6-828EBE33225C/Runner.app/Runner
    0x10284c000 - 0x1028b3fff dyld arm64e  <e008b93875933f57b94a747bc6c3beb5> /usr/lib/dyld

    EOF

**Comment by jmagman** [comment] 2020-02-13 00:09
Are you using a Personal Team provisioning profile?  If so, this is a duplicate of https://github.com/flutter/flutter/issues/49504#issuecomment-581554697.

If you run from Xcode you will see an error like:
```
/private/var/containers/Bundle/Application/D0BD5694-A7D6-4820-A146-A49DF0C0F0B1/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/D0BD5694-A7D6-4820-A146-A49DF0C0F0B1/Runner.app/Frameworks/Flutter.framework/Flutter'
```

**Comment by parikhparth23** [comment] 2020-02-13 00:11
so its an issue from the apple side and not from flutter based on the link above?

**Comment by jmagman** [comment] 2020-02-13 00:16
Yes, it's an issue with code signing any dynamic library (like Flutter) on iOS 13.3.1 and 13.4.  You can follow that issue for updates.

Duplicate of https://github.com/flutter/flutter/issues/49504.

**Comment by parikhparth23** [comment] 2020-02-13 00:16
thank you @jmagman

**Closed by jmagman** 2020-02-13 00:16 UTC
