### ISSUE TITLE
local_auth cause application lunched with black screen and error

### ISSUE THREAD

**Issue by tazik561** [flutter/flutter#80021] opened 2021-04-08 07:29 UTC
I installed `  local_auth: ^1.1.0` on my application and according [this example ](https://github.com/flutter/plugins/blob/master/packages/local_auth/example/android/app/src/main/java/io/flutter/plugins/localauthexample/EmbeddingV1Activity.java) I added this configuration in MainActivity.java :

```
import android.os.Bundle;
import io.flutter.app.FlutterFragmentActivity;
import io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin;
import io.flutter.plugins.localauth.LocalAuthPlugin;

@SuppressWarnings("deprecation")
public class MainActivity extends FlutterFragmentActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        FlutterAndroidLifecyclePlugin.registerWith(
                registrarFor(
                        "io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
        LocalAuthPlugin.registerWith(registrarFor("io.flutter.plugins.localauth.LocalAuthPlugin"));
    }
}
```
And I also added this permission:
`    <uses-permission android:name="android.permission.USE_BIOMETRIC"/>
`

But now then I am trying to run my application,  application is lunched with black screen and I got this error:

`E/flutter ( 7792): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

When I remove configuration in mainActivity , the application is run but with that configuration application start with black screen and that error.

This is my environment 
environment:
  sdk: '>=2.12.0 <3.0.0'

And shared preferences version :
`shared_preferences: ^2.0.5`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2021-04-08 14:14
Hi @tazik561 
I was running another issue bug when trying to reproduce but managed to reproduce with kotlin code and I can see the black screen at launch but no `MissingPluginException` even after using exact `shared_preferences` 

### Preview
https://user-images.githubusercontent.com/48603081/114041573-55123780-988d-11eb-8858-e0d214a1456f.mp4


<details> 
<summary>code sample</summary> 

```dart
// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// ignore_for_file: public_member_api_docs

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:local_auth/local_auth.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final LocalAuthentication auth = LocalAuthentication();
  _SupportState _supportState = _SupportState.unknown;
  bool? _canCheckBiometrics;
  List<BiometricType>? _availableBiometrics;
  String _authorized = 'Not Authorized';
  bool _isAuthenticating = false;

  @override
  void initState() {
    super.initState();
    auth.isDeviceSupported().then(
          (isSupported) => setState(() => _supportState = isSupported
              ? _SupportState.supported
              : _SupportState.unsupported),
        );
  }

  Future<void> _checkBiometrics() async {
    late bool canCheckBiometrics;
    try {
      canCheckBiometrics = await auth.canCheckBiometrics;
    } on PlatformException catch (e) {
      canCheckBiometrics = false;
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _canCheckBiometrics = canCheckBiometrics;
    });
  }

  Future<void> _getAvailableBiometrics() async {
    late List<BiometricType> availableBiometrics;
    try {
      availableBiometrics = await auth.getAvailableBiometrics();
    } on PlatformException catch (e) {
      availableBiometrics = <BiometricType>[];
      print(e);
    }
    if (!mounted) return;

    setState(() {
      _availableBiometrics = availableBiometrics;
    });
  }

  Future<void> _authenticate() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticate(
          localizedReason: 'Let OS determine authentication method',
          useErrorDialogs: true,
          stickyAuth: true);
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Authenticating';
      });
    } on PlatformException catch (e) {
      print(e);
      setState(() {
        _isAuthenticating = false;
        _authorized = "Error - ${e.message}";
      });
      return;
    }
    if (!mounted) return;

    setState(
        () => _authorized = authenticated ? 'Authorized' : 'Not Authorized');
  }

  Future<void> _authenticateWithBiometrics() async {
    bool authenticated = false;
    try {
      setState(() {
        _isAuthenticating = true;
        _authorized = 'Authenticating';
      });
      authenticated = await auth.authenticate(
          localizedReason:
              'Scan your fingerprint (or face or whatever) to authenticate',
          useErrorDialogs: true,
          stickyAuth: true,
          biometricOnly: true);
      setState(() {
        _isAuthenticating = false;
        _authorized = 'Authenticating';
      });
    } on PlatformException catch (e) {
      print(e);
      setState(() {
        _isAuthenticating = false;
        _authorized = "Error - ${e.message}";
      });
      return;
    }
    if (!mounted) return;

    final String message = authenticated ? 'Authorized' : 'Not Authorized';
    setState(() {
      _authorized = message;
    });
  }

  void _cancelAuthentication() async {
    await auth.stopAuthentication();
    setState(() => _isAuthenticating = false);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: ListView(
          padding: const EdgeInsets.only(top: 30),
          children: [
            Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                if (_supportState == _SupportState.unknown)
                  CircularProgressIndicator()
                else if (_supportState == _SupportState.supported)
                  Text("This device is supported")
                else
                  Text("This device is not supported"),
                Divider(height: 100),
                Text('Can check biometrics: $_canCheckBiometrics\n'),
                ElevatedButton(
                  child: const Text('Check biometrics'),
                  onPressed: _checkBiometrics,
                ),
                Divider(height: 100),
                Text('Available biometrics: $_availableBiometrics\n'),
                ElevatedButton(
                  child: const Text('Get available biometrics'),
                  onPressed: _getAvailableBiometrics,
                ),
                Divider(height: 100),
                Text('Current State: $_authorized\n'),
                (_isAuthenticating)
                    ? ElevatedButton(
                        onPressed: _cancelAuthentication,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Text("Cancel Authentication"),
                            Icon(Icons.cancel),
                          ],
                        ),
                      )
                    : Column(
                        children: [
                          ElevatedButton(
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Text('Authenticate'),
                                Icon(Icons.perm_device_information),
                              ],
                            ),
                            onPressed: _authenticate,
                          ),
                          ElevatedButton(
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Text(_isAuthenticating
                                    ? 'Cancel'
                                    : 'Authenticate: biometrics only'),
                                Icon(Icons.fingerprint),
                              ],
                            ),
                            onPressed: _authenticateWithBiometrics,
                          ),
                        ],
                      ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

enum _SupportState {
  unknown,
  supported,
  unsupported,
}

``` 

</details>

<details> 
<summary>logs</summary> 

```bash
Launching lib\main.dart on RMX2001 in debug mode...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:58694/kiVOXebFo-M=/ws
I/GED     (22966): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
I/.stable_flutte(22966): ProcessProfilingInfo new_methods=942 is saved saved_to_disk=1 resolve_classes_delay=5000
D/ColorViewRootUtil(22966): nav bar mode ignore false downX 669 downY 889 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=669.0, y[0]=889.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=20787593, downTime=20787593, deviceId=3, source=0x1002, displayId=0 }
D/ColorViewRootUtil(22966): nav bar mode ignore false downX 654 downY 1403 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=654.0, y[0]=1403.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=20788183, downTime=20788183, deviceId=3, source=0x1002, displayId=0 }
D/ColorViewRootUtil(22966): nav bar mode ignore false downX 657 downY 2209 mScreenHeight 2400 mScreenWidth 1080 mStatusBarHeight 54 globalScale 1.125 nav mode 0 rotation 0 event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=657.0, y[0]=2209.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x2, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=20789198, downTime=20789198, deviceId=3, source=0x1002, displayId=0 }
I/SurfaceView(22966): 55648344 visibleChanged:true -> SurfaceHolder.Callback.surfaceDestroyed
D/Surface (22966): Surface::disconnect(this=0x70806b6000,api=1)
D/ViewRootImpl(22966): setSurfaceViewCreated, created:false
D/Surface (22966): Surface::disconnect(this=0x70806b6000,api=-1)
D/SurfaceView(22966): updateScreenMode w:0 h:0 ViewRoot w:1080 h:2400
D/SurfaceView(22966): try to resquest 90Hz
D/ViewRootImpl(22966): set screen refresh mode 0 due to SurfaceView-55648344
D/Surface (22966): Surface::disconnect(this=0x7172bd1000,api=1)
I/GED     (22966): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
V/PhoneWindow(22966): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@b58ab35, this = DecorView@186c1be[MainActivity]
D/SurfaceView(22966): updateScreenMode w:0 h:0 ViewRoot w:1080 h:2400
D/SurfaceView(22966): try to resquest 90Hz
E/libEGL  (22966): call to OpenGL ES API with no current context (logged once per thread)
D/View    (22966): [Warning] assignParent to null: this = DecorView@186c1be[MainActivity]
I/InputTransport(22966): Destroy ARC handle: 0x70d00bd6e0
I/Choreographer(22966): Skipped 10 frames!  The application may be doing too much work on its main thread.
I/GED     (22966): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
```

</details>

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.870], locale en-US)
    • Flutter version 2.0.4 at C:\Users\Taha\Code\flutter_stable
    • Framework revision b1395592de (7 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31112.23
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.3
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.0)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • RMX2001 (mobile)  • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.870]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.68

! Doctor found issues in 1 category.
```
	
</details>

Is the issue in debug or release mode? If release mode try, [this](https://github.com/flutter/flutter/issues/78625#issuecomment-809915540)

Can you please try a new project with the latest `local_auth: ^1.1.3`,

**Comment by tazik561** [comment] 2021-04-08 19:32
This is my sample project . When I added configuration in MainActivityjava, The project don't be started.
[this is project ](https://github.com/tazik561/local_auth_test) .
I expect the project being run and when user did not configure finger print on mobile ,when tapped on `Authenticate` button ,default  biometric dialog open and user could do configuration.

**Comment by TahaTesser** [comment] 2021-04-09 09:24
Hi @tazik561 

> But now, The project not able to being to run and closed immediately.

This is the same issue I was running into yesterday with java project and I can see same crash on lunch using your project but app launched fine with kotlin https://github.com/flutter/flutter/issues/80021#issuecomment-815860080

<details> 
<summary>logs</summary> 

```bash
Running "flutter pub get" in demoapp...
Launching lib\main.dart on RMX2001 in debug mode...
Running Gradle task 'assembleDebug'...
Note: C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\local_auth-1.1.3\android\src\main\java\io\flutter\plugins\localauth\LocalAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Taha\AndroidStudioProjects\demoapp\android\app\src\main\java\com\example\demoapp\MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
E/AndroidRuntime(21239): FATAL EXCEPTION: main
E/AndroidRuntime(21239): Process: com.example.demoapp, PID: 21239
E/AndroidRuntime(21239): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.demoapp/com.example.demoapp.MainActivity}: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
E/AndroidRuntime(21239): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3534)
E/AndroidRuntime(21239): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689)
E/AndroidRuntime(21239): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(21239): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
E/AndroidRuntime(21239): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
E/AndroidRuntime(21239): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
E/AndroidRuntime(21239): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(21239): 	at android.os.Looper.loop(Looper.java:227)
E/AndroidRuntime(21239): 	at android.app.ActivityThread.main(ActivityThread.java:7822)
E/AndroidRuntime(21239): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21239): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(21239): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
E/AndroidRuntime(21239): Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
E/AndroidRuntime(21239): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:195)
E/AndroidRuntime(21239): 	at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:79)
E/AndroidRuntime(21239): 	at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:146)
E/AndroidRuntime(21239): 	at io.flutter.app.FlutterFragmentActivity.onCreate(FlutterFragmentActivity.java:93)
E/AndroidRuntime(21239): 	at com.example.demoapp.MainActivity.onCreate(MainActivity.java:11)
E/AndroidRuntime(21239): 	at android.app.Activity.performCreate(Activity.java:7963)
E/AndroidRuntime(21239): 	at android.app.Activity.performCreate(Activity.java:7952)
E/AndroidRuntime(21239): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
E/AndroidRuntime(21239): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505)
E/AndroidRuntime(21239): 	... 11 more

```

</details>


However both,  java or kotlin doesn't reproduce this
 `E/flutter ( 7792): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`


Can you please create a new project with kotlin and follow kotlin integration from [README](https://pub.dev/packages/local_auth#android-integration), let me know if you reproduce any issue

Thank you

**Comment by tazik561** [comment] 2021-04-09 10:27
> Hi @tazik561
> 
> > But now, The project not able to being to run and closed immediately.
> 
> This is the same issue I was running into yesterday with java project and I can see same crash on lunch using your project but app launched fine with kotlin [#80021 (comment)](https://github.com/flutter/flutter/issues/80021#issuecomment-815860080)
> 
> logs
> However both, java or kotlin doesn't reproduce this
> `E/flutter ( 7792): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
> 
> Can you please create a new project with kotlin and follow kotlin integration from [README](https://pub.dev/packages/local_auth#android-integration), let me know if you reproduce any issue
> 
> Thank you

In my[ projcet in kotlin ](https://github.com/tazik561/local_auth_kot) I just get error :
` PlatformException(NotAvailable, Required security features not enabled, null, null)
`
I expect , when user did not configure finger print on mobile ,when tapped on Authenticate button ,default biometric dialog open and user could do configuration but I got that error.

I am tring to produce `E/flutter ( 7792): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)` error

**Comment by tazik561** [comment] 2021-04-09 11:55
I produce the [error with black screen ](https://github.com/tazik561/black_error)at lunching time .

`E/flutter ( 7792): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

**Comment by TahaTesser** [comment] 2021-04-12 09:07
Hi @tazik561 
`E/flutter ( 7792): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

When running your project as it is, I can get this error. However, the project isn't exactly minimal and doesn't isolate the cause of the issue to either `local_auth` or `shared_preferences` packages. To better the issue, please try to reproduce the issue using these two packages with a minimal code as possible 

`PlatformException(NotAvailable, Required security features not enabled, null, null)`
I can also get the same error using official when I replace your `main.dart`  code with an official sample for `local_auth` and your project is Java. It works with 

This doesn't make sense when my device already has biometrics and security features (this would need a separate issue as this is not related to `MissingPluginException`. Just filed https://github.com/flutter/flutter/issues/80259 )

### Summary
### Java
Using java project with official sample gets `PlatformException(NotAvailable, Required security features not enabled, null, null)
`

### Kotlin 
Using Kotlin project, no issues

**Comment by tazik561** [comment] 2021-04-12 10:22
> Hi @tazik561
> `E/flutter ( 7792): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
> 
> When running your project as it is, I can get this error. However, the project isn't exactly minimal and doesn't isolate the cause of the issue to either `local_auth` or `shared_preferences` packages. To better the issue, please try to reproduce the issue using these two packages with a minimal code as possible
> 
> `PlatformException(NotAvailable, Required security features not enabled, null, null)`
> I can also get the same error using official when I replace your `main.dart` code with an official sample for `local_auth` and your project is Java. It works with
> 
> This doesn't make sense when my device already has biometrics and security features (this would need a separate issue as this is not related to `MissingPluginException`. Just filed #80259 )
> 
> ### Summary
> ### Java
> Using java project with official sample gets `PlatformException(NotAvailable, Required security features not enabled, null, null) `
> 
> ### Kotlin
> Using Kotlin project, no issues

I create 2 projects by [local_auth: ^0.6.3+2](https://github.com/tazik561/local_auth_0.6) on flutter  sdk: ">=2.7.0 <3.0.0" and[ local_auth: ^1.1.4](https://github.com/tazik561/local_auth_1.1.4) and flutter  sdk: ">=2.12.0 <3.0.0".

I run both project in same emulator. Im Using using[ official sample](https://pub.dev/packages/local_auth/example) for both project. [It's video](https://drive.google.com/file/d/1wokUvTbioR26DMAtuuLl4FEMmkjg5Km1/view?usp=sharing)

When I [lunch local_auth: ^0.6.3+2 project](https://pasteboard.co/JWY7bT2.png) and tapped on Authenticate button  this dialog is appeared :
https://pasteboard.co/JWY7Yc9.png

But  when I [lunch  local_auth: ^1.1.4 project](https://pasteboard.co/JWY8HoC.png) and tapped on Authenticate button I just get this error:
`PlatformException(NotAvailable, Required security features not enabled, null, null)`

I expect to see this[ configuration dialog](https://pasteboard.co/JWY7Yc9.png
) like  local_auth: ^0.6.3+2 project on local_auth: ^1.1.4 project.

Both these project lunched in one emulator and no finger print configuration do on android security setting.

In  local_auth: ^0.6.3+2 project, default biometric dialog is appeared to send user to biometric configuration part but local_auth: ^1.1.4 project, I got just error.

**Comment by TahaTesser** [comment] 2021-04-13 06:48
Hi @tazik561 


> But when I lunch local_auth: ^1.1.4 project and tapped on Authenticate button I just get this error:
> PlatformException(NotAvailable, Required security features not enabled, null, null)

This is a separate issue than your `MissingPluginException` and I filed it https://github.com/flutter/flutter/issues/80259 

`PlatformException(NotAvailable, Required security features not enabled, null, null)` also throws when I have all the security and biometrics features enabled, fingerprint registered and same code is working with Kotlin configuration for me, 

> In local_auth: ^0.6.3+2 project, default biometric dialog is appeared to send user to biometric configuration part but local_auth: ^1.1.4 project, I got just error.

That is in fact a regression


Coming to your with `MissingPluginException` 

> When running your project as it is, I can get this error. However, the project isn't exactly minimal and doesn't isolate the cause of the issue to either local_auth or shared_preferences packages. To better the issue, please try to reproduce the issue using these two packages with a minimal code as possible

**Comment by pedromassangocode** [comment] 2021-05-07 11:04
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-05-07 11:04 UTC
Labels: in triage, waiting for customer response

**Comment by tazik561** [comment] 2021-05-07 15:51
> Without additional information, we are unfortunately not sure how to resolve this issue.
> We are therefore reluctantly going to close this bug for now.
> Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
> Thanks for your contribution.
> 
> Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
> All system setups can be slightly different, so it's always better to open new issues and reference related issues.

What you mean , without additional information, you are unfortunately not sure how to resolve this issue.
Please run your example without enabling bitometric setting (fingerprint) on your device and run your example then you faced with this error.

**Comment by tazik561** [comment] 2021-05-11 11:29
> Please check your logs [#80021 (comment)](https://github.com/flutter/flutter/issues/80021#issue-853159986)
> 
> `MissingPluginException` issue was never reproduced and you don't provide details to reproduce such an issue, hence the issue is closed
> 
> > Please run your example without enabling bitometric setting (fingerprint) on your device and run your example then you faced with this error. By default biometric dialog mush be appeared but you catch error.
> 
> This is addressed in a different issue

unfortunately except in [my project](https://github.com/flutter/flutter/issues/80021#issuecomment-816630472), I can't reproduce this problem.
