### ISSUE TITLE
_listenerAttached': is not true” after layout change in a StatefulWidget

### ISSUE THREAD

**Issue by tolotrasamuel** [flutter/flutter#27841] opened 2019-02-12 15:05 UTC
I  am trying to make a form with Flutter in which user can change their answer after they submitted. The form has two TextField wrapped inside an AnimatedSwitcher. When the user clicks on the send button, the switcher is told to replace the TextField into a Text message saying that the 'Successfully submitted! (you can still change your answer)' I click on the button again, I see the form normally, but when I focus on the form, I see the error below for a brief instant.

> The following assertion was thrown building _ScrollableScope:
> 'package:flutter/src/rendering/editable.dart': Failed assertion: line 599 pos 14: 
> '_listenerAttached': is not true.

### The code below recreates exactly the error.

1. Write something in both text field
2. Click on submit button
3. Click on unsbmit button
4. Focus on any text field then focus on the other text field. The error will show .

```
import 'dart:core';
import 'package:flutter/material.dart';

class EditableFocus extends StatefulWidget {
  @override
  _State createState() {
    return _State();
  }
}

class _State extends State<EditableFocus> with TickerProviderStateMixin {
  FocusNode focusNode1 = FocusNode();
  FocusNode focusNode2 = FocusNode();
  bool success = false;
  TextEditingController controller1 = TextEditingController();
  TextEditingController controller2 = TextEditingController();
  final GlobalKey<FormState> _formKeyOne = GlobalKey<FormState>();
  final GlobalKey<FormState> _formKeyTwo = GlobalKey<FormState>();

  @override
  void initState() {
    super.initState();
    focusNode1.addListener(_focusListner);
    focusNode2.addListener(_focusListner);
    controller1.addListener(_changeListner);
    controller2.addListener(_changeListner);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        elevation: 0.5,
        title: Text(
          "Testing views",
          style: Theme.of(context).textTheme.title,
        ),
      ),
      body: _builtLayoutBuilder(),
    );
  }

  Widget _builtLayoutBuilder() {
    return Column(
      children: <Widget>[
        AnimatedSwitcher(
          duration: Duration(milliseconds: 200),
          child: _buildChild(),
        ),
        RaisedButton(
            child: Text('Submit/unsubmitted'),
            onPressed: () {
              setState(() {
                success = !success;
              });
            })
      ],
    );
  }

  void _focusListner() {
    if (focusNode1.hasFocus) {
      print('Focus on 1');
    } else if (focusNode2.hasFocus) {
      print('Focus on 2');
    }
  }

  void _changeListner() {
    if (focusNode1.hasFocus) {
      print(controller1.text);
    } else if (focusNode2.hasFocus) {
      print(controller2.text);
    }
  }

  Widget _buildChild() {
    if (success) {
      return Text('Successfully submitted! (you can still change your answer)');
    }
    return Column(
      children: <Widget>[
        TextFormField(
          key: _formKeyOne,
          focusNode: focusNode1,
          controller: controller1,
          style: TextStyle(fontSize: 16.0, color: Colors.black),
          decoration: InputDecoration(
              hintText: 'Write some text', border: InputBorder.none),
//                          onChanged: onSearchTextChanged,
        ),
        TextFormField(
          key: _formKeyTwo,
          focusNode: focusNode2,
          controller: controller2,
          style: TextStyle(fontSize: 16.0, color: Colors.black), 
          decoration: InputDecoration(
              hintText: 'Write some text', border: InputBorder.none),
//                          onChanged: onSearchTextChanged,
        ),
      ],
    );
  }
}
```

**Comment by zoechi** [comment] 2019-02-12 15:19
Duplicate of #21640

**Closed by zoechi** 2019-02-12 15:19 UTC
