### ISSUE TITLE
package non-platform dependent plugin  into snapshot

### ISSUE THREAD

**Issue by 337240552** [flutter/flutter#113307] opened 2022-10-12 02:44 UTC
It will increase the final package size. This may be a bug of flutter build tools, only platform releated plugin should be pacakaged.

## flutter doctor 
```
meemodeiMac:connectivity_plus-2.2.2 mingchunhu$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale zh-Hans-CN)                                                                                                                                                                           [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[!] Android Studio (version 2021.2)
    ✗ Failed to run Java: ProcessException: Bad CPU type in executable
        Command: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java -version
    ✗ Unable to determine bundled Java version.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[✓] VS Code (version 1.70.2)
[!] Proxy Configuration
    ! NO_PROXY does not contain ::1
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 3 categories.
```
## Steps to Reproduce
 
1. Execute `flutter build apk --target-platform=android-arm64 --analyze-size` on the code sample  
I use this [cross platform plugin](https://pub.dev/packages/connectivity_plus/example)  as a sample
 
- dependecy graph

<img width="527" alt="image" src="https://user-images.githubusercontent.com/329210/195237209-3fbc65a2-48ee-4a05-8295-5b8004d371bb.png">

**Expected results:** 
Linux dependency `package:dbus` was built in android snapshot! It was unexpected. Only android dependecy should be built in the so. 

**Actual results:** 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/329210/195230819-92e85ea4-0257-4a8d-b60d-a720d58b5fe5.png">
<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by huycozy** [comment] 2022-10-12 09:17
@337240552 I tried building APK with `connectivity_plus: ^2.3.9` on the latest Flutter stable `3.3.4` but didn't see `package:dbus`:

<img width="350" alt="Screen Shot 2022-10-12 at 16 15 47" src="https://user-images.githubusercontent.com/104349824/195302818-34d328c4-cc1b-463a-95a3-a67e979f5500.png">

Please retry on the latest Flutter stable `3.3.4` and `connectivity_plus: ^2.3.9` and share your result here.

**Comment by stuartmorgan** [comment] 2022-10-12 10:35
Duplicate of https://github.com/flutter/flutter/issues/113311

**Closed by stuartmorgan** 2022-10-12 10:35 UTC
Labels: waiting for customer response, in triage

**Comment by 337240552** [comment] 2022-10-13 02:26
> #113311
Thanks Reply!  I tried building `connectivity_plus: ^2.3.9` on Flutter `3.0.5` but dbus still existing. We cannot upgrade Flutter sdk in the short term, the current solution is to manually delete linux dependency.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/329210/195483389-9055deea-6139-4b9d-b3cb-087460575eb8.png">

**Comment by huycozy** [comment] 2022-10-13 11:42
@337240552  please follow up on https://github.com/flutter/flutter/issues/113311 for further updates.
