### ISSUE TITLE
[tool_crash] ProcessException: The system cannot find the file specified. Command: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 2

### ISSUE THREAD

**Issue by Vikalp19041999** [flutter/flutter#81112] opened 2021-04-24 07:32 UTC
## Command
```
flutter doctor
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: The system cannot find the file specified.
 Command: C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat, OS error code: 2
```
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:39:20)
#3      ErrorHandlingProcessManager.start.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:638:33)
#4      _run (package:flutter_tools/src/base/error_handling_io.dart:532:20)
#5      ErrorHandlingProcessManager.start (package:flutter_tools/src/base/error_handling_io.dart:638:12)
#6      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:472:28)
#7      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:491:35)
#8      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:282:34)
<asynchronous suspension>
#9      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:222:7)
<asynchronous suspension>
#10     PubDependencies.update (package:flutter_tools/src/cache.dart:774:5)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:562:9)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1109:7)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#15     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
<asynchronous suspension>
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:13)
```
```
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.18362.30], locale en-IN)
    • Flutter version 2.0.5 at C:\src\flutter
    • Framework revision adc687823a (8 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at F:\Android_SDK
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = F:\Android_SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.55.2)
    • VS Code at C:\Users\Vicky\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • AC2001 (mobile) • 8a4c078d • android-arm64  • Android 11 (API 30)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 89.0.4389.128

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment] 2021-04-24 12:55
duplicate of https://github.com/flutter/flutter/issues/68958

**Comment by darshankawar** [comment] 2021-04-26 07:31
Closing this as duplicate.

**Closed by darshankawar** 2021-04-26 07:31 UTC
Labels: in triage
