### ISSUE TITLE
Auto-scrolling to text fields within a SingleChildScrollView

### ISSUE THREAD

**Issue by kentcb** [flutter/flutter#15220] opened 2018-03-06 23:19 UTC
## Steps to Reproduce

All I'm trying to do is display several fields on a page. When the keyboard isn't present, I want those fields to stretch to the available space. When the keyboard _is_ present, I want them to retain their spacing, allow the user to scroll to see them all, but also **scroll to the currently focused field**. The auto-scrolling is the part that isn't working in the below repro.

I'm really confused about what flutter should be taking care of here versus what it shouldn't, as well as how I could achieve this myself using flutter's building blocks. I've found conflicting information in my searches, including a suggestion that auto-scrolling to a focused field should already work (it doesn't).

```dart
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var layoutBuilder = new LayoutBuilder(
      builder: _buildWithConstraints,
    );

    var scaffold = new Scaffold(
      body: layoutBuilder,
      appBar: new AppBar(title: new Text("Repro")),
    );

    return scaffold;
  }

  Widget _buildWithConstraints(
      BuildContext context, BoxConstraints constraints) {
    var fields = new Iterable<int>.generate(4)
        .map((_) => new TextField())
        .toList(growable: false);

    var column = new Column(
      children: fields,
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      mainAxisSize: MainAxisSize.max,
    );

    var container = new Container(
      color: Colors.white,
      child: column,
      padding: const EdgeInsets.all(20.0),
    );

    if (constraints.hasBoundedHeight) {
      constraints = constraints.copyWith(
          maxHeight: constraints.maxHeight +
              MediaQuery.of(context).viewInsets.vertical);
    }

    var constrainedBox = new ConstrainedBox(
      constraints: constraints,
      child: container,
    );

    var scrollView = new SingleChildScrollView(
      child: constrainedBox,
    );

    return scrollView;
  }
}
```

## Logs

N/A

## Flutter Doctor

```
[√] Flutter (on Microsoft Windows [Version 10.0.16299.248], locale en-AU, channel alpha)
    • Flutter version 0.0.21 at C:\Users\kent\Repository\flutter
    • Framework revision 2e449f06f0 (5 weeks ago), 2018-01-29 14:26:51 -0800
    • Engine revision 6921873c71
    • Tools Dart version 2.0.0-dev.16.0
    • Engine Dart version 2.0.0-edge.da1f52592ef73fe3afa485385cb995b9aec0181a

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 22.0.2
    • Dart plugin version 173.4548.30

[√] Connected devices
    • Pixel • FA6AF0303979 • android-arm • Android 8.1.0 (API 27)
```

**Comment by aubykhan** [comment] 2018-03-11 02:23
Happening with me too and I’m still trying to wrap my head around it. 

One way to somewhat solve this issue is to make your list view reversed by setting the property. Along with this, you’ll need to reverse your widget list of course. The problem with this approach is that the top fields go out of the viewport when they are focused though it solves the issue for the fields that are in the middle and the end.

**Comment by aubykhan** [comment] 2018-03-11 02:44
Similar issue is tracked here: https://github.com/flutter/flutter/issues/10826

**Comment by Hixie** [comment] 2018-03-12 02:47
Yeah this is a dupe of the last remaining part of #10826 -- we don't yet scroll to text fields when the keyboard comes up.

**Closed by Hixie** 2018-03-12 02:47 UTC
