### ISSUE TITLE
I have newly installed flutter but an error is recurring in the connected device section saying that the doctor check crashed and unable to run 'adb'

### ISSUE THREAD

**Issue by Kritikazr** [flutter/flutter#88513] opened 2021-08-19 09:51 UTC
```
[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_SDK_ROOT environment variable: C:\Users\Subin
      Shrestha\AppData\Local\Android\Sdk\platform-tools\adb.exe
 #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:78:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:397:54)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart)
      <asynchronous suspension>
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:163:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:510:34)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
      <asynchronous suspension>

```

**Comment by darshankawar** [comment] 2021-08-19 10:18
Closing this as a duplicate of https://github.com/flutter/flutter/issues/72101

**Closed by darshankawar** 2021-08-19 10:18 UTC
Labels: in triage
