### ISSUE TITLE
`google_maps_flutter` tests do not run on arm64 simulator

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#143133] opened 2024-02-07 23:47 UTC
Found in issue: https://github.com/flutter/packages/pull/6069

Running on a real device as the target works.

## reproduction steps
1) `cd //packages/google_maps_flutter/google_maps_flutter_ios/example/ios12`
1) `flutter pub get`
1) `cd ios`
1) `pod install` -- This should be superfluous.
1) `open Runner.xcworkspace`
1) Select a simulator as the destination
1) Run tests in side of xcode

## error log
```
ld: warning: ignoring file '/Users/aaclarke/Library/Developer/Xcode/DerivedData/Runner-ayognwbdnjnpzvfurpulipqfltxn/Build/Products/Debug-iphonesimulator/google_maps_flutter_ios/libgoogle_maps_flutter_ios.a[10](GoogleMapPolylineController.o)': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/aaclarke/Library/Developer/Xcode/DerivedData/Runner-ayognwbdnjnpzvfurpulipqfltxn/Build/Products/Debug-iphonesimulator/google_maps_flutter_ios/libgoogle_maps_flutter_ios.a[9](GoogleMapPolygonController.o)': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/aaclarke/Library/Developer/Xcode/DerivedData/Runner-ayognwbdnjnpzvfurpulipqfltxn/Build/Products/Debug-iphonesimulator/google_maps_flutter_ios/libgoogle_maps_flutter_ios.a[8](GoogleMapMarkerController.o)': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/aaclarke/Library/Developer/Xcode/DerivedData/Runner-ayognwbdnjnpzvfurpulipqfltxn/Build/Products/Debug-iphonesimulator/google_maps_flutter_ios/libgoogle_maps_flutter_ios.a[7](GoogleMapController.o)': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/aaclarke/Library/Developer/Xcode/DerivedData/Runner-ayognwbdnjnpzvfurpulipqfltxn/Build/Products/Debug-iphonesimulator/google_maps_flutter_ios/libgoogle_maps_flutter_ios.a[6](GoogleMapCircleController.o)': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/aaclarke/Library/Developer/Xcode/DerivedData/Runner-ayognwbdnjnpzvfurpulipqfltxn/Build/Products/Debug-iphonesimulator/google_maps_flutter_ios/libgoogle_maps_flutter_ios.a[5](google_maps_flutter_ios-dummy.o)': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/aaclarke/Library/Developer/Xcode/DerivedData/Runner-ayognwbdnjnpzvfurpulipqfltxn/Build/Products/Debug-iphonesimulator/google_maps_flutter_ios/libgoogle_maps_flutter_ios.a[4](FLTGoogleMapTileOverlayController.o)': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/aaclarke/Library/Developer/Xcode/DerivedData/Runner-ayognwbdnjnpzvfurpulipqfltxn/Build/Products/Debug-iphonesimulator/google_maps_flutter_ios/libgoogle_maps_flutter_ios.a[3](FLTGoogleMapsPlugin.o)': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/aaclarke/Library/Developer/Xcode/DerivedData/Runner-ayognwbdnjnpzvfurpulipqfltxn/Build/Products/Debug-iphonesimulator/google_maps_flutter_ios/libgoogle_maps_flutter_ios.a[2](FLTGoogleMapJSONConversions.o)': found architecture 'x86_64', required architecture 'arm64'
ld: building for 'iOS-simulator', but linking in object file (/Users/aaclarke/dev/packages/packages/google_maps_flutter/google_maps_flutter_ios/example/ios12/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps) built for 'iOS'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## versions
flutter:
```
commit 37fd173e03f33081ae75828272ca4d63c18aec75 (HEAD)
Author: David Martos <davidmartos96@gmail.com>
Date:   Tue Feb 6 20:01:49 2024 +0100
```

packages: 
```
commit ef765f105069489dc8db93b568a00a043575f39f (upstream/main, main)
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue Feb 6 16:33:32 2024 +0000
```

**Comment by jmagman** [comment] 2024-02-08 00:07
If you run `flutter build ios` once the xcconfig will be updated to enforce the architecture.  However there's a bug that `flutter pub get` (`ensureReadyForPlatformSpecificTooling` -> `updateGeneratedXcodeProperties`) doesn't do this correctly.  Duplicate of https://github.com/flutter/flutter/issues/141716.

**Closed by jmagman** 2024-02-08 00:07 UTC
Labels: platform-ios, fyi-ecosystem

**Comment by jmagman** [comment] 2024-02-08 19:26
> * `flutter pub get`
> * `cd ios`
> * `pod install` -- This should be superfluou

By the way, you can run `flutter build ios --config-only` to set up the Xcode project with plugins, etc. without actually building the project, instead of having to run `pod install` manually.
