### ISSUE TITLE
IntelliJ 2020.1.1 flutter plugin is not detected by flutter doctor

### ISSUE THREAD

**Issue by DZadig** [flutter/flutter#56553] opened 2020-05-07 14:22 UTC
After installing IntelliJ 2020.1.1 and its flutter plugin I run flutter doctor but the command doesn't show my IDE and its plugins like usual, this bug is only related to the 2020 version, older versions run well.

So to reproduce it, just upgrade or install the latest version of intelliJ, install the flutter plugin and finally run Flutter doctor using the CMD.

I contacted the IntelliJ team, they told me that I should open an issue here, apparently according to the Jetbrains Team _the problem must be caused by changing IDEA plugins folder in 2020.1 - consequently the flutter doctor can't find the Flutter plugin anymore._

![flutter_command](https://user-images.githubusercontent.com/41085331/81305647-dc07d000-907e-11ea-8a2e-87cca0d924a3.JPG)
![IDE_PLUGINS](https://user-images.githubusercontent.com/41085331/81305651-dca06680-907e-11ea-99d5-34945a798508.JPG)

**Comment by TahaTesser** [comment] 2020-05-07 15:33
Hi @DZadig 
You need execute `flutter doctor -v` to see all the details to related to plugin and i can see you have all the ticks 
can you please provide your `flutter doctor -v`? 
Thank you

**Comment by DZadig** [comment] 2020-05-07 15:41
@TahaTesser  Thank you for your response, you find in attachment the screenshot showing the result of "flutter doctor -v" command.
The command doesn't even detect the intelliJ IDE, like I said in the previous comment, _the jetbrains team confirmed that some changes has been made on the flutter plugins directory._

**Comment by christopherfujino** [comment] 2020-05-09 01:20
Thanks for opening this issue! It is actually a duplicate of https://github.com/flutter/flutter/issues/54867. I will close this issue, please subscribe to that issue for updates. In the comments https://github.com/flutter/flutter/issues/54867#issuecomment-623006370 there is a temporary workaround, until the issue can be fixed in the tool.

**Closed by christopherfujino** 2020-05-09 01:20 UTC
Labels: t: flutter doctor, tool
