### ISSUE TITLE
Mac_android microbenchmarks is 3.24% flaky

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#83939] opened 2021-06-03 20:21 UTC
The post-submit test builder mac_android_microbenchmarks had a flaky ratio 3.24% for the past 15 days, which is above our 2% threshold.

The test shows infra failure, however it is indeed test failures (https://github.com/flutter/flutter/issues/77193)

Please follow https://github.com/flutter/flutter/wiki/Reducing-Test-Flakiness#fixing-flaky-tests to fix the flakiness and enable the test back after validating the fix (internal dashboard to validate: go/flutter_test_flakiness).

(Creating this issue from infra team after the gardener rotation's one-time scan.)

**Comment by jmagman** [comment] 2021-06-03 20:36
I started filing this and then I noticed every test failure seemed completely different.  Which doesn't mean it shouldn't be investigated, but it's a weird one.

**Comment by jmagman** [comment] 2021-06-03 20:41
Also I ignored this because they really were infra failures:
https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1367
https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1379
https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1390

Upload metrics failure:
https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1366

**Comment by keyonghan** [comment] 2021-06-03 20:52
> Also I ignored this because they really were infra failures:
> https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1367
> https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1379
> https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1390
> 
These are due to timeout on `Waiting for observatory port to be available`

> Upload metrics failure:
> https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1366

This was caused by cocoon new deployment propagating (multiple tests failed around that time).

**Comment by jmagman** [comment] 2021-06-03 20:56
> These are due to timeout on `Waiting for observatory port to be available`

I missed the blue test timeout, only saw the purple part.

**Comment by zanderso** [comment] 2021-06-03 21:28
Do we know why these failures don't include any logs from the device?

**Comment by zanderso** [comment] 2021-06-03 23:01
@bdero Could you take a crack at this one?

**Comment by bdero** [comment] 2021-06-04 01:38
@zanderso Sure, I'll try to repro this on one of my devices.

**Comment by bdero** [comment] 2021-06-04 02:28
+1 on https://github.com/flutter/flutter/issues/83939#issuecomment-854192435

So far (100 runs in) I haven't been able to reproduce this with a Pixel 3 XL. Could someone with access to the Moto G4s run the test a couple hundred times, observing ADB output with `flutter logs` when it hangs? /cc @godofredoc, @keyonghan

```bash
pushd dev/benchmarks/microbenchmarks; ../../../bin/flutter run -v --profile --no-publish-port -d [device_id] lib/stocks/layout_bench.dart; popd
```

Otherwise, I can order a couple of aftermarket Moto G4s -- they're pretty cheap but it'll take a few days to ship. Might be best for me to get a hold of one either way.

The failure cases themselves have device ID variation:
- 2021-06-03 12:59 PM (PDT) https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1395 - lib/stocks/layout_bench.dart - ZY223HMWMJ
- 2021-06-03 8:41 AM (PDT) https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1390 - lib/foundation/all_elements_bench.dart - ZY223HMWMJ
- 2021-06-02 4:38 PM (PDT) https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1379 - lib/stocks/layout_bench.dart - ZY223LSLG4
- 2021-06-02 9:16 AM (PDT) https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1367 - lib/stocks/layout_bench.dart - ZY223VMBPX
- 2021-05-21 7:40 PM (PDT) https://ci.chromium.org/p/flutter/builders/prod/Mac_android%20microbenchmarks/1262 - lib/stocks/build_bench.dart - ZY223LSLG4

**Comment by dnfield** [comment] 2021-06-04 06:25
> Do we know why these failures don't include any logs from the device?

Logcat is starting, but we're only getting a beginning of main log and something about packagemanager for our process.

There are no other logs. It seems like the app is hanging and doing nothing and we just can't connect to the observatory.

**Comment by dnfield** [comment] 2021-06-04 06:29
@godofredoc @keyonghan - do we have any health checks that run on these devices? e.g. something that tells us how much free space they have, when their last reboot was?

We should add something to take an ADB screenshot if/when this times out too.

**Comment by dnfield** [comment] 2021-06-04 07:05
We also need to bump the execution timeout for these guys. We let the tests take up to 30 minutes before timing them out, but once that happens no subsequent steps are allowed to run.

**Comment by dnfield** [comment] 2021-06-04 07:12
https://github.com/flutter/infra/pull/467 increases the expiration time for these shard.

https://flutter-review.googlesource.com/c/recipes/+/14400 will take a screenshot after the test, which should help us know e.g. whether frames even rendered, whether we're stuck on some other system UI for some reason, etc.

**Comment by bdero** [comment] 2021-06-04 08:10
> There are no other logs. It seems like the app is hanging and doing nothing and we just can't connect to the observatory.

Although the are small logcat snaps with `-t 1` before activity launches, it doesn't look like the log stream being read to collect the observatory URI as output by flutter at runtime is [ever printed/forwarded to the test stdout](https://github.com/flutter/flutter/blob/1625befc36799f9a281b0ab4574780c469650a17/packages/flutter_tools/lib/src/protocol_discovery.dart#L111-L139) -- otherwise there'd be a line similar to the following for each time the flutter activity runs, right?:

```
[+6318 ms] I/flutter ( 7514): Observatory listening on http://127.0.0.1:37037/epPy3QczJHY=/
```

Although there's one such line mysteriously present at the top of each test run's stdout regardless of the number of activity runs. Not sure what's going on there.

Since waiting on this stream synchronously blocks anyways, maybe we should toss a print in there just in case there's useful engine output that clues to the cause of hanging next time it flakes.

**Comment by dnfield** [comment] 2021-06-04 08:26
That linked code is to avoid printing out the enormous amount of logspam that comes from logcat. It's filtering based on our process ID. 

We could try to make it more verbose if we really need to, but it's likely that it will just give us lots of system based garbage.

It may be better to instead have the recipe just get the full logcat and add it to the logs dir separately so we could analyze that, rather than clogging up what's meant to be application specific logging.

**Comment by dnfield** [comment] 2021-06-04 08:28
And the initial observatory line you're seeing is from the test running harness on the host itself, e.g.:

```
Executing: /opt/s/w/ir/x/w/recipe_cleanup/tmpjowsyt/flutter sdk/bin/cache/dart-sdk/bin/dart --disable-dart-dev --enable-vm-service=0 --no-pause-isolates-on-exit bin/tasks/microbenchmarks.dart in /opt/s/w/ir/x/w/recipe_cleanup/tmpjowsyt/flutter sdk/dev/devicelab with environment {BOT: true, LANG: en_US.UTF-8}
 [microbenchmarks] [STDOUT] Observatory listening on http://127.0.0.1:52664/KB4dbBmnho4=/
```

So `dart --disable-dart-dev --enable-vm-service=0 --no-pause-isolates-on-exit bin/tasks/microbenchmarks.dart` is causing that line to print. It's not coming from logcat.

**Comment by bdero** [comment] 2021-06-04 10:34
> We could try to make it more verbose if we really need to, but it's likely that it will just give us lots of system based garbage.

This seems essential for getting a grip on flakes like this one, as none of the streaming log output is making it to the tests at activity launch right now, and so AFAICT we don't actually get output produced by the flutter pid recorded anywhere during this moment.

+1 to possibly having completely unfiltered logcat output as a separate test artifact as well, that seems like a great idea and would probably also have the benefit of making many device resource contention issues more obvious (OOMs, FD limits, no disk space, etc).  👍

**Comment by godofredoc** [comment] 2021-06-04 16:09
@bdero @dnfield did you take a look at #77193? it has a few repros and more logs. The "waiting for observatory to be open" happens across all the android tests.

Regarding the timeouts would it be possible to add a timeout to the code blocking on getting output from observatory? microbenchmarks is the reason we added timeouts to devicelab tests to prevent a single test holding the test bed for a very long time.

I do have an android phone I can try to repro, can you please share the commands to collect additional logs?

**Comment by dnfield** [comment] 2021-06-04 16:29
Thanks @godofredoc .

I can see in the logs there that we definitely filtered logs we shouldn't have.

It'd be good to _always_ have the devicelab bots get all logs separately, and it'd also be good to try to get the tool to pull logs. Last time I was looking at this I tried ot make sure timelines always got uploaded, but I didn't go as far as the devicelogs. Filed https://github.com/flutter/flutter/issues/84000

**Comment by chinmaygarde** [comment] 2021-06-07 17:33
The linked PR has been reviewed. We can hopefully get better logs now.

**Comment by chinmaygarde** [comment] 2021-06-14 17:34
The linked PR was merged. Are we still tracking the reliability of this? Not sure how many times this has happened over the past week.

**Comment by keyonghan** [comment] 2021-06-14 17:45
This is one instance happened on 06/11:
https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_android%20microbenchmarks/1496/overview

**Comment by dnfield** [comment] 2021-06-14 18:18
The full(er) device log showed:

```
06-11 20:41:39.938 31115 31115 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 31115 (microbenchmarks)
06-11 20:41:40.021 31143 31143 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-11 20:41:40.021 31143 31143 F DEBUG   : Build fingerprint: 'motorola/athene/athene:7.0/NPJS25.93-14-8.1-9/4:user/release-keys'
06-11 20:41:40.021 31143 31143 F DEBUG   : Revision: 'p2a0'
06-11 20:41:40.021 31143 31143 F DEBUG   : ABI: 'arm'
06-11 20:41:40.021 31143 31143 F DEBUG   : pid: 31115, tid: 31115, name: microbenchmarks  >>> com.yourcompany.microbenchmarks <<<
06-11 20:41:40.021 31143 31143 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
06-11 20:41:40.021 31143 31143 F DEBUG   :     r0 ad1b3ebc  r1 9a47a0c0  r2 9aa0eba1  r3 00000000
06-11 20:41:40.022 31143 31143 F DEBUG   :     r4 9c23d238  r5 00000007  r6 9c23d230  r7 aa85fe00
06-11 20:41:40.022 31143 31143 F DEBUG   :     r8 99e9ee36  r9 beb7d718  sl abb2e800  fp 9bff438c
06-11 20:41:40.022 31143 31143 F DEBUG   :     ip 9c170d6c  sp b6bfbbd8  lr 9bcfd6b4  pc 9c0c07e8  cpsr 800f0030
06-11 20:41:40.022 31143 31143 F DEBUG   : 
06-11 20:41:40.022 31143 31143 F DEBUG   : backtrace:
06-11 20:41:40.023 31143 31143 F DEBUG   :     #00 pc 003d17e8  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libflutter.so (offset 0x501000)
06-11 20:41:40.023 31143 31143 F DEBUG   :     #01 pc 0000e6b0  /data/app/com.yourcompany.microbenchmarks-1/lib/arm/libflutter.so (offset 0x501000)
```

**Comment by dnfield** [comment] 2021-06-14 18:19
@flutter-symbolizer-bot https://github.com/flutter/flutter/issues/83939#issuecomment-860892433

**Comment by dnfield** [comment] 2021-06-14 18:21
@flutter-symbolizer-bot engine#b807dfde90a1f9409ddc3a396635320ec345ff68 https://github.com/flutter/flutter/issues/83939#issuecomment-860892433

**Comment by dnfield** [comment] 2021-06-14 18:22
@flutter-symbolizer-bot engine#b807dfde90a1f9409ddc3a396635320ec345ff68 profile arm64 https://github.com/flutter/flutter/issues/83939#issuecomment-860892433

**Comment by dnfield** [comment] 2021-06-14 18:23
@a-siva @rmacnak-google @aam - looks like we got a segfault in the VM here. We don't have a consistent reproduction yet unfortunately.

**Comment by mraleph** [comment] 2021-06-14 21:04
@flutter-symbolizer-bot engine#b807dfde90a1f9409ddc3a396635320ec345ff68 profile arm https://github.com/flutter/flutter/issues/83939#issuecomment-860892433

**Comment by dnfield** [comment] 2021-06-14 21:12
Ahh were these arm32 devices? Sorry

**Comment by godofredoc** [comment] 2021-06-14 21:19
Those are Moto G4, I believe they are arm64

**Comment by mraleph** [comment] 2021-06-14 21:35
You can see the actual ABI in the crash log, it is 32bit ARM

**Comment by rmacnak-google** [comment] 2021-06-14 21:59
Oh, I suspect the profiler is racing with stub code initialization. After the stub code entries were changed to use handles, the check for stub code being initialized could return a false positive between handle allocation and storing into the handle.

**Comment by dnfield** [comment] 2021-06-14 22:29
Another one here: https://storage.googleapis.com/flutter_logs/flutter/3794884fbbac70c94813d787a9dff7114cfe28ce/microbenchmarks/c52ef745-9eba-4c36-b5e0-561aa8cad662/ZY223VMBPX.log

**Comment by zanderso** [comment] 2021-06-20 22:44
Bumping to P2 to surface in triage.

**Comment by chinmaygarde** [comment] 2021-06-21 17:52
In the VM team meeting this morning, Ryan mentioned he is going to be working on a speculative fix.

**Comment by chinmaygarde** [comment] 2021-06-28 17:35
Update from VM team: Ryan understands the problem and is looking into prospective fixes.

**Comment by ghostgzt** [comment] 2021-06-29 02:40
huawei nova6 and lenovo moba also crash 

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4

2.0.6 2.2.2  stable and master ,all crash!

**Comment by chinmaygarde** [comment] 2021-07-12 18:14
Marking this as fixed after https://github.com/dart-lang/sdk/commit/7ebd051a06184069d3e8f97979be454e3af6f8e5.

**Closed by chinmaygarde** 2021-07-12 18:14 UTC
Labels: P2, dependency: dart, engine, passed secondary triage, severe: flake, team: flakes, team: infra
