### ISSUE TITLE
 After installing the Android R  simulator ~ Other versions are normal

### ISSUE THREAD

**Issue by bakboem** [flutter/flutter#53596] opened 2020-03-30 21:02 UTC
```
W/System  ( 8330): A resource failed to call release. 
W/System  ( 8330): A resource failed to call release. 
W/System  ( 8330): A resource failed to call release. 
W/System  ( 8330): A resource failed to call release. 
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/DynamiteModule( 8330): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule( 8330): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
I/DynamiteModule( 8330): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
I/DynamiteLoaderV2( 8330): [71] Googlecertificates
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
I/chatty  ( 8330): uid=10147(net.momonetwork.momonetworkfoodapp) androidmapsapi- identical 1 line
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
I/chatty  ( 8330): uid=10147(net.momonetwork.momonetworkfoodapp) GoogleApiHandle identical 31 lines
W/onetworkfoodap( 8330): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
```

**Comment by VladyslavBondarenko** [comment] 2020-03-31 09:38
Hi @bakboem 
the issue is tracking here https://github.com/flutter/flutter/issues/27095
Please thumb it up and comment there with your case
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you

**Closed by VladyslavBondarenko** 2020-03-31 09:38 UTC
