### ISSUE TITLE
Sent result: SmsManager.RESULT_ERROR_GENERIC_FAILURE

### ISSUE THREAD

**Issue by MuhammadAliKust** [flutter/flutter#64450] opened 2020-08-24 10:58 UTC
Hi,
I am facing this issue when sending sms from my app using SMS plugin:

https://pub.dev/packages/sms

This plugin is working fine for sending short sms from my app. But when I sent long sms i got the following error:

`Sent result: SmsManager.RESULT_ERROR_GENERIC_FAILURE`

I have found solution to this issue on stackoverflow for android:

````
SmsManager.RESULT_ERROR_GENERIC_FAILURE

Most often this error arises when the message too long for 1 SMS. In such situation use this:

ArrayList<String> texts = smsManager.divideMessage(text);
smsManager.sendMultipartTextMessage(phone, null, texts, null, null)
````

So is there any way to implement this in flutter?

Thanks in advance.

**Comment by pedromassangocode** [comment] 2020-08-24 14:05
Hi @MuhammadAliKust 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/babariviere/flutter_sms).
Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-08-24 14:05 UTC

**Comment by MuhammadAliKust** [comment] 2020-08-24 15:26
Thanks @pedromassangocode  for your respond.

But that specific plugin is not accepting issues anymore.
So how can I solve that problem.

**Comment by pedromassangocode** [comment] 2020-08-25 06:06
Hi @MuhammadAliKust 
You can try to contact the author of the plugin. Flutter repository is just for Flutter related issues/feature request
