### ISSUE TITLE
ProcessException: ProcessException: Operation not permitted command gradlew -v

### ISSUE THREAD

**Issue by GULERTOLGA** [flutter/flutter#41486] opened 2019-09-27 16:51 UTC
i can't compile my project on imac with android device due to following error. There is no problem on iOS devices. I can compile same project on windows pc without error.

here is my log file.

## command

flutter run -d LGD85516b53f50

## exception

ProcessException: ProcessException: Operation not permitted
  Command: /Users/tolgaguler/Documents/Tolga.nosynch/git/netigma_mobile/android/gradlew -v

```
#0      runAsync (package:flutter_tools/src/base/process.dart:232:33)
<asynchronous suspension>
#1      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:34)
<asynchronous suspension>
#2      _initializeGradle (package:flutter_tools/src/android/gradle.dart:300:9)
<asynchronous suspension>
#3      _ensureGradle (package:flutter_tools/src/android/gradle.dart:281:37)
<asynchronous suspension>
#4      _readGradleProject (package:flutter_tools/src/android/gradle.dart:192:31)
<asynchronous suspension>
#5      _gradleAppProject (package:flutter_tools/src/android/gradle.dart:112:37)
<asynchronous suspension>
#6      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:106:29)
<asynchronous suspension>
#7      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:164:23)
<asynchronous suspension>
#8      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:359:56)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#32     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#40     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-TR)
    [32m•[39m Flutter version 1.9.1+hotfix.2 at /Users/tolgaguler/flutter
    [32m•[39m Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    [32m•[39m Engine revision b863200c37
    [32m•[39m Dart version 2.5.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/tolgaguler/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.0, Build version 11A420a
    [32m•[39m CocoaPods version 1.7.3

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 38.2.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2019.2.3)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [32m•[39m Flutter plugin version 39.0.5
    [32m•[39m Dart plugin version 192.6603.23

[32m[✓][39m VS Code (version 1.38.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.4.1

[32m[✓][39m Connected device (3 available)
    [32m•[39m LG D855           • LGD85516b53f50                           • android-arm • Android 6.0 (API 23)
    [32m•[39m Tolga iPhone’u    • ecccd20b15c146d0181802d1217d74bb0d4f214b • ios         • iOS 13.1
    [32m•[39m iPhone 11 Pro Max • A8090B9B-1B48-48BE-8CE9-3C7F8AF3B2B0     • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

[32m•[39m No issues found!
```

**Comment by SimiPrambos** [comment] 2019-12-08 13:16
is this issue was resolved?
I found the same problem on my new mac setup.
I was install android studio with java built in installed and nothing problem with flutter doctor..
### Finally
I try to export JAVA_HOME and everything is work fine

**Comment by jonahwilliams** [comment] 2020-03-18 07:29
Duplicate of https://github.com/flutter/flutter/issues/50880

**Closed by jonahwilliams** 2020-03-18 07:29 UTC
Labels: t: gradle, tool, ⌘‬ platform-mac, ▣ platform-android
