### ISSUE TITLE
Run pre-build shell scripts before 'flutter build ...' execution

### ISSUE THREAD

**Issue by alexverbitsky** [flutter/flutter#87117] opened 2021-07-27 16:08 UTC
I faced a necessity to execute few pre-build scripts which should be executed before "flutter build ipa" or "flutter build apk" commands execution.

I added the scripts to "Run configuration" via "Edit configurations" menu. But they aren't being executed when I try to assemble builds using Command Line.

Also I tried to call them by executing gradle tasks, but it seems that gradle tasks are executed too late.

Of course, .sh files can be run manually via command line. But in my case it's crucial to remain build assembling process the same. NPM provides a possibility to declare npm scripts that allow to execute everything before the main build function. So I'm curious whether it's possible to do something similar using Flutter.

Thank you.

<details>
  <summary>Flutter Doctor</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.4 20F71 darwin-x64, locale en-BY)
    • Flutter version 1.22.5 at /Users/username/Library/flutter
    • Framework revision 7891006299 (8 months ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/username/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = /Users/username/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0
```

</details>

**Comment by TahaTesser** [comment] 2021-07-28 08:35
Hi @alexverbitsky 
If you trying from Configuration, you can add shell script to configuration see [this](https://stackoverflow.com/a/65827584)

For more low-level support for `prebuild shell scripts`, as reported in https://github.com/flutter/flutter/issues/9870, it is not supported 

Closing as duplicate of https://github.com/flutter/flutter/issues/25377
Thank you

**Closed by TahaTesser** 2021-07-28 08:35 UTC
Labels: in triage
