### ISSUE TITLE
Scroll bars not appearing in sample application in web browser 

### ISSUE THREAD

**Issue by NTiering** [flutter/flutter#66534] opened 2020-09-24 07:45 UTC
see https://flutter.github.io/samples/web/animations/#/

not scroll bars appear in the browser, making the bottom half of the application un-usable.

browser : Chrome on windows Version 85.0.4183.121 (Official Build) (64-bit) 

<img width="975" alt="Screenshot 2020-09-24 084428" src="https://user-images.githubusercontent.com/1267730/94115907-45c42300-fe42-11ea-9ea6-47a78e723953.png">

**Comment by pedromassangocode** [comment] 2020-09-24 08:39
Hi @NTiering 
Can you please provide your `flutter doctor -v`, and a minimal complete reproducible code sample?
Thank you

**Comment by NTiering** [comment] 2020-09-24 08:44
I just looked at the sample at
 https://flutter.github.io/samples/web/animations/#/

**Comment by pedromassangocode** [comment] 2020-09-24 11:56
Hi @NTiering 
From what I can see, the issue is related to a Flutter Examples repository rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/flutter/samples/issues).

The code of this webpage is located at https://github.com/flutter/samples/blob/master/animations/lib/main.dart and by looking at the code there is no [Scrollbar](https://api.flutter.dev/flutter/material/Scrollbar-class.html) widget in the code and that is why the scrollbar does not appear on the webpage.

The webpage is scrollable without a scrollbar so I'm not sure what this issue is about.

![gif](https://user-images.githubusercontent.com/67424416/94141624-ef1c1080-fe64-11ea-8233-8533bd4ee356.gif)

Closing, as this isn't an issue with Flutter itself.  
If you disagree, please write in the comments,  
providing your `flutter doctor -v`, your `flutter run -v`,  your `pubspec.yaml`
a minimal reproducible code sample that does not use 3rd party plugins,  
and I will reopen it.
Thank you

**Closed by pedromassangocode** 2020-09-24 11:56 UTC
Labels: in triage
