### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by KentMT28** [flutter/flutter#146129] opened 2024-04-02 13:58 UTC
## Command
```
flutter create --template app --overwrite .
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: The system cannot find the file specified.
, errno = 2
```
#0      _Directory.createSync (dart:io/directory_impl.dart:124:7)
#1      _File.createSync (dart:io/file_impl.dart:303:14)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:26:16)
#3      ErrorHandlingFile.createSync.<anonymous closure> (package:flutter_tools/src/base/error_handling_io.dart:282:22)
#4      _runSync (package:flutter_tools/src/base/error_handling_io.dart:587:14)
#5      ErrorHandlingFile.createSync (package:flutter_tools/src/base/error_handling_io.dart:281:5)
#6      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:321:28)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#8      Template.render (package:flutter_tools/src/template.dart:281:24)
#9      CreateBase.renderMerged (package:flutter_tools/src/commands/create_base.dart:483:21)
<asynchronous suspension>
#10     CreateBase.generateApp (package:flutter_tools/src/commands/create_base.dart:506:23)
<asynchronous suspension>
#11     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:361:31)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#14     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
```
```
[✓] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.22631.3374], locale en-US)
    • Flutter version 3.19.4 on channel stable at C:\flutter_windows_3.19.4-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (13 days ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\featu\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.5.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.5.33516.290
    • Windows 10 SDK version 10.0.22000.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code (version 1.87.2)
    • VS Code at C:\Users\featu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.84.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3374]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 123.0.6312.86
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 123.0.2420.65

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by huycozy** [comment] 2024-04-03 05:38
Closing this as a duplicate of https://github.com/flutter/flutter/issues/142537.

**Closed by huycozy** 2024-04-03 05:38 UTC
Labels: in triage
