### ISSUE TITLE
The issue of PageView and AutomaticKeepAliveClientMixin under the release version

### ISSUE THREAD

**Issue by fly512** [flutter/flutter#17328] opened 2018-05-05 13:58 UTC
I wrote a simple page using PageView and AutomaticKeepAliveClientMixin, which contains 4 page, A, B, C, D, and when App starts a meeting, the user points to D first, then tap B or C， and it can't be displayed on B or C. It can be concluded that when App starts, if you click on the Tab behind, the front will not appear.

```
[√] Flutter (Channel unknown, v0.3.5, on Microsoft Windows [Version 10.0.16299.371], locale zh-CN)
    • Flutter version 0.3.5 at D:\flutter
    • Framework revision 7ffcd3d22d (11 days ago), 2018-04-24 14:03:41 -0700
    • Engine revision ec611470b5
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\android\android-sdk-windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\android\android-sdk-windows
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.1
    • Flutter plugin version 24.1.2
    • Dart plugin version 181.4668.60

[√] VS Code, 32-bit edition (version 1.22.2)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Dart Code extension version 2.12.1

[√] Connected devices (1 available)
    • vivo Y75A • 5SUWWCDQPNZSOFSO • android-arm64 • Android 7.1.1 (API 25)
```
```
[ +150 ms] I/flutter ( 4500): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +36 ms] I/flutter ( 4500): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
[   +2 ms] I/flutter ( 4500): 'package:flutter/src/rendering/object.dart': Failed assertion: line 2732 pos 14:
[   +3 ms] I/flutter ( 4500): '_debugUltimatePreviousSiblingOf(after, equals: _firstChild)': is not true.
[ +481 ms] I/flutter ( 4500): Either the assertion indicates an error in the framework itself, or we should provide substantially
[   +1 ms] I/flutter ( 4500): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 4500): In either case, please report this assertion by filing a bug on GitHub:
[   +1 ms] I/flutter ( 4500):   https://github.com/flutter/flutter/issues/new
[   +6 ms] I/flutter ( 4500): When the exception was thrown, this was the stack:
[  +72 ms] I/flutter ( 4500): #2      RenderSliver&ContainerRenderObjectMixin._insertIntoChildList (package:flutter/src/rendering/object.dart:2732:14)
[   +2 ms] I/flutter ( 4500): #3      RenderSliver&ContainerRenderObjectMixin.insert (package:flutter/src/rendering/object.dart:2766:5)
[        ] I/flutter ( 4500): #4      RenderSliverMultiBoxAdaptor.insert (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:209:17)
[        ] I/flutter ( 4500): #5      SliverMultiBoxAdaptorElement.insertChildRenderObject (package:flutter/src/widgets/sliver.dart:863:18)
[   +1 ms] I/flutter ( 4500): #6      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:4505:35)
[        ] I/flutter ( 4500): #7      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4271:5)
[        ] I/flutter ( 4500): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4645:16)
[   +1 ms] I/flutter ( 4500): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[   +2 ms] I/flutter ( 4500): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] I/flutter ( 4500): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[   +1 ms] I/flutter ( 4500): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[   +4 ms] I/flutter ( 4500): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
[   +2 ms] I/flutter ( 4500): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
[        ] I/flutter ( 4500): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[        ] I/flutter ( 4500): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[   +2 ms] I/flutter ( 4500): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] I/flutter ( 4500): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
[   +2 ms] I/flutter ( 4500): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
[        ] I/flutter ( 4500): #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3947:16)
[        ] I/flutter ( 4500): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[   +2 ms] I/flutter ( 4500): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[   +3 ms] I/flutter ( 4500): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] I/flutter ( 4500): #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
[   +2 ms] I/flutter ( 4500): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:22)
[        ] I/flutter ( 4500): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
[        ] I/flutter ( 4500): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
[   +2 ms] I/flutter ( 4500): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
[        ] I/flutter ( 4500): #31     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:744:47)
[        ] I/flutter ( 4500): #32     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:702:34)
[   +2 ms] I/flutter ( 4500): #33     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:671:7)
[        ] I/flutter ( 4500): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #35     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4371:32)
[   +1 ms] I/flutter ( 4500): #36     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4761:17)
[        ] I/flutter ( 4500): #37     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:187:17)
[        ] I/flutter ( 4500): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +1 ms] I/flutter ( 4500): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[   +1 ms] I/flutter ( 4500): #41     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
[        ] I/flutter ( 4500): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
[   +2 ms] I/flutter ( 4500): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
[        ] I/flutter ( 4500): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +4 ms] I/flutter ( 4500): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
[        ] I/flutter ( 4500): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
[   +1 ms] I/flutter ( 4500): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[   +2 ms] I/flutter ( 4500): #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
[        ] I/flutter ( 4500): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
[        ] I/flutter ( 4500): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +1 ms] I/flutter ( 4500): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] I/flutter ( 4500): #59     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
[        ] I/flutter ( 4500): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +2 ms] I/flutter ( 4500): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] I/flutter ( 4500): #63     StatelessElement.update (package:flutter/src/widgets/framework.dart:3694:5)
[        ] I/flutter ( 4500): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +1 ms] I/flutter ( 4500): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] I/flutter ( 4500): #67     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
[        ] I/flutter ( 4500): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[   +1 ms] I/flutter ( 4500): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[   +1 ms] I/flutter ( 4500): #71     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
[        ] I/flutter ( 4500): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +2 ms] I/flutter ( 4500): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[   +1 ms] I/flutter ( 4500): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] I/flutter ( 4500): #75     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
[        ] I/flutter ( 4500): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +3 ms] I/flutter ( 4500): #77     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4371:32)
[        ] I/flutter ( 4500): #78     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4761:17)
[        ] I/flutter ( 4500): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] I/flutter ( 4500): #82     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
[   +1 ms] I/flutter ( 4500): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] I/flutter ( 4500): #86     ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
[        ] I/flutter ( 4500): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[   +1 ms] I/flutter ( 4500): #90     StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
[        ] I/flutter ( 4500): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
[        ] I/flutter ( 4500): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[   +1 ms] I/flutter ( 4500): #96     StatelessElement.update (package:flutter/src/widgets/framework.dart:3694:5)
[        ] I/flutter ( 4500): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #98     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4653:14)
[        ] I/flutter ( 4500): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +1 ms] I/flutter ( 4500): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[   +1 ms] I/flutter ( 4500): #102    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
[        ] I/flutter ( 4500): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[   +7 ms] I/flutter ( 4500): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[   +2 ms] I/flutter ( 4500): #106    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
[        ] I/flutter ( 4500): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +2 ms] I/flutter ( 4500): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[   +2 ms] I/flutter ( 4500): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[   +1 ms] I/flutter ( 4500): #110    ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
[        ] I/flutter ( 4500): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +2 ms] I/flutter ( 4500): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] I/flutter ( 4500): #114    ProxyElement.update (package:flutter/src/widgets/framework.dart:3901:5)
[        ] I/flutter ( 4500): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[   +1 ms] I/flutter ( 4500): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[   +3 ms] I/flutter ( 4500): #118    StatefulElement.update (package:flutter/src/widgets/framework.dart:3791:5)
[        ] I/flutter ( 4500): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2691:15)
[        ] I/flutter ( 4500): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
[        ] I/flutter ( 4500): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
[        ] I/flutter ( 4500): #122    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2234:33)
[        ] I/flutter ( 4500): #123    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:626:20)
[        ] I/flutter ( 4500): #124    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
[        ] I/flutter ( 4500): #125    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
[        ] I/flutter ( 4500): #126    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
[        ] I/flutter ( 4500): #127    BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
[        ] I/flutter ( 4500): #128    _invoke (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:120)
[        ] I/flutter ( 4500): #129    _drawFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:109)
```

```
import 'package:flutter/material.dart';

void main() => runApp(new MyApp());

class TabItem {
	const TabItem({this.title, this.icon});
	final String title;
	final IconData icon;
}

const List<TabItem> tabItems = const <TabItem>[
	const TabItem(title: 'A', icon: Icons.pages),
	const TabItem(title: 'B', icon: Icons.pages),
	const TabItem(title: 'C', icon: Icons.pages),
	const TabItem(title: 'D', icon: Icons.pages),
];

class MyApp extends StatelessWidget {
	@override
	Widget build(BuildContext context) {
		return new MaterialApp(
			title: 'Flutter Demo',
			theme: new ThemeData(
				primarySwatch: Colors.blue,
			),
			home: new MyHomePage(title: 'Flutter Demo Home Page'),
		);
	}
}

class MyHomePage extends StatefulWidget {
	MyHomePage({Key key, this.title}) : super(key: key);
	final String title;
	
	@override
	_MyHomePageState createState() => new _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
	PageController _tabController;
	int _getIndex(){
		return this._tabController.hasClients ? this._tabController.page.toInt() : 0;
	}
	
	@override
	void initState() {
		super.initState();
		this._tabController = new PageController(keepPage: true);
		this._tabController.addListener(this._onTabIndexChanged);
	}
	
	@override
	void dispose() {
		this._tabController.removeListener(this._onTabIndexChanged);
		this._tabController.dispose();
		super.dispose();
	}
	
	void _onTabItemClick(int index){
		this._goPage(index);
	}
	
	void _goPage(int index){
		this._tabController.jumpToPage(index);
	}
	
	void _onTabIndexChanged(){
		setState((){
		
		});
	}
	
	@override
	Widget build(BuildContext context) {
		int page = this._getIndex();
		return new Scaffold(
			appBar: new AppBar(
				title: new Text(widget.title),
			),
			bottomNavigationBar: new BottomNavigationBar(
				items: tabItems.map((TabItem item) {
					return new BottomNavigationBarItem(
						title: new Text(item.title),
						icon: new Icon(item.icon),
					);
				}).toList(),
				onTap: this._onTabItemClick,
				currentIndex: page,
				type: BottomNavigationBarType.fixed,
			),
			body: new PageView(
				physics: const NeverScrollableScrollPhysics(),
				controller: this._tabController,
				children: <Widget>[
					new PageA(),
					new PageB(),
					new PageC(),
					new PageD(),
				],
			)
		
		);
	}
}

class PageA extends StatefulWidget {
	PageA({Key key}) : super(key: key);
	
	@override
	_PageAState createState() => new _PageAState();
}

class _PageAState extends State<PageA> with AutomaticKeepAliveClientMixin<PageA> {
	@override
	bool get wantKeepAlive{
		return true;
	}
	@override
	Widget build(BuildContext context) {
		super.build(context);
		return new Center(
			child: new Text("A"),
		);
	}
}

class PageB extends StatefulWidget {
	PageB({Key key}) : super(key: key);
	
	@override
	_PageBState createState() => new _PageBState();
}

class _PageBState extends State<PageB> with AutomaticKeepAliveClientMixin<PageB> {
	@override
	bool get wantKeepAlive{
		return true;
	}
	@override
	Widget build(BuildContext context) {
		super.build(context);
		return new Center(
			child: new Text("B"),
		);
	}
}

class PageC extends StatefulWidget {
	PageC({Key key}) : super(key: key);
	
	@override
	_PageCState createState() => new _PageCState();
}

class _PageCState extends State<PageC> with AutomaticKeepAliveClientMixin<PageC> {
	@override
	bool get wantKeepAlive{
		return true;
	}
	@override
	Widget build(BuildContext context) {
		super.build(context);
		return new Center(
			child: new Text("C"),
		);
	}
}

class PageD extends StatefulWidget {
	PageD({Key key}) : super(key: key);
	
	@override
	_PageDState createState() => new _PageDState();
}

class _PageDState extends State<PageD> with AutomaticKeepAliveClientMixin<PageD> {
	@override
	bool get wantKeepAlive{
		return true;
	}
	@override
	Widget build(BuildContext context) {
		super.build(context);
		return new Center(
			child: new Text("D"),
		);
	}
}
```

**Comment by Hixie** [comment] 2018-06-12 22:30
Duplicate of https://github.com/flutter/flutter/issues/11895.

**Closed by Hixie** 2018-06-12 22:30 UTC
