### ISSUE TITLE
Preoad  for  pageview

### ISSUE THREAD

**Issue by 2372281891** [flutter/flutter#79184] opened 2021-03-27 04:50 UTC
Please update this  function

**Comment by iapicca** [comment] 2021-03-27 05:27
duplicate of https://github.com/flutter/flutter/issues/31191

**Comment by darshankawar** [comment] 2021-03-29 08:40
Closing this as duplicate of https://github.com/flutter/flutter/issues/31191

**Closed by darshankawar** 2021-03-29 08:40 UTC
Labels: in triage
