### ISSUE TITLE
DateRangePicker shows reverse date range when specifying more days between firstDate & lastDate than the previous number of days in the present month 

### ISSUE THREAD

**Issue by MiltoxBeyond** [flutter/flutter#68784] opened 2020-10-22 14:32 UTC
I created a simple prototype for work to show the benefits of flutter but I did notice the dateRangePicker is opening up to the wrong dates.  

```
                              onTap: () async { 
                                    var result = await showDateRangePicker(
                                      context: context, 
                                      firstDate: DateTime.now().subtract(Duration(days:60)), 
                                      lastDate: DateTime.now(),
                                      initialEntryMode: DatePickerEntryMode.calendar,
                                      currentDate: DateTime.now(),
                                      initialDateRange: DateTimeRange(
                                        start: DateTime.now(), 
                                        end: DateTime.now()
                                      ),
                                    );
                                 }
```

This creates the dialog and modifying the initial range and first/last dates does everything as expected, except when it opens the dialog shows the first months closest to firstDate.  It's fine with a few months but at first I set the firstDate to 10 years in the past, and that was quite the scroll to get to the current date:
<div align="center">
<img src="https://user-images.githubusercontent.com/7705397/96886114-448e1200-1451-11eb-84af-59e166a9fd3b.png"
         data-canonical="https://user-images.githubusercontent.com/7705397/96886114-448e1200-1451-11eb-84af-
59e166a9fd3b.png" width="300" />
</div>

**Comment by TahaTesser** [comment] 2020-10-22 16:13
Hi @MiltoxBeyond 
Can you please provide your `flutter doctor -v` your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by MiltoxBeyond** [comment] 2020-10-26 14:38
Sorry wasn't notified for some reason that I got a reply.

Here's my `flutter doctor -v`

```
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19042.608], locale en-US)
    • Flutter version 1.22.2 at C:\work\flutter
    • Framework revision 84f3d28555 (11 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\Android\android-sdk\
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = E:\Android\android-sdk\
    • Java binary at: E:\Android\studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at E:\Android\studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\mzuri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by MiltoxBeyond** [comment] 2020-10-26 15:33
I found something out today as well.  It's only if the initial date range is a single day selected and is also equal to the last date.

**Comment by TahaTesser** [comment] 2020-10-27 08:03
Hi @MiltoxBeyond 
Thanks for filing the issue, I can reproduce with `showDateRangePicker`

Order is reversed when specifying more days than previous days from the same day 
### Here we have 27 previous days from he same month, if i specify previous 25 days in the  `firstDate: DateTime.now().subtract(Duration(days: 25)),`, It works as expected
![Simulator Screen Shot - iPhone 12 - 2020-10-27 at 13 03 08](https://user-images.githubusercontent.com/48603081/97270218-cff21380-1854-11eb-9240-044d5181d2e9.png)

### Here we have 27 previous days from he same month, if i specify previous 27 days in the `firstDate: DateTime.now().subtract(Duration(days: 30)),`, Now order is reversed
![Simulator Screen Shot - iPhone 12 - 2020-10-27 at 13 01 29](https://user-images.githubusercontent.com/48603081/97270313-f87a0d80-1854-11eb-8ef4-9aa3803f714e.png)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.2 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 84f3d28555 (11 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios • iOS 14.1
    • iPhone 12 (mobile)   • BAFAB765-173F-4B78-93AC-F6FB6E6783C3 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1
      (simulator)

! Doctor found issues in 1 category.
```

</details> 

### However this seems to be fixed in `beta` and as well as `master`
![Simulator Screen Shot - iPhone 12 - 2020-10-27 at 13 16 31](https://user-images.githubusercontent.com/48603081/97271821-12b4eb00-1857-11eb-909d-e6afcdf6f86b.png)


I cannot reproduce this issue on the latest `beta` channel.
Can you please upgrade to the latest  `beta` and try again
`flutter channel beta`
`flutter upgrade --force`
`flutter doctor -v`

**Comment by MiltoxBeyond** [comment] 2020-10-27 09:21
Confirmed it is definitely fixed in the beta.. Althought the styles are different for inputs when readonly.  The underline is required by my boss because they like to know the textformfield is clickable.  I'll have to mess around to see if this version is usable for us, if not I'll use the workaround I had figured which was to set the date range from now() - 1 day to now().
```
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19042.608], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\work\flutter
    • Framework revision 198df796aa (12 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\Android\android-sdk\
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = E:\Android\android-sdk\
    • Java binary at: E:\Android\studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at E:\Android\studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.1)
    • Flutter extension version 3.15.1

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 86.0.4240.111
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 86.0.622.51

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-10-28 07:38
Hi @MiltoxBeyond 
Maybe I am missing something but I don't see readonly param in `showDateRangePicker` 

Can you please provide d a complete reproducible minimal code sample and screenshots to compare 
Thank you

**Comment by MiltoxBeyond** [comment] 2020-10-29 00:40
Sorry readonly is a property for TextFormField. The problem I had was actually just a change of style on the TextFormField.  The styles made the input look bigger so I had to expand the container a bit to fit it in, since the customer wanted the field specifically in the appbar.  It's a non-issue. Thank you for your help.

Just to reiterate: Confirmed to be fixed in the Beta version.

**Comment by TahaTesser** [comment] 2020-10-29 07:04
This is fixed on beta and other channels, except stable 
A complete reproduction of the issue is  here https://github.com/flutter/flutter/issues/68784#issuecomment-717061982
Labeling it further to track fix for this to the stable channel

**Comment by TahaTesser** [comment] 2020-11-12 14:20
CC @pcsosinski

**Comment by maheshmnj** [comment] 2022-12-01 06:16
Hi @MiltoxBeyond, I tried to reproduce the issue and it seems to work fine. 


```
  var result = await showDateRangePicker(
            context: context,
            firstDate: DateTime.now().subtract(const Duration(days: 2)),
            lastDate: DateTime.now(),
            initialEntryMode: DatePickerEntryMode.calendar,
            currentDate: DateTime.now(), // 1 December as the current Date
            initialDateRange:
                DateTimeRange(start: DateTime.now(), end: DateTime.now()),
          );
```

<img width="324" alt="image" src="https://user-images.githubusercontent.com/31410839/204979033-72947bbf-db8c-46ad-b382-268725f3bbaa.png">


<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.6.0-6.0.pre.33, on macOS 12.6 21G115 darwin-arm64,
    locale en-IN)
    • Flutter version 3.6.0-6.0.pre.33 on channel master at
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a9858ec524 (72 minutes ago), 2022-11-21 10:58:11 -0500
    • Engine revision 46a6b54295
    • Dart version 2.19.0 (build 2.19.0-406.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however it is
      recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64
      • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript
      • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

Closing since this is not reproducible, In case you still encounter this issue. Please feel free to comment on this issue with more details and we will reopen it.

**Closed by maheshmnj** 2022-12-01 06:16 UTC
Labels: framework, f: material design, f: date/time picker, has reproducible steps, found in release: 1.22
