### ISSUE TITLE
Establish earlier testing in Flutter, Fuchsia trees to catch breaking changes

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#43831] opened 2019-10-30 18:09 UTC
Action item from postmortem123362 (Flutter-Fuchsia rolls failed for 20 days); identify avenues for presubmit tests across Flutter and Fuchsia to detect breaking changes before they occur. Needs work on both the Fuchsia and Flutter teams.

cc @Hixie, to whom the item is assigned to delegate, and @iskakaushik for the Fuchsia components specifically.

**Comment by iskakaushik** [comment] 2020-02-14 21:21
duplicate of https://github.com/flutter/flutter/issues/44826

**Closed by iskakaushik** 2020-02-14 21:21 UTC
Labels: customer: fuchsia, dependency: fuchsia, team, team: infra
