### ISSUE TITLE
Issue with background isolate when obfuscating Android APK / AppBundle

### ISSUE THREAD

**Issue by sarbagyastha** [flutter/flutter#98475] opened 2022-02-15 07:05 UTC
The background message arrives when `obfuscate` flag is not used. Seems like this is some kind of issue related to background isolate when obfuscating code.

## Steps to Reproduce
1. Clone the project from `https://github.com/sarbagyastha/obfuscate`
2. Generate an APK with `flutter build apk --release --verbose --obfuscate --split-debug-info=test/symbols` 
3. Put the app in background.
3. Grab the push token from console and send push notification with following payload:
```json
{
    "data": {
        "title": "Test Title",
        "body": "Test Body",
        "type": "promotion"
    },
    "mutable_content": true,
    "content_available": true,
    "priority": "high",
    "registration_ids": [
        "<push-token>"
    ]
}
```

**Expected results:** 
We should see a `Push Message` payload in console for the background message.

**Actual results:**
We see nothing but, these logs.
![image](https://user-images.githubusercontent.com/9782008/154009387-ba1ebc9c-9b09-4d2f-a9d3-695a9aa2bfbb.png)

<details>
  <summary>Flutter Doctor</summary>
```

[✓] Flutter (Channel stable, 2.10.1, on Ubuntu 21.10 5.13.0-28-generic, locale en_US.UTF-8)
    • Flutter version 2.10.1 at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at ...
    • Platform android-Tiramisu, build-tools 32.1.0-rc1
    • ANDROID_HOME = ...
    • Java binary at:
      6777.52.2113.8156070/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

 Android Studio at ...
    • Flutter plugin installed
    • Dart plugin version 212.5632
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.64.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.34.0

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12
      (API 32) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google
      Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

```
</details>

**Comment by darshankawar** [comment] 2022-02-15 09:24
@sarbagyastha 
Since your code sample involves `firebase_messaging` which is 3rd party, can you replicate this behavior without using it ?
If it has to have the plugin, then it may need to open in dedicated repo: https://github.com/FirebaseExtended/flutterfire/issues

**Comment by sarbagyastha** [comment] 2022-02-15 09:36
@darshankawar Since the issue exists only when using `--obfuscate`, I think it's more of a Flutter side issue. Also the same version of `firebase_messaging` was working perfectly fine before `Flutter 2.10.0`.

**Comment by sarbagyastha** [comment] 2022-02-15 14:32
@darshankawar I'm not so familiar with the workings behind background isolate, in order to recreate reproducible example from scratch. 

Can you mention someone from Flutter or Dart team who might be able to understand the issue?

As this is a serious bug, if it is from Flutter or Dart side.

**Comment by darshankawar** [comment] 2022-02-16 06:49
Using the app clone provided and and obfuscating the android apk using `flutter build apk --release --verbose --obfuscate --split-debug-info=test/symbols` and then trying to push a notification when app is in background does show the same behavior as reported and see below:

`Service has not yet started, message will be queued`.

I am going to keep this open and label it for further insights from the team on this particular behavior using `--obfuscate` and without using `--obfuscate` flag.

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 2.10.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.10.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (5 days ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[✓] Flutter (Channel master, 2.11.0-0.0.pre.581, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.11.0-0.0.pre.581 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2097fe64f0 (37 minutes ago), 2022-02-16 06:20:22 +0200
    • Engine revision 4ea2394b8d
    • Dart version 2.17.0 (build 2.17.0-105.0.dev)
    • DevTools version 2.10.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>

**Comment by i10416** [comment] 2022-02-19 14:34
Hello, I encountered similar issue on  API 29 device and API 30, 31 emulators.

```sh
[√] Flutter (Channel beta, 2.11.0-0.1.pre, on Microsoft Windows [Version 10.0.22543.1000], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.1)
[√] Android Studio (version 2021.1)
```

My app which uses background isolate does not work well when using `obfuscate` flag in combination with release build. Without obfuscate flag, release build works as I expect.

**Comment by chinmaygarde** [comment] 2022-02-22 22:45
cc @stuartmorgan

**Comment by stuartmorgan** [comment] 2022-02-23 20:22
It looks like that plugin is using Dart entrypoints, which would make this a duplicate of https://github.com/dart-lang/sdk/issues/44215

**Closed by stuartmorgan** 2022-02-23 20:22 UTC
Labels: platform-android, tool, engine, dependency: dart, a: build, has reproducible steps, P4, found in release: 2.10, found in release: 2.11

**Comment by svarup** [comment] 2022-03-13 13:31
Having same issue, foreground notification working but Background notification stop working if we build using --obfuscate and --split-debug-info param
