### ISSUE TITLE
[camera] Support custom frame rate and bit rate

### ISSUE THREAD

**Issue by chethanprabhakar** [flutter/flutter#54339] opened 2020-04-09 06:09 UTC
Hello,

I am using the Camera plugin. Need help in setting custom FPS/frame rate for video. Also, can't find what is the default setting for frame rate

Possible to suggest a fix?

Thanks,

**Comment by VladyslavBondarenko** [comment] 2020-04-09 07:19
Related to https://github.com/flutter/flutter/issues/26959

**Comment by jpiabrantes** [comment] 2020-09-09 16:54
Is this feature on flutter's roadmap?

**Comment by julien-tamade** [comment] 2020-12-08 16:27
+1 on this. Any Update?

**Comment by jordanhart** [comment] 2021-01-06 21:00
+1

**Comment by amhwu** [comment] 2021-03-29 10:12
+1 on this.

**Comment by hxtruong6** [comment] 2021-07-05 03:37
+1 to on this too

**Comment by Enigma-I-am** [comment] 2021-08-04 12:45
Any updates on this?

**Comment by isabel5207** [comment] 2021-09-24 09:13
+1 on this

**Comment by pinball83** [comment] 2021-10-03 17:54
+1 please fix needed

**Comment by roman800** [comment] 2021-12-06 11:15
+1

**Comment by Dahlbom** [comment] 2021-12-06 11:19
+1

**Comment by Wiki1991** [comment] 2022-01-04 03:31
+1

**Comment by lucalazzaroni** [comment] 2022-01-29 10:16
+1

**Comment by andre-oshiro** [comment] 2022-02-09 05:24
+1

**Comment by farqis** [comment] 2022-02-24 11:14
+1

**Comment by Joshua27** [comment] 2022-02-28 16:44
+1

**Comment by mx1up** [comment] 2022-03-01 13:11
https://github.com/flutter/flutter/wiki/Issue-hygiene

**Comment by dhuma1981** [comment] 2022-03-21 11:26
+1

**Comment by AlexsandroZanella2** [comment] 2022-03-29 12:25
+1

**Comment by boomer30** [comment] 2022-04-11 13:40
+1

**Comment by rbennett-v1** [comment] 2022-04-11 13:53
+1

**Comment by II11II** [comment] 2022-08-25 10:06
For now, you can use temporary solution in case of your waiting this feature in camera plugin or do not want implement it by your self.

Temporary solution:
**1. Record the video from camera
2. After recodring, you can change bit rate of the video by this [plugin](https://github.com/tanersener/ffmpeg-kit)** 

P.s. It can straightforward solution to your problem but some  usecases can be applicable

**Comment by G2G2G2G** [comment] 2022-10-16 21:57
Sadly re-encoding a video with ffmpeg is a poor work around. Hardware cameras support certain resolutions and their hardware encoding will do it while recording. Re-encoding is quite a bit different and the average user won't even know what they are doing either.

**Comment by DrJMB-Coder** [comment] 2023-03-20 10:39
Is there any update on when this functionality will be introduced? I already use FFmpeg in my app, the problem is I need the higher frame rate during capture, to prevent motion blur.

The only solution I see right now is to make the app separately for Android and IOS and use othe plugins e.g.

https://github.com/android/camera-samples/tree/main/Camera2SlowMotion

or is there a way to call this in flutter?

**Comment by stuartmorgan** [comment] 2023-03-20 17:37
> I'm going to lobby a bit to reprioritize this a bit higher

[Please read https://github.com/flutter/flutter/issues/54339#issuecomment-1476584606](https://github.com/flutter/flutter/wiki/Issue-hygiene#escalating-an-issue-that-has-the-wrong-priority)

> it isn't very often that addressing an issue will both (a) improve UX for the end user, and (b) save the developing company money. That's the case here.

If there are companies who believe they could improve their application and save money with this feature, I would certainly encourage those companies to consider investing in implementing it; doing so is by far the most effective way to shorten the timeline for this issue.

**Comment by charlesluzar** [comment] 2023-03-20 17:47
> If there are companies who believe they could improve their application and save money with this feature, I would certainly encourage those companies to consider investing in implementing it; doing so is by far the most effective way to shorten the timeline for this issue.

Apologies on the issue hygiene thing, I don't chime in on these much and am not intimately familiar w/ the rules as of yet. Would be happy to invest some time into submitting this feature. Is there anyone that could give me/my team some guidance on how to accomplish that effectively?

**Comment by stuartmorgan** [comment] 2023-03-21 00:22
https://github.com/flutter/packages/blob/main/CONTRIBUTING.md has links to all of our resources about getting started with contributing to plugins, including (in the main contributor guide linked from there) the Discord server used for development discussions.

**Comment by boomer30** [comment] 2023-03-24 21:13
We desperately want to see this feature as well as the ability to control other camera configurations such as: exposure, shutter speed, ISO, and key frame interval.

**Comment by cassioso** [comment] 2023-04-06 16:59
> @stuartmorgan Thank you! Someone from our team is working on this. Whether we'll be able to navigate getting a PR merged remains to be seen but we'll try!

Maybe you want to share the PR (even if still a draft) so others can contribute

**Comment by charlesluzar** [comment] 2023-04-07 17:38
@cassioso See below...

- https://github.com/flutter/packages/pull/3586
- https://github.com/flutter/packages/pull/3615
- https://github.com/flutter/packages/pull/3616

**Comment by nguyenlaai9** [comment] 2023-05-16 08:04
> @cassioso See below...
> 
> * [[camera] MediaSettings parameter for createCameraWithSettings packages#3586](https://github.com/flutter/packages/pull/3586)
> * [[camera] CameraPlatform.createCameraWithSettings packages#3615](https://github.com/flutter/packages/pull/3615)
> * [[camera] Fix to camera_android_camerax camera_test.dart packages#3616](https://github.com/flutter/packages/pull/3616)

hi @darshankawar run faild 
![image](https://github.com/flutter/flutter/assets/24228885/903fa474-6a84-4f1d-b564-d18ed901fec7)

**Comment by oakleychen0707** [comment] 2023-09-29 17:43
Hello,
I am using the Flutter camera package to create a video recording application that allows for adjusting the resolution and frame rates to 60fps and 120fps. Please note that this feature is currently available only on iOS.

[](https://github.com/oakleychen0707/flutter_camera_60fps_ios.git)

Hope this helps everyone! Thank you.

**Comment by stuartmorgan** [comment] 2024-01-21 11:11
> Why was this comment marked as abuse? He is not offending anyone, he is respectfully challenging the [the proposed workaround](https://github.com/flutter/flutter/issues/54339#issuecomment-1227054249) by remarking the very real downsides of it.

The process of banning a user from the organization automatically marks all of their comments in the organization as abuse. This can result in comments that are individually non-problematic having that message.

(In the future, please use Discord, rather than the issue tracker, for meta-discussions that are not about the issue itself.)

**Comment by chaoyifei** [comment] 2024-04-16 12:26
@how to use in camera

**Closed** 2024-05-06 14:41 UTC
Labels: c: new feature, customer: crowd, p: camera, package, c: proposal, team-ecosystem, P3, triaged-ecosystem
