### ISSUE TITLE
[tool_crash] WebDriverException

### ISSUE THREAD

**Issue by RanenduKarmakar1997** [flutter/flutter#137686] opened 2023-11-01 11:31 UTC
## Command
```
flutter driver --driver=test/integration_driver/integration_test_driver.dart --target=test/integration_test/auth_test.dart -d chrome --web-port=4444 --browser-name=chrome --screenshot=test_report --profile-memory=profile_memory.json
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WebDriverException
```
#0      InferSessionHandler.parseCreateResponse (package:webdriver/src/handler/infer_handler.dart:94:7)
#1      AsyncRequestClient.send (package:webdriver/src/common/request_client.dart:96:32)
<asynchronous suspension>
#2      createDriver (package:webdriver/async_core.dart:64:19)
<asynchronous suspension>
#3      WebDriverService.startTest (package:flutter_tools/src/drive/web_driver_service.dart:145:19)
<asynchronous suspension>
#4      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:309:30)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
```
```
[32m[✓][39m Flutter (Channel stable, 3.7.10, on Ubuntu 22.04.3 LTS 6.2.0-36-generic, locale en_US.UTF-8)
    [32m•[39m Flutter version 3.7.10 on channel stable at /home/cloudcraftz/snap/flutter/common/flutter
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision 4b12645012 (7 months ago), 2023-04-03 17:46:48 -0700
    [32m•[39m Engine revision ec975089ac
    [32m•[39m Dart version 2.19.6
    [32m•[39m DevTools version 2.20.1

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    [32m•[39m Android SDK at /home/cloudcraftz/Android/Sdk
    [32m•[39m Platform android-33, build-tools 33.0.0
    [32m•[39m Java binary at: /snap/android-studio/128/android-studio/jbr/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Linux toolchain - develop for Linux desktop
    [32m•[39m clang version 10.0.0-4ubuntu1
    [32m•[39m cmake version 3.16.3
    [32m•[39m ninja version 1.10.0
    [32m•[39m pkg-config version 0.29.1

[32m[✓][39m Android Studio (version 2022.3)
    [32m•[39m Android Studio at /snap/android-studio/128/android-studio
    [32m•[39m Flutter plugin version 75.1.2
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2023.2)
    [32m•[39m IntelliJ at /snap/intellij-idea-community/464
    [32m•[39m Flutter plugin version 75.1.4
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[32m[✓][39m VS Code
    [32m•[39m VS Code at /snap/code/current
    [32m•[39m Flutter extension version 3.74.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Linux (desktop) • linux  • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-36-generic
    [32m•[39m Chrome (web)    • chrome • web-javascript • Google Chrome 118.0.5993.117

[32m[✓][39m HTTP Host Availability
    [32m•[39m All required HTTP hosts are available

[32m•[39m No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 6.09.2023+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e3c29ec00c9c825c891d75054c63fcc46454dca1
### Plugins
cloud_firestore-4.9.3
cloud_firestore_web-3.7.2
firebase_analytics-10.5.1
firebase_analytics_web-0.5.5+1
firebase_core-2.17.0
firebase_core_web-2.8.0
firebase_crashlytics-3.3.7
firebase_messaging-14.6.9
firebase_messaging_web-3.5.8
firebase_storage-11.2.8
firebase_storage_web-3.6.8
flutter_local_notifications-14.1.4
integration_test
path_provider-2.1.1
path_provider_android-2.2.0
path_provider_foundation-2.3.1
path_provider_linux-2.2.1
path_provider_windows-2.2.1
printing-5.10.4
share-2.0.4
url_launcher-6.1.11
url_launcher_android-6.1.0
url_launcher_ios-6.1.5
url_launcher_linux-3.0.6
url_launcher_macos-3.0.7
url_launcher_web-2.0.19
url_launcher_windows-3.0.8
webview_flutter-2.8.0
webview_flutter_android-2.10.4
webview_flutter_wkwebview-2.9.5

**Comment by darshankawar** [comment] 2023-11-01 12:21
Closing this as duplicate of https://github.com/flutter/flutter/issues/137640

**Closed by darshankawar** 2023-11-01 12:21 UTC
Labels: in triage
