### ISSUE TITLE
Engine roll causing failures in building an iOS on mac

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#71496] opened 2020-12-01 19:32 UTC
Roll attempt: https://github.com/flutter/flutter/pull/71480/checks?check_run_id=1480497561

Error: https://ci.chromium.org/ui/p/flutter/builders/try/Mac%20build_gallery/3153/overview

```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    note: Using new build systemnote: Planning buildnote: Constructing build descriptionerror: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'Reachability' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'Reachability' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'connectivity' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'connectivity' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'integration_test' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'integration_test' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'url_launcher' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'url_launcher' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'Pods-Runner' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'Pods-Runner' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'Flutter' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'Flutter' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'device_info' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'device_info' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'video_player' from project 'Pods')error: unable to find sdk 'iphoneos13.0' (in target 'video_player' from project 'Pods')error: unable to resolve run destination SDK: 'iphoneos13.0' (in target 'Runner' from project 'Runner')error: unable to find sdk 'iphoneos13.0' (in target 'Runner' from project 'Runner')

════════════════════════════════════════════════════════════════════════════════
Building a deployable iOS app requires a selected Development Team with a 
Provisioning Profile. Please ensure that a Development Team is selected by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- Make sure a 'Development Team' is selected. 
     - For Xcode 10, look under General > Signing > Team.
     - For Xcode 11 and newer, look under Signing & Capabilities > Team.
     You may need to:
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again

```

**Comment by jmagman** [comment] 2020-12-01 19:49
@godofredoc is this https://github.com/flutter/flutter/issues/70793?

**Comment by godofredoc** [comment] 2020-12-01 20:01
yes it is the same, retrying should fix the problem long term solution requires creating our own xcode packages.

**Comment by godofredoc** [comment] 2020-12-01 20:02
Setting as a P2 as retrying will pass the build.

**Comment by chinmaygarde** [comment] 2020-12-07 18:44
Closing this as a duplicate of https://github.com/flutter/flutter/issues/70793

**Closed by chinmaygarde** 2020-12-07 18:44 UTC
Labels: P2, engine, passed first triage
