### ISSUE TITLE
CupertinoNavigationBarBackButton in CupertinoNavigationBar is too far right

### ISSUE THREAD

**Issue by Vinzent03** [flutter/flutter#89136] opened 2021-08-29 17:55 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Replace `main.dart` with the following:

Version A:
```dart
import 'package:flutter/cupertino.dart';

main(List<String> args) {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: Builder(
        builder: (context) {
          return Center(
            child: CupertinoButton(
              child: const Text("Push"),
              onPressed: () {
                Navigator.of(context).push(
                  CupertinoPageRoute(
                    builder: (_) => const CupertinoPageScaffold(
                      navigationBar: CupertinoNavigationBar(
                        middle: Text("My title"),
                      ),
                      child: Center(child: Text("Centered Text")),
                    ),
                  ),
                );
              },
            ),
          );
        },
      ),
    );
  }
}
```

Version B:
```dart
import 'package:flutter/cupertino.dart';

main(List<String> args) {
  runApp(const App());
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: Builder(
        builder: (context) {
          return Center(
            child: CupertinoButton(
              child: const Text("Push"),
              onPressed: () {
                Navigator.of(context).push(
                  CupertinoPageRoute(
                    builder: (_) => const CupertinoPageScaffold(
                      navigationBar: CupertinoNavigationBar(
                        leading: CupertinoNavigationBarBackButton(),
                        middle: Text("My title"),
                      ),
                      child: Center(child: Text("Centered Text")),
                    ),
                  ),
                );
              },
            ),
          );
        },
      ),
    );
  }
}
```
The only difference is adding `leading` to `CupertinoNavigationBar`.

3. Press on the "Push" button and take a look at the top left corner.

**Expected results:** 

I expect them to look exactly the same. 

**Actual results:** 

Version B(with `CupertinoNavigationBarBackButton` as leading) is a bit more right.

Version A
![Version A](https://user-images.githubusercontent.com/63981639/131260317-ff7787f6-7d13-4c13-b4aa-8d3a80568909.png)
Version B
![Version B](https://user-images.githubusercontent.com/63981639/131260319-8618a92b-dcc9-4325-9927-32f937236f5e.png)
Version A with guidelines
![Version A Guidelines](https://user-images.githubusercontent.com/63981639/131260316-fa4cc709-5747-4385-a55c-ce292cb6ec3d.png)
Version B with guidelines
![Version B Guidelines](https://user-images.githubusercontent.com/63981639/131260318-36b2e78b-7a66-4b3d-97e9-8bbb114d1f39.png)

I need to set `leading` myself, because of an issue with `auto_route`(routing package) https://github.com/Milad-Akarie/auto_route_library/issues/668 . In my own app I use `CupertinoNavigationBarBackButton` conditionally.

<details>
  <summary>Logs</summary>

Version A 
```
[  +59 ms] executing: uname -m
[  +35 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: [/home/vinzent/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +13 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 19c61fed0da681ba2068c97e22add3bde38e51e4
[   +1 ms] executing: [/home/vinzent/snap/flutter/common/flutter/] git tag --points-at
19c61fed0da681ba2068c97e22add3bde38e51e4
[  +18 ms] Exit code 0 from: git tag --points-at 19c61fed0da681ba2068c97e22add3bde38e51e4
[        ] 2.5.0-5.2.pre
[  +16 ms] executing: [/home/vinzent/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/vinzent/snap/flutter/common/flutter/] git ls-remote --get-url
origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +84 ms] executing: [/home/vinzent/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +50 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +62 ms] executing: /home/vinzent/Android/Sdk/platform-tools/adb devices -l
[  +37 ms] List of devices attached
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +75 ms] Skipping pub get: version match.
[  +90 ms] Generating
/home/vinzent/desktop/coding/flutter/test/android/app/src/main/java/io/flutter/plugins/Gene
ratedPluginRegistrant.java
[ +144 ms] Launching lib/main.dart on Chrome in debug mode...
[ +115 ms] Updating assets
[  +67 ms] Waiting for connection from debug service on Chrome...
[  +73 ms] <- reset
[   +9 ms] /home/vinzent/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/vinzent/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_ser
ver.dart.snapshot --sdk-root
/home/vinzent/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.IABSBK/flutter_tool.QHAKJG/app.dill --libraries-spec
file:///home/vinzent/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json
--packages /home/vinzent/desktop/coding/flutter/test/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root /tmp/flutter_tools.IABSBK/flutter_tools.YOJHQG --filesystem-scheme
org-dartlang-app --initialize-from-dill
build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///home/vinzent/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_d
dc_sdk_sound.dill --sound-null-safety
[   +9 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+10167 ms] Waiting for connection from debug service on Chrome... (completed in 10,3s)
[        ] Synced 14.4MB.
[        ] <- accept
[        ] Caching compiled dill
[  +77 ms] Using Google Chrome 92.0.4515.159 

[  +29 ms] executing: uname -m
[   +8 ms] Exit code 0 from: uname -m
[        ] x86_64
[ +190 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on
ws://127.0.0.1:41161/devtools/browser/38e79809-6cd2-4ac2-a79a-e005c117a12a
[ +189 ms] DwdsInjector: Received request for entrypoint at
http://localhost:40595/main_module.bootstrap.js
[   +5 ms] MetadataProvider: Loading debug metadata...
[  +10 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +6 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:40595/main_module.bootstrap.js
[+1290 ms] ChromeProxyService: Initializing expression compiler for
main_module.bootstrap.js with sound null safety: true
[  +58 ms] DevHandler: Debug service listening on ws://127.0.0.1:40939/Z34fHQX6tjk=/ws

[  +20 ms] This app is linked to the debug service: ws://127.0.0.1:40939/Z34fHQX6tjk=/ws
[   +8 ms] Debug service listening on ws://127.0.0.1:40939/Z34fHQX6tjk=/ws
[        ] 💪 Running with sound null safety 💪
[   +3 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[        ] An Observatory debugger and profiler on Chrome is available at:
           http://127.0.0.1:40939/Z34fHQX6tjk=
[ +443 ms] DevTools activation throttled until 2021-08-30 04:10:26.159029.
[+1655 ms] The Flutter DevTools debugger and profiler on Chrome is available at:
                    http://127.0.0.1:9102?uri=http://127.0.0.1:40939/Z34fHQX6tjk=
```
Version B
```
[  +59 ms] executing: uname -m
[  +31 ms] Exit code 0 from: uname -m
[        ] x86_64
[   +6 ms] executing: [/home/vinzent/snap/flutter/common/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +11 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 19c61fed0da681ba2068c97e22add3bde38e51e4
[   +1 ms] executing: [/home/vinzent/snap/flutter/common/flutter/] git tag --points-at
19c61fed0da681ba2068c97e22add3bde38e51e4
[  +20 ms] Exit code 0 from: git tag --points-at 19c61fed0da681ba2068c97e22add3bde38e51e4
[        ] 2.5.0-5.2.pre
[  +15 ms] executing: [/home/vinzent/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/vinzent/snap/flutter/common/flutter/] git ls-remote --get-url
origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +86 ms] executing: [/home/vinzent/snap/flutter/common/flutter/] git rev-parse
--abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +49 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +54 ms] executing: /home/vinzent/Android/Sdk/platform-tools/adb devices -l
[  +42 ms] List of devices attached
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +74 ms] Skipping pub get: version match.
[  +90 ms] Generating
/home/vinzent/desktop/coding/flutter/test/android/app/src/main/java/io/flutter/plugins/Gene
ratedPluginRegistrant.java
[ +133 ms] Launching lib/main.dart on Chrome in debug mode...
[ +113 ms] Updating assets
[  +69 ms] Waiting for connection from debug service on Chrome...
[  +63 ms] <- reset
[   +7 ms] /home/vinzent/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart
--disable-dart-dev
/home/vinzent/snap/flutter/common/flutter/bin/cache/artifacts/engine/linux-x64/frontend_ser
ver.dart.snapshot --sdk-root
/home/vinzent/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/ --incremental
--target=dartdevc --debugger-module-names --experimental-emit-debug-metadata
-DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/tmp/flutter_tools.SNTAAZ/flutter_tool.DSLFAB/app.dill --libraries-spec
file:///home/vinzent/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/libraries.json
--packages /home/vinzent/desktop/coding/flutter/test/.dart_tool/package_config.json
-Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation
--filesystem-root /tmp/flutter_tools.SNTAAZ/flutter_tools.NDVGTO --filesystem-scheme
org-dartlang-app --initialize-from-dill
build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///home/vinzent/snap/flutter/common/flutter/bin/cache/flutter_web_sdk/kernel/flutter_d
dc_sdk_sound.dill --sound-null-safety
[  +11 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+10325 ms] Waiting for connection from debug service on Chrome... (completed in 10,4s)
[        ] Synced 14.4MB.
[        ] <- accept
[        ] Caching compiled dill
[  +84 ms] Using Google Chrome 92.0.4515.159 

[  +38 ms] executing: uname -m
[   +9 ms] Exit code 0 from: uname -m
[        ] x86_64
[ +206 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on
ws://127.0.0.1:36481/devtools/browser/8a91e32e-de77-4ce9-97bc-6812ef0e74fd
[ +194 ms] DwdsInjector: Received request for entrypoint at
http://localhost:35805/main_module.bootstrap.js
[   +4 ms] MetadataProvider: Loading debug metadata...
[  +11 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[   +5 ms] DwdsInjector: Injected debugging metadata for entrypoint at
http://localhost:35805/main_module.bootstrap.js
[+1344 ms] ChromeProxyService: Initializing expression compiler for
main_module.bootstrap.js with sound null safety: true
[  +69 ms] DevHandler: Debug service listening on ws://127.0.0.1:45319/-1EEsao-iX0=/ws

[  +24 ms] This app is linked to the debug service: ws://127.0.0.1:45319/-1EEsao-iX0=/ws
[   +9 ms] Debug service listening on ws://127.0.0.1:45319/-1EEsao-iX0=/ws
[        ] 💪 Running with sound null safety 💪
[   +3 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +1 ms] An Observatory debugger and profiler on Chrome is available at:
           http://127.0.0.1:45319/-1EEsao-iX0=
[ +416 ms] DevTools activation throttled until 2021-08-30 04:10:26.159029.
[+1647 ms] The Flutter DevTools debugger and profiler on Chrome is available at:
                    http://127.0.0.1:9102?uri=http://127.0.0.1:45319/-1EEsao-iX0=
```

```
Analyzing bug...                                                       
No issues found! (ran in 1.1s)
```

```
[✓] Flutter (Channel beta, 2.5.0-5.2.pre, on KDE neon User Edition 5.22 5.11.0-27-generic,
    locale de_DE.UTF-8)
    • Flutter version 2.5.0-5.2.pre at /home/vinzent/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 19c61fed0d (vor 11 Tagen), 2021-08-18 17:10:31 -0700
    • Engine revision 7a4c4505f6
    • Dart version 2.14.0 (build 2.14.0-377.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/vinzent/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio
    • Android Studio at /usr/local/android-studio/
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /usr/local/android-studio/
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.59.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.159

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-08-30 11:39
Hi @Vinzent03 
duplicate of https://github.com/flutter/flutter/issues/36689

**Closed by TahaTesser** 2021-08-30 11:39 UTC
Labels: in triage

**Comment by Vinzent03** [comment] 2021-08-30 16:04
Ok, thanks. Didn't find that issue. For those reading this issue later. I found a temporary solution:
```dart
Transform.translate(
            offset: const Offset(-16, 0),
            child: CupertinoNavigationBarBackButton())
```

**Comment by TahaTesser** [comment] 2021-08-31 07:18
@Vinzent03 
I wasn't able to find it too, i had to search deep, please share your workaround in https://github.com/flutter/flutter/issues/36689
