### ISSUE TITLE
[tool_crash] OutOfMemoryError: (null)

### ISSUE THREAD

**Issue by onorhime** [flutter/flutter#149107] opened 2024-05-26 17:48 UTC
## Command
```
flutter run --machine --start-paused -d 09217252A9000728 --devtools-server-address http://127.0.0.1:9100/ --target C:\Users\Alphatrol\Documents\flutter\guardtrol\guardtrolmobile\lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
OutOfMemoryError: (null)
```
#0      new Uint8List (dart:typed_data-patch/typed_data_patch.dart:2236:3)
#1      Uint8Buffer._createBuffer (package:typed_data/src/typed_buffer.dart:328:40)
#2      TypedDataBuffer._createBiggerBuffer (package:typed_data/src/typed_buffer.dart:259:12)
#3      TypedDataBuffer._ensureCapacity (package:typed_data/src/typed_buffer.dart:241:21)
#4      TypedDataBuffer._insertKnownLength (package:typed_data/src/typed_buffer.dart:209:5)
#5      TypedDataBuffer._addAll (package:typed_data/src/typed_buffer.dart:186:7)
#6      TypedDataBuffer.addAll (package:typed_data/src/typed_buffer.dart:91:5)
#7      HashSink.add (package:crypto/src/hash_sink.dart:79:18)
#8      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:49:11)
#9      Hash.convert (package:crypto/src/hash.dart:28:15)
#10     _calculateSha (package:flutter_tools/src/android/gradle.dart:934:20)
#11     AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:594:36)
#12     _rootRunUnary (dart:async/zone.dart:1407:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:162:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:838:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:867:13)
#17     Future._completeWithValue (dart:async/future_impl.dart:643:5)
#18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:713:7)
#19     _rootRun (dart:async/zone.dart:1399:13)
#20     _CustomZone.run (dart:async/zone.dart:1301:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
```
[✓] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
    • Flutter version 3.19.6 on channel stable at C:\Users\Alphatrol\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (6 weeks ago%

**Comment by huycozy** [comment] 2024-05-27 10:16
Closing this as a duplicate of https://github.com/flutter/flutter/issues/133371.

**Closed by huycozy** 2024-05-27 10:16 UTC
Labels: in triage
