### ISSUE TITLE
[image_picker] add multiple images or videos selection

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [flutter/flutter#71321] opened 2020-11-27 18:00 UTC
I suggest adding the functionality of choosing multiple photos or videos as it is now not supported. 

some requirements:
- choose multiple images
- have limit for choosing images
- it should be the native look, since it is supported natively. At least on iOS
- have one photo or video mode, so two new functions for multiple picking 😁

**Comment by iapicca** [comment] 2020-11-27 20:51
possible duplicate of https://github.com/flutter/flutter/issues/16054

**Comment by darshankawar** [comment] 2020-11-30 07:25
@YazeedAlKhalaf 
Please check out the the similar open issue as referred above and follow-up there for updates and for any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-11-30 07:25 UTC
