### ISSUE TITLE
Isolate created in StatefulWidget,and run app will throw 'Illegal argument in isolate message: object is unsendable', never throw the error in StatelessWidget

### ISSUE THREAD

**Issue by wangzl8128** [flutter/flutter#140269] opened 2023-12-16 09:16 UTC
### Steps to reproduce

the app run on desktop of macos
1.create a statefulWidget
2.code a Isolate 
3.run the app,you will see the error "Illegal argument in isolate message: object is unsendable"

### Expected results

do not throw the error "Illegal argument in isolate message: object is unsendable"

### Actual results

throw the error "Illegal argument in isolate message: object is unsendable"

### Code sample

```dart
class TestView extends StatefulWidget {
  const TestView({super.key});

  @override
  State<StatefulWidget> createState() => _HomeViewState();
}
class _HomeViewState extends State<TestView> {
  @override
  Widget build(BuildContext context) {
    aa();
    return Text("1111");
  }
  void aa() async {
    ReceivePort receivePort = ReceivePort();
    Isolate isolate = await Isolate.spawn(worker, receivePort.sendPort);

    receivePort.listen((message) {
      print('Received result HOME: $message');
      receivePort.close();
      isolate.kill(priority: Isolate.immediate);
    });

    await Future.delayed(Duration(seconds: 1));

    int result = await computeFactorial(10);
    isolate.kill(priority: Isolate.immediate);
    print('Computed result HOME: $result');
  }

  void worker(SendPort sendPort) {
    ReceivePort receivePort = ReceivePort();
    sendPort.send(receivePort.sendPort);

    receivePort.listen((message) {
      int number = message as int;
      int result = computeFactorial(number);
      sendPort.send(result);
    });
  }
  int computeFactorial(int number) {
    if (number <= 0) {
      return 1;
    } else {
      return number * computeFactorial(number - 1);
    }
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by danagbemava-nc** [comment] 2023-12-18 06:04
Hi @wangzl8128, this is working as intended. See https://github.com/flutter/flutter/issues/126520#issuecomment-1544422281 and https://stackoverflow.com/a/71462598 for a fix. 

Closing as this is not a flutter issue. 

If you think this behaviour should be changed, kindly file an issue on the dart sdk repo. 

Thank you

**Closed by danagbemava-nc** 2023-12-18 06:04 UTC
Labels: in triage

**Comment by wangzl8128** [comment] 2023-12-18 14:14
Thanks for your help
