### ISSUE TITLE
 [in-app-purchase] : Update the in-app-purchase sdk to implement `com.android.billingclient:billing:5.0.0` or migrate to billing:5.0.0.

### ISSUE THREAD

**Issue by mukund-7span** [flutter/flutter#105091] opened 2022-06-01 06:06 UTC
We are trying with new ApiV2 with base plan id new feature in Play Store but unable to update it to the latest use case as we are unable to fetch the base plan id with getProductDetails().

## Use case

````
val queryProductDetailsParams =
    QueryProductDetailsParams.newBuilder()
        .setProductList(
            ImmutableList.of(
                Product.newBuilder()
                    .setProductId("product_id_example")
                    .setProductType(ProductType.SUBS)
                    .build()))
        .build()

billingClient.queryProductDetailsAsync(
    queryProductDetailsParams,
    ProductDetailsResponseListener { billingResult, productDetailsList ->
        // check billingResult
        // process returned productDetailsList
    }
)
````

here we are looking to have values with product details like offers and base plan id for the following subscriptions.
````
// An activity reference from which the billing flow will be launched.
val activity : Activity = ...;

// Retrieve a value for "productDetails" by calling queryProductDetails()
//  extension function.
val flowParams = BillingFlowParams.newBuilder()
        .setProductDetails(productDetails)
        .setOfferToken(selectedOfferIdToken)
        .build()
val responseCode = billingClient.launchBillingFlow(activity, flowParams).responseCode
````

The launchBillingFlow() method returns one of several response codes listed in [BillingClient.BillingResponseCode](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponseCode). Be sure to check this result to ensure there were no errors launching the purchase flow. A BillingResponseCode of OK indicates a successful launch.

## Proposal
Update the SDK versions which help us to have relevant output like [this](https://developer.android.com/google/play/billing/integrate#launch).

**Comment by danagbemava-nc** [comment] 2022-06-01 06:28
Hi @mukund-7span, there's a PR in progress that seeks to address this. See https://github.com/flutter/plugins/pull/5405/files. Since the PR was initially going to resolve #88664, we can close this in favor of #88664. 

Closing this as a duplicate of #88664

Thank you

**Closed by danagbemava-nc** 2022-06-01 06:28 UTC
Labels: in triage
