### ISSUE TITLE
Error when selecting a date and then going to the previous or next year if the same date is outside the acceptable range

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#8430] opened 2017-02-27 21:33 UTC
Spin-off from https://github.com/flutter/flutter/issues/6501

**Comment by xster** [comment] 2017-02-27 22:43
Thanks for cleaning up

**Comment by YeungKC** [comment] 2020-10-22 20:26
It is no longer possible to reproduce and should be possible to close this issue.

cc @Hixie @xster

**Comment by YeungKC** [comment] 2020-11-21 23:38
Cannot reproduce at last master, I will close the issue.
If anyone disagree, please write in the comments and I will reopen it.

<details>
  <summary>Code</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Builder(builder: (context) {
            return FlatButton(
              onPressed: () async {
                var now = new DateTime.now();
                await showDatePicker(
                  context: context,
                  initialDate: now,
                  firstDate: now,
                  lastDate: now.add(
                    new Duration(days: 2),
                  ),
                );
              },
              child: Text('showDatePicker'),
            );
          }),
        ),
      ),
    );
  }
}
```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.343, on macOS 11.0.1 20B29 darwin-x64, locale zh-Hans)
    • Flutter version 1.24.0-8.0.pre.343 at /Users/YeungKC/FlutterProjects/flutter
    • Framework revision cf6c33e58a (2 小时前), 2020-11-21 14:04:01 -0800
    • Engine revision 23a8e027db
    • Dart version 2.12.0 (build 2.12.0-62.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/YeungKC/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/YeungKC/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode 12.1.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/YeungKC/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android Studio.app/Contents
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Users/YeungKC/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 201.7846.90

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • YeungKC's iPhone (mobile) • 0242c117696911bde40050dc77fd2c9c77781695 • ios            • iOS 14.2
    • iPhone 12 mini (mobile)   • F094173B-A98A-479A-90A8-3CAD0DA64B1A     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • macOS (desktop)           • macos                                    • darwin-x64     • macOS 11.0.1 20B29 darwin-x64
    • Web Server (web)          • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 87.0.4280.67
```

</details>

**Closed by YeungKC** 2020-11-21 23:38 UTC
Labels: P4, f: date/time picker, f: material design, framework, passed first triage
