### ISSUE TITLE
Creating Input widget leads to SkyShell assertion failure

### ISSUE THREAD

**Issue by mishadynin** [flutter/flutter#964] opened 2015-12-16 22:03 UTC
See [input-bug.txt](https://github.com/flutter/flutter/files/64633/input-bug.txt)

I can reliably reproduce this with the Create app when it instantiates the first Input widget. Tried Flutter from master and alpha branches, both crash.
If required, I can try to come up with a smaller failure case.

**Comment by Hixie** [comment] 2015-12-28 20:16
I can also reproduce this with card_collection. I'm looking at it now.

**Comment by Hixie** [comment] 2015-12-28 20:22
Stack Trace:
```
  RELADDR   FUNCTION                                                           FILE:LINE
  00041f50  tgkill+12                                                          /system/lib/libc.so
  0003fb5d  pthread_kill+32                                                    /system/lib/libc.so
  0001c30f  raise+10                                                           /system/lib/libc.so
  000194c1  __libc_android_abort+34                                            /system/lib/libc.so
  000174ac  abort+4                                                            /system/lib/libc.so
  v------>  DebugBreak                                                         engine/src/base/debug/debugger_posix.cc:216
  000e7935  base::debug::BreakDebugger()                                       engine/src/base/debug/debugger_posix.cc:240
  000d4c89  logging::LogMessage::~LogMessage()                                 engine/src/base/logging.cc:645
  000cb1f1  base::android::CheckException(_JNIEnv*)                            engine/src/base/android/jni_android.cc:249 (discriminator 5)
  v------>  jni_generator::CheckException(_JNIEnv*)                            engine/src/base/android/jni_generator/jni_generator_helper.h:33
  v------>  Java_CoreImpl_onAsyncWaitResult                                    engine/src/out/android_Debug/gen/mojo/android/system_java_jni_headers/mojo/jni/CoreImpl_jni.h:369
  0008557b  AsyncWaitCallback                                                  engine/src/mojo/android/system/core_impl.cc:44
  v------>  base::Callback<void (unsigned int)>::Run(unsigned int const&) c... engine/src/base/callback.h:396 (discriminator 2)
  000f872f  mojo::common::HandleWatcher::StateBase::NotifyAndDestroy(unsign... engine/src/mojo/message_pump/handle_watcher.cc:348 (discriminator 2)
  v------>  base::Callback<void (unsigned int)>::Run(unsigned int const&) c... engine/src/base/callback.h:396 (discriminator 2)
  v------>  base::internal::InvokeHelper<...>::MakeItSo(...)                   engine/src/base/bind_internal.h:293 (discriminator 2)
  000f8473  base::internal::Invoker<...>::Run(base::internal::BindStateBase*)  engine/src/base/bind_internal.h:346 (discriminator 2)
  v------>  base::Callback<void ()>::Run() const                               engine/src/base/callback.h:396 (discriminator 1)
  000e7e2b  base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask engine/src/base/debug/task_annotator.cc:49 (discriminator 1)
  000d5e4f  base::MessageLoop::RunTask(base::PendingTask const&)               engine/src/base/message_loop/message_loop.cc:481
  000d62bb  base::MessageLoop::DeferOrRunPendingTask(base::PendingTask const&) engine/src/base/message_loop/message_loop.cc:490
  000d639b  base::MessageLoop::DoWork()                                        engine/src/base/message_loop/message_loop.cc:602
  v------>  DoRunLoopOnce                                                      engine/src/base/message_loop/message_pump_android.cc:35
  000d78f3  Java_org_chromium_base_SystemMessageHandler_nativeDoRunLoopOnce    engine/src/out/android_Debug/gen/base/base_jni_headers/base/jni/SystemMessageHandler_jni.h:42
  0024e6cd  offset 0x1d7000) (void org.chromium.base.SystemMessageHandler.n... /data/app/org.domokit.sky.shell-1/oat/arm/base.odex
  0024eebf  offset 0x1d7000) (void org.chromium.base.SystemMessageHandler.h... /data/app/org.domokit.sky.shell-1/oat/arm/base.odex
  7372f419  offset 0x1ec9000                                                   /data/dalvik-cache/arm/system@framework@boot.oat
```

**Comment by Hixie** [comment] 2015-12-28 20:24
I'm not seeing a Java stack trace in my logs, unfortunately.

**Comment by Hixie** [comment] 2015-12-28 20:26
Aha, it's using the tag "System.err":
```
12-28 12:15:01.000  3378  3378 I Keyboard.Facilitator: onStartInput()
12-28 12:15:01.008 11138 11138 W System.err: java.lang.IndexOutOfBoundsException: setSpan (6 ... 6) ends beyond length 0
12-28 12:15:01.010  3378  3378 D KeyboardTheme: No property defined for ro.com.google.ime.theme_id
12-28 12:15:01.010  3378  3378 I LatinIME: Starting input. Cursor position = -1,-1
12-28 12:15:01.016 11138 11138 W System.err:    at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
12-28 12:15:01.016 11138 11138 W System.err:    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
12-28 12:15:01.016 11138 11138 W System.err:    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
12-28 12:15:01.016 11138 11138 W System.err:    at android.text.Selection.setSelection(Selection.java:76)
12-28 12:15:01.016 11138 11138 W System.err:    at org.chromium.mojo.keyboard.KeyboardServiceState.setSelection(KeyboardServiceState.java:62)
12-28 12:15:01.016 11138 11138 W System.err:    at org.chromium.mojo.keyboard.KeyboardServiceImpl.setSelection(KeyboardServiceImpl.java:76)
12-28 12:15:01.016 11138 11138 W System.err:    at org.chromium.mojom.keyboard.KeyboardService_Internal$Stub.accept(KeyboardService_Internal.java:149)
12-28 12:15:01.016 11138 11138 W System.err:    at org.chromium.mojo.bindings.RouterImpl.handleIncomingMessage(RouterImpl.java:236)
12-28 12:15:01.016 11138 11138 W System.err:    at org.chromium.mojo.bindings.RouterImpl.access$000(RouterImpl.java:18)
12-28 12:15:01.016 11138 11138 W System.err:    at org.chromium.mojo.bindings.RouterImpl$HandleIncomingMessageThunk.accept(RouterImpl.java:30)
12-28 12:15:01.016 11138 11138 W System.err:    at org.chromium.mojo.bindings.Connector.readAndDispatchMessage(Connector.java:245)
12-28 12:15:01.016 11138 11138 W System.err:    at org.chromium.mojo.bindings.Connector.readOutstandingMessages(Connector.java:204)
12-28 12:15:01.017 11138 11138 W System.err:    at org.chromium.mojo.bindings.Connector.onAsyncWaiterResult(Connector.java:170)
12-28 12:15:01.017 11138 11138 W System.err:    at org.chromium.mojo.bindings.Connector.access$100(Connector.java:25)
12-28 12:15:01.017 11138 11138 W System.err:    at org.chromium.mojo.bindings.Connector$AsyncWaiterCallback.onResult(Connector.java:150)
12-28 12:15:01.017 11138 11138 W System.err:    at org.chromium.mojo.system.impl.CoreImpl.onAsyncWaitResult(CoreImpl.java:560)
12-28 12:15:01.017 11138 11138 W System.err:    at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
12-28 12:15:01.017 11138 11138 W System.err:    at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
12-28 12:15:01.017 11138 11138 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:102)
12-28 12:15:01.017 11138 11138 W System.err:    at android.os.Looper.loop(Looper.java:148)
12-28 12:15:01.017 11138 11138 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:5417)
12-28 12:15:01.017 11138 11138 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
12-28 12:15:01.017 11138 11138 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12-28 12:15:01.017 11138 11138 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Hixie** [comment] 2015-12-28 22:15
Looks like the problem is with the `_keyboardHandle.setSelection` call in input.dart.

This probably broke with this change: https://github.com/flutter/flutter/commit/98b83e0cf5e17a476d54c93b4d8a9b0bc969c0f2 (cc @jason-simmons)

**Comment by Hixie** [comment] 2015-12-28 22:23
setText in the Java implementation of the keyboard service never actually sets the text! That explains the first bug in #176.

`java
    @Override
    public void setText(String text) {
        InputMethodManager imm =
                (InputMethodManager) mContext.getSystemService(Context.INPUT_METHOD_SERVICE);
        imm.restartInput(mViewState.getView());
    }
`

**Comment by Hixie** [comment] 2015-12-28 22:32
Could also have broken as part of this change: https://github.com/flutter/engine/commit/e37a1e0c38d902c56926c1cb132ea4bb3ddd92ff (cc @krisgiesing)

**Comment by Hixie** [comment] 2015-12-28 23:04
Will be fixed by https://github.com/flutter/engine/pull/2196 .

**Comment by mishadynin** [comment] 2015-12-28 23:28
Thanks Ian!

**Closed** 2015-12-29 00:54 UTC
Labels: affects: dev experience, affects: engine, affects: framework, affects: text input, customer: pink, fix pending, ⚠ crash
