### ISSUE TITLE
Running `flutter doctor --android-licenses` throws java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by ChristianKleineidam** [flutter/flutter#80966] opened 2021-04-22 17:04 UTC
Flutter doctor shows me:

    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

So I run `flutter doctor --android-licenses` and get:

     Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
     Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

The rest of my Flutter doctor:

[√] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.1.0-12.1.pre at C:\Progs\flutter
    • Framework revision 8264cb3e8a (6 weeks ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:/Users/Christian/AppData/Local/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:/Users/Christian/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\Christian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

**Comment by darshankawar** [comment] 2021-04-23 07:30
Hi @ChristianKleineidam 
Please check [this](https://github.com/flutter/flutter/issues/56778) similar issue and underlying comments / solutions to see if they help resolve your issue.
Thanks.

**Comment by anburocky3** [comment] 2021-05-05 19:28
I'm using `java version "1.8.0_291"` still when i type `flutter doctor --android-licenses` it throws the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

why is that? What I'm doing wrong? I have also installed the `Android SDK Command-line Tools (Latest)`

**Comment by darshankawar** [comment] 2021-05-07 11:48
For those who are still facing this issue, please try the solution mentioned in [this](https://stackoverflow.com/questions/61993738/flutter-doctor-android-licenses-gives-a-java-error/64162776#64162776) SO link.

**Comment by ChristianKleineidam** [comment] 2021-05-07 13:55
Great, that worked. If that's the general solution then instead of throwing the nondescriptive java.lang.NoClassDefFoundError Flutter should check whether the command line tools are installed and when they aren't throw an error that tells the user that the command line tools are required.

**Comment by TahaTesser** [comment] 2021-05-07 15:26
Hi @ChristianKleineidam 
I see there's an open issue addressing the case you described.
Please follow up on that issue, Closing as duplicate of https://github.com/flutter/flutter/issues/80273
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-05-07 15:26 UTC
Labels: in triage
