### ISSUE TITLE
TextField cursor is flickering back and forth endlessly when a keyboard suggestion is set through TextEditingController on iOS

### ISSUE THREAD

**Issue by chwo** [flutter/flutter#39480] opened 2019-08-29 13:17 UTC
- The cursor in the TextField is flickering back and forth endlessly when a text from a keyboard suggestion is set through TextEditingController. 
- Inserting the keyboard shortcut "Double Space for Period" also results into this issue.
- This endlessly flickering loop can only be stopped by closing and reopening the keyboard.

This issue is  **iOS only** and only occurs on **physical devices**. The issue does not appear in the simulator.

| input a keyboard suggestion | input "Double Space for Period" |
| ------ | ------ |
| ![RPReplay_Final1567082616](https://user-images.githubusercontent.com/7806440/63941629-4e460080-ca6c-11e9-8a0d-7b58ec54db68.gif) | ![RPReplay_Final1567082683](https://user-images.githubusercontent.com/7806440/63941660-5b62ef80-ca6c-11e9-959e-d1dcfbf5f536.gif) |

## Steps to Reproduce

The issue occurs in the [sample project](https://api.flutter.dev/flutter/widgets/TextEditingController-class.html) of the TextEditingController class:

```dart
// Flutter code sample for widgets.TextEditingController.1

// This example creates a [TextField] with a [TextEditingController] whose
// change listener forces the entered text to be lower case and keeps the
// cursor at the end of the input.

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

/// This Widget is the main application widget.
class MyApp extends StatelessWidget {
  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: _title,
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  MyStatefulWidget({Key key}) : super(key: key);

  @override
  _MyStatefulWidgetState createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  final _controller = TextEditingController();

  void initState() {
    _controller.addListener(() {
      final text = _controller.text.toLowerCase();
      _controller.value = _controller.value.copyWith(
        text: text,
        selection:
            TextSelection(baseOffset: text.length, extentOffset: text.length),
        composing: TextRange.empty,
      );
    });
    super.initState();
  }

  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        alignment: Alignment.center,
        padding: const EdgeInsets.all(6),
        child: TextFormField(
          controller: _controller,
          decoration: InputDecoration(border: OutlineInputBorder()),
        ),
      ),
    );
  }
}
```
1. Get the [sample project](https://api.flutter.dev/flutter/widgets/TextEditingController-class.html): `flutter create --sample=widgets.TextEditingController.1 mysample`
2. Run the app on a physical iOS device.
3. Type in the TextField and select a word from keyboard suggestions or quickly type two spaces.

## Logs

```
[✓] Flutter is fully installed. (Channel stable, v1.7.8+hotfix.4, on Mac OS X
    10.14.6 18G87, locale de-DE)
[✓] Xcode - develop for iOS and macOS is fully installed. (Xcode 10.3)
[✓] iOS tools - develop for iOS devices is fully installed.
[✓] VS Code is fully installed. (version 1.37.1)
[✓] Connected device is fully installed. (1 available)
```

**Comment by HansMuller** [comment] 2019-08-29 16:30
CC @justinmc @GaryQian

**Comment by justinmc** [comment] 2019-08-30 15:42
@chwo I can't reproduce this as you see it.  I tried running the above code on master on an iPhone 7 with iOS 12, and on an iPhone XR with iOS 13.

Actually, I found that I wasn't able to backspace at all, but I didn't see the cursor flicker.  What device(s) do you see it on?  Does your backspace work?

**Comment by chwo** [comment] 2019-09-02 06:05
@justinmc Thank you for looking into this.

I experienced this issue on an iPhone XS with iOS 12.4. I will test the devices you had tested tomorrow. 

As for the backspace, as soon as I press it, the cursor starts flickering.

Are there any additional information I can provide which would help your debugging?

![RPReplay_Final1567403670](https://user-images.githubusercontent.com/7806440/64093373-58ac1700-cd58-11e9-8d21-5faf324c971e.gif)

**Comment by chwo** [comment] 2019-09-03 14:21
@justinmc I looked into this again today and can confirm that the issue still exists.

I tested on an iPhone 6S with iOS 12.4 and on an iPhone X with iOS 13.

I first noticed the issue with the language/region `de-De`, but for the testing I changed it to `en-US`. Because the issue still occurs, it is not related to that.

I ran the code in the different build modes but that also almost does not make a difference as you can see below.

| | input a keyboard suggestion |  "Double Space for Period" |  press delete button | can move the cursor |
| ------ | ------ | ------ | ------ | ------ |
| steps to reproduce  | type `I` and select the suggestion |  type `test` and quickly type two spaces |   type `test` and press the delete button | try to move the cursor by pressing down in the textfield |
| iOS12, debug mode | ❌ | ❌ | ❌ | ❌ | 
| iOS12, release mode | ❌ | ❌ | ❌ | ❌  |
| iOS13, debug mode | ❌ | ❌ | ❌ | ❌  |
| iOS13, release mode | ❌ | ✅  | ❌ | ❌ |

**Comment by justinmc** [comment] 2019-09-05 22:52
Thank you for the detailed update!  I found an iPhone XR with iOS 12 to try this on and I had the same results (only the delete button has a problem).  I think it's got to be all part of the same bug though.  I'm going to try to track down the cause of that.

**Comment by justinmc** [comment] 2019-09-27 23:20
I spent some time digging into this today but still don't know exactly what causes the deleted character to reappear.  I traced a bunch of communication back and forth between the framework and the engine as I enter input into the field.

In the engine's [FlutterTextInputPlugin.mm](https://github.com/flutter/engine/blob/master/shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm), I see the following happening:

  * `insertText` is called each time a character is typed.
  * When deleting a character in an affected app, the following are all called: `setSelectedTextRange`, `deleteBackward`, and `setTextInputEditingState`.
  * When deleting on an unaffected app (no controller), then the final call to `setTextInputEditingState` doesn't happen.

On the framework side, I see that it causes the call to `setTextInputEditingState` because [EditableTextState.updateRemoteEditingValueIfNeeded](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/editable_text.dart#L1323) thinks that the selection has changed.

I think I just need to go down the rabbit hole a bit further and I'll discover why there's a discrepancy in selection and this whole buggy situation is kicked off.

**Comment by blackbeario** [comment] 2019-12-19 01:32
I am having the exact same issue(s), most noticeably the backspace/delete issue with the flickering characters and cursor. I am having this problem on multiple projects. It may be worth mentioning that both projects are CupertinoTabScaffold apps. I don't _think_ I was having this issue prior to the latest master update.
```
[✓] Flutter (Channel master, v1.13.3-pre.61, on Mac OS X 10.14.6 18G103, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by ZepSaxis** [comment] 2019-12-19 02:29
> I am having the exact same issue(s), most noticeably the backspace/delete issue with the flickering characters and cursor. I am having this problem on multiple projects. It may be worth mentioning that both projects are CupertinoTabScaffold apps. I don't _think_ I was having this issue prior to the latest master update. Multiple devices affected, the most recent attempt was iPhone X - 12.4 and also iPad Pro 12.9" 3rd gen also iOS 12.4
> 
> ```
> [✓] Flutter (Channel master, v1.13.3-pre.61, on Mac OS X 10.14.6 18G103, locale en-US)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.5)
> [✓] VS Code (version 1.40.2)
> [✓] Connected device (3 available)
> 
> • No issues found!
> ```

Having same issue with flutter channel master, switching back to beta resolves the issue:

[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
[✓] VS Code (version 1.40.1)
[✓] Connected device (3 available)

**Comment by GaryQian** [comment] 2019-12-20 00:06
See https://github.com/flutter/flutter/issues/46159 This is likely to be caused by the same commit that was already rolled back. We are considering a hotfix for this. In the meantime, the Beta channel should have this fixed.

**Comment by iapicca** [comment] 2020-03-16 15:16
Hi @chwo 
if the issue persist with the latest stable version of flutter
could you please provide your updated `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by jmagman** [comment] 2020-04-30 01:11
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Closed by jmagman** 2020-04-30 01:11 UTC
Labels: a: text input, f: material design, framework, platform-ios, waiting for customer response

**Comment by kika** [comment] 2020-09-08 01:02
@jmagman  I'm also getting this effect in one of my widgets (which is a TextEditField with a controller) on some physical devices but only sometimes and I can't figure out the system. Sometimes it happens sometimes it's not. For some reason (I don't have a wide selection of phones for testing) it almost only happens on S iPhones (on one 5S and 2 6S). I'm also getting these exceptions which could be from there, but they have no lines of my code so I can't tell for sure, but the timestamps coincide roughly with this effect appearance.
Not sure if this helps.

```
UnsupportedError: Unsupported operation: Infinity or NaN toInt
  File "double.dart", line 192, in _Double.toInt
  File "double.dart", line 160, in _Double.round
  File "editable.dart", line 362, in RenderEditable._getPixelPerfectCursorOffset
  File "editable.dart", line 1978, in RenderEditable._paintCaret
  File "editable.dart", line 2164, in RenderEditable._paintContents
  File "editable.dart", line 2206, in RenderEditable.paint
  File "object.dart", line 2266, in RenderObject._paintWithContext
  File "object.dart", line 186, in PaintingContext.paintChild
  File "proxy_box.dart", line 133, in RenderProxyBoxMixin.paint
  File "object.dart", line 2266, in RenderObject._paintWithContext
  File "object.dart", line 186, in PaintingContext.paintChild
  File "proxy_box.dart", line 133, in RenderProxyBoxMixin.paint
  File "object.dart", line 393, in PaintingContext.pushLayer
  File "proxy_box.dart", line 4858, in RenderLeaderLayer.paint
  File "object.dart", line 2266, in RenderObject._paintWithContext
  File "object.dart", line 186, in PaintingContext.paintChild
  File "proxy_box.dart", line 133, in RenderProxyBoxMixin.paint
  File "object.dart", line 2266, in RenderObject._paintWithContext
  File "object.dart", line 186, in PaintingContext.paintChild
  File "proxy_box.dart", line 133, in RenderProxyBoxMixin.paint
  File "object.dart", line 2266, in RenderObject._paintWithContext
  File "object.dart", line 186, in PaintingContext.paintChild
  File "proxy_box.dart", line 133, in RenderProxyBoxMixin.paint
  File "object.dart", line 2266, in RenderObject._paintWithContext
  File "object.dart", line 186, in PaintingContext.paintChild
  File "proxy_box.dart", line 133, in RenderProxyBoxMixin.paint
  File "object.dart", line 2266, in RenderObject._paintWithContext
  File "object.dart", line 186, in PaintingContext.paintChild
  File "proxy_box.dart", line 133, in RenderProxyBoxMixin.paint
  File "object.dart", line 2266, in RenderObject._paintWithContext
  File "object.dart", line 186, in PaintingContext.paintChild
  File "proxy_box.dart", line 133, in RenderProxyBoxMixin.paint
  File "object.dart", line 2266, in RenderObject._paintWithContext
  File "object.dart", line 137, in PaintingContext._repaintCompositedChild
  File "object.dart", line 97, in PaintingContext.repaintCompositedChild
  File "object.dart", line 982, in PipelineOwner.flushPaint
  File "binding.dart", line 406, in RendererBinding.drawFrame
  File "binding.dart", line 867, in WidgetsBinding.drawFrame
  File "binding.dart", line 286, in RendererBinding._handlePersistentFrameCallback
  File "binding.dart", line 1117, in SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 1056, in SchedulerBinding.handleDrawFrame
  File "binding.dart", line 972, in SchedulerBinding._handleDrawFrame
  File "zone.dart", line 1190, in _rootRun
  File "zone.dart", line 1093, in _CustomZone.run
  File "zone.dart", line 997, in _CustomZone.runGuarded
  File "hooks.dart", line 253, in _invoke
  File "hooks.dart", line 211, in _drawFrame
```

**Comment by jmagman** [comment] 2020-09-10 20:25
@kika https://github.com/flutter/flutter/issues/46159 try the beta channel.

**Comment by hardvain** [comment] 2021-06-28 13:42
Are there any updates on this? I am also facing a similar issue where the text field blinks for 10-15 seconds on a physical ios device. It stops blinking after 10-15seconds

**Comment by jmagman** [comment] 2021-06-28 21:56
@hardvain Can you file a new issue and completely fill out the template?  Not sure what device, version of Flutter you are on, etc.
