### ISSUE TITLE
Flutter example projects should use dartfmt if possible?

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#5499] opened 2016-08-19 16:10 UTC
I'm not sure if this is feasible yet, but seems worth investigating.  Zero rush.

@Hixie @HansMuller @devoncarew

**Comment by sethladd** [comment] 2016-08-19 16:11
For docs: https://github.com/flutter/flutter/wiki/Early-Access%3A-Auto-Formatting

**Comment by sethladd** [comment] 2016-08-19 16:19
I've seen other projects that fail their Travis if the code isn't formatted. That's a pretty good way to enforce formatting. :)

**Comment by eseidelGoogle** [comment] 2017-02-03 19:11
I think we can dupe this against https://github.com/flutter/flutter/issues/2025.

Unless we're willing to decide that our examples could use dart-fmt even if our main code does not.

**Comment by sethladd** [comment] 2017-02-03 19:12
I think our template project (created by `flutter create`) should be formatted with the formatter. We tell our users to use the formatter, so we want them to start with code that won't be reformatted when they run the tool.

**Comment by sethladd** [comment] 2017-02-03 19:12
Sorry, unless I misunderstood... is this issue about the template starter project, or the examples like Gallery?

**Comment by Hixie** [comment] 2018-01-17 00:53
We do the template now. I'm closing the remainder as a dupe of #2025 as above.

**Closed by Hixie** 2018-01-17 00:53 UTC
