### ISSUE TITLE
Engine is >100 commits behind; unable to make progress

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter#59801] opened 2020-06-18 21:11 UTC
The engine roll is >100 commits behind and is unable to make progress automatically. New regression are coming in preventing the roll. I believe this qualifies to be a "tree is on fire", i.e. a P0.

I suggest we close the tree (flutter/flutter, flutter/engine) and do an all hands on deck to fix the tree.

**Comment by pcsosinski** [comment] 2020-06-18 21:49
who's the right assignee for this?  I agree closing the tree may be the right course of action until we are un-stuck.  @kf6gpe

**Comment by jonahwilliams** [comment] 2020-06-18 22:11
We've tracked down the cause of the failure, the engine roll https://github.com/flutter/flutter/pull/59804 should bring us to back up to date

**Comment by digiter** [comment] 2020-06-18 22:16
Triage: is there anything needed from infra team?

**Comment by jonahwilliams** [comment] 2020-06-18 22:16
Not currently. In the future it would be nice to support manually closing the tree

**Comment by kf6gpe** [comment] 2020-06-18 22:53
To @pcsosinski's question, this would be assigned to the engine sheriff to root-cause and rope people in for fixes (which he's been doing). In this case, it was @cbracken, but @jonahwilliams fixed the actual issue.

**Comment by cbracken** [comment] 2020-06-19 00:08
There are a whole lot of followups out of this. There were a bunch of infra/tooling-related bugs that made this far more time-consuming to diagnose than it should be. If someone who's been on the team for over 4 years and who's intimately familiar with much of our tooling, if I'm having issues with this stuff, I think external contributors would probably just walk away. Will file issues.

The engine has rolled in https://github.com/flutter/flutter/pull/59804 so closing this.

**Closed by cbracken** 2020-06-19 00:08 UTC
Labels: P0, engine, framework, passed secondary triage, team, team: infra, tool

**Comment by cbracken** [comment] 2020-06-19 00:20
https://github.com/flutter/flutter/issues/59817 covers inability to run devicelab tests locally.
