### ISSUE TITLE
Flutter SingleChildScrollView + Column + Column + TabBarView + SizedBox => RenderBox was not laid out

### ISSUE THREAD

**Issue by georrge1994** [flutter/flutter#133339] opened 2023-08-25 17:39 UTC
Minimal code for repeating:
```
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Scaffold(
      body: SingleChildScrollView(
        child: Column(
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Expanded(
                    child: TabBarView(
                      controller: _tabController,
                      children: [
                        Container(
                          height: 200,
                          color: Colors.yellowAccent,
                        ),
                        Container(
                          height: 200,
                          color: Colors.yellowAccent,
                        ),
                      ],
                    ),
                  )
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
```

Exception:
```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
RenderBox was not laid out: RenderRepaintBoundary#2eb6e relayoutBoundary=up1 NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1966 pos 12: 'hasSize'
```

Without `SingleChildScrollView` it works, but I need srollable and stable solution. So, sad that I choosen flutter for my project.

**Comment by raiesraj** [comment] 2023-08-25 20:02
check it step by step  first things first remove expanded widgets

**Comment by raiesraj** [comment] 2023-08-25 20:20
or briefly describe what you want to get?

**Comment by moffatman** [comment] 2023-08-26 00:49
That layout is not valid, if you can describe more what you want it to look like, I'm sure we can find the right way to do it

**Comment by dheerajv099** [comment] 2023-08-26 05:32
You can not use Expanded as child of SingleChildScrollView without specifing height, so you have to give height to Expanded widget

**Comment by darshankawar** [comment] 2023-08-28 06:38
@georrge1994 
Looking at the error received and also taking into consideration above comments, it seems to be occuring due to code implementation and not a bug in the framework. You can also ask this question on support channels like StackOverflow to get solution on your code structure.
Closing from here.

**Closed by darshankawar** 2023-08-28 06:38 UTC
Labels: in triage
