### ISSUE TITLE
Flutter firebase_auth package does not provide "refresh token" property.

### ISSUE THREAD

**Issue by KFMONGF2P** [flutter/flutter#52933] opened 2020-03-20 04:27 UTC
I need to get refresh token from firebase auth, which I will use that "refresh token" for custom backend API. But firebase_auth plugin "**getIdToken**" class, I use parameter "**refresh**" and set as "**true**" it is just returning a refreshed JWT idToken, But what I want is a "**refresh token**". Is there an alternative solution for this issue?

**Comment by iapicca** [comment] 2020-03-20 06:27
Hi @KFMONGF2P 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Closed by iapicca** 2020-03-20 06:27 UTC

**Comment by KFMONGF2P** [comment] 2020-03-20 07:04
@iapicca Noted.
Submitted at https://github.com/FirebaseExtended/flutterfire/issues.
This issue moved to https://github.com/FirebaseExtended/flutterfire/issues/2212.
