### ISSUE TITLE
Can't run tests with coverage if using mixins

### ISSUE THREAD

**Issue by v3rm0n** [flutter/flutter#20811] opened 2018-08-20 09:23 UTC
## Steps to Reproduce

1. Clone test project https://github.com/v3rm0n/mixin_coverage_error
2. Run `flutter test --coverage`
## Logs

```
unhandled error during test:
/Users/maidokaara/Development/change/mixin_coverage_error/test/profile_bloc_test.dart
Bad state: Couldn't find line and column for token 180 in package:mixin_coverage_error/profile_bloc.dart.
#0      VMScript._lineAndColumn (package:vm_service_client/src/script.dart:243:5)
#1      _ScriptLocation._ensureLineAndColumn (package:vm_service_client/src/script.dart:314:26)
#2      _ScriptLocation.line (package:vm_service_client/src/script.dart:295:5)
#3      _getCoverageJson (package:coverage/src/collect.dart:99:45)
<asynchronous suspension>
#4      _getAllCoverage (package:coverage/src/collect.dart:51:26)
<asynchronous suspension>
#5      collect (package:coverage/src/collect.dart:35:18)
<asynchronous suspension>
#6      CoverageCollector.collectCoverage (package:flutter_tools/src/test/coverage_collector.dart:59:45)
<asynchronous suspension>
#7      CoverageCollector.handleFinishedTest (package:flutter_tools/src/test/coverage_collector.dart:27:11)
<asynchronous suspension>
#8      _FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:622:30)
<asynchronous suspension>
#9      _FlutterPlatform.loadChannel (package:flutter_tools/src/test/flutter_platform.dart:383:36)
#10     PlatformPlugin.load (package:test/src/runner/plugin/platform.dart:65:19)
<asynchronous suspension>
#11     Loader.loadFile.<anonymous closure> (package:test/src/runner/loader.dart:248:36)
<asynchronous suspension>
#12     new LoadSuite.<anonymous closure>.<anonymous closure> (package:test/src/runner/load_suite.dart:89:31)
<asynchronous suspension>
#13     invoke (package:test/src/utils.dart:242:5)
#14     new LoadSuite.<anonymous closure> (package:test/src/runner/load_suite.dart:88:7)
#15     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test/src/backend/invoker.dart:403:25)
<asynchronous suspension>
#16     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#17     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#18     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#19     _rootRun (dart:async/zone.dart:1120:38)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#24     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#28     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#29     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#30     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#31     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:169:12)
```

```
Analyzing mixin_coverage_error...
No issues found! (ran in 0.9s)
```

```
[✓] Flutter (Channel master, v0.5.9-pre.84, on Mac OS X 10.14 18A365a, locale en-EE)
    • Flutter version 0.5.9-pre.84 at /Users/maidokaara/Programs/flutter
    • Framework revision 3ae5ecebea (23 hours ago), 2018-08-19 06:25:00 -0400
    • Engine revision 03f8ba51e3
    • Dart version 2.1.0-dev.0.0.flutter-be6309690f

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
    • Android SDK at /Users/maidokaara/Library/Android/sdk
    • Android NDK at /Users/maidokaara/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.2
    • ANDROID_HOME = /Users/maidokaara/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 10.0, Build version 10L221o
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.3911.37

[✓] VS Code (version 1.25.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.16.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by zoechi** [comment] 2018-08-20 09:30
Do you have

```yml
analyzer:
  language:
    enableSuperMixins: true
```
in `analysis_options.yaml`

**Comment by v3rm0n** [comment] 2018-08-20 09:34
I do not, but I tried adding this to the repro project and run again but it didn't really change anything...

**Comment by zoechi** [comment] 2018-08-20 09:35
It's only for static analysis. The compiler doesn't care.
There were some changes recently but I don't know what purpose or effect they have or the intention (just back from vacation)

**Comment by v3rm0n** [comment] 2018-08-21 06:16
Just FYI, issue still there with  Flutter `v0.6.1-pre.47` and Dart `2.1.0-dev.1.0.flutter-69fce633b7`

**Comment by zoechi** [comment] 2018-10-29 11:32
Are you still seeing this?

**Comment by v3rm0n** [comment] 2018-10-29 14:17
Yes, Flutter `v0.10.1` and Dart `2.1.0-dev.7.1.flutter-b99bcfd309`

**Comment by zoechi** [comment] 2019-01-18 10:54
Duplicate of https://github.com/dart-lang/sdk/issues/34841

**Closed by zoechi** 2019-01-18 10:54 UTC
Labels: a: tests, dependency: dart, severe: crash, tool
