### ISSUE TITLE
Provide information about Element and RenderObject rebuilds in "Widget Rebuild Stats"

### ISSUE THREAD

**Issue by ChristianKleineidam** [flutter/flutter#81895] opened 2021-05-05 09:22 UTC
I'm currently trying to understanding when Flutter needs to rerender a Widget and asked a [StackOverflow question ](https://stackoverflow.com/q/67345485/25282) about it. While a more detailed past [video](https://www.youtube.com/watch?v=996ZgFRENMs) talked about the associated life cycle but not in detail the Flutter team published a new video basically saying "there's no life cycle" Flutter is doing smart magic. 

This is a bad approach to communicating how Flutter works because it leads to people not understanding what's relevant for performance and develop superstitions about how the magic works and write some code more complicated for no good reason as a recent [thread on Reddit](Methods vs Stateless Widget to return widgets
) suggests. It seems that given that [someone said](https://youtu.be/vVg9It7cOfY?t=1267) that you can optimize performance of a ListView by using a stateless Widget instead of a function, the superstition developed that it's generally more performant to use stateless Widgets over functions. 

The fact that in the Flutter performance tab Flutter lists "Widget Rebuild Stats" strongly suggests that this is what matters for performance. If it doesn't matter much because what matters is element and renderObject rebuilds then the  "Widget Rebuild Stats" tab should show those as well.

**Comment by pedromassangocode** [comment] 2021-05-05 10:40
Hi @ChristianKleineidam 

> in the Flutter performance tab Flutter lists "Widget Rebuild Stats"

Can you please point me to where I can find this tab?

Sorry, it is not clear to me what information should be provided in the "Widget Rebuild Stats" page. Can you please elaborate?
Thank you

**Comment by ChristianKleineidam** [comment] 2021-05-05 11:44
AndroidStudio has a "Flutter Performance"-tab and that has a section titled "Widget Rebuild Stats".

**Comment by pedromassangocode** [comment] 2021-05-05 11:51
Hi @ChristianKleineidam 
Following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter), the correct way to address the problem is to open an issue in the dedicated [repository](https://github.com/flutter/flutter-intellij/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by pedromassangocode** 2021-05-05 11:51 UTC
Labels: in triage

**Comment by ChristianKleineidam** [comment] 2021-05-05 12:02
I opponened it at https://github.com/flutter/flutter-intellij/issues/5462
