### ISSUE TITLE
Android tools: `install` should run `build` as necessary

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#4165] opened 2016-05-24 22:14 UTC
Running `flutter install` on an Android device without having run `flutter build apk` first fails because build/app.apk is missing. We should just run `build` on demand.

@devoncarew

**Comment by Hixie** [comment] 2017-01-30 04:43
Dupe of https://github.com/flutter/flutter/issues/4508

**Closed by Hixie** 2017-01-30 04:43 UTC
Labels: dev: tool, new feature
