### ISSUE TITLE
Unable to upload app after xcode 14.3 update | Error Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by nizom333** [flutter/flutter#124188] opened 2023-04-05 07:22 UTC
## Steps to Reproduce

1. Open xcode
2. Click Product > Archive

**Expected results:** 

**Actual results:** 

<img width="1590" alt="image" src="https://user-images.githubusercontent.com/28598438/230009345-dbd47704-5ee1-4fbe-a52c-d66da8d94577.png">

<details>
<summary>Code sample</summary>

```dart
```

</details>

<details>
  <summary>Logs</summary>

```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/nizom/Library/Developer/Xcode/DerivedData/Runner-ahbzxirstxxegzemkftnailqorto/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-B03666E8B0F5A4ED484BDC9C.sh (in target 'Runner' from project 'Runner')
    cd /Users/nizom/Documents/Projects/flutter/multibank_app/ios
    /bin/sh -c /Users/nizom/Library/Developer/Xcode/DerivedData/Runner-ahbzxirstxxegzemkftnailqorto/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-B03666E8B0F5A4ED484BDC9C.sh

mkdir -p /Users/nizom/Library/Developer/Xcode/DerivedData/Runner-ahbzxirstxxegzemkftnailqorto/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/Runner.app/Frameworks
Symlinked...
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/DKImagePickerController.framework" "/Users/nizom/Library/Developer/Xcode/DerivedData/Runner-ahbzxirstxxegzemkftnailqorto/Build/Intermediates.noindex/ArchiveIntermediates/Runner/InstallationBuildProductsLocation/Applications/Runner.app/Frameworks"
building file list ... rsync: link_stat "/Users/nizom/Documents/Projects/flutter/multibank_app/ios/../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/DKImagePickerController.framework" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code
```

</details>

**Comment by danagbemava-nc** [comment] 2023-04-05 08:35
Hi @nizom333, Xcode 14.3 changed something that broke cocoapods. See https://github.com/flutter/flutter/issues/123890#issuecomment-1494825976 for more context. 

Closing this as a duplicate of #123890

**Closed by danagbemava-nc** 2023-04-05 08:35 UTC
Labels: in triage
