### ISSUE TITLE
iOS dragging down system notification shade can trigger scroll-to-top

### ISSUE THREAD

**Issue by jklint-g** [flutter/flutter#23391] opened 2018-10-23 03:54 UTC
1. On an iphone, scroll down on a screen with a Scaffold and SingleChildScrollView.
2. Place your finger on the system status bar without moving or releasing it. Notice the flutter app immediately scrolls to top of the page.
3. Drag down to bring down the system notification shade. The app has already scrolled to top.

Expected: the flutter app does not scroll to top unless the user deliberately taps the status bar.

Looks like flutter activates the scroll-to-top on finger down, but it should wait for an actual tap gesture instead. This is consistent with how iOS handles scrolling elsewhere in the system.

**Comment by zoechi** [comment] 2018-10-23 05:58
Please add the output of `flutter doctor -v`.

**Comment by wang542413041** [comment] 2018-10-23 08:42
Hello, I have integrated flutter in existing projects today, but I have been stuck on one issue.

ld: '/Users/dp/Desktop/my_flutter/.ios/Flutter/engine/Flutter.framework/Flutter' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/dp/Desktop/my_flutter/.ios/Flutter/engine/Flutter.framework/Flutter' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

can you help me for some answers ?

**Comment by zoechi** [comment] 2018-10-24 08:35
@wang542413041 created #23396 for this

**Comment by kf6gpe** [comment] 2020-01-06 20:26
Closing due to lack of reproducibility. If this is still an issue, please re-open, include a minimal reproducible case, and the output of `flutter doctor`.

**Closed by kf6gpe** 2020-01-06 20:26 UTC
Labels: f: material design, f: scrolling, framework, ⌺‬ platform-ios

**Comment by jklint-g** [comment] 2020-01-07 01:13
This still repros on iOS 12. Currently the scroll-to-top gesture is broken on iOS 13 https://github.com/flutter/flutter/issues/35050, however once that is fixed I expect this bug to still be present on 13 as well.

Try this layout and the following steps:
1. In the app, scroll down so that text is offscreen.
2. Rest your finger on the system status bar but do not lift it off the screen.
***bug is here, the app scrolls back to the top with your finger still down***

```
Scaffold(
  body: SingleChildScrollView(
    child: Container(
      height: 10000, 
      width: 1000,
      color: Colors.white,
      child: Text('hey'))))
```
Expected behavior is that Flutter should not trigger the scroll-to-top until it receives a finger-up event, and then only if the duration from finger-down to up is short enough to constitute a tap.

[✓] Flutter (Channel google3, vnull, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version null at //third_party/dart/flutter
    • Framework revision 659dc8129d (7 days ago), 2019-12-30T00:00:00.000
    • Engine revision bdc9708d23
    • Dart version c547f5d933
