### ISSUE TITLE
cull_opacity_perf__timeline_summary is failing

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#51148] opened 2020-02-20 23:37 UTC
Devicelab cull_opacity_perf__timeline_summary test failing with 30 second timeout exception.

```
2020-02-20T14:46:42.632566: stdout: [+29502 ms] 00:30 [32m+0[0m[31m -1[0m: cull_opacity_perf [1m[31m[E][0m[0m
2020-02-20T14:46:42.634427: stdout: [   +2 ms]   TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
```

Failing on engine roll https://github.com/flutter/flutter/commit/0b5667ac12b073295403780bd3a38fd88db7a273.

**Comment by dnfield** [comment] 2020-02-21 17:21
This seems like it's different from the last time this benchmark was timing out, but its' a similar issue - the timeline JSON has grown significantly, the test is timing out, and it's gotten slower.  I'm reverting the engine change until we figure ithis out.

**Comment by dnfield** [comment] 2020-02-21 17:42
Apparently this is a duplicate of the original cause in #50997 - the same problem managed to roll in again.  @jason-simmons is working on a roll that gets us past it.

**Comment by dnfield** [comment] 2020-02-22 08:12
Going to close this - the offending commit got reverted, and the next roll should roll past it.

**Closed by dnfield** 2020-02-22 08:12 UTC
Labels: engine, ⚠ TODAY
