### ISSUE TITLE
Canvas drawImage not working from background（on Android）

### ISSUE THREAD

**Issue by Sulisong** [flutter/flutter#74816] opened 2021-01-27 15:46 UTC
Canvas drawImage not working from background（on Android）！

**Comment by iapicca** [comment] 2021-01-27 16:01
@Sulisong 
can you provide your `flutter doctor -v`, your `flutter run  -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Sulisong** [comment] 2021-01-27 16:21
flutter doctor -v：
`[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale zh-CN)
    • Flutter version 1.25.0-8.3.pre at C:\flutter
    • Framework revision 5d36f2e7f5 (13 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = F:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • M2011K2C (mobile) • 89e82f8 • android-arm64 • Android 11 (API 30)
demo：
• No issues found!
`

`import 'dart:ui';

class TestCanvas {
  //The background operation returns blank, but the foreground operation is normal
  Future<Image> runTest(Image image) async {
    final recorder = PictureRecorder();
    final canvas = Canvas(recorder);
    //When you run this method, you need to run it manually in the background, so it runs with a delay of 8 seconds
    return await Future.delayed(Duration(seconds: 8), () async {
      canvas.drawImage(image, Offset(0, 0), Paint());
      return await recorder.endRecording().toImage(100, 100);
    });
  }
}`

**Comment by Sulisong** [comment] 2021-01-27 16:23
flutter doctor -v：
`[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.19042.746], locale zh-CN)
    • Flutter version 1.25.0-8.3.pre at C:\flutter
    • Framework revision 5d36f2e7f5 (13 days ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at F:\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = F:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • M2011K2C (mobile) • 89e82f8 • android-arm64 • Android 11 (API 30)

• No issues found!
`

demo：

`import 'dart:ui';

class TestCanvas {
  //The background operation returns blank, but the foreground operation is normal
  Future<Image> runTest(Image image) async {
    final recorder = PictureRecorder();
    final canvas = Canvas(recorder);
    //When you run this method, you need to run it manually in the background, so it runs with a delay of 8 seconds
    return await Future.delayed(Duration(seconds: 8), () async {
      canvas.drawImage(image, Offset(0, 0), Paint());
      return await recorder.endRecording().toImage(100, 100);
    });
  }
}`

> @Sulisong
> can you provide your `flutter doctor -v`, your `flutter run -v` and a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Sulisong** [comment] 2021-01-27 16:34
@iapicca When using ‘--enable-software-rendering’ it can be used normally, but this is not a solution.You can look at my last reply.

**Comment by iapicca** [comment] 2021-01-27 16:34
@Sulisong 
I'm not sure how well your sample is reproducible, it seems more a snippet than a [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
anyhow I believe I can spot a problem with `dart:ui` and `Image` class, does this help ?

```diff
-import 'dart:ui';
+import 'dart:ui' as ui;

class TestCanvas {
- Future runTest(Image image) async {
+ Future runTest(ui.Image image) async {
-   final recorder = PictureRecorder();
+   final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    return await Future.delayed(Duration(seconds: 8), () async {
      canvas.drawImage(image, Offset(0, 0), Paint());
      return await recorder.endRecording().toImage(100, 100);
    });
  }
}

```

**Comment by Sulisong** [comment] 2021-01-27 16:53
@iapicca When exporting 100 size is normal, exporting 1000 is blank
`import 'dart:ui' as ui;

class TestCanvas {
  //The background operation returns blank, but the foreground operation is normal
  Future<ui.Image> runTest(ui.Image image) async {
    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(recorder);
    //When you run this method, you need to run it manually in the background, so it runs with a delay of 8 seconds
    return await Future.delayed(Duration(seconds: 8), () async {
      canvas.drawImage(image, ui.Offset(0, 0), ui.Paint());
      //When exporting 100 size is normal, exporting 1000 is blank
      return await recorder.endRecording().toImage(1000, 1000);
    });
  }
}`

**Comment by Sulisong** [comment] 2021-01-27 16:58
`<import 'dart:ui' as ui;

class TestCanvas {
  //The background operation returns blank, but the foreground operation is normal
  Future<ui.Image> runTest(ui.Image image) async {
    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(recorder);
    //When you run this method, you need to run it manually in the background, so it runs with a delay of 8 seconds
    return await Future.delayed(Duration(seconds: 8), () async {
      canvas.drawImage(image, ui.Offset(0, 0), ui.Paint());
      //When exporting 100 size is normal, exporting 1000 is blank
      return await recorder.endRecording().toImage(1000, 1000);
    });
  }
}>`

**Comment by iapicca** [comment] 2021-01-27 17:15
testing this *[code sample](https://gist.github.com/iapicca/a97bbe754cf0b6a7781159fcdeaf3da6*

<details>
<summary> code sample</summary>

```dart
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

const _url =
    'https://cdn.omlet.co.uk/images/originals/worlds_most_popular_pet_bird.jpg';

class NetworkImageRecorder {
  final NetworkImage image;
  const NetworkImageRecorder({this.image});

  Future<Image> call() async {
    final completer = Completer<ImageInfo>();
    image.resolve(ImageConfiguration()).addListener(ImageStreamListener(
        (ImageInfo info, bool _) => completer.complete(info)));
    final info = await completer.future;
    final uiImage = info.image;
    final recorder = ui.PictureRecorder();
    Canvas(recorder)..drawImage(uiImage, Offset.zero, Paint());
    final picture = recorder.endRecording();
    final pngBytes = await (await picture.toImage(1000, 1000))
        .toByteData(format: ui.ImageByteFormat.png);
    return Image.memory(pngBytes.buffer.asUint8List());
  }
}

const _decoder = NetworkImageRecorder(image: NetworkImage(_url));

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Material(
          child: Center(
            child: FutureBuilder<Image>(
              future: _decoder(),
              builder: (context, image) => !image.hasData
                  ? const CircularProgressIndicator()
                  : image.hasError
                      ? const Icon(Icons.error)
                      : image.data,
            ),
          ),
        ),
      );
}

```

</details>

with the latest `master` on a `pixel 3a`

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.26.0-13.0.pre.194, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-13.0.pre.194 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 71aec53acb (11 hours ago), 2021-01-26 21:53:04 -0800
    • Engine revision b11bef83a5
    • Dart version 2.12.0 (build 2.12.0-263.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64      • Linux
    • Chrome (web)      • chrome     • web-javascript • Chromium 88.0.4324.96 snap

! Doctor found issues in 1 category.

```

</details>

everything seems to work as intended

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/106027838-f46bbf00-60d3-11eb-9e60-b723bbbe7ddf.png)


</details>

**Comment by Sulisong** [comment] 2021-01-27 17:23
@iapicca You can also try to increase the delay. Go home immediately after running, wait for the delay to complete and then return to the App to view.It is possible to run in the foreground, and a blank image is generated when the application is in the background

**Comment by Sulisong** [comment] 2021-01-27 17:32
@iapicca You can try adding 8 seconds delay. Return to the desktop immediately after running the application, wait for the delay to complete and then return to the App to view (provided that you do not use --enable-software-rendering)

**Comment by iapicca** [comment] 2021-01-27 17:44
```diff
lass NetworkImageRecorder {
  final NetworkImage image;
  const NetworkImageRecorder({this.image});

  Future<Image> call() async {
    final completer = Completer<ImageInfo>();
    final recorder = ui.PictureRecorder();

    image.resolve(ImageConfiguration()).addListener(
        ImageStreamListener((info, _) => completer.complete(info)));

+    await Future.delayed(const Duration(seconds: 8));

    Canvas(recorder)
      ..drawImage((await completer.future).image, Offset.zero, Paint());

    return Image.memory(
        (await (await recorder.endRecording().toImage(1000, 1000))
                .toByteData(format: ui.ImageByteFormat.png))
            .buffer
            .asUint8List());
  }
}
```

I've tried, but no changes, are you getting the error with my code sample?
If the code sample I provided doesn't represent the issue you are describing
can you please provide  a **_complete runnable_** [minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example), 
not just a partial snippet of your code

**Comment by Sulisong** [comment] 2021-01-27 17:50
@iapicca I want to confirm two conditions: 1 (--enable-software-rendering is not enabled) 2 (Run ‘drawImage’ while the software is running in the background). My image is blank in this case

#73675 Same as this

**Comment by Sulisong** [comment] 2021-01-27 18:15
@iapicca `
import 'package:android_intent/android_intent.dart';
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

const _url =
    'https://cdn.omlet.co.uk/images/originals/worlds_most_popular_pet_bird.jpg';

class NetworkImageRecorder {
  final NetworkImage image;
  const NetworkImageRecorder({this.image});

  Future<Image> call() async {
    final completer = Completer<ImageInfo>();
    final recorder = ui.PictureRecorder();

    image.resolve(ImageConfiguration()).addListener(ImageStreamListener(
        (ImageInfo info, bool _) => completer.complete(info)));

       //android_intent: ^0.3.7+7
     AndroidIntent(
       action: 'android.intent.action.MAIN',
       category: 'android.intent.category.HOME').launch();

    await Future.delayed(const Duration(seconds: 2));
    Canvas(recorder)
      ..drawImage((await completer.future).image, Offset.zero, Paint());

    return Image.memory(
        (await (await recorder.endRecording().toImage(1000, 1000))
                .toByteData(format: ui.ImageByteFormat.png))
            .buffer
            .asUint8List());
  }
}

const _decoder = NetworkImageRecorder(image: NetworkImage(_url));

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Material(
          child: Center(
            child: FutureBuilder<Image>(
              future: _decoder(),
              builder: (context, image) => !image.hasData
                  ? const CircularProgressIndicator()
                  : image.hasError
                      ? const Icon(Icons.error)
                      : image.data,
            ),
          ),
        ),
      );
}
`

**Comment by iapicca** [comment] 2021-01-27 19:29
@Sulisong 
oh sorry, I missed the `running in background` part, in this case seems a duplicate of https://github.com/flutter/flutter/issues/64558

> I want to confirm two conditions: 
> 1. (--enable-software-rendering is not enabled) 
> 2. (Run ‘drawImage’ while the software is running in the background).

**Comment by Sulisong** [comment] 2021-01-27 20:02
@iapicca Is this a bug? Is there currently any way to fix it

**Comment by darshankawar** [comment] 2021-01-28 06:56
@Sulisong 
Since your issue resembles https://github.com/flutter/flutter/issues/73675 which is also related to `Canvas.drawImage` not working when app resumes from background, I am going ahead and closing this as duplicate in favor or above (https://github.com/flutter/flutter/issues/73675).
If you disagree, write in comments and I'll reopen it.

The other issue, https://github.com/flutter/flutter/issues/64558, doesn't seem to make use of `Canvas.drawImage` and has been labeled for `ios`.

**Closed by darshankawar** 2021-01-28 06:56 UTC
