### ISSUE TITLE
Disproportionate debug App and project size

### ISSUE THREAD

**Issue by nassim3952** [flutter/flutter#141776] opened 2024-01-18 13:49 UTC
### Steps to reproduce

Hi, I've build the starter project "Hello World", and I'm experiencing two issues:

The "build" folder reaches 1.2 GB, which is abnormally large for just a project that containe one text

The size of the debug APK is 470 MB, which seems disproportionate for a basic "Hello World" application.

ive tried flutter clean, flutter -reset, flutter pub upgrade, the issues persist

### Code sample

<details open><summary>Code sample</summary>

```dart
// just display hello world 
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World!'),
        ),
      ),
    );
  }
}

```

</details>

### What target platforms are you seeing this bug on?

Android

### OS/Browser name and version | Device information

• Flutter 3.16.8 
• Dart 3.2.5 
• DevTools 2.28.5
• Android Studio Giraffe | 2022.3.1 Patch 2
• Windows 11 pro • Version : 21H2 • OS build : 22000.1936

i5-7300U @ 2.60GHz   
16,0 GB
SSD 

### Does the problem occur on emulator/simulator as well as on physical devices?

Yes

### Flutter Doctor output

[√] Flutter (Channel stable, 3.16.8, on Microsoft Windows [Version 10.0.22000.1936], locale fr-FR)
    • Flutter version 3.16.8 on channel stable at C:\Users\Administrator\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 67457e669f (2 days ago), 2024-01-16 16:22:29 -0800
    • Engine revision 6e2ea58a5c
    • Dart version 3.2.5
    • DevTools version 2.28.5

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • BE2013 (mobile)   • 192.168.1.6:5555 • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows          • windows-x64    • Microsoft Windows [Version 10.0.22000.1936]
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 120.0.6099.218
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 118.0.2088.46

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by darshankawar** [comment] 2024-01-19 07:20
@nassim3952 
I tried with the code sample on latest stable and ran `flutter build apk` which resulted in 17.1 MB size:

```
Running Gradle task 'assembleRelease'...                           71.3s
✓  Built build/app/outputs/flutter-apk/app-release.apk (17.1MB).

```

I tried this on mac though and you seem to be on windows.
Can you provide which command did you run to build app ? Can you run in verbose mode and check if any logs shows adding upto the build size you are getting ?

**Comment by nassim3952** [comment] 2024-01-19 18:44
Hi @darshankawar, I'm new to Flutter. I don't know how much space a Flutter app in debug mode should occupy on the device.
I have already built a release APK, and it weighs exactly 17.1MB.
I deleted the build directory using the flutter clean command, then built the project using flutter run --release. Here are the results: 
-the size of the app in release mode is 68 MB
-the size of the build folder is 63 MB
-However, as soon as I press the "Run" button in Android Studio or build the app using the flutter run command, the app in debbug mode becomes 470 MB, and the build folder increases to 1.2 GB. 
-Is this normal in flutter ?

**Comment by darshankawar** [comment] 2024-01-22 05:21
> -However, as soon as I press the "Run" button in Android Studio or build the app using the flutter run command, the app in debbug mode becomes 470 MB, and the build folder increases to 1.2 GB.
> -Is this normal in flutter ?

I think so, because when you are in debug mode and trying to install the app on device, the size of the app / apk will be more, but if you build in release mode or push your code to github, it'll be back to normal (just like the size in release mode), so I think this is not an issue and WAI (works as intended).

Based on above, I'll close this as non-issue. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2024-01-22 05:21 UTC
Labels: in triage

**Comment by nassim3952** [comment] 2024-01-26 09:57
> I think so, because when you are in debug mode and trying to install the app on device, the size of the app / apk will be more, but if you build in release mode or push your code to github, it'll be back to normal (just like the size in release mode), so I think this is not an issue and WAI (works as intended).
> 
> Based on above, I'll close this as non-issue. If you disagree, write in comments and I'll reopen it.

Thanks for your response @darshankawar. While I understand that debug builds might be larger due to additional information for debugging purposes, a size of 470 MB for a simple 'Hello World' app in debug mode seems unusually high. This is impacting my build times, particularly the time it takes for Android to install the application on the device (due to the enormous size of the application), which is currently 3-4 minutes. This seems to be a significant issue as it affects the development workflow.
