### ISSUE TITLE
Firebase Messaging: Infinite onLaunch Loop

### ISSUE THREAD

**Issue by nevi-me** [flutter/flutter#18524] opened 2018-06-16 03:07 UTC
## Steps to Reproduce

1. Add Firebase Messaging to a Flutter app
2. Configure Hooks for `onMessage`, `onLaunch` and `onResume`
3. Receive a Firebase Message (I used both backend and Firebase Console)
4. Open notification while app is not started
5. Get an infinite loop, with `print("onLaunch: $message");` below being called repetitively.

```dart
@override
void initState() {
  super.initState();

  /// Navigate to item based on message type
  ///
  void _navigateToItemDetail(Map<String, dynamic> message) {
    if (message.containsKey("type")) {
      // handle messages by type
      String type = message["type"];
      String _id = message["_id"] ?? "";
      switch (type) {
        case "private_message":
          Application.router.navigateTo(context, "/private_message/$_id");
          break;
        case "announcement":
          FlutterWebBrowser.openWebPage(
            url: message["url"] ?? "https://me.app",
            androidToolbarColor: Colors.red
          );
          break;
        case "public_message":
          Application.router.navigateTo(context, "/public_message/$_id");
          break;
        default:
      }
    }
  }

  Future<Null> _showItemDialog(Map<String, dynamic> message, BuildContext ctx) async {
    return showDialog<Null>(
      context: ctx,
      barrierDismissible: false, // user must tap button!
      builder: (BuildContext context) {
        return new AlertDialog(
          title: new Text(
            'New Notification!',
            style: new TextStyle(
              fontWeight: FontWeight.w800,
            )
          ),
          content: new SingleChildScrollView(
            child: new ListBody(
              children: <Widget>[
                new Text(message["summary"] ?? "You have a message"),
              ],
            ),
          ),
          actions: <Widget>[
            new FlatButton(
              textColor: Colors.red[900],
              child: new Text(
                "View",
                style: new TextStyle(fontFamily: "Roboto")
              ),
              onPressed: () {
                _navigateToItemDetail(message);
                Navigator.pop(context);
              }
            ),
            new FlatButton(
              textColor: Colors.red[900],
              child: new Text('Ignore', style: new TextStyle(fontFamily: "Roboto")),
              onPressed: () {
                Navigator.pop(context);
              },
            ),
          ],
        );
      },
    ).then((shs) {
      print("$shs results");
    });
  }

  _firebaseMessaging.configure(
    onMessage: (Map<String, dynamic> message) {
      print("onMessage: $message");
      _showItemDialog(message, context);
    },
    onLaunch: (Map<String, dynamic> message) {
      print("onLaunch: $message");
      _navigateToItemDetail(message);
    },
    onResume: (Map<String, dynamic> message) {
      print("onResume: $message");
      _navigateToItemDetail(message);
    },
  );
}
```

## Logs

```

06-16 04:40:57.314 746-885/me.my.app I/flutter: Configuring gRPC client
06-16 04:40:57.520 746-885/me.my.app I/flutter: onLaunch: {google.sent_time: 1529116807754, click_action: FLUTTER_NOTIFICATION_CLICK, collapse_key: me.my.app, summary: Testing notifications., _id: 59089fbacd6f5dff5f52e5e2, from: 570961752457, type: private_message, google.message_id: 0:1529116807764195%d1b7f70ad1b7f70a, google.ttl: 2419200}
06-16 04:40:57.675 746-746/me.my.app W/FA: setCurrentScreen cannot be called with the same class and name
06-16 04:40:57.752 746-760/me.my.app D/FirebaseAuth: Notifying id token listeners about user ( Oxxxxxxxxxxxxxxxxxxxxxxxxxxx ).
06-16 04:40:57.753 746-746/me.my.app D/FirebaseApp: Notifying auth state listeners.
    Notified 0 auth state listeners.
06-16 04:40:58.381 746-885/me.my.app I/flutter: Configuring gRPC client
06-16 04:40:58.487 746-885/me.my.app I/flutter: onLaunch: {google.sent_time: 1529116807754, click_action: FLUTTER_NOTIFICATION_CLICK, collapse_key: me.my.app, summary: Testing notifications., _id: 59089fbacd6f5dff5f52e5e2, from: 570961752457, type: private_message, google.message_id: 0:1529116807764195%d1b7f70ad1b7f70a, google.ttl: 2419200}
06-16 04:40:58.561 746-746/me.my.app W/FA: setCurrentScreen cannot be called with the same class and name
06-16 04:40:59.273 746-760/me.my.app D/FirebaseAuth: Notifying id token listeners about user ( Oxxxxxxxxxxxxxxxxxxxxxxxxxxx ).
06-16 04:40:59.275 746-746/me.my.app D/FirebaseApp: Notifying auth state listeners.
    Notified 0 auth state listeners.
06-16 04:40:59.312 746-885/me.my.app I/flutter: onLaunch: {google.sent_time: 1529116807754, click_action: FLUTTER_NOTIFICATION_CLICK, collapse_key: me.my.app, summary: Testing notifications., _id: 59089fbacd6f5dff5f52e5e2, from: 570961752457, type: private_message, google.message_id: 0:1529116807764195%d1b7f70ad1b7f70a, google.ttl: 2419200}
06-16 04:40:59.349 746-746/me.my.app W/FA: setCurrentScreen cannot be called with the same class and name
06-16 04:40:59.713 746-885/me.my.app I/flutter: Configuring gRPC client
06-16 04:40:59.872 746-885/me.my.app I/flutter: onLaunch: {google.sent_time: 1529116807754, click_action: FLUTTER_NOTIFICATION_CLICK, collapse_key: me.my.app, summary: Testing notifications., _id: 59089fbacd6f5dff5f52e5e2, from: 570961752457, type: private_message, google.message_id: 0:1529116807764195%d1b7f70ad1b7f70a, google.ttl: 2419200}
06-16 04:40:59.887 746-746/me.my.app W/FA: setCurrentScreen cannot be called with the same class and name
06-16 04:41:00.334 746-885/me.my.app I/flutter: onLaunch: {google.sent_time: 1529116807754, click_action: FLUTTER_NOTIFICATION_CLICK, collapse_key: me.my.app, summary: Testing notifications., _id: 59089fbacd6f5dff5f52e5e2, from: 570961752457, type: private_message, google.message_id: 0:1529116807764195%d1b7f70ad1b7f70a, google.ttl: 2419200}
06-16 04:41:00.379 746-746/me.my.app W/FA: setCurrentScreen cannot be called with the same class and name
06-16 04:41:02.560 746-885/me.my.app I/flutter: onLaunch: {google.sent_time: 1529116807754, click_action: FLUTTER_NOTIFICATION_CLICK, collapse_key: me.my.app, summary: Testing notifications., _id: 59089fbacd6f5dff5f52e5e2, from: 570961752457, type: private_message, google.message_id: 0:1529116807764195%d1b7f70ad1b7f70a, google.ttl: 2419200}
06-16 04:41:02.609 746-746/me.my.app W/FA: setCurrentScreen cannot be called with the same class and name
06-16 04:41:03.093 746-885/me.my.app I/flutter: onLaunch: {google.sent_time: 1529116807754, click_action: FLUTTER_NOTIFICATION_CLICK, collapse_key: me.my.app, summary: Testing notifications., _id: 59089fbacd6f5dff5f52e5e2, from: 570961752457, type: private_message, google.message_id: 0:1529116807764195%d1b7f70ad1b7f70a, google.ttl: 2419200}
06-16 04:41:03.132 746-746/me.my.app W/FA: setCurrentScreen cannot be called with the same class and name
06-16 04:41:03.707 746-885/me.my.app I/flutter: onLaunch: {google.sent_time: 1529116807754, click_action: FLUTTER_NOTIFICATION_CLICK, collapse_key: me.my.app, summary: Testing notifications., _id: 59089fbacd6f5dff5f52e5e2, from: 570961752457, type: private_message, google.message_id: 0:1529116807764195%d1b7f70ad1b7f70a, google.ttl: 2419200}
06-16 04:41:03.731 746-746/me.my.app W/FA: setCurrentScreen cannot be called with the same class and name
06-16 04:41:04.441 746-885/me.my.app I/flutter: onLaunch: {google.sent_time: 1529116807754, click_action: FLUTTER_NOTIFICATION_CLICK, collapse_key: me.my.app, summary: Testing notifications., _id: 59089fbacd6f5dff5f52e5e2, from: 570961752457, type: private_message, google.message_id: 0:1529116807764195%d1b7f70ad1b7f70a, google.ttl: 2419200}
06-16 04:41:04.471 746-746/me.my.app W/FA: setCurrentScreen cannot be called with the same class and name
06-16 04:41:05.570 746-885/me.my.app I/flutter: onLaunch: {google.sent_time: 1529116807754, click_action: FLUTTER_NOTIFICATION_CLICK, collapse_key: me.my.app, summary: Testing notifications., _id: 59089fbacd6f5dff5f52e5e2, from: 570961752457, type: private_message, google.message_id: 0:1529116807764195%d1b7f70ad1b7f70a, google.ttl: 2419200}
06-16 04:41:05.583 746-746/me.my.app W/FA: setCurrentScreen cannot be called while no activity active
```

### Flutter Analyze

*Nothing useful, only warnings about protobuf messages, which aren't related to the issue

### Plugin Version on pubspec

```
  firebase_messaging:
    dependency: "direct main"
    description:
      name: firebase_messaging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
```

### Flutter Doctor

```
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [Version 10.0.17134.81], locale en-ZA)
    • Flutter version 0.4.4 at c:\Users\me\flutter
    • Framework revision f9bb4289e9 (5 weeks ago), 2018-05-11 21:44:54 -0700
    • Engine revision 06afdfe54e
    • Dart version 2.0.0-dev.54.0.flutter-46ab040e58

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\me\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 25.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.24.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.13.2

[√] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

## More Info/Observations

The screens that I navigate to perform a lot of work, but I stripped one of them to just display the below, with no `@overrides` other than my `build(context)` function:

```dart
@override
Widget build(BuildContext context) {
  return new Container(
    child: new Text("Private Message")
  );
}
```

Even with this simple screen, I'm still seeing an infinite loop of `onLaunch` messages.

I've had this issue since I first used Firebase Messaging, and unfortunately my app's users are getting infinite loops and crashes whenever they get a notification.
I have spent a few days debugging, but have not found the problem.

I thought `FirebaseMessaging().configure` was leading to an `onLaunch` hook being registered each time the app is opened, but a freshly installed copy of the app still triggers it multiple times.

Could there be something wrong that I'm using? Thanks

**Comment by eseidelGoogle** [comment] 2018-06-18 13:02
@collinjackson might know.

**Comment by nevi-me** [comment] 2018-06-20 11:16
I've also asked a question on StackOverflow: https://stackoverflow.com/questions/50946923/firebase-messaging-infinite-onlaunch-loop

**Comment by kroikie** [comment] 2018-06-20 14:55
@nevi-me Could you please include the data you are sending? Also if you remove the navigate step from onLaunch and only do a print there do you still get the loop?

**Comment by nevi-me** [comment] 2018-06-20 16:27
Hi @kroikie When I only print text, the infinite loop stops.

Here is the data:

```js
{
    "google.sent_time": 1529510843740, 
    "click_action": "FLUTTER_NOTIFICATION_CLICK", 
    "collapse_key": "za.co.movinggauteng.mytrain", 
    "summary": "Notification text.", 
    "_id": "59089fbacd6f5dff5f52e5e2_2018160", 
    "from": "000000000000", 
    "type": "vehiclePosition", 
    "google.message_id": "0:0000000000000000%d1b7f70ad1b7f70a", 
    "google.ttl": 2419200
}
```

For reference, here's the actual code that handles navigation:

```dart
void _navigateToItemDetail(Map<String, dynamic> message) {
  if (message.containsKey("type")) {
    // handle messages by type
    String type = message["type"];
    String _id = message["_id"] ?? "";
    switch (type) {
      case "serviceAlert":
        Application.router.navigateTo(context, "/servicealert/$_id");
        break;
      case "announcement":
        FlutterWebBrowser.openWebPage(
          url: message["url"] ?? "https://movinggauteng.co.za",
          androidToolbarColor: Colors.amber
        );
        break;
      case "tripUpdate":
        Application.router.navigateTo(context, "/tripupdate/$_id");
        break;
      case "vehiclePosition":
        Application.router.navigateTo(context, "/tripupdate/$_id");
        break;
      case "nearStation":
        Application.router.navigateTo(context, "/stops/$_id");
        break;
      default:
    }
  }
}

```

From what you suggested, I can only conclude that the issue is with the router. I'm using Fluro as a router (https://github.com/theyakka/fluro), and here's my router:

```dart

import 'package:fluro/fluro.dart';

class Application {
  static Router router;
}
```

I just had a look at Fluro's GH, and I'm not seeing a similar/related issue. My codebase is a bit large, but I can try to remove Fluro and see if the issue persists. I don't have much experience with navigation, and hence I used Fluro as it seemed an easier solution to what I was trying to do.

**Comment by kroikie** [comment] 2018-06-20 16:53
@nevi-me I agree that the issue is related to the implementation of the navigation. I'll close this issue, feel free to open a new one if necessary when you have more details.

**Comment by nevi-me** [comment] 2018-06-20 16:54
I replaced Fluro's `Router` with a `Navigator` as per the below:

```dart

// from
Application.router.navigateTo(context, "/tripupdate/$_id");

// to
Navigator.push(context,
  new MaterialPageRoute<void>(builder: (BuildContext context) {
    return new BottomNavigation(
      index: 0,
      navigationObject: "TRIP_UPDATE",
      navigationObjectId: _id);
    }));
```

That made what I'm doing wrong apparent. I have a navigation bar widget, and I'm trying to navigate to a different tab on the bar. Instead of navigating, I'm instantiating the `BottomNavigation`, which must be triggering an `onLaunch` from FCM repetitively.

My app is based on https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/bottom_navigation_demo.dart, so I think I've found the problem.

**Closed by kroikie** 2018-06-20 16:53 UTC
Labels: p: firebase, severe: crash

**Comment by nevi-me** [comment] 2018-06-20 16:55
@kroikie okay, I'll try navigate within my bottom bar. That should solve the problem.

**Comment by kroikie** [comment] 2018-06-20 16:55
@nevi-me nice glad you got it resolved!

**Comment by dankop123** [comment] 2018-06-21 07:04
I'm also experiencing this issue, but I'm not using BottomNavigation. I'm just pushing to the next screen like so
Navigator.push(context, new MaterialPageRoute(builder: (_) => new LoginScreen()));

**Comment by nevi-me** [comment] 2018-06-21 08:41
Hi @dankop123, please post your widget (or the parts that are relevant). I might be able to help you.

**Comment by dankop123** [comment] 2018-06-21 09:04
```
void main() async {
  DatabaseUtils dbUtils = await DatabaseUtils.getInstance();
  User user = await dbUtils.getUser();

  runApp(new MaterialApp(
      title: 'Flutter Demo',
      theme: new ThemeData(
        primarySwatch: Colors.red,
      ),
      home: new MyApp(user: user)
  ));
}

class MyApp extends StatefulWidget {
  MyApp({Key key, this.user}) : super(key: key);

  final User user;

  @override
  _MyAppState createState() => new _MyAppState();
}

class _MyAppState extends State<MyApp> {
  _onPushNotificationReceived({Map<String, dynamic> message}) {
    print(message);
    Navigator.push(context, new MaterialPageRoute(builder: (_) => new EventScreen()));
  }

  @override
  Widget build(BuildContext context) {
    firebaseMessaging.configure(
        onMessage: (Map<String, dynamic> message) {
          _onPushNotificationReceived(message: message);
        },
        onLaunch: (Map<String, dynamic> message) {
          _onPushNotificationReceived(message: message);
        },
        onResume: (Map<String, dynamic> message) {
          _onPushNotificationReceived(message: message);
        }
    );

    firebaseMessaging.requestNotificationPermissions(
        const IosNotificationSettings(sound: true, badge: true, alert: true));
    firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      print("Settings registered: $settings");
    });
    firebaseMessaging.getToken().then((String token) {
      assert(token != null);
      print('Push token: ' + token);
    });
    return new LoggedMainScreen(user: widget.user);
  }
}

```

**Comment by nevi-me** [comment] 2018-06-21 09:52
Please override `initState() {}`, and put your configuration there. Can you also `print()` the types of events, so we can ascertain whether it's `onResume`, `onLaunch` or `onMessage` that's triggered in a loop.

**Comment by dankop123** [comment] 2018-06-21 13:35
@nevi-me when app was in the background and I've opened push the `onResume` was fired once. Next `onLaunch` was firing in the loop, but moving configuration from `build` to `initState` fixed the issue, so I guess it was my bad. Thanks a lot for help :)

**Comment by nevi-me** [comment] 2018-06-21 13:51
Great @dankop123. 

**For anyone else who ever comes to this issue. It seems that the behaviour's that if you trigger a  `FirebaseMessaging.configure()` when either initialising state (by mistake like I did), or when you're building your widget (by setting `configure` before building your widget, it'll trigger an infinite `onLaunch`**

**Comment by kroikie** [comment] 2019-10-13 19:06
@nevi-me

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/793. Any further collaboration will be done there.

**Comment by visci89** [comment] 2020-10-09 15:07
> Great @dankop123.
> 
> **For anyone else who ever comes to this issue. It seems that the behaviour's that if you trigger a `FirebaseMessaging.configure()` when either initialising state on the same widget you're navigating to (by mistake like I did), or when you're building your widget (by setting `configure` before building your widget, it'll trigger an infinite `onLaunch`**

Hi Mate, i have the same problems, my FirebaseMessaging.configure() is initialize in the same widget when I will have to navigate and this generates an infinite loops. I can't change the position of initialization of firebase because i will have to use the function on resume, on launch ecc ecc. 
do you have any tips?
