### ISSUE TITLE
[Web] When using text with emoji,  text height is incorrect on web

### ISSUE THREAD

**Issue by stoneLee81** [flutter/flutter#67732] opened 2020-10-09 14:22 UTC
When using the text widget of flutter web to display Chinese, the last line of text or emoji sometimes has insufficient height, which may obscure the text， below capture is the samples:

![image](https://user-images.githubusercontent.com/18001708/95594495-9a3fe300-0a7d-11eb-90b0-64ae7898706f.png)

![image](https://user-images.githubusercontent.com/18001708/95594507-9dd36a00-0a7d-11eb-8c01-a17fcde850e3.png)

flutter --version
Flutter 1.22.0-12.1.pre • channel unknown • unknown source
Framework • revision 8b3760638a (3 weeks ago) • 2020-09-15 17:47:13 -0700
Engine • revision 4654fc6cf6
Tools • Dart 2.10.0 (build 2.10.0-110.3.beta)

**Comment by TahaTesser** [comment] 2020-10-09 15:30
Hi @stoneLee81 
Looks like you're on unknown from 3 weeks, is this happening on mobile or web? 

Can you please upgrade to the latest  `stable` and try again
`flutter channel stable`
`flutter upgrade --force`
`flutter doctor -v`

Can you please provide your `flutter doctor -v` **with upgrade** your `flutter run --verbose` and a complete reproducible minimal code sample
Thank you

**Comment by stoneLee81** [comment] 2020-10-10 00:12
This problem occurs when displaying Chinese on PC and mobile phone。

✓] Flutter (Channel unknown, 1.22.0-12.1.pre, on Mac OS X 10.15.5 19F101, locale en-CN)
    • Flutter version 1.22.0-12.1.pre at /Volumes/data/software/flutter
    • Framework revision 8b3760638a (3 weeks ago), 2020-09-15 17:47:13 -0700
    • Engine revision 4654fc6cf6
    • Dart version 2.10.0 (build 2.10.0-110.3.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/haowmazs/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio 3.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

 
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4694.29

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.75

I use flutter web, so I can only use beta or dev branch, stable channel does not support web

**Comment by stoneLee81** [comment] 2020-10-10 01:09
![image](https://user-images.githubusercontent.com/18001708/95641961-1e26b900-0ad8-11eb-8dee-770132bb9f38.png)
This is the text directly displayed, including emoji
Container(width:150,child:Text(
              '我是用的是flutter web,所以只能使用😀beta或者dev分支，stable不支持web',
            )),

**Comment by stoneLee81** [comment] 2020-10-11 10:28
what cause it?

**Comment by stoneLee81** [comment] 2020-10-11 10:35
@TahaTesser

**Comment by TahaTesser** [comment] 2020-10-12 08:56
Hi @stoneLee81 
This is not related to Chinese, as this is easily reproducible with English text as well 

### Web (`flutter run -d chrome`)
<img width="1249" alt="Screenshot 2020-10-12 at 2 13 15 PM" src="https://user-images.githubusercontent.com/48603081/95725730-a7371f00-0c95-11eb-904f-bd927fccc26b.png">

### Mobile `flutter run`
![Simulator Screen Shot - iPhone 11 - 2020-10-12 at 14 09 46](https://user-images.githubusercontent.com/48603081/95726028-0432d500-0c96-11eb-9173-df09750254e9.png)

<details> 
<summary>complete code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          // child: Text(
          //     'Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)😀Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405'),

          child: Text(
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed egestas felis at ex fringilla consequat. Praesent enim neque, ultricies quis massa sit amet, fermentum luctus enim. Suspendisse eu libero at ligula sagittis feugiat.😎Cras eget est metus. Duis egestas tortor rhoncus erat ultricies, eget molestie lectus feugiat. Morbi turpis elit, scelerisque tincidunt nunc eget, molestie scelerisque lorem. Aenean ultrices lobortis tellus sed rutrum. Quisque pharetra erat a pellentesque accumsan.'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.22.1, on Mac OS X 10.15.7 19H2, locale en-GB)
    • Flutter version 1.22.1 at /Users/tahatesser/Code/flutter_beta
    • Framework revision f30b7f4db9 (4 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (4 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 14.0.1
    • iPhone 11 (mobile)     • FFCA7F6E-C704-436E-B356-D287FCB4D714 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel dev, 1.23.0-7.0.pre, on Mac OS X 10.15.7 19H2 x86_64,
    locale en-GB)
    • Flutter version 1.23.0-7.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision db6e2d8aa5 (2 weeks ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (4 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.0.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.7 19H2 x86_64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.23.0-8.0.pre.284, on Mac OS X 10.15.7 19H2
    x86_64, locale en-GB)
    • Flutter version 1.23.0-8.0.pre.284 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision eefcff900c (35 hours ago), 2020-10-10 23:42:02 +0200
    • Engine revision 11d756a62e
    • Dart version 2.11.0 (build 2.11.0-207.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

 
[✓] Connected device (4 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      14.0.1
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.7 19H2 x86_64
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 85.0.4183.121

• No issues found!
```

</details> 

### Canvaskit doesn't render emoji but no issues with text height 
<img width="1201" alt="Screenshot 2020-10-12 at 2 18 59 PM" src="https://user-images.githubusercontent.com/48603081/95725934-e2395280-0c95-11eb-8b8f-a83a9ae7bb36.png">

**Comment by stoneLee81** [comment] 2020-10-12 09:19
i used structStyle to solve this issue, but it's seems to be strange.

**Comment by mdebbar** [comment] 2020-10-15 21:44
Duplicate of https://github.com/flutter/flutter/issues/64792

**Closed by mdebbar** 2020-10-15 21:44 UTC
Labels: a: quality, a: typography, engine, found in release: 1.22, found in release: 1.23, framework, has reproducible steps, platform-web
