### ISSUE TITLE
White screen on flutter web 1.10.15-pre179

### ISSUE THREAD

**Issue by VodnikAngus** [flutter/flutter#43210] opened 2019-10-21 20:50 UTC
After updating flutter to newest version through AUR package flutter-git on Manjaro, Flutter Web completely stopped working.

Only showing white screen and nothing else,

Logs from Flutter doctor and verbosely running web server:
https://pastebin.com/PhneNk7n

System info:
Manjaro Linux 5.2.21, all packages updated
Flutter 1.10.15-pre.179
Ryzen 3 2200U

![Screenshot from 2019-10-21 22-46-19](https://user-images.githubusercontent.com/5102074/67242162-3891fd80-f455-11e9-9ae0-6c9b100a3dd6.png)

**Comment by jonahwilliams** [comment] 2019-10-22 01:32
I'm not able to reproduce the issue - are there any failures in the network tab? From looking at the bit of DOM it looks like something is rendering, what does you application look like?

**Comment by VodnikAngus** [comment] 2019-10-22 08:53
Nothing here either
![Screenshot from 2019-10-22 10-53-16](https://user-images.githubusercontent.com/5102074/67271110-33b36500-f4ba-11e9-9bd4-1a1d856d06e4.png)

**Comment by VodnikAngus** [comment] 2019-10-22 09:05
This is how app looks on phone
![Screenshot_20191022-110354](https://user-images.githubusercontent.com/5102074/67271922-cdc7dd00-f4bb-11e9-9b47-588f7f86ef25.png)

**Comment by yjbanov** [comment] 2019-10-24 22:18
Have you tried enabling mobile view emulation in Chrome devtools? (it's the button in the top-left corner that looks like a phone and a tablet). I'm wondering if the issue is with the layout, e.g. `MediaQuery`.

**Comment by dheerajsarwaiya** [comment] 2019-10-28 01:43
I am also facing the same problem with flutter web after upgrading to 1.10.15 .. IT was working perfectly fine then in terminal i got a message to upgrade. and as soon as I did upgrade.. the window became blank, like the ones showed in earlier comments. What is the solution?

**Comment by VodnikAngus** [comment] 2019-10-28 05:27
I have tried enabling mobile view and still nothing, no fix found

**Comment by Magenda** [comment] 2019-10-28 19:47
Same thing happens to me too, with 1.10.15 - pre284 on windows 10 both on vs-code and android studio (updated to newest releases etc) : 
"flutter run -d chrome -v" results in eternal awaiting with last output as "Attempting to connect to browser instance..". Chrome opens and remains with blank screen. 

When running with "flutter run -d web-server -v" and "flutter run --profile -d chrome -v" everything works as expected.

**Comment by VodnikAngus** [comment] 2019-10-28 19:51
For me it's not the same, flutter run -d chrome, flutter run -d web-server and flutter build web all do the same... I used headless-server before but since newest version it doesn't exist

**Comment by dheerajsarwaiya** [comment] 2019-10-28 19:55
I tried both "flutter run -d web-server -v" and "flutter run --profile -d chrome -v" .. still seeing the blank screen.

**Comment by yjbanov** [comment] 2019-10-31 22:17
Can someone please provide a small app that reproduces this?

**Comment by VodnikAngus** [comment] 2019-10-31 22:57
Ok, so it looks that my problem is actually shared_preferences package, not flutter itself, I am sorry for inconvenience, but if some of you have different problem please try to send small app for testing

**Comment by ferhatb** [comment] 2020-04-01 00:27
Closing this issue since shared_preferences package has added web support. Please reopen if you still see issue.

**Closed by ferhatb** 2020-04-01 00:27 UTC
Labels: platform-web
