### ISSUE TITLE
'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1693 pos 12: 'center!.parent == this': is not true.

### ISSUE THREAD

**Issue by dnesbala** [flutter/flutter#76767] opened 2021-02-25 07:23 UTC
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by pedromassangocode** [comment] 2021-02-25 09:10
Hi @dnesbala 
Can you please provide your `flutter doctor -v` and a minimal complete reproducible code sample?
Thank you

**Comment by dnesbala** [comment] 2021-02-25 10:00
![flutter doctor](https://user-images.githubusercontent.com/33943740/109136674-78bb6b80-7780-11eb-8670-de09629cca74.PNG)
I guess the issue is due to the wrong placement of SliverGrid and other sliver widgets.

**Comment by pedromassangocode** [comment] 2021-02-25 12:04
Hi @dnesbala 
Your Flutter version is three months old, please upgrade and try again.

> I guess the issue is due to the wrong placement of SliverGrid and other sliver widgets.
If you are sure that it this is not caused by Flutter, can we close this?
Thank you

**Closed** 2021-02-25 12:09 UTC
Labels: in triage, waiting for customer response
