### ISSUE TITLE
[Flutter for Web launch on Huawei Phone] [TextField] in Huawei Browser ,there are 2 cursors

### ISSUE THREAD

**Issue by wl1395182472** [flutter/flutter#122595] opened 2023-03-14 10:36 UTC
## Steps to Reproduce
1. create flutter application
2. input example code
3. flutter run -d web-server --web-port 8989 --web-hostname 0.0.0.0 --web-renderer html
4. Huawei Phone open Huawei Browser ,launch 'http://0.0.0.0:8989/'
5. input a few long text , it appears 2 cursors

<details>
<summary>Code sample</summary>

```dart
TextField(
   obscureText: true,
   decoration: const InputDecoration(
   hintText: 'TextField',
   border: OutlineInputBorder(),
    ),
 ),
```
</details>

<details>
  <summary>Logs</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.7, on macOS 12.6 21G115 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.76.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

```
LYA AL00 (mobile) • 3EP7N19408004804 • android-arm64  • Android 10 (API 29)
```
</details>

<details>
  <summary>my test</summary>

1.set showCursor to false
2.in other device or platform there is no cursor ,it is right
3.in Huawei Phone Huawei Browser ,that wrong cursor also exist
4.so i think that Huawei Phone Huawei Browser generate that wrong cursor 
5.but i dont know how to close or hide Huawei Phone Huawei Browser cursor

</details>

**Comment by huycozy** [comment] 2023-03-14 12:05
Hi @wl1395182472 
Unfortunately, I don't have Huawei phone to check this. Can you please provide a recorded video/GIF for this issue? 

Also, please retry on the latest Flutter master channel to see if the issue still persists or not. Thanks!

**Comment by wl1395182472** [comment] 2023-03-15 02:09
<details>
<summary>Code sample</summary>

```dart
 LimitedBox(
     maxWidth: MediaQuery.of(context).size.width / 2,
     child: const TextField(
     obscureText: true,
     showCursor: true,
     decoration: InputDecoration(
            hintText: 'hintText',
            border: OutlineInputBorder(),
            ),
     ),
),
```
</details>

<details>
  <summary>Logs</summary>

https://user-images.githubusercontent.com/55087590/225186510-4d25fa42-f25f-4ec8-978f-430ba4fb1452.mp4

</details>

**Comment by wl1395182472** [comment] 2023-03-15 02:11
<details>
<summary>Code sample</summary>

```dart
 LimitedBox(
     maxWidth: MediaQuery.of(context).size.width / 2,
     child: const TextField(
     obscureText: true,
     showCursor: false,
     decoration: InputDecoration(
            hintText: 'hintText',
            border: OutlineInputBorder(),
            ),
     ),
),
```
</details>

<details>
  <summary>Video</summary>

https://user-images.githubusercontent.com/55087590/225186668-2d726c11-bafc-41c2-8569-89c42d9e7a52.mp4

</details>

**Comment by wl1395182472** [comment] 2023-03-15 02:16
<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    super.key,
  });

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: <Widget>[
            LimitedBox(
              maxWidth: MediaQuery.of(context).size.width / 2,
              child: const TextField(
                obscureText: true,
                showCursor: false,
                decoration: InputDecoration(
                  hintText: 'hintText',
                  border: OutlineInputBorder(),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by wl1395182472** [comment] 2023-03-15 02:20
I think Huawei browser is the reason, but other web page input boxes do not have this problem. So I still raised this question. Also, I want to know how to modify the web/index.html file to cancel or hide the browser's cursor. I have tried many ways, but still have no effect.

**Comment by wl1395182472** [comment] 2023-03-15 02:21
<details>
<summary>Code sample</summary>

```dart
<!DOCTYPE html>
<html>

<head>
  <base href="$FLUTTER_BASE_HREF">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="flutter_test_imagenetwork">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png" />

  <title>flutter_test_imagenetwork</title>
  <link rel="manifest" href="manifest.json">

  <script>
    var serviceWorkerVersion = null;
  </script>
  <script src="flutter.js" defer></script>
  <style>
    body {
      cursor: none;
    }
  </style>
</head>

<body>
  <script>
    window.addEventListener('load', function (ev) {
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function (engineInitializer) {
          engineInitializer.initializeEngine().then(function (appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
</body>

</html>
```
</details>

**Comment by huycozy** [comment] 2023-03-15 04:37
Thanks for providing more information. I see there's an open issue addressing the case you described https://github.com/flutter/flutter/issues/118838 and it is marked as a duplicate of https://github.com/flutter/flutter/issues/94130. 

Closing this issue as a duplicate, so please follow up on #94130 for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Closed by huycozy** 2023-03-15 04:37 UTC
Labels: in triage
