### ISSUE TITLE
Using an AssetImage in a BoxDecoration uses wrong scale

### ISSUE THREAD

**Issue by tingyouw** [flutter/flutter#17124] opened 2018-04-30 19:02 UTC
## Steps to Reproduce

I am attempting to use an asset image to repeat itself as the background of a container, however, as soon as I use the image in a BoxDecoration, the scale is wrong. It seems to pick the right asset from the N.Nx/ directory, but then shows it at that scale (as opposed to scaling it down to fit the dpi).

When just using a direction Image.asset or Image(...) the right scale is used.

Example snippet:

```
new Stack(
    children: [
      new Image(
        image: new AssetImage('assets/my.png'),
        fit: BoxFit.scaleDown,
      ),
      new Container(
        constraints: new BoxConstraints.expand(),
        decoration: new BoxDecoration(
           image: new DecorationImage( 
             image: new AssetImage('assets/my.png'),
             repeat: ImageRepeat.repeat,
           ),
        ),
      ),
    ],
),
```

**Comment by tingyouw** [comment] 2018-04-30 19:32
Screenshot (didn't use repeat, and has same issue). Expected that these two would be the same size:

![screen shot 2018-04-30 at 12 30 35 pm](https://user-images.githubusercontent.com/38863203/39446150-6285236a-4c72-11e8-96e8-16edb82c69cf.png)

**Comment by zoechi** [comment] 2018-07-26 08:16
Sorry for the late response.
Is this still an issue with recent Flutter versions?

**Comment by tingyouw** [comment] 2018-09-05 20:43
Sorry about the late reply. This still seems to be happening. Getting flutter doctor output.

**Comment by mehmetf** [comment] 2018-09-05 20:47
@zoechi This is still an issue and it is affecting a Google customer who are on a fairly recent version of Flutter at all times.

**Comment by Hixie** [comment] 2018-09-05 23:07
is this resolved by https://github.com/flutter/flutter/pull/20791 ?

**Comment by mehmetf** [comment] 2018-09-05 23:33
Yes, I think this is a dupe of https://github.com/flutter/flutter/issues/18682. Closing.

@tingyouw The fix for this should land very soon.

**Closed by mehmetf** 2018-09-05 23:33 UTC
