### ISSUE TITLE
FormatException: FormatException: Bad UTF-8 encoding 0xa1 (at offset 198)

### ISSUE THREAD

**Issue by wmq911** [flutter/flutter#28443] opened 2019-02-25 06:00 UTC
**No problem with debugging**

windows10 +  android studio
 flutter build apk 

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk

## exception

FormatException: FormatException: Bad UTF-8 encoding 0xa1 (at offset 198)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:518:13)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:311:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#11     _StreamController._add (dart:async/stream_controller.dart:640:7)
#12     _StreamController.add (dart:async/stream_controller.dart:586:5)
#13     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1722:41)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#20     _StreamController._add (dart:async/stream_controller.dart:640:7)
#21     _StreamController.add (dart:async/stream_controller.dart:586:5)
#22     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1284:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.590], locale zh-CN)
    [32m•[39m Flutter version 1.1.8 at D:\Git\flutter
    [32m•[39m Framework revision 985ccb6d14 (7 weeks ago), 2019-01-08 13:45:55 -0800
    [32m•[39m Engine revision 7112b72cc2
    [32m•[39m Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 33.1.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.31.1)
    [32m•[39m VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 2.23.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m Google Nexus 5 • 192.168.58.101:5555 • android-x86 • Android 4.4.4 (API 19)

[32m•[39m No issues found!
```

**flutter doctor**
```
D:\Git\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.590], locale zh-CN)
    • Flutter version 1.1.8 at D:\Git\flutter
    • Framework revision 985ccb6d14 (7 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.1

[√] Connected device (1 available)
    • Google Nexus 5 • 192.168.58.101:5555 • android-x86 • Android 4.4.4 (API 19)

• No issues found!
```

**Comment by zoechi** [comment] 2019-02-25 06:19
Switch to `dev` channel
```
flutter channel dev
flutter doctor
```

**Comment by zoechi** [comment] 2019-02-25 06:19
Duplicate of #15646

**Closed by zoechi** 2019-02-25 06:19 UTC
