### ISSUE TITLE
Scrollbar indicator showing incorrectly when wrapped outside horizontal listview - Issue in iphone XR

### ISSUE THREAD

**Issue by raman-kumar-ha** [flutter/flutter#124669] opened 2023-04-12 10:34 UTC
Scrollbar indicator showing incorrectly when wrapped outside horizontal listview - Issue in iphone XR

Screenshot attached
![IMG_0843](https://user-images.githubusercontent.com/92308988/231432412-c0b76591-80fd-4bd8-b8f8-ba5cf48ec01e.png)

Code
```
return Scrollbar(
      isAlwaysShown: true,
      thickness: 1,
      child: ListView.separated(
        physics: const AlwaysScrollableScrollPhysics(),
        shrinkWrap: true,
        scrollDirection: Axis.horizontal,
        padding: const EdgeInsets.all(0),
        itemCount: coordinators.length,
        separatorBuilder: (context, index) {
          return const SizedBox(
            width: StyleConfiguration.fontSize20,
          );
        },
        itemBuilder: (context, i) {
          return Card(...),
          );
        },
      ),
    );
```

**Comment by danagbemava-nc** [comment] 2023-04-12 12:37
Hi @raman-kumar-ha,

Please provide your `flutter doctor -v` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) along with steps to reproduce so that we can investigate this issue.  The code sample that you have provided is not complete. 

Please also try to provide a sample without any third-party plugins or packages. 

Thank you

**Comment by raman-kumar-ha** [comment] 2023-04-13 04:46
Okay let me add that.

**Comment by raman-kumar-ha** [comment] 2023-04-18 12:33
Flutter doctor

```
/Users/admin/Documents/flutter_sdk/flutter-sdk-3.3.10/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.5 21G72 darwin-arm, locale en-IN)
    • Flutter version 3.3.10 on channel stable at /Users/admin/Documents/flutter_sdk/flutter-sdk-3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5556 • android-arm64  • Android 13 (API 33) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.5 21G72 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 112.0.5615.49

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
Process finished with exit code 0
```

Relevant code

```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    const title = 'Horizontal List';
    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: const Text(title),
        ),
        body: Container(
          margin: const EdgeInsets.symmetric(vertical: 20.0),
          height: 200.0,
          child: Scrollbar(
            isAlwaysShown: true,
            child: ListView(
              // This next line does the trick.
              scrollDirection: Axis.horizontal,
              children: <Widget>[
                Container(
                  width: 160.0,
                  color: Colors.red,
                ),
                Container(
                  width: 160.0,
                  color: Colors.blue,
                ),
                Container(
                  width: 160.0,
                  color: Colors.green,
                ),
                Container(
                  width: 160.0,
                  color: Colors.yellow,
                ),
                Container(
                  width: 160.0,
                  color: Colors.orange,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```


<img width="375" alt="Screenshot 2023-04-18 at 6 02 11 PM" src="https://user-images.githubusercontent.com/92308988/232778282-b29aff1a-d4ab-4832-867a-ab39f621b4fc.png">

**Comment by danagbemava-nc** [comment] 2023-04-18 13:06
This is a duplicate of https://github.com/flutter/flutter/issues/57920. 

Kindly follow up in the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-04-18 13:06 UTC
Labels: in triage
