### ISSUE TITLE
[google_maps_flutter] markers flicker on updating by setState()

### ISSUE THREAD

**Issue by NikosTsesmelis** [flutter/flutter#122401] opened 2023-03-10 14:14 UTC
The markers flicker and reposition momentarily when they change in Android.
You can test it by pressing repetedly any of the buttons to update the markers.

google_maps_flutter: 2.2.5

[✓] Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-arm64, locale en-GR)
    • Flutter version 3.7.7 on channel stable at /Users/nikostsesmelis/Tools/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (2 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1

```
class TestScreen extends StatefulWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  Set<Marker> _markers = {};

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      _setRedMarkers();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: GoogleMap(
              initialCameraPosition: const CameraPosition(
                target: LatLng(37.3861, -122.0839),
                zoom: 14,
              ),
              markers: _markers,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(32),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                _button('RED', Colors.red, _setRedMarkers),
                _button('GREEN', Colors.green, _setGreenMarkers),
                _button('BLUE', Colors.blue, _setBlueMarkers),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _button(String text, Color color, VoidCallback onTap) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        color: color,
        padding: const EdgeInsets.all(16),
        child: Text(text),
      ),
    );
  }

  void _setRedMarkers() async {
    _setMarkers('assets/images/red.png');
  }

  void _setGreenMarkers() async {
    _setMarkers('assets/images/green.png');
  }

  void _setBlueMarkers() async {
    _setMarkers('assets/images/blue.png');
  }

  void _setMarkers(String assetPath) async {
    Uint8List? byteData = await _getBytesFromAsset(assetPath, 30);
    if (byteData == null) return;

    BitmapDescriptor icon = BitmapDescriptor.fromBytes(byteData);

    setState(() {
      _markers = {
        Marker(
          markerId: const MarkerId('1'),
          position: const LatLng(37.3861, -122.0839),
          icon: icon,
        ),
        Marker(
          markerId: const MarkerId('2'),
          position: const LatLng(37.3761, -122.0839),
          icon: icon,
        ),
        Marker(
          markerId: const MarkerId('3'),
          position: const LatLng(37.3961, -122.0839),
          icon: icon,
        ),
      };
    });
  }

  Future<Uint8List?> _getBytesFromAsset(String path, int width) async {
    ByteData data = await rootBundle.load(path);
    Codec codec = await instantiateImageCodec(
      data.buffer.asUint8List(),
      targetWidth: width,
    );
    FrameInfo fi = await codec.getNextFrame();
    return (await fi.image.toByteData(format: ImageByteFormat.png))?.buffer.asUint8List();
  }
}
```

**Comment by huycozy** [comment] 2023-03-13 05:26
I'm not sure what `flicker` behavior you're seeing as they look fine from my side (check out the video demo). Verifying on Realme 6, Android 11.

Which device are you using? (OS, model). It would be appreciated if you could provide a demo video as well. Thanks!

<details>
<summary>Demo</summary>


https://user-images.githubusercontent.com/104349824/224614806-626e0c8b-61c8-4fbb-913d-2a8eb92fba2b.mp4


</details>

<details>
<summary>Complete sample code</summary>

```dart
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(const MaterialApp(home: TestScreen()));
}

class TestScreen extends StatefulWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  Set<Marker> _markers = {};

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      _setRedMarkers();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(
            child: GoogleMap(
              initialCameraPosition: const CameraPosition(
                target: LatLng(37.3861, -122.0839),
                zoom: 14,
              ),
              markers: _markers,
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(32),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                _button('RED', Colors.red, _setRedMarkers),
                _button('GREEN', Colors.green, _setGreenMarkers),
                _button('BLUE', Colors.blue, _setBlueMarkers),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _button(String text, Color color, VoidCallback onTap) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        color: color,
        padding: const EdgeInsets.all(16),
        child: Text(text),
      ),
    );
  }

  void _setRedMarkers() async {
    _setMarkers('assets/red.png');
  }

  void _setGreenMarkers() async {
    _setMarkers('assets/green.png');
  }

  void _setBlueMarkers() async {
    _setMarkers('assets/blue.png');
  }

  void _setMarkers(String assetPath) async {
    Uint8List? byteData = await _getBytesFromAsset(assetPath, 30);
    if (byteData == null) return;

    BitmapDescriptor icon = BitmapDescriptor.fromBytes(byteData);

    setState(() {
      _markers = {
        Marker(
          markerId: const MarkerId('1'),
          position: const LatLng(37.3861, -122.0839),
          icon: icon,
        ),
        Marker(
          markerId: const MarkerId('2'),
          position: const LatLng(37.3761, -122.0839),
          icon: icon,
        ),
        Marker(
          markerId: const MarkerId('3'),
          position: const LatLng(37.3961, -122.0839),
          icon: icon,
        ),
      };
    });
  }

  Future<Uint8List?> _getBytesFromAsset(String path, int width) async {
    ByteData data = await rootBundle.load(path);
    Codec codec = await instantiateImageCodec(
      data.buffer.asUint8List(),
      targetWidth: width,
    );
    FrameInfo fi = await codec.getNextFrame();
    return (await fi.image.toByteData(format: ImageByteFormat.png))?.buffer.asUint8List();
  }
}
```
</details>

**Comment by NikosTsesmelis** [comment] 2023-03-13 08:13
It happens randomly mostly when pressing in quick succession.

Tested on pixel 4a(android 13) and xiaomi 8a(android 10)

https://user-images.githubusercontent.com/100851392/224643254-cc1fa2b4-c063-4dc2-b591-2a80a9dde84b.mp4

**Comment by huycozy** [comment] 2023-03-13 11:39
Hmm, I still can not reproduce this issue on my devices (Realme 6, Android 11 and Pixel 3a, Android 12). Can you provide a complete sample project? (a GitHub project would be better since it contains assets).

Also, please retry on the latest Flutter master channel as well. Thanks!

**Comment by NikosTsesmelis** [comment] 2023-03-13 14:36
I just tested it on master with the same results. 
I run the example on my normal project because otherwise I have to set everything for the map from the beginning so I have no complete project.
This happens to me 100% of the time on all my phones. I cannot see it on the emulator though.
I used these resources for the test project but I dont think that i matters because in my real project the pins are completely different and still dont work.
[Archive.zip](https://github.com/flutter/flutter/files/10958388/Archive.zip)

https://user-images.githubusercontent.com/100851392/224733370-52c08a9e-9c5c-4ad2-a266-5dacb5a5b2c9.mp4

**Comment by huycozy** [comment] 2023-03-14 04:06
>I run the example on my normal project because otherwise I have to set everything for the map from the beginning so I have no complete project.

Okay, this is just to confirm the example you are testing doesn't have any "redundant" settings thay may be missing here. 

This issue seems to be device-specific issue as you also don't see it on emulator.

However, I see there's an open issue addressing the case you described #78638. This issue is also happening when updating markers with `setState` (see https://github.com/flutter/flutter/issues/78638#issuecomment-805022065 and https://github.com/flutter/flutter/issues/78638#issuecomment-881336921).

So I will close this issue in favor of #78638, so please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. Thank you!

**Comment by NikosTsesmelis** [comment] 2023-03-14 08:15
I am sorry but this is not the same issue. From what i see in the other issue they force the map to be rebuild with every setState which doesn't seem to have anything to do with the map itself. I am describing that the map doesn't build the correct markers sometimes. And is seems like there is more than one update happening in every frame.

**Comment by huycozy** [comment] 2023-03-15 03:48
Thanks for your response. I re-open this for further investigation. 

I watched the demo video on the [SO question](https://stackoverflow.com/questions/66245336/flutter-constant-flickering-in-the-map?noredirect=1#comment117118610_66245336) from that issue, it seems the flick happens to the whole map instead of markers. 

Can you please retry this on the latest master channel and Flutter `3.3.10`? (to check if it's better on the latest Flutter version, and also check regression if any). Also, it would be great if you could test this on other devices as well. Thanks!

**Comment by NikosTsesmelis** [comment] 2023-03-15 10:42
I have not encountered any kind of flickering happening to the whole map.
As you can see from my video just the markers seem to be painted incorrectly sometimes especially when they are updated rapidly.
I tested on master and 3.3.10 and the results are the same.
I also tested in 3 physical devices and the results are the same.

**Comment by huycozy** [comment] 2023-03-16 04:50
Thanks for your response. It seems to be a specific-device issue since I can not reproduce it from my end. Labeling the issue for further investigation. 

### Issue reports
- Sample code and plugin version: https://github.com/flutter/flutter/issues/122401#issue-1619049532
- Demo: https://github.com/flutter/flutter/issues/122401#issuecomment-1465688874
- Issue can be found on devices: `pixel 4a(android 13)` and `xiaomi 8a(android 10)`
- It's reproducible on Flutter stable 3.7.7, latest master, and 3.3.10.

**Comment by stuartmorgan** [comment] 2023-03-21 19:43
Could you verify whether this happens in a non-Flutter app using Google Maps on the same devices? This may be an issue in the Google Maps SDK itself (or it may be specific to how we are updating markers).

**Comment by NikosTsesmelis** [comment] 2023-03-22 10:47
Tested it using com.google.android.gms:play-services-maps:18.1.0 and the issue is not present in the native android app.

**Comment by itssidhere** [comment] 2023-04-15 00:23
If we push a route on top of the widget which uses google maps and the route uses setState several times for example a route that uses arcore_flutter_plugin, the app simply crashes

**Comment by nabildroid** [comment] 2023-07-22 16:27
i have the same issue, when updating the markers, some of them keep appearing despite that the list has been changed and doesn't include that markers, i did debug and put debug points, and the list is 100% updated but the markers are glued to the google map

**Comment by nabildroid** [comment] 2023-07-23 16:24
for anyone who experiences the same issue, it turns out that updating the markers is very rapid and the parent widget has multiple states that are also updated, each with a separated setState, is what causes the map to "miss" removing markers 
say you put a lot of markers and delete them then add new set and lot of other updates happen sequentially and every setState cause the wrapping widget to update, one miss removing will cause the marker to be placed on the map for ever 

in my case, the Google map widget was inside a parent widget that was watching the state "context.watch" and also has its own setState so lot of markers updates and widget updates a miss accused

**Comment by NikosTsesmelis** [comment] 2023-07-25 07:08
Actually I believe this is the same issue with this one -> https://github.com/flutter/flutter/issues/128405

**Comment by huycozy** [comment] 2023-07-25 07:33
It seems so. Perhaps we already forgot to check AndroidMapRenderer as above discussion. That's why I couldn't reproduce this issue.

I will close this issue to centralize on that one since that issue has been reproduced with detailed steps. Please follow up on that issue for updates.

**Closed by huycozy** 2023-07-25 07:33 UTC
Labels: e: device-specific, platform-android, c: performance, p: maps, package, P2, team-android, triaged-android, multiteam-retriage-candidate
