### ISSUE TITLE
java.lang.module.findexception: Module java.se.ee not found

### ISSUE THREAD

**Issue by kaankoken** [flutter/flutter#25811] opened 2018-12-27 15:57 UTC
Hi everyone.

I am trying to install Flutter on my Arch Linux. This is my system properties:
> System:    Host: legolas Kernel: 4.19.12-arch1-1-ARCH x86_64 bits: 64 compiler: gcc v: 8.2.1 Desktop: 
    KDE Plasma 5.14.4 
           Distro: Arch Linux 
    Machine:   Type: Laptop System: Dell product: Inspiron 7370 v: N/A serial: <root required> 
           Mobo: Dell model: 05M4XD v: A00 serial: <root required> UEFI: Dell v: 1.11.0 date: 07/19/2018 
    Battery:   ID-1: BAT0 charge: 26.2 Wh condition: 27.2/38.0 Wh (72%) model: SMP DELL 39DY56B status: 
    Charging 
    CPU:       Topology: Quad Core model: Intel Core i7-8550U bits: 64 type: MT MCP arch: Kaby Lake rev: A 
    L2 cache: 8192 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 31880 
           Speed: 900 MHz min/max: 400/4000 MHz Core speeds (MHz): 1: 900 2: 900 3: 900 4: 900 5: 900 6:   
    900 7: 900 8: 900 
    Graphics:  Device-1: Intel UHD Graphics 620 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.3 driver: modesetting resolution: 1920x1080~60Hz 
           Message: Unable to show advanced data. Required tool glxinfo missing. 
    Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Dell driver: snd_hda_intel v: kernel bus ID: 
    00:1f.3 
           Sound Server: ALSA v: k4.19.12-arch1-1-ARCH 
    Network:   Device-1: Intel Wireless 7265 driver: iwlwifi v: kernel port: f040 bus ID: 01:00.0 
           IF: wlp1s0 state: up mac: 00:e1:8c:b0:6d:9b 
           Device-2: Realtek RTL8153 Gigabit Ethernet Adapter type: USB driver: r8152 bus ID: 2-4.1:7 
           IF: enp0s20f0u4u1 state: up speed: 10 Mbps duplex: half mac: 00:e0:4c:68:0c:15   
    Drives:    Local Storage: total: 357.72 GiB used: 46.81 GiB (13.1%) 
           ID-1: /dev/sda type: USB vendor: Generic model: SD MMC MS PRO size: 119.25 GiB 
           ID-2: /dev/sdb vendor: SK Hynix model: SC311 SATA 256GB size: 238.47 GiB 
    Partition: ID-1: / size: 223.38 GiB used: 46.76 GiB (20.9%) fs: ext4 dev: /dev/sdb3 
           ID-2: /boot size: 524.0 MiB used: 55.1 MiB (10.5%) fs: vfat dev: /dev/sdb1 
           ID-3: swap-1 size: 10.00 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sdb2 
    Sensors:   System Temperatures: cpu: 45.0 C mobo: 44.0 C sodimm: 44.0 C 
           Fan Speeds (RPM): cpu: 3411 
    Info:      Processes: 238 Uptime: 53m Memory: 7.54 GiB used: 2.58 GiB (34.2%) Init: systemd Compilers: 
    gcc: 8.2.1 Shell: bash 
           v: 4.4.23 inxi: 3.0.29 

I have a problem with licensing. When I am trying to license with `flutter doctor --android-licenses`, I got this error:
> A newer version of the Android SDK is required. To update, run:/opt/android- 
   sdk/tools/bin/sdkmanager --update

When I run `sdkmanager --update ` or `sdkmanager --licenses`, I got this error:
> Error occurred during initialization of boot layer
    java.lang.module.FindException: Module java.se.ee not found

This is my `flutter doctor -v`

> [✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /opt/flutter
    • Framework revision 5391447fae (4 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

> [!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.1+13)
    ✗ Android license status unknown.

> [!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

> [!] Connected device
    ! No devices available

> ! Doctor found issues in 3 categories.

How can I solve it? I tried many solutions for this.

**Comment by zoechi** [comment] 2018-12-27 16:10
Duplicate of #22361

**Comment by zoechi** [comment] 2018-12-27 16:10
Use Java 1.8 for now instead of 1.11

**Closed by zoechi** 2018-12-27 16:10 UTC

**Comment by fayaz112** [comment] 2019-04-21 19:50
iam using java 1.8 but yet same error

**Comment by Recognized** [comment] 2019-07-22 09:22
Reopen this issue. Java 1.8 is obsolete now.

**Comment by abdrmdn** [comment] 2019-09-10 09:32
This workaround fixes it for me 

> I had the exact same error. I resolved it by removing an export I put when my Android SDK was not showing up (from this issue):
> 
> export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
> 
> Make sure your restarting your terminal when you remove that line.

From this issue: https://github.com/flutter/flutter/issues/16093#issuecomment-390489264

**Comment by shea-hawkins** [comment] 2019-11-01 21:31
This workaround only works for Java 9-10, java 11 removed java.se.ee entirely.

The Google team has known about the deprecation of se.ee since 2017. It's fucking retarded that they haven't updated it.

**Comment by Hoossayn** [comment] 2020-07-22 00:15
@shea-hawkins   where can i find the java.se.ee file to remove on my ubuntu

**Comment by tahadostifam** [comment] 2021-05-17 19:08
this error is very nerve-wracking - and I still couldn't fix it
If anyone has a solution, please suggest it...
thanks

**Comment by tahadostifam** [comment] 2021-05-20 19:52
im try `sdmanager --help` command with superuser(**sudo**)... its work fine :)))
