### ISSUE TITLE
Post-process TypeError messages that are caught by the framework

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter#16260] opened 2018-04-05 00:50 UTC
## Steps to Reproduce

Run a program containing the follow (somewhat naive) code:

```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(
          title: new Text('Type example'),
        ),
        body: new Column(
          children: buildContents(),
        ));
  }
}

List buildContents() {
  var l = new List();
  l.add(new Text('Text 1'));
  l.add(new Object()); // This could be any non-Widget added by mistake.
  l.add(new Text('Text 2'));
  return l;
}
```

This produces hundreds of lines of output:
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       1.0s
Resolving dependencies...                                    0.8s
Running 'gradlew assembleDebug'...                           8.3s
Built build/app/outputs/apk/debug/app-debug.apk (30.4MB).
Installing build/app/outputs/apk/app.apk...                  1.6s
I/FlutterActivityDelegate( 6791): onResume setting current activity to this
I/flutter ( 6791): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6791): The following assertion was thrown building MyHomePage(dirty):
I/flutter ( 6791): type 'List<dynamic>' is not a subtype of type 'List<Widget>' where
I/flutter ( 6791):   List is from dart:core
I/flutter ( 6791):   List is from dart:core
I/flutter ( 6791):   Widget is from package:flutter/src/widgets/framework.dart
I/flutter ( 6791):
I/flutter ( 6791): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6791): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6791): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6791):   https://github.com/flutter/flutter/issues/new
I/flutter ( 6791):
I/flutter ( 6791): When the exception was thrown, this was the stack:
I/flutter ( 6791): #0      MyHomePage.build (file:///Users/mit/tmp/test45/lib/main.dart:41:21)
I/flutter ( 6791): #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)
I/flutter ( 6791): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
...
```

Full details in: https://gist.github.com/mit-mit/2e59b8ccc73e1f8f9cc6f00374ef71fb

Specific issues:

1. It's hard to see where the error occurred. Can we mention `main.dart:41:41` next to the typing error at the top?
1. Contains the somewhat scary message 'Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.'
1. Do we need all those lines of stack output? Seem like just the first line has any value for these cases?
1. Can we omit the 'EXCEPTION CAUGHT' and 'The following assertion was thrown' parts, and just say 'main.dart line 41 failed a runtime type check' or something simpler like that?

**Comment by mit-mit** [comment] 2018-04-05 00:51
cc @a-siva @Hixie

**Comment by Hixie** [comment] 2018-04-05 16:59
> It's hard to see where the error occurred. Can we mention `main.dart:41:41` next to the typing error at the top?

Usually, doing that would point the error at something useless like the source for `_AssertionError` or `Object.noSuchMethod` or some internal method of `RenderObject` or some such. It's rare that the exception is actually thrown from the exact line that has the problem.

We could special-case type errors if we had a way to recognize them, though I fear that would often result in us pointing the finger inside framework code.

This specific error is one I would have expected the analyzer to catch. You shouldn't ever see this exception if the code is analysis-clean as far as I can tell. If we could recognize this specific exception we could maybe suggest checking the analyzer first?

> Contains the somewhat scary message

Why is that message scary? It was supposed to be reassuring, by telling people that it was probably not their fault, and that they should report it.

> Do we need all those lines of stack output? Seem like just the first line has any value for these cases?

Fixing https://github.com/flutter/flutter/issues/4174 should improve that, but in the general case we don't know what the error is or whether the stack will be useful, so it's hard to know whether to include it or not. In this case, sure, the first line is the only one that matters. But that's very rarely the case. Often the stack is actually quite useful for diagnosing the issue.

> Can we omit the 'EXCEPTION CAUGHT' and 'The following assertion was thrown' parts, and just say 'main.dart line 41 failed a runtime type check' or something simpler like that?

The purpose of those lines is to separate the output from the many other lines of output that are common when debugging (e.g. other exceptions). I think it's valuable to have the exception very well delineated. Can you elaborate on why the header is not simple? (It's not redundant; both of those lines contain information that varies from error to error.)

**Comment by Hixie** [comment] 2018-04-06 19:26
(The reason I would except the analyzer to catch it is because it's statically detectable. `children` expects a `List<Widget>`, so `buildContents` should have its return type inferred as `List<Widget>`, not `List<dynamic>`, IMHO. Then where the list is constructed, it should infer `Widget` as the type argument, and when you add the `Object`, the analyzer should say that doesn't work. Maybe the analyzer isn't yet that clever, though.)

**Comment by mit-mit** [comment] 2018-04-11 17:57
Moving this one back to milestone 3; @a-siva promised to investigate yesterday.

**Comment by Hixie** [comment] 2018-04-13 01:05
I don't really understand what's wrong with the message. It seems great to me. It has lots of information and points you right to the cause.

**Comment by mit-mit** [comment] 2018-04-13 10:42
As mentioned above, I think there are two usability issues. cc @InMatrix also in case he has opinions:

**1) Unspecific error message.**

As Siva mentioned, we know when we throw the TypeError what the exact reason is. But we don't state that, we show a generic framework assert.

And to make things words, we include this misleading bit:

```
I/flutter ( 6791): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6791): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6791): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6791):   https://github.com/flutter/flutter/issues/new
```

**2) Too much information**

Yes, the message has lots of information, but that is not always a good thing. There are almost 250 lines of stack output, but it looks like just a single one (the first) has any relevance.

**Comment by InMatrix** [comment] 2018-04-15 05:55
@mit-mit I agree with both issues you identified.

I'd like to collect issues related to unhelpful error messages for my incoming summer intern who's interested in improving them for Flutter. It looks like we don't have a label for error message-related issues. Should we create a label for this type of issue? Otherwise, I'll collect issues I'm aware of in a doc.

**Comment by Hixie** [comment] 2018-04-17 23:36
> As Siva mentioned, we know when we throw the TypeError what the exact reason is. But we don't state that, we show a generic framework assert.

We should the exact message:

> ```
> I/flutter ( 6791): type 'List<dynamic>' is not a subtype of type 'List<Widget>' where
> I/flutter ( 6791):   List is from dart:core
> I/flutter ( 6791):   List is from dart:core
> I/flutter ( 6791):   Widget is from package:flutter/src/widgets/framework.dart
> ```

I don't understand what is missing?

> 2) Too much information
>
> Yes, the message has lots of information, but that is not always a good thing. There are almost 250 lines of stack output, but it looks like just a single one (the first) has any relevance.

How do we know which line is relevant? See my comment above: https://github.com/flutter/flutter/issues/16260#issuecomment-379352186

**Comment by InMatrix** [comment] 2018-04-23 04:00
```
I/flutter ( 6791): type 'List<dynamic>' is not a subtype of type 'List<Widget>' where
I/flutter ( 6791):   List is from dart:core
I/flutter ( 6791):   List is from dart:core
I/flutter ( 6791):   Widget is from package:flutter/src/widgets/framework.dart
```
> I don't understand what is missing?

This part is Okay for this snippet, as long as there is only one List in question. If the user touched two List objects from the last known good state, the user then needs to check both until finding the problem. 

> 2. Too much information

At lease in this case, the lines below the first 6 lines about type mismatch did not provide actionable information to the user. Showing them by default and all at once is overwhelming and can cause unnecessary anxiety. This also pushes the more relevant first few lines way up in the output window, and the user now needs to scroll back several screens to see them. A better experience might be showing more details only when the user requests to see more, similar to having a --verbose option in a command. In a modern IDE, we can also consider showing the first few lines of the stack trace and provide an UI affordance (e.g., `...`) to expand the message.

**Comment by Hixie** [comment] 2018-04-23 19:36
> At lease in this case

That's the key problem. We have no way to distinguish this case from the other (potentially more common) case I listed above.

I agree that IDEs should not scroll past these messages, but that seems like an IDE issue, rather than an issue with the framework?

**Comment by mit-mit** [comment] 2018-04-24 11:27
> That's the key problem. We have no way to distinguish this case from the other (potentially more common) case I listed above.

Maybe I misunderstood https://github.com/flutter/flutter/issues/16260#issuecomment-380973043, but from that it looks like type errors caught by Dart trigger a `TypeError`, so is it not just a matter of catching that?

**Comment by devoncarew** [comment] 2018-04-30 16:24
Some thoughts:

1) re: IDE stacktrace collapsing

We do do this already in IntelliJ (however, depending on the stack trace prefix, we may not catch all places we should collapse).

2) re: the `Either the assertion indicates an error in the framework itself...` message

I'm not sure why we need this? As a user, this would be a confusing message to receive. We could just remove this and assume that the exception message and stacktrace will provide specific enough info to be actionable.

3) re: the repeated `List is from dart:core`, `List is from dart:core` messages

This is also confusing to me to see; it seems like it's trying to point out an issue, when  - after understanding it and re-reading it - it's clearer that there's no issue. I'm guessing that this is trying to de-dupe class with the same name but loaded from different libraries. I think to improve this we could remove all lines about which libraries the classes are from, unless there are classes with the same names form different libraries.

**Comment by Hixie** [comment] 2018-04-30 16:38
> Maybe I misunderstood https://github.com/flutter/flutter/issues/16260#issuecomment-380973043, but from that it looks like type errors caught by Dart trigger a `TypeError`, so is it not just a matter of catching that?

I could be wrong but I believe the exception in https://github.com/flutter/flutter/issues/16260#issuecomment-379352186 is also a TypeError. This is the case where I'm saying we can't distinguish between this case and that case, and where different parts of the stack are important.

I suppose what we could do is filter out framework stack lines for TypeErrors? That might work pretty well. Should we update this bug to be specifically about doing that?

(Specifically, any sequence of stack lines that are from package:flutter or dart:* and are between two other lines that are also from package:flutter or dart:* would be either omitted or replaced by an ellipsis, unless some global `debugDumpFullStacksInExceptions` flag was set.)


> 2) re: the `Either the assertion indicates an error in the framework itself...` message
>
>I'm not sure why we need this? As a user, this would be a confusing message to receive. We could just >remove this and assume that the exception message and stacktrace will provide specific enough info to >be actionable.

This message is included in any exception where we're not confident that the error is the user's fault. There are many exceptions (including TypeError exceptions) where the error is actually our fault, and we want the user to file a bug rather than bang their head against the framework.

What we could do is hide this message in the case where the top line in the stack is from non-framework code, though. That would make sense. Should we update this bug to be specifically about doing that?


>3) re: the repeated `List is from dart:core`, `List is from dart:core` messages

The actual exception text comes from the compiler. I agree that it could be clearer. To have that changed we should probably file a bug on the Dart SDK.

**Comment by devoncarew** [comment] 2018-04-30 17:43
> What we could do is hide this message in the case where the top line in the stack is from non-framework code, though. That would make sense. Should we update this bug to be specifically about doing that?

I think minimizing the times the user sees the message would be great.

> The actual exception text comes from the compiler. I agree that it could be clearer. To have that changed we should probably file a bug on the Dart SDK.

I'll file one and reference this issue.

**Comment by Hixie** [comment] 2018-05-01 03:07
Ok, I've updated this bug accordingly.

[ ] Filter stacks in Flutter so that any sequence of stack lines that are from package:flutter or dart:* and are between two other lines that are also from package:flutter or dart:* are either omitted or replaced by an ellipsis, unless some global debugDumpFullStacksInExceptions flag is set.
[ ] Hide the message saying this could be a framework bug if the first stack frame is not in the framework.

**Comment by Hixie** [comment] 2018-06-05 23:20
Moving out of bucket5 since there is no committed assignee; please don't hesitate to move these to a specific milestone if there is someone who is committed to working on it by that milestone.

**Comment by Hixie** [comment] 2018-06-12 19:02
I've split out the specifics into https://github.com/flutter/flutter/issues/18412 and https://github.com/flutter/flutter/issues/4174.

**Closed by Hixie** 2018-06-12 19:02 UTC
Labels: framework, severe: crash
