### ISSUE TITLE
WebView Flutter Plugin Expiration method

### ISSUE THREAD

**Issue by jiechic** [flutter/flutter#42826] opened 2019-10-16 08:16 UTC
Flutter version 1.9.1 hotfix-4

> Task :webview_flutter:compileReleaseJavaWithJavac FAILED
/usr/local/share/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java:100: 错误: 方法不会覆盖或实现超类型的方法
  @Override
  ^
/usr/local/share/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.15/android/src/main/java/io/flutter/plugins/webviewflutter/FlutterWebView.java:105: 错误: 方法不会覆盖或实现超类型的方法
  @Override
  ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
2 个错误

in webview flutter  code on file FlutterWebView
this two method was Expired in Flutter version 1.9.1 hotfix-4

> @Override
  public void onFlutterViewAttached(@NonNull View flutterView) {
    webView.setContainerView(flutterView);
  }

 > @Override
  public void onFlutterViewDetached() {
    webView.setContainerView(null);
  }

**Comment by ovidiu-anghelina** [comment] 2019-10-16 10:49
It seems to me like version 0.3.15 of the webview_flutter plugin is a breaking change, because it's not compatible with flutter 1.9.1+hotfix.4 (latest stable version at this time), because FlutterWebView implements 'onFlutterViewAttached' and 'onFlutterViewDetached' from PlatformView, even though PlatformView doesn't have those methods on the latest stable version of Flutter.

It's a shame to see breaking changes on minor versions of plugins published by the Flutter team, which is the exact opposite of [versioning requirements](https://dart.dev/tools/pub/versioning) and will give lots of developers a big headache for using the recommended semantic versioning using the caret (^) symbol. Please be more careful about those kinds of things, it's one of the few things within the Flutter ecosystem that doesn't always 'just work'.

**Comment by BondarenkoStas** [comment] 2019-10-16 11:00
Thank you @jiahaog for the report and @ovidiu-anghelina for clarification! Right, those were added since 1.10.7, which is not in stable yet.

**Comment by felipeszu** [comment] 2019-10-16 19:33
Same issue here! How can we fix it!

**Comment by jmagman** [comment] 2019-10-16 22:56
You filed first, but looks like a duplicate of https://github.com/flutter/flutter/issues/42860 which already has a PR pending.
@mklim

**Closed by jmagman** 2019-10-16 22:56 UTC
Labels: documentation, p: webview, plugin
