### ISSUE TITLE
can't build web app

### ISSUE THREAD

**Issue by RomanGajdosSk** [flutter/flutter#72656] opened 2020-12-19 17:49 UTC
I followed the instructions in codelab Multi-platform Firestore Flutter, but when I want to deploy my app I got this :

192:mytrainings roman$ flutter clean & flutter build web
[1] 50783
Waiting for another flutter command to release the startup lock...
Running "flutter pub get" in mytrainings...                        639ms
Cleaning Xcode workspace...                                            ⣻Compiling lib/main.dart for the Web...                              8,8s
Deleting build...                                                    1ms
Deleting .dart_tool...                                               1ms
Deleting Generated.xcconfig...                                       0ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            0ms
Deleting .flutter-plugins...                                         0ms
Target dart2js failed: Exception: Error: FileSystemException: Cannot open file, path = '/Users/rxxx/mytrainings/.dart_tool/flutter_build/1928549685a69525fb34edcd9c95fed0/app.dill'
(OS Error: No such file or directory, errno = 2)
what's wrong ?

**Comment by iapicca** [comment] 2020-12-19 20:15
possible duplicate of https://github.com/flutter/flutter/issues/68958

**Comment by PixelToast** [comment] 2020-12-20 06:13
The tool probably doesn't like when `flutter clean` and `flutter build` are run concurrently, perhaps you meant to use `&&` to chain the two commands instead of `&`.

Does the build succeed when the commands are run separately?

If not please provide the output of `flutter doctor`

**Comment by iapicca** [comment] 2020-12-20 09:30
@RomanGajdosSk 
can you provider your `flutter doctor -v`
possible duplicate of https://github.com/flutter/flutter/issues/68958

**Comment by RomanGajdosSk** [comment] 2020-12-20 11:32
> The tool probably doesn't like when `flutter clean` and `flutter build` are run concurrently, perhaps you meant to use `&&` to chain the two commands instead of `&`.
> 
> Does the build succeed when the commands are run separately?
> 
> If not please provide the output of `flutter doctor`

if I run it separately then it's fine. thanks. But actualy it's executed together from this command
: firebase deploy --only hosting
which is described on the codelab page.

**Comment by PixelToast** [comment] 2020-12-21 03:34
related: https://github.com/FirebaseExtended/codelab-friendlyeats-flutter/issues/9

**Comment by domesticmouse** [comment] 2021-03-18 04:28
@RomanGajdosSk does this still occur if you run `firebase init hosting` before running `firebase deploy --only hosting`?

I have a fix for FirebaseExtended/codelab-friendlyeats-flutter#9 in flight, but I don't know what the required fix for this issue is.

**Comment by pedromassangocode** [comment] 2021-04-14 10:43
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Closed by pedromassangocode** 2021-04-14 10:43 UTC
Labels: d: codelabs, documentation, passed first triage, platform-web, tool, waiting for customer response
