### ISSUE TITLE
[flutter_tool]Get Flutter version failed in git hook of git submodule 

### ISSUE THREAD

**Issue by hyiso** [flutter/flutter#124681] opened 2023-04-12 15:05 UTC
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/flutter/flutter/issues)
- [X] I have read the [guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)

### Steps to reproduce

1. Add a git hook(like `pre-commit`) to a git submodule with content `flutter --version`
2. Make a commit under the submodule, this will execute the hook added above
3. See its output

### Expected results

Expect to get the right Flutter version

### Actual results

Cannot get Flutter version, resolves to unknown.

### Code sample

I've created a code sample https://github.com/hyiso/flutter_git_hook_test

1. Clone this repo
2. Run ./setup.sh
3. cd packages/flutter_git_hook_submodule
4. Make a commit

The output of `flutter --version` that is executed by git hook pre-commit:
```console
Flutter • channel unknown • unknown source
Framework • revision 956e13eca8 (9 minutes ago) • 2023-04-12 22:44:50 +0800
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1
```

The version of Flutter SDK failed.

Expected output is:
```console
Flutter 3.7.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4b12645012 (9 days ago) • 2023-04-03 17:46:48 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1
```

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.2 22D49 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.77.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by hyiso** [comment] 2023-04-12 15:12
The problem might be related to getting last git commit has of flutter repo. When running in git hook of git submodule, the git commit hash belongs to the working git submodule.

See https://github.com/hyiso/husky/issues/4#issuecomment-1503661378

**Comment by darshankawar** [comment] 2023-04-13 06:15
Thanks for the report @hyiso 
While trying to run `.sh` command, I am getting `permission denied`.
Also, does this behavior only occur on stable or on master as well ?

**Comment by hyiso** [comment] 2023-04-13 07:37
@darshankawar Thanks for ths response.
I've not tried master, the latest stable 3.7.10 has this problem.

`.sh` might need to chmod to executable

**Comment by darshankawar** [comment] 2023-04-13 12:47
Thanks for the update. Upon using chmod, I was able to run the script and following steps to replicate, see the same behavior as reported. This I verified only on stable.

<details>
<summary> stable flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.7.10, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.7.10 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (6 days ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available


```

</details>

**Comment by christopherfujino** [comment] 2023-04-18 20:19
@hyiso it seems to me like this is not a bug with the Flutter SDK, but with your particular git setup. Can you please verify what Flutter SDK that your script is resolving to, and that the version is indeed wrong?

**Comment by hyiso** [comment] 2023-04-19 02:36
@christopherfujino  As reported in the issue details, the using Flutter SDK is
```bash
Flutter 3.7.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4b12645012 (9 days ago) • 2023-04-03 17:46:48 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1
```
And reslolved version in git hook is:
```bash
Flutter • channel unknown • unknown source
Framework • revision 956e13eca8 (9 minutes ago) • 2023-04-12 22:44:50 +0800
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1
```

I don't think the git setup is particular. Just add simple shell content `flutter --version` to `.git/modules/thesubmodulepath/hooks/pre-commit` and make a commit in the submodule.

**Comment by hyiso** [comment] 2023-04-19 02:44
@christopherfujino 
Also directly calling the `pre-commit` hook script, the Flutter SDK version is resolved as expected.

I have also tested by replacing `flutter --version` to `flutter pub get -v` in two ways: directly calling `pre-commit` and making a commit

The problem begins at resolving the last commit hash of Flutter SDK repo.:

- When calling `pre-commit` directly, the last commit hash resolved to `4b12645012342076800eb701bcdfe18f87da21cf` which is exactly the last commit hash of Flutter SDK 3.7.10. 

- When calling by making a commit, the commit hash resolved to the  last one of the git submodule repo.

As detailed in https://github.com/hyiso/husky/issues/4#issuecomment-1503661378

**Comment by christopherfujino** [comment] 2023-04-19 18:21
@hyiso it looks like your sample repo (https://github.com/hyiso/flutter_git_hook_test/tree/main/packages) is using a commit of flutter_git_submodule that doesn't exist yet or anymore on github: https://github.com/hyiso/flutter_git_hook_submodule/commits/main

**Comment by christopherfujino** [comment] 2023-04-19 18:26
When I setup another git submodule, the hook script your setup.sh generated errors, because echo doesn't parse `\n` escapes (at least  not on GNU bash 5.2.1).

**Comment by christopherfujino** [comment] 2023-04-19 18:32
In any case, I suspect that the issue is that the way git invokes hooks is not playing well with our bash entrypoint https://github.com/flutter/flutter/blob/master/bin/flutter if you want to pull on this further.

**Comment by christopherfujino** [comment] 2023-05-09 20:11
I am going to close this bug as I was not able to reproduce it and there has been no response for 3 weeks. Feel free to file a new issue with working reproduction steps.

**Comment by hyiso** [comment] 2023-05-10 02:42
The reproducible steps are described above, as @darshankawar also reproduced. But close as you can.

**Closed** 2023-05-10 13:44 UTC
Labels: tool, has reproducible steps, found in release: 3.7

**Comment by christopherfujino** [comment] 2023-05-10 16:54
> The reproducible steps are described above, as @darshankawar also reproduced. But close as you can.

I tried to repro this and couldn't, see:

https://github.com/flutter/flutter/issues/124681#issuecomment-1515175556

and

https://github.com/flutter/flutter/issues/124681#issuecomment-1515181382

**Comment by hyiso** [comment] 2023-05-11 01:21
This issue is closed, the reproducible code repos are deleted. If someone else encounter this problem, another issue will be opened.
