### ISSUE TITLE
tiles_scroll_perf_ios__timeline_summary,  error: ext.flutter.driver: (-32000) Service 

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#74332] opened 2021-01-20 17:22 UTC
tiles_scroll_perf_ios__timeline_summary is failing consistently on a few test beds only while passing consistently on others. Host configurations are identical but there may be some differences in the ios phone configurations.

Link to result:

https://logs.chromium.org/logs/flutter/led/godofredoc_google.com/5c47e760b8dab2c085b193348e5f33935b25cca8ee7cb753f278191cb19e5d63/+/steps/run_tiles_scroll_perf_ios__timeline_summary/0/stdout

```
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [+714701 ms] 12:00 [32m+0[0m[31m -1[0m: scrolling performance test (setUpAll) [1m[31m[E][0m[0m
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [   +1 ms]   TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [  +21 ms]   package:test_api/src/backend/invoker.dart 318:28  Invoker._handleError.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1346:47                      _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                      _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 316:10  Invoker._handleError
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 272:9   Invoker.heartbeat.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                      _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                      _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 271:38  Invoker.heartbeat.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 395:19         _Timer._runTimers
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 426:5          _Timer._handleMessage
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePortImpl._handleMessage
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [   +2 ms] 12:00 [32m+0[0m[31m -1[0m: scrolling performance test (tearDownAll)[0m
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [  +10 ms] 12:00 [32m+0[0m[31m -1[0m: scrolling performance test (setUpAll) [1m[31m[E][0m[0m
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [   +7 ms]   DriverError: Failed to fulfill WaitForCondition due to remote error
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   Original error: ext.flutter.driver: (-32000) Service connection disposed
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   Original stack trace:
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/future_impl.dart 25:44                               _Completer.completeError
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:vm_service/src/vm_service.dart 1972:16                  VmService.dispose.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:collection-patch/compact_hash.dart 397:8                   _LinkedHashMapMixin.forEach
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:vm_service/src/vm_service.dart 1970:17                  VmService.dispose
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:flutter_driver/src/driver/vmservice_driver.dart 528:20  VMServiceFlutterDriver.close
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   test_driver/scroll_perf_test.dart 22:16                         main.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   test_driver/scroll_perf_test.dart 20:17                         main.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/future.dart 218:31                                   new Future.sync
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/util/test.dart 21:12                       errorsDontStopTest.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 231:15                Invoker.waitForOutstandingCallbacks.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 228:14                Invoker.waitForOutstandingCallbacks.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1788:10                                    _runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1710:10                                    runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 228:5                 Invoker.waitForOutstandingCallbacks
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/util/test.dart 20:20                       errorsDontStopTest
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/declarer.dart 358:19               Declarer._tearDownAll.<fn>.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/declarer.dart 356:44               Declarer._tearDownAll.<fn>.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1788:10                                    _runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1710:10                                    runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 248:12                Invoker.unclosable
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/declarer.dart 356:33               Declarer._tearDownAll.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1788:10                                    _runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1710:10                                    runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/declarer.dart 355:14               Declarer._tearDownAll.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 231:15                Invoker.waitForOutstandingCallbacks.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 228:14                Invoker.waitForOutstandingCallbacks.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1788:10                                    _runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1710:10                                    runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 228:5                 Invoker.waitForOutstandingCallbacks
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 383:17                Invoker._onRun.<fn>.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1286:19                                    _CustomZone.registerUnaryCallback
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async-patch/async_patch.dart 40:23                         _asyncThenWrapperHelper
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart                       Invoker._onRun.<fn>.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1788:10                                    _runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1710:10                                    runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 370:9                 Invoker._onRun.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 415:15                Invoker._guardIfGuarded
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 369:7                 Invoker._onRun.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:stack_trace/src/chain.dart 94:24                        Chain.capture.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1788:10                                    _runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1710:10                                    runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:stack_trace/src/chain.dart 92:12                        Chain.capture
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 368:11                Invoker._onRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/live_test_controller.dart 153:11   LiveTestController.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/future.dart 198:37                                   new Future.microtask.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1346:47                                    _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1162:7                                     _CustomZone.runGuarded
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1202:23                                    _CustomZone.bindCallbackGuarded.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                    _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                    _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1162:7                                     _CustomZone.runGuarded
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1202:23                                    _CustomZone.bindCallbackGuarded.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/schedule_microtask.dart 40:21                        _microtaskLoop
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/schedule_microtask.dart 49:5                         _startMicrotaskLoop
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/isolate_patch.dart 120:13                    _runPendingImmediateCallback
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 402:11                       _Timer._runTimers
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 426:5                        _Timer._handleMessage
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/isolate_patch.dart 184:12                    _RawReceivePortImpl._handleMessage
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:flutter_driver/src/driver/vmservice_driver.dart 322:7  VMServiceFlutterDriver.sendCommand
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1294:19                                   _CustomZone.registerBinaryCallback
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async-patch/async_patch.dart 51:8                         _asyncErrorWrapperHelper
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                   _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                   _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1788:10                                   _runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1710:10                                   runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 228:5                Invoker.waitForOutstandingCallbacks
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 383:17               Invoker._onRun.<fn>.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   ===== asynchronous gap ===========================
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1286:19                                   _CustomZone.registerUnaryCallback
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async-patch/async_patch.dart 40:23                        _asyncThenWrapperHelper
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart                      Invoker._onRun.<fn>.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                   _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                   _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1788:10                                   _runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1710:10                                   runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 370:9                Invoker._onRun.<fn>.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 415:15               Invoker._guardIfGuarded
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 369:7                Invoker._onRun.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:stack_trace/src/chain.dart 94:24                       Chain.capture.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                   _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                   _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1788:10                                   _runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1710:10                                   runZoned
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:stack_trace/src/chain.dart 92:12                       Chain.capture
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/invoker.dart 368:11               Invoker._onRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   package:test_api/src/backend/live_test_controller.dart 153:11  LiveTestController.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/future.dart 198:37                                  new Future.microtask.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1346:47                                   _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                   _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1162:7                                    _CustomZone.runGuarded
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1202:23                                   _CustomZone.bindCallbackGuarded.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1354:13                                   _rootRun
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1258:19                                   _CustomZone.run
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1162:7                                    _CustomZone.runGuarded
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/zone.dart 1202:23                                   _CustomZone.bindCallbackGuarded.<fn>
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/schedule_microtask.dart 40:21                       _microtaskLoop
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:async/schedule_microtask.dart 49:5                        _startMicrotaskLoop
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/isolate_patch.dart 120:13                   _runPendingImmediateCallback
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 402:11                      _Timer._runTimers
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/timer_impl.dart 426:5                       _Timer._handleMessage
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [        ]   dart:isolate-patch/isolate_patch.dart 184:12                   _RawReceivePortImpl._handleMessage
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stdout: [   +8 ms] 12:00 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stderr: [   +1 ms] Unhandled exception:
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stderr: [        ] Dummy exception to set exit code.
[tiles_scroll_perf_ios__timeline_summary] [STDOUT] stderr: [  +37 ms] Failed to stop app
```

**Comment by godofredoc** [comment] 2021-01-20 17:22
\cc @jmagman @xster have you seen this issue before?

**Comment by jmagman** [comment] 2021-01-20 18:20
Maybe a duplicate of https://github.com/flutter/flutter/issues/66153.

I think we can take screenshots from `FlutterDriver`, if we save it somewhere in the test on a `TimeoutException` can it be added to the test step artifacts?

In the meantime, is there a way to get a screenshot of what it's doing when it's stuck?

**Comment by jmagman** [comment] 2021-01-20 18:46
> I think we can take screenshots from `FlutterDriver`, if we save it somewhere in the test on a `TimeoutException` can it be added to the test step artifacts?

Meaning, we can start dumping useful screenshots for all kinds of tests if we can put them in some known directory to be later viewed in the build step.

**Comment by godofredoc** [comment] 2021-01-20 19:03
Sounds good, there is a separate request to support random logs in tasks. The implementation will be the following:

Recipe will run the test in a deferred context which will create an env variable called FLUTTER_LOGS_DIR, the test runner can place any logs|artifacts to help debugging there and they will be automatically uploaded to GCS.

If you can help us with the runner changes to collect the screenshots I can modify the recipe and modules to create the env variable and process the files at the end of the test execution today.

**Comment by jmagman** [comment] 2021-01-20 19:37
> If you can help us with the runner changes to collect the screenshots I can modify the recipe and modules to create the env variable and process the files at the end of the test execution today.

Tracking separately at https://github.com/flutter/flutter/issues/74344.

**Comment by godofredoc** [comment] 2021-01-26 02:59
Found the issue that is most likely affecting all the tests in xcode 12.3 with ios 14.3

![Screen Shot 2021-01-25 at 6 55 37 PM](https://user-images.githubusercontent.com/54371434/105794159-4af3c480-5f3f-11eb-939e-16a4b8253e96.png)

**Comment by godofredoc** [comment] 2021-01-26 03:00
The application gets stuck on that dialog until the test times out.

**Comment by jmagman** [comment] 2021-02-09 01:07
@godofredoc I think this should be resolved as of https://github.com/flutter/flutter/pull/75163.  Let me know if it's still happening.

**Closed by jmagman** 2021-02-09 01:07 UTC
Labels: passed first triage, passed secondary triage, team, team: infra
