### ISSUE TITLE
Android/Windows: `sdkmanager --licenses` doesn't persist when run as non-administrator

### ISSUE THREAD

**Issue by natem34** [flutter/flutter#16065] opened 2018-03-29 15:50 UTC
When I run flutter doctor, "Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses" is the only thing it's cranky about. When I run the command, and hit "y" to accept each license and rerun flutter doctor, it still complains about the android licenses.

flutter doctor -v
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
    • Flutter version 0.2.3
    • Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK
    • Android NDK
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME
    • Java binary
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.1)
    • Android Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.21.1)
    • VS Code
    • Dart Code extension version 2.11.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.

I posted the same thing on the Google groups for flutter, and it was suggested this is a bug and that I should post it here.

**Comment by tvolkert** [comment] 2018-03-29 16:10
Can you include the output of `flutter --verbose doctor -v`?

**Comment by natem34** [comment] 2018-03-29 16:17
That is the output.  The only thing stripped out are the dir locations.

**Comment by tvolkert** [comment] 2018-03-29 16:18
(this is the output of `flutter doctor -v`, which is not as verbose)

**Comment by tvolkert** [comment] 2018-03-29 16:19
@cbracken suggests that this may be getting caused because you have two Android Studio installations -- Flutter detects one, and you accept licenses on another.  Could that be the case?

**Comment by natem34** [comment] 2018-03-29 16:28
C:\Users\Nate>flutter --verbose doctor -v
[  +15 ms] [D:\Users\Nate\Go\src\github.com\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +59 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] [D:\Users\Nate\Go\src\github.com\flutter\] git rev-parse --abbrev-ref HEAD
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[        ] [D:\Users\Nate\Go\src\github.com\flutter\] git ls-remote --get-url origin
[  +30 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[        ] [D:\Users\Nate\Go\src\github.com\flutter\] git log -n 1 --pretty=format:%H
[  +32 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 5a58b36e36b8d7aace89d3950e6deb307956a6a0
[        ] [D:\Users\Nate\Go\src\github.com\flutter\] git log -n 1 --pretty=format:%ar
[  +31 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 2 weeks ago
[        ] [D:\Users\Nate\Go\src\github.com\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +32 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v0.2.3-0-g5a58b36e3
[ +404 ms] java -version
[  +82 ms] [√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
[   +1 ms]     • Flutter version 0.2.3 at D:\Users\Nate\Go\src\github.com\flutter
[        ]     • Framework revision 5a58b36e36 (2 weeks ago), 2018-03-13 13:20:13 -0700
[        ]     • Engine revision e61bb9ac3a
[        ]     • Dart version 2.0.0-dev.35.flutter-290c576264
-[   +1 ms] C:\AndroidStudio\sdk\tools\bin\sdkmanager --licenses
[   +2 ms] C:\AndroidStudio\sdk\platform-tools\adb devices -l
[  +26 ms] Exit code 0 from: C:\AndroidStudio\sdk\platform-tools\adb devices -l
[   +1 ms] List of devices attached
[   +7 ms] C:\AndroidStudio\sdk\platform-tools\adb devices -l
[  +60 ms] List of devices attached
[ +878 ms] [!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[        ]     • Android SDK at C:\AndroidStudio\sdk
[        ]     • Android NDK at C:\AndroidStudio\sdk\ndk-bundle
[        ]     • Platform android-27, build-tools 27.0.3
[        ]     • ANDROID_HOME = C:\AndroidStudio\sdk
[        ]     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
[        ]     X Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[        ] [√] Android Studio (version 3.1)
[        ]     • Android Studio at C:\Program Files\Android\Android Studio
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
[        ] [√] VS Code, 64-bit edition (version 1.21.1)
[        ]     • VS Code at C:\Program Files\Microsoft VS Code
[        ]     • Dart Code extension version 2.11.1
[        ] [!] Connected devices
[        ]     ! No devices available
[        ] ! Doctor found issues in 2 categories.
[  +13 ms] "flutter doctor" took 1,407ms.
[ +255 ms] ensureAnalyticsSent: 251ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

**Comment by tvolkert** [comment] 2018-03-29 16:37
Thanks!  One more 😄 -- can you run the following and attach the generated bug report ZIP file here?

```bash
flutter doctor --bug-report --android-licenses
```

**Comment by natem34** [comment] 2018-03-29 16:41
Sure, thanks for your help.
[bugreport_01.zip](https://github.com/flutter/flutter/files/1861049/bugreport_01.zip)

**Comment by Mahi-K** [comment] 2018-03-30 04:22
hi, @natem34 , yes flutter complains about this issue if you have first installed it or trying run your project for the first time on any android device, i think you could try and create an android project in AndroidStudio and accept all the licenses in AndroidStudio and then run the flutter doctor -v and see if this helps. if the framework still complains about not accepting licenses, you can run `flutter doctor --android-licenses` and click yes to accept. Thank you ,  this happened to me and i did the same and its fine now.

**Comment by Herohtar** [comment] 2018-03-30 05:40
I think this is actually related/duplicate of https://github.com/flutter/flutter/issues/16025.

**Comment by natem34** [comment] 2018-03-30 18:59
@Mahi-K, that a fact huh?  Ok, I will try to create a new project from Android studio and see if I can accept the licenses from there.  Seems weird that the instructions tell you to run flutter doctor during the setup, but doesn't say that it's cool to continue given certain errors.  Oh well... I guess that's why it's in beta right? :)

@Herohtar I'll check that out.  I did do a search for the issue, my apologies if I missed duplicates.

**Comment by tvolkert** [comment] 2018-03-30 19:15
@natem34 strange - everything in the bug report looks like it behaved normally when you accepted the licenses (assuming you hit "y" when prompted).  But you're saying that if you run it again, it prompts you again like it didn't record the acceptance the first time?

**Comment by natem34** [comment] 2018-04-01 18:25
@tvolkert I did hit "y" when prompted. And yes, you are correct.  If I run it again (flutter doctor) it prompts me like I never accepted the licenses.

**Comment by tvolkert** [comment] 2018-04-02 19:44
@natem34 I wonder if we're not piping the `stdin` correctly under certain circumstances or something...

Can you reproduce this by manually running the sdkmanager?

```shell
C:\AndroidStudio\sdk\tools\bin\sdkmanager --licenses
```

If you run that yourself and accept all the licenses... then run it again... does it still prompt you to accept the licenses again?  (and if not, does flutter stop complaining?)

**Comment by natem34** [comment] 2018-04-02 20:18
Okay, that brings up an interesting point... and I may have messed up the troubleshooting of this.  When I browsed to the location for the sdkmanager, I then went to file (from windows explorer) and opened powershell as administrator (just running on autopilot).  I went through the steps and accepted all the licenses, then (from the same powershell window) ran flutter doctor.  All is well now.  What I don't know is this.  Did it work because I followed your step and went through the sdkmanager, or did it work because of the elevated powershell.  I can't recall if I was using an administrator cmd prompt before... but I'd wager a guess I wasn't.

**Comment by tvolkert** [comment] 2018-04-03 16:18
Chances are that you weren't using an administrator cmd prompt before, which meant that the process that the flutter tool spawned to run `sdkmanager --licenses` also wasn't running as administrator.

What's weird, though, is that the bug report you attached shows that the process acknowledged that you accepted all licenses and returned with a successful exit code, which can also be seen here:

https://github.com/flutter/flutter/blob/6c8c824e281be567d7c5e465199c9985fa665064/packages/flutter_tools/lib/src/android/android_workflow.dart#L235

So it would seem that when run as non-administrator, the `sdkmanager` command allows you to accept the licenses, but it doesn't record that acceptance, causing it to immediately think you still haven't accepted them?

In any case, I'm going to close this since you're no longer seeing it, so our ability to debug is diminished.

**Closed by tvolkert** 2018-04-03 16:18 UTC
Labels: dev: first hour, dev: tool, ▣ platform-android

**Comment by aitseps** [comment] 2018-05-24 02:00
Hello friends, I would like to know if you could solve this problem, I am currently installing flutter, but when running flutter doctor generates the following:
`
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.4.4, on Microsoft Windows [VersiÃ³n 10.0.17134.48], locale es-CL)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
`


I have followed your instructions in this discussion and I am detained in the following:
`D:\Android Studio\Android\Sdk\tools\bin>sdkmanager --update
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 5 more

D:\Android Studio\Android\Sdk\tools\bin>sdkmanager --licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 5 more

I would appreciate your comments.
@tvolkert

`

**Comment by shivamdwivedi1511** [comment] 2018-05-25 06:32
look every thing is fine you just need to set the JAVA_HOME variable with java jdk path

**Comment by sahil904** [comment] 2018-09-27 10:49
flutter doctor --android-licenses
this is the best soloution for this issue

**Comment by stickyboiproject** [comment] 2018-11-05 09:39
![untitled](https://user-images.githubusercontent.com/43104324/47990150-c8924680-e121-11e8-8147-ab760aa9693e.png)

**Comment by harshitc0209** [comment] 2018-11-29 17:07
> Thanks! One more  -- can you run the following and attach the generated bug report ZIP file here?
> 
> ```shell
> flutter doctor --bug-report --android-licenses
> ```

I search it every where but I found invalid replies. This is what worked well.

**Comment by MaterialTime** [comment] 2019-05-16 14:30
@stickyboiproject Your JAVA_HOME is not set to the location of your Java installation. It explicitly told you that. How is it not obvious. It's set to the location of the Android SDK bin directory it seems

**Comment by mavmaso** [comment] 2019-12-31 14:53
`PS C:\WINDOWS\system32> C:\Users\mavmaso\AppData\Local\Android\sdk\tools\bin\sdkmanager --update
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more`

**Comment by iagofrota** [comment] 2020-02-29 14:43
My settings:
Windows 10 PRO
java version "1.8.0_241"
Java (TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot (TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

When I run the command `flutter doctor`, I get this message:
```Doctor summary (to see all details, run flutter doctor -v):                                                                                
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [versÃ£o 10.0.18363.657], locale pt-BR)                               
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)                                                           
    X Android license status unknown.                                                                                                      
      Try re-installing or updating your Android SDK Manager.                                                                              
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.     
[!] Android Studio (version 3.6)                                                                                                           
    X Flutter plugin not installed; this adds Flutter specific functionality.                                                              
    X Dart plugin not installed; this adds Dart specific functionality.                                                                    
[√] VS Code, 64-bit edition (version 1.42.1)                                                                                               
[!] Connected device                                                                                                                       
    ! No devices available
```

When trying to run the command `.\sdkmanager.bat` with whatever options, I get this message:

```
Warning: Could not create settings
java.lang.IllegalArgumentException
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.<init>(SdkManagerCliSettings.java:428)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:152)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.createSettings(SdkManagerCliSettings.java:134)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:57)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
```

I don't understand why this is happening

**Comment by hanseld28** [comment] 2020-07-27 13:44
@iagofrota 
Tente rodar o comando **.\sdkmanager.bat --licenses** com a opção **--sdk_root**, especificando o caminho completo até a pasta **bin** da ferramenta. 

Exemplo:
`.\sdkmanager.bat --licenses --sdk_root=C:\android\tools\bin
`

**Comment by RewaNx7** [comment] 2021-03-20 00:09
> ```
> flutter doctor --android-licenses
> ```
> 
> this is the best solution for this issue

thanks a lot it helped me!
