### ISSUE TITLE
[http] Requests fail with SocketException when app goes in to background

### ISSUE THREAD

**Issue by jimmyff** [flutter/flutter#121143] opened 2023-02-21 15:21 UTC
_(Looks like https://github.com/flutter/flutter/issues/68188)_

When my app goes in to the background it gets SocketExceptions when it tries to make http requests (examples captured by Crashlytics included below). I assume this is something to do with Android's energy saver, is this expected behavior? Getting failed host lookup exceptions isn't ideal as my app would like to take a different course of action if a hostname can't be reached compared to the app is being restricted by the host os.

### SocketException: Failed host lookup

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: SocketException: Failed host lookup: 'io.foo.bar' (OS Error: No address associated with hostname, errno = 7). Error thrown null.
       at _HttpClient.openUrl(dart:_http)
       at IOClient.send(io_client.dart:35)
       at BaseClient._sendUnstreamed(base_client.dart:93)
       at BaseClient.post(base_client.dart:32)
       at post.<fn>(http.dart:69)
       at ._withClient(http.dart:164)
       at .post(http.dart:68)
       at .cloudFunctionHttps(cloud_functions.dart:26)
       at DeviceMiddleware._possiblySendPing(device_middleware.dart:216)
       at DeviceMiddleware.call(device_middleware.dart:32)
```

### SocketException: Connection timed out

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = io.foo.bar, port = 35576. Error thrown null.
       at _HttpClient.openUrl(dart:_http)
       at IOClient.send(io_client.dart:35)
       at BaseClient._sendUnstreamed(base_client.dart:93)
       at BaseClient.post(base_client.dart:32)
       at post.<fn>(http.dart:69)
       at ._withClient(http.dart:164)
       at .post(http.dart:68)
       at .cloudFunctionHttps(cloud_functions.dart:26)
       at QueueMiddleware._publishSwipes(queue_middleware.dart:364)
       at QueueMiddleware.call(queue_middleware.dart:258)
       at Store._createDispatchers.<fn>(store.dart:255)
       at RemoteConfigMiddleware.call(remote_config_middleware.dart:56)
       at Store._createDispatchers.<fn>(store.dart:255)
       at AccountMiddleware.call(account_middleware.dart:405)
       at Store._createDispatchers.<fn>(store.dart:255)
       at AuthMiddleware.call(auth_middleware.dart:148)
       at Store._createDispatchers.<fn>(store.dart:255)
       at DeviceMiddleware.call(device_middleware.dart:135)
       at Store._createDispatchers.<fn>(store.dart:255)
       at NavigationMiddleware.call(navigation_middleware.dart:64)
       at Store._createDispatchers.<fn>(store.dart:255)
       at LoggingMiddleware.call(redux_logging.dart:120)
       at Store._createDispatchers.<fn>(store.dart:255)
       at .thunkMiddleware(redux_thunk.dart:49)
       at Store._createDispatchers.<fn>(store.dart:255)
       at Store.dispatch(store.dart:267)
       at _HomeScreenState.build.<fn>.<fn>(home_screen.dart:128)
       at _HomeScreenState.didChangeAppLifecycleState(home_screen.dart:351)
       at WidgetsBinding.handleAppLifecycleStateChanged(binding.dart:692)
       at ServicesBinding._handleLifecycleMessage(binding.dart:256)
       at BasicMessageChannel.setMessageHandler.<fn>(platform_channel.dart:197)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(binding.dart:387)
```

### SocketException: Software caused connection abort 

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: SocketException: Software caused connection abort (OS Error: Software caused connection abort, errno = 103), address = io.foo.bar, port = 47628. Error thrown null.
       at _HttpClient.openUrl(dart:_http)
       at IOClient.send(io_client.dart:35)
       at BaseClient._sendUnstreamed(base_client.dart:93)
       at BaseClient.post(base_client.dart:32)
       at post.<fn>(http.dart:69)
       at ._withClient(http.dart:164)
       at .post(http.dart:68)
       at .cloudFunctionHttps(cloud_functions.dart:26)
       at searchMigratedAccountsThunk.<fn>(user.dart:180)
       at _MigrationScreenState.build.<fn>.<fn>.<fn>(migration_screen.dart:263)
       at _NetworkTaskUiWidgetState._startTask(network_task_ui_widget.dart:124)
```

<details>
  <summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6.2 21G320 darwin-arm, locale en-GB)
    • Flutter version 3.3.8 on channel stable at /Users/jimmyff/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (3 months ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/jimmyff/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.75.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.58.0

[✓] Connected device (3 available)
    • Pixel 5 (mobile) • 09021FDD40027X • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 12.6.2 21G320
      darwin-arm
    • Chrome (web)     • chrome         • web-javascript • Google Chrome
      109.0.5414.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-02-22 08:36
@jimmyff Thanks for the report.
I think this issue is best to be reported here: https://github.com/dart-lang/http/issues since I don't see any flutter related stacktraces in the log you shared.
Closing from here. If you disagree, or get directed here again, please write in comments and I'll reopen it.

**Closed by darshankawar** 2023-02-22 08:36 UTC
Labels: in triage

**Comment by natebosch** [comment] 2023-02-23 02:34
> I think this issue is best to be reported here: https://github.com/dart-lang/http/issues since I don't see any flutter related stacktraces in the log you shared.

This issue is unrelated to `package:http`. Please only forward issues to `dart-lang/http` when they are specifically bugs in `package:http`. When the failure is related to the SDK use `dart-lang/sdk` repo issue tracker.

In this case, the issue is tracked on the flutter issue tracker. https://github.com/flutter/flutter/issues/115921
