### ISSUE TITLE
Checkbox blink when removed its border

### ISSUE THREAD

**Issue by tonywong586** [flutter/flutter#108802] opened 2022-08-02 11:18 UTC
## Steps to Reproduce

1.  Copy the code to a new file
2.  Execute `flutter run` on the code sample 
3. Click on the checkbox 

**Expected results:** 
The checkbox will not blink or flash(no border) when clicked on it

**Actual results:** 

https://user-images.githubusercontent.com/72515867/182361258-d47ac72e-fc6d-48b6-bce6-37e141389537.mov

The checkbox blink(border appear) when clicked on it

<details>
<summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

class UserLevelCheckBox {
  String title;
  bool value;
  String subtitle;

  UserLevelCheckBox({required this.title, this.value = false, required this.subtitle});
}

class UserLevelModal2 extends StatefulWidget {
  const UserLevelModal2({Key? key}) : super(key: key);

  @override
  State<UserLevelModal2> createState() => _UserLevelModalState();
}

class _UserLevelModalState extends State<UserLevelModal2> {
  final UserLevel = [UserLevelCheckBox(title: "Manager", subtitle: "Can operate and edit POS, make changes to staff passwords, icons and user levels"), UserLevelCheckBox(title: "Staff", subtitle: "Can operate POS, make changes to own password and icon")];
  bool isMobile(BuildContext context) => MediaQuery.of(context).size.width < 700;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.transparent,
        body: Flex(
          direction: Axis.vertical,
          children: [
            ...UserLevel.map(buildSingleCheckbox).toList(),
          ],
        ));
  }

  Widget buildSingleCheckbox(UserLevelCheckBox UserLevel) => CheckBoxCreate(
      UserLevel: UserLevel,
      onClicked: () {
        setState(() {
          final newValue = !UserLevel.value;
          UserLevel.value = newValue;
        });
      });

  Widget CheckBoxCreate({
    required UserLevelCheckBox UserLevel,
    required VoidCallback onClicked,
  }) =>
      Padding(
        padding: const EdgeInsets.all(12.0),
        child: ListTile(
          onTap: onClicked,
          subtitle: Text(UserLevel.subtitle),
          title: Text(UserLevel.title, style: GoogleFonts.poppins(fontSize: 18, fontWeight: FontWeight.w400)),
          trailing: Checkbox(
            activeColor: Colors.transparent,
            side: BorderSide(color: Colors.transparent),
            value: UserLevel.value,
            onChanged: (value) => onClicked(),
            shape: CircleBorder(),
            splashRadius: 0,
          ),
        ),
      );
}

```

</details>

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment] 2022-08-02 11:39
I can reproduce the border blink

<details> 
<summary>Code Sample</summary> 

```dart
import 'package:flutter/material.dart';

import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key, this.dark = true, this.useMaterial3 = true});

  final bool dark;
  final bool useMaterial3;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      themeMode: dark ? ThemeMode.dark : ThemeMode.light,
      theme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.light,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      darkTheme: ThemeData(
        useMaterial3: useMaterial3,
        brightness: Brightness.dark,
        colorSchemeSeed: const Color(0xff6750a4),
      ),
      home: const Example(),
    );
  }
}

class Example extends StatefulWidget {
  const Example({super.key});

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  bool value = false;

  void onClicked() {
    setState(() {
      value = !value;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(12.0),
        child: ListTile(
          onTap: onClicked,
          subtitle: const Text('Subtitle'),
          title: const Text('Title'),
          trailing: Checkbox(
            activeColor: Colors.transparent,
            side: const BorderSide(color: Colors.transparent),
            value: value,
            onChanged: (bool? value) => onClicked(),
            shape: const CircleBorder(),
            splashRadius: 0,
          ),
        ),
      ),
    );
  }
}

``` 
	
</details>

<details> 
<summary>flutter doctor -v</summary> 

```console
[!] Flutter (Channel master, 3.1.0-0.0.pre.2033, on macOS 13.0 22A5311f darwin-arm, locale en-GB)
    • Flutter version 3.1.0-0.0.pre.2033 on channel master at /Users/tahatesser/Code/flutter
    ! Upstream repository git@github.com:NevercodeHQ/flutter.git is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to git@github.com:NevercodeHQ/flutter.git to dismiss this
      error.
    • Framework revision 2d771d4966 (29 minutes ago), 2022-08-02 07:10:07 -0400
    • Engine revision e0b5edc113
    • Dart version 2.19.0 (build 2.19.0-54.0.dev)
    • DevTools version 2.16.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/tahatesser/Code/android-sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/tahatesser/Code/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Build 14A5270f
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.0 22A5311f darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
``` 
	
</details>

**Comment by TahaTesser** [comment] 2022-08-02 13:52
### Investigation

This seems to be caused by `_resolvedSide`which returns `null` when the checkbox isn't selected.
https://github.com/flutter/flutter/blob/2d771d4966b6a8562bd026807fccbbddecf42e2e/packages/flutter/lib/src/material/checkbox.dart#L394-L402


and `_CheckboxPainter` paints a default box when the side is null. 

https://github.com/flutter/flutter/blob/2d771d4966b6a8562bd026807fccbbddecf42e2e/packages/flutter/lib/src/material/checkbox.dart#L647-L648


### Solution

if `Checkbox.side` was a `MaterialStateProperty` like this

https://github.com/flutter/flutter/blob/2d771d4966b6a8562bd026807fccbbddecf42e2e/packages/flutter/lib/src/material/button_style.dart#L221

We could simply return `BorderSide.none` in all `states` such as selected, hovered, etc.
It would look like this:
```dart
            side: MaterialStateProperty.resolveWith((Set<MaterialState> states) {
              return BorderSide.none;
            }),
```

**Comment by TahaTesser** [comment] 2022-08-02 13:57
@Piinks @HansMuller 

I think `Checkbox.side` should be a `MaterialStateProperty` so it can be flexible in cases like this issue, even `Checkbox.shape`, just like `ButtonStyle` has this property as `MaterialStateProperty` for buttons.

Do I have to deprecate the current `side` property to make it a `MaterialStateProperty` property?  Since this might be a breaking change? 

What if we create `ButtonStyle` like a class for toggleable widgets like checkbox, switch, radio. These widgets already share a single class for painting `toggleable.dart`

**Comment by Piinks** [comment] 2022-08-02 14:41
Lopping in @darrenaustin ^ 
He has been working a lot in this area and may have some thoughts on creating continuity here.

**Comment by HansMuller** [comment] 2022-08-04 16:23
@TahaTesser - [MaterialStateBorderSide](https://api.flutter.dev/flutter/material/MaterialStateBorderSide-class.html) can be used in situations where we need to migrate an existing BorderSide property to one that _also_ supports `MaterialStateProperty<BorderSide>`. Doing so doesn't require a breaking change.

I agree that it would nice to have a ToggleStyle class modeled on or maybe derived on ButtonStyle. That would be a BIG change. It would best to focus on a narrowly scoped fix for this issue.

**Comment by TahaTesser** [comment] 2022-08-05 10:01
> @TahaTesser - [MaterialStateBorderSide](https://api.flutter.dev/flutter/material/MaterialStateBorderSide-class.html) can be used in situations where we need to migrate an existing BorderSide property to one that also supports MaterialStateProperty<BorderSide>. Doing so doesn't require a breaking change.

Thanks!


@tonywong586 
As mentioned above `MaterialStateBorderSide.resolveWith` can provided here to return `return BorderSide.none;` when you don't wanna `side` in all checkbox states. Instead of returning `null` which would draw the default side as I mentioned [here](https://github.com/flutter/flutter/issues/108802#issuecomment-1202617821)

```dart
            side: MaterialStateBorderSide.resolveWith(
                (Set<MaterialState> states) {
              return BorderSide.none;
            }),
```

Or 

likewise, you can return a border only in a selected state and `BorderSide.none` in other states.

```dart
            side: MaterialStateBorderSide.resolveWith(
                (Set<MaterialState> states) {
              if (states.contains(MaterialState.selected)) {
                return const BorderSide(color: Colors.red);
              }

              return BorderSide.none;
            }),
```

Try this code sample

<details> 
<summary>Code Sample</summary> 

```dart
import 'package:flutter/material.dart';

class Example extends StatefulWidget {
  const Example({super.key});

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  bool value = false;

  void onClicked() {
    setState(() {
      value = !value;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Sample'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(12.0),
        child: ListTile(
          onTap: onClicked,
          subtitle: const Text('Subtitle'),
          title: const Text('Title'),
          trailing: Checkbox(
            activeColor: Colors.transparent,
            side: MaterialStateBorderSide.resolveWith(
                (Set<MaterialState> states) {
              return BorderSide.none;
            }),
            value: value,
            onChanged: (bool? value) => onClicked(),
            // shape: const CircleBorder(),
            splashRadius: 0,
          ),
        ),
      ),
    );
  }
}

``` 
	
</details>


Closing as resolved.

**Closed by TahaTesser** 2022-08-05 10:01 UTC
Labels: framework, f: material design, has reproducible steps, found in release: 3.1

**Comment by tonywong586** [comment] 2022-08-08 04:04
It works thanks!

> > @TahaTesser - [MaterialStateBorderSide](https://api.flutter.dev/flutter/material/MaterialStateBorderSide-class.html) can be used in situations where we need to migrate an existing BorderSide property to one that also supports MaterialStateProperty. Doing so doesn't require a breaking change.
> 
> Thanks!
> 
> @tonywong586 As mentioned above `MaterialStateBorderSide.resolveWith` can provided here to return `return BorderSide.none;` when you don't wanna `side` in all checkbox states. Instead of returning `null` which would draw the default side as I mentioned [here](https://github.com/flutter/flutter/issues/108802#issuecomment-1202617821)
> 
> ```dart
>             side: MaterialStateBorderSide.resolveWith(
>                 (Set<MaterialState> states) {
>               return BorderSide.none;
>             }),
> ```
> 
> Or
> 
> likewise, you can return a border only in a selected state and `BorderSide.none` in other states.
> 
> ```dart
>             side: MaterialStateBorderSide.resolveWith(
>                 (Set<MaterialState> states) {
>               if (states.contains(MaterialState.selected)) {
>                 return const BorderSide(color: Colors.red);
>               }
> 
>               return BorderSide.none;
>             }),
> ```
> 
> Try this code sample
> 
> Code Sample
> ```dart
> import 'package:flutter/material.dart';
> 
> class Example extends StatefulWidget {
>   const Example({super.key});
> 
>   @override
>   State<Example> createState() => _ExampleState();
> }
> 
> class _ExampleState extends State<Example> {
>   bool value = false;
> 
>   void onClicked() {
>     setState(() {
>       value = !value;
>     });
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('Sample'),
>       ),
>       body: Padding(
>         padding: const EdgeInsets.all(12.0),
>         child: ListTile(
>           onTap: onClicked,
>           subtitle: const Text('Subtitle'),
>           title: const Text('Title'),
>           trailing: Checkbox(
>             activeColor: Colors.transparent,
>             side: MaterialStateBorderSide.resolveWith(
>                 (Set<MaterialState> states) {
>               return BorderSide.none;
>             }),
>             value: value,
>             onChanged: (bool? value) => onClicked(),
>             // shape: const CircleBorder(),
>             splashRadius: 0,
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> Closing as resolved.

It works thanks!
