### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by Surbhi2000312** [flutter/flutter#160359] opened 2024-12-16 17:06 UTC
## Command
```sh
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: No such file or directory, errno = 2
```console
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#4      ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:91:43)
#5      WebDevFS.update (package:flutter_tools/src/isolated/devfs_web.dart:963:57)
#6      ResidentWebRunner._updateDevFS (package:flutter_tools/src/isolated/resident_web_runner.dart:583:56)
<asynchronous suspension>
#7      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:334:41)
<asynchronous suspension>
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
<asynchronous suspension>
```
```console
[33m[!][39m Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale
    en-IN)
    [32m•[39m Flutter version 3.24.5 on channel stable at
      /Users/surbhipaliwal/Documents/flutterdev/sdk/flutter
    [33m![39m Warning: `flutter` on your path resolves to
      /Users/surbhipaliwal/Documents/FlutterDev/sdk/flutter/bin/flutter, which
      is not inside your current Flutter SDK checkout at
      /Users/surbhipaliwal/Documents/flutterdev/sdk/flutter. Consider adding
      /Users/surbhipaliwal/Documents/flutterdev/sdk/flutter/bin to the front of
      your path.
    [33m![39m Warning: `dart` on your path resolves to
      /Users/surbhipaliwal/Documents/FlutterDev/sdk/flutter/bin/dart, which is
      not inside your current Flutter SDK checkout at
      /Users/surbhipaliwal/Documents/flutterdev/sdk/flutter. Consider adding
      /Users/surbhipaliwal/Documents/flutterdev/sdk/flutter/bin to the front of
      your path.
    [32m•[39m Upstream repository https://github.com/flutter/flutter.git
    [32m•[39m Framework revision dec2ee5c1f (5 weeks ago), 2024-11-13 11:13:06 -0800
    [32m•[39m Engine revision a18df97ca5
    [32m•[39m Dart version 3.5.4
    [32m•[39m DevTools version 2.37.3
    [32m•[39m If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    [32m•[39m Android SDK at /Users/surbhipaliwal/Library/Android/sdk
    [32m•[39m Platform android-34, build-tools 34.0.0
    [32m•[39m Java binary at:
      /Users/surbhipaliwal/Library/Java/JavaVirtualMachines/jbr-17.0.12/Contents
      /Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment JBR-17.0.12+1-1207.37-nomod
      (build 17.0.12+1-b1207.37)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 16.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Build 16A242d
    [32m•[39m CocoaPods version 1.16.2

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 2024.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    [32m•[39m Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    [32m•[39m Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[32m[✓][39m Connected device (3 available)
    [32m•[39m macOS (desktop)                 • macos                 • darwin-arm64   •
      macOS 15.1.1 24B91 darwin-arm64
    [32m•[39m Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         •
      macOS 15.1.1 24B91 darwin-arm64
    [32m•[39m Chrome (web)                    • chrome                • web-javascript •
      Google Chrome 131.0.6778.140

[32m[✓][39m Network resources
    [32m•[39m All expected network resources are available.

[33m![39m Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: dec2ee5c1f98f8e84a7d5380c05eb8a3d0a81668

**Comment by chotixity** [comment] 2024-12-16 19:26
This is highly a problem with your code and not the framework itself. You can post the code snippet for help, the steps to reproduce seems to be empty for your submission

**Comment by danagbemava-nc** [comment] 2024-12-17 08:25
Closing this as a duplicate of https://github.com/flutter/flutter/issues/68958

**Closed by danagbemava-nc** 2024-12-17 08:25 UTC
Labels: in triage
