### ISSUE TITLE
Failed to create platform view rendering surface 

### ISSUE THREAD

**Issue by ximmyxiao** [flutter/flutter#88168] opened 2021-08-13 14:12 UTC
When build the projects , it will complains
[VERBOSE-2:platform_view.cc(87)] Failed to create platform view rendering surface

```
 flutter doctor -v :
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.0 21A5304g darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/ximmy/Documents/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ximmy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A5155e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • E73758BD-AF6C-4F2A-9CC8-F4F7EF2B1FBC • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.131

! Doctor found issues in 1 category.
```

**Comment by darshankawar** [comment] 2021-08-16 08:12
Considering the type of error received `[VERBOSE-2:platform_view.cc(87)] Failed to create platform view rendering surface`
and author seems to be trying to run on iOS 15 `com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)`,  this seems to be a duplicate of https://github.com/flutter/flutter/issues/85749.

@ximmyxiao You may follow-up in original issue for further updates. If you think your issue isn't same, write in comments and I'll reopen it.
Thanks.

**Closed by darshankawar** 2021-08-16 08:12 UTC
Labels: in triage

**Comment by ximmyxiao** [comment] 2021-08-17 03:31
thanks ! I didn't know some one had mentioned it earlier
